TrioCFD: Champ_Input_P0_Composite Class Reference
Champ_Input_P0_Composite Class Reference
#include <Champ_Input_P0_Composite.h>
Public Member Functions
double changer_temps (const double t) override
const Nom & fixer_unite (const Nom &unit) override
const Nom & fixer_unite (int i, const Nom &unit) override
const Type_info * get_info () const override
int initialiser (const double t) override
virtual DoubleTab & valeurs ()=0
Public Member Functions inherited from Champ_Fonc_P0_base
const Type_info * get_info () const override
DoubleTab & remplir_coord_noeuds (DoubleTab &positions) const override
int remplir_coord_noeuds_et_polys (DoubleTab &positions, IntVect &polys) const override
Public Member Functions inherited from Champ_Fonc_base
Champ_base & affecter_ (const Champ_base &) override
Champ_base & affecter_compo (const Champ_base &, int compo) override
int fixer_nb_valeurs_nodales (int nb_noeuds) override
const Type_info * get_info () const override
void mettre_a_jour (double temps) override
virtual DoubleTab & remplir_coord_noeuds (DoubleTab &) const
virtual DoubleTab & remplir_coord_noeuds_compo (DoubleTab &, int) const
virtual int remplir_coord_noeuds_et_polys (DoubleTab &, IntVect &) const
virtual int remplir_coord_noeuds_et_polys_compo (DoubleTab &, IntVect &, int) const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
DoubleTab & valeur_aux (const DoubleTab &, DoubleTab &) const override
Public Member Functions inherited from Champ_Don_base
void dimensionner (int, int)
int fixer_nb_valeurs_nodales (int nb_noeuds) override
const Type_info * get_info () const override
int imprime (Sortie &, int) const override
virtual int initialiser (const double temps)
void mettre_a_jour (double temps) override
int reprendre (Entree &) override
void resetTime (double time) override
int sauvegarder (Sortie &) const override
DoubleTab & valeurs () override
Public Member Functions inherited from Champ_base
Champ_base & affecter (const Champ_base &)
Champ_base ()
virtual double changer_temps (const double t)
const Type_info * get_info () const override
double temps () const
virtual DoubleTab & trace (const Frontiere_dis_base &, DoubleTab &, double, int distant) const
virtual DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const
virtual double valeur_a_compo (const DoubleVect &position, int ncomp) const
virtual DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &valeurs, int le_poly) const
virtual double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const
virtual DoubleVect & valeur_a_sommet (int, const Domaine &, DoubleVect &) const
virtual DoubleTab & valeur_aux (const DoubleTab &positions, DoubleTab &valeurs) const
virtual DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const
virtual DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const
virtual DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp) const
Public Member Functions inherited from Field_base
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
virtual void fixer_nb_comp (int i)
virtual const Nom & fixer_nom_compo (const Nom &)
virtual const Nom & fixer_nom_compo (int, const Nom &)
virtual const Noms & fixer_noms_compo (const Noms &)
virtual const Nom & fixer_unite (const Nom &)
virtual const Nom & fixer_unite (int i, const Nom &)
virtual const Noms & fixer_unites (const Noms &)
const Type_info * get_info () const override
const Nom & nom_compo (int) const
void nommer (const Nom &) override
const Nom & unite () const
const Nom & unite (int) const
const Noms & unites () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Champ_Proto
int lire_dimension (Entree &, const Nom &)
int lire_dimension (int dim, const Nom &le_nom_)
Public Member Functions inherited from Champ_implementation_P0
DoubleTab & valeur_aux_centres_de_gravite (const Domaine &, DoubleTab &valeurs) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Champ_Fonc_P0_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Champ_Fonc_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Field_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Champ_Input_P0_Composite()
Champ_Input_P0_Composite::Champ_Input_P0_Composite ()
~Champ_Input_P0_Composite()
Champ_Input_P0_Composite::~Champ_Input_P0_Composite ()
Member Function Documentation
cree_instance()
Objet_U * Champ_Input_P0_Composite::cree_instance () static
taille_memoire()
unsigned Champ_Input_P0_Composite::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Champ_Input_P0_Composite::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Champ_Input_P0_Composite::info () static
get_info()
const Type_info * Champ_Input_P0_Composite::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
Champ_Input_P0_Composite & Champ_Input_P0_Composite::self_cast (Objet_U & r) static
self_cast() [2/2]
const Champ_Input_P0_Composite & Champ_Input_P0_Composite::self_cast (const Objet_U & r) static
printOn()
Sortie & Champ_Input_P0_Composite::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
readOn()
Entree & Champ_Input_P0_Composite::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
References Param::ajouter(), Objet_U_ptr::detach(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Probleme_base::discretisation(), Discretisation_base::discretiser_champ(), domaine_dis_base(), Process::exit(), is_initialized(), Param::lire_avec_accolades_depuis(), Field_base::nb_comp(), Objet_U::que_suis_je(), Param::REQUIRED, TRUST_Deriv< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), and Champ_Input_Proto::z_probleme().
is_initialized()
bool Champ_Input_P0_Composite::is_initialized () inline
References Objet_U_ptr::non_nul().
Referenced by readOn().
initial_values()
const DoubleTab & Champ_Input_P0_Composite::initial_values () inline
References Champ_Don_base::valeurs().
input_field()
Champ_input_P0 & Champ_Input_P0_Composite::input_field () inline
valeurs() [1/6]
DoubleTab & Champ_Input_P0_Composite::valeurs () inline override virtual
Implements Champ_Proto.
References Champ_Don_base::valeurs().
valeurs() [2/6]
const DoubleTab & Champ_Input_P0_Composite::valeurs () const inline override virtual
Implements Champ_Proto.
References Champ_Don_base::valeurs().
mettre_a_jour()
void Champ_Input_P0_Composite::mettre_a_jour (double) inline override virtual
mettre_a_jour de la classe de base Champ_base :ne fait rien !
Reimplemented from Champ_base.
initialiser()
int Champ_Input_P0_Composite::initialiser (const double un_temps) inline override virtual
NE FAIT RIEN.
A surcharger dans les classes derivees. Provoque l'initialisation du champ si necessaire
Reimplemented from Champ_Don_base.
References Champ_Don_base::initialiser().
changer_temps()
double Champ_Input_P0_Composite::changer_temps (const double t) inline override virtual
Fixe le temps auquel se situe le champ.
Parameters
(double& t) le nouveau temps auquel se situe le champ
Returns
(double) le nouveau temps auquel se situe le champ
Reimplemented from Champ_base.
References Champ_base::changer_temps().
fixer_unite() [1/2]
const Nom & Champ_Input_P0_Composite::fixer_unite (const Nom & nom) inline override virtual
Specifie l'unite d'un champ scalaire ou dont toutes les composantes ont la meme unite.
Parameters
(Nom& nom) l'unite a specifier
Returns
(Nom&) l'unite du champ
Reimplemented from Field_base.
References Field_base::fixer_unite().
fixer_unite() [2/2]
const Nom & Champ_Input_P0_Composite::fixer_unite (int i, const Nom & nom) inline override virtual
Specifie l'unite de la i-eme composante du champ Signification: l'index de la composante du champ dont on veut specifier l'unite.
Parameters
(Nom& nom) le type de l'unite a specifier
Returns
(Nom&) le type de l'unite de la i-eme composante du champ
Reimplemented from Field_base.
References Field_base::fixer_unite().
associer_domaine_dis_base()
void Champ_Input_P0_Composite::associer_domaine_dis_base (const Domaine_dis_base & zdb) inline override virtual
Reimplemented from Champ_base.
References Champ_Fonc_base::associer_domaine_dis_base().
domaine_dis_base()
const Domaine_dis_base & Champ_Input_P0_Composite::domaine_dis_base () const inline override virtual
Reimplemented from Champ_base.
References Champ_Fonc_base::domaine_dis_base().
Referenced by readOn().
getTemplate()
void Champ_Input_P0_Composite::getTemplate (TrioField & afield) const inline
References Champ_input_P0::getTemplate().
setValue()
void Champ_Input_P0_Composite::setValue (const TrioField & afield) inline
References Champ_input_P0::setValue().
setDoubleValue()
void Champ_Input_P0_Composite::setDoubleValue (const double val) inline
References Champ_Input_Proto::setDoubleValue().
valeurs() [3/6]
virtual DoubleTab & Champ_Proto::valeurs () virtual
Surcharge Champ_base::valeurs() Renvoie le tableau des valeurs.
Returns
(DoubleTab&) le tableau des valeurs du champs
Reimplemented from Champ_Don_base.
valeurs() [4/6]
virtual const DoubleTab & Champ_Proto::valeurs () const virtual
Reimplemented from Champ_Don_base.
valeurs() [5/6]
virtual DoubleTab & Champ_Proto::valeurs (double temps) inline virtual
Reimplemented from Champ_Proto.
valeurs() [6/6]
virtual const DoubleTab & Champ_Proto::valeurs (double temps) const inline virtual
Reimplemented from Champ_Proto.
Member Data Documentation
info_obj
const Type_info Champ_Input_P0_Composite::info_obj static