TrioCFD: TRUSTProblem_Concentration_Gen< _DERIVED_TYPE_, _EQUATION_TYPE_, _MEDIUM_TYPE_ > Class Template Reference
TRUSTProblem_Concentration_Gen< _DERIVED_TYPE_, _EQUATION_TYPE_, _MEDIUM_TYPE_ > Class Template Reference
#include <TRUSTProblem_Concentration_Gen.h>
Member Function Documentation
printOn()
template<typename _DERIVED_TYPE_ , typename _EQUATION_TYPE_ , typename _MEDIUM_TYPE_ > Sortie & TRUSTProblem_Concentration_Gen< _DERIVED_TYPE_, _EQUATION_TYPE_, _MEDIUM_TYPE_ >::printOn (Sortie & os) const inline override protected
nb_equations_multi() [1/2]
template<typename _DERIVED_TYPE_ , typename _EQUATION_TYPE_ , typename _MEDIUM_TYPE_ > int TRUSTProblem_Concentration_Gen< _DERIVED_TYPE_, _EQUATION_TYPE_, _MEDIUM_TYPE_ >::nb_equations_multi () inline protected
References TRUSTProblem_Concentration_Gen< _DERIVED_TYPE_, _EQUATION_TYPE_, _MEDIUM_TYPE_ >::list_eq_concentration_, and TRUST_List< _CLASSE_ >::size().
Referenced by TRUSTProblem_Concentration_Gen< _DERIVED_TYPE_, _EQUATION_TYPE_, _MEDIUM_TYPE_ >::nombre_d_equations().
nb_equations_multi() [2/2]
template<typename _DERIVED_TYPE_ , typename _EQUATION_TYPE_ , typename _MEDIUM_TYPE_ > int TRUSTProblem_Concentration_Gen< _DERIVED_TYPE_, _EQUATION_TYPE_, _MEDIUM_TYPE_ >::nb_equations_multi () const inline protected
References TRUSTProblem_Concentration_Gen< _DERIVED_TYPE_, _EQUATION_TYPE_, _MEDIUM_TYPE_ >::list_eq_concentration_, and TRUST_List< _CLASSE_ >::size().
nombre_d_equations()
template<typename _DERIVED_TYPE_ , typename _EQUATION_TYPE_ , typename _MEDIUM_TYPE_ > int TRUSTProblem_Concentration_Gen< _DERIVED_TYPE_, _EQUATION_TYPE_, _MEDIUM_TYPE_ >::nombre_d_equations () const inline override
References TRUSTProblem_Concentration_Gen< _DERIVED_TYPE_, _EQUATION_TYPE_, _MEDIUM_TYPE_ >::nb_equations_multi().
Referenced by TRUSTProblem_Concentration_Gen< _DERIVED_TYPE_, _EQUATION_TYPE_, _MEDIUM_TYPE_ >::equation().
equation() [1/2]
template<typename _DERIVED_TYPE_ , typename _EQUATION_TYPE_ , typename _MEDIUM_TYPE_ > const Equation_base & TRUSTProblem_Concentration_Gen< _DERIVED_TYPE_, _EQUATION_TYPE_, _MEDIUM_TYPE_ >::equation (int i) const inline override
References Process::exit(), TRUSTProblem_Concentration_Gen< _DERIVED_TYPE_, _EQUATION_TYPE_, _MEDIUM_TYPE_ >::list_eq_concentration_, and TRUSTProblem_Concentration_Gen< _DERIVED_TYPE_, _EQUATION_TYPE_, _MEDIUM_TYPE_ >::nombre_d_equations().
equation() [2/2]
template<typename _DERIVED_TYPE_ , typename _EQUATION_TYPE_ , typename _MEDIUM_TYPE_ > Equation_base & TRUSTProblem_Concentration_Gen< _DERIVED_TYPE_, _EQUATION_TYPE_, _MEDIUM_TYPE_ >::equation (int i) inline override
References Process::exit(), TRUSTProblem_Concentration_Gen< _DERIVED_TYPE_, _EQUATION_TYPE_, _MEDIUM_TYPE_ >::list_eq_concentration_, and TRUSTProblem_Concentration_Gen< _DERIVED_TYPE_, _EQUATION_TYPE_, _MEDIUM_TYPE_ >::nombre_d_equations().
rename_equation_unknown()
template<typename _DERIVED_TYPE_ , typename _EQUATION_TYPE_ , typename _MEDIUM_TYPE_ > void TRUSTProblem_Concentration_Gen< _DERIVED_TYPE_, _EQUATION_TYPE_, _MEDIUM_TYPE_ >::rename_equation_unknown (const int i, _EQUATION_TYPE_ & eqn) inline
References TRUSTProblem_Concentration_Gen< _DERIVED_TYPE_, _EQUATION_TYPE_, _MEDIUM_TYPE_ >::nb_consts_, and Objet_U::que_suis_je().
lire_resize_medium()
template<typename _DERIVED_TYPE_ , typename _EQUATION_TYPE_ , typename _MEDIUM_TYPE_ > Entree & TRUSTProblem_Concentration_Gen< _DERIVED_TYPE_, _EQUATION_TYPE_, _MEDIUM_TYPE_ >::lire_resize_medium (Entree & is) inline
References Constituant::diffusivite_constituant(), Process::exit(), TRUSTProblem_Concentration_Gen< _DERIVED_TYPE_, _EQUATION_TYPE_, _MEDIUM_TYPE_ >::mil_constituants_, Constituant::nb_constituants(), TRUSTProblem_Concentration_Gen< _DERIVED_TYPE_, _EQUATION_TYPE_, _MEDIUM_TYPE_ >::nb_consts_, and Objet_U::que_suis_je().
create_constituants_echaines()
template<typename _DERIVED_TYPE_ , typename _EQUATION_TYPE_ , typename _MEDIUM_TYPE_ > void TRUSTProblem_Concentration_Gen< _DERIVED_TYPE_, _EQUATION_TYPE_, _MEDIUM_TYPE_ >::create_constituants_echaines () inline
References Constituant::diffusivite_constituant(), TRUSTProblem_Concentration_Gen< _DERIVED_TYPE_, _EQUATION_TYPE_, _MEDIUM_TYPE_ >::mil_constituants_, TRUSTProblem_Concentration_Gen< _DERIVED_TYPE_, _EQUATION_TYPE_, _MEDIUM_TYPE_ >::nb_consts_, and Champ_Don_base::valeurs().
Member Data Documentation
mil_constituants_
template<typename _DERIVED_TYPE_ , typename _EQUATION_TYPE_ , typename _MEDIUM_TYPE_ > std::vector<_MEDIUM_TYPE_> TRUSTProblem_Concentration_Gen< _DERIVED_TYPE_, _EQUATION_TYPE_, _MEDIUM_TYPE_ >::mil_constituants_ protected
Referenced by TRUSTProblem_Concentration_Gen< _DERIVED_TYPE_, _EQUATION_TYPE_, _MEDIUM_TYPE_ >::create_constituants_echaines(), and TRUSTProblem_Concentration_Gen< _DERIVED_TYPE_, _EQUATION_TYPE_, _MEDIUM_TYPE_ >::lire_resize_medium().
list_eq_concentration_
template<typename _DERIVED_TYPE_ , typename _EQUATION_TYPE_ , typename _MEDIUM_TYPE_ > TRUST_List< _EQUATION_TYPE_ > TRUSTProblem_Concentration_Gen< _DERIVED_TYPE_, _EQUATION_TYPE_, _MEDIUM_TYPE_ >::list_eq_concentration_ protected
Referenced by TRUSTProblem_Concentration_Gen< _DERIVED_TYPE_, _EQUATION_TYPE_, _MEDIUM_TYPE_ >::equation(), and TRUSTProblem_Concentration_Gen< _DERIVED_TYPE_, _EQUATION_TYPE_, _MEDIUM_TYPE_ >::nb_equations_multi().
nb_consts_
template<typename _DERIVED_TYPE_ , typename _EQUATION_TYPE_ , typename _MEDIUM_TYPE_ > int TRUSTProblem_Concentration_Gen< _DERIVED_TYPE_, _EQUATION_TYPE_, _MEDIUM_TYPE_ >::nb_consts_ = -123 protected
Referenced by TRUSTProblem_Concentration_Gen< _DERIVED_TYPE_, _EQUATION_TYPE_, _MEDIUM_TYPE_ >::create_constituants_echaines(), TRUSTProblem_Concentration_Gen< _DERIVED_TYPE_, _EQUATION_TYPE_, _MEDIUM_TYPE_ >::lire_resize_medium(), and TRUSTProblem_Concentration_Gen< _DERIVED_TYPE_, _EQUATION_TYPE_, _MEDIUM_TYPE_ >::rename_equation_unknown().