TrioCFD: Champ_front_var_instationnaire Class Reference
Champ_front_var_instationnaire Class Reference
#include <Champ_front_var_instationnaire.h>
Public Member Functions
int avancer (double temps) override
const Type_info * get_info () const override
int initialiser (double temps, const Champ_Inc_base &inco) override
int reculer (double temps) override
const DoubleTab & valeurs_au_temps (double temps) const override
DoubleTab & valeurs_au_temps (double temps) override
const Type_info * get_info () const override
int initialiser (double temps, const Champ_Inc_base &inco) override
Public Member Functions inherited from Champ_front_base
virtual void associer_fr_dis_base (const Frontiere_dis_base &)
virtual int avancer (double temps)
virtual void calculer_coeffs_echange (double temps)
virtual void fixer_nb_valeurs_temporelles (int nb_cases)
virtual Frontiere_dis_base & frontiere_dis ()
virtual const Frontiere_dis_base & frontiere_dis () const
const Type_info * get_info () const override
virtual int initialiser (double temps, const Champ_Inc_base &inco)
virtual void mettre_a_jour (double temps)
virtual int reculer (double temps)
virtual const DoubleTab & valeurs () const override
virtual DoubleTab & valeurs () override
virtual void valeurs_face (int, DoubleVect &) const
Public Member Functions inherited from Field_base
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
virtual void fixer_nb_comp (int i)
virtual const Nom & fixer_nom_compo (const Nom &)
virtual const Nom & fixer_nom_compo (int, const Nom &)
virtual const Noms & fixer_noms_compo (const Noms &)
virtual const Nom & fixer_unite (const Nom &)
virtual const Nom & fixer_unite (int i, const Nom &)
virtual const Noms & fixer_unites (const Noms &)
const Type_info * get_info () const override
const Nom & nom_compo (int) const
void nommer (const Nom &) override
const Nom & unite () const
const Nom & unite (int) const
const Noms & unites () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Champ_Proto
int lire_dimension (Entree &, const Nom &)
int lire_dimension (int dim, const Nom &le_nom_)
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Field_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
frontieres variables en espace et dans le temps.
Les Champ_front_var_instationnaire sont classes suivant que
leurs valeurs dependent ou non de parametres externes a
l'equation, en Champ_front_var_instationnaire_indep et
Champ_front_var_instationnaire_dep.
L'implementation du calcul du champ doit se faire dans la
methode mettre_a_jour.
Dans le premier cas (indep), la methode initialiser peut
appeler la methode mettre_a_jour, mais pas dans le second cas
(dep). Elle peut de toutes facons utiliser l'inconnue qui lui
est passee en parametre comme une premiere estimation.
See also
Champ_front_var
Constructor & Destructor Documentation
Champ_front_var_instationnaire()
Champ_front_var_instationnaire::Champ_front_var_instationnaire ()
~Champ_front_var_instationnaire()
Champ_front_var_instationnaire::~Champ_front_var_instationnaire () override
Member Function Documentation
info()
const Type_info * Champ_front_var_instationnaire::info () static
get_info()
const Type_info * Champ_front_var_instationnaire::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Champ_front_var.
Reimplemented in Ch_front_input_ALE, Champ_front_ALE, Champ_front_ALE_Beam, Champ_front_ALE_projection, Champ_front_contact_rayo_transp_VEF, Champ_front_rayonnement, Champ_front_contact_rayo_semi_transp_VEF, Boundary_field_keps_from_ud, Champ_front_MED, Champ_front_recyclage, Champ_front_pression_from_u, Champ_front_synt, Champ_front_debit_QC, Champ_front_debit_QC_fonc_t, Champ_front_fonc_gradient_VDF, Champ_front_contact_fictif_VEF, Champ_front_contact_VEF, Champ_front_fonc_gradient_VEF, and Champ_front_tangentiel_VEF.
self_cast() [1/2]
Champ_front_var_instationnaire & Champ_front_var_instationnaire::self_cast (Objet_U & r) static
self_cast() [2/2]
const Champ_front_var_instationnaire & Champ_front_var_instationnaire::self_cast (const Objet_U & r) static
printOn()
Sortie & Champ_front_var_instationnaire::printOn (Sortie & s) const override protected virtual
Imprime le nom du champ sur un flot de sortie.
Parameters
(Sortie& s) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Champ_front_var.
Reimplemented in Ch_front_input_ALE, Champ_front_ALE, Champ_front_ALE_Beam, Champ_front_ALE_projection, Champ_front_contact_rayo_transp_VEF, Champ_front_rayonnement, Champ_front_contact_rayo_semi_transp_VEF, Boundary_field_keps_from_ud, Champ_front_MED, Champ_front_recyclage, Champ_front_pression_from_u, Champ_front_synt, Champ_front_debit_QC, Champ_front_debit_QC_fonc_t, Champ_front_fonc_gradient_VDF, Champ_front_contact_fictif_VEF, Champ_front_contact_VEF, Champ_front_fonc_gradient_VEF, and Champ_front_tangentiel_VEF.
References Field_base::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Champ_front_var_instationnaire::readOn (Entree & s) override protected virtual
NE FAIT RIEN A surcharger dans les classes derivees.
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Champ_front_var.
Reimplemented in Ch_front_input_ALE, Champ_front_ALE, Champ_front_ALE_Beam, Champ_front_ALE_projection, Champ_front_contact_rayo_transp_VEF, Champ_front_rayonnement, Champ_front_contact_rayo_semi_transp_VEF, Boundary_field_keps_from_ud, Champ_front_MED, Champ_front_recyclage, Champ_front_pression_from_u, Champ_front_synt, Champ_front_debit_QC, Champ_front_debit_QC_fonc_t, Champ_front_fonc_gradient_VDF, Champ_front_contact_fictif_VEF, Champ_front_contact_VEF, Champ_front_fonc_gradient_VEF, and Champ_front_tangentiel_VEF.
fixer_nb_valeurs_temporelles()
void Champ_front_var_instationnaire::fixer_nb_valeurs_temporelles (int nb_cases) override virtual
Surcharge Champ_front_base::fixer_nb_valeurs_temporelles.
Reimplemented from Champ_front_base.
References Roue::fixer_nb_cases(), and Champ_front_base::les_valeurs.
Referenced by Echange_contact_VDF_FT_Disc::completer(), Echange_contact_VDF_FT_Disc_solid::completer(), and Champ_front_xyz_debit::fixer_nb_valeurs_temporelles().
initialiser()
int Champ_front_var_instationnaire::initialiser (double temps, const Champ_Inc_base & inco) override virtual
Initialise le temps courant et Gpoint.
Parameters
(double tps) le temps de mise a jour
Reimplemented from Champ_front_var.
Reimplemented in Ch_front_input_ALE, Champ_front_ALE, Champ_front_contact_rayo_transp_VEF, Champ_front_contact_rayo_semi_transp_VEF, Boundary_field_keps_from_ud, Champ_front_recyclage, Champ_front_pression_from_u, Champ_front_synt, Champ_front_contact_VEF, and Champ_front_tangentiel_VEF.
References Champ_front_base::changer_temps_futur(), Champ_front_var::initialiser(), Champ_front_base::set_instationnaire(), and Champ_front_base::temps_defaut.
Referenced by Ch_front_Vortex::initialiser(), Champ_Front_Fonction::initialiser(), Ch_front_var_instationnaire_dep::initialiser(), and Ch_front_var_instationnaire_indep::initialiser().
has_valeurs_au_temps()
bool Champ_front_var_instationnaire::has_valeurs_au_temps (double temps) const override virtual
Reimplemented from Champ_front_base.
References Champ_front_base::les_valeurs, Roue::nb_cases(), TRUSTVect< _TYPE_, _SIZE_ >::size(), and Roue::valeurs().
valeurs_au_temps() [1/2]
DoubleTab & Champ_front_var_instationnaire::valeurs_au_temps (double temps) override virtual
Renvoie les valeurs au temps desire.
Sinon, sort en erreur.
Implements Champ_front_base.
References Process::exit(), Champ_front_base::les_valeurs, Roue::nb_cases(), and Champ_front_base::valeurs().
Referenced by Champ_front_MED::affecter_(), Champ_front_contact_rayo_transp_VEF::calculer_temperature_bord(), Champ_front_contact_rayo_semi_transp_VEF::calculer_temperature_bord(), Echange_contact_Rayo_transp_VDF::calculer_Teta_paroi(), Ch_front_input_ALE::mettre_a_jour(), Champ_front_ALE::mettre_a_jour(), Champ_front_bruite::mettre_a_jour(), Champ_front_calc::mettre_a_jour(), Champ_front_calc_interne::mettre_a_jour(), Champ_Front_Fonction::mettre_a_jour(), Champ_front_t::mettre_a_jour(), Champ_front_txyz::mettre_a_jour(), Champ_front_xyz_debit::mettre_a_jour(), Champ_Front_xyz_Tabule::mettre_a_jour(), Champ_front_MED::mettre_a_jour(), Champ_front_recyclage::mettre_a_jour(), Champ_front_synt::mettre_a_jour(), Champ_front_debit_QC_fonc_t::mettre_a_jour(), Champ_front_contact_VEF::mettre_a_jour(), Champ_front_fonc_gradient_VEF::mettre_a_jour(), Champ_front_fonc_gradient_VDF::mettre_a_jour(), and Champ_front_contact_VEF::verifier_scalaire_bord().
valeurs_au_temps() [2/2]
const DoubleTab & Champ_front_var_instationnaire::valeurs_au_temps (double temps) const override virtual
Renvoie les valeurs au temps desire.
Sinon, sort en erreur.
Implements Champ_front_base.
References Process::exit(), Champ_front_base::les_valeurs, Roue::nb_cases(), and Champ_front_base::valeurs().
avancer()
int Champ_front_var_instationnaire::avancer (double temps) override virtual
Avance jusqu'au temps desire.
Sinon, sort en erreur.
Reimplemented from Champ_front_base.
References Process::exit(), Champ_front_base::les_valeurs, Roue::nb_cases(), and Roue::temps().
Referenced by Champ_front_xyz_debit::avancer().
reculer()
int Champ_front_var_instationnaire::reculer (double temps) override virtual
Recule jusqu'au temps desire.
Sinon, sort en erreur.
Reimplemented from Champ_front_base.
References Process::exit(), Champ_front_base::les_valeurs, and Roue::nb_cases().
Referenced by Champ_front_xyz_debit::reculer().
valeur_au_temps_et_au_point()
virtual double Champ_front_var_instationnaire::valeur_au_temps_et_au_point (double temps, int som, double x, double y, double z, int comp) const inline virtual
Reimplemented in Champ_front_txyz, Champ_Front_xyz_Tabule, Ch_front_input_P1, and Champ_front_MED.
References Process::exit().
Referenced by Domaine_Cl_EF::imposer_cond_lim().
valeur_au_temps_et_au_point_disponible()
virtual int Champ_front_var_instationnaire::valeur_au_temps_et_au_point_disponible () const inline virtual
Reimplemented in Champ_front_t, Champ_front_txyz, and Ch_front_input_P1.
Referenced by Domaine_Cl_EF::imposer_cond_lim().
Member Data Documentation
info_obj
const Type_info Champ_front_var_instationnaire::info_obj static