TrioCFD: Interface_base Class Reference
Interface_base Class Reference abstract
#include <Interface_base.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Interface_base()
Interface_base::Interface_base ()
~Interface_base()
Interface_base::~Interface_base () override
Member Function Documentation
info()
const Type_info * Interface_base::info () static
get_info()
const Type_info * Interface_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
Reimplemented in Saturation_eau_c3, Saturation_R12_c1, Interface_sigma_constant, Saturation_base, Saturation_constant, Saturation_sodium, Saturation_generique_CoolProp, Saturation_generique_EOS, and Saturation_generique_TPPI_base.
self_cast() [1/2]
Interface_base & Interface_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Interface_base & Interface_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Interface_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
Reimplemented in Saturation_eau_c3, Saturation_R12_c1, Interface_sigma_constant, Saturation_base, Saturation_constant, Saturation_sodium, Saturation_generique_CoolProp, Saturation_generique_EOS, and Saturation_generique_TPPI_base.
readOn()
Entree & Interface_base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
Reimplemented in Saturation_eau_c3, Saturation_R12_c1, Interface_sigma_constant, Saturation_base, Saturation_constant, Saturation_sodium, Saturation_generique_CoolProp, Saturation_generique_EOS, and Saturation_generique_TPPI_base.
References Param::lire_avec_accolades_depuis(), Objet_U::que_suis_je(), and set_param().
Referenced by Interface_sigma_constant::readOn().
set_param()
void Interface_base::set_param (Param & param) virtual
Reimplemented in Saturation_base, Saturation_generique_CoolProp, and Saturation_generique_EOS.
References Param::ajouter(), and sigma__.
Referenced by readOn(), and Saturation_base::set_param().
mettre_a_jour()
void Interface_base::mettre_a_jour (double temps) virtual
Reimplemented in Saturation_base.
References ch_sigma_, TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Pb_Multiphase::equation_energie(), Pb_Multiphase::equation_qdm(), TRUSTVect< _TYPE_, _SIZE_ >::get_span(), Equation_base::inconnue(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), pb_, sigma(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), and Champ_Inc_base::valeurs().
Referenced by Milieu_composite::mettre_a_jour().
assoscier_pb()
void Interface_base::assoscier_pb (const Probleme_base & pb) inline
References pb_.
Referenced by Milieu_composite::discretiser().
get_sigma_champ() [1/2]
Champ_Don_base & Interface_base::get_sigma_champ () inline
References ch_sigma_.
Referenced by Milieu_composite::discretiser().
get_sigma_champ() [2/2]
const Champ_Don_base & Interface_base::get_sigma_champ () const inline
References ch_sigma_.
discretiser_sigma()
void Interface_base::discretiser_sigma (const Nom & sig_nom, double temps)
References ch_sigma_, Discretisation_base::discretiser_champ(), and pb_.
Referenced by Milieu_composite::discretiser().
get_sigma_tab() [1/2]
DoubleTab & Interface_base::get_sigma_tab () inline
References ch_sigma_, and Champ_Don_base::valeurs().
Referenced by Coalescence_bulles_2groupes_PolyMAC_P0::ajouter_blocs(), Flux_2groupes_PolyMAC_P0::ajouter_blocs(), Rupture_bulles_2groupes_PolyMAC_P0::ajouter_blocs(), Correction_Tomiyama_PolyMAC_P0::ajouter_blocs(), Dispersion_bulles_PolyMAC_P0::ajouter_blocs(), Frottement_interfacial_PolyMAC_P0::ajouter_blocs(), Portance_interfaciale_PolyMAC_P0::ajouter_blocs(), Perte_Charge_PolyMAC::ajouter_blocs(), Dispersion_bulles_VDF::ajouter_blocs(), Frottement_interfacial_VDF::ajouter_blocs(), Portance_interfaciale_VDF::ajouter_blocs(), Perte_Charge_VDF_base::ajouter_blocs(), Correction_Lubchenko_PolyMAC_P0::ajouter_blocs_disp(), Portance_interfaciale_PolyMAC_P0::mettre_a_jour(), and Aire_interfaciale::mettre_a_jour().
get_sigma_tab() [2/2]
const DoubleTab & Interface_base::get_sigma_tab () const inline
References ch_sigma_, and Champ_Don_base::valeurs().
sigma() [1/2]
double Interface_base::sigma (const double T, const double P) const
Referenced by Coalescence_bulles_1groupe_PolyMAC_P0::ajouter_blocs(), Coalescence_bulles_2groupes_PolyMAC_P0::ajouter_blocs(), Flux_2groupes_PolyMAC_P0::ajouter_blocs(), Rupture_bulles_1groupe_PolyMAC_P0::ajouter_blocs(), Rupture_bulles_2groupes_PolyMAC_P0::ajouter_blocs(), Dissipation_WIT_PolyMAC_P0::ajouter_blocs(), Production_HZDR_PolyMAC_P0::ajouter_blocs(), Source_Dissipation_HZDR_PolyMAC_P0::ajouter_blocs(), Dispersion_bulles_PolyMAC_P0::ajouter_blocs(), Portance_interfaciale_PolyMAC_P0::ajouter_blocs(), Op_Evanescence_Homogene_Face_base::ajouter_blocs(), Dispersion_bulles_VDF::ajouter_blocs(), Frottement_interfacial_VDF::ajouter_blocs(), Portance_interfaciale_VDF::ajouter_blocs(), Op_Evanescence_Homogene_PolyMAC_P0_Face::ajouter_blocs_aux(), Correction_Lubchenko_PolyMAC_P0::ajouter_blocs_disp(), Correction_Lubchenko_PolyMAC_P0::ajouter_blocs_lift(), Portance_interfaciale_PolyMAC_P0::mettre_a_jour(), Aire_interfaciale::mettre_a_jour(), mettre_a_jour(), and Saturation_base::mettre_a_jour().
sigma() [2/2]
void Interface_base::sigma (const SpanD T, const SpanD P, SpanD res, int ncomp = 1, int ind = 0) const
References sigma_(), and sigma__.
sigma_h() [1/2]
double Interface_base::sigma_h (const double h, const double P) const
Referenced by Dispersion_bulles_PolyMAC_P0::ajouter_blocs(), Op_Evanescence_Homogene_Face_base::ajouter_blocs(), Dispersion_bulles_VDF::ajouter_blocs(), Frottement_interfacial_VDF::ajouter_blocs(), Portance_interfaciale_VDF::ajouter_blocs(), and Op_Evanescence_Homogene_PolyMAC_P0_Face::ajouter_blocs_aux().
sigma_h() [2/2]
void Interface_base::sigma_h (const SpanD H, const SpanD P, SpanD res, int ncomp = 1, int ind = 0) const
References sigma__, and sigma_h_().
sigma_()
virtual void Interface_base::sigma_ (const SpanD T, const SpanD P, SpanD res, int ncomp = 1, int ind = 0) const protected pure virtual
Implemented in Saturation_generique_TPPI_base.
Referenced by Saturation_base::get_sigma(), and sigma().
sigma_h_()
virtual void Interface_base::sigma_h_ (const SpanD H, const SpanD P, SpanD res, int ncomp = 1, int ind = 0) const protected pure virtual
Implemented in Saturation_generique_TPPI_base.
Referenced by Saturation_base::get_sigma_h(), and sigma_h().
Member Data Documentation
info_obj
const Type_info Interface_base::info_obj static
pb_
TRUST_Ref< Probleme_base *> Interface_base::pb_ protected
Referenced by assoscier_pb(), discretiser_sigma(), Saturation_base::discretiser_Tsat(), mettre_a_jour(), and Saturation_base::mettre_a_jour().
ch_sigma_
TRUST_Deriv< Champ_Don_base > Interface_base::ch_sigma_ protected
Referenced by discretiser_sigma(), get_sigma_champ(), get_sigma_tab(), mettre_a_jour(), and Saturation_base::mettre_a_jour().
sigma__
double Interface_base::sigma__ = -1. protected
Referenced by Saturation_constant::readOn(), set_param(), sigma(), and sigma_h().