TrioCFD: Op_Diff_PolyMAC_base Class Reference
Op_Diff_PolyMAC_base Class Reference
#include <Op_Diff_PolyMAC_base.h>
Public Member Functions
double calculer_dt_stab () const override
void completer () override
const Type_info * get_info () const override
void mettre_a_jour (double t) override
Public Member Functions inherited from Op_Diff_PolyMAC_Gen_base
const Type_info * get_info () const override
int impr (Sortie &os) const override
Public Member Functions inherited from Operateur_Diff_base
virtual void associer_diffusivite_pour_pas_de_temps (const Champ_base &)
const Type_info * get_info () const override
Public Member Functions inherited from Operateur_base
void associer_eqn (const Equation_base &)
virtual double calculer_dt_stab () const
virtual void completer ()
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual void mettre_a_jour (double temps)
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Op_Diff_PolyMAC_Gen_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Operateur_Diff_base
virtual const Champ_base & diffusivite_pour_pas_de_temps () const
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Op_Diff_PolyMAC_base()
Op_Diff_PolyMAC_base::Op_Diff_PolyMAC_base ()
~Op_Diff_PolyMAC_base()
Op_Diff_PolyMAC_base::~Op_Diff_PolyMAC_base () override
Member Function Documentation
info()
const Type_info * Op_Diff_PolyMAC_base::info () static
get_info()
const Type_info * Op_Diff_PolyMAC_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Operateur_Diff_base.
Reimplemented in Op_Diff_PolyMAC_Elem, Op_Diff_Nonlinear_PolyMAC_Elem, Op_Dift_PolyMAC_Elem, Op_Dift_Nonlinear_PolyMAC_Elem, and Op_Diff_PolyMAC_Face.
self_cast() [1/2]
Op_Diff_PolyMAC_base & Op_Diff_PolyMAC_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Op_Diff_PolyMAC_base & Op_Diff_PolyMAC_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Op_Diff_PolyMAC_base::printOn (Sortie & os) const override protected virtual
DOES NOTHING - to override in derived classes.
Imprime l'operateur sur un flot de sortie.
Parameters
(Sortie& os) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Operateur_Diff_base.
Reimplemented in Op_Diff_PolyMAC_Elem, Op_Diff_Nonlinear_PolyMAC_Elem, Op_Dift_PolyMAC_Elem, Op_Dift_Nonlinear_PolyMAC_Elem, and Op_Diff_PolyMAC_Face.
References Objet_U::que_suis_je().
Referenced by Op_Diff_PolyMAC_Elem::printOn(), Op_Diff_Nonlinear_PolyMAC_Elem::printOn(), Op_Dift_PolyMAC_Elem::printOn(), Op_Dift_Nonlinear_PolyMAC_Elem::printOn(), and Op_Diff_PolyMAC_Face::printOn().
readOn()
Entree & Op_Diff_PolyMAC_base::readOn (Entree & is) override protected virtual
DOES NOTHING - to override in derived classes.
Lit un operateur sur un flot d'entree.
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Operateur_Diff_base.
Reimplemented in Op_Diff_PolyMAC_Elem, Op_Diff_Nonlinear_PolyMAC_Elem, Op_Dift_PolyMAC_Elem, Op_Dift_Nonlinear_PolyMAC_Elem, and Op_Diff_PolyMAC_Face.
Referenced by Op_Diff_PolyMAC_Elem::readOn(), Op_Diff_Nonlinear_PolyMAC_Elem::readOn(), Op_Dift_PolyMAC_Elem::readOn(), Op_Dift_Nonlinear_PolyMAC_Elem::readOn(), and Op_Diff_PolyMAC_Face::readOn().
calculer_dt_stab()
double Op_Diff_PolyMAC_base::calculer_dt_stab () const override virtual
Calcul dt_stab.
Returns
(double) renvoie toujours 1.e30
Reimplemented from Operateur_base.
References Milieu_base::conductivite(), Op_Diff_PolyMAC_Gen_base::diffusivite(), Operateur_Diff_base::diffusivite_pour_pas_de_temps(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, MorEqn::equation(), Support_Champ_Masse_Volumique::get_champ_masse_volumique(), Echange_impose_base::h_imp(), Support_Champ_Masse_Volumique::has_champ_masse_volumique(), Op_Diff_PolyMAC_Gen_base::la_zcl_poly_, Op_Diff_PolyMAC_Gen_base::le_dom_poly_, Domaine_Cl_dis_base::les_conditions_limites(), Equation_base::milieu(), Process::mp_max(), Process::mp_min(), Domaine_Cl_dis_base::nb_cond_lim(), Domaine_32_64< _SIZE_ >::nb_elem(), TRUSTVect< _TYPE_, _SIZE_ >::size(), update_nu(), TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), Champ_front_base::valeurs(), and Champ_Proto::valeurs().
completer()
void Op_Diff_PolyMAC_base::completer () override virtual
Associe l'operateur au domaine_dis, le domaine_Cl_dis, et a l'inconnue de son equation.
Exceptions
pas d'equation associee
Reimplemented from Operateur_base.
Reimplemented in Op_Diff_PolyMAC_Elem, and Op_Diff_PolyMAC_Face.
References Operateur_base::completer(), Op_Diff_PolyMAC_Gen_base::diffusivite(), MorEqn::equation(), Op_Diff_PolyMAC_Gen_base::le_dom_poly_, Op_Diff_PolyMAC_Gen_base::nu_, Op_Diff_PolyMAC_Gen_base::nu_a_jour_, nu_fac_, Objet_U::que_suis_je(), and TRUSTTab< _TYPE_, _SIZE_ >::resize().
Referenced by Op_Diff_PolyMAC_Elem::completer(), and Op_Diff_PolyMAC_Face::completer().
mettre_a_jour()
void Op_Diff_PolyMAC_base::mettre_a_jour (double temps) inline override virtual
DOES NOTHING - to override in derived classes.
Mise a jour de l'operateur
Parameters
(double) un pas de temps
Reimplemented from Operateur_base.
Reimplemented in Op_Diff_PolyMAC_Elem.
References Operateur_base::mettre_a_jour(), and Op_Diff_PolyMAC_Gen_base::nu_a_jour_.
Referenced by Op_Diff_PolyMAC_Elem::mettre_a_jour().
update_nu()
void Op_Diff_PolyMAC_base::update_nu () const override virtual
Implements Op_Diff_PolyMAC_Gen_base.
References Op_Diff_PolyMAC_Gen_base::diffusivite(), Op_Diff_Turbulent_base::diffusivite_turbulente(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), MorEqn::equation(), TRUSTVect< _TYPE_, _SIZE_ >::get_md_vector(), Equation_base::get_modele(), Op_Diff_Turbulent_base::has_diffusivite_turbulente(), TRUSTArray< _TYPE_, _SIZE_ >::inject_array(), Op_Diff_PolyMAC_Gen_base::la_zcl_poly_, Op_Diff_PolyMAC_Gen_base::le_dom_poly_, TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Equation_base::milieu(), MD_Vector::non_nul(), TRUST_Ref_Objet_U::non_nul(), Op_Diff_PolyMAC_Gen_base::nu_, Op_Diff_PolyMAC_Gen_base::nu_a_jour_, nu_fac_, nu_fac_mod, Milieu_base::porosite_face(), Objet_U::que_suis_je(), TRUSTVect< _TYPE_, _SIZE_ >::size(), TRUST_Vector< _CLASSE_ >::size(), TRUST_Ref< _CLASSE_ >::valeur(), TRUST_Ref_Objet_U::valeur(), Champ_Don_base::valeurs(), and Champ_Proto::valeurs().
Referenced by Op_Diff_PolyMAC_Elem::ajouter(), Op_Diff_PolyMAC_Face::ajouter(), Op_Diff_PolyMAC_Elem::ajouter_termes_croises(), calculer_dt_stab(), Op_Diff_PolyMAC_Elem::contribuer_a_avec(), Op_Diff_PolyMAC_Face::contribuer_a_avec(), Op_Diff_PolyMAC_Elem::contribuer_termes_croises(), Echange_contact_PolyMAC::update_coeffs(), and Op_Diff_PolyMAC_Elem::update_delta_int().
get_nu()
const DoubleTab & Op_Diff_PolyMAC_base::get_nu () const inline
References Op_Diff_PolyMAC_Gen_base::nu_.
get_nu_fac()
const DoubleTab & Op_Diff_PolyMAC_base::get_nu_fac () const inline
References nu_fac_.
remplir_nu_ef()
void Op_Diff_PolyMAC_base::remplir_nu_ef (int e, DoubleTab & nu_ef) const inline
References Process::abort(), TRUSTArray< _TYPE_, _SIZE_ >::addr(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Op_Diff_PolyMAC_Gen_base::le_dom_poly_, TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Op_Diff_PolyMAC_Gen_base::nu_, nu_fac_, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Op_Diff_PolyMAC_Elem::ajouter(), Op_Diff_PolyMAC_Elem::contribuer_a_avec(), Echange_contact_PolyMAC::update_coeffs(), and Op_Diff_PolyMAC_Elem::update_delta_int().
Member Data Documentation
info_obj
const Type_info Op_Diff_PolyMAC_base::info_obj static
nu_fac_mod
DoubleTab Op_Diff_PolyMAC_base::nu_fac_mod mutable protected
Referenced by update_nu().
nu_fac_
DoubleTab Op_Diff_PolyMAC_base::nu_fac_ mutable protected
Referenced by completer(), get_nu_fac(), remplir_nu_ef(), and update_nu().