TrioCFD: Op_Diff_PolyMAC_P0_Face Class Reference
Op_Diff_PolyMAC_P0_Face Class Reference
#include <Op_Diff_PolyMAC_P0_Face.h>
Public Member Functions
double calculer_dt_stab () const override
void completer () override
const Type_info * get_info () const override
void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const override
Public Member Functions inherited from Op_Diff_PolyMAC_P0_base
void completer () override
const Type_info * get_info () const override
void mettre_a_jour (double t) override
Public Member Functions inherited from Op_Diff_PolyMAC_Gen_base
const Type_info * get_info () const override
int impr (Sortie &os) const override
Public Member Functions inherited from Operateur_Diff_base
virtual void associer_diffusivite_pour_pas_de_temps (const Champ_base &)
const Type_info * get_info () const override
Public Member Functions inherited from Operateur_base
void associer_eqn (const Equation_base &)
virtual double calculer_dt_stab () const
virtual void completer ()
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual void mettre_a_jour (double temps)
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Operateur_Diff_base
virtual const Champ_base & diffusivite_pour_pas_de_temps () const
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Op_Diff_PolyMAC_P0_Face()
Op_Diff_PolyMAC_P0_Face::Op_Diff_PolyMAC_P0_Face ()
~Op_Diff_PolyMAC_P0_Face()
Op_Diff_PolyMAC_P0_Face::~Op_Diff_PolyMAC_P0_Face ()
Member Function Documentation
cree_instance()
Objet_U * Op_Diff_PolyMAC_P0_Face::cree_instance () static
taille_memoire()
unsigned Op_Diff_PolyMAC_P0_Face::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Op_Diff_Turbulent_PolyMAC_P0_Face.
duplique()
int Op_Diff_PolyMAC_P0_Face::duplique () const override virtual
Implements Objet_U.
Reimplemented in Op_Diff_Turbulent_PolyMAC_P0_Face.
info()
const Type_info * Op_Diff_PolyMAC_P0_Face::info () static
get_info()
const Type_info * Op_Diff_PolyMAC_P0_Face::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Op_Diff_PolyMAC_P0_base.
Reimplemented in Op_Diff_Turbulent_PolyMAC_P0_Face.
self_cast() [1/2]
Op_Diff_PolyMAC_P0_Face & Op_Diff_PolyMAC_P0_Face::self_cast (Objet_U & r) static
self_cast() [2/2]
const Op_Diff_PolyMAC_P0_Face & Op_Diff_PolyMAC_P0_Face::self_cast (const Objet_U & r) static
printOn()
Sortie & Op_Diff_PolyMAC_P0_Face::printOn (Sortie & os) const override protected virtual
DOES NOTHING - to override in derived classes.
Imprime l'operateur sur un flot de sortie.
Parameters
(Sortie& os) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Op_Diff_PolyMAC_P0_base.
Reimplemented in Op_Diff_Turbulent_PolyMAC_P0_Face.
References Op_Diff_PolyMAC_P0_base::printOn().
readOn()
Entree & Op_Diff_PolyMAC_P0_Face::readOn (Entree & is) override protected virtual
DOES NOTHING - to override in derived classes.
Lit un operateur sur un flot d'entree.
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Op_Diff_PolyMAC_P0_base.
Reimplemented in Op_Diff_Turbulent_PolyMAC_P0_Face.
References Op_Diff_PolyMAC_P0_base::readOn().
completer()
void Op_Diff_PolyMAC_P0_Face::completer () override virtual
Associe l'operateur au domaine_dis, le domaine_Cl_dis, et a l'inconnue de son equation.
Exceptions
pas d'equation associee
Reimplemented from Op_Diff_PolyMAC_P0_base.
Reimplemented in Op_Diff_Turbulent_PolyMAC_P0_Face.
References Op_Diff_PolyMAC_P0_base::completer(), Objet_U::dimension, MorEqn::equation(), Process::exit(), Operateur_base::flux_bords_, Champ_Face_PolyMAC_P0::init_auxiliary_variables(), Operateur_base::le_champ_inco, Op_Diff_PolyMAC_Gen_base::le_dom_poly_, TRUSTVect< _TYPE_, _SIZE_ >::line_size(), TRUST_Ref< _CLASSE_ >::non_nul(), porosite_e, porosite_f, TRUSTVect< _TYPE_, _SIZE_ >::ref(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUST_Ref< _CLASSE_ >::valeur(), and Champ_Inc_base::valeurs().
Referenced by Op_Diff_Turbulent_PolyMAC_P0_Face::completer().
modifier_pour_Cl()
void Op_Diff_PolyMAC_P0_Face::modifier_pour_Cl (Matrice_Morse & , DoubleTab &) const inline override virtual
DOES NOTHING - to override in derived classes.
Parameters
(Matrice_Morse&) une matrice au format Morse
(DoubleTab&) un tableau de valeur (double)
Exceptions
methode a surcharger
Reimplemented from Operateur_base.
has_interface_blocs()
int Op_Diff_PolyMAC_P0_Face::has_interface_blocs () const inline override virtual
Reimplemented from Operateur_base.
calculer_dt_stab()
double Op_Diff_PolyMAC_P0_Face::calculer_dt_stab () const override virtual
Calcul dt_stab.
Returns
(double) renvoie toujours 1.e30
Reimplemented from Operateur_base.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), MorEqn::equation(), Support_Champ_Masse_Volumique::get_champ_masse_volumique(), Support_Champ_Masse_Volumique::has_champ_masse_volumique(), Equation_base::inconnue(), Op_Diff_PolyMAC_Gen_base::le_dom_poly_, TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Equation_base::milieu(), Process::mp_min(), Op_Diff_PolyMAC_Gen_base::nu_, Milieu_base::porosite_elem(), Milieu_base::porosite_face(), Option_PolyMAC::TRAITEMENT_AXI, Op_Diff_PolyMAC_P0_base::update_nu(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_Inc_base::valeurs(), and Champ_Proto::valeurs().
dimensionner_blocs()
void Op_Diff_PolyMAC_P0_Face::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl = { }) const override virtual
Reimplemented from Operateur_base.
References Matrix_tools::allocate_morse_matrix(), Objet_U::dimension, MorEqn::equation(), Champ_Face_base::fcl(), Nom::getString(), Op_Diff_PolyMAC_Gen_base::le_dom_poly_, Field_base::le_nom(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Process::mp_sum_as_double(), Matrice_Morse::nb_colonnes(), Op_Diff_PolyMAC_Gen_base::nu_constant_, Op_Diff_PolyMAC_P0_base::phif_c, Op_Diff_PolyMAC_P0_base::phif_d, Op_Diff_PolyMAC_P0_base::phif_e, Op_Diff_PolyMAC_P0_base::update_phif(), TRUST_Ref< _CLASSE_ >::valeur(), and Champ_Inc_base::valeurs().
ajouter_blocs()
void Op_Diff_PolyMAC_P0_Face::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = { }) const override virtual
Reimplemented from Operateur_base.
References Statistiques::begin_count(), Objet_U::dimension, Statistiques::end_count(), MorEqn::equation(), Champ_Face_base::fcl(), Nom::getString(), Equation_base::inconnue(), Op_Diff_PolyMAC_Gen_base::la_zcl_poly_, Operateur_base::le_champ_inco, Op_Diff_PolyMAC_Gen_base::le_dom_poly_, Field_base::le_nom(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), TRUST_Ref< _CLASSE_ >::non_nul(), Op_Diff_PolyMAC_P0_base::phif_c, Op_Diff_PolyMAC_P0_base::phif_d, Op_Diff_PolyMAC_P0_base::phif_e, porosite_e, porosite_f, Op_Diff_PolyMAC_P0_base::update_phif(), TRUST_Ref< _CLASSE_ >::valeur(), and Champ_Inc_base::valeurs().
check_multiphase_compatibility()
void Op_Diff_PolyMAC_P0_Face::check_multiphase_compatibility () const inline override virtual
Reimplemented from MorEqn.
Member Data Documentation
info_obj
const Type_info Op_Diff_PolyMAC_P0_Face::info_obj static
porosite_e
DoubleVect Op_Diff_PolyMAC_P0_Face::porosite_e protected
Referenced by ajouter_blocs(), and completer().
porosite_f
DoubleVect Op_Diff_PolyMAC_P0_Face::porosite_f protected
Referenced by ajouter_blocs(), and completer().