TrioCFD: IJK_Interfaces Class Reference
IJK_Interfaces Class Reference
#include <IJK_Interfaces.h>
Public Member Functions
void associer_pb_base (const Probleme_base &) override
void calculer_normales_et_aires_interfaciales (IJK_Field_double &ai, IJK_Field_double &kappa_ai, IJK_Field_vector3_double &normale_cell, const int igroup) const
void completer () override
void discretiser () override
void dumplata_ft_mesh (const char *filename, const char *meshname, int step) const
const Type_info * get_info () const override
int lire_motcle_non_standard (const Motcle &un_mot, Entree &is) override
void posttraiter_tous_champs (Motcles &liste) const
int preparer_calcul () override
Public Member Functions inherited from Equation_base
virtual void abortTimeStep ()
virtual void associer_domaine_dis (const Domaine_dis_base &)
virtual void associer_pb_base (const Probleme_base &)
virtual void associer_sch_tps_base (const Schema_Temps_base &)
virtual double calculer_pas_de_temps () const
virtual void completer ()
virtual std::vector< YAML_data > data_a_sauvegarder () const
DoubleTab & derivee_en_temps_conv (DoubleTab &, const DoubleTab &)
virtual DoubleTab & derivee_en_temps_inco (DoubleTab &)
const Discretisation_base & discretisation () const
virtual void discretiser ()
virtual const Motcle & domaine_application () const
virtual Domaine_Cl_dis_base & domaine_Cl_dis ()
virtual const Domaine_Cl_dis_base & domaine_Cl_dis () const
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual void imprimer (Sortie &os) const
virtual bool initTimeStep (double dt)
const Nom & le_nom () const override
int limpr () const
virtual void mettre_a_jour (double temps)
virtual int preparer_calcul ()
Probleme_base & probleme ()
const Probleme_base & probleme () const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Schema_Temps_base & schema_temps ()
const Schema_Temps_base & schema_temps () const
Solveur_Masse_base & solv_masse ()
const Solveur_Masse_base & solv_masse () const
Sources & sources ()
const Sources & sources () const
virtual void valider_iteration ()
virtual void verifie_ch_init_nb_comp (const Champ_Inc_base &ch_ref, const int nb_comp) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Equation_base
virtual Entree & lire_cl (Entree &)
virtual Entree & lire_cond_init (Entree &)
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual Entree & lire_sources (Entree &)
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
virtual int verif_Cl () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Public Types inherited from Champs_compris_IJK_interface
using FieldInfo_t = std::tuple< Motcle, Entity, Nature_du_champ, bool >
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
Cette classe rassemble tous les algorithmes de gestion des interfaces pour le ijk (le maillage, les algo de remaillage, sauvegarde, reprise, etc)
Member Enumeration Documentation
Terme_Gravite
enum IJK_Interfaces::Terme_Gravite protected
Enumerator
GRAVITE_RHO_G
GRAVITE_GRAD_I
Constructor & Destructor Documentation
IJK_Interfaces()
IJK_Interfaces::IJK_Interfaces ()
References compo_to_group_, mean_force_, positions_reference_, TRUSTTab< _TYPE_, _SIZE_ >::resize(), and TRUSTArray< _TYPE_, _SIZE_ >::resize().
~IJK_Interfaces()
IJK_Interfaces::~IJK_Interfaces ()
Member Function Documentation
cree_instance()
Objet_U * IJK_Interfaces::cree_instance () static
taille_memoire()
unsigned IJK_Interfaces::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int IJK_Interfaces::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * IJK_Interfaces::info () static
get_info()
const Type_info * IJK_Interfaces::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Equation_base.
self_cast() [1/2]
IJK_Interfaces & IJK_Interfaces::self_cast (Objet_U & r) static
self_cast() [2/2]
const IJK_Interfaces & IJK_Interfaces::self_cast (const Objet_U & r) static
printOn()
Sortie & IJK_Interfaces::printOn (Sortie & os) const override protected virtual
Surcharge Objet_U::printOn Imprime l'equation et ses composants sur un flot de sortie.
Imprime le nom de l'equation, le solveur masse, les termes sources les conditions aux limites discretisees, les inconnues et les operateurs.
Parameters
(Sortie& os) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Equation_base.
References active_repulsion_paroi_, compo_to_group_, correction_gradient_potentiel_, delta_p_max_repulsion_, delta_p_wall_max_repulsion_, fichier_sauvegarde_interface_, flag_positions_reference_, follow_colors_, frozen_, Parcours_interface::get_correction_parcours_thomas(), Parcours_interface::get_parcours_sans_tolerance(), GRAVITE_RHO_G, mean_force_, parcours_, portee_force_repulsion_, portee_wall_repulsion_, positions_reference_, read_barycentres_velocity_, remaillage_ft_ijk_, TRUSTArray< _TYPE_, _SIZE_ >::size_array(), terme_gravite_, through_yminus_, timestep_sauvegarde_interface_, and use_barycentres_velocity_.
readOn()
Entree & IJK_Interfaces::readOn (Entree & is) override protected virtual
Lecture d'une equation sur un flot d'entree.
Le format est le suivant: { [Source { [sou_1], [sour_2], ...} ] Conditions_limites { [cl_1] [cl_2] ... } Conditions_initiales { [cl_init] } }
Parameters
(Entree& is) un flot d'entree pour lire l'equation
Returns
(Entree&) le flot d'entree modifie
Exceptions
mauvais format de lecture, accolade ouvrante attendue
pas de conditions initiales, il faut initialiser l'inconnue
pas de conditions aux limites, il faut donner des conditions aux limites
Reimplemented from Equation_base.
References active_repulsion_paroi_, Param::ajouter(), Param::ajouter_flag(), avoid_duplicata_, compo_to_group_, compute_distance_autres_interfaces_, correction_gradient_potentiel_, delta_p_max_repulsion_, delta_p_wall_max_repulsion_, Param::dictionnaire(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), dt_impression_bilan_indicatrice_, factor_length_duplicata_, fichier_reprise_interface_, flag_positions_reference_, follow_colors_, frozen_, GRAVITE_GRAD_I, GRAVITE_RHO_G, lata_interfaces_meshname_, Param::lire_avec_accolades(), maillage_ft_ijk_, mean_force_, nb_groups_, ncells_deleted_, ncells_forbidden_, no_octree_method_, parcours_, portee_force_repulsion_, portee_wall_repulsion_, positions_reference_, Objet_U::que_suis_je(), read_barycentres_velocity_, remaillage_ft_ijk_, Param::REQUIRED, seuil_indicatrice_negligeable_, TRUSTArray< _TYPE_, _SIZE_ >::size_array(), terme_gravite_, through_yminus_, timestep_reprise_interface_, use_barycentres_velocity_, use_tryggvason_interfacial_source_, verbosite_surface_efficace_face_, and verbosite_surface_efficace_interface_.
set_param()
void IJK_Interfaces::set_param (Param & titi) inline override virtual
Reimplemented from Equation_base.
set_param_reprise_pb()
void IJK_Interfaces::set_param_reprise_pb (Param & param)
References Param::ajouter(), and probleme_ijk().
Referenced by Probleme_FTD_IJK_base::reprendre_probleme().
completer()
void IJK_Interfaces::completer () inline override virtual
Complete la construction (initialisation) des objets associes a l'equation.
Complete les sources, associe l'equation a l'inconnue complete les operateurs, complete les conditions aux limites discretisees. Voir les methodes Source_base::completer(), Operateur_base::completer() Domaine_Cl_dis_base::completer() Domaine_Cl_dis_base::completer(const Domaine_dis_base&)
Reimplemented from Equation_base.
associer_pb_base()
void IJK_Interfaces::associer_pb_base (const Probleme_base & pb) override virtual
S'associe au Probleme passe en parametre.
Associe egalement les sources, les operateurs et le solveur de masse a l'equation.
Parameters
(Probleme_base& pb) le probleme auquel l'equation doit s'associer
Reimplemented from Equation_base.
References IJK_Composantes_Connex::associer(), Process::exit(), ijk_compo_connex_, Probleme_U::le_nom(), Equation_base::mon_probleme, Equation_base::nom_, Objet_U::que_suis_je(), ref_ijk_ft_, and TRUST_Ref< _CLASSE_ >::valeur().
discretiser()
void IJK_Interfaces::discretiser () inline override virtual
Discretise l'equation.
Type le domaine_Cl_dis, la formatte, l'associe a l'equation. Type le solveur masse, lui associe le domaine discretisee et le domaine des conditions aux limites discretisees.
Reimplemented from Equation_base.
preparer_calcul()
int IJK_Interfaces::preparer_calcul () inline override virtual
Tout ce qui ne depend pas des autres problemes eventuels.
Returns
(int) renvoie toujours 1
Reimplemented from Equation_base.
milieu() [1/2]
const Milieu_base & IJK_Interfaces::milieu () const override virtual
Implements Equation_base.
milieu() [2/2]
Milieu_base & IJK_Interfaces::milieu () override virtual
Implements Equation_base.
associer_milieu_base()
void IJK_Interfaces::associer_milieu_base (const Milieu_base &) inline override virtual
Implements Equation_base.
nombre_d_operateurs()
int IJK_Interfaces::nombre_d_operateurs () const inline override virtual
Implements Equation_base.
operateur() [1/2]
const Operateur & IJK_Interfaces::operateur (int) const inline override virtual
Implements Equation_base.
operateur() [2/2]
Operateur & IJK_Interfaces::operateur (int) inline override virtual
Implements Equation_base.
inconnue() [1/2]
const Champ_Inc_base & IJK_Interfaces::inconnue () const inline override virtual
Implements Equation_base.
inconnue() [2/2]
Champ_Inc_base & IJK_Interfaces::inconnue () inline override virtual
Implements Equation_base.
probleme_ijk() [1/2]
Probleme_FTD_IJK_base & IJK_Interfaces::probleme_ijk ()
References Equation_base::mon_probleme, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by set_param_reprise_pb().
probleme_ijk() [2/2]
const Probleme_FTD_IJK_base & IJK_Interfaces::probleme_ijk () const
References Equation_base::mon_probleme, and TRUST_Ref< _CLASSE_ >::valeur().
has_champ() [1/2]
bool IJK_Interfaces::has_champ (const Motcle & nom) const inline override virtual
Reimplemented from Equation_base.
References Champs_compris_T< FIELD_TYPE >::has_champ().
Referenced by get_IJK_field(), and Probleme_FTD_IJK_base::has_champ().
has_champ() [2/2]
bool IJK_Interfaces::has_champ (const Motcle & nom, TRUST_Ref< Champ_base * > & ref_champ) const inline override virtual
Reimplemented from Equation_base.
has_champ_vectoriel()
bool IJK_Interfaces::has_champ_vectoriel (const Motcle & nom) const inline override virtual
Implements Champs_compris_IJK_interface.
References Champs_compris_IJK::has_champ_vectoriel().
Referenced by get_IJK_field_vector(), and Probleme_FTD_IJK_base::has_champ_vectoriel().
get_IJK_field()
const IJK_Field_double & IJK_Interfaces::get_IJK_field (const Motcle & nom) override virtual
Implements Champs_compris_IJK_interface.
References calculer_distance_autres_compo_connexe2(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::data(), Champs_compris_T< FIELD_TYPE >::get_champ(), FT_Field::get_FT_field_Array(), FT_Field::get_Grad_FT_field_Array(), FT_Field::get_interfacial_source_term_sommets(), FT_Field::get_Laplacian_FT_field_Array(), FT_Field::get_sigma_sommets(), Maillage_FT_Disc::get_update_courbure_sommets(), has_champ(), maillage_ft_ijk_, scalar_post_fields_, and Maillage_FT_IJK::Surfactant_facettes().
Referenced by Probleme_FTD_IJK_base::get_IJK_field().
get_IJK_field_vector()
const IJK_Field_vector3_double & IJK_Interfaces::get_IJK_field_vector (const Motcle & nom) override virtual
Implements Champs_compris_IJK_interface.
References Champs_compris_IJK::get_champ_vectoriel(), and has_champ_vectoriel().
Referenced by Probleme_FTD_IJK_base::get_IJK_field_vector().
Fill_postprocessable_fields()
void IJK_Interfaces::Fill_postprocessable_fields (std::vector< FieldInfo_t > & chps) static
Referenced by Probleme_FTD_IJK_base::Fill_postprocessable_fields(), and Postprocessing_IJK::register_interface_field().
get_noms_champs_postraitables()
void IJK_Interfaces::get_noms_champs_postraitables (Noms & noms, Option opt = NONE) const override virtual
Reimplemented from Equation_base.
References TRUST_Vector< _CLASSE_ >::add(), Champs_compris_IJK::liste_noms_compris(), and Champs_compris_IJK::liste_noms_compris_vectoriel().
Referenced by Probleme_FTD_IJK_base::get_noms_champs_postraitables().
register_fields()
void IJK_Interfaces::register_fields ()
References Champs_compris_T< FIELD_TYPE >::ajoute_champ(), and scalar_post_fields_.
Referenced by Probleme_FTD_IJK_base::initialise_interfaces().
dumplata_ft_mesh()
void IJK_Interfaces::dumplata_ft_mesh (const char * filename, const char * meshname, int step) const
Output the FT mesh information in the master LATA file.
ASSUMPTION: for now the FT mesh always fits within 32b (in terms of nb of elems / vertices). This is checked.
Ajoute ceci dans le fichier lata maitre: GEOM meshname type_elem=TRIANGLE_3D CHAMP SOMMETS filename.step.meshname.SOMMETS geometry=meshname size=... composantes=3 CHAMP ELEMENTS filename.step.meshname.ELEMENTS geometry=meshname size=... composantes=3 format=INT32|64
References TRUSTArray< _TYPE_, _SIZE_ >::addr(), Process::check_int_overflow(), EcrFicPartage::close(), Maillage_FT_Disc::facette_PE_owner(), Maillage_FT_Disc::facettes(), Process::je_suis_maitre(), maillage_ft_ijk_, Process::me(), Process::mp_sum(), Process::mppartial_sum(), Maillage_FT_Disc::nb_facettes(), Maillage_FT_Disc::nb_sommets(), Process::nproc(), Sortie_Fichier_base::ouvrir(), EcrFicPartage::ouvrir(), EcrFicPartage::put(), EcrFicPartage::set_64b(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), Maillage_FT_Disc::sommet_num_owner(), Maillage_FT_Disc::sommet_PE_owner(), Maillage_FT_Disc::sommets(), and EcrFicPartage::syncfile().
Referenced by posttraiter_champs_instantanes(), sauvegarder_interfaces(), and Postprocessing_IJK::write_extra_mesh().
initialize()
void IJK_Interfaces::initialize (const Domaine_IJK & splitting_FT, const Domaine_IJK & splitting_NS, const Domaine_dis_base & domaine_dis, const int thermal_probes_ghost_cells = 0, const bool compute_vint = true, const bool is_switch = false)
References Champs_compris_T< FIELD_TYPE >::ajoute_champ(), Champs_compris_IJK::ajoute_champ_vectoriel(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::allocate(), Parcours_interface::associer_connectivite_frontieres(), Remaillage_FT::associer_domaine(), Parcours_interface::associer_domaine_dis(), Connectivite_frontieres::associer_domaine_vf(), avoid_duplicata_, bary_of_interf_, bary_of_interf_ns_, bary_par_compo_, barycentre_phase1_face_ft_, barycentre_phase1_face_ns_, barycentre_phase1_ft_, barycentre_phase1_ns_, barycentre_vapeur_par_face_, barycentre_vapeur_par_face_ns_, bounding_box_duplicate_criteria_, bounding_box_forbidden_criteria_, bounding_box_NS_domain_, calculer_distance_autres_compo_connexe2(), calculer_volume_bulles(), Maillage_FT_IJK::compo_connexe_facettes(), compo_to_group_, compos_traversantes_, compute_distance_autres_interfaces_, compute_vinterp(), connectivite_frontieres_, courbure_par_compo_, creer_duplicata_bulles(), cut_cell_activated_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::data(), IJK_Shear_Periodic_helpler::defilement_, deformation_velocity_, delta_p_max_repulsion_, delta_volume_theorique_bilan_ns_, Option_IJK::DISABLE_DIPHASIQUE, distance_autres_interfaces_, Domaine_dis_base::domaine(), Equation_base::domaine_dis(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel(), Domaine_IJK::ELEM, Process::exit(), factor_length_duplicata_, fichier_reprise_interface_, field_repulsion_, follow_colors_, force_time_n_, Domaine_IJK::get_constant_delta(), Domaine_IJK::get_domain_length(), Domaine_IJK::get_origin(), Domaine_IJK::get_periodic_flag(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost(), groups_indicatrice_ft_, groups_indicatrice_ns_, ijk_compo_connex_, indicatrice_apres_remaillage_ft_, indicatrice_apres_remaillage_ns_, indicatrice_avant_remaillage_ft_, indicatrice_avant_remaillage_ns_, indicatrice_ft_, indicatrice_ns_, indicatrice_par_compo_, indicatrice_surfacique_apres_remaillage_face_ft_, indicatrice_surfacique_apres_remaillage_face_ns_, indicatrice_surfacique_avant_remaillage_face_ft_, indicatrice_surfacique_avant_remaillage_face_ns_, indicatrice_surfacique_efficace_deformation_face_, indicatrice_surfacique_face_ft_, indicatrice_surfacique_face_ns_, Maillage_FT_IJK::initialize(), SurfaceVapeurIJKComputation::initialize(), Intersection_Interface_ijk_face::initialize(), Intersection_Interface_ijk_cell::initialize(), ComputeValParCompoInCell::initialize(), FT_Field::initialize(), IJK_Composantes_Connex::initialize(), intersection_ijk_cell_, intersection_ijk_face_, lata_interfaces_meshname_, Maillage_FT_IJK::lire_maillage_ft_dans_lata(), maillage_ft_ijk_, mean_force_, Process::mp_max(), nb_bulles_reelles_, nb_compo_in_num_compo_, nb_compo_traversante_, ncells_forbidden_, next(), normal_of_interf_, normal_of_interf_ns_, normale_par_compo_, num_compo_, old(), old_maillage_ft_ijk_, parcours_, parser_, perio_NS_, phi_par_compo_, portee_force_repulsion_, read_bubbles_barycentres_old_new(), recompute_indicator_, ref_domaine_, ref_ijk_ft_, refdomaine_dis_, remaillage_ft_ijk_, repuls_par_compo_, TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), RK3_G_store_vi_, set_recompute_indicator(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), source_interf_par_compo_, supprimer_duplicata_bulles(), surf_par_compo_, surface_interface_ft_, surface_interface_ns_, surface_par_compo_, surface_vapeur_par_face_, surface_vapeur_par_face_computation_, surface_vapeur_par_face_ns_, Maillage_FT_IJK::Surfactant_facettes_non_const(), through_yminus_, timestep_reprise_interface_, transferer_bulle_perio(), use_tryggvason_interfacial_source_, and val_par_compo_in_cell_computation_.
Referenced by Switch_FT_double::initialise(), and Probleme_FTD_IJK_base::initialise_interfaces().
associer_switch()
void IJK_Interfaces::associer_switch (const Switch_FT_double & ijk_ft_switch)
References ref_ijk_ft_switch_.
posttraiter_tous_champs()
void IJK_Interfaces::posttraiter_tous_champs (Motcles & liste) const
Methode appelee lorsqu'on a mis "TOUS" dans la liste des champs a postraiter. Elle ajoute a la liste tous les noms de champs postraitables par IJK_Interfaces
References TRUST_Vector< _CLASSE_ >::add(), follow_colors_, Process::mp_sum(), RK3_G_store_vi_, and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
posttraiter_champs_instantanes()
int IJK_Interfaces::posttraiter_champs_instantanes (const Motcles & liste_post_instantanes, const char * lata_name, const int lata_step) const
References calculer_color(), Motcles::contient_(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), dumplata_ft_mesh(), Process::exit(), follow_colors_, maillage_ft_ijk_, TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), RK3_G_store_vi_, Maillage_FT_Disc::sommets(), and vinterp_.
sauvegarder_interfaces()
void IJK_Interfaces::sauvegarder_interfaces (const char * lata_name, const Nom & interf_name = "??")
References Maillage_FT_IJK::compo_connexe_facettes(), dumplata_ft_mesh(), fichier_sauvegarde_interface_, maillage_ft_ijk_, ncells_deleted_, store_bubbles_barycentres(), supprimer_certaines_bulles_reelles(), and timestep_sauvegarde_interface_.
Referenced by Switch_FT_double::ecrire_header_lata(), and Probleme_FTD_IJK_base::sauvegarder_probleme().
calculer_color()
void IJK_Interfaces::calculer_color (ArrOfInt & color) const
References Maillage_FT_IJK::compo_connexe_facettes(), maillage_ft_ijk_, Maillage_FT_Disc::nb_facettes(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), and through_yminus_.
Referenced by posttraiter_champs_instantanes().
postraiter_colors()
void IJK_Interfaces::postraiter_colors (Sortie & os, const double current_time) const
References Process::je_suis_maitre(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and through_yminus_.
calculer_var_volume_remaillage()
void IJK_Interfaces::calculer_var_volume_remaillage (double timestep, const DoubleTab & vitesses_translation_bulles, const DoubleTab & mean_bubble_rotation_vector, const DoubleTab & centre_gravite, ArrOfDouble & var_volume)
References Cut_cell_surface_efficace::calcul_delta_volume_theorique_bilan(), Cut_cell_surface_efficace::calcul_surface_face_efficace_initiale(), calculer_bounding_box_bulles(), calculer_vitesse_de_deformation(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::data(), deformation_velocity_, delta_volume_theorique_bilan_ns_, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Domaine_dis_base::domaine(), Probleme_FTD_IJK_cut_cell::get_cut_field_velocity(), get_nb_bulles_ghost(), get_nb_bulles_reelles(), I_ft(), indicatrice_avant_remaillage_ns_, indicatrice_ns_, indicatrice_surfacique_avant_remaillage_face_ns_, indicatrice_surfacique_efficace_deformation_face_, indicatrice_surfacique_face_ns_, maillage_ft_ijk_, next(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), ref_domaine_, ref_ijk_ft_, refdomaine_dis_, TRUSTArray< _TYPE_, _SIZE_ >::resize(), Cut_field_vector< T, N >::set_to_uniform_value(), Maillage_FT_Disc::sommets(), Transport_Interfaces_FT_Disc::transfert_conservatif_eulerien_vers_lagrangien_sommets(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by transporter_maillage_remaillage().
calculer_vecteurs_de_deplacement_rigide()
void IJK_Interfaces::calculer_vecteurs_de_deplacement_rigide (DoubleTab & vitesses_translation_bulles, DoubleTab & mean_bubble_rotation_vector, DoubleTab & centre_gravite, const int first_step_interface_smoothing = 0)
References bubbles_velocities_, bubbles_velocities_bary_, calculer_surface_bulles(), calculer_vmoy_rotation_composantes_connexes(), calculer_vmoy_translation_composantes_connexes(), calculer_volume_bulles(), Maillage_FT_IJK::compo_connexe_facettes(), compute_bubbles_volume_and_barycentres(), compute_vinterp(), Maillage_FT_Disc::desc_sommets(), Desc_Structure_FT::echange_espace_virtuel(), get_nb_bulles_ghost(), get_nb_bulles_reelles(), Maillage_FT_Disc::get_update_surface_facettes(), Process::je_suis_maitre(), maillage_ft_ijk_, ref_ijk_ft_, TRUSTTab< _TYPE_, _SIZE_ >::resize(), use_barycentres_velocity_, and vinterp_.
transporter_maillage_deformation()
void IJK_Interfaces::transporter_maillage_deformation (const int correction_semi_locale_volume_bulle, const DoubleTab & vitesses_translation_bulles, const DoubleTab & mean_bubble_rotation_vector, const DoubleTab & centre_gravite, const double dt_tot, ArrOfDouble & dvol, const int rk_step = -1, const int first_step_interface_smoothing = 0)
References FT_Field::avancer_en_temps(), Maillage_FT_IJK::calculer_compo_connexe_sommets(), Remaillage_FT::calculer_variation_volume(), FT_Field::check_conservation(), FT_Field::correction_conservation_globale(), Maillage_FT_Disc::desc_sommets(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Desc_Structure_FT::echange_espace_virtuel(), FT_Field::get_disable_surfactant(), get_ghost_number_from_compo(), get_nb_bulles_ghost(), get_nb_bulles_reelles(), Process::Journal(), maillage_ft_ijk_, FT_Field::passer_variable_extensive(), FT_Field::passer_variable_intensive(), Maillage_FT_Disc::preparer_tableau_avant_transport(), Vecteur3::produit_vectoriel(), remaillage_ft_ijk_, TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::resize(), RK3_G_store_vi_, Maillage_FT_Disc::sommet_virtuel(), Maillage_FT_Disc::sommets(), Maillage_FT_IJK::Surfactant_facettes(), Maillage_FT_IJK::Surfactant_facettes_non_const(), Maillage_FT_IJK::transporter(), Maillage_FT_Disc::update_tableau_apres_transport(), var_volume_deformation_, and vinterp_.
transporter_maillage_remaillage()
void IJK_Interfaces::transporter_maillage_remaillage (int correction_semi_locale_volume_bulle, const DoubleTab & vitesses_translation_bulles, const DoubleTab & mean_bubble_rotation_vector, const DoubleTab & centre_gravite, double dt_tot, ArrOfDouble & dvol, const int rk_step = -1, const double temps = -1)
References calculer_surface_bulles(), calculer_var_volume_remaillage(), Desc_Structure_FT::collecter_espace_virtuel(), Maillage_FT_IJK::compo_connexe_facettes(), Maillage_FT_Disc::desc_sommets(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Desc_Structure_FT::echange_espace_virtuel(), MD_Vector_tools::EV_SOMME, Process::exit(), Maillage_FT_Disc::facette_virtuelle(), Maillage_FT_Disc::facettes(), FT_Field::get_disable_surfactant(), get_ghost_number_from_compo(), get_nb_bulles_reelles(), Maillage_FT_Disc::get_update_surface_facettes(), maillage_ft_ijk_, Maillage_FT_Disc::nb_facettes(), Maillage_FT_Disc::nb_sommets(), Maillage_FT_IJK::nettoyer_maillage(), ref_domaine_, remaillage_ft_ijk_, remailler_interface(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::resize(), RK3_G_store_vi_, Maillage_FT_Disc::sommets(), Maillage_FT_IJK::Surfactant_facettes(), Maillage_FT_IJK::update_gradient_laplacien_Surfactant(), Maillage_FT_IJK::update_sigma_and_interfacial_source_term_sommet(), use_tryggvason_interfacial_source_, var_volume_correction_globale_, var_volume_deformation_, and var_volume_remaillage_.
transporter_maillage_rigide()
void IJK_Interfaces::transporter_maillage_rigide (const double dt_tot, const DoubleTab & vitesses_translation_bulles, const DoubleTab & mean_bubble_rotation_vector, const DoubleTab & centre_gravite, const int rk_step, const int first_step_interface_smoothing = 0)
References Maillage_FT_IJK::calculer_compo_connexe_sommets(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), get_ghost_number_from_compo(), get_nb_bulles_ghost(), get_nb_bulles_reelles(), maillage_ft_ijk_, Vecteur3::produit_vectoriel(), Maillage_FT_Disc::sommet_virtuel(), Maillage_FT_Disc::sommets(), and Maillage_FT_IJK::transporter().
calculer_vitesse_de_deformation()
void IJK_Interfaces::calculer_vitesse_de_deformation (int compo, const DoubleTab & bounding_box_bulles, const Cut_field_vector3_double & cut_field_velocity, const DoubleTab & vitesses_translation_bulles, const DoubleTab & mean_bubble_rotation_vector, const DoubleTab & positions_bulles)
References deformation_velocity_, get_barycentre(), Domaine_IJK::get_constant_delta(), IJK_Field_vector< T, N >::get_domaine(), Cut_cell_FT_Disc::get_interfaces(), Cut_cell_FT_Disc::get_n(), Domaine_IJK::get_offset_local(), Domaine_IJK::get_origin(), Cut_field_vector< T, N >::ghost(), Domaine_IJK::is_uniform(), and Vecteur3::produit_vectoriel().
Referenced by calculer_var_volume_remaillage().
calculer_bounding_box_bulles()
void IJK_Interfaces::calculer_bounding_box_bulles (DoubleTab & bounding_box, int option_shear = 0) const
References Maillage_FT_IJK::calculer_compo_connexe_sommets(), calculer_volume_bulles(), IJK_Shear_Periodic_helpler::defilement_, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), get_nb_bulles_reelles(), maillage_ft_ijk_, TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), and Maillage_FT_Disc::sommets().
Referenced by calculer_var_volume_remaillage(), IJK_Composantes_Connex::compute_bounding_box_fill_compo_connex(), creer_duplicata_bulles(), supprimer_certaines_bulles_reelles(), and transferer_bulle_perio().
preparer_duplicata_bulles()
void IJK_Interfaces::preparer_duplicata_bulles (const DoubleTab & bounding_box_of_bubbles, const DoubleTab & bounding_box_offsetp, const DoubleTab & bounding_box_offsetm, const DoubleTab & authorized_bounding_box, ArrOfInt & masque_duplicata_pour_compo_reel)
References IJK_Shear_Periodic_helpler::defilement_, get_nb_bulles_reelles(), Process::je_suis_maitre(), perio_NS_, and TRUSTArray< _TYPE_, _SIZE_ >::resize_array().
Referenced by creer_duplicata_bulles().
preparer_duplicata_bulles_masque_6bit()
void IJK_Interfaces::preparer_duplicata_bulles_masque_6bit (const DoubleTab & bounding_box, const DoubleTab & authorized_bounding_box, ArrOfInt & masque_duplicata_pour_compo)
References get_nb_bulles_reelles(), Process::je_suis_maitre(), perio_NS_, and TRUSTArray< _TYPE_, _SIZE_ >::resize_array().
Referenced by creer_duplicata_bulles(), supprimer_certaines_bulles_reelles(), and transferer_bulle_perio().
dupliquer_bulle_perio()
void IJK_Interfaces::dupliquer_bulle_perio (ArrOfInt & masque_duplicata_pour_compo)
References Maillage_FT_IJK::ajouter_maillage_IJK(), TRUSTArray< _TYPE_, _SIZE_ >::append_array(), bounding_box_NS_domain_, calculer_volume_bulles(), Maillage_FT_IJK::compo_connexe_facettes(), TRUSTArray< _TYPE_, _SIZE_ >::copy_array(), IJK_Shear_Periodic_helpler::defilement_, Process::exit(), FT_Field::get_disable_surfactant(), get_nb_bulles_reelles(), ghost_compo_converter_, Maillage_FT_IJK::initialize(), TRUSTArray< _TYPE_, _SIZE_ >::inject_array(), Process::je_suis_maitre(), maillage_ft_ijk_, Process::me(), Maillage_FT_Disc::MINIMAL, Process::mp_max(), Process::mp_sum(), nb_bulles_ghost_, nb_bulles_ghost_before_, Maillage_FT_Disc::nb_facettes(), Maillage_FT_IJK::nettoyer_maillage(), Process::nproc(), parcours_, recompute_indicator_, Maillage_FT_IJK::recopie(), ref_domaine_, refdomaine_dis_, TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), Maillage_FT_IJK::set_composante_connexe(), FT_Field::set_disable_surfactant(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), Maillage_FT_IJK::supprimer_facettes(), Maillage_FT_IJK::Surfactant_facettes(), Maillage_FT_IJK::Surfactant_facettes_non_const(), Maillage_FT_IJK::transporter(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by creer_duplicata_bulles().
creer_duplicata_bulles()
void IJK_Interfaces::creer_duplicata_bulles ()
References bounding_box_duplicate_criteria_, calculer_bounding_box_bulles(), IJK_Shear_Periodic_helpler::defilement_, dupliquer_bulle_perio(), preparer_duplicata_bulles(), and preparer_duplicata_bulles_masque_6bit().
Referenced by detecter_et_supprimer_rejeton(), initialize(), Probleme_FTD_IJK_base::sauver(), Probleme_FTD_IJK_base::solveTimeStep(), Probleme_FTD_IJK_base::solveTimeStep_Euler(), and Probleme_FTD_IJK_base::solveTimeStep_RK3().
supprimer_duplicata_bulles()
void IJK_Interfaces::supprimer_duplicata_bulles ()
References TRUSTArray< _TYPE_, _SIZE_ >::append_array(), Maillage_FT_IJK::compo_connexe_facettes(), ghost_compo_converter_, maillage_ft_ijk_, nb_bulles_ghost_, nb_bulles_ghost_before_, Maillage_FT_Disc::nb_facettes(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), RK3_G_store_vi_, and Maillage_FT_IJK::supprimer_facettes().
Referenced by detecter_et_supprimer_rejeton(), initialize(), Probleme_FTD_IJK_base::sauver(), Probleme_FTD_IJK_base::solveTimeStep_Euler(), Probleme_FTD_IJK_base::solveTimeStep_RK3(), and supprimer_certaines_bulles_reelles().
supprimer_certaines_bulles_reelles()
void IJK_Interfaces::supprimer_certaines_bulles_reelles ()
References bounding_box_delete_criteria_, bounding_box_NS_domain_, calculer_bounding_box_bulles(), Maillage_FT_IJK::compo_connexe_facettes(), compo_to_group_, Domaine_IJK::get_constant_delta(), Domaine_IJK::get_domain_length(), Domaine_IJK::get_origin(), Process::je_suis_maitre(), maillage_ft_ijk_, nb_bulles_reelles_, Maillage_FT_Disc::nb_facettes(), ncells_deleted_, perio_NS_, positions_reference_, preparer_duplicata_bulles_masque_6bit(), recompute_indicator_, ref_domaine_, TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), Maillage_FT_IJK::set_composante_connexe(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), supprimer_duplicata_bulles(), through_yminus_, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by sauvegarder_interfaces().
deplacer_bulle_perio()
void IJK_Interfaces::deplacer_bulle_perio (const ArrOfInt & masque_deplacement_par_compo)
References bounding_box_NS_domain_, calculer_volume_bulles(), get_nb_bulles_reelles(), Process::Journal(), maillage_ft_ijk_, recompute_indicator_, and Maillage_FT_IJK::transporter().
Referenced by transferer_bulle_perio().
transferer_bulle_perio()
void IJK_Interfaces::transferer_bulle_perio ()
References bounding_box_forbidden_criteria_, calculer_bounding_box_bulles(), deplacer_bulle_perio(), follow_colors_, get_nb_bulles_reelles(), Process::je_suis_maitre(), perio_NS_, preparer_duplicata_bulles_masque_6bit(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and through_yminus_.
Referenced by initialize(), Probleme_FTD_IJK_base::solveTimeStep_Euler(), and Probleme_FTD_IJK_base::solveTimeStep_RK3().
update_indicatrice_variables_monofluides()
void IJK_Interfaces::update_indicatrice_variables_monofluides ()
References compute_compo_connex_from_bounding_box(), compute_compo_connex_from_interface(), compute_rising_velocities_from_compo(), and reset_flags_and_counters().
Referenced by Probleme_FTD_IJK_base::deplacer_interfaces().
compute_vinterp()
void IJK_Interfaces::compute_vinterp ()
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), maillage_ft_ijk_, ref_ijk_ft_, TRUSTTab< _TYPE_, _SIZE_ >::resize(), Maillage_FT_Disc::sommets(), and vinterp_.
Referenced by calculer_distance_autres_compo_connexe2(), calculer_vecteurs_de_deplacement_rigide(), compute_external_forces_(), initialize(), Probleme_FTD_IJK_base::preparer_calcul(), and Probleme_FTD_IJK_base::validateTimeStep().
compute_external_forces_()
void IJK_Interfaces::compute_external_forces_ (IJK_Field_vector3_double & rappel_ft, IJK_Field_vector3_double & rappel, const IJK_Field_vector3_double & vitesse, const IJK_Field_double & indic_ns, const IJK_Field_double & indic_ft, const double coef_immo, const int tstep, const double current_time, const double coef_ammortissement, const double coef_rayon_force_rappel, double compteur, double coef_mean_force, double coef_force_time_n)
References Maillage_FT_IJK::calculer_compo_connexe_sommets(), calculer_surface_bulles(), calculer_vmoy_translation_composantes_connexes(), calculer_volume_bulles(), Sortie_Fichier_base::close(), Maillage_FT_IJK::compo_connexe_facettes(), compute_external_forces_color_function(), compute_external_forces_parser(), compute_vinterp(), Maillage_FT_Disc::desc_sommets(), Desc_Structure_FT::echange_espace_virtuel(), force_time_n_, Domaine_IJK::get_domain_length(), IJK_Field_vector< T, N >::get_domaine(), get_nb_bulles_ghost(), get_nb_bulles_reelles(), Maillage_FT_Disc::get_update_surface_facettes(), Process::je_suis_maitre(), maillage_ft_ijk_, mean_force_, nb_bulles_reelles_, Objet_U::nom_du_cas(), Sortie_Fichier_base::ouvrir(), parser_, positions_reference_, reprise_, and vinterp_.
compute_external_forces_parser()
void IJK_Interfaces::compute_external_forces_parser (IJK_Field_vector3_double & rappel, const IJK_Field_double & indic_ns, const DoubleTab & individual_forces, const ArrOfDouble & volume_reel, const DoubleTab & position, const double coef_rayon_force_rappel)
References TRUST_Vector< _CLASSE_ >::dimensionner_force(), ghost_compo_converter(), ghost_compo_converter_, nb_bulles_ghost_, nb_bulles_reelles_, and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by compute_external_forces_().
compute_external_forces_color_function()
void IJK_Interfaces::compute_external_forces_color_function (IJK_Field_vector3_double & rappel, const IJK_Field_double & indic_ns, const IJK_Field_double & indic_ft, DoubleTab & individual_forces, const ArrOfDouble & volume_reel, const DoubleTab & position)
References TRUSTArray< _TYPE_, _SIZE_ >::append_array(), Domaine_IJK::convert_ijk_cell_to_packed(), Process::exit(), Domaine_IJK::FACES_K, Domaine_IJK::get_constant_delta(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_domaine(), Domaine_IJK::get_nb_items_global(), Domaine_IJK::get_offset_local(), Domaine_IJK::get_periodic_flag(), ghost_compo_converter(), ghost_compo_converter_, nb_bulles_ghost_, nb_bulles_reelles_, nb_compo_in_num_compo_, num_compo_, TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), Domaine_IJK::search_elem(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by compute_external_forces_().
compute_indicatrice_non_perturbe()
void IJK_Interfaces::compute_indicatrice_non_perturbe (IJK_Field_double & indic_np, const IJK_Field_double & indic, const ArrOfDouble & volume_reel, const DoubleTab & position) const
References ghost_compo_converter_, nb_bulles_ghost_, nb_bulles_reelles_, positions_reference_, and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
lire_motcle_non_standard()
int IJK_Interfaces::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Equation_base.
References Process::exit(), and parcours_.
activate_cut_cell()
void IJK_Interfaces::activate_cut_cell ()
References TRUSTTabFT_cut_cell_scalar< _TYPE_ >::associer_ephemere(), TRUSTTabFT_cut_cell_vector3< _TYPE_ >::associer_ephemere(), TRUSTTabFT_cut_cell_vector6< _TYPE_ >::associer_ephemere(), coord_deplacement_interface_, cut_cell_activated_, Parcours_interface::get_correction_parcours_thomas(), Parcours_interface::get_parcours_sans_tolerance(), indicatrice_surfacique_efficace_face_, indicatrice_surfacique_efficace_face_absolute_error_, indicatrice_surfacique_efficace_face_correction_, indicatrice_surfacique_efficace_face_initial_, normale_deplacement_interface_, parcours_, ref_ijk_ft_, Parcours_interface::set_correction_parcours_thomas(), Parcours_interface::set_parcours_sans_tolerance(), surface_efficace_interface_, surface_efficace_interface_initial_, and vitesse_deplacement_interface_.
Referenced by Probleme_FTD_IJK_cut_cell::initialize().
imprime_bilan_indicatrice()
void IJK_Interfaces::imprime_bilan_indicatrice ()
References Process::check_int_overflow(), TRUSTTabFT_cut_cell< _TYPE_ >::get_cut_cell_disc(), Cut_cell_FT_Disc::get_ijk(), Cut_cell_FT_Disc::get_n_loc(), indicatrice_ns_, Process::mp_min(), Process::mp_sum(), next(), and surface_efficace_interface_.
Referenced by Probleme_FTD_IJK_cut_cell::deplacer_interfaces(), and Probleme_FTD_IJK_cut_cell::deplacer_interfaces_rk3().
set_fichier_reprise_interface()
void IJK_Interfaces::set_fichier_reprise_interface (const Nom & prefix) inline
References fichier_reprise_interface_, and set_reprise().
Referenced by Probleme_FTD_IJK_base::reprendre_probleme().
calcul_surface_efficace_face()
void IJK_Interfaces::calcul_surface_efficace_face (TYPE_SURFACE_EFFICACE_FACE type_surface_efficace_face, double timestep, const Cut_field_vector3_double & total_velocity)
Referenced by Probleme_FTD_IJK_cut_cell::deplacer_interfaces(), and Probleme_FTD_IJK_cut_cell::deplacer_interfaces_rk3().
calcul_surface_efficace_interface()
void IJK_Interfaces::calcul_surface_efficace_interface (TYPE_SURFACE_EFFICACE_INTERFACE type_surface_efficace_interface, double timestep, const Cut_field_vector3_double & velocity)
References Cut_cell_surface_efficace::calcul_surface_interface_efficace_initiale().
Referenced by Probleme_FTD_IJK_cut_cell::deplacer_interfaces(), and Probleme_FTD_IJK_cut_cell::deplacer_interfaces_rk3().
calcul_surface_efficace_face_initial()
void IJK_Interfaces::calcul_surface_efficace_face_initial (TYPE_SURFACE_EFFICACE_FACE type_surface_efficace_face)
References Cut_cell_surface_efficace::calcul_surface_face_efficace_initiale().
Referenced by Probleme_FTD_IJK_cut_cell::deplacer_interfaces(), and Probleme_FTD_IJK_cut_cell::deplacer_interfaces_rk3().
calcul_surface_efficace_interface_initial()
void IJK_Interfaces::calcul_surface_efficace_interface_initial (TYPE_SURFACE_EFFICACE_INTERFACE type_surface_efficace_interface)
References Cut_cell_surface_efficace::calcul_surface_interface_efficace_initiale().
Referenced by Probleme_FTD_IJK_cut_cell::deplacer_interfaces(), and Probleme_FTD_IJK_cut_cell::deplacer_interfaces_rk3().
get_domaine_dis()
const Domaine_dis_base & IJK_Interfaces::get_domaine_dis () const inline
References refdomaine_dis_, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by IJK_Composantes_Connex::fill_mixed_cell_compo(), and IJK_One_Dimensional_Subproblems_Interfaces_Fields::retrieve_interfacial_surface_quantity().
get_dt_impression_bilan_indicatrice()
int IJK_Interfaces::get_dt_impression_bilan_indicatrice () const inline
References dt_impression_bilan_indicatrice_.
Referenced by Probleme_FTD_IJK_cut_cell::deplacer_interfaces(), and Probleme_FTD_IJK_cut_cell::deplacer_interfaces_rk3().
get_nb_bulles_reelles()
int IJK_Interfaces::get_nb_bulles_reelles () const inline
References nb_bulles_reelles_.
Referenced by calculer_aspect_ratio(), calculer_bounding_box_bulles(), calculer_indicatrice_intermediaire(), calculer_indicatrice_next(), calculer_poussee_bulles(), calculer_surface_bulles(), calculer_surfactant(), calculer_var_volume_remaillage(), calculer_vecteurs_de_deplacement_rigide(), calculer_volume_bulles(), compute_bubbles_volume_and_barycentres(), compute_external_forces_(), compute_surface_average_per_bubble(), deplacer_bulle_perio(), dupliquer_bulle_perio(), IJK_Composantes_Connex::fill_mixed_cell_compo(), IJK_Thermal_base::force_upstream_temperature(), preparer_duplicata_bulles(), preparer_duplicata_bulles_masque_6bit(), Probleme_FTD_IJK_base::solveTimeStep(), store_bubbles_barycentres(), transferer_bulle_perio(), transporter_maillage_deformation(), transporter_maillage_remaillage(), and transporter_maillage_rigide().
get_flag_positions_reference()
int IJK_Interfaces::get_flag_positions_reference () const inline
References flag_positions_reference_.
is_frozen()
int IJK_Interfaces::is_frozen () const inline
References frozen_.
freeze()
void IJK_Interfaces::freeze () inline
References frozen_.
get_nb_bulles_ghost()
int IJK_Interfaces::get_nb_bulles_ghost (const int print = 0) const inline
References nb_bulles_ghost_.
Referenced by calculer_aspect_ratio(), calculer_poussee_bulles(), calculer_surface_bulles(), calculer_var_volume_remaillage(), calculer_vecteurs_de_deplacement_rigide(), calculer_volume_bulles(), compute_external_forces_(), Probleme_FTD_IJK_base::solveTimeStep(), transporter_maillage_deformation(), and transporter_maillage_rigide().
get_forcing_method()
int IJK_Interfaces::get_forcing_method () const inline
References parser_.
get_recompute_indicator()
int IJK_Interfaces::get_recompute_indicator () const inline
References recompute_indicator_.
Referenced by calculer_indicatrice_intermediaire(), and calculer_indicatrice_next().
set_recompute_indicator()
void IJK_Interfaces::set_recompute_indicator (int i) inline
References recompute_indicator_.
Referenced by initialize().
follow_colors()
int IJK_Interfaces::follow_colors () const inline
References follow_colors_.
get_colors()
const ArrOfInt & IJK_Interfaces::get_colors () const inline
References through_yminus_.
ghost_compo_converter()
int IJK_Interfaces::ghost_compo_converter (const int i) const inline
References ghost_compo_converter_.
Referenced by compute_external_forces_color_function(), and compute_external_forces_parser().
portee_wall_repulsion()
double IJK_Interfaces::portee_wall_repulsion () const inline
References portee_wall_repulsion_.
delta_p_wall_max_repulsion()
double IJK_Interfaces::delta_p_wall_max_repulsion () const inline
References delta_p_wall_max_repulsion_.
set_reprise()
void IJK_Interfaces::set_reprise (const int i) inline
References reprise_.
Referenced by Switch_FT_double::initialise(), and set_fichier_reprise_interface().
set_fichier_sauvegarde()
void IJK_Interfaces::set_fichier_sauvegarde (const char * lataname) inline
References fichier_sauvegarde_interface_.
Referenced by Switch_FT_double::ecrire_fichier_reprise().
set_fichier_reprise()
void IJK_Interfaces::set_fichier_reprise (const char * lataname) inline
References fichier_reprise_interface_.
Referenced by Switch_FT_double::prepare_run().
set_seuil_indicatrice_petite()
void IJK_Interfaces::set_seuil_indicatrice_petite (double seuil_indicatrice_petite) inline
References Process::exit(), seuil_indicatrice_negligeable_, and seuil_indicatrice_petite_.
Referenced by Probleme_FTD_IJK_cut_cell::readOn().
get_fichier_reprise()
Nom IJK_Interfaces::get_fichier_reprise () inline
References fichier_reprise_interface_.
Referenced by Switch_FT_double::prepare_run().
lire_maillage_ft_dans_lata()
void IJK_Interfaces::lire_maillage_ft_dans_lata () inline
References fichier_reprise_interface_, lata_interfaces_meshname_, Maillage_FT_IJK::lire_maillage_ft_dans_lata(), maillage_ft_ijk_, and timestep_reprise_interface_.
Referenced by Switch_FT_double::initialise().
parcourir_maillage()
void IJK_Interfaces::parcourir_maillage () inline
References FT_Field::get_disable_surfactant(), maillage_ft_ijk_, Maillage_FT_IJK::parcourir_maillage(), ref_domaine_, Maillage_FT_IJK::Surfactant_facettes(), Maillage_FT_IJK::update_gradient_laplacien_Surfactant(), Maillage_FT_IJK::update_sigma_and_interfacial_source_term_sommet(), and use_tryggvason_interfacial_source_.
Referenced by calculer_indicatrice_intermediaire(), calculer_indicatrice_next(), and Probleme_FTD_IJK_base::parcourir_maillage().
RK3_G_store_vi_resize()
void IJK_Interfaces::RK3_G_store_vi_resize (int n, int n2) inline
References TRUSTTab< _TYPE_, _SIZE_ >::resize(), and RK3_G_store_vi_.
Referenced by Probleme_FTD_IJK_base::parcourir_maillage().
RK3_G_store_vi_echange_esp_vect()
void IJK_Interfaces::RK3_G_store_vi_echange_esp_vect () inline
References Maillage_FT_Disc::desc_sommets(), Desc_Structure_FT::echange_espace_virtuel(), maillage_ft_ijk_, and RK3_G_store_vi_.
Referenced by Probleme_FTD_IJK_base::parcourir_maillage().
set_positions_reference()
void IJK_Interfaces::set_positions_reference () inline
References calculer_volume_bulles(), flag_positions_reference_, and positions_reference_.
maillage_ft_ijk()
const Maillage_FT_IJK & IJK_Interfaces::maillage_ft_ijk () const inline
References maillage_ft_ijk_.
Referenced by IJK_Composantes_Connex::fill_mixed_cell_compo(), Probleme_FTD_IJK_base::get_maillage_ft_ijk(), Probleme_FTD_IJK_cut_cell::initialize(), Probleme_FTD_IJK_base::parcourir_maillage(), and IJK_One_Dimensional_Subproblems_Interfaces_Fields::retrieve_interfacial_surface_quantity().
old_maillage_ft_ijk()
const Maillage_FT_IJK & IJK_Interfaces::old_maillage_ft_ijk () const inline
References old_maillage_ft_ijk_.
Referenced by Probleme_FTD_IJK_cut_cell::initialize().
remaillage_ft_ijk()
const Remaillage_FT_IJK & IJK_Interfaces::remaillage_ft_ijk () const inline
References remaillage_ft_ijk_.
Referenced by Probleme_FTD_IJK_base::get_remaillage_ft_ijk().
RK3_G_store_vi()
const DoubleTab & IJK_Interfaces::RK3_G_store_vi () const inline
References RK3_G_store_vi_.
get_num_compo()
const IntVect & IJK_Interfaces::get_num_compo () const inline
References num_compo_.
get_compo_to_group()
const ArrOfInt & IJK_Interfaces::get_compo_to_group () const inline
References compo_to_group_.
compute_cell_phase_with_interface_normal()
int IJK_Interfaces::compute_cell_phase_with_interface_normal (int num_elem, int direction, int face_plus)
References Intersections_Elem_Facettes_Data::barycentre_, Intersections_Elem_Facettes::data_intersection(), Maillage_FT_Disc::facettes(), Intersections_Elem_Facettes_Data::fraction_surface_intersection_, Domaine_IJK::get_constant_delta(), Intersections_Elem_Facettes::get_liste_facettes_traversantes(), Intersections_Elem_Facettes::index_elem(), Intersections_Elem_Facettes_Data::index_facette_suivante_, Maillage_FT_Disc::intersections_elem_facettes(), maillage_ft_ijk_, Intersections_Elem_Facettes_Data::numero_facette_, Vecteur3::produit_vectoriel(), ref_domaine_, TRUSTArray< _TYPE_, _SIZE_ >::size_array(), Maillage_FT_Disc::sommets(), and TRUST_Ref< _CLASSE_ >::valeur().
calculer_kappa_ft()
void IJK_Interfaces::calculer_kappa_ft (IJK_Field_double & kappa_ft)
References IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::allocate(), Domaine_IJK::convert_packed_to_ijk_cell(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::data(), Intersections_Elem_Facettes::data_intersection(), Domaine_IJK::ELEM, Maillage_FT_Disc::facettes(), Intersections_Elem_Facettes_Data::fraction_surface_intersection_, IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_domaine(), Maillage_FT_Disc::get_update_courbure_sommets(), Maillage_FT_Disc::get_update_surface_facettes(), Intersections_Elem_Facettes_Data::index_element_suivant_, Intersections_Elem_Facettes::index_facette(), Maillage_FT_Disc::intersections_elem_facettes(), maillage_ft_ijk_, Maillage_FT_Disc::nb_facettes(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), and Intersections_Elem_Facettes_Data::numero_element_.
calculer_normales_et_aires_interfaciales()
void IJK_Interfaces::calculer_normales_et_aires_interfaciales (IJK_Field_double & ai, IJK_Field_double & kappa_ai, IJK_Field_vector3_double & normale_cell, const int igroup) const
Le champ de normale n'est pas sur une grille decallee. Il doit etre a la meme localisation que "ai" : Domaine_IJK::ELEM Le champ kappa_ai contient le produit de la courbure moyenne sur la cellule eulerienne par l'aire interfaciale dans cette cellule, divisee par le volume de la cellule.
Le calcul repose sur la conversion vdf -> ijk du numero : num_elem Pour que cette conversion soit valide, il faut que le champ soit sur le splitting_ft_ car le dom_vdf n'est pas construit pour le splitting ns. Par definition, mettre igroup a -1 pour inclure toutes les bulles
References Maillage_FT_IJK::compo_connexe_facettes(), compo_to_group_, Domaine_IJK::convert_packed_to_ijk_cell(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::data(), Intersections_Elem_Facettes::data_intersection(), Maillage_FT_Disc::facettes(), Intersections_Elem_Facettes_Data::fraction_surface_intersection_, Domaine_IJK::get_constant_delta(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_domaine(), Maillage_FT_Disc::get_update_courbure_sommets(), Maillage_FT_Disc::get_update_normale_facettes(), Maillage_FT_Disc::get_update_surface_facettes(), Intersections_Elem_Facettes_Data::index_element_suivant_, Intersections_Elem_Facettes::index_facette(), Maillage_FT_Disc::intersections_elem_facettes(), maillage_ft_ijk_, Maillage_FT_Disc::nb_facettes(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), and Intersections_Elem_Facettes_Data::numero_element_.
compute_list_compo_connex_in_element()
int IJK_Interfaces::compute_list_compo_connex_in_element (const Maillage_FT_IJK & mesh, const int elem, ArrOfInt & liste_composantes_connexes_dans_element) const
nb_groups()
const int & IJK_Interfaces::nb_groups () const inline
References nb_groups_.
Referenced by calculer_indicatrice_next().
get_distance_autres_interfaces()
const ArrOfDoubleFT & IJK_Interfaces::get_distance_autres_interfaces () const inline
References distance_autres_interfaces_.
get_ghost_number_from_compo()
int IJK_Interfaces::get_ghost_number_from_compo (const int compo) const
References Process::exit(), ghost_compo_converter_, and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by calculer_aspect_ratio(), calculer_vmoy_rotation_composantes_connexes(), calculer_vmoy_translation_composantes_connexes(), transporter_maillage_deformation(), transporter_maillage_remaillage(), and transporter_maillage_rigide().
calculer_surface_bulles()
void IJK_Interfaces::calculer_surface_bulles (ArrOfDouble & surfaces) const
References get_nb_bulles_ghost(), get_nb_bulles_reelles(), maillage_ft_ijk_, Maillage_FT_Disc::nb_facettes(), and TRUSTArray< _TYPE_, _SIZE_ >::resize_array().
Referenced by calculer_vecteurs_de_deplacement_rigide(), compute_external_forces_(), and transporter_maillage_remaillage().
compute_surface_average_per_bubble()
void IJK_Interfaces::compute_surface_average_per_bubble (const ArrOfDouble & surfaces, const ArrOfDouble & in, ArrOfDouble & out) const
References Maillage_FT_IJK::compo_connexe_facettes(), Maillage_FT_Disc::facette_virtuelle(), get_nb_bulles_reelles(), maillage_ft_ijk_, Maillage_FT_Disc::nb_facettes(), and TRUSTArray< _TYPE_, _SIZE_ >::resize_array().
read_bubbles_barycentres_old_new()
void IJK_Interfaces::read_bubbles_barycentres_old_new (const Nom & interf_name)
References bubbles_bary_new_, bubbles_bary_old_, bubbles_rising_vectors_bary_, bubbles_velocities_bary_, bubbles_velocities_bary_magnitude_, has_readen_barycentres_prev_, read_barycentres_velocity_, read_bubbles_barycentres(), read_bubbles_barycentres_vel(), reprise_, and use_barycentres_velocity_.
Referenced by initialize().
read_bubbles_barycentres_vel()
bool IJK_Interfaces::read_bubbles_barycentres_vel (const Nom & interf_name, FixedVector< ArrOfDouble, 3 > & bubbles_rising_dir, FixedVector< ArrOfDouble, 3 > & bubbles_rising_vel, ArrOfDouble & bubbles_rising_vel_mag)
References TRUSTArray< _TYPE_, _SIZE_ >::append_array(), Entree_Fichier_base::close(), IJK_Composantes_Connex::get_compute_compo_fields(), Entree_Fichier_base::get_ifstream(), ijk_compo_connex_, Objet_U::nom_du_cas(), TRUSTArray< _TYPE_, _SIZE_ >::reset(), and use_barycentres_velocity_.
Referenced by read_bubbles_barycentres_old_new().
read_bubbles_barycentres()
bool IJK_Interfaces::read_bubbles_barycentres (const Nom & interf_name, const Nom & suffix, FixedVector< ArrOfDouble, 3 > & bubbles_bary)
References Entree_Fichier_base::close(), IJK_Composantes_Connex::get_compute_compo_fields(), Entree_Fichier_base::get_ifstream(), ijk_compo_connex_, Objet_U::nom_du_cas(), and use_barycentres_velocity_.
Referenced by read_bubbles_barycentres_old_new().
store_bubbles_barycentres()
void IJK_Interfaces::store_bubbles_barycentres (const Nom & interf_name)
References bubbles_bary_new_, bubbles_bary_old_, bubbles_rising_vectors_bary_, bubbles_velocities_bary_, bubbles_velocities_bary_magnitude_, Sortie_Fichier_base::close(), IJK_Composantes_Connex::get_compute_compo_fields(), get_nb_bulles_reelles(), ijk_compo_connex_, Process::je_suis_maitre(), and use_barycentres_velocity_.
Referenced by sauvegarder_interfaces().
compute_bubbles_volume_and_barycentres()
void IJK_Interfaces::compute_bubbles_volume_and_barycentres (ArrOfDouble & volumes, DoubleTab & barycentres, const int & store_values)
References bubbles_bary_new_, bubbles_bary_old_, bubbles_rising_vectors_bary_, bubbles_velocities_bary_, bubbles_velocities_bary_magnitude_, calculer_volume_bulles(), Domaine_IJK::get_domain_length(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_domaine(), get_nb_bulles_reelles(), has_computed_bubble_barycentres_, has_readen_barycentres_prev_, I(), ref_ijk_ft_, and TRUSTArray< _TYPE_, _SIZE_ >::resize().
Referenced by calculer_vecteurs_de_deplacement_rigide(), and IJK_Composantes_Connex::compute_compo_connex_from_interface().
calculer_volume_bulles()
void IJK_Interfaces::calculer_volume_bulles (ArrOfDouble & volumes, DoubleTab & centre_gravite) const
References get_nb_bulles_ghost(), get_nb_bulles_reelles(), maillage_ft_ijk_, Maillage_FT_Disc::nb_facettes(), and TRUSTArray< _TYPE_, _SIZE_ >::resize_array().
Referenced by calculer_aspect_ratio(), calculer_bounding_box_bulles(), calculer_vecteurs_de_deplacement_rigide(), compute_bubbles_volume_and_barycentres(), compute_external_forces_(), deplacer_bulle_perio(), dupliquer_bulle_perio(), IJK_Composantes_Connex::initialise_bubbles_params(), initialize(), and set_positions_reference().
calculer_aspect_ratio()
void IJK_Interfaces::calculer_aspect_ratio (ArrOfDouble & aspect_ratio) const
References calculer_volume_bulles(), Maillage_FT_IJK::compo_connexe_facettes(), Maillage_FT_Disc::facette_virtuelle(), Maillage_FT_Disc::facettes(), get_ghost_number_from_compo(), get_nb_bulles_ghost(), get_nb_bulles_reelles(), maillage_ft_ijk_, Maillage_FT_Disc::nb_facettes(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), and Maillage_FT_Disc::sommets().
calculer_surfactant()
void IJK_Interfaces::calculer_surfactant (ArrOfDouble & surfactant, ArrOfDouble & surfactant_min, ArrOfDouble & surfactant_max) const
References Maillage_FT_IJK::compo_connexe_facettes(), Maillage_FT_Disc::facette_virtuelle(), FT_Field::get_disable_surfactant(), FT_Field::get_FT_field_Array(), get_nb_bulles_reelles(), Maillage_FT_Disc::get_update_surface_facettes(), maillage_ft_ijk_, Process::mp_max(), Process::mp_min(), Process::mp_sum(), Maillage_FT_Disc::nb_facettes(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), and Maillage_FT_IJK::Surfactant_facettes().
calculer_poussee_bulles()
void IJK_Interfaces::calculer_poussee_bulles (const DoubleTab & gravite, DoubleTab & poussee) const
References get_nb_bulles_ghost(), get_nb_bulles_reelles(), maillage_ft_ijk_, Maillage_FT_Disc::nb_facettes(), and TRUSTTab< _TYPE_, _SIZE_ >::resize().
calculer_aire_interfaciale()
void IJK_Interfaces::calculer_aire_interfaciale (IJK_Field_double & ai) const
References Domaine_IJK::convert_packed_to_ijk_cell(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::data(), Intersections_Elem_Facettes::data_intersection(), Intersections_Elem_Facettes_Data::fraction_surface_intersection_, Domaine_IJK::get_constant_delta(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_domaine(), Maillage_FT_Disc::get_update_surface_facettes(), Intersections_Elem_Facettes_Data::index_element_suivant_, Intersections_Elem_Facettes::index_facette(), Maillage_FT_Disc::intersections_elem_facettes(), maillage_ft_ijk_, Maillage_FT_Disc::nb_facettes(), and Intersections_Elem_Facettes_Data::numero_element_.
calculer_aire_interfaciale_for_compo() [1/2]
void IJK_Interfaces::calculer_aire_interfaciale_for_compo (IJK_Field_double & ai, const int compo) const
References Maillage_FT_IJK::compo_connexe_facettes(), Domaine_IJK::convert_packed_to_ijk_cell(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::data(), Intersections_Elem_Facettes::data_intersection(), Intersections_Elem_Facettes_Data::fraction_surface_intersection_, Domaine_IJK::get_constant_delta(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_domaine(), Maillage_FT_Disc::get_update_surface_facettes(), Intersections_Elem_Facettes_Data::index_element_suivant_, Intersections_Elem_Facettes::index_facette(), Maillage_FT_Disc::intersections_elem_facettes(), maillage_ft_ijk_, Maillage_FT_Disc::nb_facettes(), and Intersections_Elem_Facettes_Data::numero_element_.
calculer_aire_interfaciale_for_compo() [2/2]
double IJK_Interfaces::calculer_aire_interfaciale_for_compo (const int compo, const int i_ref, const int j_ref, const int k_ref) const
References Maillage_FT_IJK::compo_connexe_facettes(), Domaine_IJK::convert_packed_to_ijk_cell(), Intersections_Elem_Facettes::data_intersection(), Intersections_Elem_Facettes_Data::fraction_surface_intersection_, Domaine_IJK::get_constant_delta(), Maillage_FT_IJK::get_domaine(), Maillage_FT_Disc::get_update_surface_facettes(), Intersections_Elem_Facettes_Data::index_element_suivant_, Intersections_Elem_Facettes::index_facette(), Maillage_FT_Disc::intersections_elem_facettes(), maillage_ft_ijk_, Maillage_FT_Disc::nb_facettes(), and Intersections_Elem_Facettes_Data::numero_element_.
calculer_normale_et_aire_interfaciale()
void IJK_Interfaces::calculer_normale_et_aire_interfaciale (IJK_Field_double & ai, IJK_Field_double & kappa_ai, IJK_Field_vector3_double & normale_cell) const
compute_drapeaux_vapeur_v2()
void IJK_Interfaces::compute_drapeaux_vapeur_v2 (const IntVect & vecteur_composantes, ArrOfInt & drapeau_liquide) const
Referenced by calculer_indicatrice().
compute_drapeaux_vapeur_v3()
void IJK_Interfaces::compute_drapeaux_vapeur_v3 (const Maillage_FT_IJK & mesh, const Domaine_IJK & split, const IntVect & vecteur_composantes, ArrOfInt & drapeau_vapeur) const
Referenced by calculer_indicatrice().
compute_drapeaux_vapeur_v4()
void IJK_Interfaces::compute_drapeaux_vapeur_v4 (const IntVect & vecteur_composantes, ArrOfInt & drapeau_vapeur) const
References Intersections_Elem_Facettes_Data::barycentre_, Statistiques::begin_count(), Intersections_Elem_Facettes::data_intersection(), Domaine_VF::elem_faces(), Statistiques::end_count(), Domaine_VF::face_voisins(), Maillage_FT_Disc::facettes(), Intersections_Elem_Facettes_Data::fraction_surface_intersection_, Domaine_IJK::get_constant_delta(), Intersections_Elem_Facettes::index_elem(), Intersections_Elem_Facettes_Data::index_element_suivant_, Intersections_Elem_Facettes::index_facette(), Maillage_FT_Disc::intersections_elem_facettes(), Process::je_suis_maitre(), maillage_ft_ijk_, Maillage_FT_Disc::nb_facettes(), Statistiques::new_counter(), Intersections_Elem_Facettes_Data::numero_element_, Intersections_Elem_Facettes_Data::numero_facette_, Vecteur3::produit_vectoriel(), ref_domaine_, refdomaine_dis_, TRUSTArray< _TYPE_, _SIZE_ >::size_array(), Maillage_FT_Disc::sommets(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by calculer_indicatrice(), and calculer_indicatrices().
convert_to_IntVect()
void IJK_Interfaces::convert_to_IntVect (const ArrOfInt & in, IntVect & out) const
References Domaine_dis_base::domaine(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), TRUSTArray< _TYPE_, _SIZE_ >::inject_array(), refdomaine_dis_, TRUSTVect< _TYPE_, _SIZE_ >::size(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and TRUST_Ref< _CLASSE_ >::valeur().
ajouter_terme_source_interfaces()
void IJK_Interfaces::ajouter_terme_source_interfaces (IJK_Field_vector3_double & vpoint, IJK_Field_vector3_double & vrepul, IJK_Field_vector3_double & vabsrepul) const
References bary_par_compo_, Statistiques::begin_count(), compos_traversantes_, correction_gradient_potentiel_, Statistiques::end_count(), Domaine_IJK::get_constant_delta(), Domaine_IJK::get_coords_of_dof(), FT_Field::get_disable_marangoni_source_term(), Domaine_IJK::get_nb_items_global(), Domaine_IJK::get_offset_local(), Domaine_IJK::get_periodic_flag(), indicatrice_par_compo_, maillage_ft_ijk_, normale_par_compo_, old(), phi_par_compo_, Vecteur3::produit_scalaire(), ref_domaine_, repuls_par_compo_, source_interf_par_compo_, surf_par_compo_, surface_par_compo_, Maillage_FT_IJK::Surfactant_facettes(), use_tryggvason_interfacial_source_, and TRUST_Ref< _CLASSE_ >::valeur().
remailler_interface()
void IJK_Interfaces::remailler_interface (const double temps, Maillage_FT_IJK & maillage, ArrOfDouble & var_volume, Remaillage_FT_IJK & algo_remaillage_local)
References Remaillage_FT::a_remailler(), Remaillage_FT_IJK::barycentrer_lisser_systematique_ijk(), FT_Field::get_only_remaillage(), maillage_ft_ijk_, Remaillage_FT_IJK::remaillage_local_interface(), and Maillage_FT_IJK::Surfactant_facettes().
Referenced by transporter_maillage_remaillage().
is_terme_gravite_rhog()
int IJK_Interfaces::is_terme_gravite_rhog () const
References GRAVITE_RHO_G, and terme_gravite_.
detecter_et_supprimer_rejeton()
void IJK_Interfaces::detecter_et_supprimer_rejeton (bool duplicatas_etaient_presents)
References Maillage_FT_IJK::compo_connexe_facettes(), creer_duplicata_bulles(), Maillage_FT_Disc::get_update_surface_facettes(), maillage_ft_ijk_, nb_bulles_reelles_, Maillage_FT_Disc::nb_facettes(), Maillage_FT_IJK::parcourir_maillage(), Maillage_FT_IJK::set_composante_connexe(), and supprimer_duplicata_bulles().
Referenced by Probleme_FTD_IJK_base::preparer_calcul().
update_surface_normale()
void IJK_Interfaces::update_surface_normale () const
References Maillage_FT_Disc::get_update_normale_facettes(), Maillage_FT_Disc::get_update_surface_facettes(), maillage_ft_ijk_, and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
get_maillage_MED_from_IJK_FT()
static void IJK_Interfaces::get_maillage_MED_from_IJK_FT (MEDCouplingUMesh * maillage_bulles_mcu, const Maillage_FT_IJK & maillage_bulles_ft_ijk) static
get_surface_interface_old_ft()
const IJK_Field_double & IJK_Interfaces::get_surface_interface_old_ft () const inline
References old(), and surface_interface_ft_.
get_surface_interface_old()
const IJK_Field_double & IJK_Interfaces::get_surface_interface_old () const inline
References old(), and surface_interface_ns_.
Referenced by Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_semi_lagrangien().
get_surface_interface_next_ft()
const IJK_Field_double & IJK_Interfaces::get_surface_interface_next_ft () const inline
References next(), and surface_interface_ft_.
get_surface_interface_next()
const IJK_Field_double & IJK_Interfaces::get_surface_interface_next () const inline
References next(), and surface_interface_ns_.
get_barycentre_phase1_old_ft()
const IJK_Field_vector3_double & IJK_Interfaces::get_barycentre_phase1_old_ft () const inline
References barycentre_phase1_ft_, and old().
get_barycentre_phase1_old()
const IJK_Field_vector3_double & IJK_Interfaces::get_barycentre_phase1_old () const inline
References barycentre_phase1_ns_, and old().
get_barycentre_phase1_next_ft()
const IJK_Field_vector3_double & IJK_Interfaces::get_barycentre_phase1_next_ft () const inline
References barycentre_phase1_ft_, and next().
get_barycentre_phase1_next()
const IJK_Field_vector3_double & IJK_Interfaces::get_barycentre_phase1_next () const inline
References barycentre_phase1_ns_, and next().
get_barycentre()
double IJK_Interfaces::get_barycentre (bool next_time, int bary_compo, int phase, int i, int j, int k) const
References barycentre_phase1_ns_, I(), In(), next(), old(), and opposing_barycentre().
Referenced by Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_semi_lagrangien(), Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_semi_lagrangien_interpolate(), and calculer_vitesse_de_deformation().
get_barycentre_face()
double IJK_Interfaces::get_barycentre_face (bool next_time, int face_dir, int bary_compo, int phase, int i, int j, int k) const
References barycentre_phase1_face_ns_, get_indicatrice_surfacique_face_next(), get_indicatrice_surfacique_face_old(), next(), old(), and opposing_barycentre().
get_surface_vapeur_par_face_ft()
const IJK_Field_vector3_double & IJK_Interfaces::get_surface_vapeur_par_face_ft () const inline
References old(), and surface_vapeur_par_face_.
get_surface_vapeur_par_face()
const IJK_Field_vector3_double & IJK_Interfaces::get_surface_vapeur_par_face () const inline
References old(), and surface_vapeur_par_face_ns_.
Referenced by Intersection_Interface_ijk_face::calcul_projection_bary_face_mouillee_interface_moy().
get_indicatrice_surfacique_face_ft()
const IJK_Field_vector3_double & IJK_Interfaces::get_indicatrice_surfacique_face_ft () const inline
References indicatrice_surfacique_face_ft_, and old().
get_indicatrice_surfacique_face_old()
const IJK_Field_vector3_double & IJK_Interfaces::get_indicatrice_surfacique_face_old () const inline
References indicatrice_surfacique_face_ns_, and old().
Referenced by get_barycentre_face().
get_indicatrice_surfacique_face_next()
const IJK_Field_vector3_double & IJK_Interfaces::get_indicatrice_surfacique_face_next () const inline
References indicatrice_surfacique_face_ns_, and next().
Referenced by get_barycentre_face().
get_indicatrice_surfacique_efficace_face()
const DoubleTabFT_cut_cell_vector3 & IJK_Interfaces::get_indicatrice_surfacique_efficace_face () const inline
References indicatrice_surfacique_efficace_face_.
Referenced by Cut_cell_schema_auxiliaire::add_small_nascent_cells(), Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_ponderation_voisin(), Cut_cell_schema_auxiliaire::compute_flux_dying_cells(), Cut_cell_schema_auxiliaire::compute_flux_small_nascent_cells(), Cut_cell_convection_auxiliaire::dying_cells_flux(), Cut_cell_diffusion_auxiliaire::dying_cells_flux(), Cut_cell_convection_auxiliaire::small_nascent_cells_flux(), and Cut_cell_diffusion_auxiliaire::small_nascent_cells_flux().
get_surface_efficace_interface()
const DoubleTabFT_cut_cell_scalar & IJK_Interfaces::get_surface_efficace_interface () const inline
References surface_efficace_interface_.
get_vitesse_deplacement_interface()
const DoubleTabFT_cut_cell_vector3 & IJK_Interfaces::get_vitesse_deplacement_interface () const inline
References vitesse_deplacement_interface_.
Referenced by Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_semi_lagrangien(), and Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_semi_lagrangien_interpolate().
get_normale_deplacement_interface()
const DoubleTabFT_cut_cell_vector3 & IJK_Interfaces::get_normale_deplacement_interface () const inline
References normale_deplacement_interface_.
Referenced by Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_semi_lagrangien(), Cut_cell_diffusion_auxiliaire::dying_cells_flux(), and Cut_cell_diffusion_auxiliaire::small_nascent_cells_flux().
get_coord_deplacement_interface()
const DoubleTabFT_cut_cell_vector3 & IJK_Interfaces::get_coord_deplacement_interface () const inline
References coord_deplacement_interface_.
get_barycentre_vapeur_par_face_ft()
const FixedVector< IJK_Field_vector3_double, 3 > & IJK_Interfaces::get_barycentre_vapeur_par_face_ft () const inline
References barycentre_vapeur_par_face_, and old().
get_barycentre_vapeur_par_face()
const FixedVector< IJK_Field_vector3_double, 3 > & IJK_Interfaces::get_barycentre_vapeur_par_face () const inline
References barycentre_vapeur_par_face_ns_, and old().
Referenced by Intersection_Interface_ijk_face::calcul_projection_bary_face_mouillee_interface_moy().
get_barycentre_phase1_face_ft()
const FixedVector< FixedVector< IJK_Field_double, 2 >, 3 > & IJK_Interfaces::get_barycentre_phase1_face_ft () const inline
References barycentre_phase1_face_ft_, and old().
get_barycentre_phase1_face()
const FixedVector< FixedVector< IJK_Field_double, 2 >, 3 > & IJK_Interfaces::get_barycentre_phase1_face () const inline
References barycentre_phase1_face_ns_, and old().
opposing_barycentre()
static double IJK_Interfaces::opposing_barycentre (double initial_barycentre, double initial_area) inline static
References opposing_barycentre().
Referenced by get_barycentre(), get_barycentre_face(), and opposing_barycentre().
get_nb_face_mouillees()
int IJK_Interfaces::get_nb_face_mouillees () const inline
References n_faces_mouilles_, and old().
Referenced by Intersection_Interface_ijk_face::calcul_projection_bary_face_mouillee_interface_moy().
mean_over_compo() [1/3]
static double IJK_Interfaces::mean_over_compo (const FixedVector< IJK_Field_double, max_authorized_nb_of_components_ > & field_for_compo, const IJK_Field_int & nb_compo_traversante, const int i, const int j, const int k) inline static
Referenced by calculer_indicatrice_next(), and SI().
mean_over_compo() [2/3]
static void IJK_Interfaces::mean_over_compo (const FixedVector< IJK_Field_double, 3 *max_authorized_nb_of_components_ > & field_for_compo, const IJK_Field_int & nb_compo_traversante, IJK_Field_vector3_double & mean_par_compo_field) inline static
References IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), and IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk().
mean_over_compo() [3/3]
static double IJK_Interfaces::mean_over_compo (const FixedVector< IJK_Field_double, 3 *max_authorized_nb_of_components_ > & field_for_compo, const IJK_Field_int & nb_compo_traversante, const int dir, const int i, const int j, const int k) inline static
old()
int IJK_Interfaces::old () const inline
References old_en_premier_.
Referenced by ajouter_terme_source_interfaces(), BoI(), devient_diphasique(), devient_pure(), get_bary_par_compo_itfc_in_cell_ft(), get_barycentre(), get_barycentre_face(), get_barycentre_phase1_face(), get_barycentre_phase1_face_ft(), get_barycentre_phase1_old(), get_barycentre_phase1_old_ft(), get_barycentre_vapeur_par_face(), get_barycentre_vapeur_par_face_ft(), get_indicatrice_surfacique_face_ft(), get_indicatrice_surfacique_face_old(), get_nb_face_mouillees(), get_norm_par_compo_itfc_in_cell_ft(), get_surface_interface_old(), get_surface_interface_old_ft(), get_surface_vapeur_par_face(), get_surface_vapeur_par_face_ft(), groups_indicatrice_ft(), groups_indicatrice_ns(), I(), I_ft(), initialize(), nI(), phase_mourrante(), phase_naissante(), Sf(), Sfm(), SI(), switch_indicatrice_next_old(), Probleme_FTD_IJK_cut_cell::update_twice_indicator_field(), and xI().
next()
int IJK_Interfaces::next () const inline
References old_en_premier_.
Referenced by BoIn(), calculer_indicatrice_intermediaire(), calculer_indicatrice_next(), calculer_var_volume_remaillage(), devient_diphasique(), devient_pure(), get_barycentre(), get_barycentre_face(), get_barycentre_phase1_next(), get_barycentre_phase1_next_ft(), get_indicatrice_surfacique_face_next(), get_surface_interface_next(), get_surface_interface_next_ft(), groups_indicatrice_n_ft(), groups_indicatrice_n_ns(), imprime_bilan_indicatrice(), In(), In_ft(), initialize(), nb_compo_traversantes(), nIn(), phase_mourrante(), phase_naissante(), Sfm(), Sfn(), and xIn().
get_bary_par_compo_itfc_in_cell_ft()
const FixedVector< IJK_Field_double, max_authorized_nb_of_components_ *3 > & IJK_Interfaces::get_bary_par_compo_itfc_in_cell_ft () const inline
References bary_par_compo_, and old().
get_norm_par_compo_itfc_in_cell_ft()
const FixedVector< IJK_Field_double, max_authorized_nb_of_components_ *3 > & IJK_Interfaces::get_norm_par_compo_itfc_in_cell_ft () const inline
References normale_par_compo_, and old().
I_ft() [1/2]
const IJK_Field_double & IJK_Interfaces::I_ft () const inline
References indicatrice_ft_, and old().
Referenced by calculer_distance_autres_compo_connexe_ijk(), and calculer_var_volume_remaillage().
I_ft() [2/2]
const double & IJK_Interfaces::I_ft (const int i, const int j, const int k) const inline
References indicatrice_ft_, and old().
In_ft() [1/2]
const IJK_Field_double & IJK_Interfaces::In_ft () const inline
References indicatrice_ft_, and next().
In_ft() [2/2]
const double & IJK_Interfaces::In_ft (const int i, const int j, const int k) const inline
References indicatrice_ft_, and next().
BoI()
const IJK_Field_vector3_double & IJK_Interfaces::BoI () const inline
References bary_of_interf_ns_, and old().
BoIn()
const IJK_Field_vector3_double & IJK_Interfaces::BoIn () const inline
References bary_of_interf_ns_, and next().
I() [1/2]
const IJK_Field_double & IJK_Interfaces::I () const inline
References indicatrice_ns_, and old().
Referenced by Cut_cell_schema_auxiliaire::add_dying_cells(), Cut_cell_schema_auxiliaire::add_small_nascent_cells(), Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_copie_directe(), Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_ponderation_voisin(), Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_semi_lagrangien(), Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_semi_lagrangien_interpolate(), compute_bubbles_volume_and_barycentres(), Cut_cell_schema_auxiliaire::compute_flux_dying_cells(), Cut_cell_schema_auxiliaire::compute_flux_small_nascent_cells(), Probleme_FTD_IJK_cut_cell::deplacer_interfaces(), Probleme_FTD_IJK_cut_cell::deplacer_interfaces_rk3(), Cut_cell_convection_auxiliaire::dying_cells_flux(), Cut_cell_diffusion_auxiliaire::dying_cells_flux(), IJK_One_Dimensional_Subproblem::find_cell_related_indicator_on_probes(), IJK_One_Dimensional_Subproblem_Geometry::find_cell_related_indicator_on_probes(), get_barycentre(), I_nonzero(), In_nonzero(), IJK_One_Dimensional_Subproblem::interpolate_indicator_on_probes(), IJK_One_Dimensional_Subproblem_Geometry::interpolate_indicator_on_probes(), Intersection_Interface_ijk_cell::update_interpolations_cell_centres_on_interface(), Intersection_Interface_ijk_cell::update_interpolations_cell_faces_on_interface(), and Probleme_FTD_IJK_cut_cell::update_twice_indicator_field().
In() [1/2]
const IJK_Field_double & IJK_Interfaces::In () const inline
References indicatrice_ns_, and next().
Referenced by Cut_cell_schema_auxiliaire::add_dying_cells(), Cut_cell_schema_auxiliaire::add_small_nascent_cells(), Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_copie_directe(), Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_ponderation_voisin(), Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_semi_lagrangien(), Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_semi_lagrangien_interpolate(), IJK_Composantes_Connex::compute_compo_connex_from_interface(), Cut_cell_schema_auxiliaire::compute_flux_dying_cells(), Cut_cell_schema_auxiliaire::compute_flux_small_nascent_cells(), Probleme_FTD_IJK_cut_cell::deplacer_interfaces(), Probleme_FTD_IJK_cut_cell::deplacer_interfaces_rk3(), Cut_cell_convection_auxiliaire::dying_cells_flux(), get_barycentre(), I_nonzero(), In_nonzero(), Cut_cell_convection_auxiliaire::small_nascent_cells_flux(), Cut_cell_diffusion_auxiliaire::small_nascent_cells_flux(), Intersection_Interface_ijk_cell::update_interpolations_cell_centres_on_interface_new(), Intersection_Interface_ijk_cell::update_interpolations_cell_faces_on_interface_new(), and Probleme_FTD_IJK_cut_cell::update_twice_indicator_field().
I() [2/2]
double IJK_Interfaces::I (const int i, const int j, const int k) const inline
References indicatrice_ns_, and old().
In() [2/2]
double IJK_Interfaces::In (const int i, const int j, const int k) const inline
References indicatrice_ns_, and next().
convert_indicatrice_to_phase()
static int IJK_Interfaces::convert_indicatrice_to_phase (double indicatrice) inline static
References est_pure().
Referenced by Cut_cell_schema_auxiliaire::add_dying_cells(), Cut_cell_schema_auxiliaire::add_small_nascent_cells(), Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_copie_directe(), Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_ponderation_voisin(), Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_semi_lagrangien(), Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_semi_lagrangien_interpolate(), Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::check_agreement_diph_pure_cellules_finalement_pures(), Cut_cell_schema_auxiliaire::compute_flux_dying_cells(), Cut_cell_schema_auxiliaire::compute_flux_small_nascent_cells(), Cut_cell_convection_auxiliaire::dying_cells_flux(), phase_mourrante(), phase_naissante(), Cut_cell_convection_auxiliaire::small_nascent_cells_flux(), Cut_cell_double::verify_consistency_within_layer(), and Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::vide_phase_invalide_cellules_diphasiques().
I_nonzero()
double IJK_Interfaces::I_nonzero (const int phase, const int i, const int j, const int k) const inline
References I(), and In().
In_nonzero()
double IJK_Interfaces::In_nonzero (const int phase, const int i, const int j, const int k) const inline
References I(), and In().
Referenced by Cut_cell_schema_auxiliaire::add_dying_cells().
est_pure()
static int IJK_Interfaces::est_pure (double indicatrice) inline static
Referenced by Cut_cell_schema_auxiliaire::add_dying_cells(), Cut_cell_schema_auxiliaire::add_small_nascent_cells(), below_small_threshold(), Cut_cell_surface_efficace::calcul_surface_interface_efficace_initiale(), Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_copie_directe(), Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_ponderation_voisin(), Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_semi_lagrangien(), Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_semi_lagrangien_interpolate(), calculer_barycentre(), calculer_indicatrice_surfacique_barycentre_face(), calculer_indicatrice_surfacique_face(), calculer_surface_interface(), Cut_cell_schema_auxiliaire::compute_flux_dying_cells(), Cut_cell_schema_auxiliaire::compute_flux_small_nascent_cells(), convert_indicatrice_to_phase(), devient_diphasique(), devient_pure(), est_desequilibre(), Cut_cell_surface_efficace::imprimer_informations_surface_efficace_face(), and Cut_cell_surface_efficace::imprimer_informations_surface_efficace_interface().
devient_pure() [1/2]
static int IJK_Interfaces::devient_pure (double old_indicatrice, double next_indicatrice) inline static
References est_pure().
Referenced by a_desequilibre_initial_uniquement(), Cut_cell_surface_efficace::calcul_surface_face_efficace_initiale(), Cut_cell_surface_efficace::calcul_surface_face_efficace_iteratif(), Cut_cell_surface_efficace::calcul_surface_interface_efficace_initiale(), Cut_cell_surface_efficace::imprimer_informations_surface_efficace_face(), Cut_cell_surface_efficace::imprimer_informations_surface_efficace_interface(), only_old_below_small_threhshold(), and phase_mourrante().
devient_diphasique() [1/2]
static int IJK_Interfaces::devient_diphasique (double old_indicatrice, double next_indicatrice) inline static
References est_pure().
Referenced by a_desequilibre_final(), Cut_cell_surface_efficace::calcul_surface_face_efficace_initiale(), Cut_cell_surface_efficace::calcul_surface_face_efficace_iteratif(), Cut_cell_surface_efficace::calcul_surface_interface_efficace_initiale(), Cut_cell_surface_efficace::imprimer_informations_surface_efficace_face(), Cut_cell_surface_efficace::imprimer_informations_surface_efficace_interface(), next_below_small_threshold(), and phase_naissante().
phase_mourrante() [1/2]
static int IJK_Interfaces::phase_mourrante (int phase, double old_indicatrice, double next_indicatrice) inline static
References convert_indicatrice_to_phase(), and devient_pure().
Referenced by Cut_cell_schema_auxiliaire::add_small_nascent_cells(), Cut_cell_schema_auxiliaire::compute_flux_dying_cells(), and Cut_cell_schema_auxiliaire::compute_flux_small_nascent_cells().
phase_naissante() [1/2]
static int IJK_Interfaces::phase_naissante (int phase, double old_indicatrice, double next_indicatrice) inline static
References convert_indicatrice_to_phase(), and devient_diphasique().
Referenced by Cut_cell_schema_auxiliaire::add_small_nascent_cells(), Cut_cell_schema_auxiliaire::compute_flux_dying_cells(), and Cut_cell_schema_auxiliaire::compute_flux_small_nascent_cells().
devient_pure() [2/2]
double IJK_Interfaces::devient_pure (const int i, const int j, const int k) const inline
References devient_pure(), indicatrice_ns_, next(), and old().
Referenced by devient_pure().
devient_diphasique() [2/2]
double IJK_Interfaces::devient_diphasique (const int i, const int j, const int k) const inline
References devient_diphasique(), indicatrice_ns_, next(), and old().
Referenced by devient_diphasique().
phase_mourrante() [2/2]
double IJK_Interfaces::phase_mourrante (const int phase, const int i, const int j, const int k) const inline
References indicatrice_ns_, next(), old(), and phase_mourrante().
Referenced by phase_mourrante().
phase_naissante() [2/2]
double IJK_Interfaces::phase_naissante (const int phase, const int i, const int j, const int k) const inline
References indicatrice_ns_, next(), old(), and phase_naissante().
Referenced by phase_naissante().
est_reguliere()
int IJK_Interfaces::est_reguliere (double old_indicatrice, double next_indicatrice) const inline
References seuil_indicatrice_petite_.
est_desequilibre()
int IJK_Interfaces::est_desequilibre (double indicatrice) const inline
References est_pure(), and seuil_indicatrice_petite_.
Referenced by a_desequilibre_final(), and a_desequilibre_initial_uniquement().
a_desequilibre_final()
int IJK_Interfaces::a_desequilibre_final (double old_indicatrice, double next_indicatrice) const inline
References devient_diphasique(), and est_desequilibre().
Referenced by a_desequilibre_initial_uniquement().
a_desequilibre_initial_uniquement()
int IJK_Interfaces::a_desequilibre_initial_uniquement (double old_indicatrice, double next_indicatrice) const inline
References a_desequilibre_final(), devient_pure(), and est_desequilibre().
below_small_threshold()
int IJK_Interfaces::below_small_threshold (double indicatrice) const inline
References est_pure(), and seuil_indicatrice_petite_.
Referenced by Cut_cell_schema_auxiliaire::add_small_nascent_cells(), Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_copie_directe(), Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_ponderation_voisin(), Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_semi_lagrangien(), Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_semi_lagrangien_interpolate(), Cut_cell_schema_auxiliaire::compute_flux_small_nascent_cells(), next_below_small_threshold(), and only_old_below_small_threhshold().
next_below_small_threshold()
int IJK_Interfaces::next_below_small_threshold (double old_indicatrice, double next_indicatrice) const inline
References below_small_threshold(), and devient_diphasique().
Referenced by next_below_small_threshold_for_phase(), and only_old_below_small_threhshold().
only_old_below_small_threhshold()
int IJK_Interfaces::only_old_below_small_threhshold (double old_indicatrice, double next_indicatrice) const inline
References below_small_threshold(), devient_pure(), and next_below_small_threshold().
Referenced by only_old_below_small_threshold_for_phase().
next_below_small_threshold_for_phase()
int IJK_Interfaces::next_below_small_threshold_for_phase (int phase, double old_indicatrice, double next_indicatrice) const inline
References next_below_small_threshold().
Referenced by Cut_cell_schema_auxiliaire::add_small_nascent_cells(), Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_ponderation_voisin(), and Cut_cell_schema_auxiliaire::compute_flux_small_nascent_cells().
only_old_below_small_threshold_for_phase()
int IJK_Interfaces::only_old_below_small_threshold_for_phase (int phase, double old_indicatrice, double next_indicatrice) const inline
References only_old_below_small_threhshold().
SI() [1/2]
const double & IJK_Interfaces::SI (const int compo, const int i, const int j, const int k) const inline
References old(), and surface_par_compo_.
SI() [2/2]
double IJK_Interfaces::SI (const int i, const int j, const int k) const inline
References mean_over_compo(), nb_compo_traversante_, old(), and surface_par_compo_.
groups_indicatrice_ft()
const IJK_Field_vector< double, max_authorized_nb_of_groups_ > & IJK_Interfaces::groups_indicatrice_ft () const inline
References groups_indicatrice_ft_, and old().
groups_indicatrice_ns()
const IJK_Field_vector< double, max_authorized_nb_of_groups_ > & IJK_Interfaces::groups_indicatrice_ns () const inline
References groups_indicatrice_ns_, and old().
groups_indicatrice_n_ft()
const IJK_Field_vector< double, max_authorized_nb_of_groups_ > & IJK_Interfaces::groups_indicatrice_n_ft () const inline
References groups_indicatrice_ft_, and next().
groups_indicatrice_n_ns()
const IJK_Field_vector< double, max_authorized_nb_of_groups_ > & IJK_Interfaces::groups_indicatrice_n_ns () const inline
References groups_indicatrice_ns_, and next().
nI() [1/2]
const double & IJK_Interfaces::nI (const int compo, const int i, const int j, const int k) const inline
References normal_of_interf_ns_, and old().
Referenced by Intersection_Interface_ijk::get_mean_interface_cell().
nI() [2/2]
Vecteur3 IJK_Interfaces::nI (const int i, const int j, const int k) const inline
References normal_of_interf_ns_, and old().
nIn() [1/2]
const double & IJK_Interfaces::nIn (const int compo, const int i, const int j, const int k) const inline
References next(), and normal_of_interf_ns_.
nIn() [2/2]
Vecteur3 IJK_Interfaces::nIn (const int i, const int j, const int k) const inline
References next(), and normal_of_interf_ns_.
xI() [1/2]
const double & IJK_Interfaces::xI (const int compo, const int i, const int j, const int k) const inline
References bary_of_interf_ns_, and old().
Referenced by Intersection_Interface_ijk::get_mean_interface_cell().
xIn()
Vecteur3 IJK_Interfaces::xIn (const int i, const int j, const int k) const inline
References bary_of_interf_ns_, and next().
xI() [2/2]
Vecteur3 IJK_Interfaces::xI (const int i, const int j, const int k) const inline
References bary_of_interf_ns_, and old().
Sf()
const double & IJK_Interfaces::Sf (const int compo, const int i, const int j, const int k) const inline
References old(), and surface_vapeur_par_face_ns_.
Sfn()
const double & IJK_Interfaces::Sfn (const int compo, const int i, const int j, const int k) const inline
References next(), and surface_vapeur_par_face_ns_.
Sfm()
double IJK_Interfaces::Sfm (const int compo, const int i, const int j, const int k) const inline
References next(), old(), and surface_vapeur_par_face_ns_.
update_old_intersections()
void IJK_Interfaces::update_old_intersections ()
References Maillage_FT_Disc::COMPLET, maillage_ft_ijk_, old_maillage_ft_ijk_, and Maillage_FT_IJK::recopie().
Referenced by Probleme_FTD_IJK_base::update_old_intersections().
switch_indicatrice_next_old()
void IJK_Interfaces::switch_indicatrice_next_old ()
References bary_of_interf_, bary_of_interf_ns_, bary_par_compo_, barycentre_phase1_face_ft_, barycentre_phase1_face_ns_, barycentre_phase1_ft_, barycentre_phase1_ns_, barycentre_vapeur_par_face_, barycentre_vapeur_par_face_ns_, Option_IJK::DISABLE_DIPHASIQUE, FixedVector< T, N >::echange_espace_virtuel(), groups_indicatrice_ft_, groups_indicatrice_ns_, indicatrice_ft_, indicatrice_ns_, indicatrice_surfacique_face_ft_, indicatrice_surfacique_face_ns_, nb_compo_traversante_, normal_of_interf_, normal_of_interf_ns_, normale_par_compo_, old(), old_en_premier_, surface_interface_ft_, surface_interface_ns_, surface_par_compo_, surface_vapeur_par_face_, surface_vapeur_par_face_ns_, and Champs_compris_IJK::switch_ft_fields().
Referenced by Probleme_FTD_IJK_base::update_indicator_field().
calculer_indicatrice_next()
void IJK_Interfaces::calculer_indicatrice_next (const DoubleTab & gravite, const double delta_rho, const double sigma, const double time, const int itstep, const bool parcourir = true)
References bary_of_interf_, bary_of_interf_ns_, bary_par_compo_, barycentre_phase1_face_ft_, barycentre_phase1_face_ns_, barycentre_phase1_ft_, barycentre_phase1_ns_, barycentre_vapeur_par_face_, barycentre_vapeur_par_face_ns_, Statistiques::begin_count(), calculer_barycentre(), calculer_indicatrice(), calculer_indicatrice_optim(), calculer_indicatrice_surfacique_barycentre_face(), calculer_indicatrices(), calculer_indicatrices_optim(), calculer_phi_repuls_par_compo(), calculer_surface_interface(), ComputeValParCompoInCell::calculer_valeur_par_compo(), compos_traversantes_, SurfaceVapeurIJKComputation::compute_surf_and_barys(), courbure_par_compo_, Option_IJK::DISABLE_DIPHASIQUE, FixedVector< T, N >::echange_espace_virtuel(), Statistiques::end_count(), get_nb_bulles_reelles(), get_recompute_indicator(), Navier_Stokes_FTD_IJK::get_redistribute_from_splitting_ft_faces(), groups_indicatrice_ft_, groups_indicatrice_ns_, indicatrice_ft_, indicatrice_ns_, indicatrice_par_compo_, indicatrice_surfacique_face_ft_, indicatrice_surfacique_face_ns_, maillage_ft_ijk_, mean_over_compo(), n_faces_mouilles_, nb_compo_traversante_, nb_groups(), Statistiques::new_counter(), next(), normal_of_interf_, normal_of_interf_ns_, normale_par_compo_, parcourir_maillage(), phi_par_compo_, Navier_Stokes_FTD_IJK::redistrib_from_ft_elem(), Redistribute_Field::redistribute(), ref_ijk_ft_, repuls_par_compo_, source_interf_par_compo_, surf_par_compo_, surface_interface_ft_, surface_interface_ns_, surface_par_compo_, surface_vapeur_par_face_, surface_vapeur_par_face_computation_, surface_vapeur_par_face_ns_, val_par_compo_in_cell_computation_, and verif_indic().
Referenced by Probleme_FTD_IJK_base::sauver(), and Probleme_FTD_IJK_base::update_indicator_field().
calculer_indicatrice_intermediaire()
void IJK_Interfaces::calculer_indicatrice_intermediaire (IJK_Field_double & indicatrice_intermediaire_ft_, IJK_Field_double & indicatrice_intermediaire_ns_, IJK_Field_vector3_double & indicatrice_surfacique_intermediaire_face_ft_, IJK_Field_vector3_double & indicatrice_surfacique_intermediaire_face_ns_, const bool parcourir = true)
References Statistiques::begin_count(), calculer_indicatrice(), calculer_indicatrice_optim(), calculer_indicatrice_surfacique_face(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::data(), Option_IJK::DISABLE_DIPHASIQUE, IJK_Field_vector< T, N >::echange_espace_virtuel(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel(), Statistiques::end_count(), get_nb_bulles_reelles(), get_recompute_indicator(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost(), Statistiques::new_counter(), next(), normal_of_interf_, parcourir_maillage(), and ref_ijk_ft_.
Referenced by calculer_indicatrice_apres_remaillage(), and calculer_indicatrice_avant_remaillage().
calculer_indicatrice_avant_remaillage()
void IJK_Interfaces::calculer_indicatrice_avant_remaillage (const bool parcourir = true) inline
References calculer_indicatrice_intermediaire(), indicatrice_avant_remaillage_ft_, indicatrice_avant_remaillage_ns_, indicatrice_surfacique_avant_remaillage_face_ft_, and indicatrice_surfacique_avant_remaillage_face_ns_.
Referenced by Probleme_FTD_IJK_base::update_pre_remeshing_indicator_field().
calculer_indicatrice_apres_remaillage()
void IJK_Interfaces::calculer_indicatrice_apres_remaillage (const bool parcourir = true) inline
References calculer_indicatrice_intermediaire(), indicatrice_apres_remaillage_ft_, indicatrice_apres_remaillage_ns_, indicatrice_surfacique_apres_remaillage_face_ft_, and indicatrice_surfacique_apres_remaillage_face_ns_.
Referenced by Probleme_FTD_IJK_base::update_post_remeshing_indicator_field().
set_compute_surfaces_mouillees()
void IJK_Interfaces::set_compute_surfaces_mouillees () inline
References SurfaceVapeurIJKComputation::set_compute_surfaces_mouillees(), and surface_vapeur_par_face_computation_.
nb_compo_traversantes()
const int & IJK_Interfaces::nb_compo_traversantes (const int i, const int j, const int k) const inline
References nb_compo_traversante_, and next().
get_intersection_ijk_cell()
const Intersection_Interface_ijk_cell & IJK_Interfaces::get_intersection_ijk_cell () const inline
References intersection_ijk_cell_.
get_intersection_ijk_face()
const Intersection_Interface_ijk_face & IJK_Interfaces::get_intersection_ijk_face () const inline
References intersection_ijk_face_.
get_set_intersection_ijk_cell()
Intersection_Interface_ijk_cell & IJK_Interfaces::get_set_intersection_ijk_cell () inline
References intersection_ijk_cell_.
get_set_intersection_ijk_face()
Intersection_Interface_ijk_face & IJK_Interfaces::get_set_intersection_ijk_face () inline
References intersection_ijk_face_.
get_ijk_compo_connex()
const IJK_Composantes_Connex & IJK_Interfaces::get_ijk_compo_connex () const inline
References ijk_compo_connex_.
Referenced by IJK_Thermal_base::force_upstream_temperature().
compute_compo_connex_from_bounding_box()
void IJK_Interfaces::compute_compo_connex_from_bounding_box () inline
References IJK_Composantes_Connex::compute_bounding_box_fill_compo_connex(), Option_IJK::DISABLE_DIPHASIQUE, and ijk_compo_connex_.
Referenced by update_indicatrice_variables_monofluides().
compute_compo_connex_from_interface()
void IJK_Interfaces::compute_compo_connex_from_interface () inline
References IJK_Composantes_Connex::compute_compo_connex_from_interface(), Option_IJK::DISABLE_DIPHASIQUE, and ijk_compo_connex_.
Referenced by update_indicatrice_variables_monofluides().
initialise_ijk_compo_connex_bubbles_params()
void IJK_Interfaces::initialise_ijk_compo_connex_bubbles_params () inline
References Option_IJK::DISABLE_DIPHASIQUE, ijk_compo_connex_, and IJK_Composantes_Connex::initialise_bubbles_params().
Referenced by Probleme_FTD_IJK_base::initialise_ijk_fields().
allocate_ijk_compo_connex_fields()
void IJK_Interfaces::allocate_ijk_compo_connex_fields (const Domaine_IJK & splitting, const int & allocate_compo_fields) inline
References IJK_Composantes_Connex::allocate_fields(), Option_IJK::DISABLE_DIPHASIQUE, and ijk_compo_connex_.
Referenced by Probleme_FTD_IJK_base::initialise_ijk_fields().
associate_rising_velocities_parameters()
void IJK_Interfaces::associate_rising_velocities_parameters (const Domaine_IJK & splitting, const int & compute_rising_velocities, const int & fill_rising_velocities, const int & use_bubbles_velocities_from_interface, const int & use_bubbles_velocities_from_barycentres) inline
References IJK_Composantes_Connex::associate_rising_velocities_parameters(), IJK_Composantes_Connex::compute_rising_velocities(), Option_IJK::DISABLE_DIPHASIQUE, and ijk_compo_connex_.
Referenced by Probleme_FTD_IJK_base::initialise_ijk_fields().
compute_rising_velocities_from_compo()
void IJK_Interfaces::compute_rising_velocities_from_compo () inline
References IJK_Composantes_Connex::compute_rising_velocities(), Option_IJK::DISABLE_DIPHASIQUE, and ijk_compo_connex_.
Referenced by update_indicatrice_variables_monofluides().
get_bubble_barycentres_old_new()
const DoubleTab & IJK_Interfaces::get_bubble_barycentres_old_new (const int & get_new) const inline
References bubbles_bary_new_, and bubbles_bary_old_.
get_bubble_velocities_from_interface()
const DoubleTab & IJK_Interfaces::get_bubble_velocities_from_interface () const inline
References bubbles_velocities_.
Referenced by IJK_Composantes_Connex::compute_rising_velocities().
get_bubble_velocities_from_barycentres()
const DoubleTab & IJK_Interfaces::get_bubble_velocities_from_barycentres () const inline
References bubbles_velocities_bary_.
Referenced by IJK_Composantes_Connex::compute_rising_velocities().
get_bubble_rising_vectors_from_barycentres()
const DoubleTab & IJK_Interfaces::get_bubble_rising_vectors_from_barycentres () const inline
References bubbles_rising_vectors_bary_.
get_bubbles_velocities_magnitude_from_barycentres()
const ArrOfDouble & IJK_Interfaces::get_bubbles_velocities_magnitude_from_barycentres () const inline
References bubbles_velocities_bary_.
reset_flags_and_counters()
void IJK_Interfaces::reset_flags_and_counters ()
References has_computed_bubble_barycentres_.
Referenced by update_indicatrice_variables_monofluides().
verif_indic()
void IJK_Interfaces::verif_indic () protected
Referenced by calculer_indicatrice_next().
calculer_phi_repuls_sommet()
void IJK_Interfaces::calculer_phi_repuls_sommet (ArrOfDouble & potentiels_sommets, ArrOfDouble & repulsions_sommets, const DoubleTab & gravite, const double delta_rho, const double sigma, const double time, const int itstep) protected
References active_repulsion_paroi_, bounding_box_NS_domain_, Maillage_FT_IJK::calculer_compo_connexe_sommets(), calculer_distance_autres_compo_connexe2(), Process::check_int_overflow(), Sortie_Fichier_base::close(), compute_distance_autres_interfaces_, delta_p_max_repulsion_, delta_p_wall_max_repulsion_, distance_autres_interfaces_, Domaine_IJK::get_constant_delta(), FT_Field::get_disable_surfactant(), Domaine_IJK::get_node_coordinates(), Domaine_IJK::get_periodic_flag(), FT_Field::get_sigma_sommets(), Maillage_FT_Disc::get_update_courbure_sommets(), GRAVITE_GRAD_I, Process::je_suis_maitre(), maillage_ft_ijk_, Process::me(), Maillage_FT_IJK::minimum_longueur_arrete(), Process::mp_min(), Process::mp_sum(), Process::nproc(), portee_force_repulsion_, portee_wall_repulsion_, ref_domaine_, ref_ijk_ft_, reprise_, TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), Maillage_FT_Disc::sommets(), Maillage_FT_IJK::Surfactant_facettes(), terme_gravite_, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by calculer_phi_repuls_par_compo().
calculer_phi_repuls_par_compo()
void IJK_Interfaces::calculer_phi_repuls_par_compo (FixedVector< IJK_Field_double, max_authorized_nb_of_components_ > & surf_par_compo, FixedVector< FixedVector< IJK_Field_double, max_authorized_nb_of_components_ >, 3 > & source_interf_par_compo, FixedVector< IJK_Field_double, max_authorized_nb_of_components_ > & phi_par_compo, FixedVector< IJK_Field_double, max_authorized_nb_of_components_ > & repuls_par_compo, const DoubleTab & gravite, const double delta_rho, const double sigma, const double time, const int itstep) protected
References ComputeValParCompoInCell::calculer_moy_field_sommet_par_compo(), calculer_phi_repuls_sommet(), ComputeValParCompoInCell::calculer_somme_field_sommet_par_compo(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::data(), field_repulsion_, FT_Field::get_disable_surfactant(), Domaine_IJK::get_nb_elem_local(), maillage_ft_ijk_, Maillage_FT_Disc::nb_sommets(), ref_domaine_, TRUSTArray< _TYPE_, _SIZE_ >::resize(), Maillage_FT_IJK::Surfactant_facettes(), Maillage_FT_IJK::update_sigma_and_interfacial_source_term_sommet(), use_tryggvason_interfacial_source_, and val_par_compo_in_cell_computation_.
Referenced by calculer_indicatrice_next().
calculer_indicatrice()
void IJK_Interfaces::calculer_indicatrice (IJK_Field_double & indic) protected
References Statistiques::begin_count(), compute_drapeaux_vapeur_v2(), compute_drapeaux_vapeur_v3(), compute_drapeaux_vapeur_v4(), Intersections_Elem_Facettes_Data::contrib_volume_phase1_, Domaine_IJK::convert_ijk_cell_to_packed(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::data(), Intersections_Elem_Facettes::data_intersection(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_VF::elem_faces(), Statistiques::end_count(), Domaine_VF::face_voisins(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_domaine(), Intersections_Elem_Facettes::index_elem(), Intersections_Elem_Facettes_Data::index_facette_suivante_, Maillage_FT_Disc::intersections_elem_facettes(), maillage_ft_ijk_, nb_bulles_ghost_, nb_bulles_reelles_, nb_compo_in_num_compo_, Statistiques::new_counter(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), num_compo_, ref_domaine_, refdomaine_dis_, seuil_indicatrice_negligeable_, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by calculer_indicatrice_intermediaire(), and calculer_indicatrice_next().
calculer_indicatrice_optim()
void IJK_Interfaces::calculer_indicatrice_optim (IJK_Field_double & indic) protected
References Statistiques::begin_count(), Intersections_Elem_Facettes_Data::contrib_volume_phase1_, Domaine_IJK::convert_ijk_cell_to_packed(), Intersections_Elem_Facettes::data_intersection(), Statistiques::end_count(), Process::exit(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_domaine(), Intersections_Elem_Facettes::index_elem(), Intersections_Elem_Facettes_Data::index_facette_suivante_, Maillage_FT_Disc::intersections_elem_facettes(), maillage_ft_ijk_, Statistiques::new_counter(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), and update_indicatrice().
Referenced by calculer_indicatrice_intermediaire(), and calculer_indicatrice_next().
calculer_indicatrices()
void IJK_Interfaces::calculer_indicatrices (IJK_Field_vector3_double & indic) protected
References Statistiques::begin_count(), Maillage_FT_IJK::compo_connexe_facettes(), compo_to_group_, compute_drapeaux_vapeur_v4(), Intersections_Elem_Facettes_Data::contrib_volume_phase1_, Domaine_IJK::convert_ijk_cell_to_packed(), Intersections_Elem_Facettes::data_intersection(), Domaine_dis_base::domaine(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_VF::elem_faces(), Statistiques::end_count(), Process::exit(), Domaine_VF::face_voisins(), IJK_Field_vector< T, N >::get_domaine(), Intersections_Elem_Facettes::index_elem(), Intersections_Elem_Facettes_Data::index_facette_suivante_, Maillage_FT_Disc::intersections_elem_facettes(), maillage_ft_ijk_, nb_bulles_reelles_, nb_compo_in_num_compo_, nb_groups_, Statistiques::new_counter(), Intersections_Elem_Facettes_Data::numero_facette_, parser_, refdomaine_dis_, TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by calculer_indicatrice_next().
calculer_indicatrices_optim()
void IJK_Interfaces::calculer_indicatrices_optim (IJK_Field_vector3_double & indic) protected
References Statistiques::begin_count(), Maillage_FT_IJK::compo_connexe_facettes(), compo_to_group_, Intersections_Elem_Facettes_Data::contrib_volume_phase1_, Domaine_IJK::convert_ijk_cell_to_packed(), Intersections_Elem_Facettes::data_intersection(), Statistiques::end_count(), IJK_Field_vector< T, N >::get_domaine(), Intersections_Elem_Facettes::index_elem(), Intersections_Elem_Facettes_Data::index_facette_suivante_, Maillage_FT_Disc::intersections_elem_facettes(), maillage_ft_ijk_, nb_bulles_reelles_, nb_groups_, Statistiques::new_counter(), Intersections_Elem_Facettes_Data::numero_facette_, and update_indicatrice().
Referenced by calculer_indicatrice_next().
update_indicatrice()
int IJK_Interfaces::update_indicatrice (IJK_Field_double & indic) protected
References IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_domaine(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_localisation(), Domaine_IJK::get_nb_items_global(), Domaine_IJK::get_offset_local(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), and IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk().
Referenced by calculer_indicatrice_optim(), and calculer_indicatrices_optim().
calculer_surface_interface()
void IJK_Interfaces::calculer_surface_interface (IJK_Field_double & surf_interface, IJK_Field_double & indic) protected
References Statistiques::begin_count(), Domaine_IJK::convert_ijk_cell_to_packed(), Intersections_Elem_Facettes::data_intersection(), Statistiques::end_count(), est_pure(), Intersections_Elem_Facettes_Data::fraction_surface_intersection_, IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_domaine(), Maillage_FT_Disc::get_update_surface_facettes(), Intersections_Elem_Facettes::index_elem(), Intersections_Elem_Facettes_Data::index_facette_suivante_, Maillage_FT_Disc::intersections_elem_facettes(), maillage_ft_ijk_, Statistiques::new_counter(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), and Intersections_Elem_Facettes_Data::numero_facette_.
Referenced by calculer_indicatrice_next().
calculer_barycentre()
void IJK_Interfaces::calculer_barycentre (IJK_Field_vector3_double & baric, IJK_Field_double & indic) protected
References Statistiques::begin_count(), Intersections_Elem_Facettes_Data::contrib_barycentre_phase1_, Intersections_Elem_Facettes_Data::contrib_volume_phase1_, Domaine_IJK::convert_ijk_cell_to_packed(), Intersections_Elem_Facettes::data_intersection(), Statistiques::end_count(), est_pure(), IJK_Field_vector< T, N >::get_domaine(), Intersections_Elem_Facettes::index_elem(), Intersections_Elem_Facettes_Data::index_facette_suivante_, Maillage_FT_Disc::intersections_elem_facettes(), maillage_ft_ijk_, and Statistiques::new_counter().
Referenced by calculer_indicatrice_next().
calculer_indicatrice_surfacique_face()
void IJK_Interfaces::calculer_indicatrice_surfacique_face (IJK_Field_vector3_double & indic_surfacique_face, IJK_Field_double & indic, IJK_Field_vector3_double & norme) protected
References Statistiques::begin_count(), Intersections_Elem_Facettes_Data::contrib_aire_faces_phase1_, Domaine_IJK::convert_ijk_cell_to_packed(), Intersections_Elem_Facettes::data_intersection(), Statistiques::end_count(), est_pure(), IJK_Field_vector< T, N >::get_domaine(), Intersections_Elem_Facettes::index_elem(), Intersections_Elem_Facettes_Data::index_facette_suivante_, Maillage_FT_Disc::intersections_elem_facettes(), maillage_ft_ijk_, and Statistiques::new_counter().
Referenced by calculer_indicatrice_intermediaire().
calculer_indicatrice_surfacique_barycentre_face()
void IJK_Interfaces::calculer_indicatrice_surfacique_barycentre_face (IJK_Field_vector3_double & indic_surfacique_face, FixedVector< FixedVector< IJK_Field_double, 2 >, 3 > & baric_face, IJK_Field_double & indic, IJK_Field_vector3_double & norme) protected
References Statistiques::begin_count(), Intersections_Elem_Facettes_Data::contrib_aire_faces_phase1_, Intersections_Elem_Facettes_Data::contrib_barycentre_faces_phase1_, Domaine_IJK::convert_ijk_cell_to_packed(), Intersections_Elem_Facettes::data_intersection(), Statistiques::end_count(), est_pure(), IJK_Field_vector< T, N >::get_domaine(), Intersections_Elem_Facettes::index_elem(), Intersections_Elem_Facettes_Data::index_facette_suivante_, Maillage_FT_Disc::intersections_elem_facettes(), maillage_ft_ijk_, and Statistiques::new_counter().
Referenced by calculer_indicatrice_next().
calculer_vmoy_translation_composantes_connexes()
void IJK_Interfaces::calculer_vmoy_translation_composantes_connexes (const Maillage_FT_IJK & maillage, const ArrOfDouble & surface_facette, const ArrOfDouble & surface_par_bulle, const ArrOfInt & compo_connexes_facettes, const int nbulles_reelles, const int nbulles_ghost, const DoubleTab & vitesse_sommets, DoubleTab & vitesses_translation_sommets) const protected
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), disable_rigid_translation_, Maillage_FT_Disc::facette_virtuelle(), Maillage_FT_Disc::facettes(), get_ghost_number_from_compo(), Maillage_FT_Disc::nb_facettes(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by calculer_vecteurs_de_deplacement_rigide(), and compute_external_forces_().
calculer_vmoy_rotation_composantes_connexes()
void IJK_Interfaces::calculer_vmoy_rotation_composantes_connexes (const Maillage_FT_IJK & maillage, const ArrOfDouble & surface_facette, const ArrOfDouble & surface_par_bulle, const ArrOfInt & compo_connexes_facettes, const int nbulles_reelles, const int nbulles_ghost, const DoubleTab & centre_gravite, const DoubleTab & vitesse_sommets, const DoubleTab & vitesse_translation_sommets, DoubleTab & mean_bubble_rotation_vector) const protected
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), disable_rigid_rotation_, Maillage_FT_Disc::facette_virtuelle(), Maillage_FT_Disc::facettes(), get_ghost_number_from_compo(), Maillage_FT_Disc::nb_facettes(), Vecteur3::produit_scalaire(), Vecteur3::produit_vectoriel(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and Maillage_FT_Disc::sommets().
Referenced by calculer_vecteurs_de_deplacement_rigide().
recursive_calcul_distance_chez_voisin()
void IJK_Interfaces::recursive_calcul_distance_chez_voisin (DoubleTab & vinterp_tmp, int dir, const Maillage_FT_IJK & mesh, DoubleTab & coord_sommets, ArrOfInt & compo_sommet, ArrOfDouble & distance, DoubleTab & v_closer, double distmax) protected
References TRUSTArray< _TYPE_, _SIZE_ >::append_array(), TRUSTTab< _TYPE_, _SIZE_ >::append_line(), Schema_Comm::begin_comm(), calculer_distance_autres_compo_connexe_ijk(), calculer_distance_autres_compo_connexe_octree(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Schema_Comm::echange_taille_et_messages(), Schema_Comm::end_comm(), Entree::eof(), Domaine_IJK::get_nb_elem_local(), Domaine_IJK::get_neighbour_processor(), Domaine_IJK::get_node_coordinates(), Domaine_IJK::get_offset_local(), no_octree_method_, Process::nproc(), recursive_calcul_distance_chez_voisin(), Schema_Comm::recv_buffer(), ref_domaine_, TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), Schema_Comm::send_buffer(), Schema_Comm::set_send_recv_pe_list(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by calculer_distance_autres_compo_connexe2(), and recursive_calcul_distance_chez_voisin().
calculer_distance_autres_compo_connexe2()
void IJK_Interfaces::calculer_distance_autres_compo_connexe2 (ArrOfDouble & distance, DoubleTab & v_closer) protected
References Maillage_FT_IJK::calculer_compo_connexe_sommets(), compute_vinterp(), maillage_ft_ijk_, portee_force_repulsion_, recursive_calcul_distance_chez_voisin(), Maillage_FT_Disc::sommets(), and vinterp_.
Referenced by calculer_phi_repuls_sommet(), get_IJK_field(), and initialize().
calculer_distance_autres_compo_connexe_octree()
void IJK_Interfaces::calculer_distance_autres_compo_connexe_octree (const DoubleTab & sommets_a_tester, const ArrOfInt & compo_connexe_sommets, const DoubleTab & vinterp_tmp, const Maillage_FT_IJK & mesh, ArrOfDouble & distance, DoubleTab & v_closer, const double distmax) protected
References Octree_Double_32_64< _SIZE_ >::build_elements(), Maillage_FT_IJK::compo_connexe_facettes(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Maillage_FT_Disc::facettes(), and Maillage_FT_Disc::sommets().
Referenced by recursive_calcul_distance_chez_voisin().
calculer_distance_autres_compo_connexe_ijk()
void IJK_Interfaces::calculer_distance_autres_compo_connexe_ijk (const DoubleTab & sommets_a_tester, const ArrOfInt & compo_connexe_sommets, const DoubleTab & vinterp_tmp, const Maillage_FT_IJK & mesh, ArrOfDouble & distance, DoubleTab & v_closer, const double distmax) protected
References Maillage_FT_IJK::compo_connexe_facettes(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Maillage_FT_Disc::facettes(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_domaine(), Domaine_IJK::get_nb_elem_local(), and I_ft().
Referenced by recursive_calcul_distance_chez_voisin().
Friends And Related Function Documentation
IJK_Composantes_Connex
friend class IJK_Composantes_Connex friend
Member Data Documentation
info_obj
const Type_info IJK_Interfaces::info_obj static
surface_vapeur_par_face_computation_
SurfaceVapeurIJKComputation IJK_Interfaces::surface_vapeur_par_face_computation_ protected
Referenced by calculer_indicatrice_next(), initialize(), and set_compute_surfaces_mouillees().
val_par_compo_in_cell_computation_
ComputeValParCompoInCell IJK_Interfaces::val_par_compo_in_cell_computation_ protected
Referenced by calculer_indicatrice_next(), calculer_phi_repuls_par_compo(), and initialize().
ref_domaine_
TRUST_Ref< Domaine_IJK *> IJK_Interfaces::ref_domaine_ protected
Referenced by ajouter_terme_source_interfaces(), calculer_indicatrice(), calculer_phi_repuls_par_compo(), calculer_phi_repuls_sommet(), calculer_var_volume_remaillage(), compute_cell_phase_with_interface_normal(), compute_drapeaux_vapeur_v4(), dupliquer_bulle_perio(), initialize(), parcourir_maillage(), recursive_calcul_distance_chez_voisin(), supprimer_certaines_bulles_reelles(), and transporter_maillage_remaillage().
refdomaine_dis_
TRUST_Ref< Domaine_dis_base *> IJK_Interfaces::refdomaine_dis_ protected
Referenced by calculer_indicatrice(), calculer_indicatrices(), calculer_var_volume_remaillage(), compute_drapeaux_vapeur_v4(), convert_to_IntVect(), dupliquer_bulle_perio(), get_domaine_dis(), and initialize().
ref_ijk_ft_
TRUST_Ref< Probleme_FTD_IJK_base *> IJK_Interfaces::ref_ijk_ft_ protected
Referenced by activate_cut_cell(), associer_pb_base(), calculer_indicatrice_intermediaire(), calculer_indicatrice_next(), calculer_phi_repuls_sommet(), calculer_var_volume_remaillage(), calculer_vecteurs_de_deplacement_rigide(), compute_bubbles_volume_and_barycentres(), compute_vinterp(), and initialize().
ref_ijk_ft_switch_
TRUST_Ref< Switch_FT_double *> IJK_Interfaces::ref_ijk_ft_switch_ protected
Referenced by associer_switch().
num_compo_
IntVect IJK_Interfaces::num_compo_ protected
Referenced by calculer_indicatrice(), compute_external_forces_color_function(), get_num_compo(), and initialize().
nb_compo_in_num_compo_
int IJK_Interfaces::nb_compo_in_num_compo_ = 0 protected
Referenced by calculer_indicatrice(), calculer_indicatrices(), compute_external_forces_color_function(), and initialize().
mean_force_
DoubleTab IJK_Interfaces::mean_force_ protected
Referenced by compute_external_forces_(), IJK_Interfaces(), initialize(), printOn(), and readOn().
force_time_n_
DoubleTab IJK_Interfaces::force_time_n_ protected
Referenced by compute_external_forces_(), and initialize().
positions_reference_
DoubleTab IJK_Interfaces::positions_reference_ protected
Referenced by compute_external_forces_(), compute_indicatrice_non_perturbe(), IJK_Interfaces(), printOn(), readOn(), set_positions_reference(), and supprimer_certaines_bulles_reelles().
flag_positions_reference_
int IJK_Interfaces::flag_positions_reference_ = 0 protected
Referenced by get_flag_positions_reference(), printOn(), readOn(), and set_positions_reference().
fichier_reprise_interface_
Nom IJK_Interfaces::fichier_reprise_interface_ protected
Referenced by get_fichier_reprise(), initialize(), lire_maillage_ft_dans_lata(), readOn(), set_fichier_reprise(), and set_fichier_reprise_interface().
timestep_reprise_interface_
int IJK_Interfaces::timestep_reprise_interface_ = 1 protected
Referenced by initialize(), lire_maillage_ft_dans_lata(), and readOn().
lata_interfaces_meshname_
Nom IJK_Interfaces::lata_interfaces_meshname_ = "INTERFACES" protected
Referenced by initialize(), lire_maillage_ft_dans_lata(), and readOn().
fichier_sauvegarde_interface_
Nom IJK_Interfaces::fichier_sauvegarde_interface_ protected
Referenced by printOn(), sauvegarder_interfaces(), and set_fichier_sauvegarde().
timestep_sauvegarde_interface_
int IJK_Interfaces::timestep_sauvegarde_interface_ = 1 protected
Referenced by printOn(), and sauvegarder_interfaces().
follow_colors_
int IJK_Interfaces::follow_colors_ = 0 protected
Referenced by follow_colors(), initialize(), posttraiter_champs_instantanes(), posttraiter_tous_champs(), printOn(), readOn(), and transferer_bulle_perio().
active_repulsion_paroi_
int IJK_Interfaces::active_repulsion_paroi_ = 0 protected
Referenced by calculer_phi_repuls_sommet(), printOn(), and readOn().
use_tryggvason_interfacial_source_
int IJK_Interfaces::use_tryggvason_interfacial_source_ = 0 protected
Referenced by ajouter_terme_source_interfaces(), calculer_phi_repuls_par_compo(), initialize(), parcourir_maillage(), readOn(), and transporter_maillage_remaillage().
correction_gradient_potentiel_
int IJK_Interfaces::correction_gradient_potentiel_ = 0 protected
Referenced by ajouter_terme_source_interfaces(), printOn(), and readOn().
compute_distance_autres_interfaces_
int IJK_Interfaces::compute_distance_autres_interfaces_ = 0 protected
Referenced by calculer_phi_repuls_sommet(), initialize(), and readOn().
nb_bulles_reelles_
int IJK_Interfaces::nb_bulles_reelles_ = 0 protected
Referenced by calculer_indicatrice(), calculer_indicatrices(), calculer_indicatrices_optim(), compute_external_forces_(), compute_external_forces_color_function(), compute_external_forces_parser(), compute_indicatrice_non_perturbe(), detecter_et_supprimer_rejeton(), get_nb_bulles_reelles(), initialize(), and supprimer_certaines_bulles_reelles().
nb_bulles_ghost_
int IJK_Interfaces::nb_bulles_ghost_ = 0 protected
Referenced by calculer_indicatrice(), compute_external_forces_color_function(), compute_external_forces_parser(), compute_indicatrice_non_perturbe(), dupliquer_bulle_perio(), get_nb_bulles_ghost(), and supprimer_duplicata_bulles().
nb_bulles_ghost_before_
int IJK_Interfaces::nb_bulles_ghost_before_ = 0 protected
Referenced by dupliquer_bulle_perio(), and supprimer_duplicata_bulles().
recompute_indicator_
int IJK_Interfaces::recompute_indicator_ = 1 protected
Referenced by deplacer_bulle_perio(), dupliquer_bulle_perio(), get_recompute_indicator(), initialize(), set_recompute_indicator(), and supprimer_certaines_bulles_reelles().
parser_
int IJK_Interfaces::parser_ = 0 protected
Referenced by calculer_indicatrices(), compute_external_forces_(), get_forcing_method(), and initialize().
maillage_ft_ijk_
Maillage_FT_IJK IJK_Interfaces::maillage_ft_ijk_ protected
Referenced by ajouter_terme_source_interfaces(), calculer_aire_interfaciale(), calculer_aire_interfaciale_for_compo(), calculer_aspect_ratio(), calculer_barycentre(), calculer_bounding_box_bulles(), calculer_color(), calculer_distance_autres_compo_connexe2(), calculer_indicatrice(), calculer_indicatrice_next(), calculer_indicatrice_optim(), calculer_indicatrice_surfacique_barycentre_face(), calculer_indicatrice_surfacique_face(), calculer_indicatrices(), calculer_indicatrices_optim(), calculer_kappa_ft(), calculer_normales_et_aires_interfaciales(), calculer_phi_repuls_par_compo(), calculer_phi_repuls_sommet(), calculer_poussee_bulles(), calculer_surface_bulles(), calculer_surface_interface(), calculer_surfactant(), calculer_var_volume_remaillage(), calculer_vecteurs_de_deplacement_rigide(), calculer_volume_bulles(), compute_cell_phase_with_interface_normal(), compute_drapeaux_vapeur_v4(), compute_external_forces_(), compute_surface_average_per_bubble(), compute_vinterp(), deplacer_bulle_perio(), detecter_et_supprimer_rejeton(), dumplata_ft_mesh(), dupliquer_bulle_perio(), get_IJK_field(), initialize(), lire_maillage_ft_dans_lata(), maillage_ft_ijk(), parcourir_maillage(), posttraiter_champs_instantanes(), readOn(), remailler_interface(), RK3_G_store_vi_echange_esp_vect(), sauvegarder_interfaces(), supprimer_certaines_bulles_reelles(), supprimer_duplicata_bulles(), transporter_maillage_deformation(), transporter_maillage_remaillage(), transporter_maillage_rigide(), update_old_intersections(), and update_surface_normale().
old_maillage_ft_ijk_
Maillage_FT_IJK IJK_Interfaces::old_maillage_ft_ijk_ protected
Referenced by initialize(), old_maillage_ft_ijk(), and update_old_intersections().
RK3_G_store_vi_
DoubleTab IJK_Interfaces::RK3_G_store_vi_ protected
Referenced by initialize(), posttraiter_champs_instantanes(), posttraiter_tous_champs(), RK3_G_store_vi(), RK3_G_store_vi_echange_esp_vect(), RK3_G_store_vi_resize(), supprimer_duplicata_bulles(), transporter_maillage_deformation(), and transporter_maillage_remaillage().
vinterp_
DoubleTab IJK_Interfaces::vinterp_ protected
Referenced by calculer_distance_autres_compo_connexe2(), calculer_vecteurs_de_deplacement_rigide(), compute_external_forces_(), compute_vinterp(), posttraiter_champs_instantanes(), and transporter_maillage_deformation().
disable_rigid_translation_
int IJK_Interfaces::disable_rigid_translation_ = 0 protected
Referenced by calculer_vmoy_translation_composantes_connexes().
disable_rigid_rotation_
int IJK_Interfaces::disable_rigid_rotation_ = 1 protected
Referenced by calculer_vmoy_rotation_composantes_connexes().
var_volume_deformation_
ArrOfDouble IJK_Interfaces::var_volume_deformation_ protected
Referenced by transporter_maillage_deformation(), and transporter_maillage_remaillage().
var_volume_remaillage_
ArrOfDouble IJK_Interfaces::var_volume_remaillage_ protected
Referenced by transporter_maillage_remaillage().
var_volume_correction_globale_
ArrOfDouble IJK_Interfaces::var_volume_correction_globale_ protected
Referenced by transporter_maillage_remaillage().
deformation_velocity_
IJK_Field_vector3_double IJK_Interfaces::deformation_velocity_ protected
Referenced by calculer_var_volume_remaillage(), calculer_vitesse_de_deformation(), and initialize().
parcours_
Parcours_interface IJK_Interfaces::parcours_ protected
Referenced by activate_cut_cell(), dupliquer_bulle_perio(), initialize(), lire_motcle_non_standard(), printOn(), and readOn().
connectivite_frontieres_
Connectivite_frontieres IJK_Interfaces::connectivite_frontieres_ protected
Referenced by initialize().
remaillage_ft_ijk_
Remaillage_FT_IJK IJK_Interfaces::remaillage_ft_ijk_ protected
Referenced by initialize(), printOn(), readOn(), remaillage_ft_ijk(), transporter_maillage_deformation(), and transporter_maillage_remaillage().
bounding_box_NS_domain_
DoubleTab IJK_Interfaces::bounding_box_NS_domain_ protected
Referenced by calculer_phi_repuls_sommet(), deplacer_bulle_perio(), dupliquer_bulle_perio(), initialize(), and supprimer_certaines_bulles_reelles().
perio_NS_
bool IJK_Interfaces::perio_NS_[3] protected
Referenced by initialize(), preparer_duplicata_bulles(), preparer_duplicata_bulles_masque_6bit(), supprimer_certaines_bulles_reelles(), and transferer_bulle_perio().
avoid_duplicata_
int IJK_Interfaces::avoid_duplicata_ = 0 protected
Referenced by initialize(), and readOn().
factor_length_duplicata_
double IJK_Interfaces::factor_length_duplicata_ = 1. protected
Referenced by initialize(), and readOn().
ncells_forbidden_
int IJK_Interfaces::ncells_forbidden_ = 3 protected
Referenced by initialize(), and readOn().
ncells_deleted_
int IJK_Interfaces::ncells_deleted_ = -1 protected
Referenced by readOn(), sauvegarder_interfaces(), and supprimer_certaines_bulles_reelles().
frozen_
int IJK_Interfaces::frozen_ = 0 protected
Referenced by freeze(), is_frozen(), printOn(), and readOn().
bounding_box_forbidden_criteria_
DoubleTab IJK_Interfaces::bounding_box_forbidden_criteria_ protected
Referenced by initialize(), and transferer_bulle_perio().
bounding_box_delete_criteria_
DoubleTab IJK_Interfaces::bounding_box_delete_criteria_ protected
Referenced by supprimer_certaines_bulles_reelles().
bounding_box_duplicate_criteria_
DoubleTab IJK_Interfaces::bounding_box_duplicate_criteria_ protected
Referenced by creer_duplicata_bulles(), and initialize().
portee_force_repulsion_
double IJK_Interfaces::portee_force_repulsion_ = 1.e-8 protected
Referenced by calculer_distance_autres_compo_connexe2(), calculer_phi_repuls_sommet(), initialize(), printOn(), and readOn().
delta_p_max_repulsion_
double IJK_Interfaces::delta_p_max_repulsion_ = 0. protected
Referenced by calculer_phi_repuls_sommet(), initialize(), printOn(), and readOn().
portee_wall_repulsion_
double IJK_Interfaces::portee_wall_repulsion_ = 1.e-8 protected
Referenced by calculer_phi_repuls_sommet(), portee_wall_repulsion(), printOn(), and readOn().
delta_p_wall_max_repulsion_
double IJK_Interfaces::delta_p_wall_max_repulsion_ = 0. protected
Referenced by calculer_phi_repuls_sommet(), delta_p_wall_max_repulsion(), printOn(), and readOn().
no_octree_method_
int IJK_Interfaces::no_octree_method_ = 0 protected
Referenced by readOn(), and recursive_calcul_distance_chez_voisin().
distance_autres_interfaces_
ArrOfDoubleFT IJK_Interfaces::distance_autres_interfaces_ protected
Referenced by calculer_phi_repuls_sommet(), get_distance_autres_interfaces(), and initialize().
through_yminus_
ArrOfInt IJK_Interfaces::through_yminus_ protected
Referenced by calculer_color(), get_colors(), initialize(), postraiter_colors(), printOn(), readOn(), supprimer_certaines_bulles_reelles(), and transferer_bulle_perio().
ghost_compo_converter_
ArrOfInt IJK_Interfaces::ghost_compo_converter_ protected
Referenced by compute_external_forces_color_function(), compute_external_forces_parser(), compute_indicatrice_non_perturbe(), dupliquer_bulle_perio(), get_ghost_number_from_compo(), ghost_compo_converter(), and supprimer_duplicata_bulles().
reprise_
int IJK_Interfaces::reprise_ = 0 protected
Referenced by calculer_phi_repuls_sommet(), compute_external_forces_(), read_bubbles_barycentres_old_new(), and set_reprise().
terme_gravite_
int IJK_Interfaces::terme_gravite_ = GRAVITE_GRAD_I protected
Referenced by calculer_phi_repuls_sommet(), is_terme_gravite_rhog(), printOn(), and readOn().
nb_groups_
int IJK_Interfaces::nb_groups_ = 1 protected
Referenced by calculer_indicatrices(), calculer_indicatrices_optim(), nb_groups(), and readOn().
compo_to_group_
ArrOfInt IJK_Interfaces::compo_to_group_ protected
Referenced by calculer_indicatrices(), calculer_indicatrices_optim(), calculer_normales_et_aires_interfaciales(), get_compo_to_group(), IJK_Interfaces(), initialize(), printOn(), readOn(), and supprimer_certaines_bulles_reelles().
compute_surf_mouillees_
bool IJK_Interfaces::compute_surf_mouillees_ = false protected
n_faces_mouilles_
FixedVector<int,2> IJK_Interfaces::n_faces_mouilles_ protected
Referenced by calculer_indicatrice_next(), and get_nb_face_mouillees().
surface_vapeur_par_face_
FixedVector<IJK_Field_vector3_double, 2> IJK_Interfaces::surface_vapeur_par_face_ protected
Referenced by calculer_indicatrice_next(), get_surface_vapeur_par_face_ft(), initialize(), and switch_indicatrice_next_old().
surface_vapeur_par_face_ns_
FixedVector<IJK_Field_vector3_double, 2> IJK_Interfaces::surface_vapeur_par_face_ns_ protected
Referenced by calculer_indicatrice_next(), get_surface_vapeur_par_face(), initialize(), Sf(), Sfm(), Sfn(), and switch_indicatrice_next_old().
normal_of_interf_
FixedVector<IJK_Field_vector3_double, 2> IJK_Interfaces::normal_of_interf_ protected
Referenced by calculer_indicatrice_intermediaire(), calculer_indicatrice_next(), initialize(), and switch_indicatrice_next_old().
normal_of_interf_ns_
FixedVector<IJK_Field_vector3_double, 2> IJK_Interfaces::normal_of_interf_ns_ protected
Referenced by calculer_indicatrice_next(), initialize(), nI(), nIn(), and switch_indicatrice_next_old().
bary_of_interf_
FixedVector<IJK_Field_vector3_double, 2> IJK_Interfaces::bary_of_interf_ protected
Referenced by calculer_indicatrice_next(), initialize(), and switch_indicatrice_next_old().
bary_of_interf_ns_
FixedVector<IJK_Field_vector3_double, 2> IJK_Interfaces::bary_of_interf_ns_ protected
Referenced by BoI(), BoIn(), calculer_indicatrice_next(), initialize(), switch_indicatrice_next_old(), xI(), and xIn().
barycentre_vapeur_par_face_
FixedVector<FixedVector<IJK_Field_vector3_double, 3>, 2> IJK_Interfaces::barycentre_vapeur_par_face_ protected
Referenced by calculer_indicatrice_next(), get_barycentre_vapeur_par_face_ft(), initialize(), and switch_indicatrice_next_old().
barycentre_vapeur_par_face_ns_
FixedVector<FixedVector<IJK_Field_vector3_double, 3>, 2> IJK_Interfaces::barycentre_vapeur_par_face_ns_ protected
Referenced by calculer_indicatrice_next(), get_barycentre_vapeur_par_face(), initialize(), and switch_indicatrice_next_old().
n_cell_diph_
int IJK_Interfaces::n_cell_diph_ = 0 protected
old_en_premier_
bool IJK_Interfaces::old_en_premier_ = true protected
Referenced by next(), old(), and switch_indicatrice_next_old().
indicatrice_ns_
FixedVector<IJK_Field_double, 2> IJK_Interfaces::indicatrice_ns_ protected
Referenced by calculer_indicatrice_next(), calculer_var_volume_remaillage(), devient_diphasique(), devient_pure(), I(), imprime_bilan_indicatrice(), In(), initialize(), phase_mourrante(), phase_naissante(), and switch_indicatrice_next_old().
indicatrice_ft_
FixedVector<IJK_Field_double, 2> IJK_Interfaces::indicatrice_ft_ protected
Referenced by calculer_indicatrice_next(), I_ft(), In_ft(), initialize(), and switch_indicatrice_next_old().
indicatrice_avant_remaillage_ns_
IJK_Field_double IJK_Interfaces::indicatrice_avant_remaillage_ns_ protected
Referenced by calculer_indicatrice_avant_remaillage(), calculer_var_volume_remaillage(), and initialize().
indicatrice_avant_remaillage_ft_
IJK_Field_double IJK_Interfaces::indicatrice_avant_remaillage_ft_ protected
Referenced by calculer_indicatrice_avant_remaillage(), and initialize().
indicatrice_apres_remaillage_ns_
IJK_Field_double IJK_Interfaces::indicatrice_apres_remaillage_ns_ protected
Referenced by calculer_indicatrice_apres_remaillage(), and initialize().
indicatrice_apres_remaillage_ft_
IJK_Field_double IJK_Interfaces::indicatrice_apres_remaillage_ft_ protected
Referenced by calculer_indicatrice_apres_remaillage(), and initialize().
delta_volume_theorique_bilan_ns_
IJK_Field_double IJK_Interfaces::delta_volume_theorique_bilan_ns_ protected
Referenced by calculer_var_volume_remaillage(), and initialize().
surface_interface_ns_
FixedVector<IJK_Field_double, 2> IJK_Interfaces::surface_interface_ns_ protected
Referenced by calculer_indicatrice_next(), get_surface_interface_next(), get_surface_interface_old(), initialize(), and switch_indicatrice_next_old().
surface_interface_ft_
FixedVector<IJK_Field_double, 2> IJK_Interfaces::surface_interface_ft_ protected
Referenced by calculer_indicatrice_next(), get_surface_interface_next_ft(), get_surface_interface_old_ft(), initialize(), and switch_indicatrice_next_old().
barycentre_phase1_ns_
FixedVector<IJK_Field_vector3_double, 2> IJK_Interfaces::barycentre_phase1_ns_ protected
Referenced by calculer_indicatrice_next(), get_barycentre(), get_barycentre_phase1_next(), get_barycentre_phase1_old(), initialize(), and switch_indicatrice_next_old().
barycentre_phase1_ft_
FixedVector<IJK_Field_vector3_double, 2> IJK_Interfaces::barycentre_phase1_ft_ protected
Referenced by calculer_indicatrice_next(), get_barycentre_phase1_next_ft(), get_barycentre_phase1_old_ft(), initialize(), and switch_indicatrice_next_old().
field_repulsion_
IJK_Field_double IJK_Interfaces::field_repulsion_ protected
Referenced by calculer_phi_repuls_par_compo(), and initialize().
indicatrice_surfacique_face_ns_
FixedVector<IJK_Field_vector3_double, 2> IJK_Interfaces::indicatrice_surfacique_face_ns_ protected
Referenced by calculer_indicatrice_next(), calculer_var_volume_remaillage(), get_indicatrice_surfacique_face_next(), get_indicatrice_surfacique_face_old(), initialize(), and switch_indicatrice_next_old().
indicatrice_surfacique_face_ft_
FixedVector<IJK_Field_vector3_double, 2> IJK_Interfaces::indicatrice_surfacique_face_ft_ protected
Referenced by calculer_indicatrice_next(), get_indicatrice_surfacique_face_ft(), initialize(), and switch_indicatrice_next_old().
indicatrice_surfacique_avant_remaillage_face_ns_
IJK_Field_vector3_double IJK_Interfaces::indicatrice_surfacique_avant_remaillage_face_ns_ protected
Referenced by calculer_indicatrice_avant_remaillage(), calculer_var_volume_remaillage(), and initialize().
indicatrice_surfacique_avant_remaillage_face_ft_
IJK_Field_vector3_double IJK_Interfaces::indicatrice_surfacique_avant_remaillage_face_ft_ protected
Referenced by calculer_indicatrice_avant_remaillage(), and initialize().
indicatrice_surfacique_apres_remaillage_face_ns_
IJK_Field_vector3_double IJK_Interfaces::indicatrice_surfacique_apres_remaillage_face_ns_ protected
Referenced by calculer_indicatrice_apres_remaillage(), and initialize().
indicatrice_surfacique_apres_remaillage_face_ft_
IJK_Field_vector3_double IJK_Interfaces::indicatrice_surfacique_apres_remaillage_face_ft_ protected
Referenced by calculer_indicatrice_apres_remaillage(), and initialize().
barycentre_phase1_face_ns_
FixedVector<FixedVector<FixedVector<IJK_Field_double, 2>, 3>, 2> IJK_Interfaces::barycentre_phase1_face_ns_ protected
Referenced by calculer_indicatrice_next(), get_barycentre_face(), get_barycentre_phase1_face(), initialize(), and switch_indicatrice_next_old().
barycentre_phase1_face_ft_
FixedVector<FixedVector<FixedVector<IJK_Field_double, 2>, 3>, 2> IJK_Interfaces::barycentre_phase1_face_ft_ protected
Referenced by calculer_indicatrice_next(), get_barycentre_phase1_face_ft(), initialize(), and switch_indicatrice_next_old().
groups_indicatrice_ft_
FixedVector<IJK_Field_vector<double, max_authorized_nb_of_groups_>, 2> IJK_Interfaces::groups_indicatrice_ft_ protected
Referenced by calculer_indicatrice_next(), groups_indicatrice_ft(), groups_indicatrice_n_ft(), initialize(), and switch_indicatrice_next_old().
groups_indicatrice_ns_
FixedVector<IJK_Field_vector<double, max_authorized_nb_of_groups_>, 2> IJK_Interfaces::groups_indicatrice_ns_ protected
Referenced by calculer_indicatrice_next(), groups_indicatrice_n_ns(), groups_indicatrice_ns(), initialize(), and switch_indicatrice_next_old().
nb_compo_traversante_
FixedVector<IJK_Field_int, 2> IJK_Interfaces::nb_compo_traversante_ protected
Referenced by calculer_indicatrice_next(), initialize(), nb_compo_traversantes(), SI(), and switch_indicatrice_next_old().
compos_traversantes_
FixedVector<FixedVector<IJK_Field_int, max_authorized_nb_of_components_>, 2> IJK_Interfaces::compos_traversantes_ protected
Referenced by ajouter_terme_source_interfaces(), calculer_indicatrice_next(), and initialize().
indicatrice_par_compo_
FixedVector<FixedVector<IJK_Field_double, max_authorized_nb_of_components_>, 2> IJK_Interfaces::indicatrice_par_compo_ protected
Referenced by ajouter_terme_source_interfaces(), calculer_indicatrice_next(), and initialize().
surface_par_compo_
FixedVector<FixedVector<IJK_Field_double, max_authorized_nb_of_components_>, 2> IJK_Interfaces::surface_par_compo_ protected
Referenced by ajouter_terme_source_interfaces(), calculer_indicatrice_next(), initialize(), SI(), and switch_indicatrice_next_old().
courbure_par_compo_
FixedVector<FixedVector<IJK_Field_double, max_authorized_nb_of_components_>, 2> IJK_Interfaces::courbure_par_compo_ protected
Referenced by calculer_indicatrice_next(), and initialize().
phi_par_compo_
FixedVector<FixedVector<IJK_Field_double, max_authorized_nb_of_components_>, 2> IJK_Interfaces::phi_par_compo_ protected
Referenced by ajouter_terme_source_interfaces(), calculer_indicatrice_next(), and initialize().
surf_par_compo_
FixedVector<FixedVector<IJK_Field_double, max_authorized_nb_of_components_>, 2> IJK_Interfaces::surf_par_compo_ protected
Referenced by ajouter_terme_source_interfaces(), calculer_indicatrice_next(), and initialize().
source_interf_par_compo_
FixedVector<FixedVector<FixedVector<IJK_Field_double, max_authorized_nb_of_components_>, 3>, 2> IJK_Interfaces::source_interf_par_compo_ protected
Referenced by ajouter_terme_source_interfaces(), calculer_indicatrice_next(), and initialize().
gradx_sigma_par_compo_
FixedVector<FixedVector<IJK_Field_double, max_authorized_nb_of_components_>, 2> IJK_Interfaces::gradx_sigma_par_compo_ protected
grady_sigma_par_compo_
FixedVector<FixedVector<IJK_Field_double, max_authorized_nb_of_components_>, 2> IJK_Interfaces::grady_sigma_par_compo_ protected
gradz_sigma_par_compo_
FixedVector<FixedVector<IJK_Field_double, max_authorized_nb_of_components_>, 2> IJK_Interfaces::gradz_sigma_par_compo_ protected
repuls_par_compo_
FixedVector<FixedVector<IJK_Field_double, max_authorized_nb_of_components_>, 2> IJK_Interfaces::repuls_par_compo_ protected
Referenced by ajouter_terme_source_interfaces(), calculer_indicatrice_next(), and initialize().
normale_par_compo_
FixedVector<FixedVector<IJK_Field_double, 3 * max_authorized_nb_of_components_>, 2> IJK_Interfaces::normale_par_compo_ protected
Referenced by ajouter_terme_source_interfaces(), calculer_indicatrice_next(), get_norm_par_compo_itfc_in_cell_ft(), initialize(), and switch_indicatrice_next_old().
bary_par_compo_
FixedVector<FixedVector<IJK_Field_double, 3 * max_authorized_nb_of_components_>, 2> IJK_Interfaces::bary_par_compo_ protected
Referenced by ajouter_terme_source_interfaces(), calculer_indicatrice_next(), get_bary_par_compo_itfc_in_cell_ft(), initialize(), and switch_indicatrice_next_old().
intersection_ijk_cell_
Intersection_Interface_ijk_cell IJK_Interfaces::intersection_ijk_cell_ protected
Referenced by get_intersection_ijk_cell(), get_set_intersection_ijk_cell(), and initialize().
intersection_ijk_face_
Intersection_Interface_ijk_face IJK_Interfaces::intersection_ijk_face_ protected
Referenced by get_intersection_ijk_face(), get_set_intersection_ijk_face(), and initialize().
ijk_compo_connex_
IJK_Composantes_Connex IJK_Interfaces::ijk_compo_connex_ protected
Referenced by allocate_ijk_compo_connex_fields(), associate_rising_velocities_parameters(), associer_pb_base(), compute_compo_connex_from_bounding_box(), compute_compo_connex_from_interface(), compute_rising_velocities_from_compo(), get_ijk_compo_connex(), initialise_ijk_compo_connex_bubbles_params(), initialize(), read_bubbles_barycentres(), read_bubbles_barycentres_vel(), and store_bubbles_barycentres().
bubbles_velocities_
DoubleTab IJK_Interfaces::bubbles_velocities_ protected
Referenced by calculer_vecteurs_de_deplacement_rigide(), and get_bubble_velocities_from_interface().
bubbles_velocities_bary_
DoubleTab IJK_Interfaces::bubbles_velocities_bary_ protected
Referenced by calculer_vecteurs_de_deplacement_rigide(), compute_bubbles_volume_and_barycentres(), get_bubble_velocities_from_barycentres(), get_bubbles_velocities_magnitude_from_barycentres(), read_bubbles_barycentres_old_new(), and store_bubbles_barycentres().
bubbles_rising_vectors_bary_
DoubleTab IJK_Interfaces::bubbles_rising_vectors_bary_ protected
Referenced by compute_bubbles_volume_and_barycentres(), get_bubble_rising_vectors_from_barycentres(), read_bubbles_barycentres_old_new(), and store_bubbles_barycentres().
bubbles_velocities_bary_magnitude_
ArrOfDouble IJK_Interfaces::bubbles_velocities_bary_magnitude_ protected
Referenced by compute_bubbles_volume_and_barycentres(), read_bubbles_barycentres_old_new(), and store_bubbles_barycentres().
bubbles_bary_old_
DoubleTab IJK_Interfaces::bubbles_bary_old_ protected
Referenced by compute_bubbles_volume_and_barycentres(), get_bubble_barycentres_old_new(), read_bubbles_barycentres_old_new(), and store_bubbles_barycentres().
bubbles_bary_new_
DoubleTab IJK_Interfaces::bubbles_bary_new_ protected
Referenced by compute_bubbles_volume_and_barycentres(), get_bubble_barycentres_old_new(), read_bubbles_barycentres_old_new(), and store_bubbles_barycentres().
read_barycentres_velocity_
int IJK_Interfaces::read_barycentres_velocity_ = 0 protected
Referenced by printOn(), read_bubbles_barycentres_old_new(), and readOn().
use_barycentres_velocity_
int IJK_Interfaces::use_barycentres_velocity_ = 0 protected
Referenced by calculer_vecteurs_de_deplacement_rigide(), printOn(), read_bubbles_barycentres(), read_bubbles_barycentres_old_new(), read_bubbles_barycentres_vel(), readOn(), and store_bubbles_barycentres().
has_computed_bubble_barycentres_
bool IJK_Interfaces::has_computed_bubble_barycentres_ = false protected
Referenced by compute_bubbles_volume_and_barycentres(), and reset_flags_and_counters().
has_readen_barycentres_prev_
bool IJK_Interfaces::has_readen_barycentres_prev_ = false protected
Referenced by compute_bubbles_volume_and_barycentres(), and read_bubbles_barycentres_old_new().
dt_impression_bilan_indicatrice_
int IJK_Interfaces::dt_impression_bilan_indicatrice_ = -1 protected
Referenced by get_dt_impression_bilan_indicatrice(), and readOn().
verbosite_surface_efficace_face_
int IJK_Interfaces::verbosite_surface_efficace_face_ = 1 protected
Referenced by readOn().
verbosite_surface_efficace_interface_
int IJK_Interfaces::verbosite_surface_efficace_interface_ = 1 protected
Referenced by readOn().
seuil_indicatrice_petite_
double IJK_Interfaces::seuil_indicatrice_petite_ = -1 protected
Referenced by below_small_threshold(), est_desequilibre(), est_reguliere(), and set_seuil_indicatrice_petite().
seuil_indicatrice_negligeable_
double IJK_Interfaces::seuil_indicatrice_negligeable_ = 1e-6 protected
Referenced by calculer_indicatrice(), readOn(), and set_seuil_indicatrice_petite().
cut_cell_activated_
int IJK_Interfaces::cut_cell_activated_ = 0 protected
Referenced by activate_cut_cell(), and initialize().
indicatrice_surfacique_efficace_face_
DoubleTabFT_cut_cell_vector3 IJK_Interfaces::indicatrice_surfacique_efficace_face_ protected
Referenced by activate_cut_cell(), and get_indicatrice_surfacique_efficace_face().
indicatrice_surfacique_efficace_face_initial_
DoubleTabFT_cut_cell_vector3 IJK_Interfaces::indicatrice_surfacique_efficace_face_initial_ protected
Referenced by activate_cut_cell().
indicatrice_surfacique_efficace_face_correction_
DoubleTabFT_cut_cell_vector6 IJK_Interfaces::indicatrice_surfacique_efficace_face_correction_ protected
Referenced by activate_cut_cell().
indicatrice_surfacique_efficace_face_absolute_error_
DoubleTabFT_cut_cell_scalar IJK_Interfaces::indicatrice_surfacique_efficace_face_absolute_error_ protected
Referenced by activate_cut_cell().
indicatrice_surfacique_efficace_deformation_face_
IJK_Field_vector3_double IJK_Interfaces::indicatrice_surfacique_efficace_deformation_face_ protected
Referenced by calculer_var_volume_remaillage(), and initialize().
surface_efficace_interface_
DoubleTabFT_cut_cell_scalar IJK_Interfaces::surface_efficace_interface_ protected
Referenced by activate_cut_cell(), get_surface_efficace_interface(), and imprime_bilan_indicatrice().
surface_efficace_interface_initial_
DoubleTabFT_cut_cell_scalar IJK_Interfaces::surface_efficace_interface_initial_ protected
Referenced by activate_cut_cell().
coord_deplacement_interface_
DoubleTabFT_cut_cell_vector3 IJK_Interfaces::coord_deplacement_interface_ protected
Referenced by activate_cut_cell(), and get_coord_deplacement_interface().
vitesse_deplacement_interface_
DoubleTabFT_cut_cell_vector3 IJK_Interfaces::vitesse_deplacement_interface_ protected
Referenced by activate_cut_cell(), and get_vitesse_deplacement_interface().
normale_deplacement_interface_
DoubleTabFT_cut_cell_vector3 IJK_Interfaces::normale_deplacement_interface_ protected
Referenced by activate_cut_cell(), and get_normale_deplacement_interface().
scalar_post_fields_
std::map<Motcle, IJK_Field_double> IJK_Interfaces::scalar_post_fields_ protected
Referenced by get_IJK_field(), and register_fields().