TrioCFD: Paroi_hyd_base_EF Class Reference
Paroi_hyd_base_EF Class Reference
#include <Paroi_hyd_base_EF.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Turbulence_paroi_base
void associer_modele (const Modele_turbulence_hyd_base &)
int calculer_hyd (Champ_Fonc_base &, Champ_Fonc_base &)
int calculer_hyd (Champ_Inc_base &)
const Type_info * get_info () const override
virtual void imprimer_premiere_ligne_ustar (int, const TRUST_List< Nom > &, const Nom &) const
virtual void imprimer_ustar_mean_only (Sortie &, int, const TRUST_List< Nom > &, const Nom &) const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Turbulence_paroi_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Turbulence_paroi_base
static void typer_lire_turbulence_paroi (TRUST_Deriv< Turbulence_paroi_base > &, const Modele_turbulence_hyd_base &, Entree &)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Paroi_hyd_base_EF()
Paroi_hyd_base_EF::Paroi_hyd_base_EF ()
~Paroi_hyd_base_EF()
Paroi_hyd_base_EF::~Paroi_hyd_base_EF () override
Member Function Documentation
info()
const Type_info * Paroi_hyd_base_EF::info () static
get_info()
const Type_info * Paroi_hyd_base_EF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
Reimplemented in Paroi_loi_WW_hyd_EF, Paroi_std_hyd_EF, Loi_expert_hydr_EF, and Paroi_negligeable_EF.
self_cast() [1/2]
Paroi_hyd_base_EF & Paroi_hyd_base_EF::self_cast (Objet_U & r) static
self_cast() [2/2]
const Paroi_hyd_base_EF & Paroi_hyd_base_EF::self_cast (const Objet_U & r) static
printOn()
Sortie & Paroi_hyd_base_EF::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
Reimplemented in Paroi_loi_WW_hyd_EF, Paroi_std_hyd_EF, Loi_expert_hydr_EF, and Paroi_negligeable_EF.
References Objet_U::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Paroi_hyd_base_EF::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
Reimplemented in Paroi_loi_WW_hyd_EF, Paroi_std_hyd_EF, Loi_expert_hydr_EF, and Paroi_negligeable_EF.
References Turbulence_paroi_base::readOn().
Referenced by Paroi_std_hyd_EF::readOn().
associer()
void Paroi_hyd_base_EF::associer (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis) override virtual
Implements Turbulence_paroi_base.
References Turbulence_paroi_base::le_dom_Cl_dis_, and Turbulence_paroi_base::le_dom_dis_.
init_lois_paroi_()
void Paroi_hyd_base_EF::init_lois_paroi_ ()
References Turbulence_paroi_base::Cisaillement_paroi_, Domaine_VF::creer_tableau_faces_bord(), Objet_U::dimension, TRUSTVect< _TYPE_, _SIZE_ >::get_md_vector(), Turbulence_paroi_base::le_dom_dis_, MD_Vector::non_nul(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), Turbulence_paroi_base::tab_d_plus_, Turbulence_paroi_base::tab_u_star_, and TRUST_Ref< _CLASSE_ >::valeur().
corriger_derivee_impl()
DoubleTab & Paroi_hyd_base_EF::corriger_derivee_impl (DoubleTab & d) const override virtual
Reimplemented from Turbulence_paroi_base.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), face_keps_imposee_, flag_face_keps_imposee_, and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
face_keps_imposee()
const ArrOfInt & Paroi_hyd_base_EF::face_keps_imposee () const inline
References face_keps_imposee_.
creer_champ()
void Paroi_hyd_base_EF::creer_champ (const Motcle & motlu) override virtual
Implements Champs_compris_interface.
References Champs_compris_T< FIELD_TYPE >::ajoute_champ(), Turbulence_paroi_base::champ_u_star_, Turbulence_paroi_base::champs_compris_, Probleme_base::discretisation(), Discretisation_base::discretiser_champ(), Equation_base::domaine_dis(), Turbulence_paroi_base::mon_modele_turb_hyd, Objet_U_ptr::non_nul(), and Equation_base::probleme().
get_champ()
const Champ_base & Paroi_hyd_base_EF::get_champ (const Motcle & nom) const override virtual
Implements Champs_compris_interface.
References Turbulence_paroi_base::champ_u_star_, Turbulence_paroi_base::champs_compris_, Equation_base::domaine_Cl_dis(), Equation_base::domaine_dis(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_VF::face_voisins(), Champs_compris_T< FIELD_TYPE >::get_champ(), Turbulence_paroi_base::le_dom_dis_, Objet_U_ptr::le_nom(), Domaine_Cl_dis_base::les_conditions_limites(), Champ_Fonc_base::mettre_a_jour(), Turbulence_paroi_base::mon_modele_turb_hyd, Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), Equation_base::schema_temps(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), Turbulence_paroi_base::tab_u_star_, Schema_Temps_base::temps_courant(), TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), and Champ_Don_base::valeurs().
Referenced by has_champ().
has_champ() [1/2]
bool Paroi_hyd_base_EF::has_champ (const Motcle & nom, TRUST_Ref< Champ_base * > & ref_champ) const override virtual
Implements Champs_compris_interface.
References Turbulence_paroi_base::champ_u_star_, Turbulence_paroi_base::champs_compris_, get_champ(), Champs_compris_T< FIELD_TYPE >::has_champ(), and Objet_U_ptr::le_nom().
has_champ() [2/2]
bool Paroi_hyd_base_EF::has_champ (const Motcle & nom) const override virtual
Implements Champs_compris_interface.
References Turbulence_paroi_base::champ_u_star_, Turbulence_paroi_base::champs_compris_, Champs_compris_T< FIELD_TYPE >::has_champ(), and Objet_U_ptr::le_nom().
get_noms_champs_postraitables()
void Paroi_hyd_base_EF::get_noms_champs_postraitables (Noms & nom, Option opt = NONE) const override virtual
Implements Champs_compris_interface.
References Turbulence_paroi_base::get_noms_champs_postraitables().
Member Data Documentation
info_obj
const Type_info Paroi_hyd_base_EF::info_obj static
face_keps_imposee_
IntVect Paroi_hyd_base_EF::face_keps_imposee_ protected
Referenced by corriger_derivee_impl(), and face_keps_imposee().
flag_face_keps_imposee_
int Paroi_hyd_base_EF::flag_face_keps_imposee_ = 0 protected
Referenced by corriger_derivee_impl().