TrioCFD: Terme_Boussinesq_PolyMAC_Face Class Reference
Terme_Boussinesq_PolyMAC_Face Class Reference
#include <Terme_Boussinesq_PolyMAC_Face.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Terme_Boussinesq_base
const Type_info * get_info () const override
void mettre_a_jour (double temps) override
Public Member Functions inherited from Source_base
virtual int a_pour_Champ_Fonc (const Motcle &mot, TRUST_Ref< Champ_base * > &ch_ref) const
virtual void associer_champ_rho (const Champ_base &champ_rho)
virtual void completer ()
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
virtual void resetTime (double t)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Terme_Boussinesq_base
int lire_motcle_non_standard (const Motcle &, Entree &) override
Sortie & printOn (Sortie &x) const override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
Terme Source de Boussinesq pour une dicretisation PolyMAC_P0P1NC
Constructor & Destructor Documentation
Terme_Boussinesq_PolyMAC_Face()
Terme_Boussinesq_PolyMAC_Face::Terme_Boussinesq_PolyMAC_Face ()
~Terme_Boussinesq_PolyMAC_Face()
Terme_Boussinesq_PolyMAC_Face::~Terme_Boussinesq_PolyMAC_Face ()
Member Function Documentation
cree_instance()
Objet_U * Terme_Boussinesq_PolyMAC_Face::cree_instance () static
taille_memoire()
unsigned Terme_Boussinesq_PolyMAC_Face::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Terme_Boussinesq_PolyMAC_Face::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Terme_Boussinesq_PolyMAC_Face::info () static
get_info()
const Type_info * Terme_Boussinesq_PolyMAC_Face::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Source_base.
self_cast() [1/2]
Terme_Boussinesq_PolyMAC_Face & Terme_Boussinesq_PolyMAC_Face::self_cast (Objet_U & r) static
self_cast() [2/2]
const Terme_Boussinesq_PolyMAC_Face & Terme_Boussinesq_PolyMAC_Face::self_cast (const Objet_U & r) static
printOn()
Sortie & Terme_Boussinesq_PolyMAC_Face::printOn (Sortie & os) const override protected virtual
DOES NOTHING - to override in derived classes.
Imprime la source sur un flot de sortie.
Parameters
(Sortie& os) le flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Source_base.
References Terme_Boussinesq_base::printOn().
readOn()
Entree & Terme_Boussinesq_PolyMAC_Face::readOn (Entree & is) override protected virtual
DOES NOTHING - to override in derived classes.
Lecture d'un terme source sur un flot d'entree.
Parameters
(Entree& is) le flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Source_base.
References Terme_Boussinesq_base::readOn().
has_interface_blocs()
int Terme_Boussinesq_PolyMAC_Face::has_interface_blocs () const inline override virtual
Reimplemented from Source_base.
dimensionner_blocs()
void Terme_Boussinesq_PolyMAC_Face::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl = {}) const inline override virtual
Reimplemented from Source_base.
ajouter_blocs()
void Terme_Boussinesq_PolyMAC_Face::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = {}) const override virtual
Reimplemented from Source_base.
References TRUSTArray< _TYPE_, _SIZE_ >::addr(), Terme_Boussinesq_base::beta(), Terme_Boussinesq_base::check(), Objet_U::dimension, TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), MorEqn::equation(), Terme_Boussinesq_base::equation_scalaire(), Terme_Boussinesq_base::gravite(), Convection_Diffusion_std::inconnue(), le_dom_PolyMAC, TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Milieu_base::masse_volumique(), Equation_base::milieu(), Champ_Proto::passe(), Milieu_base::porosite_elem(), Milieu_base::porosite_face(), Terme_Boussinesq_base::Scalaire0(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), and Champ_Inc_base::valeurs().
check_multiphase_compatibility()
void Terme_Boussinesq_PolyMAC_Face::check_multiphase_compatibility () const inline override virtual
Reimplemented from MorEqn.
associer_domaines()
void Terme_Boussinesq_PolyMAC_Face::associer_domaines (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis) override protected virtual
Implements Source_base.
References le_dom_Cl_PolyMAC, and le_dom_PolyMAC.
Member Data Documentation
info_obj
const Type_info Terme_Boussinesq_PolyMAC_Face::info_obj static
le_dom_PolyMAC
TRUST_Ref< Domaine_PolyMAC *> Terme_Boussinesq_PolyMAC_Face::le_dom_PolyMAC protected
Referenced by ajouter_blocs(), and associer_domaines().
le_dom_Cl_PolyMAC
TRUST_Ref< Domaine_Cl_PolyMAC *> Terme_Boussinesq_PolyMAC_Face::le_dom_Cl_PolyMAC protected
Referenced by associer_domaines().