TrioCFD: Calculer_Moments Class Reference
Calculer_Moments Class Reference
#include <Calculer_Moments.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Interprete_geometrique_base_32_64< _SIZE_ >
const Type_info * get_info () const override
void mettre_a_jour_sous_domaine (Domaine_t &domaine, int_t &elem, int_t num_premier_elem, int_t nb_elem) const
Public Member Functions inherited from Interprete
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Interprete_geometrique_base_32_64< _SIZE_ >
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Interprete
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Interprete
static Objet_U & objet (const Nom &)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Calculer_Moments()
Calculer_Moments::Calculer_Moments ()
~Calculer_Moments()
Calculer_Moments::~Calculer_Moments ()
Member Function Documentation
cree_instance()
Objet_U * Calculer_Moments::cree_instance () static
taille_memoire()
unsigned Calculer_Moments::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Calculer_Moments::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Calculer_Moments::info () static
get_info()
const Type_info * Calculer_Moments::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
Calculer_Moments & Calculer_Moments::self_cast (Objet_U & r) static
self_cast() [2/2]
const Calculer_Moments & Calculer_Moments::self_cast (const Objet_U & r) static
printOn()
Sortie & Calculer_Moments::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
References Objet_U::que_suis_je().
readOn()
Entree & Calculer_Moments::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
centre_de_gravite()
const ArrOfDouble & Calculer_Moments::centre_de_gravite () const inline
interpreter_()
Entree & Calculer_Moments::interpreter_ (Entree & is) override virtual
Implements Interprete_geometrique_base_32_64< _SIZE_ >.
References Interprete_geometrique_base_32_64< _SIZE_ >::associer_domaine(), Domaine_32_64< _SIZE_ >::calculer_mon_centre_de_gravite(), Objet_U::dimension, Interprete_geometrique_base_32_64< _SIZE_ >::domaine(), Process::exit(), Domaine_32_64< _SIZE_ >::exporter_mon_centre_de_gravite(), Domaine_base::moments_a_imprimer(), and TRUSTArray< _TYPE_, _SIZE_ >::resize_array().
Member Data Documentation
info_obj
const Type_info Calculer_Moments::info_obj static