TrioCFD: Champ_Generique_Ecart_Type Class Reference
Champ_Generique_Ecart_Type Class Reference
#include <Champ_Generique_Ecart_Type.h>
Public Member Functions
const Type_info * get_info () const override
const Noms get_property (const Motcle &query) const override
Public Member Functions inherited from Champ_Generique_Statistiques_base
const Type_info * get_info () const override
Public Member Functions inherited from Champ_Gen_de_Champs_Gen
void get_copy_domain (Domaine &) const override
void get_copy_values (DoubleTab &) const override
int get_dimension () const override
const Type_info * get_info () const override
Entity get_localisation (const int index=-1) const override
const Noms get_property (const Motcle &query) const override
const IntTab & get_ref_connectivity (Entity index1, Entity index2) const override
const DoubleTab & get_ref_coordinates () const override
const Domaine & get_ref_domain () const override
const Domaine_dis_base & get_ref_domaine_dis_base () const override
const DoubleTab & get_ref_values () const override
void get_xyz_values (const DoubleTab &coords, DoubleTab &values, ArrOfBit &validity_flag) const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
Public Member Functions inherited from Champ_Generique_base
virtual void get_copy_domain (Domaine &) const
virtual void get_copy_values (DoubleTab &) const
virtual int get_dimension () const
const Type_info * get_info () const override
virtual Entity get_localisation (const int index=-1) const
virtual const Noms get_property (const Motcle &query) const
virtual const IntTab & get_ref_connectivity (Entity index1, Entity index2) const
virtual const DoubleTab & get_ref_coordinates () const
virtual const Domaine & get_ref_domain () const
virtual const Domaine_dis_base & get_ref_domaine_dis_base () const
virtual const DoubleTab & get_ref_values () const
virtual void get_xyz_values (const DoubleTab &coords, DoubleTab &values, ArrOfBit &validity_flag) const
int lire_motcle_non_standard (const Motcle &, Entree &) override
void nommer (const Nom &nom) override
int reprendre (Entree &is) override
int sauvegarder (Sortie &os) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Champ_Generique_Statistiques_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Champ_Generique_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
La classe porte un operateur statistique "Op_Ecart_Type"
Syntaxe a respecter pour jdd
"nom_champ" Ecart_Type { t_deb "val_tdeb" t_fin "val_tfin" source "type_champ_gen" { ...source ref_Champ { Pb_champ "nom_pb" "nom_champ_discret" } } } "nom_champ" fixe par utilisateur sera le nom du champ generique "val_tdeb" et "val_tfin" valeur de debut et fin des statistiques pour ce champ "type_champ_gen" type d'un champ generique
Constructor & Destructor Documentation
Champ_Generique_Ecart_Type()
Champ_Generique_Ecart_Type::Champ_Generique_Ecart_Type ()
~Champ_Generique_Ecart_Type()
Champ_Generique_Ecart_Type::~Champ_Generique_Ecart_Type ()
Member Function Documentation
cree_instance()
Objet_U * Champ_Generique_Ecart_Type::cree_instance () static
taille_memoire()
unsigned Champ_Generique_Ecart_Type::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Champ_Generique_Ecart_Type::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Champ_Generique_Ecart_Type::info () static
get_info()
const Type_info * Champ_Generique_Ecart_Type::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Champ_Gen_de_Champs_Gen.
self_cast() [1/2]
Champ_Generique_Ecart_Type & Champ_Generique_Ecart_Type::self_cast (Objet_U & r) static
self_cast() [2/2]
const Champ_Generique_Ecart_Type & Champ_Generique_Ecart_Type::self_cast (const Objet_U & r) static
printOn()
Sortie & Champ_Generique_Ecart_Type::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Champ_Gen_de_Champs_Gen.
References Objet_U::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Champ_Generique_Ecart_Type::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Champ_Gen_de_Champs_Gen.
References Champ_Generique_Statistiques_base::readOn().
get_property()
const Noms Champ_Generique_Ecart_Type::get_property (const Motcle & query) const override virtual
Renvoie la propriete demandee.
Exemples: "DISCRETISATION" : type du champ discret (P0, P1, P1NC, etc...) "ELEMENT_TYPE" : type de l'element de plus grande dimension ({TRIANGLE}, {TETRAHEDRA}, {QUAD}, {HEXA}, etc) "DYNAMIC_MESH" : le maillage est-il dynamique ou pas ({STATIC}, {DYNAMIC}) "NAME" : nom du champ "COMPONENT_NAMES" : nom des composantes du champ ({K,EPSILON} ou {VITESSE_X,VITESSE_Y,VITESSE_Z}) "BOUNDARY_NAMES" : nom des bords "COORDINATES" : systeme de coordonnees des noeuds ({X}, {X,Y}, {X,Y,Z}, {R,THETA}, etc...) Exceptions:
GenericFieldError::INVALID : query non comprise
Reimplemented from Champ_Gen_de_Champs_Gen.
References Champ_Generique_base::get_property(), Champ_Gen_de_Champs_Gen::get_property(), Champ_Gen_de_Champs_Gen::get_source(), Champ_Generique_base::nom_post_, Motcles::search(), and TRUST_Vector< _CLASSE_ >::size().
Referenced by completer().
temps()
double Champ_Generique_Ecart_Type::temps () const inline override virtual
Implements Champ_Generique_Statistiques_base.
References Op_Ecart_type::integrale(), Integrale_tps_Champ::le_champ_calcule(), Op_Ecart_Type_, and Champ_base::temps().
Referenced by get_champ().
integrale()
const Integrale_tps_Champ & Champ_Generique_Ecart_Type::integrale () const inline override virtual
Implements Champ_Generique_Statistiques_base.
References Op_Ecart_type::integrale(), and Op_Ecart_Type_.
Referenced by get_champ(), and get_champ_without_evaluation().
valeurs()
const DoubleTab & Champ_Generique_Ecart_Type::valeurs () const inline
References Op_Moyenne::integrale(), Integrale_tps_Champ::le_champ_calcule(), Op_Ecart_type::moyenne(), Op_Ecart_Type_, and Champ_Don_base::valeurs().
valeurs_carre()
const DoubleTab & Champ_Generique_Ecart_Type::valeurs_carre () const inline
References Op_Ecart_type::integrale(), Integrale_tps_Champ::le_champ_calcule(), Op_Ecart_Type_, and Champ_Don_base::valeurs().
dt_integration()
double Champ_Generique_Ecart_Type::dt_integration () const inline
References Op_Moyenne::dt_integration(), Op_Ecart_type::moyenne(), and Op_Ecart_Type_.
dt_integration_carre()
double Champ_Generique_Ecart_Type::dt_integration_carre () const inline
References Op_Ecart_type::dt_integration_carre(), and Op_Ecart_Type_.
Operateur_Statistique() [1/2]
Operateur_Statistique_tps_base & Champ_Generique_Ecart_Type::Operateur_Statistique () inline override virtual
Implements Champ_Generique_Statistiques_base.
References Op_Ecart_Type_.
Operateur_Statistique() [2/2]
const Operateur_Statistique_tps_base & Champ_Generique_Ecart_Type::Operateur_Statistique () const inline override virtual
Implements Champ_Generique_Statistiques_base.
References Op_Ecart_Type_.
get_champ_without_evaluation()
const Champ_base & Champ_Generique_Ecart_Type::get_champ_without_evaluation (TRUST_Deriv< Champ_base > & espace_stockage) const override virtual
Implements Champ_Generique_base.
References Champ_Gen_de_Champs_Gen::creer_espace_stockage(), integrale(), Integrale_tps_Champ::le_champ(), Field_base::nature_du_champ(), and Field_base::nb_comp().
get_champ()
const Champ_base & Champ_Generique_Ecart_Type::get_champ (TRUST_Deriv< Champ_base > & espace_stockage) const override virtual
Implements Champ_Generique_base.
References Op_Ecart_type::calculer_valeurs(), Champ_base::changer_temps(), Champ_Gen_de_Champs_Gen::creer_espace_stockage(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Objet_U_ptr::est_nul(), integrale(), Integrale_tps_Champ::le_champ(), Field_base::nature_du_champ(), Field_base::nb_comp(), Op_Ecart_Type_, temps(), and Champ_Don_base::valeurs().
completer()
void Champ_Generique_Ecart_Type::completer (const Postraitement_base & post) override virtual
Reimplemented from Champ_Gen_de_Champs_Gen.
References Op_Ecart_type::associer(), Op_Ecart_type::associer_op_stat(), Champ_Gen_de_Champs_Gen::completer(), Op_Ecart_type::completer(), Postraitement::comprend_champ_post(), Process::exit(), Postraitement::get_champ_post(), Champ_Generique_base::get_property(), get_property(), Champ_Gen_de_Champs_Gen::get_ref_domaine_dis_base(), Champ_Gen_de_Champs_Gen::get_ref_pb_base(), Champ_Gen_de_Champs_Gen::get_source(), Probleme_U::le_nom(), Postraitement_base::le_nom(), Op_Ecart_Type_, Champ_Gen_de_Champs_Gen::parent_name_, Champ_Generique_Statistiques_base::tstat_deb_, Champ_Generique_Statistiques_base::tstat_fin_, and Champ_Generique_Statistiques_base::use_source_name_only_.
nommer_source()
void Champ_Generique_Ecart_Type::nommer_source () override virtual
Reimplemented from Champ_Gen_de_Champs_Gen.
References Champ_Generique_base::get_property(), Champ_Gen_de_Champs_Gen::get_source(), Champ_Generique_base::nom_post_, and Champ_Generique_base::nommer().
Member Data Documentation
info_obj
const Type_info Champ_Generique_Ecart_Type::info_obj static
Op_Ecart_Type_
Op_Ecart_type Champ_Generique_Ecart_Type::Op_Ecart_Type_ protected
Referenced by completer(), dt_integration(), dt_integration_carre(), get_champ(), integrale(), Operateur_Statistique(), temps(), valeurs(), and valeurs_carre().