TrioCFD: Calcul_Production_K_VEF Class Reference
Calcul_Production_K_VEF Class Reference
#include <Calcul_Production_K_VEF.h>
Protected Member Functions
DoubleTab & calculer_terme_production_K (const Domaine_VEF &, const Domaine_Cl_VEF &, DoubleTab &, const DoubleTab &, const DoubleTab &, const DoubleTab &, const int &interpol_visco, const double &limiteur) const
double get_turbulent_viscosity (const DoubleTab &visco_turb, const DoubleVect &volumes, const int type_interpo, const int poly1, const int poly2, const double limiteur) const
void loop_for_internal_or_periodic_faces (DoubleTab &prodK, const DoubleTab &gradient_elem, const DoubleTab &visco_turb, const DoubleVect &volumes, const IntTab &face_voisins, const int nfaceinit, const int nfaceend, const int interpol_visco, const double limiteur) const
void loop_for_non_periodic_boundaries (DoubleTab &prodK, const DoubleTab &gradient_elem, const DoubleTab &visco_turb, const DoubleVect &volumes, const IntTab &face_voisins, const int nfaceinit, const int nfaceend, const int interpol_visco, const double limiteur) const
Constructor & Destructor Documentation
Calcul_Production_K_VEF()
Calcul_Production_K_VEF::Calcul_Production_K_VEF () inline protected
Member Function Documentation
calculer_terme_production_K()
DoubleTab & Calcul_Production_K_VEF::calculer_terme_production_K (const Domaine_VEF & domaine_VEF, const Domaine_Cl_VEF & zcl_VEF, DoubleTab & prodK, const DoubleTab & K_eps, const DoubleTab & vit, const DoubleTab & visco_turb, const int & interpol_visco, const double & limiteur) const protected
Compute the production term for the turbulent kinetic energy.
The total production term writes Being in a incompressible flow, the first part is not computed.
Like the TKE and epsilon, P is discretised on face centers.
Parameters
[in] const Domaine_VEF& domaine_VEF,
[in] const Domaine_Cl_VEF& zcl_VEF,
[in] DoubleTab& prodK,
[in] const DoubleTab& K_eps,
[in] const DoubleTab& vit,
[in] const DoubleTab& visco_turb,
[in] const int& interpol_visco,
[in] const double& limiteur
[out]
return DoubleTab& prodK
References Champ_P1NC::calcul_gradient(), Objet_U::dimension, Domaine_VF::face_voisins(), Domaine_Cl_dis_base::les_conditions_limites(), loop_for_internal_or_periodic_faces(), loop_for_non_periodic_boundaries(), Domaine_dis_base::nb_elem_tot(), Domaine_VF::nb_faces(), Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), Domaine_VF::premiere_face_int(), TRUST_Deriv< _CLASSE_ >::valeur(), and Domaine_VF::volumes().
Referenced by Source_Transport_K_Eps_Bas_Reynolds_anisotherme_VEF_Face::ajouter(), Source_Transport_K_Eps_Bas_Reynolds_VEF_Face::ajouter(), Source_Transport_VEF_Face_base::ajouter_keps(), Source_Transport_K_Omega_VEF_Face_base::ajouter_komega(), and Source_Transport_K_Omega_VEF_Face::contribuer_a_avec().
loop_for_internal_or_periodic_faces()
void Calcul_Production_K_VEF::loop_for_internal_or_periodic_faces (DoubleTab & prodK, const DoubleTab & gradient_elem, const DoubleTab & visco_turb, const DoubleVect & volumes, const IntTab & face_voisins, const int nfaceinit, const int nfaceend, const int interpol_visco, const double limiteur) const protected
Compute production term on internal and periodic boundary faces.
Using the velocity gradient, the loop computes the production term written with .
Parameters
[in] DoubleTab& prodK
[in] const DoubleTab& gradient_elem,
[in] const DoubleTab& visco_turb,
[in] const DoubleVect& volumes,
[in] const IntTab& face_voisins,
[in] const int nfaceinit,
[in] const int nfaceend,
[in] const int interpol_visco,
[in] const double limiteur
Returns
References Objet_U::dimension, and get_turbulent_viscosity().
Referenced by calculer_terme_production_K().
loop_for_non_periodic_boundaries()
void Calcul_Production_K_VEF::loop_for_non_periodic_boundaries (DoubleTab & prodK, const DoubleTab & gradient_elem, const DoubleTab & visco_turb, const DoubleVect & volumes, const IntTab & face_voisins, const int nfaceinit, const int nfaceend, const int interpol_visco, const double limiteur) const protected
Compute production term on non periodic boundary faces.
Using the velocity gradient, the loop computes the production term written with .
Parameters
[in] DoubleTab& prodK
[in] const DoubleTab& gradient_elem,
[in] const DoubleTab& visco_turb,
[in] const DoubleVect& volumes,
[in] const IntTab& face_voisins,
[in] const int nfaceinit,
[in] const int nfaceend,
[in] const int interpol_visco,
[in] const double limiteur
Returns
References Objet_U::dimension.
Referenced by calculer_terme_production_K().
calculer_terme_production_K_BiK()
DoubleTab & Calcul_Production_K_VEF::calculer_terme_production_K_BiK (const Domaine_VEF & domaine_VEF, const Domaine_Cl_VEF & zcl_VEF, DoubleTab & P, const DoubleTab & K, const DoubleTab & eps, const DoubleTab & vit, const DoubleTab & visco_turb, const int & interpol_visco, const double & limiteur) const protected
References Champ_P1NC::calcul_gradient(), Objet_U::dimension, Domaine_VF::face_voisins(), get_turbulent_viscosity(), Domaine_Cl_dis_base::les_conditions_limites(), Domaine_dis_base::nb_elem_tot(), Domaine_VF::nb_faces(), Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), Domaine_VF::premiere_face_int(), TRUST_Deriv< _CLASSE_ >::valeur(), and Domaine_VF::volumes().
Referenced by Source_Transport_K_Realisable_VEF_Face::ajouter().
calculer_terme_production_K_EASM()
DoubleTab & Calcul_Production_K_VEF::calculer_terme_production_K_EASM (const Domaine_VEF & domaine_VEF, const Domaine_Cl_VEF & zcl_VEF, DoubleTab & P, const DoubleTab & K_eps, const DoubleTab & gradient_elem, const DoubleTab & visco_turb, const DoubleTab & Re, const int & interpol_visco, const double & limiteur) const protected
References calcul_tenseur_face(), compute_production_term_EASM(), Objet_U::dimension, Process::exit(), Domaine_VF::face_voisins(), get_turbulent_viscosity(), Domaine_Cl_dis_base::les_conditions_limites(), Domaine_VF::nb_faces(), Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), Domaine_VF::premiere_face_int(), TRUST_Deriv< _CLASSE_ >::valeur(), and Domaine_VF::volumes().
Referenced by Source_Transport_VEF_Face_base::ajouter_keps().
compute_production_term_EASM()
void Calcul_Production_K_VEF::compute_production_term_EASM (const int face, const double visco_face, const DoubleTab & Re_face, const DoubleTab & gradient_face, DoubleTab & P) const protected
References Objet_U::dimension.
Referenced by calculer_terme_production_K_EASM().
calcul_tenseur_face()
DoubleTab & Calcul_Production_K_VEF::calcul_tenseur_face (DoubleTab & Tenseur_face, const DoubleTab & Tenseur_elem, const Domaine_VEF & domaine_VEF, const Domaine_Cl_VEF & domaine_Cl_VEF) const protected
References Objet_U::dimension, Domaine_VF::face_voisins(), Domaine_Cl_dis_base::les_conditions_limites(), Domaine_VF::nb_faces(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), Domaine_VF::premiere_face_int(), TRUST_Vector< _CLASSE_ >::size(), TRUST_Deriv< _CLASSE_ >::valeur(), and Domaine_VF::volumes().
Referenced by calculer_terme_production_K_EASM().
get_turbulent_viscosity()
double Calcul_Production_K_VEF::get_turbulent_viscosity (const DoubleTab & visco_turb, const DoubleVect & volumes, const int type_interpo, const int poly1, const int poly2, const double limiteur) const protected
Get the turbulent viscosity depending on the interpolation choice.
if type_interpo == 0: arithmetic interpolation (instable) if type_interpo == 1: harmonic mean (used for the realisable k-epsilon) if type_interpo == 2: weighted harmonic mean (used for the realisable k-epsilon)
Parameters
[in] const DoubleTab& visco_turb
[in] const DoubleVect& volumes
[in] const int type_interpo
[in] const int poly1
[in] const int poly2
[in] const double limiteur
[out]
return double
References Process::exit().
Referenced by calculer_terme_production_K_BiK(), calculer_terme_production_K_EASM(), and loop_for_internal_or_periodic_faces().
calculer_terme_destruction_K_gen()
DoubleTab & Calcul_Production_K_VEF::calculer_terme_destruction_K_gen (const Domaine_VEF & domaine_VEF, const Domaine_Cl_VEF & zcl_VEF, DoubleTab & G, const DoubleTab & inconnue, const DoubleTab & alpha_turb, const Champ_Don_base & ch_beta, const DoubleVect & gravite, int nb_consti) const protected
References Champ_P1NC::calcul_gradient(), compute_utheta_nbConsti_gt_1_nbCompo_eq_0(), compute_utheta_nbConsti_gt_1_nbCompo_eq_1(), compute_utheta_nbConsti_gt_1_nbCompo_gt_1(), compute_utheta_nbConsti_le_1_nbCompo_eq_0(), compute_utheta_nbConsti_le_1_nbCompo_eq_1(), compute_utheta_nbConsti_le_1_nbCompo_gt_1(), Objet_U::dimension, Process::exit(), Domaine_VF::face_voisins(), Field_base::nb_comp(), Domaine_dis_base::nb_elem_tot(), Domaine_VF::nb_faces(), Domaine_VF::nb_faces_tot(), Champ_Don_base::valeurs(), and Domaine_VF::volumes().
Referenced by Source_Transport_K_Eps_Bas_Reynolds_anisotherme_VEF_Face::ajouter(), Source_Transport_VEF_Face_base::ajouter_anisotherme(), Source_Transport_VEF_Face_base::ajouter_anisotherme_concen(), and Source_Transport_VEF_Face_base::ajouter_concen().
compute_utheta_nbConsti_le_1_nbCompo_eq_0()
void Calcul_Production_K_VEF::compute_utheta_nbConsti_le_1_nbCompo_eq_0 (const Domaine_VEF & domaine_VEF, const Domaine_Cl_VEF & zcl_VEF, const IntTab & face_voisins, const DoubleVect & volumes, const DoubleTab & tab_beta, const DoubleTab & alpha_turb, const DoubleTrav & gradient_elem, DoubleTrav & u_theta) const protected
References Objet_U::dimension, Domaine_Cl_dis_base::les_conditions_limites(), Front_VF::nb_faces(), Domaine_VF::nb_faces_tot(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by calculer_terme_destruction_K_gen().
compute_utheta_nbConsti_le_1_nbCompo_eq_1()
void Calcul_Production_K_VEF::compute_utheta_nbConsti_le_1_nbCompo_eq_1 (const Domaine_VEF & domaine_VEF, const Domaine_Cl_VEF & zcl_VEF, const IntTab & face_voisins, const DoubleVect & volumes, const DoubleTab & tab_beta, const DoubleTab & alpha_turb, const DoubleTrav & gradient_elem, DoubleTrav & u_theta) const protected
References Objet_U::dimension, Domaine_Cl_dis_base::les_conditions_limites(), Front_VF::nb_faces(), Domaine_VF::nb_faces_tot(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by calculer_terme_destruction_K_gen().
compute_utheta_nbConsti_le_1_nbCompo_gt_1()
void Calcul_Production_K_VEF::compute_utheta_nbConsti_le_1_nbCompo_gt_1 (const Domaine_VEF & domaine_VEF, const Domaine_Cl_VEF & zcl_VEF, const IntTab & face_voisins, const DoubleVect & volumes, const DoubleTab & tab_beta, const DoubleTab & alpha_turb, const DoubleTrav & gradient_elem, DoubleTrav & u_theta) const protected
References Objet_U::dimension, Domaine_Cl_dis_base::les_conditions_limites(), Front_VF::nb_faces(), Domaine_VF::nb_faces_tot(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by calculer_terme_destruction_K_gen().
compute_utheta_nbConsti_gt_1_nbCompo_eq_0()
void Calcul_Production_K_VEF::compute_utheta_nbConsti_gt_1_nbCompo_eq_0 (const Domaine_VEF & domaine_VEF, const Domaine_Cl_VEF & zcl_VEF, const IntTab & face_voisins, const DoubleVect & volumes, const DoubleTab & tab_beta, const DoubleTab & alpha_turb, const DoubleTrav & gradient_elem, const int nb_consti, DoubleTrav & u_theta) const protected
References Objet_U::dimension, Domaine_Cl_dis_base::les_conditions_limites(), Front_VF::nb_faces(), Domaine_VF::nb_faces_tot(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by calculer_terme_destruction_K_gen().
compute_utheta_nbConsti_gt_1_nbCompo_eq_1()
void Calcul_Production_K_VEF::compute_utheta_nbConsti_gt_1_nbCompo_eq_1 (const Domaine_VEF & domaine_VEF, const Domaine_Cl_VEF & zcl_VEF, const IntTab & face_voisins, const DoubleVect & volumes, const DoubleTab & tab_beta, const DoubleTab & alpha_turb, const DoubleTrav & gradient_elem, const int nb_consti, DoubleTrav & u_theta) const protected
References Objet_U::dimension, Domaine_Cl_dis_base::les_conditions_limites(), Front_VF::nb_faces(), Domaine_VF::nb_faces_tot(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by calculer_terme_destruction_K_gen().
compute_utheta_nbConsti_gt_1_nbCompo_gt_1()
void Calcul_Production_K_VEF::compute_utheta_nbConsti_gt_1_nbCompo_gt_1 (const Domaine_VEF & domaine_VEF, const Domaine_Cl_VEF & zcl_VEF, const IntTab & face_voisins, const DoubleVect & volumes, const DoubleTab & tab_beta, const DoubleTab & alpha_turb, const DoubleTrav & gradient_elem, const int nb_consti, DoubleTrav & u_theta) const protected
References Objet_U::dimension, Domaine_Cl_dis_base::les_conditions_limites(), Front_VF::nb_faces(), Domaine_VF::nb_faces_tot(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by calculer_terme_destruction_K_gen().
mettre_a_jour()
void Calcul_Production_K_VEF::mettre_a_jour (double temps) inline protected
Referenced by Source_Transport_K_Omega_VEF_Face_base::mettre_a_jour(), Source_Transport_VEF_Face_base::mettre_a_jour(), Source_Transport_Eps_Realisable_VEF_Face::mettre_a_jour(), Source_Transport_K_Realisable_VEF_Face::mettre_a_jour(), and Source_Transport_K_Eps_Realisable_VEF_Face::mettre_a_jour().