TrioCFD: Diffu_totale_scal_base Class Reference
Diffu_totale_scal_base Class Reference
#include <Diffu_totale_scal_base.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
moleculaire et diffusivite turbulente) dans les equations de couche limite simplifiees necessaires a l'utilisation des lois de parois de type Balaras
Constructor & Destructor Documentation
~Diffu_totale_scal_base()
Diffu_totale_scal_base::~Diffu_totale_scal_base () override
Diffu_totale_scal_base()
Diffu_totale_scal_base::Diffu_totale_scal_base ()
Member Function Documentation
info()
const Type_info * Diffu_totale_scal_base::info () static
get_info()
const Type_info * Diffu_totale_scal_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Diffu_totale_base.
self_cast() [1/2]
Diffu_totale_scal_base & Diffu_totale_scal_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Diffu_totale_scal_base & Diffu_totale_scal_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Diffu_totale_scal_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Diffu_totale_base.
readOn()
Entree & Diffu_totale_scal_base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Diffu_totale_base.
set_visco_tot()
void Diffu_totale_scal_base::set_visco_tot (Diffu_totale_base & a) inline
References visco_tot.
Referenced by Paroi_TBLE_QDM_Scal::init_lois_paroi().
getPrandtl()
double Diffu_totale_scal_base::getPrandtl () inline
Referenced by Diffu_scal_lm::calculer_a_local().
setPrandtl()
void Diffu_totale_scal_base::setPrandtl (double p) inline
Referenced by Paroi_TBLE_QDM_Scal::init_lois_paroi().
Member Data Documentation
info_obj
const Type_info Diffu_totale_scal_base::info_obj static
visco_tot
TRUST_Ref< Diffu_totale_base *> Diffu_totale_scal_base::visco_tot
Referenced by Diffu_scal_lm::calculer_a_local(), and set_visco_tot().