TrioCFD: Front_VF Class Reference
Front_VF Class Reference
#include <Front_VF.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Frontiere_dis_base
void associer_frontiere (const Frontiere &)
Frontiere & frontiere ()
const Frontiere & frontiere () const
const Type_info * get_info () const override
const Nom & le_nom () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
See also
Frontiere_dis_base
Constructor & Destructor Documentation
Front_VF()
Front_VF::Front_VF ()
~Front_VF()
Front_VF::~Front_VF ()
Member Function Documentation
cree_instance()
Objet_U * Front_VF::cree_instance () static
taille_memoire()
unsigned Front_VF::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Front_VF::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Front_VF::info () static
get_info()
const Type_info * Front_VF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Frontiere_dis_base.
self_cast() [1/2]
Front_VF & Front_VF::self_cast (Objet_U & r) static
self_cast() [2/2]
const Front_VF & Front_VF::self_cast (const Objet_U & r) static
printOn()
Sortie & Front_VF::printOn (Sortie & os) const override protected virtual
Surcharge Objet_U::printOn(Sortie&) NE FAIT RIEN.
A surcharger dans les classes derivees. Imprime la frontiere discretisee sur un flot de sortie
Parameters
(Sortie& os) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Frontiere_dis_base.
References Objet_U::que_suis_je().
readOn()
Entree & Front_VF::readOn (Entree & is) override protected virtual
DOES NOTHING - to override in derived classes.
Lit une frontiere discretisee a partir d'un flot d'entree
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Frontiere_dis_base.
nb_faces()
int Front_VF::nb_faces () const inline
References Frontiere_dis_base::frontiere(), and Frontiere_32_64< _SIZE_ >::nb_faces().
Referenced by Operateur_Conv_sensibility_VEF::add_diffusion_scalar_term(), Operateur_Conv_sensibility_VEF::add_diffusion_term(), Op_Grad_PolyMAC_Face::ajouter(), Op_Conv_Amont_old_VEF_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Centre_EF_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_EF_VEF_P1NC::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Conv_Vort_VEF_Face::ajouter(), Op_Diff_VEF_Face_Q1::ajouter(), Op_Dift_VEF_Face_Q1::ajouter(), Op_Div_VEFP1B_Elem::ajouter(), Source_Reaction_Particules_VDF::ajouter(), Source_Reaction_Particules_VEF::ajouter(), SourceFiltree_FT_disc_VEF_P1NC::ajouter(), Source_Gravite_PF_VDF::ajouter(), Terme_Boussinesq_Sensibility_VEFPreP1B_Face::ajouter(), Source_Transport_Flux_Chaleur_Turbulente_VDF_Face::ajouter(), Source_Robin::ajouter(), Source_Robin_Scalaire::ajouter(), Source_Generique_Face_PolyMAC::ajouter(), Terme_Source_Qdm_Face_PolyMAC::ajouter(), Source_Generique_VEF::ajouter(), Terme_Boussinesq_VEFPreP1B_Face::ajouter(), Terme_Source_Acceleration_VEF_Face::ajouter(), Terme_Source_Qdm_VEF_Face::ajouter(), Op_Grad_VEF_P1B_Face::ajouter_aretes(), Tenseur_Reynolds_Externe_VDF_Face::ajouter_blocs(), Source_Transport_K_KEps_VDF_Elem::ajouter_blocs(), Op_Grad_P0_to_Face::ajouter_blocs(), Op_Grad_VDF_Face::ajouter_blocs(), Terme_Source_Canal_perio_VDF_Face::ajouter_blocs(), Force_Centrifuge_VDF_Face_Axi::ajouter_blocs(), Source_Generique_VDF_Face::ajouter_blocs(), Terme_Boussinesq_VDF_Face::ajouter_blocs(), Terme_Source_Acceleration_VDF_Face::ajouter_blocs(), Terme_Source_Coriolis_VDF_Face::ajouter_blocs(), Terme_Source_inc_th_VDF_Face::ajouter_blocs(), Terme_Source_inc_VDF_Face::ajouter_blocs(), Terme_Source_Qdm_VDF_Face::ajouter_blocs(), Diffusion_supplementaire_echelle_temp_turb_VDF::ajouter_blocs(), Iterateur_PolyMAC_Elem< _TYPE_ >::ajouter_bords(), Op_Diff_EF::ajouter_bords(), Op_Dift_EF_Q1::ajouter_bords(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Face::ajouter_cas_vectoriel(), Op_Conv_Amont_old_VEF_Face::ajouter_contribution(), Op_Conv_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution(), Op_Diff_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Face_Q1::ajouter_contribution(), Op_Diff_VEF_Face_Stab::ajouter_contribution(), Op_Conv_RT_VEF_Face::ajouter_contribution(), Iterateur_PolyMAC_Elem< _TYPE_ >::ajouter_contribution_bords(), Iterateur_PolyMAC_Elem< _TYPE_ >::ajouter_contribution_bords_vitesse(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution_elem(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face_Stab::ajouter_contribution_multi_scalaire(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution_som(), Op_Diff_EF::ajouter_contributions_bords(), Op_Dift_EF_Q1::ajouter_contributions_bords(), Operateur_Conv_sensibility_VEF::ajouter_conv_term(), Op_Grad_VEF_P1B_Face::ajouter_elem(), Source_Masse_Fluide_Dilatable_VEF::ajouter_eq_espece(), Iterateur_Source_Face< _TYPE_ >::ajouter_faces_bords(), Source_Fluide_Dilatable_VDF_Proto::ajouter_impl(), Source_Fluide_Dilatable_VEF_Proto::ajouter_impl(), Operateur_Conv_sensibility_VEF::ajouter_Lsensibility_state_Amont(), Operateur_Conv_sensibility_VEF::ajouter_Lstate_sensibility_Amont(), Source_Masse_Fluide_Dilatable_VDF::ajouter_projection(), Source_Masse_Fluide_Dilatable_VEF::ajouter_projection(), Op_Grad_VEF_P1B_Face::ajouter_som(), Op_Div_VEFP1B_Elem::ajouter_som(), Op_Diff_PolyMAC_Elem::ajouter_termes_croises(), Op_Conv_ALE_VEF::ajouterALE(), Tensors_Computation_VEF::antisym_loop_edges_general(), Tensors_Computation_VEF::antisym_loop_edges_periodiqueBC(), Solveur_Masse_EF::appliquer_impl(), Masse_VDF_Face::appliquer_impl(), Masse_VEF_P1NC::appliquer_impl(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_avec_inertie_impl(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_blocs_avec_inertie(), BilanQdmVEF::bilan_energie(), BilanQdmVEF::bilan_qdm(), Traitement_particulier_NS_chmoy_faceperio_VEF::calcul_chmoy_faceperio(), Champ_front_contact_VEF::calcul_coeff_amort(), Modele_Jones_Launder_VDF::Calcul_D(), Modele_Jones_Launder_Thermique_VDF::Calcul_D(), Modele_Jones_Launder_VDF::Calcul_D_BiK(), Champ_P1NC::calcul_duidxj_paroi(), Modele_Jones_Launder_VDF::Calcul_E(), Modele_Jones_Launder_Thermique_VDF::Calcul_E(), Traitement_particulier_NS_THI_VEF::calcul_Ec_spatial(), Modele_EASM_Baglietto_VEF::Calcul_F1(), Modele_EASM_Baglietto_VEF::Calcul_F1_BiK(), Modele_EASM_Baglietto_VEF::Calcul_Fmu(), Modele_EASM_Baglietto_VEF::Calcul_Fmu_BiK(), Champ_front_contact_VEF::calcul_grads_locaux(), Champ_P1NC::calcul_h_conv(), Traitement_particulier_NS_THI_VEF::calcul_moyenne(), Champ_front_recyclage::calcul_moyenne_imposee(), Champ_front_recyclage::calcul_moyenne_recyclee(), Traitement_particulier_NS_canal::calcul_reynolds_tau(), Traitement_particulier_NS_THI_VDF::calcul_skewness_ordre_2(), Traitement_particulier_NS_temperature_VEF::calcul_temperature(), Modele_Lam_Bremhorst_VEF::calcul_tenseur_face(), Modele_Shih_Zhu_Lumley_VEF::calcul_tenseur_face(), Calcul_Production_K_VEF::calcul_tenseur_face(), Traitement_particulier_NS_THI_VEF::calcul_vitesse_moyenne(), Champ_P1NC::calcul_y_plus(), Champ_Face_VDF::calcul_y_plus(), Champ_P1NC::calcul_y_plus_diphasique(), Champ_Face_VDF::calcul_y_plus_diphasique(), Op_Conv_ALE_VEF::calculateALEMeshVelocityGradientOnFaces(), Terme_Source_Canal_perio_VDF_Face::calculer_debit(), Terme_Source_Canal_perio_VEF_P1NC::calculer_debit(), Op_Diff_P1NC_barprim::calculer_divergence(), Op_Dift_VEF_P1NCP1B_Face::calculer_divergence_som(), Op_Diff_VEFP1NCP1B_Face::calculer_divergence_som(), Op_Conv_VDF_base::calculer_dt_local(), Op_Conv_VEF_base::calculer_dt_local(), Op_Conv_ALE_VEF::calculer_dt_stab(), Operateur_Conv_sensibility_VEF::calculer_dt_stab(), Op_Conv_PolyMAC_iterateur_base::calculer_dt_stab(), Op_Conv_VDF_base::calculer_dt_stab(), Op_Conv_VEF_base::calculer_dt_stab(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab_elem(), Iterateur_PolyMAC_Elem< _TYPE_ >::calculer_flux_bord(), Op_Grad_EF::calculer_flux_bords(), Op_Grad_VDF_Face::calculer_flux_bords(), Op_Diff_VEFP1NCP1B_Face::calculer_flux_bords_elem(), Op_Diff_VEFP1NCP1B_Face::calculer_flux_bords_som(), Flux_radiatif_VDF::calculer_flux_radiatif(), Flux_radiatif_VEF::calculer_flux_radiatif(), Modele_turbulence_hyd_LES_VDF::calculer_fonction_structure(), Modele_turbulence_hyd_LES_VEF::calculer_fonction_structure(), Modele_turbulence_hyd_LES_axi_VDF::calculer_fonction_structure(), EDO_Pression_th_VEF::calculer_grad(), Navier_Stokes_FT_Disc::calculer_gradient_indicatrice(), Op_Dift_VEF_P1NCP1B_Face::calculer_gradient_som(), Echange_contact_Correlation_VEF::calculer_h_solide(), Echange_contact_Correlation_VDF::calculer_h_solide(), ParoiVDF_TBLE_LRM::calculer_hyd(), Paroi_negligeable_VDF::calculer_hyd(), Paroi_negligeable_VEF::calculer_hyd(), Paroi_std_hyd_VDF_diphasique::calculer_hyd(), Paroi_2couches_VDF::calculer_hyd(), Paroi_loi_Ciofalo_hyd_VDF::calculer_hyd(), Paroi_loi_WW_hyd_VDF::calculer_hyd(), Paroi_loi_WW_hyd_VEF::calculer_hyd(), Paroi_std_hyd_VDF::calculer_hyd(), Paroi_UTAU_IMP_VDF::calculer_hyd(), LoiParoiHybride::calculer_hyd(), ParoiVDF_TBLE::calculer_hyd(), ParoiVEF_TBLE::calculer_hyd(), Paroi_std_hyd_VDF::calculer_hyd_BiK(), Paroi_UTAU_IMP_VDF::calculer_hyd_BiK(), ParoiVDF_TBLE::calculer_hyd_BiK(), ParoiVDF_TBLE_LRM::calculer_hyd_BiK(), ParoiVEF_TBLE::calculer_hyd_BiK(), LoiParoiHybride::calculer_hyd_BiK(), Paroi_std_hyd_VDF::calculer_moyennes_parois(), Champ_front_xyz_debit::calculer_normales_et_integrale(), Operateur_base::calculer_pour_post(), Op_Conv_PolyMAC_iterateur_base::calculer_pour_post(), Op_Conv_VDF_base::calculer_pour_post(), Op_Conv_VEF_base::calculer_pour_post(), Source_Transport_Fluctuation_Temperature_VDF_Elem::calculer_Prod_uteta_T(), Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::calculer_Prod_uteta_T(), Source_Transport_Fluctuation_Temperature_W_VDF_Elem::calculer_Prod_uteta_T(), Echange_contact_Correlation_VDF::calculer_Q(), Echange_contact_Correlation_VEF::calculer_Q(), Paroi_std_scal_hyd_EF::calculer_scal(), Loi_Paroi_Nu_Impose_VDF::calculer_scal(), Paroi_loi_WW_scal_VDF::calculer_scal(), Paroi_ODVM_scal_VDF::calculer_scal(), Paroi_std_scal_hyd_VDF::calculer_scal(), Paroi_TBLE_scal_VDF::calculer_scal(), Loi_Paroi_Nu_Impose_VEF::calculer_scal(), Paroi_std_scal_hyd_VEF::calculer_scal(), ParoiVEF_TBLE_scal::calculer_scal(), Neumann_paroi_rayo_semi_transp_VDF::calculer_temperature_bord(), Neumann_paroi_rayo_semi_transp_VEF::calculer_temperature_bord(), Calcul_Production_K_VEF::calculer_terme_production_K(), Calcul_Production_K_VEF::calculer_terme_production_K_BiK(), Calcul_Production_K_VEF::calculer_terme_production_K_EASM(), Echange_contact_ODVM_VDF::calculer_Teta_equiv(), Echange_contact_rayo_semi_transp_VDF::calculer_Teta_equiv(), Echange_contact_VDF::calculer_Teta_equiv(), Frontiere_Ouverte_Rayo_transp::calculer_Teta_i(), Frontiere_Ouverte_temperature_imposee_Rayo_transp::calculer_Teta_i(), Echange_externe_impose_rayo_transp::calculer_Teta_i(), Temperature_imposee_paroi_rayo_transp::calculer_Teta_i(), Paroi_flux_impose_Rayo_transp::calculer_Teta_i_VDF(), Paroi_flux_impose_Rayo_transp::calculer_Teta_i_VEF(), Echange_contact_VDF::calculer_Teta_paroi(), Echange_contact_Rayo_transp_VDF::calculer_Teta_paroi(), Echange_contact_rayo_semi_transp_VDF::calculer_Teta_paroi(), Calcul_Production_K_VDF::calculer_u_conc(), Calcul_Production_K_VDF::calculer_u_teta(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_W_VDF_Elem::calculer_u_teta_W(), Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::calculer_u_teta_W(), Source_Transport_Fluctuation_Temperature_W_VDF_Elem::calculer_u_teta_W(), Modele_turbulence_hyd_LES_VEF::calculer_viscosite_turbulente(), Domaine_ALE::calculer_vitesse(), Echange_contact_Rayo_transp_VDF::completer(), Paroi_flux_impose_Rayo_transp::completer(), Flux_radiatif_base::completer(), Neumann_paroi_rayo_semi_transp_VDF::completer(), Neumann_paroi_rayo_semi_transp_VEF::completer(), Champ_front_calc_interne::completer(), Echange_contact_Correlation_VDF::completer(), Echange_interne_impose::completer(), Echange_contact_Correlation_VEF::completer(), Terme_Source_Canal_perio::compute_heat_flux(), Paroi_std_hyd_VDF::compute_law_komega(), Paroi_scal_hyd_base_EF::compute_nusselt(), Paroi_scal_hyd_base_VDF::compute_nusselt(), Paroi_scal_hyd_base_VEF::compute_nusselt(), Calcul_Production_K_VEF::compute_utheta_nbConsti_gt_1_nbCompo_eq_0(), Calcul_Production_K_VEF::compute_utheta_nbConsti_gt_1_nbCompo_eq_1(), Calcul_Production_K_VEF::compute_utheta_nbConsti_gt_1_nbCompo_gt_1(), Calcul_Production_K_VEF::compute_utheta_nbConsti_le_1_nbCompo_eq_0(), Calcul_Production_K_VEF::compute_utheta_nbConsti_le_1_nbCompo_eq_1(), Calcul_Production_K_VEF::compute_utheta_nbConsti_le_1_nbCompo_gt_1(), Op_Conv_Amont_old_VEF_Face::contribue_au_second_membre(), Op_Conv_VEF_Face::contribue_au_second_membre(), Op_Diff_VEF_Anisotrope_Face::contribue_au_second_membre(), Op_Diff_VEF_Face::contribue_au_second_membre(), Op_Diff_VEF_Face_Q1::contribue_au_second_membre(), Op_Dift_VEF_Face_Q1::contribuer_a_avec(), Op_Grad_PolyMAC_Face::contribuer_a_avec(), Op_Diff_DG_Elem::contribuer_au_second_membre(), Op_Dift_VEF_Face::contribuer_au_second_membre(), Iterateur_PolyMAC_Elem< _TYPE_ >::contribuer_au_second_membre_bords(), Op_Diff_PolyMAC_Elem::contribuer_termes_croises(), Navier_Stokes_FT_Disc::correct_at_exit_bad_gradient(), Source_WC_Chaleur::correct_grad_boundary(), Op_Diff_VEFP1NCP1B_Face::corriger_Cl_test(), Op_Diff_VEFP1NCP1B_Face::corriger_div_pour_Cl(), Op_Dift_VEF_P1NCP1B_Face::corriger_div_pour_Cl(), Domaine_VDF::creer_elements_fictifs(), Op_EF_base::dimensionner(), Op_PolyMAC_Elem::dimensionner(), Op_VDF_Face::dimensionner(), Domaine_Poly_base::dist_norm_bord(), Domaine_VDF::dist_norm_bord(), Paroi_scal_hyd_base_EF::equivalent_distance_name(), Paroi_scal_hyd_base_VEF::equivalent_distance_name(), Paroi_scal_hyd_base_VDF::equivalent_distance_name(), Champ_val_tot_sur_vol_VEF::eval_contrib_loc(), Flux_radiatif_VDF::evaluer_cl_rayonnement(), Flux_radiatif_VEF::evaluer_cl_rayonnement(), Source_Masse_Fluide_Dilatable_base::fill_val_flux_tab(), Champ_P1NC_implementation::filtrer_resu(), Neumann::flux_impose(), Paroi_hyd_base_EF::get_champ(), Turbulence_paroi_base::get_champ(), Champ_front_recyclage::get_coord_faces(), Domaine_Cl_PolyMAC::imposer_cond_lim(), Domaine_Cl_VDF::imposer_cond_lim(), Domaine_Cl_VEF::imposer_cond_lim(), Op_Grad_VEF_P1B_Face::impr(), Op_EF_base::impr(), Op_VEF_Face::impr(), Op_Div_EF::impr(), Op_Grad_EF::impr(), Iterateur_PolyMAC_Elem< _TYPE_ >::impr(), Op_Conv_PolyMAC_base::impr(), Op_Diff_PolyMAC_Gen_base::impr(), Op_Div_PolyMAC::impr(), Op_Grad_VDF_Face::impr(), Op_Div_VEFP1B_Elem::impr(), Loi_Paroi_Nu_Impose_VDF::imprimer_nusselt(), Loi_Paroi_Nu_Impose_VEF::imprimer_nusselt(), Paroi_scal_hyd_base_EF::imprimer_nusselt(), Paroi_scal_hyd_base_VDF::imprimer_nusselt(), Paroi_scal_hyd_base_VEF::imprimer_nusselt(), Turbulence_paroi_scal_base::imprimer_nusselt_mean_only(), Paroi_std_hyd_EF::imprimer_ustar(), Paroi_std_hyd_VDF::imprimer_ustar(), Paroi_std_hyd_VEF::imprimer_ustar(), Paroi_2couches_VDF::imprimer_ustar(), Turbulence_paroi_base::imprimer_ustar_mean_only(), Echange_contact_Correlation_VEF::init(), Sonde::init_bords(), Traitement_particulier_NS_chmoy_faceperio_VEF::init_calcul_stats(), ParoiVDF_TBLE::init_lois_paroi(), ParoiVDF_TBLE_LRM::init_lois_paroi(), Paroi_ODVM_scal_VDF::init_lois_paroi(), Paroi_TBLE_scal_VDF::init_lois_paroi(), ParoiVEF_TBLE::init_lois_paroi(), ParoiVEF_TBLE_scal::init_lois_paroi(), Paroi_scal_hyd_base_EF::init_lois_paroi(), Paroi_scal_hyd_base_VDF::init_lois_paroi(), Paroi_negligeable_VEF::init_lois_paroi(), Paroi_scal_hyd_base_VEF::init_lois_paroi(), Paroi_TBLE_QDM::init_lois_paroi(), Paroi_TBLE_QDM_Scal::init_lois_paroi(), Echange_contact_PolyMAC::initialiser(), Echange_contact_VDF::initialiser(), Sortie_libre_Gradient_Pression_libre_VEF::initialiser(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::initialiser(), Domaine_Cl_VEF::initialiser(), Boundary_field_keps_from_ud::initialiser(), Champ_front_recyclage::initialiser(), Champ_front_tangentiel_VEF::initialiser(), Champ_front_recyclage::initialiser_moyenne_imposee(), Domaine_ALE::laplacien(), Champ_front_recyclage::lire_fichier_format2(), Champ_front_recyclage::lire_fichier_format3(), AssembleurPVDF_PF::liste_faces_periodiques(), Assembleur_P_VDF::liste_faces_periodiques(), Domaine_VF::marquer_faces_double_contrib(), T_paroi_Champ_P0_VDF::me_calculer(), T_paroi_Champ_P1NC::me_calculer(), Source_Masse_Fluide_Dilatable_base::mettre_a_jour(), Champ_front_recyclage::mettre_a_jour(), Champ_front_pression_from_u::mettre_a_jour(), Champ_front_synt::mettre_a_jour(), Champ_front_fonc_gradient_VEF::mettre_a_jour(), Sortie_libre_Gradient_Pression_libre_VEF::mettre_a_jour(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::mettre_a_jour(), Boundary_field_inward::mettre_a_jour(), Echange_interne_impose::mettre_a_jour(), Champ_front_fonc_gradient_VDF::mettre_a_jour(), PlaqThVDF::mettre_a_jour(), Sortie_libre_Gradient_Pression_impose::mettre_a_jour(), Sortie_libre_Pression_imposee_Orlansky::mettre_a_jour(), Op_Diff_VEF_Face_Stab::modifie_pour_Cl(), Op_Grad_VEF_P1B_Face::modifier_grad_pour_Cl(), Eq_rayo_semi_transp_VDF::modifier_matrice(), Eq_rayo_semi_transp_VEF::modifier_matrice(), Op_VEF_Face::modifier_matrice_pour_periodique_apres_contribuer(), Domaine_EF::modifier_pour_Cl(), Domaine_Poly_base::modifier_pour_Cl(), Domaine_VF::modifier_pour_Cl(), Domaine_PolyMAC::modifier_pour_Cl(), Domaine_VEF::modifier_pour_Cl(), Domaine_VDF::modifier_pour_Cl(), Op_VDF_Face::modifier_pour_Cl(), Op_VEF_Face::modifier_pour_Cl(), Op_Diff_K_Eps_VDF_base::modifier_pour_Cl(), Op_Diff_K_Omega_VDF_base::modifier_pour_Cl(), Assembleur_P_EF::modifier_secmem(), Assembleur_P_PolyMAC::modifier_secmem(), Assembleur_P_VEF::modifier_secmem(), Assembleur_P_VEFPreP1B::modifier_secmem(), AssembleurPVDF_PF::modifier_secmem_pression_imposee(), Assembleur_P_VDF::modifier_secmem_pression_imposee(), AssembleurPVDF_PF::modifier_secmem_vitesse_imposee(), Assembleur_P_VDF::modifier_secmem_vitesse_imposee(), Domaine_Cl_VDF::nb_faces_sortie_libre(), Domaine_Cl_VEF::nb_faces_sortie_libre(), num_face(), num_local_face(), Paroi_std_hyd_VDF::preparer_calcul_hyd(), Cond_Lim_Rayo::preparer_surface(), AssembleurPVDF_PF::remplir(), Assembleur_P_VDF::remplir(), Champ_front_contact_VEF::remplir_connect_bords(), Champ_front_contact_VEF::remplir_elems_voisin_bord(), Op_Conv_VEF_Face::remplir_fluent(), Operateur_Conv_sensibility_VEF::remplir_fluent(), Domaine_Cl_VEF::remplir_type_elem_Cl(), Iterateur_Source_VEF_Face< _TYPE_ >::remplir_volumes_cl_dirichlet(), Domaine_Cl_VEF::remplir_volumes_entrelaces_Cl(), Paroi_TBLE_QDM::reprendre(), Paroi_TBLE_QDM_Scal::reprendre(), EDO_Pression_th_VDF_Gaz_Parfait::resoudre(), Paroi_TBLE_QDM::sauvegarder(), Paroi_TBLE_QDM_Scal::sauvegarder(), Champ_Face_PolyMAC::trace(), Champ_Face_PolyMAC_P0::trace(), Champ_Face_PolyMAC_P0P1NC::trace(), Champ_Face_VDF_implementation::trace(), Champ_P1iP1B_implementation::trace(), Champ_Elem_PolyMAC::trace(), Echange_contact_Correlation_VDF::trier_coord(), Echange_contact_PolyMAC::update_coeffs(), Echange_contact_PolyMAC::update_delta(), Echange_interne_impose::update_inv_lambda(), Champ_Face_VDF::verifie_valeurs_cl(), Champ_P1NC::verifie_valeurs_cl(), Champ_Q1NC::verifie_valeurs_cl(), Echange_contact_VDF::verifier_correspondance(), and Assembleur_P_VEFPreP1B::verifier_dirichlet().
nb_faces_tot()
int Front_VF::nb_faces_tot () const inline
References Frontiere_dis_base::frontiere(), Frontiere_32_64< _SIZE_ >::get_faces_virt(), Frontiere_32_64< _SIZE_ >::nb_faces(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by Operateur_Conv_sensibility_VEF::add_diffusion_scalar_term(), Operateur_Conv_sensibility_VEF::add_diffusion_term(), Op_Conv_EF_VEF_P1NC::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Dift_VEF_Face_Q1::ajouter(), Op_Div_VEFP1B_Elem::ajouter(), Op_Grad_EF::ajouter_bord(), Op_Dift_EF_Q1::ajouter_bords(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Face::ajouter_cas_scalaire(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution_som(), Operateur_Conv_sensibility_VEF::ajouter_conv_term(), Operateur_Conv_sensibility_VEF::ajouter_Lsensibility_state_Amont(), Operateur_Conv_sensibility_VEF::ajouter_Lstate_sensibility_Amont(), Op_Div_VEFP1B_Elem::ajouter_som(), Op_Conv_ALE_VEF::ajouterALE(), Champ_Q1_EF::calcul_y_plus(), Champ_front_xyz_debit::calculer_champ_vitesse(), Op_Conv_Muscl_New_VEF_Face::calculer_dt_stab(), Op_Diff_VEFP1NCP1B_Face::calculer_gradient_som(), Paroi_std_hyd_VEF::calculer_hyd(), Paroi_std_hyd_VEF_diphasique::calculer_hyd(), Paroi_loi_WW_hyd_EF::calculer_hyd(), Paroi_std_hyd_EF::calculer_hyd(), Paroi_std_hyd_VEF::calculer_hyd_BiK(), Op_Diff_VEF_Face_Stab::calculer_max(), Op_Diff_VEF_Face_Stab::calculer_min(), Champ_front_xyz_debit::calculer_normales_et_integrale(), Paroi_loi_WW_scal_VEF::calculer_scal(), Paroi_scal_analytique_VEF::calculer_scal(), Sortie_libre_Gradient_Pression_impose_VEFPreP1B::calculer_trace_pression(), Op_Diff_VEF_Face_Stab::completer(), Op_Dift_Stab_VEF_Face::completer(), Domaine_VEF::construire_renum_arete_perio(), Source_PDF_EF::filtre_CLD(), Champ_P1NC_implementation::filtrer_L2(), Champ_P1NC_implementation::filtrer_resu(), Neumann::flux_impose(), Champ_Generique_Tparoi_VEF::get_champ(), Domaine_Cl_EF::imposer_cond_lim(), Domaine_Cl_VEF::imposer_cond_lim(), Domaine_Cl_EF::imposer_symetrie_partiellement(), Champ_Inc_P0_base::init_fcl(), Champ_Face_base::init_fcl(), ParoiVEF_TBLE_scal::init_lois_paroi(), Champ_front_softanalytique::initialiser(), Champ_front_xyz_debit::initialiser_coefficient(), Op_Diff_VEFP1NCP1B_Face::isFaceOfSymetry(), Op_Diff_VEFP1NCP1B_Face::liste_face(), Domaine_VF::marquer_faces_double_contrib(), Champ_Front_Fonction::mettre_a_jour(), Domaine_ALE::mettre_a_jour(), Domaine_EF::modifier_pour_Cl(), Domaine_Poly_base::modifier_pour_Cl(), Domaine_VF::modifier_pour_Cl(), Domaine_PolyMAC::modifier_pour_Cl(), Domaine_VEF::modifier_pour_Cl(), Op_EF_base::modifier_pour_Cl(), Op_VEF_Face::modifier_pour_Cl(), Assembleur_P_VEFPreP1B::modifier_secmem_elem(), Assembleur_P_VEFPreP1B::modifier_secmem_som(), num_face(), Assembleur_P_VEF::remplir(), Op_Dift_EF_Q1::remplir_marqueur_elem_CL_paroi(), Domaine_Cl_EF::remplir_type_elem_Cl(), Op_Diff_VEFP1NCP1B_Face::test(), Champ_front_debit_massique::update_coeff(), Neumann_sortie_libre::val_ext(), Dirichlet::val_imp(), and Champ_Inc_base::valeur_aux_bords().
num_premiere_face()
int Front_VF::num_premiere_face () const inline
References Frontiere_dis_base::frontiere(), and Frontiere_32_64< _SIZE_ >::num_premiere_face().
Referenced by Operateur_Conv_sensibility_VEF::add_diffusion_scalar_term(), Operateur_Conv_sensibility_VEF::add_diffusion_term(), Op_Grad_PolyMAC_Face::ajouter(), Op_Conv_Amont_old_VEF_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Centre_EF_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_EF_VEF_P1NC::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Conv_Vort_VEF_Face::ajouter(), Op_Diff_VEF_Face_Q1::ajouter(), Op_Dift_VEF_Face_Q1::ajouter(), Source_Reaction_Particules_VDF::ajouter(), Source_Reaction_Particules_VEF::ajouter(), SourceFiltree_FT_disc_VEF_P1NC::ajouter(), Source_Gravite_PF_VDF::ajouter(), Source_Transport_Flux_Chaleur_Turbulente_VDF_Face::ajouter(), Source_Robin::ajouter(), Source_Robin_Scalaire::ajouter(), Source_Generique_Face_PolyMAC::ajouter(), Terme_Source_Qdm_Face_PolyMAC::ajouter(), Source_Generique_VEF::ajouter(), Terme_Source_Acceleration_VEF_Face::ajouter(), Op_Grad_VEF_P1B_Face::ajouter_aretes(), Tenseur_Reynolds_Externe_VDF_Face::ajouter_blocs(), Source_Transport_K_KEps_VDF_Elem::ajouter_blocs(), Op_Grad_P0_to_Face::ajouter_blocs(), Op_Grad_VDF_Face::ajouter_blocs(), Terme_Source_Canal_perio_VDF_Face::ajouter_blocs(), Force_Centrifuge_VDF_Face_Axi::ajouter_blocs(), Source_Generique_VDF_Face::ajouter_blocs(), Terme_Boussinesq_VDF_Face::ajouter_blocs(), Terme_Source_Acceleration_VDF_Face::ajouter_blocs(), Terme_Source_Coriolis_VDF_Face::ajouter_blocs(), Terme_Source_inc_th_VDF_Face::ajouter_blocs(), Terme_Source_inc_VDF_Face::ajouter_blocs(), Terme_Source_Qdm_VDF_Face::ajouter_blocs(), Diffusion_supplementaire_echelle_temp_turb_VDF::ajouter_blocs(), Iterateur_PolyMAC_Elem< _TYPE_ >::ajouter_bords(), Op_Diff_EF::ajouter_bords(), Op_Dift_EF_Q1::ajouter_bords(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Face::ajouter_cas_vectoriel(), Op_Conv_Amont_old_VEF_Face::ajouter_contribution(), Op_Conv_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution(), Op_Diff_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Face_Q1::ajouter_contribution(), Op_Diff_VEF_Face_Stab::ajouter_contribution(), Op_Conv_RT_VEF_Face::ajouter_contribution(), Iterateur_PolyMAC_Elem< _TYPE_ >::ajouter_contribution_bords(), Iterateur_PolyMAC_Elem< _TYPE_ >::ajouter_contribution_bords_vitesse(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution_elem(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face_Stab::ajouter_contribution_multi_scalaire(), Op_Diff_EF::ajouter_contributions_bords(), Op_Dift_EF_Q1::ajouter_contributions_bords(), Operateur_Conv_sensibility_VEF::ajouter_conv_term(), Op_Grad_VEF_P1B_Face::ajouter_elem(), Source_Masse_Fluide_Dilatable_VEF::ajouter_eq_espece(), Iterateur_Source_Face< _TYPE_ >::ajouter_faces_bords(), Source_Fluide_Dilatable_VDF_Proto::ajouter_impl(), Source_Fluide_Dilatable_VEF_Proto::ajouter_impl(), Operateur_Conv_sensibility_VEF::ajouter_Lsensibility_state_Amont(), Operateur_Conv_sensibility_VEF::ajouter_Lstate_sensibility_Amont(), Source_Masse_Fluide_Dilatable_VDF::ajouter_projection(), Source_Masse_Fluide_Dilatable_VEF::ajouter_projection(), Op_Grad_VEF_P1B_Face::ajouter_som(), Op_Conv_ALE_VEF::ajouterALE(), Tensors_Computation_VEF::antisym_loop_edges_general(), Tensors_Computation_VEF::antisym_loop_edges_periodiqueBC(), Solveur_Masse_EF::appliquer_impl(), Masse_VDF_Face::appliquer_impl(), Masse_VEF_P1NC::appliquer_impl(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_avec_inertie_impl(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_blocs_avec_inertie(), BilanQdmVEF::bilan_energie(), BilanQdmVEF::bilan_qdm(), Traitement_particulier_NS_chmoy_faceperio_VEF::calcul_chmoy_faceperio(), Champ_front_contact_VEF::calcul_coeff_amort(), Modele_Jones_Launder_VDF::Calcul_D(), Modele_Jones_Launder_Thermique_VDF::Calcul_D(), Modele_Jones_Launder_VDF::Calcul_D_BiK(), Champ_P1NC::calcul_duidxj_paroi(), Modele_Jones_Launder_VDF::Calcul_E(), Modele_Jones_Launder_Thermique_VDF::Calcul_E(), Traitement_particulier_NS_THI_VEF::calcul_Ec_spatial(), Modele_EASM_Baglietto_VEF::Calcul_F1(), Modele_EASM_Baglietto_VEF::Calcul_F1_BiK(), Modele_EASM_Baglietto_VEF::Calcul_Fmu(), Modele_EASM_Baglietto_VEF::Calcul_Fmu_BiK(), Champ_front_contact_VEF::calcul_grads_locaux(), Champ_P1NC::calcul_h_conv(), Traitement_particulier_NS_THI_VEF::calcul_moyenne(), Champ_front_recyclage::calcul_moyenne_imposee(), Traitement_particulier_NS_canal::calcul_reynolds_tau(), Traitement_particulier_NS_THI_VDF::calcul_skewness_ordre_2(), Traitement_particulier_NS_temperature_VEF::calcul_temperature(), Modele_Lam_Bremhorst_VEF::calcul_tenseur_face(), Modele_Shih_Zhu_Lumley_VEF::calcul_tenseur_face(), Calcul_Production_K_VEF::calcul_tenseur_face(), Traitement_particulier_NS_THI_VEF::calcul_vitesse_moyenne(), Champ_P1NC::calcul_y_plus(), Champ_Face_VDF::calcul_y_plus(), Champ_P1NC::calcul_y_plus_diphasique(), Champ_Face_VDF::calcul_y_plus_diphasique(), Op_Conv_ALE_VEF::calculateALEMeshVelocityGradientOnFaces(), Terme_Source_Canal_perio_VDF_Face::calculer_debit(), Terme_Source_Canal_perio_VEF_P1NC::calculer_debit(), Op_Diff_P1NC_barprim::calculer_divergence(), Op_Dift_VEF_P1NCP1B_Face::calculer_divergence_som(), Op_Conv_VDF_base::calculer_dt_local(), Op_Conv_VEF_base::calculer_dt_local(), Op_Conv_ALE_VEF::calculer_dt_stab(), Operateur_Conv_sensibility_VEF::calculer_dt_stab(), Op_Conv_PolyMAC_iterateur_base::calculer_dt_stab(), Op_Conv_VDF_base::calculer_dt_stab(), Op_Conv_VEF_base::calculer_dt_stab(), Iterateur_PolyMAC_Elem< _TYPE_ >::calculer_flux_bord(), Op_Grad_EF::calculer_flux_bords(), Op_Grad_VDF_Face::calculer_flux_bords(), Flux_radiatif_VDF::calculer_flux_radiatif(), Flux_radiatif_VEF::calculer_flux_radiatif(), Modele_turbulence_hyd_LES_VDF::calculer_fonction_structure(), Modele_turbulence_hyd_LES_VEF::calculer_fonction_structure(), Modele_turbulence_hyd_LES_axi_VDF::calculer_fonction_structure(), EDO_Pression_th_VEF::calculer_grad(), Navier_Stokes_FT_Disc::calculer_gradient_indicatrice(), Op_Dift_VEF_P1NCP1B_Face::calculer_gradient_som(), Echange_contact_Correlation_VEF::calculer_h_solide(), Echange_contact_Correlation_VDF::calculer_h_solide(), ParoiVDF_TBLE_LRM::calculer_hyd(), Paroi_negligeable_VDF::calculer_hyd(), Paroi_negligeable_VEF::calculer_hyd(), Paroi_std_hyd_VDF_diphasique::calculer_hyd(), Paroi_2couches_VDF::calculer_hyd(), Paroi_loi_Ciofalo_hyd_VDF::calculer_hyd(), Paroi_loi_WW_hyd_VDF::calculer_hyd(), Paroi_loi_WW_hyd_VEF::calculer_hyd(), Paroi_std_hyd_VDF::calculer_hyd(), Paroi_UTAU_IMP_VDF::calculer_hyd(), LoiParoiHybride::calculer_hyd(), ParoiVDF_TBLE::calculer_hyd(), Paroi_std_hyd_VDF::calculer_hyd_BiK(), Paroi_UTAU_IMP_VDF::calculer_hyd_BiK(), ParoiVDF_TBLE::calculer_hyd_BiK(), ParoiVDF_TBLE_LRM::calculer_hyd_BiK(), LoiParoiHybride::calculer_hyd_BiK(), Paroi_std_hyd_VDF::calculer_moyennes_parois(), Operateur_base::calculer_pour_post(), Op_Conv_PolyMAC_iterateur_base::calculer_pour_post(), Op_Conv_VDF_base::calculer_pour_post(), Op_Conv_VEF_base::calculer_pour_post(), Source_Transport_Fluctuation_Temperature_VDF_Elem::calculer_Prod_uteta_T(), Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::calculer_Prod_uteta_T(), Source_Transport_Fluctuation_Temperature_W_VDF_Elem::calculer_Prod_uteta_T(), Echange_contact_Correlation_VDF::calculer_Q(), Echange_contact_Correlation_VEF::calculer_Q(), Loi_Paroi_Nu_Impose_VDF::calculer_scal(), Paroi_loi_WW_scal_VDF::calculer_scal(), Paroi_ODVM_scal_VDF::calculer_scal(), Paroi_std_scal_hyd_VDF::calculer_scal(), Paroi_TBLE_scal_VDF::calculer_scal(), Neumann_paroi_rayo_semi_transp_VDF::calculer_temperature_bord(), Neumann_paroi_rayo_semi_transp_VEF::calculer_temperature_bord(), Calcul_Production_K_VEF::calculer_terme_production_K(), Calcul_Production_K_VEF::calculer_terme_production_K_BiK(), Calcul_Production_K_VEF::calculer_terme_production_K_EASM(), Echange_contact_ODVM_VDF::calculer_Teta_equiv(), Paroi_flux_impose_Rayo_transp::calculer_Teta_i_VDF(), Paroi_flux_impose_Rayo_transp::calculer_Teta_i_VEF(), Echange_contact_VDF::calculer_Teta_paroi(), Echange_contact_Rayo_transp_VDF::calculer_Teta_paroi(), Echange_contact_rayo_semi_transp_VDF::calculer_Teta_paroi(), Calcul_Production_K_VDF::calculer_u_conc(), Calcul_Production_K_VDF::calculer_u_teta(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_W_VDF_Elem::calculer_u_teta_W(), Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::calculer_u_teta_W(), Source_Transport_Fluctuation_Temperature_W_VDF_Elem::calculer_u_teta_W(), Modele_turbulence_hyd_LES_VEF::calculer_viscosite_turbulente(), Domaine_ALE::calculer_vitesse(), Echange_contact_Rayo_transp_VDF::completer(), Paroi_flux_impose_Rayo_transp::completer(), Neumann_paroi_rayo_semi_transp_VDF::completer(), Echange_contact_Correlation_VEF::completer(), Terme_Source_Canal_perio::compute_heat_flux(), Paroi_std_hyd_VDF::compute_law_komega(), Paroi_scal_hyd_base_EF::compute_nusselt(), Paroi_scal_hyd_base_VDF::compute_nusselt(), Paroi_scal_hyd_base_VEF::compute_nusselt(), Calcul_Production_K_VEF::compute_utheta_nbConsti_gt_1_nbCompo_eq_0(), Calcul_Production_K_VEF::compute_utheta_nbConsti_gt_1_nbCompo_eq_1(), Calcul_Production_K_VEF::compute_utheta_nbConsti_gt_1_nbCompo_gt_1(), Calcul_Production_K_VEF::compute_utheta_nbConsti_le_1_nbCompo_eq_0(), Calcul_Production_K_VEF::compute_utheta_nbConsti_le_1_nbCompo_eq_1(), Calcul_Production_K_VEF::compute_utheta_nbConsti_le_1_nbCompo_gt_1(), Op_Conv_Amont_old_VEF_Face::contribue_au_second_membre(), Op_Conv_VEF_Face::contribue_au_second_membre(), Op_Diff_VEF_Anisotrope_Face::contribue_au_second_membre(), Op_Diff_VEF_Face::contribue_au_second_membre(), Op_Diff_VEF_Face_Q1::contribue_au_second_membre(), Op_Dift_VEF_Face_Q1::contribuer_a_avec(), Op_Grad_PolyMAC_Face::contribuer_a_avec(), Op_Dift_VEF_Face::contribuer_au_second_membre(), Iterateur_PolyMAC_Elem< _TYPE_ >::contribuer_au_second_membre_bords(), Navier_Stokes_FT_Disc::correct_at_exit_bad_gradient(), Source_WC_Chaleur::correct_grad_boundary(), Op_Dift_VEF_P1NCP1B_Face::corriger_div_pour_Cl(), Domaine_VDF::creer_elements_fictifs(), Op_EF_base::dimensionner(), Op_PolyMAC_Elem::dimensionner(), Op_VDF_Face::dimensionner(), Domaine_Poly_base::dist_norm_bord(), Domaine_VDF::dist_norm_bord(), Flux_radiatif_VDF::evaluer_cl_rayonnement(), Flux_radiatif_VEF::evaluer_cl_rayonnement(), Source_Masse_Fluide_Dilatable_base::fill_val_flux_tab(), Paroi_Rayo_transp::flux_impose(), Neumann_paroi_rayo_semi_transp_VDF::flux_impose(), Paroi_hyd_base_EF::get_champ(), Turbulence_paroi_base::get_champ(), Champ_front_recyclage::get_coord_faces(), Convection_Diffusion_Temperature_FT_Disc::get_flux_and_Twall(), Convection_Diffusion_Temperature_FT_Disc::get_flux_to_face(), Triple_Line_Model_FT_Disc::get_theta_app(), Domaine_Cl_PolyMAC::imposer_cond_lim(), Domaine_Cl_VDF::imposer_cond_lim(), Domaine_Cl_VEF::imposer_cond_lim(), Op_Grad_VEF_P1B_Face::impr(), Op_EF_base::impr(), Op_VEF_Face::impr(), Op_Div_EF::impr(), Op_Grad_EF::impr(), Iterateur_PolyMAC_Elem< _TYPE_ >::impr(), Op_Conv_PolyMAC_base::impr(), Op_Diff_PolyMAC_Gen_base::impr(), Op_Div_PolyMAC::impr(), Op_Grad_VDF_Face::impr(), Op_Div_VEFP1B_Elem::impr(), Loi_Paroi_Nu_Impose_VDF::imprimer_nusselt(), Loi_Paroi_Nu_Impose_VEF::imprimer_nusselt(), Paroi_scal_hyd_base_EF::imprimer_nusselt(), Paroi_scal_hyd_base_VDF::imprimer_nusselt(), Paroi_scal_hyd_base_VEF::imprimer_nusselt(), Turbulence_paroi_scal_base::imprimer_nusselt_mean_only(), Paroi_std_hyd_EF::imprimer_ustar(), Paroi_std_hyd_VDF::imprimer_ustar(), Paroi_std_hyd_VEF::imprimer_ustar(), Paroi_2couches_VDF::imprimer_ustar(), Turbulence_paroi_base::imprimer_ustar_mean_only(), Echange_contact_Correlation_VEF::init(), Sonde::init_bords(), Traitement_particulier_NS_chmoy_faceperio_VEF::init_calcul_stats(), ParoiVDF_TBLE::init_lois_paroi(), ParoiVDF_TBLE_LRM::init_lois_paroi(), Paroi_ODVM_scal_VDF::init_lois_paroi(), Paroi_TBLE_scal_VDF::init_lois_paroi(), Paroi_negligeable_VEF::init_lois_paroi(), Paroi_TBLE_QDM::init_lois_paroi(), Sortie_libre_Gradient_Pression_libre_VEF::initialiser(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::initialiser(), Domaine_Cl_VEF::initialiser(), Champ_front_tangentiel_VEF::initialiser(), Champ_front_recyclage::initialiser_moyenne_imposee(), Domaine_ALE::laplacien(), Champ_front_recyclage::lire_fichier_format2(), Champ_front_recyclage::lire_fichier_format3(), AssembleurPVDF_PF::liste_faces_periodiques(), Assembleur_P_VDF::liste_faces_periodiques(), Domaine_VF::marquer_faces_double_contrib(), T_paroi_Champ_P0_VDF::me_calculer(), T_paroi_Champ_P1NC::me_calculer(), Source_Masse_Fluide_Dilatable_base::mettre_a_jour(), Echange_contact_rayo_semi_transp_VDF::mettre_a_jour(), Champ_front_pression_from_u::mettre_a_jour(), Champ_front_debit_QC::mettre_a_jour(), Champ_front_debit_QC_fonc_t::mettre_a_jour(), Champ_front_fonc_gradient_VEF::mettre_a_jour(), Sortie_libre_Gradient_Pression_libre_VEF::mettre_a_jour(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::mettre_a_jour(), Boundary_field_inward::mettre_a_jour(), Echange_contact_Rayo_transp_VDF::mettre_a_jour(), Champ_front_fonc_gradient_VDF::mettre_a_jour(), PlaqThVDF::mettre_a_jour(), Sortie_libre_Gradient_Pression_impose::mettre_a_jour(), Sortie_libre_Pression_imposee_Orlansky::mettre_a_jour(), Echange_contact_Correlation_VEF::mettre_a_jour(), Sonde::mettre_a_jour_bords(), Op_Grad_VEF_P1B_Face::modifier_grad_pour_Cl(), Eq_rayo_semi_transp_VDF::modifier_matrice(), Eq_rayo_semi_transp_VEF::modifier_matrice(), Op_VEF_Face::modifier_matrice_pour_periodique_apres_contribuer(), Domaine_EF::modifier_pour_Cl(), Domaine_Poly_base::modifier_pour_Cl(), Domaine_VF::modifier_pour_Cl(), Domaine_PolyMAC::modifier_pour_Cl(), Domaine_VEF::modifier_pour_Cl(), Domaine_VDF::modifier_pour_Cl(), Op_VDF_Face::modifier_pour_Cl(), Op_Diff_K_Eps_VDF_base::modifier_pour_Cl(), Op_Diff_K_Omega_VDF_base::modifier_pour_Cl(), Assembleur_P_EF::modifier_secmem(), Assembleur_P_PolyMAC::modifier_secmem(), Assembleur_P_VEF::modifier_secmem(), Assembleur_P_VEFPreP1B::modifier_secmem(), AssembleurPVDF_PF::modifier_secmem_pression_imposee(), Assembleur_P_VDF::modifier_secmem_pression_imposee(), AssembleurPVDF_PF::modifier_secmem_vitesse_imposee(), Assembleur_P_VDF::modifier_secmem_vitesse_imposee(), num_face(), num_local_face(), Paroi_std_hyd_VDF::preparer_calcul_hyd(), Cond_Lim_Rayo::preparer_surface(), AssembleurPVDF_PF::remplir(), Assembleur_P_VDF::remplir(), Champ_front_contact_VEF::remplir_connect_bords(), Champ_front_contact_VEF::remplir_elems_voisin_bord(), Op_Conv_VEF_Face::remplir_fluent(), Operateur_Conv_sensibility_VEF::remplir_fluent(), Domaine_Cl_VEF::remplir_type_elem_Cl(), Domaine_Cl_VEF::remplir_volumes_entrelaces_Cl(), Paroi_TBLE_QDM::reprendre(), Paroi_TBLE_QDM_Scal::reprendre(), EDO_Pression_th_VDF_Gaz_Parfait::resoudre(), Paroi_TBLE_QDM::sauvegarder(), Paroi_TBLE_QDM_Scal::sauvegarder(), Champ_front_contact_VEF::test_faces_coin(), Champ_Face_PolyMAC::trace(), Champ_Face_PolyMAC_P0::trace(), Champ_Face_PolyMAC_P0P1NC::trace(), Champ_Face_VDF_implementation::trace(), Champ_P1iP1B_implementation::trace(), Echange_contact_Correlation_VDF::trier_coord(), Champ_Face_VDF::verifie_valeurs_cl(), Champ_P1NC::verifie_valeurs_cl(), Champ_Q1NC::verifie_valeurs_cl(), Echange_contact_VDF::verifier_correspondance(), and Assembleur_P_VEFPreP1B::verifier_dirichlet().
num_face() [1/2]
int Front_VF::num_face (const int ind_face) const inline
References Frontiere_dis_base::frontiere(), Frontiere_32_64< _SIZE_ >::get_faces_virt(), nb_faces(), and num_premiere_face().
Referenced by Operateur_Conv_sensibility_VEF::add_diffusion_scalar_term(), Operateur_Conv_sensibility_VEF::add_diffusion_term(), Op_Conv_EF_VEF_P1NC::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Dift_VEF_Face_Q1::ajouter(), Op_Div_VEFP1B_Elem::ajouter(), Terme_Boussinesq_Sensibility_VEFPreP1B_Face::ajouter(), Terme_Boussinesq_VEFPreP1B_Face::ajouter(), Terme_Source_Acceleration_VEF_Face::ajouter(), Terme_Source_Qdm_VEF_Face::ajouter(), Terme_Source_Acceleration_VDF_Face::ajouter_blocs(), Op_Grad_EF::ajouter_bord(), Op_Dift_EF_Q1::ajouter_bords(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Face::ajouter_cas_scalaire(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution_som(), Operateur_Conv_sensibility_VEF::ajouter_conv_term(), Operateur_Conv_sensibility_VEF::ajouter_Lsensibility_state_Amont(), Operateur_Conv_sensibility_VEF::ajouter_Lstate_sensibility_Amont(), Op_Div_VEFP1B_Elem::ajouter_som(), Op_Diff_PolyMAC_Elem::ajouter_termes_croises(), Op_Conv_ALE_VEF::ajouterALE(), Champ_Q1_EF::calcul_y_plus(), Op_Diff_VEFP1NCP1B_Face::calculer_divergence_som(), Op_Conv_VDF_base::calculer_dt_local(), Op_Conv_VEF_base::calculer_dt_local(), Op_Conv_Muscl_New_VEF_Face::calculer_dt_stab(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab_elem(), Op_Diff_VEFP1NCP1B_Face::calculer_flux_bords_elem(), Op_Diff_VEFP1NCP1B_Face::calculer_flux_bords_som(), Op_Diff_VEFP1NCP1B_Face::calculer_gradient_som(), Paroi_std_hyd_VEF::calculer_hyd(), Paroi_std_hyd_VEF_diphasique::calculer_hyd(), Paroi_loi_WW_hyd_EF::calculer_hyd(), Paroi_std_hyd_EF::calculer_hyd(), ParoiVEF_TBLE::calculer_hyd(), Paroi_std_hyd_VEF::calculer_hyd_BiK(), ParoiVEF_TBLE::calculer_hyd_BiK(), Op_Diff_VEF_Face_Stab::calculer_max(), Op_Diff_VEF_Face_Stab::calculer_min(), Champ_front_xyz_debit::calculer_normales_et_integrale(), Paroi_std_scal_hyd_EF::calculer_scal(), Loi_Paroi_Nu_Impose_VEF::calculer_scal(), Paroi_loi_WW_scal_VEF::calculer_scal(), Paroi_scal_analytique_VEF::calculer_scal(), Paroi_std_scal_hyd_VEF::calculer_scal(), ParoiVEF_TBLE_scal::calculer_scal(), Sortie_libre_Gradient_Pression_impose_VEFPreP1B::calculer_trace_pression(), Op_Diff_VEF_Face_Stab::completer(), Op_Dift_Stab_VEF_Face::completer(), Domaine_VEF::construire_renum_arete_perio(), Op_Diff_DG_Elem::contribuer_au_second_membre(), Op_Diff_PolyMAC_Elem::contribuer_termes_croises(), Op_Diff_VDF_Elem_base::contribuer_termes_croises(), Op_Diff_VEFP1NCP1B_Face::corriger_Cl_test(), Op_Diff_VEFP1NCP1B_Face::corriger_div_pour_Cl(), Op_Diff_PolyMAC_Elem::dimensionner_termes_croises(), Op_Diff_VDF_Elem_base::dimensionner_termes_croises(), Champ_val_tot_sur_vol_VEF::eval_contrib_loc(), Source_PDF_EF::filtre_CLD(), Champ_P1NC_implementation::filtrer_L2(), Champ_P1NC_implementation::filtrer_resu(), Champ_Generique_Tparoi_VEF::get_champ(), Domaine_Cl_EF::imposer_cond_lim(), Domaine_Cl_VEF::imposer_cond_lim(), Domaine_Cl_EF::imposer_symetrie_partiellement(), Champ_Inc_P0_base::init_fcl(), Champ_Face_base::init_fcl(), ParoiVEF_TBLE::init_lois_paroi(), ParoiVEF_TBLE_scal::init_lois_paroi(), Paroi_scal_hyd_base_VDF::init_lois_paroi(), Paroi_TBLE_QDM_Scal::init_lois_paroi(), Echange_contact_VDF::initialiser(), Champ_front_softanalytique::initialiser(), Op_Diff_VEFP1NCP1B_Face::isFaceOfSymetry(), Op_Diff_VEFP1NCP1B_Face::liste_face(), Domaine_VF::marquer_faces_double_contrib(), Champ_Front_Fonction::mettre_a_jour(), Domaine_ALE::mettre_a_jour(), Op_Diff_VEF_Face_Stab::modifie_pour_Cl(), Domaine_EF::modifier_pour_Cl(), Domaine_Poly_base::modifier_pour_Cl(), Domaine_VF::modifier_pour_Cl(), Domaine_PolyMAC::modifier_pour_Cl(), Domaine_VEF::modifier_pour_Cl(), Op_EF_base::modifier_pour_Cl(), Op_VEF_Face::modifier_pour_Cl(), Assembleur_P_VEFPreP1B::modifier_secmem_elem(), Assembleur_P_VEFPreP1B::modifier_secmem_som(), Assembleur_P_VEF::remplir(), Op_Dift_EF_Q1::remplir_marqueur_elem_CL_paroi(), Domaine_Cl_EF::remplir_type_elem_Cl(), Iterateur_Source_VEF_Face< _TYPE_ >::remplir_volumes_cl_dirichlet(), Op_Diff_VEFP1NCP1B_Face::test(), Champ_Elem_PolyMAC::trace(), Champ_front_debit_massique::update_coeff(), Echange_contact_PolyMAC::update_coeffs(), Echange_contact_PolyMAC::update_delta(), Echange_interne_impose::update_inv_lambda(), and Champ_Inc_base::valeur_aux_bords().
num_local_face()
int Front_VF::num_local_face (const int ind_global_face) const inline
References Frontiere_dis_base::frontiere(), Frontiere_32_64< _SIZE_ >::get_faces_virt(), nb_faces(), num_premiere_face(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by Loi_Paroi_Nu_Impose_VDF::calculer_scal(), Paroi_loi_WW_scal_VDF::calculer_scal(), Paroi_ODVM_scal_VDF::calculer_scal(), Paroi_std_scal_hyd_VDF::calculer_scal(), Paroi_TBLE_scal_VDF::calculer_scal(), Paroi_scal_hyd_base_VDF::compute_nusselt(), Loi_Paroi_Nu_Impose_VDF::imprimer_nusselt(), and PlaqThVDF::mettre_a_jour().
num_face() [2/2]
const ArrOfInt & Front_VF::num_face () const inline
References nb_faces_tot(), num_face(), num_face_, TRUSTArray< _TYPE_, _SIZE_ >::resize(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by num_face().
Member Data Documentation
info_obj
const Type_info Front_VF::info_obj static
num_face_
ArrOfInt Front_VF::num_face_ mutable protected
Referenced by num_face().