TrioCFD: Remove_elem Class Reference
Remove_elem Class Reference
#include <Remove_elem.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Interprete_geometrique_base_32_64< _SIZE_ >
const Type_info * get_info () const override
void mettre_a_jour_sous_domaine (Domaine_t &domaine, int_t &elem, int_t num_premier_elem, int_t nb_elem) const
Public Member Functions inherited from Interprete
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Interprete
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Interprete
static Objet_U & objet (const Nom &)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
See also
Interprete
Constructor & Destructor Documentation
Remove_elem()
Remove_elem::Remove_elem ()
~Remove_elem()
Remove_elem::~Remove_elem ()
Member Function Documentation
cree_instance()
Objet_U * Remove_elem::cree_instance () static
taille_memoire()
unsigned Remove_elem::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Remove_elem::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Remove_elem::info () static
get_info()
const Type_info * Remove_elem::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Interprete_geometrique_base_32_64< _SIZE_ >.
self_cast() [1/2]
Remove_elem & Remove_elem::self_cast (Objet_U & r) static
self_cast() [2/2]
const Remove_elem & Remove_elem::self_cast (const Objet_U & r) static
printOn()
Sortie & Remove_elem::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Interprete_geometrique_base_32_64< _SIZE_ >.
References Interprete::printOn().
readOn()
Entree & Remove_elem::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Interprete_geometrique_base_32_64< _SIZE_ >.
References Interprete::readOn().
interpreter_()
Entree & Remove_elem::interpreter_ (Entree & is) override virtual
Implements Interprete_geometrique_base_32_64< _SIZE_ >.
References Parser_U::addVar(), Param::ajouter(), Param::ajouter_non_std(), Interprete_geometrique_base_32_64< _SIZE_ >::associer_domaine(), Interprete_geometrique_base_32_64< _SIZE_ >::domaine(), f, f_ok, Scatter::init_sequential_domain(), Param::lire_avec_accolades_depuis(), NettoieNoeuds_32_64< _SIZE_ >::nettoie(), Parser_U::parseString(), Objet_U::que_suis_je(), remove_elem_(), Parser_U::setNbVar(), Parser_U::setString(), and Scatter::uninit_sequential_domain().
remove_elem_()
void Remove_elem::remove_elem_ (Domaine & dom)
References Elem_geom_base_32_64< _SIZE_ >::calculer_centres_gravite(), Domaine_32_64< _SIZE_ >::construit_octree(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Interprete_geometrique_base_32_64< _SIZE_ >::domaine(), Parser_U::eval(), f, f_ok, Domaine_32_64< _SIZE_ >::faces_bord(), Domaine_32_64< _SIZE_ >::invalide_octree(), Domaine_base::le_nom(), Domaine_32_64< _SIZE_ >::les_elems(), Domaine_32_64< _SIZE_ >::les_sommets(), listelem, Objet_U::que_suis_je(), TRUSTTab< _TYPE_, _SIZE_ >::ref(), remplir_liste(), Domaine_32_64< _SIZE_ >::reordonner(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Parser_U::setVar(), TRUSTList< _TYPE_ >::size(), Domaine_32_64< _SIZE_ >::type_elem(), and Faces_32_64< _SIZE_ >::typer().
Referenced by interpreter_().
recreer_faces()
void Remove_elem::recreer_faces (Domaine & domaine, Faces & faces, IntTab & som_face) const
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Faces_32_64< _SIZE_ >::les_sommets(), TRUSTTab< _TYPE_, _SIZE_ >::ref(), TRUSTTab< _TYPE_, _SIZE_ >::reset(), and TRUSTTab< _TYPE_, _SIZE_ >::resize().
creer_faces()
void Remove_elem::creer_faces (Domaine & dom, Faces & faces, IntTab & som_face) const
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Faces_32_64< _SIZE_ >::dimensionner(), Interprete_geometrique_base_32_64< _SIZE_ >::domaine(), Domaine_32_64< _SIZE_ >::les_sommets(), Faces_32_64< _SIZE_ >::les_sommets(), TRUSTTab< _TYPE_, _SIZE_ >::ref(), and TRUSTTab< _TYPE_, _SIZE_ >::resize().
remplir_liste()
void Remove_elem::remplir_liste (IntTab & som_face, int ind1, int ind2, int ind3, int ind4) const
References TRUSTTab< _TYPE_, _SIZE_ >::dimension().
Referenced by remove_elem_().
Member Data Documentation
info_obj
const Type_info Remove_elem::info_obj static
listelem
IntList Remove_elem::listelem protected
Referenced by remove_elem_().
f
Parser_U Remove_elem::f protected
Referenced by interpreter_(), and remove_elem_().
f_ok
int Remove_elem::f_ok = -10 protected
Referenced by interpreter_(), and remove_elem_().