TrioCFD: Corrige_flux_FT_temperature_subresolution Class Reference
Corrige_flux_FT_temperature_subresolution Class Reference
#include <Corrige_flux_FT_temperature_subresolution.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Member Enumeration Documentation
fluxes_type_
enum Corrige_flux_FT_temperature_subresolution::fluxes_type_ protected
Enumerator
convection
diffusion
Constructor & Destructor Documentation
Corrige_flux_FT_temperature_subresolution()
Corrige_flux_FT_temperature_subresolution::Corrige_flux_FT_temperature_subresolution ()
~Corrige_flux_FT_temperature_subresolution()
Corrige_flux_FT_temperature_subresolution::~Corrige_flux_FT_temperature_subresolution ()
Member Function Documentation
cree_instance()
Objet_U * Corrige_flux_FT_temperature_subresolution::cree_instance () static
taille_memoire()
unsigned Corrige_flux_FT_temperature_subresolution::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Corrige_flux_FT_temperature_subresolution::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Corrige_flux_FT_temperature_subresolution::info () static
get_info()
const Type_info * Corrige_flux_FT_temperature_subresolution::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Corrige_flux_FT_base.
self_cast() [1/2]
Corrige_flux_FT_temperature_subresolution & Corrige_flux_FT_temperature_subresolution::self_cast (Objet_U & r) static
self_cast() [2/2]
const Corrige_flux_FT_temperature_subresolution & Corrige_flux_FT_temperature_subresolution::self_cast (const Objet_U & r) static
printOn()
Sortie & Corrige_flux_FT_temperature_subresolution::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Corrige_flux_FT_base.
References Corrige_flux_FT_base::printOn().
readOn()
Entree & Corrige_flux_FT_temperature_subresolution::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Corrige_flux_FT_base.
References Corrige_flux_FT_base::readOn().
initialize_with_subproblems()
void Corrige_flux_FT_temperature_subresolution::initialize_with_subproblems (const Domaine_IJK & splitting, const IJK_Field_double & field, const IJK_Interfaces & interfaces, const Probleme_FTD_IJK_base & ijk_ft, Intersection_Interface_ijk_face & intersection_ijk_face, Intersection_Interface_ijk_cell & intersection_ijk_cell, IJK_One_Dimensional_Subproblems & thermal_subproblems) override virtual
Reimplemented from Corrige_flux_FT_base.
References associate_thermal_problems(), and Corrige_flux_FT_base::initialize_with_subproblems().
associate_thermal_problems()
void Corrige_flux_FT_temperature_subresolution::associate_thermal_problems (IJK_One_Dimensional_Subproblems & thermal_subproblems)
References thermal_subproblems_.
Referenced by initialize_with_subproblems().
set_convection_diffusion_correction()
void Corrige_flux_FT_temperature_subresolution::set_convection_diffusion_correction (const int & convective_flux_correction, const int & diffusive_flux_correction) inline override virtual
Reimplemented from Corrige_flux_FT_base.
References convective_flux_correction_, and diffusive_flux_correction_.
set_convection_negligible()
void Corrige_flux_FT_temperature_subresolution::set_convection_negligible (const int & convection_negligible) inline override virtual
Reimplemented from Corrige_flux_FT_base.
References convection_negligible_.
set_diffusion_negligible()
void Corrige_flux_FT_temperature_subresolution::set_diffusion_negligible (const int & diffusion_negligible) inline override virtual
Reimplemented from Corrige_flux_FT_base.
References diffusion_negligible_.
set_fluxes_feedback_params()
void Corrige_flux_FT_temperature_subresolution::set_fluxes_feedback_params (const int discrete_integral, const int levels) inline override virtual
Reimplemented from Corrige_flux_FT_base.
References discrete_integral_, and levels_.
set_distance_cell_faces_from_lrs()
void Corrige_flux_FT_temperature_subresolution::set_distance_cell_faces_from_lrs (const int & distance_cell_faces_from_lrs) inline override virtual
Reimplemented from Corrige_flux_FT_base.
References distance_cell_faces_from_lrs_.
set_correction_cell_neighbours()
void Corrige_flux_FT_temperature_subresolution::set_correction_cell_neighbours (const int & correct_temperature_cell_neighbours, const int & neighbours_colinearity_weighting, const int & keep_max_flux_correction, const int & smooth_temperature_field) inline override virtual
Reimplemented from Corrige_flux_FT_base.
References find_temperature_cell_neighbours_, keep_max_flux_correction_, neighbours_colinearity_weighting_, and smooth_temperature_field_.
set_cell_faces_neighbours_corrected_bool()
void Corrige_flux_FT_temperature_subresolution::set_cell_faces_neighbours_corrected_bool (IJK_Field_vector3_int & cell_faces_neighbours_corrected_bool) inline override virtual
Reimplemented from Corrige_flux_FT_base.
References cell_faces_neighbours_corrected_bool_.
set_eulerian_normal_vectors_ns_normed()
void Corrige_flux_FT_temperature_subresolution::set_eulerian_normal_vectors_ns_normed (const IJK_Field_vector3_double * eulerian_normal_vectors_ns_normed) inline override virtual
Reimplemented from Corrige_flux_FT_base.
References eulerian_normal_vectors_ns_normed_.
set_correction_cell_faces_neighbours()
void Corrige_flux_FT_temperature_subresolution::set_correction_cell_faces_neighbours (const int & find_cell_neighbours_for_fluxes_spherical_correction, const int & use_cell_neighbours_for_fluxes_spherical_correction, const int & find_reachable_fluxes, const int & use_reachable_fluxes, const int & keep_first_reachable_fluxes, const int & store_flux_operators_for_energy_balance) inline override virtual
Reimplemented from Corrige_flux_FT_base.
References find_cell_neighbours_for_fluxes_spherical_correction_, find_reachable_fluxes_, keep_first_reachable_fluxes_, store_flux_operators_for_energy_balance_, use_cell_neighbours_for_fluxes_spherical_correction_, and use_reachable_fluxes_.
set_temperature_fluxes_periodic_sharing_strategy_on_processors()
void Corrige_flux_FT_temperature_subresolution::set_temperature_fluxes_periodic_sharing_strategy_on_processors (const int & copy_fluxes_on_every_procs, const int & copy_temperature_on_every_procs) inline override virtual
Reimplemented from Corrige_flux_FT_base.
References copy_fluxes_on_every_procs_, and copy_temperature_on_every_procs_.
set_debug()
void Corrige_flux_FT_temperature_subresolution::set_debug (const int & debug) inline override virtual
Reimplemented from Corrige_flux_FT_base.
References debug_.
corrige_flux_faceIJ_any_flux()
void Corrige_flux_FT_temperature_subresolution::corrige_flux_faceIJ_any_flux (IJK_Field_local_double *const flux, FixedVector< FixedVector< std::vector< ArrOfInt >, 3 >, 2 > & index_face_ij_flux_xyz_sorted, FixedVector< std::vector< ArrOfDouble >, 3 > & subgrid_fluxes_xyz, const int k_layer, const int dir)
Referenced by corrige_flux_diff_faceIJ(), and corrige_flux_faceIJ().
corrige_flux_faceIJ()
void Corrige_flux_FT_temperature_subresolution::corrige_flux_faceIJ (IJK_Field_local_double *const flux, const int k_layer, const int dir) override virtual
Implements Corrige_flux_FT_base.
References convective_diffusive_flux_xyz_min_max_faces_sorted_, convective_diffusive_flux_xyz_sorted_, convective_flux_correction_, corrige_flux_faceIJ_any_flux(), index_face_ij_flux_xyz_neighbours_min_max_faces_sorted_, index_face_ij_flux_xyz_sorted_, and use_reachable_fluxes_.
Referenced by corrige_flux_conv_faceIJ().
corrige_flux_conv_faceIJ()
void Corrige_flux_FT_temperature_subresolution::corrige_flux_conv_faceIJ (IJK_Field_local_double *const flux, const int k_layer, const int dir) inline
References corrige_flux_faceIJ().
corrige_flux_diff_faceIJ()
void Corrige_flux_FT_temperature_subresolution::corrige_flux_diff_faceIJ (IJK_Field_local_double *const flux, const int k_layer, const int dir) override virtual
Reimplemented from Corrige_flux_FT_base.
References convective_diffusive_flux_xyz_min_max_faces_sorted_, convective_diffusive_flux_xyz_sorted_, corrige_flux_faceIJ_any_flux(), diffusive_flux_correction_, index_face_ij_flux_xyz_neighbours_min_max_faces_sorted_, index_face_ij_flux_xyz_sorted_, and use_reachable_fluxes_.
correct_flux_spherical()
void Corrige_flux_FT_temperature_subresolution::correct_flux_spherical (Simd_double & a, Simd_double & b, const int & i, const int & j, const int & k_layer, const int dir) override virtual
Reimplemented from Corrige_flux_FT_base.
References eulerian_normal_vectors_ns_normed_, and use_cell_neighbours_for_fluxes_spherical_correction_.
calcul_temperature_flux_interface()
void Corrige_flux_FT_temperature_subresolution::calcul_temperature_flux_interface (const IJK_Field_double & temperature, const double ldal, const double ldav, const double dist, const DoubleTab & positions, const DoubleTab & normale, ArrOfDouble & temperature_interp, ArrOfDouble & flux_normal_interp, ArrOfDouble & temp_liqu, ArrOfDouble & temp_vap, DoubleTab & coo_liqu, DoubleTab & coo_vap) const inline override virtual
Implements Corrige_flux_FT_base.
update_intersections()
void Corrige_flux_FT_temperature_subresolution::update_intersections () override virtual
Reimplemented from Corrige_flux_FT_base.
References convection_negligible_, diffusion_negligible_, Corrige_flux_FT_base::intersection_ijk_cell_, Intersection_Interface_ijk_cell::update_interpolations_cell_centres_on_interface(), and Intersection_Interface_ijk_cell::update_interpolations_cell_faces_on_interface().
update()
void Corrige_flux_FT_temperature_subresolution::update () override virtual
Implements Corrige_flux_FT_base.
References associate_indices_and_check_subproblems_consistency().
associate_indices_and_check_subproblems_consistency()
void Corrige_flux_FT_temperature_subresolution::associate_indices_and_check_subproblems_consistency ()
References Process::exit(), IJK_One_Dimensional_Subproblems::get_effective_subproblems_counter(), Intersection_Interface_ijk_cell::get_nb_diph(), IJK_One_Dimensional_Subproblems::get_subproblem_ijk_indices(), IJK_One_Dimensional_Subproblems::get_subproblems_counter(), has_checked_consistency_, ijk_intersections_subproblems_indices_, Corrige_flux_FT_base::intersection_ijk_cell_, TRUSTArray< _TYPE_, _SIZE_ >::reset(), TRUSTArray< _TYPE_, _SIZE_ >::resize(), and thermal_subproblems_.
Referenced by update().
compute_temperature_cell_centre()
void Corrige_flux_FT_temperature_subresolution::compute_temperature_cell_centre (IJK_Field_double & temperature) const override virtual
Reimplemented from Corrige_flux_FT_base.
References debug_, Intersection_Interface_ijk::dist_interf(), distance_cell_faces_from_lrs_, IJK_One_Dimensional_Subproblems::get_bary_facet(), IJK_One_Dimensional_Subproblems::get_dist_cell_interface(), IJK_One_Dimensional_Subproblems::get_effective_subproblems_counter(), IJK_One_Dimensional_Subproblems::get_max_temperature_domain_ends(), IJK_One_Dimensional_Subproblems::get_min_temperature_domain_ends(), IJK_One_Dimensional_Subproblems::get_subproblem_ijk_indices(), IJK_One_Dimensional_Subproblems::get_temperature_profile_at_point(), ijk_intersections_subproblems_indices_, Corrige_flux_FT_base::intersection_ijk_cell_, Corrige_flux_FT_base::ref_ijk_ft_, and thermal_subproblems_.
compute_temperature_cell_centre_neighbours()
void Corrige_flux_FT_temperature_subresolution::compute_temperature_cell_centre_neighbours (IJK_Field_double & temperature_neighbours, IJK_Field_int & neighbours_weighting, IJK_Field_double & neighbours_weighting_colinearity) override virtual
Reimplemented from Corrige_flux_FT_base.
References combine_temperature_cell_centre_neighbours_from_procs(), compute_temperature_cell_centre_neighbours_on_procs(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::data(), distance_cell_faces_from_lrs_, IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel(), find_temperature_cell_neighbours_, IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_domaine(), IJK_One_Dimensional_Subproblems::get_dxyz_increment_bool(), Domaine_IJK::get_nb_elem_tot(), Domaine_IJK::get_offset_local(), IJK_One_Dimensional_Subproblems::get_pure_neighbours_corrected_colinearity(), IJK_One_Dimensional_Subproblems::get_pure_neighbours_corrected_distance(), IJK_One_Dimensional_Subproblems::get_pure_neighbours_corrected_sign(), IJK_One_Dimensional_Subproblems::get_pure_neighbours_to_correct(), IJK_One_Dimensional_Subproblems::get_subproblem_ijk_indices(), IJK_One_Dimensional_Subproblems::get_temperature_profile_at_point(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost(), ijk_intersections_subproblems_indices_, neighbours_colinearity_weighting_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), receive_temperature_cell_centre_neighbours_from_procs(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and thermal_subproblems_.
compute_temperature_cell_centre_neighbours_on_procs()
void Corrige_flux_FT_temperature_subresolution::compute_temperature_cell_centre_neighbours_on_procs (const double & temperature_neighbours, const double & neighbours_weighting_colinearity, const int & index_i_neighbour_global, const int & index_j_neighbour_global, const int & index_k_neighbour_global)
References TRUSTArray< _TYPE_, _SIZE_ >::append_array(), indices_temperature_neighbours_on_procs_, neighbours_colinearity_weighting_, neighbours_weighting_colinearity_on_procs_, and temperature_neighbours_on_procs_.
Referenced by compute_temperature_cell_centre_neighbours().
receive_temperature_cell_centre_neighbours_from_procs()
void Corrige_flux_FT_temperature_subresolution::receive_temperature_cell_centre_neighbours_from_procs ()
References Process::check_int_overflow(), copy_temperature_on_every_procs_, indices_temperature_neighbours_on_procs_, Process::me(), Process::mp_sum(), neighbours_colinearity_weighting_, neighbours_weighting_colinearity_on_procs_, Process::nproc(), TRUSTArray< _TYPE_, _SIZE_ >::reset(), TRUSTArray< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and temperature_neighbours_on_procs_.
Referenced by compute_temperature_cell_centre_neighbours().
combine_temperature_cell_centre_neighbours_from_procs()
void Corrige_flux_FT_temperature_subresolution::combine_temperature_cell_centre_neighbours_from_procs (IJK_Field_double & temperature_neighbours, IJK_Field_int & neighbours_weighting, IJK_Field_double & neighbours_weighting_colinearity, const int & ni, const int & nj, const int & nk, const int & offset_i, const int & offset_j, const int & offset_k)
References copy_temperature_on_every_procs_, indices_temperature_neighbours_on_procs_, neighbours_colinearity_weighting_, neighbours_weighting_colinearity_on_procs_, and temperature_neighbours_on_procs_.
Referenced by compute_temperature_cell_centre_neighbours().
replace_temperature_cell_centre_neighbours()
void Corrige_flux_FT_temperature_subresolution::replace_temperature_cell_centre_neighbours (IJK_Field_double & temperature, IJK_Field_double & temperature_neighbours, IJK_Field_int & neighbours_weighting, IJK_Field_double & neighbours_weighting_colinearity) const override virtual
Reimplemented from Corrige_flux_FT_base.
References TRUSTArray< _TYPE_, _SIZE_ >::append_array(), Domaine_IJK::convert_ijk_cell_to_packed(), debug_, distance_cell_faces_from_lrs_, IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel(), find_temperature_cell_neighbours_, IJK_One_Dimensional_Subproblems::get_dist_cell_interface(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_domaine(), IJK_One_Dimensional_Subproblems::get_subproblem_index_from_ijk_indices(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost(), neighbours_colinearity_weighting_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), Corrige_flux_FT_base::ref_ijk_ft_, smooth_temperature_cell_centre_neighbours(), smooth_temperature_field_, and thermal_subproblems_.
smooth_temperature_cell_centre_neighbours()
void Corrige_flux_FT_temperature_subresolution::smooth_temperature_cell_centre_neighbours (IJK_Field_double & temperature, ArrOfInt & corrected_values, ArrOfInt & out_of_bounds_corrected_values, ArrOfDouble & out_of_bounds_values, IJK_Field_double & distance) const
References TRUSTArray< _TYPE_, _SIZE_ >::append_array(), Domaine_IJK::convert_packed_to_ijk_cell(), debug_, IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_domaine(), Corrige_flux_FT_base::ref_ijk_ft_, TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and smooth_temperature_field_.
Referenced by replace_temperature_cell_centre_neighbours().
initialise_cell_neighbours_indices_to_correct()
void Corrige_flux_FT_temperature_subresolution::initialise_cell_neighbours_indices_to_correct () override virtual
Reimplemented from Corrige_flux_FT_base.
References colinearity_flux_xyz_neighbours_all_faces_remaining_global_sorted_, convection_negligible_, convective_diffusive_flux_all_faces_remaining_global_sorted_, convective_diffusive_flux_xyz_min_max_faces_sorted_, diffusion_negligible_, distance_cell_faces_from_lrs_, find_cell_neighbours_for_fluxes_spherical_correction_, find_reachable_fluxes_, find_temperature_cell_neighbours_, flux_init_, index_face_ij_flux_xyz_neighbours_all_faces_remaining_global_sorted_, index_face_ij_flux_xyz_neighbours_diag_faces_sorted_, index_face_ij_flux_xyz_neighbours_min_max_faces_sorted_, initialise_any_cell_neighbours_indices_to_correct(), initialise_any_cell_neighbours_indices_to_correct_with_flux(), Process::nproc(), temperature_flux_all_faces_remaining_global_sorted_, use_reachable_fluxes_, and weighting_flux_xyz_neighbours_all_faces_remaining_global_sorted_.
initialise_fixed_vectors()
void Corrige_flux_FT_temperature_subresolution::initialise_fixed_vectors (FixedVector< FixedVector< std::vector< ArrOfInt >, 3 >, 2 > & fixed_vectors, const int nb_k_layer)
Referenced by initialise_any_cell_neighbours_indices_to_correct().
initialise_fixed_vector()
void Corrige_flux_FT_temperature_subresolution::initialise_fixed_vector (FixedVector< std::vector< ArrOfInt >, 3 > & fixed_vector, const int nb_k_layer)
Referenced by initialise_any_cell_neighbours_indices_to_correct_with_flux().
initialise_fixed_vector_values()
void Corrige_flux_FT_temperature_subresolution::initialise_fixed_vector_values (FixedVector< std::vector< ArrOfDouble >, 3 > & fixed_vector_values, const int nb_k_layer)
Referenced by initialise_any_cell_neighbours_indices_to_correct_with_flux().
initialise_any_cell_neighbours_indices_to_correct()
void Corrige_flux_FT_temperature_subresolution::initialise_any_cell_neighbours_indices_to_correct (FixedVector< FixedVector< std::vector< ArrOfInt >, 3 >, 2 > & index_face_ij_flux_xyz_faces_sorted, const int global_indices = 0)
References initialise_fixed_vectors(), and Corrige_flux_FT_base::ref_ijk_ft_.
Referenced by initialise_any_cell_neighbours_indices_to_correct_with_flux(), and initialise_cell_neighbours_indices_to_correct().
initialise_any_cell_neighbours_indices_to_correct_with_flux()
void Corrige_flux_FT_temperature_subresolution::initialise_any_cell_neighbours_indices_to_correct_with_flux (FixedVector< FixedVector< std::vector< ArrOfInt >, 3 >, 2 > & index_face_ij_flux_xyz_faces_sorted, FixedVector< std::vector< ArrOfDouble >, 3 > & fluxes, FixedVector< std::vector< ArrOfInt >, 3 > & weighting_flux_xyz_faces_sorted, FixedVector< std::vector< ArrOfDouble >, 3 > & colinearity_flux_xyz_faces_sorted, FixedVector< std::vector< ArrOfDouble >, 3 > & temperature_flux_xyz_faces_sorted, const bool & ini_index, const int global_indices = 0, const int weighting_colinearity = 0)
References initialise_any_cell_neighbours_indices_to_correct(), initialise_fixed_vector(), initialise_fixed_vector_values(), Corrige_flux_FT_base::ref_ijk_ft_, and store_flux_operators_for_energy_balance_.
Referenced by initialise_cell_neighbours_indices_to_correct(), and sort_ijk_intersections_subproblems_indices_fluxes_by_k_layers().
compute_cell_neighbours_faces_indices_for_spherical_correction()
void Corrige_flux_FT_temperature_subresolution::compute_cell_neighbours_faces_indices_for_spherical_correction (const int & n_iter_distance) override virtual
Reimplemented from Corrige_flux_FT_base.
References cell_faces_neighbours_corrected_bool_, distance_cell_faces_from_lrs_, find_cell_neighbours_for_fluxes_spherical_correction_, IJK_One_Dimensional_Subproblems::get_dxyz_increment_bool(), IJK_One_Dimensional_Subproblems::get_pure_neighbours_corrected_sign(), IJK_One_Dimensional_Subproblems::get_pure_neighbours_to_correct(), IJK_One_Dimensional_Subproblems::get_subproblem_ijk_indices(), ijk_intersections_subproblems_indices_, index_face_ij_flux_xyz_neighbours_diag_faces_sorted_, Corrige_flux_FT_base::ref_ijk_ft_, TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and thermal_subproblems_.
compute_cell_neighbours_mixed_cell_faces_indices_to_correct()
void Corrige_flux_FT_temperature_subresolution::compute_cell_neighbours_mixed_cell_faces_indices_to_correct (IJK_Field_vector3_int & cell_faces_neighbours_corrected_bool_mixed_cell, IJK_Field_vector3_double & cell_faces_neighbours_corrected_velocity_temperature, IJK_Field_vector3_double & cell_faces_neighbours_corrected_convective_mixed_cell, IJK_Field_vector3_double & cell_faces_neighbours_corrected_diffusive_mixed_cell, IJK_Field_vector3_double & neighbours_weighting_colinearity_mixed_cell)
References IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::allocate(), compute_cell_neighbours_mixed_cell_faces_any_field(), convective_flux_correction_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::data(), diffusive_flux_correction_, distance_cell_faces_from_lrs_, IJK_Field_vector< T, N >::echange_espace_virtuel(), find_reachable_fluxes_, keep_first_reachable_fluxes_, neighbours_colinearity_weighting_, Corrige_flux_FT_base::ref_ijk_ft_, store_flux_operators_for_energy_balance_, and use_reachable_fluxes_.
Referenced by compute_cell_neighbours_faces_indices_to_correct().
compute_cell_neighbours_mixed_cell_faces_any_field()
void Corrige_flux_FT_temperature_subresolution::compute_cell_neighbours_mixed_cell_faces_any_field (IJK_Field_vector3_int & cell_faces_neighbours_corrected_bool, IJK_Field_local_double & cell_faces_neighbours_corrected_field, IJK_Field_vector3_double & cell_faces_neighbours_corrected_field_mixed_cell)
References IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::data(), and IJK_Field_vector< T, N >::echange_espace_virtuel().
Referenced by compute_cell_neighbours_mixed_cell_faces_indices_to_correct().
compute_cell_neighbours_faces_indices_to_correct()
void Corrige_flux_FT_temperature_subresolution::compute_cell_neighbours_faces_indices_to_correct (IJK_Field_vector3_int & cell_faces_neighbours_corrected_bool, IJK_Field_vector3_double & cell_faces_neighbours_corrected_velocity_temperature, IJK_Field_vector3_double & cell_faces_neighbours_corrected_convective, IJK_Field_vector3_double & cell_faces_neighbours_corrected_diffusive, IJK_Field_vector3_double & neighbours_weighting_colinearity) override virtual
Reimplemented from Corrige_flux_FT_base.
References combine_all_fluxes_from_outisde_frontier_on_procs(), complete_neighbours_and_weighting_colinearity(), compute_cell_neighbours_fluxes_to_correct(), compute_cell_neighbours_mixed_cell_faces_indices_to_correct(), compute_flux_neighbours_on_procs(), convective_flux_correction_, debug_, diffusive_flux_correction_, distance_cell_faces_from_lrs_, IJK_Field_vector< T, N >::echange_espace_virtuel(), find_reachable_fluxes_, IJK_One_Dimensional_Subproblems::get_dxyz_over_two_increment_bool(), Domaine_IJK::get_nb_elem_tot(), Domaine_IJK::get_offset_local(), IJK_One_Dimensional_Subproblems::get_pure_neighbours_corrected_sign(), IJK_One_Dimensional_Subproblems::get_pure_neighbours_last_faces_corrected_colinearity(), IJK_One_Dimensional_Subproblems::get_pure_neighbours_last_faces_corrected_distance(), IJK_One_Dimensional_Subproblems::get_pure_neighbours_last_faces_to_correct(), IJK_One_Dimensional_Subproblems::get_subproblem_ijk_indices(), ijk_intersections_subproblems_indices_, neighbours_colinearity_weighting_, Process::nproc(), receive_all_fluxes_from_outisde_frontier_on_procs(), Corrige_flux_FT_base::ref_ijk_ft_, TRUSTArray< _TYPE_, _SIZE_ >::size_array(), store_flux_operators_for_energy_balance_, thermal_subproblems_, and use_reachable_fluxes_.
compute_flux_neighbours_on_procs()
void Corrige_flux_FT_temperature_subresolution::compute_flux_neighbours_on_procs (const int & index_i_neighbour_global, const int & index_j_neighbour_global, const int & index_k_neighbour_global, const int & subproblem_index, const double & dist, const int & dir, const double & colinearity, const int & index_i, const int & index_j, const int & index_k, const double & convective_flux_computed = 0, const double & diffusive_flux_computed = 0)
References colinearity_flux_xyz_neighbours_all_faces_remaining_global_sorted_, compute_cell_neighbours_convective_fluxes_to_correct(), compute_cell_neighbours_diffusive_fluxes_to_correct(), convective_diffusive_flux_all_faces_remaining_global_sorted_, convective_flux_correction_, diffusive_flux_correction_, flux_outside_frontier_all_map_, get_linear_index_global(), index_face_ij_flux_xyz_neighbours_all_faces_remaining_global_sorted_, neighbours_colinearity_weighting_, store_flux_operators_for_energy_balance_, temperature_flux_all_faces_remaining_global_sorted_, use_reachable_fluxes_, and weighting_flux_xyz_neighbours_all_faces_remaining_global_sorted_.
Referenced by compute_cell_neighbours_faces_indices_to_correct().
receive_all_fluxes_from_outisde_frontier_on_procs()
void Corrige_flux_FT_temperature_subresolution::receive_all_fluxes_from_outisde_frontier_on_procs ()
References Process::check_int_overflow(), colinearity_flux_xyz_neighbours_all_faces_remaining_global_sorted_, convective_diffusive_flux_all_faces_remaining_global_sorted_, convective_flux_correction_, copy_fluxes_on_every_procs_, debug_, diffusive_flux_correction_, index_face_ij_flux_xyz_neighbours_all_faces_remaining_global_sorted_, Process::me(), Process::mp_sum(), neighbours_colinearity_weighting_, Process::nproc(), TRUSTArray< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), store_flux_operators_for_energy_balance_, temperature_flux_all_faces_remaining_global_sorted_, use_reachable_fluxes_, and weighting_flux_xyz_neighbours_all_faces_remaining_global_sorted_.
Referenced by compute_cell_neighbours_faces_indices_to_correct().
combine_all_fluxes_from_outisde_frontier_on_procs()
void Corrige_flux_FT_temperature_subresolution::combine_all_fluxes_from_outisde_frontier_on_procs (IJK_Field_vector3_int & cell_faces_neighbours_corrected_bool, IJK_Field_vector3_double & cell_faces_neighbours_corrected_velocity_temperature, IJK_Field_vector3_double & cell_faces_neighbours_corrected_convective, IJK_Field_vector3_double & cell_faces_neighbours_corrected_diffusive, IJK_Field_vector3_double & neighbours_weighting_colinearity)
References colinearity_flux_xyz_neighbours_all_faces_remaining_global_sorted_, convective_diffusive_flux_all_faces_remaining_global_sorted_, convective_flux_correction_, diffusive_flux_correction_, get_add_replace_flux_value(), Domaine_IJK::get_offset_local(), index_face_ij_flux_xyz_neighbours_all_faces_remaining_global_sorted_, neighbours_colinearity_weighting_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), Corrige_flux_FT_base::ref_ijk_ft_, store_flux_operators_for_energy_balance_, temperature_flux_all_faces_remaining_global_sorted_, use_reachable_fluxes_, and weighting_flux_xyz_neighbours_all_faces_remaining_global_sorted_.
Referenced by compute_cell_neighbours_faces_indices_to_correct().
identify_wrong_predicted_values()
bool Corrige_flux_FT_temperature_subresolution::identify_wrong_predicted_values (IJK_Field_vector3_int & cell_faces_neighbours_corrected_bool, IJK_Field_vector3_double & cell_faces_neighbours_corrected_convective_diffusive_flux, const int & dir, const int & index_i, const int & index_j, const int & index_k, double & convective_diffusive_flux)
Referenced by compute_cell_neighbours_fluxes_to_correct().
get_add_replace_flux_value()
void Corrige_flux_FT_temperature_subresolution::get_add_replace_flux_value (IJK_Field_vector3_double & cell_faces_neighbours_corrected_convective_diffusive_flux, const int & dir, const int & i, const int & j, const int & k, double & convective_diffusive_flux, const double & replace_weighting_values)
References keep_max_flux_correction_.
Referenced by combine_all_fluxes_from_outisde_frontier_on_procs(), and compute_cell_neighbours_fluxes_to_correct().
complete_neighbours_and_weighting_colinearity()
void Corrige_flux_FT_temperature_subresolution::complete_neighbours_and_weighting_colinearity (IJK_Field_vector3_int & cell_faces_neighbours_corrected_bool, IJK_Field_vector3_double & cell_faces_neighbours_corrected_velocity_temperature, IJK_Field_vector3_double & cell_faces_neighbours_corrected_convective, IJK_Field_vector3_double & cell_faces_neighbours_corrected_diffusive, IJK_Field_vector3_double & neighbours_weighting_colinearity, const int & compute_fluxes_values)
References convective_flux_correction_, diffusive_flux_correction_, IJK_Field_vector< T, N >::echange_espace_virtuel(), keep_max_flux_correction_, neighbours_colinearity_weighting_, and store_flux_operators_for_energy_balance_.
Referenced by compute_cell_neighbours_faces_indices_to_correct().
compute_cell_neighbours_fluxes_to_correct()
void Corrige_flux_FT_temperature_subresolution::compute_cell_neighbours_fluxes_to_correct (IJK_Field_vector3_int & cell_faces_neighbours_corrected_bool, IJK_Field_vector3_double & neighbours_weighting_colinearity, IJK_Field_vector3_double & cell_faces_neighbours_corrected_convective, IJK_Field_vector3_double & cell_faces_neighbours_corrected_diffusive, IJK_Field_vector3_double & cell_faces_neighbours_corrected_velocity_temperature, const int & subproblem_index, const int & index_i, const int & index_j, const int & index_k, const double & dist, const int & dir, const double & colinearity, const int & compute_fluxes_values, double & convective_flux, double & diffusive_flux)
References compute_cell_neighbours_convective_fluxes_to_correct(), compute_cell_neighbours_diffusive_fluxes_to_correct(), convective_flux_correction_, diffusive_flux_correction_, get_add_replace_flux_value(), identify_wrong_predicted_values(), neighbours_colinearity_weighting_, store_flux_operators_for_energy_balance_, and use_reachable_fluxes_.
Referenced by compute_cell_neighbours_faces_indices_to_correct().
compute_cell_neighbours_convective_fluxes_to_correct()
bool Corrige_flux_FT_temperature_subresolution::compute_cell_neighbours_convective_fluxes_to_correct (double & convective_flux, const int & subproblem_index, const double & dist, const int & dir, const double & colinearity, const int & index_i, const int & index_j, const int & index_k, const int & temperature = 0)
References compute_cell_neighbours_thermal_convective_fluxes_face_centre(), compute_cell_neighbours_thermal_convective_fluxes_face_centre_discrete_integral(), and discrete_integral_.
Referenced by compute_cell_neighbours_fluxes_to_correct(), and compute_flux_neighbours_on_procs().
compute_cell_neighbours_thermal_convective_fluxes_face_centre()
bool Corrige_flux_FT_temperature_subresolution::compute_cell_neighbours_thermal_convective_fluxes_face_centre (double & convective_flux, const int & subproblem_index, const double & dist, const int & dir, const double & colinearity, const int & index_i, const int & index_j, const int & index_k, const int & temperature = 0)
References compute_cell_neighbours_thermal_fluxes_face_centre(), and convection.
Referenced by compute_cell_neighbours_convective_fluxes_to_correct().
compute_cell_neighbours_thermal_convective_fluxes_face_centre_discrete_integral()
void Corrige_flux_FT_temperature_subresolution::compute_cell_neighbours_thermal_convective_fluxes_face_centre_discrete_integral (double & convective_flux, const int & subproblem_index, const double & dist, const int & dir, const double & colinearity, const int & index_i, const int & index_j, const int & index_k)
References compute_cell_neighbours_thermal_fluxes_face_centre_discrete_integral(), and convection.
Referenced by compute_cell_neighbours_convective_fluxes_to_correct().
compute_cell_neighbours_diffusive_fluxes_to_correct()
bool Corrige_flux_FT_temperature_subresolution::compute_cell_neighbours_diffusive_fluxes_to_correct (double & diffusive_flux, const int & subproblem_index, const double & dist, const int & dir, const double & colinearity, const int & index_i, const int & index_j, const int & index_k)
References compute_cell_neighbours_thermal_diffusive_fluxes_face_centre(), compute_cell_neighbours_thermal_diffusive_fluxes_face_centre_discrete_integral(), and discrete_integral_.
Referenced by compute_cell_neighbours_fluxes_to_correct(), and compute_flux_neighbours_on_procs().
compute_cell_neighbours_thermal_diffusive_fluxes_face_centre()
bool Corrige_flux_FT_temperature_subresolution::compute_cell_neighbours_thermal_diffusive_fluxes_face_centre (double & diffusive_flux, const int & subproblem_index, const double & dist, const int & dir, const double & colinearity, const int & index_i, const int & index_j, const int & index_k)
References compute_cell_neighbours_thermal_fluxes_face_centre(), and diffusion.
Referenced by compute_cell_neighbours_diffusive_fluxes_to_correct().
compute_cell_neighbours_thermal_diffusive_fluxes_face_centre_discrete_integral()
void Corrige_flux_FT_temperature_subresolution::compute_cell_neighbours_thermal_diffusive_fluxes_face_centre_discrete_integral (double & diffusive_flux, const int & subproblem_index, const double & dist, const int & dir, const double & colinearity, const int & index_i, const int & index_j, const int & index_k)
References compute_cell_neighbours_thermal_fluxes_face_centre_discrete_integral(), and diffusion.
Referenced by compute_cell_neighbours_diffusive_fluxes_to_correct().
compute_cell_neighbours_thermal_fluxes_face_centre()
bool Corrige_flux_FT_temperature_subresolution::compute_cell_neighbours_thermal_fluxes_face_centre (double & flux, const int fluxes_type, const int & subproblem_index, const double & dist, const int & dir, const double & colinearity, const int & index_i, const int & index_j, const int & index_k, const int & temperature = 0)
References compute_thermal_flux_face_centre(), Corrige_flux_FT_base::domaine_, and neighbours_colinearity_weighting_.
Referenced by compute_cell_neighbours_thermal_convective_fluxes_face_centre(), and compute_cell_neighbours_thermal_diffusive_fluxes_face_centre().
compute_cell_neighbours_thermal_fluxes_face_centre_discrete_integral()
void Corrige_flux_FT_temperature_subresolution::compute_cell_neighbours_thermal_fluxes_face_centre_discrete_integral (double & flux, const int fluxes_type, const int & subproblem_index, const double & dist, const int & dir, const double & colinearity, const int & index_i, const int & index_j, const int & index_k)
References compute_thermal_flux_face_centre_discrete_integral(), neighbours_colinearity_weighting_, and TRUSTVect< _TYPE_, _SIZE_ >::size().
Referenced by compute_cell_neighbours_thermal_convective_fluxes_face_centre_discrete_integral(), and compute_cell_neighbours_thermal_diffusive_fluxes_face_centre_discrete_integral().
replace_cell_neighbours_thermal_convective_diffusive_fluxes_faces()
void Corrige_flux_FT_temperature_subresolution::replace_cell_neighbours_thermal_convective_diffusive_fluxes_faces (const IJK_Field_vector3_int & cell_faces_neighbours_corrected_min_max_bool, const IJK_Field_vector3_int & cell_faces_neighbours_corrected_all_bool, const IJK_Field_vector3_double & cell_faces_neighbours_fluxes_corrected, const int & fluxes_type) override virtual
Reimplemented from Corrige_flux_FT_base.
References convection, convection_negligible_, convective_diffusive_flux_xyz_min_max_faces_sorted_, debug_, diffusion, diffusion_negligible_, replace_cell_neighbours_thermal_fluxes_faces(), and use_reachable_fluxes_.
replace_cell_neighbours_thermal_fluxes_faces()
void Corrige_flux_FT_temperature_subresolution::replace_cell_neighbours_thermal_fluxes_faces (const IJK_Field_vector3_int & cell_faces_neighbours_corrected_min_max_bool, const IJK_Field_vector3_int & cell_faces_neighbours_corrected_all_bool, const IJK_Field_vector3_double & cell_faces_neighbours_fluxes_corrected, FixedVector< std::vector< ArrOfDouble >, 3 > & flux_xyz, const int counter)
References index_face_ij_flux_xyz_neighbours_min_max_faces_sorted_, and keep_first_reachable_fluxes_.
Referenced by replace_cell_neighbours_thermal_convective_diffusive_fluxes_faces().
set_zero_temperature_increment()
void Corrige_flux_FT_temperature_subresolution::set_zero_temperature_increment (IJK_Field_double & d_temperature) const override virtual
Reimplemented from Corrige_flux_FT_base.
References IJK_One_Dimensional_Subproblems::get_effective_subproblems_counter(), IJK_One_Dimensional_Subproblems::get_subproblem_ijk_indices(), and thermal_subproblems_.
compute_thermal_convective_fluxes()
void Corrige_flux_FT_temperature_subresolution::compute_thermal_convective_fluxes (const int & last_flux) override virtual
Reimplemented from Corrige_flux_FT_base.
References compute_thermal_convective_fluxes_face_centre(), compute_thermal_convective_fluxes_face_centre_discrete_integral(), and discrete_integral_.
compute_thermal_diffusive_fluxes()
void Corrige_flux_FT_temperature_subresolution::compute_thermal_diffusive_fluxes (const int & last_flux) override virtual
Reimplemented from Corrige_flux_FT_base.
References compute_thermal_diffusive_fluxes_face_centre(), compute_thermal_diffusive_fluxes_face_centre_discrete_integral(), and discrete_integral_.
compute_thermal_convective_fluxes_face_centre()
void Corrige_flux_FT_temperature_subresolution::compute_thermal_convective_fluxes_face_centre (const int & last_flux)
References compute_thermal_fluxes_face_centre(), convection, and convective_fluxes_.
Referenced by compute_thermal_convective_fluxes().
compute_thermal_diffusive_fluxes_face_centre()
void Corrige_flux_FT_temperature_subresolution::compute_thermal_diffusive_fluxes_face_centre (const int & last_flux)
References compute_thermal_fluxes_face_centre(), diffusion, and diffusive_fluxes_.
Referenced by compute_thermal_diffusive_fluxes().
compute_thermal_fluxes_face_centre()
void Corrige_flux_FT_temperature_subresolution::compute_thermal_fluxes_face_centre (DoubleVect & fluxes, const int fluxes_type, const int & last_flux)
References IJK_One_Dimensional_Subproblems::complete_frame_of_reference_lrs_fluxes_eval(), IJK_One_Dimensional_Subproblems::compute_error_flux_interface(), compute_thermal_flux_face_centre(), dist_, Intersection_Interface_ijk_cell::dist_pure_faces_interf(), distance_cell_faces_from_lrs_, Corrige_flux_FT_base::domaine_, IJK_One_Dimensional_Subproblems::get_dist_faces_interface(), Intersection_Interface_ijk_cell::get_ijk_pure_face_neighbours(), Intersection_Interface_ijk_cell::get_nb_faces_to_correct(), ijk_intersections_subproblems_indices_, Corrige_flux_FT_base::intersection_ijk_cell_, TRUSTVect< _TYPE_, _SIZE_ >::reset(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), IJK_One_Dimensional_Subproblems::set_pure_flux_corrected(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and thermal_subproblems_.
Referenced by compute_thermal_convective_fluxes_face_centre(), and compute_thermal_diffusive_fluxes_face_centre().
complete_thermal_fluxes_face_centre() [1/2]
void Corrige_flux_FT_temperature_subresolution::complete_thermal_fluxes_face_centre (const int & fluxes_correction_conservations) override virtual
Reimplemented from Corrige_flux_FT_base.
References complete_thermal_fluxes_face_centre(), convective_fluxes_, diffusive_flux_correction_, and diffusive_fluxes_.
Referenced by complete_thermal_fluxes_face_centre().
complete_thermal_fluxes_face_centre() [2/2]
void Corrige_flux_FT_temperature_subresolution::complete_thermal_fluxes_face_centre (DoubleVect * fluxes, const int & fluxes_correction_conservations)
References IJK_One_Dimensional_Subproblems::get_corrective_flux_from_current(), IJK_One_Dimensional_Subproblems::get_corrective_flux_from_neighbours(), Intersection_Interface_ijk_cell::get_ijk_pure_face_neighbours(), ijk_intersections_subproblems_indices_, Corrige_flux_FT_base::intersection_ijk_cell_, IJK_One_Dimensional_Subproblems::set_pure_flux_corrected(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and thermal_subproblems_.
compute_thermal_flux_face_centre()
double Corrige_flux_FT_temperature_subresolution::compute_thermal_flux_face_centre (const int fluxes_type, const int & index_subproblem, const double & dist, const int & dir, bool & valid_val, const int & l = -1, const int & index_i = -100, const int & index_j = -100, const int & index_k = -100, const int & temperature = 0)
References convection, diffusion, IJK_One_Dimensional_Subproblems::get_temperature_gradient_times_conductivity_profile_at_point(), IJK_One_Dimensional_Subproblems::get_temperature_times_velocity_profile_at_point(), and thermal_subproblems_.
Referenced by compute_cell_neighbours_thermal_fluxes_face_centre(), and compute_thermal_fluxes_face_centre().
compute_thermal_convective_fluxes_face_centre_discrete_integral()
void Corrige_flux_FT_temperature_subresolution::compute_thermal_convective_fluxes_face_centre_discrete_integral ()
References compute_thermal_fluxes_face_centre_discrete_integral(), convection, and convective_fluxes_.
Referenced by compute_thermal_convective_fluxes().
compute_thermal_diffusive_fluxes_face_centre_discrete_integral()
void Corrige_flux_FT_temperature_subresolution::compute_thermal_diffusive_fluxes_face_centre_discrete_integral ()
References compute_thermal_fluxes_face_centre_discrete_integral(), diffusion, and diffusive_fluxes_.
Referenced by compute_thermal_diffusive_fluxes().
compute_thermal_fluxes_face_centre_discrete_integral()
void Corrige_flux_FT_temperature_subresolution::compute_thermal_fluxes_face_centre_discrete_integral (DoubleVect & fluxes, const int fluxes_type)
References IJK_One_Dimensional_Subproblems::complete_frame_of_reference_lrs_fluxes_eval(), compute_thermal_flux_face_centre_discrete_integral(), dist_, Intersection_Interface_ijk_cell::dist_pure_faces_interf(), distance_cell_faces_from_lrs_, IJK_One_Dimensional_Subproblems::get_dist_faces_interface(), Intersection_Interface_ijk_cell::get_ijk_pure_face_neighbours(), Intersection_Interface_ijk_cell::get_nb_faces_to_correct(), ijk_intersections_subproblems_indices_, Corrige_flux_FT_base::intersection_ijk_cell_, TRUSTVect< _TYPE_, _SIZE_ >::reset(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), IJK_One_Dimensional_Subproblems::set_pure_flux_corrected(), TRUSTVect< _TYPE_, _SIZE_ >::size(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and thermal_subproblems_.
Referenced by compute_thermal_convective_fluxes_face_centre_discrete_integral(), and compute_thermal_diffusive_fluxes_face_centre_discrete_integral().
compute_thermal_flux_face_centre_discrete_integral()
DoubleVect Corrige_flux_FT_temperature_subresolution::compute_thermal_flux_face_centre_discrete_integral (const int fluxes_type, const int & index_subproblem, const double & dist, const int & dir, const int & l = -1)
References convection, diffusion, IJK_One_Dimensional_Subproblems::get_temperature_gradient_times_conductivity_profile_discrete_integral_at_point(), IJK_One_Dimensional_Subproblems::get_temperature_times_velocity_profile_discrete_integral_at_point(), levels_, and thermal_subproblems_.
Referenced by compute_cell_neighbours_thermal_fluxes_face_centre_discrete_integral(), and compute_thermal_fluxes_face_centre_discrete_integral().
get_discrete_surface_at_level()
void Corrige_flux_FT_temperature_subresolution::get_discrete_surface_at_level (const int & dir, const int & level)
clean()
void Corrige_flux_FT_temperature_subresolution::clean () override virtual
Reimplemented from Corrige_flux_FT_base.
References has_checked_consistency_, Corrige_flux_FT_base::intersection_ijk_cell_, and Intersection_Interface_ijk_cell::set_pas_a_jour().
compute_ijk_pure_faces_indices()
void Corrige_flux_FT_temperature_subresolution::compute_ijk_pure_faces_indices () override virtual
Reimplemented from Corrige_flux_FT_base.
References convective_fluxes_, diffusive_fluxes_, Intersection_Interface_ijk_cell::get_ijk_pure_face_neighbours(), Intersection_Interface_ijk_cell::get_nb_faces_to_correct(), ijk_faces_to_correct_, ijk_intersections_subproblems_indices_, Corrige_flux_FT_base::intersection_ijk_cell_, TRUSTVect< _TYPE_, _SIZE_ >::resize(), TRUSTVect< _TYPE_, _SIZE_ >::size(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
sort_ijk_intersections_subproblems_indices_by_k_layers()
void Corrige_flux_FT_temperature_subresolution::sort_ijk_intersections_subproblems_indices_by_k_layers () override virtual
Reimplemented from Corrige_flux_FT_base.
References convection_negligible_, convective_diffusive_flux_xyz_remaining_global_sorted_, convective_diffusive_flux_xyz_sorted_, convective_fluxes_, diffusion_negligible_, diffusive_fluxes_, flux_frontier_map_, flux_init_, index_face_ij_flux_xyz_remaining_global_sorted_, index_face_ij_flux_xyz_sorted_, and sort_ijk_intersections_subproblems_indices_fluxes_by_k_layers().
sort_ijk_intersections_subproblems_indices_fluxes_by_k_layers()
void Corrige_flux_FT_temperature_subresolution::sort_ijk_intersections_subproblems_indices_fluxes_by_k_layers (FixedVector< FixedVector< std::vector< ArrOfInt >, 3 >, 2 > & index_face_ij_flux_xyz, FixedVector< FixedVector< std::vector< ArrOfInt >, 3 >, 2 > & index_face_ij_flux_xyz_remaining_global, FixedVector< std::vector< ArrOfDouble >, 3 > & flux_xyz, FixedVector< std::vector< ArrOfDouble >, 3 > & flux_xyz_remaining_global, FixedVector< std::map< int, int >, 3 > & flux_frontier_map, const DoubleVect & fluxes_subgrid, const int ini_index)
References TRUSTArray< _TYPE_, _SIZE_ >::append_array(), combine_fluxes_from_frontier_on_procs(), debug_, get_linear_index_local(), Domaine_IJK::get_nb_elem_tot(), Domaine_IJK::get_offset_local(), ijk_faces_to_correct_, initialise_any_cell_neighbours_indices_to_correct_with_flux(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), Process::nproc(), receive_fluxes_from_frontier_on_procs(), and Corrige_flux_FT_base::ref_ijk_ft_.
Referenced by sort_ijk_intersections_subproblems_indices_by_k_layers().
get_linear_index_local()
int Corrige_flux_FT_temperature_subresolution::get_linear_index_local (const int & i, const int & j, const int & k, const int & dir)
References Corrige_flux_FT_base::ref_ijk_ft_.
Referenced by combine_fluxes_from_frontier_on_procs(), and sort_ijk_intersections_subproblems_indices_fluxes_by_k_layers().
get_linear_index_global()
int Corrige_flux_FT_temperature_subresolution::get_linear_index_global (const int & i, const int & j, const int & k, const int & dir)
References Domaine_IJK::get_nb_elem_tot(), and Corrige_flux_FT_base::ref_ijk_ft_.
Referenced by compute_flux_neighbours_on_procs().
receive_fluxes_from_frontier_on_procs()
void Corrige_flux_FT_temperature_subresolution::receive_fluxes_from_frontier_on_procs (FixedVector< FixedVector< std::vector< ArrOfInt >, 3 >, 2 > & index_face_ij_flux_xyz_remaining_global, FixedVector< std::vector< ArrOfDouble >, 3 > & flux_xyz_remaining_global, const int ini_index)
References Process::check_int_overflow(), copy_fluxes_on_every_procs_, debug_, Process::me(), Process::mp_sum(), Process::nproc(), TRUSTArray< _TYPE_, _SIZE_ >::resize(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by sort_ijk_intersections_subproblems_indices_fluxes_by_k_layers().
combine_fluxes_from_frontier_on_procs()
void Corrige_flux_FT_temperature_subresolution::combine_fluxes_from_frontier_on_procs (FixedVector< FixedVector< std::vector< ArrOfInt >, 3 >, 2 > & index_face_ij_flux_xyz, FixedVector< FixedVector< std::vector< ArrOfInt >, 3 >, 2 > & index_face_ij_flux_xyz_remaining_global, FixedVector< std::vector< ArrOfDouble >, 3 > & flux_xyz, FixedVector< std::vector< ArrOfDouble >, 3 > & flux_xyz_remaining_global, FixedVector< std::map< int, int >, 3 > & flux_frontier_map, const int ini_index)
References get_linear_index_local(), Domaine_IJK::get_offset_local(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), and Corrige_flux_FT_base::ref_ijk_ft_.
Referenced by sort_ijk_intersections_subproblems_indices_fluxes_by_k_layers().
initialise_any_cell_neighbours_indices_to_correct_on_processors()
void Corrige_flux_FT_temperature_subresolution::initialise_any_cell_neighbours_indices_to_correct_on_processors (FixedVector< FixedVector< std::vector< std::vector< ArrOfInt > >, 3 >, 2 > & index_face_ij_flux_xyz, FixedVector< std::vector< std::vector< ArrOfDouble > >, 3 > & flux_xyz, const int ini_index)
References Process::nproc().
redistribute_indices_fluxes_by_k_layers()
void Corrige_flux_FT_temperature_subresolution::redistribute_indices_fluxes_by_k_layers (FixedVector< FixedVector< std::vector< ArrOfInt >, 3 >, 2 > & index_face_i_flux_x, FixedVector< FixedVector< std::vector< ArrOfInt >, 3 >, 2 > & index_face_i_flux_x_remaining_global, FixedVector< std::vector< ArrOfDouble >, 3 > & flux_xyz, FixedVector< std::vector< ArrOfDouble >, 3 > & flux_xyz_remaining_global, const int ini_index)
store_cell_faces_corrected()
void Corrige_flux_FT_temperature_subresolution::store_cell_faces_corrected (IJK_Field_vector3_int & cell_faces_corrected_bool, IJK_Field_vector3_double & cell_faces_corrected_convective, IJK_Field_vector3_double & cell_faces_corrected_diffusive) override virtual
Reimplemented from Corrige_flux_FT_base.
References convection_negligible_, convective_diffusive_flux_xyz_sorted_, convective_fluxes_, diffusion_negligible_, diffusive_fluxes_, index_face_ij_flux_xyz_sorted_, store_any_cell_faces_corrected(), and use_reachable_fluxes_.
store_any_cell_faces_corrected()
void Corrige_flux_FT_temperature_subresolution::store_any_cell_faces_corrected (IJK_Field_vector3_int & cell_faces_corrected_bool, FixedVector< FixedVector< std::vector< ArrOfInt >, 3 >, 2 > & index_face_ij_flux_xyz_sorted, IJK_Field_vector3_double & cell_faces_corrected, const DoubleVect & fluxes, FixedVector< std::vector< ArrOfDouble >, 3 > & flux_xyz, const int counter)
References ijk_faces_to_correct_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), Process::nproc(), and Corrige_flux_FT_base::ref_ijk_ft_.
Referenced by store_cell_faces_corrected().
check_pure_fluxes_duplicates()
void Corrige_flux_FT_temperature_subresolution::check_pure_fluxes_duplicates (const DoubleVect & fluxes, DoubleVect & fluxes_unique, IntVect & pure_face_unique, const int known_unique)
References TRUSTArray< _TYPE_, _SIZE_ >::append_array(), dist_, ijk_faces_to_correct_, TRUSTVect< _TYPE_, _SIZE_ >::reset(), and TRUSTVect< _TYPE_, _SIZE_ >::size().
clear_vectors()
void Corrige_flux_FT_temperature_subresolution::clear_vectors () override virtual
Reimplemented from Corrige_flux_FT_base.
References clear_std_vectors_array_of_double(), clear_std_vectors_array_of_int(), colinearity_flux_xyz_neighbours_all_faces_remaining_global_sorted_, convective_diffusive_flux_all_faces_remaining_global_sorted_, convective_diffusive_flux_xyz_min_max_faces_sorted_, convective_diffusive_flux_xyz_remaining_global_sorted_, convective_diffusive_flux_xyz_sorted_, convective_flux_correction_, diffusive_flux_correction_, flux_frontier_all_map_, flux_frontier_map_, flux_outside_frontier_all_map_, index_face_ij_flux_xyz_neighbours_all_faces_remaining_global_sorted_, index_face_ij_flux_xyz_neighbours_all_faces_sorted_, index_face_ij_flux_xyz_neighbours_diag_faces_sorted_, index_face_ij_flux_xyz_neighbours_min_max_faces_sorted_, index_face_ij_flux_xyz_remaining_global_sorted_, index_face_ij_flux_xyz_sorted_, indices_temperature_neighbours_on_procs_, neighbours_colinearity_weighting_, neighbours_weighting_colinearity_on_procs_, TRUSTArray< _TYPE_, _SIZE_ >::reset(), store_flux_operators_for_energy_balance_, temperature_flux_all_faces_remaining_global_sorted_, temperature_neighbours_on_procs_, and weighting_flux_xyz_neighbours_all_faces_remaining_global_sorted_.
clear_std_vectors_array_of_int()
void Corrige_flux_FT_temperature_subresolution::clear_std_vectors_array_of_int (std::vector< ArrOfInt > & indices_to_clear)
Referenced by clear_vectors().
clear_std_vectors_array_of_double()
void Corrige_flux_FT_temperature_subresolution::clear_std_vectors_array_of_double (std::vector< ArrOfDouble > & values_to_clear)
Referenced by clear_vectors().
compute_min_max_ijk_reachable_fluxes()
void Corrige_flux_FT_temperature_subresolution::compute_min_max_ijk_reachable_fluxes (const IJK_Field_vector3_int & cell_faces_neighbours_corrected_all_bool, const IJK_Field_int & neighbours_temperature_to_correct, IJK_Field_vector3_int & cell_faces_neighbours_corrected_min_max_bool, const int & max_flux_per_dir, const int & check_cell_center_neighbour, const int & remove_external_neighbour_values, IJK_Field_int & neighbours_temperature_to_correct_trimmed) override virtual
Reimplemented from Corrige_flux_FT_base.
References distance_cell_faces_from_lrs_, IJK_Field_vector< T, N >::echange_espace_virtuel(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel(), find_reachable_fluxes_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost(), keep_first_reachable_fluxes_, and remove_min_max_ijk_reachable_fluxes_discontinuous().
compute_min_max_ijk_any_reachable_fluxes()
void Corrige_flux_FT_temperature_subresolution::compute_min_max_ijk_any_reachable_fluxes (const IJK_Field_vector3_int & cell_faces_neighbours_corrected_all_bool, const IJK_Field_int & neighbours_temperature_to_correct, IJK_Field_vector3_int & cell_faces_neighbours_corrected_min_max_bool, const int & max_flux_per_dir, const int & check_cell_center_neighbour, const int & remove_external_neighbour_values, IJK_Field_int & neighbours_temperature_to_correct_trimmed) override virtual
Reimplemented from Corrige_flux_FT_base.
References TRUSTArray< _TYPE_, _SIZE_ >::append_array(), distance_cell_faces_from_lrs_, IJK_Field_vector< T, N >::echange_espace_virtuel(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel(), find_reachable_fluxes_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost(), keep_first_reachable_fluxes_, Corrige_flux_FT_base::ref_ijk_ft_, remove_min_max_ijk_reachable_fluxes_discontinuous(), remove_non_overlapping_fluxes_values(), TRUSTArray< _TYPE_, _SIZE_ >::reset(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and sort_ini_end_arrays().
sort_ini_end_arrays() [1/2]
void Corrige_flux_FT_temperature_subresolution::sort_ini_end_arrays (ArrOfInt & indices_found_transition_ini, ArrOfInt & indices_found_transition_end, ArrOfInt & indices_found_ini, ArrOfInt & indices_found_end, FixedVector< ArrOfInt, 2 > & indices_sorted, const int & max_n_layer)
Referenced by compute_min_max_ijk_any_reachable_fluxes().
sort_ini_end_arrays() [2/2]
void Corrige_flux_FT_temperature_subresolution::sort_ini_end_arrays (ArrOfInt & indices_found_ini, ArrOfInt & indices_found_end, FixedVector< ArrOfInt, 2 > & indices_sorted, const int & max_n_layer)
References TRUSTArray< _TYPE_, _SIZE_ >::size_array().
remove_non_overlapping_fluxes_values()
void Corrige_flux_FT_temperature_subresolution::remove_non_overlapping_fluxes_values (const FixedVector< ArrOfInt, 2 > & indices_sorted, const FixedVector< ArrOfInt, 2 > & indices_fluxes_sorted, ArrOfInt & indices_to_remove, ArrOfInt & indices_fluxes_to_remove, int & index_bis, int & index_ter, const int & dir)
References TRUSTArray< _TYPE_, _SIZE_ >::append_array(), and Corrige_flux_FT_base::ref_ijk_ft_.
Referenced by compute_min_max_ijk_any_reachable_fluxes().
remove_min_max_ijk_reachable_fluxes_discontinuous()
void Corrige_flux_FT_temperature_subresolution::remove_min_max_ijk_reachable_fluxes_discontinuous (const IJK_Field_vector3_int & cell_faces_neighbours_corrected_all_bool, FixedVector< IJK_Field_local_int, 3 > & cell_faces_neighbours_corrected_min_max_bool)
References eulerian_normal_vectors_ns_normed_.
Referenced by compute_min_max_ijk_any_reachable_fluxes(), and compute_min_max_ijk_reachable_fluxes().
Member Data Documentation
info_obj
const Type_info Corrige_flux_FT_temperature_subresolution::info_obj static
dist_
DoubleVect Corrige_flux_FT_temperature_subresolution::dist_ protected
Referenced by check_pure_fluxes_duplicates(), compute_thermal_fluxes_face_centre(), and compute_thermal_fluxes_face_centre_discrete_integral().
pure_face_unique_
IntVect Corrige_flux_FT_temperature_subresolution::pure_face_unique_ protected
convective_fluxes_
DoubleVect Corrige_flux_FT_temperature_subresolution::convective_fluxes_ protected
Referenced by complete_thermal_fluxes_face_centre(), compute_ijk_pure_faces_indices(), compute_thermal_convective_fluxes_face_centre(), compute_thermal_convective_fluxes_face_centre_discrete_integral(), sort_ijk_intersections_subproblems_indices_by_k_layers(), and store_cell_faces_corrected().
convective_fluxes_unique_
DoubleVect Corrige_flux_FT_temperature_subresolution::convective_fluxes_unique_ protected
diffusive_fluxes_
DoubleVect Corrige_flux_FT_temperature_subresolution::diffusive_fluxes_ protected
Referenced by complete_thermal_fluxes_face_centre(), compute_ijk_pure_faces_indices(), compute_thermal_diffusive_fluxes_face_centre(), compute_thermal_diffusive_fluxes_face_centre_discrete_integral(), sort_ijk_intersections_subproblems_indices_by_k_layers(), and store_cell_faces_corrected().
diffusive_fluxes_unique_
DoubleVect Corrige_flux_FT_temperature_subresolution::diffusive_fluxes_unique_ protected
thermal_subproblems_
IJK_One_Dimensional_Subproblems* Corrige_flux_FT_temperature_subresolution::thermal_subproblems_ = nullptr protected
Referenced by associate_indices_and_check_subproblems_consistency(), associate_thermal_problems(), complete_thermal_fluxes_face_centre(), compute_cell_neighbours_faces_indices_for_spherical_correction(), compute_cell_neighbours_faces_indices_to_correct(), compute_temperature_cell_centre(), compute_temperature_cell_centre_neighbours(), compute_thermal_flux_face_centre(), compute_thermal_flux_face_centre_discrete_integral(), compute_thermal_fluxes_face_centre(), compute_thermal_fluxes_face_centre_discrete_integral(), replace_temperature_cell_centre_neighbours(), and set_zero_temperature_increment().
has_checked_consistency_
bool Corrige_flux_FT_temperature_subresolution::has_checked_consistency_ = false protected
Referenced by associate_indices_and_check_subproblems_consistency(), and clean().
ijk_intersections_subproblems_indices_
ArrOfInt Corrige_flux_FT_temperature_subresolution::ijk_intersections_subproblems_indices_ protected
Referenced by associate_indices_and_check_subproblems_consistency(), complete_thermal_fluxes_face_centre(), compute_cell_neighbours_faces_indices_for_spherical_correction(), compute_cell_neighbours_faces_indices_to_correct(), compute_ijk_pure_faces_indices(), compute_temperature_cell_centre(), compute_temperature_cell_centre_neighbours(), compute_thermal_fluxes_face_centre(), and compute_thermal_fluxes_face_centre_discrete_integral().
indices_temperature_neighbours_on_procs_
FixedVector<ArrOfInt,3> Corrige_flux_FT_temperature_subresolution::indices_temperature_neighbours_on_procs_ protected
Referenced by clear_vectors(), combine_temperature_cell_centre_neighbours_from_procs(), compute_temperature_cell_centre_neighbours_on_procs(), and receive_temperature_cell_centre_neighbours_from_procs().
temperature_neighbours_on_procs_
ArrOfDouble Corrige_flux_FT_temperature_subresolution::temperature_neighbours_on_procs_ protected
Referenced by clear_vectors(), combine_temperature_cell_centre_neighbours_from_procs(), compute_temperature_cell_centre_neighbours_on_procs(), and receive_temperature_cell_centre_neighbours_from_procs().
neighbours_weighting_colinearity_on_procs_
ArrOfDouble Corrige_flux_FT_temperature_subresolution::neighbours_weighting_colinearity_on_procs_ protected
Referenced by clear_vectors(), combine_temperature_cell_centre_neighbours_from_procs(), compute_temperature_cell_centre_neighbours_on_procs(), and receive_temperature_cell_centre_neighbours_from_procs().
index_face_ij_flux_xyz_sorted_
FixedVector<FixedVector<std::vector<ArrOfInt>,3>,2> Corrige_flux_FT_temperature_subresolution::index_face_ij_flux_xyz_sorted_ protected
Referenced by clear_vectors(), corrige_flux_diff_faceIJ(), corrige_flux_faceIJ(), sort_ijk_intersections_subproblems_indices_by_k_layers(), and store_cell_faces_corrected().
convective_diffusive_flux_xyz_sorted_
FixedVector<FixedVector<std::vector<ArrOfDouble>,3>,2> Corrige_flux_FT_temperature_subresolution::convective_diffusive_flux_xyz_sorted_ protected
Referenced by clear_vectors(), corrige_flux_diff_faceIJ(), corrige_flux_faceIJ(), sort_ijk_intersections_subproblems_indices_by_k_layers(), and store_cell_faces_corrected().
index_face_ij_flux_xyz_remaining_global_sorted_
FixedVector<FixedVector<std::vector<ArrOfInt>,3>,2> Corrige_flux_FT_temperature_subresolution::index_face_ij_flux_xyz_remaining_global_sorted_ protected
Referenced by clear_vectors(), and sort_ijk_intersections_subproblems_indices_by_k_layers().
convective_diffusive_flux_xyz_remaining_global_sorted_
FixedVector<FixedVector<std::vector<ArrOfDouble>,3>,2> Corrige_flux_FT_temperature_subresolution::convective_diffusive_flux_xyz_remaining_global_sorted_ protected
Referenced by clear_vectors(), and sort_ijk_intersections_subproblems_indices_by_k_layers().
flux_frontier_map_
FixedVector<std::map<int, int>, 3> Corrige_flux_FT_temperature_subresolution::flux_frontier_map_ protected
Referenced by clear_vectors(), and sort_ijk_intersections_subproblems_indices_by_k_layers().
ijk_faces_to_correct_
FixedVector<IntVect,4> Corrige_flux_FT_temperature_subresolution::ijk_faces_to_correct_ protected
Referenced by check_pure_fluxes_duplicates(), compute_ijk_pure_faces_indices(), sort_ijk_intersections_subproblems_indices_fluxes_by_k_layers(), and store_any_cell_faces_corrected().
index_face_ij_flux_xyz_neighbours_diag_faces_sorted_
FixedVector<FixedVector<std::vector<ArrOfInt>,3>,2> Corrige_flux_FT_temperature_subresolution::index_face_ij_flux_xyz_neighbours_diag_faces_sorted_ protected
Referenced by clear_vectors(), compute_cell_neighbours_faces_indices_for_spherical_correction(), and initialise_cell_neighbours_indices_to_correct().
index_face_ij_flux_xyz_neighbours_all_faces_sorted_
FixedVector<FixedVector<std::vector<ArrOfInt>,3>,2> Corrige_flux_FT_temperature_subresolution::index_face_ij_flux_xyz_neighbours_all_faces_sorted_ protected
Referenced by clear_vectors().
index_face_ij_flux_xyz_neighbours_min_max_faces_sorted_
FixedVector<FixedVector<std::vector<ArrOfInt>,3>,2> Corrige_flux_FT_temperature_subresolution::index_face_ij_flux_xyz_neighbours_min_max_faces_sorted_ protected
Referenced by clear_vectors(), corrige_flux_diff_faceIJ(), corrige_flux_faceIJ(), initialise_cell_neighbours_indices_to_correct(), and replace_cell_neighbours_thermal_fluxes_faces().
convective_diffusive_flux_xyz_min_max_faces_sorted_
FixedVector<FixedVector<std::vector<ArrOfDouble>,3>,2> Corrige_flux_FT_temperature_subresolution::convective_diffusive_flux_xyz_min_max_faces_sorted_ protected
Referenced by clear_vectors(), corrige_flux_diff_faceIJ(), corrige_flux_faceIJ(), initialise_cell_neighbours_indices_to_correct(), and replace_cell_neighbours_thermal_convective_diffusive_fluxes_faces().
index_face_ij_flux_xyz_neighbours_all_faces_remaining_global_sorted_
FixedVector<FixedVector<std::vector<ArrOfInt>,3>,2> Corrige_flux_FT_temperature_subresolution::index_face_ij_flux_xyz_neighbours_all_faces_remaining_global_sorted_ protected
Referenced by clear_vectors(), combine_all_fluxes_from_outisde_frontier_on_procs(), compute_flux_neighbours_on_procs(), initialise_cell_neighbours_indices_to_correct(), and receive_all_fluxes_from_outisde_frontier_on_procs().
weighting_flux_xyz_neighbours_all_faces_remaining_global_sorted_
FixedVector<std::vector<ArrOfInt>,3> Corrige_flux_FT_temperature_subresolution::weighting_flux_xyz_neighbours_all_faces_remaining_global_sorted_ protected
Referenced by clear_vectors(), combine_all_fluxes_from_outisde_frontier_on_procs(), compute_flux_neighbours_on_procs(), initialise_cell_neighbours_indices_to_correct(), and receive_all_fluxes_from_outisde_frontier_on_procs().
colinearity_flux_xyz_neighbours_all_faces_remaining_global_sorted_
FixedVector<std::vector<ArrOfDouble>,3> Corrige_flux_FT_temperature_subresolution::colinearity_flux_xyz_neighbours_all_faces_remaining_global_sorted_ protected
Referenced by clear_vectors(), combine_all_fluxes_from_outisde_frontier_on_procs(), compute_flux_neighbours_on_procs(), initialise_cell_neighbours_indices_to_correct(), and receive_all_fluxes_from_outisde_frontier_on_procs().
temperature_flux_all_faces_remaining_global_sorted_
FixedVector<std::vector<ArrOfDouble>,3> Corrige_flux_FT_temperature_subresolution::temperature_flux_all_faces_remaining_global_sorted_ protected
Referenced by clear_vectors(), combine_all_fluxes_from_outisde_frontier_on_procs(), compute_flux_neighbours_on_procs(), initialise_cell_neighbours_indices_to_correct(), and receive_all_fluxes_from_outisde_frontier_on_procs().
convective_diffusive_flux_all_faces_remaining_global_sorted_
FixedVector<FixedVector<std::vector<ArrOfDouble>,3>,2> Corrige_flux_FT_temperature_subresolution::convective_diffusive_flux_all_faces_remaining_global_sorted_ protected
Referenced by clear_vectors(), combine_all_fluxes_from_outisde_frontier_on_procs(), compute_flux_neighbours_on_procs(), initialise_cell_neighbours_indices_to_correct(), and receive_all_fluxes_from_outisde_frontier_on_procs().
flux_frontier_all_map_
FixedVector<std::map<int, int>, 3> Corrige_flux_FT_temperature_subresolution::flux_frontier_all_map_ protected
Referenced by clear_vectors().
flux_outside_frontier_all_map_
FixedVector<std::map<int, int>, 3> Corrige_flux_FT_temperature_subresolution::flux_outside_frontier_all_map_ protected
Referenced by clear_vectors(), and compute_flux_neighbours_on_procs().
convection_negligible_
int Corrige_flux_FT_temperature_subresolution::convection_negligible_ = 0 protected
Referenced by initialise_cell_neighbours_indices_to_correct(), replace_cell_neighbours_thermal_convective_diffusive_fluxes_faces(), set_convection_negligible(), sort_ijk_intersections_subproblems_indices_by_k_layers(), store_cell_faces_corrected(), and update_intersections().
diffusion_negligible_
int Corrige_flux_FT_temperature_subresolution::diffusion_negligible_ = 0 protected
Referenced by initialise_cell_neighbours_indices_to_correct(), replace_cell_neighbours_thermal_convective_diffusive_fluxes_faces(), set_diffusion_negligible(), sort_ijk_intersections_subproblems_indices_by_k_layers(), store_cell_faces_corrected(), and update_intersections().
debug_
int Corrige_flux_FT_temperature_subresolution::debug_ = 0 protected
Referenced by compute_cell_neighbours_faces_indices_to_correct(), compute_temperature_cell_centre(), receive_all_fluxes_from_outisde_frontier_on_procs(), receive_fluxes_from_frontier_on_procs(), replace_cell_neighbours_thermal_convective_diffusive_fluxes_faces(), replace_temperature_cell_centre_neighbours(), set_debug(), smooth_temperature_cell_centre_neighbours(), and sort_ijk_intersections_subproblems_indices_fluxes_by_k_layers().
levels_
int Corrige_flux_FT_temperature_subresolution::levels_ = 0 protected
Referenced by compute_thermal_flux_face_centre_discrete_integral(), and set_fluxes_feedback_params().
discrete_integral_
int Corrige_flux_FT_temperature_subresolution::discrete_integral_ = 0 protected
Referenced by compute_cell_neighbours_convective_fluxes_to_correct(), compute_cell_neighbours_diffusive_fluxes_to_correct(), compute_thermal_convective_fluxes(), compute_thermal_diffusive_fluxes(), and set_fluxes_feedback_params().
flux_init_
bool Corrige_flux_FT_temperature_subresolution::flux_init_ = false protected
Referenced by initialise_cell_neighbours_indices_to_correct(), and sort_ijk_intersections_subproblems_indices_by_k_layers().
distance_cell_faces_from_lrs_
int Corrige_flux_FT_temperature_subresolution::distance_cell_faces_from_lrs_ = 0 protected
Referenced by compute_cell_neighbours_faces_indices_for_spherical_correction(), compute_cell_neighbours_faces_indices_to_correct(), compute_cell_neighbours_mixed_cell_faces_indices_to_correct(), compute_min_max_ijk_any_reachable_fluxes(), compute_min_max_ijk_reachable_fluxes(), compute_temperature_cell_centre(), compute_temperature_cell_centre_neighbours(), compute_thermal_fluxes_face_centre(), compute_thermal_fluxes_face_centre_discrete_integral(), initialise_cell_neighbours_indices_to_correct(), replace_temperature_cell_centre_neighbours(), and set_distance_cell_faces_from_lrs().
find_temperature_cell_neighbours_
int Corrige_flux_FT_temperature_subresolution::find_temperature_cell_neighbours_ = 0 protected
Referenced by compute_temperature_cell_centre_neighbours(), initialise_cell_neighbours_indices_to_correct(), replace_temperature_cell_centre_neighbours(), and set_correction_cell_neighbours().
find_cell_neighbours_for_fluxes_spherical_correction_
int Corrige_flux_FT_temperature_subresolution::find_cell_neighbours_for_fluxes_spherical_correction_ = 0 protected
Referenced by compute_cell_neighbours_faces_indices_for_spherical_correction(), initialise_cell_neighbours_indices_to_correct(), and set_correction_cell_faces_neighbours().
use_cell_neighbours_for_fluxes_spherical_correction_
int Corrige_flux_FT_temperature_subresolution::use_cell_neighbours_for_fluxes_spherical_correction_ = 0 protected
Referenced by correct_flux_spherical(), and set_correction_cell_faces_neighbours().
neighbours_colinearity_weighting_
int Corrige_flux_FT_temperature_subresolution::neighbours_colinearity_weighting_ = 0 protected
Referenced by clear_vectors(), combine_all_fluxes_from_outisde_frontier_on_procs(), combine_temperature_cell_centre_neighbours_from_procs(), complete_neighbours_and_weighting_colinearity(), compute_cell_neighbours_faces_indices_to_correct(), compute_cell_neighbours_fluxes_to_correct(), compute_cell_neighbours_mixed_cell_faces_indices_to_correct(), compute_cell_neighbours_thermal_fluxes_face_centre(), compute_cell_neighbours_thermal_fluxes_face_centre_discrete_integral(), compute_flux_neighbours_on_procs(), compute_temperature_cell_centre_neighbours(), compute_temperature_cell_centre_neighbours_on_procs(), receive_all_fluxes_from_outisde_frontier_on_procs(), receive_temperature_cell_centre_neighbours_from_procs(), replace_temperature_cell_centre_neighbours(), and set_correction_cell_neighbours().
keep_max_flux_correction_
int Corrige_flux_FT_temperature_subresolution::keep_max_flux_correction_ = 0 protected
Referenced by complete_neighbours_and_weighting_colinearity(), get_add_replace_flux_value(), and set_correction_cell_neighbours().
find_reachable_fluxes_
int Corrige_flux_FT_temperature_subresolution::find_reachable_fluxes_ = 0 protected
Referenced by compute_cell_neighbours_faces_indices_to_correct(), compute_cell_neighbours_mixed_cell_faces_indices_to_correct(), compute_min_max_ijk_any_reachable_fluxes(), compute_min_max_ijk_reachable_fluxes(), initialise_cell_neighbours_indices_to_correct(), and set_correction_cell_faces_neighbours().
use_reachable_fluxes_
int Corrige_flux_FT_temperature_subresolution::use_reachable_fluxes_ = 0 protected
Referenced by combine_all_fluxes_from_outisde_frontier_on_procs(), compute_cell_neighbours_faces_indices_to_correct(), compute_cell_neighbours_fluxes_to_correct(), compute_cell_neighbours_mixed_cell_faces_indices_to_correct(), compute_flux_neighbours_on_procs(), corrige_flux_diff_faceIJ(), corrige_flux_faceIJ(), initialise_cell_neighbours_indices_to_correct(), receive_all_fluxes_from_outisde_frontier_on_procs(), replace_cell_neighbours_thermal_convective_diffusive_fluxes_faces(), set_correction_cell_faces_neighbours(), and store_cell_faces_corrected().
keep_first_reachable_fluxes_
int Corrige_flux_FT_temperature_subresolution::keep_first_reachable_fluxes_ = 0 protected
Referenced by compute_cell_neighbours_mixed_cell_faces_indices_to_correct(), compute_min_max_ijk_any_reachable_fluxes(), compute_min_max_ijk_reachable_fluxes(), replace_cell_neighbours_thermal_fluxes_faces(), and set_correction_cell_faces_neighbours().
cell_faces_neighbours_corrected_bool_
IJK_Field_vector3_int* Corrige_flux_FT_temperature_subresolution::cell_faces_neighbours_corrected_bool_ = nullptr protected
Referenced by compute_cell_neighbours_faces_indices_for_spherical_correction(), and set_cell_faces_neighbours_corrected_bool().
eulerian_normal_vectors_ns_normed_
const IJK_Field_vector3_double* Corrige_flux_FT_temperature_subresolution::eulerian_normal_vectors_ns_normed_ = nullptr protected
Referenced by correct_flux_spherical(), remove_min_max_ijk_reachable_fluxes_discontinuous(), and set_eulerian_normal_vectors_ns_normed().
store_flux_operators_for_energy_balance_
int Corrige_flux_FT_temperature_subresolution::store_flux_operators_for_energy_balance_ = 0 protected
Referenced by clear_vectors(), combine_all_fluxes_from_outisde_frontier_on_procs(), complete_neighbours_and_weighting_colinearity(), compute_cell_neighbours_faces_indices_to_correct(), compute_cell_neighbours_fluxes_to_correct(), compute_cell_neighbours_mixed_cell_faces_indices_to_correct(), compute_flux_neighbours_on_procs(), initialise_any_cell_neighbours_indices_to_correct_with_flux(), receive_all_fluxes_from_outisde_frontier_on_procs(), and set_correction_cell_faces_neighbours().
convective_flux_correction_
int Corrige_flux_FT_temperature_subresolution::convective_flux_correction_ = 0 protected
Referenced by clear_vectors(), combine_all_fluxes_from_outisde_frontier_on_procs(), complete_neighbours_and_weighting_colinearity(), compute_cell_neighbours_faces_indices_to_correct(), compute_cell_neighbours_fluxes_to_correct(), compute_cell_neighbours_mixed_cell_faces_indices_to_correct(), compute_flux_neighbours_on_procs(), corrige_flux_faceIJ(), receive_all_fluxes_from_outisde_frontier_on_procs(), and set_convection_diffusion_correction().
diffusive_flux_correction_
int Corrige_flux_FT_temperature_subresolution::diffusive_flux_correction_ = 0 protected
Referenced by clear_vectors(), combine_all_fluxes_from_outisde_frontier_on_procs(), complete_neighbours_and_weighting_colinearity(), complete_thermal_fluxes_face_centre(), compute_cell_neighbours_faces_indices_to_correct(), compute_cell_neighbours_fluxes_to_correct(), compute_cell_neighbours_mixed_cell_faces_indices_to_correct(), compute_flux_neighbours_on_procs(), corrige_flux_diff_faceIJ(), receive_all_fluxes_from_outisde_frontier_on_procs(), and set_convection_diffusion_correction().
smooth_temperature_field_
int Corrige_flux_FT_temperature_subresolution::smooth_temperature_field_ = 0 protected
Referenced by replace_temperature_cell_centre_neighbours(), set_correction_cell_neighbours(), and smooth_temperature_cell_centre_neighbours().
copy_fluxes_on_every_procs_
int Corrige_flux_FT_temperature_subresolution::copy_fluxes_on_every_procs_ = 1 protected
Referenced by receive_all_fluxes_from_outisde_frontier_on_procs(), receive_fluxes_from_frontier_on_procs(), and set_temperature_fluxes_periodic_sharing_strategy_on_processors().
copy_temperature_on_every_procs_
int Corrige_flux_FT_temperature_subresolution::copy_temperature_on_every_procs_ = 1 protected
Referenced by combine_temperature_cell_centre_neighbours_from_procs(), receive_temperature_cell_centre_neighbours_from_procs(), and set_temperature_fluxes_periodic_sharing_strategy_on_processors().