TrioCFD: Triple_Line_Model_FT_Disc Class Reference
Triple_Line_Model_FT_Disc Class Reference
#include <Triple_Line_Model_FT_Disc.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Member Enumeration Documentation
InoutMethod
enum Triple_Line_Model_FT_Disc::InoutMethod
Enumerator
EXACT
APPROX
BOTH
Constructor & Destructor Documentation
~Triple_Line_Model_FT_Disc()
Triple_Line_Model_FT_Disc::~Triple_Line_Model_FT_Disc ()
Triple_Line_Model_FT_Disc()
Triple_Line_Model_FT_Disc::Triple_Line_Model_FT_Disc ()
Member Function Documentation
cree_instance()
Objet_U * Triple_Line_Model_FT_Disc::cree_instance () static
taille_memoire()
unsigned Triple_Line_Model_FT_Disc::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Triple_Line_Model_FT_Disc::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Triple_Line_Model_FT_Disc::info () static
get_info()
const Type_info * Triple_Line_Model_FT_Disc::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
Triple_Line_Model_FT_Disc & Triple_Line_Model_FT_Disc::self_cast (Objet_U & r) static
self_cast() [2/2]
const Triple_Line_Model_FT_Disc & Triple_Line_Model_FT_Disc::self_cast (const Objet_U & r) static
printOn()
Sortie & Triple_Line_Model_FT_Disc::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
References Param::print(), and Objet_U::que_suis_je().
readOn()
Entree & Triple_Line_Model_FT_Disc::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
References activated_, TRUSTArray< _TYPE_, _SIZE_ >::append_array(), deactivate_, Process::exit(), Lec_Diffuse_base::get(), Param::lire_avec_accolades_depuis(), nb_colon_tab_, Nom_ficher_tcl_, LecFicDiffuse::ouvrir(), Objet_U::que_suis_je(), read_via_file_, TRUSTTab< _TYPE_, _SIZE_ >::resize(), set_param(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and tab_Mtcl_.
associer_pb()
void Triple_Line_Model_FT_Disc::associer_pb (const Probleme_base & pb)
References pb_base_.
Referenced by Probleme_FT_Disc_gen::lire_equations().
initialize()
void Triple_Line_Model_FT_Disc::initialize ()
References boundary_faces_, elems_, Maillage_FT_Disc::get_mesh_tag(), Transport_Interfaces_FT_Disc::maillage_interface(), mp_, nom_eq_hydr_, nom_eq_interf_, nom_eq_therm_, TRUST_Ref< _CLASSE_ >::non_nul(), pb_base_, Q_, ref_eq_interf_, ref_eq_temp_, ref_ns_, TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), tag_tcl_, and TRUST_Ref< _CLASSE_ >::valeur().
completer()
void Triple_Line_Model_FT_Disc::completer ()
References Milieu_base::capacite_calorifique(), Milieu_base::conductivite(), Domaine_VDF::dist_face_elem0(), Equation_base::domaine_Cl_dis(), Equation_base::domaine_dis(), Process::exit(), Domaine_VF::face_voisins(), kl_cond_, Domaine_Cl_dis_base::les_conditions_limites(), Milieu_base::masse_volumique(), Process::mp_max(), n_ext_meso_, Domaine_Cl_dis_base::nb_cond_lim(), Frontiere_32_64< _SIZE_ >::nb_faces(), Frontiere_32_64< _SIZE_ >::num_premiere_face(), Rc_inject_, Rc_tcl_GridN_, ref_eq_temp_, ref_ns_, reinjection_tcl(), rhocpl_, TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), Champ_Proto::valeurs(), and ymeso_.
Referenced by Probleme_FT_Disc_gen::completer().
set_param()
void Triple_Line_Model_FT_Disc::set_param (Param & p)
References Param::ajouter(), Param::ajouter_flag(), APPROX, BOTH, capillary_effect_on_theta_activated_, deactivate_, Param::dictionnaire(), distri_first_facette_, EXACT, initial_CL_xcoord_, inout_method_, lv_, n_ext_meso_, nb_colon_tab_, nom_eq_hydr_, nom_eq_interf_, nom_eq_therm_, Nom_ficher_tcl_, num_colon_app_, num_colon_qtcl_, num_colon_tem_, Qtcl_, Rc_tcl_GridN_, read_via_file_, reinjection_tcl_, Param::REQUIRED, sm_, TCL_energy_correction_, tempC_tcl_, theta_app_, thetaC_tcl_, ym_, and ymeso_.
Referenced by readOn().
get_Qtcl()
double Triple_Line_Model_FT_Disc::get_Qtcl (const int num_face)
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), num_colon_qtcl_, num_colon_tem_, Qtcl_, read_via_file_, ref_eq_temp_, tab_Mtcl_, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by compute_TCL_fluxes_in_all_boundary_cells().
get_lv()
const double & Triple_Line_Model_FT_Disc::get_lv () const inline
References lv_.
Referenced by Maillage_FT_Disc::calcul_courbure_sommets().
get_ym()
const double & Triple_Line_Model_FT_Disc::get_ym () const inline
References ym_.
get_sm()
double Triple_Line_Model_FT_Disc::get_sm () inline
References sm_.
get_initial_CL_xcoord()
const double & Triple_Line_Model_FT_Disc::get_initial_CL_xcoord () const inline
References initial_CL_xcoord_.
get_rhocpl()
const double & Triple_Line_Model_FT_Disc::get_rhocpl () const inline
References rhocpl_.
is_activated()
const bool & Triple_Line_Model_FT_Disc::is_activated () const inline
References activated_.
Referenced by Maillage_FT_Disc::calcul_courbure_sommets(), Probleme_FT_Disc_gen::completer(), Echange_contact_VDF_FT_Disc::completer(), Convection_Diffusion_Temperature_FT_Disc::derivee_en_temps_inco(), and Echange_contact_VDF_FT_Disc_solid::mettre_a_jour().
is_capillary_activated()
const int & Triple_Line_Model_FT_Disc::is_capillary_activated () const inline
References capillary_effect_on_theta_activated_.
Referenced by Maillage_FT_Disc::calcul_courbure_sommets().
is_read_via_file()
const int & Triple_Line_Model_FT_Disc::is_read_via_file () const inline
References read_via_file_.
Referenced by Maillage_FT_Disc::calcul_courbure_sommets().
Rc_tcl_GridN()
const int & Triple_Line_Model_FT_Disc::Rc_tcl_GridN () const inline
References Rc_tcl_GridN_.
Referenced by get_theta_app().
Rc_inject()
const double & Triple_Line_Model_FT_Disc::Rc_inject () const inline
References Rc_inject_.
Referenced by Transport_Interfaces_FT_Disc::mettre_a_jour(), and Echange_contact_VDF_FT_Disc::mettre_a_jour().
thetaC_tcl()
const double & Triple_Line_Model_FT_Disc::thetaC_tcl () const inline
References thetaC_tcl_.
Referenced by get_theta_app(), and Transport_Interfaces_FT_Disc::mettre_a_jour().
reinjection_tcl()
const int & Triple_Line_Model_FT_Disc::reinjection_tcl () const inline
References reinjection_tcl_.
Referenced by completer(), get_theta_app(), Transport_Interfaces_FT_Disc::mettre_a_jour(), and Echange_contact_VDF_FT_Disc::mettre_a_jour().
distri_first_facette()
const int & Triple_Line_Model_FT_Disc::distri_first_facette () const inline
References distri_first_facette_.
Referenced by compute_TCL_fluxes_in_all_boundary_cells().
ready_inject_tcl() [1/2]
const bool & Triple_Line_Model_FT_Disc::ready_inject_tcl () const inline
References ready_inject_tcl_.
Referenced by Transport_Interfaces_FT_Disc::mettre_a_jour(), and Echange_contact_VDF_FT_Disc::mettre_a_jour().
ready_inject_tcl() [2/2]
bool & Triple_Line_Model_FT_Disc::ready_inject_tcl () inline
References ready_inject_tcl_.
tempC_tcl()
const double & Triple_Line_Model_FT_Disc::tempC_tcl () const inline
References tempC_tcl_.
Referenced by Echange_contact_VDF_FT_Disc::mettre_a_jour().
tag_tcl()
const int & Triple_Line_Model_FT_Disc::tag_tcl () const inline
References tag_tcl_.
Referenced by boundary_faces(), Convection_Diffusion_Temperature_FT_Disc::derivee_en_temps_inco(), and elems().
compute_capillary_number()
double Triple_Line_Model_FT_Disc::compute_capillary_number () const
get_any_tcl_face()
int Triple_Line_Model_FT_Disc::get_any_tcl_face () const
References Transport_Interfaces_FT_Disc::maillage_interface(), Maillage_FT_Disc::nb_sommets(), ref_eq_interf_, Maillage_FT_Disc::sommet_face_bord(), Maillage_FT_Disc::sommet_ligne_contact(), Maillage_FT_Disc::sommet_virtuel(), and TRUST_Ref< _CLASSE_ >::valeur().
get_in_out_coords()
void Triple_Line_Model_FT_Disc::get_in_out_coords (const Domaine_VDF & zvdf, const int elem, const double dt, DoubleTab & in_out, FTd_vecteur3 & norm_elem, double & surface_tot)
References Intersections_Elem_Facettes_Data::barycentre_, Intersections_Elem_Facettes::data_intersection(), Domaine_VDF::dim_elem(), Objet_U::dimension, Process::exit(), Maillage_FT_Disc::facettes(), Intersections_Elem_Facettes_Data::fraction_surface_intersection_, Maillage_FT_Disc::get_update_normale_facettes(), Maillage_FT_Disc::get_update_surface_facettes(), Intersections_Elem_Facettes::index_elem(), Intersections_Elem_Facettes_Data::index_facette_suivante_, Maillage_FT_Disc::intersections_elem_facettes(), Transport_Interfaces_FT_Disc::maillage_interface(), Intersections_Elem_Facettes_Data::numero_facette_, Objet_U::precision_geom, Objet_U::que_suis_je(), ref_eq_interf_, TRUSTTab< _TYPE_, _SIZE_ >::resize(), Maillage_FT_Disc::sommets(), TRUST_Ref< _CLASSE_ >::valeur(), and Domaine_VF::xp().
Referenced by compute_TCL_fluxes_in_all_boundary_cells().
compute_approximate_interface_inout()
void Triple_Line_Model_FT_Disc::compute_approximate_interface_inout (const Domaine_VDF & zvdf, const int korient, const int elem, const int num_face, DoubleTab & in_out, FTd_vecteur3 & norm_elem, double & surface_tot) const
References Intersections_Elem_Facettes_Data::barycentre_, Intersections_Elem_Facettes::data_intersection(), Domaine_VDF::dim_elem(), Objet_U::dimension, Process::exit(), Maillage_FT_Disc::facettes(), Intersections_Elem_Facettes_Data::fraction_surface_intersection_, Maillage_FT_Disc::get_update_normale_facettes(), Maillage_FT_Disc::get_update_surface_facettes(), Intersections_Elem_Facettes::index_elem(), Intersections_Elem_Facettes_Data::index_facette_suivante_, Maillage_FT_Disc::intersections_elem_facettes(), Intersections_Elem_Facettes_Data::numero_facette_, ref_eq_interf_, TRUSTTab< _TYPE_, _SIZE_ >::resize(), Maillage_FT_Disc::sommets(), and Domaine_VF::xp().
Referenced by compute_TCL_fluxes_in_all_boundary_cells().
compute_local_cos_theta()
double Triple_Line_Model_FT_Disc::compute_local_cos_theta (const Parcours_interface & parcours, const int num_face, const FTd_vecteur3 & norm_elem) const
References Parcours_interface::calculer_normale_face_bord(), and Objet_U::dimension.
Referenced by compute_TCL_fluxes_in_all_boundary_cells().
compute_Qint()
double Triple_Line_Model_FT_Disc::compute_Qint (const DoubleTab & in_out, const double theta_app_locs, const int num_face, double & Qmeso) const
References Maillage_FT_Disc::angle_bidim_axi(), Objet_U::bidim_axi, kl_cond_, ref_eq_temp_, ym_, and ymeso_.
Referenced by compute_TCL_fluxes_in_all_boundary_cells().
compute_TCL_fluxes_in_all_boundary_cells()
void Triple_Line_Model_FT_Disc::compute_TCL_fluxes_in_all_boundary_cells (ArrOfInt & elems_with_CL_contrib, ArrOfInt & faces_with_CL_contrib, ArrOfDouble & mpoint_from_CL, ArrOfDouble & Q_from_CL)
References Maillage_FT_Disc::angle_bidim_axi(), TRUSTArray< _TYPE_, _SIZE_ >::append_array(), APPROX, Objet_U::bidim_axi, boundary_faces_, Fluide_Diphasique::chaleur_latente(), compute_approximate_interface_inout(), compute_local_cos_theta(), compute_Qint(), Intersections_Elem_Facettes::data_intersection(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Domaine_VDF::dist_face_elem0(), distri_first_facette(), Equation_base::domaine_Cl_dis(), Equation_base::domaine_dis(), Domaine_VF::elem_faces(), elems_, EXACT, Process::exit(), Domaine_VF::face_voisins(), Maillage_FT_Disc::facettes(), Navier_Stokes_FT_Disc::fluide_diphasique(), Fluide_Diphasique::fluide_phase(), Intersections_Elem_Facettes_Data::fraction_surface_intersection_, get_in_out_coords(), Maillage_FT_Disc::get_mesh_tag(), get_Qtcl(), Transport_Interfaces_FT_Disc::inconnue(), Intersections_Elem_Facettes::index_elem(), Intersections_Elem_Facettes_Data::index_element_suivant_, Intersections_Elem_Facettes::index_facette(), Intersections_Elem_Facettes_Data::index_facette_suivante_, inout_method_, instant_mmeso_evap_, instant_mmicro_evap_, instant_vmeso_evap_, instant_vmicro_evap_, integrated_vmeso_evap_, integration_time_, Maillage_FT_Disc::intersections_elem_facettes(), Process::je_suis_maitre(), Objet_U_ptr::le_nom(), Domaine_Cl_dis_base::les_conditions_limites(), Transport_Interfaces_FT_Disc::maillage_interface(), Milieu_base::masse_volumique(), mp_, Process::mp_sum(), Domaine_Cl_dis_base::nb_cond_lim(), Frontiere_32_64< _SIZE_ >::nb_faces(), Frontiere_32_64< _SIZE_ >::num_premiere_face(), Intersections_Elem_Facettes_Data::numero_element_, Intersections_Elem_Facettes_Data::numero_facette_, Domaine_VDF::orientation(), Transport_Interfaces_FT_Disc::parcours_interface(), Schema_Temps_base::pas_de_temps(), Objet_U::precision_geom, Q_, Objet_U::que_suis_je(), ref_eq_interf_, ref_ns_, TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), Equation_base::schema_temps(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), sm_, Maillage_FT_Disc::sommet_ligne_contact(), Maillage_FT_Disc::sommets(), tag_tcl_, Schema_Temps_base::temps_courant(), TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_Inc_base::valeurs(), Champ_Proto::valeurs(), vevap_int_, Domaine_VF::volumes(), x_cl_, Domaine_VF::xp(), Domaine_VF::xv(), ym_, and ymeso_.
Referenced by Probleme_FT_Disc_gen::updateGivenFields().
corriger_mpoint()
void Triple_Line_Model_FT_Disc::corriger_mpoint (DoubleTab & mpoint) const
References elems_, mp_, and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by Convection_Diffusion_Temperature_FT_Disc::derivee_en_temps_inco().
corriger_secmem()
void Triple_Line_Model_FT_Disc::corriger_secmem (const double coef, DoubleTab & secmem2) const
References elems_, Q_, and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
correct_wall_adjacent_temperature_according_to_TCL_fluxes()
void Triple_Line_Model_FT_Disc::correct_wall_adjacent_temperature_according_to_TCL_fluxes (DoubleTab & temperature) const
References boundary_faces_, elems_, kl_cond_, ref_eq_temp_, and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
set_wall_adjacent_temperature_according_to_TCL_model()
void Triple_Line_Model_FT_Disc::set_wall_adjacent_temperature_according_to_TCL_model (DoubleTab & temperature) const
References boundary_faces_, elems_, ref_eq_temp_, and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by Convection_Diffusion_Temperature_FT_Disc::derivee_en_temps_inco().
correct_TCL_energy_evolution()
void Triple_Line_Model_FT_Disc::correct_TCL_energy_evolution (DoubleTab & temperature) const
References Process::exit(), ref_eq_temp_, rhocpl_, TCL_energy_correction_, and Domaine_VF::volumes().
get_theta_app()
double Triple_Line_Model_FT_Disc::get_theta_app (const int num_face)
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Domaine_VDF::dist_face_elem0(), Equation_base::domaine_dis(), Domaine_VF::elem_faces(), Process::exit(), Domaine_VF::face_voisins(), Domaine_Cl_VDF::la_cl_de_la_face(), num_colon_app_, num_colon_tem_, Front_VF::num_premiere_face(), Domaine_VDF::orientation(), Rc_tcl_GridN(), read_via_file_, ref_eq_temp_, ref_ns_, reinjection_tcl(), Echange_impose_base::T_ext(), tab_Mtcl_, theta_app_, thetaC_tcl(), Echange_contact_VDF_FT_Disc::Ti_wall(), TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), and Domaine_VF::xv().
Referenced by Maillage_FT_Disc::calcul_courbure_sommets().
elems() [1/2]
ArrOfInt & Triple_Line_Model_FT_Disc::elems () inline
References elems_, Process::exit(), Maillage_FT_Disc::get_mesh_tag(), Transport_Interfaces_FT_Disc::maillage_interface(), ref_eq_interf_, tag_tcl(), and TRUST_Ref< _CLASSE_ >::valeur().
elems() [2/2]
const ArrOfInt & Triple_Line_Model_FT_Disc::elems () const inline
References elems_, ref_eq_interf_, and tag_tcl().
boundary_faces() [1/2]
ArrOfInt & Triple_Line_Model_FT_Disc::boundary_faces () inline
References boundary_faces_.
boundary_faces() [2/2]
const ArrOfInt & Triple_Line_Model_FT_Disc::boundary_faces () const inline
References boundary_faces_, ref_eq_interf_, and tag_tcl().
mp() [1/2]
ArrOfDouble & Triple_Line_Model_FT_Disc::mp () inline
References mp_.
mp() [2/2]
const ArrOfDouble & Triple_Line_Model_FT_Disc::mp () const inline
References mp_.
Q() [1/2]
ArrOfDouble & Triple_Line_Model_FT_Disc::Q () inline
References Q_.
Referenced by Echange_contact_VDF_FT_Disc::mettre_a_jour().
Q() [2/2]
const ArrOfDouble & Triple_Line_Model_FT_Disc::Q () const inline
References Q_.
Member Data Documentation
info_obj
const Type_info Triple_Line_Model_FT_Disc::info_obj static
activated_
bool Triple_Line_Model_FT_Disc::activated_ protected
Referenced by is_activated(), and readOn().
deactivate_
int Triple_Line_Model_FT_Disc::deactivate_ protected
Referenced by readOn(), and set_param().
capillary_effect_on_theta_activated_
int Triple_Line_Model_FT_Disc::capillary_effect_on_theta_activated_ protected
Referenced by is_capillary_activated(), and set_param().
TCL_energy_correction_
int Triple_Line_Model_FT_Disc::TCL_energy_correction_ protected
Referenced by correct_TCL_energy_evolution(), and set_param().
n_ext_meso_
int Triple_Line_Model_FT_Disc::n_ext_meso_ protected
Referenced by completer(), and set_param().
tag_tcl_
int Triple_Line_Model_FT_Disc::tag_tcl_ protected
Referenced by compute_TCL_fluxes_in_all_boundary_cells(), initialize(), and tag_tcl().
Qtcl_
double Triple_Line_Model_FT_Disc::Qtcl_ protected
Referenced by get_Qtcl(), and set_param().
lv_
double Triple_Line_Model_FT_Disc::lv_ protected
Referenced by get_lv(), and set_param().
theta_app_
double Triple_Line_Model_FT_Disc::theta_app_ protected
Referenced by get_theta_app(), and set_param().
x_cl_
double Triple_Line_Model_FT_Disc::x_cl_ protected
Referenced by compute_TCL_fluxes_in_all_boundary_cells().
ym_
double Triple_Line_Model_FT_Disc::ym_ protected
Referenced by compute_Qint(), compute_TCL_fluxes_in_all_boundary_cells(), get_ym(), and set_param().
sm_
double Triple_Line_Model_FT_Disc::sm_ protected
Referenced by compute_TCL_fluxes_in_all_boundary_cells(), get_sm(), and set_param().
ymeso_
double Triple_Line_Model_FT_Disc::ymeso_ protected
Referenced by completer(), compute_Qint(), compute_TCL_fluxes_in_all_boundary_cells(), and set_param().
initial_CL_xcoord_
double Triple_Line_Model_FT_Disc::initial_CL_xcoord_ protected
Referenced by get_initial_CL_xcoord(), and set_param().
kl_cond_
double Triple_Line_Model_FT_Disc::kl_cond_ protected
Referenced by completer(), compute_Qint(), and correct_wall_adjacent_temperature_according_to_TCL_fluxes().
rhocpl_
double Triple_Line_Model_FT_Disc::rhocpl_ protected
Referenced by completer(), correct_TCL_energy_evolution(), and get_rhocpl().
inout_method_
int Triple_Line_Model_FT_Disc::inout_method_ = 0 protected
Referenced by compute_TCL_fluxes_in_all_boundary_cells(), and set_param().
read_via_file_
int Triple_Line_Model_FT_Disc::read_via_file_ protected
Referenced by get_Qtcl(), get_theta_app(), is_read_via_file(), readOn(), and set_param().
Nom_ficher_tcl_
Nom Triple_Line_Model_FT_Disc::Nom_ficher_tcl_ protected
Referenced by readOn(), and set_param().
tab_Mtcl_
DoubleTab Triple_Line_Model_FT_Disc::tab_Mtcl_ protected
Referenced by get_Qtcl(), get_theta_app(), and readOn().
nb_colon_tab_
int Triple_Line_Model_FT_Disc::nb_colon_tab_ protected
Referenced by readOn(), and set_param().
num_colon_tem_
int Triple_Line_Model_FT_Disc::num_colon_tem_ protected
Referenced by get_Qtcl(), get_theta_app(), and set_param().
num_colon_app_
int Triple_Line_Model_FT_Disc::num_colon_app_ protected
Referenced by get_theta_app(), and set_param().
num_colon_qtcl_
int Triple_Line_Model_FT_Disc::num_colon_qtcl_ protected
Referenced by get_Qtcl(), and set_param().
Rc_tcl_GridN_
int Triple_Line_Model_FT_Disc::Rc_tcl_GridN_ protected
Referenced by completer(), Rc_tcl_GridN(), and set_param().
Rc_inject_
double Triple_Line_Model_FT_Disc::Rc_inject_ protected
Referenced by completer(), and Rc_inject().
thetaC_tcl_
double Triple_Line_Model_FT_Disc::thetaC_tcl_ protected
Referenced by set_param(), and thetaC_tcl().
reinjection_tcl_
int Triple_Line_Model_FT_Disc::reinjection_tcl_ protected
Referenced by reinjection_tcl(), and set_param().
tempC_tcl_
double Triple_Line_Model_FT_Disc::tempC_tcl_ protected
Referenced by set_param(), and tempC_tcl().
ready_inject_tcl_
bool Triple_Line_Model_FT_Disc::ready_inject_tcl_ protected
Referenced by ready_inject_tcl().
distri_first_facette_
int Triple_Line_Model_FT_Disc::distri_first_facette_ protected
Referenced by distri_first_facette(), and set_param().
elems_
ArrOfInt Triple_Line_Model_FT_Disc::elems_ protected
Referenced by compute_TCL_fluxes_in_all_boundary_cells(), correct_wall_adjacent_temperature_according_to_TCL_fluxes(), corriger_mpoint(), corriger_secmem(), elems(), initialize(), and set_wall_adjacent_temperature_according_to_TCL_model().
boundary_faces_
ArrOfInt Triple_Line_Model_FT_Disc::boundary_faces_ protected
Referenced by boundary_faces(), compute_TCL_fluxes_in_all_boundary_cells(), correct_wall_adjacent_temperature_according_to_TCL_fluxes(), initialize(), and set_wall_adjacent_temperature_according_to_TCL_model().
mp_
ArrOfDouble Triple_Line_Model_FT_Disc::mp_ protected
Referenced by compute_TCL_fluxes_in_all_boundary_cells(), corriger_mpoint(), initialize(), and mp().
Q_
ArrOfDouble Triple_Line_Model_FT_Disc::Q_ protected
Referenced by compute_TCL_fluxes_in_all_boundary_cells(), corriger_secmem(), initialize(), and Q().
integration_time_
double Triple_Line_Model_FT_Disc::integration_time_ protected
Referenced by compute_TCL_fluxes_in_all_boundary_cells().
instant_mmicro_evap_
double Triple_Line_Model_FT_Disc::instant_mmicro_evap_ protected
Referenced by compute_TCL_fluxes_in_all_boundary_cells().
instant_mmeso_evap_
double Triple_Line_Model_FT_Disc::instant_mmeso_evap_ protected
Referenced by compute_TCL_fluxes_in_all_boundary_cells().
instant_vmicro_evap_
double Triple_Line_Model_FT_Disc::instant_vmicro_evap_ protected
Referenced by compute_TCL_fluxes_in_all_boundary_cells().
instant_vmeso_evap_
double Triple_Line_Model_FT_Disc::instant_vmeso_evap_ protected
Referenced by compute_TCL_fluxes_in_all_boundary_cells().
integrated_m_evap_
double Triple_Line_Model_FT_Disc::integrated_m_evap_ protected
integrated_vmicro_evap_
double Triple_Line_Model_FT_Disc::integrated_vmicro_evap_ protected
integrated_vmeso_evap_
double Triple_Line_Model_FT_Disc::integrated_vmeso_evap_ protected
Referenced by compute_TCL_fluxes_in_all_boundary_cells().
vevap_int_
double Triple_Line_Model_FT_Disc::vevap_int_ protected
Referenced by compute_TCL_fluxes_in_all_boundary_cells().
nom_eq_hydr_
Nom Triple_Line_Model_FT_Disc::nom_eq_hydr_ protected
Referenced by initialize(), and set_param().
nom_eq_therm_
Nom Triple_Line_Model_FT_Disc::nom_eq_therm_ protected
Referenced by initialize(), and set_param().
nom_eq_interf_
Nom Triple_Line_Model_FT_Disc::nom_eq_interf_ protected
Referenced by initialize(), and set_param().
pb_base_
TRUST_Ref< Probleme_base *> Triple_Line_Model_FT_Disc::pb_base_ protected
Referenced by associer_pb(), and initialize().
ref_eq_temp_
TRUST_Ref< Convection_Diffusion_Temperature_FT_Disc *> Triple_Line_Model_FT_Disc::ref_eq_temp_ protected
Referenced by completer(), compute_Qint(), correct_TCL_energy_evolution(), correct_wall_adjacent_temperature_according_to_TCL_fluxes(), get_Qtcl(), get_theta_app(), initialize(), and set_wall_adjacent_temperature_according_to_TCL_model().
ref_eq_interf_
TRUST_Ref< Transport_Interfaces_FT_Disc *> Triple_Line_Model_FT_Disc::ref_eq_interf_ protected
Referenced by boundary_faces(), compute_approximate_interface_inout(), compute_TCL_fluxes_in_all_boundary_cells(), elems(), get_any_tcl_face(), get_in_out_coords(), and initialize().
ref_ns_
TRUST_Ref< Navier_Stokes_FT_Disc *> Triple_Line_Model_FT_Disc::ref_ns_ protected
Referenced by completer(), compute_TCL_fluxes_in_all_boundary_cells(), get_theta_app(), and initialize().