TrioCFD: Operateur_IJK_data_channel Class Reference
Operateur_IJK_data_channel Class Reference
#include <Operateur_IJK_data_channel.h>
Member Function Documentation
initialize()
void Operateur_IJK_data_channel::initialize (const Domaine_IJK & splitting)
References delta_x_, delta_y_, delta_z_, first_global_k_layer_flux(), Domaine_IJK::get_constant_delta(), Domaine_IJK::get_local_mesh_delta(), Domaine_IJK::get_nb_elem_tot(), Domaine_IJK::get_offset_local(), Domaine_IJK::get_periodic_flag(), inv_delta_x_, inv_delta_y_, inv_dist_z_elemcenter_, inv_elem_size_z_, Domaine_IJK::is_uniform(), last_global_k_layer_flux(), nb_elem_k_tot_, offset_to_global_k_layer_, perio_k_, IJKArray_with_ghost< _TYPE_, _TYPE_ARRAY_ >::resize(), IJKArray_with_ghost< _TYPE_, _TYPE_ARRAY_ >::size(), and uniform_k_.
Referenced by Operateur_IJK_faces_conv_base_double::initialize(), Operateur_IJK_elem_conv_base_double::initialize(), Operateur_IJK_elem_diff_base_double::initialize(), and Operateur_IJK_faces_diff_base_double::initialize().
nb_elem_k_tot()
int Operateur_IJK_data_channel::nb_elem_k_tot () const inline
References nb_elem_k_tot_.
first_global_k_layer_flux()
int Operateur_IJK_data_channel::first_global_k_layer_flux (int icompo, int idir) const inline
Referenced by initialize(), OpConvCentre2IJK_double::initialize(), and OpConvCentre4IJK_double::initialize().
last_global_k_layer_flux()
int Operateur_IJK_data_channel::last_global_k_layer_flux (int icompo, int idir) const inline
References nb_elem_k_tot_.
Referenced by initialize(), OpConvCentre2IJK_double::initialize(), and OpConvCentre4IJK_double::initialize().
offset_to_global_k_layer()
int Operateur_IJK_data_channel::offset_to_global_k_layer () const inline
References offset_to_global_k_layer_.
Referenced by OpConvCentre2IJK_double::initialize(), and OpConvCentre4IJK_double::initialize().
get_surface()
double Operateur_IJK_data_channel::get_surface (int k_layer, int compo, int dir) inline
References delta_x_, delta_y_, and delta_z_.
get_surface_leftright()
void Operateur_IJK_data_channel::get_surface_leftright (int k_layer, int compo, int dir, double & left, double & right) inline
References delta_x_, delta_y_, and delta_z_.
inv_distance_for_gradient()
double Operateur_IJK_data_channel::inv_distance_for_gradient (int k_layer, int compo, int dir) inline
References inv_delta_x_, inv_delta_y_, inv_dist_z_elemcenter_, and inv_elem_size_z_.
get_delta_z()
const ArrOfDouble_with_ghost & Operateur_IJK_data_channel::get_delta_z () const inline
References delta_z_.
Referenced by Operateur_IJK_elem_conv_base_double::ajouter(), Operateur_IJK_elem_conv_base_double::calculer(), OpGradCentre2IJKScalar_double::fill_grad_field_z_(), OpGradQuickIJKScalar_double::fill_grad_field_z_(), OpHessCentre2IJKScalar_double::fill_grad_field_z_(), OpConvCentre2IJK_double::initialize(), and OpConvCentre4IJK_double::initialize().
get_delta_x()
double Operateur_IJK_data_channel::get_delta_x () const inline
References delta_x_.
get_delta_y()
double Operateur_IJK_data_channel::get_delta_y () const inline
References delta_y_.
get_delta()
double Operateur_IJK_data_channel::get_delta (int dir, int k_layer = -1) const inline
References delta_x_, delta_y_, delta_z_, and Process::exit().
get_delta_xyz()
double Operateur_IJK_data_channel::get_delta_xyz (int k_layer, int dir) inline
References delta_x_, delta_y_, and delta_z_.
is_k_uniform_and_periodic()
bool Operateur_IJK_data_channel::is_k_uniform_and_periodic () inline
References perio_k_, and uniform_k_.
is_k_periodic()
bool Operateur_IJK_data_channel::is_k_periodic () inline
References perio_k_.
Referenced by OpConvCentre2IJK_double::initialize(), and OpConvCentre4IJK_double::initialize().
Member Data Documentation
nb_elem_k_tot_
int Operateur_IJK_data_channel::nb_elem_k_tot_ protected
Referenced by initialize(), last_global_k_layer_flux(), and nb_elem_k_tot().
offset_to_global_k_layer_
int Operateur_IJK_data_channel::offset_to_global_k_layer_ protected
Referenced by initialize(), and offset_to_global_k_layer().
delta_x_
double Operateur_IJK_data_channel::delta_x_ protected
Referenced by get_delta(), get_delta_x(), get_delta_xyz(), get_surface(), get_surface_leftright(), and initialize().
delta_y_
double Operateur_IJK_data_channel::delta_y_ protected
Referenced by get_delta(), get_delta_xyz(), get_delta_y(), get_surface(), get_surface_leftright(), and initialize().
delta_z_
ArrOfDouble_with_ghost Operateur_IJK_data_channel::delta_z_ protected
Referenced by get_delta(), get_delta_xyz(), get_delta_z(), get_surface(), get_surface_leftright(), and initialize().
inv_delta_x_
double Operateur_IJK_data_channel::inv_delta_x_ protected
Referenced by initialize(), and inv_distance_for_gradient().
inv_delta_y_
double Operateur_IJK_data_channel::inv_delta_y_ protected
Referenced by initialize(), and inv_distance_for_gradient().
inv_elem_size_z_
ArrOfDouble_with_ghost Operateur_IJK_data_channel::inv_elem_size_z_ protected
Referenced by initialize(), and inv_distance_for_gradient().
inv_dist_z_elemcenter_
ArrOfDouble_with_ghost Operateur_IJK_data_channel::inv_dist_z_elemcenter_ protected
Referenced by initialize(), and inv_distance_for_gradient().
uniform_k_
bool Operateur_IJK_data_channel::uniform_k_ protected
Referenced by initialize(), and is_k_uniform_and_periodic().
perio_k_
bool Operateur_IJK_data_channel::perio_k_ protected
Referenced by initialize(), is_k_periodic(), and is_k_uniform_and_periodic().