TrioCFD: Modele_Fonc_Bas_Reynolds_Thermique_Base Class Reference
Modele_Fonc_Bas_Reynolds_Thermique_Base Class Reference abstract
#include <Modele_Fonc_Bas_Reynolds_Thermique_Base.h>
Public Member Functions
const Type_info * get_info () const override
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Modele_Fonc_Bas_Reynolds_Thermique_Base()
Modele_Fonc_Bas_Reynolds_Thermique_Base::Modele_Fonc_Bas_Reynolds_Thermique_Base ()
~Modele_Fonc_Bas_Reynolds_Thermique_Base()
Modele_Fonc_Bas_Reynolds_Thermique_Base::~Modele_Fonc_Bas_Reynolds_Thermique_Base () override
Member Function Documentation
info()
const Type_info * Modele_Fonc_Bas_Reynolds_Thermique_Base::info () static
get_info()
const Type_info * Modele_Fonc_Bas_Reynolds_Thermique_Base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
Modele_Fonc_Bas_Reynolds_Thermique_Base & Modele_Fonc_Bas_Reynolds_Thermique_Base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Modele_Fonc_Bas_Reynolds_Thermique_Base & Modele_Fonc_Bas_Reynolds_Thermique_Base::self_cast (const Objet_U & r) static
printOn()
Sortie & Modele_Fonc_Bas_Reynolds_Thermique_Base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
References Objet_U::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Modele_Fonc_Bas_Reynolds_Thermique_Base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
typer_lire_Modele_Fonc_Bas_Reynolds_Thermique()
void Modele_Fonc_Bas_Reynolds_Thermique_Base::typer_lire_Modele_Fonc_Bas_Reynolds_Thermique (TRUST_Deriv< Modele_Fonc_Bas_Reynolds_Thermique_Base > & mod, const Equation_base & eqn, Entree & is) static
References associer(), associer_eqn(), Equation_base::discretisation(), Equation_base::domaine_Cl_dis(), Equation_base::domaine_dis(), and Objet_U::que_suis_je().
Referenced by Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re::lire_motcle_non_standard().
modele_turbulence_Bas_Re() [1/2]
const Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re & Modele_Fonc_Bas_Reynolds_Thermique_Base::modele_turbulence_Bas_Re () const inline
References mon_modele_turb_Bas_Re, TRUST_Ref< _CLASSE_ >::non_nul(), and TRUST_Ref< _CLASSE_ >::valeur().
modele_turbulence_Bas_Re() [2/2]
Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re & Modele_Fonc_Bas_Reynolds_Thermique_Base::modele_turbulence_Bas_Re () inline
References mon_modele_turb_Bas_Re, TRUST_Ref< _CLASSE_ >::non_nul(), and TRUST_Ref< _CLASSE_ >::valeur().
equation() [1/2]
const Transport_Fluctuation_Temperature_W_Bas_Re & Modele_Fonc_Bas_Reynolds_Thermique_Base::equation () const inline
References mon_equation, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Modele_Jones_Launder_Thermique_VDF::associer_pb().
equation() [2/2]
Transport_Fluctuation_Temperature_W_Bas_Re & Modele_Fonc_Bas_Reynolds_Thermique_Base::equation () inline
References mon_equation, and TRUST_Ref< _CLASSE_ >::valeur().
preparer_calcul()
int Modele_Fonc_Bas_Reynolds_Thermique_Base::preparer_calcul () virtual
mettre_a_jour()
virtual void Modele_Fonc_Bas_Reynolds_Thermique_Base::mettre_a_jour (double) pure virtual
Implemented in Modele_Jones_Launder_Thermique_VDF.
discretiser()
void Modele_Fonc_Bas_Reynolds_Thermique_Base::discretiser () virtual
Referenced by Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re::lire_motcle_non_standard().
completer()
void Modele_Fonc_Bas_Reynolds_Thermique_Base::completer () virtual
associer_pb()
virtual void Modele_Fonc_Bas_Reynolds_Thermique_Base::associer_pb (const Probleme_base &) pure virtual
Implemented in Modele_Jones_Launder_Thermique_VDF.
associer_eqn()
void Modele_Fonc_Bas_Reynolds_Thermique_Base::associer_eqn (const Equation_base & eqn) virtual
References mon_equation.
Referenced by typer_lire_Modele_Fonc_Bas_Reynolds_Thermique().
associer()
virtual void Modele_Fonc_Bas_Reynolds_Thermique_Base::associer (const Domaine_dis_base & , const Domaine_Cl_dis_base &) pure virtual
Implemented in Modele_Jones_Launder_Thermique_VDF.
Referenced by typer_lire_Modele_Fonc_Bas_Reynolds_Thermique().
sauvegarder()
int Modele_Fonc_Bas_Reynolds_Thermique_Base::sauvegarder (Sortie &) const override virtual
Sauvegarde d'un Objet_U sur un flot de sortie Methode a surcharger.
Parameters
(Sortie&) flot de sortie a utiliser pour la sauvegarde
Returns
(int) code de retour
Reimplemented from Objet_U.
reprendre()
int Modele_Fonc_Bas_Reynolds_Thermique_Base::reprendre (Entree &) override virtual
Reprise d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree&) flot d'entree a utiliser pour la reprise
Returns
(int) code de retour
Reimplemented from Objet_U.
Calcul_D()
virtual DoubleTab & Modele_Fonc_Bas_Reynolds_Thermique_Base::Calcul_D (DoubleTab & , const Domaine_dis_base & , const Domaine_Cl_dis_base & , const DoubleTab & , const DoubleTab & , double) const pure virtual
Implemented in Modele_Jones_Launder_Thermique_VDF.
Referenced by Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::ajouter().
Calcul_E()
virtual DoubleTab & Modele_Fonc_Bas_Reynolds_Thermique_Base::Calcul_E (DoubleTab & , const Domaine_dis_base & , const Domaine_Cl_dis_base & , const DoubleTab & , const DoubleTab & , double , const DoubleTab &) const pure virtual
Implemented in Modele_Jones_Launder_Thermique_VDF.
Referenced by Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::ajouter().
Calcul_F1()
virtual DoubleTab & Modele_Fonc_Bas_Reynolds_Thermique_Base::Calcul_F1 (DoubleTab & , const Domaine_dis_base & , const DoubleTab & , const DoubleTab & , double , double) const pure virtual
Implemented in Modele_Jones_Launder_Thermique_VDF.
Referenced by Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::ajouter().
Calcul_F2()
virtual DoubleTab & Modele_Fonc_Bas_Reynolds_Thermique_Base::Calcul_F2 (DoubleTab & , const Domaine_dis_base & , const DoubleTab & , const DoubleTab & , double , double) const pure virtual
Implemented in Modele_Jones_Launder_Thermique_VDF.
Referenced by Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::ajouter().
Calcul_F3()
virtual DoubleTab & Modele_Fonc_Bas_Reynolds_Thermique_Base::Calcul_F3 (DoubleTab & , const Domaine_dis_base & , const DoubleTab & , const DoubleTab & , double , double) const pure virtual
Implemented in Modele_Jones_Launder_Thermique_VDF.
Referenced by Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::ajouter().
Calcul_F4()
virtual DoubleTab & Modele_Fonc_Bas_Reynolds_Thermique_Base::Calcul_F4 (DoubleTab & , const Domaine_dis_base & , const DoubleTab & , const DoubleTab & , double , double) const pure virtual
Implemented in Modele_Jones_Launder_Thermique_VDF.
Referenced by Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::ajouter().
Calcul_Flambda()
virtual DoubleTab & Modele_Fonc_Bas_Reynolds_Thermique_Base::Calcul_Flambda (DoubleTab & , const Domaine_dis_base & , const DoubleTab & , const DoubleTab & , double , double) const pure virtual
Implemented in Modele_Jones_Launder_Thermique_VDF.
Referenced by Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re::calculer_diffusivite_turbulente().
creer_champ()
void Modele_Fonc_Bas_Reynolds_Thermique_Base::creer_champ (const Motcle & motlu) override virtual
Implements Champs_compris_interface.
get_champ()
const Champ_base & Modele_Fonc_Bas_Reynolds_Thermique_Base::get_champ (const Motcle & nom) const override virtual
Implements Champs_compris_interface.
References Champs_compris_T< FIELD_TYPE >::get_champ().
has_champ() [1/2]
bool Modele_Fonc_Bas_Reynolds_Thermique_Base::has_champ (const Motcle & nom, TRUST_Ref< Champ_base * > & ref_champ) const override virtual
Implements Champs_compris_interface.
References Champs_compris_T< FIELD_TYPE >::has_champ().
Referenced by Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re::get_champ(), and Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re::has_champ().
has_champ() [2/2]
bool Modele_Fonc_Bas_Reynolds_Thermique_Base::has_champ (const Motcle & nom) const override virtual
Implements Champs_compris_interface.
References Champs_compris_T< FIELD_TYPE >::has_champ().
get_noms_champs_postraitables()
void Modele_Fonc_Bas_Reynolds_Thermique_Base::get_noms_champs_postraitables (Noms & nom, Option opt = NONE) const override virtual
Implements Champs_compris_interface.
References TRUST_Vector< _CLASSE_ >::add(), and Champs_compris_T< FIELD_TYPE >::liste_noms_compris().
Referenced by Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re::get_noms_champs_postraitables().
Member Data Documentation
info_obj
const Type_info Modele_Fonc_Bas_Reynolds_Thermique_Base::info_obj static
mon_equation
TRUST_Ref< Transport_Fluctuation_Temperature_W_Bas_Re *> Modele_Fonc_Bas_Reynolds_Thermique_Base::mon_equation protected
Referenced by associer_eqn(), and equation().
mon_modele_turb_Bas_Re
TRUST_Ref< Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re *> Modele_Fonc_Bas_Reynolds_Thermique_Base::mon_modele_turb_Bas_Re protected
Referenced by modele_turbulence_Bas_Re().