TrioCFD: Cond_lim_omega_demi Class Reference
Cond_lim_omega_demi Class Reference
#include <Cond_lim_omega_demi.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Dirichlet_loi_paroi
void associer_domaine_cl_dis_base (const Domaine_Cl_dis_base &zcl) override
void associer_fr_dis_base (const Frontiere_dis_base &fr) override
virtual void calculer_coeffs_echange (double temps) override
virtual const Frontiere_dis_base & frontiere_dis () const override
virtual Frontiere_dis_base & frontiere_dis () override
const Type_info * get_info () const override
virtual int initialiser (double temps) override
void mettre_a_jour (double tps) override
virtual double val_imp (int i) const override
virtual double val_imp (int i, int j) const override
void verifie_ch_init_nb_comp () const override
const Type_info * get_info () const override
virtual double val_imp (int i) const
virtual double val_imp (int i, int j) const
void verifie_ch_init_nb_comp () const override
Public Member Functions inherited from Cond_lim_base
virtual int a_mettre_a_jour_ss_pas_dt ()
virtual void associer_domaine_cl_dis_base (const Domaine_Cl_dis_base &)
virtual void associer_fr_dis_base (const Frontiere_dis_base &)
virtual void calculer_coeffs_echange (double temps)
virtual int compatible_avec_discr (const Discretisation_base &) const
Domaine_Cl_dis_base & domaine_Cl_dis ()
const Domaine_Cl_dis_base & domaine_Cl_dis () const
virtual Frontiere_dis_base & frontiere_dis ()
virtual const Frontiere_dis_base & frontiere_dis () const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
void set_modifier_val_imp (int)
virtual void verifie_ch_init_nb_comp () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Cond_lim_base
void err_pas_compatible (const Discretisation_base &) const
void err_pas_compatible (const Equation_base &) const
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Cond_lim_omega_demi()
Cond_lim_omega_demi::Cond_lim_omega_demi ()
~Cond_lim_omega_demi()
Cond_lim_omega_demi::~Cond_lim_omega_demi ()
Member Function Documentation
cree_instance()
Objet_U * Cond_lim_omega_demi::cree_instance () static
taille_memoire()
unsigned Cond_lim_omega_demi::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Cond_lim_omega_demi::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Cond_lim_omega_demi::info () static
get_info()
const Type_info * Cond_lim_omega_demi::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Dirichlet_loi_paroi.
self_cast() [1/2]
Cond_lim_omega_demi & Cond_lim_omega_demi::self_cast (Objet_U & r) static
self_cast() [2/2]
const Cond_lim_omega_demi & Cond_lim_omega_demi::self_cast (const Objet_U & r) static
printOn()
Sortie & Cond_lim_omega_demi::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Dirichlet_loi_paroi.
References Objet_U::que_suis_je().
readOn()
Entree & Cond_lim_omega_demi::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Dirichlet_loi_paroi.
References Param::ajouter(), beta_k, beta_omega, Cond_lim_base::le_champ_front, Param::lire_avec_accolades_depuis(), Objet_U::que_suis_je(), Objet_U_ptr::typer(), and von_karman_.
completer()
void Cond_lim_omega_demi::completer () override virtual
NE FAIT RIEN A surcharger dans les classes derivees.
Reimplemented from Dirichlet_loi_paroi.
References Dirichlet_loi_paroi::correlation_loi_paroi_, Cond_lim_base::domaine_Cl_dis(), MorEqn::equation(), Process::exit(), Probleme_base::get_correlation(), Equation_base::inconnue(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Equation_base::probleme(), Objet_U::que_suis_je(), and Champ_Inc_base::valeurs().
me_calculer()
void Cond_lim_omega_demi::me_calculer () override protected virtual
Implements Dirichlet_loi_paroi.
References calc_omega(), Dirichlet_loi_paroi::correlation_loi_paroi_, Dirichlet_loi_paroi::d_, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Cond_lim_base::domaine_Cl_dis(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Loi_paroi_base::get_tab(), Dirichlet_loi_paroi::la_frontiere_dis, and TRUST_Ref< _CLASSE_ >::valeur().
calc_omega()
double Cond_lim_omega_demi::calc_omega (const double y, const double u_tau, const double visc) const protected
References beta_k, beta_omega, and von_karman_.
Referenced by me_calculer().
Member Data Documentation
info_obj
const Type_info Cond_lim_omega_demi::info_obj static
von_karman_
double Cond_lim_omega_demi::von_karman_ = 0.41 protected
Referenced by calc_omega(), and readOn().
beta_omega
double Cond_lim_omega_demi::beta_omega = 0.075 protected
Referenced by calc_omega(), and readOn().
beta_k
double Cond_lim_omega_demi::beta_k = 0.09 protected
Referenced by calc_omega(), and readOn().