TrioCFD: Maillage_FT_IJK Class Reference
Maillage_FT_IJK Class Reference
#include <Maillage_FT_IJK.h>
Public Member Functions
void deplacer_sommets (const ArrOfInt &liste_sommets_initiale, const DoubleTab &deplacement_initial, ArrOfInt &liste_sommets_sortis, ArrOfInt &numero_face_sortie, int skip_facettes=0) override
const Type_info * get_info () const override
void lire_maillage_ft_dans_lata (const char *filename_with_path, int tstep, const char *geometryname)
void recopie (const Maillage_FT_Disc &source_mesh, Statut_Maillage niveau_copie) override
void transporter (const DoubleTab &deplacement) override
Public Member Functions inherited from Maillage_FT_Disc
void associer_equation_transport (const Equation_base &equation) override
void calcul_indicatrice (DoubleVect &indicatrice, const DoubleVect &indicatrice_precedente)
virtual void calculer_costheta_minmax (DoubleTab &costheta) const
void completer_maillage ()
const ArrOfInt & drapeaux_sommets () const
int facette_virtuelle (int i) const
const IntTab & facettes () const
int facettes_voisines (int fa70, int fa71, int &iarete0, int &iarete1) const
const Type_info * get_info () const override
virtual const ArrOfDouble & get_update_courbure_sommets () const
virtual const DoubleTab & get_update_normale_facettes () const
virtual const ArrOfDouble & get_update_surface_facettes () const
virtual Entree & lire_param_maillage (Entree &is)
int nb_facettes () const
int nb_sommets () const
void parcourir_maillage ()
void preparer_tableau_avant_transport (ArrOfDouble &tableau, const Desc_Structure_FT &descripteur) const
virtual void recopie (const Maillage_FT_Disc &maillage_source, Statut_Maillage niveau_copie)
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
const DoubleTab & sommets () const
void supprimer_facettes (const ArrOfInt &liste_facettes)
double temps () const
virtual void transporter (const DoubleTab &deplacement)
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
void calculer_costheta_minmax (DoubleTab &costheta) const override
void creer_facettes_virtuelles (const ArrOfInt &liste_facettes, const ArrOfInt &liste_pe, const ArrOfInt &facettes_send_pe_list, const ArrOfInt &facettes_recv_pe_list) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Maillage_FT_Disc
void calcul_courbure_sommets (ArrOfDouble &courbure, const int call_number) const
void calcul_surface_normale (ArrOfDouble &surface, DoubleTab &normale) const
void convertir_numero_distant_local (const Desc_Structure_FT &descripteur, const ArrOfInt &element_num_owner, const ArrOfInt &numeros_distants, const ArrOfInt &pe_distant, ArrOfInt &numeros_locaux) const
void corriger_proprietaires_facettes ()
virtual void creer_facettes_virtuelles (const ArrOfInt &liste_facettes, const ArrOfInt &liste_pe, const ArrOfInt &facettes_send_pe_list, const ArrOfInt &facettes_recv_pe_list)
void creer_sommets_virtuels (const ArrOfInt &liste_sommets, const ArrOfInt &liste_pe, const Schema_Comm &comm)
void creer_sommets_virtuels_numowner (const ArrOfInt &request_sommets_pe, const ArrOfInt &request_sommets_num)
virtual void deplacer_sommets (const ArrOfInt &liste_sommets_initiale, const DoubleTab &deplacement_initial, ArrOfInt &liste_sommets_sortis, ArrOfInt &numero_face_sortie, int skip_facettes=0)
void echanger_facettes (const ArrOfInt &liste_facettes, const ArrOfInt &liste_elem_arrivee, ArrOfInt &facettes_recues_numfacettes, ArrOfInt &facettes_recues_numelement)
void echanger_sommets_PE (const ArrOfInt &liste_sommets, const ArrOfInt &liste_elem_virtuel_arrivee, const ArrOfInt &liste_face_virtuelle_arrivee, const DoubleTab &deplacement, ArrOfInt &liste_nouveaux_sommets, DoubleTab &deplacement_restant, int skip_facettes=0)
void maillage_modifie (Statut_Maillage nouveau_statut)
Maillage_FT_Disc_Data_Cache & mesh_data_cache () const
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Maillage_FT_IJK() [1/2]
Maillage_FT_IJK::Maillage_FT_IJK ()
~Maillage_FT_IJK()
Maillage_FT_IJK::~Maillage_FT_IJK ()
Maillage_FT_IJK() [2/2]
Maillage_FT_IJK::Maillage_FT_IJK (const Maillage_FT_IJK &) default
Member Function Documentation
cree_instance()
Objet_U * Maillage_FT_IJK::cree_instance () static
taille_memoire()
unsigned Maillage_FT_IJK::taille_memoire () const override virtual
Reimplemented from Maillage_FT_Disc.
duplique()
int Maillage_FT_IJK::duplique () const override virtual
Reimplemented from Maillage_FT_Disc.
info()
const Type_info * Maillage_FT_IJK::info () static
get_info()
const Type_info * Maillage_FT_IJK::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Maillage_FT_Disc.
self_cast() [1/2]
Maillage_FT_IJK & Maillage_FT_IJK::self_cast (Objet_U & r) static
self_cast() [2/2]
const Maillage_FT_IJK & Maillage_FT_IJK::self_cast (const Objet_U & r) static
printOn()
Sortie & Maillage_FT_IJK::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Maillage_FT_Disc.
References Objet_U::printOn().
readOn()
Entree & Maillage_FT_IJK::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Maillage_FT_Disc.
References Param::ajouter(), Param::lire_avec_accolades(), Objet_U::que_suis_je(), and Surfactant_facettes_.
initialize()
void Maillage_FT_IJK::initialize (const Domaine_IJK & dom, const Domaine_dis_base & domaine_dis, const Parcours_interface & parcours, const bool use_tryggvason_interfacial_source = false)
References Maillage_FT_Disc::associer_domaine_dis_parcours(), Domaine_IJK::get_nb_elem_local(), initialize_processor_neighbourhood(), nbmailles_euler_i_, nbmailles_euler_j_, nbmailles_euler_k_, ref_domaine_, and use_tryggvason_interfacial_source_.
Referenced by IJK_Interfaces::dupliquer_bulle_perio(), and IJK_Interfaces::initialize().
compo_connexe_facettes()
const ArrOfInt & Maillage_FT_IJK::compo_connexe_facettes () const inline
References compo_connexe_facettes_.
Referenced by ajouter_maillage_IJK(), IJK_Interfaces::calculer_aire_interfaciale_for_compo(), IJK_Interfaces::calculer_aspect_ratio(), IJK_Interfaces::calculer_color(), IJK_Interfaces::calculer_distance_autres_compo_connexe_ijk(), IJK_Interfaces::calculer_distance_autres_compo_connexe_octree(), ComputeValParCompoInCell::calculer_indic_elem_pour_compo(), IJK_Interfaces::calculer_indicatrices(), IJK_Interfaces::calculer_indicatrices_optim(), ComputeValParCompoInCell::calculer_moy_field_fa7_par_compo(), ComputeValParCompoInCell::calculer_moy_field_sommet_par_compo(), ComputeValParCompoInCell::calculer_moyennes_interface_element_pour_compo(), IJK_Interfaces::calculer_normales_et_aires_interfaciales(), ComputeValParCompoInCell::calculer_somme_field_sommet_par_compo(), IJK_Interfaces::calculer_surfactant(), IJK_Interfaces::calculer_vecteurs_de_deplacement_rigide(), FT_Field::calculer_volume_bulles(), FT_Field::check_conservation(), FT_Field::completer_compo_connexe_partielle(), IJK_Interfaces::compute_external_forces_(), ComputeValParCompoInCell::compute_list_compo_connex_in_element(), IJK_Interfaces::compute_surface_average_per_bubble(), FT_Field::correction_conservation_globale(), deplacer_sommets(), IJK_Interfaces::detecter_et_supprimer_rejeton(), IJK_Interfaces::dupliquer_bulle_perio(), FT_Field::exchange_compo_connexe(), FT_Field::exchange_data(), IJK_Composantes_Connex::fill_mixed_cell_compo(), IJK_Interfaces::initialize(), FT_Field::initialize(), recopie(), IJK_Interfaces::sauvegarder_interfaces(), IJK_Interfaces::supprimer_certaines_bulles_reelles(), IJK_Interfaces::supprimer_duplicata_bulles(), IJK_Interfaces::transporter_maillage_remaillage(), and FT_Field::update_sigma_and_interfacial_source_term_sommet().
compo_connexe_facettes_non_const()
ArrOfInt & Maillage_FT_IJK::compo_connexe_facettes_non_const () inline
References compo_connexe_facettes_.
Referenced by deplacer_sommets(), Remaillage_FT_IJK::diviser_grandes_aretes(), and Remaillage_FT_IJK::supprimer_petites_aretes().
Surfactant_facettes()
const FT_Field & Maillage_FT_IJK::Surfactant_facettes () const inline
References Surfactant_facettes_.
Referenced by ajouter_maillage_IJK(), IJK_Interfaces::ajouter_terme_source_interfaces(), IJK_Interfaces::calculer_phi_repuls_par_compo(), IJK_Interfaces::calculer_phi_repuls_sommet(), IJK_Interfaces::calculer_surfactant(), IJK_Interfaces::dupliquer_bulle_perio(), IJK_Interfaces::get_IJK_field(), IJK_Interfaces::parcourir_maillage(), recopie(), IJK_Interfaces::remailler_interface(), IJK_Interfaces::transporter_maillage_deformation(), and IJK_Interfaces::transporter_maillage_remaillage().
Surfactant_facettes_non_const()
FT_Field & Maillage_FT_IJK::Surfactant_facettes_non_const () inline
References Surfactant_facettes_.
Referenced by Remaillage_FT_IJK::barycentrer_lisser_apres_remaillage(), Remaillage_FT_IJK::barycentrer_lisser_systematique_ijk(), deplacer_sommets(), Remaillage_FT_IJK::diviser_grandes_aretes(), IJK_Interfaces::dupliquer_bulle_perio(), IJK_Interfaces::initialize(), Remaillage_FT_IJK::remaillage_local_interface(), Remaillage_FT_IJK::supprimer_petites_aretes(), and IJK_Interfaces::transporter_maillage_deformation().
update_gradient_laplacien_Surfactant()
void Maillage_FT_IJK::update_gradient_laplacien_Surfactant () inline
References Surfactant_facettes_, and FT_Field::update_gradient_laplacien_FT().
Referenced by IJK_Interfaces::parcourir_maillage(), and IJK_Interfaces::transporter_maillage_remaillage().
update_sigma_and_interfacial_source_term_sommet()
DoubleTab Maillage_FT_IJK::update_sigma_and_interfacial_source_term_sommet (const Domaine_IJK & splitting, bool compute_interfacial_source, bool use_tryggvason_formulation, const double sigma_const = -1.)
References Operator_FT_Disc::Compute_interfaciale_source(), Process::exit(), FT_Field::get_disable_marangoni_source_term(), FT_Field::get_disable_surfactant(), Maillage_FT_Disc::nb_facettes(), TRUSTArray< _TYPE_, _SIZE_ >::resize(), Surfactant_facettes_, FT_Field::update_sigma_and_interfacial_source_term_sommet(), and use_tryggvason_interfacial_source_.
Referenced by IJK_Interfaces::calculer_phi_repuls_par_compo(), IJK_Interfaces::parcourir_maillage(), and IJK_Interfaces::transporter_maillage_remaillage().
set_Surfactant_facettes()
void Maillage_FT_IJK::set_Surfactant_facettes (ArrOfDouble Surfactant_field)
set_Surfactant_facettes_sommets()
void Maillage_FT_IJK::set_Surfactant_facettes_sommets (ArrOfDouble Surfactant_field)
supprimer_facettes()
void Maillage_FT_IJK::supprimer_facettes (const ArrOfInt & liste_facettes)
References Maillage_FT_Disc::supprimer_facettes().
Referenced by IJK_Interfaces::dupliquer_bulle_perio(), and IJK_Interfaces::supprimer_duplicata_bulles().
nettoyer_maillage()
void Maillage_FT_IJK::nettoyer_maillage () override virtual
Retire toutes les facettes virtuelles, toutes les facettes invalides (sommet0 == sommet1) et tous les sommets qui ne sont pas utilises.
Reimplemented from Maillage_FT_Disc.
References compo_connexe_facettes_, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Maillage_FT_Disc::facette_virtuelle(), Maillage_FT_Disc::facettes_, FT_Field::get_disable_surfactant(), Maillage_FT_Disc::nettoyer_maillage(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), FT_Field::resize_array(), and Surfactant_facettes_.
Referenced by IJK_Interfaces::dupliquer_bulle_perio(), lire_maillage_ft_dans_lata(), and IJK_Interfaces::transporter_maillage_remaillage().
sauv_facette_indexation_avant_transport()
void Maillage_FT_IJK::sauv_facette_indexation_avant_transport ()
References Maillage_FT_Disc::facettes_, indexation_facettes_avant_transport_, Maillage_FT_Disc::nb_facettes(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Maillage_FT_Disc::sommets_, and Surfactant_facettes_.
Referenced by corriger_proprietaires_facettes(), and parcourir_maillage().
corriger_proprietaires_facettes()
void Maillage_FT_IJK::corriger_proprietaires_facettes ()
References Maillage_FT_Disc::corriger_proprietaires_facettes(), FT_Field::get_disable_surfactant(), sauv_facette_indexation_avant_transport(), Surfactant_facettes_, and update_surfactant_apres_transport().
Referenced by Remaillage_FT_IJK::diviser_grandes_aretes(), Remaillage_FT_IJK::remaillage_local_interface(), and Remaillage_FT_IJK::supprimer_petites_aretes().
update_surfactant_apres_transport()
void Maillage_FT_IJK::update_surfactant_apres_transport ()
References compo_connexe_facettes_, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), FT_Field::echange_espace_virtuel(), Maillage_FT_Disc::facette_virtuelle(), Maillage_FT_Disc::facettes_, indexation_facettes_avant_transport_, Maillage_FT_Disc::nb_facettes(), FT_Field::resize(), Maillage_FT_Disc::sommets_, and Surfactant_facettes_.
Referenced by corriger_proprietaires_facettes(), and parcourir_maillage().
parcourir_maillage()
void Maillage_FT_IJK::parcourir_maillage ()
References FT_Field::get_disable_surfactant(), Maillage_FT_Disc::parcourir_maillage(), sauv_facette_indexation_avant_transport(), Surfactant_facettes_, and update_surfactant_apres_transport().
Referenced by IJK_Interfaces::detecter_et_supprimer_rejeton(), and IJK_Interfaces::parcourir_maillage().
transporter()
void Maillage_FT_IJK::transporter (const DoubleTab & deplacement) override virtual
Deplace les sommets de l'interface d'un vecteur "deplacement" fourni, Change eventuellement les sommets de processeur, cree eventuellement.
des lignes de contact et detecte les collisions.
Parameters
(deplacement) un tableau de taille (nb_sommets(), Objet_U::dimension) contenant le vecteur deplacement de chaque sommet. Les deplacements des sommets virtuels sont ignores.
Reimplemented from Maillage_FT_Disc.
References Maillage_FT_Disc::transporter().
Referenced by IJK_Interfaces::deplacer_bulle_perio(), IJK_Interfaces::dupliquer_bulle_perio(), lire_maillage_ft_dans_lata(), IJK_Interfaces::transporter_maillage_deformation(), and IJK_Interfaces::transporter_maillage_rigide().
deplacer_sommets()
void Maillage_FT_IJK::deplacer_sommets (const ArrOfInt & liste_sommets_initiale, const DoubleTab & deplacement_initial, ArrOfInt & liste_sommets_sortis, ArrOfInt & numero_face_sortie, int skip_facettes = 0) override virtual
Applique un vecteur deplacement aux noeuds dont le numero est dans "liste_noeud", puis echange les espaces virtuels.
Si un noeud traverse un joint, il change de proprietaire. Si un noeud rencontre une paroi, il s'arrete sur la paroi et on le transforme en noeud "ligne de contact". Si un noeud est sur une paroi (noeud "ligne de contact"), il longe la paroi (on deplace le noeud de face de bord en face de bord en minimisant la distance entre le noeud et le deplacement demande.
Parameters
(liste_sommets_initiale) une liste non redondante de noeuds REELS a deplacer
(deplacement_initial) le vecteur deplacement des noeuds de "liste_noeuds" (dimension(0)==liste_noeuds.size_array() et dimension(1)==dimension)
Reimplemented from Maillage_FT_Disc.
References TRUSTArray< _TYPE_, _SIZE_ >::append_array(), FT_Field::calculer_normale_apres_deplacement(), FT_Field::champ_sommet_from_facettes(), Comm_Group::check_enabled(), Process::check_int_overflow(), check_mesh(), FT_Field::completer_compo_connexe_partielle(), compo_connexe_facettes(), compo_connexe_facettes_non_const(), Maillage_FT_Disc::creer_sommets_virtuels(), Maillage_FT_Disc::desc_sommets_, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), during_barycentrage_, Desc_Structure_FT::echange_espace_virtuel(), FT_Field::echange_espace_virtuel(), Desc_Structure_FT::echanger_elements(), Domaine_IJK::ELEM, Process::exit(), FT_Field::get_compo_connexe_sommets(), FT_Field::get_disable_surfactant(), FT_Field::get_facettes_sommets_full_compo_non_const(), get_ijk_cell_index(), FT_Field::get_liste_sommets_et_deplacements_non_const(), FT_Field::get_sorted_index(), Maillage_FT_Disc::get_surface_facettes(), liste_processeurs_voisins_aretes_, liste_processeurs_voisins_coins_, liste_processeurs_voisins_faces_, Process::me(), Process::mp_max(), Process::mp_sum(), nbmailles_euler_i_, nbmailles_euler_j_, nbmailles_euler_k_, Point3D::norme(), Process::nproc(), ref_domaine_, FT_Field::reinit_remeshing_table(), FT_Field::remailler_FT_Field(), Desc_Structure_FT::remplir_element_pe(), FT_Field::sauvegarder_triangle(), set_ijk_cell_index(), Schema_Comm::set_send_recv_pe_list(), FT_Field::set_tolerance_point_identique(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), Maillage_FT_Disc::sommet_elem_, Maillage_FT_Disc::sommet_num_owner_, Maillage_FT_Disc::sommet_PE_owner_, Maillage_FT_Disc::sommet_virtuel(), Maillage_FT_Disc::sommets_, Surfactant_facettes_non_const(), Point3D::tol, FT_Field::update_FT_Field_local_from_full_compo(), TRUST_Ref< _CLASSE_ >::valeur(), voisinage_processeur_, Point3D::x, Point3D::y, and Point3D::z.
Referenced by Remaillage_FT_IJK::diviser_grandes_aretes().
recopie()
void Maillage_FT_IJK::recopie (const Maillage_FT_Disc & source, Statut_Maillage niveau_copie) override virtual
Recopie une partie du maillage source dans *this.
Si niveau_copie == MINIMAL, seuls les membres de l'etat minimal sont copies.
Reimplemented from Maillage_FT_Disc.
References compo_connexe_facettes(), compo_connexe_facettes_, TRUSTArray< _TYPE_, _SIZE_ >::copy_array(), FT_Field::copy_FT_Field(), Process::exit(), liste_processeurs_voisins_aretes_, liste_processeurs_voisins_coins_, liste_processeurs_voisins_faces_, nbmailles_euler_i_, nbmailles_euler_j_, nbmailles_euler_k_, Maillage_FT_Disc::recopie(), Surfactant_facettes(), Surfactant_facettes_, and voisinage_processeur_.
Referenced by IJK_Interfaces::dupliquer_bulle_perio(), recopie_force_compo(), and IJK_Interfaces::update_old_intersections().
ajouter_maillage()
void Maillage_FT_IJK::ajouter_maillage (const Maillage_FT_Disc & maillage_tmp, int skip_facettes = 0) override virtual
Reimplemented from Maillage_FT_Disc.
References ajouter_maillage_IJK(), and Process::exit().
echanger_facettes()
void Maillage_FT_IJK::echanger_facettes (const ArrOfInt & liste_facettes, const ArrOfInt & liste_elem_arrivee, ArrOfInt & facettes_recues_numfacettes, ArrOfInt & facettes_recues_numelement)
ajouter_maillage_IJK()
void Maillage_FT_IJK::ajouter_maillage_IJK (const Maillage_FT_IJK & added_mesh)
References Maillage_FT_Disc::ajouter_maillage(), compo_connexe_facettes(), compo_connexe_facettes_, FT_Field::get_disable_surfactant(), FT_Field::inject_array(), TRUSTArray< _TYPE_, _SIZE_ >::inject_array(), Maillage_FT_Disc::nb_facettes(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), FT_Field::resize_array(), Surfactant_facettes(), and Surfactant_facettes_.
Referenced by ajouter_maillage(), and IJK_Interfaces::dupliquer_bulle_perio().
lire_maillage_ft_dans_lata()
void Maillage_FT_IJK::lire_maillage_ft_dans_lata (const char * filename_with_path, int tstep, const char * geometryname)
Reading the FT mesh from a LATA file. Assumption: FT mesh is always small enough so that all indices fit within 32b. This check implicitely in the 'ref_as_small' methods.
References TRUSTArray< _TYPE_, _SIZE_ >::append_array(), Desc_Structure_FT::calcul_schema_comm(), compo_connexe_facettes_, Maillage_FT_Disc::desc_facettes_, Maillage_FT_Disc::desc_sommets_, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, TRUSTTab< _TYPE_, _SIZE_ >::dimension_int(), Maillage_FT_Disc::drapeaux_sommets_, Process::exit(), Maillage_FT_Disc::facette_num_owner_, Maillage_FT_Disc::facettes_, FT_Field::get_disable_surfactant(), Process::je_suis_maitre(), Process::Journal(), Process::me(), Maillage_FT_Disc::MINIMAL, TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Maillage_FT_Disc::nb_facettes(), Maillage_FT_Disc::nb_sommets(), nettoyer_maillage(), Process::nproc(), TRUSTTab< _TYPE_, _SIZE_ >::ref_as_small(), ref_domaine_, Maillage_FT_Disc::reset(), Desc_Structure_FT::reset(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), FT_Field::resize_array(), set_ijk_cell_index(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), Maillage_FT_Disc::sommet_elem_, Maillage_FT_Disc::sommet_face_bord_, Maillage_FT_Disc::sommet_num_owner_, Maillage_FT_Disc::sommet_PE_owner_, Maillage_FT_Disc::sommets_, Maillage_FT_Disc::statut_, Surfactant_facettes_, and transporter().
Referenced by IJK_Interfaces::initialize(), and IJK_Interfaces::lire_maillage_ft_dans_lata().
set_ijk_cell_index()
void Maillage_FT_IJK::set_ijk_cell_index (int num_sommet, Int3 ijk) inline
References Domaine_IJK::convert_ijk_cell_to_packed(), ref_domaine_, Maillage_FT_Disc::sommet_elem_, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by deplacer_sommets(), and lire_maillage_ft_dans_lata().
set_barycentrage()
void Maillage_FT_IJK::set_barycentrage (bool bary) inline
References during_barycentrage_.
Referenced by Remaillage_FT_IJK::barycentrer_lisser_apres_remaillage(), and Remaillage_FT_IJK::barycentrer_lisser_systematique_ijk().
get_ijk_cell_index()
Int3 Maillage_FT_IJK::get_ijk_cell_index (int num_sommet) const inline
References Domaine_IJK::convert_packed_to_ijk_cell(), ref_domaine_, Maillage_FT_Disc::sommet_elem_, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by deplacer_sommets().
initialize_processor_neighbourhood()
void Maillage_FT_IJK::initialize_processor_neighbourhood ()
References TRUSTArray< _TYPE_, _SIZE_ >::append_array(), liste_processeurs_voisins_aretes_, liste_processeurs_voisins_coins_, liste_processeurs_voisins_faces_, Process::nproc(), ref_domaine_, TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), and voisinage_processeur_.
Referenced by initialize().
check_sommets()
int Maillage_FT_IJK::check_sommets (int error_is_fatal = 1) const override virtual
Reimplemented from Maillage_FT_Disc.
References Desc_Structure_FT::check(), Maillage_FT_Disc::desc_sommets_, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Desc_Structure_FT::echange_espace_virtuel(), Descripteur_FT::elements(), Desc_Structure_FT::espace_distant(), Desc_Structure_FT::espace_virtuel(), Process::exit(), Process::Journal(), Maillage_FT_Disc::nb_sommets(), Descripteur_FT::pe_voisins(), Desc_Structure_FT::remplir_element_pe(), Maillage_FT_Disc::RESET, TRUSTArray< _TYPE_, _SIZE_ >::size_array(), Maillage_FT_Disc::sommet_elem_, Maillage_FT_Disc::sommet_face_bord_, Maillage_FT_Disc::sommet_num_owner_, Maillage_FT_Disc::sommet_PE_owner_, Maillage_FT_Disc::sommets_, and Maillage_FT_Disc::statut_.
check_mesh()
int Maillage_FT_IJK::check_mesh (int error_is_fatal = 1, int skip_facette_owner = 0, int skip_facettes = 0) const override virtual
Reimplemented from Maillage_FT_Disc.
References Comm_Group::check_enabled(), Maillage_FT_Disc::check_mesh(), compo_connexe_facettes_, Process::exit(), FT_Field::get_disable_surfactant(), Process::Journal(), Maillage_FT_Disc::nb_facettes(), FT_Field::size_array(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and Surfactant_facettes_.
Referenced by creer_facettes_virtuelles(), deplacer_sommets(), Remaillage_FT_IJK::remaillage_local_interface(), and Remaillage_FT_IJK::supprimer_petites_aretes().
calculer_compo_connexe_sommets()
void Maillage_FT_IJK::calculer_compo_connexe_sommets (ArrOfIntFT & compo_connexe_sommets) const
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Maillage_FT_Disc::facettes_, TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), and Maillage_FT_Disc::sommets().
Referenced by IJK_Interfaces::calculer_bounding_box_bulles(), IJK_Interfaces::calculer_distance_autres_compo_connexe2(), IJK_Interfaces::calculer_phi_repuls_sommet(), IJK_Interfaces::compute_external_forces_(), IJK_Interfaces::transporter_maillage_deformation(), and IJK_Interfaces::transporter_maillage_rigide().
recopie_force_compo()
void Maillage_FT_IJK::recopie_force_compo (const Maillage_FT_IJK & source_mesh, const int icompo)
References compo_connexe_facettes_, Process::exit(), Maillage_FT_Disc::MINIMAL, Maillage_FT_Disc::nb_facettes(), recopie(), and TRUSTArray< _TYPE_, _SIZE_ >::resize_array().
set_composante_connexe()
void Maillage_FT_IJK::set_composante_connexe (const int i_facette, const int icompo) inline
References compo_connexe_facettes_.
Referenced by IJK_Interfaces::detecter_et_supprimer_rejeton(), IJK_Interfaces::dupliquer_bulle_perio(), and IJK_Interfaces::supprimer_certaines_bulles_reelles().
minimum_longueur_arrete()
double Maillage_FT_IJK::minimum_longueur_arrete () const
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Maillage_FT_Disc::facettes_, Process::mp_min(), and Maillage_FT_Disc::sommets().
Referenced by IJK_Interfaces::calculer_phi_repuls_sommet().
nb_facettes_sans_duplicata()
int Maillage_FT_IJK::nb_facettes_sans_duplicata () const
References compo_connexe_facettes_, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Maillage_FT_Disc::facettes_, Maillage_FT_Disc::MINIMAL, and Maillage_FT_Disc::statut_.
get_domaine()
const Domaine_IJK & Maillage_FT_IJK::get_domaine () const inline
References ref_domaine_, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by IJK_Interfaces::calculer_aire_interfaciale_for_compo(), Remaillage_FT_IJK::get_delta_euler(), and Remaillage_FT_IJK::supprimer_petites_aretes().
calculer_costheta_minmax()
void Maillage_FT_IJK::calculer_costheta_minmax (DoubleTab & costheta) const override protected virtual
Pour chaque sommet du maillage, s'il est sur un bord, on calcule costheta min et max (hysteresis) correspondant a la condition aux limites ou.
se trouve le sommet. L'angle est constant par face de bord... possibilite de faire mieux pour un champ xyz
Reimplemented from Maillage_FT_Disc.
References Maillage_FT_Disc::nb_sommets(), and TRUSTTab< _TYPE_, _SIZE_ >::resize().
operator=()
const Maillage_FT_IJK & Maillage_FT_IJK::operator= (const Maillage_FT_IJK &) inline protected
References Process::exit().
creer_facettes_virtuelles()
void Maillage_FT_IJK::creer_facettes_virtuelles (const ArrOfInt & liste_facettes, const ArrOfInt & liste_facettes_pe, const ArrOfInt & facettes_send_pe_list, const ArrOfInt & facettes_recv_pe_list) override protected virtual
Creation de facettes virtuelles sur le pe specifie.
liste_facettes = liste de numeros de facettes reelles a envoyer sur le processeur distant (la liste peut comporter des doublons) Le processeur distant ne doit pas etre moi ! liste_pe = numero du pe a qui il faut envoyer chaque facette comm = un schema ou send_pe_list contient les PEs mentionnes dans la liste.
Algo: Il faut d'abord creer les sommets des facettes, s'ils n'existent pas encore, puis creer les facettes. Cas general, le processeur A possede la facette (au sens du descripteur des facettes), le processeur B possede un sommet 's' de la facette, on veut envoyer la facette au processeur C. Il faut: A envoie a B le numero du sommet 's' et le numero du processeur C B cree sur C le sommet virtuel 's' A envoie a C les numeros des sommets 's' de la facette, C peut maintenant creer la facette.
Reimplemented from Maillage_FT_Disc.
References Comm_Group::check_enabled(), check_mesh(), compo_connexe_facettes_, Maillage_FT_Disc::creer_facettes_virtuelles(), Maillage_FT_Disc::desc_facettes(), Desc_Structure_FT::echange_espace_virtuel(), FT_Field::echange_espace_virtuel(), FT_Field::get_disable_surfactant(), Maillage_FT_Disc::nb_facettes(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), FT_Field::resize_array(), and Surfactant_facettes_.
Member Data Documentation
info_obj
const Type_info Maillage_FT_IJK::info_obj static
Surfactant_facettes_
FT_Field Maillage_FT_IJK::Surfactant_facettes_
Referenced by ajouter_maillage_IJK(), check_mesh(), corriger_proprietaires_facettes(), creer_facettes_virtuelles(), lire_maillage_ft_dans_lata(), nettoyer_maillage(), parcourir_maillage(), readOn(), recopie(), sauv_facette_indexation_avant_transport(), Surfactant_facettes(), Surfactant_facettes_non_const(), update_gradient_laplacien_Surfactant(), update_sigma_and_interfacial_source_term_sommet(), and update_surfactant_apres_transport().
during_barycentrage_
bool Maillage_FT_IJK::during_barycentrage_ = false protected
Referenced by deplacer_sommets(), and set_barycentrage().
use_tryggvason_interfacial_source_
bool Maillage_FT_IJK::use_tryggvason_interfacial_source_ =false protected
Referenced by initialize(), and update_sigma_and_interfacial_source_term_sommet().
ref_domaine_
TRUST_Ref< Domaine_IJK *> Maillage_FT_IJK::ref_domaine_ protected
Referenced by deplacer_sommets(), get_domaine(), get_ijk_cell_index(), initialize(), initialize_processor_neighbourhood(), lire_maillage_ft_dans_lata(), and set_ijk_cell_index().
nbmailles_euler_i_
int Maillage_FT_IJK::nbmailles_euler_i_ = 0 protected
Referenced by deplacer_sommets(), initialize(), and recopie().
nbmailles_euler_j_
int Maillage_FT_IJK::nbmailles_euler_j_ = 0 protected
Referenced by deplacer_sommets(), initialize(), and recopie().
nbmailles_euler_k_
int Maillage_FT_IJK::nbmailles_euler_k_ = 0 protected
Referenced by deplacer_sommets(), initialize(), and recopie().
voisinage_processeur_
ArrOfInt Maillage_FT_IJK::voisinage_processeur_ protected
Referenced by deplacer_sommets(), initialize_processor_neighbourhood(), and recopie().
liste_processeurs_voisins_faces_
ArrOfInt Maillage_FT_IJK::liste_processeurs_voisins_faces_ protected
Referenced by deplacer_sommets(), initialize_processor_neighbourhood(), and recopie().
liste_processeurs_voisins_aretes_
ArrOfInt Maillage_FT_IJK::liste_processeurs_voisins_aretes_ protected
Referenced by deplacer_sommets(), initialize_processor_neighbourhood(), and recopie().
liste_processeurs_voisins_coins_
ArrOfInt Maillage_FT_IJK::liste_processeurs_voisins_coins_ protected
Referenced by deplacer_sommets(), initialize_processor_neighbourhood(), and recopie().
compo_connexe_facettes_
ArrOfIntFT Maillage_FT_IJK::compo_connexe_facettes_ protected
Referenced by ajouter_maillage_IJK(), check_mesh(), compo_connexe_facettes(), compo_connexe_facettes_non_const(), creer_facettes_virtuelles(), lire_maillage_ft_dans_lata(), nb_facettes_sans_duplicata(), nettoyer_maillage(), recopie(), recopie_force_compo(), set_composante_connexe(), and update_surfactant_apres_transport().
indexation_facettes_avant_transport_
DoubleTab Maillage_FT_IJK::indexation_facettes_avant_transport_ protected
Referenced by sauv_facette_indexation_avant_transport(), and update_surfactant_apres_transport().