TrioCFD: Convection_Diffusion_Temperature_IBM Class Reference
Convection_Diffusion_Temperature_IBM Class Reference
#include <Convection_Diffusion_Temperature_IBM.h>
Public Member Functions
const Type_info * get_info () const override
bool initTimeStep (double dt) override
int preparer_calcul () override
Public Member Functions inherited from Convection_Diffusion_Temperature
void associer_milieu_base (const Milieu_base &) override
DoubleTab & derivee_en_temps_inco (DoubleTab &) override
void discretiser () override
const Motcle & domaine_application () const override
const Type_info * get_info () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
int preparer_calcul () override
Public Member Functions inherited from Convection_Diffusion_Temperature_base
void associer_milieu_base (const Milieu_base &) override
Fluide_base & fluide ()
const Type_info * get_info () const override
Public Member Functions inherited from Convection_Diffusion_std
void associer_vitesse (const Champ_base &)
const Type_info * get_info () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
int nombre_d_operateurs () const override
const Operateur & operateur (int) const override
Operateur & operateur (int) override
const Champ_Inc_base & vitesse_transportante () const
Public Member Functions inherited from Equation_base
virtual void abortTimeStep ()
virtual void associer_domaine_dis (const Domaine_dis_base &)
virtual void associer_pb_base (const Probleme_base &)
virtual void associer_sch_tps_base (const Schema_Temps_base &)
virtual double calculer_pas_de_temps () const
virtual void completer ()
virtual std::vector< YAML_data > data_a_sauvegarder () const
DoubleTab & derivee_en_temps_conv (DoubleTab &, const DoubleTab &)
virtual DoubleTab & derivee_en_temps_inco (DoubleTab &)
const Discretisation_base & discretisation () const
virtual void discretiser ()
virtual const Motcle & domaine_application () const
virtual Domaine_Cl_dis_base & domaine_Cl_dis ()
virtual const Domaine_Cl_dis_base & domaine_Cl_dis () const
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual void imprimer (Sortie &os) const
virtual bool initTimeStep (double dt)
const Nom & le_nom () const override
int limpr () const
virtual void mettre_a_jour (double temps)
virtual int preparer_calcul ()
Probleme_base & probleme ()
const Probleme_base & probleme () const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Schema_Temps_base & schema_temps ()
const Schema_Temps_base & schema_temps () const
Solveur_Masse_base & solv_masse ()
const Solveur_Masse_base & solv_masse () const
Sources & sources ()
const Sources & sources () const
virtual void valider_iteration ()
virtual void verifie_ch_init_nb_comp (const Champ_Inc_base &ch_ref, const int nb_comp) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Convection_Diffusion_Temperature
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Convection_Diffusion_Temperature_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Equation_base
virtual Entree & lire_cl (Entree &)
virtual Entree & lire_cond_init (Entree &)
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual Entree & lire_sources (Entree &)
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
virtual int verif_Cl () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Convection_Diffusion_Temperature_IBM()
Convection_Diffusion_Temperature_IBM::Convection_Diffusion_Temperature_IBM ()
~Convection_Diffusion_Temperature_IBM()
Convection_Diffusion_Temperature_IBM::~Convection_Diffusion_Temperature_IBM ()
Member Function Documentation
cree_instance()
Objet_U * Convection_Diffusion_Temperature_IBM::cree_instance () static
taille_memoire()
unsigned Convection_Diffusion_Temperature_IBM::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Convection_Diffusion_Temperature_IBM_Turbulent.
duplique()
int Convection_Diffusion_Temperature_IBM::duplique () const override virtual
Implements Objet_U.
Reimplemented in Convection_Diffusion_Temperature_IBM_Turbulent.
info()
const Type_info * Convection_Diffusion_Temperature_IBM::info () static
get_info()
const Type_info * Convection_Diffusion_Temperature_IBM::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Equation_base.
Reimplemented in Convection_Diffusion_Temperature_IBM_Turbulent.
self_cast() [1/2]
Convection_Diffusion_Temperature_IBM & Convection_Diffusion_Temperature_IBM::self_cast (Objet_U & r) static
self_cast() [2/2]
const Convection_Diffusion_Temperature_IBM & Convection_Diffusion_Temperature_IBM::self_cast (const Objet_U & r) static
printOn()
Sortie & Convection_Diffusion_Temperature_IBM::printOn (Sortie & os) const override protected virtual
Surcharge Objet_U::printOn Imprime l'equation et ses composants sur un flot de sortie.
Imprime le nom de l'equation, le solveur masse, les termes sources les conditions aux limites discretisees, les inconnues et les operateurs.
Parameters
(Sortie& os) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Equation_base.
Reimplemented in Convection_Diffusion_Temperature_IBM_Turbulent.
References Convection_Diffusion_Temperature::printOn().
readOn()
Entree & Convection_Diffusion_Temperature_IBM::readOn (Entree & is) override protected virtual
Lecture d'une equation sur un flot d'entree.
Le format est le suivant: { [Source { [sou_1], [sour_2], ...} ] Conditions_limites { [cl_1] [cl_2] ... } Conditions_initiales { [cl_init] } }
Parameters
(Entree& is) un flot d'entree pour lire l'equation
Returns
(Entree&) le flot d'entree modifie
Exceptions
mauvais format de lecture, accolade ouvrante attendue
pas de conditions initiales, il faut initialiser l'inconnue
pas de conditions aux limites, il faut donner des conditions aux limites
Reimplemented from Equation_base.
Reimplemented in Convection_Diffusion_Temperature_IBM_Turbulent.
References Convection_Diffusion_Temperature::readOn(), and Equation_IBM_proto::readOn_ibm_proto().
Referenced by Convection_Diffusion_Temperature_IBM_Turbulent::readOn().
set_param()
void Convection_Diffusion_Temperature_IBM::set_param (Param & titi) override virtual
Reimplemented from Equation_base.
Reimplemented in Convection_Diffusion_Temperature_IBM_Turbulent.
References Convection_Diffusion_Temperature::set_param(), and Equation_IBM_proto::set_param_ibm_proto().
Referenced by Convection_Diffusion_Temperature_IBM_Turbulent::set_param().
assembler()
void Convection_Diffusion_Temperature_IBM::assembler (Matrice_Morse & mat_morse, const DoubleTab & present, DoubleTab & secmem) override virtual
Reimplemented from Equation_base.
References Equation_IBM_proto::assembler_ibm_proto().
preparer_calcul()
int Convection_Diffusion_Temperature_IBM::preparer_calcul () override virtual
Tout ce qui ne depend pas des autres problemes eventuels.
Returns
(int) renvoie toujours 1
Reimplemented from Equation_base.
Reimplemented in Convection_Diffusion_Temperature_IBM_Turbulent.
References Equation_base::preparer_calcul(), and Equation_IBM_proto::preparer_calcul_ibm_proto().
Referenced by Convection_Diffusion_Temperature_IBM_Turbulent::preparer_calcul().
initTimeStep()
bool Convection_Diffusion_Temperature_IBM::initTimeStep (double dt) override virtual
Allocation et initialisation de l'inconnue et des CLs jusqu'a present+dt.
autres initialisations pour les calculs sur le prochain pas de temps : operateurs, solveur_masse->
Returns
(0 en cas d'erreur, 1 sinon)
Reimplemented from Equation_base.
Reimplemented in Convection_Diffusion_Temperature_IBM_Turbulent.
References Equation_base::initTimeStep(), and Equation_IBM_proto::initTimeStep_ibm_proto().
Referenced by Convection_Diffusion_Temperature_IBM_Turbulent::initTimeStep().
derivee_en_temps_inco_sources()
void Convection_Diffusion_Temperature_IBM::derivee_en_temps_inco_sources (DoubleTrav & secmem) override virtual
Reimplemented from Equation_base.
References Equation_IBM_proto::derivee_en_temps_inco_ibm_proto().
verify_scheme()
void Convection_Diffusion_Temperature_IBM::verify_scheme () override virtual
Reimplemented from Equation_base.
References Process::abort(), Equation_base::equation_non_resolue(), and Equation_IBM_proto::is_IBM().
Member Data Documentation
info_obj
const Type_info Convection_Diffusion_Temperature_IBM::info_obj static