TrioCFD: Champ_Elem_DG Class Reference
Champ_Elem_DG Class Reference
#include <Champ_Elem_DG.h>
Public Member Functions
const Matrice_Dense build_local_mass_matrix (const Quadrature_base &quad, const int nelem) const
const Type_info * get_info () const override
DoubleTab & valeur_aux (const DoubleTab &positions, DoubleTab &valeurs) const override
Public Member Functions inherited from Champ_Inc_P0_base
const Type_info * get_info () const override
Public Member Functions inherited from Champ_Inc_base
Champ_base & affecter_ (const Champ_base &) override
Champ_base & affecter_compo (const Champ_base &, int compo) override
virtual void associer_eqn (const Equation_base &)
Champ_Inc_base & avancer (int i=1)
double changer_temps (const double temps) override
double changer_temps_futur (double, int i=1)
double changer_temps_passe (double, int i=1)
virtual int fixer_nb_valeurs_temporelles (int)
DoubleTab & futur (int i=1) override
const Type_info * get_info () const override
int lire_donnees (Entree &)
void mettre_a_jour (double temps) override
virtual int nb_valeurs_temporelles () const
DoubleTab & passe (int i=1) override
Champ_Inc_base & reculer (int i=1)
double recuperer_temps_futur (int i=1) const
double recuperer_temps_passe (int i=1) const
virtual DoubleTab & remplir_coord_noeuds_compo (DoubleTab &, int) const
virtual int remplir_coord_noeuds_et_polys (DoubleTab &, IntVect &) const
virtual int remplir_coord_noeuds_et_polys_compo (DoubleTab &, IntVect &, int) const
int reprendre (Entree &) override
void resetTime (double time) override
int sauvegarder (Sortie &) const override
DoubleTab & trace (const Frontiere_dis_base &, DoubleTab &, double, int distant) const override
DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const override
DoubleTab & valeur_aux (const DoubleTab &positions, DoubleTab &valeurs) const override
DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const override
DoubleTab & valeurs () override
const DoubleTab & valeurs (double temps) const override
DoubleTab & valeurs (double temps) override
Public Member Functions inherited from Champ_base
Champ_base & affecter (const Champ_base &)
Champ_base ()
virtual double changer_temps (const double t)
const Type_info * get_info () const override
double temps () const
virtual DoubleTab & trace (const Frontiere_dis_base &, DoubleTab &, double, int distant) const
virtual DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const
virtual double valeur_a_compo (const DoubleVect &position, int ncomp) const
virtual DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &valeurs, int le_poly) const
virtual double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const
virtual DoubleVect & valeur_a_sommet (int, const Domaine &, DoubleVect &) const
virtual DoubleTab & valeur_aux (const DoubleTab &positions, DoubleTab &valeurs) const
virtual DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const
virtual DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const
virtual DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp) const
Public Member Functions inherited from Field_base
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
virtual void fixer_nb_comp (int i)
virtual const Nom & fixer_nom_compo (const Nom &)
virtual const Nom & fixer_nom_compo (int, const Nom &)
virtual const Noms & fixer_noms_compo (const Noms &)
virtual const Nom & fixer_unite (const Nom &)
virtual const Nom & fixer_unite (int i, const Nom &)
virtual const Noms & fixer_unites (const Noms &)
const Type_info * get_info () const override
const Nom & nom_compo (int) const
void nommer (const Nom &) override
const Nom & unite () const
const Nom & unite (int) const
const Noms & unites () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Champ_Proto
int lire_dimension (Entree &, const Nom &)
int lire_dimension (int dim, const Nom &le_nom_)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Champ_implementation_P0
DoubleTab & valeur_aux_centres_de_gravite (const Domaine &, DoubleTab &valeurs) const
Protected Member Functions
void allocate_mass_matrix ()
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Champ_Inc_P0_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Champ_Inc_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Field_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Champ_Elem_DG()
Champ_Elem_DG::Champ_Elem_DG ()
~Champ_Elem_DG()
Champ_Elem_DG::~Champ_Elem_DG ()
Member Function Documentation
cree_instance()
Objet_U * Champ_Elem_DG::cree_instance () static
taille_memoire()
unsigned Champ_Elem_DG::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Champ_Elem_DG::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Champ_Elem_DG::info () static
get_info()
const Type_info * Champ_Elem_DG::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
Champ_Elem_DG & Champ_Elem_DG::self_cast (Objet_U & r) static
self_cast() [2/2]
const Champ_Elem_DG & Champ_Elem_DG::self_cast (const Objet_U & r) static
printOn()
Sortie & Champ_Elem_DG::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
References Field_base::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Champ_Elem_DG::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
References Champ_Inc_base::lire_donnees().
affecter_()
Champ_base & Champ_Elem_DG::affecter_ (const Champ_base & ch) override virtual
Implements Champ_base.
References Matrice_Dense::ajouter_multvect_(), Quadrature_base::compute_integral_on_elem(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Champ_Inc_base::domaine(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), eval_bfunc(), eval_invMassMatrix(), Quadrature_base::get_integ_points(), Quadrature_base::ind_pts_integ(), Champ_Inc_base::le_dom_VF, nb_bfunc_, Domaine_32_64< _SIZE_ >::nb_elem(), Quadrature_base::nb_pts_integ(), Quadrature_base::nb_pts_integ_max(), TRUSTTab< _TYPE_, _SIZE_ >::ref_tab(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_base::valeur_aux(), and Champ_Inc_base::valeurs().
imprime()
int Champ_Elem_DG::imprime (Sortie & os, int ncomp) const override virtual
construct inverse of global mass matrix, Unused now, cleaning used
Implements Champ_base.
References Domaine_32_64< _SIZE_ >::coord_sommets(), Objet_U::dimension, Champ_Inc_base::domaine(), Domaine_dis_base::domaine(), Champ_Inc_base::domaine_dis_base(), Field_base::nb_compo_, Domaine_32_64< _SIZE_ >::nb_som(), and Champ_Inc_base::valeurs().
fixer_nb_valeurs_nodales()
int Champ_Elem_DG::fixer_nb_valeurs_nodales (int n) override virtual
Reimplemented from Champ_base.
References Champ_Inc_base::creer_tableau_distribue(), Champ_Inc_base::domaine(), and Champ_Inc_base::domaine_dis_base().
associer_domaine_dis_base()
void Champ_Elem_DG::associer_domaine_dis_base (const Domaine_dis_base & z_dis) override virtual
Reimplemented from Champ_base.
References allocate_mass_matrix(), allocate_transition_matrix(), build_mass_matrix(), build_transition_matrix(), compute_stab_param(), Champ_Inc_base::domaine(), Option_DG::Get_order_for(), Champ_Inc_base::le_dom_VF, nb_bfunc_, Option_DG::Nb_col_from_order(), Field_base::nom_, order_, and TRUST_Ref< _CLASSE_ >::valeur().
get_order()
const int & Champ_Elem_DG::get_order () const inline
References order_.
Referenced by compute_stab_param(), and Op_Diff_DG_Elem::dimensionner().
indices_glob_elem()
const IntTab & Champ_Elem_DG::indices_glob_elem () const inline
References indices_glob_elem_.
Referenced by Op_Diff_DG_Elem::ajouter_blocs(), and Op_Diff_DG_Elem::dimensionner().
nb_bfunc()
const int & Champ_Elem_DG::nb_bfunc () const inline
References nb_bfunc_.
Referenced by Op_Diff_DG_Elem::ajouter_blocs(), Eval_Puiss_Th_DG_Elem::calculer_terme_source(), and Op_Diff_DG_Elem::contribuer_au_second_membre().
eval_bfunc() [1/2]
void Champ_Elem_DG::eval_bfunc (const Quadrature_base & quad, const int & nelem, DoubleTab & fbasis) const
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Champ_Inc_base::domaine(), Process::exit(), Quadrature_base::get_integ_points(), Quadrature_base::ind_pts_integ(), is_orthonormalized_, Champ_Inc_base::le_dom_VF, nb_bfunc_, Quadrature_base::nb_pts_integ(), Quadrature_base::nb_pts_integ_max(), order_, orthonormalize(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by affecter_(), build_local_mass_matrix(), build_mass_matrix(), build_transition_matrix(), Eval_Puiss_Th_DG_Elem::calculer_terme_source(), eval_elem(), eval_invMassMatrix(), and valeur_aux_elems().
eval_bfunc_on_facets()
void Champ_Elem_DG::eval_bfunc_on_facets (const Quadrature_base & quad, const int & nelem, const int & num_face, DoubleTab & grad_fbasis) const
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Champ_Inc_base::domaine(), Process::exit(), Quadrature_base::get_integ_points_facets(), is_orthonormalized_, Champ_Inc_base::le_dom_VF, nb_bfunc_, Quadrature_base::nb_pts_integ_facets(), order_, orthonormalize(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Op_Diff_DG_Elem::ajouter_blocs(), and Op_Diff_DG_Elem::contribuer_au_second_membre().
eval_bfunc() [2/2]
void Champ_Elem_DG::eval_bfunc (const DoubleTab & coord, const int & nelem, DoubleTab & fbasis) const
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Champ_Inc_base::domaine(), Process::exit(), is_orthonormalized_, Champ_Inc_base::le_dom_VF, nb_bfunc_, Quadrature_base::nb_pts_integ(), order_, orthonormalize(), and TRUST_Ref< _CLASSE_ >::valeur().
eval_grad_bfunc()
void Champ_Elem_DG::eval_grad_bfunc (const Quadrature_base & quad, const int & nelem, DoubleTab & fbasis) const
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Champ_Inc_base::domaine(), Process::exit(), Quadrature_base::get_integ_points(), Quadrature_base::ind_pts_integ(), is_orthonormalized_, Champ_Inc_base::le_dom_VF, nb_bfunc_, Quadrature_base::nb_pts_integ(), Quadrature_base::nb_pts_integ_max(), order_, orthonormalize(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Op_Diff_DG_Elem::ajouter_blocs().
eval_grad_bfunc_on_facets()
void Champ_Elem_DG::eval_grad_bfunc_on_facets (const Quadrature_base & quad, const int & nelem, const int & num_face, DoubleTab & grad_fbasis) const
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Champ_Inc_base::domaine(), Process::exit(), Quadrature_base::get_integ_points_facets(), is_orthonormalized_, Champ_Inc_base::le_dom_VF, nb_bfunc_, Quadrature_base::nb_pts_integ_facets(), order_, orthonormalize(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Op_Diff_DG_Elem::ajouter_blocs(), and Op_Diff_DG_Elem::contribuer_au_second_membre().
get_mass_matrix()
const Matrice_Morse & Champ_Elem_DG::get_mass_matrix () const inline
References mass_matrix_.
Referenced by Masse_DG_base::ajouter_blocs().
get_eta_elem()
const DoubleTab & Champ_Elem_DG::get_eta_elem () const inline
References eta_elem.
get_eta_facet()
const DoubleTab & Champ_Elem_DG::get_eta_facet () const inline
References eta_facet.
Referenced by Op_Diff_DG_Elem::ajouter_blocs(), and Op_Diff_DG_Elem::contribuer_au_second_membre().
eval_invMassMatrix()
const Matrice_Dense Champ_Elem_DG::eval_invMassMatrix (const Quadrature_base & quad, const int & nelem) const
References build_local_mass_matrix(), Objet_U::dimension, Champ_Inc_base::domaine(), eval_bfunc(), Process::exit(), Quadrature_base::get_weights(), Quadrature_base::ind_pts_integ(), Matrice_Dense::inverse(), Champ_Inc_base::le_dom_VF, nb_bfunc_, Quadrature_base::nb_pts_integ(), Quadrature_base::nb_pts_integ_max(), order_, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by affecter_().
build_local_mass_matrix()
const Matrice_Dense Champ_Elem_DG::build_local_mass_matrix (const Quadrature_base & quad, const int nelem) const
Compute the mass matrix of cell nelem.
Parameters
quad quadature used to compute mass matrix
nelem index of the cell
References Quadrature_base::compute_integral_on_elem(), eval_bfunc(), Quadrature_base::get_tab_nb_pts_integ(), nb_bfunc_, and Quadrature_base::nb_pts_integ_max().
Referenced by eval_invMassMatrix().
valeur_aux_elems()
DoubleTab & Champ_Elem_DG::valeur_aux_elems (const DoubleTab & positions, const IntVect & les_polys, DoubleTab & valeurs) const override virtual
Implements Champ_implementation.
References Quadrature_base::compute_integral_on_elem(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Champ_Inc_base::domaine(), eval_bfunc(), Champ_Inc_P0_base::le_champ(), Champ_Inc_base::le_dom_VF, TRUSTVect< _TYPE_, _SIZE_ >::line_size(), nb_bfunc_, TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Quadrature_base::nb_pts_integ(), Quadrature_base::nb_pts_integ_max(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTVect< _TYPE_, _SIZE_ >::size(), TRUST_Ref< _CLASSE_ >::valeur(), and Champ_Proto::valeurs().
valeur_aux()
DoubleTab & Champ_Elem_DG::valeur_aux (const DoubleTab & positions, DoubleTab & les_valeurs) const override virtual
Provoque une erreur ! Doit etre surchargee par les classes derivees.
non virtuelle pure par commodite de developpement ! Renvoie les valeurs du champ aux points specifies par leurs coordonnees.
Parameters
(DoubleTab&) le tableau des coordonnees des points de calcul
(DoubleTab& les_valeurs) le tableau des valeurs du champ aux points specifies
Returns
(DoubleTab&) le tableau des valeurs du champ aux points specifies
Reimplemented from Champ_base.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Champ_Inc_base::domaine(), Domaine_dis_base::domaine(), Champ_Inc_base::domaine_dis_base(), Domaine_DG::get_quadrature(), Champ_Inc_base::le_dom_VF, Quadrature_base::nb_pts_integ_max(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), and TRUST_Ref< _CLASSE_ >::valeur().
eval_elem()
DoubleTab & Champ_Elem_DG::eval_elem (DoubleTab & valeurs) const override virtual
Reimplemented from Champ_base.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Champ_Inc_base::domaine(), eval_bfunc(), Champ_Inc_P0_base::le_champ(), Champ_Inc_base::le_dom_VF, nb_bfunc_, Domaine_32_64< _SIZE_ >::nb_elem(), Quadrature_base::nb_pts_integ(), Quadrature_base::nb_pts_integ_max(), TRUST_Ref< _CLASSE_ >::valeur(), and Champ_Proto::valeurs().
allocate_mass_matrix()
void Champ_Elem_DG::allocate_mass_matrix () protected
Compute size of mass matrix and allocate the associated array.
Compute the mass matrix
References Matrix_tools::allocate_morse_matrix(), TRUSTTab< _TYPE_, _SIZE_ >::append_line(), Objet_U::dimension, indices_glob_elem_, Champ_Inc_base::le_dom_VF, mass_matrix_, nb_bfunc_, and TRUSTTab< _TYPE_, _SIZE_ >::resize().
Referenced by associer_domaine_dis_base().
allocate_transition_matrix()
void Champ_Elem_DG::allocate_transition_matrix () protected
References Matrix_tools::allocate_morse_matrix(), TRUSTTab< _TYPE_, _SIZE_ >::append_line(), Objet_U::dimension, indices_glob_elem_, Champ_Inc_base::le_dom_VF, nb_bfunc_, TRUSTTab< _TYPE_, _SIZE_ >::resize(), and transition_matrix_.
Referenced by associer_domaine_dis_base().
compute_stab_param()
void Champ_Elem_DG::compute_stab_param () protected
References Champ_Inc_base::domaine(), eta_elem, eta_facet, get_order(), Champ_Inc_base::le_dom_VF, Domaine_32_64< _SIZE_ >::nb_elem_tot(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by associer_domaine_dis_base().
build_mass_matrix()
void Champ_Elem_DG::build_mass_matrix () protected
Fill up the mass matrix after computing its coefficients.
References Quadrature_base::compute_integral_on_elem(), Champ_Inc_base::domaine(), eval_bfunc(), Quadrature_base::get_tab_nb_pts_integ(), Champ_Inc_base::le_dom_VF, mass_matrix_, nb_bfunc_, Quadrature_base::nb_pts_integ_max(), order_, Objet_U::que_suis_je(), Domaine_32_64< _SIZE_ >::type_elem(), TRUST_Deriv< _CLASSE_ >::valeur(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by associer_domaine_dis_base().
build_transition_matrix()
void Champ_Elem_DG::build_transition_matrix () protected
References Champ_Inc_base::domaine(), eval_bfunc(), Quadrature_base::get_tab_nb_pts_integ(), gramSchmidt(), is_orthonormalized_, Champ_Inc_base::le_dom_VF, nb_bfunc_, Quadrature_base::nb_pts_integ_max(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by associer_domaine_dis_base().
orthonormalize()
void Champ_Elem_DG::orthonormalize (const int & nelem, DoubleTab & fbasis) const protected
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, indices_glob_elem_, nb_bfunc_, TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), and transition_matrix_.
Referenced by eval_bfunc(), eval_bfunc_on_facets(), eval_grad_bfunc(), and eval_grad_bfunc_on_facets().
gramSchmidt()
void Champ_Elem_DG::gramSchmidt (DoubleTab & fbase, const Quadrature_base & quad, const int & num_elem, const int & current_indice, const int & nb_pts_integ, const double & volume, int index) protected
References Quadrature_base::compute_integral_on_elem(), gramSchmidt(), nb_bfunc_, and transition_matrix_.
Referenced by build_transition_matrix(), and gramSchmidt().
Member Data Documentation
info_obj
const Type_info Champ_Elem_DG::info_obj static
order_
int Champ_Elem_DG::order_ = -1 protected
Referenced by associer_domaine_dis_base(), build_mass_matrix(), eval_bfunc(), eval_bfunc_on_facets(), eval_grad_bfunc(), eval_grad_bfunc_on_facets(), eval_invMassMatrix(), and get_order().
nb_bfunc_
int Champ_Elem_DG::nb_bfunc_ = -1 protected
Referenced by affecter_(), allocate_mass_matrix(), allocate_transition_matrix(), associer_domaine_dis_base(), build_local_mass_matrix(), build_mass_matrix(), build_transition_matrix(), eval_bfunc(), eval_bfunc_on_facets(), eval_elem(), eval_grad_bfunc(), eval_grad_bfunc_on_facets(), eval_invMassMatrix(), gramSchmidt(), nb_bfunc(), orthonormalize(), and valeur_aux_elems().
is_orthonormalized_
bool Champ_Elem_DG::is_orthonormalized_ = false protected
Referenced by build_transition_matrix(), eval_bfunc(), eval_bfunc_on_facets(), eval_grad_bfunc(), and eval_grad_bfunc_on_facets().
indices_glob_elem_
IntTab Champ_Elem_DG::indices_glob_elem_ protected
Referenced by allocate_mass_matrix(), allocate_transition_matrix(), indices_glob_elem(), and orthonormalize().
mass_matrix_
Matrice_Morse Champ_Elem_DG::mass_matrix_ protected
Referenced by allocate_mass_matrix(), build_mass_matrix(), and get_mass_matrix().
transition_matrix_
Matrice_Morse Champ_Elem_DG::transition_matrix_ protected
Referenced by allocate_transition_matrix(), gramSchmidt(), and orthonormalize().
eta_elem
DoubleTab Champ_Elem_DG::eta_elem protected
Referenced by compute_stab_param(), and get_eta_elem().
eta_facet
DoubleTab Champ_Elem_DG::eta_facet protected
Referenced by compute_stab_param(), and get_eta_facet().