TrioCFD: Simple Class Reference
Simple Class Reference
#include <Simple.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Simpler_Base
TRUST_Deriv< Parametre_equation_base > & get_and_set_parametre_equation (Equation_base &) override
const Type_info * get_info () const override
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Entree & readOn (Entree &) override
Protected Member Functions inherited from Simpler_Base
Entree & readOn (Entree &) override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Member Typedef Documentation
list_of_eq_ptr_t
using Simple::list_of_eq_ptr_t = std::vector<intptr_t>
Constructor & Destructor Documentation
~Simple()
Simple::~Simple ()
Simple()
Simple::Simple ()
References alpha_, beta_, TRUSTTab< _TYPE_, _SIZE_ >::resize(), Ustar_old, and with_d_rho_dt_.
Member Function Documentation
cree_instance()
Objet_U * Simple::cree_instance () static
taille_memoire()
unsigned Simple::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Implicite_ALE, Implicit_steady, Simpler, and Solveur_U_P.
duplique()
int Simple::duplique () const override virtual
Implements Objet_U.
Reimplemented in Implicite_ALE, Implicit_steady, Simpler, and Solveur_U_P.
info()
const Type_info * Simple::info () static
get_info()
const Type_info * Simple::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Solveur_non_lineaire.
Reimplemented in Implicite_ALE, Implicit_steady, Simpler, and Solveur_U_P.
self_cast() [1/2]
Simple & Simple::self_cast (Objet_U & r) static
self_cast() [2/2]
const Simple & Simple::self_cast (const Objet_U & r) static
printOn()
Sortie & Simple::printOn (Sortie & x) const override protected virtual
voir Solveur::printOn
Reimplemented from Solveur_non_lineaire.
Reimplemented in Implicite_ALE, Implicit_steady, Simpler, and Solveur_U_P.
References Simpler_Base::printOn().
Referenced by Simpler::printOn(), and Solveur_U_P::printOn().
readOn()
Entree & Simple::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Solveur_non_lineaire.
Reimplemented in Implicite_ALE, Implicit_steady, Simpler, and Solveur_U_P.
References Simpler_Base::readOn().
Referenced by Simpler::readOn(), and Solveur_U_P::readOn().
iterer_eqn()
bool Simple::iterer_eqn (Equation_base & equation, const DoubleTab & inconnue, DoubleTab & result, double dt, int numero_iteration, int & ok) override virtual
Implements Simpler_Base.
References Parametre_implicite::calcul_explicite(), Equation_base::derivee_en_temps_inco(), Objet_U_ptr::detach(), Equation_base::dimensionner_matrice(), Parametre_implicite::equation_frequence_resolue(), Equation_base::equation_non_resolue(), Objet_U_ptr::est_nul(), Simpler_Base::get_and_set_parametre_implicite(), Matrice_Morse::get_set_coeff(), Equation_base::inconnue(), Simpler_Base::is_seuil_convg_variable, Schema_Temps_base::nb_pas_dt(), Simpler_Base::no_qdm_, Objet_U::que_suis_je(), Equation_base::schema_temps(), Parametre_implicite::seuil_convergence_implicite(), Parametre_implicite::seuil_diffusion_implicite(), Parametre_implicite::seuil_test_preliminaire_solveur(), Parametre_implicite::seuil_verification_solveur(), Parametre_implicite::solveur(), Schema_Temps_base::temps_courant(), Champ_Inc_base::valeurs(), and Equation_base::valider_iteration().
iterer_NS()
void Simple::iterer_NS (Equation_base & eqn, DoubleTab & current, DoubleTab & pression, double dt, Matrice_Morse & matrice, double seuil_resol, DoubleTrav & secmem, int nb_iter, int & converge, int & ok) override virtual
Implements Simpler_Base.
Reimplemented in Implicit_steady, Simpler, and Solveur_U_P.
References Simpler_Base::get_and_set_parametre_implicite(), and Parametre_implicite::solveur().
iterer_eqs()
bool Simple::iterer_eqs (TRUST_List< TRUST_Ref< Equation_base * > > eqs, int compteur, int & ok) override virtual
Reimplemented from Solveur_Implicite_base.
References MD_Vector_composite::add_part(), Matrice_Base::ajouter_multvect(), Equation_base::ajouter_termes_croises(), Equation_base::assembler_avec_inertie(), Equation_base::assembler_blocs_avec_inertie(), Equation_base::contribuer_termes_croises(), MD_Vector::copy(), MD_Vector_tools::creer_tableau_distribue(), Matrice_Bloc::dimensionner(), Equation_base::dimensionner_matrice(), Equation_base::dimensionner_termes_croises(), Equation_base::domaine_Cl_dis(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Champ_Inc_base::futur(), Simpler_Base::get_and_set_parametre_implicite(), Matrice_Bloc::get_bloc(), TRUSTVect< _TYPE_, _SIZE_ >::get_md_vector(), Matrice_Morse::get_set_coeff(), Matrice_Morse::get_set_tab2(), Nom::getString(), Domaine_Cl_dis_base::imposer_cond_lim(), Equation_base::inconnue(), Objet_U::le_nom(), Field_base::le_nom(), Probleme_U::le_nom(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), mbloc, Equation_base::mettre_a_jour(), Schema_Temps_base::pas_de_temps(), Equation_base::probleme(), Objet_U::que_suis_je(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), SolveurSys::resoudre_systeme(), Equation_base::schema_temps(), Parametre_implicite::seuil_convergence_implicite(), TRUSTVect< _TYPE_, _SIZE_ >::size(), TRUSTVect< _TYPE_, _SIZE_ >::size_totale(), Parametre_implicite::solveur(), Schema_Temps_base::temps_courant(), Objet_U_ptr::typer(), TRUST_Deriv< _CLASSE_ >::valeur(), and Champ_Inc_base::valeurs().
lire()
Entree & Simple::lire (const Motcle & motlu, Entree & is) override protected virtual
Implements Simpler_Base.
References beta_, Process::exit(), Objet_U::que_suis_je(), and Motcles::search().
Referenced by SETS::lire().
calculer_correction_en_vitesse()
void Simple::calculer_correction_en_vitesse (const DoubleTrav & correction_en_pression, DoubleTrav & gradP, DoubleTrav & correction_en_vitesse, const Matrice_Morse & matrice, const Operateur_Grad & gradient) protected
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), and TRUSTTab< _TYPE_, _SIZE_ >::nb_dim().
Member Data Documentation
info_obj
const Type_info Simple::info_obj static
mbloc
std::map<list_of_eq_ptr_t, Matrice_Bloc> Simple::mbloc
Referenced by iterer_eqs().
Ustar_old
DoubleTab Simple::Ustar_old protected
Referenced by Simple().
alpha_
double Simple::alpha_ protected
Referenced by Simple().
beta_
double Simple::beta_ protected
Referenced by lire(), and Simple().
with_d_rho_dt_
int Simple::with_d_rho_dt_ protected
Referenced by Simple().