TrioCFD: TRUST_Ref_Objet_U Class Reference
TRUST_Ref_Objet_U Class Reference
#include <TRUST_Ref.h>
Detailed Description
Cette classe est quasiment identique a TRUST_Ref<>, sauf qu'elle ne contient pas les operateurs de conversion implicite
Constructor & Destructor Documentation
~TRUST_Ref_Objet_U()
TRUST_Ref_Objet_U::~TRUST_Ref_Objet_U () default
TRUST_Ref_Objet_U() [1/3]
TRUST_Ref_Objet_U::TRUST_Ref_Objet_U () default
TRUST_Ref_Objet_U() [2/3]
TRUST_Ref_Objet_U::TRUST_Ref_Objet_U (const Objet_U & t)
TRUST_Ref_Objet_U() [3/3]
TRUST_Ref_Objet_U::TRUST_Ref_Objet_U (const TRUST_Ref_Objet_U & t)
Member Function Documentation
operator=() [1/2]
const TRUST_Ref_Objet_U & TRUST_Ref_Objet_U::operator= (const Objet_U & t)
operator=() [2/2]
const TRUST_Ref_Objet_U & TRUST_Ref_Objet_U::operator= (const TRUST_Ref_Objet_U & t)
non_nul()
bool TRUST_Ref_Objet_U::non_nul () const
Referenced by Champ_front_contact_VEF::calcul_grads_locaux(), Traitement_particulier_NS_canal::calcul_reynolds_tau(), Champ_Q1_EF::calcul_y_plus(), Champ_P1NC::calcul_y_plus(), Champ_Face_VDF::calcul_y_plus(), Champ_P1NC::calcul_y_plus_diphasique(), Champ_Face_VDF::calcul_y_plus_diphasique(), Op_Dift_EF_base::completer(), Op_Dift_VEF_base::completer(), Champ_P1NC_implementation::filtrer_L2(), Champ_Generique_Tparoi_VEF::get_champ(), Navier_Stokes_Turbulent_ALE::get_modele(), Convection_Diffusion_Temperature_IBM_Turbulent::get_modele(), Navier_Stokes_IBM_Turbulent::get_modele(), Convection_Diffusion_Chaleur_Turbulent_QC::get_modele(), Convection_Diffusion_Concentration_Turbulent::get_modele(), Convection_Diffusion_Espece_Binaire_Turbulent_QC::get_modele(), Convection_Diffusion_Espece_Multi_Turbulent_QC::get_modele(), Convection_Diffusion_Temperature_Turbulent::get_modele(), Navier_Stokes_Turbulent::get_modele(), PlaqThVDF::mettre_a_jour(), Traitement_particulier_NS_canal::preparer_calcul_particulier(), and Op_Diff_PolyMAC_base::update_nu().
est_nul()
bool TRUST_Ref_Objet_U::est_nul () const
valeur() [1/2]
const Objet_U & TRUST_Ref_Objet_U::valeur () const inline
Referenced by Op_Dift_VDF_base::ajoute_terme_pour_axi_turb(), Source_Transport_Fluctuation_Temperature_VDF_Elem::ajouter(), Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::ajouter(), Source_Transport_Fluctuation_Temperature_W_VDF_Elem::ajouter(), Source_Transport_Flux_Chaleur_Turbulente_VDF_Face::ajouter(), Source_Robin_Scalaire::ajouter(), Champ_front_contact_VEF::calcul_grads_locaux(), Traitement_particulier_NS_canal::calcul_reynolds_tau(), Champ_Q1_EF::calcul_y_plus(), Champ_P1NC::calcul_y_plus(), Champ_Face_VDF::calcul_y_plus(), Champ_P1NC::calcul_y_plus_diphasique(), Champ_Face_VDF::calcul_y_plus_diphasique(), Modele_turbulence_scal_LES_dyn_VDF::calculer_diffusivite_turbulente(), Modele_turbulence_scal_Fluctuation_Temperature_W::calculer_diffusivite_turbulente(), Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re::calculer_diffusivite_turbulente(), ParoiVDF_TBLE_LRM::calculer_hyd(), ParoiVDF_TBLE::calculer_hyd(), ParoiVEF_TBLE::calculer_hyd(), ParoiVDF_TBLE::calculer_hyd_BiK(), ParoiVDF_TBLE_LRM::calculer_hyd_BiK(), ParoiVEF_TBLE::calculer_hyd_BiK(), Traitement_particulier_NS_canal_VDF::calculer_moyenne_spatiale_nut(), Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_nut(), Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_nut(), Paroi_std_scal_hyd_EF::calculer_scal(), Paroi_loi_WW_scal_VDF::calculer_scal(), Paroi_ODVM_scal_VDF::calculer_scal(), Paroi_std_scal_hyd_VDF::calculer_scal(), Paroi_loi_WW_scal_VEF::calculer_scal(), Paroi_scal_analytique_VEF::calculer_scal(), Paroi_std_scal_hyd_VEF::calculer_scal(), Echange_contact_ODVM_VDF::calculer_Teta_equiv(), Op_Diff_K_Eps_VEF_base::completer(), Op_Diff_K_Omega_VEF_base::completer(), Transport_K_Eps_Bas_Reynolds::completer(), Modele_turbulence_scal_Fluctuation_Temperature::completer(), Modele_turbulence_scal_Fluctuation_Temperature_W::completer(), Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re::completer(), Op_Diff_DG_Elem::completer(), Op_Dift_EF_base::completer(), Op_Diff_PolyMAC_Elem::completer(), Op_Diff_PolyMAC_Face::completer(), Modele_turbulence_scal_diffturb_base::completer(), Op_Dift_VDF_Face_Axi_base::completer(), Op_Dift_VEF_base::completer(), Champ_Generique_Morceau_Equation::completer(), Champ_Post_Operateur_Eqn::completer(), Op_Diff_Dift_VDF< OP_TYPE >::completer_impl(), Champ_P1NC_implementation::filtrer_L2(), Champ_Generique_Tparoi_VEF::get_champ(), Navier_Stokes_Turbulent_ALE::get_modele(), Convection_Diffusion_Temperature_IBM_Turbulent::get_modele(), Navier_Stokes_IBM_Turbulent::get_modele(), Convection_Diffusion_Chaleur_Turbulent_QC::get_modele(), Convection_Diffusion_Concentration_Turbulent::get_modele(), Convection_Diffusion_Espece_Binaire_Turbulent_QC::get_modele(), Convection_Diffusion_Espece_Multi_Turbulent_QC::get_modele(), Convection_Diffusion_Temperature_Turbulent::get_modele(), Navier_Stokes_Turbulent::get_modele(), Paroi_TBLE_scal_VDF::getLoiParoiHydraulique(), ParoiVEF_TBLE_scal::getLoiParoiHydraulique(), Paroi_TBLE_scal_VDF::init_lois_paroi(), ParoiVEF_TBLE_scal::init_lois_paroi(), Traitement_particulier_NS_Profils::lire(), Y_plus_Champ_Face::me_calculer(), Y_plus_Champ_P1NC::me_calculer(), Champ_Inc_base::mettre_a_jour(), PlaqThVDF::mettre_a_jour(), Convection_Diffusion_Concentration_FT_Disc::mettre_a_jour_chimie(), Convection_Diffusion_Concentration_Turbulent_FT_Disc::mettre_a_jour_chimie(), Modele_turbulence_hyd_K_Eps::preparer_calcul(), Modele_turbulence_hyd_K_Eps_Bicephale::preparer_calcul(), Traitement_particulier_NS_canal::preparer_calcul_particulier(), Modele_turbulence_scal_base::readOn(), Modele_turbulence_scal_null::readOn(), Turbulence_paroi_scal_base::typer_lire_turbulence_paroi_scal(), Op_Diff_PolyMAC_base::update_nu(), Pb_Hydraulique_Turbulent_ALE::verifier(), Pb_Hydraulique_Concentration_Turbulent::verifier(), Pb_Hydraulique_Melange_Binaire_Turbulent_QC::verifier(), Pb_Hydraulique_Turbulent::verifier(), Pb_Thermohydraulique_Concentration_Turbulent::verifier(), Pb_Thermohydraulique_Turbulent::verifier(), and Pb_Thermohydraulique_Turbulent_QC::verifier().
valeur() [2/2]
Objet_U & TRUST_Ref_Objet_U::valeur () inline
operator->() [1/2]
const Objet_U * TRUST_Ref_Objet_U::operator-> () const inline
operator->() [2/2]
Objet_U * TRUST_Ref_Objet_U::operator-> () inline
Member Data Documentation
HAS_POINTER
constexpr bool TRUST_Ref_Objet_U::HAS_POINTER = true static constexpr