TrioCFD: Statistiques_dns_ijk_monophasique Class Reference
Statistiques_dns_ijk_monophasique Class Reference
#include <Statistiques_dns_ijk_monophasique.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Statistiques_dns_ijk
const IJK_Field_double & get_IJK_field (const Motcle &nom) override
const Type_info * get_info () const override
bool is_post_required (const Motcle &nom) const
int lire_motcle_non_standard (const Motcle &mot, Entree &is) override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Public Types inherited from Champs_compris_IJK_interface
using FieldInfo_t = std::tuple< Motcle, Entity, Nature_du_champ, bool >
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Statistiques_dns_ijk_monophasique()
Statistiques_dns_ijk_monophasique::Statistiques_dns_ijk_monophasique ()
References TRUST_Vector< _CLASSE_ >::dimensionner_force(), Statistiques_dns_ijk::noms_moyennes_, and Statistiques_dns_ijk::nval_.
~Statistiques_dns_ijk_monophasique()
Statistiques_dns_ijk_monophasique::~Statistiques_dns_ijk_monophasique ()
Member Function Documentation
cree_instance()
Objet_U * Statistiques_dns_ijk_monophasique::cree_instance () static
taille_memoire()
unsigned Statistiques_dns_ijk_monophasique::taille_memoire () const override virtual
Reimplemented from Statistiques_dns_ijk.
duplique()
int Statistiques_dns_ijk_monophasique::duplique () const override virtual
Reimplemented from Statistiques_dns_ijk.
info()
const Type_info * Statistiques_dns_ijk_monophasique::info () static
get_info()
const Type_info * Statistiques_dns_ijk_monophasique::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Statistiques_dns_ijk.
self_cast() [1/2]
Statistiques_dns_ijk_monophasique & Statistiques_dns_ijk_monophasique::self_cast (Objet_U & r) static
self_cast() [2/2]
const Statistiques_dns_ijk_monophasique & Statistiques_dns_ijk_monophasique::self_cast (const Objet_U & r) static
printOn()
Sortie & Statistiques_dns_ijk_monophasique::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Statistiques_dns_ijk.
References Statistiques_dns_ijk::printOn().
readOn()
Entree & Statistiques_dns_ijk_monophasique::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Statistiques_dns_ijk.
References Statistiques_dns_ijk::readOn().
initialize() [1/3]
void Statistiques_dns_ijk_monophasique::initialize (const Domaine_IJK & geom) override virtual
Reimplemented from Statistiques_dns_ijk.
References Statistiques_dns_ijk::check_converge_, Statistiques_dns_ijk::dx_, Statistiques_dns_ijk::dy_, Statistiques_dns_ijk::elem_coord_, Process::exit(), Domaine_IJK::get_constant_delta(), Domaine_IJK::get_delta(), Domaine_IJK::get_nb_elem_tot(), Domaine_IJK::get_node_coordinates(), Statistiques_dns_ijk::integrale_temporelle_, Process::je_suis_maitre(), Statistiques_dns_ijk::moyenne_spatiale_instantanee_, Statistiques_dns_ijk::nval_, TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), Statistiques_dns_ijk::t_integration_, Statistiques_dns_ijk::tab_dz_, and Statistiques_dns_ijk::vit_moy_.
update_stat()
void Statistiques_dns_ijk_monophasique::update_stat (const IJK_Field_vector3_double & vitesse, const IJK_Field_double & pression, const IJK_Field_double & temperature, double dt)
References Statistiques_dns_ijk::elem_coord_, Process::exit(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
initialize() [2/3]
virtual void Statistiques_dns_ijk::initialize (const Domaine_IJK &) inline virtual
Reimplemented from Statistiques_dns_ijk.
initialize() [3/3]
void Statistiques_dns_ijk::initialize (const Domaine_IJK & geom, const double T_KMAX, const double T_KMIN, const double constante_specifique_gaz) virtual
Reimplemented from Statistiques_dns_ijk.
Member Data Documentation
info_obj
const Type_info Statistiques_dns_ijk_monophasique::info_obj static