TrioCFD: Sous_Domaine_32_64< _SIZE_ > Class Template Reference
Sous_Domaine_32_64< _SIZE_ > Class Template Reference
#include <Sous_Domaine.h>
Public Member Functions
void add_elem (const int_t poly)
int associer_ (Objet_U &) override
const Type_info * get_info () const override
const Nom & le_nom () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
void nommer (const Nom &nom) override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
template<typename _SIZE_>
class Sous_Domaine_32_64< _SIZE_ >
It bears a reference to the Domaine it subdivides
See also
Domaine Sous_Domaines
Member Typedef Documentation
int_t
template<typename _SIZE_ > using Sous_Domaine_32_64< _SIZE_ >::int_t = _SIZE_
ArrOfInt_t
template<typename _SIZE_ > using Sous_Domaine_32_64< _SIZE_ >::ArrOfInt_t = ArrOfInt_T<_SIZE_>
IntVect_t
template<typename _SIZE_ > using Sous_Domaine_32_64< _SIZE_ >::IntVect_t = IntVect_T<_SIZE_>
IntTab_t
template<typename _SIZE_ > using Sous_Domaine_32_64< _SIZE_ >::IntTab_t = IntTab_T<_SIZE_>
SmallArrOfTID_t
template<typename _SIZE_ > using Sous_Domaine_32_64< _SIZE_ >::SmallArrOfTID_t = SmallArrOfTID_T<_SIZE_>
ArrOfDouble_t
template<typename _SIZE_ > using Sous_Domaine_32_64< _SIZE_ >::ArrOfDouble_t = ArrOfDouble_T<_SIZE_>
DoubleVect_t
template<typename _SIZE_ > using Sous_Domaine_32_64< _SIZE_ >::DoubleVect_t = DoubleVect_T<_SIZE_>
DoubleTab_t
template<typename _SIZE_ > using Sous_Domaine_32_64< _SIZE_ >::DoubleTab_t = DoubleTab_T<_SIZE_>
DoubleTabs_t
template<typename _SIZE_ > using Sous_Domaine_32_64< _SIZE_ >::DoubleTabs_t = DoubleTabs_T<_SIZE_>
Domaine_t
template<typename _SIZE_ > using Sous_Domaine_32_64< _SIZE_ >::Domaine_t = Domaine_32_64<_SIZE_>
Constructor & Destructor Documentation
Sous_Domaine_32_64()
template<typename _T_ > Sous_Domaine_32_64< _T_ >::Sous_Domaine_32_64
~Sous_Domaine_32_64()
template<typename _T_ > Sous_Domaine_32_64< _T_ >::~Sous_Domaine_32_64
Member Function Documentation
cree_instance()
template<typename _T_ > Objet_U * Sous_Domaine_32_64< _T_ >::cree_instance static
taille_memoire()
template<typename _T_ > unsigned Sous_Domaine_32_64< _T_ >::taille_memoire override virtual
Implements Objet_U.
duplique()
template<typename _T_ > int Sous_Domaine_32_64< _T_ >::duplique override virtual
Implements Objet_U.
info()
template<typename _T_ > const Type_info * Sous_Domaine_32_64< _T_ >::info static
get_info()
template<typename _T_ > const Type_info * Sous_Domaine_32_64< _T_ >::get_info override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
template<typename _T_ > Sous_Domaine_32_64< _T_ > & Sous_Domaine_32_64< _T_ >::self_cast (Objet_U & r) static
self_cast() [2/2]
template<typename _T_ > const Sous_Domaine_32_64< _T_ > & Sous_Domaine_32_64< _T_ >::self_cast (const Objet_U & r) static
printOn()
template<typename _SIZE_ > Sortie & Sous_Domaine_32_64< _SIZE_ >::printOn (Sortie & os) const override protected virtual
Ecrit la liste des polyedres de la sous-domaine sur un flot de sortie.
Format: Liste n1 n2 .. Ni
Parameters
(Sortie& os) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Objet_U.
readOn()
template<typename _SIZE_ > Entree & Sous_Domaine_32_64< _SIZE_ >::readOn (Entree & is) override protected virtual
Lit les specifications d'un sous-domaine dans le jeu de donnee a partir d'un flot d'entree.
Format: { Rectangle Origine x0 y0 Cotes lx ly } en dimension 2 { Boite Origine x0 y0 z0 Cotes lx ly lz} en dimension 3 ou { Liste n n1 ni nn } ou { Intervalle n1 n2 } ou { Polynomes {bloc_lecture_poly1 et bloc_lecture_poly_i et bloc_lecture_poly_n} }
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Exceptions
accolade ouvrante attendue
mot clef non reconnu
mot clef "et" ou "}" attendu
En dimension 2, il faut utiliser Rectangle
mot clef "Origine" attendu
mot clef "Cotes" attendu
En dimension 3, il faut utiliser Boite
Erreur TRUST (mot clef reconnu non prevu)
accolade fermante attendue
Reimplemented from Objet_U.
References Parser_U::addVar(), Domaine_32_64< _SIZE_ >::coord(), Domaine_32_64< _SIZE_ >::creer_tableau_elements(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Parser_U::eval(), Process::exit(), Process::is_parallel(), Domaine_32_64< _SIZE_ >::nb_elem(), Domaine_32_64< _SIZE_ >::nb_elem_tot(), Sous_Domaine_32_64< _SIZE_ >::nb_elem_tot(), Domaine_32_64< _SIZE_ >::nb_som_elem(), Entree_Fichier_base::ouvrir(), Parser_U::parseString(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), Motcles::search(), Parser_U::setNbVar(), Parser_U::setString(), Parser_U::setVar(), and Domaine_32_64< _SIZE_ >::sommet_elem().
lire_motcle_non_standard()
template<typename _SIZE_ > int Sous_Domaine_32_64< _SIZE_ >::lire_motcle_non_standard (const Motcle & motlu, Entree & is) inline override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Objet_U.
le_nom()
template<typename _SIZE_ > const Nom & Sous_Domaine_32_64< _SIZE_ >::le_nom () const inline override virtual
Donne le nom de l'Objet_U Methode a surcharger : renvoie "neant" dans cette implementation.
Returns
(Nom&) le nom de l'Objet_U
Reimplemented from Objet_U.
References Sous_Domaine_32_64< _SIZE_ >::nom_.
Referenced by Partitionneur_Sous_Domaines::construire_partition(), Postraiter_domaine::ecrire(), Interprete_geometrique_base_32_64< _SIZE_ >::mettre_a_jour_sous_domaine(), and Champ_Fonc_Tabule_Morceaux::readOn().
operator()()
template<typename _SIZE_ > int_t Sous_Domaine_32_64< _SIZE_ >::operator() (int_t i) const inline
References Sous_Domaine_32_64< _SIZE_ >::les_elems_.
operator[]()
template<typename _SIZE_ > int_t Sous_Domaine_32_64< _SIZE_ >::operator[] (int_t i) const inline
References Sous_Domaine_32_64< _SIZE_ >::les_elems_.
nb_elem_tot()
template<typename _SIZE_ > int_t Sous_Domaine_32_64< _SIZE_ >::nb_elem_tot () const inline
References Sous_Domaine_32_64< _SIZE_ >::les_elems_, and TRUSTVect< _TYPE_, _SIZE_ >::size().
Referenced by Perte_Charge_PolyMAC::ajouter(), Perte_Charge_PolyMAC::ajouter_blocs(), Perte_Charge_VDF_base::ajouter_blocs(), Eval_Puiss_Neutr_VDF_Elem::associer_repartition(), Refine_Mesh::build_new_sub_domaines_descriptions(), Partitionneur_Sous_Domaines::construire_partition(), Partitionneur_Union::construire_partition(), Perte_Charge_PolyMAC::contribuer_a_avec(), Transport_Interfaces_FT_Disc::deplacer_maillage_ft_v_fluide(), Postraiter_domaine::ecrire(), Champ_val_tot_sur_vol_VDF::eval_contrib_loc(), Champ_val_tot_sur_vol_VEF::eval_contrib_loc(), Champ_val_tot_sur_vol_base::evaluer(), Ensemble_Lagrange_base::generer_marqueurs_sz(), Create_domain_from_sub_domain::interpreter_(), Extraire_domaine::interpreter_(), Perte_Charge_Singuliere::lire_surfaces(), Convection_Diffusion_Concentration_FT_Disc::marquer_faces_sous_domaine(), Convection_Diffusion_Concentration_Turbulent_FT_Disc::marquer_faces_sous_domaine(), Champ_Uniforme_Morceaux_Tabule_Temps::me_calculer(), Frontiere_ouverte_vitesse_vortex::mettre_a_jour(), Convection_Diffusion_Temperature_FT_Disc::mettre_a_jour(), Interprete_geometrique_base_32_64< _SIZE_ >::mettre_a_jour_sous_domaine(), Champ_input_P0::readOn(), Champ_Fonc_Tabule_Morceaux::readOn(), Champ_Uniforme_Morceaux::readOn(), Sous_Domaine_32_64< _SIZE_ >::readOn(), Porosites::remplir_champ(), Perte_Charge_Reguliere_VDF_Face::remplir_num_faces(), Perte_Charge_Reguliere_VEF_P1NC::remplir_num_faces(), Champ_input_P0::setValue(), and Transport_Interfaces_FT_Disc::test_suppression_interfaces_sous_domaine().
associer_domaine()
template<typename _SIZE_ > void Sous_Domaine_32_64< _SIZE_ >::associer_domaine (const Domaine_t & d) inline
References Sous_Domaine_32_64< _SIZE_ >::le_dom_.
associer_()
template<typename _SIZE_ > int Sous_Domaine_32_64< _SIZE_ >::associer_ (Objet_U & ob) override virtual
Associe un Objet_U au sous-domaine.
On controle le type de l'objet a associer dynamiquement.
Parameters
(Objet_U& ob) objet a associer au sous-domaine.
Returns
(int) renvoie 1 si l'association a reussi 0 sinon.
Reimplemented from Objet_U.
References Objet_U::associer_().
nommer()
template<typename _SIZE_ > void Sous_Domaine_32_64< _SIZE_ >::nommer (const Nom &) inline override virtual
Donne un nom a l'Objet_U Methode virtuelle a surcharger.
Parameters
(const Nom&) le nom a affectuer a l'Objet_U
Reimplemented from Objet_U.
References Sous_Domaine_32_64< _SIZE_ >::nom_.
add_elem()
template<typename _SIZE_ > void Sous_Domaine_32_64< _SIZE_ >::add_elem (const int_t poly)
Ajoute un polyedre au sous-domaine.
Returns
(int)
Referenced by Interprete_geometrique_base_32_64< _SIZE_ >::mettre_a_jour_sous_domaine().
les_elems() [1/2]
template<typename _SIZE_ > const IntVect_t & Sous_Domaine_32_64< _SIZE_ >::les_elems () const inline
References Sous_Domaine_32_64< _SIZE_ >::les_elems_.
les_elems() [2/2]
template<typename _SIZE_ > IntVect_t & Sous_Domaine_32_64< _SIZE_ >::les_elems () inline
References Sous_Domaine_32_64< _SIZE_ >::les_elems_.
domaine() [1/2]
template<typename _SIZE_ > Domaine_t & Sous_Domaine_32_64< _SIZE_ >::domaine () inline
References Sous_Domaine_32_64< _SIZE_ >::le_dom_.
Referenced by Domaine_dis_base::discretiser_root(), and Postraitement::lire_motcle_non_standard().
domaine() [2/2]
template<typename _SIZE_ > const Domaine_t & Sous_Domaine_32_64< _SIZE_ >::domaine () const inline
References Sous_Domaine_32_64< _SIZE_ >::le_dom_.
info_obj() [1/2]
const Type_info Sous_Domaine_32_64< int >::info_obj ("Sous_Domaine" , Sous_Domaine_32_64< int >::cree_instance , 1 , Sous_Domaine_32_64bases< int >)
info_obj() [2/2]
const Type_info Sous_Domaine_32_64< trustIdType >::info_obj ("Sous_Domaine" "_64" , Sous_Domaine_32_64< trustIdType >::cree_instance , 1 , Sous_Domaine_32_64bases< trustIdType >)
Member Data Documentation
info_obj
template<typename _SIZE_ > const Type_info Sous_Domaine_32_64< _SIZE_ >::info_obj static
les_elems_
template<typename _SIZE_ > IntVect_t Sous_Domaine_32_64< _SIZE_ >::les_elems_ protected
Referenced by Sous_Domaine_32_64< _SIZE_ >::les_elems(), Sous_Domaine_32_64< _SIZE_ >::nb_elem_tot(), Sous_Domaine_32_64< _SIZE_ >::operator()(), and Sous_Domaine_32_64< _SIZE_ >::operator[]().
le_dom_
template<typename _SIZE_ > TRUST_Ref< Domaine_t *> Sous_Domaine_32_64< _SIZE_ >::le_dom_ protected
Referenced by Sous_Domaine_32_64< _SIZE_ >::associer_domaine(), and Sous_Domaine_32_64< _SIZE_ >::domaine().
nom_
template<typename _SIZE_ > Nom Sous_Domaine_32_64< _SIZE_ >::nom_ protected
Referenced by Sous_Domaine_32_64< _SIZE_ >::le_nom(), and Sous_Domaine_32_64< _SIZE_ >::nommer().