TrioCFD: Acceleration_QC_VEF_P1NC Class Reference
Acceleration_QC_VEF_P1NC Class Reference
#include <Source_QC_VEF_P1NC.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Terme_Source_Acceleration_VEF_Face
DoubleTab & ajouter (DoubleTab &) const override
void associer_champ_rho (const Champ_base &champ_rho) override
const Type_info * get_info () const override
Public Member Functions inherited from Terme_Source_Acceleration
int a_pour_Champ_Fonc (const Motcle &mot, TRUST_Ref< Champ_base * > &ch_ref) const override
const Type_info * get_info () const override
Public Member Functions inherited from Source_base
virtual int a_pour_Champ_Fonc (const Motcle &mot, TRUST_Ref< Champ_base * > &ch_ref) const
virtual void associer_champ_rho (const Champ_base &champ_rho)
virtual void completer ()
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
virtual void resetTime (double t)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Protected Member Functions inherited from Terme_Source_Acceleration_VEF_Face
void associer_domaines (const Domaine_dis_base &, const Domaine_Cl_dis_base &) override
const DoubleTab & calculer_vitesse_faces (DoubleTab &v_faces_stockage) const override
Sortie & printOn (Sortie &x) const override
Protected Member Functions inherited from Terme_Source_Acceleration
const DoubleTab & calculer_la_source (DoubleTab &src_faces) const
virtual void lire_data (Entree &s)
Sortie & printOn (Sortie &x) const override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Acceleration_QC_VEF_P1NC()
Acceleration_QC_VEF_P1NC::Acceleration_QC_VEF_P1NC ()
~Acceleration_QC_VEF_P1NC()
Acceleration_QC_VEF_P1NC::~Acceleration_QC_VEF_P1NC ()
Member Function Documentation
cree_instance()
Objet_U * Acceleration_QC_VEF_P1NC::cree_instance () static
taille_memoire()
unsigned Acceleration_QC_VEF_P1NC::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Acceleration_QC_VEF_P1NC::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Acceleration_QC_VEF_P1NC::info () static
get_info()
const Type_info * Acceleration_QC_VEF_P1NC::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Terme_Source_Acceleration.
self_cast() [1/2]
Acceleration_QC_VEF_P1NC & Acceleration_QC_VEF_P1NC::self_cast (Objet_U & r) static
self_cast() [2/2]
const Acceleration_QC_VEF_P1NC & Acceleration_QC_VEF_P1NC::self_cast (const Objet_U & r) static
printOn()
Sortie & Acceleration_QC_VEF_P1NC::printOn (Sortie & os) const override protected virtual
DOES NOTHING - to override in derived classes.
Imprime la source sur un flot de sortie.
Parameters
(Sortie& os) le flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Terme_Source_Acceleration.
References Terme_Source_Acceleration_VEF_Face::printOn().
readOn()
Entree & Acceleration_QC_VEF_P1NC::readOn (Entree & s) override protected virtual
Appel a Terme_Source_Acceleration::lire_data.
Reimplemented from Terme_Source_Acceleration.
References Terme_Source_Acceleration_VEF_Face::readOn().
contribuer_a_avec()
void Acceleration_QC_VEF_P1NC::contribuer_a_avec (const DoubleTab & , Matrice_Morse & mat) const override virtual
contribution a la matrice implicite des termes sources par defaut pas de contribution
Reimplemented from Source_base.
References Source_Fluide_Dilatable_Face< Acceleration_QC_VEF_P1NC >::contribuer_a_avec_impl().
ajouter()
DoubleTab & Acceleration_QC_VEF_P1NC::ajouter (DoubleTab & resu) const override virtual
Reimplemented from Source_base.
References Source_Fluide_Dilatable_Face< Acceleration_QC_VEF_P1NC >::ajouter_impl().
ajouter_mere()
DoubleTab & Acceleration_QC_VEF_P1NC::ajouter_mere (DoubleTab & resu) const
References Terme_Source_Acceleration_VEF_Face::ajouter().
Member Data Documentation
info_obj
const Type_info Acceleration_QC_VEF_P1NC::info_obj static