TrioCFD: Transport_K_ou_Eps_base Class Reference
Transport_K_ou_Eps_base Class Reference
#include <Transport_K_ou_Eps_base.h>
Public Member Functions
virtual int controler_variable ()
void discretiser () override
const Type_info * get_info () const override
const Champ_Inc_base & inconnue () const override
Champ_Inc_base & inconnue () override
Public Member Functions inherited from Transport_2eq_base
void associer_milieu_base (const Milieu_base &) override
double calculer_pas_de_temps () const override
const Type_info * get_info () const override
const Milieu_base & milieu () const override
Milieu_base & milieu () override
Modele_turbulence_hyd_2_eq_base & modele_turbulence ()
const Modele_turbulence_hyd_2_eq_base & modele_turbulence () const
Public Member Functions inherited from Equation_base
virtual void abortTimeStep ()
virtual void associer_domaine_dis (const Domaine_dis_base &)
virtual void associer_pb_base (const Probleme_base &)
virtual void associer_sch_tps_base (const Schema_Temps_base &)
virtual double calculer_pas_de_temps () const
virtual void completer ()
virtual std::vector< YAML_data > data_a_sauvegarder () const
DoubleTab & derivee_en_temps_conv (DoubleTab &, const DoubleTab &)
virtual DoubleTab & derivee_en_temps_inco (DoubleTab &)
const Discretisation_base & discretisation () const
virtual void discretiser ()
virtual const Motcle & domaine_application () const
virtual Domaine_Cl_dis_base & domaine_Cl_dis ()
virtual const Domaine_Cl_dis_base & domaine_Cl_dis () const
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual void imprimer (Sortie &os) const
virtual bool initTimeStep (double dt)
const Nom & le_nom () const override
int limpr () const
virtual void mettre_a_jour (double temps)
virtual int preparer_calcul ()
Probleme_base & probleme ()
const Probleme_base & probleme () const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Schema_Temps_base & schema_temps ()
const Schema_Temps_base & schema_temps () const
Solveur_Masse_base & solv_masse ()
const Solveur_Masse_base & solv_masse () const
Sources & sources ()
const Sources & sources () const
virtual void valider_iteration ()
virtual void verifie_ch_init_nb_comp (const Champ_Inc_base &ch_ref, const int nb_comp) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Equation_base
virtual Entree & lire_cl (Entree &)
virtual Entree & lire_cond_init (Entree &)
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual Entree & lire_sources (Entree &)
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
virtual int verif_Cl () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
de transport des modeles k_Epsilon dans une approche ou K et Epsilon sont traites par deux equations differentes.
Constructor & Destructor Documentation
Transport_K_ou_Eps_base()
Transport_K_ou_Eps_base::Transport_K_ou_Eps_base ()
~Transport_K_ou_Eps_base()
Transport_K_ou_Eps_base::~Transport_K_ou_Eps_base () override
Member Function Documentation
info()
const Type_info * Transport_K_ou_Eps_base::info () static
get_info()
const Type_info * Transport_K_ou_Eps_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Transport_2eq_base.
Reimplemented in Transport_K_ou_Eps_non_std, and Transport_K_ou_Eps_Realisable.
self_cast() [1/2]
Transport_K_ou_Eps_base & Transport_K_ou_Eps_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Transport_K_ou_Eps_base & Transport_K_ou_Eps_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Transport_K_ou_Eps_base::printOn (Sortie & is) const override protected virtual
Parameters
(Sortie& is) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Transport_2eq_base.
Reimplemented in Transport_K_ou_Eps_non_std, and Transport_K_ou_Eps_Realisable.
References Objet_U::que_suis_je().
readOn()
Entree & Transport_K_ou_Eps_base::readOn (Entree & is) override protected virtual
Simple appel a Equation_base::readOn(Entree&)
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Transport_2eq_base.
Reimplemented in Transport_K_ou_Eps_non_std, and Transport_K_ou_Eps_Realisable.
References Equation_base::readOn().
Referenced by Transport_K_ou_Eps::readOn(), Transport_K_ou_Eps_non_std::readOn(), and Transport_K_ou_Eps_Realisable::readOn().
discretiser()
void Transport_K_ou_Eps_base::discretiser () override virtual
Discretise l'equation.
Type le domaine_Cl_dis, la formatte, l'associe a l'equation. Type le solveur masse, lui associe le domaine discretisee et le domaine des conditions aux limites discretisees.
Reimplemented from Equation_base.
References Champs_compris_T< FIELD_TYPE >::ajoute_champ(), Equation_base::calculate_time_derivative(), Equation_base::champs_compris_, Equation_base::creer_champ(), Equation_base::discretisation(), Equation_base::discretiser(), Discretisation_base::discretiser_champ(), Equation_base::domaine_dis(), Process::exit(), le_champ_, Transport_2eq_base::modele_turbulence(), Field_base::nommer(), Objet_U::que_suis_je(), Equation_base::schema_temps(), Equation_base::set_calculate_time_derivative(), and transporte_K_.
Referenced by Transport_K_ou_Eps::associer_modele_turbulence(), and Transport_K_ou_Eps_Realisable::associer_modele_turbulence().
controler_variable()
int Transport_K_ou_Eps_base::controler_variable () virtual
Controle le champ inconnue K-epsilon en forcant a zero les valeurs du champ.
inferieurs a 1.e-10.
Returns
(int) renvoie toujours 1
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Domaine_dis_base::domaine(), Equation_base::domaine_dis(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_VF::elem_faces(), MorEqn::equation(), Process::exit(), Domaine_VF::face_voisins(), Modele_turbulence_hyd_2_eq_base::get_EPS_MAX(), Modele_turbulence_hyd_2_eq_base::get_EPS_MIN(), Modele_turbulence_hyd_2_eq_base::get_K_MIN(), Modele_turbulence_hyd_2_eq_base::get_lquiet(), Probleme_base::is_dilatable(), Process::je_suis_maitre(), le_champ_, Schema_Temps_base::limpr(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Transport_2eq_base::modele_turbulence(), Domaine_32_64< _SIZE_ >::nb_elem(), Process::nproc(), Probleme_base::postraiter(), Equation_base::probleme(), Equation_base::schema_temps(), Champ_base::temps(), transporte_K_, TRUST_Deriv< _CLASSE_ >::valeur(), Champ_Inc_base::valeurs(), Debog::verifier(), Domaine_VF::xp(), and Domaine_VF::xv().
Referenced by Modele_turbulence_hyd_K_Eps_Bicephale::controler(), Modele_turbulence_hyd_K_Eps_Realisable_Bicephale::controler(), and valider_iteration().
valider_iteration()
void Transport_K_ou_Eps_base::valider_iteration () override virtual
on remet eps et K positifs
Reimplemented from Equation_base.
References controler_variable().
inconnue() [1/2]
const Champ_Inc_base & Transport_K_ou_Eps_base::inconnue () const inline override virtual
Renvoie le champ inconnue de l'equation.
Un champ vecteur contenant K ou epsilon. (version const)
Returns
(Champ_Inc_base&) le champ inconnue de l'equation
Implements Equation_base.
References le_champ_.
Referenced by Modele_turbulence_hyd_K_Eps_Bicephale::calculer_viscosite_turbulente(), Modele_turbulence_hyd_K_Eps_Realisable_Bicephale::calculer_viscosite_turbulente(), Modele_turbulence_hyd_K_Eps_Realisable_Bicephale::Eps(), Modele_turbulence_hyd_K_Eps_Bicephale::Eps(), Modele_turbulence_hyd_K_Eps_Realisable_Bicephale::K(), Modele_turbulence_hyd_K_Eps_Bicephale::K(), and Op_Diff_K_Eps_VDF_base::modifier_pour_Cl().
inconnue() [2/2]
Champ_Inc_base & Transport_K_ou_Eps_base::inconnue () inline override virtual
Renvoie le champ inconnue de l'equation.
Un champ vecteur contenant K ou epsilon.
Returns
(Champ_Inc_base&) le champ inconnue de l'equation
Implements Equation_base.
References le_champ_.
get_champ()
const Champ_base & Transport_K_ou_Eps_base::get_champ (const Motcle & nom) const override virtual
Reimplemented from Equation_base.
References Equation_base::champs_compris_, Champs_compris_T< FIELD_TYPE >::get_champ(), Nom::getString(), Equation_base::has_champ(), le_champ_, Champ_Fonc_base::mettre_a_jour(), residu_, Equation_base::schema_temps(), Champ_base::temps(), Schema_Temps_base::temps_init(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by has_champ().
has_champ() [1/2]
bool Transport_K_ou_Eps_base::has_champ (const Motcle & nom, TRUST_Ref< Champ_base * > & ref_champ) const override virtual
Reimplemented from Equation_base.
References get_champ(), and Equation_base::has_champ().
has_champ() [2/2]
bool Transport_K_ou_Eps_base::has_champ (const Motcle & nom) const override virtual
Reimplemented from Equation_base.
References Equation_base::has_champ().
transporte_K()
void Transport_K_ou_Eps_base::transporte_K () inline
References transporte_K_.
Referenced by Modele_turbulence_hyd_RANS_Bicephale_base::lire_motcle_non_standard().
transporte_Eps()
void Transport_K_ou_Eps_base::transporte_Eps () inline
References transporte_K_.
Referenced by Modele_turbulence_hyd_RANS_Bicephale_base::lire_motcle_non_standard().
transporte_t_il_K()
bool Transport_K_ou_Eps_base::transporte_t_il_K () const inline
References transporte_K_.
Referenced by Op_Diff_K_Eps_VDF_base::completer(), and Op_Diff_K_Eps_VEF_base::completer().
Member Data Documentation
info_obj
const Type_info Transport_K_ou_Eps_base::info_obj static
le_champ_
TRUST_Deriv< Champ_Inc_base > Transport_K_ou_Eps_base::le_champ_ protected
Referenced by controler_variable(), discretiser(), get_champ(), and inconnue().
residu_
TRUST_Deriv< Champ_Fonc_base > Transport_K_ou_Eps_base::residu_ protected
Referenced by get_champ().
transporte_K_
bool Transport_K_ou_Eps_base::transporte_K_ protected
Referenced by controler_variable(), discretiser(), Transport_K_ou_Eps::readOn(), Transport_K_ou_Eps_Realisable::readOn(), transporte_Eps(), transporte_K(), and transporte_t_il_K().