TrioCFD: IJK_Ghost_Fluid_Fields Class Reference
IJK_Ghost_Fluid_Fields Class Reference
#include <IJK_Ghost_Fluid_Fields.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Public Types inherited from Champs_compris_IJK_interface
using FieldInfo_t = std::tuple< Motcle, Entity, Nature_du_champ, bool >
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
IJK_Ghost_Fluid_Fields()
IJK_Ghost_Fluid_Fields::IJK_Ghost_Fluid_Fields ()
~IJK_Ghost_Fluid_Fields()
IJK_Ghost_Fluid_Fields::~IJK_Ghost_Fluid_Fields ()
Member Function Documentation
cree_instance()
Objet_U * IJK_Ghost_Fluid_Fields::cree_instance () static
taille_memoire()
unsigned IJK_Ghost_Fluid_Fields::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int IJK_Ghost_Fluid_Fields::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * IJK_Ghost_Fluid_Fields::info () static
get_info()
const Type_info * IJK_Ghost_Fluid_Fields::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
IJK_Ghost_Fluid_Fields & IJK_Ghost_Fluid_Fields::self_cast (Objet_U & r) static
self_cast() [2/2]
const IJK_Ghost_Fluid_Fields & IJK_Ghost_Fluid_Fields::self_cast (const Objet_U & r) static
printOn()
Sortie & IJK_Ghost_Fluid_Fields::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
References Objet_U::printOn().
readOn()
Entree & IJK_Ghost_Fluid_Fields::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
References Objet_U::readOn().
associer()
void IJK_Ghost_Fluid_Fields::associer (const Probleme_FTD_IJK_base & ijk_ft)
References ref_ijk_ft_.
Referenced by IJK_Thermals::completer().
initialize()
void IJK_Ghost_Fluid_Fields::initialize (const Domaine_IJK & splitting)
References IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::allocate(), avoid_gfm_parallel_calls_, compute_curvature_, compute_distance_, IJK_Field_vector< T, N >::echange_espace_virtuel(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel(), Domaine_IJK::ELEM, eulerian_curvature_ft_, eulerian_curvature_ns_, eulerian_distance_ft_, eulerian_distance_ns_, eulerian_facets_barycentre_ft_, eulerian_facets_barycentre_ns_, eulerian_interfacial_area_ft_, eulerian_interfacial_area_ns_, eulerian_normal_vectors_ft_, eulerian_normal_vectors_ns_, eulerian_normal_vectors_ns_normed_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost(), n_iter_distance_, nb_cells_gfm_parallel_calls_, ref_ijk_ft_, tmp_interf_cells_, tmp_new_curv_val_, tmp_new_dist_val_, tmp_new_vector_val_, tmp_old_curv_val_, tmp_old_dist_val_, tmp_old_vector_val_, tmp_propagated_cells_, and use_n_iter_distance_.
Referenced by IJK_Thermals::initialize().
has_champ() [1/2]
bool IJK_Ghost_Fluid_Fields::has_champ (const Motcle & nom) const override virtual
Implements Champs_compris_IJK_interface.
References champs_compris_, Noms::contient_(), Champs_compris_T< FIELD_TYPE >::has_champ(), Champs_compris_IJK::has_champ_vectoriel(), Champs_compris_IJK::liste_noms_compris(), and Champs_compris_IJK::liste_noms_compris_vectoriel().
Referenced by IJK_Thermals::get_IJK_field(), IJK_Thermals::get_IJK_field_vector(), and IJK_Thermals::has_champ().
has_champ() [2/2]
bool IJK_Ghost_Fluid_Fields::has_champ (const Motcle & nom, TRUST_Ref< Champ_base * > & ref_champ) const inline
has_champ_vectoriel()
bool IJK_Ghost_Fluid_Fields::has_champ_vectoriel (const Motcle & nom) const inline override virtual
Implements Champs_compris_IJK_interface.
get_IJK_field()
const IJK_Field_double & IJK_Ghost_Fluid_Fields::get_IJK_field (const Motcle & nom) override virtual
Implements Champs_compris_IJK_interface.
References champs_compris_, Noms::contient_(), Champs_compris_T< FIELD_TYPE >::get_champ(), and Champs_compris_IJK::liste_noms_compris().
Referenced by IJK_Thermals::get_IJK_field().
get_IJK_field_vector()
const IJK_Field_vector3_double & IJK_Ghost_Fluid_Fields::get_IJK_field_vector (const Motcle & nom) override virtual
Implements Champs_compris_IJK_interface.
References champs_compris_, Noms::contient_(), Champs_compris_IJK::get_champ_vectoriel(), and Champs_compris_IJK::liste_noms_compris_vectoriel().
Referenced by IJK_Thermals::get_IJK_field_vector().
Fill_postprocessable_fields()
void IJK_Ghost_Fluid_Fields::Fill_postprocessable_fields (std::vector< FieldInfo_t > & chps) static
Referenced by Probleme_FTD_IJK_base::Fill_postprocessable_fields().
get_noms_champs_postraitables()
void IJK_Ghost_Fluid_Fields::get_noms_champs_postraitables (Noms & noms, Option opt = NONE) const
References TRUST_Vector< _CLASSE_ >::add(), champs_compris_, Champs_compris_IJK::liste_noms_compris(), and Champs_compris_IJK::liste_noms_compris_vectoriel().
Referenced by IJK_Thermals::get_noms_champs_postraitables().
compute_eulerian_distance()
void IJK_Ghost_Fluid_Fields::compute_eulerian_distance ()
References avoid_gfm_parallel_calls_, compute_distance_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::data(), IJK_Field_vector< T, N >::echange_espace_virtuel(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel(), eulerian_distance_ft_, eulerian_distance_ns_, eulerian_facets_barycentre_ft_, eulerian_facets_barycentre_ns_, eulerian_normal_vectors_ft_, eulerian_normal_vectors_ns_, eulerian_normal_vectors_ns_normed_, gfm_first_cells_indices_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost(), has_computed_distance_, interf_cells_indices_, n_iter_distance_, propagated_cells_indices_, Navier_Stokes_FTD_IJK::redistribute_from_splitting_ft_elem(), ref_ijk_ft_, tmp_interf_cells_, tmp_new_dist_val_, tmp_new_vector_val_, tmp_old_dist_val_, tmp_old_vector_val_, and tmp_propagated_cells_.
Referenced by IJK_Thermals::compute_eulerian_distance().
enforce_zero_value_eulerian_distance()
void IJK_Ghost_Fluid_Fields::enforce_zero_value_eulerian_distance ()
References compute_distance_, eulerian_distance_ft_, and eulerian_distance_ns_.
Referenced by enforce_distance_curvature_values_for_post_processings().
enforce_distance_curvature_values_for_post_processings()
void IJK_Ghost_Fluid_Fields::enforce_distance_curvature_values_for_post_processings ()
References enforce_max_value_eulerian_curvature(), enforce_zero_value_eulerian_distance(), and eulerian_interfacial_area_ft_.
Referenced by IJK_Thermals::euler_time_step().
compute_eulerian_curvature_from_interface()
void IJK_Ghost_Fluid_Fields::compute_eulerian_curvature_from_interface ()
References compute_curvature_, IJK_Field_vector< T, N >::echange_espace_virtuel(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel(), eulerian_curvature_ft_, eulerian_curvature_ns_, eulerian_interfacial_area_ft_, eulerian_interfacial_area_ns_, eulerian_normal_vectors_ft_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost(), has_computed_curvature_, n_iter_distance_, ref_ijk_ft_, tmp_new_curv_val_, and tmp_old_curv_val_.
Referenced by IJK_Thermals::compute_eulerian_curvature_from_interface().
compute_eulerian_curvature()
void IJK_Ghost_Fluid_Fields::compute_eulerian_curvature ()
References boundary_flux_kmax_, boundary_flux_kmin_, compute_curvature_, IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel(), eulerian_curvature_ft_, eulerian_curvature_ns_, eulerian_distance_ft_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost(), and ref_ijk_ft_.
Referenced by IJK_Thermals::compute_eulerian_curvature().
enforce_zero_value_eulerian_curvature()
void IJK_Ghost_Fluid_Fields::enforce_zero_value_eulerian_curvature ()
References compute_curvature_, and eulerian_curvature_ft_.
enforce_max_value_eulerian_curvature()
void IJK_Ghost_Fluid_Fields::enforce_max_value_eulerian_curvature ()
References compute_curvature_, eulerian_curvature_ft_, and eulerian_curvature_ns_.
Referenced by enforce_distance_curvature_values_for_post_processings().
reset_field_computations()
void IJK_Ghost_Fluid_Fields::reset_field_computations () inline
References has_computed_curvature_, and has_computed_distance_.
retrieve_ghost_fluid_params()
void IJK_Ghost_Fluid_Fields::retrieve_ghost_fluid_params (const int & compute_distance, const int & compute_curvature, const int & n_iter_distance, const int & avoid_gfm_parallel_calls, const IJK_Field_local_double & boundary_flux_kmin, const IJK_Field_local_double & boundary_flux_kmax) inline
References avoid_gfm_parallel_calls_, boundary_flux_kmax_, boundary_flux_kmin_, compute_curvature_, compute_distance_, n_iter_distance_, nb_cells_gfm_parallel_calls_, and use_n_iter_distance_.
Referenced by IJK_Thermals::retrieve_ghost_fluid_params().
get_eulerian_distance_ft()
const IJK_Field_double & IJK_Ghost_Fluid_Fields::get_eulerian_distance_ft () const inline
References eulerian_distance_ft_.
Referenced by IJK_Thermal_base::get_eulerian_distance_ft(), and IJK_Thermal_base::initialize().
get_eulerian_distance_ns()
const IJK_Field_double & IJK_Ghost_Fluid_Fields::get_eulerian_distance_ns () const inline
References eulerian_distance_ns_.
Referenced by IJK_Thermal_base::get_eulerian_distance_ns(), and IJK_Thermal_base::initialize().
get_eulerian_normal_vectors_ft()
const IJK_Field_vector3_double & IJK_Ghost_Fluid_Fields::get_eulerian_normal_vectors_ft () const inline
References eulerian_normal_vectors_ft_.
Referenced by IJK_Thermal_base::get_normal_vector_ft(), and IJK_Thermal_base::initialize().
get_eulerian_facets_barycentre_ft()
const IJK_Field_vector3_double & IJK_Ghost_Fluid_Fields::get_eulerian_facets_barycentre_ft () const inline
References eulerian_facets_barycentre_ft_.
Referenced by IJK_Thermal_base::get_bary(), and IJK_Thermal_base::initialize().
get_eulerian_normal_vectors_ns()
const IJK_Field_vector3_double & IJK_Ghost_Fluid_Fields::get_eulerian_normal_vectors_ns () const inline
References eulerian_normal_vectors_ns_.
Referenced by IJK_Thermal_base::get_normal_vector_ns(), and IJK_Thermal_base::initialize().
get_eulerian_normal_vectors_ns_normed()
const IJK_Field_vector3_double & IJK_Ghost_Fluid_Fields::get_eulerian_normal_vectors_ns_normed () const inline
References eulerian_normal_vectors_ns_normed_.
Referenced by IJK_Thermal_base::get_normal_vector_ns_normed(), and IJK_Thermal_base::initialize().
get_eulerian_facets_barycentre_ns()
const IJK_Field_vector3_double & IJK_Ghost_Fluid_Fields::get_eulerian_facets_barycentre_ns () const inline
References eulerian_facets_barycentre_ns_.
Referenced by IJK_Thermal_base::initialize().
get_eulerian_curvature_ft()
const IJK_Field_double & IJK_Ghost_Fluid_Fields::get_eulerian_curvature_ft () const inline
References eulerian_curvature_ft_.
Referenced by IJK_Thermal_base::get_eulerian_curvature_ft(), and IJK_Thermal_base::initialize().
get_eulerian_curvature_ns()
const IJK_Field_double & IJK_Ghost_Fluid_Fields::get_eulerian_curvature_ns () const inline
References eulerian_curvature_ns_.
Referenced by IJK_Thermal_base::get_eulerian_curvature_ns(), and IJK_Thermal_base::initialize().
get_eulerian_interfacial_area_ft()
const IJK_Field_double & IJK_Ghost_Fluid_Fields::get_eulerian_interfacial_area_ft () const inline
References eulerian_interfacial_area_ft_.
Referenced by IJK_Thermal_base::get_interfacial_area_ft(), and IJK_Thermal_base::initialize().
get_eulerian_interfacial_area_ns()
const IJK_Field_double & IJK_Ghost_Fluid_Fields::get_eulerian_interfacial_area_ns () const inline
References eulerian_interfacial_area_ns_.
Referenced by IJK_Thermal_base::get_interfacial_area_ns(), and IJK_Thermal_base::initialize().
get_eulerian_rising_velocities()
const IJK_Field_double & IJK_Ghost_Fluid_Fields::get_eulerian_rising_velocities () const inline
References eulerian_rising_velocities_.
get_dummy_int_vect()
const IJK_Field_vector3_int & IJK_Ghost_Fluid_Fields::get_dummy_int_vect () const inline
References dummy_int_vect_.
get_dummy_double_vect()
const IJK_Field_vector3_double & IJK_Ghost_Fluid_Fields::get_dummy_double_vect () const inline
References dummy_double_vect_.
get_dummy_int_field()
const IJK_Field_int & IJK_Ghost_Fluid_Fields::get_dummy_int_field () const inline
References dummy_int_field_.
get_dummy_double_field()
const IJK_Field_double & IJK_Ghost_Fluid_Fields::get_dummy_double_field () const inline
References dummy_double_field_.
Member Data Documentation
info_obj
const Type_info IJK_Ghost_Fluid_Fields::info_obj static
eulerian_distance_ft_
IJK_Field_double IJK_Ghost_Fluid_Fields::eulerian_distance_ft_ protected
Referenced by compute_eulerian_curvature(), compute_eulerian_distance(), enforce_zero_value_eulerian_distance(), get_eulerian_distance_ft(), and initialize().
eulerian_distance_ns_
IJK_Field_double IJK_Ghost_Fluid_Fields::eulerian_distance_ns_ protected
Referenced by compute_eulerian_distance(), enforce_zero_value_eulerian_distance(), get_eulerian_distance_ns(), and initialize().
eulerian_normal_vectors_ft_
IJK_Field_vector3_double IJK_Ghost_Fluid_Fields::eulerian_normal_vectors_ft_ protected
Referenced by compute_eulerian_curvature_from_interface(), compute_eulerian_distance(), get_eulerian_normal_vectors_ft(), and initialize().
eulerian_facets_barycentre_ft_
IJK_Field_vector3_double IJK_Ghost_Fluid_Fields::eulerian_facets_barycentre_ft_ protected
Referenced by compute_eulerian_distance(), get_eulerian_facets_barycentre_ft(), and initialize().
eulerian_normal_vectors_ns_
IJK_Field_vector3_double IJK_Ghost_Fluid_Fields::eulerian_normal_vectors_ns_ protected
Referenced by compute_eulerian_distance(), get_eulerian_normal_vectors_ns(), and initialize().
eulerian_normal_vectors_ns_normed_
IJK_Field_vector3_double IJK_Ghost_Fluid_Fields::eulerian_normal_vectors_ns_normed_ protected
Referenced by compute_eulerian_distance(), get_eulerian_normal_vectors_ns_normed(), and initialize().
eulerian_facets_barycentre_ns_
IJK_Field_vector3_double IJK_Ghost_Fluid_Fields::eulerian_facets_barycentre_ns_ protected
Referenced by compute_eulerian_distance(), get_eulerian_facets_barycentre_ns(), and initialize().
tmp_old_vector_val_
IJK_Field_vector3_double IJK_Ghost_Fluid_Fields::tmp_old_vector_val_ protected
Referenced by compute_eulerian_distance(), and initialize().
tmp_new_vector_val_
IJK_Field_vector3_double IJK_Ghost_Fluid_Fields::tmp_new_vector_val_ protected
Referenced by compute_eulerian_distance(), and initialize().
tmp_interf_cells_
IJK_Field_int IJK_Ghost_Fluid_Fields::tmp_interf_cells_ protected
Referenced by compute_eulerian_distance(), and initialize().
tmp_propagated_cells_
IJK_Field_int IJK_Ghost_Fluid_Fields::tmp_propagated_cells_ protected
Referenced by compute_eulerian_distance(), and initialize().
interf_cells_indices_
FixedVector<ArrOfInt,3> IJK_Ghost_Fluid_Fields::interf_cells_indices_ protected
Referenced by compute_eulerian_distance().
gfm_first_cells_indices_
FixedVector<ArrOfInt,3> IJK_Ghost_Fluid_Fields::gfm_first_cells_indices_ protected
Referenced by compute_eulerian_distance().
propagated_cells_indices_
FixedVector<ArrOfInt,3> IJK_Ghost_Fluid_Fields::propagated_cells_indices_ protected
Referenced by compute_eulerian_distance().
tmp_old_dist_val_
IJK_Field_double IJK_Ghost_Fluid_Fields::tmp_old_dist_val_ protected
Referenced by compute_eulerian_distance(), and initialize().
tmp_new_dist_val_
IJK_Field_double IJK_Ghost_Fluid_Fields::tmp_new_dist_val_ protected
Referenced by compute_eulerian_distance(), and initialize().
tmp_old_curv_val_
IJK_Field_double IJK_Ghost_Fluid_Fields::tmp_old_curv_val_ protected
Referenced by compute_eulerian_curvature_from_interface(), and initialize().
tmp_new_curv_val_
IJK_Field_double IJK_Ghost_Fluid_Fields::tmp_new_curv_val_ protected
Referenced by compute_eulerian_curvature_from_interface(), and initialize().
eulerian_curvature_ft_
IJK_Field_double IJK_Ghost_Fluid_Fields::eulerian_curvature_ft_ protected
Referenced by compute_eulerian_curvature(), compute_eulerian_curvature_from_interface(), enforce_max_value_eulerian_curvature(), enforce_zero_value_eulerian_curvature(), get_eulerian_curvature_ft(), and initialize().
eulerian_curvature_ns_
IJK_Field_double IJK_Ghost_Fluid_Fields::eulerian_curvature_ns_ protected
Referenced by compute_eulerian_curvature(), compute_eulerian_curvature_from_interface(), enforce_max_value_eulerian_curvature(), get_eulerian_curvature_ns(), and initialize().
eulerian_interfacial_area_ft_
IJK_Field_double IJK_Ghost_Fluid_Fields::eulerian_interfacial_area_ft_ protected
Referenced by compute_eulerian_curvature_from_interface(), enforce_distance_curvature_values_for_post_processings(), get_eulerian_interfacial_area_ft(), and initialize().
eulerian_interfacial_area_ns_
IJK_Field_double IJK_Ghost_Fluid_Fields::eulerian_interfacial_area_ns_ protected
Referenced by compute_eulerian_curvature_from_interface(), get_eulerian_interfacial_area_ns(), and initialize().
eulerian_rising_velocities_
IJK_Field_double IJK_Ghost_Fluid_Fields::eulerian_rising_velocities_ protected
Referenced by get_eulerian_rising_velocities().
dummy_int_vect_
IJK_Field_vector3_int IJK_Ghost_Fluid_Fields::dummy_int_vect_ protected
Referenced by get_dummy_int_vect().
dummy_double_vect_
IJK_Field_vector3_double IJK_Ghost_Fluid_Fields::dummy_double_vect_ protected
Referenced by get_dummy_double_vect().
dummy_int_field_
IJK_Field_int IJK_Ghost_Fluid_Fields::dummy_int_field_ protected
Referenced by get_dummy_int_field().
dummy_double_field_
IJK_Field_double IJK_Ghost_Fluid_Fields::dummy_double_field_ protected
Referenced by get_dummy_double_field().
ref_ijk_ft_
TRUST_Ref< Probleme_FTD_IJK_base *> IJK_Ghost_Fluid_Fields::ref_ijk_ft_ protected
Referenced by associer(), compute_eulerian_curvature(), compute_eulerian_curvature_from_interface(), compute_eulerian_distance(), and initialize().
compute_distance_
int IJK_Ghost_Fluid_Fields::compute_distance_ = 1 protected
Referenced by compute_eulerian_distance(), enforce_zero_value_eulerian_distance(), initialize(), and retrieve_ghost_fluid_params().
compute_curvature_
int IJK_Ghost_Fluid_Fields::compute_curvature_ = 1 protected
Referenced by compute_eulerian_curvature(), compute_eulerian_curvature_from_interface(), enforce_max_value_eulerian_curvature(), enforce_zero_value_eulerian_curvature(), initialize(), and retrieve_ghost_fluid_params().
n_iter_distance_
int IJK_Ghost_Fluid_Fields::n_iter_distance_ = 8 protected
Referenced by compute_eulerian_curvature_from_interface(), compute_eulerian_distance(), initialize(), and retrieve_ghost_fluid_params().
avoid_gfm_parallel_calls_
int IJK_Ghost_Fluid_Fields::avoid_gfm_parallel_calls_ = 0 protected
Referenced by compute_eulerian_distance(), initialize(), and retrieve_ghost_fluid_params().
use_n_iter_distance_
int IJK_Ghost_Fluid_Fields::use_n_iter_distance_ = 0 protected
Referenced by initialize(), and retrieve_ghost_fluid_params().
nb_cells_gfm_parallel_calls_
int IJK_Ghost_Fluid_Fields::nb_cells_gfm_parallel_calls_ = 2 protected
Referenced by initialize(), and retrieve_ghost_fluid_params().
boundary_flux_kmin_
IJK_Field_local_double IJK_Ghost_Fluid_Fields::boundary_flux_kmin_ protected
Referenced by compute_eulerian_curvature(), and retrieve_ghost_fluid_params().
boundary_flux_kmax_
IJK_Field_local_double IJK_Ghost_Fluid_Fields::boundary_flux_kmax_ protected
Referenced by compute_eulerian_curvature(), and retrieve_ghost_fluid_params().
has_computed_distance_
bool IJK_Ghost_Fluid_Fields::has_computed_distance_ = false protected
Referenced by compute_eulerian_distance(), and reset_field_computations().
has_computed_curvature_
bool IJK_Ghost_Fluid_Fields::has_computed_curvature_ = false protected
Referenced by compute_eulerian_curvature_from_interface(), and reset_field_computations().
champs_compris_
Champs_compris_IJK IJK_Ghost_Fluid_Fields::champs_compris_ protected
Referenced by get_IJK_field(), get_IJK_field_vector(), get_noms_champs_postraitables(), and has_champ().