TrioCFD: Raffiner_isotrope_parallele Class Reference
Raffiner_isotrope_parallele Class Reference
#include <Raffiner_isotrope_parallele.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Raffiner_Simplexes_32_64< _SIZE_ >
const Type_info * get_info () const override
Public Member Functions inherited from Interprete_geometrique_base_32_64< _SIZE_ >
const Type_info * get_info () const override
void mettre_a_jour_sous_domaine (Domaine_t &domaine, int_t &elem, int_t num_premier_elem, int_t nb_elem) const
Public Member Functions inherited from Interprete
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Raffiner_Simplexes_32_64< _SIZE_ >
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Interprete
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Interprete
static Objet_U & objet (const Nom &)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
Constructor & Destructor Documentation
Raffiner_isotrope_parallele()
Raffiner_isotrope_parallele::Raffiner_isotrope_parallele ()
~Raffiner_isotrope_parallele()
Raffiner_isotrope_parallele::~Raffiner_isotrope_parallele ()
Member Function Documentation
cree_instance()
Objet_U * Raffiner_isotrope_parallele::cree_instance () static
taille_memoire()
unsigned Raffiner_isotrope_parallele::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Raffiner_isotrope_parallele::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Raffiner_isotrope_parallele::info () static
get_info()
const Type_info * Raffiner_isotrope_parallele::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Interprete_geometrique_base_32_64< _SIZE_ >.
self_cast() [1/2]
Raffiner_isotrope_parallele & Raffiner_isotrope_parallele::self_cast (Objet_U & r) static
self_cast() [2/2]
const Raffiner_isotrope_parallele & Raffiner_isotrope_parallele::self_cast (const Objet_U & r) static
printOn()
Sortie & Raffiner_isotrope_parallele::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Interprete_geometrique_base_32_64< _SIZE_ >.
References Raffiner_Simplexes_32_64< _SIZE_ >::printOn().
readOn()
Entree & Raffiner_isotrope_parallele::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Interprete_geometrique_base_32_64< _SIZE_ >.
References Raffiner_Simplexes_32_64< _SIZE_ >::readOn().
interpreter()
Entree & Raffiner_isotrope_parallele::interpreter (Entree & is) override protected virtual
Reimplemented from Interprete_geometrique_base_32_64< _SIZE_ >.
References Param::ajouter(), Param::ajouter_flag(), Statistiques::begin_count(), Scatter::calculer_renum_items_communs(), FichierHDF::close(), Scatter::construire_correspondance_sommets_par_coordonnees(), Process::exit(), Domaine_32_64< _SIZE_ >::faces_joint(), Process::force_single_file(), Objet_U::format_precision_geom, FichierHDF::is_hdf5(), Param::lire_avec_accolades(), Process::me(), Domaine_32_64< _SIZE_ >::nb_som(), Statistiques::new_counter(), Nom::nom_me(), Process::nproc(), FichierHDF::open(), LecFicDistribue::ouvrir(), EcrFicCollecte::ouvrir(), Sortie_Fichier_base::precision(), Objet_U::que_suis_je(), FichierHDF::read_dataset(), Raffiner_Simplexes_32_64< _SIZE_ >::refine_domain(), Param::REQUIRED, Entree::set_bin(), Sortie::set_bin(), Domaine_base::set_fichier_lu(), Sortie_Fichier_base::setf(), Scatter::trier_les_joints(), and Scatter::uninit_sequential_domain().
Member Data Documentation
info_obj
const Type_info Raffiner_isotrope_parallele::info_obj static