TrioCFD: Convection_Diffusion_Temperature_FT_Disc Class Reference
Convection_Diffusion_Temperature_FT_Disc Class Reference
#include <Convection_Diffusion_Temperature_FT_Disc.h>
Public Member Functions
void associer_milieu_base (const Milieu_base &milieu) override
void calculer_grad_t ()
void completer () override
DoubleTab & derivee_en_temps_inco (DoubleTab &) override
void discretiser () override
const Type_info * get_info () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
void mettre_a_jour (double temps) override
int preparer_calcul () override
virtual void suppression_interfaces (const IntVect &num_compo, const ArrOfInt &flags_compo_a_supprimer, int nouvelle_phase)
Public Member Functions inherited from Convection_Diffusion_Temperature
void associer_milieu_base (const Milieu_base &) override
DoubleTab & derivee_en_temps_inco (DoubleTab &) override
void discretiser () override
const Motcle & domaine_application () const override
const Type_info * get_info () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
int preparer_calcul () override
Public Member Functions inherited from Convection_Diffusion_Temperature_base
void associer_milieu_base (const Milieu_base &) override
Fluide_base & fluide ()
const Type_info * get_info () const override
Public Member Functions inherited from Convection_Diffusion_std
void associer_vitesse (const Champ_base &)
const Type_info * get_info () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
int nombre_d_operateurs () const override
const Operateur & operateur (int) const override
Operateur & operateur (int) override
const Champ_Inc_base & vitesse_transportante () const
Public Member Functions inherited from Equation_base
virtual void abortTimeStep ()
virtual void associer_domaine_dis (const Domaine_dis_base &)
virtual void associer_pb_base (const Probleme_base &)
virtual void associer_sch_tps_base (const Schema_Temps_base &)
virtual double calculer_pas_de_temps () const
virtual void completer ()
virtual std::vector< YAML_data > data_a_sauvegarder () const
DoubleTab & derivee_en_temps_conv (DoubleTab &, const DoubleTab &)
virtual DoubleTab & derivee_en_temps_inco (DoubleTab &)
const Discretisation_base & discretisation () const
virtual void discretiser ()
virtual const Motcle & domaine_application () const
virtual Domaine_Cl_dis_base & domaine_Cl_dis ()
virtual const Domaine_Cl_dis_base & domaine_Cl_dis () const
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual void imprimer (Sortie &os) const
virtual bool initTimeStep (double dt)
const Nom & le_nom () const override
int limpr () const
virtual void mettre_a_jour (double temps)
virtual int preparer_calcul ()
Probleme_base & probleme ()
const Probleme_base & probleme () const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Schema_Temps_base & schema_temps ()
const Schema_Temps_base & schema_temps () const
Solveur_Masse_base & solv_masse ()
const Solveur_Masse_base & solv_masse () const
Sources & sources ()
const Sources & sources () const
virtual void valider_iteration ()
virtual void verifie_ch_init_nb_comp (const Champ_Inc_base &ch_ref, const int nb_comp) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Equation_base
virtual Entree & lire_cl (Entree &)
virtual Entree & lire_cond_init (Entree &)
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual Entree & lire_sources (Entree &)
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
virtual int verif_Cl () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Member Enumeration Documentation
Thermal_correction_discretization_method
enum class Convection_Diffusion_Temperature_FT_Disc::Thermal_correction_discretization_method strong
Enumerator
P1
ELEM_DIPH
P1_ALL
Constructor & Destructor Documentation
~Convection_Diffusion_Temperature_FT_Disc()
Convection_Diffusion_Temperature_FT_Disc::~Convection_Diffusion_Temperature_FT_Disc ()
Convection_Diffusion_Temperature_FT_Disc()
Convection_Diffusion_Temperature_FT_Disc::Convection_Diffusion_Temperature_FT_Disc ()
References correction_courbure_ordre_, derivee_energy_, divergence_free_velocity_extension_, is_prescribed_mpoint_, lost_fluxes_, lost_fluxes_conv_, lost_fluxes_diffu_, maintien_temperature_, mixed_elems_, mixed_elems_conv_, mixed_elems_diffu_, nom_sous_domaine_, phase_, prescribed_mpoint_, TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), stencil_width_, and temp_moy_ini_.
Member Function Documentation
cree_instance()
Objet_U * Convection_Diffusion_Temperature_FT_Disc::cree_instance () static
taille_memoire()
unsigned Convection_Diffusion_Temperature_FT_Disc::taille_memoire () const override virtual
Reimplemented from Convection_Diffusion_Temperature.
duplique()
int Convection_Diffusion_Temperature_FT_Disc::duplique () const override virtual
Reimplemented from Convection_Diffusion_Temperature.
info()
const Type_info * Convection_Diffusion_Temperature_FT_Disc::info () static
get_info()
const Type_info * Convection_Diffusion_Temperature_FT_Disc::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Convection_Diffusion_Temperature.
self_cast() [1/2]
Convection_Diffusion_Temperature_FT_Disc & Convection_Diffusion_Temperature_FT_Disc::self_cast (Objet_U & r) static
self_cast() [2/2]
const Convection_Diffusion_Temperature_FT_Disc & Convection_Diffusion_Temperature_FT_Disc::self_cast (const Objet_U & r) static
printOn()
Sortie & Convection_Diffusion_Temperature_FT_Disc::printOn (Sortie & is) const override protected virtual
Simple appel a Equation_base::printOn(Sortie&)
Parameters
(Sortie& is) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Convection_Diffusion_Temperature.
References Convection_Diffusion_Temperature::printOn().
readOn()
Entree & Convection_Diffusion_Temperature_FT_Disc::readOn (Entree & is) override protected virtual
cf Convection_Diffusion_std::readOn(Entree&).
Reimplemented from Convection_Diffusion_Temperature.
References correction_mpoint_diff_conv_energy_, Convection_Diffusion_Temperature::inconnue(), Field_base::le_nom(), Convection_Diffusion_std::readOn(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), Operateur::set_description(), Operateur::set_fichier(), Solveur_Masse_base::set_name_of_coefficient_temporel(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), Equation_base::solveur_masse, Nom::suffix(), Convection_Diffusion_std::terme_convectif, and Convection_Diffusion_std::terme_diffusif.
set_param()
void Convection_Diffusion_Temperature_FT_Disc::set_param (Param & titi) override virtual
Reimplemented from Convection_Diffusion_Temperature.
References Param::ajouter(), Param::ajouter_condition(), Param::ajouter_flag(), Param::ajouter_non_std(), correction_courbure_ordre_, correction_mpoint_diff_conv_energy_, divergence_free_velocity_extension_, name_bc_opening_pressure_, Param::OPTIONAL, phase_, Param::REQUIRED, Convection_Diffusion_Temperature::set_param(), and stencil_width_.
lire_motcle_non_standard()
int Convection_Diffusion_Temperature_FT_Disc::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Convection_Diffusion_Temperature.
References Process::barrier(), divergence_free_velocity_extension_, Probleme_FT_Disc_gen::equation_hydraulique(), Probleme_FT_Disc_gen::equation_interfaces(), Process::exit(), is_prescribed_mpoint_, Process::je_suis_maitre(), Convection_Diffusion_std::lire_motcle_non_standard(), Convection_Diffusion_Temperature::lire_motcle_non_standard(), maintien_temperature_, nom_sous_domaine_, SolveurSys::nommer(), TRUST_Ref< _CLASSE_ >::non_nul(), phase_, prescribed_mpoint_, Equation_base::probleme(), Objet_U::que_suis_je(), ref_eq_interface_, ref_eq_ns_, solveur_pression_, and temp_moy_ini_.
preparer_pas_de_temps()
void Convection_Diffusion_Temperature_FT_Disc::preparer_pas_de_temps () virtual
corriger_pas_de_temps()
void Convection_Diffusion_Temperature_FT_Disc::corriger_pas_de_temps (double dt) virtual
compute_divergence_free_velocity_extension()
void Convection_Diffusion_Temperature_FT_Disc::compute_divergence_free_velocity_extension ()
References assembleur_pression_, Operateur_base::associer(), MorEqn::associer_eqn(), Operateur_base::associer_eqn(), Operateur_Div::calculer(), Operateur_Grad::calculer(), Champ_Inc_base::changer_temps(), Operateur::completer(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Equation_base::discretisation(), divergence_delta_U, Equation_base::domaine_dis(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_VF::elem_faces(), Domaine_VF::face_voisins(), Discretisation_base::get_name_of_type_for(), Transport_Interfaces_FT_Disc::get_update_distance_interface(), gradient_pression_, Navier_Stokes_std::inconnue(), Operateur_Div::l_op_base(), Operateur_Grad::l_op_base(), la_pression, matrice_pression_, Assembleur_base::modifier_secmem(), Assembleur_base::modifier_solution(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Objet_U::que_suis_je(), ref_eq_interface_, ref_eq_ns_, SolveurSys::resoudre_systeme(), Equation_base::schema_temps(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), Equation_base::solv_masse(), solveur_pression_, Operateur::type(), Operateur_Div::typer(), Operateur_Grad::typer(), TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_Inc_base::valeurs(), Champ_Proto::valeurs(), vitesse_convection_, and zcl_fictitious_.
Referenced by derivee_en_temps_inco().
derivee_en_temps_inco()
DoubleTab & Convection_Diffusion_Temperature_FT_Disc::derivee_en_temps_inco (DoubleTab & derivee) override virtual
Returns the time derivative of the unknown I of the equation: dI/dt = M-1*(sum(operators(I) + sources))
In : derivee contains I (but immediatly set to 0) Out: derivee contains dI/dt
Reimplemented from Convection_Diffusion_Temperature.
References Operateur_Conv::ajouter(), Operateur_Diff::ajouter(), Solveur_Masse_base::appliquer(), Statistiques::begin_count(), Parametre_implicite::calcul_explicite(), Navier_Stokes_FT_Disc::calculer_delta_u_interface(), calculer_mpoint(), compute_divergence_free_velocity_extension(), correct_mpoint(), correction_courbure_ordre_, correction_mpoint_diff_conv_energy_, Triple_Line_Model_FT_Disc::corriger_mpoint(), Convection_Diffusion_Temperature::derivee_en_temps_inco(), divergence_free_velocity_extension_, TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Statistiques::end_count(), Champ_Inc_base::futur(), Convection_Diffusion_Temperature::get_champ(), Navier_Stokes_FT_Disc::get_interfacial_area(), Maillage_FT_Disc::get_mesh_tag(), Convection_Diffusion_Temperature::inconnue(), Navier_Stokes_std::inconnue(), Triple_Line_Model_FT_Disc::is_activated(), is_prescribed_mpoint_, lost_fluxes_, lost_fluxes_conv_, lost_fluxes_diffu_, Transport_Interfaces_FT_Disc::maillage_interface(), mixed_elems_, mixed_elems_conv_, mixed_elems_diffu_, Process::mp_sum(), mpoint_, mpoint_uncorrected_, Statistiques::new_counter(), Objet_U_ptr::non_nul(), Equation_base::parametre_equation_, phase_, Equation_base::probleme(), ref_eq_interface_, ref_eq_ns_, TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), Equation_base::schema_temps(), Triple_Line_Model_FT_Disc::set_wall_adjacent_temperature_according_to_TCL_model(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), Equation_base::solveur_masse, Triple_Line_Model_FT_Disc::tag_tcl(), Probleme_FT_Disc_gen::tcl(), Schema_Temps_base::temps_courant(), Convection_Diffusion_std::terme_convectif, Convection_Diffusion_std::terme_diffusif, TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), Champ_Inc_base::valeurs(), Champ_Proto::valeurs(), and vitesse_convection_.
mettre_a_jour()
void Convection_Diffusion_Temperature_FT_Disc::mettre_a_jour (double temps) override virtual
La valeur de l'inconnue sur le pas de temps a ete calculee.
Cette methode avance le present jusqu'au temps passe en parametre. Elle met aussi a jour les proprietes du milieu.
Parameters
(double temps) le pas de temps de mise a jour
Reimplemented from Equation_base.
References Domaine_dis_base::domaine(), Equation_base::domaine_dis(), Transport_Interfaces_FT_Disc::get_update_indicatrice(), Convection_Diffusion_Temperature::inconnue(), maintien_temperature_, Equation_base::mettre_a_jour(), Champ_Inc_base::mettre_a_jour(), Process::mp_sum(), Domaine_32_64< _SIZE_ >::nb_elem(), Sous_Domaine_32_64< _SIZE_ >::nb_elem_tot(), nom_sous_domaine_, ref_eq_interface_, Domaine_32_64< _SIZE_ >::ss_domaine(), temp_moy_ini_, TRUST_Ref< _CLASSE_ >::valeur(), Champ_Inc_base::valeurs(), Champ_Proto::valeurs(), and vitesse_convection_.
preparer_calcul()
int Convection_Diffusion_Temperature_FT_Disc::preparer_calcul () override virtual
Tout ce qui ne depend pas des autres problemes eventuels.
Returns
(int) renvoie toujours 1
Reimplemented from Convection_Diffusion_Temperature.
References is_solid_particle_, Equation_base::preparer_calcul(), ref_eq_interface_, set_is_solid_particle(), and TRUST_Ref< _CLASSE_ >::valeur().
get_flux_to_face()
double Convection_Diffusion_Temperature_FT_Disc::get_flux_to_face (const int num_face) const
References Cond_lim_base::champ_front(), Equation_base::domaine_Cl_dis(), Process::exit(), Echange_impose_base::h_imp(), Domaine_Cl_VDF::la_cl_de_la_face(), Objet_U_ptr::le_nom(), Front_VF::num_premiere_face(), Objet_U::que_suis_je(), Echange_impose_base::T_ext(), TRUST_Deriv< _CLASSE_ >::valeur(), and Champ_front_base::valeurs().
Referenced by get_Twall().
get_Twall_at_face()
double Convection_Diffusion_Temperature_FT_Disc::get_Twall_at_face (const int num_face) const
References get_flux_and_Twall().
get_Twall_at_elem()
double Convection_Diffusion_Temperature_FT_Disc::get_Twall_at_elem (const int elem) const
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Equation_base::domaine_dis(), Domaine_VF::elem_faces(), Process::exit(), Domaine_VF::face_voisins(), and get_flux_and_Twall().
get_tsat_constant()
const double & Convection_Diffusion_Temperature_FT_Disc::get_tsat_constant () const
Referenced by Post_Processing_Hydrodynamic_Forces::compute_heat_transfer().
get_flux_and_Twall()
void Convection_Diffusion_Temperature_FT_Disc::get_flux_and_Twall (const int num_face, double & flux, double & Twall) const
References Cond_lim_base::champ_front(), Equation_base::domaine_Cl_dis(), Process::exit(), Echange_global_impose::flux_exterieur_impose(), Echange_impose_base::h_imp(), Domaine_Cl_VDF::la_cl_de_la_face(), Objet_U_ptr::le_nom(), Front_VF::num_premiere_face(), Objet_U::que_suis_je(), Echange_impose_base::T_ext(), Echange_contact_VDF_FT_Disc::Ti_wall(), TRUST_Deriv< _CLASSE_ >::valeur(), and Champ_front_base::valeurs().
Referenced by get_Twall_at_elem(), and get_Twall_at_face().
get_Twall()
double Convection_Diffusion_Temperature_FT_Disc::get_Twall (const int num_face) const
References Objet_U::dimension, Equation_base::domaine_dis(), Domaine_VF::face_voisins(), fluide_dipha_, get_flux_to_face(), Convection_Diffusion_Temperature::inconnue(), phase_, Champ_Inc_base::valeurs(), Domaine_VF::xp(), and Domaine_VF::xv().
suppression_interfaces()
void Convection_Diffusion_Temperature_FT_Disc::suppression_interfaces (const IntVect & num_compo, const ArrOfInt & flags_compo_a_supprimer, int nouvelle_phase) virtual
Methode appelee par Transport_Interfaces_xxx::test_suppression_interfaces_sous_domaine() lorqu'une interfaces disparait.
Il faut remettre la temperature de saturation dans l'inclusion supprimee.
References Domaine_dis_base::domaine(), Equation_base::domaine_dis(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Champ_Inc_base::futur(), Convection_Diffusion_Temperature::inconnue(), Domaine_32_64< _SIZE_ >::nb_elem(), Champ_Inc_base::nb_valeurs_temporelles(), phase_, and TRUSTVect< _TYPE_, _SIZE_ >::size().
Referenced by Transport_Interfaces_FT_Disc::test_suppression_interfaces_sous_domaine().
associer_milieu_base()
void Convection_Diffusion_Temperature_FT_Disc::associer_milieu_base (const Milieu_base & un_milieu) override virtual
Associe un milieu physique a l'equation, le milieu est en fait caste en Fluide_base.
Parameters
(Milieu_base& un_milieu)
Exceptions
le milieu n'est pas un Fluide_base
Reimplemented from Convection_Diffusion_Temperature.
References Process::exit(), and fluide_dipha_.
milieu() [1/2]
Milieu_base & Convection_Diffusion_Temperature_FT_Disc::milieu () override virtual
Reimplemented from Convection_Diffusion_Temperature_base.
References Process::exit(), fluide_dipha_, Probleme_U::le_nom(), TRUST_Ref< _CLASSE_ >::non_nul(), phase_, and Equation_base::probleme().
milieu() [2/2]
const Milieu_base & Convection_Diffusion_Temperature_FT_Disc::milieu () const override virtual
Reimplemented from Convection_Diffusion_Temperature_base.
References Process::exit(), fluide_dipha_, Probleme_U::le_nom(), TRUST_Ref< _CLASSE_ >::non_nul(), phase_, and Equation_base::probleme().
vitesse_pour_transport()
const Champ_base & Convection_Diffusion_Temperature_FT_Disc::vitesse_pour_transport () const override virtual
Reimplemented from Convection_Diffusion_std.
References vitesse_convection_.
discretiser()
void Convection_Diffusion_Temperature_FT_Disc::discretiser () override virtual
Discretise l'equation.
Type le domaine_Cl_dis, la formatte, l'associe a l'equation. Type le solveur masse, lui associe le domaine discretisee et le domaine des conditions aux limites discretisees.
Reimplemented from Convection_Diffusion_Temperature.
References Champs_compris_T< FIELD_TYPE >::ajoute_champ(), Equation_base::champs_compris_, Equation_base::discretisation(), Equation_base::discretiser(), discretiser_assembleur_pression(), Discretisation_base::discretiser_champ(), divergence_delta_U, divergence_free_velocity_extension_, Equation_base::domaine_dis(), grad_t_, gradient_pression_, la_pression, Convection_Diffusion_Temperature::la_temperature, Equation_base::le_nom(), liste_champs_compris_, mpoint_, mpoint_uncorrected_, Schema_Temps_base::nb_valeurs_temporelles(), phase_, Equation_base::schema_temps(), Schema_Temps_base::temps_courant(), TRUST_Deriv< _CLASSE_ >::valeur(), and vitesse_convection_.
get_phase()
int Convection_Diffusion_Temperature_FT_Disc::get_phase () const
References phase_.
Referenced by Navier_Stokes_FT_Disc::compute_boussinesq_additional_gravity().
discretiser_assembleur_pression()
void Convection_Diffusion_Temperature_FT_Disc::discretiser_assembleur_pression ()
References assembleur_pression_, Assembleur_base::associer_domaine_dis_base(), Equation_base::discretisation(), Equation_base::domaine_dis(), Objet_U::que_suis_je(), and Objet_U_ptr::typer().
Referenced by discretiser().
completer()
void Convection_Diffusion_Temperature_FT_Disc::completer () override virtual
Complete la construction (initialisation) des objets associes a l'equation.
Complete les sources, associe l'equation a l'inconnue complete les operateurs, complete les conditions aux limites discretisees. Voir les methodes Source_base::completer(), Operateur_base::completer() Domaine_Cl_dis_base::completer() Domaine_Cl_dis_base::completer(const Domaine_dis_base&)
Reimplemented from Equation_base.
References Assembleur_base::assembler(), assembleur_pression_, Domaine_Cl_VDF::associer(), Assembleur_base::associer_domaine_cl_dis_base(), MorEqn::associer_eqn(), Domaine_Cl_dis_base::completer(), Equation_base::completer(), Assembleur_base::completer(), Noms::contient_(), divergence_free_velocity_extension_, Domaine_dis_base::domaine(), Equation_base::domaine_dis(), Process::exit(), Domaine_32_64< _SIZE_ >::frontiere(), Transport_Interfaces_FT_Disc::get_n_iterations_distance(), SChaine::get_str(), Frontiere_32_64< _SIZE_ >::le_nom(), matrice_pression_, name_bc_opening_pressure_, Domaine_32_64< _SIZE_ >::nb_front_Cl(), Objet_U_ptr::non_nul(), Objet_U::que_suis_je(), ref_eq_interface_, ref_eq_ns_, solveur_pression_, stencil_width_, Objet_U_ptr::typer(), TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), and zcl_fictitious_.
get_mpoint()
const DoubleTab & Convection_Diffusion_Temperature_FT_Disc::get_mpoint () const inline
References mpoint_, and Champ_Don_base::valeurs().
get_eq_interface()
const Transport_Interfaces_FT_Disc & Convection_Diffusion_Temperature_FT_Disc::get_eq_interface () const inline
References ref_eq_interface_, and TRUST_Ref< _CLASSE_ >::valeur().
eq_interface()
Transport_Interfaces_FT_Disc & Convection_Diffusion_Temperature_FT_Disc::eq_interface () inline
References ref_eq_interface_, and TRUST_Ref< _CLASSE_ >::valeur().
mixed_elems()
ArrOfInt & Convection_Diffusion_Temperature_FT_Disc::mixed_elems () inline
References mixed_elems_.
lost_fluxes()
ArrOfDouble & Convection_Diffusion_Temperature_FT_Disc::lost_fluxes () inline
References lost_fluxes_.
calculer_grad_t()
void Convection_Diffusion_Temperature_FT_Disc::calculer_grad_t ()
met a jour le champ grad_t en fonction du champ inconnue.
Attention, l'inconnue est modifiee (on etend le champ de temperature dans la phase opposee.
References Navier_Stokes_FT_Disc::calculer_div_normale_interface(), Equation_base::domaine_dis(), Transport_Interfaces_FT_Disc::get_update_distance_interface(), Transport_Interfaces_FT_Disc::get_update_indicatrice(), Transport_Interfaces_FT_Disc::get_update_normale_interface(), grad_t_, Convection_Diffusion_Temperature::inconnue(), phase_, ref_eq_interface_, ref_eq_ns_, Equation_base::schema_temps(), stencil_width_, Schema_Temps_base::temps_courant(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), Champ_Inc_base::valeurs(), and Champ_Proto::valeurs().
Referenced by calculer_mpoint().
calculer_mpoint() [1/2]
void Convection_Diffusion_Temperature_FT_Disc::calculer_mpoint (Champ_base & mpoint)
References calculer_grad_t(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), fluide_dipha_, grad_t_, is_prescribed_mpoint_, phase_, prescribed_mpoint_, TRUSTVect< _TYPE_, _SIZE_ >::size(), Champ_Don_base::valeurs(), and Champ_Proto::valeurs().
calculer_mpoint() [2/2]
void Convection_Diffusion_Temperature_FT_Disc::calculer_mpoint ()
References calculer_mpoint(), and mpoint_.
Referenced by calculer_mpoint(), and derivee_en_temps_inco().
get_thermal_correction_discretization_method()
const Thermal_correction_discretization_method & Convection_Diffusion_Temperature_FT_Disc::get_thermal_correction_discretization_method () const inline
References thermal_correction_discretization_method_.
correct_mpoint()
void Convection_Diffusion_Temperature_FT_Disc::correct_mpoint () protected
References correction_mpoint_diff_conv_energy_, derivee_energy_, Equation_base::domaine_dis(), Process::exit(), fluide_dipha_, Navier_Stokes_FT_Disc::get_interfacial_area(), Transport_Interfaces_FT_Disc::get_update_distance_interface(), Transport_Interfaces_FT_Disc::inconnue(), Convection_Diffusion_Temperature::inconnue(), lost_fluxes_, lost_fluxes_conv_, lost_fluxes_diffu_, mixed_elems_, mixed_elems_conv_, mixed_elems_diffu_, Process::mp_max(), Process::mp_sum(), mpoint_, Schema_Temps_base::pas_de_temps(), Champ_Inc_base::passe(), phase_, ref_eq_interface_, ref_eq_ns_, TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), Equation_base::schema_temps(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), stencil_width_, Schema_Temps_base::temps_courant(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), Champ_Inc_base::valeurs(), and Champ_Proto::valeurs().
Referenced by derivee_en_temps_inco().
set_is_solid_particle()
void Convection_Diffusion_Temperature_FT_Disc::set_is_solid_particle (const bool is_solid_particle) inline protected
References is_solid_particle_.
Referenced by preparer_calcul().
Friends And Related Function Documentation
Post_Processing_Hydrodynamic_Forces
friend class Post_Processing_Hydrodynamic_Forces friend
Member Data Documentation
info_obj
const Type_info Convection_Diffusion_Temperature_FT_Disc::info_obj static
phase_
int Convection_Diffusion_Temperature_FT_Disc::phase_ protected
Referenced by calculer_grad_t(), calculer_mpoint(), Convection_Diffusion_Temperature_FT_Disc(), correct_mpoint(), derivee_en_temps_inco(), discretiser(), get_phase(), get_Twall(), lire_motcle_non_standard(), milieu(), set_param(), and suppression_interfaces().
stencil_width_
int Convection_Diffusion_Temperature_FT_Disc::stencil_width_ protected
Referenced by calculer_grad_t(), completer(), Convection_Diffusion_Temperature_FT_Disc(), correct_mpoint(), and set_param().
correction_courbure_ordre_
int Convection_Diffusion_Temperature_FT_Disc::correction_courbure_ordre_ protected
Referenced by Convection_Diffusion_Temperature_FT_Disc(), derivee_en_temps_inco(), and set_param().
is_solid_particle_
int Convection_Diffusion_Temperature_FT_Disc::is_solid_particle_ protected
Referenced by preparer_calcul(), and set_is_solid_particle().
nom_sous_domaine_
Nom Convection_Diffusion_Temperature_FT_Disc::nom_sous_domaine_ protected
Referenced by Convection_Diffusion_Temperature_FT_Disc(), lire_motcle_non_standard(), and mettre_a_jour().
temp_moy_ini_
double Convection_Diffusion_Temperature_FT_Disc::temp_moy_ini_ protected
Referenced by Convection_Diffusion_Temperature_FT_Disc(), lire_motcle_non_standard(), and mettre_a_jour().
maintien_temperature_
bool Convection_Diffusion_Temperature_FT_Disc::maintien_temperature_ protected
Referenced by Convection_Diffusion_Temperature_FT_Disc(), lire_motcle_non_standard(), and mettre_a_jour().
is_prescribed_mpoint_
bool Convection_Diffusion_Temperature_FT_Disc::is_prescribed_mpoint_ protected
Referenced by calculer_mpoint(), Convection_Diffusion_Temperature_FT_Disc(), derivee_en_temps_inco(), and lire_motcle_non_standard().
prescribed_mpoint_
double Convection_Diffusion_Temperature_FT_Disc::prescribed_mpoint_ protected
Referenced by calculer_mpoint(), Convection_Diffusion_Temperature_FT_Disc(), and lire_motcle_non_standard().
correction_mpoint_diff_conv_energy_
ArrOfInt Convection_Diffusion_Temperature_FT_Disc::correction_mpoint_diff_conv_energy_ protected
Referenced by correct_mpoint(), derivee_en_temps_inco(), readOn(), and set_param().
fluide_dipha_
TRUST_Ref< Fluide_Diphasique *> Convection_Diffusion_Temperature_FT_Disc::fluide_dipha_ protected
Referenced by associer_milieu_base(), calculer_mpoint(), correct_mpoint(), get_Twall(), and milieu().
liste_champs_compris_
TRUST_List< TRUST_Ref< Champ_base *> > Convection_Diffusion_Temperature_FT_Disc::liste_champs_compris_ protected
Referenced by discretiser().
ref_eq_interface_
TRUST_Ref< Transport_Interfaces_FT_Disc *> Convection_Diffusion_Temperature_FT_Disc::ref_eq_interface_ protected
Referenced by calculer_grad_t(), completer(), compute_divergence_free_velocity_extension(), correct_mpoint(), derivee_en_temps_inco(), eq_interface(), get_eq_interface(), lire_motcle_non_standard(), mettre_a_jour(), and preparer_calcul().
ref_eq_ns_
TRUST_Ref< Navier_Stokes_std *> Convection_Diffusion_Temperature_FT_Disc::ref_eq_ns_ protected
Referenced by calculer_grad_t(), completer(), compute_divergence_free_velocity_extension(), correct_mpoint(), derivee_en_temps_inco(), and lire_motcle_non_standard().
grad_t_
TRUST_Deriv< Champ_Fonc_base > Convection_Diffusion_Temperature_FT_Disc::grad_t_ protected
Referenced by calculer_grad_t(), calculer_mpoint(), and discretiser().
mpoint_
TRUST_Deriv< Champ_Fonc_base > Convection_Diffusion_Temperature_FT_Disc::mpoint_ protected
Referenced by calculer_mpoint(), correct_mpoint(), derivee_en_temps_inco(), discretiser(), and get_mpoint().
mpoint_uncorrected_
TRUST_Deriv< Champ_Fonc_base > Convection_Diffusion_Temperature_FT_Disc::mpoint_uncorrected_ protected
Referenced by derivee_en_temps_inco(), and discretiser().
vitesse_convection_
TRUST_Deriv< Champ_Inc_base > Convection_Diffusion_Temperature_FT_Disc::vitesse_convection_ protected
Referenced by compute_divergence_free_velocity_extension(), derivee_en_temps_inco(), discretiser(), mettre_a_jour(), and vitesse_pour_transport().
divergence_free_velocity_extension_
int Convection_Diffusion_Temperature_FT_Disc::divergence_free_velocity_extension_ protected
Referenced by completer(), Convection_Diffusion_Temperature_FT_Disc(), derivee_en_temps_inco(), discretiser(), lire_motcle_non_standard(), and set_param().
assembleur_pression_
TRUST_Deriv< Assembleur_base > Convection_Diffusion_Temperature_FT_Disc::assembleur_pression_ protected
Referenced by completer(), compute_divergence_free_velocity_extension(), and discretiser_assembleur_pression().
la_pression
TRUST_Deriv< Champ_Inc_base > Convection_Diffusion_Temperature_FT_Disc::la_pression protected
Referenced by compute_divergence_free_velocity_extension(), and discretiser().
gradient_pression_
TRUST_Deriv< Champ_Inc_base > Convection_Diffusion_Temperature_FT_Disc::gradient_pression_ protected
Referenced by compute_divergence_free_velocity_extension(), and discretiser().
divergence_delta_U
TRUST_Deriv< Champ_Inc_base > Convection_Diffusion_Temperature_FT_Disc::divergence_delta_U protected
Referenced by compute_divergence_free_velocity_extension(), and discretiser().
solveur_pression_
SolveurSys Convection_Diffusion_Temperature_FT_Disc::solveur_pression_ protected
Referenced by completer(), compute_divergence_free_velocity_extension(), and lire_motcle_non_standard().
matrice_pression_
Matrice Convection_Diffusion_Temperature_FT_Disc::matrice_pression_ protected
Referenced by completer(), and compute_divergence_free_velocity_extension().
zcl_fictitious_
TRUST_Deriv< Domaine_Cl_dis_base > Convection_Diffusion_Temperature_FT_Disc::zcl_fictitious_ protected
Referenced by completer(), and compute_divergence_free_velocity_extension().
name_bc_opening_pressure_
Noms Convection_Diffusion_Temperature_FT_Disc::name_bc_opening_pressure_ protected
Referenced by completer(), and set_param().
mixed_elems_
ArrOfInt Convection_Diffusion_Temperature_FT_Disc::mixed_elems_ protected
Referenced by Convection_Diffusion_Temperature_FT_Disc(), correct_mpoint(), derivee_en_temps_inco(), and mixed_elems().
lost_fluxes_
ArrOfDouble Convection_Diffusion_Temperature_FT_Disc::lost_fluxes_ protected
Referenced by Convection_Diffusion_Temperature_FT_Disc(), correct_mpoint(), derivee_en_temps_inco(), and lost_fluxes().
derivee_energy_
ArrOfDouble Convection_Diffusion_Temperature_FT_Disc::derivee_energy_ protected
Referenced by Convection_Diffusion_Temperature_FT_Disc(), and correct_mpoint().
mixed_elems_diffu_
ArrOfInt Convection_Diffusion_Temperature_FT_Disc::mixed_elems_diffu_ protected
Referenced by Convection_Diffusion_Temperature_FT_Disc(), correct_mpoint(), and derivee_en_temps_inco().
lost_fluxes_diffu_
ArrOfDouble Convection_Diffusion_Temperature_FT_Disc::lost_fluxes_diffu_ protected
Referenced by Convection_Diffusion_Temperature_FT_Disc(), correct_mpoint(), and derivee_en_temps_inco().
mixed_elems_conv_
ArrOfInt Convection_Diffusion_Temperature_FT_Disc::mixed_elems_conv_ protected
Referenced by Convection_Diffusion_Temperature_FT_Disc(), correct_mpoint(), and derivee_en_temps_inco().
lost_fluxes_conv_
ArrOfDouble Convection_Diffusion_Temperature_FT_Disc::lost_fluxes_conv_ protected
Referenced by Convection_Diffusion_Temperature_FT_Disc(), correct_mpoint(), and derivee_en_temps_inco().
thermal_correction_discretization_method_
Thermal_correction_discretization_method Convection_Diffusion_Temperature_FT_Disc::thermal_correction_discretization_method_ protected
Initial value:
=
    Thermal_correction_discretization_method::P1_ALL
Referenced by get_thermal_correction_discretization_method().