TrioCFD: Eval_Dift_Multiphase_VDF Class Reference
Eval_Dift_Multiphase_VDF Class Reference
#include <Eval_Dift_Multiphase_VDF.h>
Member Function Documentation
associer_corr()
void Eval_Dift_Multiphase_VDF::associer_corr (const Correlation_base & c) inline
References corr_, and Eval_Dift_VDF::is_multi_.
mettre_a_jour()
void Eval_Dift_Multiphase_VDF::mettre_a_jour () inline override virtual
Reimplemented from Eval_Diff_VDF.
References Eval_Diff_VDF::mettre_a_jour(), and update_diffusivite_turbulente().
set_nut()
void Eval_Dift_Multiphase_VDF::set_nut (const DoubleTab & nut, const bool need_ar) inline
References need_alpha_rho_, and nu_t_.
update_diffusivite_turbulente()
virtual void Eval_Dift_Multiphase_VDF::update_diffusivite_turbulente () inline final virtual
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), need_alpha_rho_, nu_t_, Eval_Diff_VDF::ref_probleme_, Eval_Diff_VDF::tab_alpha_, tab_diff_turb_first_update_, Eval_Dift_VDF::tab_diffusivite_turbulente, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by get_diffusivite_turbulente_multiphase(), and mettre_a_jour().
get_diffusivite_turbulente_multiphase()
const DoubleTab & Eval_Dift_Multiphase_VDF::get_diffusivite_turbulente_multiphase () const inline
References tab_diff_turb_first_update_, Eval_Dift_VDF::tab_diffusivite_turbulente, and update_diffusivite_turbulente().
diffusivite_turbulente()
const Champ_Fonc_base & Eval_Dift_Multiphase_VDF::diffusivite_turbulente () const inline
tab_nu_t()
const DoubleTab & Eval_Dift_Multiphase_VDF::tab_nu_t () const inline
References nu_t_.
Referenced by Op_Dift_VDF_base::ajoute_terme_pour_axi_turb().
associer_diff_turb()
void Eval_Dift_Multiphase_VDF::associer_diff_turb (const Champ_Fonc_base & diff_turb) inline
associer_loipar()
void Eval_Dift_Multiphase_VDF::associer_loipar (const Turbulence_paroi_scal_base & loi_paroi) inline override virtual
Reimplemented from Eval_Dift_VDF.
get_corr()
const Correlation_base & Eval_Dift_Multiphase_VDF::get_corr () const inline
References corr_.
Member Data Documentation
corr_
TRUST_Ref< Correlation_base *> Eval_Dift_Multiphase_VDF::corr_ protected
Referenced by associer_corr(), and get_corr().
nu_t_
TRUST_Ref< DoubleTab *> Eval_Dift_Multiphase_VDF::nu_t_ protected
Referenced by set_nut(), tab_nu_t(), and update_diffusivite_turbulente().
need_alpha_rho_
bool Eval_Dift_Multiphase_VDF::need_alpha_rho_ = true protected
Referenced by set_nut(), and update_diffusivite_turbulente().
tab_diff_turb_first_update_
bool Eval_Dift_Multiphase_VDF::tab_diff_turb_first_update_ = true protected
Referenced by get_diffusivite_turbulente_multiphase(), and update_diffusivite_turbulente().