TrioCFD: KerasLayerDense Class Reference
KerasLayerDense Class Reference
#include <keras_model.h>
Constructor & Destructor Documentation
KerasLayerDense()
KerasLayerDense::KerasLayerDense () inline
~KerasLayerDense()
KerasLayerDense::~KerasLayerDense () inline override
Member Function Documentation
LoadLayer()
bool KerasLayerDense::LoadLayer (std::ifstream * file) override virtual
Implements KerasLayer.
References Tensor::data_, KerasLayerActivation::LoadLayer(), and Tensor::Resize().
Apply()
bool KerasLayerDense::Apply (Tensor * in, Tensor * out) override virtual
Implements KerasLayer.
References KerasLayerActivation::Apply(), and Tensor::dims_.