TrioCFD: Paroi_std_hyd_VDF Class Reference
Paroi_std_hyd_VDF Class Reference
#include <Paroi_std_hyd_VDF.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Turbulence_paroi_base
void associer_modele (const Modele_turbulence_hyd_base &)
int calculer_hyd (Champ_Fonc_base &, Champ_Fonc_base &)
int calculer_hyd (Champ_Inc_base &)
const Type_info * get_info () const override
virtual void imprimer_premiere_ligne_ustar (int, const TRUST_List< Nom > &, const Nom &) const
virtual void imprimer_ustar_mean_only (Sortie &, int, const TRUST_List< Nom > &, const Nom &) const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Turbulence_paroi_base
static void typer_lire_turbulence_paroi (TRUST_Deriv< Turbulence_paroi_base > &, const Modele_turbulence_hyd_base &, Entree &)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
.SECTION voir aussi Turbulence_paroi_base
Constructor & Destructor Documentation
Paroi_std_hyd_VDF()
Paroi_std_hyd_VDF::Paroi_std_hyd_VDF ()
~Paroi_std_hyd_VDF()
Paroi_std_hyd_VDF::~Paroi_std_hyd_VDF ()
Member Function Documentation
cree_instance()
Objet_U * Paroi_std_hyd_VDF::cree_instance () static
taille_memoire()
unsigned Paroi_std_hyd_VDF::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Loi_expert_hydr_VDF, and Paroi_TAU_NUL_VDF.
duplique()
int Paroi_std_hyd_VDF::duplique () const override virtual
Implements Objet_U.
Reimplemented in Loi_expert_hydr_VDF, and Paroi_TAU_NUL_VDF.
info()
const Type_info * Paroi_std_hyd_VDF::info () static
get_info()
const Type_info * Paroi_std_hyd_VDF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Paroi_hyd_base_VDF.
Reimplemented in Loi_expert_hydr_VDF, and Paroi_TAU_NUL_VDF.
self_cast() [1/2]
Paroi_std_hyd_VDF & Paroi_std_hyd_VDF::self_cast (Objet_U & r) static
self_cast() [2/2]
const Paroi_std_hyd_VDF & Paroi_std_hyd_VDF::self_cast (const Objet_U & r) static
printOn()
Sortie & Paroi_std_hyd_VDF::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Paroi_hyd_base_VDF.
Reimplemented in Loi_expert_hydr_VDF, and Paroi_TAU_NUL_VDF.
References Objet_U::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Paroi_std_hyd_VDF::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Paroi_hyd_base_VDF.
Reimplemented in Loi_expert_hydr_VDF, and Paroi_TAU_NUL_VDF.
References Paroi_hyd_base_VDF::readOn().
Referenced by Paroi_std_hyd_VDF_diphasique::readOn(), and Paroi_loi_Ciofalo_hyd_VDF::readOn().
set_param()
void Paroi_std_hyd_VDF::set_param (Param & param) override virtual
Reimplemented from Turbulence_paroi_base.
References Paroi_log_QDM::set_param(), and Turbulence_paroi_base::set_param().
Referenced by Loi_expert_hydr_VDF::readOn(), and Paroi_loi_WW_hyd_VDF::set_param().
init_lois_paroi()
int Paroi_std_hyd_VDF::init_lois_paroi () override virtual
Implements Turbulence_paroi_base.
References Paroi_hyd_base_VDF::init_lois_paroi_(), init_lois_paroi_hydraulique(), Turbulence_paroi_base::le_dom_dis_, TRUSTVect< _TYPE_, _SIZE_ >::resize(), and uplus_.
calculer_hyd() [1/3]
int Paroi_std_hyd_VDF::calculer_hyd (DoubleTab & tab_k_eps) override virtual
Implements Turbulence_paroi_base.
Reimplemented in Paroi_TAU_NUL_VDF.
References calculer_hyd().
Referenced by calculer_hyd().
calculer_hyd_BiK()
int Paroi_std_hyd_VDF::calculer_hyd_BiK (DoubleTab & tab_k, DoubleTab & tab_eps) override virtual
Implements Turbulence_paroi_base.
Reimplemented in Paroi_TAU_NUL_VDF.
References Objet_U::axi, Paroi_log_QDM::calcul_lm_plus(), calculer_u_star_sous_couche_log(), calculer_u_star_sous_couche_tampon(), calculer_u_star_sous_couche_visq(), calculer_uplus_dplus(), Turbulence_paroi_base::Cisaillement_paroi_, Paroi_log_QDM::Cmu_, Objet_U::dimension, Domaine_VDF::dist_norm_bord(), Domaine_VDF::dist_norm_bord_axi(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Process::exit(), Domaine_VF::face_voisins(), Equation_base::inconnue(), Paroi_log_QDM::Kappa_, Turbulence_paroi_base::le_dom_Cl_dis_, Turbulence_paroi_base::le_dom_dis_, TRUSTVect< _TYPE_, _SIZE_ >::local_min_vect(), Equation_base::milieu(), Turbulence_paroi_base::mon_modele_turb_hyd, Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), Domaine_VDF::orientation(), Turbulence_paroi_base::tab_d_plus_, Turbulence_paroi_base::tab_u_star(), Turbulence_paroi_base::tab_u_star_, Paroi_log_QDM::table_hyd, uplus_, Table::val(), Dirichlet::val_imp(), TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), Champ_Inc_base::valeurs(), and Fluide_base::viscosite_cinematique().
calculer_hyd() [2/3]
int Paroi_std_hyd_VDF::calculer_hyd (DoubleTab & tab_nu_t, DoubleTab & tab_k) override virtual
Implements Turbulence_paroi_base.
Reimplemented in Paroi_TAU_NUL_VDF.
References calculer_hyd().
calculer_hyd() [3/3]
int Paroi_std_hyd_VDF::calculer_hyd (DoubleTab & tab1, int isKeps, DoubleTab & tab2)
References Objet_U::axi, calculer_local(), calculer_uplus_dplus(), Turbulence_paroi_base::Cisaillement_paroi_, Objet_U::dimension, Domaine_VDF::dist_norm_bord(), Domaine_VDF::dist_norm_bord_axi(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Process::exit(), Domaine_VF::face_voisins(), Equation_base::inconnue(), Turbulence_paroi_base::le_dom_Cl_dis_, Turbulence_paroi_base::le_dom_dis_, TRUSTVect< _TYPE_, _SIZE_ >::local_min_vect(), Equation_base::milieu(), Turbulence_paroi_base::mon_modele_turb_hyd, Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), Domaine_VDF::orientation(), Turbulence_paroi_base::tab_d_plus_, Turbulence_paroi_base::tab_u_star(), Turbulence_paroi_base::tab_u_star_, uplus_, Dirichlet::val_imp(), TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), Champ_Inc_base::valeurs(), and Fluide_base::viscosite_cinematique().
compute_law_komega()
int Paroi_std_hyd_VDF::compute_law_komega (DoubleTab & field_komega)
References Objet_U::axi, BETA1, blended_, calculer_uplus_dplus(), Turbulence_paroi_base::Cisaillement_paroi_, Cmu025, Objet_U::dimension, Domaine_VDF::dist_norm_bord(), Domaine_VDF::dist_norm_bord_axi(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Process::exit(), Domaine_VF::face_voisins(), Equation_base::inconnue(), Paroi_log_QDM::Kappa_, Turbulence_paroi_base::le_dom_Cl_dis_, Turbulence_paroi_base::le_dom_dis_, TRUSTVect< _TYPE_, _SIZE_ >::local_min_vect(), Equation_base::milieu(), Turbulence_paroi_base::mon_modele_turb_hyd, Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), Domaine_VDF::orientation(), sCmu, Turbulence_paroi_base::tab_d_plus_, Turbulence_paroi_base::tab_u_star(), Turbulence_paroi_base::tab_u_star_, uplus_, Dirichlet::val_imp(), TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), Champ_Inc_base::valeurs(), Fluide_base::viscosite_cinematique(), and ypluslam.
tab_u_plus()
const DoubleVect & Paroi_std_hyd_VDF::tab_u_plus () const inline
References uplus_.
tau_tang()
double Paroi_std_hyd_VDF::tau_tang (int face, int k) const inline
References Turbulence_paroi_base::Cisaillement_paroi_, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Process::exit(), and Turbulence_paroi_base::le_dom_dis_.
imprimer_ustar()
void Paroi_std_hyd_VDF::imprimer_ustar (Sortie & os) const override virtual
Reimplemented from Turbulence_paroi_base.
References Turbulence_paroi_base::Cisaillement_paroi_, Objet_U::dimension, Process::je_suis_maitre(), Turbulence_paroi_base::le_dom_Cl_dis_, Turbulence_paroi_base::le_dom_dis_, Frontiere_dis_base::le_nom(), Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), Turbulence_paroi_base::ouvrir_fichier_partage(), EcrFicPartage::syncfile(), Turbulence_paroi_base::tab_d_plus(), Turbulence_paroi_base::tab_u_star(), uplus_, TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), and Domaine_VF::xv().
calculer_uplus_dplus()
void Paroi_std_hyd_VDF::calculer_uplus_dplus (DoubleVect & uplus, DoubleVect & dplus, DoubleVect & tab_ustar, int num_face, double dist, double d_visco, double norm_v)
Referenced by Paroi_std_hyd_VDF_diphasique::calculer_hyd(), calculer_hyd(), calculer_hyd_BiK(), and compute_law_komega().
init_lois_paroi_hydraulique()
int Paroi_std_hyd_VDF::init_lois_paroi_hydraulique () protected virtual
Reimplemented in Paroi_loi_Ciofalo_hyd_VDF, and Paroi_loi_WW_hyd_VDF.
References Paroi_log_QDM::Cmu_, Paroi_log_QDM::init_lois_paroi_hydraulique_(), and Turbulence_paroi_base::mon_modele_turb_hyd.
Referenced by init_lois_paroi().
preparer_calcul_hyd()
int Paroi_std_hyd_VDF::preparer_calcul_hyd (DoubleTab & tab) protected virtual
Reimplemented in Paroi_loi_Ciofalo_hyd_VDF, and Paroi_loi_WW_hyd_VDF.
References Process::exit(), Turbulence_paroi_base::le_dom_Cl_dis_, Turbulence_paroi_base::le_dom_dis_, TRUSTVect< _TYPE_, _SIZE_ >::line_size(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), and TRUST_Deriv< _CLASSE_ >::valeur().
initialize_wall_law_komega()
int Paroi_std_hyd_VDF::initialize_wall_law_komega (DoubleTab & field_komega) protected virtual
References Paroi_log_QDM::Cmu_, Paroi_hyd_base_VDF::init_lois_paroi_(), Paroi_log_QDM::init_lois_paroi_hydraulique_(), Turbulence_paroi_base::le_dom_dis_, Turbulence_paroi_base::mon_modele_turb_hyd, TRUSTVect< _TYPE_, _SIZE_ >::resize(), set_yplus_komega(), and uplus_.
compute_layer_selection()
int Paroi_std_hyd_VDF::compute_layer_selection (double u_plus_d_plus, double d_visco, DoubleTab & field_komega, double norm_vit, double dist, int elem, int num_face) protected
References calculer_u_star_sous_couche_log(), calculer_u_star_sous_couche_tampon(), calculer_u_star_sous_couche_visq(), compute_buffer_layer(), compute_log_layer(), compute_viscous_layer(), Paroi_log_QDM::table_hyd, and Table::val().
compute_viscous_layer()
int Paroi_std_hyd_VDF::compute_viscous_layer (DoubleTab & field_komega, double dist_y, double viscosity, int elem) protected
References BETA1.
Referenced by compute_layer_selection().
compute_buffer_layer()
int Paroi_std_hyd_VDF::compute_buffer_layer (DoubleTab & field_komega, double dist_y, double viscosity, int elem, int face) protected
References BETA1, Cmu025, Paroi_log_QDM::Kappa_, sCmu, and Turbulence_paroi_base::tab_u_star_.
Referenced by compute_layer_selection().
compute_log_layer()
int Paroi_std_hyd_VDF::compute_log_layer (DoubleTab & field_komega, double dist_y, int elem, int face) protected
References Cmu025, Paroi_log_QDM::Cmu_, Paroi_log_QDM::Kappa_, and Turbulence_paroi_base::tab_u_star().
Referenced by compute_layer_selection().
set_yplus_komega()
void Paroi_std_hyd_VDF::set_yplus_komega () protected
References Paroi_log_QDM::Erugu, Paroi_log_QDM::Kappa_, and ypluslam.
Referenced by initialize_wall_law_komega().
calculer_u_star_sous_couche_visq() [1/2]
int Paroi_std_hyd_VDF::calculer_u_star_sous_couche_visq (double norm_vit, double d_visco, double dist, int face) protected
References Turbulence_paroi_base::tab_u_star_.
Referenced by calculer_hyd_BiK(), calculer_local(), Paroi_loi_WW_hyd_VDF::calculer_local(), and compute_layer_selection().
calculer_u_star_sous_couche_visq() [2/2]
double Paroi_std_hyd_VDF::calculer_u_star_sous_couche_visq (double norm_vit, double d_visco, double dist) protected
calculer_sous_couche_visq() [1/2]
int Paroi_std_hyd_VDF::calculer_sous_couche_visq (DoubleTab & K_eps, double dist, int elem, double d_visco, int face) protected
References Turbulence_paroi_base::tab_u_star().
Referenced by calculer_local(), Paroi_loi_Ciofalo_hyd_VDF::calculer_local(), and Paroi_loi_WW_hyd_VDF::calculer_local().
calculer_sous_couche_visq() [2/2]
int Paroi_std_hyd_VDF::calculer_sous_couche_visq (DoubleTab & nu_t, DoubleTab & k, int elem) protected
calculer_u_star_sous_couche_tampon() [1/2]
int Paroi_std_hyd_VDF::calculer_u_star_sous_couche_tampon (double & d_plus, double u_plus_d_plus, double d_visco, double dist, int face) protected
References Turbulence_paroi_base::tab_u_star_, Paroi_log_QDM::table_hyd, and Table::val().
Referenced by calculer_hyd_BiK(), calculer_local(), and compute_layer_selection().
calculer_u_star_sous_couche_tampon() [2/2]
double Paroi_std_hyd_VDF::calculer_u_star_sous_couche_tampon (double u_plus_d_plus, double d_visco, double dist, double & d_plus) protected
References Paroi_log_QDM::table_hyd, and Table::val().
calculer_sous_couche_tampon() [1/2]
int Paroi_std_hyd_VDF::calculer_sous_couche_tampon (DoubleTab & K_eps, double d_visco, double d_plus, int elem, int face) protected
References Paroi_log_QDM::calcul_lm_plus(), Paroi_log_QDM::Cmu_, and Turbulence_paroi_base::tab_u_star().
Referenced by calculer_local().
calculer_sous_couche_tampon() [2/2]
int Paroi_std_hyd_VDF::calculer_sous_couche_tampon (DoubleTab & nu_t, DoubleTab & tab_k, double d_visco, double d_plus, int elem, int face) protected
References Paroi_log_QDM::calcul_lm_plus(), Paroi_log_QDM::Cmu_, and Turbulence_paroi_base::tab_u_star().
calculer_u_star_sous_couche_log()
int Paroi_std_hyd_VDF::calculer_u_star_sous_couche_log (double norm_vit, double d_visco, double dist, int face) protected
References Paroi_log_QDM::Erugu, Paroi_log_QDM::Kappa_, and Turbulence_paroi_base::tab_u_star_.
Referenced by calculer_hyd_BiK(), calculer_local(), and compute_layer_selection().
calculer_u_star()
double Paroi_std_hyd_VDF::calculer_u_star (double & norm_vit, double & visco, double & dist) protected virtual
References Process::exit().
Referenced by calculer_local().
calculer_sous_couche_log() [1/2]
int Paroi_std_hyd_VDF::calculer_sous_couche_log (DoubleTab & K_eps, double dist, int elem, int face) protected
References Paroi_log_QDM::Cmu_, Paroi_log_QDM::Kappa_, and Turbulence_paroi_base::tab_u_star().
Referenced by calculer_local(), and Paroi_loi_Ciofalo_hyd_VDF::calculer_local().
calculer_sous_couche_log() [2/2]
int Paroi_std_hyd_VDF::calculer_sous_couche_log (DoubleTab & nu_t, DoubleTab & tab_k, double dist, int elem, int face) protected
References Paroi_log_QDM::Cmu_, Paroi_log_QDM::Kappa_, and Turbulence_paroi_base::tab_u_star().
calculer_local() [1/3]
int Paroi_std_hyd_VDF::calculer_local (double u_plus_d_plus, double d_visco, DoubleTab & k_eps, double norm_vit, double dist, int elem, int num_face) protected
References calculer_sous_couche_log(), calculer_sous_couche_tampon(), calculer_sous_couche_visq(), calculer_u_star_sous_couche_log(), calculer_u_star_sous_couche_tampon(), calculer_u_star_sous_couche_visq(), Paroi_log_QDM::table_hyd, and Table::val().
Referenced by Paroi_std_hyd_VDF_diphasique::calculer_hyd(), and calculer_hyd().
calculer_local() [2/3]
int Paroi_std_hyd_VDF::calculer_local (double u_plus_d_plus, double d_visco, DoubleTab & tab_nu_t, DoubleTab & tab_k, double norm_vit, double dist, int elem, int num_face) protected
References calculer_sous_couche_log(), calculer_sous_couche_tampon(), calculer_sous_couche_visq(), calculer_u_star_sous_couche_log(), calculer_u_star_sous_couche_tampon(), calculer_u_star_sous_couche_visq(), Paroi_log_QDM::table_hyd, and Table::val().
calculer_local() [3/3]
double Paroi_std_hyd_VDF::calculer_local (double u_plus_d_plus, double d_visco, double norm_vit, double dist, int & type_cou, double & d_plus) protected
References calculer_u_star(), calculer_u_star_sous_couche_tampon(), calculer_u_star_sous_couche_visq(), Process::exit(), Paroi_log_QDM::table_hyd, and Table::val().
calculer_moyennes_parois()
void Paroi_std_hyd_VDF::calculer_moyennes_parois (double & U_moy_1, double & U_moy_2, double & dist_1, double & dist_2, double & visco_1, double & visco_2) protected
References Domaine_VDF::dim_elem(), Domaine_VF::elem_faces(), Process::exit(), Domaine_VF::face_voisins(), Equation_base::inconnue(), Turbulence_paroi_base::le_dom_Cl_dis_, Turbulence_paroi_base::le_dom_dis_, TRUSTVect< _TYPE_, _SIZE_ >::local_min_vect(), Equation_base::milieu(), Turbulence_paroi_base::mon_modele_turb_hyd, Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), Domaine_VDF::orientation(), Objet_U::que_suis_je(), TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), Champ_Inc_base::valeurs(), and Fluide_base::viscosite_cinematique().
modifs_valeurs_turb()
void Paroi_std_hyd_VDF::modifs_valeurs_turb (int num_elem, int type_cou, double u_star, double dist, double d_visco, double d_plus, DoubleTab & tab_nu_t, DoubleTab & tab_k) protected
References Paroi_log_QDM::calcul_lm_plus(), Paroi_log_QDM::Cmu_, Process::exit(), and Paroi_log_QDM::Kappa_.
Member Data Documentation
info_obj
const Type_info Paroi_std_hyd_VDF::info_obj static
uplus_
DoubleVect Paroi_std_hyd_VDF::uplus_ protected
Referenced by Paroi_std_hyd_VDF_diphasique::calculer_hyd(), calculer_hyd(), calculer_hyd_BiK(), compute_law_komega(), imprimer_ustar(), init_lois_paroi(), initialize_wall_law_komega(), and tab_u_plus().
BETA1
constexpr double Paroi_std_hyd_VDF::BETA1 {0.075} static constexpr protected
Referenced by compute_buffer_layer(), compute_law_komega(), and compute_viscous_layer().
Cmu025
const double Paroi_std_hyd_VDF::Cmu025 {std::pow(0.09, 0.25)} protected
Referenced by compute_buffer_layer(), compute_law_komega(), and compute_log_layer().
sCmu
const double Paroi_std_hyd_VDF::sCmu {std::sqrt(0.09)} protected
Referenced by compute_buffer_layer(), and compute_law_komega().
ypluslam
double Paroi_std_hyd_VDF::ypluslam {0} protected
Referenced by compute_law_komega(), and set_yplus_komega().
blended_
int Paroi_std_hyd_VDF::blended_ {0} protected
Referenced by compute_law_komega().