TrioCFD: EOS_Tools_base Class Reference
EOS_Tools_base Class Reference abstract
#include <EOS_Tools_base.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
EOS_Tools_base()
EOS_Tools_base::EOS_Tools_base ()
~EOS_Tools_base()
EOS_Tools_base::~EOS_Tools_base () override
Member Function Documentation
info()
const Type_info * EOS_Tools_base::info () static
get_info()
const Type_info * EOS_Tools_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
Reimplemented in EOS_Tools_VDF, and EOS_Tools_VEF.
self_cast() [1/2]
EOS_Tools_base & EOS_Tools_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const EOS_Tools_base & EOS_Tools_base::self_cast (const Objet_U & r) static
printOn()
Sortie & EOS_Tools_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
Reimplemented in EOS_Tools_VDF, and EOS_Tools_VEF.
readOn()
Entree & EOS_Tools_base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
Reimplemented in EOS_Tools_VDF, and EOS_Tools_VEF.
associer_fluide()
void EOS_Tools_base::associer_fluide (const Fluide_Dilatable_base & fl)
References le_fluide_.
Referenced by Fluide_Dilatable_base::completer().
mettre_a_jour()
virtual void EOS_Tools_base::mettre_a_jour (double) inline virtual
Reimplemented in EOS_Tools_VDF.
Referenced by Fluide_Dilatable_base::completer(), Fluide_Dilatable_base::prepare_pressure_edo(), and Fluide_Dilatable_base::preparer_pas_temps().
rho_discvit()
virtual const DoubleTab & EOS_Tools_base::rho_discvit () const pure virtual
Implemented in EOS_Tools_VDF, and EOS_Tools_VEF.
Referenced by Fluide_Dilatable_base::rho_discvit().
rho_face_n()
virtual const DoubleTab & EOS_Tools_base::rho_face_n () const pure virtual
Implemented in EOS_Tools_VDF, and EOS_Tools_VEF.
Referenced by Fluide_Dilatable_base::rho_face_n().
rho_face_np1()
virtual const DoubleTab & EOS_Tools_base::rho_face_np1 () const pure virtual
Implemented in EOS_Tools_VDF, and EOS_Tools_VEF.
Referenced by Fluide_Dilatable_base::rho_face_np1().
associer_domaines()
virtual void EOS_Tools_base::associer_domaines (const Domaine_dis_base & , const Domaine_Cl_dis_base &) pure virtual
Implemented in EOS_Tools_VDF, and EOS_Tools_VEF.
Referenced by Fluide_Dilatable_base::completer().
divu_discvit()
virtual void EOS_Tools_base::divu_discvit (const DoubleTab & , DoubleTab &) pure virtual
Implemented in EOS_Tools_VDF, and EOS_Tools_VEF.
Referenced by Fluide_Dilatable_base::divu_discvit().
secmembre_divU_Z()
virtual void EOS_Tools_base::secmembre_divU_Z (DoubleTab &) const pure virtual
Implemented in EOS_Tools_VDF, and EOS_Tools_VEF.
Referenced by Fluide_Quasi_Compressible::secmembre_divU_Z(), and Fluide_Weakly_Compressible::secmembre_divU_Z().
calculer_rho_face_np1()
virtual void EOS_Tools_base::calculer_rho_face_np1 (const DoubleTab & rho) pure virtual
Implemented in EOS_Tools_VDF, and EOS_Tools_VEF.
Referenced by Fluide_Dilatable_base::calculer_rho_face().
moyenne_vol()
virtual double EOS_Tools_base::moyenne_vol (const DoubleTab &) const pure virtual
Implemented in EOS_Tools_VDF, and EOS_Tools_VEF.
Referenced by Fluide_Dilatable_base::moyenne_vol(), Fluide_Dilatable_base::write_mean_edo(), and Fluide_Weakly_Compressible::write_mean_edo().
Member Data Documentation
info_obj
const Type_info EOS_Tools_base::info_obj static
le_fluide_
TRUST_Ref< Fluide_Dilatable_base *> EOS_Tools_base::le_fluide_ protected
Referenced by associer_fluide(), EOS_Tools_VDF::le_fluide(), EOS_Tools_VEF::le_fluide(), EOS_Tools_VEF::rho_discvit(), EOS_Tools_VEF::rho_face_n(), and EOS_Tools_VEF::rho_face_np1().