TrioCFD: Op_Dift_VEF_P1NCP1B_Face Class Reference
Op_Dift_VEF_P1NCP1B_Face Class Reference
#include <Op_Dift_VEF_P1NCP1B_Face.h>
Public Member Functions
double calculer_dt_stab () const override
const Type_info * get_info () const override
Public Member Functions inherited from Op_Dift_VEF_base
double calculer_dt_stab () const override
void completer () override
void dimensionner (Matrice_Morse &matrice) const override
const Type_info * get_info () const override
void mettre_a_jour (double temps) override
void modifier_pour_Cl (Matrice_Morse &matrice, DoubleTab &secmem) const override
Public Member Functions inherited from Op_Diff_VEF_base
double calculer_dt_stab () const override
const Type_info * get_info () const override
int impr (Sortie &os) const override
Public Member Functions inherited from Operateur_Diff_base
virtual void associer_diffusivite_pour_pas_de_temps (const Champ_base &)
const Type_info * get_info () const override
Public Member Functions inherited from Operateur_base
void associer_eqn (const Equation_base &)
virtual double calculer_dt_stab () const
virtual void completer ()
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual void mettre_a_jour (double temps)
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Public Member Functions inherited from Op_VEF_Face
void dimensionner (const Domaine_VEF &, const Domaine_Cl_VEF &, Matrice_Morse &) const
void modifier_matrice_pour_periodique_apres_contribuer (Matrice_Morse &matrice, const Equation_base &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Operateur_Diff_base
virtual const Champ_base & diffusivite_pour_pas_de_temps () const
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
La discretisation est VEF Le champ diffuse est scalaire Le champ de diffusivite est uniforme
Constructor & Destructor Documentation
Op_Dift_VEF_P1NCP1B_Face()
Op_Dift_VEF_P1NCP1B_Face::Op_Dift_VEF_P1NCP1B_Face ()
~Op_Dift_VEF_P1NCP1B_Face()
Op_Dift_VEF_P1NCP1B_Face::~Op_Dift_VEF_P1NCP1B_Face ()
Member Function Documentation
cree_instance()
Objet_U * Op_Dift_VEF_P1NCP1B_Face::cree_instance () static
taille_memoire()
unsigned Op_Dift_VEF_P1NCP1B_Face::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Op_Dift_VEF_P1NCP1B_Face::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Op_Dift_VEF_P1NCP1B_Face::info () static
get_info()
const Type_info * Op_Dift_VEF_P1NCP1B_Face::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Op_Dift_VEF_base.
self_cast() [1/2]
Op_Dift_VEF_P1NCP1B_Face & Op_Dift_VEF_P1NCP1B_Face::self_cast (Objet_U & r) static
self_cast() [2/2]
const Op_Dift_VEF_P1NCP1B_Face & Op_Dift_VEF_P1NCP1B_Face::self_cast (const Objet_U & r) static
printOn()
Sortie & Op_Dift_VEF_P1NCP1B_Face::printOn (Sortie & os) const override protected virtual
DOES NOTHING - to override in derived classes.
Imprime l'operateur sur un flot de sortie.
Parameters
(Sortie& os) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Op_Dift_VEF_base.
References Objet_U::que_suis_je().
readOn()
Entree & Op_Dift_VEF_P1NCP1B_Face::readOn (Entree & is) override protected virtual
DOES NOTHING - to override in derived classes.
Lit un operateur sur un flot d'entree.
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Op_Dift_VEF_base.
associer()
void Op_Dift_VEF_P1NCP1B_Face::associer (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_cl_dis, const Champ_Inc_base & ch_transporte) override virtual
Reimplemented from Op_Dift_VEF_base.
References Op_Diff_VEF_base::inconnue_, Op_Diff_VEF_base::la_zcl_vef, Op_Diff_VEF_base::le_dom_vef, SolveurSys::nommer(), solveur, Objet_U_ptr::typer(), and TRUST_Deriv< _CLASSE_ >::valeur().
ajouter()
DoubleTab & Op_Dift_VEF_P1NCP1B_Face::ajouter (const DoubleTab & inconnue, DoubleTab & resu) const override virtual
Reimplemented from Operateur_base.
References calculer_divergence_elem(), calculer_divergence_som(), calculer_gradient_elem(), calculer_gradient_som(), corriger_div_pour_Cl(), Op_Dift_VEF_base::diffusivite(), Op_Diff_Turbulent_base::diffusivite_turbulente(), Objet_U::dimension, Domaine_dis_base::domaine(), Op_Diff_VEF_base::domaine_vef(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Op_VEF_Face::modifier_flux(), Domaine_32_64< _SIZE_ >::nb_elem_tot(), Domaine_32_64< _SIZE_ >::nb_som_tot(), and Champ_Don_base::valeurs().
calculer_dt_stab()
double Op_Dift_VEF_P1NCP1B_Face::calculer_dt_stab () const inline override virtual
Calcul dt_stab.
Returns
(double) renvoie toujours 1.e30
Reimplemented from Op_Dift_VEF_base.
References Op_Dift_VEF_base::calculer_dt_stab_P1NCP1B().
remplir_nu()
void Op_Dift_VEF_P1NCP1B_Face::remplir_nu (DoubleTab &) const inline override virtual
Reimplemented from Op_Diff_VEF_base.
References Process::exit().
calculer_gradient_elem()
DoubleTab & Op_Dift_VEF_P1NCP1B_Face::calculer_gradient_elem (const DoubleTab & vit, DoubleTab & grad) const protected
References Objet_U::dimension, Domaine_dis_base::domaine(), Op_Diff_VEF_base::domaine_vef(), Domaine_VF::elem_faces(), Domaine_VF::face_normales(), Domaine_VF::face_voisins(), Domaine_32_64< _SIZE_ >::nb_elem_tot(), and Domaine_32_64< _SIZE_ >::nb_faces_elem().
Referenced by ajouter().
calculer_gradient_som()
DoubleTab & Op_Dift_VEF_P1NCP1B_Face::calculer_gradient_som (const DoubleTab & vit, DoubleTab & grad) const protected
References Matrice_Morse_Sym::compacte(), Domaine_32_64< _SIZE_ >::creer_tableau_sommets(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Matrice_Morse::dimensionner(), Domaine_dis_base::domaine(), Op_Diff_VEF_base::domaine_cl_vef(), Op_Diff_VEF_base::domaine_vef(), Domaine_VF::elem_faces(), Domaine_VF::face_normales(), Domaine_VF::face_sommets(), Domaine_VF::face_voisins(), Domaine_32_64< _SIZE_ >::get_renum_som_perio(), Domaine_Cl_dis_base::les_conditions_limites(), Domaine_32_64< _SIZE_ >::les_elems(), masse, Domaine_32_64< _SIZE_ >::nb_elem_tot(), Front_VF::nb_faces(), Domaine_32_64< _SIZE_ >::nb_faces_elem(), Matrice_Morse::nb_lignes(), Domaine_32_64< _SIZE_ >::nb_som_elem(), Front_VF::num_premiere_face(), Domaine_VEF::numero_premier_sommet(), Matrice_Morse::remplir(), savgrad, Matrice_Sym::set_est_definie(), TRUST_Vector< _CLASSE_ >::size(), solveur, TRUST_Deriv< _CLASSE_ >::valeur(), and Domaine_VF::volumes().
Referenced by ajouter().
calculer_divergence_elem()
DoubleTab & Op_Dift_VEF_P1NCP1B_Face::calculer_divergence_elem (double nu, const DoubleTab & nu_turb, const DoubleTab & grad, DoubleTab & div) const protected
References Objet_U::dimension, Domaine_dis_base::domaine(), Op_Diff_VEF_base::domaine_vef(), Domaine_VF::elem_faces(), Domaine_VF::face_normales(), Domaine_VF::face_voisins(), Domaine_32_64< _SIZE_ >::nb_elem_tot(), and Domaine_32_64< _SIZE_ >::nb_faces_elem().
Referenced by ajouter().
calculer_divergence_som()
DoubleTab & Op_Dift_VEF_P1NCP1B_Face::calculer_divergence_som (double nu, const DoubleTab & nu_turb, const DoubleTab & grad, DoubleTab & div) const protected
References Objet_U::dimension, Domaine_dis_base::domaine(), Op_Diff_VEF_base::domaine_cl_vef(), Op_Diff_VEF_base::domaine_vef(), Domaine_VF::elem_faces(), Domaine_VF::face_normales(), Domaine_VF::face_sommets(), Domaine_VF::face_voisins(), Domaine_32_64< _SIZE_ >::get_renum_som_perio(), Domaine_Cl_dis_base::les_conditions_limites(), Domaine_32_64< _SIZE_ >::les_elems(), Domaine_32_64< _SIZE_ >::nb_elem_tot(), Front_VF::nb_faces(), Domaine_32_64< _SIZE_ >::nb_faces_elem(), Front_VF::num_premiere_face(), Domaine_VEF::numero_premier_sommet(), TRUST_Vector< _CLASSE_ >::size(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by ajouter().
corriger_div_pour_Cl()
DoubleTab & Op_Dift_VEF_P1NCP1B_Face::corriger_div_pour_Cl (DoubleTab & div) const protected
References Objet_U::dimension, Op_Diff_VEF_base::domaine_cl_vef(), Op_Diff_VEF_base::domaine_vef(), Periodique::face_associee(), Domaine_VF::face_normales(), Domaine_Cl_dis_base::les_conditions_limites(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), TRUST_Vector< _CLASSE_ >::size(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by ajouter().
Member Data Documentation
info_obj
const Type_info Op_Dift_VEF_P1NCP1B_Face::info_obj static
solveur
SolveurSys Op_Dift_VEF_P1NCP1B_Face::solveur protected
Referenced by associer(), and calculer_gradient_som().
masse
Matrice_Morse_Sym Op_Dift_VEF_P1NCP1B_Face::masse protected
Referenced by calculer_gradient_som().
savgrad
DoubleTab Op_Dift_VEF_P1NCP1B_Face::savgrad protected
Referenced by calculer_gradient_som().