TrioCFD: Eval_Quick_VDF_Elem Class Reference
Eval_Quick_VDF_Elem Class Reference
#include <Eval_Conv_VDF_Elem_leaves.h>
Detailed Description
Schema de convection Quick
Member Function Documentation
amont_amont()
int Eval_Quick_VDF_Elem::amont_amont (int face, int i) const inline override virtual
Reimplemented from Eval_Conv_VDF_tools.
References Evaluateur_VDF::le_dom.
dim_elem()
double Eval_Quick_VDF_Elem::dim_elem (int n1, int k) const inline override virtual
Reimplemented from Eval_Conv_VDF_tools.
References Evaluateur_VDF::le_dom.
Referenced by quick_fram().
dist_elem()
double Eval_Quick_VDF_Elem::dist_elem (int n1, int n2, int k) const inline override virtual
Reimplemented from Eval_Conv_VDF_tools.
References Evaluateur_VDF::le_dom.
Referenced by quick_fram().
quick_fram()
template<typename Type_Double > void Eval_Quick_VDF_Elem::quick_fram (const double psc, const int num0, const int num1, const int num0_0, const int num1_1, const int face, const DoubleTab & transporte, Type_Double & flux) const inline
References dim_elem(), dist_elem(), and Evaluateur_VDF::orientation.
Member Data Documentation
IS_QUICK
constexpr bool Eval_Quick_VDF_Elem::IS_QUICK = true static constexpr