TrioCFD: Pb_Couple_Rayonnement Class Reference
Pb_Couple_Rayonnement Class Reference
#include <Pb_Couple_Rayonnement.h>
Public Member Functions
int associer_ (Objet_U &) override
const Type_info * get_info () const override
void initialize () override
int postraiter (int force=1) override
void validateTimeStep () override
Public Member Functions inherited from Probleme_Couple
void ajouter (Probleme_base &)
int associer_ (Objet_U &) override
virtual void associer_sch_tps_base (Schema_Temps_base &)
double computeTimeStep (bool &stop) const override
virtual void discretiser (Discretisation_base &)
const Type_info * get_info () const override
void initialize () override
bool initTimeStep (double dt) override
bool iterateTimeStep (bool &converged) override
virtual Schema_Temps_base & schema_temps ()
virtual const Schema_Temps_base & schema_temps () const
bool updateGivenFields () override
Public Member Functions inherited from Couplage_U
void abortTimeStep () override
TRUST_Ref< Field_base * > findInputField (const Nom &name) const override
double futureTime () const override
const Type_info * get_info () const override
void getInputFieldsNames (Noms &noms) const override
void getOutputFieldsNames (Noms &noms) const override
void initialize () override
bool initTimeStep (double dt) override
bool isStationary () const override
bool iterateTimeStep (bool &converged) override
int postraiter (int force=1) override
double presentTime () const override
void resetTime (double t) override
void terminate () override
bool updateGivenFields () override
void validateTimeStep () override
Public Member Functions inherited from Probleme_U
virtual void abortTimeStep ()
virtual double computeTimeStep (bool &stop) const
virtual TRUST_Ref< Field_base * > findInputField (const Nom &name) const
virtual double futureTime () const
const Type_info * get_info () const override
virtual void getInputFieldsNames (Noms &noms) const
virtual void getOutputFieldsNames (Noms &noms) const
virtual void initialize ()
virtual bool initTimeStep (double dt)
virtual bool isStationary () const
virtual bool iterateTimeStep (bool &converged)
const Nom & le_nom () const override
void nommer (const Nom &name) override
virtual int postraiter (int force=1)
virtual double presentTime () const
virtual void resetTime (double time)
virtual bool run ()
virtual bool runUntil (double time)
virtual void terminate ()
virtual bool updateGivenFields ()
virtual void validateTimeStep ()
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Pb_Couple_Rayonnement()
Pb_Couple_Rayonnement::Pb_Couple_Rayonnement ()
~Pb_Couple_Rayonnement()
Pb_Couple_Rayonnement::~Pb_Couple_Rayonnement ()
Member Function Documentation
cree_instance()
Objet_U * Pb_Couple_Rayonnement::cree_instance () static
taille_memoire()
unsigned Pb_Couple_Rayonnement::taille_memoire () const override virtual
Reimplemented from Probleme_Couple.
duplique()
int Pb_Couple_Rayonnement::duplique () const override virtual
Reimplemented from Probleme_Couple.
info()
const Type_info * Pb_Couple_Rayonnement::info () static
get_info()
const Type_info * Pb_Couple_Rayonnement::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Probleme_Couple.
self_cast() [1/2]
Pb_Couple_Rayonnement & Pb_Couple_Rayonnement::self_cast (Objet_U & r) static
self_cast() [2/2]
const Pb_Couple_Rayonnement & Pb_Couple_Rayonnement::self_cast (const Objet_U & r) static
printOn()
Sortie & Pb_Couple_Rayonnement::printOn (Sortie & os) const override protected virtual
Surcharge Objet_U::printOn(Sortie&) Imprime les problemes couples sur un flot de sortie.
Parameters
(Sortie& os) le flot de sortie sur lequel imprimer
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Probleme_Couple.
References Probleme_Couple::printOn().
readOn()
Entree & Pb_Couple_Rayonnement::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Probleme_Couple.
le_modele_rayo_associe()
void Pb_Couple_Rayonnement::le_modele_rayo_associe (const Modele_Rayonnement_base & un_modele_de_rayonnement)
References le_modele_de_rayo.
Referenced by associer_().
associer_cl_base()
void Pb_Couple_Rayonnement::associer_cl_base (const Cond_lim_base & les_cl_)
References les_cl.
associer_()
int Pb_Couple_Rayonnement::associer_ (Objet_U & ob) override virtual
Surcharge Objet_U::associer_(Objet_U&) Associe un objet au probleme couple, en verifiant le type.
dynamiquement. L'objet peut-etre:
un schema en temps (Schema_Temps_base), et on l'associe aux problemes
un probleme (Probleme_base), on l'ajoute a la liste
Parameters
(Objet_U& ob) l'objet a associer
Returns
(int) 1 si l'association a reussie 0 sinon
Exceptions
l'objet n'est pas d'un type attendu
Reimplemented from Probleme_Couple.
References Probleme_Couple::associer_(), Fluide_base::fixer_type_rayo(), le_modele_rayo_associe(), Probleme_base::milieu(), Couplage_U::nb_problemes(), Couplage_U::probleme(), and Fluide_base::reset_type_rayo().
completer()
void Pb_Couple_Rayonnement::completer ()
References Process::abort(), Ensemble_Faces_base::associer_les_cl(), Modele_Rayonnement_Milieu_Transparent::associer_processeur_rayonnant(), Equation_base::domaine_Cl_dis(), Face_Rayonnante::emissivite(), Face_Rayonnante::ensembles_faces_bord(), Probleme_base::equation(), Process::exit(), Modele_Rayonnement_Milieu_Transparent::face_rayonnante(), Ensemble_Faces_base::is_ok(), Milieu_base::is_rayo_transp(), le_modele_de_rayo, Probleme_U::le_nom(), Objet_U_ptr::le_nom(), Domaine_Cl_dis_base::les_conditions_limites(), Process::me(), Probleme_base::milieu(), Domaine_Cl_dis_base::nb_cond_lim(), Ensemble_Faces_base::nb_faces_bord(), Modele_Rayonnement_Milieu_Transparent::nb_faces_rayonnantes(), Modele_Rayonnement_Milieu_Transparent::nb_faces_totales(), Couplage_U::nb_problemes(), Face_Rayonnante::nom_bord_rayo(), Face_Rayonnante::nom_bord_rayo_lu(), Modele_Rayonnement_Milieu_Transparent::nom_pb_rayonnant(), Probleme_base::nombre_d_equations(), Process::nproc(), Couplage_U::probleme(), TRUST_Deriv< _CLASSE_ >::valeur(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by initialize().
validateTimeStep()
void Pb_Couple_Rayonnement::validateTimeStep () override virtual
Validates the calculated unknown by moving the present time at the end of the time step.
This method is allowed to free past values of the unknown and given fields.
Exceptions
WrongContext
Reimplemented from Couplage_U.
References le_modele_rayo(), Modele_Rayonnement_base::mettre_a_jour(), Couplage_U::presentTime(), and Couplage_U::validateTimeStep().
initialize()
void Pb_Couple_Rayonnement::initialize () override virtual
This method is called once at the beginning, before any other one of the interface Problem.
Exceptions
WrongContext
Reimplemented from Probleme_Couple.
References completer(), Probleme_Couple::initialize(), le_modele_rayo(), and Modele_Rayonnement_base::preparer_calcul().
le_modele_rayo()
Modele_Rayonnement_base & Pb_Couple_Rayonnement::le_modele_rayo () inline
References le_modele_de_rayo, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by initialize(), and validateTimeStep().
cond_l_base()
Cond_lim_base & Pb_Couple_Rayonnement::cond_l_base () inline
References les_cl, and TRUST_Ref< _CLASSE_ >::valeur().
postraiter()
int Pb_Couple_Rayonnement::postraiter (int force = 1) override virtual
Demande au probleme de postraiter ses champs, sondes,.
.. Dans Probleme_U::run(), postraiter() est appele a chaque pas de temps avec force=0 et au debut et a la fin du calcul avec force=1. WEC : il serait bon que, un jour, postraiter soit const
Parameters
(force) 1=postraiter absolument, 0=postraiter si c'est necessaire.
Returns
(0 en cas d'erreur, 1 sinon.)
Reimplemented from Couplage_U.
References le_modele_de_rayo, Couplage_U::limpr(), Couplage_U::postraiter(), Modele_Rayonnement_Milieu_Transparent::processeur_rayonnant(), Probleme_Couple::schema_temps(), and TRUST_Ref< _CLASSE_ >::valeur().
Member Data Documentation
info_obj
const Type_info Pb_Couple_Rayonnement::info_obj static
le_modele_de_rayo
TRUST_Ref< Modele_Rayonnement_base *> Pb_Couple_Rayonnement::le_modele_de_rayo protected
Referenced by completer(), le_modele_rayo(), le_modele_rayo_associe(), and postraiter().
les_cl
TRUST_Ref< Cond_lim_base *> Pb_Couple_Rayonnement::les_cl protected
Referenced by associer_cl_base(), and cond_l_base().