TrioCFD: Solveur_Masse_Face_proto Class Reference
Solveur_Masse_Face_proto Class Reference
#include <Solveur_Masse_Face_proto.h>
Member Function Documentation
associer_masse_proto()
void Solveur_Masse_Face_proto::associer_masse_proto (const Solveur_Masse_base & sm, const Domaine_VF & zvf)
References le_dom_, and solv_mass_.
Referenced by Masse_PolyMAC_P0_Face::completer(), Masse_PolyMAC_P0P1NC_Face::completer(), and Masse_VDF_Face::completer().
appliquer_impl_proto()
DoubleTab & Solveur_Masse_Face_proto::appliquer_impl_proto (DoubleTab & sm) const
References TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), le_dom_, solv_mass_, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Masse_PolyMAC_P0_Face::appliquer_impl(), and Masse_VDF_Face::appliquer_impl().
dimensionner_blocs_proto()
void Solveur_Masse_Face_proto::dimensionner_blocs_proto (matrices_t matrices, const tabs_t & semi_impl, const bool allocate, IntTab & sten) const
References Matrix_tools::allocate_morse_matrix(), TRUSTTab< _TYPE_, _SIZE_ >::append_line(), Probleme_base::get_correlation(), Nom::getString(), Probleme_base::has_correlation(), le_dom_, TRUST_Ref< _CLASSE_ >::le_nom(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Matrice_Morse::nb_colonnes(), TRUSTVect< _TYPE_, _SIZE_ >::size_totale(), solv_mass_, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Masse_PolyMAC_P0_Face::dimensionner_blocs(), Masse_PolyMAC_P0P1NC_Face::dimensionner_blocs(), and Masse_VDF_Face::dimensionner_blocs().
ajouter_blocs_proto()
void Solveur_Masse_Face_proto::ajouter_blocs_proto (matrices_t matrices, DoubleTab & secmem, double dt, const tabs_t & semi_impl, int resoudre_en_increments) const
References Masse_ajoutee_base::ajouter(), Equation_base::champ_conserve(), Pb_Multiphase::equation_masse(), Probleme_base::get_correlation(), Nom::getString(), Probleme_base::has_correlation(), Equation_base::inconnue(), le_dom_, TRUST_Ref< _CLASSE_ >::le_nom(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Champ_Inc_base::passe(), solv_mass_, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Masse_PolyMAC_P0P1NC_Face::ajouter_blocs().
Member Data Documentation
solv_mass_
TRUST_Ref< Solveur_Masse_base *> Solveur_Masse_Face_proto::solv_mass_ protected
Referenced by ajouter_blocs_proto(), appliquer_impl_proto(), associer_masse_proto(), and dimensionner_blocs_proto().
le_dom_
TRUST_Ref< Domaine_VF *> Solveur_Masse_Face_proto::le_dom_ protected
Referenced by ajouter_blocs_proto(), appliquer_impl_proto(), associer_masse_proto(), and dimensionner_blocs_proto().