TrioCFD: Champ_front_contact_VEF Class Reference
Champ_front_contact_VEF Class Reference
#include <Champ_front_contact_VEF.h>
Public Member Functions
void calculer_coeffs_echange (double temps) override
const Type_info * get_info () const override
int initialiser (double temps, const Champ_Inc_base &inco) override
void mettre_a_jour (double temps) override
const Type_info * get_info () const override
int initialiser (double temps, const Champ_Inc_base &inco) override
Public Member Functions inherited from Champ_front_var_instationnaire
int avancer (double temps) override
const Type_info * get_info () const override
int initialiser (double temps, const Champ_Inc_base &inco) override
int reculer (double temps) override
const DoubleTab & valeurs_au_temps (double temps) const override
DoubleTab & valeurs_au_temps (double temps) override
const Type_info * get_info () const override
int initialiser (double temps, const Champ_Inc_base &inco) override
Public Member Functions inherited from Champ_front_base
virtual void associer_fr_dis_base (const Frontiere_dis_base &)
virtual int avancer (double temps)
virtual void calculer_coeffs_echange (double temps)
virtual void fixer_nb_valeurs_temporelles (int nb_cases)
virtual Frontiere_dis_base & frontiere_dis ()
virtual const Frontiere_dis_base & frontiere_dis () const
const Type_info * get_info () const override
virtual int initialiser (double temps, const Champ_Inc_base &inco)
virtual void mettre_a_jour (double temps)
virtual int reculer (double temps)
virtual const DoubleTab & valeurs () const override
virtual DoubleTab & valeurs () override
virtual void valeurs_face (int, DoubleVect &) const
Public Member Functions inherited from Field_base
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
virtual void fixer_nb_comp (int i)
virtual const Nom & fixer_nom_compo (const Nom &)
virtual const Nom & fixer_nom_compo (int, const Nom &)
virtual const Noms & fixer_noms_compo (const Noms &)
virtual const Nom & fixer_unite (const Nom &)
virtual const Nom & fixer_unite (int i, const Nom &)
virtual const Noms & fixer_unites (const Noms &)
const Type_info * get_info () const override
const Nom & nom_compo (int) const
void nommer (const Nom &) override
const Nom & unite () const
const Nom & unite (int) const
const Noms & unites () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Champ_Proto
int lire_dimension (Entree &, const Nom &)
int lire_dimension (int dim, const Nom &le_nom_)
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
la valeur a la paroi qui permet d'egaliser les flux.
calculer_coeffs_echange stocke grad_num_local et grad_fro_local tels que (aux signes pres?)
flux = grad_num_local + Scal_paroi*grad_fro_local
mettre_a_jour recupere les grad* d'en face et calcule Scal_paroi de
facon a egaliser les flux.
See also
Champ_front_var_instationnaire Champ_Inc
Constructor & Destructor Documentation
Champ_front_contact_VEF()
Champ_front_contact_VEF::Champ_front_contact_VEF ()
~Champ_front_contact_VEF()
Champ_front_contact_VEF::~Champ_front_contact_VEF ()
Member Function Documentation
cree_instance()
Objet_U * Champ_front_contact_VEF::cree_instance () static
taille_memoire()
unsigned Champ_front_contact_VEF::taille_memoire () const override virtual
Reimplemented from Ch_front_var_instationnaire_dep.
Reimplemented in Champ_front_contact_rayo_transp_VEF, and Champ_front_contact_rayo_semi_transp_VEF.
duplique()
int Champ_front_contact_VEF::duplique () const override virtual
Reimplemented from Ch_front_var_instationnaire_dep.
Reimplemented in Champ_front_contact_rayo_transp_VEF, and Champ_front_contact_rayo_semi_transp_VEF.
info()
const Type_info * Champ_front_contact_VEF::info () static
get_info()
const Type_info * Champ_front_contact_VEF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Ch_front_var_instationnaire_dep.
Reimplemented in Champ_front_contact_rayo_transp_VEF, and Champ_front_contact_rayo_semi_transp_VEF.
self_cast() [1/2]
Champ_front_contact_VEF & Champ_front_contact_VEF::self_cast (Objet_U & r) static
self_cast() [2/2]
const Champ_front_contact_VEF & Champ_front_contact_VEF::self_cast (const Objet_U & r) static
printOn()
Sortie & Champ_front_contact_VEF::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Ch_front_var_instationnaire_dep.
Reimplemented in Champ_front_contact_rayo_transp_VEF, and Champ_front_contact_rayo_semi_transp_VEF.
readOn()
Entree & Champ_front_contact_VEF::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Ch_front_var_instationnaire_dep.
Reimplemented in Champ_front_contact_rayo_transp_VEF, and Champ_front_contact_rayo_semi_transp_VEF.
References connect_est_remplit, Field_base::fixer_nb_comp(), Process::is_parallel(), nom_bord1, nom_bord2, nom_pb1, and nom_pb2.
Referenced by Champ_front_contact_rayo_transp_VEF::readOn(), Champ_front_contact_rayo_semi_transp_VEF::readOn(), and Champ_front_contact_fictif_VEF::readOn().
initialiser()
int Champ_front_contact_VEF::initialiser (double temps, const Champ_Inc_base & inco) override virtual
Initialisation en debut de calcul.
Imperativement cette methode ne doit pas utiliser de donnees externes a l'equation (couplage). Si mettre_a_jour le fait, alors initialiser ne doit pas appeler mettre_a_jour.
Returns
(0 en cas d'erreur, 1 sinon.)
Reimplemented from Ch_front_var_instationnaire_dep.
Reimplemented in Champ_front_contact_rayo_transp_VEF, and Champ_front_contact_rayo_semi_transp_VEF.
References associer_ch_inc_base(), associer_front_vf_et_ch_front_autre_pb(), calculer_coeffs_echange(), coeff_amort_denum, coeff_amort_num, connect_est_remplit, creer(), Domaine_dis_base::domaine(), Frontiere_dis_base::domaine_dis(), Process::exit(), front_dis(), Frontiere_dis_base::frontiere(), Champ_front_base::frontiere_dis(), gradient_fro_local, gradient_fro_transf, gradient_num_local, gradient_num_transf, Raccord_distant_homogene_32_64< _SIZE_ >::initialise(), Ch_front_var_instationnaire_dep::initialiser(), is_conduction, Process::is_parallel(), l_inconnue1, l_inconnue2, Domaine_base::le_nom(), Frontiere_32_64< _SIZE_ >::le_nom(), Frontiere_32_64< _SIZE_ >::nb_faces(), nom_bord, nom_bord1, nom_bord2, nom_pb1, nom_pb2, remplir_connect_bords(), remplir_elems_voisin_bord(), remplir_faces_coin(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), Scal_moy, TRUST_Ref< _CLASSE_ >::valeur(), and verification_faces_coin.
Referenced by Champ_front_contact_rayo_transp_VEF::initialiser(), and Champ_front_contact_rayo_semi_transp_VEF::initialiser().
affecter_()
Champ_front_base & Champ_front_contact_VEF::affecter_ (const Champ_front_base & ch) override virtual
Reimplemented from Ch_front_var_instationnaire_dep.
Reimplemented in Champ_front_contact_rayo_transp_VEF, and Champ_front_contact_rayo_semi_transp_VEF.
mettre_a_jour()
void Champ_front_contact_VEF::mettre_a_jour (double temps) override virtual
NE FAIT RIEN, a surcharger.
Cette methode est appelee au debut de chaque pas de temps ou sous-pas-de-temps, elle peut eventuellement utiliser des donnees exterieures a l'equation. A charge a l'algorithme de s'assurer que ces donnees sont pertinentes... Calcule la valeur de la condition aux limites au temps demande.
Parameters
(double)
Reimplemented from Champ_front_base.
Reimplemented in Champ_front_contact_rayo_transp_VEF, and Champ_front_contact_rayo_semi_transp_VEF.
References ch_fr_autre_pb, TRUST_Ref< _CLASSE_ >::est_nul(), Process::exit(), fr_vf_autre_pb, gradient_fro_local, gradient_num_local, Champ_front_base::la_frontiere_dis, Frontiere_32_64< _SIZE_ >::nb_faces(), nom_bord1, nom_bord2, nom_pb1, nom_pb2, test_faces_coin(), trace_face_raccord(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_front_var_instationnaire::valeurs_au_temps(), and verification_faces_coin.
Referenced by Champ_front_contact_rayo_transp_VEF::mettre_a_jour().
calculer_coeffs_echange()
void Champ_front_contact_VEF::calculer_coeffs_echange (double temps) override virtual
NE FAIT RIEN, a surcharger Cette methode peut calculer et stocker des donnees utiles a la.
CL, et dependant uniquement de l'inconnue sur laquelle porte cette CL (pas de l'exterieur). cf Champ_front_contact_VEF par exemple. Elle est appelee lorsque l'inconnue est modifiee.
Parameters
(double)
Reimplemented from Champ_front_base.
Reimplemented in Champ_front_contact_rayo_transp_VEF.
References calcul_grads_locaux(), and calcul_grads_transf().
Referenced by Champ_front_contact_rayo_transp_VEF::calculer_coeffs_echange(), and initialiser().
creer()
void Champ_front_contact_VEF::creer (const Nom & nompb1, const Nom & nom1, const Nom & nompb2, const Nom & nom2, const Motcle & nom_inco)
References Probleme_base::equation(), Process::exit(), Probleme_base::get_champ(), Equation_base::inconnue(), l_inconnue1, l_inconnue2, Field_base::le_nom(), nom_bord1, nom_bord2, and Interprete::objet().
Referenced by initialiser().
inconnue()
const Champ_Inc_base & Champ_front_contact_VEF::inconnue () const
References l_inconnue, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by domaine_dis(), and equation().
equation()
const Equation_base & Champ_front_contact_VEF::equation () const
References MorEqn::equation(), TRUST_Ref< _CLASSE_ >::est_nul(), Process::exit(), inconnue(), and l_inconnue.
Referenced by domaine_Cl_dis(), and milieu().
domaine_dis()
const Domaine_dis_base & Champ_front_contact_VEF::domaine_dis () const override virtual
Reimplemented from Champ_front_base.
References Champ_Inc_base::domaine_dis_base(), and inconnue().
Referenced by calcul_grads_locaux(), and front_dis().
domaine_Cl_dis()
const Domaine_Cl_dis_base & Champ_front_contact_VEF::domaine_Cl_dis () const
References Equation_base::domaine_Cl_dis(), and equation().
front_dis()
const Frontiere_dis_base & Champ_front_contact_VEF::front_dis () const
References domaine_dis(), Domaine_dis_base::frontiere_dis(), and nom_bord.
Referenced by calcul_grads_locaux(), and initialiser().
associer_ch_inc_base()
void Champ_front_contact_VEF::associer_ch_inc_base (const Champ_Inc_base & inco)
References l_inconnue.
Referenced by calcul_grads_locaux(), initialiser(), and remplir_connect_bords().
nom_bord_oppose()
const Nom & Champ_front_contact_VEF::nom_bord_oppose () const
References nom_bord.
milieu()
const Milieu_base & Champ_front_contact_VEF::milieu () const
References equation(), and Equation_base::milieu().
Referenced by calcul_grads_locaux().
calcul_grads_transf()
void Champ_front_contact_VEF::calcul_grads_transf (double temps) virtual
References TRUSTArray< _TYPE_, _SIZE_ >::copy_array(), gradient_fro_local, gradient_fro_transf, gradient_num_local, and gradient_num_transf.
Referenced by calculer_coeffs_echange().
calcul_grads_locaux()
void Champ_front_contact_VEF::calcul_grads_locaux (double temps) virtual
Reimplemented in Champ_front_contact_rayo_transp_VEF, and Champ_front_contact_rayo_semi_transp_VEF.
References associer_ch_inc_base(), Milieu_base::conductivite(), Modele_turbulence_scal_base::conductivite_turbulente(), Objet_U::dimension, Domaine_dis_base::domaine(), domaine_dis(), Domaine_VF::elem_faces(), MorEqn::equation(), Turbulence_paroi_scal_base::equivalent_distance(), Domaine_VF::face_normales(), Domaine_VF::face_surfaces(), Domaine_VF::face_voisins(), front_dis(), Domaine_VF::front_VF(), Equation_base::get_modele(), gradient_fro_local, gradient_num_local, l_inconnue, l_inconnue1, Frontiere_dis_base::le_nom(), Modele_turbulence_scal_base::loi_paroi(), Modele_turbulence_scal_base::loi_paroi_non_nulle(), milieu(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Front_VF::nb_faces(), Domaine_32_64< _SIZE_ >::nb_faces_elem(), nom_bord, nom_bord1, TRUST_Ref_Objet_U::non_nul(), Front_VF::num_premiere_face(), Domaine_VEF::oriente_normale(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), Scal_moy, Turbulence_paroi_scal_base::use_equivalent_distance(), TRUST_Ref< _CLASSE_ >::valeur(), TRUST_Ref_Objet_U::valeur(), Champ_Don_base::valeurs(), and Domaine_VF::volumes().
Referenced by Champ_front_contact_rayo_transp_VEF::calcul_grads_locaux(), Champ_front_contact_rayo_semi_transp_VEF::calcul_grads_locaux(), and calculer_coeffs_echange().
calcul_coeff_amort()
void Champ_front_contact_VEF::calcul_coeff_amort ()
References coeff_amort_denum, coeff_amort_num, Milieu_base::diffusivite(), Objet_U::dimension, Domaine_VF::face_normales(), Domaine_VF::face_voisins(), Domaine_VF::frontiere_dis(), l_inconnue1, Front_VF::nb_faces(), nom_bord1, Front_VF::num_premiere_face(), Domaine_dis_base::rang_frontiere(), Champ_Don_base::valeurs(), and Domaine_VF::volumes().
Referenced by Champ_front_contact_rayo_transp_VEF::calcul_grads_locaux(), and Champ_front_contact_rayo_semi_transp_VEF::calcul_grads_locaux().
recupere_gradients_autre_pb()
void Champ_front_contact_VEF::recupere_gradients_autre_pb (const Front_VF & , DoubleVect & , DoubleVect &)
trace_face_raccord()
DoubleVect & Champ_front_contact_VEF::trace_face_raccord (const Front_VF & fr_vf, const DoubleVect & y, DoubleVect & x)
References connect_bords, Process::exit(), Frontiere_dis_base::frontiere(), Process::is_parallel(), Frontiere_32_64< _SIZE_ >::le_nom(), TRUSTVect< _TYPE_, _SIZE_ >::size(), and Frontiere_32_64< _SIZE_ >::trace_face_distant().
Referenced by Champ_front_contact_rayo_transp_VEF::calculer_temperature_bord(), Champ_front_contact_rayo_semi_transp_VEF::calculer_temperature_bord(), Champ_front_contact_fictif_VEF::mettre_a_jour(), mettre_a_jour(), Champ_front_contact_rayo_transp_VEF::mettre_a_jour_flux_radiatif(), Champ_front_contact_rayo_semi_transp_VEF::mettre_a_jour_flux_radiatif(), and verifier_scalaire_bord().
remplir_connect_bords()
void Champ_front_contact_VEF::remplir_connect_bords ()
if (j==1) { Cout << "connect i j " << i << " " << j << finl; Cout << "xv i j " << xv1(ndeb1+i,0) << " " << xv2(ndeb2+j,0) << finl; Cout << "xv i j " << xv1(ndeb1+i,1) << " " << xv2(ndeb2+j,1) << finl; Cout << "xv i j " << xv1(ndeb1+i,2) << " " << xv2(ndeb2+j,2) << finl; Cout << "err i j " << std::fabs(xv1(ndeb1+i,0) - xv2(ndeb2+j,0)) << finl; Cout << "err i j " << std::fabs(xv1(ndeb1+i,1) - xv2(ndeb2+j,1)) << finl; Cout << "err i j " << std::fabs(xv1(ndeb1+i,2) - xv2(ndeb2+j,2)) << finl; Cout << "erreur " << erreur << finl; }
if (j==1) { Cout << "connect i j " << i << " " << j << finl; Cout << "xv i j " << xv1(ndeb1+i,0) << " " << xv2(ndeb2+j,0) << finl; Cout << "xv i j " << xv1(ndeb1+i,1) << " " << xv2(ndeb2+j,1) << finl; Cout << "xv i j " << xv1(ndeb1+i,2) << " " << xv2(ndeb2+j,2) << finl; Cout << "err i j " << std::fabs(xv1(ndeb1+i,0) - xv2(ndeb2+j,0)) << finl; Cout << "err i j " << std::fabs(xv1(ndeb1+i,1) - xv2(ndeb2+j,1)) << finl; Cout << "err i j " << std::fabs(xv1(ndeb1+i,2) - xv2(ndeb2+j,2)) << finl; Cout << "erreur " << erreur << finl; }
References associer_ch_inc_base(), connect_bords, connectivity_failed(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), Process::exit(), Domaine_VF::face_voisins(), Domaine_VF::frontiere_dis(), l_inconnue1, l_inconnue2, Champ_front_base::la_frontiere_dis, Frontiere_dis_base::le_nom(), Domaine_base::le_nom(), Frontiere_32_64< _SIZE_ >::nb_faces(), Front_VF::nb_faces(), nom_bord, nom_bord1, nom_bord2, nom_pb1, nom_pb2, Front_VF::num_premiere_face(), Domaine_dis_base::rang_frontiere(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), TRUST_Ref< _CLASSE_ >::valeur(), and Domaine_VF::xv().
Referenced by initialiser().
verifier_scalaire_bord()
void Champ_front_contact_VEF::verifier_scalaire_bord (double temps)
References ch_fr_autre_pb, fr_vf_autre_pb, Champ_front_base::la_frontiere_dis, Frontiere_32_64< _SIZE_ >::nb_faces(), Scal_moy, trace_face_raccord(), TRUST_Ref< _CLASSE_ >::valeur(), and Champ_front_var_instationnaire::valeurs_au_temps().
Referenced by Champ_front_contact_rayo_semi_transp_VEF::mettre_a_jour().
associer_front_vf_et_ch_front_autre_pb()
void Champ_front_contact_VEF::associer_front_vf_et_ch_front_autre_pb ()
References ch_fr_autre_pb, Cond_lim_base::champ_front(), Equation_base::domaine_Cl_dis(), MorEqn::equation(), Process::exit(), fr_vf_autre_pb, Cond_lim_base::frontiere_dis(), l_inconnue2, Frontiere_dis_base::le_nom(), Domaine_Cl_dis_base::les_conditions_limites(), Domaine_Cl_dis_base::nb_cond_lim(), nom_bord2, nom_pb1, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by initialiser().
connectivity_failed()
void Champ_front_contact_VEF::connectivity_failed (const Domaine_VEF & zvef1, int & nb_faces1, int & ndeb1, const Domaine_VEF & zvef2, int & nb_faces2, int & ndeb2, Nom & fichier, Nom & fichier_med)
References Champ_Fonc_base::associer_domaine_dis_base(), Domaine_32_64< _SIZE_ >::chercher_elements(), Sortie_Fichier_base::close(), Objet_U::dimension, Champ_Don_base::dimensionner(), Domaine_dis_base::domaine(), Format_Post_Med::ecrire_champ(), Format_Post_Med::ecrire_domaine(), Domaine_VF::elem_faces(), Process::exit(), Domaine_VF::face_voisins(), Field_base::fixer_nb_comp(), Format_Post_Med::initialize_by_default(), Field_base::le_nom(), Domaine_base::le_nom(), Domaine_dis_base::nb_elem(), Field_base::nommer(), Nom::prefix(), Champ_Don_base::valeurs(), and Domaine_VF::xv().
Referenced by remplir_connect_bords().
remplir_faces_coin()
void Champ_front_contact_VEF::remplir_faces_coin ()
References elems_voisin_bord_, faces_coin, get_elems_voisin_bord(), get_nom_bord1(), l_inconnue1, Domaine_Cl_dis_base::les_conditions_limites(), nom_bord1, TRUSTVect< _TYPE_, _SIZE_ >::resize(), TRUSTVect< _TYPE_, _SIZE_ >::size(), and TRUST_Vector< _CLASSE_ >::size().
Referenced by initialiser().
remplir_elems_voisin_bord()
void Champ_front_contact_VEF::remplir_elems_voisin_bord ()
References elems_voisin_bord_, Domaine_VF::face_voisins(), Domaine_VF::frontiere_dis(), l_inconnue1, Front_VF::nb_faces(), nom_bord1, Front_VF::num_premiere_face(), Domaine_dis_base::rang_frontiere(), and TRUSTVect< _TYPE_, _SIZE_ >::resize().
Referenced by initialiser().
test_faces_coin()
void Champ_front_contact_VEF::test_faces_coin ()
References Objet_U::dimension, Domaine_VF::frontiere_dis(), get_faces_coin(), get_nom_bord1(), l_inconnue1, TRUST_Ref< _CLASSE_ >::le_nom(), Domaine_Cl_dis_base::les_conditions_limites(), Front_VF::num_premiere_face(), Domaine_dis_base::rang_frontiere(), TRUSTVect< _TYPE_, _SIZE_ >::size(), TRUST_Vector< _CLASSE_ >::size(), and Domaine_VF::xv().
Referenced by mettre_a_jour().
set_gradient_num_local()
DoubleVect & Champ_front_contact_VEF::set_gradient_num_local () inline
References gradient_num_local.
get_gradient_num_local()
const DoubleVect & Champ_front_contact_VEF::get_gradient_num_local () const inline
References gradient_num_local.
set_gradient_fro_local()
DoubleVect & Champ_front_contact_VEF::set_gradient_fro_local () inline
References gradient_fro_local.
get_gradient_fro_local()
const DoubleVect & Champ_front_contact_VEF::get_gradient_fro_local () const inline
References gradient_fro_local.
set_gradient_num_transf()
DoubleVect & Champ_front_contact_VEF::set_gradient_num_transf () inline
References gradient_num_transf.
get_gradient_num_transf()
const DoubleVect & Champ_front_contact_VEF::get_gradient_num_transf () const inline
References gradient_num_transf.
set_gradient_fro_transf()
DoubleVect & Champ_front_contact_VEF::set_gradient_fro_transf () inline
References gradient_fro_transf.
get_gradient_fro_transf()
const DoubleVect & Champ_front_contact_VEF::get_gradient_fro_transf () const inline
References gradient_fro_transf.
set_coeff_amort_num()
DoubleVect & Champ_front_contact_VEF::set_coeff_amort_num () inline
References coeff_amort_num.
get_coeff_amort_num()
const DoubleVect & Champ_front_contact_VEF::get_coeff_amort_num () const inline
References coeff_amort_num.
set_coeff_amort_denum()
DoubleVect & Champ_front_contact_VEF::set_coeff_amort_denum () inline
References coeff_amort_denum.
get_coeff_amort_denum()
const DoubleVect & Champ_front_contact_VEF::get_coeff_amort_denum () const inline
References coeff_amort_denum.
get_elems_voisin_bord()
const IntVect & Champ_front_contact_VEF::get_elems_voisin_bord () const inline
References elems_voisin_bord_.
Referenced by remplir_faces_coin().
get_nom_bord1()
const Nom & Champ_front_contact_VEF::get_nom_bord1 () const inline
References nom_bord1.
Referenced by remplir_faces_coin(), and test_faces_coin().
get_connect_bords()
const IntVect & Champ_front_contact_VEF::get_connect_bords () const inline
References connect_bords.
get_faces_coin()
const IntVect & Champ_front_contact_VEF::get_faces_coin () const inline
References faces_coin.
Referenced by test_faces_coin().
Member Data Documentation
info_obj
const Type_info Champ_front_contact_VEF::info_obj static
is_conduction
int Champ_front_contact_VEF::is_conduction =0 protected
Referenced by initialiser(), Champ_front_contact_rayo_transp_VEF::mettre_a_jour_flux_radiatif(), Champ_front_contact_rayo_semi_transp_VEF::mettre_a_jour_flux_radiatif(), Champ_front_contact_rayo_transp_VEF::modifie_gradients_pour_rayonnement(), and Champ_front_contact_rayo_semi_transp_VEF::modifie_gradients_pour_rayonnement().
l_inconnue1
TRUST_Ref< Champ_Inc_base *> Champ_front_contact_VEF::l_inconnue1 protected
Referenced by calcul_coeff_amort(), calcul_grads_locaux(), creer(), Champ_front_contact_rayo_transp_VEF::inconnue1(), Champ_front_contact_rayo_semi_transp_VEF::inconnue1(), initialiser(), remplir_connect_bords(), remplir_elems_voisin_bord(), remplir_faces_coin(), and test_faces_coin().
l_inconnue2
TRUST_Ref< Champ_Inc_base *> Champ_front_contact_VEF::l_inconnue2 protected
Referenced by associer_front_vf_et_ch_front_autre_pb(), creer(), Champ_front_contact_rayo_transp_VEF::inconnue2(), Champ_front_contact_rayo_semi_transp_VEF::inconnue2(), initialiser(), and remplir_connect_bords().
l_inconnue
TRUST_Ref< Champ_Inc_base *> Champ_front_contact_VEF::l_inconnue protected
Referenced by associer_ch_inc_base(), calcul_grads_locaux(), Champ_front_contact_rayo_transp_VEF::calculer_temperature_bord(), Champ_front_contact_rayo_semi_transp_VEF::calculer_temperature_bord(), equation(), and inconnue().
fr_vf_autre_pb
TRUST_Ref< Front_VF *> Champ_front_contact_VEF::fr_vf_autre_pb protected
Referenced by associer_front_vf_et_ch_front_autre_pb(), Champ_front_contact_rayo_transp_VEF::calculer_temperature_bord(), Champ_front_contact_rayo_semi_transp_VEF::calculer_temperature_bord(), Champ_front_contact_fictif_VEF::mettre_a_jour(), mettre_a_jour(), Champ_front_contact_rayo_transp_VEF::mettre_a_jour_flux_radiatif(), Champ_front_contact_rayo_semi_transp_VEF::mettre_a_jour_flux_radiatif(), and verifier_scalaire_bord().
ch_fr_autre_pb
TRUST_Ref< Champ_front_contact_VEF *> Champ_front_contact_VEF::ch_fr_autre_pb protected
Referenced by associer_front_vf_et_ch_front_autre_pb(), Champ_front_contact_rayo_transp_VEF::calculer_temperature_bord(), Champ_front_contact_rayo_semi_transp_VEF::calculer_temperature_bord(), Champ_front_contact_fictif_VEF::mettre_a_jour(), mettre_a_jour(), Champ_front_contact_rayo_transp_VEF::mettre_a_jour_flux_radiatif(), Champ_front_contact_rayo_semi_transp_VEF::mettre_a_jour_flux_radiatif(), and verifier_scalaire_bord().
nom_bord1
Nom Champ_front_contact_VEF::nom_bord1 protected
Referenced by calcul_coeff_amort(), calcul_grads_locaux(), creer(), get_nom_bord1(), initialiser(), Champ_front_contact_fictif_VEF::mettre_a_jour(), mettre_a_jour(), Champ_front_contact_fictif_VEF::readOn(), readOn(), remplir_connect_bords(), remplir_elems_voisin_bord(), and remplir_faces_coin().
nom_bord2
Nom Champ_front_contact_VEF::nom_bord2 protected
Referenced by associer_front_vf_et_ch_front_autre_pb(), creer(), initialiser(), Champ_front_contact_fictif_VEF::mettre_a_jour(), mettre_a_jour(), Champ_front_contact_fictif_VEF::readOn(), readOn(), and remplir_connect_bords().
nom_bord
Nom Champ_front_contact_VEF::nom_bord protected
Referenced by calcul_grads_locaux(), front_dis(), initialiser(), nom_bord_oppose(), and remplir_connect_bords().
nom_pb1
Nom Champ_front_contact_VEF::nom_pb1 protected
Referenced by associer_front_vf_et_ch_front_autre_pb(), Champ_front_contact_rayo_transp_VEF::calculer_coeffs_echange(), initialiser(), Champ_front_contact_fictif_VEF::mettre_a_jour(), mettre_a_jour(), Champ_front_contact_rayo_transp_VEF::nom_prob1(), Champ_front_contact_rayo_semi_transp_VEF::nom_prob1(), Champ_front_contact_fictif_VEF::readOn(), readOn(), and remplir_connect_bords().
nom_pb2
Nom Champ_front_contact_VEF::nom_pb2 protected
Referenced by Champ_front_contact_rayo_transp_VEF::calculer_coeffs_echange(), initialiser(), Champ_front_contact_fictif_VEF::mettre_a_jour(), mettre_a_jour(), Champ_front_contact_rayo_transp_VEF::nom_prob2(), Champ_front_contact_rayo_semi_transp_VEF::nom_prob2(), Champ_front_contact_fictif_VEF::readOn(), readOn(), and remplir_connect_bords().
connect_bords
IntVect Champ_front_contact_VEF::connect_bords protected
Referenced by get_connect_bords(), remplir_connect_bords(), and trace_face_raccord().
connect_est_remplit
int Champ_front_contact_VEF::connect_est_remplit = -1 protected
Referenced by initialiser(), and readOn().
gradient_num_local
DoubleVect Champ_front_contact_VEF::gradient_num_local protected
Referenced by calcul_grads_locaux(), calcul_grads_transf(), Champ_front_contact_rayo_transp_VEF::calculer_temperature_bord(), Champ_front_contact_rayo_semi_transp_VEF::calculer_temperature_bord(), get_gradient_num_local(), initialiser(), Champ_front_contact_fictif_VEF::mettre_a_jour(), mettre_a_jour(), Champ_front_contact_rayo_transp_VEF::modifie_gradients_pour_rayonnement(), Champ_front_contact_rayo_semi_transp_VEF::modifie_gradients_pour_rayonnement(), and set_gradient_num_local().
gradient_fro_local
DoubleVect Champ_front_contact_VEF::gradient_fro_local protected
Referenced by calcul_grads_locaux(), calcul_grads_transf(), Champ_front_contact_rayo_transp_VEF::calculer_temperature_bord(), Champ_front_contact_rayo_semi_transp_VEF::calculer_temperature_bord(), get_gradient_fro_local(), initialiser(), Champ_front_contact_fictif_VEF::mettre_a_jour(), mettre_a_jour(), and set_gradient_fro_local().
gradient_num_transf
DoubleVect Champ_front_contact_VEF::gradient_num_transf protected
Referenced by calcul_grads_transf(), Champ_front_contact_rayo_transp_VEF::calculer_coeffs_echange(), Champ_front_contact_rayo_semi_transp_VEF::calculer_temperature_bord(), get_gradient_num_transf(), initialiser(), and set_gradient_num_transf().
gradient_fro_transf
DoubleVect Champ_front_contact_VEF::gradient_fro_transf protected
Referenced by calcul_grads_transf(), get_gradient_fro_transf(), initialiser(), and set_gradient_fro_transf().
Scal_moy
DoubleVect Champ_front_contact_VEF::Scal_moy protected
Referenced by calcul_grads_locaux(), initialiser(), and verifier_scalaire_bord().
coeff_amort_num
DoubleVect Champ_front_contact_VEF::coeff_amort_num protected
Referenced by calcul_coeff_amort(), Champ_front_contact_rayo_transp_VEF::calculer_temperature_bord(), Champ_front_contact_rayo_semi_transp_VEF::calculer_temperature_bord(), get_coeff_amort_num(), initialiser(), and set_coeff_amort_num().
coeff_amort_denum
DoubleVect Champ_front_contact_VEF::coeff_amort_denum protected
Referenced by calcul_coeff_amort(), Champ_front_contact_rayo_transp_VEF::calculer_temperature_bord(), Champ_front_contact_rayo_semi_transp_VEF::calculer_temperature_bord(), get_coeff_amort_denum(), initialiser(), and set_coeff_amort_denum().
elems_voisin_bord_
IntVect Champ_front_contact_VEF::elems_voisin_bord_ protected
Referenced by get_elems_voisin_bord(), remplir_elems_voisin_bord(), and remplir_faces_coin().
faces_coin
IntVect Champ_front_contact_VEF::faces_coin protected
Referenced by get_faces_coin(), and remplir_faces_coin().
verification_faces_coin
int Champ_front_contact_VEF::verification_faces_coin =0 protected
Referenced by initialiser(), and mettre_a_jour().