TrioCFD: Echange_contact_rayo_semi_transp_VDF Class Reference
Echange_contact_rayo_semi_transp_VDF Class Reference
#include <Echange_contact_rayo_semi_transp_VDF.h>
Public Member Functions
void calculer_temperature_bord (double temps)
const Type_info * get_info () const override
void mettre_a_jour (double temps) override
Public Member Functions inherited from Cond_Lim_rayo_semi_transp
virtual void associer_modele (const Modele_rayo_semi_transp &)
Modele_rayo_semi_transp & modele ()
const Modele_rayo_semi_transp & modele () const
Public Member Functions inherited from Echange_contact_VDF
const Type_info * get_info () const override
int initialiser (double temps) override
void mettre_a_jour (double) override
Public Member Functions inherited from Echange_global_impose
int compatible_avec_discr (const Discretisation_base &discr) const override
const Type_info * get_info () const override
int initialiser (double temps) override
void mettre_a_jour (double temps) override
Public Member Functions inherited from Echange_impose_base
int a_mettre_a_jour_ss_pas_dt () override
void associer_fr_dis_base (const Frontiere_dis_base &) override
double emissivite (int num) const
double emissivite (int num, int k) const
const Type_info * get_info () const override
virtual double h_imp (int num) const
virtual double h_imp (int num, int k) const
int initialiser (double temps) override
void mettre_a_jour (double) override
virtual Champ_front_base & T_ext ()
virtual double T_ext (int num) const
virtual double T_ext (int num, int k) const
Public Member Functions inherited from Cond_lim_base
virtual int a_mettre_a_jour_ss_pas_dt ()
virtual void associer_domaine_cl_dis_base (const Domaine_Cl_dis_base &)
virtual void associer_fr_dis_base (const Frontiere_dis_base &)
virtual void calculer_coeffs_echange (double temps)
virtual int compatible_avec_discr (const Discretisation_base &) const
Domaine_Cl_dis_base & domaine_Cl_dis ()
const Domaine_Cl_dis_base & domaine_Cl_dis () const
virtual Frontiere_dis_base & frontiere_dis ()
virtual const Frontiere_dis_base & frontiere_dis () const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
void set_modifier_val_imp (int)
virtual void verifie_ch_init_nb_comp () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Cond_lim_base
void err_pas_compatible (const Discretisation_base &) const
void err_pas_compatible (const Equation_base &) const
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
paroi solide et un fluide semi transparent en prenant en compte le rayonnement de la paroi. Elle est utilisee uniquement pour une discretisation VDF.
Constructor & Destructor Documentation
Echange_contact_rayo_semi_transp_VDF()
Echange_contact_rayo_semi_transp_VDF::Echange_contact_rayo_semi_transp_VDF ()
~Echange_contact_rayo_semi_transp_VDF()
Echange_contact_rayo_semi_transp_VDF::~Echange_contact_rayo_semi_transp_VDF ()
Member Function Documentation
cree_instance()
Objet_U * Echange_contact_rayo_semi_transp_VDF::cree_instance () static
taille_memoire()
unsigned Echange_contact_rayo_semi_transp_VDF::taille_memoire () const override virtual
Reimplemented from Echange_contact_VDF.
duplique()
int Echange_contact_rayo_semi_transp_VDF::duplique () const override virtual
Reimplemented from Echange_contact_VDF.
info()
const Type_info * Echange_contact_rayo_semi_transp_VDF::info () static
get_info()
const Type_info * Echange_contact_rayo_semi_transp_VDF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Echange_contact_VDF.
self_cast() [1/2]
Echange_contact_rayo_semi_transp_VDF & Echange_contact_rayo_semi_transp_VDF::self_cast (Objet_U & r) static
self_cast() [2/2]
const Echange_contact_rayo_semi_transp_VDF & Echange_contact_rayo_semi_transp_VDF::self_cast (const Objet_U & r) static
printOn()
Sortie & Echange_contact_rayo_semi_transp_VDF::printOn (Sortie & os) const override protected virtual
Parameters
(Sortie& os) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Echange_contact_VDF.
readOn()
Entree & Echange_contact_rayo_semi_transp_VDF::readOn (Entree & is) override protected virtual
Lecture et construction du champ_front_calc T_autre_Pb qui servira pour calculer les conditions d'echange a la paroi.
Lecture de l'emissivite de la paroi Lecture du coefficient A typage et dimenssionnement du champ_front T_ext() qui contient les temperatures de paroi et qui est utilise lors du calcul des flux diffusifs.
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Echange_contact_VDF.
References Echange_contact_VDF::readOn().
la_cl()
const Cond_lim_base & Echange_contact_rayo_semi_transp_VDF::la_cl () const override virtual
Implements Cond_Lim_rayo_semi_transp.
temperature_bord()
Champ_front_base & Echange_contact_rayo_semi_transp_VDF::temperature_bord ()
Renvoie le champ_front des temperatures de bord.
References Echange_impose_base::T_ext().
Referenced by Flux_radiatif_VDF::calculer_flux_radiatif(), and Eq_rayo_semi_transp_VDF::evaluer_cl_rayonnement().
calculer_temperature_bord()
void Echange_contact_rayo_semi_transp_VDF::calculer_temperature_bord (double temps)
la methode mettre_a_jour(temps) a pour role de remplire le tableau T_ext avec les temperatures de paroi.
Ces temperatures de paroi sont utilisees pour imposer la condition a la limite du probleme de rayonnement. Les temperatures de paroi sont calculees en tenant compte du caractere rayonnant de la paroi.
References Champ_front_base::associer_fr_dis_base(), Echange_contact_VDF::autre_h, Echange_contact_VDF::calculer_h_autre_pb(), Echange_contact_VDF::calculer_h_mon_pb(), calculer_Teta_paroi(), Domaine_dis_base::domaine(), Cond_lim_base::domaine_Cl_dis(), Domaine_Cl_dis_base::domaine_dis(), Frontiere_dis_base::frontiere(), Cond_lim_base::frontiere_dis(), Echange_impose_base::h_imp_, Echange_contact_VDF::h_paroi, Frontiere_32_64< _SIZE_ >::le_nom(), Objet_U::que_suis_je(), Domaine_32_64< _SIZE_ >::raccord(), Echange_contact_VDF::T_autre_pb(), Echange_impose_base::T_ext(), T_paroi, Champ_front_base::valeurs(), Champ_front_base::valeurs_au_temps(), and Echange_contact_VDF::verifier_correspondance().
Referenced by Eq_rayo_semi_transp_VDF::evaluer_cl_rayonnement().
compatible_avec_eqn()
int Echange_contact_rayo_semi_transp_VDF::compatible_avec_eqn (const Equation_base & eqn) const override virtual
Reimplemented from Cond_lim_base.
References Equation_base::domaine_application(), and Cond_lim_base::err_pas_compatible().
mettre_a_jour()
void Echange_contact_rayo_semi_transp_VDF::mettre_a_jour (double temps) override virtual
la methode mettre_a_jour(temps) a pour role de remplire le tableau T_ext avec les temperatures de paroi.
T_ext sera utilise pour calculer le flux impose a la limite de chaque domaine du probleme couple. Les temperatures de paroi sont calculees en tenant compte du caractere rayonnant de la paroi. Appel de la methode Echange_externe_impose::mettre_a_jour(temps);
Parameters
(double temps) temps courant
Reimplemented from Echange_contact_VDF.
References Champ_front_base::associer_fr_dis_base(), Echange_contact_VDF::autre_h, Echange_contact_VDF::calculer_h_autre_pb(), Echange_contact_VDF::calculer_h_mon_pb(), calculer_Teta_equiv(), Milieu_base::conductivite(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Domaine_dis_base::domaine(), Cond_lim_base::domaine_Cl_dis(), Domaine_Cl_dis_base::domaine_dis(), Equation_base::domaine_dis(), MorEqn::equation(), Process::exit(), Frontiere_dis_base::frontiere(), Cond_lim_base::frontiere_dis(), Domaine_dis_base::frontiere_dis(), Echange_impose_base::h_imp_, Echange_contact_VDF::h_paroi, Champ_front_calc::inconnue(), Milieu_base::is_rayo_semi_transp(), Objet_U::le_nom(), Frontiere_32_64< _SIZE_ >::le_nom(), Champ_front_base::mettre_a_jour(), Echange_global_impose::mettre_a_jour(), Champ_front_calc::milieu(), Probleme_base::milieu(), Field_base::nb_comp(), Front_VF::num_premiere_face(), num_premiere_face_dans_pb_fluide, Equation_base::probleme(), Objet_U::que_suis_je(), Domaine_32_64< _SIZE_ >::raccord(), Echange_contact_VDF::T_autre_pb(), Echange_impose_base::T_ext(), Champ_front_base::valeurs(), and Echange_contact_VDF::verifier_correspondance().
completer()
void Echange_contact_rayo_semi_transp_VDF::completer () override virtual
NE FAIT RIEN A surcharger dans les classes derivees.
Reimplemented from Echange_contact_VDF.
References Echange_contact_VDF::completer(), Field_base::fixer_nb_comp(), T_paroi, and Objet_U_ptr::typer().
calculer_Teta_paroi()
void Echange_contact_rayo_semi_transp_VDF::calculer_Teta_paroi (DoubleTab & tab_p, const DoubleTab & mon_h, const DoubleTab & autre_h, int is_pb_fluide, double temps) override virtual
remplit Teta_p utilise T_autre_pb au temps passe en parametre
Reimplemented from Echange_contact_VDF.
References Cond_lim_base::domaine_Cl_dis(), MorEqn::equation(), Process::exit(), Domaine_VF::face_voisins(), Modele_rayo_semi_transp::flux_radiatif(), Cond_lim_base::frontiere_dis(), Equation_base::inconnue(), Objet_U::le_nom(), Cond_Lim_rayo_semi_transp::modele(), Cond_lim_base::mon_dom_cl_dis, Front_VF::nb_faces(), Front_VF::num_premiere_face(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Echange_contact_VDF::T_autre_pb(), Champ_front_base::valeurs(), Champ_Inc_base::valeurs(), and Champ_front_base::valeurs_au_temps().
Referenced by calculer_temperature_bord().
calculer_Teta_equiv()
void Echange_contact_rayo_semi_transp_VDF::calculer_Teta_equiv (DoubleTab & Teta_equiv, const DoubleTab & mon_h, const DoubleTab & autre_h, int is_pb_fluide, double temps) override virtual
remplit Teta_eq utilise T_autre_pb au temps passe en parametre
Reimplemented from Echange_contact_VDF.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Modele_rayo_semi_transp::flux_radiatif(), Cond_lim_base::frontiere_dis(), Objet_U::le_nom(), Cond_Lim_rayo_semi_transp::modele(), Front_VF::nb_faces(), Echange_contact_VDF::T_autre_pb(), Champ_front_base::valeurs(), and Champ_front_base::valeurs_au_temps().
Referenced by mettre_a_jour().
la_Cl_opposee()
Echange_contact_rayo_semi_transp_VDF & Echange_contact_rayo_semi_transp_VDF::la_Cl_opposee ()
Renvoie la CL portee par le probleme de l'autre cote de la frontiere.
References Champ_front_calc::domaine_Cl_dis(), Process::exit(), Cond_lim_base::frontiere_dis(), Objet_U::le_nom(), Objet_U_ptr::le_nom(), Domaine_Cl_dis_base::les_conditions_limites(), Domaine_Cl_dis_base::nb_cond_lim(), Echange_contact_VDF::T_autre_pb(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by Modele_rayo_semi_transp::preparer_calcul().
Member Data Documentation
info_obj
const Type_info Echange_contact_rayo_semi_transp_VDF::info_obj static
T_paroi
TRUST_Deriv< Champ_front_base > Echange_contact_rayo_semi_transp_VDF::T_paroi protected
Referenced by calculer_temperature_bord(), and completer().
num_premiere_face_dans_pb_fluide
int Echange_contact_rayo_semi_transp_VDF::num_premiere_face_dans_pb_fluide protected
Referenced by mettre_a_jour().