TrioCFD: Champ_Face_base Class Reference
Champ_Face_base Class Reference abstract
#include <Champ_Face_base.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Champ_Inc_base
Champ_base & affecter_ (const Champ_base &) override
Champ_base & affecter_compo (const Champ_base &, int compo) override
virtual void associer_eqn (const Equation_base &)
Champ_Inc_base & avancer (int i=1)
double changer_temps (const double temps) override
double changer_temps_futur (double, int i=1)
double changer_temps_passe (double, int i=1)
virtual int fixer_nb_valeurs_temporelles (int)
DoubleTab & futur (int i=1) override
const Type_info * get_info () const override
int lire_donnees (Entree &)
void mettre_a_jour (double temps) override
virtual int nb_valeurs_temporelles () const
DoubleTab & passe (int i=1) override
Champ_Inc_base & reculer (int i=1)
double recuperer_temps_futur (int i=1) const
double recuperer_temps_passe (int i=1) const
virtual DoubleTab & remplir_coord_noeuds_compo (DoubleTab &, int) const
virtual int remplir_coord_noeuds_et_polys (DoubleTab &, IntVect &) const
virtual int remplir_coord_noeuds_et_polys_compo (DoubleTab &, IntVect &, int) const
int reprendre (Entree &) override
void resetTime (double time) override
int sauvegarder (Sortie &) const override
DoubleTab & trace (const Frontiere_dis_base &, DoubleTab &, double, int distant) const override
DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const override
DoubleTab & valeur_aux (const DoubleTab &positions, DoubleTab &valeurs) const override
DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const override
DoubleTab & valeurs () override
const DoubleTab & valeurs (double temps) const override
DoubleTab & valeurs (double temps) override
Public Member Functions inherited from Champ_base
Champ_base & affecter (const Champ_base &)
Champ_base ()
virtual double changer_temps (const double t)
const Type_info * get_info () const override
double temps () const
virtual DoubleTab & trace (const Frontiere_dis_base &, DoubleTab &, double, int distant) const
virtual DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const
virtual double valeur_a_compo (const DoubleVect &position, int ncomp) const
virtual DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &valeurs, int le_poly) const
virtual double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const
virtual DoubleVect & valeur_a_sommet (int, const Domaine &, DoubleVect &) const
virtual DoubleTab & valeur_aux (const DoubleTab &positions, DoubleTab &valeurs) const
virtual DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const
virtual DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const
virtual DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp) const
Public Member Functions inherited from Field_base
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
virtual void fixer_nb_comp (int i)
virtual const Nom & fixer_nom_compo (const Nom &)
virtual const Nom & fixer_nom_compo (int, const Nom &)
virtual const Noms & fixer_noms_compo (const Noms &)
virtual const Nom & fixer_unite (const Nom &)
virtual const Nom & fixer_unite (int i, const Nom &)
virtual const Noms & fixer_unites (const Noms &)
const Type_info * get_info () const override
const Nom & nom_compo (int) const
void nommer (const Nom &) override
const Nom & unite () const
const Nom & unite (int) const
const Noms & unites () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Champ_Proto
int lire_dimension (Entree &, const Nom &)
int lire_dimension (int dim, const Nom &le_nom_)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Champ_Inc_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Field_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Champ_Face_base()
Champ_Face_base::Champ_Face_base ()
~Champ_Face_base()
Champ_Face_base::~Champ_Face_base () override
Member Function Documentation
info()
const Type_info * Champ_Face_base::info () static
get_info()
const Type_info * Champ_Face_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Champ_base.
Reimplemented in Champ_Face_PolyMAC, Champ_Face_PolyMAC_P0, Champ_Face_PolyMAC_P0P1NC, and Champ_Face_VDF.
self_cast() [1/2]
Champ_Face_base & Champ_Face_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Champ_Face_base & Champ_Face_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Champ_Face_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Champ_base.
Reimplemented in Champ_Face_PolyMAC, Champ_Face_PolyMAC_P0, Champ_Face_PolyMAC_P0P1NC, and Champ_Face_VDF.
readOn()
Entree & Champ_Face_base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Champ_base.
Reimplemented in Champ_Face_PolyMAC, Champ_Face_PolyMAC_P0, Champ_Face_PolyMAC_P0P1NC, and Champ_Face_VDF.
fcl()
const IntTab & Champ_Face_base::fcl () const inline
References fcl_, fcl_init_, and init_fcl().
Referenced by Op_Conv_EF_Stab_PolyMAC_Face::ajouter(), Op_Diff_PolyMAC_Face::ajouter(), Perte_Charge_PolyMAC::ajouter(), Op_Conv_EF_Stab_PolyMAC_P0_Face::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Face::ajouter_blocs(), Op_Diff_PolyMAC_P0_Face::ajouter_blocs(), Op_Grad_PolyMAC_P0_Face::ajouter_blocs(), Injection_QDM_nulle_PolyMAC_P0::ajouter_blocs(), Injection_QDM_nulle_VDF::ajouter_blocs(), Correction_Antal_PolyMAC_P0::ajouter_blocs(), Correction_Tomiyama_PolyMAC_P0::ajouter_blocs(), Dispersion_bulles_PolyMAC_P0::ajouter_blocs(), Frottement_interfacial_PolyMAC_P0::ajouter_blocs(), Portance_interfaciale_PolyMAC_P0::ajouter_blocs(), Perte_Charge_PolyMAC::ajouter_blocs(), Terme_Source_Qdm_Face_PolyMAC_P0P1NC::ajouter_blocs(), Op_Evanescence_Homogene_Face_base::ajouter_blocs(), Source_Force_Tchen_base::ajouter_blocs(), Correction_Antal_VDF::ajouter_blocs(), Dispersion_bulles_VDF::ajouter_blocs(), Frottement_interfacial_VDF::ajouter_blocs(), Portance_interfaciale_VDF::ajouter_blocs(), Op_Conv_Amont_VPoly_VDF_Face::ajouter_blocs(), Perte_Charge_VDF_base::ajouter_blocs(), Correction_Lubchenko_PolyMAC_P0::ajouter_blocs_disp(), Op_Div_PolyMAC_P0P1NC::ajouter_blocs_ext(), Op_Diff_PolyMAC_P0P1NC_Face::ajouter_blocs_ext(), Correction_Lubchenko_PolyMAC_P0::ajouter_blocs_lift(), Masse_PolyMAC_Face::ajouter_masse(), Masse_PolyMAC_Face::appliquer_impl(), Assembleur_P_PolyMAC::assembler_mat(), Assembleur_P_PolyMAC_P0P1NC::assembler_mat(), grad_Champ_Face_PolyMAC_P0::calc_gradfve(), Op_Conv_EF_Stab_PolyMAC_P0_Face::calculer_dt_stab(), Op_Conv_EF_Stab_PolyMAC_Face::contribuer_a_avec(), Op_Diff_PolyMAC_Face::contribuer_a_avec(), Perte_Charge_PolyMAC::contribuer_a_avec(), Op_Conv_EF_Stab_PolyMAC_Face::dimensionner(), Op_Diff_PolyMAC_Face::dimensionner(), Masse_PolyMAC_Face::dimensionner(), Op_Conv_EF_Stab_PolyMAC_P0_Face::dimensionner_blocs(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Face::dimensionner_blocs(), Op_Diff_PolyMAC_P0_Face::dimensionner_blocs(), Op_Div_PolyMAC_P0P1NC::dimensionner_blocs(), Op_Grad_PolyMAC_P0_Face::dimensionner_blocs(), Op_Grad_PolyMAC_P0P1NC_Face::dimensionner_blocs(), Op_Evanescence_Homogene_Face_base::dimensionner_blocs(), Source_Force_Tchen_base::dimensionner_blocs(), Source_Frottement_interfacial_base::dimensionner_blocs(), Op_Diff_PolyMAC_P0P1NC_Face::dimensionner_blocs_ext(), Op_Conv_VDF_base::dimensionner_blocs_face(), Assembleur_P_PolyMAC_P0P1NC::modifier_secmem_pour_incr_p(), Op_Grad_PolyMAC_P0_Face::update_grad(), grad_Champ_Face_PolyMAC_P0::update_tab_grad(), and Champ_Face_PolyMAC::valeur_aux_elems_compo().
get_elem_vector_field()
DoubleTab & Champ_Face_base::get_elem_vector_field (DoubleTab & val_vec, bool passe = false) const virtual
References Champ_Inc_base::domaine(), Champ_Inc_base::le_dom_VF, Domaine_32_64< _SIZE_ >::nb_elem_tot(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_base::valeur_aux_elems(), and valeur_aux_elems_passe().
Referenced by Coalescence_bulles_1groupe_PolyMAC_P0::ajouter_blocs(), Coalescence_bulles_2groupes_PolyMAC_P0::ajouter_blocs(), Flux_2groupes_PolyMAC_P0::ajouter_blocs(), Rupture_bulles_1groupe_PolyMAC_P0::ajouter_blocs(), Rupture_bulles_2groupes_PolyMAC_P0::ajouter_blocs(), Correction_Antal_VDF::ajouter_blocs(), Dispersion_bulles_VDF::ajouter_blocs(), Frottement_interfacial_VDF::ajouter_blocs(), Portance_interfaciale_VDF::ajouter_blocs(), Loi_paroi_adaptative::calc_y_plus(), Loi_paroi_Ramstorfer::calc_y_plus(), Loi_paroi_log::calc_y_plus(), and Paroi_frottante_simple::me_calculer().
get_elem_vector()
DoubleVect & Champ_Face_base::get_elem_vector (const int num_elem, DoubleVect & val_vec) const virtual
References Champ_Inc_base::domaine(), Champ_Inc_base::le_dom_VF, TRUST_Ref< _CLASSE_ >::valeur(), and Champ_base::valeur_a_elem().
init_fcl()
void Champ_Face_base::init_fcl () const protected
References Champ_Inc_base::domaine(), Champ_Inc_base::domaine_Cl_dis(), Process::exit(), fcl_, fcl_init_, Champ_Inc_base::le_dom_VF, Domaine_Cl_dis_base::les_conditions_limites(), Front_VF::nb_faces_tot(), Front_VF::num_face(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUST_Vector< _CLASSE_ >::size(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by fcl(), Champ_Face_PolyMAC::init_ra(), Champ_Face_PolyMAC_P0::init_ve2(), Champ_Face_PolyMAC::trace(), and Champ_Face_PolyMAC_P0::update_ve2().
valeur_aux_elems_passe()
virtual DoubleTab & Champ_Face_base::valeur_aux_elems_passe (const DoubleTab & positions, const IntVect & les_polys, DoubleTab & tab_valeurs) const protected pure virtual
Implemented in Champ_Face_VDF, Champ_Face_PolyMAC, and Champ_Face_PolyMAC_P0.
Referenced by get_elem_vector_field().
Member Data Documentation
info_obj
const Type_info Champ_Face_base::info_obj static
fcl_
IntTab Champ_Face_base::fcl_ mutable protected
Referenced by fcl(), init_fcl(), Champ_Face_PolyMAC::init_ra(), Champ_Face_PolyMAC::init_va(), Champ_Face_PolyMAC_P0::init_ve2(), Champ_Face_PolyMAC::interp_gve(), Champ_Face_PolyMAC::interp_ve(), and Champ_Face_PolyMAC_P0::update_ve2().
fcl_init_
int Champ_Face_base::fcl_init_ = 0 mutable protected
Referenced by fcl(), and init_fcl().