TrioCFD: AssembleurPVDF_PF Class Reference
AssembleurPVDF_PF Class Reference
#include <AssembleurPVDF_PF.h>
Public Member Functions
int assembler (Matrice &) override
int assembler_QC (const DoubleTab &, Matrice &) override
int assembler_rho_variable (Matrice &, const Champ_Don_base &rho) override
const Type_info * get_info () const override
int modifier_secmem (DoubleTab &) override
int assembler (Matrice &) override
int assembler_QC (const DoubleTab &, Matrice &) override
int assembler_rho_variable (Matrice &, const Champ_Don_base &rho) override
const Type_info * get_info () const override
int modifier_secmem (DoubleTab &) override
Public Member Functions inherited from Assembleur_base
virtual int assembler_rho_variable (Matrice &, const Champ_Don_base &rho)
const Type_info * get_info () const override
int set_resoudre_en_u (int flag)
int set_resoudre_increment_pression (int flag)
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
int construire (Matrice &la_matrice)
int liste_faces_periodiques (ArrOfInt &faces)
void modifier_secmem_pression_imposee (const Neumann_sortie_libre &cond_lim, const Front_VF &frontiere_vf, DoubleTab &secmem)
void modifier_secmem_vitesse_imposee (const Entree_fluide_vitesse_imposee &cond_lim, const Front_VF &frontiere_vf, DoubleTab &secmem)
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
int remplir (Matrice &la_matrice, const Champ_Don_base *rho_ptr)
Protected Member Functions inherited from Assembleur_P_VDF
int construire (Matrice &la_matrice)
int liste_faces_periodiques (ArrOfInt &faces)
void modifier_secmem_pression_imposee (const Neumann_sortie_libre &cond_lim, const Front_VF &frontiere_vf, DoubleTab &secmem)
void modifier_secmem_vitesse_imposee (const Entree_fluide_vitesse_imposee &cond_lim, const Front_VF &frontiere_vf, DoubleTab &secmem)
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
int remplir (Matrice &la_matrice, const DoubleVect &volumes_entrelaces, const Champ_Don_base *rho_ptr)
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
AssembleurPVDF_PF()
AssembleurPVDF_PF::AssembleurPVDF_PF ()
~AssembleurPVDF_PF()
AssembleurPVDF_PF::~AssembleurPVDF_PF ()
Member Function Documentation
cree_instance()
Objet_U * AssembleurPVDF_PF::cree_instance () static
taille_memoire()
unsigned AssembleurPVDF_PF::taille_memoire () const override virtual
Reimplemented from Assembleur_P_VDF.
duplique()
int AssembleurPVDF_PF::duplique () const override virtual
Reimplemented from Assembleur_P_VDF.
info()
const Type_info * AssembleurPVDF_PF::info () static
get_info()
const Type_info * AssembleurPVDF_PF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Assembleur_P_VDF.
self_cast() [1/2]
AssembleurPVDF_PF & AssembleurPVDF_PF::self_cast (Objet_U & r) static
self_cast() [2/2]
const AssembleurPVDF_PF & AssembleurPVDF_PF::self_cast (const Objet_U & r) static
printOn()
Sortie & AssembleurPVDF_PF::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Assembleur_P_VDF.
References Objet_U::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & AssembleurPVDF_PF::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Assembleur_P_VDF.
References Assembleur_P_VDF::readOn().
associer_domaine_dis_base()
void AssembleurPVDF_PF::associer_domaine_dis_base (const Domaine_dis_base & le_dom_dis) override virtual
Reimplemented from Assembleur_P_VDF.
References le_dom_VDF.
associer_domaine_cl_dis_base()
void AssembleurPVDF_PF::associer_domaine_cl_dis_base (const Domaine_Cl_dis_base & le_dom_Cl_dis) override virtual
Reimplemented from Assembleur_P_VDF.
References le_dom_Cl_VDF.
domaine_dis_base()
const Domaine_dis_base & AssembleurPVDF_PF::domaine_dis_base () const override virtual
Reimplemented from Assembleur_P_VDF.
References le_dom_VDF, and TRUST_Ref< _CLASSE_ >::valeur().
domaine_Cl_dis_base()
const Domaine_Cl_dis_base & AssembleurPVDF_PF::domaine_Cl_dis_base () const override virtual
Reimplemented from Assembleur_P_VDF.
References le_dom_Cl_VDF, and TRUST_Ref< _CLASSE_ >::valeur().
assembler()
int AssembleurPVDF_PF::assembler (Matrice & matrice) override virtual
Assemblage de la matrice de pression M telle que M*P = div(porosite * grad (P))
et calcul des coefficients pour modifier_secmem.
Reimplemented from Assembleur_P_VDF.
References construire(), remplir(), and Assembleur_base::set_resoudre_increment_pression().
assembler_rho_variable()
int AssembleurPVDF_PF::assembler_rho_variable (Matrice & matrice, const Champ_Don_base & rho) override virtual
Assemblage de la matrice de pression M telle que M*P = div(porosite/rho * grad (P))
et calcul des coefficients pour modifier_secmem.
Parameters
(matrice) La matrice a assembler. Contrainte: Soit la matrice n'est pas encore typee (alors on la "construit"), soit c'est la meme que lors de l'appel precedent.
(rho)
Reimplemented from Assembleur_P_VDF.
References construire(), Assembleur_base::get_resoudre_increment_pression(), Process::je_suis_maitre(), Objet_U_ptr::non_nul(), and remplir().
assembler_QC()
int AssembleurPVDF_PF::assembler_QC (const DoubleTab & tab_rho, Matrice & matrice) override virtual
Assemble la matrice de pression pour un fluide quasi compressible.
La matrice M est telle que M*P = div(porosite * grad(P)). Le drapeau resoudre_increment_pression est mis a zero s'il n'a pas encore ete assigne.
Parameters
(DoubleTab& tab_rho) mass volumique
Returns
(int) renvoie toujours 1
Reimplemented from Assembleur_P_VDF.
References construire(), Process::exit(), Matrice_Bloc::get_bloc(), Matrice_Sym::get_est_definie(), Assembleur_base::get_resoudre_increment_pression(), Process::je_suis_maitre(), Matrice_Morse::nb_colonnes(), Matrice_Morse::nb_lignes(), Objet_U_ptr::non_nul(), remplir(), Matrice_Sym::set_est_definie(), Assembleur_base::set_resoudre_increment_pression(), and TRUST_Deriv< _CLASSE_ >::valeur().
modifier_secmem()
int AssembleurPVDF_PF::modifier_secmem (DoubleTab & secmem) override virtual
Modification du second membre pour appliquer les conditions aux limites.
Les conditions prises en charge sont Neumann_sortie_libre, Entree_fluide_vitesse_imposee, Dirichlet_paroi_defilante (rien a faire), Dirichlet_paroi_fixe (rien a faire), Symetrie (rien a faire)
Reimplemented from Assembleur_P_VDF.
References TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Process::exit(), Cond_lim_base::frontiere_dis(), le_dom_Cl_VDF, Domaine_Cl_dis_base::les_conditions_limites(), modifier_secmem_pression_imposee(), modifier_secmem_vitesse_imposee(), Domaine_Cl_dis_base::nb_cond_lim(), Objet_U::que_suis_je(), TRUST_Deriv< _CLASSE_ >::valeur(), and TRUST_Ref< _CLASSE_ >::valeur().
modifier_solution()
int AssembleurPVDF_PF::modifier_solution (DoubleTab & pression) override virtual
Reimplemented from Assembleur_P_VDF.
References has_P_ref, and le_dom_VDF.
completer()
void AssembleurPVDF_PF::completer (const Equation_base & Eqn) override virtual
Reimplemented from Assembleur_P_VDF.
construire()
int AssembleurPVDF_PF::construire (Matrice & la_matrice) protected
Determine les elements non nuls de la matrice et prepare le stockage.
Matrice creuse de taille nb_elements (lignes) * nb_elem_tot (colonnes) Codee comme une matrice bloc composee de deux matrices morse:
Matrice carree symetrique nb_elements * nb_elements (contient les termes M(i,j) ou i et j sont des numeros d'elements reels)
Matrice rectangle nb_elements * (nb_elem_tot - nb_elem) (contient les termes M(i,j) ou i est reel et j est virtuel
References Matrice_Bloc::dimensionner(), Matrice_Morse::dimensionner(), Domaine_VF::face_voisins(), Matrice_Bloc::get_bloc(), Matrice_Morse::get_set_tab1(), Matrice_Morse::get_set_tab2(), le_dom_VDF, les_coeff_pression, liste_faces_periodiques(), Domaine_dis_base::nb_elem(), Domaine_dis_base::nb_elem_tot(), Domaine_VF::nb_faces_bord(), Domaine_VF::nb_faces_internes(), Domaine_VF::premiere_face_int(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), Objet_U_ptr::typer(), TRUST_Deriv< _CLASSE_ >::valeur(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by assembler(), assembler_QC(), and assembler_rho_variable().
remplir()
int AssembleurPVDF_PF::remplir (Matrice & la_matrice, const Champ_Don_base * rho_ptr) protected
Calcul des coefficients de la matrice de pression avec un champ de rho.
Si rho_ptr == 0, on calcule la matrice -div(porosite * grad P), sinon on calcule -div(porosite/rho grad P) et *rho_ptr doit etre un Champ_Fonc_Face.
References Domaine_VF::face_surfaces(), Domaine_VF::face_voisins(), Cond_lim_base::frontiere_dis(), Matrice_Bloc::get_bloc(), Matrice_Morse::get_set_coeff(), Matrice_Morse::get_set_tab1(), Matrice_Morse::get_set_tab2(), has_P_ref, le_dom_Cl_VDF, le_dom_VDF, les_coeff_pression, liste_faces_periodiques(), Domaine_dis_base::nb_elem(), Front_VF::nb_faces(), Domaine_VF::nb_faces_internes(), Front_VF::num_premiere_face(), Domaine_VF::premiere_face_int(), TRUST_Vector< _CLASSE_ >::size(), TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), and Domaine_VF::volumes_entrelaces().
Referenced by assembler(), assembler_QC(), and assembler_rho_variable().
modifier_secmem_pression_imposee()
void AssembleurPVDF_PF::modifier_secmem_pression_imposee (const Neumann_sortie_libre & cond_lim, const Front_VF & frontiere_vf, DoubleTab & secmem) protected
Modification du second membre du solveur en pression pour une condition "Neumann_sortie_libre".
Calcul en "increment de pression" : ajouter l'increment de pression, c'est a dire zero (c.l. instationnaire non supportee) Calcul en "pression" : Ajout du terme Pimpose * surface / volume_entrelace au second membre dans la discretisation de la pression au bord (entre un element elem0 et un element fictif exterieur a pression imposee) : grad P = (P(elem0) - Pimpose) * surface / volume_entrelace
References Cond_lim_base::champ_front(), Process::exit(), Domaine_VF::face_voisins(), Neumann::flux_impose(), Assembleur_base::get_resoudre_increment_pression(), le_dom_VDF, les_coeff_pression, Front_VF::nb_faces(), Front_VF::num_premiere_face(), Objet_U::que_suis_je(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by modifier_secmem().
modifier_secmem_vitesse_imposee()
void AssembleurPVDF_PF::modifier_secmem_vitesse_imposee (const Entree_fluide_vitesse_imposee & cond_lim, const Front_VF & frontiere_vf, DoubleTab & secmem) protected
Modification du second membre du systeme en pression pour une condition aux limites de vitesse imposee.
Si on resout en increment de pression, ... sinon rien a faire.
References Cond_lim_base::champ_front(), Champ_front_base::derivee_en_temps(), Domaine_VF::face_surfaces(), Domaine_VF::face_voisins(), Assembleur_base::get_resoudre_increment_pression(), Champ_front_base::instationnaire(), le_dom_VDF, TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), Domaine_VDF::orientation(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by modifier_secmem().
liste_faces_periodiques()
int AssembleurPVDF_PF::liste_faces_periodiques (ArrOfInt & faces) protected
Remplit le tableau faces avec la liste des indices des faces periodiques dans le tableau faces_voisins.
Chaque face periodique figure deux fois dans faces_voisins (a chaque face correspond la face opposee). On ne met dans le tableau faces que celle des deux qui a l'indice le + petit dans la liste des faces de chaque bord periodique. Valeur de retour: nombre de faces periodiques (egal a la taille du tableau faces).
References Periodique::face_associee(), Cond_lim_base::frontiere_dis(), le_dom_Cl_VDF, le_dom_VDF, Front_VF::nb_faces(), Front_VF::num_premiere_face(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), and TRUST_Vector< _CLASSE_ >::size().
Referenced by construire(), and remplir().
Member Data Documentation
info_obj
const Type_info AssembleurPVDF_PF::info_obj static
le_dom_VDF
TRUST_Ref< Domaine_VDF *> AssembleurPVDF_PF::le_dom_VDF protected
Referenced by associer_domaine_dis_base(), construire(), domaine_dis_base(), liste_faces_periodiques(), modifier_secmem_pression_imposee(), modifier_secmem_vitesse_imposee(), modifier_solution(), and remplir().
le_dom_Cl_VDF
TRUST_Ref< Domaine_Cl_VDF *> AssembleurPVDF_PF::le_dom_Cl_VDF protected
Referenced by associer_domaine_cl_dis_base(), domaine_Cl_dis_base(), liste_faces_periodiques(), modifier_secmem(), and remplir().
les_coeff_pression
ArrOfDouble AssembleurPVDF_PF::les_coeff_pression protected
Referenced by construire(), modifier_secmem_pression_imposee(), and remplir().
has_P_ref
int AssembleurPVDF_PF::has_P_ref protected
Referenced by modifier_solution(), and remplir().