TrioCFD: FixedVector< T, N > Class Template Reference
FixedVector< T, N > Class Template Reference
#include <FixedVector.h>
Constructor & Destructor Documentation
FixedVector() [1/2]
template<class T , int N> FixedVector< T, N >::FixedVector () inline
FixedVector() [2/2]
template<class T , int N> FixedVector< T, N >::FixedVector (int i, int j, int k) inline
Member Function Documentation
size()
template<class T , int N> static int FixedVector< T, N >::size () inline static
operator[]() [1/2]
template<class T , int N> T & FixedVector< T, N >::operator[] (int i) inline
operator[]() [2/2]
template<class T , int N> const T & FixedVector< T, N >::operator[] (int i) const inline
echange_espace_virtuel()
template<class T , int N> void FixedVector< T, N >::echange_espace_virtuel () inline
References FixedVector< T, N >::data_, and FixedVector< T, N >::echange_espace_virtuel().
Referenced by IJK_Interfaces::calculer_indicatrice_next(), ComputeValParCompoInCell::calculer_moy_field_fa7_par_compo(), ComputeValParCompoInCell::calculer_moy_field_sommet_par_compo(), ComputeValParCompoInCell::calculer_moy_par_compo(), ComputeValParCompoInCell::calculer_somme_field_sommet_par_compo(), FixedVector< T, N >::echange_espace_virtuel(), and IJK_Interfaces::switch_indicatrice_next_old().
get_domaine()
template<class T , int N> const Domaine_IJK & FixedVector< T, N >::get_domaine () const inline
References FixedVector< T, N >::data_.
Member Data Documentation
data_
template<class T , int N> T FixedVector< T, N >::data_[N] protected
Referenced by FixedVector< T, N >::echange_espace_virtuel(), and FixedVector< T, N >::get_domaine().