TrioCFD: Champ_Generique_Reduction_0D Class Reference
Champ_Generique_Reduction_0D Class Reference
#include <Champ_Generique_Reduction_0D.h>
Public Member Functions
const Champ_base & get_champ (TRUST_Deriv< Champ_base > &espace_stockage) const override
const Type_info * get_info () const override
const Noms get_property (const Motcle &query) const override
Public Member Functions inherited from Champ_Gen_de_Champs_Gen
void get_copy_domain (Domaine &) const override
void get_copy_values (DoubleTab &) const override
int get_dimension () const override
const Type_info * get_info () const override
Entity get_localisation (const int index=-1) const override
const Noms get_property (const Motcle &query) const override
const IntTab & get_ref_connectivity (Entity index1, Entity index2) const override
const DoubleTab & get_ref_coordinates () const override
const Domaine & get_ref_domain () const override
const Domaine_dis_base & get_ref_domaine_dis_base () const override
const DoubleTab & get_ref_values () const override
void get_xyz_values (const DoubleTab &coords, DoubleTab &values, ArrOfBit &validity_flag) const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
Public Member Functions inherited from Champ_Generique_base
virtual void get_copy_domain (Domaine &) const
virtual void get_copy_values (DoubleTab &) const
virtual int get_dimension () const
const Type_info * get_info () const override
virtual Entity get_localisation (const int index=-1) const
virtual const Noms get_property (const Motcle &query) const
virtual const IntTab & get_ref_connectivity (Entity index1, Entity index2) const
virtual const DoubleTab & get_ref_coordinates () const
virtual const Domaine & get_ref_domain () const
virtual const Domaine_dis_base & get_ref_domaine_dis_base () const
virtual const DoubleTab & get_ref_values () const
virtual void get_xyz_values (const DoubleTab &coords, DoubleTab &values, ArrOfBit &validity_flag) const
int lire_motcle_non_standard (const Motcle &, Entree &) override
void nommer (const Nom &nom) override
int reprendre (Entree &is) override
int sauvegarder (Sortie &os) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Champ_Generique_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Champ_Generique_Reduction_0D()
Champ_Generique_Reduction_0D::Champ_Generique_Reduction_0D ()
~Champ_Generique_Reduction_0D()
Champ_Generique_Reduction_0D::~Champ_Generique_Reduction_0D ()
Member Function Documentation
cree_instance()
Objet_U * Champ_Generique_Reduction_0D::cree_instance () static
taille_memoire()
unsigned Champ_Generique_Reduction_0D::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Champ_Generique_Reduction_0D::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Champ_Generique_Reduction_0D::info () static
get_info()
const Type_info * Champ_Generique_Reduction_0D::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Champ_Gen_de_Champs_Gen.
self_cast() [1/2]
Champ_Generique_Reduction_0D & Champ_Generique_Reduction_0D::self_cast (Objet_U & r) static
self_cast() [2/2]
const Champ_Generique_Reduction_0D & Champ_Generique_Reduction_0D::self_cast (const Objet_U & r) static
printOn()
Sortie & Champ_Generique_Reduction_0D::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Champ_Gen_de_Champs_Gen.
References Objet_U::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Champ_Generique_Reduction_0D::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Champ_Gen_de_Champs_Gen.
References Process::exit(), methode_, Objet_U::que_suis_je(), and Champ_Gen_de_Champs_Gen::readOn().
set_param()
void Champ_Generique_Reduction_0D::set_param (Param & param) override virtual
Reimplemented from Champ_Gen_de_Champs_Gen.
References Param::ajouter(), methode_, Param::REQUIRED, and Champ_Gen_de_Champs_Gen::set_param().
completer()
void Champ_Generique_Reduction_0D::completer (const Postraitement_base & post) override virtual
Reimplemented from Champ_Gen_de_Champs_Gen.
References Champ_Gen_de_Champs_Gen::completer(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Domaine_dis_base::domaine(), Process::exit(), Champ_Gen_de_Champs_Gen::get_directive_pour_discr(), Champ_Generique_base::get_property(), get_property(), Champ_Generique_base::get_ref_domaine_dis_base(), Champ_Gen_de_Champs_Gen::get_source(), Process::je_suis_maitre(), Process::Journal(), Domaine_32_64< _SIZE_ >::les_elems(), Domaine_32_64< _SIZE_ >::les_sommets(), Process::me(), methode_, Process::mp_min(), Process::nproc(), numero_elem_, numero_proc_, and Objet_U::que_suis_je().
get_property()
const Noms Champ_Generique_Reduction_0D::get_property (const Motcle & query) const override virtual
Renvoie la propriete demandee.
Exemples: "DISCRETISATION" : type du champ discret (P0, P1, P1NC, etc...) "ELEMENT_TYPE" : type de l'element de plus grande dimension ({TRIANGLE}, {TETRAHEDRA}, {QUAD}, {HEXA}, etc) "DYNAMIC_MESH" : le maillage est-il dynamique ou pas ({STATIC}, {DYNAMIC}) "NAME" : nom du champ "COMPONENT_NAMES" : nom des composantes du champ ({K,EPSILON} ou {VITESSE_X,VITESSE_Y,VITESSE_Z}) "BOUNDARY_NAMES" : nom des bords "COORDINATES" : systeme de coordonnees des noeuds ({X}, {X,Y}, {X,Y,Z}, {R,THETA}, etc...) Exceptions:
GenericFieldError::INVALID : query non comprise
Reimplemented from Champ_Gen_de_Champs_Gen.
References Champ_Generique_base::get_property(), Champ_Gen_de_Champs_Gen::get_property(), Champ_Gen_de_Champs_Gen::get_source(), Champ_Generique_base::nom_post_, Motcles::search(), and TRUST_Vector< _CLASSE_ >::size().
Referenced by completer().
get_champ()
const Champ_base & Champ_Generique_Reduction_0D::get_champ (TRUST_Deriv< Champ_base > & espace_stockage) const override virtual
Reduction_0D du champ source (au sens qu on le rend uniforme) en fonction de la methode (min, max, moyenne, moyenne_ponderee_volume_elem, somme, somme_ponderee)
Dans le cas ou le champ possede plusieurs composantes, elles sont traitees une par une
Implements Champ_Generique_base.
References Champ_base::changer_temps(), Champ_Gen_de_Champs_Gen::creer_espace_stockage(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U_ptr::est_nul(), Process::exit(), extraire(), Champ_Generique_base::get_champ(), Champ_Gen_de_Champs_Gen::get_localisation(), Champ_Generique_base::get_ref_domaine_dis_base(), Champ_Gen_de_Champs_Gen::get_source(), Champ_Gen_de_Champs_Gen::get_time(), methode_, Field_base::nature_du_champ(), Field_base::nb_comp(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Domaine_VF::orientation(), Objet_U::que_suis_je(), Champ_Don_base::valeurs(), and Champ_Proto::valeurs().
get_champ_without_evaluation()
const Champ_base & Champ_Generique_Reduction_0D::get_champ_without_evaluation (TRUST_Deriv< Champ_base > & espace_stockage) const override virtual
Implements Champ_Generique_base.
References Champ_Gen_de_Champs_Gen::creer_espace_stockage(), Champ_Generique_base::get_champ_without_evaluation(), Champ_Gen_de_Champs_Gen::get_source(), Field_base::nature_du_champ(), and Field_base::nb_comp().
nommer_source()
void Champ_Generique_Reduction_0D::nommer_source () override virtual
Reimplemented from Champ_Gen_de_Champs_Gen.
References Champ_Generique_base::get_property(), Champ_Gen_de_Champs_Gen::get_source(), Champ_Generique_base::nom_post_, and Champ_Generique_base::nommer().
extraire()
void Champ_Generique_Reduction_0D::extraire (double & val_extraites, const DoubleVect & val_source, const int composante_VDF = -1) const
References Domaine_dis_base::domaine(), Process::exit(), Champ_Gen_de_Champs_Gen::get_localisation(), Champ_Gen_de_Champs_Gen::get_ref_domaine_dis_base(), Domaine_base::le_nom(), methode_, Domaine_dis_base::nb_elem(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and Domaine_VF::volumes().
Referenced by get_champ().
Member Data Documentation
info_obj
const Type_info Champ_Generique_Reduction_0D::info_obj static
methode_
Motcle Champ_Generique_Reduction_0D::methode_ protected
Referenced by completer(), extraire(), get_champ(), readOn(), and set_param().
numero_proc_
int Champ_Generique_Reduction_0D::numero_proc_ = -10 protected
Referenced by completer().
numero_elem_
int Champ_Generique_Reduction_0D::numero_elem_ = -10 protected
Referenced by completer().
volume_controle_
DoubleVect Champ_Generique_Reduction_0D::volume_controle_ mutable protected