TrioCFD: Tube_impose Class Reference
Tube_impose Class Reference
#include <Tube_base.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Tube_impose()
Tube_impose::Tube_impose ()
~Tube_impose()
Tube_impose::~Tube_impose ()
Member Function Documentation
cree_instance()
Objet_U * Tube_impose::cree_instance () static
taille_memoire()
unsigned Tube_impose::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Tube_impose::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Tube_impose::info () static
get_info()
const Type_info * Tube_impose::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Tube_base.
self_cast() [1/2]
Tube_impose & Tube_impose::self_cast (Objet_U & r) static
self_cast() [2/2]
const Tube_impose & Tube_impose::self_cast (const Objet_U & r) static
printOn()
Sortie & Tube_impose::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Tube_base.
References Tube_base::acceleration_, expressions_position_, Tube_base::nom_, Tube_base::omega_, Tube_base::pos_, Tube_base::rayon_, and Tube_base::v_.
readOn()
Entree & Tube_impose::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Tube_base.
References Param::ajouter(), TRUST_Vector< _CLASSE_ >::dimensionner(), expressions_position_, Param::lire_avec_accolades(), Tube_base::nom_, Tube_base::omega_, Objet_U::que_suis_je(), Tube_base::rayon_, Param::REQUIRED, and update_vitesse_position().
update_vitesse_position()
void Tube_impose::update_vitesse_position (double current_time, double dt, const Vecteur3 & force_appliquee) override virtual
Implements Tube_base.
References Tube_base::acceleration_, expressions_position_, Tube_base::pos_, and Tube_base::v_.
Referenced by readOn().
Member Data Documentation
info_obj
const Type_info Tube_impose::info_obj static
expressions_position_
Noms Tube_impose::expressions_position_ protected
Referenced by printOn(), readOn(), and update_vitesse_position().