TrioCFD: LoiParoiHybride Class Reference
LoiParoiHybride Class Reference
#include <LoiParoiHybride.h>
Detailed Description
Cette loi de paroi permet de choisir des lois de parois differentes par conditions aux limites.
Member Function Documentation
lire()
Entree & LoiParoiHybride::lire (Entree & is, const Noms & noms_bord, const Modele_turbulence_hyd_base & mod)
References TRUST_Vector< _CLASSE_ >::dimensionner(), Process::exit(), and TRUST_Vector< _CLASSE_ >::size().
Referenced by LoiParoiHybride_VDF::readOn(), and LoiParoiHybride_VEF::readOn().
associer()
void LoiParoiHybride::associer (const Domaine_dis_base & zd, const Domaine_Cl_dis_base & zcl)
References Domaine_dis_base::nb_front_Cl(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), and TRUST_Vector< _CLASSE_ >::size().
Referenced by LoiParoiHybride_VDF::associer(), and LoiParoiHybride_VEF::associer().
init_lois_paroi()
int LoiParoiHybride::init_lois_paroi ()
References TRUST_Vector< _CLASSE_ >::size().
Referenced by LoiParoiHybride_VDF::init_lois_paroi(), and LoiParoiHybride_VEF::init_lois_paroi().
calculer_hyd() [1/4]
int LoiParoiHybride::calculer_hyd (DoubleTab & tab1)
References TRUST_Vector< _CLASSE_ >::size().
Referenced by LoiParoiHybride_VDF::calculer_hyd(), and LoiParoiHybride_VEF::calculer_hyd().
calculer_hyd() [2/4]
int LoiParoiHybride::calculer_hyd (DoubleTab & tab1, const Domaine_dis_base & zd, const Domaine_Cl_dis_base & zcl, DoubleTab & tab_cis)
References Objet_U::dimension, TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_Cl_dis_base::les_conditions_limites(), Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), TRUST_Vector< _CLASSE_ >::size(), and TRUST_Deriv< _CLASSE_ >::valeur().
calculer_hyd() [3/4]
int LoiParoiHybride::calculer_hyd (DoubleTab & tab1, DoubleTab & tab2)
References TRUST_Vector< _CLASSE_ >::size().
calculer_hyd() [4/4]
int LoiParoiHybride::calculer_hyd (DoubleTab & tab1, DoubleTab & tab2, const Domaine_dis_base & zd, const Domaine_Cl_dis_base & zcl, DoubleTab & tab_cis)
References Objet_U::dimension, TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_Cl_dis_base::les_conditions_limites(), Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), TRUST_Vector< _CLASSE_ >::size(), and TRUST_Deriv< _CLASSE_ >::valeur().
calculer_hyd_BiK() [1/2]
int LoiParoiHybride::calculer_hyd_BiK (DoubleTab & tab_k, DoubleTab & tab_eps)
References TRUST_Vector< _CLASSE_ >::size().
Referenced by LoiParoiHybride_VDF::calculer_hyd_BiK(), and LoiParoiHybride_VEF::calculer_hyd_BiK().
calculer_hyd_BiK() [2/2]
int LoiParoiHybride::calculer_hyd_BiK (DoubleTab & tab_k, DoubleTab & tab_eps, Domaine_dis_base const & zd, Domaine_Cl_dis_base const & zcl, DoubleTab & tab_cis)
References Objet_U::dimension, TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_Cl_dis_base::les_conditions_limites(), Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), TRUST_Vector< _CLASSE_ >::size(), and TRUST_Deriv< _CLASSE_ >::valeur().