TrioCFD: Rectify_Mesh Class Reference
Rectify_Mesh Class Reference
#include <Rectify_Mesh.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Interprete_geometrique_base_32_64< _SIZE_ >
const Type_info * get_info () const override
void mettre_a_jour_sous_domaine (Domaine_t &domaine, int_t &elem, int_t num_premier_elem, int_t nb_elem) const
Public Member Functions inherited from Interprete
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Interprete
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Interprete
static Objet_U & objet (const Nom &)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
Constructor & Destructor Documentation
Rectify_Mesh()
Rectify_Mesh::Rectify_Mesh ()
~Rectify_Mesh()
Rectify_Mesh::~Rectify_Mesh ()
Member Function Documentation
cree_instance()
Objet_U * Rectify_Mesh::cree_instance () static
taille_memoire()
unsigned Rectify_Mesh::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Rectify_Mesh::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Rectify_Mesh::info () static
get_info()
const Type_info * Rectify_Mesh::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Interprete_geometrique_base_32_64< _SIZE_ >.
self_cast() [1/2]
Rectify_Mesh & Rectify_Mesh::self_cast (Objet_U & r) static
self_cast() [2/2]
const Rectify_Mesh & Rectify_Mesh::self_cast (const Objet_U & r) static
printOn()
Sortie & Rectify_Mesh::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Interprete_geometrique_base_32_64< _SIZE_ >.
References Interprete::printOn().
readOn()
Entree & Rectify_Mesh::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Interprete_geometrique_base_32_64< _SIZE_ >.
References Interprete::readOn().
interpreter_()
Entree & Rectify_Mesh::interpreter_ (Entree & is) override virtual
Implements Interprete_geometrique_base_32_64< _SIZE_ >.
References apply(), and Interprete_geometrique_base_32_64< _SIZE_ >::associer_domaine().
apply()
void Rectify_Mesh::apply () protected
References apply_2D(), apply_3D(), check_cell_type(), check_dimension(), Objet_U::dimension, Interprete_geometrique_base_32_64< _SIZE_ >::domaine(), and Domaine_base::le_nom().
Referenced by interpreter_().
check_dimension()
void Rectify_Mesh::check_dimension () const protected
References Objet_U::dimension, and Process::exit().
Referenced by apply().
check_cell_type()
void Rectify_Mesh::check_cell_type () const protected
References Interprete_geometrique_base_32_64< _SIZE_ >::domaine(), Process::exit(), Objet_U::que_suis_je(), and Domaine_32_64< _SIZE_ >::type_elem().
Referenced by apply().
apply_2D()
void Rectify_Mesh::apply_2D () protected
References check_cell_orientation_2D(), Interprete_geometrique_base_32_64< _SIZE_ >::domaine(), Scatter::init_sequential_domain(), Objet_U::que_suis_je(), Domaine_32_64< _SIZE_ >::type_elem(), and Scatter::uninit_sequential_domain().
Referenced by apply().
apply_3D()
void Rectify_Mesh::apply_3D () protected
References check_cell_enumeration_3D(), check_cell_orientation_3D(), Interprete_geometrique_base_32_64< _SIZE_ >::domaine(), Scatter::init_sequential_domain(), Objet_U::que_suis_je(), Domaine_32_64< _SIZE_ >::type_elem(), and Scatter::uninit_sequential_domain().
Referenced by apply().
check_cell_orientation_2D()
void Rectify_Mesh::check_cell_orientation_2D () protected
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Interprete_geometrique_base_32_64< _SIZE_ >::domaine(), Domaine_32_64< _SIZE_ >::les_elems(), Domaine_32_64< _SIZE_ >::les_sommets(), and swap_nodes().
Referenced by apply_2D().
check_cell_orientation_3D()
void Rectify_Mesh::check_cell_orientation_3D () protected
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Interprete_geometrique_base_32_64< _SIZE_ >::domaine(), Domaine_32_64< _SIZE_ >::les_elems(), Domaine_32_64< _SIZE_ >::les_sommets(), and swap_nodes().
Referenced by apply_3D().
check_cell_enumeration_3D()
void Rectify_Mesh::check_cell_enumeration_3D () protected
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Interprete_geometrique_base_32_64< _SIZE_ >::domaine(), Domaine_32_64< _SIZE_ >::les_elems(), Domaine_32_64< _SIZE_ >::les_sommets(), and swap_nodes().
Referenced by apply_3D().
swap_nodes()
void Rectify_Mesh::swap_nodes (IntTab & cells, int cell, int node0, int node1) protected
Referenced by check_cell_enumeration_3D(), check_cell_orientation_2D(), and check_cell_orientation_3D().
Member Data Documentation
info_obj
const Type_info Rectify_Mesh::info_obj static