TrioCFD: init_forcage_THI Class Reference
init_forcage_THI Class Reference
#include <init_forcage_THI.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
init_forcage_THI()
init_forcage_THI::init_forcage_THI ()
References advection_length_, and TRUSTArray< _TYPE_, _SIZE_ >::resize_array().
~init_forcage_THI()
init_forcage_THI::~init_forcage_THI ()
Member Function Documentation
cree_instance()
Objet_U * init_forcage_THI::cree_instance () static
taille_memoire()
unsigned init_forcage_THI::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int init_forcage_THI::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * init_forcage_THI::info () static
get_info()
const Type_info * init_forcage_THI::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
init_forcage_THI & init_forcage_THI::self_cast (Objet_U & r) static
self_cast() [2/2]
const init_forcage_THI & init_forcage_THI::self_cast (const Objet_U & r) static
printOn()
Sortie & init_forcage_THI::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
References advection_length_, advection_velocity_, amplitude, eps_etoile, facteur_forcage_, forcage_t_stop, forcage_ts_stop, forced_advection_, mode_max, mode_min, random_, tL, and type_forcage.
readOn()
Entree & init_forcage_THI::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
References advection_length_, advection_velocity_, Param::ajouter(), amplitude, eps_etoile, facteur_forcage_, forcage_t_stop, forcage_ts_stop, forced_advection_, Param::lire_avec_accolades(), mode_max, mode_min, Objet_U::que_suis_je(), random_, Param::REQUIRED, tL, and type_forcage.
compute_initial_chouippe()
void init_forcage_THI::compute_initial_chouippe (int nproc_tot, const Domaine_IJK & my_geom, int my_ni, int my_nj, int my_nk, const Domaine_IJK & my_splitting, Nom nom_sauvegarde)
References amplitude, eps_etoile, f_ph_THI, f_sp_THI, Domaine_IJK::get_domain_length(), Domaine_IJK::get_offset_local(), Domaine_IJK::get_origin(), i_offset, Random_process::initialise(), Force_sp::initialise(), Force_ph::initialise(), j_offset, k_offset, mode_max, mode_min, random_, tL, and type_forcage.
Referenced by Switch_FT_double::initialise(), and Navier_Stokes_FTD_IJK::initialise_ijk_fields().
compute_THI_force()
void init_forcage_THI::compute_THI_force (const int time_iteration, const double tstep, const double current_time, const Domaine_IJK & my_splitting)
References activate_forcage(), advection_length_, Force_ph::cheat_function(), Force_sp::compute_dirac_point_div_nulle(), Force_sp::compute_dirac_point_uniX_alongX(), Force_sp::compute_dirac_point_uniX_alongY(), Force_sp::compute_dirac_point_uniY(), Force_sp::compute_dirac_point_uniZ(), Force_sp::compute_diracs_for_cos_squarred(), Force_sp::compute_diracs_for_t_times_cos_squarred(), Force_sp::compute_door_cube(), Force_sp::compute_step2(), f_ph_THI, f_sp_THI, forced_advection_, Force_ph::from_spect_to_phys_opti2(), Force_ph::from_spect_to_phys_opti2_advection(), Random_process::get_b_flt(), Force_sp::get_coeff_flt(), Random_process::next_step2(), random_, Force_ph::set_zero(), and Force_sp::set_zero().
Referenced by Navier_Stokes_FTD_IJK::compute_add_THI_force(), and Navier_Stokes_FTD_IJK::compute_add_THI_force_sur_d_velocity().
get_type_forcage()
int init_forcage_THI::get_type_forcage ()
References type_forcage.
Referenced by activate_forcage(), Navier_Stokes_FTD_IJK::calculer_dv(), Navier_Stokes_FTD_IJK::calculer_terme_source_acceleration(), and Navier_Stokes_FTD_IJK::initialise_ijk_fields().
get_facteur_forcage()
int init_forcage_THI::get_facteur_forcage ()
References facteur_forcage_.
Referenced by Navier_Stokes_FTD_IJK::calculer_dv().
get_forced_advection()
int init_forcage_THI::get_forced_advection ()
References forced_advection_.
Referenced by Navier_Stokes_FTD_IJK::compute_add_THI_force(), and Navier_Stokes_FTD_IJK::compute_add_THI_force_sur_d_velocity().
activate_forcage()
int init_forcage_THI::activate_forcage (const int current_time_step, const double current_time)
References forcage_t_stop, forcage_ts_stop, and get_type_forcage().
Referenced by compute_THI_force().
get_semi_gen()
int init_forcage_THI::get_semi_gen ()
References Random_process::get_semi_gen(), and random_.
Referenced by Switch_FT_double::initialise().
get_b_flt()
ArrOfDouble init_forcage_THI::get_b_flt ()
References Random_process::get_b_flt(), and random_.
Referenced by Switch_FT_double::initialise().
get_force_ph()
IJK_Field_vector3_double init_forcage_THI::get_force_ph ()
References f_ph_THI, and Force_ph::get_force_attribute().
get_force_ph2()
IJK_Field_vector3_double & init_forcage_THI::get_force_ph2 ()
References f_ph_THI, and Force_ph::get_force_attribute2().
Referenced by Navier_Stokes_FTD_IJK::calculer_terme_source_acceleration(), Navier_Stokes_FTD_IJK::compute_add_THI_force(), Navier_Stokes_FTD_IJK::compute_add_THI_force_sur_d_velocity(), and Navier_Stokes_FTD_IJK::initialise_ijk_fields().
update_advection_velocity()
void init_forcage_THI::update_advection_velocity (ArrOfDouble & value)
References advection_velocity_, and TRUSTArray< _TYPE_, _SIZE_ >::resize_array().
Referenced by Navier_Stokes_FTD_IJK::compute_add_THI_force(), and Navier_Stokes_FTD_IJK::compute_add_THI_force_sur_d_velocity().
update_advection_length()
void init_forcage_THI::update_advection_length (double dt)
References advection_length_, advection_velocity_, and time_to_be_del_.
Referenced by Navier_Stokes_FTD_IJK::compute_add_THI_force(), and Navier_Stokes_FTD_IJK::compute_add_THI_force_sur_d_velocity().
Member Data Documentation
info_obj
const Type_info init_forcage_THI::info_obj static
type_forcage
int init_forcage_THI::type_forcage = 0 protected
Referenced by compute_initial_chouippe(), get_type_forcage(), printOn(), and readOn().
facteur_forcage_
int init_forcage_THI::facteur_forcage_ = 0 protected
Referenced by get_facteur_forcage(), printOn(), and readOn().
forced_advection_
int init_forcage_THI::forced_advection_ = 0 protected
Referenced by compute_THI_force(), get_forced_advection(), printOn(), and readOn().
advection_velocity_
ArrOfDouble init_forcage_THI::advection_velocity_ protected
Referenced by printOn(), readOn(), update_advection_length(), and update_advection_velocity().
advection_length_
ArrOfDouble init_forcage_THI::advection_length_ protected
Referenced by compute_THI_force(), init_forcage_THI(), printOn(), readOn(), and update_advection_length().
time_to_be_del_
double init_forcage_THI::time_to_be_del_ = 0. protected
Referenced by update_advection_length().
forcage_ts_stop
int init_forcage_THI::forcage_ts_stop = -1 protected
Referenced by activate_forcage(), printOn(), and readOn().
forcage_t_stop
double init_forcage_THI::forcage_t_stop = -1 protected
Referenced by activate_forcage(), printOn(), and readOn().
mode_min
int init_forcage_THI::mode_min = 0 protected
Referenced by compute_initial_chouippe(), printOn(), and readOn().
mode_max
int init_forcage_THI::mode_max = 0 protected
Referenced by compute_initial_chouippe(), printOn(), and readOn().
amplitude
double init_forcage_THI::amplitude = 1. protected
Referenced by compute_initial_chouippe(), printOn(), and readOn().
eps_etoile
double init_forcage_THI::eps_etoile = 0.1 protected
Referenced by compute_initial_chouippe(), printOn(), and readOn().
tL
double init_forcage_THI::tL = 0.02 protected
Referenced by compute_initial_chouippe(), printOn(), and readOn().
i_offset
int init_forcage_THI::i_offset = 0 protected
Referenced by compute_initial_chouippe().
j_offset
int init_forcage_THI::j_offset = 0 protected
Referenced by compute_initial_chouippe().
k_offset
int init_forcage_THI::k_offset = 0 protected
Referenced by compute_initial_chouippe().
f_sp_THI
Force_sp init_forcage_THI::f_sp_THI protected
Referenced by compute_initial_chouippe(), and compute_THI_force().
f_ph_THI
Force_ph init_forcage_THI::f_ph_THI protected
Referenced by compute_initial_chouippe(), compute_THI_force(), get_force_ph(), and get_force_ph2().
random_
Random_process init_forcage_THI::random_ protected
Referenced by compute_initial_chouippe(), compute_THI_force(), get_b_flt(), get_semi_gen(), printOn(), and readOn().