TrioCFD: Op_Diff_K_Eps_VDF_base Class Reference
Op_Diff_K_Eps_VDF_base Class Reference
#include <Op_Diff_K_Eps_VDF_base.h>
Public Member Functions
void completer () override
const Type_info * get_info () const override
void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const override
Public Member Functions inherited from Op_Dift_VDF_base
void contribuer_au_second_membre (DoubleTab &) const override
const Type_info * get_info () const override
Public Member Functions inherited from Op_Diff_VDF_base
void completer () override
void contribuer_au_second_membre (DoubleTab &resu) const override
const Type_info * get_info () const override
int impr (Sortie &os) const override
Public Member Functions inherited from Operateur_Diff_base
virtual void associer_diffusivite_pour_pas_de_temps (const Champ_base &)
const Type_info * get_info () const override
Public Member Functions inherited from Operateur_base
void associer_eqn (const Equation_base &)
virtual double calculer_dt_stab () const
virtual void completer ()
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual void mettre_a_jour (double temps)
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Operateur_Diff_base
virtual const Champ_base & diffusivite_pour_pas_de_temps () const
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Op_Diff_K_Eps_VDF_base() [1/2]
Op_Diff_K_Eps_VDF_base::Op_Diff_K_Eps_VDF_base ()
~Op_Diff_K_Eps_VDF_base()
Op_Diff_K_Eps_VDF_base::~Op_Diff_K_Eps_VDF_base () override
Op_Diff_K_Eps_VDF_base() [2/2]
Op_Diff_K_Eps_VDF_base::Op_Diff_K_Eps_VDF_base (const Iterateur_VDF_base & iter_base) inline
References iter.
Member Function Documentation
info()
const Type_info * Op_Diff_K_Eps_VDF_base::info () static
get_info()
const Type_info * Op_Diff_K_Eps_VDF_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Op_Dift_VDF_base.
Reimplemented in Op_Diff_K_Eps_VDF_Elem, Op_Diff_K_Eps_VDF_Elem_Axi, Op_Diff_K_Eps_QC_VDF_Elem, Op_Diff_K_Eps_var_VDF_Elem, Op_Diff_K_Eps_var_QC_VDF_Elem, Op_Diff_K_VDF_Elem, and Op_Diff_Eps_VDF_Elem.
self_cast() [1/2]
Op_Diff_K_Eps_VDF_base & Op_Diff_K_Eps_VDF_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Op_Diff_K_Eps_VDF_base & Op_Diff_K_Eps_VDF_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Op_Diff_K_Eps_VDF_base::printOn (Sortie & os) const override protected virtual
DOES NOTHING - to override in derived classes.
Imprime l'operateur sur un flot de sortie.
Parameters
(Sortie& os) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Op_Dift_VDF_base.
Reimplemented in Op_Diff_K_Eps_VDF_Elem, Op_Diff_K_Eps_VDF_Elem_Axi, Op_Diff_K_Eps_QC_VDF_Elem, Op_Diff_K_Eps_var_VDF_Elem, Op_Diff_K_Eps_var_QC_VDF_Elem, Op_Diff_K_VDF_Elem, and Op_Diff_Eps_VDF_Elem.
References Objet_U::que_suis_je().
readOn()
Entree & Op_Diff_K_Eps_VDF_base::readOn (Entree & is) override protected virtual
DOES NOTHING - to override in derived classes.
Lit un operateur sur un flot d'entree.
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Op_Dift_VDF_base.
Reimplemented in Op_Diff_K_Eps_VDF_Elem, Op_Diff_K_Eps_VDF_Elem_Axi, Op_Diff_K_Eps_QC_VDF_Elem, Op_Diff_K_Eps_var_VDF_Elem, Op_Diff_K_Eps_var_QC_VDF_Elem, Op_Diff_K_VDF_Elem, and Op_Diff_Eps_VDF_Elem.
completer()
void Op_Diff_K_Eps_VDF_base::completer () override virtual
Associe l'operateur au domaine_dis, le domaine_Cl_dis, et a l'inconnue de son equation.
Exceptions
pas d'equation associee
Reimplemented from Op_Diff_VDF_base.
References Iterateur_VDF_base::associer_champ_convecte_ou_inc(), Eval_Diff_K_Eps_VDF::associer_diff_turb(), Eval_Diff_K_Eps_VDF::associer_mvolumique(), Eval_Diff_K_Eps_VDF::associer_Pr_K_Eps(), Operateur_base::completer(), Iterateur_VDF_base::completer_(), MorEqn::equation(), Iterateur_VDF_base::evaluateur(), Modele_turbulence_hyd_2_eq_base::get_Prandtl_Eps(), Modele_turbulence_hyd_2_eq_base::get_Prandtl_K(), iter, Objet_U::le_nom(), Milieu_base::masse_volumique(), Transport_2eq_base::modele_turbulence(), MorEqn::mon_equation, Iterateur_VDF_base::set_convective_op_pb_type(), Iterateur_VDF_base::set_name_champ_inco(), Transport_K_ou_Eps_base::transporte_t_il_K(), TRUST_Ref< _CLASSE_ >::valeur(), and Modele_turbulence_hyd_base::viscosite_turbulente().
associer_diffusivite()
void Op_Diff_K_Eps_VDF_base::associer_diffusivite (const Champ_base & ch_diff) override virtual
Implements Operateur_Diff_base.
References Eval_Diff_K_Eps_VDF::associer(), Iterateur_VDF_base::evaluateur(), and iter.
associer_diffusivite_turbulente()
void Op_Diff_K_Eps_VDF_base::associer_diffusivite_turbulente ()
modifier_pour_Cl()
void Op_Diff_K_Eps_VDF_base::modifier_pour_Cl (Matrice_Morse & , DoubleTab &) const override virtual
DOES NOTHING - to override in derived classes.
Parameters
(Matrice_Morse&) une matrice au format Morse
(DoubleTab&) un tableau de valeur (double)
Exceptions
methode a surcharger
Reimplemented from Operateur_base.
References Nom::debute_par(), Iterateur_VDF_base::domaine(), Iterateur_VDF_base::domaine_Cl(), Equation_base::domaine_Cl_dis(), MorEqn::equation(), Process::exit(), Domaine_VF::face_voisins(), Matrice_Morse::get_set_coeff(), Matrice_Morse::get_tab1(), Transport_K_Eps_base::inconnue(), Transport_K_ou_Eps_base::inconnue(), iter, Domaine_Cl_dis_base::les_conditions_limites(), Modele_turbulence_hyd_base::loi_paroi(), Navier_Stokes_Turbulent::modele_turbulence(), Op_VDF_Elem::modifier_pour_Cl(), MorEqn::mon_equation, Front_VF::nb_faces(), Front_VF::num_premiere_face(), Objet_U::que_suis_je(), TRUST_Vector< _CLASSE_ >::size(), TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), and Champ_Inc_base::valeurs().
diffusivite_turbulente()
const Champ_Fonc_base & Op_Diff_K_Eps_VDF_base::diffusivite_turbulente () const
References Eval_Diff_K_Eps_VDF::diffusivite_turbulente(), Iterateur_VDF_base::evaluateur(), and iter.
diffusivite()
const Champ_base & Op_Diff_K_Eps_VDF_base::diffusivite () const override virtual
Implements Operateur_Diff_base.
References Eval_Diff_K_Eps_VDF::diffusivite(), Iterateur_VDF_base::evaluateur(), and iter.
mettre_a_jour_diffusivite()
virtual void Op_Diff_K_Eps_VDF_base::mettre_a_jour_diffusivite () const inline virtual
References MorEqn::mon_equation, and TRUST_Ref< _CLASSE_ >::non_nul().
Referenced by ajouter_blocs(), and calculer().
calculer()
DoubleTab & Op_Diff_K_Eps_VDF_base::calculer (const DoubleTab & inco, DoubleTab & resu) const inline override virtual
calcule la contribution de la diffusion, la range dans resu
Reimplemented from Op_Diff_VDF_base.
References Iterateur_VDF_base::calculer(), iter, and mettre_a_jour_diffusivite().
get_iter()
TRUST_Deriv< Iterateur_VDF_base > & Op_Diff_K_Eps_VDF_base::get_iter () inline
References iter.
has_interface_blocs()
int Op_Diff_K_Eps_VDF_base::has_interface_blocs () const inline override virtual
Reimplemented from Op_Diff_VDF_base.
dimensionner_blocs()
void Op_Diff_K_Eps_VDF_base::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl) const override virtual
Reimplemented from Operateur_base.
References Op_VDF_Elem::dimensionner(), Iterateur_VDF_base::domaine(), Iterateur_VDF_base::domaine_Cl(), MorEqn::equation(), Nom::getString(), Equation_base::inconnue(), iter, Field_base::le_nom(), and Matrice_Morse::nb_colonnes().
ajouter_blocs()
void Op_Diff_K_Eps_VDF_base::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl) const override virtual
Reimplemented from Op_Dift_VDF_base.
References Iterateur_VDF_base::ajouter(), Iterateur_VDF_base::ajouter_contribution(), Statistiques::begin_count(), Statistiques::end_count(), MorEqn::equation(), Nom::getString(), Equation_base::inconnue(), iter, Field_base::le_nom(), mettre_a_jour_diffusivite(), and Champ_Inc_base::valeurs().
Member Data Documentation
info_obj
const Type_info Op_Diff_K_Eps_VDF_base::info_obj static
iter
TRUST_Deriv< Iterateur_VDF_base > Op_Diff_K_Eps_VDF_base::iter protected
Referenced by ajouter_blocs(), associer_diffusivite(), calculer(), completer(), diffusivite(), diffusivite_turbulente(), dimensionner_blocs(), get_iter(), modifier_pour_Cl(), and Op_Diff_K_Eps_VDF_base().