TrioCFD: Diffusion_supplementaire_echelle_temp_turb_PolyMAC_P0 Class Reference
Diffusion_supplementaire_echelle_temp_turb_PolyMAC_P0 Class Reference
#include <Diffusion_supplementaire_echelle_temp_turb_PolyMAC_P0.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Source_Diffusion_supplementaire_echelle_temp_turb
void completer () override
const Type_info * get_info () const override
Public Member Functions inherited from Sources_Multiphase_base
const Type_info * get_info () const override
void mettre_a_jour (double temps) override
Public Member Functions inherited from Source_base
virtual int a_pour_Champ_Fonc (const Motcle &mot, TRUST_Ref< Champ_base * > &ch_ref) const
virtual void associer_champ_rho (const Champ_base &champ_rho)
virtual void completer ()
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
virtual void resetTime (double t)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Source_Diffusion_supplementaire_echelle_temp_turb
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
See also
Operateur_PolyMAC_P0_base Operateur_base
Constructor & Destructor Documentation
Diffusion_supplementaire_echelle_temp_turb_PolyMAC_P0()
Diffusion_supplementaire_echelle_temp_turb_PolyMAC_P0::Diffusion_supplementaire_echelle_temp_turb_PolyMAC_P0 ()
~Diffusion_supplementaire_echelle_temp_turb_PolyMAC_P0()
Diffusion_supplementaire_echelle_temp_turb_PolyMAC_P0::~Diffusion_supplementaire_echelle_temp_turb_PolyMAC_P0 ()
Member Function Documentation
cree_instance()
Objet_U * Diffusion_supplementaire_echelle_temp_turb_PolyMAC_P0::cree_instance () static
taille_memoire()
unsigned Diffusion_supplementaire_echelle_temp_turb_PolyMAC_P0::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Diffusion_supplementaire_echelle_temp_turb_PolyMAC_P0::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Diffusion_supplementaire_echelle_temp_turb_PolyMAC_P0::info () static
get_info()
const Type_info * Diffusion_supplementaire_echelle_temp_turb_PolyMAC_P0::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Sources_Multiphase_base.
self_cast() [1/2]
Diffusion_supplementaire_echelle_temp_turb_PolyMAC_P0 & Diffusion_supplementaire_echelle_temp_turb_PolyMAC_P0::self_cast (Objet_U & r) static
self_cast() [2/2]
const Diffusion_supplementaire_echelle_temp_turb_PolyMAC_P0 & Diffusion_supplementaire_echelle_temp_turb_PolyMAC_P0::self_cast (const Objet_U & r) static
printOn()
Sortie & Diffusion_supplementaire_echelle_temp_turb_PolyMAC_P0::printOn (Sortie & os) const override protected virtual
DOES NOTHING - to override in derived classes.
Imprime la source sur un flot de sortie.
Parameters
(Sortie& os) le flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Sources_Multiphase_base.
References Source_Diffusion_supplementaire_echelle_temp_turb::printOn().
readOn()
Entree & Diffusion_supplementaire_echelle_temp_turb_PolyMAC_P0::readOn (Entree & is) override protected virtual
DOES NOTHING - to override in derived classes.
Lecture d'un terme source sur un flot d'entree.
Parameters
(Entree& is) le flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Sources_Multiphase_base.
References Source_Diffusion_supplementaire_echelle_temp_turb::readOn().
dimensionner_blocs()
void Diffusion_supplementaire_echelle_temp_turb_PolyMAC_P0::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl = {}) const override virtual
Reimplemented from Source_base.
References Matrix_tools::allocate_morse_matrix(), TRUSTTab< _TYPE_, _SIZE_ >::append_line(), Source_Diffusion_supplementaire_echelle_temp_turb::dimensionner_blocs(), MorEqn::equation(), Champ_Elem_PolyMAC_P0::fgrad_d, Champ_Elem_PolyMAC_P0::fgrad_e, Equation_base::inconnue(), Champ_Elem_PolyMAC_P0::init_grad(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), and Champ_Inc_base::valeurs().
ajouter_blocs()
void Diffusion_supplementaire_echelle_temp_turb_PolyMAC_P0::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = {}) const override virtual
Implements Source_Diffusion_supplementaire_echelle_temp_turb.
References Champ_Elem_PolyMAC_P0::calc_grad(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, MorEqn::equation(), Process::exit(), Source_Diffusion_supplementaire_echelle_temp_turb::f_grad_tau_fixe, Champ_Inc_P0_base::fcl(), Champ_Elem_PolyMAC_P0::fgrad_d, Champ_Elem_PolyMAC_P0::fgrad_e, Champ_Elem_PolyMAC_P0::fgrad_w, Probleme_base::get_champ(), Champ_Elem_PolyMAC_P0::init_grad(), Domaine_Cl_dis_base::les_conditions_limites(), limiter_tau_, Equation_base::milieu(), Champ_Inc_base::passe(), Milieu_base::porosite_elem(), Equation_base::probleme(), Objet_U::que_suis_je(), Source_Diffusion_supplementaire_echelle_temp_turb::sigma_tau_, Champ_Inc_base::valeurs(), and Champ_Proto::valeurs().
Member Data Documentation
info_obj
const Type_info Diffusion_supplementaire_echelle_temp_turb_PolyMAC_P0::info_obj static
limiter_
double Diffusion_supplementaire_echelle_temp_turb_PolyMAC_P0::limiter_ = 5 protected
limiter_tau_
double Diffusion_supplementaire_echelle_temp_turb_PolyMAC_P0::limiter_tau_ = 1.e-6 protected
Referenced by ajouter_blocs().