TrioCFD: Modele_turbulence_hyd_base Class Reference
Modele_turbulence_hyd_base Class Reference abstract
#include <Modele_turbulence_hyd_base.h>
Public Member Functions
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Type_info * get_info () const override
virtual void imprimer (Sortie &) const
void lire_distance_paroi ()
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual int preparer_calcul ()
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
qui representent un modele de turbulence pour les equations de Navier-Stokes. Il existe deja deux classes derivees qui representent le modele de turbulence (k,e) et le modele de turbulence sous maille. Ces deux modeles ont en commun le calcul d'une viscosite turbulente.
B.Mat. : la classe herite de support_champ_masse_volumique. en Front-Tracking (et plus tard en qc), elle fournit le mecanisme pour recuperer rho.
Constructor & Destructor Documentation
Modele_turbulence_hyd_base()
Modele_turbulence_hyd_base::Modele_turbulence_hyd_base ()
~Modele_turbulence_hyd_base()
Modele_turbulence_hyd_base::~Modele_turbulence_hyd_base () override
Member Function Documentation
info()
const Type_info * Modele_turbulence_hyd_base::info () static
get_info()
const Type_info * Modele_turbulence_hyd_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
Reimplemented in Modele_turbulence_hyd_LES_axi_VDF, Modele_turbulence_hyd_LES_DSGS_VDF, Modele_turbulence_hyd_LES_selectif_mod_VDF, Modele_turbulence_hyd_LES_selectif_VDF, Modele_turbulence_hyd_LES_SMAGO_DYN_VDF, Modele_turbulence_hyd_LES_VDF, Modele_turbulence_hyd_LES_1elt_selectif_mod_VEF, Modele_turbulence_hyd_LES_1elt_VEF, Modele_turbulence_hyd_LES_Fst_sel_VEF, Modele_turbulence_hyd_LES_Fst_VEF, Modele_turbulence_hyd_LES_Smago_filtre_VEF, Modele_turbulence_hyd_LES_VEF, Modele_turbulence_hyd_combinaison, Modele_turbulence_hyd_K_Eps, Modele_turbulence_hyd_K_Eps_2_Couches, Modele_turbulence_hyd_K_Eps_Bas_Reynolds, Modele_turbulence_hyd_K_Eps_Bicephale, Modele_turbulence_hyd_K_Eps_Realisable, Modele_turbulence_hyd_K_Eps_Realisable_Bicephale, Modele_turbulence_hyd_K_Omega, Modele_turbulence_hyd_RANS_Bicephale_base, Modele_turbulence_hyd_RANS_K_Eps_base, Modele_turbulence_hyd_RANS_K_Omega_base, Modele_turbulence_hyd_LES_base, Modele_turbulence_hyd_Longueur_Melange_base, Modele_turbulence_hyd_null, Modele_turbulence_hyd_LES_Smago_VDF, Modele_turbulence_hyd_LES_VDF_base, Modele_turbulence_hyd_LES_Wale_VDF, Modele_turbulence_hyd_Longueur_Melange_VDF, Modele_turbulence_hyd_LES_Smago_VEF, Modele_turbulence_hyd_LES_VEF_base, Modele_turbulence_hyd_LES_Wale_VEF, and Modele_turbulence_hyd_Longueur_Melange_VEF.
self_cast() [1/2]
Modele_turbulence_hyd_base & Modele_turbulence_hyd_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Modele_turbulence_hyd_base & Modele_turbulence_hyd_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Modele_turbulence_hyd_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
Reimplemented in Modele_turbulence_hyd_LES_axi_VDF, Modele_turbulence_hyd_LES_DSGS_VDF, Modele_turbulence_hyd_LES_selectif_mod_VDF, Modele_turbulence_hyd_LES_selectif_VDF, Modele_turbulence_hyd_LES_SMAGO_DYN_VDF, Modele_turbulence_hyd_LES_VDF, Modele_turbulence_hyd_LES_1elt_selectif_mod_VEF, Modele_turbulence_hyd_LES_1elt_VEF, Modele_turbulence_hyd_LES_Fst_sel_VEF, Modele_turbulence_hyd_LES_Fst_VEF, Modele_turbulence_hyd_LES_Smago_filtre_VEF, Modele_turbulence_hyd_LES_VEF, Modele_turbulence_hyd_combinaison, Modele_turbulence_hyd_K_Eps, Modele_turbulence_hyd_K_Eps_2_Couches, Modele_turbulence_hyd_K_Eps_Bas_Reynolds, Modele_turbulence_hyd_K_Eps_Bicephale, Modele_turbulence_hyd_K_Eps_Realisable, Modele_turbulence_hyd_K_Eps_Realisable_Bicephale, Modele_turbulence_hyd_K_Omega, Modele_turbulence_hyd_RANS_Bicephale_base, Modele_turbulence_hyd_RANS_K_Eps_base, Modele_turbulence_hyd_RANS_K_Omega_base, Modele_turbulence_hyd_LES_base, Modele_turbulence_hyd_Longueur_Melange_base, Modele_turbulence_hyd_null, Modele_turbulence_hyd_LES_Smago_VDF, Modele_turbulence_hyd_LES_VDF_base, Modele_turbulence_hyd_LES_Wale_VDF, Modele_turbulence_hyd_Longueur_Melange_VDF, Modele_turbulence_hyd_LES_Smago_VEF, Modele_turbulence_hyd_LES_VEF_base, Modele_turbulence_hyd_LES_Wale_VEF, and Modele_turbulence_hyd_Longueur_Melange_VEF.
References Objet_U::le_nom(), and Objet_U::que_suis_je().
Referenced by Modele_turbulence_hyd_RANS_Bicephale_base::printOn(), Modele_turbulence_hyd_0_eq_base::printOn(), Modele_turbulence_hyd_2_eq_base::printOn(), and Modele_turbulence_hyd_7_eq_base::printOn().
readOn()
Entree & Modele_turbulence_hyd_base::readOn (Entree & is) override protected virtual
Lit les specifications d'un modele de turbulence a partir d'un flot d'entree.
Format: Modele_turbulence type_modele { [Turbulence_paroi la_loi_de_paroi] bloc de lecture specifique du type de turbulence }
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Exceptions
accolade ouvrante attendue
loi de paroi incompatible avec le probleme
Reimplemented from Objet_U.
Reimplemented in Modele_turbulence_hyd_LES_axi_VDF, Modele_turbulence_hyd_LES_DSGS_VDF, Modele_turbulence_hyd_LES_selectif_mod_VDF, Modele_turbulence_hyd_LES_selectif_VDF, Modele_turbulence_hyd_LES_SMAGO_DYN_VDF, Modele_turbulence_hyd_LES_VDF, Modele_turbulence_hyd_LES_1elt_selectif_mod_VEF, Modele_turbulence_hyd_LES_1elt_VEF, Modele_turbulence_hyd_LES_Fst_sel_VEF, Modele_turbulence_hyd_LES_Fst_VEF, Modele_turbulence_hyd_LES_Smago_filtre_VEF, Modele_turbulence_hyd_LES_VEF, Modele_turbulence_hyd_combinaison, Modele_turbulence_hyd_K_Eps, Modele_turbulence_hyd_K_Eps_2_Couches, Modele_turbulence_hyd_K_Eps_Bas_Reynolds, Modele_turbulence_hyd_K_Eps_Bicephale, Modele_turbulence_hyd_K_Eps_Realisable, Modele_turbulence_hyd_K_Eps_Realisable_Bicephale, Modele_turbulence_hyd_K_Omega, Modele_turbulence_hyd_RANS_Bicephale_base, Modele_turbulence_hyd_RANS_K_Eps_base, Modele_turbulence_hyd_RANS_K_Omega_base, Modele_turbulence_hyd_LES_base, Modele_turbulence_hyd_Longueur_Melange_base, Modele_turbulence_hyd_null, Modele_turbulence_hyd_LES_Smago_VDF, Modele_turbulence_hyd_LES_VDF_base, Modele_turbulence_hyd_LES_Wale_VDF, Modele_turbulence_hyd_Longueur_Melange_VDF, Modele_turbulence_hyd_LES_Smago_VEF, Modele_turbulence_hyd_LES_VEF_base, Modele_turbulence_hyd_LES_Wale_VEF, and Modele_turbulence_hyd_Longueur_Melange_VEF.
References Process::exit(), Param::lire_avec_accolades_depuis(), Objet_U::que_suis_je(), and set_param().
Referenced by Modele_turbulence_hyd_RANS_Bicephale_base::readOn(), Modele_turbulence_hyd_0_eq_base::readOn(), Modele_turbulence_hyd_2_eq_base::readOn(), and Modele_turbulence_hyd_7_eq_base::readOn().
viscosite_turbulente() [1/2]
const Champ_Fonc_base & Modele_turbulence_hyd_base::viscosite_turbulente () const inline
References la_viscosite_turbulente_.
Referenced by Source_Transport_Fluctuation_Temperature_VDF_Elem::ajouter(), Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::ajouter(), Source_Transport_Fluctuation_Temperature_W_VDF_Elem::ajouter(), Source_Transport_Flux_Chaleur_Turbulente_VDF_Face::ajouter(), Source_Transport_K_Realisable_VEF_Face::ajouter(), Source_Transport_K_Eps_Bas_Reynolds_VEF_Face::ajouter(), Source_Transport_Bas_Reynolds_VDF_Elem_base::ajouter_blocs(), Op_Diff_K_Omega_VDF_base::associer_diffusivite_turbulente(), Op_Diff_K_Eps_Bas_Re_VDF_base::associer_diffusivite_turbulente_impl(), Modele_turbulence_scal_LES_dyn_VDF::calculer_diffusivite_turbulente(), Traitement_particulier_NS_canal_VDF::calculer_moyenne_spatiale_nut(), Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_nut(), Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_nut(), Op_Diff_K_Eps_VDF_base::completer(), Modele_turbulence_scal_Fluctuation_Temperature::completer(), Modele_turbulence_scal_Fluctuation_Temperature_W::completer(), Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re::completer(), Op_Dift_EF_base::completer(), Op_Diff_PolyMAC_Face::completer(), Modele_turbulence_scal_diffturb_base::completer(), Op_Dift_VEF_base::completer(), Op_Diff_Dift_VDF< OP_TYPE >::completer_impl(), limiter_viscosite_turbulente(), Source_Transport_Eps_Realisable_VEF_Face::mettre_a_jour(), Source_Transport_K_Realisable_VEF_Face::mettre_a_jour(), Source_Transport_K_Eps_Realisable_VEF_Face::mettre_a_jour(), Convection_Diffusion_Concentration_FT_Disc::mettre_a_jour_chimie(), Convection_Diffusion_Concentration_Turbulent_FT_Disc::mettre_a_jour_chimie(), Navier_Stokes_Turbulent_ALE::viscosite_turbulente(), Navier_Stokes_IBM_Turbulent::viscosite_turbulente(), and Navier_Stokes_Turbulent::viscosite_turbulente().
viscosite_turbulente() [2/2]
Champ_Fonc_base & Modele_turbulence_hyd_base::viscosite_turbulente () inline
References la_viscosite_turbulente_.
equation() [1/2]
Equation_base & Modele_turbulence_hyd_base::equation () inline
Renvoie l'equation associee au modele de turbulence.
(c'est une equation du type Equation_base)
Returns
(Equation_base&) l'equation associee au modele de turbulence
References TRUST_Ref< _CLASSE_ >::est_nul(), Process::exit(), mon_equation_, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by a_faire(), Transport_K_Eps::associer_modele_turbulence(), Transport_K_Eps_Bas_Reynolds::associer_modele_turbulence(), Transport_K_Eps_Realisable::associer_modele_turbulence(), Transport_K_KEps::associer_modele_turbulence(), Transport_K_Omega::associer_modele_turbulence(), Transport_K_ou_Eps::associer_modele_turbulence(), Transport_K_ou_Eps_Realisable::associer_modele_turbulence(), Modele_turbulence_hyd_combinaison::calculer_viscosite_turbulente(), discretiser_visc_turb(), limiter_viscosite_turbulente(), lire_distance_paroi(), lire_motcle_non_standard(), Transport_2eq_base::lire_op_diff_turbulent(), Modele_turbulence_hyd_combinaison::mettre_a_jour(), preparer_calcul(), Modele_turbulence_hyd_K_Eps::preparer_calcul(), Modele_turbulence_hyd_K_Eps_2_Couches::preparer_calcul(), Modele_turbulence_hyd_K_Eps_Bicephale::preparer_calcul(), Modele_turbulence_hyd_Longueur_Melange_VEF::preparer_calcul(), Modele_turbulence_hyd_K_Omega::readOn(), Modele_turbulence_hyd_null::readOn(), Modele_turbulence_hyd_null::sauvegarder(), Turbulence_paroi_base::typer_lire_turbulence_paroi(), and Modele_turbulence_hyd_LES_base::verifie_loi_paroi_diphasique().
equation() [2/2]
const Equation_base & Modele_turbulence_hyd_base::equation () const inline
References TRUST_Ref< _CLASSE_ >::est_nul(), Process::exit(), mon_equation_, and TRUST_Ref< _CLASSE_ >::valeur().
loi_paroi() [1/2]
const Turbulence_paroi_base & Modele_turbulence_hyd_base::loi_paroi () const inline
References loipar_, and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by Source_Robin::ajouter(), Champ_Q1_EF::calcul_y_plus(), Champ_P1NC::calcul_y_plus(), Champ_Face_VDF::calcul_y_plus(), Champ_P1NC::calcul_y_plus_diphasique(), Champ_Face_VDF::calcul_y_plus_diphasique(), Paroi_std_scal_hyd_EF::calculer_scal(), Paroi_loi_WW_scal_VDF::calculer_scal(), Paroi_ODVM_scal_VDF::calculer_scal(), Paroi_std_scal_hyd_VDF::calculer_scal(), Paroi_loi_WW_scal_VEF::calculer_scal(), Paroi_scal_analytique_VEF::calculer_scal(), Paroi_std_scal_hyd_VEF::calculer_scal(), Modele_turbulence_hyd_K_Eps::calculer_viscosite_turbulente(), Modele_turbulence_hyd_K_Eps_Bicephale::calculer_viscosite_turbulente(), Navier_Stokes_IBM_Turbulent::completer(), Navier_Stokes_Turbulent::completer(), Transport_K_Eps::corriger_derivee_impl(), Transport_K_Omega::corriger_derivee_impl(), Transport_K_ou_Eps::corriger_derivee_impl(), Transport_K_ou_Eps_Realisable::corriger_derivee_impl(), Champ_P1NC_implementation::filtrer_L2(), Paroi_TBLE_scal_VDF::getLoiParoiHydraulique(), ParoiVEF_TBLE_scal::getLoiParoiHydraulique(), Paroi_TBLE_scal_VDF::init_lois_paroi(), ParoiVEF_TBLE_scal::init_lois_paroi(), Y_plus_Champ_Face::me_calculer(), Y_plus_Champ_P1NC::me_calculer(), Source_Transport_Eps_Realisable_VEF_Face::mettre_a_jour(), Source_Transport_K_Realisable_VEF_Face::mettre_a_jour(), Source_Transport_K_Eps_Realisable_VEF_Face::mettre_a_jour(), Op_Diff_K_Eps_VDF_base::modifier_pour_Cl(), Op_Diff_K_Omega_VDF_base::modifier_pour_Cl(), Navier_Stokes_Turbulent_ALE::preparer_calcul(), Navier_Stokes_IBM_Turbulent::preparer_calcul(), Navier_Stokes_Turbulent::preparer_calcul(), and Turbulence_paroi_scal_base::typer_lire_turbulence_paroi_scal().
loi_paroi() [2/2]
Turbulence_paroi_base & Modele_turbulence_hyd_base::loi_paroi () inline
References loipar_, and TRUST_Deriv< _CLASSE_ >::valeur().
utiliser_loi_paroi()
bool Modele_turbulence_hyd_base::utiliser_loi_paroi () const inline
References loipar_, Objet_U_ptr::non_nul(), and Turbulence_paroi_base::use_shear().
Referenced by Champ_P1NC_implementation::filtrer_L2().
has_loi_paroi_hyd()
bool Modele_turbulence_hyd_base::has_loi_paroi_hyd () const inline
References loipar_, and Objet_U_ptr::non_nul().
Referenced by Navier_Stokes_Turbulent_ALE::preparer_calcul(), Navier_Stokes_IBM_Turbulent::preparer_calcul(), Navier_Stokes_Turbulent::preparer_calcul(), and Modele_turbulence_scal_base::readOn().
calcul_tenseur_Re()
virtual bool Modele_turbulence_hyd_base::calcul_tenseur_Re (const DoubleTab & nu_turb, const DoubleTab & grad, DoubleTab & Re) const inline virtual
Reimplemented in Modele_turbulence_hyd_RANS_K_Eps_base.
set_param()
void Modele_turbulence_hyd_base::set_param (Param & param) virtual
Reimplemented in Modele_turbulence_hyd_2_eq_base, Modele_turbulence_hyd_LES_selectif_mod_VDF, Modele_turbulence_hyd_LES_SMAGO_DYN_VDF, Modele_turbulence_hyd_LES_VDF, Modele_turbulence_hyd_combinaison, Modele_turbulence_hyd_K_Eps, Modele_turbulence_hyd_K_Eps_2_Couches, Modele_turbulence_hyd_K_Eps_Bas_Reynolds, Modele_turbulence_hyd_K_Eps_Bicephale, Modele_turbulence_hyd_K_Eps_Realisable, Modele_turbulence_hyd_K_Eps_Realisable_Bicephale, Modele_turbulence_hyd_K_Omega, Modele_turbulence_hyd_RANS_Bicephale_base, Modele_turbulence_hyd_RANS_K_Eps_base, Modele_turbulence_hyd_RANS_K_Omega_base, Modele_turbulence_hyd_0_eq_base, Modele_turbulence_hyd_LES_base, Modele_turbulence_hyd_LES_Smago_VDF, Modele_turbulence_hyd_LES_Wale_VDF, Modele_turbulence_hyd_Longueur_Melange_VDF, Modele_turbulence_hyd_LES_Smago_VEF, Modele_turbulence_hyd_LES_Wale_VEF, and Modele_turbulence_hyd_Longueur_Melange_VEF.
References Param::ajouter(), Param::ajouter_flag(), Param::ajouter_non_std(), and Param::REQUIRED.
Referenced by readOn(), Modele_turbulence_hyd_2_eq_base::set_param(), Modele_turbulence_hyd_combinaison::set_param(), Modele_turbulence_hyd_0_eq_base::set_param(), and Modele_turbulence_hyd_LES_base::set_param().
lire_motcle_non_standard()
int Modele_turbulence_hyd_base::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
< liste stockant tous les noms de frontiere du domaine
Reimplemented from Objet_U.
Reimplemented in Modele_turbulence_hyd_LES_selectif_mod_VDF, Modele_turbulence_hyd_LES_SMAGO_DYN_VDF, Modele_turbulence_hyd_LES_VDF, Modele_turbulence_hyd_K_Eps, Modele_turbulence_hyd_K_Eps_2_Couches, Modele_turbulence_hyd_K_Eps_Bas_Reynolds, Modele_turbulence_hyd_K_Eps_Bicephale, Modele_turbulence_hyd_K_Eps_Realisable, Modele_turbulence_hyd_K_Eps_Realisable_Bicephale, Modele_turbulence_hyd_K_Omega, Modele_turbulence_hyd_RANS_Bicephale_base, and Modele_turbulence_hyd_Longueur_Melange_VEF.
References Frontiere_32_64< _SIZE_ >::add(), TRUST_List< _CLASSE_ >::add(), boundaries_, boundaries_list_, Nom::contient(), Probleme_base::domaine(), dt_impr_ustar_, dt_impr_ustar_mean_only_, equation(), Process::exit(), Domaine_32_64< _SIZE_ >::frontiere(), Probleme_U::le_nom(), Domaine_base::le_nom(), Frontiere_32_64< _SIZE_ >::le_nom(), loipar_, Domaine_32_64< _SIZE_ >::nb_front_Cl(), Objet_U::nom_du_cas(), nom_fichier_, Equation_base::probleme(), Objet_U::que_suis_je(), Turbulence_paroi_base::typer_lire_turbulence_paroi(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::lire_motcle_non_standard(), Modele_turbulence_hyd_LES_VDF::lire_motcle_non_standard(), Modele_turbulence_hyd_K_Eps::lire_motcle_non_standard(), Modele_turbulence_hyd_K_Eps_2_Couches::lire_motcle_non_standard(), Modele_turbulence_hyd_K_Eps_Bas_Reynolds::lire_motcle_non_standard(), Modele_turbulence_hyd_K_Eps_Realisable::lire_motcle_non_standard(), Modele_turbulence_hyd_K_Omega::lire_motcle_non_standard(), Modele_turbulence_hyd_RANS_Bicephale_base::lire_motcle_non_standard(), and Modele_turbulence_hyd_Longueur_Melange_VEF::lire_motcle_non_standard().
preparer_calcul()
int Modele_turbulence_hyd_base::preparer_calcul () virtual
Prepare le calcul.
Initialise la loi de paroi. Remplit le champ wall_length en cas de post traitemetn de la distance_paroi
Returns
(int) code de retour de Turbulence_paroi::init_lois_paroi()
Reimplemented in Modele_turbulence_hyd_LES_SMAGO_DYN_VDF, Modele_turbulence_hyd_combinaison, Modele_turbulence_hyd_K_Eps, Modele_turbulence_hyd_K_Eps_2_Couches, Modele_turbulence_hyd_K_Eps_Bas_Reynolds, Modele_turbulence_hyd_K_Eps_Bicephale, Modele_turbulence_hyd_K_Eps_Realisable, Modele_turbulence_hyd_K_Eps_Realisable_Bicephale, Modele_turbulence_hyd_K_Omega, Modele_turbulence_hyd_LES_base, Modele_turbulence_hyd_Longueur_Melange_VDF, and Modele_turbulence_hyd_Longueur_Melange_VEF.
References boundaries_, boundaries_list_, Nom::contient(), equation(), Turbulence_paroi_base::imprimer_premiere_ligne_ustar(), Turbulence_paroi_base::init_lois_paroi(), lire_distance_paroi(), loipar_, nom_fichier_, Postraitement::noms_champs_a_post(), and Objet_U_ptr::non_nul().
Referenced by Navier_Stokes_Turbulent_ALE::preparer_calcul(), Navier_Stokes_FT_Disc::preparer_calcul(), Modele_turbulence_hyd_combinaison::preparer_calcul(), Modele_turbulence_hyd_K_Eps::preparer_calcul(), Modele_turbulence_hyd_K_Eps_2_Couches::preparer_calcul(), Modele_turbulence_hyd_K_Eps_Bicephale::preparer_calcul(), Modele_turbulence_hyd_K_Eps_Realisable::preparer_calcul(), Modele_turbulence_hyd_K_Eps_Realisable_Bicephale::preparer_calcul(), Modele_turbulence_hyd_K_Omega::preparer_calcul(), Navier_Stokes_IBM_Turbulent::preparer_calcul(), Navier_Stokes_Turbulent::preparer_calcul(), Modele_turbulence_hyd_LES_base::preparer_calcul(), Modele_turbulence_hyd_Longueur_Melange_VDF::preparer_calcul(), and Modele_turbulence_hyd_Longueur_Melange_VEF::preparer_calcul().
initTimeStep()
bool Modele_turbulence_hyd_base::initTimeStep (double dt) virtual
Reimplemented in Modele_turbulence_hyd_K_Eps, Modele_turbulence_hyd_K_Eps_2_Couches, Modele_turbulence_hyd_K_Eps_Bas_Reynolds, Modele_turbulence_hyd_K_Eps_Bicephale, Modele_turbulence_hyd_K_Eps_Realisable, Modele_turbulence_hyd_K_Eps_Realisable_Bicephale, and Modele_turbulence_hyd_K_Omega.
Referenced by Navier_Stokes_Turbulent_ALE::initTimeStep(), Navier_Stokes_IBM_Turbulent::initTimeStep(), and Navier_Stokes_Turbulent::initTimeStep().
mettre_a_jour()
virtual void Modele_turbulence_hyd_base::mettre_a_jour (double) pure virtual
Implemented in Modele_turbulence_hyd_LES_SMAGO_DYN_VDF, Modele_turbulence_hyd_combinaison, Modele_turbulence_hyd_K_Eps, Modele_turbulence_hyd_K_Eps_2_Couches, Modele_turbulence_hyd_K_Eps_Bas_Reynolds, Modele_turbulence_hyd_K_Eps_Bicephale, Modele_turbulence_hyd_K_Eps_Realisable, Modele_turbulence_hyd_K_Eps_Realisable_Bicephale, Modele_turbulence_hyd_K_Omega, Modele_turbulence_hyd_0_eq_base, and Modele_turbulence_hyd_null.
Referenced by Navier_Stokes_Turbulent_ALE::mettre_a_jour(), Navier_Stokes_IBM_Turbulent::mettre_a_jour(), and Navier_Stokes_Turbulent::mettre_a_jour().
discretiser()
void Modele_turbulence_hyd_base::discretiser () virtual
Discretise le modele de turbulence.
Reimplemented in Modele_turbulence_hyd_LES_selectif_mod_VDF, Modele_turbulence_hyd_LES_selectif_VDF, Modele_turbulence_hyd_LES_1elt_selectif_mod_VEF, Modele_turbulence_hyd_LES_Fst_sel_VEF, and Modele_turbulence_hyd_0_eq_base.
References Champs_compris_T< FIELD_TYPE >::ajoute_champ(), champs_compris_, Discretisation_base::discretiser_champ(), discretiser_corr_visc_turb(), discretiser_visc_turb(), la_viscosite_turbulente_, mon_equation_, and wall_length_.
Referenced by Modele_turbulence_hyd_0_eq_base::discretiser(), and Navier_Stokes_Turbulent_ALE::lire_motcle_non_standard().
discretiser_visc_turb()
void Modele_turbulence_hyd_base::discretiser_visc_turb (const Schema_Temps_base & sch, Domaine_dis_base & z, TRUST_Deriv< Champ_Fonc_base > & ch) const
References Discretisation_base::discretiser_champ(), equation(), Probleme_base::is_dilatable(), mon_equation_, Equation_base::probleme(), and Schema_Temps_base::temps_courant().
Referenced by discretiser().
discretiser_corr_visc_turb()
void Modele_turbulence_hyd_base::discretiser_corr_visc_turb (const Schema_Temps_base & sch, Domaine_dis_base & z, TRUST_Deriv< Champ_Fonc_base > & ch) const
References Discretisation_base::discretiser_champ(), mon_equation_, and Schema_Temps_base::temps_courant().
Referenced by discretiser().
discretiser_K()
void Modele_turbulence_hyd_base::discretiser_K (const Schema_Temps_base & sch, Domaine_dis_base & z, TRUST_Deriv< Champ_Fonc_base > & ch) const
References Discretisation_base::discretiser_champ(), mon_equation_, and Schema_Temps_base::temps_courant().
Referenced by Modele_turbulence_hyd_0_eq_base::discretiser().
completer()
virtual void Modele_turbulence_hyd_base::completer () inline virtual
Reimplemented in Modele_turbulence_hyd_combinaison, Modele_turbulence_hyd_K_Eps_2_Couches, Modele_turbulence_hyd_K_Eps_Bas_Reynolds, Modele_turbulence_hyd_RANS_Bicephale_base, Modele_turbulence_hyd_RANS_K_Eps_base, Modele_turbulence_hyd_RANS_K_Omega_base, Modele_turbulence_hyd_0_eq_base, and Modele_turbulence_hyd_LES_base.
Referenced by Navier_Stokes_Turbulent_ALE::completer(), Navier_Stokes_IBM_Turbulent::completer(), and Navier_Stokes_Turbulent::completer().
associer_eqn()
void Modele_turbulence_hyd_base::associer_eqn (const Equation_base & eqn)
Associe l'equation passe en parametre au modele de turbulence.
Parameters
(Equation_base& eqn) l'equation a laquelle l'objet s'associe
References mon_equation_.
Referenced by Navier_Stokes_Turbulent_ALE::lire_motcle_non_standard().
associer()
virtual void Modele_turbulence_hyd_base::associer (const Domaine_dis_base & , const Domaine_Cl_dis_base &) inline virtual
Reimplemented in Modele_turbulence_hyd_0_eq_base, Modele_turbulence_hyd_LES_DSGS_VDF, and Modele_turbulence_hyd_LES_SMAGO_DYN_VDF.
Referenced by Navier_Stokes_Turbulent_ALE::lire_motcle_non_standard().
reprendre()
int Modele_turbulence_hyd_base::reprendre (Entree & is) override virtual
Reprend la loi de paroi.
Parameters
(Entree&) un flot d'entree
Returns
(int) renvoie toujours 0
Reimplemented from Objet_U.
Reimplemented in Modele_turbulence_hyd_combinaison, Modele_turbulence_hyd_RANS_Bicephale_base, Modele_turbulence_hyd_RANS_K_Eps_base, Modele_turbulence_hyd_RANS_K_Omega_base, and Modele_turbulence_hyd_LES_base.
References loipar_, Objet_U_ptr::non_nul(), and Turbulence_paroi_base::reprendre().
Referenced by Navier_Stokes_Turbulent_ALE::reprendre(), Navier_Stokes_IBM_Turbulent::reprendre(), Navier_Stokes_Turbulent::reprendre(), Modele_turbulence_hyd_combinaison::reprendre(), Modele_turbulence_hyd_RANS_Bicephale_base::reprendre(), Modele_turbulence_hyd_RANS_K_Eps_base::reprendre(), Modele_turbulence_hyd_RANS_K_Omega_base::reprendre(), and Modele_turbulence_hyd_LES_base::reprendre().
creer_champ()
void Modele_turbulence_hyd_base::creer_champ (const Motcle & motlu) override virtual
Implements Champs_compris_interface.
References Turbulence_paroi_base::creer_champ(), loipar_, and Objet_U_ptr::non_nul().
Referenced by Navier_Stokes_Turbulent_ALE::creer_champ(), Navier_Stokes_IBM_Turbulent::creer_champ(), and Navier_Stokes_Turbulent::creer_champ().
get_champ()
const Champ_base & Modele_turbulence_hyd_base::get_champ (const Motcle & nom) const override virtual
Implements Champs_compris_interface.
Reimplemented in Modele_turbulence_hyd_K_Eps, Modele_turbulence_hyd_K_Eps_Bas_Reynolds, Modele_turbulence_hyd_K_Eps_Bicephale, Modele_turbulence_hyd_K_Eps_Realisable, Modele_turbulence_hyd_K_Eps_Realisable_Bicephale, Modele_turbulence_hyd_RANS_Bicephale_base, Modele_turbulence_hyd_RANS_K_Eps_base, and Modele_turbulence_hyd_RANS_K_Omega_base.
References champs_compris_, Nom::getString(), Turbulence_paroi_base::has_champ(), Champs_compris_T< FIELD_TYPE >::has_champ(), loipar_, and Objet_U_ptr::non_nul().
get_noms_champs_postraitables()
void Modele_turbulence_hyd_base::get_noms_champs_postraitables (Noms & nom, Option opt = NONE) const override virtual
Implements Champs_compris_interface.
Reimplemented in Modele_turbulence_hyd_K_Eps, Modele_turbulence_hyd_K_Eps_Bas_Reynolds, Modele_turbulence_hyd_K_Eps_Bicephale, Modele_turbulence_hyd_K_Eps_Realisable, Modele_turbulence_hyd_K_Eps_Realisable_Bicephale, Modele_turbulence_hyd_RANS_Bicephale_base, Modele_turbulence_hyd_RANS_K_Eps_base, and Modele_turbulence_hyd_RANS_K_Omega_base.
References TRUST_Vector< _CLASSE_ >::add(), champs_compris_, Turbulence_paroi_base::get_noms_champs_postraitables(), Champs_compris_T< FIELD_TYPE >::liste_noms_compris(), loipar_, Objet_U_ptr::non_nul(), and Objet_U::que_suis_je().
Referenced by Navier_Stokes_Turbulent_ALE::get_noms_champs_postraitables(), Modele_turbulence_hyd_RANS_Bicephale_base::get_noms_champs_postraitables(), Modele_turbulence_hyd_RANS_K_Eps_base::get_noms_champs_postraitables(), Modele_turbulence_hyd_RANS_K_Omega_base::get_noms_champs_postraitables(), Navier_Stokes_IBM_Turbulent::get_noms_champs_postraitables(), and Navier_Stokes_Turbulent::get_noms_champs_postraitables().
has_champ() [1/2]
bool Modele_turbulence_hyd_base::has_champ (const Motcle & nom, TRUST_Ref< Champ_base * > & ref_champ) const override virtual
Implements Champs_compris_interface.
Reimplemented in Modele_turbulence_hyd_K_Eps, Modele_turbulence_hyd_K_Eps_Bas_Reynolds, Modele_turbulence_hyd_K_Eps_Bicephale, Modele_turbulence_hyd_K_Eps_Realisable, Modele_turbulence_hyd_K_Eps_Realisable_Bicephale, Modele_turbulence_hyd_RANS_Bicephale_base, Modele_turbulence_hyd_RANS_K_Eps_base, and Modele_turbulence_hyd_RANS_K_Omega_base.
References champs_compris_, Turbulence_paroi_base::has_champ(), Champs_compris_T< FIELD_TYPE >::has_champ(), loipar_, and Objet_U_ptr::non_nul().
Referenced by Navier_Stokes_Turbulent_ALE::get_champ(), Modele_turbulence_hyd_RANS_Bicephale_base::get_champ(), Modele_turbulence_hyd_RANS_K_Eps_base::get_champ(), Modele_turbulence_hyd_RANS_K_Omega_base::get_champ(), Navier_Stokes_IBM_Turbulent::get_champ(), Navier_Stokes_Turbulent::get_champ(), Navier_Stokes_Turbulent_ALE::has_champ(), Modele_turbulence_hyd_RANS_Bicephale_base::has_champ(), Modele_turbulence_hyd_RANS_K_Eps_base::has_champ(), Modele_turbulence_hyd_RANS_K_Omega_base::has_champ(), Navier_Stokes_IBM_Turbulent::has_champ(), and Navier_Stokes_Turbulent::has_champ().
has_champ() [2/2]
bool Modele_turbulence_hyd_base::has_champ (const Motcle & nom) const override virtual
Implements Champs_compris_interface.
Reimplemented in Modele_turbulence_hyd_K_Eps, Modele_turbulence_hyd_K_Eps_Bas_Reynolds, Modele_turbulence_hyd_K_Eps_Bicephale, Modele_turbulence_hyd_K_Eps_Realisable, Modele_turbulence_hyd_K_Eps_Realisable_Bicephale, Modele_turbulence_hyd_RANS_Bicephale_base, Modele_turbulence_hyd_RANS_K_Eps_base, and Modele_turbulence_hyd_RANS_K_Omega_base.
References champs_compris_, Turbulence_paroi_base::has_champ(), Champs_compris_T< FIELD_TYPE >::has_champ(), loipar_, and Objet_U_ptr::non_nul().
champs_compris()
Champs_compris & Modele_turbulence_hyd_base::champs_compris () inline
References champs_compris_.
imprimer()
void Modele_turbulence_hyd_base::imprimer (Sortie & os) const virtual
Effectue l'impression si cela est necessaire.
Returns
renvoie toujours 1
Reimplemented in Modele_turbulence_hyd_K_Eps_Bas_Reynolds, Modele_turbulence_hyd_0_eq_base, Modele_turbulence_hyd_combinaison, and Modele_turbulence_hyd_LES_base.
References boundaries_, boundaries_list_, dt_impr_ustar_, dt_impr_ustar_mean_only_, Turbulence_paroi_base::imprimer_ustar(), Turbulence_paroi_base::imprimer_ustar_mean_only(), limpr_ustar(), loipar_, mon_equation_, nom_fichier_, Objet_U_ptr::non_nul(), Schema_Temps_base::pas_de_temps(), Schema_Temps_base::temps_courant(), and Schema_Temps_base::temps_precedent().
Referenced by Navier_Stokes_Turbulent_ALE::imprimer(), Navier_Stokes_IBM_Turbulent::imprimer(), Navier_Stokes_Turbulent::imprimer(), Modele_turbulence_hyd_0_eq_base::imprimer(), Modele_turbulence_hyd_combinaison::imprimer(), and Modele_turbulence_hyd_LES_base::imprimer().
a_faire()
void Modele_turbulence_hyd_base::a_faire (Sortie & os) const
Effectue l'ecriture d'une identite si cela est necessaire.
References Probleme_base::domaine(), equation(), Sortie::flush(), Equation_base::inconnue(), EcritureLectureSpecial::is_ecriture_special(), Domaine_base::le_nom(), Equation_base::probleme(), Objet_U::que_suis_je(), and Champ_base::temps().
Referenced by sauvegarder().
sauvegarder()
int Modele_turbulence_hyd_base::sauvegarder (Sortie & os) const override virtual
Sauvegarde le modele de turbulence sur un flot de sortie.
Sauvegarde le type de l'objet.
Parameters
(Sortie& os) un flot de sortie
Returns
(int) renvoie toujours 1
Reimplemented from Objet_U.
Reimplemented in Modele_turbulence_hyd_null, Modele_turbulence_hyd_RANS_Bicephale_base, Modele_turbulence_hyd_RANS_K_Eps_base, and Modele_turbulence_hyd_RANS_K_Omega_base.
References a_faire(), TRUST_2_PDI::is_PDI_checkpoint(), loipar_, mon_equation_, Process::mp_sum(), Objet_U_ptr::non_nul(), Objet_U::que_suis_je(), Turbulence_paroi_base::sauvegarder(), TRUSTVect< _TYPE_, _SIZE_ >::size(), and Nom::substr_old().
Referenced by Navier_Stokes_Turbulent_ALE::sauvegarder(), Navier_Stokes_IBM_Turbulent::sauvegarder(), Navier_Stokes_Turbulent::sauvegarder(), Modele_turbulence_hyd_RANS_Bicephale_base::sauvegarder(), Modele_turbulence_hyd_RANS_K_Eps_base::sauvegarder(), and Modele_turbulence_hyd_RANS_K_Omega_base::sauvegarder().
data_a_sauvegarder()
std::vector< YAML_data > Modele_turbulence_hyd_base::data_a_sauvegarder () const virtual
for PDI IO: retrieve name, type and dimensions of the fields to save/restore
Reimplemented in Modele_turbulence_hyd_RANS_Bicephale_base, Modele_turbulence_hyd_RANS_K_Eps_base, and Modele_turbulence_hyd_RANS_K_Omega_base.
References Turbulence_paroi_base::data_a_sauvegarder(), loipar_, and Objet_U_ptr::non_nul().
Referenced by Navier_Stokes_Turbulent_ALE::data_a_sauvegarder(), Modele_turbulence_hyd_RANS_Bicephale_base::data_a_sauvegarder(), Modele_turbulence_hyd_RANS_K_Eps_base::data_a_sauvegarder(), Modele_turbulence_hyd_RANS_K_Omega_base::data_a_sauvegarder(), Navier_Stokes_IBM_Turbulent::data_a_sauvegarder(), and Navier_Stokes_Turbulent::data_a_sauvegarder().
limpr_ustar()
int Modele_turbulence_hyd_base::limpr_ustar (double temps_courant, double temps_prec, double dt, double dt_ustar) const
References mon_equation_, Schema_Temps_base::nb_pas_dt(), Schema_Temps_base::nb_pas_dt_max_atteint(), Schema_Temps_base::stationnaire_atteint(), Schema_Temps_base::stop_lu(), Schema_Temps_base::temps_cpu_max_atteint(), and Schema_Temps_base::temps_final_atteint().
Referenced by imprimer(), and Modele_turbulence_hyd_0_eq_base::imprimer().
get_Cmu()
double Modele_turbulence_hyd_base::get_Cmu () const inline
References LeCmu_.
lire_distance_paroi()
void Modele_turbulence_hyd_base::lire_distance_paroi ()
Lit le fichier dom_Wall_length.
xyz pour remplir le champs wall_length en vue d'un post-traitement de distance_paroi
References Probleme_base::domaine(), equation(), Process::exit(), Domaine_base::le_nom(), EcritureLectureSpecial::lecture_special(), LecFicDiffuse::ouvrir(), Equation_base::probleme(), Lec_Diffuse_base::set_bin(), Champ_Don_base::valeurs(), and wall_length_.
Referenced by preparer_calcul().
limiter_viscosite_turbulente()
void Modele_turbulence_hyd_base::limiter_viscosite_turbulente ()
References Operateur_Diff_base::calculer_borne_locale(), Champ_base::changer_temps(), Domaine_dis_base::domaine(), Equation_base::domaine_dis(), Operateur_Conv_base::dt_stab_conv(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), equation(), Process::je_suis_maitre(), la_viscosite_turbulente_, mon_equation_, Domaine_32_64< _SIZE_ >::nb_elem(), TRUSTVect< _TYPE_, _SIZE_ >::size(), Champ_Don_base::valeurs(), Debog::verifier(), TRUSTArray< _TYPE_, _SIZE_ >::view_ro(), and viscosite_turbulente().
Referenced by Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::mettre_a_jour(), Modele_turbulence_hyd_combinaison::mettre_a_jour(), and Modele_turbulence_hyd_0_eq_base::mettre_a_jour().
Member Data Documentation
info_obj
const Type_info Modele_turbulence_hyd_base::info_obj static
LeCmu_
double Modele_turbulence_hyd_base::LeCmu_ = CMU protected
Referenced by Modele_turbulence_hyd_K_Eps_Bicephale::fill_turbulent_viscosity_tab(), Modele_turbulence_hyd_K_Eps::fill_turbulent_viscosity_tab(), get_Cmu(), Modele_turbulence_hyd_K_Eps::mettre_a_jour(), Modele_turbulence_hyd_K_Eps_2_Couches::mettre_a_jour(), Modele_turbulence_hyd_K_Eps_Bicephale::mettre_a_jour(), Modele_turbulence_hyd_K_Eps_Realisable::mettre_a_jour(), Modele_turbulence_hyd_K_Eps::preparer_calcul(), Modele_turbulence_hyd_K_Eps_Bicephale::preparer_calcul(), Modele_turbulence_hyd_K_Eps_Realisable::preparer_calcul(), Modele_turbulence_hyd_K_Eps::set_param(), and Modele_turbulence_hyd_K_Eps_Bicephale::set_param().
la_viscosite_turbulente_
TRUST_Deriv< Champ_Fonc_base > Modele_turbulence_hyd_base::la_viscosite_turbulente_ protected
Referenced by Modele_turbulence_hyd_LES_selectif_mod_VDF::a_pour_Champ_Fonc(), Modele_turbulence_hyd_LES_selectif_VDF::a_pour_Champ_Fonc(), Modele_turbulence_hyd_LES_1elt_selectif_mod_VEF::a_pour_Champ_Fonc(), Modele_turbulence_hyd_LES_Fst_sel_VEF::a_pour_Champ_Fonc(), Modele_turbulence_hyd_0_eq_base::a_pour_Champ_Fonc(), Modele_turbulence_hyd_LES_base::calculer_energie_cinetique_turb(), Modele_turbulence_hyd_LES_axi_VDF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_DSGS_VDF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_VDF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_1elt_VEF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_Fst_VEF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_VEF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_combinaison::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_Smago_VDF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_Wale_VDF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_Longueur_Melange_VDF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_Smago_VEF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_Wale_VEF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_Longueur_Melange_VEF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_K_Eps::calculer_viscosite_turbulente(), Modele_turbulence_hyd_K_Eps_2_Couches::calculer_viscosite_turbulente(), Modele_turbulence_hyd_K_Eps_Bas_Reynolds::calculer_viscosite_turbulente(), Modele_turbulence_hyd_K_Eps_Bicephale::calculer_viscosite_turbulente(), Modele_turbulence_hyd_K_Eps_Realisable::calculer_viscosite_turbulente(), Modele_turbulence_hyd_K_Eps_Realisable_Bicephale::calculer_viscosite_turbulente(), Modele_turbulence_hyd_K_Omega::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::controler_grandeurs_turbulentes(), discretiser(), Modele_turbulence_hyd_0_eq_base::imprimer(), limiter_viscosite_turbulente(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::mettre_a_jour(), Modele_turbulence_hyd_combinaison::mettre_a_jour(), Modele_turbulence_hyd_K_Eps::mettre_a_jour(), Modele_turbulence_hyd_K_Eps_Bas_Reynolds::mettre_a_jour(), Modele_turbulence_hyd_K_Eps_Bicephale::mettre_a_jour(), Modele_turbulence_hyd_K_Eps_Realisable::mettre_a_jour(), Modele_turbulence_hyd_K_Eps_Realisable_Bicephale::mettre_a_jour(), Modele_turbulence_hyd_K_Omega::mettre_a_jour(), Modele_turbulence_hyd_0_eq_base::mettre_a_jour(), Modele_turbulence_hyd_K_Eps::preparer_calcul(), Modele_turbulence_hyd_K_Eps_2_Couches::preparer_calcul(), Modele_turbulence_hyd_K_Eps_Bicephale::preparer_calcul(), Modele_turbulence_hyd_K_Omega::preparer_calcul(), and viscosite_turbulente().
wall_length_
TRUST_Deriv< Champ_Fonc_base > Modele_turbulence_hyd_base::wall_length_ protected
Referenced by Modele_turbulence_hyd_Longueur_Melange_VEF::calculer_f_amortissement(), Modele_turbulence_hyd_Longueur_Melange_VEF::calculer_viscosite_turbulente(), discretiser(), Modele_turbulence_hyd_0_eq_base::imprimer(), lire_distance_paroi(), and Modele_turbulence_hyd_Longueur_Melange_VEF::lire_distance_paroi().
mon_equation_
TRUST_Ref< Equation_base *> Modele_turbulence_hyd_base::mon_equation_ protected
Referenced by associer_eqn(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calcul_voisins(), Modele_turbulence_hyd_LES_DSGS_VDF::calculer_cell_cent_vel(), Modele_turbulence_hyd_LES_VDF::calculer_energie_cinetique_turb(), Modele_turbulence_hyd_LES_base::calculer_energie_cinetique_turb(), Modele_turbulence_hyd_Longueur_Melange_base::calculer_energie_cinetique_turb(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calculer_energie_cinetique_turb(), Modele_turbulence_hyd_Longueur_Melange_VEF::calculer_f_amortissement(), Modele_turbulence_hyd_LES_VDF::calculer_fonction_structure(), Modele_turbulence_hyd_LES_1elt_VEF::calculer_fonction_structure(), Modele_turbulence_hyd_LES_VEF::calculer_fonction_structure(), Modele_turbulence_hyd_LES_axi_VDF::calculer_fonction_structure(), Modele_turbulence_hyd_LES_Wale_VDF::calculer_OP1_OP2(), Modele_turbulence_hyd_LES_Fst_VEF::calculer_racine(), Modele_turbulence_hyd_LES_Smago_VDF::calculer_S_barre(), Modele_turbulence_hyd_LES_Smago_VEF::calculer_S_barre(), Modele_turbulence_hyd_LES_Smago_filtre_VEF::calculer_S_barre(), Modele_turbulence_hyd_LES_DSGS_VDF::calculer_Sij(), Modele_turbulence_hyd_Longueur_Melange_VDF::calculer_Sij2(), Modele_turbulence_hyd_Longueur_Melange_VEF::calculer_Sij2(), Modele_turbulence_hyd_LES_axi_VDF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_DSGS_VDF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_VDF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_1elt_VEF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_Fst_VEF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_VEF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_Smago_VDF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_Wale_VDF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_Longueur_Melange_VDF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_Smago_VEF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_Wale_VEF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_Longueur_Melange_VEF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_K_Eps::calculer_viscosite_turbulente(), Modele_turbulence_hyd_K_Eps_Bicephale::calculer_viscosite_turbulente(), Modele_turbulence_hyd_0_eq_base::completer(), Modele_turbulence_hyd_LES_selectif_mod_VDF::cutoff(), Modele_turbulence_hyd_LES_selectif_VDF::cutoff(), Modele_turbulence_hyd_LES_1elt_selectif_mod_VEF::cutoff(), Modele_turbulence_hyd_LES_Fst_sel_VEF::cutoff(), discretiser(), Modele_turbulence_hyd_LES_selectif_mod_VDF::discretiser(), Modele_turbulence_hyd_LES_selectif_VDF::discretiser(), Modele_turbulence_hyd_LES_1elt_selectif_mod_VEF::discretiser(), Modele_turbulence_hyd_LES_Fst_sel_VEF::discretiser(), Modele_turbulence_hyd_0_eq_base::discretiser(), discretiser_corr_visc_turb(), discretiser_K(), discretiser_visc_turb(), equation(), imprimer(), Modele_turbulence_hyd_0_eq_base::imprimer(), limiter_viscosite_turbulente(), limpr_ustar(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::mettre_a_jour(), Modele_turbulence_hyd_0_eq_base::mettre_a_jour(), Modele_turbulence_hyd_RANS_Bicephale_base::reprendre(), Modele_turbulence_hyd_RANS_K_Eps_base::reprendre(), Modele_turbulence_hyd_RANS_K_Omega_base::reprendre(), sauvegarder(), and Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::stabilise_moyenne_euler_lagrange().
loipar_
TRUST_Deriv< Turbulence_paroi_base > Modele_turbulence_hyd_base::loipar_ protected
Referenced by creer_champ(), data_a_sauvegarder(), get_champ(), get_noms_champs_postraitables(), has_champ(), has_loi_paroi_hyd(), imprimer(), lire_motcle_non_standard(), loi_paroi(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::mettre_a_jour(), Modele_turbulence_hyd_combinaison::mettre_a_jour(), Modele_turbulence_hyd_0_eq_base::mettre_a_jour(), preparer_calcul(), Modele_turbulence_hyd_null::readOn(), reprendre(), sauvegarder(), utiliser_loi_paroi(), Modele_turbulence_hyd_2_eq_base::verifie_loi_paroi(), Modele_turbulence_hyd_K_Eps::verifie_loi_paroi(), Modele_turbulence_hyd_K_Eps_Bicephale::verifie_loi_paroi(), Modele_turbulence_hyd_K_Eps_Realisable::verifie_loi_paroi(), Modele_turbulence_hyd_K_Eps_Realisable_Bicephale::verifie_loi_paroi(), and Modele_turbulence_hyd_LES_base::verifie_loi_paroi_diphasique().
dt_impr_ustar_
double Modele_turbulence_hyd_base::dt_impr_ustar_ = 1.e20 protected
Referenced by imprimer(), Modele_turbulence_hyd_0_eq_base::imprimer(), and lire_motcle_non_standard().
dt_impr_ustar_mean_only_
double Modele_turbulence_hyd_base::dt_impr_ustar_mean_only_ = 1.e20 protected
Referenced by imprimer(), Modele_turbulence_hyd_0_eq_base::imprimer(), and lire_motcle_non_standard().
boundaries_
int Modele_turbulence_hyd_base::boundaries_ = 0 protected
Referenced by imprimer(), lire_motcle_non_standard(), and preparer_calcul().
boundaries_list_
TRUST_List< Nom > Modele_turbulence_hyd_base::boundaries_list_ protected
Referenced by imprimer(), lire_motcle_non_standard(), and preparer_calcul().
nom_fichier_
Nom Modele_turbulence_hyd_base::nom_fichier_ = "" protected
Referenced by imprimer(), lire_motcle_non_standard(), and preparer_calcul().
champs_compris_
Champs_compris Modele_turbulence_hyd_base::champs_compris_ protected
Referenced by Modele_turbulence_hyd_LES_DSGS_VDF::associer(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::associer(), champs_compris(), discretiser(), Modele_turbulence_hyd_0_eq_base::discretiser(), get_champ(), get_noms_champs_postraitables(), and has_champ().