TrioCFD: Champ_Inc_base Class Reference
Champ_Inc_base Class Reference abstract
#include <Champ_Inc_base.h>
Public Member Functions
Champ_base & affecter_ (const Champ_base &) override
Champ_base & affecter_compo (const Champ_base &, int compo) override
virtual void associer_eqn (const Equation_base &)
Champ_Inc_base & avancer (int i=1)
double changer_temps (const double temps) override
double changer_temps_futur (double, int i=1)
double changer_temps_passe (double, int i=1)
virtual int fixer_nb_valeurs_temporelles (int)
DoubleTab & futur (int i=1) override
const Type_info * get_info () const override
int lire_donnees (Entree &)
void mettre_a_jour (double temps) override
virtual int nb_valeurs_temporelles () const
DoubleTab & passe (int i=1) override
Champ_Inc_base & reculer (int i=1)
double recuperer_temps_futur (int i=1) const
double recuperer_temps_passe (int i=1) const
virtual DoubleTab & remplir_coord_noeuds_compo (DoubleTab &, int) const
virtual int remplir_coord_noeuds_et_polys (DoubleTab &, IntVect &) const
virtual int remplir_coord_noeuds_et_polys_compo (DoubleTab &, IntVect &, int) const
int reprendre (Entree &) override
void resetTime (double time) override
int sauvegarder (Sortie &) const override
DoubleTab & trace (const Frontiere_dis_base &, DoubleTab &, double, int distant) const override
DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const override
DoubleTab & valeur_aux (const DoubleTab &positions, DoubleTab &valeurs) const override
DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const override
DoubleTab & valeurs () override
const DoubleTab & valeurs (double temps) const override
DoubleTab & valeurs (double temps) override
Public Member Functions inherited from Champ_base
Champ_base & affecter (const Champ_base &)
Champ_base ()
virtual double changer_temps (const double t)
const Type_info * get_info () const override
double temps () const
virtual DoubleTab & trace (const Frontiere_dis_base &, DoubleTab &, double, int distant) const
virtual DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const
virtual double valeur_a_compo (const DoubleVect &position, int ncomp) const
virtual DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &valeurs, int le_poly) const
virtual double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const
virtual DoubleVect & valeur_a_sommet (int, const Domaine &, DoubleVect &) const
virtual DoubleTab & valeur_aux (const DoubleTab &positions, DoubleTab &valeurs) const
virtual DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const
virtual DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const
virtual DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp) const
Public Member Functions inherited from Field_base
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
virtual void fixer_nb_comp (int i)
virtual const Nom & fixer_nom_compo (const Nom &)
virtual const Nom & fixer_nom_compo (int, const Nom &)
virtual const Noms & fixer_noms_compo (const Noms &)
virtual const Nom & fixer_unite (const Nom &)
virtual const Nom & fixer_unite (int i, const Nom &)
virtual const Noms & fixer_unites (const Noms &)
const Type_info * get_info () const override
const Nom & nom_compo (int) const
void nommer (const Nom &) override
const Nom & unite () const
const Nom & unite (int) const
const Noms & unites () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Champ_Proto
int lire_dimension (Entree &, const Nom &)
int lire_dimension (int dim, const Nom &le_nom_)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Field_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
Classe de base des champs inconnues qui sont les champs calcules par une equation.
Un objet de type Roue est associe au Champ_Inc, cette roue permet de gerer le nombre de valeurs du temps pour lesquels le champ
doit rester en memoire. C'est le schema en temps qui guide le nombre de valeurs a garder.
Cette classe peut aussi servir a stocker des champs calcules a partir d'autres Champ_Inc. Dans ce cas, une fonction calculer_valeurs(...)
est appellee lors de mettre_a_jour() et doit remplir :
 - les valeurs du champ a l'instant courant;
 - les derivees de ces valeurs par rapport aux inconnues;
 - ses valeurs aux bords (stockees dans un tableau, car le champ n'a pas
   de CL associee);
OWN_PTR(Champ_Inc_base) est un morceaux d'equation car il herite de MorEqn.
See also
MorEqn OWN_PTR(Champ_Inc_base) Champ_base Ch_proto Equation_base, Classe abstraite, Methodes abstraites:, const Domaine_dis_base& associer_domaine_dis_base(const Domaine_dis_base&), const Domaine_dis_base& domaine_dis_base() const, DoubleTab& remplir_coord_noeuds(DoubleTab&) const
Constructor & Destructor Documentation
~Champ_Inc_base()
Champ_Inc_base::~Champ_Inc_base () override
Champ_Inc_base()
Champ_Inc_base::Champ_Inc_base () inline
Member Function Documentation
info()
const Type_info * Champ_Inc_base::info () static
get_info()
const Type_info * Champ_Inc_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Champ_base.
Reimplemented in Champ_Elem_PolyMAC, Champ_Elem_PolyMAC_P0, Champ_Elem_PolyMAC_P0P1NC, Champ_Face_PolyMAC, Champ_Face_PolyMAC_P0, Champ_Face_PolyMAC_P0P1NC, Champ_Som_PolyMAC, Champ_Face_VDF, Champ_P0_VDF, Champ_P0_VEF, Champ_P1_isoP1Bulle, Champ_P1NC, and Champ_Q1NC.
self_cast() [1/2]
Champ_Inc_base & Champ_Inc_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Champ_Inc_base & Champ_Inc_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Champ_Inc_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Champ_base.
Reimplemented in Champ_Elem_PolyMAC, Champ_Elem_PolyMAC_P0, Champ_Elem_PolyMAC_P0P1NC, Champ_Face_PolyMAC, Champ_Face_PolyMAC_P0, Champ_Face_PolyMAC_P0P1NC, Champ_Som_PolyMAC, Champ_Face_VDF, Champ_P0_VDF, Champ_P0_VEF, Champ_P1_isoP1Bulle, Champ_P1NC, and Champ_Q1NC.
References Champ_base::printOn().
readOn()
Entree & Champ_Inc_base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Champ_base.
Reimplemented in Champ_Elem_PolyMAC, Champ_Elem_PolyMAC_P0, Champ_Elem_PolyMAC_P0P1NC, Champ_Face_PolyMAC, Champ_Face_PolyMAC_P0, Champ_Face_PolyMAC_P0P1NC, Champ_Som_PolyMAC, Champ_Face_VDF, Champ_P0_VDF, Champ_P0_VEF, Champ_P1_isoP1Bulle, Champ_P1NC, and Champ_Q1NC.
References Champ_base::readOn().
fixer_nb_valeurs_nodales()
int Champ_Inc_base::fixer_nb_valeurs_nodales (int nb_noeuds) override virtual
Reimplemented from Champ_base.
Reimplemented in Champ_Elem_PolyMAC, Champ_Elem_PolyMAC_P0P1NC, Champ_Face_PolyMAC, Champ_Face_PolyMAC_P0, Champ_Face_PolyMAC_P0P1NC, Champ_Q1NC, Champ_P1NC, Champ_Face_VDF, and Champ_P1_isoP1Bulle.
References Process::exit(), and Objet_U::que_suis_je().
Referenced by Modele_turbulence_hyd_RANS_Gen< MODELE >::complete_viscosity_field(), and Champ_Fonc_reprise_IJK::readOn().
changer_temps()
double Champ_Inc_base::changer_temps (const double t) override virtual
Fixe le temps du champ.
Parameters
(double t) le nouveau temps
Returns
(double) le nouveau temps
Reimplemented from Champ_base.
References Roue::changer_temps(), les_valeurs, and Champ_base::temps_.
Referenced by Modele_turbulence_hyd_RANS_Gen< MODELE >::complete_viscosity_field(), Convection_Diffusion_Temperature_FT_Disc::compute_divergence_free_velocity_extension(), Fluide_reel_base::initialiser(), Transport_Interfaces_FT_Disc::mettre_a_jour(), mettre_a_jour(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::mettre_a_jour(), Op_Conv_VDF_base::mettre_a_jour(), Equation_base::preparer_calcul(), Navier_Stokes_FT_Disc::preparer_calcul(), Transport_Interfaces_FT_Disc::preparer_calcul(), Navier_Stokes_phase_field::preparer_calcul(), Navier_Stokes_IBM::preparer_calcul(), Navier_Stokes_std::preparer_calcul(), QDM_Multiphase::preparer_calcul(), resetTime(), and Transport_Interfaces_FT_Disc::transporter_sans_changement_topologie().
mettre_a_jour()
void Champ_Inc_base::mettre_a_jour (double un_temps) override virtual
Effectue une mise a jour en temps du champ inconnue.
WEC : Maintenant si on l'appelle 2 fois de suite avec le meme argument, la 2eme ne fait rien.
Parameters
(double temps) le nouveau temps
Reimplemented from Champ_base.
Reimplemented in Champ_Face_VDF, Champ_P1NC, and Champ_Elem_PolyMAC_P0.
References avancer(), changer_temps(), deriv_, Process::exit(), fonc_calc_, fonc_calc_init_, Field_base::le_nom(), les_valeurs, Roue::nb_cases(), obj_calc_, Champ_base::temps(), Champ_base::temps_, val_bord_, TRUST_Ref_Objet_U::valeur(), and valeurs().
Referenced by Navier_Stokes_std::calculer_la_pression_en_pa(), Modele_turbulence_hyd_0_eq_base::imprimer(), Pb_Dilatable_base::iterateTimeStep(), Equation_base::mettre_a_jour(), Convection_Diffusion_Temperature_FT_Disc::mettre_a_jour(), Navier_Stokes_std::mettre_a_jour(), QDM_Multiphase::mettre_a_jour(), Champ_Face_VDF::mettre_a_jour(), Champ_P1NC::mettre_a_jour(), Champ_Elem_PolyMAC_P0::mettre_a_jour(), Navier_Stokes_std_ALE::mettre_a_jour(), Equation_base::mettre_a_jour_champs_conserves(), Schema_Adams_Moulton_base::mettre_a_jour_equation(), and Schema_Backward_Differentiation_base::mettre_a_jour_equation().
reprendre()
int Champ_Inc_base::reprendre (Entree & fich) override virtual
Lecture d'un champ inconnue a partir d'un flot d'entree en vue d'une reprise.
Parameters
(Entree& fich) un flot d'entree
Returns
(int) renvoie toujours 1
Reimplemented from Objet_U.
Reimplemented in Champ_Elem_PolyMAC_P0, Champ_Elem_PolyMAC_P0P1NC, Champ_Face_PolyMAC_P0, and Champ_Face_PolyMAC_P0P1NC.
References TRUSTArray< _TYPE_, _SIZE_ >::addr(), Process::exit(), get_PDI_dname(), Nom::getChar(), EcritureLectureSpecial::is_lecture_special(), TRUST_2_PDI::is_PDI_restart(), TRUSTTab< _TYPE_, _SIZE_ >::jump(), EcritureLectureSpecial::lecture_special(), TRUSTTab< _TYPE_, _SIZE_ >::lit(), nb_valeurs_nodales(), Field_base::nom_, TRUST_2_PDI::read(), TRUST_2_PDI::share_TRUSTTab_dimensions(), and valeurs().
Referenced by Equation_base::reprendre(), Navier_Stokes_std::reprendre(), Champ_Elem_PolyMAC_P0::reprendre(), Champ_Elem_PolyMAC_P0P1NC::reprendre(), Champ_Face_PolyMAC_P0::reprendre(), Champ_Face_PolyMAC_P0P1NC::reprendre(), and Transport_Interfaces_FT_Disc_interne::reprendre().
sauvegarder()
int Champ_Inc_base::sauvegarder (Sortie & fich) const override virtual
Sauvegarde le champ inconnue sur un flot de sortie.
Ecrit un identifiant, les valeurs du champs, et la date (le temps au moment de la sauvegarde).
Parameters
(Sortie& fich) un flot de sortie
Returns
(int) returns the size of array
Reimplemented from Objet_U.
References TRUSTArray< _TYPE_, _SIZE_ >::addr(), Probleme_base::domaine(), TRUSTTab< _TYPE_, _SIZE_ >::ecrit(), EcritureLectureSpecial::ecriture_special(), MorEqn::equation(), Process::exit(), Sortie::flush(), get_PDI_dname(), Nom::getString(), EcritureLectureSpecial::is_ecriture_special(), TRUST_2_PDI::is_PDI_checkpoint(), Domaine_base::le_nom(), Field_base::nom_, PDI_save_type_, Equation_base::probleme(), Objet_U::que_suis_je(), Probleme_base::schema_temps(), TRUST_2_PDI::share_TRUSTTab_dimensions(), TRUST_2_PDI::share_type(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), Champ_base::temps_, Schema_Temps_base::temps_courant(), TRUST_2_PDI::TRUST_start_sharing(), and valeurs().
Referenced by Equation_base::sauvegarder(), Navier_Stokes_std::sauvegarder(), and Transport_Interfaces_FT_Disc_interne::sauvegarder().
affecter_compo()
Champ_base & Champ_Inc_base::affecter_compo (const Champ_base & ch, int compo) override virtual
Affectation d'une composante d'un OWN_PTR(Champ_base) quelconque (Champ_base) dans une composante d'un champ inconnue.
Parameters
(Champ_base& ch) la partie droite de l'affectation
(int compo) l'index de la composante a affecter
Returns
(Champ_base&) le resultat de l'affectation (avec upcast)
Implements Champ_base.
References remplir_coord_noeuds_compo(), remplir_coord_noeuds_et_polys_compo(), Champ_base::valeur_aux_compo(), Champ_base::valeur_aux_elems_compo(), and valeurs().
resetTime()
void Champ_Inc_base::resetTime (double time) override virtual
See comments in Probleme_base_interface_proto::resetTime_impl(). Here we force a new time value.
Implements Champ_base.
References changer_temps().
Referenced by Equation_base::resetTime(), and Navier_Stokes_std::resetTime().
affecter_()
Champ_base & Champ_Inc_base::affecter_ (const Champ_base & ch) override virtual
Affectation d'un OWN_PTR(Champ_base) generique (Champ_base) dans un champ inconnue.
Parameters
(Champ_base& ch) le champ partie droite de l'affectation
Returns
(Champ_base&) le resultat de l'affectation (*this)
Implements Champ_base.
Reimplemented in Champ_Face_PolyMAC, Champ_Face_PolyMAC_P0, Champ_Face_VDF, Champ_P1_isoP1Bulle, Champ_P1NC, Champ_Elem_PolyMAC, Champ_Elem_PolyMAC_P0, and Champ_Elem_PolyMAC_P0P1NC.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Process::exit(), les_valeurs, Roue::nb_cases(), TRUSTTab< _TYPE_, _SIZE_ >::ref_tab(), remplir_coord_noeuds(), Champ_base::valeur_aux(), and valeurs().
Referenced by Champ_Inc_P0_base::affecter_(), and Champ_P1NC::affecter_().
verifie_valeurs_cl()
void Champ_Inc_base::verifie_valeurs_cl () virtual
Reimplemented in Champ_Face_VDF, Champ_P1NC, and Champ_Q1NC.
Referenced by Equation_base::preparer_calcul().
valeurs() [1/4]
DoubleTab & Champ_Inc_base::valeurs () inline override virtual
Renvoie le tableau des valeurs du champ au temps courant.
Returns
(DoubleTab&) le tableau des valeurs du champ
Implements Champ_Proto.
References les_valeurs, and Roue::valeurs().
Referenced by Navier_Stokes_std::abortTimeStep(), Schema_Adams_Moulton_base::add_multi_timestep_data(), Schema_Backward_Differentiation_base::add_multi_timestep_data(), Champ_Face_VDF::affecter(), affecter_(), Champ_Face_PolyMAC::affecter_(), Champ_Face_PolyMAC_P0::affecter_(), Champ_Face_VDF::affecter_(), Champ_P1_isoP1Bulle::affecter_(), Champ_P1NC::affecter_(), Champ_Elem_DG::affecter_(), Champ_Elem_PolyMAC::affecter_(), Champ_Elem_PolyMAC_P0P1NC::affecter_(), affecter_compo(), Op_Diff_VDF_base::ajoute_terme_pour_axi(), Op_Dift_VDF_base::ajoute_terme_pour_axi_turb(), Operateur::ajouter(), Operateur_Conv_sensibility_VEF::ajouter(), Op_Conv_Amont_old_VEF_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Centre_EF_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_EF_VEF_P1NC::ajouter(), Op_Conv_EF_VEF_P1NC_Stab::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_Muscl_New_VEF_Face::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Conv_Vort_VEF_Face::ajouter(), Op_Diff_RotRot::ajouter(), Op_Conv_RT_VEF_Face::ajouter(), Terme_Boussinesq_Sensibility_VEFPreP1B_Face::ajouter(), Source_Transport_Fluctuation_Temperature_VDF_Elem::ajouter(), Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::ajouter(), Source_Transport_Fluctuation_Temperature_W_VDF_Elem::ajouter(), Source_Transport_Flux_Chaleur_Turbulente_VDF_Face::ajouter(), Source_Robin_Scalaire::ajouter(), Terme_Boussinesq_VEF_Face::ajouter(), Terme_Source_Decroissance_Radioactive_VEF_Face::ajouter(), Terme_Source_Th_TdivU_VEF_Face::ajouter(), Source_rayo_semi_transp_VDF_P0_VDF::ajouter(), Source_rayo_semi_transp_VEF_P1NC::ajouter(), Op_Diff_K_Eps_VDF_base::ajouter_blocs(), Op_Diff_K_Omega_VDF_base::ajouter_blocs(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_W_VDF_Elem::ajouter_blocs(), Source_Transport_K_Eps_VDF_Elem::ajouter_blocs(), Source_Transport_K_Omega_VDF_Elem::ajouter_blocs(), Op_Grad_P0_to_Face::ajouter_blocs(), Perte_Charge_Reguliere_VDF_Face::ajouter_blocs(), Perte_Charge_Singuliere_VDF_Face::ajouter_blocs(), Terme_Boussinesq_VDF_Face::ajouter_blocs(), Terme_Source_inc_th_VDF_Face::ajouter_blocs(), Terme_Source_Qdm_VDF_Face::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_P0_Face::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Face::ajouter_blocs(), Op_Diff_PolyMAC_P0_Face::ajouter_blocs(), Couplage_Parietal_PolyMAC_helper::ajouter_blocs(), Coalescence_bulles_1groupe_PolyMAC_P0::ajouter_blocs(), Coalescence_bulles_2groupes_PolyMAC_P0::ajouter_blocs(), Flux_2groupes_PolyMAC_P0::ajouter_blocs(), Injection_QDM_nulle_PolyMAC_P0::ajouter_blocs(), Rupture_bulles_1groupe_PolyMAC_P0::ajouter_blocs(), Rupture_bulles_2groupes_PolyMAC_P0::ajouter_blocs(), Variation_rho::ajouter_blocs(), Injection_QDM_nulle_VDF::ajouter_blocs(), Diffusion_croisee_echelle_temp_taux_diss_turb_PolyMAC_P0::ajouter_blocs(), Diffusion_supplementaire_echelle_temp_turb_PolyMAC_P0::ajouter_blocs(), Dissipation_WIT_PolyMAC_P0::ajouter_blocs(), Production_echelle_temp_taux_diss_turb_PolyMAC_P0::ajouter_blocs(), Production_energie_cin_turb_PolyMAC_P0::ajouter_blocs(), Production_WIT_PolyMAC_P0::ajouter_blocs(), Source_BIF_PolyMAC_P0::ajouter_blocs(), Source_Dissipation_echelle_temp_taux_diss_turb::ajouter_blocs(), Source_Dissipation_energie_cin_turb::ajouter_blocs(), Diffusion_croisee_echelle_temp_taux_diss_turb_VDF::ajouter_blocs(), Production_echelle_temp_taux_diss_turb_VDF::ajouter_blocs(), Production_energie_cin_turb_VDF::ajouter_blocs(), Op_Diff_DG_Elem::ajouter_blocs(), Frottement_interfacial_PolyMAC_P0::ajouter_blocs(), Portance_interfaciale_PolyMAC_P0::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::ajouter_blocs(), Op_Diff_PolyMAC_P0_Elem::ajouter_blocs(), DP_Impose_PolyMAC_Face::ajouter_blocs(), Perte_Charge_Singuliere_PolyMAC_P0P1NC_Face::ajouter_blocs(), Terme_Boussinesq_PolyMAC_Face::ajouter_blocs(), Terme_Source_Decroissance_Radioactive_Elem_PolyMAC::ajouter_blocs(), Terme_Source_Qdm_Face_PolyMAC_P0P1NC::ajouter_blocs(), Op_Evanescence_Homogene_Elem_base::ajouter_blocs(), Op_Evanescence_Homogene_Face_base::ajouter_blocs(), Source_Flux_interfacial_base::ajouter_blocs(), Source_Force_Tchen_base::ajouter_blocs(), Source_Travail_pression_Elem_base::ajouter_blocs(), Frottement_interfacial_VDF::ajouter_blocs(), Portance_interfaciale_VDF::ajouter_blocs(), Op_Conv_Amont_VPoly_VDF_Face::ajouter_blocs(), DP_Impose_VEF_Face::ajouter_blocs(), Masse_DG_base::ajouter_blocs(), Masse_PolyMAC_P0_Face::ajouter_blocs(), Masse_VDF_base::ajouter_blocs(), Masse_VDF_Face::ajouter_blocs(), Op_Evanescence_Homogene_PolyMAC_P0_Face::ajouter_blocs_aux(), Force_Tchen_PolyMAC_P0::ajouter_blocs_aux(), Correction_Lubchenko_PolyMAC_P0::ajouter_blocs_BIF(), Op_Diff_PolyMAC_P0P1NC_Elem::ajouter_blocs_ext(), Op_Diff_PolyMAC_P0P1NC_Face::ajouter_blocs_ext(), Solveur_Masse_Elem_proto::ajouter_blocs_proto(), Op_Conv_Amont_old_VEF_Face::ajouter_contribution(), Op_Conv_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution(), Op_Diff_VEF_Face::ajouter_contribution(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution(), Op_Conv_RT_VEF_Face::ajouter_contribution(), Operateur_base::ajouter_contribution_explicite_au_second_membre(), Op_Conv_EF::ajouter_contribution_sous_cond(), Op_Diff_EF::ajouter_contributions_bords(), Op_Dift_EF_Q1::ajouter_contributions_bords(), Operateur_Conv_sensibility_VEF::ajouter_conv_term(), Solveur_Masse_base::ajouter_masse(), Masse_PolyMAC_Elem::ajouter_masse(), Source_Masse_Fluide_Dilatable_VEF::ajouter_projection(), Op_Diff_PolyMAC_Elem::ajouter_termes_croises(), Op_Conv_ALE_VEF::ajouterALE(), Solveur_Masse_base::appliquer(), Masse_DG_base::appliquer_coef(), Masse_PolyMAC_base::appliquer_coef(), Masse_PolyMAC_P0_Face::appliquer_impl(), Masse_PolyMAC_P0P1NC_Face::appliquer_impl(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_blocs(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_blocs_avec_inertie(), Convection_Diffusion_Espece_Multi_QC::assembler_blocs_avec_inertie(), Assembleur_P_PolyMAC_P0P1NC::assembler_continuite(), Eq_rayo_semi_transp_VDF::assembler_matrice(), Eq_rayo_semi_transp_VEF::assembler_matrice(), Source_Con_Phase_field::assembler_matrice_point_fixe(), Simpler_Base::assembler_matrice_pression_implicite(), Eval_Conv_PolyMAC::associer(), Eval_Conv_VDF::associer(), Op_Diff_VEF_base::associer(), EOS_Tools_VDF::associer_domaines(), Source_PDF_EF::associer_pb(), grad_Champ_Face_PolyMAC_P0::calc_gradfve(), Modele_Shih_Zhu_Lumley_VDF::Calcul_Cmu_et_S(), Modele_Shih_Zhu_Lumley_VDF::Calcul_Cmu_et_S_BiK(), Champ_Face_VDF::calcul_critere_Q(), Champ_P1NC::calcul_critere_Q(), Modele_Jones_Launder_VDF::calcul_derivees_premieres_croisees(), Modele_Jones_Launder_VDF::Calcul_E(), Champ_P1NC::calcul_grad_T(), Champ_P1NC::calcul_grad_U(), Champ_P1NC::calcul_h_conv(), Transport_Interfaces_FT_Disc::calcul_indicatrice_faces(), Terme_Source_Solide_SWIFT_VDF::calcul_moyenne(), Tenseur_Reynolds_Externe_VDF_Face::Calcul_RSLambda(), Modele_Shih_Zhu_Lumley_VDF::Calcul_S(), Traitement_particulier_NS_THI_VEF::calcul_spectre(), Segment_poly::calcul_vc(), Tetra_poly::calcul_vc(), Point_EF::calcul_vc(), Segment_EF::calcul_vc(), Tetra_EF::calcul_vc(), Tri_EF::calcul_vc(), Tetra_VEF::calcul_vc(), Tri_VEF::calcul_vc(), Champ_Q1_EF::calcul_y_plus(), Champ_P1NC::calcul_y_plus(), Champ_Face_VDF::calcul_y_plus(), Champ_P1NC::calcul_y_plus_diphasique(), Champ_Face_VDF::calcul_y_plus_diphasique(), Fluide_reel_base::calculate_fluid_properties_enthalpie(), Fluide_reel_base::calculate_fluid_properties_enthalpie_incompressible(), Modele_turbulence_hyd_RANS_Gen< MODELE >::calculate_limit_viscosity(), Perte_Charge_Singuliere::calculate_Q(), Op_Conv_ALE_VEF::calculateALEjacobian(), Operateur::calculer(), Op_Diff_P1NC_barprim::calculer(), Source_PDF_base::calculer(), Source_Con_Phase_field::calculer_alpha_gradC_carre(), Masse_Multiphase::calculer_alpha_rho(), Energie_Multiphase::calculer_alpha_rho_e(), Energie_Multiphase::calculer_alpha_rho_h(), Energie_cinetique_turbulente::calculer_alpha_rho_k(), Energie_cinetique_turbulente_WIT::calculer_alpha_rho_k_WIT(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calculer_cell_cent_vel(), Equation_base::calculer_champ_conserve(), Terme_Source_Canal_perio_VDF_Face::calculer_debit(), Terme_Source_Canal_perio_VEF_P1NC::calculer_debit(), Champ_Face_VDF::calculer_dercov_axi(), Navier_Stokes_FT_Disc::calculer_dI_dt(), Modele_turbulence_scal_LES_dyn_VDF::calculer_diffusivite_turbulente(), Modele_turbulence_scal_Fluctuation_Temperature_W::calculer_diffusivite_turbulente(), Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re::calculer_diffusivite_turbulente(), Source_Con_Phase_field::calculer_div_alpha_gradC(), Source_Con_Phase_field::calculer_div_alpha_rho_gradC(), Convection_Diffusion_Fluide_Dilatable_Proto::calculer_div_rho_u_impl(), Champ_Face_VDF::calculer_dscald_centre_element(), Op_Conv_VDF_base::calculer_dt_local(), Op_Conv_EF::calculer_dt_stab(), Op_Diff_PolyMAC_P0_Elem::calculer_dt_stab(), Op_Diff_PolyMAC_P0_Face::calculer_dt_stab(), Op_Diff_PolyMAC_P0P1NC_Elem::calculer_dt_stab(), Op_Diff_PolyMAC_P0P1NC_Face::calculer_dt_stab(), Op_Conv_Muscl_New_VEF_Face::calculer_dt_stab(), Op_Grad_EF::calculer_flux_bords(), Op_Grad_VDF_Face::calculer_flux_bords(), Flux_radiatif_VDF::calculer_flux_radiatif(), Flux_radiatif_VEF::calculer_flux_radiatif(), Terme_Source_Coriolis_VDF_Face::calculer_force_de_Coriolis(), Convection_Diffusion_Temperature_FT_Disc::calculer_grad_t(), Turbulence_paroi_base::calculer_hyd(), ParoiVDF_TBLE_LRM::calculer_hyd(), Paroi_std_hyd_VEF::calculer_hyd(), Paroi_negligeable_VDF::calculer_hyd(), Paroi_negligeable_VEF::calculer_hyd(), Paroi_std_hyd_VDF_diphasique::calculer_hyd(), Paroi_std_hyd_VEF_diphasique::calculer_hyd(), Paroi_loi_WW_hyd_EF::calculer_hyd(), Paroi_std_hyd_EF::calculer_hyd(), Paroi_2couches_VDF::calculer_hyd(), Paroi_loi_Ciofalo_hyd_VDF::calculer_hyd(), Paroi_loi_WW_hyd_VDF::calculer_hyd(), Paroi_loi_WW_hyd_VEF::calculer_hyd(), Paroi_std_hyd_VDF::calculer_hyd(), Paroi_UTAU_IMP_VDF::calculer_hyd(), ParoiVDF_TBLE::calculer_hyd(), ParoiVEF_TBLE::calculer_hyd(), Paroi_std_hyd_VDF::calculer_hyd_BiK(), Paroi_UTAU_IMP_VDF::calculer_hyd_BiK(), ParoiVDF_TBLE::calculer_hyd_BiK(), ParoiVDF_TBLE_LRM::calculer_hyd_BiK(), Paroi_std_hyd_VEF::calculer_hyd_BiK(), ParoiVEF_TBLE::calculer_hyd_BiK(), Navier_Stokes_std::calculer_la_pression_en_pa(), Navier_Stokes_FT_Disc::calculer_la_pression_en_pa(), Op_Diff_VEFP1NCP1B_Face::calculer_laplacien_som(), Paroi_std_hyd_VDF::calculer_moyennes_parois(), Source_Con_Phase_field::calculer_mutilde(), Source_Con_Phase_field::calculer_mutilde_demi(), Taux_dissipation_turbulent::calculer_omega(), Source_Con_Phase_field::calculer_pression_thermo(), Echange_contact_Correlation_VDF::calculer_Q(), Champ_Face_VDF::calculer_rotationnel_ordre2_centre_element(), Loi_Paroi_Nu_Impose_VDF::calculer_scal(), Paroi_ODVM_scal_VDF::calculer_scal(), Paroi_TBLE_scal_VDF::calculer_scal(), Loi_Paroi_Nu_Impose_VEF::calculer_scal(), ParoiVEF_TBLE_scal::calculer_scal(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calculer_Sij(), Echelle_temporelle_turbulente::calculer_tau(), Neumann_paroi_rayo_semi_transp_VEF::calculer_temperature_bord(), Echange_contact_ODVM_VDF::calculer_Teta_equiv(), Echange_contact_VDF::calculer_Teta_paroi(), Echange_contact_Rayo_transp_VDF::calculer_Teta_paroi(), Echange_contact_rayo_semi_transp_VDF::calculer_Teta_paroi(), Source_Con_Phase_field::calculer_u2_elem(), Source_PDF_EF::calculer_variable_imposee_elem_fluid(), Source_PDF_EF::calculer_variable_imposee_hybrid(), Source_PDF_EF::calculer_variable_imposee_mean_grad(), Terme_Source_Acceleration_VDF_Face::calculer_vitesse_faces(), Terme_Source_Acceleration_VEF_Face::calculer_vitesse_faces(), Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl(), Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl_u_star(), Transport_Interfaces_FT_Disc::calculer_vitesse_transport_interpolee(), Fluide_reel_base::check_unknown_range(), Modele_turbulence_hyd_RANS_Gen< MODELE >::complete_viscosity_field(), Cond_lim_omega_demi::completer(), Cond_lim_omega_dix::completer(), Echange_contact_Rayo_transp_VDF::completer(), Op_Diff_DG_Elem::completer(), Op_Diff_PolyMAC_P0_base::completer(), Op_Diff_PolyMAC_P0P1NC_base::completer(), Op_Diff_PolyMAC_Elem::completer(), Op_Diff_PolyMAC_P0_Elem::completer(), Op_Diff_PolyMAC_P0_Face::completer(), Op_Diff_PolyMAC_P0P1NC_Elem::completer(), Op_Diff_PolyMAC_P0P1NC_Face::completer(), Source_Flux_interfacial_base::completer(), Echange_contact_Correlation_VEF::completer(), Champ_Post_Operateur_Eqn::completer(), Couplage_Parietal_PolyMAC_helper::completer_d_nuc(), Champ_Face_VDF::compo_normale_sortante(), Champ_P1NC::compo_normale_sortante(), Champ_Q1NC::compo_normale_sortante(), Navier_Stokes_FT_Disc::compute_boussinesq_additional_gravity(), Source_PDF_EF::compute_coeff_elem(), Source_PDF_EF::compute_coeff_matrice(), Source_Transport_K_Omega_VEF_Face::compute_cross_diffusion(), Convection_Diffusion_Temperature_FT_Disc::compute_divergence_free_velocity_extension(), Post_Processing_Hydrodynamic_Forces::compute_friction_force_complet_tensor(), Post_Processing_Hydrodynamic_Forces::compute_friction_force_projected_tensor(), Post_Processing_Hydrodynamic_Forces::compute_heat_transfer(), Source_WC_Chaleur_VDF::compute_interpolate_gradP(), Source_WC_Chaleur_VEF::compute_interpolate_gradP(), Paroi_std_hyd_VDF::compute_law_komega(), Paroi_scal_hyd_base_EF::compute_nusselt(), Paroi_scal_hyd_base_VDF::compute_nusselt(), Paroi_scal_hyd_base_VEF::compute_nusselt(), Transport_Interfaces_FT_Disc::compute_particles_rms(), Post_Processing_Hydrodynamic_Forces::compute_pressure_force_trilinear_linear(), Triple_Line_Model_FT_Disc::compute_TCL_fluxes_in_all_boundary_cells(), Source_PDF_EF::compute_variable_imposee_projete(), Domaine_ALE::computeFluidForceOnBeam(), Op_Conv_Amont_old_VEF_Face::contribue_au_second_membre(), Op_Conv_VEF_Face::contribue_au_second_membre(), Source_Transport_K_Eps_VEF_Face::contribuer_a_avec(), Source_Transport_K_Omega_VEF_Face::contribuer_a_avec(), Source_PDF_EF::contribuer_a_avec(), Terme_Source_Decroissance_Radioactive_VEF_Face::contribuer_a_avec(), Op_Div_PolyMAC_P0::contribuer_a_avec(), Op_Diff_EF::contribuer_au_second_membre(), Op_Dift_EF_Q1::contribuer_au_second_membre(), Op_Dift_VEF_Face::contribuer_au_second_membre(), Op_Diff_PolyMAC_Elem::contribuer_termes_croises(), Transport_Fluctuation_Temperature::controler_grandeur(), Transport_Fluctuation_Temperature_W::controler_grandeur(), Transport_Flux_Chaleur_Turbulente::controler_grandeur(), Transport_K_Eps_base::controler_K_Eps(), Transport_K_Omega_base::controler_K_Omega(), Transport_K_ou_Eps_base::controler_variable(), Convection_Diffusion_Temperature_FT_Disc::correct_mpoint(), Navier_Stokes_std::corriger_derivee_expl(), Navier_Stokes_std::corriger_derivee_impl(), Masse_VDF_Face::corriger_solution(), Masse_PolyMAC_P0P1NC_Face::corriger_solution(), PolyMAC_P0_discretisation::creer_champ_vorticite(), VDF_discretisation::creer_champ_vorticite(), data_a_sauvegarder(), Navier_Stokes_std_ALE::data_a_sauvegarder(), Transport_Interfaces_FT_Disc::deplacer_maillage_ft_v_fluide(), Equation_base::derivee_en_temps_inco(), Convection_Diffusion_Temperature_FT_Disc::derivee_en_temps_inco(), Navier_Stokes_phase_field::derivee_en_temps_inco(), Convection_Diffusion_Espece_Multi_QC::derivee_en_temps_inco(), Convection_Diffusion_Temperature::derivee_en_temps_inco(), Navier_Stokes_std::derivee_en_temps_inco(), Navier_Stokes_FT_Disc::derivee_en_temps_inco(), Navier_Stokes_Fluide_Dilatable_Proto::derivee_en_temps_inco_impl(), Convection_Diffusion_Fluide_Dilatable_Proto::derivee_en_temps_inco_sans_solveur_masse_impl(), Schema_Phase_field::deuxieme_dt(), Op_EF_base::dimensionner(), Op_PolyMAC_Elem::dimensionner(), Op_VDF_Face::dimensionner(), Op_VEF_Face::dimensionner(), Op_Diff_PolyMAC_Elem::dimensionner(), Op_Div_PolyMAC_P0::dimensionner(), Solveur_Masse_base::dimensionner(), Masse_PolyMAC_Elem::dimensionner(), Masse_DG_base::dimensionner_blocs(), Masse_PolyMAC_P0_Face::dimensionner_blocs(), Op_Grad_VDF_Face::dimensionner_blocs(), Masse_VDF_base::dimensionner_blocs(), Op_Conv_EF_Stab_PolyMAC_P0_Face::dimensionner_blocs(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Face::dimensionner_blocs(), Op_Diff_PolyMAC_P0_Face::dimensionner_blocs(), Op_Div_PolyMAC_P0P1NC::dimensionner_blocs(), Op_Grad_PolyMAC_P0_Face::dimensionner_blocs(), Op_Grad_PolyMAC_P0P1NC_Face::dimensionner_blocs(), Coalescence_bulles_1groupe_PolyMAC_P0::dimensionner_blocs(), Coalescence_bulles_2groupes_PolyMAC_P0::dimensionner_blocs(), Flux_2groupes_PolyMAC_P0::dimensionner_blocs(), Rupture_bulles_1groupe_PolyMAC_P0::dimensionner_blocs(), Rupture_bulles_2groupes_PolyMAC_P0::dimensionner_blocs(), Variation_rho::dimensionner_blocs(), Diffusion_supplementaire_echelle_temp_turb_PolyMAC_P0::dimensionner_blocs(), Source_Diffusion_supplementaire_echelle_temp_turb::dimensionner_blocs(), Source_Dissipation_energie_cin_turb::dimensionner_blocs(), Source_Production_echelle_temp_taux_diss_turb::dimensionner_blocs(), Source_Production_energie_cin_turb::dimensionner_blocs(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::dimensionner_blocs(), Op_Diff_PolyMAC_P0_Elem::dimensionner_blocs(), Perte_Charge_Singuliere_PolyMAC_P0P1NC_Face::dimensionner_blocs(), Terme_Source_Decroissance_Radioactive_Elem_PolyMAC::dimensionner_blocs(), Op_Evanescence_Homogene_Elem_base::dimensionner_blocs(), Op_Evanescence_Homogene_Face_base::dimensionner_blocs(), Source_Flux_interfacial_base::dimensionner_blocs(), Source_Force_Tchen_base::dimensionner_blocs(), Source_Frottement_interfacial_base::dimensionner_blocs(), Source_Travail_pression_Elem_base::dimensionner_blocs(), DP_Impose_VEF_Face::dimensionner_blocs(), Dispersion_bulles_PolyMAC_P0::dimensionner_blocs_aux(), Op_Evanescence_Homogene_PolyMAC_P0_Face::dimensionner_blocs_aux(), Op_Conv_VDF_base::dimensionner_blocs_elem(), Op_Diff_PolyMAC_P0P1NC_Elem::dimensionner_blocs_ext(), Op_Diff_PolyMAC_P0P1NC_Face::dimensionner_blocs_ext(), Op_Conv_VDF_base::dimensionner_blocs_face(), Solveur_Masse_Elem_proto::dimensionner_blocs_proto(), Assembleur_P_PolyMAC_P0P1NC::dimensionner_continuite(), Op_Diff_PolyMAC_Elem::dimensionner_termes_croises(), Op_Diff_VDF_Elem_base::dimensionner_termes_croises(), Navier_Stokes_std_ALE::div_ale_derivative(), Source_Con_Phase_field::div_kappa_grad(), Convection_Diffusion_Temperature::ecrire_fichier_pena_th(), Viscosite_turbulente_WALE::eddy_viscosity(), Schema_Euler_explicite_ALE::faire_un_pas_de_temps_eqn_base(), RK3_MassRedistrib::faire_un_pas_de_temps_eqn_base(), Schema_Euler_explicite_Phase_field::faire_un_pas_de_temps_eqn_base(), Leap_frog::faire_un_pas_de_temps_eqn_base(), Pred_Cor::faire_un_pas_de_temps_eqn_base(), Schema_Euler_explicite::faire_un_pas_de_temps_eqn_base(), Schema_Euler_Implicite::faire_un_pas_de_temps_eqn_base(), Schema_Explicite_Multi_TimeStep_base::faire_un_pas_de_temps_eqn_base(), Schema_Implicite_Multi_TimeStep_base::faire_un_pas_de_temps_eqn_base(), RRK2::faire_un_pas_de_temps_eqn_base(), RK3_FT::faire_un_pas_de_temps_pb_couple(), Schema_Euler_Implicite::faire_un_pas_de_temps_pb_couple(), Champ_P1NC_implementation::filtrer_H1(), Sortie_libre_Gradient_Pression_libre_VEF::flux_impose(), Convection_Diffusion_Temperature_FT_Disc::get_Twall(), Transport_Interfaces_FT_Disc::get_update_indicatrice(), ICoCo::ProblemTrio::getDirectAccessToUnknown(), VDF_discretisation::grad_u(), PolyMAC_P0_discretisation::grad_u(), Champ_Q1_EF::gradient(), Champ_Q1NC::gradient(), Champ_P1NC::gradient(), Domaine_Cl_EF::imposer_cond_lim(), Domaine_Cl_PolyMAC::imposer_cond_lim(), Domaine_Cl_VDF::imposer_cond_lim(), Domaine_Cl_VEF::imposer_cond_lim(), Domaine_Cl_EF::imposer_symetrie_matrice_secmem(), Source_PDF_EF::impr(), Navier_Stokes_std::impr(), Navier_Stokes_Fluide_Dilatable_Proto::impr_impl(), Champ_Elem_DG::imprime(), Champ_P0_EF::imprime(), Champ_P1_EF::imprime(), Champ_Q1_EF::imprime(), Champ_Elem_PolyMAC::imprime(), Champ_Som_PolyMAC::imprime(), Equation_base::imprime_residu(), Modele_turbulence_hyd_0_eq_base::imprimer(), Loi_Paroi_Nu_Impose_VDF::imprimer_nusselt(), Loi_Paroi_Nu_Impose_VEF::imprimer_nusselt(), Equation_base::init_champ_conserve(), Energie_Multiphase::init_champ_convecte(), ParoiVDF_TBLE::init_lois_paroi(), ParoiVDF_TBLE_LRM::init_lois_paroi(), Paroi_ODVM_scal_VDF::init_lois_paroi(), Paroi_TBLE_scal_VDF::init_lois_paroi(), ParoiVEF_TBLE::init_lois_paroi(), ParoiVEF_TBLE_scal::init_lois_paroi(), Champ_Face_PolyMAC_P0::init_ve2(), Equation_base::initialise_residu(), Op_Diff_VEFP1NCP1B_Face::initialiser(), Ch_front_var_instationnaire_dep::initialiser(), Schema_Euler_Implicite::Initialiser_Champs(), Equation_base::initTimeStep(), Navier_Stokes_Fluide_Dilatable_base::initTimeStep(), Navier_Stokes_std::initTimeStep(), Fluide_base::initTimeStep(), QDM_Multiphase::initTimeStep(), Navier_Stokes_Turbulent_QC::initTimeStep(), Champ_P0_VDF::integrale_espace(), Imprimer_Fichiers_RANS_VDF::interpreter(), Imprimer_Fichiers_RANS_VEF::interpreter(), Schema_Temps_base::iterateTimeStep(), Schema_Phase_field::iterateTimeStep(), Multi_Sch_ThHyd::iterateTimeStep(), Sch_CN_iteratif::iterateTimeStepOnEquation(), Sch_CN_EX_iteratif::iterateTimeStepOnNS(), Sch_CN_EX_iteratif::iterateTimeStepOnOther(), SETS::iterer_eqn(), Simple::iterer_eqn(), Simple::iterer_eqs(), Schema_Implicite_Multi_TimeStep_base::Iterer_Pb(), Schema_Euler_Implicite::Iterer_Pb(), Source_Con_Phase_field::laplacien(), QDM_Multiphase::lire_cond_init(), Transport_Interfaces_FT_Disc::lire_cond_init(), Transport_Interfaces_FT_Disc::lire_maillage_ft_cao(), Paroi_frottante_simple::me_calculer(), Champ_Fonc_Elem_PolyMAC_P0_TC::me_calculer(), Champ_Fonc_Elem_PolyMAC_P0_rot::me_calculer_2D(), Champ_Fonc_Elem_PolyMAC_P0_rot::me_calculer_3D(), Source_Qdm_VDF_Phase_field::methode_1(), Source_Qdm_VDF_Phase_field::methode_2(), Source_Qdm_VDF_Phase_field::methode_3(), Source_Qdm_VDF_Phase_field::methode_4(), Frontiere_ouverte_vitesse_vortex::mettre_a_jour(), Convection_Diffusion_Concentration_FT_Disc::mettre_a_jour(), Convection_Diffusion_Concentration_Turbulent_FT_Disc::mettre_a_jour(), Convection_Diffusion_Temperature_FT_Disc::mettre_a_jour(), Transport_Interfaces_FT_Disc::mettre_a_jour(), mettre_a_jour(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::mettre_a_jour(), Navier_Stokes_std::mettre_a_jour(), QDM_Multiphase::mettre_a_jour(), Fluide_reel_base::mettre_a_jour(), Interface_base::mettre_a_jour(), Navier_Stokes_std_ALE::mettre_a_jour(), Energie_cinetique_turbulente::mettre_a_jour(), Echange_contact_VDF_FT_Disc_solid::mettre_a_jour(), Navier_Stokes_phase_field::mettre_a_jour(), Source_Qdm_VDF_Phase_field::mettre_a_jour(), PlaqThVDF::mettre_a_jour(), Op_Conv_VDF_base::mettre_a_jour(), Echange_contact_Correlation_VEF::mettre_a_jour(), Sonde::mettre_a_jour_bords(), Convection_Diffusion_Concentration_FT_Disc::mettre_a_jour_chimie(), Convection_Diffusion_Concentration_Turbulent_FT_Disc::mettre_a_jour_chimie(), Milieu_composite::mettre_a_jour_tabs(), Op_VEF_Face::modifier_matrice_pour_periodique_apres_contribuer(), Op_Diff_Turbulent_PolyMAC_P0_Face::modifier_mu(), Op_EF_base::modifier_pour_Cl(), Op_VDF_Face::modifier_pour_Cl(), Op_VEF_Face::modifier_pour_Cl(), Op_Diff_K_Eps_VDF_base::modifier_pour_Cl(), Op_Diff_K_Omega_VDF_base::modifier_pour_Cl(), Op_Diff_K_Eps_VEF_Face::modifier_pour_Cl(), Op_Diff_K_Omega_VEF_Face::modifier_pour_Cl(), Schema_Adams_Bashforth_base::modifier_second_membre(), Schema_Backward_Differentiation_base::modify_equation_parameters(), Navier_Stokes_IBM::modify_initial_variable(), Champ_P0_VDF::moyenne(), nb_valeurs_nodales(), Champ_Face_PolyMAC::nb_valeurs_nodales(), Maillage_FT_Disc::nettoyer_phase(), Champ_P1NC::norme_H1(), Champ_P1NC::norme_L2(), Champ_P1_isoP1Bulle::norme_L2(), Convection_Diffusion_Temperature::penalisation_L2(), Source_Con_Phase_field::premier_demi_dt(), Equation_base::preparer_calcul(), Navier_Stokes_FT_Disc::preparer_calcul(), Transport_Interfaces_FT_Disc::preparer_calcul(), Convection_Diffusion_Phase_field::preparer_calcul(), Navier_Stokes_phase_field::preparer_calcul(), Navier_Stokes_IBM::preparer_calcul(), Navier_Stokes_std::preparer_calcul(), Navier_Stokes_std::projeter(), Champ_Fonc_reprise::readOn(), Terme_Source_Decroissance_Radioactive_Elem_PolyMAC::readOn(), Terme_Source_Decroissance_Radioactive_VEF_Face::readOn(), Reaction::reagir(), Op_Conv_DI_L2_VEF_Face::reconst_DI_L2_2d(), Op_Conv_DI_L2_VEF_Face::reconst_DI_L2_3d(), Op_Conv_VEF_Face::remplir_fluent(), Operateur_Conv_sensibility_VEF::remplir_fluent(), Op_Conv_ALE_VEF::remplir_fluent_ALEincluded(), Navier_Stokes_std_ALE::renewing_jacobians(), reprendre(), Champ_Elem_PolyMAC_P0::reprendre(), Champ_Face_PolyMAC_P0::reprendre(), VDF_discretisation::residu(), VEF_discretisation::residu(), PolyMAC_P0_discretisation::residu(), PolyMAC_P0P1NC_discretisation::residu(), resize_val_bord(), Eq_rayo_semi_transp_VDF::resoudre(), Eq_rayo_semi_transp_VEF::resoudre(), sauvegarder(), Schema_Backward_Differentiation_base::store_equation_parameters(), Transport_Interfaces_FT_Disc::suppression_interfaces(), VDF_discretisation::t_paroi(), PolyMAC_P0_discretisation::taux_cisaillement(), Op_Diff_VEFP1NCP1B_Face::test(), Schema_Euler_Implicite::test_stationnaire(), Schema_Implicite_Multi_TimeStep_base::test_stationnaire(), Transport_Interfaces_FT_Disc::test_suppression_interfaces_sous_domaine(), Champ_Inc_P0_base::trace(), Champ_Inc_P1_base::trace(), Champ_Face_PolyMAC::trace(), Champ_Face_PolyMAC_P0::trace(), Champ_Face_PolyMAC_P0P1NC::trace(), Champ_Face_VDF::trace(), Champ_P1_isoP1Bulle::trace(), Champ_P1NC::trace(), Champ_Q1NC::trace(), Champ_Elem_PolyMAC::trace(), Transport_Interfaces_FT_Disc::transporter_sans_changement_topologie(), Echange_contact_PolyMAC::update_coeffs(), Transport_Interfaces_FT_Disc::update_critere_statio(), Op_Diff_PolyMAC_Elem::update_delta(), Op_Diff_PolyMAC_Elem::update_delta_int(), Op_Diff_PolyMAC_P0_base::update_nu(), Op_Diff_PolyMAC_P0P1NC_base::update_nu(), Op_Diff_PolyMAC_P0_base::update_phif(), Champ_Face_PolyMAC_P0::update_ve(), Champ_Face_PolyMAC_P0::update_ve2(), Champ_Inc_P0_base::valeur_au_bord(), Champ_P1_isoP1Bulle::valeur_au_bord(), valeur_aux_bords(), Champ_Face_PolyMAC::valeur_aux_elems(), Champ_Face_PolyMAC_P0::valeur_aux_elems(), Champ_Face_PolyMAC_P0::valeur_aux_elems_compo(), Champ_Face_PolyMAC_P0::valeur_aux_elems_passe(), Champ_Elem_PolyMAC::valeur_aux_faces(), Champ_P1iP1B_implementation::valeur_aux_sommets(), Champ_Fonc_reprise_IJK::valeurs(), Champ_Fonc_reprise::valeurs(), valeurs(), Champ_Face_VDF::verifie_valeurs_cl(), Champ_P1NC::verifie_valeurs_cl(), Champ_Q1NC::verifie_valeurs_cl(), and Debog::verifier().
valeurs() [2/4]
const DoubleTab & Champ_Inc_base::valeurs () const inline override virtual
Implements Champ_Proto.
References les_valeurs, and Roue::valeurs().
valeur_a()
DoubleVect & Champ_Inc_base::valeur_a (const DoubleVect & position, DoubleVect & tab_valeurs) const override virtual
Calcule la valeur du champs inconnue a la position specifiee.
Parameters
(DoubleVect& position) la position a laquelle on veut calculer le champ
(DoubleVect& les_valeurs) la valeur du champ inconnue a la position specifiee
Returns
(DoubleVect&) la valeur du champ inconnue a la position specifiee
Reimplemented from Champ_base.
References Domaine_32_64< _SIZE_ >::chercher_elements(), domaine(), Domaine_dis_base::domaine(), domaine_dis_base(), and Champ_base::valeur_a_elem().
valeur_aux()
DoubleTab & Champ_Inc_base::valeur_aux (const DoubleTab & positions, DoubleTab & tab_valeurs) const override virtual
Calcule les valeurs du champs inconnue aux positions specifiees.
Parameters
(DoubleTab& positions) les positions ou l'ont doit calculer le champ inconnues
(DoubleTab& valeurs) le tableau des valeurs du champ inconnue aux positions voulues
Returns
(DoubleTab&) le tableau des valeurs du champ inconnue aux positions voulues
Reimplemented from Champ_base.
References Domaine_32_64< _SIZE_ >::chercher_elements(), domaine(), Domaine_dis_base::domaine(), domaine_dis_base(), and Champ_base::valeur_aux_elems().
Referenced by Champ_P0_VDF::imprime().
valeur_aux_compo()
DoubleVect & Champ_Inc_base::valeur_aux_compo (const DoubleTab & positions, DoubleVect & tab_valeurs, int ncomp) const override virtual
Calcule les valeurs du champs inconnue aux positions specifiees, pour une certaine composante du champ.
Parameters
(DoubleTab& positions) les positions ou l'ont doit calculer le champ inconnues
(DoubleTab& les_valeurs) le tableau des valeurs du champ inconnue aux positions voulues
(int) l'index de la composante du champ a calculer
Returns
(DoubleVect&) le tableau des valeurs de la composante du champ specifiee aux positions voulues
Reimplemented from Champ_base.
References Domaine_32_64< _SIZE_ >::chercher_elements(), domaine(), Domaine_dis_base::domaine(), domaine_dis_base(), and Champ_base::valeur_aux_elems_compo().
Referenced by Champ_Fonc_reprise_IJK::valeur_aux_compo(), and Champ_Fonc_reprise::valeur_aux_compo().
nb_valeurs_nodales()
int Champ_Inc_base::nb_valeurs_nodales () const override virtual
Returns the number of "real" geometric positions of the degrees of freedom, or -1 if not applicable (fields with multiple localisations)
Reimplemented from Champ_base.
Reimplemented in Champ_Elem_PolyMAC_P0P1NC, Champ_Face_PolyMAC, and Champ_Face_PolyMAC_P0P1NC.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTVect< _TYPE_, _SIZE_ >::size_reelle_ok(), and valeurs().
Referenced by Champ_Fonc_reprise_IJK::readOn(), and reprendre().
fixer_nb_valeurs_temporelles()
int Champ_Inc_base::fixer_nb_valeurs_temporelles (int i) virtual
Fixe le nombre de valeurs temporelles a conserver.
(un nombre different suivant le schema en temps utilise) Appelle Roue::fixer_nb_cases(int)
Parameters
(int i) le nombre de valeurs temporelles a conserver
Returns
(int) le nombre de valeurs temporelles a conserver
References Roue::fixer_nb_cases(), and les_valeurs.
Referenced by Discretisation_base::creer_champ(), Equation_rayonnement_base::discretiser(), and Champ_Fonc_reprise_IJK::readOn().
nb_valeurs_temporelles()
int Champ_Inc_base::nb_valeurs_temporelles () const virtual
Renvoie le nombre de valeurs temporelles actuellement conservees.
Cette valeur est stockee par la Roue du Champ_Inc_base
Returns
(int) le nombre de valeurs temporelles actuellement conservees
References les_valeurs, and Roue::nb_cases().
Referenced by Fluide_base::creer_e_int(), creer_tableau_distribue(), Fluide_reel_base::discretiser(), Milieu_composite::discretiser(), Champ_Elem_PolyMAC_P0P1NC::init_auxiliary_variables(), Champ_Face_PolyMAC_P0P1NC::init_auxiliary_variables(), Champ_Face_PolyMAC_P0::init_auxiliary_variables(), Equation_base::init_champ_conserve(), Energie_Multiphase::init_champ_convecte(), Convection_Diffusion_Temperature_FT_Disc::suppression_interfaces(), and valeurs().
changer_temps_futur()
double Champ_Inc_base::changer_temps_futur (double t, int i = 1)
Fixe le temps du ieme champ futur.
Parameters
(double t, int i) le nouveau temps
Returns
(double) le nouveau temps
References Roue::changer_temps(), Roue::futur(), les_valeurs, and Roue_ptr::valeur().
Referenced by Equation_base::initTimeStep(), Navier_Stokes_std::initTimeStep(), Fluide_base::initTimeStep(), and QDM_Multiphase::initTimeStep().
changer_temps_passe()
double Champ_Inc_base::changer_temps_passe (double t, int i = 1)
Fixe le temps du ieme champ passe.
Parameters
(double t, int i) le nouveau temps
Returns
(double) le nouveau temps
References Roue::changer_temps(), les_valeurs, Roue::passe(), and Roue_ptr::valeur().
recuperer_temps_futur()
double Champ_Inc_base::recuperer_temps_futur (int i = 1) const
Retourne le temps du ieme champ futur.
Parameters
(int i) le temps
Returns
(double) le temps
References Roue::futur(), les_valeurs, Roue::temps(), and Roue_ptr::valeur().
Referenced by Schema_Implicite_Multi_TimeStep_base::ajouter_inertie(), and Schema_Adams_Bashforth_base::modifier_second_membre().
recuperer_temps_passe()
double Champ_Inc_base::recuperer_temps_passe (int i = 1) const
Retourne le temps du ieme champ passe.
Parameters
(int i) le temps
Returns
(double) le temps
References les_valeurs, Roue::passe(), Roue::temps(), and Roue_ptr::valeur().
Referenced by Schema_Implicite_Multi_TimeStep_base::ajouter_inertie(), Schema_Adams_Bashforth_base::modifier_second_membre(), and Op_Grad_PolyMAC_P0_Face::update_grad().
valeurs() [3/4]
DoubleTab & Champ_Inc_base::valeurs (double tps) override virtual
Renvoie les valeurs du champs a l'instant temps.
Parameters
(double temps) le temps auquel on veut les valeurs du champ
Returns
(DoubleTab&) les valeurs du champs a l'instant temps
Reimplemented from Champ_Proto.
References Process::exit(), Roue::futur(), les_valeurs, nb_valeurs_temporelles(), Roue::passe(), Champ_base::temps(), Roue::temps(), Roue_ptr::valeur(), Roue::valeurs(), and valeurs().
valeurs() [4/4]
const DoubleTab & Champ_Inc_base::valeurs (double tps) const override virtual
Renvoie les valeurs du champs a l'instant temps.
Parameters
(double temps) le temps auquel on veut les valeurs du champ
Returns
(DoubleTab&) les valeurs du champs a l'instant temps
Reimplemented from Champ_Proto.
References Process::exit(), Roue::futur(), Roue::passe(), Roue::temps(), and Roue::valeurs().
operator DoubleTab &()
Champ_Inc_base::operator DoubleTab & () delete
operator const DoubleTab &()
Champ_Inc_base::operator const DoubleTab & () const delete
futur() [1/2]
DoubleTab & Champ_Inc_base::futur (int i = 1) inline override virtual
Renvoie les valeurs du champs a l'instant t+i.
Parameters
(int i) le pas de temps futur auquel on veut les valeurs du champ
Returns
(DoubleTab&) les valeurs du champs a l'instant t+i
Reimplemented from Champ_Proto.
References Roue::futur(), les_valeurs, and Roue::valeurs().
Referenced by Navier_Stokes_phase_field::calculer_mu(), Navier_Stokes_phase_field::calculer_rho(), creer_tableau_distribue(), Convection_Diffusion_Temperature_FT_Disc::derivee_en_temps_inco(), Convection_Diffusion_Fluide_Dilatable_Proto::derivee_en_temps_inco_sans_solveur_masse_impl(), Schema_Euler_explicite_ALE::faire_un_pas_de_temps_eqn_base(), RK3_MassRedistrib::faire_un_pas_de_temps_eqn_base(), Schema_Euler_explicite_Phase_field::faire_un_pas_de_temps_eqn_base(), Leap_frog::faire_un_pas_de_temps_eqn_base(), Pred_Cor::faire_un_pas_de_temps_eqn_base(), Schema_Euler_explicite::faire_un_pas_de_temps_eqn_base(), Schema_Euler_Implicite::faire_un_pas_de_temps_eqn_base(), Schema_Explicite_Multi_TimeStep_base::faire_un_pas_de_temps_eqn_base(), Schema_Implicite_Multi_TimeStep_base::faire_un_pas_de_temps_eqn_base(), RRK2::faire_un_pas_de_temps_eqn_base(), Schema_Euler_Implicite::faire_un_pas_de_temps_pb_couple(), ICoCo::ProblemTrio::getDirectAccessToUnknown(), Champ_Elem_PolyMAC_P0P1NC::init_auxiliary_variables(), Champ_Face_PolyMAC_P0P1NC::init_auxiliary_variables(), Champ_Face_PolyMAC_P0::init_auxiliary_variables(), Equation_base::initTimeStep(), Navier_Stokes_std::initTimeStep(), Fluide_base::initTimeStep(), QDM_Multiphase::initTimeStep(), Simple::iterer_eqs(), Schema_Implicite_Multi_TimeStep_base::Iterer_Pb(), Schema_Euler_Implicite::Iterer_Pb(), Convection_Diffusion_Temperature_FT_Disc::suppression_interfaces(), Schema_Euler_Implicite::test_stationnaire(), Schema_Implicite_Multi_TimeStep_base::test_stationnaire(), Schema_Temps_base::update_critere_statio(), and Schema_Adams_Moulton_base::update_time_derivative().
futur() [2/2]
const DoubleTab & Champ_Inc_base::futur (int i = 1) const inline override virtual
Reimplemented from Champ_Proto.
References Roue::futur(), les_valeurs, and Roue::valeurs().
passe() [1/2]
DoubleTab & Champ_Inc_base::passe (int i = 1) inline override virtual
Renvoie les valeurs du champs a l'instant t-i.
Parameters
(int i) le pas de temps passe auquel on veut les valeurs du champ
Returns
(DoubleTab&) les valeurs du champs a l'instant t-i
Reimplemented from Champ_Proto.
References les_valeurs, Roue::passe(), and Roue::valeurs().
Referenced by Schema_Adams_Moulton_base::add_multi_timestep_data(), Schema_Backward_Differentiation_base::add_multi_timestep_data(), Op_Dift_VDF_base::ajoute_terme_pour_axi_turb(), Perte_Charge_Singuliere_VDF_Face::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_P0_Face::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Face::ajouter_blocs(), Coalescence_bulles_1groupe_PolyMAC_P0::ajouter_blocs(), Coalescence_bulles_2groupes_PolyMAC_P0::ajouter_blocs(), Flux_2groupes_PolyMAC_P0::ajouter_blocs(), Injection_QDM_nulle_PolyMAC_P0::ajouter_blocs(), Rupture_bulles_1groupe_PolyMAC_P0::ajouter_blocs(), Rupture_bulles_2groupes_PolyMAC_P0::ajouter_blocs(), Injection_QDM_nulle_VDF::ajouter_blocs(), Diffusion_croisee_echelle_temp_taux_diss_turb_PolyMAC_P0::ajouter_blocs(), Diffusion_supplementaire_echelle_temp_turb_PolyMAC_P0::ajouter_blocs(), Dissipation_WIT_PolyMAC_P0::ajouter_blocs(), Source_Dissipation_HZDR_PolyMAC_P0::ajouter_blocs(), Source_Dissipation_echelle_temp_taux_diss_turb::ajouter_blocs(), Source_Dissipation_energie_cin_turb::ajouter_blocs(), Diffusion_croisee_echelle_temp_taux_diss_turb_VDF::ajouter_blocs(), Diffusion_supplementaire_echelle_temp_turb_VDF::ajouter_blocs(), Production_echelle_temp_taux_diss_turb_VDF::ajouter_blocs(), Correction_Antal_PolyMAC_P0::ajouter_blocs(), Correction_Tomiyama_PolyMAC_P0::ajouter_blocs(), Dispersion_bulles_PolyMAC_P0::ajouter_blocs(), Frottement_interfacial_PolyMAC_P0::ajouter_blocs(), Portance_interfaciale_PolyMAC_P0::ajouter_blocs(), Perte_Charge_PolyMAC::ajouter_blocs(), Perte_Charge_Singuliere_PolyMAC_P0P1NC_Face::ajouter_blocs(), Source_Force_Tchen_base::ajouter_blocs(), Source_Travail_pression_Elem_base::ajouter_blocs(), Correction_Antal_VDF::ajouter_blocs(), Dispersion_bulles_VDF::ajouter_blocs(), Frottement_interfacial_VDF::ajouter_blocs(), Portance_interfaciale_VDF::ajouter_blocs(), Op_Conv_Amont_VPoly_VDF_Face::ajouter_blocs(), Perte_Charge_VDF_base::ajouter_blocs(), Masse_DG_base::ajouter_blocs(), Masse_PolyMAC_P0_Face::ajouter_blocs(), Masse_VDF_base::ajouter_blocs(), Masse_VDF_Face::ajouter_blocs(), Op_Evanescence_Homogene_PolyMAC_P0_Face::ajouter_blocs_aux(), Force_Tchen_PolyMAC_P0::ajouter_blocs_aux(), Correction_Lubchenko_PolyMAC_P0::ajouter_blocs_disp(), Op_Diff_PolyMAC_P0P1NC_Elem::ajouter_blocs_ext(), Correction_Lubchenko_PolyMAC_P0::ajouter_blocs_lift(), Solveur_Masse_Face_proto::ajouter_blocs_proto(), Solveur_Masse_Elem_proto::ajouter_blocs_proto(), Schema_Temps_base::ajouter_inertie(), Schema_Euler_Implicite_Stationnaire::ajouter_inertie(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_avec_inertie_impl(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_blocs_avec_inertie(), Assembleur_P_PolyMAC_P0P1NC::assembler_continuite(), Op_Evanescence_Homogene_PolyMAC_P0_Face::calc_grad_alpha_elem(), Op_Evanescence_Homogene_PolyMAC_P0_Face::calc_grad_alpha_faces(), Op_Evanescence_Homogene_VDF_Face::calc_grad_alpha_faces(), grad_Champ_Face_PolyMAC_P0::calc_gradfve(), Convection_Diffusion_Temperature_FT_Disc::correct_mpoint(), Navier_Stokes_std::corriger_derivee_impl(), Leap_frog::faire_un_pas_de_temps_eqn_base(), Schema_Euler_Implicite::faire_un_pas_de_temps_eqn_base(), Schema_Implicite_Multi_TimeStep_base::faire_un_pas_de_temps_eqn_base(), Schema_Euler_Implicite::Initialiser_Champs(), Schema_Implicite_Multi_TimeStep_base::Initialiser_Champs(), SETS::iterer_NS(), QDM_Multiphase::lire_cond_init(), Portance_interfaciale_PolyMAC_P0::mettre_a_jour(), Aire_interfaciale::mettre_a_jour(), Energie_cinetique_turbulente::mettre_a_jour(), Schema_Adams_Bashforth_base::modifier_second_membre(), Schema_Adams_Moulton_base::modifier_second_membre_full_impl(), Implicite_ALE::second_special_treatment(), Schema_Euler_Implicite::test_stationnaire(), Schema_Implicite_Multi_TimeStep_base::test_stationnaire(), Transport_Interfaces_FT_Disc::update_critere_statio(), Champ_Face_PolyMAC::valeur_aux_elems_passe(), and Champ_Face_PolyMAC_P0::valeur_aux_elems_passe().
passe() [2/2]
const DoubleTab & Champ_Inc_base::passe (int i = 1) const inline override virtual
Reimplemented from Champ_Proto.
References les_valeurs, Roue::passe(), and Roue::valeurs().
avancer()
Champ_Inc_base & Champ_Inc_base::avancer (int i = 1)
Avance le pointeur courant de i pas de temps, dans la liste des valeurs temporelles conservees.
Parameters
(int i) le nombre de pas de temps dont on avance
Returns
(Champ_Inc_base&) renvoie *this, le champ au pas de temps voulu
References Roue::avancer(), les_valeurs, Roue::temps(), and Champ_base::temps_.
Referenced by Equation_base::avancer(), Schema_Euler_explicite_ALE::faire_un_pas_de_temps_eqn_base(), Schema_Euler_explicite_Phase_field::faire_un_pas_de_temps_eqn_base(), Pred_Cor::faire_un_pas_de_temps_eqn_base(), Schema_Euler_explicite::faire_un_pas_de_temps_eqn_base(), Sch_CN_iteratif::iterateTimeStepOnEquation(), Sch_CN_EX_iteratif::iterateTimeStepOnNS(), Sch_CN_EX_iteratif::iterateTimeStepOnOther(), and mettre_a_jour().
reculer()
Champ_Inc_base & Champ_Inc_base::reculer (int i = 1)
Recule le pointeur courant de i pas de temps, dans la liste des valeurs temporelles conservees.
Parameters
(int i) le nombre de pas de temps dont on recule
Returns
(Champ_Inc_base&) renvoie *this, le champ au pas de temps voulu
References les_valeurs, Roue::reculer(), Roue::temps(), and Champ_base::temps_.
Referenced by Schema_Euler_explicite_ALE::faire_un_pas_de_temps_eqn_base(), Schema_Euler_explicite_Phase_field::faire_un_pas_de_temps_eqn_base(), Pred_Cor::faire_un_pas_de_temps_eqn_base(), Schema_Euler_explicite::faire_un_pas_de_temps_eqn_base(), Pb_Dilatable_base::iterateTimeStep(), Sch_CN_iteratif::iterateTimeStepOnEquation(), Sch_CN_EX_iteratif::iterateTimeStepOnNS(), Sch_CN_EX_iteratif::iterateTimeStepOnOther(), and Equation_base::reculer().
lire_donnees()
int Champ_Inc_base::lire_donnees (Entree & is)
Lit les valeurs du champs a partir d'un flot d'entree.
Format de lecture: int [LE NOMBRE DE VALEURS A LIRE] [LIRE LE NOMBRE DE VALEUR VOULUES]
Parameters
(Entree& is) le flot d'entree
Returns
(int) renvoie 1 si la lecture est correcte
Exceptions
le nombre de valeur a lire est incorrect
References Process::exit(), les_valeurs, TRUSTVect< _TYPE_, _SIZE_ >::size(), and Roue::valeurs().
Referenced by Champ_Elem_DG::readOn(), Champ_P0_EF::readOn(), Champ_P1_EF::readOn(), Champ_Q1_EF::readOn(), Champ_Inc_P0_base::readOn(), Champ_Inc_P1_base::readOn(), Champ_Inc_Q1_base::readOn(), Champ_Elem_PolyMAC::readOn(), Champ_Som_PolyMAC::readOn(), Champ_Face_VDF::readOn(), Champ_P1_isoP1Bulle::readOn(), Champ_P1NC::readOn(), and Champ_Q1NC::readOn().
imprime()
int Champ_Inc_base::imprime (Sortie & os, int ncomp) const override virtual
Implements Champ_base.
Reimplemented in Champ_Elem_PolyMAC, Champ_Som_PolyMAC, Champ_Face_VDF, Champ_P0_VEF, Champ_P1NC, and Champ_P0_VDF.
References Process::exit(), and Objet_U::que_suis_je().
a_un_domaine_dis_base()
int Champ_Inc_base::a_un_domaine_dis_base () const inline override virtual
Reimplemented from Champ_base.
associer_eqn()
void Champ_Inc_base::associer_eqn (const Equation_base & eqn) virtual
Associe le champ a l'equation dont il represente une inconnue.
Simple appel a MorEqn::associer_eqn(const Equation_base&)
Parameters
(Equation_base& eqn) l'equation auquel le champ doit s'associer
References MorEqn::associer_eqn().
Referenced by Equation_base::completer(), Transport_Fluctuation_Temperature::completer(), Transport_Flux_Chaleur_Turbulente::completer(), Navier_Stokes_std::completer(), Transport_Interfaces_FT_Disc::discretiser(), Transport_Marqueur_FT::discretiser(), Equation_base::init_champ_conserve(), Energie_Multiphase::init_champ_convecte(), Fluide_reel_base::initialiser(), and Milieu_composite::initialiser().
associer_domaine_cl_dis()
void Champ_Inc_base::associer_domaine_cl_dis (const Domaine_Cl_dis_base & zcl) virtual
References mon_dom_cl_dis.
Referenced by Equation_base::completer(), and Navier_Stokes_std::completer().
associer_domaine_dis_base()
void Champ_Inc_base::associer_domaine_dis_base (const Domaine_dis_base & z_dis) override virtual
Reimplemented from Champ_base.
References le_dom_VF.
Referenced by Op_Diff_RotRot::associer(), EOS_Tools_VDF::associer_domaines(), Modele_turbulence_hyd_RANS_Gen< MODELE >::complete_viscosity_field(), Traitement_particulier_NS_Pression_VDF::lire(), Traitement_particulier_NS_Pression_VEF::lire(), Champ_Fonc_reprise_IJK::readOn(), Champ_Fonc_reprise::readOn(), and Champ_P1iP1B_implementation::valeur_aux_sommets().
domaine_Cl_dis() [1/2]
const Domaine_Cl_dis_base & Champ_Inc_base::domaine_Cl_dis () const
References Equation_base::domaine_Cl_dis(), MorEqn::equation(), mon_dom_cl_dis, TRUST_Ref< _CLASSE_ >::non_nul(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Flux_2groupes_PolyMAC_P0::ajouter_blocs(), Injection_QDM_nulle_PolyMAC_P0::ajouter_blocs(), Injection_QDM_nulle_VDF::ajouter_blocs(), Diffusion_croisee_echelle_temp_taux_diss_turb_PolyMAC_P0::ajouter_blocs(), Dispersion_bulles_PolyMAC_P0::ajouter_blocs(), Op_Diff_PolyMAC_P0P1NC_Face::ajouter_blocs_ext(), Champ_Elem_PolyMAC_P0::calc_grad(), Op_Evanescence_Homogene_PolyMAC_P0_Face::calc_grad_alpha_elem(), Op_Evanescence_Homogene_PolyMAC_P0_Face::calc_grad_alpha_faces(), grad_Champ_Face_PolyMAC_P0::calc_gradfve(), Champ_P1NC::calcul_critere_Q(), Champ_Face_VDF::calcul_duidxj(), Champ_P1NC::gradient(), Sonde::init_bords(), Champ_Face_base::init_fcl(), Champ_Elem_PolyMAC_P0::init_grad(), Champ_Face_PolyMAC::interp_gve(), Champ_Face_PolyMAC::interp_ve(), Sonde::mettre_a_jour_bords(), Operateur_base::ouvrir_fichier(), grad_Champ_Face_PolyMAC_P0::update_tab_grad(), Champ_Face_PolyMAC_P0::update_ve2(), valeur_aux_bords(), and Champ_Face_VDF::verifie_valeurs_cl().
domaine_Cl_dis() [2/2]
Domaine_Cl_dis_base & Champ_Inc_base::domaine_Cl_dis ()
References Equation_base::domaine_Cl_dis(), MorEqn::equation(), mon_dom_cl_dis, TRUST_Ref< _CLASSE_ >::non_nul(), and TRUST_Ref< _CLASSE_ >::valeur().
domaine_dis_base()
const Domaine_dis_base & Champ_Inc_base::domaine_dis_base () const inline override virtual
Reimplemented from Champ_base.
References le_dom_VF, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Terme_Source_Solide_SWIFT_VDF::calcul_moyenne(), EF_discretisation::creer_champ_vorticite(), PolyMAC_P0_discretisation::creer_champ_vorticite(), VDF_discretisation::creer_champ_vorticite(), VEF_discretisation::creer_champ_vorticite(), domaine(), Champ_front_calc::domaine_dis(), Champ_front_contact_VEF::domaine_dis(), Champ_Elem_DG::fixer_nb_valeurs_nodales(), Champ_Elem_PolyMAC::fixer_nb_valeurs_nodales(), Champ_Elem_PolyMAC_P0P1NC::fixer_nb_valeurs_nodales(), Champ_Face_PolyMAC::fixer_nb_valeurs_nodales(), Champ_implementation::get_domaine_dis(), Champ_Elem_DG::imprime(), Champ_P0_EF::imprime(), Champ_P1_EF::imprime(), Champ_Q1_EF::imprime(), Champ_Elem_PolyMAC::imprime(), Champ_Som_PolyMAC::imprime(), Terme_Source_Solide_SWIFT_VDF::init_calcul_moyenne(), Ch_front_var_instationnaire_dep::initialiser(), Champ_P0_VDF::remplir_coord_noeuds(), Precond_local::res_syst_loc_hybride(), resize_val_bord(), PolyMAC_P0_discretisation::taux_cisaillement(), Champ_Elem_PolyMAC::trace(), valeur_a(), Champ_Elem_DG::valeur_aux(), valeur_aux(), valeur_aux_bords(), and valeur_aux_compo().
domaine_vf()
const Domaine_VF & Champ_Inc_base::domaine_vf () const inline
References le_dom_VF, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Champ_Face_PolyMAC::calcul_S_barre(), Domaine_Cl_PolyMAC::imposer_cond_lim(), Champ_Face_PolyMAC::init_ra(), Champ_Face_PolyMAC::init_va(), Champ_Face_PolyMAC::interp_gve(), Champ_Face_PolyMAC::interp_ve(), Champ_Fonc_Elem_PolyMAC_P0_TC::me_calculer(), Champ_Fonc_Elem_PolyMAC_P0_rot::me_calculer_2D(), Champ_Fonc_Elem_PolyMAC_P0_rot::me_calculer_3D(), Champ_Face_PolyMAC::trace(), Champ_Face_PolyMAC::valeur_aux_elems_(), Champ_Face_PolyMAC::valeur_aux_elems_compo(), and Champ_Face_PolyMAC::valeur_aux_faces().
trace()
DoubleTab & Champ_Inc_base::trace (const Frontiere_dis_base & , DoubleTab & x, double tps, int distant) const override virtual
voir Champ_base Cas particulier (malheureusement) du Champ_P0_VDF :
Si la frontiere est un raccord, le resultat est calcule sur le raccord associe. Dans ce cas, le DoubleTab x doit etre dimensionne sur le raccord associe.
Reimplemented from Champ_base.
Reimplemented in Champ_Face_PolyMAC, Champ_Face_PolyMAC_P0, Champ_Face_PolyMAC_P0P1NC, Champ_Face_VDF, Champ_P1_isoP1Bulle, Champ_P1NC, Champ_Q1NC, and Champ_Elem_PolyMAC.
References Objet_U::que_suis_je().
remplir_coord_noeuds_et_polys()
int Champ_Inc_base::remplir_coord_noeuds_et_polys (DoubleTab & , IntVect &) const virtual
NE FAIT RIEN Methode a surcharger.
Parameters
(DoubleTab&)
(IntVect&)
Returns
(int) renvoie toujours 0
Reimplemented in Champ_Inc_P0_base, Champ_Inc_P1_base, Champ_Inc_Q1_base, Champ_Face_PolyMAC, Champ_Face_VDF, Champ_P1NC, and Champ_Q1NC.
Referenced by Champ_Fonc_reprise_IJK::remplir_coord_noeuds_et_polys(), Champ_Fonc_reprise::remplir_coord_noeuds_et_polys(), and remplir_coord_noeuds_et_polys_compo().
remplir_coord_noeuds_et_polys_compo()
int Champ_Inc_base::remplir_coord_noeuds_et_polys_compo (DoubleTab & coord, IntVect & poly, int) const virtual
Simple appel a: Champ_Inc_base::remplir_coord_noeuds_et_polys(DoubleTab&,IntVect& poly)
Parameters
(DoubleTab& coord)
(IntVect& poly)
(int)
Returns
(int) code de retour propage
References remplir_coord_noeuds_et_polys().
Referenced by affecter_compo().
remplir_coord_noeuds()
virtual DoubleTab & Champ_Inc_base::remplir_coord_noeuds (DoubleTab &) const pure virtual
Implemented in Champ_P0_VDF, Champ_P1_isoP1Bulle, Champ_Inc_P0_base, Champ_Inc_P1_base, Champ_Inc_Q1_base, Champ_Face_PolyMAC, Champ_Face_VDF, Champ_P1NC, and Champ_Q1NC.
Referenced by affecter_(), Solveur_Masse_base::appliquer(), Masse_DG_base::appliquer_coef(), Masse_PolyMAC_base::appliquer_coef(), Champ_Fonc_reprise_IJK::remplir_coord_noeuds(), Champ_Fonc_reprise::remplir_coord_noeuds(), and remplir_coord_noeuds_compo().
remplir_coord_noeuds_compo()
DoubleTab & Champ_Inc_base::remplir_coord_noeuds_compo (DoubleTab & coord, int) const virtual
Simple appel a Champ_Inc_base::remplir_coord_noeuds(DoubleTab&)
Parameters
(DoubleTab& coord) coordonnees des noeuds a modifier
(int) l'index de la composante a modifier
Returns
(DoubleTab&)
References remplir_coord_noeuds().
Referenced by affecter_compo().
integrale_espace()
double Champ_Inc_base::integrale_espace (int ncomp) const virtual
Reimplemented in Champ_P0_VDF.
References Process::exit(), and Objet_U::que_suis_je().
domaine()
const Domaine & Champ_Inc_base::domaine () const
References Domaine_dis_base::domaine(), and domaine_dis_base().
Referenced by Champ_Face_PolyMAC_P0::affecter_(), Champ_P1NC::affecter_(), Champ_Elem_DG::affecter_(), Champ_Elem_PolyMAC::affecter_(), Champ_Elem_PolyMAC_P0P1NC::affecter_(), Op_Conv_ALE_VEF::associer(), Operateur_Conv_sensibility::associer(), Op_Conv_ALE::associer(), Champ_Elem_DG::associer_domaine_dis_base(), Champ_Elem_DG::build_mass_matrix(), Champ_Elem_DG::build_transition_matrix(), Champ_Elem_PolyMAC_P0::calc_grad(), Champ_Face_PolyMAC::calcul_S_barre(), Champ_P1NC::calculer_integrale_volumique(), Champ_Elem_DG::compute_stab_param(), Champ_Elem_DG::eval_bfunc(), Champ_Elem_DG::eval_bfunc_on_facets(), Champ_Elem_DG::eval_elem(), Champ_Elem_DG::eval_grad_bfunc(), Champ_Elem_DG::eval_grad_bfunc_on_facets(), Champ_Elem_DG::eval_invMassMatrix(), Champ_P1NC_implementation::filtrer_H1(), Champ_P1NC_implementation::filtrer_resu(), Champ_Elem_DG::fixer_nb_valeurs_nodales(), Champ_Elem_PolyMAC::fixer_nb_valeurs_nodales(), Champ_Elem_PolyMAC_P0P1NC::fixer_nb_valeurs_nodales(), Champ_Face_PolyMAC::fixer_nb_valeurs_nodales(), Champ_Inc_P1_base::fixer_nb_valeurs_nodales(), Champ_Inc_Q1_base::fixer_nb_valeurs_nodales(), Champ_Face_base::get_elem_vector(), Champ_Face_base::get_elem_vector_field(), Champ_Elem_DG::imprime(), Champ_P0_EF::imprime(), Champ_P1_EF::imprime(), Champ_Q1_EF::imprime(), Champ_Elem_PolyMAC::imprime(), Champ_Som_PolyMAC::imprime(), Champ_Elem_PolyMAC_P0P1NC::init_auxiliary_variables(), Champ_Inc_P0_base::init_fcl(), Champ_Face_base::init_fcl(), Champ_Elem_PolyMAC_P0::init_grad(), Champ_Face_PolyMAC::init_ra(), Champ_Face_PolyMAC::init_va(), Champ_Face_PolyMAC_P0::init_ve2(), Champ_Face_PolyMAC::interp_gve(), Champ_Face_PolyMAC::interp_ve(), Champ_Face_PolyMAC_P0P1NC::interp_ve(), Champ_P0_VDF::remplir_coord_noeuds(), Champ_Elem_PolyMAC_P0::reprendre(), Champ_Face_PolyMAC_P0::reprendre(), Champ_Face_PolyMAC::trace(), Champ_Face_PolyMAC_P0::trace(), Champ_Elem_PolyMAC::trace(), Champ_Face_PolyMAC_P0::update_ve(), Champ_Face_PolyMAC_P0::update_ve2(), Champ_Face_PolyMAC_P0::v_norm(), Champ_Face_VDF::v_norm(), valeur_a(), Champ_Elem_DG::valeur_aux(), valeur_aux(), valeur_aux_bords(), valeur_aux_compo(), Champ_Elem_DG::valeur_aux_elems(), Champ_Face_PolyMAC::valeur_aux_faces(), Champ_Face_PolyMAC_P0P1NC::valeur_aux_faces(), and Champ_Elem_PolyMAC::valeur_aux_faces().
derivees() [1/2]
const tabs_t & Champ_Inc_base::derivees () const inline
References deriv_.
Referenced by Flux_2groupes_PolyMAC_P0::ajouter_blocs(), Variation_rho::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::ajouter_blocs(), Solveur_Masse_Elem_proto::ajouter_blocs_proto(), Fluide_reel_base::calculate_fluid_properties_enthalpie(), Fluide_reel_base::calculate_fluid_properties_enthalpie_incompressible(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::dimensionner_blocs(), Op_Conv_VDF_base::dimensionner_blocs_elem(), and Solveur_Masse_Elem_proto::dimensionner_blocs_proto().
derivees() [2/2]
tabs_t & Champ_Inc_base::derivees () inline
References deriv_.
val_bord()
DoubleTab & Champ_Inc_base::val_bord () inline
References val_bord_.
Referenced by Fluide_reel_base::calculate_fluid_properties_enthalpie(), and Fluide_reel_base::calculate_fluid_properties_enthalpie_incompressible().
init_champ_calcule()
void Champ_Inc_base::init_champ_calcule (const Objet_U & obj, fonc_calc_t fonc)
References fonc_calc_, fonc_calc_init_, obj_calc_, and resize_val_bord().
Referenced by Equation_base::init_champ_conserve(), Energie_Multiphase::init_champ_convecte(), and Milieu_composite::initialiser().
reset_champ_calcule()
void Champ_Inc_base::reset_champ_calcule () inline
References fonc_calc_init_.
Referenced by Equation_base::mettre_a_jour_champs_conserves().
resize_val_bord()
void Champ_Inc_base::resize_val_bord ()
References domaine_dis_base(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), val_bord_, and valeurs().
Referenced by init_champ_calcule(), and Fluide_reel_base::initialiser().
set_val_bord_fluide_multiphase()
void Champ_Inc_base::set_val_bord_fluide_multiphase (const bool flag) inline
References bord_fluide_multiphase_.
Referenced by Fluide_reel_base::initialiser().
valeur_aux_bords()
DoubleTab Champ_Inc_base::valeur_aux_bords () const override virtual
renvoie la valeur du champ aux faces de bord
Reimplemented from Champ_base.
References bord_fluide_multiphase_, Nom::debute_par(), domaine(), domaine_Cl_dis(), domaine_dis_base(), Process::exit(), fonc_calc_, Field_base::le_nom(), Domaine_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Front_VF::nb_faces_tot(), Front_VF::num_face(), Objet_U::que_suis_je(), TRUSTTab< _TYPE_, _SIZE_ >::ref(), val_bord_, and valeurs().
Referenced by Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::ajouter_blocs(), Source_Travail_pression_Elem_base::ajouter_blocs(), Fluide_reel_base::calculate_fluid_properties_enthalpie(), Fluide_reel_base::calculate_fluid_properties_enthalpie_incompressible(), Masse_Multiphase::calculer_alpha_rho(), Energie_Multiphase::calculer_alpha_rho_e(), Energie_Multiphase::calculer_alpha_rho_h(), Energie_cinetique_turbulente::calculer_alpha_rho_k(), Energie_cinetique_turbulente_WIT::calculer_alpha_rho_k_WIT(), Equation_base::calculer_champ_conserve(), Taux_dissipation_turbulent::calculer_omega(), Echelle_temporelle_turbulente::calculer_tau(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::mettre_a_jour(), and Op_Conv_VDF_base::mettre_a_jour().
creer_espace_distant()
virtual void Champ_Inc_base::creer_espace_distant (int dummy) inline virtual
set_via_ch_fonc_reprise()
void Champ_Inc_base::set_via_ch_fonc_reprise () inline
References via_ch_fonc_reprise_.
Referenced by Champ_Fonc_reprise::readOn().
via_ch_fonc_reprise()
bool Champ_Inc_base::via_ch_fonc_reprise () const inline
References via_ch_fonc_reprise_.
Referenced by Champ_Elem_PolyMAC_P0::reprendre(), Champ_Elem_PolyMAC_P0P1NC::reprendre(), Champ_Face_PolyMAC_P0::reprendre(), and Champ_Face_PolyMAC_P0P1NC::reprendre().
PDI_save_type()
void Champ_Inc_base::PDI_save_type (bool b) inline
References PDI_save_type_.
Referenced by Transport_Interfaces_FT_Disc::discretiser().
data_a_sauvegarder()
std::vector< YAML_data > Champ_Inc_base::data_a_sauvegarder () const virtual
for PDI IO: retrieve name, type and dimensions of the field to save/restore.
References get_PDI_dname(), Nom::getString(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), PDI_save_type_, YAML_data::set_save_field_type(), and valeurs().
Referenced by Transport_Interfaces_FT_Disc_interne::data_a_sauvegarder(), Equation_base::data_a_sauvegarder(), and Navier_Stokes_std::data_a_sauvegarder().
get_PDI_dname()
Nom Champ_Inc_base::get_PDI_dname () const
for PDI IO: retrieve the name of the HDF5 dataset in which the field will be saved or be restored from
References MorEqn::equation(), Process::exit(), Field_base::le_nom(), Probleme_U::le_nom(), MorEqn::mon_equation_non_nul(), PDI_dname_, and Equation_base::probleme().
Referenced by data_a_sauvegarder(), reprendre(), and sauvegarder().
set_PDI_dname()
void Champ_Inc_base::set_PDI_dname (const Nom & name) inline
References PDI_dname_.
creer_tableau_distribue()
void Champ_Inc_base::creer_tableau_distribue (const MD_Vector & md, RESIZE_OPTIONS opt = RESIZE_OPTIONS::COPY_INIT) protected virtual
References MD_Vector_tools::creer_tableau_distribue(), Process::exit(), futur(), TRUSTVect< _TYPE_, _SIZE_ >::get_md_vector(), Field_base::nb_compo_, nb_valeurs_temporelles(), MD_Vector::non_nul(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by Champ_Elem_DG::fixer_nb_valeurs_nodales(), Champ_Inc_P0_base::fixer_nb_valeurs_nodales(), Champ_Elem_PolyMAC::fixer_nb_valeurs_nodales(), Champ_Elem_PolyMAC_P0P1NC::fixer_nb_valeurs_nodales(), Champ_Face_PolyMAC::fixer_nb_valeurs_nodales(), Champ_Face_PolyMAC_P0::fixer_nb_valeurs_nodales(), Champ_Face_PolyMAC_P0P1NC::fixer_nb_valeurs_nodales(), Champ_Q1NC::fixer_nb_valeurs_nodales(), Champ_Inc_P1_base::fixer_nb_valeurs_nodales(), Champ_Inc_Q1_base::fixer_nb_valeurs_nodales(), Champ_P1NC::fixer_nb_valeurs_nodales(), Champ_Face_VDF::fixer_nb_valeurs_nodales(), and Champ_P1_isoP1Bulle::fixer_nb_valeurs_nodales().
Member Data Documentation
info_obj
const Type_info Champ_Inc_base::info_obj static
les_valeurs
Roue_ptr Champ_Inc_base::les_valeurs protected
Referenced by affecter_(), Champ_Face_PolyMAC_P0::affecter_(), avancer(), changer_temps(), changer_temps_futur(), changer_temps_passe(), fixer_nb_valeurs_temporelles(), futur(), lire_donnees(), mettre_a_jour(), nb_valeurs_temporelles(), passe(), reculer(), recuperer_temps_futur(), recuperer_temps_passe(), and valeurs().
mon_dom_cl_dis
TRUST_Ref< Domaine_Cl_dis_base *> Champ_Inc_base::mon_dom_cl_dis protected
Referenced by associer_domaine_cl_dis(), domaine_Cl_dis(), Champ_Inc_P0_base::init_fcl(), Champ_Face_PolyMAC::valeur_aux_elems_(), and Champ_Face_PolyMAC::valeur_aux_elems_compo().
le_dom_VF
TRUST_Ref< Domaine_VF *> Champ_Inc_base::le_dom_VF protected
Referenced by Champ_Face_PolyMAC::affecter_(), Champ_Elem_DG::affecter_(), Champ_Elem_PolyMAC::affecter_(), Champ_Elem_DG::allocate_mass_matrix(), Champ_Elem_DG::allocate_transition_matrix(), Champ_Elem_DG::associer_domaine_dis_base(), associer_domaine_dis_base(), Champ_Elem_DG::build_mass_matrix(), Champ_Elem_DG::build_transition_matrix(), Champ_Elem_PolyMAC_P0::calc_grad(), Champ_Q1_EF::calcul_y_plus(), Champ_Elem_DG::compute_stab_param(), domaine_dis_base(), Champ_P0_EF::domaine_EF(), Champ_P1_EF::domaine_EF(), Champ_Q1_EF::domaine_EF(), Champ_Elem_PolyMAC_P0::domaine_PolyMAC_P0(), Champ_Face_PolyMAC_P0::domaine_PolyMAC_P0(), Champ_Elem_PolyMAC_P0P1NC::domaine_PolyMAC_P0P1NC(), Champ_Face_PolyMAC_P0P1NC::domaine_PolyMAC_P0P1NC(), Champ_P0_VDF::domaine_VDF(), Champ_Face_VDF::domaine_vdf(), Champ_P0_VEF::domaine_vef(), Champ_P1_isoP1Bulle::domaine_vef(), Champ_P1NC::domaine_vef(), Champ_Q1NC::domaine_vef(), domaine_vf(), Champ_Elem_DG::eval_bfunc(), Champ_Elem_DG::eval_bfunc_on_facets(), Champ_Elem_DG::eval_elem(), Champ_Elem_DG::eval_grad_bfunc(), Champ_Elem_DG::eval_grad_bfunc_on_facets(), Champ_Elem_DG::eval_invMassMatrix(), Champ_Face_base::get_elem_vector(), Champ_Face_base::get_elem_vector_field(), Champ_Face_base::init_fcl(), Champ_Elem_PolyMAC_P0::init_grad(), Champ_Elem_PolyMAC_P0P1NC::nb_valeurs_nodales(), Champ_Elem_PolyMAC_P0::reprendre(), Champ_Face_PolyMAC_P0::reprendre(), Champ_Inc_P0_base::valeur_au_bord(), Champ_Elem_DG::valeur_aux(), Champ_Elem_DG::valeur_aux_elems(), and Champ_Elem_PolyMAC::valeur_aux_faces().
fonc_calc_
fonc_calc_t Champ_Inc_base::fonc_calc_ protected
Referenced by init_champ_calcule(), mettre_a_jour(), and valeur_aux_bords().
fonc_calc_init_
int Champ_Inc_base::fonc_calc_init_ = 0 protected
Referenced by init_champ_calcule(), mettre_a_jour(), and reset_champ_calcule().
obj_calc_
RefObjU Champ_Inc_base::obj_calc_ protected
Referenced by init_champ_calcule(), and mettre_a_jour().
val_bord_
DoubleTab Champ_Inc_base::val_bord_ protected
Referenced by mettre_a_jour(), resize_val_bord(), val_bord(), and valeur_aux_bords().
deriv_
tabs_t Champ_Inc_base::deriv_ protected
Referenced by derivees(), and mettre_a_jour().
bord_fluide_multiphase_
bool Champ_Inc_base::bord_fluide_multiphase_ = false protected
Referenced by set_val_bord_fluide_multiphase(), and valeur_aux_bords().
via_ch_fonc_reprise_
bool Champ_Inc_base::via_ch_fonc_reprise_ = false protected
Referenced by set_via_ch_fonc_reprise(), and via_ch_fonc_reprise().
PDI_save_type_
bool Champ_Inc_base::PDI_save_type_ = false protected
Referenced by data_a_sauvegarder(), PDI_save_type(), and sauvegarder().
PDI_dname_
Nom Champ_Inc_base::PDI_dname_ protected
Referenced by get_PDI_dname(), and set_PDI_dname().