TrioCFD: SourceFiltree_FT_disc_base Class Reference
SourceFiltree_FT_disc_base Class Reference
#include <SourceFiltree_FT_disc_base.h>
Protected Member Functions
Entree & lire_donnees (Entree &)
Detailed Description
phase, du temps, de la position, ...
See also
Probleme_FT_Disc_gen
Constructor & Destructor Documentation
SourceFiltree_FT_disc_base()
SourceFiltree_FT_disc_base::SourceFiltree_FT_disc_base ()
References Objet_U::dimension, dimension_, fI_xyz_t, and temps_.
~SourceFiltree_FT_disc_base()
SourceFiltree_FT_disc_base::~SourceFiltree_FT_disc_base ()
References dimension_, and fI_xyz_t.
Member Function Documentation
lire_donnees()
Entree & SourceFiltree_FT_disc_base::lire_donnees (Entree & is) protected
Lit les parametres du terme source a partir d'un flot d'entree.
Parameters
(Entree& is) un flot d'entree
References Parser::addVar(), dimension_, ecrire_donnees(), Process::exit(), fI_xyz_t, Nom::getChar(), Parser::getString(), Process::je_suis_maitre(), nom_eq_transport_, Parser::parseString(), and Motcles::search().
Referenced by SourceFiltree_FT_disc_VEF_P1NC::lire().
ecrire_donnees()
Sortie & SourceFiltree_FT_disc_base::ecrire_donnees (Sortie & os) const protected
References dimension_, fI_xyz_t, and Parser::getString().
Referenced by lire_donnees(), and SourceFiltree_FT_disc_VEF_P1NC::printOn().
Member Data Documentation
fI_xyz_t
Parser** SourceFiltree_FT_disc_base::fI_xyz_t protected
Referenced by SourceFiltree_FT_disc_VEF_P1NC::ajouter(), ecrire_donnees(), lire_donnees(), SourceFiltree_FT_disc_base(), and ~SourceFiltree_FT_disc_base().
nom_eq_transport_
Motcle SourceFiltree_FT_disc_base::nom_eq_transport_ protected
Referenced by SourceFiltree_FT_disc_VEF_P1NC::associer_pb(), and lire_donnees().
temps_
double SourceFiltree_FT_disc_base::temps_ protected
Referenced by SourceFiltree_FT_disc_VEF_P1NC::ajouter(), SourceFiltree_FT_disc_VEF_P1NC::mettre_a_jour(), and SourceFiltree_FT_disc_base().
dimension_
int SourceFiltree_FT_disc_base::dimension_ protected
Referenced by SourceFiltree_FT_disc_VEF_P1NC::ajouter(), ecrire_donnees(), lire_donnees(), SourceFiltree_FT_disc_base(), and ~SourceFiltree_FT_disc_base().