TrioCFD: Intersection_Interface_ijk Class Reference
Intersection_Interface_ijk Class Reference abstract
#include <Intersection_Interface_ijk.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Intersection_Interface_ijk()
Intersection_Interface_ijk::Intersection_Interface_ijk ()
~Intersection_Interface_ijk()
Intersection_Interface_ijk::~Intersection_Interface_ijk () override
Member Function Documentation
info()
const Type_info * Intersection_Interface_ijk::info () static
get_info()
const Type_info * Intersection_Interface_ijk::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
Reimplemented in Intersection_Interface_ijk_face, and Intersection_Interface_ijk_cell.
self_cast() [1/2]
Intersection_Interface_ijk & Intersection_Interface_ijk::self_cast (Objet_U & r) static
self_cast() [2/2]
const Intersection_Interface_ijk & Intersection_Interface_ijk::self_cast (const Objet_U & r) static
printOn()
Sortie & Intersection_Interface_ijk::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
Reimplemented in Intersection_Interface_ijk_face, and Intersection_Interface_ijk_cell.
readOn()
Entree & Intersection_Interface_ijk::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
Reimplemented in Intersection_Interface_ijk_face, and Intersection_Interface_ijk_cell.
initialize()
virtual int Intersection_Interface_ijk::initialize (const Domaine_IJK & splitting, const IJK_Interfaces & interfaces) pure virtual
Implemented in Intersection_Interface_ijk_face, and Intersection_Interface_ijk_cell.
get_position_interpolation_normal_interf() [1/2]
Vecteur3 Intersection_Interface_ijk::get_position_interpolation_normal_interf (const Vecteur3 & position_on_interf, const Vecteur3 & normal_on_interf, const double dist) static
Referenced by Facettes_Interp_FT::calcul_coefficient_interpolation_facette_cut_cell(), Facettes_Interp_FT::calcul_coefficient_interpolation_facette_cut_cell_second_order(), and Corrige_flux_FT_temperature_conv::calcul_temperature_flux_interface().
get_position_interpolation_normal_interf() [2/2]
void Intersection_Interface_ijk::get_position_interpolation_normal_interf (const DoubleTab & position_on_interf, const DoubleTab & normal_on_interf, const double dist, DoubleTab & positions) static
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), and TRUSTTab< _TYPE_, _SIZE_ >::resize().
n()
int Intersection_Interface_ijk::n () const inline
References n_diph_.
Referenced by Corrige_flux_FT_temperature_conv::initialize(), Corrige_flux_FT_temperature_conv::interp_back_to_bary_faces(), Corrige_flux_FT_temperature_conv::update(), and Corrige_flux_FT_temperature_conv::update_temperature_ghost().
pos_interf()
const DoubleTab & Intersection_Interface_ijk::pos_interf () const inline
References positions_on_interf_.
Referenced by Corrige_flux_FT_temperature_conv::calcul_temp_flux_interf_pour_bary_cell(), and Corrige_flux_FT_temperature_conv::calcul_temp_flux_interf_pour_bary_face().
norm_interf()
const DoubleTab & Intersection_Interface_ijk::norm_interf () const inline
References normal_on_interf_.
Referenced by Corrige_flux_FT_temperature_conv::calcul_temp_flux_interf_pour_bary_cell(), Corrige_flux_FT_temperature_conv::calcul_temp_flux_interf_pour_bary_face(), and Corrige_flux_FT_temperature_conv::extrapolation_amont_1_depuis_l_interface().
dist_interf()
const DoubleTab & Intersection_Interface_ijk::dist_interf () const inline
References dist_to_interf_.
Referenced by Corrige_flux_FT_temperature_subresolution::compute_temperature_cell_centre(), Corrige_flux_FT_temperature_conv::interp_back_to_bary_faces(), and Corrige_flux_FT_temperature_conv::update_temperature_ghost().
set_pas_a_jour()
virtual void Intersection_Interface_ijk::set_pas_a_jour () inline virtual
Reimplemented in Intersection_Interface_ijk_cell.
References projected_on_interface_flag_.
is_a_jour()
virtual bool Intersection_Interface_ijk::is_a_jour () const inline virtual
Reimplemented in Intersection_Interface_ijk_cell.
References projected_on_interface_flag_.
projete_interface()
void Intersection_Interface_ijk::projete_interface (const Vecteur3 & normale, const Vecteur3 & point_plan, const Vecteur3 & coo, Vecteur3 & posit_proj) static
References Vecteur3::produit_scalaire().
Referenced by Intersection_Interface_ijk_face::calcul_projection_bary_face_mouillee_interface_moy(), Intersection_Interface_ijk_cell::calcul_projection_centre_faces_sur_interface_moy(), and Intersection_Interface_ijk_cell::calcul_projection_centre_sur_interface_moy().
distance_point_point()
void Intersection_Interface_ijk::distance_point_point (const Vecteur3 & point_1, const Vecteur3 & point_2, double & distance) static
References Vecteur3::produit_scalaire().
Referenced by Intersection_Interface_ijk_face::calcul_projection_bary_face_mouillee_interface_moy(), and distance_point_point_signe().
distance_point_point_signe()
void Intersection_Interface_ijk::distance_point_point_signe (const Vecteur3 & point_1, const Vecteur3 & point_2, const Vecteur3 & normal_interf, double & distance) static
References distance_point_point(), and Vecteur3::produit_scalaire().
Referenced by Intersection_Interface_ijk_cell::calcul_projection_centre_faces_sur_interface_moy(), and Intersection_Interface_ijk_cell::calcul_projection_centre_sur_interface_moy().
get_mean_interface_cell()
void Intersection_Interface_ijk::get_mean_interface_cell (const int elem, Vecteur3 & normale, Vecteur3 & bary) const protected
References Domaine_IJK::convert_packed_to_ijk_cell(), interfaces_, IJK_Interfaces::nI(), splitting_, and IJK_Interfaces::xI().
Referenced by Intersection_Interface_ijk_cell::calcul_projection_centre_faces_sur_interface_moy(), Intersection_Interface_ijk_cell::calcul_projection_centre_sur_interface_moy(), and Intersection_Interface_ijk_face::compute_mean_interface_face().
Member Data Documentation
info_obj
const Type_info Intersection_Interface_ijk::info_obj static
interfaces_
const IJK_Interfaces* Intersection_Interface_ijk::interfaces_ = nullptr protected
Referenced by Intersection_Interface_ijk_face::calcul_projection_bary_face_mouillee_interface_moy(), get_mean_interface_cell(), Intersection_Interface_ijk_face::initialize(), Intersection_Interface_ijk_cell::initialize(), Intersection_Interface_ijk_cell::update_interpolations_cell_centres_on_interface(), Intersection_Interface_ijk_cell::update_interpolations_cell_centres_on_interface_new(), Intersection_Interface_ijk_cell::update_interpolations_cell_faces_on_interface(), and Intersection_Interface_ijk_cell::update_interpolations_cell_faces_on_interface_new().
splitting_
const Domaine_IJK* Intersection_Interface_ijk::splitting_ = nullptr protected
Referenced by Intersection_Interface_ijk_face::calcul_projection_bary_face_mouillee_interface_moy(), Intersection_Interface_ijk_cell::calcul_projection_centre_faces_sur_interface_moy(), Intersection_Interface_ijk_cell::calcul_projection_centre_sur_interface_moy(), Intersection_Interface_ijk_face::compute_mean_interface_face(), get_mean_interface_cell(), Intersection_Interface_ijk_face::initialize(), and Intersection_Interface_ijk_cell::initialize().
n_diph_
int Intersection_Interface_ijk::n_diph_ = 1 protected
Referenced by Intersection_Interface_ijk_face::calcul_projection_bary_face_mouillee_interface_moy(), Intersection_Interface_ijk_cell::calcul_projection_centre_faces_sur_interface_moy(), Intersection_Interface_ijk_cell::calcul_projection_centre_sur_interface_moy(), Intersection_Interface_ijk_cell::compute_face_to_correct(), Intersection_Interface_ijk_cell::initialize(), and n().
positions_on_interf_
DoubleTab Intersection_Interface_ijk::positions_on_interf_ protected
Referenced by Intersection_Interface_ijk_face::maj_interpolation_coo_on_interfaces(), pos_interf(), and Intersection_Interface_ijk_cell::update_interpolations_cell_centres_on_interface().
dist_to_interf_
DoubleTab Intersection_Interface_ijk::dist_to_interf_ protected
Referenced by dist_interf(), Intersection_Interface_ijk_face::maj_interpolation_coo_on_interfaces(), and Intersection_Interface_ijk_cell::update_interpolations_cell_centres_on_interface().
normal_on_interf_
DoubleTab Intersection_Interface_ijk::normal_on_interf_ protected
Referenced by Intersection_Interface_ijk_face::maj_interpolation_coo_on_interfaces(), norm_interf(), Intersection_Interface_ijk_cell::update_interpolations_cell_centres_on_interface(), and Intersection_Interface_ijk_cell::update_interpolations_cell_faces_on_interface().
projected_on_interface_flag_
bool Intersection_Interface_ijk::projected_on_interface_flag_ = true protected
Referenced by Intersection_Interface_ijk_cell::initialize(), is_a_jour(), Intersection_Interface_ijk_cell::is_a_jour(), Intersection_Interface_ijk_face::maj_interpolation_coo_on_interfaces(), set_pas_a_jour(), Intersection_Interface_ijk_cell::set_pas_a_jour(), and Intersection_Interface_ijk_cell::update_interpolations_cell_centres_on_interface().