TrioCFD: Statistiques_dns_ijk_FT Class Reference
Statistiques_dns_ijk_FT Class Reference
#include <Statistiques_dns_ijk_FT.h>
Public Member Functions
const IJK_Field_double & get_IJK_field (const Motcle &nom) override
const Type_info * get_info () const override
int lire_motcle_non_standard (const Motcle &mot, Entree &is) override
Public Member Functions inherited from Statistiques_dns_ijk
const IJK_Field_double & get_IJK_field (const Motcle &nom) override
const Type_info * get_info () const override
bool is_post_required (const Motcle &nom) const
int lire_motcle_non_standard (const Motcle &mot, Entree &is) override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Public Types inherited from Champs_compris_IJK_interface
using FieldInfo_t = std::tuple< Motcle, Entity, Nature_du_champ, bool >
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
~Statistiques_dns_ijk_FT()
Statistiques_dns_ijk_FT::~Statistiques_dns_ijk_FT ()
Statistiques_dns_ijk_FT()
Statistiques_dns_ijk_FT::Statistiques_dns_ijk_FT ()
References TRUST_Vector< _CLASSE_ >::dimensionner_force(), Statistiques_dns_ijk::noms_moyennes_, noms_moyennes_temperature_, Statistiques_dns_ijk::nval_, and nvalt_.
Member Function Documentation
cree_instance()
Objet_U * Statistiques_dns_ijk_FT::cree_instance () static
taille_memoire()
unsigned Statistiques_dns_ijk_FT::taille_memoire () const override virtual
Reimplemented from Statistiques_dns_ijk.
duplique()
int Statistiques_dns_ijk_FT::duplique () const override virtual
Reimplemented from Statistiques_dns_ijk.
info()
const Type_info * Statistiques_dns_ijk_FT::info () static
get_info()
const Type_info * Statistiques_dns_ijk_FT::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Statistiques_dns_ijk.
self_cast() [1/2]
Statistiques_dns_ijk_FT & Statistiques_dns_ijk_FT::self_cast (Objet_U & r) static
self_cast() [2/2]
const Statistiques_dns_ijk_FT & Statistiques_dns_ijk_FT::self_cast (const Objet_U & r) static
printOn()
Sortie & Statistiques_dns_ijk_FT::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Statistiques_dns_ijk.
References Statistiques_dns_ijk::printOn().
readOn()
Entree & Statistiques_dns_ijk_FT::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Statistiques_dns_ijk.
References Statistiques_dns_ijk::readOn().
associer_probleme()
void Statistiques_dns_ijk_FT::associer_probleme (const Probleme_FTD_IJK_base & ijk_ft)
References Statistiques_dns_ijk::ref_ijk_ft_.
Referenced by Postprocessing_IJK::associer_probleme().
initialize() [1/4]
void Statistiques_dns_ijk_FT::initialize (const Probleme_FTD_IJK_base & ijk_ft, const Domaine_IJK & geom)
References Statistiques_dns_ijk::check_converge_, check_stats_, Statistiques_dns_ijk::dx_, Statistiques_dns_ijk::dy_, Statistiques_dns_ijk::elem_coord_, Process::exit(), Domaine_IJK::get_constant_delta(), Domaine_IJK::get_delta(), Domaine_IJK::get_nb_elem_tot(), Domaine_IJK::get_node_coordinates(), Statistiques_dns_ijk::integrale_temporelle_, integrale_temporelle_temperature_, Process::je_suis_maitre(), Statistiques_dns_ijk::moyenne_spatiale_instantanee_, moyenne_spatiale_instantanee_temperature_, nb_thermal_fields_, Statistiques_dns_ijk::nval_, nvalt_, Objet_U::que_suis_je(), Statistiques_dns_ijk::ref_ijk_ft_, TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), Statistiques_dns_ijk::t_integration_, Statistiques_dns_ijk::tab_dz_, and Statistiques_dns_ijk::vit_moy_.
Referenced by Postprocessing_IJK::initialise_stats(), and initialize().
initialize() [2/4]
void Statistiques_dns_ijk_FT::initialize (const Probleme_FTD_IJK_base & ijk_ft, const Domaine_IJK & splitting, const int check_stats)
References alloc_fields(), check_stats_, and initialize().
alloc_fields()
void Statistiques_dns_ijk_FT::alloc_fields ()
References Champs_compris_IJK::ajoute_champ_vectoriel(), Statistiques_dns_ijk::champs_compris_, Statistiques_dns_ijk::domaine_ijk_, Nom::getString(), and Statistiques_dns_ijk::vect_post_fields_.
Referenced by initialize().
completer_print()
Sortie & Statistiques_dns_ijk_FT::completer_print (Sortie & os) const override virtual
Reimplemented from Statistiques_dns_ijk.
References Statistiques_dns_ijk::elem_coord_, integrale_temporelle_temperature_, Process::je_suis_maitre(), nb_thermal_fields_, noms_moyennes_temperature_, nvalt_, TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and Statistiques_dns_ijk::t_integration_.
completer_read()
void Statistiques_dns_ijk_FT::completer_read (Param & param) override virtual
Reimplemented from Statistiques_dns_ijk.
References Param::ajouter_non_std().
lire_motcle_non_standard()
int Statistiques_dns_ijk_FT::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Statistiques_dns_ijk.
References Param::ajouter(), integrale_temporelle_temperature_, Param::lire_avec_accolades(), Statistiques_dns_ijk::lire_motcle_non_standard(), moyenne_spatiale_instantanee_temperature_, nb_thermal_fields_, noms_moyennes_temperature_, Statistiques_dns_ijk::nval_, nvalt_, Objet_U::que_suis_je(), and TRUSTTab< _TYPE_, _SIZE_ >::resize().
update_stat()
void Statistiques_dns_ijk_FT::update_stat (Probleme_FTD_IJK_base & cas, const double dt)
References Probleme_FTD_IJK_base::eq_ns(), Postprocessing_IJK::extended_pl_, Postprocessing_IJK::extended_pressure_computed_, Postprocessing_IJK::extended_pv_, Probleme_FTD_IJK_base::get_post(), Navier_Stokes_FTD_IJK::pressure_, Navier_Stokes_FTD_IJK::terme_repulsion_interfaces_ft_, Navier_Stokes_FTD_IJK::terme_source_interfaces_ft_, and Navier_Stokes_FTD_IJK::velocity_.
Referenced by Postprocessing_IJK::update_stat_ft().
postraiter()
void Statistiques_dns_ijk_FT::postraiter (Sortie & os, int flag_valeur_instantanee = 0) const
References Statistiques_dns_ijk::postraiter().
Referenced by Postprocessing_IJK::posttraiter_statistiques_plans().
postraiter_thermique()
void Statistiques_dns_ijk_FT::postraiter_thermique (const double t) const
References Option_IJK::DISABLE_DIPHASIQUE, Statistiques_dns_ijk::elem_coord_, integrale_temporelle_temperature_, Process::je_suis_maitre(), moyenne_spatiale_instantanee_temperature_, nb_thermal_fields_, noms_moyennes_temperature_, nvalt_, Sortie_Fichier_base::precision(), Sortie_Fichier_base::setf(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and Statistiques_dns_ijk::t_integration_.
Referenced by Postprocessing_IJK::posttraiter_statistiques_plans().
compute_desequil_alpha()
double Statistiques_dns_ijk_FT::compute_desequil_alpha (const Domaine_IJK & geom_NS, const double portee_wall_repulsion) const
References Statistiques_dns_ijk::elem_coord_, Process::exit(), Domaine_IJK::get_domain_length(), Domaine_IJK::get_origin(), Process::je_suis_maitre(), Statistiques_dns_ijk::moyenne_spatiale_instantanee_, and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
get_IJK_field_vector()
const IJK_Field_vector3_double & Statistiques_dns_ijk_FT::get_IJK_field_vector (const Motcle & nom) override virtual
Reimplemented from Statistiques_dns_ijk.
References Statistiques_dns_ijk::champs_compris_, Champs_compris_IJK::get_champ_vectoriel(), Statistiques_dns_ijk::has_champ_vectoriel(), Statistiques_dns_ijk::ref_ijk_ft_, and Statistiques_dns_ijk::vect_post_fields_.
Referenced by Postprocessing_IJK::get_IJK_field_vector(), and Postprocessing_IJK::get_update_lambda2_and_rot_and_Q().
get_IJK_field()
const IJK_Field_double & Statistiques_dns_ijk_FT::get_IJK_field (const Motcle & nom) override virtual
Retrieve requested field for postprocessing, potentially updating it.
Reimplemented from Statistiques_dns_ijk.
References Statistiques_dns_ijk::champs_compris_, Champs_compris_T< FIELD_TYPE >::get_champ(), and Statistiques_dns_ijk::has_champ().
Referenced by Postprocessing_IJK::get_IJK_field().
initialize() [3/4]
virtual void Statistiques_dns_ijk::initialize (const Domaine_IJK &) inline virtual
Reimplemented from Statistiques_dns_ijk.
initialize() [4/4]
void Statistiques_dns_ijk::initialize (const Domaine_IJK & geom, const double T_KMAX, const double T_KMIN, const double constante_specifique_gaz) virtual
Reimplemented from Statistiques_dns_ijk.
Member Data Documentation
info_obj
const Type_info Statistiques_dns_ijk_FT::info_obj static
check_stats_
int Statistiques_dns_ijk_FT::check_stats_ protected
Referenced by initialize().
nb_thermal_fields_
int Statistiques_dns_ijk_FT::nb_thermal_fields_ protected
Referenced by completer_print(), initialize(), lire_motcle_non_standard(), and postraiter_thermique().
nvalt_
int Statistiques_dns_ijk_FT::nvalt_ protected
Referenced by completer_print(), initialize(), lire_motcle_non_standard(), postraiter_thermique(), and Statistiques_dns_ijk_FT().
moyenne_spatiale_instantanee_temperature_
DoubleTab Statistiques_dns_ijk_FT::moyenne_spatiale_instantanee_temperature_ protected
Referenced by initialize(), lire_motcle_non_standard(), and postraiter_thermique().
integrale_temporelle_temperature_
DoubleTab Statistiques_dns_ijk_FT::integrale_temporelle_temperature_ protected
Referenced by completer_print(), initialize(), lire_motcle_non_standard(), and postraiter_thermique().
noms_moyennes_temperature_
TRUST_Vector< Nom > Statistiques_dns_ijk_FT::noms_moyennes_temperature_ protected
Referenced by completer_print(), lire_motcle_non_standard(), postraiter_thermique(), and Statistiques_dns_ijk_FT().