TrioCFD: Dirichlet_entree_fluide Class Reference
Dirichlet_entree_fluide Class Reference
#include <Dirichlet_entree_fluide_leaves.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Dirichlet
const Type_info * get_info () const override
virtual double val_imp (int i) const
virtual double val_imp (int i, int j) const
void verifie_ch_init_nb_comp () const override
Public Member Functions inherited from Cond_lim_base
virtual int a_mettre_a_jour_ss_pas_dt ()
virtual void associer_domaine_cl_dis_base (const Domaine_Cl_dis_base &)
virtual void associer_fr_dis_base (const Frontiere_dis_base &)
virtual void calculer_coeffs_echange (double temps)
virtual int compatible_avec_discr (const Discretisation_base &) const
Domaine_Cl_dis_base & domaine_Cl_dis ()
const Domaine_Cl_dis_base & domaine_Cl_dis () const
virtual Frontiere_dis_base & frontiere_dis ()
virtual const Frontiere_dis_base & frontiere_dis () const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
void set_modifier_val_imp (int)
virtual void verifie_ch_init_nb_comp () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Cond_lim_base
void err_pas_compatible (const Discretisation_base &) const
void err_pas_compatible (const Equation_base &) const
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
sur l'entree du fluide. Des classes derivees specialiseront la grandeur imposee: vitesse, temperature, concentration, fraction_massique ...
See also
Dirichlet Entree_fluide_vitesse_imposee Entree_fluide_vitesse_imposee_libre, Entree_fluide_temperature_imposee Entree_fluide_T_h_imposee, Entree_fluide_Fluctu_Temperature_imposee Entree_fluide_Flux_Chaleur_Turbulente_imposee, Entree_fluide_K_Eps_impose Entree_fluide_V2_impose, Entree_fluide_concentration_imposee Entree_fluide_fraction_massique_imposee
Constructor & Destructor Documentation
Dirichlet_entree_fluide()
Dirichlet_entree_fluide::Dirichlet_entree_fluide ()
~Dirichlet_entree_fluide()
Dirichlet_entree_fluide::~Dirichlet_entree_fluide () override
Member Function Documentation
info()
const Type_info * Dirichlet_entree_fluide::info () static
get_info()
const Type_info * Dirichlet_entree_fluide::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Dirichlet.
Reimplemented in Entree_fluide_vitesse_imposee_ALE, Frontiere_ouverte_vitesse_vortex, Frontiere_Ouverte_temperature_imposee_Rayo_transp, Frontiere_ouverte_temperature_imposee_rayo_semi_transp, Entree_fluide_K_Eps_impose, Entree_fluide_K_Omega_impose, Entree_fluide_vitesse_imposee, Entree_fluide_vitesse_imposee_libre, Entree_fluide_Fluctu_Temperature_imposee, Entree_fluide_temperature_imposee, Entree_fluide_V2_impose, Entree_fluide_fraction_massique_imposee, Entree_fluide_alpha_impose, Entree_fluide_Flux_Chaleur_Turbulente_imposee, Entree_fluide_temperature_imposee_H, Frontiere_ouverte_rho_u_impose, Entree_fluide_concentration_imposee, and Entree_fluide_T_h_imposee.
self_cast() [1/2]
Dirichlet_entree_fluide & Dirichlet_entree_fluide::self_cast (Objet_U & r) static
self_cast() [2/2]
const Dirichlet_entree_fluide & Dirichlet_entree_fluide::self_cast (const Objet_U & r) static
printOn()
Sortie & Dirichlet_entree_fluide::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Dirichlet.
Reimplemented in Entree_fluide_vitesse_imposee_ALE, Frontiere_ouverte_vitesse_vortex, Frontiere_Ouverte_temperature_imposee_Rayo_transp, Frontiere_ouverte_temperature_imposee_rayo_semi_transp, Entree_fluide_K_Eps_impose, Entree_fluide_K_Omega_impose, Entree_fluide_vitesse_imposee, Entree_fluide_vitesse_imposee_libre, Entree_fluide_Fluctu_Temperature_imposee, Entree_fluide_temperature_imposee, Entree_fluide_V2_impose, Entree_fluide_fraction_massique_imposee, Entree_fluide_alpha_impose, Entree_fluide_Flux_Chaleur_Turbulente_imposee, Entree_fluide_temperature_imposee_H, Frontiere_ouverte_rho_u_impose, Entree_fluide_concentration_imposee, and Entree_fluide_T_h_imposee.
References Objet_U::que_suis_je().
readOn()
Entree & Dirichlet_entree_fluide::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Dirichlet.
Reimplemented in Entree_fluide_vitesse_imposee_ALE, Frontiere_ouverte_vitesse_vortex, Frontiere_Ouverte_temperature_imposee_Rayo_transp, Frontiere_ouverte_temperature_imposee_rayo_semi_transp, Entree_fluide_K_Eps_impose, Entree_fluide_K_Omega_impose, Entree_fluide_vitesse_imposee, Entree_fluide_vitesse_imposee_libre, Entree_fluide_Fluctu_Temperature_imposee, Entree_fluide_temperature_imposee, Entree_fluide_V2_impose, Entree_fluide_fraction_massique_imposee, Entree_fluide_alpha_impose, Entree_fluide_Flux_Chaleur_Turbulente_imposee, Entree_fluide_temperature_imposee_H, Frontiere_ouverte_rho_u_impose, Entree_fluide_concentration_imposee, and Entree_fluide_T_h_imposee.
References Cond_lim_base::readOn().
Referenced by Entree_fluide_K_Eps_impose::readOn(), Entree_fluide_K_Omega_impose::readOn(), Entree_fluide_vitesse_imposee::readOn(), Entree_fluide_Fluctu_Temperature_imposee::readOn(), Entree_fluide_temperature_imposee::readOn(), Entree_fluide_V2_impose::readOn(), Entree_fluide_fraction_massique_imposee::readOn(), Entree_fluide_alpha_impose::readOn(), Entree_fluide_Flux_Chaleur_Turbulente_imposee::readOn(), Entree_fluide_temperature_imposee_H::readOn(), and Entree_fluide_concentration_imposee::readOn().
Member Data Documentation
info_obj
const Type_info Dirichlet_entree_fluide::info_obj static