TrioCFD: Modele_turbulence_hyd_K_Eps_Bicephale Class Reference
Modele_turbulence_hyd_K_Eps_Bicephale Class Reference
#include <Modele_turbulence_hyd_K_Eps_Bicephale.h>
Public Member Functions
virtual Champ_Fonc_base & calculer_viscosite_turbulente (double temps)
virtual Champ_Inc_base & Eps ()
virtual const Champ_Inc_base & Eps () const
const Transport_K_ou_Eps_base & eqn_transp_Eps () const override
Transport_K_ou_Eps_base & eqn_transp_Eps () override
const Transport_K_ou_Eps_base & eqn_transp_K () const override
Transport_K_ou_Eps_base & eqn_transp_K () override
const Type_info * get_info () const override
virtual Champ_Inc_base & K ()
virtual const Champ_Inc_base & K () const
int lire_motcle_non_standard (const Motcle &, Entree &) override
void mettre_a_jour (double) override
int preparer_calcul () override
Public Member Functions inherited from Modele_turbulence_hyd_RANS_Bicephale_base
void associer_seconde_eqn (const Equation_base &)
const Type_info * get_info () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
int reprendre (Entree &is) override
int sauvegarder (Sortie &os) const override
Equation_base & seconde_equation ()
const Type_info * get_info () const override
Public Member Functions inherited from Modele_turbulence_hyd_base
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Type_info * get_info () const override
virtual void imprimer (Sortie &) const
void lire_distance_paroi ()
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual int preparer_calcul ()
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Modele_turbulence_hyd_RANS_Bicephale_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
equations de Navier-Stokes ou les 2 equations de k et eps sont gerees separement du point de vue informatique.
See also
Modele_turbulence_hyd_base Modele_turbulence_hyd_LES_base
Constructor & Destructor Documentation
Modele_turbulence_hyd_K_Eps_Bicephale()
Modele_turbulence_hyd_K_Eps_Bicephale::Modele_turbulence_hyd_K_Eps_Bicephale ()
~Modele_turbulence_hyd_K_Eps_Bicephale()
Modele_turbulence_hyd_K_Eps_Bicephale::~Modele_turbulence_hyd_K_Eps_Bicephale ()
Member Function Documentation
cree_instance()
Objet_U * Modele_turbulence_hyd_K_Eps_Bicephale::cree_instance () static
taille_memoire()
unsigned Modele_turbulence_hyd_K_Eps_Bicephale::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Modele_turbulence_hyd_K_Eps_Bicephale::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Modele_turbulence_hyd_K_Eps_Bicephale::info () static
get_info()
const Type_info * Modele_turbulence_hyd_K_Eps_Bicephale::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Modele_turbulence_hyd_2_eq_base.
self_cast() [1/2]
Modele_turbulence_hyd_K_Eps_Bicephale & Modele_turbulence_hyd_K_Eps_Bicephale::self_cast (Objet_U & r) static
self_cast() [2/2]
const Modele_turbulence_hyd_K_Eps_Bicephale & Modele_turbulence_hyd_K_Eps_Bicephale::self_cast (const Objet_U & r) static
printOn()
Sortie & Modele_turbulence_hyd_K_Eps_Bicephale::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Modele_turbulence_hyd_2_eq_base.
References Objet_U::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Modele_turbulence_hyd_K_Eps_Bicephale::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Modele_turbulence_hyd_2_eq_base.
References Modele_turbulence_hyd_RANS_Bicephale_base::readOn().
set_param()
void Modele_turbulence_hyd_K_Eps_Bicephale::set_param (Param & param) override virtual
Reimplemented from Modele_turbulence_hyd_2_eq_base.
References Param::ajouter(), Param::ajouter_non_std(), Modele_turbulence_hyd_base::LeCmu_, Param::REQUIRED, and Modele_turbulence_hyd_RANS_Bicephale_base::set_param().
lire_motcle_non_standard()
int Modele_turbulence_hyd_K_Eps_Bicephale::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
< liste stockant tous les noms de frontiere du domaine
Reimplemented from Modele_turbulence_hyd_base.
References Modele_Fonc_Bas_Reynolds_Base::associer_eqn_2(), Modele_Fonc_Bas_Reynolds_Base::discretiser(), eqn_transp_Eps(), eqn_transp_K(), Modele_Fonc_Bas_Reynolds_Base::lire_distance_paroi(), Modele_turbulence_hyd_RANS_Bicephale_base::lire_motcle_non_standard(), mon_modele_fonc_, Objet_U::que_suis_je(), and Modele_Fonc_Bas_Reynolds_Base::typer_lire_Modele_Fonc_Bas_Reynolds().
preparer_calcul()
int Modele_turbulence_hyd_K_Eps_Bicephale::preparer_calcul () override virtual
Prepare le calcul.
Initialise la loi de paroi. Remplit le champ wall_length en cas de post traitemetn de la distance_paroi
Returns
(int) code de retour de Turbulence_paroi::init_lois_paroi()
Reimplemented from Modele_turbulence_hyd_base.
References Eps(), eqn_transp_Eps(), eqn_transp_K(), Modele_turbulence_hyd_base::equation(), Probleme_base::equation(), Equation_base::get_modele(), Turbulence_paroi_scal_base::init_lois_paroi(), K(), Modele_turbulence_hyd_base::la_viscosite_turbulente_, Modele_turbulence_hyd_base::LeCmu_, Modele_turbulence_hyd_RANS_Bicephale_base::nombre_d_equations(), Equation_base::preparer_calcul(), Modele_turbulence_hyd_base::preparer_calcul(), Equation_base::probleme(), TRUST_Ref_Objet_U::valeur(), Champ_Don_base::valeurs(), and Debog::verifier().
verifie_loi_paroi()
void Modele_turbulence_hyd_K_Eps_Bicephale::verifie_loi_paroi () override virtual
Reimplemented from Modele_turbulence_hyd_2_eq_base.
References associe_modele_fonction(), Modele_turbulence_hyd_base::loipar_, and Objet_U::que_suis_je().
initTimeStep()
bool Modele_turbulence_hyd_K_Eps_Bicephale::initTimeStep (double dt) override virtual
Reimplemented from Modele_turbulence_hyd_base.
References eqn_transport_Eps_, eqn_transport_K_, and Equation_base::initTimeStep().
mettre_a_jour()
void Modele_turbulence_hyd_K_Eps_Bicephale::mettre_a_jour (double temps) override virtual
Effectue une mise a jour en temps du modele de turbulence.
Met a jour les equations de transport de K et epsilon, calcule la viscosite turbulente au nouveau temps.
Parameters
(double temps) le temps de mise a jour
Implements Modele_turbulence_hyd_base.
References Statistiques::begin_count(), Equation_base::domaine_Cl_dis(), Statistiques::end_count(), Eps(), eqn_transp_Eps(), eqn_transp_K(), Schema_Temps_base::faire_un_pas_de_temps_eqn_base(), K(), Modele_turbulence_hyd_base::la_viscosite_turbulente_, Modele_turbulence_hyd_base::LeCmu_, Domaine_Cl_dis_base::mettre_a_jour(), Equation_base::mettre_a_jour(), Equation_base::schema_temps(), Champ_Don_base::valeurs(), and Debog::verifier().
K() [1/2]
Champ_Inc_base & Modele_turbulence_hyd_K_Eps_Bicephale::K () inline virtual
Renvoie le champ inconnue K du modele de turbulence Cette inconnue est portee.
par l equation de transport K porte par le modele.
Returns
(Champ_Inc_base&) le champ inconnue (K)
References eqn_transport_K_, and Transport_K_ou_Eps_base::inconnue().
Referenced by mettre_a_jour(), and preparer_calcul().
K() [2/2]
const Champ_Inc_base & Modele_turbulence_hyd_K_Eps_Bicephale::K () const inline virtual
Renvoie le champ inconnue K du modele de turbulence Cette inconnue est portee.
par l equation de transport K porte par le modele. (version const)
Returns
(Champ_Inc_base&) le champ inconnue (K)
References eqn_transport_K_, and Transport_K_ou_Eps_base::inconnue().
Eps() [1/2]
Champ_Inc_base & Modele_turbulence_hyd_K_Eps_Bicephale::Eps () inline virtual
Renvoie le champ inconnue epsilon du modele de turbulence Cette inconnue est portee.
par l equation de transport epsilon porte par le modele.
Returns
(Champ_Inc_base&) le champ inconnue (epsilon)
References eqn_transport_Eps_, and Transport_K_ou_Eps_base::inconnue().
Referenced by mettre_a_jour(), and preparer_calcul().
Eps() [2/2]
const Champ_Inc_base & Modele_turbulence_hyd_K_Eps_Bicephale::Eps () const inline virtual
Renvoie le champ inconnue epsilon du modele de turbulence Cette inconnue est portee.
par l equation de transport epsilon porte par le modele. (version const)
Returns
(Champ_Inc_base&) le champ inconnue (epsilon)
References eqn_transport_Eps_, and Transport_K_ou_Eps_base::inconnue().
eqn_transp_K() [1/2]
Transport_K_ou_Eps_base & Modele_turbulence_hyd_K_Eps_Bicephale::eqn_transp_K () inline override virtual
Renvoie l equation d evolution de K du modele de turbulence.
Returns
(Transport_K_ou_Eps&) equation (K)
Implements Modele_turbulence_hyd_RANS_Bicephale_base.
References eqn_transport_K_.
Referenced by Source_Transport_Eps_VDF_Elem::associer_pb(), Source_Transport_Eps_VEF_Face::associer_pb(), calculer_viscosite_turbulente(), lire_motcle_non_standard(), mettre_a_jour(), and preparer_calcul().
eqn_transp_K() [2/2]
const Transport_K_ou_Eps_base & Modele_turbulence_hyd_K_Eps_Bicephale::eqn_transp_K () const inline override virtual
Renvoie l equation d evolution de K du modele de turbulence (version const)
Returns
(Transport_K_ou_Eps&) equation (K)
Implements Modele_turbulence_hyd_RANS_Bicephale_base.
References eqn_transport_K_.
eqn_transp_Eps() [1/2]
Transport_K_ou_Eps_base & Modele_turbulence_hyd_K_Eps_Bicephale::eqn_transp_Eps () inline override virtual
Renvoie l equation d evolution de epsilon du modele de turbulence.
Returns
(Transport_K_ou_Eps&) equation (epsilon)
Implements Modele_turbulence_hyd_RANS_Bicephale_base.
References eqn_transport_Eps_.
Referenced by Source_Transport_K_VDF_Elem::associer_pb(), Source_Transport_K_VEF_Face::associer_pb(), calculer_viscosite_turbulente(), lire_motcle_non_standard(), mettre_a_jour(), and preparer_calcul().
eqn_transp_Eps() [2/2]
const Transport_K_ou_Eps_base & Modele_turbulence_hyd_K_Eps_Bicephale::eqn_transp_Eps () const inline override virtual
Renvoie l equation d evolution de epsilon du modele de turbulence (version const)
Returns
(Transport_K_ou_Eps&) equation (epsilon)
Implements Modele_turbulence_hyd_RANS_Bicephale_base.
References eqn_transport_Eps_.
equation_k_eps()
const Equation_base & Modele_turbulence_hyd_K_Eps_Bicephale::equation_k_eps (int i) const override virtual
Implements Modele_turbulence_hyd_RANS_Bicephale_base.
References eqn_transport_Eps_, and eqn_transport_K_.
associe_modele_fonction() [1/2]
TRUST_Deriv< Modele_Fonc_Bas_Reynolds_Base > & Modele_turbulence_hyd_K_Eps_Bicephale::associe_modele_fonction () inline
References mon_modele_fonc_.
Referenced by verifie_loi_paroi().
associe_modele_fonction() [2/2]
const TRUST_Deriv< Modele_Fonc_Bas_Reynolds_Base > & Modele_turbulence_hyd_K_Eps_Bicephale::associe_modele_fonction () const inline
References mon_modele_fonc_.
get_champ()
const Champ_base & Modele_turbulence_hyd_K_Eps_Bicephale::get_champ (const Motcle & nom) const override virtual
Reimplemented from Modele_turbulence_hyd_base.
References Nom::getString(), Modele_Fonc_Bas_Reynolds_Base::has_champ(), Modele_turbulence_hyd_RANS_Bicephale_base::has_champ(), mon_modele_fonc_, and Objet_U_ptr::non_nul().
has_champ() [1/2]
bool Modele_turbulence_hyd_K_Eps_Bicephale::has_champ (const Motcle & nom, TRUST_Ref< Champ_base * > & ref_champ) const override virtual
Reimplemented from Modele_turbulence_hyd_base.
References Modele_Fonc_Bas_Reynolds_Base::has_champ(), Modele_turbulence_hyd_RANS_Bicephale_base::has_champ(), mon_modele_fonc_, and Objet_U_ptr::non_nul().
has_champ() [2/2]
bool Modele_turbulence_hyd_K_Eps_Bicephale::has_champ (const Motcle & nom) const override virtual
Reimplemented from Modele_turbulence_hyd_base.
References Modele_Fonc_Bas_Reynolds_Base::has_champ(), Modele_turbulence_hyd_RANS_Bicephale_base::has_champ(), mon_modele_fonc_, and Objet_U_ptr::non_nul().
get_noms_champs_postraitables()
void Modele_turbulence_hyd_K_Eps_Bicephale::get_noms_champs_postraitables (Noms & nom, Option opt = NONE) const override virtual
Reimplemented from Modele_turbulence_hyd_base.
References Modele_Fonc_Bas_Reynolds_Base::get_noms_champs_postraitables(), Modele_turbulence_hyd_RANS_Bicephale_base::get_noms_champs_postraitables(), mon_modele_fonc_, and Objet_U_ptr::non_nul().
calculer_viscosite_turbulente()
Champ_Fonc_base & Modele_turbulence_hyd_K_Eps_Bicephale::calculer_viscosite_turbulente (double temps) virtual
Calcule la viscosite turbulente au temps demande.
Parameters
(double temps) le temps auquel il faut calculer la viscosite
Returns
(Champ_Fonc_base&) la viscosite turbulente au temps demande
Exceptions
erreur de taille de visco_turb_K_eps
References Champ_base::affecter(), Modele_Fonc_Bas_Reynolds_Base::Calcul_Cmu_BiK(), Modele_Fonc_Bas_Reynolds_Base::Calcul_Cmu_Paroi_BiK(), Modele_Fonc_Bas_Reynolds_Base::Calcul_Fmu_BiK(), Modele_Fonc_Bas_Reynolds_Base::Calcul_is_Cmu_constant(), Champ_base::changer_temps(), Turbulence_paroi_base::Cisaillement_paroi(), Modele_turbulence_hyd_RANS_Gen< Modele_turbulence_hyd_K_Eps_Bicephale >::complete_viscosity_field(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Domaine_dis_base::domaine(), Equation_base::domaine_Cl_dis(), Equation_base::domaine_dis(), Modele_turbulence_hyd_2_eq_base::EPS_MIN_, eqn_transp_Eps(), eqn_transp_K(), Process::exit(), fill_turbulent_viscosity_tab(), Transport_K_ou_Eps_base::inconnue(), Modele_turbulence_hyd_base::la_viscosite_turbulente_, Modele_turbulence_hyd_base::loi_paroi(), Transport_2eq_base::modele_turbulence(), Modele_turbulence_hyd_base::mon_equation_, mon_modele_fonc_, Process::mp_max(), Domaine_32_64< _SIZE_ >::nb_elem(), Objet_U_ptr::non_nul(), Objet_U::que_suis_je(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTVect< _TYPE_, _SIZE_ >::size(), Champ_Don_base::valeurs(), Champ_Proto::valeurs(), and Debog::verifier().
controler()
void Modele_turbulence_hyd_K_Eps_Bicephale::controler () inline
References Transport_K_ou_Eps_base::controler_variable(), eqn_transport_Eps_, and eqn_transport_K_.
fill_turbulent_viscosity_tab()
void Modele_turbulence_hyd_K_Eps_Bicephale::fill_turbulent_viscosity_tab (const int n, const DoubleTab & tab_K, const DoubleTab & tab_Eps, const DoubleTab & Cmu, const DoubleTab & Fmu, const DoubleTab & D, DoubleTab & turbulent_viscosity) protected
References Modele_Fonc_Bas_Reynolds_Base::Calcul_is_Cmu_constant(), Modele_turbulence_hyd_2_eq_base::EPS_MIN_, Modele_turbulence_hyd_base::LeCmu_, mon_modele_fonc_, and Objet_U_ptr::non_nul().
Referenced by calculer_viscosite_turbulente().
Member Data Documentation
info_obj
const Type_info Modele_turbulence_hyd_K_Eps_Bicephale::info_obj static
mon_modele_fonc_
TRUST_Deriv< Modele_Fonc_Bas_Reynolds_Base > Modele_turbulence_hyd_K_Eps_Bicephale::mon_modele_fonc_ protected
Referenced by associe_modele_fonction(), calculer_viscosite_turbulente(), fill_turbulent_viscosity_tab(), get_champ(), get_noms_champs_postraitables(), has_champ(), and lire_motcle_non_standard().
eqn_transport_K_
Transport_K_ou_Eps Modele_turbulence_hyd_K_Eps_Bicephale::eqn_transport_K_ protected
Referenced by controler(), eqn_transp_K(), equation_k_eps(), initTimeStep(), and K().
eqn_transport_Eps_
Transport_K_ou_Eps Modele_turbulence_hyd_K_Eps_Bicephale::eqn_transport_Eps_ protected
Referenced by controler(), Eps(), eqn_transp_Eps(), equation_k_eps(), and initTimeStep().