TrioCFD: Op_Evanescence_Homogene_VDF_Face Class Reference
Op_Evanescence_Homogene_VDF_Face Class Reference
#include <Op_Evanescence_Homogene_VDF_Face.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Operateur_base
void associer_eqn (const Equation_base &)
virtual double calculer_dt_stab () const
virtual void completer ()
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual void mettre_a_jour (double temps)
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Op_Evanescence_Homogene_VDF_Face()
Op_Evanescence_Homogene_VDF_Face::Op_Evanescence_Homogene_VDF_Face ()
~Op_Evanescence_Homogene_VDF_Face()
Op_Evanescence_Homogene_VDF_Face::~Op_Evanescence_Homogene_VDF_Face ()
Member Function Documentation
cree_instance()
Objet_U * Op_Evanescence_Homogene_VDF_Face::cree_instance () static
taille_memoire()
unsigned Op_Evanescence_Homogene_VDF_Face::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Op_Evanescence_Homogene_VDF_Face::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Op_Evanescence_Homogene_VDF_Face::info () static
get_info()
const Type_info * Op_Evanescence_Homogene_VDF_Face::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Op_Evanescence_Homogene_Face_base.
self_cast() [1/2]
Op_Evanescence_Homogene_VDF_Face & Op_Evanescence_Homogene_VDF_Face::self_cast (Objet_U & r) static
self_cast() [2/2]
const Op_Evanescence_Homogene_VDF_Face & Op_Evanescence_Homogene_VDF_Face::self_cast (const Objet_U & r) static
printOn()
Sortie & Op_Evanescence_Homogene_VDF_Face::printOn (Sortie & os) const override protected virtual
DOES NOTHING - to override in derived classes.
Imprime l'operateur sur un flot de sortie.
Parameters
(Sortie& os) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Op_Evanescence_Homogene_Face_base.
readOn()
Entree & Op_Evanescence_Homogene_VDF_Face::readOn (Entree & is) override protected virtual
DOES NOTHING - to override in derived classes.
Lit un operateur sur un flot d'entree.
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Op_Evanescence_Homogene_Face_base.
References Op_Evanescence_Homogene_Face_base::readOn().
calc_grad_alpha_faces()
void Op_Evanescence_Homogene_VDF_Face::calc_grad_alpha_faces (DoubleTab & gradAlphaFaces) const override protected virtual
Reimplemented from Op_Evanescence_Homogene_Face_base.
References Operateur_Grad::calculer(), Objet_U::dimension, MorEqn::equation(), Pb_Multiphase::equation_masse(), Equation_base::inconnue(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Objet_U_ptr::non_nul(), and Champ_Inc_base::passe().
preparer_calcul()
void Op_Evanescence_Homogene_VDF_Face::preparer_calcul () override protected virtual
Reimplemented from Operateur_base.
References MorEqn::associer_eqn(), Operateur_base::associer_eqn(), Equation_base::domaine_Cl_dis(), Equation_base::domaine_dis(), MorEqn::equation(), Pb_Multiphase::equation_masse(), Probleme_base::get_correlation(), Probleme_base::has_correlation(), Equation_base::inconnue(), Operateur_Grad::l_op_base(), Vitesse_relative_base::needs_grad_alpha(), Operateur_base::preparer_calcul(), Objet_U::que_suis_je(), and Operateur_Grad::typer().
Member Data Documentation
info_obj
const Type_info Op_Evanescence_Homogene_VDF_Face::info_obj static