TrioCFD: KerasLayerLSTM Class Reference
KerasLayerLSTM Class Reference
#include <keras_model.h>
Constructor & Destructor Documentation
KerasLayerLSTM()
KerasLayerLSTM::KerasLayerLSTM () inline
~KerasLayerLSTM()
KerasLayerLSTM::~KerasLayerLSTM () inline override
Member Function Documentation
LoadLayer()
bool KerasLayerLSTM::LoadLayer (std::ifstream * file) override virtual
Implements KerasLayer.
References Tensor::data_, KerasLayerActivation::LoadLayer(), and Tensor::Resize().
Apply()
bool KerasLayerLSTM::Apply (Tensor * in, Tensor * out) override virtual
Implements KerasLayer.
References Tensor::data_, Tensor::dims_, Tensor::Fill(), and Tensor::Select().