TrioCFD: Tenseur_Reynolds_Externe_VDF_Face Class Reference
Tenseur_Reynolds_Externe_VDF_Face Class Reference
#include <Tenseur_Reynolds_Externe_VDF_Face.h>
Public Member Functions
void completer () override
const Type_info * get_info () const override
void mettre_a_jour (double) override
Public Member Functions inherited from Source_base
virtual int a_pour_Champ_Fonc (const Motcle &mot, TRUST_Ref< Champ_base * > &ch_ref) const
virtual void associer_champ_rho (const Champ_base &champ_rho)
virtual void completer ()
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
virtual void resetTime (double t)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Terme_Source_Qdm
const Champ_Don_base & source () const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
See also
Source_base
Constructor & Destructor Documentation
Tenseur_Reynolds_Externe_VDF_Face()
Tenseur_Reynolds_Externe_VDF_Face::Tenseur_Reynolds_Externe_VDF_Face ()
~Tenseur_Reynolds_Externe_VDF_Face()
Tenseur_Reynolds_Externe_VDF_Face::~Tenseur_Reynolds_Externe_VDF_Face () override
References tbnn.
Member Function Documentation
cree_instance()
Objet_U * Tenseur_Reynolds_Externe_VDF_Face::cree_instance () static
taille_memoire()
unsigned Tenseur_Reynolds_Externe_VDF_Face::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Tenseur_Reynolds_Externe_VDF_Face::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Tenseur_Reynolds_Externe_VDF_Face::info () static
get_info()
const Type_info * Tenseur_Reynolds_Externe_VDF_Face::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Source_base.
self_cast() [1/2]
Tenseur_Reynolds_Externe_VDF_Face & Tenseur_Reynolds_Externe_VDF_Face::self_cast (Objet_U & r) static
self_cast() [2/2]
const Tenseur_Reynolds_Externe_VDF_Face & Tenseur_Reynolds_Externe_VDF_Face::self_cast (const Objet_U & r) static
printOn()
Sortie & Tenseur_Reynolds_Externe_VDF_Face::printOn (Sortie & os) const override protected virtual
DOES NOTHING - to override in derived classes.
Imprime la source sur un flot de sortie.
Parameters
(Sortie& os) le flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Source_base.
References Objet_U::que_suis_je().
readOn()
Entree & Tenseur_Reynolds_Externe_VDF_Face::readOn (Entree & is) override protected virtual
DOES NOTHING - to override in derived classes.
Lecture d'un terme source sur un flot d'entree.
Parameters
(Entree& is) le flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Source_base.
References Process::exit(), nn_casename, readNN(), and Motcles::search().
associer_pb()
void Tenseur_Reynolds_Externe_VDF_Face::associer_pb (const Probleme_base & pb) override virtual
Implements Source_base.
References eqn_NS_, eqn_transport_K_Eps_, Probleme_base::equation(), Process::exit(), modele_K_Eps_, probleme_, and Objet_U::que_suis_je().
has_interface_blocs()
int Tenseur_Reynolds_Externe_VDF_Face::has_interface_blocs () const inline override virtual
Reimplemented from Source_base.
ajouter_blocs()
void Tenseur_Reynolds_Externe_VDF_Face::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl) const override virtual
Reimplemented from Source_base.
References MorEqn::equation(), Domaine_VF::face_voisins(), Terme_Source_Qdm::la_source, le_dom_Cl_VDF, le_dom_VDF, Domaine_Cl_dis_base::les_conditions_limites(), Equation_base::milieu(), Domaine_VF::nb_faces(), Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), Domaine_VDF::orientation(), Milieu_base::porosite_face(), Domaine_VF::premiere_face_int(), TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), and Domaine_VF::volumes_entrelaces().
dimensionner_blocs()
void Tenseur_Reynolds_Externe_VDF_Face::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl) const inline override virtual
Reimplemented from Source_base.
calculer()
DoubleTab & Tenseur_Reynolds_Externe_VDF_Face::calculer (DoubleTab & resu) const override virtual
Reimplemented from Source_base.
References Source_base::ajouter().
mettre_a_jour()
void Tenseur_Reynolds_Externe_VDF_Face::mettre_a_jour (double temps) override virtual
DOES NOTHING - to override in derived classes.
Mise a jour en temps du terme source.
Parameters
(double) le pas de temps de mise a jour
Reimplemented from Source_base.
References Calcul_RSLambda(), Calcul_Tenseur_Reynolds(), Objet_U::dimension, TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Terme_Source_Qdm::la_source, le_dom_VDF, TRUSTVect< _TYPE_, _SIZE_ >::line_size(), and Champ_Don_base::valeurs().
completer()
void Tenseur_Reynolds_Externe_VDF_Face::completer () override virtual
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees: Source_base::associer_domaines(const Domaine_dis_base& ,const Domaine_Cl_dis_base&) Source_base::associer_pb(const Probleme_base&)
Reimplemented from Source_base.
References Source_base::completer(), and Terme_Source_Qdm::la_source.
readNN()
void Tenseur_Reynolds_Externe_VDF_Face::readNN () protected
References nn_casename, and tbnn.
Referenced by readOn().
associer_domaines()
void Tenseur_Reynolds_Externe_VDF_Face::associer_domaines (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis) override protected virtual
Implements Source_base.
References le_dom_Cl_VDF, le_dom_VDF, and nelem_.
Calcul_RSLambda()
void Tenseur_Reynolds_Externe_VDF_Face::Calcul_RSLambda () protected
References Objet_U::dimension, eqn_NS_, eqn_transport_K_Eps_, lambda_1_etoile_, lambda_2_etoile_, lambda_3_etoile_, lambda_4_etoile_, lambda_5_etoile_, le_dom_Cl_VDF, le_dom_VDF, TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Domaine_dis_base::nb_elem_tot(), nelem_, T10_etoile_, T1_etoile_, T2_etoile_, T3_etoile_, T4_etoile_, T5_etoile_, T6_etoile_, T7_etoile_, T8_etoile_, T9_etoile_, TRUST_Ref< _CLASSE_ >::valeur(), and Champ_Inc_base::valeurs().
Referenced by mettre_a_jour().
Calcul_bij_TBNN()
DoubleTab & Tenseur_Reynolds_Externe_VDF_Face::Calcul_bij_TBNN (DoubleTab & resu) const protected
Referenced by Calcul_Tenseur_Reynolds().
Calcul_Tenseur_Reynolds()
DoubleTab & Tenseur_Reynolds_Externe_VDF_Face::Calcul_Tenseur_Reynolds (DoubleTab & resu) const protected
References Calcul_bij_TBNN(), Objet_U::dimension, eqn_transport_K_Eps_, and nelem_.
Referenced by mettre_a_jour().
Member Data Documentation
info_obj
const Type_info Tenseur_Reynolds_Externe_VDF_Face::info_obj static
eqn_NS_
TRUST_Ref< Navier_Stokes_Turbulent *> Tenseur_Reynolds_Externe_VDF_Face::eqn_NS_ protected
Referenced by associer_pb(), and Calcul_RSLambda().
modele_K_Eps_
TRUST_Ref< Modele_turbulence_hyd_K_Eps *> Tenseur_Reynolds_Externe_VDF_Face::modele_K_Eps_ protected
Referenced by associer_pb().
probleme_
TRUST_Ref< Probleme_base *> Tenseur_Reynolds_Externe_VDF_Face::probleme_ protected
Referenced by associer_pb().
eqn_transport_K_Eps_
TRUST_Ref< Transport_K_Eps *> Tenseur_Reynolds_Externe_VDF_Face::eqn_transport_K_Eps_ protected
Referenced by associer_pb(), Calcul_RSLambda(), and Calcul_Tenseur_Reynolds().
le_dom_VDF
TRUST_Ref< Domaine_VDF *> Tenseur_Reynolds_Externe_VDF_Face::le_dom_VDF protected
Referenced by ajouter_blocs(), associer_domaines(), Calcul_RSLambda(), and mettre_a_jour().
le_dom_Cl_VDF
TRUST_Ref< Domaine_Cl_VDF *> Tenseur_Reynolds_Externe_VDF_Face::le_dom_Cl_VDF protected
Referenced by ajouter_blocs(), associer_domaines(), and Calcul_RSLambda().
lambda_1_etoile_
DoubleTab Tenseur_Reynolds_Externe_VDF_Face::lambda_1_etoile_ protected
Referenced by Calcul_RSLambda().
lambda_2_etoile_
DoubleTab Tenseur_Reynolds_Externe_VDF_Face::lambda_2_etoile_ protected
Referenced by Calcul_RSLambda().
lambda_3_etoile_
DoubleTab Tenseur_Reynolds_Externe_VDF_Face::lambda_3_etoile_ protected
Referenced by Calcul_RSLambda().
lambda_4_etoile_
DoubleTab Tenseur_Reynolds_Externe_VDF_Face::lambda_4_etoile_ protected
Referenced by Calcul_RSLambda().
lambda_5_etoile_
DoubleTab Tenseur_Reynolds_Externe_VDF_Face::lambda_5_etoile_ protected
Referenced by Calcul_RSLambda().
T1_etoile_
DoubleTab Tenseur_Reynolds_Externe_VDF_Face::T1_etoile_ protected
Referenced by Calcul_RSLambda().
T2_etoile_
DoubleTab Tenseur_Reynolds_Externe_VDF_Face::T2_etoile_ protected
Referenced by Calcul_RSLambda().
T3_etoile_
DoubleTab Tenseur_Reynolds_Externe_VDF_Face::T3_etoile_ protected
Referenced by Calcul_RSLambda().
T4_etoile_
DoubleTab Tenseur_Reynolds_Externe_VDF_Face::T4_etoile_ protected
Referenced by Calcul_RSLambda().
T5_etoile_
DoubleTab Tenseur_Reynolds_Externe_VDF_Face::T5_etoile_ protected
Referenced by Calcul_RSLambda().
T6_etoile_
DoubleTab Tenseur_Reynolds_Externe_VDF_Face::T6_etoile_ protected
Referenced by Calcul_RSLambda().
T7_etoile_
DoubleTab Tenseur_Reynolds_Externe_VDF_Face::T7_etoile_ protected
Referenced by Calcul_RSLambda().
T8_etoile_
DoubleTab Tenseur_Reynolds_Externe_VDF_Face::T8_etoile_ protected
Referenced by Calcul_RSLambda().
T9_etoile_
DoubleTab Tenseur_Reynolds_Externe_VDF_Face::T9_etoile_ protected
Referenced by Calcul_RSLambda().
T10_etoile_
DoubleTab Tenseur_Reynolds_Externe_VDF_Face::T10_etoile_ protected
Referenced by Calcul_RSLambda().
nelem_
int Tenseur_Reynolds_Externe_VDF_Face::nelem_ protected
Referenced by associer_domaines(), Calcul_RSLambda(), and Calcul_Tenseur_Reynolds().
nn_casename
Nom Tenseur_Reynolds_Externe_VDF_Face::nn_casename protected
Referenced by readNN(), and readOn().
tbnn
TBNN* Tenseur_Reynolds_Externe_VDF_Face::tbnn protected
Referenced by readNN(), and ~Tenseur_Reynolds_Externe_VDF_Face().