TrioCFD: Raccord_distant_32_64< _SIZE_ > Class Template Reference
Raccord_distant_32_64< _SIZE_ > Class Template Reference
#include <Raccord_base.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Frontiere_32_64< _SIZE_ >
void add (const Frontiere_32_64 &)
void ajouter_faces (const IntTab_t &)
void associer_domaine (const Domaine_t &)
Domaine_t & domaine ()
const Domaine_t & domaine () const
const Type_info * get_info () const override
const Nom & le_nom () const override
IntTab_t & les_sommets_des_faces ()
const IntTab_t & les_sommets_des_faces () const
void nommer (const Nom &) override
void renum (const IntVect_t &)
void typer_faces (const Motcle &)
void typer_faces (const Type_Face &)
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
template<typename _SIZE_>
class Raccord_distant_32_64< _SIZE_ >
See also
Raccord_base Raccord Raccord_local
Constructor & Destructor Documentation
Raccord_distant_32_64()
template<typename _T_ > Raccord_distant_32_64< _T_ >::Raccord_distant_32_64
~Raccord_distant_32_64()
template<typename _T_ > Raccord_distant_32_64< _T_ >::~Raccord_distant_32_64 override
Member Function Documentation
info()
template<typename _T_ > const Type_info * Raccord_distant_32_64< _T_ >::info static
get_info()
template<typename _T_ > const Type_info * Raccord_distant_32_64< _T_ >::get_info override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Raccord_base_32_64< _SIZE_ >.
Reimplemented in Raccord_distant_homogene_32_64< _SIZE_ >.
self_cast() [1/2]
template<typename _T_ > Raccord_distant_32_64< _T_ > & Raccord_distant_32_64< _T_ >::self_cast (Objet_U & r) static
self_cast() [2/2]
template<typename _T_ > const Raccord_distant_32_64< _T_ > & Raccord_distant_32_64< _T_ >::self_cast (const Objet_U & r) static
printOn()
template<typename _SIZE_ > Sortie & Raccord_distant_32_64< _SIZE_ >::printOn (Sortie & os) const override protected virtual
Ecrit la frontiere sur un flot de sortie.
On ecrit: le nom de la frontiere les faces
Parameters
(Sortie& os) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Raccord_base_32_64< _SIZE_ >.
Reimplemented in Raccord_distant_homogene_32_64< _SIZE_ >.
References Raccord_base_32_64< _SIZE_ >::printOn().
Referenced by Raccord_distant_homogene_32_64< _SIZE_ >::printOn().
readOn()
template<typename _SIZE_ > Entree & Raccord_distant_32_64< _SIZE_ >::readOn (Entree & is) override protected virtual
Lit les specification d'une frontiere a partir d'un flot d'entree.
On lit: le nom les faces
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Raccord_base_32_64< _SIZE_ >.
Reimplemented in Raccord_distant_homogene_32_64< _SIZE_ >.
References Raccord_base_32_64< _SIZE_ >::readOn().
Referenced by Raccord_distant_homogene_32_64< _SIZE_ >::readOn().
info_obj() [1/2]
const Type_info Raccord_distant_32_64< int >::info_obj ("Raccord_distant" , 1 , Raccord_distant_32_64bases< int >)
info_obj() [2/2]
const Type_info Raccord_distant_32_64< trustIdType >::info_obj ("Raccord_distant" "_64" , 1 , Raccord_distant_32_64bases< trustIdType >)
Member Data Documentation
info_obj
template<typename _SIZE_ > const Type_info Raccord_distant_32_64< _SIZE_ >::info_obj static