TrioCFD: Terme_Source_Canal_RANS_LES_VDF_Face Class Reference
Terme_Source_Canal_RANS_LES_VDF_Face Class Reference
#include <Terme_Source_Canal_RANS_LES_VDF_Face.h>
Public Member Functions
const Type_info * get_info () const override
void mettre_a_jour (double) override
Public Member Functions inherited from Source_base
virtual int a_pour_Champ_Fonc (const Motcle &mot, TRUST_Ref< Champ_base * > &ch_ref) const
virtual void associer_champ_rho (const Champ_base &champ_rho)
virtual void completer ()
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
virtual void resetTime (double t)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
a un calcul RANS preliminaire et applique au calcul LES en cours
Constructor & Destructor Documentation
Terme_Source_Canal_RANS_LES_VDF_Face()
Terme_Source_Canal_RANS_LES_VDF_Face::Terme_Source_Canal_RANS_LES_VDF_Face ()
~Terme_Source_Canal_RANS_LES_VDF_Face()
Terme_Source_Canal_RANS_LES_VDF_Face::~Terme_Source_Canal_RANS_LES_VDF_Face () override
References TRUSTVect< _TYPE_, _SIZE_ >::size().
Member Function Documentation
cree_instance()
Objet_U * Terme_Source_Canal_RANS_LES_VDF_Face::cree_instance () static
taille_memoire()
unsigned Terme_Source_Canal_RANS_LES_VDF_Face::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Terme_Source_Canal_RANS_LES_VDF_Face::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Terme_Source_Canal_RANS_LES_VDF_Face::info () static
get_info()
const Type_info * Terme_Source_Canal_RANS_LES_VDF_Face::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Source_base.
self_cast() [1/2]
Terme_Source_Canal_RANS_LES_VDF_Face & Terme_Source_Canal_RANS_LES_VDF_Face::self_cast (Objet_U & r) static
self_cast() [2/2]
const Terme_Source_Canal_RANS_LES_VDF_Face & Terme_Source_Canal_RANS_LES_VDF_Face::self_cast (const Objet_U & r) static
printOn()
Sortie & Terme_Source_Canal_RANS_LES_VDF_Face::printOn (Sortie & os) const override protected virtual
DOES NOTHING - to override in derived classes.
Imprime la source sur un flot de sortie.
Parameters
(Sortie& os) le flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Source_base.
References Objet_U::que_suis_je().
readOn()
Entree & Terme_Source_Canal_RANS_LES_VDF_Face::readOn (Entree & is) override protected virtual
DOES NOTHING - to override in derived classes.
Lecture d'un terme source sur un flot d'entree.
Parameters
(Entree& is) le flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Source_base.
References Process::exit(), init(), and Motcles::search().
associer_pb()
void Terme_Source_Canal_RANS_LES_VDF_Face::associer_pb (const Probleme_base & pb) override virtual
Implements Source_base.
calculer()
DoubleTab & Terme_Source_Canal_RANS_LES_VDF_Face::calculer (DoubleTab & resu) const override virtual
Reimplemented from Source_base.
References Source_base::ajouter().
init_calcul_moyenne_spat()
void Terme_Source_Canal_RANS_LES_VDF_Face::init_calcul_moyenne_spat ()
References Domaine_dis_base::domaine(), Process::exit(), MorEqn::mon_equation, Domaine_32_64< _SIZE_ >::nb_elem(), Domaine_VF::nb_faces(), Domaine_VDF::nb_faces_Y(), Domaine_VDF::orientation(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), and Domaine_VF::xv().
Referenced by init().
init()
void Terme_Source_Canal_RANS_LES_VDF_Face::init ()
References init_calcul_moyenne_spat(), MorEqn::mon_equation, Domaine_dis_base::nb_elem(), Domaine_VF::nb_faces(), Domaine_VDF::nb_faces_Y(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), and TRUSTVect< _TYPE_, _SIZE_ >::resize().
Referenced by readOn().
norme_vit()
DoubleTab Terme_Source_Canal_RANS_LES_VDF_Face::norme_vit () const
References Domaine_VF::elem_faces(), Domaine_VF::face_voisins(), le_dom_VDF, Domaine_dis_base::nb_elem(), Domaine_VF::nb_faces(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by ajouter_blocs(), and mettre_a_jour().
mettre_a_jour()
void Terme_Source_Canal_RANS_LES_VDF_Face::mettre_a_jour (double temps) override virtual
DOES NOTHING - to override in derived classes.
Mise a jour en temps du terme source.
Parameters
(double) le pas de temps de mise a jour
Reimplemented from Source_base.
References calculer_integrale_temporelle(), ecriture_moy_spat(), ecriture_moy_temp(), MorEqn::equation(), le_dom_VDF, Equation_base::milieu(), MorEqn::mon_equation, moy_spat(), Domaine_dis_base::nb_elem(), Domaine_VF::nb_faces(), Domaine_VDF::nb_faces_X(), Domaine_VDF::nb_faces_Y(), Domaine_VDF::nb_faces_Z(), norme_vit(), Interprete::objet(), Domaine_VDF::orientation(), Milieu_base::porosite_face(), TRUST_Ref< _CLASSE_ >::valeur(), Domaine_VF::volumes_entrelaces(), and Domaine_VF::xv().
moy_spat()
void Terme_Source_Canal_RANS_LES_VDF_Face::moy_spat (DoubleVect & champ, DoubleVect & champ_spat_x, DoubleVect & champ_spat_y, DoubleVect & champ_spat_z, DoubleVect & champ_spat_x_2, DoubleVect & champ_spat_y_2, DoubleVect & champ_spat_z_2)
References le_dom_VDF, Domaine_VF::nb_faces(), Domaine_VDF::orientation(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by mettre_a_jour().
calculer_integrale_temporelle()
void Terme_Source_Canal_RANS_LES_VDF_Face::calculer_integrale_temporelle (DoubleVect & moy_temp, const DoubleVect & moy)
References TRUSTVect< _TYPE_, _SIZE_ >::ajoute(), Process::je_suis_maitre(), and MorEqn::mon_equation.
Referenced by mettre_a_jour().
ecriture_moy_spat()
void Terme_Source_Canal_RANS_LES_VDF_Face::ecriture_moy_spat (DoubleVect & champ_spat_x, DoubleVect & champ_spat_y, DoubleVect & champ_spat_z, DoubleVect & champ_spat_x_2, DoubleVect & champ_spat_y_2, DoubleVect & champ_spat_z_2)
References MorEqn::mon_equation.
Referenced by mettre_a_jour().
ecriture_moy_temp()
void Terme_Source_Canal_RANS_LES_VDF_Face::ecriture_moy_temp (DoubleVect & champ_temp_x, DoubleVect & champ_temp_y, DoubleVect & champ_temp_z, DoubleVect & champ_temp_x_2, DoubleVect & champ_temp_y_2, DoubleVect & champ_temp_z_2, const double dt)
References MorEqn::mon_equation.
Referenced by mettre_a_jour().
dimensionner_blocs()
void Terme_Source_Canal_RANS_LES_VDF_Face::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl) const inline override virtual
Reimplemented from Source_base.
ajouter_blocs()
void Terme_Source_Canal_RANS_LES_VDF_Face::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl) const override virtual
Reimplemented from Source_base.
References MorEqn::equation(), le_dom_VDF, Equation_base::milieu(), MorEqn::mon_equation, Domaine_VF::nb_faces(), norme_vit(), Milieu_base::porosite_face(), TRUST_Ref< _CLASSE_ >::valeur(), and Domaine_VF::volumes_entrelaces().
has_interface_blocs()
int Terme_Source_Canal_RANS_LES_VDF_Face::has_interface_blocs () const inline override virtual
Reimplemented from Source_base.
associer_domaines()
void Terme_Source_Canal_RANS_LES_VDF_Face::associer_domaines (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis) override protected virtual
Implements Source_base.
References le_dom_Cl_VDF, and le_dom_VDF.
Member Data Documentation
info_obj
const Type_info Terme_Source_Canal_RANS_LES_VDF_Face::info_obj static
le_dom_VDF
TRUST_Ref< Domaine_VDF *> Terme_Source_Canal_RANS_LES_VDF_Face::le_dom_VDF protected
Referenced by ajouter_blocs(), associer_domaines(), mettre_a_jour(), moy_spat(), and norme_vit().
le_dom_Cl_VDF
TRUST_Ref< Domaine_Cl_VDF *> Terme_Source_Canal_RANS_LES_VDF_Face::le_dom_Cl_VDF protected
Referenced by associer_domaines().