TrioCFD: Modele_turbulence_hyd_RANS_Bicephale_base Class Reference
Modele_turbulence_hyd_RANS_Bicephale_base Class Reference abstract
#include <Modele_turbulence_hyd_RANS_Bicephale_base.h>
Public Member Functions
void associer_seconde_eqn (const Equation_base &)
const Type_info * get_info () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
int reprendre (Entree &is) override
int sauvegarder (Sortie &os) const override
Equation_base & seconde_equation ()
const Type_info * get_info () const override
Public Member Functions inherited from Modele_turbulence_hyd_base
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Type_info * get_info () const override
virtual void imprimer (Sortie &) const
void lire_distance_paroi ()
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual int preparer_calcul ()
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
See also
Modele_turbulence_hyd_2_eq_base
Constructor & Destructor Documentation
~Modele_turbulence_hyd_RANS_Bicephale_base()
Modele_turbulence_hyd_RANS_Bicephale_base::~Modele_turbulence_hyd_RANS_Bicephale_base () override
Modele_turbulence_hyd_RANS_Bicephale_base()
Modele_turbulence_hyd_RANS_Bicephale_base::Modele_turbulence_hyd_RANS_Bicephale_base () inline
References Modele_turbulence_hyd_2_eq_base::EPS_MIN_, and Modele_turbulence_hyd_2_eq_base::K_MIN_.
Member Function Documentation
info()
const Type_info * Modele_turbulence_hyd_RANS_Bicephale_base::info () static
get_info()
const Type_info * Modele_turbulence_hyd_RANS_Bicephale_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Modele_turbulence_hyd_2_eq_base.
self_cast() [1/2]
Modele_turbulence_hyd_RANS_Bicephale_base & Modele_turbulence_hyd_RANS_Bicephale_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Modele_turbulence_hyd_RANS_Bicephale_base & Modele_turbulence_hyd_RANS_Bicephale_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Modele_turbulence_hyd_RANS_Bicephale_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Modele_turbulence_hyd_2_eq_base.
References Modele_turbulence_hyd_base::printOn().
readOn()
Entree & Modele_turbulence_hyd_RANS_Bicephale_base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Modele_turbulence_hyd_2_eq_base.
References Modele_turbulence_hyd_base::readOn().
Referenced by Modele_turbulence_hyd_K_Eps_Bicephale::readOn(), and Modele_turbulence_hyd_K_Eps_Realisable_Bicephale::readOn().
set_param()
void Modele_turbulence_hyd_RANS_Bicephale_base::set_param (Param & param) override virtual
Reimplemented from Modele_turbulence_hyd_2_eq_base.
References Param::ajouter(), Modele_turbulence_hyd_2_eq_base::EPS_MAX_, Modele_turbulence_hyd_2_eq_base::EPS_MIN_, Modele_turbulence_hyd_2_eq_base::Prandtl_Eps_, Modele_turbulence_hyd_2_eq_base::Prandtl_K_, and Modele_turbulence_hyd_2_eq_base::set_param().
Referenced by Modele_turbulence_hyd_K_Eps_Bicephale::set_param(), and Modele_turbulence_hyd_K_Eps_Realisable_Bicephale::set_param().
completer()
void Modele_turbulence_hyd_RANS_Bicephale_base::completer () override virtual
Reimplemented from Modele_turbulence_hyd_base.
References Equation_base::completer(), eqn_transp_Eps(), eqn_transp_K(), and Modele_turbulence_hyd_2_eq_base::verifie_loi_paroi().
sauvegarder()
int Modele_turbulence_hyd_RANS_Bicephale_base::sauvegarder (Sortie & os) const override virtual
Sauvegarde le modele de turbulence sur un flot de sortie.
(en vue d'une reprise) Sauvegarde le type de l'objet et les equations de transport K-epsilon associees.
Parameters
(Sortie& os) un flot de sortie
Returns
(int) code de retour propage de: Transport_K_ou_Eps::sauvegarder(Sortie&)
Reimplemented from Modele_turbulence_hyd_base.
References eqn_transp_Eps(), eqn_transp_K(), Modele_turbulence_hyd_base::sauvegarder(), and sauvegarder().
Referenced by sauvegarder().
reprendre()
int Modele_turbulence_hyd_RANS_Bicephale_base::reprendre (Entree & is) override virtual
Reprise du modele a partir d'un flot d'entree.
Si l'equation portee par l'objet est non nulle on effectue une reprise "bidon".
Parameters
(Entree& is) un flot d'entree
Returns
(int) code de retour propage de: Transport_K_ou_Eps::reprendre(Entree& is) ou 1 si la reprise est bidon.
Reimplemented from Modele_turbulence_hyd_base.
References eqn_transp_Eps(), eqn_transp_K(), Modele_turbulence_hyd_base::mon_equation_, TRUST_Ref< _CLASSE_ >::non_nul(), Modele_turbulence_hyd_base::reprendre(), reprendre(), and Modele_turbulence_hyd_2_eq_base::reprendre_generique().
Referenced by reprendre().
lire_motcle_non_standard()
int Modele_turbulence_hyd_RANS_Bicephale_base::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
< liste stockant tous les noms de frontiere du domaine
Reimplemented from Modele_turbulence_hyd_base.
References Transport_2eq_base::associer_modele_turbulence(), eqn_transp_Eps(), eqn_transp_K(), Modele_turbulence_hyd_base::lire_motcle_non_standard(), Transport_K_ou_Eps_base::transporte_Eps(), and Transport_K_ou_Eps_base::transporte_K().
Referenced by Modele_turbulence_hyd_K_Eps_Bicephale::lire_motcle_non_standard(), and Modele_turbulence_hyd_K_Eps_Realisable_Bicephale::lire_motcle_non_standard().
data_a_sauvegarder()
std::vector< YAML_data > Modele_turbulence_hyd_RANS_Bicephale_base::data_a_sauvegarder () const override virtual
for PDI IO: retrieve name, type and dimensions of the fields to save/restore
Reimplemented from Modele_turbulence_hyd_base.
References Equation_base::data_a_sauvegarder(), Modele_turbulence_hyd_base::data_a_sauvegarder(), and eqn_transp_K().
get_champ()
const Champ_base & Modele_turbulence_hyd_RANS_Bicephale_base::get_champ (const Motcle & nom) const override virtual
Reimplemented from Modele_turbulence_hyd_base.
References equation_k_eps(), Nom::getString(), Equation_base::has_champ(), Modele_turbulence_hyd_base::has_champ(), and nombre_d_equations().
has_champ() [1/2]
bool Modele_turbulence_hyd_RANS_Bicephale_base::has_champ (const Motcle & nom, TRUST_Ref< Champ_base * > & ref_champ) const override virtual
Reimplemented from Modele_turbulence_hyd_base.
References equation_k_eps(), Equation_base::has_champ(), Modele_turbulence_hyd_base::has_champ(), and nombre_d_equations().
Referenced by Modele_turbulence_hyd_K_Eps_Bicephale::get_champ(), Modele_turbulence_hyd_K_Eps_Realisable_Bicephale::get_champ(), Modele_turbulence_hyd_K_Eps_Bicephale::has_champ(), and Modele_turbulence_hyd_K_Eps_Realisable_Bicephale::has_champ().
has_champ() [2/2]
bool Modele_turbulence_hyd_RANS_Bicephale_base::has_champ (const Motcle & nom) const override virtual
Reimplemented from Modele_turbulence_hyd_base.
References equation_k_eps(), Equation_base::has_champ(), Modele_turbulence_hyd_base::has_champ(), and nombre_d_equations().
get_noms_champs_postraitables()
void Modele_turbulence_hyd_RANS_Bicephale_base::get_noms_champs_postraitables (Noms & nom, Option opt = NONE) const override virtual
Reimplemented from Modele_turbulence_hyd_base.
References equation_k_eps(), Equation_base::get_noms_champs_postraitables(), Modele_turbulence_hyd_base::get_noms_champs_postraitables(), and nombre_d_equations().
Referenced by Modele_turbulence_hyd_K_Eps_Bicephale::get_noms_champs_postraitables(), and Modele_turbulence_hyd_K_Eps_Realisable_Bicephale::get_noms_champs_postraitables().
nombre_d_equations()
int Modele_turbulence_hyd_RANS_Bicephale_base::nombre_d_equations () const inline override virtual
Reimplemented from Modele_turbulence_hyd_2_eq_base.
Referenced by get_champ(), get_noms_champs_postraitables(), has_champ(), and Modele_turbulence_hyd_K_Eps_Bicephale::preparer_calcul().
eqn_transp_K() [1/2]
virtual Transport_K_ou_Eps_base & Modele_turbulence_hyd_RANS_Bicephale_base::eqn_transp_K () pure virtual
Implemented in Modele_turbulence_hyd_K_Eps_Bicephale, and Modele_turbulence_hyd_K_Eps_Realisable_Bicephale.
Referenced by completer(), data_a_sauvegarder(), lire_motcle_non_standard(), reprendre(), and sauvegarder().
eqn_transp_Eps() [1/2]
virtual Transport_K_ou_Eps_base & Modele_turbulence_hyd_RANS_Bicephale_base::eqn_transp_Eps () pure virtual
Implemented in Modele_turbulence_hyd_K_Eps_Bicephale, and Modele_turbulence_hyd_K_Eps_Realisable_Bicephale.
Referenced by completer(), lire_motcle_non_standard(), reprendre(), and sauvegarder().
eqn_transp_K() [2/2]
virtual const Transport_K_ou_Eps_base & Modele_turbulence_hyd_RANS_Bicephale_base::eqn_transp_K () const pure virtual
Implemented in Modele_turbulence_hyd_K_Eps_Bicephale, and Modele_turbulence_hyd_K_Eps_Realisable_Bicephale.
eqn_transp_Eps() [2/2]
virtual const Transport_K_ou_Eps_base & Modele_turbulence_hyd_RANS_Bicephale_base::eqn_transp_Eps () const pure virtual
Implemented in Modele_turbulence_hyd_K_Eps_Bicephale, and Modele_turbulence_hyd_K_Eps_Realisable_Bicephale.
equation_k_eps()
virtual const Equation_base & Modele_turbulence_hyd_RANS_Bicephale_base::equation_k_eps (int) const pure virtual
Implemented in Modele_turbulence_hyd_K_Eps_Bicephale, and Modele_turbulence_hyd_K_Eps_Realisable_Bicephale.
Referenced by get_champ(), get_noms_champs_postraitables(), and has_champ().
associer_seconde_eqn()
void Modele_turbulence_hyd_RANS_Bicephale_base::associer_seconde_eqn (const Equation_base & eqn)
Associe la seconde equation en parametre au modele de turbulence.
Parameters
(Equation_base& eqn) la seconde equation a laquelle l'objet s'associe
References ma_seconde_equation_.
seconde_equation() [1/2]
Equation_base & Modele_turbulence_hyd_RANS_Bicephale_base::seconde_equation () inline
Renvoie la seconde equation associee au modele de turbulence en formulation bicephale.
(c'est une equation du type Equation_base)
Returns
(Equation_base&) la seconde equation associee au modele de turbulence en formulation bicephale
References TRUST_Ref< _CLASSE_ >::est_nul(), Process::exit(), ma_seconde_equation_, and TRUST_Ref< _CLASSE_ >::valeur().
seconde_equation() [2/2]
const Equation_base & Modele_turbulence_hyd_RANS_Bicephale_base::seconde_equation () const inline
References TRUST_Ref< _CLASSE_ >::est_nul(), Process::exit(), ma_seconde_equation_, and TRUST_Ref< _CLASSE_ >::valeur().
Member Data Documentation
info_obj
const Type_info Modele_turbulence_hyd_RANS_Bicephale_base::info_obj static
ma_seconde_equation_
TRUST_Ref< Equation_base *> Modele_turbulence_hyd_RANS_Bicephale_base::ma_seconde_equation_ protected
Referenced by associer_seconde_eqn(), and seconde_equation().