TrioCFD: Source_Masse_Fluide_Dilatable_VDF Class Reference
Source_Masse_Fluide_Dilatable_VDF Class Reference
#include <Source_Masse_Fluide_Dilatable_VDF.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Source_Masse_Fluide_Dilatable_VDF()
Source_Masse_Fluide_Dilatable_VDF::Source_Masse_Fluide_Dilatable_VDF ()
~Source_Masse_Fluide_Dilatable_VDF()
Source_Masse_Fluide_Dilatable_VDF::~Source_Masse_Fluide_Dilatable_VDF ()
Member Function Documentation
cree_instance()
Objet_U * Source_Masse_Fluide_Dilatable_VDF::cree_instance () static
taille_memoire()
unsigned Source_Masse_Fluide_Dilatable_VDF::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Source_Masse_Fluide_Dilatable_VDF::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Source_Masse_Fluide_Dilatable_VDF::info () static
get_info()
const Type_info * Source_Masse_Fluide_Dilatable_VDF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Source_Masse_Fluide_Dilatable_base.
self_cast() [1/2]
Source_Masse_Fluide_Dilatable_VDF & Source_Masse_Fluide_Dilatable_VDF::self_cast (Objet_U & r) static
self_cast() [2/2]
const Source_Masse_Fluide_Dilatable_VDF & Source_Masse_Fluide_Dilatable_VDF::self_cast (const Objet_U & r) static
printOn()
Sortie & Source_Masse_Fluide_Dilatable_VDF::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Source_Masse_Fluide_Dilatable_base.
readOn()
Entree & Source_Masse_Fluide_Dilatable_VDF::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Source_Masse_Fluide_Dilatable_base.
References Source_Masse_Fluide_Dilatable_base::readOn().
ajouter_eq_espece()
void Source_Masse_Fluide_Dilatable_VDF::ajouter_eq_espece (const Convection_Diffusion_Fluide_Dilatable_base & eqn, const Fluide_Dilatable_base & fluide, const bool is_expl, DoubleVect & resu) const override virtual
Implements Source_Masse_Fluide_Dilatable_base.
ajouter_projection()
void Source_Masse_Fluide_Dilatable_VDF::ajouter_projection (const Fluide_Dilatable_base & fluide, DoubleVect & resu) const override virtual
Implements Source_Masse_Fluide_Dilatable_base.
References Source_Masse_Fluide_Dilatable_base::domaine_cl_dis_, Domaine_Cl_dis_base::domaine_dis(), Domaine_VF::face_surfaces(), Domaine_VF::face_voisins(), Source_Masse_Fluide_Dilatable_base::fill_val_flux_tab(), Fluide_Dilatable_base::has_source_masse_projection_champ(), Fluide_Dilatable_base::inco_chaleur(), Frontiere_dis_base::le_nom(), Domaine_VF::nb_faces(), Front_VF::nb_faces(), Source_Masse_Fluide_Dilatable_base::nom_bord_, Front_VF::num_premiere_face(), Champ_base::temps(), TRUST_Ref< _CLASSE_ >::valeur(), and Domaine_VF::volumes().
Member Data Documentation
info_obj
const Type_info Source_Masse_Fluide_Dilatable_VDF::info_obj static