TrioCFD: Source_Qdm_VDF_Phase_field Class Reference
Source_Qdm_VDF_Phase_field Class Reference
#include <Source_Qdm_VDF_Phase_field.h>
Public Member Functions
const Type_info * get_info () const override
void mettre_a_jour (double) override
Public Member Functions inherited from Source_base
virtual int a_pour_Champ_Fonc (const Motcle &mot, TRUST_Ref< Champ_base * > &ch_ref) const
virtual void associer_champ_rho (const Champ_base &champ_rho)
virtual void completer ()
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
virtual void resetTime (double t)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Terme_Source_Qdm
const Champ_Don_base & source () const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
See also
Source_base
Constructor & Destructor Documentation
Source_Qdm_VDF_Phase_field()
Source_Qdm_VDF_Phase_field::Source_Qdm_VDF_Phase_field ()
~Source_Qdm_VDF_Phase_field()
Source_Qdm_VDF_Phase_field::~Source_Qdm_VDF_Phase_field ()
Member Function Documentation
cree_instance()
Objet_U * Source_Qdm_VDF_Phase_field::cree_instance () static
taille_memoire()
unsigned Source_Qdm_VDF_Phase_field::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Source_Qdm_VDF_Phase_field::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Source_Qdm_VDF_Phase_field::info () static
get_info()
const Type_info * Source_Qdm_VDF_Phase_field::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Source_base.
self_cast() [1/2]
Source_Qdm_VDF_Phase_field & Source_Qdm_VDF_Phase_field::self_cast (Objet_U & r) static
self_cast() [2/2]
const Source_Qdm_VDF_Phase_field & Source_Qdm_VDF_Phase_field::self_cast (const Objet_U & r) static
printOn()
Sortie & Source_Qdm_VDF_Phase_field::printOn (Sortie & os) const override protected virtual
DOES NOTHING - to override in derived classes.
Imprime la source sur un flot de sortie.
Parameters
(Sortie& os) le flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Source_base.
References Objet_U::que_suis_je().
readOn()
Entree & Source_Qdm_VDF_Phase_field::readOn (Entree & is) override protected virtual
DOES NOTHING - to override in derived classes.
Lecture d'un terme source sur un flot d'entree.
Parameters
(Entree& is) le flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Source_base.
References compressible, Process::exit(), methode, methode_1(), methode_2(), methode_3(), methode_4(), and terme_source.
associer_pb()
void Source_Qdm_VDF_Phase_field::associer_pb (const Probleme_base & pb) override virtual
Implements Source_base.
References boussi_, compressible, Process::exit(), Navier_Stokes_phase_field::get_boussi_(), Navier_Stokes_phase_field::getset_compressible_(), Navier_Stokes_phase_field::getset_terme_source_(), le_probleme2, Navier_Stokes_phase_field::rho0(), rho0, and terme_source.
methode_1()
DoubleTab & Source_Qdm_VDF_Phase_field::methode_1 (DoubleTab & resu) const
References boussi_, Operateur_Grad::calculer(), Convection_Diffusion_Concentration::constituant(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Source_Con_Phase_field::drhodc(), Domaine_VF::face_voisins(), Convection_Diffusion_Phase_field::get_mutilde_(), Convection_Diffusion_Phase_field::get_mutype_(), Source_Con_Phase_field::get_type_systeme_naire(), Source_Con_Phase_field::get_u_carre(), grad_mutilde_, Convection_Diffusion_Concentration::inconnue(), Navier_Stokes_std::inconnue(), le_dom_VDF, le_probleme2, Constituant::nb_constituants(), Domaine_VF::nb_faces(), Navier_Stokes_std::operateur_gradient(), Domaine_VF::premiere_face_int(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Navier_Stokes_phase_field::rho(), rho0, TRUSTVect< _TYPE_, _SIZE_ >::size(), TRUSTVect< _TYPE_, _SIZE_ >::size_totale(), Equation_base::sources(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), Champ_Inc_base::valeurs(), and Domaine_VF::volumes().
Referenced by readOn().
methode_2()
DoubleTab & Source_Qdm_VDF_Phase_field::methode_2 (DoubleTab & resu) const
References boussi_, Operateur_Grad::calculer(), compressible, Domaine_VF::face_voisins(), Convection_Diffusion_Phase_field::get_div_alpha_rho_gradC(), Source_Con_Phase_field::get_type_systeme_naire(), grad_div_alpha_rho_gradC_, Convection_Diffusion_Concentration::inconnue(), Navier_Stokes_std::inconnue(), le_dom_VDF, le_probleme2, Domaine_VF::nb_faces(), Navier_Stokes_std::operateur_gradient(), Domaine_VF::premiere_face_int(), Navier_Stokes_phase_field::rho(), rho0, TRUSTVect< _TYPE_, _SIZE_ >::size(), Equation_base::sources(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), Champ_Inc_base::valeurs(), and Domaine_VF::volumes().
Referenced by readOn().
methode_3()
DoubleTab & Source_Qdm_VDF_Phase_field::methode_3 (DoubleTab & resu) const
References boussi_, Operateur_Grad::calculer(), compressible, Domaine_VF::face_voisins(), Convection_Diffusion_Phase_field::get_alpha_gradC_carre(), Convection_Diffusion_Phase_field::get_div_alpha_rho_gradC(), Source_Con_Phase_field::get_type_systeme_naire(), grad_alpha_gradC_carre_, grad_div_alpha_rho_gradC_, Convection_Diffusion_Concentration::inconnue(), Navier_Stokes_std::inconnue(), le_dom_VDF, le_probleme2, Domaine_VF::nb_faces(), Navier_Stokes_std::operateur_gradient(), Domaine_VF::premiere_face_int(), Navier_Stokes_phase_field::rho(), rho0, TRUSTVect< _TYPE_, _SIZE_ >::size(), Equation_base::sources(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), Champ_Inc_base::valeurs(), and Domaine_VF::volumes().
Referenced by readOn().
methode_4()
DoubleTab & Source_Qdm_VDF_Phase_field::methode_4 (DoubleTab & resu) const
References boussi_, Operateur_Grad::calculer(), compressible, Domaine_VF::face_voisins(), Convection_Diffusion_Phase_field::get_div_alpha_rho_gradC(), Source_Con_Phase_field::get_type_systeme_naire(), gradC_, Convection_Diffusion_Concentration::inconnue(), Navier_Stokes_std::inconnue(), le_dom_VDF, le_probleme2, Domaine_VF::nb_faces(), Navier_Stokes_std::operateur_gradient(), Domaine_VF::premiere_face_int(), Navier_Stokes_phase_field::rho(), rho0, TRUSTVect< _TYPE_, _SIZE_ >::size(), Equation_base::sources(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), Champ_Inc_base::valeurs(), and Domaine_VF::volumes().
Referenced by readOn().
ajouter()
DoubleTab & Source_Qdm_VDF_Phase_field::ajouter (DoubleTab & resu) const override virtual
Reimplemented from Source_base.
References methode.
Referenced by calculer().
calculer()
DoubleTab & Source_Qdm_VDF_Phase_field::calculer (DoubleTab & resu) const override virtual
Reimplemented from Source_base.
References ajouter().
mettre_a_jour()
void Source_Qdm_VDF_Phase_field::mettre_a_jour (double temps) override virtual
DOES NOTHING - to override in derived classes.
Mise a jour en temps du terme source.
Parameters
(double) le pas de temps de mise a jour
Reimplemented from Source_base.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Navier_Stokes_std::inconnue(), le_probleme2, Objet_U::nom_du_cas(), Sortie_Fichier_base::precision(), and Champ_Inc_base::valeurs().
associer_domaines()
void Source_Qdm_VDF_Phase_field::associer_domaines (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis) override protected virtual
Implements Source_base.
References le_dom_Cl_VDF, and le_dom_VDF.
Member Data Documentation
info_obj
const Type_info Source_Qdm_VDF_Phase_field::info_obj static
terme_source
int Source_Qdm_VDF_Phase_field::terme_source protected
Referenced by associer_pb(), and readOn().
compressible
int Source_Qdm_VDF_Phase_field::compressible protected
Referenced by associer_pb(), methode_2(), methode_3(), methode_4(), and readOn().
rho0
double Source_Qdm_VDF_Phase_field::rho0 protected
Referenced by associer_pb(), methode_1(), methode_2(), methode_3(), and methode_4().
grad_mutilde_
DoubleTab Source_Qdm_VDF_Phase_field::grad_mutilde_ protected
Referenced by methode_1().
grad_div_alpha_rho_gradC_
DoubleTab Source_Qdm_VDF_Phase_field::grad_div_alpha_rho_gradC_ protected
Referenced by methode_2(), and methode_3().
grad_alpha_gradC_carre_
DoubleTab Source_Qdm_VDF_Phase_field::grad_alpha_gradC_carre_ protected
Referenced by methode_3().
gradC_
DoubleTab Source_Qdm_VDF_Phase_field::gradC_ protected
Referenced by methode_4().
boussi_
int Source_Qdm_VDF_Phase_field::boussi_ protected
Referenced by associer_pb(), methode_1(), methode_2(), methode_3(), and methode_4().
le_dom_VDF
TRUST_Ref< Domaine_VDF *> Source_Qdm_VDF_Phase_field::le_dom_VDF protected
Referenced by associer_domaines(), methode_1(), methode_2(), methode_3(), and methode_4().
le_dom_Cl_VDF
TRUST_Ref< Domaine_Cl_VDF *> Source_Qdm_VDF_Phase_field::le_dom_Cl_VDF protected
Referenced by associer_domaines().
le_probleme2
TRUST_Ref< Probleme_base *> Source_Qdm_VDF_Phase_field::le_probleme2 protected
Referenced by associer_pb(), methode_1(), methode_2(), methode_3(), methode_4(), and mettre_a_jour().
methode
DoubleTab &(Source_Qdm_VDF_Phase_field::* Source_Qdm_VDF_Phase_field::methode) (DoubleTab &) const protected
Referenced by ajouter(), and readOn().