TrioCFD: Frontiere_Ouverte_Rayo_transp Class Reference
Frontiere_Ouverte_Rayo_transp Class Reference
#include <Frontiere_Ouverte_Rayo_transp.h>
Public Member Functions
const Type_info * get_info () const override
void mettre_a_jour (double) override
Public Member Functions inherited from Neumann_sortie_libre
void associer_fr_dis_base (const Frontiere_dis_base &) override
const Type_info * get_info () const override
int initialiser (double temps) override
void mettre_a_jour (double temps) override
double val_ext (int i) const override
double val_ext (int i, int j) const override
void verifie_ch_init_nb_comp () const override
const Type_info * get_info () const override
Public Member Functions inherited from Neumann
const DoubleTab & flux_impose (bool nb_faces_tot=false) const
virtual double flux_impose (int i) const
virtual double flux_impose (int i, int j) const
const Type_info * get_info () const override
Public Member Functions inherited from Cond_lim_base
virtual int a_mettre_a_jour_ss_pas_dt ()
virtual void associer_domaine_cl_dis_base (const Domaine_Cl_dis_base &)
virtual void associer_fr_dis_base (const Frontiere_dis_base &)
virtual void calculer_coeffs_echange (double temps)
virtual int compatible_avec_discr (const Discretisation_base &) const
Domaine_Cl_dis_base & domaine_Cl_dis ()
const Domaine_Cl_dis_base & domaine_Cl_dis () const
virtual Frontiere_dis_base & frontiere_dis ()
virtual const Frontiere_dis_base & frontiere_dis () const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
void set_modifier_val_imp (int)
virtual void verifie_ch_init_nb_comp () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Cond_lim_base
void err_pas_compatible (const Discretisation_base &) const
void err_pas_compatible (const Equation_base &) const
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Frontiere_Ouverte_Rayo_transp()
Frontiere_Ouverte_Rayo_transp::Frontiere_Ouverte_Rayo_transp ()
~Frontiere_Ouverte_Rayo_transp()
Frontiere_Ouverte_Rayo_transp::~Frontiere_Ouverte_Rayo_transp ()
Member Function Documentation
cree_instance()
Objet_U * Frontiere_Ouverte_Rayo_transp::cree_instance () static
taille_memoire()
unsigned Frontiere_Ouverte_Rayo_transp::taille_memoire () const override virtual
Reimplemented from Neumann_sortie_libre.
duplique()
int Frontiere_Ouverte_Rayo_transp::duplique () const override virtual
Reimplemented from Neumann_sortie_libre.
info()
const Type_info * Frontiere_Ouverte_Rayo_transp::info () static
get_info()
const Type_info * Frontiere_Ouverte_Rayo_transp::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Neumann_sortie_libre.
self_cast() [1/2]
Frontiere_Ouverte_Rayo_transp & Frontiere_Ouverte_Rayo_transp::self_cast (Objet_U & r) static
self_cast() [2/2]
const Frontiere_Ouverte_Rayo_transp & Frontiere_Ouverte_Rayo_transp::self_cast (const Objet_U & r) static
printOn()
Sortie & Frontiere_Ouverte_Rayo_transp::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Neumann_sortie_libre.
readOn()
Entree & Frontiere_Ouverte_Rayo_transp::readOn (Entree & s) override protected virtual
Type le_champ_front en "Champ_front_uniforme".
Lit les valeurs du champ exterieur si les conditions aux limites sont specifiees: "T_ext","C_ext","Y_ext","K_Eps_ext","Fluctu_Temperature_ext","Flux_Chaleur_Turb_ext","V2_ext","a_ext","tau_ext","k_ext","omega_ext","H_ext" Produit une erreur sinon.
Parameters
(Entree& s) un flot d'entree
Returns
(Entree& s) le flot d'entree modifie
Exceptions
type de champ exterieur non reconnu, les types reconnus sont: "T_ext","C_ext","Y_ext","K_Eps_ext","Fluctu_Temperature_ext","Flux_Chaleur_Turb_ext","V2_ext","a_ext","tau_ext","k_ext","omega_ext","H_ext"
Reimplemented from Neumann_sortie_libre.
References Neumann_sortie_libre::readOn().
completer()
void Frontiere_Ouverte_Rayo_transp::completer () override virtual
Reimplemented from Cond_Lim_Rayo.
References Cond_lim_base::completer(), Cond_lim_base::domaine_Cl_dis(), Cond_lim_base::frontiere_dis(), and Cond_Lim_Rayo::preparer_surface().
mettre_a_jour()
void Frontiere_Ouverte_Rayo_transp::mettre_a_jour (double temps) override virtual
Effectue une mise a jour en temps de la condition aux limites.
Parameters
(double temps) le pas de temps de mise a jour
Reimplemented from Neumann_sortie_libre.
References calculer_Teta_i(), and Neumann_sortie_libre::mettre_a_jour().
calculer_Teta_i()
void Frontiere_Ouverte_Rayo_transp::calculer_Teta_i ()
References Cond_lim_base::frontiere_dis(), Front_VF::nb_faces(), Cond_Lim_Rayo::Teta_i, and Neumann_sortie_libre::val_ext().
Referenced by mettre_a_jour().
Member Data Documentation
info_obj
const Type_info Frontiere_Ouverte_Rayo_transp::info_obj static