TrioCFD: Operator_FT_Disc Class Reference
Operator_FT_Disc Class Reference
#include <Operator_FT_Disc.h>
Member Function Documentation
Operator_Laplacian_FT_element()
void Operator_FT_Disc::Operator_Laplacian_FT_element (const ArrOfDouble & Phi_Facet, const Maillage_FT_Disc & FTmesh, ArrOfDouble & Laplacian_Phi_Facet, DoubleTab & Grad_Phi_Sommet)
References Maillage_FT_Disc::desc_facettes(), Objet_U::dimension, Desc_Structure_FT::echange_espace_virtuel(), Maillage_FT_Disc::facette_virtuelle(), Maillage_FT_Disc::facettes(), Maillage_FT_Disc::get_update_normale_facettes(), Maillage_FT_Disc::nb_facettes(), Operator_Gradient_FT_sommets(), produit_vectoriel(), TRUSTArray< _TYPE_, _SIZE_ >::resize(), and Maillage_FT_Disc::sommets().
Referenced by FT_Field::update_gradient_laplacien_FT().
Operator_Gradient_FT_sommets()
void Operator_FT_Disc::Operator_Gradient_FT_sommets (const ArrOfDouble & Phi_Facet, const Maillage_FT_Disc & FTmesh, DoubleTab & Grad_Phi_Sommet, bool Normalised_with_Surface = true)
References Maillage_FT_Disc::desc_sommets(), Objet_U::dimension, Desc_Structure_FT::echange_espace_virtuel(), Facette_to_Sommets(), Maillage_FT_Disc::nb_facettes(), Maillage_FT_Disc::nb_sommets(), Operator_integral_bord_facette_phi_p_dl(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::resize(), and Maillage_FT_Disc::sommet_virtuel().
Referenced by Operator_Laplacian_FT_element().
Compute_interfaciale_source()
void Operator_FT_Disc::Compute_interfaciale_source (const ArrOfDouble & sigma_Facet, const Maillage_FT_Disc & FTmesh, DoubleTab & df_sigma, bool Normalised_with_Surface, bool use_tryggvason_formulation, bool with_marangoni = false)
References Maillage_FT_Disc::desc_sommets(), Objet_U::dimension, Desc_Structure_FT::echange_espace_virtuel(), Facette_to_Sommets(), Maillage_FT_Disc::nb_facettes(), Maillage_FT_Disc::nb_sommets(), Operator_integral_bord_facette_phi_p_dl(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::resize(), and Maillage_FT_Disc::sommet_virtuel().
Referenced by Maillage_FT_IJK::update_sigma_and_interfacial_source_term_sommet(), and FT_Field::update_sigma_and_interfacial_source_term_sommet().
Operator_integral_bord_facette_phi_p_dl()
void Operator_FT_Disc::Operator_integral_bord_facette_phi_p_dl (const ArrOfDouble & Surface_sommet, const ArrOfDouble & Phi_sommet, const ArrOfDouble & Phi_Facet, const Maillage_FT_Disc & FTmesh, DoubleTab & int_phi_p_dl, DoubleTab & int_p_dl)
References Desc_Structure_FT::collecter_espace_virtuel(), Maillage_FT_Disc::desc_sommets(), Objet_U::dimension, Desc_Structure_FT::echange_espace_virtuel(), MD_Vector_tools::EV_SOMME, Maillage_FT_Disc::facette_virtuelle(), Maillage_FT_Disc::facettes(), Maillage_FT_Disc::get_update_normale_facettes(), Maillage_FT_Disc::nb_facettes(), Maillage_FT_Disc::nb_sommets(), produit_vectoriel(), Maillage_FT_Disc::sommet_virtuel(), Maillage_FT_Disc::sommets(), and unitarisation().
Referenced by Compute_interfaciale_source(), and Operator_Gradient_FT_sommets().
Sommets_to_Facettes() [1/2]
void Operator_FT_Disc::Sommets_to_Facettes (DoubleTab & Phi_Facet, const DoubleTab & Phi_Som, const Maillage_FT_Disc & FTmesh, bool Normalised_with_Surface)
References Objet_U::dimension, Maillage_FT_Disc::nb_facettes(), Maillage_FT_Disc::nb_sommets(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::resize(), and Sommets_to_Facettes().
Referenced by Sommets_to_Facettes().
Sommets_to_Facettes() [2/2]
void Operator_FT_Disc::Sommets_to_Facettes (ArrOfDouble & Phi_Facet, const ArrOfDouble & Phi_Som, const Maillage_FT_Disc & FTmesh, bool Normalised_with_Surface)
References Maillage_FT_Disc::desc_facettes(), Objet_U::dimension, Desc_Structure_FT::echange_espace_virtuel(), Maillage_FT_Disc::facette_virtuelle(), Maillage_FT_Disc::facettes(), Maillage_FT_Disc::get_update_surface_facettes(), Maillage_FT_Disc::nb_facettes(), and TRUSTArray< _TYPE_, _SIZE_ >::resize().
Facette_to_Sommets() [1/2]
void Operator_FT_Disc::Facette_to_Sommets (ArrOfDouble & Surface_sommet, DoubleTab & Phi_Som, const DoubleTab & Phi_Facet, const Maillage_FT_Disc & FTmesh, bool Normalised_with_Surface)
References Objet_U::dimension, Facette_to_Sommets(), Maillage_FT_Disc::nb_facettes(), Maillage_FT_Disc::nb_sommets(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), and TRUSTArray< _TYPE_, _SIZE_ >::resize().
Referenced by Compute_interfaciale_source(), Facette_to_Sommets(), and Operator_Gradient_FT_sommets().
Facette_to_Sommets() [2/2]
void Operator_FT_Disc::Facette_to_Sommets (ArrOfDouble & Surface_sommet, ArrOfDouble & Phi_Som, const ArrOfDouble & Phi_Facet, const Maillage_FT_Disc & FTmesh, bool Normalised_with_Surface)
References Desc_Structure_FT::collecter_espace_virtuel(), Maillage_FT_Disc::desc_sommets(), Objet_U::dimension, Desc_Structure_FT::echange_espace_virtuel(), MD_Vector_tools::EV_SOMME, Maillage_FT_Disc::facette_virtuelle(), Maillage_FT_Disc::facettes(), Maillage_FT_Disc::get_update_surface_facettes(), Maillage_FT_Disc::nb_facettes(), Maillage_FT_Disc::nb_sommets(), TRUSTArray< _TYPE_, _SIZE_ >::resize(), and Maillage_FT_Disc::sommet_virtuel().
produit_vectoriel()
void Operator_FT_Disc::produit_vectoriel (const ArrOfDouble & a, const ArrOfDouble & b, ArrOfDouble & resu)
References Objet_U::dimension.
Referenced by Operator_integral_bord_facette_phi_p_dl(), and Operator_Laplacian_FT_element().
norme()
double Operator_FT_Disc::norme (const ArrOfDouble & a)
References Objet_U::dimension.
Referenced by unitarisation().
unitarisation()
void Operator_FT_Disc::unitarisation (ArrOfDouble & a)
References Objet_U::dimension, and norme().
Referenced by Operator_integral_bord_facette_phi_p_dl().
get_Phi_sommet()
const ArrOfDouble & Operator_FT_Disc::get_Phi_sommet () const inline
References Phi_sommet_.
get_Surface_sommet()
const ArrOfDouble & Operator_FT_Disc::get_Surface_sommet () const inline
References Surface_sommet_.
get_n_sommet() [1/2]
const DoubleTab & Operator_FT_Disc::get_n_sommet () const inline
References n_sommet_.
get_n_sommet() [2/2]
ArrOfDouble Operator_FT_Disc::get_n_sommet (int dir) const inline
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), n_sommet_, and TRUSTArray< _TYPE_, _SIZE_ >::resize().
Member Data Documentation
Phi_sommet_
ArrOfDouble Operator_FT_Disc::Phi_sommet_
Referenced by get_Phi_sommet().
Surface_sommet_
ArrOfDouble Operator_FT_Disc::Surface_sommet_
Referenced by get_Surface_sommet().
Kappa_n_
DoubleTab Operator_FT_Disc::Kappa_n_
n_sommet_
DoubleTab Operator_FT_Disc::n_sommet_
Referenced by get_n_sommet().