TrioCFD: Memoire_ptr Class Reference
Memoire_ptr Class Reference
#include <Memoire_ptr.h>
Public Member Functions
int libre () const
Memoire_ptr (Objet_U *ptr=0)
Objet_U & obj ()
Memoire_ptr & operator= (const Memoire_ptr &)
void set (Objet_U *ptr)
Detailed Description
See also
Objet_U Memoire
Constructor & Destructor Documentation
Memoire_ptr()
Memoire_ptr::Memoire_ptr (Objet_U * ptr = 0)
Constructeur.
Parameters
(Objet_U* ptr) l'Objet_U sur lequel pointer
References next.
Member Function Documentation
libre()
int Memoire_ptr::libre () const inline
Indique si le pointeur memoire est libre, c'est-a-dire s'il pointe sur un Objet_U non nul.
Returns
(int) 1 si le pointeur est libre
Referenced by Memoire::rang().
set()
void Memoire_ptr::set (Objet_U * ptr) inline
Affecte un Objet_U a un pointeur memoire.
Parameters
(Objet_U* ptr) pointeur sur un Objet_U
Referenced by Memoire::add(), and Memoire::suppr().
obj()
Objet_U & Memoire_ptr::obj () inline
Retourne une reference sur l'Objet_U pointe par le pointeur memoire.
Returns
(Objet_U&) reference sur l'Objet_U pointe
Referenced by Memoire::imprime(), Memoire::objet_u(), Memoire::objet_u_ptr(), and Memoire::rang().
operator=()
Memoire_ptr & Memoire_ptr::operator= (const Memoire_ptr & mptr) inline
Operateur d'affectation entre pointeurs memoire Dans le cas A=B, l'Objet_U pointe par A est l'Objet_U pointe par B.
Parameters
(const Memoire_ptr& mptr) le pointeur memoire B
Returns
(Memoire_ptr&) le pointeur memoire A
References next.
Member Data Documentation
next
int Memoire_ptr::next
Referenced by Memoire::add(), Memoire_ptr(), operator=(), and Memoire::suppr().