TrioCFD: Solid_Particle_arbitrary Class Reference
Solid_Particle_arbitrary Class Reference
#include <Solid_Particle_arbitrary.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Solid_Particle_base
const Type_info * get_info () const override
Public Member Functions inherited from Fluide_Incompressible
const Type_info * get_info () const override
void verifier_coherence_champs (int &err, Nom &message) override
Public Member Functions inherited from Fluide_base
const Type_info * get_info () const override
void mettre_a_jour (double) override
void verifier_coherence_champs (int &err, Nom &message) override
Public Member Functions inherited from Milieu_base
virtual int a_gravite () const
int associer_ (Objet_U &) override
virtual void associer_gravite (const Champ_Don_base &)
virtual Champ_Don_base & beta_t ()
virtual const Champ_Don_base & beta_t () const
virtual Champ_Don_base & capacite_calorifique ()
virtual const Champ_Don_base & capacite_calorifique () const
virtual Champ_Don_base & conductivite ()
virtual const Champ_Don_base & conductivite () const
virtual Champ_Don_base & diffusivite ()
virtual const Champ_Don_base & diffusivite () const
virtual int est_deja_associe ()
const Type_info * get_info () const override
virtual Champ_Don_base & gravite ()
virtual const Champ_Don_base & gravite () const
const Nom & le_nom () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual Champ_base & masse_volumique ()
virtual const Champ_base & masse_volumique () const
void nommer (const Nom &) override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Solid_Particle_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Fluide_base
void creer_nu ()
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Milieu_base
virtual void calculer_alpha ()
void ecrire (Sortie &) const
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
~Solid_Particle_arbitrary()
Solid_Particle_arbitrary::~Solid_Particle_arbitrary ()
Solid_Particle_arbitrary()
Solid_Particle_arbitrary::Solid_Particle_arbitrary ()
Member Function Documentation
cree_instance()
Objet_U * Solid_Particle_arbitrary::cree_instance () static
taille_memoire()
unsigned Solid_Particle_arbitrary::taille_memoire () const override virtual
Reimplemented from Fluide_Incompressible.
duplique()
int Solid_Particle_arbitrary::duplique () const override virtual
Reimplemented from Fluide_Incompressible.
info()
const Type_info * Solid_Particle_arbitrary::info () static
get_info()
const Type_info * Solid_Particle_arbitrary::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Fluide_Incompressible.
self_cast() [1/2]
Solid_Particle_arbitrary & Solid_Particle_arbitrary::self_cast (Objet_U & r) static
self_cast() [2/2]
const Solid_Particle_arbitrary & Solid_Particle_arbitrary::self_cast (const Objet_U & r) static
printOn()
Sortie & Solid_Particle_arbitrary::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Fluide_Incompressible.
References Process::exit().
readOn()
Entree & Solid_Particle_arbitrary::readOn (Entree & is) override protected virtual
Lit les caracteristiques du fluide a partir d'un flot d'entree.
Format: Fluide_base { Mu type_champ bloc de lecture de champ Rho Champ_Uniforme 1 vrel [Cp Champ_Uniforme 1 vrel] [Lambda type_champ bloc de lecture de champ] [Beta_th type_champ bloc de lecture de champ] [Beta_co type_champ bloc de lecture de champ] } cf Milieu_base::readOn
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Exceptions
accolade ouvrante attendue
Reimplemented from Fluide_Incompressible.
References Solid_Particle_base::readOn().
set_param()
void Solid_Particle_arbitrary::set_param (Param & param) override virtual
Reimplemented from Fluide_Incompressible.
References Solid_Particle_base::set_param().
get_half_small_axis_arbitrary()
const double & Solid_Particle_arbitrary::get_half_small_axis_arbitrary () const inline
References half_small_axis_arbitrary_.
get_half_long_axis_arbitrary()
const double & Solid_Particle_arbitrary::get_half_long_axis_arbitrary () const inline
References half_long_axis_arbitrary_.
Member Data Documentation
info_obj
const Type_info Solid_Particle_arbitrary::info_obj static
half_small_axis_arbitrary_
double Solid_Particle_arbitrary::half_small_axis_arbitrary_ =0 protected
Referenced by get_half_small_axis_arbitrary().
half_long_axis_arbitrary_
double Solid_Particle_arbitrary::half_long_axis_arbitrary_ =0 protected
Referenced by get_half_long_axis_arbitrary().