TrioCFD: Champ_Don_base Class Reference
Champ_Don_base Class Reference
#include <Champ_Don_base.h>
Public Member Functions
void dimensionner (int, int)
int fixer_nb_valeurs_nodales (int nb_noeuds) override
const Type_info * get_info () const override
int imprime (Sortie &, int) const override
virtual int initialiser (const double temps)
void mettre_a_jour (double temps) override
int reprendre (Entree &) override
void resetTime (double time) override
int sauvegarder (Sortie &) const override
DoubleTab & valeurs () override
Public Member Functions inherited from Champ_base
Champ_base & affecter (const Champ_base &)
Champ_base ()
virtual double changer_temps (const double t)
const Type_info * get_info () const override
double temps () const
virtual DoubleTab & trace (const Frontiere_dis_base &, DoubleTab &, double, int distant) const
virtual DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const
virtual double valeur_a_compo (const DoubleVect &position, int ncomp) const
virtual DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &valeurs, int le_poly) const
virtual double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const
virtual DoubleVect & valeur_a_sommet (int, const Domaine &, DoubleVect &) const
virtual DoubleTab & valeur_aux (const DoubleTab &positions, DoubleTab &valeurs) const
virtual DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const
virtual DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const
virtual DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp) const
Public Member Functions inherited from Field_base
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
virtual void fixer_nb_comp (int i)
virtual const Nom & fixer_nom_compo (const Nom &)
virtual const Nom & fixer_nom_compo (int, const Nom &)
virtual const Noms & fixer_noms_compo (const Noms &)
virtual const Nom & fixer_unite (const Nom &)
virtual const Nom & fixer_unite (int i, const Nom &)
virtual const Noms & fixer_unites (const Noms &)
const Type_info * get_info () const override
const Nom & nom_compo (int) const
void nommer (const Nom &) override
const Nom & unite () const
const Nom & unite (int) const
const Noms & unites () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Champ_Proto
int lire_dimension (Entree &, const Nom &)
int lire_dimension (int dim, const Nom &le_nom_)
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Field_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
les proprietes physiques sont des Champs donnes
mais peuvent etre variables dans le temps dans l'espace
fonctions d'autres champs ...
See also
Champ_base OWN_PTR(Champ_Don_base) Champ_Fonc_base
Constructor & Destructor Documentation
Champ_Don_base()
Champ_Don_base::Champ_Don_base ()
~Champ_Don_base()
Champ_Don_base::~Champ_Don_base () override
Member Function Documentation
info()
const Type_info * Champ_Don_base::info () static
get_info()
const Type_info * Champ_Don_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Champ_base.
Reimplemented in Champ_Fonc_reprise_IJK, Estimateur_Aposteriori_P0_VEF, Field_uniform_keps_from_ud, Champ_Fonc_base, Champ_Parametrique, Champ_Fonc_MED, Champ_Fonc_MED_Table_Temps, Champ_Fonc_MED_Tabule, Champ_Fonc_P0_MED, Champ_Fonc_P1_MED, Champ_Fonc_Q1_MED, Champ_Fonc_reprise, Champ_Fonc_Elem_PolyMAC, Champ_Fonc_Elem_PolyMAC_P0_rot, Champ_Fonc_Elem_PolyMAC_P0_TC, Champ_Fonc_Face_PolyMAC, Champ_Fonc_Som_PolyMAC, Champ_Fonc_Tabule_Elem_PolyMAC, grad_Champ_Face_PolyMAC_P0, grad_U_Champ_Face_PolyMAC, Champ_Ostwald, Champ_Don_Face_lu, Champ_Fonc_Face_VDF, Champ_Fonc_P0_VDF, Champ_Fonc_P1_VDF, Champ_Fonc_Q1_VDF, Champ_Fonc_Tabule_P0_VDF, Champ_Ostwald_VDF, Champ_som_lu_VDF, Champ_val_tot_sur_vol_VDF, Correlation_Vec_Sca_VDF, Courant_maille_Champ_Face, Critere_Q_Champ_Face, grad_U_Champ_Face, Reynolds_maille_Champ_Face, Rotationnel_Champ_Face, T_paroi_Champ_P0_VDF, Taux_cisaillement_P0_VDF, Y_plus_Champ_Face, Champ_Fonc_P0_VEF, Champ_Fonc_P1_isoP1Bulle, Champ_Fonc_P1_VEF, Champ_Fonc_P1NC, Champ_Fonc_Q1_VEF, Champ_Fonc_Q1NC, Champ_Fonc_Tabule_P0_VEF, Champ_Ostwald_VEF, Champ_som_lu_VEF, Champ_val_tot_sur_vol_VEF, Correlation_Vec_Sca_VEF, Critere_Q_Champ_P1NC, grad_T_Champ_P1NC, grad_U_Champ_P1NC, h_conv_Champ_P1NC, Rotationnel_Champ_P1NC, Rotationnel_Champ_Q1NC, T_paroi_Champ_P1NC, Taux_cisaillement_P0_VEF, and Y_plus_Champ_P1NC.
self_cast() [1/2]
Champ_Don_base & Champ_Don_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Champ_Don_base & Champ_Don_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Champ_Don_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Champ_base.
Reimplemented in TRUSTChamp_Don_generique< _TYPE_ >, TRUSTChamp_Don_generique< Champ_Don_Type::TXYZ >, TRUSTChamp_Don_generique< Champ_Don_Type::XYZ >, TRUSTChamp_Don_generique< Champ_Don_Type::LU >, Champ_Fonc_reprise_IJK, Estimateur_Aposteriori_P0_VEF, Field_uniform_keps_from_ud, Champ_Fonc_base, Champ_Parametrique, Champ_Fonc_MED, Champ_Fonc_MED_Table_Temps, Champ_Fonc_MED_Tabule, Champ_Fonc_P0_MED, Champ_Fonc_P1_MED, Champ_Fonc_Q1_MED, Champ_Fonc_reprise, Champ_Fonc_Elem_PolyMAC, Champ_Fonc_Elem_PolyMAC_P0_rot, Champ_Fonc_Elem_PolyMAC_P0_TC, Champ_Fonc_Face_PolyMAC, Champ_Fonc_Som_PolyMAC, Champ_Fonc_Tabule_Elem_PolyMAC, grad_Champ_Face_PolyMAC_P0, grad_U_Champ_Face_PolyMAC, Champ_Ostwald, Champ_Don_Face_lu, Champ_Fonc_Face_VDF, Champ_Fonc_P0_VDF, Champ_Fonc_P1_VDF, Champ_Fonc_Q1_VDF, Champ_Fonc_Tabule_P0_VDF, Champ_Ostwald_VDF, Champ_som_lu_VDF, Champ_val_tot_sur_vol_VDF, Correlation_Vec_Sca_VDF, Courant_maille_Champ_Face, Critere_Q_Champ_Face, grad_U_Champ_Face, Reynolds_maille_Champ_Face, Rotationnel_Champ_Face, T_paroi_Champ_P0_VDF, Taux_cisaillement_P0_VDF, Y_plus_Champ_Face, Champ_Fonc_P0_VEF, Champ_Fonc_P1_isoP1Bulle, Champ_Fonc_P1_VEF, Champ_Fonc_P1NC, Champ_Fonc_Q1_VEF, Champ_Fonc_Q1NC, Champ_Fonc_Tabule_P0_VEF, Champ_Ostwald_VEF, Champ_som_lu_VEF, Champ_val_tot_sur_vol_VEF, Correlation_Vec_Sca_VEF, Critere_Q_Champ_P1NC, grad_T_Champ_P1NC, grad_U_Champ_P1NC, h_conv_Champ_P1NC, Rotationnel_Champ_P1NC, Rotationnel_Champ_Q1NC, T_paroi_Champ_P1NC, Taux_cisaillement_P0_VEF, and Y_plus_Champ_P1NC.
References Champ_base::printOn().
Referenced by Champ_Composite::printOn(), and Champ_Parametrique::printOn().
readOn()
Entree & Champ_Don_base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Champ_base.
Reimplemented in Champ_Fonc_reprise_IJK, Estimateur_Aposteriori_P0_VEF, Field_uniform_keps_from_ud, Champ_Fonc_base, Champ_Parametrique, Champ_Fonc_MED, Champ_Fonc_MED_Table_Temps, Champ_Fonc_MED_Tabule, Champ_Fonc_P0_MED, Champ_Fonc_P1_MED, Champ_Fonc_Q1_MED, Champ_Fonc_reprise, Champ_Fonc_Elem_PolyMAC, Champ_Fonc_Elem_PolyMAC_P0_rot, Champ_Fonc_Elem_PolyMAC_P0_TC, Champ_Fonc_Face_PolyMAC, Champ_Fonc_Som_PolyMAC, Champ_Fonc_Tabule_Elem_PolyMAC, grad_Champ_Face_PolyMAC_P0, grad_U_Champ_Face_PolyMAC, Champ_Ostwald, Champ_Don_Face_lu, Champ_Fonc_Face_VDF, Champ_Fonc_P0_VDF, Champ_Fonc_P1_VDF, Champ_Fonc_Q1_VDF, Champ_Fonc_Tabule_P0_VDF, Champ_Ostwald_VDF, Champ_som_lu_VDF, Champ_val_tot_sur_vol_VDF, Correlation_Vec_Sca_VDF, Courant_maille_Champ_Face, Critere_Q_Champ_Face, grad_U_Champ_Face, Reynolds_maille_Champ_Face, Rotationnel_Champ_Face, T_paroi_Champ_P0_VDF, Taux_cisaillement_P0_VDF, Y_plus_Champ_Face, Champ_Fonc_P0_VEF, Champ_Fonc_P1_isoP1Bulle, Champ_Fonc_P1_VEF, Champ_Fonc_P1NC, Champ_Fonc_Q1_VEF, Champ_Fonc_Q1NC, Champ_Fonc_Tabule_P0_VEF, Champ_Ostwald_VEF, Champ_som_lu_VEF, Champ_val_tot_sur_vol_VEF, Correlation_Vec_Sca_VEF, Critere_Q_Champ_P1NC, grad_T_Champ_P1NC, grad_U_Champ_P1NC, h_conv_Champ_P1NC, Rotationnel_Champ_P1NC, Rotationnel_Champ_Q1NC, T_paroi_Champ_P1NC, Taux_cisaillement_P0_VEF, and Y_plus_Champ_P1NC.
References Champ_base::readOn().
mettre_a_jour()
void Champ_Don_base::mettre_a_jour (double t) override virtual
Mise a jour en temps.
Parameters
(double) le temps de mise a jour
Reimplemented from Champ_base.
Reimplemented in Champ_Fonc_base, Champ_Parametrique, TRUSTChamp_Morceaux_generique< _TYPE_ >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC_TXYZ >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC_TABULE >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::UNIFORME >, Champ_Fonc_MED_Tabule, Champ_Ostwald, Champ_Ostwald_VDF, Champ_Ostwald_VEF, Champ_Fonc_Elem_PolyMAC_P0_rot, Champ_Fonc_reprise_IJK, Estimateur_Aposteriori_P0_VEF, TRUSTChamp_Don_generique< _TYPE_ >, TRUSTChamp_Don_generique< Champ_Don_Type::TXYZ >, TRUSTChamp_Don_generique< Champ_Don_Type::XYZ >, TRUSTChamp_Don_generique< Champ_Don_Type::LU >, Champ_Fonc_MED, Champ_Fonc_P0_MED, Champ_Fonc_P1_MED, Champ_Fonc_Q1_MED, Champ_Fonc_reprise, Champ_Fonc_Elem_PolyMAC_P0_TC, Champ_Fonc_Face_PolyMAC, Champ_Fonc_Som_PolyMAC, Champ_Fonc_Tabule_Elem_PolyMAC, grad_Champ_Face_PolyMAC_P0, grad_U_Champ_Face_PolyMAC, Champ_Fonc_Face_VDF, Champ_Fonc_P1_VDF, Champ_Fonc_Q1_VDF, Champ_Fonc_Tabule_P0_VDF, Correlation_Vec_Sca_VDF, Courant_maille_Champ_Face, Critere_Q_Champ_Face, grad_U_Champ_Face, Reynolds_maille_Champ_Face, Rotationnel_Champ_Face, T_paroi_Champ_P0_VDF, Taux_cisaillement_P0_VDF, Y_plus_Champ_Face, Champ_Fonc_P1_isoP1Bulle, Champ_Fonc_P1_VEF, Champ_Fonc_P1NC, Champ_Fonc_Q1_VEF, Champ_Fonc_Q1NC, Champ_Fonc_Tabule_P0_VEF, Correlation_Vec_Sca_VEF, Critere_Q_Champ_P1NC, grad_T_Champ_P1NC, grad_U_Champ_P1NC, h_conv_Champ_P1NC, Rotationnel_Champ_P1NC, Rotationnel_Champ_Q1NC, T_paroi_Champ_P1NC, Taux_cisaillement_P0_VEF, and Y_plus_Champ_P1NC.
References Champ_base::changer_temps(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), and valeurs_.
Referenced by Loi_Etat_TPPI_QC_base::calculer_Cp(), Loi_Etat_TPPI_WC_base::calculer_Cp(), Loi_Etat_GP_base::calculer_lambda(), Loi_Etat_Multi_GP_base::calculer_lambda(), Loi_Etat_base::calculer_mu(), Loi_Etat_Multi_GP_base::calculer_mu(), Fluide_Weakly_Compressible::completer(), initialiser(), Milieu_base::mettre_a_jour(), DP_Impose::mettre_a_jour(), Terme_Source_Constituant::mettre_a_jour(), Terme_Puissance_Thermique::mettre_a_jour(), Source_injection_masse_base::mettre_a_jour(), Navier_Stokes_FT_Disc::mettre_a_jour(), Champ_Parametrique::mettre_a_jour(), Champ_front_MED::mettre_a_jour(), Perte_Charge_Anisotrope_PolyMAC_Face::mettre_a_jour(), Perte_Charge_Circulaire_PolyMAC_Face::mettre_a_jour(), Perte_Charge_Directionnelle_PolyMAC_Face::mettre_a_jour(), Perte_Charge_Isotrope_PolyMAC_Face::mettre_a_jour(), Constituant::mettre_a_jour(), Terme_Source_Acceleration::mettre_a_jour(), Fluide_reel_base::mettre_a_jour(), Milieu_composite::mettre_a_jour(), Champ_Ostwald_VDF::mettre_a_jour(), Perte_Charge_Anisotrope_VDF_Face::mettre_a_jour(), Perte_Charge_Circulaire_VDF_Face::mettre_a_jour(), Perte_Charge_Directionnelle_VDF_Face::mettre_a_jour(), Perte_Charge_Isotrope_VDF_Face::mettre_a_jour(), Champ_Ostwald_VEF::mettre_a_jour(), Perte_Charge_Anisotrope_VEF_P1NC::mettre_a_jour(), Perte_Charge_Circulaire_VEF_P1NC::mettre_a_jour(), Perte_Charge_Directionnelle_VEF_P1NC::mettre_a_jour(), Perte_Charge_Isotrope_VEF_P1NC::mettre_a_jour(), Source_Qdm_EF::mettre_a_jour(), Source_Scalaire_EF::mettre_a_jour(), Terme_Source_Qdm_Face_PolyMAC::mettre_a_jour(), Fluide_Dilatable_base::mettre_a_jour(), Fluide_base::mettre_a_jour(), Fluide_Ostwald::mettre_a_jour(), Terme_Source_Qdm_VDF_Face::mettre_a_jour(), Terme_Source_Qdm_VEF_Face::mettre_a_jour(), Milieu_base::mettre_a_jour_porosite(), resetTime(), Fluide_Dilatable_base::update_pressure_fields(), and Fluide_Weakly_Compressible::update_pressure_fields().
dimensionner()
void Champ_Don_base::dimensionner (int nb_noeuds, int nb_compo)
Fixe le nombre de composantes et le nombre de valeurs nodales.
Parameters
(int) le nombre de noeud par composante du champ (le nombre de dl par composante)
(int) le nombre de composante du champ
References Field_base::fixer_nb_comp(), and fixer_nb_valeurs_nodales().
Referenced by Op_Conv_EF::calculer_dt_stab(), Champ_front_contact_VEF::connectivity_failed(), Champ_Don_Fonc_xyz::readOn(), Champ_Don_lu::readOn(), Champ_Fonc_t::readOn(), champ_init_canal_sinal::readOn(), Champ_Tabule_Temps::readOn(), Champ_Uniforme::readOn(), Champ_Don_Face_lu::readOn(), Fluide_Dilatable_base::set_Cp(), and Tayl_Green::Tayl_Green().
imprime()
int Champ_Don_base::imprime (Sortie & os, int ncomp) const override virtual
NE FAIT RIEN.
EXIT ! A surcharger dans les classes derivees
Implements Champ_base.
Reimplemented in Champ_Fonc_Som_PolyMAC, Champ_Fonc_P0_VDF, Champ_Fonc_Q1_VDF, Champ_Fonc_P1NC, Champ_Fonc_Q1_VEF, Champ_Parametrique, and Champ_Fonc_Face_VDF.
References Process::exit(), and Objet_U::que_suis_je().
Referenced by Champ_Parametrique::imprime().
fixer_nb_valeurs_nodales()
int Champ_Don_base::fixer_nb_valeurs_nodales (int nb_noeuds) override virtual
Fixe le nombre de degres de liberte par composante.
Parameters
(int nb_noeuds) le nombre de degre de liberte par composante
Reimplemented from Champ_base.
Reimplemented in Champ_Fonc_Face_PolyMAC, grad_Champ_Face_PolyMAC_P0, Champ_Fonc_base, Champ_Parametrique, Champ_Ostwald, Champ_Fonc_Face_VDF, Champ_Fonc_P1_isoP1Bulle, Champ_Fonc_P1NC, and Champ_Fonc_Q1NC.
References Field_base::nb_compo_, TRUSTTab< _TYPE_, _SIZE_ >::resize(), and valeurs_.
Referenced by dimensionner(), Modele_rayo_semi_transp::discretiser(), Champ_Parametrique::fixer_nb_valeurs_nodales(), Champ_Composite::readOn(), and Champ_MUSIG::readOn().
reprendre()
int Champ_Don_base::reprendre (Entree &) override virtual
NE FAIT RIEN.
A surcharger dans les classes derivees
Reimplemented from Objet_U.
Reimplemented in Champ_Fonc_base, and Champ_Parametrique.
Referenced by Champ_Parametrique::reprendre().
sauvegarder()
int Champ_Don_base::sauvegarder (Sortie &) const override virtual
NE FAIT RIEN.
A surcharger dans les classes derivees
Reimplemented from Objet_U.
Reimplemented in Champ_Fonc_base, and Champ_Parametrique.
Referenced by Champ_Parametrique::sauvegarder().
resetTime()
void Champ_Don_base::resetTime (double time) override virtual
See comments in Probleme_base_interface_proto::resetTime_impl() Here we update.
Implements Champ_base.
Reimplemented in Champ_Parametrique.
References mettre_a_jour().
Referenced by Champ_Parametrique::resetTime().
valeurs() [1/6]
DoubleTab & Champ_Don_base::valeurs () inline override virtual
Surcharge Champ_base::valeurs() Renvoie le tableau des valeurs.
Returns
(DoubleTab&) le tableau des valeurs du champs
Implements Champ_Proto.
Reimplemented in Champ_Fonc_reprise_IJK, Champ_Parametrique, Champ_Fonc_MED, Champ_Fonc_reprise, and Champ_Input_P0_Composite.
References valeurs_.
Referenced by Champ_Fonc_base::affecter_(), Champ_Fonc_Face_PolyMAC::affecter_(), Champ_Ostwald::affecter_(), Champ_Fonc_Face_VDF::affecter_(), Champ_Fonc_Elem_DG::affecter_(), Champ_Uniforme::affecter_(), Champ_Uniforme_Morceaux::affecter_(), Champ_Fonc_Elem_PolyMAC::affecter_(), Champ_Fonc_base::affecter_compo(), PDF_model::affecter_variable_imposee(), Integrale_tps_produit_champs::ajoute_produit_tensoriel(), Op_Dift_VDF_base::ajoute_terme_pour_axi_turb(), Operateur_Conv_sensibility_VEF::ajouter(), Op_Diff_K_Eps_VEF_Face::ajouter(), Op_Diff_K_Omega_VEF_Face::ajouter(), Op_Dift_Stab_VEF_Face::ajouter(), Op_Dift_standard_VEF_Face::ajouter(), Op_Dift_VEF_Face::ajouter(), Op_Dift_VEF_Face_Q1::ajouter(), Op_Dift_VEF_P1NCP1B_Face::ajouter(), Source_Flottabilite::ajouter(), Source_Trainee::ajouter(), Source_Gravite_PF_VDF::ajouter(), Terme_Boussinesq_Sensibility_VEFPreP1B_Face::ajouter(), Source_Transport_Fluctuation_Temperature_VDF_Elem::ajouter(), Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::ajouter(), Source_Transport_Fluctuation_Temperature_W_VDF_Elem::ajouter(), Source_Transport_Flux_Chaleur_Turbulente_VDF_Face::ajouter(), Source_Transport_K_Realisable_VEF_Face::ajouter(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_VEF_Face::ajouter(), Source_Transport_K_Eps_Bas_Reynolds_VEF_Face::ajouter(), Source_Robin_Scalaire::ajouter(), Source_Qdm_EF::ajouter(), Source_Scalaire_EF::ajouter(), Perte_Charge_PolyMAC::ajouter(), Terme_Source_Qdm_Face_PolyMAC::ajouter(), Perte_Charge_Reguliere_VEF_P1NC::ajouter(), Perte_Charge_VEF::ajouter(), Terme_Boussinesq_VEF_Face::ajouter(), Terme_Boussinesq_VEFPreP1B_Face::ajouter(), Terme_Puissance_Thermique_Echange_Impose_VEF_Face::ajouter(), Terme_Source_Acceleration_VEF_Face::ajouter(), Terme_Source_Th_TdivU_VEF_Face::ajouter(), Source_rayo_semi_transp_VDF_P0_VDF::ajouter(), Source_rayo_semi_transp_VEF_P1NC::ajouter(), Perte_Charge_Reguliere_VDF_Face::ajouter_(), Source_PDF_EF::ajouter_(), Source_Transport_VDF_Elem_base::ajouter_anisotherme(), Source_Transport_VEF_Face_base::ajouter_anisotherme(), Source_Transport_VDF_Elem_base::ajouter_anisotherme_concen(), Source_Transport_VEF_Face_base::ajouter_anisotherme_concen(), Tenseur_Reynolds_Externe_VDF_Face::ajouter_blocs(), Source_Transport_Bas_Reynolds_VDF_Elem_base::ajouter_blocs(), Source_Transport_Realisable_VDF_Elem_base::ajouter_blocs(), Source_Transport_K_Eps_Bas_Reynolds_aniso_therm_concen_VDF_Elem::ajouter_blocs(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_VDF_Elem::ajouter_blocs(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_W_VDF_Elem::ajouter_blocs(), Source_Transport_K_KEps_VDF_Elem::ajouter_blocs(), Terme_Boussinesq_VDF_Face::ajouter_blocs(), Terme_Source_Acceleration_VDF_Face::ajouter_blocs(), Terme_Source_inc_th_VDF_Face::ajouter_blocs(), Terme_Source_Qdm_VDF_Face::ajouter_blocs(), Source_injection_masse_base::ajouter_blocs(), Perte_Charge_PolyMAC::ajouter_blocs(), Terme_Boussinesq_PolyMAC_Face::ajouter_blocs(), Terme_Source_Qdm_Face_PolyMAC_P0P1NC::ajouter_blocs(), Terme_Puissance_Thermique_Echange_Impose_Elem_base::ajouter_blocs(), Perte_Charge_VDF_base::ajouter_blocs(), Op_Grad_EF::ajouter_bord(), Source_Transport_VDF_Elem_base::ajouter_concen(), Source_Transport_VEF_Face_base::ajouter_concen(), Source_Transport_VEF_Face_base::ajouter_keps(), Source_Transport_Realisable_VDF_Elem_base::ajouter_keps_real(), Source_Transport_Realisable_VEF_Face_base::ajouter_keps_real(), Solveur_Masse_base::appliquer(), Masse_DG_base::appliquer_coef(), Masse_PolyMAC_base::appliquer_coef(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_impl(), Eq_rayo_semi_transp_VDF::assembler_matrice(), Eq_rayo_semi_transp_VEF::assembler_matrice(), Assembleur_P_VEFPreP1B::assembler_rho_variable(), Assembleur_P_EF::assembler_rho_variable(), Eval_Gravite_VDF_Face::associer(), Eval_Diff_K_Eps_VDF_var::associer(), Eval_Diff_K_Omega_VDF_var::associer(), Modele_turbulence_hyd_LES_DSGS_VDF::associer(), Eval_Puiss_Th_DG_Elem::associer_champs(), Eval_Puiss_Th_EF::associer_champs(), Eval_Puiss_Th_PolyMAC_Elem::associer_champs(), Eval_Source_C_PolyMAC_Elem::associer_champs(), Eval_Dirac_VDF_Elem::associer_champs(), Eval_Puiss_Neutr_VDF_Elem::associer_champs(), Eval_Puiss_Th_VDF_Elem::associer_champs(), Eval_Source_C_VDF_Elem::associer_champs(), Eval_Dirac_VEF_Face::associer_champs(), Eval_Puiss_Th_VEF_Face::associer_champs(), Eval_Source_C_VEF_Face::associer_champs(), Eval_Dift_VDF::associer_diff_turb(), Source_PDF_EF::associer_pb(), Eval_Puiss_Th_QC_EF::associer_puissance(), Eval_Puiss_Th_QC_VEF_Face::associer_puissance(), Eval_Puiss_Th_QC_VDF_Elem::associer_puissance(), grad_Champ_Face_PolyMAC_P0::calc_gradfve(), Champ_front_contact_VEF::calcul_coeff_amort(), Modele_Jones_Launder_VDF::Calcul_D(), Modele_Jones_Launder_VEF::Calcul_D(), Modele_Launder_Sharma_VEF::Calcul_D(), Modele_Jones_Launder_VDF::Calcul_D_BiK(), Modele_Jones_Launder_VEF::Calcul_D_BiK(), Modele_Launder_Sharma_VEF::Calcul_D_BiK(), Modele_Jones_Launder_VDF::Calcul_E(), Modele_Jones_Launder_VEF::Calcul_E(), Modele_Launder_Sharma_VEF::Calcul_E(), Modele_EASM_Baglietto_VEF::Calcul_F1(), Modele_Lam_Bremhorst_VEF::Calcul_F1(), Modele_EASM_Baglietto_VEF::Calcul_F1_BiK(), Modele_Lam_Bremhorst_VEF::Calcul_F1_BiK(), Modele_Jones_Launder_VDF::Calcul_Fmu(), Modele_Launder_Sharma_VDF::Calcul_Fmu(), Modele_Jones_Launder_VEF::Calcul_Fmu(), Modele_Lam_Bremhorst_VEF::Calcul_Fmu(), Modele_Launder_Sharma_VEF::Calcul_Fmu(), Modele_EASM_Baglietto_VEF::Calcul_Fmu(), Modele_Jones_Launder_VDF::Calcul_Fmu_BiK(), Modele_Launder_Sharma_VDF::Calcul_Fmu_BiK(), Modele_EASM_Baglietto_VEF::Calcul_Fmu_BiK(), Modele_Jones_Launder_VEF::Calcul_Fmu_BiK(), Modele_Lam_Bremhorst_VEF::Calcul_Fmu_BiK(), Modele_Launder_Sharma_VEF::Calcul_Fmu_BiK(), Champ_front_contact_VEF::calcul_grads_locaux(), Champ_P1NC::calcul_h_conv(), Traitement_particulier_NS_THI_VEF::calcul_nu_t(), Traitement_particulier_NS_canal::calcul_reynolds_tau(), Champ_Q1_EF::calcul_y_plus(), Champ_P1NC::calcul_y_plus(), Champ_Face_VDF::calcul_y_plus(), Champ_P1NC::calcul_y_plus_diphasique(), Champ_Face_VDF::calcul_y_plus_diphasique(), Milieu_base::calculate_face_hydr_diam(), Milieu_base::calculate_face_porosity(), Milieu_base::calculer_alpha(), Loi_Etat_base::calculer_alpha(), Loi_Etat_GP_base::calculer_alpha(), Loi_Etat_Multi_GP_base::calculer_alpha(), Source_Con_Phase_field::calculer_champ_fonc_c(), Loi_Etat_Multi_GP_base::calculer_Cp(), Loi_Etat_TPPI_QC_base::calculer_Cp(), Loi_Etat_TPPI_WC_base::calculer_Cp(), Diffu_lm::calculer_D_local(), Modele_turbulence_scal_Schmidt::calculer_diffusion_turbulente(), Modele_turbulence_scal_LES_dyn_VDF::calculer_diffusivite_turbulente(), Modele_turbulence_scal_Fluctuation_Temperature::calculer_diffusivite_turbulente(), Modele_turbulence_scal_Fluctuation_Temperature_W::calculer_diffusivite_turbulente(), Modele_turbulence_scal_Prandtl::calculer_diffusivite_turbulente(), Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re::calculer_diffusivite_turbulente(), Source_Con_Phase_field::calculer_div_alpha_rho_gradC(), Op_Diff_K_Eps_Bas_Re_VDF_var_Elem::calculer_dt_stab(), Op_Diff_DG_base::calculer_dt_stab(), Op_Conv_EF::calculer_dt_stab(), Op_Diff_PolyMAC_base::calculer_dt_stab(), Op_Diff_VEF_base::calculer_dt_stab(), Op_Dift_VEF_base::calculer_dt_stab(), Op_Dift_VDF_Face_base::calculer_dt_stab(), Op_Dift_VDF_Elem_base::calculer_dt_stab_elem(), Op_Dift_VDF_Elem_base::calculer_dt_stab_elem_axi(), Op_Dift_VDF_Elem_base::calculer_dt_stab_elem_var_axi(), Op_Dift_VEF_base::calculer_dt_stab_P1NCP1B(), Navier_Stokes_FTD_IJK::calculer_dv(), Traitement_particulier_NS_EC::calculer_Ec(), Modele_turbulence_hyd_LES_VDF::calculer_energie_cinetique_turb(), Modele_turbulence_hyd_LES_base::calculer_energie_cinetique_turb(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calculer_energie_cinetique_turb(), Modele_turbulence_hyd_Longueur_Melange_VEF::calculer_f_amortissement(), Flux_radiatif_VDF::calculer_flux_radiatif(), Flux_radiatif_VEF::calculer_flux_radiatif(), Convection_Diffusion_Temperature_FT_Disc::calculer_grad_t(), Modele_turbulence_scal_LES_dyn_VDF::calculer_grad_teta(), Echange_contact_Correlation_VEF::calculer_h_solide(), Echange_contact_Correlation_VDF::calculer_h_solide(), Turbulence_paroi_base::calculer_hyd(), ParoiVDF_TBLE_LRM::calculer_hyd(), Paroi_std_hyd_VEF::calculer_hyd(), Paroi_negligeable_VDF::calculer_hyd(), Paroi_negligeable_VEF::calculer_hyd(), Paroi_std_hyd_VDF_diphasique::calculer_hyd(), Paroi_std_hyd_VEF_diphasique::calculer_hyd(), Paroi_loi_WW_hyd_EF::calculer_hyd(), Paroi_std_hyd_EF::calculer_hyd(), Paroi_2couches_VDF::calculer_hyd(), Paroi_loi_Ciofalo_hyd_VDF::calculer_hyd(), Paroi_loi_WW_hyd_VDF::calculer_hyd(), Paroi_loi_WW_hyd_VEF::calculer_hyd(), Paroi_std_hyd_VDF::calculer_hyd(), Paroi_UTAU_IMP_VDF::calculer_hyd(), ParoiVDF_TBLE::calculer_hyd(), ParoiVEF_TBLE::calculer_hyd(), Paroi_std_hyd_VDF::calculer_hyd_BiK(), Paroi_UTAU_IMP_VDF::calculer_hyd_BiK(), ParoiVDF_TBLE::calculer_hyd_BiK(), ParoiVDF_TBLE_LRM::calculer_hyd_BiK(), Paroi_std_hyd_VEF::calculer_hyd_BiK(), ParoiVEF_TBLE::calculer_hyd_BiK(), Terme_Source_Acceleration::calculer_la_source(), Loi_Etat_base::calculer_lambda(), Loi_Etat_GP_base::calculer_lambda(), Loi_Etat_GR_base::calculer_lambda(), Loi_Etat_Multi_GP_base::calculer_lambda(), Loi_Etat_Multi_GP_WC::calculer_masse_molaire(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calculer_model_coefficient(), Traitement_particulier_NS_canal_VDF::calculer_moyenne_spatiale_nut(), Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_nut(), Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_nut(), Traitement_particulier_NS_canal_VDF::calculer_moyenne_spatiale_vitesse_rho_mu(), Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_vitesse_rho_mu(), Paroi_std_hyd_VDF::calculer_moyennes_parois(), Convection_Diffusion_Temperature_FT_Disc::calculer_mpoint(), Navier_Stokes_phase_field::calculer_mu(), Loi_Etat_Binaire_GP_base::calculer_mu_sur_Sc(), Loi_Etat_Multi_GP_QC::calculer_mu_sur_Sc(), Loi_Etat_Multi_GP_WC::calculer_mu_sur_Sc(), Loi_Etat_base::calculer_nu(), Fluide_base::calculer_nu(), Loi_Etat_Binaire_GP_base::calculer_nu_sur_Sc(), Loi_Etat_Multi_GP_WC::calculer_nu_sur_Sc(), Navier_Stokes_phase_field::calculer_pas_de_temps(), Op_Dift_VEF_base::calculer_pour_post(), Navier_Stokes_std::calculer_pression_hydrostatique(), Fluide_Dilatable_base::calculer_pression_tot(), Transport_Marqueur_FT::calculer_proprietes_fluide_pos_particules(), Navier_Stokes_phase_field::calculer_rho(), Convection_Diffusion_Temperature::calculer_rho_cp_T(), Paroi_std_scal_hyd_EF::calculer_scal(), Loi_Paroi_Nu_Impose_VDF::calculer_scal(), Paroi_loi_WW_scal_VDF::calculer_scal(), Paroi_ODVM_scal_VDF::calculer_scal(), Paroi_std_scal_hyd_VDF::calculer_scal(), Paroi_TBLE_scal_VDF::calculer_scal(), Loi_Paroi_Nu_Impose_VEF::calculer_scal(), Paroi_loi_WW_scal_VEF::calculer_scal(), Paroi_scal_analytique_VEF::calculer_scal(), Paroi_std_scal_hyd_VEF::calculer_scal(), ParoiVEF_TBLE_scal::calculer_scal(), Loi_Etat_Multi_GP_WC::calculer_tab_Cp(), Neumann_paroi_rayo_semi_transp_VDF::calculer_temperature_bord(), Calcul_Production_K_VEF::calculer_terme_destruction_K_gen(), Paroi_flux_impose_Rayo_transp::calculer_Teta_i_VDF(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_W_VDF_Elem::calculer_u_teta_W(), Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::calculer_u_teta_W(), Source_Transport_Fluctuation_Temperature_W_VDF_Elem::calculer_u_teta_W(), Op_Correlation::calculer_valeurs(), Source_PDF_EF::calculer_variable_imposee_elem_fluid(), Source_PDF_EF::calculer_variable_imposee_hybrid(), Source_PDF_EF::calculer_variable_imposee_mean_grad(), Modele_turbulence_hyd_LES_axi_VDF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_DSGS_VDF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_VDF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_1elt_VEF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_Fst_VEF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_VEF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_combinaison::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_Smago_VDF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_Wale_VDF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_Longueur_Melange_VDF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_Smago_VEF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_Wale_VEF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_Longueur_Melange_VEF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_K_Eps::calculer_viscosite_turbulente(), Modele_turbulence_hyd_K_Eps_2_Couches::calculer_viscosite_turbulente(), Modele_turbulence_hyd_K_Eps_Bas_Reynolds::calculer_viscosite_turbulente(), Modele_turbulence_hyd_K_Eps_Bicephale::calculer_viscosite_turbulente(), Modele_turbulence_hyd_K_Eps_Realisable::calculer_viscosite_turbulente(), Modele_turbulence_hyd_K_Eps_Realisable_Bicephale::calculer_viscosite_turbulente(), Modele_turbulence_hyd_K_Omega::calculer_viscosite_turbulente(), Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl(), Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl_u_star(), Fluide_Diphasique::chaleur_latente(), Echange_global_impose::champ_exterieur(), Echange_couplage_thermique::champ_exterieur(), Triple_Line_Model_FT_Disc::completer(), Navier_Stokes_Fluide_Dilatable_base::completer(), Sortie_libre_pression_imposee_QC::completer(), Sortie_libre_pression_imposee::completer(), Sortie_libre_pression_moyenne_imposee::completer(), Navier_Stokes_std::completer(), Fluide_Weakly_Compressible::completer(), Navier_Stokes_FT_Disc::compute_boussinesq_additional_gravity(), Source_PDF_EF::compute_coeff_elem(), Source_PDF_EF::compute_coeff_matrice(), Navier_Stokes_FTD_IJK::compute_correction_for_momentum_balance(), Source_Transport_K_Omega_VEF_Face::compute_cross_diffusion(), Post_Processing_Hydrodynamic_Forces::compute_heat_transfer(), Source_PDF_EF::compute_indicateur_nodal_champ_aire(), Source_WC_Chaleur_VEF::compute_interpolate_gradP(), Paroi_std_hyd_VDF::compute_law_komega(), Paroi_scal_hyd_base_EF::compute_nusselt(), Paroi_scal_hyd_base_VDF::compute_nusselt(), Paroi_scal_hyd_base_VEF::compute_nusselt(), Source_PDF_EF::compute_variable_imposee_projete(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_vinf_Stokes(), Interpolation_IBM_elem_fluid::computeFluidElems(), Interpolation_IBM_mean_gradient_proto::computeSommetsVoisins(), Champ_front_contact_VEF::connectivity_failed(), Op_Diff_K_Eps_VEF_Face::contribuer_a_avec(), Op_Diff_K_Omega_VEF_Face::contribuer_a_avec(), Source_Transport_Realisable_VEF_Face_base::contribuer_a_avec(), Source_PDF_EF::contribuer_a_avec(), Perte_Charge_PolyMAC::contribuer_a_avec(), Op_Dift_Stab_VEF_Face::contribuer_a_avec(), Op_Dift_VEF_Face::contribuer_a_avec(), Op_Dift_VEF_Face_Q1::contribuer_a_avec(), Perte_Charge_Reguliere_VEF_P1NC::contribuer_a_avec(), Perte_Charge_VEF::contribuer_a_avec(), Terme_Puissance_Thermique_Echange_Impose_VEF_Face::contribuer_a_avec(), Op_Dift_VEF_Face::contribuer_au_second_membre(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::controler_grandeurs_turbulentes(), Source_PDF_EF::correct_incr_pressure(), Convection_Diffusion_Temperature_FT_Disc::correct_mpoint(), Source_PDF_EF::correct_pressure(), TRUSTProblem_Concentration_Gen< _DERIVED_TYPE_, _EQUATION_TYPE_, _MEDIUM_TYPE_ >::create_constituants_echaines(), Fluide_Dilatable_base::creer_champs_non_lus(), Fluide_base::creer_nu(), Modele_turbulence_hyd_LES_selectif_mod_VDF::cutoff(), Modele_turbulence_hyd_LES_selectif_VDF::cutoff(), Modele_turbulence_hyd_LES_1elt_selectif_mod_VEF::cutoff(), Modele_turbulence_hyd_LES_Fst_sel_VEF::cutoff(), Champ_Fonc_base::data_a_sauvegarder(), Op_Correlation::data_a_sauvegarder(), Op_Ecart_type::data_a_sauvegarder(), Op_Moyenne::data_a_sauvegarder(), Transport_Interfaces_FT_Disc::deplacer_maillage_ft_v_fluide(), Convection_Diffusion_Temperature_FT_Disc::derivee_en_temps_inco(), Navier_Stokes_phase_field::derivee_en_temps_inco(), Navier_Stokes_FT_Disc::derivee_en_temps_inco(), Milieu_base::diametre_hydraulique_elem(), Discret_Thyd::diametre_hydraulique_face(), Milieu_base::discretiser(), Fluide_base::discretiser(), Solide::discretiser(), Convection_Diffusion_Temperature::ecrire_fichier_pena_th(), Champ_val_tot_sur_vol_base::evaluer(), Flux_radiatif_VDF::evaluer_cl_rayonnement(), Flux_radiatif_VEF::evaluer_cl_rayonnement(), Transport_Marqueur_FT::get_champ(), Source_PDF_EF::get_champ(), Paroi_hyd_base_EF::get_champ(), Turbulence_paroi_base::get_champ(), Moyenne_volumique::get_champ(), Champ_Generique_Correlation::get_champ(), Champ_Generique_Ecart_Type::get_champ(), Champ_Generique_Moyenne::get_champ(), Champ_Generique_Reduction_0D::get_champ(), Champ_Generique_Transformation::get_champ(), Champ_Generique_Interpolation::get_champ_with_calculer_champ_post(), Fluide_Diphasique_IJK::get_gravite_norm(), Convection_Diffusion_Temperature_FT_Disc::get_mpoint(), Navier_Stokes_FT_Disc::get_set_pressure_field_Stokes_th(), Navier_Stokes_FT_Disc::get_set_velocity_field_Stokes_th(), Interface_base::get_sigma_tab(), Convection_Diffusion_Temperature::get_time_factor(), Saturation_base::get_Tsat_tab(), Transport_Interfaces_FT_Disc::get_update_distance_interface(), Transport_Interfaces_FT_Disc::get_update_distance_interface_faces(), Transport_Interfaces_FT_Disc::get_update_normale_interface(), Solide::get_user_champ(), Sortie_libre_Gradient_Pression_impose::grad_P_imp(), Sortie_libre_Gradient_Pression_libre_VEF::Grad_P_lib_VEF(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::Grad_P_lib_VEFPreP1B(), PolyMAC_P0_discretisation::grad_u(), Domaine_Cl_EF::imposer_symetrie(), Domaine_Cl_EF::imposer_symetrie_matrice_secmem(), Domaine_Cl_EF::imposer_symetrie_partiellement(), Source_PDF_EF::impr(), Champ_Fonc_P1_EF::imprime(), Champ_Fonc_Q1_EF::imprime(), Champ_Fonc_Som_PolyMAC::imprime(), Champ_Fonc_Q1_VDF::imprime(), Champ_Fonc_Q1_VEF::imprime(), Loi_horaire::imprimer(), Modele_turbulence_hyd_0_eq_base::imprimer(), Loi_Paroi_Nu_Impose_VDF::imprimer_nusselt(), Loi_Paroi_Nu_Impose_VEF::imprimer_nusselt(), ParoiVDF_TBLE::init_lois_paroi(), Paroi_ODVM_scal_VDF::init_lois_paroi(), Paroi_TBLE_scal_VDF::init_lois_paroi(), ParoiVEF_TBLE::init_lois_paroi(), Champ_Input_P0_Composite::initial_values(), Loi_Etat_GR_base::initialiser(), Fluide_Dilatable_base::initialiser(), Fluide_base::initialiser(), Fluide_reel_base::initialiser(), MuLambda_TBLE_Cte::initialiser(), MuLambda_TBLE_Fcts_T::initialiser(), Op_Correlation::initialiser(), Op_Ecart_type::initialiser(), Op_Moyenne::initialiser(), Fluide_Dilatable_base::initialiser_radiatives(), Loi_Etat_rhoT_GP_QC::initialiser_rho(), Ecrire_Champ_MED::interpreter(), Modele_turbulence_hyd_base::limiter_viscosite_turbulente(), Champ_Fonc_MED_Table_Temps::lire(), Terme_Source_Acceleration::lire_data(), Modele_turbulence_hyd_base::lire_distance_paroi(), Modele_turbulence_hyd_Longueur_Melange_VEF::lire_distance_paroi(), Modele_Lam_Bremhorst_VEF::lire_distance_paroi(), Terme_Puissance_Thermique::lire_donnees(), PDF_model::lire_motcle_non_standard(), Champ_Fonc_t::me_calculer(), Champ_Tabule_Temps::me_calculer(), Champ_Uniforme_Morceaux_Tabule_Temps::me_calculer(), Champ_Fonc_Elem_PolyMAC_P0_TC::me_calculer(), Champ_Ostwald_VDF::me_calculer(), Champ_Ostwald_VEF::me_calculer(), grad_Champ_Face_PolyMAC_P0::me_calculer(), grad_U_Champ_Face_PolyMAC::me_calculer(), grad_U_Champ_Face::me_calculer(), T_paroi_Champ_P0_VDF::me_calculer(), grad_U_Champ_P1NC::me_calculer(), T_paroi_Champ_P1NC::me_calculer(), Rotationnel_Champ_Q1_EF::me_calculer(), Y_plus_Champ_Q1::me_calculer(), Critere_Q_Champ_Face::me_calculer(), Rotationnel_Champ_Face::me_calculer(), Y_plus_Champ_Face::me_calculer(), Critere_Q_Champ_P1NC::me_calculer(), grad_T_Champ_P1NC::me_calculer(), h_conv_Champ_P1NC::me_calculer(), Rotationnel_Champ_P1NC::me_calculer(), Rotationnel_Champ_Q1NC::me_calculer(), Y_plus_Champ_P1NC::me_calculer(), Champ_Fonc_Elem_PolyMAC_P0_rot::me_calculer_2D(), Champ_Fonc_Elem_PolyMAC_P0_rot::me_calculer_3D(), Discretisation_base::mesh_numbering(), Source_Qdm_VDF_Phase_field::methode_1(), Source_Qdm_VDF_Phase_field::methode_2(), Source_Qdm_VDF_Phase_field::methode_3(), Source_Qdm_VDF_Phase_field::methode_4(), Navier_Stokes_FT_Disc::mettre_a_jour(), Transport_Interfaces_FT_Disc::mettre_a_jour(), Source_Transport_Eps_Realisable_VEF_Face::mettre_a_jour(), Source_Transport_K_Realisable_VEF_Face::mettre_a_jour(), Source_Transport_K_Eps_Realisable_VEF_Face::mettre_a_jour(), Champ_Fonc_Tabule_Morceaux::mettre_a_jour(), Champ_Fonc_Tabule_Morceaux_Interp::mettre_a_jour(), Champ_Fonc_base::mettre_a_jour(), Op_Moyenne::mettre_a_jour(), Portance_interfaciale_PolyMAC_P0::mettre_a_jour(), Aire_interfaciale::mettre_a_jour(), QDM_Multiphase::mettre_a_jour(), Fluide_reel_base::mettre_a_jour(), Source_Neutronique::mettre_a_jour(), Interface_base::mettre_a_jour(), Navier_Stokes_phase_field::mettre_a_jour(), Estimateur_Aposteriori_P0_VEF::mettre_a_jour(), Tenseur_Reynolds_Externe_VDF_Face::mettre_a_jour(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::mettre_a_jour(), Modele_turbulence_scal_LES_dyn_VDF::mettre_a_jour(), Modele_turbulence_hyd_combinaison::mettre_a_jour(), Modele_turbulence_scal_Fluctuation_Temperature_W::mettre_a_jour(), Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re::mettre_a_jour(), Modele_turbulence_hyd_K_Eps::mettre_a_jour(), Modele_turbulence_hyd_K_Eps_Bas_Reynolds::mettre_a_jour(), Modele_turbulence_hyd_K_Eps_Bicephale::mettre_a_jour(), Modele_turbulence_hyd_K_Eps_Realisable::mettre_a_jour(), Modele_turbulence_hyd_K_Eps_Realisable_Bicephale::mettre_a_jour(), Modele_turbulence_hyd_K_Omega::mettre_a_jour(), Champ_Fonc_Tabule_P0_EF::mettre_a_jour(), Champ_Fonc_Interp::mettre_a_jour(), Champ_Fonc_Tabule_Elem_PolyMAC::mettre_a_jour(), Fluide_base::mettre_a_jour(), Terme_Puissance_Thermique_Echange_Impose_Elem_base::mettre_a_jour(), Saturation_base::mettre_a_jour(), Modele_turbulence_hyd_0_eq_base::mettre_a_jour(), Modele_turbulence_scal_Prandtl::mettre_a_jour(), Modele_turbulence_scal_Schmidt::mettre_a_jour(), Champ_Fonc_Tabule_P0_VDF::mettre_a_jour(), Correlation_Vec_Sca_VDF::mettre_a_jour(), Courant_maille_Champ_Face::mettre_a_jour(), Reynolds_maille_Champ_Face::mettre_a_jour(), Taux_cisaillement_P0_VDF::mettre_a_jour(), PlaqThVDF::mettre_a_jour(), Champ_Fonc_Tabule_P0_VEF::mettre_a_jour(), Correlation_Vec_Sca_VEF::mettre_a_jour(), Taux_cisaillement_P0_VEF::mettre_a_jour(), Terme_Puissance_Thermique_Echange_Impose_VEF_Face::mettre_a_jour(), Convection_Diffusion_Concentration_FT_Disc::mettre_a_jour_chimie(), Convection_Diffusion_Concentration_Turbulent_FT_Disc::mettre_a_jour_chimie(), Integrale_tps_Champ::mettre_a_jour_integrale(), Milieu_composite::mettre_a_jour_tabs(), Domaine_Cl_EF::modifie_gradient(), Iterateur_PolyMAC_Elem< _TYPE_ >::modifier_flux(), Op_VEF_Face::modifier_flux(), Eq_rayo_semi_transp_VDF::modifier_matrice(), Transport_Interfaces_FT_Disc::modifier_vpoint_pour_imposer_vit(), Champ_Fonc_P0_base::moyenne(), Champ_Parametrique::nb_valeurs_nodales(), Milieu_base::porosite_elem(), Loi_horaire::position(), Source_Con_Phase_field::premier_demi_dt(), Navier_Stokes_FT_Disc::preparer_calcul(), Navier_Stokes_phase_field::preparer_calcul(), Modele_turbulence_scal_Fluctuation_Temperature_W::preparer_calcul(), Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re::preparer_calcul(), Modele_turbulence_hyd_K_Eps::preparer_calcul(), Modele_turbulence_hyd_K_Eps_2_Couches::preparer_calcul(), Modele_turbulence_hyd_K_Eps_Bicephale::preparer_calcul(), Modele_turbulence_hyd_K_Omega::preparer_calcul(), Field_uniform_keps_from_ud::printOn(), Champ_Fonc_Fonction_txyz_Morceaux::printOn(), Champ_Fonc_Morceaux::printOn(), Champ_Fonc_Tabule_Morceaux::printOn(), Champ_Uniforme::printOn(), Champ_Uniforme_Morceaux::printOn(), Champ_Don_Face_lu::printOn(), Champ_Ostwald_VDF::printOn(), Champ_Ostwald_VEF::printOn(), Navier_Stokes_FTD_IJK::projeter(), Terme_Puissance_Thermique::puissance_thermique(), Source_injection_masse_base::readOn(), Field_uniform_keps_from_ud::readOn(), Champ_Input_P0_Composite::readOn(), Ch_input_uniforme::readOn(), Champ_Don_Fonc_xyz::readOn(), Champ_Don_lu::readOn(), Champ_Uniforme::readOn(), Champ_Uniforme_Morceaux::readOn(), Champ_Fonc_MED::readOn(), Loi_Etat_Multi_GP_WC::readOn(), Diametre_bulles_champ::readOn(), Diametre_bulles_constant::readOn(), Diametre_bulles_musig::readOn(), Gravite_Multiphase::readOn(), Champ_Don_Face_lu::readOn(), AssembleurPVDF_PF::remplir(), Assembleur_P_VDF::remplir(), Loi_Etat_GP_base::remplir_T(), Loi_Etat_GR_base::remplir_T(), Domaine_Cl_EF::remplir_type_elem_Cl(), Navier_Stokes_FT_Disc::reprendre(), Champ_Fonc_base::reprendre(), VDF_discretisation::residu(), VEF_discretisation::residu(), PolyMAC_P0_discretisation::residu(), PolyMAC_P0P1NC_discretisation::residu(), Eq_rayo_semi_transp_VDF::resoudre(), Eq_rayo_semi_transp_VEF::resoudre(), Navier_Stokes_phase_field::rho_aux_faces(), Source_PDF_EF::rotate_imposed_velocity(), Champ_Fonc_base::sauvegarder(), Discret_Thyd::section_passage(), Fluide_Dilatable_base::set_Cp(), Equation_base::set_residuals(), Ch_input_uniforme::setValue(), Fluide_Diphasique::sigma(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::stabilise_moyenne_6_points(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::stabilise_moyenne_euler_lagrange(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::stabilise_moyenne_plans_paralleles(), Fluide_Dilatable_base::temperature(), Loi_Etat_base::temperature(), Navier_Stokes_FTD_IJK::terme_source_gravite(), Champ_Fonc_P0_base::trace(), Champ_Fonc_Face_VDF::trace(), Champ_Fonc_P1_isoP1Bulle::trace(), Champ_Fonc_P1NC::trace(), Champ_Fonc_Q1NC::trace(), Champ_Fonc_Interp::update_fields(), grad_Champ_Face_PolyMAC_P0::update_ge(), Op_Diff_DG_base::update_nu(), Op_Diff_PolyMAC_base::update_nu(), Fluide_Weakly_Compressible::update_pressure_fields(), Milieu_base::update_rho_cp(), Fluide_Dilatable_base::update_rho_cp(), grad_Champ_Face_PolyMAC_P0::update_tab_grad(), Navier_Stokes_std::update_y_plus(), Champ_Fonc_P0_base::valeur_au_bord(), TRUSTChamp_Divers_generique< _TYPE_ >::valeur_aux(), TRUSTChamp_Divers_generique< _TYPE_ >::valeur_aux_elems(), Champ_som_lu::valeur_aux_elems(), Champ_som_lu_VEF::valeur_aux_elems(), Champ_som_lu::valeur_aux_elems_compo(), Champ_som_lu_VEF::valeur_aux_elems_compo(), Champ_Generique_Ecart_Type::valeurs(), Op_Moyenne::valeurs(), Champ_Fonc_Tabule::valeurs(), Champ_Input_P0_Composite::valeurs(), Champ_Parametrique::valeurs(), Champ_Fonc_MED::valeurs(), Op_Correlation::valeurs_ab(), Op_Ecart_type::valeurs_carre(), Champ_Generique_Ecart_Type::valeurs_carre(), Source_PDF_EF::verif_ajouter_contrib(), IJK_Thermals::verifie_milieu(), Fluide_Diphasique::verifier_coherence_champs(), Fluide_Dilatable_base::verifier_coherence_champs(), Fluide_base::verifier_coherence_champs(), Solide::verifier_coherence_champs(), Loi_horaire::vitesse(), Discretisation_base::volume_maille(), VDF_discretisation::y_plus(), and PolyMAC_P0P1NC_discretisation::y_plus().
valeurs() [2/6]
const DoubleTab & Champ_Don_base::valeurs () const inline override virtual
Implements Champ_Proto.
Reimplemented in Champ_Fonc_reprise_IJK, Champ_Parametrique, Champ_Fonc_MED, Champ_Fonc_reprise, and Champ_Input_P0_Composite.
References valeurs_.
affecter_compo()
Champ_base & Champ_Don_base::affecter_compo (const Champ_base & , int) override virtual
Provoque une erreur ! A surcharger par les classes derivees ! non virtuelle pure par commoditees de developpement !
Implements Champ_base.
Reimplemented in Champ_Fonc_base, and Champ_Parametrique.
Referenced by Champ_Parametrique::affecter_compo().
initialiser()
int Champ_Don_base::initialiser (const double un_temps) virtual
NE FAIT RIEN.
A surcharger dans les classes derivees. Provoque l'initialisation du champ si necessaire
Reimplemented in Champ_Input_P0_Composite, Champ_Fonc_Tabule_P0_EF, Champ_Fonc_Tabule_Morceaux, Champ_Fonc_Tabule_Morceaux_Interp, Champ_Parametrique, TRUSTChamp_Morceaux_generique< _TYPE_ >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC_TXYZ >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC_TABULE >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::UNIFORME >, Champ_Fonc_Tabule_Elem_PolyMAC, Champ_Ostwald, Champ_Fonc_Tabule_P0_VDF, Champ_Ostwald_VDF, Champ_Fonc_Tabule_P0_VEF, Champ_Ostwald_VEF, Champ_Fonc_Tabule, and Champ_Fonc_Interp.
References mettre_a_jour().
Referenced by Champ_Input_P0_Composite::initialiser(), Milieu_base::initialiser(), Fluide_Dilatable_base::initialiser(), Constituant::initialiser(), Fluide_base::initialiser(), Fluide_reel_base::initialiser(), Champ_Fonc_Tabule::initialiser(), Terme_Source_Qdm_Face_PolyMAC_P0P1NC::initialiser(), Terme_Puissance_Thermique_Echange_Impose_Elem_base::initialiser(), Terme_Source_Qdm_VDF_Face::initialiser(), Terme_Puissance_Thermique_Echange_Impose_VEF_Face::initialiser(), Champ_Fonc_Interp::initialiser(), Milieu_base::initialiser_porosite(), Fluide_Dilatable_base::initialiser_radiatives(), and Navier_Stokes_phase_field::preparer_calcul().
set_instationnaire()
virtual void Champ_Don_base::set_instationnaire (bool flag) inline virtual
Referenced by Champ_Fonc_MED_Tabule::mettre_a_jour(), and Champ_Fonc_Fonction_txyz::readOn().
instationnaire()
virtual bool Champ_Don_base::instationnaire () const inline virtual
Reimplemented in Champ_Parametrique, and Champ_Fonc_MED_Table_Temps.
Referenced by Champ_Parametrique::instationnaire().
nb_valeurs_nodales()
int Champ_Don_base::nb_valeurs_nodales () const inline override virtual
Renvoie le nombre de degre de liberte par composante: le nombre de noeuds.
Reimplemented from Champ_base.
Reimplemented in Champ_Parametrique.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), and valeurs_.
Referenced by Champ_Ostwald_VDF::calculer_mu(), Champ_Ostwald_VEF::calculer_mu(), Champ_Composite::fill_valeurs_composite(), Champ_Ostwald_VEF::init_mu(), Fluide_base::initialiser(), Fluide_Dilatable_base::initialiser_radiatives(), Fluide_base::mettre_a_jour(), and Champ_Fonc_reprise_IJK::reprendre_IJK().
operator DoubleTab &()
Champ_Don_base::operator DoubleTab & () delete
operator const DoubleTab &()
Champ_Don_base::operator const DoubleTab & () const delete
affecter_()
Champ_base & Champ_Don_base::affecter_ (const Champ_base &) override protected virtual
Provoque une erreur ! A surcharger par les classes derivees ! non virtuelle pure par commoditees de developpement !
Implements Champ_base.
Reimplemented in Champ_Fonc_base, Champ_Fonc_Face_PolyMAC, Champ_Ostwald, Champ_Fonc_Face_VDF, Champ_Parametrique, TRUSTChamp_Don_generique< _TYPE_ >, TRUSTChamp_Don_generique< Champ_Don_Type::TXYZ >, TRUSTChamp_Don_generique< Champ_Don_Type::XYZ >, TRUSTChamp_Don_generique< Champ_Don_Type::LU >, TRUSTChamp_Morceaux_generique< _TYPE_ >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC_TXYZ >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC_TABULE >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::UNIFORME >, and Champ_Fonc_Elem_PolyMAC.
References Objet_U::que_suis_je().
valeurs() [3/6]
virtual DoubleTab & Champ_Proto::valeurs () virtual
Implements Champ_Proto.
valeurs() [4/6]
virtual const DoubleTab & Champ_Proto::valeurs () const virtual
Implements Champ_Proto.
valeurs() [5/6]
virtual DoubleTab & Champ_Proto::valeurs (double temps) inline virtual
Reimplemented from Champ_Proto.
valeurs() [6/6]
virtual const DoubleTab & Champ_Proto::valeurs (double temps) const inline virtual
Reimplemented from Champ_Proto.
Member Data Documentation
info_obj
const Type_info Champ_Don_base::info_obj static
valeurs_
DoubleTab Champ_Don_base::valeurs_ protected
Referenced by Champ_Fonc_P1_DG::affecter_(), Champ_Uniforme_Morceaux::affecter_(), Champ_Fonc_base::creer_tableau_distribue(), Champ_val_tot_sur_vol_base::evaluer(), Champ_Composite::fill_valeurs_composite(), fixer_nb_valeurs_nodales(), Champ_Ostwald::fixer_nb_valeurs_nodales(), Champ_Fonc_Interp::initialiser(), mettre_a_jour(), nb_valeurs_nodales(), Champ_input_P0::readOn(), Champ_Fonc_Tabule_Morceaux::readOn(), Champ_som_lu::readOn(), Champ_Uniforme_Morceaux::readOn(), Champ_Uniforme_Morceaux_Tabule_Temps::readOn(), Champ_input_P0::setValue(), TRUSTChamp_Divers_generique< _TYPE_ >::valeur_a_elem_compo(), TRUSTChamp_Divers_generique< _TYPE_ >::valeur_aux(), TRUSTChamp_Divers_generique< _TYPE_ >::valeur_aux_compo(), TRUSTChamp_Divers_generique< _TYPE_ >::valeur_aux_elems(), TRUSTChamp_Divers_generique< _TYPE_ >::valeur_aux_elems_compo(), and valeurs().