TrioCFD: Eq_ODVM Class Reference
Eq_ODVM Class Reference
#include <Eq_ODVM.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
fluctuation de temperature et l'equation de variance de temperature en 1-D
Constructor & Destructor Documentation
Eq_ODVM()
Eq_ODVM::Eq_ODVM ()
~Eq_ODVM()
Eq_ODVM::~Eq_ODVM ()
Member Function Documentation
cree_instance()
Objet_U * Eq_ODVM::cree_instance () static
taille_memoire()
unsigned Eq_ODVM::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Eq_ODVM::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Eq_ODVM::info () static
get_info()
const Type_info * Eq_ODVM::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
Eq_ODVM & Eq_ODVM::self_cast (Objet_U & r) static
self_cast() [2/2]
const Eq_ODVM & Eq_ODVM::self_cast (const Objet_U & r) static
printOn()
Sortie & Eq_ODVM::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
readOn()
Entree & Eq_ODVM::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
initialiser()
void Eq_ODVM::initialiser (int N, double gamma, double dist, double T0, double Tn, double t0, double rat, double f)
References mailler_fin(), and TRUSTVect< _TYPE_, _SIZE_ >::resize().
mailler_fin()
void Eq_ODVM::mailler_fin (double dist, double un_facteur)
Referenced by initialiser().
calculer_secmem_qb()
void Eq_ODVM::calculer_secmem_qb ()
Referenced by aller_au_temps().
calculer_secmem_qf()
void Eq_ODVM::calculer_secmem_qf ()
Referenced by aller_au_temps().
calculer_dt_stab()
void Eq_ODVM::calculer_dt_stab ()
Referenced by aller_au_temps().
set_U_tau()
void Eq_ODVM::set_U_tau (double u, int j) inline
init_profile_CHT()
void Eq_ODVM::init_profile_CHT (double Ts, double Tf)
aller_au_temps()
void Eq_ODVM::aller_au_temps (double tnp1, double Tw_np1, double Tnp1, double diff, double visco_cin, int type_pb)
References calculer_dt_stab(), calculer_secmem_qb(), and calculer_secmem_qf().
get_Tm()
double Eq_ODVM::get_Tm (int i) inline
get_Tp()
double Eq_ODVM::get_Tp (int i) inline
get_qb()
double Eq_ODVM::get_qb (int i) inline
get_qf()
double Eq_ODVM::get_qf (int i) inline
get_Y()
double Eq_ODVM::get_Y (int i) inline
get_dy_w()
double Eq_ODVM::get_dy_w () inline
get_Q()
double Eq_ODVM::get_Q (int i) inline
set_F()
void Eq_ODVM::set_F (double f) inline
Member Data Documentation
info_obj
const Type_info Eq_ODVM::info_obj static