TrioCFD: Interpolation_IBM_hybrid Class Reference
Interpolation_IBM_hybrid Class Reference
#include <Interpolation_IBM_hybrid.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
Constructor & Destructor Documentation
Interpolation_IBM_hybrid()
Interpolation_IBM_hybrid::Interpolation_IBM_hybrid ()
~Interpolation_IBM_hybrid()
Interpolation_IBM_hybrid::~Interpolation_IBM_hybrid ()
Member Function Documentation
cree_instance()
Objet_U * Interpolation_IBM_hybrid::cree_instance () static
taille_memoire()
unsigned Interpolation_IBM_hybrid::taille_memoire () const override virtual
Reimplemented from Interpolation_IBM_elem_fluid.
duplique()
int Interpolation_IBM_hybrid::duplique () const override virtual
Reimplemented from Interpolation_IBM_elem_fluid.
info()
const Type_info * Interpolation_IBM_hybrid::info () static
get_info()
const Type_info * Interpolation_IBM_hybrid::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Interpolation_IBM_elem_fluid.
self_cast() [1/2]
Interpolation_IBM_hybrid & Interpolation_IBM_hybrid::self_cast (Objet_U & r) static
self_cast() [2/2]
const Interpolation_IBM_hybrid & Interpolation_IBM_hybrid::self_cast (const Objet_U & r) static
printOn()
Sortie & Interpolation_IBM_hybrid::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Interpolation_IBM_elem_fluid.
References Objet_U::printOn().
readOn()
Entree & Interpolation_IBM_hybrid::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Interpolation_IBM_elem_fluid.
References Param::ajouter(), Interpolation_IBM_mean_gradient_proto::is_dirichlet_lu_, Param::lire_avec_accolades_depuis(), Objet_U::que_suis_je(), Param::REQUIRED, Interpolation_IBM_elem_fluid::set_param(), and Interpolation_IBM_mean_gradient_proto::solid_elems_lu_.
discretise()
void Interpolation_IBM_hybrid::discretise (const Discretisation_base & dis, Domaine_dis_base & le_dom_EF) override virtual
Reimplemented from Interpolation_IBM_elem_fluid.
References Champ_base::affecter(), Interpolation_IBM_mean_gradient_proto::computeSommetsVoisins(), Interpolation_IBM_base::corresp_elems_, Interpolation_IBM_elem_fluid::discretise(), Discretisation_base::discretiser_champ(), Interpolation_IBM_base::has_corresp_, Interpolation_IBM_mean_gradient_proto::is_dirichlet_, Interpolation_IBM_mean_gradient_proto::is_dirichlet_lu_, Interpolation_IBM_mean_gradient_proto::solid_elems_, Interpolation_IBM_mean_gradient_proto::solid_elems_lu_, and Interpolation_IBM_base::solid_points_.
getSommetsVoisinsOf()
IntList & Interpolation_IBM_hybrid::getSommetsVoisinsOf (int i) inline
References Interpolation_IBM_mean_gradient_proto::sommets_voisins_.
Referenced by Source_PDF_EF::calculer_variable_imposee_hybrid().
Friends And Related Function Documentation
Source_PDF_EF
friend class Source_PDF_EF friend
Member Data Documentation
info_obj
const Type_info Interpolation_IBM_hybrid::info_obj static