TrioCFD: Transport_Interfaces_FT_Disc Class Reference
Transport_Interfaces_FT_Disc Class Reference
#include <Transport_Interfaces_FT_Disc.h>
Public Member Functions
void associer_pb_base (const Probleme_base &probleme) override
double calculer_pas_de_temps () const override
virtual void calculer_vitesse_transport_interpolee (const Champ_base &champ_vitesse, const Maillage_FT_Disc &, DoubleTab &vitesse_noeuds, int nv_calc, int standard) const
void discretiser () override
virtual int get_champ_post_FT (const Motcle &champ, Postraitement_base::Localisation loc, DoubleTab *dtab=0) const
virtual int get_champ_post_FT (const Motcle &champ, Postraitement_base::Localisation loc, IntTab *itab=0) const
const Type_info * get_info () const override
virtual const DoubleTab & get_update_distance_interface_sommets () const
const Champ_base & get_update_indicatrice () override
int impr (Sortie &os) const override
Entree & lire_cond_init (Entree &is) override
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual const Maillage_FT_Disc & maillage_interface_pour_post () const
void mettre_a_jour (double temps) override
int preparer_calcul () override
virtual void remailler_interface ()
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
int verif_Cl () const override
const Type_info * get_info () const override
Public Member Functions inherited from Equation_base
virtual void abortTimeStep ()
virtual void associer_domaine_dis (const Domaine_dis_base &)
virtual void associer_pb_base (const Probleme_base &)
virtual void associer_sch_tps_base (const Schema_Temps_base &)
virtual double calculer_pas_de_temps () const
virtual void completer ()
virtual std::vector< YAML_data > data_a_sauvegarder () const
DoubleTab & derivee_en_temps_conv (DoubleTab &, const DoubleTab &)
virtual DoubleTab & derivee_en_temps_inco (DoubleTab &)
const Discretisation_base & discretisation () const
virtual void discretiser ()
virtual const Motcle & domaine_application () const
virtual Domaine_Cl_dis_base & domaine_Cl_dis ()
virtual const Domaine_Cl_dis_base & domaine_Cl_dis () const
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual void imprimer (Sortie &os) const
virtual bool initTimeStep (double dt)
const Nom & le_nom () const override
int limpr () const
virtual void mettre_a_jour (double temps)
virtual int preparer_calcul ()
Probleme_base & probleme ()
const Probleme_base & probleme () const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Schema_Temps_base & schema_temps ()
const Schema_Temps_base & schema_temps () const
Solveur_Masse_base & solv_masse ()
const Solveur_Masse_base & solv_masse () const
Sources & sources ()
const Sources & sources () const
virtual void valider_iteration ()
virtual void verifie_ch_init_nb_comp (const Champ_Inc_base &ch_ref, const int nb_comp) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
virtual void calculer_distance_interface (const Maillage_FT_Disc &maillage, DoubleTab &distance_elements, DoubleTab &normale_elements, const int n_iter) const
virtual void calculer_distance_interface_sommets (const DoubleTab &dist_elem, const DoubleTab &normale_elem, DoubleTab &dist_som) const
virtual void calculer_vmoy_composantes_connexes (const Maillage_FT_Disc &maillage, const ArrOfInt &compo_connexes_facettes, const int nb_compo_tot, const DoubleTab &vitesse_sommets, DoubleTab &vitesses, DoubleTab &positions) const
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Equation_base
virtual Entree & lire_cl (Entree &)
virtual Entree & lire_cond_init (Entree &)
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual Entree & lire_sources (Entree &)
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
virtual int verif_Cl () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
~Transport_Interfaces_FT_Disc()
Transport_Interfaces_FT_Disc::~Transport_Interfaces_FT_Disc ()
le destructeur qui va avec
Transport_Interfaces_FT_Disc()
Transport_Interfaces_FT_Disc::Transport_Interfaces_FT_Disc ()
constructeur par defaut
References Objet_U::dimension, and TRUSTArray< _TYPE_, _SIZE_ >::resize().
Member Function Documentation
cree_instance()
Objet_U * Transport_Interfaces_FT_Disc::cree_instance () static
taille_memoire()
unsigned Transport_Interfaces_FT_Disc::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Transport_Marqueur_FT.
duplique()
int Transport_Interfaces_FT_Disc::duplique () const override virtual
Implements Objet_U.
Reimplemented in Transport_Marqueur_FT.
info()
const Type_info * Transport_Interfaces_FT_Disc::info () static
get_info()
const Type_info * Transport_Interfaces_FT_Disc::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Transport_Interfaces_base.
Reimplemented in Transport_Marqueur_FT.
self_cast() [1/2]
Transport_Interfaces_FT_Disc & Transport_Interfaces_FT_Disc::self_cast (Objet_U & r) static
self_cast() [2/2]
const Transport_Interfaces_FT_Disc & Transport_Interfaces_FT_Disc::self_cast (const Objet_U & r) static
printOn()
Sortie & Transport_Interfaces_FT_Disc::printOn (Sortie & is) const override protected virtual
Appel a Equation_base::printOn(Sortie&)
Parameters
(Sortie& is) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Transport_Interfaces_base.
Reimplemented in Transport_Marqueur_FT.
References Transport_Interfaces_base::printOn().
readOn()
Entree & Transport_Interfaces_FT_Disc::readOn (Entree & is) override protected virtual
cf Equation_base::readOn(Entree&)
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Exceptions
terme diffusif non specifie
terme convectif non specifie
Reimplemented from Transport_Interfaces_base.
Reimplemented in Transport_Marqueur_FT.
References Domaine_dis_base::domaine(), Equation_base::domaine_dis(), Transport_Interfaces_base::readOn(), Domaine_32_64< _SIZE_ >::ss_domaine(), and suppression_interfaces_sous_domaine_.
set_param()
void Transport_Interfaces_FT_Disc::set_param (Param & titi) override virtual
Reimplemented from Equation_base.
Reimplemented in Transport_Marqueur_FT.
References Param::ajouter(), Param::ajouter_flag(), Param::ajouter_non_std(), collision_model_, compute_particles_rms_, Transport_Interfaces_FT_Disc_interne::n_iterations_interpolation_ibc, Transport_Interfaces_FT_Disc_interne::nb_iter_uzawa, Transport_Interfaces_FT_Disc_interne::nb_iterations_correction_volume, Transport_Interfaces_FT_Disc_interne::nb_lissage_correction_volume, Transport_Interfaces_FT_Disc_interne::nom_domaine_volume_impose_, Transport_Interfaces_FT_Disc_interne::nomb_fa7_accepted, Transport_Interfaces_FT_Disc_interne::parcours_interface_, post_process_hydro_forces_, remaillage_interface(), Param::REQUIRED, Equation_base::set_param(), Transport_Interfaces_FT_Disc_interne::seuil_uzawa, suppression_interfaces_sous_domaine_, topologie_interface(), Transport_Interfaces_FT_Disc_interne::vimp_regul, and Transport_Interfaces_FT_Disc_interne::VOFlike_correction_volume.
lire_motcle_non_standard()
int Transport_Interfaces_FT_Disc::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Equation_base.
Reimplemented in Transport_Marqueur_FT.
References TRUST_Vector< _CLASSE_ >::add(), Transport_Interfaces_FT_Disc_interne::AI_BASED, Transport_Interfaces_FT_Disc_interne::ANALYTIQUE, TRUSTArray< _TYPE_, _SIZE_ >::append_array(), associer_equation_ns(), Process::barrier(), Transport_Interfaces_FT_Disc_interne::BASE, Objet_U::dimension, Transport_Interfaces_FT_Disc_interne::DIST_INITIALE, Transport_Interfaces_FT_Disc_interne::DIST_MODIFIEE, Entree_Fichier_base::eof(), Process::exit(), Transport_Interfaces_FT_Disc_interne::expression_vitesse_imposee, Navier_Stokes_FT_Disc::get_is_solid_particle(), Remaillage_FT::get_nb_iter_bary_volume_seul(), Transport_Interfaces_FT_Disc_interne::injection_interfaces_expressions_, Transport_Interfaces_FT_Disc_interne::injection_interfaces_phase_, Transport_Interfaces_FT_Disc_interne::injection_interfaces_temps_, Transport_Interfaces_FT_Disc_interne::interpolation_champ_face, Transport_Interfaces_FT_Disc_interne::is_distance_projete_face, Transport_Interfaces_FT_Disc_interne::is_extra_diphasique_solide, Transport_Interfaces_FT_Disc_interne::is_extra_solide, Transport_Interfaces_FT_Disc_interne::iterations_correction_volume, Process::je_suis_maitre(), Transport_Interfaces_FT_Disc_interne::LINEAIRE, Equation_base::lire_motcle_non_standard(), Maillage_FT_Disc::lire_param_maillage(), Transport_Interfaces_FT_Disc_interne::LOI_HORAIRE, Transport_Interfaces_FT_Disc_interne::loi_horaire_, maillage_interface(), Transport_Interfaces_FT_Disc_interne::MEAN_VOLUMIC_VELOCITY, Transport_Interfaces_FT_Disc_interne::methode_interpolation_v, Transport_Interfaces_FT_Disc_interne::methode_transport, Transport_Interfaces_FT_Disc_interne::modified_indic_faces_position, Transport_Interfaces_FT_Disc_interne::modified_indic_faces_thickness, Transport_Interfaces_FT_Disc_interne::MODIFIEE, Transport_Interfaces_FT_Disc_interne::n_iterations_distance, Transport_Interfaces_FT_Disc_interne::nb_iterations_correction_volume, Transport_Interfaces_FT_Disc_interne::nb_lissage_correction_volume, Interprete::objet(), Transport_Interfaces_FT_Disc_interne::parcours_interface_, probleme_base_, Transport_Interfaces_FT_Disc_interne::PROJETE_INITIAL, Transport_Interfaces_FT_Disc_interne::PROJETE_MODIFIE, Transport_Interfaces_FT_Disc_interne::PROJETE_SIMPLIFIE, Transport_Interfaces_FT_Disc_interne::refequation_vitesse_transport, remaillage_interface(), Motcles::search(), Maillage_FT_Disc::set_is_solid_particle(), Remaillage_FT::set_is_solid_particle(), set_is_solid_particle(), Transport_Interfaces_FT_Disc_interne::STANDARD, Transport_Interfaces_FT_Disc_interne::type_indic_faces_, Transport_Interfaces_FT_Disc_interne::UNIFORME, TRUST_Ref< _CLASSE_ >::valeur(), Transport_Interfaces_FT_Disc_interne::VALEUR_A_ELEM, Transport_Interfaces_FT_Disc_interne::VDF_LINEAIRE, Transport_Interfaces_FT_Disc_interne::vf_explicite, Transport_Interfaces_FT_Disc_interne::VITESSE_IMPOSEE, Transport_Interfaces_FT_Disc_interne::VITESSE_INTERPOLEE, Transport_Interfaces_FT_Disc_interne::VOFlike_correction_volume, and Transport_Interfaces_FT_Disc_interne::volume_impose_phase_1.
nombre_d_operateurs()
int Transport_Interfaces_FT_Disc::nombre_d_operateurs () const override virtual
Implements Equation_base.
operateur() [1/2]
const Operateur & Transport_Interfaces_FT_Disc::operateur (int i) const override virtual
Implements Equation_base.
References Process::exit().
operateur() [2/2]
Operateur & Transport_Interfaces_FT_Disc::operateur (int i) override virtual
Implements Equation_base.
References Process::exit().
inconnue() [1/2]
const Champ_Inc_base & Transport_Interfaces_FT_Disc::inconnue () const override virtual
Implements Equation_base.
Reimplemented in Transport_Marqueur_FT.
References indicatrice_.
Referenced by SourceFiltree_FT_disc_VEF_P1NC::associer_pb(), Champ_P1NC::calcul_y_plus_diphasique(), Champ_Face_VDF::calcul_y_plus_diphasique(), Navier_Stokes_FT_Disc::calculer_dI_dt(), Paroi_std_hyd_VDF_diphasique::calculer_hyd(), Paroi_std_hyd_VEF_diphasique::calculer_hyd(), Senseur_Interface::calculer_position(), Triple_Line_Model_FT_Disc::compute_TCL_fluxes_in_all_boundary_cells(), Convection_Diffusion_Temperature_FT_Disc::correct_mpoint(), discretiser(), Frontiere_ouverte_vitesse_vortex::mettre_a_jour(), Maillage_FT_Disc::nettoyer_phase(), Convection_Diffusion_Concentration_FT_Disc::ramasse_miette_simple(), Convection_Diffusion_Concentration_Turbulent_FT_Disc::ramasse_miette_simple(), sauvegarder(), and update_critere_statio().
inconnue() [2/2]
Champ_Inc_base & Transport_Interfaces_FT_Disc::inconnue () override virtual
Implements Equation_base.
Reimplemented in Transport_Marqueur_FT.
References indicatrice_.
associer_milieu_base()
void Transport_Interfaces_FT_Disc::associer_milieu_base (const Milieu_base & milieu) override virtual
Implements Equation_base.
associer_equation_ns()
void Transport_Interfaces_FT_Disc::associer_equation_ns (const Navier_Stokes_FT_Disc & ns)
References equation_ns_.
Referenced by lire_motcle_non_standard().
milieu() [1/2]
Milieu_base & Transport_Interfaces_FT_Disc::milieu () override virtual
Implements Equation_base.
References Process::exit(), Probleme_U::le_nom(), TRUST_Ref< _CLASSE_ >::non_nul(), Equation_base::probleme(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Transport_Marqueur_FT::calculer_proprietes_fluide_pos_particules(), and Transport_Marqueur_FT::construction_ensemble_proprietes().
milieu() [2/2]
const Milieu_base & Transport_Interfaces_FT_Disc::milieu () const override virtual
Implements Equation_base.
References Process::exit(), Probleme_U::le_nom(), TRUST_Ref< _CLASSE_ >::non_nul(), Equation_base::probleme(), and TRUST_Ref< _CLASSE_ >::valeur().
associer_pb_base()
void Transport_Interfaces_FT_Disc::associer_pb_base (const Probleme_base & pb) override virtual
S'associe au Probleme passe en parametre.
Associe egalement les sources, les operateurs et le solveur de masse a l'equation.
Parameters
(Probleme_base& pb) le probleme auquel l'equation doit s'associer
Reimplemented from Equation_base.
References Equation_base::associer_pb_base(), Process::exit(), Probleme_base::is_dilatable(), Probleme_U::le_nom(), TRUST_Ref< _CLASSE_ >::non_nul(), probleme_base_, and Transport_Interfaces_FT_Disc_interne::set_pb_name().
discretiser()
void Transport_Interfaces_FT_Disc::discretiser () override virtual
Discretisation des champs: - indicatrice_ : champ scalaire discretise aux elements.
typage du maillage et de l'algorithme marching cubes
Reimplemented from Equation_base.
Reimplemented in Transport_Marqueur_FT.
References Champs_compris_T< FIELD_TYPE >::ajoute_champ(), Transport_Interfaces_FT_Disc_interne::algorithmes_transport_, Domaine_Cl_dis_base::associer(), Parcours_interface::associer_connectivite_frontieres(), Remaillage_FT::associer_domaine(), Parcours_interface::associer_domaine_dis(), Connectivite_frontieres::associer_domaine_vf(), Marching_Cubes::associer_domaine_vf(), Champ_Inc_base::associer_eqn(), MorEqn::associer_eqn(), Maillage_FT_Disc::associer_equation_transport(), Domaine_Cl_dis_base::associer_inconnue(), Equation_base::calculate_time_derivative(), Equation_base::champs_compris_, Maillage_FT_Disc::changer_temps(), connectivite_frontieres(), Transport_Interfaces_FT_Disc_interne::connectivite_frontieres_, Domaine_32_64< _SIZE_ >::construire_elem_virt_pe_num(), Domaine_VF::construire_face_virt_pe_num(), Domaine_32_64< _SIZE_ >::creer_tableau_sommets(), Equation_base::derivee_en_temps_, Objet_U::dimension, Equation_base::discretisation(), Discretisation_base::discretiser_champ(), Transport_Interfaces_FT_Disc_interne::distance_interface, Transport_Interfaces_FT_Disc_interne::distance_interface_faces, Transport_Interfaces_FT_Disc_interne::distance_interface_faces_corrigee, Transport_Interfaces_FT_Disc_interne::distance_interface_faces_difference, Transport_Interfaces_FT_Disc_interne::distance_interface_sommets, Domaine_dis_base::domaine(), Equation_base::domaine_dis(), inconnue(), Transport_Interfaces_FT_Disc_interne::index_element, indicatrice_, Transport_Interfaces_FT_Disc_interne::indicatrice_cache, indicatrice_faces_, Equation_base::le_dom_Cl_dis, Equation_base::le_nom(), maillage_interface(), marching_cubes(), Schema_Temps_base::nb_valeurs_temporelles(), Transport_Interfaces_FT_Disc_interne::nelem_par_direction, Transport_Interfaces_FT_Disc_interne::normale_interface, Transport_Interfaces_FT_Disc_interne::parcours_interface_, Champ_Inc_base::PDI_save_type(), remaillage_interface(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Equation_base::schema_temps(), Transport_Interfaces_FT_Disc_interne::set_ident(), Transport_Interfaces_FT_Disc_interne::surface_interface, Schema_Temps_base::temps_courant(), Transport_Interfaces_FT_Disc_interne::tmp_flux, Objet_U_ptr::typer(), Transport_Interfaces_FT_Disc_interne::vitesse_filtree, and vitesse_imp_interp_.
Referenced by Transport_Marqueur_FT::discretiser().
lire_cond_init()
Entree & Transport_Interfaces_FT_Disc::lire_cond_init (Entree & is) override virtual
Lecture des conditions initiales.
On s'attend a trouver ceci : { fonction EXPRESSION } ou expression depend de x, y et z et sera interpretee par le parser de TRUST. L'expression est envoyee a Marching_Cubes pour construire l'interface. Voir aussi parser et Marching_Cubes.
Reimplemented from Equation_base.
Reimplemented in Transport_Marqueur_FT.
References Maillage_FT_Disc::AJOUTE_PHASE0, Maillage_FT_Disc::AJOUTE_PHASE1, Maillage_FT_Disc::AJOUTE_TOUTES_PHASES, Maillage_FT_Disc::ajouter_maillage(), Maillage_FT_Disc::associer_equation_transport(), Process::barrier(), Marching_Cubes::construire_iso(), Transport_Interfaces_FT_Disc_interne::distance_interface_sommets, Process::exit(), Nom::finit_par(), Transport_Interfaces_FT_Disc_interne::indicatrice_cache, Process::je_suis_maitre(), lire_maillage_ft_cao(), maillage_interface(), marching_cubes(), EcritureLectureSpecial::mode_lec, Equation_base::probleme(), reprendre(), Motcles::search(), and Champ_Inc_base::valeurs().
verif_Cl()
int Transport_Interfaces_FT_Disc::verif_Cl () const override virtual
Methode appelee par Equation_base::readOn On verifie que toutes les cl sont de type Paroi_FT_disc.
Fait Process::exit() si erreur.
Reimplemented from Equation_base.
References Process::exit(), Equation_base::le_dom_Cl_dis, Domaine_Cl_dis_base::les_conditions_limites(), and TRUST_Vector< _CLASSE_ >::size().
calculer_pas_de_temps()
double Transport_Interfaces_FT_Disc::calculer_pas_de_temps () const override virtual
Calcul du prochain pas de temps.
Renvoie l'inverse de la somme des inverses des pas de temps calcules par les operateurs. Ces pas de temps sont ceux pour le schema d'Euler explicite. Le pas de temps n'est pas majore par dt_max, ceci est fait dans corriger_dt_calcule
Returns
(double) inverse de la somme des inverses des pas de temps calcules par les operateurs
Reimplemented from Equation_base.
derivee_en_temps_inco()
DoubleTab & Transport_Interfaces_FT_Disc::derivee_en_temps_inco (DoubleTab & derivee) override virtual
Calcul de la derivee en temps de l'inconnue : zero.
Reimplemented from Equation_base.
assembler()
void Transport_Interfaces_FT_Disc::assembler (Matrice_Morse & mat_morse, const DoubleTab & present, DoubleTab & secmem) override virtual
Reimplemented from Equation_base.
References Process::abort().
mettre_a_jour()
void Transport_Interfaces_FT_Disc::mettre_a_jour (double temps) override virtual
La valeur de l'inconnue sur le pas de temps a ete calculee.
Cette methode avance le present jusqu'au temps passe en parametre. Elle met aussi a jour les proprietes du milieu.
Parameters
(double temps) le pas de temps de mise a jour
Reimplemented from Equation_base.
Reimplemented in Transport_Marqueur_FT.
References Maillage_FT_Disc::AJOUTE_PHASE0, Maillage_FT_Disc::AJOUTE_PHASE1, Maillage_FT_Disc::ajouter_maillage(), Maillage_FT_Disc::associer_equation_transport(), Process::barrier(), Equation_base::calculate_time_derivative(), calculer_integrale_indicatrice(), Champ_Inc_base::changer_temps(), Maillage_FT_Disc::changer_temps(), Process::check_int_overflow(), collision_model_, Maillage_FT_Disc::completer_maillage(), Post_Processing_Hydrodynamic_Forces::compute_heat_transfer(), Post_Processing_Hydrodynamic_Forces::compute_hydrodynamic_forces(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_hydrodynamic_forces(), Navier_Stokes_FT_Disc::compute_particles_eulerian_id_number(), compute_particles_rms(), Marching_Cubes::construire_iso(), Intersections_Elem_Facettes::data_intersection(), deplacer_maillage_ft_v_fluide(), Equation_base::derivee_en_temps(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Transport_Interfaces_FT_Disc_interne::distance_interface_sommets, Equation_base::domaine_dis(), Post_Processing_Hydrodynamic_Forces::drop_the_flag(), Post_Processing_Hydrodynamic_Forces::drop_the_flag_heat_transfer(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Process::exit(), Transport_Interfaces_FT_Disc_interne::expression_vitesse_imposee, Maillage_FT_Disc::facette_virtuelle(), Intersections_Elem_Facettes_Data::fraction_surface_intersection_, Post_Processing_Hydrodynamic_Forces::get_is_compute_forces(), Post_Processing_Hydrodynamic_Forces::get_is_compute_forces_Stokes_th(), Post_Processing_Hydrodynamic_Forces::get_is_compute_heat_transfer(), get_probleme_base(), get_update_distance_interface(), get_update_indicatrice(), get_update_normale_interface(), Maillage_FT_Disc::get_update_surface_facettes(), gravity_center_elem_, Intersections_Elem_Facettes::index_elem(), Intersections_Elem_Facettes_Data::index_facette_suivante_, indicatrice_, Transport_Interfaces_FT_Disc_interne::indicatrice_cache, Transport_Interfaces_FT_Disc_interne::injection_interfaces_expressions_, Transport_Interfaces_FT_Disc_interne::injection_interfaces_last_time_, Transport_Interfaces_FT_Disc_interne::injection_interfaces_phase_, Transport_Interfaces_FT_Disc_interne::injection_interfaces_temps_, Maillage_FT_Disc::intersections_elem_facettes(), is_solid_particle_, Process::je_suis_maitre(), Process::Journal(), Equation_base::le_nom(), Equation_base::limpr(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Transport_Interfaces_FT_Disc_interne::LOI_HORAIRE, Transport_Interfaces_FT_Disc_interne::loi_horaire_, maillage_interface(), marching_cubes(), Transport_Interfaces_FT_Disc_interne::methode_transport, Champ_Fonc_base::mettre_a_jour(), Process::mp_sum(), Domaine_dis_base::nb_elem(), Maillage_FT_Disc::nb_facettes(), Maillage_FT_Disc::nb_sommets(), Maillage_FT_Disc::nettoyer_elements_virtuels(), Intersections_Elem_Facettes_Data::numero_facette_, post_process_hydro_forces_, post_process_hydro_forces_Stokes_, Triple_Line_Model_FT_Disc::Rc_inject(), Triple_Line_Model_FT_Disc::ready_inject_tcl(), Transport_Interfaces_FT_Disc_interne::refequation_vitesse_transport, Triple_Line_Model_FT_Disc::reinjection_tcl(), remailler_interface(), Equation_base::schema_temps(), TRUST_Vector< _CLASSE_ >::size(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), Maillage_FT_Disc::sommet_virtuel(), Maillage_FT_Disc::sommets(), Transport_Interfaces_FT_Disc_interne::surface_interface, Navier_Stokes_FT_Disc::swap_particles_eulerian_id_number(), Probleme_FT_Disc_gen::tcl(), Maillage_FT_Disc::temps(), test_suppression_interfaces_sous_domaine(), Triple_Line_Model_FT_Disc::thetaC_tcl(), Maillage_FT_Disc::transporter(), update_critere_statio(), TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), Champ_Inc_base::valeurs(), Champ_Proto::valeurs(), Transport_Interfaces_FT_Disc_interne::VITESSE_IMPOSEE, Transport_Interfaces_FT_Disc_interne::VITESSE_INTERPOLEE, Domaine_VF::volumes(), and Domaine_VF::xp().
data_a_sauvegarder()
std::vector< YAML_data > Transport_Interfaces_FT_Disc::data_a_sauvegarder () const override virtual
for PDI IO: retrieve name and type and dimensions of the indicatrice tag
Reimplemented from Equation_base.
References Transport_Interfaces_FT_Disc_interne::data_a_sauvegarder(), and Equation_base::data_a_sauvegarder().
sauvegarder()
int Transport_Interfaces_FT_Disc::sauvegarder (Sortie & os) const override virtual
On sauvegarde l'inconnue de l'equation sur un flot de sortie.
Parameters
(Sortie& os)
Returns
(int) le code de retour de Champ_Inc::sauvegarder()
Reimplemented from Equation_base.
Reimplemented in Transport_Marqueur_FT.
References collision_model_, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Process::exit(), Sortie::flush(), inconnue(), EcritureLectureSpecial::is_ecriture_special(), TRUST_2_PDI::is_PDI_checkpoint(), is_solid_particle_, Process::je_suis_maitre(), Objet_U_ptr::non_nul(), particles_position_collision_, particles_velocity_collision_, Objet_U::que_suis_je(), Equation_base::sauvegarder(), Collision_Model_FT_base::sauvegarder(), Transport_Interfaces_FT_Disc_interne::sauvegarder(), Transport_Interfaces_FT_Disc_interne::set_time(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), Champ_base::temps(), and TRUST_Deriv< _CLASSE_ >::valeur().
reprendre()
int Transport_Interfaces_FT_Disc::reprendre (Entree & fich) override virtual
On reprend l'inconnue a partir d'un flot d'entree.
[ON CHERCHE L'INCONNUE PAR SON NOM] [ON LIT L'INCONNUE] Voir Champ_Inc::reprendre(Entree&)
Parameters
(Entree& fich) le flot d'entree (fichier) a lire
Returns
(int) renvoie toujours 1
Exceptions
erreur de reprise, fin de fichier atteinte sans trouver l'inconnue
Reimplemented from Equation_base.
Reimplemented in Transport_Marqueur_FT.
References Maillage_FT_Disc::associer_equation_transport(), Domaine_32_64< _SIZE_ >::chercher_elements(), collision_model_, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Domaine_dis_base::domaine(), Equation_base::domaine_dis(), Process::exit(), get_probleme_base(), gravity_center_elem_, Transport_Interfaces_FT_Disc_interne::injection_interfaces_last_time_, EcritureLectureSpecial::is_lecture_special(), TRUST_2_PDI::is_PDI_restart(), is_solid_particle_, Transport_Interfaces_FT_Disc_interne::maillage_interface, Objet_U_ptr::non_nul(), particles_position_collision_, particles_velocity_collision_, Objet_U::que_suis_je(), Equation_base::reprendre(), Collision_Model_FT_base::reprendre(), Transport_Interfaces_FT_Disc_interne::reprendre(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Probleme_base::restart_filename(), Equation_base::schema_temps(), Transport_Interfaces_FT_Disc_interne::set_restart_fname(), Transport_Interfaces_FT_Disc_interne::set_time(), Schema_Temps_base::temps_courant(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by lire_cond_init().
impr()
int Transport_Interfaces_FT_Disc::impr (Sortie & os) const override virtual
Imprime les operateurs de l'equation sur un flot de sortie, de facon inconditionnelle.
appelle Operateur_base::impr(os)
Parameters
(Sortie& os) le flot de sortie
Returns
(int) renvoie toujours 1
Reimplemented from Equation_base.
References collision_model_, compute_particles_rms_, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Domaine_dis_base::domaine(), Equation_base::domaine_dis(), Collision_Model_FT_base::get_collision_number(), Post_Processing_Hydrodynamic_Forces::get_friction_force(), Post_Processing_Hydrodynamic_Forces::get_heat_transfer(), Post_Processing_Hydrodynamic_Forces::get_is_compute_forces(), Post_Processing_Hydrodynamic_Forces::get_is_compute_forces_Stokes_th(), Post_Processing_Hydrodynamic_Forces::get_is_compute_heat_transfer(), Collision_Model_FT_base::get_lagrangian_contact_forces(), get_mean_particles_volumic_squared_velocity(), get_mean_particles_volumic_velocity(), Collision_Model_FT_base::get_particles_collision_number(), get_particles_purely_solid_mesh_volume(), Post_Processing_Hydrodynamic_Forces::get_pressure_force(), Post_Processing_Hydrodynamic_Forces::get_prop_fa7_ok_P2(), Post_Processing_Hydrodynamic_Forces::get_prop_P2_fluid(), get_rms_particles_volumic_velocity(), Post_Processing_Hydrodynamic_Forces::get_total_surface_interf(), Post_Processing_Hydrodynamic_Forces::get_U_P2_moy(), Schema_Temps_base::imprimer_temps_courant(), is_solid_particle_, Process::je_suis_maitre(), Objet_U_ptr::non_nul(), particles_position_collision_, particles_velocity_collision_, post_process_hydro_forces_, post_process_hydro_forces_Stokes_, Equation_base::schema_temps(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), Schema_Temps_base::temps_courant(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by calcul_effort_fluide_interface().
update_critere_statio()
void Transport_Interfaces_FT_Disc::update_critere_statio ()
References inconnue(), Schema_Temps_base::pas_de_temps(), Champ_Inc_base::passe(), Equation_base::schema_temps(), Schema_Temps_base::update_critere_statio(), and Champ_Inc_base::valeurs().
Referenced by mettre_a_jour().
init_save_file()
void Transport_Interfaces_FT_Disc::init_save_file () override virtual
Reimplemented from Equation_base.
References Transport_Interfaces_FT_Disc_interne::init_save_file().
close_save_file()
void Transport_Interfaces_FT_Disc::close_save_file () override virtual
Reimplemented from Equation_base.
References Transport_Interfaces_FT_Disc_interne::close_save_file().
lire_maillage_ft_cao()
void Transport_Interfaces_FT_Disc::lire_maillage_ft_cao (Entree & is) virtual
References TRUST_Vector< _CLASSE_ >::add(), Process::barrier(), Format_Post_Lata::BINAIRE, Domaine_32_64< _SIZE_ >::chercher_elements(), Domaine_32_64< _SIZE_ >::creer_tableau_elements(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Domaine_dis_base::domaine(), Equation_base::domaine_dis(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Format_Post_Lata::ecrire_champ(), Format_Post_Lata::ecrire_domaine(), Format_Post_Lata::ecrire_entete(), Format_Post_Lata::ecrire_temps(), Domaine_VF::elem_faces(), Process::exit(), Domaine_VF::face_voisins(), get_update_distance_interface(), get_update_indicatrice(), Intersections_Elem_Facettes::index_elem(), Transport_Interfaces_FT_Disc_interne::indicatrice_cache, Scatter::init_sequential_domain(), Format_Post_Lata::initialize(), Maillage_FT_Disc::intersections_elem_facettes(), Domaine_base::le_nom(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Sauvegarde_Reprise_Maillage_FT::lire_xyz(), maillage_interface(), Process::mp_max(), Domaine_32_64< _SIZE_ >::nb_elem(), Interprete::objet(), Maillage_FT_Disc::parcourir_maillage(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), Motcles::search(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), Scatter::uninit_sequential_domain(), and Champ_Inc_base::valeurs().
Referenced by lire_cond_init().
preparer_calcul()
int Transport_Interfaces_FT_Disc::preparer_calcul () override virtual
Tout ce qui ne depend pas des autres problemes eventuels.
Returns
(int) renvoie toujours 1
Reimplemented from Equation_base.
Reimplemented in Transport_Marqueur_FT.
References Post_Processing_Hydrodynamic_Forces::associate_ns_equation(), Post_Processing_Hydrodynamic_Forces::associate_transport_equation(), Equation_base::calculate_time_derivative(), Champ_base::changer_temps(), Champ_Inc_base::changer_temps(), Probleme_base::checkpoint_filename(), collision_model_, Maillage_FT_Disc::compute_gravity_center_fa7(), Equation_base::derivee_en_temps(), Objet_U::dimension, Transport_Interfaces_FT_Disc_interne::distance_interface, Transport_Interfaces_FT_Disc_interne::distance_interface_faces, Transport_Interfaces_FT_Disc_interne::distance_interface_faces_corrigee, Transport_Interfaces_FT_Disc_interne::distance_interface_faces_difference, Equation_base::domaine_dis(), equation_ns_, Process::exit(), get_probleme_base(), Maillage_FT_Disc::get_schema_comm_FT(), get_update_distance_interface(), get_update_indicatrice(), get_update_normale_interface(), Transport_Interfaces_FT_Disc_interne::INDEFINI, Transport_Interfaces_FT_Disc_interne::index_element, indicatrice_, Transport_Interfaces_FT_Disc_interne::indicatrice_cache, indicatrice_faces_, init_particles_position_velocity(), Domaine_Cl_dis_base::initialiser(), is_solid_particle_, Process::Journal(), Equation_base::le_dom_Cl_dis, Equation_base::le_nom(), maillage_interface(), mean_particles_volumic_squared_velocity_, mean_particles_volumic_velocity_, Transport_Interfaces_FT_Disc_interne::methode_transport, Transport_Interfaces_FT_Disc_interne::nelem_par_direction, Objet_U_ptr::non_nul(), Transport_Interfaces_FT_Disc_interne::normale_interface, particles_purely_solid_mesh_volume_, post_process_hydro_forces_, post_process_hydro_forces_Stokes_, Collision_Model_FT_base::preparer_calcul(), Equation_base::probleme(), remailler_interface(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Post_Processing_Hydrodynamic_Forces::resize_and_init_tables(), Post_Processing_Hydrodynamic_Forces_Stokes::resize_and_init_tables(), rms_particles_volumic_velocity_, Equation_base::schema_temps(), Transport_Interfaces_FT_Disc_interne::set_checkpoint_fname(), Post_Processing_Hydrodynamic_Forces_Stokes::set_param(), Transport_Interfaces_FT_Disc_interne::surface_interface, Schema_Temps_base::temps_courant(), Transport_Interfaces_FT_Disc_interne::tmp_flux, TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_Inc_base::valeurs(), Champ_Proto::valeurs(), Transport_Interfaces_FT_Disc_interne::vitesse_filtree, and vitesse_imp_interp_.
preparer_pas_de_temps()
void Transport_Interfaces_FT_Disc::preparer_pas_de_temps () virtual
maillage_interface() [1/2]
const Maillage_FT_Disc & Transport_Interfaces_FT_Disc::maillage_interface () const
References Transport_Interfaces_FT_Disc_interne::maillage_interface.
Referenced by ajouter_contribution_saut_vitesse(), Transport_Marqueur_FT::ajouter_points(), calcul_eq_plan_facette(), Transport_Marqueur_FT::calcul_vitesse_p(), Navier_Stokes_FT_Disc::calculer_delta_u_interface(), Navier_Stokes_FT_Disc::calculer_dI_dt(), Navier_Stokes_FT_Disc::calculer_gradient_indicatrice(), Transport_Marqueur_FT::calculer_valeurs_densite(), Transport_Marqueur_FT::calculer_valeurs_volumes(), Transport_Marqueur_FT::completer(), Post_Processing_Hydrodynamic_Forces::compute_heat_transfer(), Triple_Line_Model_FT_Disc::compute_TCL_fluxes_in_all_boundary_cells(), deplacer_maillage_ft_v_fluide(), Convection_Diffusion_Temperature_FT_Disc::derivee_en_temps_inco(), Navier_Stokes_FT_Disc::derivee_en_temps_inco(), discretiser(), Transport_Marqueur_FT::discretiser(), Triple_Line_Model_FT_Disc::elems(), RK3_FT::faire_un_pas_de_temps_pb_couple(), Triple_Line_Model_FT_Disc::get_any_tcl_face(), Triple_Line_Model_FT_Disc::get_in_out_coords(), get_update_distance_interface(), get_update_distance_interface_faces(), get_update_distance_interface_sommets(), get_update_indicatrice(), get_update_normale_interface(), Transport_Marqueur_FT::imposer_cond_lim(), init_particles_position_velocity(), Triple_Line_Model_FT_Disc::initialize(), Transport_Marqueur_FT::initTimeStep(), Transport_Marqueur_FT::integrer_ensemble_lagrange(), interpoler_vitesse_face(), RK3_FT::iterateTimeStep(), lire_cond_init(), Transport_Marqueur_FT::lire_cond_init(), lire_maillage_ft_cao(), lire_motcle_non_standard(), maillage_interface_pour_post(), mettre_a_jour(), Transport_Marqueur_FT::mettre_a_jour(), nettoyer_maillage(), preparer_calcul(), Transport_Marqueur_FT::preparer_calcul(), remailler_interface(), Collision_Model_FT_base::research_collision_pairs_Verlet(), suppression_interfaces(), test_suppression_interfaces_sous_domaine(), Transport_Marqueur_FT::transformer_particules(), transporter_sans_changement_topologie(), Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_elem(), Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_face(), Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_face_sommets(), Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_gradU_elem(), Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_gradU_elem_P1(), and Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_gradU_face().
get_update_indicatrice()
const Champ_base & Transport_Interfaces_FT_Disc::get_update_indicatrice () override virtual
Recalcul du champ variables_internes_->indicatrice_cache a partir de la position des interfaces.
ATTENTION, ce n'est pas l'inconnue du probleme. L'inconnue est mise a jour a partir de ce champ dans mettre_a_jour.
Implements Transport_Interfaces_base.
References Maillage_FT_Disc::calcul_indicatrice(), Maillage_FT_Disc::get_mesh_tag(), Transport_Interfaces_FT_Disc_interne::indicatrice_cache, Transport_Interfaces_FT_Disc_interne::indicatrice_cache_tag, maillage_interface(), Maillage_FT_Disc::parcourir_maillage(), TRUST_Deriv< _CLASSE_ >::valeur(), and Champ_Inc_base::valeurs().
Referenced by calculer_composantes_connexes_pour_suppression(), Convection_Diffusion_Temperature_FT_Disc::calculer_grad_t(), Post_Processing_Hydrodynamic_Forces::find_neighboring_elements(), get_compute_indicatrice_faces(), interpoler_vitesse_face(), lire_maillage_ft_cao(), Convection_Diffusion_Temperature_FT_Disc::mettre_a_jour(), mettre_a_jour(), modifier_vpoint_pour_imposer_vit(), preparer_calcul(), ramasse_miettes(), test_suppression_interfaces_sous_domaine(), Remailleur_Collision_FT_Thomas::traite_RuptureCoalescenceInterfaces_Conservatif(), Transport_Marqueur_FT::transformation(), transporter_sans_changement_topologie(), Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_elem(), and Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_gradU_elem_P1().
get_indicatrice_faces()
const Champ_base & Transport_Interfaces_FT_Disc::get_indicatrice_faces () virtual
References indicatrice_faces_.
Referenced by calcul_effort_fluide_interface(), impr_effort_fluide_interface(), and modifier_vpoint_pour_imposer_vit().
get_compute_indicatrice_faces()
const Champ_base & Transport_Interfaces_FT_Disc::get_compute_indicatrice_faces () virtual
References calcul_indicatrice_faces(), Equation_base::domaine_dis(), Domaine_dis_base::face_voisins(), get_update_indicatrice(), indicatrice_faces_, and Champ_Proto::valeurs().
Referenced by interpoler_vitesse_face().
parcours_interface()
const Parcours_interface & Transport_Interfaces_FT_Disc::parcours_interface () const virtual
References Transport_Interfaces_FT_Disc_interne::parcours_interface_.
Referenced by Maillage_FT_Disc::associer_equation_transport(), and Triple_Line_Model_FT_Disc::compute_TCL_fluxes_in_all_boundary_cells().
marching_cubes() [1/2]
const Marching_Cubes & Transport_Interfaces_FT_Disc::marching_cubes () const virtual
References Transport_Interfaces_FT_Disc_interne::marching_cubes_.
Referenced by discretiser(), lire_cond_init(), mettre_a_jour(), and Remailleur_Collision_FT_Juric::traite_RuptureCoalescenceInterfaces().
algorithmes_transport()
const Algorithmes_Transport_FT_Disc & Transport_Interfaces_FT_Disc::algorithmes_transport () const virtual
References Transport_Interfaces_FT_Disc_interne::algorithmes_transport_, and TRUST_Deriv< _CLASSE_ >::valeur().
connectivite_frontieres()
const Connectivite_frontieres & Transport_Interfaces_FT_Disc::connectivite_frontieres () const virtual
References Transport_Interfaces_FT_Disc_interne::connectivite_frontieres_.
Referenced by discretiser().
remaillage_interface() [1/2]
Remaillage_FT & Transport_Interfaces_FT_Disc::remaillage_interface ()
References Transport_Interfaces_FT_Disc_interne::remaillage_interface_.
Referenced by deplacer_maillage_ft_v_fluide(), discretiser(), lire_motcle_non_standard(), remailler_interface(), and set_param().
remaillage_interface() [2/2]
const Remaillage_FT & Transport_Interfaces_FT_Disc::remaillage_interface () const
References Transport_Interfaces_FT_Disc_interne::remaillage_interface_.
topologie_interface() [1/2]
const Topologie_Maillage_FT & Transport_Interfaces_FT_Disc::topologie_interface () const
References Transport_Interfaces_FT_Disc_interne::topologie_interface_.
Referenced by calculer_composantes_connexes_pour_suppression(), remailler_interface(), set_param(), suppression_interfaces(), and test_suppression_interfaces_sous_domaine().
calculer_integrale_indicatrice()
double Transport_Interfaces_FT_Disc::calculer_integrale_indicatrice (const DoubleVect & indicatrice, double & v_ph0) const virtual
References Equation_base::domaine_dis(), Process::mp_sum(), Domaine_dis_base::nb_elem(), TRUSTVect< _TYPE_, _SIZE_ >::size(), and Domaine_VF::volumes().
Referenced by deplacer_maillage_ft_v_fluide(), and mettre_a_jour().
proprietes_particules() [1/2]
const Proprietes_part_vol & Transport_Interfaces_FT_Disc::proprietes_particules () const
References Transport_Interfaces_FT_Disc_interne::proprietes_particules_.
Referenced by Transport_Marqueur_FT::calcul_vitesse_p(), Transport_Marqueur_FT::calculer_valeurs_volumes(), Transport_Marqueur_FT::completer(), Source_Action_Particules::delta_v(), Source_Action_Particules::diametre_particules(), Transport_Marqueur_FT::get_champ_post_FT(), Transport_Marqueur_FT::imposer_cond_lim(), Transport_Marqueur_FT::initTimeStep(), Transport_Marqueur_FT::injection(), Transport_Marqueur_FT::integrer_ensemble_lagrange(), Transport_Marqueur_FT::lire_cond_init(), nettoyer_proprietes_particules(), Transport_Marqueur_FT::preparer_calcul(), Transport_Marqueur_FT::resoudre_edo(), Source_Action_Particules::rho_particules(), Transport_Marqueur_FT::update_delta_v(), Source_Action_Particules::vitesse_particules(), and Source_Action_Particules::volumes_particules().
maillage_inject() [1/2]
const Maillage_FT_Disc & Transport_Interfaces_FT_Disc::maillage_inject () const
References Transport_Interfaces_FT_Disc_interne::maillage_inject_.
Referenced by Transport_Marqueur_FT::completer(), Transport_Marqueur_FT::injecter(), and Transport_Marqueur_FT::lire_injection().
proprietes_inject() [1/2]
const Proprietes_part_vol & Transport_Interfaces_FT_Disc::proprietes_inject () const
References Transport_Interfaces_FT_Disc_interne::proprietes_inject_.
Referenced by Transport_Marqueur_FT::completer(), Transport_Marqueur_FT::injecter(), and Transport_Marqueur_FT::lire_injection().
nettoyer_proprietes_particules()
void Transport_Interfaces_FT_Disc::nettoyer_proprietes_particules (const ArrOfInt & som_utilises)
References Proprietes_part_vol::nettoyer(), and proprietes_particules().
Referenced by Maillage_FT_Disc::nettoyer_noeuds_virtuels_et_frontieres(), and Maillage_FT_Disc::nettoyer_phase().
calculer_vitesse_transport_interpolee() [1/2]
virtual void Transport_Interfaces_FT_Disc::calculer_vitesse_transport_interpolee (const Champ_base & champ_vitesse, const Maillage_FT_Disc & m, DoubleTab & vitesse_noeuds, int nv_calc) const inline virtual
References calculer_vitesse_transport_interpolee().
Referenced by ajouter_contribution_saut_vitesse(), Transport_Marqueur_FT::calcul_vitesse_p(), Transport_Marqueur_FT::calculer_proprietes_fluide_pos_particules(), calculer_vitesse_transport_interpolee(), deplacer_maillage_ft_v_fluide(), RK3_FT::faire_un_pas_de_temps_pb_couple(), fill_ftab_local_reference_frame_velocity(), fill_ftab_velocity(), RK3_FT::iterateTimeStep(), and Transport_Marqueur_FT::transformation().
calculer_vitesse_transport_interpolee() [2/2]
void Transport_Interfaces_FT_Disc::calculer_vitesse_transport_interpolee (const Champ_base & champ_vitesse, const Maillage_FT_Disc & maillage, DoubleTab & vitesse_noeuds, int nv_calc, int standard) const virtual
Calcul de la vitesse de deplacement des noeuds du maillage a partir d'un champ eulerien par interpolation.
Le deplacement fourni n'a aucune propriete particuliere de conservation du volume. Les lignes de contact sont deplacees avec une vitesse qui n'a pas de propriete particuliere non plus...
ATTENTION : on evalue simplement la vitesse a l'endroit ou sont les sommets. Param nv_calc : si =1 : recalcule le champ eulerien de la vitesse par filtrage L2 sinon, reutilise celui stocke dans variables_internes_
References Domaine_32_64< _SIZE_ >::chercher_elements(), collision_model_, Navier_Stokes_FT_Disc::compute_particles_eulerian_id_number(), Maillage_FT_Disc::creer_tableau_sommets(), Maillage_FT_Disc::desc_sommets(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Domaine_dis_base::domaine(), Equation_base::domaine_dis(), Transport_Interfaces_FT_Disc_interne::doubletab_pos, Transport_Interfaces_FT_Disc_interne::doubletab_vitesses, Desc_Structure_FT::echange_espace_virtuel(), Domaine_VF::elem_faces(), Process::exit(), Maillage_FT_Disc::facette_virtuelle(), Maillage_FT_Disc::facettes(), Navier_Stokes_FT_Disc::fluide_diphasique(), Fluide_Diphasique::get_id_fluid_phase(), Navier_Stokes_FT_Disc::get_particles_eulerian_id_number(), Maillage_FT_Disc::get_update_surface_facettes(), gravity_center_elem_, indicatrice_, Transport_Interfaces_FT_Disc_interne::intvect_elements, Transport_Interfaces_FT_Disc_interne::MEAN_VOLUMIC_VELOCITY, Transport_Interfaces_FT_Disc_interne::methode_interpolation_v, Domaine_dis_base::nb_elem(), Maillage_FT_Disc::nb_facettes(), particles_position_collision_, particles_velocity_collision_, Objet_U::que_suis_je(), TRUSTVect< _TYPE_, _SIZE_ >::ref_array(), Transport_Interfaces_FT_Disc_interne::refequation_vitesse_transport, TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), Maillage_FT_Disc::sommet_elem(), Maillage_FT_Disc::sommets(), Navier_Stokes_FT_Disc::swap_particles_eulerian_id_number(), TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), Transport_Interfaces_FT_Disc_interne::VALEUR_A_ELEM, Champ_base::valeur_aux_elems(), Champ_Inc_base::valeurs(), Champ_Proto::valeurs(), Transport_Interfaces_FT_Disc_interne::VDF_LINEAIRE, Transport_Interfaces_FT_Disc_interne::vitesse_filtree, and Domaine_VF::volumes().
calculer_scalaire_interpole()
void Transport_Interfaces_FT_Disc::calculer_scalaire_interpole (const Champ_base & ch_scal, const Maillage_FT_Disc & maillage, DoubleTab & ch_scal_noeuds, int nv_calc) const
DoubleTab & les_vitesses = variables_internes_->doubletab_vitesses;
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Transport_Interfaces_FT_Disc_interne::doubletab_pos, Process::exit(), Transport_Interfaces_FT_Disc_interne::intvect_elements, Transport_Interfaces_FT_Disc_interne::MEAN_VOLUMIC_VELOCITY, Transport_Interfaces_FT_Disc_interne::methode_interpolation_v, Objet_U::que_suis_je(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), Maillage_FT_Disc::sommet_elem(), Maillage_FT_Disc::sommets(), Transport_Interfaces_FT_Disc_interne::VALEUR_A_ELEM, Champ_Proto::valeurs(), and Transport_Interfaces_FT_Disc_interne::VDF_LINEAIRE.
Referenced by Transport_Marqueur_FT::calculer_proprietes_fluide_pos_particules().
remailler_interface()
void Transport_Interfaces_FT_Disc::remailler_interface () virtual
Remaillage de l'interface : - amelioration petites et grandes facettes,.
barycentrage,
gestion des coalescences-fragmentations.
References Transport_Interfaces_FT_Disc_interne::indicatrice_cache, Process::Journal(), Equation_base::le_nom(), maillage_interface(), remaillage_interface(), Topologie_Maillage_FT::remailler_interface(), Equation_base::schema_temps(), Schema_Temps_base::temps_courant(), topologie_interface(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by mettre_a_jour(), and preparer_calcul().
get_champ_post_FT() [1/2]
int Transport_Interfaces_FT_Disc::get_champ_post_FT (const Motcle & champ, Postraitement_base::Localisation loc, DoubleTab * ftab = 0) const virtual
Cherche le champ discret aux interfaces dont le nom est "champ", et verifie qu'il peut etre postraite a la localisation demandee (loc).
Si oui on renvoie 1 et, si ftab est non nul, on remplit le champ ftab avec le champ demande. Si non, on renvoie 0. (la fonction est appelee avec ftab=0 lors de la lecture du postraitement, car on n'a pas besoin de la valeur du champ, on veut seulement verifier qu'il existe).
Reimplemented in Transport_Marqueur_FT.
References Post_Processing_Hydrodynamic_Forces::compute_heat_transfer(), Post_Processing_Hydrodynamic_Forces::compute_hydrodynamic_forces(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_hydrodynamic_forces(), Postraitement_base::demande_description, Postraitement_base::ELEMENTS, Post_Processing_Hydrodynamic_Forces::get_is_compute_forces(), Post_Processing_Hydrodynamic_Forces::get_is_compute_forces_Stokes_th(), Post_Processing_Hydrodynamic_Forces::get_is_compute_heat_transfer(), post_process_hydro_forces_, post_process_hydro_forces_Stokes_, and Postraitement_base::SOMMETS.
Referenced by Maillage_FT_Disc::calcul_courbure_sommets(), Postraitement_ft_lata::postprocess_field_values(), and Postraitement_ft_lata::register_interface_field().
get_champ_post_FT() [2/2]
int Transport_Interfaces_FT_Disc::get_champ_post_FT (const Motcle & champ, Postraitement_base::Localisation loc, IntTab * itab = 0) const virtual
Voir l'autre get_champ_post_FT.
Cette fonction est specifique aux champs d'entiers.
Reimplemented in Transport_Marqueur_FT.
References Postraitement_base::demande_description, Postraitement_base::ELEMENTS, Process::exit(), Maillage_FT_Disc::facette_PE_owner(), Maillage_FT_Disc::intersections_elem_facettes(), maillage_interface_pour_post(), Process::me(), Maillage_FT_Disc::nb_facettes(), Maillage_FT_Disc::nb_sommets(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Motcles::search(), Maillage_FT_Disc::sommet_PE_owner(), and Postraitement_base::SOMMETS.
maillage_interface_pour_post()
const Maillage_FT_Disc & Transport_Interfaces_FT_Disc::maillage_interface_pour_post () const virtual
Renvoie le maillage stocke specialement pour le postraitement (si on veut postraiter un etat intermediaire.
..)
References maillage_interface().
Referenced by Post_Processing_Hydrodynamic_Forces::compute_hydrodynamic_forces(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_hydrodynamic_forces(), fill_ftab_local_reference_frame_velocity(), fill_ftab_normal_unit(), fill_ftab_velocity(), fill_ftab_vertices_curvature(), Post_Processing_Hydrodynamic_Forces_Stokes::fill_sigma_Stokes_th(), get_champ_post_FT(), get_mesh_tag(), and Postraitement_ft_lata::postprocess_field_values().
get_n_iterations_distance()
const int & Transport_Interfaces_FT_Disc::get_n_iterations_distance () const virtual
References Transport_Interfaces_FT_Disc_interne::n_iterations_distance.
Referenced by Convection_Diffusion_Temperature_FT_Disc::completer().
get_mesh_tag()
int Transport_Interfaces_FT_Disc::get_mesh_tag () const inline override virtual
Implements Transport_Interfaces_base.
References Maillage_FT_Disc::get_mesh_tag(), and maillage_interface_pour_post().
get_probleme_base()
const Probleme_base & Transport_Interfaces_FT_Disc::get_probleme_base () const
References probleme_base_, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Maillage_FT_Disc::calcul_courbure_sommets(), Transport_Marqueur_FT::discretiser(), mettre_a_jour(), Maillage_FT_Disc::nettoyer_noeuds_virtuels_et_frontieres(), preparer_calcul(), and reprendre().
modifier_vpoint_pour_imposer_vit()
void Transport_Interfaces_FT_Disc::modifier_vpoint_pour_imposer_vit (const DoubleTab & inco_val, DoubleTab & vpoint0, DoubleTab & vpoint, const DoubleTab & rho_faces, DoubleTab & terme_source, const double temps, const double dt, const int is_explicite, const double eta) override virtual
Implements Transport_Interfaces_base.
References calcul_indicatrice_faces(), calcul_source(), calcul_vitesse(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Equation_base::domaine_dis(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Process::exit(), Domaine_dis_base::face_voisins(), get_indicatrice_faces(), get_update_indicatrice(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Transport_Interfaces_FT_Disc_interne::LOI_HORAIRE, Transport_Interfaces_FT_Disc_interne::methode_transport, modifie_source(), probleme_base_, Equation_base::solv_masse(), Champ_Don_base::valeurs(), Champ_Proto::valeurs(), Debog::verifier(), Transport_Interfaces_FT_Disc_interne::vimp_regul, vitesse_imp_interp_, and Transport_Interfaces_FT_Disc_interne::VITESSE_IMPOSEE.
calcul_source()
void Transport_Interfaces_FT_Disc::calcul_source (const DoubleTab & inco_val, const DoubleTab & vpoint, const DoubleTab & rho_faces, DoubleTab & source_val, const DoubleTab & vit_imposee, const DoubleTab & indicatrice_faces, const int is_QC, const double dt, const int is_explicite, const double eta)
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Process::exit(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), and Transport_Interfaces_FT_Disc_interne::vimp_regul.
Referenced by modifier_vpoint_pour_imposer_vit().
modifie_source()
void Transport_Interfaces_FT_Disc::modifie_source (DoubleTab & so_modif, const DoubleTab & so_val, const DoubleTab & rho_faces, const int n, const int m, const int is_QC, const DoubleVect & vol_entrelaces, const Solveur_Masse_base & solv_masse)
References Solveur_Masse_base::appliquer(), and TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel().
Referenced by modifier_vpoint_pour_imposer_vit().
calcul_effort_fluide_interface()
void Transport_Interfaces_FT_Disc::calcul_effort_fluide_interface (const DoubleTab & vpoint, const DoubleTab & rho_faces, DoubleTab & source_val, const int is_explicite, const double eta)
References Solveur_Masse_base::appliquer(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Domaine_dis_base::domaine(), Equation_base::domaine_dis(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), get_indicatrice_faces(), TRUSTVect< _TYPE_, _SIZE_ >::get_md_vector(), MD_Vector_base::get_sequential_items_flags(), impr(), Process::Journal(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Domaine_VDF::orientation(), probleme_base_, Equation_base::solv_masse(), and Champ_Proto::valeurs().
impr_effort_fluide_interface()
void Transport_Interfaces_FT_Disc::impr_effort_fluide_interface (DoubleTab & source_val, DoubleTab & pressure_part, DoubleTab & friction_part, DoubleTab & diff_part)
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Equation_base::domaine_dis(), get_indicatrice_faces(), TRUSTVect< _TYPE_, _SIZE_ >::get_md_vector(), MD_Vector_base::get_sequential_items_flags(), Schema_Temps_base::imprimer_temps_courant(), Process::je_suis_maitre(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Domaine_VDF::orientation(), Sortie_Fichier_base::precision(), Equation_base::schema_temps(), and Champ_Proto::valeurs().
calcul_vitesse()
void Transport_Interfaces_FT_Disc::calcul_vitesse (DoubleTab & vitesse_imp, const DoubleTab & champ_vitesse, const DoubleTab & vpoint, const double temps, const double dt) virtual
References Transport_Interfaces_FT_Disc_interne::BASE, Operateur::calculer_pas_de_temps(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Equation_base::domaine_dis(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Parser::eval(), Process::exit(), Transport_Interfaces_FT_Disc_interne::expression_vitesse_imposee, Domaine_dis_base::face_voisins(), get_update_distance_interface_faces(), Transport_Interfaces_FT_Disc_interne::interpolation_champ_face, interpoler_vitesse_face(), Equation_base::le_schema_en_temps, Transport_Interfaces_FT_Disc_interne::LINEAIRE, Transport_Interfaces_FT_Disc_interne::LOI_HORAIRE, Transport_Interfaces_FT_Disc_interne::loi_horaire_, Transport_Interfaces_FT_Disc_interne::methode_transport, Process::mp_min(), Transport_Interfaces_FT_Disc_interne::n_iterations_interpolation_ibc, Equation_base::nombre_d_operateurs(), Equation_base::operateur(), Domaine_VDF::orientation(), probleme_base_, TRUSTTab< _TYPE_, _SIZE_ >::resize(), Parser::setVar(), Champ_Proto::valeurs(), Debog::verifier(), Transport_Interfaces_FT_Disc_interne::vf_explicite, and Transport_Interfaces_FT_Disc_interne::VITESSE_IMPOSEE.
Referenced by modifier_vpoint_pour_imposer_vit().
get_expression_vitesse_imposee()
void Transport_Interfaces_FT_Disc::get_expression_vitesse_imposee (DoubleTab & vitesse_imp) virtual
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Equation_base::domaine_dis(), Parser::eval(), Transport_Interfaces_FT_Disc_interne::expression_vitesse_imposee, Domaine_VF::face_voisins(), Equation_base::le_schema_en_temps, Domaine_VDF::orientation(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Parser::setVar(), and Domaine_VF::xv().
integrer_ensemble_lagrange()
void Transport_Interfaces_FT_Disc::integrer_ensemble_lagrange (const double temps) override virtual
Implements Transport_Interfaces_base.
Reimplemented in Transport_Marqueur_FT.
References Process::exit().
interpoler_vitesse_face()
void Transport_Interfaces_FT_Disc::interpoler_vitesse_face (const DoubleTab & distance_interface, const int phase, const int stencil_width, DoubleTab & champ, DoubleTab & gradient, const double t, const double dt) virtual
--— variables pour post-traitement
References Domaine_32_64< _SIZE_ >::creer_tableau_elements(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Transport_Interfaces_FT_Disc_interne::DIST_MODIFIEE, Domaine_dis_base::domaine(), Equation_base::domaine_dis(), Domaine_VF::elem_faces(), Transport_Interfaces_FT_Disc_interne::expression_vitesse_imposee, Domaine_VF::face_voisins(), get_compute_indicatrice_faces(), get_update_indicatrice(), maillage_interface(), Domaine_dis_base::nb_elem(), Domaine_dis_base::nb_elem_tot(), Domaine_VDF::orientation(), Champ_Proto::valeurs(), Domaine_VF::xp(), and Domaine_VF::xv().
Referenced by calcul_vitesse().
interpoler_simple_vitesse_face()
void Transport_Interfaces_FT_Disc::interpoler_simple_vitesse_face (const DoubleTab & distance_interface, const int phase, const int stencil_width, DoubleTab & champ, DoubleTab & gradient, const double t, const double dt)
calcul_nb_traverse()
void Transport_Interfaces_FT_Disc::calcul_nb_traverse (const DoubleTab & xe, const double dx, const int dim, const int ori, Maillage_FT_Disc & maillage, int elem, int & traverse) virtual
References Intersections_Elem_Facettes::data_intersection(), Process::exit(), Maillage_FT_Disc::facettes(), Maillage_FT_Disc::get_update_normale_facettes(), Intersections_Elem_Facettes::index_elem(), Intersections_Elem_Facettes_Data::index_facette_suivante_, Maillage_FT_Disc::intersections_elem_facettes(), Intersections_Elem_Facettes_Data::numero_facette_, Objet_U::precision_geom, and Maillage_FT_Disc::sommets().
calcul_OutElemFa7()
void Transport_Interfaces_FT_Disc::calcul_OutElemFa7 (Maillage_FT_Disc & maillage, const DoubleTab & indicatrice, const int nb_elem, int & nb_fa7_accepted, IntList & OutElem, IntList & OutFa7) virtual
References TRUSTList< _TYPE_ >::add(), TRUSTList< _TYPE_ >::add_if_not(), TRUSTList< _TYPE_ >::contient(), Intersections_Elem_Facettes::data_intersection(), Maillage_FT_Disc::get_update_surface_facettes(), Intersections_Elem_Facettes::index_elem(), Intersections_Elem_Facettes_Data::index_facette_suivante_, Maillage_FT_Disc::intersections_elem_facettes(), Intersections_Elem_Facettes_Data::numero_facette_, and TRUSTList< _TYPE_ >::size().
PPP_face_interface()
void Transport_Interfaces_FT_Disc::PPP_face_interface (Maillage_FT_Disc & maillage, const DoubleTab & indicatrice, const DoubleTab & indicatrice_face, DoubleTab & Vertex) virtual
References Intersections_Elem_Facettes::data_intersection(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Equation_base::domaine_dis(), Domaine_VF::face_voisins(), Maillage_FT_Disc::facettes(), Intersections_Elem_Facettes::index_elem(), Intersections_Elem_Facettes_Data::index_facette_suivante_, Maillage_FT_Disc::intersections_elem_facettes(), Domaine_dis_base::nb_elem(), Intersections_Elem_Facettes_Data::numero_facette_, Maillage_FT_Disc::sommets(), and Domaine_VF::xv().
PPP_face_interface_voisin()
void Transport_Interfaces_FT_Disc::PPP_face_interface_voisin (const DoubleTab & indicatrice, const DoubleTab & indicatrice_face, DoubleTab & Vertex, DoubleTab & PPP) virtual
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Equation_base::domaine_dis(), Domaine_VF::elem_faces(), Domaine_VF::face_voisins(), and Domaine_VF::xv().
PPP_face_voisin()
void Transport_Interfaces_FT_Disc::PPP_face_voisin (const DoubleTab & indicatrice, const DoubleTab & indicatrice_face, DoubleTab & PPP) virtual
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Equation_base::domaine_dis(), Domaine_VF::elem_faces(), Domaine_VF::face_voisins(), and Domaine_VF::xv().
calcul_maxfa7()
void Transport_Interfaces_FT_Disc::calcul_maxfa7 (Maillage_FT_Disc & maillage, const DoubleTab & indicatrice, const int nb_elem, int & max_fa7, const int exec_planfa7existan) virtual
References TRUSTList< _TYPE_ >::add(), calcul_eq_plan_facette(), Intersections_Elem_Facettes::data_intersection(), TRUSTListElem< _TYPE_ >::est_vide(), Intersections_Elem_Facettes::index_elem(), Intersections_Elem_Facettes_Data::index_facette_suivante_, Maillage_FT_Disc::intersections_elem_facettes(), Intersections_Elem_Facettes_Data::numero_facette_, and plan_facette_existant().
RenumFa7()
void Transport_Interfaces_FT_Disc::RenumFa7 (DoubleTab & Barycentre, DoubleTab & Tab110, DoubleTab & Tab111, DoubleTab & Tab112, IntTab & Tab12, IntTab & CptFacette, const int nb_facettes, const int nb_facettes_dim) virtual
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), and Objet_U::precision_geom.
StockageFa7() [1/2]
void Transport_Interfaces_FT_Disc::StockageFa7 (Maillage_FT_Disc & maillage, IntTab & CptFacette, DoubleTab & Tab100, DoubleTab & Tab101, DoubleTab & Tab102, DoubleTab & Tab103, DoubleTab & Tab110, DoubleTab & Tab111, DoubleTab & Tab112, IntTab & Tab12, DoubleTab & Barycentre, const DoubleTab & indicatrice, IntList & OutElem, ArrOfBit & fa7, const int exec_planfa7existant) virtual
References TRUSTList< _TYPE_ >::add(), BaryFa7(), calcul_eq_plan_facette(), TRUSTList< _TYPE_ >::contient(), Intersections_Elem_Facettes::data_intersection(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), TRUSTListElem< _TYPE_ >::est_vide(), Process::exit(), Intersections_Elem_Facettes::index_elem(), Intersections_Elem_Facettes_Data::index_facette_suivante_, Maillage_FT_Disc::intersections_elem_facettes(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Intersections_Elem_Facettes_Data::numero_facette_, plan_facette_existant(), and ArrOfBit_32_64< _SIZE_ >::testsetbit().
StockageFa7() [2/2]
void Transport_Interfaces_FT_Disc::StockageFa7 (Maillage_FT_Disc & maillage, DoubleTab & Tab100, DoubleTab & Tab101, DoubleTab & Tab102, DoubleTab & Tab103, DoubleTab & Tab110, DoubleTab & Tab111, DoubleTab & Tab112, IntTab & Tab12, DoubleTab & Barycentre, IntList & OutElem, IntTab & TabOutFa7, ArrOfBit & fa7) virtual
References BaryFa7(), calcul_eq_plan_facette(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), TRUSTList< _TYPE_ >::size(), and ArrOfBit_32_64< _SIZE_ >::testsetbit().
BaryFa7()
void Transport_Interfaces_FT_Disc::BaryFa7 (Maillage_FT_Disc & maillage, const int i_facette, DoubleTab & Barycentre) virtual
References Objet_U::dimension, Maillage_FT_Disc::facettes(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), and Maillage_FT_Disc::sommets().
Referenced by StockageFa7().
plan_facette_existant()
void Transport_Interfaces_FT_Disc::plan_facette_existant (Maillage_FT_Disc & maillage, DoubleList A, DoubleList B, DoubleList C, DoubleList D, const int i_facette, int & test_liste) virtual
References Objet_U::dimension, Maillage_FT_Disc::facettes(), TRUSTList< _TYPE_ >::size(), and Maillage_FT_Disc::sommets().
Referenced by calcul_maxfa7(), and StockageFa7().
calcul_eq_plan_facette() [1/2]
void Transport_Interfaces_FT_Disc::calcul_eq_plan_facette (Maillage_FT_Disc & maillage, const int i_facette, double & a, double & b, double & c, double & d) virtual
References Objet_U::dimension, Maillage_FT_Disc::facettes(), Maillage_FT_Disc::get_update_normale_facettes(), and Maillage_FT_Disc::sommets().
Referenced by calcul_maxfa7(), and StockageFa7().
calcul_eq_plan_facette() [2/2]
void Transport_Interfaces_FT_Disc::calcul_eq_plan_facette (const int i_facette, double & a, double & b, double & c, double & d) virtual
References Objet_U::dimension, Maillage_FT_Disc::facettes(), Maillage_FT_Disc::get_update_normale_facettes(), maillage_interface(), and Maillage_FT_Disc::sommets().
calcul_tolerance_projete_monophasique()
void Transport_Interfaces_FT_Disc::calcul_tolerance_projete_monophasique (const int i_face, const int ori, const int voisin0, const int voisin1, const DoubleTab & indicatrice_face, const DoubleTab & indicatrice, double & tol) virtual
References Objet_U::dimension, Domaine_VDF::distance_face(), Equation_base::domaine_dis(), Domaine_VF::elem_faces(), Domaine_VF::face_voisins(), and Domaine_VDF::orientation().
Referenced by projete_point_face_fluide().
calcul_tolerance_projete_diphasique()
void Transport_Interfaces_FT_Disc::calcul_tolerance_projete_diphasique (const int i_face, const int ori, const int voisin0, const int voisin1, const DoubleTab & indicatrice, double & tol) virtual
References Objet_U::dimension, Domaine_VDF::distance_face(), Equation_base::domaine_dis(), and Domaine_VF::elem_faces().
Referenced by projete_point_face_interface().
verifprojete()
void Transport_Interfaces_FT_Disc::verifprojete (const int monophasique, const double Lref, double d, const DoubleTab & x, const DoubleTab & V, DoubleTab & coord_projete, int & cpt)
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), and Objet_U::precision_geom.
Referenced by projete_point_face_fluide(), and projete_point_face_interface().
uzawa()
void Transport_Interfaces_FT_Disc::uzawa (const double d, const DoubleTab & matrice, const DoubleTab & x, const DoubleTab & secmem, DoubleTab & solution) const virtual
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Transport_Interfaces_FT_Disc_interne::nb_iter_uzawa, and Transport_Interfaces_FT_Disc_interne::seuil_uzawa.
Referenced by projete_point_face_fluide(), and projete_point_face_interface().
projete_point_face_fluide()
void Transport_Interfaces_FT_Disc::projete_point_face_fluide (int & nb_proj_modif, const int dim_fa7, const DoubleTab & indicatrice_face, const DoubleTab & indicatrice, const DoubleTab & dist_face, const double t, const double dt, DoubleTab & Tab100, DoubleTab & Tab101, DoubleTab & Tab102, DoubleTab & Tab103, IntTab & Tab12, IntTab & CptFacette, DoubleTab & v_imp, DoubleTab & Vertex, Parser & parser_x, Parser & parser_y, Parser & parser_z) virtual
References TRUSTList< _TYPE_ >::add(), calcul_tolerance_projete_monophasique(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Equation_base::domaine_dis(), Domaine_VF::elem_faces(), Parser::eval(), Domaine_VF::face_voisins(), Transport_Interfaces_FT_Disc_interne::LOI_HORAIRE, Transport_Interfaces_FT_Disc_interne::loi_horaire_, Transport_Interfaces_FT_Disc_interne::methode_transport, Domaine_VDF::orientation(), Transport_Interfaces_FT_Disc_interne::PROJETE_MODIFIE, Parser::setVar(), ArrOfBit_32_64< _SIZE_ >::testsetbit(), Transport_Interfaces_FT_Disc_interne::type_projete_calcule, uzawa(), verifprojete(), Transport_Interfaces_FT_Disc_interne::VITESSE_IMPOSEE, and Domaine_VF::xv().
projete_point_face_interface()
void Transport_Interfaces_FT_Disc::projete_point_face_interface (int & nb_proj_modif, const int dim_fa7, const DoubleTab & indicatrice_face, const DoubleTab & indicatrice, const DoubleTab & dist_face, const double t, const double dt, DoubleTab & Tab100, DoubleTab & Tab101, DoubleTab & Tab102, DoubleTab & Tab103, IntTab & Tab12, IntTab & CptFacette, DoubleTab & v_imp, DoubleTab & Vertex, Parser & parser_x, Parser & parser_y, Parser & parser_z) virtual
References TRUSTList< _TYPE_ >::add(), calcul_tolerance_projete_diphasique(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Equation_base::domaine_dis(), Domaine_VF::elem_faces(), Parser::eval(), Process::exit(), Domaine_VF::face_voisins(), Transport_Interfaces_FT_Disc_interne::is_extra_diphasique_solide, Transport_Interfaces_FT_Disc_interne::is_extra_solide, Transport_Interfaces_FT_Disc_interne::LOI_HORAIRE, Transport_Interfaces_FT_Disc_interne::loi_horaire_, Transport_Interfaces_FT_Disc_interne::methode_transport, Domaine_VDF::orientation(), Transport_Interfaces_FT_Disc_interne::PROJETE_MODIFIE, Parser::setVar(), ArrOfBit_32_64< _SIZE_ >::testsetbit(), uzawa(), verifprojete(), Transport_Interfaces_FT_Disc_interne::VITESSE_IMPOSEE, and Domaine_VF::xv().
transporter_sans_changement_topologie()
void Transport_Interfaces_FT_Disc::transporter_sans_changement_topologie (DoubleTab & vitesse, const double coeff, const double temps) virtual
References Champ_Inc_base::changer_temps(), Maillage_FT_Disc::changer_temps(), Maillage_FT_Disc::desc_sommets(), get_update_distance_interface(), get_update_indicatrice(), get_update_normale_interface(), indicatrice_, Transport_Interfaces_FT_Disc_interne::indicatrice_cache, maillage_interface(), Maillage_FT_Disc::nb_sommets(), Maillage_FT_Disc::parcourir_maillage(), Maillage_FT_Disc::preparer_tableau_avant_transport(), Maillage_FT_Disc::transporter(), Maillage_FT_Disc::update_tableau_apres_transport(), Champ_Inc_base::valeurs(), and Champ_Proto::valeurs().
Referenced by RK3_FT::faire_un_pas_de_temps_pb_couple(), and RK3_FT::iterateTimeStep().
calculer_composantes_connexes_pour_suppression()
int Transport_Interfaces_FT_Disc::calculer_composantes_connexes_pour_suppression (IntVect & num_compo) virtual
References Topologie_Maillage_FT::calculer_composantes_connexes_pour_suppression(), Equation_base::domaine_dis(), get_update_indicatrice(), topologie_interface(), and Champ_Proto::valeurs().
Referenced by Transport_Marqueur_FT::transformation().
suppression_interfaces()
double Transport_Interfaces_FT_Disc::suppression_interfaces (const IntVect & num_compo, const ArrOfInt & flags_compo_a_supprimer) virtual
References Transport_Interfaces_FT_Disc_interne::indicatrice_cache, maillage_interface(), Topologie_Maillage_FT::suppression_interfaces(), topologie_interface(), and Champ_Inc_base::valeurs().
Referenced by Transport_Marqueur_FT::transformation().
get_vimp_regul()
const int & Transport_Interfaces_FT_Disc::get_vimp_regul () const
References Transport_Interfaces_FT_Disc_interne::vimp_regul.
get_update_distance_interface()
const Champ_base & Transport_Interfaces_FT_Disc::get_update_distance_interface () const virtual
Calcule et renvoie la distance a l'interface, evaluee sur une epaisseur egale a n_iterations_distance aux elements et discretisee aux elements.
References calculer_distance_interface(), Transport_Interfaces_FT_Disc_interne::distance_interface, Transport_Interfaces_FT_Disc_interne::distance_normale_cache_tag, Maillage_FT_Disc::get_mesh_tag(), maillage_interface(), Transport_Interfaces_FT_Disc_interne::n_iterations_distance, Transport_Interfaces_FT_Disc_interne::normale_interface, TRUST_Deriv< _CLASSE_ >::valeur(), and Champ_Don_base::valeurs().
Referenced by Maillage_FT_Disc::calcul_indicatrice(), Navier_Stokes_FT_Disc::calculer_delta_u_interface(), Navier_Stokes_FT_Disc::calculer_div_normale_interface(), Convection_Diffusion_Temperature_FT_Disc::calculer_grad_t(), Senseur_Interface::calculer_position(), Convection_Diffusion_Temperature_FT_Disc::compute_divergence_free_velocity_extension(), Convection_Diffusion_Temperature_FT_Disc::correct_mpoint(), get_update_distance_interface_faces(), get_update_distance_interface_sommets(), lire_maillage_ft_cao(), mettre_a_jour(), preparer_calcul(), and transporter_sans_changement_topologie().
get_update_distance_interface_faces()
const Champ_base & Transport_Interfaces_FT_Disc::get_update_distance_interface_faces () const virtual
References calculer_distance_interface_faces(), Transport_Interfaces_FT_Disc_interne::distance_faces_cache_tag, Transport_Interfaces_FT_Disc_interne::distance_interface_faces, Maillage_FT_Disc::get_mesh_tag(), get_update_distance_interface(), get_update_normale_interface(), maillage_interface(), TRUST_Deriv< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), and Champ_Proto::valeurs().
Referenced by calcul_indicatrice_faces(), and calcul_vitesse().
get_update_normale_interface()
const Champ_base & Transport_Interfaces_FT_Disc::get_update_normale_interface () const virtual
Calcule et renvoie la normale a l'interface, evaluee sur une epaisseur egale a n_iterations_distance aux elements et discretisee aux elements.
References calculer_distance_interface(), Transport_Interfaces_FT_Disc_interne::distance_interface, Transport_Interfaces_FT_Disc_interne::distance_normale_cache_tag, Maillage_FT_Disc::get_mesh_tag(), maillage_interface(), Transport_Interfaces_FT_Disc_interne::n_iterations_distance, Transport_Interfaces_FT_Disc_interne::normale_interface, TRUST_Deriv< _CLASSE_ >::valeur(), and Champ_Don_base::valeurs().
Referenced by calcul_indicatrice_faces(), Navier_Stokes_FT_Disc::calculer_delta_u_interface(), Convection_Diffusion_Temperature_FT_Disc::calculer_grad_t(), Senseur_Interface::calculer_position(), get_update_distance_interface_faces(), get_update_distance_interface_sommets(), mettre_a_jour(), preparer_calcul(), ramasse_miettes(), and transporter_sans_changement_topologie().
get_update_distance_interface_sommets()
const DoubleTab & Transport_Interfaces_FT_Disc::get_update_distance_interface_sommets () const virtual
Renvoi de la distance signee entre l'interface et les sommets du maillage eulerien.
Si cette distance n'a pas encore ete calculee, appel a calculer_distance_interface_sommets. C'est un DoubleTab parce qu'il n'existe pas (encore) de champ aux sommets en VDF ...
References calculer_distance_interface_sommets(), Transport_Interfaces_FT_Disc_interne::distance_interface_sommets, Transport_Interfaces_FT_Disc_interne::distance_sommets_cache_tag, Maillage_FT_Disc::get_mesh_tag(), get_update_distance_interface(), get_update_normale_interface(), maillage_interface(), and Champ_Proto::valeurs().
Referenced by Navier_Stokes_FT_Disc::derivee_en_temps_inco(), and Remailleur_Collision_FT_Juric::traite_RuptureCoalescenceInterfaces().
ramasse_miettes()
void Transport_Interfaces_FT_Disc::ramasse_miettes (const Maillage_FT_Disc & maillage, DoubleVect & flux, DoubleVect & valeurs)
References Objet_U::dimension, Domaine_dis_base::domaine(), Equation_base::domaine_dis(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_VF::elem_faces(), Domaine_VF::face_normales(), Domaine_VF::face_voisins(), get_update_indicatrice(), get_update_normale_interface(), Domaine_32_64< _SIZE_ >::nb_faces_elem(), Domaine_VF::nb_faces_tot(), and Champ_Proto::valeurs().
Referenced by deplacer_maillage_ft_v_fluide().
nettoyer_maillage()
void Transport_Interfaces_FT_Disc::nettoyer_maillage () inline
References maillage_interface(), and Maillage_FT_Disc::nettoyer_maillage().
transfert_conservatif_eulerien_vers_lagrangien_sommets()
void Transport_Interfaces_FT_Disc::transfert_conservatif_eulerien_vers_lagrangien_sommets (const Maillage_FT_Disc & maillage, const DoubleVect & valeurs_euler, ArrOfDouble & valeurs_lagrange) static
References Intersections_Elem_Facettes_Data::barycentre_, Desc_Structure_FT::collecter_espace_virtuel(), Intersections_Elem_Facettes::data_intersection(), Maillage_FT_Disc::desc_sommets(), Objet_U::dimension, Desc_Structure_FT::echange_espace_virtuel(), MD_Vector_tools::EV_SOMME, Maillage_FT_Disc::facettes(), Intersections_Elem_Facettes_Data::fraction_surface_intersection_, Maillage_FT_Disc::get_update_surface_facettes(), Intersections_Elem_Facettes::index_elem(), Intersections_Elem_Facettes_Data::index_facette_suivante_, Maillage_FT_Disc::intersections_elem_facettes(), Maillage_FT_Disc::nb_sommets(), Intersections_Elem_Facettes_Data::numero_facette_, TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), TRUSTVect< _TYPE_, _SIZE_ >::size(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by IJK_Interfaces::calculer_var_volume_remaillage(), and deplacer_maillage_ft_v_fluide().
get_set_collision_model()
Collision_Model_FT_base & Transport_Interfaces_FT_Disc::get_set_collision_model () inline
References collision_model_, and TRUST_Deriv< _CLASSE_ >::valeur().
get_nb_particles_tot()
const int & Transport_Interfaces_FT_Disc::get_nb_particles_tot () const inline
Referenced by Maillage_FT_Disc::calcul_indicatrice().
get_collision_model()
const Collision_Model_FT_base & Transport_Interfaces_FT_Disc::get_collision_model () const inline
References collision_model_, and TRUST_Deriv< _CLASSE_ >::valeur().
get_ptr_collision_model()
const TRUST_Deriv< Collision_Model_FT_base > & Transport_Interfaces_FT_Disc::get_ptr_collision_model () const inline
References collision_model_.
Referenced by Navier_Stokes_FT_Disc::derivee_en_temps_inco().
get_particles_position()
const DoubleTab & Transport_Interfaces_FT_Disc::get_particles_position () const inline
References particles_position_collision_.
Referenced by Post_Processing_Hydrodynamic_Forces::compute_friction_force_projected_tensor(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_friction_force_projected_tensor(), Post_Processing_Hydrodynamic_Forces::compute_viscosity_edges_sphere(), and Collision_Model_FT_base::research_collision_pairs_Verlet().
get_particles_velocity()
const DoubleTab & Transport_Interfaces_FT_Disc::get_particles_velocity () const inline
References particles_velocity_collision_.
Referenced by Post_Processing_Hydrodynamic_Forces::compute_friction_force_projected_tensor(), and Collision_Model_FT_base::research_collision_pairs_Verlet().
get_gravity_center_elem()
const ArrOfInt & Transport_Interfaces_FT_Disc::get_gravity_center_elem () const inline
References gravity_center_elem_.
Referenced by Collision_Model_FT_base::research_collision_pairs_Verlet().
get_post_process_hydro_forces()
Post_Processing_Hydrodynamic_Forces & Transport_Interfaces_FT_Disc::get_post_process_hydro_forces () inline
References post_process_hydro_forces_.
associate_temp_equation_post_processing()
void Transport_Interfaces_FT_Disc::associate_temp_equation_post_processing (TRUST_Ref< Convection_Diffusion_Temperature_FT_Disc * > ref_eq_temp) inline
References Post_Processing_Hydrodynamic_Forces::associate_temp_equation(), and post_process_hydro_forces_.
get_is_solid_particle()
const bool & Transport_Interfaces_FT_Disc::get_is_solid_particle () const inline
References is_solid_particle_.
calculer_vmoy_composantes_connexes()
void Transport_Interfaces_FT_Disc::calculer_vmoy_composantes_connexes (const Maillage_FT_Disc & maillage, const ArrOfInt & compo_connexes_facettes, const int nb_compo_tot, const DoubleTab & vitesse_sommets, DoubleTab & vitesses, DoubleTab & positions) const protected virtual
Calcul de la derivee par rapport au temps du volume de phase 1 aux sommets du maillage lagrangien a partir du champ de vitesse.
eulerien. On utilise le fait que le champ eulerien est a divergence nulle Cette grandeur permet de corriger le deplacement des sommets pour conserver le volume des phases (voir these B.M. paragraphe 3.2.10). On a I = rho_0 + (rho_1-rho_0) * I. Donc: drho/dt = (rho_1-rho_0) * dI/dt (d'une part) = div(rho*u) = div((rho_0 + (rho_1-rho_0)*I) * u) (d'autre part) Donc, si div(u) = 0 dI/dt = div(I * u) Si non (changement de phase): dI/dt = div((rho_0/(rho_1-rho_0) + I) * u) Parametre : vitesse Signification: le champ de vitesse eulerien aux faces du maillage. si vitesse.dimension(1)==1, on suppose que c'est la composante normale a la face de la vitesse, sinon on suppose que c'est le vecteur vitesse 2d ou 3d. Parametre : indicatrice Signification: indicatrice de phase aux elements euleriens. doit avoir son espace virtuel a jour et correspondre au maillage suivant... Parametre : maillage Signification : le maillage de l'interface, doit etre parcouru. Parametre : rho_0_sur_delta_rho_div_u Signification: resultat de l'operateur div(u) aux elements (integrale de div_u sur les elements. Si ce tableau est de taille non nulle, on ajoute le terme en div_u Parametre : var_volume Signification : Tableau ou on stocke la variation de volume de phase 1 pour chaque sommet du maillage lagrangien.
References Domaine_32_64< _SIZE_ >::chercher_elements(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Domaine_dis_base::domaine(), Equation_base::domaine_dis(), Maillage_FT_Disc::facette_virtuelle(), Maillage_FT_Disc::facettes(), Maillage_FT_Disc::get_update_normale_facettes(), Maillage_FT_Disc::get_update_surface_facettes(), gravity_center_elem_, is_solid_particle_, TRUSTVect< _TYPE_, _SIZE_ >::line_size(), particles_position_collision_, particles_velocity_collision_, TRUSTVect< _TYPE_, _SIZE_ >::ref_array(), and Maillage_FT_Disc::sommets().
Referenced by calculer_vitesse_repere_local().
ajouter_contribution_saut_vitesse()
void Transport_Interfaces_FT_Disc::ajouter_contribution_saut_vitesse (DoubleTab & deplacement) const protected
References calculer_vitesse_transport_interpolee(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Navier_Stokes_FT_Disc::get_delta_vitesse_interface(), Navier_Stokes_FT_Disc::get_new_mass_source(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), maillage_interface(), Transport_Interfaces_FT_Disc_interne::refequation_vitesse_transport, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by deplacer_maillage_ft_v_fluide(), fill_ftab_local_reference_frame_velocity(), and fill_ftab_velocity().
deplacer_maillage_ft_v_fluide()
void Transport_Interfaces_FT_Disc::deplacer_maillage_ft_v_fluide (const double temps) protected virtual
References ajouter_contribution_saut_vitesse(), Navier_Stokes_FT_Disc::calculer_dI_dt(), calculer_integrale_indicatrice(), Remaillage_FT::calculer_variation_volume(), calculer_vitesse_repere_local(), calculer_vitesse_transport_interpolee(), Maillage_FT_Disc::changer_temps(), collision_model_, Maillage_FT_Disc::compute_gravity_center_fa7(), Remaillage_FT::corriger_volume_(), Domaine_32_64< _SIZE_ >::creer_tableau_elements(), Transport_Interfaces_FT_Disc_interne::deplacement_sommets, Maillage_FT_Disc::desc_sommets(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Domaine_dis_base::domaine(), Equation_base::domaine_dis(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Maillage_FT_Disc::facettes(), Navier_Stokes_FT_Disc::get_delta_vitesse_interface(), Maillage_FT_Disc::get_update_surface_facettes(), Equation_base::inconnue(), indicatrice_, Process::je_suis_maitre(), Process::Journal(), Remaillage_FT::lisser_dvolume(), maillage_interface(), Process::mp_sum(), Domaine_dis_base::nb_elem(), Sous_Domaine_32_64< _SIZE_ >::nb_elem_tot(), Maillage_FT_Disc::nb_facettes(), Transport_Interfaces_FT_Disc_interne::nb_iterations_correction_volume, Transport_Interfaces_FT_Disc_interne::nb_lissage_correction_volume, Maillage_FT_Disc::nb_sommets(), Transport_Interfaces_FT_Disc_interne::nom_domaine_volume_impose_, Objet_U_ptr::non_nul(), Maillage_FT_Disc::preparer_tableau_avant_transport(), ramasse_miettes(), Transport_Interfaces_FT_Disc_interne::refequation_vitesse_transport, remaillage_interface(), Equation_base::schema_temps(), Maillage_FT_Disc::sommets(), Domaine_32_64< _SIZE_ >::ss_domaine(), swap_particles_lagrangian_position_velocity(), Maillage_FT_Disc::temps(), Schema_Temps_base::temps_courant(), Transport_Interfaces_FT_Disc_interne::tmp_flux, Remaillage_FT::traite_adherence(), Remaillage_FT::traite_decollement(), transfert_conservatif_eulerien_vers_lagrangien_sommets(), Maillage_FT_Disc::transporter(), Maillage_FT_Disc::update_tableau_apres_transport(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), Champ_Inc_base::valeurs(), Transport_Interfaces_FT_Disc_interne::VOFlike_correction_volume, Transport_Interfaces_FT_Disc_interne::volume_impose_phase_1, and Domaine_VF::volumes().
Referenced by mettre_a_jour().
calculer_distance_interface()
void Transport_Interfaces_FT_Disc::calculer_distance_interface (const Maillage_FT_Disc & maillage, DoubleTab & distance_elements, DoubleTab & normale_elements, const int n_iter) const protected virtual
Calcul d'un champ scalaire aux elements contenant une distance signee entre le centre de l'element et l'interface.
La distance est positive dans la phase 1 et negative dans la phase 0. On calcule aussi un champ vectoriel aux elements contenant une normale a l'interface. Ce champ est evalue en resolvant moralement laplacien(normale) = gradient(indicatrice) ou gradient(indicatrice) est le gradient de l'indicatrice continue c'est a dire un dirac localise a la surface de l'interface. Pour l'instant, cette normale est calculee de facon approchee avec quelques iterations d'un lisseur. Le support est donc limite au voisinage de l'interface. Pour les autres elements, la distance vaut -1.e30 Precondition : le maillage doit etre parcouru
References TRUSTArray< _TYPE_, _SIZE_ >::append_array(), Intersections_Elem_Facettes_Data::barycentre_, Statistiques::begin_count(), Intersections_Elem_Facettes::data_intersection(), Objet_U::dimension, Domaine_dis_base::domaine(), Equation_base::domaine_dis(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_VF::elem_faces(), Statistiques::end_count(), Domaine_VF::face_voisins(), Maillage_FT_Disc::facettes(), Intersections_Elem_Facettes_Data::fraction_surface_intersection_, Maillage_FT_Disc::get_update_normale_facettes(), Maillage_FT_Disc::get_update_surface_facettes(), Intersections_Elem_Facettes::index_elem(), Intersections_Elem_Facettes_Data::index_facette_suivante_, Maillage_FT_Disc::intersections_elem_facettes(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Domaine_32_64< _SIZE_ >::nb_elem(), Statistiques::new_counter(), Intersections_Elem_Facettes_Data::numero_facette_, TRUSTArray< _TYPE_, _SIZE_ >::size_array(), Maillage_FT_Disc::sommets(), Debog::verifier(), and Domaine_VF::xp().
Referenced by get_update_distance_interface(), and get_update_normale_interface().
calculer_distance_interface_sommets()
void Transport_Interfaces_FT_Disc::calculer_distance_interface_sommets (const DoubleTab & dist_elem, const DoubleTab & normale_elem, DoubleTab & dist_som) const protected virtual
Calcule dist_som, la distance entre l'interface et les sommets du maillage eulerien a partir de dist_elem et normale_elem,.
distance et normale a l'interface aux centres des elements euleriens. Pour un element, on evalue la distance entre chaque sommet de l'element et l'interface comme : d = d1 + d2, d2 = normale scalaire (position_sommet - centre_element) d1 est la distance entre l'interface et le centre de l'element, normale est la normale a l'interface evaluee au centre de l'element Ensuite, la distance entre un sommet et l'interface est la moyenne de toutes les distances calculee a l'aide des elements adjacents a ce sommet. La distance est invalide au-dela d'une certaine epaisseur autour de l'interface (voir iterations de lissage dans calculer_distance_interface). Dans ce cas on met une distance de +1e30 si l'indicatrice est >0.5, sinon on met -1e30 (ce choix permet d'utiliser la fonction distance dans les marching-cubes sans avoir a calculer une vraie distance partout). Parametre : dist_elem Signification : tableau contenant pour chaque element reel et virtuel la distance entre l'interface et le centre de l'element (calculee par calculer_distance_interface). L'espace virtuel doit etre a jour. Parametre : normale_elem Signification : idem pour la normale a l'interface Parametre : dist_som Signification : tableau ou on stocke le resultat du calcul. Le tableau doit avoir la bonne taille et un descripteur adequat (voir "discretiser", a priori un tableau avec une epaisseur de joint de zero et uniquement des items communs).
References Objet_U::dimension, TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Domaine_dis_base::domaine(), Equation_base::domaine_dis(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_32_64< _SIZE_ >::les_elems(), Domaine_32_64< _SIZE_ >::les_sommets(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Debog::verifier(), and Domaine_VF::xp().
Referenced by get_update_distance_interface_sommets().
calculer_vitesse_repere_local()
void Transport_Interfaces_FT_Disc::calculer_vitesse_repere_local (const Maillage_FT_Disc & maillage, DoubleTab & deplacement, DoubleTab & Positions, DoubleTab & Vitesses) const protected virtual
References calculer_vmoy_composantes_connexes(), Maillage_FT_Disc::creer_tableau_sommets(), Objet_U::dimension, Maillage_FT_Disc::facettes(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Maillage_FT_Disc::nb_facettes(), and TRUSTTab< _TYPE_, _SIZE_ >::resize().
Referenced by deplacer_maillage_ft_v_fluide(), and fill_ftab_local_reference_frame_velocity().
test_suppression_interfaces_sous_domaine()
void Transport_Interfaces_FT_Disc::test_suppression_interfaces_sous_domaine () protected virtual
References TRUSTArray< _TYPE_, _SIZE_ >::append_array(), Topologie_Maillage_FT::calculer_composantes_connexes_pour_suppression(), Domaine_dis_base::domaine(), Equation_base::domaine_dis(), Probleme_base::equation(), Topologie_Maillage_FT::get_phase_continue(), get_update_indicatrice(), Transport_Interfaces_FT_Disc_interne::indicatrice_cache, maillage_interface(), Process::mp_sum(), Sous_Domaine_32_64< _SIZE_ >::nb_elem_tot(), Probleme_base::nombre_d_equations(), Equation_base::probleme(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), Domaine_32_64< _SIZE_ >::ss_domaine(), Convection_Diffusion_Temperature_FT_Disc::suppression_interfaces(), Topologie_Maillage_FT::suppression_interfaces(), suppression_interfaces_sous_domaine_, topologie_interface(), Champ_Inc_base::valeurs(), and Champ_Proto::valeurs().
Referenced by mettre_a_jour().
calculer_distance_interface_faces()
void Transport_Interfaces_FT_Disc::calculer_distance_interface_faces (const DoubleTab & dist_elem, const DoubleTab & normale_elem, DoubleTab & dist_faces) const protected virtual
References Statistiques::begin_count(), Objet_U::dimension, TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Equation_base::domaine_dis(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_VF::elem_faces(), Statistiques::end_count(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Statistiques::new_counter(), Domaine_VF::xp(), and Domaine_VF::xv().
Referenced by get_update_distance_interface_faces().
calcul_indicatrice_faces()
void Transport_Interfaces_FT_Disc::calcul_indicatrice_faces (const DoubleTab & indicatrice, const IntTab & face_voisins) protected
References Transport_Interfaces_FT_Disc_interne::AI_BASED, TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Equation_base::domaine_dis(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Process::exit(), Domaine_VF::face_normales(), Domaine_VF::face_surfaces(), Navier_Stokes_FT_Disc::get_interfacial_area(), get_update_distance_interface_faces(), get_update_normale_interface(), Navier_Stokes_std::inconnue(), indicatrice_faces_, TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Transport_Interfaces_FT_Disc_interne::modified_indic_faces_position, Transport_Interfaces_FT_Disc_interne::modified_indic_faces_thickness, Transport_Interfaces_FT_Disc_interne::MODIFIEE, Domaine_VDF::orientation(), Transport_Interfaces_FT_Disc_interne::refequation_vitesse_transport, Transport_Interfaces_FT_Disc_interne::STANDARD, Transport_Interfaces_FT_Disc_interne::type_indic_faces_, TRUST_Ref< _CLASSE_ >::valeur(), Champ_Inc_base::valeurs(), Champ_Proto::valeurs(), Debog::verifier(), and Domaine_VF::volumes_entrelaces().
Referenced by get_compute_indicatrice_faces(), and modifier_vpoint_pour_imposer_vit().
get_mean_particles_volumic_velocity()
const DoubleTab & Transport_Interfaces_FT_Disc::get_mean_particles_volumic_velocity () const inline protected
References mean_particles_volumic_velocity_.
Referenced by impr().
get_mean_particles_volumic_squared_velocity()
const DoubleTab & Transport_Interfaces_FT_Disc::get_mean_particles_volumic_squared_velocity () const inline protected
References mean_particles_volumic_squared_velocity_.
Referenced by impr().
get_rms_particles_volumic_velocity()
const DoubleTab & Transport_Interfaces_FT_Disc::get_rms_particles_volumic_velocity () const inline protected
References rms_particles_volumic_velocity_.
Referenced by impr().
get_particles_purely_solid_mesh_volume()
const DoubleTab & Transport_Interfaces_FT_Disc::get_particles_purely_solid_mesh_volume () const inline protected
References particles_purely_solid_mesh_volume_.
Referenced by impr().
set_is_solid_particle()
void Transport_Interfaces_FT_Disc::set_is_solid_particle (const bool is_solid_particle) inline protected
References is_solid_particle_.
Referenced by lire_motcle_non_standard().
init_particles_position_velocity()
void Transport_Interfaces_FT_Disc::init_particles_position_velocity () protected
References Domaine_32_64< _SIZE_ >::chercher_elements(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Domaine_dis_base::domaine(), Equation_base::domaine_dis(), Maillage_FT_Disc::facette_virtuelle(), Maillage_FT_Disc::facettes(), Maillage_FT_Disc::get_update_surface_facettes(), gravity_center_elem_, maillage_interface(), Maillage_FT_Disc::nb_facettes(), particles_position_collision_, particles_velocity_collision_, TRUSTVect< _TYPE_, _SIZE_ >::ref_array(), Transport_Interfaces_FT_Disc_interne::refequation_vitesse_transport, TRUSTTab< _TYPE_, _SIZE_ >::resize(), Maillage_FT_Disc::sommets(), Navier_Stokes_FT_Disc::swap_particles_eulerian_id_number(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by preparer_calcul().
swap_particles_lagrangian_position_velocity()
void Transport_Interfaces_FT_Disc::swap_particles_lagrangian_position_velocity () protected
WARNING, particles_position_collision_ and particles_velocity_collision_ are not used to transport particles but only for the computation of contact forces. Thus, be aware that tables Vitesses and Positions from the method calculer_vitesse_repere_local() are different from those of the present method. Indeed, it is not required to conserve the same lagrangian number to transport particles. To merge tables from both methods, one should modify the following methods: search_connex_components_local_FT and compute_global_connex_components_FT. If a particle is numbered 0 by proc 0, its global Lagrangian number will be 0. However, if it passes to proc 1 and is assigned the number 0, its global number will be 0 + the number of particles of proc 0. This method swap rows of particles_position_collision_ and particles_velocity_collision_ to conserve the particles lagrangian ID number between two successive times steps using the particles eulerian ID number. Indeed, after calling the function search_connex_components_local_FT and compute_global_connex_components_FT, their lagrangian number has changed. The method is base on the assumption that the element in which the gravity center of a given particle conserve its eulerian ID number between two successive time steps, which is always verified for resolved particles. We then attribute the eulerian ID number of this elem to the lagrangian particle ID number by swapping table rows. /!\ /!\ /!\ At the moment, this method is performed sequentially only All processors know the tables particles_position_collision_ and particles_velocity_collision_.
References Collision_Model_FT_base::check_for_duplicates(), Domaine_32_64< _SIZE_ >::chercher_elements(), collision_model_, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Domaine_dis_base::domaine(), Equation_base::domaine_dis(), Process::exit(), Navier_Stokes_FT_Disc::get_particles_eulerian_id_number(), gravity_center_elem_, particles_position_collision_, particles_velocity_collision_, Transport_Interfaces_FT_Disc_interne::refequation_vitesse_transport, TRUST_Deriv< _CLASSE_ >::valeur(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by deplacer_maillage_ft_v_fluide().
compute_particles_rms()
void Transport_Interfaces_FT_Disc::compute_particles_rms () protected
References Objet_U::dimension, Equation_base::domaine_dis(), Domaine_VF::elem_faces(), Navier_Stokes_FT_Disc::fluide_diphasique(), Fluide_Diphasique::get_id_fluid_phase(), Navier_Stokes_FT_Disc::get_particles_eulerian_id_number(), Navier_Stokes_std::inconnue(), indicatrice_, mean_particles_volumic_squared_velocity_, mean_particles_volumic_velocity_, Domaine_dis_base::nb_elem(), particles_purely_solid_mesh_volume_, TRUSTVect< _TYPE_, _SIZE_ >::ref_array(), Transport_Interfaces_FT_Disc_interne::refequation_vitesse_transport, rms_particles_volumic_velocity_, TRUST_Ref< _CLASSE_ >::valeur(), Champ_Inc_base::valeurs(), and Domaine_VF::volumes().
Referenced by mettre_a_jour().
add_fields_to_post_FT()
void Transport_Interfaces_FT_Disc::add_fields_to_post_FT (Motcles & fields) const protected
fill_ftab_vertices_curvature()
void Transport_Interfaces_FT_Disc::fill_ftab_vertices_curvature (DoubleTab * ftab, const DoubleTab & dummytab) const protected
References Maillage_FT_Disc::get_update_courbure_sommets(), and maillage_interface_pour_post().
fill_ftab_velocity()
void Transport_Interfaces_FT_Disc::fill_ftab_velocity (DoubleTab * ftab, const DoubleTab & dummytab) const protected
References ajouter_contribution_saut_vitesse(), calculer_vitesse_transport_interpolee(), Process::exit(), Navier_Stokes_FT_Disc::get_delta_vitesse_interface(), Equation_base::inconnue(), maillage_interface_pour_post(), TRUST_Ref< _CLASSE_ >::non_nul(), Transport_Interfaces_FT_Disc_interne::refequation_vitesse_transport, and TRUST_Ref< _CLASSE_ >::valeur().
fill_ftab_local_reference_frame_velocity()
void Transport_Interfaces_FT_Disc::fill_ftab_local_reference_frame_velocity (DoubleTab * ftab, const DoubleTab & dummytab) const protected
References ajouter_contribution_saut_vitesse(), calculer_vitesse_repere_local(), calculer_vitesse_transport_interpolee(), Process::exit(), Equation_base::inconnue(), maillage_interface_pour_post(), TRUST_Ref< _CLASSE_ >::non_nul(), Transport_Interfaces_FT_Disc_interne::refequation_vitesse_transport, and TRUST_Ref< _CLASSE_ >::valeur().
fill_ftab_normal_unit()
void Transport_Interfaces_FT_Disc::fill_ftab_normal_unit (DoubleTab * ftab, const DoubleTab & dummytab) const protected
References Maillage_FT_Disc::get_update_normale_facettes(), and maillage_interface_pour_post().
fill_ftab_pressure()
void Transport_Interfaces_FT_Disc::fill_ftab_pressure (DoubleTab * ftab, const DoubleTab & dummytab) const protected
References Post_Processing_Hydrodynamic_Forces::get_is_post_process_pressure_fa7(), Post_Processing_Hydrodynamic_Forces::get_pressure_fa7(), and post_process_hydro_forces_.
fill_ftab_pressure_force()
void Transport_Interfaces_FT_Disc::fill_ftab_pressure_force (DoubleTab * ftab, const DoubleTab & dummytab) const protected
References Post_Processing_Hydrodynamic_Forces::get_is_post_process_pressure_force_fa7(), Post_Processing_Hydrodynamic_Forces::get_pressure_force_fa7(), and post_process_hydro_forces_.
fill_ftab_friction_force()
void Transport_Interfaces_FT_Disc::fill_ftab_friction_force (DoubleTab * ftab, const DoubleTab & dummytab) const protected
References Post_Processing_Hydrodynamic_Forces::get_friction_force_fa7(), Post_Processing_Hydrodynamic_Forces::get_is_post_process_friction_force_fa7(), and post_process_hydro_forces_.
fill_ftab_Stokes_pressure_interp()
void Transport_Interfaces_FT_Disc::fill_ftab_Stokes_pressure_interp (DoubleTab * ftab, const DoubleTab & values) const protected
References Post_Processing_Hydrodynamic_Forces::get_is_compute_forces_Stokes_th(), Post_Processing_Hydrodynamic_Forces::get_pressure_fa7(), and post_process_hydro_forces_Stokes_.
fill_ftab_Stokes_pressure_th()
void Transport_Interfaces_FT_Disc::fill_ftab_Stokes_pressure_th (DoubleTab * ftab, const DoubleTab & values) const protected
References Post_Processing_Hydrodynamic_Forces::get_is_compute_forces_Stokes_th(), Post_Processing_Hydrodynamic_Forces_Stokes::get_pressure_fa7_Stokes_th(), and post_process_hydro_forces_Stokes_.
fill_ftab_Stokes()
void Transport_Interfaces_FT_Disc::fill_ftab_Stokes (DoubleTab * ftab, const DoubleTab & values) const protected
References Post_Processing_Hydrodynamic_Forces::get_is_compute_forces_Stokes_th(), and post_process_hydro_forces_Stokes_.
maillage_interface() [2/2]
Maillage_FT_Disc & Transport_Interfaces_FT_Disc::maillage_interface () protected
References Transport_Interfaces_FT_Disc_interne::maillage_interface.
marching_cubes() [2/2]
Marching_Cubes & Transport_Interfaces_FT_Disc::marching_cubes () protected
References Transport_Interfaces_FT_Disc_interne::marching_cubes_.
topologie_interface() [2/2]
Topologie_Maillage_FT & Transport_Interfaces_FT_Disc::topologie_interface () protected
References Transport_Interfaces_FT_Disc_interne::topologie_interface_.
proprietes_particules() [2/2]
Proprietes_part_vol & Transport_Interfaces_FT_Disc::proprietes_particules () protected
References Transport_Interfaces_FT_Disc_interne::proprietes_particules_.
maillage_inject() [2/2]
Maillage_FT_Disc & Transport_Interfaces_FT_Disc::maillage_inject () protected
References Transport_Interfaces_FT_Disc_interne::maillage_inject_.
proprietes_inject() [2/2]
Proprietes_part_vol & Transport_Interfaces_FT_Disc::proprietes_inject () protected
References Transport_Interfaces_FT_Disc_interne::proprietes_inject_.
tableaux_positions()
DoubleTab & Transport_Interfaces_FT_Disc::tableaux_positions () protected
References Transport_Interfaces_FT_Disc_interne::doubletab_pos.
Referenced by Transport_Marqueur_FT::calculer_proprietes_fluide_pos_particules().
vecteur_elements()
IntVect & Transport_Interfaces_FT_Disc::vecteur_elements () protected
References Transport_Interfaces_FT_Disc_interne::intvect_elements.
Referenced by Transport_Marqueur_FT::calculer_proprietes_fluide_pos_particules().
deplacement_som()
DoubleTab & Transport_Interfaces_FT_Disc::deplacement_som () protected
References Transport_Interfaces_FT_Disc_interne::deplacement_sommets.
Referenced by Transport_Marqueur_FT::integrer_ensemble_lagrange().
Friends And Related Function Documentation
Post_Processing_Hydrodynamic_Forces
friend class Post_Processing_Hydrodynamic_Forces friend
Member Data Documentation
info_obj
const Type_info Transport_Interfaces_FT_Disc::info_obj static
probleme_base_
TRUST_Ref< Probleme_base *> Transport_Interfaces_FT_Disc::probleme_base_ protected
Referenced by associer_pb_base(), calcul_effort_fluide_interface(), calcul_vitesse(), Transport_Marqueur_FT::calcul_vitesse_p(), get_probleme_base(), Transport_Marqueur_FT::integrer_ensemble_lagrange(), lire_motcle_non_standard(), modifier_vpoint_pour_imposer_vit(), and Transport_Marqueur_FT::transformation().
equation_ns_
TRUST_Ref< Navier_Stokes_FT_Disc *> Transport_Interfaces_FT_Disc::equation_ns_ protected
Referenced by associer_equation_ns(), and preparer_calcul().
indicatrice_
TRUST_Deriv< Champ_Inc_base > Transport_Interfaces_FT_Disc::indicatrice_ protected
Referenced by calculer_vitesse_transport_interpolee(), compute_particles_rms(), deplacer_maillage_ft_v_fluide(), discretiser(), inconnue(), mettre_a_jour(), preparer_calcul(), and transporter_sans_changement_topologie().
indicatrice_faces_
TRUST_Deriv< Champ_Inc_base > Transport_Interfaces_FT_Disc::indicatrice_faces_ protected
Referenced by calcul_indicatrice_faces(), discretiser(), get_compute_indicatrice_faces(), get_indicatrice_faces(), and preparer_calcul().
suppression_interfaces_sous_domaine_
Nom Transport_Interfaces_FT_Disc::suppression_interfaces_sous_domaine_ protected
Referenced by readOn(), set_param(), and test_suppression_interfaces_sous_domaine().
vitesse_imp_interp_
TRUST_Deriv< Champ_Fonc_base > Transport_Interfaces_FT_Disc::vitesse_imp_interp_ protected
Referenced by discretiser(), modifier_vpoint_pour_imposer_vit(), and preparer_calcul().
is_solid_particle_
bool Transport_Interfaces_FT_Disc::is_solid_particle_ =false protected
Referenced by calculer_vmoy_composantes_connexes(), get_is_solid_particle(), impr(), mettre_a_jour(), preparer_calcul(), reprendre(), sauvegarder(), and set_is_solid_particle().
compute_particles_rms_
int Transport_Interfaces_FT_Disc::compute_particles_rms_ =0 protected
Referenced by impr(), and set_param().
collision_model_
TRUST_Deriv< Collision_Model_FT_base > Transport_Interfaces_FT_Disc::collision_model_ protected
Referenced by calculer_vitesse_transport_interpolee(), deplacer_maillage_ft_v_fluide(), get_collision_model(), get_ptr_collision_model(), get_set_collision_model(), impr(), mettre_a_jour(), preparer_calcul(), reprendre(), sauvegarder(), set_param(), and swap_particles_lagrangian_position_velocity().
particles_position_collision_
DoubleTab Transport_Interfaces_FT_Disc::particles_position_collision_ mutable protected
Referenced by calculer_vitesse_transport_interpolee(), calculer_vmoy_composantes_connexes(), get_particles_position(), impr(), init_particles_position_velocity(), reprendre(), sauvegarder(), and swap_particles_lagrangian_position_velocity().
particles_velocity_collision_
DoubleTab Transport_Interfaces_FT_Disc::particles_velocity_collision_ mutable protected
Referenced by calculer_vitesse_transport_interpolee(), calculer_vmoy_composantes_connexes(), get_particles_velocity(), impr(), init_particles_position_velocity(), reprendre(), sauvegarder(), and swap_particles_lagrangian_position_velocity().
gravity_center_elem_
ArrOfInt Transport_Interfaces_FT_Disc::gravity_center_elem_ mutable protected
Referenced by calculer_vitesse_transport_interpolee(), calculer_vmoy_composantes_connexes(), get_gravity_center_elem(), init_particles_position_velocity(), mettre_a_jour(), reprendre(), and swap_particles_lagrangian_position_velocity().
mean_particles_volumic_velocity_
DoubleTab Transport_Interfaces_FT_Disc::mean_particles_volumic_velocity_ protected
Referenced by compute_particles_rms(), get_mean_particles_volumic_velocity(), and preparer_calcul().
mean_particles_volumic_squared_velocity_
DoubleTab Transport_Interfaces_FT_Disc::mean_particles_volumic_squared_velocity_ protected
Referenced by compute_particles_rms(), get_mean_particles_volumic_squared_velocity(), and preparer_calcul().
rms_particles_volumic_velocity_
DoubleTab Transport_Interfaces_FT_Disc::rms_particles_volumic_velocity_ protected
Referenced by compute_particles_rms(), get_rms_particles_volumic_velocity(), and preparer_calcul().
particles_purely_solid_mesh_volume_
DoubleTab Transport_Interfaces_FT_Disc::particles_purely_solid_mesh_volume_ protected
Referenced by compute_particles_rms(), get_particles_purely_solid_mesh_volume(), and preparer_calcul().
post_process_hydro_forces_
Post_Processing_Hydrodynamic_Forces Transport_Interfaces_FT_Disc::post_process_hydro_forces_ mutable protected
Referenced by associate_temp_equation_post_processing(), fill_ftab_friction_force(), fill_ftab_pressure(), fill_ftab_pressure_force(), get_champ_post_FT(), get_post_process_hydro_forces(), impr(), mettre_a_jour(), preparer_calcul(), and set_param().
post_process_hydro_forces_Stokes_
Post_Processing_Hydrodynamic_Forces_Stokes Transport_Interfaces_FT_Disc::post_process_hydro_forces_Stokes_ mutable protected
Referenced by fill_ftab_Stokes(), fill_ftab_Stokes_pressure_interp(), fill_ftab_Stokes_pressure_th(), get_champ_post_FT(), impr(), mettre_a_jour(), and preparer_calcul().