TrioCFD: Random_process Class Reference
Random_process Class Reference
#include <Random_process.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Random_process()
Random_process::Random_process ()
~Random_process()
Random_process::~Random_process ()
Member Function Documentation
cree_instance()
Objet_U * Random_process::cree_instance () static
taille_memoire()
unsigned Random_process::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Random_process::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Random_process::info () static
get_info()
const Type_info * Random_process::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
Random_process & Random_process::self_cast (Objet_U & r) static
self_cast() [2/2]
const Random_process & Random_process::self_cast (const Objet_U & r) static
printOn()
Sortie & Random_process::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
readOn()
Entree & Random_process::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
References Param::ajouter(), Param::lire_avec_accolades(), Objet_U::que_suis_je(), and Param::REQUIRED.
initialise()
void Random_process::initialise (double eps_etoile, double tL, int nl, int nm, int nn, std::string nom_fichier_sortie, Nom nom_sauvegarde)
References TRUSTArray< _TYPE_, _SIZE_ >::resize().
Referenced by init_forcage_THI::compute_initial_chouippe().
next_step()
void Random_process::next_step (double dt, int it)
next_step2()
void Random_process::next_step2 (double dt, int it)
References Process::je_suis_maitre().
Referenced by init_forcage_THI::compute_THI_force().
next_step3()
void Random_process::next_step3 (ArrOfDouble & advection_velocity, double dt, int it)
References Process::je_suis_maitre().
write()
void Random_process::write (std::string nom_fichier_sortie, double temps)
write_separate()
void Random_process::write_separate (std::string nom_fichier_sortie, double t)
get_b()
std::vector< std::vector< std::vector< double > > > Random_process::get_b ()
get_b_flt()
ArrOfDouble & Random_process::get_b_flt ()
Referenced by init_forcage_THI::compute_THI_force(), and init_forcage_THI::get_b_flt().
initialise_gen()
std::minstd_rand Random_process::initialise_gen (int i)
get_semi_gen()
int Random_process::get_semi_gen ()
Referenced by init_forcage_THI::get_semi_gen().
Member Data Documentation
info_obj
const Type_info Random_process::info_obj static