TrioCFD: Quadrature_Ord5_Polygone Class Reference
Quadrature_Ord5_Polygone Class Reference
#include <Quadrature_Ord5_Polygone.h>
Public Member Functions
void compute_integ_points () override
void compute_integ_points_on_facet () override
Public Member Functions inherited from Quadrature_base
virtual void compute_integ_points ()=0
virtual void compute_integ_points_on_facet ()=0
double compute_integral (DoubleTab &vals_pts_integ) const
double compute_integral (Parser_U &parser) const
double compute_integral_on_elem (int num_elem, DoubleTab &val_pts_integ) const
double compute_integral_on_elem (int num_elem, Parser_U &parser) const
double compute_integral_on_elem (Parser_U &parser) const
double compute_integral_on_facet (int num_facet, DoubleTab &val_pts_integ) const
double compute_integral_on_facet (int num_facet, Parser_U &parser) const
Constructor & Destructor Documentation
Quadrature_Ord5_Polygone()
Quadrature_Ord5_Polygone::Quadrature_Ord5_Polygone (const Domaine_DG & dom) inline
References compute_integ_points(), compute_integ_points_on_facet(), Quadrature_base::dom_, and nb_f_elem_max.
Member Function Documentation
compute_integ_points()
void Quadrature_Ord5_Polygone::compute_integ_points () override virtual
Compute for the whole domain the exact location of integration points per element
Implements Quadrature_base.
References Quadrature_base::calculateWeightScale(), Objet_U::dimension, Quadrature_base::dom_, Quadrature_base::ind_pts_integ_, Quadrature_base::integ_points_, Process::mp_max(), Quadrature_base::nb_pts_integ_max_, TRUSTTab< _TYPE_, _SIZE_ >::resize(), Quadrature_base::tab_nb_pts_integ_, Quadrature_base::weights_, and Quadrature_base::weights_tri_.
Referenced by Quadrature_Ord5_Polygone().
compute_integ_points_on_facet()
void Quadrature_Ord5_Polygone::compute_integ_points_on_facet () override virtual
Compute for the whole domain the exact location of integration points per facet
Implements Quadrature_base.
References Objet_U::dimension, Quadrature_base::dom_, Quadrature_base::integ_points_facets_, Quadrature_base::nb_pts_integ_facets_, TRUSTTab< _TYPE_, _SIZE_ >::resize(), and Quadrature_base::weights_facets_.
Referenced by Quadrature_Ord5_Polygone().
Member Data Documentation
nb_f_elem_max
int Quadrature_Ord5_Polygone::nb_f_elem_max protected
Referenced by Quadrature_Ord5_Polygone().