TrioCFD: Champ_val_tot_sur_vol_base Class Reference
Champ_val_tot_sur_vol_base Class Reference abstract
#include <Champ_val_tot_sur_vol_base.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::UNIFORME >
int initialiser (const double temps) override
void mettre_a_jour (double temps) override
DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const override
DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &valeurs, int le_poly) const override
double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const override
DoubleTab & valeur_aux (const DoubleTab &positions, DoubleTab &valeurs) const override
DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const override
DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const override
DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp) const override
Public Member Functions inherited from Champ_Don_base
void dimensionner (int, int)
int fixer_nb_valeurs_nodales (int nb_noeuds) override
const Type_info * get_info () const override
int imprime (Sortie &, int) const override
virtual int initialiser (const double temps)
void mettre_a_jour (double temps) override
int reprendre (Entree &) override
void resetTime (double time) override
int sauvegarder (Sortie &) const override
DoubleTab & valeurs () override
Public Member Functions inherited from Champ_base
Champ_base & affecter (const Champ_base &)
Champ_base ()
virtual double changer_temps (const double t)
const Type_info * get_info () const override
double temps () const
virtual DoubleTab & trace (const Frontiere_dis_base &, DoubleTab &, double, int distant) const
virtual DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const
virtual double valeur_a_compo (const DoubleVect &position, int ncomp) const
virtual DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &valeurs, int le_poly) const
virtual double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const
virtual DoubleVect & valeur_a_sommet (int, const Domaine &, DoubleVect &) const
virtual DoubleTab & valeur_aux (const DoubleTab &positions, DoubleTab &valeurs) const
virtual DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const
virtual DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const
virtual DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp) const
Public Member Functions inherited from Field_base
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
virtual void fixer_nb_comp (int i)
virtual const Nom & fixer_nom_compo (const Nom &)
virtual const Nom & fixer_nom_compo (int, const Nom &)
virtual const Noms & fixer_noms_compo (const Noms &)
virtual const Nom & fixer_unite (const Nom &)
virtual const Nom & fixer_unite (int i, const Nom &)
virtual const Noms & fixer_unites (const Noms &)
const Type_info * get_info () const override
const Nom & nom_compo (int) const
void nommer (const Nom &) override
const Nom & unite () const
const Nom & unite (int) const
const Noms & unites () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Champ_Proto
int lire_dimension (Entree &, const Nom &)
int lire_dimension (int dim, const Nom &le_nom_)
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Champ_Don_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Field_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
dont on veut une evaluation exprimee par val_lue_loc/(Somme_vol_poro_loc)
val_lue_loc designe la valeur lue pour une localisation de l espace (sous domaine ou domaine par defaut)
cas VDF : Somme_vol_poro_loc exprime la sommation de vol_element*poro_volumique
          pour les elements contenus dans la localisation loc
cas VEF : Somme_vol_poro_loc exprime la sommation de vol_entrelaces*poro_surface
            pour les faces contenues dans la localisation loc
Somme_vol_poro_loc est evalue par la methode eval_contrib_loc() des classes derivees
La syntaxe utilisateur a respecter est la suivante : Valeur_totale_sur_volume nom_domaine nb_comp { defaut val_lue_dom ...domainei val_lue_szi ... } nom_domaine : nom du domaine de calcul nb_comp : nombre de composantes du champ val_lue_dom : valeur lue pour le domaine par defaut val_lue_szi : valeur lue pour la sous domaine domainei
Constructor & Destructor Documentation
Champ_val_tot_sur_vol_base()
Champ_val_tot_sur_vol_base::Champ_val_tot_sur_vol_base ()
~Champ_val_tot_sur_vol_base()
Champ_val_tot_sur_vol_base::~Champ_val_tot_sur_vol_base () override
Member Function Documentation
info()
const Type_info * Champ_val_tot_sur_vol_base::info () static
get_info()
const Type_info * Champ_val_tot_sur_vol_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Champ_Uniforme_Morceaux.
Reimplemented in Champ_val_tot_sur_vol_VDF, and Champ_val_tot_sur_vol_VEF.
self_cast() [1/2]
Champ_val_tot_sur_vol_base & Champ_val_tot_sur_vol_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Champ_val_tot_sur_vol_base & Champ_val_tot_sur_vol_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Champ_val_tot_sur_vol_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Champ_Uniforme_Morceaux.
Reimplemented in Champ_val_tot_sur_vol_VDF, and Champ_val_tot_sur_vol_VEF.
References Champ_Uniforme_Morceaux::printOn().
Referenced by Champ_val_tot_sur_vol_VDF::printOn(), and Champ_val_tot_sur_vol_VEF::printOn().
readOn()
Entree & Champ_val_tot_sur_vol_base::readOn (Entree & is) override protected virtual
Lit les valeurs du champ uniforme par morceaux a partir d'un flot d'entree.
On lit le nom du domaine (nom_domaine) le nombre de composantes du champ (nb_comp) la valeur par defaut du champ ainsi que les valeurs sur les sous domaines. Format: Champ_Uniforme_Morceaux nom_domaine nb_comp { Defaut val_def sous_domaine_1 val_1 ... sous_domaine_i val_i }
Reimplemented from Champ_Uniforme_Morceaux.
Reimplemented in Champ_val_tot_sur_vol_VDF, and Champ_val_tot_sur_vol_VEF.
References Champ_Uniforme_Morceaux::readOn().
Referenced by Champ_val_tot_sur_vol_VDF::readOn(), and Champ_val_tot_sur_vol_VEF::readOn().
evaluer()
void Champ_val_tot_sur_vol_base::evaluer (const Domaine_dis_base & zdis, const Domaine_Cl_dis_base & zcldis)
References TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), eval_contrib_loc(), TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::UNIFORME >::les_sous_domaines, Field_base::nb_compo_, Domaine_dis_base::nb_elem(), Sous_Domaine_32_64< _SIZE_ >::nb_elem_tot(), Champ_Don_base::valeurs(), and Champ_Don_base::valeurs_.
Referenced by Terme_Puissance_Thermique::initialiser_champ_puissance().
eval_contrib_loc()
virtual DoubleVect & Champ_val_tot_sur_vol_base::eval_contrib_loc (const Domaine_dis_base & zdis, const Domaine_Cl_dis_base & zcldis, DoubleVect & vol) pure virtual
Implemented in Champ_val_tot_sur_vol_VDF, and Champ_val_tot_sur_vol_VEF.
Referenced by evaluer().
Member Data Documentation
info_obj
const Type_info Champ_val_tot_sur_vol_base::info_obj static