TrioCFD: Modele_Jones_Launder_Thermique_VDF Class Reference
Modele_Jones_Launder_Thermique_VDF Class Reference
#include <Modele_Jones_Launder_Thermique_VDF.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Modele_Fonc_Bas_Reynolds_Thermique_Base
const Type_info * get_info () const override
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Modele_Fonc_Bas_Reynolds_Thermique_Base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Modele_Jones_Launder_Thermique_VDF()
Modele_Jones_Launder_Thermique_VDF::Modele_Jones_Launder_Thermique_VDF ()
~Modele_Jones_Launder_Thermique_VDF()
Modele_Jones_Launder_Thermique_VDF::~Modele_Jones_Launder_Thermique_VDF ()
Member Function Documentation
cree_instance()
Objet_U * Modele_Jones_Launder_Thermique_VDF::cree_instance () static
taille_memoire()
unsigned Modele_Jones_Launder_Thermique_VDF::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Modele_Jones_Launder_Thermique_VDF::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Modele_Jones_Launder_Thermique_VDF::info () static
get_info()
const Type_info * Modele_Jones_Launder_Thermique_VDF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
Modele_Jones_Launder_Thermique_VDF & Modele_Jones_Launder_Thermique_VDF::self_cast (Objet_U & r) static
self_cast() [2/2]
const Modele_Jones_Launder_Thermique_VDF & Modele_Jones_Launder_Thermique_VDF::self_cast (const Objet_U & r) static
printOn()
Sortie & Modele_Jones_Launder_Thermique_VDF::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
readOn()
Entree & Modele_Jones_Launder_Thermique_VDF::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
References Process::exit().
Calcul_D()
DoubleTab & Modele_Jones_Launder_Thermique_VDF::Calcul_D (DoubleTab & D, const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const DoubleTab & vitesse, const DoubleTab & Fluctu_Temp, double diffu) const override virtual
Implements Modele_Fonc_Bas_Reynolds_Thermique_Base.
References Domaine_VDF::dist_norm_bord(), MorEqn::equation(), Domaine_VF::face_voisins(), Domaine_Cl_dis_base::les_conditions_limites(), Equation_base::milieu(), Domaine_VF::nb_faces(), Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), Domaine_VDF::orientation(), Milieu_base::porosite_face(), Domaine_VF::premiere_face_int(), Dirichlet::val_imp(), TRUST_Deriv< _CLASSE_ >::valeur(), Domaine_VF::volumes_entrelaces(), and Domaine_VF::xp().
Calcul_E()
DoubleTab & Modele_Jones_Launder_Thermique_VDF::Calcul_E (DoubleTab & E, const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const DoubleTab & temp, const DoubleTab & Fluctu_Temp, double diffu, const DoubleTab & diffu_turb) const override virtual
Implements Modele_Fonc_Bas_Reynolds_Thermique_Base.
References Objet_U::dimension, Domaine_VDF::dist_face(), Domaine_VDF::dist_norm_bord(), Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), Domaine_VF::face_voisins(), Domaine_Cl_dis_base::les_conditions_limites(), Domaine_dis_base::nb_elem(), Domaine_dis_base::nb_elem_tot(), Domaine_VF::nb_faces(), Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), Domaine_VDF::orientation(), Domaine_VF::premiere_face_int(), Dirichlet::val_imp(), TRUST_Deriv< _CLASSE_ >::valeur(), Domaine_VF::volumes(), and Domaine_VF::xp().
Calcul_F1()
DoubleTab & Modele_Jones_Launder_Thermique_VDF::Calcul_F1 (DoubleTab & F1, const Domaine_dis_base & domaine_dis, const DoubleTab & K_Eps_Bas_Re, const DoubleTab & FluctuTemp_Bas_Re, double visco, double diffu) const override virtual
Implements Modele_Fonc_Bas_Reynolds_Thermique_Base.
References Domaine_dis_base::nb_elem().
Calcul_F2()
DoubleTab & Modele_Jones_Launder_Thermique_VDF::Calcul_F2 (DoubleTab & F2, const Domaine_dis_base & domaine_dis, const DoubleTab & K_Eps_Bas_Re, const DoubleTab & FluctuTemp_Bas_Re, double visco, double diffu) const override virtual
Implements Modele_Fonc_Bas_Reynolds_Thermique_Base.
References Domaine_dis_base::nb_elem().
Calcul_F3()
DoubleTab & Modele_Jones_Launder_Thermique_VDF::Calcul_F3 (DoubleTab & F3, const Domaine_dis_base & domaine_dis, const DoubleTab & K_Eps_Bas_Re, const DoubleTab & FluctuTemp_Bas_Re, double visco, double diffu) const override virtual
Implements Modele_Fonc_Bas_Reynolds_Thermique_Base.
References Domaine_dis_base::nb_elem().
Calcul_F4()
DoubleTab & Modele_Jones_Launder_Thermique_VDF::Calcul_F4 (DoubleTab & F4, const Domaine_dis_base & domaine_dis, const DoubleTab & K_Eps_Bas_Re, const DoubleTab & FluctuTemp_Bas_Re, double visco, double diffu) const override virtual
Implements Modele_Fonc_Bas_Reynolds_Thermique_Base.
References Domaine_dis_base::nb_elem().
Calcul_Flambda()
DoubleTab & Modele_Jones_Launder_Thermique_VDF::Calcul_Flambda (DoubleTab & Flambda, const Domaine_dis_base & domaine_dis, const DoubleTab & K_Eps_Bas_Re, const DoubleTab & FluctuTemp_Bas_Re, double visco, double diffu) const override virtual
Implements Modele_Fonc_Bas_Reynolds_Thermique_Base.
References Domaine_dis_base::nb_elem().
lire()
Entree & Modele_Jones_Launder_Thermique_VDF::lire (const Motcle & , Entree & is)
associer_pb()
void Modele_Jones_Launder_Thermique_VDF::associer_pb (const Probleme_base & pb) override virtual
Implements Modele_Fonc_Bas_Reynolds_Thermique_Base.
References eq_transport_Fluctu_Temp_Bas_Re, and Modele_Fonc_Bas_Reynolds_Thermique_Base::equation().
associer()
void Modele_Jones_Launder_Thermique_VDF::associer (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis) override virtual
Implements Modele_Fonc_Bas_Reynolds_Thermique_Base.
mettre_a_jour()
void Modele_Jones_Launder_Thermique_VDF::mettre_a_jour (double temps) override virtual
Implements Modele_Fonc_Bas_Reynolds_Thermique_Base.
Member Data Documentation
info_obj
const Type_info Modele_Jones_Launder_Thermique_VDF::info_obj static
le_dom_VDF
TRUST_Ref< Domaine_VDF *> Modele_Jones_Launder_Thermique_VDF::le_dom_VDF protected
le_dom_Cl_VDF
TRUST_Ref< Domaine_Cl_VDF *> Modele_Jones_Launder_Thermique_VDF::le_dom_Cl_VDF protected
le_fluide
TRUST_Ref< Fluide_base *> Modele_Jones_Launder_Thermique_VDF::le_fluide protected
la_vitesse_transportante
TRUST_Ref< Champ_Inc_base *> Modele_Jones_Launder_Thermique_VDF::la_vitesse_transportante protected
eq_transport_Fluctu_Temp_Bas_Re
TRUST_Ref< Transport_Fluctuation_Temperature_W_Bas_Re *> Modele_Jones_Launder_Thermique_VDF::eq_transport_Fluctu_Temp_Bas_Re protected
Referenced by associer_pb().