TrioCFD: Flux_interfacial_Wolfert Class Reference
Flux_interfacial_Wolfert Class Reference
#include <Flux_interfacial_Wolfert.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Flux_interfacial_Wolfert()
Flux_interfacial_Wolfert::Flux_interfacial_Wolfert ()
~Flux_interfacial_Wolfert()
Flux_interfacial_Wolfert::~Flux_interfacial_Wolfert ()
Member Function Documentation
cree_instance()
Objet_U * Flux_interfacial_Wolfert::cree_instance () static
taille_memoire()
unsigned Flux_interfacial_Wolfert::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Flux_interfacial_Wolfert::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Flux_interfacial_Wolfert::info () static
get_info()
const Type_info * Flux_interfacial_Wolfert::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Flux_interfacial_base.
self_cast() [1/2]
Flux_interfacial_Wolfert & Flux_interfacial_Wolfert::self_cast (Objet_U & r) static
self_cast() [2/2]
const Flux_interfacial_Wolfert & Flux_interfacial_Wolfert::self_cast (const Objet_U & r) static
printOn()
Sortie & Flux_interfacial_Wolfert::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Flux_interfacial_base.
readOn()
Entree & Flux_interfacial_Wolfert::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Flux_interfacial_base.
References Param::ajouter(), Param::lire_avec_accolades_depuis(), Pr_t_, and Objet_U::que_suis_je().
coeffs()
void Flux_interfacial_Wolfert::coeffs (const input_t & in, output_t & out) const override virtual
Implements Flux_interfacial_base.
References Flux_interfacial_base::input_t::alpha, Flux_interfacial_base::input_t::Cp, Flux_interfacial_base::input_t::d_bulles, Flux_interfacial_base::output_t::da_hi, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Flux_interfacial_base::output_t::hi, Flux_interfacial_base::input_t::lambda, Flux_interfacial_base::input_t::Lvap, n_l, Flux_interfacial_base::input_t::nut, Flux_interfacial_base::input_t::nv, Flux_interfacial_base::input_t::rho, and Flux_interfacial_base::input_t::T.
completer()
void Flux_interfacial_Wolfert::completer () override virtual
Reimplemented from Correlation_base.
References Nom::debute_par(), Process::exit(), Probleme_base::has_champ(), n_l, Pb_Multiphase::nb_phases(), Pb_Multiphase::nom_phase(), Correlation_base::pb_, Objet_U::que_suis_je(), and TRUST_Ref< _CLASSE_ >::valeur().
Member Data Documentation
info_obj
const Type_info Flux_interfacial_Wolfert::info_obj static
n_l
int Flux_interfacial_Wolfert::n_l = -1 protected
Referenced by coeffs(), and completer().
Pr_t_
double Flux_interfacial_Wolfert::Pr_t_ = 0.85 protected
Referenced by readOn().