TrioCFD: ALE_Neumann_BC_for_grid_problem Class Reference
ALE_Neumann_BC_for_grid_problem Class Reference
#include <ALE_Neumann_BC_for_grid_problem.h>
Public Member Functions
const Type_info * get_info () const override
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Constructor & Destructor Documentation
ALE_Neumann_BC_for_grid_problem()
ALE_Neumann_BC_for_grid_problem::ALE_Neumann_BC_for_grid_problem ()
~ALE_Neumann_BC_for_grid_problem()
ALE_Neumann_BC_for_grid_problem::~ALE_Neumann_BC_for_grid_problem ()
Member Function Documentation
cree_instance()
Objet_U * ALE_Neumann_BC_for_grid_problem::cree_instance () static
taille_memoire()
unsigned ALE_Neumann_BC_for_grid_problem::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int ALE_Neumann_BC_for_grid_problem::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * ALE_Neumann_BC_for_grid_problem::info () static
get_info()
const Type_info * ALE_Neumann_BC_for_grid_problem::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Interprete_geometrique_base_32_64< _SIZE_ >.
self_cast() [1/2]
ALE_Neumann_BC_for_grid_problem & ALE_Neumann_BC_for_grid_problem::self_cast (Objet_U & r) static
self_cast() [2/2]
const ALE_Neumann_BC_for_grid_problem & ALE_Neumann_BC_for_grid_problem::self_cast (const Objet_U & r) static
printOn()
Sortie & ALE_Neumann_BC_for_grid_problem::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Interprete_geometrique_base_32_64< _SIZE_ >.
References Interprete::printOn().
readOn()
Entree & ALE_Neumann_BC_for_grid_problem::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Interprete_geometrique_base_32_64< _SIZE_ >.
References Interprete::readOn().
interpreter_()
Entree & ALE_Neumann_BC_for_grid_problem::interpreter_ (Entree & is) override protected virtual
Implements Interprete_geometrique_base_32_64< _SIZE_ >.
References Interprete_geometrique_base_32_64< _SIZE_ >::associer_domaine(), Interprete_geometrique_base_32_64< _SIZE_ >::domaine(), and Domaine_ALE::reading_ALE_Neumann_BC_for_grid_problem().
Member Data Documentation
info_obj
const Type_info ALE_Neumann_BC_for_grid_problem::info_obj static