TrioCFD: TRUSTArray< _TYPE_, _SIZE_ > Class Template Reference
TRUSTArray< _TYPE_, _SIZE_ > Class Template Reference
#include <TRUSTArray.h>
Public Member Functions
void append_array (_TYPE_ valeur)
void from_tid_to_int (TRUSTArray< int, int > &out) const
TRUSTArray & inject_array (const TRUSTArray &source, _SIZE_ nb_elements=-1, _SIZE_ first_element_dest=0, _SIZE_ first_element_source=0)
TRUSTArray & operator*= (const _TYPE_ dy)
TRUSTArray & operator+= (const _TYPE_ dy)
TRUSTArray & operator+= (const TRUSTArray &y)
TRUSTArray & operator-= (const _TYPE_ dy)
TRUSTArray & operator-= (const TRUSTArray &y)
TRUSTArray & operator/= (const _TYPE_ dy)
TRUSTArray & operator= (_TYPE_ x)
void ref_as_small (TRUSTArray< float, int > &out) const
int ref_count () const
virtual void ref_data (_TYPE_ *ptr, _SIZE_ size)
virtual void reset ()
void set_mem_storage (const STORAGE storage)
_SIZE_ size_array () const
TRUSTArray (const TRUSTArray &A)
Public Member Functions inherited from Array_base
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &os) const override
Entree & readOn (Entree &is) override
void resize_array_ (_SIZE_ n, RESIZE_OPTIONS opt=RESIZE_OPTIONS::COPY_INIT)
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
template<typename _TYPE_, typename _SIZE_>
class TRUSTArray< _TYPE_, _SIZE_ >
The two main members are mem_ and span_:
'mem_' is the (shared) pointer to the actual underlying data. The block of data itself is a std::vector. This block of data can be shared among several arrays (see below) or can be null if we reference external data (ref_data)
'span_' is a view on the actual data, and can point to a sub-part of *mem_.
We can have 3 states for the array:
"detached": meaning mem_==nullptr, span_.empty() == true (state obtained with the default ctor and detach_array())
"normal" : in this case mem_ is a non-null shared pointer to a std::vector holding the data. 'span_' then typically represents the entire span of the vector. The array is always initialised with 0. When the array is destroyed, the shared_ptr 'mem_' is destroyed too, and if this was the last reference to the underlying data, the std::vector itself is freed. The memory space of the array can be shared among several TRUSTArray ('mem_' has the same underlying value in several instances). This is typically produced by ref_array(). Note that when this happens, we have two instances pointing to the same underlying block of data, but none of them has precedence over the other one (none of them is 'the' owner of the data). Ownership is shared, and when the last owner is destroyed, memory is released.
"ref_data" : this is used to point to an exterior existing memory zone (not managed by TRUSTArray - for example data provided by an external Fortran func) In this case, mem_ remains nullptr, just the span_ is correctly filled, and no memory is released when the array is destroyed.
Finally, in case of a "XXTrav" array, the memory allocation is special:
a Trav array is allocated once, but when released, memory is kept in a pool so that another request for a new Trav might re-use it without having to perform the allocation again.
a Trav may not be ref_data or ref_array.
see implementation details of this mechanism in the TRUSTTravPool class.
In the template parameters below, TYPE is the value type (what it contains), SIZE is the extent type (how many items).
Member Typedef Documentation
Value_type_
template<typename _TYPE_ , typename _SIZE_ > using TRUSTArray< _TYPE_, _SIZE_ >::Value_type_ = _TYPE_
int_t
template<typename _TYPE_ , typename _SIZE_ > using TRUSTArray< _TYPE_, _SIZE_ >::int_t = _SIZE_
Iterator_
template<typename _TYPE_ , typename _SIZE_ > using TRUSTArray< _TYPE_, _SIZE_ >::Iterator_ = typename tcb::span<_TYPE_>::iterator
Vector_
template<typename _TYPE_ , typename _SIZE_ > using TRUSTArray< _TYPE_, _SIZE_ >::Vector_ = std::vector<_TYPE_, TVAlloc<_TYPE_> >
Span_
template<typename _TYPE_ , typename _SIZE_ > using TRUSTArray< _TYPE_, _SIZE_ >::Span_ = tcb::span<_TYPE_>
Constructor & Destructor Documentation
~TRUSTArray()
template<typename _TYPE_ , typename _SIZE_ > virtual TRUSTArray< _TYPE_, _SIZE_ >::~TRUSTArray () inline virtual
TRUSTArray() [1/3]
template<typename _TYPE_ , typename _SIZE_ > TRUSTArray< _TYPE_, _SIZE_ >::TRUSTArray () inline
TRUSTArray() [2/3]
template<typename _TYPE_ , typename _SIZE_ > TRUSTArray< _TYPE_, _SIZE_ >::TRUSTArray (_SIZE_ n) inline
TRUSTArray() [3/3]
template<typename _TYPE_ , typename _SIZE_ > TRUSTArray< _TYPE_, _SIZE_ >::TRUSTArray (const TRUSTArray< _TYPE_, _SIZE_ > & A) inline
Copy ctor. Performs a deep copy.
It is forbidden to deep copy a ref_data.
References TRUSTArray< _TYPE_, _SIZE_ >::resize_array_(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Member Function Documentation
taille_memoire()
template<typename _TYPE_ , typename _SIZE_ > unsigned TRUSTArray< _TYPE_, _SIZE_ >::taille_memoire () const inline override protected virtual
Implements Objet_U.
Reimplemented in TRUSTTab< _TYPE_, _SIZE_ >, TRUSTTab< int, int >, TRUSTTab< double, int >, TRUSTTab< _TYPE_ >, TRUSTTab< _TYPE_, int >, TRUSTTab< int >, TRUSTTab< double >, TRUSTTab< _SIZE_ >, TRUSTTab< trustIdType, int >, TRUSTVect< _TYPE_, _SIZE_ >, TRUSTVect< int, int >, TRUSTVect< double, int >, TRUSTVect< _TYPE_, int >, TRUSTVect< int, _SIZE_ >, TRUSTVect< double, _SIZE_ >, TRUSTVect< _SIZE_, _SIZE_ >, and TRUSTVect< trustIdType, int >.
duplique()
template<typename _TYPE_ , typename _SIZE_ > int TRUSTArray< _TYPE_, _SIZE_ >::duplique () const inline override protected virtual
Implements Objet_U.
Reimplemented in TRUSTTab< _TYPE_, _SIZE_ >, TRUSTTab< int, int >, TRUSTTab< double, int >, TRUSTTab< _TYPE_ >, TRUSTTab< _TYPE_, int >, TRUSTTab< int >, TRUSTTab< double >, TRUSTTab< _SIZE_ >, TRUSTTab< trustIdType, int >, TRUSTVect< _TYPE_, _SIZE_ >, TRUSTVect< int, int >, TRUSTVect< double, int >, TRUSTVect< _TYPE_, int >, TRUSTVect< int, _SIZE_ >, TRUSTVect< double, _SIZE_ >, TRUSTVect< _SIZE_, _SIZE_ >, and TRUSTVect< trustIdType, int >.
References Process::exit(), Objet_U::numero(), and TRUSTArray< _TYPE_, _SIZE_ >::TRUSTArray.
printOn()
template<typename _TYPE_ , typename _SIZE_ > Sortie & TRUSTArray< _TYPE_, _SIZE_ >::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Array_base.
Reimplemented in TRUSTTab< _TYPE_, _SIZE_ >, TRUSTTab< int, int >, TRUSTTab< double, int >, TRUSTTab< _TYPE_ >, TRUSTTab< _TYPE_, int >, TRUSTTab< int >, TRUSTTab< double >, TRUSTTab< _SIZE_ >, TRUSTTab< trustIdType, int >, TRUSTVect< _TYPE_, _SIZE_ >, TRUSTVect< int, int >, TRUSTVect< double, int >, TRUSTVect< _TYPE_, int >, TRUSTVect< int, _SIZE_ >, TRUSTVect< double, _SIZE_ >, TRUSTVect< _SIZE_, _SIZE_ >, and TRUSTVect< trustIdType, int >.
References Sortie::put().
Referenced by TRUSTVect< _TYPE_, _SIZE_ >::printOn().
readOn()
template<typename _TYPE_ , typename _SIZE_ > Entree & TRUSTArray< _TYPE_, _SIZE_ >::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Array_base.
Reimplemented in TRUSTTab< _TYPE_, _SIZE_ >, TRUSTTab< int, int >, TRUSTTab< double, int >, TRUSTTab< _TYPE_ >, TRUSTTab< _TYPE_, int >, TRUSTTab< int >, TRUSTTab< double >, TRUSTTab< _SIZE_ >, TRUSTTab< trustIdType, int >, TRUSTVect< _TYPE_, _SIZE_ >, TRUSTVect< int, int >, TRUSTVect< double, int >, TRUSTVect< _TYPE_, int >, TRUSTVect< int, _SIZE_ >, TRUSTVect< double, _SIZE_ >, TRUSTVect< _SIZE_, _SIZE_ >, and TRUSTVect< trustIdType, int >.
References Process::exit(), and Entree::get().
Referenced by TRUSTVect< _TYPE_, _SIZE_ >::readOn().
begin()
template<typename _TYPE_ , typename _SIZE_ > Iterator_ TRUSTArray< _TYPE_, _SIZE_ >::begin () inline
Referenced by Partitionneur_Tranche_32_64< _SIZE_ >::construire_partition(), Integrer_champ_med::interpreter(), and Remaillage_FT::marquer_aretes().
end()
template<typename _TYPE_ , typename _SIZE_ > Iterator_ TRUSTArray< _TYPE_, _SIZE_ >::end () inline
Referenced by Partitionneur_Tranche_32_64< _SIZE_ >::construire_partition(), Integrer_champ_med::interpreter(), and Remaillage_FT::marquer_aretes().
resize()
template<typename _TYPE_ , typename _SIZE_ > void TRUSTArray< _TYPE_, _SIZE_ >::resize (_SIZE_ new_size, RESIZE_OPTIONS opt = RESIZE_OPTIONS::COPY_INIT) inline
Referenced by Parser::addVar(), Op_Grad_VEF_P1B_Face::ajouter_som(), Corrige_flux_FT_temperature_subresolution::associate_indices_and_check_subproblems_consistency(), Polygone_32_64< _SIZE_ >::build_reduced(), Corrige_flux_FT_temperature_conv::calcul_temperature_flux_interface(), Op_Conv_VEF_base::calculer_dt_stab(), IJK_Interfaces::calculer_phi_repuls_par_compo(), IJK_Interfaces::calculer_var_volume_remaillage(), FT_Field::champ_sommet_from_facettes(), Op_Conv_VEF_Face::completer(), FT_Field::completer_compo_connexe_partielle(), IJK_Interfaces::compute_bubbles_volume_and_barycentres(), Operator_FT_Disc::Compute_interfaciale_source(), IJK_Thermal_Subresolution::compute_md_vector(), IJK_One_Dimensional_Subproblems::compute_overall_quantities_per_bubbles(), Solv_Externe::Create_lhs_rhs_onDevice(), Traitement_particulier_NS_CEG::critere_cea_jaea(), FT_Field::exchange_compo_connexe(), Extruder::Extruder(), Extruder_en20::Extruder_en20(), Extruder_en3::Extruder_en3(), Operator_FT_Disc::Facette_to_Sommets(), FT_Field::get_Grad_FT_field_Array(), FT_Field::get_interfacial_source_term_sommets(), FT_Field::get_interfacial_source_term_sommets_non_const(), Operator_FT_Disc::get_n_sommet(), Matrice_Nulle::get_stencil_and_coefficients(), Matrice_Morse_Sym::get_symmetric_stencil_and_coefficients(), IJK_Interfaces::IJK_Interfaces(), Random_process::initialise(), Corrige_flux_FT_temperature_conv::initialize(), IJK_Interfaces::initialize(), FT_Field::initialize(), Matrice_Dense::inverse(), Terme_Boussinesq_base::lire_motcle_non_standard(), FT_Field::nettoyer_espace_virtuel_facette(), Front_VF::num_face(), Operator_FT_Disc::Operator_Gradient_FT_sommets(), Operator_FT_Disc::Operator_Laplacian_FT_element(), ParcoursIJKDir::ParcoursIJKDir(), Polyedre_32_64< _SIZE_ >::Polyedre_32_64(), Polygone_32_64< _SIZE_ >::Polygone_32_64(), IJK_Thermal_Subresolution::post_process_thermal_downstream_lines(), Terme_Source_Canal_perio::readOn(), Vitesse_derive_base::readOn(), Corrige_flux_FT_temperature_subresolution::receive_all_fluxes_from_outisde_frontier_on_procs(), Corrige_flux_FT_temperature_subresolution::receive_fluxes_from_frontier_on_procs(), Corrige_flux_FT_temperature_subresolution::receive_temperature_cell_centre_neighbours_from_procs(), FT_Field::remailler_FT_Field(), Collision_Model_FT_base::research_collision_pairs_Verlet(), FT_Field::resize(), Solv_rocALUTION::resoudre_systeme(), IJK_One_Dimensional_Subproblems_Interfaces_Fields::retrieve_interfacial_surface_quantity(), FT_Field::sauv_num_pe_echange(), Force_sp::set_zero(), Parser::setNbVar(), IJK_One_Dimensional_Subproblems::share_boundary_previous_values(), IJK_One_Dimensional_Subproblems::share_interfacial_heat_flux_correction_on_procs(), Matrice_Dense::solve(), Operator_FT_Disc::Sommets_to_Facettes(), IJK_One_Dimensional_Subproblems::sort_limited_probes_spherical_coords_post_processing(), Terme_Source_Canal_perio::source(), Remaillage_FT_IJK::supprimer_petites_aretes(), Transport_Interfaces_FT_Disc::Transport_Interfaces_FT_Disc(), IJK_Interfaces::transporter_maillage_deformation(), IJK_Interfaces::transporter_maillage_remaillage(), Corrige_flux_FT_temperature_conv::update(), FT_Field::update_Field_sommets(), Maillage_FT_IJK::update_sigma_and_interfacial_source_term_sommet(), and FT_Field::update_sigma_and_interfacial_source_term_sommet().
resize_array()
template<typename _TYPE_ , typename _SIZE_ > void TRUSTArray< _TYPE_, _SIZE_ >::resize_array (_SIZE_ new_size, RESIZE_OPTIONS opt = RESIZE_OPTIONS::COPY_INIT) inline
Referenced by RTabInt::add(), CSR_Builder::add_coeff(), Polyedre_32_64< _SIZE_ >::affecte_connectivite_numero_global(), Intersections_Elem_Facettes::ajoute_intersection(), Op_Conv_VEF_Face::ajouter(), Operateur_Conv_sensibility_VEF::ajouter_conv_term(), Scatter::ajouter_joints(), Operateur_Conv_sensibility_VEF::ajouter_Lsensibility_state_Amont(), Operateur_Conv_sensibility_VEF::ajouter_Lstate_sensibility_Amont(), Maillage_FT_Disc::ajouter_maillage(), Maillage_FT_IJK::ajouter_maillage_IJK(), Terme_Source_Constituant_Vortex_VEF_Face::ajouter_terme_div_u(), Op_Conv_ALE_VEF::ajouterALE(), IJK_Shear_Periodic_helpler::allocate(), MD_Vector_base::append_blocs(), MD_Vector_std::append_from_other_std(), MD_Vector_base::append_items(), Pb_Couple_rayo_semi_transp::associer_(), Remaillage_FT_IJK::barycentrer_lisser_systematique_ijk(), Schema_Comm_Vecteurs::begin_init(), Octree_Int_32_64< _SIZE_ >::build(), Octree_Int_32_64< _SIZE_ >::build_octree_recursively(), Maillage_FT_Disc::calcul_courbure_sommets(), Couplage_Tubes_IBC::calcul_F_pression(), Couplage_Tubes_IBC::calcul_F_pression2(), Parcours_interface::calcul_intersection_facelem_3D(), Descripteur_FT::calcul_liste_pe_voisins(), Transport_Marqueur_FT::calcul_proprietes_geometriques(), Desc_Structure_FT::calcul_schema_comm(), Maillage_FT_Disc::calcul_surface_normale(), Corrige_flux_FT_temperature_conv::calcul_temperature_flux_interface(), IJK_Interfaces::calculer_aspect_ratio(), IJK_Interfaces::calculer_bounding_box_bulles(), Navier_Stokes_FT_Disc::calculer_champ_forces_superficielles(), IJK_Interfaces::calculer_color(), Maillage_FT_IJK::calculer_compo_connexe_sommets(), Navier_Stokes_FTD_IJK::calculer_dv(), IJK_Interfaces::calculer_indicatrices(), IJK_Interfaces::calculer_phi_repuls_sommet(), Senseur_Interface::calculer_position(), IJK_Interfaces::calculer_surface_bulles(), IJK_Interfaces::calculer_surfactant(), Remaillage_FT::calculer_variation_volume(), IJK_Interfaces::calculer_volume_bulles(), FT_Field::calculer_volume_bulles(), Reordonner_faces_periodiques_32_64< _SIZE_ >::check_faces_periodiques(), Reordonner_faces_periodiques_32_64< _SIZE_ >::chercher_direction_perio(), Partitionneur_Tranche_32_64< _SIZE_ >::chercher_direction_perio(), Maillage_FT_Disc_Data_Cache::clear(), Coarsen_Operator_Uniform::Coarsen_Operator_Uniform(), Op_Conv_EF_VEF_P1NC_Stab::completer(), Terme_Source_Rappel_T_VEF_Face::completer(), Reaction::completer(), Chimie::completer(), Navier_Stokes_FTD_IJK::compute_add_THI_force(), Navier_Stokes_FTD_IJK::compute_add_THI_force_sur_d_velocity(), Navier_Stokes_FTD_IJK::compute_correction_for_momentum_balance(), IJK_Interfaces::compute_external_forces_color_function(), IJK_Thermal_cut_cell::compute_interfacial_temperature2(), ComputeValParCompoInCell::compute_list_compo_connex_in_element(), DebogIJK::compute_signature(), DebogFT::compute_signature_sommets(), IJK_Interfaces::compute_surface_average_per_bubble(), Triple_Line_Model_FT_Disc::compute_TCL_fluxes_in_all_boundary_cells(), Navier_Stokes_FTD_IJK::compute_var_volume_par_bulle(), AssembleurPVDF_PF::construire(), Assembleur_P_VDF::construire(), Domain_Graph::construire_graph_elem_elem(), Domain_Graph::construire_graph_from_segment(), Scatter::construire_md_vector(), Maillage_FT_Disc::construire_noeuds(), Marching_Cubes::construire_noeuds_liste_faces(), Partitionneur_Tranche_32_64< _SIZE_ >::construire_partition(), Partitionneur_Parmetis::construire_partition(), Partitionneur_Ptscotch::construire_partition(), Convection_Diffusion_Temperature_FT_Disc::Convection_Diffusion_Temperature_FT_Disc(), Matrix_tools::convert_to_morse_matrix_with_ptrs(), Maillage_FT_Disc::convertir_numero_distant_local(), Maillage_FT_Disc::copier_sommet(), Static_Int_Lists_32_64< _SIZE_ >::copy_list_to_array(), Convection_Diffusion_Temperature_FT_Disc::correct_mpoint(), Marching_Cubes::correspondance_espaces_distant_virtuel(), Maillage_FT_Disc::corriger_proprietaires_facettes(), Partitionneur_base_32_64< _SIZE_ >::corriger_sommets_bord(), Maillage_FT_Disc::creer_facettes_virtuelles(), Maillage_FT_IJK::creer_facettes_virtuelles(), Maillage_FT_Disc::creer_sommets_virtuels_numowner(), Maillage_FT_Disc::deplacer_sommets(), Convection_Diffusion_Temperature_FT_Disc::derivee_en_temps_inco(), Descripteur_FT::Descripteur_FT(), Transport_Marqueur_FT::detection_groupes_a_supprimer(), SolvElem_BiCGStab::dimensionne_wks(), SolvElem_Gmres::dimensionne_wks(), Remaillage_FT_IJK::diviser_grandes_aretes(), IJK_Interfaces::dupliquer_bulle_perio(), Schema_Comm::echange_taille(), Schema_Comm::echange_taille_et_messages(), Desc_Structure_FT::echanger_elements(), Maillage_FT_Disc::echanger_facettes(), Maillage_FT_Disc::echanger_sommets_PE(), Postprocessing_IJK::ecrire_statistiques_bulles(), Sauvegarde_Reprise_Maillage_FT::ecrire_xyz(), Remailleur_Collision_FT_Thomas::elements_voisins(), Remailleur_Collision_FT_Thomas::elements_voisins_a_distance_plus_petite2(), Schema_Comm_Vecteurs::end_init(), ExtrudeParoi::ExtrudeParoi(), Maillage_FT_Disc::facette_PE_owner(), Solv_Cholesky::Fact_Cholesky(), ILU_SP::factoriser(), MD_Vector_std::fill_md_vect_renum(), Couplage_Tubes_IBC::force_ibc_velocity(), Couplage_Tubes_IBC::force_ibc_velocity_anticipe_cube(), Couplage_Tubes_IBC::force_ibc_velocity_frac_vol(), Couplage_Tubes_IBC::force_ibc_velocity_miroir(), Couplage_Tubes_IBC::force_ibc_velocity_symetrie_plane(), Champ_Generique_Interpolation::get_champ_with_calculer_champ_post(), Intersections_Elem_Facettes::get_liste_elements_traverses(), Intersections_Elem_Facettes::get_liste_facettes_traversantes(), MD_Vector_base::get_sequential_items_flags(), Matrice_Morse::get_stencil(), Matrice_Bloc::get_stencil_and_coefficients(), Matrice_Diagonale::get_stencil_and_coefficients(), Matrice_Morse_Sym::get_symmetric_stencil(), Matrice_Bloc_Sym::get_symmetric_stencil_and_coefficients(), Matrice_Morse_Sym::get_symmetric_stencil_and_coefficients(), Couplage_Tubes_IBC::ibc0_force_cube(), Couplage_Tubes_IBC::ibc0_velocity_cube(), Couplage_Tubes_IBC::ibc_diffuse_force_cube(), Couplage_Tubes_IBC::ibc_diffuse_velocity_cube(), Couplage_Tubes_IBC::ibc_localisee_velocity_cube(), Couplage_Tubes_IBC::ibc_localisee_velocity_cube_qdm(), init_forcage_THI::init_forcage_THI(), Comm_Group::init_group(), Comm_Group::init_group_node(), Comm_Group::init_group_trio(), moyenne_glissante::initialise(), Raccord_distant_homogene_32_64< _SIZE_ >::initialise(), Force_sp::initialise(), Postprocessing_IJK::initialise_stats(), Ch_front_Vortex::initialiser(), Eq_couch_lim::initialiser(), Triple_Line_Model_FT_Disc::initialize(), Statistiques_dns_ijk_monophasique::initialize(), Fourier_trans::initialize(), Statistiques_dns_ijk::initialize(), IJK_Interfaces::initialize(), Statistiques_dns_ijk_FT::initialize(), Domaine_IJK::initialize_from_unstructured(), IJK_Grid_Geometry::initialize_from_unstructured(), Maillage_FT_IJK::initialize_processor_neighbourhood(), Matrice_Grossiere::interpolation_for_shear_periodicity(), DNS_QC_double::interpreter(), Execute_parallel::interpreter(), MaillerParallel::interpreter(), Calculer_Moments::interpreter_(), Extraire_plan::interpreter_(), Lire_Tgrid::interpreter_(), Remove_Invalid_Internal_Boundaries::interpreter_(), Champ_Fonc_MED_Table_Temps::lire_donnees_champ(), Transport_Interfaces_FT_Disc::lire_maillage_ft_cao(), Maillage_FT_IJK::lire_maillage_ft_dans_lata(), Sauvegarde_Reprise_Maillage_FT::lire_xyz(), AssembleurPVDF_PF::liste_faces_periodiques(), Assembleur_P_VDF::liste_faces_periodiques(), Op_EF_base::marque_elem(), Remaillage_FT::marquer_aretes(), MD_Vector_std::MD_Vector_std(), Chimie::mettre_a_jour(), Remailleur_Collision_FT_Thomas::mettre_a_jour_data(), moyenne_glissante::moyenne_glissante(), Multigrille_base::Multigrille_base(), Navier_Stokes_FTD_IJK::Navier_Stokes_FTD_IJK(), Maillage_FT_Disc::nettoyer_maillage(), Maillage_FT_IJK::nettoyer_maillage(), Maillage_FT_Disc::nettoyer_noeuds_virtuels_et_frontieres(), Maillage_FT_Disc::nettoyer_phase(), OctreeFloor_32_64< _SIZE_ >::OctreeFloor_32_64(), Parcours_interface::parcourir(), Parcours_interface::parcours_facette(), Polyedriser_32_64< _SIZE_ >::polyedriser(), IJK_Interfaces::posttraiter_champs_instantanes(), IJK_Interfaces::preparer_duplicata_bulles(), IJK_Interfaces::preparer_duplicata_bulles_masque_6bit(), OctreeRoot_32_64< _SIZE_ >::rang_arete(), OctreeRoot_32_64< _SIZE_ >::rang_elem(), OctreeRoot_32_64< _SIZE_ >::rang_elem_depuis(), OctreeRoot_32_64< _SIZE_ >::rang_elems_sommet(), OctreeRoot_32_64< _SIZE_ >::rang_sommet(), LireMED_32_64< _SIZE_ >::read_boundaries(), Tube_libre::readOn(), Convection_Diffusion_Temperature_FT_Disc::readOn(), Probleme_Couple::readOn(), Sous_Domaine_32_64< _SIZE_ >::readOn(), Maillage_FT_IJK::recopie_force_compo(), IJK_Interfaces::recursive_calcul_distance_chez_voisin(), Remaillage_FT::redistribuer_sommets(), Redistribute_Field::redistribute_(), Remaillage_FT::remaillage_local_interface(), Remaillage_FT_IJK::remaillage_local_interface(), Champ_front_contact_VEF::remplir_connect_bords(), Marching_Cubes::remplir_data_marching_cubes(), Op_Dift_EF_Q1::remplir_marqueur_elem_CL_paroi(), Polyedre_32_64< _SIZE_ >::remplir_Nodes_glob(), Marching_Cubes::remplir_renum_virt_loc(), Maillage_FT_Disc::remplir_structure(), Domaine_Cl_EF::remplir_type_elem_Cl(), Matrice_Morse_Sym::renumerote(), Collision_Model_FT_base::research_collision_pairs_Verlet(), Maillage_FT_Disc::reset(), Descripteur_FT::reset(), Intersections_Elem_Facettes::reset(), RTabInt::resize(), FT_Field::resize_array(), Descripteur_FT::retirer_elements(), RTabInt::RTabInt(), Octree_Double_32_64< _SIZE_ >::search_elements_box(), Octree_Int_32_64< _SIZE_ >::search_elements_box(), Octree_Double_32_64< _SIZE_ >::search_nodes_close_to(), forcage_spectral::set_a_force(), Collision_Model_FT_base::set_LC_zones(), forcage_spectral::set_spectral_domain(), Topologie_Maillage_FT::suppression_interfaces(), IJK_Interfaces::supprimer_certaines_bulles_reelles(), Remaillage_FT::supprimer_doublons_facettes(), IJK_Interfaces::supprimer_duplicata_bulles(), Remaillage_FT::supprimer_petites_aretes(), Remaillage_FT_IJK::supprimer_petites_aretes(), Topologie_Maillage_FT::test_collision_facettes(), Remailleur_Collision_FT_Thomas::traite_RuptureCoalescenceInterfaces_Conservatif(), Transport_Interfaces_FT_Disc::transfert_conservatif_eulerien_vers_lagrangien_sommets(), Remailleur_Collision_FT_Thomas::transport_volume_perdu_sur_sommet(), Maillage_FT_Disc::transporter(), Maillage_FT_Disc::transporter_simple(), TRUSTArrayFT< _TYPE_ >::TRUSTArrayFT(), Matrice_Sym::unsymmetrize_stencil_and_coefficients(), init_forcage_THI::update_advection_velocity(), and Maillage_FT_Disc::update_tableau_apres_transport().
ref_as_big()
template<typename _TYPE_ , typename _SIZE_ > void TRUSTArray< _TYPE_, _SIZE_ >::ref_as_big (TRUSTArray< _TYPE_, trustIdType > & out) const
References Process::exit().
ref_as_small() [1/3]
template<typename _TYPE_ , typename _SIZE_ > void TRUSTArray< _TYPE_, _SIZE_ >::ref_as_small (TRUSTArray< _TYPE_, int > & out) const
References Process::exit().
from_tid_to_int() [1/2]
template<typename _TYPE_ , typename _SIZE_ > void TRUSTArray< _TYPE_, _SIZE_ >::from_tid_to_int (TRUSTArray< int, int > & out) const
References Process::exit().
set_mem_storage()
template<typename _TYPE_ , typename _SIZE_ > void TRUSTArray< _TYPE_, _SIZE_ >::set_mem_storage (const STORAGE storage) inline
Memory allocation type - TEMP arrays (i.e. Trav) have a different allocation mechanism - see TRUSTTravPool.h)
Referenced by TRUSTTrav< _TYPE_ >::TRUSTTrav().
get_mem_storage()
template<typename _TYPE_ , typename _SIZE_ > STORAGE TRUSTArray< _TYPE_, _SIZE_ >::get_mem_storage () const inline
get_mem()
template<typename _TYPE_ , typename _SIZE_ > std::shared_ptr< Vector_ > TRUSTArray< _TYPE_, _SIZE_ >::get_mem () inline
operator=() [1/2]
template<typename _TYPE_ , typename _SIZE_ > TRUSTArray & TRUSTArray< _TYPE_, _SIZE_ >::operator= (const TRUSTArray< _TYPE_, _SIZE_ > &) inline
Referenced by TRUSTArray< _TYPE_, _SIZE_ >::copy_array(), and TRUSTArrayFT< _TYPE_ >::operator=().
operator[]() [1/2]
template<typename _TYPE_ , typename _SIZE_ > _TYPE_ & TRUSTArray< _TYPE_, _SIZE_ >::operator[] (_SIZE_ i) inline
Referenced by TRUSTArray< _TYPE_, _SIZE_ >::operator()().
operator[]() [2/2]
template<typename _TYPE_ , typename _SIZE_ > const _TYPE_ & TRUSTArray< _TYPE_, _SIZE_ >::operator[] (_SIZE_ i) const inline
operator()() [1/2]
template<typename _TYPE_ , typename _SIZE_ > _TYPE_ & TRUSTArray< _TYPE_, _SIZE_ >::operator() (_SIZE_ i) inline
References TRUSTArray< _TYPE_, _SIZE_ >::operator[]().
operator()() [2/2]
template<typename _TYPE_ , typename _SIZE_ > const _TYPE_ & TRUSTArray< _TYPE_, _SIZE_ >::operator() (_SIZE_ i) const inline
References TRUSTArray< _TYPE_, _SIZE_ >::operator[]().
addr() [1/2]
template<typename _TYPE_ , typename _SIZE_ > _TYPE_ * TRUSTArray< _TYPE_, _SIZE_ >::addr () inline
Referenced by Terme_Boussinesq_PolyMAC_Face::ajouter_blocs(), Masse_VDF_base::ajouter_blocs(), Op_Diff_PolyMAC_P0P1NC_Elem::ajouter_blocs_ext(), Op_Diff_PolyMAC_P0P1NC_Face::ajouter_blocs_ext(), Solveur_Masse_base::ajouter_masse(), Solveur_Masse_base::ajouter_masse_dt_local(), Matrice_SuperMorse::ajouter_mult_vect_et_prodscal(), Matrice_Morse::ajouter_multvect_(), Matrice_Morse_Sym::ajouter_multvect_(), Matrice_Bloc::ajouter_multvect_(), Matrice_Diagonale::ajouter_multvect_(), Matrice_Bloc_Sym::ajouter_multvect_(), Matrice_Bloc::ajouter_multvectT_(), SETS::assembler(), Domaine_VF::build_mc_dual_mesh(), Domaine_32_64< _SIZE_ >::build_mc_mesh(), Traitement_particulier_NS_THI_VEF::calcul_spectre_1D(), Tetra_VEF::calcul_vc(), Tetra_VEF::calcul_xg(), Fluide_base::calculer_nu(), Solv_Cholesky::Cholesky(), interface_INITGAUSS::Compute(), interface_CALCULSI::Compute(), interface_CALCULBIJ::Compute(), Partitionneur_Metis_32_64< _SIZE_ >::construire_partition(), Partitionneur_Tranche_32_64< _SIZE_ >::construire_partition(), Partitionneur_Fichier_MED::construire_partition(), Partitionneur_Parmetis::construire_partition(), Partitionneur_Ptscotch::construire_partition(), Terme_Puissance_Thermique_Echange_Impose_VEF_Face::contribuer_a_avec(), Matrix_tools::convert_to_morse_matrix_with_ptrs(), Solveur_Masse_base::corriger_solution(), Matrice_Morse::diagmulmat(), Op_Diff_PolyMAC_P0P1NC_Face::dimensionner_blocs_ext(), MD_Vector_tools::dump_vector_with_md(), IJK_Interfaces::dumplata_ft_mesh(), SETS::eliminer(), Solv_Cholesky::Fact_Cholesky(), ILU_SP::factoriser(), SurfaceVapeurIJKComputation::get_maillage_MED_from_IJK_FT(), MD_Vector_base::get_seq_flags_impl(), ICoCo::ProblemTrio::getDirectAccessToUnknown(), ILU_SP::ilu(), ILU_SP::ilut(), Echange_contact_PolyMAC_P0P1NC::init_f_dist(), Echange_contact_PolyMAC_P0::init_fs_dist(), Comm_Group::init_group_node(), Champ_Face_PolyMAC::interp_gve(), Decouper_multi::interpreter(), Matrice_Dense::inverse(), Matrice_Morse::inverse(), SolvElem_BiCGStab::iteration(), SolvElem_Gmres::iteration(), Matrice_Morse::largeur_de_bande(), Champ_front_recyclage::lire_fichier_format2(), Champ_front_recyclage::lire_fichier_format3(), Sauvegarde_Reprise_Maillage_FT::lire_xyz(), Chimie::mettre_a_jour(), Matrice_Morse_Sym::multvect_et_prodscal(), Matrice_Morse::operator()(), TRUSTTab< _TYPE_, _SIZE_ >::printOn(), Matrice_Morse::remplir(), Matrice_Bloc::remplir(), Connectivite_frontieres::remplir_faces_voisins(), Op_Diff_PolyMAC_base::remplir_nu_ef(), Marching_Cubes::remplir_renum_virt_loc(), Matrice_Morse_Sym::renumerote(), Champ_Inc_base::reprendre(), Solv_rocALUTION::resoudre_systeme(), Navier_Stokes_std_ALE::sauvegarder(), Champ_Inc_base::sauvegarder(), Convection_Diffusion_Fluide_Dilatable_Proto::Sauvegarder_WC(), Vecteur3::set(), Champ_Input_Proto::setValueOnTab(), TRUST_2_PDI::share_TRUSTTab_dimensions(), Matrice_Dense::solve(), Matrice_Morse::sort_stencil(), Switch_double::switch_scalar_field_direct(), Switch_double::switch_vit_direct(), Raccord_distant_homogene_32_64< _SIZE_ >::trace_face_distant(), Frontiere_32_64< _SIZE_ >::trace_face_local(), Marching_Cubes::trier_les_noeuds(), Champ_Fonc_Interp::update_fields(), Op_Diff_PolyMAC_P0_base::update_nu(), Op_Diff_PolyMAC_P0P1NC_base::update_nu(), Champ_Face_PolyMAC_P0::valeur_aux_elems_compo(), Vecteur3::Vecteur3(), and Domaine_VF::xv_bord().
addr() [2/2]
template<typename _TYPE_ , typename _SIZE_ > const _TYPE_ * TRUSTArray< _TYPE_, _SIZE_ >::addr () const inline
data() [1/2]
template<typename _TYPE_ , typename _SIZE_ > _TYPE_ * TRUSTArray< _TYPE_, _SIZE_ >::data () inline
Referenced by Champ_P1iP1B_implementation::filtrage(), Comm_Group::init_group_node(), and TRUSTTab< _TYPE_, _SIZE_ >::printOn().
data() [2/2]
template<typename _TYPE_ , typename _SIZE_ > const _TYPE_ * TRUSTArray< _TYPE_, _SIZE_ >::data () const inline
size_array()
template<typename _TYPE_ , typename _SIZE_ > _SIZE_ TRUSTArray< _TYPE_, _SIZE_ >::size_array () const inline
Return the size of the span on the data (not the full underlying allocated size)
Referenced by Schema_Comm_Vecteurs::add(), RTabInt::add(), CSR_Builder::add_coeff(), Matrix_tools::add_scaled_matrices(), Matrix_tools::add_symmetric_scaled_matrices(), Polygone_32_64< _SIZE_ >::affecte_connectivite_numero_global(), Polyedre_32_64< _SIZE_ >::affecte_connectivite_numero_global(), Matrice_Grossiere::ajoute_coeff(), Descripteur_FT::ajoute_element(), Descripteur_FT::ajoute_elements(), Intersections_Elem_Facettes::ajoute_intersection(), Op_Conv_VEF_Face::ajouter(), Op_Diff_VEF_Face::ajouter(), Domaine_32_64< _SIZE_ >::ajouter(), Terme_Source_Canal_perio_VEF_P1NC::ajouter(), Iterateur_Source_VEF_Face< _TYPE_ >::ajouter(), Operateur_Conv_sensibility_VEF::ajouter_conv_term(), Scatter::ajouter_joints(), Operateur_Conv_sensibility_VEF::ajouter_Lsensibility_state_Amont(), Operateur_Conv_sensibility_VEF::ajouter_Lstate_sensibility_Amont(), Maillage_FT_Disc::ajouter_maillage(), Matrice_SuperMorse::ajouter_mult_vect_et_prodscal(), Matrice_Morse::ajouter_multvect_(), Matrice_Bloc::ajouter_multvect_(), Matrice_Dense::ajouter_multvect_(), Matrice_Bloc_Sym::ajouter_multvect_(), Matrice_Morse::ajouter_multvectT_(), Matrice_Bloc::ajouter_multvectT_(), Matrice_Dense::ajouter_multvectT_(), Op_Grad_VEF_P1B_Face::ajouter_som(), Op_Conv_ALE_VEF::ajouterALE(), MD_Vector_base::append_blocs(), MD_Vector_std::append_from_other_std(), MD_Vector_base::append_item_to_blocs(), MD_Vector_base::append_items(), Assembleur_P_VEFPreP1B::assembler_rho_variable(), Assembleur_P_EF::assembler_rho_variable(), Pb_Couple_rayo_semi_transp::associer_(), FT_Field::avancer_en_temps(), IJK_One_Dimensional_Subproblems_Interfaces_Fields::averaged_by_vertex_surface(), Schema_Comm_Vecteurs::begin_comm(), BilanQdmVEF::bilan_energie(), BilanQdmVEF::bilan_qdm(), Octree_Int_32_64< _SIZE_ >::build(), Refine_Mesh::build_edges(), Domaine_32_64< _SIZE_ >::build_mc_mesh(), Matrix_tools::build_morse_matrix(), Octree_Int_32_64< _SIZE_ >::build_octree_floor(), Octree_Int_32_64< _SIZE_ >::build_octree_recursively(), Polyedre_32_64< _SIZE_ >::build_reduced(), Polygone_32_64< _SIZE_ >::build_reduced(), Matrix_tools::build_symmetric_morse_matrix(), Maillage_FT_Disc::calcul_courbure_sommets(), Couplage_Tubes_IBC::calcul_F_pression(), Couplage_Tubes_IBC::calcul_F_pression2(), Reaction::calcul_proportion_implicite(), Desc_Structure_FT::calcul_schema_comm(), Domaine_EF::calculer_Bij(), Transport_Interfaces_FT_Disc::calculer_distance_interface(), Op_Dift_EF_Q1::calculer_dt_stab(), Op_Conv_VEF_base::calculer_dt_stab(), Op_Dift_VEF_base::calculer_dt_stab(), Scatter::calculer_espace_distant(), Op_Grad_EF::calculer_flux_bords(), Op_Grad_VDF_Face::calculer_flux_bords(), Op_Grad_VEF_P1B_Face::calculer_flux_bords(), Modele_turbulence_scal_LES_dyn_VDF::calculer_grad_teta(), Partitionneur_base_32_64< _SIZE_ >::calculer_graphe_connexions_periodiques(), Algorithmes_Transport_FT_Disc::calculer_moments_indicatrice(), Scatter::calculer_nb_items_virtuels(), IJK_Interfaces::calculer_phi_repuls_sommet(), Senseur_Interface::calculer_position(), Op_Diff_VEF_base::calculer_pour_post(), Op_Dift_VEF_base::calculer_pour_post(), Scatter::calculer_renum_items_communs(), Eval_Puiss_Th_QC_VDF_Elem::calculer_terme_source(), Modele_turbulence_hyd_LES_Smago_VEF::calculer_viscosite_turbulente(), IJK_Interfaces::calculer_vmoy_rotation_composantes_connexes(), IJK_Interfaces::calculer_vmoy_translation_composantes_connexes(), Maillage_FT_Disc::calculer_voisinage_facettes(), FT_Field::calculer_volume_bulles(), Domaine_EF::calculer_volumes_sommets(), FT_Field::champ_sommet_from_facettes(), Desc_Structure_FT::check(), Schema_Comm_Vecteurs::check_buffers_full(), FT_Field::check_conservation(), Collision_Model_FT_base::check_for_duplicates(), Maillage_FT_Disc::check_mesh(), Maillage_FT_IJK::check_mesh(), Schema_Comm_Vecteurs::check_next_area(), Schema_Comm::check_send_recv_pe_list(), Maillage_FT_Disc::check_sommets(), Maillage_FT_IJK::check_sommets(), Remaillage_FT::chercher_arete_tab(), Scatter::Chercher_Correspondance(), IJK_One_Dimensional_Subproblems::clear_sort_problems_colliding_bubbles(), Matrice_Morse_Sym::compacte(), Corrige_flux_FT_temperature_subresolution::complete_thermal_fluxes_face_centre(), Raccord_distant_homogene_32_64< _SIZE_ >::completer(), Navier_Stokes_FTD_IJK::completer(), Periodique::completer(), Op_Conv_VEF_Face::completer(), FT_Field::completer_compo_connexe_partielle(), Statistiques_dns_ijk_FT::completer_print(), Schema_Adams_Bashforth_order_2::compute_adams_bashforth_coefficients(), Schema_Adams_Bashforth_order_3::compute_adams_bashforth_coefficients(), Schema_Adams_Moulton_order_2::compute_adams_moulton_coefficients(), Schema_Adams_Moulton_order_3::compute_adams_moulton_coefficients(), Schema_Backward_Differentiation_order_2::compute_backward_differentiation_coefficients(), Schema_Backward_Differentiation_order_3::compute_backward_differentiation_coefficients(), Corrige_flux_FT_temperature_subresolution::compute_cell_neighbours_faces_indices_for_spherical_correction(), Corrige_flux_FT_temperature_subresolution::compute_cell_neighbours_faces_indices_to_correct(), IJK_Interfaces::compute_cell_phase_with_interface_normal(), IJK_Composantes_Connex::compute_compo_connex_from_interface(), Statistiques_dns_ijk_FT::compute_desequil_alpha(), Convection_Diffusion_Temperature_FT_Disc::compute_divergence_free_velocity_extension(), IJK_Interfaces::compute_drapeaux_vapeur_v4(), IJK_Interfaces::compute_external_forces_color_function(), IJK_Interfaces::compute_external_forces_parser(), Post_Processing_Hydrodynamic_Forces::compute_heat_transfer(), Corrige_flux_FT_temperature_subresolution::compute_ijk_pure_faces_indices(), IJK_Interfaces::compute_indicatrice_non_perturbe(), ComputeValParCompoInCell::compute_list_compo_connex_in_element(), Corrige_flux_FT_temperature_subresolution::compute_min_max_ijk_any_reachable_fluxes(), Redistribute_Field::compute_send_blocs(), Triple_Line_Model_FT_Disc::compute_TCL_fluxes_in_all_boundary_cells(), Corrige_flux_FT_temperature_subresolution::compute_temperature_cell_centre_neighbours(), Corrige_flux_FT_temperature_subresolution::compute_thermal_fluxes_face_centre(), Corrige_flux_FT_temperature_subresolution::compute_thermal_fluxes_face_centre_discrete_integral(), moyenne_glissante::compute_v_cible(), Navier_Stokes_FTD_IJK::compute_var_volume_par_bulle(), Domaine_Cl_dis_base::condition_limite_de_la_face_virtuelle(), Octree_32_64< _SIZE_ >::construire(), Domain_Graph::construire_graph_from_segment(), Scatter::construire_md_vector(), Marching_Cubes::construire_noeuds_uniques(), Partitionneur_Tranche_32_64< _SIZE_ >::construire_partition(), Partitionneur_Fichier_Decoupage::construire_partition(), Partitionneur_Partition::construire_partition(), Partitionneur_Sous_Domaine::construire_partition(), Partitionneur_Union::construire_partition(), Hexaedre_32_64< _SIZE_ >::contient(), Hexaedre_axi_32_64< _SIZE_ >::contient(), Hexaedre_VEF_32_64< _SIZE_ >::contient(), Point_32_64< _SIZE_ >::contient(), Prisme_32_64< _SIZE_ >::contient(), Quadrangle_VEF_32_64< _SIZE_ >::contient(), Rectangle_32_64< _SIZE_ >::contient(), Rectangle_axi_32_64< _SIZE_ >::contient(), Segment_32_64< _SIZE_ >::contient(), Tetraedre_32_64< _SIZE_ >::contient(), Triangle_32_64< _SIZE_ >::contient(), Descripteur_FT::contient_element(), IJK_Interfaces::convert_to_IntVect(), Maillage_FT_Disc::convertir_numero_distant_local(), Convection_Diffusion_Temperature_FT_Disc::correct_mpoint(), Triple_Line_Model_FT_Disc::correct_wall_adjacent_temperature_according_to_TCL_fluxes(), FT_Field::correction_conservation_globale(), Marching_Cubes::correspondance_espaces_distant_virtuel(), Paroi_hyd_base_EF::corriger_derivee_impl(), Paroi_hyd_base_VEF::corriger_derivee_impl(), Scatter::corriger_espace_distant_elements_perio(), Triple_Line_Model_FT_Disc::corriger_mpoint(), Triple_Line_Model_FT_Disc::corriger_secmem(), Partitionneur_base_32_64< _SIZE_ >::corriger_sommets_bord(), PE_Groups::create_group(), Maillage_FT_Disc::creer_facettes_virtuelles(), MD_Vector_tools::creer_md_vect_renum_auto(), Domaine_32_64< int >::creer_mes_domaines_frontieres(), Maillage_FT_Disc::creer_sommets_virtuels(), Maillage_FT_Disc::creer_sommets_virtuels_numowner(), Champ_Fonc_base::creer_tableau_distribue(), Champ_Inc_base::creer_tableau_distribue(), Maillage_FT_Disc::deplacer_sommets(), Maillage_FT_IJK::deplacer_sommets(), Convection_Diffusion_Temperature_FT_Disc::derivee_en_temps_inco(), Transport_Marqueur_FT::detection_groupes_a_supprimer(), Matrice_Morse::diagmulmat(), Op_EF_base::dimensionner(), Matrice_Morse::dimensionner(), Collision_Model_FT_sphere::discretize_contact_forces_eulerian_field(), MD_Vector_tools::dump_vector_with_md(), IJK_Interfaces::dumplata_ft_mesh(), IJK_Interfaces::dupliquer_bulle_perio(), Schema_Comm::echange_messages(), Schema_Comm::echange_taille(), Schema_Comm::echange_taille_et_messages(), Desc_Structure_FT::echanger_elements(), Maillage_FT_Disc::echanger_facettes(), Maillage_FT_Disc::echanger_sommets_PE(), IJK_Thermal_base::ecrire_statistiques_bulles(), Op_EF_base::elem_contribue(), Remailleur_Collision_FT_Thomas::elements_voisins(), Remailleur_Collision_FT_Thomas::elements_voisins_a_distance_plus_petite2(), SETS::eliminer(), Schema_Comm::end_comm(), Schema_Comm_Vecteurs::end_init(), Moyenne_volumique::eval_filtre(), Schema_Comm_Vecteurs::exchange(), FT_Field::exchange_compo_connexe(), Equation_base::expression_residu(), Reaction::extract_coef(), Champ_Generique_Reduction_0D::extraire(), Matrix_tools::fill_csr_arrays(), MD_Vector_std::fill_md_vect_renum(), IJK_Composantes_Connex::fill_mixed_cell_compo(), Milieu_base::fill_section_passage_face(), Refine_Mesh::find_edge(), Couplage_Tubes_IBC::force_ibc_velocity(), Couplage_Tubes_IBC::force_ibc_velocity_anticipe_cube(), Couplage_Tubes_IBC::force_ibc_velocity_frac_vol(), Couplage_Tubes_IBC::force_ibc_velocity_miroir(), Couplage_Tubes_IBC::force_ibc_velocity_symetrie_plane(), Source_PDF_EF::get_champ(), Paroi_hyd_base_EF::get_champ(), Turbulence_paroi_base::get_champ(), IJK_Interfaces::get_ghost_number_from_compo(), Collision_Model_FT_base::get_last_id(), Intersections_Elem_Facettes::get_liste_elements_traverses(), Domaine_IJK::get_nb_elem_tot(), IJK_Grid_Geometry::get_nb_elem_tot(), MD_Vector_base::get_seq_flags_impl(), Domaine_IJK::get_slice_size(), Matrice_Morse::get_stencil(), Matrice_Morse::get_stencil_and_coefficients(), Matrice_Morse::get_stencil_coeff_templ(), Matrice_Bloc_Sym::get_symmetric_stencil_and_coefficients(), Matrice_Morse_Sym::get_symmetric_stencil_and_coefficients(), Domaine_IJK::get_volume_elem(), Matrice_Morse::has_same_morse_matrix_structure(), Couplage_Tubes_IBC::ibc0_force_cube(), Couplage_Tubes_IBC::ibc0_velocity_cube(), Couplage_Tubes_IBC::ibc_diffuse_force_cube(), Couplage_Tubes_IBC::ibc_diffuse_velocity_cube(), Couplage_Tubes_IBC::ibc_localisee_velocity_cube(), Couplage_Tubes_IBC::ibc_localisee_velocity_cube_qdm(), Transport_Interfaces_FT_Disc::impr(), Navier_Stokes_std::impr(), Equation_base::imprime_residu(), Sonde::init_bords(), Comm_Group::init_group(), Comm_Group_Noparallel::init_group(), Raccord_distant_homogene_32_64< _SIZE_ >::initialise(), Cut_cell_FT_Disc::initialise_communications(), Sonde::initialiser(), Partitionneur_Tranche_32_64< _SIZE_ >::initialiser(), DomaineCutter_32_64< _SIZE_ >::initialiser(), Ch_front_input_uniforme::initialiser(), Ch_front_input_P1::initialiser(), Fourier_trans::initialize(), IJK_Interfaces::initialize(), Domaine_IJK::initialize_from_unstructured(), IJK_Grid_Geometry::initialize_from_unstructured(), Domaine_IJK::initialize_mapping(), Domaine_IJK::initialize_with_mapping(), TRUSTArray< _TYPE_, _SIZE_ >::inject_array(), Corrige_flux_FT_temperature_conv::interp_back_to_bary_faces(), IJK_Thermal_Subresolution::interpolate_convective_term_on_downstream_line(), DNS_QC_double::interpreter(), Execute_parallel::interpreter(), MaillerParallel::interpreter(), Lata_2_Other::interpreter(), Create_domain_from_sub_domain::interpreter_(), DecoupeBord_32_64< _SIZE_ >::interpreter_(), Extraire_plan::interpreter_(), ExtrudeParoi::interpreter_(), Redresser_hexaedres_vdf::interpreter_(), Corriger_frontiere_periodique_32_64< _SIZE_ >::interpreter_(), Remove_Invalid_Internal_Boundaries::interpreter_(), Matrice_Dense::inverse(), FT_Field::is_compo_in_proc(), Probleme_Couple::iterateTimeStep(), Domaine_VEF::lecture_ok_arete(), Champ_Fonc_MED::lire(), Champ_front_recyclage::lire_fichier_format2(), Champ_front_recyclage::lire_fichier_format3(), Transport_Interfaces_FT_Disc::lire_maillage_ft_cao(), Maillage_FT_IJK::lire_maillage_ft_dans_lata(), Perte_Charge_Singuliere::lire_surfaces(), Sauvegarde_Reprise_Maillage_FT::lire_xyz(), Remaillage_FT::marquer_aretes(), MD_Vector_std::MD_Vector_std(), Eval_Dift_VDF_Face::mettre_a_jour(), Transport_Interfaces_FT_Disc::mettre_a_jour(), Terme_Source_Constituant_Vortex_VEF_Face::mettre_a_jour(), Op_Dift_EF_base::mettre_a_jour(), Champ_front_xyz_debit::mettre_a_jour(), Champ_Fonc_MED_Tabule::mettre_a_jour(), Champ_front_recyclage::mettre_a_jour(), Terme_Boussinesq_base::mettre_a_jour(), Op_Dift_VEF_base::mettre_a_jour(), Echange_contact_VDF_FT_Disc::mettre_a_jour(), Sonde::mettre_a_jour_bords(), Remailleur_Collision_FT_Thomas::mettre_a_jour_data(), Domaine_Cl_EF::modifie_gradient(), Op_Diff_K_Eps_VEF_Face::modifier_pour_Cl(), Op_Diff_K_Omega_VEF_Face::modifier_pour_Cl(), Remailleur_Collision_FT_Thomas::nb_elements_voisins(), Remailleur_Collision_FT_Thomas::nb_elements_voisins_a_distance_plus_petite(), Front_VF::nb_faces_tot(), Frontiere_32_64< _SIZE_ >::nb_faces_virt(), Maillage_FT_Disc::nettoyer_maillage(), Maillage_FT_Disc::nettoyer_noeuds_virtuels_et_frontieres(), Maillage_FT_Disc::nettoyer_phase(), Multigrille_base::nsweeps_jacobi_residu(), Front_VF::num_face(), Front_VF::num_local_face(), TRUSTArray< _TYPE_, _SIZE_ >::operator+=(), TRUSTArray< _TYPE_, _SIZE_ >::operator-=(), Intersections_Elem_Facettes::operator=(), Parcours_interface::parcourir(), Parcours_interface::parcours_facette(), FT_Field::passer_variable_extensive(), FT_Field::passer_variable_intensive(), IJK_Thermal_Subresolution::post_processed_fields_on_downstream_line(), Statistiques_dns_ijk::postraiter(), IJK_Interfaces::postraiter_colors(), Statistiques_dns_ijk::postraiter_k(), Fourier_trans::postraiter_TFi(), Statistiques_dns_ijk_FT::postraiter_thermique(), IJK_Interfaces::posttraiter_tous_champs(), Solv_GCP::prepare_data(), Maillage_FT_Disc::preparer_tableau_avant_transport(), Maillage_FT_Disc::printFa7(), TRUSTTab< _TYPE_, _SIZE_ >::printOn(), IJK_Interfaces::printOn(), Descripteur_FT::printOn(), Eval_centre_PolyMAC_Elem::qcentre(), Objet_a_lire::read(), Senseur_Interface::readOn(), IJK_Interfaces::readOn(), Frontiere_ouverte_vitesse_vortex::readOn(), Convection_Diffusion_Temperature_FT_Disc::readOn(), Descripteur_FT::readOn(), Terme_Source_Constituant_Vortex_VEF_Face::readOn(), Triple_Line_Model_FT_Disc::readOn(), IJK_VDF_converter::readOn(), Champ_input_P0::readOn(), Ch_input_uniforme::readOn(), MD_Vector_std::readOn(), Champ_Fonc_MED::readOn(), Pbc_MED::readOn(), TRUSTTab< _TYPE_, _SIZE_ >::readOn(), TRUSTVect< _TYPE_, _SIZE_ >::readOn(), Corrige_flux_FT_temperature_subresolution::receive_all_fluxes_from_outisde_frontier_on_procs(), Corrige_flux_FT_temperature_subresolution::receive_fluxes_from_frontier_on_procs(), Corrige_flux_FT_temperature_subresolution::receive_temperature_cell_centre_neighbours_from_procs(), IJK_Interfaces::recursive_calcul_distance_chez_voisin(), Remaillage_FT::redistribuer_sommets(), Remaillage_FT::regulariser_maillage(), Multigrille_base::relax_jacobi(), FT_Field::remailler_FT_Field(), Topologie_Maillage_FT::remailler_interface(), Matrice_Bloc::remplir(), Assembleur_P_VEF::remplir(), Desc_Structure_FT::remplir_element_pe(), Connectivite_frontieres::remplir_faces_voisins(), Domaine_Cl_VEF::remplir_volumes_entrelaces_Cl(), Marching_Cubes::renum_sommets_dist_loc(), Matrice_Morse_Sym::renumerote(), Groupes_Faces_32_64< _SIZE_ >::renumerote(), Scatter::reordonner_faces_de_joint(), Fourier_trans::reprise(), Precond_local::res_syst_loc_hybride(), Collision_Model_FT_base::research_collision_pairs_Verlet(), RTabInt::resize(), Solv_Petsc::resoudre_systeme(), Solv_rocALUTION::resoudre_systeme(), Descripteur_FT::retirer_elements(), IJK_One_Dimensional_Subproblems::retrieve_interfacial_heat_flux_correction_on_procs(), IJK_One_Dimensional_Subproblems_Interfaces_Fields::retrieve_interfacial_surface_quantity(), Comm_Group_Noparallel::reverse_send_recv_list(), DNS_QC_double::run(), FT_Field::sauv_num_pe_echange(), Navier_Stokes_std_ALE::sauvegarder(), Maillage_FT_Disc::sauvegarder(), Transport_Interfaces_FT_Disc::sauvegarder(), Champ_Fonc_base::sauvegarder(), Champ_Inc_base::sauvegarder(), Collision_Model_FT_base::sauvegarder(), Convection_Diffusion_Fluide_Dilatable_Proto::Sauvegarder_WC(), Octree_Double_32_64< _SIZE_ >::search_elements_box(), Octree_Int_32_64< _SIZE_ >::search_elements_box(), Octree_Double_32_64< _SIZE_ >::search_nodes_close_to(), Comm_Group_MPI::send_recv_start(), Comm_Group_Noparallel::send_recv_start(), Collision_Model_FT_base::set_LC_zones(), Static_Int_Lists_32_64< _SIZE_ >::set_list_sizes(), Triple_Line_Model_FT_Disc::set_wall_adjacent_temperature_according_to_TCL_model(), IJK_One_Dimensional_Subproblems::share_boundary_previous_values(), IJK_One_Dimensional_Subproblems::share_interfacial_heat_flux_correction_on_procs(), FT_Field::size(), FT_Field::size_array(), FT_Field::size_sommets(), Corrige_flux_FT_temperature_subresolution::smooth_temperature_cell_centre_neighbours(), Matrice_Dense::solve(), Solv_Gen::solve(), Corrige_flux_FT_temperature_subresolution::sort_ini_end_arrays(), SSOR::ssor(), IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::sum_sparse_matrices_subproblems(), IJK_Interfaces::supprimer_certaines_bulles_reelles(), Maillage_FT_Disc::supprimer_facettes(), Remaillage_FT::supprimer_petites_aretes(), Remaillage_FT_IJK::supprimer_petites_aretes(), Navier_Stokes_FT_Disc::swap_particles_eulerian_id_number(), Switch_double::switch_scalar_field_direct(), Switch_double::switch_vit_direct(), Topologie_Maillage_FT::test_collision_facettes(), Transport_Interfaces_FT_Disc::test_suppression_interfaces_sous_domaine(), Raccord_distant_homogene_32_64< _SIZE_ >::trace_elem_distant(), Frontiere_32_64< _SIZE_ >::trace_elem_local(), Raccord_distant_homogene_32_64< _SIZE_ >::trace_face_distant(), Frontiere_32_64< _SIZE_ >::trace_som_local(), IJK_Interfaces::transferer_bulle_perio(), Transport_Interfaces_FT_Disc::transfert_conservatif_eulerien_vers_lagrangien_sommets(), Remailleur_Collision_FT_Thomas::transport_volume_perdu_sur_element(), Remailleur_Collision_FT_Thomas::transport_volume_perdu_sur_sommet(), TRUSTArray< _TYPE_, _SIZE_ >::TRUSTArray(), Matrice_Sym::unsymmetrize_stencil_and_coefficients(), Fourier_trans::update(), Schema_Temps_base::update_critere_statio(), Solv_Externe::Update_lhs_rhs(), Solv_Externe::Update_solution(), Statistiques_dns_ijk::update_stat(), Statistiques_dns_ijk_monophasique::update_stat(), Statistiques_dns_ijk::update_stat_k(), IJK_Interfaces::update_surface_normale(), Maillage_FT_Disc::update_tableau_apres_transport(), Corrige_flux_FT_temperature_conv::update_temperature_ghost(), Tube_libre::update_vitesse_position(), Domaine_IJK::update_volume_elem(), Champ_som_lu::valeur_aux_elems(), Champ_som_lu::valeur_aux_elems_compo(), Champ_implementation_P1::value_interpolation(), Champ_implementation_Q1::value_interpolation(), Vecteur3::Vecteur3(), DebogIJK::verifier(), DebogFT::verifier_(), Assembleur_P_VEFPreP1B::verifier_dirichlet(), and Verifier_Qualite_Raffinements_32_64< _SIZE_ >::verifier_qualite_raffinements().
ref_count()
template<typename _TYPE_ , typename _SIZE_ > int TRUSTArray< _TYPE_, _SIZE_ >::ref_count () const inline
Returns the number of owners of the data, i.e. the number of Arrays pointing to the same underlying data
append_array()
template<typename _TYPE_ , typename _SIZE_ > void TRUSTArray< _TYPE_, _SIZE_ >::append_array (_TYPE_ valeur) inline
Add a slot at the end of the array and store it valeur -> similar to vector<>::push_back
Referenced by Schema_Comm_Vecteurs::add(), CSR_Builder::add_coeff(), Objet_a_lire::add_dict(), Matrice_Grossiere::add_dist_bloc(), MD_Vector_composite::add_part(), Matrice_Grossiere::add_virt_bloc(), Descripteur_FT::ajoute_element(), Sonde::ajouter_bords(), Scatter::ajouter_joints(), MD_Vector_std::append_from_other_std(), MD_Vector_base::append_item_to_blocs(), Maillage_FT_Disc::associer_domaine_dis_parcours(), Polyedre_32_64< _SIZE_ >::build_reduced(), Polygone_32_64< _SIZE_ >::build_reduced(), Parcours_interface::calcul_intersection_facelem_3D(), Descripteur_FT::calcul_liste_pe_voisins(), Transport_Interfaces_FT_Disc::calculer_distance_interface(), Scatter::calculer_espace_distant(), Scatter::check_consistancy_remote_items(), Corrige_flux_FT_temperature_subresolution::check_pure_fluxes_duplicates(), IJK_One_Dimensional_Subproblems::clear_sort_problems_colliding_bubbles(), Raccord_distant_homogene_32_64< _SIZE_ >::completer(), IJK_Composantes_Connex::compute_compo_connex_from_interface(), IJK_Interfaces::compute_external_forces_color_function(), ComputeValParCompoInCell::compute_list_compo_connex_in_element(), Corrige_flux_FT_temperature_subresolution::compute_min_max_ijk_any_reachable_fluxes(), Triple_Line_Model_FT_Disc::compute_TCL_fluxes_in_all_boundary_cells(), Corrige_flux_FT_temperature_subresolution::compute_temperature_cell_centre_neighbours_on_procs(), moyenne_glissante::compute_v_cible(), Scatter::construire_md_vector(), Partitionneur_Tranche_32_64< _SIZE_ >::construire_partition(), Maillage_FT_Disc::corriger_proprietaires_facettes(), Partitionneur_base_32_64< _SIZE_ >::corriger_sommets_bord(), Maillage_FT_Disc::creer_facettes_virtuelles(), Maillage_FT_Disc::creer_sommets_virtuels(), Maillage_FT_Disc::creer_sommets_virtuels_numowner(), Maillage_FT_IJK::deplacer_sommets(), Maillage_FT_Disc::deplacer_un_sommet(), IJK_One_Dimensional_Subproblem::dispatch_interfacial_heat_flux_correction(), IJK_Interfaces::dupliquer_bulle_perio(), Maillage_FT_Disc::echanger_facettes(), Maillage_FT_Disc::echanger_sommets_PE(), Remailleur_Collision_FT_Thomas::elements_voisins(), Domaine_bord_32_64< _SIZE_ >::extraire_domaine_bord(), IJK_Composantes_Connex::fill_mixed_cell_compo(), Intersections_Elem_Facettes::get_liste_elements_traverses(), Intersections_Elem_Facettes::get_liste_facettes_traversantes(), Matrice_Morse_Sym::get_symmetric_stencil_and_coefficients(), Cut_cell_FT_Disc::initialise_schema_comm(), VDF_to_IJK::initialize(), Maillage_FT_IJK::initialize_processor_neighbourhood(), Create_domain_from_sub_domain::interpreter_(), Maillage_FT_IJK::lire_maillage_ft_dans_lata(), Transport_Interfaces_FT_Disc::lire_motcle_non_standard(), Sauvegarde_Reprise_Maillage_FT::lire_xyz(), Remaillage_FT::marquer_aretes(), MD_Vector_std::MD_Vector_std(), Remailleur_Collision_FT_Thomas::mettre_a_jour_data(), Maillage_FT_Disc::nettoyer_maillage(), Maillage_FT_Disc::nettoyer_noeuds_virtuels_et_frontieres(), Maillage_FT_Disc::nettoyer_phase(), Parcours_interface::parcours_facette(), IJK_Thermal_Subresolution::post_process_thermal_wake_slices(), IJK_Interfaces::read_bubbles_barycentres_vel(), Triple_Line_Model_FT_Disc::readOn(), Coarsen_Operator_K::readOn(), Domaine_IJK::readOn(), IJK_Grid_Geometry::readOn(), IJK_Interfaces::recursive_calcul_distance_chez_voisin(), Corrige_flux_FT_temperature_subresolution::remove_non_overlapping_fluxes_values(), Scatter::reordonner_faces_de_joint(), Corrige_flux_FT_temperature_subresolution::replace_temperature_cell_centre_neighbours(), Collision_Model_FT_base::research_collision_pairs_Verlet(), Descripteur_FT::retirer_elements(), IJK_One_Dimensional_Subproblems_Interfaces_Fields::retrieve_interfacial_surface_quantity(), Collision_Model_FT_base::set_LC_zones(), Corrige_flux_FT_temperature_subresolution::smooth_temperature_cell_centre_neighbours(), Corrige_flux_FT_temperature_subresolution::sort_ijk_intersections_subproblems_indices_fluxes_by_k_layers(), IJK_One_Dimensional_Subproblems::sort_limited_probes_spherical_coords_post_processing(), IJK_Interfaces::supprimer_duplicata_bulles(), Remaillage_FT::supprimer_petites_aretes(), Remaillage_FT_IJK::supprimer_petites_aretes(), Topologie_Maillage_FT::test_collision_facettes(), and Transport_Interfaces_FT_Disc::test_suppression_interfaces_sous_domaine().
operator=() [2/2]
template<typename _TYPE_ , typename _SIZE_ > TRUSTArray< _TYPE_, _SIZE_ > & TRUSTArray< _TYPE_, _SIZE_ >::operator= (_TYPE_ x)
Assign 'x' to all slots in the array
Remplit le tableau avec la x en parametre (x est affecte a toutes les cases du tableau)
operator+=() [1/2]
template<typename _TYPE_ , typename _SIZE_ > TRUSTArray< _TYPE_, _SIZE_ > & TRUSTArray< _TYPE_, _SIZE_ >::operator+= (const TRUSTArray< _TYPE_, _SIZE_ > & y)
Addition case a case sur toutes les cases du tableau : la taille de y doit etre au moins egale a la taille de this
References TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and TRUSTArray< _TYPE_, _SIZE_ >::view_ro().
operator+=() [2/2]
template<typename _TYPE_ , typename _SIZE_ > TRUSTArray< _TYPE_, _SIZE_ > & TRUSTArray< _TYPE_, _SIZE_ >::operator+= (const _TYPE_ dy)
ajoute la meme valeur a toutes les cases du tableau
Ajoute la meme valeur a toutes les cases du tableau
operator-=() [1/2]
template<typename _TYPE_ , typename _SIZE_ > TRUSTArray< _TYPE_, _SIZE_ > & TRUSTArray< _TYPE_, _SIZE_ >::operator-= (const TRUSTArray< _TYPE_, _SIZE_ > & y)
Soustraction case a case sur toutes les cases du tableau : tableau de meme taille que *this
References TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and TRUSTArray< _TYPE_, _SIZE_ >::view_ro().
operator-=() [2/2]
template<typename _TYPE_ , typename _SIZE_ > TRUSTArray< _TYPE_, _SIZE_ > & TRUSTArray< _TYPE_, _SIZE_ >::operator-= (const _TYPE_ dy)
soustrait la meme valeur a toutes les cases
operator*=()
template<typename _TYPE_ , typename _SIZE_ > TRUSTArray< _TYPE_, _SIZE_ > & TRUSTArray< _TYPE_, _SIZE_ >::operator*= (const _TYPE_ dy)
muliplie toutes les cases par dy
operator/=()
template<typename _TYPE_ , typename _SIZE_ > TRUSTArray< _TYPE_, _SIZE_ > & TRUSTArray< _TYPE_, _SIZE_ >::operator/= (const _TYPE_ dy)
divise toutes les cases par dy (pas pour TRUSTArray<int>)
inject_array()
template<typename _TYPE_ , typename _SIZE_ > TRUSTArray< _TYPE_, _SIZE_ > & TRUSTArray< _TYPE_, _SIZE_ >::inject_array (const TRUSTArray< _TYPE_, _SIZE_ > & source, _SIZE_ nb_elements = -1, _SIZE_ first_element_dest = 0, _SIZE_ first_element_source = 0)
Copie les elements source[first_element_source + i] dans les elements (*this)[first_element_dest + i] pour 0 <= i < nb_elements Les autres elements de (*this) sont inchanges.
Parameters
const ArrOfDouble& m: le tableau a utiliser, doit etre different de *this !
_SIZE_ nb_elements: nombre d'elements a copier, nb_elements >= -1. Si nb_elements==-1, on copie tout le tableau m. Valeurs par defaut: -1
_SIZE_ first_element_dest. Valeurs par defaut: 0
_SIZE_ first_element_source. Valeurs par defaut: 0
Returns
ArrOfDouble& : *this
Exceptions
Sort en erreur si la taille du tableau m est plus grande que la taille de tableau this.
References TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by Maillage_FT_IJK::ajouter_maillage_IJK(), Partitionneur_Tranche_32_64< _SIZE_ >::construire_partition(), IJK_Interfaces::convert_to_IntVect(), IJK_Interfaces::dupliquer_bulle_perio(), ExtrudeParoi::extrude(), FT_Field::inject_array(), Champ_front_recyclage::mettre_a_jour(), Discret_Thyd::section_passage(), Op_Diff_DG_base::update_nu(), and Op_Diff_PolyMAC_base::update_nu().
copy_array()
template<typename _TYPE_ , typename _SIZE_ > TRUSTArray & TRUSTArray< _TYPE_, _SIZE_ >::copy_array (const TRUSTArray< _TYPE_, _SIZE_ > & a) inline
References TRUSTArray< _TYPE_, _SIZE_ >::operator=().
Referenced by Champ_front_contact_VEF::calcul_grads_transf(), FT_Field::copy_FT_Field(), IJK_Interfaces::dupliquer_bulle_perio(), and Maillage_FT_IJK::recopie().
ordonne_array()
template<typename _TYPE_ , typename _SIZE_ > void TRUSTArray< _TYPE_, _SIZE_ >::ordonne_array () inline
Referenced by Scatter::calculer_espace_distant(), Collision_Model_FT_base::check_for_duplicates(), Schema_Comm::check_send_recv_pe_list(), OctreeFloor_32_64< _SIZE_ >::construire(), Schema_Comm_Vecteurs::end_init(), Matrice_Morse::get_stencil(), Matrice_Morse_Sym::get_symmetric_stencil(), Traitement_particulier_NS_canal::remplir_reordonne_Y_tot(), Domaine_VF::renumeroter(), Domaine_VDF::reordonner(), Scatter::trier_les_joints(), and Static_Int_Lists_32_64< _SIZE_ >::trier_liste().
ref_data()
template<typename _TYPE_ , typename _SIZE_ > virtual void TRUSTArray< _TYPE_, _SIZE_ >::ref_data (_TYPE_ * ptr, _SIZE_ size) inline virtual
Construction de tableaux qui pointent vers des donnees existantes !!! Utiliser ref_data avec precaution
Reimplemented in TRUSTVect< _SIZE_, _SIZE_ >, TRUSTTab< _SIZE_ >, TRUSTVect< _TYPE_, _SIZE_ >, TRUSTTab< _TYPE_, _SIZE_ >, TRUSTTab< _TYPE_ >, TRUSTVect< _TYPE_, int >, TRUSTTab< _TYPE_, int >, TRUSTVect< double, _SIZE_ >, TRUSTTab< double >, TRUSTVect< double, int >, TRUSTTab< double, int >, TRUSTVect< int, _SIZE_ >, TRUSTTab< int >, TRUSTVect< int, int >, TRUSTTab< int, int >, TRUSTVect< trustIdType, int >, and TRUSTTab< trustIdType, int >.
Referenced by Partitionneur_Tranche_32_64< _SIZE_ >::construire_partition(), and Schema_Comm_Vecteurs::get_next_area_template().
reset()
template<typename _TYPE_ , typename _SIZE_ > virtual void TRUSTArray< _TYPE_, _SIZE_ >::reset () inline virtual
Remet le tableau dans l'etat obtenu avec le constructeur par defaut (libere la memoire mais conserve le mode d'allocation memoire actuel)
Reimplemented in TRUSTTab< _TYPE_, _SIZE_ >, TRUSTTab< int, int >, TRUSTTab< double, int >, TRUSTTab< _TYPE_ >, TRUSTTab< _TYPE_, int >, TRUSTTab< int >, TRUSTTab< double >, TRUSTTab< _SIZE_ >, TRUSTTab< trustIdType, int >, TRUSTVect< _TYPE_, _SIZE_ >, TRUSTVect< int, int >, TRUSTVect< double, int >, TRUSTVect< _TYPE_, int >, TRUSTVect< int, _SIZE_ >, TRUSTVect< double, _SIZE_ >, TRUSTVect< _SIZE_, _SIZE_ >, and TRUSTVect< trustIdType, int >.
References TRUSTArray< _TYPE_, _SIZE_ >::detach_array().
Referenced by Corrige_flux_FT_temperature_subresolution::associate_indices_and_check_subproblems_consistency(), IJK_One_Dimensional_Subproblems::clear_sort_problems_colliding_bubbles(), Corrige_flux_FT_temperature_subresolution::clear_vectors(), IJK_Composantes_Connex::compute_compo_connex_from_interface(), Corrige_flux_FT_temperature_subresolution::compute_min_max_ijk_any_reachable_fluxes(), Domaine_32_64< int >::creer_tableau_sommets(), IJK_One_Dimensional_Subproblems::dispatch_interfacial_heat_flux_correction(), Domaine_bord_32_64< _SIZE_ >::extraire_domaine_bord(), IJK_Composantes_Connex::fill_mixed_cell_compo(), IJK_Interfaces::read_bubbles_barycentres_vel(), Corrige_flux_FT_temperature_subresolution::receive_temperature_cell_centre_neighbours_from_procs(), TRUSTVect< _TYPE_, _SIZE_ >::reset(), and IJK_One_Dimensional_Subproblems_Interfaces_Fields::retrieve_interfacial_surface_quantity().
ref_array()
template<typename _TYPE_ , typename _SIZE_ > virtual void TRUSTArray< _TYPE_, _SIZE_ >::ref_array (TRUSTArray< _TYPE_, _SIZE_ > & , _SIZE_ start = 0, _SIZE_ sz = -1) inline virtual
Reimplemented in TRUSTTab< _TYPE_, _SIZE_ >, TRUSTTab< _TYPE_ >, and TRUSTVect< _TYPE_, _SIZE_ >.
Referenced by Op_Diff_VEF_Anisotrope_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution_multi_scalaire(), Pb_Couple_rayo_semi_transp::associer_(), Domaine_IJK::init_subregion(), and Static_Int_Lists_32_64< _SIZE_ >::trier_liste().
resize_tab()
template<typename _TYPE_ , typename _SIZE_ > virtual void TRUSTArray< _TYPE_, _SIZE_ >::resize_tab (_SIZE_ n, RESIZE_OPTIONS opt = RESIZE_OPTIONS::COPY_INIT) inline virtual
Reimplemented in TRUSTTab< _TYPE_, _SIZE_ >, TRUSTTab< _TYPE_ >, TRUSTTab< int >, TRUSTTab< double >, TRUSTTab< _SIZE_ >, TRUSTVect< _TYPE_, _SIZE_ >, TRUSTVect< int, _SIZE_ >, TRUSTVect< double, _SIZE_ >, TRUSTVect< _SIZE_, _SIZE_ >, TRUSTTab< int, int >, TRUSTTab< double, int >, TRUSTTab< _TYPE_, int >, TRUSTTab< trustIdType, int >, TRUSTVect< int, int >, TRUSTVect< double, int >, TRUSTVect< _TYPE_, int >, and TRUSTVect< trustIdType, int >.
Referenced by Domaine_32_64< int >::creer_mes_domaines_frontieres().
get_data_location() [1/2]
template<typename _TYPE_ , typename _SIZE_ > DataLocation TRUSTArray< _TYPE_, _SIZE_ >::get_data_location () inline
get_data_location() [2/2]
template<typename _TYPE_ , typename _SIZE_ > DataLocation TRUSTArray< _TYPE_, _SIZE_ >::get_data_location () const inline
set_data_location() [1/2]
template<typename _TYPE_ , typename _SIZE_ > void TRUSTArray< _TYPE_, _SIZE_ >::set_data_location (DataLocation flag) inline
Referenced by Schema_Comm_Vecteurs::get_next_area_template().
set_data_location() [2/2]
template<typename _TYPE_ , typename _SIZE_ > void TRUSTArray< _TYPE_, _SIZE_ >::set_data_location (DataLocation flag) const inline
size_mem()
template<typename _TYPE_ , typename _SIZE_ > int TRUSTArray< _TYPE_, _SIZE_ >::size_mem () inline
ensureDataOnHost() [1/2]
template<typename _TYPE_ , typename _SIZE_ > void TRUSTArray< _TYPE_, _SIZE_ >::ensureDataOnHost () inline
Referenced by Matrice_Morse::ajouter_multvect_(), and Solv_rocALUTION::resoudre_systeme().
ensureDataOnHost() [2/2]
template<typename _TYPE_ , typename _SIZE_ > void TRUSTArray< _TYPE_, _SIZE_ >::ensureDataOnHost () const inline
isDataOnDevice()
template<typename _TYPE_ , typename _SIZE_ > bool TRUSTArray< _TYPE_, _SIZE_ >::isDataOnDevice () const inline
Referenced by Matrice_Morse::ajouter_multvect_(), Champ_Generique_Interpolation::get_champ_with_calculer_champ_post(), Integrale_tps_Champ::mettre_a_jour_integrale(), Postraitement::postraiter_tableau(), Solv_Petsc::resoudre_systeme(), and Solv_rocALUTION::resoudre_systeme().
checkDataOnDevice() [1/3]
template<typename _TYPE_ , typename _SIZE_ > bool TRUSTArray< _TYPE_, _SIZE_ >::checkDataOnDevice () inline
Referenced by Discretisation_tools::cells_to_faces(), Solveur_Masse_base::corriger_solution(), TRUSTChamp_Divers_generique< _TYPE_ >::valeur_aux(), TRUSTChamp_Divers_generique< _TYPE_ >::valeur_aux_elems(), Champ_implementation_P0::valeur_aux_elems(), and Champ_implementation_P0::valeur_aux_elems_compo().
checkDataOnDevice() [2/3]
template<typename _TYPE_ , typename _SIZE_ > bool TRUSTArray< _TYPE_, _SIZE_ >::checkDataOnDevice () const inline
checkDataOnDevice() [3/3]
template<typename _TYPE_ , typename _SIZE_ > bool TRUSTArray< _TYPE_, _SIZE_ >::checkDataOnDevice (const TRUSTArray< _TYPE_, _SIZE_ > & arr) inline
get_span() [1/2]
template<typename _TYPE_ , typename _SIZE_ > virtual Span_ TRUSTArray< _TYPE_, _SIZE_ >::get_span () inline virtual
Reimplemented in TRUSTVect< _TYPE_, _SIZE_ >, TRUSTVect< int, int >, TRUSTVect< double, int >, TRUSTVect< _TYPE_, int >, TRUSTVect< int, _SIZE_ >, TRUSTVect< double, _SIZE_ >, TRUSTVect< _SIZE_, _SIZE_ >, and TRUSTVect< trustIdType, int >.
get_span_tot() [1/2]
template<typename _TYPE_ , typename _SIZE_ > virtual Span_ TRUSTArray< _TYPE_, _SIZE_ >::get_span_tot () inline virtual
Reimplemented in TRUSTVect< _TYPE_, _SIZE_ >, TRUSTVect< int, int >, TRUSTVect< double, int >, TRUSTVect< _TYPE_, int >, TRUSTVect< int, _SIZE_ >, TRUSTVect< double, _SIZE_ >, TRUSTVect< _SIZE_, _SIZE_ >, and TRUSTVect< trustIdType, int >.
get_span() [2/2]
template<typename _TYPE_ , typename _SIZE_ > virtual const Span_ TRUSTArray< _TYPE_, _SIZE_ >::get_span () const inline virtual
Reimplemented in TRUSTVect< _TYPE_, _SIZE_ >, TRUSTVect< int, int >, TRUSTVect< double, int >, TRUSTVect< _TYPE_, int >, TRUSTVect< int, _SIZE_ >, TRUSTVect< double, _SIZE_ >, TRUSTVect< _SIZE_, _SIZE_ >, and TRUSTVect< trustIdType, int >.
get_span_tot() [2/2]
template<typename _TYPE_ , typename _SIZE_ > virtual const Span_ TRUSTArray< _TYPE_, _SIZE_ >::get_span_tot () const inline virtual
Reimplemented in TRUSTVect< _TYPE_, _SIZE_ >, TRUSTVect< int, int >, TRUSTVect< double, int >, TRUSTVect< _TYPE_, int >, TRUSTVect< int, _SIZE_ >, TRUSTVect< double, _SIZE_ >, TRUSTVect< _SIZE_, _SIZE_ >, and TRUSTVect< trustIdType, int >.
dimension_tot()
template<typename _TYPE_ , typename _SIZE_ > virtual _SIZE_ TRUSTArray< _TYPE_, _SIZE_ >::dimension_tot (int) const inline virtual
Reimplemented in TRUSTTab< _TYPE_, _SIZE_ >, TRUSTTab< int, int >, TRUSTTab< double, int >, TRUSTTab< _TYPE_ >, TRUSTTab< _TYPE_, int >, TRUSTTab< int >, TRUSTTab< double >, TRUSTTab< _SIZE_ >, and TRUSTTab< trustIdType, int >.
check_flattened()
template<typename _TYPE_ , typename _SIZE_ > template<int _SHAPE_> bool TRUSTArray< _TYPE_, _SIZE_ >::check_flattened () const inline
getDims()
template<typename _TYPE_ , typename _SIZE_ > template<int _SHAPE_> std::array< _SIZE_, 4 > TRUSTArray< _TYPE_, _SIZE_ >::getDims () const
CleanMyView()
template<typename _TYPE_ , typename _SIZE_ > void TRUSTArray< _TYPE_, _SIZE_ >::CleanMyView () inline
References TRUSTArray< _TYPE_, _SIZE_ >::device_view_1_, TRUSTArray< _TYPE_, _SIZE_ >::device_view_2_, TRUSTArray< _TYPE_, _SIZE_ >::device_view_3_, and TRUSTArray< _TYPE_, _SIZE_ >::device_view_4_.
Referenced by Schema_Comm_Vecteurs::CleanMyStaticViews().
view_ro() [1/2]
template<typename _TYPE_ , typename _SIZE_ > template<int _SHAPE_ = 1, typename EXEC_SPACE = Kokkos::DefaultExecutionSpace> std::enable_if_t< is_default_exec_space< EXEC_SPACE >, ConstView< _TYPE_, _SHAPE_ > > TRUSTArray< _TYPE_, _SIZE_ >::view_ro () const inline
Referenced by Op_Conv_VEF_Face::ajouter(), Terme_Source_Canal_perio_VEF_P1NC::ajouter(), Terme_Boussinesq_VEF_Face::ajouter(), Terme_Boussinesq_VEFPreP1B_Face::ajouter(), Source_QC_Chaleur::ajouter_(), Op_Diff_VEF_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Grad_VEF_P1B_Face::ajouter_elem(), Source_Masse_Fluide_Dilatable_VEF::ajouter_eq_espece(), Source_Fluide_Dilatable_VEF_Proto::ajouter_impl(), Matrice_Morse::ajouter_multvect_(), Source_Masse_Fluide_Dilatable_VEF::ajouter_projection(), Op_Grad_VEF_P1B_Face::ajouter_som(), Op_Div_VEFP1B_Elem::ajouter_som(), Masse_VEF_P1NC::appliquer_impl(), Champ_P1NC::calcul_duidxj_paroi(), Op_Dift_VEF_base::calculer_borne_locale(), Terme_Source_Canal_perio_VEF_P1NC::calculer_debit(), Op_Conv_VEF_base::calculer_dt_stab(), Op_Diff_VEF_base::calculer_dt_stab(), Op_Dift_VEF_base::calculer_dt_stab(), Modele_turbulence_hyd_LES_base::calculer_energie_cinetique_turb(), Op_Grad_VEF_P1B_Face::calculer_flux_bords(), Modele_turbulence_hyd_LES_Smago_VEF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_Wale_VEF::calculer_viscosite_turbulente(), Discretisation_tools::cells_to_faces(), Champ_Generique_Transformation::get_champ(), Modele_turbulence_hyd_base::limiter_viscosite_turbulente(), Assembleur_P_VEFPreP1B::modifier_secmem(), TRUSTArray< _TYPE_, _SIZE_ >::operator+=(), TRUSTArray< _TYPE_, _SIZE_ >::operator-=(), Op_Conv_VEF_Face::remplir_fluent(), Eval_Puiss_Th_QC_VEF_Face_View::set(), Eval_Puiss_Th_VEF_Face_View::set(), Eval_Source_C_VEF_Face_View::set(), Matrice_Morse_View::set(), Champ_P1iP1B_implementation::valeur_aux_elems(), Champ_P1NC_implementation::valeur_aux_elems(), and Op_Div_VEFP1B_Elem::volumique().
view_ro() [2/2]
template<typename _TYPE_ , typename _SIZE_ > template<int _SHAPE_ = 1, typename EXEC_SPACE = Kokkos::DefaultExecutionSpace> std::enable_if_t< gpu_enabled_is_host_exec_space< EXEC_SPACE >, ConstHostView< _TYPE_, _SHAPE_ > > TRUSTArray< _TYPE_, _SIZE_ >::view_ro () const inline
view_wo() [1/2]
template<typename _TYPE_ , typename _SIZE_ > template<int _SHAPE_ = 1, typename EXEC_SPACE = Kokkos::DefaultExecutionSpace> std::enable_if_t< is_default_exec_space< EXEC_SPACE >, View< _TYPE_, _SHAPE_ > > TRUSTArray< _TYPE_, _SIZE_ >::view_wo () inline
Referenced by Champ_P1NC::calcul_S_barre(), Paroi_std_hyd_VEF::calculer_hyd(), and Op_Conv_Muscl_New_VEF_Face::remplir_fluent().
view_wo() [2/2]
template<typename _TYPE_ , typename _SIZE_ > template<int _SHAPE_ = 1, typename EXEC_SPACE = Kokkos::DefaultExecutionSpace> std::enable_if_t< gpu_enabled_is_host_exec_space< EXEC_SPACE >, HostView< _TYPE_, _SHAPE_ > > TRUSTArray< _TYPE_, _SIZE_ >::view_wo () inline
view_rw() [1/2]
template<typename _TYPE_ , typename _SIZE_ > template<int _SHAPE_ = 1, typename EXEC_SPACE = Kokkos::DefaultExecutionSpace> std::enable_if_t< is_default_exec_space< EXEC_SPACE >, View< _TYPE_, _SHAPE_ > > TRUSTArray< _TYPE_, _SIZE_ >::view_rw () inline
Referenced by Terme_Source_Canal_perio_VEF_P1NC::ajouter(), Source_Masse_Fluide_Dilatable_VEF::ajouter_eq_espece(), Matrice_Morse::ajouter_multvect_(), Source_Masse_Fluide_Dilatable_VEF::ajouter_projection(), Op_Div_VEFP1B_Elem::ajouter_som(), Champ_P1NC::calcul_critere_Q(), Champ_P1NC::calcul_y_plus(), Op_Dift_VEF_base::calculer_borne_locale(), Modele_turbulence_hyd_LES_base::calculer_energie_cinetique_turb(), Paroi_negligeable_VEF::calculer_hyd(), Assembleur_P_VEFPreP1B::changer_base(), Op_Conv_EF_VEF_P1NC_Stab::remplir_fluent(), Op_Conv_VEF_Face::remplir_fluent(), and Matrice_Morse_View::set().
view_rw() [2/2]
template<typename _TYPE_ , typename _SIZE_ > template<int _SHAPE_ = 1, typename EXEC_SPACE = Kokkos::DefaultExecutionSpace> std::enable_if_t< gpu_enabled_is_host_exec_space< EXEC_SPACE >, HostView< _TYPE_, _SHAPE_ > > TRUSTArray< _TYPE_, _SIZE_ >::view_rw () inline
attach_array()
template<typename _TYPE_ , typename _SIZE_ > void TRUSTArray< _TYPE_, _SIZE_ >::attach_array (const TRUSTArray< _TYPE_, _SIZE_ > & a, _SIZE_ start = 0, _SIZE_ size = -1) inline protected
detach_array()
template<typename _TYPE_ , typename _SIZE_ > bool TRUSTArray< _TYPE_, _SIZE_ >::detach_array () inline protected
Referenced by TRUSTArray< _TYPE_, _SIZE_ >::reset().
resize_array_()
template<typename _TYPE_ , typename _SIZE_ > void TRUSTArray< _TYPE_, _SIZE_ >::resize_array_ (_SIZE_ new_size, RESIZE_OPTIONS opt = RESIZE_OPTIONS::COPY_INIT) protected
Protected method for resize. Used by derived classes. Same as resize_array() with less checks.
This is also where we deal with the STORAGE::TEMP_STORAGE capability, i.e. the Trav arrays. There memory is taken from a shared pool (TRUSTTravPool). This kind of array should never be used in 64bits, since Trav are meaningful when inside the timestepping (so the 32bit world after the Scatter isntruction).
Referenced by TRUSTArray< _TYPE_, _SIZE_ >::from_tid_to_int(), and TRUSTArray< _TYPE_, _SIZE_ >::TRUSTArray().
init_device_view()
template<typename _TYPE_ , typename _SIZE_ > template<int _SHAPE_> void TRUSTArray< _TYPE_, _SIZE_ >::init_device_view () const inline protected
ref_as_small() [2/3]
void TRUSTArray< float, trustIdType >::ref_as_small (TRUSTArray< float, int > & out) const
Conversion methods - from a big array (SIZE=trustIdType), return a small one (SIZE=int). Overflow is detected in debug if array is too big to be fit into SIZE=int. No data copied! This behaves somewhat like a ref_array. Used in LATA stuff and FT notably.
ref_as_small() [3/3]
void TRUSTArray< int, trustIdType >::ref_as_small (TRUSTArray< int, int > & out) const
from_tid_to_int() [2/2]
void TRUSTArray< trustIdType, trustIdType >::from_tid_to_int (TRUSTArray< int, int > & out) const
Conversion from a BigArrOfTID to an ArrOfInt. Careful, it always does a copy! It is your responsibility to invoke it only when necessary (typically you should avoid this when trustIdType == int ...)
References TRUSTArray< _TYPE_, _SIZE_ >::resize_array_().
Friends And Related Function Documentation
TRUSTArrayKokkos
template<typename _TYPE_ , typename _SIZE_ > friend class TRUSTArrayKokkos friend
TRUSTArray
template<typename _TYPE_ , typename _SIZE_ > template<typename _TYPE2_ , typename _SIZE2_ > friend class TRUSTArray friend
Referenced by TRUSTArray< _TYPE_, _SIZE_ >::duplique().
Member Data Documentation
nb_dim_
template<typename _TYPE_ , typename _SIZE_ > int TRUSTArray< _TYPE_, _SIZE_ >::nb_dim_ = 1 protected
Referenced by TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), TRUSTTab< _TYPE_, _SIZE_ >::printOn(), TRUSTTab< _TYPE_, _SIZE_ >::readOn(), and TRUSTTab< _TYPE_, _SIZE_ >::TRUSTTab().
device_view_1_
template<typename _TYPE_ , typename _SIZE_ > DeviceView<_TYPE_, 1> TRUSTArray< _TYPE_, _SIZE_ >::device_view_1_ mutable protected
Referenced by TRUSTArray< _TYPE_, _SIZE_ >::CleanMyView().
device_view_2_
template<typename _TYPE_ , typename _SIZE_ > DeviceView<_TYPE_, 2> TRUSTArray< _TYPE_, _SIZE_ >::device_view_2_ mutable protected
Referenced by TRUSTArray< _TYPE_, _SIZE_ >::CleanMyView().
device_view_3_
template<typename _TYPE_ , typename _SIZE_ > DeviceView<_TYPE_, 3> TRUSTArray< _TYPE_, _SIZE_ >::device_view_3_ mutable protected
Referenced by TRUSTArray< _TYPE_, _SIZE_ >::CleanMyView().
device_view_4_
template<typename _TYPE_ , typename _SIZE_ > DeviceView<_TYPE_, 4> TRUSTArray< _TYPE_, _SIZE_ >::device_view_4_ mutable protected
Referenced by TRUSTArray< _TYPE_, _SIZE_ >::CleanMyView().