TrioCFD: Sonde_IJK Class Reference
Sonde_IJK Class Reference
#include <Sonde_IJK.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Sonde
void associer_post (const Postraitement &)
SFichier & fichier ()
void fixer_periode (double)
const Type_info * get_info () const override
virtual void initialiser ()
const Champ_Generique_base & le_champ () const
const IntVect & les_poly () const
const DoubleTab & les_positions_sondes_initiales () const
virtual void mettre_a_jour (double temps, double tinit)
void nommer (const Nom &n) override
void ouvrir_fichier ()
virtual void postraiter ()
Sonde (const Nom &)
double temps () const
~Sonde () override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
void create_champ_generique (Entree &is, const Motcle &motlu) override
void fill_local_values () override
void fix_probe_position () override
void fix_probe_position_grav () override
const Domaine & get_domaine_geom () const override
int get_nb_compo_champ () const override
const Noms get_noms_champ () const override
double get_temps_champ () const override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
void update_source (double un_temps) override
void validate_position () const override
void validate_type (const Motcle &loc) const override
virtual void create_champ_generique (Entree &is, const Motcle &motlu)
virtual void fill_local_values ()
virtual void fix_probe_position ()
virtual void fix_probe_position_grav ()
virtual const Domaine & get_domaine_geom () const
virtual int get_nb_compo_champ () const
virtual const Noms get_noms_champ () const
virtual double get_temps_champ () const
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
virtual void update_source (double un_temps)
virtual void validate_position () const
virtual void validate_type (const Motcle &loc) const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Attributes inherited from Sonde
int ncomp
bool nodes
Constructor & Destructor Documentation
Sonde_IJK()
Sonde_IJK::Sonde_IJK ()
~Sonde_IJK()
Sonde_IJK::~Sonde_IJK ()
Member Function Documentation
cree_instance()
Objet_U * Sonde_IJK::cree_instance () static
taille_memoire()
unsigned Sonde_IJK::taille_memoire () const override virtual
Reimplemented from Sonde.
duplique()
int Sonde_IJK::duplique () const override virtual
Reimplemented from Sonde.
info()
const Type_info * Sonde_IJK::info () static
get_info()
const Type_info * Sonde_IJK::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Sonde.
self_cast() [1/2]
Sonde_IJK & Sonde_IJK::self_cast (Objet_U & r) static
self_cast() [2/2]
const Sonde_IJK & Sonde_IJK::self_cast (const Objet_U & r) static
printOn()
Sortie & Sonde_IJK::printOn (Sortie & s) const override protected virtual
Imprime le type de l'objet sur un flot de sortie.
Parameters
(Sortie& s) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Sonde.
References Objet_U::que_suis_je().
readOn()
Entree & Sonde_IJK::readOn (Entree & is) override protected virtual
Lit les specifications d'une sonde a partir d'un flot d'entree.
Format: Sondes { [nom_sonde nom_champ Periode dts Points n x1 y1 [z1] ... xn yn [zn] [nom_sonde nom_champ Periode dts Segment ns x1 y1 [z1] x2 y2 [z2] ... }
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Exceptions
donnees de la sonde non definies
erreur de format, mot clef inconnus
donnees de la sonde pas definies correctement
Reimplemented from Sonde.
References Sonde::readOn().
completer()
void Sonde_IJK::completer () override virtual
Reimplemented from Sonde.
References Domaine_IJK::ELEM, Sonde::grav, Sonde::initialiser(), Sonde::mon_post, Sonde::nom_champ_lu_, ref_ijk_field_, and ref_ijk_ft_.
get_domaine_geom()
const Domaine & Sonde_IJK::get_domaine_geom () const override protected virtual
Retrieve the domain to be used for the probe
Reimplemented from Sonde.
References ref_ijk_ft_.
get_noms_champ()
const Noms Sonde_IJK::get_noms_champ () const override protected virtual
Retrieve the field names - overriden in IJK
Reimplemented from Sonde.
References TRUST_Vector< _CLASSE_ >::add(), and ref_ijk_field_.
get_nb_compo_champ()
int Sonde_IJK::get_nb_compo_champ () const override protected virtual
Retrieve the number of component for the field - overriden in IJK
Reimplemented from Sonde.
References ref_ijk_field_.
get_temps_champ()
double Sonde_IJK::get_temps_champ () const override protected virtual
Retrieve the current time for the field - overriden in IJK
Reimplemented from Sonde.
References ref_ijk_ft_.
validate_type()
void Sonde_IJK::validate_type (const Motcle & loc) const override protected virtual
Override. Exit if invalid type for the probe.
Reimplemented from Sonde.
References Process::exit(), and Nom::getString().
validate_position()
void Sonde_IJK::validate_position () const override protected virtual
Override. Exit if invalid localisation for the probe.
Reimplemented from Sonde.
References Sonde::chsom, Process::exit(), Sonde::gravcl, Sonde::nodes, and Sonde::som.
create_champ_generique()
void Sonde_IJK::create_champ_generique (Entree & is, const Motcle & motlu) inline override protected virtual
Creation des Champ_Generique_refChamp necessaire pour l initialisation de la REF a Champ_Generique_base Si le champ demande est un Champ_base connu du probleme on cree le Champ_Generique_refChamp correspondant
Reimplemented from Sonde.
fix_probe_position()
void Sonde_IJK::fix_probe_position () override protected virtual
Fix probe position. In IJK, if no position modifier is specified, we systematically move the probe to the center of the element for a ELEM field, and to the face corresponding to the field component if this is a FACE field.
Reimplemented from Sonde.
References ref_ijk_field_.
fix_probe_position_grav()
void Sonde_IJK::fix_probe_position_grav () override protected virtual
In IJK, velocity components might be interpolated/moved to element center. This is equivalent to having a ELEM field.
Reimplemented from Sonde.
References Domaine_IJK::ELEM.
fill_local_values()
void Sonde_IJK::fill_local_values () override protected virtual
Fill the array 'valeurs_locales' used by each proc to store prob local values
Reimplemented from Sonde.
References Domaine_IJK::convert_packed_to_ijk_cell(), Domaine_IJK::ELEM, Sonde::elem_, Process::exit(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_domaine(), Sonde::grav, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), Sonde::nom_, ref_ijk_field_, ref_ijk_ft_, TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTVect< _TYPE_, _SIZE_ >::size(), tmp_storage_, and Sonde::valeurs_locales.
update_source()
void Sonde_IJK::update_source (double un_temps) inline override protected virtual
Update the underlying field source if needed
Reimplemented from Sonde.
Member Data Documentation
info_obj
const Type_info Sonde_IJK::info_obj static
ref_ijk_ft_
TRUST_Ref< Probleme_FTD_IJK_base *> Sonde_IJK::ref_ijk_ft_ protected
Referenced by completer(), fill_local_values(), get_domaine_geom(), and get_temps_champ().
ref_ijk_field_
TRUST_Ref< IJK_Field_double *> Sonde_IJK::ref_ijk_field_ protected
Referenced by completer(), fill_local_values(), fix_probe_position(), get_nb_compo_champ(), and get_noms_champ().
tmp_storage_
IJK_Field_double Sonde_IJK::tmp_storage_ protected
Referenced by fill_local_values().
ncomp
int Sonde_IJK::ncomp = 1 protected
Number of the component to handle.
nbre_points_tot
int Sonde_IJK::nbre_points_tot protected