TrioCFD: OpConvQuickIJKScalar_cut_cell_double Class Reference
OpConvQuickIJKScalar_cut_cell_double Class Reference
#include <OpConvQuickIJKScalar_cut_cell.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
~OpConvQuickIJKScalar_cut_cell_double()
OpConvQuickIJKScalar_cut_cell_double::~OpConvQuickIJKScalar_cut_cell_double ()
OpConvQuickIJKScalar_cut_cell_double()
OpConvQuickIJKScalar_cut_cell_double::OpConvQuickIJKScalar_cut_cell_double () inline
Member Function Documentation
cree_instance()
Objet_U * OpConvQuickIJKScalar_cut_cell_double::cree_instance () static
taille_memoire()
unsigned OpConvQuickIJKScalar_cut_cell_double::taille_memoire () const override virtual
Reimplemented from OpConvQuickIJKScalar_double.
duplique()
int OpConvQuickIJKScalar_cut_cell_double::duplique () const override virtual
Reimplemented from OpConvQuickIJKScalar_double.
info()
const Type_info * OpConvQuickIJKScalar_cut_cell_double::info () static
get_info()
const Type_info * OpConvQuickIJKScalar_cut_cell_double::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from OpConvQuickIJKScalar_double.
self_cast() [1/2]
OpConvQuickIJKScalar_cut_cell_double & OpConvQuickIJKScalar_cut_cell_double::self_cast (Objet_U & r) static
self_cast() [2/2]
const OpConvQuickIJKScalar_cut_cell_double & OpConvQuickIJKScalar_cut_cell_double::self_cast (const Objet_U & r) static
printOn()
Sortie & OpConvQuickIJKScalar_cut_cell_double::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from OpConvQuickIJKScalar_double.
readOn()
Entree & OpConvQuickIJKScalar_cut_cell_double::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from OpConvQuickIJKScalar_double.
initialise_cut_cell()
void OpConvQuickIJKScalar_cut_cell_double::initialise_cut_cell (Cut_cell_conv_scheme cut_cell_conv_scheme, bool ignore_small_cells, FixedVector< Cut_cell_double, 3 > & cut_cell_flux, IJK_Field_int & treatment_count, int & new_treatment) inline
set_runge_kutta()
void OpConvQuickIJKScalar_cut_cell_double::set_runge_kutta (int rk_step, double dt_tot, IJK_Field_vector3_double & current_fluxes, IJK_Field_vector3_double & RK3_F_fluxes, Cut_field_int & cellule_rk_restreint_conv_main) inline
References Operateur_IJK_elem_base_double::current_fluxes_, Operateur_IJK_elem_base_double::dt_tot_, Operateur_IJK_elem_base_double::RK3_F_fluxes_, Operateur_IJK_elem_base_double::rk_step_, and Operateur_IJK_elem_base_double::runge_kutta_flux_correction_.
get_cut_cell_disc()
const Cut_cell_FT_Disc * OpConvQuickIJKScalar_cut_cell_double::get_cut_cell_disc () inline
References get_cut_cell_disc().
Referenced by compute_cut_cell_divergence(), and get_cut_cell_disc().
get_cut_cell_flux()
FixedVector< Cut_cell_double, 3 > * OpConvQuickIJKScalar_cut_cell_double::get_cut_cell_flux () inline
Referenced by Operator_IJK_div().
compute_cut_cell_divergence()
void OpConvQuickIJKScalar_cut_cell_double::compute_cut_cell_divergence (const FixedVector< Cut_cell_double, 3 > & cut_cell_flux, const IJK_Field_local_double & flux_x, const IJK_Field_local_double & flux_y, const IJK_Field_local_double & flux_zmin, const IJK_Field_local_double & flux_zmax, IJK_Field_double & resu, int k_layer, bool add)
References Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::diph_l_, Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::diph_v_, Process::exit(), get_cut_cell_disc(), Cut_cell_FT_Disc::get_domaine(), Cut_cell_FT_Disc::get_ijk(), Cut_cell_FT_Disc::get_k_value_index(), Cut_cell_FT_Disc::get_n(), Cut_cell_FT_Disc::get_n_from_k_index(), Cut_cell_FT_Disc::indic_pure(), and Domaine_IJK::within_ghost().
Referenced by Operator_IJK_div().
Operator_IJK_div()
void OpConvQuickIJKScalar_cut_cell_double::Operator_IJK_div (const IJK_Field_local_double & flux_x, const IJK_Field_local_double & flux_y, const IJK_Field_local_double & flux_zmin, const IJK_Field_local_double & flux_zmax, IJK_Field_double & resu, int k_layer, bool add) inline override virtual
Reimplemented from Operateur_IJK_elem_base_double.
References compute_cut_cell_divergence(), get_cut_cell_flux(), and Operateur_IJK_elem_base_double::Operator_IJK_div().
compute_flux_x()
void OpConvQuickIJKScalar_cut_cell_double::compute_flux_x (IJK_Field_local_double & resu, const int k_layer) inline override protected virtual
Reimplemented from OpConvQuickIJKScalar_double.
compute_flux_y()
void OpConvQuickIJKScalar_cut_cell_double::compute_flux_y (IJK_Field_local_double & resu, const int k_layer) inline override protected virtual
Reimplemented from OpConvQuickIJKScalar_double.
compute_flux_z()
void OpConvQuickIJKScalar_cut_cell_double::compute_flux_z (IJK_Field_local_double & resu, const int k_layer) inline override protected virtual
Reimplemented from OpConvQuickIJKScalar_double.
Member Data Documentation
info_obj
const Type_info OpConvQuickIJKScalar_cut_cell_double::info_obj static