TrioCFD: Dispersion_bulles_base Class Reference
Dispersion_bulles_base Class Reference abstract
#include <Dispersion_bulles_base.h>
Classes
struct input_t
struct output_t
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
 exercee sur le gaz par le liquide prend la forme
 F_{kl} = - F_{lk} = - C_{kl} grad(alpha{k}) + C_{lk} grad(alpha{l}) ou la phase
 l est la phase liquide porteuse et k != 0 une phase quelconque
 cette classe definit une fonction C_{kl}!=C_{lk} dependant de :
   alpha, p, T -> inconnues (une valeur par phase chacune)
   rho, mu, sigma, nut, k_turb -> proprietes physiques (idem)
   ndv(k, l) -> ||v_k - v_l||, a remplir pour k < l
sortie : coeff(k, l, 0/1) -> coefficient C_{kl} et sa derivee en ndv(k, l), rempli pour k < l
Constructor & Destructor Documentation
Dispersion_bulles_base()
Dispersion_bulles_base::Dispersion_bulles_base ()
~Dispersion_bulles_base()
Dispersion_bulles_base::~Dispersion_bulles_base () override
Member Function Documentation
info()
const Type_info * Dispersion_bulles_base::info () static
get_info()
const Type_info * Dispersion_bulles_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Correlation_base.
Reimplemented in Dispersion_bulles_turbulente_Bazin, Dispersion_bulles_turbulente_Bertodano, Dispersion_bulles_turbulente_Burns, Dispersion_bulles_turbulente_constante, Dispersion_bulles_turbulente_Lavieville, and Dispersion_bulles_constante.
self_cast() [1/2]
Dispersion_bulles_base & Dispersion_bulles_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Dispersion_bulles_base & Dispersion_bulles_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Dispersion_bulles_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Correlation_base.
Reimplemented in Dispersion_bulles_turbulente_Bazin, Dispersion_bulles_turbulente_Bertodano, Dispersion_bulles_turbulente_Burns, Dispersion_bulles_turbulente_constante, Dispersion_bulles_turbulente_Lavieville, and Dispersion_bulles_constante.
readOn()
Entree & Dispersion_bulles_base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Correlation_base.
Reimplemented in Dispersion_bulles_turbulente_Bazin, Dispersion_bulles_turbulente_Bertodano, Dispersion_bulles_turbulente_Burns, Dispersion_bulles_turbulente_constante, Dispersion_bulles_turbulente_Lavieville, and Dispersion_bulles_constante.
coefficient()
virtual void Dispersion_bulles_base::coefficient (const input_t & input, output_t & output) const pure virtual
Implemented in Dispersion_bulles_turbulente_Bazin, Dispersion_bulles_turbulente_Bertodano, Dispersion_bulles_turbulente_Burns, Dispersion_bulles_turbulente_constante, Dispersion_bulles_turbulente_Lavieville, and Dispersion_bulles_constante.
Referenced by Dispersion_bulles_PolyMAC_P0::ajouter_blocs(), Dispersion_bulles_VDF::ajouter_blocs(), and Correction_Lubchenko_PolyMAC_P0::ajouter_blocs_disp().
Member Data Documentation
info_obj
const Type_info Dispersion_bulles_base::info_obj static