TrioCFD: Pb_Couple_rayo_semi_transp Class Reference
Pb_Couple_rayo_semi_transp Class Reference
#include <Pb_Couple_rayo_semi_transp.h>
Public Member Functions
int associer_ (Objet_U &) override
void associer_sch_tps_base (Schema_Temps_base &) override
const Type_info * get_info () const override
void initialize () override
Public Member Functions inherited from Probleme_Couple
void ajouter (Probleme_base &)
int associer_ (Objet_U &) override
virtual void associer_sch_tps_base (Schema_Temps_base &)
double computeTimeStep (bool &stop) const override
virtual void discretiser (Discretisation_base &)
const Type_info * get_info () const override
void initialize () override
bool initTimeStep (double dt) override
bool iterateTimeStep (bool &converged) override
virtual Schema_Temps_base & schema_temps ()
virtual const Schema_Temps_base & schema_temps () const
bool updateGivenFields () override
Public Member Functions inherited from Couplage_U
void abortTimeStep () override
TRUST_Ref< Field_base * > findInputField (const Nom &name) const override
double futureTime () const override
const Type_info * get_info () const override
void getInputFieldsNames (Noms &noms) const override
void getOutputFieldsNames (Noms &noms) const override
void initialize () override
bool initTimeStep (double dt) override
bool isStationary () const override
bool iterateTimeStep (bool &converged) override
int postraiter (int force=1) override
double presentTime () const override
void resetTime (double t) override
void terminate () override
bool updateGivenFields () override
void validateTimeStep () override
Public Member Functions inherited from Probleme_U
virtual void abortTimeStep ()
virtual double computeTimeStep (bool &stop) const
virtual TRUST_Ref< Field_base * > findInputField (const Nom &name) const
virtual double futureTime () const
const Type_info * get_info () const override
virtual void getInputFieldsNames (Noms &noms) const
virtual void getOutputFieldsNames (Noms &noms) const
virtual void initialize ()
virtual bool initTimeStep (double dt)
virtual bool isStationary () const
virtual bool iterateTimeStep (bool &converged)
const Nom & le_nom () const override
void nommer (const Nom &name) override
virtual int postraiter (int force=1)
virtual double presentTime () const
virtual void resetTime (double time)
virtual bool run ()
virtual bool runUntil (double time)
virtual void terminate ()
virtual bool updateGivenFields ()
virtual void validateTimeStep ()
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
rayonnement.
Seule l'etape d'initialisation impose actuellement que le
modele de rayonnement soit differencie, et donc l'existence de
la classe Pb_Couple_rayo_semi_transp.
See also
Probleme_Couple Modele_rayo_semi_transp
Constructor & Destructor Documentation
Pb_Couple_rayo_semi_transp()
Pb_Couple_rayo_semi_transp::Pb_Couple_rayo_semi_transp ()
~Pb_Couple_rayo_semi_transp()
Pb_Couple_rayo_semi_transp::~Pb_Couple_rayo_semi_transp ()
Member Function Documentation
cree_instance()
Objet_U * Pb_Couple_rayo_semi_transp::cree_instance () static
taille_memoire()
unsigned Pb_Couple_rayo_semi_transp::taille_memoire () const override virtual
Reimplemented from Probleme_Couple.
duplique()
int Pb_Couple_rayo_semi_transp::duplique () const override virtual
Reimplemented from Probleme_Couple.
info()
const Type_info * Pb_Couple_rayo_semi_transp::info () static
get_info()
const Type_info * Pb_Couple_rayo_semi_transp::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Probleme_Couple.
self_cast() [1/2]
Pb_Couple_rayo_semi_transp & Pb_Couple_rayo_semi_transp::self_cast (Objet_U & r) static
self_cast() [2/2]
const Pb_Couple_rayo_semi_transp & Pb_Couple_rayo_semi_transp::self_cast (const Objet_U & r) static
printOn()
Sortie & Pb_Couple_rayo_semi_transp::printOn (Sortie & os) const override protected virtual
Surcharge Objet_U::printOn(Sortie&) Imprime les problemes couples sur un flot de sortie.
Parameters
(Sortie& os) le flot de sortie sur lequel imprimer
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Probleme_Couple.
References Probleme_Couple::printOn().
readOn()
Entree & Pb_Couple_rayo_semi_transp::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Probleme_Couple.
initialize()
void Pb_Couple_rayo_semi_transp::initialize () override virtual
This method is called once at the beginning, before any other one of the interface Problem.
Exceptions
WrongContext
Reimplemented from Probleme_Couple.
References Source_rayo_semi_transp_base::associer_modele_rayo(), Domaine_Cl_dis_base::calculer_coeffs_echange(), Modele_rayo_semi_transp::calculer_flux_radiatif(), Equation_base::domaine_Cl_dis(), Modele_rayo_semi_transp::eq_rayo(), Probleme_base::equation(), Probleme_Couple::initialize(), modele(), Couplage_U::nb_problemes(), Probleme_base::nombre_d_equations(), Couplage_U::presentTime(), Modele_rayo_semi_transp::probleme(), Couplage_U::probleme(), Equation_rayonnement_base::resoudre(), TRUST_List< _CLASSE_ >::size(), Equation_base::sources(), and TRUST_Deriv< _CLASSE_ >::valeur().
le_modele_rayo_associe()
void Pb_Couple_rayo_semi_transp::le_modele_rayo_associe (const Modele_rayo_semi_transp & un_modele_de_rayonnement)
References Interprete_bloc::ajouter(), Probleme_base::associer_domaine(), Modele_rayo_semi_transp::associer_probleme(), der_domaine_clone, Probleme_base::domaine(), Process::exit(), Interprete_bloc::interprete_courant(), Milieu_base::is_rayo_semi_transp(), le_modele_, Domaine_base::le_nom(), Probleme_base::milieu(), modele(), Couplage_U::nb_problemes(), Domaine_base::nommer(), TRUST_Ref< _CLASSE_ >::non_nul(), Couplage_U::probleme(), Objet_U_ptr::typer(), and TRUST_Deriv_Objet_U::valeur().
Referenced by associer_().
associer_()
int Pb_Couple_rayo_semi_transp::associer_ (Objet_U & ob) override virtual
Surcharge Objet_U::associer_(Objet_U&) Associe un objet au probleme couple, en verifiant le type.
dynamiquement. L'objet peut-etre:
un schema en temps (Schema_Temps_base), et on l'associe aux problemes
un probleme (Probleme_base), on l'ajoute a la liste
Parameters
(Objet_U& ob) l'objet a associer
Returns
(int) 1 si l'association a reussie 0 sinon
Exceptions
l'objet n'est pas d'un type attendu
Reimplemented from Probleme_Couple.
References Probleme_Couple::ajouter(), Probleme_Couple::associer_(), Fluide_base::fixer_type_rayo(), Probleme_Couple::groupes, le_modele_rayo_associe(), Probleme_base::milieu(), modele(), Couplage_U::nb_problemes(), Objet_U::que_suis_je(), TRUSTArray< _TYPE_, _SIZE_ >::ref_array(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
associer_sch_tps_base()
void Pb_Couple_rayo_semi_transp::associer_sch_tps_base (Schema_Temps_base & sch) override virtual
Associe une copie du schema en temps a chaque probleme du Probleme couple.
Parameters
(Schema_Temps_base& sch) le schema en temps a associer
Reimplemented from Probleme_Couple.
References Modele_rayo_semi_transp::associer_sch_tps_base(), Probleme_Couple::associer_sch_tps_base(), Process::exit(), le_modele_, modele(), TRUST_Ref< _CLASSE_ >::non_nul(), and sch_clone.
modele() [1/2]
Modele_rayo_semi_transp & Pb_Couple_rayo_semi_transp::modele () inline
References le_modele_, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by associer_(), associer_sch_tps_base(), initialize(), and le_modele_rayo_associe().
modele() [2/2]
const Modele_rayo_semi_transp & Pb_Couple_rayo_semi_transp::modele () const inline
References le_modele_, and TRUST_Ref< _CLASSE_ >::valeur().
Member Data Documentation
info_obj
const Type_info Pb_Couple_rayo_semi_transp::info_obj static
der_domaine_clone
DerObjU Pb_Couple_rayo_semi_transp::der_domaine_clone protected
Referenced by le_modele_rayo_associe().
sch_clone
TRUST_Deriv< Schema_Temps_base > Pb_Couple_rayo_semi_transp::sch_clone protected
Referenced by associer_sch_tps_base().
le_modele_
TRUST_Ref< Modele_rayo_semi_transp *> Pb_Couple_rayo_semi_transp::le_modele_ protected
Referenced by associer_sch_tps_base(), le_modele_rayo_associe(), and modele().