TrioCFD: Face_Rayonnante Class Reference
Face_Rayonnante Class Reference
#include <Face_Rayonnante.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Face_Rayonnante()
Face_Rayonnante::Face_Rayonnante ()
~Face_Rayonnante()
Face_Rayonnante::~Face_Rayonnante ()
Member Function Documentation
cree_instance()
Objet_U * Face_Rayonnante::cree_instance () static
taille_memoire()
unsigned Face_Rayonnante::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Face_Rayonnante::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Face_Rayonnante::info () static
get_info()
const Type_info * Face_Rayonnante::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
Face_Rayonnante & Face_Rayonnante::self_cast (Objet_U & r) static
self_cast() [2/2]
const Face_Rayonnante & Face_Rayonnante::self_cast (const Objet_U & r) static
printOn()
Sortie & Face_Rayonnante::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
readOn()
Entree & Face_Rayonnante::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
References TRUST_Vector< _CLASSE_ >::dimensionner(), nb_ensembles_faces(), and Nom::prefix().
T_face_rayo()
double Face_Rayonnante::T_face_rayo () const inline
emissivite()
double Face_Rayonnante::emissivite () const inline
Referenced by Pb_Couple_Rayonnement::completer(), and Modele_Rayonnement_Milieu_Transparent::preparer_calcul().
flux_radiatif()
double Face_Rayonnante::flux_radiatif () const inline
surface_rayo()
double Face_Rayonnante::surface_rayo () const inline
Referenced by imprimer_flux_radiatif().
nom_bord_rayo()
const Nom & Face_Rayonnante::nom_bord_rayo () const inline
Referenced by Pb_Couple_Rayonnement::completer(), and Modele_Rayonnement_Milieu_Transparent::discretiser().
nom_bord_rayo_lu()
const Nom & Face_Rayonnante::nom_bord_rayo_lu () const inline
Referenced by Pb_Couple_Rayonnement::completer(), Modele_Rayonnement_Milieu_Transparent::discretiser(), ecrire_temperature_bord(), and imprimer_flux_radiatif().
num_faces()
const IntVect & Face_Rayonnante::num_faces (int j) const inline
ensembles_faces_bord() [1/2]
const Ensemble_Faces_base & Face_Rayonnante::ensembles_faces_bord (int j) const inline
Referenced by calculer_temperature(), Pb_Couple_Rayonnement::completer(), Modele_Rayonnement_Milieu_Transparent::discretiser(), and ecrire_temperature_bord().
ensembles_faces_bord() [2/2]
Ensemble_Faces_base & Face_Rayonnante::ensembles_faces_bord (int j) inline
calculer_temperature()
double Face_Rayonnante::calculer_temperature ()
References ensembles_faces_bord(), Frontiere_dis_base::frontiere(), Cond_lim_base::frontiere_dis(), Ensemble_Faces_base::la_cl_base(), Process::mp_sum(), nb_ensembles_faces(), Frontiere_32_64< _SIZE_ >::nb_faces(), Ensemble_Faces_base::nb_faces_bord(), TRUSTVect< _TYPE_, _SIZE_ >::size(), Ensemble_Faces_base::surface(), Ensemble_Faces_base::Table_faces(), and Ensemble_Faces_base::teta_i().
imprimer_flux_radiatif()
double Face_Rayonnante::imprimer_flux_radiatif (Sortie & os, Sortie & os1, Sortie & os2) const
References nom_bord_rayo_lu(), and surface_rayo().
chercher_ensemble_faces()
int Face_Rayonnante::chercher_ensemble_faces (const Nom & nom_bord) const
nb_ensembles_faces()
int Face_Rayonnante::nb_ensembles_faces () const inline
Referenced by calculer_temperature(), Modele_Rayonnement_Milieu_Transparent::discretiser(), ecrire_temperature_bord(), and readOn().
mettre_a_jour_flux_radiatif()
void Face_Rayonnante::mettre_a_jour_flux_radiatif (double J) inline
ecrire_temperature_bord()
void Face_Rayonnante::ecrire_temperature_bord () const
References ensembles_faces_bord(), Process::je_suis_maitre(), EcrFicPartage::lockfile(), nb_ensembles_faces(), and nom_bord_rayo_lu().
Member Data Documentation
info_obj
const Type_info Face_Rayonnante::info_obj static