TrioCFD: Probleme_FT_Disc_gen Class Reference
Probleme_FT_Disc_gen Class Reference
#include <Probleme_FT_Disc_gen.h>
Public Member Functions
int associer_ (Objet_U &ob) override
void associer_milieu_base (const Milieu_base &milieu) override
double calculer_pas_de_temps () const override
void completer () override
const Type_info * get_info () const override
void mettre_a_jour (double temps) override
virtual bool updateGivenFields () override
const Type_info * get_info () const override
Public Member Functions inherited from Probleme_base
void abortTimeStep () override
int associer_ (Objet_U &) override
virtual void associer_domaine (const Domaine &)
virtual void associer_milieu_base (const Milieu_base &)
virtual void associer_sch_tps_base (const Schema_Temps_base &)
virtual double calculer_pas_de_temps () const
virtual void completer ()
double computeTimeStep (bool &stop) const override
const Discretisation_base & discretisation () const
virtual void discretiser (Discretisation_base &)
Domaine & domaine ()
const Domaine & domaine () const
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
Equation_base & equation (const Nom &)
const Equation_base & equation (const Nom &) const
TRUST_Ref< Field_base * > findInputField (const Nom &name) const override
virtual void finir ()
double futureTime () const override
const Type_info * get_info () const override
void getInputFieldsNames (Noms &noms) const override
void getOutputFieldsNames (Noms &noms) const override
virtual void imprimer (Sortie &os) const
void initialize () override
bool initTimeStep (double dt) override
bool isStationary () const override
bool iterateTimeStep (bool &converged) override
int limpr () const override
int lsauv () const override
virtual void mettre_a_jour (double temps)
virtual Milieu_base & milieu ()
virtual const Milieu_base & milieu () const
int postraiter (int force=1) override
double presentTime () const override
int reprendre (Entree &) override
void resetTime (double time) override
int sauvegarder (Sortie &) const override
Schema_Temps_base & schema_temps ()
const Schema_Temps_base & schema_temps () const
void terminate () override
bool updateGivenFields () override
void validateTimeStep () override
virtual int verifier ()
Public Member Functions inherited from Probleme_U
virtual void abortTimeStep ()
virtual double computeTimeStep (bool &stop) const
virtual TRUST_Ref< Field_base * > findInputField (const Nom &name) const
virtual double futureTime () const
const Type_info * get_info () const override
virtual void getInputFieldsNames (Noms &noms) const
virtual void getOutputFieldsNames (Noms &noms) const
virtual void initialize ()
virtual bool initTimeStep (double dt)
virtual bool isStationary () const
virtual bool iterateTimeStep (bool &converged)
const Nom & le_nom () const override
void nommer (const Nom &name) override
virtual int postraiter (int force=1)
virtual double presentTime () const
virtual void resetTime (double time)
virtual bool run ()
virtual bool runUntil (double time)
virtual void terminate ()
virtual bool updateGivenFields ()
virtual void validateTimeStep ()
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Probleme_FT_Disc_gen()
Probleme_FT_Disc_gen::Probleme_FT_Disc_gen ()
~Probleme_FT_Disc_gen()
Probleme_FT_Disc_gen::~Probleme_FT_Disc_gen ()
Member Function Documentation
cree_instance()
Objet_U * Probleme_FT_Disc_gen::cree_instance () static
taille_memoire()
unsigned Probleme_FT_Disc_gen::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Probleme_FTD_IJK, and Probleme_FTD_IJK_cut_cell.
duplique()
int Probleme_FT_Disc_gen::duplique () const override virtual
Implements Objet_U.
Reimplemented in Probleme_FTD_IJK, and Probleme_FTD_IJK_cut_cell.
info()
const Type_info * Probleme_FT_Disc_gen::info () static
get_info()
const Type_info * Probleme_FT_Disc_gen::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Pb_Fluide_base.
Reimplemented in Probleme_FTD_IJK, Probleme_FTD_IJK_base, and Probleme_FTD_IJK_cut_cell.
self_cast() [1/2]
Probleme_FT_Disc_gen & Probleme_FT_Disc_gen::self_cast (Objet_U & r) static
self_cast() [2/2]
const Probleme_FT_Disc_gen & Probleme_FT_Disc_gen::self_cast (const Objet_U & r) static
printOn()
Sortie & Probleme_FT_Disc_gen::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Pb_Fluide_base.
Reimplemented in Probleme_FTD_IJK, Probleme_FTD_IJK_base, and Probleme_FTD_IJK_cut_cell.
readOn()
Entree & Probleme_FT_Disc_gen::readOn (Entree & is) override protected virtual
Lecture d'un probleme dans un flot d'entree, et ouverture du flot de sauvegarde.
Format: { nom_milieu bloc de lecture d'un milieu nom_equation bloc de lecture d'une equation Postraitement bloc de lecture postraitement reprise | sauvegarde | sauvegarde_simple formatte | binaire | pdi nom_de_fichier } L'option sauvegarde_simple permet de sauver le probleme dans le fichier choisi en ecrasant a chaque fois les sauvegardes precedentes : cela permet d'economiser de la place disque.
Parameters
(Entree& is) flot d'entree
Returns
(Entree&) le flot d'entre modifie
Exceptions
pas d'accolade ouvrante en debut de format
mot clef "Postraitement" n'est pas la
format de sauvegarde doit etre "binaire" ou "formatte"
pas d'accolade fermante en fin de jeu de donnee
Reimplemented from Pb_Fluide_base.
Reimplemented in Probleme_FTD_IJK, Probleme_FTD_IJK_base, and Probleme_FTD_IJK_cut_cell.
References Pb_Fluide_base::readOn().
nombre_d_equations()
int Probleme_FT_Disc_gen::nombre_d_equations () const inline override virtual
Implements Probleme_base.
References equations_, and TRUST_List< _CLASSE_ >::size().
Referenced by associer_milieu_base(), equation_hydraulique(), equation_interfaces(), get_equation_by_name(), getset_equation_by_name(), mettre_a_jour(), and typer_lire_milieu().
equation() [1/2]
const Equation_base & Probleme_FT_Disc_gen::equation (int i) const inline override virtual
Implements Probleme_base.
References equations_.
Referenced by associer_milieu_base(), equation_hydraulique(), equation_interfaces(), get_equation_by_name(), getset_equation_by_name(), mettre_a_jour(), and typer_lire_milieu().
equation() [2/2]
Equation_base & Probleme_FT_Disc_gen::equation (int i) inline override virtual
Implements Probleme_base.
References equations_.
typer_lire_milieu()
void Probleme_FT_Disc_gen::typer_lire_milieu (Entree & is) override virtual
Reimplemented from Probleme_base.
Reimplemented in Probleme_FTD_IJK_base.
References associer_milieu_base(), Equation_base::associer_milieu_equation(), Nom::contient(), Probleme_base::discretiser_equations(), equation(), equations_, TRUST_List< _CLASSE_ >::get_stl_list(), Probleme_base::la_discretisation_, Probleme_base::le_milieu_, nombre_d_equations(), and TRUST_Ref< _CLASSE_ >::valeur().
lire_solved_equations()
void Probleme_FT_Disc_gen::lire_solved_equations (Entree & is) override virtual
Reimplemented from Probleme_base.
Reimplemented in Probleme_FTD_IJK_base.
References TRUST_Vector< _CLASSE_ >::add(), add_FT_equation(), Nom::contient(), Motcle::debute_par(), Process::exit(), Type_info::les_sous_types(), Objet_U::que_suis_je(), and Noms::rang().
lire_equations()
Entree & Probleme_FT_Disc_gen::lire_equations (Entree & is, Motcle & dernier_mot) override virtual
Lecture des equations du probleme.
Reimplemented from Probleme_base.
Reimplemented in Probleme_FTD_IJK_base.
References Triple_Line_Model_FT_Disc::associer_pb(), and Probleme_base::lire_equations().
get_equation_by_name()
const Equation_base & Probleme_FT_Disc_gen::get_equation_by_name (const Nom & un_nom) const override virtual
(B. Math): Methode virtuelle ajoutee pour les problemes ayant plusieurs equations de meme type (Probleme_FT_Disc_gen). Dans ce cas, le nom de l'equation n'est pas son type...
Reimplemented from Probleme_base.
References equation(), Process::exit(), Equation_base::le_nom(), and nombre_d_equations().
Referenced by Navier_Stokes_FT_Disc::lire_motcle_non_standard().
getset_equation_by_name()
Equation_base & Probleme_FT_Disc_gen::getset_equation_by_name (const Nom & un_nom) override virtual
(B. Math): Methode virtuelle ajoutee pour les problemes ayant plusieurs equations de meme type (Probleme_FT_Disc_gen). Dans ce cas, le nom de l'equation n'est pas son type... Version non const. Cette methode est notamment appelee a la lecture du probleme.
Reimplemented from Probleme_base.
References equation(), Process::exit(), Equation_base::le_nom(), and nombre_d_equations().
Referenced by Probleme_FTD_IJK_base::readOn().
associer_milieu_base()
void Probleme_FT_Disc_gen::associer_milieu_base (const Milieu_base & un_milieu) override virtual
Verifie que le milieu est de type Fluide_Diphasique et associe le milieu aux equations.
Precondition: Toutes les equations doivent avoir ete associees.
Reimplemented from Probleme_base.
References Equation_base::associer_milieu_base(), equation(), and nombre_d_equations().
Referenced by typer_lire_milieu().
associer_()
int Probleme_FT_Disc_gen::associer_ (Objet_U & ob) override virtual
surcharge Objet_U::associer_(Objet_U& ob) Associe differents objets au probleme en controlant
le type de l'objet a associer a l'execution.
On peut ainsi associer: un schema en temps, un domaine de calcul ou
un milieu physique.
Utilise les routine de la classe Type_Info (Utilitaires)
Parameters
(Objet_U& ob) l'objet a associer
Returns
(int) 1 si association reussie 0 sinon 2 si le milieu est deja associe a un autre probleme
Exceptions
Objet_U de type inconnu (non prevu)
Reimplemented from Probleme_base.
Reimplemented in Probleme_FTD_IJK_base.
References Probleme_base::associer_().
Referenced by Probleme_FTD_IJK_base::associer_().
completer()
void Probleme_FT_Disc_gen::completer () override virtual
Complete les equations associees au probleme.
Remplissage des references, deleguee aux equations.
Reimplemented from Probleme_base.
Reimplemented in Probleme_FTD_IJK_base.
References Triple_Line_Model_FT_Disc::completer(), Probleme_base::completer(), Triple_Line_Model_FT_Disc::is_activated(), and TRUST_Ref< _CLASSE_ >::non_nul().
calculer_pas_de_temps()
double Probleme_FT_Disc_gen::calculer_pas_de_temps () const override virtual
Calcul la valeur du prochain pas de temps du probleme.
On calcule le minimum des pas de temps des equations associees au probleme.
Returns
(double) le pas de temps maximum autorise pour ce probleme
Reimplemented from Probleme_base.
References Probleme_base::calculer_pas_de_temps(), Process::mp_min(), and TRUST_Ref< _CLASSE_ >::non_nul().
mettre_a_jour()
void Probleme_FT_Disc_gen::mettre_a_jour (double temps) override virtual
Effectue une mise a jour en temps du probleme.
Effectue la mise a jour sur toutes les equations du probleme.
Parameters
(double temps) le pas de temps de mise a jour
Reimplemented from Probleme_base.
Reimplemented in Probleme_FTD_IJK_base.
References equation(), Probleme_base::les_postraitements_, Equation_base::mettre_a_jour(), Probleme_base::mettre_a_jour(), Postraitements::mettre_a_jour(), nombre_d_equations(), TRUST_Ref< _CLASSE_ >::non_nul(), Objet_U::que_suis_je(), and Probleme_base::schema_temps().
updateGivenFields()
bool Probleme_FT_Disc_gen::updateGivenFields () override virtual
ATTENTION :
Rentre ici tout ce qui ne correspond pas a l'API normale de Problem.
Actuellement on y met a jour les CLs et les termes sources, sachant que certains vont chercher eux-memes des informations dans les problemes voisins...
Programme de travail : tout ce qui est dans cette methode doit etre rendu independant de l'exterieur, et peut du coup rejoindre initTimeStep. Le reste passe dans l'interface d'echange de champs. Ce travail sera fini quand updateGivenFields sera vide et supprime !
Returns
(true=OK, false=error)
Reimplemented from Probleme_base.
Reimplemented in Probleme_FTD_IJK_base.
References Triple_Line_Model_FT_Disc::compute_TCL_fluxes_in_all_boundary_cells(), tcl(), and Probleme_base::updateGivenFields().
equation_hydraulique()
const Navier_Stokes_FT_Disc & Probleme_FT_Disc_gen::equation_hydraulique (const Motcle & nom) const virtual
References equation(), Process::exit(), Process::je_suis_maitre(), Equation_base::le_nom(), nombre_d_equations(), and Objet_U::que_suis_je().
Referenced by Convection_Diffusion_Temperature_FT_Disc::lire_motcle_non_standard().
equation_interfaces()
const Transport_Interfaces_FT_Disc & Probleme_FT_Disc_gen::equation_interfaces (const Motcle & nom) const virtual
References equation(), Process::exit(), Process::je_suis_maitre(), Equation_base::le_nom(), nombre_d_equations(), and Objet_U::que_suis_je().
Referenced by SourceFiltree_FT_disc_VEF_P1NC::associer_pb(), Postraitement_ft_lata::lire_entete_bloc_interface(), Convection_Diffusion_Temperature_FT_Disc::lire_motcle_non_standard(), and Navier_Stokes_FT_Disc::lire_motcle_non_standard().
tcl() [1/2]
const Triple_Line_Model_FT_Disc & Probleme_FT_Disc_gen::tcl () const inline
Referenced by Maillage_FT_Disc::calcul_courbure_sommets(), Echange_contact_VDF_FT_Disc::completer(), Convection_Diffusion_Temperature_FT_Disc::derivee_en_temps_inco(), Transport_Interfaces_FT_Disc::mettre_a_jour(), Echange_contact_VDF_FT_Disc::mettre_a_jour(), Echange_contact_VDF_FT_Disc_solid::mettre_a_jour(), and updateGivenFields().
tcl() [2/2]
Triple_Line_Model_FT_Disc & Probleme_FT_Disc_gen::tcl () inline
get_list_equations()
const TRUST_List< TRUST_Deriv< Equation_base > > & Probleme_FT_Disc_gen::get_list_equations () const inline
References equations_.
add_FT_equation()
void Probleme_FT_Disc_gen::add_FT_equation (const Nom & eq_name, const Nom & eq_type) protected
References TRUST_List< _CLASSE_ >::add(), Equation_base::associer_pb_base(), Equation_base::associer_sch_tps_base(), TRUST_List< _CLASSE_ >::dernier(), equations_, Probleme_base::le_schema_en_temps_, Equation_base::nommer(), Objet_U_ptr::typer(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by lire_solved_equations(), and Probleme_FTD_IJK_base::lire_solved_equations().
Member Data Documentation
info_obj
const Type_info Probleme_FT_Disc_gen::info_obj static
equations_
TRUST_List< TRUST_Deriv< Equation_base > > Probleme_FT_Disc_gen::equations_ protected
Referenced by add_FT_equation(), Probleme_FTD_IJK_base::build_vdf_domaine(), Probleme_FTD_IJK_base::completer(), Probleme_FTD_IJK::create_forced_dilation(), Probleme_FTD_IJK_base::deplacer_interfaces(), Probleme_FTD_IJK_cut_cell::deplacer_interfaces(), Probleme_FTD_IJK_base::deplacer_interfaces_rk3(), Probleme_FTD_IJK_cut_cell::deplacer_interfaces_rk3(), Probleme_FTD_IJK_base::eq_ns(), equation(), Probleme_FTD_IJK_base::euler_time_step(), Probleme_FTD_IJK_cut_cell::get_cut_field_velocity(), Probleme_FTD_IJK_base::get_IJK_field(), Probleme_FTD_IJK_base::get_IJK_field_vector(), Probleme_FTD_IJK_base::get_ijk_thermals(), Probleme_FTD_IJK_base::get_interface(), get_list_equations(), Probleme_FTD_IJK_base::get_noms_champs_postraitables(), Probleme_FTD_IJK_base::has_champ(), Probleme_FTD_IJK_base::has_champ_vectoriel(), Probleme_FTD_IJK_base::initialise_ijk_fields(), Probleme_FTD_IJK::initialize(), Probleme_FTD_IJK_base::initialize(), Probleme_FTD_IJK_cut_cell::initialize(), nombre_d_equations(), Probleme_FTD_IJK_base::preparer_calcul(), Probleme_FTD_IJK_base::readOn(), Probleme_FTD_IJK_base::reprendre_probleme(), Probleme_FTD_IJK_base::rk3_sub_step(), Probleme_FTD_IJK_base::sauvegarder_probleme(), Probleme_FTD_IJK_base::solveTimeStep(), Probleme_FTD_IJK_base::solveTimeStep_Euler(), Probleme_FTD_IJK_base::solveTimeStep_RK3(), typer_lire_milieu(), and Probleme_FTD_IJK_cut_cell::update_twice_indicator_field().