TrioCFD: Source_Transport_Fluctuation_Temperature_W_VDF_Elem Class Reference
Source_Transport_Fluctuation_Temperature_W_VDF_Elem Class Reference
#include <Source_Transport_Fluctuation_Temperature_W_VDF_Elem.h>
Public Member Functions
const Type_info * get_info () const override
void mettre_a_jour (double temps) override
Public Member Functions inherited from Source_base
virtual int a_pour_Champ_Fonc (const Motcle &mot, TRUST_Ref< Champ_base * > &ch_ref) const
virtual void associer_champ_rho (const Champ_base &champ_rho)
virtual void completer ()
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
virtual void resetTime (double t)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
~Source_Transport_Fluctuation_Temperature_W_VDF_Elem()
Source_Transport_Fluctuation_Temperature_W_VDF_Elem::~Source_Transport_Fluctuation_Temperature_W_VDF_Elem ()
Source_Transport_Fluctuation_Temperature_W_VDF_Elem()
Source_Transport_Fluctuation_Temperature_W_VDF_Elem::Source_Transport_Fluctuation_Temperature_W_VDF_Elem (double ctea = 0.8, double cteb = 2.2, double ctec = 1.8, double cted = 0.72) inline
Member Function Documentation
cree_instance()
Objet_U * Source_Transport_Fluctuation_Temperature_W_VDF_Elem::cree_instance () static
taille_memoire()
unsigned Source_Transport_Fluctuation_Temperature_W_VDF_Elem::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Source_Transport_Fluctuation_Temperature_W_VDF_Elem::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Source_Transport_Fluctuation_Temperature_W_VDF_Elem::info () static
get_info()
const Type_info * Source_Transport_Fluctuation_Temperature_W_VDF_Elem::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Source_base.
self_cast() [1/2]
Source_Transport_Fluctuation_Temperature_W_VDF_Elem & Source_Transport_Fluctuation_Temperature_W_VDF_Elem::self_cast (Objet_U & r) static
self_cast() [2/2]
const Source_Transport_Fluctuation_Temperature_W_VDF_Elem & Source_Transport_Fluctuation_Temperature_W_VDF_Elem::self_cast (const Objet_U & r) static
printOn()
Sortie & Source_Transport_Fluctuation_Temperature_W_VDF_Elem::printOn (Sortie & os) const override protected virtual
DOES NOTHING - to override in derived classes.
Imprime la source sur un flot de sortie.
Parameters
(Sortie& os) le flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Source_base.
References Objet_U::que_suis_je().
readOn()
Entree & Source_Transport_Fluctuation_Temperature_W_VDF_Elem::readOn (Entree & is) override protected virtual
DOES NOTHING - to override in derived classes.
Lecture d'un terme source sur un flot d'entree.
Parameters
(Entree& is) le flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Source_base.
References Ca, Cb, Cc, Cd, Process::exit(), and Motcles::search().
associer_pb()
void Source_Transport_Fluctuation_Temperature_W_VDF_Elem::associer_pb (const Probleme_base & pb) override virtual
Implements Source_base.
References beta_t, Milieu_base::beta_t(), eq_hydraulique, eq_thermique, MorEqn::equation(), Probleme_base::equation(), Milieu_base::gravite(), gravite_, and mon_eq_transport_Fluctu_Temp.
calculer_Prod_uteta_T()
DoubleTab & Source_Transport_Fluctuation_Temperature_W_VDF_Elem::calculer_Prod_uteta_T (const Domaine_VDF & domaine_VDF, const Domaine_Cl_VDF & zcl_VDF, const DoubleTab & temper, const DoubleTab & u_teta, DoubleTab & uteta_T) const
References Objet_U::axi, Objet_U::dimension, Domaine_VDF::dist_norm(), Domaine_VDF::dist_norm_axi(), Domaine_VDF::dist_norm_bord(), Domaine_VDF::dist_norm_bord_axi(), Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), MorEqn::equation(), Domaine_VF::face_voisins(), Domaine_Cl_dis_base::les_conditions_limites(), Equation_base::milieu(), Domaine_dis_base::nb_elem(), Domaine_VF::nb_faces(), Front_VF::nb_faces(), Domaine_32_64< _SIZE_ >::nb_faces_elem(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), Milieu_base::porosite_face(), Domaine_VF::premiere_face_int(), Dirichlet::val_imp(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by ajouter().
ajouter()
DoubleTab & Source_Transport_Fluctuation_Temperature_W_VDF_Elem::ajouter (DoubleTab & resu) const override virtual
Reimplemented from Source_base.
References Objet_U::axi, beta_t, Ca, calculer_Prod_uteta_T(), Calcul_Production_K_VDF::calculer_terme_destruction_K(), Calcul_Production_K_VDF::calculer_terme_production_K(), Calcul_Production_K_VDF::calculer_terme_production_K_Axi(), Calcul_Production_K_VDF::calculer_u_teta(), Cb, Cc, Cd, Modele_turbulence_scal_base::diffusivite_turbulente(), eq_hydraulique, eq_thermique, Modele_turbulence_hyd_K_Eps_Bas_Reynolds::eqn_transp_K_Eps(), MorEqn::equation(), gravite_, Transport_K_Eps_base::inconnue(), Equation_base::milieu(), mon_eq_transport_Fluctu_Temp, Domaine_dis_base::nb_elem(), Domaine_dis_base::nb_elem_tot(), Domaine_VF::nb_faces(), Milieu_base::porosite_elem(), TRUST_Ref< _CLASSE_ >::valeur(), TRUST_Ref_Objet_U::valeur(), Champ_Don_base::valeurs(), Champ_Inc_base::valeurs(), Modele_turbulence_hyd_base::viscosite_turbulente(), and Domaine_VF::volumes().
Referenced by calculer().
calculer()
DoubleTab & Source_Transport_Fluctuation_Temperature_W_VDF_Elem::calculer (DoubleTab & resu) const override virtual
Reimplemented from Source_base.
References ajouter().
calculer_gteta2() [1/2]
DoubleTab & Source_Transport_Fluctuation_Temperature_W_VDF_Elem::calculer_gteta2 (const Domaine_VDF & domaine_VDF, DoubleTab & gteta2, const DoubleTab & fluctu_temp, double beta, const DoubleVect & gravite) const
References Objet_U::dimension, and Domaine_dis_base::nb_elem().
Referenced by calculer_u_teta_W().
calculer_gteta2() [2/2]
DoubleTab & Source_Transport_Fluctuation_Temperature_W_VDF_Elem::calculer_gteta2 (const Domaine_VDF & domaine_VDF, DoubleTab & gteta2, const DoubleTab & fluctu_temp, const DoubleTab & beta, const DoubleVect & gravite) const
References Objet_U::dimension, and Domaine_dis_base::nb_elem().
calculer_u_teta_W()
DoubleTab & Source_Transport_Fluctuation_Temperature_W_VDF_Elem::calculer_u_teta_W (const Domaine_VDF & domaine_VDF, const Domaine_Cl_VDF & zcl_VDF, const DoubleTab & temper, const DoubleTab & fluctu_temp, const DoubleTab & keps, const DoubleTab & alpha_turb, DoubleTab & u_teta) const
References Objet_U::axi, beta_t, calculer_gteta2(), Objet_U::dimension, Domaine_VDF::dist_norm(), Domaine_VDF::dist_norm_axi(), Domaine_VDF::dist_norm_bord(), Domaine_VDF::dist_norm_bord_axi(), Domaine_VF::face_voisins(), gravite_, Domaine_Cl_dis_base::les_conditions_limites(), Domaine_dis_base::nb_elem(), Domaine_VF::nb_faces(), Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), Domaine_VDF::orientation(), Domaine_VF::premiere_face_int(), Dirichlet::val_imp(), TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), and Champ_Don_base::valeurs().
Referenced by calculer_terme_destruction_K_W().
calculer_terme_destruction_K_W() [1/2]
DoubleTab & Source_Transport_Fluctuation_Temperature_W_VDF_Elem::calculer_terme_destruction_K_W (const Domaine_VDF & domaine_VDF, const Domaine_Cl_VDF & zcl_VDF, DoubleTab & G, const DoubleTab & temper, const DoubleTab & fluctuTemp, const DoubleTab & keps, const DoubleTab & alpha_turb, double beta, const DoubleVect & gravite) const
References calculer_u_teta_W(), Objet_U::dimension, Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), MorEqn::equation(), Equation_base::milieu(), Domaine_dis_base::nb_elem(), Domaine_VF::nb_faces(), Domaine_32_64< _SIZE_ >::nb_faces_elem(), and Milieu_base::porosite_face().
calculer_terme_destruction_K_W() [2/2]
DoubleTab & Source_Transport_Fluctuation_Temperature_W_VDF_Elem::calculer_terme_destruction_K_W (const Domaine_VDF & domaine_VDF, const Domaine_Cl_VDF & zcl_VDF, DoubleTab & G, const DoubleTab & temper, const DoubleTab & fluctuTemp, const DoubleTab & keps, const DoubleTab & alpha_turb, const DoubleTab & beta, const DoubleVect & gravite) const
References calculer_u_teta_W(), Objet_U::dimension, Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), MorEqn::equation(), Equation_base::milieu(), Domaine_dis_base::nb_elem(), Domaine_VF::nb_faces(), Domaine_32_64< _SIZE_ >::nb_faces_elem(), and Milieu_base::porosite_face().
mettre_a_jour()
void Source_Transport_Fluctuation_Temperature_W_VDF_Elem::mettre_a_jour (double temps) inline override virtual
DOES NOTHING - to override in derived classes.
Mise a jour en temps du terme source.
Parameters
(double) le pas de temps de mise a jour
Reimplemented from Source_base.
References Calcul_Production_K_VDF::mettre_a_jour().
associer_domaines()
void Source_Transport_Fluctuation_Temperature_W_VDF_Elem::associer_domaines (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis) override protected virtual
Implements Source_base.
References le_dom_Cl_VDF, and le_dom_VDF.
Member Data Documentation
info_obj
const Type_info Source_Transport_Fluctuation_Temperature_W_VDF_Elem::info_obj static
Ca
double Source_Transport_Fluctuation_Temperature_W_VDF_Elem::Ca protected
Referenced by ajouter(), and readOn().
Cb
double Source_Transport_Fluctuation_Temperature_W_VDF_Elem::Cb protected
Referenced by ajouter(), and readOn().
Cc
double Source_Transport_Fluctuation_Temperature_W_VDF_Elem::Cc protected
Referenced by ajouter(), and readOn().
Cd
double Source_Transport_Fluctuation_Temperature_W_VDF_Elem::Cd protected
Referenced by ajouter(), and readOn().
le_dom_VDF
TRUST_Ref< Domaine_VDF *> Source_Transport_Fluctuation_Temperature_W_VDF_Elem::le_dom_VDF protected
Referenced by associer_domaines().
le_dom_Cl_VDF
TRUST_Ref< Domaine_Cl_VDF *> Source_Transport_Fluctuation_Temperature_W_VDF_Elem::le_dom_Cl_VDF protected
Referenced by associer_domaines().
eq_hydraulique
TRUST_Ref< Equation_base *> Source_Transport_Fluctuation_Temperature_W_VDF_Elem::eq_hydraulique protected
Referenced by ajouter(), and associer_pb().
mon_eq_transport_K_Eps_Bas_Re_
TRUST_Ref< Transport_K_Eps_Bas_Reynolds *> Source_Transport_Fluctuation_Temperature_W_VDF_Elem::mon_eq_transport_K_Eps_Bas_Re_ protected
mon_eq_transport_Fluctu_Temp
TRUST_Ref< Transport_Fluctuation_Temperature_W *> Source_Transport_Fluctuation_Temperature_W_VDF_Elem::mon_eq_transport_Fluctu_Temp protected
Referenced by ajouter(), and associer_pb().
eq_thermique
TRUST_Ref< Convection_Diffusion_Temperature *> Source_Transport_Fluctuation_Temperature_W_VDF_Elem::eq_thermique protected
Referenced by ajouter(), and associer_pb().
beta_t
TRUST_Ref< Champ_Don_base *> Source_Transport_Fluctuation_Temperature_W_VDF_Elem::beta_t protected
Referenced by ajouter(), associer_pb(), and calculer_u_teta_W().
gravite_
TRUST_Ref< Champ_Don_base *> Source_Transport_Fluctuation_Temperature_W_VDF_Elem::gravite_ protected
Referenced by ajouter(), associer_pb(), and calculer_u_teta_W().