TrioCFD: IJK_Grid_Geometry Class Reference
IJK_Grid_Geometry Class Reference
#include <IJK_Grid_Geometry.h>
Public Member Functions
const Type_info * get_info () const override
const Nom & le_nom () const override
void nommer (const Nom &n) override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
~IJK_Grid_Geometry()
IJK_Grid_Geometry::~IJK_Grid_Geometry ()
IJK_Grid_Geometry()
IJK_Grid_Geometry::IJK_Grid_Geometry ()
References delta_xyz_, node_coordinates_xyz_, periodic_, and uniform_.
Member Function Documentation
cree_instance()
Objet_U * IJK_Grid_Geometry::cree_instance () static
taille_memoire()
unsigned IJK_Grid_Geometry::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int IJK_Grid_Geometry::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * IJK_Grid_Geometry::info () static
get_info()
const Type_info * IJK_Grid_Geometry::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
IJK_Grid_Geometry & IJK_Grid_Geometry::self_cast (Objet_U & r) static
self_cast() [2/2]
const IJK_Grid_Geometry & IJK_Grid_Geometry::self_cast (const Objet_U & r) static
printOn()
Sortie & IJK_Grid_Geometry::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
readOn()
Entree & IJK_Grid_Geometry::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
References Param::ajouter(), Param::ajouter_flag(), TRUSTArray< _TYPE_, _SIZE_ >::append_array(), Entree_Fichier_base::eof(), Process::exit(), initialize_origin_deltas(), Process::je_suis_maitre(), le_nom(), Param::lire_avec_accolades(), periodic_, and Objet_U::que_suis_je().
nommer()
void IJK_Grid_Geometry::nommer (const Nom &) inline override virtual
Donne un nom a l'Objet_U Methode virtuelle a surcharger.
Parameters
(const Nom&) le nom a affectuer a l'Objet_U
Reimplemented from Objet_U.
References object_name_.
le_nom()
const Nom & IJK_Grid_Geometry::le_nom () const inline override virtual
Donne le nom de l'Objet_U Methode a surcharger : renvoie "neant" dans cette implementation.
Returns
(Nom&) le nom de l'Objet_U
Reimplemented from Objet_U.
References object_name_.
Referenced by readOn().
initialize_from_unstructured()
void IJK_Grid_Geometry::initialize_from_unstructured (const Domaine & domaine, int direction_for_x, int direction_for_y, int direction_for_z, bool perio_x, bool perio_y, bool perio_z)
References delta_xyz_, Process::exit(), node_coordinates_xyz_, periodic_, Objet_U::precision_geom, TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and uniform_.
initialize_origin_deltas()
void IJK_Grid_Geometry::initialize_origin_deltas (double x0, double y0, double z0, const ArrOfDouble & delta_x, const ArrOfDouble & delta_y, const ArrOfDouble & delta_z, bool perio_x, bool perio_y, bool perio_z)
References delta_xyz_, node_coordinates_xyz_, periodic_, Objet_U::precision_geom, and uniform_.
Referenced by readOn().
get_periodic_flag()
bool IJK_Grid_Geometry::get_periodic_flag (int direction) const inline
References periodic_.
get_origin()
double IJK_Grid_Geometry::get_origin (int direction) const inline
References node_coordinates_xyz_.
Referenced by get_domain_length().
get_nb_elem_tot()
int IJK_Grid_Geometry::get_nb_elem_tot (int direction) const inline
References get_delta(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by get_domain_length().
get_delta()
const ArrOfDouble & IJK_Grid_Geometry::get_delta (int direction) const inline
References delta_xyz_.
Referenced by get_nb_elem_tot().
get_node_coordinates()
const ArrOfDouble & IJK_Grid_Geometry::get_node_coordinates (int direction) const inline
References node_coordinates_xyz_.
Referenced by get_domain_length().
get_constant_delta()
double IJK_Grid_Geometry::get_constant_delta (int direction) const inline
References delta_xyz_, Process::exit(), and is_uniform().
is_uniform()
bool IJK_Grid_Geometry::is_uniform (int direction) const inline
References uniform_.
Referenced by get_constant_delta().
get_domain_length()
double IJK_Grid_Geometry::get_domain_length (int direction) const inline
References get_nb_elem_tot(), get_node_coordinates(), and get_origin().
Member Data Documentation
info_obj
const Type_info IJK_Grid_Geometry::info_obj static
object_name_
Nom IJK_Grid_Geometry::object_name_ protected
Referenced by le_nom(), and nommer().
node_coordinates_xyz_
TRUST_Vector< ArrOfDouble > IJK_Grid_Geometry::node_coordinates_xyz_ protected
Referenced by get_node_coordinates(), get_origin(), IJK_Grid_Geometry(), initialize_from_unstructured(), and initialize_origin_deltas().
delta_xyz_
TRUST_Vector< ArrOfDouble > IJK_Grid_Geometry::delta_xyz_ protected
Referenced by get_constant_delta(), get_delta(), IJK_Grid_Geometry(), initialize_from_unstructured(), and initialize_origin_deltas().
uniform_
bool IJK_Grid_Geometry::uniform_[3] protected
Referenced by IJK_Grid_Geometry(), initialize_from_unstructured(), initialize_origin_deltas(), and is_uniform().
periodic_
bool IJK_Grid_Geometry::periodic_[3] protected
Referenced by get_periodic_flag(), IJK_Grid_Geometry(), initialize_from_unstructured(), initialize_origin_deltas(), and readOn().