TrioCFD: Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem Class Reference
Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem Class Reference
#include <Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem.h>
Public Member Functions
double calculer_dt_stab () const override
const Type_info * get_info () const override
void mettre_a_jour (double temps) override
void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const override
Public Member Functions inherited from Op_Conv_PolyMAC_base
double calculer_dt_stab () const override
void completer () override
const Type_info * get_info () const override
int impr (Sortie &os) const override
const Type_info * get_info () const override
Public Member Functions inherited from Operateur_base
void associer_eqn (const Equation_base &)
virtual double calculer_dt_stab () const
virtual void completer ()
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual void mettre_a_jour (double temps)
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Op_Conv_PolyMAC_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
Constructor & Destructor Documentation
Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem()
Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem ()
~Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem()
Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::~Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem ()
Member Function Documentation
cree_instance()
Objet_U * Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::cree_instance () static
taille_memoire()
unsigned Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Op_Conv_Amont_PolyMAC_P0P1NC_Elem, and Op_Conv_Centre_PolyMAC_P0P1NC_Elem.
duplique()
int Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::duplique () const override virtual
Implements Objet_U.
Reimplemented in Op_Conv_Amont_PolyMAC_P0P1NC_Elem, and Op_Conv_Centre_PolyMAC_P0P1NC_Elem.
info()
const Type_info * Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::info () static
get_info()
const Type_info * Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Operateur_Conv_base.
Reimplemented in Op_Conv_Amont_PolyMAC_P0P1NC_Elem, and Op_Conv_Centre_PolyMAC_P0P1NC_Elem.
self_cast() [1/2]
Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem & Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::self_cast (Objet_U & r) static
self_cast() [2/2]
const Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem & Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::self_cast (const Objet_U & r) static
printOn()
Sortie & Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN A surcharger dans les classes derivees.
Parameters
(Sortie& os) un flot de sortie
Returns
(Sortie&) le flot de sortie
Reimplemented from Operateur_Conv_base.
Reimplemented in Op_Conv_Amont_PolyMAC_P0P1NC_Elem, and Op_Conv_Centre_PolyMAC_P0P1NC_Elem.
References Op_Conv_PolyMAC_base::printOn().
Referenced by Op_Conv_Amont_PolyMAC_P0P1NC_Elem::printOn(), and Op_Conv_Centre_PolyMAC_P0P1NC_Elem::printOn().
readOn()
Entree & Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::readOn (Entree & is) override protected virtual
NE FAIT RIEN A surcharger dans les classes derivees.
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree
Reimplemented from Operateur_Conv_base.
Reimplemented in Op_Conv_Amont_PolyMAC_P0P1NC_Elem, and Op_Conv_Centre_PolyMAC_P0P1NC_Elem.
References Param::ajouter(), alpha_, cc_phases_, TRUST_Vector< _CLASSE_ >::dimensionner(), MorEqn::equation(), Param::lire_avec_accolades_depuis(), Pb_Multiphase::nb_phases(), Pb_Multiphase::nom_phase(), noms_cc_phases_, noms_vd_phases_, noms_x_phases_, Objet_U::que_suis_je(), Op_Conv_PolyMAC_base::readOn(), vd_phases_, and x_phases_.
Referenced by Op_Conv_Amont_PolyMAC_P0P1NC_Elem::readOn(), and Op_Conv_Centre_PolyMAC_P0P1NC_Elem::readOn().
preparer_calcul()
void Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::preparer_calcul () override virtual
Reimplemented from Operateur_base.
References MorEqn::equation(), Process::exit(), Operateur_base::flux_bords_, Equation_base::init_champ_convecte(), Operateur_base::le_champ_inco, Op_Conv_PolyMAC_base::le_dom_poly_, TRUST_Ref< _CLASSE_ >::non_nul(), Operateur_base::preparer_calcul(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), and TRUST_Ref< _CLASSE_ >::valeur().
modifier_pour_Cl()
void Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::modifier_pour_Cl (Matrice_Morse & , DoubleTab &) const inline override virtual
DOES NOTHING - to override in derived classes.
Parameters
(Matrice_Morse&) une matrice au format Morse
(DoubleTab&) un tableau de valeur (double)
Exceptions
methode a surcharger
Reimplemented from Operateur_base.
calculer_dt_stab()
double Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::calculer_dt_stab () const override virtual
Calcul dt_stab.
Returns
(double) renvoie toujours 1.e30
Reimplemented from Operateur_base.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), MorEqn::equation(), Op_Conv_PolyMAC_base::le_dom_poly_, TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Equation_base::milieu(), Process::mp_min(), Milieu_base::porosite_elem(), Milieu_base::porosite_face(), Option_PolyMAC::TRAITEMENT_AXI, TRUST_Ref< _CLASSE_ >::valeur(), and Op_Conv_PolyMAC_base::vitesse_.
has_interface_blocs()
int Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::has_interface_blocs () const inline override virtual
Reimplemented from Operateur_base.
dimensionner_blocs()
void Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl = {}) const override virtual
Reimplemented from Operateur_base.
References Matrix_tools::allocate_morse_matrix(), TRUSTTab< _TYPE_, _SIZE_ >::append_line(), Equation_base::champ_convecte(), Champ_Inc_base::derivees(), MorEqn::equation(), Probleme_base::get_champ(), Nom::getString(), Equation_base::inconnue(), Op_Conv_PolyMAC_base::le_dom_poly_, Field_base::le_nom(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Equation_base::probleme(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_Inc_base::valeurs(), Champ_Proto::valeurs(), and Op_Conv_PolyMAC_base::vitesse_.
ajouter_blocs()
void Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = {}) const override virtual
Reimplemented from Operateur_base.
References alpha_, Statistiques::begin_count(), Equation_base::champ_convecte(), Champ_Inc_base::derivees(), Statistiques::end_count(), MorEqn::equation(), Operateur_base::get_champ(), Nom::getString(), Operateur_base::le_champ_inco, Op_Conv_PolyMAC_base::le_dom_poly_, Field_base::le_nom(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Equation_base::milieu(), TRUST_Ref< _CLASSE_ >::non_nul(), Milieu_base::porosite_face(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_Inc_base::valeur_aux_bords(), Champ_Inc_base::valeurs(), Champ_Proto::valeurs(), and Op_Conv_PolyMAC_base::vitesse_.
check_multiphase_compatibility()
void Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::check_multiphase_compatibility () const inline override virtual
Reimplemented from MorEqn.
creer_champ()
void Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::creer_champ (const Motcle & motlu) override virtual
Reimplemented from Operateur_base.
References Champs_compris_T< FIELD_TYPE >::ajoute_champ(), cc_phases_, Operateur_base::champs_compris_, Operateur_base::creer_champ(), Objet_U::dimension, Equation_base::discretisation(), Discretisation_base::discretiser_champ(), MorEqn::equation(), noms_cc_phases_, noms_vd_phases_, noms_x_phases_, Motcles::rang(), vd_phases_, and x_phases_.
get_noms_champs_postraitables()
void Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::get_noms_champs_postraitables (Noms & nom, Option opt = NONE) const override virtual
Reimplemented from Operateur_base.
References TRUST_Vector< _CLASSE_ >::add(), MorEqn::equation(), Operateur_base::get_noms_champs_postraitables(), Pb_Multiphase::nb_phases(), noms_cc_phases_, noms_vd_phases_, and noms_x_phases_.
mettre_a_jour()
void Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::mettre_a_jour (double temps) override virtual
DOES NOTHING - to override in derived classes.
Mise a jour de l'operateur
Parameters
(double) un pas de temps
Reimplemented from Operateur_base.
References alpha_, cc_phases_, Equation_base::champ_convecte(), Champ_Inc_base::changer_temps(), Objet_U::dimension, MorEqn::equation(), Operateur_base::flux_bords_, Equation_base::inconnue(), Operateur_base::le_champ_inco, Op_Conv_PolyMAC_base::le_dom_poly_, TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Operateur_base::mettre_a_jour(), Equation_base::milieu(), TRUST_Ref< _CLASSE_ >::non_nul(), Milieu_base::porosite_elem(), Milieu_base::porosite_face(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_Inc_base::valeur_aux_bords(), Champ_Inc_base::valeurs(), vd_phases_, Op_Conv_PolyMAC_base::vitesse_, and x_phases_.
Member Data Documentation
info_obj
const Type_info Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::info_obj static
alpha_
double Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::alpha_ = 1.0
Referenced by ajouter_blocs(), Travail_pression_PolyMAC_P0P1NC::completer(), mettre_a_jour(), Op_Conv_Amont_PolyMAC_P0P1NC_Elem::Op_Conv_Amont_PolyMAC_P0P1NC_Elem(), Op_Conv_Centre_PolyMAC_P0P1NC_Elem::Op_Conv_Centre_PolyMAC_P0P1NC_Elem(), and readOn().
cc_phases_
std::vector<TRUST_Deriv< Champ_Inc_base > > Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::cc_phases_ protected
Referenced by creer_champ(), mettre_a_jour(), and readOn().
noms_cc_phases_
Motcles Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::noms_cc_phases_ protected
Referenced by creer_champ(), get_noms_champs_postraitables(), and readOn().
vd_phases_
std::vector<TRUST_Deriv< Champ_Inc_base > > Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::vd_phases_ protected
Referenced by creer_champ(), mettre_a_jour(), and readOn().
noms_vd_phases_
Motcles Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::noms_vd_phases_ protected
Referenced by creer_champ(), get_noms_champs_postraitables(), and readOn().
x_phases_
std::vector<TRUST_Deriv< Champ_Inc_base > > Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::x_phases_ protected
Referenced by creer_champ(), mettre_a_jour(), and readOn().
noms_x_phases_
Motcles Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::noms_x_phases_ protected
Referenced by creer_champ(), get_noms_champs_postraitables(), and readOn().