TrioCFD: IJK_Thermal_Onefluid Class Reference
IJK_Thermal_Onefluid Class Reference
#include <IJK_Thermal_Onefluid.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Public Types inherited from Champs_compris_IJK_interface
using FieldInfo_t = std::tuple< Motcle, Entity, Nature_du_champ, bool >
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
IJK_Thermal_Onefluid()
IJK_Thermal_Onefluid::IJK_Thermal_Onefluid ()
References IJK_Thermal_base::conserv_energy_global_, deprecated_rho_cp_, E0_, lambda_moy_arith_, IJK_Thermal_base::needs_op_unform_, rho_cp_moy_harmonic_, and IJK_Thermal_base::rho_cp_post_.
~IJK_Thermal_Onefluid()
IJK_Thermal_Onefluid::~IJK_Thermal_Onefluid ()
Member Function Documentation
cree_instance()
Objet_U * IJK_Thermal_Onefluid::cree_instance () static
taille_memoire()
unsigned IJK_Thermal_Onefluid::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int IJK_Thermal_Onefluid::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * IJK_Thermal_Onefluid::info () static
get_info()
const Type_info * IJK_Thermal_Onefluid::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from IJK_Thermal_base.
self_cast() [1/2]
IJK_Thermal_Onefluid & IJK_Thermal_Onefluid::self_cast (Objet_U & r) static
self_cast() [2/2]
const IJK_Thermal_Onefluid & IJK_Thermal_Onefluid::self_cast (const Objet_U & r) static
printOn()
Sortie & IJK_Thermal_Onefluid::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from IJK_Thermal_base.
References IJK_Thermal_base::conserv_energy_global_, deprecated_rho_cp_, lambda_moy_arith_, IJK_Thermal_base::lambda_variable_, IJK_Thermal_base::printOn(), rho_cp_moy_harmonic_, and IJK_Thermal_base::type_T_source_.
readOn()
Entree & IJK_Thermal_Onefluid::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from IJK_Thermal_base.
References IJK_Thermal_base::readOn().
initialize()
void IJK_Thermal_Onefluid::initialize (const Domaine_IJK & splitting, const int idx) override virtual
Reimplemented from IJK_Thermal_base.
References Champs_compris_T< FIELD_TYPE >::ajoute_champ(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::allocate(), IJK_Thermal_base::champs_compris_, IJK_Thermal_base::compute_global_energy(), IJK_Thermal_base::conserv_energy_global_, cp_, d_T_rustine_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::data(), deprecated_rho_cp_, div_rho_cp_T_, E0_, Domaine_IJK::ELEM, IJK_Thermal_base::get_field_name_with_rank(), IJK_Thermal_base::initialize(), lambda_, TRUST_Ref< _CLASSE_ >::non_nul(), Objet_U::que_suis_je(), IJK_Thermal_base::ref_ijk_ft_, IJK_Thermal_base::ref_ijk_ft_post_, IJK_Thermal_base::rho_cp_, rho_cp_inv_, rho_cp_moy_harmonic_, IJK_Thermal_base::rho_cp_post_, IJK_Thermal_base::rho_cp_T_, RK3_F_rustine_, Operateur_IJK_elem_diff::set_conductivity_coefficient(), T_rust_, IJK_Thermal_base::temperature_, IJK_Thermal_base::temperature_diffusion_op_, IJK_Thermal_base::type_temperature_convection_form_, and IJK_Thermal_base::uniform_lambda_.
compute_timestep()
double IJK_Thermal_Onefluid::compute_timestep (const double timestep, const double rho_l, const double rho_v, const double dxmin)
update_thermal_properties()
void IJK_Thermal_Onefluid::update_thermal_properties () override virtual
Reimplemented from IJK_Thermal_base.
References cp_, IJK_Thermal_base::cp_liquid_, IJK_Thermal_base::cp_vapour_, deprecated_rho_cp_, IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost(), lambda_, IJK_Thermal_base::lambda_liquid_, lambda_moy_arith_, IJK_Thermal_base::lambda_vapour_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), IJK_Thermal_base::ref_ijk_ft_, IJK_Thermal_base::rho_cp_, rho_cp_inv_, rho_cp_moy_harmonic_, IJK_Thermal_base::rho_cp_post_, and IJK_Thermal_base::update_thermal_properties().
Referenced by euler_rustine_step(), and rk3_rustine_sub_step().
set_param()
void IJK_Thermal_Onefluid::set_param (Param & param) override virtual
Reimplemented from IJK_Thermal_base.
References Param::ajouter_flag(), deprecated_rho_cp_, lambda_moy_arith_, rho_cp_moy_harmonic_, and IJK_Thermal_base::set_param().
euler_rustine_step() [1/2]
void IJK_Thermal_Onefluid::euler_rustine_step (const double timestep) override virtual
Reimplemented from IJK_Thermal_base.
References IJK_Thermal_base::compute_global_energy(), euler_rustine_step(), IJK_Thermal_base::get_conserv_energy_global(), IJK_Thermal_base::get_E0(), and update_thermal_properties().
Referenced by euler_rustine_step().
rk3_rustine_sub_step() [1/2]
void IJK_Thermal_Onefluid::rk3_rustine_sub_step (const int rk_step, const double total_timestep, const double fractionnal_timestep, const double time) override virtual
Reimplemented from IJK_Thermal_base.
References IJK_Thermal_base::compute_global_energy(), IJK_Thermal_base::get_conserv_energy_global(), IJK_Thermal_base::get_E0(), rk3_rustine_sub_step(), and update_thermal_properties().
Referenced by rk3_rustine_sub_step().
euler_rustine_step() [2/2]
void IJK_Thermal_Onefluid::euler_rustine_step (const double timestep, const double dE)
References compute_dT_rustine(), IJK_Thermal_base::compute_global_energy(), d_T_rustine_, IJK_Thermal_base::rang_, IJK_Thermal_base::ref_ijk_ft_, IJK_Thermal_base::source_callback(), and IJK_Thermal_base::temperature_.
rk3_rustine_sub_step() [2/2]
void IJK_Thermal_Onefluid::rk3_rustine_sub_step (const int rk_step, const double total_timestep, const double fractionnal_timestep, const double time, const double dE)
References compute_dT_rustine(), IJK_Thermal_base::compute_global_energy(), d_T_rustine_, IJK_Thermal_base::rang_, IJK_Thermal_base::ref_ijk_ft_, RK3_F_rustine_, IJK_Thermal_base::source_callback(), and IJK_Thermal_base::temperature_.
compute_temperature_convection_conservative()
void IJK_Thermal_Onefluid::compute_temperature_convection_conservative (const IJK_Field_vector3_double & velocity) override virtual
Reimplemented from IJK_Thermal_base.
References Statistiques::begin_count(), compute_T_rust(), IJK_Thermal_base::conv_temperature_negligible_, IJK_Thermal_base::cp_liquid_, IJK_Thermal_base::cp_vapour_, IJK_Thermal_base::d_temperature_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::data(), div_rho_cp_T_, IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel(), Statistiques::end_count(), Domaine_IJK::get_constant_delta(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_domaine(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost(), Statistiques::new_counter(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), IJK_Thermal_base::ref_ijk_ft_, T_rust_, and DebogIJK::verifier().
compute_dT_rustine()
void IJK_Thermal_Onefluid::compute_dT_rustine (const double dE) protected
References IJK_Thermal_base::cp_liquid_, IJK_Thermal_base::cp_vapour_, d_T_rustine_, Domaine_IJK::ELEM, Process::exit(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_domaine(), Domaine_IJK::get_nb_items_global(), Process::mp_sum(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), IJK_Thermal_base::ref_ijk_ft_, and T_rust_.
Referenced by euler_rustine_step(), and rk3_rustine_sub_step().
compute_T_rust()
void IJK_Thermal_Onefluid::compute_T_rust (const IJK_Field_vector3_double & velocity) protected
References Statistiques::begin_count(), IJK_Thermal_base::cp_liquid_, IJK_Thermal_base::cp_vapour_, d_T_rustine_, Statistiques::end_count(), Domaine_IJK::get_constant_delta(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_domaine(), Statistiques::new_counter(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), IJK_Thermal_base::ref_ijk_ft_, T_rust_, IJK_Thermal_base::temperature_, and IJK_Thermal_base::temperature_convection_op_.
Referenced by compute_temperature_convection_conservative().
add_temperature_diffusion()
void IJK_Thermal_Onefluid::add_temperature_diffusion () override protected virtual
Reimplemented from IJK_Thermal_base.
References IJK_Thermal_base::add_temperature_diffusion(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost(), lambda_, IJK_Thermal_base::temperature_diffusion_op_, and DebogIJK::verifier().
compute_diffusion_increment()
void IJK_Thermal_Onefluid::compute_diffusion_increment () override protected virtual
Implements IJK_Thermal_base.
References cp_, IJK_Thermal_base::d_temperature_, deprecated_rho_cp_, IJK_Thermal_base::div_coeff_grad_T_volume_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), IJK_Thermal_base::ref_ijk_ft_, IJK_Thermal_base::rho_cp_, rho_cp_inv_, rho_cp_moy_harmonic_, and IJK_Thermal_base::vol_.
correct_temperature_for_eulerian_fluxes()
void IJK_Thermal_Onefluid::correct_temperature_for_eulerian_fluxes () inline override protected virtual
Implements IJK_Thermal_base.
get_rho_cp_ijk()
double IJK_Thermal_Onefluid::get_rho_cp_ijk (int i, int j, int k) const protected
References cp_, IJK_Thermal_base::cp_liquid_, IJK_Thermal_base::cp_vapour_, deprecated_rho_cp_, IJK_Thermal_base::ref_ijk_ft_, IJK_Thermal_base::rho_cp_, rho_cp_inv_, and rho_cp_moy_harmonic_.
Referenced by get_rho_cp_u_ijk().
get_rho_cp_u_ijk()
double IJK_Thermal_Onefluid::get_rho_cp_u_ijk (const IJK_Field_double & vx, int i, int j, int k) const override protected virtual
Reimplemented from IJK_Thermal_base.
References get_rho_cp_ijk().
compute_rho_cp_u_mean()
double IJK_Thermal_Onefluid::compute_rho_cp_u_mean (const IJK_Field_double & vx) override protected virtual
Reimplemented from IJK_Thermal_base.
References cp_, IJK_Thermal_base::cp_liquid_, IJK_Thermal_base::cp_vapour_, deprecated_rho_cp_, IJK_Thermal_base::ref_ijk_ft_, IJK_Thermal_base::rho_cp_, rho_cp_inv_, and rho_cp_moy_harmonic_.
get_div_lambda_ijk()
double IJK_Thermal_Onefluid::get_div_lambda_ijk (int i, int j, int k) const override protected virtual
Reimplemented from IJK_Thermal_base.
References lambda_.
compute_temperature_dimensionless_theta_mean()
double IJK_Thermal_Onefluid::compute_temperature_dimensionless_theta_mean (const IJK_Field_double & vx) override protected virtual
Reimplemented from IJK_Thermal_base.
References cp_, IJK_Thermal_base::cp_liquid_, IJK_Thermal_base::cp_vapour_, deprecated_rho_cp_, IJK_Thermal_base::ref_ijk_ft_, IJK_Thermal_base::rho_cp_, rho_cp_inv_, rho_cp_moy_harmonic_, and IJK_Thermal_base::temperature_adimensionnelle_theta_.
Member Data Documentation
info_obj
const Type_info IJK_Thermal_Onefluid::info_obj static
E0_
double IJK_Thermal_Onefluid::E0_ protected
Referenced by IJK_Thermal_Onefluid(), and initialize().
deprecated_rho_cp_
int IJK_Thermal_Onefluid::deprecated_rho_cp_ protected
Referenced by compute_diffusion_increment(), compute_rho_cp_u_mean(), compute_temperature_dimensionless_theta_mean(), get_rho_cp_ijk(), IJK_Thermal_Onefluid(), initialize(), printOn(), set_param(), and update_thermal_properties().
rho_cp_moy_harmonic_
int IJK_Thermal_Onefluid::rho_cp_moy_harmonic_ protected
Referenced by compute_diffusion_increment(), compute_rho_cp_u_mean(), compute_temperature_dimensionless_theta_mean(), get_rho_cp_ijk(), IJK_Thermal_Onefluid(), initialize(), printOn(), set_param(), and update_thermal_properties().
lambda_moy_arith_
int IJK_Thermal_Onefluid::lambda_moy_arith_ protected
Referenced by IJK_Thermal_Onefluid(), printOn(), set_param(), and update_thermal_properties().
T_rust_
IJK_Field_double IJK_Thermal_Onefluid::T_rust_ protected
Referenced by compute_dT_rustine(), compute_T_rust(), compute_temperature_convection_conservative(), and initialize().
d_T_rustine_
IJK_Field_double IJK_Thermal_Onefluid::d_T_rustine_ protected
Referenced by compute_dT_rustine(), compute_T_rust(), euler_rustine_step(), initialize(), and rk3_rustine_sub_step().
RK3_F_rustine_
IJK_Field_double IJK_Thermal_Onefluid::RK3_F_rustine_ protected
Referenced by initialize(), and rk3_rustine_sub_step().
div_rho_cp_T_
IJK_Field_double IJK_Thermal_Onefluid::div_rho_cp_T_ protected
Referenced by compute_temperature_convection_conservative(), and initialize().
lambda_
IJK_Field_double IJK_Thermal_Onefluid::lambda_ protected
Referenced by add_temperature_diffusion(), get_div_lambda_ijk(), initialize(), and update_thermal_properties().
cp_
IJK_Field_double IJK_Thermal_Onefluid::cp_ protected
Referenced by compute_diffusion_increment(), compute_rho_cp_u_mean(), compute_temperature_dimensionless_theta_mean(), get_rho_cp_ijk(), initialize(), and update_thermal_properties().
rho_cp_inv_
IJK_Field_double IJK_Thermal_Onefluid::rho_cp_inv_ protected
Referenced by compute_diffusion_increment(), compute_rho_cp_u_mean(), compute_temperature_dimensionless_theta_mean(), get_rho_cp_ijk(), initialize(), and update_thermal_properties().