TrioCFD: Loi_Etat_TPPI_base Class Reference
Loi_Etat_TPPI_base Class Reference
#include <Loi_Etat_TPPI_base.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Loi_Etat_GP_base
void associer_fluide (const Fluide_Dilatable_base &) override
const Type_info * get_info () const override
void remplir_T () override
const Nom type_fluide () const override
Public Member Functions inherited from Loi_Etat_base
virtual void associer_fluide (const Fluide_Dilatable_base &)
void assoscier_probleme (const Probleme_base &pb)
const Type_info * get_info () const override
void mettre_a_jour (double)
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Loi_Etat_TPPI_base()
Loi_Etat_TPPI_base::Loi_Etat_TPPI_base ()
~Loi_Etat_TPPI_base()
Loi_Etat_TPPI_base::~Loi_Etat_TPPI_base () override
Member Function Documentation
info()
const Type_info * Loi_Etat_TPPI_base::info () static
get_info()
const Type_info * Loi_Etat_TPPI_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Loi_Etat_Mono_GP_base.
Reimplemented in Loi_Etat_CoolProp_QC, Loi_Etat_EOS_QC, Loi_Etat_TPPI_QC_base, Loi_Etat_CoolProp_WC, Loi_Etat_EOS_WC, and Loi_Etat_TPPI_WC_base.
self_cast() [1/2]
Loi_Etat_TPPI_base & Loi_Etat_TPPI_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Loi_Etat_TPPI_base & Loi_Etat_TPPI_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Loi_Etat_TPPI_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Loi_Etat_Mono_GP_base.
Reimplemented in Loi_Etat_CoolProp_QC, Loi_Etat_EOS_QC, Loi_Etat_TPPI_QC_base, Loi_Etat_CoolProp_WC, Loi_Etat_EOS_WC, and Loi_Etat_TPPI_WC_base.
References Objet_U::que_suis_je().
readOn()
Entree & Loi_Etat_TPPI_base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Loi_Etat_Mono_GP_base.
Reimplemented in Loi_Etat_CoolProp_QC, Loi_Etat_EOS_QC, Loi_Etat_TPPI_QC_base, Loi_Etat_CoolProp_WC, Loi_Etat_EOS_WC, and Loi_Etat_TPPI_WC_base.
References Param::ajouter(), fluid_name_, model_name_, Objet_U::que_suis_je(), and Param::REQUIRED.
Referenced by Loi_Etat_TPPI_QC_base::readOn(), and Loi_Etat_TPPI_WC_base::readOn().
preparer_calcul()
void Loi_Etat_TPPI_base::preparer_calcul () override virtual
Prepare le fluide au calcul.
Reimplemented from Loi_Etat_base.
Reimplemented in Loi_Etat_TPPI_QC_base.
References Loi_Etat_base::preparer_calcul(), and verify_fields().
Referenced by Loi_Etat_TPPI_QC_base::preparer_calcul().
inverser_Pth()
double Loi_Etat_TPPI_base::inverser_Pth (double T, double rho) override virtual
Calcule la pression avec la temperature et la masse volumique.
Reimplemented from Loi_Etat_GP_base.
calculer_masse_volumique()
double Loi_Etat_TPPI_base::calculer_masse_volumique (double , double) const override virtual
Reimplemented from Loi_Etat_GP_base.
Reimplemented in Loi_Etat_TPPI_QC_base, and Loi_Etat_TPPI_WC_base.
calculer_mu()
void Loi_Etat_TPPI_base::calculer_mu () inline override virtual
Calcule la viscosite.
Reimplemented from Loi_Etat_base.
calculer_lambda()
void Loi_Etat_TPPI_base::calculer_lambda () inline override virtual
Calcule la conductivite.
Reimplemented from Loi_Etat_GP_base.
calculer_alpha()
void Loi_Etat_TPPI_base::calculer_alpha () inline override virtual
Calcule la diffusivite.
Reimplemented from Loi_Etat_GP_base.
verify_fields()
void Loi_Etat_TPPI_base::verify_fields () protected
References Process::exit(), and Loi_Etat_base::le_fluide.
Referenced by preparer_calcul().
Member Data Documentation
info_obj
const Type_info Loi_Etat_TPPI_base::info_obj static
TPPI_
std::shared_ptr<TPPI> Loi_Etat_TPPI_base::TPPI_ = nullptr protected
Referenced by Loi_Etat_TPPI_QC_base::calculer_Cp(), Loi_Etat_TPPI_WC_base::calculer_Cp(), Loi_Etat_TPPI_QC_base::calculer_masse_volumique(), Loi_Etat_TPPI_WC_base::calculer_masse_volumique(), Loi_Etat_CoolProp_QC::readOn(), Loi_Etat_EOS_QC::readOn(), Loi_Etat_CoolProp_WC::readOn(), and Loi_Etat_EOS_WC::readOn().
model_name_
Motcle Loi_Etat_TPPI_base::model_name_ protected
Referenced by readOn(), Loi_Etat_CoolProp_QC::readOn(), Loi_Etat_EOS_QC::readOn(), Loi_Etat_CoolProp_WC::readOn(), and Loi_Etat_EOS_WC::readOn().
fluid_name_
Motcle Loi_Etat_TPPI_base::fluid_name_ protected
Referenced by readOn(), Loi_Etat_CoolProp_QC::readOn(), Loi_Etat_EOS_QC::readOn(), Loi_Etat_CoolProp_WC::readOn(), and Loi_Etat_EOS_WC::readOn().