TrioCFD: Op_Conv_Amont_PolyMAC_Elem Class Reference
Op_Conv_Amont_PolyMAC_Elem Class Reference
#include <Op_Conv_Amont_PolyMAC_Elem.h>
Public Member Functions
const Type_info * get_info () const override
void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const override
Public Member Functions inherited from Op_Conv_PolyMAC_iterateur_base
double calculer_dt_stab () const override
void completer () override
void contribuer_a_avec (const DoubleTab &inco, Matrice_Morse &matrice) const override
void contribuer_au_second_membre (DoubleTab &resu) const override
const Type_info * get_info () const override
int impr (Sortie &os) const override
const Type_info * get_info () const override
Public Member Functions inherited from Operateur_base
void associer_eqn (const Equation_base &)
virtual double calculer_dt_stab () const
virtual void completer ()
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual void mettre_a_jour (double temps)
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Op_Conv_PolyMAC_iterateur_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
Cette classe represente l'operateur de convection associe a une equation de transport d'un scalaire. La discretisation est PolyMAC Le champ convecte est scalaire Le schema de convection est du type Amont L'iterateur associe est de type Iterateur_PolyMAC_Elem L'evaluateur associe est de type Eval_Amont_PolyMAC_Elem
Constructor & Destructor Documentation
~Op_Conv_Amont_PolyMAC_Elem()
Op_Conv_Amont_PolyMAC_Elem::~Op_Conv_Amont_PolyMAC_Elem ()
Op_Conv_Amont_PolyMAC_Elem() [1/2]
Op_Conv_Amont_PolyMAC_Elem::Op_Conv_Amont_PolyMAC_Elem ()
Op_Conv_Amont_PolyMAC_Elem() [2/2]
Op_Conv_Amont_PolyMAC_Elem::Op_Conv_Amont_PolyMAC_Elem (const Iterateur_PolyMAC_base & it) inline protected
Member Function Documentation
cree_instance()
Objet_U * Op_Conv_Amont_PolyMAC_Elem::cree_instance () static
taille_memoire()
unsigned Op_Conv_Amont_PolyMAC_Elem::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Op_Conv_Amont_PolyMAC_Elem::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Op_Conv_Amont_PolyMAC_Elem::info () static
get_info()
const Type_info * Op_Conv_Amont_PolyMAC_Elem::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Operateur_Conv_base.
self_cast() [1/2]
Op_Conv_Amont_PolyMAC_Elem & Op_Conv_Amont_PolyMAC_Elem::self_cast (Objet_U & r) static
self_cast() [2/2]
const Op_Conv_Amont_PolyMAC_Elem & Op_Conv_Amont_PolyMAC_Elem::self_cast (const Objet_U & r) static
printOn()
Sortie & Op_Conv_Amont_PolyMAC_Elem::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN A surcharger dans les classes derivees.
Parameters
(Sortie& os) un flot de sortie
Returns
(Sortie&) le flot de sortie
Reimplemented from Operateur_Conv_base.
References Objet_U::que_suis_je().
readOn()
Entree & Op_Conv_Amont_PolyMAC_Elem::readOn (Entree & is) override protected virtual
NE FAIT RIEN A surcharger dans les classes derivees.
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree
Reimplemented from Operateur_Conv_base.
associer()
void Op_Conv_Amont_PolyMAC_Elem::associer (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_cl_dis, const Champ_Inc_base & ch_transporte) override virtual
Implements Operateur_base.
References Iterateur_PolyMAC_base::associer(), Evaluateur_PolyMAC::associer_domaines(), Eval_PolyMAC_Elem::associer_inconnue(), Iterateur_PolyMAC_base::evaluateur(), and Op_Conv_PolyMAC_iterateur_base::iter_.
associer_vitesse()
void Op_Conv_Amont_PolyMAC_Elem::associer_vitesse (const Champ_base & ch_vit) override virtual
associe le champ de vitesse a l'evaluateur
Implements Operateur_Conv_base.
References Eval_Conv_PolyMAC::associer(), Iterateur_PolyMAC_base::evaluateur(), and Op_Conv_PolyMAC_iterateur_base::iter_.
vitesse() [1/2]
const Champ_base & Op_Conv_Amont_PolyMAC_Elem::vitesse () const override virtual
Implements Op_Conv_PolyMAC_iterateur_base.
References Iterateur_PolyMAC_base::evaluateur(), Op_Conv_PolyMAC_iterateur_base::iter_, and Eval_Conv_PolyMAC::vitesse().
vitesse() [2/2]
Champ_base & Op_Conv_Amont_PolyMAC_Elem::vitesse () override virtual
Implements Op_Conv_PolyMAC_iterateur_base.
References Iterateur_PolyMAC_base::evaluateur(), Op_Conv_PolyMAC_iterateur_base::iter_, and Eval_Conv_PolyMAC::vitesse().
dimensionner()
void Op_Conv_Amont_PolyMAC_Elem::dimensionner (Matrice_Morse & matrice) const inline override virtual
on dimensionne notre matrice.
Reimplemented from Operateur_base.
References Op_PolyMAC_Elem::dimensionner(), Iterateur_PolyMAC_base::domaine(), Iterateur_PolyMAC_base::domaine_Cl(), and Op_Conv_PolyMAC_iterateur_base::iter_.
dimensionner_bloc_vitesse()
void Op_Conv_Amont_PolyMAC_Elem::dimensionner_bloc_vitesse (Matrice_Morse & matrice) const inline override virtual
Reimplemented from Operateur_base.
References Op_PolyMAC_Elem::dimensionner_bloc_vitesse(), Iterateur_PolyMAC_base::domaine(), Iterateur_PolyMAC_base::domaine_Cl(), and Op_Conv_PolyMAC_iterateur_base::iter_.
modifier_pour_Cl()
void Op_Conv_Amont_PolyMAC_Elem::modifier_pour_Cl (Matrice_Morse & , DoubleTab &) const inline override virtual
DOES NOTHING - to override in derived classes.
Parameters
(Matrice_Morse&) une matrice au format Morse
(DoubleTab&) un tableau de valeur (double)
Exceptions
methode a surcharger
Reimplemented from Operateur_base.
References Iterateur_PolyMAC_base::domaine(), Iterateur_PolyMAC_base::domaine_Cl(), Op_Conv_PolyMAC_iterateur_base::iter_, and Op_PolyMAC_Elem::modifier_pour_Cl().
Member Data Documentation
info_obj
const Type_info Op_Conv_Amont_PolyMAC_Elem::info_obj static