TrioCFD: Fluide_generique_CoolProp Class Reference
Fluide_generique_CoolProp Class Reference
#include <Fluide_generique_CoolProp.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Fluide_generique_TPPI_base
const Type_info * get_info () const override
Public Member Functions inherited from Fluide_reel_base
const Type_info * get_info () const override
void mettre_a_jour (double temps) override
Public Member Functions inherited from Fluide_base
const Type_info * get_info () const override
void mettre_a_jour (double) override
void verifier_coherence_champs (int &err, Nom &message) override
Public Member Functions inherited from Milieu_base
virtual int a_gravite () const
int associer_ (Objet_U &) override
virtual void associer_gravite (const Champ_Don_base &)
virtual Champ_Don_base & beta_t ()
virtual const Champ_Don_base & beta_t () const
virtual Champ_Don_base & capacite_calorifique ()
virtual const Champ_Don_base & capacite_calorifique () const
virtual Champ_Don_base & conductivite ()
virtual const Champ_Don_base & conductivite () const
virtual Champ_Don_base & diffusivite ()
virtual const Champ_Don_base & diffusivite () const
virtual int est_deja_associe ()
const Type_info * get_info () const override
virtual Champ_Don_base & gravite ()
virtual const Champ_Don_base & gravite () const
const Nom & le_nom () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual Champ_base & masse_volumique ()
virtual const Champ_base & masse_volumique () const
void nommer (const Nom &) override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Fluide_generique_TPPI_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Fluide_base
void creer_nu ()
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Milieu_base
virtual void calculer_alpha ()
void ecrire (Sortie &) const
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Fluide_generique_CoolProp()
Fluide_generique_CoolProp::Fluide_generique_CoolProp ()
~Fluide_generique_CoolProp()
Fluide_generique_CoolProp::~Fluide_generique_CoolProp ()
Member Function Documentation
cree_instance()
Objet_U * Fluide_generique_CoolProp::cree_instance () static
taille_memoire()
unsigned Fluide_generique_CoolProp::taille_memoire () const override virtual
Reimplemented from Fluide_base.
duplique()
int Fluide_generique_CoolProp::duplique () const override virtual
Reimplemented from Fluide_base.
info()
const Type_info * Fluide_generique_CoolProp::info () static
get_info()
const Type_info * Fluide_generique_CoolProp::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Fluide_reel_base.
self_cast() [1/2]
Fluide_generique_CoolProp & Fluide_generique_CoolProp::self_cast (Objet_U & r) static
self_cast() [2/2]
const Fluide_generique_CoolProp & Fluide_generique_CoolProp::self_cast (const Objet_U & r) static
printOn()
Sortie & Fluide_generique_CoolProp::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Fluide_reel_base.
readOn()
Entree & Fluide_generique_CoolProp::readOn (Entree & is) override protected virtual
Lit les caracteristiques du fluide a partir d'un flot d'entree.
Format: Fluide_base { Mu type_champ bloc de lecture de champ Rho Champ_Uniforme 1 vrel [Cp Champ_Uniforme 1 vrel] [Lambda type_champ bloc de lecture de champ] [Beta_th type_champ bloc de lecture de champ] [Beta_co type_champ bloc de lecture de champ] } cf Milieu_base::readOn
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Exceptions
accolade ouvrante attendue
Reimplemented from Fluide_reel_base.
References Fluide_generique_TPPI_base::fluid_name_, Fluide_generique_TPPI_base::hmax_, Fluide_generique_TPPI_base::hmin_, Fluide_generique_TPPI_base::model_name_, Fluide_generique_TPPI_base::pmax_, Fluide_generique_TPPI_base::pmin_, Fluide_generique_TPPI_base::readOn(), Fluide_reel_base::res_en_T_, Fluide_generique_TPPI_base::tmax_, Fluide_generique_TPPI_base::tmin_, and Fluide_generique_TPPI_base::TPPI_.
set_param()
void Fluide_generique_CoolProp::set_param (Param & param) override virtual
Reimplemented from Fluide_reel_base.
References Param::ajouter(), Fluide_generique_TPPI_base::fluid_name_, Fluide_generique_TPPI_base::model_name_, Param::OPTIONAL, Param::REQUIRED, and Fluide_reel_base::set_param().
Member Data Documentation
info_obj
const Type_info Fluide_generique_CoolProp::info_obj static