TrioCFD: Op_Dift_VEF_base Class Reference
Op_Dift_VEF_base Class Reference
#include <Op_Dift_VEF_base.h>
Public Member Functions
double calculer_dt_stab () const override
void completer () override
void dimensionner (Matrice_Morse &matrice) const override
const Type_info * get_info () const override
void mettre_a_jour (double temps) override
void modifier_pour_Cl (Matrice_Morse &matrice, DoubleTab &secmem) const override
Public Member Functions inherited from Op_Diff_VEF_base
double calculer_dt_stab () const override
const Type_info * get_info () const override
int impr (Sortie &os) const override
Public Member Functions inherited from Operateur_Diff_base
virtual void associer_diffusivite_pour_pas_de_temps (const Champ_base &)
const Type_info * get_info () const override
Public Member Functions inherited from Operateur_base
void associer_eqn (const Equation_base &)
virtual double calculer_dt_stab () const
virtual void completer ()
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual void mettre_a_jour (double temps)
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Public Member Functions inherited from Op_VEF_Face
void dimensionner (const Domaine_VEF &, const Domaine_Cl_VEF &, Matrice_Morse &) const
void modifier_matrice_pour_periodique_apres_contribuer (Matrice_Morse &matrice, const Equation_base &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Operateur_Diff_base
virtual const Champ_base & diffusivite_pour_pas_de_temps () const
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Op_Dift_VEF_base()
Op_Dift_VEF_base::Op_Dift_VEF_base ()
~Op_Dift_VEF_base()
Op_Dift_VEF_base::~Op_Dift_VEF_base () override
Member Function Documentation
info()
const Type_info * Op_Dift_VEF_base::info () static
get_info()
const Type_info * Op_Dift_VEF_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Op_Diff_VEF_base.
Reimplemented in Op_Diff_K_Eps_QC_VEF_Face, Op_Diff_K_Eps_VEF_base, Op_Diff_K_Eps_VEF_Face, Op_Diff_K_Omega_VEF_base, Op_Diff_K_Omega_VEF_Face, Op_Dift_VEF_Face, Op_Dift_VEF_Face_Q1, and Op_Dift_VEF_P1NCP1B_Face.
self_cast() [1/2]
Op_Dift_VEF_base & Op_Dift_VEF_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Op_Dift_VEF_base & Op_Dift_VEF_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Op_Dift_VEF_base::printOn (Sortie & os) const override protected virtual
DOES NOTHING - to override in derived classes.
Imprime l'operateur sur un flot de sortie.
Parameters
(Sortie& os) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Op_Diff_VEF_base.
Reimplemented in Op_Diff_K_Eps_QC_VEF_Face, Op_Diff_K_Eps_VEF_base, Op_Diff_K_Eps_VEF_Face, Op_Diff_K_Omega_VEF_base, Op_Diff_K_Omega_VEF_Face, Op_Dift_VEF_Face, Op_Dift_VEF_Face_Q1, and Op_Dift_VEF_P1NCP1B_Face.
References Op_Diff_VEF_base::printOn().
readOn()
Entree & Op_Dift_VEF_base::readOn (Entree & is) override protected virtual
DOES NOTHING - to override in derived classes.
Lit un operateur sur un flot d'entree.
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Op_Diff_VEF_base.
Reimplemented in Op_Diff_K_Eps_QC_VEF_Face, Op_Diff_K_Eps_VEF_base, Op_Diff_K_Eps_VEF_Face, Op_Diff_K_Omega_VEF_base, Op_Diff_K_Omega_VEF_Face, Op_Dift_VEF_Face, Op_Dift_VEF_Face_Q1, and Op_Dift_VEF_P1NCP1B_Face.
References Op_Diff_VEF_base::readOn().
calculer_dt_stab()
double Op_Dift_VEF_base::calculer_dt_stab () const override virtual
Calcul dt_stab.
Returns
(double) renvoie toujours 1.e30
Reimplemented from Op_Diff_VEF_base.
Reimplemented in Op_Dift_VEF_Face_Q1, and Op_Dift_VEF_P1NCP1B_Face.
References Domaine_VEF::carre_pas_maille(), Operateur_Diff_base::diffusivite_pour_pas_de_temps(), Op_Diff_Turbulent_base::diffusivite_turbulente(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Domaine_dis_base::domaine(), Op_Diff_VEF_base::domaine_vef(), MorEqn::equation(), Support_Champ_Masse_Volumique::get_champ_masse_volumique(), Support_Champ_Masse_Volumique::has_champ_masse_volumique(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), MorEqn::mon_equation, Process::mp_min(), Domaine_32_64< _SIZE_ >::nb_elem(), Domaine_dis_base::nb_elem_tot(), Op_Diff_VEF_base::nu_, Objet_U::que_suis_je(), Op_Diff_VEF_base::remplir_nu(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), Champ_Don_base::valeurs(), Champ_Proto::valeurs(), TRUSTArray< _TYPE_, _SIZE_ >::view_ro(), and TRUSTTab< _TYPE_, _SIZE_ >::view_ro().
Referenced by calculer_pour_post().
calculer_pour_post()
void Op_Dift_VEF_base::calculer_pour_post (Champ_base & espace_stockage, const Nom & option, int comp) const override virtual
Reimplemented from Op_Diff_VEF_base.
References calculer_dt_stab(), Op_Diff_VEF_base::calculer_pour_post(), Domaine_VEF::carre_pas_maille(), Operateur_Diff_base::diffusivite_pour_pas_de_temps(), Op_Diff_Turbulent_base::diffusivite_turbulente(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Domaine_dis_base::domaine(), Op_Diff_VEF_base::domaine_vef(), Support_Champ_Masse_Volumique::get_champ_masse_volumique(), Support_Champ_Masse_Volumique::has_champ_masse_volumique(), Op_Diff_VEF_base::le_dom_vef, Domaine_32_64< _SIZE_ >::nb_elem(), Domaine_dis_base::nb_elem_tot(), TRUST_Ref< _CLASSE_ >::non_nul(), Op_Diff_VEF_base::nu_, Op_Diff_VEF_base::remplir_nu(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), Champ_Don_base::valeurs(), and Champ_Proto::valeurs().
associer_diffusivite()
void Op_Dift_VEF_base::associer_diffusivite (const Champ_base & diffu) inline override virtual
Implements Operateur_Diff_base.
References diffusivite_.
diffusivite() [1/2]
const Champ_base & Op_Dift_VEF_base::diffusivite () const inline override virtual
Implements Operateur_Diff_base.
References diffusivite_, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Op_Dift_VEF_Face_Q1::ajouter(), Op_Dift_VEF_P1NCP1B_Face::ajouter(), calculer_borne_locale(), calculer_dt_stab_P1NCP1B(), Op_Dift_VEF_Face_Q1::contribuer_a_avec(), and diffusivite().
diffusivite() [2/2]
double Op_Dift_VEF_base::diffusivite (int) const inline
References diffusivite(), and Champ_Proto::valeurs().
dimensionner()
void Op_Dift_VEF_base::dimensionner (Matrice_Morse & mat) const inline override virtual
DOES NOTHING - to override in derived classes.
Parameters
(Matrice_Morse&) une matrice au format Morse
Exceptions
methode a surcharger
Reimplemented from Operateur_base.
References Op_VEF_Face::dimensionner(), Op_Diff_VEF_base::la_zcl_vef, Op_Diff_VEF_base::le_dom_vef, and TRUST_Ref< _CLASSE_ >::valeur().
modifier_pour_Cl()
void Op_Dift_VEF_base::modifier_pour_Cl (Matrice_Morse & , DoubleTab &) const inline override virtual
DOES NOTHING - to override in derived classes.
Parameters
(Matrice_Morse&) une matrice au format Morse
(DoubleTab&) un tableau de valeur (double)
Exceptions
methode a surcharger
Reimplemented from Operateur_base.
Reimplemented in Op_Diff_K_Eps_VEF_Face, and Op_Diff_K_Omega_VEF_Face.
References Op_Diff_VEF_base::la_zcl_vef, Op_Diff_VEF_base::le_dom_vef, Op_VEF_Face::modifier_pour_Cl(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Op_Diff_K_Eps_VEF_Face::modifier_pour_Cl(), and Op_Diff_K_Omega_VEF_Face::modifier_pour_Cl().
calculer_borne_locale()
void Op_Dift_VEF_base::calculer_borne_locale (DoubleVect & tab_borne_visco_turb, double dt_conv, double dt_diff_sur_dt_conv) const override virtual
Reimplemented from Operateur_Diff_base.
References Domaine_VEF::carre_pas_maille(), diffusivite(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Op_Diff_VEF_base::domaine_vef(), Domaine_dis_base::nb_elem(), Champ_Proto::valeurs(), TRUSTArray< _TYPE_, _SIZE_ >::view_ro(), TRUSTTab< _TYPE_, _SIZE_ >::view_ro(), and TRUSTArray< _TYPE_, _SIZE_ >::view_rw().
associer_modele_turbulence()
void Op_Dift_VEF_base::associer_modele_turbulence (const Modele_turbulence_hyd_base & mod)
References le_modele_turbulence.
Referenced by completer().
mettre_a_jour()
void Op_Dift_VEF_base::mettre_a_jour (double temps) override virtual
DOES NOTHING - to override in derived classes.
Mise a jour de l'operateur
Parameters
(double) un pas de temps
Reimplemented from Operateur_base.
References MorEqn::equation(), le_modele_turbulence, TRUSTTab< _TYPE_, _SIZE_ >::ref(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and tau_tan_.
associer()
void Op_Dift_VEF_base::associer (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_cl_dis, const Champ_Inc_base & ch_transporte) override virtual
Reimplemented from Op_Diff_VEF_base.
Reimplemented in Op_Dift_VEF_P1NCP1B_Face.
References Op_Diff_VEF_base::inconnue_, Op_Diff_VEF_base::la_zcl_vef, and Op_Diff_VEF_base::le_dom_vef.
completer()
void Op_Dift_VEF_base::completer () override virtual
Associe l'operateur au domaine_dis, le domaine_Cl_dis, et a l'inconnue de son equation.
Exceptions
pas d'equation associee
Reimplemented from Operateur_base.
Reimplemented in Op_Diff_K_Eps_VEF_base, and Op_Diff_K_Omega_VEF_base.
References Op_Diff_Turbulent_base::associer_diffusivite_turbulente(), associer_modele_turbulence(), Operateur_base::completer(), Modele_turbulence_scal_base::conductivite_turbulente(), MorEqn::equation(), Process::exit(), Equation_base::get_modele(), TRUST_Ref_Objet_U::non_nul(), Objet_U::que_suis_je(), TRUST_Ref_Objet_U::valeur(), and Modele_turbulence_hyd_base::viscosite_turbulente().
Referenced by Op_Diff_K_Eps_VEF_base::completer(), Op_Diff_K_Omega_VEF_base::completer(), and Op_Dift_Stab_VEF_Face::completer().
get_tau_tan()
const DoubleTab & Op_Dift_VEF_base::get_tau_tan () const inline
References tau_tan_.
get_modele_turbulence()
const Modele_turbulence_hyd_base & Op_Dift_VEF_base::get_modele_turbulence () const inline
References le_modele_turbulence, and TRUST_Ref< _CLASSE_ >::valeur().
calculer_dt_stab_P1NCP1B()
double Op_Dift_VEF_base::calculer_dt_stab_P1NCP1B () const protected
References diffusivite(), Op_Diff_Turbulent_base::diffusivite_turbulente(), Objet_U::dimension, Domaine_dis_base::domaine(), Op_Diff_VEF_base::domaine_vef(), Domaine_VF::elem_faces(), Domaine_VF::face_normales(), Process::mp_min(), Domaine_32_64< _SIZE_ >::nb_elem(), Domaine_32_64< _SIZE_ >::nb_faces_elem(), Champ_Don_base::valeurs(), and Domaine_VF::volumes().
Referenced by Op_Dift_VEF_Face_Q1::calculer_dt_stab(), and Op_Dift_VEF_P1NCP1B_Face::calculer_dt_stab().
Member Data Documentation
info_obj
const Type_info Op_Dift_VEF_base::info_obj static
le_modele_turbulence
TRUST_Ref< Modele_turbulence_hyd_base *> Op_Dift_VEF_base::le_modele_turbulence protected
Referenced by Op_Dift_VEF_Face_Q1::ajouter(), associer_modele_turbulence(), Op_Dift_VEF_Face::contribuer_au_second_membre(), get_modele_turbulence(), mettre_a_jour(), Op_Diff_K_Eps_VEF_Face::modifier_pour_Cl(), and Op_Diff_K_Omega_VEF_Face::modifier_pour_Cl().
diffusivite_
TRUST_Ref< Champ_base *> Op_Dift_VEF_base::diffusivite_ protected
Referenced by associer_diffusivite(), and diffusivite().
tau_tan_
DoubleTab Op_Dift_VEF_base::tau_tan_ protected
Referenced by Op_Dift_VEF_Face_Q1::ajouter(), Op_Dift_VEF_Face::contribuer_au_second_membre(), get_tau_tan(), and mettre_a_jour().