TrioCFD: Modele_turbulence_hyd_K_Eps_2_Couches Class Reference
Modele_turbulence_hyd_K_Eps_2_Couches Class Reference
#include <Modele_turbulence_hyd_K_Eps_2_Couches.h>
Public Member Functions
Champ_Fonc_base & calculer_viscosite_turbulente (double temps)
const Transport_K_Eps_base & eqn_transp_K_Eps () const override
Transport_K_Eps_base & eqn_transp_K_Eps () override
int get_impr () const
const Type_info * get_info () const override
int get_nbcouches () const
int get_nutswitch () const
int get_switch () const
int get_yswitch () const
Champ_Inc_base & K_Eps ()
const Champ_Inc_base & K_Eps () const
int lire_motcle_non_standard (const Motcle &, Entree &) override
void mettre_a_jour (double) override
int preparer_calcul () override
Public Member Functions inherited from Modele_turbulence_hyd_RANS_K_Eps_base
const Type_info * get_info () const override
int reprendre (Entree &is) override
int sauvegarder (Sortie &os) const override
const Type_info * get_info () const override
Public Member Functions inherited from Modele_turbulence_hyd_base
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Type_info * get_info () const override
virtual void imprimer (Sortie &) const
void lire_distance_paroi ()
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual int preparer_calcul ()
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Modele_turbulence_hyd_RANS_K_Eps_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
equations de Navier-Stokes.
See also
Modele_turbulence_hyd_base Modele_turbulence_hyd_LES_base
Constructor & Destructor Documentation
Modele_turbulence_hyd_K_Eps_2_Couches()
Modele_turbulence_hyd_K_Eps_2_Couches::Modele_turbulence_hyd_K_Eps_2_Couches ()
~Modele_turbulence_hyd_K_Eps_2_Couches()
Modele_turbulence_hyd_K_Eps_2_Couches::~Modele_turbulence_hyd_K_Eps_2_Couches ()
Member Function Documentation
cree_instance()
Objet_U * Modele_turbulence_hyd_K_Eps_2_Couches::cree_instance () static
taille_memoire()
unsigned Modele_turbulence_hyd_K_Eps_2_Couches::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Modele_turbulence_hyd_K_Eps_2_Couches::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Modele_turbulence_hyd_K_Eps_2_Couches::info () static
get_info()
const Type_info * Modele_turbulence_hyd_K_Eps_2_Couches::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Modele_turbulence_hyd_2_eq_base.
self_cast() [1/2]
Modele_turbulence_hyd_K_Eps_2_Couches & Modele_turbulence_hyd_K_Eps_2_Couches::self_cast (Objet_U & r) static
self_cast() [2/2]
const Modele_turbulence_hyd_K_Eps_2_Couches & Modele_turbulence_hyd_K_Eps_2_Couches::self_cast (const Objet_U & r) static
printOn()
Sortie & Modele_turbulence_hyd_K_Eps_2_Couches::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Modele_turbulence_hyd_2_eq_base.
References Objet_U::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Modele_turbulence_hyd_K_Eps_2_Couches::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Modele_turbulence_hyd_2_eq_base.
References Modele_turbulence_hyd_RANS_K_Eps_base::readOn().
set_param()
void Modele_turbulence_hyd_K_Eps_2_Couches::set_param (Param & param) override virtual
Reimplemented from Modele_turbulence_hyd_2_eq_base.
References Param::ajouter_non_std(), Param::REQUIRED, and Modele_turbulence_hyd_RANS_K_Eps_base::set_param().
lire_motcle_non_standard()
int Modele_turbulence_hyd_K_Eps_2_Couches::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
< liste stockant tous les noms de frontiere du domaine
Reimplemented from Modele_turbulence_hyd_base.
References Transport_2eq_base::associer_modele_turbulence(), eqn_transp_K_Eps(), and Modele_turbulence_hyd_base::lire_motcle_non_standard().
completer()
void Modele_turbulence_hyd_K_Eps_2_Couches::completer () override virtual
Simple appel a Transport_K_Eps::completer()
Reimplemented from Modele_turbulence_hyd_base.
References Equation_base::completer(), eqn_transp_K_Eps(), and Modele_turbulence_hyd_2_eq_base::verifie_loi_paroi().
preparer_calcul()
int Modele_turbulence_hyd_K_Eps_2_Couches::preparer_calcul () override virtual
Prepare le calcul.
Initialise la loi de paroi. Remplit le champ wall_length en cas de post traitemetn de la distance_paroi
Returns
(int) code de retour de Turbulence_paroi::init_lois_paroi()
Reimplemented from Modele_turbulence_hyd_base.
References calculer_viscosite_turbulente(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), eqn_transp_K_Eps(), Modele_turbulence_hyd_base::equation(), K_Eps(), Modele_turbulence_hyd_base::la_viscosite_turbulente_, Equation_base::preparer_calcul(), Modele_turbulence_hyd_base::preparer_calcul(), and Champ_Don_base::valeurs().
initTimeStep()
bool Modele_turbulence_hyd_K_Eps_2_Couches::initTimeStep (double dt) override virtual
Reimplemented from Modele_turbulence_hyd_base.
References Equation_base::initTimeStep().
mettre_a_jour()
void Modele_turbulence_hyd_K_Eps_2_Couches::mettre_a_jour (double temps) override virtual
Effectue une mise a jour en temps du modele de turbulence.
Met a jour l'equation de transport K-epsilon, calcule la loi de paroi et la viscosite turbulente au nouveau temps.
Parameters
(double temps) le temps de mise a jour
Implements Modele_turbulence_hyd_base.
References Statistiques::begin_count(), Equation_base::domaine_Cl_dis(), Statistiques::end_count(), Schema_Temps_base::faire_un_pas_de_temps_eqn_base(), K_Eps(), Modele_turbulence_hyd_base::LeCmu_, Domaine_Cl_dis_base::mettre_a_jour(), Equation_base::mettre_a_jour(), and Equation_base::schema_temps().
K_Eps() [1/2]
Champ_Inc_base & Modele_turbulence_hyd_K_Eps_2_Couches::K_Eps () inline
Renvoie le champ inconnue du modele de turbulence i.
e. : (K,Epsilon). Cette inconnue est portee par l'equation de transport K-eps porte par le modele.
Returns
(Champ_Inc_base&) le champ inconnue (K,epsilon)
References Transport_K_Eps_base::inconnue().
Referenced by mettre_a_jour(), and preparer_calcul().
K_Eps() [2/2]
const Champ_Inc_base & Modele_turbulence_hyd_K_Eps_2_Couches::K_Eps () const inline
Renvoie le champ inconnue du modele de turbulence i.
e. : (K,Epsilon). Cette inconnue est portee par l'equation de transport K-eps porte par le modele. (version const)
Returns
(Champ_Inc_base&) le champ inconnue (K,epsilon)
References Transport_K_Eps_base::inconnue().
get_nbcouches()
int Modele_turbulence_hyd_K_Eps_2_Couches::get_nbcouches () const inline
Renvoie le nombre couches utilises pour les lois de paroi Ce nombre est porte par l'equation de transport K_K-eps.
Returns
(int) le nombre de couches
References Transport_K_KEps::get_nbcouches().
Referenced by Paroi_2couches_VDF::calculer_hyd().
get_yswitch()
int Modele_turbulence_hyd_K_Eps_2_Couches::get_yswitch () const inline
Renvoie le y* de switch entre les deux couches pour le modele a deux couches.
(version const)
Returns
(int) le nombre de couches
References Transport_K_KEps::get_yswitch().
Referenced by Paroi_2couches_VDF::calculer_hyd().
get_nutswitch()
int Modele_turbulence_hyd_K_Eps_2_Couches::get_nutswitch () const inline
Renvoie la valeur de nut/nu qui delimite les deux couches.
(version const)
Returns
(int) valeur limite de nu_t/nu
References Transport_K_KEps::get_nutswitch().
Referenced by Paroi_2couches_VDF::calculer_hyd().
get_switch()
int Modele_turbulence_hyd_K_Eps_2_Couches::get_switch () const inline
Renvoie 0 si on choisit le switch par y*, 1 par nu_t.
(version const)
Returns
(int)
References Transport_K_KEps::get_switch().
Referenced by Paroi_2couches_VDF::calculer_hyd().
get_impr()
int Modele_turbulence_hyd_K_Eps_2_Couches::get_impr () const inline
indique si on doit ecrire le domaine des 2 couches dans le .
out. (version const)
Returns
(int) 1 si on imprime , 0 sinon.
References Transport_K_KEps::get_impr().
eqn_transp_K_Eps() [1/2]
Transport_K_Eps_base & Modele_turbulence_hyd_K_Eps_2_Couches::eqn_transp_K_Eps () inline override virtual
Renvoie l'equation.
(version const)
Returns
(Trasnport_K_KEps)
Implements Modele_turbulence_hyd_RANS_K_Eps_base.
Referenced by Paroi_2couches_VDF::calculer_hyd(), completer(), lire_motcle_non_standard(), and preparer_calcul().
eqn_transp_K_Eps() [2/2]
const Transport_K_Eps_base & Modele_turbulence_hyd_K_Eps_2_Couches::eqn_transp_K_Eps () const inline override virtual
Renvoie l'equation.
(version const)
Returns
(Trasnport_K_KEps)
Implements Modele_turbulence_hyd_RANS_K_Eps_base.
equation_k_eps()
const Equation_base & Modele_turbulence_hyd_K_Eps_2_Couches::equation_k_eps (int i) const inline override virtual
Implements Modele_turbulence_hyd_RANS_K_Eps_base.
controler()
void Modele_turbulence_hyd_K_Eps_2_Couches::controler () inline
References Transport_K_Eps_base::controler_K_Eps().
calculer_viscosite_turbulente()
Champ_Fonc_base & Modele_turbulence_hyd_K_Eps_2_Couches::calculer_viscosite_turbulente (double temps)
Calcule la viscosite turbulente au temps demande.
Parameters
(double temps) le temps auquel il faut calculer la viscosite
Returns
(Champ_Fonc_base&) la viscosite turbulente au temps demande
Exceptions
erreur de taille de visco_turb_K_eps
References Champ_base::affecter(), Champ_base::changer_temps(), Modele_turbulence_hyd_RANS_Gen< Modele_turbulence_hyd_K_Eps_2_Couches >::complete_viscosity_field(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Equation_base::domaine_dis(), Process::exit(), Transport_K_Eps_base::inconnue(), Modele_turbulence_hyd_base::la_viscosite_turbulente_, Objet_U::que_suis_je(), TRUSTVect< _TYPE_, _SIZE_ >::size(), Champ_Don_base::valeurs(), and Champ_Proto::valeurs().
Referenced by preparer_calcul().
Member Data Documentation
info_obj
const Type_info Modele_turbulence_hyd_K_Eps_2_Couches::info_obj static