TrioCFD: Domaine_Cl_DG Class Reference
Domaine_Cl_DG Class Reference
#include <Domaine_Cl_DG.h>
Public Member Functions
const Type_info * get_info () const override
int initialiser (double temps) override
Public Member Functions inherited from Domaine_Cl_dis_base
virtual int calculer_coeffs_echange (double temps)
const Cond_lim_base & condition_limite_de_la_face_reelle (int face_globale, int &face_locale) const
const Cond_lim_base & condition_limite_de_la_face_virtuelle (int face_globale, int &face_locale) const
Cond_lim_base & condition_limite_de_la_frontiere (Nom frontiere)
const Cond_lim_base & condition_limite_de_la_frontiere (Nom frontiere) const
int contient_Cl (const Nom &)
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual const Cond_lim & la_cl_de_la_face (int num_face) const
const Nom & le_nom () const override
Conds_lim & les_conditions_limites ()
const Conds_lim & les_conditions_limites () const
Cond_lim & les_conditions_limites (int)
const Cond_lim & les_conditions_limites (int) const
virtual void mettre_a_jour (double temps)
virtual void mettre_a_jour_ss_pas_dt (double temps)
int nb_cond_lim () const
void nommer (const Nom &nom) override
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Domaine_Cl_dis_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Domaine_Cl_DG()
Domaine_Cl_DG::Domaine_Cl_DG ()
~Domaine_Cl_DG()
Domaine_Cl_DG::~Domaine_Cl_DG ()
Member Function Documentation
cree_instance()
Objet_U * Domaine_Cl_DG::cree_instance () static
taille_memoire()
unsigned Domaine_Cl_DG::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Domaine_Cl_DG::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Domaine_Cl_DG::info () static
get_info()
const Type_info * Domaine_Cl_DG::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
Domaine_Cl_DG & Domaine_Cl_DG::self_cast (Objet_U & r) static
self_cast() [2/2]
const Domaine_Cl_DG & Domaine_Cl_DG::self_cast (const Objet_U & r) static
printOn()
Sortie & Domaine_Cl_DG::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
readOn()
Entree & Domaine_Cl_DG::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
References Domaine_Cl_dis_base::readOn().
completer()
void Domaine_Cl_DG::completer (const Domaine_dis_base &) override virtual
Need to investigate.
Implements Domaine_Cl_dis_base.
References modif_perio_fait_.
initialiser()
int Domaine_Cl_DG::initialiser (double temps) override virtual
Initialise les CLs Contrairement aux methodes mettre_a_jour, les methodes.
initialiser des CLs ne peuvent pas dependre de l'exterieur (lui-meme peut ne pas etre initialise)
Returns
(int) 1 si OK, 0 sinon
Reimplemented from Domaine_Cl_dis_base.
References Process::exit(), Domaine_Cl_dis_base::initialiser(), and nb_bord_periodicite().
imposer_cond_lim()
void Domaine_Cl_DG::imposer_cond_lim (Champ_Inc_base & ch, double temps) override virtual
Need to investigate: a priori, nothing to do for DG.
Implements Domaine_Cl_dis_base.
References Process::exit(), Field_base::nature_du_champ(), and Objet_U::que_suis_je().
nb_faces_sortie_libre()
int Domaine_Cl_DG::nb_faces_sortie_libre () const
References Process::exit().
domaine_vf() [1/2]
Domaine_VF & Domaine_Cl_DG::domaine_vf ()
References Domaine_Cl_dis_base::domaine_dis().
domaine_vf() [2/2]
const Domaine_VF & Domaine_Cl_DG::domaine_vf () const
References Domaine_Cl_dis_base::domaine_dis().
nb_bord_periodicite()
int Domaine_Cl_DG::nb_bord_periodicite () const
References Domaine_Cl_dis_base::les_conditions_limites_, and TRUST_Vector< _CLASSE_ >::size().
Referenced by initialiser().
Member Data Documentation
info_obj
const Type_info Domaine_Cl_DG::info_obj static
modif_perio_fait_
int Domaine_Cl_DG::modif_perio_fait_ = 0 protected
Referenced by completer().