TrioCFD: Groupe_Faces_32_64< _SIZE_ > Class Template Reference
Groupe_Faces_32_64< _SIZE_ > Class Template Reference
#include <Groupe_Faces.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Frontiere_32_64< _SIZE_ >
void add (const Frontiere_32_64 &)
void ajouter_faces (const IntTab_t &)
void associer_domaine (const Domaine_t &)
Domaine_t & domaine ()
const Domaine_t & domaine () const
const Type_info * get_info () const override
const Nom & le_nom () const override
IntTab_t & les_sommets_des_faces ()
const IntTab_t & les_sommets_des_faces () const
void nommer (const Nom &) override
void renum (const IntVect_t &)
void typer_faces (const Motcle &)
void typer_faces (const Type_Face &)
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
template<typename _SIZE_>
class Groupe_Faces_32_64< _SIZE_ >
See also
Frontiere Domaine
Member Typedef Documentation
ArrOfInt_t
template<typename _SIZE_ > using Groupe_Faces_32_64< _SIZE_ >::ArrOfInt_t = ArrOfInt_T<_SIZE_>
Constructor & Destructor Documentation
Groupe_Faces_32_64()
template<typename _T_ > Groupe_Faces_32_64< _T_ >::Groupe_Faces_32_64
~Groupe_Faces_32_64()
template<typename _T_ > Groupe_Faces_32_64< _T_ >::~Groupe_Faces_32_64
Member Function Documentation
cree_instance()
template<typename _T_ > Objet_U * Groupe_Faces_32_64< _T_ >::cree_instance static
taille_memoire()
template<typename _T_ > unsigned Groupe_Faces_32_64< _T_ >::taille_memoire override virtual
Implements Objet_U.
duplique()
template<typename _T_ > int Groupe_Faces_32_64< _T_ >::duplique override virtual
Implements Objet_U.
info()
template<typename _T_ > const Type_info * Groupe_Faces_32_64< _T_ >::info static
get_info()
template<typename _T_ > const Type_info * Groupe_Faces_32_64< _T_ >::get_info override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Frontiere_32_64< _SIZE_ >.
self_cast() [1/2]
template<typename _T_ > Groupe_Faces_32_64< _T_ > & Groupe_Faces_32_64< _T_ >::self_cast (Objet_U & r) static
self_cast() [2/2]
template<typename _T_ > const Groupe_Faces_32_64< _T_ > & Groupe_Faces_32_64< _T_ >::self_cast (const Objet_U & r) static
printOn()
template<typename _SIZE_ > Sortie & Groupe_Faces_32_64< _SIZE_ >::printOn (Sortie & os) const override protected virtual
Ecrit la frontiere sur un flot de sortie.
On ecrit: le nom de la frontiere les faces
Parameters
(Sortie& os) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Frontiere_32_64< _SIZE_ >.
References Frontiere_32_64< _SIZE_ >::printOn().
readOn()
template<typename _SIZE_ > Entree & Groupe_Faces_32_64< _SIZE_ >::readOn (Entree & is) override protected virtual
Lit les specification d'une frontiere a partir d'un flot d'entree.
On lit: le nom les faces
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Frontiere_32_64< _SIZE_ >.
References Frontiere_32_64< _SIZE_ >::readOn().
get_indices_faces() [1/2]
template<typename _SIZE_ > const ArrOfInt_t & Groupe_Faces_32_64< _SIZE_ >::get_indices_faces () const inline
Referenced by Perte_Charge_Singuliere::lire_surfaces().
get_indices_faces() [2/2]
template<typename _SIZE_ > ArrOfInt_t & Groupe_Faces_32_64< _SIZE_ >::get_indices_faces () inline
info_obj() [1/2]
const Type_info Groupe_Faces_32_64< int >::info_obj ("Groupe_Faces" , Groupe_Faces_32_64< int >::cree_instance , 1 , Groupe_Faces_32_64bases< int >)
info_obj() [2/2]
const Type_info Groupe_Faces_32_64< trustIdType >::info_obj ("Groupe_Faces" "_64" , Groupe_Faces_32_64< trustIdType >::cree_instance , 1 , Groupe_Faces_32_64bases< trustIdType >)
Member Data Documentation
info_obj
template<typename _SIZE_ > const Type_info Groupe_Faces_32_64< _SIZE_ >::info_obj static