TrioCFD: Proprietes_part_vol Class Reference
Proprietes_part_vol Class Reference
#include <Proprietes_part_vol.h>
Public Member Functions
const Type_info * get_info () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
~Proprietes_part_vol()
Proprietes_part_vol::~Proprietes_part_vol ()
Proprietes_part_vol()
Proprietes_part_vol::Proprietes_part_vol ()
References deltat_v_, diametre_p_, Objet_U::dimension, masse_volumique_p_, nb_particules_, TRUSTTab< _TYPE_, _SIZE_ >::resize(), temperature_p_, and vitesse_p_.
Member Function Documentation
cree_instance()
Objet_U * Proprietes_part_vol::cree_instance () static
taille_memoire()
unsigned Proprietes_part_vol::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Proprietes_part_vol::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Proprietes_part_vol::info () static
get_info()
const Type_info * Proprietes_part_vol::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
Proprietes_part_vol & Proprietes_part_vol::self_cast (Objet_U & r) static
self_cast() [2/2]
const Proprietes_part_vol & Proprietes_part_vol::self_cast (const Objet_U & r) static
printOn()
Sortie & Proprietes_part_vol::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
References Process::exit().
readOn()
Entree & Proprietes_part_vol::readOn (Entree & is) override protected virtual
Lecture des proprietes sur un flot d'entree.
Format de lecture : -cas 1 lecture dans un fichier (motcle fichier) -cas 2 specification des valeurs uniformes (motcle distribution) Appel a lire_distribution()
Reimplemented from Objet_U.
References Process::exit(), Param::lire_avec_accolades_depuis(), Objet_U::que_suis_je(), and set_param().
set_param()
void Proprietes_part_vol::set_param (Param & param)
References Param::ajouter_non_std().
Referenced by readOn().
lire_motcle_non_standard()
int Proprietes_part_vol::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Objet_U.
References diametre_p_, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Process::exit(), lire_distribution(), masse_volumique_p_, nb_particules_, Entree_Fichier_base::ouvrir(), temperature_p_, and vitesse_p_.
completer()
void Proprietes_part_vol::completer ()
References deltat_v_, diametre_p_, Objet_U::dimension, Process::exit(), nb_particules_, TRUSTTab< _TYPE_, _SIZE_ >::resize(), and volume_p_.
Referenced by Transport_Marqueur_FT::completer(), and Transport_Marqueur_FT::construction_ensemble_proprietes().
fixer_nb_particules()
void Proprietes_part_vol::fixer_nb_particules (const int nb_part)
References nb_particules_.
Referenced by Transport_Marqueur_FT::construction_ensemble_proprietes(), and Transport_Marqueur_FT::update_tableaux_apres_transport().
lire_distribution()
void Proprietes_part_vol::lire_distribution (Entree & is)
References Param::ajouter(), Param::ajouter_arr_size_predefinie(), diametre_p_, Objet_U::dimension, Param::lire_avec_accolades_depuis(), masse_volumique_p_, nb_particules_, Objet_U::que_suis_je(), Param::REQUIRED, TRUSTTab< _TYPE_, _SIZE_ >::resize(), temperature_p_, and vitesse_p_.
Referenced by lire_motcle_non_standard().
nettoyer()
void Proprietes_part_vol::nettoyer (const ArrOfInt & som_utilises)
References deltat_v_, diametre_p_, Objet_U::dimension, masse_volumique_p_, nb_particules_, TRUSTTab< _TYPE_, _SIZE_ >::resize(), temperature_p_, vitesse_p_, and volume_p_.
Referenced by Transport_Marqueur_FT::completer(), Transport_Marqueur_FT::construction_ensemble_proprietes(), and Transport_Interfaces_FT_Disc::nettoyer_proprietes_particules().
ajouter_proprietes()
void Proprietes_part_vol::ajouter_proprietes (const Proprietes_part_vol & proprietes_tmp)
References delta_v(), deltat_v_, diametre_p_, diametre_particules(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), masse_vol_particules(), masse_volumique_p_, nb_particules(), nb_particules_, TRUSTTab< _TYPE_, _SIZE_ >::resize(), temperature_p_, temperature_particules(), vitesse_p_, vitesse_particules(), volume_p_, and volume_particules().
Referenced by Transport_Marqueur_FT::injection().
vitesse_particules() [1/2]
DoubleTab & Proprietes_part_vol::vitesse_particules () inline
References vitesse_p_.
Referenced by ajouter_proprietes(), Transport_Marqueur_FT::calcul_vitesse_p(), Transport_Marqueur_FT::construction_ensemble_proprietes(), Transport_Marqueur_FT::imposer_cond_lim(), Transport_Marqueur_FT::initTimeStep(), Transport_Marqueur_FT::preparer_tableaux_avant_transport(), Transport_Marqueur_FT::transformation(), Transport_Marqueur_FT::update_delta_v(), Transport_Marqueur_FT::update_tableaux_apres_transport(), and Source_Action_Particules::vitesse_particules().
vitesse_particules() [2/2]
const DoubleTab & Proprietes_part_vol::vitesse_particules () const inline
References vitesse_p_.
delta_v() [1/2]
DoubleTab & Proprietes_part_vol::delta_v () inline
References deltat_v_.
Referenced by ajouter_proprietes(), Transport_Marqueur_FT::construction_ensemble_proprietes(), Source_Action_Particules::delta_v(), Transport_Marqueur_FT::preparer_tableaux_avant_transport(), Transport_Marqueur_FT::update_delta_v(), and Transport_Marqueur_FT::update_tableaux_apres_transport().
delta_v() [2/2]
const DoubleTab & Proprietes_part_vol::delta_v () const inline
References deltat_v_.
temperature_particules() [1/2]
DoubleTab & Proprietes_part_vol::temperature_particules () inline
References temperature_p_.
Referenced by ajouter_proprietes(), Transport_Marqueur_FT::construction_ensemble_proprietes(), Transport_Marqueur_FT::preparer_tableaux_avant_transport(), and Transport_Marqueur_FT::update_tableaux_apres_transport().
temperature_particules() [2/2]
const DoubleTab & Proprietes_part_vol::temperature_particules () const inline
References temperature_p_.
masse_vol_particules() [1/2]
DoubleTab & Proprietes_part_vol::masse_vol_particules () inline
References masse_volumique_p_.
Referenced by ajouter_proprietes(), Transport_Marqueur_FT::construction_ensemble_proprietes(), Transport_Marqueur_FT::preparer_tableaux_avant_transport(), Transport_Marqueur_FT::resoudre_edo(), Source_Action_Particules::rho_particules(), and Transport_Marqueur_FT::update_tableaux_apres_transport().
masse_vol_particules() [2/2]
const DoubleTab & Proprietes_part_vol::masse_vol_particules () const inline
References masse_volumique_p_.
diametre_particules() [1/2]
DoubleTab & Proprietes_part_vol::diametre_particules () inline
References diametre_p_.
Referenced by ajouter_proprietes(), Transport_Marqueur_FT::construction_ensemble_proprietes(), Source_Action_Particules::diametre_particules(), Transport_Marqueur_FT::preparer_tableaux_avant_transport(), and Transport_Marqueur_FT::update_tableaux_apres_transport().
diametre_particules() [2/2]
const DoubleTab & Proprietes_part_vol::diametre_particules () const inline
References diametre_p_.
volume_particules() [1/2]
DoubleTab & Proprietes_part_vol::volume_particules () inline
References volume_p_.
Referenced by ajouter_proprietes(), Transport_Marqueur_FT::calculer_valeurs_volumes(), Transport_Marqueur_FT::construction_ensemble_proprietes(), Transport_Marqueur_FT::preparer_tableaux_avant_transport(), Transport_Marqueur_FT::resoudre_edo(), Transport_Marqueur_FT::update_tableaux_apres_transport(), and Source_Action_Particules::volumes_particules().
volume_particules() [2/2]
const DoubleTab & Proprietes_part_vol::volume_particules () const inline
References volume_p_.
nb_particules()
int Proprietes_part_vol::nb_particules () const inline
References nb_particules_.
Referenced by ajouter_proprietes(), Transport_Marqueur_FT::initTimeStep(), Transport_Marqueur_FT::injection(), Transport_Marqueur_FT::preparer_calcul(), Transport_Marqueur_FT::preparer_tableaux_avant_transport(), Transport_Marqueur_FT::resoudre_edo(), and Transport_Marqueur_FT::update_tableaux_apres_transport().
Member Data Documentation
info_obj
const Type_info Proprietes_part_vol::info_obj static
vitesse_p_
DoubleTabFT Proprietes_part_vol::vitesse_p_ protected
Referenced by ajouter_proprietes(), lire_distribution(), lire_motcle_non_standard(), nettoyer(), Proprietes_part_vol(), and vitesse_particules().
deltat_v_
DoubleTabFT Proprietes_part_vol::deltat_v_ protected
Referenced by ajouter_proprietes(), completer(), delta_v(), nettoyer(), and Proprietes_part_vol().
temperature_p_
DoubleTabFT Proprietes_part_vol::temperature_p_ protected
Referenced by ajouter_proprietes(), lire_distribution(), lire_motcle_non_standard(), nettoyer(), Proprietes_part_vol(), and temperature_particules().
masse_volumique_p_
DoubleTabFT Proprietes_part_vol::masse_volumique_p_ protected
Referenced by ajouter_proprietes(), lire_distribution(), lire_motcle_non_standard(), masse_vol_particules(), nettoyer(), and Proprietes_part_vol().
diametre_p_
DoubleTabFT Proprietes_part_vol::diametre_p_ protected
Referenced by ajouter_proprietes(), completer(), diametre_particules(), lire_distribution(), lire_motcle_non_standard(), nettoyer(), and Proprietes_part_vol().
volume_p_
DoubleTabFT Proprietes_part_vol::volume_p_ protected
Referenced by ajouter_proprietes(), completer(), nettoyer(), and volume_particules().
nb_particules_
int Proprietes_part_vol::nb_particules_ protected
Referenced by ajouter_proprietes(), completer(), fixer_nb_particules(), lire_distribution(), lire_motcle_non_standard(), nb_particules(), nettoyer(), and Proprietes_part_vol().