TrioCFD: Entree_fluide_temperature_imposee_H Class Reference
Entree_fluide_temperature_imposee_H Class Reference
#include <Entree_fluide_temperature_imposee_H.h>
Public Member Functions
const Type_info * get_info () const override
double val_imp (int i) const override
double val_imp (int i, int j) const override
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Dirichlet
const Type_info * get_info () const override
virtual double val_imp (int i) const
virtual double val_imp (int i, int j) const
void verifie_ch_init_nb_comp () const override
Public Member Functions inherited from Cond_lim_base
virtual int a_mettre_a_jour_ss_pas_dt ()
virtual void associer_domaine_cl_dis_base (const Domaine_Cl_dis_base &)
virtual void associer_fr_dis_base (const Frontiere_dis_base &)
virtual void calculer_coeffs_echange (double temps)
virtual int compatible_avec_discr (const Discretisation_base &) const
Domaine_Cl_dis_base & domaine_Cl_dis ()
const Domaine_Cl_dis_base & domaine_Cl_dis () const
virtual Frontiere_dis_base & frontiere_dis ()
virtual const Frontiere_dis_base & frontiere_dis () const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
void set_modifier_val_imp (int)
virtual void verifie_ch_init_nb_comp () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Cond_lim_base
void err_pas_compatible (const Discretisation_base &) const
void err_pas_compatible (const Equation_base &) const
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
See also
Dirichlet_entree_fluide
Constructor & Destructor Documentation
Entree_fluide_temperature_imposee_H()
Entree_fluide_temperature_imposee_H::Entree_fluide_temperature_imposee_H ()
~Entree_fluide_temperature_imposee_H()
Entree_fluide_temperature_imposee_H::~Entree_fluide_temperature_imposee_H ()
Member Function Documentation
cree_instance()
Objet_U * Entree_fluide_temperature_imposee_H::cree_instance () static
taille_memoire()
unsigned Entree_fluide_temperature_imposee_H::taille_memoire () const override virtual
Reimplemented from Entree_fluide_temperature_imposee.
duplique()
int Entree_fluide_temperature_imposee_H::duplique () const override virtual
Reimplemented from Entree_fluide_temperature_imposee.
info()
const Type_info * Entree_fluide_temperature_imposee_H::info () static
get_info()
const Type_info * Entree_fluide_temperature_imposee_H::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Entree_fluide_temperature_imposee.
self_cast() [1/2]
Entree_fluide_temperature_imposee_H & Entree_fluide_temperature_imposee_H::self_cast (Objet_U & r) static
self_cast() [2/2]
const Entree_fluide_temperature_imposee_H & Entree_fluide_temperature_imposee_H::self_cast (const Objet_U & r) static
printOn()
Sortie & Entree_fluide_temperature_imposee_H::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Entree_fluide_temperature_imposee.
References Objet_U::que_suis_je().
readOn()
Entree & Entree_fluide_temperature_imposee_H::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Entree_fluide_temperature_imposee.
References Cond_lim_base::app_domains, and Dirichlet_entree_fluide::readOn().
completer()
void Entree_fluide_temperature_imposee_H::completer () override virtual
Complete les conditions aux limites.
Reimplemented from Cond_lim_base.
References le_fluide, Cond_lim_base::modifier_val_imp, and Cond_lim_base::mon_dom_cl_dis.
val_imp() [1/2]
double Entree_fluide_temperature_imposee_H::val_imp (int i) const override virtual
Renvoie la valeur imposee sur la i-eme composante du champ a la frontiere.
Parameters
(int i) indice suivant la premiere dimension du champ
Returns
(double) la valeur imposee sur la composante du champ specifiee
Exceptions
deuxieme dimension du champ de frontiere superieur a 1
Reimplemented from Dirichlet.
References Process::abort(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Cond_lim_base::le_champ_front, le_fluide, Cond_lim_base::modifier_val_imp, TRUSTVect< _TYPE_, _SIZE_ >::size(), and Champ_front_base::valeurs().
val_imp() [2/2]
double Entree_fluide_temperature_imposee_H::val_imp (int i, int j) const override virtual
Renvoie la valeur imposee sur la (i,j)-eme composante du champ a la frontiere.
Parameters
(int i) indice suivant la premiere dimension du champ
(int j) indice suivant la deuxieme dimension du champ
Returns
(double) la valeur imposee sur la composante du champ specifiee
Reimplemented from Dirichlet.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Cond_lim_base::le_champ_front, le_fluide, Cond_lim_base::modifier_val_imp, and Champ_front_base::valeurs().
Member Data Documentation
info_obj
const Type_info Entree_fluide_temperature_imposee_H::info_obj static
le_fluide
TRUST_Ref< Fluide_Dilatable_base *> Entree_fluide_temperature_imposee_H::le_fluide protected
Referenced by completer(), and val_imp().