TrioCFD: Nucleation_paroi_PolyMAC_P0 Class Reference
Nucleation_paroi_PolyMAC_P0 Class Reference
#include <Nucleation_paroi_PolyMAC_P0.h>
Public Member Functions
const Type_info * get_info () const override
void mettre_a_jour (double temps) override
Public Member Functions inherited from Source_base
virtual int a_pour_Champ_Fonc (const Motcle &mot, TRUST_Ref< Champ_base * > &ch_ref) const
virtual void associer_champ_rho (const Champ_base &champ_rho)
virtual void completer ()
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
virtual void resetTime (double t)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Nucleation_paroi_PolyMAC_P0()
Nucleation_paroi_PolyMAC_P0::Nucleation_paroi_PolyMAC_P0 ()
~Nucleation_paroi_PolyMAC_P0()
Nucleation_paroi_PolyMAC_P0::~Nucleation_paroi_PolyMAC_P0 ()
Member Function Documentation
cree_instance()
Objet_U * Nucleation_paroi_PolyMAC_P0::cree_instance () static
taille_memoire()
unsigned Nucleation_paroi_PolyMAC_P0::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Nucleation_paroi_PolyMAC_P0::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Nucleation_paroi_PolyMAC_P0::info () static
get_info()
const Type_info * Nucleation_paroi_PolyMAC_P0::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Source_base.
self_cast() [1/2]
Nucleation_paroi_PolyMAC_P0 & Nucleation_paroi_PolyMAC_P0::self_cast (Objet_U & r) static
self_cast() [2/2]
const Nucleation_paroi_PolyMAC_P0 & Nucleation_paroi_PolyMAC_P0::self_cast (const Objet_U & r) static
printOn()
Sortie & Nucleation_paroi_PolyMAC_P0::printOn (Sortie & os) const override protected virtual
DOES NOTHING - to override in derived classes.
Imprime la source sur un flot de sortie.
Parameters
(Sortie& os) le flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Source_base.
readOn()
Entree & Nucleation_paroi_PolyMAC_P0::readOn (Entree & is) override protected virtual
DOES NOTHING - to override in derived classes.
Lecture d'un terme source sur un flot d'entree.
Parameters
(Entree& is) le flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Source_base.
References Flux_parietal_base::calculates_bubble_nucleation_diameter(), Nom::debute_par(), MorEqn::equation(), Pb_Multiphase::equation(), Process::exit(), Probleme_base::get_correlation(), Probleme_base::has_correlation(), n_l, Pb_Multiphase::nb_phases(), Pb_Multiphase::nom_phase(), TRUST_Ref< _CLASSE_ >::non_nul(), Objet_U::que_suis_je(), TRUST_List< _CLASSE_ >::size(), Equation_base::sources(), and src_flux_interfacial_.
has_interface_blocs()
int Nucleation_paroi_PolyMAC_P0::has_interface_blocs () const inline override virtual
Reimplemented from Source_base.
dimensionner_blocs()
void Nucleation_paroi_PolyMAC_P0::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl = {}) const override virtual
Reimplemented from Source_base.
ajouter_blocs()
void Nucleation_paroi_PolyMAC_P0::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = {}) const override virtual
Reimplemented from Source_base.
References MorEqn::equation(), Pb_Multiphase::equation(), Pb_Multiphase::equation_qdm(), Probleme_base::get_champ(), Milieu_composite::get_saturation(), Milieu_composite::has_saturation(), Operateur::l_op_base(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Saturation_base::Lvap(), Milieu_base::masse_volumique(), Probleme_base::milieu(), n_l, Pb_Multiphase::nb_phases(), Equation_base::operateur(), Champ_Proto::passe(), src_flux_interfacial_, TRUST_Ref< _CLASSE_ >::valeur(), and Champ_Proto::valeurs().
check_multiphase_compatibility()
void Nucleation_paroi_PolyMAC_P0::check_multiphase_compatibility () const inline override virtual
Reimplemented from MorEqn.
associer_domaines()
void Nucleation_paroi_PolyMAC_P0::associer_domaines (const Domaine_dis_base & , const Domaine_Cl_dis_base &) inline override virtual
Implements Source_base.
associer_pb()
void Nucleation_paroi_PolyMAC_P0::associer_pb (const Probleme_base &) inline override virtual
Implements Source_base.
mettre_a_jour()
void Nucleation_paroi_PolyMAC_P0::mettre_a_jour (double temps) inline override virtual
DOES NOTHING - to override in derived classes.
Mise a jour en temps du terme source.
Parameters
(double) le pas de temps de mise a jour
Reimplemented from Source_base.
Member Data Documentation
info_obj
const Type_info Nucleation_paroi_PolyMAC_P0::info_obj static
n_l
int Nucleation_paroi_PolyMAC_P0::n_l = -1 protected
Referenced by ajouter_blocs(), and readOn().
src_flux_interfacial_
TRUST_Ref< Source_base *> Nucleation_paroi_PolyMAC_P0::src_flux_interfacial_ protected
Referenced by ajouter_blocs(), and readOn().