TrioCFD: Fluide_Ostwald Class Reference
Fluide_Ostwald Class Reference
#include <Fluide_Ostwald.h>
Public Member Functions
const Type_info * get_info () const override
void mettre_a_jour (double) override
Public Member Functions inherited from Fluide_Incompressible
const Type_info * get_info () const override
void verifier_coherence_champs (int &err, Nom &message) override
const Type_info * get_info () const override
void mettre_a_jour (double) override
void verifier_coherence_champs (int &err, Nom &message) override
Public Member Functions inherited from Milieu_base
virtual int a_gravite () const
int associer_ (Objet_U &) override
virtual void associer_gravite (const Champ_Don_base &)
virtual Champ_Don_base & beta_t ()
virtual const Champ_Don_base & beta_t () const
virtual Champ_Don_base & capacite_calorifique ()
virtual const Champ_Don_base & capacite_calorifique () const
virtual Champ_Don_base & conductivite ()
virtual const Champ_Don_base & conductivite () const
virtual Champ_Don_base & diffusivite ()
virtual const Champ_Don_base & diffusivite () const
virtual int est_deja_associe ()
const Type_info * get_info () const override
virtual Champ_Don_base & gravite ()
virtual const Champ_Don_base & gravite () const
const Nom & le_nom () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual Champ_base & masse_volumique ()
virtual const Champ_base & masse_volumique () const
void nommer (const Nom &) override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Fluide_base
void creer_nu ()
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Milieu_base
virtual void calculer_alpha ()
void ecrire (Sortie &) const
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
Possede les proprietes d'un fluide incompressible plus: N : indice de structure K : consistance du fluide La viscosite dynamique dans ce cas depend de K, N et Grad(U) Nouveau fluide. c'est un fluide incompressible non newtonien. Il derive donc de fluide_Incompressible et possede quelques proprietes de plus (K, N) mu depend de K, N, et de grad(U)
See also
Fluide_Incompressible
Constructor & Destructor Documentation
~Fluide_Ostwald()
Fluide_Ostwald::~Fluide_Ostwald ()
Fluide_Ostwald()
Fluide_Ostwald::Fluide_Ostwald ()
Member Function Documentation
cree_instance()
Objet_U * Fluide_Ostwald::cree_instance () static
taille_memoire()
unsigned Fluide_Ostwald::taille_memoire () const override virtual
Reimplemented from Fluide_Incompressible.
duplique()
int Fluide_Ostwald::duplique () const override virtual
Reimplemented from Fluide_Incompressible.
info()
const Type_info * Fluide_Ostwald::info () static
get_info()
const Type_info * Fluide_Ostwald::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Fluide_Incompressible.
self_cast() [1/2]
Fluide_Ostwald & Fluide_Ostwald::self_cast (Objet_U & r) static
self_cast() [2/2]
const Fluide_Ostwald & Fluide_Ostwald::self_cast (const Objet_U & r) static
printOn()
Sortie & Fluide_Ostwald::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Fluide_Incompressible.
References Milieu_base::ecrire(), K_, and N_.
readOn()
Entree & Fluide_Ostwald::readOn (Entree & is) override protected virtual
Lit les caracteristiques du fluide a partir d'un flot d'entree.
Format: Fluide_base { Mu type_champ bloc de lecture de champ Rho Champ_Uniforme 1 vrel [Cp Champ_Uniforme 1 vrel] [Lambda type_champ bloc de lecture de champ] [Beta_th type_champ bloc de lecture de champ] [Beta_co type_champ bloc de lecture de champ] } cf Milieu_base::readOn
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Exceptions
accolade ouvrante attendue
Reimplemented from Fluide_Incompressible.
References Fluide_Incompressible::readOn().
consistance() [1/2]
const Champ_Don_base & Fluide_Ostwald::consistance () const inline
References K_, and TRUST_Deriv< _CLASSE_ >::valeur().
consistance() [2/2]
Champ_Don_base & Fluide_Ostwald::consistance () inline
References K_, and TRUST_Deriv< _CLASSE_ >::valeur().
indice_struct() [1/2]
const Champ_Don_base & Fluide_Ostwald::indice_struct () const inline
References N_, and TRUST_Deriv< _CLASSE_ >::valeur().
indice_struct() [2/2]
Champ_Don_base & Fluide_Ostwald::indice_struct () inline
References N_, and TRUST_Deriv< _CLASSE_ >::valeur().
set_param()
void Fluide_Ostwald::set_param (Param & param) override virtual
Reimplemented from Fluide_Incompressible.
References Param::ajouter(), Param::ajouter_condition(), K_, N_, Param::REQUIRED, and Fluide_Incompressible::set_param().
creer_champs_non_lus()
void Fluide_Ostwald::creer_champs_non_lus () override virtual
Reimplemented from Fluide_base.
References Milieu_base::creer_champs_non_lus().
mettre_a_jour()
void Fluide_Ostwald::mettre_a_jour (double temps) override virtual
Effectue une mise a jour en temps du milieu, et donc de ses parametres caracteristiques.
Les champs uniformes sont recalcules pour le nouveau temps specifie, les autres sont mis a par un appel a CLASSE_DU_CHAMP::mettre_a_jour(double temps).
Parameters
(double temps) le temps de mise a jour
Reimplemented from Fluide_base.
References K_, Champ_Don_base::mettre_a_jour(), Fluide_base::mettre_a_jour(), N_, and Objet_U_ptr::non_nul().
initialiser()
int Fluide_Ostwald::initialiser (const double temps) override virtual
Initialise les parametres du fluide.
Reimplemented from Fluide_base.
References Fluide_base::initialiser().
discretiser()
void Fluide_Ostwald::discretiser (const Probleme_base & pb, const Discretisation_base & dis) override virtual
Reimplemented from Fluide_base.
References Champs_compris_T< FIELD_TYPE >::ajoute_champ(), Fluide_base::ch_mu_, Milieu_base::champs_compris_, Nom::debute_par(), Fluide_base::discretiser(), Equation_base::domaine_dis(), Probleme_base::equation(), Navier_Stokes_std::inconnue(), K_, Discretisation_base::nommer_completer_champ_physique(), Objet_U_ptr::non_nul(), Discret_Thyd::proprietes_physiques_fluide_Ostwald(), Objet_U::que_suis_je(), Objet_U_ptr::typer(), and TRUST_Deriv< _CLASSE_ >::valeur().
Member Data Documentation
info_obj
const Type_info Fluide_Ostwald::info_obj static
K_
TRUST_Deriv< Champ_Don_base > Fluide_Ostwald::K_ protected
Referenced by consistance(), discretiser(), mettre_a_jour(), printOn(), and set_param().
N_
TRUST_Deriv< Champ_Don_base > Fluide_Ostwald::N_ protected
Referenced by indice_struct(), mettre_a_jour(), printOn(), and set_param().