TrioCFD: Turbulence_paroi_scal_base Class Reference
Turbulence_paroi_scal_base Class Reference abstract
#include <Turbulence_paroi_scal_base.h>
Public Member Functions
void associer_modele (const Modele_turbulence_scal_base &)
const Type_info * get_info () const override
void imprimer_nusselt_mean_only (Sortie &, int, const TRUST_List< Nom > &, const Nom &) const
void imprimer_premiere_ligne_nusselt (int, const TRUST_List< Nom > &, const Nom &) const
int reprendre (Entree &is) override
int sauvegarder (Sortie &os) const override
virtual bool use_equivalent_distance () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions
static void typer_lire_turbulence_paroi_scal (TRUST_Deriv< Turbulence_paroi_scal_base > &, const Modele_turbulence_scal_base &, Entree &)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
de calcul des grandeurs turbulentes aux voisinages des parois. La methode principale a implenter dans les classes filles est calculer_scal qui doit se charger de calculer et remplir le tableau equivalent_distance_ des distances equivalentes en paroi.
See also
Classe abstraite, Methodes abstraites
Constructor & Destructor Documentation
~Turbulence_paroi_scal_base()
Turbulence_paroi_scal_base::~Turbulence_paroi_scal_base () override
Turbulence_paroi_scal_base()
Turbulence_paroi_scal_base::Turbulence_paroi_scal_base () inline
Member Function Documentation
info()
const Type_info * Turbulence_paroi_scal_base::info () static
get_info()
const Type_info * Turbulence_paroi_scal_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
Reimplemented in Paroi_std_scal_hyd_EF, Loi_expert_scalaire_EF, Loi_Paroi_Nu_Impose_VDF, Paroi_2couches_scal_VDF, Paroi_loi_WW_scal_VDF, Paroi_ODVM_scal_VDF, Paroi_std_scal_hyd_VDF, Loi_expert_scalaire_VDF, Paroi_TBLE_scal_VDF, Loi_Paroi_Nu_Impose_VEF, Paroi_loi_WW_scal_VEF, Paroi_scal_analytique_VEF, Paroi_std_scal_hyd_VEF, Loi_expert_scalaire_VEF, ParoiVEF_TBLE_scal, Paroi_negligeable_scal_VDF, Paroi_scal_hyd_base_VDF, Paroi_negligeable_scal_VEF, and Paroi_scal_hyd_base_VEF.
self_cast() [1/2]
Turbulence_paroi_scal_base & Turbulence_paroi_scal_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Turbulence_paroi_scal_base & Turbulence_paroi_scal_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Turbulence_paroi_scal_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
Reimplemented in Paroi_std_scal_hyd_EF, Loi_expert_scalaire_EF, Loi_Paroi_Nu_Impose_VDF, Paroi_2couches_scal_VDF, Paroi_loi_WW_scal_VDF, Paroi_ODVM_scal_VDF, Paroi_std_scal_hyd_VDF, Loi_expert_scalaire_VDF, Paroi_TBLE_scal_VDF, Loi_Paroi_Nu_Impose_VEF, Paroi_loi_WW_scal_VEF, Paroi_scal_analytique_VEF, Paroi_std_scal_hyd_VEF, Loi_expert_scalaire_VEF, ParoiVEF_TBLE_scal, Paroi_negligeable_scal_VDF, Paroi_scal_hyd_base_VDF, Paroi_negligeable_scal_VEF, and Paroi_scal_hyd_base_VEF.
References Objet_U::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Turbulence_paroi_scal_base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
Reimplemented in Paroi_std_scal_hyd_EF, Loi_expert_scalaire_EF, Loi_Paroi_Nu_Impose_VDF, Paroi_2couches_scal_VDF, Paroi_loi_WW_scal_VDF, Paroi_ODVM_scal_VDF, Paroi_std_scal_hyd_VDF, Loi_expert_scalaire_VDF, Paroi_TBLE_scal_VDF, Loi_Paroi_Nu_Impose_VEF, Paroi_loi_WW_scal_VEF, Paroi_scal_analytique_VEF, Paroi_std_scal_hyd_VEF, Loi_expert_scalaire_VEF, ParoiVEF_TBLE_scal, Paroi_negligeable_scal_VDF, Paroi_scal_hyd_base_VDF, Paroi_negligeable_scal_VEF, and Paroi_scal_hyd_base_VEF.
typer_lire_turbulence_paroi_scal()
void Turbulence_paroi_scal_base::typer_lire_turbulence_paroi_scal (TRUST_Deriv< Turbulence_paroi_scal_base > & turb_par, const Modele_turbulence_scal_base & mod_turb_scal, Entree & s) static
Lit les caracteristques de la loi de parois a partir d'un flot d'entree.
Format: type_de_loi_de_paroi Les valeurs possibles du type de loi de paroi sont:
"loi_standard_hydr"
"negligeable"
"loi_VanDriest"
"loi_standard_hydr_scalaire"
References associer(), associer_modele(), Equation_base::discretisation(), Equation_base::domaine_Cl_dis(), Equation_base::domaine_dis(), Modele_turbulence_scal_base::equation(), Probleme_base::equation(), Process::exit(), Equation_base::get_modele(), Modele_turbulence_hyd_base::loi_paroi(), Equation_base::probleme(), Objet_U::que_suis_je(), and TRUST_Ref_Objet_U::valeur().
Referenced by Modele_turbulence_scal_base::lire_motcle_non_standard().
sauvegarder()
int Turbulence_paroi_scal_base::sauvegarder (Sortie &) const inline override virtual
Sauvegarde d'un Objet_U sur un flot de sortie Methode a surcharger.
Parameters
(Sortie&) flot de sortie a utiliser pour la sauvegarde
Returns
(int) code de retour
Reimplemented from Objet_U.
Reimplemented in Paroi_TBLE_scal_VDF, and ParoiVEF_TBLE_scal.
Referenced by Modele_turbulence_scal_base::sauvegarder().
reprendre()
int Turbulence_paroi_scal_base::reprendre (Entree &) inline override virtual
Reprise d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree&) flot d'entree a utiliser pour la reprise
Returns
(int) code de retour
Reimplemented from Objet_U.
Reimplemented in Paroi_TBLE_scal_VDF, and ParoiVEF_TBLE_scal.
Referenced by Modele_turbulence_scal_base::reprendre().
data_a_sauvegarder()
virtual std::vector< YAML_data > Turbulence_paroi_scal_base::data_a_sauvegarder () const inline virtual
Referenced by Modele_turbulence_scal_base::data_a_sauvegarder().
associer_modele()
void Turbulence_paroi_scal_base::associer_modele (const Modele_turbulence_scal_base & le_modele) inline
Associe un modele de turbulence a l'objet.
Parameters
(Modele_turbulence_hyd_base& le_modele) le modele de turbulence hydraulique a associer a l'objet
References mon_modele_turb_scal.
Referenced by Modele_turbulence_scal_null::readOn(), and typer_lire_turbulence_paroi_scal().
associer()
virtual void Turbulence_paroi_scal_base::associer (const Domaine_dis_base & , const Domaine_Cl_dis_base &) pure virtual
Implemented in Paroi_loi_WW_scal_VEF, Paroi_scal_hyd_base_EF, Paroi_scal_hyd_base_VDF, and Paroi_scal_hyd_base_VEF.
Referenced by Modele_turbulence_scal_null::readOn(), and typer_lire_turbulence_paroi_scal().
completer()
virtual void Turbulence_paroi_scal_base::completer () inline virtual
Referenced by Convection_Diffusion_Turbulent::completer().
init_lois_paroi()
virtual int Turbulence_paroi_scal_base::init_lois_paroi () pure virtual
Implemented in Paroi_std_scal_hyd_EF, Paroi_loi_WW_scal_VDF, Paroi_ODVM_scal_VDF, Paroi_std_scal_hyd_VDF, Paroi_TBLE_scal_VDF, Paroi_std_scal_hyd_VEF, ParoiVEF_TBLE_scal, Paroi_scal_hyd_base_EF, Paroi_scal_hyd_base_VDF, and Paroi_scal_hyd_base_VEF.
Referenced by Modele_turbulence_scal_base::preparer_calcul(), Modele_turbulence_hyd_K_Eps::preparer_calcul(), and Modele_turbulence_hyd_K_Eps_Bicephale::preparer_calcul().
calculer_scal()
virtual int Turbulence_paroi_scal_base::calculer_scal (Champ_Fonc_base &) pure virtual
Implemented in Paroi_std_scal_hyd_EF, Loi_Paroi_Nu_Impose_VDF, Paroi_loi_WW_scal_VDF, Paroi_ODVM_scal_VDF, Paroi_std_scal_hyd_VDF, Paroi_TBLE_scal_VDF, Loi_Paroi_Nu_Impose_VEF, Paroi_loi_WW_scal_VEF, Paroi_scal_analytique_VEF, Paroi_std_scal_hyd_VEF, ParoiVEF_TBLE_scal, Paroi_negligeable_scal_EF, Paroi_negligeable_scal_VDF, and Paroi_negligeable_scal_VEF.
Referenced by Modele_turbulence_scal_Prandtl::mettre_a_jour(), and Modele_turbulence_scal_Schmidt::mettre_a_jour().
compute_nusselt()
virtual void Turbulence_paroi_scal_base::compute_nusselt () const pure virtual
Implemented in Paroi_scal_hyd_base_EF, Paroi_scal_hyd_base_VDF, and Paroi_scal_hyd_base_VEF.
Referenced by imprimer_nusselt_mean_only().
imprimer_nusselt()
virtual void Turbulence_paroi_scal_base::imprimer_nusselt (Sortie &) const inline virtual
Reimplemented in Loi_Paroi_Nu_Impose_VDF, Paroi_TBLE_scal_VDF, Loi_Paroi_Nu_Impose_VEF, ParoiVEF_TBLE_scal, Paroi_scal_hyd_base_EF, Paroi_scal_hyd_base_VDF, and Paroi_scal_hyd_base_VEF.
References Objet_U::que_suis_je().
Referenced by Modele_turbulence_scal_base::imprimer().
imprimer_premiere_ligne_nusselt()
void Turbulence_paroi_scal_base::imprimer_premiere_ligne_nusselt (int boundaries_, const TRUST_List< Nom > & boundaries_list, const Nom & nom_fichier_) const
Writes header line for Nusselt number and heat transfer statistics file.
Parameters
boundaries_ Flag to control boundary selection (0: all boundaries, 1: specified boundaries)
boundaries_list List of boundary names to process
nom_fichier_ Output filename
Creates header line with column names for thermal statistics including:
Characteristic distance (m)
Local Nusselt number
Convective heat transfer coefficient (W/m²/K)
Near-wall fluid temperature (K)
Boundary face temperature (K)
Equivalent wall temperature (K)
Format: "Time Mean(field1) Mean(field2) ... [boundary1(field1) boundary1(field2) ...]" Writes warning messages if specified boundaries are not valid wall types.
References Nom::contient(), Process::je_suis_maitre(), le_dom_Cl_dis_, le_dom_dis_, Objet_U_ptr::le_nom(), nb_fields_, ouvrir_fichier_partage(), EcrFicPartage::syncfile(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by Modele_turbulence_scal_base::preparer_calcul().
imprimer_nusselt_mean_only()
void Turbulence_paroi_scal_base::imprimer_nusselt_mean_only (Sortie & os, int boundaries_, const TRUST_List< Nom > & boundaries_list, const Nom & nom_fichier_) const
Prints mean Nusselt number and heat transfer statistics to a file for specified boundaries.
Parameters
os Output stream for messages
boundaries_ Flag to control boundary selection (0: all boundaries, 1: specified boundaries)
boundaries_list List of boundary names to process when boundaries_=1
nom_fichier_ Output filename
Calculates and writes average values for multiple thermal parameters:
Characteristic distance
Nusselt number
Heat transfer coefficient
Near-wall temperatures
Wall temperatures
Results are written for all boundaries combined and then for each boundary separately. Only processes fixed walls (Dirichlet_paroi_fixe) and moving walls (Dirichlet_paroi_defilante). Output format: time [mean_values] [boundary1_values] [boundary2_values] ...
References compute_nusselt(), Nom::contient(), Process::je_suis_maitre(), le_dom_Cl_dis_, le_dom_dis_, Frontiere_dis_base::le_nom(), mon_modele_turb_scal, Front_VF::nb_faces(), nb_fields_, Front_VF::num_premiere_face(), ouvrir_fichier_partage(), Probleme_base::schema_temps(), EcrFicPartage::syncfile(), tab_, Schema_Temps_base::temps_courant(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by Modele_turbulence_scal_base::imprimer().
creer_champ()
void Turbulence_paroi_scal_base::creer_champ (const Motcle & motlu) override virtual
Implements Champs_compris_interface.
Referenced by Modele_turbulence_scal_base::creer_champ().
get_champ()
const Champ_base & Turbulence_paroi_scal_base::get_champ (const Motcle & nom) const override virtual
Implements Champs_compris_interface.
References Champs_compris_T< FIELD_TYPE >::get_champ().
get_noms_champs_postraitables()
void Turbulence_paroi_scal_base::get_noms_champs_postraitables (Noms & nom, Option opt = NONE) const override virtual
Implements Champs_compris_interface.
References TRUST_Vector< _CLASSE_ >::add(), and Champs_compris_T< FIELD_TYPE >::liste_noms_compris().
Referenced by Modele_turbulence_scal_base::get_noms_champs_postraitables().
has_champ() [1/2]
bool Turbulence_paroi_scal_base::has_champ (const Motcle & nom, TRUST_Ref< Champ_base * > & ref_champ) const override virtual
Implements Champs_compris_interface.
References Champs_compris_T< FIELD_TYPE >::has_champ().
Referenced by Modele_turbulence_scal_base::get_champ(), and Modele_turbulence_scal_base::has_champ().
has_champ() [2/2]
bool Turbulence_paroi_scal_base::has_champ (const Motcle & nom) const override virtual
Implements Champs_compris_interface.
References Champs_compris_T< FIELD_TYPE >::has_champ().
ouvrir_fichier_partage() [1/2]
void Turbulence_paroi_scal_base::ouvrir_fichier_partage (EcrFicPartage & Nusselt, const Nom & extension) const
Ouverture/creation d'un fichier d'impression de Face, d_eq, Nu local, h.
References Process::je_suis_maitre(), Probleme_U::le_nom(), mon_modele_turb_scal, nb_impr_, Objet_U::nom_du_cas(), EcrFicPartage::ouvrir(), Probleme_base::reprise_effectuee(), Probleme_base::schema_temps(), and Schema_Temps_base::temps_courant().
Referenced by Loi_Paroi_Nu_Impose_VDF::imprimer_nusselt(), Loi_Paroi_Nu_Impose_VEF::imprimer_nusselt(), Paroi_scal_hyd_base_EF::imprimer_nusselt(), Paroi_scal_hyd_base_VDF::imprimer_nusselt(), Paroi_scal_hyd_base_VEF::imprimer_nusselt(), imprimer_nusselt_mean_only(), and imprimer_premiere_ligne_nusselt().
ouvrir_fichier_partage() [2/2]
void Turbulence_paroi_scal_base::ouvrir_fichier_partage (EcrFicPartage & fichier, const Nom & nom_fichier, const Nom & extension) const
Ouverture/creation d'un fichier d'impression de moyennes.
References mon_modele_turb_scal, nb_impr0_, EcrFicPartage::ouvrir(), and Probleme_base::reprise_effectuee().
get_flag_calcul_ldp_en_flux_impose()
const int & Turbulence_paroi_scal_base::get_flag_calcul_ldp_en_flux_impose () const inline
References calcul_ldp_en_flux_impose_.
Referenced by Champ_Generique_Tparoi_VEF::get_champ().
use_equivalent_distance()
bool Turbulence_paroi_scal_base::use_equivalent_distance () const virtual
Give a boolean indicating if we need to use equivant distance by default we consider that we use the equivalent distance.
Returns
(boolean)
Reimplemented in Paroi_negligeable_scal_EF, Paroi_negligeable_scal_VDF, and Paroi_negligeable_scal_VEF.
Referenced by Champ_front_contact_VEF::calcul_grads_locaux(), and Champ_Generique_Tparoi_VEF::get_champ().
equivalent_distance_name()
virtual DoubleVect & Turbulence_paroi_scal_base::equivalent_distance_name (DoubleVect & d_eq, const Nom & nom_bord) const pure virtual
Implemented in Paroi_scal_hyd_base_EF, Paroi_scal_hyd_base_VEF, and Paroi_scal_hyd_base_VDF.
equivalent_distance() [1/3]
const DoubleVects & Turbulence_paroi_scal_base::equivalent_distance () const inline
References equivalent_distance_.
Referenced by Source_Robin_Scalaire::ajouter(), Champ_front_contact_VEF::calcul_grads_locaux(), Paroi_scal_hyd_base_EF::equivalent_distance_name(), Paroi_scal_hyd_base_VEF::equivalent_distance_name(), Paroi_scal_hyd_base_VDF::equivalent_distance_name(), Champ_Generique_Tparoi_VEF::get_champ(), Loi_Paroi_Nu_Impose_VEF::imprimer_nusselt(), and PlaqThVDF::mettre_a_jour().
equivalent_distance() [2/3]
const DoubleVect & Turbulence_paroi_scal_base::equivalent_distance (int bord) const inline
References equivalent_distance_, and TRUST_Vector< _CLASSE_ >::size().
equivalent_distance() [3/3]
double Turbulence_paroi_scal_base::equivalent_distance (int bord, int face) const inline
References equivalent_distance_, and TRUST_Vector< _CLASSE_ >::size().
tab_equivalent_distance() [1/2]
const DoubleVects & Turbulence_paroi_scal_base::tab_equivalent_distance () const inline
References equivalent_distance_.
tab_equivalent_distance_size()
int Turbulence_paroi_scal_base::tab_equivalent_distance_size () inline
References equivalent_distance_, and TRUST_Vector< _CLASSE_ >::size().
tab_equivalent_distance() [2/2]
const DoubleVect & Turbulence_paroi_scal_base::tab_equivalent_distance (int bord) const inline
References equivalent_distance_, and TRUST_Vector< _CLASSE_ >::size().
T_plus()
double Turbulence_paroi_scal_base::T_plus (double y_plus, double Pr) inline protected
References Prdt_sur_kappa_.
Referenced by Paroi_std_scal_hyd_EF::calculer_scal(), Paroi_std_scal_hyd_VDF::calculer_scal(), and Paroi_std_scal_hyd_VEF::calculer_scal().
Member Data Documentation
info_obj
const Type_info Turbulence_paroi_scal_base::info_obj static
mon_modele_turb_scal
TRUST_Ref< Modele_turbulence_scal_base *> Turbulence_paroi_scal_base::mon_modele_turb_scal protected
Referenced by associer_modele(), Paroi_std_scal_hyd_EF::calculer_scal(), Loi_Paroi_Nu_Impose_VDF::calculer_scal(), Paroi_loi_WW_scal_VDF::calculer_scal(), Paroi_ODVM_scal_VDF::calculer_scal(), Paroi_std_scal_hyd_VDF::calculer_scal(), Paroi_TBLE_scal_VDF::calculer_scal(), Loi_Paroi_Nu_Impose_VEF::calculer_scal(), Paroi_loi_WW_scal_VEF::calculer_scal(), Paroi_scal_analytique_VEF::calculer_scal(), Paroi_std_scal_hyd_VEF::calculer_scal(), ParoiVEF_TBLE_scal::calculer_scal(), Paroi_scal_hyd_base_EF::compute_nusselt(), Paroi_scal_hyd_base_VDF::compute_nusselt(), Paroi_scal_hyd_base_VEF::compute_nusselt(), Paroi_TBLE_scal_VDF::getLoiParoiHydraulique(), ParoiVEF_TBLE_scal::getLoiParoiHydraulique(), Paroi_TBLE_scal_VDF::getPbBase(), ParoiVEF_TBLE_scal::getPbBase(), Loi_Paroi_Nu_Impose_VDF::imprimer_nusselt(), Paroi_TBLE_scal_VDF::imprimer_nusselt(), Loi_Paroi_Nu_Impose_VEF::imprimer_nusselt(), ParoiVEF_TBLE_scal::imprimer_nusselt(), Paroi_scal_hyd_base_EF::imprimer_nusselt(), Paroi_scal_hyd_base_VDF::imprimer_nusselt(), Paroi_scal_hyd_base_VEF::imprimer_nusselt(), imprimer_nusselt_mean_only(), Paroi_ODVM_scal_VDF::init_lois_paroi(), Paroi_TBLE_scal_VDF::init_lois_paroi(), ParoiVEF_TBLE_scal::init_lois_paroi(), ouvrir_fichier_partage(), Paroi_TBLE_scal_VDF::reprendre(), ParoiVEF_TBLE_scal::reprendre(), Paroi_TBLE_scal_VDF::sauvegarder(), and ParoiVEF_TBLE_scal::sauvegarder().
nb_impr_
int Turbulence_paroi_scal_base::nb_impr_ = 0 mutable protected
Referenced by ouvrir_fichier_partage().
nb_impr0_
int Turbulence_paroi_scal_base::nb_impr0_ = 0 protected
Referenced by ouvrir_fichier_partage().
calcul_ldp_en_flux_impose_
int Turbulence_paroi_scal_base::calcul_ldp_en_flux_impose_ protected
Referenced by get_flag_calcul_ldp_en_flux_impose(), Loi_expert_scalaire_EF::readOn(), and Loi_expert_scalaire_VEF::readOn().
Prdt_sur_kappa_
double Turbulence_paroi_scal_base::Prdt_sur_kappa_ protected
Referenced by Loi_expert_scalaire_EF::readOn(), Loi_expert_scalaire_VDF::readOn(), Loi_expert_scalaire_VEF::readOn(), and T_plus().
equivalent_distance_
DoubleVects Turbulence_paroi_scal_base::equivalent_distance_ protected
Referenced by Paroi_std_scal_hyd_EF::calculer_scal(), Loi_Paroi_Nu_Impose_VDF::calculer_scal(), Paroi_loi_WW_scal_VDF::calculer_scal(), Paroi_ODVM_scal_VDF::calculer_scal(), Paroi_std_scal_hyd_VDF::calculer_scal(), Paroi_TBLE_scal_VDF::calculer_scal(), Loi_Paroi_Nu_Impose_VEF::calculer_scal(), Paroi_loi_WW_scal_VEF::calculer_scal(), Paroi_scal_analytique_VEF::calculer_scal(), Paroi_std_scal_hyd_VEF::calculer_scal(), ParoiVEF_TBLE_scal::calculer_scal(), Paroi_scal_hyd_base_EF::compute_nusselt(), Paroi_scal_hyd_base_VDF::compute_nusselt(), Paroi_scal_hyd_base_VEF::compute_nusselt(), equivalent_distance(), Loi_Paroi_Nu_Impose_VDF::imprimer_nusselt(), Paroi_TBLE_scal_VDF::imprimer_nusselt(), ParoiVEF_TBLE_scal::imprimer_nusselt(), ParoiVEF_TBLE_scal::init_lois_paroi(), Paroi_scal_hyd_base_EF::init_lois_paroi(), Paroi_scal_hyd_base_VDF::init_lois_paroi(), Paroi_scal_hyd_base_VEF::init_lois_paroi(), tab_equivalent_distance(), and tab_equivalent_distance_size().
tab_
DoubleTab Turbulence_paroi_scal_base::tab_ mutable protected
Referenced by Paroi_scal_hyd_base_EF::compute_nusselt(), Paroi_scal_hyd_base_VDF::compute_nusselt(), Paroi_scal_hyd_base_VEF::compute_nusselt(), Paroi_scal_hyd_base_EF::imprimer_nusselt(), Paroi_scal_hyd_base_VDF::imprimer_nusselt(), Paroi_scal_hyd_base_VEF::imprimer_nusselt(), imprimer_nusselt_mean_only(), Paroi_scal_hyd_base_EF::init_lois_paroi(), Paroi_scal_hyd_base_VDF::init_lois_paroi(), and Paroi_scal_hyd_base_VEF::init_lois_paroi().
nb_fields_
int Turbulence_paroi_scal_base::nb_fields_ = 6 protected
Referenced by Paroi_scal_hyd_base_EF::imprimer_nusselt(), Paroi_scal_hyd_base_VDF::imprimer_nusselt(), Paroi_scal_hyd_base_VEF::imprimer_nusselt(), imprimer_nusselt_mean_only(), imprimer_premiere_ligne_nusselt(), Paroi_scal_hyd_base_EF::init_lois_paroi(), Paroi_scal_hyd_base_VDF::init_lois_paroi(), and Paroi_scal_hyd_base_VEF::init_lois_paroi().
le_dom_dis_
TRUST_Ref< Domaine_VF *> Turbulence_paroi_scal_base::le_dom_dis_ protected
Referenced by Paroi_loi_WW_scal_VEF::associer(), Paroi_scal_hyd_base_EF::associer(), Paroi_scal_hyd_base_VDF::associer(), Paroi_scal_hyd_base_VEF::associer(), Paroi_std_scal_hyd_EF::calculer_scal(), Loi_Paroi_Nu_Impose_VDF::calculer_scal(), Paroi_loi_WW_scal_VDF::calculer_scal(), Paroi_ODVM_scal_VDF::calculer_scal(), Paroi_std_scal_hyd_VDF::calculer_scal(), Paroi_TBLE_scal_VDF::calculer_scal(), Loi_Paroi_Nu_Impose_VEF::calculer_scal(), Paroi_loi_WW_scal_VEF::calculer_scal(), Paroi_scal_analytique_VEF::calculer_scal(), Paroi_std_scal_hyd_VEF::calculer_scal(), ParoiVEF_TBLE_scal::calculer_scal(), Paroi_scal_hyd_base_EF::compute_nusselt(), Paroi_scal_hyd_base_VDF::compute_nusselt(), Paroi_scal_hyd_base_VEF::compute_nusselt(), Paroi_scal_hyd_base_EF::equivalent_distance_name(), Paroi_scal_hyd_base_VEF::equivalent_distance_name(), Paroi_scal_hyd_base_VDF::equivalent_distance_name(), Loi_Paroi_Nu_Impose_VDF::imprimer_nusselt(), Loi_Paroi_Nu_Impose_VEF::imprimer_nusselt(), Paroi_scal_hyd_base_EF::imprimer_nusselt(), Paroi_scal_hyd_base_VDF::imprimer_nusselt(), Paroi_scal_hyd_base_VEF::imprimer_nusselt(), imprimer_nusselt_mean_only(), imprimer_premiere_ligne_nusselt(), Paroi_loi_WW_scal_VDF::init_lois_paroi(), Paroi_ODVM_scal_VDF::init_lois_paroi(), Paroi_TBLE_scal_VDF::init_lois_paroi(), ParoiVEF_TBLE_scal::init_lois_paroi(), Paroi_scal_hyd_base_EF::init_lois_paroi(), Paroi_scal_hyd_base_VDF::init_lois_paroi(), Paroi_scal_hyd_base_VEF::init_lois_paroi(), Paroi_TBLE_scal_VDF::reprendre(), ParoiVEF_TBLE_scal::reprendre(), Paroi_TBLE_scal_VDF::sauvegarder(), and ParoiVEF_TBLE_scal::sauvegarder().
le_dom_Cl_dis_
TRUST_Ref< Domaine_Cl_dis_base *> Turbulence_paroi_scal_base::le_dom_Cl_dis_ protected
Referenced by Paroi_loi_WW_scal_VEF::associer(), Paroi_scal_hyd_base_EF::associer(), Paroi_scal_hyd_base_VDF::associer(), Paroi_scal_hyd_base_VEF::associer(), Paroi_std_scal_hyd_EF::calculer_scal(), Loi_Paroi_Nu_Impose_VDF::calculer_scal(), Paroi_loi_WW_scal_VDF::calculer_scal(), Paroi_ODVM_scal_VDF::calculer_scal(), Paroi_std_scal_hyd_VDF::calculer_scal(), Paroi_TBLE_scal_VDF::calculer_scal(), Loi_Paroi_Nu_Impose_VEF::calculer_scal(), Paroi_loi_WW_scal_VEF::calculer_scal(), Paroi_scal_analytique_VEF::calculer_scal(), Paroi_std_scal_hyd_VEF::calculer_scal(), ParoiVEF_TBLE_scal::calculer_scal(), Paroi_scal_hyd_base_EF::compute_nusselt(), Paroi_scal_hyd_base_VDF::compute_nusselt(), Paroi_scal_hyd_base_VEF::compute_nusselt(), Loi_Paroi_Nu_Impose_VDF::imprimer_nusselt(), Loi_Paroi_Nu_Impose_VEF::imprimer_nusselt(), Paroi_scal_hyd_base_EF::imprimer_nusselt(), Paroi_scal_hyd_base_VDF::imprimer_nusselt(), Paroi_scal_hyd_base_VEF::imprimer_nusselt(), imprimer_nusselt_mean_only(), imprimer_premiere_ligne_nusselt(), Paroi_ODVM_scal_VDF::init_lois_paroi(), Paroi_TBLE_scal_VDF::init_lois_paroi(), ParoiVEF_TBLE_scal::init_lois_paroi(), Paroi_scal_hyd_base_EF::init_lois_paroi(), Paroi_scal_hyd_base_VDF::init_lois_paroi(), Paroi_scal_hyd_base_VEF::init_lois_paroi(), Paroi_TBLE_scal_VDF::reprendre(), ParoiVEF_TBLE_scal::reprendre(), Paroi_TBLE_scal_VDF::sauvegarder(), and ParoiVEF_TBLE_scal::sauvegarder().