TrioCFD: IJK_Thermal_base Class Reference
IJK_Thermal_base Class Reference abstract
#include <IJK_Thermal_base.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Public Types inherited from Champs_compris_IJK_interface
using FieldInfo_t = std::tuple< Motcle, Entity, Nature_du_champ, bool >
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Member Typedef Documentation
FieldInfo_t
using IJK_Thermal_base::FieldInfo_t = Champs_compris_IJK_interface::FieldInfo_t
Member Enumeration Documentation
THERMAL_TYPE
enum IJK_Thermal_base::THERMAL_TYPE protected
Enumerator
SUBRES
MSUBRES
ONEFLUID
ONEFLUIDE
CUTCELL
Constructor & Destructor Documentation
IJK_Thermal_base()
IJK_Thermal_base::IJK_Thermal_base ()
References d_temperature_, div_coeff_grad_T_volume_, lata_suffix_, RK3_F_temperature_, temperature_, and thermal_words_.
~IJK_Thermal_base()
IJK_Thermal_base::~IJK_Thermal_base () override
Member Function Documentation
info()
const Type_info * IJK_Thermal_base::info () static
get_info()
const Type_info * IJK_Thermal_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
Reimplemented in IJK_Thermal_cut_cell, IJK_Thermal_Multiple_Subresolutions, IJK_Thermal_Onefluid, and IJK_Thermal_Subresolution.
self_cast() [1/2]
IJK_Thermal_base & IJK_Thermal_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const IJK_Thermal_base & IJK_Thermal_base::self_cast (const Objet_U & r) static
printOn()
Sortie & IJK_Thermal_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
Reimplemented in IJK_Thermal_cut_cell, IJK_Thermal_Multiple_Subresolutions, IJK_Thermal_Onefluid, and IJK_Thermal_Subresolution.
References avoid_gfm_parallel_calls_, boundary_conditions_, calculate_local_energy_, compute_eulerian_compo_, conv_temperature_negligible_, debug_, diff_temperature_negligible_, disable_relative_velocity_energy_balance_, expression_T_ana_, fichier_reprise_temperature_, Boundary_Conditions_Thermique::get_bctype_k_max(), Boundary_Conditions_Thermique::get_bctype_k_min(), Boundary_Conditions_Thermique::get_flux_kmax(), Boundary_Conditions_Thermique::get_flux_kmin(), Boundary_Conditions_Thermique::get_temperature_kmax(), Boundary_Conditions_Thermique::get_temperature_kmin(), gfm_smooth_factor_, ghost_fluid_, kl_, kv_, latastep_reprise_, n_iter_distance_, nb_diam_upstream_, Boundary_Conditions_Thermique::Paroi_Flux_impose, Boundary_Conditions_Thermique::Paroi_Temperature_imposee, Boundary_Conditions_Thermique::Perio, Objet_U::printOn(), rank_reprise_temperature_, side_temperature_, smooth_grad_T_elem_, smoothing_numbers_, smoothing_remove_normal_compo_, smoothing_use_unique_phase_, spherical_exact_, stencil_side_, store_flux_operators_for_energy_balance_, T0l_, T0v_, temperature_convection_op_, temperature_diffusion_op_, timestep_reprise_temperature_, type_T_source_, upstream_temperature_, use_bubbles_velocities_from_barycentres_, use_bubbles_velocities_from_interface_, and wall_flux_.
Referenced by IJK_Thermal_cut_cell::printOn(), IJK_Thermal_Onefluid::printOn(), IJK_Thermal_Subresolution::printOn(), and readOn().
readOn()
Entree & IJK_Thermal_base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
Reimplemented in IJK_Thermal_cut_cell, IJK_Thermal_Multiple_Subresolutions, IJK_Thermal_Onefluid, and IJK_Thermal_Subresolution.
References Param::lire_avec_accolades(), printOn(), Objet_U::que_suis_je(), and set_param().
Referenced by IJK_Thermal_cut_cell::readOn(), IJK_Thermal_Onefluid::readOn(), and IJK_Thermal_Subresolution::readOn().
milieu() [1/2]
const Milieu_base & IJK_Thermal_base::milieu () const
References TRUST_Ref< _CLASSE_ >::est_nul(), Process::exit(), le_fluide_, TRUST_Ref< _CLASSE_ >::le_nom(), ref_ijk_ft_, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by milieu_ijk().
milieu() [2/2]
Milieu_base & IJK_Thermal_base::milieu ()
References TRUST_Ref< _CLASSE_ >::est_nul(), Process::exit(), le_fluide_, TRUST_Ref< _CLASSE_ >::le_nom(), ref_ijk_ft_, and TRUST_Ref< _CLASSE_ >::valeur().
associer_milieu_base()
void IJK_Thermal_base::associer_milieu_base (const Milieu_base & un_milieu)
References cp_liquid_, cp_vapour_, Process::exit(), Fluide_Diphasique_IJK::get_cp_liquid(), Fluide_Diphasique_IJK::get_cp_vapour(), Fluide_Diphasique_IJK::get_lambda_liquid(), Fluide_Diphasique_IJK::get_lambda_vapour(), lambda_liquid_, lambda_vapour_, le_fluide_, milieu_ijk(), and rang_.
milieu_ijk() [1/2]
Fluide_Diphasique_IJK & IJK_Thermal_base::milieu_ijk () inline
References milieu().
Referenced by associer_milieu_base().
milieu_ijk() [2/2]
const Fluide_Diphasique_IJK & IJK_Thermal_base::milieu_ijk () const inline
References milieu().
set_param()
void IJK_Thermal_base::set_param (Param & param) virtual
Reimplemented in IJK_Thermal_cut_cell, IJK_Thermal_Multiple_Subresolutions, IJK_Thermal_Onefluid, and IJK_Thermal_Subresolution.
References Param::ajouter(), Param::ajouter_flag(), avoid_gfm_parallel_calls_, boundary_conditions_, calculate_local_energy_, compute_eulerian_compo_, conserv_energy_global_, conv_temperature_negligible_, debug_, Param::dictionnaire(), diff_temperature_negligible_, disable_relative_velocity_energy_balance_, expression_source_temperature_, expression_T_ana_, expression_T_init_, fichier_reprise_temperature_, fo_, gfm_smooth_factor_, gfm_vapour_liquid_vapour_, ghost_fluid_, kl_, kv_, lambda_variable_, latastep_reprise_ini_, n_iter_distance_, nb_diam_upstream_, rank_reprise_temperature_, Param::REQUIRED, side_temperature_, smooth_grad_T_elem_, smoothing_numbers_, smoothing_remove_normal_compo_, smoothing_use_unique_phase_, spherical_exact_, stencil_side_, store_flux_operators_for_energy_balance_, T0l_, T0v_, temperature_convection_op_, temperature_diffusion_op_, timestep_reprise_temperature_, type_T_source_, type_temperature_convection_form_, upstream_temperature_, use_bubbles_velocities_from_barycentres_, use_bubbles_velocities_from_interface_, and wall_flux_.
Referenced by readOn(), IJK_Thermal_cut_cell::set_param(), IJK_Thermal_Onefluid::set_param(), and IJK_Thermal_Subresolution::set_param().
initialize()
void IJK_Thermal_base::initialize (const Domaine_IJK & splitting, const int idx) virtual
Reimplemented in IJK_Thermal_cut_cell, IJK_Thermal_Multiple_Subresolutions, IJK_Thermal_Onefluid, and IJK_Thermal_Subresolution.
References Champs_compris_T< FIELD_TYPE >::ajoute_champ(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::allocate(), bubbles_barycentre_, bubbles_barycentres_new_, bubbles_barycentres_old_, calculate_local_energy_, calulate_grad_T_, champs_compris_, compute_cell_volume(), compute_curvature_, compute_distance_, compute_eulerian_compo_, compute_grad_T_elem_, compute_grad_T_interface_, compute_hess_cross_T_elem_, compute_hess_diag_T_elem_, compute_hess_T_elem_, compute_min_cell_delta(), compute_rising_velocities_, compute_temperature_init(), Motcles::contient_(), conv_temperature_negligible_, corrige_flux_, d_source_Tl_, d_source_Tv_, d_temperature_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::data(), diff_temperature_negligible_, Option_IJK::DISABLE_DIPHASIQUE, div_coeff_grad_T_, div_coeff_grad_T_raw_, div_coeff_grad_T_volume_, div_rho_cp_T_, dummy_double_field_, dummy_double_vect_, dummy_int_field_, dummy_int_vect_, ecart_source_t_ana_, ecart_t_ana_, ecart_t_ana_rel_, IJK_Field_vector< T, N >::echange_espace_virtuel(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel(), Domaine_IJK::ELEM, eulerian_compo_connex_from_interface_ft_, eulerian_compo_connex_from_interface_ghost_ft_, eulerian_compo_connex_from_interface_ghost_int_ns_, eulerian_compo_connex_from_interface_ghost_ns_, eulerian_compo_connex_from_interface_int_ns_, eulerian_compo_connex_from_interface_ns_, eulerian_compo_connex_ft_, eulerian_compo_connex_ghost_ft_, eulerian_compo_connex_ghost_ns_, eulerian_compo_connex_ns_, eulerian_curvature_ft_, eulerian_curvature_ns_, eulerian_distance_ft_, eulerian_distance_ns_, eulerian_facets_barycentre_ft_, eulerian_facets_barycentre_ns_, eulerian_grad_T_interface_ft_, eulerian_grad_T_interface_ns_, eulerian_interfacial_area_ft_, eulerian_interfacial_area_ns_, eulerian_normal_vectors_ft_, eulerian_normal_vectors_ns_, eulerian_normal_vectors_ns_normed_, eulerian_rising_velocities_, Process::exit(), expression_T_init_, fichier_reprise_temperature_, fill_rising_velocities_, IJK_Ghost_Fluid_Fields::get_eulerian_curvature_ft(), IJK_Ghost_Fluid_Fields::get_eulerian_curvature_ns(), IJK_Ghost_Fluid_Fields::get_eulerian_distance_ft(), IJK_Ghost_Fluid_Fields::get_eulerian_distance_ns(), IJK_Ghost_Fluid_Fields::get_eulerian_facets_barycentre_ft(), IJK_Ghost_Fluid_Fields::get_eulerian_facets_barycentre_ns(), IJK_Ghost_Fluid_Fields::get_eulerian_interfacial_area_ft(), IJK_Ghost_Fluid_Fields::get_eulerian_interfacial_area_ns(), IJK_Ghost_Fluid_Fields::get_eulerian_normal_vectors_ft(), IJK_Ghost_Fluid_Fields::get_eulerian_normal_vectors_ns(), IJK_Ghost_Fluid_Fields::get_eulerian_normal_vectors_ns_normed(), get_field_name_with_rank(), gfm_vapour_liquid_vapour_, gfm_vapour_mixed_only_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost(), ghost_cells_, ghost_fluid_, ghost_fluid_fields_, grad_T_, grad_T_elem_, grad_T_elem_smooth_, grad_T_elem_tangential_, hess_cross_T_elem_, hess_diag_T_elem_, Operateur_IJK_elem_conv::initialize(), Operateur_IJK_elem_diff::initialize(), Operateur_IJK_elem_conv_base_double::initialize(), Operateur_IJK_elem_diff_base_double::initialize(), latastep_reprise_, latastep_reprise_ini_, liquid_velocity_, lire_temperature(), liste_post_instantanes_, needs_op_unform_, TRUST_Ref< _CLASSE_ >::non_nul(), rang_, ref_ijk_ft_, ref_ijk_ft_post_, rho_cp_, rho_cp_convection_op_, rho_cp_post_, rho_cp_T_, rho_cp_u_T_convective_raw_, rising_vectors_, rising_vectors_from_barycentres_, rising_velocities_, rising_velocities_from_barycentres_, rising_velocity_overall_, RK3_F_temperature_, TRUST_Vector< _CLASSE_ >::size(), smooth_grad_T_elem_, source_temperature_, source_temperature_ana_, source_temperature_l_, source_temperature_v_, spherical_approx_, spherical_exact_, storage_, store_flux_operators_for_energy_balance_, temperature_, temperature_adim_bulles_, temperature_adimensionnelle_theta_, temperature_ana_, temperature_convection_op_, temperature_diffusion_op_, temperature_for_ini_per_bubble_, temperature_ft_, temperature_gaussian_filtered_, temperature_grad_flux_op_quick_, temperature_grad_op_centre_, temperature_hess_flux_op_centre_, temperature_hess_op_centre_, temperature_physique_T_, tmp_smoothing_field_, type_T_source_, type_temperature_convection_form_, Objet_U_ptr::typer(), Operateur_IJK_elem_conv::typer_convection_op(), Operateur_IJK_elem_diff::typer_diffusion_op(), u_T_convective_, u_T_convective_volume_, and wall_flux_.
Referenced by IJK_Thermal_cut_cell::initialize(), IJK_Thermal_Onefluid::initialize(), and IJK_Thermal_Subresolution::initialize().
initialize_switch()
void IJK_Thermal_base::initialize_switch (const Domaine_IJK & splitting, const int idx) virtual
References Champs_compris_T< FIELD_TYPE >::ajoute_champ(), champs_compris_, Domaine_IJK::ELEM, Process::exit(), fichier_reprise_temperature_, get_field_name_with_rank(), lire_temperature(), and temperature_.
update_thermal_properties()
void IJK_Thermal_base::update_thermal_properties () virtual
Reimplemented in IJK_Thermal_cut_cell, IJK_Thermal_Multiple_Subresolutions, IJK_Thermal_Onefluid, and IJK_Thermal_Subresolution.
References calculate_local_energy_, compute_global_energy(), conserv_energy_global_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::data(), Option_IJK::DISABLE_DIPHASIQUE, IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel(), get_rhocp_l(), get_rhocp_v(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), rang_, ref_ijk_ft_, rho_cp_, rho_cp_post_, rho_cp_T_, temperature_, and type_temperature_convection_form_.
Referenced by IJK_Thermal_Onefluid::update_thermal_properties(), and IJK_Thermal_Subresolution::update_thermal_properties().
compute_timestep()
double IJK_Thermal_base::compute_timestep (const double timestep, const double dxmin)
References cp_liquid_, cp_vapour_, diff_temperature_negligible_, Option_IJK::DISABLE_DIPHASIQUE, dt_fo_, fo_, lambda_liquid_, lambda_vapour_, and ref_ijk_ft_.
set_fichier_reprise()
void IJK_Thermal_base::set_fichier_reprise (const char * lataname)
References fichier_reprise_temperature_.
get_fichier_reprise()
const Nom & IJK_Thermal_base::get_fichier_reprise () const inline
References fichier_reprise_temperature_.
associer()
void IJK_Thermal_base::associer (const Probleme_FTD_IJK_base & ijk_ft)
References IJK_One_Dimensional_Subproblems_Interfaces_Fields::associer(), Postprocessing_IJK::get_liste_post_instantanes(), Probleme_FTD_IJK_base::get_post(), liste_post_instantanes_, ref_ijk_ft_, and thermal_local_subproblems_interfaces_fields_.
associer_post()
void IJK_Thermal_base::associer_post (const Postprocessing_IJK & ijk_ft_post)
References ref_ijk_ft_post_.
associer_switch()
void IJK_Thermal_base::associer_switch (const Switch_FT_double & ijk_ft_switch)
References ref_ijk_ft_switch_.
has_champ() [1/2]
bool IJK_Thermal_base::has_champ (const Motcle & nom) const override virtual
Implements Champs_compris_IJK_interface.
References champs_compris_, Noms::contient_(), Champs_compris_T< FIELD_TYPE >::has_champ(), Champs_compris_IJK::has_champ_vectoriel(), Champs_compris_IJK::liste_noms_compris(), and Champs_compris_IJK::liste_noms_compris_vectoriel().
has_champ() [2/2]
bool IJK_Thermal_base::has_champ (const Motcle & nom, TRUST_Ref< Champ_base * > & ref_champ) const inline
has_champ_vectoriel()
bool IJK_Thermal_base::has_champ_vectoriel (const Motcle & nom) const inline override virtual
Implements Champs_compris_IJK_interface.
get_IJK_field()
const IJK_Field_double & IJK_Thermal_base::get_IJK_field (const Motcle & nom) override virtual
Implements Champs_compris_IJK_interface.
References calculer_ecart_T_ana(), champs_compris_, expression_T_ana_, Champs_compris_T< FIELD_TYPE >::get_champ(), get_field_name_with_rank(), Champs_compris_T< FIELD_TYPE >::has_champ(), rang_, ref_ijk_ft_, and temperature_ana_.
get_IJK_field_vector()
const IJK_Field_vector3_double & IJK_Thermal_base::get_IJK_field_vector (const Motcle & nom) override virtual
Implements Champs_compris_IJK_interface.
References champs_compris_, Noms::contient_(), Champs_compris_IJK::get_champ_vectoriel(), and Champs_compris_IJK::liste_noms_compris_vectoriel().
Fill_postprocessable_fields()
void IJK_Thermal_base::Fill_postprocessable_fields (std::vector< FieldInfo_t > & chps) static
get_noms_champs_postraitables()
void IJK_Thermal_base::get_noms_champs_postraitables (Noms & noms, Option opt = NONE) const
References TRUST_Vector< _CLASSE_ >::add(), champs_compris_, Champs_compris_IJK::liste_noms_compris(), and Champs_compris_IJK::liste_noms_compris_vectoriel().
get_field_name_with_rank()
Nom IJK_Thermal_base::get_field_name_with_rank (Nom basename) const
References rang_.
Referenced by get_IJK_field(), initialize(), IJK_Thermal_Onefluid::initialize(), and initialize_switch().
associer_interface_intersections()
void IJK_Thermal_base::associer_interface_intersections (const Intersection_Interface_ijk_cell & intersection_ijk_cell, const Intersection_Interface_ijk_face & intersection_ijk_face)
References ref_intersection_ijk_cell_, and ref_intersection_ijk_face_.
associer_ghost_fluid_fields()
void IJK_Thermal_base::associer_ghost_fluid_fields (const IJK_Ghost_Fluid_Fields & ghost_fluid_fields)
References ghost_fluid_fields_.
retrieve_ghost_fluid_params()
void IJK_Thermal_base::retrieve_ghost_fluid_params (int & compute_distance, int & compute_curvature, int & n_iter_distance, int & avoid_gfm_parallel_calls)
References avoid_gfm_parallel_calls_, compute_curvature_, compute_distance_, and n_iter_distance_.
get_boundary_fluxes()
void IJK_Thermal_base::get_boundary_fluxes (IJK_Field_local_double & boundary_flux_kmin, IJK_Field_local_double & boundary_flux_kmax)
References boundary_flux_kmax_, and boundary_flux_kmin_.
euler_time_step()
void IJK_Thermal_base::euler_time_step (const double timestep) virtual
Reimplemented in IJK_Thermal_cut_cell.
References Statistiques::begin_count(), calculer_dT(), compute_global_energy(), d_temperature_, debug_, Statistiques::end_count(), Statistiques::new_counter(), post_process_after_temperature_increment(), rang_, ref_ijk_ft_, source_callback(), and temperature_.
rk3_sub_step()
void IJK_Thermal_base::rk3_sub_step (const int rk_step, const double total_timestep, const double time) virtual
Reimplemented in IJK_Thermal_cut_cell.
References calculer_dT(), compute_global_energy(), d_temperature_, rang_, ref_ijk_ft_, RK3_F_temperature_, source_callback(), and temperature_.
sauvegarder_temperature()
void IJK_Thermal_base::sauvegarder_temperature (Nom & lata_name, int idx, const int & stop = 0) virtual
Reimplemented in IJK_Thermal_cut_cell.
References fichier_reprise_temperature_, latastep_reprise_, latastep_reprise_ini_, rank_reprise_temperature_, ref_ijk_ft_, temperature_, and timestep_reprise_temperature_.
euler_rustine_step()
virtual void IJK_Thermal_base::euler_rustine_step (const double timestep) inline virtual
Reimplemented in IJK_Thermal_Onefluid.
rk3_rustine_sub_step()
virtual void IJK_Thermal_base::rk3_rustine_sub_step (const int rk_step, const double total_timestep, const double fractionnal_timestep, const double time) inline virtual
Reimplemented in IJK_Thermal_Onefluid.
compute_global_energy() [1/2]
double IJK_Thermal_base::compute_global_energy (const IJK_Field_double & temperature)
References Domaine_IJK::ELEM, Domaine_IJK::get_constant_delta(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_domaine(), Domaine_IJK::get_nb_items_global(), get_rhocp_l(), get_rhocp_v(), Process::mp_sum(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), and ref_ijk_ft_.
compute_global_energy() [2/2]
virtual double IJK_Thermal_base::compute_global_energy () inline virtual
Reimplemented in IJK_Thermal_cut_cell.
References compute_global_energy(), and temperature_.
Referenced by calculer_dT(), compute_global_energy(), IJK_Thermal_Onefluid::euler_rustine_step(), euler_time_step(), IJK_Thermal_Onefluid::initialize(), IJK_Thermal_Onefluid::rk3_rustine_sub_step(), rk3_sub_step(), and update_thermal_properties().
calculer_k_pour_bord()
int IJK_Thermal_base::calculer_k_pour_bord (const IJK_Field_double & temperature, const bool bord_kmax)
References Domaine_IJK::ELEM, IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_domaine(), Domaine_IJK::get_nb_items_global(), Domaine_IJK::get_offset_local(), and IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk().
Referenced by calculer_flux_thermique_bord(), and imposer_flux_thermique_bord().
calculer_flux_thermique_bord()
int IJK_Thermal_base::calculer_flux_thermique_bord (const IJK_Field_double & temperature, const double lambda_de_t_paroi, const double T_paroi_impose, IJK_Field_local_double & flux_bord, const bool bord_kmax)
References IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::allocate(), calculer_k_pour_bord(), Domaine_IJK::get_constant_delta(), Domaine_IJK::get_delta(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_domaine(), Domaine_IJK::get_offset_local(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), and IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj().
Referenced by IJK_Thermal_cut_cell::add_temperature_diffusion(), and compute_boundary_conditions_thermal().
imposer_flux_thermique_bord()
int IJK_Thermal_base::imposer_flux_thermique_bord (const IJK_Field_double & temperature, const double flux_paroi_impose, IJK_Field_local_double & flux_bord, const bool bord_kmax)
References IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::allocate(), calculer_k_pour_bord(), Domaine_IJK::get_constant_delta(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_domaine(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), and IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj().
Referenced by IJK_Thermal_cut_cell::add_temperature_diffusion(), and compute_boundary_conditions_thermal().
get_first_step_thermals_post()
virtual int IJK_Thermal_base::get_first_step_thermals_post () inline virtual
Reimplemented in IJK_Thermal_Subresolution.
set_latastep_reprise()
void IJK_Thermal_base::set_latastep_reprise (const int latastep) inline
References latastep_reprise_.
get_latastep_reprise()
const int & IJK_Thermal_base::get_latastep_reprise () const inline
References latastep_reprise_.
get_latastep_reprise_ini()
const int & IJK_Thermal_base::get_latastep_reprise_ini () const inline
References latastep_reprise_.
get_rhocp_l()
double IJK_Thermal_base::get_rhocp_l () const
References ref_ijk_ft_.
Referenced by compute_global_energy(), compute_temperature_convective_fluxes(), IJK_Thermal_cut_cell::perform_thermal_step(), and update_thermal_properties().
get_rhocp_v()
double IJK_Thermal_base::get_rhocp_v () const
References ref_ijk_ft_.
Referenced by compute_global_energy(), IJK_Thermal_cut_cell::perform_thermal_step(), and update_thermal_properties().
get_rank()
const int & IJK_Thermal_base::get_rank () const inline
References rang_.
Referenced by posttraiter_champs_instantanes_thermal().
get_temperature()
const std::shared_ptr< IJK_Field_double > & IJK_Thermal_base::get_temperature () const inline
References temperature_.
Referenced by ecrire_statistiques_bulles(), posttraiter_champs_instantanes_thermal(), and posttraiter_champs_instantanes_thermal_interface_ref().
get_temperature_before_extrapolation()
const IJK_Field_double & IJK_Thermal_base::get_temperature_before_extrapolation () const inline
References temperature_before_extrapolation_.
Referenced by posttraiter_champs_instantanes_thermal().
get_temperature_ft()
IJK_Field_double & IJK_Thermal_base::get_temperature_ft () inline
References temperature_ft_.
Referenced by ecrire_statistiques_bulles(), posttraiter_champs_instantanes_thermal(), and posttraiter_champs_instantanes_thermal_interface_ref().
get_grad_T()
const IJK_Field_vector3_double & IJK_Thermal_base::get_grad_T () const inline
References grad_T_.
Referenced by posttraiter_champs_instantanes_thermal().
set_temperature()
IJK_Field_double & IJK_Thermal_base::set_temperature () inline
References temperature_.
get_temperature_ana()
const IJK_Field_double & IJK_Thermal_base::get_temperature_ana () const inline
References temperature_ana_.
Referenced by posttraiter_champs_instantanes_thermal().
get_ecart_t_ana()
const IJK_Field_double & IJK_Thermal_base::get_ecart_t_ana () const inline
References ecart_t_ana_.
Referenced by posttraiter_champs_instantanes_thermal().
get_ecart_t_ana_rel()
const IJK_Field_double & IJK_Thermal_base::get_ecart_t_ana_rel () const inline
References ecart_t_ana_rel_.
Referenced by posttraiter_champs_instantanes_thermal().
get_div_lambda_grad_T()
const IJK_Field_double & IJK_Thermal_base::get_div_lambda_grad_T () const inline
References div_coeff_grad_T_.
Referenced by posttraiter_champs_instantanes_thermal().
get_div_lambda_grad_T_volume()
const std::shared_ptr< IJK_Field_double > & IJK_Thermal_base::get_div_lambda_grad_T_volume () const inline
References div_coeff_grad_T_volume_.
Referenced by posttraiter_champs_instantanes_thermal().
get_u_T_convective()
const IJK_Field_double & IJK_Thermal_base::get_u_T_convective () const inline
References u_T_convective_.
Referenced by posttraiter_champs_instantanes_thermal().
get_u_T_convective_volume()
const IJK_Field_double & IJK_Thermal_base::get_u_T_convective_volume () const inline
References u_T_convective_volume_.
Referenced by posttraiter_champs_instantanes_thermal().
get_eulerian_distance_ft()
const IJK_Field_double & IJK_Thermal_base::get_eulerian_distance_ft () const inline
References IJK_Ghost_Fluid_Fields::get_eulerian_distance_ft(), and ghost_fluid_fields_.
Referenced by posttraiter_champs_instantanes_thermal().
get_eulerian_curvature_ft()
const IJK_Field_double & IJK_Thermal_base::get_eulerian_curvature_ft () const inline
References IJK_Ghost_Fluid_Fields::get_eulerian_curvature_ft(), and ghost_fluid_fields_.
Referenced by posttraiter_champs_instantanes_thermal().
get_interfacial_area_ft()
const IJK_Field_double & IJK_Thermal_base::get_interfacial_area_ft () const inline
References IJK_Ghost_Fluid_Fields::get_eulerian_interfacial_area_ft(), and ghost_fluid_fields_.
Referenced by posttraiter_champs_instantanes_thermal().
get_grad_T_interface_ft()
const IJK_Field_double & IJK_Thermal_base::get_grad_T_interface_ft () const inline
References eulerian_grad_T_interface_ft_.
Referenced by posttraiter_champs_instantanes_thermal().
get_eulerian_compo_connex_ft()
const IJK_Field_double & IJK_Thermal_base::get_eulerian_compo_connex_ft () const
References dummy_double_field_, eulerian_compo_connex_ft_, and ref_ijk_ft_.
Referenced by posttraiter_champs_instantanes_thermal().
get_eulerian_compo_connex_ghost_ft()
const IJK_Field_double & IJK_Thermal_base::get_eulerian_compo_connex_ghost_ft () const
References dummy_double_field_, eulerian_compo_connex_ghost_ft_, and ref_ijk_ft_.
Referenced by posttraiter_champs_instantanes_thermal().
get_eulerian_compo_connex_from_interface_ft()
const IJK_Field_double & IJK_Thermal_base::get_eulerian_compo_connex_from_interface_ft () const
References dummy_double_field_, eulerian_compo_connex_from_interface_ft_, and ref_ijk_ft_.
Referenced by posttraiter_champs_instantanes_thermal().
get_eulerian_compo_connex_from_interface_ghost_ft()
const IJK_Field_double & IJK_Thermal_base::get_eulerian_compo_connex_from_interface_ghost_ft () const
References dummy_double_field_, eulerian_compo_connex_from_interface_ghost_ft_, and ref_ijk_ft_.
Referenced by posttraiter_champs_instantanes_thermal().
get_eulerian_compo_connex_ns()
const IJK_Field_double & IJK_Thermal_base::get_eulerian_compo_connex_ns () const
References dummy_double_field_, eulerian_compo_connex_ns_, and ref_ijk_ft_.
Referenced by posttraiter_champs_instantanes_thermal().
get_eulerian_compo_connex_ghost_ns()
const IJK_Field_double & IJK_Thermal_base::get_eulerian_compo_connex_ghost_ns () const
References dummy_double_field_, eulerian_compo_connex_ghost_ns_, and ref_ijk_ft_.
Referenced by posttraiter_champs_instantanes_thermal().
get_eulerian_compo_connex_from_interface_ns()
const IJK_Field_double & IJK_Thermal_base::get_eulerian_compo_connex_from_interface_ns () const
References dummy_double_field_, eulerian_compo_connex_from_interface_ns_, and ref_ijk_ft_.
Referenced by posttraiter_champs_instantanes_thermal().
get_eulerian_compo_connex_from_interface_ghost_ns()
const IJK_Field_double & IJK_Thermal_base::get_eulerian_compo_connex_from_interface_ghost_ns () const
References dummy_double_field_, eulerian_compo_connex_from_interface_ghost_ns_, and ref_ijk_ft_.
Referenced by posttraiter_champs_instantanes_thermal().
get_eulerian_compo_connex_int_from_interface_ns()
const IJK_Field_int & IJK_Thermal_base::get_eulerian_compo_connex_int_from_interface_ns () const
References dummy_int_field_, eulerian_compo_connex_from_interface_int_ns_, and ref_ijk_ft_.
Referenced by posttraiter_champs_instantanes_thermal().
get_eulerian_compo_connex_int_from_interface_ghost_ns()
const IJK_Field_int & IJK_Thermal_base::get_eulerian_compo_connex_int_from_interface_ghost_ns () const
References dummy_int_field_, eulerian_compo_connex_from_interface_ghost_int_ns_, and ref_ijk_ft_.
Referenced by posttraiter_champs_instantanes_thermal().
get_eulerian_distance_ns()
const IJK_Field_double & IJK_Thermal_base::get_eulerian_distance_ns () const inline
References IJK_Ghost_Fluid_Fields::get_eulerian_distance_ns(), and ghost_fluid_fields_.
Referenced by posttraiter_champs_instantanes_thermal().
get_eulerian_curvature_ns()
const IJK_Field_double & IJK_Thermal_base::get_eulerian_curvature_ns () const inline
References IJK_Ghost_Fluid_Fields::get_eulerian_curvature_ns(), and ghost_fluid_fields_.
Referenced by posttraiter_champs_instantanes_thermal().
get_interfacial_area_ns()
const IJK_Field_double & IJK_Thermal_base::get_interfacial_area_ns () const inline
References IJK_Ghost_Fluid_Fields::get_eulerian_interfacial_area_ns(), and ghost_fluid_fields_.
Referenced by posttraiter_champs_instantanes_thermal().
get_grad_T_interface_ns()
const IJK_Field_double & IJK_Thermal_base::get_grad_T_interface_ns () const inline
References eulerian_grad_T_interface_ns_.
Referenced by posttraiter_champs_instantanes_thermal().
get_eulerian_rising_velocities()
const IJK_Field_double & IJK_Thermal_base::get_eulerian_rising_velocities () const inline
References eulerian_rising_velocities_.
Referenced by posttraiter_champs_instantanes_thermal().
get_temperature_adim_bulles()
const IJK_Field_double & IJK_Thermal_base::get_temperature_adim_bulles () const inline
References temperature_adim_bulles_.
get_temperature_adim_theta()
const IJK_Field_double & IJK_Thermal_base::get_temperature_adim_theta () const inline
References temperature_adimensionnelle_theta_.
get_gradient_temperature()
const IJK_Field_vector3_double & IJK_Thermal_base::get_gradient_temperature () const inline
References grad_T_.
get_gradient_temperature_elem()
const IJK_Field_vector3_double & IJK_Thermal_base::get_gradient_temperature_elem () const inline
References grad_T_elem_.
Referenced by posttraiter_champs_instantanes_thermal().
get_gradient_temperature_elem_smooth()
const IJK_Field_vector3_double & IJK_Thermal_base::get_gradient_temperature_elem_smooth () const inline
References dummy_double_vect_, grad_T_elem_smooth_, and smooth_grad_T_elem_.
Referenced by posttraiter_champs_instantanes_thermal().
get_tangential_gradient_temperature_elem_smooth()
const IJK_Field_vector3_double & IJK_Thermal_base::get_tangential_gradient_temperature_elem_smooth () const inline
References dummy_double_vect_, grad_T_elem_tangential_, and smooth_grad_T_elem_.
Referenced by posttraiter_champs_instantanes_thermal().
get_temperature_elem_smooth()
const IJK_Field_double & IJK_Thermal_base::get_temperature_elem_smooth () const inline
References dummy_double_field_, smooth_grad_T_elem_, and temperature_gaussian_filtered_.
Referenced by posttraiter_champs_instantanes_thermal().
get_normal_vector_ns()
const IJK_Field_vector3_double & IJK_Thermal_base::get_normal_vector_ns () const inline
References IJK_Ghost_Fluid_Fields::get_eulerian_normal_vectors_ns(), and ghost_fluid_fields_.
Referenced by posttraiter_champs_instantanes_thermal().
get_normal_vector_ns_normed()
const IJK_Field_vector3_double & IJK_Thermal_base::get_normal_vector_ns_normed () const inline
References IJK_Ghost_Fluid_Fields::get_eulerian_normal_vectors_ns_normed(), and ghost_fluid_fields_.
Referenced by posttraiter_champs_instantanes_thermal().
get_normal_vector_ft()
const IJK_Field_vector3_double & IJK_Thermal_base::get_normal_vector_ft () const inline
References IJK_Ghost_Fluid_Fields::get_eulerian_normal_vectors_ft(), and ghost_fluid_fields_.
Referenced by posttraiter_champs_instantanes_thermal().
get_hessian_diag_temperature_elem()
const IJK_Field_vector3_double & IJK_Thermal_base::get_hessian_diag_temperature_elem () const inline
References hess_diag_T_elem_.
Referenced by posttraiter_champs_instantanes_thermal().
get_hessian_cross_temperature_elem()
const IJK_Field_vector3_double & IJK_Thermal_base::get_hessian_cross_temperature_elem () const inline
References hess_cross_T_elem_.
Referenced by posttraiter_champs_instantanes_thermal().
get_bary()
const IJK_Field_vector3_double & IJK_Thermal_base::get_bary () const inline
References IJK_Ghost_Fluid_Fields::get_eulerian_facets_barycentre_ft(), and ghost_fluid_fields_.
Referenced by posttraiter_champs_instantanes_thermal().
get_ghost_fluid_flag()
const int & IJK_Thermal_base::get_ghost_fluid_flag () const inline
References ghost_fluid_.
get_ghost_cells()
const int & IJK_Thermal_base::get_ghost_cells () const inline
References ghost_cells_.
get_debug()
const int & IJK_Thermal_base::get_debug () const inline
References debug_.
Referenced by posttraiter_champs_instantanes_thermal().
get_temperature_cell_neighbours_debug()
virtual const IJK_Field_double & IJK_Thermal_base::get_temperature_cell_neighbours_debug () const inline virtual
Reimplemented in IJK_Thermal_Subresolution.
References dummy_double_field_.
Referenced by posttraiter_champs_instantanes_thermal().
get_temperature_cell_neighbours()
virtual const IJK_Field_double & IJK_Thermal_base::get_temperature_cell_neighbours () const inline virtual
Reimplemented in IJK_Thermal_Subresolution.
References dummy_double_field_.
Referenced by posttraiter_champs_instantanes_thermal().
get_cell_neighbours_corrected()
virtual const IJK_Field_int & IJK_Thermal_base::get_cell_neighbours_corrected () const inline virtual
Reimplemented in IJK_Thermal_Subresolution.
References dummy_int_field_.
Referenced by posttraiter_champs_instantanes_thermal().
get_neighbours_temperature_colinearity_weighting()
virtual const IJK_Field_double & IJK_Thermal_base::get_neighbours_temperature_colinearity_weighting () const inline virtual
Reimplemented in IJK_Thermal_Subresolution.
References dummy_double_field_.
Referenced by posttraiter_champs_instantanes_thermal().
get_debug_lrs_cells()
virtual const IJK_Field_double & IJK_Thermal_base::get_debug_lrs_cells () const inline virtual
Reimplemented in IJK_Thermal_Subresolution.
References dummy_double_field_.
Referenced by posttraiter_champs_instantanes_thermal().
get_disable_post_processing_probes_out_files()
virtual int IJK_Thermal_base::get_disable_post_processing_probes_out_files () const inline virtual
Reimplemented in IJK_Thermal_Subresolution.
get_cell_faces_corrected_diffusive()
virtual const IJK_Field_vector3_double & IJK_Thermal_base::get_cell_faces_corrected_diffusive () const inline virtual
Reimplemented in IJK_Thermal_Subresolution.
References dummy_double_vect_.
Referenced by posttraiter_champs_instantanes_thermal().
get_cell_faces_corrected_convective()
virtual const IJK_Field_vector3_double & IJK_Thermal_base::get_cell_faces_corrected_convective () const inline virtual
Reimplemented in IJK_Thermal_Subresolution.
References dummy_double_vect_.
Referenced by posttraiter_champs_instantanes_thermal().
get_cell_faces_corrected_bool()
virtual const IJK_Field_vector3_int & IJK_Thermal_base::get_cell_faces_corrected_bool () const inline virtual
Reimplemented in IJK_Thermal_Subresolution.
References dummy_int_vect_.
Referenced by posttraiter_champs_instantanes_thermal().
get_cell_faces_neighbours_corrected_diag_bool()
virtual const IJK_Field_vector3_int & IJK_Thermal_base::get_cell_faces_neighbours_corrected_diag_bool () const inline virtual
Reimplemented in IJK_Thermal_Subresolution.
References dummy_int_vect_.
Referenced by posttraiter_champs_instantanes_thermal().
get_cell_faces_neighbours_corrected_all_bool()
virtual const IJK_Field_vector3_int & IJK_Thermal_base::get_cell_faces_neighbours_corrected_all_bool () const inline virtual
Reimplemented in IJK_Thermal_Subresolution.
References dummy_int_vect_.
Referenced by posttraiter_champs_instantanes_thermal().
get_cell_faces_neighbours_corrected_min_max_bool()
virtual const IJK_Field_vector3_int & IJK_Thermal_base::get_cell_faces_neighbours_corrected_min_max_bool () const inline virtual
Reimplemented in IJK_Thermal_Subresolution.
References dummy_int_vect_.
Referenced by posttraiter_champs_instantanes_thermal().
get_cell_faces_neighbours_corrected_velocity_temperature()
virtual const IJK_Field_vector3_double & IJK_Thermal_base::get_cell_faces_neighbours_corrected_velocity_temperature () const inline virtual
Reimplemented in IJK_Thermal_Subresolution.
References dummy_double_vect_.
Referenced by posttraiter_champs_instantanes_thermal().
get_cell_faces_neighbours_corrected_convective()
virtual const IJK_Field_vector3_double & IJK_Thermal_base::get_cell_faces_neighbours_corrected_convective () const inline virtual
Reimplemented in IJK_Thermal_Subresolution.
References dummy_double_vect_.
Referenced by posttraiter_champs_instantanes_thermal().
get_cell_faces_neighbours_corrected_convective_frame_of_ref()
virtual const IJK_Field_vector3_double & IJK_Thermal_base::get_cell_faces_neighbours_corrected_convective_frame_of_ref () const inline virtual
Reimplemented in IJK_Thermal_Subresolution.
References dummy_double_vect_.
Referenced by posttraiter_champs_instantanes_thermal().
get_cell_faces_neighbours_corrected_diffusive()
virtual const IJK_Field_vector3_double & IJK_Thermal_base::get_cell_faces_neighbours_corrected_diffusive () const inline virtual
Reimplemented in IJK_Thermal_Subresolution.
References dummy_double_vect_.
Referenced by posttraiter_champs_instantanes_thermal().
get_neighbours_faces_weighting_colinearity()
virtual const IJK_Field_vector3_double & IJK_Thermal_base::get_neighbours_faces_weighting_colinearity () const inline virtual
Reimplemented in IJK_Thermal_Subresolution.
References dummy_double_vect_.
Referenced by posttraiter_champs_instantanes_thermal().
get_cell_neighbours_corrected_trimmed()
virtual const IJK_Field_int & IJK_Thermal_base::get_cell_neighbours_corrected_trimmed () const inline virtual
Reimplemented in IJK_Thermal_Subresolution.
References dummy_int_field_.
Referenced by posttraiter_champs_instantanes_thermal().
get_probe_collision_debug_field()
virtual const IJK_Field_double & IJK_Thermal_base::get_probe_collision_debug_field () const inline virtual
Reimplemented in IJK_Thermal_Subresolution.
References dummy_double_field_.
Referenced by posttraiter_champs_instantanes_thermal().
get_rho_cp_u_T_convective_fluxes()
const IJK_Field_vector3_double & IJK_Thermal_base::get_rho_cp_u_T_convective_fluxes () const inline
References dummy_double_vect_, rho_cp_u_T_convective_raw_, and store_flux_operators_for_energy_balance_.
Referenced by posttraiter_champs_instantanes_thermal().
get_div_coeff_grad_T_diffusive_fluxes()
const IJK_Field_vector3_double & IJK_Thermal_base::get_div_coeff_grad_T_diffusive_fluxes () const inline
References div_coeff_grad_T_raw_, dummy_double_vect_, and store_flux_operators_for_energy_balance_.
Referenced by posttraiter_champs_instantanes_thermal().
get_interfacial_heat_flux_dispatched()
virtual const IJK_Field_vector3_double & IJK_Thermal_base::get_interfacial_heat_flux_dispatched () const inline virtual
Reimplemented in IJK_Thermal_Subresolution.
References dummy_double_vect_.
Referenced by posttraiter_champs_instantanes_thermal().
get_interfacial_heat_flux_contrib()
virtual const IJK_Field_vector3_double & IJK_Thermal_base::get_interfacial_heat_flux_contrib () const inline virtual
Reimplemented in IJK_Thermal_Subresolution.
References dummy_double_vect_.
Referenced by posttraiter_champs_instantanes_thermal().
get_interfacial_heat_flux_current()
virtual const IJK_Field_vector3_double & IJK_Thermal_base::get_interfacial_heat_flux_current () const inline virtual
Reimplemented in IJK_Thermal_Subresolution.
References dummy_double_vect_.
Referenced by posttraiter_champs_instantanes_thermal().
get_modified_time()
double IJK_Thermal_base::get_modified_time () virtual
Reimplemented in IJK_Thermal_Subresolution.
References ref_ijk_ft_.
get_rising_velocities_parameters()
void IJK_Thermal_base::get_rising_velocities_parameters (int & compute_rising_velocities, int & fill_rising_velocities, int & use_bubbles_velocities_from_interface, int & use_bubbles_velocities_from_barycentres)
References compute_rising_velocities(), compute_rising_velocities_, fill_rising_velocities_, use_bubbles_velocities_from_barycentres_, and use_bubbles_velocities_from_interface_.
get_rho_cp_u_ijk()
double IJK_Thermal_base::get_rho_cp_u_ijk (const IJK_Field_double & vx, int i, int j, int k) const virtual
Reimplemented in IJK_Thermal_Onefluid.
References cp_liquid_, and ref_ijk_ft_.
Referenced by add_temperature_source().
get_div_lambda_ijk()
virtual double IJK_Thermal_base::get_div_lambda_ijk (int i, int j, int k) const inline virtual
Reimplemented in IJK_Thermal_Onefluid.
Referenced by add_temperature_source().
compute_temperature_dimensionless_theta_mean()
double IJK_Thermal_base::compute_temperature_dimensionless_theta_mean (const IJK_Field_double & vx) virtual
Reimplemented in IJK_Thermal_Onefluid.
References cp_liquid_, ref_ijk_ft_, and temperature_adimensionnelle_theta_.
Referenced by calculer_Nusselt().
get_fichier_sauvegarde()
const char * IJK_Thermal_base::get_fichier_sauvegarde () const inline
References fichier_reprise_temperature_.
set_fichier_sauvegarde()
void IJK_Thermal_base::set_fichier_sauvegarde (const char * lataname) inline
References fichier_reprise_temperature_.
set_field_T_ana()
void IJK_Thermal_base::set_field_T_ana () virtual
Reimplemented in IJK_Thermal_Subresolution.
References expression_T_ana_, rang_, ref_ijk_ft_, and temperature_ana_.
Referenced by post_process_after_temperature_increment(), and posttraiter_champs_instantanes_thermal().
get_conserv_energy_global()
virtual int & IJK_Thermal_base::get_conserv_energy_global () inline virtual
References conserv_energy_global_.
Referenced by IJK_Thermal_Onefluid::euler_rustine_step(), and IJK_Thermal_Onefluid::rk3_rustine_sub_step().
get_E0()
const double & IJK_Thermal_base::get_E0 () const inline
References E0_.
Referenced by IJK_Thermal_Onefluid::euler_rustine_step(), and IJK_Thermal_Onefluid::rk3_rustine_sub_step().
calculer_ecart_T_ana()
void IJK_Thermal_base::calculer_ecart_T_ana () virtual
Reimplemented in IJK_Thermal_Subresolution.
References ecart_t_ana_, IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel(), expression_T_ana_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost(), Process::je_suis_maitre(), Process::Journal(), Process::mp_sum(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), ref_ijk_ft_, temperature_, and temperature_ana_.
Referenced by get_IJK_field(), and posttraiter_champs_instantanes_thermal().
compute_interfacial_temperature2()
void IJK_Thermal_base::compute_interfacial_temperature2 (ArrOfDouble & interfacial_temperature, ArrOfDouble & flux_normal_interp) virtual
Reimplemented in IJK_Thermal_cut_cell.
References Corrige_flux_FT_base::calcul_temperature_flux_interface(), corrige_flux_, Maillage_FT_Disc::facettes(), Domaine_IJK::get_constant_delta(), Maillage_FT_Disc::get_update_normale_facettes(), Maillage_FT_Disc::get_update_surface_facettes(), lambda_liquid_, lambda_vapour_, Maillage_FT_Disc::nb_facettes(), ref_ijk_ft_, TRUSTTab< _TYPE_, _SIZE_ >::resize(), Maillage_FT_Disc::sommets(), and temperature_ft_.
Referenced by ecrire_statistiques_bulles(), and posttraiter_champs_instantanes_thermal_interface_ref().
compute_ghost_cell_numbers_for_subproblems()
virtual void IJK_Thermal_base::compute_ghost_cell_numbers_for_subproblems (const Domaine_IJK & splitting, int ghost_init) inline virtual
Reimplemented in IJK_Thermal_Subresolution.
References ghost_cells_.
compute_eulerian_distance()
void IJK_Thermal_base::compute_eulerian_distance ()
compute_eulerian_curvature()
void IJK_Thermal_base::compute_eulerian_curvature ()
compute_eulerian_curvature_from_interface()
void IJK_Thermal_base::compute_eulerian_curvature_from_interface ()
update_intersections()
virtual void IJK_Thermal_base::update_intersections () inline virtual
Reimplemented in IJK_Thermal_Subresolution.
clean_ijk_intersections()
virtual void IJK_Thermal_base::clean_ijk_intersections () inline virtual
Reimplemented in IJK_Thermal_Subresolution.
post_process_thermal_wake_slices()
virtual void IJK_Thermal_base::post_process_thermal_wake_slices (const Nom & local_quantities_thermal_slices_time_index_folder) inline virtual
Reimplemented in IJK_Thermal_Subresolution.
Referenced by thermal_subresolution_outputs().
post_process_thermal_downstream_lines()
virtual void IJK_Thermal_base::post_process_thermal_downstream_lines (const Nom & local_quantities_thermal_lines_time_index_folder) inline virtual
Reimplemented in IJK_Thermal_Subresolution.
Referenced by thermal_subresolution_outputs().
set_thermal_subresolution_outputs()
virtual void IJK_Thermal_base::set_thermal_subresolution_outputs (const Nom & interfacial_quantities_thermal_probes, const Nom & shell_quantities_thermal_probes, const Nom & overall_bubbles_quantities, const Nom & local_quantities_thermal_probes_time_index_folder) inline virtual
Reimplemented in IJK_Thermal_Subresolution.
Referenced by thermal_subresolution_outputs().
compute_temperature_init()
void IJK_Thermal_base::compute_temperature_init () virtual
Reimplemented in IJK_Thermal_cut_cell, and IJK_Thermal_Subresolution.
References expression_T_init_, ref_ijk_ft_, and temperature_.
Referenced by IJK_Thermal_cut_cell::compute_temperature_init(), IJK_Thermal_Subresolution::compute_temperature_init(), initialize(), and recompute_temperature_init().
recompute_temperature_init()
void IJK_Thermal_base::recompute_temperature_init () virtual
Reimplemented in IJK_Thermal_cut_cell, and IJK_Thermal_Subresolution.
References compute_temperature_init().
Referenced by IJK_Thermal_cut_cell::recompute_temperature_init().
set_subproblems_interfaces_fields()
virtual void IJK_Thermal_base::set_subproblems_interfaces_fields (const Domaine_IJK & splitting) inline virtual
Reimplemented in IJK_Thermal_Subresolution.
copy_previous_interface_state()
void IJK_Thermal_base::copy_previous_interface_state ()
References IJK_One_Dimensional_Subproblems_Interfaces_Fields::copy_previous_interface_state(), and thermal_local_subproblems_interfaces_fields_.
post_process_quantities_from_subresolution()
int IJK_Thermal_base::post_process_quantities_from_subresolution (const Motcles & liste_post_instantanes, const char * lata_name, const int latastep)
References IJK_One_Dimensional_Subproblems_Interfaces_Fields::posttraiter_champs_instantanes(), and thermal_local_subproblems_interfaces_fields_.
Referenced by posttraiter_champs_instantanes_thermal_interface().
copie_pure_vers_diph_sans_interpolation()
void IJK_Thermal_base::copie_pure_vers_diph_sans_interpolation () virtual
Reimplemented in IJK_Thermal_cut_cell.
References Process::exit().
echange_pure_vers_diph_cellules_initialement_pures()
void IJK_Thermal_base::echange_pure_vers_diph_cellules_initialement_pures () virtual
Reimplemented in IJK_Thermal_cut_cell.
References Process::exit().
echange_diph_vers_pure_cellules_finalement_pures()
void IJK_Thermal_base::echange_diph_vers_pure_cellules_finalement_pures () virtual
Reimplemented in IJK_Thermal_cut_cell.
References Process::exit().
vide_phase_invalide_cellules_diphasiques()
void IJK_Thermal_base::vide_phase_invalide_cellules_diphasiques () virtual
Reimplemented in IJK_Thermal_cut_cell.
References Process::exit().
remplir_tableau_pure_cellules_diphasiques()
void IJK_Thermal_base::remplir_tableau_pure_cellules_diphasiques (bool next_time) virtual
Reimplemented in IJK_Thermal_cut_cell.
References Process::exit().
compare_fluxes_thermal_subproblems()
virtual void IJK_Thermal_base::compare_fluxes_thermal_subproblems () inline virtual
Reimplemented in IJK_Thermal_Subresolution.
Referenced by calculer_dT().
post_process_std_thermal_field()
void IJK_Thermal_base::post_process_std_thermal_field (const Motcles & liste_post_instantanes, const char * lata_name, const int latastep, const double current_time, const int idx, const Motcles & tested_names, const Nom & name_field, const Motcle & lata_suffix, const IJK_Field_double & field, std::ostringstream & oss, int & counter, const int & first_thermal_rank = 0)
References Motcles::contient_(), and TRUST_Vector< _CLASSE_ >::size().
posttraiter_champs_instantanes_thermal()
int IJK_Thermal_base::posttraiter_champs_instantanes_thermal (const Motcles & liste_post_instantanes, const char * lata_name, const int latastep, const double current_time, const int idx)
References calculer_ecart_T_ana(), Motcles::contient_(), CUTCELL, get_bary(), get_cell_faces_corrected_bool(), get_cell_faces_corrected_convective(), get_cell_faces_corrected_diffusive(), get_cell_faces_neighbours_corrected_all_bool(), get_cell_faces_neighbours_corrected_convective(), get_cell_faces_neighbours_corrected_convective_frame_of_ref(), get_cell_faces_neighbours_corrected_diag_bool(), get_cell_faces_neighbours_corrected_diffusive(), get_cell_faces_neighbours_corrected_min_max_bool(), get_cell_faces_neighbours_corrected_velocity_temperature(), get_cell_neighbours_corrected(), get_cell_neighbours_corrected_trimmed(), get_debug(), get_debug_lrs_cells(), get_div_coeff_grad_T_diffusive_fluxes(), get_div_lambda_grad_T(), get_div_lambda_grad_T_volume(), get_ecart_t_ana(), get_ecart_t_ana_rel(), get_eulerian_compo_connex_from_interface_ft(), get_eulerian_compo_connex_from_interface_ghost_ft(), get_eulerian_compo_connex_from_interface_ghost_ns(), get_eulerian_compo_connex_from_interface_ns(), get_eulerian_compo_connex_ft(), get_eulerian_compo_connex_ghost_ft(), get_eulerian_compo_connex_ghost_ns(), get_eulerian_compo_connex_int_from_interface_ghost_ns(), get_eulerian_compo_connex_int_from_interface_ns(), get_eulerian_compo_connex_ns(), get_eulerian_curvature_ft(), get_eulerian_curvature_ns(), get_eulerian_distance_ft(), get_eulerian_distance_ns(), get_eulerian_rising_velocities(), get_grad_T(), get_grad_T_interface_ft(), get_grad_T_interface_ns(), get_gradient_temperature_elem(), get_gradient_temperature_elem_smooth(), get_hessian_cross_temperature_elem(), get_hessian_diag_temperature_elem(), get_interfacial_area_ft(), get_interfacial_area_ns(), get_interfacial_heat_flux_contrib(), get_interfacial_heat_flux_current(), get_interfacial_heat_flux_dispatched(), get_neighbours_faces_weighting_colinearity(), get_neighbours_temperature_colinearity_weighting(), get_normal_vector_ft(), get_normal_vector_ns(), get_normal_vector_ns_normed(), get_probe_collision_debug_field(), get_rank(), get_rho_cp_u_T_convective_fluxes(), get_tangential_gradient_temperature_elem_smooth(), get_temperature(), get_temperature_ana(), get_temperature_before_extrapolation(), get_temperature_cell_neighbours(), get_temperature_cell_neighbours_debug(), get_temperature_elem_smooth(), get_temperature_ft(), get_u_T_convective(), get_u_T_convective_volume(), lata_suffix_, ref_ijk_ft_, set_field_T_ana(), source_temperature_, temperature_adimensionnelle_theta_, and thermal_rank_.
get_thermal_problem_type()
Nom & IJK_Thermal_base::get_thermal_problem_type () inline
References thermal_problem_type_.
Referenced by typer_lire_thermal_equation().
get_thermal_rank()
int & IJK_Thermal_base::get_thermal_rank () inline
References thermal_rank_.
Referenced by typer_lire_thermal_equation().
get_thermal_words()
const Motcles & IJK_Thermal_base::get_thermal_words () const inline
References thermal_words_.
get_thermal_suffix()
const Motcles & IJK_Thermal_base::get_thermal_suffix () const inline
References lata_suffix_.
posttraiter_tous_champs_thermal()
void IJK_Thermal_base::posttraiter_tous_champs_thermal (Motcles & liste, const int idx) const
References TRUST_Vector< _CLASSE_ >::add(), MSUBRES, SUBRES, and thermal_rank_.
ecrire_statistiques_bulles()
void IJK_Thermal_base::ecrire_statistiques_bulles (int reset, const Nom & nom_cas, const double current_time, const ArrOfDouble & surface, const int idx)
References Sortie_Fichier_base::close(), compute_interfacial_temperature2(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel(), get_temperature(), get_temperature_ft(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost(), Process::je_suis_maitre(), Sortie_Fichier_base::ouvrir(), ref_ijk_ft_, and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
posttraiter_champs_instantanes_thermal_interface()
int IJK_Thermal_base::posttraiter_champs_instantanes_thermal_interface (const Motcles & liste_post_instantanes, const char * lata_name, const int latastep, const double current_time, const int idx)
References MSUBRES, post_process_quantities_from_subresolution(), posttraiter_champs_instantanes_thermal_interface_ref(), SUBRES, and thermal_rank_.
posttraiter_champs_instantanes_thermal_interface_ref()
int IJK_Thermal_base::posttraiter_champs_instantanes_thermal_interface_ref (const Motcles & liste_post_instantanes, const char * lata_name, const int latastep, const double current_time, const int idx)
References compute_interfacial_temperature2(), Motcles::contient_(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel(), get_temperature(), get_temperature_ft(), Maillage_FT_Disc::get_update_surface_facettes(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost(), lata_suffix_, Maillage_FT_Disc::nb_facettes(), ref_ijk_ft_, and thermal_rank_.
Referenced by posttraiter_champs_instantanes_thermal_interface().
thermal_subresolution_outputs()
void IJK_Thermal_base::thermal_subresolution_outputs (const Nom & interfacial_quantities_thermal_probes, const Nom & shell_quantities_thermal_probes, const Nom & overall_bubbles_quantities, const Nom & local_quantities_thermal_probes_time_index_folder, const Nom & local_quantities_thermal_slices_time_index_folder, const Nom & local_quantities_thermal_lines_time_index_folder)
References MSUBRES, post_process_thermal_downstream_lines(), post_process_thermal_wake_slices(), set_thermal_subresolution_outputs(), SUBRES, and thermal_rank_.
typer_lire_thermal_equation()
void IJK_Thermal_base::typer_lire_thermal_equation (TRUST_Deriv< IJK_Thermal_base > & eq, Entree & is) static
References Process::abort(), Motcle::debute_par(), get_thermal_problem_type(), get_thermal_rank(), Nom::getString(), and Motcles::search().
Referenced by IJK_Thermals::readOn().
noms_compris()
const Noms IJK_Thermal_base::noms_compris () const inline
References champs_compris(), and Champs_compris_IJK::liste_noms_compris().
champs_compris()
const Champs_compris_IJK & IJK_Thermal_base::champs_compris () const inline
References champs_compris_.
Referenced by noms_compris().
compute_cell_volume()
void IJK_Thermal_base::compute_cell_volume () protected
References d_temperature_, Domaine_IJK::get_constant_delta(), and vol_.
Referenced by initialize().
compute_min_cell_delta()
void IJK_Thermal_base::compute_min_cell_delta () protected
References d_temperature_, Domaine_IJK::get_constant_delta(), and min_delta_xyz_.
Referenced by initialize().
compute_cell_diagonal()
void IJK_Thermal_base::compute_cell_diagonal (const Domaine_IJK & splitting) protected
References cell_diagonal_, and Domaine_IJK::get_constant_delta().
Referenced by IJK_Thermal_Subresolution::compute_ghost_cell_numbers_for_subproblems().
lire_temperature()
void IJK_Thermal_base::lire_temperature (const Domaine_IJK & splitting) protected virtual
Reimplemented in IJK_Thermal_cut_cell.
References fichier_reprise_temperature_, Domaine_base::le_nom(), rang_, rank_reprise_temperature_, temperature_, and timestep_reprise_temperature_.
Referenced by initialize(), and initialize_switch().
calculer_dT()
void IJK_Thermal_base::calculer_dT (const IJK_Field_vector3_double & velocity) protected
References add_temperature_diffusion(), add_temperature_source(), Statistiques::begin_count(), clean_thermal_subproblems(), compare_fluxes_thermal_subproblems(), compute_convective_diffusive_fluxes_face_centre(), compute_eulerian_bounding_box_fill_compo(), compute_eulerian_grad_T_interface(), compute_eulerian_temperature_ghost(), compute_global_energy(), compute_temperature_cell_centres(), compute_temperature_convection(), compute_temperature_convection_conservative(), compute_temperature_convective_fluxes(), compute_temperature_diffusive_fluxes(), compute_temperature_gradient_elem(), compute_temperature_hessian_cross_elem(), compute_temperature_hessian_diag_elem(), compute_thermal_subproblems(), conv_temperature_negligible_, correct_temperature_for_eulerian_fluxes(), d_temperature_, debug_, diff_temperature_negligible_, Statistiques::end_count(), Process::exit(), force_upstream_temperature(), Navier_Stokes_FTD_IJK::get_nb_diam_upstream(), Navier_Stokes_FTD_IJK::get_upstream_dir(), Navier_Stokes_FTD_IJK::get_upstream_stencil(), Navier_Stokes_FTD_IJK::get_vitesse_upstream(), Process::mp_max(), Process::mp_min(), nb_diam_upstream_, Statistiques::new_counter(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), prepare_ij_fluxes_k_layers(), propagate_eulerian_grad_T_interface(), rang_, ref_ijk_ft_, set_zero_temperature_increment(), store_temperature_before_extrapolation(), temperature_, type_temperature_convection_form_, and upstream_temperature_.
Referenced by euler_time_step(), and rk3_sub_step().
post_process_after_temperature_increment()
void IJK_Thermal_base::post_process_after_temperature_increment () protected virtual
Reimplemented in IJK_Thermal_Subresolution.
References clip_max_temperature_values(), clip_min_temperature_values(), compute_temperature_cell_centres(), correct_operators_for_visu(), correct_temperature_for_visu(), debug_, enforce_periodic_temperature_boundary_value(), and set_field_T_ana().
Referenced by euler_time_step(), and IJK_Thermal_Subresolution::post_process_after_temperature_increment().
compute_temperature_convective_fluxes()
void IJK_Thermal_base::compute_temperature_convective_fluxes (const IJK_Field_vector3_double & velocity) protected
References Statistiques::begin_count(), OpGradFluxQuickIJKScalar_double::calculer_grad_flux(), d_temperature_, disable_relative_velocity_energy_balance_, IJK_Field_vector< T, N >::echange_espace_virtuel(), Statistiques::end_count(), get_rhocp_l(), Statistiques::new_counter(), rho_cp_u_T_convective_raw_, Operateur_IJK_elem_conv_base_double::set_velocity_frame_of_reference(), store_flux_operators_for_energy_balance_, temperature_, and temperature_grad_flux_op_quick_.
Referenced by calculer_dT().
compute_temperature_convection()
void IJK_Thermal_base::compute_temperature_convection (const IJK_Field_vector3_double & velocity) protected
References Statistiques::begin_count(), conv_temperature_negligible_, d_temperature_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::data(), Statistiques::end_count(), Statistiques::new_counter(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), ref_ijk_ft_, temperature_, temperature_convection_op_, u_T_convective_, u_T_convective_volume_, DebogIJK::verifier(), and vol_.
Referenced by calculer_dT().
compute_temperature_convection_conservative()
virtual void IJK_Thermal_base::compute_temperature_convection_conservative (const IJK_Field_vector3_double & velocity) inline protected virtual
Reimplemented in IJK_Thermal_Onefluid.
Referenced by calculer_dT().
compute_boundary_conditions_thermal()
void IJK_Thermal_base::compute_boundary_conditions_thermal () protected
References boundary_conditions_, boundary_flux_kmax_, boundary_flux_kmin_, calculer_flux_thermique_bord(), Boundary_Conditions_Thermique::get_bctype_k_max(), Boundary_Conditions_Thermique::get_bctype_k_min(), Boundary_Conditions_Thermique::get_flux_kmax(), Boundary_Conditions_Thermique::get_flux_kmin(), Boundary_Conditions_Thermique::get_temperature_kmax(), Boundary_Conditions_Thermique::get_temperature_kmin(), imposer_flux_thermique_bord(), lambda_liquid_, Boundary_Conditions_Thermique::Paroi_Flux_impose, Boundary_Conditions_Thermique::Paroi_Temperature_imposee, temperature_, and DebogIJK::verifier().
Referenced by add_temperature_diffusion().
compute_temperature_diffusive_fluxes()
void IJK_Thermal_base::compute_temperature_diffusive_fluxes () protected
References Statistiques::begin_count(), boundary_flux_kmax_, boundary_flux_kmin_, OpHessFluxCentre2IJKScalar_double::calculer_hess_flux(), div_coeff_grad_T_raw_, IJK_Field_vector< T, N >::echange_espace_virtuel(), Statistiques::end_count(), Statistiques::new_counter(), store_flux_operators_for_energy_balance_, temperature_, and temperature_hess_flux_op_centre_.
Referenced by calculer_dT().
add_temperature_diffusion()
void IJK_Thermal_base::add_temperature_diffusion () protected virtual
Reimplemented in IJK_Thermal_cut_cell, and IJK_Thermal_Onefluid.
References Statistiques::begin_count(), boundary_flux_kmax_, boundary_flux_kmin_, compute_boundary_conditions_thermal(), compute_diffusion_increment(), diff_temperature_negligible_, div_coeff_grad_T_volume_, Statistiques::end_count(), Statistiques::new_counter(), temperature_, temperature_diffusion_op_, and DebogIJK::verifier().
Referenced by IJK_Thermal_Onefluid::add_temperature_diffusion(), and calculer_dT().
compute_diffusion_increment()
virtual void IJK_Thermal_base::compute_diffusion_increment () protected pure virtual
Implemented in IJK_Thermal_cut_cell, IJK_Thermal_Onefluid, and IJK_Thermal_Subresolution.
Referenced by add_temperature_diffusion().
correct_temperature_for_eulerian_fluxes()
virtual void IJK_Thermal_base::correct_temperature_for_eulerian_fluxes () protected pure virtual
Implemented in IJK_Thermal_cut_cell, IJK_Thermal_Onefluid, and IJK_Thermal_Subresolution.
Referenced by calculer_dT().
store_temperature_before_extrapolation()
virtual void IJK_Thermal_base::store_temperature_before_extrapolation () inline protected virtual
Reimplemented in IJK_Thermal_Subresolution.
Referenced by calculer_dT().
correct_temperature_increment_for_interface_leaving_cell()
virtual void IJK_Thermal_base::correct_temperature_increment_for_interface_leaving_cell () inline protected virtual
Reimplemented in IJK_Thermal_Subresolution.
enforce_zero_value_eulerian_distance()
void IJK_Thermal_base::enforce_zero_value_eulerian_distance () protected
enforce_zero_value_eulerian_curvature()
void IJK_Thermal_base::enforce_zero_value_eulerian_curvature () protected
enforce_max_value_eulerian_curvature()
void IJK_Thermal_base::enforce_max_value_eulerian_curvature () protected
compute_eulerian_grad_T_interface()
void IJK_Thermal_base::compute_eulerian_grad_T_interface (const int on_splitting_ns = 0) protected
References compute_grad_T_interface_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::data(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel(), eulerian_curvature_ft_, eulerian_curvature_ns_, eulerian_distance_ft_, eulerian_distance_ns_, eulerian_grad_T_interface_ft_, eulerian_grad_T_interface_ns_, eulerian_interfacial_area_ft_, eulerian_interfacial_area_ns_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost(), ref_ijk_ft_, spherical_approx_, temperature_, and temperature_ft_.
Referenced by calculer_dT().
propagate_eulerian_grad_T_interface()
void IJK_Thermal_base::propagate_eulerian_grad_T_interface () protected
References compute_grad_T_interface_, IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel(), eulerian_distance_ft_, eulerian_grad_T_interface_ft_, eulerian_grad_T_interface_ns_, gfm_recompute_field_ini_, gfm_smooth_factor_, gfm_vapour_mixed_only_, gfm_zero_neighbour_value_mean_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost(), n_iter_distance_, and ref_ijk_ft_.
Referenced by calculer_dT().
compute_eulerian_temperature_ghost()
void IJK_Thermal_base::compute_eulerian_temperature_ghost (const int on_splitting_ns = 0) protected
References IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel(), eulerian_curvature_ft_, eulerian_curvature_ns_, eulerian_distance_ft_, eulerian_distance_ns_, eulerian_grad_T_interface_ft_, eulerian_grad_T_interface_ns_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost(), ghost_fluid_, ref_ijk_ft_, spherical_approx_, temperature_, and temperature_ft_.
Referenced by calculer_dT().
compute_eulerian_bounding_box_fill_compo()
void IJK_Thermal_base::compute_eulerian_bounding_box_fill_compo () protected
References bounding_box_, bubbles_barycentre_, bubbles_volume_, compute_eulerian_compo_, min_max_larger_box_, and ref_ijk_ft_.
Referenced by calculer_dT().
compute_rising_velocities()
void IJK_Thermal_base::compute_rising_velocities () protected
Referenced by get_rising_velocities_parameters().
compute_temperature_gradient_elem()
void IJK_Thermal_base::compute_temperature_gradient_elem () protected
References OpGradCentre2IJKScalar_double::calculer_grad(), compute_grad_T_elem_, direct_smoothing_factors_, IJK_Field_vector< T, N >::echange_espace_virtuel(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel(), eulerian_normal_vectors_ns_normed_, gaussian_smoothing_factors_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost(), grad_T_elem_, grad_T_elem_smooth_, grad_T_elem_tangential_, ref_ijk_ft_, smooth_grad_T_elem_, smoothing_numbers_, smoothing_remove_normal_compo_, smoothing_use_unique_phase_, temperature_, temperature_gaussian_filtered_, and temperature_grad_op_centre_.
Referenced by calculer_dT().
compute_temperature_hessian_diag_elem()
void IJK_Thermal_base::compute_temperature_hessian_diag_elem () protected
References boundary_flux_kmax_, boundary_flux_kmin_, OpHessCentre2IJKScalar_double::calculer_hess(), compute_hess_diag_T_elem_, IJK_Field_vector< T, N >::echange_espace_virtuel(), hess_diag_T_elem_, temperature_, and temperature_hess_op_centre_.
Referenced by calculer_dT().
compute_temperature_hessian_cross_elem()
void IJK_Thermal_base::compute_temperature_hessian_cross_elem () protected
References OpGradCentre2IJKScalar_double::calculer_grad_y(), OpGradCentre2IJKScalar_double::calculer_grad_z(), compute_hess_cross_T_elem_, IJK_Field_vector< T, N >::echange_espace_virtuel(), grad_T_elem_, hess_cross_T_elem_, temperature_, and temperature_grad_op_centre_.
Referenced by calculer_dT().
correct_temperature_for_visu()
virtual void IJK_Thermal_base::correct_temperature_for_visu () inline protected virtual
Reimplemented in IJK_Thermal_Subresolution.
Referenced by post_process_after_temperature_increment().
correct_operators_for_visu()
virtual void IJK_Thermal_base::correct_operators_for_visu () inline protected virtual
Reimplemented in IJK_Thermal_Subresolution.
Referenced by post_process_after_temperature_increment().
clip_temperature_values()
virtual void IJK_Thermal_base::clip_temperature_values () inline protected virtual
clip_min_temperature_values()
virtual void IJK_Thermal_base::clip_min_temperature_values () inline protected virtual
Reimplemented in IJK_Thermal_Subresolution.
Referenced by post_process_after_temperature_increment().
clip_max_temperature_values()
virtual void IJK_Thermal_base::clip_max_temperature_values () inline protected virtual
Reimplemented in IJK_Thermal_Subresolution.
Referenced by post_process_after_temperature_increment().
compute_thermal_subproblems()
virtual void IJK_Thermal_base::compute_thermal_subproblems () inline protected virtual
Reimplemented in IJK_Thermal_Subresolution.
Referenced by calculer_dT().
compute_convective_diffusive_fluxes_face_centre()
virtual void IJK_Thermal_base::compute_convective_diffusive_fluxes_face_centre () inline protected virtual
Reimplemented in IJK_Thermal_Subresolution.
Referenced by calculer_dT().
compute_convective_fluxes_face_centre()
virtual void IJK_Thermal_base::compute_convective_fluxes_face_centre () inline protected virtual
Reimplemented in IJK_Thermal_Subresolution.
compute_diffusive_fluxes_face_centre()
virtual void IJK_Thermal_base::compute_diffusive_fluxes_face_centre () inline protected virtual
Reimplemented in IJK_Thermal_Subresolution.
prepare_ij_fluxes_k_layers()
virtual void IJK_Thermal_base::prepare_ij_fluxes_k_layers () inline protected virtual
Reimplemented in IJK_Thermal_Subresolution.
Referenced by calculer_dT().
compute_temperature_cell_centres()
virtual void IJK_Thermal_base::compute_temperature_cell_centres (const int first_corr) inline protected virtual
Reimplemented in IJK_Thermal_Subresolution.
Referenced by calculer_dT(), and post_process_after_temperature_increment().
set_zero_temperature_increment()
virtual void IJK_Thermal_base::set_zero_temperature_increment () inline protected virtual
Reimplemented in IJK_Thermal_Subresolution.
Referenced by calculer_dT().
clean_thermal_subproblems()
virtual void IJK_Thermal_base::clean_thermal_subproblems () inline protected virtual
Reimplemented in IJK_Thermal_Subresolution.
Referenced by calculer_dT().
calculer_gradient_temperature()
void IJK_Thermal_base::calculer_gradient_temperature (const IJK_Field_double & temperature, IJK_Field_vector3_double & grad_T) protected
References calulate_grad_T_, Motcles::contient_(), and liste_post_instantanes_.
calculer_energies()
void IJK_Thermal_base::calculer_energies (double & E_liq_pure, double & E_liq, double & E_vap_pure, double & E_vap, double & E_mixt, double & E_tot) protected
References cp_liquid_, cp_vapour_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), ref_ijk_ft_, and temperature_.
Referenced by calculer_temperature_adim_bulles().
source_callback()
void IJK_Thermal_base::source_callback () protected
References calculer_temperature_adim_bulles(), Motcles::contient_(), debug_, and liste_post_instantanes_.
Referenced by IJK_Thermal_Onefluid::euler_rustine_step(), euler_time_step(), IJK_Thermal_Onefluid::rk3_rustine_sub_step(), and rk3_sub_step().
calculer_temperature_physique_T()
void IJK_Thermal_base::calculer_temperature_physique_T (const IJK_Field_double & vx, const double dTm) protected
References d_temperature_, IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel(), Domaine_IJK::get_constant_delta(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_domaine(), Domaine_IJK::get_offset_local(), Domaine_IJK::get_origin(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost(), temperature_, temperature_physique_T_, DebogIJK::verifier(), and wall_flux_.
Referenced by add_temperature_source().
calculer_temperature_adim_bulles()
void IJK_Thermal_base::calculer_temperature_adim_bulles () protected
References calculer_energies(), Sortie_Fichier_base::close(), Domaine_IJK::ELEM, IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_domaine(), Domaine_IJK::get_nb_items_global(), Process::je_suis_maitre(), Process::mp_sum(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), rang_, ref_ijk_ft_, temperature_, temperature_adim_bulles_, and Tv0_.
Referenced by source_callback().
add_temperature_source()
void IJK_Thermal_base::add_temperature_source () protected
References Statistiques::begin_count(), boundary_conditions_, calculer_Nusselt(), calculer_temperature_adimensionnelle_theta(), calculer_temperature_physique_T(), compute_rho_cp_u_mean(), cp_liquid_, cp_vapour_, d_temperature_, Process::exit(), Domaine_IJK::get_constant_delta(), get_div_lambda_ijk(), Domaine_IJK::get_domain_length(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_domaine(), Boundary_Conditions_Thermique::get_flux_kmax(), get_rho_cp_u_ijk(), lambda_variable_, Statistiques::new_counter(), ref_ijk_ft_, source_temperature_, temperature_, type_T_source_, and vol_.
Referenced by calculer_dT().
calculer_Nusselt()
void IJK_Thermal_base::calculer_Nusselt (const IJK_Field_double & vx) protected
References Sortie_Fichier_base::close(), compute_rho_cp_u_mean(), compute_temperature_dimensionless_theta_mean(), Process::je_suis_maitre(), rang_, and ref_ijk_ft_.
Referenced by add_temperature_source().
calculer_temperature_adimensionnelle_theta()
void IJK_Thermal_base::calculer_temperature_adimensionnelle_theta (const IJK_Field_double & vx, const double qw) protected
References compute_variable_wall_temperature(), Domaine_IJK::get_domain_length(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_domaine(), Domaine_IJK::get_nb_elem_tot(), Domaine_IJK::get_offset_local(), lambda_liquid_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), temperature_, temperature_adimensionnelle_theta_, and wall_flux_.
Referenced by add_temperature_source().
calculer_source_temperature_ana()
void IJK_Thermal_base::calculer_source_temperature_ana () protected
References Motcles::contient_(), ecart_source_t_ana_, expression_source_temperature_, Process::je_suis_maitre(), Process::Journal(), liste_post_instantanes_, Process::mp_sum(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), ref_ijk_ft_, source_temperature_, and source_temperature_ana_.
compute_rho_cp_u_mean()
double IJK_Thermal_base::compute_rho_cp_u_mean (const IJK_Field_double & vx) protected virtual
Reimplemented in IJK_Thermal_Onefluid, and IJK_Thermal_Subresolution.
References cp_liquid_, and ref_ijk_ft_.
Referenced by add_temperature_source(), calculer_Nusselt(), and IJK_Thermal_Subresolution::compute_rho_cp_u_mean().
compute_variable_wall_temperature()
double IJK_Thermal_base::compute_variable_wall_temperature (const int kmin, const int kmax) protected
References cp_liquid_, ref_ijk_ft_, and temperature_.
Referenced by calculer_temperature_adimensionnelle_theta().
force_upstream_temperature()
void IJK_Thermal_base::force_upstream_temperature (IJK_Field_double & temperature, double T_imposed, const IJK_Interfaces & interfaces, double nb_diam, int upstream_dir, int gravity_dir, int upstream_stencil) protected
References IJK_Composantes_Connex::get_bounding_box(), Domaine_IJK::get_constant_delta(), Domaine_IJK::get_domain_length(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_domaine(), IJK_Interfaces::get_ijk_compo_connex(), IJK_Interfaces::get_nb_bulles_reelles(), Domaine_IJK::get_offset_local(), Domaine_IJK::get_origin(), Domaine_IJK::get_periodic_flag(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), and IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk().
Referenced by calculer_dT().
enforce_periodic_temperature_boundary_value()
virtual void IJK_Thermal_base::enforce_periodic_temperature_boundary_value () inline protected virtual
Reimplemented in IJK_Thermal_Subresolution.
Referenced by post_process_after_temperature_increment().
compute_mixed_cells_number()
void IJK_Thermal_base::compute_mixed_cells_number (const IJK_Field_double & indicator) protected
Friends And Related Function Documentation
IJK_One_Dimensional_Subproblems
friend class IJK_One_Dimensional_Subproblems friend
IJK_One_Dimensional_Subproblem
friend class IJK_One_Dimensional_Subproblem friend
Member Data Documentation
info_obj
const Type_info IJK_Thermal_base::info_obj static
needs_op_unform_
int IJK_Thermal_base::needs_op_unform_ = 1 protected
Referenced by IJK_Thermal_cut_cell::IJK_Thermal_cut_cell(), IJK_Thermal_Onefluid::IJK_Thermal_Onefluid(), and initialize().
le_fluide_
TRUST_Ref< Milieu_base *> IJK_Thermal_base::le_fluide_ protected
Referenced by associer_milieu_base(), and milieu().
thermal_rank_
int IJK_Thermal_base::thermal_rank_ = 0 protected
Referenced by get_thermal_rank(), posttraiter_champs_instantanes_thermal(), posttraiter_champs_instantanes_thermal_interface(), posttraiter_champs_instantanes_thermal_interface_ref(), posttraiter_tous_champs_thermal(), and thermal_subresolution_outputs().
thermal_problem_type_
Nom IJK_Thermal_base::thermal_problem_type_ = "subresolution" protected
Referenced by get_thermal_problem_type().
thermal_words_
Motcles IJK_Thermal_base::thermal_words_ protected
Referenced by get_thermal_words(), and IJK_Thermal_base().
lata_suffix_
Motcles IJK_Thermal_base::lata_suffix_ protected
Referenced by get_thermal_suffix(), IJK_Thermal_base(), posttraiter_champs_instantanes_thermal(), and posttraiter_champs_instantanes_thermal_interface_ref().
champs_compris_
Champs_compris_IJK IJK_Thermal_base::champs_compris_ protected
Referenced by champs_compris(), get_IJK_field(), get_IJK_field_vector(), get_noms_champs_postraitables(), has_champ(), initialize(), IJK_Thermal_Onefluid::initialize(), and initialize_switch().
debug_
int IJK_Thermal_base::debug_ = 0 protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), IJK_One_Dimensional_Subproblems::associate_variables_for_post_processing(), calculer_dT(), IJK_Thermal_Subresolution::check_wrong_values_rhs(), IJK_Thermal_Subresolution::complete_field_thermal_wake_slice_ij_convection(), IJK_Thermal_Subresolution::compute_diffusion_increment(), IJK_Thermal_Subresolution::compute_first_order_operator_raw(), IJK_Thermal_Subresolution::compute_local_substep(), IJK_Thermal_Subresolution::compute_overall_probes_parameters(), IJK_Thermal_Subresolution::compute_temperature_cell_centres_first_correction(), IJK_Thermal_Subresolution::compute_temperature_cell_centres_second_correction(), IJK_Thermal_Subresolution::compute_temperature_init(), IJK_Thermal_Subresolution::compute_thermal_subproblems(), euler_time_step(), IJK_Thermal_Subresolution::find_time_dichotomy_derivative(), IJK_Thermal_Subresolution::find_time_dichotomy_integral(), get_debug(), IJK_Thermal_Subresolution::get_temperature_cell_neighbours_debug(), IJK_Thermal_Subresolution::initialise_identity_matrices(), IJK_Thermal_Subresolution::initialise_identity_matrices_sparse(), IJK_Thermal_Subresolution::initialise_radial_convection_operator(), IJK_Thermal_Subresolution::initialise_radial_convection_operator_sparse(), IJK_Thermal_Subresolution::initialise_radial_diffusion_operator(), IJK_Thermal_Subresolution::initialise_radial_diffusion_operator_sparse(), IJK_Thermal_Subresolution::initialise_thermal_subproblems(), IJK_Thermal_Subresolution::initialize(), IJK_Thermal_Subresolution::interpolate_convective_term_on_downstream_line(), IJK_Thermal_cut_cell::perform_thermal_step(), post_process_after_temperature_increment(), IJK_Thermal_Subresolution::post_process_after_temperature_increment(), IJK_Thermal_Subresolution::post_processed_field_thermal_wake_slice_ij(), IJK_Thermal_Subresolution::prepare_temporal_schemes(), printOn(), IJK_Thermal_cut_cell::rk3_sub_step(), set_param(), IJK_Thermal_Subresolution::set_subproblems_interfaces_fields(), IJK_Thermal_Subresolution::set_thermal_subresolution_outputs(), and source_callback().
latastep_reprise_
int IJK_Thermal_base::latastep_reprise_ = 0 protected
Referenced by get_latastep_reprise(), get_latastep_reprise_ini(), initialize(), printOn(), sauvegarder_temperature(), IJK_Thermal_cut_cell::sauvegarder_temperature(), and set_latastep_reprise().
latastep_reprise_ini_
int IJK_Thermal_base::latastep_reprise_ini_ = 0 protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), IJK_One_Dimensional_Subproblems::associate_variables_for_post_processing(), initialize(), IJK_Thermal_Subresolution::post_processed_field_thermal_wake_slice_ij(), IJK_Thermal_Subresolution::post_processed_fields_on_downstream_line(), sauvegarder_temperature(), IJK_Thermal_cut_cell::sauvegarder_temperature(), and set_param().
E0_
double IJK_Thermal_base::E0_ = 0. protected
Referenced by get_E0().
ref_ijk_ft_
TRUST_Ref< Probleme_FTD_IJK_base *> IJK_Thermal_base::ref_ijk_ft_ protected
Referenced by add_temperature_source(), associer(), calculer_dT(), calculer_ecart_T_ana(), calculer_energies(), calculer_Nusselt(), calculer_source_temperature_ana(), calculer_temperature_adim_bulles(), IJK_Thermal_Subresolution::clean_thermal_subproblems(), IJK_Thermal_Subresolution::clip_max_temperature_values(), IJK_Thermal_Subresolution::complete_convective_flux_frame_of_reference(), IJK_Thermal_Subresolution::complete_field_thermal_wake_slice_ij_convection(), IJK_Thermal_Subresolution::complete_field_thermal_wake_slice_ij_diffusion(), IJK_Thermal_Subresolution::complete_field_thermal_wake_slice_ij_indices_coords(), IJK_Thermal_Subresolution::complete_field_thermal_wake_slice_ij_temperature(), IJK_Thermal_Subresolution::complete_field_thermal_wake_slice_ij_temperature_incr(), IJK_Thermal_Subresolution::complete_field_thermal_wake_slice_ij_values(), IJK_Thermal_Subresolution::complete_field_thermal_wake_slice_ij_velocity(), IJK_Thermal_Onefluid::compute_diffusion_increment(), IJK_Thermal_Subresolution::compute_diffusion_increment(), IJK_Thermal_Onefluid::compute_dT_rustine(), compute_eulerian_bounding_box_fill_compo(), compute_eulerian_grad_T_interface(), compute_eulerian_temperature_ghost(), compute_global_energy(), compute_interfacial_temperature2(), IJK_Thermal_cut_cell::compute_interfacial_temperature2(), IJK_Thermal_Subresolution::compute_local_substep(), IJK_Thermal_Subresolution::compute_mean_liquid_temperature(), IJK_Thermal_Subresolution::compute_Nusselt_spherical_diffusion(), IJK_Thermal_Subresolution::compute_quasi_static_spherical_diffusion_expression(), compute_rho_cp_u_mean(), IJK_Thermal_Onefluid::compute_rho_cp_u_mean(), IJK_Thermal_Onefluid::compute_T_rust(), IJK_Thermal_Subresolution::compute_temperature_cell_centres_first_correction(), compute_temperature_convection(), IJK_Thermal_Onefluid::compute_temperature_convection_conservative(), compute_temperature_dimensionless_theta_mean(), IJK_Thermal_Onefluid::compute_temperature_dimensionless_theta_mean(), compute_temperature_gradient_elem(), compute_temperature_init(), IJK_Thermal_cut_cell::compute_temperature_init(), IJK_Thermal_Subresolution::compute_temperature_init(), IJK_Thermal_Subresolution::compute_thermal_subproblems(), compute_timestep(), compute_variable_wall_temperature(), IJK_Thermal_Subresolution::correct_any_temperature_field_for_visu(), IJK_Thermal_Subresolution::correct_any_temperature_fields_for_eulerian_fluxes(), IJK_Thermal_Subresolution::correct_operators_for_visu(), IJK_Thermal_Subresolution::correct_temperature_increment_for_interface_leaving_cell(), IJK_Thermal_Multiple_Subresolutions::correct_temperature_vapour_for_eulerian_fluxes(), ecrire_statistiques_bulles(), IJK_Thermal_Subresolution::enforce_periodic_temperature_boundary_value(), IJK_Thermal_Onefluid::euler_rustine_step(), euler_time_step(), IJK_Thermal_Subresolution::evaluate_total_liquid_absolute_parameter(), IJK_Thermal_Subresolution::evaluate_total_liquid_parameter_squared(), IJK_Thermal_Subresolution::find_time_dichotomy_derivative(), IJK_Thermal_Subresolution::find_time_dichotomy_integral(), IJK_Thermal_Subresolution::generate_expression_temperature_ini(), get_eulerian_compo_connex_from_interface_ft(), get_eulerian_compo_connex_from_interface_ghost_ft(), get_eulerian_compo_connex_from_interface_ghost_ns(), get_eulerian_compo_connex_from_interface_ns(), get_eulerian_compo_connex_ft(), get_eulerian_compo_connex_ghost_ft(), get_eulerian_compo_connex_ghost_ns(), get_eulerian_compo_connex_int_from_interface_ghost_ns(), get_eulerian_compo_connex_int_from_interface_ns(), get_eulerian_compo_connex_ns(), get_IJK_field(), get_modified_time(), IJK_Thermal_Subresolution::get_modified_time(), IJK_Thermal_Onefluid::get_rho_cp_ijk(), get_rho_cp_u_ijk(), get_rhocp_l(), get_rhocp_v(), IJK_Thermal_Subresolution::get_time_inflection_derivative(), IJK_Thermal_Subresolution::initialise_identity_matrices_sparse(), IJK_Thermal_Subresolution::initialise_radial_convection_operator_sparse(), IJK_Thermal_Subresolution::initialise_radial_diffusion_operator_sparse(), IJK_Thermal_Subresolution::initialise_thermal_line_points(), IJK_Thermal_Subresolution::initialise_thermal_subproblems(), initialize(), IJK_Thermal_cut_cell::initialize(), IJK_Thermal_Onefluid::initialize(), IJK_Thermal_Subresolution::initialize(), IJK_Thermal_Subresolution::interpolate_convective_term_on_downstream_line(), IJK_Thermal_Subresolution::interpolate_diffusive_term_on_downstream_line(), IJK_Thermal_Subresolution::interpolate_temperature_increment_on_downstream_line(), IJK_Thermal_Subresolution::interpolate_temperature_on_downstream_line(), IJK_Thermal_Subresolution::interpolate_velocity_on_downstream_line(), milieu(), IJK_Thermal_cut_cell::perform_thermal_step(), IJK_Thermal_Subresolution::post_process_thermal_downstream_lines(), IJK_Thermal_Subresolution::post_process_thermal_wake_slice(), IJK_Thermal_Subresolution::post_process_thermal_wake_slice_index_dir(), IJK_Thermal_Subresolution::post_process_thermal_wake_slices(), IJK_Thermal_Subresolution::post_processed_field_thermal_wake_slice_ij(), IJK_Thermal_Subresolution::post_processed_fields_on_downstream_line(), posttraiter_champs_instantanes_thermal(), posttraiter_champs_instantanes_thermal_interface_ref(), IJK_Thermal_Subresolution::pre_initialise_thermal_subproblems_matrices(), propagate_eulerian_grad_T_interface(), IJK_Thermal_Multiple_Subresolutions::readOn(), IJK_Thermal_cut_cell::recompute_temperature_init(), IJK_Thermal_Subresolution::replace_temperature_cell_centres_neighbours(), IJK_Thermal_Onefluid::rk3_rustine_sub_step(), rk3_sub_step(), sauvegarder_temperature(), IJK_Thermal_cut_cell::sauvegarder_temperature(), set_field_T_ana(), IJK_Thermal_Subresolution::set_field_T_ana(), IJK_Thermal_Subresolution::set_field_temperature_per_bubble(), IJK_Thermal_Subresolution::store_temperature_before_extrapolation(), update_thermal_properties(), and IJK_Thermal_Onefluid::update_thermal_properties().
ref_ijk_ft_post_
TRUST_Ref< Postprocessing_IJK *> IJK_Thermal_base::ref_ijk_ft_post_ protected
Referenced by associer_post(), initialize(), and IJK_Thermal_Onefluid::initialize().
ref_ijk_ft_switch_
TRUST_Ref< Switch_FT_double *> IJK_Thermal_base::ref_ijk_ft_switch_ protected
Referenced by associer_switch().
ref_intersection_ijk_cell_
TRUST_Ref< Intersection_Interface_ijk_cell *> IJK_Thermal_base::ref_intersection_ijk_cell_ protected
Referenced by associer_interface_intersections().
ref_intersection_ijk_face_
TRUST_Ref< Intersection_Interface_ijk_face *> IJK_Thermal_base::ref_intersection_ijk_face_ protected
Referenced by associer_interface_intersections().
corrige_flux_
TRUST_Deriv< Corrige_flux_FT_base > IJK_Thermal_base::corrige_flux_ protected
Referenced by IJK_Thermal_Subresolution::clean_ijk_intersections(), IJK_Thermal_Subresolution::clean_thermal_subproblems(), IJK_Thermal_Subresolution::complete_thermal_fluxes_face_centre(), IJK_Thermal_Subresolution::compute_convective_diffusive_fluxes_face_centre(), IJK_Thermal_Subresolution::compute_convective_fluxes_face_centre(), IJK_Thermal_Subresolution::compute_diffusive_fluxes_face_centre(), compute_interfacial_temperature2(), IJK_Thermal_Subresolution::compute_min_max_reachable_fluxes(), IJK_Thermal_Subresolution::compute_temperature_cell_centres_first_correction(), initialize(), IJK_Thermal_Subresolution::initialize(), IJK_Thermal_Subresolution::prepare_ij_fluxes_k_layers(), IJK_Thermal_Subresolution::prepare_thermal_flux_correction(), IJK_Thermal_Subresolution::replace_temperature_cell_centres_neighbours(), IJK_Thermal_Subresolution::set_zero_temperature_increment(), and IJK_Thermal_Subresolution::update_intersections().
rang_
int IJK_Thermal_base::rang_ = 0 protected
Referenced by associer_milieu_base(), calculer_dT(), calculer_Nusselt(), calculer_temperature_adim_bulles(), IJK_Thermal_Onefluid::euler_rustine_step(), euler_time_step(), get_field_name_with_rank(), get_IJK_field(), get_rank(), initialize(), lire_temperature(), IJK_Thermal_cut_cell::lire_temperature(), IJK_Thermal_Subresolution::post_processed_field_thermal_wake_slice_ij(), IJK_Thermal_Subresolution::post_processed_fields_on_downstream_line(), IJK_Thermal_Onefluid::rk3_rustine_sub_step(), rk3_sub_step(), set_field_T_ana(), IJK_Thermal_Subresolution::set_thermal_subresolution_outputs(), and update_thermal_properties().
dt_fo_
double IJK_Thermal_base::dt_fo_ = 1.e20 protected
Referenced by compute_timestep().
fo_
double IJK_Thermal_base::fo_ = 1. protected
Referenced by compute_timestep(), IJK_Thermal_Subresolution::initialize(), and set_param().
cp_liquid_
double IJK_Thermal_base::cp_liquid_ = -123. protected
Referenced by IJK_Thermal_cut_cell::add_temperature_diffusion(), add_temperature_source(), IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), associer_milieu_base(), calculer_energies(), IJK_Thermal_Subresolution::complete_convective_flux_frame_of_reference(), IJK_Thermal_Subresolution::complete_field_thermal_wake_slice_ij_convection(), IJK_Thermal_Subresolution::compute_diffusion_increment(), IJK_Thermal_Onefluid::compute_dT_rustine(), IJK_Thermal_Subresolution::compute_Nusselt_spherical_diffusion(), compute_rho_cp_u_mean(), IJK_Thermal_Onefluid::compute_rho_cp_u_mean(), IJK_Thermal_Onefluid::compute_T_rust(), IJK_Thermal_Onefluid::compute_temperature_convection_conservative(), compute_temperature_dimensionless_theta_mean(), IJK_Thermal_Onefluid::compute_temperature_dimensionless_theta_mean(), IJK_Thermal_Subresolution::compute_temperature_init(), compute_timestep(), compute_variable_wall_temperature(), IJK_Thermal_Subresolution::find_time_dichotomy_derivative(), IJK_Thermal_Subresolution::find_time_dichotomy_integral(), IJK_Thermal_Subresolution::generate_expression_temperature_ini(), IJK_Thermal_Onefluid::get_rho_cp_ijk(), get_rho_cp_u_ijk(), IJK_Thermal_Subresolution::get_time_inflection_derivative(), IJK_Thermal_Subresolution::initialize(), IJK_Thermal_Subresolution::interpolate_convective_term_on_downstream_line(), IJK_Thermal_Multiple_Subresolutions::readOn(), IJK_Thermal_cut_cell::update_thermal_properties(), and IJK_Thermal_Onefluid::update_thermal_properties().
cp_vapour_
double IJK_Thermal_base::cp_vapour_ = -123. protected
Referenced by IJK_Thermal_cut_cell::add_temperature_diffusion(), add_temperature_source(), associer_milieu_base(), calculer_energies(), IJK_Thermal_Onefluid::compute_dT_rustine(), IJK_Thermal_Onefluid::compute_rho_cp_u_mean(), IJK_Thermal_Onefluid::compute_T_rust(), IJK_Thermal_Onefluid::compute_temperature_convection_conservative(), IJK_Thermal_Onefluid::compute_temperature_dimensionless_theta_mean(), compute_timestep(), IJK_Thermal_Onefluid::get_rho_cp_ijk(), IJK_Thermal_Subresolution::initialize(), IJK_Thermal_Multiple_Subresolutions::readOn(), IJK_Thermal_cut_cell::update_thermal_properties(), and IJK_Thermal_Onefluid::update_thermal_properties().
lambda_liquid_
double IJK_Thermal_base::lambda_liquid_ = -123. protected
Referenced by IJK_Thermal_cut_cell::add_temperature_diffusion(), associer_milieu_base(), calculer_temperature_adimensionnelle_theta(), compute_boundary_conditions_thermal(), compute_interfacial_temperature2(), IJK_Thermal_Subresolution::compute_Nusselt_spherical_diffusion(), IJK_Thermal_Subresolution::compute_temperature_init(), compute_timestep(), IJK_Thermal_Subresolution::find_time_dichotomy_derivative(), IJK_Thermal_Subresolution::find_time_dichotomy_integral(), IJK_Thermal_Subresolution::generate_expression_temperature_ini(), IJK_Thermal_Subresolution::get_time_inflection_derivative(), IJK_Thermal_cut_cell::initialize(), IJK_Thermal_Subresolution::initialize(), IJK_Thermal_cut_cell::perform_thermal_step(), IJK_Thermal_Multiple_Subresolutions::readOn(), IJK_Thermal_cut_cell::update_thermal_properties(), and IJK_Thermal_Onefluid::update_thermal_properties().
lambda_vapour_
double IJK_Thermal_base::lambda_vapour_ = -123. protected
Referenced by associer_milieu_base(), compute_interfacial_temperature2(), compute_timestep(), IJK_Thermal_cut_cell::initialize(), IJK_Thermal_Subresolution::initialize(), IJK_Thermal_cut_cell::perform_thermal_step(), IJK_Thermal_Multiple_Subresolutions::readOn(), IJK_Thermal_cut_cell::update_thermal_properties(), and IJK_Thermal_Onefluid::update_thermal_properties().
uniform_lambda_
double IJK_Thermal_base::uniform_lambda_ = 0. protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), IJK_Thermal_Subresolution::complete_field_thermal_wake_slice_ij_diffusion(), IJK_One_Dimensional_Subproblems::compute_overall_bubbles_quantities(), IJK_Thermal_Onefluid::initialize(), IJK_Thermal_Subresolution::initialize(), IJK_Thermal_Subresolution::interpolate_diffusive_term_on_downstream_line(), and IJK_Thermal_Multiple_Subresolutions::readOn().
uniform_alpha_
double IJK_Thermal_base::uniform_alpha_ = 0. protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), IJK_One_Dimensional_Subproblems::compute_overall_bubbles_quantities(), IJK_Thermal_Subresolution::initialize(), and IJK_Thermal_Multiple_Subresolutions::readOn().
prandtl_number_
double IJK_Thermal_base::prandtl_number_ = 0. protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), IJK_One_Dimensional_Subproblems::associate_variables_for_post_processing(), and IJK_Thermal_Subresolution::initialize().
boundary_conditions_
Boundary_Conditions_Thermique IJK_Thermal_base::boundary_conditions_ protected
Referenced by IJK_Thermal_cut_cell::add_temperature_diffusion(), add_temperature_source(), compute_boundary_conditions_thermal(), printOn(), and set_param().
boundary_flux_kmin_
IJK_Field_local_double IJK_Thermal_base::boundary_flux_kmin_ protected
Referenced by add_temperature_diffusion(), IJK_Thermal_cut_cell::add_temperature_diffusion(), compute_boundary_conditions_thermal(), compute_temperature_diffusive_fluxes(), compute_temperature_hessian_diag_elem(), and get_boundary_fluxes().
boundary_flux_kmax_
IJK_Field_local_double IJK_Thermal_base::boundary_flux_kmax_ protected
Referenced by add_temperature_diffusion(), IJK_Thermal_cut_cell::add_temperature_diffusion(), compute_boundary_conditions_thermal(), compute_temperature_diffusive_fluxes(), compute_temperature_hessian_diag_elem(), and get_boundary_fluxes().
expression_T_init_
Nom IJK_Thermal_base::expression_T_init_ = "??" protected
Referenced by compute_temperature_init(), IJK_Thermal_cut_cell::compute_temperature_init(), initialize(), IJK_Thermal_cut_cell::initialize(), IJK_Thermal_cut_cell::recompute_temperature_init(), and set_param().
upstream_temperature_
double IJK_Thermal_base::upstream_temperature_ = -1.1e20 protected
Referenced by calculer_dT(), printOn(), and set_param().
nb_diam_upstream_
double IJK_Thermal_base::nb_diam_upstream_ = 0 protected
Referenced by calculer_dT(), printOn(), and set_param().
side_temperature_
int IJK_Thermal_base::side_temperature_ = 0 protected
Referenced by printOn(), and set_param().
stencil_side_
int IJK_Thermal_base::stencil_side_ = 0 protected
Referenced by printOn(), and set_param().
fichier_reprise_temperature_
Nom IJK_Thermal_base::fichier_reprise_temperature_ = "??" protected
Referenced by get_fichier_reprise(), get_fichier_sauvegarde(), initialize(), IJK_Thermal_cut_cell::initialize(), initialize_switch(), lire_temperature(), IJK_Thermal_cut_cell::lire_temperature(), printOn(), sauvegarder_temperature(), IJK_Thermal_cut_cell::sauvegarder_temperature(), set_fichier_reprise(), set_fichier_sauvegarde(), and set_param().
timestep_reprise_temperature_
int IJK_Thermal_base::timestep_reprise_temperature_ = 1 protected
Referenced by lire_temperature(), IJK_Thermal_cut_cell::lire_temperature(), printOn(), sauvegarder_temperature(), IJK_Thermal_cut_cell::sauvegarder_temperature(), and set_param().
rank_reprise_temperature_
int IJK_Thermal_base::rank_reprise_temperature_ = -1 protected
Referenced by lire_temperature(), IJK_Thermal_cut_cell::lire_temperature(), printOn(), sauvegarder_temperature(), and set_param().
expression_source_temperature_
Nom IJK_Thermal_base::expression_source_temperature_ protected
Referenced by calculer_source_temperature_ana(), and set_param().
type_T_source_
Nom IJK_Thermal_base::type_T_source_ = "??" protected
Referenced by add_temperature_source(), initialize(), printOn(), IJK_Thermal_cut_cell::printOn(), IJK_Thermal_Onefluid::printOn(), and set_param().
lambda_variable_
int IJK_Thermal_base::lambda_variable_ = 0 protected
Referenced by add_temperature_source(), IJK_Thermal_cut_cell::printOn(), IJK_Thermal_Onefluid::printOn(), and set_param().
wall_flux_
int IJK_Thermal_base::wall_flux_ = 0 protected
Referenced by calculer_temperature_adimensionnelle_theta(), calculer_temperature_physique_T(), initialize(), printOn(), and set_param().
source_temperature_
IJK_Field_double IJK_Thermal_base::source_temperature_ protected
Referenced by add_temperature_source(), calculer_source_temperature_ana(), initialize(), and posttraiter_champs_instantanes_thermal().
source_temperature_v_
IJK_Field_double IJK_Thermal_base::source_temperature_v_ protected
Referenced by initialize().
source_temperature_l_
IJK_Field_double IJK_Thermal_base::source_temperature_l_ protected
Referenced by initialize().
d_source_Tl_
IJK_Field_double IJK_Thermal_base::d_source_Tl_ protected
Referenced by initialize().
d_source_Tv_
IJK_Field_double IJK_Thermal_base::d_source_Tv_ protected
Referenced by initialize().
dTl_
double IJK_Thermal_base::dTl_ = 0. protected
dTv_
double IJK_Thermal_base::dTv_ = 1. protected
Tl_
double IJK_Thermal_base::Tl_ = 0. protected
Tv_
double IJK_Thermal_base::Tv_ = 1. protected
Tv0_
double IJK_Thermal_base::Tv0_ = 1. protected
Referenced by calculer_temperature_adim_bulles().
kl_
double IJK_Thermal_base::kl_ = -100000000000000. protected
Referenced by printOn(), and set_param().
kv_
double IJK_Thermal_base::kv_ = -200000000000000. protected
Referenced by printOn(), and set_param().
T0v_
double IJK_Thermal_base::T0v_ = 1. protected
Referenced by printOn(), and set_param().
T0l_
double IJK_Thermal_base::T0l_ = 0. protected
Referenced by printOn(), and set_param().
source_temperature_ana_
IJK_Field_double IJK_Thermal_base::source_temperature_ana_ protected
Referenced by calculer_source_temperature_ana(), and initialize().
ecart_source_t_ana_
IJK_Field_double IJK_Thermal_base::ecart_source_t_ana_ protected
Referenced by calculer_source_temperature_ana(), and initialize().
temperature_physique_T_
IJK_Field_double IJK_Thermal_base::temperature_physique_T_ protected
Referenced by calculer_temperature_physique_T(), and initialize().
temperature_adimensionnelle_theta_
IJK_Field_double IJK_Thermal_base::temperature_adimensionnelle_theta_ protected
Referenced by calculer_temperature_adimensionnelle_theta(), compute_temperature_dimensionless_theta_mean(), IJK_Thermal_Onefluid::compute_temperature_dimensionless_theta_mean(), get_temperature_adim_theta(), initialize(), and posttraiter_champs_instantanes_thermal().
temperature_adim_bulles_
IJK_Field_double IJK_Thermal_base::temperature_adim_bulles_ protected
Referenced by calculer_temperature_adim_bulles(), get_temperature_adim_bulles(), and initialize().
diff_temperature_negligible_
int IJK_Thermal_base::diff_temperature_negligible_ = 0 protected
Referenced by add_temperature_diffusion(), IJK_Thermal_cut_cell::add_temperature_diffusion(), calculer_dT(), IJK_Thermal_Subresolution::compare_fluxes_thermal_subproblems(), IJK_Thermal_Subresolution::compute_convective_diffusive_fluxes_face_centre(), compute_timestep(), IJK_Thermal_Subresolution::correct_operators_for_visu(), initialize(), IJK_Thermal_Subresolution::initialize(), IJK_Thermal_cut_cell::perform_thermal_step(), printOn(), and set_param().
conv_temperature_negligible_
int IJK_Thermal_base::conv_temperature_negligible_ = 0 protected
Referenced by calculer_dT(), IJK_Thermal_Subresolution::compare_fluxes_thermal_subproblems(), IJK_Thermal_Subresolution::compute_convective_diffusive_fluxes_face_centre(), compute_temperature_convection(), IJK_Thermal_Onefluid::compute_temperature_convection_conservative(), IJK_Thermal_cut_cell::compute_temperature_convection_cut_cell(), IJK_Thermal_Subresolution::correct_operators_for_visu(), initialize(), IJK_Thermal_Subresolution::initialize(), IJK_Thermal_cut_cell::perform_thermal_step(), printOn(), and set_param().
type_temperature_convection_form_
int IJK_Thermal_base::type_temperature_convection_form_ = 1 protected
Referenced by calculer_dT(), initialize(), IJK_Thermal_cut_cell::initialize(), IJK_Thermal_Onefluid::initialize(), set_param(), and update_thermal_properties().
temperature_convection_op_
Operateur_IJK_elem_conv IJK_Thermal_base::temperature_convection_op_ protected
Referenced by IJK_Thermal_Onefluid::compute_T_rust(), compute_temperature_convection(), IJK_Thermal_cut_cell::compute_temperature_convection_cut_cell(), initialize(), IJK_Thermal_cut_cell::initialize(), IJK_Thermal_Subresolution::initialize(), IJK_Thermal_cut_cell::perform_thermal_step(), printOn(), and set_param().
rho_cp_convection_op_
Operateur_IJK_elem_conv IJK_Thermal_base::rho_cp_convection_op_ protected
Referenced by initialize().
temperature_diffusion_op_
Operateur_IJK_elem_diff IJK_Thermal_base::temperature_diffusion_op_ protected
Referenced by add_temperature_diffusion(), IJK_Thermal_cut_cell::add_temperature_diffusion(), IJK_Thermal_Onefluid::add_temperature_diffusion(), IJK_Thermal_Subresolution::compute_diffusion_increment(), initialize(), IJK_Thermal_cut_cell::initialize(), IJK_Thermal_Onefluid::initialize(), IJK_Thermal_Subresolution::initialize(), IJK_Thermal_cut_cell::perform_thermal_step(), printOn(), and set_param().
div_coeff_grad_T_raw_
IJK_Field_vector3_double IJK_Thermal_base::div_coeff_grad_T_raw_ protected
Referenced by IJK_Thermal_Subresolution::compare_fluxes_thermal_subproblems(), compute_temperature_diffusive_fluxes(), get_div_coeff_grad_T_diffusive_fluxes(), and initialize().
div_coeff_grad_T_volume_
std::shared_ptr<IJK_Field_double> IJK_Thermal_base::div_coeff_grad_T_volume_ protected
Referenced by add_temperature_diffusion(), IJK_Thermal_cut_cell::add_temperature_diffusion(), IJK_Thermal_Onefluid::compute_diffusion_increment(), IJK_Thermal_Subresolution::compute_diffusion_increment(), IJK_Thermal_Subresolution::correct_operators_for_visu(), IJK_Thermal_Subresolution::correct_temperature_for_visu(), get_div_lambda_grad_T_volume(), IJK_Thermal_base(), and initialize().
div_coeff_grad_T_
IJK_Field_double IJK_Thermal_base::div_coeff_grad_T_ protected
Referenced by IJK_Thermal_Subresolution::compute_diffusion_increment(), IJK_Thermal_Subresolution::correct_temperature_for_visu(), get_div_lambda_grad_T(), and initialize().
rho_cp_u_T_convective_raw_
IJK_Field_vector3_double IJK_Thermal_base::rho_cp_u_T_convective_raw_ protected
Referenced by IJK_Thermal_Subresolution::compare_fluxes_thermal_subproblems(), compute_temperature_convective_fluxes(), get_rho_cp_u_T_convective_fluxes(), and initialize().
u_T_convective_volume_
IJK_Field_double IJK_Thermal_base::u_T_convective_volume_ protected
Referenced by compute_temperature_convection(), IJK_Thermal_cut_cell::compute_temperature_convection_cut_cell(), IJK_Thermal_Subresolution::correct_operators_for_visu(), IJK_Thermal_Subresolution::correct_temperature_for_visu(), get_u_T_convective_volume(), and initialize().
u_T_convective_
IJK_Field_double IJK_Thermal_base::u_T_convective_ protected
Referenced by compute_temperature_convection(), IJK_Thermal_Subresolution::correct_temperature_for_visu(), get_u_T_convective(), and initialize().
temperature_grad_flux_op_quick_
OpGradFluxQuickIJKScalar_double IJK_Thermal_base::temperature_grad_flux_op_quick_ protected
Referenced by compute_temperature_convective_fluxes(), and initialize().
temperature_grad_op_centre_
OpGradCentre2IJKScalar_double IJK_Thermal_base::temperature_grad_op_centre_ protected
Referenced by compute_temperature_gradient_elem(), compute_temperature_hessian_cross_elem(), and initialize().
temperature_hess_op_centre_
OpHessCentre2IJKScalar_double IJK_Thermal_base::temperature_hess_op_centre_ protected
Referenced by compute_temperature_hessian_diag_elem(), and initialize().
temperature_hess_flux_op_centre_
OpHessFluxCentre2IJKScalar_double IJK_Thermal_base::temperature_hess_flux_op_centre_ protected
Referenced by compute_temperature_diffusive_fluxes(), initialize(), and IJK_Thermal_Subresolution::initialize().
vol_
double IJK_Thermal_base::vol_ = 0. protected
Referenced by IJK_Thermal_cut_cell::add_temperature_diffusion(), add_temperature_source(), compute_cell_volume(), IJK_Thermal_Onefluid::compute_diffusion_increment(), IJK_Thermal_Subresolution::compute_diffusion_increment(), IJK_Thermal_Subresolution::compute_mean_liquid_temperature(), compute_temperature_convection(), IJK_Thermal_cut_cell::compute_temperature_convection_cut_cell(), IJK_Thermal_Subresolution::evaluate_total_liquid_absolute_parameter(), and IJK_Thermal_Subresolution::evaluate_total_liquid_parameter_squared().
min_delta_xyz_
double IJK_Thermal_base::min_delta_xyz_ = 0. protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), and compute_min_cell_delta().
cell_diagonal_
double IJK_Thermal_base::cell_diagonal_ = 0. protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), compute_cell_diagonal(), IJK_Thermal_Subresolution::compute_ghost_cell_numbers_for_subproblems(), IJK_Thermal_Subresolution::compute_overall_probes_parameters(), and IJK_Thermal_Subresolution::get_probes_length().
ghost_cells_
int IJK_Thermal_base::ghost_cells_ = 4 protected
Referenced by compute_ghost_cell_numbers_for_subproblems(), IJK_Thermal_Subresolution::compute_ghost_cell_numbers_for_subproblems(), get_ghost_cells(), initialize(), IJK_Thermal_cut_cell::initialize(), and IJK_Thermal_Subresolution::initialize().
rho_cp_
IJK_Field_double IJK_Thermal_base::rho_cp_ protected
Referenced by IJK_Thermal_Onefluid::compute_diffusion_increment(), IJK_Thermal_Onefluid::compute_rho_cp_u_mean(), IJK_Thermal_Onefluid::compute_temperature_dimensionless_theta_mean(), IJK_Thermal_Onefluid::get_rho_cp_ijk(), initialize(), IJK_Thermal_cut_cell::initialize(), IJK_Thermal_Onefluid::initialize(), update_thermal_properties(), IJK_Thermal_cut_cell::update_thermal_properties(), and IJK_Thermal_Onefluid::update_thermal_properties().
rho_cp_T_
IJK_Field_double IJK_Thermal_base::rho_cp_T_ protected
Referenced by initialize(), IJK_Thermal_cut_cell::initialize(), IJK_Thermal_Onefluid::initialize(), and update_thermal_properties().
div_rho_cp_T_
IJK_Field_double IJK_Thermal_base::div_rho_cp_T_ protected
Referenced by initialize().
temperature_
std::shared_ptr<IJK_Field_double> IJK_Thermal_base::temperature_ protected
Referenced by add_temperature_diffusion(), IJK_Thermal_cut_cell::add_temperature_diffusion(), add_temperature_source(), IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), calculer_dT(), calculer_ecart_T_ana(), calculer_energies(), calculer_temperature_adim_bulles(), calculer_temperature_adimensionnelle_theta(), calculer_temperature_physique_T(), IJK_Thermal_Subresolution::clip_max_temperature_values(), IJK_Thermal_Subresolution::clip_min_temperature_values(), IJK_Thermal_Subresolution::complete_field_thermal_wake_slice_ij_convection(), IJK_Thermal_Subresolution::complete_field_thermal_wake_slice_ij_diffusion(), IJK_Thermal_Subresolution::complete_field_thermal_wake_slice_ij_indices_coords(), IJK_Thermal_Subresolution::complete_field_thermal_wake_slice_ij_temperature(), IJK_Thermal_Subresolution::complete_field_thermal_wake_slice_ij_velocity(), compute_boundary_conditions_thermal(), compute_eulerian_grad_T_interface(), compute_eulerian_temperature_ghost(), compute_global_energy(), IJK_Thermal_Subresolution::compute_mean_liquid_temperature(), IJK_Thermal_Subresolution::compute_quasi_static_spherical_diffusion_expression(), IJK_Thermal_Onefluid::compute_T_rust(), IJK_Thermal_Subresolution::compute_temperature_cell_centres_first_correction(), compute_temperature_convection(), compute_temperature_convective_fluxes(), compute_temperature_diffusive_fluxes(), compute_temperature_gradient_elem(), compute_temperature_hessian_cross_elem(), compute_temperature_hessian_diag_elem(), compute_temperature_init(), IJK_Thermal_Subresolution::compute_thermal_subproblems(), compute_variable_wall_temperature(), IJK_Thermal_Subresolution::correct_temperature_for_eulerian_fluxes(), IJK_Thermal_Subresolution::correct_temperature_for_visu(), IJK_Thermal_Subresolution::enforce_periodic_temperature_boundary_value(), IJK_Thermal_Onefluid::euler_rustine_step(), euler_time_step(), IJK_Thermal_Subresolution::find_points_on_proc(), get_temperature(), IJK_Thermal_base(), IJK_Thermal_Subresolution::initialise_thermal_line_points(), IJK_Thermal_Subresolution::initialise_thermal_subproblems(), initialize(), IJK_Thermal_Onefluid::initialize(), IJK_Thermal_Subresolution::initialize(), initialize_switch(), IJK_Thermal_Subresolution::interpolate_convective_term_on_downstream_line(), IJK_Thermal_Subresolution::interpolate_diffusive_term_on_downstream_line(), IJK_Thermal_Subresolution::interpolate_temperature_on_downstream_line(), IJK_Thermal_Subresolution::interpolate_velocity_on_downstream_line(), lire_temperature(), IJK_Thermal_cut_cell::lire_temperature(), IJK_Thermal_cut_cell::perform_thermal_step(), IJK_Thermal_Subresolution::post_process_thermal_wake_slice_index_dir(), IJK_Thermal_Subresolution::replace_temperature_cell_centres_neighbours(), IJK_Thermal_Onefluid::rk3_rustine_sub_step(), rk3_sub_step(), sauvegarder_temperature(), IJK_Thermal_cut_cell::sauvegarder_temperature(), IJK_Thermal_Subresolution::set_field_T_ana(), IJK_Thermal_Subresolution::set_field_temperature_per_bubble(), set_temperature(), IJK_Thermal_Subresolution::store_temperature_before_extrapolation(), and update_thermal_properties().
temperature_for_ini_per_bubble_
IJK_Field_double IJK_Thermal_base::temperature_for_ini_per_bubble_ protected
Referenced by IJK_Thermal_Subresolution::compute_temperature_init(), initialize(), and IJK_Thermal_Subresolution::set_field_temperature_per_bubble().
temperature_before_extrapolation_
IJK_Field_double IJK_Thermal_base::temperature_before_extrapolation_ protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), get_temperature_before_extrapolation(), IJK_Thermal_Subresolution::initialize(), and IJK_Thermal_Subresolution::store_temperature_before_extrapolation().
d_temperature_
std::shared_ptr<IJK_Field_double> IJK_Thermal_base::d_temperature_ protected
Referenced by add_temperature_source(), calculer_dT(), calculer_temperature_physique_T(), IJK_Thermal_Subresolution::complete_field_thermal_wake_slice_ij_temperature_incr(), compute_cell_volume(), IJK_Thermal_Onefluid::compute_diffusion_increment(), IJK_Thermal_Subresolution::compute_diffusion_increment(), compute_min_cell_delta(), compute_temperature_convection(), IJK_Thermal_Onefluid::compute_temperature_convection_conservative(), compute_temperature_convective_fluxes(), IJK_Thermal_Subresolution::correct_temperature_increment_for_interface_leaving_cell(), euler_time_step(), IJK_Thermal_base(), initialize(), IJK_Thermal_Subresolution::interpolate_temperature_increment_on_downstream_line(), rk3_sub_step(), and IJK_Thermal_Subresolution::set_zero_temperature_increment().
RK3_F_temperature_
std::shared_ptr<IJK_Field_double> IJK_Thermal_base::RK3_F_temperature_ protected
Referenced by IJK_Thermal_base(), initialize(), and rk3_sub_step().
storage_
IJK_Field_vector3_double IJK_Thermal_base::storage_ protected
Referenced by initialize().
calculate_local_energy_
int IJK_Thermal_base::calculate_local_energy_ = 0 protected
Referenced by initialize(), printOn(), set_param(), and update_thermal_properties().
conserv_energy_global_
int IJK_Thermal_base::conserv_energy_global_ = 0 protected
Referenced by get_conserv_energy_global(), IJK_Thermal_cut_cell::IJK_Thermal_cut_cell(), IJK_Thermal_Onefluid::IJK_Thermal_Onefluid(), IJK_Thermal_cut_cell::initialize(), IJK_Thermal_Onefluid::initialize(), IJK_Thermal_cut_cell::printOn(), IJK_Thermal_Onefluid::printOn(), set_param(), and update_thermal_properties().
temperature_ft_
IJK_Field_double IJK_Thermal_base::temperature_ft_ protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), compute_eulerian_grad_T_interface(), compute_eulerian_temperature_ghost(), compute_interfacial_temperature2(), get_temperature_ft(), initialize(), IJK_Thermal_cut_cell::initialize(), and IJK_Thermal_cut_cell::perform_thermal_step().
expression_T_ana_
Nom IJK_Thermal_base::expression_T_ana_ = "??" protected
Referenced by calculer_ecart_T_ana(), get_IJK_field(), printOn(), set_field_T_ana(), and set_param().
liste_post_instantanes_
Motcles IJK_Thermal_base::liste_post_instantanes_ protected
Referenced by associer(), calculer_gradient_temperature(), calculer_source_temperature_ana(), IJK_Thermal_Subresolution::compute_diffusion_increment(), IJK_Thermal_Subresolution::correct_temperature_for_visu(), initialize(), IJK_Thermal_Subresolution::set_field_T_ana(), and source_callback().
temperature_ana_
IJK_Field_double IJK_Thermal_base::temperature_ana_ protected
Referenced by calculer_ecart_T_ana(), get_IJK_field(), get_temperature_ana(), initialize(), set_field_T_ana(), and IJK_Thermal_Subresolution::set_field_T_ana().
ecart_t_ana_
IJK_Field_double IJK_Thermal_base::ecart_t_ana_ protected
Referenced by calculer_ecart_T_ana(), get_ecart_t_ana(), initialize(), and IJK_Thermal_Subresolution::set_field_T_ana().
ecart_t_ana_rel_
IJK_Field_double IJK_Thermal_base::ecart_t_ana_rel_ protected
Referenced by get_ecart_t_ana_rel(), initialize(), and IJK_Thermal_Subresolution::set_field_T_ana().
grad_T_
IJK_Field_vector3_double IJK_Thermal_base::grad_T_ protected
Referenced by get_grad_T(), get_gradient_temperature(), and initialize().
calulate_grad_T_
int IJK_Thermal_base::calulate_grad_T_ = 0 protected
Referenced by calculer_gradient_temperature(), initialize(), and IJK_Thermal_Subresolution::initialize().
rho_cp_post_
int IJK_Thermal_base::rho_cp_post_ = 0 protected
Referenced by IJK_Thermal_Onefluid::IJK_Thermal_Onefluid(), initialize(), IJK_Thermal_cut_cell::initialize(), IJK_Thermal_Onefluid::initialize(), update_thermal_properties(), and IJK_Thermal_Onefluid::update_thermal_properties().
ghost_fluid_
int IJK_Thermal_base::ghost_fluid_ = 0 protected
Referenced by compute_eulerian_temperature_ghost(), IJK_Thermal_Subresolution::correct_temperature_increment_for_interface_leaving_cell(), IJK_Thermal_Multiple_Subresolutions::correct_temperature_vapour_for_eulerian_fluxes(), get_ghost_fluid_flag(), initialize(), IJK_Thermal_Multiple_Subresolutions::initialize(), IJK_Thermal_Subresolution::initialize(), printOn(), IJK_Thermal_Subresolution::readOn(), and set_param().
n_iter_distance_
int IJK_Thermal_base::n_iter_distance_ = 3 protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), IJK_Thermal_Subresolution::compute_convective_diffusive_fluxes_face_centre(), printOn(), propagate_eulerian_grad_T_interface(), retrieve_ghost_fluid_params(), and set_param().
gfm_recompute_field_ini_
int IJK_Thermal_base::gfm_recompute_field_ini_ = 1 protected
Referenced by propagate_eulerian_grad_T_interface().
gfm_zero_neighbour_value_mean_
int IJK_Thermal_base::gfm_zero_neighbour_value_mean_ = 0 protected
Referenced by propagate_eulerian_grad_T_interface().
gfm_vapour_mixed_only_
int IJK_Thermal_base::gfm_vapour_mixed_only_ = 1 protected
Referenced by initialize(), and propagate_eulerian_grad_T_interface().
gfm_vapour_liquid_vapour_
int IJK_Thermal_base::gfm_vapour_liquid_vapour_ = 0 protected
Referenced by initialize(), and set_param().
gfm_smooth_factor_
int IJK_Thermal_base::gfm_smooth_factor_ = 20 protected
Referenced by printOn(), propagate_eulerian_grad_T_interface(), and set_param().
avoid_gfm_parallel_calls_
int IJK_Thermal_base::avoid_gfm_parallel_calls_ = 0 protected
Referenced by printOn(), retrieve_ghost_fluid_params(), and set_param().
compute_distance_
int IJK_Thermal_base::compute_distance_ = 0 protected
Referenced by initialize(), IJK_Thermal_Multiple_Subresolutions::initialize(), IJK_Thermal_Subresolution::initialize(), and retrieve_ghost_fluid_params().
compute_curvature_
int IJK_Thermal_base::compute_curvature_ = 0 protected
Referenced by initialize(), IJK_Thermal_Subresolution::initialize(), and retrieve_ghost_fluid_params().
compute_grad_T_interface_
int IJK_Thermal_base::compute_grad_T_interface_ = 0 protected
Referenced by compute_eulerian_grad_T_interface(), initialize(), IJK_Thermal_Subresolution::initialize(), and propagate_eulerian_grad_T_interface().
bounding_box_
const DoubleTab* IJK_Thermal_base::bounding_box_ = nullptr protected
Referenced by compute_eulerian_bounding_box_fill_compo().
min_max_larger_box_
const DoubleTab* IJK_Thermal_base::min_max_larger_box_ = nullptr protected
Referenced by compute_eulerian_bounding_box_fill_compo().
ghost_fluid_fields_
const IJK_Ghost_Fluid_Fields* IJK_Thermal_base::ghost_fluid_fields_ = nullptr protected
Referenced by associer_ghost_fluid_fields(), get_bary(), get_eulerian_curvature_ft(), get_eulerian_curvature_ns(), get_eulerian_distance_ft(), get_eulerian_distance_ns(), get_interfacial_area_ft(), get_interfacial_area_ns(), get_normal_vector_ft(), get_normal_vector_ns(), get_normal_vector_ns_normed(), and initialize().
eulerian_distance_ft_
const IJK_Field_double* IJK_Thermal_base::eulerian_distance_ft_ = nullptr protected
Referenced by compute_eulerian_grad_T_interface(), compute_eulerian_temperature_ghost(), initialize(), and propagate_eulerian_grad_T_interface().
eulerian_distance_ns_
const IJK_Field_double* IJK_Thermal_base::eulerian_distance_ns_ = nullptr protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), IJK_One_Dimensional_Subproblems::associate_sub_problem_to_inputs(), compute_eulerian_grad_T_interface(), compute_eulerian_temperature_ghost(), and initialize().
eulerian_normal_vectors_ft_
const IJK_Field_vector3_double* IJK_Thermal_base::eulerian_normal_vectors_ft_ = nullptr protected
Referenced by initialize().
eulerian_facets_barycentre_ft_
const IJK_Field_vector3_double* IJK_Thermal_base::eulerian_facets_barycentre_ft_ = nullptr protected
Referenced by initialize().
eulerian_normal_vectors_ns_
const IJK_Field_vector3_double* IJK_Thermal_base::eulerian_normal_vectors_ns_ = nullptr protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), IJK_One_Dimensional_Subproblems::associate_sub_problem_to_inputs(), and initialize().
eulerian_normal_vectors_ns_normed_
const IJK_Field_vector3_double* IJK_Thermal_base::eulerian_normal_vectors_ns_normed_ = nullptr protected
Referenced by compute_temperature_gradient_elem(), initialize(), and IJK_Thermal_Subresolution::initialize().
eulerian_facets_barycentre_ns_
const IJK_Field_vector3_double* IJK_Thermal_base::eulerian_facets_barycentre_ns_ = nullptr protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), IJK_One_Dimensional_Subproblems::associate_sub_problem_to_inputs(), and initialize().
eulerian_curvature_ft_
const IJK_Field_double* IJK_Thermal_base::eulerian_curvature_ft_ = nullptr protected
Referenced by compute_eulerian_grad_T_interface(), compute_eulerian_temperature_ghost(), and initialize().
eulerian_curvature_ns_
const IJK_Field_double* IJK_Thermal_base::eulerian_curvature_ns_ = nullptr protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), IJK_One_Dimensional_Subproblems::associate_sub_problem_to_inputs(), compute_eulerian_grad_T_interface(), compute_eulerian_temperature_ghost(), and initialize().
eulerian_interfacial_area_ft_
const IJK_Field_double* IJK_Thermal_base::eulerian_interfacial_area_ft_ = nullptr protected
Referenced by compute_eulerian_grad_T_interface(), and initialize().
eulerian_interfacial_area_ns_
const IJK_Field_double* IJK_Thermal_base::eulerian_interfacial_area_ns_ = nullptr protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), IJK_One_Dimensional_Subproblems::associate_sub_problem_to_inputs(), compute_eulerian_grad_T_interface(), and initialize().
eulerian_grad_T_interface_ft_
IJK_Field_double IJK_Thermal_base::eulerian_grad_T_interface_ft_ protected
Referenced by compute_eulerian_grad_T_interface(), compute_eulerian_temperature_ghost(), get_grad_T_interface_ft(), initialize(), and propagate_eulerian_grad_T_interface().
eulerian_grad_T_interface_ns_
IJK_Field_double IJK_Thermal_base::eulerian_grad_T_interface_ns_ protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), compute_eulerian_grad_T_interface(), compute_eulerian_temperature_ghost(), IJK_One_Dimensional_Subproblems::compute_overall_bubbles_quantities(), get_grad_T_interface_ns(), initialize(), and propagate_eulerian_grad_T_interface().
compute_grad_T_elem_
int IJK_Thermal_base::compute_grad_T_elem_ = 0 protected
Referenced by compute_temperature_gradient_elem(), initialize(), IJK_Thermal_Subresolution::initialize(), and IJK_Thermal_Subresolution::readOn().
grad_T_elem_
IJK_Field_vector3_double IJK_Thermal_base::grad_T_elem_ protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), IJK_Thermal_Subresolution::complete_field_thermal_wake_slice_ij_convection(), IJK_Thermal_Subresolution::complete_field_thermal_wake_slice_ij_diffusion(), IJK_Thermal_Subresolution::complete_field_thermal_wake_slice_ij_indices_coords(), IJK_Thermal_Subresolution::complete_field_thermal_wake_slice_ij_temperature(), IJK_Thermal_Subresolution::complete_field_thermal_wake_slice_ij_temperature_incr(), IJK_Thermal_Subresolution::complete_field_thermal_wake_slice_ij_velocity(), compute_temperature_gradient_elem(), compute_temperature_hessian_cross_elem(), get_gradient_temperature_elem(), initialize(), IJK_Thermal_Subresolution::interpolate_convective_term_on_downstream_line(), IJK_Thermal_Subresolution::interpolate_diffusive_term_on_downstream_line(), IJK_Thermal_Subresolution::interpolate_temperature_increment_on_downstream_line(), IJK_Thermal_Subresolution::interpolate_temperature_on_downstream_line(), and IJK_Thermal_Subresolution::interpolate_velocity_on_downstream_line().
smooth_grad_T_elem_
int IJK_Thermal_base::smooth_grad_T_elem_ = 0 protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), compute_temperature_gradient_elem(), get_gradient_temperature_elem_smooth(), get_tangential_gradient_temperature_elem_smooth(), get_temperature_elem_smooth(), initialize(), printOn(), and set_param().
grad_T_elem_smooth_
IJK_Field_vector3_double IJK_Thermal_base::grad_T_elem_smooth_ protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), compute_temperature_gradient_elem(), get_gradient_temperature_elem_smooth(), and initialize().
hess_diag_T_elem_
IJK_Field_vector3_double IJK_Thermal_base::hess_diag_T_elem_ protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), compute_temperature_hessian_diag_elem(), get_hessian_diag_temperature_elem(), and initialize().
hess_cross_T_elem_
IJK_Field_vector3_double IJK_Thermal_base::hess_cross_T_elem_ protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), compute_temperature_hessian_cross_elem(), get_hessian_cross_temperature_elem(), and initialize().
facets_barycentre
IJK_Field_vector3_double IJK_Thermal_base::facets_barycentre protected
d_temperature_uncorrected_
IJK_Field_double IJK_Thermal_base::d_temperature_uncorrected_ protected
Referenced by IJK_Thermal_Subresolution::initialize().
div_coeff_grad_T_volume_uncorrected_
IJK_Field_double IJK_Thermal_base::div_coeff_grad_T_volume_uncorrected_ protected
Referenced by IJK_Thermal_Subresolution::initialize().
temperature_convection_op_uncorrected_
Operateur_IJK_elem_conv IJK_Thermal_base::temperature_convection_op_uncorrected_ protected
temperature_diffusion_op_uncorrected_
Operateur_IJK_elem_diff IJK_Thermal_base::temperature_diffusion_op_uncorrected_ protected
compute_hess_T_elem_
int IJK_Thermal_base::compute_hess_T_elem_ = 0 protected
Referenced by initialize(), and IJK_Thermal_Subresolution::initialize().
compute_hess_diag_T_elem_
int IJK_Thermal_base::compute_hess_diag_T_elem_ = 0 protected
Referenced by compute_temperature_hessian_diag_elem(), initialize(), and IJK_Thermal_Subresolution::initialize().
compute_hess_cross_T_elem_
int IJK_Thermal_base::compute_hess_cross_T_elem_ = 0 protected
Referenced by compute_temperature_hessian_cross_elem(), initialize(), and IJK_Thermal_Subresolution::initialize().
mixed_cells_number_
int IJK_Thermal_base::mixed_cells_number_ = 0 protected
compute_eulerian_compo_
int IJK_Thermal_base::compute_eulerian_compo_ = 1 protected
Referenced by compute_eulerian_bounding_box_fill_compo(), initialize(), IJK_Thermal_Subresolution::initialize(), printOn(), and set_param().
spherical_approx_
int IJK_Thermal_base::spherical_approx_ = 1 protected
Referenced by compute_eulerian_grad_T_interface(), compute_eulerian_temperature_ghost(), and initialize().
spherical_exact_
int IJK_Thermal_base::spherical_exact_ = 0 protected
Referenced by initialize(), printOn(), and set_param().
eulerian_compo_connex_ft_
const IJK_Field_double* IJK_Thermal_base::eulerian_compo_connex_ft_ = nullptr protected
Referenced by get_eulerian_compo_connex_ft(), and initialize().
eulerian_compo_connex_ns_
const IJK_Field_double* IJK_Thermal_base::eulerian_compo_connex_ns_ = nullptr protected
Referenced by get_eulerian_compo_connex_ns(), and initialize().
eulerian_compo_connex_ghost_ft_
const IJK_Field_double* IJK_Thermal_base::eulerian_compo_connex_ghost_ft_ = nullptr protected
Referenced by get_eulerian_compo_connex_ghost_ft(), and initialize().
eulerian_compo_connex_ghost_ns_
const IJK_Field_double* IJK_Thermal_base::eulerian_compo_connex_ghost_ns_ = nullptr protected
Referenced by get_eulerian_compo_connex_ghost_ns(), and initialize().
eulerian_compo_connex_from_interface_ft_
const IJK_Field_double* IJK_Thermal_base::eulerian_compo_connex_from_interface_ft_ = nullptr protected
Referenced by get_eulerian_compo_connex_from_interface_ft(), and initialize().
eulerian_compo_connex_from_interface_ns_
const IJK_Field_double* IJK_Thermal_base::eulerian_compo_connex_from_interface_ns_ = nullptr protected
Referenced by get_eulerian_compo_connex_from_interface_ns(), and initialize().
eulerian_compo_connex_from_interface_ghost_ft_
const IJK_Field_double* IJK_Thermal_base::eulerian_compo_connex_from_interface_ghost_ft_ = nullptr protected
Referenced by get_eulerian_compo_connex_from_interface_ghost_ft(), and initialize().
eulerian_compo_connex_from_interface_ghost_ns_
const IJK_Field_double* IJK_Thermal_base::eulerian_compo_connex_from_interface_ghost_ns_ = nullptr protected
Referenced by get_eulerian_compo_connex_from_interface_ghost_ns(), and initialize().
eulerian_compo_connex_from_interface_int_ns_
const IJK_Field_int* IJK_Thermal_base::eulerian_compo_connex_from_interface_int_ns_ = nullptr protected
Referenced by IJK_One_Dimensional_Subproblems::associate_sub_problem_to_inputs(), get_eulerian_compo_connex_int_from_interface_ns(), and initialize().
eulerian_compo_connex_from_interface_ghost_int_ns_
const IJK_Field_int* IJK_Thermal_base::eulerian_compo_connex_from_interface_ghost_int_ns_ = nullptr protected
Referenced by get_eulerian_compo_connex_int_from_interface_ghost_ns(), and initialize().
compute_rising_velocities_
int IJK_Thermal_base::compute_rising_velocities_ = 0 protected
Referenced by get_rising_velocities_parameters(), initialize(), and IJK_Thermal_Subresolution::initialize().
fill_rising_velocities_
int IJK_Thermal_base::fill_rising_velocities_ = 0 protected
Referenced by get_rising_velocities_parameters(), and initialize().
use_bubbles_velocities_from_interface_
int IJK_Thermal_base::use_bubbles_velocities_from_interface_ = 0 protected
Referenced by get_rising_velocities_parameters(), printOn(), and set_param().
use_bubbles_velocities_from_barycentres_
int IJK_Thermal_base::use_bubbles_velocities_from_barycentres_ = 0 protected
Referenced by get_rising_velocities_parameters(), printOn(), and set_param().
liquid_velocity_
const Vecteur3* IJK_Thermal_base::liquid_velocity_ = nullptr protected
Referenced by IJK_One_Dimensional_Subproblems::associate_variables_for_post_processing(), and initialize().
rising_velocity_overall_
const Vecteur3* IJK_Thermal_base::rising_velocity_overall_ = nullptr protected
Referenced by initialize().
rising_velocities_
const ArrOfDouble* IJK_Thermal_base::rising_velocities_ = nullptr protected
Referenced by IJK_One_Dimensional_Subproblems::associate_sub_problem_to_inputs(), IJK_One_Dimensional_Subproblems::associate_variables_for_post_processing(), and initialize().
rising_velocities_from_barycentres_
const ArrOfDouble* IJK_Thermal_base::rising_velocities_from_barycentres_ = nullptr protected
Referenced by IJK_One_Dimensional_Subproblems::associate_variables_for_post_processing(), and initialize().
rising_vectors_
const DoubleTab* IJK_Thermal_base::rising_vectors_ = nullptr protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), IJK_One_Dimensional_Subproblems::associate_sub_problem_to_inputs(), IJK_One_Dimensional_Subproblems::associate_variables_for_post_processing(), and initialize().
rising_vectors_from_barycentres_
const DoubleTab* IJK_Thermal_base::rising_vectors_from_barycentres_ = nullptr protected
Referenced by IJK_One_Dimensional_Subproblems::associate_variables_for_post_processing(), and initialize().
eulerian_rising_velocities_
const IJK_Field_double* IJK_Thermal_base::eulerian_rising_velocities_ = nullptr protected
Referenced by get_eulerian_rising_velocities(), and initialize().
bubbles_volume_
const ArrOfDouble* IJK_Thermal_base::bubbles_volume_ = nullptr protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), IJK_One_Dimensional_Subproblems::associate_variables_for_post_processing(), and compute_eulerian_bounding_box_fill_compo().
bubbles_barycentre_
const DoubleTab* IJK_Thermal_base::bubbles_barycentre_ = nullptr protected
Referenced by IJK_One_Dimensional_Subproblems::associate_sub_problem_to_inputs(), IJK_One_Dimensional_Subproblems::associate_variables_for_post_processing(), compute_eulerian_bounding_box_fill_compo(), and initialize().
bubbles_barycentres_old_
const DoubleTab* IJK_Thermal_base::bubbles_barycentres_old_ = nullptr protected
Referenced by IJK_One_Dimensional_Subproblems::associate_variables_for_post_processing(), and initialize().
bubbles_barycentres_new_
const DoubleTab* IJK_Thermal_base::bubbles_barycentres_new_ = nullptr protected
Referenced by IJK_One_Dimensional_Subproblems::associate_variables_for_post_processing(), and initialize().
dummy_int_vect_
IJK_Field_vector3_int IJK_Thermal_base::dummy_int_vect_ protected
Referenced by get_cell_faces_corrected_bool(), IJK_Thermal_Subresolution::get_cell_faces_corrected_bool(), get_cell_faces_neighbours_corrected_all_bool(), IJK_Thermal_Subresolution::get_cell_faces_neighbours_corrected_all_bool(), get_cell_faces_neighbours_corrected_diag_bool(), IJK_Thermal_Subresolution::get_cell_faces_neighbours_corrected_diag_bool(), get_cell_faces_neighbours_corrected_min_max_bool(), IJK_Thermal_Subresolution::get_cell_faces_neighbours_corrected_min_max_bool(), and initialize().
dummy_double_vect_
IJK_Field_vector3_double IJK_Thermal_base::dummy_double_vect_ protected
Referenced by get_cell_faces_corrected_convective(), IJK_Thermal_Subresolution::get_cell_faces_corrected_convective(), get_cell_faces_corrected_diffusive(), IJK_Thermal_Subresolution::get_cell_faces_corrected_diffusive(), get_cell_faces_neighbours_corrected_convective(), IJK_Thermal_Subresolution::get_cell_faces_neighbours_corrected_convective(), get_cell_faces_neighbours_corrected_convective_frame_of_ref(), IJK_Thermal_Subresolution::get_cell_faces_neighbours_corrected_convective_frame_of_ref(), get_cell_faces_neighbours_corrected_diffusive(), IJK_Thermal_Subresolution::get_cell_faces_neighbours_corrected_diffusive(), get_cell_faces_neighbours_corrected_velocity_temperature(), IJK_Thermal_Subresolution::get_cell_faces_neighbours_corrected_velocity_temperature(), get_div_coeff_grad_T_diffusive_fluxes(), get_gradient_temperature_elem_smooth(), get_interfacial_heat_flux_contrib(), IJK_Thermal_Subresolution::get_interfacial_heat_flux_contrib(), get_interfacial_heat_flux_current(), IJK_Thermal_Subresolution::get_interfacial_heat_flux_current(), get_interfacial_heat_flux_dispatched(), IJK_Thermal_Subresolution::get_interfacial_heat_flux_dispatched(), get_neighbours_faces_weighting_colinearity(), IJK_Thermal_Subresolution::get_neighbours_faces_weighting_colinearity(), get_rho_cp_u_T_convective_fluxes(), get_tangential_gradient_temperature_elem_smooth(), and initialize().
dummy_int_field_
IJK_Field_int IJK_Thermal_base::dummy_int_field_ protected
Referenced by get_cell_neighbours_corrected(), IJK_Thermal_Subresolution::get_cell_neighbours_corrected(), get_cell_neighbours_corrected_trimmed(), IJK_Thermal_Subresolution::get_cell_neighbours_corrected_trimmed(), get_eulerian_compo_connex_int_from_interface_ghost_ns(), get_eulerian_compo_connex_int_from_interface_ns(), and initialize().
dummy_double_field_
IJK_Field_double IJK_Thermal_base::dummy_double_field_ protected
Referenced by get_debug_lrs_cells(), get_eulerian_compo_connex_from_interface_ft(), get_eulerian_compo_connex_from_interface_ghost_ft(), get_eulerian_compo_connex_from_interface_ghost_ns(), get_eulerian_compo_connex_from_interface_ns(), get_eulerian_compo_connex_ft(), get_eulerian_compo_connex_ghost_ft(), get_eulerian_compo_connex_ghost_ns(), get_eulerian_compo_connex_ns(), get_neighbours_temperature_colinearity_weighting(), IJK_Thermal_Subresolution::get_neighbours_temperature_colinearity_weighting(), get_probe_collision_debug_field(), IJK_Thermal_Subresolution::get_probe_collision_debug_field(), get_temperature_cell_neighbours(), IJK_Thermal_Subresolution::get_temperature_cell_neighbours(), get_temperature_cell_neighbours_debug(), IJK_Thermal_Subresolution::get_temperature_cell_neighbours_debug(), get_temperature_elem_smooth(), and initialize().
store_flux_operators_for_energy_balance_
int IJK_Thermal_base::store_flux_operators_for_energy_balance_ = 0 protected
Referenced by IJK_Thermal_Subresolution::compare_fluxes_thermal_subproblems(), IJK_Thermal_Subresolution::complete_convective_flux_frame_of_reference(), compute_temperature_convective_fluxes(), compute_temperature_diffusive_fluxes(), IJK_Thermal_Subresolution::get_cell_faces_neighbours_corrected_convective_frame_of_ref(), IJK_Thermal_Subresolution::get_cell_faces_neighbours_corrected_velocity_temperature(), get_div_coeff_grad_T_diffusive_fluxes(), get_rho_cp_u_T_convective_fluxes(), initialize(), IJK_Thermal_Subresolution::initialize(), printOn(), and set_param().
disable_relative_velocity_energy_balance_
int IJK_Thermal_base::disable_relative_velocity_energy_balance_ = 0 protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), compute_temperature_convective_fluxes(), printOn(), and set_param().
thermal_local_subproblems_interfaces_fields_
IJK_One_Dimensional_Subproblems_Interfaces_Fields IJK_Thermal_base::thermal_local_subproblems_interfaces_fields_ protected
Referenced by associer(), copy_previous_interface_state(), post_process_quantities_from_subresolution(), and IJK_Thermal_Subresolution::set_subproblems_interfaces_fields().
temperature_gaussian_filtered_
IJK_Field_double IJK_Thermal_base::temperature_gaussian_filtered_ protected
Referenced by compute_temperature_gradient_elem(), get_temperature_elem_smooth(), and initialize().
tmp_smoothing_field_
IJK_Field_double IJK_Thermal_base::tmp_smoothing_field_ protected
Referenced by initialize().
grad_T_elem_tangential_
IJK_Field_vector3_double IJK_Thermal_base::grad_T_elem_tangential_ protected
Referenced by compute_temperature_gradient_elem(), get_tangential_gradient_temperature_elem_smooth(), and initialize().
smoothing_numbers_
int IJK_Thermal_base::smoothing_numbers_ = 1 protected
Referenced by compute_temperature_gradient_elem(), printOn(), and set_param().
smoothing_remove_normal_compo_
int IJK_Thermal_base::smoothing_remove_normal_compo_ = 0 protected
Referenced by compute_temperature_gradient_elem(), printOn(), and set_param().
smoothing_use_unique_phase_
int IJK_Thermal_base::smoothing_use_unique_phase_ = 0 protected
Referenced by compute_temperature_gradient_elem(), printOn(), and set_param().
direct_smoothing_factors_
double IJK_Thermal_base::direct_smoothing_factors_[7] = {1.,1.,1.,1.,1.,1.,2.} protected
Referenced by compute_temperature_gradient_elem().
gaussian_smoothing_factors_
double IJK_Thermal_base::gaussian_smoothing_factors_[3][3][3] protected
Initial value:
= {{{1,2,1},
      {2,4,2},
      {1,2,1}
    },
    { {1,4,1},
      {4,8,4},
      {2,4,2}
    },
    { {1,2,1},
      {2,4,2},
      {1,2,1}
    }
  }
Referenced by compute_temperature_gradient_elem().
sharpen_smoothing_factors_
double IJK_Thermal_base::sharpen_smoothing_factors_[3][3][3] protected
Initial value:
= {{{0,0,0},
      {0,-1,0},
      {0,0,0}
    },
    { {0,-1,0},
      {-1,8,-1},
      {0,-1,0}
    },
    { {0,0,0},
      {0,-1,0},
      {0,0,0}
    }
  }