TrioCFD: Op_Diff_EF_base Class Reference
Op_Diff_EF_base Class Reference abstract
#include <Op_Diff_EF_base.h>
Public Member Functions
double calculer_dt_stab () const override
const Type_info * get_info () const override
int impr (Sortie &os) const override
Public Member Functions inherited from Operateur_Diff_base
virtual void associer_diffusivite_pour_pas_de_temps (const Champ_base &)
const Type_info * get_info () const override
Public Member Functions inherited from Operateur_base
void associer_eqn (const Equation_base &)
virtual double calculer_dt_stab () const
virtual void completer ()
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual void mettre_a_jour (double temps)
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Public Member Functions inherited from Op_EF_base
void dimensionner (const Domaine_EF &, const Domaine_Cl_EF &, Matrice_Morse &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Operateur_Diff_base
virtual const Champ_base & diffusivite_pour_pas_de_temps () const
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Op_Diff_EF_base()
Op_Diff_EF_base::Op_Diff_EF_base ()
References Support_Champ_Masse_Volumique::declare_support_masse_volumique().
~Op_Diff_EF_base()
Op_Diff_EF_base::~Op_Diff_EF_base () override
Member Function Documentation
info()
const Type_info * Op_Diff_EF_base::info () static
get_info()
const Type_info * Op_Diff_EF_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
Reimplemented in Op_Dift_EF_base, Op_Dift_EF_Q1, and Op_Dift_EF_Q1_option.
self_cast() [1/2]
Op_Diff_EF_base & Op_Diff_EF_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Op_Diff_EF_base & Op_Diff_EF_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Op_Diff_EF_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
Reimplemented in Op_Dift_EF_base, Op_Dift_EF_Q1, and Op_Dift_EF_Q1_option.
References Objet_U::que_suis_je().
Referenced by Op_Dift_EF_base::printOn().
readOn()
Entree & Op_Diff_EF_base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
Reimplemented in Op_Dift_EF_base, Op_Dift_EF_Q1, and Op_Dift_EF_Q1_option.
Referenced by Op_Dift_EF_base::readOn().
impr()
int Op_Diff_EF_base::impr (Sortie & os) const override virtual
DOES NOTHING - to override in derived classes.
Imprime l'operateur sur un flot de sortie.
Parameters
(Sortie& os)
Returns
(int) renvoie toujours 1
Reimplemented from Operateur_base.
References Op_EF_base::impr().
associer()
void Op_Diff_EF_base::associer (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_cl_dis, const Champ_Inc_base & ch_transporte) override virtual
Implements Operateur_base.
References Operateur_base::flux_bords_, inconnue, la_zcl_EF, le_dom_EF, Domaine_VF::nb_faces_bord(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), and TRUST_Ref< _CLASSE_ >::valeur().
calculer_dt_stab()
double Op_Diff_EF_base::calculer_dt_stab () const override virtual
Calcul dt_stab.
Returns
(double) renvoie toujours 1.e30
Reimplemented from Operateur_base.
Reimplemented in Op_Dift_EF_Q1.
References Domaine_EF::carre_pas_du_maillage(), Domaine_EF::carre_pas_maille(), Operateur_Diff_base::diffusivite(), Operateur_Diff_base::diffusivite_pour_pas_de_temps(), Objet_U::dimension, Domaine_dis_base::domaine(), MorEqn::equation(), Support_Champ_Masse_Volumique::get_champ_masse_volumique(), Support_Champ_Masse_Volumique::has_champ_masse_volumique(), le_dom_EF, Domaine_32_64< _SIZE_ >::les_elems(), Domaine_32_64< _SIZE_ >::les_sommets(), Process::mp_min(), Domaine_dis_base::nb_elem(), nu_, remplir_nu(), TRUST_Ref< _CLASSE_ >::valeur(), and Champ_Proto::valeurs().
remplir_nu()
virtual void Op_Diff_EF_base::remplir_nu (DoubleTab &) const pure virtual
Implemented in Op_Diff_EF, and Op_Dift_EF_Q1.
Referenced by calculer_dt_stab().
Member Data Documentation
info_obj
const Type_info Op_Diff_EF_base::info_obj static
le_dom_EF
TRUST_Ref< Domaine_EF *> Op_Diff_EF_base::le_dom_EF protected
Referenced by Op_Diff_EF::ajouter(), Op_Dift_EF_Q1::ajouter(), Op_Diff_EF::ajouter_bords(), Op_Dift_EF_Q1::ajouter_bords(), Op_Diff_EF::ajouter_contributions_bords(), Op_Dift_EF_Q1::ajouter_contributions_bords(), associer(), Op_Dift_EF_base::calculer_borne_locale(), calculer_dt_stab(), Op_Dift_EF_Q1::calculer_dt_stab(), Op_Diff_EF::dimensionner(), Op_Dift_EF_Q1::dimensionner(), Op_Diff_EF::modifier_pour_Cl(), Op_Dift_EF_Q1::modifier_pour_Cl(), Op_Diff_EF::remplir_nu(), and Op_Dift_EF_Q1::remplir_nu().
la_zcl_EF
TRUST_Ref< Domaine_Cl_EF *> Op_Diff_EF_base::la_zcl_EF protected
Referenced by Op_Diff_EF::ajouter_bords(), Op_Dift_EF_Q1::ajouter_bords(), Op_Diff_EF::ajouter_contribution(), Op_Dift_EF_Q1::ajouter_contribution(), Op_Diff_EF::ajouter_contribution_new(), Op_Dift_EF_Q1::ajouter_contribution_new(), Op_Diff_EF::ajouter_contributions_bords(), Op_Dift_EF_Q1::ajouter_contributions_bords(), Op_Diff_EF::ajouter_new(), Op_Dift_EF_Q1::ajouter_new(), associer(), Op_Diff_EF::dimensionner(), Op_Dift_EF_Q1::dimensionner(), Op_Diff_EF::modifier_pour_Cl(), and Op_Dift_EF_Q1::modifier_pour_Cl().
inconnue
TRUST_Ref< Champ_Inc_base *> Op_Diff_EF_base::inconnue protected
Referenced by associer().
nu_
DoubleTab Op_Diff_EF_base::nu_ mutable protected
Referenced by Op_Diff_EF::ajouter(), Op_Dift_EF_Q1::ajouter(), Op_Diff_EF::ajouter_bords(), Op_Dift_EF_Q1::ajouter_bords(), Op_Diff_EF::ajouter_contribution(), Op_Dift_EF_Q1::ajouter_contribution(), Op_Diff_EF::ajouter_contribution_new(), Op_Dift_EF_Q1::ajouter_contribution_new(), Op_Diff_EF::ajouter_new(), Op_Dift_EF_Q1::ajouter_new(), calculer_dt_stab(), and Op_Dift_EF_Q1::calculer_dt_stab().