TrioCFD: Probleme_base_interface_proto Class Reference
Probleme_base_interface_proto Class Reference
#include <Probleme_base_interface_proto.h>
Member Function Documentation
initTimeStep_impl()
bool Probleme_base_interface_proto::initTimeStep_impl (Probleme_base & pb, double dt)
References Domaine_Cl_dis_base::calculer_coeffs_echange(), Probleme_base::domaine(), Equation_base::domaine_Cl_dis(), dt_defined, dt_validated, Probleme_base::equation(), Nom::getChar(), initialized, Equation_base::initTimeStep(), Milieu_base::initTimeStep(), Schema_Temps_base::initTimeStep(), Probleme_U::le_nom(), Probleme_base::milieu(), Probleme_base::nombre_d_equations(), Probleme_base::schema_temps(), Domaine_base::set_dt(), Debog::set_nom_pb_actuel(), Schema_Temps_base::temps_defaut(), and terminated.
Referenced by Probleme_base::initTimeStep().
solveTimeStep_impl()
bool Probleme_base_interface_proto::solveTimeStep_impl (Probleme_base & pb)
References Domaine_Cl_dis_base::calculer_coeffs_echange(), Equation_base::domaine_Cl_dis(), dt_defined, Probleme_base::equation(), Nom::getChar(), Probleme_U::le_nom(), Probleme_base::nombre_d_equations(), Probleme_base::schema_temps(), Debog::set_nom_pb_actuel(), Probleme_base::solveTimeStep_pbU(), and Schema_Temps_base::temps_defaut().
Referenced by Probleme_base::solveTimeStep().
isStationary_impl()
bool Probleme_base_interface_proto::isStationary_impl (const Probleme_base & pb) const
References dt_validated, Nom::getChar(), Schema_Temps_base::isStationary(), Probleme_U::le_nom(), Probleme_base::schema_temps(), and terminated.
Referenced by Probleme_base::isStationary().
iterateTimeStep_impl()
bool Probleme_base_interface_proto::iterateTimeStep_impl (Probleme_base & pb, bool & converged)
References Domaine_Cl_dis_base::calculer_coeffs_echange(), Probleme_base::domaine(), Equation_base::domaine_Cl_dis(), Probleme_base::domaine_dis(), dt_defined, Probleme_base::equation(), Nom::getChar(), Schema_Temps_base::iterateTimeStep(), Probleme_U::le_nom(), Domaine_base::mettre_a_jour(), Probleme_base::nombre_d_equations(), Probleme_base::schema_temps(), Debog::set_nom_pb_actuel(), and Schema_Temps_base::temps_defaut().
Referenced by Probleme_FTD_IJK_base::iterateTimeStep(), and Probleme_base::iterateTimeStep().
updateGivenFields_impl()
bool Probleme_base_interface_proto::updateGivenFields_impl (Probleme_base & pb)
References Probleme_base::equation(), Probleme_U::le_nom(), Probleme_base::nombre_d_equations(), Debog::set_nom_pb_actuel(), and Equation_base::updateGivenFields().
Referenced by Probleme_base::updateGivenFields().
is_probleme_initialized_impl()
const bool & Probleme_base_interface_proto::is_probleme_initialized_impl () const inline
References initialized.
Referenced by Probleme_base::is_probleme_base_initialized().
initialize_impl()
void Probleme_base_interface_proto::initialize_impl (Probleme_base & pb)
References Probleme_base::domaine(), Probleme_base::domaine_dis(), Nom::getChar(), Probleme_base::init_postraitements(), Domaine_base::initialiser(), Schema_Temps_base::initialize(), initialized, Probleme_U::le_nom(), Probleme_base::preparer_calcul(), Probleme_base::schema_temps(), and Debog::set_nom_pb_actuel().
Referenced by Probleme_base::initialize().
terminate_impl()
void Probleme_base_interface_proto::terminate_impl (Probleme_base & pb)
References dt_defined, Probleme_base::finir(), Nom::getChar(), initialized, Probleme_U::le_nom(), Probleme_base::schema_temps(), Debog::set_nom_pb_actuel(), Schema_Temps_base::terminate(), and terminated.
Referenced by Probleme_base::terminate().
validateTimeStep_impl()
void Probleme_base_interface_proto::validateTimeStep_impl (Probleme_base & pb)
References Probleme_base::allocation(), dt_defined, dt_validated, Nom::getChar(), Probleme_U::le_nom(), Probleme_base::schema_temps(), Debog::set_nom_pb_actuel(), and Schema_Temps_base::validateTimeStep().
Referenced by Probleme_base::validateTimeStep().
abortTimeStep_impl()
void Probleme_base_interface_proto::abortTimeStep_impl (Probleme_base & pb)
References Milieu_base::abortTimeStep(), Schema_Temps_base::abortTimeStep(), dt_defined, Nom::getChar(), Probleme_U::le_nom(), Probleme_base::milieu(), and Probleme_base::schema_temps().
Referenced by Probleme_base::abortTimeStep().
getInputFieldsNames_impl()
void Probleme_base_interface_proto::getInputFieldsNames_impl (const Probleme_base & pb, Noms & noms) const
References TRUST_Vector< _CLASSE_ >::add(), input_fields, and TRUST_List< _CLASSE_ >::size().
Referenced by Probleme_base::getInputFieldsNames().
getOutputFieldsNames_impl()
void Probleme_base_interface_proto::getOutputFieldsNames_impl (const Probleme_base & pb, Noms & noms) const
References TRUST_Vector< _CLASSE_ >::add(), Probleme_base::postraitements(), and TRUST_List< _CLASSE_ >::size().
Referenced by Probleme_base::getOutputFieldsNames().
addInputField_impl()
void Probleme_base_interface_proto::addInputField_impl (Probleme_base & pb, Field_base & f)
References TRUST_List< _CLASSE_ >::add(), Nom::getChar(), input_fields, Field_base::le_nom(), and TRUST_List< _CLASSE_ >::size().
Referenced by Probleme_base::addInputField().
presentTime_impl()
double Probleme_base_interface_proto::presentTime_impl (const Probleme_base & pb) const
References Nom::getChar(), initialized, Probleme_U::le_nom(), Probleme_base::schema_temps(), Debog::set_nom_pb_actuel(), Schema_Temps_base::temps_courant(), and terminated.
Referenced by Probleme_base::presentTime().
computeTimeStep_impl()
double Probleme_base_interface_proto::computeTimeStep_impl (const Probleme_base & pb, bool & stop) const
References Schema_Temps_base::computeTimeStep(), Nom::getChar(), initialized, Probleme_U::le_nom(), Probleme_base::schema_temps(), Debog::set_nom_pb_actuel(), and terminated.
Referenced by Probleme_base::computeTimeStep().
futureTime_impl()
double Probleme_base_interface_proto::futureTime_impl (const Probleme_base & pb) const
References dt_defined, Nom::getChar(), Probleme_U::le_nom(), Schema_Temps_base::nb_valeurs_futures(), Probleme_base::schema_temps(), and Schema_Temps_base::temps_futur().
Referenced by Probleme_base::futureTime().
resetTimeWithDir_impl()
void Probleme_base_interface_proto::resetTimeWithDir_impl (Probleme_base & pb, double time, std::string direname)
References dt_defined, Probleme_base::equation(), Nom::getChar(), Probleme_base::init_postraitements(), Schema_Temps_base::initialize(), initialized, Probleme_U::le_nom(), Probleme_base::milieu(), Probleme_base::nombre_d_equations(), Probleme_base::postraitements(), Probleme_base::postraiter(), Postraitements::resetTime(), Equation_base::resetTime(), Milieu_base::resetTime(), Schema_Temps_base::resetTime(), Probleme_base::schema_temps(), Sortie_Fichier_base::set_root(), Probleme_base::terminate(), and terminated.
Referenced by Probleme_base::resetTime().
findInputField_impl()
TRUST_Ref< Field_base * > Probleme_base_interface_proto::findInputField_impl (const Probleme_base & pb, const Nom & name) const
References input_fields, and TRUST_List< _CLASSE_ >::size().
Referenced by Probleme_base::findInputField().
findOutputField_impl()
TRUST_Ref< Champ_Generique_base * > Probleme_base_interface_proto::findOutputField_impl (const Probleme_base & pb, const Nom & name) const
References Probleme_base::comprend_champ_post(), and Probleme_base::get_champ_post().
Referenced by Probleme_base::findOutputField().
Member Data Documentation
input_fields
TRUST_List< TRUST_Ref< Field_base *> > Probleme_base_interface_proto::input_fields protected
Referenced by addInputField_impl(), findInputField_impl(), and getInputFieldsNames_impl().
initialized
bool Probleme_base_interface_proto::initialized = false protected
Referenced by computeTimeStep_impl(), initialize_impl(), initTimeStep_impl(), is_probleme_initialized_impl(), presentTime_impl(), resetTimeWithDir_impl(), and terminate_impl().
terminated
bool Probleme_base_interface_proto::terminated = false protected
Referenced by computeTimeStep_impl(), initTimeStep_impl(), isStationary_impl(), presentTime_impl(), resetTimeWithDir_impl(), and terminate_impl().
dt_defined
bool Probleme_base_interface_proto::dt_defined = false protected
Referenced by abortTimeStep_impl(), futureTime_impl(), initTimeStep_impl(), iterateTimeStep_impl(), resetTimeWithDir_impl(), solveTimeStep_impl(), terminate_impl(), and validateTimeStep_impl().
dt_validated
bool Probleme_base_interface_proto::dt_validated = false protected
Referenced by initTimeStep_impl(), isStationary_impl(), and validateTimeStep_impl().