TrioCFD: Paroi_scal_hyd_base_VEF Class Reference
Paroi_scal_hyd_base_VEF Class Reference
#include <Paroi_scal_hyd_base_VEF.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Turbulence_paroi_scal_base
void associer_modele (const Modele_turbulence_scal_base &)
const Type_info * get_info () const override
void imprimer_nusselt_mean_only (Sortie &, int, const TRUST_List< Nom > &, const Nom &) const
void imprimer_premiere_ligne_nusselt (int, const TRUST_List< Nom > &, const Nom &) const
int reprendre (Entree &is) override
int sauvegarder (Sortie &os) const override
virtual bool use_equivalent_distance () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Turbulence_paroi_scal_base
static void typer_lire_turbulence_paroi_scal (TRUST_Deriv< Turbulence_paroi_scal_base > &, const Modele_turbulence_scal_base &, Entree &)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Paroi_scal_hyd_base_VEF()
Paroi_scal_hyd_base_VEF::Paroi_scal_hyd_base_VEF ()
~Paroi_scal_hyd_base_VEF()
Paroi_scal_hyd_base_VEF::~Paroi_scal_hyd_base_VEF () override
Member Function Documentation
info()
const Type_info * Paroi_scal_hyd_base_VEF::info () static
get_info()
const Type_info * Paroi_scal_hyd_base_VEF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Turbulence_paroi_scal_base.
Reimplemented in Loi_Paroi_Nu_Impose_VEF, Paroi_loi_WW_scal_VEF, Paroi_scal_analytique_VEF, Paroi_std_scal_hyd_VEF, Loi_expert_scalaire_VEF, and ParoiVEF_TBLE_scal.
self_cast() [1/2]
Paroi_scal_hyd_base_VEF & Paroi_scal_hyd_base_VEF::self_cast (Objet_U & r) static
self_cast() [2/2]
const Paroi_scal_hyd_base_VEF & Paroi_scal_hyd_base_VEF::self_cast (const Objet_U & r) static
printOn()
Sortie & Paroi_scal_hyd_base_VEF::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Turbulence_paroi_scal_base.
Reimplemented in Loi_Paroi_Nu_Impose_VEF, Paroi_loi_WW_scal_VEF, Paroi_scal_analytique_VEF, Paroi_std_scal_hyd_VEF, Loi_expert_scalaire_VEF, and ParoiVEF_TBLE_scal.
References Objet_U::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Paroi_scal_hyd_base_VEF::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Turbulence_paroi_scal_base.
Reimplemented in Loi_Paroi_Nu_Impose_VEF, Paroi_loi_WW_scal_VEF, Paroi_scal_analytique_VEF, Paroi_std_scal_hyd_VEF, Loi_expert_scalaire_VEF, and ParoiVEF_TBLE_scal.
Referenced by Paroi_scal_analytique_VEF::readOn().
associer()
void Paroi_scal_hyd_base_VEF::associer (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis) override virtual
Implements Turbulence_paroi_scal_base.
Reimplemented in Paroi_loi_WW_scal_VEF.
References init_lois_paroi(), Turbulence_paroi_scal_base::le_dom_Cl_dis_, and Turbulence_paroi_scal_base::le_dom_dis_.
init_lois_paroi()
int Paroi_scal_hyd_base_VEF::init_lois_paroi () override virtual
Implements Turbulence_paroi_scal_base.
Reimplemented in Paroi_std_scal_hyd_VEF, and ParoiVEF_TBLE_scal.
References Objet_U::axi, Frontiere_32_64< _SIZE_ >::creer_tableau_faces(), TRUST_Vector< _CLASSE_ >::dimensionner(), Turbulence_paroi_scal_base::equivalent_distance_, Process::exit(), Frontiere_dis_base::frontiere(), TRUSTVect< _TYPE_, _SIZE_ >::get_md_vector(), Turbulence_paroi_scal_base::le_dom_Cl_dis_, Turbulence_paroi_scal_base::le_dom_dis_, Front_VF::nb_faces(), Turbulence_paroi_scal_base::nb_fields_, MD_Vector::non_nul(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), Turbulence_paroi_scal_base::tab_, and tab_d_reel_.
Referenced by associer(), and Paroi_std_scal_hyd_VEF::init_lois_paroi().
compute_nusselt()
void Paroi_scal_hyd_base_VEF::compute_nusselt () const override virtual
Implements Turbulence_paroi_scal_base.
References Milieu_base::conductivite(), Objet_U::dimension, Equation_base::domaine_Cl_dis(), Probleme_base::equation(), Turbulence_paroi_scal_base::equivalent_distance_, Neumann::flux_impose(), Equation_base::inconnue(), Turbulence_paroi_scal_base::le_dom_Cl_dis_, Turbulence_paroi_scal_base::le_dom_dis_, Domaine_Cl_dis_base::les_conditions_limites(), Equation_base::milieu(), Turbulence_paroi_scal_base::mon_modele_turb_scal, Front_VF::nb_faces(), Front_VF::num_premiere_face(), Equation_base::probleme(), Turbulence_paroi_scal_base::tab_, tab_d_reel_, TRUST_Deriv< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), and Champ_Inc_base::valeurs().
Referenced by imprimer_nusselt().
imprimer_nusselt()
void Paroi_scal_hyd_base_VEF::imprimer_nusselt (Sortie & os) const override virtual
Reimplemented from Turbulence_paroi_scal_base.
Reimplemented in Loi_Paroi_Nu_Impose_VEF, and ParoiVEF_TBLE_scal.
References compute_nusselt(), Objet_U::dimension, Equation_base::domaine_Cl_dis(), Probleme_base::equation(), Process::je_suis_maitre(), Turbulence_paroi_scal_base::le_dom_Cl_dis_, Turbulence_paroi_scal_base::le_dom_dis_, Frontiere_dis_base::le_nom(), Domaine_Cl_dis_base::les_conditions_limites(), Turbulence_paroi_scal_base::mon_modele_turb_scal, Front_VF::nb_faces(), Turbulence_paroi_scal_base::nb_fields_, Front_VF::num_premiere_face(), Turbulence_paroi_scal_base::ouvrir_fichier_partage(), Equation_base::probleme(), EcrFicPartage::syncfile(), Turbulence_paroi_scal_base::tab_, and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by ParoiVEF_TBLE_scal::imprimer_nusselt().
tab_d_reel() [1/2]
const DoubleVect & Paroi_scal_hyd_base_VEF::tab_d_reel () const inline
tab_d_reel() [2/2]
DoubleVect & Paroi_scal_hyd_base_VEF::tab_d_reel () inline
equivalent_distance_name()
DoubleVect & Paroi_scal_hyd_base_VEF::equivalent_distance_name (DoubleVect & d_eq, const Nom & nom_bord) const override virtual
Implements Turbulence_paroi_scal_base.
References Turbulence_paroi_scal_base::equivalent_distance(), Turbulence_paroi_scal_base::le_dom_dis_, Frontiere_dis_base::le_nom(), Front_VF::nb_faces(), and TRUSTVect< _TYPE_, _SIZE_ >::resize().
Member Data Documentation
info_obj
const Type_info Paroi_scal_hyd_base_VEF::info_obj static
tab_d_reel_
DoubleVect Paroi_scal_hyd_base_VEF::tab_d_reel_ protected
Referenced by compute_nusselt(), and init_lois_paroi().