TrioCFD: Pb_Thermohydraulique Class Reference
Pb_Thermohydraulique Class Reference
#include <Pb_Thermohydraulique.h>
Public Member Functions
void associer_milieu_base (const Milieu_base &) override
const Equation_base & equation (int) const override
Equation_base & equation (int) override
const Type_info * get_info () const override
int verifier () override
void associer_milieu_base (const Milieu_base &) override
const Equation_base & equation (int) const override
Equation_base & equation (int) override
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Probleme_base
void abortTimeStep () override
int associer_ (Objet_U &) override
virtual void associer_domaine (const Domaine &)
virtual void associer_milieu_base (const Milieu_base &)
virtual void associer_sch_tps_base (const Schema_Temps_base &)
virtual double calculer_pas_de_temps () const
virtual void completer ()
double computeTimeStep (bool &stop) const override
const Discretisation_base & discretisation () const
virtual void discretiser (Discretisation_base &)
Domaine & domaine ()
const Domaine & domaine () const
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
Equation_base & equation (const Nom &)
const Equation_base & equation (const Nom &) const
TRUST_Ref< Field_base * > findInputField (const Nom &name) const override
virtual void finir ()
double futureTime () const override
const Type_info * get_info () const override
void getInputFieldsNames (Noms &noms) const override
void getOutputFieldsNames (Noms &noms) const override
virtual void imprimer (Sortie &os) const
void initialize () override
bool initTimeStep (double dt) override
bool isStationary () const override
bool iterateTimeStep (bool &converged) override
int limpr () const override
int lsauv () const override
virtual void mettre_a_jour (double temps)
virtual Milieu_base & milieu ()
virtual const Milieu_base & milieu () const
int postraiter (int force=1) override
double presentTime () const override
int reprendre (Entree &) override
void resetTime (double time) override
int sauvegarder (Sortie &) const override
Schema_Temps_base & schema_temps ()
const Schema_Temps_base & schema_temps () const
void terminate () override
bool updateGivenFields () override
void validateTimeStep () override
virtual int verifier ()
Public Member Functions inherited from Probleme_U
virtual void abortTimeStep ()
virtual double computeTimeStep (bool &stop) const
virtual TRUST_Ref< Field_base * > findInputField (const Nom &name) const
virtual double futureTime () const
const Type_info * get_info () const override
virtual void getInputFieldsNames (Noms &noms) const
virtual void getOutputFieldsNames (Noms &noms) const
virtual void initialize ()
virtual bool initTimeStep (double dt)
virtual bool isStationary () const
virtual bool iterateTimeStep (bool &converged)
const Nom & le_nom () const override
void nommer (const Nom &name) override
virtual int postraiter (int force=1)
virtual double presentTime () const
virtual void resetTime (double time)
virtual bool run ()
virtual bool runUntil (double time)
virtual void terminate ()
virtual bool updateGivenFields ()
virtual void validateTimeStep ()
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
 - Equations de Navier_Stokes en regime laminaire
   pour un fluide incompressible
 - Equation d'energie en regime laminaire
   En general, on couple les 2 equations par l'intermediaire du terme
   source des forces de volume de Navier_Stokes dans lequel on prend en
   compte de petites variations de la masse volumique en fonction de
   la temperature
   (le fluide est incompressible et faiblement dilalatable)
See also
Pb_Fluide_base Navier_Stokes_std Convection_Diffusion_Temperature
Constructor & Destructor Documentation
Pb_Thermohydraulique()
Pb_Thermohydraulique::Pb_Thermohydraulique ()
~Pb_Thermohydraulique()
Pb_Thermohydraulique::~Pb_Thermohydraulique ()
Member Function Documentation
cree_instance()
Objet_U * Pb_Thermohydraulique::cree_instance () static
taille_memoire()
unsigned Pb_Thermohydraulique::taille_memoire () const override virtual
Reimplemented from Pb_Hydraulique.
Reimplemented in Pb_Rayo_Thermohydraulique, TRUSTProblem_sup_eqns< Pb_Thermohydraulique_Concentration >, TRUSTProblem_sup_eqns< Pb_Thermohydraulique >, TRUSTProblem_Cloned_Concentration_Gen< Pb_Thermohydraulique >, TRUSTProblem_List_Concentration_Gen< Pb_Thermohydraulique >, Pb_Thermohydraulique_Concentration, Pb_Thermohydraulique_Cloned_Concentration, Pb_Thermohydraulique_List_Concentration, Pb_Thermohydraulique_Concentration_Scalaires_Passifs, and Pb_Thermohydraulique_Scalaires_Passifs.
duplique()
int Pb_Thermohydraulique::duplique () const override virtual
Reimplemented from Pb_Hydraulique.
Reimplemented in Pb_Rayo_Thermohydraulique, TRUSTProblem_sup_eqns< Pb_Thermohydraulique_Concentration >, TRUSTProblem_sup_eqns< Pb_Thermohydraulique >, TRUSTProblem_Cloned_Concentration_Gen< Pb_Thermohydraulique >, TRUSTProblem_List_Concentration_Gen< Pb_Thermohydraulique >, Pb_Thermohydraulique_Concentration, Pb_Thermohydraulique_Cloned_Concentration, Pb_Thermohydraulique_List_Concentration, Pb_Thermohydraulique_Concentration_Scalaires_Passifs, and Pb_Thermohydraulique_Scalaires_Passifs.
info()
const Type_info * Pb_Thermohydraulique::info () static
get_info()
const Type_info * Pb_Thermohydraulique::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Pb_Hydraulique.
Reimplemented in Pb_Rayo_Thermohydraulique, Pb_Thermohydraulique_Concentration, Pb_Thermohydraulique_Cloned_Concentration, Pb_Thermohydraulique_List_Concentration, Pb_Thermohydraulique_Concentration_Scalaires_Passifs, and Pb_Thermohydraulique_Scalaires_Passifs.
self_cast() [1/2]
Pb_Thermohydraulique & Pb_Thermohydraulique::self_cast (Objet_U & r) static
self_cast() [2/2]
const Pb_Thermohydraulique & Pb_Thermohydraulique::self_cast (const Objet_U & r) static
printOn()
Sortie & Pb_Thermohydraulique::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Pb_Hydraulique.
Reimplemented in TRUSTProblem_sup_eqns< Pb_Thermohydraulique_Concentration >, TRUSTProblem_sup_eqns< Pb_Thermohydraulique >, TRUSTProblem_Concentration_Gen< Pb_Thermohydraulique, Convection_Diffusion_Concentration, Constituant >, Pb_Rayo_Thermohydraulique, Pb_Thermohydraulique_Concentration, Pb_Thermohydraulique_Cloned_Concentration, Pb_Thermohydraulique_List_Concentration, Pb_Thermohydraulique_Concentration_Scalaires_Passifs, and Pb_Thermohydraulique_Scalaires_Passifs.
References Pb_Hydraulique::printOn().
Referenced by Pb_Rayo_Thermohydraulique::printOn(), and Pb_Thermohydraulique_Concentration::printOn().
readOn()
Entree & Pb_Thermohydraulique::readOn (Entree & is) override protected virtual
Lecture d'un probleme dans un flot d'entree, et ouverture du flot de sauvegarde.
Format: { nom_milieu bloc de lecture d'un milieu nom_equation bloc de lecture d'une equation Postraitement bloc de lecture postraitement reprise | sauvegarde | sauvegarde_simple formatte | binaire | pdi nom_de_fichier } L'option sauvegarde_simple permet de sauver le probleme dans le fichier choisi en ecrasant a chaque fois les sauvegardes precedentes : cela permet d'economiser de la place disque.
Parameters
(Entree& is) flot d'entree
Returns
(Entree&) le flot d'entre modifie
Exceptions
pas d'accolade ouvrante en debut de format
mot clef "Postraitement" n'est pas la
format de sauvegarde doit etre "binaire" ou "formatte"
pas d'accolade fermante en fin de jeu de donnee
Reimplemented from Pb_Hydraulique.
Reimplemented in Pb_Rayo_Thermohydraulique, Pb_Thermohydraulique_Concentration, Pb_Thermohydraulique_Cloned_Concentration, Pb_Thermohydraulique_List_Concentration, Pb_Thermohydraulique_Concentration_Scalaires_Passifs, Pb_Thermohydraulique_Scalaires_Passifs, TRUSTProblem_sup_eqns< Pb_Thermohydraulique_Concentration >, TRUSTProblem_sup_eqns< Pb_Thermohydraulique >, TRUSTProblem_Cloned_Concentration_Gen< Pb_Thermohydraulique >, and TRUSTProblem_List_Concentration_Gen< Pb_Thermohydraulique >.
References Pb_Hydraulique::readOn().
Referenced by Pb_Rayo_Thermohydraulique::readOn(), and Pb_Thermohydraulique_Concentration::readOn().
nombre_d_equations()
int Pb_Thermohydraulique::nombre_d_equations () const inline override virtual
Reimplemented from Pb_Hydraulique.
Reimplemented in TRUSTProblem_sup_eqns< Pb_Thermohydraulique_Concentration >, TRUSTProblem_sup_eqns< Pb_Thermohydraulique >, TRUSTProblem_Concentration_Gen< Pb_Thermohydraulique, Convection_Diffusion_Concentration, Constituant >, and Pb_Thermohydraulique_Concentration.
References Probleme_base::eq_opt_, and TRUST_List< _CLASSE_ >::size().
equation() [1/2]
const Equation_base & Pb_Thermohydraulique::equation (int i) const override virtual
Renvoie l'equation d'hydraulique de type Navier_Stokes_std si i=0 Renvoie l'equation de la thermique de type.
Convection_Diffusion_Temperature si i=1 (version const)
Parameters
(int i) l'index de l'equation a renvoyer
Returns
(Equation_base&) l'equation correspondante a l'index
Reimplemented from Pb_Hydraulique.
Reimplemented in TRUSTProblem_sup_eqns< Pb_Thermohydraulique_Concentration >, TRUSTProblem_sup_eqns< Pb_Thermohydraulique >, TRUSTProblem_Concentration_Gen< Pb_Thermohydraulique, Convection_Diffusion_Concentration, Constituant >, and Pb_Thermohydraulique_Concentration.
References Pb_Hydraulique::eq_hydraulique, Probleme_base::eq_opt_, eq_thermique, Process::exit(), and TRUST_List< _CLASSE_ >::size().
Referenced by Pb_Thermohydraulique_Concentration::equation().
equation() [2/2]
Equation_base & Pb_Thermohydraulique::equation (int i) override virtual
Renvoie l'equation d'hydraulique de type Navier_Stokes_std si i=0 Renvoie l'equation de la thermique de type.
Convection_Diffusion_Temperature si i=1
Parameters
(int i) l'index de l'equation a renvoyer
Returns
(Equation_base&) l'equation correspondante a l'index
Reimplemented from Pb_Hydraulique.
Reimplemented in TRUSTProblem_sup_eqns< Pb_Thermohydraulique_Concentration >, TRUSTProblem_sup_eqns< Pb_Thermohydraulique >, TRUSTProblem_Concentration_Gen< Pb_Thermohydraulique, Convection_Diffusion_Concentration, Constituant >, and Pb_Thermohydraulique_Concentration.
References Pb_Hydraulique::eq_hydraulique, Probleme_base::eq_opt_, eq_thermique, Process::exit(), and TRUST_List< _CLASSE_ >::size().
associer_milieu_base()
void Pb_Thermohydraulique::associer_milieu_base (const Milieu_base & mil) override virtual
Associe le milieu au probleme Le milieu doit etre de type fluide incompressible.
Parameters
(Milieu_base& mil) le milieu physique a associer au probleme
Exceptions
mauvais type de milieu physique
Reimplemented from Pb_Hydraulique.
Reimplemented in TRUSTProblem_Cloned_Concentration_Gen< Pb_Thermohydraulique >, TRUSTProblem_List_Concentration_Gen< Pb_Thermohydraulique >, Pb_Thermohydraulique_Concentration, TRUSTProblem_sup_eqns< Pb_Thermohydraulique_Concentration >, and TRUSTProblem_sup_eqns< Pb_Thermohydraulique >.
References Convection_Diffusion_Temperature::associer_milieu_base(), Pb_Hydraulique::associer_milieu_base(), and eq_thermique.
Referenced by Pb_Thermohydraulique_Concentration::associer_milieu_base().
verifier()
int Pb_Thermohydraulique::verifier () override virtual
Teste la compatibilite des equations de la thermique et de l'hydraulique.
Le test se fait sur les conditions aux limites discretisees de chaque equation. Appel la fonction de librairie hors classe: tester_compatibilite_hydr_thermique(const Domaine_Cl_dis_base&,const Domaine_Cl_dis_base&)
Returns
(int) code de retour propage
Reimplemented from Probleme_base.
Reimplemented in TRUSTProblem_Cloned_Concentration_Gen< Pb_Thermohydraulique >, TRUSTProblem_List_Concentration_Gen< Pb_Thermohydraulique >, and Pb_Thermohydraulique_Concentration.
References Equation_base::domaine_Cl_dis(), Pb_Hydraulique::eq_hydraulique, and eq_thermique.
Referenced by Pb_Thermohydraulique_Concentration::verifier().
Member Data Documentation
info_obj
const Type_info Pb_Thermohydraulique::info_obj static
eq_thermique
Convection_Diffusion_Temperature Pb_Thermohydraulique::eq_thermique protected
Referenced by associer_milieu_base(), equation(), and verifier().