TrioCFD: Loi_Etat_rhoT_GP_QC Class Reference
Loi_Etat_rhoT_GP_QC Class Reference
#include <Loi_Etat_rhoT_GP_QC.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Loi_Etat_GP_base
void associer_fluide (const Fluide_Dilatable_base &) override
const Type_info * get_info () const override
void remplir_T () override
const Nom type_fluide () const override
Public Member Functions inherited from Loi_Etat_base
virtual void associer_fluide (const Fluide_Dilatable_base &)
void assoscier_probleme (const Probleme_base &pb)
const Type_info * get_info () const override
void mettre_a_jour (double)
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
Constructor & Destructor Documentation
~Loi_Etat_rhoT_GP_QC()
Loi_Etat_rhoT_GP_QC::~Loi_Etat_rhoT_GP_QC ()
Loi_Etat_rhoT_GP_QC()
Loi_Etat_rhoT_GP_QC::Loi_Etat_rhoT_GP_QC ()
Member Function Documentation
cree_instance()
Objet_U * Loi_Etat_rhoT_GP_QC::cree_instance () static
taille_memoire()
unsigned Loi_Etat_rhoT_GP_QC::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Loi_Etat_rhoT_GP_QC::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Loi_Etat_rhoT_GP_QC::info () static
get_info()
const Type_info * Loi_Etat_rhoT_GP_QC::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Loi_Etat_GP_base.
self_cast() [1/2]
Loi_Etat_rhoT_GP_QC & Loi_Etat_rhoT_GP_QC::self_cast (Objet_U & r) static
self_cast() [2/2]
const Loi_Etat_rhoT_GP_QC & Loi_Etat_rhoT_GP_QC::self_cast (const Objet_U & r) static
printOn()
Sortie & Loi_Etat_rhoT_GP_QC::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Loi_Etat_GP_base.
References Loi_Etat_GP_base::printOn().
readOn()
Entree & Loi_Etat_rhoT_GP_QC::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Loi_Etat_GP_base.
References Parser_U::addVar(), Param::ajouter(), Loi_Etat_GP_base::Cp_, Objet_U_ptr::est_nul(), Process::exit(), is_exp_, Param::lire_avec_accolades(), parser_, Parser_U::parseString(), Loi_Etat_base::Pr_, Objet_U::que_suis_je(), Param::REQUIRED, rho_xyz_, Parser_U::setNbVar(), Parser_U::setString(), and TMIN_.
initialiser_inco_ch()
void Loi_Etat_rhoT_GP_QC::initialiser_inco_ch () override virtual
Initialise l'inconnue de l'equation de chaleur : ne fai rien.
Reimplemented from Loi_Etat_base.
References Loi_Etat_base::initialiser_inco_ch(), initialiser_rho(), and is_exp_.
initialiser_rho()
void Loi_Etat_rhoT_GP_QC::initialiser_rho ()
References Champ_base::affecter_(), Loi_Etat_base::le_fluide, TRUSTTab< _TYPE_, _SIZE_ >::resize(), rho_, rho_xyz_, TRUSTVect< _TYPE_, _SIZE_ >::size(), Champ_Don_base::valeurs(), and Champ_Proto::valeurs().
Referenced by initialiser_inco_ch().
calculer_masse_volumique() [1/3]
void Loi_Etat_rhoT_GP_QC::calculer_masse_volumique () override virtual
Recalcule la masse volumique.
Reimplemented from Loi_Etat_GP_base.
References is_exp_, Loi_Etat_base::le_fluide, parser_, ParserView::parseString(), Loi_Etat_base::rho_n(), Loi_Etat_base::rho_np1(), TRUSTVect< _TYPE_, _SIZE_ >::size(), Loi_Etat_base::tab_rho_n, Loi_Etat_base::tab_rho_np1, TMIN_, TRUSTTab< _TYPE_, _SIZE_ >::view_ro(), and TRUSTTab< _TYPE_, _SIZE_ >::view_wo().
calculer_masse_volumique() [2/3]
double Loi_Etat_rhoT_GP_QC::calculer_masse_volumique (double P, double T) const override virtual
Reimplemented from Loi_Etat_GP_base.
calculer_masse_volumique() [3/3]
double Loi_Etat_rhoT_GP_QC::calculer_masse_volumique (double P, double T, int ind) const
inverser_Pth()
double Loi_Etat_rhoT_GP_QC::inverser_Pth (double T, double rho) override virtual
Calcule la pression avec la temperature et la masse volumique.
Reimplemented from Loi_Etat_GP_base.
References Process::abort().
Member Data Documentation
info_obj
const Type_info Loi_Etat_rhoT_GP_QC::info_obj static
is_exp_
bool Loi_Etat_rhoT_GP_QC::is_exp_ protected
Referenced by calculer_masse_volumique(), initialiser_inco_ch(), and readOn().
rho_xyz_
TRUST_Deriv< Champ_Don_base > Loi_Etat_rhoT_GP_QC::rho_xyz_ protected
Referenced by initialiser_rho(), and readOn().
rho_
DoubleTab Loi_Etat_rhoT_GP_QC::rho_ protected
Referenced by initialiser_rho().
TMIN_
double Loi_Etat_rhoT_GP_QC::TMIN_ =-1000 protected
Referenced by calculer_masse_volumique(), and readOn().
parser_
Parser_U Loi_Etat_rhoT_GP_QC::parser_ mutable protected
Referenced by calculer_masse_volumique(), and readOn().