TrioCFD: Operateur_Conv_sensibility_VEF Class Reference
Operateur_Conv_sensibility_VEF Class Reference
#include <Operateur_Conv_sensibility_VEF.h>
Public Member Functions
double calculer_dt_stab () const override
const Type_info * get_info () const override
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Operateur_base
void associer_eqn (const Equation_base &)
virtual double calculer_dt_stab () const
virtual void completer ()
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual void mettre_a_jour (double temps)
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
Constructor & Destructor Documentation
Operateur_Conv_sensibility_VEF()
Operateur_Conv_sensibility_VEF::Operateur_Conv_sensibility_VEF ()
~Operateur_Conv_sensibility_VEF()
Operateur_Conv_sensibility_VEF::~Operateur_Conv_sensibility_VEF ()
Member Function Documentation
cree_instance()
Objet_U * Operateur_Conv_sensibility_VEF::cree_instance () static
taille_memoire()
unsigned Operateur_Conv_sensibility_VEF::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Operateur_Conv_sensibility_VEF::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Operateur_Conv_sensibility_VEF::info () static
get_info()
const Type_info * Operateur_Conv_sensibility_VEF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Operateur_Conv_sensibility.
self_cast() [1/2]
Operateur_Conv_sensibility_VEF & Operateur_Conv_sensibility_VEF::self_cast (Objet_U & r) static
self_cast() [2/2]
const Operateur_Conv_sensibility_VEF & Operateur_Conv_sensibility_VEF::self_cast (const Objet_U & r) static
printOn()
Sortie & Operateur_Conv_sensibility_VEF::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN A surcharger dans les classes derivees.
Parameters
(Sortie& os) un flot de sortie
Returns
(Sortie&) le flot de sortie
Reimplemented from Operateur_Conv_sensibility.
readOn()
Entree & Operateur_Conv_sensibility_VEF::readOn (Entree & is) override protected virtual
NE FAIT RIEN A surcharger dans les classes derivees.
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree
Reimplemented from Operateur_Conv_sensibility.
References MorEqn::associer_eqn(), Operateur_Conv::associer_vitesse(), MorEqn::equation(), Operateur_Conv_sensibility::la_vitesse, Operateur::lire(), Operateur_Conv_sensibility::op_conv, Objet_U::que_suis_je(), and TRUST_Ref< _CLASSE_ >::valeur().
associer()
void Operateur_Conv_sensibility_VEF::associer (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_cl_dis, const Champ_Inc_base & inco) override virtual
Reimplemented from Operateur_Conv_sensibility.
References Operateur_Conv_sensibility::associer(), fluent, la_zcl_vef, and le_dom_vef.
ajouter()
DoubleTab & Operateur_Conv_sensibility_VEF::ajouter (const DoubleTab & inco, DoubleTab & resu) const override virtual
Reimplemented from Operateur_Conv_sensibility.
References add_diffusion_scalar_term(), add_diffusion_term(), ajouter_conv_term(), Matrice_Morse::ajouter_multvectT_(), Milieu_base::capacite_calorifique(), Milieu_base::conductivite(), Op_Conv_VEF_Face::contribue_au_second_membre(), Op_Conv_VEF_Face::contribuer_a_avec(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Op_Conv_VEF_Face::dimensionner(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), MorEqn::equation(), Process::exit(), Convection_Diffusion_Temperature_base::fluide(), Operateur_base::flux_bords_, Navier_Stokes_std_sensibility::get_adjoint_value(), Convection_Diffusion_Temperature_sensibility::get_poly_chaos_value(), Navier_Stokes_std_sensibility::get_poly_chaos_value(), Navier_Stokes_std_sensibility::get_state(), Navier_Stokes_std_sensibility::get_state_field(), Convection_Diffusion_Temperature_sensibility::get_temperature_state_field(), Op_Conv_VEF_Face::get_type_op(), Convection_Diffusion_Temperature_sensibility::get_uncertain_variable_name(), Navier_Stokes_std_sensibility::get_uncertain_variable_name(), Convection_Diffusion_Temperature_sensibility::get_velocity_state(), Operateur_Conv_sensibility::la_vitesse, le_dom_vef, Op_VEF_Face::modifier_flux(), Op_Conv_VEF_Face::modifier_pour_Cl(), Domaine_VF::nb_faces_bord(), Operateur_Conv_sensibility::op_conv, Objet_U::que_suis_je(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Operateur::type(), TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), Champ_Inc_base::valeurs(), Debog::verifier(), Operateur_Conv_sensibility::vitesse(), and Navier_Stokes_std::vitesse().
ajouter_Lstate_sensibility_Amont()
void Operateur_Conv_sensibility_VEF::ajouter_Lstate_sensibility_Amont (const DoubleTab & state_field, const DoubleTab & inco, DoubleTab & resu) const
References calcul_vc(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Domaine_dis_base::domaine(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_VF::elem_faces(), est_une_face_de_dirichlet_, Process::exit(), Periodique::face_associee(), Domaine_VF::face_normales(), Domaine_VF::face_sommets(), Domaine_VEF::facette_normales(), Operateur_base::flux_bords_, Cond_lim_base::frontiere_dis(), Elem_VEF_base::KEL(), la_zcl_vef, le_dom_vef, Domaine_Cl_dis_base::les_conditions_limites(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Domaine_dis_base::nb_elem_tot(), Domaine_VF::nb_faces(), Front_VF::nb_faces(), Domaine_VF::nb_faces_bord(), Domaine_VF::nb_faces_tot(), Front_VF::nb_faces_tot(), Elem_VEF_base::nb_facette(), Domaine_dis_base::nb_front_Cl(), Domaine_dis_base::nb_som_tot(), Domaine_Cl_VEF::normales_facettes_Cl(), Front_VF::num_face(), Front_VF::num_premiere_face(), Objet_U::que_suis_je(), Domaine_VEF::rang_elem_non_std(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), traitement_pres_bord_, Domaine_VEF::type_elem(), Domaine_Cl_VEF::type_elem_Cl(), Neumann_sortie_libre::val_ext(), TRUST_Deriv< _CLASSE_ >::valeur(), and TRUST_Ref< _CLASSE_ >::valeur().
ajouter_Lsensibility_state_Amont()
void Operateur_Conv_sensibility_VEF::ajouter_Lsensibility_state_Amont (const DoubleTab & inco, const DoubleTab & state_field, DoubleTab & resu) const
References calcul_vc(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Domaine_dis_base::domaine(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_VF::elem_faces(), est_une_face_de_dirichlet_, Process::exit(), Periodique::face_associee(), Domaine_VF::face_normales(), Domaine_VF::face_sommets(), Domaine_VEF::facette_normales(), Operateur_base::flux_bords_, Cond_lim_base::frontiere_dis(), Elem_VEF_base::KEL(), la_zcl_vef, le_dom_vef, Domaine_Cl_dis_base::les_conditions_limites(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Domaine_dis_base::nb_elem_tot(), Domaine_VF::nb_faces(), Front_VF::nb_faces(), Domaine_VF::nb_faces_bord(), Domaine_VF::nb_faces_tot(), Front_VF::nb_faces_tot(), Elem_VEF_base::nb_facette(), Domaine_dis_base::nb_front_Cl(), Domaine_dis_base::nb_som_tot(), Domaine_Cl_VEF::normales_facettes_Cl(), Front_VF::num_face(), Front_VF::num_premiere_face(), Objet_U::que_suis_je(), Domaine_VEF::rang_elem_non_std(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), traitement_pres_bord_, Domaine_VEF::type_elem(), Domaine_Cl_VEF::type_elem_Cl(), Neumann_sortie_libre::val_ext(), TRUST_Deriv< _CLASSE_ >::valeur(), and TRUST_Ref< _CLASSE_ >::valeur().
calcul_vc()
void Operateur_Conv_sensibility_VEF::calcul_vc (const ArrOfInt & Face, ArrOfDouble & vc, const ArrOfDouble & s, const DoubleTab & vsom, const DoubleTab & vitesse_face, int type_cl) const
References Objet_U::dimension.
Referenced by ajouter_Lsensibility_state_Amont(), ajouter_Lstate_sensibility_Amont(), and remplir_fluent().
remplir_fluent()
void Operateur_Conv_sensibility_VEF::remplir_fluent (DoubleVect & tab_fluent) const virtual
References calcul_vc(), Objet_U::dimension, Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), Domaine_VF::face_normales(), Domaine_VEF::facette_normales(), Elem_VEF_base::KEL(), la_zcl_vef, le_dom_vef, Domaine_Cl_dis_base::les_conditions_limites(), Domaine_dis_base::nb_elem_tot(), Front_VF::nb_faces(), Elem_VEF_base::nb_facette(), Domaine_dis_base::nb_front_Cl(), Domaine_Cl_VEF::normales_facettes_Cl(), Front_VF::num_premiere_face(), Objet_U::que_suis_je(), Domaine_VEF::rang_elem_non_std(), Domaine_VEF::type_elem(), Domaine_Cl_VEF::type_elem_Cl(), TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_base::valeur_a_sommet_compo(), Champ_Inc_base::valeurs(), and Operateur_Conv_sensibility::vitesse().
Referenced by calculer_dt_stab().
calculer_dt_stab()
double Operateur_Conv_sensibility_VEF::calculer_dt_stab () const override virtual
Calcul dt_stab.
Returns
(double) renvoie toujours 1.e30
Reimplemented from Operateur_base.
References Operateur_Conv_base::fixer_dt_stab_conv(), fluent, la_zcl_vef, le_dom_vef, Domaine_Cl_dis_base::les_conditions_limites(), Process::mp_min(), Domaine_VF::nb_faces(), Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), Domaine_VF::premiere_face_int(), Domaine_VEF::premiere_face_std(), remplir_fluent(), TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), Domaine_VF::volumes_entrelaces(), and Domaine_Cl_VEF::volumes_entrelaces_Cl().
add_diffusion_term()
void Operateur_Conv_sensibility_VEF::add_diffusion_term (const DoubleTab & state, DoubleTab & resu) const
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), Periodique::face_associee(), Domaine_VF::face_voisins(), Operateur_base::flux_bords_, la_zcl_vef, le_dom_vef, Domaine_Cl_dis_base::les_conditions_limites(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Domaine_VF::nb_faces(), Front_VF::nb_faces(), Domaine_VF::nb_faces_bord(), Domaine_32_64< _SIZE_ >::nb_faces_elem(), Front_VF::nb_faces_tot(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_face(), Front_VF::num_premiere_face(), Domaine_VF::premiere_face_int(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), and viscA().
Referenced by ajouter().
add_diffusion_scalar_term()
void Operateur_Conv_sensibility_VEF::add_diffusion_scalar_term (const DoubleTab & inconnue, DoubleTab & resu, double diffu = 1.) const
References Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), Periodique::face_associee(), Domaine_VF::face_voisins(), Operateur_base::flux_bords_, Neumann::flux_impose(), Echange_impose_base::h_imp(), la_zcl_vef, le_dom_vef, Domaine_Cl_dis_base::les_conditions_limites(), Domaine_VF::nb_faces(), Front_VF::nb_faces(), Domaine_VF::nb_faces_bord(), Domaine_32_64< _SIZE_ >::nb_faces_elem(), Front_VF::nb_faces_tot(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_face(), Front_VF::num_premiere_face(), Domaine_VF::premiere_face_int(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Domaine_VF::surface(), Echange_impose_base::T_ext(), TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), and viscA().
Referenced by ajouter().
viscA()
double Operateur_Conv_sensibility_VEF::viscA (int face_i, int face_j, int num_elem, double diffu = 1.) const inline
References Objet_U::dimension, le_dom_vef, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by add_diffusion_scalar_term(), and add_diffusion_term().
ajouter_conv_term()
void Operateur_Conv_sensibility_VEF::ajouter_conv_term (const Champ_Inc_base & velocity, const DoubleTab & transporte, DoubleTab & resu, DoubleTab & flux_b) const
References application_LIMITEUR(), Champ_P1NC::calcul_gradient(), Elem_VEF_base::calcul_vc(), Elem_VEF_base::calcul_xg(), Domaine_VF::creer_tableau_faces(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Domaine_dis_base::domaine(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_VF::elem_faces(), MorEqn::equation(), est_une_face_de_dirichlet_, Periodique::face_associee(), Domaine_VF::face_normales(), Domaine_VF::face_sommets(), Domaine_VF::face_voisins(), Domaine_VEF::facette_normales(), Cond_lim_base::frontiere_dis(), Op_Conv_VEF_Face::get_alpha(), Op_Conv_VEF_Face::get_ordre(), Op_Conv_VEF_Face::get_type_lim(), Elem_VEF_base::KEL(), la_zcl_vef, le_dom_vef, Domaine_Cl_dis_base::les_conditions_limites(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Domaine_dis_base::nb_elem_tot(), Domaine_VF::nb_faces(), Front_VF::nb_faces(), Domaine_VF::nb_faces_bord(), Domaine_VF::nb_faces_tot(), Front_VF::nb_faces_tot(), Elem_VEF_base::nb_facette(), Domaine_dis_base::nb_front_Cl(), Domaine_dis_base::nb_som_tot(), Domaine_Cl_VEF::normales_facettes_Cl(), Front_VF::num_face(), Front_VF::num_premiere_face(), Operateur_Conv_sensibility::op_conv, Op_Conv_VEF_base::phi_u_transportant(), Domaine_VF::premiere_face_int(), Objet_U::que_suis_je(), Domaine_VEF::rang_elem_non_std(), TRUSTTab< _TYPE_, _SIZE_ >::ref(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), traitement_pres_bord_, Operateur::type(), Domaine_VEF::type_elem(), Domaine_Cl_VEF::type_elem_Cl(), Neumann_sortie_libre::val_ext(), TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_base::valeur_a_sommet_compo(), Champ_Inc_base::valeurs(), Domaine_Cl_VEF::vecteur_face_facette_Cl(), and Domaine_VF::xv().
Referenced by ajouter().
application_LIMITEUR()
double Operateur_Conv_sensibility_VEF::application_LIMITEUR (double grad1, double grad2, Motcle & type_limit) const
References Process::exit().
Referenced by ajouter_conv_term().
Member Data Documentation
info_obj
const Type_info Operateur_Conv_sensibility_VEF::info_obj static
le_dom_vef
TRUST_Ref< Domaine_VEF *> Operateur_Conv_sensibility_VEF::le_dom_vef protected
Referenced by add_diffusion_scalar_term(), add_diffusion_term(), ajouter(), ajouter_conv_term(), ajouter_Lsensibility_state_Amont(), ajouter_Lstate_sensibility_Amont(), associer(), calculer_dt_stab(), remplir_fluent(), and viscA().
la_zcl_vef
TRUST_Ref< Domaine_Cl_VEF *> Operateur_Conv_sensibility_VEF::la_zcl_vef protected
Referenced by add_diffusion_scalar_term(), add_diffusion_term(), ajouter_conv_term(), ajouter_Lsensibility_state_Amont(), ajouter_Lstate_sensibility_Amont(), associer(), calculer_dt_stab(), and remplir_fluent().
fluent
DoubleVect Operateur_Conv_sensibility_VEF::fluent mutable protected
Referenced by associer(), and calculer_dt_stab().
traitement_pres_bord_
ArrOfInt Operateur_Conv_sensibility_VEF::traitement_pres_bord_ mutable protected
Referenced by ajouter_conv_term(), ajouter_Lsensibility_state_Amont(), and ajouter_Lstate_sensibility_Amont().
est_une_face_de_dirichlet_
ArrOfInt Operateur_Conv_sensibility_VEF::est_une_face_de_dirichlet_ mutable protected
Referenced by ajouter_conv_term(), ajouter_Lsensibility_state_Amont(), and ajouter_Lstate_sensibility_Amont().