TrioCFD: Maillage_FT_Disc Class Reference
Maillage_FT_Disc Class Reference
#include <Maillage_FT_Disc.h>
Public Member Functions
void associer_equation_transport (const Equation_base &equation) override
void calcul_indicatrice (DoubleVect &indicatrice, const DoubleVect &indicatrice_precedente)
virtual void calculer_costheta_minmax (DoubleTab &costheta) const
void completer_maillage ()
const ArrOfInt & drapeaux_sommets () const
int facette_virtuelle (int i) const
const IntTab & facettes () const
int facettes_voisines (int fa70, int fa71, int &iarete0, int &iarete1) const
const Type_info * get_info () const override
virtual const ArrOfDouble & get_update_courbure_sommets () const
virtual const DoubleTab & get_update_normale_facettes () const
virtual const ArrOfDouble & get_update_surface_facettes () const
virtual Entree & lire_param_maillage (Entree &is)
int nb_facettes () const
int nb_sommets () const
void parcourir_maillage ()
void preparer_tableau_avant_transport (ArrOfDouble &tableau, const Desc_Structure_FT &descripteur) const
virtual void recopie (const Maillage_FT_Disc &maillage_source, Statut_Maillage niveau_copie)
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
const DoubleTab & sommets () const
void supprimer_facettes (const ArrOfInt &liste_facettes)
double temps () const
virtual void transporter (const DoubleTab &deplacement)
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
void calcul_courbure_sommets (ArrOfDouble &courbure, const int call_number) const
void calcul_surface_normale (ArrOfDouble &surface, DoubleTab &normale) const
void convertir_numero_distant_local (const Desc_Structure_FT &descripteur, const ArrOfInt &element_num_owner, const ArrOfInt &numeros_distants, const ArrOfInt &pe_distant, ArrOfInt &numeros_locaux) const
void corriger_proprietaires_facettes ()
virtual void creer_facettes_virtuelles (const ArrOfInt &liste_facettes, const ArrOfInt &liste_pe, const ArrOfInt &facettes_send_pe_list, const ArrOfInt &facettes_recv_pe_list)
void creer_sommets_virtuels (const ArrOfInt &liste_sommets, const ArrOfInt &liste_pe, const Schema_Comm &comm)
void creer_sommets_virtuels_numowner (const ArrOfInt &request_sommets_pe, const ArrOfInt &request_sommets_num)
virtual void deplacer_sommets (const ArrOfInt &liste_sommets_initiale, const DoubleTab &deplacement_initial, ArrOfInt &liste_sommets_sortis, ArrOfInt &numero_face_sortie, int skip_facettes=0)
void echanger_facettes (const ArrOfInt &liste_facettes, const ArrOfInt &liste_elem_arrivee, ArrOfInt &facettes_recues_numfacettes, ArrOfInt &facettes_recues_numelement)
void echanger_sommets_PE (const ArrOfInt &liste_sommets, const ArrOfInt &liste_elem_virtuel_arrivee, const ArrOfInt &liste_face_virtuelle_arrivee, const DoubleTab &deplacement, ArrOfInt &liste_nouveaux_sommets, DoubleTab &deplacement_restant, int skip_facettes=0)
void maillage_modifie (Statut_Maillage nouveau_statut)
Maillage_FT_Disc_Data_Cache & mesh_data_cache () const
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
un tableau de coordonnees des sommets, un tableau de facettes, drapeaux, intersections facettes / elements ...
Member Enumeration Documentation
Statut_Maillage
enum Maillage_FT_Disc::Statut_Maillage
Enumerator
RESET
MINIMAL
PARCOURU
COMPLET
AjoutPhase
enum Maillage_FT_Disc::AjoutPhase
Enumerator
AJOUTE_TOUTES_PHASES
AJOUTE_PHASE0
AJOUTE_PHASE1
enum_methode_calcul_courbure_contact_line_
enum Maillage_FT_Disc::enum_methode_calcul_courbure_contact_line_ protected
Enumerator
STANDARD
MIRROR
IMPROVED
none
WEIGHTED
HYSTERESIS
Constructor & Destructor Documentation
~Maillage_FT_Disc()
Maillage_FT_Disc::~Maillage_FT_Disc ()
Maillage_FT_Disc() [1/2]
Maillage_FT_Disc::Maillage_FT_Disc ()
constructeur par defaut.
References mesh_data_cache_, and Objet_U_ptr::typer().
Maillage_FT_Disc() [2/2]
Maillage_FT_Disc::Maillage_FT_Disc (const Maillage_FT_Disc &)
La construction par copie est interdite !
References Process::exit().
Member Function Documentation
cree_instance()
Objet_U * Maillage_FT_Disc::cree_instance () static
taille_memoire()
unsigned Maillage_FT_Disc::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Maillage_FT_IJK.
duplique()
int Maillage_FT_Disc::duplique () const override virtual
Implements Objet_U.
Reimplemented in Maillage_FT_IJK.
info()
const Type_info * Maillage_FT_Disc::info () static
get_info()
const Type_info * Maillage_FT_Disc::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Ensemble_Lagrange_base.
Reimplemented in Maillage_FT_IJK.
self_cast() [1/2]
Maillage_FT_Disc & Maillage_FT_Disc::self_cast (Objet_U & r) static
self_cast() [2/2]
const Maillage_FT_Disc & Maillage_FT_Disc::self_cast (const Objet_U & r) static
printOn()
Sortie & Maillage_FT_Disc::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Ensemble_Lagrange_base.
Reimplemented in Maillage_FT_IJK.
readOn()
Entree & Maillage_FT_Disc::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Ensemble_Lagrange_base.
Reimplemented in Maillage_FT_IJK.
References Objet_U::dimension, TRUST_Vector< _CLASSE_ >::dimensionner(), Process::exit(), Process::je_suis_maitre(), Ensemble_Lagrange_base::nb_marqs_par_dir, Ensemble_Lagrange_base::nb_marqs_sz, Ensemble_Lagrange_base::nom_sz, Entree_Fichier_base::ouvrir(), Objet_U::que_suis_je(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), Motcles::search(), TRUST_Vector< _CLASSE_ >::size(), and Ensemble_Lagrange_base::sommets_lu_.
reprendre()
int Maillage_FT_Disc::reprendre (Entree &) override virtual
Reprise d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree&) flot d'entree a utiliser pour la reprise
Returns
(int) code de retour
Reimplemented from Objet_U.
References Desc_Structure_FT::calcul_schema_comm(), check_mesh(), desc_facettes_, desc_sommets_, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), drapeaux_sommets_, Process::exit(), facette_num_owner_, facettes_, EcritureLectureSpecial::is_lecture_special(), TRUST_2_PDI::is_PDI_restart(), Sauvegarde_Reprise_Maillage_FT::lire_xyz(), maillage_modifie(), mesh_state_tag_, MINIMAL, TRUST_Ref< _CLASSE_ >::non_nul(), Objet_U::que_suis_je(), refdomaine_dis_, reset(), sommet_elem_, sommet_face_bord_, sommet_num_owner_, sommet_PE_owner_, sommets_, temps_physique_, TRUST_Ref< _CLASSE_ >::valeur(), and voisins_.
Referenced by Transport_Interfaces_FT_Disc_interne::reprendre().
sauvegarder()
int Maillage_FT_Disc::sauvegarder (Sortie &) const override virtual
Sauvegarde d'un Objet_U sur un flot de sortie Methode a surcharger.
Parameters
(Sortie&) flot de sortie a utiliser pour la sauvegarde
Returns
(int) code de retour
Reimplemented from Objet_U.
References desc_facettes_, desc_sommets_, drapeaux_sommets_, Sauvegarde_Reprise_Maillage_FT::ecrire_xyz(), Process::exit(), facette_num_owner_, facettes_, Sortie::get_ostream(), EcritureLectureSpecial::is_ecriture_special(), TRUST_2_PDI::is_PDI_checkpoint(), mesh_state_tag_, Sortie::precision(), Objet_U::que_suis_je(), refdomaine_dis_, TRUSTArray< _TYPE_, _SIZE_ >::size_array(), sommet_elem_, sommet_face_bord_, sommet_num_owner_, sommet_PE_owner_, sommets_, temps_physique_, TRUST_Ref< _CLASSE_ >::valeur(), and voisins_.
Referenced by Transport_Interfaces_FT_Disc_interne::sauvegarder().
lire_param_maillage()
Entree & Maillage_FT_Disc::lire_param_maillage (Entree & is) virtual
Cette fonction permet de lire les parametres pour le maillage des interfaces.
Parameters
(is) flot d'entree
Returns
(Entree) le flot d'entree
References Param::ajouter(), calcul_courbure_iterations_, correction_contact_courbure_coeff_, Param::dictionnaire(), HYSTERESIS, IMPROVED, Param::lire_avec_accolades(), methode_calcul_courbure_contact_line_, MIRROR, niter_pre_lissage_, niveau_plot_, STANDARD, weight_CL_, and WEIGHTED.
Referenced by Transport_Interfaces_FT_Disc::lire_motcle_non_standard().
ajouter_maillage()
void Maillage_FT_Disc::ajouter_maillage (const Maillage_FT_Disc & maillage_tmp, int skip_facettes = 0) virtual
Reimplemented in Maillage_FT_IJK.
References Descripteur_FT::ajoute_elements(), Descripteur_FT::calcul_liste_pe_voisins(), Desc_Structure_FT::calcul_schema_comm(), check_mesh(), desc_facettes(), desc_facettes_, desc_sommets(), desc_sommets_, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, drapeaux_sommets_, Desc_Structure_FT::echange_espace_virtuel(), Descripteur_FT::elements(), Desc_Structure_FT::espace_distant(), Desc_Structure_FT::espace_virtuel(), facette_num_owner_, facettes(), facettes_, maillage_modifie(), MINIMAL, nb_facettes(), nb_sommets(), Descripteur_FT::pe_voisins(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), sommet_elem_, sommet_face_bord_, sommet_num_owner_, sommet_PE_owner(), sommet_PE_owner_, sommets(), sommets_, and statut_.
Referenced by Maillage_FT_IJK::ajouter_maillage_IJK(), Transport_Marqueur_FT::ajouter_points(), Transport_Interfaces_FT_Disc::lire_cond_init(), Transport_Interfaces_FT_Disc::mettre_a_jour(), and Topologie_Maillage_FT::remailler_interface().
recopie()
void Maillage_FT_Disc::recopie (const Maillage_FT_Disc & source, Statut_Maillage niveau_copie) virtual
Recopie une partie du maillage source dans *this.
Si niveau_copie == MINIMAL, seuls les membres de l'etat minimal sont copies.
Reimplemented in Maillage_FT_IJK.
References Maillage_FT_Disc_Data_Cache::courbure_sommets_, desc_facettes_, desc_sommets_, drapeaux_sommets_, facette_num_owner_, facettes_, get_update_courbure_sommets(), get_update_normale_facettes(), get_update_surface_facettes(), intersections_elem_facettes(), intersections_elem_facettes_, maillage_modifie(), mesh_data_cache(), MINIMAL, Maillage_FT_Disc_Data_Cache::normale_facettes_, refdomaine_dis_, refequation_transport_, refparcours_interface_, RESET, reset(), schema_comm_domaine_, sommet_elem_, sommet_face_bord_, sommet_num_owner_, sommet_PE_owner_, sommets_, Maillage_FT_Disc_Data_Cache::surface_facettes_, temps_physique_, and voisins_.
Referenced by Maillage_FT_IJK::recopie(), and Topologie_Maillage_FT::remailler_interface().
equation_associee()
const Equation_base & Maillage_FT_Disc::equation_associee () const override virtual
Implements Ensemble_Lagrange_base.
References equation_transport().
temps()
double Maillage_FT_Disc::temps () const
return temps_physique_ (temps_physique_ ne sert a rien en interne.
..)
References temps_physique_.
Referenced by Transport_Interfaces_FT_Disc::deplacer_maillage_ft_v_fluide(), Transport_Interfaces_FT_Disc::mettre_a_jour(), Remaillage_FT::regulariser_courbure(), and Remailleur_Collision_FT_Thomas::traite_RuptureCoalescenceInterfaces_Conservatif().
changer_temps()
double Maillage_FT_Disc::changer_temps (double t)
return temps_physique_ = t
References temps_physique_.
Referenced by Transport_Interfaces_FT_Disc::deplacer_maillage_ft_v_fluide(), Transport_Interfaces_FT_Disc::discretiser(), Transport_Marqueur_FT::integrer_ensemble_lagrange(), Transport_Interfaces_FT_Disc::mettre_a_jour(), and Transport_Interfaces_FT_Disc::transporter_sans_changement_topologie().
get_mesh_tag()
int Maillage_FT_Disc::get_mesh_tag () const
return mesh_state_tag_
References mesh_state_tag_.
Referenced by Triple_Line_Model_FT_Disc::compute_TCL_fluxes_in_all_boundary_cells(), Convection_Diffusion_Temperature_FT_Disc::derivee_en_temps_inco(), Triple_Line_Model_FT_Disc::elems(), Transport_Interfaces_FT_Disc::get_mesh_tag(), get_update_courbure_sommets(), Transport_Interfaces_FT_Disc::get_update_distance_interface(), Transport_Interfaces_FT_Disc::get_update_distance_interface_faces(), Transport_Interfaces_FT_Disc::get_update_distance_interface_sommets(), Transport_Interfaces_FT_Disc::get_update_indicatrice(), get_update_normale_facettes(), Transport_Interfaces_FT_Disc::get_update_normale_interface(), get_update_surface_facettes(), and Triple_Line_Model_FT_Disc::initialize().
sommets()
const DoubleTab & Maillage_FT_Disc::sommets () const
renvoie le tableau des sommets (reels et virtuels) dimension(0) = nombre de sommets,
dimension(1) = dimension du probleme (2 ou 3) contenu = coordonnees des sommets
References MINIMAL, sommets_, and statut_.
Referenced by Source_Reaction_Particules_VDF::ajouter(), Source_Reaction_Particules_VEF::ajouter(), ajouter_maillage(), Transport_Interfaces_FT_Disc::BaryFa7(), Transport_Interfaces_FT_Disc::calcul_eq_plan_facette(), Transport_Interfaces_FT_Disc::calcul_nb_traverse(), IJK_Interfaces::calculer_aspect_ratio(), Remaillage_FT::calculer_barycentre_facettes_voisines(), IJK_Interfaces::calculer_bounding_box_bulles(), Maillage_FT_IJK::calculer_compo_connexe_sommets(), Remaillage_FT::calculer_differentielle_volume(), IJK_Interfaces::calculer_distance_autres_compo_connexe2(), IJK_Interfaces::calculer_distance_autres_compo_connexe_octree(), Transport_Interfaces_FT_Disc::calculer_distance_interface(), ComputeValParCompoInCell::calculer_indic_elem_pour_compo(), Remaillage_FT::calculer_longueurIdeale2_arete(), Remaillage_FT_IJK::calculer_longueurIdeale2_arete(), ComputeValParCompoInCell::calculer_moyennes_interface_element_pour_compo(), IJK_Interfaces::calculer_phi_repuls_sommet(), Transport_Marqueur_FT::calculer_proprietes_fluide_pos_particules(), Transport_Interfaces_FT_Disc::calculer_scalaire_interpole(), IJK_Interfaces::calculer_var_volume_remaillage(), Remaillage_FT::calculer_variation_volume_facette_2D(), Remaillage_FT::calculer_variation_volume_facette_3D(), Transport_Interfaces_FT_Disc::calculer_vitesse_transport_interpolee(), Transport_Interfaces_FT_Disc::calculer_vmoy_composantes_connexes(), IJK_Interfaces::calculer_vmoy_rotation_composantes_connexes(), Remaillage_FT::calculer_volume_sommets_supprimes(), Triple_Line_Model_FT_Disc::compute_approximate_interface_inout(), IJK_Interfaces::compute_cell_phase_with_interface_normal(), IJK_Interfaces::compute_drapeaux_vapeur_v4(), IJK_Thermal_base::compute_interfacial_temperature2(), DebogFT::compute_signature_sommets(), Triple_Line_Model_FT_Disc::compute_TCL_fluxes_in_all_boundary_cells(), IJK_Interfaces::compute_vinterp(), Transport_Interfaces_FT_Disc::deplacer_maillage_ft_v_fluide(), IJK_Interfaces::dumplata_ft_mesh(), Postraitement_ft_lata::ecrire_maillage_ft_disc(), FT_Field::exchange_data(), Triple_Line_Model_FT_Disc::get_in_out_coords(), SurfaceVapeurIJKComputation::get_maillage_MED_from_IJK_FT(), Transport_Marqueur_FT::imposer_cond_lim(), Transport_Interfaces_FT_Disc::init_particles_position_velocity(), FT_Field::initialize(), Transport_Interfaces_FT_Disc::mettre_a_jour(), Maillage_FT_IJK::minimum_longueur_arrete(), Operator_FT_Disc::Operator_integral_bord_facette_phi_p_dl(), Operator_FT_Disc::Operator_Laplacian_FT_element(), Parcours_interface::parcourir(), Transport_Interfaces_FT_Disc::plan_facette_existant(), Postraitement_ft_lata::postprocess_field_values(), IJK_Interfaces::posttraiter_champs_instantanes(), Transport_Interfaces_FT_Disc::PPP_face_interface(), Remaillage_FT::redistribuer_sommets(), Remaillage_FT::regulariser_courbure(), IJK_One_Dimensional_Subproblems_Interfaces_Fields::retrieve_interfacial_surface_quantity(), Remaillage_FT::supprimer_facettes_bord(), Remaillage_FT::supprimer_petites_aretes(), Remaillage_FT_IJK::supprimer_petites_aretes(), Topologie_Maillage_FT::test_intersection_facettes_2D(), Topologie_Maillage_FT::test_intersection_facettes_3D(), Remaillage_FT::traite_decollement(), IJK_Interfaces::transporter_maillage_deformation(), IJK_Interfaces::transporter_maillage_remaillage(), IJK_Interfaces::transporter_maillage_rigide(), Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_face_sommets(), Transport_Marqueur_FT::update_delta_v(), and FT_Field::update_sigma_and_interfacial_source_term_sommet().
nb_sommets()
int Maillage_FT_Disc::nb_sommets () const
renvoie le nombre de sommets (reels et virtuels) (egal a sommets().
dimension(0))
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), MINIMAL, sommets_, and statut_.
Referenced by ajouter_maillage(), Remaillage_FT::barycentrer_lisser_systematique(), Remaillage_FT_IJK::barycentrer_lisser_systematique_ijk(), calcul_courbure_sommets(), Remaillage_FT::calculer_barycentre_facettes_voisines(), Navier_Stokes_FT_Disc::calculer_champ_forces_superficielles(), Remaillage_FT::calculer_connectivites_sommetFacettes(), calculer_costheta_minmax(), Maillage_FT_IJK::calculer_costheta_minmax(), Remaillage_FT::calculer_differentielle_volume(), IJK_Interfaces::calculer_phi_repuls_par_compo(), Transport_Marqueur_FT::calculer_valeurs_densite(), Transport_Marqueur_FT::calculer_valeurs_volumes(), Remaillage_FT::calculer_variation_volume(), Remaillage_FT::calculer_volume_sommets_supprimes(), FT_Field::champ_sommet_from_facettes(), check_sommets(), Maillage_FT_IJK::check_sommets(), FT_Field::completer_compo_connexe_partielle(), Operator_FT_Disc::Compute_interfaciale_source(), DebogFT::compute_signature_sommets(), copier_sommet(), creer_sommets_virtuels_numowner(), Transport_Interfaces_FT_Disc::deplacer_maillage_ft_v_fluide(), Remaillage_FT::diviser_grandes_aretes(), Remaillage_FT_IJK::diviser_grandes_aretes(), IJK_Interfaces::dumplata_ft_mesh(), Sauvegarde_Reprise_Maillage_FT::ecrire_xyz(), Parcours_interface::eloigner_sommets_des_faces(), Operator_FT_Disc::Facette_to_Sommets(), Triple_Line_Model_FT_Disc::get_any_tcl_face(), Transport_Interfaces_FT_Disc::get_champ_post_FT(), SurfaceVapeurIJKComputation::get_maillage_MED_from_IJK_FT(), Maillage_FT_IJK::lire_maillage_ft_dans_lata(), Sauvegarde_Reprise_Maillage_FT::lire_xyz(), Remaillage_FT::marquer_aretes(), Transport_Interfaces_FT_Disc::mettre_a_jour(), nettoyer_maillage(), nettoyer_noeuds_virtuels_et_frontieres(), nettoyer_phase(), Operator_FT_Disc::Operator_Gradient_FT_sommets(), Operator_FT_Disc::Operator_integral_bord_facette_phi_p_dl(), Probleme_FTD_IJK_base::parcourir_maillage(), Remaillage_FT::redistribuer_sommets(), Remaillage_FT::regulariser_courbure(), Remaillage_FT::regulariser_maillage(), Remaillage_FT::remaillage_local_interface(), Remaillage_FT_IJK::remaillage_local_interface(), Operator_FT_Disc::Sommets_to_Facettes(), Remaillage_FT::supprimer_doublons_facettes(), Remaillage_FT::supprimer_petites_aretes(), Remaillage_FT_IJK::supprimer_petites_aretes(), Remaillage_FT::traite_decollement(), Remailleur_Collision_FT_Thomas::traite_RuptureCoalescenceInterfaces_Conservatif(), Transport_Interfaces_FT_Disc::transfert_conservatif_eulerien_vers_lagrangien_sommets(), Remailleur_Collision_FT_Thomas::transport_volume_perdu_sur_sommet(), transporter(), IJK_Interfaces::transporter_maillage_remaillage(), Transport_Interfaces_FT_Disc::transporter_sans_changement_topologie(), transporter_simple(), FT_Field::update_Field_sommets(), FT_Field::update_sigma_and_interfacial_source_term_sommet(), Transport_Marqueur_FT::update_tableaux_apres_transport(), DebogFT::verifier_maillage_ft(), and DebogFT::verifier_tableau_sommets().
facettes()
const IntTab & Maillage_FT_Disc::facettes () const
renvoie le tableau des facettes (reelles et virtuelles) dimension(0) = nombre de facettes,
dimension(1) = nombre de sommets par facette (2 en 2D, 3 en 3D) contenu = numero des sommets de chaque facette dans le tableau des sommets
References facettes_, MINIMAL, and statut_.
Referenced by ajouter_maillage(), Transport_Interfaces_FT_Disc::BaryFa7(), Transport_Interfaces_FT_Disc::calcul_eq_plan_facette(), Transport_Interfaces_FT_Disc::calcul_nb_traverse(), IJK_Interfaces::calculer_aspect_ratio(), Remaillage_FT::calculer_barycentre_facettes_voisines(), Remaillage_FT::calculer_connectivites_sommetFacettes(), Remaillage_FT::calculer_differentielle_volume(), IJK_Interfaces::calculer_distance_autres_compo_connexe_ijk(), IJK_Interfaces::calculer_distance_autres_compo_connexe_octree(), Transport_Interfaces_FT_Disc::calculer_distance_interface(), ComputeValParCompoInCell::calculer_indic_elem_pour_compo(), IJK_Interfaces::calculer_kappa_ft(), ComputeValParCompoInCell::calculer_moy_field_sommet_par_compo(), ComputeValParCompoInCell::calculer_moyennes_interface_element_pour_compo(), IJK_Interfaces::calculer_normales_et_aires_interfaciales(), ComputeValParCompoInCell::calculer_somme_field_sommet_par_compo(), Remaillage_FT::calculer_variation_volume(), Remaillage_FT::calculer_variation_volume_facette_2D(), Remaillage_FT::calculer_variation_volume_facette_3D(), Transport_Interfaces_FT_Disc::calculer_vitesse_repere_local(), Transport_Interfaces_FT_Disc::calculer_vitesse_transport_interpolee(), Transport_Interfaces_FT_Disc::calculer_vmoy_composantes_connexes(), IJK_Interfaces::calculer_vmoy_rotation_composantes_connexes(), IJK_Interfaces::calculer_vmoy_translation_composantes_connexes(), Remaillage_FT::calculer_volume_sommets_supprimes(), FT_Field::champ_sommet_from_facettes(), Triple_Line_Model_FT_Disc::compute_approximate_interface_inout(), IJK_Interfaces::compute_cell_phase_with_interface_normal(), IJK_Interfaces::compute_drapeaux_vapeur_v4(), IJK_Thermal_base::compute_interfacial_temperature2(), Triple_Line_Model_FT_Disc::compute_TCL_fluxes_in_all_boundary_cells(), Transport_Interfaces_FT_Disc::deplacer_maillage_ft_v_fluide(), IJK_Interfaces::dumplata_ft_mesh(), Postraitement_ft_lata::ecrire_maillage_ft_disc(), FT_Field::exchange_data(), Operator_FT_Disc::Facette_to_Sommets(), Postraitement_ft_lata::filter_out_virtual_fa7(), Triple_Line_Model_FT_Disc::get_in_out_coords(), SurfaceVapeurIJKComputation::get_maillage_MED_from_IJK_FT(), Transport_Interfaces_FT_Disc::init_particles_position_velocity(), FT_Field::initialize(), Remaillage_FT::lisser_dvolume(), Remaillage_FT::marquer_aretes(), FT_Field::nettoyer_espace_virtuel_facette(), Operator_FT_Disc::Operator_integral_bord_facette_phi_p_dl(), Operator_FT_Disc::Operator_Laplacian_FT_element(), Transport_Interfaces_FT_Disc::plan_facette_existant(), Postraitement_ft_lata::postprocess_field_values(), Transport_Interfaces_FT_Disc::PPP_face_interface(), Remaillage_FT::regulariser_courbure(), IJK_One_Dimensional_Subproblems_Interfaces_Fields::retrieve_interfacial_surface_quantity(), Operator_FT_Disc::Sommets_to_Facettes(), Topologie_Maillage_FT::test_intersection_facettes_2D(), Topologie_Maillage_FT::test_intersection_facettes_3D(), Remaillage_FT::traite_decollement(), Transport_Interfaces_FT_Disc::transfert_conservatif_eulerien_vers_lagrangien_sommets(), Remailleur_Collision_FT_Thomas::transport_volume_perdu_sur_sommet(), IJK_Interfaces::transporter_maillage_remaillage(), FT_Field::update_Field_sommets(), and FT_Field::update_sigma_and_interfacial_source_term_sommet().
nb_facettes()
int Maillage_FT_Disc::nb_facettes () const
renvoie le nombre de facettes (reelles et virtuelles) (egal a facettes().
dimension(0))
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), facettes_, MINIMAL, and statut_.
Referenced by ajouter_maillage(), Maillage_FT_IJK::ajouter_maillage_IJK(), Facettes_Interp_FT::calcul_coefficient_interpolation_facette_cut_cell(), Facettes_Interp_FT::calcul_coefficient_interpolation_facette_cut_cell_second_order(), calcul_courbure_sommets(), IJK_Interfaces::calculer_aire_interfaciale(), IJK_Interfaces::calculer_aire_interfaciale_for_compo(), IJK_Interfaces::calculer_aspect_ratio(), Remaillage_FT::calculer_barycentre_facettes_voisines(), IJK_Interfaces::calculer_color(), Remaillage_FT::calculer_connectivites_sommetFacettes(), Navier_Stokes_FT_Disc::calculer_delta_u_interface(), Remaillage_FT::calculer_differentielle_volume(), IJK_Interfaces::calculer_kappa_ft(), IJK_Interfaces::calculer_normales_et_aires_interfaciales(), IJK_Interfaces::calculer_poussee_bulles(), IJK_Interfaces::calculer_surface_bulles(), IJK_Interfaces::calculer_surfactant(), Remaillage_FT::calculer_variation_volume(), Transport_Interfaces_FT_Disc::calculer_vitesse_repere_local(), Transport_Interfaces_FT_Disc::calculer_vitesse_transport_interpolee(), IJK_Interfaces::calculer_vmoy_rotation_composantes_connexes(), IJK_Interfaces::calculer_vmoy_translation_composantes_connexes(), calculer_voisinage_facettes(), IJK_Interfaces::calculer_volume_bulles(), FT_Field::calculer_volume_bulles(), Remaillage_FT::calculer_volume_sommets_supprimes(), FT_Field::check_conservation(), check_mesh(), Maillage_FT_IJK::check_mesh(), FT_Field::completer_compo_connexe_partielle(), IJK_Interfaces::compute_drapeaux_vapeur_v4(), compute_gravity_center_fa7(), Post_Processing_Hydrodynamic_Forces::compute_heat_transfer(), Post_Processing_Hydrodynamic_Forces::compute_hydrodynamic_forces(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_hydrodynamic_forces(), IJK_Thermal_base::compute_interfacial_temperature2(), Operator_FT_Disc::Compute_interfaciale_source(), IJK_Interfaces::compute_surface_average_per_bubble(), FT_Field::correction_conservation_globale(), Maillage_FT_IJK::creer_facettes_virtuelles(), Transport_Interfaces_FT_Disc::deplacer_maillage_ft_v_fluide(), IJK_Interfaces::detecter_et_supprimer_rejeton(), Remaillage_FT::diviser_grandes_aretes(), Remaillage_FT_IJK::diviser_grandes_aretes(), IJK_Interfaces::dumplata_ft_mesh(), IJK_Interfaces::dupliquer_bulle_perio(), Sauvegarde_Reprise_Maillage_FT::ecrire_xyz(), FT_Field::exchange_compo_connexe(), FT_Field::exchange_data(), Operator_FT_Disc::Facette_to_Sommets(), Transport_Interfaces_FT_Disc::get_champ_post_FT(), SurfaceVapeurIJKComputation::get_maillage_MED_from_IJK_FT(), Transport_Interfaces_FT_Disc::init_particles_position_velocity(), FT_Field::initialize(), Maillage_FT_IJK::lire_maillage_ft_dans_lata(), Sauvegarde_Reprise_Maillage_FT::lire_xyz(), Remaillage_FT::lisser_dvolume(), Remaillage_FT::marquer_aretes(), Transport_Interfaces_FT_Disc::mettre_a_jour(), Remailleur_Collision_FT_Thomas::mettre_a_jour_data(), Remaillage_FT::nettoyer_maillage(), Operator_FT_Disc::Operator_Gradient_FT_sommets(), Operator_FT_Disc::Operator_integral_bord_facette_phi_p_dl(), Operator_FT_Disc::Operator_Laplacian_FT_element(), IJK_Thermal_base::posttraiter_champs_instantanes_thermal_interface_ref(), Maillage_FT_IJK::recopie_force_compo(), Maillage_FT_IJK::sauv_facette_indexation_avant_transport(), Operator_FT_Disc::Sommets_to_Facettes(), Topologie_Maillage_FT::suppression_interfaces(), IJK_Interfaces::supprimer_certaines_bulles_reelles(), Remaillage_FT::supprimer_doublons_facettes(), IJK_Interfaces::supprimer_duplicata_bulles(), Remaillage_FT::supprimer_facettes_bord(), Remaillage_FT::supprimer_facettes_nulles(), Topologie_Maillage_FT::test_collision_facettes(), Remaillage_FT::traite_decollement(), Remailleur_Collision_FT_Thomas::transport_volume_perdu_sur_sommet(), IJK_Interfaces::transporter_maillage_remaillage(), FT_Field::update_Field_sommets(), FT_Field::update_FT_Field_local_from_full_compo(), Maillage_FT_IJK::update_sigma_and_interfacial_source_term_sommet(), FT_Field::update_sigma_and_interfacial_source_term_sommet(), and Maillage_FT_IJK::update_surfactant_apres_transport().
nb_facettes_reelle_totale()
int Maillage_FT_Disc::nb_facettes_reelle_totale () const
References Process::check_int_overflow(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), facette_virtuelle(), facettes_, MINIMAL, Process::mp_sum(), and statut_.
nb_facettes_reelles()
int Maillage_FT_Disc::nb_facettes_reelles () const
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), facette_virtuelle(), facettes_, MINIMAL, and statut_.
nb_facettes_totale()
int Maillage_FT_Disc::nb_facettes_totale () const
References Process::check_int_overflow(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), facettes_, MINIMAL, Process::mp_sum(), and statut_.
drapeaux_sommets()
const ArrOfInt & Maillage_FT_Disc::drapeaux_sommets () const
Pour postraitement uniquement : la signification precise des drapeaux est de la cuisine interne a la classe.
..
References drapeaux_sommets_, MINIMAL, and statut_.
sommet_PE_owner()
const ArrOfInt & Maillage_FT_Disc::sommet_PE_owner () const
pour postraitement, renvoie le numero du PE proprietaire des sommets
References MINIMAL, sommet_PE_owner_, and statut_.
Referenced by ajouter_maillage(), Remaillage_FT::calculer_variation_volume_facette_2D(), IJK_Interfaces::dumplata_ft_mesh(), and Transport_Interfaces_FT_Disc::get_champ_post_FT().
sommet_num_owner()
const ArrOfInt & Maillage_FT_Disc::sommet_num_owner () const
pour postraitement, renvoie le numero des sommets sur le PE proprietaire des sommets
References MINIMAL, sommet_num_owner_, and statut_.
Referenced by IJK_Interfaces::dumplata_ft_mesh(), Remaillage_FT::supprimer_petites_aretes(), and Remaillage_FT_IJK::supprimer_petites_aretes().
facette_PE_owner()
void Maillage_FT_Disc::facette_PE_owner (ArrOfInt & facette_pe) const
pour postraitement, remplit le tableau en parametre avec le numero du PE proprietaire de chaque facette.
References desc_facettes_, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), facettes_, MINIMAL, Desc_Structure_FT::remplir_element_pe(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), and statut_.
Referenced by IJK_Interfaces::dumplata_ft_mesh(), and Transport_Interfaces_FT_Disc::get_champ_post_FT().
sommet_elem()
const ArrOfInt & Maillage_FT_Disc::sommet_elem () const
pour postraitement, renvoie sommet_elem_
References MINIMAL, sommet_elem_, and statut_.
Referenced by Source_Reaction_Particules_VDF::ajouter(), Source_Reaction_Particules_VEF::ajouter(), Transport_Marqueur_FT::calculer_proprietes_fluide_pos_particules(), Transport_Interfaces_FT_Disc::calculer_scalaire_interpole(), Transport_Marqueur_FT::calculer_valeurs_densite(), Transport_Marqueur_FT::calculer_valeurs_volumes(), Transport_Interfaces_FT_Disc::calculer_vitesse_transport_interpolee(), Transport_Marqueur_FT::imposer_cond_lim(), Remaillage_FT::regulariser_courbure(), IJK_One_Dimensional_Subproblems_Interfaces_Fields::retrieve_interfacial_surface_quantity(), and Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_face_sommets().
sommet_face_bord() [1/2]
const ArrOfInt & Maillage_FT_Disc::sommet_face_bord () const
pour postraitement, renvoie sommet_face_bord_
References MINIMAL, sommet_face_bord_, and statut_.
Referenced by Triple_Line_Model_FT_Disc::get_any_tcl_face(), and Transport_Marqueur_FT::imposer_cond_lim().
desc_sommets()
const Desc_Structure_FT & Maillage_FT_Disc::desc_sommets () const
renvoie le descripteur des sommets (espace_distant/virtuel)
References desc_sommets_, MINIMAL, and statut_.
Referenced by ajouter_maillage(), calcul_courbure_sommets(), Remaillage_FT::calculer_barycentre_facettes_voisines(), Remaillage_FT::calculer_differentielle_volume(), Remaillage_FT::calculer_variation_volume(), IJK_Interfaces::calculer_vecteurs_de_deplacement_rigide(), Transport_Interfaces_FT_Disc::calculer_vitesse_transport_interpolee(), FT_Field::champ_sommet_from_facettes(), IJK_Interfaces::compute_external_forces_(), Operator_FT_Disc::Compute_interfaciale_source(), creer_tableau_sommets(), Transport_Interfaces_FT_Disc::deplacer_maillage_ft_v_fluide(), Remaillage_FT::diviser_grandes_aretes(), Remaillage_FT_IJK::diviser_grandes_aretes(), Sauvegarde_Reprise_Maillage_FT::ecrire_xyz(), Parcours_interface::eloigner_sommets_des_faces(), Operator_FT_Disc::Facette_to_Sommets(), Sauvegarde_Reprise_Maillage_FT::lire_xyz(), Remaillage_FT::lisser_dvolume(), Remaillage_FT::marquer_aretes(), Operator_FT_Disc::Operator_Gradient_FT_sommets(), Operator_FT_Disc::Operator_integral_bord_facette_phi_p_dl(), Parcours_interface::parcourir(), Transport_Marqueur_FT::preparer_tableaux_avant_transport(), Remaillage_FT::redistribuer_sommets(), Remaillage_FT::regulariser_courbure(), IJK_Interfaces::RK3_G_store_vi_echange_esp_vect(), Remaillage_FT::supprimer_petites_aretes(), Remaillage_FT_IJK::supprimer_petites_aretes(), Remaillage_FT::traite_decollement(), Transport_Interfaces_FT_Disc::transfert_conservatif_eulerien_vers_lagrangien_sommets(), Remailleur_Collision_FT_Thomas::transport_volume_perdu_sur_sommet(), IJK_Interfaces::transporter_maillage_deformation(), IJK_Interfaces::transporter_maillage_remaillage(), Transport_Interfaces_FT_Disc::transporter_sans_changement_topologie(), FT_Field::update_Field_sommets(), and Transport_Marqueur_FT::update_tableaux_apres_transport().
desc_facettes()
const Desc_Structure_FT & Maillage_FT_Disc::desc_facettes () const
renvoie le descripteur des facettes (espace_distant/virtuel)
References desc_facettes_, MINIMAL, and statut_.
Referenced by ajouter_maillage(), FT_Field::avancer_en_temps(), check_mesh(), Maillage_FT_IJK::creer_facettes_virtuelles(), creer_tableau_elements(), FT_Field::echange_espace_virtuel(), FT_Field::initialize(), Operator_FT_Disc::Operator_Laplacian_FT_element(), FT_Field::passer_variable_extensive(), FT_Field::passer_variable_intensive(), Operator_FT_Disc::Sommets_to_Facettes(), Remaillage_FT::supprimer_doublons_facettes(), and FT_Field::update_sigma_and_interfacial_source_term_sommet().
intersections_elem_facettes()
const Intersections_Elem_Facettes & Maillage_FT_Disc::intersections_elem_facettes () const
References intersections_elem_facettes_, PARCOURU, and statut_.
Referenced by Transport_Interfaces_FT_Disc::calcul_maxfa7(), Transport_Interfaces_FT_Disc::calcul_nb_traverse(), Transport_Interfaces_FT_Disc::calcul_OutElemFa7(), IJK_Interfaces::calculer_aire_interfaciale(), IJK_Interfaces::calculer_aire_interfaciale_for_compo(), IJK_Interfaces::calculer_barycentre(), Navier_Stokes_FT_Disc::calculer_delta_u_interface(), Transport_Interfaces_FT_Disc::calculer_distance_interface(), Navier_Stokes_FT_Disc::calculer_gradient_indicatrice(), ComputeValParCompoInCell::calculer_indic_elem_pour_compo(), IJK_Interfaces::calculer_indicatrice(), IJK_Interfaces::calculer_indicatrice_optim(), IJK_Interfaces::calculer_indicatrice_surfacique_barycentre_face(), IJK_Interfaces::calculer_indicatrice_surfacique_face(), IJK_Interfaces::calculer_indicatrices(), IJK_Interfaces::calculer_indicatrices_optim(), IJK_Interfaces::calculer_kappa_ft(), ComputeValParCompoInCell::calculer_moy_field_fa7_par_compo(), ComputeValParCompoInCell::calculer_moy_field_sommet_par_compo(), ComputeValParCompoInCell::calculer_moyennes_interface_element_pour_compo(), IJK_Interfaces::calculer_normales_et_aires_interfaciales(), ComputeValParCompoInCell::calculer_somme_field_sommet_par_compo(), IJK_Interfaces::calculer_surface_interface(), Triple_Line_Model_FT_Disc::compute_approximate_interface_inout(), IJK_Interfaces::compute_cell_phase_with_interface_normal(), IJK_Interfaces::compute_drapeaux_vapeur_v4(), ComputeValParCompoInCell::compute_list_compo_connex_in_element(), compute_normale_element(), compute_surface_and_normale_element(), Triple_Line_Model_FT_Disc::compute_TCL_fluxes_in_all_boundary_cells(), IJK_Composantes_Connex::fill_mixed_cell_compo(), Transport_Interfaces_FT_Disc::get_champ_post_FT(), Triple_Line_Model_FT_Disc::get_in_out_coords(), Transport_Interfaces_FT_Disc::lire_maillage_ft_cao(), Transport_Interfaces_FT_Disc::mettre_a_jour(), Remailleur_Collision_FT_Thomas::mettre_a_jour_data(), Transport_Interfaces_FT_Disc::PPP_face_interface(), recopie(), IJK_One_Dimensional_Subproblems_Interfaces_Fields::retrieve_interfacial_surface_quantity(), Transport_Interfaces_FT_Disc::StockageFa7(), Topologie_Maillage_FT::test_collision_facettes(), Transport_Interfaces_FT_Disc::transfert_conservatif_eulerien_vers_lagrangien_sommets(), and Remailleur_Collision_FT_Thomas::transport_volume_perdu_sur_sommet().
som_init_util()
const ArrOfInt & Maillage_FT_Disc::som_init_util () const
return som_init_util_
References som_init_util_.
Referenced by Transport_Marqueur_FT::completer(), and Transport_Marqueur_FT::construction_ensemble_proprietes().
sommet_virtuel()
int Maillage_FT_Disc::sommet_virtuel (int i) const inline
References sommet_elem_.
Referenced by calcul_courbure_sommets(), Remaillage_FT::calculer_barycentre_facettes_voisines(), check_sommets(), Operator_FT_Disc::Compute_interfaciale_source(), DebogFT::compute_signature_sommets(), creer_sommets_virtuels(), Maillage_FT_IJK::deplacer_sommets(), Sauvegarde_Reprise_Maillage_FT::ecrire_xyz(), Parcours_interface::eloigner_sommets_des_faces(), Operator_FT_Disc::Facette_to_Sommets(), Triple_Line_Model_FT_Disc::get_any_tcl_face(), Transport_Interfaces_FT_Disc::mettre_a_jour(), nettoyer_noeuds_virtuels_et_frontieres(), Operator_FT_Disc::Operator_Gradient_FT_sommets(), Operator_FT_Disc::Operator_integral_bord_facette_phi_p_dl(), Remaillage_FT::redistribuer_sommets(), Remaillage_FT::regulariser_courbure(), Remaillage_FT::supprimer_petites_aretes(), Remaillage_FT_IJK::supprimer_petites_aretes(), Remailleur_Collision_FT_Thomas::transport_volume_perdu_sur_sommet(), IJK_Interfaces::transporter_maillage_deformation(), IJK_Interfaces::transporter_maillage_rigide(), transporter_simple(), and FT_Field::update_Field_sommets().
sommet_ligne_contact()
int Maillage_FT_Disc::sommet_ligne_contact (int i) const inline
References sommet_face_bord_.
Referenced by Parcours_interface::calcul_intersection_facelem_2D(), Parcours_interface::calcul_intersection_facelem_3D(), Triple_Line_Model_FT_Disc::compute_TCL_fluxes_in_all_boundary_cells(), echanger_sommets_PE(), Triple_Line_Model_FT_Disc::get_any_tcl_face(), Transport_Marqueur_FT::imposer_cond_lim(), Remaillage_FT::supprimer_facettes_bord(), and Remaillage_FT::traite_decollement().
sommet_face_bord() [2/2]
int Maillage_FT_Disc::sommet_face_bord (int i) const inline
References sommet_face_bord_.
facette_virtuelle()
int Maillage_FT_Disc::facette_virtuelle (int i) const inline
Renvoie 0 si la facette m'appartient, 1 sinon.
(le test est "le premier sommet de la facette m'appartient-t-il ?")
References facettes_, and sommet_elem_.
Referenced by FT_Field::avancer_en_temps(), calcul_courbure_sommets(), IJK_Interfaces::calculer_aspect_ratio(), Remaillage_FT::calculer_barycentre_facettes_voisines(), Remaillage_FT::calculer_differentielle_volume(), IJK_Interfaces::calculer_surfactant(), Remaillage_FT::calculer_variation_volume(), Transport_Interfaces_FT_Disc::calculer_vitesse_transport_interpolee(), Transport_Interfaces_FT_Disc::calculer_vmoy_composantes_connexes(), IJK_Interfaces::calculer_vmoy_rotation_composantes_connexes(), IJK_Interfaces::calculer_vmoy_translation_composantes_connexes(), FT_Field::champ_sommet_from_facettes(), FT_Field::check_conservation(), Post_Processing_Hydrodynamic_Forces::compute_friction_force_complet_tensor(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_friction_force_complet_tensor(), Post_Processing_Hydrodynamic_Forces::compute_friction_force_projected_tensor(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_friction_force_projected_tensor(), Post_Processing_Hydrodynamic_Forces::compute_heat_transfer(), Post_Processing_Hydrodynamic_Forces::compute_neighbors_coordinates_fluid_fa7(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_neighbors_coordinates_fluid_fa7(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_pressure_force_trilinear_linear(), Post_Processing_Hydrodynamic_Forces::compute_pressure_force_trilinear_linear(), IJK_Interfaces::compute_surface_average_per_bubble(), FT_Field::correction_conservation_globale(), ecrire_plot(), Sauvegarde_Reprise_Maillage_FT::ecrire_xyz(), FT_Field::exchange_compo_connexe(), FT_Field::exchange_data(), Operator_FT_Disc::Facette_to_Sommets(), Postraitement_ft_lata::filter_out_virtual_fa7(), Transport_Interfaces_FT_Disc::init_particles_position_velocity(), Remaillage_FT::lisser_dvolume(), Remaillage_FT::marquer_aretes(), Transport_Interfaces_FT_Disc::mettre_a_jour(), nb_facettes_reelle_totale(), nb_facettes_reelles(), FT_Field::nettoyer_espace_virtuel_facette(), nettoyer_maillage(), Maillage_FT_IJK::nettoyer_maillage(), Operator_FT_Disc::Operator_integral_bord_facette_phi_p_dl(), Operator_FT_Disc::Operator_Laplacian_FT_element(), FT_Field::passer_variable_extensive(), FT_Field::passer_variable_intensive(), Remaillage_FT::regulariser_courbure(), Operator_FT_Disc::Sommets_to_Facettes(), IJK_Interfaces::transporter_maillage_remaillage(), Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_elem(), Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_face(), Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_gradU_elem(), Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_gradU_elem_P1(), Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_gradU_face(), FT_Field::update_Field_sommets(), FT_Field::update_sigma_and_interfacial_source_term_sommet(), and Maillage_FT_IJK::update_surfactant_apres_transport().
facettes_voisines()
int Maillage_FT_Disc::facettes_voisines (int fa70, int fa71, int & iarete0, int & iarete1) const
Cette methode teste si les facettes sont voisines : Des facettes sont voisines si :
-elles ont 1 sommet commun en 2D -elles ont 2 sommets communs en 3D La methode renvoie -1 si les facettes ne sont pas voisines. Elle renvoie l'indice (local) de l'arete (dans fa70) par laquelle les facettes sont voisines A OPTIMISER eventuellement
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, facettes_, Process::Journal(), and printFa7().
Referenced by calculer_voisinage_facettes().
calculer_voisinage_facettes()
int Maillage_FT_Disc::calculer_voisinage_facettes (IntTab & fa7Voisines, const Intersections_Elem_Facettes * ief = nullptr) const
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Domaine_dis_base::domaine(), facettes_, facettes_voisines(), Intersections_Elem_Facettes::get_liste_facettes_traversantes(), intersections_elem_facettes_, Process::Journal(), Domaine_32_64< _SIZE_ >::nb_elem(), nb_facettes(), PARCOURU, refdomaine_dis_, TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), statut_, and TRUST_Ref< _CLASSE_ >::valeur().
associer_equation_transport()
void Maillage_FT_Disc::associer_equation_transport (const Equation_base & equation) override virtual
on remplit refequation_transport_, schema_comm_domaine_ desc_sommets_.comm_group_ et desc_facettes_.comm_group_
Precondition: le domaine_dis de l'equation doit etre complete (joints)
Implements Ensemble_Lagrange_base.
References associer_domaine_dis_parcours(), Equation_base::domaine_dis(), Transport_Interfaces_FT_Disc::parcours_interface(), and refequation_transport_.
Referenced by Transport_Marqueur_FT::completer(), Transport_Marqueur_FT::construction_ensemble_proprietes(), Transport_Interfaces_FT_Disc::discretiser(), Transport_Interfaces_FT_Disc::lire_cond_init(), Transport_Interfaces_FT_Disc::mettre_a_jour(), and Transport_Interfaces_FT_Disc::reprendre().
associer_domaine_dis_parcours()
void Maillage_FT_Disc::associer_domaine_dis_parcours (const Domaine_dis_base & domaine_dis, const Parcours_interface & parcours)
References TRUSTArray< _TYPE_, _SIZE_ >::append_array(), Domaine_dis_base::domaine(), Domaine_32_64< _SIZE_ >::faces_joint(), Joint_32_64< _SIZE_ >::PEvoisin(), refdomaine_dis_, refparcours_interface_, schema_comm_domaine_, and Schema_Comm::set_send_recv_pe_list().
Referenced by associer_equation_transport(), and Maillage_FT_IJK::initialize().
equation_transport() [1/2]
Transport_Interfaces_FT_Disc & Maillage_FT_Disc::equation_transport ()
References refequation_transport_, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by calcul_courbure_sommets(), calcul_indicatrice(), calculer_costheta_minmax(), equation_associee(), nettoyer_noeuds_virtuels_et_frontieres(), nettoyer_phase(), Remailleur_Collision_FT_Juric::traite_RuptureCoalescenceInterfaces(), and Remailleur_Collision_FT_Thomas::traite_RuptureCoalescenceInterfaces_Conservatif().
equation_transport() [2/2]
const Transport_Interfaces_FT_Disc & Maillage_FT_Disc::equation_transport () const
References refequation_transport_, and TRUST_Ref< _CLASSE_ >::valeur().
type_statut()
int Maillage_FT_Disc::type_statut () const
References COMPLET, Process::exit(), MINIMAL, PARCOURU, RESET, and statut_.
Referenced by Transport_Marqueur_FT::calculer_valeurs_densite(), and Transport_Marqueur_FT::calculer_valeurs_volumes().
reset()
void Maillage_FT_Disc::reset ()
vide toutes les structures du maillage, le statut passe a RESET.
References Maillage_FT_Disc_Data_Cache::clear(), desc_facettes_, desc_sommets_, Objet_U::dimension, drapeaux_sommets_, facettes_, intersections_elem_facettes_, maillage_modifie(), mesh_data_cache(), RESET, Desc_Structure_FT::reset(), Intersections_Elem_Facettes::reset(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), sommet_elem_, sommet_face_bord_, sommet_num_owner_, sommet_PE_owner_, sommets_, and voisins_.
Referenced by Maillage_FT_IJK::lire_maillage_ft_dans_lata(), recopie(), remplir_structure(), and reprendre().
parcourir_maillage()
void Maillage_FT_Disc::parcourir_maillage ()
Remplit la structure intersections_elem_facettes_.
Le statut passe a PARCOURU.
Precondition: statut >= MINIMAL
References Statistiques::begin_count(), Statistiques::end_count(), Process::exit(), maillage_modifie(), Statistiques::new_counter(), Parcours_interface::parcourir(), PARCOURU, refparcours_interface_, RESET, statut_, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by completer_maillage(), Transport_Interfaces_FT_Disc::get_update_indicatrice(), Transport_Interfaces_FT_Disc::lire_maillage_ft_cao(), Maillage_FT_IJK::parcourir_maillage(), Topologie_Maillage_FT::remailler_interface(), Remailleur_Collision_FT_Thomas::traite_RuptureCoalescenceInterfaces_Conservatif(), and Transport_Interfaces_FT_Disc::transporter_sans_changement_topologie().
completer_maillage()
void Maillage_FT_Disc::completer_maillage ()
Complete les structures de donnees du maillage.
Le statut passe a COMPLET.
Precondition: statut >= MINIMAL
References calculer_voisins(), COMPLET, get_update_courbure_sommets(), get_update_normale_facettes(), get_update_surface_facettes(), parcourir_maillage(), RESET, and statut_.
Referenced by Transport_Interfaces_FT_Disc::mettre_a_jour().
calcul_indicatrice()
void Maillage_FT_Disc::calcul_indicatrice (DoubleVect & indicatrice, const DoubleVect & indicatrice_precedente)
Calcul de la fonction indicatrice (on suppose que "indicatrice" a la structure d'un tableau de valeurs aux elements, on ne remplit.
que les elements reels). La fraction volumique de la phase 1 dans les elements traverses par une interface est determinee a partir des donnees du parcours dans "intersections_elem_facettes_". Les autres elements sont remplis par une methode heuristique utilisant l'indicatrice_precedente.
Precondition: statut >= PARCOURU Attention, l'algorithme est concu de sorte que l'on puisse utiliser le meme tableau "indicatrice" et "indicatrice_precedente".
References TRUSTTab< _TYPE_, _SIZE_ >::append_line(), Statistiques::begin_count(), ArrOfBit_32_64< _SIZE_ >::clearbit(), Intersections_Elem_Facettes_Data::contrib_volume_phase1_, Intersections_Elem_Facettes::data_intersection(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Domaine_dis_base::domaine(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_VF::elem_faces(), Statistiques::end_count(), equation_transport(), Domaine_VF::face_voisins(), Transport_Interfaces_FT_Disc::get_nb_particles_tot(), Transport_Interfaces_FT_Disc::get_update_distance_interface(), Intersections_Elem_Facettes::index_elem(), Intersections_Elem_Facettes_Data::index_facette_suivante_, intersections_elem_facettes_, is_solid_particle_, Process::Journal(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Process::me(), Domaine_32_64< _SIZE_ >::nb_elem(), Domaine_32_64< _SIZE_ >::nb_elem_tot(), Statistiques::new_counter(), PARCOURU, refdomaine_dis_, refequation_transport_, ArrOfBit_32_64< _SIZE_ >::resize_array(), ArrOfBit_32_64< _SIZE_ >::setbit(), TRUSTVect< _TYPE_, _SIZE_ >::size(), statut_, TRUST_Ref< _CLASSE_ >::valeur(), Champ_Proto::valeurs(), and Debog::verifier().
Referenced by Transport_Interfaces_FT_Disc::get_update_indicatrice().
transporter()
void Maillage_FT_Disc::transporter (const DoubleTab & deplacement) virtual
Deplace les sommets de l'interface d'un vecteur "deplacement" fourni, Change eventuellement les sommets de processeur, cree eventuellement.
des lignes de contact et detecte les collisions.
Parameters
(deplacement) un tableau de taille (nb_sommets(), Objet_U::dimension) contenant le vecteur deplacement de chaque sommet. Les deplacements des sommets virtuels sont ignores.
Reimplemented in Maillage_FT_IJK.
References Statistiques::begin_count(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, nb_sommets(), Statistiques::new_counter(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), and sommets_.
Referenced by Transport_Interfaces_FT_Disc::deplacer_maillage_ft_v_fluide(), Transport_Interfaces_FT_Disc::mettre_a_jour(), Remaillage_FT::redistribuer_sommets(), Maillage_FT_IJK::transporter(), and Transport_Interfaces_FT_Disc::transporter_sans_changement_topologie().
transporter_simple()
void Maillage_FT_Disc::transporter_simple (const DoubleTab & deplacement)
References deplacer_sommets(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, maillage_modifie(), MINIMAL, nb_sommets(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), sommet_virtuel(), and sommets_.
Referenced by Transport_Marqueur_FT::integrer_ensemble_lagrange().
nettoyer_noeuds_virtuels_et_frontieres()
void Maillage_FT_Disc::nettoyer_noeuds_virtuels_et_frontieres ()
References TRUSTArray< _TYPE_, _SIZE_ >::append_array(), Schema_Comm::begin_comm(), Descripteur_FT::calcul_liste_pe_voisins(), Desc_Structure_FT::calcul_schema_comm(), Comm_Group::check_enabled(), check_mesh(), Domaine_Cl_dis_base::condition_limite_de_la_face_reelle(), desc_sommets_, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Equation_base::domaine_Cl_dis(), drapeaux_sommets_, Desc_Structure_FT::echange_espace_virtuel(), Schema_Comm::echange_taille_et_messages(), Descripteur_FT::elements(), Schema_Comm::end_comm(), Entree::eof(), Probleme_base::equation(), equation_transport(), Desc_Structure_FT::espace_distant(), Desc_Structure_FT::espace_virtuel(), Transport_Interfaces_FT_Disc::get_probleme_base(), Schema_Comm::get_recv_pe_list(), maillage_modifie(), MINIMAL, nb_sommets(), Transport_Interfaces_FT_Disc::nettoyer_proprietes_particules(), Descripteur_FT::pe_voisins(), Schema_Comm::recv_buffer(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), Desc_Structure_FT::schema_comm_inverse(), Schema_Comm::send_buffer(), Descripteur_FT::set_elements(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), sommet_elem_, sommet_face_bord_, sommet_num_owner_, sommet_PE_owner_, sommet_virtuel(), sommets_, and statut_.
Referenced by Transport_Marqueur_FT::mettre_a_jour().
nettoyer_phase()
void Maillage_FT_Disc::nettoyer_phase (const Nom & nom_eq, const int phase)
References TRUSTArray< _TYPE_, _SIZE_ >::append_array(), Schema_Comm::begin_comm(), Descripteur_FT::calcul_liste_pe_voisins(), Desc_Structure_FT::calcul_schema_comm(), Comm_Group::check_enabled(), check_mesh(), desc_sommets_, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, drapeaux_sommets_, Desc_Structure_FT::echange_espace_virtuel(), Schema_Comm::echange_taille_et_messages(), Descripteur_FT::elements(), Schema_Comm::end_comm(), Entree::eof(), equation_transport(), Desc_Structure_FT::espace_distant(), Desc_Structure_FT::espace_virtuel(), Probleme_base::get_equation_by_name(), Schema_Comm::get_recv_pe_list(), Transport_Interfaces_FT_Disc::inconnue(), maillage_modifie(), MINIMAL, nb_sommets(), Transport_Interfaces_FT_Disc::nettoyer_proprietes_particules(), Descripteur_FT::pe_voisins(), Equation_base::probleme(), Schema_Comm::recv_buffer(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), Desc_Structure_FT::schema_comm_inverse(), Schema_Comm::send_buffer(), Descripteur_FT::set_elements(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), sommet_elem_, sommet_face_bord_, sommet_num_owner_, sommet_PE_owner_, sommets_, statut_, and Champ_Inc_base::valeurs().
Referenced by Transport_Marqueur_FT::transformer_particules().
nettoyer_elements_virtuels()
void Maillage_FT_Disc::nettoyer_elements_virtuels ()
Retire toutes les facettes virtuelles et tous les sommets qui ne sont pas utilises.
References nettoyer_maillage().
Referenced by Remaillage_FT::diviser_grandes_aretes(), Remaillage_FT_IJK::diviser_grandes_aretes(), Transport_Interfaces_FT_Disc::mettre_a_jour(), Remaillage_FT::remaillage_local_interface(), and Remaillage_FT_IJK::remaillage_local_interface().
nettoyer_maillage()
void Maillage_FT_Disc::nettoyer_maillage () virtual
Retire toutes les facettes virtuelles, toutes les facettes invalides (sommet0 == sommet1) et tous les sommets qui ne sont pas utilises.
Reimplemented in Maillage_FT_IJK.
References TRUSTArray< _TYPE_, _SIZE_ >::append_array(), Schema_Comm::begin_comm(), Descripteur_FT::calcul_liste_pe_voisins(), Desc_Structure_FT::calcul_schema_comm(), Comm_Group::check_enabled(), check_mesh(), desc_facettes_, desc_sommets_, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, drapeaux_sommets_, Desc_Structure_FT::echange_espace_virtuel(), Schema_Comm::echange_taille_et_messages(), Descripteur_FT::elements(), Schema_Comm::end_comm(), Entree::eof(), Desc_Structure_FT::espace_distant(), Desc_Structure_FT::espace_virtuel(), facette_num_owner_, facette_virtuelle(), facettes_, Schema_Comm::get_recv_pe_list(), maillage_modifie(), MINIMAL, nb_sommets(), Descripteur_FT::pe_voisins(), Schema_Comm::recv_buffer(), Desc_Structure_FT::reset(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), Desc_Structure_FT::schema_comm_inverse(), Schema_Comm::send_buffer(), Descripteur_FT::set_elements(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), sommet_elem_, sommet_face_bord_, sommet_num_owner_, sommet_PE_owner_, sommets_, and statut_.
Referenced by nettoyer_elements_virtuels(), Transport_Interfaces_FT_Disc::nettoyer_maillage(), Maillage_FT_IJK::nettoyer_maillage(), Remaillage_FT::nettoyer_maillage(), and supprimer_facettes().
supprimer_facettes()
void Maillage_FT_Disc::supprimer_facettes (const ArrOfInt & liste_facettes)
Supprime les facettes dont les indices locaux sont donnes en parametre.
Le maillage est nettoye et retourne a l'etat MINIMAL.
References facettes_, nettoyer_maillage(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by Maillage_FT_IJK::supprimer_facettes().
ecrire_plot()
void Maillage_FT_Disc::ecrire_plot (const Nom & nom, double temps, int niveau_requete) const
References Sortie_Fichier_base::close(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Process::exit(), facette_virtuelle(), facettes_, Process::Journal(), Process::me(), niveau_plot_, Objet_U::nom_du_cas(), Process::nproc(), Sortie_Fichier_base::precision(), printFa7(), Sortie_Fichier_base::setf(), and sommets_.
printFa7()
Sortie & Maillage_FT_Disc::printFa7 (int fa7, int affsom, Sortie & os) const
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, facettes_, get_update_normale_facettes(), get_update_surface_facettes(), printSom(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), sommet_num_owner_, and sommet_PE_owner_.
Referenced by calcul_surface_normale(), check_mesh(), ecrire_plot(), facettes_voisines(), Remaillage_FT::supprimer_doublons_facettes(), and Remaillage_FT::supprimer_facettes_bord().
printSom()
Sortie & Maillage_FT_Disc::printSom (int som, Sortie & os) const
References Objet_U::dimension, sommet_elem_, sommet_face_bord_, sommet_num_owner_, sommet_PE_owner_, and sommets_.
Referenced by printFa7(), and Remaillage_FT::traite_decollement().
get_update_surface_facettes()
const ArrOfDouble & Maillage_FT_Disc::get_update_surface_facettes () const virtual
Calcule la grandeur demandee, stocke le resultat dans un tableau interne a la classe et renvoie le resultat.
Si le maillage n'a pas change depuis le dernier calcul (mesh_tag identique) alors on ne recalcule pas la valeur. Attention, cette methode doit etre appelee simultanement sur tous les processeurs.
References calcul_surface_normale(), get_mesh_tag(), mesh_data_cache(), Maillage_FT_Disc_Data_Cache::normale_facettes_, Maillage_FT_Disc_Data_Cache::surface_facettes_, Maillage_FT_Disc_Data_Cache::tag_normale_, and Maillage_FT_Disc_Data_Cache::tag_surface_.
Referenced by calcul_courbure_sommets(), Transport_Interfaces_FT_Disc::calcul_OutElemFa7(), IJK_Interfaces::calculer_aire_interfaciale(), IJK_Interfaces::calculer_aire_interfaciale_for_compo(), Remaillage_FT::calculer_barycentre_facettes_voisines(), Remaillage_FT::calculer_differentielle_volume(), Transport_Interfaces_FT_Disc::calculer_distance_interface(), IJK_Interfaces::calculer_kappa_ft(), ComputeValParCompoInCell::calculer_moy_field_fa7_par_compo(), ComputeValParCompoInCell::calculer_moy_field_sommet_par_compo(), ComputeValParCompoInCell::calculer_moyennes_interface_element_pour_compo(), IJK_Interfaces::calculer_normales_et_aires_interfaciales(), ComputeValParCompoInCell::calculer_somme_field_sommet_par_compo(), IJK_Interfaces::calculer_surface_interface(), IJK_Interfaces::calculer_surfactant(), Remaillage_FT::calculer_variation_volume_facette_2D(), IJK_Interfaces::calculer_vecteurs_de_deplacement_rigide(), Transport_Interfaces_FT_Disc::calculer_vitesse_transport_interpolee(), Transport_Interfaces_FT_Disc::calculer_vmoy_composantes_connexes(), FT_Field::check_conservation(), completer_maillage(), Triple_Line_Model_FT_Disc::compute_approximate_interface_inout(), IJK_Interfaces::compute_external_forces_(), Post_Processing_Hydrodynamic_Forces::compute_heat_transfer(), Post_Processing_Hydrodynamic_Forces::compute_hydrodynamic_forces(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_hydrodynamic_forces(), IJK_Thermal_base::compute_interfacial_temperature2(), compute_normale_element(), compute_surface_and_normale_element(), Transport_Interfaces_FT_Disc::deplacer_maillage_ft_v_fluide(), IJK_Interfaces::detecter_et_supprimer_rejeton(), Operator_FT_Disc::Facette_to_Sommets(), Triple_Line_Model_FT_Disc::get_in_out_coords(), Transport_Interfaces_FT_Disc::init_particles_position_velocity(), FT_Field::initialize(), Remaillage_FT::lisser_dvolume(), Transport_Interfaces_FT_Disc::mettre_a_jour(), Remailleur_Collision_FT_Thomas::mettre_a_jour_data(), FT_Field::passer_variable_extensive(), FT_Field::passer_variable_intensive(), IJK_Thermal_base::posttraiter_champs_instantanes_thermal_interface_ref(), printFa7(), recopie(), Remaillage_FT::regulariser_courbure(), IJK_One_Dimensional_Subproblems_Interfaces_Fields::retrieve_interfacial_surface_quantity(), Operator_FT_Disc::Sommets_to_Facettes(), Remaillage_FT::supprimer_facettes_nulles(), Transport_Interfaces_FT_Disc::transfert_conservatif_eulerien_vers_lagrangien_sommets(), Remailleur_Collision_FT_Thomas::transport_volume_perdu_sur_sommet(), IJK_Interfaces::transporter_maillage_remaillage(), and IJK_Interfaces::update_surface_normale().
get_update_normale_facettes()
const DoubleTab & Maillage_FT_Disc::get_update_normale_facettes () const virtual
Calcule la grandeur demandee, stocke le resultat dans un tableau interne a la classe et renvoie le resultat.
Si le maillage n'a pas change depuis le dernier calcul (mesh_tag identique) alors on ne recalcule pas la valeur. Attention, cette methode doit etre appelee simultanement sur tous les processeurs.
References calcul_surface_normale(), get_mesh_tag(), mesh_data_cache(), Maillage_FT_Disc_Data_Cache::normale_facettes_, Maillage_FT_Disc_Data_Cache::surface_facettes_, Maillage_FT_Disc_Data_Cache::tag_normale_, and Maillage_FT_Disc_Data_Cache::tag_surface_.
Referenced by calcul_courbure_sommets(), Transport_Interfaces_FT_Disc::calcul_eq_plan_facette(), Transport_Interfaces_FT_Disc::calcul_nb_traverse(), calcule_equation_plan_areteFa7(), Remaillage_FT::calculer_differentielle_volume(), Transport_Interfaces_FT_Disc::calculer_distance_interface(), ComputeValParCompoInCell::calculer_moyennes_interface_element_pour_compo(), IJK_Interfaces::calculer_normales_et_aires_interfaciales(), Remaillage_FT::calculer_variation_volume_facette_2D(), Transport_Interfaces_FT_Disc::calculer_vmoy_composantes_connexes(), completer_maillage(), Triple_Line_Model_FT_Disc::compute_approximate_interface_inout(), Post_Processing_Hydrodynamic_Forces::compute_heat_transfer(), Post_Processing_Hydrodynamic_Forces::compute_hydrodynamic_forces(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_hydrodynamic_forces(), IJK_Thermal_base::compute_interfacial_temperature2(), compute_normale_element(), compute_surface_and_normale_element(), Facettes_Interp_FT::cut_cell_perform_interpolation_facettes(), FT_Field::exchange_data(), Transport_Interfaces_FT_Disc::fill_ftab_normal_unit(), Triple_Line_Model_FT_Disc::get_in_out_coords(), Operator_FT_Disc::Operator_integral_bord_facette_phi_p_dl(), Operator_FT_Disc::Operator_Laplacian_FT_element(), printFa7(), recopie(), Remaillage_FT::supprimer_facettes_bord(), Topologie_Maillage_FT::test_intersection_facettes_3D(), and IJK_Interfaces::update_surface_normale().
compute_normale_element()
double Maillage_FT_Disc::compute_normale_element (const int elem, const bool normalize, ArrOfDouble & normale) const virtual
References Intersections_Elem_Facettes::data_intersection(), Objet_U::dimension, Intersections_Elem_Facettes_Data::fraction_surface_intersection_, get_update_normale_facettes(), get_update_surface_facettes(), Intersections_Elem_Facettes::index_elem(), Intersections_Elem_Facettes_Data::index_facette_suivante_, intersections_elem_facettes(), Intersections_Elem_Facettes_Data::numero_facette_, and Objet_U::precision_geom.
compute_surface_and_normale_element()
double Maillage_FT_Disc::compute_surface_and_normale_element (const int elem, const bool normalize, double surface, double normal[3]) const virtual
References Intersections_Elem_Facettes::data_intersection(), Objet_U::dimension, Intersections_Elem_Facettes_Data::fraction_surface_intersection_, get_update_normale_facettes(), get_update_surface_facettes(), Intersections_Elem_Facettes::index_elem(), Intersections_Elem_Facettes_Data::index_facette_suivante_, intersections_elem_facettes(), Intersections_Elem_Facettes_Data::numero_facette_, and Objet_U::precision_geom.
get_update_courbure_sommets()
const ArrOfDouble & Maillage_FT_Disc::get_update_courbure_sommets () const virtual
Calcule la grandeur demandee, stocke le resultat dans un tableau interne a la classe et renvoie le resultat.
Si le maillage n'a pas change depuis le dernier calcul (mesh_tag identique) alors on ne recalcule pas la valeur. Attention, cette methode doit etre appelee simultanement sur tous les processeurs.
References calcul_courbure_iterations_, calcul_courbure_sommets(), Maillage_FT_Disc_Data_Cache::courbure_sommets_, get_mesh_tag(), mesh_data_cache(), and Maillage_FT_Disc_Data_Cache::tag_courbure_.
Referenced by IJK_Interfaces::calculer_kappa_ft(), IJK_Interfaces::calculer_normales_et_aires_interfaciales(), IJK_Interfaces::calculer_phi_repuls_sommet(), ComputeValParCompoInCell::calculer_valeur_par_compo(), completer_maillage(), Transport_Interfaces_FT_Disc::fill_ftab_vertices_curvature(), IJK_Interfaces::get_IJK_field(), recopie(), and Remaillage_FT::regulariser_courbure().
get_surface_facettes()
const ArrOfDouble & Maillage_FT_Disc::get_surface_facettes () const virtual
References mesh_data_cache(), and Maillage_FT_Disc_Data_Cache::surface_facettes_.
Referenced by FT_Field::correction_conservation_globale(), Maillage_FT_IJK::deplacer_sommets(), Remaillage_FT_IJK::supprimer_petites_aretes(), and FT_Field::update_Field_sommets().
get_normale_facettes()
const DoubleTab & Maillage_FT_Disc::get_normale_facettes () const virtual
References mesh_data_cache(), and Maillage_FT_Disc_Data_Cache::normale_facettes_.
coords_fa7()
Vecteur3 Maillage_FT_Disc::coords_fa7 (int fa7) const
References coords_fa7(), facettes_, and sommets_.
Referenced by Facettes_Interp_FT::calcul_coefficient_interpolation_facette_cut_cell(), Facettes_Interp_FT::calcul_coefficient_interpolation_facette_cut_cell_second_order(), and coords_fa7().
get_liste_facette_supprimees_et_voisines()
const IntTabFT & Maillage_FT_Disc::get_liste_facette_supprimees_et_voisines () const inline
References liste_facette_supprimees_et_voisines_.
set_liste_facette_supprimees_et_voisines()
void Maillage_FT_Disc::set_liste_facette_supprimees_et_voisines (IntTabFT tab) inline
References liste_facette_supprimees_et_voisines_.
get_nb_facette_supprimees()
const int & Maillage_FT_Disc::get_nb_facette_supprimees () const inline
References nb_facette_supprimees_.
set_nb_facette_supprimees()
void Maillage_FT_Disc::set_nb_facette_supprimees (int nb) inline
References nb_facette_supprimees_.
set_niveau_plot()
int Maillage_FT_Disc::set_niveau_plot (int niv) inline
References niveau_plot_.
deplacer_un_point()
int Maillage_FT_Disc::deplacer_un_point (double & x, double & y, double & z, double x1, double y1, double z1, int & element_suivant, int & face_suivante, const Parcours_interface & parcours, const Domaine_VF & domaine_vf, const IntTab & face_voisins, int skip_facettes = 0) static
References Parcours_interface::calculer_face_sortie_element(), and Parcours_interface::calculer_sortie_face_bord().
Referenced by deplacer_un_sommet().
deplacer_un_sommet()
int Maillage_FT_Disc::deplacer_un_sommet (double & x, double & y, double & z, double x1, double y1, double z1, int & element, int & face_bord, const int num_sommet, const Parcours_interface & parcours, const Domaine_VF & domaine_vf, const IntTab & face_voisins, ArrOfInt & sommets_envoyes, ArrOfInt & element_virtuel_arrivee, ArrOfInt & face_virtuelle_arrivee, DoubleTab & deplacement_restant, int skip_facettes = 0) static
References TRUSTArray< _TYPE_, _SIZE_ >::append_array(), deplacer_un_point(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Domaine_dis_base::nb_elem(), and TRUSTTab< _TYPE_, _SIZE_ >::resize().
Referenced by deplacer_sommets().
preparer_tableau_avant_transport() [1/3]
void Maillage_FT_Disc::preparer_tableau_avant_transport (ArrOfDouble & tableau, const Desc_Structure_FT & descripteur) const
Prepare un tableau de donnees aux sommets ou aux facettes pour conserver les valeurs apres transport.
Le transport modifie le descripteur et augmente le nombre de sommets ou de facettes. En general les tableaux qui contiennent des valeurs aux sommets ou aux facettes ne sont donc plus valables apres le transport. On peut les rendre valables comme suit (exemple avec le tableau courbure aux sommets) : preparer_tableau_avant_transport(courbure, desc_sommets()); transporter(deplacement); update_tableau_apres_transport(courbure, desc_sommets()); Attention, le tableau ne devient valable qu'apres avoir appele update_tableau_apres_transport.
References Descripteur_FT::elements(), Desc_Structure_FT::espace_virtuel(), Descripteur_FT::pe_voisins(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by Transport_Interfaces_FT_Disc::deplacer_maillage_ft_v_fluide(), Transport_Marqueur_FT::preparer_tableaux_avant_transport(), Remaillage_FT::redistribuer_sommets(), IJK_Interfaces::transporter_maillage_deformation(), and Transport_Interfaces_FT_Disc::transporter_sans_changement_topologie().
preparer_tableau_avant_transport() [2/3]
void Maillage_FT_Disc::preparer_tableau_avant_transport (ArrOfInt & tableau, const Desc_Structure_FT & descripteur) const
References Descripteur_FT::elements(), Desc_Structure_FT::espace_virtuel(), Descripteur_FT::pe_voisins(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
preparer_tableau_avant_transport() [3/3]
void Maillage_FT_Disc::preparer_tableau_avant_transport (DoubleTab & tableau, const Desc_Structure_FT & descripteur) const
Voir preparer_tableau_avant_transport.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Descripteur_FT::elements(), Desc_Structure_FT::espace_virtuel(), Descripteur_FT::pe_voisins(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
update_tableau_apres_transport() [1/3]
void Maillage_FT_Disc::update_tableau_apres_transport (ArrOfDouble & tableau, int nb_elements, const Desc_Structure_FT & descripteur) const
Voir preparer_tableau_avant_transport.
References Desc_Structure_FT::collecter_espace_virtuel(), Desc_Structure_FT::echange_espace_virtuel(), MD_Vector_tools::EV_SOMME, TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by Transport_Interfaces_FT_Disc::deplacer_maillage_ft_v_fluide(), Remaillage_FT::redistribuer_sommets(), IJK_Interfaces::transporter_maillage_deformation(), Transport_Interfaces_FT_Disc::transporter_sans_changement_topologie(), and Transport_Marqueur_FT::update_tableaux_apres_transport().
update_tableau_apres_transport() [2/3]
void Maillage_FT_Disc::update_tableau_apres_transport (ArrOfInt & tableau, int nb_elements, const Desc_Structure_FT & descripteur) const
References Desc_Structure_FT::collecter_espace_virtuel(), Desc_Structure_FT::echange_espace_virtuel(), MD_Vector_tools::EV_SOMME, TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
update_tableau_apres_transport() [3/3]
void Maillage_FT_Disc::update_tableau_apres_transport (DoubleTab & tableau, int nb_elements, const Desc_Structure_FT & descripteur) const
Voir preparer_tableau_avant_transport.
References Desc_Structure_FT::collecter_espace_virtuel(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Desc_Structure_FT::echange_espace_virtuel(), MD_Vector_tools::EV_SOMME, and TRUSTTab< _TYPE_, _SIZE_ >::resize().
angle_bidim_axi()
double Maillage_FT_Disc::angle_bidim_axi () static
renvoie l'angle solide qui sert a calculer les surfaces et les volumes en bidim_axi
Referenced by calcul_surface_normale(), Remaillage_FT::calculer_differentielle_volume(), Remaillage_FT::calculer_variation_volume_facette_2D(), Triple_Line_Model_FT_Disc::compute_Qint(), Triple_Line_Model_FT_Disc::compute_TCL_fluxes_in_all_boundary_cells(), Remaillage_FT::regulariser_courbure(), Parcours_interface::volume_barycentre_rectangle(), and Parcours_interface::volume_rectangle().
generer_structure()
void Maillage_FT_Disc::generer_structure ()
References Ensemble_Lagrange_base::remplir_sommets_tmp(), and remplir_structure().
Referenced by Transport_Marqueur_FT::completer(), and Transport_Marqueur_FT::construction_ensemble_proprietes().
remplir_structure()
void Maillage_FT_Disc::remplir_structure (const DoubleTab & soms)
References Descripteur_FT::calcul_liste_pe_voisins(), Desc_Structure_FT::calcul_schema_comm(), calculer_coord_noeuds(), construire_noeuds(), desc_sommets_, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), drapeaux_sommets_, Desc_Structure_FT::echange_espace_virtuel(), Desc_Structure_FT::espace_distant(), Desc_Structure_FT::espace_virtuel(), Process::Journal(), maillage_modifie(), MINIMAL, Desc_Structure_FT::remplir_element_pe(), reset(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), som_init_util_, sommet_elem_, sommet_face_bord_, sommet_num_owner_, sommet_PE_owner_, sommets_, and statut_.
Referenced by generer_structure().
creer_tableau_sommets()
void Maillage_FT_Disc::creer_tableau_sommets (Array_base & x, RESIZE_OPTIONS opt = RESIZE_OPTIONS::COPY_INIT) const
creation d'un tableau aux sommets du maillage Meme principe que Domaine::creer_tableau_sommets()
References MD_Vector_tools::creer_tableau_distribue(), desc_sommets(), and Desc_Structure_FT::get_md_vector().
Referenced by Transport_Interfaces_FT_Disc::calculer_vitesse_repere_local(), and Transport_Interfaces_FT_Disc::calculer_vitesse_transport_interpolee().
creer_tableau_elements()
void Maillage_FT_Disc::creer_tableau_elements (Array_base & x, RESIZE_OPTIONS opt = RESIZE_OPTIONS::COPY_INIT) const
creation d'un tableau aux sommets du maillage Meme principe que Domaine::creer_tableau_elements()
References MD_Vector_tools::creer_tableau_distribue(), desc_facettes(), and Desc_Structure_FT::get_md_vector().
calcul_normale_3D()
double Maillage_FT_Disc::calcul_normale_3D (int num_facette, double norme[3]) const
References facettes_, Process::Journal(), and sommets_.
Referenced by Parcours_interface::calcul_intersection_facelem_3D(), and calcul_surface_normale().
calculer_costheta_minmax()
void Maillage_FT_Disc::calculer_costheta_minmax (DoubleTab & costheta) const virtual
Pour chaque sommet du maillage, s'il est sur un bord, on calcule costheta min et max (hysteresis) correspondant a la condition aux limites ou.
se trouve le sommet. L'angle est constant par face de bord... possibilite de faire mieux pour un champ xyz
Reimplemented in Maillage_FT_IJK.
References Cond_lim_base::champ_front(), Paroi_FT_disc::CONSTANT, desc_sommets_, Equation_base::domaine_Cl_dis(), Equation_base::domaine_dis(), Desc_Structure_FT::echange_espace_virtuel(), equation_transport(), Process::exit(), Frontiere_dis_base::frontiere(), Cond_lim_base::frontiere_dis(), Paroi_FT_disc::get_type_modele(), Paroi_FT_disc::HYSTERESIS, Domaine_Cl_dis_base::la_cl_de_la_face(), Domaine_VF::nb_faces_bord(), nb_sommets(), Frontiere_32_64< _SIZE_ >::num_premiere_face(), Objet_U::que_suis_je(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), sommet_face_bord_, Paroi_FT_disc::SYMETRIE, TRUST_Deriv< _CLASSE_ >::valeur(), and Champ_front_base::valeurs_face().
Referenced by calcul_courbure_sommets().
set_is_solid_particle()
void Maillage_FT_Disc::set_is_solid_particle (const bool is_solid_particle) inline
References is_solid_particle_.
Referenced by Transport_Interfaces_FT_Disc::lire_motcle_non_standard().
get_is_solid_particle()
const bool & Maillage_FT_Disc::get_is_solid_particle () const inline
References is_solid_particle_.
Referenced by deplacer_sommets().
get_schema_comm_FT()
const Schema_Comm & Maillage_FT_Disc::get_schema_comm_FT () const inline
References schema_comm_domaine_.
Referenced by Transport_Interfaces_FT_Disc::preparer_calcul(), and Collision_Model_FT_base::research_collision_pairs_Verlet().
get_gravity_center_fa7()
const DoubleTab & Maillage_FT_Disc::get_gravity_center_fa7 () const inline
References gravity_center_fa7_.
Referenced by Post_Processing_Hydrodynamic_Forces_Stokes::compute_friction_force_complet_tensor(), Post_Processing_Hydrodynamic_Forces::compute_friction_force_projected_tensor(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_friction_force_projected_tensor(), Post_Processing_Hydrodynamic_Forces::compute_heat_transfer(), Post_Processing_Hydrodynamic_Forces::compute_hydrodynamic_forces(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_hydrodynamic_forces(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_pressure_force_trilinear_linear(), Post_Processing_Hydrodynamic_Forces_Stokes::fill_sigma_Stokes_th(), and Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_elem().
compute_gravity_center_fa7()
void Maillage_FT_Disc::compute_gravity_center_fa7 ()
References Objet_U::dimension, facettes_, gravity_center_fa7_, nb_facettes(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), and sommets_.
Referenced by Transport_Interfaces_FT_Disc::deplacer_maillage_ft_v_fluide(), and Transport_Interfaces_FT_Disc::preparer_calcul().
pre_lissage_courbure()
void Maillage_FT_Disc::pre_lissage_courbure (ArrOfDouble & store_courbure_sommets, const int niter) const protected
Referenced by calcul_courbure_sommets().
correction_costheta()
void Maillage_FT_Disc::correction_costheta (const double c, const int s0, const int facette, double ps) const protected
Referenced by calcul_courbure_sommets().
calculer_costheta_objectif()
double Maillage_FT_Disc::calculer_costheta_objectif (const int som, const int facette, const int call, const double c, const DoubleTabFT & tab_cos_theta, ArrOfBit & drapeau_angle_in_range) const protected
Referenced by calcul_courbure_sommets().
operator=()
const Maillage_FT_Disc & Maillage_FT_Disc::operator= (const Maillage_FT_Disc &) protected
L'operateur = est interdit !
References Process::exit().
maillage_modifie()
void Maillage_FT_Disc::maillage_modifie (Statut_Maillage nouveau_statut) protected
Cette methode change le statut du maillage et invalide le cache de valeurs calculees (surface, courbure, .
..) Il faut l'appeler chaque fois que le maillage est modifie et avant le prochain appel a get_update_xxx. Cette methode est appelee par les methode publiques non constantes de Maillage_FT_Disc et par les methodes de Remaillage, ...
References intersections_elem_facettes_, mesh_state_tag_, PARCOURU, Intersections_Elem_Facettes::reset(), and statut_.
Referenced by ajouter_maillage(), copier_sommet(), Remaillage_FT::diviser_grandes_aretes(), Remaillage_FT_IJK::diviser_grandes_aretes(), Remaillage_FT::marquer_aretes(), nettoyer_maillage(), nettoyer_noeuds_virtuels_et_frontieres(), nettoyer_phase(), parcourir_maillage(), Remaillage_FT::permuter_aretes(), recopie(), remplir_structure(), reprendre(), reset(), Remaillage_FT::supprimer_doublons_facettes(), Remaillage_FT::supprimer_facettes_nulles(), Remaillage_FT::supprimer_petites_aretes(), Remaillage_FT_IJK::supprimer_petites_aretes(), Remaillage_FT::traite_adherence(), Remaillage_FT::traite_decollement(), and transporter_simple().
calculer_voisins()
void Maillage_FT_Disc::calculer_voisins () protected
References MINIMAL, and statut_.
Referenced by completer_maillage().
calcul_surface_normale()
void Maillage_FT_Disc::calcul_surface_normale (ArrOfDouble & surface, DoubleTab & normale) const protected
Calcul de la surface et de la normale aux facettes du maillage.
Stocke le resultat dans les tableaux en parametres.
References angle_bidim_axi(), Objet_U::bidim_axi, calcul_normale_3D(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, facettes_, Process::Journal(), MINIMAL, printFa7(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), sommets_, and statut_.
Referenced by get_update_normale_facettes(), and get_update_surface_facettes().
calcul_courbure_sommets()
void Maillage_FT_Disc::calcul_courbure_sommets (ArrOfDouble & courbure_sommets, const int call) const protected
Calcul de la courbure discrete du maillage aux sommets.
Methode de calcul : voir these B. Mathieu paragraphe 3.3.3 page 97 La courbure est egale a la differentielle de la surface d'interface par rapport au deplacement des sommets, divisee par la differentielle du volume.
Parameters
(courbure_sommets) Tableau dans lequel on veut stocker la courbure aux sommets. La valeur initiale du tableau est perdue. L'espace virtuel du tableau resultat est a jour.
References Objet_U::bidim_axi, calculer_costheta_minmax(), calculer_costheta_objectif(), Parcours_interface::calculer_normale_face_bord(), Desc_Structure_FT::collecter_espace_virtuel(), Domaine_Cl_dis_base::condition_limite_de_la_face_reelle(), correction_contact_courbure_coeff_, correction_costheta(), desc_sommets(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Equation_base::domaine_Cl_dis(), Desc_Structure_FT::echange_espace_virtuel(), Probleme_base::equation(), equation_transport(), MD_Vector_tools::EV_SOMME, Process::exit(), facette_virtuelle(), facettes_, Cond_lim_base::frontiere_dis(), Transport_Interfaces_FT_Disc::get_champ_post_FT(), Triple_Line_Model_FT_Disc::get_lv(), Transport_Interfaces_FT_Disc::get_probleme_base(), Triple_Line_Model_FT_Disc::get_theta_app(), get_update_normale_facettes(), get_update_surface_facettes(), HYSTERESIS, IMPROVED, Triple_Line_Model_FT_Disc::is_activated(), Triple_Line_Model_FT_Disc::is_capillary_activated(), Triple_Line_Model_FT_Disc::is_read_via_file(), Process::Journal(), Frontiere_dis_base::le_nom(), Process::me(), methode_calcul_courbure_contact_line_, MIRROR, Process::mp_max(), Process::mp_sum(), nb_facettes(), nb_sommets(), niter_pre_lissage_, TRUST_Ref< _CLASSE_ >::non_nul(), pre_lissage_courbure(), Parcours_interface::projeter_vecteur_sur_face(), refequation_transport_, refparcours_interface_, TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), ArrOfBit_32_64< _SIZE_ >::resize_array(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), sommet_elem_, sommet_face_bord_, sommet_virtuel(), Postraitement_base::SOMMETS, sommets_, STANDARD, Probleme_FT_Disc_gen::tcl(), temps_physique_, ArrOfBit_32_64< _SIZE_ >::testsetbit(), TRUST_Ref< _CLASSE_ >::valeur(), weight_CL_, and WEIGHTED.
Referenced by get_update_courbure_sommets().
copier_sommet()
int Maillage_FT_Disc::copier_sommet (int som) protected
fonction qui cree un nouveau sommet par copie d'une existant utilise dans Remailleur_Collision_FT_Collision_Seq
References Objet_U::dimension, drapeaux_sommets_, maillage_modifie(), Process::me(), MINIMAL, nb_sommets(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), sommet_elem_, sommet_face_bord_, sommet_num_owner_, sommet_PE_owner_, and sommets_.
Referenced by copier_sommet_interne().
copier_sommet_interne()
int Maillage_FT_Disc::copier_sommet_interne (int som) protected
References copier_sommet(), and sommet_face_bord_.
calcule_equation_plan_areteFa7()
int Maillage_FT_Disc::calcule_equation_plan_areteFa7 (int fa7, int iarete, double & a, double & b, double & c, double & d) const protected
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), facettes_, get_update_normale_facettes(), and sommets_.
creer_sommets_virtuels()
void Maillage_FT_Disc::creer_sommets_virtuels (const ArrOfInt & liste_sommets, const ArrOfInt & liste_pe, const Schema_Comm & comm) protected
Envoi des sommets dont le numero est donne dans liste_sommets au processeur dont le numero est donne dans liste_pe (on cree un.
sommet virtuel sur ce processeur). Parmi les sommets de la liste_sommets, seuls ceux qui ne sont pas encore dans l'espace virtuel sont crees.
Precondition: Les membres suivants doivent etre valides:
sommets_,
desc_sommets_,
drapeaux_sommets_,
sommet_elem_,
sommet_PE_owner_,
sommet_num_owner_
Postcondition: Les memes tableaux sont valides a la sortie de la fonction.
Parameters
(liste_sommets) une liste de numeros de sommets REELS qui peut contenir des doublons.
(liste_pe) une liste de meme taille que liste_sommets contenant le numero du processeur sur lequel il faut creer un noeud virtuel. Le processeur ne doit pas etre moi.
(comm) un schema de comm valide, dans lequel send_pe_list contient au moins les processeurs cites dans liste_pe.
References Descripteur_FT::ajoute_element(), TRUSTArray< _TYPE_, _SIZE_ >::append_array(), TRUSTTab< _TYPE_, _SIZE_ >::append_line(), Schema_Comm::begin_comm(), Descripteur_FT::calcul_liste_pe_voisins(), Desc_Structure_FT::calcul_schema_comm(), Comm_Group::check_enabled(), check_sommets(), Descripteur_FT::contient_element(), desc_sommets_, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, drapeaux_sommets_, Schema_Comm::echange_taille_et_messages(), Schema_Comm::end_comm(), Entree::eof(), Desc_Structure_FT::espace_distant(), Desc_Structure_FT::espace_virtuel(), Schema_Comm::get_recv_pe_list(), Process::me(), Schema_Comm::recv_buffer(), Schema_Comm::send_buffer(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), sommet_elem_, sommet_face_bord_, sommet_num_owner_, sommet_PE_owner_, sommet_virtuel(), and sommets_.
Referenced by creer_facettes_virtuelles(), creer_sommets_virtuels_numowner(), Maillage_FT_IJK::deplacer_sommets(), echanger_sommets_PE(), Sauvegarde_Reprise_Maillage_FT::lire_xyz(), and Remaillage_FT::marquer_aretes().
creer_sommets_virtuels_numowner()
void Maillage_FT_Disc::creer_sommets_virtuels_numowner (const ArrOfInt & request_sommets_pe, const ArrOfInt & request_sommets_num) protected
Cree chez moi les sommets virtuels specifies par le couple (pe,num) si le sommet n'existe pas encore.
Le sommet est suppose etre reel sur "pe" et le sommet virtuel est cree sur "me()". (c'est l'inverse de "creer_sommets_virtuels" qui cree des sommets virtuels chez chez le pe demande). Fait appel a creer_sommets_virtuels, donc meme preconditions.
Parameters
(request_sommets_pe) une liste de numeros de processeurs DIFFERENTS de me()
(request_sommets_num) une liste de numeros de sommets. Chaque couple pe[i],num[i] designe un sommet reel d'indice "num" sur le processeur "pe". Pour chaque sommet, on cree un sommet virtuel sur me() s'il n'existe pas deja.
References TRUSTArray< _TYPE_, _SIZE_ >::append_array(), Schema_Comm::begin_comm(), creer_sommets_virtuels(), Schema_Comm::echange_taille_et_messages(), Schema_Comm::end_comm(), Entree::eof(), Process::me(), nb_sommets(), Process::nproc(), Schema_Comm::recv_buffer(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), Schema_Comm::send_buffer(), Schema_Comm::set_send_recv_pe_list(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by Remaillage_FT::supprimer_petites_aretes(), and Remaillage_FT_IJK::supprimer_petites_aretes().
echanger_sommets_PE()
void Maillage_FT_Disc::echanger_sommets_PE (const ArrOfInt & liste_sommets, const ArrOfInt & liste_elem_virtuel_arrivee, const ArrOfInt & liste_face_virtuelle_arrivee, const DoubleTab & deplacement, ArrOfInt & liste_nouveaux_sommets, DoubleTab & deplacement_restant, int skip_facettes = 0) protected
Realise l'ensemble des echanges de noeuds specifies dans liste_sommets, liste_elem_virtuel_arrivee et deplacement.
Met a jour les sommets, facettes, espaces distants et virtuels. Le maillage retourne a l'etat minimal. Le buffer d'echange est reinitialise. On stocke dans liste_nouveaux_sommets la liste des numeros des sommets reels fraichement arrives sur le domaine, ainsi que le deplacement restant pour chacun de ces sommets (tableau a 3 colonnes (meme en dimension 2 !), de taille le nombre de nouveaux sommets).
Precondition: Les membres suivants doivent etre valides a l'entree de la fonction: (Meme liste que pour creer_sommets_virtuels(...)) Postcondition: Les memes membres sont valides a la sortie. Attention: on ne met PAS a jour les facettes, la regle de propriete des facettes n'est donc pas verifiee au retour de la fonction. Il faut appeler corriger_proprietaire_facettes.
References TRUSTArray< _TYPE_, _SIZE_ >::append_array(), Schema_Comm::begin_comm(), Comm_Group::check_enabled(), check_mesh(), creer_sommets_virtuels(), desc_sommets_, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Domaine_dis_base::domaine(), Desc_Structure_FT::echange_espace_virtuel(), Schema_Comm::echange_taille_et_messages(), Desc_Structure_FT::echanger_elements(), Domaine_32_64< _SIZE_ >::elem_virt_pe_num(), Schema_Comm::end_comm(), Entree::eof(), Domaine_VF::face_virt_pe_num(), Schema_Comm::get_recv_pe_list(), Process::me(), MINIMAL, Domaine_32_64< _SIZE_ >::nb_elem(), Domaine_VF::nb_faces(), Schema_Comm::recv_buffer(), refdomaine_dis_, Desc_Structure_FT::remplir_element_pe(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), schema_comm_domaine_, Desc_Structure_FT::schema_comm_inverse(), Schema_Comm::send_buffer(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), sommet_elem_, sommet_face_bord_, sommet_ligne_contact(), sommet_num_owner_, sommet_PE_owner_, sommets_, statut_, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by deplacer_sommets().
corriger_proprietaires_facettes()
void Maillage_FT_Disc::corriger_proprietaires_facettes () protected
Sans changer les sommets existants ni la numerotation des facettes, on change le proprietaire des facettes de sorte que ce soit aussi le proprietaire.
du premier sommet de la facette. Pour cela on doit eventuellement creer des sommets virtuels supplementaire et des facettes. Aucune facette n'est supprimee. Certaines facettes reelles sont creees, Certaines facettes reelles deviennent virtuelles. Le maillage retourne a l'etat minimal. Cette methode est utilisee lors de l'algorithme Marching-Cubes, du transport et du remaillage pour amener le maillage dans son etat conforme aux conventions.
Precondition: Les membres suivants doivent etre valides :
Memes membres que creer_facettes_virtuelles
desc_facettes_ (remarque) (remarque) desc_facettes_ doit etre un descripteur valide (correspondance entre elements distants et elements virtuels). En revanche, on suppose que la facette peut etre reelle sur n'importe quel processeur (pas forcement le proprietaire du premier sommet). Postcondition:
Toutes les conditions qui definissent l'etat MINIMAL sont remplies.
References TRUSTArray< _TYPE_, _SIZE_ >::append_array(), Comm_Group::check_enabled(), check_mesh(), creer_facettes_virtuelles(), desc_facettes_, desc_sommets_, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Desc_Structure_FT::echange_espace_virtuel(), Desc_Structure_FT::echanger_elements(), facette_num_owner_, facettes_, Schema_Comm::get_recv_pe_list(), Schema_Comm::get_send_pe_list(), Process::me(), MINIMAL, Desc_Structure_FT::remplir_element_pe(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), Desc_Structure_FT::schema_comm_inverse(), sommet_num_owner_, sommet_PE_owner_, and statut_.
Referenced by Maillage_FT_IJK::corriger_proprietaires_facettes(), Remaillage_FT::diviser_grandes_aretes(), and Remaillage_FT::supprimer_petites_aretes().
creer_facettes_virtuelles()
void Maillage_FT_Disc::creer_facettes_virtuelles (const ArrOfInt & liste_facettes, const ArrOfInt & liste_facettes_pe, const ArrOfInt & facettes_send_pe_list, const ArrOfInt & facettes_recv_pe_list) protected virtual
Creation de facettes virtuelles sur le pe specifie.
liste_facettes = liste de numeros de facettes reelles a envoyer sur le processeur distant (la liste peut comporter des doublons) Le processeur distant ne doit pas etre moi ! liste_pe = numero du pe a qui il faut envoyer chaque facette comm = un schema ou send_pe_list contient les PEs mentionnes dans la liste.
Algo: Il faut d'abord creer les sommets des facettes, s'ils n'existent pas encore, puis creer les facettes. Cas general, le processeur A possede la facette (au sens du descripteur des facettes), le processeur B possede un sommet 's' de la facette, on veut envoyer la facette au processeur C. Il faut: A envoie a B le numero du sommet 's' et le numero du processeur C B cree sur C le sommet virtuel 's' A envoie a C les numeros des sommets 's' de la facette, C peut maintenant creer la facette.
Reimplemented in Maillage_FT_IJK.
References Descripteur_FT::ajoute_element(), TRUSTArray< _TYPE_, _SIZE_ >::append_array(), Schema_Comm::begin_comm(), Descripteur_FT::calcul_liste_pe_voisins(), Desc_Structure_FT::calcul_schema_comm(), Comm_Group::check_enabled(), check_mesh(), Descripteur_FT::contient_element(), convertir_numero_distant_local(), creer_sommets_virtuels(), desc_facettes_, desc_sommets_, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Schema_Comm::echange_taille_et_messages(), Schema_Comm::end_comm(), Entree::eof(), Desc_Structure_FT::espace_distant(), Desc_Structure_FT::espace_virtuel(), facette_num_owner_, facettes_, Entree::get(), Schema_Comm::get_recv_pe_list(), Schema_Comm::get_send_pe_list(), Process::me(), MINIMAL, Process::nproc(), Sortie::put(), Schema_Comm::recv_buffer(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), Desc_Structure_FT::schema_comm_inverse(), Schema_Comm::send_buffer(), Schema_Comm::set_send_recv_pe_list(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), sommet_num_owner_, sommet_PE_owner_, and statut_.
Referenced by corriger_proprietaires_facettes(), Maillage_FT_IJK::creer_facettes_virtuelles(), and echanger_facettes().
buffer_envoyer_facette_PE()
void Maillage_FT_Disc::buffer_envoyer_facette_PE (int num_facette, int PE, int num_element_sur_PE) protected
echanger_facettes()
void Maillage_FT_Disc::echanger_facettes (const ArrOfInt & liste_facettes, const ArrOfInt & liste_elem_arrivee, ArrOfInt & facettes_recues_numfacettes, ArrOfInt & facettes_recues_numelement) protected
Echange des facettes dont les numeros sont fournis dans "liste_facettes" : Pour chaque facette a ajouter,.
On determine le processeur destinataire de la facette (c'est le processeur qui possede l'element_arrivee)
On ajoute la facette sur ce processeur si elle n'existe pas encore (creation d'une facette virtuelle et des sommets de la facette).
On envoie a ce processeur le numero de l'element_arrivee. Le numero est converti en numero local d'un element reel sur ce processeur. Cette methode est essentiellement utilisee dans le parcours de l'interface.
Precondition: Le maillage doit etre dans l'etat minimal (en particulier, il doit respecter la convention "proprietaire facette=proprietaire 1er sommet").
Trois categories de processeurs vont se parler: le processeur A qui connait le numero de la facette a envoyer, le processeur B qui possede la facette, le processeur C a qui on veut envoyer la facette.
Parameters
(liste_facettes) un tableau contenant des numeros de facettes reelles ou virtuelles, eventuellement avec doublons.
(liste_elem_arrivee) tableau de taille identique a liste_facettes, contenant pour chacune un numero d'element virtuel.
(facettes_recues_numfacettes) tableau rempli lors de l'echange avec la liste des facettes qui ont ete recues (meme si elles existaient deja et avec les doublons eventuels). Le contenu initial du tableau est efface. Aliasing ave liste_facettes autorise.
(facettes_recues_numelement) tableau rempli lors de l'echange: pour chaque facette recue, numero de l'element d'arrivee (c'est la traduction du numero d'element virtuel "liste_elem_arrivee" en numero d'element reel sur le processeur qui a recu la facette. Aliasing avec liste_elem_arrivee autorise.
References TRUSTArray< _TYPE_, _SIZE_ >::append_array(), Schema_Comm::begin_comm(), Comm_Group::check_enabled(), check_mesh(), convertir_numero_distant_local(), creer_facettes_virtuelles(), desc_facettes_, Domaine_dis_base::domaine(), Schema_Comm::echange_taille_et_messages(), Domaine_32_64< _SIZE_ >::elem_virt_pe_num(), Schema_Comm::end_comm(), Entree::eof(), facette_num_owner_, facettes_, Schema_Comm::get_recv_pe_list(), Process::me(), Domaine_32_64< _SIZE_ >::nb_elem(), Process::nproc(), Schema_Comm::recv_buffer(), refdomaine_dis_, TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), schema_comm_domaine_, Desc_Structure_FT::schema_comm_inverse(), Schema_Comm::send_buffer(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), sommet_PE_owner_, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Parcours_interface::parcourir().
convertir_numero_distant_local() [1/2]
void Maillage_FT_Disc::convertir_numero_distant_local (const Desc_Structure_FT & descripteur, const ArrOfInt & element_num_owner, const ArrOfInt & numeros_distants, const ArrOfInt & pe_distant, ArrOfInt & numeros_locaux) const protected
Conversion des couples (numeros_distants, pe) en numeros_locaux.
Parametres: descripteur = soit desc_sommets_, soit desc_facettes_, ou un autre element_num_owner = soit sommets_num_owner_, soit facettes_num_owner_, ou equivalent numeros_distants = une liste de numeros de facettes ou sommets qui appartiennent au pe_distant et qui sont virtuels chez moi. Le numero est le numero de la facette ou du sommet sur le pe_distant pe_distant = pour chaque numero de facette ou sommet, le pe proprietaire
Parameters
(numeros_locaux) tableau rempli par cette methode. Le contenu initial est efface. La taille est identique a celle de numeros_distants. On y met le numero local des elements (ce sont des numeros d'elements virtuels). Attention: numeros_locaux et numeros_distants peuvent referencer le meme tableau
References Descripteur_FT::elements(), Desc_Structure_FT::espace_virtuel(), Process::me(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by creer_facettes_virtuelles(), Remaillage_FT::diviser_grandes_aretes(), Remaillage_FT_IJK::diviser_grandes_aretes(), echanger_facettes(), Remaillage_FT::marquer_aretes(), Remaillage_FT::supprimer_petites_aretes(), and Remaillage_FT_IJK::supprimer_petites_aretes().
convertir_numero_distant_local() [2/2]
void Maillage_FT_Disc::convertir_numero_distant_local (const Desc_Structure_FT & descripteur, const ArrOfInt & element_num_owner, const int numero_distant, const int pe_distant, int & numero_local) const protected
References Descripteur_FT::elements(), Desc_Structure_FT::espace_virtuel(), Process::me(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
deplacer_sommets()
void Maillage_FT_Disc::deplacer_sommets (const ArrOfInt & liste_sommets_initiale, const DoubleTab & deplacement_initial, ArrOfInt & liste_sommets_sortis, ArrOfInt & numero_face_sortie, int skip_facettes = 0) protected virtual
Applique un vecteur deplacement aux noeuds dont le numero est dans "liste_noeud", puis echange les espaces virtuels.
Si un noeud traverse un joint, il change de proprietaire. Si un noeud rencontre une paroi, il s'arrete sur la paroi et on le transforme en noeud "ligne de contact". Si un noeud est sur une paroi (noeud "ligne de contact"), il longe la paroi (on deplace le noeud de face de bord en face de bord en minimisant la distance entre le noeud et le deplacement demande.
Parameters
(liste_sommets_initiale) une liste non redondante de noeuds REELS a deplacer
(deplacement_initial) le vecteur deplacement des noeuds de "liste_noeuds" (dimension(0)==liste_noeuds.size_array() et dimension(1)==dimension)
Reimplemented in Maillage_FT_IJK.
References Comm_Group::check_enabled(), Process::check_int_overflow(), check_mesh(), check_sommets(), deplacer_un_sommet(), desc_sommets_, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Desc_Structure_FT::echange_espace_virtuel(), echanger_sommets_PE(), Domaine_VF::face_voisins(), get_is_solid_particle(), Process::je_suis_maitre(), Process::mp_sum(), refdomaine_dis_, refparcours_interface_, TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), sommet_elem_, sommet_face_bord_, sommets_, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Remaillage_FT::diviser_grandes_aretes(), and transporter_simple().
check_sommets()
int Maillage_FT_Disc::check_sommets (int error_is_fatal = 1) const protected virtual
Reimplemented in Maillage_FT_IJK.
References Desc_Structure_FT::check(), desc_sommets_, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Parcours_interface::distance_sommet_faces(), Desc_Structure_FT::echange_espace_virtuel(), Descripteur_FT::elements(), Desc_Structure_FT::espace_distant(), Desc_Structure_FT::espace_virtuel(), Process::exit(), Domaine_VF::face_voisins(), Parcours_interface::get_erreur_geometrique(), Process::Journal(), Process::me(), Domaine_dis_base::nb_elem(), nb_sommets(), Descripteur_FT::pe_voisins(), refdomaine_dis_, refparcours_interface_, Desc_Structure_FT::remplir_element_pe(), RESET, TRUSTArray< _TYPE_, _SIZE_ >::size_array(), sommet_elem_, sommet_face_bord_, sommet_num_owner_, sommet_PE_owner_, sommet_virtuel(), sommets_, statut_, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by check_mesh(), creer_sommets_virtuels(), and deplacer_sommets().
check_mesh()
int Maillage_FT_Disc::check_mesh (int error_is_fatal = 1, int skip_facette_owner = 0, int skip_facettes = 0) const protected virtual
Reimplemented in Maillage_FT_IJK.
References Statistiques::begin_count(), Desc_Structure_FT::check(), check_sommets(), desc_facettes(), desc_facettes_, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Desc_Structure_FT::echange_espace_virtuel(), Descripteur_FT::elements(), Statistiques::end_count(), Desc_Structure_FT::espace_distant(), Desc_Structure_FT::espace_virtuel(), Process::exit(), facette_num_owner_, facettes_, Process::Journal(), Process::me(), nb_facettes(), Statistiques::new_counter(), Descripteur_FT::pe_voisins(), printFa7(), Desc_Structure_FT::remplir_element_pe(), RESET, TRUSTArray< _TYPE_, _SIZE_ >::size_array(), sommet_PE_owner_, sommets_, and statut_.
Referenced by ajouter_maillage(), Maillage_FT_IJK::check_mesh(), corriger_proprietaires_facettes(), creer_facettes_virtuelles(), deplacer_sommets(), echanger_facettes(), echanger_sommets_PE(), nettoyer_maillage(), nettoyer_noeuds_virtuels_et_frontieres(), nettoyer_phase(), Remaillage_FT::remaillage_local_interface(), reprendre(), Remaillage_FT::supprimer_doublons_facettes(), Remaillage_FT::supprimer_facettes_bord(), and Remaillage_FT::supprimer_facettes_nulles().
construire_noeuds()
void Maillage_FT_Disc::construire_noeuds (IntTab & def_noeud, const DoubleTab & soms) protected
References Domaine_32_64< _SIZE_ >::chercher_elements(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Process::exit(), Process::me(), Ensemble_Lagrange_base::mon_dom_, Domaine_32_64< _SIZE_ >::nb_elem(), Process::nproc(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), and TRUSTArray< _TYPE_, _SIZE_ >::resize_array().
Referenced by remplir_structure().
calculer_coord_noeuds()
void Maillage_FT_Disc::calculer_coord_noeuds (const IntTab & def_noeud, const DoubleTab & soms, IntTab & renum) protected
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, TRUSTTab< _TYPE_, _SIZE_ >::resize(), and sommets_.
Referenced by remplir_structure().
mesh_data_cache()
Maillage_FT_Disc_Data_Cache & Maillage_FT_Disc::mesh_data_cache () const protected
renvoie une ref non const au cache de valeurs calculees sur le maillage (courbure, surface, normale, .
..) On fait un cast de l'objet en non const (voir commentaire sur mesh_data_cache_ dans Maillage_FT_Disc.h)
References mesh_data_cache_, and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by get_normale_facettes(), get_surface_facettes(), get_update_courbure_sommets(), get_update_normale_facettes(), get_update_surface_facettes(), recopie(), and reset().
Friends And Related Function Documentation
Post_Processing_Hydrodynamic_Forces
friend class Post_Processing_Hydrodynamic_Forces friend
Marching_Cubes
friend class Marching_Cubes friend
Parcours_interface
friend class Parcours_interface friend
Remaillage_FT
friend class Remaillage_FT friend
Remaillage_FT_IJK
friend class Remaillage_FT_IJK friend
Topologie_Maillage_FT
friend class Topologie_Maillage_FT friend
Remailleur_Collision_FT_Collision_Seq
friend class Remailleur_Collision_FT_Collision_Seq friend
Sauvegarde_Reprise_Maillage_FT
friend class Sauvegarde_Reprise_Maillage_FT friend
Member Data Documentation
info_obj
const Type_info Maillage_FT_Disc::info_obj static
refequation_transport_
TRUST_Ref< Transport_Interfaces_FT_Disc *> Maillage_FT_Disc::refequation_transport_ protected
Referenced by associer_equation_transport(), calcul_courbure_sommets(), calcul_indicatrice(), equation_transport(), and recopie().
refdomaine_dis_
TRUST_Ref< Domaine_dis_base *> Maillage_FT_Disc::refdomaine_dis_ protected
Referenced by associer_domaine_dis_parcours(), calcul_indicatrice(), calculer_voisinage_facettes(), check_sommets(), deplacer_sommets(), echanger_facettes(), echanger_sommets_PE(), recopie(), reprendre(), and sauvegarder().
refparcours_interface_
TRUST_Ref< Parcours_interface *> Maillage_FT_Disc::refparcours_interface_ protected
Referenced by associer_domaine_dis_parcours(), calcul_courbure_sommets(), check_sommets(), deplacer_sommets(), parcourir_maillage(), recopie(), Remaillage_FT::redistribuer_sommets(), and Remaillage_FT::supprimer_facettes_bord().
som_init_util_
ArrOfIntFT Maillage_FT_Disc::som_init_util_ protected
Referenced by remplir_structure(), and som_init_util().
schema_comm_domaine_
Schema_Comm Maillage_FT_Disc::schema_comm_domaine_ protected
Referenced by associer_domaine_dis_parcours(), echanger_facettes(), echanger_sommets_PE(), get_schema_comm_FT(), and recopie().
statut_
Statut_Maillage Maillage_FT_Disc::statut_ protected
Referenced by ajouter_maillage(), calcul_indicatrice(), calcul_surface_normale(), calculer_voisinage_facettes(), calculer_voisins(), check_mesh(), check_sommets(), Maillage_FT_IJK::check_sommets(), completer_maillage(), corriger_proprietaires_facettes(), creer_facettes_virtuelles(), desc_facettes(), desc_sommets(), drapeaux_sommets(), echanger_sommets_PE(), facette_PE_owner(), facettes(), intersections_elem_facettes(), Maillage_FT_IJK::lire_maillage_ft_dans_lata(), Sauvegarde_Reprise_Maillage_FT::lire_xyz(), maillage_modifie(), nb_facettes(), nb_facettes_reelle_totale(), nb_facettes_reelles(), Maillage_FT_IJK::nb_facettes_sans_duplicata(), nb_facettes_totale(), nb_sommets(), nettoyer_maillage(), nettoyer_noeuds_virtuels_et_frontieres(), nettoyer_phase(), parcourir_maillage(), remplir_structure(), sommet_elem(), sommet_face_bord(), sommet_num_owner(), sommet_PE_owner(), sommets(), and type_statut().
mesh_state_tag_
int Maillage_FT_Disc::mesh_state_tag_ protected
Referenced by get_mesh_tag(), maillage_modifie(), reprendre(), and sauvegarder().
temps_physique_
double Maillage_FT_Disc::temps_physique_ protected
Referenced by calcul_courbure_sommets(), changer_temps(), Sauvegarde_Reprise_Maillage_FT::ecrire_xyz(), Sauvegarde_Reprise_Maillage_FT::lire_xyz(), recopie(), reprendre(), sauvegarder(), and temps().
sommets_
DoubleTabFT Maillage_FT_Disc::sommets_ protected
Referenced by ajouter_maillage(), calcul_courbure_sommets(), Parcours_interface::calcul_intersection_facelem_2D(), Parcours_interface::calcul_intersection_facelem_3D(), calcul_normale_3D(), calcul_surface_normale(), calcule_equation_plan_areteFa7(), Marching_Cubes::calculer_coord_noeuds(), calculer_coord_noeuds(), check_mesh(), check_sommets(), Maillage_FT_IJK::check_sommets(), compute_gravity_center_fa7(), coords_fa7(), copier_sommet(), creer_sommets_virtuels(), deplacer_sommets(), Maillage_FT_IJK::deplacer_sommets(), echanger_sommets_PE(), ecrire_plot(), Sauvegarde_Reprise_Maillage_FT::ecrire_xyz(), Parcours_interface::eloigner_sommets_des_faces(), Maillage_FT_IJK::lire_maillage_ft_dans_lata(), Sauvegarde_Reprise_Maillage_FT::lire_xyz(), Remaillage_FT::marquer_aretes(), nb_sommets(), nettoyer_maillage(), nettoyer_noeuds_virtuels_et_frontieres(), nettoyer_phase(), Parcours_interface::parcourir(), printSom(), recopie(), remplir_structure(), reprendre(), reset(), Maillage_FT_IJK::sauv_facette_indexation_avant_transport(), sauvegarder(), sommets(), Remaillage_FT_IJK::supprimer_petites_aretes(), transporter(), transporter_simple(), Maillage_FT_IJK::update_surfactant_apres_transport(), and Parcours_interface::volume_tetraedre().
facettes_
IntTabFT Maillage_FT_Disc::facettes_ protected
Referenced by ajouter_maillage(), calcul_courbure_sommets(), Parcours_interface::calcul_intersection_facelem_2D(), Parcours_interface::calcul_intersection_facelem_3D(), calcul_normale_3D(), calcul_surface_normale(), calcule_equation_plan_areteFa7(), Maillage_FT_IJK::calculer_compo_connexe_sommets(), calculer_voisinage_facettes(), check_mesh(), compute_gravity_center_fa7(), Marching_Cubes::construire_noeuds_uniques(), coords_fa7(), corriger_proprietaires_facettes(), creer_facettes_virtuelles(), Remaillage_FT::diviser_grandes_aretes(), Remaillage_FT_IJK::diviser_grandes_aretes(), echanger_facettes(), ecrire_plot(), Sauvegarde_Reprise_Maillage_FT::ecrire_xyz(), facette_PE_owner(), facette_virtuelle(), facettes(), facettes_voisines(), Maillage_FT_IJK::lire_maillage_ft_dans_lata(), Sauvegarde_Reprise_Maillage_FT::lire_xyz(), Maillage_FT_IJK::minimum_longueur_arrete(), nb_facettes(), nb_facettes_reelle_totale(), nb_facettes_reelles(), Maillage_FT_IJK::nb_facettes_sans_duplicata(), nb_facettes_totale(), nettoyer_maillage(), Maillage_FT_IJK::nettoyer_maillage(), Parcours_interface::parcourir(), printFa7(), recopie(), reprendre(), reset(), Maillage_FT_IJK::sauv_facette_indexation_avant_transport(), sauvegarder(), Remaillage_FT::supprimer_doublons_facettes(), supprimer_facettes(), Remaillage_FT::supprimer_facettes_bord(), Remaillage_FT::supprimer_facettes_nulles(), Remaillage_FT::supprimer_petites_aretes(), Remaillage_FT_IJK::supprimer_petites_aretes(), Maillage_FT_IJK::update_surfactant_apres_transport(), and Parcours_interface::volume_tetraedre().
liste_facette_supprimees_et_voisines_
IntTabFT Maillage_FT_Disc::liste_facette_supprimees_et_voisines_ protected
Referenced by get_liste_facette_supprimees_et_voisines(), and set_liste_facette_supprimees_et_voisines().
nb_facette_supprimees_
int Maillage_FT_Disc::nb_facette_supprimees_ protected
Referenced by get_nb_facette_supprimees(), and set_nb_facette_supprimees().
sommet_elem_
ArrOfIntFT Maillage_FT_Disc::sommet_elem_ protected
Referenced by ajouter_maillage(), calcul_courbure_sommets(), Remaillage_FT::calculer_longueurIdeale2_arete(), check_sommets(), Maillage_FT_IJK::check_sommets(), copier_sommet(), creer_sommets_virtuels(), deplacer_sommets(), Maillage_FT_IJK::deplacer_sommets(), echanger_sommets_PE(), Sauvegarde_Reprise_Maillage_FT::ecrire_xyz(), Parcours_interface::eloigner_sommets_des_faces(), facette_virtuelle(), Maillage_FT_IJK::get_ijk_cell_index(), Maillage_FT_IJK::lire_maillage_ft_dans_lata(), Sauvegarde_Reprise_Maillage_FT::lire_xyz(), Remaillage_FT::marquer_aretes(), nettoyer_maillage(), nettoyer_noeuds_virtuels_et_frontieres(), nettoyer_phase(), Parcours_interface::parcourir(), printSom(), recopie(), remplir_structure(), reprendre(), reset(), sauvegarder(), Maillage_FT_IJK::set_ijk_cell_index(), sommet_elem(), sommet_virtuel(), and Remaillage_FT::traite_decollement().
sommet_face_bord_
ArrOfIntFT Maillage_FT_Disc::sommet_face_bord_ protected
Referenced by ajouter_maillage(), calcul_courbure_sommets(), calculer_costheta_minmax(), check_sommets(), Maillage_FT_IJK::check_sommets(), copier_sommet(), copier_sommet_interne(), creer_sommets_virtuels(), deplacer_sommets(), echanger_sommets_PE(), Sauvegarde_Reprise_Maillage_FT::ecrire_xyz(), Maillage_FT_IJK::lire_maillage_ft_dans_lata(), Sauvegarde_Reprise_Maillage_FT::lire_xyz(), Remaillage_FT::marquer_aretes(), nettoyer_maillage(), nettoyer_noeuds_virtuels_et_frontieres(), nettoyer_phase(), printSom(), recopie(), Remaillage_FT::redistribuer_sommets(), remplir_structure(), reprendre(), reset(), sauvegarder(), sommet_face_bord(), sommet_ligne_contact(), Remaillage_FT::supprimer_facettes_bord(), and Remaillage_FT::traite_decollement().
sommet_PE_owner_
ArrOfIntFT Maillage_FT_Disc::sommet_PE_owner_ protected
Referenced by ajouter_maillage(), Remaillage_FT::calculer_variation_volume_facette_3D(), check_mesh(), check_sommets(), Maillage_FT_IJK::check_sommets(), copier_sommet(), corriger_proprietaires_facettes(), creer_facettes_virtuelles(), creer_sommets_virtuels(), Maillage_FT_IJK::deplacer_sommets(), echanger_facettes(), echanger_sommets_PE(), Maillage_FT_IJK::lire_maillage_ft_dans_lata(), Sauvegarde_Reprise_Maillage_FT::lire_xyz(), Remaillage_FT::marquer_aretes(), nettoyer_maillage(), nettoyer_noeuds_virtuels_et_frontieres(), nettoyer_phase(), printFa7(), printSom(), recopie(), remplir_structure(), reprendre(), reset(), sauvegarder(), and sommet_PE_owner().
sommet_num_owner_
ArrOfIntFT Maillage_FT_Disc::sommet_num_owner_ protected
Referenced by ajouter_maillage(), Remaillage_FT::calculer_variation_volume_facette_3D(), check_sommets(), Maillage_FT_IJK::check_sommets(), copier_sommet(), corriger_proprietaires_facettes(), creer_facettes_virtuelles(), creer_sommets_virtuels(), Maillage_FT_IJK::deplacer_sommets(), Remaillage_FT::diviser_grandes_aretes(), Remaillage_FT_IJK::diviser_grandes_aretes(), echanger_sommets_PE(), Maillage_FT_IJK::lire_maillage_ft_dans_lata(), Sauvegarde_Reprise_Maillage_FT::lire_xyz(), Remaillage_FT::marquer_aretes(), nettoyer_maillage(), nettoyer_noeuds_virtuels_et_frontieres(), nettoyer_phase(), printFa7(), printSom(), recopie(), remplir_structure(), reprendre(), reset(), sauvegarder(), and sommet_num_owner().
facette_num_owner_
ArrOfIntFT Maillage_FT_Disc::facette_num_owner_ protected
Referenced by ajouter_maillage(), check_mesh(), corriger_proprietaires_facettes(), creer_facettes_virtuelles(), echanger_facettes(), Maillage_FT_IJK::lire_maillage_ft_dans_lata(), Sauvegarde_Reprise_Maillage_FT::lire_xyz(), nettoyer_maillage(), recopie(), reprendre(), and sauvegarder().
desc_sommets_
Desc_Structure_FT Maillage_FT_Disc::desc_sommets_ protected
Referenced by ajouter_maillage(), Marching_Cubes::calculer_coord_noeuds(), calculer_costheta_minmax(), check_sommets(), Maillage_FT_IJK::check_sommets(), Marching_Cubes::construire_noeuds_uniques(), corriger_proprietaires_facettes(), creer_facettes_virtuelles(), creer_sommets_virtuels(), deplacer_sommets(), Maillage_FT_IJK::deplacer_sommets(), desc_sommets(), echanger_sommets_PE(), Maillage_FT_IJK::lire_maillage_ft_dans_lata(), Sauvegarde_Reprise_Maillage_FT::lire_xyz(), Remaillage_FT::marquer_aretes(), nettoyer_maillage(), nettoyer_noeuds_virtuels_et_frontieres(), nettoyer_phase(), recopie(), remplir_structure(), reprendre(), reset(), and sauvegarder().
desc_facettes_
Desc_Structure_FT Maillage_FT_Disc::desc_facettes_ protected
Referenced by ajouter_maillage(), check_mesh(), corriger_proprietaires_facettes(), creer_facettes_virtuelles(), desc_facettes(), Remaillage_FT::diviser_grandes_aretes(), Remaillage_FT_IJK::diviser_grandes_aretes(), echanger_facettes(), facette_PE_owner(), Maillage_FT_IJK::lire_maillage_ft_dans_lata(), Sauvegarde_Reprise_Maillage_FT::lire_xyz(), nettoyer_maillage(), recopie(), reprendre(), reset(), and sauvegarder().
drapeaux_sommets_
ArrOfIntFT Maillage_FT_Disc::drapeaux_sommets_ protected
Referenced by ajouter_maillage(), copier_sommet(), creer_sommets_virtuels(), drapeaux_sommets(), Maillage_FT_IJK::lire_maillage_ft_dans_lata(), Sauvegarde_Reprise_Maillage_FT::lire_xyz(), Remaillage_FT::marquer_aretes(), nettoyer_maillage(), nettoyer_noeuds_virtuels_et_frontieres(), nettoyer_phase(), recopie(), remplir_structure(), reprendre(), reset(), and sauvegarder().
EFFACE
const int Maillage_FT_Disc::EFFACE = 1 static protected
intersections_elem_facettes_
Intersections_Elem_Facettes Maillage_FT_Disc::intersections_elem_facettes_ protected
Referenced by calcul_indicatrice(), Parcours_interface::calcul_intersection_facelem_2D(), Parcours_interface::calcul_intersection_facelem_3D(), calculer_voisinage_facettes(), intersections_elem_facettes(), maillage_modifie(), Parcours_interface::parcourir(), Parcours_interface::parcours_facette(), recopie(), and reset().
voisins_
IntTabFT Maillage_FT_Disc::voisins_ protected
Referenced by recopie(), reprendre(), reset(), and sauvegarder().
mesh_data_cache_
TRUST_Deriv< Maillage_FT_Disc_Data_Cache > Maillage_FT_Disc::mesh_data_cache_ protected
Referenced by Maillage_FT_Disc(), and mesh_data_cache().
niveau_plot_
int Maillage_FT_Disc::niveau_plot_ protected
Referenced by ecrire_plot(), lire_param_maillage(), and set_niveau_plot().
correction_contact_courbure_coeff_
double Maillage_FT_Disc::correction_contact_courbure_coeff_ protected
Referenced by calcul_courbure_sommets(), and lire_param_maillage().
calcul_courbure_iterations_
int Maillage_FT_Disc::calcul_courbure_iterations_ protected
Referenced by get_update_courbure_sommets(), and lire_param_maillage().
niter_pre_lissage_
int Maillage_FT_Disc::niter_pre_lissage_ protected
Referenced by calcul_courbure_sommets(), and lire_param_maillage().
methode_calcul_courbure_contact_line_
int Maillage_FT_Disc::methode_calcul_courbure_contact_line_ protected
Referenced by calcul_courbure_sommets(), and lire_param_maillage().
weight_CL_
double Maillage_FT_Disc::weight_CL_ protected
Referenced by calcul_courbure_sommets(), and lire_param_maillage().
is_solid_particle_
bool Maillage_FT_Disc::is_solid_particle_ =false protected
Referenced by calcul_indicatrice(), get_is_solid_particle(), and set_is_solid_particle().
gravity_center_fa7_
DoubleTab Maillage_FT_Disc::gravity_center_fa7_ protected
Referenced by compute_gravity_center_fa7(), and get_gravity_center_fa7().