TrioCFD: MorEqn Class Reference
MorEqn Class Reference
#include <MorEqn.h>
Public Member Functions
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Detailed Description
Equation. Le membre MorEqn::mon_equation contient une reference
vers un objet Equation_base. Les classes qui sont des "Morceaux d'equation"
sont associe par une liaison 1-1 a leur equation en heritant de MorEqn,
par exemple: Operateur_base, Solveur_Masse, Source_base ...
See also
Equation_base, Ce n'est pas une classe de l'arbre TRUST a elle seule., Cette classe est faite etre une classe mere d'une classe, qui heritera par ailleurs d'Objet_U
Constructor & Destructor Documentation
~MorEqn()
MorEqn::~MorEqn () inline protected virtual
Member Function Documentation
associer_eqn()
void MorEqn::associer_eqn (const Equation_base & eqn)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet passe en parametre.
Parameters
(Equation_base& eqn) l'equation a laquelle on veut s'associer
References mon_equation.
Referenced by Champ_Inc_base::associer_eqn(), Operateur_base::associer_eqn(), Equation_base::associer_pb_base(), Navier_Stokes_std::associer_pb_base(), Equation_rayonnement_base::associer_pb_base(), Convection_diffusion_turbulence_multiphase::completer(), Convection_Diffusion_Temperature_FT_Disc::completer(), Transport_K_Omega::completer(), Convection_Diffusion_Chaleur_WC::completer(), Masse_Multiphase::completer(), Champ_Generique_Divergence::completer(), Champ_Generique_Gradient::completer(), Convection_Diffusion_Temperature_FT_Disc::compute_divergence_free_velocity_extension(), Equation_base::discretiser(), Transport_Interfaces_FT_Disc::discretiser(), Convection_Diffusion_Phase_field::discretiser(), Op_Evanescence_Homogene_VDF_Face::preparer_calcul(), Op_Conv_ALE_VEF::readOn(), Operateur_Conv_sensibility_VEF::readOn(), Aire_interfaciale::readOn(), Energie_Multiphase::readOn(), Masse_Multiphase::readOn(), and QDM_Multiphase::readOn().
calculer_pour_post()
void MorEqn::calculer_pour_post (Champ_base & espace_stockage, const Nom & option, int comp) const virtual
Reimplemented in Op_Dift_EF_Q1, Operateur_base, Op_Diff_negligeable, Op_Conv_PolyMAC_iterateur_base, Op_Conv_VDF_base, Op_Conv_VEF_base, Op_Diff_VEF_base, Op_Dift_VEF_base, and Op_Conv_EF_base.
References Process::exit().
Referenced by Champ_Generique_Morceau_Equation::get_champ().
get_localisation_pour_post()
Motcle MorEqn::get_localisation_pour_post (const Nom & option) const virtual
Reimplemented in Operateur_base, Op_Diff_negligeable, Op_Conv_PolyMAC_iterateur_base, Op_Conv_VDF_base, Op_Conv_VEF_base, and Op_Diff_VEF_base.
References Process::exit().
Referenced by Champ_Generique_Morceau_Equation::completer().
equation() [1/2]
const Equation_base & MorEqn::equation () const inline
Renvoie la reference sur l'equation pointe par MorEqn::mon_equation.
(version const)
Returns
(Equation_base&) l'equation associee a l'objet
Exceptions
pas d'equation associee
References Process::exit(), mon_equation, TRUST_Ref< _CLASSE_ >::non_nul(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Op_Diff_VDF_base::ajoute_terme_pour_axi(), Op_Dift_VDF_base::ajoute_terme_pour_axi_turb(), Operateur::ajouter(), Operateur_base::ajouter(), Operateur_Conv_sensibility_VEF::ajouter(), Op_Diff_EF::ajouter(), Op_Dift_EF_Q1::ajouter(), Op_Div_EF::ajouter(), Op_Diff_PolyMAC_Elem::ajouter(), Op_Div_PolyMAC::ajouter(), Op_Div_PolyMAC_P0::ajouter(), Op_Conv_ALE::ajouter(), Op_Conv_Amont_old_VEF_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Centre_EF_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_EF_VEF_P1NC::ajouter(), Op_Conv_EF_VEF_P1NC_Stab::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_Muscl_New_VEF_Face::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Diff_VEF_Anisotrope_Face::ajouter(), Op_Diff_VEF_Face::ajouter(), Op_Diff_VEF_Face_Stab::ajouter(), Op_Diff_VEFP1NCP1B_Face::ajouter(), Op_Dift_Stab_VEF_Face::ajouter(), Op_Dift_VEF_Face::ajouter(), Op_Dift_VEF_Face_Q1::ajouter(), Op_Div_VEFP1B_Elem::ajouter(), Op_Conv_EF_Stab_PolyMAC_Face::ajouter(), Op_Diff_PolyMAC_Face::ajouter(), Source_Flottabilite::ajouter(), Source_Masse_Ajoutee::ajouter(), Source_Portance::ajouter(), Source_Trainee::ajouter(), Source_Reaction_Particules_VDF::ajouter(), Source_Reaction_Particules_VEF::ajouter(), SourceFiltree_FT_disc_VEF_P1NC::ajouter(), Source_Gravite_PF_VDF::ajouter(), Terme_Boussinesq_Sensibility_VEFPreP1B_Face::ajouter(), Source_Transport_Fluctuation_Temperature_VDF_Elem::ajouter(), Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::ajouter(), Source_Transport_Fluctuation_Temperature_W_VDF_Elem::ajouter(), Source_Transport_Flux_Chaleur_Turbulente_VDF_Face::ajouter(), Source_Robin::ajouter(), Source_Robin_Scalaire::ajouter(), Source_Scalaire_EF::ajouter(), Perte_Charge_PolyMAC::ajouter(), Perte_Charge_Singuliere_PolyMAC_Face::ajouter(), Source_Generique_Face_PolyMAC::ajouter(), Source_Generique_Face_PolyMAC_P0P1NC::ajouter(), Terme_Source_Qdm_Face_PolyMAC::ajouter(), Source_QC_QDM_Gen::ajouter(), Terme_Source_Canal_perio_VEF_P1NC::ajouter(), Terme_Source_Canal_RANS_LES_VEF_Face::ajouter(), Perte_Charge_Reguliere_VEF_P1NC::ajouter(), Perte_Charge_Singuliere_VEF_Face::ajouter(), Perte_Charge_VEF::ajouter(), Source_Generique_VEF::ajouter(), Terme_Boussinesq_VEF_Face::ajouter(), Terme_Boussinesq_VEFPreP1B_Face::ajouter(), Terme_Source_Acceleration_VEF_Face::ajouter(), Terme_Source_Decroissance_Radioactive_VEF_Face::ajouter(), Terme_Source_Qdm_lambdaup_VEF_Face::ajouter(), Terme_Source_Qdm_VEF_Face::ajouter(), Terme_Source_Th_TdivU_VEF_Face::ajouter(), Source_rayo_semi_transp_VDF_P0_VDF::ajouter(), Source_rayo_semi_transp_VEF_P1NC::ajouter(), Source_dep_inco_base::ajouter(), Perte_Charge_Reguliere_VDF_Face::ajouter_(), Perte_Charge_Singuliere_VDF_Face::ajouter_(), Op_Grad_VEF_P1B_Face::ajouter_aretes(), Tenseur_Reynolds_Externe_VDF_Face::ajouter_blocs(), Op_Diff_K_Eps_VDF_base::ajouter_blocs(), Op_Diff_K_Omega_VDF_base::ajouter_blocs(), Source_Transport_Realisable_VDF_Elem_base::ajouter_blocs(), Source_Transport_Eps_VDF_Elem::ajouter_blocs(), Source_Transport_K_VDF_Elem::ajouter_blocs(), Source_Transport_K_Eps_VDF_Elem::ajouter_blocs(), Source_Transport_K_Omega_VDF_Elem::ajouter_blocs(), Op_Grad_P0_to_Face::ajouter_blocs(), Op_Grad_VDF_Face::ajouter_blocs(), Terme_Source_Canal_perio_VDF_Face::ajouter_blocs(), Terme_Source_Canal_RANS_LES_VDF_Face::ajouter_blocs(), Acceleration_QC_VDF_Face::ajouter_blocs(), Source_qdm_QC_VDF_Face::ajouter_blocs(), Perte_Charge_Reguliere_QC_VDF_Face::ajouter_blocs(), Perte_Charge_Singuliere_QC_VDF_Face::ajouter_blocs(), Darcy_QC_VDF_Face::ajouter_blocs(), Forchheimer_QC_VDF_Face::ajouter_blocs(), Perte_Charge_Reguliere_VDF_Face::ajouter_blocs(), Perte_Charge_Singuliere_VDF_Face::ajouter_blocs(), Source_Generique_VDF_Face::ajouter_blocs(), Terme_Boussinesq_VDF_Face::ajouter_blocs(), Terme_Source_Acceleration_VDF_Face::ajouter_blocs(), Terme_Source_Coriolis_VDF_Face::ajouter_blocs(), Terme_Source_inc_th_VDF_Face::ajouter_blocs(), Terme_Source_inc_VDF_Face::ajouter_blocs(), Terme_Source_Qdm_VDF_Face::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_P0_Face::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Face::ajouter_blocs(), Op_Diff_PolyMAC_P0_Face::ajouter_blocs(), Op_Grad_PolyMAC_P0_Face::ajouter_blocs(), Op_Grad_PolyMAC_P0P1NC_Face::ajouter_blocs(), Coalescence_bulles_1groupe_PolyMAC_P0::ajouter_blocs(), Coalescence_bulles_2groupes_PolyMAC_P0::ajouter_blocs(), Correction_Lubchenko_PolyMAC_P0::ajouter_blocs(), Flux_2groupes_PolyMAC_P0::ajouter_blocs(), Injection_QDM_nulle_PolyMAC_P0::ajouter_blocs(), Nucleation_paroi_PolyMAC_P0::ajouter_blocs(), Rupture_bulles_1groupe_PolyMAC_P0::ajouter_blocs(), Rupture_bulles_2groupes_PolyMAC_P0::ajouter_blocs(), Variation_rho::ajouter_blocs(), Source_injection_masse_base::ajouter_blocs(), Injection_QDM_nulle_VDF::ajouter_blocs(), Diffusion_croisee_echelle_temp_taux_diss_turb_PolyMAC_P0::ajouter_blocs(), Diffusion_supplementaire_echelle_temp_turb_PolyMAC_P0::ajouter_blocs(), Dissipation_WIT_PolyMAC_P0::ajouter_blocs(), Production_echelle_temp_taux_diss_turb_PolyMAC_P0::ajouter_blocs(), Production_energie_cin_turb_PolyMAC_P0::ajouter_blocs(), Production_HZDR_PolyMAC_P0::ajouter_blocs(), Production_WIT_PolyMAC_P0::ajouter_blocs(), Source_BIF_PolyMAC_P0::ajouter_blocs(), Source_Dissipation_HZDR_PolyMAC_P0::ajouter_blocs(), Source_Dissipation_echelle_temp_taux_diss_turb::ajouter_blocs(), Source_Dissipation_energie_cin_turb::ajouter_blocs(), Diffusion_croisee_echelle_temp_taux_diss_turb_VDF::ajouter_blocs(), Diffusion_supplementaire_echelle_temp_turb_VDF::ajouter_blocs(), Production_echelle_temp_taux_diss_turb_VDF::ajouter_blocs(), Production_energie_cin_turb_VDF::ajouter_blocs(), Op_Diff_DG_Elem::ajouter_blocs(), Correction_Antal_PolyMAC_P0::ajouter_blocs(), Correction_Tomiyama_PolyMAC_P0::ajouter_blocs(), Dispersion_bulles_PolyMAC_P0::ajouter_blocs(), Frottement_interfacial_PolyMAC_P0::ajouter_blocs(), Portance_interfaciale_PolyMAC_P0::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::ajouter_blocs(), Op_Diff_PolyMAC_P0_Elem::ajouter_blocs(), DP_Impose_PolyMAC_Face::ajouter_blocs(), Perte_Charge_PolyMAC::ajouter_blocs(), Perte_Charge_Singuliere_PolyMAC_P0P1NC_Face::ajouter_blocs(), Terme_Boussinesq_PolyMAC_Face::ajouter_blocs(), Terme_Source_Decroissance_Radioactive_Elem_PolyMAC::ajouter_blocs(), Terme_Source_Qdm_Face_PolyMAC_P0P1NC::ajouter_blocs(), Op_Evanescence_Homogene_Elem_base::ajouter_blocs(), Op_Evanescence_Homogene_Face_base::ajouter_blocs(), Source_Flux_interfacial_base::ajouter_blocs(), Source_Force_Tchen_base::ajouter_blocs(), Source_Travail_pression_Elem_base::ajouter_blocs(), Correction_Antal_VDF::ajouter_blocs(), Dispersion_bulles_VDF::ajouter_blocs(), Frottement_interfacial_VDF::ajouter_blocs(), Portance_interfaciale_VDF::ajouter_blocs(), Op_Conv_Amont_VPoly_VDF_Face::ajouter_blocs(), Perte_Charge_VDF_base::ajouter_blocs(), DP_Impose_VEF_Face::ajouter_blocs(), Masse_DG_base::ajouter_blocs(), Masse_PolyMAC_P0_Face::ajouter_blocs(), Masse_VDF_base::ajouter_blocs(), Masse_VDF_Face::ajouter_blocs(), Op_Evanescence_Homogene_PolyMAC_P0_Face::ajouter_blocs_aux(), Force_Tchen_PolyMAC_P0::ajouter_blocs_aux(), Correction_Lubchenko_PolyMAC_P0::ajouter_blocs_BIF(), Correction_Lubchenko_PolyMAC_P0::ajouter_blocs_disp(), Op_Div_PolyMAC_P0P1NC::ajouter_blocs_ext(), Op_Diff_PolyMAC_P0P1NC_Elem::ajouter_blocs_ext(), Op_Diff_PolyMAC_P0P1NC_Face::ajouter_blocs_ext(), Correction_Lubchenko_PolyMAC_P0::ajouter_blocs_lift(), Op_Diff_EF::ajouter_bords(), Op_Dift_EF_Q1::ajouter_bords(), Op_Diff_EF::ajouter_contribution(), Op_Dift_EF_Q1::ajouter_contribution(), Op_Conv_Amont_old_VEF_Face::ajouter_contribution(), Op_Conv_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution(), Op_Diff_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Face_Stab::ajouter_contribution(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution(), Op_Conv_RT_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face_Stab::ajouter_contribution_multi_scalaire(), Op_Diff_EF::ajouter_contribution_new(), Op_Dift_EF_Q1::ajouter_contribution_new(), Op_Conv_EF::ajouter_contribution_sous_cond(), Op_Diff_EF::ajouter_contributions_bords(), Op_Dift_EF_Q1::ajouter_contributions_bords(), Operateur_Conv_sensibility_VEF::ajouter_conv_term(), Op_Grad_VEF_P1B_Face::ajouter_elem(), Source_Transport_VDF_Elem_base::ajouter_keps(), Source_Transport_VEF_Face_base::ajouter_keps(), Masse_PolyMAC_Elem::ajouter_masse(), Masse_PolyMAC_Face::ajouter_masse(), Solveur_Masse_base::ajouter_masse(), Solveur_Masse_base::ajouter_masse_dt_local(), Op_Diff_EF::ajouter_new(), Op_Dift_EF_Q1::ajouter_new(), Op_Grad_VEF_P1B_Face::ajouter_som(), Op_Conv_EF::ajouter_sous_cond(), Terme_Source_Constituant_Vortex_VEF_Face::ajouter_terme_div_u(), Op_Diff_PolyMAC_Elem::ajouter_termes_croises(), Op_Conv_ALE_VEF::ajouterALE(), Solveur_Masse_base::appliquer(), Masse_DG_base::appliquer_coef(), Masse_PolyMAC_base::appliquer_coef(), Masse_DG_Elem::appliquer_impl(), Solveur_Masse_EF::appliquer_impl(), Masse_PolyMAC_Elem::appliquer_impl(), Masse_PolyMAC_Face::appliquer_impl(), Masse_PolyMAC_P0_Face::appliquer_impl(), Masse_PolyMAC_P0P1NC_Face::appliquer_impl(), Masse_VDF_Elem::appliquer_impl(), Masse_VDF_Face::appliquer_impl(), Masse_VEF_P1NC::appliquer_impl(), Op_Grad_EF::associer(), Op_Grad_PolyMAC_Face::associer(), Op_Diff_VEFP1NCP1B_Face::associer(), Op_Conv_VDF_base::associer_champ_convecte_elem(), Op_Conv_VDF_base::associer_champ_convecte_face(), Terme_Source_Th_TdivU_VEF_Face::associer_eqn_t(), Champ_front_contact_VEF::associer_front_vf_et_ch_front_autre_pb(), Source_Transport_Bas_Reynolds_VDF_Elem_base::associer_pb(), Source_Transport_Eps_Realisable_VDF_Elem::associer_pb(), Source_Transport_K_Realisable_VDF_Elem::associer_pb(), Source_Transport_K_Eps_Realisable_VDF_Elem::associer_pb(), Source_Transport_Fluctuation_Temperature_VDF_Elem::associer_pb(), Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::associer_pb(), Source_Transport_Fluctuation_Temperature_W_VDF_Elem::associer_pb(), Source_Transport_Flux_Chaleur_Turbulente_VDF_Face::associer_pb(), Source_Transport_Eps_Realisable_VEF_Face::associer_pb(), Source_Transport_K_Realisable_VEF_Face::associer_pb(), Source_Transport_K_Eps_Bas_Reynolds_VEF_Face::associer_pb(), Source_Transport_K_Eps_Realisable_VEF_Face::associer_pb(), Source_PDF_EF::associer_pb(), Perte_Charge_Gen::associer_pb(), Source_Echange_Th_VDF::associer_pb(), Perte_Charge_VEF::associer_pb(), Source_Transport_Eps_VDF_Elem::associer_pb(), Source_Transport_K_VDF_Elem::associer_pb(), Source_Transport_K_Eps_VDF_Elem::associer_pb(), Source_Transport_K_Omega_VDF_Elem::associer_pb(), Source_Transport_K_KEps_VDF_Elem::associer_pb(), Source_Transport_Eps_VEF_Face::associer_pb(), Source_Transport_K_VEF_Face::associer_pb(), Source_Transport_K_Eps_VEF_Face::associer_pb(), Source_Transport_K_Omega_VEF_Face::associer_pb(), Terme_Boussinesq_base::associer_pb(), Op_Evanescence_Homogene_PolyMAC_P0_Face::calc_grad_alpha_elem(), Op_Evanescence_Homogene_PolyMAC_P0_Face::calc_grad_alpha_faces(), Op_Evanescence_Homogene_VDF_Face::calc_grad_alpha_faces(), Op_Evanescence_Homogene_PolyMAC_P0_Face::calc_vort_elem(), Op_Evanescence_Homogene_Face_base::calc_vort_faces(), Champ_P1NC::calcul_critere_Q(), Modele_Jones_Launder_VDF::Calcul_D(), Modele_Jones_Launder_Thermique_VDF::Calcul_D(), Modele_Jones_Launder_VDF::Calcul_D_BiK(), Champ_P1NC::calcul_duidxj_paroi(), Champ_front_contact_VEF::calcul_grads_locaux(), Champ_P1NC::calcul_h_conv(), Segment_poly::calcul_vc(), Tetra_poly::calcul_vc(), Point_EF::calcul_vc(), Segment_EF::calcul_vc(), Tetra_EF::calcul_vc(), Tri_EF::calcul_vc(), Champ_Q1_EF::calcul_y_plus(), Champ_P1NC::calcul_y_plus(), Champ_Face_VDF::calcul_y_plus(), Champ_P1NC::calcul_y_plus_diphasique(), Champ_Face_VDF::calcul_y_plus_diphasique(), Op_Conv_ALE_VEF::calculateALEjacobian(), Op_Conv_ALE_VEF::calculateALEMeshVelocityGradientOnFaces(), Op_Diff_P1NC_barprim::calculer(), Source_PDF_base::calculer(), Terme_Source_Constituant_Vortex_VEF_Face::calculer(), Terme_Source_Canal_perio_VDF_Face::calculer_debit(), Terme_Source_Canal_perio_VEF_P1NC::calculer_debit(), Op_Conv_VDF_base::calculer_dt_local(), Op_Diff_DG_base::calculer_dt_stab(), Op_Conv_EF::calculer_dt_stab(), Op_Diff_EF_base::calculer_dt_stab(), Op_Dift_EF_Q1::calculer_dt_stab(), Op_Conv_PolyMAC_iterateur_base::calculer_dt_stab(), Op_Conv_EF_Stab_PolyMAC_P0_Face::calculer_dt_stab(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::calculer_dt_stab(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Face::calculer_dt_stab(), Op_Diff_PolyMAC_base::calculer_dt_stab(), Op_Diff_PolyMAC_P0_Elem::calculer_dt_stab(), Op_Diff_PolyMAC_P0_Face::calculer_dt_stab(), Op_Diff_PolyMAC_P0P1NC_Elem::calculer_dt_stab(), Op_Diff_PolyMAC_P0P1NC_Face::calculer_dt_stab(), Op_Conv_VDF_base::calculer_dt_stab(), Op_Diff_VDF_Elem_base::calculer_dt_stab(), Op_Dift_Multiphase_VDF_Elem::calculer_dt_stab(), Op_Dift_Multiphase_VDF_Face::calculer_dt_stab(), Op_Conv_Muscl_New_VEF_Face::calculer_dt_stab(), Op_Conv_VEF_base::calculer_dt_stab(), Op_Diff_VEF_base::calculer_dt_stab(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab(), Op_Dift_VEF_base::calculer_dt_stab(), Op_Diff_VDF_base::calculer_dt_stab_(), Op_Dift_VDF_Elem_base::calculer_dt_stab_elem(), Op_Grad_EF::calculer_flux_bords(), Op_Grad_VDF_Face::calculer_flux_bords(), Op_Grad_VEF_P1B_Face::calculer_flux_bords(), Op_Diff_VEFP1NCP1B_Face::calculer_gradient_som(), Echange_contact_Correlation_VDF::calculer_h_mon_pb(), Echange_contact_VDF::calculer_h_mon_pb(), Echange_contact_Correlation_VEF::calculer_h_solide(), Paroi_std_hyd_VDF_diphasique::calculer_hyd(), Paroi_std_hyd_VEF_diphasique::calculer_hyd(), Assembleur_P_VEF::calculer_inv_volume(), Domaine_EF::calculer_IPhi(), Domaine_EF_axi::calculer_IPhi(), Terme_Source_Acceleration::calculer_la_source(), Op_Diff_VEFP1NCP1B_Face::calculer_laplacien_som(), Operateur::calculer_pas_de_temps(), Operateur_base::calculer_pour_post(), Op_Conv_PolyMAC_iterateur_base::calculer_pour_post(), Op_Conv_VDF_base::calculer_pour_post(), Op_Conv_VEF_base::calculer_pour_post(), Source_Transport_Fluctuation_Temperature_VDF_Elem::calculer_Prod_uteta_T(), Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::calculer_Prod_uteta_T(), Source_Transport_Fluctuation_Temperature_W_VDF_Elem::calculer_Prod_uteta_T(), Echange_contact_Correlation_VDF::calculer_Q(), Neumann_paroi_rayo_semi_transp_VEF::calculer_temperature_bord(), Calcul_Production_K_VDF::calculer_terme_destruction_K(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_W_VDF_Elem::calculer_terme_destruction_K_W(), Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::calculer_terme_destruction_K_W(), Source_Transport_Fluctuation_Temperature_W_VDF_Elem::calculer_terme_destruction_K_W(), Echange_contact_ODVM_VDF::calculer_Teta_equiv(), Echange_contact_VDF::calculer_Teta_paroi(), Echange_contact_Rayo_transp_VDF::calculer_Teta_paroi(), Echange_contact_rayo_semi_transp_VDF::calculer_Teta_paroi(), Echange_contact_Correlation_VDF::calculer_Tfluide(), Echange_contact_Correlation_VEF::calculer_Tfluide(), Champ_base::calculer_valeurs_som_compo_post(), Champ_base::calculer_valeurs_som_post(), Source_PDF_EF::calculer_variable_imposee_elem_fluid(), Source_PDF_EF::calculer_variable_imposee_hybrid(), Source_PDF_EF::calculer_variable_imposee_mean_grad(), Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl(), Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl_u_star(), Domaine_EF::calculer_volumes_sommets(), Op_Conv_EF::coefficient_btd(), Op_Conv_BTD_EF::coefficient_btd(), Operateur_base::completer(), Source_base::completer(), Correction_Lubchenko_PolyMAC_P0::completer(), Cond_lim_omega_demi::completer(), Cond_lim_omega_dix::completer(), Diffusion_croisee_echelle_temp_taux_diss_turb_PolyMAC_P0::completer(), Source_Diffusion_supplementaire_echelle_temp_turb::completer(), Source_Dissipation_energie_cin_turb::completer(), Production_energie_cin_turb_VDF::completer(), Echange_contact_VDF_FT_Disc::completer(), Echange_contact_VDF_FT_Disc_solid::completer(), Source_Portance::completer(), Echange_contact_Rayo_transp_VDF::completer(), Source_rayo_semi_transp_QC_VDF_P0_VDF::completer(), Source_rayo_semi_transp_QC_VEF_P1NC::completer(), Op_Diff_K_Eps_Bas_Re_VDF_base::completer(), Op_Diff_K_Eps_Bas_Re_VDF_var_Elem::completer(), Op_Diff_K_Eps_VDF_base::completer(), Op_Diff_K_Omega_VDF_base::completer(), Op_Diff_K_Eps_VEF_base::completer(), Op_Diff_K_Omega_VEF_base::completer(), Source_Robin_Scalaire::completer(), Op_Diff_DG_base::completer(), Op_Diff_DG_Elem::completer(), Op_Conv_EF::completer(), Op_Conv_EF_base::completer(), Op_Diff_EF::completer(), Op_Dift_EF_base::completer(), Source_Generique_base::completer(), Correction_Antal_PolyMAC_P0::completer(), Correction_Tomiyama_PolyMAC_P0::completer(), Travail_pression_PolyMAC_P0P1NC::completer(), Op_Diff_PolyMAC_base::completer(), Op_Diff_PolyMAC_P0_base::completer(), Op_Diff_PolyMAC_P0P1NC_base::completer(), Op_Diff_PolyMAC_Elem::completer(), Op_Diff_PolyMAC_Face::completer(), Op_Diff_PolyMAC_P0_Elem::completer(), Op_Diff_PolyMAC_P0_Face::completer(), Op_Diff_PolyMAC_P0P1NC_Elem::completer(), Op_Diff_PolyMAC_P0P1NC_Face::completer(), Op_Grad_PolyMAC_P0_Face::completer(), Op_Grad_PolyMAC_P0P1NC_Face::completer(), Masse_PolyMAC_base::completer(), Masse_PolyMAC_P0_Face::completer(), Navier_Stokes_Fluide_Dilatable_base::completer(), Paroi_Knudsen_non_negligeable::completer(), Perte_Charge_Gen::completer(), Terme_Source_Canal_perio::completer(), QDM_Multiphase::completer(), Source_Flux_interfacial_base::completer(), Source_Frottement_interfacial_base::completer(), Source_Portance_interfaciale_base::completer(), Echange_contact_Correlation_VDF::completer(), Echange_contact_VDF::completer(), Echange_interne_impose::completer(), Sortie_libre_Gradient_Pression_impose::completer(), Sortie_libre_Pression_imposee_Orlansky::completer(), Correction_Antal_VDF::completer(), Travail_pression_VDF::completer(), Op_Diff_VDF_base::completer(), Op_Dift_VDF_Face_Axi_base::completer(), Op_Diff_VDF_Elem::completer(), Op_Diff_VDF_Elem_Axi::completer(), Op_Diff_VDF_Elem_aniso::completer(), Op_Diff_VDF_Multi_inco_Elem::completer(), Op_Diff_VDF_Multi_inco_Multi_scalar_Elem::completer(), Op_Diff_VDF_Multi_inco_Elem_Axi::completer(), Op_Diff_VDF_Face::completer(), Op_Dift_Multiphase_VDF_Elem::completer(), Op_Dift_Multiphase_VDF_Face::completer(), Op_Dift_VDF_Elem::completer(), Op_Dift_VDF_Elem_Axi::completer(), Op_Dift_VDF_Multi_inco_Elem::completer(), Op_Dift_VDF_Multi_inco_Elem_Axi::completer(), Op_Dift_VDF_Face::completer(), Op_Div_VDF_base::completer(), Force_Centrifuge_VDF_Face_Axi::completer(), Terme_Source_Constituant_VDF_Elem::completer(), Echange_contact_Correlation_VEF::completer(), Sortie_libre_Gradient_Pression_libre_VEF::completer(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::completer(), Op_Conv_EF_VEF_P1NC_Stab::completer(), Op_Dift_VEF_base::completer(), Perte_Charge_VEF::completer(), Terme_Source_Rappel_T_VEF_Face::completer(), Source_PDF_EF::compute_coeff_elem(), Source_PDF_EF::compute_coeff_matrice(), Terme_Source_Canal_perio::compute_heat_flux(), Source_PDF_EF::compute_pond(), Source_PDF_EF::compute_variable_imposee_projete(), Domaine_ALE::computeFluidForceOnBeam(), Op_Conv_EF::contribue_au_second_membre(), Op_Dift_VDF_Face_Axi_base::contribue_au_second_membre(), Op_Conv_EF::contribue_au_second_membre_a_la_diffusion(), Operateur_base::contribuer_a_avec(), Source_base::contribuer_a_avec(), Op_Diff_K_Eps_VEF_Face::contribuer_a_avec(), Op_Diff_K_Omega_VEF_Face::contribuer_a_avec(), Source_Transport_K_Eps_VEF_Face::contribuer_a_avec(), Source_Transport_K_Omega_VEF_Face::contribuer_a_avec(), Source_PDF_EF::contribuer_a_avec(), Operateur_Grad_base::contribuer_a_avec(), Op_Conv_EF_Stab_PolyMAC_Face::contribuer_a_avec(), Op_Diff_PolyMAC_Elem::contribuer_a_avec(), Op_Diff_PolyMAC_Face::contribuer_a_avec(), Perte_Charge_PolyMAC::contribuer_a_avec(), Perte_Charge_Singuliere_PolyMAC_Face::contribuer_a_avec(), Op_Diff_VEF_Anisotrope_Face::contribuer_a_avec(), Op_Diff_VEF_Face::contribuer_a_avec(), Op_Diff_VEF_Face_Stab::contribuer_a_avec(), Op_Dift_Stab_VEF_Face::contribuer_a_avec(), Op_Dift_VEF_Face::contribuer_a_avec(), Op_Dift_VEF_Face_Q1::contribuer_a_avec(), Perte_Charge_Reguliere_VEF_P1NC::contribuer_a_avec(), Perte_Charge_Singuliere_VEF_Face::contribuer_a_avec(), Perte_Charge_VEF::contribuer_a_avec(), Terme_Source_Decroissance_Radioactive_VEF_Face::contribuer_a_avec(), Op_Div_PolyMAC::contribuer_a_avec(), Op_Div_PolyMAC_P0::contribuer_a_avec(), Op_Diff_EF::contribuer_au_second_membre(), Op_Dift_EF_Q1::contribuer_au_second_membre(), Op_Diff_DG_Elem::contribuer_au_second_membre(), Op_Dift_VEF_Face::contribuer_au_second_membre(), Operateur_base::contribuer_termes_croises(), Op_Diff_PolyMAC_Elem::contribuer_termes_croises(), Transport_K_Eps_base::controler_K_Eps(), Transport_K_Omega_base::controler_K_Omega(), Transport_K_ou_Eps_base::controler_variable(), Masse_VDF_Face::corriger_solution(), Solveur_Masse_base::corriger_solution(), Masse_PolyMAC_P0_Face::corriger_solution(), Masse_PolyMAC_P0P1NC_Face::corriger_solution(), Source_Transport_K_Omega_VEF_Face::creer_champ(), Op_Conv_VDF_base::creer_champ(), Source_PDF_EF::creer_champ(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::creer_champ(), Source_Portance_interfaciale_base::creer_champ(), Source_Flux_interfacial_base::da_qpi(), Op_Div_VEFP1B_Elem::degres_liberte(), Source_Action_Particules::delta_v(), Convection_Diffusion_Fluide_Dilatable_Proto::derivee_en_temps_inco_sans_solveur_masse_impl(), Source_Action_Particules::diametre_particules(), Op_EF_base::dimensionner(), Op_PolyMAC_Elem::dimensionner(), Op_VDF_Face::dimensionner(), Op_VEF_Face::dimensionner(), Operateur_base::dimensionner(), Source_base::dimensionner(), Op_Conv_EF_Stab_PolyMAC_Face::dimensionner(), Op_Diff_PolyMAC_Elem::dimensionner(), Op_Diff_PolyMAC_Face::dimensionner(), Op_Div_PolyMAC_P0::dimensionner(), Solveur_Masse_base::dimensionner(), Masse_PolyMAC_Elem::dimensionner(), Masse_PolyMAC_Face::dimensionner(), Op_Diff_K_Eps_Bas_Re_VDF_base::dimensionner_blocs(), Op_Diff_K_Eps_VDF_base::dimensionner_blocs(), Op_Diff_K_Omega_VDF_base::dimensionner_blocs(), Source_Transport_Eps_VDF_Elem::dimensionner_blocs(), Masse_DG_base::dimensionner_blocs(), Masse_PolyMAC_P0_Face::dimensionner_blocs(), Op_Diff_VDF_Elem_base::dimensionner_blocs(), Op_Diff_VDF_Face_base::dimensionner_blocs(), Op_Dift_VDF_Elem_base::dimensionner_blocs(), Op_Dift_VDF_Face_base::dimensionner_blocs(), Op_Grad_VDF_Face::dimensionner_blocs(), Masse_VDF_base::dimensionner_blocs(), Masse_VDF_Face::dimensionner_blocs(), Perte_Charge_Singuliere_VDF_Face::dimensionner_blocs(), Op_Conv_EF_Stab_PolyMAC_P0_Face::dimensionner_blocs(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Face::dimensionner_blocs(), Op_Diff_PolyMAC_P0_Face::dimensionner_blocs(), Op_Div_PolyMAC_P0P1NC::dimensionner_blocs(), Op_Grad_PolyMAC_P0_Face::dimensionner_blocs(), Op_Grad_PolyMAC_P0P1NC_Face::dimensionner_blocs(), Coalescence_bulles_1groupe_PolyMAC_P0::dimensionner_blocs(), Coalescence_bulles_2groupes_PolyMAC_P0::dimensionner_blocs(), Flux_2groupes_PolyMAC_P0::dimensionner_blocs(), Rupture_bulles_1groupe_PolyMAC_P0::dimensionner_blocs(), Rupture_bulles_2groupes_PolyMAC_P0::dimensionner_blocs(), Variation_rho::dimensionner_blocs(), Diffusion_supplementaire_echelle_temp_turb_PolyMAC_P0::dimensionner_blocs(), Source_Diffusion_supplementaire_echelle_temp_turb::dimensionner_blocs(), Source_Dissipation_energie_cin_turb::dimensionner_blocs(), Source_Production_echelle_temp_taux_diss_turb::dimensionner_blocs(), Source_Production_energie_cin_turb::dimensionner_blocs(), Op_Diff_DG_Elem::dimensionner_blocs(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::dimensionner_blocs(), Op_Diff_PolyMAC_P0_Elem::dimensionner_blocs(), Perte_Charge_Singuliere_PolyMAC_P0P1NC_Face::dimensionner_blocs(), Terme_Source_Decroissance_Radioactive_Elem_PolyMAC::dimensionner_blocs(), Op_Evanescence_Homogene_Elem_base::dimensionner_blocs(), Op_Evanescence_Homogene_Face_base::dimensionner_blocs(), Source_Flux_interfacial_base::dimensionner_blocs(), Source_Force_Tchen_base::dimensionner_blocs(), Source_Frottement_interfacial_base::dimensionner_blocs(), Source_Travail_pression_Elem_base::dimensionner_blocs(), DP_Impose_VEF_Face::dimensionner_blocs(), Op_Conv_Amont_VDF_Face::dimensionner_blocs(), Dispersion_bulles_PolyMAC_P0::dimensionner_blocs_aux(), Force_Tchen_PolyMAC_P0::dimensionner_blocs_aux(), Frottement_interfacial_PolyMAC_P0::dimensionner_blocs_aux(), Op_Evanescence_Homogene_PolyMAC_P0_Face::dimensionner_blocs_aux(), Op_Conv_VDF_base::dimensionner_blocs_elem(), Op_Diff_PolyMAC_P0P1NC_Elem::dimensionner_blocs_ext(), Op_Diff_PolyMAC_P0P1NC_Face::dimensionner_blocs_ext(), Op_Conv_VDF_base::dimensionner_blocs_face(), Operateur_base::dimensionner_termes_croises(), Op_Diff_PolyMAC_Elem::dimensionner_termes_croises(), Op_Diff_VDF_Elem_base::dimensionner_termes_croises(), Champ_Inc_base::domaine_Cl_dis(), Domaine_Cl_dis_base::domaine_dis(), Source_Flux_interfacial_base::dp_qpi(), Source_Flux_interfacial_base::dT_qpi(), Champ_front_calc::equation(), Champ_front_contact_VEF::equation(), Champ_val_tot_sur_vol_VDF::eval_contrib_loc(), Champ_val_tot_sur_vol_VEF::eval_contrib_loc(), Champ_P1NC_implementation::filtrer_L2(), Champ_P1NC_implementation::filtrer_resu(), Sortie_libre_Gradient_Pression_libre_VEF::flux_impose(), Source_PDF_base::fonct_coeff(), Source_PDF_EF::get_champ(), Champ_Generique_Extraction::get_champ(), Champ_Generique_Gradient::get_champ(), Terme_Source_Acceleration::get_eq_hydraulique(), Operateur_base::get_localisation_pour_post(), Solveur_Masse_base::get_masse_divide_by_local_dt(), Solveur_Masse_base::get_masse_dt_local(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::get_noms_champs_postraitables(), Op_Conv_VDF_base::get_noms_champs_postraitables(), Champ_Inc_base::get_PDI_dname(), Source_Action_Particules::grad_pression(), Champ_Q1_EF::gradient(), Champ_Q1NC::gradient(), Champ_P1NC::gradient(), Domaine_Cl_VEF::imposer_cond_lim(), Domaine_Cl_EF::imposer_symetrie_matrice_secmem(), Source_PDF_EF::impr(), Op_Grad_VEF_P1B_Face::impr(), Op_EF_base::impr(), Op_VEF_Face::impr(), Source_base::impr(), Op_Div_EF::impr(), Op_Grad_EF::impr(), Op_Div_PolyMAC::impr(), Op_Grad_VDF_Face::impr(), Op_Div_VEFP1B_Elem::impr(), Echange_contact_PolyMAC_P0::init_op(), Echange_contact_PolyMAC_P0P1NC::init_op(), Couplage_Parietal_PolyMAC_helper::init_op_ext(), Op_Diff_PolyMAC_P0P1NC_Elem::init_op_ext(), Champ_Face_PolyMAC::init_va(), Champ_Face_PolyMAC_P0::init_ve2(), Op_Diff_VEFP1NCP1B_Face::initialiser(), Paroi_frottante_simple::initialiser(), Terme_Puissance_Thermique_DG_base::initialiser(), Terme_Puissance_Thermique_PolyMAC_base::initialiser(), Terme_Source_Qdm_Face_PolyMAC_P0P1NC::initialiser(), Terme_Puissance_Thermique_Echange_Impose_Elem_base::initialiser(), Echange_global_impose_turbulent::initialiser(), Echange_couplage_thermique::initialiser(), Terme_Puissance_Thermique_VDF_base::initialiser(), Terme_Source_Qdm_VDF_Face::initialiser(), Sortie_libre_Gradient_Pression_impose_VEFPreP1B::initialiser(), Sortie_libre_Gradient_Pression_libre_VEF::initialiser(), Terme_Puissance_Thermique_VEF_base::initialiser(), Terme_Puissance_Thermique_Echange_Impose_VEF_Face::initialiser(), Boundary_field_keps_from_ud::initialiser(), Champ_Front_Fonction::initialiser(), Champ_front_pression_from_u::initialiser(), Champ_front_debit_massique::initialiser_coefficient(), Champ_Face_PolyMAC::interp_ve(), Champ_Face_PolyMAC_P0P1NC::interp_ve(), Echange_contact_Correlation_VDF::limpr(), Echange_contact_Correlation_VEF::limpr(), Operateur::lire(), Terme_Source_Acceleration::lire_data(), Terme_Source_Canal_perio::lire_motcle_non_standard(), Paroi_frottante_simple::me_calculer(), Champ_Fonc_Elem_PolyMAC_P0_TC::me_calculer(), T_paroi_Champ_P1NC::me_calculer(), Y_plus_Champ_Face::me_calculer(), Y_plus_Champ_P1NC::me_calculer(), Champ_Fonc_Elem_PolyMAC_P0_rot::me_calculer_2D(), Champ_Fonc_Elem_PolyMAC_P0_rot::me_calculer_3D(), Frontiere_ouverte_vitesse_vortex::mettre_a_jour(), Echange_contact_rayo_semi_transp_VDF::mettre_a_jour(), Op_Dift_EF_base::mettre_a_jour(), Portance_interfaciale_PolyMAC_P0::mettre_a_jour(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::mettre_a_jour(), DP_Impose_PolyMAC_Face::mettre_a_jour(), Perte_Charge_Singuliere_PolyMAC_Face::mettre_a_jour(), Champ_front_pression_from_u::mettre_a_jour(), Perte_Charge_Singuliere_VDF_Face::mettre_a_jour(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::mettre_a_jour(), Op_Dift_VEF_base::mettre_a_jour(), DP_Impose_VEF_Face::mettre_a_jour(), Perte_Charge_Singuliere_VEF_Face::mettre_a_jour(), Echange_contact_VDF_FT_Disc_solid::mettre_a_jour(), Echange_contact_Rayo_transp_VDF::mettre_a_jour(), Echange_contact_Correlation_VDF::mettre_a_jour(), Op_Conv_VDF_base::mettre_a_jour(), Op_Dift_Multiphase_VDF_Elem::mettre_a_jour(), Terme_Source_Canal_RANS_LES_VDF_Face::mettre_a_jour(), Echange_contact_Correlation_VEF::mettre_a_jour(), Op_EF_base::modifier_flux(), Op_VEF_Face::modifier_flux(), Op_Diff_Turbulent_PolyMAC_P0_Elem::modifier_mu(), Op_Diff_Turbulent_PolyMAC_P0_Face::modifier_mu(), Op_EF_base::modifier_pour_Cl(), Op_VDF_Face::modifier_pour_Cl(), Op_VEF_Face::modifier_pour_Cl(), Operateur_base::modifier_pour_Cl(), Op_Diff_K_Eps_VDF_base::modifier_pour_Cl(), Op_Diff_K_Omega_VDF_base::modifier_pour_Cl(), Op_Diff_K_Eps_VEF_Face::modifier_pour_Cl(), Op_Diff_K_Omega_VEF_Face::modifier_pour_Cl(), Assembleur_P_VEFPreP1B::modifier_secmem(), Champ_P1NC::norme_L2_H1(), Source_PDF_base::ouvrir_fichier(), Operateur_base::ouvrir_fichier(), Source_base::ouvrir_fichier(), Terme_Source_Constituant_VDF_Elem::ouvrir_fichier(), Operateur_base::ouvrir_fichier_partage(), Terme_Puissance_Thermique_Echange_Impose_Elem_base::pid_process(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::preparer_calcul(), Op_Evanescence_Homogene_VDF_Face::preparer_calcul(), Op_Conv_VDF_base::preparer_calcul(), Masse_VDF_Elem::preparer_calcul(), Source_Flux_interfacial_base::qpi(), Op_Conv_ALE_VEF::readOn(), Coalescence_bulles_1groupe_PolyMAC_P0::readOn(), Coalescence_bulles_2groupes_PolyMAC_P0::readOn(), Correction_Lubchenko_PolyMAC_P0::readOn(), Flux_2groupes_PolyMAC_P0::readOn(), Nucleation_paroi_PolyMAC_P0::readOn(), Rupture_bulles_1groupe_PolyMAC_P0::readOn(), Rupture_bulles_2groupes_PolyMAC_P0::readOn(), Source_injection_masse_base::readOn(), Dissipation_WIT_PolyMAC_P0::readOn(), Production_HZDR_PolyMAC_P0::readOn(), Production_WIT_PolyMAC_P0::readOn(), Source_BIF_PolyMAC_P0::readOn(), Source_Dissipation_HZDR_PolyMAC_P0::readOn(), Source_Production_echelle_temp_taux_diss_turb::readOn(), Source_Production_energie_cin_turb::readOn(), Terme_Source_Constituant_Vortex_VEF_Face::readOn(), Operateur_Conv_sensibility_VEF::readOn(), Terme_Puissance_Thermique_DG_base::readOn(), Source_Scalaire_EF::readOn(), Puissance_Thermique_EF::readOn(), Puissance_Thermique_QC_EF::readOn(), Domaine_Cl_dis_base::readOn(), Source_PDF_base::readOn(), Correction_Antal_PolyMAC_P0::readOn(), Correction_Tomiyama_PolyMAC_P0::readOn(), Dispersion_bulles_PolyMAC_P0::readOn(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::readOn(), Op_Diff_Turbulent_PolyMAC_P0_Elem::readOn(), Op_Diff_Turbulent_PolyMAC_P0_Face::readOn(), Terme_Puissance_Thermique_PolyMAC_base::readOn(), Terme_Source_Decroissance_Radioactive_Elem_PolyMAC::readOn(), Terme_Source_Qdm_Face_PolyMAC::readOn(), Op_Evanescence_Homogene_Face_base::readOn(), Source_Dispersion_bulles_base::readOn(), Source_Flux_interfacial_base::readOn(), Source_Force_Tchen_base::readOn(), Source_Frottement_interfacial_base::readOn(), Source_Portance_interfaciale_base::readOn(), Correction_Antal_VDF::readOn(), Dispersion_bulles_VDF::readOn(), Op_Conv_VDF_base::readOn(), Op_Dift_Multiphase_VDF_Elem::readOn(), Op_Dift_Multiphase_VDF_Face::readOn(), Terme_Puissance_Thermique_VDF_base::readOn(), Terme_Source_Qdm_VDF_Face::readOn(), Terme_Puissance_Thermique_VEF_base::readOn(), Terme_Source_Decroissance_Radioactive_VEF_Face::readOn(), Op_Conv_DI_L2_VEF_Face::reconst_DI_L2_2d(), Op_Conv_DI_L2_VEF_Face::reconst_DI_L2_3d(), Op_Conv_EF_base::remplir_fluent(), Op_Conv_VEF_base::remplir_fluent(), Op_Conv_VEF_Face::remplir_fluent(), Op_Conv_ALE_VEF::remplir_fluent_ALEincluded(), DP_Impose_PolyMAC_Face::remplir_num_faces(), Perte_Charge_Singuliere_PolyMAC_Face::remplir_num_faces(), Perte_Charge_Singuliere_VDF_Face::remplir_num_faces(), DP_Impose_VEF_Face::remplir_num_faces(), Perte_Charge_Singuliere_VEF_Face::remplir_num_faces(), Perte_Charge_Reguliere_VDF_Face::remplir_num_faces(), Perte_Charge_Reguliere_VEF_P1NC::remplir_num_faces(), Domaine_Cl_EF::remplir_type_elem_Cl(), Domaine_Cl_VEF::remplir_volumes_entrelaces_Cl(), Champ_Elem_PolyMAC_P0::reprendre(), Champ_Elem_PolyMAC_P0P1NC::reprendre(), Champ_Face_PolyMAC_P0::reprendre(), Champ_Face_PolyMAC_P0P1NC::reprendre(), Source_Action_Particules::rho_fluide(), Source_Action_Particules::rho_particules(), Source_PDF_EF::rotate_imposed_velocity(), Champ_Inc_base::sauvegarder(), EOS_Tools_VDF::secmembre_divU_Z(), EOS_Tools_VEF::secmembre_divU_Z(), Operateur_base::set_fichier(), Source_base::set_fichier(), Solveur_Masse_base::set_name_of_coefficient_temporel(), Terme_Source_Canal_perio::source(), Terme_Source_Canal_perio::source_convection_diffusion(), Terme_Source_Canal_perio_VDF_P0::source_convection_diffusion(), Op_Diff_VEFP1NCP1B_Face::test(), Op_Diff_Fluctu_Temp::typer(), Op_Diff_Flux_Chaleur_Turb::typer(), Operateur_Grad::typer(), Domaine_ALE::update_ALE_projection(), Op_Diff_PolyMAC_P0P1NC_base::update_aux(), Op_Diff_PolyMAC_Elem::update_delta(), Op_Diff_PolyMAC_Elem::update_delta_int(), Op_Grad_PolyMAC_P0_Face::update_grad(), Op_Diff_DG_base::update_nu(), Op_Diff_PolyMAC_base::update_nu(), Op_Diff_PolyMAC_P0_base::update_nu(), Op_Diff_PolyMAC_P0P1NC_base::update_nu(), Op_Diff_PolyMAC_P0_base::update_phif(), Champ_Face_PolyMAC_P0::update_ve(), Source_PDF_base::updateChampRho(), Echange_global_impose_rayo_semi_transp::verifie_ch_init_nb_comp(), Dirichlet::verifie_ch_init_nb_comp(), Echange_externe_impose::verifie_ch_init_nb_comp(), Neumann_paroi::verifie_ch_init_nb_comp(), Neumann_sortie_libre::verifie_ch_init_nb_comp(), Champ_P1NC::verifie_valeurs_cl(), Champ_Q1NC::verifie_valeurs_cl(), Op_Diff_VEF_Anisotrope_Face::verifier(), Op_Diff_VEF_Face::verifier(), Source_Action_Particules::visco_dyn_fluide(), Source_Action_Particules::vitesse_fluide(), Source_Action_Particules::vitesse_particules(), Source_Action_Particules::volumes_particules(), Terme_Source_Canal_perio::write_flow_rate(), and VDF_discretisation::y_plus().
equation() [2/2]
Equation_base & MorEqn::equation () inline
Renvoie la reference sur l'equation pointe par MorEqn::mon_equation.
Returns
(Equation_base&) l'equation associee a l'objet
References Process::exit(), mon_equation, TRUST_Ref< _CLASSE_ >::non_nul(), and TRUST_Ref< _CLASSE_ >::valeur().
mon_equation_non_nul()
int MorEqn::mon_equation_non_nul () const inline
References mon_equation, and TRUST_Ref< _CLASSE_ >::non_nul().
Referenced by Champ_base::calculer_valeurs_som_post(), Navier_Stokes_Aposteriori::get_champ(), Convection_Diffusion_Temperature::get_champ(), Navier_Stokes_std::get_champ(), Conduction::get_champ(), Champ_Inc_base::get_PDI_dname(), Champ_Face_PolyMAC::interp_ve(), Champ_Face_PolyMAC_P0P1NC::interp_ve(), Champ_Elem_PolyMAC_P0::reprendre(), Champ_Elem_PolyMAC_P0P1NC::reprendre(), Champ_Face_PolyMAC_P0::reprendre(), Champ_Face_PolyMAC_P0P1NC::reprendre(), and Champ_Face_PolyMAC_P0::update_ve().
check_multiphase_compatibility()
void MorEqn::check_multiphase_compatibility () const virtual
Reimplemented in Coalescence_bulles_1groupe_PolyMAC_P0, Coalescence_bulles_2groupes_PolyMAC_P0, Correction_Lubchenko_PolyMAC_P0, Flux_2groupes_PolyMAC_P0, Nucleation_paroi_PolyMAC_P0, Rupture_bulles_1groupe_PolyMAC_P0, Rupture_bulles_2groupes_PolyMAC_P0, Variation_rho, Source_injection_QDM_base, Dissipation_WIT_PolyMAC_P0, Production_HZDR_PolyMAC_P0, Production_WIT_PolyMAC_P0, Source_BIF_PolyMAC_P0, Source_Dissipation_HZDR_PolyMAC_P0, Sources, Op_Conv_negligeable, Op_Diff_negligeable, Correction_Antal_PolyMAC_P0, Correction_Tomiyama_PolyMAC_P0, Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem, Op_Conv_EF_Stab_PolyMAC_P0P1NC_Face, Op_Diff_PolyMAC_P0_Face, Op_Diff_PolyMAC_P0P1NC_Face, Op_Grad_PolyMAC_P0P1NC_Face, Masse_PolyMAC_P0P1NC_base, DP_Impose_PolyMAC_Face, Perte_Charge_Anisotrope_PolyMAC_P0P1NC_Face, Perte_Charge_Circulaire_PolyMAC_P0P1NC_Face, Perte_Charge_Directionnelle_PolyMAC_P0P1NC_Face, Perte_Charge_Isotrope_PolyMAC_P0P1NC_Face, Perte_Charge_Singuliere_PolyMAC_P0P1NC_Face, Terme_Boussinesq_PolyMAC_Face, Terme_Source_Qdm_Face_PolyMAC_P0P1NC, Sources_Multiphase_base, Correction_Antal_VDF, Op_Conv_Amont_VDF_Elem, Op_Conv_Amont_VDF_Face, Op_Diff_VDF_base, Op_Grad_VDF_Face_base, Masse_VDF_base, Perte_Charge_Singuliere_VDF_Face, Perte_Charge_VDF_base, and Terme_Source_Qdm_VDF_Face.
References Process::exit(), mon_equation, and Objet_U::que_suis_je().
Referenced by Sources::check_multiphase_compatibility(), Masse_Multiphase::completer(), and QDM_Multiphase::completer().
Member Data Documentation
mon_equation
TRUST_Ref< Equation_base *> MorEqn::mon_equation protected
Referenced by Op_Diff_K_Eps_QC_VEF_Face::ajouter(), Op_Conv_EF_VEF_P1NC::ajouter(), Terme_Source_Canal_RANS_LES_VEF_Face::ajouter(), Source_QC_Gravite_VEF::ajouter(), Source_WC_Gravite_VEF::ajouter(), Terme_Source_Rappel_T_VEF_Face::ajouter(), Source_QC_Chaleur::ajouter_(), Source_WC_Chaleur::ajouter_(), Terme_Source_Canal_RANS_LES_VDF_Elem::ajouter_blocs(), Terme_Source_Canal_RANS_LES_VDF_Face::ajouter_blocs(), Terme_Source_inc_VDF_Face::ajouter_blocs(), Source_Transport_VEF_Face_base::ajouter_keps(), Op_Diff_K_Omega_VDF_base::associer_diffusivite_turbulente(), Op_Diff_K_Eps_Bas_Re_VDF_base::associer_diffusivite_turbulente_impl(), associer_eqn(), Champ_Face_VDF::calcul_duidxj(), Champ_Face_VDF::calcul_S_barre_sans_contrib_paroi(), Op_Dift_EF_Q1::calculer_dt_stab(), Op_Dift_VEF_base::calculer_dt_stab(), Op_Dift_VDF_Elem_base::calculer_dt_stab_elem(), Terme_Source_Canal_RANS_LES_VDF_Face::calculer_integrale_temporelle(), check_multiphase_compatibility(), Operateur::completer(), Operateur_base::completer(), Op_Diff_K_Eps_VDF_base::completer(), Op_Diff_K_Omega_VDF_base::completer(), Op_Diff_K_Eps_VEF_base::completer(), Op_Conv_EF_Stab_PolyMAC_Face::completer(), DP_Impose_PolyMAC_Face::completer(), Perte_Charge_Singuliere_PolyMAC_P0P1NC_Face::completer(), Source_Chaleur_Fluide_Dilatable_base::completer(), Source_Gravite_Fluide_Dilatable_base::completer(), Perte_Charge_Singuliere_VDF_Face::completer(), Source_Transport_K_Omega_VEF_Face::compute_cross_diffusion(), Source_WC_Chaleur_VDF::compute_interpolate_gradP(), Source_WC_Chaleur_VEF::compute_interpolate_gradP(), Source_WC_Chaleur::correct_grad_boundary(), Operateur::discretisation(), Terme_Source_Canal_RANS_LES_VDF_Face::ecriture_moy_spat(), Terme_Source_Canal_RANS_LES_VDF_Face::ecriture_moy_temp(), equation(), Terme_Source_Canal_RANS_LES_VDF_Elem::init(), Terme_Source_Canal_RANS_LES_VDF_Face::init(), Terme_Source_Canal_RANS_LES_VEF_Face::init(), Terme_Source_Canal_RANS_LES_VDF_Face::init_calcul_moyenne_spat(), Champ_Inc_P0_base::init_fcl(), Operateur::limpr(), Source_Neutronique::limpr(), Terme_Source_Canal_RANS_LES_VDF_Elem::mettre_a_jour(), Terme_Source_Canal_RANS_LES_VDF_Face::mettre_a_jour(), Terme_Source_Canal_RANS_LES_VEF_Face::mettre_a_jour(), Op_Diff_K_Eps_VDF_base::mettre_a_jour_diffusivite(), Op_Diff_K_Omega_VDF_base::mettre_a_jour_diffusivite(), Op_Diff_K_Eps_VDF_base::modifier_pour_Cl(), Op_Diff_K_Omega_VDF_base::modifier_pour_Cl(), mon_equation_non_nul(), Source_Transport_Eps_aniso_therm_concen_VDF_Elem::readOn(), Source_Transport_Eps_anisotherme_VDF_Elem::readOn(), Source_Transport_Eps_concen_VDF_Elem::readOn(), Source_Transport_Eps_VDF_Elem::readOn(), Source_Transport_K_aniso_therm_concen_VDF_Elem::readOn(), Source_Transport_K_anisotherme_VDF_Elem::readOn(), Source_Transport_K_concen_VDF_Elem::readOn(), Source_Transport_K_VDF_Elem::readOn(), Source_Transport_K_Eps_aniso_therm_concen_VDF_Elem::readOn(), Source_Transport_K_Eps_anisotherme_VDF_Elem::readOn(), Source_Transport_K_Eps_concen_VDF_Elem::readOn(), Source_Transport_K_Eps_VDF_Elem::readOn(), Source_Transport_K_Omega_VDF_Elem::readOn(), Source_Transport_Eps_aniso_concen_VEF_Face::readOn(), Source_Transport_Eps_aniso_therm_concen_VEF_Face::readOn(), Source_Transport_Eps_anisotherme_VEF_Face::readOn(), Source_Transport_Eps_VEF_Face::readOn(), Source_Transport_K_aniso_concen_VEF_Face::readOn(), Source_Transport_K_aniso_therm_concen_VEF_Face::readOn(), Source_Transport_K_anisotherme_VEF_Face::readOn(), Source_Transport_K_VEF_Face::readOn(), Source_Transport_K_Eps_aniso_concen_VEF_Face::readOn(), Source_Transport_K_Eps_aniso_therm_concen_VEF_Face::readOn(), Source_Transport_K_Eps_anisotherme_VEF_Face::readOn(), Source_Transport_K_Eps_VEF_Face::readOn(), Source_Transport_K_Omega_VEF_Face::readOn(), Domaine_Cl_dis_base::readOn(), Sources::readOn(), Operateur_Conv::readOn(), Source_QC_QDM_Gen::readOn_spec(), Operateur_base::tester_contribuer_a_avec(), Operateur_Conv::typer(), Operateur_Diff::typer(), Operateur_Div::typer(), and Operateur_Evanescence::typer().