TrioCFD: Sondes Class Reference
Sondes Class Reference
#include <Sondes.h>
Public Member Functions
const Type_info * get_info () const override
void mettre_a_jour (double temps, double tinit)
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from TRUST_List< TRUST_Deriv< Sonde > >
Sortie & printOn (Sortie &os) const override
Entree & readOn (Entree &is) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
See also
Sonde Postraitement
Constructor & Destructor Documentation
Sondes()
Sondes::Sondes ()
~Sondes()
Sondes::~Sondes ()
Member Function Documentation
cree_instance()
Objet_U * Sondes::cree_instance () static
taille_memoire()
unsigned Sondes::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Sondes::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Sondes::info () static
get_info()
const Type_info * Sondes::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
Sondes & Sondes::self_cast (Objet_U & r) static
self_cast() [2/2]
const Sondes & Sondes::self_cast (const Objet_U & r) static
printOn()
Sortie & Sondes::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
readOn()
Entree & Sondes::readOn (Entree & s) override protected virtual
Lit une liste de sondes a partir d'un flot d'entree Format:
{ [LIRE UNE SONDE AUTANT DE FOIS QUE NECESSAIRE] }
Parameters
(Entree& s) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Exceptions
accolade ouvrante attendue
Reimplemented from Objet_U.
References TRUST_List< TRUST_Deriv< Sonde > >::add(), Process::exit(), TRUST_Ref< _CLASSE_ >::non_nul(), Objet_U::que_suis_je(), set_noms_champs_postraitables(), and TRUST_Ref< _CLASSE_ >::valeur().
ouvrir_fichiers()
void Sondes::ouvrir_fichiers () inline
Ouvre tous les fichiers associes a chacune des sondes de la liste.
fermer_fichiers()
void Sondes::fermer_fichiers () inline
Ferme tous les fichiers des sondes de la liste.
Referenced by Postraitement::finir().
completer()
void Sondes::completer ()
References set_noms_champs_postraitables().
Referenced by Postraitement::completer_sondes(), and Postraitement::readOn().
init_bords()
void Sondes::init_bords () inline
Referenced by Postraitement::completer().
associer_post()
void Sondes::associer_post (const Postraitement & post)
Associe un postraitement a la liste des sondes.
Referenced by Postraitement::lire_motcle_non_standard().
postraiter()
void Sondes::postraiter ()
Effectue le postraitement sur chacune des sondes de la liste.
References clear_cache().
Referenced by Postraitement::postraiter_sondes().
mettre_a_jour()
void Sondes::mettre_a_jour (double temps, double tinit)
Effectue une mise a jour en temps de chacune des sondes de la liste.
Parameters
(double temps) le temps de mise a jour
(double tinit) le temps initial des sondes
References clear_cache().
Referenced by Postprocessing_IJK::postraiter(), and Postraitement::traiter_sondes().
get_from_cache()
TRUST_Ref< Champ_base * > Sondes::get_from_cache (TRUST_Ref< Champ_Generique_base * > & mon_champ, const Nom & nom_champ_lu_)
References TRUST_Vector< _CLASSE_ >::add(), TRUST_List< _CLASSE_ >::add(), TRUST_List< _CLASSE_ >::dernier(), Champ_Generique_base::fixer_identifiant_appel(), Champ_Generique_base::get_champ(), Objet_U_ptr::non_nul(), Noms::rang(), and TRUST_Deriv< _CLASSE_ >::valeur().
clear_cache()
void Sondes::clear_cache ()
References TRUST_Vector< _CLASSE_ >::reset(), and TRUST_List< _CLASSE_ >::vide().
Referenced by mettre_a_jour(), and postraiter().
set_noms_champs_postraitables()
void Sondes::set_noms_champs_postraitables ()
References TRUST_Vector< _CLASSE_ >::dimensionner_force(), TRUST_Ref< _CLASSE_ >::non_nul(), and TRUST_Vector< _CLASSE_ >::size().
Referenced by completer(), and readOn().
get_noms_champs_postraitables()
const Motcles & Sondes::get_noms_champs_postraitables () const inline
set_update_positions()
void Sondes::set_update_positions (bool update_positions)
Modifie le parametrage des sondes mobiles.
References update_positions.
Referenced by Postraitement::lire_motcle_non_standard().
get_update_positions()
bool Sondes::get_update_positions ()
Renvoie le parametrage des sondes mobiles.
References update_positions.
resetTime()
void Sondes::resetTime (double time) inline
Referenced by Postraitement::resetTime().
Member Data Documentation
info_obj
const Type_info Sondes::info_obj static
update_positions
bool Sondes::update_positions =false
Referenced by get_update_positions(), and set_update_positions().