TrioCFD: TRUSTTabFT_cut_cell_vector2< _TYPE_ > Class Template Reference
TRUSTTabFT_cut_cell_vector2< _TYPE_ > Class Template Reference
#include <TRUSTTabFT_cut_cell.h>
Additional Inherited Members
Public Member Functions inherited from TRUSTTab< _TYPE_ >
void ref_data (_TYPE_ *ptr, _SIZE_ size) override
void reset () override
Public Member Functions inherited from TRUSTVect< _TYPE_, _SIZE_ >
void ref_data (_TYPE_ *ptr, _SIZE_ new_size) override
TRUSTVect (_SIZE_ n)
TRUSTVect (const TRUSTVect &v)
Public Member Functions inherited from TRUSTArray< _TYPE_, _SIZE_ >
void append_array (_TYPE_ valeur)
void from_tid_to_int (TRUSTArray< int, int > &out) const
TRUSTArray & inject_array (const TRUSTArray &source, _SIZE_ nb_elements=-1, _SIZE_ first_element_dest=0, _SIZE_ first_element_source=0)
TRUSTArray & operator*= (const _TYPE_ dy)
TRUSTArray & operator+= (const _TYPE_ dy)
TRUSTArray & operator+= (const TRUSTArray &y)
TRUSTArray & operator-= (const _TYPE_ dy)
TRUSTArray & operator-= (const TRUSTArray &y)
TRUSTArray & operator/= (const _TYPE_ dy)
TRUSTArray & operator= (_TYPE_ x)
void ref_as_small (TRUSTArray< float, int > &out) const
int ref_count () const
virtual void ref_data (_TYPE_ *ptr, _SIZE_ size)
virtual void reset ()
void set_mem_storage (const STORAGE storage)
_SIZE_ size_array () const
TRUSTArray (const TRUSTArray &A)
Public Member Functions inherited from Array_base
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Sortie & printOn (Sortie &os) const override
Entree & readOn (Entree &is) override
Protected Member Functions inherited from TRUSTArray< _TYPE_, _SIZE_ >
Sortie & printOn (Sortie &os) const override
Entree & readOn (Entree &is) override
void resize_array_ (_SIZE_ n, RESIZE_OPTIONS opt=RESIZE_OPTIONS::COPY_INIT)
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Member Function Documentation
associer_persistant()
template<typename _TYPE_ > void TRUSTTabFT_cut_cell_vector2< _TYPE_ >::associer_persistant (Cut_cell_FT_Disc & cut_cell_disc) inline
References TRUSTTabFT_cut_cell< _TYPE_ >::associer_persistant().
associer_ephemere()
template<typename _TYPE_ > void TRUSTTabFT_cut_cell_vector2< _TYPE_ >::associer_ephemere (Cut_cell_FT_Disc & cut_cell_disc) inline
References TRUSTTabFT_cut_cell< _TYPE_ >::associer_ephemere().
associer_paresseux()
template<typename _TYPE_ > void TRUSTTabFT_cut_cell_vector2< _TYPE_ >::associer_paresseux (Cut_cell_FT_Disc & cut_cell_disc) inline
References TRUSTTabFT_cut_cell< _TYPE_ >::associer_paresseux().
Referenced by Cut_cell_FT_Disc::Cut_cell_FT_Disc().