TrioCFD: Flux_parietal_base Class Reference
Flux_parietal_base Class Reference abstract
#include <Flux_parietal_base.h>
Classes
struct input_t
struct output_t
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
   flux de chaleur sensible : q_{p}(k)     = F(alpha_f, p, T_f, T_p, v_f, D_h, D_ch)
   flux de chaleur latente  : q_{pi}(k, l) = F(alpha_f, p, T_f, T_p, v_f, D_h, D_ch)
     (par ex ebullition nucleee : Gamma_{kl} = q_{pi}(k, l) / Lvap)
 cette classe definit deux fonctions q_pk, q_pi
Constructor & Destructor Documentation
Flux_parietal_base()
Flux_parietal_base::Flux_parietal_base ()
~Flux_parietal_base()
Flux_parietal_base::~Flux_parietal_base () override
Member Function Documentation
info()
const Type_info * Flux_parietal_base::info () static
get_info()
const Type_info * Flux_parietal_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Correlation_base.
Reimplemented in Flux_parietal_Hibiki, Flux_parietal_Kommajosyula, Flux_parietal_Kurul_Podowski, Flux_parietal_adaptatif, Flux_parietal_diphasique_simple_lineaire, and Flux_parietal_Nusselt.
self_cast() [1/2]
Flux_parietal_base & Flux_parietal_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Flux_parietal_base & Flux_parietal_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Flux_parietal_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Correlation_base.
Reimplemented in Flux_parietal_Hibiki, Flux_parietal_Kommajosyula, Flux_parietal_Kurul_Podowski, Flux_parietal_adaptatif, Flux_parietal_diphasique_simple_lineaire, and Flux_parietal_Nusselt.
Referenced by Flux_parietal_Hibiki::printOn(), Flux_parietal_Kommajosyula::printOn(), Flux_parietal_Kurul_Podowski::printOn(), and Flux_parietal_adaptatif::printOn().
readOn()
Entree & Flux_parietal_base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Correlation_base.
Reimplemented in Flux_parietal_Hibiki, Flux_parietal_Kommajosyula, Flux_parietal_Kurul_Podowski, Flux_parietal_adaptatif, Flux_parietal_diphasique_simple_lineaire, and Flux_parietal_Nusselt.
Referenced by Flux_parietal_adaptatif::readOn().
qp()
virtual void Flux_parietal_base::qp (const input_t & input, output_t & output) const pure virtual
Implemented in Flux_parietal_Hibiki, Flux_parietal_Kommajosyula, Flux_parietal_Kurul_Podowski, Flux_parietal_adaptatif, Flux_parietal_diphasique_simple_lineaire, and Flux_parietal_Nusselt.
T_at_wall()
virtual int Flux_parietal_base::T_at_wall () const pure virtual
Implemented in Flux_parietal_Hibiki, Flux_parietal_Kommajosyula, Flux_parietal_Kurul_Podowski, Flux_parietal_adaptatif, Flux_parietal_diphasique_simple_lineaire, and Flux_parietal_Nusselt.
calculates_bubble_nucleation_diameter()
virtual int Flux_parietal_base::calculates_bubble_nucleation_diameter () const inline virtual
Reimplemented in Flux_parietal_Hibiki, Flux_parietal_Kommajosyula, and Flux_parietal_Kurul_Podowski.
Referenced by Nucleation_paroi_PolyMAC_P0::readOn().
needs_saturation()
virtual int Flux_parietal_base::needs_saturation () const inline virtual
Reimplemented in Flux_parietal_Hibiki, Flux_parietal_Kommajosyula, and Flux_parietal_Kurul_Podowski.
Member Data Documentation
info_obj
const Type_info Flux_parietal_base::info_obj static