TrioCFD: EOS_Tools_VDF Class Reference
EOS_Tools_VDF Class Reference
#include <EOS_Tools_VDF.h>
Public Member Functions
void divu_discvit (const DoubleTab &, DoubleTab &) override
const Type_info * get_info () const override
double moyenne_vol (const DoubleTab &) const override
const DoubleTab & rho_discvit () const override
void secmembre_divU_Z (DoubleTab &) const override
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
See also
Fluide_Dilatable_base EOS_Tools_base
Constructor & Destructor Documentation
EOS_Tools_VDF()
EOS_Tools_VDF::EOS_Tools_VDF ()
~EOS_Tools_VDF()
EOS_Tools_VDF::~EOS_Tools_VDF ()
Member Function Documentation
cree_instance()
Objet_U * EOS_Tools_VDF::cree_instance () static
taille_memoire()
unsigned EOS_Tools_VDF::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int EOS_Tools_VDF::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * EOS_Tools_VDF::info () static
get_info()
const Type_info * EOS_Tools_VDF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from EOS_Tools_base.
self_cast() [1/2]
EOS_Tools_VDF & EOS_Tools_VDF::self_cast (Objet_U & r) static
self_cast() [2/2]
const EOS_Tools_VDF & EOS_Tools_VDF::self_cast (const Objet_U & r) static
printOn()
Sortie & EOS_Tools_VDF::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from EOS_Tools_base.
References Objet_U::que_suis_je().
readOn()
Entree & EOS_Tools_VDF::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from EOS_Tools_base.
rho_discvit()
const DoubleTab & EOS_Tools_VDF::rho_discvit () const override virtual
Renvoie rho avec la meme discretisation que la vitesse : une valeur par face en VDF.
Returns
(DoubleTab&) rho discretise par face
Implements EOS_Tools_base.
References tab_rho_face_demi.
associer_domaines()
void EOS_Tools_VDF::associer_domaines (const Domaine_dis_base & dds, const Domaine_Cl_dis_base & domaine_cl) override virtual
Implements EOS_Tools_base.
References Champ_Inc_base::associer_domaine_dis_base(), Field_base::fixer_nb_comp(), Champ_Face_VDF::fixer_nb_valeurs_nodales(), le_dom, le_dom_Cl, tab_rho_face, tab_rho_face_demi, tab_rho_face_np1, and Champ_Inc_base::valeurs().
divu_discvit()
void EOS_Tools_VDF::divu_discvit (const DoubleTab & secmem1, DoubleTab & secmem2) override virtual
Renvoie div(u) avec la meme discretisation que la vitesse : une valeur par face en VDF.
Returns
div(u) discretise par face
Implements EOS_Tools_base.
References TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), and le_dom.
secmembre_divU_Z()
void EOS_Tools_VDF::secmembre_divU_Z (DoubleTab & tab_W) const override virtual
Calcule le second membre de l'equation de continuite : div(rhoU) = W = -dZ/dT avec Z=rho.
Returns
rho discretise par face
Implements EOS_Tools_base.
References Source_Masse_Fluide_Dilatable_base::ajouter_projection(), MorEqn::equation(), le_dom, le_fluide(), Fluide_Dilatable_base::loi_etat(), Schema_Temps_base::pas_de_temps(), Loi_Etat_base::rho_n(), Loi_Etat_base::rho_np1(), Equation_base::schema_temps(), Debog::verifier(), and Fluide_Dilatable_base::vitesse().
mettre_a_jour()
void EOS_Tools_VDF::mettre_a_jour (double temps) override virtual
Reimplemented from EOS_Tools_base.
References TRUSTVect< _TYPE_, _SIZE_ >::size_totale(), tab_rho_face, tab_rho_face_demi, and tab_rho_face_np1.
calculer_rho_face_np1()
void EOS_Tools_VDF::calculer_rho_face_np1 (const DoubleTab & rho) override virtual
Implements EOS_Tools_base.
References TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), le_dom, tab_rho_face, tab_rho_face_demi, tab_rho_face_np1, and Debog::verifier().
moyenne_vol()
double EOS_Tools_VDF::moyenne_vol (const DoubleTab & tab) const override virtual
Calcule la moyenne volumique de la grandeur P0 donnee.
Returns
(DoubleTab&) rho discretise par face
Implements EOS_Tools_base.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), and le_dom.
rho_face_n()
const DoubleTab & EOS_Tools_VDF::rho_face_n () const inline override virtual
Implements EOS_Tools_base.
References tab_rho_face.
rho_face_np1()
const DoubleTab & EOS_Tools_VDF::rho_face_np1 () const inline override virtual
Implements EOS_Tools_base.
References tab_rho_face_np1.
le_fluide()
const Fluide_Dilatable_base & EOS_Tools_VDF::le_fluide () const inline
References EOS_Tools_base::le_fluide_, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by secmembre_divU_Z().
Member Data Documentation
info_obj
const Type_info EOS_Tools_VDF::info_obj static
le_dom
TRUST_Ref< Domaine_VDF *> EOS_Tools_VDF::le_dom protected
Referenced by associer_domaines(), calculer_rho_face_np1(), divu_discvit(), moyenne_vol(), and secmembre_divU_Z().
le_dom_Cl
TRUST_Ref< Domaine_Cl_dis_base *> EOS_Tools_VDF::le_dom_Cl protected
Referenced by associer_domaines().
tab_rho_face
DoubleTab EOS_Tools_VDF::tab_rho_face protected
Referenced by associer_domaines(), calculer_rho_face_np1(), mettre_a_jour(), and rho_face_n().
tab_rho_face_demi
DoubleTab EOS_Tools_VDF::tab_rho_face_demi protected
Referenced by associer_domaines(), calculer_rho_face_np1(), mettre_a_jour(), and rho_discvit().
tab_rho_face_np1
DoubleTab EOS_Tools_VDF::tab_rho_face_np1 protected
Referenced by associer_domaines(), calculer_rho_face_np1(), mettre_a_jour(), and rho_face_np1().