TrioCFD: Flux_parietal_diphasique_simple_lineaire Class Reference
Flux_parietal_diphasique_simple_lineaire Class Reference
#include <Flux_parietal_diphasique_simple_lineaire.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Flux_parietal_diphasique_simple_lineaire()
Flux_parietal_diphasique_simple_lineaire::Flux_parietal_diphasique_simple_lineaire ()
~Flux_parietal_diphasique_simple_lineaire()
Flux_parietal_diphasique_simple_lineaire::~Flux_parietal_diphasique_simple_lineaire ()
Member Function Documentation
cree_instance()
Objet_U * Flux_parietal_diphasique_simple_lineaire::cree_instance () static
taille_memoire()
unsigned Flux_parietal_diphasique_simple_lineaire::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Flux_parietal_diphasique_simple_lineaire::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Flux_parietal_diphasique_simple_lineaire::info () static
get_info()
const Type_info * Flux_parietal_diphasique_simple_lineaire::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Flux_parietal_base.
self_cast() [1/2]
Flux_parietal_diphasique_simple_lineaire & Flux_parietal_diphasique_simple_lineaire::self_cast (Objet_U & r) static
self_cast() [2/2]
const Flux_parietal_diphasique_simple_lineaire & Flux_parietal_diphasique_simple_lineaire::self_cast (const Objet_U & r) static
printOn()
Sortie & Flux_parietal_diphasique_simple_lineaire::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Flux_parietal_base.
readOn()
Entree & Flux_parietal_diphasique_simple_lineaire::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Flux_parietal_base.
References Param::ajouter(), Nom::debute_par(), Process::exit(), Milieu_composite::get_saturation(), Milieu_composite::has_saturation(), Param::lire_avec_accolades_depuis(), Pb_Multiphase::nb_phases(), Pb_Multiphase::nom_phase(), Correlation_base::pb_, Objet_U::que_suis_je(), Param::REQUIRED, and TRUST_Ref< _CLASSE_ >::valeur().
qp()
void Flux_parietal_diphasique_simple_lineaire::qp (const input_t & input, output_t & output) const override virtual
Implements Flux_parietal_base.
References Flux_parietal_base::output_t::dTf_qpi, Flux_parietal_base::output_t::dTf_qpk, Flux_parietal_base::output_t::dTp_qpi, Flux_parietal_base::output_t::dTp_qpk, fraction_flux_vap(), Milieu_composite::has_saturation(), Flux_parietal_base::input_t::N, Flux_parietal_base::output_t::nonlinear, Flux_parietal_base::input_t::p, Correlation_base::pb_, Flux_parietal_base::output_t::qpi, Flux_parietal_base::output_t::qpk, Flux_parietal_base::input_t::T, Flux_parietal_base::input_t::Tp, and Saturation_base::Tsat().
T_at_wall()
int Flux_parietal_diphasique_simple_lineaire::T_at_wall () const inline override virtual
Implements Flux_parietal_base.
fraction_flux_vap()
double Flux_parietal_diphasique_simple_lineaire::fraction_flux_vap (const input_t & in, double phi, double dTf_phi, double dp_phi, double dTp_phi, double & dTf_eps, double & dp_eps, double & dTp_eps) const
References Saturation_base::dP_Tsat(), Flux_parietal_base::input_t::p, Flux_parietal_base::input_t::T, and Saturation_base::Tsat().
Referenced by qp().
Member Data Documentation
info_obj
const Type_info Flux_parietal_diphasique_simple_lineaire::info_obj static