TrioCFD: Source_Robin_Scalaire Class Reference
Source_Robin_Scalaire Class Reference
#include <Source_Robin_Scalaire.h>
Public Member Functions
void completer () override
const Type_info * get_info () const override
void mettre_a_jour (double) override
Public Member Functions inherited from Source_base
virtual int a_pour_Champ_Fonc (const Motcle &mot, TRUST_Ref< Champ_base * > &ch_ref) const
virtual void associer_champ_rho (const Champ_base &champ_rho)
virtual void completer ()
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
virtual void resetTime (double t)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Source_Robin_Scalaire()
Source_Robin_Scalaire::Source_Robin_Scalaire ()
~Source_Robin_Scalaire()
Source_Robin_Scalaire::~Source_Robin_Scalaire ()
Member Function Documentation
cree_instance()
Objet_U * Source_Robin_Scalaire::cree_instance () static
taille_memoire()
unsigned Source_Robin_Scalaire::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Source_Robin_Scalaire::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Source_Robin_Scalaire::info () static
get_info()
const Type_info * Source_Robin_Scalaire::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Source_base.
self_cast() [1/2]
Source_Robin_Scalaire & Source_Robin_Scalaire::self_cast (Objet_U & r) static
self_cast() [2/2]
const Source_Robin_Scalaire & Source_Robin_Scalaire::self_cast (const Objet_U & r) static
printOn()
Sortie & Source_Robin_Scalaire::printOn (Sortie & os) const override protected virtual
DOES NOTHING - to override in derived classes.
Imprime la source sur un flot de sortie.
Parameters
(Sortie& os) le flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Source_base.
References Objet_U::que_suis_je().
readOn()
Entree & Source_Robin_Scalaire::readOn (Entree & is) override protected virtual
DOES NOTHING - to override in derived classes.
Lecture d'un terme source sur un flot d'entree.
Parameters
(Entree& is) le flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Source_base.
References TRUST_Vector< _CLASSE_ >::dimensionner(), noms_parois, TRUSTVect< _TYPE_, _SIZE_ >::resize(), and T_parois.
associer_pb()
void Source_Robin_Scalaire::associer_pb (const Probleme_base & pb) override virtual
Implements Source_base.
ajouter()
DoubleTab & Source_Robin_Scalaire::ajouter (DoubleTab & resu) const override virtual
Reimplemented from Source_base.
References Milieu_base::conductivite(), Modele_turbulence_scal_base::conductivite_turbulente(), MorEqn::equation(), Turbulence_paroi_scal_base::equivalent_distance(), Domaine_VF::face_voisins(), Equation_base::get_modele(), Equation_base::inconnue(), le_dom_Cl_VEF, le_dom_VEF, Objet_U_ptr::le_nom(), Domaine_Cl_dis_base::les_conditions_limites(), Modele_turbulence_scal_base::loi_paroi(), Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), noms_parois, Front_VF::num_premiere_face(), Noms::search(), T_parois, TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), TRUST_Ref_Objet_U::valeur(), Champ_Don_base::valeurs(), and Champ_Inc_base::valeurs().
Referenced by calculer().
calculer()
DoubleTab & Source_Robin_Scalaire::calculer (DoubleTab & resu) const override virtual
Reimplemented from Source_base.
References ajouter().
mettre_a_jour()
void Source_Robin_Scalaire::mettre_a_jour (double temps) inline override virtual
DOES NOTHING - to override in derived classes.
Mise a jour en temps du terme source.
Parameters
(double) le pas de temps de mise a jour
Reimplemented from Source_base.
completer()
void Source_Robin_Scalaire::completer () override virtual
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees: Source_base::associer_domaines(const Domaine_dis_base& ,const Domaine_Cl_dis_base&) Source_base::associer_pb(const Probleme_base&)
Reimplemented from Source_base.
References Source_base::completer(), MorEqn::equation(), Probleme_base::equation(), Equation_base::probleme(), Equation_base::sources(), Source_Robin::tab_d_plus(), tab_d_plus, Source_Robin::tab_u_star(), and tab_u_star.
associer_domaines()
void Source_Robin_Scalaire::associer_domaines (const Domaine_dis_base & z, const Domaine_Cl_dis_base & zcl) override protected virtual
Implements Source_base.
References le_dom_Cl_VEF, and le_dom_VEF.
Member Data Documentation
info_obj
const Type_info Source_Robin_Scalaire::info_obj static
le_dom_VEF
TRUST_Ref< Domaine_VEF *> Source_Robin_Scalaire::le_dom_VEF protected
Referenced by ajouter(), and associer_domaines().
le_dom_Cl_VEF
TRUST_Ref< Domaine_Cl_VEF *> Source_Robin_Scalaire::le_dom_Cl_VEF protected
Referenced by ajouter(), and associer_domaines().
noms_parois
Noms Source_Robin_Scalaire::noms_parois protected
Referenced by ajouter(), and readOn().
T_parois
DoubleVect Source_Robin_Scalaire::T_parois protected
Referenced by ajouter(), and readOn().
tab_u_star
TRUST_Ref< DoubleVect *> Source_Robin_Scalaire::tab_u_star protected
Referenced by completer().
tab_d_plus
TRUST_Ref< DoubleVect *> Source_Robin_Scalaire::tab_d_plus protected
Referenced by completer().