TrioCFD: Domaine_bord_32_64< _SIZE_ > Class Template Reference
Domaine_bord_32_64< _SIZE_ > Class Template Reference
#include <Domaine_bord.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Domaine_32_64< _SIZE_ >
void ajouter (const DoubleTab_t &soms)
void ajouter (const DoubleTab_t &soms, IntVect_t &nums)
int associer_ (Objet_U &) override
Bord_Interne_t & bords_interne (int i)
void build_mc_mesh () const
void calculer_centres_gravite (DoubleTab_t &xp) const
void calculer_centres_gravite_aretes (DoubleTab_t &xa) const
void calculer_volumes (DoubleVect_t &volumes, DoubleVect_t &inv_volumes) const
SmallArrOfTID_t & chercher_aretes (const DoubleTab &pos, SmallArrOfTID_t &arr, int reel=0) const
SmallArrOfTID_t & chercher_elements (const DoubleTab &pos, SmallArrOfTID_t &elem, int reel=0) const
SmallArrOfTID_t & chercher_elements (const DoubleVect &pos, SmallArrOfTID_t &elem, int reel=0) const
int_t chercher_elements (double x, double y=0, double z=0, int reel=0) const
SmallArrOfTID_t & chercher_sommets (const DoubleTab &pos, SmallArrOfTID_t &som, int reel=0) const
int_t chercher_sommets (double x, double y=0, double z=0, int reel=0) const
virtual void clear ()
void construire_elem_virt_pe_num ()
void correct_type_of_borders_after_merge ()
virtual void creer_tableau_elements (Array_base &, RESIZE_OPTIONS opt=RESIZE_OPTIONS::COPY_INIT) const
virtual void creer_tableau_sommets (Array_base &, RESIZE_OPTIONS opt=RESIZE_OPTIONS::COPY_INIT) const
const TRUST_List< TRUST_Ref< Domaine_32_64 * > > & domaines_frontieres () const
void ecrire_noms_bords (Sortie &) const
int_t face_bords_interne_conjuguee (int_t face) const
void fill_from_list (std::list< Domaine_32_64 * > &lst)
const Frontiere_t & frontiere (int i) const
const Type_info * get_info () const override
const ArrOfInt_t & ind_faces_virt_bord () const
SmallArrOfTID_t & indice_elements (const IntTab &som, SmallArrOfTID_t &elem, int reel=0) const
void init_renum_perio ()
int nb_bords () const
int nb_faces_elem (int=0) const
int_t nb_faces_frontiere (Type_Face type) const
int_t nb_faces_specifiques () const
int_t nb_faces_specifiques (Type_Face type) const
int nb_groupes_faces () const
int nb_joints () const
int nb_raccords () const
int nb_som_elem () const
void renum (const IntVect_t &nums)
void renum_joint_common_items (const IntVect_t &nums, const int_t elem_offset)
void typer (const Nom &)
Public Member Functions inherited from Domaine_base
const Type_info * get_info () const override
const Nom & le_nom () const override
void nommer (const Nom &nom) override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions
static void extraire_domaine_bord (const Domaine_t &src, const Nom &nom_bord, Domaine_t &dest, ArrOfInt_t &renum_som)
Static Public Member Functions inherited from Domaine_32_64< _SIZE_ >
static int identifie_item_unique (IntList &item_possible, DoubleTab &coord_possible, const DoubleVect &coord_ref)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Additional Inherited Members
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
template<typename _SIZE_>
class Domaine_bord_32_64< _SIZE_ >
On construit ce domaine par la methode construire_domaine_bord()
Member Typedef Documentation
int_t
template<typename _SIZE_ > using Domaine_bord_32_64< _SIZE_ >::int_t = _SIZE_
ArrOfInt_t
template<typename _SIZE_ > using Domaine_bord_32_64< _SIZE_ >::ArrOfInt_t = ArrOfInt_T<_SIZE_>
IntTab_t
template<typename _SIZE_ > using Domaine_bord_32_64< _SIZE_ >::IntTab_t = IntTab_T<_SIZE_>
DoubleTab_t
template<typename _SIZE_ > using Domaine_bord_32_64< _SIZE_ >::DoubleTab_t = DoubleTab_T<_SIZE_>
Frontiere_t
template<typename _SIZE_ > using Domaine_bord_32_64< _SIZE_ >::Frontiere_t = Frontiere_32_64<_SIZE_>
Domaine_t
template<typename _SIZE_ > using Domaine_bord_32_64< _SIZE_ >::Domaine_t = Domaine_32_64<_SIZE_>
Constructor & Destructor Documentation
Domaine_bord_32_64()
template<typename _T_ > Domaine_bord_32_64< _T_ >::Domaine_bord_32_64
~Domaine_bord_32_64()
template<typename _T_ > Domaine_bord_32_64< _T_ >::~Domaine_bord_32_64
Member Function Documentation
cree_instance()
template<typename _T_ > Objet_U * Domaine_bord_32_64< _T_ >::cree_instance static
taille_memoire()
template<typename _T_ > unsigned Domaine_bord_32_64< _T_ >::taille_memoire override virtual
Reimplemented from Domaine_32_64< _SIZE_ >.
duplique()
template<typename _T_ > int Domaine_bord_32_64< _T_ >::duplique override virtual
Reimplemented from Domaine_32_64< _SIZE_ >.
info()
template<typename _T_ > const Type_info * Domaine_bord_32_64< _T_ >::info static
get_info()
template<typename _T_ > const Type_info * Domaine_bord_32_64< _T_ >::get_info override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Domaine_32_64< _SIZE_ >.
self_cast() [1/2]
template<typename _T_ > Domaine_bord_32_64< _T_ > & Domaine_bord_32_64< _T_ >::self_cast (Objet_U & r) static
self_cast() [2/2]
template<typename _T_ > const Domaine_bord_32_64< _T_ > & Domaine_bord_32_64< _T_ >::self_cast (const Objet_U & r) static
printOn()
template<typename _SIZE_ > Sortie & Domaine_bord_32_64< _SIZE_ >::printOn (Sortie & x) const override protected virtual
pour l'instant exit()
Reimplemented from Domaine_32_64< _SIZE_ >.
readOn()
template<typename _SIZE_ > Entree & Domaine_bord_32_64< _SIZE_ >::readOn (Entree & is) override protected virtual
pour l'instant exit()
Reimplemented from Domaine_32_64< _SIZE_ >.
construire_domaine_bord()
template<typename _SIZE_ > void Domaine_bord_32_64< _SIZE_ >::construire_domaine_bord (const Domaine_t & source, const Nom & nom_bord) virtual
construit le domaine en appelant extraire_domaine_bord()
Referenced by Corriger_frontiere_periodique_32_64< _SIZE_ >::corriger_coordonnees_sommets_perio().
get_domaine_source()
template<typename _SIZE_ > const Domaine_32_64< _SIZE_ > & Domaine_bord_32_64< _SIZE_ >::get_domaine_source virtual
renvoie une reference au domaine source
get_nom_bord_source()
template<typename _SIZE_ > const Nom & Domaine_bord_32_64< _SIZE_ >::get_nom_bord_source virtual
renvoie le nom du bord source
get_renum_som()
template<typename _SIZE_ > const ArrOfInt_T< _SIZE_ > & Domaine_bord_32_64< _SIZE_ >::get_renum_som virtual
renvoie renum_som (pour chaque sommet du domaine_bord, indice du meme sommet dans le domaine)
Referenced by Corriger_frontiere_periodique_32_64< _SIZE_ >::corriger_coordonnees_sommets_perio().
extraire_domaine_bord()
template<typename _SIZE_ > void Domaine_bord_32_64< _SIZE_ >::extraire_domaine_bord (const Domaine_t & src, const Nom & nom_bord, Domaine_t & dest, ArrOfInt_t & renum_som) static
remplit le domaine "dest" avec les sommets et les faces du bord "nom_bord" du domaine "src".
Les sommets du domaine dest sont uniquement les sommets qui sont sur une face du bord. Le tableau renum_som est dimensionne a dest.nb_som() et rempli comme suit: renum_som[i] est l'indice dans le domaine "src" du sommet i du domaine "dest".
References TRUSTArray< _TYPE_, _SIZE_ >::append_array(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Frontiere_32_64< _SIZE_ >::faces(), Domaine_32_64< _SIZE_ >::frontiere(), Process::is_parallel(), Domaine_base::le_nom(), Domaine_32_64< _SIZE_ >::les_elems(), Domaine_32_64< _SIZE_ >::les_sommets(), Faces_32_64< _SIZE_ >::les_sommets(), Domaine_32_64< _SIZE_ >::nb_elem(), Faces_32_64< _SIZE_ >::nb_faces(), Domaine_32_64< _SIZE_ >::nb_som(), Faces_32_64< _SIZE_ >::nb_som_faces(), Domaine_base::nommer(), TRUSTArray< _TYPE_, _SIZE_ >::reset(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Domaine_32_64< _SIZE_ >::type_elem(), Objet_U_ptr::typer(), and TRUST_Deriv< _CLASSE_ >::valeur().
info_obj() [1/2]
const Type_info Domaine_bord_32_64< int >::info_obj ("Domaine_bord" , Domaine_bord_32_64< int >::cree_instance , 1 , Domaine_bord_32_64bases< int >)
info_obj() [2/2]
const Type_info Domaine_bord_32_64< trustIdType >::info_obj ("Domaine_bord" "_64" , Domaine_bord_32_64< trustIdType >::cree_instance , 1 , Domaine_bord_32_64bases< trustIdType >)
Member Data Documentation
info_obj
template<typename _SIZE_ > const Type_info Domaine_bord_32_64< _SIZE_ >::info_obj static
domaine_source_
template<typename _SIZE_ > TRUST_Ref< Domaine_t *> Domaine_bord_32_64< _SIZE_ >::domaine_source_ protected
bord_source_
template<typename _SIZE_ > Nom Domaine_bord_32_64< _SIZE_ >::bord_source_ protected
renum_som_
template<typename _SIZE_ > ArrOfInt_t Domaine_bord_32_64< _SIZE_ >::renum_som_ protected