TrioCFD: MD_Vector_seq Class Reference
MD_Vector_seq Class Reference
#include <MD_Vector_seq.h>
Public Member Functions
const Type_info * get_info () const override
bool use_blocks () const override
bool validate (trustIdType sz_array, int line_size) const override
const Type_info * get_info () const override
const Type_info * get_info () const override
virtual bool use_blocks () const =0
virtual bool validate (trustIdType sz_array, int line_size) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from MD_Vector_base
static void append_item_to_blocs (ArrOfInt &blocs, int item)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
Its only useful information is the total number of items hold by the array which can be big (hence the use of trustIdType).
In this class, all the inherited counters accessors (get_nb_items*() methods, etc.) return this number. We however carefully check that the number of items fit within 32b since thoses inherited accessors return 'int'. No piece of code is actually using those methods in the 64b part of the execution (i.e. before Scatter).
Historically we used a MD_Vector_std for sequential computations too, and this std MD_Vector had a single block covering the whole array. But having a template version of the MD_Vector_std class (supporting both 32b and 64b) seemed unreasonable, hence the creation of the current class.
See arch.h.in for more explanations on 64b.
In this class, members inherited from MD_Vector_mono are meaningless and their information is not updated. Algorithm like get_sequential_items_flags() are actually overriden not to use this.
Constructor & Destructor Documentation
~MD_Vector_seq()
MD_Vector_seq::~MD_Vector_seq ()
MD_Vector_seq() [1/2]
MD_Vector_seq::MD_Vector_seq () inline
MD_Vector_seq() [2/2]
MD_Vector_seq::MD_Vector_seq (const trustIdType & nb) inline
Member Function Documentation
cree_instance()
Objet_U * MD_Vector_seq::cree_instance () static
taille_memoire()
unsigned MD_Vector_seq::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int MD_Vector_seq::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * MD_Vector_seq::info () static
get_info()
const Type_info * MD_Vector_seq::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from MD_Vector_mono.
self_cast() [1/2]
MD_Vector_seq & MD_Vector_seq::self_cast (Objet_U & r) static
self_cast() [2/2]
const MD_Vector_seq & MD_Vector_seq::self_cast (const Objet_U & r) static
printOn()
Sortie & MD_Vector_seq::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from MD_Vector_mono.
References MD_Vector_mono::printOn().
readOn()
Entree & MD_Vector_seq::readOn (Entree & is) override protected virtual
method used to dump/restore a descriptor in a file Each process writes a different descriptor.
See MD_Vector_tools::dump_vector_with_md()
Reimplemented from MD_Vector_mono.
References Param::ajouter(), Param::lire_avec_accolades(), Objet_U::que_suis_je(), and MD_Vector_mono::readOn().
get_nb_items()
trustIdType MD_Vector_seq::get_nb_items () const inline
validate()
bool MD_Vector_seq::validate (trustIdType sz_array, int line_size) const inline override virtual
Check the consistency of array size as defined by the MD_Vector and as found in the array.
Reimplemented from MD_Vector_base.
get_nb_items_reels()
int MD_Vector_seq::get_nb_items_reels () const override virtual
Reimplemented from MD_Vector_base.
get_nb_items_tot()
int MD_Vector_seq::get_nb_items_tot () const override virtual
Reimplemented from MD_Vector_base.
nb_items_seq_tot()
trustIdType MD_Vector_seq::nb_items_seq_tot () const inline override virtual
Reimplemented from MD_Vector_base.
nb_items_seq_local()
int MD_Vector_seq::nb_items_seq_local () const override virtual
Reimplemented from MD_Vector_base.
initialize_comm() [1/4]
void MD_Vector_seq::initialize_comm (const Echange_EV_Options & opt, Schema_Comm_Vecteurs & , DoubleVect &) const inline override virtual
Implements MD_Vector_base.
prepare_send_data() [1/4]
void MD_Vector_seq::prepare_send_data (const Echange_EV_Options & opt, Schema_Comm_Vecteurs & , DoubleVect &) const inline override virtual
Implements MD_Vector_base.
process_recv_data() [1/4]
void MD_Vector_seq::process_recv_data (const Echange_EV_Options & opt, Schema_Comm_Vecteurs & , DoubleVect &) const inline override virtual
Implements MD_Vector_base.
initialize_comm() [2/4]
void MD_Vector_seq::initialize_comm (const Echange_EV_Options & opt, Schema_Comm_Vecteurs & , FloatVect &) const inline override virtual
Implements MD_Vector_base.
prepare_send_data() [2/4]
void MD_Vector_seq::prepare_send_data (const Echange_EV_Options & opt, Schema_Comm_Vecteurs & , FloatVect &) const inline override virtual
Implements MD_Vector_base.
process_recv_data() [2/4]
void MD_Vector_seq::process_recv_data (const Echange_EV_Options & opt, Schema_Comm_Vecteurs & , FloatVect &) const inline override virtual
Implements MD_Vector_base.
initialize_comm() [3/4]
void MD_Vector_seq::initialize_comm (const Echange_EV_Options & opt, Schema_Comm_Vecteurs & , IntVect &) const inline override virtual
Implements MD_Vector_base.
prepare_send_data() [3/4]
void MD_Vector_seq::prepare_send_data (const Echange_EV_Options & opt, Schema_Comm_Vecteurs & , IntVect &) const inline override virtual
Implements MD_Vector_base.
process_recv_data() [3/4]
void MD_Vector_seq::process_recv_data (const Echange_EV_Options & opt, Schema_Comm_Vecteurs & , IntVect &) const inline override virtual
Implements MD_Vector_base.
initialize_comm() [4/4]
void MD_Vector_seq::initialize_comm (const Echange_EV_Options & opt, Schema_Comm_Vecteurs & , TIDVect &) const inline override virtual
Implements MD_Vector_base.
prepare_send_data() [4/4]
void MD_Vector_seq::prepare_send_data (const Echange_EV_Options & opt, Schema_Comm_Vecteurs & , TIDVect &) const inline override virtual
Implements MD_Vector_base.
process_recv_data() [4/4]
void MD_Vector_seq::process_recv_data (const Echange_EV_Options & opt, Schema_Comm_Vecteurs & , TIDVect &) const inline override virtual
Implements MD_Vector_base.
append_from_other_seq()
void MD_Vector_seq::append_from_other_seq (const MD_Vector_seq & src, int offset, int multiplier) override virtual
Reimplemented from MD_Vector_mono.
fill_md_vect_renum()
void MD_Vector_seq::fill_md_vect_renum (const IntVect & renum, MD_Vector & md_vect) const override virtual
Implements MD_Vector_base.
References MD_Vector::copy().
use_blocks()
bool MD_Vector_seq::use_blocks () const inline override virtual
Whether algorithms in TRUSTVect_tools should use the blocks stored in members MD_Vector_mono::blocs_items_to_*
Implements MD_Vector_base.
get_seq_flags_impl()
int MD_Vector_seq::get_seq_flags_impl (ArrOfBit & flags, int line_size) const override protected virtual
Reimplemented from MD_Vector_base.
References ArrOfBit_32_64< _SIZE_ >::resize_array().
Member Data Documentation
info_obj
const Type_info MD_Vector_seq::info_obj static