TrioCFD: Transport_K_ou_Eps_non_std Class Reference
Transport_K_ou_Eps_non_std Class Reference
#include <Transport_K_ou_Eps_non_std.h>
Public Member Functions
const Type_info * get_info () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
const Operateur & operateur (int) const override
Operateur & operateur (int) override
Public Member Functions inherited from Transport_K_ou_Eps_base
virtual int controler_variable ()
void discretiser () override
const Type_info * get_info () const override
const Champ_Inc_base & inconnue () const override
Champ_Inc_base & inconnue () override
Public Member Functions inherited from Transport_2eq_base
void associer_milieu_base (const Milieu_base &) override
double calculer_pas_de_temps () const override
const Type_info * get_info () const override
const Milieu_base & milieu () const override
Milieu_base & milieu () override
Modele_turbulence_hyd_2_eq_base & modele_turbulence ()
const Modele_turbulence_hyd_2_eq_base & modele_turbulence () const
Public Member Functions inherited from Equation_base
virtual void abortTimeStep ()
virtual void associer_domaine_dis (const Domaine_dis_base &)
virtual void associer_pb_base (const Probleme_base &)
virtual void associer_sch_tps_base (const Schema_Temps_base &)
virtual double calculer_pas_de_temps () const
virtual void completer ()
virtual std::vector< YAML_data > data_a_sauvegarder () const
DoubleTab & derivee_en_temps_conv (DoubleTab &, const DoubleTab &)
virtual DoubleTab & derivee_en_temps_inco (DoubleTab &)
const Discretisation_base & discretisation () const
virtual void discretiser ()
virtual const Motcle & domaine_application () const
virtual Domaine_Cl_dis_base & domaine_Cl_dis ()
virtual const Domaine_Cl_dis_base & domaine_Cl_dis () const
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual void imprimer (Sortie &os) const
virtual bool initTimeStep (double dt)
const Nom & le_nom () const override
int limpr () const
virtual void mettre_a_jour (double temps)
virtual int preparer_calcul ()
Probleme_base & probleme ()
const Probleme_base & probleme () const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Schema_Temps_base & schema_temps ()
const Schema_Temps_base & schema_temps () const
Solveur_Masse_base & solv_masse ()
const Solveur_Masse_base & solv_masse () const
Sources & sources ()
const Sources & sources () const
virtual void valider_iteration ()
virtual void verifie_ch_init_nb_comp (const Champ_Inc_base &ch_ref, const int nb_comp) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Equation_base
virtual Entree & lire_cl (Entree &)
virtual Entree & lire_cond_init (Entree &)
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual Entree & lire_sources (Entree &)
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
virtual int verif_Cl () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
des modeles k_Epsilon non standard en formulation bicephale.
Constructor & Destructor Documentation
Transport_K_ou_Eps_non_std()
Transport_K_ou_Eps_non_std::Transport_K_ou_Eps_non_std ()
~Transport_K_ou_Eps_non_std()
Transport_K_ou_Eps_non_std::~Transport_K_ou_Eps_non_std () override
Member Function Documentation
info()
const Type_info * Transport_K_ou_Eps_non_std::info () static
get_info()
const Type_info * Transport_K_ou_Eps_non_std::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Transport_K_ou_Eps_base.
self_cast() [1/2]
Transport_K_ou_Eps_non_std & Transport_K_ou_Eps_non_std::self_cast (Objet_U & r) static
self_cast() [2/2]
const Transport_K_ou_Eps_non_std & Transport_K_ou_Eps_non_std::self_cast (const Objet_U & r) static
printOn()
Sortie & Transport_K_ou_Eps_non_std::printOn (Sortie & is) const override protected virtual
Parameters
(Sortie& is) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Transport_K_ou_Eps_base.
References Objet_U::que_suis_je().
readOn()
Entree & Transport_K_ou_Eps_non_std::readOn (Entree & is) override protected virtual
Simple appel a Equation_base::readOn(Entree&)
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Transport_K_ou_Eps_base.
References Transport_K_ou_Eps_base::readOn().
set_param()
void Transport_K_ou_Eps_non_std::set_param (Param & titi) override virtual
Reimplemented from Transport_2eq_base.
References Transport_2eq_base::set_param().
lire_motcle_non_standard()
int Transport_K_ou_Eps_non_std::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Equation_base.
References Operateur_Diff::associer_diffusivite(), Transport_2eq_base::associer_vitesse(), Operateur_Conv::associer_vitesse(), diffusivite_pour_transport(), Equation_base::lire_motcle_non_standard(), Transport_2eq_base::lire_op_diff_turbulent(), Transport_2eq_base::terme_convectif, Transport_2eq_base::terme_diffusif, and vitesse_pour_transport().
diffusivite_pour_transport()
const Champ_Don_base & Transport_K_ou_Eps_non_std::diffusivite_pour_transport () const virtual
References Transport_2eq_base::le_fluide, TRUST_Ref< _CLASSE_ >::valeur(), and Fluide_base::viscosite_cinematique().
Referenced by lire_motcle_non_standard().
vitesse_pour_transport()
const Champ_base & Transport_K_ou_Eps_non_std::vitesse_pour_transport () const virtual
References Probleme_base::equation(), Equation_base::inconnue(), and Equation_base::probleme().
Referenced by lire_motcle_non_standard().
nombre_d_operateurs()
int Transport_K_ou_Eps_non_std::nombre_d_operateurs () const override virtual
Implements Equation_base.
Referenced by operateur().
operateur() [1/2]
const Operateur & Transport_K_ou_Eps_non_std::operateur (int i) const override virtual
renvoie terme_diffusif si i=0 renvoie terme_convectif si i=1
exit si i>1
Implements Equation_base.
References Process::exit(), nombre_d_operateurs(), Objet_U::que_suis_je(), Transport_2eq_base::terme_convectif, and Transport_2eq_base::terme_diffusif.
operateur() [2/2]
Operateur & Transport_K_ou_Eps_non_std::operateur (int i) override virtual
renvoie terme_diffusif si i=0 renvoie terme_convectif si i=1
exit si i>1
Implements Equation_base.
References Process::exit(), nombre_d_operateurs(), Objet_U::que_suis_je(), Transport_2eq_base::terme_convectif, and Transport_2eq_base::terme_diffusif.
Member Data Documentation
info_obj
const Type_info Transport_K_ou_Eps_non_std::info_obj static