TrioCFD: Modele_turbulence_hyd_0_eq_base Class Reference
Modele_turbulence_hyd_0_eq_base Class Reference abstract
#include <Modele_turbulence_hyd_0_eq_base.h>
Public Member Functions
const Type_info * get_info () const override
void imprimer (Sortie &) const override
int reprendre (Entree &is) override
Public Member Functions inherited from Modele_turbulence_hyd_base
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Type_info * get_info () const override
virtual void imprimer (Sortie &) const
void lire_distance_paroi ()
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual int preparer_calcul ()
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Modele_turbulence_hyd_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
See also
Modele_turbulence_hyd_base
Constructor & Destructor Documentation
Modele_turbulence_hyd_0_eq_base()
Modele_turbulence_hyd_0_eq_base::Modele_turbulence_hyd_0_eq_base ()
~Modele_turbulence_hyd_0_eq_base()
Modele_turbulence_hyd_0_eq_base::~Modele_turbulence_hyd_0_eq_base () override
Member Function Documentation
info()
const Type_info * Modele_turbulence_hyd_0_eq_base::info () static
get_info()
const Type_info * Modele_turbulence_hyd_0_eq_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
Reimplemented in Modele_turbulence_hyd_LES_axi_VDF, Modele_turbulence_hyd_LES_DSGS_VDF, Modele_turbulence_hyd_LES_selectif_mod_VDF, Modele_turbulence_hyd_LES_selectif_VDF, Modele_turbulence_hyd_LES_SMAGO_DYN_VDF, Modele_turbulence_hyd_LES_VDF, Modele_turbulence_hyd_LES_1elt_selectif_mod_VEF, Modele_turbulence_hyd_LES_1elt_VEF, Modele_turbulence_hyd_LES_Fst_sel_VEF, Modele_turbulence_hyd_LES_Fst_VEF, Modele_turbulence_hyd_LES_Smago_filtre_VEF, Modele_turbulence_hyd_LES_VEF, Modele_turbulence_hyd_combinaison, Modele_turbulence_hyd_LES_base, Modele_turbulence_hyd_Longueur_Melange_base, Modele_turbulence_hyd_LES_Smago_VDF, Modele_turbulence_hyd_LES_VDF_base, Modele_turbulence_hyd_LES_Wale_VDF, Modele_turbulence_hyd_Longueur_Melange_VDF, Modele_turbulence_hyd_LES_Smago_VEF, Modele_turbulence_hyd_LES_VEF_base, Modele_turbulence_hyd_LES_Wale_VEF, and Modele_turbulence_hyd_Longueur_Melange_VEF.
self_cast() [1/2]
Modele_turbulence_hyd_0_eq_base & Modele_turbulence_hyd_0_eq_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Modele_turbulence_hyd_0_eq_base & Modele_turbulence_hyd_0_eq_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Modele_turbulence_hyd_0_eq_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
Reimplemented in Modele_turbulence_hyd_LES_axi_VDF, Modele_turbulence_hyd_LES_DSGS_VDF, Modele_turbulence_hyd_LES_selectif_mod_VDF, Modele_turbulence_hyd_LES_selectif_VDF, Modele_turbulence_hyd_LES_SMAGO_DYN_VDF, Modele_turbulence_hyd_LES_VDF, Modele_turbulence_hyd_LES_1elt_selectif_mod_VEF, Modele_turbulence_hyd_LES_1elt_VEF, Modele_turbulence_hyd_LES_Fst_sel_VEF, Modele_turbulence_hyd_LES_Fst_VEF, Modele_turbulence_hyd_LES_Smago_filtre_VEF, Modele_turbulence_hyd_LES_VEF, Modele_turbulence_hyd_combinaison, Modele_turbulence_hyd_LES_base, Modele_turbulence_hyd_Longueur_Melange_base, Modele_turbulence_hyd_LES_Smago_VDF, Modele_turbulence_hyd_LES_VDF_base, Modele_turbulence_hyd_LES_Wale_VDF, Modele_turbulence_hyd_Longueur_Melange_VDF, Modele_turbulence_hyd_LES_Smago_VEF, Modele_turbulence_hyd_LES_VEF_base, Modele_turbulence_hyd_LES_Wale_VEF, and Modele_turbulence_hyd_Longueur_Melange_VEF.
References Modele_turbulence_hyd_base::printOn().
Referenced by Modele_turbulence_hyd_combinaison::printOn(), Modele_turbulence_hyd_LES_base::printOn(), and Modele_turbulence_hyd_Longueur_Melange_base::printOn().
readOn()
Entree & Modele_turbulence_hyd_0_eq_base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
Reimplemented in Modele_turbulence_hyd_LES_axi_VDF, Modele_turbulence_hyd_LES_DSGS_VDF, Modele_turbulence_hyd_LES_selectif_mod_VDF, Modele_turbulence_hyd_LES_selectif_VDF, Modele_turbulence_hyd_LES_SMAGO_DYN_VDF, Modele_turbulence_hyd_LES_VDF, Modele_turbulence_hyd_LES_1elt_selectif_mod_VEF, Modele_turbulence_hyd_LES_1elt_VEF, Modele_turbulence_hyd_LES_Fst_sel_VEF, Modele_turbulence_hyd_LES_Fst_VEF, Modele_turbulence_hyd_LES_Smago_filtre_VEF, Modele_turbulence_hyd_LES_VEF, Modele_turbulence_hyd_combinaison, Modele_turbulence_hyd_LES_base, Modele_turbulence_hyd_Longueur_Melange_base, Modele_turbulence_hyd_LES_Smago_VDF, Modele_turbulence_hyd_LES_VDF_base, Modele_turbulence_hyd_LES_Wale_VDF, Modele_turbulence_hyd_Longueur_Melange_VDF, Modele_turbulence_hyd_LES_Smago_VEF, Modele_turbulence_hyd_LES_VEF_base, Modele_turbulence_hyd_LES_Wale_VEF, and Modele_turbulence_hyd_Longueur_Melange_VEF.
References Modele_turbulence_hyd_base::readOn().
Referenced by Modele_turbulence_hyd_combinaison::readOn(), Modele_turbulence_hyd_LES_base::readOn(), and Modele_turbulence_hyd_Longueur_Melange_base::readOn().
set_param()
void Modele_turbulence_hyd_0_eq_base::set_param (Param & param) override virtual
Reimplemented from Modele_turbulence_hyd_base.
Reimplemented in Modele_turbulence_hyd_LES_selectif_mod_VDF, Modele_turbulence_hyd_LES_SMAGO_DYN_VDF, Modele_turbulence_hyd_LES_VDF, Modele_turbulence_hyd_combinaison, Modele_turbulence_hyd_LES_base, Modele_turbulence_hyd_LES_Smago_VDF, Modele_turbulence_hyd_LES_Wale_VDF, Modele_turbulence_hyd_Longueur_Melange_VDF, Modele_turbulence_hyd_LES_Smago_VEF, Modele_turbulence_hyd_LES_Wale_VEF, and Modele_turbulence_hyd_Longueur_Melange_VEF.
References Param::ajouter(), fichier_K_eps_sortie_, and Modele_turbulence_hyd_base::set_param().
Referenced by Modele_turbulence_hyd_Longueur_Melange_VDF::set_param(), and Modele_turbulence_hyd_Longueur_Melange_VEF::set_param().
reprendre()
int Modele_turbulence_hyd_0_eq_base::reprendre (Entree &) inline override virtual
Reprise d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree&) flot d'entree a utiliser pour la reprise
Returns
(int) code de retour
Reimplemented from Objet_U.
Reimplemented in Modele_turbulence_hyd_combinaison, and Modele_turbulence_hyd_LES_base.
comprend_mot()
int Modele_turbulence_hyd_0_eq_base::comprend_mot (const Motcle & mot) const
References comprend_champ().
a_pour_Champ_Fonc()
int Modele_turbulence_hyd_0_eq_base::a_pour_Champ_Fonc (const Motcle & mot, TRUST_Ref< Champ_base * > & ch_ref) const
References Process::exit(), Modele_turbulence_hyd_base::la_viscosite_turbulente_, Motcles::search(), and TRUST_Deriv< _CLASSE_ >::valeur().
comprend_champ()
int Modele_turbulence_hyd_0_eq_base::comprend_champ (const Motcle & mot) const
References Process::exit(), and Motcles::search().
Referenced by comprend_mot().
associer()
void Modele_turbulence_hyd_0_eq_base::associer (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis) override virtual
Reimplemented from Modele_turbulence_hyd_base.
Reimplemented in Modele_turbulence_hyd_LES_DSGS_VDF, and Modele_turbulence_hyd_LES_SMAGO_DYN_VDF.
References le_dom_Cl_, and le_dom_VF_.
Referenced by Modele_turbulence_hyd_LES_DSGS_VDF::associer(), and Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::associer().
completer()
void Modele_turbulence_hyd_0_eq_base::completer () override virtual
Reimplemented from Modele_turbulence_hyd_base.
Reimplemented in Modele_turbulence_hyd_combinaison, and Modele_turbulence_hyd_LES_base.
References Discretisation_base::discretiser_champ(), Ecrire_MED_32_64< _SIZE_ >::ecrire_domaine(), fichier_K_eps_sortie_, Field_base::fixer_noms_compo(), Field_base::fixer_unites(), K_eps_sortie_, Process::me(), Modele_turbulence_hyd_base::mon_equation_, Nom::nom_me(), and Field_base::nommer().
mettre_a_jour()
void Modele_turbulence_hyd_0_eq_base::mettre_a_jour (double) override virtual
Implements Modele_turbulence_hyd_base.
Reimplemented in Modele_turbulence_hyd_LES_SMAGO_DYN_VDF, and Modele_turbulence_hyd_combinaison.
References Statistiques::begin_count(), calculer_energie_cinetique_turb(), Turbulence_paroi_base::calculer_hyd(), calculer_viscosite_turbulente(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Statistiques::end_count(), energie_cinetique_turb_, energie_cinetique_turbulente(), Modele_turbulence_hyd_base::la_viscosite_turbulente_, Modele_turbulence_hyd_base::limiter_viscosite_turbulente(), Modele_turbulence_hyd_base::loipar_, Modele_turbulence_hyd_base::mon_equation_, and Champ_Don_base::valeurs().
Referenced by Modele_turbulence_hyd_LES_base::preparer_calcul(), Modele_turbulence_hyd_Longueur_Melange_VDF::preparer_calcul(), and Modele_turbulence_hyd_Longueur_Melange_VEF::preparer_calcul().
discretiser()
void Modele_turbulence_hyd_0_eq_base::discretiser () override virtual
Discretise le modele de turbulence.
Reimplemented from Modele_turbulence_hyd_base.
Reimplemented in Modele_turbulence_hyd_LES_selectif_mod_VDF, Modele_turbulence_hyd_LES_selectif_VDF, Modele_turbulence_hyd_LES_1elt_selectif_mod_VEF, and Modele_turbulence_hyd_LES_Fst_sel_VEF.
References Champs_compris_T< FIELD_TYPE >::ajoute_champ(), Modele_turbulence_hyd_base::champs_compris_, Modele_turbulence_hyd_base::discretiser(), Modele_turbulence_hyd_base::discretiser_K(), energie_cinetique_turb_, and Modele_turbulence_hyd_base::mon_equation_.
Referenced by Modele_turbulence_hyd_LES_selectif_mod_VDF::discretiser(), Modele_turbulence_hyd_LES_selectif_VDF::discretiser(), Modele_turbulence_hyd_LES_1elt_selectif_mod_VEF::discretiser(), and Modele_turbulence_hyd_LES_Fst_sel_VEF::discretiser().
calculer_viscosite_turbulente()
virtual Champ_Fonc_base & Modele_turbulence_hyd_0_eq_base::calculer_viscosite_turbulente () pure virtual
Implemented in Modele_turbulence_hyd_LES_axi_VDF, Modele_turbulence_hyd_LES_DSGS_VDF, Modele_turbulence_hyd_LES_SMAGO_DYN_VDF, Modele_turbulence_hyd_LES_VDF, Modele_turbulence_hyd_LES_1elt_VEF, Modele_turbulence_hyd_LES_Fst_VEF, Modele_turbulence_hyd_LES_VEF, Modele_turbulence_hyd_combinaison, Modele_turbulence_hyd_LES_Smago_VDF, Modele_turbulence_hyd_LES_Wale_VDF, Modele_turbulence_hyd_Longueur_Melange_VDF, Modele_turbulence_hyd_LES_Smago_VEF, Modele_turbulence_hyd_LES_Wale_VEF, and Modele_turbulence_hyd_Longueur_Melange_VEF.
Referenced by mettre_a_jour().
calculer_energie_cinetique_turb()
virtual void Modele_turbulence_hyd_0_eq_base::calculer_energie_cinetique_turb () pure virtual
Implemented in Modele_turbulence_hyd_LES_SMAGO_DYN_VDF, Modele_turbulence_hyd_LES_VDF, Modele_turbulence_hyd_combinaison, Modele_turbulence_hyd_LES_base, and Modele_turbulence_hyd_Longueur_Melange_base.
Referenced by mettre_a_jour().
imprimer()
void Modele_turbulence_hyd_0_eq_base::imprimer (Sortie & os) const override virtual
Effectue l'impression si cela est necessaire.
Returns
renvoie toujours 1
Reimplemented from Modele_turbulence_hyd_base.
Reimplemented in Modele_turbulence_hyd_combinaison, and Modele_turbulence_hyd_LES_base.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Modele_turbulence_hyd_base::dt_impr_ustar_, Modele_turbulence_hyd_base::dt_impr_ustar_mean_only_, Ecrire_MED_32_64< _SIZE_ >::ecrire_champ(), fichier_K_eps_sortie_, Modele_turbulence_hyd_base::imprimer(), K_eps_sortie_, Modele_turbulence_hyd_base::la_viscosite_turbulente_, Objet_U_ptr::le_nom(), Modele_turbulence_hyd_base::limpr_ustar(), Process::me(), Champ_Inc_base::mettre_a_jour(), Modele_turbulence_hyd_base::mon_equation_, Domaine_32_64< _SIZE_ >::nb_elem(), Nom::nom_me(), Field_base::noms_compo(), Objet_U_ptr::non_nul(), Schema_Temps_base::pas_de_temps(), Objet_U::que_suis_je(), Schema_Temps_base::temps_courant(), Schema_Temps_base::temps_precedent(), Domaine_32_64< _SIZE_ >::type_elem(), Field_base::unites(), Champ_Don_base::valeurs(), Champ_Inc_base::valeurs(), and Modele_turbulence_hyd_base::wall_length_.
energie_cinetique_turbulente() [1/2]
virtual Champ_Fonc_base & Modele_turbulence_hyd_0_eq_base::energie_cinetique_turbulente () inline virtual
References energie_cinetique_turb_.
Referenced by Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::mettre_a_jour(), Modele_turbulence_hyd_combinaison::mettre_a_jour(), and mettre_a_jour().
energie_cinetique_turbulente() [2/2]
virtual const Champ_Fonc_base & Modele_turbulence_hyd_0_eq_base::energie_cinetique_turbulente () const inline virtual
References energie_cinetique_turb_.
Member Data Documentation
info_obj
const Type_info Modele_turbulence_hyd_0_eq_base::info_obj static
energie_cinetique_turb_
TRUST_Deriv< Champ_Fonc_base > Modele_turbulence_hyd_0_eq_base::energie_cinetique_turb_ protected
Referenced by Modele_turbulence_hyd_LES_selectif_mod_VDF::a_pour_Champ_Fonc(), Modele_turbulence_hyd_LES_selectif_VDF::a_pour_Champ_Fonc(), Modele_turbulence_hyd_LES_1elt_selectif_mod_VEF::a_pour_Champ_Fonc(), Modele_turbulence_hyd_LES_Fst_sel_VEF::a_pour_Champ_Fonc(), Modele_turbulence_hyd_LES_VDF::calculer_energie_cinetique_turb(), Modele_turbulence_hyd_LES_base::calculer_energie_cinetique_turb(), Modele_turbulence_hyd_Longueur_Melange_base::calculer_energie_cinetique_turb(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calculer_energie_cinetique_turb(), Modele_turbulence_hyd_Longueur_Melange_VDF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_Longueur_Melange_VEF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::controler_grandeurs_turbulentes(), discretiser(), energie_cinetique_turbulente(), and mettre_a_jour().
K_eps_sortie_
TRUST_Deriv< Champ_Inc_base > Modele_turbulence_hyd_0_eq_base::K_eps_sortie_ mutable protected
Referenced by completer(), and imprimer().
fichier_K_eps_sortie_
Nom Modele_turbulence_hyd_0_eq_base::fichier_K_eps_sortie_ protected
Referenced by completer(), imprimer(), and set_param().
le_dom_VF_
TRUST_Ref< Domaine_VF *> Modele_turbulence_hyd_0_eq_base::le_dom_VF_ protected
Referenced by associer(), Modele_turbulence_hyd_LES_DSGS_VDF::associer(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::associer(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calc_elem_elem(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calcul_tableaux_correspondance(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calcul_voisins(), Modele_turbulence_hyd_LES_DSGS_VDF::calculer_cell_cent_vel(), Modele_turbulence_hyd_LES_VDF::calculer_energie_cinetique_turb(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calculer_energie_cinetique_turb(), Modele_turbulence_hyd_Longueur_Melange_VEF::calculer_f_amortissement(), Modele_turbulence_hyd_LES_DSGS_VDF::calculer_filter_coeff(), Modele_turbulence_hyd_LES_DSGS_VDF::calculer_filter_field(), Modele_turbulence_hyd_LES_DSGS_VDF::calculer_filter_tensor(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calculer_filter_tensor(), Modele_turbulence_hyd_LES_VDF::calculer_fonction_structure(), Modele_turbulence_hyd_LES_1elt_VEF::calculer_fonction_structure(), Modele_turbulence_hyd_LES_VEF::calculer_fonction_structure(), Modele_turbulence_hyd_LES_axi_VDF::calculer_fonction_structure(), Modele_turbulence_hyd_LES_DSGS_VDF::calculer_Lij(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calculer_Lij(), Modele_turbulence_hyd_LES_VDF_base::calculer_longueurs_caracteristiques(), Modele_turbulence_hyd_LES_VEF_base::calculer_longueurs_caracteristiques(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calculer_Mij(), Modele_turbulence_hyd_LES_DSGS_VDF::calculer_Mij(), Modele_turbulence_hyd_LES_DSGS_VDF::calculer_model_coefficient(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calculer_model_coefficient(), Modele_turbulence_hyd_LES_Wale_VDF::calculer_OP1_OP2(), Modele_turbulence_hyd_LES_Fst_VEF::calculer_racine(), Modele_turbulence_hyd_LES_Smago_VDF::calculer_S_barre(), Modele_turbulence_hyd_LES_Smago_filtre_VEF::calculer_S_barre(), Modele_turbulence_hyd_LES_DSGS_VDF::calculer_Sij(), Modele_turbulence_hyd_Longueur_Melange_VDF::calculer_Sij2(), Modele_turbulence_hyd_Longueur_Melange_VEF::calculer_Sij2(), Modele_turbulence_hyd_LES_axi_VDF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_DSGS_VDF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_VDF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_1elt_VEF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_Fst_VEF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_VEF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_Smago_VDF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_Wale_VDF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_Longueur_Melange_VDF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_Smago_VEF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_Wale_VEF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_Longueur_Melange_VEF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::controler_grandeurs_turbulentes(), Modele_turbulence_hyd_LES_selectif_mod_VDF::cutoff(), Modele_turbulence_hyd_LES_selectif_VDF::cutoff(), Modele_turbulence_hyd_LES_1elt_selectif_mod_VEF::cutoff(), Modele_turbulence_hyd_LES_Fst_sel_VEF::cutoff(), Modele_turbulence_hyd_Longueur_Melange_VEF::lire_distance_paroi(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::mettre_a_jour(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::stabilise_moyenne_6_points(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::stabilise_moyenne_euler_lagrange(), and Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::stabilise_moyenne_plans_paralleles().
le_dom_Cl_
TRUST_Ref< Domaine_Cl_dis_base *> Modele_turbulence_hyd_0_eq_base::le_dom_Cl_ protected
Referenced by associer(), Modele_turbulence_hyd_LES_VDF::calculer_fonction_structure(), Modele_turbulence_hyd_LES_VEF::calculer_fonction_structure(), Modele_turbulence_hyd_LES_axi_VDF::calculer_fonction_structure(), Modele_turbulence_hyd_LES_Wale_VDF::calculer_OP1_OP2(), Modele_turbulence_hyd_LES_Fst_VEF::calculer_racine(), Modele_turbulence_hyd_LES_Smago_VDF::calculer_S_barre(), Modele_turbulence_hyd_LES_Smago_VEF::calculer_S_barre(), Modele_turbulence_hyd_LES_Smago_filtre_VEF::calculer_S_barre(), Modele_turbulence_hyd_Longueur_Melange_VDF::calculer_Sij2(), Modele_turbulence_hyd_Longueur_Melange_VEF::calculer_Sij2(), Modele_turbulence_hyd_LES_VEF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_Wale_VEF::calculer_viscosite_turbulente(), and Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::mettre_a_jour().