TrioCFD: OpHessCentre2IJKScalar_double Class Reference
OpHessCentre2IJKScalar_double Class Reference
#include <OpHessCentre2IJKScalar.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
OpHessCentre2IJKScalar_double()
OpHessCentre2IJKScalar_double::OpHessCentre2IJKScalar_double ()
References Operateur_IJK_elem_diff_base_double::is_hess_, Operateur_IJK_elem_diff_base_double::set_uniform_lambda(), and unit_lambda_.
~OpHessCentre2IJKScalar_double()
OpHessCentre2IJKScalar_double::~OpHessCentre2IJKScalar_double ()
Member Function Documentation
cree_instance()
Objet_U * OpHessCentre2IJKScalar_double::cree_instance () static
taille_memoire()
unsigned OpHessCentre2IJKScalar_double::taille_memoire () const override virtual
Reimplemented from OpDiffUniformIJKScalar_double.
Reimplemented in OpHessFluxCentre2IJKScalar_double.
duplique()
int OpHessCentre2IJKScalar_double::duplique () const override virtual
Reimplemented from OpDiffUniformIJKScalar_double.
Reimplemented in OpHessFluxCentre2IJKScalar_double.
info()
const Type_info * OpHessCentre2IJKScalar_double::info () static
get_info()
const Type_info * OpHessCentre2IJKScalar_double::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from OpDiffUniformIJKScalar_double.
Reimplemented in OpHessFluxCentre2IJKScalar_double.
self_cast() [1/2]
OpHessCentre2IJKScalar_double & OpHessCentre2IJKScalar_double::self_cast (Objet_U & r) static
self_cast() [2/2]
const OpHessCentre2IJKScalar_double & OpHessCentre2IJKScalar_double::self_cast (const Objet_U & r) static
printOn()
Sortie & OpHessCentre2IJKScalar_double::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from OpDiffUniformIJKScalar_double.
Reimplemented in OpHessFluxCentre2IJKScalar_double.
readOn()
Entree & OpHessCentre2IJKScalar_double::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from OpDiffUniformIJKScalar_double.
Reimplemented in OpHessFluxCentre2IJKScalar_double.
calculer_hess()
void OpHessCentre2IJKScalar_double::calculer_hess (const IJK_Field_double & field, IJK_Field_vector3_double & result, const IJK_Field_local_double & boundary_flux_kmin, const IJK_Field_local_double & boundary_flux_kmax)
References Operateur_IJK_elem_diff_base_double::boundary_flux_kmax_, Operateur_IJK_elem_diff_base_double::boundary_flux_kmin_, Operateur_IJK_elem_diff_base_double::coeff_field_x_, Operateur_IJK_elem_diff_base_double::coeff_field_y_, Operateur_IJK_elem_diff_base_double::coeff_field_z_, Operateur_IJK_elem_base_double::compute_grad(), Operateur_IJK_elem_diff_base_double::input_field_, and Operateur_IJK_elem_diff_base_double::lambda_.
Referenced by OpHessFluxCentre2IJKScalar_double::calculer_hess_flux(), and IJK_Thermal_base::compute_temperature_hessian_diag_elem().
calculer_hess_xx()
void OpHessCentre2IJKScalar_double::calculer_hess_xx (const IJK_Field_double & field, IJK_Field_double & result, const IJK_Field_local_double & boundary_flux_kmin, const IJK_Field_local_double & boundary_flux_kmax)
References Operateur_IJK_elem_diff_base_double::boundary_flux_kmax_, Operateur_IJK_elem_diff_base_double::boundary_flux_kmin_, Operateur_IJK_elem_diff_base_double::coeff_field_x_, Operateur_IJK_elem_diff_base_double::coeff_field_y_, Operateur_IJK_elem_diff_base_double::coeff_field_z_, Operateur_IJK_elem_base_double::compute_grad_x(), Operateur_IJK_elem_diff_base_double::input_field_, and Operateur_IJK_elem_diff_base_double::lambda_.
calculer_hess_yy()
void OpHessCentre2IJKScalar_double::calculer_hess_yy (const IJK_Field_double & field, IJK_Field_double & result, const IJK_Field_local_double & boundary_flux_kmin, const IJK_Field_local_double & boundary_flux_kmax)
References Operateur_IJK_elem_diff_base_double::boundary_flux_kmax_, Operateur_IJK_elem_diff_base_double::boundary_flux_kmin_, Operateur_IJK_elem_diff_base_double::coeff_field_x_, Operateur_IJK_elem_diff_base_double::coeff_field_y_, Operateur_IJK_elem_diff_base_double::coeff_field_z_, Operateur_IJK_elem_base_double::compute_grad_y(), Operateur_IJK_elem_diff_base_double::input_field_, and Operateur_IJK_elem_diff_base_double::lambda_.
calculer_hess_zz()
void OpHessCentre2IJKScalar_double::calculer_hess_zz (const IJK_Field_double & field, IJK_Field_double & result, const IJK_Field_local_double & boundary_flux_kmin, const IJK_Field_local_double & boundary_flux_kmax)
References Operateur_IJK_elem_diff_base_double::boundary_flux_kmax_, Operateur_IJK_elem_diff_base_double::boundary_flux_kmin_, Operateur_IJK_elem_diff_base_double::coeff_field_x_, Operateur_IJK_elem_diff_base_double::coeff_field_y_, Operateur_IJK_elem_diff_base_double::coeff_field_z_, Operateur_IJK_elem_base_double::compute_grad_z(), Operateur_IJK_elem_diff_base_double::input_field_, and Operateur_IJK_elem_diff_base_double::lambda_.
fill_grad_field_x_y_()
void OpHessCentre2IJKScalar_double::fill_grad_field_x_y_ (IJK_Field_local_double & flux, IJK_Field_double & resu, int k, int dir) override protected virtual
Reimplemented from Operateur_IJK_elem_base_double.
Reimplemented in OpHessFluxCentre2IJKScalar_double.
References IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), and IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj().
fill_grad_field_z_()
void OpHessCentre2IJKScalar_double::fill_grad_field_z_ (IJK_Field_local_double & flux_min, IJK_Field_local_double & flux_max, IJK_Field_double & resu, int k) override protected virtual
Reimplemented from Operateur_IJK_elem_base_double.
Reimplemented in OpHessFluxCentre2IJKScalar_double.
References Operateur_IJK_elem_diff_base_double::channel_data_, Operateur_IJK_data_channel::get_delta_z(), Operateur_IJK_elem_diff_base_double::is_flux_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), and IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj().
Member Data Documentation
info_obj
const Type_info OpHessCentre2IJKScalar_double::info_obj static
unit_lambda_
const double OpHessCentre2IJKScalar_double::unit_lambda_ = 1. protected
Referenced by OpHessCentre2IJKScalar_double().