TrioCFD: Modele_turbulence_scal_Fluctuation_Temperature_W Class Reference
Modele_turbulence_scal_Fluctuation_Temperature_W Class Reference
#include <Modele_turbulence_scal_Fluctuation_Temperature_W.h>
Public Member Functions
const Type_info * get_info () const override
void imprimer (Sortie &) const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
int preparer_calcul () override
int reprendre (Entree &is) override
int sauvegarder (Sortie &os) const override
Public Member Functions inherited from Modele_turbulence_scal_base
virtual void associer (const Domaine_dis_base &, const Domaine_Cl_dis_base &)
void associer_eqn (const Equation_base &)
const Type_info * get_info () const override
virtual void imprimer (Sortie &) const
int limpr_nusselt (double, double, double, double) const
int lire_motcle_non_standard (const Motcle &, Entree &) override
Turbulence_paroi_scal_base & loi_paroi ()
const Turbulence_paroi_scal_base & loi_paroi () const
int loi_paroi_non_nulle () const
virtual int preparer_calcul ()
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Modele_turbulence_scal_Fluctuation_Temperature_W()
Modele_turbulence_scal_Fluctuation_Temperature_W::Modele_turbulence_scal_Fluctuation_Temperature_W ()
~Modele_turbulence_scal_Fluctuation_Temperature_W()
Modele_turbulence_scal_Fluctuation_Temperature_W::~Modele_turbulence_scal_Fluctuation_Temperature_W ()
Member Function Documentation
cree_instance()
Objet_U * Modele_turbulence_scal_Fluctuation_Temperature_W::cree_instance () static
taille_memoire()
unsigned Modele_turbulence_scal_Fluctuation_Temperature_W::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re.
duplique()
int Modele_turbulence_scal_Fluctuation_Temperature_W::duplique () const override virtual
Implements Objet_U.
Reimplemented in Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re.
info()
const Type_info * Modele_turbulence_scal_Fluctuation_Temperature_W::info () static
get_info()
const Type_info * Modele_turbulence_scal_Fluctuation_Temperature_W::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Modele_turbulence_scal_base.
Reimplemented in Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re.
self_cast() [1/2]
Modele_turbulence_scal_Fluctuation_Temperature_W & Modele_turbulence_scal_Fluctuation_Temperature_W::self_cast (Objet_U & r) static
self_cast() [2/2]
const Modele_turbulence_scal_Fluctuation_Temperature_W & Modele_turbulence_scal_Fluctuation_Temperature_W::self_cast (const Objet_U & r) static
printOn()
Sortie & Modele_turbulence_scal_Fluctuation_Temperature_W::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Modele_turbulence_scal_base.
Reimplemented in Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re.
References Objet_U::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Modele_turbulence_scal_Fluctuation_Temperature_W::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Modele_turbulence_scal_base.
Reimplemented in Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re.
References eqn, Modele_turbulence_scal_base::readOn(), Objet_U_ptr::typer(), and TRUST_Deriv< _CLASSE_ >::valeur().
completer()
void Modele_turbulence_scal_Fluctuation_Temperature_W::completer () override virtual
Complete le modele de turbulence: met a jour des references de l'objet.
Reimplemented from Modele_turbulence_scal_base.
Reimplemented in Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re.
References associer_viscosite_turbulente(), Probleme_base::equation(), Equation_base::get_modele(), Modele_turbulence_scal_base::mon_equation_, TRUST_Ref_Objet_U::valeur(), and Modele_turbulence_hyd_base::viscosite_turbulente().
preparer_calcul()
int Modele_turbulence_scal_Fluctuation_Temperature_W::preparer_calcul () override virtual
NE FAIT RIEN.
Returns
(int) renvoie toujours 1
Reimplemented from Modele_turbulence_scal_base.
Reimplemented in Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re.
References calculer_diffusivite_turbulente(), Modele_turbulence_scal_base::diffusivite_turbulente_, TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Modele_turbulence_scal_base::preparer_calcul(), and Champ_Don_base::valeurs().
initTimeStep()
bool Modele_turbulence_scal_Fluctuation_Temperature_W::initTimeStep (double dt) override virtual
A surcharger dans les classes derivees qui possedent une ou des equations Appeler preparer_pas_de_temps sur ces equations.
Reimplemented from Modele_turbulence_scal_base.
References eqn, and Equation_base::initTimeStep().
mettre_a_jour()
void Modele_turbulence_scal_Fluctuation_Temperature_W::mettre_a_jour (double temps) override virtual
Implements Modele_turbulence_scal_base.
Reimplemented in Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re.
References calculer_diffusivite_turbulente(), Modele_turbulence_scal_base::diffusivite_turbulente_, TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Schema_Temps_base::faire_un_pas_de_temps_eqn_base(), TRUST_Ref< _CLASSE_ >::valeur(), and Champ_Don_base::valeurs().
associer_viscosite_turbulente()
void Modele_turbulence_scal_Fluctuation_Temperature_W::associer_viscosite_turbulente (const Champ_Fonc_base & visc_turb)
References la_viscosite_turbulente.
Referenced by completer(), and Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re::completer().
Fluctu_Temperature() [1/2]
Champ_Inc_base & Modele_turbulence_scal_Fluctuation_Temperature_W::Fluctu_Temperature () inline virtual
Reimplemented in Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re.
Fluctu_Temperature() [2/2]
const Champ_Inc_base & Modele_turbulence_scal_Fluctuation_Temperature_W::Fluctu_Temperature () const inline virtual
Reimplemented in Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re.
equation_Fluctu() [1/2]
Transport_Fluctuation_Temperature_W & Modele_turbulence_scal_Fluctuation_Temperature_W::equation_Fluctu () inline virtual
Reimplemented in Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re.
References TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Source_Transport_K_Eps_Bas_Reynolds_anisotherme_W_VDF_Elem::ajouter_blocs(), reprendre(), and sauvegarder().
equation_Fluctu() [2/2]
const Transport_Fluctuation_Temperature_W & Modele_turbulence_scal_Fluctuation_Temperature_W::equation_Fluctu () const inline virtual
Reimplemented in Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re.
References TRUST_Ref< _CLASSE_ >::valeur().
sauvegarder()
int Modele_turbulence_scal_Fluctuation_Temperature_W::sauvegarder (Sortie & os) const override virtual
NE FAIT RIEN.
Parameters
(Sortie&) un flot de sortie
Returns
(int) renvoie toujours 1
Reimplemented from Modele_turbulence_scal_base.
References Modele_turbulence_scal_base::a_faire(), equation_Fluctu(), and Equation_base::sauvegarder().
reprendre()
int Modele_turbulence_scal_Fluctuation_Temperature_W::reprendre (Entree & is) override virtual
NE FAIT RIEN.
Parameters
(Entree&) un flot d'entree
Returns
(int) renvoie toujours 1
Reimplemented from Modele_turbulence_scal_base.
References equation_Fluctu(), TRUSTTab< _TYPE_, _SIZE_ >::jump(), Modele_turbulence_scal_base::mon_equation_, TRUST_Ref< _CLASSE_ >::non_nul(), Equation_base::reprendre(), and Modele_turbulence_scal_base::reprendre().
calculer_diffusivite_turbulente()
Champ_Fonc_base & Modele_turbulence_scal_Fluctuation_Temperature_W::calculer_diffusivite_turbulente () virtual
Reimplemented in Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re.
References Champ_base::changer_temps(), Modele_turbulence_scal_base::diffusivite_turbulente_, Modele_turbulence_hyd_K_Eps_Bas_Reynolds::eqn_transp_K_Eps(), Probleme_base::equation(), Process::exit(), Equation_base::get_modele(), Transport_K_Eps_base::inconnue(), la_viscosite_turbulente, Modele_turbulence_scal_base::mon_equation_, TRUSTVect< _TYPE_, _SIZE_ >::size(), Champ_base::temps(), TRUST_Ref_Objet_U::valeur(), Champ_Don_base::valeurs(), Champ_Inc_base::valeurs(), and Champ_Proto::valeurs().
Referenced by mettre_a_jour(), and preparer_calcul().
imprimer()
void Modele_turbulence_scal_Fluctuation_Temperature_W::imprimer (Sortie & os) const override virtual
Effectue l'impression si cela est necessaire.
Returns
renvoie toujours 1
Reimplemented from Modele_turbulence_scal_base.
set_param()
void Modele_turbulence_scal_Fluctuation_Temperature_W::set_param (Param & param) override virtual
Reimplemented from Modele_turbulence_scal_base.
Reimplemented in Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re.
References Param::ajouter_non_std().
lire_motcle_non_standard()
int Modele_turbulence_scal_Fluctuation_Temperature_W::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
< liste stockant tous les noms de frontiere du domaine
Reimplemented from Modele_turbulence_scal_base.
Reimplemented in Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re.
References Process::exit(), Motcles::search(), and TRUST_Ref< _CLASSE_ >::valeur().
get_champ()
const Champ_base & Modele_turbulence_scal_Fluctuation_Temperature_W::get_champ (const Motcle & nom) const override virtual
Reimplemented from Modele_turbulence_scal_base.
Reimplemented in Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re.
References eqn, Nom::getString(), Equation_base::has_champ(), and Modele_turbulence_scal_base::has_champ().
has_champ() [1/2]
bool Modele_turbulence_scal_Fluctuation_Temperature_W::has_champ (const Motcle & nom, TRUST_Ref< Champ_base * > & ref_champ) const override virtual
Reimplemented from Modele_turbulence_scal_base.
Reimplemented in Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re.
References eqn, Equation_base::has_champ(), and Modele_turbulence_scal_base::has_champ().
Referenced by Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re::get_champ(), and Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re::has_champ().
has_champ() [2/2]
bool Modele_turbulence_scal_Fluctuation_Temperature_W::has_champ (const Motcle & nom) const override virtual
Reimplemented from Modele_turbulence_scal_base.
Reimplemented in Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re.
References eqn, Equation_base::has_champ(), and Modele_turbulence_scal_base::has_champ().
get_noms_champs_postraitables()
void Modele_turbulence_scal_Fluctuation_Temperature_W::get_noms_champs_postraitables (Noms & nom, Option opt = NONE) const override virtual
Reimplemented from Modele_turbulence_scal_base.
Reimplemented in Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re.
References eqn, Equation_base::get_noms_champs_postraitables(), and Modele_turbulence_scal_base::get_noms_champs_postraitables().
Referenced by Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re::get_noms_champs_postraitables().
Member Data Documentation
info_obj
const Type_info Modele_turbulence_scal_Fluctuation_Temperature_W::info_obj static
eqn
TRUST_Deriv< Equation_base > Modele_turbulence_scal_Fluctuation_Temperature_W::eqn protected
Referenced by get_champ(), get_noms_champs_postraitables(), has_champ(), initTimeStep(), readOn(), and Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re::readOn().
la_viscosite_turbulente
TRUST_Ref< Champ_Fonc_base *> Modele_turbulence_scal_Fluctuation_Temperature_W::la_viscosite_turbulente protected
Referenced by associer_viscosite_turbulente(), calculer_diffusivite_turbulente(), and Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re::calculer_diffusivite_turbulente().