TrioCFD: Loi_paroi_base Class Reference
Loi_paroi_base Class Reference abstract
#include <Loi_paroi_base.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
Methodes implementees :
Constructor & Destructor Documentation
Loi_paroi_base()
Loi_paroi_base::Loi_paroi_base ()
~Loi_paroi_base()
Loi_paroi_base::~Loi_paroi_base () override
Member Function Documentation
info()
const Type_info * Loi_paroi_base::info () static
get_info()
const Type_info * Loi_paroi_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Correlation_base.
Reimplemented in Loi_paroi_adaptative, Loi_paroi_Ramstorfer, and Loi_paroi_log.
self_cast() [1/2]
Loi_paroi_base & Loi_paroi_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Loi_paroi_base & Loi_paroi_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Loi_paroi_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Correlation_base.
Reimplemented in Loi_paroi_adaptative, Loi_paroi_Ramstorfer, and Loi_paroi_log.
readOn()
Entree & Loi_paroi_base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Correlation_base.
Reimplemented in Loi_paroi_adaptative, Loi_paroi_Ramstorfer, and Loi_paroi_log.
References Param::ajouter(), eps_y_p_, Param::lire_avec_accolades_depuis(), and Objet_U::que_suis_je().
Referenced by Loi_paroi_Ramstorfer::readOn(), and Loi_paroi_log::readOn().
completer()
void Loi_paroi_base::completer () override virtual
Reimplemented from Correlation_base.
Reimplemented in Loi_paroi_Ramstorfer.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Process::exit(), Faces_a_calculer_, Correlation_base::pb_, Objet_U::que_suis_je(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUST_Deriv< _CLASSE_ >::valeur(), and valeurs_loi_paroi_.
Referenced by Loi_paroi_Ramstorfer::completer().
mettre_a_jour()
void Loi_paroi_base::mettre_a_jour (double temps) override virtual
Reimplemented from Correlation_base.
References calc_y_plus(), Process::exit(), Faces_a_calculer_, Correlation_base::pb_, tps_loc, and valeurs_loi_paroi_.
calc_y_plus()
virtual void Loi_paroi_base::calc_y_plus (const DoubleTab & vit, const DoubleTab & nu_visc) pure virtual
Implemented in Loi_paroi_adaptative, Loi_paroi_Ramstorfer, and Loi_paroi_log.
Referenced by mettre_a_jour().
get_y_plus()
double Loi_paroi_base::get_y_plus (int f) const inline
References valeurs_loi_paroi_.
get_utau()
double Loi_paroi_base::get_utau (int f) const inline
References valeurs_loi_paroi_.
Referenced by Flux_parietal_Kommajosyula::qp(), and Flux_parietal_adaptatif::qp().
get_tab()
DoubleTab & Loi_paroi_base::get_tab (std::string str) inline
References valeurs_loi_paroi_.
Referenced by Paroi_frottante_simple::me_calculer(), Cond_lim_k_complique_transition_flux_nul_demi::me_calculer(), Cond_lim_k_simple_flux_nul::me_calculer(), Cond_lim_omega_demi::me_calculer(), and Cond_lim_omega_dix::me_calculer().
Member Data Documentation
info_obj
const Type_info Loi_paroi_base::info_obj static
eps_y_p_
double Loi_paroi_base::eps_y_p_ = 1.e-4 protected
Referenced by Loi_paroi_Ramstorfer::calc_y_plus_loc(), Loi_paroi_log::calc_y_plus_loc(), and readOn().
y_p_min_
double Loi_paroi_base::y_p_min_ = 1.e-2 protected
Referenced by Loi_paroi_adaptative::calc_y_plus(), Loi_paroi_Ramstorfer::calc_y_plus(), and Loi_paroi_log::calc_y_plus().
Faces_a_calculer_
IntTab Loi_paroi_base::Faces_a_calculer_ protected
Referenced by Loi_paroi_adaptative::calc_y_plus(), Loi_paroi_Ramstorfer::calc_y_plus(), Loi_paroi_log::calc_y_plus(), completer(), and mettre_a_jour().
valeurs_loi_paroi_
std::map<std::string, DoubleTab> Loi_paroi_base::valeurs_loi_paroi_ protected
Referenced by Loi_paroi_adaptative::calc_y_plus(), Loi_paroi_Ramstorfer::calc_y_plus(), Loi_paroi_log::calc_y_plus(), completer(), get_tab(), get_utau(), get_y_plus(), and mettre_a_jour().
tps_loc
double Loi_paroi_base::tps_loc = -1.e8 protected
Referenced by mettre_a_jour().