TrioCFD: Pb_Hydraulique_IBM Class Reference
Pb_Hydraulique_IBM Class Reference
#include <Pb_Hydraulique_IBM.h>
Public Member Functions
void associer_milieu_base (const Milieu_base &) override
const Type_info * get_info () const override
Public Member Functions inherited from Pb_Fluide_base
const Type_info * get_info () const override
Public Member Functions inherited from Probleme_base
void abortTimeStep () override
int associer_ (Objet_U &) override
virtual void associer_domaine (const Domaine &)
virtual void associer_milieu_base (const Milieu_base &)
virtual void associer_sch_tps_base (const Schema_Temps_base &)
virtual double calculer_pas_de_temps () const
virtual void completer ()
double computeTimeStep (bool &stop) const override
const Discretisation_base & discretisation () const
virtual void discretiser (Discretisation_base &)
Domaine & domaine ()
const Domaine & domaine () const
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
Equation_base & equation (const Nom &)
const Equation_base & equation (const Nom &) const
TRUST_Ref< Field_base * > findInputField (const Nom &name) const override
virtual void finir ()
double futureTime () const override
const Type_info * get_info () const override
void getInputFieldsNames (Noms &noms) const override
void getOutputFieldsNames (Noms &noms) const override
virtual void imprimer (Sortie &os) const
void initialize () override
bool initTimeStep (double dt) override
bool isStationary () const override
bool iterateTimeStep (bool &converged) override
int limpr () const override
int lsauv () const override
virtual void mettre_a_jour (double temps)
virtual Milieu_base & milieu ()
virtual const Milieu_base & milieu () const
int postraiter (int force=1) override
double presentTime () const override
int reprendre (Entree &) override
void resetTime (double time) override
int sauvegarder (Sortie &) const override
Schema_Temps_base & schema_temps ()
const Schema_Temps_base & schema_temps () const
void terminate () override
bool updateGivenFields () override
void validateTimeStep () override
virtual int verifier ()
Public Member Functions inherited from Probleme_U
virtual void abortTimeStep ()
virtual double computeTimeStep (bool &stop) const
virtual TRUST_Ref< Field_base * > findInputField (const Nom &name) const
virtual double futureTime () const
const Type_info * get_info () const override
virtual void getInputFieldsNames (Noms &noms) const
virtual void getOutputFieldsNames (Noms &noms) const
virtual void initialize ()
virtual bool initTimeStep (double dt)
virtual bool isStationary () const
virtual bool iterateTimeStep (bool &converged)
const Nom & le_nom () const override
void nommer (const Nom &name) override
virtual int postraiter (int force=1)
virtual double presentTime () const
virtual void resetTime (double time)
virtual bool run ()
virtual bool runUntil (double time)
virtual void terminate ()
virtual bool updateGivenFields ()
virtual void validateTimeStep ()
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Pb_Fluide_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Pb_Hydraulique_IBM()
Pb_Hydraulique_IBM::Pb_Hydraulique_IBM ()
~Pb_Hydraulique_IBM()
Pb_Hydraulique_IBM::~Pb_Hydraulique_IBM ()
Member Function Documentation
cree_instance()
Objet_U * Pb_Hydraulique_IBM::cree_instance () static
taille_memoire()
unsigned Pb_Hydraulique_IBM::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Pb_Thermohydraulique_IBM.
duplique()
int Pb_Hydraulique_IBM::duplique () const override virtual
Implements Objet_U.
Reimplemented in Pb_Thermohydraulique_IBM.
info()
const Type_info * Pb_Hydraulique_IBM::info () static
get_info()
const Type_info * Pb_Hydraulique_IBM::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Probleme_base.
Reimplemented in Pb_Thermohydraulique_IBM.
self_cast() [1/2]
Pb_Hydraulique_IBM & Pb_Hydraulique_IBM::self_cast (Objet_U & r) static
self_cast() [2/2]
const Pb_Hydraulique_IBM & Pb_Hydraulique_IBM::self_cast (const Objet_U & r) static
printOn()
Sortie & Pb_Hydraulique_IBM::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Probleme_base.
Reimplemented in Pb_Thermohydraulique_IBM.
References Pb_Fluide_base::printOn().
Referenced by Pb_Thermohydraulique_IBM::printOn().
readOn()
Entree & Pb_Hydraulique_IBM::readOn (Entree & is) override protected virtual
Lecture d'un probleme dans un flot d'entree, et ouverture du flot de sauvegarde.
Format: { nom_milieu bloc de lecture d'un milieu nom_equation bloc de lecture d'une equation Postraitement bloc de lecture postraitement reprise | sauvegarde | sauvegarde_simple formatte | binaire | pdi nom_de_fichier } L'option sauvegarde_simple permet de sauver le probleme dans le fichier choisi en ecrasant a chaque fois les sauvegardes precedentes : cela permet d'economiser de la place disque.
Parameters
(Entree& is) flot d'entree
Returns
(Entree&) le flot d'entre modifie
Exceptions
pas d'accolade ouvrante en debut de format
mot clef "Postraitement" n'est pas la
format de sauvegarde doit etre "binaire" ou "formatte"
pas d'accolade fermante en fin de jeu de donnee
Reimplemented from Probleme_base.
Reimplemented in Pb_Thermohydraulique_IBM.
References Pb_Fluide_base::readOn().
Referenced by Pb_Thermohydraulique_IBM::readOn().
nombre_d_equations()
int Pb_Hydraulique_IBM::nombre_d_equations () const inline override virtual
Implements Probleme_base.
Reimplemented in Pb_Thermohydraulique_IBM.
References Probleme_base::eq_opt_, and TRUST_List< _CLASSE_ >::size().
equation() [1/2]
const Equation_base & Pb_Hydraulique_IBM::equation (int i) const override virtual
Implements Probleme_base.
Reimplemented in Pb_Thermohydraulique_IBM.
References eq_hydraulique_, Probleme_base::eq_opt_, Process::exit(), and TRUST_List< _CLASSE_ >::size().
equation() [2/2]
Equation_base & Pb_Hydraulique_IBM::equation (int i) override virtual
Implements Probleme_base.
Reimplemented in Pb_Thermohydraulique_IBM.
References eq_hydraulique_, Probleme_base::eq_opt_, Process::exit(), and TRUST_List< _CLASSE_ >::size().
associer_milieu_base()
void Pb_Hydraulique_IBM::associer_milieu_base (const Milieu_base & mil) override virtual
Associe un milieu physique aux equations du probleme.
Choix du milieu physique.
Parameters
(Milieu_base& mil) le milieu a associer (Solide, Fluide Incompressible ...)
Reimplemented from Probleme_base.
Reimplemented in Pb_Thermohydraulique_IBM.
References Navier_Stokes_std::associer_milieu_base(), eq_hydraulique_, Process::exit(), and Objet_U::que_suis_je().
Referenced by Pb_Thermohydraulique_IBM::associer_milieu_base().
Member Data Documentation
info_obj
const Type_info Pb_Hydraulique_IBM::info_obj static
eq_hydraulique_
Navier_Stokes_IBM Pb_Hydraulique_IBM::eq_hydraulique_ protected
Referenced by associer_milieu_base(), equation(), Pb_Thermohydraulique_IBM::equation(), and Pb_Thermohydraulique_IBM::verifier().