TrioCFD: Imprimer_Fichiers_RANS_VDF Class Reference
Imprimer_Fichiers_RANS_VDF Class Reference
#include <Imprimer_Fichiers_RANS_VDF.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Interprete
static Objet_U & objet (const Nom &)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Imprimer_Fichiers_RANS_VDF()
Imprimer_Fichiers_RANS_VDF::Imprimer_Fichiers_RANS_VDF ()
~Imprimer_Fichiers_RANS_VDF()
Imprimer_Fichiers_RANS_VDF::~Imprimer_Fichiers_RANS_VDF ()
Member Function Documentation
cree_instance()
Objet_U * Imprimer_Fichiers_RANS_VDF::cree_instance () static
taille_memoire()
unsigned Imprimer_Fichiers_RANS_VDF::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Imprimer_Fichiers_RANS_VDF::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Imprimer_Fichiers_RANS_VDF::info () static
get_info()
const Type_info * Imprimer_Fichiers_RANS_VDF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Interprete.
self_cast() [1/2]
Imprimer_Fichiers_RANS_VDF & Imprimer_Fichiers_RANS_VDF::self_cast (Objet_U & r) static
self_cast() [2/2]
const Imprimer_Fichiers_RANS_VDF & Imprimer_Fichiers_RANS_VDF::self_cast (const Objet_U & r) static
printOn()
Sortie & Imprimer_Fichiers_RANS_VDF::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Interprete.
References Interprete::printOn().
readOn()
Entree & Imprimer_Fichiers_RANS_VDF::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Interprete.
References Interprete::readOn().
interpreter()
Entree & Imprimer_Fichiers_RANS_VDF::interpreter (Entree & is) override virtual
Implements Interprete.
References Equation_base::domaine_dis(), Probleme_base::equation(), Process::exit(), Equation_base::inconnue(), Domaine_dis_base::nb_elem_tot(), Domaine_VF::nb_faces_tot(), Interprete::objet(), Objet_U::que_suis_je(), and Champ_Inc_base::valeurs().
Member Data Documentation
info_obj
const Type_info Imprimer_Fichiers_RANS_VDF::info_obj static