TrioCFD: Source_base Class Reference
Source_base Class Reference abstract
#include <Source_base.h>
Public Member Functions
virtual int a_pour_Champ_Fonc (const Motcle &mot, TRUST_Ref< Champ_base * > &ch_ref) const
virtual void associer_champ_rho (const Champ_base &champ_rho)
virtual void completer ()
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
virtual void resetTime (double t)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
equation. Cette classe est la base de la hierarchie des Sources, une
source est un morceau d'equation donc Source_base herite de MorEqn.
Constructor & Destructor Documentation
Source_base()
Source_base::Source_base ()
~Source_base()
Source_base::~Source_base () override
Member Function Documentation
info()
const Type_info * Source_base::info () static
get_info()
const Type_info * Source_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
Reimplemented in Coalescence_bulles_1groupe_PolyMAC_P0, Coalescence_bulles_2groupes_PolyMAC_P0, Correction_Lubchenko_PolyMAC_P0, Flux_2groupes_PolyMAC_P0, Injection_masse_PolyMAC_P0, Injection_QDM_nulle_PolyMAC_P0, Nucleation_paroi_PolyMAC_P0, Rupture_bulles_1groupe_PolyMAC_P0, Rupture_bulles_2groupes_PolyMAC_P0, Variation_rho, Source_injection_masse_base, Source_injection_QDM_base, Injection_QDM_nulle_VDF, Diffusion_croisee_echelle_temp_taux_diss_turb_PolyMAC_P0, Diffusion_supplementaire_echelle_temp_turb_PolyMAC_P0, Dissipation_echelle_temp_taux_diss_turb_PolyMAC_P0, Dissipation_energie_cin_turb_PolyMAC_P0, Dissipation_WIT_PolyMAC_P0, Production_echelle_temp_taux_diss_turb_PolyMAC_P0, Production_energie_cin_turb_PolyMAC_P0, Production_HZDR_PolyMAC_P0, Production_WIT_PolyMAC_P0, Source_BIF_PolyMAC_P0, Source_Dissipation_HZDR_PolyMAC_P0, Source_Diffusion_croisee_echelle_temp_taux_diss_turb, Source_Diffusion_supplementaire_echelle_temp_turb, Source_Dissipation_echelle_temp_taux_diss_turb, Source_Dissipation_energie_cin_turb, Source_Production_echelle_temp_taux_diss_turb, Source_Production_energie_cin_turb, Diffusion_croisee_echelle_temp_taux_diss_turb_VDF, Diffusion_supplementaire_echelle_temp_turb_VDF, Dissipation_echelle_temp_taux_diss_turb_VDF, Dissipation_energie_cin_turb_VDF, Production_echelle_temp_taux_diss_turb_VDF, Production_energie_cin_turb_VDF, Source_Action_Particules, Source_Flottabilite, Source_Masse_Ajoutee, Source_Portance, Source_Reaction_Particules, Source_Trainee, Source_Reaction_Particules_VDF, Source_Reaction_Particules_VEF, SourceFiltree_FT_disc_VEF_P1NC, Terme_Source_Constituant_Vortex_VEF_Face, Source_Con_Phase_field_base, Source_Con_Phase_field, Source_Gravite_PF_VDF, Source_Qdm_VDF_Phase_field, Source_rayo_semi_transp_base, Source_rayo_semi_transp_QC_VDF_P0_VDF, Source_rayo_semi_transp_VDF_P0_VDF, Source_rayo_semi_transp_QC_VEF_P1NC, Source_rayo_semi_transp_VEF_P1NC, Terme_Boussinesq_Sensibility_VEFPreP1B_Face, Tenseur_Reynolds_Externe_VDF_Face, Source_Transport_Bas_Reynolds_VDF_Elem_base, Source_Transport_K_Omega_VDF_Elem_base, Source_Transport_Realisable_VDF_Elem_base, Source_Transport_VDF_Elem_base, Source_Transport_Eps_aniso_therm_concen_VDF_Elem, Source_Transport_Eps_anisotherme_VDF_Elem, Source_Transport_Eps_concen_VDF_Elem, Source_Transport_Eps_Realisable_aniso_concen_VDF_Elem, Source_Transport_Eps_Realisable_aniso_therm_concen_VDF_Elem, Source_Transport_Eps_Realisable_anisotherme_VDF_Elem, Source_Transport_Eps_Realisable_VDF_Elem, Source_Transport_Eps_VDF_Elem, Source_Transport_K_aniso_therm_concen_VDF_Elem, Source_Transport_K_anisotherme_VDF_Elem, Source_Transport_K_concen_VDF_Elem, Source_Transport_K_Realisable_aniso_concen_VDF_Elem, Source_Transport_K_Realisable_aniso_therm_concen_VDF_Elem, Source_Transport_K_Realisable_anisotherme_VDF_Elem, Source_Transport_K_Realisable_VDF_Elem, Source_Transport_K_VDF_Elem, Source_Transport_K_Eps_aniso_therm_concen_VDF_Elem, Source_Transport_K_Eps_anisotherme_VDF_Elem, Source_Transport_K_Eps_Bas_Reynolds_aniso_therm_concen_VDF_Elem, Source_Transport_K_Eps_Bas_Reynolds_anisotherme_VDF_Elem, Source_Transport_K_Eps_Bas_Reynolds_anisotherme_QC_VDF_Elem, Source_Transport_K_Eps_Bas_Reynolds_anisotherme_W_VDF_Elem, Source_Transport_K_Eps_Bas_Reynolds_VDF_Elem, Source_Transport_K_Eps_Bas_Reynolds_W_VDF_Elem, Source_Transport_K_Eps_concen_VDF_Elem, Source_Transport_K_Eps_Realisable_aniso_concen_VDF_Elem, Source_Transport_K_Eps_Realisable_aniso_therm_concen_VDF_Elem, Source_Transport_K_Eps_Realisable_anisotherme_VDF_Elem, Source_Transport_K_Eps_Realisable_VDF_Elem, Source_Transport_K_Eps_VDF_Elem, Source_Transport_K_Omega_VDF_Elem, Source_Transport_Fluctuation_Temperature_VDF_Elem, Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem, Source_Transport_Fluctuation_Temperature_W_VDF_Elem, Source_Transport_Flux_Chaleur_Turbulente_VDF_Face, Source_Transport_K_KEps_anisotherme_VDF_Elem, Source_Transport_K_KEps_VDF_Elem, Source_Transport_K_Omega_VEF_Face_base, Source_Transport_Realisable_VEF_Face_base, Source_Transport_VEF_Face_base, Source_Transport_Eps_aniso_concen_VEF_Face, Source_Transport_Eps_aniso_therm_concen_VEF_Face, Source_Transport_Eps_anisotherme_VEF_Face, Source_Transport_Eps_Realisable_aniso_concen_VEF_Face, Source_Transport_Eps_Realisable_aniso_therm_concen_VEF_Face, Source_Transport_Eps_Realisable_anisotherme_VEF_Face, Source_Transport_Eps_Realisable_VEF_Face, Source_Transport_Eps_VEF_Face, Source_Transport_K_aniso_concen_VEF_Face, Source_Transport_K_aniso_therm_concen_VEF_Face, Source_Transport_K_anisotherme_VEF_Face, Source_Transport_K_Realisable_aniso_concen_VEF_Face, Source_Transport_K_Realisable_aniso_therm_concen_VEF_Face, Source_Transport_K_Realisable_anisotherme_VEF_Face, Source_Transport_K_Realisable_VEF_Face, Source_Transport_K_VEF_Face, Source_Transport_K_Eps_aniso_concen_VEF_Face, Source_Transport_K_Eps_aniso_therm_concen_VEF_Face, Source_Transport_K_Eps_anisotherme_VEF_Face, Source_Transport_K_Eps_Bas_Reynolds_anisotherme_VEF_Face, Source_Transport_K_Eps_Bas_Reynolds_VEF_Face, Source_Transport_K_Eps_Realisable_aniso_concen_VEF_Face, Source_Transport_K_Eps_Realisable_aniso_therm_concen_VEF_Face, Source_Transport_K_Eps_Realisable_anisotherme_VEF_Face, Source_Transport_K_Eps_Realisable_VEF_Face, Source_Transport_K_Eps_VEF_Face, Source_Transport_K_Omega_VEF_Face, Source_Robin, Source_Robin_Scalaire, Source_dep_inco_base, Source_Generique_base, Source_Generique_P0_Elem, Correction_Antal_PolyMAC_P0, Correction_Tomiyama_PolyMAC_P0, Dispersion_bulles_PolyMAC_P0, Flux_interfacial_PolyMAC_P0P1NC, Force_Tchen_PolyMAC_P0, Frottement_interfacial_PolyMAC_P0, Portance_interfaciale_PolyMAC_P0, Travail_pression_PolyMAC_P0P1NC, DP_Impose_PolyMAC_Face, Perte_Charge_Anisotrope_PolyMAC_Face, Perte_Charge_Anisotrope_PolyMAC_P0P1NC_Face, Perte_Charge_Circulaire_PolyMAC_Face, Perte_Charge_Circulaire_PolyMAC_P0P1NC_Face, Perte_Charge_Directionnelle_PolyMAC_Face, Perte_Charge_Directionnelle_PolyMAC_P0P1NC_Face, Perte_Charge_Isotrope_PolyMAC_Face, Perte_Charge_Isotrope_PolyMAC_P0P1NC_Face, Perte_Charge_PolyMAC, Perte_Charge_PolyMAC_Face, Perte_Charge_Singuliere_PolyMAC_Face, Perte_Charge_Singuliere_PolyMAC_P0P1NC_Face, Source_Generique_Face_PolyMAC, Source_Generique_Face_PolyMAC_P0P1NC, Terme_Puissance_Thermique_PolyMAC_base, Terme_Puissance_Thermique_PolyMAC_Elem, Terme_Source_Constituant_PolyMAC_Elem, Terme_Source_PolyMAC_base, Terme_Boussinesq_PolyMAC_Face, Terme_Puissance_Thermique_Echange_Impose_Elem_PolyMAC, Terme_Source_Decroissance_Radioactive_Elem_PolyMAC, Terme_Source_Qdm_Face_PolyMAC, Terme_Source_Qdm_Face_PolyMAC_P0P1NC, Source_Chaleur_Fluide_Dilatable_base, Source_Gravite_Fluide_Dilatable_base, Source_QC_Chaleur, Source_QC_Chaleur_Verif, Source_QC_Chaleur_Verif_VEF, Source_QC_Chaleur_Verif_VEF_P1NC, Source_QC_QDM_Gen, Source_WC_Chaleur, Perte_Charge_Gen, Terme_Boussinesq_base, Terme_Puissance_Thermique_Echange_Impose_Elem_base, Terme_Source_Acceleration, Terme_Source_Canal_perio, Terme_Source_Coriolis_base, Source_Dispersion_bulles_base, Source_Flux_interfacial_base, Source_Force_Tchen_base, Source_Frottement_interfacial_base, Source_Portance_interfaciale_base, Source_Travail_pression_Elem_base, Sources_Multiphase_base, Source_Neutronique, Correction_Antal_VDF, Dispersion_bulles_VDF, Flux_interfacial_VDF, Force_Tchen_VDF, Frottement_interfacial_VDF, Portance_interfaciale_VDF, Travail_pression_VDF, Terme_Source_Canal_perio_VDF_Face, Terme_Source_Canal_perio_QC_VDF_Face, Terme_Source_Canal_perio_VDF_P0, Terme_Source_Canal_RANS_LES_VDF_Elem, Terme_Source_Canal_RANS_LES_VDF_Face, Source_QC_Chaleur_VDF, Source_QC_Gravite_VDF, Acceleration_QC_VDF_Face, Source_qdm_QC_VDF_Face, Perte_Charge_Reguliere_QC_VDF_Face, Perte_Charge_Singuliere_QC_VDF_Face, Darcy_QC_VDF_Face, Forchheimer_QC_VDF_Face, Source_WC_Chaleur_VDF, Source_WC_Gravite_VDF, Force_Centrifuge_VDF_Face_Axi, Perte_Charge_Anisotrope_VDF_Face, Perte_Charge_Circulaire_VDF_Face, Perte_Charge_Directionnelle_VDF_Face, Perte_Charge_Isotrope_VDF_Face, Perte_Charge_Reguliere_VDF_Face, Perte_Charge_Singuliere_VDF_Face, Perte_Charge_VDF_base, Perte_Charge_VDF_Face, Source_Generique_VDF_Face, Source_Darcy_VDF_Face, Source_Dirac_VDF_Elem, Source_Echange_Th_VDF, Source_Forchheimer_VDF_Face, Source_Neutronique_VDF, Terme_Gravite_VDF_Face, Terme_Puissance_Thermique_QC_VDF_Elem, Terme_Puissance_Thermique_VDF_base, Terme_Puissance_Thermique_VDF_Elem, Terme_Source_Constituant_VDF_Elem, Terme_Source_VDF_base, Terme_Boussinesq_VDF_Face, Terme_Puissance_Thermique_Echange_Impose_P0_VDF, Terme_Source_Acceleration_VDF_Face, Terme_Source_Coriolis_VDF_Face, Terme_Source_Coriolis_QC_VDF_Face, Terme_Source_inc_base, Terme_Source_inc_th_VDF_Face, Terme_Source_inc_VDF_Face, Terme_Source_Qdm_VDF_Face, Terme_Source_Solide_SWIFT_VDF, Terme_Source_Canal_perio_VEF_P1NC, Terme_Source_Canal_perio_QC_VEF_P1NC, Terme_Source_Canal_RANS_LES_VEF_Face, Source_QC_Chaleur_VEF, Source_QC_Gravite_VEF, Acceleration_QC_VEF_P1NC, Perte_Charge_Circulaire_QC_VEF_P1NC, Perte_Charge_Anisotrope_QC_VEF_P1NC, Perte_Charge_Directionnelle_QC_VEF_P1NC, Perte_Charge_Isotrope_QC_VEF_P1NC, Perte_Charge_Reguliere_QC_VEF_P1NC, Perte_Charge_Singuliere_QC_VEF_P1NC, Source_qdm_QC_VEF_P1NC, Darcy_QC_VEF_P1NC, Forchheimer_QC_VEF_P1NC, Source_WC_Chaleur_VEF, Source_WC_Gravite_VEF, DP_Impose_VEF_Face, Perte_Charge_Anisotrope_VEF_P1NC, Perte_Charge_Circulaire_VEF_P1NC, Perte_Charge_Directionnelle_VEF_P1NC, Perte_Charge_Isotrope_VEF_P1NC, Perte_Charge_Reguliere_VEF_P1NC, Perte_Charge_Singuliere_VEF_Face, Perte_Charge_VEF, Perte_Charge_VEF_Face, Source_Generique_VEF, Source_Darcy_VEF_Face, Source_Dirac_VEF_Face, Source_Forchheimer_VEF_Face, Terme_Puissance_Thermique_QC_VEF_Face, Terme_Puissance_Thermique_VEF_base, Terme_Puissance_Thermique_VEF_Face, Terme_Source_Constituant_VEF_Face, Terme_Source_VEF_base, Terme_Boussinesq_VEF_Face, Terme_Boussinesq_VEFPreP1B_Face, Terme_Puissance_Thermique_Echange_Impose_VEF_Face, Terme_Source_Acceleration_VEF_Face, Terme_Source_Decroissance_Radioactive_VEF_Face, Terme_Source_Qdm_lambdaup_VEF_Face, Terme_Source_Qdm_VEF_Face, Terme_Source_Rappel_T_VEF_Face, and Terme_Source_Th_TdivU_VEF_Face.
self_cast() [1/2]
Source_base & Source_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Source_base & Source_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Source_base::printOn (Sortie & os) const override protected virtual
DOES NOTHING - to override in derived classes.
Imprime la source sur un flot de sortie.
Parameters
(Sortie& os) le flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Objet_U.
Reimplemented in Coalescence_bulles_1groupe_PolyMAC_P0, Coalescence_bulles_2groupes_PolyMAC_P0, Correction_Lubchenko_PolyMAC_P0, Flux_2groupes_PolyMAC_P0, Injection_masse_PolyMAC_P0, Injection_QDM_nulle_PolyMAC_P0, Nucleation_paroi_PolyMAC_P0, Rupture_bulles_1groupe_PolyMAC_P0, Rupture_bulles_2groupes_PolyMAC_P0, Variation_rho, Source_injection_masse_base, Source_injection_QDM_base, Injection_QDM_nulle_VDF, Diffusion_croisee_echelle_temp_taux_diss_turb_PolyMAC_P0, Diffusion_supplementaire_echelle_temp_turb_PolyMAC_P0, Dissipation_echelle_temp_taux_diss_turb_PolyMAC_P0, Dissipation_energie_cin_turb_PolyMAC_P0, Dissipation_WIT_PolyMAC_P0, Production_echelle_temp_taux_diss_turb_PolyMAC_P0, Production_energie_cin_turb_PolyMAC_P0, Production_HZDR_PolyMAC_P0, Production_WIT_PolyMAC_P0, Source_BIF_PolyMAC_P0, Source_Dissipation_HZDR_PolyMAC_P0, Source_Diffusion_croisee_echelle_temp_taux_diss_turb, Source_Diffusion_supplementaire_echelle_temp_turb, Source_Dissipation_echelle_temp_taux_diss_turb, Source_Dissipation_energie_cin_turb, Source_Production_echelle_temp_taux_diss_turb, Source_Production_energie_cin_turb, Diffusion_croisee_echelle_temp_taux_diss_turb_VDF, Diffusion_supplementaire_echelle_temp_turb_VDF, Dissipation_echelle_temp_taux_diss_turb_VDF, Dissipation_energie_cin_turb_VDF, Production_echelle_temp_taux_diss_turb_VDF, Production_energie_cin_turb_VDF, Source_Action_Particules, Source_Flottabilite, Source_Masse_Ajoutee, Source_Portance, Source_Reaction_Particules, Source_Trainee, Source_Reaction_Particules_VDF, Source_Reaction_Particules_VEF, SourceFiltree_FT_disc_VEF_P1NC, Terme_Source_Constituant_Vortex_VEF_Face, Source_Con_Phase_field_base, Source_Con_Phase_field, Source_Gravite_PF_VDF, Source_Qdm_VDF_Phase_field, Source_rayo_semi_transp_base, Source_rayo_semi_transp_QC_VDF_P0_VDF, Source_rayo_semi_transp_VDF_P0_VDF, Source_rayo_semi_transp_QC_VEF_P1NC, Source_rayo_semi_transp_VEF_P1NC, Terme_Boussinesq_Sensibility_VEFPreP1B_Face, Tenseur_Reynolds_Externe_VDF_Face, Source_Transport_Bas_Reynolds_VDF_Elem_base, Source_Transport_K_Omega_VDF_Elem_base, Source_Transport_Realisable_VDF_Elem_base, Source_Transport_VDF_Elem_base, Source_Transport_Eps_aniso_therm_concen_VDF_Elem, Source_Transport_Eps_anisotherme_VDF_Elem, Source_Transport_Eps_concen_VDF_Elem, Source_Transport_Eps_Realisable_aniso_concen_VDF_Elem, Source_Transport_Eps_Realisable_aniso_therm_concen_VDF_Elem, Source_Transport_Eps_Realisable_anisotherme_VDF_Elem, Source_Transport_Eps_Realisable_VDF_Elem, Source_Transport_Eps_VDF_Elem, Source_Transport_K_aniso_therm_concen_VDF_Elem, Source_Transport_K_anisotherme_VDF_Elem, Source_Transport_K_concen_VDF_Elem, Source_Transport_K_Realisable_aniso_concen_VDF_Elem, Source_Transport_K_Realisable_aniso_therm_concen_VDF_Elem, Source_Transport_K_Realisable_anisotherme_VDF_Elem, Source_Transport_K_Realisable_VDF_Elem, Source_Transport_K_VDF_Elem, Source_Transport_K_Eps_aniso_therm_concen_VDF_Elem, Source_Transport_K_Eps_anisotherme_VDF_Elem, Source_Transport_K_Eps_Bas_Reynolds_aniso_therm_concen_VDF_Elem, Source_Transport_K_Eps_Bas_Reynolds_anisotherme_VDF_Elem, Source_Transport_K_Eps_Bas_Reynolds_anisotherme_QC_VDF_Elem, Source_Transport_K_Eps_Bas_Reynolds_anisotherme_W_VDF_Elem, Source_Transport_K_Eps_Bas_Reynolds_VDF_Elem, Source_Transport_K_Eps_Bas_Reynolds_W_VDF_Elem, Source_Transport_K_Eps_concen_VDF_Elem, Source_Transport_K_Eps_Realisable_aniso_concen_VDF_Elem, Source_Transport_K_Eps_Realisable_aniso_therm_concen_VDF_Elem, Source_Transport_K_Eps_Realisable_anisotherme_VDF_Elem, Source_Transport_K_Eps_Realisable_VDF_Elem, Source_Transport_K_Eps_VDF_Elem, Source_Transport_K_Omega_VDF_Elem, Source_Transport_Fluctuation_Temperature_VDF_Elem, Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem, Source_Transport_Fluctuation_Temperature_W_VDF_Elem, Source_Transport_Flux_Chaleur_Turbulente_VDF_Face, Source_Transport_K_KEps_anisotherme_VDF_Elem, Source_Transport_K_KEps_VDF_Elem, Source_Transport_K_Omega_VEF_Face_base, Source_Transport_Realisable_VEF_Face_base, Source_Transport_VEF_Face_base, Source_Transport_Eps_aniso_concen_VEF_Face, Source_Transport_Eps_aniso_therm_concen_VEF_Face, Source_Transport_Eps_anisotherme_VEF_Face, Source_Transport_Eps_Realisable_aniso_concen_VEF_Face, Source_Transport_Eps_Realisable_aniso_therm_concen_VEF_Face, Source_Transport_Eps_Realisable_anisotherme_VEF_Face, Source_Transport_Eps_Realisable_VEF_Face, Source_Transport_Eps_VEF_Face, Source_Transport_K_aniso_concen_VEF_Face, Source_Transport_K_aniso_therm_concen_VEF_Face, Source_Transport_K_anisotherme_VEF_Face, Source_Transport_K_Realisable_aniso_concen_VEF_Face, Source_Transport_K_Realisable_aniso_therm_concen_VEF_Face, Source_Transport_K_Realisable_anisotherme_VEF_Face, Source_Transport_K_Realisable_VEF_Face, Source_Transport_K_VEF_Face, Source_Transport_K_Eps_aniso_concen_VEF_Face, Source_Transport_K_Eps_aniso_therm_concen_VEF_Face, Source_Transport_K_Eps_anisotherme_VEF_Face, Source_Transport_K_Eps_Bas_Reynolds_anisotherme_VEF_Face, Source_Transport_K_Eps_Bas_Reynolds_VEF_Face, Source_Transport_K_Eps_Realisable_aniso_concen_VEF_Face, Source_Transport_K_Eps_Realisable_aniso_therm_concen_VEF_Face, Source_Transport_K_Eps_Realisable_anisotherme_VEF_Face, Source_Transport_K_Eps_Realisable_VEF_Face, Source_Transport_K_Eps_VEF_Face, Source_Transport_K_Omega_VEF_Face, Source_Robin, Source_Robin_Scalaire, Source_dep_inco_base, Source_Generique_base, Source_Generique_P0_Elem, Correction_Antal_PolyMAC_P0, Correction_Tomiyama_PolyMAC_P0, Dispersion_bulles_PolyMAC_P0, Flux_interfacial_PolyMAC_P0P1NC, Force_Tchen_PolyMAC_P0, Frottement_interfacial_PolyMAC_P0, Portance_interfaciale_PolyMAC_P0, Travail_pression_PolyMAC_P0P1NC, DP_Impose_PolyMAC_Face, Perte_Charge_Anisotrope_PolyMAC_Face, Perte_Charge_Anisotrope_PolyMAC_P0P1NC_Face, Perte_Charge_Circulaire_PolyMAC_Face, Perte_Charge_Circulaire_PolyMAC_P0P1NC_Face, Perte_Charge_Directionnelle_PolyMAC_Face, Perte_Charge_Directionnelle_PolyMAC_P0P1NC_Face, Perte_Charge_Isotrope_PolyMAC_Face, Perte_Charge_Isotrope_PolyMAC_P0P1NC_Face, Perte_Charge_PolyMAC, Perte_Charge_PolyMAC_Face, Perte_Charge_Singuliere_PolyMAC_Face, Perte_Charge_Singuliere_PolyMAC_P0P1NC_Face, Source_Generique_Face_PolyMAC, Source_Generique_Face_PolyMAC_P0P1NC, Terme_Puissance_Thermique_PolyMAC_base, Terme_Puissance_Thermique_PolyMAC_Elem, Terme_Source_Constituant_PolyMAC_Elem, Terme_Source_PolyMAC_base, Terme_Boussinesq_PolyMAC_Face, Terme_Puissance_Thermique_Echange_Impose_Elem_PolyMAC, Terme_Source_Decroissance_Radioactive_Elem_PolyMAC, Terme_Source_Qdm_Face_PolyMAC, Terme_Source_Qdm_Face_PolyMAC_P0P1NC, Source_Chaleur_Fluide_Dilatable_base, Source_Gravite_Fluide_Dilatable_base, Source_QC_Chaleur, Source_QC_Chaleur_Verif, Source_QC_Chaleur_Verif_VEF, Source_QC_Chaleur_Verif_VEF_P1NC, Source_QC_QDM_Gen, Source_WC_Chaleur, Perte_Charge_Gen, Terme_Boussinesq_base, Terme_Puissance_Thermique_Echange_Impose_Elem_base, Terme_Source_Acceleration, Terme_Source_Canal_perio, Terme_Source_Coriolis_base, Source_Dispersion_bulles_base, Source_Flux_interfacial_base, Source_Force_Tchen_base, Source_Frottement_interfacial_base, Source_Portance_interfaciale_base, Source_Travail_pression_Elem_base, Sources_Multiphase_base, Source_Neutronique, Correction_Antal_VDF, Dispersion_bulles_VDF, Flux_interfacial_VDF, Force_Tchen_VDF, Frottement_interfacial_VDF, Portance_interfaciale_VDF, Travail_pression_VDF, Terme_Source_Canal_perio_VDF_Face, Terme_Source_Canal_perio_QC_VDF_Face, Terme_Source_Canal_perio_VDF_P0, Terme_Source_Canal_RANS_LES_VDF_Elem, Terme_Source_Canal_RANS_LES_VDF_Face, Source_QC_Chaleur_VDF, Source_QC_Gravite_VDF, Acceleration_QC_VDF_Face, Source_qdm_QC_VDF_Face, Perte_Charge_Reguliere_QC_VDF_Face, Perte_Charge_Singuliere_QC_VDF_Face, Darcy_QC_VDF_Face, Forchheimer_QC_VDF_Face, Source_WC_Chaleur_VDF, Source_WC_Gravite_VDF, Force_Centrifuge_VDF_Face_Axi, Perte_Charge_Anisotrope_VDF_Face, Perte_Charge_Circulaire_VDF_Face, Perte_Charge_Directionnelle_VDF_Face, Perte_Charge_Isotrope_VDF_Face, Perte_Charge_Reguliere_VDF_Face, Perte_Charge_Singuliere_VDF_Face, Perte_Charge_VDF_base, Perte_Charge_VDF_Face, Source_Generique_VDF_Face, Source_Darcy_VDF_Face, Source_Dirac_VDF_Elem, Source_Echange_Th_VDF, Source_Forchheimer_VDF_Face, Source_Neutronique_VDF, Terme_Gravite_VDF_Face, Terme_Puissance_Thermique_QC_VDF_Elem, Terme_Puissance_Thermique_VDF_base, Terme_Puissance_Thermique_VDF_Elem, Terme_Source_Constituant_VDF_Elem, Terme_Source_VDF_base, Terme_Boussinesq_VDF_Face, Terme_Puissance_Thermique_Echange_Impose_P0_VDF, Terme_Source_Acceleration_VDF_Face, Terme_Source_Coriolis_VDF_Face, Terme_Source_Coriolis_QC_VDF_Face, Terme_Source_inc_base, Terme_Source_inc_th_VDF_Face, Terme_Source_inc_VDF_Face, Terme_Source_Qdm_VDF_Face, Terme_Source_Solide_SWIFT_VDF, Terme_Source_Canal_perio_VEF_P1NC, Terme_Source_Canal_perio_QC_VEF_P1NC, Terme_Source_Canal_RANS_LES_VEF_Face, Source_QC_Chaleur_VEF, Source_QC_Gravite_VEF, Acceleration_QC_VEF_P1NC, Perte_Charge_Circulaire_QC_VEF_P1NC, Perte_Charge_Anisotrope_QC_VEF_P1NC, Perte_Charge_Directionnelle_QC_VEF_P1NC, Perte_Charge_Isotrope_QC_VEF_P1NC, Perte_Charge_Reguliere_QC_VEF_P1NC, Perte_Charge_Singuliere_QC_VEF_P1NC, Source_qdm_QC_VEF_P1NC, Darcy_QC_VEF_P1NC, Forchheimer_QC_VEF_P1NC, Source_WC_Chaleur_VEF, Source_WC_Gravite_VEF, DP_Impose_VEF_Face, Perte_Charge_Anisotrope_VEF_P1NC, Perte_Charge_Circulaire_VEF_P1NC, Perte_Charge_Directionnelle_VEF_P1NC, Perte_Charge_Isotrope_VEF_P1NC, Perte_Charge_Reguliere_VEF_P1NC, Perte_Charge_Singuliere_VEF_Face, Perte_Charge_VEF, Perte_Charge_VEF_Face, Source_Generique_VEF, Source_Darcy_VEF_Face, Source_Dirac_VEF_Face, Source_Forchheimer_VEF_Face, Terme_Puissance_Thermique_QC_VEF_Face, Terme_Puissance_Thermique_VEF_base, Terme_Puissance_Thermique_VEF_Face, Terme_Source_Constituant_VEF_Face, Terme_Source_VEF_base, Terme_Boussinesq_VEF_Face, Terme_Boussinesq_VEFPreP1B_Face, Terme_Puissance_Thermique_Echange_Impose_VEF_Face, Terme_Source_Acceleration_VEF_Face, Terme_Source_Decroissance_Radioactive_VEF_Face, Terme_Source_Qdm_lambdaup_VEF_Face, Terme_Source_Qdm_VEF_Face, Terme_Source_Rappel_T_VEF_Face, and Terme_Source_Th_TdivU_VEF_Face.
Referenced by Source_Con_Phase_field_base::printOn().
readOn()
Entree & Source_base::readOn (Entree & is) override protected virtual
DOES NOTHING - to override in derived classes.
Lecture d'un terme source sur un flot d'entree.
Parameters
(Entree& is) le flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Objet_U.
Reimplemented in Coalescence_bulles_1groupe_PolyMAC_P0, Coalescence_bulles_2groupes_PolyMAC_P0, Correction_Lubchenko_PolyMAC_P0, Flux_2groupes_PolyMAC_P0, Injection_masse_PolyMAC_P0, Injection_QDM_nulle_PolyMAC_P0, Nucleation_paroi_PolyMAC_P0, Rupture_bulles_1groupe_PolyMAC_P0, Rupture_bulles_2groupes_PolyMAC_P0, Variation_rho, Source_injection_masse_base, Source_injection_QDM_base, Injection_QDM_nulle_VDF, Diffusion_croisee_echelle_temp_taux_diss_turb_PolyMAC_P0, Diffusion_supplementaire_echelle_temp_turb_PolyMAC_P0, Dissipation_echelle_temp_taux_diss_turb_PolyMAC_P0, Dissipation_energie_cin_turb_PolyMAC_P0, Dissipation_WIT_PolyMAC_P0, Production_echelle_temp_taux_diss_turb_PolyMAC_P0, Production_energie_cin_turb_PolyMAC_P0, Production_HZDR_PolyMAC_P0, Production_WIT_PolyMAC_P0, Source_BIF_PolyMAC_P0, Source_Dissipation_HZDR_PolyMAC_P0, Source_Diffusion_croisee_echelle_temp_taux_diss_turb, Source_Diffusion_supplementaire_echelle_temp_turb, Source_Dissipation_echelle_temp_taux_diss_turb, Source_Dissipation_energie_cin_turb, Source_Production_echelle_temp_taux_diss_turb, Source_Production_energie_cin_turb, Diffusion_croisee_echelle_temp_taux_diss_turb_VDF, Diffusion_supplementaire_echelle_temp_turb_VDF, Dissipation_echelle_temp_taux_diss_turb_VDF, Dissipation_energie_cin_turb_VDF, Production_echelle_temp_taux_diss_turb_VDF, Production_energie_cin_turb_VDF, Source_Action_Particules, Source_Flottabilite, Source_Masse_Ajoutee, Source_Portance, Source_Reaction_Particules, Source_Trainee, Source_Reaction_Particules_VDF, Source_Reaction_Particules_VEF, SourceFiltree_FT_disc_VEF_P1NC, Terme_Source_Constituant_Vortex_VEF_Face, Source_Con_Phase_field_base, Source_Con_Phase_field, Source_Gravite_PF_VDF, Source_Qdm_VDF_Phase_field, Source_rayo_semi_transp_base, Source_rayo_semi_transp_QC_VDF_P0_VDF, Source_rayo_semi_transp_VDF_P0_VDF, Source_rayo_semi_transp_QC_VEF_P1NC, Source_rayo_semi_transp_VEF_P1NC, Terme_Boussinesq_Sensibility_VEFPreP1B_Face, Tenseur_Reynolds_Externe_VDF_Face, Source_Transport_Bas_Reynolds_VDF_Elem_base, Source_Transport_K_Omega_VDF_Elem_base, Source_Transport_Realisable_VDF_Elem_base, Source_Transport_VDF_Elem_base, Source_Transport_Eps_aniso_therm_concen_VDF_Elem, Source_Transport_Eps_anisotherme_VDF_Elem, Source_Transport_Eps_concen_VDF_Elem, Source_Transport_Eps_Realisable_aniso_concen_VDF_Elem, Source_Transport_Eps_Realisable_aniso_therm_concen_VDF_Elem, Source_Transport_Eps_Realisable_anisotherme_VDF_Elem, Source_Transport_Eps_Realisable_VDF_Elem, Source_Transport_Eps_VDF_Elem, Source_Transport_K_aniso_therm_concen_VDF_Elem, Source_Transport_K_anisotherme_VDF_Elem, Source_Transport_K_concen_VDF_Elem, Source_Transport_K_Realisable_aniso_concen_VDF_Elem, Source_Transport_K_Realisable_aniso_therm_concen_VDF_Elem, Source_Transport_K_Realisable_anisotherme_VDF_Elem, Source_Transport_K_Realisable_VDF_Elem, Source_Transport_K_VDF_Elem, Source_Transport_K_Eps_aniso_therm_concen_VDF_Elem, Source_Transport_K_Eps_anisotherme_VDF_Elem, Source_Transport_K_Eps_Bas_Reynolds_aniso_therm_concen_VDF_Elem, Source_Transport_K_Eps_Bas_Reynolds_anisotherme_VDF_Elem, Source_Transport_K_Eps_Bas_Reynolds_anisotherme_QC_VDF_Elem, Source_Transport_K_Eps_Bas_Reynolds_anisotherme_W_VDF_Elem, Source_Transport_K_Eps_Bas_Reynolds_VDF_Elem, Source_Transport_K_Eps_Bas_Reynolds_W_VDF_Elem, Source_Transport_K_Eps_concen_VDF_Elem, Source_Transport_K_Eps_Realisable_aniso_concen_VDF_Elem, Source_Transport_K_Eps_Realisable_aniso_therm_concen_VDF_Elem, Source_Transport_K_Eps_Realisable_anisotherme_VDF_Elem, Source_Transport_K_Eps_Realisable_VDF_Elem, Source_Transport_K_Eps_VDF_Elem, Source_Transport_K_Omega_VDF_Elem, Source_Transport_Fluctuation_Temperature_VDF_Elem, Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem, Source_Transport_Fluctuation_Temperature_W_VDF_Elem, Source_Transport_Flux_Chaleur_Turbulente_VDF_Face, Source_Transport_K_KEps_anisotherme_VDF_Elem, Source_Transport_K_KEps_VDF_Elem, Source_Transport_K_Omega_VEF_Face_base, Source_Transport_Realisable_VEF_Face_base, Source_Transport_VEF_Face_base, Source_Transport_Eps_aniso_concen_VEF_Face, Source_Transport_Eps_aniso_therm_concen_VEF_Face, Source_Transport_Eps_anisotherme_VEF_Face, Source_Transport_Eps_Realisable_aniso_concen_VEF_Face, Source_Transport_Eps_Realisable_aniso_therm_concen_VEF_Face, Source_Transport_Eps_Realisable_anisotherme_VEF_Face, Source_Transport_Eps_Realisable_VEF_Face, Source_Transport_Eps_VEF_Face, Source_Transport_K_aniso_concen_VEF_Face, Source_Transport_K_aniso_therm_concen_VEF_Face, Source_Transport_K_anisotherme_VEF_Face, Source_Transport_K_Realisable_aniso_concen_VEF_Face, Source_Transport_K_Realisable_aniso_therm_concen_VEF_Face, Source_Transport_K_Realisable_anisotherme_VEF_Face, Source_Transport_K_Realisable_VEF_Face, Source_Transport_K_VEF_Face, Source_Transport_K_Eps_aniso_concen_VEF_Face, Source_Transport_K_Eps_aniso_therm_concen_VEF_Face, Source_Transport_K_Eps_anisotherme_VEF_Face, Source_Transport_K_Eps_Bas_Reynolds_anisotherme_VEF_Face, Source_Transport_K_Eps_Bas_Reynolds_VEF_Face, Source_Transport_K_Eps_Realisable_aniso_concen_VEF_Face, Source_Transport_K_Eps_Realisable_aniso_therm_concen_VEF_Face, Source_Transport_K_Eps_Realisable_anisotherme_VEF_Face, Source_Transport_K_Eps_Realisable_VEF_Face, Source_Transport_K_Eps_VEF_Face, Source_Transport_K_Omega_VEF_Face, Source_Robin, Source_Robin_Scalaire, Source_dep_inco_base, Source_Generique_base, Source_Generique_P0_Elem, Correction_Antal_PolyMAC_P0, Correction_Tomiyama_PolyMAC_P0, Dispersion_bulles_PolyMAC_P0, Flux_interfacial_PolyMAC_P0P1NC, Force_Tchen_PolyMAC_P0, Frottement_interfacial_PolyMAC_P0, Portance_interfaciale_PolyMAC_P0, Travail_pression_PolyMAC_P0P1NC, DP_Impose_PolyMAC_Face, Perte_Charge_Anisotrope_PolyMAC_Face, Perte_Charge_Anisotrope_PolyMAC_P0P1NC_Face, Perte_Charge_Circulaire_PolyMAC_Face, Perte_Charge_Circulaire_PolyMAC_P0P1NC_Face, Perte_Charge_Directionnelle_PolyMAC_Face, Perte_Charge_Directionnelle_PolyMAC_P0P1NC_Face, Perte_Charge_Isotrope_PolyMAC_Face, Perte_Charge_Isotrope_PolyMAC_P0P1NC_Face, Perte_Charge_PolyMAC, Perte_Charge_PolyMAC_Face, Perte_Charge_Singuliere_PolyMAC_Face, Perte_Charge_Singuliere_PolyMAC_P0P1NC_Face, Source_Generique_Face_PolyMAC, Source_Generique_Face_PolyMAC_P0P1NC, Terme_Puissance_Thermique_PolyMAC_base, Terme_Puissance_Thermique_PolyMAC_Elem, Terme_Source_Constituant_PolyMAC_Elem, Terme_Source_PolyMAC_base, Terme_Boussinesq_PolyMAC_Face, Terme_Puissance_Thermique_Echange_Impose_Elem_PolyMAC, Terme_Source_Decroissance_Radioactive_Elem_PolyMAC, Terme_Source_Qdm_Face_PolyMAC, Terme_Source_Qdm_Face_PolyMAC_P0P1NC, Source_Chaleur_Fluide_Dilatable_base, Source_Gravite_Fluide_Dilatable_base, Source_QC_Chaleur, Source_QC_Chaleur_Verif, Source_QC_Chaleur_Verif_VEF, Source_QC_Chaleur_Verif_VEF_P1NC, Source_QC_QDM_Gen, Source_WC_Chaleur, Perte_Charge_Gen, Terme_Boussinesq_base, Terme_Puissance_Thermique_Echange_Impose_Elem_base, Terme_Source_Acceleration, Terme_Source_Canal_perio, Terme_Source_Coriolis_base, Source_Dispersion_bulles_base, Source_Flux_interfacial_base, Source_Force_Tchen_base, Source_Frottement_interfacial_base, Source_Portance_interfaciale_base, Source_Travail_pression_Elem_base, Sources_Multiphase_base, Source_Neutronique, Correction_Antal_VDF, Dispersion_bulles_VDF, Flux_interfacial_VDF, Force_Tchen_VDF, Frottement_interfacial_VDF, Portance_interfaciale_VDF, Travail_pression_VDF, Terme_Source_Canal_perio_VDF_Face, Terme_Source_Canal_perio_QC_VDF_Face, Terme_Source_Canal_perio_VDF_P0, Terme_Source_Canal_RANS_LES_VDF_Elem, Terme_Source_Canal_RANS_LES_VDF_Face, Source_QC_Chaleur_VDF, Source_QC_Gravite_VDF, Acceleration_QC_VDF_Face, Source_qdm_QC_VDF_Face, Perte_Charge_Reguliere_QC_VDF_Face, Perte_Charge_Singuliere_QC_VDF_Face, Darcy_QC_VDF_Face, Forchheimer_QC_VDF_Face, Source_WC_Chaleur_VDF, Source_WC_Gravite_VDF, Force_Centrifuge_VDF_Face_Axi, Perte_Charge_Anisotrope_VDF_Face, Perte_Charge_Circulaire_VDF_Face, Perte_Charge_Directionnelle_VDF_Face, Perte_Charge_Isotrope_VDF_Face, Perte_Charge_Reguliere_VDF_Face, Perte_Charge_Singuliere_VDF_Face, Perte_Charge_VDF_base, Perte_Charge_VDF_Face, Source_Generique_VDF_Face, Source_Darcy_VDF_Face, Source_Dirac_VDF_Elem, Source_Echange_Th_VDF, Source_Forchheimer_VDF_Face, Source_Neutronique_VDF, Terme_Gravite_VDF_Face, Terme_Puissance_Thermique_QC_VDF_Elem, Terme_Puissance_Thermique_VDF_base, Terme_Puissance_Thermique_VDF_Elem, Terme_Source_Constituant_VDF_Elem, Terme_Source_VDF_base, Terme_Boussinesq_VDF_Face, Terme_Puissance_Thermique_Echange_Impose_P0_VDF, Terme_Source_Acceleration_VDF_Face, Terme_Source_Coriolis_VDF_Face, Terme_Source_Coriolis_QC_VDF_Face, Terme_Source_inc_base, Terme_Source_inc_th_VDF_Face, Terme_Source_inc_VDF_Face, Terme_Source_Qdm_VDF_Face, Terme_Source_Solide_SWIFT_VDF, Terme_Source_Canal_perio_VEF_P1NC, Terme_Source_Canal_perio_QC_VEF_P1NC, Terme_Source_Canal_RANS_LES_VEF_Face, Source_QC_Chaleur_VEF, Source_QC_Gravite_VEF, Acceleration_QC_VEF_P1NC, Perte_Charge_Circulaire_QC_VEF_P1NC, Perte_Charge_Anisotrope_QC_VEF_P1NC, Perte_Charge_Directionnelle_QC_VEF_P1NC, Perte_Charge_Isotrope_QC_VEF_P1NC, Perte_Charge_Reguliere_QC_VEF_P1NC, Perte_Charge_Singuliere_QC_VEF_P1NC, Source_qdm_QC_VEF_P1NC, Darcy_QC_VEF_P1NC, Forchheimer_QC_VEF_P1NC, Source_WC_Chaleur_VEF, Source_WC_Gravite_VEF, DP_Impose_VEF_Face, Perte_Charge_Anisotrope_VEF_P1NC, Perte_Charge_Circulaire_VEF_P1NC, Perte_Charge_Directionnelle_VEF_P1NC, Perte_Charge_Isotrope_VEF_P1NC, Perte_Charge_Reguliere_VEF_P1NC, Perte_Charge_Singuliere_VEF_Face, Perte_Charge_VEF, Perte_Charge_VEF_Face, Source_Generique_VEF, Source_Darcy_VEF_Face, Source_Dirac_VEF_Face, Source_Forchheimer_VEF_Face, Terme_Puissance_Thermique_QC_VEF_Face, Terme_Puissance_Thermique_VEF_base, Terme_Puissance_Thermique_VEF_Face, Terme_Source_Constituant_VEF_Face, Terme_Source_VEF_base, Terme_Boussinesq_VEF_Face, Terme_Boussinesq_VEFPreP1B_Face, Terme_Puissance_Thermique_Echange_Impose_VEF_Face, Terme_Source_Acceleration_VEF_Face, Terme_Source_Decroissance_Radioactive_VEF_Face, Terme_Source_Qdm_lambdaup_VEF_Face, Terme_Source_Qdm_VEF_Face, Terme_Source_Rappel_T_VEF_Face, and Terme_Source_Th_TdivU_VEF_Face.
Referenced by Source_Con_Phase_field_base::readOn().
ajouter()
DoubleTab & Source_base::ajouter (DoubleTab & secmem) const virtual
Reimplemented in Source_Flottabilite, Source_Masse_Ajoutee, Source_Portance, Source_Trainee, Source_Reaction_Particules_VDF, Source_Reaction_Particules_VEF, SourceFiltree_FT_disc_VEF_P1NC, Source_Con_Phase_field, Source_Gravite_PF_VDF, Source_Qdm_VDF_Phase_field, Terme_Boussinesq_Sensibility_VEFPreP1B_Face, Source_Transport_Fluctuation_Temperature_VDF_Elem, Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem, Source_Transport_Fluctuation_Temperature_W_VDF_Elem, Source_Transport_Flux_Chaleur_Turbulente_VDF_Face, Source_Transport_Eps_aniso_concen_VEF_Face, Source_Transport_Eps_aniso_therm_concen_VEF_Face, Source_Transport_Eps_anisotherme_VEF_Face, Source_Transport_Eps_Realisable_aniso_concen_VEF_Face, Source_Transport_Eps_Realisable_aniso_therm_concen_VEF_Face, Source_Transport_Eps_Realisable_anisotherme_VEF_Face, Source_Transport_Eps_Realisable_VEF_Face, Source_Transport_Eps_VEF_Face, Source_Transport_K_aniso_concen_VEF_Face, Source_Transport_K_aniso_therm_concen_VEF_Face, Source_Transport_K_anisotherme_VEF_Face, Source_Transport_K_Realisable_aniso_concen_VEF_Face, Source_Transport_K_Realisable_aniso_therm_concen_VEF_Face, Source_Transport_K_Realisable_anisotherme_VEF_Face, Source_Transport_K_Realisable_VEF_Face, Source_Transport_K_VEF_Face, Source_Transport_K_Eps_aniso_concen_VEF_Face, Source_Transport_K_Eps_aniso_therm_concen_VEF_Face, Source_Transport_K_Eps_anisotherme_VEF_Face, Source_Transport_K_Eps_Bas_Reynolds_anisotherme_VEF_Face, Source_Transport_K_Eps_Bas_Reynolds_VEF_Face, Source_Transport_K_Eps_Realisable_aniso_concen_VEF_Face, Source_Transport_K_Eps_Realisable_aniso_therm_concen_VEF_Face, Source_Transport_K_Eps_Realisable_anisotherme_VEF_Face, Source_Transport_K_Eps_Realisable_VEF_Face, Source_Transport_K_Eps_VEF_Face, Source_Transport_K_Omega_VEF_Face, Source_Robin, Source_Robin_Scalaire, Source_Qdm_EF, Source_Scalaire_EF, Source_PDF_base, Source_Generique_P0_Elem, Perte_Charge_PolyMAC, Perte_Charge_Singuliere_PolyMAC_Face, Source_Generique_Face_PolyMAC, Source_Generique_Face_PolyMAC_P0P1NC, Terme_Source_Qdm_Face_PolyMAC, Source_QC_Chaleur, Source_QC_Chaleur_Verif, Source_QC_QDM_Gen, Source_WC_Chaleur, Terme_Source_Canal_perio_VEF_P1NC, Terme_Source_Canal_RANS_LES_VEF_Face, Source_QC_Gravite_VEF, Acceleration_QC_VEF_P1NC, Perte_Charge_Circulaire_QC_VEF_P1NC, Perte_Charge_Anisotrope_QC_VEF_P1NC, Perte_Charge_Directionnelle_QC_VEF_P1NC, Perte_Charge_Isotrope_QC_VEF_P1NC, Perte_Charge_Reguliere_QC_VEF_P1NC, Perte_Charge_Singuliere_QC_VEF_P1NC, Source_qdm_QC_VEF_P1NC, Darcy_QC_VEF_P1NC, Forchheimer_QC_VEF_P1NC, Source_WC_Gravite_VEF, Perte_Charge_Reguliere_VEF_P1NC, Perte_Charge_Singuliere_VEF_Face, Perte_Charge_VEF, Source_Generique_VEF, Terme_Boussinesq_VEF_Face, Terme_Boussinesq_VEFPreP1B_Face, Terme_Puissance_Thermique_Echange_Impose_VEF_Face, Terme_Source_Acceleration_VEF_Face, Terme_Source_Decroissance_Radioactive_VEF_Face, Terme_Source_Qdm_lambdaup_VEF_Face, Terme_Source_Qdm_VEF_Face, Terme_Source_Rappel_T_VEF_Face, Terme_Source_Th_TdivU_VEF_Face, Source_Transport_K_Omega_VEF_Face_base, Source_Transport_VEF_Face_base, Source_Chaleur_Fluide_Dilatable_base, Perte_Charge_VEF_Face, Source_rayo_semi_transp_QC_VDF_P0_VDF, Source_rayo_semi_transp_VDF_P0_VDF, Source_rayo_semi_transp_QC_VEF_P1NC, Source_rayo_semi_transp_VEF_P1NC, Terme_Source_EF_base, Source_dep_inco_base, DP_Impose_VEF_Face, Terme_Source_VEF_base, and Terme_Source_Constituant_Vortex_VEF_Face.
References ajouter_blocs(), Process::exit(), has_interface_blocs(), and Objet_U::que_suis_je().
Referenced by Source::ajouter(), Perte_Charge_PolyMAC::ajouter(), Perte_Charge_Singuliere_PolyMAC_Face::ajouter(), Terme_Source_Qdm_Face_PolyMAC::ajouter(), DP_Impose_VEF_Face::ajouter(), calculer(), Source_Reaction_Particules::calculer(), Tenseur_Reynolds_Externe_VDF_Face::calculer(), Source_Transport_K_Omega_VDF_Elem_base::calculer(), Source_Transport_VDF_Elem_base::calculer(), Source_Generique_base::calculer(), Source_Gravite_Fluide_Dilatable_base::calculer(), Terme_Source_Acceleration::calculer(), Terme_Source_Canal_RANS_LES_VDF_Elem::calculer(), Terme_Source_Canal_RANS_LES_VDF_Face::calculer(), Force_Centrifuge_VDF_Face_Axi::calculer(), Terme_Source_Coriolis_VDF_Face::calculer(), Terme_Source_inc_th_VDF_Face::calculer(), Terme_Source_inc_VDF_Face::calculer(), Terme_Source_Solide_SWIFT_VDF::calculer(), Terme_Boussinesq_base::calculer(), Terme_Source_Canal_perio::calculer(), ParoiVDF_TBLE::calculer_hyd(), and ParoiVDF_TBLE::calculer_hyd_BiK().
calculer()
DoubleTab & Source_base::calculer (DoubleTab & secmem) const virtual
Reimplemented in Source_Flottabilite, Source_Masse_Ajoutee, Source_Portance, Source_Reaction_Particules, Source_Trainee, SourceFiltree_FT_disc_VEF_P1NC, Source_Con_Phase_field, Source_Gravite_PF_VDF, Source_Qdm_VDF_Phase_field, Tenseur_Reynolds_Externe_VDF_Face, Source_Transport_K_Omega_VDF_Elem_base, Source_Transport_VDF_Elem_base, Source_Transport_Fluctuation_Temperature_VDF_Elem, Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem, Source_Transport_Fluctuation_Temperature_W_VDF_Elem, Source_Transport_Flux_Chaleur_Turbulente_VDF_Face, Source_Transport_K_Omega_VEF_Face_base, Source_Transport_VEF_Face_base, Source_Robin, Source_Robin_Scalaire, Source_Qdm_EF, Source_Scalaire_EF, Source_PDF_base, Source_Generique_base, Perte_Charge_Singuliere_PolyMAC_Face, Terme_Source_Qdm_Face_PolyMAC, Source_Chaleur_Fluide_Dilatable_base, Source_Gravite_Fluide_Dilatable_base, Source_QC_QDM_Gen, Terme_Source_Acceleration, Terme_Source_Canal_RANS_LES_VDF_Elem, Terme_Source_Canal_RANS_LES_VDF_Face, Force_Centrifuge_VDF_Face_Axi, Terme_Source_Coriolis_VDF_Face, Terme_Source_inc_th_VDF_Face, Terme_Source_inc_VDF_Face, Terme_Source_Solide_SWIFT_VDF, Terme_Source_Canal_RANS_LES_VEF_Face, Perte_Charge_VEF, Terme_Puissance_Thermique_Echange_Impose_VEF_Face, Terme_Source_Decroissance_Radioactive_VEF_Face, Terme_Source_Qdm_lambdaup_VEF_Face, Terme_Source_Qdm_VEF_Face, Terme_Source_Rappel_T_VEF_Face, Terme_Source_Th_TdivU_VEF_Face, Source_rayo_semi_transp_QC_VDF_P0_VDF, Source_rayo_semi_transp_VDF_P0_VDF, Source_rayo_semi_transp_QC_VEF_P1NC, Source_rayo_semi_transp_VEF_P1NC, Terme_Source_EF_base, Source_dep_inco_base, Terme_Boussinesq_base, Terme_Source_Canal_perio, Source_Neutronique_VDF, Terme_Source_VDF_base, Terme_Source_VEF_base, and Terme_Source_Constituant_Vortex_VEF_Face.
References ajouter().
Referenced by Source::calculer().
mettre_a_jour()
void Source_base::mettre_a_jour (double temps) virtual
DOES NOTHING - to override in derived classes.
Mise a jour en temps du terme source.
Parameters
(double) le pas de temps de mise a jour
Reimplemented in Source_Transport_K_Omega_VDF_Elem_base, Source_Transport_VDF_Elem_base, Coalescence_bulles_1groupe_PolyMAC_P0, Coalescence_bulles_2groupes_PolyMAC_P0, Correction_Lubchenko_PolyMAC_P0, Flux_2groupes_PolyMAC_P0, Nucleation_paroi_PolyMAC_P0, Rupture_bulles_1groupe_PolyMAC_P0, Rupture_bulles_2groupes_PolyMAC_P0, Variation_rho, Source_injection_masse_base, Source_injection_QDM_base, Dissipation_WIT_PolyMAC_P0, Production_HZDR_PolyMAC_P0, Production_WIT_PolyMAC_P0, Source_BIF_PolyMAC_P0, Source_Dissipation_HZDR_PolyMAC_P0, Source_Action_Particules, Source_Reaction_Particules, SourceFiltree_FT_disc_VEF_P1NC, Terme_Source_Constituant_Vortex_VEF_Face, Source_Gravite_PF_VDF, Source_rayo_semi_transp_base, Source_rayo_semi_transp_QC_VDF_P0_VDF, Source_rayo_semi_transp_QC_VEF_P1NC, Source_Transport_Eps_Realisable_VDF_Elem, Source_Transport_K_Realisable_VDF_Elem, Source_Transport_K_Eps_Realisable_VDF_Elem, Source_Transport_Fluctuation_Temperature_VDF_Elem, Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem, Source_Transport_Fluctuation_Temperature_W_VDF_Elem, Source_Transport_Flux_Chaleur_Turbulente_VDF_Face, Source_Transport_K_Omega_VEF_Face_base, Source_Transport_VEF_Face_base, Source_Transport_Eps_Realisable_VEF_Face, Source_Transport_K_Realisable_VEF_Face, Source_Transport_K_Eps_Realisable_VEF_Face, Terme_Puissance_Thermique_DG_Elem, Puissance_Thermique_EF, Puissance_Thermique_QC_EF, Source_Generique_base, Correction_Antal_PolyMAC_P0, Correction_Tomiyama_PolyMAC_P0, Portance_interfaciale_PolyMAC_P0, DP_Impose_PolyMAC_Face, Perte_Charge_Anisotrope_PolyMAC_Face, Perte_Charge_Circulaire_PolyMAC_Face, Perte_Charge_Directionnelle_PolyMAC_Face, Perte_Charge_Isotrope_PolyMAC_Face, Perte_Charge_Singuliere_PolyMAC_Face, Terme_Puissance_Thermique_PolyMAC_Elem, Terme_Source_Constituant_PolyMAC_Elem, Source_QC_QDM_Gen, Terme_Boussinesq_base, Terme_Source_Acceleration, Terme_Source_Canal_perio, Terme_Source_Coriolis_base, Source_Flux_interfacial_base, Sources_Multiphase_base, Source_Neutronique, Correction_Antal_VDF, Force_Centrifuge_VDF_Face_Axi, Perte_Charge_Anisotrope_VDF_Face, Perte_Charge_Circulaire_VDF_Face, Perte_Charge_Directionnelle_VDF_Face, Perte_Charge_Isotrope_VDF_Face, Perte_Charge_Singuliere_VDF_Face, Perte_Charge_VDF_Face, Source_Darcy_VDF_Face, Source_Dirac_VDF_Elem, Source_Echange_Th_VDF, Source_Forchheimer_VDF_Face, Terme_Gravite_VDF_Face, Terme_Puissance_Thermique_QC_VDF_Elem, Terme_Puissance_Thermique_VDF_Elem, Terme_Source_Constituant_VDF_Elem, Terme_Source_Coriolis_VDF_Face, Terme_Source_inc_base, Terme_Source_inc_th_VDF_Face, Terme_Source_inc_VDF_Face, Terme_Source_Solide_SWIFT_VDF, DP_Impose_VEF_Face, Perte_Charge_Anisotrope_VEF_P1NC, Perte_Charge_Circulaire_VEF_P1NC, Perte_Charge_Directionnelle_VEF_P1NC, Perte_Charge_Isotrope_VEF_P1NC, Perte_Charge_Singuliere_VEF_Face, Source_Darcy_VEF_Face, Source_Dirac_VEF_Face, Source_Forchheimer_VEF_Face, Terme_Puissance_Thermique_QC_VEF_Face, Terme_Puissance_Thermique_VEF_Face, Terme_Source_Constituant_VEF_Face, Terme_Source_Rappel_T_VEF_Face, Source_Con_Phase_field, Source_Qdm_VDF_Phase_field, Tenseur_Reynolds_Externe_VDF_Face, Source_Robin, Source_Robin_Scalaire, Source_Qdm_EF, Source_Scalaire_EF, Source_PDF_base, Perte_Charge_PolyMAC_Face, Terme_Source_Decroissance_Radioactive_Elem_PolyMAC, Terme_Source_Qdm_Face_PolyMAC, Source_Chaleur_Fluide_Dilatable_base, Source_Gravite_Fluide_Dilatable_base, Terme_Puissance_Thermique_Echange_Impose_Elem_base, Terme_Source_Canal_RANS_LES_VDF_Elem, Terme_Source_Canal_RANS_LES_VDF_Face, Terme_Source_Qdm_VDF_Face, Terme_Source_Canal_RANS_LES_VEF_Face, Perte_Charge_VEF_Face, Terme_Puissance_Thermique_Echange_Impose_VEF_Face, Terme_Source_Decroissance_Radioactive_VEF_Face, Terme_Source_Qdm_lambdaup_VEF_Face, Terme_Source_Qdm_VEF_Face, and Terme_Source_Th_TdivU_VEF_Face.
References Process::exit(), and Objet_U::que_suis_je().
Referenced by initialiser().
resetTime()
void Source_base::resetTime (double t) virtual
DOES NOTHING - to override in derived classes.
Reset current time.
Parameters
(double) new current time to be set.
Reimplemented in Puissance_Thermique_EF, and Terme_Puissance_Thermique_VDF_base.
References Process::exit(), and Objet_U::que_suis_je().
completer()
void Source_base::completer () virtual
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees: Source_base::associer_domaines(const Domaine_dis_base& ,const Domaine_Cl_dis_base&) Source_base::associer_pb(const Probleme_base&)
Reimplemented in Correction_Lubchenko_PolyMAC_P0, Diffusion_croisee_echelle_temp_taux_diss_turb_PolyMAC_P0, Source_Diffusion_supplementaire_echelle_temp_turb, Source_Dissipation_energie_cin_turb, Production_energie_cin_turb_VDF, Source_Portance, SourceFiltree_FT_disc_VEF_P1NC, Source_rayo_semi_transp_QC_VDF_P0_VDF, Source_rayo_semi_transp_QC_VEF_P1NC, Tenseur_Reynolds_Externe_VDF_Face, Source_Robin, Source_Robin_Scalaire, Terme_Source_DG_base, Terme_Source_EF_base, Source_Generique_base, Correction_Antal_PolyMAC_P0, Correction_Tomiyama_PolyMAC_P0, Travail_pression_PolyMAC_P0P1NC, DP_Impose_PolyMAC_Face, Perte_Charge_Singuliere_PolyMAC_P0P1NC_Face, Terme_Source_PolyMAC_base, Source_Chaleur_Fluide_Dilatable_base, Source_Gravite_Fluide_Dilatable_base, Source_QC_QDM_Gen, Perte_Charge_Gen, Terme_Source_Canal_perio, Source_Flux_interfacial_base, Source_Frottement_interfacial_base, Source_Portance_interfaciale_base, Source_Neutronique, Correction_Antal_VDF, Travail_pression_VDF, Force_Centrifuge_VDF_Face_Axi, Perte_Charge_Singuliere_VDF_Face, Source_Neutronique_VDF, Terme_Source_Constituant_VDF_Elem, Terme_Source_VDF_base, DP_Impose_VEF_Face, Perte_Charge_Reguliere_VEF_P1NC, Perte_Charge_VEF, Terme_Source_VEF_base, Terme_Source_Rappel_T_VEF_Face, and Terme_Source_Th_TdivU_VEF_Face.
References associer_domaines(), associer_pb(), bilan_, Equation_base::domaine_Cl_dis(), Equation_base::domaine_dis(), MorEqn::equation(), Equation_base::inconnue(), Field_base::nb_comp(), Equation_base::probleme(), and TRUSTVect< _TYPE_, _SIZE_ >::resize().
Referenced by SourceFiltree_FT_disc_VEF_P1NC::completer(), Source_rayo_semi_transp_QC_VDF_P0_VDF::completer(), Source_rayo_semi_transp_QC_VEF_P1NC::completer(), Tenseur_Reynolds_Externe_VDF_Face::completer(), Source_Robin::completer(), Source_Robin_Scalaire::completer(), Terme_Source_DG_base::completer(), Terme_Source_EF_base::completer(), Source_Generique_base::completer(), Travail_pression_PolyMAC_P0P1NC::completer(), DP_Impose_PolyMAC_Face::completer(), Perte_Charge_Singuliere_PolyMAC_P0P1NC_Face::completer(), Terme_Source_PolyMAC_base::completer(), Source_Chaleur_Fluide_Dilatable_base::completer(), Source_Gravite_Fluide_Dilatable_base::completer(), Source_QC_QDM_Gen::completer(), Perte_Charge_Gen::completer(), Terme_Source_Canal_perio::completer(), Source_Neutronique::completer(), Travail_pression_VDF::completer(), Force_Centrifuge_VDF_Face_Axi::completer(), Perte_Charge_Singuliere_VDF_Face::completer(), Terme_Source_VDF_base::completer(), DP_Impose_VEF_Face::completer(), Perte_Charge_Reguliere_VEF_P1NC::completer(), Perte_Charge_VEF::completer(), Terme_Source_VEF_base::completer(), Terme_Source_Rappel_T_VEF_Face::completer(), and Terme_Source_Th_TdivU_VEF_Face::completer().
dimensionner()
void Source_base::dimensionner (Matrice_Morse & mat) const virtual
Dimensionnement de la matrice implicite des termes sources.
Par defaut ne fait rien.
References dimensionner_blocs(), MorEqn::equation(), Nom::getString(), has_interface_blocs(), Equation_base::inconnue(), and Field_base::le_nom().
Referenced by Sources::dimensionner().
dimensionner_bloc_vitesse()
void Source_base::dimensionner_bloc_vitesse (Matrice_Morse & mat) const virtual
References dimensionner_blocs(), and has_interface_blocs().
contribuer_a_avec()
void Source_base::contribuer_a_avec (const DoubleTab & , Matrice_Morse & mat) const virtual
contribution a la matrice implicite des termes sources par defaut pas de contribution
Reimplemented in Source_Transport_K_Omega_VEF_Face_base, Source_Transport_Realisable_VEF_Face_base, Source_Transport_VEF_Face_base, Source_Transport_K_Eps_VEF_Face, Source_Transport_K_Omega_VEF_Face, Source_PDF_EF, Source_PDF_base, Perte_Charge_PolyMAC, Perte_Charge_Singuliere_PolyMAC_Face, Acceleration_QC_VEF_P1NC, Perte_Charge_Circulaire_QC_VEF_P1NC, Perte_Charge_Anisotrope_QC_VEF_P1NC, Perte_Charge_Directionnelle_QC_VEF_P1NC, Perte_Charge_Isotrope_QC_VEF_P1NC, Perte_Charge_Reguliere_QC_VEF_P1NC, Perte_Charge_Singuliere_QC_VEF_P1NC, Source_qdm_QC_VEF_P1NC, Darcy_QC_VEF_P1NC, Forchheimer_QC_VEF_P1NC, Perte_Charge_Reguliere_VEF_P1NC, Perte_Charge_Singuliere_VEF_Face, Perte_Charge_VEF, Terme_Puissance_Thermique_Echange_Impose_VEF_Face, and Terme_Source_Decroissance_Radioactive_VEF_Face.
References ajouter_blocs(), MorEqn::equation(), Nom::getString(), has_interface_blocs(), Equation_base::inconnue(), and Field_base::le_nom().
Referenced by Equation_IBM_proto::assembler_ibm_proto(), Sources::contribuer_a_avec(), Perte_Charge_PolyMAC::contribuer_a_avec(), and Perte_Charge_Singuliere_PolyMAC_Face::contribuer_a_avec().
contribuer_au_second_membre()
void Source_base::contribuer_au_second_membre (DoubleTab &) const virtual
contribution au second membres des termes sources en implicite par defaut erreur
methode presente par coherence avec Operateur_base
References Process::exit().
impr()
int Source_base::impr (Sortie & os) const virtual
Reimplemented in Source_PDF_EF, Source_PDF_base, Terme_Source_EF_base, and Source_QC_QDM_Gen.
References Sortie::add_col(), bilan_, MorEqn::equation(), Flux, Process::je_suis_maitre(), out_, ouvrir_fichier(), Equation_base::probleme(), Objet_U::que_suis_je(), Probleme_base::schema_temps(), TRUSTVect< _TYPE_, _SIZE_ >::size(), and Schema_Temps_base::temps_courant().
associer_domaines_public()
void Source_base::associer_domaines_public (const Domaine_dis_base & zdis, const Domaine_Cl_dis_base & zcldis) inline
References associer_domaines().
initialiser()
int Source_base::initialiser (double temps) virtual
Contrairement aux methodes mettre_a_jour, les methodes initialiser des sources ne peuvent pas dependre de l'exterieur.
(lui-meme peut ne pas etre initialise) Par defaut, mettre_a_jour
Reimplemented in Terme_Puissance_Thermique_DG_base, Terme_Puissance_Thermique_PolyMAC_base, Terme_Source_Qdm_Face_PolyMAC_P0P1NC, Terme_Puissance_Thermique_Echange_Impose_Elem_base, Terme_Puissance_Thermique_VDF_base, Terme_Source_Qdm_VDF_Face, Terme_Puissance_Thermique_VEF_base, Terme_Source_VEF_base, and Terme_Puissance_Thermique_Echange_Impose_VEF_Face.
References mettre_a_jour().
Referenced by Terme_Puissance_Thermique_DG_base::initialiser(), Terme_Puissance_Thermique_PolyMAC_base::initialiser(), Terme_Source_Qdm_Face_PolyMAC_P0P1NC::initialiser(), Terme_Puissance_Thermique_Echange_Impose_Elem_base::initialiser(), Terme_Puissance_Thermique_VDF_base::initialiser(), Terme_Source_Qdm_VDF_Face::initialiser(), Terme_Source_VEF_base::initialiser(), and Terme_Puissance_Thermique_Echange_Impose_VEF_Face::initialiser().
associer_champ_rho()
void Source_base::associer_champ_rho (const Champ_base & champ_rho) virtual
Cette methode (ou la methode de la classe derivee) est appelee par Sources::associer_champ_rho pour chaque source de la liste.
(par exemple, a l'initialisation d'un calcul front-tracking). Cette methode doit etre reimplementee dans les classes derivees utilisees dans les problemes a rho variable.
La methode ajouter calcule le terme suivant: INTEGRALE (terme source) sur volume entrelace
Dans les problemes ou rho est variable, "terme source" homogene a rho*v. Sinon, "terme source" est homogene a v.
Reimplemented in Terme_Source_Acceleration_VDF_Face, and Terme_Source_Acceleration_VEF_Face.
References Process::exit(), Field_base::le_nom(), and Objet_U::que_suis_je().
Referenced by Sources::associer_champ_rho().
a_pour_Champ_Fonc()
int Source_base::a_pour_Champ_Fonc (const Motcle & mot, TRUST_Ref< Champ_base * > & ch_ref) const virtual
Si la source comprend le motcle "mot", elle remplit la reference a ch_ref et renvoie 1, sinon renvoie 0 (voir Source_Translation par ex.
)
Reimplemented in Terme_Source_Acceleration.
Referenced by Sources::a_pour_Champ_Fonc().
contribuer_jacobienne()
virtual void Source_base::contribuer_jacobienne (Matrice_Bloc & , int) const inline virtual
Referenced by Sources::contribuer_jacobienne().
has_interface_blocs()
virtual int Source_base::has_interface_blocs () const inline virtual
Reimplemented in Coalescence_bulles_1groupe_PolyMAC_P0, Coalescence_bulles_2groupes_PolyMAC_P0, Correction_Lubchenko_PolyMAC_P0, Nucleation_paroi_PolyMAC_P0, Rupture_bulles_1groupe_PolyMAC_P0, Rupture_bulles_2groupes_PolyMAC_P0, Variation_rho, Source_injection_QDM_base, Dissipation_WIT_PolyMAC_P0, Production_HZDR_PolyMAC_P0, Production_WIT_PolyMAC_P0, Source_BIF_PolyMAC_P0, Source_Dissipation_HZDR_PolyMAC_P0, Tenseur_Reynolds_Externe_VDF_Face, Source_Transport_K_Omega_VDF_Elem_base, Source_Transport_VDF_Elem_base, Terme_Source_DG_base, Correction_Antal_PolyMAC_P0, Correction_Tomiyama_PolyMAC_P0, DP_Impose_PolyMAC_Face, Perte_Charge_Anisotrope_PolyMAC_P0P1NC_Face, Perte_Charge_Circulaire_PolyMAC_P0P1NC_Face, Perte_Charge_Directionnelle_PolyMAC_P0P1NC_Face, Perte_Charge_Isotrope_PolyMAC_P0P1NC_Face, Perte_Charge_Singuliere_PolyMAC_P0P1NC_Face, Terme_Source_PolyMAC_base, Terme_Boussinesq_PolyMAC_Face, Terme_Source_Decroissance_Radioactive_Elem_PolyMAC, Terme_Source_Qdm_Face_PolyMAC_P0P1NC, Terme_Puissance_Thermique_Echange_Impose_Elem_base, Sources_Multiphase_base, Correction_Antal_VDF, Terme_Source_Canal_perio_VDF_Face, Terme_Source_Canal_RANS_LES_VDF_Elem, Terme_Source_Canal_RANS_LES_VDF_Face, Source_QC_Chaleur_VDF, Source_QC_Gravite_VDF, Acceleration_QC_VDF_Face, Source_qdm_QC_VDF_Face, Perte_Charge_Reguliere_QC_VDF_Face, Perte_Charge_Singuliere_QC_VDF_Face, Darcy_QC_VDF_Face, Forchheimer_QC_VDF_Face, Source_WC_Chaleur_VDF, Source_WC_Gravite_VDF, Force_Centrifuge_VDF_Face_Axi, Perte_Charge_Reguliere_VDF_Face, Perte_Charge_Singuliere_VDF_Face, Perte_Charge_VDF_base, Perte_Charge_VDF_Face, Source_Generique_VDF_Face, Source_Neutronique_VDF, Terme_Source_VDF_base, Terme_Boussinesq_VDF_Face, Terme_Source_Acceleration_VDF_Face, Terme_Source_Coriolis_VDF_Face, Terme_Source_inc_th_VDF_Face, Terme_Source_inc_VDF_Face, Terme_Source_Qdm_VDF_Face, Terme_Source_Solide_SWIFT_VDF, and DP_Impose_VEF_Face.
Referenced by ajouter(), Source_PDF_base::ajouter(), Perte_Charge_PolyMAC::ajouter(), Perte_Charge_Singuliere_PolyMAC_Face::ajouter(), Terme_Source_Qdm_Face_PolyMAC::ajouter(), Source_QC_Chaleur::ajouter(), Source_WC_Chaleur::ajouter(), Source_dep_inco_base::ajouter(), Perte_Charge_PolyMAC::ajouter_blocs(), contribuer_a_avec(), Perte_Charge_PolyMAC::contribuer_a_avec(), Perte_Charge_Singuliere_PolyMAC_Face::contribuer_a_avec(), dimensionner(), and dimensionner_bloc_vitesse().
dimensionner_blocs()
void Source_base::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl = { }) const virtual
Reimplemented in Tenseur_Reynolds_Externe_VDF_Face, Source_Transport_K_Omega_VDF_Elem_base, Source_Transport_VDF_Elem_base, Source_Transport_Eps_VDF_Elem, Terme_Source_Canal_perio_VDF_Face, Terme_Source_Canal_RANS_LES_VDF_Elem, Terme_Source_Canal_RANS_LES_VDF_Face, Source_QC_Chaleur_VDF, Source_QC_Gravite_VDF, Acceleration_QC_VDF_Face, Source_qdm_QC_VDF_Face, Perte_Charge_Reguliere_QC_VDF_Face, Perte_Charge_Singuliere_QC_VDF_Face, Darcy_QC_VDF_Face, Forchheimer_QC_VDF_Face, Source_WC_Chaleur_VDF, Source_WC_Gravite_VDF, Force_Centrifuge_VDF_Face_Axi, Perte_Charge_Reguliere_VDF_Face, Perte_Charge_Singuliere_VDF_Face, Source_Generique_VDF_Face, Source_Neutronique_VDF, Terme_Source_VDF_base, Terme_Boussinesq_VDF_Face, Terme_Source_Acceleration_VDF_Face, Terme_Source_Coriolis_VDF_Face, Terme_Source_inc_th_VDF_Face, Terme_Source_inc_VDF_Face, Terme_Source_Qdm_VDF_Face, Terme_Source_Solide_SWIFT_VDF, Coalescence_bulles_1groupe_PolyMAC_P0, Coalescence_bulles_2groupes_PolyMAC_P0, Correction_Lubchenko_PolyMAC_P0, Flux_2groupes_PolyMAC_P0, Nucleation_paroi_PolyMAC_P0, Rupture_bulles_1groupe_PolyMAC_P0, Rupture_bulles_2groupes_PolyMAC_P0, Variation_rho, Source_injection_masse_base, Source_injection_QDM_base, Diffusion_supplementaire_echelle_temp_turb_PolyMAC_P0, Dissipation_WIT_PolyMAC_P0, Production_HZDR_PolyMAC_P0, Production_WIT_PolyMAC_P0, Source_BIF_PolyMAC_P0, Source_Dissipation_HZDR_PolyMAC_P0, Source_Diffusion_croisee_echelle_temp_taux_diss_turb, Source_Diffusion_supplementaire_echelle_temp_turb, Source_Dissipation_echelle_temp_taux_diss_turb, Source_Dissipation_energie_cin_turb, Source_Production_echelle_temp_taux_diss_turb, Source_Production_energie_cin_turb, Diffusion_supplementaire_echelle_temp_turb_VDF, Terme_Source_DG_base, Correction_Antal_PolyMAC_P0, Correction_Tomiyama_PolyMAC_P0, DP_Impose_PolyMAC_Face, Perte_Charge_Singuliere_PolyMAC_P0P1NC_Face, Terme_Source_PolyMAC_base, Terme_Boussinesq_PolyMAC_Face, Terme_Source_Decroissance_Radioactive_Elem_PolyMAC, Terme_Source_Qdm_Face_PolyMAC_P0P1NC, Perte_Charge_Gen, Terme_Puissance_Thermique_Echange_Impose_Elem_base, Source_Dispersion_bulles_base, Source_Flux_interfacial_base, Source_Force_Tchen_base, Source_Frottement_interfacial_base, Source_Portance_interfaciale_base, Source_Travail_pression_Elem_base, Correction_Antal_VDF, and DP_Impose_VEF_Face.
References Process::exit(), and Objet_U::que_suis_je().
Referenced by dimensionner(), and dimensionner_bloc_vitesse().
ajouter_blocs()
void Source_base::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = { }) const virtual
Reimplemented in Tenseur_Reynolds_Externe_VDF_Face, Source_Transport_Bas_Reynolds_VDF_Elem_base, Source_Transport_Realisable_VDF_Elem_base, Source_Transport_Eps_aniso_therm_concen_VDF_Elem, Source_Transport_Eps_anisotherme_VDF_Elem, Source_Transport_Eps_concen_VDF_Elem, Source_Transport_Eps_Realisable_aniso_concen_VDF_Elem, Source_Transport_Eps_Realisable_aniso_therm_concen_VDF_Elem, Source_Transport_Eps_Realisable_anisotherme_VDF_Elem, Source_Transport_Eps_Realisable_VDF_Elem, Source_Transport_Eps_VDF_Elem, Source_Transport_K_aniso_therm_concen_VDF_Elem, Source_Transport_K_anisotherme_VDF_Elem, Source_Transport_K_concen_VDF_Elem, Source_Transport_K_Realisable_aniso_concen_VDF_Elem, Source_Transport_K_Realisable_aniso_therm_concen_VDF_Elem, Source_Transport_K_Realisable_anisotherme_VDF_Elem, Source_Transport_K_Realisable_VDF_Elem, Source_Transport_K_VDF_Elem, Source_Transport_K_Eps_aniso_therm_concen_VDF_Elem, Source_Transport_K_Eps_anisotherme_VDF_Elem, Source_Transport_K_Eps_Bas_Reynolds_aniso_therm_concen_VDF_Elem, Source_Transport_K_Eps_Bas_Reynolds_anisotherme_VDF_Elem, Source_Transport_K_Eps_Bas_Reynolds_anisotherme_QC_VDF_Elem, Source_Transport_K_Eps_Bas_Reynolds_anisotherme_W_VDF_Elem, Source_Transport_K_Eps_concen_VDF_Elem, Source_Transport_K_Eps_Realisable_aniso_concen_VDF_Elem, Source_Transport_K_Eps_Realisable_aniso_therm_concen_VDF_Elem, Source_Transport_K_Eps_Realisable_anisotherme_VDF_Elem, Source_Transport_K_Eps_Realisable_VDF_Elem, Source_Transport_K_Eps_VDF_Elem, Source_Transport_K_Omega_VDF_Elem, Source_Transport_K_KEps_anisotherme_VDF_Elem, Source_Transport_K_KEps_VDF_Elem, Terme_Source_Canal_perio_VDF_Face, Terme_Source_Canal_perio_VDF_P0, Terme_Source_Canal_RANS_LES_VDF_Elem, Terme_Source_Canal_RANS_LES_VDF_Face, Source_QC_Chaleur_VDF, Source_QC_Gravite_VDF, Acceleration_QC_VDF_Face, Source_qdm_QC_VDF_Face, Perte_Charge_Reguliere_QC_VDF_Face, Perte_Charge_Singuliere_QC_VDF_Face, Darcy_QC_VDF_Face, Forchheimer_QC_VDF_Face, Source_WC_Chaleur_VDF, Source_WC_Gravite_VDF, Force_Centrifuge_VDF_Face_Axi, Perte_Charge_Reguliere_VDF_Face, Perte_Charge_Singuliere_VDF_Face, Source_Generique_VDF_Face, Source_Neutronique_VDF, Terme_Source_VDF_base, Terme_Boussinesq_VDF_Face, Terme_Source_Acceleration_VDF_Face, Terme_Source_Coriolis_VDF_Face, Terme_Source_inc_th_VDF_Face, Terme_Source_inc_VDF_Face, Terme_Source_Qdm_VDF_Face, Terme_Source_Solide_SWIFT_VDF, Source_Transport_K_Omega_VDF_Elem_base, Source_Transport_VDF_Elem_base, Coalescence_bulles_1groupe_PolyMAC_P0, Coalescence_bulles_2groupes_PolyMAC_P0, Correction_Lubchenko_PolyMAC_P0, Flux_2groupes_PolyMAC_P0, Injection_QDM_nulle_PolyMAC_P0, Nucleation_paroi_PolyMAC_P0, Rupture_bulles_1groupe_PolyMAC_P0, Rupture_bulles_2groupes_PolyMAC_P0, Variation_rho, Source_injection_masse_base, Injection_QDM_nulle_VDF, Diffusion_croisee_echelle_temp_taux_diss_turb_PolyMAC_P0, Diffusion_supplementaire_echelle_temp_turb_PolyMAC_P0, Dissipation_WIT_PolyMAC_P0, Production_echelle_temp_taux_diss_turb_PolyMAC_P0, Production_energie_cin_turb_PolyMAC_P0, Production_HZDR_PolyMAC_P0, Production_WIT_PolyMAC_P0, Source_BIF_PolyMAC_P0, Source_Dissipation_HZDR_PolyMAC_P0, Source_Dissipation_echelle_temp_taux_diss_turb, Source_Dissipation_energie_cin_turb, Diffusion_croisee_echelle_temp_taux_diss_turb_VDF, Diffusion_supplementaire_echelle_temp_turb_VDF, Production_echelle_temp_taux_diss_turb_VDF, Production_energie_cin_turb_VDF, Terme_Source_DG_base, Correction_Antal_PolyMAC_P0, Correction_Tomiyama_PolyMAC_P0, Dispersion_bulles_PolyMAC_P0, Frottement_interfacial_PolyMAC_P0, Portance_interfaciale_PolyMAC_P0, DP_Impose_PolyMAC_Face, Perte_Charge_PolyMAC, Perte_Charge_Singuliere_PolyMAC_P0P1NC_Face, Terme_Source_PolyMAC_base, Terme_Boussinesq_PolyMAC_Face, Terme_Source_Decroissance_Radioactive_Elem_PolyMAC, Terme_Source_Qdm_Face_PolyMAC_P0P1NC, Terme_Puissance_Thermique_Echange_Impose_Elem_base, Source_Flux_interfacial_base, Source_Force_Tchen_base, Source_Travail_pression_Elem_base, Correction_Antal_VDF, Dispersion_bulles_VDF, Frottement_interfacial_VDF, Portance_interfaciale_VDF, Perte_Charge_VDF_base, DP_Impose_VEF_Face, Source_Diffusion_croisee_echelle_temp_taux_diss_turb, Source_Diffusion_supplementaire_echelle_temp_turb, Source_Production_echelle_temp_taux_diss_turb, Source_Production_energie_cin_turb, Source_Dispersion_bulles_base, Source_Frottement_interfacial_base, and Source_Portance_interfaciale_base.
References Process::exit(), and Objet_U::que_suis_je().
Referenced by ajouter(), Source_PDF_base::ajouter(), Source_QC_Chaleur::ajouter(), Source_WC_Chaleur::ajouter(), Source_dep_inco_base::ajouter(), and contribuer_a_avec().
creer_champ()
void Source_base::creer_champ (const Motcle & motlu) inline override virtual
Implements Champs_compris_interface.
Reimplemented in Source_Transport_K_Omega_VEF_Face, Source_QC_QDM_Gen, and Source_Portance_interfaciale_base.
Referenced by Source_Transport_K_Omega_VEF_Face::creer_champ().
get_champ()
const Champ_base & Source_base::get_champ (const Motcle & nom) const override virtual
Implements Champs_compris_interface.
Reimplemented in Source_QC_QDM_Gen.
References champs_compris_, and Champs_compris_T< FIELD_TYPE >::get_champ().
Referenced by Diffusion_croisee_echelle_temp_taux_diss_turb_PolyMAC_P0::ajouter_blocs(), Source_BIF_PolyMAC_P0::ajouter_blocs(), Source_Dissipation_HZDR_PolyMAC_P0::ajouter_blocs(), Diffusion_croisee_echelle_temp_taux_diss_turb_VDF::ajouter_blocs(), Correction_Lubchenko_PolyMAC_P0::ajouter_blocs_BIF(), Source_Dissipation_energie_cin_turb::dimensionner_blocs(), Source_Production_echelle_temp_taux_diss_turb::dimensionner_blocs(), Source_Production_energie_cin_turb::dimensionner_blocs(), Terme_Source_Decroissance_Radioactive_Elem_PolyMAC::dimensionner_blocs(), Source_Travail_pression_Elem_base::dimensionner_blocs(), and Source_PDF_base::updateChampRho().
has_champ() [1/2]
bool Source_base::has_champ (const Motcle & nom, TRUST_Ref< Champ_base * > & ref_champ) const override virtual
Implements Champs_compris_interface.
Reimplemented in Source_QC_QDM_Gen.
References champs_compris_, and Champs_compris_T< FIELD_TYPE >::has_champ().
Referenced by Source_Portance_interfaciale_base::completer(), Puissance_Thermique_QC_EF::get_champ(), and Puissance_Thermique_QC_EF::has_champ().
has_champ() [2/2]
bool Source_base::has_champ (const Motcle & nom) const override virtual
Implements Champs_compris_interface.
Reimplemented in Source_QC_QDM_Gen.
References champs_compris_, and Champs_compris_T< FIELD_TYPE >::has_champ().
get_noms_champs_postraitables()
void Source_base::get_noms_champs_postraitables (Noms & nom, Option opt = NONE) const override virtual
Implements Champs_compris_interface.
Reimplemented in Source_Transport_K_Omega_VEF_Face, and Source_QC_QDM_Gen.
References TRUST_Vector< _CLASSE_ >::add(), champs_compris_, Champs_compris_T< FIELD_TYPE >::liste_noms_compris(), and Objet_U::que_suis_je().
Referenced by Source_Transport_K_Omega_VEF_Face::get_noms_champs_postraitables(), Source_PDF_EF::get_noms_champs_postraitables(), and Puissance_Thermique_QC_EF::get_noms_champs_postraitables().
ouvrir_fichier()
void Source_base::ouvrir_fichier (SFichier & os, const Nom & type, const int flag = 1) const virtual
Ouverture/creation d'un fichier d'impression d'un terme source A surcharger dans les classes derivees.
Exceptions
methode a surcharger
Reimplemented in Source_PDF_base, and Terme_Source_Constituant_VDF_Elem.
References Sortie::add_col(), col_names_, col_width_, description(), MorEqn::equation(), Process::exit(), Nom::getString(), Schema_Temps_base::gnuplot_header(), Probleme_U::le_nom(), Schema_Temps_base::nb_impr(), out_, Sortie_Fichier_base::ouvrir(), Sortie_Fichier_base::precision(), Schema_Temps_base::precision_impr(), Equation_base::probleme(), Objet_U::que_suis_je(), Probleme_base::reprise_effectuee(), Probleme_base::schema_temps(), Sortie::set_col_width(), Sortie_Fichier_base::setf(), TRUST_Vector< _CLASSE_ >::size(), and Schema_Temps_base::wcol().
Referenced by impr().
set_fichier()
void Source_base::set_fichier (const Nom & nom)
References MorEqn::equation(), Probleme_U::le_nom(), Objet_U::nom_du_cas(), out_, and Equation_base::probleme().
Referenced by Terme_Source_Canal_perio::completer(), Terme_Puissance_Thermique_DG_base::readOn(), DP_Impose_PolyMAC_Face::readOn(), Perte_Charge_Singuliere_PolyMAC_Face::readOn(), Terme_Puissance_Thermique_PolyMAC_base::readOn(), Terme_Source_Constituant_PolyMAC_Elem::readOn(), Terme_Puissance_Thermique_Echange_Impose_Elem_base::readOn(), Perte_Charge_Singuliere_VDF_Face::readOn(), Source_Darcy_VDF_Face::readOn(), Source_Dirac_VDF_Elem::readOn(), Source_Echange_Th_VDF::readOn(), Source_Forchheimer_VDF_Face::readOn(), Terme_Gravite_VDF_Face::readOn(), Terme_Puissance_Thermique_VDF_base::readOn(), Terme_Source_Constituant_VDF_Elem::readOn(), DP_Impose_VEF_Face::readOn(), Perte_Charge_Singuliere_VEF_Face::readOn(), Source_Darcy_VEF_Face::readOn(), Source_Dirac_VEF_Face::readOn(), Source_Forchheimer_VEF_Face::readOn(), Terme_Puissance_Thermique_VEF_base::readOn(), Terme_Source_Constituant_VEF_Face::readOn(), and Terme_Puissance_Thermique_Echange_Impose_VEF_Face::readOn().
set_description()
void Source_base::set_description (const Nom & nom) inline
References description_.
Referenced by Terme_Source_Canal_perio::completer(), Terme_Puissance_Thermique_DG_base::readOn(), DP_Impose_PolyMAC_Face::readOn(), Perte_Charge_Singuliere_PolyMAC_Face::readOn(), Terme_Puissance_Thermique_PolyMAC_base::readOn(), Terme_Source_Constituant_PolyMAC_Elem::readOn(), Terme_Puissance_Thermique_Echange_Impose_Elem_base::readOn(), Perte_Charge_Singuliere_VDF_Face::readOn(), Source_Darcy_VDF_Face::readOn(), Source_Dirac_VDF_Elem::readOn(), Source_Echange_Th_VDF::readOn(), Source_Forchheimer_VDF_Face::readOn(), Terme_Gravite_VDF_Face::readOn(), Terme_Puissance_Thermique_VDF_base::readOn(), Terme_Source_Constituant_VDF_Elem::readOn(), DP_Impose_VEF_Face::readOn(), Perte_Charge_Singuliere_VEF_Face::readOn(), Source_Darcy_VEF_Face::readOn(), Source_Dirac_VEF_Face::readOn(), Source_Forchheimer_VEF_Face::readOn(), Terme_Puissance_Thermique_VEF_base::readOn(), Terme_Source_Constituant_VEF_Face::readOn(), and Terme_Puissance_Thermique_Echange_Impose_VEF_Face::readOn().
set_col_names()
void Source_base::set_col_names (const Noms & col_names) inline
References col_names_.
Referenced by DP_Impose_PolyMAC_Face::readOn(), Perte_Charge_Singuliere_PolyMAC_Face::readOn(), Terme_Puissance_Thermique_Echange_Impose_Elem_base::readOn(), and DP_Impose_VEF_Face::readOn().
fichier()
const Nom Source_base::fichier () const inline
References out_.
description()
const Nom Source_base::description () const inline
References description_.
Referenced by Source_PDF_base::ouvrir_fichier(), ouvrir_fichier(), and Terme_Source_Constituant_VDF_Elem::ouvrir_fichier().
bilan() [1/2]
DoubleVect & Source_base::bilan () inline
References bilan_.
Referenced by Terme_Source_Canal_perio_VEF_P1NC::ajouter(), DP_Impose_PolyMAC_Face::ajouter_blocs(), DP_Impose_VEF_Face::ajouter_blocs(), DP_Impose_PolyMAC_Face::completer(), DP_Impose_VEF_Face::completer(), DP_Impose_PolyMAC_Face::mettre_a_jour(), Perte_Charge_Singuliere_PolyMAC_Face::mettre_a_jour(), Perte_Charge_Singuliere_VDF_Face::mettre_a_jour(), DP_Impose_VEF_Face::mettre_a_jour(), Perte_Charge_Singuliere_VEF_Face::mettre_a_jour(), Terme_Puissance_Thermique_Echange_Impose_Elem_base::pid_process(), Perte_Charge_Singuliere_PolyMAC_Face::readOn(), Perte_Charge_Singuliere_VDF_Face::readOn(), and Perte_Charge_Singuliere_VEF_Face::readOn().
bilan() [2/2]
DoubleVect & Source_base::bilan () const inline
References bilan_.
champs_compris()
Champs_compris & Source_base::champs_compris () inline
References champs_compris_.
champs_don()
const TRUST_List< TRUST_Ref< Champ_Don_base * > > & Source_base::champs_don () const inline
References champs_don_.
associer_domaines()
virtual void Source_base::associer_domaines (const Domaine_dis_base & , const Domaine_Cl_dis_base &) protected pure virtual
Implemented in Coalescence_bulles_1groupe_PolyMAC_P0, Coalescence_bulles_2groupes_PolyMAC_P0, Correction_Lubchenko_PolyMAC_P0, Flux_2groupes_PolyMAC_P0, Nucleation_paroi_PolyMAC_P0, Rupture_bulles_1groupe_PolyMAC_P0, Rupture_bulles_2groupes_PolyMAC_P0, Variation_rho, Source_injection_QDM_base, Dissipation_WIT_PolyMAC_P0, Production_HZDR_PolyMAC_P0, Production_WIT_PolyMAC_P0, Source_BIF_PolyMAC_P0, Source_Dissipation_HZDR_PolyMAC_P0, Source_Action_Particules, Source_Reaction_Particules, SourceFiltree_FT_disc_VEF_P1NC, Source_Con_Phase_field, Source_Qdm_VDF_Phase_field, Source_rayo_semi_transp_QC_VDF_P0_VDF, Source_rayo_semi_transp_VDF_P0_VDF, Source_rayo_semi_transp_QC_VEF_P1NC, Source_rayo_semi_transp_VEF_P1NC, Tenseur_Reynolds_Externe_VDF_Face, Source_Transport_K_Omega_VDF_Elem_base, Source_Transport_VDF_Elem_base, Source_Transport_Fluctuation_Temperature_VDF_Elem, Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem, Source_Transport_Fluctuation_Temperature_W_VDF_Elem, Source_Transport_Flux_Chaleur_Turbulente_VDF_Face, Source_Transport_K_Omega_VEF_Face_base, Source_Transport_VEF_Face_base, Source_Robin, Source_Robin_Scalaire, Terme_Puissance_Thermique_DG_base, Terme_Puissance_Thermique_DG_Elem, Source_PDF_EF, Source_Qdm_EF, Source_Scalaire_EF, Puissance_Thermique_EF, Puissance_Thermique_QC_EF, Source_PDF_base, Source_Generique_P0_Elem, Correction_Antal_PolyMAC_P0, Correction_Tomiyama_PolyMAC_P0, Perte_Charge_PolyMAC_Face, Source_Generique_Face_PolyMAC, Terme_Puissance_Thermique_PolyMAC_base, Terme_Puissance_Thermique_PolyMAC_Elem, Terme_Source_Constituant_PolyMAC_Elem, Terme_Boussinesq_PolyMAC_Face, Terme_Source_Decroissance_Radioactive_Elem_PolyMAC, Terme_Source_Qdm_Face_PolyMAC, Source_QC_Chaleur_Verif, Source_QC_QDM_Gen, Perte_Charge_Gen, Terme_Puissance_Thermique_Echange_Impose_Elem_base, Sources_Multiphase_base, Correction_Antal_VDF, Terme_Source_Canal_perio_VDF_Face, Terme_Source_Canal_RANS_LES_VDF_Elem, Terme_Source_Canal_RANS_LES_VDF_Face, Source_QC_Chaleur_VDF, Force_Centrifuge_VDF_Face_Axi, Perte_Charge_VDF_Face, Source_Generique_VDF_Face, Source_Darcy_VDF_Face, Source_Dirac_VDF_Elem, Source_Echange_Th_VDF, Source_Forchheimer_VDF_Face, Source_Neutronique_VDF, Terme_Gravite_VDF_Face, Terme_Puissance_Thermique_QC_VDF_Elem, Terme_Puissance_Thermique_VDF_base, Terme_Puissance_Thermique_VDF_Elem, Terme_Source_Constituant_VDF_Elem, Terme_Boussinesq_VDF_Face, Terme_Source_Acceleration_VDF_Face, Terme_Source_Coriolis_VDF_Face, Terme_Source_inc_th_VDF_Face, Terme_Source_inc_VDF_Face, Terme_Source_Qdm_VDF_Face, Terme_Source_Solide_SWIFT_VDF, Terme_Source_Canal_perio_VEF_P1NC, Terme_Source_Canal_RANS_LES_VEF_Face, Source_QC_Chaleur_VEF, Source_WC_Chaleur_VEF, Perte_Charge_VEF, Perte_Charge_VEF_Face, Source_Generique_VEF, Source_Darcy_VEF_Face, Source_Dirac_VEF_Face, Source_Forchheimer_VEF_Face, Terme_Puissance_Thermique_QC_VEF_Face, Terme_Puissance_Thermique_VEF_base, Terme_Puissance_Thermique_VEF_Face, Terme_Source_Constituant_VEF_Face, Terme_Boussinesq_VEF_Face, Terme_Puissance_Thermique_Echange_Impose_VEF_Face, Terme_Source_Acceleration_VEF_Face, Terme_Source_Decroissance_Radioactive_VEF_Face, Terme_Source_Qdm_lambdaup_VEF_Face, Terme_Source_Qdm_VEF_Face, Terme_Source_Rappel_T_VEF_Face, Terme_Source_Th_TdivU_VEF_Face, Source_Generique_base, Source_Chaleur_Fluide_Dilatable_base, Source_Gravite_Fluide_Dilatable_base, Source_Gravite_PF_VDF, Source_QC_Gravite_VDF, Source_WC_Gravite_VDF, Source_QC_Gravite_VEF, Source_WC_Gravite_VEF, and Source_WC_Chaleur_VDF.
Referenced by associer_domaines_public(), and completer().
associer_pb()
virtual void Source_base::associer_pb (const Probleme_base &) protected pure virtual
Implemented in Coalescence_bulles_1groupe_PolyMAC_P0, Coalescence_bulles_2groupes_PolyMAC_P0, Correction_Lubchenko_PolyMAC_P0, Flux_2groupes_PolyMAC_P0, Nucleation_paroi_PolyMAC_P0, Rupture_bulles_1groupe_PolyMAC_P0, Rupture_bulles_2groupes_PolyMAC_P0, Variation_rho, Source_injection_QDM_base, Dissipation_WIT_PolyMAC_P0, Production_HZDR_PolyMAC_P0, Production_WIT_PolyMAC_P0, Source_BIF_PolyMAC_P0, Source_Dissipation_HZDR_PolyMAC_P0, Source_Action_Particules, Source_Reaction_Particules, SourceFiltree_FT_disc_VEF_P1NC, Source_Con_Phase_field, Source_Gravite_PF_VDF, Source_Qdm_VDF_Phase_field, Source_rayo_semi_transp_QC_VDF_P0_VDF, Source_rayo_semi_transp_VDF_P0_VDF, Source_rayo_semi_transp_QC_VEF_P1NC, Source_rayo_semi_transp_VEF_P1NC, Tenseur_Reynolds_Externe_VDF_Face, Source_Transport_Bas_Reynolds_VDF_Elem_base, Source_Transport_K_Omega_VDF_Elem_base, Source_Transport_VDF_Elem_base, Source_Transport_Eps_aniso_therm_concen_VDF_Elem, Source_Transport_Eps_anisotherme_VDF_Elem, Source_Transport_Eps_concen_VDF_Elem, Source_Transport_Eps_Realisable_aniso_concen_VDF_Elem, Source_Transport_Eps_Realisable_aniso_therm_concen_VDF_Elem, Source_Transport_Eps_Realisable_anisotherme_VDF_Elem, Source_Transport_Eps_Realisable_VDF_Elem, Source_Transport_K_aniso_therm_concen_VDF_Elem, Source_Transport_K_anisotherme_VDF_Elem, Source_Transport_K_concen_VDF_Elem, Source_Transport_K_Realisable_aniso_concen_VDF_Elem, Source_Transport_K_Realisable_aniso_therm_concen_VDF_Elem, Source_Transport_K_Realisable_anisotherme_VDF_Elem, Source_Transport_K_Realisable_VDF_Elem, Source_Transport_K_Eps_aniso_therm_concen_VDF_Elem, Source_Transport_K_Eps_anisotherme_VDF_Elem, Source_Transport_K_Eps_Bas_Reynolds_aniso_therm_concen_VDF_Elem, Source_Transport_K_Eps_Bas_Reynolds_anisotherme_VDF_Elem, Source_Transport_K_Eps_Bas_Reynolds_anisotherme_W_VDF_Elem, Source_Transport_K_Eps_concen_VDF_Elem, Source_Transport_K_Eps_Realisable_aniso_concen_VDF_Elem, Source_Transport_K_Eps_Realisable_aniso_therm_concen_VDF_Elem, Source_Transport_K_Eps_Realisable_anisotherme_VDF_Elem, Source_Transport_K_Eps_Realisable_VDF_Elem, Source_Transport_Fluctuation_Temperature_VDF_Elem, Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem, Source_Transport_Fluctuation_Temperature_W_VDF_Elem, Source_Transport_Flux_Chaleur_Turbulente_VDF_Face, Source_Transport_K_KEps_anisotherme_VDF_Elem, Source_Transport_Eps_aniso_concen_VEF_Face, Source_Transport_Eps_aniso_therm_concen_VEF_Face, Source_Transport_Eps_anisotherme_VEF_Face, Source_Transport_Eps_Realisable_aniso_concen_VEF_Face, Source_Transport_Eps_Realisable_aniso_therm_concen_VEF_Face, Source_Transport_Eps_Realisable_anisotherme_VEF_Face, Source_Transport_Eps_Realisable_VEF_Face, Source_Transport_K_aniso_concen_VEF_Face, Source_Transport_K_aniso_therm_concen_VEF_Face, Source_Transport_K_anisotherme_VEF_Face, Source_Transport_K_Realisable_aniso_concen_VEF_Face, Source_Transport_K_Realisable_aniso_therm_concen_VEF_Face, Source_Transport_K_Realisable_anisotherme_VEF_Face, Source_Transport_K_Realisable_VEF_Face, Source_Transport_K_Eps_aniso_concen_VEF_Face, Source_Transport_K_Eps_aniso_therm_concen_VEF_Face, Source_Transport_K_Eps_anisotherme_VEF_Face, Source_Transport_K_Eps_Bas_Reynolds_anisotherme_VEF_Face, Source_Transport_K_Eps_Bas_Reynolds_VEF_Face, Source_Transport_K_Eps_Realisable_aniso_concen_VEF_Face, Source_Transport_K_Eps_Realisable_aniso_therm_concen_VEF_Face, Source_Transport_K_Eps_Realisable_anisotherme_VEF_Face, Source_Transport_K_Eps_Realisable_VEF_Face, Source_Robin, Source_Robin_Scalaire, Terme_Puissance_Thermique_DG_Elem, Source_PDF_EF, Source_Qdm_EF, Source_Scalaire_EF, Puissance_Thermique_EF, Puissance_Thermique_QC_EF, Source_PDF_base, Source_Generique_base, Correction_Antal_PolyMAC_P0, Correction_Tomiyama_PolyMAC_P0, Perte_Charge_PolyMAC_Face, Terme_Puissance_Thermique_PolyMAC_Elem, Terme_Source_Constituant_PolyMAC_Elem, Terme_Source_Decroissance_Radioactive_Elem_PolyMAC, Terme_Source_Qdm_Face_PolyMAC, Source_Chaleur_Fluide_Dilatable_base, Source_Gravite_Fluide_Dilatable_base, Source_QC_QDM_Gen, Perte_Charge_Gen, Terme_Puissance_Thermique_Echange_Impose_Elem_base, Terme_Source_Acceleration, Terme_Source_Canal_perio, Sources_Multiphase_base, Correction_Antal_VDF, Terme_Source_Canal_RANS_LES_VDF_Elem, Terme_Source_Canal_RANS_LES_VDF_Face, Force_Centrifuge_VDF_Face_Axi, Perte_Charge_VDF_Face, Source_Darcy_VDF_Face, Source_Dirac_VDF_Elem, Source_Echange_Th_VDF, Source_Forchheimer_VDF_Face, Source_Neutronique_VDF, Terme_Gravite_VDF_Face, Terme_Puissance_Thermique_QC_VDF_Elem, Terme_Puissance_Thermique_VDF_Elem, Terme_Source_Constituant_VDF_Elem, Terme_Source_Coriolis_VDF_Face, Terme_Source_inc_th_VDF_Face, Terme_Source_inc_VDF_Face, Terme_Source_Qdm_VDF_Face, Terme_Source_Solide_SWIFT_VDF, Terme_Source_Canal_RANS_LES_VEF_Face, Perte_Charge_VEF, Perte_Charge_VEF_Face, Source_Darcy_VEF_Face, Source_Dirac_VEF_Face, Source_Forchheimer_VEF_Face, Terme_Puissance_Thermique_QC_VEF_Face, Terme_Puissance_Thermique_VEF_Face, Terme_Source_Constituant_VEF_Face, Terme_Puissance_Thermique_Echange_Impose_VEF_Face, Terme_Source_Decroissance_Radioactive_VEF_Face, Terme_Source_Qdm_lambdaup_VEF_Face, Terme_Source_Qdm_VEF_Face, Terme_Source_Rappel_T_VEF_Face, Terme_Source_Th_TdivU_VEF_Face, Terme_Source_Constituant_Vortex_VEF_Face, Source_Transport_Eps_VDF_Elem, Source_Transport_K_VDF_Elem, Source_Transport_K_Eps_VDF_Elem, Source_Transport_K_Omega_VDF_Elem, Source_Transport_K_KEps_VDF_Elem, Source_Transport_K_Omega_VEF_Face_base, Source_Transport_VEF_Face_base, Source_Transport_Eps_VEF_Face, Source_Transport_K_VEF_Face, Source_Transport_K_Eps_VEF_Face, Source_Transport_K_Omega_VEF_Face, and Terme_Boussinesq_base.
Referenced by completer().
Member Data Documentation
info_obj
const Type_info Source_base::info_obj static
col_width_
int Source_base::col_width_ = 0 protected
Referenced by Terme_Source_Constituant_VDF_Elem::completer(), and ouvrir_fichier().
out_
Nom Source_base::out_ protected
Referenced by fichier(), Source_PDF_EF::impr(), impr(), Source_PDF_base::ouvrir_fichier(), ouvrir_fichier(), Terme_Source_Constituant_VDF_Elem::ouvrir_fichier(), and set_fichier().
description_
Nom Source_base::description_ protected
Referenced by description(), and set_description().
col_names_
Noms Source_base::col_names_ protected
Referenced by ouvrir_fichier(), and set_col_names().
bilan_
DoubleVect Source_base::bilan_ mutable protected
Referenced by Terme_Source_Canal_perio_VEF_P1NC::ajouter(), bilan(), completer(), Source_PDF_EF::impr(), and impr().
Flux
SFichier Source_base::Flux mutable protected
Referenced by Source_PDF_EF::impr(), and impr().
champs_compris_
Champs_compris Source_base::champs_compris_ protected
Referenced by champs_compris(), Source_Transport_K_Omega_VEF_Face::creer_champ(), Source_PDF_EF::creer_champ(), Source_Portance_interfaciale_base::creer_champ(), Source_PDF_EF::get_champ(), get_champ(), Source_Transport_K_Omega_VEF_Face::get_noms_champs_postraitables(), Source_PDF_EF::get_noms_champs_postraitables(), get_noms_champs_postraitables(), Source_PDF_EF::has_champ(), has_champ(), Terme_Source_Acceleration::lire_data(), Terme_Puissance_Thermique_DG_base::readOn(), Source_Scalaire_EF::readOn(), Puissance_Thermique_EF::readOn(), Terme_Puissance_Thermique_PolyMAC_base::readOn(), Terme_Puissance_Thermique_VDF_base::readOn(), and Terme_Puissance_Thermique_VEF_base::readOn().
champs_don_
TRUST_List< TRUST_Ref< Champ_Don_base *> > Source_base::champs_don_ protected
Referenced by champs_don(), Puissance_Thermique_EF::readOn(), and Terme_Puissance_Thermique_VDF_base::readOn().