TrioCFD: Op_VDF_Elem Class Reference
Op_VDF_Elem Class Reference
#include <Op_VDF_Elem.h>
Member Function Documentation
dimensionner()
void Op_VDF_Elem::dimensionner (const Domaine_VDF & le_dom, const Domaine_Cl_VDF & le_dom_cl, Matrice_Morse & la_matrice, const bool multi_scalar_diff) const
Referenced by Op_Diff_K_Eps_Bas_Re_VDF_base::dimensionner_blocs(), Op_Diff_K_Eps_VDF_base::dimensionner_blocs(), Op_Diff_K_Omega_VDF_base::dimensionner_blocs(), Op_Diff_VDF_Elem_base::dimensionner_blocs(), Op_Dift_VDF_Elem_base::dimensionner_blocs(), and Op_Conv_VDF< OP_TYPE >::dimensionner_elem().
modifier_pour_Cl()
void Op_VDF_Elem::modifier_pour_Cl (const Domaine_VDF & , const Domaine_Cl_VDF & , Matrice_Morse & , DoubleTab &) const
Referenced by Op_Diff_K_Eps_VDF_base::modifier_pour_Cl(), Op_Diff_K_Omega_VDF_base::modifier_pour_Cl(), Op_Diff_K_Eps_Bas_Re_VDF_base::modifier_pour_Cl(), Op_Diff_VDF_Elem_base::modifier_pour_Cl(), Op_Dift_VDF_Elem_base::modifier_pour_Cl(), and Op_Conv_VDF< OP_TYPE >::modifier_pour_Cl_elem().