TrioCFD: Transport_Marqueur_FT Class Reference
Transport_Marqueur_FT Class Reference
#include <Transport_Marqueur_FT.h>
Public Member Functions
void completer () override
void discretiser () override
int get_champ_post_FT (const Motcle &champ, Postraitement_base::Localisation loc, DoubleTab *ftab=0) const override
int get_champ_post_FT (const Motcle &champ, Postraitement_base::Localisation loc, IntTab *itab=0) const override
const Type_info * get_info () const override
bool initTimeStep (double dt) override
Entree & lire_cl (Entree &) override
Entree & lire_cond_init (Entree &is) override
int lire_motcle_non_standard (const Motcle &, Entree &) override
void mettre_a_jour (double temps) override
int preparer_calcul () override
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Public Member Functions inherited from Transport_Interfaces_FT_Disc
void associer_pb_base (const Probleme_base &probleme) override
double calculer_pas_de_temps () const override
virtual void calculer_vitesse_transport_interpolee (const Champ_base &champ_vitesse, const Maillage_FT_Disc &, DoubleTab &vitesse_noeuds, int nv_calc, int standard) const
void discretiser () override
virtual int get_champ_post_FT (const Motcle &champ, Postraitement_base::Localisation loc, DoubleTab *dtab=0) const
virtual int get_champ_post_FT (const Motcle &champ, Postraitement_base::Localisation loc, IntTab *itab=0) const
const Type_info * get_info () const override
virtual const DoubleTab & get_update_distance_interface_sommets () const
const Champ_base & get_update_indicatrice () override
int impr (Sortie &os) const override
Entree & lire_cond_init (Entree &is) override
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual const Maillage_FT_Disc & maillage_interface_pour_post () const
void mettre_a_jour (double temps) override
int preparer_calcul () override
virtual void remailler_interface ()
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
int verif_Cl () const override
const Type_info * get_info () const override
Public Member Functions inherited from Equation_base
virtual void abortTimeStep ()
virtual void associer_domaine_dis (const Domaine_dis_base &)
virtual void associer_pb_base (const Probleme_base &)
virtual void associer_sch_tps_base (const Schema_Temps_base &)
virtual double calculer_pas_de_temps () const
virtual void completer ()
virtual std::vector< YAML_data > data_a_sauvegarder () const
DoubleTab & derivee_en_temps_conv (DoubleTab &, const DoubleTab &)
virtual DoubleTab & derivee_en_temps_inco (DoubleTab &)
const Discretisation_base & discretisation () const
virtual void discretiser ()
virtual const Motcle & domaine_application () const
virtual Domaine_Cl_dis_base & domaine_Cl_dis ()
virtual const Domaine_Cl_dis_base & domaine_Cl_dis () const
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual void imprimer (Sortie &os) const
virtual bool initTimeStep (double dt)
const Nom & le_nom () const override
int limpr () const
virtual void mettre_a_jour (double temps)
virtual int preparer_calcul ()
Probleme_base & probleme ()
const Probleme_base & probleme () const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Schema_Temps_base & schema_temps ()
const Schema_Temps_base & schema_temps () const
Solveur_Masse_base & solv_masse ()
const Solveur_Masse_base & solv_masse () const
Sources & sources ()
const Sources & sources () const
virtual void valider_iteration ()
virtual void verifie_ch_init_nb_comp (const Champ_Inc_base &ch_ref, const int nb_comp) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Transport_Interfaces_FT_Disc
virtual void calculer_distance_interface (const Maillage_FT_Disc &maillage, DoubleTab &distance_elements, DoubleTab &normale_elements, const int n_iter) const
virtual void calculer_distance_interface_sommets (const DoubleTab &dist_elem, const DoubleTab &normale_elem, DoubleTab &dist_som) const
virtual void calculer_vmoy_composantes_connexes (const Maillage_FT_Disc &maillage, const ArrOfInt &compo_connexes_facettes, const int nb_compo_tot, const DoubleTab &vitesse_sommets, DoubleTab &vitesses, DoubleTab &positions) const
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Equation_base
virtual Entree & lire_cl (Entree &)
virtual Entree & lire_cond_init (Entree &)
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual Entree & lire_sources (Entree &)
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
virtual int verif_Cl () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
~Transport_Marqueur_FT()
Transport_Marqueur_FT::~Transport_Marqueur_FT ()
Transport_Marqueur_FT()
Transport_Marqueur_FT::Transport_Marqueur_FT ()
References beta_transfo_, contrib_one_way, diametre_min_, dt_inject_, dt_transfo_, implicite_, methode_calcul_vp_, methode_couplage_, nb_it_, phase_marquee_, t_debut_inject_, t_debut_integr_, t_debut_transfo_, t_derniere_inject_, and t_derniere_transfo_.
Member Function Documentation
cree_instance()
Objet_U * Transport_Marqueur_FT::cree_instance () static
taille_memoire()
unsigned Transport_Marqueur_FT::taille_memoire () const override virtual
Reimplemented from Transport_Interfaces_FT_Disc.
duplique()
int Transport_Marqueur_FT::duplique () const override virtual
Reimplemented from Transport_Interfaces_FT_Disc.
info()
const Type_info * Transport_Marqueur_FT::info () static
get_info()
const Type_info * Transport_Marqueur_FT::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Transport_Interfaces_FT_Disc.
self_cast() [1/2]
Transport_Marqueur_FT & Transport_Marqueur_FT::self_cast (Objet_U & r) static
self_cast() [2/2]
const Transport_Marqueur_FT & Transport_Marqueur_FT::self_cast (const Objet_U & r) static
printOn()
Sortie & Transport_Marqueur_FT::printOn (Sortie & os) const override protected virtual
Parameters
(Sortie& os) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Transport_Interfaces_FT_Disc.
readOn()
Entree & Transport_Marqueur_FT::readOn (Entree & is) override protected virtual
Lecture d'une equation sur un flot d'entree.
Voir Equation_base::readOn() Exception : le bloc de lecture des conditions limites doit etre vide Conditions_limites { }
Reimplemented from Transport_Interfaces_FT_Disc.
References dt_inject_, dt_transfo_, Process::exit(), implicite_, Equation_base::les_sources, Navier_Stokes_std::milieu(), phase_marquee_, Equation_base::probleme(), Equation_base::readOn(), Equation_base::schema_temps(), t_debut_inject_, t_debut_integr_, t_debut_transfo_, t_derniere_inject_, t_derniere_transfo_, and Schema_Temps_base::temps_init().
set_param()
void Transport_Marqueur_FT::set_param (Param & titi) override virtual
Reimplemented from Transport_Interfaces_FT_Disc.
References Param::ajouter(), Param::ajouter_condition(), Param::ajouter_non_std(), contrib_one_way, implicite_, nb_it_, phase_marquee_, and Equation_base::set_param().
lire_motcle_non_standard()
int Transport_Marqueur_FT::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Transport_Interfaces_FT_Disc.
References TRUST_List< _CLASSE_ >::add(), Source_Reaction_Particules::associer_eq_marqueur(), Probleme_base::discretisation(), Process::exit(), lire_injection(), Equation_base::lire_motcle_non_standard(), lire_transformation(), methode_calcul_vp_, methode_couplage_, Equation_base::probleme(), Objet_U::que_suis_je(), Equation_base::sources(), Source::typer_direct(), and TRUST_Deriv< _CLASSE_ >::valeur().
lire_cond_init()
Entree & Transport_Marqueur_FT::lire_cond_init (Entree & is) override virtual
Lecture des conditions initiales dans un flot d'entree.
Le format de lecture est le suivant: { ensemble_points { } lecture de la positions des particules cf Maillage_FT_Disc::readOn [ proprietes_particules { } ] lecture des proprietes materielles des particules cf Prprietes_part_vol::readOn [ t_debut_integration value ] }
Reimplemented from Transport_Interfaces_FT_Disc.
References Param::ajouter(), Param::lire_avec_accolades_depuis(), Transport_Interfaces_FT_Disc::maillage_interface(), Transport_Interfaces_FT_Disc::proprietes_particules(), Objet_U::que_suis_je(), and t_debut_integr_.
lire_cl()
Entree & Transport_Marqueur_FT::lire_cl (Entree & is) override virtual
Lecture des conditions limites sur un flot d'entree.
voir Domaine_Cl_dis_base::readOn
Parameters
(Entree& is) le flot d'entree
Returns
(Entree&) le flot d'entree modifie
Exceptions
le domaine des conditions aux limites discretisee est vide
Reimplemented from Equation_base.
References Param::lire_avec_accolades_depuis(), and Objet_U::que_suis_je().
lire_injection()
Entree & Transport_Marqueur_FT::lire_injection (Entree & is)
References Param::ajouter(), dt_inject_, Param::lire_avec_accolades_depuis(), Transport_Interfaces_FT_Disc::maillage_inject(), Schema_Temps_base::pas_temps_min(), Equation_base::probleme(), Transport_Interfaces_FT_Disc::proprietes_inject(), Objet_U::que_suis_je(), Probleme_base::schema_temps(), and t_debut_inject_.
Referenced by lire_motcle_non_standard().
lire_transformation()
Entree & Transport_Marqueur_FT::lire_transformation (Entree & is)
References Param::ajouter(), beta_transfo_, diametre_min_, dt_transfo_, Process::exit(), Param::lire_avec_accolades_depuis(), Navier_Stokes_std::milieu(), nom_eq_interf_, nom_sz_transfo_, Schema_Temps_base::pas_temps_min(), Equation_base::probleme(), Objet_U::que_suis_je(), Param::REQUIRED, Probleme_base::schema_temps(), and t_debut_transfo_.
Referenced by lire_motcle_non_standard().
discretiser()
void Transport_Marqueur_FT::discretiser () override virtual
Discretisation des champs: - indicatrice_ : champ scalaire discretise aux elements.
typage du maillage et de l'algorithme marching cubes
Reimplemented from Transport_Interfaces_FT_Disc.
References Ensemble_Lagrange_base::associer_domaine(), Champ_Inc_base::associer_eqn(), champ_bidon_, Probleme_base::discretisation(), Transport_Interfaces_FT_Disc::discretiser(), Discretisation_base::discretiser_champ(), Domaine_dis_base::domaine(), Equation_base::domaine_dis(), Transport_Interfaces_FT_Disc::get_probleme_base(), Equation_base::le_nom(), Transport_Interfaces_FT_Disc::maillage_interface(), Schema_Temps_base::nb_valeurs_temporelles(), Equation_base::schema_temps(), and Schema_Temps_base::temps_courant().
preparer_calcul()
int Transport_Marqueur_FT::preparer_calcul () override virtual
Tout ce qui ne depend pas des autres problemes eventuels.
Returns
(int) renvoie toujours 1
Reimplemented from Transport_Interfaces_FT_Disc.
References Objet_U::dimension, Transport_Interfaces_FT_Disc::maillage_interface(), methode_calcul_vp_, Proprietes_part_vol::nb_particules(), Transport_Interfaces_FT_Disc::proprietes_particules(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), source_stockage_, and update_delta_v().
completer()
void Transport_Marqueur_FT::completer () override virtual
Complete la construction (initialisation) des objets : maillage_interface et proprietes_particules_.
   maillage_inject_ et proprietes_inject_
Reimplemented from Equation_base.
References Ensemble_Lagrange_base::associer_domaine(), Maillage_FT_Disc::associer_equation_transport(), Proprietes_part_vol::completer(), Sources::completer(), Maillage_FT_Disc::generer_structure(), Equation_base::initialise_residu(), Equation_base::le_dom_dis, Equation_base::les_sources, Transport_Interfaces_FT_Disc::maillage_inject(), Transport_Interfaces_FT_Disc::maillage_interface(), Proprietes_part_vol::nettoyer(), Transport_Interfaces_FT_Disc::proprietes_inject(), Transport_Interfaces_FT_Disc::proprietes_particules(), and Maillage_FT_Disc::som_init_util().
mettre_a_jour()
void Transport_Marqueur_FT::mettre_a_jour (double temps) override virtual
La valeur de l'inconnue sur le pas de temps a ete calculee.
Cette methode avance le present jusqu'au temps passe en parametre. Elle met aussi a jour les proprietes du milieu.
Parameters
(double temps) le pas de temps de mise a jour
Reimplemented from Transport_Interfaces_FT_Disc.
References integrer_ensemble_lagrange(), Transport_Interfaces_FT_Disc::maillage_interface(), and Maillage_FT_Disc::nettoyer_noeuds_virtuels_et_frontieres().
initTimeStep()
bool Transport_Marqueur_FT::initTimeStep (double dt) override virtual
Allocation et initialisation de l'inconnue et des CLs jusqu'a present+dt.
autres initialisations pour les calculs sur le prochain pas de temps : operateurs, solveur_masse->
Returns
(0 en cas d'erreur, 1 sinon)
Reimplemented from Equation_base.
References Sources::ajouter(), calculer_proprietes_fluide_pos_particules(), contrib_one_way, Objet_U::dimension, dt_p_, imposer_cond_lim(), Equation_base::initTimeStep(), injecter(), Equation_base::les_sources, Transport_Interfaces_FT_Disc::maillage_interface(), methode_calcul_vp_, methode_couplage_, nb_it_, Proprietes_part_vol::nb_particules(), Equation_base::probleme(), Transport_Interfaces_FT_Disc::proprietes_particules(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), resoudre_edo(), Probleme_base::schema_temps(), source_stockage_, t_debut_integr_, Schema_Temps_base::temps_courant(), transformer(), update_delta_v(), and Proprietes_part_vol::vitesse_particules().
imposer_cond_lim()
void Transport_Marqueur_FT::imposer_cond_lim ()
References appliquer_reflexion_vitesse(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Equation_base::domaine_dis(), Transport_Interfaces_FT_Disc::maillage_interface(), Transport_Interfaces_FT_Disc::proprietes_particules(), Maillage_FT_Disc::sommet_elem(), Maillage_FT_Disc::sommet_face_bord(), Maillage_FT_Disc::sommet_ligne_contact(), Maillage_FT_Disc::sommets(), and Proprietes_part_vol::vitesse_particules().
Referenced by initTimeStep().
appliquer_reflexion_vitesse()
void Transport_Marqueur_FT::appliquer_reflexion_vitesse (const double x, const double y, const double z, const int som, int & face_bord, const Domaine_VF & domaine_vf, DoubleTab & vitesse) static
References Objet_U::dimension, Domaine_VF::face_normales(), and Domaine_VF::xv().
Referenced by imposer_cond_lim().
integrer_ensemble_lagrange()
void Transport_Marqueur_FT::integrer_ensemble_lagrange (const double temps) override virtual
Reimplemented from Transport_Interfaces_FT_Disc.
References calcul_vitesse_p(), Maillage_FT_Disc::changer_temps(), Transport_Interfaces_FT_Disc::deplacement_som(), Transport_Interfaces_FT_Disc::maillage_interface(), preparer_tableaux_avant_transport(), Transport_Interfaces_FT_Disc::probleme_base_, Transport_Interfaces_FT_Disc::proprietes_particules(), temps_debut_integration(), Maillage_FT_Disc::transporter_simple(), and update_tableaux_apres_transport().
Referenced by mettre_a_jour().
calculer_proprietes_fluide_pos_particules()
void Transport_Marqueur_FT::calculer_proprietes_fluide_pos_particules (const Maillage_FT_Disc & ens_points)
References Milieu_base::a_gravite(), Solveur_Masse_base::appliquer(), Operateur_Grad::calculer(), Transport_Interfaces_FT_Disc::calculer_scalaire_interpole(), Transport_Interfaces_FT_Disc::calculer_vitesse_transport_interpolee(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Process::exit(), Fluide_Diphasique::fluide_phase(), Navier_Stokes_std::grad_P(), grad_P_som_, Milieu_base::gravite(), Navier_Stokes_std::inconnue(), Navier_Stokes_FT_Disc::is_terme_gravite_rhog(), Milieu_base::masse_volumique(), Navier_Stokes_FT_Disc::milieu(), Navier_Stokes_std::milieu(), Transport_Interfaces_FT_Disc::milieu(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Navier_Stokes_std::operateur_gradient(), phase_marquee_, Navier_Stokes_std::pression(), Equation_base::probleme(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), rho_fluide_som_, Equation_base::solv_masse(), Maillage_FT_Disc::sommet_elem(), Maillage_FT_Disc::sommets(), Transport_Interfaces_FT_Disc::tableaux_positions(), Champ_base::valeur_aux_elems(), Champ_Don_base::valeurs(), Champ_Proto::valeurs(), Transport_Interfaces_FT_Disc::vecteur_elements(), visco_dyn_fluide_som_, Fluide_base::viscosite_dynamique(), and vit_fluide_som_.
Referenced by initTimeStep(), and update_delta_v().
calcul_vitesse_p()
void Transport_Marqueur_FT::calcul_vitesse_p (DoubleTab & deplacement) const
References Transport_Interfaces_FT_Disc::calculer_vitesse_transport_interpolee(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Navier_Stokes_FT_Disc::get_delta_vitesse_interface(), Equation_base::inconnue(), Transport_Interfaces_FT_Disc::maillage_interface(), methode_calcul_vp_, Transport_Interfaces_FT_Disc::probleme_base_, Transport_Interfaces_FT_Disc::proprietes_particules(), and Proprietes_part_vol::vitesse_particules().
Referenced by get_champ_post_FT(), and integrer_ensemble_lagrange().
resoudre_edo()
void Transport_Marqueur_FT::resoudre_edo (DoubleTab & vitesse_p, DoubleTab & source_stockage, const double delta_t)
References contrib_one_way, Objet_U::dimension, implicite_, Proprietes_part_vol::masse_vol_particules(), Proprietes_part_vol::nb_particules(), Transport_Interfaces_FT_Disc::proprietes_particules(), rho_fluide_som_, source_stockage_, and Proprietes_part_vol::volume_particules().
Referenced by initTimeStep().
update_delta_v()
void Transport_Marqueur_FT::update_delta_v (int n_deb, int n_fin, const Maillage_FT_Disc & ens_points, int calc = 1)
References calculer_proprietes_fluide_pos_particules(), Proprietes_part_vol::delta_v(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, implicite_, Process::mp_sum(), Transport_Interfaces_FT_Disc::proprietes_particules(), Maillage_FT_Disc::sommets(), vit_fluide_som_, and Proprietes_part_vol::vitesse_particules().
Referenced by initTimeStep(), injection(), and preparer_calcul().
preparer_tableaux_avant_transport()
void Transport_Marqueur_FT::preparer_tableaux_avant_transport (Maillage_FT_Disc & maillage, Proprietes_part_vol & proprietes)
References Proprietes_part_vol::delta_v(), Maillage_FT_Disc::desc_sommets(), Proprietes_part_vol::diametre_particules(), Proprietes_part_vol::masse_vol_particules(), Process::mp_sum(), Proprietes_part_vol::nb_particules(), Maillage_FT_Disc::preparer_tableau_avant_transport(), Proprietes_part_vol::temperature_particules(), Proprietes_part_vol::vitesse_particules(), and Proprietes_part_vol::volume_particules().
Referenced by integrer_ensemble_lagrange().
update_tableaux_apres_transport()
void Transport_Marqueur_FT::update_tableaux_apres_transport (Maillage_FT_Disc & maillage, Proprietes_part_vol & proprietes)
References Proprietes_part_vol::delta_v(), Maillage_FT_Disc::desc_sommets(), Proprietes_part_vol::diametre_particules(), Proprietes_part_vol::fixer_nb_particules(), Proprietes_part_vol::masse_vol_particules(), Process::mp_sum(), Proprietes_part_vol::nb_particules(), Maillage_FT_Disc::nb_sommets(), Proprietes_part_vol::temperature_particules(), Maillage_FT_Disc::update_tableau_apres_transport(), Proprietes_part_vol::vitesse_particules(), and Proprietes_part_vol::volume_particules().
Referenced by integrer_ensemble_lagrange().
linject()
int Transport_Marqueur_FT::linject (double temps) const inline
References dt_inject_, t_debut_inject_, and t_derniere_inject_.
Referenced by injecter().
injecter()
void Transport_Marqueur_FT::injecter (double temps)
References injection(), linject(), Transport_Interfaces_FT_Disc::maillage_inject(), Transport_Interfaces_FT_Disc::proprietes_inject(), and t_derniere_inject_.
Referenced by initTimeStep().
injection()
void Transport_Marqueur_FT::injection (const Maillage_FT_Disc & maill_inject, const Proprietes_part_vol & propr_inject)
References ajouter_points(), Proprietes_part_vol::ajouter_proprietes(), Proprietes_part_vol::nb_particules(), Transport_Interfaces_FT_Disc::proprietes_particules(), and update_delta_v().
Referenced by injecter(), and transformer().
ajouter_points()
void Transport_Marqueur_FT::ajouter_points (const Maillage_FT_Disc & maillage_inject)
References Maillage_FT_Disc::ajouter_maillage(), and Transport_Interfaces_FT_Disc::maillage_interface().
Referenced by injection().
ltransfo()
int Transport_Marqueur_FT::ltransfo (double temps) const inline
References dt_transfo_, t_debut_transfo_, and t_derniere_transfo_.
Referenced by transformer().
transformer()
void Transport_Marqueur_FT::transformer (double temps)
References injection(), ltransfo(), t_derniere_transfo_, transformation(), and transformer_particules().
Referenced by initTimeStep().
transformer_particules()
void Transport_Marqueur_FT::transformer_particules ()
References Probleme_base::equation(), Process::exit(), Transport_Interfaces_FT_Disc::maillage_interface(), Equation_base::milieu(), Maillage_FT_Disc::nettoyer_phase(), nom_eq_interf_, phase_marquee_, and Equation_base::probleme().
Referenced by transformer().
transformation()
void Transport_Marqueur_FT::transformation (Maillage_FT_Disc & maillage, Proprietes_part_vol & proprietes)
References calcul_proprietes_geometriques(), Transport_Interfaces_FT_Disc::calculer_composantes_connexes_pour_suppression(), Transport_Interfaces_FT_Disc::calculer_vitesse_transport_interpolee(), construction_ensemble_proprietes(), detection_groupes_a_supprimer(), Transport_Interfaces_FT_Disc::get_update_indicatrice(), Equation_base::inconnue(), nom_eq_interf_, Transport_Interfaces_FT_Disc::probleme_base_, Transport_Interfaces_FT_Disc::suppression_interfaces(), Champ_Proto::valeurs(), and Proprietes_part_vol::vitesse_particules().
Referenced by transformer().
calcul_proprietes_geometriques()
void Transport_Marqueur_FT::calcul_proprietes_geometriques (const IntVect & num_compo, const int nb_compo_glob, const DoubleTab & indic, ArrOfDouble & volumes, DoubleTab & positions)
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Equation_base::domaine_dis(), Domaine_dis_base::nb_elem(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), Domaine_VF::volumes(), and Domaine_VF::xp().
Referenced by transformation().
detection_groupes_a_supprimer()
void Transport_Marqueur_FT::detection_groupes_a_supprimer (const ArrOfDouble & volumes, const DoubleTab & positions, ArrOfInt & flags_compo_a_supprimer)
References Domaine_32_64< _SIZE_ >::chercher_elements(), Domaine_dis_base::domaine(), Equation_base::domaine_dis(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and Domaine_VF::volumes().
Referenced by transformation().
construction_ensemble_proprietes()
void Transport_Marqueur_FT::construction_ensemble_proprietes (const IntVect & num_compo, const int nb_compo, Maillage_FT_Disc & ens_points, Proprietes_part_vol & propri, const ArrOfInt & flags_compos_a_supprimer, const DoubleTab & positions, const ArrOfDouble & volumes)
References Ensemble_Lagrange_base::associer_domaine(), Maillage_FT_Disc::associer_equation_transport(), Proprietes_part_vol::completer(), Proprietes_part_vol::delta_v(), Proprietes_part_vol::diametre_particules(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Proprietes_part_vol::fixer_nb_particules(), Fluide_Diphasique::fluide_phase(), Maillage_FT_Disc::generer_structure(), Equation_base::le_dom_dis, Proprietes_part_vol::masse_vol_particules(), Milieu_base::masse_volumique(), Transport_Interfaces_FT_Disc::milieu(), Proprietes_part_vol::nettoyer(), phase_marquee_, Equation_base::probleme(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Maillage_FT_Disc::som_init_util(), Ensemble_Lagrange_base::sommets_lu(), Proprietes_part_vol::temperature_particules(), Champ_Proto::valeurs(), Proprietes_part_vol::vitesse_particules(), and Proprietes_part_vol::volume_particules().
Referenced by transformation().
sauvegarder()
int Transport_Marqueur_FT::sauvegarder (Sortie & os) const override virtual
On sauvegarde l'inconnue de l'equation sur un flot de sortie.
Parameters
(Sortie& os)
Returns
(int) le code de retour de Champ_Inc::sauvegarder()
Reimplemented from Transport_Interfaces_FT_Disc.
reprendre()
int Transport_Marqueur_FT::reprendre (Entree & fich) override virtual
On reprend l'inconnue a partir d'un flot d'entree.
[ON CHERCHE L'INCONNUE PAR SON NOM] [ON LIT L'INCONNUE] Voir Champ_Inc::reprendre(Entree&)
Parameters
(Entree& fich) le flot d'entree (fichier) a lire
Returns
(int) renvoie toujours 1
Exceptions
erreur de reprise, fin de fichier atteinte sans trouver l'inconnue
Reimplemented from Transport_Interfaces_FT_Disc.
creer_champ()
void Transport_Marqueur_FT::creer_champ (const Motcle & motlu) override virtual
Reimplemented from Equation_base.
References Champs_compris_T< FIELD_TYPE >::ajoute_champ(), Equation_base::champs_compris_, Equation_base::creer_champ(), densite_particules_, Probleme_base::discretisation(), Discretisation_base::discretiser_champ(), Equation_base::domaine_dis(), Objet_U_ptr::non_nul(), Equation_base::probleme(), Equation_base::schema_temps(), Schema_Temps_base::temps_courant(), TRUST_Deriv< _CLASSE_ >::valeur(), and volume_particules_.
get_champ()
const Champ_base & Transport_Marqueur_FT::get_champ (const Motcle & nom) const override virtual
Reimplemented from Equation_base.
References calculer_valeurs_densite(), calculer_valeurs_volumes(), Equation_base::champs_compris_, Champ_base::changer_temps(), densite_particules_, Champs_compris_T< FIELD_TYPE >::get_champ(), Nom::getString(), Equation_base::has_champ(), Equation_base::schema_temps(), Schema_Temps_base::temps_courant(), TRUST_Deriv< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), and volume_particules_.
Referenced by has_champ().
has_champ() [1/2]
bool Transport_Marqueur_FT::has_champ (const Motcle & nom, TRUST_Ref< Champ_base * > & ref_champ) const override virtual
Reimplemented from Equation_base.
References get_champ(), and Equation_base::has_champ().
has_champ() [2/2]
bool Transport_Marqueur_FT::has_champ (const Motcle & nom) const override virtual
Reimplemented from Equation_base.
References Equation_base::has_champ().
get_noms_champs_postraitables()
void Transport_Marqueur_FT::get_noms_champs_postraitables (Noms & nom, Option opt = NONE) const override virtual
Reimplemented from Equation_base.
References TRUST_Vector< _CLASSE_ >::add(), Equation_base::champs_compris_, Equation_base::get_noms_champs_postraitables(), and Champs_compris_T< FIELD_TYPE >::liste_noms_compris().
get_champ_post_FT() [1/2]
int Transport_Marqueur_FT::get_champ_post_FT (const Motcle & champ, Postraitement_base::Localisation loc, DoubleTab * ftab = 0) const override virtual
Cherche le champ discret aux interfaces dont le nom est "champ", et verifie qu'il peut etre postraite a la localisation demandee (loc).
Si oui on renvoie 1 et, si ftab est non nul, on remplit le champ ftab avec le champ demande. Si non, on renvoie 0. (la fonction est appelee avec ftab=0 lors de la lecture du postraitement, car on n'a pas besoin de la valeur du champ, on veut seulement verifier qu'il existe).
Reimplemented from Transport_Interfaces_FT_Disc.
References calcul_vitesse_p(), Postraitement_base::demande_description, Postraitement_base::ELEMENTS, Process::exit(), methode_calcul_vp_, Transport_Interfaces_FT_Disc::proprietes_particules(), Motcles::search(), and Postraitement_base::SOMMETS.
get_champ_post_FT() [2/2]
int Transport_Marqueur_FT::get_champ_post_FT (const Motcle & champ, Postraitement_base::Localisation loc, IntTab * itab = 0) const override virtual
Voir l'autre get_champ_post_FT.
Cette fonction est specifique aux champs d'entiers.
Reimplemented from Transport_Interfaces_FT_Disc.
calculer_valeurs_densite()
const DoubleTab & Transport_Marqueur_FT::calculer_valeurs_densite (DoubleTab & val_densite) const
References Transport_Interfaces_FT_Disc::maillage_interface(), Maillage_FT_Disc::nb_sommets(), Maillage_FT_Disc::sommet_elem(), and Maillage_FT_Disc::type_statut().
Referenced by get_champ().
calculer_valeurs_volumes()
const DoubleTab & Transport_Marqueur_FT::calculer_valeurs_volumes (DoubleTab & val_volume) const
References Transport_Interfaces_FT_Disc::maillage_interface(), Maillage_FT_Disc::nb_sommets(), Transport_Interfaces_FT_Disc::proprietes_particules(), Maillage_FT_Disc::sommet_elem(), Maillage_FT_Disc::type_statut(), and Proprietes_part_vol::volume_particules().
Referenced by get_champ().
inconnue() [1/2]
const Champ_Inc_base & Transport_Marqueur_FT::inconnue () const override virtual
Reimplemented from Transport_Interfaces_FT_Disc.
References champ_bidon_.
inconnue() [2/2]
Champ_Inc_base & Transport_Marqueur_FT::inconnue () override virtual
Reimplemented from Transport_Interfaces_FT_Disc.
References champ_bidon_.
vitesse_fluide()
const DoubleTab & Transport_Marqueur_FT::vitesse_fluide () const inline
References vit_fluide_som_.
Referenced by Source_Action_Particules::vitesse_fluide().
rho_fluide()
const DoubleTab & Transport_Marqueur_FT::rho_fluide () const inline
References rho_fluide_som_.
Referenced by Source_Action_Particules::rho_fluide().
visco_dyn_fluide()
const DoubleTab & Transport_Marqueur_FT::visco_dyn_fluide () const inline
References visco_dyn_fluide_som_.
Referenced by Source_Action_Particules::visco_dyn_fluide().
grad_pression()
const DoubleTab & Transport_Marqueur_FT::grad_pression () const inline
References grad_P_som_.
Referenced by Source_Action_Particules::grad_pression().
temps_debut_integration()
const double & Transport_Marqueur_FT::temps_debut_integration () const inline
References t_debut_integr_.
Referenced by integrer_ensemble_lagrange().
dela_t()
const double & Transport_Marqueur_FT::dela_t () const inline
References dt_p_.
Referenced by Source_Masse_Ajoutee::ajouter().
resol_implicite()
const int & Transport_Marqueur_FT::resol_implicite () const inline
References implicite_.
Referenced by Source_Masse_Ajoutee::ajouter().
source_stockage()
const DoubleTab & Transport_Marqueur_FT::source_stockage () const inline
References source_stockage_.
Member Data Documentation
info_obj
const Type_info Transport_Marqueur_FT::info_obj static
densite_particules_
TRUST_Deriv< Champ_Fonc_base > Transport_Marqueur_FT::densite_particules_ protected
Referenced by creer_champ(), and get_champ().
volume_particules_
TRUST_Deriv< Champ_Fonc_base > Transport_Marqueur_FT::volume_particules_ protected
Referenced by creer_champ(), and get_champ().
t_debut_integr_
double Transport_Marqueur_FT::t_debut_integr_ protected
Referenced by initTimeStep(), lire_cond_init(), readOn(), temps_debut_integration(), and Transport_Marqueur_FT().
t_debut_inject_
double Transport_Marqueur_FT::t_debut_inject_ protected
Referenced by linject(), lire_injection(), readOn(), and Transport_Marqueur_FT().
t_debut_transfo_
double Transport_Marqueur_FT::t_debut_transfo_ protected
Referenced by lire_transformation(), ltransfo(), readOn(), and Transport_Marqueur_FT().
t_derniere_inject_
double Transport_Marqueur_FT::t_derniere_inject_ protected
Referenced by injecter(), linject(), readOn(), and Transport_Marqueur_FT().
t_derniere_transfo_
double Transport_Marqueur_FT::t_derniere_transfo_ protected
Referenced by ltransfo(), readOn(), transformer(), and Transport_Marqueur_FT().
dt_inject_
double Transport_Marqueur_FT::dt_inject_ protected
Referenced by linject(), lire_injection(), readOn(), and Transport_Marqueur_FT().
dt_transfo_
double Transport_Marqueur_FT::dt_transfo_ protected
Referenced by lire_transformation(), ltransfo(), readOn(), and Transport_Marqueur_FT().
nom_sz_transfo_
Noms Transport_Marqueur_FT::nom_sz_transfo_ protected
Referenced by lire_transformation().
diametre_min_
double Transport_Marqueur_FT::diametre_min_ protected
Referenced by lire_transformation(), and Transport_Marqueur_FT().
beta_transfo_
double Transport_Marqueur_FT::beta_transfo_ protected
Referenced by lire_transformation(), and Transport_Marqueur_FT().
dt_p_
double Transport_Marqueur_FT::dt_p_ protected
Referenced by dela_t(), and initTimeStep().
nb_it_
int Transport_Marqueur_FT::nb_it_ protected
Referenced by initTimeStep(), set_param(), and Transport_Marqueur_FT().
implicite_
int Transport_Marqueur_FT::implicite_ protected
Referenced by readOn(), resol_implicite(), resoudre_edo(), set_param(), Transport_Marqueur_FT(), and update_delta_v().
champ_bidon_
TRUST_Deriv< Champ_Inc_base > Transport_Marqueur_FT::champ_bidon_ protected
Referenced by discretiser(), and inconnue().
phase_marquee_
int Transport_Marqueur_FT::phase_marquee_ protected
Referenced by calculer_proprietes_fluide_pos_particules(), construction_ensemble_proprietes(), readOn(), set_param(), transformer_particules(), and Transport_Marqueur_FT().
nom_eq_interf_
Nom Transport_Marqueur_FT::nom_eq_interf_ protected
Referenced by lire_transformation(), transformation(), and transformer_particules().
methode_calcul_vp_
Methode_calcul_vp Transport_Marqueur_FT::methode_calcul_vp_ protected
Referenced by calcul_vitesse_p(), get_champ_post_FT(), initTimeStep(), lire_motcle_non_standard(), preparer_calcul(), and Transport_Marqueur_FT().
methode_couplage_
Methode_couplage Transport_Marqueur_FT::methode_couplage_ protected
Referenced by initTimeStep(), lire_motcle_non_standard(), and Transport_Marqueur_FT().
vit_fluide_som_
DoubleTab Transport_Marqueur_FT::vit_fluide_som_ protected
Referenced by calculer_proprietes_fluide_pos_particules(), update_delta_v(), and vitesse_fluide().
rho_fluide_som_
DoubleTab Transport_Marqueur_FT::rho_fluide_som_ protected
Referenced by calculer_proprietes_fluide_pos_particules(), resoudre_edo(), and rho_fluide().
visco_dyn_fluide_som_
DoubleTab Transport_Marqueur_FT::visco_dyn_fluide_som_ protected
Referenced by calculer_proprietes_fluide_pos_particules(), and visco_dyn_fluide().
grad_P_som_
DoubleTab Transport_Marqueur_FT::grad_P_som_ protected
Referenced by calculer_proprietes_fluide_pos_particules(), and grad_pression().
contrib_one_way
int Transport_Marqueur_FT::contrib_one_way protected
Referenced by initTimeStep(), resoudre_edo(), set_param(), and Transport_Marqueur_FT().
source_stockage_
DoubleTab Transport_Marqueur_FT::source_stockage_ protected
Referenced by initTimeStep(), preparer_calcul(), resoudre_edo(), and source_stockage().