TrioCFD: Ecrire_MED_32_64< _SIZE_ > Class Template Reference
Ecrire_MED_32_64< _SIZE_ > Class Template Reference
#include <Ecrire_MED.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Interprete
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Interprete
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Interprete
static Objet_U & objet (const Nom &)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
template<typename _SIZE_>
class Ecrire_MED_32_64< _SIZE_ >
Warning: fields and everything related to discretised domains can only be invoked with the 32 bit version.
Member Typedef Documentation
int_t
template<typename _SIZE_ > using Ecrire_MED_32_64< _SIZE_ >::int_t = _SIZE_
ArrOfInt_t
template<typename _SIZE_ > using Ecrire_MED_32_64< _SIZE_ >::ArrOfInt_t = ArrOfInt_T<_SIZE_>
IntTab_t
template<typename _SIZE_ > using Ecrire_MED_32_64< _SIZE_ >::IntTab_t = IntTab_T<_SIZE_>
Domaine_t
template<typename _SIZE_ > using Ecrire_MED_32_64< _SIZE_ >::Domaine_t = Domaine_32_64<_SIZE_>
Constructor & Destructor Documentation
Ecrire_MED_32_64() [1/2]
template<typename _T_ > Ecrire_MED_32_64< _T_ >::Ecrire_MED_32_64
~Ecrire_MED_32_64()
template<typename _T_ > Ecrire_MED_32_64< _T_ >::~Ecrire_MED_32_64
Ecrire_MED_32_64() [2/2]
template<typename _SIZE_ > Ecrire_MED_32_64< _SIZE_ >::Ecrire_MED_32_64 (const Nom & file_name, const Domaine_t & dom)
Member Function Documentation
cree_instance()
template<typename _T_ > Objet_U * Ecrire_MED_32_64< _T_ >::cree_instance static
taille_memoire()
template<typename _T_ > unsigned Ecrire_MED_32_64< _T_ >::taille_memoire override virtual
Implements Objet_U.
duplique()
template<typename _T_ > int Ecrire_MED_32_64< _T_ >::duplique override virtual
Implements Objet_U.
info()
template<typename _T_ > const Type_info * Ecrire_MED_32_64< _T_ >::info static
get_info()
template<typename _T_ > const Type_info * Ecrire_MED_32_64< _T_ >::get_info override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
template<typename _T_ > Ecrire_MED_32_64< _T_ > & Ecrire_MED_32_64< _T_ >::self_cast (Objet_U & r) static
self_cast() [2/2]
template<typename _T_ > const Ecrire_MED_32_64< _T_ > & Ecrire_MED_32_64< _T_ >::self_cast (const Objet_U & r) static
printOn()
template<typename _SIZE_ > Sortie & Ecrire_MED_32_64< _SIZE_ >::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
References Interprete::printOn().
readOn()
template<typename _SIZE_ > Entree & Ecrire_MED_32_64< _SIZE_ >::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
References Interprete::readOn().
set_file_name_and_dom()
template<typename _SIZE_ > void Ecrire_MED_32_64< _SIZE_ >::set_file_name_and_dom (const Nom & file_name, const Domaine_t & dom, const Domaine_dis_base * dom_dis = nullptr)
References Sortie_Fichier_base::root.
Referenced by Format_Post_Med::ecrire_champ_med(), Format_Post_Med::ecrire_domaine_dual(), and Format_Post_Med::ecrire_domaine_med().
set_major_mode()
template<typename _SIZE_ > void Ecrire_MED_32_64< _SIZE_ >::set_major_mode (bool majorMod) inline
! Set major mode for MED file writing. See major_mode member below.
References Ecrire_MED_32_64< _SIZE_ >::major_mode_.
Referenced by Format_Post_Med_major::Format_Post_Med_major(), and Format_Post_Med::reset().
get_major_mode()
template<typename _SIZE_ > bool Ecrire_MED_32_64< _SIZE_ >::get_major_mode () inline
References Ecrire_MED_32_64< _SIZE_ >::major_mode_.
Referenced by Format_Post_Med::ecrire_domaine_med().
version()
template<typename _SIZE_ > Nom Ecrire_MED_32_64< _SIZE_ >::version () inline
Referenced by Format_Post_Med::ecrire_domaine_med().
interpreter()
template<typename _SIZE_ > Entree & Ecrire_MED_32_64< _SIZE_ >::interpreter (Entree & is) override virtual
Implements Interprete.
References Objet_U::que_suis_je().
ecrire_domaine()
template<typename _SIZE_ > void Ecrire_MED_32_64< _SIZE_ >::ecrire_domaine (bool append = true)
Referenced by Modele_turbulence_hyd_0_eq_base::completer().
ecrire_domaine_dual()
template<typename _SIZE_ > void Ecrire_MED_32_64< _SIZE_ >::ecrire_domaine_dual (bool append = true)
Referenced by Format_Post_Med::ecrire_domaine_dual().
ecrire_domaine_dis()
template<typename _SIZE_ > void Ecrire_MED_32_64< _SIZE_ >::ecrire_domaine_dis (bool append = true)
Referenced by Format_Post_Med::ecrire_domaine_med().
ecrire_champ() [1/2]
template<typename _SIZE_ > void Ecrire_MED_32_64< _SIZE_ >::ecrire_champ (const Nom & type, const Nom & nom_cha1, const DoubleTab & val, const Noms & unite, const Noms & noms_compo, const Nom & type_elem, double time)
Referenced by Format_Post_Med::ecrire_champ_med(), and Modele_turbulence_hyd_0_eq_base::imprimer().
ecrire_champ() [2/2]
template<typename _SIZE_ > void Ecrire_MED_32_64< _SIZE_ >::ecrire_champ (const Nom & type, const Nom & nom_cha1, const DoubleTab & val, const Noms & unite, const Nom & type_elem, double time, const Champ_Inc_base & le_champ)
get_bords_infos()
template<typename _SIZE_ > void Ecrire_MED_32_64< _SIZE_ >::get_bords_infos (Noms & noms_bords_and_jnts, ArrOfInt_t & sz_bords_and_jnts) const protected
fill_faces_and_boundaries()
template<typename _SIZE_ > void Ecrire_MED_32_64< _SIZE_ >::fill_faces_and_boundaries () protected
info_obj()
const Type_info Ecrire_MED_32_64< trustIdType >::info_obj ("Write_MED" "_64" , Ecrire_MED_32_64< trustIdType >::cree_instance , 1 , Ecrire_MED_32_64bases< trustIdType >)
Member Data Documentation
info_obj
template<typename _SIZE_ > const Type_info Ecrire_MED_32_64< _SIZE_ >::info_obj static
major_mode_
template<typename _SIZE_ > bool Ecrire_MED_32_64< _SIZE_ >::major_mode_ = false protected
False by default. If true, the MED file will be written in the major mode of the release version (3.0 for example if current MED version is 3.2)
Referenced by Ecrire_MED_32_64< _SIZE_ >::get_major_mode(), and Ecrire_MED_32_64< _SIZE_ >::set_major_mode().
nom_fichier_
template<typename _SIZE_ > Nom Ecrire_MED_32_64< _SIZE_ >::nom_fichier_ protected
Name of the MED file to write.
dom_
template<typename _SIZE_ > TRUST_Ref< Domaine_t *> Ecrire_MED_32_64< _SIZE_ >::dom_ protected
Domain that will be written.
timestep_
template<typename _SIZE_ > std::map<std::string, int> Ecrire_MED_32_64< _SIZE_ >::timestep_ protected
mesh_dimension_
template<typename _SIZE_ > int Ecrire_MED_32_64< _SIZE_ >::mesh_dimension_ = -1 protected
domaine_dis_
template<typename _SIZE_ > TRUST_Ref< Domaine_VF *> Ecrire_MED_32_64< _SIZE_ >::domaine_dis_ protected