TrioCFD: Remaillage_FT Class Reference
Remaillage_FT Class Reference
#include <Remaillage_FT.h>
Public Member Functions
void associer_domaine (const Domaine_dis_base &domaine_dis)
void barycentrer_lisser_apres_remaillage (Maillage_FT_Disc &maillage, ArrOfDouble &var_volume)
void barycentrer_lisser_systematique (double temps, Maillage_FT_Disc &maillage)
double calculer_variation_volume (const Maillage_FT_Disc &maillage, const DoubleTab &position_initiale, ArrOfDouble &varVolume) const
void corriger_volume (Maillage_FT_Disc &maillage, ArrOfDouble &var_volume)
const Type_info * get_info () const override
void lisser_dvolume (const Maillage_FT_Disc &maillage, ArrOfDouble &var_volume, const int nb_iterations) const
virtual void regulariser_courbure (Maillage_FT_Disc &maillage, const double coeff, ArrOfDouble &dvolume) const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
void set_param (Param &p)
int supprimer_facettes_nulles (Maillage_FT_Disc &maillage) const
int traite_adherence (Maillage_FT_Disc &maillage) const
int traite_decollement (Maillage_FT_Disc &maillage, const DoubleTab &deplacement) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
int calculer_barycentre_facettes_voisines (const Maillage_FT_Disc &maillage, DoubleTab &barycentres) const
int calculer_connectivites_sommetFacettes (const Maillage_FT_Disc &maillage, ArrOfInt &fa7VoisinesSom_index, IntTab &fa7VoisinesSom_data) const
int calculer_correction_deplacement (DoubleTab &deplacement, const ArrOfDouble &varVolume, const DoubleTab &deplacement_varVolume, const ArrOfDouble &norme2_deplacement_varVolume) const
int calculer_differentielle_volume (const Maillage_FT_Disc &maillage, DoubleTab &differentielle_volume) const
virtual double calculer_longueurIdeale2_arete (const Maillage_FT_Disc &maillage, int som0, double x, double y, double z) const
double calculer_variation_volume_facette_2D (int fa7, const Maillage_FT_Disc &maillage, const DoubleTab &position_initiale) const
double calculer_volume_sommets_supprimes (const Maillage_FT_Disc &maillage, const ArrOfInt &tab_somSupp, ArrOfDouble &varVolume) const
int diviser_grandes_aretes (Maillage_FT_Disc &maillage) const
int nettoyer_maillage (Maillage_FT_Disc &maillage) const
int permuter_aretes (Maillage_FT_Disc &maillage) const
double qualiteTriangle (const FTd_vecteur3 &som0, const FTd_vecteur3 &som1, const FTd_vecteur3 &som2, double &aire) const
double redistribuer_sommets (Maillage_FT_Disc &maillage, const double relaxation_direction_tangente, const double relaxation_direction_normale, ArrOfDouble &var_volume_impose, ArrOfDouble &var_volume_obtenu) const
double regulariser_maillage (Maillage_FT_Disc &maillage, ArrOfDouble &var_volume, const double facteur_barycentrage_tangent, const double coeff_lissage, const int nb_iter_barycentrage, const int nb_iter_lissage, const int max_nb_iter_correction_volume, const double seuil_dvolume) const
int supprimer_doublons_facettes (Maillage_FT_Disc &maillage) const
int supprimer_facettes_bord (Maillage_FT_Disc &maillage) const
int supprimer_petites_aretes (Maillage_FT_Disc &maillage, ArrOfDouble &varVolume) const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
See also
Transport_Interfaces_FT_Disc Maillage_FT_Disc
Constructor & Destructor Documentation
~Remaillage_FT()
Remaillage_FT::~Remaillage_FT ()
Remaillage_FT()
Remaillage_FT::Remaillage_FT ()
Member Function Documentation
cree_instance()
Objet_U * Remaillage_FT::cree_instance () static
taille_memoire()
unsigned Remaillage_FT::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Remaillage_FT_IJK.
duplique()
int Remaillage_FT::duplique () const override virtual
Implements Objet_U.
Reimplemented in Remaillage_FT_IJK.
info()
const Type_info * Remaillage_FT::info () static
get_info()
const Type_info * Remaillage_FT::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
Reimplemented in Remaillage_FT_IJK.
self_cast() [1/2]
Remaillage_FT & Remaillage_FT::self_cast (Objet_U & r) static
self_cast() [2/2]
const Remaillage_FT & Remaillage_FT::self_cast (const Objet_U & r) static
printOn()
Sortie & Remaillage_FT::printOn (Sortie & x) const override protected virtual
Cette fonction ne doit pas etre appelee.
Reimplemented from Objet_U.
Reimplemented in Remaillage_FT_IJK.
readOn()
Entree & Remaillage_FT::readOn (Entree & is) override protected virtual
Lecture des parametres de remaillage.
Reimplemented from Objet_U.
Reimplemented in Remaillage_FT_IJK.
References Param::ajouter(), Objet_U::dimension, equilateral_, Process::exit(), facteur_longueur_ideale_, Param::lire_avec_accolades_depuis(), lissage_courbure_iterations_old_, Objet_U::que_suis_je(), set_param(), and valeur_longueur_fixe_.
set_param()
void Remaillage_FT::set_param (Param & p)
Methode appelee par readOn.
Declaration des parametres a lire dans le .data
References Param::ajouter(), critere_arete_, dt_lissage_, dt_remaillage_, facteur_longueur_ideale_, impr_, lissage_courbure_coeff_, lissage_courbure_iterations_old_, lissage_courbure_iterations_si_remaillage_, lissage_courbure_iterations_systematique_, lissage_critere_, nb_iter_bary_volume_seul_, nb_iter_barycentrage_, nb_iter_remaillage_, relax_barycentrage_, seuil_dvolume_residuel_, and valeur_longueur_fixe_.
Referenced by readOn().
associer_domaine()
void Remaillage_FT::associer_domaine (const Domaine_dis_base & domaine_dis)
Cette fonction stocke le domaine_dis dans refdomaine_dis_.
Parameters
(domaine_dis) domaine discretisee de calcul
Returns
le flot d'entree
References refdomaine_VF_.
Referenced by Transport_Interfaces_FT_Disc::discretiser(), and IJK_Interfaces::initialize().
supprimer_facettes_nulles()
int Remaillage_FT::supprimer_facettes_nulles (Maillage_FT_Disc & maillage) const
Cette fonction "supprime" les facettes de surface nulle : Elle les reduit a 1 sommet (le sommet 0, pour ne pas changer de processeur)
Parameters
(maillage) maillage a remailler
Returns
(int) 1 si le remaillage s'est deroule correctement, 0 sinon
References Maillage_FT_Disc::check_mesh(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Maillage_FT_Disc::facettes_, Maillage_FT_Disc::get_update_surface_facettes(), Process::Journal(), Maillage_FT_Disc::maillage_modifie(), Maillage_FT_Disc::MINIMAL, Maillage_FT_Disc::nb_facettes(), and nettoyer_maillage().
traite_adherence()
int Remaillage_FT::traite_adherence (Maillage_FT_Disc & maillage) const
Cette fonction permet de gerer l'adherence de l'interface a la paroi Si une facette possede 3 sommets sur un paroi, elle est supprimee.
Parameters
(maillage) maillage a traiter
Returns
(int) 1 si le remaillage s'est deroule correctement, 0 sinon
References Process::Journal(), Maillage_FT_Disc::maillage_modifie(), Maillage_FT_Disc::MINIMAL, nettoyer_maillage(), and supprimer_facettes_bord().
Referenced by Transport_Interfaces_FT_Disc::deplacer_maillage_ft_v_fluide().
traite_decollement()
int Remaillage_FT::traite_decollement (Maillage_FT_Disc & maillage, const DoubleTab & deplacement) const
Cette fonction permet de gerer le decollement de l'interface de la paroi Si un sommet de bord n'a pas de sommet voisin de bord.
et que son deplacement tend a le faire rentrer dans le domaine,
il est marque comme sommet interne
Parameters
(maillage) maillage a traiter
(deplacement) vecteur deplacement des sommets
Returns
(int) 1 si le remaillage s'est deroule correctement, 0 sinon
References Desc_Structure_FT::collecter_espace_virtuel(), Maillage_FT_Disc::desc_sommets(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Desc_Structure_FT::echange_espace_virtuel(), MD_Vector_tools::EV_SOMME, Maillage_FT_Disc::facettes(), impr_, Process::Journal(), Maillage_FT_Disc::maillage_modifie(), Maillage_FT_Disc::MINIMAL, Maillage_FT_Disc::nb_facettes(), Maillage_FT_Disc::nb_sommets(), Maillage_FT_Disc::printSom(), refdomaine_VF_, Maillage_FT_Disc::sommet_elem_, Maillage_FT_Disc::sommet_face_bord_, Maillage_FT_Disc::sommet_ligne_contact(), and Maillage_FT_Disc::sommets().
Referenced by Transport_Interfaces_FT_Disc::deplacer_maillage_ft_v_fluide().
a_remailler()
int Remaillage_FT::a_remailler (double temps, const Maillage_FT_Disc & maillage) const
References dt_remaillage_, and temps_dernier_remaillage_.
Referenced by Topologie_Maillage_FT::remailler_interface(), and IJK_Interfaces::remailler_interface().
a_lisser()
int Remaillage_FT::a_lisser (double temps) const
References dt_lissage_, and temps_dernier_lissage_.
Referenced by Topologie_Maillage_FT::remailler_interface().
remaillage_local_interface()
void Remaillage_FT::remaillage_local_interface (double temps, Maillage_FT_Disc & maillage)
Verifie les criteres de remaillage locaux (longueur des aretes) et effectue les remaillages locaux si necessaires.
References barycentrer_lisser_apres_remaillage(), Statistiques::begin_count(), Comm_Group::check_enabled(), Maillage_FT_Disc::check_mesh(), diviser_grandes_aretes(), Statistiques::end_count(), Process::je_suis_maitre(), Process::Journal(), nb_iter_remaillage_, Maillage_FT_Disc::nb_sommets(), Maillage_FT_Disc::nettoyer_elements_virtuels(), nettoyer_maillage(), Statistiques::new_counter(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), supprimer_doublons_facettes(), supprimer_petites_aretes(), temps_, temps_dernier_lissage_, temps_dernier_remaillage_, and variation_volume_.
Referenced by Topologie_Maillage_FT::remailler_interface(), and Remailleur_Collision_FT_Thomas::traite_RuptureCoalescenceInterfaces_Conservatif().
corriger_volume()
void Remaillage_FT::corriger_volume (Maillage_FT_Disc & maillage, ArrOfDouble & var_volume)
deplacement des sommets se sorte a produire la variation de volume prescrite a chaque sommet.
Precondition: pas de facettes virtuelles
References corriger_volume_(), and nb_iter_bary_volume_seul_.
Referenced by Remailleur_Collision_FT_Thomas::traite_RuptureCoalescenceInterfaces_Conservatif().
corriger_volume_()
void Remaillage_FT::corriger_volume_ (Maillage_FT_Disc & maillage, ArrOfDouble & var_volume, const int nb_iter_corrections_vol)
References nettoyer_maillage(), regulariser_maillage(), seuil_dvolume_residuel_, and supprimer_facettes_bord().
Referenced by corriger_volume(), and Transport_Interfaces_FT_Disc::deplacer_maillage_ft_v_fluide().
barycentrer_lisser_systematique()
void Remaillage_FT::barycentrer_lisser_systematique (double temps, Maillage_FT_Disc & maillage)
applique barycentrage, lissage et correction de volume.
On applique le nombre d'iterations de lissage systematique.
Precondition: pas de facettes virtuelles
References Statistiques::begin_count(), Statistiques::end_count(), Process::je_suis_maitre(), Process::Journal(), lissage_courbure_coeff_, lissage_courbure_iterations_systematique_, nb_iter_bary_volume_seul_, nb_iter_barycentrage_, Maillage_FT_Disc::nb_sommets(), nettoyer_maillage(), Statistiques::new_counter(), regulariser_maillage(), relax_barycentrage_, seuil_dvolume_residuel_, supprimer_facettes_bord(), and temps_dernier_lissage_.
Referenced by Topologie_Maillage_FT::remailler_interface().
barycentrer_lisser_apres_remaillage()
void Remaillage_FT::barycentrer_lisser_apres_remaillage (Maillage_FT_Disc & maillage, ArrOfDouble & var_volume)
idem mais avec le nombre d'iterations de lissage si remaillage
Precondition: pas d'elements virtuels (on doit avoir appele nettoyer_elements_virtuels())
References Statistiques::begin_count(), Statistiques::end_count(), Process::je_suis_maitre(), Process::Journal(), lissage_courbure_coeff_, lissage_courbure_iterations_si_remaillage_, nb_iter_bary_volume_seul_, nb_iter_barycentrage_, nettoyer_maillage(), Statistiques::new_counter(), regulariser_maillage(), relax_barycentrage_, seuil_dvolume_residuel_, and supprimer_facettes_bord().
Referenced by remaillage_local_interface().
sauvegarder()
int Remaillage_FT::sauvegarder (Sortie &) const override virtual
Sauvegarde d'un Objet_U sur un flot de sortie Methode a surcharger.
Parameters
(Sortie&) flot de sortie a utiliser pour la sauvegarde
Returns
(int) code de retour
Reimplemented from Objet_U.
References Process::exit(), EcritureLectureSpecial::is_ecriture_special(), TRUST_2_PDI::is_PDI_checkpoint(), Process::je_suis_maitre(), Objet_U::que_suis_je(), temps_dernier_lissage_, and temps_dernier_remaillage_.
Referenced by Transport_Interfaces_FT_Disc_interne::sauvegarder().
reprendre()
int Remaillage_FT::reprendre (Entree &) override virtual
Reprise d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree&) flot d'entree a utiliser pour la reprise
Returns
(int) code de retour
Reimplemented from Objet_U.
References Process::exit(), TRUST_2_PDI::is_PDI_restart(), Objet_U::que_suis_je(), temps_dernier_lissage_, and temps_dernier_remaillage_.
Referenced by Transport_Interfaces_FT_Disc_interne::reprendre().
calculer_variation_volume()
double Remaillage_FT::calculer_variation_volume (const Maillage_FT_Disc & maillage, const DoubleTab & position_initiale, ArrOfDouble & varVolume) const
Cette fonction calcule le volume de phase 0 engendre par chaque sommet lors du deplacement de l'interface entre la position initiale et la position actuelle.
du maillage (le volume engendre est positif si l'interface se deplace dans la direction de la normale aux facettes). On definit d'abord le volume engendre par le deplacement de chaque facette : C'est le volume d'un polyedre construit comme reunion de trois tetraedres, engendres par deplacement successifs des trois sommets dans un ordre conventionnel (deux sommets d'une arete sont toujours deplaces dans le meme ordre pour que les deux triangles voisins engendrent des tetraedres conformes, sans laisser de trous et sans se chevaucher) Ensuite, le volume engendre par chaque facette est divise en trois parts egales et reparti sur les trois sommets de la facette.
Parameters
(maillage) maillage
(position_initiale) position initiale des sommets (doit avoir la meme taille que maillage.sommets(), et l'espace virtuel doit etre a jour)
(varVolume) la variation de volume pour chaque sommet (on lui donne la bonne taille et on met a jour l'espace virtuel)
Returns
(double) Variation de volume totale sur l'ensemble du domaine.
References calculer_variation_volume_facette_2D(), calculer_variation_volume_facette_3D(), Desc_Structure_FT::collecter_espace_virtuel(), Maillage_FT_Disc::desc_sommets(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Desc_Structure_FT::echange_espace_virtuel(), MD_Vector_tools::EV_SOMME, Maillage_FT_Disc::facette_virtuelle(), Maillage_FT_Disc::facettes(), Process::mp_sum(), Maillage_FT_Disc::nb_facettes(), Maillage_FT_Disc::nb_sommets(), and TRUSTArray< _TYPE_, _SIZE_ >::resize_array().
Referenced by Transport_Interfaces_FT_Disc::deplacer_maillage_ft_v_fluide(), redistribuer_sommets(), supprimer_petites_aretes(), Remaillage_FT_IJK::supprimer_petites_aretes(), and IJK_Interfaces::transporter_maillage_deformation().
lisser_dvolume()
void Remaillage_FT::lisser_dvolume (const Maillage_FT_Disc & maillage, ArrOfDouble & var_volume, const int nb_iterations) const
Regularise le champ scalaire "var_volume" defini aux sommets du "maillage".
On regularise en faisant calculant une valeur moyenne par facette, puis en recalculant une moyenne aux sommets en fonction de la moyenne aux faces. Les moyennes sont ponderees par la surface des facettes... Le lissage est repete un nombre donne de fois. Cette methode est utilisee pour lisser les corrections de volume et eviter l'apparition de pointes sur les interfaces.
Parameters
(maillage) le support du champ a regulariser
(var_volume) le champ a regulariser (champ aux sommets du maillage)
(nb_iterations) nombre d'iterations de l'operation de regularisation.
References calculer_barycentre_facettes_voisines(), Desc_Structure_FT::collecter_espace_virtuel(), Maillage_FT_Disc::desc_sommets(), Objet_U::dimension, Desc_Structure_FT::echange_espace_virtuel(), MD_Vector_tools::EV_SOMME, Maillage_FT_Disc::facette_virtuelle(), Maillage_FT_Disc::facettes(), Maillage_FT_Disc::get_update_surface_facettes(), and Maillage_FT_Disc::nb_facettes().
Referenced by Transport_Interfaces_FT_Disc::deplacer_maillage_ft_v_fluide(), regulariser_maillage(), and Remailleur_Collision_FT_Thomas::traite_RuptureCoalescenceInterfaces_Conservatif().
regulariser_courbure()
void Remaillage_FT::regulariser_courbure (Maillage_FT_Disc & maillage, const double coeff, ArrOfDouble & dvolume) const virtual
Regularise le maillage en deplacant les sommets pour reduire les gradients de courbure.
L'equation d'evolution du maillage est une diffusion de masse le long de l'interface proportionnelle au gradient de courbure.
References Maillage_FT_Disc::angle_bidim_axi(), Objet_U::bidim_axi, Process::check_int_overflow(), Desc_Structure_FT::collecter_espace_virtuel(), Maillage_FT_Disc::desc_sommets(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Desc_Structure_FT::echange_espace_virtuel(), MD_Vector_tools::EV_SOMME, Maillage_FT_Disc::facette_virtuelle(), Maillage_FT_Disc::facettes(), Maillage_FT_Disc::get_update_courbure_sommets(), Maillage_FT_Disc::get_update_surface_facettes(), Process::je_suis_maitre(), Process::Journal(), lissage_critere_, Process::mp_min(), Process::mp_sum(), Maillage_FT_Disc::nb_sommets(), refdomaine_VF_, Maillage_FT_Disc::sommet_elem(), Maillage_FT_Disc::sommet_virtuel(), Maillage_FT_Disc::sommets(), and Maillage_FT_Disc::temps().
Referenced by regulariser_maillage().
get_nb_iter_bary_volume_seul()
int Remaillage_FT::get_nb_iter_bary_volume_seul () inline
References nb_iter_bary_volume_seul_.
Referenced by Transport_Interfaces_FT_Disc::lire_motcle_non_standard().
set_is_solid_particle()
void Remaillage_FT::set_is_solid_particle (const bool is_solid_particle) inline
References is_solid_particle_.
Referenced by Transport_Interfaces_FT_Disc::lire_motcle_non_standard().
get_is_solid_particle()
const bool & Remaillage_FT::get_is_solid_particle () const inline
References is_solid_particle_.
Referenced by supprimer_facettes_bord().
tester_a_remailler()
int Remaillage_FT::tester_a_remailler (const Maillage_FT_Disc & maillage) const protected
regulariser_maillage()
double Remaillage_FT::regulariser_maillage (Maillage_FT_Disc & maillage, ArrOfDouble & var_volume, const double facteur_barycentrage_tangent, const double coeff_lissage, const int nb_iter_barycentrage, const int nb_iter_lissage, const int max_nb_iter_correction_volume, const double seuil_dvolume) const protected
Algorithme general de lissage du maillage.
Permet de barycentrer, regulariser la courbure, et d'appliquer une correction de volume en deplacant les noeuds dans la direction normale.
Parameters
(maillage) maillage a barycentrer
(var_volume) pour chaque sommet du maillage initial, variation de volume a obtenir lors du deplacement. En retour, on y met le residu (difference entre var_volume initial et var_volume obtenu lors du deplacement).
Returns
(double) erreur sur la variation totale de volume obtenue (en m3)
References lissage_courbure_coeff_, lisser_dvolume(), Maillage_FT_Disc::nb_sommets(), redistribuer_sommets(), regulariser_courbure(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and DebogFT::verifier_tableau_sommets().
Referenced by barycentrer_lisser_apres_remaillage(), Remaillage_FT_IJK::barycentrer_lisser_apres_remaillage(), barycentrer_lisser_systematique(), Remaillage_FT_IJK::barycentrer_lisser_systematique_ijk(), and corriger_volume_().
redistribuer_sommets()
double Remaillage_FT::redistribuer_sommets (Maillage_FT_Disc & maillage, const double relaxation_direction_tangente, const double relaxation_direction_normale, ArrOfDouble & var_volume_impose, ArrOfDouble & var_volume_obtenu) const protected
Deplace les sommets du maillage pour les redistribuer de facon homogene.
Le deplacement est la somme d'une composante tangentielle et d'une composante normale a l'interface. La composante tangentielle ramene le sommet vers le barycentre des facettes voisines du sommet. La composante normale est calculee de sorte a produire la variation de volume imposee. Traitement des lignes de contact: le deplacement est decompose en une composante normale a la ligne de contact et une composante tangente.
Parameters
(maillage) le maillage a redistribuer (il retourne dans l'etat minimal)
(relaxation_direction_tangente) si ce parametre vaut 1, le sommet est deplace sur le barycentre. le parametre fixe la fraction du deplacement a realiser.
(relaxation_direction_normale)
References calculer_barycentre_facettes_voisines(), calculer_differentielle_volume(), calculer_variation_volume(), Maillage_FT_Disc::desc_sommets(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Desc_Structure_FT::echange_espace_virtuel(), Process::Journal(), Maillage_FT_Disc::nb_sommets(), Maillage_FT_Disc::preparer_tableau_avant_transport(), Parcours_interface::projeter_vecteur_sur_face(), Maillage_FT_Disc::refparcours_interface_, TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), Maillage_FT_Disc::sommet_face_bord_, Maillage_FT_Disc::sommet_virtuel(), Maillage_FT_Disc::sommets(), Maillage_FT_Disc::transporter(), Maillage_FT_Disc::update_tableau_apres_transport(), TRUST_Ref< _CLASSE_ >::valeur(), DebogFT::verifier_maillage_ft(), and DebogFT::verifier_tableau_sommets().
Referenced by regulariser_maillage().
calculer_barycentre_facettes_voisines()
int Remaillage_FT::calculer_barycentre_facettes_voisines (const Maillage_FT_Disc & maillage, DoubleTab & barycentres) const protected
Cette fonction calcule pour chaque sommet le barycentre de l'ensemble des facettes voisines du sommet.
Les "dimension" premieres colonnes contiennent les coordonnees du barycentre, la colonne "dimension" contient la somme des surfaces des facettes voisines du sommet.
Parameters
(maillage) maillage a barycentrer
(barycentres) par sommet, barycentres de ses facettes voisines
Returns
(int) toujours 1...
References Desc_Structure_FT::collecter_espace_virtuel(), Maillage_FT_Disc::desc_sommets(), Objet_U::dimension, Desc_Structure_FT::echange_espace_virtuel(), MD_Vector_tools::EV_SOMME, Maillage_FT_Disc::facette_virtuelle(), Maillage_FT_Disc::facettes(), Maillage_FT_Disc::get_update_surface_facettes(), Maillage_FT_Disc::nb_facettes(), Maillage_FT_Disc::nb_sommets(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Maillage_FT_Disc::sommet_virtuel(), and Maillage_FT_Disc::sommets().
Referenced by lisser_dvolume(), and redistribuer_sommets().
calculer_connectivites_sommetFacettes()
int Remaillage_FT::calculer_connectivites_sommetFacettes (const Maillage_FT_Disc & maillage, ArrOfInt & fa7VoisinesSom_index, IntTab & fa7VoisinesSom_data) const protected
Cette fonction calcule les connectivites sommet ->facettes voisines Les facettes voisines des sommets sont stockees dans le tableau fa7VoisinesSom_data.
sous forme de liste chainee. Pour le sommet som, le premier index de la liste est index = fa7VoisinesSom_index[som] la premiere facette est alors fa7VoisinesSom_data(index,1) et l'indice suivant index = fa7VoisinesSom_data(index,0) La chaine est terminee lorsque index==-1.
Parameters
(maillage) maillage a barycentrer
(fa7VoisinesSom_index) premier index pour le sommet som
(fa7VoisinesSom_data) premier liste des index et facettes voisines pour le sommet som
Returns
(int) le nombre de connectivites trouvees
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Maillage_FT_Disc::facettes(), Maillage_FT_Disc::nb_facettes(), and Maillage_FT_Disc::nb_sommets().
Referenced by supprimer_doublons_facettes().
calculer_correction_deplacement()
int Remaillage_FT::calculer_correction_deplacement (DoubleTab & deplacement, const ArrOfDouble & varVolume, const DoubleTab & deplacement_varVolume, const ArrOfDouble & norme2_deplacement_varVolume) const protected
Cette fonction calcule une correction sur un deplacement liee a une variation de volume imposee Utile pour IJK.
Parameters
(deplacement) delacement a corriger
(varVolume) la variation de volume
(deplacement_varVolume) la normale au plan de conservation de volume
(norme2_deplacement_varVolume) carre de la normale au plan
Returns
(int) 1 si le barycentrage s'est deroule correctement, 0 sinon
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, impr_, Process::Journal(), relax_barycentrage_, surface_interface_, and variation_volume_.
calculer_differentielle_volume()
int Remaillage_FT::calculer_differentielle_volume (const Maillage_FT_Disc & maillage, DoubleTab & differentielle_volume) const protected
Calcul de la differentielle du volume de phase 0 par rapport au deplacement de chaque sommet de l'interface.
C'est une forme lineaire qu'on exprime sous la forme d'un vecteur v tel que differentielle(deplacement) = deplacement scalaire v. En un certain sens, v est la normale a l'interface evaluee aux sommets. Si on deplace le sommet dans un plan orthogonal au vecteur, le volume des phases est conserve a l'ordre 1 par rapport a l'amplitude du deplacement.
Parameters
(maillage)
(differentielle_volume)
Returns
(int (1))
References Maillage_FT_Disc::angle_bidim_axi(), Objet_U::bidim_axi, Desc_Structure_FT::collecter_espace_virtuel(), Maillage_FT_Disc::desc_sommets(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Desc_Structure_FT::echange_espace_virtuel(), MD_Vector_tools::EV_SOMME, Maillage_FT_Disc::facette_virtuelle(), Maillage_FT_Disc::facettes(), Maillage_FT_Disc::get_update_normale_facettes(), Maillage_FT_Disc::get_update_surface_facettes(), Maillage_FT_Disc::nb_facettes(), Maillage_FT_Disc::nb_sommets(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), and Maillage_FT_Disc::sommets().
Referenced by redistribuer_sommets().
calculer_variation_volume_facette_2D()
double Remaillage_FT::calculer_variation_volume_facette_2D (int fa7, const Maillage_FT_Disc & maillage, const DoubleTab & position_initiale) const protected
Cette fonction calcule la difference de volume au niveau d'une facette par rapport a une position initiale des sommets.
version 2D
Parameters
(fa7) indice de la facette de calcul
(maillage) maillage a barycentrer
(position_initiale) position initiale des sommets
Returns
(double) la variation de volume
References Maillage_FT_Disc::angle_bidim_axi(), Objet_U::bidim_axi, Maillage_FT_Disc::facettes(), Maillage_FT_Disc::get_update_normale_facettes(), Maillage_FT_Disc::get_update_surface_facettes(), Maillage_FT_Disc::sommet_PE_owner(), and Maillage_FT_Disc::sommets().
Referenced by calculer_variation_volume().
calculer_variation_volume_facette_3D()
double Remaillage_FT::calculer_variation_volume_facette_3D (int fa7, const Maillage_FT_Disc & maillage, const DoubleTab & position_initiale) const protected
References Maillage_FT_Disc::facettes(), Maillage_FT_Disc::sommet_num_owner_, Maillage_FT_Disc::sommet_PE_owner_, and Maillage_FT_Disc::sommets().
Referenced by calculer_variation_volume().
calculer_longueurIdeale2_arete()
double Remaillage_FT::calculer_longueurIdeale2_arete (const Maillage_FT_Disc & maillage, int som0, double x, double y, double z) const protected virtual
Cette fonction calcule le carre de la longueur ideale d'une arete Dans un premier, cette longueur ideale est la racine cubique (en 3D) de la moyenne.
des volumes des elements euleriens contenant les sommets
Parameters
(som0) indice du 1er sommet de l'arete
(som1) indice du 2e sommet de l'arete
Returns
(double) carre de la longueur idealede l'arete
Reimplemented in Remaillage_FT_IJK.
References Objet_U::dimension, equilateral_, Process::exit(), facteur_longueur_ideale_, Objet_U::que_suis_je(), refdomaine_VF_, Maillage_FT_Disc::sommet_elem_, Maillage_FT_Disc::sommets(), TRUST_Ref< _CLASSE_ >::valeur(), and valeur_longueur_fixe_.
Referenced by marquer_aretes().
supprimer_petites_aretes()
int Remaillage_FT::supprimer_petites_aretes (Maillage_FT_Disc & maillage, ArrOfDouble & varVolume) const protected
A l'aide de "marquer_aretes", on determine les aretes trop petites du maillage.
On les supprime en remplacant un sommet d'une extremite de l'arete par le sommet de l'autre extremite. Pour cela, on cree des sommets virtuels, des facettes nulles (deux ou trois sommets confondus) et on change le volume des phases. La variation de volume engendree est ajoutee a varVolume.
Parameters
(maillage) Le maillage a optimiser. Le maillage retourne a l'etat minimal, Le volume change, Certaines facettes sont "nulles" (plusieurs sommets confondus), On cree des sommets virtuels.
(varVolume) Un tableau de taille nb_sommets() contenant une valeur initiale de variation de volume. On augmente la taille du tableau (creation de sommets virtuels) et on ajoute la variation de volume du maillage due a la suppression des aretes. L'espace virtuel est a jour. Valeur de retour: nombre total (sur tous les procs) de sommets du maillage supprimes
References TRUSTArray< _TYPE_, _SIZE_ >::append_array(), TRUSTTab< _TYPE_, _SIZE_ >::append_line(), Statistiques::begin_count(), calculer_variation_volume(), Process::check_int_overflow(), Desc_Structure_FT::collecter_espace_virtuel(), Maillage_FT_Disc::convertir_numero_distant_local(), Maillage_FT_Disc::corriger_proprietaires_facettes(), Maillage_FT_Disc::creer_sommets_virtuels_numowner(), Maillage_FT_Disc::desc_sommets(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Desc_Structure_FT::echange_espace_virtuel(), Statistiques::end_count(), MD_Vector_tools::EV_SOMME, Maillage_FT_Disc::facettes_, Maillage_FT_Disc::maillage_modifie(), marquer_aretes(), Process::me(), Maillage_FT_Disc::MINIMAL, Process::mp_sum(), Maillage_FT_Disc::nb_sommets(), Statistiques::new_counter(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), Maillage_FT_Disc::sommet_num_owner(), Maillage_FT_Disc::sommet_virtuel(), and Maillage_FT_Disc::sommets().
Referenced by remaillage_local_interface(), and Remaillage_FT_IJK::supprimer_petites_aretes().
diviser_grandes_aretes()
int Remaillage_FT::diviser_grandes_aretes (Maillage_FT_Disc & maillage) const protected
Cette fonction divise les grandes aretes en 2.
Parameters
(maillage) maillage a remailler
Returns
(int) 1 si le remaillage s'est deroule correctement, 0 sinon
References Statistiques::begin_count(), Desc_Structure_FT::calcul_schema_comm(), Process::check_int_overflow(), Maillage_FT_Disc::convertir_numero_distant_local(), Maillage_FT_Disc::corriger_proprietaires_facettes(), Maillage_FT_Disc::deplacer_sommets(), Maillage_FT_Disc::desc_facettes_, Maillage_FT_Disc::desc_sommets(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Statistiques::end_count(), Maillage_FT_Disc::facettes_, Process::Journal(), Maillage_FT_Disc::maillage_modifie(), marquer_aretes(), Process::me(), Maillage_FT_Disc::MINIMAL, Process::mp_sum(), Maillage_FT_Disc::nb_facettes(), Maillage_FT_Disc::nb_sommets(), Maillage_FT_Disc::nettoyer_elements_virtuels(), Statistiques::new_counter(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Maillage_FT_Disc::sommet_num_owner_, and temps_.
Referenced by remaillage_local_interface().
marquer_aretes()
int Remaillage_FT::marquer_aretes (Maillage_FT_Disc & maillage, IntTab & tab_aretesMarquees, ArrOfInt & tab_somD, DoubleTab & tab_deplacement_somD, int drap) const protected
References TRUSTArray< _TYPE_, _SIZE_ >::append_array(), TRUSTArray< _TYPE_, _SIZE_ >::begin(), Schema_Comm::begin_comm(), Desc_Structure_FT::calcul_schema_comm(), calculer_longueurIdeale2_arete(), chercher_arete_tab(), Maillage_FT_Disc::convertir_numero_distant_local(), Maillage_FT_Disc::creer_sommets_virtuels(), critere_arete_, Maillage_FT_Disc::desc_sommets(), Maillage_FT_Disc::desc_sommets_, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Maillage_FT_Disc::drapeaux_sommets_, Schema_Comm::echange_taille_et_messages(), TRUSTArray< _TYPE_, _SIZE_ >::end(), Schema_Comm::end_comm(), Entree::eof(), Maillage_FT_Disc::facette_virtuelle(), Maillage_FT_Disc::facettes(), Schema_Comm::get_recv_pe_list(), inserer_tab_aretes(), Process::Journal(), Maillage_FT_Disc::maillage_modifie(), Process::me(), Maillage_FT_Disc::MINIMAL, Process::mp_sum(), Maillage_FT_Disc::nb_facettes(), Maillage_FT_Disc::nb_sommets(), Process::nproc(), Schema_Comm::recv_buffer(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), Desc_Structure_FT::schema_comm(), Desc_Structure_FT::schema_comm_inverse(), Schema_Comm::send_buffer(), Schema_Comm::set_send_recv_pe_list(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), Maillage_FT_Disc::sommet_elem_, Maillage_FT_Disc::sommet_face_bord_, Maillage_FT_Disc::sommet_num_owner_, Maillage_FT_Disc::sommet_PE_owner_, and Maillage_FT_Disc::sommets_.
Referenced by diviser_grandes_aretes(), Remaillage_FT_IJK::diviser_grandes_aretes(), supprimer_petites_aretes(), and Remaillage_FT_IJK::supprimer_petites_aretes().
inserer_tab_aretes()
int Remaillage_FT::inserer_tab_aretes (int & nb_tab_aretes, IntTab & tab_aretes, DoubleTab & tab_criteres, int pe0, int numOwner0, int pe1, int numOwner1, int face_bord1, int peRequete, int fa7_peR, int iarete_fa7_peR) const protected
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), and TRUSTTab< _TYPE_, _SIZE_ >::resize().
Referenced by marquer_aretes().
chercher_arete_tab()
int Remaillage_FT::chercher_arete_tab (int tmp, const ArrOfInt & tab_index, const IntTab & tab_aretes, int pe0, int numOwner0, int pe1, int numOwner1) const protected
References TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by marquer_aretes().
calculer_volume_sommets_supprimes()
double Remaillage_FT::calculer_volume_sommets_supprimes (const Maillage_FT_Disc & maillage, const ArrOfInt & tab_somSupp, ArrOfDouble & varVolume) const protected
Cette fonction calcule la variation de volume liee a la suppression de sommets.
Parameters
(maillage) maillage a barycentrer
(tab_somSupp) tableau des sommets a supprimer tab[som] < 0 : sommet a conserver tab[som] >=0 : sommet a remplacer par tab[som]
(varVolume) la variation de volume
Returns
(double) volume total supprime
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Maillage_FT_Disc::facettes(), impr_, Process::Journal(), Maillage_FT_Disc::nb_facettes(), Maillage_FT_Disc::nb_sommets(), and Maillage_FT_Disc::sommets().
supprimer_facettes_bord()
int Remaillage_FT::supprimer_facettes_bord (Maillage_FT_Disc & maillage) const protected
Cette fonction marque a supprimer les facettes ayant leurs 3 sommets de bord Marquer a supprimer = condenser les 3 sommets en un seul (le sommet 0)
MODIF GB 21/07/2015 : Pour le cas sloshing par exemple, si le domaine a des coins, l'interface peut contenir un element dont les 3 sommets sont sur le bord sans pour autant que la facette soit integralement sur le bord. Elle peut avoir son 3eme cote dans le domaine. Dans ce cas, on la conserve.
Parameters
(maillage) maillage a remailler
Returns
(int) 1 si le remaillage s'est deroule correctement, 0 sinon
References Parcours_interface::calculer_normale_face_bord(), Maillage_FT_Disc::check_mesh(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Maillage_FT_Disc::facettes_, get_is_solid_particle(), Maillage_FT_Disc::get_update_normale_facettes(), impr_, Process::Journal(), Process::mp_sum(), Maillage_FT_Disc::nb_facettes(), Maillage_FT_Disc::printFa7(), Maillage_FT_Disc::refparcours_interface_, Maillage_FT_Disc::sommet_face_bord_, Maillage_FT_Disc::sommet_ligne_contact(), Maillage_FT_Disc::sommets(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by barycentrer_lisser_apres_remaillage(), Remaillage_FT_IJK::barycentrer_lisser_apres_remaillage(), barycentrer_lisser_systematique(), Remaillage_FT_IJK::barycentrer_lisser_systematique_ijk(), corriger_volume_(), and traite_adherence().
supprimer_doublons_facettes()
int Remaillage_FT::supprimer_doublons_facettes (Maillage_FT_Disc & maillage) const protected
Cette fonction marque a supprimer les facettes en double.
Lorsque 2 facettes se trouvent avoir 3 de leur sommets en commun, il faut supprimer les 2 facettes? Marquer a supprimer = condenser les 3 sommets en un seul (le sommet 0)
Precondition: Le maillage doit verifier la propriete "proprietaire facette = premier sommet"
Parameters
(maillage) maillage a remailler
Returns
(int) Le nombre de facettes supprimees
References calculer_connectivites_sommetFacettes(), Comm_Group::check_enabled(), Maillage_FT_Disc::check_mesh(), Maillage_FT_Disc::desc_facettes(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Desc_Structure_FT::echange_espace_virtuel(), Maillage_FT_Disc::facettes_, impr_, Process::Journal(), Maillage_FT_Disc::maillage_modifie(), Maillage_FT_Disc::MINIMAL, Maillage_FT_Disc::nb_facettes(), Maillage_FT_Disc::nb_sommets(), Maillage_FT_Disc::printFa7(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), and TRUSTArray< _TYPE_, _SIZE_ >::resize_array().
Referenced by remaillage_local_interface(), and Remaillage_FT_IJK::remaillage_local_interface().
permuter_aretes()
int Remaillage_FT::permuter_aretes (Maillage_FT_Disc & maillage) const protected
Cette fonction effectue des permutations d'aretes afin d'ameliorer la qualite du maillage.
Parameters
(maillage) maillage a remailler
Returns
(int) 1 si le remaillage s'est deroule correctement, 0 sinon
References Objet_U::dimension, Maillage_FT_Disc::maillage_modifie(), and Maillage_FT_Disc::MINIMAL.
qualiteTriangle()
double Remaillage_FT::qualiteTriangle (const FTd_vecteur3 & som0, const FTd_vecteur3 & som1, const FTd_vecteur3 & som2, double & aire) const protected
Cette methode calcule, pour un triangle donne, sa qualite : celle-ci est comprise dans ]0,1], et vaut 1 pour un triangle equilateral.
Parameters
(som0) id du premier sommet
(som1) id du second sommet
(som2) id du troisieme sommet
(CoordSom) coordonnees des sommets
Returns
(double) le coefficient de qualite du triangle.
References Objet_U::dimension, and impr_.
nettoyer_maillage()
int Remaillage_FT::nettoyer_maillage (Maillage_FT_Disc & maillage) const protected
Cette fonction nettoie le maillage : Elle supprime les facettes reduites a 1 sommet.
Elle supprime les sommets non utilises
Parameters
(maillage) maillage a remailler
Returns
(int) 1 si le remaillage s'est deroule correctement, 0 sinon
References Process::Journal(), Maillage_FT_Disc::nb_facettes(), and Maillage_FT_Disc::nettoyer_maillage().
Referenced by barycentrer_lisser_apres_remaillage(), Remaillage_FT_IJK::barycentrer_lisser_apres_remaillage(), barycentrer_lisser_systematique(), corriger_volume_(), remaillage_local_interface(), Remaillage_FT_IJK::remaillage_local_interface(), supprimer_facettes_nulles(), and traite_adherence().
Member Data Documentation
info_obj
const Type_info Remaillage_FT::info_obj static
refdomaine_VF_
TRUST_Ref< Domaine_VF *> Remaillage_FT::refdomaine_VF_ protected
Referenced by associer_domaine(), calculer_longueurIdeale2_arete(), regulariser_courbure(), and traite_decollement().
temps_
double Remaillage_FT::temps_ = 0 protected
Referenced by diviser_grandes_aretes(), Remaillage_FT_IJK::diviser_grandes_aretes(), remaillage_local_interface(), and Remaillage_FT_IJK::remaillage_local_interface().
temps_dernier_remaillage_
double Remaillage_FT::temps_dernier_remaillage_ = -1.e40 protected
Referenced by a_remailler(), remaillage_local_interface(), Remaillage_FT_IJK::remaillage_local_interface(), reprendre(), and sauvegarder().
temps_dernier_lissage_
double Remaillage_FT::temps_dernier_lissage_ = -1.e40 protected
Referenced by a_lisser(), barycentrer_lisser_systematique(), remaillage_local_interface(), Remaillage_FT_IJK::remaillage_local_interface(), reprendre(), and sauvegarder().
dt_remaillage_
double Remaillage_FT::dt_remaillage_ = -1. protected
Referenced by a_remailler(), Remaillage_FT_IJK::printOn(), Remaillage_FT_IJK::readOn(), and set_param().
dt_lissage_
double Remaillage_FT::dt_lissage_ = -1. protected
Referenced by a_lisser(), and set_param().
nb_iter_remaillage_
int Remaillage_FT::nb_iter_remaillage_ = 1 protected
Referenced by Remaillage_FT_IJK::printOn(), Remaillage_FT_IJK::readOn(), Remaillage_FT_IJK::Remaillage_FT_IJK(), remaillage_local_interface(), Remaillage_FT_IJK::remaillage_local_interface(), and set_param().
nb_iter_barycentrage_
int Remaillage_FT::nb_iter_barycentrage_ = 1 protected
Referenced by barycentrer_lisser_apres_remaillage(), Remaillage_FT_IJK::barycentrer_lisser_apres_remaillage(), barycentrer_lisser_systematique(), Remaillage_FT_IJK::barycentrer_lisser_systematique_ijk(), Remaillage_FT_IJK::printOn(), Remaillage_FT_IJK::readOn(), Remaillage_FT_IJK::Remaillage_FT_IJK(), and set_param().
nb_iter_bary_volume_seul_
int Remaillage_FT::nb_iter_bary_volume_seul_ = 3 protected
Referenced by barycentrer_lisser_apres_remaillage(), Remaillage_FT_IJK::barycentrer_lisser_apres_remaillage(), barycentrer_lisser_systematique(), Remaillage_FT_IJK::barycentrer_lisser_systematique_ijk(), corriger_volume(), get_nb_iter_bary_volume_seul(), Remaillage_FT_IJK::printOn(), Remaillage_FT_IJK::readOn(), Remaillage_FT_IJK::Remaillage_FT_IJK(), and set_param().
seuil_dvolume_residuel_
double Remaillage_FT::seuil_dvolume_residuel_ = 0. protected
Referenced by barycentrer_lisser_apres_remaillage(), Remaillage_FT_IJK::barycentrer_lisser_apres_remaillage(), barycentrer_lisser_systematique(), Remaillage_FT_IJK::barycentrer_lisser_systematique_ijk(), corriger_volume_(), Remaillage_FT_IJK::printOn(), Remaillage_FT_IJK::readOn(), and set_param().
relax_barycentrage_
double Remaillage_FT::relax_barycentrage_ = 1. protected
Referenced by barycentrer_lisser_apres_remaillage(), Remaillage_FT_IJK::barycentrer_lisser_apres_remaillage(), barycentrer_lisser_systematique(), Remaillage_FT_IJK::barycentrer_lisser_systematique_ijk(), calculer_correction_deplacement(), Remaillage_FT_IJK::printOn(), Remaillage_FT_IJK::readOn(), and set_param().
critere_arete_
double Remaillage_FT::critere_arete_ = 0.35 protected
Referenced by marquer_aretes(), Remaillage_FT_IJK::printOn(), Remaillage_FT_IJK::readOn(), Remaillage_FT_IJK::Remaillage_FT_IJK(), and set_param().
impr_
int Remaillage_FT::impr_ = -1 protected
Referenced by calculer_correction_deplacement(), calculer_volume_sommets_supprimes(), qualiteTriangle(), set_param(), supprimer_doublons_facettes(), supprimer_facettes_bord(), and traite_decollement().
valeur_longueur_fixe_
double Remaillage_FT::valeur_longueur_fixe_ = -1. protected
Referenced by calculer_longueurIdeale2_arete(), readOn(), and set_param().
facteur_longueur_ideale_
double Remaillage_FT::facteur_longueur_ideale_ = -1. protected
Referenced by calculer_longueurIdeale2_arete(), Remaillage_FT_IJK::calculer_longueurIdeale2_arete(), Remaillage_FT_IJK::get_facteur_longueur_ideale(), Remaillage_FT_IJK::printOn(), readOn(), Remaillage_FT_IJK::readOn(), Remaillage_FT_IJK::Remaillage_FT_IJK(), and set_param().
equilateral_
int Remaillage_FT::equilateral_ = 0 protected
Referenced by calculer_longueurIdeale2_arete(), Remaillage_FT_IJK::calculer_longueurIdeale2_arete(), Remaillage_FT_IJK::printOn(), readOn(), Remaillage_FT_IJK::readOn(), and Remaillage_FT_IJK::Remaillage_FT_IJK().
variation_volume_
double Remaillage_FT::variation_volume_ = 0. protected
Referenced by calculer_correction_deplacement(), remaillage_local_interface(), and Remaillage_FT_IJK::remaillage_local_interface().
surface_interface_
double Remaillage_FT::surface_interface_ = 0. protected
Referenced by calculer_correction_deplacement().
lissage_courbure_coeff_
double Remaillage_FT::lissage_courbure_coeff_ = -0.05 protected
Referenced by barycentrer_lisser_apres_remaillage(), Remaillage_FT_IJK::barycentrer_lisser_apres_remaillage(), barycentrer_lisser_systematique(), Remaillage_FT_IJK::barycentrer_lisser_systematique_ijk(), Remaillage_FT_IJK::printOn(), Remaillage_FT_IJK::readOn(), regulariser_maillage(), and set_param().
lissage_courbure_iterations_systematique_
int Remaillage_FT::lissage_courbure_iterations_systematique_ = 0 protected
Referenced by barycentrer_lisser_systematique(), Remaillage_FT_IJK::barycentrer_lisser_systematique_ijk(), Remaillage_FT_IJK::printOn(), Remaillage_FT_IJK::readOn(), and set_param().
lissage_courbure_iterations_si_remaillage_
int Remaillage_FT::lissage_courbure_iterations_si_remaillage_ = 0 protected
Referenced by barycentrer_lisser_apres_remaillage(), Remaillage_FT_IJK::barycentrer_lisser_apres_remaillage(), Remaillage_FT_IJK::printOn(), Remaillage_FT_IJK::readOn(), and set_param().
lissage_courbure_iterations_old_
int Remaillage_FT::lissage_courbure_iterations_old_ = -1 protected
Referenced by readOn(), and set_param().
lissage_critere_
double Remaillage_FT::lissage_critere_ = 0. protected
Referenced by regulariser_courbure(), and set_param().
is_solid_particle_
bool Remaillage_FT::is_solid_particle_ =false protected
Referenced by get_is_solid_particle(), and set_is_solid_particle().