TrioCFD: Flux_radiatif_base Class Reference
Flux_radiatif_base Class Reference abstract
#include <Flux_radiatif_base.h>
Public Member Functions
void completer () override
const Type_info * get_info () const override
Public Member Functions inherited from Neumann_paroi
const Type_info * get_info () const override
void verifie_ch_init_nb_comp () const override
Public Member Functions inherited from Neumann
const DoubleTab & flux_impose (bool nb_faces_tot=false) const
virtual double flux_impose (int i) const
virtual double flux_impose (int i, int j) const
const Type_info * get_info () const override
Public Member Functions inherited from Cond_lim_base
virtual int a_mettre_a_jour_ss_pas_dt ()
virtual void associer_domaine_cl_dis_base (const Domaine_Cl_dis_base &)
virtual void associer_fr_dis_base (const Frontiere_dis_base &)
virtual void calculer_coeffs_echange (double temps)
virtual int compatible_avec_discr (const Discretisation_base &) const
Domaine_Cl_dis_base & domaine_Cl_dis ()
const Domaine_Cl_dis_base & domaine_Cl_dis () const
virtual Frontiere_dis_base & frontiere_dis ()
virtual const Frontiere_dis_base & frontiere_dis () const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
void set_modifier_val_imp (int)
virtual void verifie_ch_init_nb_comp () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Cond_lim_base
void err_pas_compatible (const Discretisation_base &) const
void err_pas_compatible (const Equation_base &) const
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
.FINHTML .FINEPS
Constructor & Destructor Documentation
Flux_radiatif_base()
Flux_radiatif_base::Flux_radiatif_base ()
~Flux_radiatif_base()
Flux_radiatif_base::~Flux_radiatif_base () override
Member Function Documentation
info()
const Type_info * Flux_radiatif_base::info () static
get_info()
const Type_info * Flux_radiatif_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Neumann_paroi.
Reimplemented in Flux_radiatif_VDF, and Flux_radiatif_VEF.
self_cast() [1/2]
Flux_radiatif_base & Flux_radiatif_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Flux_radiatif_base & Flux_radiatif_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Flux_radiatif_base::printOn (Sortie & s) const override protected virtual
Imprime le type de l'equation sur un flot de sortie.
Parameters
(Sortie& s) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Neumann_paroi.
Reimplemented in Flux_radiatif_VDF, and Flux_radiatif_VEF.
References Objet_U::que_suis_je().
readOn()
Entree & Flux_radiatif_base::readOn (Entree & is) override protected virtual
Appel Neumann_paroi::readOn(Entree& is)
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Exceptions
solveur pression non defini dans jeu de donnees
Reimplemented from Neumann_paroi.
Reimplemented in Flux_radiatif_VDF, and Flux_radiatif_VEF.
References A_, Cond_lim_base::champ_front(), emissivite_, Process::exit(), Field_base::fixer_nb_comp(), flux_radiatif(), flux_radiatif_, Cond_lim_base::le_champ_front, Motcles::search(), and Objet_U_ptr::typer().
Referenced by Flux_radiatif_VDF::readOn(), and Flux_radiatif_VEF::readOn().
compatible_avec_eqn()
int Flux_radiatif_base::compatible_avec_eqn (const Equation_base &) const inline override virtual
Reimplemented from Cond_lim_base.
emissivite() [1/2]
Champ_front_base & Flux_radiatif_base::emissivite () inline
References emissivite_.
Referenced by Flux_radiatif_VDF::calculer_flux_radiatif(), Flux_radiatif_VEF::calculer_flux_radiatif(), Flux_radiatif_VDF::evaluer_cl_rayonnement(), Flux_radiatif_VEF::evaluer_cl_rayonnement(), Eq_rayo_semi_transp_VDF::modifier_matrice(), Eq_rayo_semi_transp_VEF::modifier_matrice(), and Cond_Lim_rayo_semi_transp::recherche_emissivite_et_A().
emissivite() [2/2]
const Champ_front_base & Flux_radiatif_base::emissivite () const inline
References emissivite_.
A() [1/2]
double & Flux_radiatif_base::A () inline
References A_.
Referenced by Flux_radiatif_VDF::calculer_flux_radiatif(), Flux_radiatif_VEF::calculer_flux_radiatif(), Eq_rayo_semi_transp_VDF::modifier_matrice(), Eq_rayo_semi_transp_VEF::modifier_matrice(), and Cond_Lim_rayo_semi_transp::recherche_emissivite_et_A().
A() [2/2]
const double & Flux_radiatif_base::A () const inline
References A_.
calculer_flux_radiatif()
virtual void Flux_radiatif_base::calculer_flux_radiatif (const Equation_base & eq_temp) pure virtual
Implemented in Flux_radiatif_VDF, and Flux_radiatif_VEF.
Referenced by Modele_rayo_semi_transp::calculer_flux_radiatif().
flux_radiatif() [1/2]
Champ_front_base & Flux_radiatif_base::flux_radiatif () inline
References flux_radiatif_.
Referenced by Flux_radiatif_VEF::calculer_flux_radiatif(), completer(), Modele_rayo_semi_transp::flux_radiatif(), and readOn().
flux_radiatif() [2/2]
const Champ_front_base & Flux_radiatif_base::flux_radiatif () const inline
References flux_radiatif_.
completer()
void Flux_radiatif_base::completer () override virtual
cette methode permet de typer les champs_front : - le_champ_front
   - flux_radiatif_
Reimplemented from Cond_lim_base.
References Champ_front_base::associer_fr_dis_base(), Cond_lim_base::champ_front(), Cond_lim_base::completer(), emissivite_, flux_radiatif(), Champ_front_base::frontiere_dis(), Cond_lim_base::le_champ_front, Frontiere_dis_base::le_nom(), Front_VF::nb_faces(), Field_base::nommer(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), and Champ_front_base::valeurs().
flux_impose() [1/2]
double Flux_radiatif_base::flux_impose (int i) const override virtual
Renvoie la valeur de flux imposes a la paroi radiative.
Reimplemented from Neumann.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Process::exit(), Cond_lim_base::le_champ_front, TRUSTVect< _TYPE_, _SIZE_ >::size(), and Champ_front_base::valeurs().
flux_impose() [2/2]
double Flux_radiatif_base::flux_impose (int i, int j) const override virtual
Renvoie la valeur de flux imposes a la paroi radiative.
Reimplemented from Neumann.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Cond_lim_base::le_champ_front, and Champ_front_base::valeurs().
Member Data Documentation
info_obj
const Type_info Flux_radiatif_base::info_obj static
A_
double Flux_radiatif_base::A_ protected
Referenced by A(), and readOn().
emissivite_
TRUST_Deriv< Champ_front_base > Flux_radiatif_base::emissivite_ protected
Referenced by completer(), emissivite(), and readOn().
flux_radiatif_
TRUST_Deriv< Champ_front_base > Flux_radiatif_base::flux_radiatif_ protected
Referenced by Flux_radiatif_VDF::calculer_flux_radiatif(), flux_radiatif(), and readOn().