TrioCFD: Modele_turbulence_hyd_LES_Smago_VDF Class Reference
Modele_turbulence_hyd_LES_Smago_VDF Class Reference
#include <Modele_turbulence_hyd_LES_Smago_VDF.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Modele_turbulence_hyd_LES_VDF_base
const Type_info * get_info () const override
Public Member Functions inherited from Modele_turbulence_hyd_LES_base
const Type_info * get_info () const override
void imprimer (Sortie &is) const override
int preparer_calcul () override
int reprendre (Entree &is) override
const Type_info * get_info () const override
void imprimer (Sortie &) const override
int reprendre (Entree &is) override
Public Member Functions inherited from Modele_turbulence_hyd_base
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Type_info * get_info () const override
virtual void imprimer (Sortie &) const
void lire_distance_paroi ()
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual int preparer_calcul ()
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Modele_turbulence_hyd_LES_VDF_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
maille Smagorinsky en VDF
Constructor & Destructor Documentation
Modele_turbulence_hyd_LES_Smago_VDF()
Modele_turbulence_hyd_LES_Smago_VDF::Modele_turbulence_hyd_LES_Smago_VDF ()
~Modele_turbulence_hyd_LES_Smago_VDF()
Modele_turbulence_hyd_LES_Smago_VDF::~Modele_turbulence_hyd_LES_Smago_VDF ()
Member Function Documentation
cree_instance()
Objet_U * Modele_turbulence_hyd_LES_Smago_VDF::cree_instance () static
taille_memoire()
unsigned Modele_turbulence_hyd_LES_Smago_VDF::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Modele_turbulence_hyd_LES_DSGS_VDF, and Modele_turbulence_hyd_LES_SMAGO_DYN_VDF.
duplique()
int Modele_turbulence_hyd_LES_Smago_VDF::duplique () const override virtual
Implements Objet_U.
Reimplemented in Modele_turbulence_hyd_LES_DSGS_VDF, and Modele_turbulence_hyd_LES_SMAGO_DYN_VDF.
info()
const Type_info * Modele_turbulence_hyd_LES_Smago_VDF::info () static
get_info()
const Type_info * Modele_turbulence_hyd_LES_Smago_VDF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Modele_turbulence_hyd_LES_base.
Reimplemented in Modele_turbulence_hyd_LES_DSGS_VDF, and Modele_turbulence_hyd_LES_SMAGO_DYN_VDF.
self_cast() [1/2]
Modele_turbulence_hyd_LES_Smago_VDF & Modele_turbulence_hyd_LES_Smago_VDF::self_cast (Objet_U & r) static
self_cast() [2/2]
const Modele_turbulence_hyd_LES_Smago_VDF & Modele_turbulence_hyd_LES_Smago_VDF::self_cast (const Objet_U & r) static
printOn()
Sortie & Modele_turbulence_hyd_LES_Smago_VDF::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Modele_turbulence_hyd_LES_base.
Reimplemented in Modele_turbulence_hyd_LES_DSGS_VDF, and Modele_turbulence_hyd_LES_SMAGO_DYN_VDF.
References Objet_U::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Modele_turbulence_hyd_LES_Smago_VDF::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Modele_turbulence_hyd_LES_base.
Reimplemented in Modele_turbulence_hyd_LES_DSGS_VDF, and Modele_turbulence_hyd_LES_SMAGO_DYN_VDF.
References Modele_turbulence_hyd_LES_VDF_base::readOn().
Referenced by Modele_turbulence_hyd_LES_DSGS_VDF::readOn(), and Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::readOn().
set_param()
void Modele_turbulence_hyd_LES_Smago_VDF::set_param (Param & param) override virtual
Reimplemented from Modele_turbulence_hyd_LES_base.
Reimplemented in Modele_turbulence_hyd_LES_SMAGO_DYN_VDF.
References Param::ajouter(), Param::ajouter_condition(), cs_, and Modele_turbulence_hyd_LES_base::set_param().
Referenced by Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::set_param().
calculer_viscosite_turbulente()
Champ_Fonc_base & Modele_turbulence_hyd_LES_Smago_VDF::calculer_viscosite_turbulente () override protected virtual
Implements Modele_turbulence_hyd_0_eq_base.
Reimplemented in Modele_turbulence_hyd_LES_DSGS_VDF, and Modele_turbulence_hyd_LES_SMAGO_DYN_VDF.
References calculer_S_barre(), Champ_base::changer_temps(), cs_, Domaine_dis_base::domaine(), Process::exit(), Modele_turbulence_hyd_LES_base::l_, Modele_turbulence_hyd_base::la_viscosite_turbulente_, Modele_turbulence_hyd_0_eq_base::le_dom_VF_, Modele_turbulence_hyd_base::mon_equation_, Domaine_32_64< _SIZE_ >::nb_elem(), Domaine_dis_base::nb_elem_tot(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), TRUSTVect< _TYPE_, _SIZE_ >::size(), SMA_barre_, TRUST_Ref< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), and Debog::verifier().
calculer_S_barre()
void Modele_turbulence_hyd_LES_Smago_VDF::calculer_S_barre () protected
References Champ_Face_VDF::calcul_duidxj(), Objet_U::dimension, Modele_turbulence_hyd_0_eq_base::le_dom_Cl_, Modele_turbulence_hyd_0_eq_base::le_dom_VF_, TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Modele_turbulence_hyd_base::mon_equation_, Domaine_dis_base::nb_elem_tot(), SMA_barre_, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Modele_turbulence_hyd_LES_DSGS_VDF::calculer_viscosite_turbulente(), and calculer_viscosite_turbulente().
Member Data Documentation
info_obj
const Type_info Modele_turbulence_hyd_LES_Smago_VDF::info_obj static
cs_
double Modele_turbulence_hyd_LES_Smago_VDF::cs_ = 0.18 protected
Referenced by calculer_viscosite_turbulente(), and set_param().
SMA_barre_
DoubleVect Modele_turbulence_hyd_LES_Smago_VDF::SMA_barre_ protected
Referenced by calculer_S_barre(), Modele_turbulence_hyd_LES_DSGS_VDF::calculer_viscosite_turbulente(), and calculer_viscosite_turbulente().