TrioCFD: Terme_Source_Coriolis_base Class Reference
Terme_Source_Coriolis_base Class Reference
#include <Terme_Source_Coriolis_base.h>
Public Member Functions
const Type_info * get_info () const override
void mettre_a_jour (double temps) override
Public Member Functions inherited from Source_base
virtual int a_pour_Champ_Fonc (const Motcle &mot, TRUST_Ref< Champ_base * > &ch_ref) const
virtual void associer_champ_rho (const Champ_base &champ_rho)
virtual void completer ()
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
virtual void resetTime (double t)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
int lire_motcle_non_standard (const Motcle &, Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Terme_Source_Coriolis_base()
Terme_Source_Coriolis_base::Terme_Source_Coriolis_base ()
~Terme_Source_Coriolis_base()
Terme_Source_Coriolis_base::~Terme_Source_Coriolis_base () override
Member Function Documentation
info()
const Type_info * Terme_Source_Coriolis_base::info () static
get_info()
const Type_info * Terme_Source_Coriolis_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Source_base.
Reimplemented in Terme_Source_Coriolis_VDF_Face, and Terme_Source_Coriolis_QC_VDF_Face.
self_cast() [1/2]
Terme_Source_Coriolis_base & Terme_Source_Coriolis_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Terme_Source_Coriolis_base & Terme_Source_Coriolis_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Terme_Source_Coriolis_base::printOn (Sortie & os) const override protected virtual
DOES NOTHING - to override in derived classes.
Imprime la source sur un flot de sortie.
Parameters
(Sortie& os) le flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Source_base.
Reimplemented in Terme_Source_Coriolis_VDF_Face, and Terme_Source_Coriolis_QC_VDF_Face.
References Objet_U::que_suis_je().
readOn()
Entree & Terme_Source_Coriolis_base::readOn (Entree & is) override protected virtual
DOES NOTHING - to override in derived classes.
Lecture d'un terme source sur un flot d'entree.
Parameters
(Entree& is) le flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Source_base.
Reimplemented in Terme_Source_Coriolis_VDF_Face, and Terme_Source_Coriolis_QC_VDF_Face.
References Param::lire_avec_accolades_depuis(), Objet_U::que_suis_je(), and set_param().
Referenced by Terme_Source_Coriolis_VDF_Face::readOn(), and Terme_Source_Coriolis_QC_VDF_Face::readOn().
associer_eqn()
void Terme_Source_Coriolis_base::associer_eqn (const Navier_Stokes_std & eq_hyd) inline
References eq_hydraulique_.
Referenced by Terme_Source_Coriolis_VDF_Face::associer_pb().
omega()
const DoubleVect & Terme_Source_Coriolis_base::omega () const inline
References omega_.
Referenced by Terme_Source_Coriolis_VDF_Face::omega().
eq_hydraulique()
const Navier_Stokes_std & Terme_Source_Coriolis_base::eq_hydraulique () const inline
References eq_hydraulique_, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Terme_Source_Coriolis_VDF_Face::calculer_force_de_Coriolis().
mettre_a_jour()
void Terme_Source_Coriolis_base::mettre_a_jour (double temps) inline override virtual
DOES NOTHING - to override in derived classes.
Mise a jour en temps du terme source.
Parameters
(double) le pas de temps de mise a jour
Reimplemented from Source_base.
Reimplemented in Terme_Source_Coriolis_VDF_Face.
Referenced by Terme_Source_Coriolis_VDF_Face::mettre_a_jour().
set_param()
void Terme_Source_Coriolis_base::set_param (Param & param) protected
References Param::ajouter_non_std(), and Param::REQUIRED.
Referenced by readOn().
lire_motcle_non_standard()
int Terme_Source_Coriolis_base::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override protected virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Objet_U.
References Objet_U::dimension, Process::exit(), omega_, and TRUSTVect< _TYPE_, _SIZE_ >::resize().
Member Data Documentation
info_obj
const Type_info Terme_Source_Coriolis_base::info_obj static
omega_
DoubleVect Terme_Source_Coriolis_base::omega_ protected
Referenced by lire_motcle_non_standard(), and omega().
eq_hydraulique_
TRUST_Ref< Navier_Stokes_std *> Terme_Source_Coriolis_base::eq_hydraulique_ protected
Referenced by associer_eqn(), and eq_hydraulique().