TrioCFD: Modele_turbulence_hyd_LES_DSGS_VDF Class Reference
Modele_turbulence_hyd_LES_DSGS_VDF Class Reference
#include <Modele_turbulence_hyd_LES_DSGS_VDF.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Modele_turbulence_hyd_LES_base
const Type_info * get_info () const override
void imprimer (Sortie &is) const override
int preparer_calcul () override
int reprendre (Entree &is) override
const Type_info * get_info () const override
void imprimer (Sortie &) const override
int reprendre (Entree &is) override
Public Member Functions inherited from Modele_turbulence_hyd_base
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Type_info * get_info () const override
virtual void imprimer (Sortie &) const
void lire_distance_paroi ()
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual int preparer_calcul ()
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
correspond a la mise en oeuvre du modele sous maille dynamique en VDF
.SECTION voir aussi Modele_turbulence_hyd_LES_Smago_VDF
Constructor & Destructor Documentation
Modele_turbulence_hyd_LES_DSGS_VDF()
Modele_turbulence_hyd_LES_DSGS_VDF::Modele_turbulence_hyd_LES_DSGS_VDF ()
~Modele_turbulence_hyd_LES_DSGS_VDF()
Modele_turbulence_hyd_LES_DSGS_VDF::~Modele_turbulence_hyd_LES_DSGS_VDF ()
Member Function Documentation
cree_instance()
Objet_U * Modele_turbulence_hyd_LES_DSGS_VDF::cree_instance () static
taille_memoire()
unsigned Modele_turbulence_hyd_LES_DSGS_VDF::taille_memoire () const override virtual
Reimplemented from Modele_turbulence_hyd_LES_Smago_VDF.
duplique()
int Modele_turbulence_hyd_LES_DSGS_VDF::duplique () const override virtual
Reimplemented from Modele_turbulence_hyd_LES_Smago_VDF.
info()
const Type_info * Modele_turbulence_hyd_LES_DSGS_VDF::info () static
get_info()
const Type_info * Modele_turbulence_hyd_LES_DSGS_VDF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Modele_turbulence_hyd_LES_Smago_VDF.
self_cast() [1/2]
Modele_turbulence_hyd_LES_DSGS_VDF & Modele_turbulence_hyd_LES_DSGS_VDF::self_cast (Objet_U & r) static
self_cast() [2/2]
const Modele_turbulence_hyd_LES_DSGS_VDF & Modele_turbulence_hyd_LES_DSGS_VDF::self_cast (const Objet_U & r) static
printOn()
Sortie & Modele_turbulence_hyd_LES_DSGS_VDF::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Modele_turbulence_hyd_LES_Smago_VDF.
References Objet_U::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Modele_turbulence_hyd_LES_DSGS_VDF::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Modele_turbulence_hyd_LES_Smago_VDF.
References Modele_turbulence_hyd_LES_Smago_VDF::readOn().
associer()
void Modele_turbulence_hyd_LES_DSGS_VDF::associer (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis) override virtual
Reimplemented from Modele_turbulence_hyd_0_eq_base.
References Champs_compris_T< FIELD_TYPE >::ajoute_champ(), Modele_turbulence_hyd_0_eq_base::associer(), Champ_Fonc_base::associer_domaine_dis_base(), Modele_turbulence_hyd_base::champs_compris_, Champ_base::changer_temps(), coeff_field, Field_base::fixer_nb_comp(), Champ_Fonc_P0_base::fixer_nb_valeurs_nodales(), Field_base::fixer_unite(), Modele_turbulence_hyd_0_eq_base::le_dom_VF_, model_coeff, Field_base::nommer(), TRUSTVect< _TYPE_, _SIZE_ >::ref(), Objet_U_ptr::typer(), TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), and Champ_Don_base::valeurs().
calculer_cell_cent_vel()
void Modele_turbulence_hyd_LES_DSGS_VDF::calculer_cell_cent_vel (DoubleTab & cell_cent_vel) protected
References Objet_U::dimension, Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), Modele_turbulence_hyd_0_eq_base::le_dom_VF_, Modele_turbulence_hyd_base::mon_equation_, Domaine_32_64< _SIZE_ >::nb_elem_tot(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by calculer_viscosite_turbulente().
calculer_filter_field()
void Modele_turbulence_hyd_LES_DSGS_VDF::calculer_filter_field (const DoubleTab & in_vel, DoubleTab & out_vel) protected
References Objet_U::dimension, Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), Domaine_VF::face_voisins(), Modele_turbulence_hyd_0_eq_base::le_dom_VF_, Domaine_32_64< _SIZE_ >::nb_elem_tot(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by calculer_viscosite_turbulente().
calculer_filter_tensor()
void Modele_turbulence_hyd_LES_DSGS_VDF::calculer_filter_tensor (DoubleTab & in_vel) protected
References Objet_U::dimension, Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), Domaine_VF::face_voisins(), Modele_turbulence_hyd_0_eq_base::le_dom_VF_, Domaine_32_64< _SIZE_ >::nb_elem_tot(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by calculer_Lij(), and calculer_Mij().
calculer_filter_coeff()
void Modele_turbulence_hyd_LES_DSGS_VDF::calculer_filter_coeff (DoubleVect & in_vel) protected
References Objet_U::dimension, Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), Domaine_VF::face_voisins(), Modele_turbulence_hyd_0_eq_base::le_dom_VF_, Domaine_32_64< _SIZE_ >::nb_elem_tot(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by calculer_model_coefficient().
calculer_Lij()
void Modele_turbulence_hyd_LES_DSGS_VDF::calculer_Lij (const DoubleTab & cell_cent_vel, const DoubleTab & filt_vel, DoubleTab & Lij) protected
References calculer_filter_tensor(), Objet_U::dimension, Domaine_dis_base::domaine(), Modele_turbulence_hyd_0_eq_base::le_dom_VF_, Domaine_32_64< _SIZE_ >::nb_elem_tot(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by calculer_viscosite_turbulente().
calculer_Sij()
void Modele_turbulence_hyd_LES_DSGS_VDF::calculer_Sij (const DoubleTab & in_vel, DoubleTab & out_vel) protected
References Champ_Face_VDF::calcul_duidxj(), Objet_U::dimension, Domaine_dis_base::domaine(), Modele_turbulence_hyd_0_eq_base::le_dom_VF_, Modele_turbulence_hyd_base::mon_equation_, Domaine_32_64< _SIZE_ >::nb_elem_tot(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by calculer_viscosite_turbulente().
calculer_Mij()
void Modele_turbulence_hyd_LES_DSGS_VDF::calculer_Mij (const DoubleTab & Sij_grid_scale, const DoubleTab & Sij_test_scale, DoubleTab & Mij) protected
References calculer_filter_tensor(), Objet_U::dimension, Domaine_dis_base::domaine(), Process::exit(), Modele_turbulence_hyd_LES_base::l_, Modele_turbulence_hyd_0_eq_base::le_dom_VF_, Domaine_32_64< _SIZE_ >::nb_elem_tot(), Objet_U::que_suis_je(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by calculer_viscosite_turbulente().
calculer_model_coefficient()
void Modele_turbulence_hyd_LES_DSGS_VDF::calculer_model_coefficient (const DoubleTab & Lij, const DoubleTab & Mij) protected
References calculer_filter_coeff(), Objet_U::dimension, Modele_turbulence_hyd_0_eq_base::le_dom_VF_, model_coeff, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by calculer_viscosite_turbulente().
calculer_viscosite_turbulente()
Champ_Fonc_base & Modele_turbulence_hyd_LES_DSGS_VDF::calculer_viscosite_turbulente () override protected virtual
Reimplemented from Modele_turbulence_hyd_LES_Smago_VDF.
References calculer_cell_cent_vel(), calculer_filter_field(), calculer_Lij(), calculer_Mij(), calculer_model_coefficient(), Modele_turbulence_hyd_LES_Smago_VDF::calculer_S_barre(), calculer_Sij(), Champ_base::changer_temps(), coeff_field, Objet_U::dimension, Process::exit(), Modele_turbulence_hyd_LES_base::l_, Modele_turbulence_hyd_base::la_viscosite_turbulente_, Modele_turbulence_hyd_0_eq_base::le_dom_VF_, model_coeff, Modele_turbulence_hyd_base::mon_equation_, TRUSTVect< _TYPE_, _SIZE_ >::resize(), TRUSTVect< _TYPE_, _SIZE_ >::size(), Modele_turbulence_hyd_LES_Smago_VDF::SMA_barre_, TRUST_Ref< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), and Debog::verifier().
Member Data Documentation
info_obj
const Type_info Modele_turbulence_hyd_LES_DSGS_VDF::info_obj static
coeff_field
TRUST_Deriv< Champ_Fonc_base > Modele_turbulence_hyd_LES_DSGS_VDF::coeff_field protected
Referenced by associer(), and calculer_viscosite_turbulente().
model_coeff
DoubleVect Modele_turbulence_hyd_LES_DSGS_VDF::model_coeff protected
Referenced by associer(), calculer_model_coefficient(), and calculer_viscosite_turbulente().