TrioCFD: Frottement_interfacial_VDF Class Reference
Frottement_interfacial_VDF Class Reference
#include <Frottement_interfacial_VDF.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Source_Frottement_interfacial_base
void completer () override
const Type_info * get_info () const override
Public Member Functions inherited from Sources_Multiphase_base
const Type_info * get_info () const override
void mettre_a_jour (double temps) override
Public Member Functions inherited from Source_base
virtual int a_pour_Champ_Fonc (const Motcle &mot, TRUST_Ref< Champ_base * > &ch_ref) const
virtual void associer_champ_rho (const Champ_base &champ_rho)
virtual void completer ()
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
virtual void resetTime (double t)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Frottement_interfacial_VDF()
Frottement_interfacial_VDF::Frottement_interfacial_VDF ()
~Frottement_interfacial_VDF()
Frottement_interfacial_VDF::~Frottement_interfacial_VDF ()
Member Function Documentation
cree_instance()
Objet_U * Frottement_interfacial_VDF::cree_instance () static
taille_memoire()
unsigned Frottement_interfacial_VDF::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Frottement_interfacial_VDF::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Frottement_interfacial_VDF::info () static
get_info()
const Type_info * Frottement_interfacial_VDF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Source_Frottement_interfacial_base.
self_cast() [1/2]
Frottement_interfacial_VDF & Frottement_interfacial_VDF::self_cast (Objet_U & r) static
self_cast() [2/2]
const Frottement_interfacial_VDF & Frottement_interfacial_VDF::self_cast (const Objet_U & r) static
printOn()
Sortie & Frottement_interfacial_VDF::printOn (Sortie & os) const override protected virtual
DOES NOTHING - to override in derived classes.
Imprime la source sur un flot de sortie.
Parameters
(Sortie& os) le flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Source_Frottement_interfacial_base.
readOn()
Entree & Frottement_interfacial_VDF::readOn (Entree & is) override protected virtual
DOES NOTHING - to override in derived classes.
Lecture d'un terme source sur un flot d'entree.
Parameters
(Entree& is) le flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Source_Frottement_interfacial_base.
References Source_Frottement_interfacial_base::readOn().
ajouter_blocs()
void Frottement_interfacial_VDF::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = {}) const override protected virtual
Implements Source_Frottement_interfacial_base.
References Source_Frottement_interfacial_base::a_res_, Frottement_interfacial_base::coefficient(), Source_Frottement_interfacial_base::correlation_, Milieu_base::diametre_hydraulique_elem(), Objet_U::dimension, Source_Frottement_interfacial_base::dv_min, MorEqn::equation(), Pb_Multiphase::equation_energie(), Pb_Multiphase::equation_masse(), Process::exit(), Source_Frottement_interfacial_base::exp_res, Champ_Face_base::fcl(), Probleme_base::get_champ(), Champ_Face_base::get_elem_vector_field(), Milieu_composite::get_interface(), Milieu_composite::get_saturation(), Interface_base::get_sigma_tab(), Nom::getString(), Probleme_base::has_champ(), Milieu_composite::has_interface(), Milieu_composite::has_saturation(), Equation_base::inconnue(), Field_base::le_nom(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Milieu_base::masse_volumique(), Equation_base::milieu(), Champ_Proto::passe(), Champ_Inc_base::passe(), Milieu_base::porosite_face(), Equation_base::probleme(), Pb_Multiphase::resolution_en_T(), Interface_base::sigma(), Interface_base::sigma_h(), Champ_Face_VDF::v_norm(), TRUST_Deriv< _CLASSE_ >::valeur(), Champ_Inc_base::valeurs(), and Champ_Proto::valeurs().
Member Data Documentation
info_obj
const Type_info Frottement_interfacial_VDF::info_obj static