TrioCFD: Op_Evanescence_Homogene_Face_base Class Reference
Op_Evanescence_Homogene_Face_base Class Reference
#include <Op_Evanescence_Homogene_Face_base.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Operateur_Evanescence_base
const Type_info * get_info () const override
Public Member Functions inherited from Operateur_base
void associer_eqn (const Equation_base &)
virtual double calculer_dt_stab () const
virtual void completer ()
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual void mettre_a_jour (double temps)
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Operateur_Evanescence_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
gestion de l'evanescence dans une equation aux faces (-> QDM)
See also
Operateur_Evanescence_base Operateur_base
Constructor & Destructor Documentation
Op_Evanescence_Homogene_Face_base()
Op_Evanescence_Homogene_Face_base::Op_Evanescence_Homogene_Face_base ()
~Op_Evanescence_Homogene_Face_base()
Op_Evanescence_Homogene_Face_base::~Op_Evanescence_Homogene_Face_base () override
Member Function Documentation
info()
const Type_info * Op_Evanescence_Homogene_Face_base::info () static
get_info()
const Type_info * Op_Evanescence_Homogene_Face_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Operateur_base.
Reimplemented in Op_Evanescence_Homogene_VDF_Face.
self_cast() [1/2]
Op_Evanescence_Homogene_Face_base & Op_Evanescence_Homogene_Face_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Op_Evanescence_Homogene_Face_base & Op_Evanescence_Homogene_Face_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Op_Evanescence_Homogene_Face_base::printOn (Sortie & os) const override protected virtual
DOES NOTHING - to override in derived classes.
Imprime l'operateur sur un flot de sortie.
Parameters
(Sortie& os) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Operateur_base.
Reimplemented in Op_Evanescence_Homogene_VDF_Face.
readOn()
Entree & Op_Evanescence_Homogene_Face_base::readOn (Entree & is) override protected virtual
DOES NOTHING - to override in derived classes.
Lit un operateur sur un flot d'entree.
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Operateur_base.
Reimplemented in Op_Evanescence_Homogene_VDF_Face.
References Param::ajouter(), alpha_res_, alpha_res_min_, Probleme_base::creer_champ(), MorEqn::equation(), Process::exit(), Probleme_base::get_correlation(), Probleme_base::has_correlation(), Param::lire_avec_accolades_depuis(), Objet_U::que_suis_je(), and Param::REQUIRED.
Referenced by Op_Evanescence_Homogene_PolyMAC_P0_Face::readOn(), Op_Evanescence_Homogene_PolyMAC_P0P1NC_Face::readOn(), and Op_Evanescence_Homogene_VDF_Face::readOn().
has_interface_blocs()
int Op_Evanescence_Homogene_Face_base::has_interface_blocs () const inline override virtual
Reimplemented from Operateur_base.
dimensionner_blocs()
void Op_Evanescence_Homogene_Face_base::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl = {}) const override virtual
Reimplemented from Operateur_base.
References Matrix_tools::allocate_morse_matrix(), TRUSTTab< _TYPE_, _SIZE_ >::append_line(), dimensionner_blocs_aux(), MorEqn::equation(), Champ_Face_base::fcl(), Matrice_Morse::get_tab1(), Matrice_Morse::get_tab2(), Nom::getString(), Field_base::le_nom(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Matrice_Morse::nb_colonnes(), Matrice_Morse::nb_lignes(), and Champ_Inc_base::valeurs().
ajouter_blocs()
void Op_Evanescence_Homogene_Face_base::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = {}) const override virtual
Reimplemented from Operateur_base.
References Process::abort(), ajouter_blocs_aux(), Vitesse_relative_base::input_t::alpha, alpha_res_, alpha_res_min_, calc_grad_alpha_faces(), calc_vort_faces(), Vitesse_relative_base::input_t::d_bulles, Vitesse_relative_base::input_t::dh, Milieu_base::diametre_hydraulique_elem(), Objet_U::dimension, TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Vitesse_relative_base::output_t::dvr, MorEqn::equation(), Pb_Multiphase::equation_qdm(), Champ_Face_base::fcl(), Vitesse_relative_base::input_t::g, Probleme_base::get_champ(), Probleme_base::get_correlation(), Milieu_composite::get_interface(), Matrice_Morse::get_set_coeff(), Matrice_Morse::get_tab1(), Matrice_Morse::get_tab2(), Nom::getString(), Vitesse_relative_base::input_t::gradAlpha, Probleme_base::has_champ(), Probleme_base::has_correlation(), Milieu_composite::has_interface(), Vitesse_relative_base::input_t::k, Field_base::le_nom(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Milieu_base::masse_volumique(), Equation_base::milieu(), Vitesse_relative_base::input_t::mu, Vitesse_relative_base::needs_grad_alpha(), Vitesse_relative_base::needs_vort(), Vitesse_relative_base::input_t::nut, Champ_Proto::passe(), Equation_base::probleme(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), Pb_Multiphase::resolution_en_T(), Vitesse_relative_base::input_t::rho, Vitesse_relative_base::input_t::sigma, Interface_base::sigma(), Interface_base::sigma_h(), Vitesse_relative_base::input_t::v, Champ_Inc_base::valeurs(), Champ_Proto::valeurs(), Vitesse_relative_base::vitesse_relative(), Vitesse_relative_base::input_t::vort, and Vitesse_relative_base::output_t::vr.
alpha_res()
double Op_Evanescence_Homogene_Face_base::alpha_res () const inline override virtual
Reimplemented from Operateur_Evanescence_base.
References alpha_res_.
calc_grad_alpha_faces()
virtual void Op_Evanescence_Homogene_Face_base::calc_grad_alpha_faces (DoubleTab &) const inline protected virtual
Reimplemented in Op_Evanescence_Homogene_PolyMAC_P0_Face, and Op_Evanescence_Homogene_VDF_Face.
References Process::exit(), and Objet_U::que_suis_je().
Referenced by ajouter_blocs().
calc_vort_faces()
void Op_Evanescence_Homogene_Face_base::calc_vort_faces (DoubleTab & vort) const protected
References Objet_U::dimension, TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), MorEqn::equation(), Probleme_base::get_champ(), Champ_Proto::passe(), and Equation_base::probleme().
Referenced by ajouter_blocs().
dimensionner_blocs_aux()
virtual void Op_Evanescence_Homogene_Face_base::dimensionner_blocs_aux (std::set< int > & , IntTab & , Matrice_Morse &) const inline protected virtual
Reimplemented in Op_Evanescence_Homogene_PolyMAC_P0_Face.
Referenced by dimensionner_blocs().
ajouter_blocs_aux()
virtual void Op_Evanescence_Homogene_Face_base::ajouter_blocs_aux (IntTrav & , DoubleTrav , matrices_t , DoubleTab &) const inline protected virtual
Reimplemented in Op_Evanescence_Homogene_PolyMAC_P0_Face.
Referenced by ajouter_blocs().
Member Data Documentation
info_obj
const Type_info Op_Evanescence_Homogene_Face_base::info_obj static
alpha_res_
double Op_Evanescence_Homogene_Face_base::alpha_res_ = 0. protected
Referenced by ajouter_blocs(), Op_Evanescence_Homogene_PolyMAC_P0_Face::ajouter_blocs_aux(), alpha_res(), and readOn().
alpha_res_min_
double Op_Evanescence_Homogene_Face_base::alpha_res_min_ = 0. protected
Referenced by ajouter_blocs(), Op_Evanescence_Homogene_PolyMAC_P0_Face::ajouter_blocs_aux(), and readOn().