TrioCFD: Convection_Diffusion_Temperature_sensibility Class Reference
Convection_Diffusion_Temperature_sensibility Class Reference
#include <Convection_Diffusion_Temperature_sensibility.h>
Public Member Functions
const Type_info * get_info () const override
int lire_motcle_non_standard (const Motcle &mot, Entree &is) override
void mettre_a_jour (double temps) override
Public Member Functions inherited from Convection_Diffusion_Temperature
void associer_milieu_base (const Milieu_base &) override
DoubleTab & derivee_en_temps_inco (DoubleTab &) override
void discretiser () override
const Motcle & domaine_application () const override
const Type_info * get_info () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
int preparer_calcul () override
Public Member Functions inherited from Convection_Diffusion_Temperature_base
void associer_milieu_base (const Milieu_base &) override
Fluide_base & fluide ()
const Type_info * get_info () const override
Public Member Functions inherited from Convection_Diffusion_std
void associer_vitesse (const Champ_base &)
const Type_info * get_info () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
int nombre_d_operateurs () const override
const Operateur & operateur (int) const override
Operateur & operateur (int) override
const Champ_Inc_base & vitesse_transportante () const
Public Member Functions inherited from Equation_base
virtual void abortTimeStep ()
virtual void associer_domaine_dis (const Domaine_dis_base &)
virtual void associer_pb_base (const Probleme_base &)
virtual void associer_sch_tps_base (const Schema_Temps_base &)
virtual double calculer_pas_de_temps () const
virtual void completer ()
virtual std::vector< YAML_data > data_a_sauvegarder () const
DoubleTab & derivee_en_temps_conv (DoubleTab &, const DoubleTab &)
virtual DoubleTab & derivee_en_temps_inco (DoubleTab &)
const Discretisation_base & discretisation () const
virtual void discretiser ()
virtual const Motcle & domaine_application () const
virtual Domaine_Cl_dis_base & domaine_Cl_dis ()
virtual const Domaine_Cl_dis_base & domaine_Cl_dis () const
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual void imprimer (Sortie &os) const
virtual bool initTimeStep (double dt)
const Nom & le_nom () const override
int limpr () const
virtual void mettre_a_jour (double temps)
virtual int preparer_calcul ()
Probleme_base & probleme ()
const Probleme_base & probleme () const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Schema_Temps_base & schema_temps ()
const Schema_Temps_base & schema_temps () const
Solveur_Masse_base & solv_masse ()
const Solveur_Masse_base & solv_masse () const
Sources & sources ()
const Sources & sources () const
virtual void valider_iteration ()
virtual void verifie_ch_init_nb_comp (const Champ_Inc_base &ch_ref, const int nb_comp) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Equation_base
virtual Entree & lire_cl (Entree &)
virtual Entree & lire_cond_init (Entree &)
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual Entree & lire_sources (Entree &)
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
virtual int verif_Cl () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
Constructor & Destructor Documentation
Convection_Diffusion_Temperature_sensibility()
Convection_Diffusion_Temperature_sensibility::Convection_Diffusion_Temperature_sensibility ()
~Convection_Diffusion_Temperature_sensibility()
Convection_Diffusion_Temperature_sensibility::~Convection_Diffusion_Temperature_sensibility ()
Member Function Documentation
cree_instance()
Objet_U * Convection_Diffusion_Temperature_sensibility::cree_instance () static
taille_memoire()
unsigned Convection_Diffusion_Temperature_sensibility::taille_memoire () const override virtual
Reimplemented from Convection_Diffusion_Temperature.
duplique()
int Convection_Diffusion_Temperature_sensibility::duplique () const override virtual
Reimplemented from Convection_Diffusion_Temperature.
info()
const Type_info * Convection_Diffusion_Temperature_sensibility::info () static
get_info()
const Type_info * Convection_Diffusion_Temperature_sensibility::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Convection_Diffusion_Temperature.
self_cast() [1/2]
Convection_Diffusion_Temperature_sensibility & Convection_Diffusion_Temperature_sensibility::self_cast (Objet_U & r) static
self_cast() [2/2]
const Convection_Diffusion_Temperature_sensibility & Convection_Diffusion_Temperature_sensibility::self_cast (const Objet_U & r) static
printOn()
Sortie & Convection_Diffusion_Temperature_sensibility::printOn (Sortie & is) const override protected virtual
Simple appel a Equation_base::printOn(Sortie&)
Parameters
(Sortie& is) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Convection_Diffusion_Temperature.
References Convection_Diffusion_Temperature::printOn().
readOn()
Entree & Convection_Diffusion_Temperature_sensibility::readOn (Entree & is) override protected virtual
cf Equation_base::readOn(Entree&)
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Exceptions
terme diffusif non specifie
terme convectif non specifie
Reimplemented from Convection_Diffusion_Temperature.
References Convection_Diffusion_Temperature::readOn().
set_param()
void Convection_Diffusion_Temperature_sensibility::set_param (Param & param) override virtual
Reimplemented from Convection_Diffusion_Temperature.
References Param::ajouter_non_std(), Param::OPTIONAL, poly_chaos, Param::REQUIRED, and Convection_Diffusion_Temperature::set_param().
lire_motcle_non_standard()
int Convection_Diffusion_Temperature_sensibility::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Convection_Diffusion_Temperature.
References associate_evaluator_field(), Process::exit(), Convection_Diffusion_Temperature::lire_motcle_non_standard(), name_state_pb, name_temperature_state_field, name_velocity_state_field, poly_chaos, Objet_U::que_suis_je(), and uncertain_var.
associate_evaluator_field()
void Convection_Diffusion_Temperature_sensibility::associate_evaluator_field (const Nom & one_name_state_pb, const Motcle & one_name_state_field)
References Process::exit(), Equation_base::le_nom(), name_velocity_state_field, Interprete::objet(), Equation_base::probleme(), temperature_state_field, and velocity_state_field.
Referenced by lire_motcle_non_standard().
update_evaluator_field()
void Convection_Diffusion_Temperature_sensibility::update_evaluator_field (const Nom & one_name_state_pb, const Motcle & one_name_state_field)
References name_velocity_state_field, Interprete::objet(), temperature_state_field, and velocity_state_field.
Referenced by mettre_a_jour().
mettre_a_jour()
void Convection_Diffusion_Temperature_sensibility::mettre_a_jour (double temps) override virtual
La valeur de l'inconnue sur le pas de temps a ete calculee.
Cette methode avance le present jusqu'au temps passe en parametre. Elle met aussi a jour les proprietes du milieu.
Parameters
(double temps) le pas de temps de mise a jour
Reimplemented from Equation_base.
References Equation_base::mettre_a_jour(), name_state_pb, name_temperature_state_field, name_velocity_state_field, and update_evaluator_field().
get_velocity_state_field()
const DoubleTab & Convection_Diffusion_Temperature_sensibility::get_velocity_state_field () const
References velocity_state_field.
get_temperature_state_field()
const DoubleTab & Convection_Diffusion_Temperature_sensibility::get_temperature_state_field () const
References temperature_state_field.
Referenced by Operateur_Conv_sensibility_VEF::ajouter(), and Terme_Boussinesq_Sensibility_VEFPreP1B_Face::ajouter().
get_velocity_state()
const Champ_Inc_base & Convection_Diffusion_Temperature_sensibility::get_velocity_state () const
References TRUST_Ref< _CLASSE_ >::valeur(), and velocity_state_field.
Referenced by Operateur_Conv_sensibility_VEF::ajouter().
get_temperature_state()
const Champ_Inc_base & Convection_Diffusion_Temperature_sensibility::get_temperature_state () const
References temperature_state_field, and TRUST_Ref< _CLASSE_ >::valeur().
get_uncertain_variable_name()
const Motcle & Convection_Diffusion_Temperature_sensibility::get_uncertain_variable_name () const
References uncertain_var.
Referenced by Operateur_Conv_sensibility_VEF::ajouter(), and Terme_Boussinesq_Sensibility_VEFPreP1B_Face::ajouter().
get_poly_chaos_value()
const double & Convection_Diffusion_Temperature_sensibility::get_poly_chaos_value () const
References poly_chaos.
Referenced by Operateur_Conv_sensibility_VEF::ajouter().
Member Data Documentation
info_obj
const Type_info Convection_Diffusion_Temperature_sensibility::info_obj static
velocity_state_field
TRUST_Ref< Champ_Inc_base *> Convection_Diffusion_Temperature_sensibility::velocity_state_field protected
Referenced by associate_evaluator_field(), get_velocity_state(), get_velocity_state_field(), and update_evaluator_field().
temperature_state_field
TRUST_Ref< Champ_Inc_base *> Convection_Diffusion_Temperature_sensibility::temperature_state_field protected
Referenced by associate_evaluator_field(), get_temperature_state(), get_temperature_state_field(), and update_evaluator_field().
name_state_pb
Nom Convection_Diffusion_Temperature_sensibility::name_state_pb protected
Referenced by lire_motcle_non_standard(), and mettre_a_jour().
name_velocity_state_field
Motcle Convection_Diffusion_Temperature_sensibility::name_velocity_state_field protected
Referenced by associate_evaluator_field(), lire_motcle_non_standard(), mettre_a_jour(), and update_evaluator_field().
name_temperature_state_field
Motcle Convection_Diffusion_Temperature_sensibility::name_temperature_state_field protected
Referenced by lire_motcle_non_standard(), and mettre_a_jour().
uncertain_var
Motcle Convection_Diffusion_Temperature_sensibility::uncertain_var protected
Referenced by get_uncertain_variable_name(), and lire_motcle_non_standard().
poly_chaos
double Convection_Diffusion_Temperature_sensibility::poly_chaos protected
Referenced by get_poly_chaos_value(), lire_motcle_non_standard(), and set_param().