TrioCFD: Paroi_FT_disc Class Reference
Paroi_FT_disc Class Reference
#include <Paroi_FT_disc.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Cond_lim_base
virtual int a_mettre_a_jour_ss_pas_dt ()
virtual void associer_domaine_cl_dis_base (const Domaine_Cl_dis_base &)
virtual void associer_fr_dis_base (const Frontiere_dis_base &)
virtual void calculer_coeffs_echange (double temps)
virtual int compatible_avec_discr (const Discretisation_base &) const
Domaine_Cl_dis_base & domaine_Cl_dis ()
const Domaine_Cl_dis_base & domaine_Cl_dis () const
virtual Frontiere_dis_base & frontiere_dis ()
virtual const Frontiere_dis_base & frontiere_dis () const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
void set_modifier_val_imp (int)
virtual void verifie_ch_init_nb_comp () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Cond_lim_base
void err_pas_compatible (const Discretisation_base &) const
void err_pas_compatible (const Equation_base &) const
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
"Transport_Interfaces_FT_disc" Le champ frontiere contient une valeur d'angle de contact exprimee en degres (voir methode readOn) Attention: l'heritage de "Symetrie" est necessaire pour
le calcul du gradient de l'indicatrice (nul au bord)
le calcul du champ indicatrice_som du fichier lml pour les cas-tests de non regression
See also
Symetrie
Member Enumeration Documentation
Type_modele
enum Paroi_FT_disc::Type_modele
Enumerator
CONSTANT
HYSTERESIS
SYMETRIE
Constructor & Destructor Documentation
Paroi_FT_disc()
Paroi_FT_disc::Paroi_FT_disc ()
~Paroi_FT_disc()
Paroi_FT_disc::~Paroi_FT_disc ()
Member Function Documentation
cree_instance()
Objet_U * Paroi_FT_disc::cree_instance () static
taille_memoire()
unsigned Paroi_FT_disc::taille_memoire () const override virtual
Reimplemented from Symetrie.
duplique()
int Paroi_FT_disc::duplique () const override virtual
Reimplemented from Symetrie.
info()
const Type_info * Paroi_FT_disc::info () static
get_info()
const Type_info * Paroi_FT_disc::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Symetrie.
self_cast() [1/2]
Paroi_FT_disc & Paroi_FT_disc::self_cast (Objet_U & r) static
self_cast() [2/2]
const Paroi_FT_disc & Paroi_FT_disc::self_cast (const Objet_U & r) static
printOn()
Sortie & Paroi_FT_disc::printOn (Sortie & s) const override protected virtual
Ecrit le type de l'objet sur un flot de sortie.
Parameters
(Sortie& s) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Symetrie.
References Objet_U::que_suis_je().
readOn()
Entree & Paroi_FT_disc::readOn (Entree & is) override protected virtual
Lecture de l'angle impose dans le jeu de donnees.
Format : soit "constant champ_frontiere_a_une_composante" soit "hysteresis champ_frontiere_a_deux_composantes" Les valeurs du champ sont un angle en degres. Convention: L'angle specifie est celui entre l'interface et la paroi du cote de la phase 0. / phase 1 /\ phase 0 / | theta ________/___|________
Reimplemented from Symetrie.
References CONSTANT, Process::exit(), Field_base::fixer_nb_comp(), HYSTERESIS, Cond_lim_base::le_champ_front, Motcles::search(), SYMETRIE, type_, and Objet_U_ptr::typer().
compatible_avec_eqn()
int Paroi_FT_disc::compatible_avec_eqn (const Equation_base & eqn) const override virtual
Cette condition aux limites ne support que l'equation Transport_Interfaces_FT_disc.
Reimplemented from Navier.
References Cond_lim_base::err_pas_compatible(), and Objet_U::que_suis_je().
get_type_modele()
Paroi_FT_disc::Type_modele Paroi_FT_disc::get_type_modele () const
References type_.
Referenced by Maillage_FT_Disc::calculer_costheta_minmax().
Member Data Documentation
info_obj
const Type_info Paroi_FT_disc::info_obj static
type_
Type_modele Paroi_FT_disc::type_ protected
Referenced by get_type_modele(), and readOn().