TrioCFD: Couplage_Tubes_IBC Class Reference
Couplage_Tubes_IBC Class Reference
#include <Couplage_Tubes_IBC.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Couplage_Tubes_IBC()
Couplage_Tubes_IBC::Couplage_Tubes_IBC ()
~Couplage_Tubes_IBC()
Couplage_Tubes_IBC::~Couplage_Tubes_IBC ()
Member Function Documentation
cree_instance()
Objet_U * Couplage_Tubes_IBC::cree_instance () static
taille_memoire()
unsigned Couplage_Tubes_IBC::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Couplage_Tubes_IBC::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Couplage_Tubes_IBC::info () static
get_info()
const Type_info * Couplage_Tubes_IBC::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
Couplage_Tubes_IBC & Couplage_Tubes_IBC::self_cast (Objet_U & r) static
self_cast() [2/2]
const Couplage_Tubes_IBC & Couplage_Tubes_IBC::self_cast (const Objet_U & r) static
printOn()
Sortie & Couplage_Tubes_IBC::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
readOn()
Entree & Couplage_Tubes_IBC::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
References Param::ajouter(), champ_miroir_, Param::dictionnaire(), epaisseur_lissage_, faisceau_, L_cube_, Param::lire_avec_accolades(), lissage_, methode_IBC_, n_P_, Interprete_bloc::objet_global(), Objet_U::que_suis_je(), Param::REQUIRED, rho_fluide_pour_adim_, solide_, and vitesse_pour_adim_.
initialize()
void Couplage_Tubes_IBC::initialize (const Domaine_IJK & dom)
References d_integrale_force_, d_integrale_force_post_proj_, faisceau_, initialize(), integrale_force_, integrale_force_N_moins_1_, integrale_force_N_moins_1_post_proj_, integrale_force_post_proj_, integrale_force_pression_, masse_fluide_cylindres_, n_P_, pression_teta_, ref_domaine_, TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUST_Vector< _CLASSE_ >::size(), and volume_cylindres_.
Referenced by initialize().
force_ibc()
void Couplage_Tubes_IBC::force_ibc (IJK_Field_double & vx, IJK_Field_double & vy, IJK_Field_double & vz, const IJK_Field_double & rho_field, double timestep, const IJK_Field_double & pressure, double current_time)
References calcul_F_pression2(), champ_miroir_, d_integrale_force_, Process::exit(), faisceau_, force_ibc_velocity(), force_ibc_velocity_frac_vol(), force_ibc_velocity_miroir(), force_ibc_velocity_symetrie_plane(), ibc0_velocity_cube(), ibc_diffuse_velocity_cube(), ibc_localisee_velocity_cube(), ibc_localisee_velocity_cube_qdm(), integrale_force_, integrale_force_N_moins_1_, integrale_force_pression_, masse_fluide_cylindres_, methode_IBC_, pression_teta_, solide_, and volume_cylindres_.
calcul_force_post_projection()
void Couplage_Tubes_IBC::calcul_force_post_projection (IJK_Field_double & vx, IJK_Field_double & vy, IJK_Field_double & vz, const IJK_Field_double & rho_field, double timestep, double current_time)
Calcul force ibc post projection.
References d_integrale_force_post_proj_, Process::exit(), faisceau_, ibc0_force_cube(), ibc_diffuse_force_cube(), ibc_localisee_force_cube(), ibc_localisee_velocity_cube_qdm(), integrale_force_, integrale_force_N_moins_1_post_proj_, integrale_force_post_proj_, masse_fluide_cylindres_, methode_IBC_, and volume_cylindres_.
champ_miroir()
void Couplage_Tubes_IBC::champ_miroir (IJK_Field_double & vx, IJK_Field_double & vy, IJK_Field_double & vz, const IJK_Field_double & rho_field, double timestep, const IJK_Field_double & pressure)
References faisceau_, force_ibc_velocity_miroir(), integrale_force_, masse_fluide_cylindres_, and volume_cylindres_.
forcage_anticipe()
void Couplage_Tubes_IBC::forcage_anticipe (IJK_Field_double & vx, IJK_Field_double & vy, IJK_Field_double & vz, const IJK_Field_double & rho_field, double timestep, const IJK_Field_double & pressure)
References faisceau_, force_ibc_velocity_anticipe_cube(), integrale_force_, masse_fluide_cylindres_, and volume_cylindres_.
force_ibc_velocity_anticipe_cube()
void Couplage_Tubes_IBC::force_ibc_velocity_anticipe_cube (IJK_Field_double & vx, IJK_Field_double & vy, IJK_Field_double & vz, const IJK_Field_double & rho_field, DoubleTab & masse_fluide_cylindres, DoubleTab & volume_cylindres, DoubleTab & integrale_force, const Faisceau_Tubes & faisceau, const double timestep) const
forcage anticpe dans le cas du cube
References Domaine_IJK::get_constant_delta(), Tube_base::get_current_pos(), Tube_base::get_current_velocity(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_domaine(), Domaine_IJK::get_node_coordinates(), Domaine_IJK::get_offset_local(), Tube_base::get_omega(), L_cube_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), TRUST_Vector< _CLASSE_ >::size(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by forcage_anticipe().
force_ibc_velocity()
void Couplage_Tubes_IBC::force_ibc_velocity (IJK_Field_double & vx, IJK_Field_double & vy, IJK_Field_double & vz, const IJK_Field_double & rho_field, DoubleTab & masse_fluide_cylindres, DoubleTab & volume_cylindres, DoubleTab & integrale_force, const Faisceau_Tubes & faisceau) const
References epaisseur_lissage_, Process::exit(), Domaine_IJK::get_constant_delta(), Tube_base::get_current_pos(), Tube_base::get_current_velocity(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_domaine(), Domaine_IJK::get_node_coordinates(), Domaine_IJK::get_offset_local(), Tube_base::get_omega(), Tube_base::get_rayon(), lissage_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), TRUST_Vector< _CLASSE_ >::size(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by force_ibc().
force_ibc_velocity_frac_vol()
void Couplage_Tubes_IBC::force_ibc_velocity_frac_vol (IJK_Field_double & vx, IJK_Field_double & vy, IJK_Field_double & vz, const IJK_Field_double & rho_field, DoubleTab & masse_fluide_cylindres, DoubleTab & volume_cylindres, DoubleTab & integrale_force, const Faisceau_Tubes & faisceau) const
References Domaine_IJK::get_constant_delta(), Tube_base::get_current_pos(), Tube_base::get_current_velocity(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_domaine(), Domaine_IJK::get_node_coordinates(), Domaine_IJK::get_offset_local(), Tube_base::get_omega(), Tube_base::get_rayon(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), TRUST_Vector< _CLASSE_ >::size(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by force_ibc().
ibc0_velocity_cube()
void Couplage_Tubes_IBC::ibc0_velocity_cube (IJK_Field_double & vx, IJK_Field_double & vy, IJK_Field_double & vz, const IJK_Field_double & rho_field, DoubleTab & masse_fluide_cylindres, DoubleTab & volume_cylindres, DoubleTab & integrale_force, const Faisceau_Tubes & faisceau) const
References Domaine_IJK::get_constant_delta(), Tube_base::get_current_pos(), Tube_base::get_current_velocity(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_domaine(), Domaine_IJK::get_node_coordinates(), Domaine_IJK::get_offset_local(), Tube_base::get_omega(), L_cube_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), TRUST_Vector< _CLASSE_ >::size(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by force_ibc().
ibc_diffuse_velocity_cube()
void Couplage_Tubes_IBC::ibc_diffuse_velocity_cube (IJK_Field_double & vx, IJK_Field_double & vy, IJK_Field_double & vz, const IJK_Field_double & rho_field, DoubleTab & masse_fluide_cylindres, DoubleTab & volume_cylindres, DoubleTab & integrale_force, const Faisceau_Tubes & faisceau) const
References Domaine_IJK::get_constant_delta(), Tube_base::get_current_pos(), Tube_base::get_current_velocity(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_domaine(), Domaine_IJK::get_node_coordinates(), Domaine_IJK::get_offset_local(), Tube_base::get_omega(), L_cube_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), TRUST_Vector< _CLASSE_ >::size(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by force_ibc().
ibc_localisee_velocity_cube()
void Couplage_Tubes_IBC::ibc_localisee_velocity_cube (IJK_Field_double & vx, IJK_Field_double & vy, IJK_Field_double & vz, const IJK_Field_double & rho_field, DoubleTab & masse_fluide_cylindres, DoubleTab & volume_cylindres, DoubleTab & integrale_force, const Faisceau_Tubes & faisceau, double current_time) const
References Domaine_IJK::get_constant_delta(), Tube_base::get_current_pos(), Tube_base::get_current_velocity(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_domaine(), Domaine_IJK::get_node_coordinates(), Domaine_IJK::get_offset_local(), Tube_base::get_omega(), L_cube_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), TRUST_Vector< _CLASSE_ >::size(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by force_ibc().
ibc_localisee_velocity_cube_qdm()
void Couplage_Tubes_IBC::ibc_localisee_velocity_cube_qdm (IJK_Field_double & vx, IJK_Field_double & vy, IJK_Field_double & vz, const IJK_Field_double & rho_field, DoubleTab & masse_fluide_cylindres, DoubleTab & volume_cylindres, DoubleTab & integrale_force, const Faisceau_Tubes & faisceau, double current_time) const
References Domaine_IJK::get_constant_delta(), Tube_base::get_current_pos(), Tube_base::get_current_velocity(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_domaine(), Domaine_IJK::get_node_coordinates(), Domaine_IJK::get_offset_local(), Tube_base::get_omega(), L_cube_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), TRUST_Vector< _CLASSE_ >::size(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by calcul_force_post_projection(), and force_ibc().
force_ibc_velocity_miroir()
void Couplage_Tubes_IBC::force_ibc_velocity_miroir (IJK_Field_double & vx, IJK_Field_double & vy, IJK_Field_double & vz, const IJK_Field_double & rho_field, DoubleTab & masse_fluide_cylindres, DoubleTab & volume_cylindres, DoubleTab & integrale_force, const Faisceau_Tubes & faisceau) const
References epaisseur_lissage_, Process::exit(), Domaine_IJK::get_constant_delta(), Tube_base::get_current_pos(), Tube_base::get_current_velocity(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_domaine(), Domaine_IJK::get_node_coordinates(), Domaine_IJK::get_offset_local(), Tube_base::get_omega(), Tube_base::get_rayon(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), TRUST_Vector< _CLASSE_ >::size(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by champ_miroir(), and force_ibc().
force_ibc_velocity_symetrie_plane()
void Couplage_Tubes_IBC::force_ibc_velocity_symetrie_plane (IJK_Field_double & vx, IJK_Field_double & vy, IJK_Field_double & vz, const IJK_Field_double & rho_field, DoubleTab & masse_fluide_cylindres, DoubleTab & volume_cylindres, DoubleTab & integrale_force, const Faisceau_Tubes & faisceau) const
fonction_ibc pour faire le champ miroir
References epaisseur_lissage_, Domaine_IJK::get_constant_delta(), Tube_base::get_current_pos(), Tube_base::get_current_velocity(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_domaine(), Domaine_IJK::get_node_coordinates(), Domaine_IJK::get_offset_local(), Tube_base::get_rayon(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), TRUST_Vector< _CLASSE_ >::size(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by force_ibc().
calcul_F_pression()
void Couplage_Tubes_IBC::calcul_F_pression (const IJK_Field_double & pressure, const IJK_Field_double & vx, DoubleTab & integrale_force_pression, DoubleTab & pression_teta, const Faisceau_Tubes & faisceau) const
References Process::exit(), Domaine_IJK::get_constant_delta(), Tube_base::get_current_pos(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_domaine(), Domaine_IJK::get_node_coordinates(), Tube_base::get_rayon(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost(), n_P_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), TRUST_Vector< _CLASSE_ >::size(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
calcul_F_pression2()
void Couplage_Tubes_IBC::calcul_F_pression2 (const IJK_Field_double & pressure, const IJK_Field_double & vx, DoubleTab & integrale_force_pression, DoubleTab & pression_teta, const Faisceau_Tubes & faisceau) const
References Domaine_IJK::get_constant_delta(), Tube_base::get_current_pos(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_domaine(), Domaine_IJK::get_node_coordinates(), Domaine_IJK::get_offset_local(), Tube_base::get_rayon(), n_P_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), TRUST_Vector< _CLASSE_ >::size(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by force_ibc().
ibc0_force_cube()
void Couplage_Tubes_IBC::ibc0_force_cube (IJK_Field_double & vx, IJK_Field_double & vy, IJK_Field_double & vz, const IJK_Field_double & rho_field, DoubleTab & masse_fluide_cylindres, DoubleTab & volume_cylindres, DoubleTab & integrale_force, const Faisceau_Tubes & faisceau) const
References Domaine_IJK::get_constant_delta(), Tube_base::get_current_pos(), Tube_base::get_current_velocity(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_domaine(), Domaine_IJK::get_node_coordinates(), Domaine_IJK::get_offset_local(), Tube_base::get_omega(), L_cube_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), TRUST_Vector< _CLASSE_ >::size(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by calcul_force_post_projection().
ibc_diffuse_force_cube()
void Couplage_Tubes_IBC::ibc_diffuse_force_cube (IJK_Field_double & vx, IJK_Field_double & vy, IJK_Field_double & vz, const IJK_Field_double & rho_field, DoubleTab & masse_fluide_cylindres, DoubleTab & volume_cylindres, DoubleTab & integrale_force, const Faisceau_Tubes & faisceau) const
References Domaine_IJK::get_constant_delta(), Tube_base::get_current_pos(), Tube_base::get_current_velocity(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_domaine(), Domaine_IJK::get_node_coordinates(), Domaine_IJK::get_offset_local(), Tube_base::get_omega(), L_cube_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), TRUST_Vector< _CLASSE_ >::size(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by calcul_force_post_projection().
ibc_localisee_force_cube()
void Couplage_Tubes_IBC::ibc_localisee_force_cube (IJK_Field_double & vx, IJK_Field_double & vy, IJK_Field_double & vz, const IJK_Field_double & rho_field, DoubleTab & masse_fluide_cylindres, DoubleTab & volume_cylindres, DoubleTab & integrale_force, const Faisceau_Tubes & , double current_time) const
Referenced by calcul_force_post_projection().
update()
void Couplage_Tubes_IBC::update (double current_time, double timestep)
reprendre_probleme()
void Couplage_Tubes_IBC::reprendre_probleme (Entree & fichier)
References Param::ajouter(), faisceau_, integrale_force_, integrale_force_N_moins_1_, Param::lire_avec_accolades(), and Objet_U::que_suis_je().
sauvegarder_probleme()
void Couplage_Tubes_IBC::sauvegarder_probleme (SFichier & f)
References faisceau_, integrale_force_, integrale_force_N_moins_1_, and Process::je_suis_maitre().
sauvegarder_pression()
void Couplage_Tubes_IBC::sauvegarder_pression (SFichier & f)
References faisceau_, Process::je_suis_maitre(), n_P_, Sortie_Fichier_base::precision(), pression_teta_, rho_fluide_pour_adim_, Sortie_Fichier_base::setf(), TRUST_Vector< _CLASSE_ >::size(), and vitesse_pour_adim_.
Member Data Documentation
info_obj
const Type_info Couplage_Tubes_IBC::info_obj static
ref_domaine_
TRUST_Ref< Domaine_IJK *> Couplage_Tubes_IBC::ref_domaine_ protected
Referenced by initialize().
lissage_
int Couplage_Tubes_IBC::lissage_ protected
Referenced by force_ibc_velocity(), and readOn().
epaisseur_lissage_
double Couplage_Tubes_IBC::epaisseur_lissage_ protected
Referenced by force_ibc_velocity(), force_ibc_velocity_miroir(), force_ibc_velocity_symetrie_plane(), and readOn().
n_P_
int Couplage_Tubes_IBC::n_P_ protected
Referenced by calcul_F_pression(), calcul_F_pression2(), initialize(), readOn(), and sauvegarder_pression().
champ_miroir_
int Couplage_Tubes_IBC::champ_miroir_ protected
Referenced by force_ibc(), and readOn().
methode_IBC_
int Couplage_Tubes_IBC::methode_IBC_ protected
Referenced by calcul_force_post_projection(), force_ibc(), and readOn().
solide_
int Couplage_Tubes_IBC::solide_ protected
Referenced by force_ibc(), and readOn().
L_cube_
double Couplage_Tubes_IBC::L_cube_ protected
Referenced by force_ibc_velocity_anticipe_cube(), ibc0_force_cube(), ibc0_velocity_cube(), ibc_diffuse_force_cube(), ibc_diffuse_velocity_cube(), ibc_localisee_velocity_cube(), ibc_localisee_velocity_cube_qdm(), and readOn().
integrale_force_
DoubleTab Couplage_Tubes_IBC::integrale_force_ protected
Referenced by calcul_force_post_projection(), champ_miroir(), forcage_anticipe(), force_ibc(), initialize(), reprendre_probleme(), and sauvegarder_probleme().
integrale_force_post_proj_
DoubleTab Couplage_Tubes_IBC::integrale_force_post_proj_ protected
Referenced by calcul_force_post_projection(), and initialize().
integrale_force_pression_
DoubleTab Couplage_Tubes_IBC::integrale_force_pression_ protected
Referenced by force_ibc(), and initialize().
pression_teta_
DoubleTab Couplage_Tubes_IBC::pression_teta_ protected
Referenced by force_ibc(), initialize(), and sauvegarder_pression().
integrale_force_N_moins_1_
DoubleTab Couplage_Tubes_IBC::integrale_force_N_moins_1_ protected
Referenced by force_ibc(), initialize(), reprendre_probleme(), and sauvegarder_probleme().
integrale_force_N_moins_1_post_proj_
DoubleTab Couplage_Tubes_IBC::integrale_force_N_moins_1_post_proj_ protected
Referenced by calcul_force_post_projection(), and initialize().
masse_fluide_cylindres_
DoubleTab Couplage_Tubes_IBC::masse_fluide_cylindres_ protected
Referenced by calcul_force_post_projection(), champ_miroir(), forcage_anticipe(), force_ibc(), and initialize().
d_integrale_force_
DoubleTab Couplage_Tubes_IBC::d_integrale_force_ protected
Referenced by force_ibc(), and initialize().
d_integrale_force_post_proj_
DoubleTab Couplage_Tubes_IBC::d_integrale_force_post_proj_ protected
Referenced by calcul_force_post_projection(), and initialize().
volume_cylindres_
DoubleTab Couplage_Tubes_IBC::volume_cylindres_ protected
Referenced by calcul_force_post_projection(), champ_miroir(), forcage_anticipe(), force_ibc(), and initialize().
rho_fluide_pour_adim_
double Couplage_Tubes_IBC::rho_fluide_pour_adim_ protected
Referenced by readOn(), and sauvegarder_pression().
vitesse_pour_adim_
double Couplage_Tubes_IBC::vitesse_pour_adim_ protected
Referenced by readOn(), and sauvegarder_pression().
faisceau_
Faisceau_Tubes Couplage_Tubes_IBC::faisceau_ protected
Referenced by calcul_force_post_projection(), champ_miroir(), forcage_anticipe(), force_ibc(), initialize(), readOn(), reprendre_probleme(), sauvegarder_pression(), and sauvegarder_probleme().