TrioCFD: Operateur_IJK_elem_diff Class Reference
Operateur_IJK_elem_diff Class Reference
#include <Operateur_IJK_elem_diff.h>
Public Member Functions
const Type_info * get_info () const override
int lire_motcle_non_standard (const Motcle &mot, Entree &is) override
Public Member Functions inherited from Objet_U_ptr
int associer_ (Objet_U &objet) override
const Type_info * get_info () const override
const Nom & le_nom () const override
Objet_U * typer (const char *nom_type)
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from TRUST_Deriv< Operateur_IJK_elem_diff_base_double >
Sortie & printOn (Sortie &os) const override
Entree & readOn (Entree &is) override
Protected Member Functions inherited from Objet_U_ptr
int change_num (const int *const) override
Objet_U * get_Objet_U_ptr_check () const
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
void recopie (const Objet_U &)
~Objet_U_ptr () override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Operateur_IJK_elem_diff()
Operateur_IJK_elem_diff::Operateur_IJK_elem_diff ()
References diffusion_op_, diffusion_op_options_, diffusion_op_words_, diffusion_rank_, is_cast_, prefix_, and suffix_.
~Operateur_IJK_elem_diff()
Operateur_IJK_elem_diff::~Operateur_IJK_elem_diff ()
Member Function Documentation
cree_instance()
Objet_U * Operateur_IJK_elem_diff::cree_instance () static
taille_memoire()
unsigned Operateur_IJK_elem_diff::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Operateur_IJK_elem_diff::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Operateur_IJK_elem_diff::info () static
get_info()
const Type_info * Operateur_IJK_elem_diff::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U_ptr.
self_cast() [1/2]
Operateur_IJK_elem_diff & Operateur_IJK_elem_diff::self_cast (Objet_U & r) static
self_cast() [2/2]
const Operateur_IJK_elem_diff & Operateur_IJK_elem_diff::self_cast (const Objet_U & r) static
printOn()
Sortie & Operateur_IJK_elem_diff::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U_ptr.
References diffusion_op_words_, and diffusion_rank_.
readOn()
Entree & Operateur_IJK_elem_diff::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U_ptr.
References typer_diffusion_op().
initialize()
void Operateur_IJK_elem_diff::initialize (const Domaine_IJK & splitting) inline
References Operateur_IJK_elem_diff_base_double::initialize(), is_cast_, typer_diffusion_op(), and TRUST_Deriv< Operateur_IJK_elem_diff_base_double >::valeur().
Referenced by IJK_Thermal_base::initialize(), IJK_Thermal_cut_cell::initialize(), and IJK_Thermal_Subresolution::initialize().
reset_operator()
void Operateur_IJK_elem_diff::reset_operator ()
References diffusion_op_, diffusion_op_options_, diffusion_rank_, and is_cast_.
Referenced by typer_diffusion_op().
typer_diffusion_op() [1/2]
void Operateur_IJK_elem_diff::typer_diffusion_op (const char * diffusion_op)
References get_diffusion_op_type(), is_cast_, reset_operator(), and Objet_U_ptr::typer().
Referenced by initialize(), IJK_Thermal_base::initialize(), and readOn().
typer_diffusion_op() [2/2]
Entree & Operateur_IJK_elem_diff::typer_diffusion_op (Entree & is)
References get_diffusion_op_type(), is_cast_, reset_operator(), Objet_U_ptr::typer(), and TRUST_Deriv< Operateur_IJK_elem_diff_base_double >::valeur().
lire_motcle_non_standard()
int Operateur_IJK_elem_diff::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Objet_U.
set_param()
void Operateur_IJK_elem_diff::set_param (Param & param)
References Param::ajouter_non_std().
get_diffusion_op_type()
Nom Operateur_IJK_elem_diff::get_diffusion_op_type (Motcle word)
References Process::abort(), diffusion_op_, diffusion_op_words_, diffusion_rank_, prefix_, Motcles::search(), suffix_, and Objet_U_ptr::typer().
Referenced by typer_diffusion_op().
set_conductivity_coefficient()
void Operateur_IJK_elem_diff::set_conductivity_coefficient (const double & uniform_lambda, const IJK_Field_local_double & lambda, IJK_Field_local_double & coeff_field_x, IJK_Field_local_double & coeff_field_y, IJK_Field_local_double & coeff_field_z)
References Process::abort(), diffusion_rank_, Operateur_IJK_elem_diff_base_double::set_coeff_x_y_z(), Operateur_IJK_elem_diff_base_double::set_lambda(), Operateur_IJK_elem_diff_base_double::set_uniform_lambda(), and TRUST_Deriv< Operateur_IJK_elem_diff_base_double >::valeur().
Referenced by IJK_Thermal_Onefluid::initialize(), and IJK_Thermal_Subresolution::initialize().
Member Data Documentation
info_obj
const Type_info Operateur_IJK_elem_diff::info_obj static
diffusion_op_words_
Motcles Operateur_IJK_elem_diff::diffusion_op_words_ protected
Referenced by get_diffusion_op_type(), Operateur_IJK_elem_diff(), and printOn().
prefix_
Nom Operateur_IJK_elem_diff::prefix_ protected
Referenced by get_diffusion_op_type(), and Operateur_IJK_elem_diff().
suffix_
Nom Operateur_IJK_elem_diff::suffix_ protected
Referenced by get_diffusion_op_type(), and Operateur_IJK_elem_diff().
diffusion_rank_
int Operateur_IJK_elem_diff::diffusion_rank_ protected
Referenced by get_diffusion_op_type(), Operateur_IJK_elem_diff(), printOn(), reset_operator(), and set_conductivity_coefficient().
diffusion_op_
Nom Operateur_IJK_elem_diff::diffusion_op_ protected
Referenced by get_diffusion_op_type(), Operateur_IJK_elem_diff(), and reset_operator().
diffusion_op_options_
Nom Operateur_IJK_elem_diff::diffusion_op_options_ protected
Referenced by Operateur_IJK_elem_diff(), and reset_operator().
is_cast_
bool Operateur_IJK_elem_diff::is_cast_ protected
Referenced by initialize(), Operateur_IJK_elem_diff(), reset_operator(), and typer_diffusion_op().