TrioCFD: Objet_U_ptr Class Reference
Objet_U_ptr Class Reference abstract
#include <Objet_U_ptr.h>
Public Member Functions
int associer_ (Objet_U &objet) override
const Type_info * get_info () const override
const Nom & le_nom () const override
Objet_U * typer (const char *nom_type)
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
int change_num (const int *const) override
Objet_U * get_Objet_U_ptr_check () const
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
void recopie (const Objet_U &)
~Objet_U_ptr () override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
Le constructeur par defaut construit un pointeur "nul".
See also
TRUST_Deriv
Constructor & Destructor Documentation
Objet_U_ptr() [1/2]
Objet_U_ptr::Objet_U_ptr (const Objet_U_ptr &) delete
~Objet_U_ptr()
Objet_U_ptr::~Objet_U_ptr () override protected
Destructeur.
Il ne detruit pas l'objet en reference
Objet_U_ptr() [2/2]
Objet_U_ptr::Objet_U_ptr () protected
construit un pointeur nul (cle a -1)
Member Function Documentation
info()
const Type_info * Objet_U_ptr::info () static
get_info()
const Type_info * Objet_U_ptr::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
Reimplemented in Operateur_IJK_elem_conv, Operateur_IJK_elem_diff, Operateur_IJK_faces_conv, Operateur_IJK_faces_diff, IJK_SolveSys_FD_thermal, Op_Diff_Fluctu_Temp, Op_Diff_Flux_Chaleur_Turb, TRUST_Deriv_Objet_U, and Operateur_Evanescence.
self_cast() [1/2]
Objet_U_ptr & Objet_U_ptr::self_cast (Objet_U & r) static
self_cast() [2/2]
const Objet_U_ptr & Objet_U_ptr::self_cast (const Objet_U & r) static
printOn()
Sortie & Objet_U_ptr::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
Reimplemented in TRUST_Deriv< _CLASSE_ >, TRUST_Deriv< Cond_lim_base >, TRUST_Deriv< Matrice_Base >, TRUST_Deriv< Op_Diff_Fluctu_Temp_Base >, TRUST_Deriv< Op_Diff_Flux_Chaleur_Turb_Base >, TRUST_Deriv< Operateur_Conv_base >, TRUST_Deriv< Operateur_Diff_base >, TRUST_Deriv< Operateur_Div_base >, TRUST_Deriv< Operateur_Evanescence_base >, TRUST_Deriv< Operateur_Grad_base >, TRUST_Deriv< Operateur_IJK_elem_conv_base_double >, TRUST_Deriv< Operateur_IJK_elem_diff_base_double >, TRUST_Deriv< Operateur_IJK_faces_conv_base_double >, TRUST_Deriv< Operateur_IJK_faces_diff_base_double >, TRUST_Deriv< SolveurSys_base >, TRUST_Deriv< Source_base >, TRUST_Deriv< Champ_Inc_base >, TRUST_Deriv< Champ_Fonc_base >, TRUST_Deriv< Champ_front_base >, TRUST_Deriv< Champ_base >, TRUST_Deriv< Elem_geom_base_32_64< int > >, TRUST_Deriv< OctreeRoot_32_64 >, TRUST_Deriv< Champ_Generique_base >, TRUST_Deriv< Champ_Don_base >, TRUST_Deriv< Correlation_base >, TRUST_Deriv< Traitement_particulier_Solide_base >, TRUST_Deriv< Domaine_Cl_dis_base >, TRUST_Deriv< Assembleur_base >, TRUST_Deriv< Modele_turbulence_scal_base >, TRUST_Deriv< Partitionneur_base_32_64 >, TRUST_Deriv< Elem_geom_base_32_64< _SIZE_ > >, TRUST_Deriv< Elem_EF_base >, TRUST_Deriv< Elem_poly_base >, TRUST_Deriv< Elem_VEF_base >, TRUST_Deriv< Diffu_totale_base >, TRUST_Deriv< Solveur_Masse_base >, TRUST_Deriv< Parametre_equation_base >, TRUST_Deriv< Modele_Permeabilite_base >, TRUST_Deriv< Loi_Etat_base >, TRUST_Deriv< EOS_Tools_base >, TRUST_Deriv< EDO_Pression_th_base >, TRUST_Deriv< Milieu_base >, TRUST_Deriv< Fluide_base >, TRUST_Deriv< Corrige_flux_FT_base >, TRUST_Deriv< Maillage_FT_Disc_Data_Cache >, TRUST_Deriv< Interface_base >, TRUST_Deriv< Equation_rayonnement_base >, TRUST_Deriv< Modele_Fonc_Bas_Reynolds_Base >, TRUST_Deriv< Modele_Fonc_Realisable_base >, TRUST_Deriv< Turbulence_paroi_base >, TRUST_Deriv< Equation_base >, TRUST_Deriv< Modele_Fonc_Bas_Reynolds_Thermique_Base >, TRUST_Deriv< Turbulence_paroi_scal_base >, TRUST_Deriv< Schema_Temps_base >, TRUST_Deriv< Source_Masse_Fluide_Dilatable_base >, TRUST_Deriv< Modele_turbulence_hyd_base >, TRUST_Deriv< Traitement_particulier_NS_base >, TRUST_Deriv< Iterateur_PolyMAC_base >, TRUST_Deriv< Iterateur_VDF_base >, TRUST_Deriv< PCShell_base >, TRUST_Deriv< Mod_echelle_LRM_base >, TRUST_Deriv< MuLambda_TBLE_base >, TRUST_Deriv< Discretisation_base >, TRUST_Deriv< Format_Post_base >, TRUST_Deriv< Precond_base >, TRUST_Deriv< Sortie_Fichier_base >, TRUST_Deriv< Solveur_Implicite_base >, TRUST_Deriv< SolvElem_base >, TRUST_Deriv< Iterateur_Source_base >, TRUST_Deriv< Interpolation_IBM_base >, TRUST_Deriv< Remailleur_Collision_FT_base >, TRUST_Deriv< Collision_Model_FT_base >, TRUST_Deriv< Algorithmes_Transport_FT_Disc >, TRUST_Deriv< Loi_2couches_base >, TRUST_Deriv< Comm_Group >, Operateur_IJK_elem_conv, Operateur_IJK_elem_diff, Operateur_IJK_faces_conv, Operateur_IJK_faces_diff, IJK_SolveSys_FD_thermal, Op_Diff_Fluctu_Temp, Op_Diff_Flux_Chaleur_Turb, TRUST_Deriv_Objet_U, and Operateur_Evanescence.
References get_Objet_U_ptr(), and Objet_U::le_type().
Referenced by TRUST_Deriv< _CLASSE_ >::printOn(), and TRUST_Deriv_Objet_U::printOn().
readOn()
Entree & Objet_U_ptr::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
Reimplemented in Operateur_IJK_elem_conv, Operateur_IJK_elem_diff, Operateur_IJK_faces_conv, Operateur_IJK_faces_diff, IJK_SolveSys_FD_thermal, Op_Diff_Fluctu_Temp, Op_Diff_Flux_Chaleur_Turb, TRUST_Deriv_Objet_U, Operateur_Evanescence, TRUST_Deriv< _CLASSE_ >, TRUST_Deriv< Cond_lim_base >, TRUST_Deriv< Matrice_Base >, TRUST_Deriv< Op_Diff_Fluctu_Temp_Base >, TRUST_Deriv< Op_Diff_Flux_Chaleur_Turb_Base >, TRUST_Deriv< Operateur_Conv_base >, TRUST_Deriv< Operateur_Diff_base >, TRUST_Deriv< Operateur_Div_base >, TRUST_Deriv< Operateur_Evanescence_base >, TRUST_Deriv< Operateur_Grad_base >, TRUST_Deriv< Operateur_IJK_elem_conv_base_double >, TRUST_Deriv< Operateur_IJK_elem_diff_base_double >, TRUST_Deriv< Operateur_IJK_faces_conv_base_double >, TRUST_Deriv< Operateur_IJK_faces_diff_base_double >, TRUST_Deriv< SolveurSys_base >, TRUST_Deriv< Source_base >, TRUST_Deriv< Champ_Inc_base >, TRUST_Deriv< Champ_Fonc_base >, TRUST_Deriv< Champ_front_base >, TRUST_Deriv< Champ_base >, TRUST_Deriv< Elem_geom_base_32_64< int > >, TRUST_Deriv< OctreeRoot_32_64 >, TRUST_Deriv< Champ_Generique_base >, TRUST_Deriv< Champ_Don_base >, TRUST_Deriv< Correlation_base >, TRUST_Deriv< Traitement_particulier_Solide_base >, TRUST_Deriv< Domaine_Cl_dis_base >, TRUST_Deriv< Assembleur_base >, TRUST_Deriv< Modele_turbulence_scal_base >, TRUST_Deriv< Partitionneur_base_32_64 >, TRUST_Deriv< Elem_geom_base_32_64< _SIZE_ > >, TRUST_Deriv< Elem_EF_base >, TRUST_Deriv< Elem_poly_base >, TRUST_Deriv< Elem_VEF_base >, TRUST_Deriv< Diffu_totale_base >, TRUST_Deriv< Solveur_Masse_base >, TRUST_Deriv< Parametre_equation_base >, TRUST_Deriv< Modele_Permeabilite_base >, TRUST_Deriv< Loi_Etat_base >, TRUST_Deriv< EOS_Tools_base >, TRUST_Deriv< EDO_Pression_th_base >, TRUST_Deriv< Milieu_base >, TRUST_Deriv< Fluide_base >, TRUST_Deriv< Corrige_flux_FT_base >, TRUST_Deriv< Maillage_FT_Disc_Data_Cache >, TRUST_Deriv< Interface_base >, TRUST_Deriv< Equation_rayonnement_base >, TRUST_Deriv< Modele_Fonc_Bas_Reynolds_Base >, TRUST_Deriv< Modele_Fonc_Realisable_base >, TRUST_Deriv< Turbulence_paroi_base >, TRUST_Deriv< Equation_base >, TRUST_Deriv< Modele_Fonc_Bas_Reynolds_Thermique_Base >, TRUST_Deriv< Turbulence_paroi_scal_base >, TRUST_Deriv< Schema_Temps_base >, TRUST_Deriv< Source_Masse_Fluide_Dilatable_base >, TRUST_Deriv< Modele_turbulence_hyd_base >, TRUST_Deriv< Traitement_particulier_NS_base >, TRUST_Deriv< Iterateur_PolyMAC_base >, TRUST_Deriv< Iterateur_VDF_base >, TRUST_Deriv< PCShell_base >, TRUST_Deriv< Mod_echelle_LRM_base >, TRUST_Deriv< MuLambda_TBLE_base >, TRUST_Deriv< Discretisation_base >, TRUST_Deriv< Format_Post_base >, TRUST_Deriv< Precond_base >, TRUST_Deriv< Sortie_Fichier_base >, TRUST_Deriv< Solveur_Implicite_base >, TRUST_Deriv< SolvElem_base >, TRUST_Deriv< Iterateur_Source_base >, TRUST_Deriv< Interpolation_IBM_base >, TRUST_Deriv< Remailleur_Collision_FT_base >, TRUST_Deriv< Collision_Model_FT_base >, TRUST_Deriv< Algorithmes_Transport_FT_Disc >, TRUST_Deriv< Loi_2couches_base >, and TRUST_Deriv< Comm_Group >.
References detach(), Process::exit(), set_Objet_U_ptr(), and typer().
Referenced by TRUST_Deriv_Objet_U::readOn(), and TRUST_Deriv< _CLASSE_ >::readOn().
operator=()
const Objet_U_ptr & Objet_U_ptr::operator= (const Objet_U_ptr &) delete
non_nul()
bool Objet_U_ptr::non_nul () const
Renvoie true si le pointeur est non_nul Renvoie false sinon.
References get_Objet_U_ptr_check().
Referenced by Milieu_base::a_gravite(), Equation_base::abortTimeStep(), Milieu_base::abortTimeStep(), Milieu_composite::abortTimeStep(), Op_Grad_EF::ajouter_bord(), Energie_Multiphase::assembler_blocs_avec_inertie(), Masse_Multiphase::assembler_blocs_avec_inertie(), QDM_Multiphase::assembler_blocs_avec_inertie(), AssembleurPVDF_PF::assembler_QC(), AssembleurPVDF_PF::assembler_rho_variable(), Cond_lim_base::associer_fr_dis_base(), Neumann_sortie_libre::associer_fr_dis_base(), Echange_interne_impose::associer_fr_dis_base(), Milieu_base::associer_gravite(), Echange_interne_impose::avancer(), Equation_base::avancer(), Op_Evanescence_Homogene_VDF_Face::calc_grad_alpha_faces(), Milieu_base::calculer_alpha(), Terme_Source_Acceleration::calculer_la_source(), Loi_Etat_GP_QC::calculer_masse_volumique(), Modele_turbulence_hyd_K_Eps::calculer_viscosite_turbulente(), Modele_turbulence_hyd_K_Eps_Bicephale::calculer_viscosite_turbulente(), Fluide_Diphasique::chaleur_latente(), Echange_interne_impose::changer_temps_futur(), Milieu_base::check_gravity_vector(), Transport_Interfaces_FT_Disc_interne::close_save_file(), Equation_base::completer(), Convection_Diffusion_Temperature_FT_Disc::completer(), Navier_Stokes_std::completer(), Source_Portance_interfaciale_base::completer(), Op_Diff_VDF_base::completer(), Op_Dift_Multiphase_VDF_Elem::completer(), Op_Dift_Multiphase_VDF_Face::completer(), Fluide_Weakly_Compressible::completer(), Milieu_base::creer_alpha(), Navier_Stokes_Turbulent_ALE::creer_champ(), Transport_Marqueur_FT::creer_champ(), Navier_Stokes_phase_field::creer_champ(), Navier_Stokes_Aposteriori::creer_champ(), Source_PDF_EF::creer_champ(), Paroi_hyd_base_EF::creer_champ(), Equation_base::creer_champ(), Convection_Diffusion_Temperature_IBM_Turbulent::creer_champ(), Navier_Stokes_IBM_Turbulent::creer_champ(), Navier_Stokes_std::creer_champ(), QDM_Multiphase::creer_champ(), Convection_Diffusion_Chaleur_Turbulent_QC::creer_champ(), Convection_Diffusion_Concentration_Turbulent::creer_champ(), Convection_Diffusion_Espece_Binaire_Turbulent_QC::creer_champ(), Convection_Diffusion_Espece_Multi_Turbulent_QC::creer_champ(), Convection_Diffusion_Temperature_Turbulent::creer_champ(), Navier_Stokes_Turbulent::creer_champ(), Modele_turbulence_hyd_base::creer_champ(), Modele_turbulence_scal_base::creer_champ(), Milieu_base::creer_champs_non_lus(), Fluide_Dilatable_base::creer_champs_non_lus(), Fluide_base::creer_nu(), Modele_turbulence_hyd_base::data_a_sauvegarder(), Modele_turbulence_scal_base::data_a_sauvegarder(), Transport_Interfaces_FT_Disc::deplacer_maillage_ft_v_fluide(), Equation_base::derivee_en_temps_inco(), Convection_Diffusion_Temperature_FT_Disc::derivee_en_temps_inco(), Navier_Stokes_std::derivee_en_temps_inco(), Navier_Stokes_FT_Disc::derivee_en_temps_inco(), Constituant::diffusivite_constituant(), Energie_Multiphase::dimensionner_blocs(), Masse_Multiphase::dimensionner_blocs(), QDM_Multiphase::dimensionner_blocs(), Energie_Multiphase::dimensionner_matrice_sans_mem(), QDM_Multiphase::dimensionner_matrice_sans_mem(), Interpolation_IBM_elem_fluid::discretise(), Interpolation_IBM_mean_gradient::discretise(), Milieu_base::discretiser(), Fluide_base::discretiser(), Fluide_Ostwald::discretiser(), Solide::discretiser(), Equation_base::domaine_Cl_dis(), Fluide_base::enthalpie(), Modele_rayo_semi_transp::eq_rayo(), Modele_turbulence_hyd_K_Eps_Bicephale::fill_turbulent_viscosity_tab(), Modele_turbulence_hyd_K_Eps::fill_turbulent_viscosity_tab(), Save_Restart::finir(), Echange_interne_impose::fixer_nb_valeurs_temporelles(), Fluide_base::fixer_type_rayo(), Navier_Stokes_Turbulent_ALE::get_champ(), Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re::get_champ(), Modele_turbulence_hyd_K_Eps::get_champ(), Modele_turbulence_hyd_K_Eps_Bas_Reynolds::get_champ(), Modele_turbulence_hyd_K_Eps_Bicephale::get_champ(), Modele_turbulence_hyd_K_Eps_Realisable::get_champ(), Modele_turbulence_hyd_K_Eps_Realisable_Bicephale::get_champ(), Convection_Diffusion_Temperature_IBM_Turbulent::get_champ(), Navier_Stokes_IBM_Turbulent::get_champ(), Convection_Diffusion_Temperature::get_champ(), Navier_Stokes_std::get_champ(), Convection_Diffusion_Chaleur_Turbulent_QC::get_champ(), Convection_Diffusion_Concentration_Turbulent::get_champ(), Convection_Diffusion_Espece_Binaire_Turbulent_QC::get_champ(), Convection_Diffusion_Espece_Multi_Turbulent_QC::get_champ(), Convection_Diffusion_Temperature_Turbulent::get_champ(), Navier_Stokes_Turbulent::get_champ(), Modele_turbulence_hyd_base::get_champ(), Modele_turbulence_scal_base::get_champ(), Conduction::get_champ(), Champ_Generique_Divergence::get_champ(), Champ_Generique_Gradient::get_champ(), Champ_Generique_Divergence::get_champ_without_evaluation(), Champ_Generique_Gradient::get_champ_without_evaluation(), Sondes::get_from_cache(), Navier_Stokes_Turbulent_ALE::get_noms_champs_postraitables(), Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re::get_noms_champs_postraitables(), Modele_turbulence_hyd_K_Eps::get_noms_champs_postraitables(), Modele_turbulence_hyd_K_Eps_Bas_Reynolds::get_noms_champs_postraitables(), Modele_turbulence_hyd_K_Eps_Bicephale::get_noms_champs_postraitables(), Modele_turbulence_hyd_K_Eps_Realisable::get_noms_champs_postraitables(), Modele_turbulence_hyd_K_Eps_Realisable_Bicephale::get_noms_champs_postraitables(), Convection_Diffusion_Temperature_IBM_Turbulent::get_noms_champs_postraitables(), Navier_Stokes_IBM_Turbulent::get_noms_champs_postraitables(), Navier_Stokes_std::get_noms_champs_postraitables(), Convection_Diffusion_Chaleur_Turbulent_QC::get_noms_champs_postraitables(), Convection_Diffusion_Concentration_Turbulent::get_noms_champs_postraitables(), Convection_Diffusion_Espece_Binaire_Turbulent_QC::get_noms_champs_postraitables(), Convection_Diffusion_Espece_Multi_Turbulent_QC::get_noms_champs_postraitables(), Convection_Diffusion_Temperature_Turbulent::get_noms_champs_postraitables(), Navier_Stokes_Turbulent::get_noms_champs_postraitables(), Modele_turbulence_hyd_base::get_noms_champs_postraitables(), Modele_turbulence_scal_base::get_noms_champs_postraitables(), Conduction::get_noms_champs_postraitables(), Milieu_base::gravite(), Fluide_base::has_beta_c(), Milieu_base::has_beta_t(), Milieu_base::has_capacite_calorifique(), Navier_Stokes_Turbulent_ALE::has_champ(), Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re::has_champ(), Modele_turbulence_hyd_K_Eps::has_champ(), Modele_turbulence_hyd_K_Eps_Bas_Reynolds::has_champ(), Modele_turbulence_hyd_K_Eps_Bicephale::has_champ(), Modele_turbulence_hyd_K_Eps_Realisable::has_champ(), Modele_turbulence_hyd_K_Eps_Realisable_Bicephale::has_champ(), Source_PDF_EF::has_champ(), Convection_Diffusion_Temperature_IBM_Turbulent::has_champ(), Navier_Stokes_IBM_Turbulent::has_champ(), Convection_Diffusion_Temperature::has_champ(), Navier_Stokes_std::has_champ(), Convection_Diffusion_Chaleur_Turbulent_QC::has_champ(), Convection_Diffusion_Concentration_Turbulent::has_champ(), Convection_Diffusion_Espece_Binaire_Turbulent_QC::has_champ(), Convection_Diffusion_Espece_Multi_Turbulent_QC::has_champ(), Convection_Diffusion_Temperature_Turbulent::has_champ(), Navier_Stokes_Turbulent::has_champ(), Modele_turbulence_hyd_base::has_champ(), Modele_turbulence_scal_base::has_champ(), Conduction::has_champ(), Equation_base::has_champ_conserve(), Equation_base::has_champ_convecte(), Energie_Multiphase::has_champ_convecte(), DomaineAxi1d_32_64< _SIZE_ >::has_champ_origine(), Terme_Source_Acceleration::has_champ_vitesse(), Milieu_base::has_conductivite(), Milieu_base::has_diffusivite(), Echange_impose_base::has_emissivite(), Navier_Stokes_std::has_grad_P(), Echange_impose_base::has_h_imp(), Energie_Multiphase::has_interface_blocs(), Masse_Multiphase::has_interface_blocs(), QDM_Multiphase::has_interface_blocs(), Fluide_base::has_kappa(), Modele_turbulence_hyd_base::has_loi_paroi_hyd(), Milieu_base::has_masse_volumique(), Terme_Source_Acceleration::has_omega(), Milieu_base::has_porosites(), Navier_Stokes_Fluide_Dilatable_base::has_source_masse(), Fluide_Dilatable_base::has_source_masse_espece_champ(), Fluide_Dilatable_base::has_source_masse_projection_champ(), Fluide_base::has_viscosite_dynamique(), Domaine_Cl_EF::imposer_symetrie(), Domaine_Cl_EF::imposer_symetrie_matrice_secmem(), Domaine_Cl_EF::imposer_symetrie_partiellement(), Transport_Interfaces_FT_Disc::impr(), Op_Diff_VDF_base::impr(), Modele_turbulence_hyd_base::imprimer(), Modele_turbulence_hyd_0_eq_base::imprimer(), Equation_base::init_champ_conserve(), Energie_Multiphase::init_champ_convecte(), Transport_Interfaces_FT_Disc_interne::init_save_file(), Milieu_base::initialiser(), Fluide_Dilatable_base::initialiser(), Constituant::initialiser(), Fluide_base::initialiser(), Fluide_reel_base::initialiser(), Neumann_sortie_libre::initialiser(), Milieu_base::initialiser_porosite(), IJK_Thermal_cut_cell::initialize(), Equation_base::initTimeStep(), Milieu_composite::initTimeStep(), Champ_Input_P0_Composite::is_initialized(), Op_Diff_Fluctu_Temp::l_op_base(), Op_Diff_Flux_Chaleur_Turb::l_op_base(), Champ_Fonc_Tabule::le_champ_tabule_discretise(), Equation_base::lire_cl(), Terme_Source_Acceleration::lire_data(), Navier_Stokes_Turbulent_ALE::lire_motcle_non_standard(), Navier_Stokes_FT_Disc::lire_motcle_non_standard(), Convection_Diffusion_Chaleur_QC::lire_motcle_non_standard(), Modele_turbulence_scal_base::loi_paroi_non_nulle(), Fluide_base::longueur_rayo_is_discretised(), Milieu_base::mettre_a_jour(), Op_Moyenne::mettre_a_jour(), Portance_interfaciale_PolyMAC_P0::mettre_a_jour(), Navier_Stokes_Fluide_Dilatable_base::mettre_a_jour(), Navier_Stokes_std::mettre_a_jour(), Constituant::mettre_a_jour(), Terme_Source_Acceleration::mettre_a_jour(), QDM_Multiphase::mettre_a_jour(), Fluide_reel_base::mettre_a_jour(), Conduction::mettre_a_jour(), Navier_Stokes_phase_field::mettre_a_jour(), Fluide_base::mettre_a_jour(), Fluide_Ostwald::mettre_a_jour(), Equation_base::mettre_a_jour_champs_conserves(), Milieu_base::mettre_a_jour_porosite(), Domaine_Cl_EF::modifie_gradient(), Op_Diff_Fluctu_Temp::op_non_nul(), Op_Diff_Flux_Chaleur_Turb::op_non_nul(), Operateur_Conv::op_non_nul(), Operateur_Diff::op_non_nul(), Operateur_Div::op_non_nul(), Operateur_Grad::op_non_nul(), Operateur_Evanescence::op_non_nul(), TRUST_Deriv< _CLASSE_ >::operator=(), TRUST_Deriv_Objet_U::operator=(), IJK_Thermal_cut_cell::perform_thermal_step(), Modele_turbulence_hyd_base::preparer_calcul(), Modele_turbulence_scal_base::preparer_calcul(), Navier_Stokes_FT_Disc::preparer_calcul(), Transport_Interfaces_FT_Disc::preparer_calcul(), Navier_Stokes_phase_field::preparer_calcul(), Navier_Stokes_IBM::preparer_calcul(), Navier_Stokes_std::preparer_calcul(), QDM_Multiphase::preparer_calcul(), Solv_GCP::printOn(), Convection_diffusion_turbulence_multiphase::readOn(), Energie_cinetique_turbulente_WIT::readOn(), Topologie_Maillage_FT::readOn(), Schema_Euler_Implicite_Stationnaire::readOn(), Puissance_Thermique_EF::readOn(), Milieu_base::readOn(), Solv_GCP::readOn(), Schema_Euler_Implicite::readOn(), Schema_Implicite_Multi_TimeStep_base::readOn(), Convection_Diffusion_Fluide_Dilatable_base::readOn(), Loi_Etat_GP_WC::readOn(), Convection_Diffusion_Concentration::readOn(), Convection_Diffusion_Temperature::readOn(), Fluide_base::readOn(), Aire_interfaciale::readOn(), Energie_Multiphase::readOn(), Masse_Multiphase::readOn(), Solide::readOn(), Terme_Puissance_Thermique_VDF_base::readOn(), Echange_interne_impose::reculer(), Equation_base::reculer(), Solv_GCP::reinit(), Solv_Gen::reinit(), Solv_Optimal::reinit(), Domaine_Cl_EF::remplir_type_elem_Cl(), Transport_Interfaces_FT_Disc::reprendre(), Navier_Stokes_std::reprendre(), Modele_turbulence_hyd_base::reprendre(), Modele_turbulence_scal_base::reprendre(), Transport_Interfaces_FT_Disc_interne::reprendre(), Equation_base::resetTime(), Milieu_base::resetTime(), Solv_GCP::resoudre_(), Solv_GCP_NS::resoudre_systeme(), Transport_Interfaces_FT_Disc::sauvegarder(), Modele_turbulence_hyd_base::sauvegarder(), Modele_turbulence_scal_base::sauvegarder(), Save_Restart::sauver(), Navier_Stokes_std::sauver(), Equation_base::set_residuals(), Echange_contact_VDF_FT_Disc::set_temps_defaut(), Echange_interne_impose::set_temps_defaut(), Solv_Gen::solve(), Navier_Stokes_Fluide_Dilatable_base::source_masse(), Fluide_Dilatable_base::source_masse_espece(), Fluide_Dilatable_base::source_masse_projection(), Solv_GCP::supporte_matrice_morse_sym(), TRUST_Deriv< _CLASSE_ >::TRUST_Deriv(), TRUST_Deriv_Objet_U::TRUST_Deriv_Objet_U(), Fluide_Weakly_Compressible::use_pth_xyz(), Modele_turbulence_hyd_base::utiliser_loi_paroi(), Echange_global_impose_rayo_semi_transp::verifie_ch_init_nb_comp(), Dirichlet::verifie_ch_init_nb_comp(), Echange_externe_impose::verifie_ch_init_nb_comp(), Neumann_paroi::verifie_ch_init_nb_comp(), Neumann_sortie_libre::verifie_ch_init_nb_comp(), Fluide_Diphasique::verifier_coherence_champs(), Fluide_Dilatable_base::verifier_coherence_champs(), Fluide_base::verifier_coherence_champs(), Fluide_Incompressible::verifier_coherence_champs(), and Solv_Optimal::~Solv_Optimal().
est_nul()
bool Objet_U_ptr::est_nul () const
References get_Objet_U_ptr_check().
Referenced by Champ_Fonc_Tabule::affecter_(), QDM_Multiphase::alpha_res(), Assembleur_P_VDF::assembler_mat(), Assembleur_P_VDF::assembler_QC(), Assembleur_P_VDF::assembler_rho_variable(), Convection_Diffusion_Fluide_Dilatable_Proto::calculer_div_rho_u_impl(), Source_Transport_K_Omega_VEF_Face::creer_champ(), Domaine_dis_base::creer_champ(), Fluide_Dilatable_base::creer_champ(), Convection_Diffusion_Temperature::creer_champ(), Convection_Diffusion_Temperature_base::creer_champ(), Navier_Stokes_std::creer_champ(), QDM_Multiphase::creer_champ(), Source_Portance_interfaciale_base::creer_champ(), Turbulence_paroi_base::creer_champ(), Conduction::creer_champ(), Fluide_Dilatable_base::creer_champs_non_lus(), Fluide_base::creer_temperature_multiphase(), Equation_base::derivee_en_temps_inco(), Fluide_Dilatable_base::discretiser(), Fluide_base::discretiser(), Fluide_base::energie_interne(), Fluide_base::enthalpie(), Simpler_Base::get_and_set_parametre_equation(), Source_PDF_EF::get_champ(), Navier_Stokes_std::get_champ(), Champ_Generique_Correlation::get_champ(), Champ_Generique_Ecart_Type::get_champ(), Champ_Generique_Moyenne::get_champ(), Champ_Generique_Reduction_0D::get_champ(), Champ_Generique_Transformation::get_champ(), Champ_Generique_Interpolation::get_champ_with_calculer_champ_post(), Champ_Generique_Transformation::get_champ_without_evaluation(), IJK_Thermal_Subresolution::initialize(), Simple::iterer_eqn(), Op_Diff_Turbulent_PolyMAC_P0_Elem::modifier_mu(), Op_Diff_Turbulent_PolyMAC_P0_Face::modifier_mu(), Loi_Etat_rhoT_GP_QC::readOn(), QDM_Multiphase::readOn(), Modele_turbulence_scal_base::readOn(), IJK_Thermal_Subresolution::solve_thermal_subproblems(), Fluide_base::temperature_multiphase(), Navier_Stokes_std::update_y_plus(), and Fluide_base::verifier_coherence_champs().
le_nom()
const Nom & Objet_U_ptr::le_nom () const override virtual
Renvoie ref_().
le_nom() si le pointeur est non nul ou "Pointeur Nul"
Reimplemented from Objet_U.
References get_Objet_U_ptr_check(), and Objet_U::le_nom().
Referenced by Source_Robin_Scalaire::ajouter(), Op_Diff_VEFP1NCP1B_Face::associer(), Puissance_Thermique_EF::associer_pb(), Terme_Source_Constituant_PolyMAC_Elem::associer_pb(), Terme_Source_Constituant_VDF_Elem::associer_pb(), Terme_Source_Constituant_VEF_Face::associer_pb(), Flux_radiatif_VDF::calculer_flux_radiatif(), Flux_radiatif_VEF::calculer_flux_radiatif(), Pb_Couple_Rayonnement::completer(), Triple_Line_Model_FT_Disc::compute_TCL_fluxes_in_all_boundary_cells(), Navier_Stokes_phase_field::creer_champ(), Postraiter_domaine::ecrire(), Eq_rayo_semi_transp_VDF::evaluer_cl_rayonnement(), Eq_rayo_semi_transp_VEF::evaluer_cl_rayonnement(), Modele_rayo_semi_transp::flux_radiatif(), Paroi_hyd_base_EF::get_champ(), Turbulence_paroi_base::get_champ(), Convection_Diffusion_Temperature_FT_Disc::get_flux_and_Twall(), Convection_Diffusion_Temperature_FT_Disc::get_flux_to_face(), Paroi_hyd_base_EF::has_champ(), Turbulence_paroi_base::has_champ(), Modele_turbulence_hyd_0_eq_base::imprimer(), Turbulence_paroi_scal_base::imprimer_premiere_ligne_nusselt(), Turbulence_paroi_base::imprimer_premiere_ligne_ustar(), ConcatAnsys::interpreter_(), Echange_contact_rayo_semi_transp_VDF::la_Cl_opposee(), Terme_Puissance_Thermique::modify_name_file(), Cond_lim::printOn(), Schema_Euler_Implicite_Stationnaire::readOn(), LoiParoiHybride_VDF::readOn(), LoiParoiHybride_VEF::readOn(), Cond_Lim_rayo_semi_transp::recherche_emissivite_et_A(), Navier_Stokes_FT_Disc::reprendre(), Navier_Stokes_std::reprendre(), Transport_Interfaces_FT_Disc_interne::reprendre(), Operateurs_Statistique_tps::reprendre(), and Operateurs_Statistique_tps::sauvegarder().
typer()
Objet_U * Objet_U_ptr::typer (const char * type)
Essaie de creer une instance du type "type".
si type n'est pas un type ou type n'est pas instanciable=>arret si type n'est pas un sous-type du type du pointeur=>retour 0 si ok, renvoie l'adresse de l'objet cree.
References detach(), Process::exit(), Nom::find(), get_info_ptr(), get_Objet_U_ptr(), Type_info::has_base(), Type_info::instance(), Type_info::instanciable(), Type_info::name(), Synonyme_info::org_name_(), set_Objet_U_ptr(), Synonyme_info::synonyme_info_from_name(), Type_info::type_info_from_name(), and typer().
Referenced by Probleme_FT_Disc_gen::add_FT_equation(), Matrix_tools::allocate_for_scaled_addition(), Matrix_tools::allocate_for_symmetric_scaled_addition(), Matrix_tools::allocate_from_stencil(), Assembleur_P_VDF_Q4::assembler(), Assembleur_P_EF::assembler_mat(), Assembleur_P_PolyMAC::assembler_mat(), Assembleur_P_PolyMAC_P0::assembler_mat(), Assembleur_P_PolyMAC_P0P1NC::assembler_mat(), Assembleur_P_VEFPreP1B::assembler_mat(), Op_Diff_RotRot::assembler_matrice(), Op_Diff_RotRot::associer(), Op_Dift_VEF_P1NCP1B_Face::associer(), Modele_turbulence_hyd_LES_DSGS_VDF::associer(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::associer(), IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::build_with_known_pattern(), IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::build_with_unknown_pattern(), IJK_SolveSys_FD_thermal::cast_direct_solver_by_default(), IJK_SolveSys_FD_thermal::cast_iterative_solver_by_default(), Champ_P1NC_implementation::Champ_P1NC_implementation(), Echange_contact_VDF_FT_Disc::completer(), Echange_contact_VDF_FT_Disc_solid::completer(), Convection_Diffusion_Temperature_FT_Disc::completer(), Echange_contact_rayo_semi_transp_VDF::completer(), Neumann_paroi_rayo_semi_transp_VDF::completer(), Neumann_paroi_rayo_semi_transp_VEF::completer(), Echange_global_impose::completer(), Paroi_Knudsen_non_negligeable::completer(), Echange_couplage_thermique::completer(), Assembleur_P_VEFPreP1B::completer(), Fluide_Dilatable_base::completer(), Fluide_Dilatable_base::completer_edo(), IJK_Thermal_Subresolution::compute_overall_probes_parameters(), AssembleurPVDF_PF::construire(), Assembleur_P_VDF::construire(), Champ_Fonc_MED::creer(), Fluide_Dilatable_base::creer_champs_non_lus(), DecoupeBord_32_64< _SIZE_ >::decouper(), Equation_base::derivee_en_temps_inco(), Equation_rayonnement_base::dimensionner_Mat_Bloc_Morse_Sym(), Champ_P1NC_implementation::dimensionner_Mat_Bloc_Morse_Sym(), Equation_base::discretiser(), Transport_Interfaces_FT_Disc::discretiser(), Navier_Stokes_phase_field::discretiser(), Fluide_Ostwald::discretiser(), Modele_rayo_semi_transp::discretiser(), Convection_Diffusion_Temperature_FT_Disc::discretiser_assembleur_pression(), Navier_Stokes_std::discretiser_assembleur_pression(), Navier_Stokes_FT_Disc::discretiser_assembleur_pression(), TroisDto2D_32_64< _SIZE_ >::extraire_2D(), Domaine_bord_32_64< _SIZE_ >::extraire_domaine_bord(), Simpler_Base::get_and_set_parametre_equation(), Operateur_IJK_elem_diff::get_diffusion_op_type(), Echange_interne_global_impose::init(), Echange_interne_impose::init(), Paroi_TBLE_QDM::init_lois_paroi(), mon_main::init_parallel(), Transport_Interfaces_FT_Disc_interne::init_save_file(), IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::initialise_matrix_subproblems(), IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::initialise_sparse_matrix_subproblems(), Echange_contact_PolyMAC::initialiser(), Echange_contact_VDF::initialiser(), IJK_Thermal_base::initialize(), IJK_Thermal_cut_cell::initialize(), IJK_Thermal_Subresolution::initialize(), Lire::interpreter(), Typer_Lire::interpreter(), MaillerParallel::interpreter(), Create_domain_from_sub_domain::interpreter_(), Lire_Tgrid::interpreter_(), Modif_bord_to_raccord_32_64< _SIZE_ >::interpreter_(), TroisDto2D_32_64< _SIZE_ >::interpreter_(), Interprete_bloc::interpreter_bloc(), Simple::iterer_eqs(), SETS::iterer_NS(), Pb_Couple_rayo_semi_transp::le_modele_rayo_associe(), Terme_Puissance_Thermique::lire_donnees(), Champ_Fonc_MED_Table_Temps::lire_donnees_champ(), Convection_Diffusion_Turbulent::lire_modele(), Navier_Stokes_Turbulent_ALE::lire_motcle_non_standard(), Schema_Phase_field::lire_motcle_non_standard(), Equation_rayonnement_base::lire_motcle_non_standard(), Transport_K_KEps::lire_motcle_non_standard(), Solveur_Lineaire_Std::lire_motcle_non_standard(), Fluide_Dilatable_base::lire_motcle_non_standard(), Fluide_Quasi_Compressible::lire_motcle_non_standard(), Navier_Stokes_std::lire_motcle_non_standard(), Conduction::lire_motcle_non_standard(), Source_Darcy_VDF_Face::lire_motcle_non_standard(), Source_Forchheimer_VDF_Face::lire_motcle_non_standard(), Source_Darcy_VEF_Face::lire_motcle_non_standard(), Source_Forchheimer_VEF_Face::lire_motcle_non_standard(), Navier_Stokes_Fluide_Dilatable_base::lire_motcle_non_standard(), Maillage_FT_Disc::Maillage_FT_Disc(), IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::make_operation_on_sub_matrix_sparse(), PlaqThVDF::mettre_a_jour(), IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::pre_initialise_matrix_subproblems(), IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::pre_initialise_sparse_matrix_subproblems(), Probleme_base::read_optional_equations(), Cond_lim_omega_demi::readOn(), Cond_lim_omega_dix::readOn(), Paroi_frottante_loi::readOn(), Paroi_frottante_simple::readOn(), Champ_Fonc_reprise_IJK::readOn(), IJK_SolveSys_FD_thermal::readOn(), Paroi_FT_disc::readOn(), Echange_contact_VDF_FT_Disc::readOn(), Echange_contact_VDF_FT_Disc_solid::readOn(), Flux_radiatif_base::readOn(), ParoiVDF_TBLE_LRM::readOn(), Transport_K_KEps::readOn(), Modele_turbulence_scal_Fluctuation_Temperature_W::readOn(), Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re::readOn(), Source_Scalaire_EF::readOn(), Dirichlet_homogene::readOn(), Dirichlet_loi_paroi::readOn(), Neumann_homogene::readOn(), Symetrie::readOn(), Periodique::readOn(), Solv_AMG::readOn(), SolveurSys::readOn(), Pb_MED::readOn(), Pbc_MED::readOn(), Postraitement::readOn(), readOn(), Champ_Fonc_reprise::readOn(), Echange_contact_PolyMAC::readOn(), Echange_contact_PolyMAC_P0P1NC::readOn(), Sortie_libre_pression_imposee_QC::readOn(), Entree_fluide_T_h_imposee::readOn(), Paroi_Knudsen_non_negligeable::readOn(), Sortie_libre_pression_imposee::readOn(), Sortie_libre_pression_moyenne_imposee::readOn(), Sortie_libre_Text_H_ext::readOn(), Echange_global_impose_turbulent::readOn(), Paroi_decalee_Robin::readOn(), Modele_turbulence_hyd_null::readOn(), Modele_turbulence_scal_null::readOn(), Echange_contact_Correlation_VDF::readOn(), Echange_contact_VDF::readOn(), PlaqThVDF::readOn(), Sortie_libre_Gradient_Pression_impose::readOn(), Sortie_libre_Pression_imposee_Orlansky::readOn(), Echange_contact_Correlation_VEF::readOn(), Sortie_libre_Gradient_Pression_impose_VEF::readOn(), Sortie_libre_Gradient_Pression_libre_VEF::readOn(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::readOn(), Matrice_Bloc::remplir(), Assembleur_P_VEF::remplir(), Matrice_Morse_Sym::renumerote(), Transport_Interfaces_FT_Disc_interne::reprendre(), Save_Restart::sauver(), Save_Restart::sauver_xyz(), Fluide_Dilatable_base::set_Cp(), Eq_couch_lim::set_diffu(), typer(), Integrale_tps_Champ::typer_champ(), Champ_Fonc_Tabule::typer_champ_tabule_discretise(), Operateur_IJK_elem_conv::typer_convection_op(), Operateur_IJK_faces_conv::typer_convection_op(), Operateur_IJK_elem_diff::typer_diffusion_op(), Operateur_IJK_faces_diff::typer_diffusion_op(), Domaine_VEF::typer_elem(), Domaine_EF::typer_elem(), Domaine_Poly_base::typer_elem(), TRUST_Deriv< _CLASSE_ >::typer_lire(), Fluide_base::typer_longeur_rayo(), Op_Diff_PolyMAC_P0P1NC_base::update_aux(), and Modele_turbulence_hyd_LES_base::verifie_loi_paroi_diphasique().
detach()
void Objet_U_ptr::detach ()
References get_Objet_U_ptr(), and set_Objet_U_ptr().
Referenced by Cond_lim::adopt(), TRUST_Deriv_Objet_U::deplace(), Milieu_base::discretiser(), Fluide_base::discretiser(), Solide::discretiser(), Save_Restart::finir(), Simple::iterer_eqn(), Save_Restart::lire_sauvegarde_reprise(), TRUST_Deriv< _CLASSE_ >::operator=(), TRUST_Deriv_Objet_U::operator=(), Source_Scalaire_EF::readOn(), Champ_Input_P0_Composite::readOn(), Solv_GCP::readOn(), readOn(), Champ_Generique_Champ::reset(), Save_Restart::sauver(), Save_Restart::sauver_xyz(), typer(), mon_main::~mon_main(), TRUST_Deriv< _CLASSE_ >::~TRUST_Deriv(), and TRUST_Deriv_Objet_U::~TRUST_Deriv_Objet_U().
associer_()
int Objet_U_ptr::associer_ (Objet_U &) override virtual
Associe l'Objet_U a un autre Objet_U Methode virtuelle a surcharger.
Parameters
(Objet_U&) l'Objet_U avec lequel doit s'effectuer l'association
Returns
(int) code de retour
Reimplemented from Objet_U.
References Objet_U::associer_(), and get_Objet_U_ptr_check().
set_Objet_U_ptr()
void Objet_U_ptr::set_Objet_U_ptr (Objet_U * ptr) protected virtual
Fait pointer *this sur l'objet *ptr L'adresse peut etre nulle (pointeur nul).
Reimplemented in TRUST_Deriv< _CLASSE_ >, TRUST_Deriv< Cond_lim_base >, TRUST_Deriv< Matrice_Base >, TRUST_Deriv< Op_Diff_Fluctu_Temp_Base >, TRUST_Deriv< Op_Diff_Flux_Chaleur_Turb_Base >, TRUST_Deriv< Operateur_Conv_base >, TRUST_Deriv< Operateur_Diff_base >, TRUST_Deriv< Operateur_Div_base >, TRUST_Deriv< Operateur_Evanescence_base >, TRUST_Deriv< Operateur_Grad_base >, TRUST_Deriv< Operateur_IJK_elem_conv_base_double >, TRUST_Deriv< Operateur_IJK_elem_diff_base_double >, TRUST_Deriv< Operateur_IJK_faces_conv_base_double >, TRUST_Deriv< Operateur_IJK_faces_diff_base_double >, TRUST_Deriv< SolveurSys_base >, TRUST_Deriv< Source_base >, TRUST_Deriv< Champ_Inc_base >, TRUST_Deriv< Champ_Fonc_base >, TRUST_Deriv< Champ_front_base >, TRUST_Deriv< Champ_base >, TRUST_Deriv< Elem_geom_base_32_64< int > >, TRUST_Deriv< OctreeRoot_32_64 >, TRUST_Deriv< Champ_Generique_base >, TRUST_Deriv< Champ_Don_base >, TRUST_Deriv< Correlation_base >, TRUST_Deriv< Traitement_particulier_Solide_base >, TRUST_Deriv< Domaine_Cl_dis_base >, TRUST_Deriv< Assembleur_base >, TRUST_Deriv< Modele_turbulence_scal_base >, TRUST_Deriv< Partitionneur_base_32_64 >, TRUST_Deriv< Elem_geom_base_32_64< _SIZE_ > >, TRUST_Deriv< Elem_EF_base >, TRUST_Deriv< Elem_poly_base >, TRUST_Deriv< Elem_VEF_base >, TRUST_Deriv< Diffu_totale_base >, TRUST_Deriv< Solveur_Masse_base >, TRUST_Deriv< Parametre_equation_base >, TRUST_Deriv< Modele_Permeabilite_base >, TRUST_Deriv< Loi_Etat_base >, TRUST_Deriv< EOS_Tools_base >, TRUST_Deriv< EDO_Pression_th_base >, TRUST_Deriv< Milieu_base >, TRUST_Deriv< Fluide_base >, TRUST_Deriv< Corrige_flux_FT_base >, TRUST_Deriv< Maillage_FT_Disc_Data_Cache >, TRUST_Deriv< Interface_base >, TRUST_Deriv< Equation_rayonnement_base >, TRUST_Deriv< Modele_Fonc_Bas_Reynolds_Base >, TRUST_Deriv< Modele_Fonc_Realisable_base >, TRUST_Deriv< Turbulence_paroi_base >, TRUST_Deriv< Equation_base >, TRUST_Deriv< Modele_Fonc_Bas_Reynolds_Thermique_Base >, TRUST_Deriv< Turbulence_paroi_scal_base >, TRUST_Deriv< Schema_Temps_base >, TRUST_Deriv< Source_Masse_Fluide_Dilatable_base >, TRUST_Deriv< Modele_turbulence_hyd_base >, TRUST_Deriv< Traitement_particulier_NS_base >, TRUST_Deriv< Iterateur_PolyMAC_base >, TRUST_Deriv< Iterateur_VDF_base >, TRUST_Deriv< PCShell_base >, TRUST_Deriv< Mod_echelle_LRM_base >, TRUST_Deriv< MuLambda_TBLE_base >, TRUST_Deriv< Discretisation_base >, TRUST_Deriv< Format_Post_base >, TRUST_Deriv< Precond_base >, TRUST_Deriv< Sortie_Fichier_base >, TRUST_Deriv< Solveur_Implicite_base >, TRUST_Deriv< SolvElem_base >, TRUST_Deriv< Iterateur_Source_base >, TRUST_Deriv< Interpolation_IBM_base >, TRUST_Deriv< Remailleur_Collision_FT_base >, TRUST_Deriv< Collision_Model_FT_base >, TRUST_Deriv< Algorithmes_Transport_FT_Disc >, TRUST_Deriv< Loi_2couches_base >, TRUST_Deriv< Comm_Group >, and TRUST_Deriv_Objet_U.
References check_Objet_U_ptr_type(), Objet_U::get_object_id(), get_Objet_U_ptr_check(), and Objet_U::numero().
Referenced by detach(), readOn(), recopie(), TRUST_Deriv< _CLASSE_ >::set_Objet_U_ptr(), TRUST_Deriv_Objet_U::set_Objet_U_ptr(), and typer().
get_Objet_U_ptr()
Objet_U * Objet_U_ptr::get_Objet_U_ptr () const protected virtual
Renvoie un pointeur sur l'Objet_U associe ATTENTION: l'adresse peut etre nulle (si le pointeur est nul)
References get_Objet_U_ptr_check(), Memoire::Instance(), and Memoire::objet_u().
Referenced by detach(), printOn(), and typer().
recopie()
void Objet_U_ptr::recopie (const Objet_U & obj) protected
Duplique l'Objet_U obj puis change le pointeur vers cette copie.
Parameters
(const Objet_U& obj) reference sur l'Objet_U a copier
References Objet_U::duplique(), Memoire::Instance(), Memoire::objet_u(), and set_Objet_U_ptr().
Referenced by TRUST_Deriv< _CLASSE_ >::operator=(), TRUST_Deriv_Objet_U::operator=(), TRUST_Deriv< _CLASSE_ >::TRUST_Deriv(), and TRUST_Deriv_Objet_U::TRUST_Deriv_Objet_U().
change_num()
int Objet_U_ptr::change_num (const int * const new_ones) override protected virtual
Pour mettre a jour les cles lorsque les Objet_U ont etes renumerotes.
Parameters
(const int* const new_ones) tableau de la nouvelle numerotation
Returns
(int) la nouvelle cle du pointeur
Reimplemented from Objet_U.
References Objet_U::change_num().
get_Objet_U_ptr_check()
Objet_U * Objet_U_ptr::get_Objet_U_ptr_check () const protected
Verifie si le pointeur est valide.
Le pointeur est valide si cle_==-1 ou si la_memoire().objet_u(cle_) a le meme object_id_ que celui enregistre dans ptr_object_id_. Si le pointeur n'est pas valide, arret du programme. Renvoie l'adresse de l'objet pointe (de type Objet_U)
References Process::exit(), Objet_U::get_object_id(), Memoire::Instance(), Objet_U::le_type(), Process::me(), and Memoire::objet_u().
Referenced by associer_(), est_nul(), get_Objet_U_ptr(), le_nom(), non_nul(), TRUST_Deriv< _CLASSE_ >::operator->(), TRUST_Deriv_Objet_U::operator->(), set_Objet_U_ptr(), TRUST_Deriv< _CLASSE_ >::valeur(), and TRUST_Deriv_Objet_U::valeur().
check_Objet_U_ptr_type()
int Objet_U_ptr::check_Objet_U_ptr_type (const Objet_U * ptr) const protected
Verifie que l'objet pointe par ptr est d'un type acceptable pour le pointeur (avec get_info_ptr)
References Type_info::can_cast(), Process::exit(), Objet_U::get_info(), get_info_ptr(), Objet_U::le_type(), Process::me(), and Type_info::name().
Referenced by set_Objet_U_ptr().
get_info_ptr()
virtual const Type_info & Objet_U_ptr::get_info_ptr () const protected pure virtual
Implemented in TRUST_Deriv< _CLASSE_ >, TRUST_Deriv< Cond_lim_base >, TRUST_Deriv< Matrice_Base >, TRUST_Deriv< Op_Diff_Fluctu_Temp_Base >, TRUST_Deriv< Op_Diff_Flux_Chaleur_Turb_Base >, TRUST_Deriv< Operateur_Conv_base >, TRUST_Deriv< Operateur_Diff_base >, TRUST_Deriv< Operateur_Div_base >, TRUST_Deriv< Operateur_Evanescence_base >, TRUST_Deriv< Operateur_Grad_base >, TRUST_Deriv< Operateur_IJK_elem_conv_base_double >, TRUST_Deriv< Operateur_IJK_elem_diff_base_double >, TRUST_Deriv< Operateur_IJK_faces_conv_base_double >, TRUST_Deriv< Operateur_IJK_faces_diff_base_double >, TRUST_Deriv< SolveurSys_base >, TRUST_Deriv< Source_base >, TRUST_Deriv< Champ_Inc_base >, TRUST_Deriv< Champ_Fonc_base >, TRUST_Deriv< Champ_front_base >, TRUST_Deriv< Champ_base >, TRUST_Deriv< Elem_geom_base_32_64< int > >, TRUST_Deriv< OctreeRoot_32_64 >, TRUST_Deriv< Champ_Generique_base >, TRUST_Deriv< Champ_Don_base >, TRUST_Deriv< Correlation_base >, TRUST_Deriv< Traitement_particulier_Solide_base >, TRUST_Deriv< Domaine_Cl_dis_base >, TRUST_Deriv< Assembleur_base >, TRUST_Deriv< Modele_turbulence_scal_base >, TRUST_Deriv< Partitionneur_base_32_64 >, TRUST_Deriv< Elem_geom_base_32_64< _SIZE_ > >, TRUST_Deriv< Elem_EF_base >, TRUST_Deriv< Elem_poly_base >, TRUST_Deriv< Elem_VEF_base >, TRUST_Deriv< Diffu_totale_base >, TRUST_Deriv< Solveur_Masse_base >, TRUST_Deriv< Parametre_equation_base >, TRUST_Deriv< Modele_Permeabilite_base >, TRUST_Deriv< Loi_Etat_base >, TRUST_Deriv< EOS_Tools_base >, TRUST_Deriv< EDO_Pression_th_base >, TRUST_Deriv< Milieu_base >, TRUST_Deriv< Fluide_base >, TRUST_Deriv< Corrige_flux_FT_base >, TRUST_Deriv< Maillage_FT_Disc_Data_Cache >, TRUST_Deriv< Interface_base >, TRUST_Deriv< Equation_rayonnement_base >, TRUST_Deriv< Modele_Fonc_Bas_Reynolds_Base >, TRUST_Deriv< Modele_Fonc_Realisable_base >, TRUST_Deriv< Turbulence_paroi_base >, TRUST_Deriv< Equation_base >, TRUST_Deriv< Modele_Fonc_Bas_Reynolds_Thermique_Base >, TRUST_Deriv< Turbulence_paroi_scal_base >, TRUST_Deriv< Schema_Temps_base >, TRUST_Deriv< Source_Masse_Fluide_Dilatable_base >, TRUST_Deriv< Modele_turbulence_hyd_base >, TRUST_Deriv< Traitement_particulier_NS_base >, TRUST_Deriv< Iterateur_PolyMAC_base >, TRUST_Deriv< Iterateur_VDF_base >, TRUST_Deriv< PCShell_base >, TRUST_Deriv< Mod_echelle_LRM_base >, TRUST_Deriv< MuLambda_TBLE_base >, TRUST_Deriv< Discretisation_base >, TRUST_Deriv< Format_Post_base >, TRUST_Deriv< Precond_base >, TRUST_Deriv< Sortie_Fichier_base >, TRUST_Deriv< Solveur_Implicite_base >, TRUST_Deriv< SolvElem_base >, TRUST_Deriv< Iterateur_Source_base >, TRUST_Deriv< Interpolation_IBM_base >, TRUST_Deriv< Remailleur_Collision_FT_base >, TRUST_Deriv< Collision_Model_FT_base >, TRUST_Deriv< Algorithmes_Transport_FT_Disc >, TRUST_Deriv< Loi_2couches_base >, TRUST_Deriv< Comm_Group >, and TRUST_Deriv_Objet_U.
Referenced by check_Objet_U_ptr_type(), and typer().
Member Data Documentation
info_obj
const Type_info Objet_U_ptr::info_obj static
HAS_POINTER
constexpr bool Objet_U_ptr::HAS_POINTER = true static constexpr