TrioCFD: Probleme_U Class Reference
Probleme_U Class Reference
#include <Probleme_U.h>
Public Member Functions
virtual void abortTimeStep ()
virtual double computeTimeStep (bool &stop) const
virtual TRUST_Ref< Field_base * > findInputField (const Nom &name) const
virtual double futureTime () const
const Type_info * get_info () const override
virtual void getInputFieldsNames (Noms &noms) const
virtual void getOutputFieldsNames (Noms &noms) const
virtual void initialize ()
virtual bool initTimeStep (double dt)
virtual bool isStationary () const
virtual bool iterateTimeStep (bool &converged)
const Nom & le_nom () const override
void nommer (const Nom &name) override
virtual int postraiter (int force=1)
virtual double presentTime () const
virtual void resetTime (double time)
virtual bool run ()
virtual bool runUntil (double time)
virtual void terminate ()
virtual bool updateGivenFields ()
virtual void validateTimeStep ()
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
Cette classe ajoute des specificites TRUST a l'interface
generale definie dans la classe Problem.
De Probleme_U derivent :
* Probleme_base pour tous les problemes individuels
* Couplage_U pour les couplages de plusieurs Probleme_U
Toutes ces classes doivent satisfaire l'API de Problem
completee par celle de Probleme_U.
Constructor & Destructor Documentation
Probleme_U()
Probleme_U::Probleme_U ()
~Probleme_U()
Probleme_U::~Probleme_U () override
Member Function Documentation
info()
const Type_info * Probleme_U::info () static
get_info()
const Type_info * Probleme_U::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
Reimplemented in Pb_Hydraulique_ALE, Pb_Hydraulique_Turbulent_ALE, Probleme_FT_Disc_gen, Probleme_FTD_IJK, Probleme_FTD_IJK_base, Probleme_FTD_IJK_cut_cell, Pb_Phase_field, Pb_Hydraulique_Aposteriori, Pb_Couple_Rayonnement, Modele_rayo_semi_transp, Pb_Couple_rayo_semi_transp, Pb_Rayo_Conduction, Pb_Rayo_Hydraulique, Pb_Rayo_Thermohydraulique, Pb_Rayo_Thermohydraulique_QC, Pb_Rayo_Hydraulique_Turbulent, Pb_Rayo_Thermohydraulique_Turbulent, Pb_Rayo_Thermohydraulique_Turbulent_QC, Pb_Hydraulique_sensibility, Pb_Thermohydraulique_sensibility, Pb_MED, Pbc_MED, Pb_Dilatable_base, Pb_Thermohydraulique_Especes_QC, Pb_Thermohydraulique_Especes_WC, Pb_Hydraulique_Melange_Binaire_QC, Pb_QC_base, Pb_Thermohydraulique_QC, Pb_Hydraulique_Melange_Binaire_WC, Pb_Thermohydraulique_WC, Pb_WC_base, Pb_Couple_Optimisation_IBM, Pb_Hydraulique_IBM, Pb_Hydraulique_IBM_Turbulent, Pb_Thermohydraulique_IBM, Pb_Thermohydraulique_IBM_Turbulent, Pb_Fluide_base, Pb_Hydraulique, Pb_Hydraulique_Concentration, Pb_Thermohydraulique, Pb_Thermohydraulique_Concentration, Pb_Thermohydraulique_Cloned_Concentration, Pb_Hydraulique_Cloned_Concentration, Pb_Thermohydraulique_List_Concentration, Pb_Hydraulique_List_Concentration, Pb_Thermohydraulique_Concentration_Scalaires_Passifs, Pb_Hydraulique_Concentration_Scalaires_Passifs, Pb_Thermohydraulique_Scalaires_Passifs, Pb_Conduction_Scalaires_Passifs, Pb_Multiphase, Pb_Multiphase_Enthalpie, Pb_Multiphase_HEM, Pb_Hydraulique_Concentration_Turbulent, Pb_Hydraulique_Melange_Binaire_Turbulent_QC, Pb_Hydraulique_Turbulent, Pb_Thermohydraulique_Concentration_Turbulent, Pb_Thermohydraulique_Turbulent, Pb_Thermohydraulique_Turbulent_QC, Pb_Thermohydraulique_Cloned_Concentration_Turbulent, Pb_Hydraulique_Cloned_Concentration_Turbulent, Pb_Thermohydraulique_List_Concentration_Turbulent, Pb_Hydraulique_List_Concentration_Turbulent, Pb_Thermohydraulique_Turbulent_Scalaires_Passifs, Pb_Thermohydraulique_Especes_Turbulent_QC, Pb_Hydraulique_Concentration_Turbulent_Scalaires_Passifs, Pb_Thermohydraulique_Concentration_Turbulent_Scalaires_Passifs, Pb_Conduction_IBM, and Pb_Conduction.
self_cast() [1/2]
Probleme_U & Probleme_U::self_cast (Objet_U & r) static
self_cast() [2/2]
const Probleme_U & Probleme_U::self_cast (const Objet_U & r) static
printOn()
Sortie & Probleme_U::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
Reimplemented in TRUSTProblem_sup_eqns< Pb_Conduction >, TRUSTProblem_sup_eqns< Pb_Hydraulique_Concentration >, TRUSTProblem_sup_eqns< Pb_Hydraulique_Concentration_Turbulent >, TRUSTProblem_sup_eqns< Pb_Thermohydraulique_Concentration >, TRUSTProblem_sup_eqns< Pb_Thermohydraulique_Concentration_Turbulent >, TRUSTProblem_sup_eqns< Pb_Thermohydraulique_QC >, TRUSTProblem_sup_eqns< Pb_Thermohydraulique_Turbulent_QC >, TRUSTProblem_sup_eqns< Pb_Thermohydraulique_WC >, TRUSTProblem_sup_eqns< Pb_Thermohydraulique >, TRUSTProblem_sup_eqns< Pb_Thermohydraulique_Turbulent >, TRUSTProblem_Concentration_Gen< Pb_Hydraulique, Convection_Diffusion_Concentration, Constituant >, TRUSTProblem_Concentration_Gen< Pb_Hydraulique_Turbulent, Convection_Diffusion_Concentration_Turbulent, Constituant >, TRUSTProblem_Concentration_Gen< Pb_Thermohydraulique, Convection_Diffusion_Concentration, Constituant >, TRUSTProblem_Concentration_Gen< Pb_Thermohydraulique_Turbulent, Convection_Diffusion_Concentration_Turbulent, Constituant >, Pb_Hydraulique_ALE, Pb_Hydraulique_Turbulent_ALE, Probleme_FT_Disc_gen, Probleme_FTD_IJK, Probleme_FTD_IJK_base, Probleme_FTD_IJK_cut_cell, Pb_Phase_field, Pb_Hydraulique_Aposteriori, Pb_Couple_Rayonnement, Modele_rayo_semi_transp, Pb_Couple_rayo_semi_transp, Pb_Rayo_Conduction, Pb_Rayo_Hydraulique, Pb_Rayo_Thermohydraulique, Pb_Rayo_Thermohydraulique_QC, Pb_Rayo_Hydraulique_Turbulent, Pb_Rayo_Thermohydraulique_Turbulent, Pb_Rayo_Thermohydraulique_Turbulent_QC, Pb_Hydraulique_sensibility, Pb_Thermohydraulique_sensibility, Pb_MED, Pbc_MED, Pb_Dilatable_base, Pb_Thermohydraulique_Especes_QC, Pb_Thermohydraulique_Especes_WC, Pb_Hydraulique_Melange_Binaire_QC, Pb_QC_base, Pb_Thermohydraulique_QC, Pb_Hydraulique_Melange_Binaire_WC, Pb_Thermohydraulique_WC, Pb_WC_base, Pb_Couple_Optimisation_IBM, Pb_Hydraulique_IBM, Pb_Hydraulique_IBM_Turbulent, Pb_Thermohydraulique_IBM, Pb_Thermohydraulique_IBM_Turbulent, Pb_Fluide_base, Pb_Hydraulique, Pb_Hydraulique_Concentration, Pb_Thermohydraulique, Pb_Thermohydraulique_Concentration, Pb_Thermohydraulique_Cloned_Concentration, Pb_Hydraulique_Cloned_Concentration, Pb_Thermohydraulique_List_Concentration, Pb_Hydraulique_List_Concentration, Pb_Thermohydraulique_Concentration_Scalaires_Passifs, Pb_Hydraulique_Concentration_Scalaires_Passifs, Pb_Thermohydraulique_Scalaires_Passifs, Pb_Conduction_Scalaires_Passifs, Pb_Multiphase, Pb_Multiphase_Enthalpie, Pb_Multiphase_HEM, Pb_Hydraulique_Concentration_Turbulent, Pb_Hydraulique_Melange_Binaire_Turbulent_QC, Pb_Hydraulique_Turbulent, Pb_Thermohydraulique_Concentration_Turbulent, Pb_Thermohydraulique_Turbulent, Pb_Thermohydraulique_Turbulent_QC, Pb_Thermohydraulique_Cloned_Concentration_Turbulent, Pb_Hydraulique_Cloned_Concentration_Turbulent, Pb_Thermohydraulique_List_Concentration_Turbulent, Pb_Hydraulique_List_Concentration_Turbulent, Pb_Thermohydraulique_Turbulent_Scalaires_Passifs, Pb_Thermohydraulique_Especes_Turbulent_QC, Pb_Hydraulique_Concentration_Turbulent_Scalaires_Passifs, Pb_Thermohydraulique_Concentration_Turbulent_Scalaires_Passifs, Pb_Conduction_IBM, and Pb_Conduction.
readOn()
Entree & Probleme_U::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
Reimplemented in Pb_Hydraulique_ALE, Pb_Hydraulique_Turbulent_ALE, Probleme_FT_Disc_gen, Probleme_FTD_IJK, Probleme_FTD_IJK_base, Probleme_FTD_IJK_cut_cell, Pb_Phase_field, Pb_Hydraulique_Aposteriori, Pb_Couple_Rayonnement, Modele_rayo_semi_transp, Pb_Couple_rayo_semi_transp, Pb_Rayo_Conduction, Pb_Rayo_Hydraulique, Pb_Rayo_Thermohydraulique, Pb_Rayo_Thermohydraulique_QC, Pb_Rayo_Hydraulique_Turbulent, Pb_Rayo_Thermohydraulique_Turbulent, Pb_Rayo_Thermohydraulique_Turbulent_QC, Pb_Hydraulique_sensibility, Pb_Thermohydraulique_sensibility, Pb_MED, Pbc_MED, Pb_Dilatable_base, Pb_Thermohydraulique_Especes_QC, Pb_Thermohydraulique_Especes_WC, Pb_Hydraulique_Melange_Binaire_QC, Pb_QC_base, Pb_Thermohydraulique_QC, Pb_Hydraulique_Melange_Binaire_WC, Pb_Thermohydraulique_WC, Pb_WC_base, Pb_Couple_Optimisation_IBM, Pb_Hydraulique_IBM, Pb_Hydraulique_IBM_Turbulent, Pb_Thermohydraulique_IBM, Pb_Thermohydraulique_IBM_Turbulent, Pb_Fluide_base, Pb_Hydraulique, Pb_Hydraulique_Concentration, Pb_Thermohydraulique, Pb_Thermohydraulique_Concentration, Pb_Thermohydraulique_Cloned_Concentration, Pb_Hydraulique_Cloned_Concentration, Pb_Thermohydraulique_List_Concentration, Pb_Hydraulique_List_Concentration, Pb_Thermohydraulique_Concentration_Scalaires_Passifs, Pb_Hydraulique_Concentration_Scalaires_Passifs, Pb_Thermohydraulique_Scalaires_Passifs, Pb_Conduction_Scalaires_Passifs, Pb_Multiphase, Pb_Multiphase_Enthalpie, Pb_Multiphase_HEM, Pb_Hydraulique_Concentration_Turbulent, Pb_Hydraulique_Melange_Binaire_Turbulent_QC, Pb_Hydraulique_Turbulent, Pb_Thermohydraulique_Concentration_Turbulent, Pb_Thermohydraulique_Turbulent, Pb_Thermohydraulique_Turbulent_QC, Pb_Thermohydraulique_Cloned_Concentration_Turbulent, Pb_Hydraulique_Cloned_Concentration_Turbulent, Pb_Thermohydraulique_List_Concentration_Turbulent, Pb_Hydraulique_List_Concentration_Turbulent, Pb_Thermohydraulique_Turbulent_Scalaires_Passifs, Pb_Thermohydraulique_Especes_Turbulent_QC, Pb_Hydraulique_Concentration_Turbulent_Scalaires_Passifs, Pb_Thermohydraulique_Concentration_Turbulent_Scalaires_Passifs, Pb_Conduction_IBM, Pb_Conduction, TRUSTProblem_sup_eqns< Pb_Conduction >, TRUSTProblem_sup_eqns< Pb_Hydraulique_Concentration >, TRUSTProblem_sup_eqns< Pb_Hydraulique_Concentration_Turbulent >, TRUSTProblem_sup_eqns< Pb_Thermohydraulique_Concentration >, TRUSTProblem_sup_eqns< Pb_Thermohydraulique_Concentration_Turbulent >, TRUSTProblem_sup_eqns< Pb_Thermohydraulique_QC >, TRUSTProblem_sup_eqns< Pb_Thermohydraulique_Turbulent_QC >, TRUSTProblem_sup_eqns< Pb_Thermohydraulique_WC >, TRUSTProblem_sup_eqns< Pb_Thermohydraulique >, TRUSTProblem_sup_eqns< Pb_Thermohydraulique_Turbulent >, TRUSTProblem_Cloned_Concentration_Gen< Pb_Hydraulique >, TRUSTProblem_Cloned_Concentration_Gen< Pb_Hydraulique_Turbulent, Convection_Diffusion_Concentration_Turbulent, Constituant >, TRUSTProblem_Cloned_Concentration_Gen< Pb_Thermohydraulique >, TRUSTProblem_Cloned_Concentration_Gen< Pb_Thermohydraulique_Turbulent, Convection_Diffusion_Concentration_Turbulent, Constituant >, TRUSTProblem_List_Concentration_Gen< Pb_Hydraulique >, TRUSTProblem_List_Concentration_Gen< Pb_Hydraulique_Turbulent, Convection_Diffusion_Concentration_Turbulent, Constituant >, TRUSTProblem_List_Concentration_Gen< Pb_Thermohydraulique >, and TRUSTProblem_List_Concentration_Gen< Pb_Thermohydraulique_Turbulent, Convection_Diffusion_Concentration_Turbulent, Constituant >.
initialize()
void Probleme_U::initialize () virtual
This method is called once at the beginning, before any other one of the interface Problem.
Exceptions
WrongContext
Reimplemented in Probleme_FTD_IJK, Probleme_FTD_IJK_base, Probleme_FTD_IJK_cut_cell, Pb_Couple_Rayonnement, Pb_Couple_rayo_semi_transp, Couplage_U, Probleme_base, Probleme_Couple, and Pb_Couple_Optimisation_IBM.
Referenced by Couplage_U::initialize(), ICoCo::ProblemTrio::initialize_pb(), and Resoudre::interpreter().
terminate()
void Probleme_U::terminate () virtual
This method is called once at the end, after any other one.
It frees the memory and saves anything that needs to be saved.
Exceptions
WrongContext
Reimplemented in Probleme_FTD_IJK_base, Modele_rayo_semi_transp, Couplage_U, and Probleme_base.
Referenced by Resoudre::interpreter(), Couplage_U::terminate(), and ICoCo::ProblemTrio::terminate().
presentTime()
double Probleme_U::presentTime () const virtual
Returns the present time.
This value may change only at the call of validateTimeStep. A surcharger
Returns
(double) present time
Exceptions
WrongContext
Reimplemented in Probleme_FTD_IJK_base, Couplage_U, and Probleme_base.
Referenced by Couplage_U::presentTime(), ICoCo::ProblemTrio::presentTime(), runUntil(), and setInputField().
computeTimeStep()
double Probleme_U::computeTimeStep (bool & stop) const virtual
Compute the value the Problem would like for the next time step.
This value will not necessarily be used at the call of initTimeStep, but it is a hint. This method may use all the internal state of the Problem.
Parameters
(stop) Does the Problem want to stop ?
Returns
(double) The desired time step
Exceptions
WrongContext
Reimplemented in Probleme_FTD_IJK_base, Modele_rayo_semi_transp, Probleme_base, and Probleme_Couple.
Referenced by Probleme_Couple::computeTimeStep(), ICoCo::ProblemTrio::computeTimeStep(), run(), and runUntil().
initTimeStep()
bool Probleme_U::initTimeStep (double dt) virtual
This method allocates and initializes the unknown and given fields for the future time step.
The value of the interval is imposed through the parameter dt. In case of error, returns false.
Parameters
(double dt) the time interval to allocate
Returns
(bool) true=OK, false=error, not able to tackle this dt
Exceptions
WrongContext,WrongArgument
Reimplemented in Probleme_FTD_IJK_base, Modele_rayo_semi_transp, Couplage_U, Probleme_base, Probleme_Couple, and Pb_Dilatable_base.
Referenced by Couplage_U::initTimeStep(), ICoCo::ProblemTrio::initTimeStep(), run(), and runUntil().
solveTimeStep()
bool Probleme_U::solveTimeStep () virtual
pour recodage eventuel et appel unifie en python
Reimplemented in Probleme_FTD_IJK_base, Probleme_base, and Probleme_Couple.
References iterateTimeStep(), and updateGivenFields().
Referenced by run(), runUntil(), Probleme_Couple::solveTimeStep(), ICoCo::ProblemTrio::solveTimeStep(), and Probleme_base::solveTimeStep_pbU().
validateTimeStep()
void Probleme_U::validateTimeStep () virtual
Validates the calculated unknown by moving the present time at the end of the time step.
This method is allowed to free past values of the unknown and given fields.
Exceptions
WrongContext
Reimplemented in Probleme_FTD_IJK_base, Pb_Couple_Rayonnement, Modele_rayo_semi_transp, Couplage_U, Probleme_base, and Pb_Couple_Optimisation_IBM.
Referenced by run(), runUntil(), Couplage_U::validateTimeStep(), and ICoCo::ProblemTrio::validateTimeStep().
isStationary()
bool Probleme_U::isStationary () const virtual
Tells if the Problem unknowns have changed during the last time step.
Returns
(bool) true=stationary, false=not stationary
Exceptions
WrongContext
Reimplemented in Couplage_U, and Probleme_base.
Referenced by Couplage_U::isStationary(), ICoCo::ProblemTrio::isStationary(), and run().
newCompute()
virtual std::string Probleme_U::newCompute () inline virtual
Reimplemented in Couplage_U, and Probleme_base.
Referenced by run().
setStationary()
void Probleme_U::setStationary (bool) virtual
Tells to the Problem that stationary is reached or not.
Reimplemented in Probleme_FTD_IJK_base, Probleme_base, and Couplage_U.
Referenced by run(), and Couplage_U::setStationary().
abortTimeStep()
void Probleme_U::abortTimeStep () virtual
Aborts the resolution of the current time step.
Exceptions
WrongContext
Reimplemented in Probleme_FTD_IJK_base, Couplage_U, and Probleme_base.
Referenced by Couplage_U::abortTimeStep(), ICoCo::ProblemTrio::abortTimeStep(), run(), and runUntil().
resetTime()
void Probleme_U::resetTime (double time) virtual
Reset the current time of the Problem to a given value.
Particularly useful for the initialization of complex transients: the starting point of the transient of interest is computed first, the time is reset to 0, and then the actual transient of interest starts with proper initial conditions, and global time 0.
Parameters
[in] time the new current time.
Exceptions
ICoCo::WrongContext exception if called before initialize() or after terminate().
ICoCo::WrongContext exception if called inside the TIME_STEP_DEFINED context (see Problem documentation)
Reimplemented in Couplage_U, Probleme_FTD_IJK_base, and Probleme_base.
Referenced by Couplage_U::resetTime(), ICoCo::ProblemTrio::resetTime(), and run().
iterateTimeStep()
bool Probleme_U::iterateTimeStep (bool & converged) virtual
In the case solveTimeStep uses an iterative process, this method executes a single iteration.
It is thus possible to modify the given fields between iterations. converged is set to true if the process has converged, ie if the unknown fields are solution to the problem on the next time step. Otherwise converged is set to false. The return value indicates if the convergence process behaves normally. If false, the Problem wishes to abort the time step resolution.
Parameters
(bool& converged) It is a return value : true if the process has converged, false otherwise.
Returns
(bool) true=OK, false=unable to converge
Exceptions
WrongContext
Reimplemented in Probleme_FTD_IJK_base, Modele_rayo_semi_transp, Couplage_U, Probleme_base, Probleme_Couple, and Pb_Dilatable_base.
Referenced by Couplage_U::iterateTimeStep(), Probleme_Couple::iterateTimeStep(), ICoCo::ProblemTrio::iterateTimeStep(), and solveTimeStep().
getInputFieldsNames()
void Probleme_U::getInputFieldsNames (Noms & noms) const virtual
This method is used to find the names of input fields understood by the Problem.
Parameters
(Noms) list of names where the Problem appends its input field names.
Reimplemented in Couplage_U, and Probleme_base.
Referenced by ICoCo::ProblemTrio::getInputFieldsNames(), and Couplage_U::getInputFieldsNames().
getInputFieldTemplate()
void Probleme_U::getInputFieldTemplate (const Nom & name, ICoCo::TrioField & afield) const virtual
This method is used to get a template of a field expected for the given name.
References findInputField(), Nom::getString(), Champ_Input_Proto::getTemplate(), and le_nom().
Referenced by ICoCo::ProblemTrio::getInputFieldTemplate().
setInputField()
void Probleme_U::setInputField (const Nom & name, const ICoCo::TrioField & afield) virtual
This method is used to provide the Problem with an input field.
References findInputField(), futureTime(), Nom::getChar(), Nom::getString(), le_nom(), presentTime(), and Champ_Input_Proto::setValue().
Referenced by ICoCo::ProblemTrio::setInputField().
getOutputFieldsNames()
void Probleme_U::getOutputFieldsNames (Noms & noms) const virtual
This method is used to find the names of output fields understood by the Problem.
Parameters
(Noms) list of names where the Problem appends its output field names.
Reimplemented in Couplage_U, and Probleme_base.
Referenced by ICoCo::ProblemTrio::getOutputFieldsNames(), and Couplage_U::getOutputFieldsNames().
getOutputField()
void Probleme_U::getOutputField (const Nom & nameField, ICoCo::TrioField & afield) const virtual
References findOutputField(), Nom::getString(), and le_nom().
Referenced by ICoCo::ProblemTrio::getOutputField().
setInputIntValue()
void Probleme_U::setInputIntValue (const Nom & name, const int & val) virtual
References reg_, and ScalarRegister::setInputIntValue().
Referenced by ICoCo::ProblemTrio::setInputIntValue().
getOutputIntValue()
int Probleme_U::getOutputIntValue (const Nom & name) const virtual
References ScalarRegister::getOutputIntValue(), and reg_.
Referenced by ICoCo::ProblemTrio::getOutputIntValue().
setInputDoubleValue()
void Probleme_U::setInputDoubleValue (const Nom & name, const double val) virtual
References findInputField(), Nom::getString(), le_nom(), and Champ_Input_Proto::setDoubleValue().
Referenced by ICoCo::ProblemTrio::setInputDoubleValue().
setInputStringValue()
virtual void Probleme_U::setInputStringValue (const std::string & name, const std::string & val) inline virtual
References str_params_.
Referenced by Couplage_U::resetTime(), run(), and ICoCo::ProblemTrio::setInputStringValue().
getOutputStringValue()
std::string Probleme_U::getOutputStringValue (const std::string & name) virtual
References str_params_.
Referenced by ICoCo::ProblemTrio::getOutputStringValue(), Couplage_U::resetTime(), and Probleme_base::resetTime().
post_initialize()
virtual void Probleme_U::post_initialize () inline virtual
Referenced by Couplage_U::initialize().
postraiter()
int Probleme_U::postraiter (int force = 1) virtual
Demande au probleme de postraiter ses champs, sondes,.
.. Dans Probleme_U::run(), postraiter() est appele a chaque pas de temps avec force=0 et au debut et a la fin du calcul avec force=1. WEC : il serait bon que, un jour, postraiter soit const
Parameters
(force) 1=postraiter absolument, 0=postraiter si c'est necessaire.
Returns
(0 en cas d'erreur, 1 sinon.)
Reimplemented in Pb_Couple_Rayonnement, Couplage_U, and Probleme_base.
Referenced by ICoCo::ProblemTrio::initialize_pb(), Couplage_U::postraiter(), run(), runUntil(), ICoCo::ProblemTrio::terminate(), and ICoCo::ProblemTrio::validateTimeStep().
limpr()
int Probleme_U::limpr () const virtual
Doit-on imprimer les statistiques d'execution maintenant ?
Reimplemented in Couplage_U, and Probleme_base.
Referenced by Couplage_U::limpr(), run(), and runUntil().
lsauv()
int Probleme_U::lsauv () const virtual
Doit-on sauvegarder l'etat du probleme sur disque maintenant ?
Reimplemented in Couplage_U, and Probleme_base.
Referenced by Couplage_U::lsauv(), run(), and ICoCo::ProblemTrio::solveTimeStep().
sauver()
void Probleme_U::sauver () const virtual
Sauvegarder l'etat du probleme sur disque.
Reimplemented in Probleme_FTD_IJK_base, Couplage_U, Probleme_base, and Probleme_Couple.
Referenced by run(), Couplage_U::sauver(), and ICoCo::ProblemTrio::solveTimeStep().
updateGivenFields()
bool Probleme_U::updateGivenFields () virtual
ATTENTION :
Rentre ici tout ce qui ne correspond pas a l'API normale de Problem.
Actuellement on y met a jour les CLs et les termes sources, sachant que certains vont chercher eux-memes des informations dans les problemes voisins...
Programme de travail : tout ce qui est dans cette methode doit etre rendu independant de l'exterieur, et peut du coup rejoindre initTimeStep. Le reste passe dans l'interface d'echange de champs. Ce travail sera fini quand updateGivenFields sera vide et supprime !
Returns
(true=OK, false=error)
Reimplemented in Probleme_FT_Disc_gen, Probleme_FTD_IJK_base, Couplage_U, Probleme_base, and Probleme_Couple.
Referenced by Schema_Euler_Implicite::faire_un_pas_de_temps_pb_couple(), Schema_Implicite_Multi_TimeStep_base::faire_un_pas_de_temps_pb_couple(), Probleme_Couple::iterateTimeStep(), solveTimeStep(), and Couplage_U::updateGivenFields().
futureTime()
double Probleme_U::futureTime () const virtual
Returns the future time (end of current computing interval) This value is valid between initTimeStep and either.
validateTimeStep or abortTimeStep. A surcharger
Returns
(double) future time
Exceptions
WrongContext
Reimplemented in Couplage_U, and Probleme_base.
Referenced by Couplage_U::futureTime(), and setInputField().
run()
bool Probleme_U::run () virtual
Cette methode est une sorte de main() du Problem Elle peut etre utilisee si le probleme n'est couple a aucun autre.
(s'il n'a besoin d'aucun champ d'entree).
Returns
(bool) true=OK, false=error
Reimplemented in Probleme_FTD_IJK_base.
References abortTimeStep(), Statistiques::begin_count(), Statistiques::compute_avg_min_max_var_per_step(), computeTimeStep(), Objet_U::disable_TU, Statistiques::dump(), Statistiques::end_count(), initTimeStep(), isStationary(), Statistiques::last_time(), limpr(), lsauv(), newCompute(), postraiter(), Statistiques::print_communciation_tracking_details(), Statistiques::reset_counters(), resetTime(), sauver(), Statistiques::set_three_first_steps_elapsed(), setInputStringValue(), setStationary(), solveTimeStep(), and validateTimeStep().
Referenced by Resoudre::interpreter().
runUntil()
bool Probleme_U::runUntil (double time) virtual
This method has the same role as the method run, but it stops when reaching the time given in parameter.
If this time cannot be reached, the method returns false.
Parameters
(double time) time to reach
Returns
(true=OK, false=error)
References abortTimeStep(), Statistiques::begin_count(), computeTimeStep(), Statistiques::end_count(), initTimeStep(), Process::je_suis_maitre(), Statistiques::last_time(), limpr(), postraiter(), presentTime(), solveTimeStep(), and validateTimeStep().
findInputField()
TRUST_Ref< Field_base * > Probleme_U::findInputField (const Nom & name) const virtual
This method is used to find in a hierarchy of problems the Champ_Input_Proto of a given name.
Implementation is not optimal in 2 ways :
no error if two input fields have the same name.
no optimisation of the number of REF objects created and destroyed.
Parameters
(string name) name of the input field we are looking for
Returns
(OBS_PTR(Field_base)) found <=> non_nul(), then points to a Champ_Input_Proto of that name.
Reimplemented in Couplage_U, and Probleme_base.
Referenced by Couplage_U::findInputField(), getInputFieldTemplate(), setInputDoubleValue(), setInputField(), and ICoCo::ProblemTrio::setInputMEDDoubleField().
findOutputField()
TRUST_Ref< Champ_Generique_base * > Probleme_U::findOutputField (const Nom & name) const virtual
Reimplemented in Couplage_U, and Probleme_base.
Referenced by Couplage_U::findOutputField(), and getOutputField().
nommer()
void Probleme_U::nommer (const Nom &) inline override virtual
Donne un nom a l'Objet_U Methode virtuelle a surcharger.
Parameters
(const Nom&) le nom a affectuer a l'Objet_U
Reimplemented from Objet_U.
References nom_.
Referenced by Probleme_FTD_IJK_cut_cell::initialize(), and Pbc_MED::readOn().
le_nom()
const Nom & Probleme_U::le_nom () const inline override virtual
Donne le nom de l'Objet_U Methode a surcharger : renvoie "neant" dans cette implementation.
Returns
(Nom&) le nom de l'Objet_U
Reimplemented from Objet_U.
References nom_.
Referenced by Probleme_base_interface_proto::abortTimeStep_impl(), Ecrire_YAML::add_field(), Ecrire_YAML::add_scalar(), Probleme_Couple::ajouter(), Op_Diff_PolyMAC_Elem::ajouter_termes_croises(), Equation_base::associer_pb_base(), Loi_Fermeture_base::associer_pb_base(), IJK_Interfaces::associer_pb_base(), IJK_Thermals::associer_pb_base(), Navier_Stokes_FTD_IJK::associer_pb_base(), Transport_Interfaces_FT_Disc::associer_pb_base(), Probleme_base::associer_sch_tps_base(), Probleme_base::calculer_pas_de_temps(), Schema_Temps_IJK_base::check_stop_criteria(), Pb_Couple_Rayonnement::completer(), Champ_Gen_de_Champs_Gen::completer(), Champ_Generique_Correlation::completer(), Champ_Generique_Ecart_Type::completer(), Champ_Generique_Moyenne::completer(), Champ_Generique_Transformation::completer(), Fluide_Dilatable_base::completer_edo(), Probleme_base_interface_proto::computeTimeStep_impl(), Convection_Diffusion_Concentration::constituant(), Operateur_base::contribuer_termes_croises(), Op_Diff_PolyMAC_Elem::contribuer_termes_croises(), Op_Diff_VDF_Elem_base::contribuer_termes_croises(), Navier_Stokes_Aposteriori::creer_champ(), Navier_Stokes_std_ALE::data_a_sauvegarder(), Postraitement::data_a_sauvegarder(), Convection_Diffusion_Fluide_Dilatable_Proto::data_a_sauvegarder(), Operateur_base::dimensionner_termes_croises(), Op_Diff_PolyMAC_Elem::dimensionner_termes_croises(), Op_Diff_VDF_Elem_base::dimensionner_termes_croises(), Probleme_base::discretiser(), Probleme_Couple::discretiser(), Modele_rayo_semi_transp::discretiser(), Probleme_FTD_IJK_base::discretiser(), Pb_Fluide_base::expression_predefini(), Pb_Hydraulique_Melange_Binaire_Turbulent_QC::expression_predefini(), Pb_Thermohydraulique_Turbulent_QC::expression_predefini(), Equation_base::expression_residu(), Schema_Euler_Implicite::faire_un_pas_de_temps_eqn_base(), Schema_Implicite_Multi_TimeStep_base::faire_un_pas_de_temps_eqn_base(), Schema_Euler_Implicite::faire_un_pas_de_temps_pb_couple(), Probleme_base::finir(), Convection_Diffusion_Fluide_Dilatable_base::fluide(), Convection_Diffusion_Temperature_base::fluide(), Masse_Multiphase::fluide(), Probleme_base_interface_proto::futureTime_impl(), Probleme_base::get_champ(), Champ_Inc_base::get_PDI_dname(), getInputFieldTemplate(), getOutputField(), Navier_Stokes_std::impr(), Schema_Temps_base::impr(), Navier_Stokes_Fluide_Dilatable_Proto::impr_impl(), Couplage_U::indice_probleme(), Echange_contact_PolyMAC_P0::init_op(), Echange_contact_PolyMAC_P0P1NC::init_op(), Probleme_base_interface_proto::initialize_impl(), Probleme_base_interface_proto::initTimeStep_impl(), Discretiser::interpreter(), Resoudre::interpreter(), Schema_Temps_base::isStationary(), Probleme_base_interface_proto::isStationary_impl(), Schema_Euler_Implicite::iterateTimeStep(), Pb_Dilatable_base::iterateTimeStep(), Sch_CN_iteratif::iterateTimeStep(), Probleme_base_interface_proto::iterateTimeStep_impl(), SETS::iterer_eqn(), Simple::iterer_eqs(), Schema_Euler_Implicite::Iterer_Pb(), Postraitement::lire_champs_operateurs(), Postraitement::lire_motcle_non_standard(), Modele_turbulence_hyd_base::lire_motcle_non_standard(), Modele_turbulence_scal_base::lire_motcle_non_standard(), Probleme_base::mettre_a_jour(), Pb_Dilatable_base::mettre_a_jour(), Echange_contact_Correlation_VDF::mettre_a_jour(), PlaqThVDF::mettre_a_jour(), Echange_contact_Correlation_VEF::mettre_a_jour(), IJK_Thermals::milieu(), Navier_Stokes_FTD_IJK::milieu(), Equation_rayonnement_base::milieu(), Navier_Stokes_std::milieu(), Convection_Diffusion_Temperature_FT_Disc::milieu(), Transport_Interfaces_FT_Disc::milieu(), Terme_Source_Constituant::ouvrir_fichier(), Source_PDF_base::ouvrir_fichier(), Operateur_base::ouvrir_fichier(), Source_base::ouvrir_fichier(), Turbulence_paroi_base::ouvrir_fichier_partage(), Turbulence_paroi_scal_base::ouvrir_fichier_partage(), Probleme_base::postraiter(), Probleme_base_interface_proto::presentTime_impl(), Probleme_FTD_IJK_base::readOn(), Domaine_Cl_dis_base::readOn(), Probleme_base::readOn(), Probleme_Couple::readOn(), Champ_Fonc_reprise::readOn(), Probleme_base::reprendre(), Postraitement::reprendre(), Probleme_base_interface_proto::resetTimeWithDir_impl(), Navier_Stokes_std_ALE::sauvegarder(), Probleme_base::sauvegarder(), Postraitement::sauvegarder(), Convection_Diffusion_Fluide_Dilatable_Proto::Sauvegarder_WC(), Probleme_base::sauver(), Probleme_Couple::sauver(), Probleme_base::schema_temps(), Probleme_Couple::schema_temps(), Postraitement::set_expression_champ(), Operateur_base::set_fichier(), Source_base::set_fichier(), setInputDoubleValue(), setInputField(), Conduction::solide(), Probleme_base_interface_proto::solveTimeStep_impl(), Terme_Source_Canal_perio::source(), Schema_Temps_base::stop(), Probleme_base_interface_proto::terminate_impl(), Probleme_base_interface_proto::updateGivenFields_impl(), Probleme_base_interface_proto::validateTimeStep_impl(), and Postraitement::verifie_nom_et_sources().
Member Data Documentation
info_obj
const Type_info Probleme_U::info_obj static
nom_
Nom Probleme_U::nom_ protected
Referenced by le_nom(), and nommer().
reg_
ScalarRegister Probleme_U::reg_ protected
Referenced by getOutputIntValue(), and setInputIntValue().
str_params_
std::map<std::string, std::string> Probleme_U::str_params_ protected
Referenced by getOutputStringValue(), Couplage_U::resetTime(), Probleme_base::resetTime(), and setInputStringValue().