TrioCFD: Modele_Shih_Zhu_Lumley_VEF Class Reference
Modele_Shih_Zhu_Lumley_VEF Class Reference
#include <Modele_Shih_Zhu_Lumley_VEF.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Modele_Fonc_Realisable_base
const Type_info * get_info () const override
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Modele_Fonc_Realisable_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Modele_Shih_Zhu_Lumley_VEF()
Modele_Shih_Zhu_Lumley_VEF::Modele_Shih_Zhu_Lumley_VEF ()
~Modele_Shih_Zhu_Lumley_VEF()
Modele_Shih_Zhu_Lumley_VEF::~Modele_Shih_Zhu_Lumley_VEF ()
Member Function Documentation
cree_instance()
Objet_U * Modele_Shih_Zhu_Lumley_VEF::cree_instance () static
taille_memoire()
unsigned Modele_Shih_Zhu_Lumley_VEF::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Modele_Shih_Zhu_Lumley_VEF::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Modele_Shih_Zhu_Lumley_VEF::info () static
get_info()
const Type_info * Modele_Shih_Zhu_Lumley_VEF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
Modele_Shih_Zhu_Lumley_VEF & Modele_Shih_Zhu_Lumley_VEF::self_cast (Objet_U & r) static
self_cast() [2/2]
const Modele_Shih_Zhu_Lumley_VEF & Modele_Shih_Zhu_Lumley_VEF::self_cast (const Objet_U & r) static
printOn()
Sortie & Modele_Shih_Zhu_Lumley_VEF::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
readOn()
Entree & Modele_Shih_Zhu_Lumley_VEF::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
References Modele_Fonc_Realisable_base::is_Cmu_constant_, Param::lire_avec_accolades_depuis(), Objet_U::que_suis_je(), and set_param().
set_param()
void Modele_Shih_Zhu_Lumley_VEF::set_param (Param & param) virtual
References A0_, and Param::ajouter().
Referenced by readOn().
mettre_a_jour()
void Modele_Shih_Zhu_Lumley_VEF::mettre_a_jour (double temps) override virtual
Implements Modele_Fonc_Realisable_base.
Calcul_S()
void Modele_Shih_Zhu_Lumley_VEF::Calcul_S (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const DoubleTab & vitesse) override virtual
Implements Modele_Fonc_Realisable_base.
References calcul_tenseur_face(), Objet_U::dimension, init_tenseur_face(), nfaces_, Modele_Fonc_Realisable_base::S_, and S_elem_.
Calcul_C1()
void Modele_Shih_Zhu_Lumley_VEF::Calcul_C1 (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const DoubleTab & vitesse, const DoubleTab & K_Eps, const double EPS_MIN) override virtual
Implements Modele_Fonc_Realisable_base.
References Modele_Fonc_Realisable_base::C1_, nfaces_, and Modele_Fonc_Realisable_base::S_.
Referenced by Contributions_Sources(), and Contributions_Sources_Paroi().
Calcul_Cmu_et_S()
void Modele_Shih_Zhu_Lumley_VEF::Calcul_Cmu_et_S (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const DoubleTab & vitesse, const DoubleTab & K_Eps, const double EPS_MIN) override virtual
Implements Modele_Fonc_Realisable_base.
References A0_, calcul_tenseur_face(), Modele_Fonc_Realisable_base::Cmu_, Domaine_VF::creer_tableau_faces(), Objet_U::dimension, init_tenseur_face(), nfaces_, R_elem_, Modele_Fonc_Realisable_base::S_, and S_elem_.
Referenced by Contributions_Sources(), and Contributions_Sources_Paroi().
calcul_tenseur_face()
DoubleTab & Modele_Shih_Zhu_Lumley_VEF::calcul_tenseur_face (DoubleTab & Tenseur_face, const DoubleTab & Tenseur_elem, const Domaine_VEF & domaine_VEF, const Domaine_Cl_VEF & domaine_Cl_VEF) const virtual
References Objet_U::dimension, Domaine_VF::face_voisins(), Domaine_Cl_dis_base::les_conditions_limites(), Domaine_VF::nb_faces(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), Domaine_VF::premiere_face_int(), TRUST_Vector< _CLASSE_ >::size(), TRUST_Deriv< _CLASSE_ >::valeur(), and Domaine_VF::volumes().
Referenced by Calcul_Cmu_et_S(), Calcul_Cmu_et_S_BiK(), and Calcul_S().
Contributions_Sources()
void Modele_Shih_Zhu_Lumley_VEF::Contributions_Sources (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const DoubleTab & vitesse, const DoubleTab & K_Eps, const double EPS_MIN) override virtual
Implements Modele_Fonc_Realisable_base.
References Calcul_C1(), Calcul_Cmu_et_S(), and Calcul_Tenseurs_S_et_R_elem().
Contributions_Sources_Paroi()
void Modele_Shih_Zhu_Lumley_VEF::Contributions_Sources_Paroi (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const DoubleTab & vitesse, const DoubleTab & K_Eps, const double EPS_MIN, const DoubleTab & visco, const DoubleTab & visco_turb, const DoubleTab & loi_paroi, const int idt) override virtual
Implements Modele_Fonc_Realisable_base.
References Calcul_C1(), Calcul_Cmu_et_S(), and Calcul_Tenseurs_S_et_R_elem_Paroi().
Calcul_C1_BiK()
void Modele_Shih_Zhu_Lumley_VEF::Calcul_C1_BiK (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const DoubleTab & vitesse, const DoubleTab & K, const DoubleTab & Eps, const double EPS_MIN) override virtual
Implements Modele_Fonc_Realisable_base.
References Modele_Fonc_Realisable_base::C1_, nfaces_, and Modele_Fonc_Realisable_base::S_.
Referenced by Contributions_Sources_BiK(), and Contributions_Sources_Paroi_BiK().
Calcul_Cmu_et_S_BiK()
void Modele_Shih_Zhu_Lumley_VEF::Calcul_Cmu_et_S_BiK (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const DoubleTab & vitesse, const DoubleTab & K, const DoubleTab & Eps, const double EPS_MIN) override virtual
Implements Modele_Fonc_Realisable_base.
References A0_, calcul_tenseur_face(), Modele_Fonc_Realisable_base::Cmu_, Domaine_VF::creer_tableau_faces(), Objet_U::dimension, init_tenseur_face(), nfaces_, R_elem_, Modele_Fonc_Realisable_base::S_, and S_elem_.
Referenced by Contributions_Sources_BiK(), and Contributions_Sources_Paroi_BiK().
Contributions_Sources_BiK()
void Modele_Shih_Zhu_Lumley_VEF::Contributions_Sources_BiK (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const DoubleTab & vitesse, const DoubleTab & K, const DoubleTab & Eps, const double EPS_MIN) override virtual
Implements Modele_Fonc_Realisable_base.
References Calcul_C1_BiK(), Calcul_Cmu_et_S_BiK(), and Calcul_Tenseurs_S_et_R_elem().
Contributions_Sources_Paroi_BiK()
void Modele_Shih_Zhu_Lumley_VEF::Contributions_Sources_Paroi_BiK (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const DoubleTab & vitesse, const DoubleTab & K, const DoubleTab & Eps, const double EPS_MIN, const DoubleTab & visco_tab, const DoubleTab & visco_turb, const DoubleTab & tab_paroi, const int idt) override virtual
Implements Modele_Fonc_Realisable_base.
References Calcul_C1_BiK(), Calcul_Cmu_et_S_BiK(), and Calcul_Tenseurs_S_et_R_elem_Paroi().
associer()
void Modele_Shih_Zhu_Lumley_VEF::associer (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis) override virtual
Implements Modele_Fonc_Realisable_base.
References Initialisation(), le_dom_Cl_VEF, and le_dom_VEF.
init_tenseur_elem() [1/2]
void Modele_Shih_Zhu_Lumley_VEF::init_tenseur_elem (DoubleTab & Tenseur, const Domaine_VEF & domaine_VEF, const int ndim) const
References Domaine_32_64< _SIZE_ >::creer_tableau_elements(), Objet_U::dimension, Domaine_dis_base::domaine(), TRUSTVect< _TYPE_, _SIZE_ >::get_md_vector(), MD_Vector::non_nul(), and TRUSTTab< _TYPE_, _SIZE_ >::resize().
Referenced by Calcul_Tenseurs_S_et_R_elem(), Calcul_Tenseurs_S_et_R_elem_Paroi(), and Initialisation().
init_tenseur_face() [1/2]
void Modele_Shih_Zhu_Lumley_VEF::init_tenseur_face (DoubleTab & Tenseur, const Domaine_VEF & domaine_VEF, const int ndim) const
References Domaine_VF::creer_tableau_faces(), Objet_U::dimension, TRUSTVect< _TYPE_, _SIZE_ >::get_md_vector(), MD_Vector::non_nul(), and TRUSTTab< _TYPE_, _SIZE_ >::resize().
Referenced by Calcul_Cmu_et_S(), Calcul_Cmu_et_S_BiK(), and Calcul_S().
init_tenseur_elem() [2/2]
void Modele_Shih_Zhu_Lumley_VEF::init_tenseur_elem (DoubleTab & Tenseur, const Domaine_VEF & domaine_VEF, const int ndim)
References Domaine_32_64< _SIZE_ >::creer_tableau_elements(), Objet_U::dimension, Domaine_dis_base::domaine(), TRUSTVect< _TYPE_, _SIZE_ >::get_md_vector(), MD_Vector::non_nul(), and TRUSTTab< _TYPE_, _SIZE_ >::resize().
init_tenseur_face() [2/2]
void Modele_Shih_Zhu_Lumley_VEF::init_tenseur_face (DoubleTab & Tenseur, const Domaine_VEF & domaine_VEF, const int ndim)
References Domaine_VF::creer_tableau_faces(), Objet_U::dimension, TRUSTVect< _TYPE_, _SIZE_ >::get_md_vector(), MD_Vector::non_nul(), and TRUSTTab< _TYPE_, _SIZE_ >::resize().
Initialisation()
void Modele_Shih_Zhu_Lumley_VEF::Initialisation (const Domaine_dis_base & domaine_dis)
References Modele_Fonc_Realisable_base::C1_, Modele_Fonc_Realisable_base::Cmu_, init_tenseur_elem(), Domaine_VF::nb_faces(), nfaces_, R_elem_, TRUSTTab< _TYPE_, _SIZE_ >::resize_tab(), Modele_Fonc_Realisable_base::S_, and S_elem_.
Referenced by associer().
Calcul_Tenseurs_S_et_R_elem()
void Modele_Shih_Zhu_Lumley_VEF::Calcul_Tenseurs_S_et_R_elem (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const DoubleTab & vitesse)
References Champ_P1NC::calcul_gradient(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), init_tenseur_elem(), R_elem_, and S_elem_.
Referenced by Contributions_Sources(), and Contributions_Sources_BiK().
Calcul_Tenseurs_S_et_R_elem_Paroi()
void Modele_Shih_Zhu_Lumley_VEF::Calcul_Tenseurs_S_et_R_elem_Paroi (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const DoubleTab & vitesse, const DoubleTab & visco_tab, const DoubleTab & visco_turb, const DoubleTab & tab_paroi, const int idt)
References Champ_P1NC::calcul_duidxj_paroi(), Champ_P1NC::calcul_gradient(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), init_tenseur_elem(), R_elem_, and S_elem_.
Referenced by Contributions_Sources_Paroi(), and Contributions_Sources_Paroi_BiK().
Member Data Documentation
info_obj
const Type_info Modele_Shih_Zhu_Lumley_VEF::info_obj static
nfaces_
int Modele_Shih_Zhu_Lumley_VEF::nfaces_ protected
Referenced by Calcul_C1(), Calcul_C1_BiK(), Calcul_Cmu_et_S(), Calcul_Cmu_et_S_BiK(), Calcul_S(), and Initialisation().
S_elem_
DoubleTab Modele_Shih_Zhu_Lumley_VEF::S_elem_ protected
Referenced by Calcul_Cmu_et_S(), Calcul_Cmu_et_S_BiK(), Calcul_S(), Calcul_Tenseurs_S_et_R_elem(), Calcul_Tenseurs_S_et_R_elem_Paroi(), and Initialisation().
R_elem_
DoubleTab Modele_Shih_Zhu_Lumley_VEF::R_elem_ protected
Referenced by Calcul_Cmu_et_S(), Calcul_Cmu_et_S_BiK(), Calcul_Tenseurs_S_et_R_elem(), Calcul_Tenseurs_S_et_R_elem_Paroi(), and Initialisation().
le_dom_VEF
TRUST_Ref< Domaine_VEF *> Modele_Shih_Zhu_Lumley_VEF::le_dom_VEF protected
Referenced by associer().
le_dom_Cl_VEF
TRUST_Ref< Domaine_Cl_VEF *> Modele_Shih_Zhu_Lumley_VEF::le_dom_Cl_VEF protected
Referenced by associer().
A0_
double Modele_Shih_Zhu_Lumley_VEF::A0_ protected
Referenced by Calcul_Cmu_et_S(), Calcul_Cmu_et_S_BiK(), and set_param().