TrioCFD: Eval_Diff_VDF Class Reference
Eval_Diff_VDF Class Reference
#include <Eval_Diff_VDF.h>
Constructor & Destructor Documentation
~Eval_Diff_VDF()
virtual Eval_Diff_VDF::~Eval_Diff_VDF () inline virtual
Member Function Documentation
is_var()
const int & Eval_Diff_VDF::is_var () const inline
References is_var_.
diffusivite()
virtual const Champ_base & Eval_Diff_VDF::diffusivite () const inline final virtual
References get_diffusivite().
get_diffusivite()
virtual const Champ_base & Eval_Diff_VDF::get_diffusivite () const inline final virtual
References TRUST_Ref< _CLASSE_ >::non_nul(), ref_diffusivite_, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Op_Diff_VDF_base::ajoute_terme_pour_axi(), Op_Dift_VDF_base::ajoute_terme_pour_axi_turb(), and diffusivite().
associer_pb()
virtual void Eval_Diff_VDF::associer_pb (const Probleme_base & pb) inline final virtual
References ref_probleme_, and update_diffusivite().
Referenced by Op_Diff_K_Eps_Bas_Re_VDF_var_Elem::completer().
update_diffusivite()
virtual void Eval_Diff_VDF::update_diffusivite () inline final virtual
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), is_var_, TRUSTTab< _TYPE_, _SIZE_ >::ref(), ref_diffusivite_, ref_probleme_, tab_alpha_, tab_diffusivite_, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by associer_pb(), and mettre_a_jour().
associer()
virtual void Eval_Diff_VDF::associer (const Champ_base & diffu) inline virtual
Reimplemented in Eval_Diff_VDF_Elem_aniso.
References is_var_, and ref_diffusivite_.
Referenced by Eval_Diff_VDF_Elem_aniso::associer().
mettre_a_jour()
virtual void Eval_Diff_VDF::mettre_a_jour () inline virtual
Reimplemented in Eval_Diff_K_Eps_Bas_Re_VDF_var, Eval_Diff_VDF_Multi_inco_Elem_Axi, Eval_Diff_VDF_Multi_inco_Elem, Eval_Diff_VDF_Multi_inco_Multi_scalar_Elem, Eval_Dift_Multiphase_VDF, Eval_Dift_VDF, Eval_Dift_VDF_Multi_inco_Elem_Axi, Eval_Dift_VDF_Multi_inco_Elem, and Eval_Dift_VDF_Face.
References ref_diffusivite_, and update_diffusivite().
Referenced by Eval_Dift_Multiphase_VDF::mettre_a_jour(), and Eval_Dift_VDF::mettre_a_jour().
compute_heq_impl()
double Eval_Diff_VDF::compute_heq_impl (double d0, int i, double d1, int j, int compo) const inline
References is_var_, and tab_diffusivite_.
Referenced by Eval_Dift_VDF::compute_heq_impl().
nu_1_impl()
double Eval_Diff_VDF::nu_1_impl (int i, int compo) const inline
References is_var_, and tab_diffusivite_.
Referenced by Eval_Dift_VDF::nu_1_impl().
nu_2_impl()
double Eval_Diff_VDF::nu_2_impl (int i, int compo) const inline
References is_var_, and tab_diffusivite_.
Referenced by T_paroi_Champ_P0_VDF::me_calculer(), and Eval_Dift_VDF::nu_2_impl().
nu_1_impl_face()
double Eval_Diff_VDF::nu_1_impl_face (int i, int j, int compo) const inline
References is_var_, and tab_diffusivite_.
Referenced by nu_lam_impl_face2(), and Eval_Dift_VDF::nu_lam_impl_face2().
nu_2_impl_face()
double Eval_Diff_VDF::nu_2_impl_face (int i, int j, int k, int l, int compo) const inline
References is_var_, and tab_diffusivite_.
Referenced by nu_lam_impl_face(), and Eval_Dift_VDF::nu_lam_impl_face().
nu_lam_impl_face()
double Eval_Diff_VDF::nu_lam_impl_face (int i, int j, int k, int l, int compo) const inline
References nu_2_impl_face().
nu_lam_impl_face2()
double Eval_Diff_VDF::nu_lam_impl_face2 (int i, int j, int compo) const inline
References nu_1_impl_face().
get_ind_Fluctu_Term()
int Eval_Diff_VDF::get_ind_Fluctu_Term () const inline
get_dv_mvol()
double Eval_Diff_VDF::get_dv_mvol (const int i) const inline
get_equivalent_distance()
virtual double Eval_Diff_VDF::get_equivalent_distance (int boundary_index, int local_face) const inline virtual
Reimplemented in Eval_Dift_VDF.
nu_t_impl()
double Eval_Diff_VDF::nu_t_impl (int i, int compo) const inline
tau_tan_impl()
double Eval_Diff_VDF::tau_tan_impl (int i, int j) const inline
uses_wall()
bool Eval_Diff_VDF::uses_wall () const inline
uses_mod()
bool Eval_Diff_VDF::uses_mod () const inline
get_k_elem()
const DoubleTab & Eval_Diff_VDF::get_k_elem () const inline
Member Data Documentation
is_var_
int Eval_Diff_VDF::is_var_ = 0 protected
Referenced by associer(), compute_heq_impl(), is_var(), nu_1_impl(), nu_1_impl_face(), nu_2_impl(), nu_2_impl_face(), and update_diffusivite().
ref_probleme_
TRUST_Ref< Probleme_base *> Eval_Diff_VDF::ref_probleme_ protected
Referenced by associer_pb(), update_diffusivite(), and Eval_Dift_Multiphase_VDF::update_diffusivite_turbulente().
ref_diffusivite_
TRUST_Ref< Champ_base *> Eval_Diff_VDF::ref_diffusivite_ protected
Referenced by associer(), get_diffusivite(), mettre_a_jour(), and update_diffusivite().
tab_diffusivite_
DoubleTab Eval_Diff_VDF::tab_diffusivite_ protected
Referenced by compute_heq_impl(), Eval_Diff_K_Eps_Bas_Re_VDF_var::nu_1_impl(), nu_1_impl(), nu_1_impl_face(), nu_2_impl(), nu_2_impl_face(), and update_diffusivite().
tab_alpha_
DoubleTab Eval_Diff_VDF::tab_alpha_ protected
Referenced by update_diffusivite(), and Eval_Dift_Multiphase_VDF::update_diffusivite_turbulente().