TrioCFD: Parallel_io_parameters Class Reference
Parallel_io_parameters Class Reference
#include <Parallel_io_parameters.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Interprete
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Interprete
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Interprete
static Objet_U & objet (const Nom &)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Parallel_io_parameters()
Parallel_io_parameters::Parallel_io_parameters ()
~Parallel_io_parameters()
Parallel_io_parameters::~Parallel_io_parameters ()
Member Function Documentation
cree_instance()
Objet_U * Parallel_io_parameters::cree_instance () static
taille_memoire()
unsigned Parallel_io_parameters::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Parallel_io_parameters::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Parallel_io_parameters::info () static
get_info()
const Type_info * Parallel_io_parameters::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
Parallel_io_parameters & Parallel_io_parameters::self_cast (Objet_U & r) static
self_cast() [2/2]
const Parallel_io_parameters & Parallel_io_parameters::self_cast (const Objet_U & r) static
printOn()
Sortie & Parallel_io_parameters::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
References Objet_U::printOn().
readOn()
Entree & Parallel_io_parameters::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
interpreter()
Entree & Parallel_io_parameters::interpreter (Entree & is) override virtual
Implements Interprete.
References Param::ajouter(), Process::exit(), get_nb_writing_processes(), Param::lire_avec_accolades(), max_block_size_, nb_writing_processes_, Objet_U::que_suis_je(), run_bench_read(), and run_bench_write().
get_max_block_size()
static Size_t Parallel_io_parameters::get_max_block_size () inline static
References max_block_size_.
get_nb_writing_processes()
int Parallel_io_parameters::get_nb_writing_processes () static
References nb_writing_processes_, and Process::nproc().
Referenced by interpreter().
run_bench_read()
void Parallel_io_parameters::run_bench_read (const Nom & ijk_splitting) static protected
References IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::allocate(), Statistiques::begin_count(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::data(), Statistiques::end_count(), Domaine_IJK::FACES_I, Domaine_IJK::FACES_J, Domaine_IJK::FACES_K, Domaine_IJK::get_nb_elem_tot(), Statistiques::last_time(), Domaine_base::le_nom(), Statistiques::new_counter(), Interprete_bloc::objet_global(), and Statistiques::set_three_first_steps_elapsed().
Referenced by interpreter().
run_bench_write()
void Parallel_io_parameters::run_bench_write (const Nom & ijk_splitting) static protected
References IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::allocate(), Statistiques::begin_count(), Statistiques::end_count(), Domaine_IJK::FACES_I, Domaine_IJK::FACES_J, Domaine_IJK::FACES_K, Domaine_IJK::get_nb_elem_tot(), Statistiques::last_time(), Statistiques::new_counter(), Interprete_bloc::objet_global(), and Statistiques::set_three_first_steps_elapsed().
Referenced by interpreter().
Member Data Documentation
info_obj
const Type_info Parallel_io_parameters::info_obj static
max_block_size_
Size_t Parallel_io_parameters::max_block_size_ = (Size_t) 0 static protected
Referenced by get_max_block_size(), and interpreter().
nb_writing_processes_
int Parallel_io_parameters::nb_writing_processes_ = 0 static protected
Referenced by get_nb_writing_processes(), and interpreter().