TrioCFD: Navier_Stokes_Fluide_Dilatable_base Class Reference
Navier_Stokes_Fluide_Dilatable_base Class Reference
#include <Navier_Stokes_Fluide_Dilatable_base.h>
Public Member Functions
void completer () override
DoubleTab & derivee_en_temps_inco (DoubleTab &) override
void discretiser () override
const Type_info * get_info () const override
int impr (Sortie &os) const override
bool initTimeStep (double dt) override
int lire_motcle_non_standard (const Motcle &mot, Entree &is) override
void mettre_a_jour (double temps) override
int preparer_calcul () override
Public Member Functions inherited from Navier_Stokes_std
void abortTimeStep () override
void associer_milieu_base (const Milieu_base &) override
void associer_pb_base (const Probleme_base &) override
virtual void calculer_la_pression_en_pa ()
void completer () override
DoubleTab & derivee_en_temps_inco (DoubleTab &) override
const Motcle & domaine_application () const override
Fluide_base & fluide ()
const Fluide_base & fluide () const
const Type_info * get_info () const override
int impr (Sortie &os) const override
const Champ_Inc_base & inconnue () const override
Champ_Inc_base & inconnue () override
bool initTimeStep (double dt) override
Entree & lire_cond_init (Entree &) override
int lire_motcle_non_standard (const Motcle &, Entree &) override
void mettre_a_jour (double temps) override
const Milieu_base & milieu () const override
Milieu_base & milieu () override
int nombre_d_operateurs () const override
const Operateur & operateur (int) const override
Operateur & operateur (int) override
Operateur_Div & operateur_divergence ()
const Operateur_Div & operateur_divergence () const
Operateur_Grad & operateur_gradient ()
const Operateur_Grad & operateur_gradient () const
int preparer_calcul () override
virtual void projeter ()
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
SolveurSys & solveur_pression ()
int verif_Cl () const override
Public Member Functions inherited from Equation_base
virtual void abortTimeStep ()
virtual void associer_domaine_dis (const Domaine_dis_base &)
virtual void associer_pb_base (const Probleme_base &)
virtual void associer_sch_tps_base (const Schema_Temps_base &)
virtual double calculer_pas_de_temps () const
virtual void completer ()
virtual std::vector< YAML_data > data_a_sauvegarder () const
DoubleTab & derivee_en_temps_conv (DoubleTab &, const DoubleTab &)
virtual DoubleTab & derivee_en_temps_inco (DoubleTab &)
const Discretisation_base & discretisation () const
virtual void discretiser ()
virtual const Motcle & domaine_application () const
virtual Domaine_Cl_dis_base & domaine_Cl_dis ()
virtual const Domaine_Cl_dis_base & domaine_Cl_dis () const
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual void imprimer (Sortie &os) const
virtual bool initTimeStep (double dt)
const Nom & le_nom () const override
int limpr () const
virtual void mettre_a_jour (double temps)
virtual int preparer_calcul ()
Probleme_base & probleme ()
const Probleme_base & probleme () const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Schema_Temps_base & schema_temps ()
const Schema_Temps_base & schema_temps () const
Solveur_Masse_base & solv_masse ()
const Solveur_Masse_base & solv_masse () const
Sources & sources ()
const Sources & sources () const
virtual void valider_iteration ()
virtual void verifie_ch_init_nb_comp (const Champ_Inc_base &ch_ref, const int nb_comp) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Navier_Stokes_Fluide_Dilatable_Proto
DoubleTab & derivee_en_temps_inco_impl (Navier_Stokes_std &, DoubleTab &res)
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Navier_Stokes_std
virtual void discretiser_assembleur_pression ()
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Equation_base
virtual Entree & lire_cl (Entree &)
virtual Entree & lire_cond_init (Entree &)
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual Entree & lire_sources (Entree &)
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
virtual int verif_Cl () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
pour un fluide sans modelisation de la turbulence. On suppose l'hypothese de fluide dilatable. Sous ces hypotheses, on utilise la forme suivante des equations de Navier_Stokes: DU/dt = div(terme visqueux) - gradP/rho + sources/rho div U = W avec DU/dt : derivee particulaire de la vitesse rho : masse volumique Rq : l'implementation de la classe permet bien sur de negliger certains termes de l'equation (le terme visqueux, le terme convectif, tel ou tel terme source). L'inconnue est le champ de vitesse.
See also
Navier_Stokes_std
Constructor & Destructor Documentation
Navier_Stokes_Fluide_Dilatable_base()
Navier_Stokes_Fluide_Dilatable_base::Navier_Stokes_Fluide_Dilatable_base ()
~Navier_Stokes_Fluide_Dilatable_base()
Navier_Stokes_Fluide_Dilatable_base::~Navier_Stokes_Fluide_Dilatable_base () override
Member Function Documentation
info()
const Type_info * Navier_Stokes_Fluide_Dilatable_base::info () static
get_info()
const Type_info * Navier_Stokes_Fluide_Dilatable_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Equation_base.
Reimplemented in Navier_Stokes_QC, and Navier_Stokes_WC.
self_cast() [1/2]
Navier_Stokes_Fluide_Dilatable_base & Navier_Stokes_Fluide_Dilatable_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Navier_Stokes_Fluide_Dilatable_base & Navier_Stokes_Fluide_Dilatable_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Navier_Stokes_Fluide_Dilatable_base::printOn (Sortie & os) const override protected virtual
Surcharge Objet_U::printOn Imprime l'equation et ses composants sur un flot de sortie.
Imprime le nom de l'equation, le solveur masse, les termes sources les conditions aux limites discretisees, les inconnues et les operateurs.
Parameters
(Sortie& os) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Equation_base.
Reimplemented in Navier_Stokes_QC, and Navier_Stokes_WC.
References Navier_Stokes_std::printOn().
Referenced by Navier_Stokes_QC::printOn(), and Navier_Stokes_WC::printOn().
readOn()
Entree & Navier_Stokes_Fluide_Dilatable_base::readOn (Entree & is) override protected virtual
Lecture d'une equation sur un flot d'entree.
Le format est le suivant: { [Source { [sou_1], [sour_2], ...} ] Conditions_limites { [cl_1] [cl_2] ... } Conditions_initiales { [cl_init] } }
Parameters
(Entree& is) un flot d'entree pour lire l'equation
Returns
(Entree&) le flot d'entree modifie
Exceptions
mauvais format de lecture, accolade ouvrante attendue
pas de conditions initiales, il faut initialiser l'inconnue
pas de conditions aux limites, il faut donner des conditions aux limites
Reimplemented from Equation_base.
Reimplemented in Navier_Stokes_QC, and Navier_Stokes_WC.
References Navier_Stokes_std::divergence, Navier_Stokes_std::readOn(), and Operateur::set_description().
Referenced by Navier_Stokes_QC::readOn(), and Navier_Stokes_WC::readOn().
lire_motcle_non_standard()
int Navier_Stokes_Fluide_Dilatable_base::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Equation_base.
References Source_Masse_Fluide_Dilatable_base::associer_domaine_cl(), Equation_base::discretisation(), Equation_base::domaine_Cl_dis(), Navier_Stokes_std::lire_motcle_non_standard(), Objet_U::que_suis_je(), source_masse_, Objet_U_ptr::typer(), and TRUST_Deriv< _CLASSE_ >::valeur().
preparer_calcul()
int Navier_Stokes_Fluide_Dilatable_base::preparer_calcul () override virtual
Appel Equation_base::preparer_calcul() Assemblage du solveur pression et.
initialisation de la pression.
Returns
(int) renvoie toujours 1
Reimplemented from Equation_base.
References Navier_Stokes_std::preparer_calcul().
set_param()
void Navier_Stokes_Fluide_Dilatable_base::set_param (Param & param) override virtual
Reimplemented from Equation_base.
References Param::ajouter_non_std(), and Navier_Stokes_std::set_param().
discretiser()
void Navier_Stokes_Fluide_Dilatable_base::discretiser () override virtual
Discretise l'equation.
Type le domaine_Cl_dis, la formatte, l'associe a l'equation. Type le solveur masse, lui associe le domaine discretisee et le domaine des conditions aux limites discretisees.
Reimplemented from Equation_base.
References Equation_base::discretisation(), Navier_Stokes_std::discretiser(), Equation_base::domaine_dis(), Field_base::nommer(), Navier_Stokes_Fluide_Dilatable_Proto::rho_la_vitesse_, Equation_base::schema_temps(), and Discret_Thyd::vitesse().
diffusivite_pour_transport()
const Champ_Don_base & Navier_Stokes_Fluide_Dilatable_base::diffusivite_pour_transport () const override virtual
Reimplemented from Navier_Stokes_std.
References Navier_Stokes_std::le_fluide.
diffusivite_pour_pas_de_temps()
const Champ_base & Navier_Stokes_Fluide_Dilatable_base::diffusivite_pour_pas_de_temps () const override virtual
Reimplemented from Navier_Stokes_std.
References Navier_Stokes_std::le_fluide.
vitesse_pour_transport()
const Champ_base & Navier_Stokes_Fluide_Dilatable_base::vitesse_pour_transport () const override virtual
Reimplemented from Navier_Stokes_std.
References Navier_Stokes_std::la_vitesse.
derivee_en_temps_inco()
DoubleTab & Navier_Stokes_Fluide_Dilatable_base::derivee_en_temps_inco (DoubleTab & derivee) override virtual
Returns the time derivative of the unknown I of the equation: dI/dt = M-1*(sum(operators(I) + sources))
In : derivee contains I (but immediatly set to 0) Out: derivee contains dI/dt
Reimplemented from Equation_base.
References Navier_Stokes_Fluide_Dilatable_Proto::derivee_en_temps_inco_impl().
get_champ()
const Champ_base & Navier_Stokes_Fluide_Dilatable_base::get_champ (const Motcle & nom) const override virtual
Reimplemented from Equation_base.
References Nom::getString(), has_champ(), Navier_Stokes_std::has_champ(), Navier_Stokes_std::milieu(), and rho_la_vitesse().
has_champ() [1/2]
bool Navier_Stokes_Fluide_Dilatable_base::has_champ (const Motcle & nom, TRUST_Ref< Champ_base * > & ref_champ) const override virtual
Reimplemented from Equation_base.
References has_champ(), Navier_Stokes_std::has_champ(), Navier_Stokes_std::milieu(), and rho_la_vitesse().
Referenced by get_champ(), and has_champ().
has_champ() [2/2]
bool Navier_Stokes_Fluide_Dilatable_base::has_champ (const Motcle & nom) const override virtual
Reimplemented from Equation_base.
References has_champ(), Navier_Stokes_std::has_champ(), and Navier_Stokes_std::milieu().
completer()
void Navier_Stokes_Fluide_Dilatable_base::completer () override virtual
Complete l'equation base, associe la pression a l'equation,.
complete la divergence, le gradient et le solveur pression. Ajout de 2 termes sources: l'un representant la force centrifuge dans le cas axi-symetrique,l'autre intervenant dans la resolution en 2D axisymetrique
Reimplemented from Equation_base.
Reimplemented in Navier_Stokes_QC, and Navier_Stokes_WC.
References Source_Masse_Fluide_Dilatable_base::completer(), Navier_Stokes_std::completer(), MorEqn::equation(), Process::exit(), has_source_masse(), Navier_Stokes_std::inconnue(), Navier_Stokes_std::le_fluide, Field_base::le_nom(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Fluide_Dilatable_base::loi_etat(), Loi_Etat_Multi_GP_WC::masse_molaire_especes(), Source_Masse_Fluide_Dilatable_base::nb_comp(), Equation_base::probleme(), Objet_U::que_suis_je(), source_masse_, TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), and Champ_Don_base::valeurs().
Referenced by Navier_Stokes_QC::completer(), and Navier_Stokes_WC::completer().
assembler()
void Navier_Stokes_Fluide_Dilatable_base::assembler (Matrice_Morse & mat_morse, const DoubleTab & present, DoubleTab & secmem) override virtual
Reimplemented from Equation_base.
References Navier_Stokes_Fluide_Dilatable_Proto::assembler_impl().
assembler_avec_inertie()
void Navier_Stokes_Fluide_Dilatable_base::assembler_avec_inertie (Matrice_Morse & mat_morse, const DoubleTab & present, DoubleTab & secmem) override virtual
Reimplemented from Equation_base.
References Navier_Stokes_Fluide_Dilatable_Proto::assembler_avec_inertie_impl().
assembler_blocs_avec_inertie()
void Navier_Stokes_Fluide_Dilatable_base::assembler_blocs_avec_inertie (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl) override virtual
Reimplemented from Equation_base.
References Navier_Stokes_Fluide_Dilatable_Proto::assembler_blocs_avec_inertie().
impr()
int Navier_Stokes_Fluide_Dilatable_base::impr (Sortie & os) const override virtual
Imprime les operateurs de l'equation sur un flot de sortie, de facon inconditionnelle.
appelle Operateur_base::impr(os)
Parameters
(Sortie& os) le flot de sortie
Returns
(int) renvoie toujours 1
Reimplemented from Equation_base.
Reimplemented in Navier_Stokes_QC, and Navier_Stokes_WC.
References Navier_Stokes_std::impr(), and Navier_Stokes_Fluide_Dilatable_Proto::impr_impl().
Referenced by Navier_Stokes_QC::impr(), and Navier_Stokes_WC::impr().
initTimeStep()
bool Navier_Stokes_Fluide_Dilatable_base::initTimeStep (double dt) override virtual
Allocation et initialisation de l'inconnue et des CLs jusqu'a present+dt.
autres initialisations pour les calculs sur le prochain pas de temps : operateurs, solveur_masse->
Returns
(0 en cas d'erreur, 1 sinon)
Reimplemented from Equation_base.
References Source_Masse_Fluide_Dilatable_base::changer_temps_futur(), has_source_masse(), Navier_Stokes_std::inconnue(), Navier_Stokes_std::initTimeStep(), Navier_Stokes_std::le_fluide, Schema_Temps_base::nb_valeurs_futures(), Fluide_Dilatable_base::rho_discvit(), Navier_Stokes_Fluide_Dilatable_Proto::rho_la_vitesse_, Navier_Stokes_Fluide_Dilatable_Proto::rho_vitesse_impl(), Equation_base::schema_temps(), Source_Masse_Fluide_Dilatable_base::set_temps_defaut(), source_masse_, Schema_Temps_base::temps_courant(), Schema_Temps_base::temps_defaut(), Schema_Temps_base::temps_futur(), TRUST_Ref< _CLASSE_ >::valeur(), and Champ_Inc_base::valeurs().
mettre_a_jour()
void Navier_Stokes_Fluide_Dilatable_base::mettre_a_jour (double temps) inline override virtual
La valeur de l'inconnue sur le pas de temps a ete calculee.
Cette methode avance le present jusqu'au temps passe en parametre. Elle met aussi a jour les proprietes du milieu.
Parameters
(double temps) le pas de temps de mise a jour
Reimplemented from Equation_base.
References Source_Masse_Fluide_Dilatable_base::mettre_a_jour(), Navier_Stokes_std::mettre_a_jour(), Objet_U_ptr::non_nul(), and source_masse_.
rho_la_vitesse()
const Champ_Inc_base & Navier_Stokes_Fluide_Dilatable_base::rho_la_vitesse () const inline override virtual
Reimplemented from Navier_Stokes_std.
References Navier_Stokes_Fluide_Dilatable_Proto::rho_la_vitesse_.
Referenced by get_champ(), and has_champ().
has_source_masse()
bool Navier_Stokes_Fluide_Dilatable_base::has_source_masse () const inline
References Objet_U_ptr::non_nul(), and source_masse_.
Referenced by completer(), and initTimeStep().
source_masse()
const Source_Masse_Fluide_Dilatable_base & Navier_Stokes_Fluide_Dilatable_base::source_masse () const inline
References Objet_U_ptr::non_nul(), source_masse_, and TRUST_Deriv< _CLASSE_ >::valeur().
Member Data Documentation
info_obj
const Type_info Navier_Stokes_Fluide_Dilatable_base::info_obj static
source_masse_
TRUST_Deriv< Source_Masse_Fluide_Dilatable_base > Navier_Stokes_Fluide_Dilatable_base::source_masse_ protected
Referenced by completer(), has_source_masse(), initTimeStep(), lire_motcle_non_standard(), mettre_a_jour(), and source_masse().