TrioCFD: Corrige_flux_FT_temperature_conv Class Reference
Corrige_flux_FT_temperature_conv Class Reference
#include <Corrige_flux_FT_temperature_conv.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Corrige_flux_FT_temperature_conv()
Corrige_flux_FT_temperature_conv::Corrige_flux_FT_temperature_conv ()
~Corrige_flux_FT_temperature_conv()
Corrige_flux_FT_temperature_conv::~Corrige_flux_FT_temperature_conv ()
Member Function Documentation
cree_instance()
Objet_U * Corrige_flux_FT_temperature_conv::cree_instance () static
taille_memoire()
unsigned Corrige_flux_FT_temperature_conv::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Corrige_flux_FT_temperature_conv::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Corrige_flux_FT_temperature_conv::info () static
get_info()
const Type_info * Corrige_flux_FT_temperature_conv::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Corrige_flux_FT_base.
self_cast() [1/2]
Corrige_flux_FT_temperature_conv & Corrige_flux_FT_temperature_conv::self_cast (Objet_U & r) static
self_cast() [2/2]
const Corrige_flux_FT_temperature_conv & Corrige_flux_FT_temperature_conv::self_cast (const Objet_U & r) static
printOn()
Sortie & Corrige_flux_FT_temperature_conv::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Corrige_flux_FT_base.
References Corrige_flux_FT_base::printOn().
readOn()
Entree & Corrige_flux_FT_temperature_conv::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Corrige_flux_FT_base.
References Corrige_flux_FT_base::readOn().
initialize()
void Corrige_flux_FT_temperature_conv::initialize (const Domaine_IJK & splitting, const IJK_Field_double & field, const IJK_Interfaces & interfaces, const Probleme_FTD_IJK_base & ijk_ft, Intersection_Interface_ijk_face & intersection_ijk_face, Intersection_Interface_ijk_cell & intersection_ijk_cell) override virtual
Reimplemented from Corrige_flux_FT_base.
References Corrige_flux_FT_base::initialize(), IJK_MonofluidVar::initialize(), Corrige_flux_FT_base::intersection_ijk_cell_, Corrige_flux_FT_base::intersection_ijk_face_, lda_, Corrige_flux_FT_base::lda_l_, Corrige_flux_FT_base::lda_v_, Intersection_Interface_ijk::n(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::resize(), rho_cp_, Corrige_flux_FT_base::rhocp_l_, Corrige_flux_FT_base::rhocp_v_, temp_interface_cell_, temp_interface_face_, temperature_barys_, and temperature_ghost_.
corrige_flux_faceIJ()
void Corrige_flux_FT_temperature_conv::corrige_flux_faceIJ (IJK_Field_local_double *const flux, const int k_layer, const int dir) override virtual
Implements Corrige_flux_FT_base.
References ParcoursIJKDir::calculer_surface_face(), Corrige_flux_FT_base::domaine_, Corrige_flux_FT_base::field_, Corrige_flux_FT_base::interfaces_, multiplie_par_rho_cp_de_la_face_monophasique(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), Corrige_flux_FT_base::parcours_, ParcoursIJKDir::set_dir(), ParcoursIJKDir::set_elem(), and TRUST_Ref< _CLASSE_ >::valeur().
update()
void Corrige_flux_FT_temperature_conv::update () override virtual
Implements Corrige_flux_FT_base.
References calcul_temp_flux_interf_pour_bary_cell(), calcul_temp_flux_interf_pour_bary_face(), interp_back_to_bary_faces(), Corrige_flux_FT_base::intersection_ijk_cell_, Corrige_flux_FT_base::intersection_ijk_face_, Intersection_Interface_ijk_face::maj_interpolation_coo_on_interfaces(), Intersection_Interface_ijk::n(), TRUSTArray< _TYPE_, _SIZE_ >::resize(), Intersection_Interface_ijk_cell::update_interpolations_cell_centres_on_interface(), and update_temperature_ghost().
calcul_temperature_flux_interface()
void Corrige_flux_FT_temperature_conv::calcul_temperature_flux_interface (const IJK_Field_double & temperature, const double ldal, const double ldav, const double dist, const DoubleTab & positions, const DoubleTab & normale, ArrOfDouble & temperature_interp, ArrOfDouble & flux_normal_interp, ArrOfDouble & temp_liqu, ArrOfDouble & temp_vap, DoubleTab & coo_liqu, DoubleTab & coo_vap) const override virtual
Implements Corrige_flux_FT_base.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Intersection_Interface_ijk::get_position_interpolation_normal_interf(), TRUSTArray< _TYPE_, _SIZE_ >::resize(), and TRUSTArray< _TYPE_, _SIZE_ >::resize_array().
Referenced by calcul_temp_flux_interf_pour_bary_cell(), and calcul_temp_flux_interf_pour_bary_face().
calcul_temp_flux_interf_pour_bary_face()
void Corrige_flux_FT_temperature_conv::calcul_temp_flux_interf_pour_bary_face (ArrOfDouble & temp_vap, ArrOfDouble & temp_liqu) protected
References calcul_temperature_flux_interface(), Corrige_flux_FT_base::domaine_, Corrige_flux_FT_base::field_, Corrige_flux_FT_base::intersection_ijk_face_, Corrige_flux_FT_base::lda_l_, Corrige_flux_FT_base::lda_v_, Intersection_Interface_ijk::norm_interf(), Intersection_Interface_ijk::pos_interf(), q_interface_face_, and temp_interface_face_.
Referenced by update().
calcul_temp_flux_interf_pour_bary_cell()
void Corrige_flux_FT_temperature_conv::calcul_temp_flux_interf_pour_bary_cell (ArrOfDouble & temp_vap, ArrOfDouble & temp_liqu) protected
References calcul_temperature_flux_interface(), Corrige_flux_FT_base::domaine_, Corrige_flux_FT_base::field_, Corrige_flux_FT_base::intersection_ijk_cell_, Corrige_flux_FT_base::lda_l_, Corrige_flux_FT_base::lda_v_, Intersection_Interface_ijk::norm_interf(), Intersection_Interface_ijk::pos_interf(), q_interface_cell_, and temp_interface_cell_.
Referenced by update().
interp_back_to_bary_faces()
void Corrige_flux_FT_temperature_conv::interp_back_to_bary_faces (const ArrOfDouble & temp_vap, const ArrOfDouble & temp_liqu) protected
References Intersection_Interface_ijk::dist_interf(), Corrige_flux_FT_base::domaine_, Corrige_flux_FT_base::intersection_ijk_face_, Intersection_Interface_ijk::n(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), temp_interface_face_, and temperature_barys_.
Referenced by update().
update_temperature_ghost()
void Corrige_flux_FT_temperature_conv::update_temperature_ghost (const ArrOfDouble & temp_vap, const ArrOfDouble & temp_liqu) protected
References Intersection_Interface_ijk::dist_interf(), Corrige_flux_FT_base::intersection_ijk_cell_, Corrige_flux_FT_base::lda_l_, Corrige_flux_FT_base::lda_v_, Intersection_Interface_ijk::n(), q_interface_cell_, TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), temp_interface_cell_, and temperature_ghost_.
Referenced by update().
multiplie_par_rho_cp_de_la_face_monophasique()
void Corrige_flux_FT_temperature_conv::multiplie_par_rho_cp_de_la_face_monophasique (const double frac_liquide, IJK_Field_local_double *const flux) const protected
References ParcoursIJKDir::elem(), Corrige_flux_FT_base::parcours_, and rho_cp_.
Referenced by corrige_flux_faceIJ().
remplace_flux_par_quick_ghost_amont_1()
void Corrige_flux_FT_temperature_conv::remplace_flux_par_quick_ghost_amont_1 (const double frac_liquide, const double s_face, IJK_Field_local_double *const flux) const protected
References ParcoursIJKDir::elem(), extrapolation_amont_1_depuis_l_interface(), ParcoursIJKDir::face(), interpolation_quick_avec_1_ghost(), is_flux_upwind_from_interface(), Corrige_flux_FT_base::parcours_, Corrige_flux_FT_base::ref_ijk_ft_, and rho_cp_.
remplace_flux_par_somme_rhocpf_Tf_v_Sf()
void Corrige_flux_FT_temperature_conv::remplace_flux_par_somme_rhocpf_Tf_v_Sf (const double frac_liquide, const double s_face, IJK_Field_local_double *const flux) const protected
References ParcoursIJKDir::face(), ParcoursIJKDir::i(), ParcoursIJKDir::j(), ParcoursIJKDir::k(), Corrige_flux_FT_base::parcours_, Corrige_flux_FT_base::ref_ijk_ft_, Corrige_flux_FT_base::rhocp_l_, Corrige_flux_FT_base::rhocp_v_, and temperature_barys_.
quick()
double Corrige_flux_FT_temperature_conv::quick (const double Tim1, const double Ti, const double Tip1, const double Tip2, const double velocity) const protected
Referenced by interpolation_quick_avec_1_ghost().
get_ghost_temp_if_cell_is_diph()
const double & Corrige_flux_FT_temperature_conv::get_ghost_temp_if_cell_is_diph (const FixedVector< int, 3 > & elem, const bool from_liqu_phase) const protected
References Corrige_flux_FT_base::field_, Corrige_flux_FT_base::ref_ijk_ft_, and temperature_ghost_.
Referenced by interpolation_quick_avec_1_ghost().
extrapolation_amont_1_depuis_l_interface()
double Corrige_flux_FT_temperature_conv::extrapolation_amont_1_depuis_l_interface (const double frac_liquide, const double decal) const protected
References Corrige_flux_FT_base::domaine_, ParcoursIJKDir::elem(), ParcoursIJKDir::face(), ParcoursIJKDir::get_normale_vec(), Corrige_flux_FT_base::intersection_ijk_cell_, Corrige_flux_FT_base::lda_l_, Corrige_flux_FT_base::lda_v_, Intersection_Interface_ijk::norm_interf(), Corrige_flux_FT_base::parcours_, Vecteur3::produit_scalaire(), q_interface_cell_, and temp_interface_cell_.
Referenced by remplace_flux_par_quick_ghost_amont_1().
interpolation_quick_avec_1_ghost()
double Corrige_flux_FT_temperature_conv::interpolation_quick_avec_1_ghost (const double frac_liquide, const double decal) const protected
References ParcoursIJKDir::elem(), get_ghost_temp_if_cell_is_diph(), Corrige_flux_FT_base::parcours_, and quick().
Referenced by remplace_flux_par_quick_ghost_amont_1().
is_flux_upwind_from_interface()
bool Corrige_flux_FT_temperature_conv::is_flux_upwind_from_interface (const double decal) const protected
Referenced by remplace_flux_par_quick_ghost_amont_1().
Member Data Documentation
info_obj
const Type_info Corrige_flux_FT_temperature_conv::info_obj static
rho_cp_
IJK_MonofluidVar Corrige_flux_FT_temperature_conv::rho_cp_ protected
Referenced by initialize(), multiplie_par_rho_cp_de_la_face_monophasique(), and remplace_flux_par_quick_ghost_amont_1().
lda_
IJK_MonofluidVar Corrige_flux_FT_temperature_conv::lda_ protected
Referenced by initialize().
temp_interface_face_
ArrOfDouble Corrige_flux_FT_temperature_conv::temp_interface_face_ protected
Referenced by calcul_temp_flux_interf_pour_bary_face(), initialize(), and interp_back_to_bary_faces().
q_interface_face_
ArrOfDouble Corrige_flux_FT_temperature_conv::q_interface_face_ protected
Referenced by calcul_temp_flux_interf_pour_bary_face().
temp_interface_cell_
ArrOfDouble Corrige_flux_FT_temperature_conv::temp_interface_cell_ protected
Referenced by calcul_temp_flux_interf_pour_bary_cell(), extrapolation_amont_1_depuis_l_interface(), initialize(), and update_temperature_ghost().
q_interface_cell_
ArrOfDouble Corrige_flux_FT_temperature_conv::q_interface_cell_ protected
Referenced by calcul_temp_flux_interf_pour_bary_cell(), extrapolation_amont_1_depuis_l_interface(), and update_temperature_ghost().
temperature_barys_
DoubleTab Corrige_flux_FT_temperature_conv::temperature_barys_ protected
Referenced by initialize(), interp_back_to_bary_faces(), and remplace_flux_par_somme_rhocpf_Tf_v_Sf().
temperature_ghost_
DoubleTab Corrige_flux_FT_temperature_conv::temperature_ghost_ protected
Referenced by get_ghost_temp_if_cell_is_diph(), initialize(), and update_temperature_ghost().