TrioCFD: Coalescence_bulles_2groupes_PolyMAC_P0 Class Reference
Coalescence_bulles_2groupes_PolyMAC_P0 Class Reference
#include <Coalescence_bulles_2groupes_PolyMAC_P0.h>
Public Member Functions
const Type_info * get_info () const override
void mettre_a_jour (double temps) override
Public Member Functions inherited from Source_base
virtual int a_pour_Champ_Fonc (const Motcle &mot, TRUST_Ref< Champ_base * > &ch_ref) const
virtual void associer_champ_rho (const Champ_base &champ_rho)
virtual void completer ()
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
virtual void resetTime (double t)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Coalescence_bulles_2groupes_PolyMAC_P0()
Coalescence_bulles_2groupes_PolyMAC_P0::Coalescence_bulles_2groupes_PolyMAC_P0 ()
~Coalescence_bulles_2groupes_PolyMAC_P0()
Coalescence_bulles_2groupes_PolyMAC_P0::~Coalescence_bulles_2groupes_PolyMAC_P0 ()
Member Function Documentation
cree_instance()
Objet_U * Coalescence_bulles_2groupes_PolyMAC_P0::cree_instance () static
taille_memoire()
unsigned Coalescence_bulles_2groupes_PolyMAC_P0::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Coalescence_bulles_2groupes_PolyMAC_P0::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Coalescence_bulles_2groupes_PolyMAC_P0::info () static
get_info()
const Type_info * Coalescence_bulles_2groupes_PolyMAC_P0::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Source_base.
self_cast() [1/2]
Coalescence_bulles_2groupes_PolyMAC_P0 & Coalescence_bulles_2groupes_PolyMAC_P0::self_cast (Objet_U & r) static
self_cast() [2/2]
const Coalescence_bulles_2groupes_PolyMAC_P0 & Coalescence_bulles_2groupes_PolyMAC_P0::self_cast (const Objet_U & r) static
printOn()
Sortie & Coalescence_bulles_2groupes_PolyMAC_P0::printOn (Sortie & os) const override protected virtual
DOES NOTHING - to override in derived classes.
Imprime la source sur un flot de sortie.
Parameters
(Sortie& os) le flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Source_base.
readOn()
Entree & Coalescence_bulles_2groupes_PolyMAC_P0::readOn (Entree & is) override protected virtual
DOES NOTHING - to override in derived classes.
Lecture d'un terme source sur un flot d'entree.
Parameters
(Entree& is) le flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Source_base.
References Param::ajouter(), beta_k_, correlation_, Nom::debute_par(), dh_, MorEqn::equation(), Process::exit(), Nom::finit_par(), Probleme_base::get_correlation(), Probleme_base::has_correlation(), Param::lire_avec_accolades_depuis(), n_g1, n_g2, n_l, Pb_Multiphase::nb_phases(), Pb_Multiphase::nom_phase(), Objet_U::que_suis_je(), and Correlation_base::typer_lire_correlation().
has_interface_blocs()
int Coalescence_bulles_2groupes_PolyMAC_P0::has_interface_blocs () const inline override virtual
Reimplemented from Source_base.
dimensionner_blocs()
void Coalescence_bulles_2groupes_PolyMAC_P0::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl = {}) const override virtual
Reimplemented from Source_base.
References Matrix_tools::allocate_morse_matrix(), TRUSTTab< _TYPE_, _SIZE_ >::append_line(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), MorEqn::equation(), Probleme_base::get_champ(), Equation_base::inconnue(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Matrice_Morse::nb_colonnes(), Equation_base::probleme(), Champ_Inc_base::valeurs(), and Champ_Proto::valeurs().
ajouter_blocs()
void Coalescence_bulles_2groupes_PolyMAC_P0::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = {}) const override virtual
Reimplemented from Source_base.
References beta_k_, Coalescence_bulles_2groupes_base::coefficient_RC(), Coalescence_bulles_2groupes_base::coefficient_WE(), Op_Dift_Multiphase_proto::correlation(), correlation_, dh_, Objet_U::dimension, Viscosite_turbulente_base::eps(), MorEqn::equation(), Pb_Multiphase::equation_energie(), Pb_Multiphase::equation_masse(), Pb_Multiphase::equation_qdm(), Probleme_base::get_champ(), Champ_Face_base::get_elem_vector_field(), Milieu_composite::get_interface(), Milieu_composite::get_saturation(), Interface_base::get_sigma_tab(), Probleme_base::has_champ(), Milieu_composite::has_interface(), Milieu_composite::has_saturation(), Equation_base::inconnue(), Viscosite_turbulente_base::limiteur(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Milieu_base::masse_volumique(), Equation_base::milieu(), n_g1, n_g2, n_l, Pb_Multiphase::nb_phases(), Champ_Proto::passe(), Champ_Inc_base::passe(), Milieu_base::porosite_elem(), Equation_base::probleme(), Interface_base::sigma(), TRUST_Deriv< _CLASSE_ >::valeur(), Champ_Inc_base::valeurs(), and Champ_Proto::valeurs().
check_multiphase_compatibility()
void Coalescence_bulles_2groupes_PolyMAC_P0::check_multiphase_compatibility () const inline override virtual
Reimplemented from MorEqn.
associer_domaines()
void Coalescence_bulles_2groupes_PolyMAC_P0::associer_domaines (const Domaine_dis_base & , const Domaine_Cl_dis_base &) inline override virtual
Implements Source_base.
associer_pb()
void Coalescence_bulles_2groupes_PolyMAC_P0::associer_pb (const Probleme_base &) inline override virtual
Implements Source_base.
mettre_a_jour()
void Coalescence_bulles_2groupes_PolyMAC_P0::mettre_a_jour (double temps) inline override virtual
DOES NOTHING - to override in derived classes.
Mise a jour en temps du terme source.
Parameters
(double) le pas de temps de mise a jour
Reimplemented from Source_base.
Member Data Documentation
info_obj
const Type_info Coalescence_bulles_2groupes_PolyMAC_P0::info_obj static
correlation_
TRUST_Deriv< Correlation_base > Coalescence_bulles_2groupes_PolyMAC_P0::correlation_ protected
Referenced by ajouter_blocs(), and readOn().
beta_k_
double Coalescence_bulles_2groupes_PolyMAC_P0::beta_k_ = 0.09 protected
Referenced by ajouter_blocs(), and readOn().
dh_
double Coalescence_bulles_2groupes_PolyMAC_P0::dh_ = 1.e6 protected
Referenced by ajouter_blocs(), and readOn().
n_l
int Coalescence_bulles_2groupes_PolyMAC_P0::n_l = -1 protected
Referenced by ajouter_blocs(), and readOn().
n_g1
int Coalescence_bulles_2groupes_PolyMAC_P0::n_g1 = -1 protected
Referenced by ajouter_blocs(), and readOn().
n_g2
int Coalescence_bulles_2groupes_PolyMAC_P0::n_g2 = -1 protected
Referenced by ajouter_blocs(), and readOn().