TrioCFD: Terme_Source_Solide_SWIFT_VDF Class Reference
Terme_Source_Solide_SWIFT_VDF Class Reference
#include <Terme_Source_Solide_SWIFT_VDF.h>
Public Member Functions
const Type_info * get_info () const override
void mettre_a_jour (double temps) override
Public Member Functions inherited from Source_base
virtual int a_pour_Champ_Fonc (const Motcle &mot, TRUST_Ref< Champ_base * > &ch_ref) const
virtual void associer_champ_rho (const Champ_base &champ_rho)
virtual void completer ()
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
virtual void resetTime (double t)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Terme_Source_Solide_SWIFT_VDF()
Terme_Source_Solide_SWIFT_VDF::Terme_Source_Solide_SWIFT_VDF ()
~Terme_Source_Solide_SWIFT_VDF()
Terme_Source_Solide_SWIFT_VDF::~Terme_Source_Solide_SWIFT_VDF ()
Member Function Documentation
cree_instance()
Objet_U * Terme_Source_Solide_SWIFT_VDF::cree_instance () static
taille_memoire()
unsigned Terme_Source_Solide_SWIFT_VDF::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Terme_Source_Solide_SWIFT_VDF::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Terme_Source_Solide_SWIFT_VDF::info () static
get_info()
const Type_info * Terme_Source_Solide_SWIFT_VDF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Source_base.
self_cast() [1/2]
Terme_Source_Solide_SWIFT_VDF & Terme_Source_Solide_SWIFT_VDF::self_cast (Objet_U & r) static
self_cast() [2/2]
const Terme_Source_Solide_SWIFT_VDF & Terme_Source_Solide_SWIFT_VDF::self_cast (const Objet_U & r) static
printOn()
Sortie & Terme_Source_Solide_SWIFT_VDF::printOn (Sortie & os) const override protected virtual
DOES NOTHING - to override in derived classes.
Imprime la source sur un flot de sortie.
Parameters
(Sortie& os) le flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Source_base.
References Objet_U::que_suis_je().
readOn()
Entree & Terme_Source_Solide_SWIFT_VDF::readOn (Entree & is) override protected virtual
DOES NOTHING - to override in derived classes.
Lecture d'un terme source sur un flot d'entree.
Parameters
(Entree& is) le flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Source_base.
References compt_corse, compt_swift, corresp_corse, corresp_swift, correspondance_SWIFT_coarse(), eq_corse, eq_swift, Process::exit(), init_calcul_moyenne(), TRUST_Ref< _CLASSE_ >::le_nom(), Interprete::objet(), pb_corse, pb_swift, tau, TRUST_Ref< _CLASSE_ >::valeur(), Y_corse, and Y_swift.
calculer()
DoubleTab & Terme_Source_Solide_SWIFT_VDF::calculer (DoubleTab & resu) const override virtual
Reimplemented from Source_base.
References Source_base::ajouter().
init_calcul_moyenne()
void Terme_Source_Solide_SWIFT_VDF::init_calcul_moyenne (const Conduction & my_eqn, DoubleVect & Y, IntVect & corresp, IntVect & compt)
References Domaine_dis_base::domaine(), Champ_Inc_base::domaine_dis_base(), Conduction::inconnue(), Domaine_32_64< _SIZE_ >::nb_elem(), Domaine_VDF::nb_faces_X(), Domaine_VDF::nb_faces_Z(), and Domaine_VF::xp().
Referenced by readOn().
calcul_moyenne()
void Terme_Source_Solide_SWIFT_VDF::calcul_moyenne (const Conduction & my_eqn, DoubleVect & T_moy, const IntVect & corresp, const IntVect & compt) const
References Domaine_dis_base::domaine(), Champ_Inc_base::domaine_dis_base(), Conduction::inconnue(), Domaine_32_64< _SIZE_ >::nb_elem(), Domaine_VDF::nb_faces_X(), Domaine_VDF::nb_faces_Z(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), and Champ_Inc_base::valeurs().
Referenced by ajouter_blocs().
correspondance_SWIFT_coarse()
void Terme_Source_Solide_SWIFT_VDF::correspondance_SWIFT_coarse ()
References corresp_SC, TRUSTVect< _TYPE_, _SIZE_ >::resize(), TRUSTVect< _TYPE_, _SIZE_ >::size(), Y_corse, and Y_swift.
Referenced by readOn().
mettre_a_jour()
void Terme_Source_Solide_SWIFT_VDF::mettre_a_jour (double temps) inline override virtual
DOES NOTHING - to override in derived classes.
Mise a jour en temps du terme source.
Parameters
(double) le pas de temps de mise a jour
Reimplemented from Source_base.
associer_pb()
void Terme_Source_Solide_SWIFT_VDF::associer_pb (const Probleme_base & pb) override virtual
Implements Source_base.
associer_domaines()
void Terme_Source_Solide_SWIFT_VDF::associer_domaines (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis) override virtual
Implements Source_base.
dimensionner_blocs()
void Terme_Source_Solide_SWIFT_VDF::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl) const inline override virtual
Reimplemented from Source_base.
ajouter_blocs()
void Terme_Source_Solide_SWIFT_VDF::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl) const override virtual
Reimplemented from Source_base.
References calcul_moyenne(), compt_corse, compt_swift, corresp_corse, corresp_SC, corresp_swift, eq_corse, eq_swift, Domaine_dis_base::nb_elem(), tau, TRUST_Ref< _CLASSE_ >::valeur(), and Domaine_VF::volumes().
has_interface_blocs()
int Terme_Source_Solide_SWIFT_VDF::has_interface_blocs () const inline override virtual
Reimplemented from Source_base.
Member Data Documentation
info_obj
const Type_info Terme_Source_Solide_SWIFT_VDF::info_obj static
pb_swift
TRUST_Ref< Probleme_base *> Terme_Source_Solide_SWIFT_VDF::pb_swift protected
Referenced by readOn().
pb_corse
TRUST_Ref< Probleme_base *> Terme_Source_Solide_SWIFT_VDF::pb_corse protected
Referenced by readOn().
eq_swift
TRUST_Ref< Conduction *> Terme_Source_Solide_SWIFT_VDF::eq_swift protected
Referenced by ajouter_blocs(), and readOn().
eq_corse
TRUST_Ref< Conduction *> Terme_Source_Solide_SWIFT_VDF::eq_corse protected
Referenced by ajouter_blocs(), and readOn().
tau
double Terme_Source_Solide_SWIFT_VDF::tau = -123. protected
Referenced by ajouter_blocs(), and readOn().
Y_swift
DoubleVect Terme_Source_Solide_SWIFT_VDF::Y_swift protected
Referenced by correspondance_SWIFT_coarse(), and readOn().
Y_corse
DoubleVect Terme_Source_Solide_SWIFT_VDF::Y_corse protected
Referenced by correspondance_SWIFT_coarse(), and readOn().
compt_swift
IntVect Terme_Source_Solide_SWIFT_VDF::compt_swift protected
Referenced by ajouter_blocs(), and readOn().
compt_corse
IntVect Terme_Source_Solide_SWIFT_VDF::compt_corse protected
Referenced by ajouter_blocs(), and readOn().
corresp_swift
IntVect Terme_Source_Solide_SWIFT_VDF::corresp_swift protected
Referenced by ajouter_blocs(), and readOn().
corresp_corse
IntVect Terme_Source_Solide_SWIFT_VDF::corresp_corse protected
Referenced by ajouter_blocs(), and readOn().
corresp_SC
IntVect Terme_Source_Solide_SWIFT_VDF::corresp_SC protected
Referenced by ajouter_blocs(), and correspondance_SWIFT_coarse().