TrioCFD: Paroi_frottante_loi Class Reference
Paroi_frottante_loi Class Reference
#include <Paroi_frottante_loi.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Paroi_frottante_simple
const Type_info * get_info () const override
virtual int initialiser (double temps) override
void mettre_a_jour (double tps) override
const Type_info * get_info () const override
Public Member Functions inherited from Frottement_impose_base
void associer_domaine_cl_dis_base (const Domaine_Cl_dis_base &zcl) override
void associer_fr_dis_base (const Frontiere_dis_base &fr) override
void calculer_coeffs_echange (double temps) override
const Frontiere_dis_base & frontiere_dis () const override
Frontiere_dis_base & frontiere_dis () override
const Type_info * get_info () const override
int initialiser (double temps) override=0
void verifie_ch_init_nb_comp () const override
const Type_info * get_info () const override
Public Member Functions inherited from Cond_lim_base
virtual int a_mettre_a_jour_ss_pas_dt ()
virtual void associer_domaine_cl_dis_base (const Domaine_Cl_dis_base &)
virtual void associer_fr_dis_base (const Frontiere_dis_base &)
virtual void calculer_coeffs_echange (double temps)
virtual int compatible_avec_discr (const Discretisation_base &) const
Domaine_Cl_dis_base & domaine_Cl_dis ()
const Domaine_Cl_dis_base & domaine_Cl_dis () const
virtual Frontiere_dis_base & frontiere_dis ()
virtual const Frontiere_dis_base & frontiere_dis () const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
void set_modifier_val_imp (int)
virtual void verifie_ch_init_nb_comp () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Paroi_frottante_simple
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Cond_lim_base
void err_pas_compatible (const Discretisation_base &) const
void err_pas_compatible (const Equation_base &) const
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
transport de QDM. Le coefficient de frottement est calcule a partir de la correlation de loi de paroi adaptative.
See also
Neumann
Constructor & Destructor Documentation
Paroi_frottante_loi()
Paroi_frottante_loi::Paroi_frottante_loi ()
~Paroi_frottante_loi()
Paroi_frottante_loi::~Paroi_frottante_loi ()
Member Function Documentation
cree_instance()
Objet_U * Paroi_frottante_loi::cree_instance () static
taille_memoire()
unsigned Paroi_frottante_loi::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Paroi_frottante_loi::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Paroi_frottante_loi::info () static
get_info()
const Type_info * Paroi_frottante_loi::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Frottement_global_impose.
self_cast() [1/2]
Paroi_frottante_loi & Paroi_frottante_loi::self_cast (Objet_U & r) static
self_cast() [2/2]
const Paroi_frottante_loi & Paroi_frottante_loi::self_cast (const Objet_U & r) static
printOn()
Sortie & Paroi_frottante_loi::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Frottement_global_impose.
References Objet_U::que_suis_je().
readOn()
Entree & Paroi_frottante_loi::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Frottement_global_impose.
References Param::ajouter(), Cond_lim_base::app_domains, fac_prod_k_, fac_prod_k_grand_, Cond_lim_base::le_champ_front, Param::lire_avec_accolades_depuis(), Objet_U::que_suis_je(), Objet_U_ptr::typer(), y_p_prod_k_, and y_p_prod_k_grand_.
completer()
void Paroi_frottante_loi::completer () override virtual
NE FAIT RIEN A surcharger dans les classes derivees.
Reimplemented from Frottement_impose_base.
References Cond_lim_base::domaine_Cl_dis(), Process::exit(), fac_prod_k_, fac_prod_k_grand_, Objet_U::que_suis_je(), y_p_prod_k_, and y_p_prod_k_grand_.
fac_coeff_grad()
double Paroi_frottante_loi::fac_coeff_grad (double y_p) const override protected virtual
Reimplemented from Paroi_frottante_simple.
References fac_prod_k_, fac_prod_k_grand_, y_p_prod_k_, and y_p_prod_k_grand_.
Member Data Documentation
info_obj
const Type_info Paroi_frottante_loi::info_obj static
y_p_prod_k_
double Paroi_frottante_loi::y_p_prod_k_ = -1.e8 protected
Referenced by completer(), fac_coeff_grad(), and readOn().
fac_prod_k_
double Paroi_frottante_loi::fac_prod_k_ = -1.e8 protected
Referenced by completer(), fac_coeff_grad(), and readOn().
y_p_prod_k_grand_
double Paroi_frottante_loi::y_p_prod_k_grand_ = -1.e8 protected
Referenced by completer(), fac_coeff_grad(), and readOn().
fac_prod_k_grand_
double Paroi_frottante_loi::fac_prod_k_grand_ = -1.e8 protected
Referenced by completer(), fac_coeff_grad(), and readOn().