TrioCFD: Precond_local Class Reference
Precond_local Class Reference
#include <Precond_local.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Precond_base
const Type_info * get_info () const override
int preconditionner (const Matrice_Base &, const DoubleVect &src, DoubleVect &solution)
void prepare (const Matrice_Base &, const DoubleVect &src)
void reinit (Init_Status x=REINIT_ALL)
void set_echange_espace_virtuel_resultat (int flag)
virtual int supporte_matrice_morse_sym ()
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
void prepare_ (const Matrice_Base &, const DoubleVect &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
virtual void prepare_ (const Matrice_Base &, const DoubleVect &)
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Precond_local()
Precond_local::Precond_local ()
~Precond_local()
Precond_local::~Precond_local ()
Member Function Documentation
cree_instance()
Objet_U * Precond_local::cree_instance () static
taille_memoire()
unsigned Precond_local::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Precond_local::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Precond_local::info () static
get_info()
const Type_info * Precond_local::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Precond_base.
self_cast() [1/2]
Precond_local & Precond_local::self_cast (Objet_U & r) static
self_cast() [2/2]
const Precond_local & Precond_local::self_cast (const Objet_U & r) static
printOn()
Sortie & Precond_local::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Precond_base.
References le_precond_local_, and Objet_U::que_suis_je().
readOn()
Entree & Precond_local::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Precond_base.
References le_precond_local_.
prepare_()
void Precond_local::prepare_ (const Matrice_Base & m, const DoubleVect & v) override protected virtual
this method must be overloaded if some preparation is necessary.
It is called after a call to reinit() and before the next call to preconditionner_(). Do not forget to call the prepare_() method of the ancestor (at the end of the routine, otherwise status will be put to READY) and use get_status() to know what should be prepared.
Reimplemented from Precond_base.
References Matrice_Bloc_Sym::BlocSymToMatMorseSym(), Process::exit(), Matrice_Bloc::get_bloc(), Matrice_Bloc_Sym::get_bloc(), Matrice_Sym::get_est_definie(), le_precond_local_, matrice_a_resoudre_, matrice_de_travail_, Precond_base::prepare_(), Objet_U::que_suis_je(), Matrice_Sym::set_est_definie(), and TRUST_Deriv< _CLASSE_ >::valeur().
preconditionner_()
int Precond_local::preconditionner_ (const Matrice_Base & la_matrice, const DoubleVect & secmem, DoubleVect & solution) override protected virtual
Implements Precond_base.
References matrice_a_resoudre_, precond(), and TRUST_Ref< _CLASSE_ >::valeur().
precond()
int Precond_local::precond (const Matrice_Base & mat, const DoubleVect & secmem, DoubleVect & solution) protected
References Process::exit(), Process::is_parallel(), le_precond_local_, res_syst_loc_hybride(), res_syst_loc_simple(), SolveurSys::resoudre_systeme(), and TRUSTVect< _TYPE_, _SIZE_ >::size().
Referenced by preconditionner_().
res_syst_loc_simple()
void Precond_local::res_syst_loc_simple (const Matrice_Morse_Sym & mat, const DoubleVect & secmem, DoubleVect & solution, const Champ_Inc_base & champ) protected
References Matrice_Morse::coeff_, Matrice_Morse::dimensionner(), Process::exit(), Matrice_Sym::get_est_definie(), la_matrice_locale_, le_precond_local_, SolveurSys::resoudre_systeme(), Matrice_Sym::set_est_definie(), TRUSTVect< _TYPE_, _SIZE_ >::size(), Matrice_Morse::tab1_, and Matrice_Morse::tab2_.
Referenced by precond().
res_syst_loc_hybride()
void Precond_local::res_syst_loc_hybride (const Matrice_Morse_Sym & mat, const DoubleVect & secmem, DoubleVect & solution, const Champ_Inc_base & champ) protected
References Matrice_Morse::coeff_, Matrice_Morse::dimensionner(), Domaine_dis_base::domaine(), Champ_Inc_base::domaine_dis_base(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Process::exit(), Matrice_Sym::get_est_definie(), la_matrice_locale_, le_precond_local_, SolveurSys::resoudre_systeme(), Matrice_Sym::set_est_definie(), TRUSTVect< _TYPE_, _SIZE_ >::size(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), Matrice_Morse::tab1_, and Matrice_Morse::tab2_.
Referenced by precond().
Member Data Documentation
info_obj
const Type_info Precond_local::info_obj static
le_precond_local_
SolveurSys Precond_local::le_precond_local_ protected
Referenced by precond(), prepare_(), printOn(), readOn(), res_syst_loc_hybride(), and res_syst_loc_simple().
la_matrice_locale_
Matrice_Morse_Sym Precond_local::la_matrice_locale_ protected
Referenced by res_syst_loc_hybride(), and res_syst_loc_simple().
matrice_de_travail_
Matrice_Morse_Sym Precond_local::matrice_de_travail_ protected
Referenced by prepare_().
matrice_a_resoudre_
TRUST_Ref< Matrice_Base *> Precond_local::matrice_a_resoudre_ protected
Referenced by preconditionner_(), and prepare_().