TrioCFD: Source_Action_Particules Class Reference
Source_Action_Particules Class Reference
#include <Source_Action_Particules.h>
Public Member Functions
const Type_info * get_info () const override
void mettre_a_jour (double temps) override
Public Member Functions inherited from Source_base
virtual int a_pour_Champ_Fonc (const Motcle &mot, TRUST_Ref< Champ_base * > &ch_ref) const
virtual void associer_champ_rho (const Champ_base &champ_rho)
virtual void completer ()
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
virtual void resetTime (double t)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
(ou inversement) Ces forces interviennent dans le bilan de qdm des particules (one_way_coupling) et eventuellement dans l equation de Navier_Stokes (two_way_coupling) sous forme d une source interpolee (voir Source_Reaction_Particules) .SECTION Classe non instanciable.
Constructor & Destructor Documentation
Source_Action_Particules()
Source_Action_Particules::Source_Action_Particules ()
~Source_Action_Particules()
Source_Action_Particules::~Source_Action_Particules () override
Member Function Documentation
info()
const Type_info * Source_Action_Particules::info () static
get_info()
const Type_info * Source_Action_Particules::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Source_base.
Reimplemented in Source_Flottabilite, Source_Masse_Ajoutee, Source_Portance, and Source_Trainee.
self_cast() [1/2]
Source_Action_Particules & Source_Action_Particules::self_cast (Objet_U & r) static
self_cast() [2/2]
const Source_Action_Particules & Source_Action_Particules::self_cast (const Objet_U & r) static
printOn()
Sortie & Source_Action_Particules::printOn (Sortie & os) const override protected virtual
DOES NOTHING - to override in derived classes.
Imprime la source sur un flot de sortie.
Parameters
(Sortie& os) le flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Source_base.
Reimplemented in Source_Flottabilite, Source_Masse_Ajoutee, Source_Portance, and Source_Trainee.
readOn()
Entree & Source_Action_Particules::readOn (Entree & is) override protected virtual
DOES NOTHING - to override in derived classes.
Lecture d'un terme source sur un flot d'entree.
Parameters
(Entree& is) le flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Source_base.
Reimplemented in Source_Flottabilite, Source_Masse_Ajoutee, Source_Portance, and Source_Trainee.
mettre_a_jour()
void Source_Action_Particules::mettre_a_jour (double temps) override virtual
DOES NOTHING - to override in derived classes.
Mise a jour en temps du terme source.
Parameters
(double) le pas de temps de mise a jour
Reimplemented from Source_base.
vitesse_fluide()
const DoubleTab & Source_Action_Particules::vitesse_fluide () const inline
References MorEqn::equation(), and Transport_Marqueur_FT::vitesse_fluide().
Referenced by Source_Masse_Ajoutee::ajouter(), and Source_Trainee::ajouter().
rho_fluide()
const DoubleTab & Source_Action_Particules::rho_fluide () const inline
References MorEqn::equation(), and Transport_Marqueur_FT::rho_fluide().
Referenced by Source_Masse_Ajoutee::ajouter(), and Source_Trainee::ajouter().
visco_dyn_fluide()
const DoubleTab & Source_Action_Particules::visco_dyn_fluide () const inline
References MorEqn::equation(), and Transport_Marqueur_FT::visco_dyn_fluide().
Referenced by Source_Trainee::ajouter().
grad_pression()
const DoubleTab & Source_Action_Particules::grad_pression () const inline
References MorEqn::equation(), and Transport_Marqueur_FT::grad_pression().
Referenced by Source_Flottabilite::ajouter().
vitesse_particules()
const DoubleTab & Source_Action_Particules::vitesse_particules () const inline
References MorEqn::equation(), Transport_Interfaces_FT_Disc::proprietes_particules(), and Proprietes_part_vol::vitesse_particules().
Referenced by Source_Masse_Ajoutee::ajouter(), and Source_Trainee::ajouter().
delta_v()
const DoubleTab & Source_Action_Particules::delta_v () const inline
References Proprietes_part_vol::delta_v(), MorEqn::equation(), and Transport_Interfaces_FT_Disc::proprietes_particules().
Referenced by Source_Masse_Ajoutee::ajouter().
rho_particules()
const DoubleTab & Source_Action_Particules::rho_particules () const inline
References MorEqn::equation(), Proprietes_part_vol::masse_vol_particules(), and Transport_Interfaces_FT_Disc::proprietes_particules().
Referenced by Source_Flottabilite::ajouter(), and Source_Trainee::ajouter().
diametre_particules()
const DoubleTab & Source_Action_Particules::diametre_particules () const inline
References Proprietes_part_vol::diametre_particules(), MorEqn::equation(), and Transport_Interfaces_FT_Disc::proprietes_particules().
Referenced by Source_Trainee::ajouter().
volumes_particules()
const DoubleTab & Source_Action_Particules::volumes_particules () const inline
References MorEqn::equation(), Transport_Interfaces_FT_Disc::proprietes_particules(), and Proprietes_part_vol::volume_particules().
Referenced by Source_Flottabilite::ajouter(), and Source_Masse_Ajoutee::ajouter().
associer_domaines()
void Source_Action_Particules::associer_domaines (const Domaine_dis_base & zdis, const Domaine_Cl_dis_base & zcldis) override protected virtual
Implements Source_base.
associer_pb()
void Source_Action_Particules::associer_pb (const Probleme_base & pb) override protected virtual
Implements Source_base.
Member Data Documentation
info_obj
const Type_info Source_Action_Particules::info_obj static