TrioCFD: YAML_data Class Reference
YAML_data Class Reference
#include <YAML_data.h>
Constructor & Destructor Documentation
YAML_data() [1/5]
YAML_data::YAML_data () inline
YAML_data() [2/5]
YAML_data::YAML_data (const std::string & name, const std::string & type) inline
YAML_data() [3/5]
YAML_data::YAML_data (const std::string & name, const std::string & type, int nb_dim) inline
YAML_data() [4/5]
YAML_data::YAML_data (const std::string & name, const std::string & type, int nb_dim, bool loc) inline
YAML_data() [5/5]
YAML_data::YAML_data (const std::string & name, const std::string & type, int nb_dim, bool loc, bool is_ds) inline
Member Function Documentation
set_local()
void YAML_data::set_local (bool l) inline
Referenced by Ecrire_YAML::add_scalar(), Transport_Interfaces_FT_Disc_interne::data_a_sauvegarder(), Postraitement::data_a_sauvegarder(), and Convection_Diffusion_Chaleur_Fluide_Dilatable_base::data_a_sauvegarder().
set_conditions()
void YAML_data::set_conditions (const std::string & cond) inline
Referenced by Postraitement::data_a_sauvegarder().
add_attribute()
void YAML_data::add_attribute (const std::string & attr) inline
set_dataset()
void YAML_data::set_dataset (bool d) inline
set_hdf_name()
void YAML_data::set_hdf_name (const std::string & n) inline
set_save_field_type()
void YAML_data::set_save_field_type (bool b) inline
Referenced by Champ_Inc_base::data_a_sauvegarder().
get_name()
const std::string & YAML_data::get_name () const inline
get_type()
const std::string & YAML_data::get_type () const inline
get_dims()
int YAML_data::get_dims () const inline
is_local()
bool YAML_data::is_local () const inline
get_conditions()
const std::string & YAML_data::get_conditions () const inline
get_attributes()
const std::vector< std::string > & YAML_data::get_attributes () const inline
is_dataset()
bool YAML_data::is_dataset () const inline
get_hdf_name()
const std::string & YAML_data::get_hdf_name () const inline
save_field_type()
bool YAML_data::save_field_type () const inline