TrioCFD: Tube_libre Class Reference
Tube_libre Class Reference
#include <Tube_base.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Tube_libre()
Tube_libre::Tube_libre ()
~Tube_libre()
Tube_libre::~Tube_libre ()
Member Function Documentation
cree_instance()
Objet_U * Tube_libre::cree_instance () static
taille_memoire()
unsigned Tube_libre::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Tube_libre::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Tube_libre::info () static
get_info()
const Type_info * Tube_libre::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Tube_base.
self_cast() [1/2]
Tube_libre & Tube_libre::self_cast (Objet_U & r) static
self_cast() [2/2]
const Tube_libre & Tube_libre::self_cast (const Objet_U & r) static
printOn()
Sortie & Tube_libre::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Tube_base.
References Tube_base::acceleration_, amortissement_, blocage_, Tube_base::nom_, Tube_base::omega_, Tube_base::pos_, position_equilibre_, raideur_, Tube_base::rayon_, rho_cylindre_, and Tube_base::v_.
readOn()
Entree & Tube_libre::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Tube_base.
References Tube_base::acceleration_, Param::ajouter(), Param::ajouter_flag(), amortissement_, blocage_, Param::lire_avec_accolades(), Tube_base::nom_, Tube_base::omega_, Tube_base::pos_, position_equilibre_, Objet_U::que_suis_je(), raideur_, Tube_base::rayon_, Param::REQUIRED, TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), rho_cylindre_, and Tube_base::v_.
update_vitesse_position()
void Tube_libre::update_vitesse_position (double current_time, double dt, const Vecteur3 & force_appliquee) override virtual
Implements Tube_base.
References Tube_base::acceleration_, amortissement_, blocage_, Domaine_IJK::get_constant_delta(), Domaine_IJK::get_node_coordinates(), Tube_base::pos_, position_equilibre_, raideur_, Tube_base::rayon_, Tube_base::ref_domaine_, rho_cylindre_, TRUSTArray< _TYPE_, _SIZE_ >::size_array(), Tube_base::v_, and TRUST_Ref< _CLASSE_ >::valeur().
Member Data Documentation
info_obj
const Type_info Tube_libre::info_obj static
position_equilibre_
Vecteur3 Tube_libre::position_equilibre_ protected
Referenced by printOn(), readOn(), and update_vitesse_position().
blocage_
ArrOfInt Tube_libre::blocage_ protected
Referenced by printOn(), readOn(), and update_vitesse_position().
rho_cylindre_
double Tube_libre::rho_cylindre_ protected
Referenced by printOn(), readOn(), and update_vitesse_position().
amortissement_
double Tube_libre::amortissement_ protected
Referenced by printOn(), readOn(), and update_vitesse_position().
raideur_
double Tube_libre::raideur_ protected
Referenced by printOn(), readOn(), and update_vitesse_position().