TrioCFD: Op_Diff_Turbulent_base Class Reference
Op_Diff_Turbulent_base Class Reference
#include <Op_Diff_Turbulent_base.h>
Detailed Description
See also
Operateur_Diff_base
Constructor & Destructor Documentation
~Op_Diff_Turbulent_base()
virtual Op_Diff_Turbulent_base::~Op_Diff_Turbulent_base () inline virtual
Member Function Documentation
associer_diffusivite_turbulente()
void Op_Diff_Turbulent_base::associer_diffusivite_turbulente (const Champ_Fonc_base & diff_turb)
Referenced by Op_Dift_VDF_Face_Axi_base::associer_diffusivite_turbulente(), Op_Dift_VDF_base::associer_diffusivite_turbulente_base(), Op_Diff_DG_Elem::completer(), Op_Dift_EF_base::completer(), Op_Diff_PolyMAC_Elem::completer(), Op_Diff_PolyMAC_Face::completer(), and Op_Dift_VEF_base::completer().
diffusivite_turbulente()
const Champ_Fonc_base & Op_Diff_Turbulent_base::diffusivite_turbulente () const inline
References TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Op_Diff_K_Eps_VEF_Face::ajouter(), Op_Diff_K_Omega_VEF_Face::ajouter(), Op_Dift_Stab_VEF_Face::ajouter(), Op_Dift_standard_VEF_Face::ajouter(), Op_Dift_VEF_Face::ajouter(), Op_Dift_VEF_Face_Q1::ajouter(), Op_Dift_VEF_P1NCP1B_Face::ajouter(), Op_Dift_EF_Q1::ajouter_bords(), Op_Dift_EF_Q1::ajouter_contribution(), Op_Dift_EF_Q1::ajouter_contribution_new(), Op_Dift_EF_Q1::ajouter_new(), Op_Dift_EF_Q1::calculer_dt_stab(), Op_Dift_VEF_base::calculer_dt_stab(), Op_Dift_VDF_Face_base::calculer_dt_stab(), Op_Dift_VDF_Elem_base::calculer_dt_stab_elem(), Op_Dift_VDF_Elem_base::calculer_dt_stab_elem_axi(), Op_Dift_VDF_Elem_base::calculer_dt_stab_elem_var_axi(), Op_Dift_VEF_base::calculer_dt_stab_P1NCP1B(), Op_Dift_VEF_base::calculer_pour_post(), Op_Diff_K_Eps_VEF_Face::contribuer_a_avec(), Op_Diff_K_Omega_VEF_Face::contribuer_a_avec(), Op_Dift_Stab_VEF_Face::contribuer_a_avec(), Op_Dift_VEF_Face::contribuer_a_avec(), Op_Dift_VEF_Face_Q1::contribuer_a_avec(), Op_Dift_VEF_Face::contribuer_au_second_membre(), Op_Diff_DG_base::update_nu(), and Op_Diff_PolyMAC_base::update_nu().
has_diffusivite_turbulente()
bool Op_Diff_Turbulent_base::has_diffusivite_turbulente () const inline
References TRUST_Ref< _CLASSE_ >::non_nul().
Referenced by Op_Diff_DG_base::update_nu(), and Op_Diff_PolyMAC_base::update_nu().