TrioCFD: Op_Conv_Amont_old_VEF_Face Class Reference
Op_Conv_Amont_old_VEF_Face Class Reference
#include <Op_Conv_Amont_old_VEF_Face.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Op_Conv_VEF_base
double calculer_dt_stab () const override
const Type_info * get_info () const override
int impr (Sortie &os) const override
const Type_info * get_info () const override
Public Member Functions inherited from Operateur_base
void associer_eqn (const Equation_base &)
virtual double calculer_dt_stab () const
virtual void completer ()
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual void mettre_a_jour (double temps)
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Op_VEF_Face
void dimensionner (const Domaine_VEF &, const Domaine_Cl_VEF &, Matrice_Morse &) const
void modifier_matrice_pour_periodique_apres_contribuer (Matrice_Morse &matrice, const Equation_base &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Op_Conv_VEF_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
Cette classe represente l'operateur de convection associe a une equation de transport d'un scalaire. La discretisation est VEF Le champ convecte est scalaire ou vecteur de type Champ_P1NC Le schema de convection est du type Amont Les methodes pour l'implicite sont codees.
See also
Operateur_Conv_base
Constructor & Destructor Documentation
Op_Conv_Amont_old_VEF_Face()
Op_Conv_Amont_old_VEF_Face::Op_Conv_Amont_old_VEF_Face ()
~Op_Conv_Amont_old_VEF_Face()
Op_Conv_Amont_old_VEF_Face::~Op_Conv_Amont_old_VEF_Face ()
Member Function Documentation
cree_instance()
Objet_U * Op_Conv_Amont_old_VEF_Face::cree_instance () static
taille_memoire()
unsigned Op_Conv_Amont_old_VEF_Face::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Op_Conv_Amont_old_VEF_Face::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Op_Conv_Amont_old_VEF_Face::info () static
get_info()
const Type_info * Op_Conv_Amont_old_VEF_Face::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Operateur_Conv_base.
self_cast() [1/2]
Op_Conv_Amont_old_VEF_Face & Op_Conv_Amont_old_VEF_Face::self_cast (Objet_U & r) static
self_cast() [2/2]
const Op_Conv_Amont_old_VEF_Face & Op_Conv_Amont_old_VEF_Face::self_cast (const Objet_U & r) static
printOn()
Sortie & Op_Conv_Amont_old_VEF_Face::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN A surcharger dans les classes derivees.
Parameters
(Sortie& os) un flot de sortie
Returns
(Sortie&) le flot de sortie
Reimplemented from Operateur_Conv_base.
References Objet_U::que_suis_je().
readOn()
Entree & Op_Conv_Amont_old_VEF_Face::readOn (Entree & is) override protected virtual
NE FAIT RIEN A surcharger dans les classes derivees.
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree
Reimplemented from Operateur_Conv_base.
ajouter()
DoubleTab & Op_Conv_Amont_old_VEF_Face::ajouter (const DoubleTab & transporte, DoubleTab & resu) const override virtual
Reimplemented from Operateur_base.
References Elem_VEF_base::calcul_vc(), Objet_U::dimension, Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), MorEqn::equation(), Periodique::face_associee(), Domaine_VF::face_normales(), Domaine_VEF::facette_normales(), Op_Conv_VEF_base::fluent_, Operateur_base::flux_bords_, Elem_VEF_base::KEL(), Op_Conv_VEF_base::la_zcl_vef, Op_Conv_VEF_base::le_dom_vef, Domaine_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Equation_base::milieu(), Op_VEF_Face::modifier_flux(), Domaine_dis_base::nb_elem_tot(), Front_VF::nb_faces(), Domaine_VF::nb_faces_bord(), Elem_VEF_base::nb_facette(), Domaine_dis_base::nb_front_Cl(), Domaine_Cl_VEF::normales_facettes_Cl(), Front_VF::num_premiere_face(), Milieu_base::porosite_face(), Objet_U::que_suis_je(), Domaine_VEF::rang_elem_non_std(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Domaine_VEF::type_elem(), Domaine_Cl_VEF::type_elem_Cl(), Neumann_sortie_libre::val_ext(), TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_base::valeur_a_sommet_compo(), Champ_Inc_base::valeurs(), Op_Conv_VEF_base::vitesse(), and Op_Conv_VEF_base::vitesse_.
dimensionner()
void Op_Conv_Amont_old_VEF_Face::dimensionner (Matrice_Morse & matrice) const inline override virtual
on dimensionne notre matrice au moyen de la methode dimensionner de la classe Op_VEF_Face.
Reimplemented from Operateur_base.
References Op_VEF_Face::dimensionner(), Op_Conv_VEF_base::la_zcl_vef, Op_Conv_VEF_base::le_dom_vef, and TRUST_Ref< _CLASSE_ >::valeur().
modifier_pour_Cl()
void Op_Conv_Amont_old_VEF_Face::modifier_pour_Cl (Matrice_Morse & matrice, DoubleTab & secmem) const inline override virtual
On modifie le second membre et la matrice dans le cas des conditions de dirichlet.
Reimplemented from Operateur_base.
References Op_Conv_VEF_base::la_zcl_vef, Op_Conv_VEF_base::le_dom_vef, Op_VEF_Face::modifier_pour_Cl(), and TRUST_Ref< _CLASSE_ >::valeur().
contribuer_a_avec()
void Op_Conv_Amont_old_VEF_Face::contribuer_a_avec (const DoubleTab & inco, Matrice_Morse & matrice) const inline override virtual
on assemble la matrice des inconnues implicite.
Reimplemented from Operateur_base.
References ajouter_contribution().
contribuer_au_second_membre()
void Op_Conv_Amont_old_VEF_Face::contribuer_au_second_membre (DoubleTab & resu) const inline override virtual
on ajoute la contribution du second membre.
Reimplemented from Operateur_base.
References contribue_au_second_membre().
contribue_au_second_membre()
void Op_Conv_Amont_old_VEF_Face::contribue_au_second_membre (DoubleTab & resu) const
References Objet_U::dimension, Periodique::face_associee(), Domaine_VF::face_normales(), Op_Conv_VEF_base::la_zcl_vef, Op_Conv_VEF_base::le_dom_vef, Domaine_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), Neumann_sortie_libre::val_ext(), TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_Inc_base::valeurs(), and Op_Conv_VEF_base::vitesse_.
Referenced by contribuer_au_second_membre().
ajouter_contribution()
void Op_Conv_Amont_old_VEF_Face::ajouter_contribution (const DoubleTab & transporte, Matrice_Morse & matrice) const
References Elem_VEF_base::calcul_vc(), Objet_U::dimension, Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), MorEqn::equation(), Periodique::face_associee(), Domaine_VF::face_normales(), Domaine_VEF::facette_normales(), Matrice_Morse::get_set_coeff(), Matrice_Morse::get_set_tab1(), Matrice_Morse::get_set_tab2(), Elem_VEF_base::KEL(), Op_Conv_VEF_base::la_zcl_vef, Op_Conv_VEF_base::le_dom_vef, Domaine_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Equation_base::milieu(), Domaine_dis_base::nb_elem_tot(), Front_VF::nb_faces(), Elem_VEF_base::nb_facette(), Domaine_dis_base::nb_front_Cl(), Domaine_Cl_VEF::normales_facettes_Cl(), Front_VF::num_premiere_face(), Milieu_base::porosite_face(), Domaine_VEF::rang_elem_non_std(), Domaine_VEF::type_elem(), Domaine_Cl_VEF::type_elem_Cl(), TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_base::valeur_a_sommet_compo(), Champ_Inc_base::valeurs(), Op_Conv_VEF_base::vitesse(), and Op_Conv_VEF_base::vitesse_.
Referenced by contribuer_a_avec().
Member Data Documentation
info_obj
const Type_info Op_Conv_Amont_old_VEF_Face::info_obj static