TrioCFD: Loi_Paroi_Nu_Impose_VEF Class Reference
Loi_Paroi_Nu_Impose_VEF Class Reference
#include <Loi_Paroi_Nu_Impose_VEF.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Turbulence_paroi_scal_base
void associer_modele (const Modele_turbulence_scal_base &)
const Type_info * get_info () const override
void imprimer_nusselt_mean_only (Sortie &, int, const TRUST_List< Nom > &, const Nom &) const
void imprimer_premiere_ligne_nusselt (int, const TRUST_List< Nom > &, const Nom &) const
int reprendre (Entree &is) override
int sauvegarder (Sortie &os) const override
virtual bool use_equivalent_distance () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Turbulence_paroi_scal_base
static void typer_lire_turbulence_paroi_scal (TRUST_Deriv< Turbulence_paroi_scal_base > &, const Modele_turbulence_scal_base &, Entree &)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
.SECTION voir aussi Paroi_std_hyd_VEF
Constructor & Destructor Documentation
Loi_Paroi_Nu_Impose_VEF()
Loi_Paroi_Nu_Impose_VEF::Loi_Paroi_Nu_Impose_VEF ()
~Loi_Paroi_Nu_Impose_VEF()
Loi_Paroi_Nu_Impose_VEF::~Loi_Paroi_Nu_Impose_VEF ()
Member Function Documentation
cree_instance()
Objet_U * Loi_Paroi_Nu_Impose_VEF::cree_instance () static
taille_memoire()
unsigned Loi_Paroi_Nu_Impose_VEF::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Loi_Paroi_Nu_Impose_VEF::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Loi_Paroi_Nu_Impose_VEF::info () static
get_info()
const Type_info * Loi_Paroi_Nu_Impose_VEF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Paroi_scal_hyd_base_VEF.
self_cast() [1/2]
Loi_Paroi_Nu_Impose_VEF & Loi_Paroi_Nu_Impose_VEF::self_cast (Objet_U & r) static
self_cast() [2/2]
const Loi_Paroi_Nu_Impose_VEF & Loi_Paroi_Nu_Impose_VEF::self_cast (const Objet_U & r) static
printOn()
Sortie & Loi_Paroi_Nu_Impose_VEF::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Paroi_scal_hyd_base_VEF.
References Objet_U::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Loi_Paroi_Nu_Impose_VEF::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Paroi_scal_hyd_base_VEF.
References Parser_U::addVar(), diam_hydr, Objet_U::dimension, Process::exit(), Field_base::nb_comp(), nusselt, Parser_U::parseString(), Objet_U::que_suis_je(), Motcles::search(), Parser_U::setNbVar(), and Parser_U::setString().
calculer_scal()
int Loi_Paroi_Nu_Impose_VEF::calculer_scal (Champ_Fonc_base & diffusivite_turb) override virtual
Implements Turbulence_paroi_scal_base.
References diam_hydr, Milieu_base::diffusivite(), Objet_U::dimension, Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), Turbulence_paroi_scal_base::equivalent_distance_, Parser_U::eval(), Process::exit(), Domaine_VF::face_voisins(), Equation_base::inconnue(), Turbulence_paroi_scal_base::le_dom_Cl_dis_, Turbulence_paroi_scal_base::le_dom_dis_, Equation_base::milieu(), Turbulence_paroi_scal_base::mon_modele_turb_scal, Field_base::nb_comp(), Front_VF::nb_faces(), Domaine_32_64< _SIZE_ >::nb_faces_elem(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_face(), nusselt, Domaine_VF::premiere_face_int(), Parser_U::setVar(), TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_base::valeur_a_compo(), Champ_Don_base::valeurs(), Champ_Inc_base::valeurs(), Fluide_base::viscosite_cinematique(), and Domaine_VF::xv().
imprimer_nusselt()
void Loi_Paroi_Nu_Impose_VEF::imprimer_nusselt (Sortie &) const override virtual
Reimplemented from Paroi_scal_hyd_base_VEF.
References Milieu_base::conductivite(), diam_hydr, Objet_U::dimension, Domaine_dis_base::domaine(), Equation_base::domaine_Cl_dis(), Domaine_VF::elem_faces(), Probleme_base::equation(), Turbulence_paroi_scal_base::equivalent_distance(), Domaine_VF::face_normales(), Domaine_VF::face_surfaces(), Domaine_VF::face_voisins(), Neumann::flux_impose(), Equation_base::inconnue(), Process::je_suis_maitre(), Turbulence_paroi_scal_base::le_dom_Cl_dis_, Turbulence_paroi_scal_base::le_dom_dis_, Frontiere_dis_base::le_nom(), Domaine_Cl_dis_base::les_conditions_limites(), Equation_base::milieu(), Turbulence_paroi_scal_base::mon_modele_turb_scal, Field_base::nb_comp(), Front_VF::nb_faces(), Domaine_32_64< _SIZE_ >::nb_faces_elem(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), Domaine_VEF::oriente_normale(), Turbulence_paroi_scal_base::ouvrir_fichier_partage(), Equation_base::probleme(), EcrFicPartage::syncfile(), TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_base::valeur_a_compo(), Champ_Don_base::valeurs(), Champ_Inc_base::valeurs(), and Domaine_VF::xv().
Member Data Documentation
info_obj
const Type_info Loi_Paroi_Nu_Impose_VEF::info_obj static
diam_hydr
TRUST_Deriv< Champ_Don_base > Loi_Paroi_Nu_Impose_VEF::diam_hydr protected
Referenced by calculer_scal(), imprimer_nusselt(), and readOn().
nusselt
Parser_U Loi_Paroi_Nu_Impose_VEF::nusselt protected
Referenced by calculer_scal(), and readOn().