TrioCFD: Postprocessing_IJK Class Reference
Postprocessing_IJK Class Reference
#include <Postprocessing_IJK.h>
Public Member Functions
const IJK_Field_double & get_IJK_field (const Motcle &nom) override
const Type_info * get_info () const override
double get_max_timestep_for_post (double current_time) const
void init () override
bool is_post_required (const Motcle &nom) const
int lire_champs_a_postraiter (Entree &is, bool expect_acco) override
int postraiter_champs () override
void prepare_lata_and_stats ()
void register_interface_field (const Motcle &nom_champ, const Motcle &loc) override
void resetTime (double t, std::string dirname) override
void update_stat_ft (const double dt)
int write_extra_mesh () override
Public Member Functions inherited from Postraitement_ft_lata
const Type_info * get_info () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
Public Member Functions inherited from Postraitement
int & compteur_champ_stat ()
const Type_info * get_info () const override
void init () override
virtual int lire_champs_a_postraiter (Entree &is, bool expect_acco)
int lire_motcle_non_standard (const Motcle &, Entree &) override
Postraitement ()
virtual int postraiter_champs ()
int postraiter_sondes ()
int reprendre (Entree &is) override
void resetTime (double t, const std::string dirname) override
int sauvegarder (Sortie &os) const override
int traiter_champs ()
int traiter_sondes ()
virtual int write_extra_mesh ()
Public Member Functions inherited from Postraitement_base
const Type_info * get_info () const override
const Nom & le_nom () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
int reprendre (Entree &is) override
int sauvegarder (Sortie &os) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Types
using FieldIndex_t = std::pair< int, bool >
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Postraitement_ft_lata
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Attributes
std::vector< FieldIndex_t > field_post_idx_
Additional Inherited Members
Public Types inherited from Champs_compris_IJK_interface
using FieldInfo_t = std::tuple< Motcle, Entity, Nature_du_champ, bool >
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
Post-processing stuff of Probleme_FTD_IJK_base.
Member Typedef Documentation
FieldInfo_t
using Postprocessing_IJK::FieldInfo_t = Champs_compris_IJK_interface::FieldInfo_t
FieldIndex_t
using Postprocessing_IJK::FieldIndex_t = std::pair<int, bool> protected
Handy type to register the reference of a field to be postprocessed:
first part is the index in champs_postraitables_ array
second part is a boolean indicating if an interpolation will be needed (when projecting from face to elem)
Constructor & Destructor Documentation
Postprocessing_IJK()
Postprocessing_IJK::Postprocessing_IJK ()
References TRUST_Vector< _CLASSE_ >::dimensionner(), and groups_statistiques_FT_.
~Postprocessing_IJK()
Postprocessing_IJK::~Postprocessing_IJK ()
Member Function Documentation
cree_instance()
Objet_U * Postprocessing_IJK::cree_instance () static
taille_memoire()
unsigned Postprocessing_IJK::taille_memoire () const override virtual
Reimplemented from Postraitement.
duplique()
int Postprocessing_IJK::duplique () const override virtual
Reimplemented from Postraitement.
info()
const Type_info * Postprocessing_IJK::info () static
get_info()
const Type_info * Postprocessing_IJK::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Postraitement.
self_cast() [1/2]
Postprocessing_IJK & Postprocessing_IJK::self_cast (Objet_U & r) static
self_cast() [2/2]
const Postprocessing_IJK & Postprocessing_IJK::self_cast (const Objet_U & r) static
printOn()
Sortie & Postprocessing_IJK::printOn (Sortie & s) const override protected virtual
Imprime le type de l'objet sur un flot de sortie.
Parameters
(Sortie& s) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Postraitement.
readOn()
Entree & Postprocessing_IJK::readOn (Entree & s) override protected virtual
Lit les directives de postraitement sur un flot d'entree.
Format: Postraitement { Sondes bloc de lecture des sondes | Champs bloc de lecture des champs a postraiter | Statistiques bloc de lecture objet statistique | Fichier }
Parameters
(Entree& s) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Exceptions
accolade ouverte attendue
lecture des champs: mot clef "dt_post" attendu
lecture du bloc statistique: mot clef "dt_post" attendu
mot clef inconnu
Reimplemented from Postraitement.
References Postraitement_base::readOn().
Get_champs_postraitables()
static std::vector< FieldInfo_t > & Postprocessing_IJK::Get_champs_postraitables () inline static
References champs_postraitables_.
Referenced by Probleme_FTD_IJK_base::Fill_postprocessable_fields().
set_param()
void Postprocessing_IJK::set_param (Param & param) override virtual
Reimplemented from Postraitement.
References Param::ajouter(), Param::ajouter_flag(), check_stats_, TRUST_Vector< _CLASSE_ >::dimensionner_force(), expression_dvitesse_analytique_, expression_grad2P_analytique_, expression_grad2U_analytique_, expression_grad2V_analytique_, expression_grad2W_analytique_, expression_gradP_analytique_, expression_gradU_analytique_, expression_gradV_analytique_, expression_gradW_analytique_, expression_pression_analytique_, expression_vitesse_analytique_, liste_post_instantanes_, nb_pas_dt_post_stats_bulles_, nb_pas_dt_post_stats_cisaillement_, nb_pas_dt_post_stats_plans_, nb_pas_dt_post_stats_rmf_, nb_pas_dt_post_thermals_probes_, post_par_paires_, postraiter_sous_pas_de_temps_, reset_reprise_integrated_, Postraitement_ft_lata::set_param(), t_debut_statistiques_, time_interval_post_, time_interval_post_stats_bulles_, time_interval_post_stats_cisaillement_, time_interval_post_stats_plans_, time_interval_post_stats_rmf_, and time_interval_post_thermals_probes_.
lire_entete_bloc_interface()
void Postprocessing_IJK::lire_entete_bloc_interface (Entree & is) override virtual
Reimplemented from Postraitement_ft_lata.
References Process::exit(), Process::je_suis_maitre(), Equation_base::le_nom(), Postraitement_base::mon_probleme, and Objet_U::que_suis_je().
lire_champs_a_postraiter()
int Postprocessing_IJK::lire_champs_a_postraiter (Entree & is, bool expect_acco) override virtual
Override to have a simpler logic than base class. We really want to retrieve names + location.
Reimplemented from Postraitement.
References register_one_field().
register_one_field()
void Postprocessing_IJK::register_one_field (const Motcle & fld_nam, const Motcle & loc)
References TRUST_List< _CLASSE_ >::add(), champs_postraitables_, IJK_Thermals::Fill_postprocessable_fields(), Nom::getString(), Postraitement::noms_champs_a_post_, scalar_post_fields_, and vect_post_fields_.
Referenced by lire_champs_a_postraiter(), and register_interface_field().
register_interface_field()
void Postprocessing_IJK::register_interface_field (const Motcle & nom_champ, const Motcle & loc_lu) override virtual
Override. Called from base class.
Reimplemented from Postraitement_ft_lata.
References Process::exit(), IJK_Interfaces::Fill_postprocessable_fields(), and register_one_field().
init()
void Postprocessing_IJK::init () override virtual
Initialise lata file and various other stuff
Reimplemented from Postraitement.
References alloc_fields(), alloc_velocity_and_co(), Postraitement::completer_sondes(), compute_extended_pressures(), Nom::finit_par(), init_integrated_and_ana(), Postraitement::nom_fich_, prepare_lata_and_stats(), and ref_ijk_ft_.
completer()
void Postprocessing_IJK::completer () inline override virtual
Reimplemented from Postraitement.
postraiter()
void Postprocessing_IJK::postraiter (int forcer) override virtual
Reimplemented from Postraitement.
References Schema_Temps_IJK_base::get_current_time(), Schema_Temps_IJK_base::get_timestep(), Postraitement::les_sondes_, Sondes::mettre_a_jour(), Postraitement::postraiter(), and ref_ijk_ft_.
postraiter_champs()
int Postprocessing_IJK::postraiter_champs () override virtual
Override from 'Postraitement' since the logic is simpler here
Reimplemented from Postraitement.
References champs_postraitables_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::data(), domaine_ijk_, IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::dumplata_scalar(), Process::exit(), field_post_idx_, IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_localisation(), IJK_Field_vector< T, N >::get_ptr(), IJK_Field_vector< T, N >::localisation(), Field_base::nature_du_champ(), Postraitement::nom_fich_, ref_ijk_ft_, and write_extra_mesh().
prepare_lata_and_stats()
void Postprocessing_IJK::prepare_lata_and_stats ()
Write the master lata file and prepare statistics and other stuff
References is_stats_plans_activated(), Postraitement::nom_fich_, pressure_, ref_ijk_ft_, t_debut_statistiques_, update_stat_ft(), and velocity_.
Referenced by init().
write_extra_mesh()
int Postprocessing_IJK::write_extra_mesh () override virtual
Override. Write the interface mesh if present, and the integer field 'COMPO_CONNEXE' on it.
Reimplemented from Postraitement.
References IJK_Interfaces::dumplata_ft_mesh(), Schema_Temps_IJK_base::get_tstep(), Nom::getChar(), Postraitement::nom_fich_, and ref_ijk_ft_.
Referenced by postraiter_champs().
resetTime()
void Postprocessing_IJK::resetTime (double time, std::string dirname) inline override virtual
When reseting time (see ProblemTrio::resetTime() documentation) we change the name of the postprocessing files with a new suffix. TODO: In the current setup suffix is "" meaning that the previous output are discarded. This might change in the future!
Reimplemented from Postraitement.
associer_probleme()
void Postprocessing_IJK::associer_probleme (const Probleme_FTD_IJK_base & ijk_ft)
References Statistiques_dns_ijk_FT::associer_probleme(), bk_tsi_ns_, d_velocity_, interfaces_, pressure_, ref_ijk_ft_, statistiques_FT_, thermals_, and velocity_.
Referenced by Probleme_FTD_IJK_base::completer().
associer_domaines()
void Postprocessing_IJK::associer_domaines (Domaine_IJK & dom_ijk, Domaine_IJK & dom_ft)
References Statistiques_dns_ijk::associer_domaine(), domaine_ft_, domaine_ijk_, and statistiques_FT_.
Referenced by Probleme_FTD_IJK_base::completer().
init_integrated_and_ana()
void Postprocessing_IJK::init_integrated_and_ana (bool reprise)
References Champs_compris_T< FIELD_TYPE >::ajoute_champ(), Champs_compris_IJK::ajoute_champ_vectoriel(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::allocate(), champs_compris_, check_stats_, Navier_Stokes_FTD_IJK::coef_immobilisation_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::data(), domaine_ijk_, Domaine_IJK::ELEM, Process::exit(), expression_grad2P_analytique_, expression_grad2U_analytique_, expression_grad2V_analytique_, expression_grad2W_analytique_, expression_gradP_analytique_, expression_gradU_analytique_, expression_gradV_analytique_, expression_gradW_analytique_, Navier_Stokes_FTD_IJK::fichier_reprise_vitesse_, fill_indic(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_domaine(), indicatrice_non_perturbe_, integrated_pressure_, integrated_timescale_, integrated_velocity_, interfaces_, is_post_required(), is_stats_plans_activated(), Domaine_base::le_nom(), pressure_, ref_ijk_ft_, reset_reprise_integrated_, and velocity_.
Referenced by init().
fill_indic()
void Postprocessing_IJK::fill_indic (bool reprise = 0)
References fichier_reprise_indicatrice_non_perturbe_, init_indicatrice_non_perturbe(), is_post_required(), is_stats_plans_activated(), and ref_ijk_ft_.
Referenced by init_integrated_and_ana().
initialise_stats()
void Postprocessing_IJK::initialise_stats (Domaine_IJK & splitting, ArrOfDouble & vol_bulles, const double vol_bulle_monodisperse)
References check_stats_, TRUST_Vector< _CLASSE_ >::dimensionner(), groups_statistiques_FT_, Statistiques_dns_ijk_FT::initialize(), interfaces_, ref_ijk_ft_, TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), statistiques_FT_, and t_debut_statistiques_.
Referenced by Navier_Stokes_FTD_IJK::initialise_ijk_fields().
init_indicatrice_non_perturbe()
void Postprocessing_IJK::init_indicatrice_non_perturbe ()
References fichier_reprise_indicatrice_non_perturbe_, IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_domaine(), indicatrice_non_perturbe_, interfaces_, is_post_required(), is_stats_plans_activated(), Domaine_base::le_nom(), ref_ijk_ft_, and reset_reprise_integrated_.
Referenced by fill_indic().
posttraiter_champs_instantanes()
void Postprocessing_IJK::posttraiter_champs_instantanes (const char * lata_name, double time, int time_iteration)
posttraiter_statistiques_plans()
void Postprocessing_IJK::posttraiter_statistiques_plans (double time)
References Statistiques::begin_count(), Option_IJK::DISABLE_DIPHASIQUE, Statistiques::end_count(), groups_statistiques_FT_, interfaces_, Process::je_suis_maitre(), Statistiques_dns_ijk_FT::postraiter(), Statistiques_dns_ijk_FT::postraiter_thermique(), Sortie_Fichier_base::precision(), Sortie_Fichier_base::setf(), statistiques_FT_, and Statistiques_dns_ijk::t_integration().
ecrire_statistiques_bulles()
void Postprocessing_IJK::ecrire_statistiques_bulles (int reset, const Nom & nom_cas, const double current_time) const
References Statistiques::begin_count(), Sortie_Fichier_base::close(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Option_IJK::DISABLE_DIPHASIQUE, Statistiques::end_count(), interfaces_, Process::je_suis_maitre(), Sortie_Fichier_base::ouvrir(), ref_ijk_ft_, TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), and thermals_.
ecrire_statistiques_cisaillement()
void Postprocessing_IJK::ecrire_statistiques_cisaillement (int reset, const Nom & nom_cas, const double current_time) const
References Statistiques::begin_count(), Navier_Stokes_FTD_IJK::calculer_vitesse_droite(), Navier_Stokes_FTD_IJK::calculer_vitesse_gauche(), Sortie_Fichier_base::close(), Option_IJK::DISABLE_DIPHASIQUE, Statistiques::end_count(), Process::je_suis_maitre(), Sortie_Fichier_base::ouvrir(), ref_ijk_ft_, and velocity_.
ecrire_statistiques_rmf()
void Postprocessing_IJK::ecrire_statistiques_rmf (int reset, const Nom & nom_cas, const double current_time) const
References Statistiques::begin_count(), Sortie_Fichier_base::close(), Option_IJK::DISABLE_DIPHASIQUE, Statistiques::end_count(), Process::je_suis_maitre(), Sortie_Fichier_base::ouvrir(), and ref_ijk_ft_.
update_stat_ft()
void Postprocessing_IJK::update_stat_ft (const double dt)
Methode qui met a jour l'indicatrice, les termes de repulsion ainsi que les termes interfaciaux : ai, kappa*ai, n(aux cellules)
Par definition, mettre igroup a -1 pour inclure toutes les bulles Dans ce cas, la methode met a jour l'ev de l'indicatrice au lieu de celui de interfaces_.groups_indicatrice_n_ns()[igroup]
Attention: de nombreux tableaux sont modifies par cette methode en sortie. Ils peuvent etre des tableaux de travail. Si on veut qu'il soient correctent pour la suite, il faut faire l'appel avec les champs globaux (incluant tous les groupes a la fin). Sinon, les champs en ai, normale ou grad_I ne contiendront qu'un groupe.
References ai_ns_, Statistiques::begin_count(), calculer_gradient_indicatrice(), Option_IJK::DISABLE_DIPHASIQUE, Statistiques::end_count(), groups_statistiques_FT_, interfaces_, is_post_required(), kappa_ai_ft_, kappa_ai_ns_, Statistiques::new_counter(), normale_cell_ft_, normale_cell_ns_, Redistribute_Field::redistribute(), Navier_Stokes_FTD_IJK::redistribute_from_splitting_ft_elem_, ref_ijk_ft_, scalar_post_fields_, statistiques_FT_, Navier_Stokes_FTD_IJK::transfer_ft_to_ns(), and Statistiques_dns_ijk_FT::update_stat().
Referenced by prepare_lata_and_stats(), and Probleme_FTD_IJK_base::solveTimeStep().
update_gradU_lambda2()
void Postprocessing_IJK::update_gradU_lambda2 (const bool need_lambda2 = false)
References Statistiques_dns_ijk::compute_and_store_gradU_cell(), dudx_, dudy_, dudz_, dvdx_, dvdy_, dvdz_, dwdx_, dwdy_, dwdz_, scalar_post_fields_, statistiques_FT_, and velocity_.
Referenced by get_IJK_field(), and get_update_lambda2_and_rot_and_Q().
get_update_lambda2_and_rot_and_Q()
void Postprocessing_IJK::get_update_lambda2_and_rot_and_Q ()
References Statistiques_dns_ijk_FT::get_IJK_field_vector(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), scalar_post_fields_, statistiques_FT_, update_gradU_lambda2(), and vect_post_fields_.
Referenced by get_IJK_field(), and get_IJK_field_vector().
activate_cut_cell()
void Postprocessing_IJK::activate_cut_cell () inline
References cut_cell_activated_.
Referenced by Probleme_FTD_IJK_cut_cell::initialize().
rebuilt_indic()
IJK_Field_double & Postprocessing_IJK::rebuilt_indic () inline
References rebuilt_indic_.
coords()
IJK_Field_vector3_double & Postprocessing_IJK::coords () inline
References coords_.
Referenced by Navier_Stokes_FTD_IJK::projeter().
integrated_timescale()
IJK_Field_double & Postprocessing_IJK::integrated_timescale () inline
References integrated_timescale_.
postraiter_sous_pas_de_temps()
bool Postprocessing_IJK::postraiter_sous_pas_de_temps () const inline
References postraiter_sous_pas_de_temps_.
post_par_paires()
int Postprocessing_IJK::post_par_paires () const inline
References post_par_paires_.
t_debut_statistiques()
double Postprocessing_IJK::t_debut_statistiques () const inline
References t_debut_statistiques_.
Referenced by Probleme_FTD_IJK_base::t_debut_statistiques().
sondes_demande()
int Postprocessing_IJK::sondes_demande () inline
References sondes_demande_.
is_post_required()
bool Postprocessing_IJK::is_post_required (const Motcle & nom) const
Was the field of name 'nom' requested for postprocessing?
References list_post_required_.
Referenced by alloc_fields(), alloc_velocity_and_co(), fill_indic(), fill_surface_force(), init_indicatrice_non_perturbe(), init_integrated_and_ana(), Navier_Stokes_FTD_IJK::preparer_calcul(), sauvegarder_post(), and update_stat_ft().
has_champ()
bool Postprocessing_IJK::has_champ (const Motcle & nom) const override virtual
Implements Champs_compris_IJK_interface.
References champs_compris_, Statistiques_dns_ijk::has_champ(), Champs_compris_T< FIELD_TYPE >::has_champ(), and statistiques_FT_.
Referenced by get_IJK_field(), and Probleme_FTD_IJK_base::has_champ().
has_champ_vectoriel()
bool Postprocessing_IJK::has_champ_vectoriel (const Motcle & nom) const override virtual
Implements Champs_compris_IJK_interface.
References champs_compris_, Champs_compris_IJK::has_champ_vectoriel(), Statistiques_dns_ijk::has_champ_vectoriel(), and statistiques_FT_.
Referenced by get_IJK_field_vector(), and Probleme_FTD_IJK_base::has_champ_vectoriel().
get_IJK_field_vector()
const IJK_Field_vector3_double & Postprocessing_IJK::get_IJK_field_vector (const Motcle & nom) override virtual
Implements Champs_compris_IJK_interface.
References champs_compris_, ecart_ana_, expression_vitesse_analytique_, Champs_compris_IJK::get_champ_vectoriel(), Statistiques_dns_ijk_FT::get_IJK_field_vector(), get_update_lambda2_and_rot_and_Q(), has_champ_vectoriel(), Statistiques_dns_ijk::has_champ_vectoriel(), integrated_pressure_, integrated_timescale_, integrated_velocity_, interfaces_, Process::je_suis_maitre(), Process::Journal(), Process::mp_sum(), Process::mp_sum_as_double(), pressure_, ref_ijk_ft_, statistiques_FT_, velocity_, and velocity_ana_.
Referenced by Probleme_FTD_IJK_base::get_IJK_field_vector().
get_IJK_field()
const IJK_Field_double & Postprocessing_IJK::get_IJK_field (const Motcle & nom) override virtual
Retrieve requested field for postprocessing, potentially updating it.
Implements Champs_compris_IJK_interface.
References champs_compris_, domaine_ft_, ecart_p_ana_, IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel(), expression_pression_analytique_, Champs_compris_T< FIELD_TYPE >::get_champ(), Statistiques_dns_ijk_FT::get_IJK_field(), Schema_RK3_IJK::get_rk_step(), Schema_Temps_IJK_base::get_timestep(), get_update_lambda2_and_rot_and_Q(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost(), has_champ(), Statistiques_dns_ijk::has_champ(), interfaces_, Process::je_suis_maitre(), Process::Journal(), Process::mp_sum(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), pressure_, ref_ijk_ft_, scalar_post_fields_, statistiques_FT_, and update_gradU_lambda2().
Referenced by Probleme_FTD_IJK_base::get_IJK_field().
Fill_postprocessable_fields()
void Postprocessing_IJK::Fill_postprocessable_fields (std::vector< FieldInfo_t > & chps) static
Referenced by Probleme_FTD_IJK_base::Fill_postprocessable_fields().
get_noms_champs_postraitables()
void Postprocessing_IJK::get_noms_champs_postraitables (Noms & noms, Option opt = NONE) const
References TRUST_Vector< _CLASSE_ >::add(), champs_compris_, Statistiques_dns_ijk::get_noms_champs_postraitables(), Champs_compris_IJK::liste_noms_compris(), Champs_compris_IJK::liste_noms_compris_vectoriel(), and statistiques_FT_.
Referenced by Probleme_FTD_IJK_base::get_noms_champs_postraitables().
get_IJK_flag()
const int & Postprocessing_IJK::get_IJK_flag (const Nom & nom) const
References Process::exit().
get_grad_I_ns()
IJK_Field_vector3_double & Postprocessing_IJK::get_grad_I_ns () inline
References grad_I_ns_.
Referenced by Navier_Stokes_FTD_IJK::fill_variable_source_and_potential_phi().
sauvegarder_post()
void Postprocessing_IJK::sauvegarder_post (const Nom & lata_name)
References indicatrice_non_perturbe_, integrated_pressure_, integrated_timescale_, integrated_velocity_, and is_post_required().
Referenced by Probleme_FTD_IJK_base::sauvegarder_probleme().
sauvegarder_post_maitre()
void Postprocessing_IJK::sauvegarder_post_maitre (const Nom & lata_name, SFichier & fichier) const
References groups_statistiques_FT_, interfaces_, statistiques_FT_, and Statistiques_dns_ijk::t_integration().
Referenced by Probleme_FTD_IJK_base::sauvegarder_probleme().
reprendre_post()
void Postprocessing_IJK::reprendre_post (Param & param)
References Param::ajouter(), groups_statistiques_FT_, and statistiques_FT_.
Referenced by Probleme_FTD_IJK_base::reprendre_probleme().
fill_op_conv()
void Postprocessing_IJK::fill_op_conv ()
References cell_op_conv_, Motcles::contient_(), d_velocity_, liste_post_instantanes_, and op_conv_.
Referenced by Navier_Stokes_FTD_IJK::calculer_dv().
fill_surface_force()
void Postprocessing_IJK::fill_surface_force (IJK_Field_vector3_double & the_field_you_know)
References cell_rho_Ssigma_, Motcles::contient_(), domaine_ijk_, is_post_required(), liste_post_instantanes_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), ref_ijk_ft_, and vect_post_fields_.
Referenced by Navier_Stokes_FTD_IJK::calculer_dv().
fill_surface_force_bis()
void Postprocessing_IJK::fill_surface_force_bis (const char * lata_name, double time, int time_iteration)
get_rho_Ssigma()
IJK_Field_vector3_double Postprocessing_IJK::get_rho_Ssigma ()
calculer_gradient_indicatrice()
void Postprocessing_IJK::calculer_gradient_indicatrice (const IJK_Field_double & indic)
References IJK_Field_vector< T, N >::echange_espace_virtuel(), and grad_I_ns_.
Referenced by update_stat_ft().
improved_initial_pressure_guess()
void Postprocessing_IJK::improved_initial_pressure_guess (bool imp)
References Motcles::contient_(), coords_, TRUST_Vector< _CLASSE_ >::dimensionner_force(), domaine_ijk_, and liste_post_instantanes_.
posttraiter_tous_champs_thermique()
void Postprocessing_IJK::posttraiter_tous_champs_thermique (Motcles & liste, const int idx) const
References TRUST_Vector< _CLASSE_ >::add().
posttraiter_tous_champs_energie()
void Postprocessing_IJK::posttraiter_tous_champs_energie (Motcles & liste, const int idx) const
References TRUST_Vector< _CLASSE_ >::add().
posttraiter_tous_champs_thermal()
void Postprocessing_IJK::posttraiter_tous_champs_thermal (Motcles & liste, const int idx) const
get_liste_post_instantanes()
Motcles Postprocessing_IJK::get_liste_post_instantanes () const inline
References liste_post_instantanes_.
Referenced by IJK_Thermal_base::associer(), IJK_One_Dimensional_Subproblems_Interfaces_Fields::associer(), and Navier_Stokes_FTD_IJK::calculer_dv().
alloc_fields()
void Postprocessing_IJK::alloc_fields ()
References ai_ns_, Champs_compris_T< FIELD_TYPE >::ajoute_champ(), Champs_compris_IJK::ajoute_champ_vectoriel(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::allocate(), ana_dUd_, ana_dVd_, ana_dWd_, ana_grad2Pc_, ana_grad2Pi_, ana_grad2Uc_, ana_grad2Ui_, ana_grad2Vc_, ana_grad2Vi_, ana_grad2Wc_, ana_grad2Wi_, ana_gradP_, champs_compris_, check_stats_, Option_IJK::DISABLE_DIPHASIQUE, domaine_ft_, domaine_ijk_, dudx_, dudy_, dudz_, dvdx_, dvdy_, dvdz_, dwdx_, dwdy_, dwdz_, ecart_ana_, ecart_p_ana_, Domaine_IJK::ELEM, Process::exit(), extended_pl_, extended_pl_ft_, extended_pressure_computed_, extended_pv_, extended_pv_ft_, interfaces_, is_post_required(), is_stats_plans_activated(), kappa_ai_ft_, kappa_ai_ns_, normale_cell_ft_, normale_cell_ns_, pressure_ft_, rebuilt_indic_, scalar_post_fields_, vect_post_fields_, and velocity_ana_.
Referenced by init().
alloc_velocity_and_co()
void Postprocessing_IJK::alloc_velocity_and_co ()
References Champs_compris_IJK::ajoute_champ_vectoriel(), cell_op_conv_, cell_rho_Ssigma_, champs_compris_, Motcles::contient_(), d_velocity_ana_, domaine_ft_, domaine_ijk_, grad_I_ft_, grad_I_ns_, is_post_required(), is_stats_plans_activated(), liste_post_instantanes_, op_conv_, ref_ijk_ft_, and vect_post_fields_.
Referenced by init().
compute_extended_pressures()
void Postprocessing_IJK::compute_extended_pressures ()
References Statistiques::begin_count(), domaine_ft_, IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel(), extended_pl_ft_, extended_pressure_computed_, extended_pv_ft_, Domaine_IJK::get_constant_delta(), Domaine_IJK::get_nb_elem_local(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost(), interfaces_, Process::Journal(), Process::me(), pressure_, pressure_ft_, Redistribute_Field::redistribute(), Navier_Stokes_FTD_IJK::redistribute_to_splitting_ft_elem_, ref_ijk_ft_, and TRUSTTab< _TYPE_, _SIZE_ >::resize().
Referenced by init(), and Probleme_FTD_IJK_base::solveTimeStep().
is_stats_bulles_activated()
bool Postprocessing_IJK::is_stats_bulles_activated () const
References nb_pas_dt_post_stats_bulles_, and time_interval_post_stats_bulles_.
is_stats_plans_activated()
bool Postprocessing_IJK::is_stats_plans_activated () const
References nb_pas_dt_post_stats_plans_, t_debut_statistiques_, and time_interval_post_stats_plans_.
Referenced by alloc_fields(), alloc_velocity_and_co(), fill_indic(), init_indicatrice_non_perturbe(), init_integrated_and_ana(), and prepare_lata_and_stats().
is_stats_cisaillement_activated()
bool Postprocessing_IJK::is_stats_cisaillement_activated () const
References nb_pas_dt_post_stats_cisaillement_, and time_interval_post_stats_cisaillement_.
is_stats_rmf_activated()
bool Postprocessing_IJK::is_stats_rmf_activated () const
References nb_pas_dt_post_stats_rmf_, and time_interval_post_stats_rmf_.
get_max_timestep_for_post()
double Postprocessing_IJK::get_max_timestep_for_post (double current_time) const
Compute the max possible timestep to use during the next iteration in order to not skip a time interval for postpro.
Parameters
current_time
Returns
max time step acceptable in order to land on a time for requirede post
References time_interval_post_, time_interval_post_stats_bulles_, time_interval_post_stats_cisaillement_, time_interval_post_stats_plans_, time_interval_post_stats_rmf_, and time_interval_post_thermals_probes_.
Referenced by Probleme_FTD_IJK_base::run().
compute_phase_pressures_based_on_poisson()
void Postprocessing_IJK::compute_phase_pressures_based_on_poisson (const int phase) protected
Friends And Related Function Documentation
Statistiques_dns_ijk_FT
friend class Statistiques_dns_ijk_FT friend
Member Data Documentation
info_obj
const Type_info Postprocessing_IJK::info_obj static
expression_gradP_analytique_
Noms Postprocessing_IJK::expression_gradP_analytique_
Referenced by init_integrated_and_ana(), and set_param().
expression_gradU_analytique_
Noms Postprocessing_IJK::expression_gradU_analytique_
Referenced by init_integrated_and_ana(), and set_param().
expression_gradV_analytique_
Noms Postprocessing_IJK::expression_gradV_analytique_
Referenced by init_integrated_and_ana(), and set_param().
expression_gradW_analytique_
Noms Postprocessing_IJK::expression_gradW_analytique_
Referenced by init_integrated_and_ana(), and set_param().
expression_grad2P_analytique_
Noms Postprocessing_IJK::expression_grad2P_analytique_
Referenced by init_integrated_and_ana(), and set_param().
expression_grad2U_analytique_
Noms Postprocessing_IJK::expression_grad2U_analytique_
Referenced by init_integrated_and_ana(), and set_param().
expression_grad2V_analytique_
Noms Postprocessing_IJK::expression_grad2V_analytique_
Referenced by init_integrated_and_ana(), and set_param().
expression_grad2W_analytique_
Noms Postprocessing_IJK::expression_grad2W_analytique_
Referenced by init_integrated_and_ana(), and set_param().
champs_postraitables_
std::vector< Postprocessing_IJK::FieldInfo_t > Postprocessing_IJK::champs_postraitables_ = {} static protected
list of fields that can be potentially postprocessed
Referenced by Get_champs_postraitables(), postraiter_champs(), and register_one_field().
field_post_idx_
std::vector<FieldIndex_t> Postprocessing_IJK::field_post_idx_ protected
Index in 'champs_postraitables_' of each of the requested field for post-processing:
first part is the index in champs_postraitables_
second part is the field component number (-1) when not relevant and flag indicating if interpolation will be needed:
Referenced by postraiter_champs().
list_post_required_
std::vector<Motcle> Postprocessing_IJK::list_post_required_ protected
Referenced by is_post_required().
champs_compris_
Champs_compris_IJK Postprocessing_IJK::champs_compris_ protected
the actual fields registered and managed by the post-processing part (=all the extra fields, not the main unknowns)
Referenced by alloc_fields(), alloc_velocity_and_co(), get_IJK_field(), get_IJK_field_vector(), get_noms_champs_postraitables(), has_champ(), has_champ_vectoriel(), and init_integrated_and_ana().
scalar_post_fields_
std::map<Motcle, IJK_Field_double> Postprocessing_IJK::scalar_post_fields_ protected
Referenced by alloc_fields(), get_IJK_field(), get_update_lambda2_and_rot_and_Q(), register_one_field(), update_gradU_lambda2(), and update_stat_ft().
vect_post_fields_
std::map<Motcle, IJK_Field_vector3_double> Postprocessing_IJK::vect_post_fields_ protected
Referenced by alloc_fields(), alloc_velocity_and_co(), fill_surface_force(), get_update_lambda2_and_rot_and_Q(), and register_one_field().
statistiques_FT_
Statistiques_dns_ijk_FT Postprocessing_IJK::statistiques_FT_ protected
Referenced by associer_domaines(), associer_probleme(), get_IJK_field(), get_IJK_field_vector(), get_noms_champs_postraitables(), get_update_lambda2_and_rot_and_Q(), has_champ(), has_champ_vectoriel(), initialise_stats(), posttraiter_statistiques_plans(), reprendre_post(), sauvegarder_post_maitre(), update_gradU_lambda2(), and update_stat_ft().
nb_pas_dt_post_thermals_probes_
int Postprocessing_IJK::nb_pas_dt_post_thermals_probes_ = -1 protected
Referenced by set_param().
nb_pas_dt_post_stats_bulles_
int Postprocessing_IJK::nb_pas_dt_post_stats_bulles_ = -1 protected
Referenced by is_stats_bulles_activated(), and set_param().
nb_pas_dt_post_stats_plans_
int Postprocessing_IJK::nb_pas_dt_post_stats_plans_ = -1 protected
Referenced by is_stats_plans_activated(), and set_param().
nb_pas_dt_post_stats_cisaillement_
int Postprocessing_IJK::nb_pas_dt_post_stats_cisaillement_ = -1 protected
Referenced by is_stats_cisaillement_activated(), and set_param().
nb_pas_dt_post_stats_rmf_
int Postprocessing_IJK::nb_pas_dt_post_stats_rmf_ = -1 protected
Referenced by is_stats_rmf_activated(), and set_param().
time_interval_post_
double Postprocessing_IJK::time_interval_post_ = -1.0 protected
Referenced by get_max_timestep_for_post(), and set_param().
time_interval_post_thermals_probes_
double Postprocessing_IJK::time_interval_post_thermals_probes_ = -1.0 protected
Referenced by get_max_timestep_for_post(), and set_param().
time_interval_post_stats_bulles_
double Postprocessing_IJK::time_interval_post_stats_bulles_ = -1.0 protected
Referenced by get_max_timestep_for_post(), is_stats_bulles_activated(), and set_param().
time_interval_post_stats_plans_
double Postprocessing_IJK::time_interval_post_stats_plans_ = -1.0 protected
Referenced by get_max_timestep_for_post(), is_stats_plans_activated(), and set_param().
time_interval_post_stats_cisaillement_
double Postprocessing_IJK::time_interval_post_stats_cisaillement_ = -1.0 protected
Referenced by get_max_timestep_for_post(), is_stats_cisaillement_activated(), and set_param().
time_interval_post_stats_rmf_
double Postprocessing_IJK::time_interval_post_stats_rmf_ = -1.0 protected
Referenced by get_max_timestep_for_post(), is_stats_rmf_activated(), and set_param().
liste_post_instantanes_
Motcles Postprocessing_IJK::liste_post_instantanes_ protected
Referenced by alloc_velocity_and_co(), fill_op_conv(), fill_surface_force(), get_liste_post_instantanes(), improved_initial_pressure_guess(), and set_param().
compteur_post_instantanes_
int Postprocessing_IJK::compteur_post_instantanes_ = 0 protected
postraiter_sous_pas_de_temps_
int Postprocessing_IJK::postraiter_sous_pas_de_temps_ = 0 protected
Referenced by postraiter_sous_pas_de_temps(), and set_param().
post_par_paires_
int Postprocessing_IJK::post_par_paires_ = 0 protected
Referenced by post_par_paires(), and set_param().
expression_vitesse_analytique_
Noms Postprocessing_IJK::expression_vitesse_analytique_ protected
Referenced by get_IJK_field_vector(), and set_param().
expression_pression_analytique_
Nom Postprocessing_IJK::expression_pression_analytique_ = "??" protected
Referenced by get_IJK_field(), and set_param().
expression_dvitesse_analytique_
Noms Postprocessing_IJK::expression_dvitesse_analytique_ protected
Referenced by set_param().
check_stats_
int Postprocessing_IJK::check_stats_ = 0 protected
Referenced by alloc_fields(), init_integrated_and_ana(), initialise_stats(), and set_param().
groups_statistiques_FT_
TRUST_Vector< Statistiques_dns_ijk_FT > Postprocessing_IJK::groups_statistiques_FT_ protected
Referenced by initialise_stats(), Postprocessing_IJK(), posttraiter_statistiques_plans(), reprendre_post(), sauvegarder_post_maitre(), and update_stat_ft().
t_debut_statistiques_
double Postprocessing_IJK::t_debut_statistiques_ = -1.0 protected
Referenced by initialise_stats(), is_stats_plans_activated(), prepare_lata_and_stats(), set_param(), and t_debut_statistiques().
integrated_velocity_
IJK_Field_vector3_double Postprocessing_IJK::integrated_velocity_ protected
Referenced by get_IJK_field_vector(), init_integrated_and_ana(), and sauvegarder_post().
integrated_pressure_
IJK_Field_double Postprocessing_IJK::integrated_pressure_ protected
Referenced by get_IJK_field_vector(), init_integrated_and_ana(), and sauvegarder_post().
indicatrice_non_perturbe_
IJK_Field_double Postprocessing_IJK::indicatrice_non_perturbe_ protected
Referenced by init_indicatrice_non_perturbe(), init_integrated_and_ana(), and sauvegarder_post().
integrated_timescale_
IJK_Field_double Postprocessing_IJK::integrated_timescale_ protected
Referenced by get_IJK_field_vector(), init_integrated_and_ana(), integrated_timescale(), and sauvegarder_post().
reset_reprise_integrated_
bool Postprocessing_IJK::reset_reprise_integrated_ = false protected
Referenced by init_indicatrice_non_perturbe(), init_integrated_and_ana(), and set_param().
fichier_reprise_integrated_velocity_
Nom Postprocessing_IJK::fichier_reprise_integrated_velocity_ = "??" protected
fichier_reprise_integrated_pressure_
Nom Postprocessing_IJK::fichier_reprise_integrated_pressure_ = "??" protected
fichier_reprise_indicatrice_non_perturbe_
Nom Postprocessing_IJK::fichier_reprise_indicatrice_non_perturbe_ = "??" protected
Referenced by fill_indic(), and init_indicatrice_non_perturbe().
fichier_reprise_integrated_timescale_
Nom Postprocessing_IJK::fichier_reprise_integrated_timescale_ = "??" protected
coords_
IJK_Field_vector3_double Postprocessing_IJK::coords_ protected
Referenced by coords(), and improved_initial_pressure_guess().
velocity_ana_
IJK_Field_vector3_double Postprocessing_IJK::velocity_ana_ protected
Referenced by alloc_fields(), and get_IJK_field_vector().
ecart_ana_
IJK_Field_vector3_double Postprocessing_IJK::ecart_ana_ protected
Referenced by alloc_fields(), and get_IJK_field_vector().
op_conv_
IJK_Field_vector3_double Postprocessing_IJK::op_conv_ protected
Referenced by alloc_velocity_and_co(), and fill_op_conv().
cell_op_conv_
IJK_Field_vector3_double Postprocessing_IJK::cell_op_conv_ protected
Referenced by alloc_velocity_and_co(), and fill_op_conv().
cell_rho_Ssigma_
IJK_Field_vector3_double Postprocessing_IJK::cell_rho_Ssigma_ protected
Referenced by alloc_velocity_and_co(), and fill_surface_force().
d_velocity_ana_
IJK_Field_vector3_double Postprocessing_IJK::d_velocity_ana_ protected
Referenced by alloc_velocity_and_co().
ecart_p_ana_
IJK_Field_double Postprocessing_IJK::ecart_p_ana_ protected
Referenced by alloc_fields(), and get_IJK_field().
grad_I_ft_
IJK_Field_vector3_double Postprocessing_IJK::grad_I_ft_ protected
Referenced by alloc_velocity_and_co().
rebuilt_indic_
IJK_Field_double Postprocessing_IJK::rebuilt_indic_ protected
Referenced by alloc_fields(), and rebuilt_indic().
extended_pressure_computed_
int Postprocessing_IJK::extended_pressure_computed_ = 0 protected
Referenced by alloc_fields(), compute_extended_pressures(), and Statistiques_dns_ijk_FT::update_stat().
pressure_ft_
IJK_Field_double Postprocessing_IJK::pressure_ft_ protected
Referenced by alloc_fields(), and compute_extended_pressures().
extended_pl_ft_
IJK_Field_double Postprocessing_IJK::extended_pl_ft_ protected
Referenced by alloc_fields(), and compute_extended_pressures().
extended_pv_ft_
IJK_Field_double Postprocessing_IJK::extended_pv_ft_ protected
Referenced by alloc_fields(), and compute_extended_pressures().
extended_pl_
IJK_Field_double Postprocessing_IJK::extended_pl_ protected
Referenced by alloc_fields(), and Statistiques_dns_ijk_FT::update_stat().
extended_pv_
IJK_Field_double Postprocessing_IJK::extended_pv_ protected
Referenced by alloc_fields(), and Statistiques_dns_ijk_FT::update_stat().
kappa_ai_ft_
IJK_Field_double Postprocessing_IJK::kappa_ai_ft_ protected
Referenced by alloc_fields(), and update_stat_ft().
normale_cell_ft_
IJK_Field_vector3_double Postprocessing_IJK::normale_cell_ft_ protected
Referenced by alloc_fields(), and update_stat_ft().
ai_ns_
IJK_Field_double Postprocessing_IJK::ai_ns_ protected
Referenced by alloc_fields(), and update_stat_ft().
kappa_ai_ns_
IJK_Field_double Postprocessing_IJK::kappa_ai_ns_ protected
Referenced by alloc_fields(), and update_stat_ft().
normale_cell_ns_
IJK_Field_vector3_double Postprocessing_IJK::normale_cell_ns_ protected
Referenced by alloc_fields(), and update_stat_ft().
dudx_
IJK_Field_double Postprocessing_IJK::dudx_ protected
Referenced by alloc_fields(), and update_gradU_lambda2().
dvdy_
IJK_Field_double Postprocessing_IJK::dvdy_ protected
Referenced by alloc_fields(), and update_gradU_lambda2().
dwdx_
IJK_Field_double Postprocessing_IJK::dwdx_ protected
Referenced by alloc_fields(), and update_gradU_lambda2().
dudz_
IJK_Field_double Postprocessing_IJK::dudz_ protected
Referenced by alloc_fields(), and update_gradU_lambda2().
dvdz_
IJK_Field_double Postprocessing_IJK::dvdz_ protected
Referenced by alloc_fields(), and update_gradU_lambda2().
dwdz_
IJK_Field_double Postprocessing_IJK::dwdz_ protected
Referenced by alloc_fields(), and update_gradU_lambda2().
grad_I_ns_
IJK_Field_vector3_double Postprocessing_IJK::grad_I_ns_ protected
Referenced by alloc_velocity_and_co(), calculer_gradient_indicatrice(), and get_grad_I_ns().
ana_gradP_
IJK_Field_vector3_double Postprocessing_IJK::ana_gradP_ protected
Referenced by alloc_fields().
ana_dUd_
IJK_Field_vector3_double Postprocessing_IJK::ana_dUd_ protected
Referenced by alloc_fields().
ana_dVd_
IJK_Field_vector3_double Postprocessing_IJK::ana_dVd_ protected
Referenced by alloc_fields().
ana_dWd_
IJK_Field_vector3_double Postprocessing_IJK::ana_dWd_ protected
Referenced by alloc_fields().
ana_grad2Pi_
IJK_Field_vector3_double Postprocessing_IJK::ana_grad2Pi_ protected
Referenced by alloc_fields().
ana_grad2Pc_
IJK_Field_vector3_double Postprocessing_IJK::ana_grad2Pc_ protected
Referenced by alloc_fields().
ana_grad2Ui_
IJK_Field_vector3_double Postprocessing_IJK::ana_grad2Ui_ protected
Referenced by alloc_fields().
ana_grad2Uc_
IJK_Field_vector3_double Postprocessing_IJK::ana_grad2Uc_ protected
Referenced by alloc_fields().
ana_grad2Vi_
IJK_Field_vector3_double Postprocessing_IJK::ana_grad2Vi_ protected
Referenced by alloc_fields().
ana_grad2Vc_
IJK_Field_vector3_double Postprocessing_IJK::ana_grad2Vc_ protected
Referenced by alloc_fields().
ana_grad2Wi_
IJK_Field_vector3_double Postprocessing_IJK::ana_grad2Wi_ protected
Referenced by alloc_fields().
ana_grad2Wc_
IJK_Field_vector3_double Postprocessing_IJK::ana_grad2Wc_ protected
Referenced by alloc_fields().
IFd_source_spectraleX_
IJK_Field_double Postprocessing_IJK::IFd_source_spectraleX_ protected
AOD_source_spectraleX_
IJK_Field_double Postprocessing_IJK::AOD_source_spectraleX_ protected
source_spectraleY_
IJK_Field_double Postprocessing_IJK::source_spectraleY_ protected
source_spectraleZ_
IJK_Field_double Postprocessing_IJK::source_spectraleZ_ protected
dudy_
IJK_Field_double Postprocessing_IJK::dudy_ protected
Referenced by alloc_fields(), and update_gradU_lambda2().
dvdx_
IJK_Field_double Postprocessing_IJK::dvdx_ protected
Referenced by alloc_fields(), and update_gradU_lambda2().
dwdy_
IJK_Field_double Postprocessing_IJK::dwdy_ protected
Referenced by alloc_fields(), and update_gradU_lambda2().
cell_velocity_
IJK_Field_vector3_double Postprocessing_IJK::cell_velocity_ protected
cell_bk_tsi_ns_
IJK_Field_vector3_double Postprocessing_IJK::cell_bk_tsi_ns_ protected
cell_grad_p_
IJK_Field_vector3_double Postprocessing_IJK::cell_grad_p_ protected
cell_source_interface_
IJK_Field_vector3_double Postprocessing_IJK::cell_source_interface_ protected
cell_backup_source_interface_
IJK_Field_vector3_double Postprocessing_IJK::cell_backup_source_interface_ protected
cell_repulsion_interface_
IJK_Field_vector3_double Postprocessing_IJK::cell_repulsion_interface_ protected
sondes_demande_
int Postprocessing_IJK::sondes_demande_ = 0 protected
Referenced by sondes_demande().
ref_ijk_ft_
TRUST_Ref< Probleme_FTD_IJK_base *> Postprocessing_IJK::ref_ijk_ft_ protected
Referenced by alloc_velocity_and_co(), associer_probleme(), compute_extended_pressures(), ecrire_statistiques_bulles(), ecrire_statistiques_cisaillement(), ecrire_statistiques_rmf(), fill_indic(), fill_surface_force(), get_IJK_field(), get_IJK_field_vector(), init(), init_indicatrice_non_perturbe(), init_integrated_and_ana(), initialise_stats(), postraiter(), postraiter_champs(), prepare_lata_and_stats(), update_stat_ft(), and write_extra_mesh().
interfaces_
TRUST_Ref< IJK_Interfaces *> Postprocessing_IJK::interfaces_ protected
Referenced by alloc_fields(), associer_probleme(), compute_extended_pressures(), ecrire_statistiques_bulles(), get_IJK_field(), get_IJK_field_vector(), init_indicatrice_non_perturbe(), init_integrated_and_ana(), initialise_stats(), posttraiter_statistiques_plans(), sauvegarder_post_maitre(), and update_stat_ft().
pressure_
TRUST_Ref< IJK_Field_double *> Postprocessing_IJK::pressure_ protected
Referenced by associer_probleme(), compute_extended_pressures(), get_IJK_field(), get_IJK_field_vector(), init_integrated_and_ana(), and prepare_lata_and_stats().
velocity_
TRUST_Ref< IJK_Field_vector3_double *> Postprocessing_IJK::velocity_ protected
Referenced by associer_probleme(), ecrire_statistiques_cisaillement(), get_IJK_field_vector(), init_integrated_and_ana(), prepare_lata_and_stats(), and update_gradU_lambda2().
bk_tsi_ns_
TRUST_Ref< IJK_Field_vector3_double *> Postprocessing_IJK::bk_tsi_ns_ protected
Referenced by associer_probleme().
source_interface_ft_
IJK_Field_vector3_double Postprocessing_IJK::source_interface_ft_ protected
source_interface_ns_
IJK_Field_vector3_double Postprocessing_IJK::source_interface_ns_ protected
repulsion_interface_ns_
IJK_Field_vector3_double Postprocessing_IJK::repulsion_interface_ns_ protected
d_velocity_
TRUST_Ref< IJK_Field_vector3_double *> Postprocessing_IJK::d_velocity_ protected
Referenced by associer_probleme(), and fill_op_conv().
domaine_ijk_
TRUST_Ref< Domaine_IJK *> Postprocessing_IJK::domaine_ijk_ protected
Referenced by alloc_fields(), alloc_velocity_and_co(), associer_domaines(), fill_surface_force(), improved_initial_pressure_guess(), init_integrated_and_ana(), and postraiter_champs().
domaine_ft_
TRUST_Ref< Domaine_IJK *> Postprocessing_IJK::domaine_ft_ protected
Referenced by alloc_fields(), alloc_velocity_and_co(), associer_domaines(), compute_extended_pressures(), and get_IJK_field().
thermals_
TRUST_Ref< IJK_Thermals *> Postprocessing_IJK::thermals_ protected
Referenced by associer_probleme(), and ecrire_statistiques_bulles().
first_step_thermals_post_
int Postprocessing_IJK::first_step_thermals_post_ =0 protected
poisson_solver_post_
Multigrille_Adrien Postprocessing_IJK::poisson_solver_post_ protected
cut_cell_activated_
int Postprocessing_IJK::cut_cell_activated_ = 0 protected
Referenced by activate_cut_cell().