TrioCFD: Milieu_base Class Reference
Milieu_base Class Reference
#include <Milieu_base.h>
Public Member Functions
virtual int a_gravite () const
int associer_ (Objet_U &) override
virtual void associer_gravite (const Champ_Don_base &)
virtual Champ_Don_base & beta_t ()
virtual const Champ_Don_base & beta_t () const
virtual Champ_Don_base & capacite_calorifique ()
virtual const Champ_Don_base & capacite_calorifique () const
virtual Champ_Don_base & conductivite ()
virtual const Champ_Don_base & conductivite () const
virtual Champ_Don_base & diffusivite ()
virtual const Champ_Don_base & diffusivite () const
virtual int est_deja_associe ()
const Type_info * get_info () const override
virtual Champ_Don_base & gravite ()
virtual const Champ_Don_base & gravite () const
const Nom & le_nom () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual Champ_base & masse_volumique ()
virtual const Champ_base & masse_volumique () const
void nommer (const Nom &) override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
virtual void calculer_alpha ()
void ecrire (Sortie &) const
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
Elle regroupe les fonctionnalites (communes) et les proprietes physiques
d'un milieu. Cette classe contient les principaux champs donnees
caracterisant le milieu:
   - masse volumique       (rho)
   - diffusivite           (alpha)
   - conductivite          (lambda)
   - capacite calorifique  (Cp)
   - dilatabilite          (beta_th)
See also
Milieu Solide Fluide_Incompressible Constituant, Classe abstraite dont tous les milieux physiques doivent deriver., Methodes abstraites:, void tester_champs_lus(), void mettre_a_jour(double temps), void initialiser()
Member Enumeration Documentation
Type_rayo
enum Milieu_base::Type_rayo protected
Enumerator
NONRAYO
TRANSP
SEMITRANSP
Constructor & Destructor Documentation
~Milieu_base()
Milieu_base::~Milieu_base () override
Milieu_base()
Milieu_base::Milieu_base ()
References indic_rayo_, and NONRAYO.
Member Function Documentation
info()
const Type_info * Milieu_base::info () static
get_info()
const Type_info * Milieu_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
Reimplemented in Fluide_eau_c3_gaz, Fluide_eau_c3_liquide, Fluide_R12_c1_gaz, Fluide_R12_c1_liquide, Solid_Particle_arbitrary, Solid_Particle_base, Solid_Particle_sphere, Solid_Particle_spheroid, Fluide_Diphasique_IJK, Fluide_Diphasique, Fluide_Dilatable_base, Espece, Fluide_Quasi_Compressible, Fluide_Weakly_Compressible, Constituant, Fluide_base, Fluide_Incompressible, Fluide_Ostwald, Fluide_MUSIG, Fluide_reel_base, Fluide_sodium_gaz, Fluide_sodium_liquide, Fluide_stiffened_gas, Milieu_composite, Milieu_MUSIG, Fluide_generique_CoolProp, Fluide_generique_EOS, Fluide_generique_TPPI_base, and Solide.
self_cast() [1/2]
Milieu_base & Milieu_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Milieu_base & Milieu_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Milieu_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
Reimplemented in Fluide_eau_c3_gaz, Fluide_eau_c3_liquide, Fluide_R12_c1_gaz, Fluide_R12_c1_liquide, Solid_Particle_arbitrary, Solid_Particle_base, Solid_Particle_sphere, Solid_Particle_spheroid, Fluide_Diphasique_IJK, Fluide_Diphasique, Fluide_Dilatable_base, Espece, Fluide_Quasi_Compressible, Fluide_Weakly_Compressible, Constituant, Fluide_base, Fluide_Incompressible, Fluide_Ostwald, Fluide_MUSIG, Fluide_reel_base, Fluide_sodium_gaz, Fluide_sodium_liquide, Fluide_stiffened_gas, Milieu_composite, Milieu_MUSIG, Fluide_generique_CoolProp, Fluide_generique_EOS, Fluide_generique_TPPI_base, and Solide.
References ecrire().
Referenced by Solide::printOn().
readOn()
Entree & Milieu_base::readOn (Entree & is) override protected virtual
Lecture d'un milieu sur un flot d'entree.
Format: { grandeur_physique type_champ bloc de lecture du champ } cf set_param method to know the understood keywords cf Param class to know possible options reading
Parameters
(Entree& is) le flot d'entree pour la lecture des parametres du milieu
Returns
(Entree&) le flot d'entree modifie
Exceptions
accolade ouvrante attendue
Reimplemented from Objet_U.
Reimplemented in Fluide_eau_c3_gaz, Fluide_eau_c3_liquide, Fluide_R12_c1_gaz, Fluide_R12_c1_liquide, Solid_Particle_arbitrary, Solid_Particle_base, Solid_Particle_sphere, Solid_Particle_spheroid, Fluide_Diphasique_IJK, Fluide_Diphasique, Fluide_Dilatable_base, Espece, Fluide_Quasi_Compressible, Fluide_Weakly_Compressible, Constituant, Fluide_base, Fluide_Incompressible, Fluide_Ostwald, Fluide_MUSIG, Fluide_reel_base, Fluide_sodium_gaz, Fluide_sodium_liquide, Fluide_stiffened_gas, Milieu_composite, Milieu_MUSIG, Fluide_generique_CoolProp, Fluide_generique_EOS, Fluide_generique_TPPI_base, and Solide.
References TRUST_List< _CLASSE_ >::add(), ch_alpha_, ch_beta_th_, ch_Cp_, ch_diametre_hyd_, ch_g_, ch_lambda_, ch_porosites_, champs_don_, check_gravity_vector(), creer_champs_non_lus(), Param::lire_avec_accolades_depuis(), Objet_U_ptr::non_nul(), Objet_U::que_suis_je(), set_param(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by Fluide_Diphasique::readOn(), Espece::readOn(), Constituant::readOn(), Fluide_base::readOn(), and Solide::readOn().
lire_motcle_non_standard()
int Milieu_base::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Objet_U.
Reimplemented in Fluide_Dilatable_base, Fluide_Quasi_Compressible, Solide, and Constituant.
Referenced by Fluide_Dilatable_base::lire_motcle_non_standard(), Solide::lire_motcle_non_standard(), and Constituant::lire_motcle_non_standard().
associer_()
int Milieu_base::associer_ (Objet_U & ob) override virtual
Associe la gravite en controlant dynamiquement le type de l'objet a associer.
Si l'objet est du type OWN_PTR(Champ_Don_base) ou Champ_Don_base l'association reussit, sinon elle echoue.
Parameters
(Objet_U& ob) un objet TRUST devant representer un champ de gravite
Returns
(int) 1 si l'association a reussie, 0 sinon.
Reimplemented from Objet_U.
References associer_gravite().
nommer()
void Milieu_base::nommer (const Nom &) override virtual
Donne un nom a l'Objet_U Methode virtuelle a surcharger.
Parameters
(const Nom&) le nom a affectuer a l'Objet_U
Reimplemented from Objet_U.
References nom_.
le_nom()
const Nom & Milieu_base::le_nom () const override virtual
Donne le nom de l'Objet_U Methode a surcharger : renvoie "neant" dans cette implementation.
Returns
(Nom&) le nom de l'Objet_U
Reimplemented from Objet_U.
References nom_.
Referenced by Milieu_MUSIG::has_carrier_gas(), Milieu_MUSIG::has_carrier_liquid(), Milieu_MUSIG::has_dispersed_gas(), and Milieu_MUSIG::has_dispersed_liquid().
porosite_elem() [1/3]
DoubleVect & Milieu_base::porosite_elem () inline
References ch_porosites_, and Champ_Don_base::valeurs().
Referenced by Op_Conv_VEF_Face::ajouter(), Op_Diff_VEF_Anisotrope_Face::ajouter(), Op_Diff_VEF_Face::ajouter(), Op_Diff_VEF_Face_Stab::ajouter(), Op_Diff_VEFP1NCP1B_Face::ajouter(), Op_Dift_Stab_VEF_Face::ajouter(), Op_Dift_VEF_Face::ajouter(), Op_Diff_PolyMAC_Face::ajouter(), Source_Transport_Fluctuation_Temperature_VDF_Elem::ajouter(), Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::ajouter(), Source_Transport_Fluctuation_Temperature_W_VDF_Elem::ajouter(), Perte_Charge_PolyMAC::ajouter(), Op_Grad_PolyMAC_P0_Face::ajouter_blocs(), Op_Grad_PolyMAC_P0P1NC_Face::ajouter_blocs(), Coalescence_bulles_1groupe_PolyMAC_P0::ajouter_blocs(), Coalescence_bulles_2groupes_PolyMAC_P0::ajouter_blocs(), Flux_2groupes_PolyMAC_P0::ajouter_blocs(), Rupture_bulles_1groupe_PolyMAC_P0::ajouter_blocs(), Rupture_bulles_2groupes_PolyMAC_P0::ajouter_blocs(), Variation_rho::ajouter_blocs(), Source_injection_masse_base::ajouter_blocs(), Diffusion_croisee_echelle_temp_taux_diss_turb_PolyMAC_P0::ajouter_blocs(), Diffusion_supplementaire_echelle_temp_turb_PolyMAC_P0::ajouter_blocs(), Dissipation_WIT_PolyMAC_P0::ajouter_blocs(), Production_echelle_temp_taux_diss_turb_PolyMAC_P0::ajouter_blocs(), Production_energie_cin_turb_PolyMAC_P0::ajouter_blocs(), Production_HZDR_PolyMAC_P0::ajouter_blocs(), Production_WIT_PolyMAC_P0::ajouter_blocs(), Source_BIF_PolyMAC_P0::ajouter_blocs(), Source_Dissipation_HZDR_PolyMAC_P0::ajouter_blocs(), Source_Dissipation_echelle_temp_taux_diss_turb::ajouter_blocs(), Source_Dissipation_energie_cin_turb::ajouter_blocs(), Diffusion_croisee_echelle_temp_taux_diss_turb_VDF::ajouter_blocs(), Diffusion_supplementaire_echelle_temp_turb_VDF::ajouter_blocs(), Production_echelle_temp_taux_diss_turb_VDF::ajouter_blocs(), Production_energie_cin_turb_VDF::ajouter_blocs(), Correction_Antal_PolyMAC_P0::ajouter_blocs(), Correction_Tomiyama_PolyMAC_P0::ajouter_blocs(), Dispersion_bulles_PolyMAC_P0::ajouter_blocs(), Frottement_interfacial_PolyMAC_P0::ajouter_blocs(), Portance_interfaciale_PolyMAC_P0::ajouter_blocs(), Terme_Boussinesq_PolyMAC_Face::ajouter_blocs(), Terme_Source_Decroissance_Radioactive_Elem_PolyMAC::ajouter_blocs(), Terme_Source_Qdm_Face_PolyMAC_P0P1NC::ajouter_blocs(), Source_Flux_interfacial_base::ajouter_blocs(), Source_Travail_pression_Elem_base::ajouter_blocs(), Op_Conv_Amont_VPoly_VDF_Face::ajouter_blocs(), Masse_PolyMAC_P0_Face::ajouter_blocs(), Force_Tchen_PolyMAC_P0::ajouter_blocs_aux(), Correction_Lubchenko_PolyMAC_P0::ajouter_blocs_BIF(), Correction_Lubchenko_PolyMAC_P0::ajouter_blocs_disp(), Correction_Lubchenko_PolyMAC_P0::ajouter_blocs_lift(), Op_Conv_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution(), Op_Diff_VEF_Face_Stab::ajouter_contribution(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face_Stab::ajouter_contribution_multi_scalaire(), Masse_PolyMAC_Elem::ajouter_masse(), Masse_PolyMAC_Face::ajouter_masse(), Op_Conv_ALE_VEF::ajouterALE(), Masse_PolyMAC_Elem::appliquer_impl(), Masse_PolyMAC_P0_Face::appliquer_impl(), Masse_VDF_Elem::appliquer_impl(), Assembleur_P_PolyMAC_P0::assembler_continuite(), Assembleur_P_PolyMAC_P0P1NC::assembler_continuite(), Assembleur_P_PolyMAC_P0P1NC::assembler_mat(), Op_Conv_EF_Stab_PolyMAC_P0_Face::calculer_dt_stab(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::calculer_dt_stab(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Face::calculer_dt_stab(), Op_Diff_PolyMAC_P0_Elem::calculer_dt_stab(), Op_Diff_PolyMAC_P0_Face::calculer_dt_stab(), Op_Diff_PolyMAC_P0P1NC_Elem::calculer_dt_stab(), Op_Diff_PolyMAC_P0P1NC_Face::calculer_dt_stab(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab(), Domaine_EF::calculer_IPhi(), Domaine_EF_axi::calculer_IPhi(), Domaine_EF::calculer_volumes_sommets(), Op_Diff_PolyMAC_Face::contribuer_a_avec(), Perte_Charge_PolyMAC::contribuer_a_avec(), Op_Dift_Stab_VEF_Face::contribuer_a_avec(), Op_Dift_VEF_Face::contribuer_a_avec(), Op_Dift_VEF_Face::contribuer_au_second_membre(), Champ_val_tot_sur_vol_VDF::eval_contrib_loc(), Champ_Face_PolyMAC::init_va(), Champ_Face_PolyMAC_P0::init_ve2(), Champ_Face_PolyMAC::interp_ve(), Champ_Face_PolyMAC_P0P1NC::interp_ve(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::mettre_a_jour(), Op_Conv_VDF_base::mettre_a_jour(), Assembleur_P_PolyMAC_P0P1NC::norme_continuite(), Op_Conv_VEF_Face::remplir_fluent(), Op_Diff_VEFP1NCP1B_Face::test(), Op_Diff_PolyMAC_P0_base::update_nu(), Op_Diff_PolyMAC_P0P1NC_base::update_nu(), and Champ_Face_PolyMAC_P0::update_ve().
porosite_elem() [2/3]
const DoubleVect & Milieu_base::porosite_elem () const inline
References ch_porosites_, and Champ_Don_base::valeurs().
porosite_elem() [3/3]
double Milieu_base::porosite_elem (const int i) const inline
References ch_porosites_, and Champ_Don_base::valeurs().
has_porosites()
bool Milieu_base::has_porosites () const inline
References ch_porosites_, and Objet_U_ptr::non_nul().
porosite_face() [1/3]
DoubleVect & Milieu_base::porosite_face () inline
References porosite_face_.
Referenced by Op_Div_PolyMAC::ajouter(), Op_Div_PolyMAC_P0::ajouter(), Op_Conv_Amont_old_VEF_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Centre_EF_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_EF_VEF_P1NC::ajouter(), Op_Conv_EF_VEF_P1NC_Stab::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_Muscl_New_VEF_Face::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Diff_VEF_Anisotrope_Face::ajouter(), Op_Diff_VEF_Face::ajouter(), Op_Diff_VEF_Face_Stab::ajouter(), Op_Diff_VEFP1NCP1B_Face::ajouter(), Op_Dift_Stab_VEF_Face::ajouter(), Op_Dift_VEF_Face::ajouter(), Op_Dift_VEF_Face_Q1::ajouter(), Op_Div_VEFP1B_Elem::ajouter(), SourceFiltree_FT_disc_VEF_P1NC::ajouter(), Terme_Boussinesq_Sensibility_VEFPreP1B_Face::ajouter(), Source_Transport_Fluctuation_Temperature_VDF_Elem::ajouter(), Source_Transport_Flux_Chaleur_Turbulente_VDF_Face::ajouter(), Perte_Charge_PolyMAC::ajouter(), Perte_Charge_Singuliere_PolyMAC_Face::ajouter(), Source_Generique_Face_PolyMAC::ajouter(), Source_Generique_Face_PolyMAC_P0P1NC::ajouter(), Terme_Source_Qdm_Face_PolyMAC::ajouter(), Terme_Source_Canal_perio_VEF_P1NC::ajouter(), Terme_Source_Canal_RANS_LES_VEF_Face::ajouter(), Perte_Charge_Reguliere_VEF_P1NC::ajouter(), Perte_Charge_Singuliere_VEF_Face::ajouter(), Perte_Charge_VEF::ajouter(), Source_Generique_VEF::ajouter(), Terme_Boussinesq_VEF_Face::ajouter(), Terme_Boussinesq_VEFPreP1B_Face::ajouter(), Terme_Source_Acceleration_VEF_Face::ajouter(), Terme_Source_Qdm_lambdaup_VEF_Face::ajouter(), Perte_Charge_Reguliere_VDF_Face::ajouter_(), Op_Grad_VEF_P1B_Face::ajouter_aretes(), Tenseur_Reynolds_Externe_VDF_Face::ajouter_blocs(), Terme_Source_Canal_perio_VDF_Face::ajouter_blocs(), Terme_Source_Canal_RANS_LES_VDF_Face::ajouter_blocs(), Perte_Charge_Singuliere_VDF_Face::ajouter_blocs(), Source_Generique_VDF_Face::ajouter_blocs(), Terme_Boussinesq_VDF_Face::ajouter_blocs(), Terme_Source_Acceleration_VDF_Face::ajouter_blocs(), Terme_Source_Coriolis_VDF_Face::ajouter_blocs(), Terme_Source_inc_th_VDF_Face::ajouter_blocs(), Terme_Source_inc_VDF_Face::ajouter_blocs(), Terme_Source_Qdm_VDF_Face::ajouter_blocs(), Op_Grad_PolyMAC_P0_Face::ajouter_blocs(), Correction_Antal_PolyMAC_P0::ajouter_blocs(), Correction_Tomiyama_PolyMAC_P0::ajouter_blocs(), Dispersion_bulles_PolyMAC_P0::ajouter_blocs(), Frottement_interfacial_PolyMAC_P0::ajouter_blocs(), Portance_interfaciale_PolyMAC_P0::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::ajouter_blocs(), DP_Impose_PolyMAC_Face::ajouter_blocs(), Perte_Charge_Singuliere_PolyMAC_P0P1NC_Face::ajouter_blocs(), Terme_Boussinesq_PolyMAC_Face::ajouter_blocs(), Terme_Source_Qdm_Face_PolyMAC_P0P1NC::ajouter_blocs(), Source_Force_Tchen_base::ajouter_blocs(), Source_Travail_pression_Elem_base::ajouter_blocs(), Correction_Antal_VDF::ajouter_blocs(), Dispersion_bulles_VDF::ajouter_blocs(), Frottement_interfacial_VDF::ajouter_blocs(), Portance_interfaciale_VDF::ajouter_blocs(), DP_Impose_VEF_Face::ajouter_blocs(), Masse_PolyMAC_P0_Face::ajouter_blocs(), Masse_VDF_Face::ajouter_blocs(), Correction_Lubchenko_PolyMAC_P0::ajouter_blocs_disp(), Op_Div_PolyMAC_P0P1NC::ajouter_blocs_ext(), Correction_Lubchenko_PolyMAC_P0::ajouter_blocs_lift(), Op_Conv_Amont_old_VEF_Face::ajouter_contribution(), Op_Conv_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Face::ajouter_contribution(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution(), Op_Conv_RT_VEF_Face::ajouter_contribution(), Op_Grad_VEF_P1B_Face::ajouter_elem(), Op_Grad_VEF_P1B_Face::ajouter_som(), Op_Conv_ALE_VEF::ajouterALE(), Masse_PolyMAC_P0P1NC_Face::appliquer_impl(), Masse_VDF_Face::appliquer_impl(), Masse_VEF_P1NC::appliquer_impl(), Assembleur_P_PolyMAC_P0::assembler_mat(), Assembleur_P_PolyMAC_P0P1NC::assembler_mat(), Modele_Jones_Launder_VDF::Calcul_D(), Modele_Jones_Launder_Thermique_VDF::Calcul_D(), Modele_Jones_Launder_VDF::Calcul_D_BiK(), Champ_P1NC::calcul_duidxj_paroi(), Segment_poly::calcul_vc(), Tetra_poly::calcul_vc(), Point_EF::calcul_vc(), Segment_EF::calcul_vc(), Tetra_EF::calcul_vc(), Tri_EF::calcul_vc(), Perte_Charge_Singuliere::calculate_Q(), Terme_Source_Constituant_Vortex_VEF_Face::calculer(), Terme_Source_Canal_perio_VDF_Face::calculer_debit(), Terme_Source_Canal_perio_VEF_P1NC::calculer_debit(), Op_Conv_EF_Stab_PolyMAC_P0_Face::calculer_dt_stab(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::calculer_dt_stab(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Face::calculer_dt_stab(), Op_Diff_PolyMAC_P0_Face::calculer_dt_stab(), Op_Conv_Muscl_New_VEF_Face::calculer_dt_stab(), Assembleur_P_VEF::calculer_inv_volume(), Op_Diff_VEFP1NCP1B_Face::calculer_laplacien_som(), Source_Transport_Fluctuation_Temperature_VDF_Elem::calculer_Prod_uteta_T(), Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::calculer_Prod_uteta_T(), Source_Transport_Fluctuation_Temperature_W_VDF_Elem::calculer_Prod_uteta_T(), Calcul_Production_K_VDF::calculer_terme_destruction_K(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_W_VDF_Elem::calculer_terme_destruction_K_W(), Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::calculer_terme_destruction_K_W(), Source_Transport_Fluctuation_Temperature_W_VDF_Elem::calculer_terme_destruction_K_W(), Source_Transport_Realisable_VEF_Face_base::contribuer_a_avec(), Perte_Charge_PolyMAC::contribuer_a_avec(), Perte_Charge_Singuliere_PolyMAC_Face::contribuer_a_avec(), Op_Dift_VEF_Face_Q1::contribuer_a_avec(), Perte_Charge_Reguliere_VEF_P1NC::contribuer_a_avec(), Perte_Charge_Singuliere_VEF_Face::contribuer_a_avec(), Perte_Charge_VEF::contribuer_a_avec(), Op_Div_PolyMAC::contribuer_a_avec(), Op_Div_PolyMAC_P0::contribuer_a_avec(), Op_Dift_VEF_Face::contribuer_au_second_membre(), Champ_val_tot_sur_vol_VEF::eval_contrib_loc(), Champ_Face_PolyMAC::init_va(), Champ_Face_PolyMAC_P0::init_ve2(), Champ_Face_PolyMAC::interp_ve(), Champ_Face_PolyMAC_P0P1NC::interp_ve(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::mettre_a_jour(), Op_Conv_VDF_base::mettre_a_jour(), Terme_Source_Canal_RANS_LES_VDF_Face::mettre_a_jour(), Assembleur_P_VEFPreP1B::modifier_secmem(), Op_Conv_VEF_Face::remplir_fluent(), Op_Diff_PolyMAC_base::update_nu(), and Champ_Face_PolyMAC_P0::update_ve().
porosite_face() [2/3]
const DoubleVect & Milieu_base::porosite_face () const inline
References porosite_face_.
get_porosites_champ()
const Champ_Don_base & Milieu_base::get_porosites_champ () const inline
References ch_porosites_.
porosite_face() [3/3]
double Milieu_base::porosite_face (const int i) const inline
References porosite_face_.
section_passage_face() [1/2]
const DoubleVect & Milieu_base::section_passage_face () const inline
References section_passage_face_.
section_passage_face() [2/2]
double Milieu_base::section_passage_face (int i) const inline
References section_passage_face_.
diametre_hydraulique_elem() [1/2]
DoubleTab & Milieu_base::diametre_hydraulique_elem () inline
References ch_diametre_hyd_, and Champ_Don_base::valeurs().
Referenced by Frottement_interfacial_PolyMAC_P0::ajouter_blocs(), Op_Evanescence_Homogene_Face_base::ajouter_blocs(), Frottement_interfacial_VDF::ajouter_blocs(), Op_Evanescence_Homogene_PolyMAC_P0_Face::ajouter_blocs_aux(), and Op_Diff_PolyMAC_P0P1NC_Elem::ajouter_blocs_ext().
diametre_hydraulique_elem() [2/2]
const DoubleTab & Milieu_base::diametre_hydraulique_elem () const inline
References ch_diametre_hyd_, and Champ_Don_base::valeurs().
diametre_hydraulique_face() [1/3]
DoubleVect & Milieu_base::diametre_hydraulique_face () inline
References diametre_hydraulique_face_.
diametre_hydraulique_face() [2/3]
const DoubleVect & Milieu_base::diametre_hydraulique_face () const inline
References diametre_hydraulique_face_.
diametre_hydraulique_face() [3/3]
double Milieu_base::diametre_hydraulique_face (int i) const inline
References diametre_hydraulique_face_.
est_deja_associe()
int Milieu_base::est_deja_associe () virtual
Renvoie 0 si le milieu est deja associe a un probleme, 1 sinon.
Returns
(int)
set_param()
void Milieu_base::set_param (Param & param) virtual
Reimplemented in Solid_Particle_arbitrary, Solid_Particle_base, Solid_Particle_sphere, Solid_Particle_spheroid, Fluide_Diphasique, Fluide_Dilatable_base, Espece, Fluide_Quasi_Compressible, Fluide_Weakly_Compressible, Constituant, Fluide_base, Fluide_Incompressible, Fluide_Ostwald, Fluide_reel_base, Fluide_stiffened_gas, Fluide_generique_CoolProp, Fluide_generique_EOS, and Solide.
References Param::ajouter(), ch_beta_th_, ch_Cp_, ch_lambda_, ch_rho_, and set_additional_params().
Referenced by readOn(), Constituant::set_param(), Fluide_base::set_param(), and Solide::set_param().
preparer_calcul()
void Milieu_base::preparer_calcul () virtual
Reimplemented in Fluide_Dilatable_base, Fluide_reel_base, and Milieu_composite.
Referenced by Probleme_base::preparer_calcul().
verifier_coherence_champs()
void Milieu_base::verifier_coherence_champs (int & err, Nom & message) virtual
Reimplemented in Fluide_Diphasique, Fluide_Dilatable_base, Espece, Fluide_base, Fluide_Incompressible, and Solide.
References Process::exit(), and Objet_U::que_suis_je().
Referenced by initialiser(), Fluide_Diphasique::verifier_coherence_champs(), Fluide_Dilatable_base::verifier_coherence_champs(), Espece::verifier_coherence_champs(), Fluide_base::verifier_coherence_champs(), and Solide::verifier_coherence_champs().
creer_champs_non_lus()
void Milieu_base::creer_champs_non_lus () virtual
Reimplemented in Fluide_Dilatable_base, Espece, Fluide_base, Fluide_Ostwald, and Fluide_reel_base.
References ch_Cp_, ch_lambda_, ch_rho_, creer_alpha(), and Objet_U_ptr::non_nul().
Referenced by Fluide_base::creer_champs_non_lus(), Fluide_Ostwald::creer_champs_non_lus(), and readOn().
discretiser()
void Milieu_base::discretiser (const Probleme_base & pb, const Discretisation_base & dis) virtual
Reimplemented in Fluide_Diphasique, Fluide_Dilatable_base, Fluide_Quasi_Compressible, Fluide_Weakly_Compressible, Constituant, Fluide_base, Fluide_Ostwald, Fluide_reel_base, Milieu_composite, and Solide.
References Champs_compris_T< FIELD_TYPE >::ajoute_champ(), ch_alpha_, ch_alpha_fois_rho_, ch_beta_th_, ch_Cp_, ch_lambda_, ch_rho_, ch_rho_Cp_comme_T_, ch_rho_Cp_elem_, champs_compris_, Objet_U_ptr::detach(), Discretisation_base::discretiser_champ(), discretiser_diametre_hydro(), discretiser_porosite(), Equation_base::domaine_dis(), Probleme_base::equation(), Field_base::fixer_nature_du_champ(), Discretisation_base::is_dg(), Field_base::nb_comp(), Discretisation_base::nommer_completer_champ_physique(), Objet_U_ptr::non_nul(), Probleme_base::schema_temps(), Champ_base::temps(), Schema_Temps_base::temps_courant(), TRUST_Deriv< _CLASSE_ >::valeur(), and Champ_Don_base::valeurs().
Referenced by Fluide_Diphasique::discretiser(), Fluide_base::discretiser(), Solide::discretiser(), Probleme_base::discretiser(), Constituant::discretiser_multi_concentration(), Probleme_base::typer_lire_milieu(), Pb_Phase_field::typer_lire_milieu(), and Pb_Multiphase::typer_lire_milieu().
is_rayo_semi_transp()
virtual int Milieu_base::is_rayo_semi_transp () const inline virtual
Reimplemented in Fluide_base.
Referenced by Cond_lim_utilisateur_base::is_pb_rayo(), Pb_Couple_rayo_semi_transp::le_modele_rayo_associe(), and Echange_contact_rayo_semi_transp_VDF::mettre_a_jour().
is_rayo_transp()
virtual int Milieu_base::is_rayo_transp () const inline virtual
Reimplemented in Fluide_base.
Referenced by Echange_contact_Rayo_transp_VDF::calculer_Teta_paroi(), Pb_Couple_Rayonnement::completer(), Cond_lim_utilisateur_base::is_pb_rayo(), and Echange_contact_Rayo_transp_VDF::mettre_a_jour().
mettre_a_jour()
void Milieu_base::mettre_a_jour (double temps) virtual
Reimplemented in Fluide_Diphasique, Constituant, Fluide_reel_base, Milieu_composite, Fluide_Dilatable_base, Fluide_base, and Fluide_Ostwald.
References calculer_alpha(), ch_alpha_, ch_alpha_fois_rho_, ch_beta_th_, ch_Cp_, ch_g_, ch_lambda_, ch_rho_, ch_rho_Cp_comme_T_, Champ_base::changer_temps(), Champ_Don_base::mettre_a_jour(), Champ_base::mettre_a_jour(), mettre_a_jour_porosite(), Objet_U_ptr::non_nul(), TRUST_Ref< _CLASSE_ >::non_nul(), and update_rho_cp().
Referenced by Pb_Dilatable_base::iterateTimeStep(), Probleme_base::mettre_a_jour(), Fluide_Diphasique::mettre_a_jour(), and Fluide_base::mettre_a_jour().
initTimeStep()
virtual bool Milieu_base::initTimeStep (double dt) inline virtual
Reimplemented in Fluide_base, Fluide_reel_base, and Milieu_composite.
Referenced by Probleme_base_interface_proto::initTimeStep_impl().
abortTimeStep()
void Milieu_base::abortTimeStep () virtual
Reimplemented in Fluide_Dilatable_base, Fluide_Weakly_Compressible, Fluide_reel_base, and Milieu_composite.
References Champ_base::abortTimeStep(), ch_rho_, and Objet_U_ptr::non_nul().
Referenced by Fluide_reel_base::abortTimeStep(), Milieu_composite::abortTimeStep(), and Probleme_base_interface_proto::abortTimeStep_impl().
resetTime()
void Milieu_base::resetTime (double time) virtual
References ch_rho_, Champ_base::mettre_a_jour(), Objet_U_ptr::non_nul(), Champ_base::resetTime(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by Probleme_base_interface_proto::resetTimeWithDir_impl().
initialiser()
int Milieu_base::initialiser (const double temps) virtual
Reimplemented in Fluide_Diphasique, Fluide_Dilatable_base, Constituant, Fluide_base, Fluide_Ostwald, Fluide_MUSIG, Fluide_reel_base, and Milieu_composite.
References calculer_alpha(), ch_alpha_, ch_alpha_fois_rho_, ch_beta_th_, ch_Cp_, ch_g_, ch_lambda_, ch_rho_, ch_rho_Cp_comme_T_, Champ_base::changer_temps(), Champ_Don_base::initialiser(), initialiser_porosite(), Objet_U_ptr::non_nul(), TRUST_Ref< _CLASSE_ >::non_nul(), Objet_U::que_suis_je(), update_rho_cp(), TRUST_Deriv< _CLASSE_ >::valeur(), and verifier_coherence_champs().
Referenced by Fluide_Diphasique::initialiser(), Fluide_base::initialiser(), and Probleme_base::preparer_calcul().
associer_gravite()
void Milieu_base::associer_gravite (const Champ_Don_base & la_gravite) virtual
Associe (affecte) un champ de gravite au milieu.
Parameters
(Champ_Don_base& gravite) champ donne representant la gravite
References ch_g_, Objet_U::dimension, Process::exit(), Field_base::nb_comp(), Objet_U_ptr::non_nul(), and TRUST_Ref< _CLASSE_ >::non_nul().
Referenced by associer_().
masse_volumique() [1/2]
const Champ_base & Milieu_base::masse_volumique () const virtual
Renvoie la masse volumique du milieu.
(version const)
Returns
(Champ_base&) le champ donne representant la masse volumique
Reimplemented in Fluide_Diphasique.
References ch_rho_, and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by Op_Diff_K_Eps_QC_VEF_Face::ajouter(), Source_Reaction_Particules_VDF::ajouter(), Source_Reaction_Particules_VEF::ajouter(), Iterateur_Source_EF_Som< _TYPE_ >::ajouter(), Terme_Source_Th_TdivU_VEF_Face::ajouter(), Source_QC_Gravite_VDF::ajouter_blocs(), Terme_Source_Qdm_VDF_Face::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_P0_Face::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Face::ajouter_blocs(), Coalescence_bulles_1groupe_PolyMAC_P0::ajouter_blocs(), Coalescence_bulles_2groupes_PolyMAC_P0::ajouter_blocs(), Flux_2groupes_PolyMAC_P0::ajouter_blocs(), Injection_QDM_nulle_PolyMAC_P0::ajouter_blocs(), Nucleation_paroi_PolyMAC_P0::ajouter_blocs(), Rupture_bulles_1groupe_PolyMAC_P0::ajouter_blocs(), Rupture_bulles_2groupes_PolyMAC_P0::ajouter_blocs(), Variation_rho::ajouter_blocs(), Injection_QDM_nulle_VDF::ajouter_blocs(), Production_energie_cin_turb_PolyMAC_P0::ajouter_blocs(), Production_energie_cin_turb_VDF::ajouter_blocs(), Correction_Antal_PolyMAC_P0::ajouter_blocs(), Correction_Tomiyama_PolyMAC_P0::ajouter_blocs(), Dispersion_bulles_PolyMAC_P0::ajouter_blocs(), Frottement_interfacial_PolyMAC_P0::ajouter_blocs(), Portance_interfaciale_PolyMAC_P0::ajouter_blocs(), DP_Impose_PolyMAC_Face::ajouter_blocs(), Terme_Boussinesq_PolyMAC_Face::ajouter_blocs(), Terme_Source_Qdm_Face_PolyMAC_P0P1NC::ajouter_blocs(), Op_Evanescence_Homogene_Elem_base::ajouter_blocs(), Op_Evanescence_Homogene_Face_base::ajouter_blocs(), Source_Flux_interfacial_base::ajouter_blocs(), Source_Force_Tchen_base::ajouter_blocs(), Correction_Antal_VDF::ajouter_blocs(), Dispersion_bulles_VDF::ajouter_blocs(), Frottement_interfacial_VDF::ajouter_blocs(), Portance_interfaciale_VDF::ajouter_blocs(), Op_Conv_Amont_VPoly_VDF_Face::ajouter_blocs(), DP_Impose_VEF_Face::ajouter_blocs(), Masse_PolyMAC_P0_Face::ajouter_blocs(), Masse_VDF_Face::ajouter_blocs(), Op_Evanescence_Homogene_PolyMAC_P0_Face::ajouter_blocs_aux(), Force_Tchen_PolyMAC_P0::ajouter_blocs_aux(), Correction_Lubchenko_PolyMAC_P0::ajouter_blocs_disp(), Op_Diff_PolyMAC_P0P1NC_Elem::ajouter_blocs_ext(), Correction_Lubchenko_PolyMAC_P0::ajouter_blocs_lift(), Source_Masse_Fluide_Dilatable_VEF::ajouter_eq_espece(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_blocs(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_impl(), Op_Diff_K_Omega_VDF_base::associer_diffusivite_turbulente(), Champ_P1NC::calcul_h_conv(), Implicit_steady::calcul_mat_masse_diviser_par_dt_vdf(), Implicit_steady::calcul_mat_masse_diviser_par_dt_vef(), Traitement_particulier_NS_canal::calcul_reynolds_tau(), Traitement_particulier_NS_temperature_VEF::calcul_temperature(), Masse_Multiphase::calculer_alpha_rho(), Energie_Multiphase::calculer_alpha_rho_e(), Energie_Multiphase::calculer_alpha_rho_h(), Navier_Stokes_FT_Disc::calculer_delta_u_interface(), Navier_Stokes_FT_Disc::calculer_dI_dt(), Op_Dift_Multiphase_VDF_Face::calculer_dt_stab(), Terme_Source_Coriolis_VDF_Face::calculer_force_de_Coriolis(), Navier_Stokes_std::calculer_la_pression_en_pa(), Traitement_particulier_NS_canal_VDF::calculer_moyenne_spatiale_vitesse_rho_mu(), Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_vitesse_rho_mu(), Navier_Stokes_std::calculer_pression_hydrostatique(), Transport_Marqueur_FT::calculer_proprietes_fluide_pos_particules(), Convection_Diffusion_Temperature::calculer_rho_cp_T(), Paroi_ODVM_scal_VDF::calculer_scal(), Paroi_TBLE_scal_VDF::calculer_scal(), ParoiVEF_TBLE_scal::calculer_scal(), Neumann_paroi_rayo_semi_transp_VDF::calculer_temperature_bord(), Paroi_flux_impose_Rayo_transp::calculer_Teta_i_VDF(), Echange_global_impose::champ_exterieur(), Echange_couplage_thermique::champ_exterieur(), Triple_Line_Model_FT_Disc::completer(), Op_Diff_K_Eps_VDF_base::completer(), Op_Diff_PolyMAC_P0_base::completer(), Sortie_libre_pression_imposee_QC::completer(), Sortie_libre_pression_imposee::completer(), Sortie_libre_pression_moyenne_imposee::completer(), Fluide_Weakly_Compressible::completer(), Triple_Line_Model_FT_Disc::compute_TCL_fluxes_in_all_boundary_cells(), Transport_Marqueur_FT::construction_ensemble_proprietes(), Convection_Diffusion_Fluide_Dilatable_Proto::derivee_en_temps_inco_sans_solveur_masse_impl(), Variation_rho::dimensionner_blocs(), Convection_Diffusion_Temperature::ecrire_fichier_pena_th(), Sortie_libre_pression_imposee_QC::flux_impose(), Sortie_libre_pression_moyenne_imposee::flux_impose(), Sortie_libre_pression_imposee::flux_impose(), Convection_Diffusion_Temperature::get_time_factor(), Sortie_libre_Gradient_Pression_impose::grad_P_imp(), Sortie_libre_Gradient_Pression_libre_VEF::Grad_P_lib_VEF(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::Grad_P_lib_VEFPreP1B(), Paroi_ODVM_scal_VDF::init_lois_paroi(), Paroi_TBLE_scal_VDF::init_lois_paroi(), MuLambda_TBLE_Fcts_T::initialiser(), Champ_front_pression_from_u::initialiser(), Champ_front_debit_massique::initialiser_coefficient(), Portance_interfaciale_PolyMAC_P0::mettre_a_jour(), Aire_interfaciale::mettre_a_jour(), Fluide_reel_base::mettre_a_jour(), Modele_turbulence_scal_LES_dyn_VDF::mettre_a_jour(), Modele_turbulence_scal_Prandtl::mettre_a_jour(), PlaqThVDF::mettre_a_jour(), Op_EF_base::modifier_flux(), Op_VEF_Face::modifier_flux(), Op_Diff_Turbulent_PolyMAC_P0_Face::modifier_mu(), Solid_Particle_sphere::readOn(), and Op_Diff_PolyMAC_P0_base::update_nu().
masse_volumique() [2/2]
Champ_base & Milieu_base::masse_volumique () virtual
Renvoie la masse volumique du milieu.
Returns
(Champ_base&) le champ donne representant la masse volumique
Reimplemented in Fluide_Diphasique.
References ch_rho_, and TRUST_Deriv< _CLASSE_ >::valeur().
has_masse_volumique()
bool Milieu_base::has_masse_volumique () const inline
References ch_rho_, and Objet_U_ptr::non_nul().
Referenced by Terme_Source_Qdm_Face_PolyMAC_P0P1NC::ajouter_blocs(), Op_Diff_PolyMAC_P0_base::completer(), and Op_Diff_PolyMAC_P0_base::update_nu().
diffusivite() [1/2]
const Champ_Don_base & Milieu_base::diffusivite () const virtual
Renvoie la diffusivite du milieu.
(version const)
Returns
(Champ_Don_base&) le champ donne representant la diffusivite
Reimplemented in Fluide_Diphasique.
References ch_alpha_, and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::ajouter(), Champ_front_contact_VEF::calcul_coeff_amort(), Modele_turbulence_scal_Prandtl::calculer_diffusivite_turbulente(), Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re::calculer_diffusivite_turbulente(), Paroi_std_scal_hyd_EF::calculer_scal(), Loi_Paroi_Nu_Impose_VDF::calculer_scal(), Paroi_loi_WW_scal_VDF::calculer_scal(), Paroi_ODVM_scal_VDF::calculer_scal(), Paroi_std_scal_hyd_VDF::calculer_scal(), Loi_Paroi_Nu_Impose_VEF::calculer_scal(), Paroi_loi_WW_scal_VEF::calculer_scal(), Paroi_scal_analytique_VEF::calculer_scal(), Paroi_std_scal_hyd_VEF::calculer_scal(), ParoiVEF_TBLE_scal::calculer_scal(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::diffusivite_pour_pas_de_temps(), Convection_Diffusion_Temperature_base::diffusivite_pour_pas_de_temps(), Energie_Multiphase_Enthalpie::diffusivite_pour_pas_de_temps(), Convection_Diffusion_std::diffusivite_pour_transport(), MuLambda_TBLE_Cte::initialiser(), and PlaqThVDF::mettre_a_jour().
diffusivite() [2/2]
Champ_Don_base & Milieu_base::diffusivite () virtual
Renvoie la diffusivite du milieu.
Returns
(Champ_Don_base&) le champ donne representant la diffusivite
Reimplemented in Fluide_Diphasique.
References ch_alpha_, and TRUST_Deriv< _CLASSE_ >::valeur().
has_diffusivite()
bool Milieu_base::has_diffusivite () const inline
References ch_alpha_, and Objet_U_ptr::non_nul().
Referenced by Modele_turbulence_scal_Prandtl::calculer_diffusivite_turbulente(), and MuLambda_TBLE_Cte::initialiser().
diffusivite_fois_rho() [1/2]
const Champ_Don_base & Milieu_base::diffusivite_fois_rho () const virtual
References ch_alpha_fois_rho_, and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by Energie_Multiphase_Enthalpie::diffusivite_pour_transport().
diffusivite_fois_rho() [2/2]
Champ_Don_base & Milieu_base::diffusivite_fois_rho () virtual
References ch_alpha_fois_rho_, and TRUST_Deriv< _CLASSE_ >::valeur().
conductivite() [1/2]
const Champ_Don_base & Milieu_base::conductivite () const virtual
Renvoie la conductivite du milieu.
(version const)
Returns
(Champ_Don_base&) le champ donne representant la conductivite
Reimplemented in Fluide_Diphasique.
References ch_lambda_, and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by Operateur_Conv_sensibility_VEF::ajouter(), Source_Robin_Scalaire::ajouter(), Flux_2groupes_PolyMAC_P0::ajouter_blocs(), Source_Flux_interfacial_base::ajouter_blocs(), Op_Diff_PolyMAC_P0P1NC_Elem::ajouter_blocs_ext(), Champ_front_contact_VEF::calcul_grads_locaux(), Op_Diff_DG_base::calculer_dt_stab(), Op_Diff_PolyMAC_base::calculer_dt_stab(), Op_Diff_VEF_base::calculer_dt_stab(), Modele_turbulence_scal_LES_dyn_VDF::calculer_grad_teta(), Echange_contact_VDF::calculer_h_autre_pb(), Echange_contact_Correlation_VEF::calculer_h_solide(), Echange_contact_Correlation_VDF::calculer_h_solide(), Paroi_ODVM_scal_VDF::calculer_scal(), Neumann_paroi_rayo_semi_transp_VDF::calculer_temperature_bord(), Paroi_flux_impose_Rayo_transp::calculer_Teta_i_VDF(), Triple_Line_Model_FT_Disc::completer(), Echange_interne_impose::completer(), Echange_contact_Correlation_VEF::completer(), Post_Processing_Hydrodynamic_Forces::compute_heat_transfer(), Source_WC_Chaleur_VEF::compute_interpolate_gradP(), Paroi_scal_hyd_base_EF::compute_nusselt(), Paroi_scal_hyd_base_VDF::compute_nusselt(), Paroi_scal_hyd_base_VEF::compute_nusselt(), Conduction::diffusivite_pour_transport(), Convection_Diffusion_Fluide_Dilatable_base::diffusivite_pour_transport(), Convection_Diffusion_Temperature_base::diffusivite_pour_transport(), Loi_Paroi_Nu_Impose_VDF::imprimer_nusselt(), Loi_Paroi_Nu_Impose_VEF::imprimer_nusselt(), Paroi_ODVM_scal_VDF::init_lois_paroi(), Echange_contact_VDF::initialiser(), Echange_contact_rayo_semi_transp_VDF::mettre_a_jour(), Echange_contact_VDF_FT_Disc::mettre_a_jour(), Echange_contact_VDF_FT_Disc_solid::mettre_a_jour(), Echange_contact_Rayo_transp_VDF::mettre_a_jour(), Echange_contact_VDF::mettre_a_jour(), and IJK_Thermals::verifie_milieu().
conductivite() [2/2]
Champ_Don_base & Milieu_base::conductivite () virtual
Renvoie la conductivite du milieu.
Returns
(Champ_Don_base&) le champ donne representant la conductivite
Reimplemented in Fluide_Diphasique.
References ch_lambda_, and TRUST_Deriv< _CLASSE_ >::valeur().
has_conductivite()
bool Milieu_base::has_conductivite () const inline
References ch_lambda_, and Objet_U_ptr::non_nul().
Referenced by IJK_Thermals::verifie_milieu().
capacite_calorifique() [1/2]
const Champ_Don_base & Milieu_base::capacite_calorifique () const virtual
Renvoie la capacite calorifique du milieu.
(version const)
Returns
(Champ_Don_base&) le champ donne representant la capacite calorifique
Reimplemented in Fluide_Diphasique.
References ch_Cp_, and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by Operateur_Conv_sensibility_VEF::ajouter(), Terme_Source_Th_TdivU_VEF_Face::ajouter(), Flux_2groupes_PolyMAC_P0::ajouter_blocs(), Source_Flux_interfacial_base::ajouter_blocs(), Op_Diff_PolyMAC_P0P1NC_Elem::ajouter_blocs_ext(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_impl(), Champ_P1NC::calcul_h_conv(), Fluide_base::calculer_e_int(), Convection_Diffusion_Temperature::calculer_rho_cp_T(), Paroi_ODVM_scal_VDF::calculer_scal(), Paroi_TBLE_scal_VDF::calculer_scal(), ParoiVEF_TBLE_scal::calculer_scal(), Neumann_paroi_rayo_semi_transp_VDF::calculer_temperature_bord(), Fluide_base::calculer_temperature_multiphase(), Paroi_flux_impose_Rayo_transp::calculer_Teta_i_VDF(), Echange_global_impose::champ_exterieur(), Echange_couplage_thermique::champ_exterieur(), Triple_Line_Model_FT_Disc::completer(), Convection_Diffusion_Temperature::ecrire_fichier_pena_th(), Convection_Diffusion_Temperature::get_time_factor(), Paroi_ODVM_scal_VDF::init_lois_paroi(), Paroi_TBLE_scal_VDF::init_lois_paroi(), MuLambda_TBLE_Fcts_T::initialiser(), Modele_turbulence_scal_LES_dyn_VDF::mettre_a_jour(), Modele_turbulence_scal_Prandtl::mettre_a_jour(), PlaqThVDF::mettre_a_jour(), Op_VEF_Face::modifier_flux(), and IJK_Thermals::verifie_milieu().
capacite_calorifique() [2/2]
Champ_Don_base & Milieu_base::capacite_calorifique () virtual
Renvoie la capacite calorifique du milieu.
Returns
(Champ_Don_base&) le champ donne representant la capacite calorifique
Reimplemented in Fluide_Diphasique.
References ch_Cp_, and TRUST_Deriv< _CLASSE_ >::valeur().
has_capacite_calorifique()
bool Milieu_base::has_capacite_calorifique () const inline
References ch_Cp_, and Objet_U_ptr::non_nul().
Referenced by IJK_Thermals::verifie_milieu().
beta_t() [1/2]
const Champ_Don_base & Milieu_base::beta_t () const virtual
Renvoie beta_t du milieu.
(version const)
Returns
(Champ_Don_base&) le champ donne representant beta_t
Reimplemented in Fluide_Diphasique.
References ch_beta_th_, and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by Source_Transport_Fluctuation_Temperature_VDF_Elem::associer_pb(), Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::associer_pb(), Source_Transport_Fluctuation_Temperature_W_VDF_Elem::associer_pb(), Source_Transport_Flux_Chaleur_Turbulente_VDF_Face::associer_pb(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_VEF_Face::associer_pb(), Terme_Source_inc_th_VDF_Face::associer_pb(), Terme_Boussinesq_base::associer_pb(), Source_Transport_proto::associer_pb_anisotherme(), Source_Transport_proto::associer_pb_anisotherme_concen(), ParoiVDF_TBLE_LRM::calculer_hyd(), ParoiVDF_TBLE_LRM::calculer_hyd_BiK(), Navier_Stokes_FT_Disc::compute_boussinesq_additional_gravity(), ParoiVDF_TBLE::init_lois_paroi(), and ParoiVEF_TBLE::init_lois_paroi().
beta_t() [2/2]
Champ_Don_base & Milieu_base::beta_t () virtual
Renvoie beta_t du milieu.
Returns
(Champ_Don_base&) le champ donne representant beta_t
Reimplemented in Fluide_Diphasique.
References ch_beta_th_, and TRUST_Deriv< _CLASSE_ >::valeur().
has_beta_t()
bool Milieu_base::has_beta_t () const inline
References ch_beta_th_, and Objet_U_ptr::non_nul().
Referenced by Source_Transport_K_Eps_Bas_Reynolds_anisotherme_VEF_Face::associer_pb(), and Terme_Boussinesq_base::associer_pb().
gravite() [1/2]
const Champ_Don_base & Milieu_base::gravite () const virtual
Renvoie la gravite du milieu si elle a ete associe provoque une erreur sinon.
(version const)
Returns
(Champ_Don_base&) le champ representant la gravite du milieu
Exceptions
pas de gravite associee au milieu
References ch_g_, Process::exit(), Objet_U_ptr::non_nul(), TRUST_Ref< _CLASSE_ >::non_nul(), TRUST_Deriv< _CLASSE_ >::valeur(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Source_Flottabilite::ajouter(), Source_Trainee::ajouter(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_VDF_Elem::associer_pb(), Source_Transport_Fluctuation_Temperature_VDF_Elem::associer_pb(), Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::associer_pb(), Source_Transport_Fluctuation_Temperature_W_VDF_Elem::associer_pb(), Source_Transport_Flux_Chaleur_Turbulente_VDF_Face::associer_pb(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_VEF_Face::associer_pb(), Terme_Gravite_VDF_Face::associer_pb(), Terme_Boussinesq_base::associer_pb(), Source_Transport_proto::associer_pb_anisotherme(), Source_Transport_proto::associer_pb_anisotherme_concen(), Source_Transport_proto::associer_pb_concen(), Fluide_Diphasique_IJK::calculate_direction_gravite(), Navier_Stokes_FTD_IJK::calculer_dv(), ParoiVDF_TBLE_LRM::calculer_hyd(), ParoiVDF_TBLE::calculer_hyd(), ParoiVEF_TBLE::calculer_hyd(), ParoiVDF_TBLE::calculer_hyd_BiK(), ParoiVDF_TBLE_LRM::calculer_hyd_BiK(), ParoiVEF_TBLE::calculer_hyd_BiK(), Navier_Stokes_std::calculer_pression_hydrostatique(), Transport_Marqueur_FT::calculer_proprietes_fluide_pos_particules(), Navier_Stokes_FTD_IJK::compute_correction_for_momentum_balance(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_vinf_Stokes(), Navier_Stokes_FT_Disc::derivee_en_temps_inco(), Fluide_Diphasique_IJK::get_gravite_norm(), Navier_Stokes_FTD_IJK::projeter(), and Navier_Stokes_FTD_IJK::terme_source_gravite().
gravite() [2/2]
Champ_Don_base & Milieu_base::gravite () virtual
Renvoie la gravite du milieu si elle a ete associe provoque une erreur sinon.
Returns
(Champ_Don_base&) le champ representant la gravite du milieu
References ch_g_, Process::exit(), Objet_U_ptr::non_nul(), TRUST_Ref< _CLASSE_ >::non_nul(), TRUST_Deriv< _CLASSE_ >::valeur(), and TRUST_Ref< _CLASSE_ >::valeur().
a_gravite()
int Milieu_base::a_gravite () const virtual
Renvoie 1 si la gravite a ete initialisee.
Returns
(int) 1 si g.non_nul
References ch_g_, Objet_U_ptr::non_nul(), and TRUST_Ref< _CLASSE_ >::non_nul().
Referenced by Source_Trainee::ajouter(), Transport_Marqueur_FT::calculer_proprietes_fluide_pos_particules(), Fluide_Weakly_Compressible::completer(), Fluide_Diphasique_IJK::get_gravite_norm(), Fluide_Weakly_Compressible::Resoudre_EDO_PT(), Fluide_Weakly_Compressible::update_pressure_fields(), and Fluide_Diphasique::verifier_coherence_champs().
update_rho_cp()
void Milieu_base::update_rho_cp (double temps) virtual
Reimplemented in Fluide_Dilatable_base.
References Discretisation_tools::cells_to_faces(), Discretisation_tools::cells_to_nodes(), ch_Cp_, ch_rho_, ch_rho_Cp_comme_T_, ch_rho_Cp_elem_, Champ_base::changer_temps(), Domaine_dis_base::domaine(), Champ_Fonc_base::domaine_dis_base(), equation_, Process::exit(), TRUSTVect< _TYPE_, _SIZE_ >::get_md_vector(), Domaine_32_64< _SIZE_ >::md_vector_sommets(), Objet_U::que_suis_je(), TRUST_Deriv< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), and Champ_Proto::valeurs().
Referenced by initialiser(), mettre_a_jour(), and Fluide_reel_base::mettre_a_jour().
associer_equation()
void Milieu_base::associer_equation (const Equation_base * eqn) const virtual
Reimplemented in Milieu_composite.
References equation_, Process::exit(), Nom::getString(), Equation_base::inconnue(), Field_base::le_nom(), Equation_base::probleme(), and Objet_U::que_suis_je().
Referenced by Milieu_composite::associer_equation(), and Equation_base::associer_milieu_equation().
equation()
const Equation_base & Milieu_base::equation (const std::string & nom_inc) const virtual
References equation_.
Referenced by Iterateur_Source_EF_Som< _TYPE_ >::ajouter(), Fluide_reel_base::calculate_fluid_properties(), Fluide_reel_base::calculate_fluid_properties_enthalpie(), Fluide_reel_base::calculate_fluid_properties_enthalpie_incompressible(), Fluide_reel_base::calculate_fluid_properties_incompressible(), Modele_turbulence_hyd_RANS_Gen< MODELE >::calculate_limit_viscosity(), Fluide_base::calculer_e_int(), Fluide_base::calculer_temperature_multiphase(), Fluide_reel_base::check_unknown_range(), Fluide_base::creer_e_int(), Fluide_base::creer_temperature_multiphase(), Fluide_reel_base::initialiser(), Milieu_composite::initialiser(), Fluide_reel_base::mettre_a_jour(), and Milieu_composite::mettre_a_jour_tabs().
check_unknown_range()
virtual int Milieu_base::check_unknown_range () const inline virtual
Reimplemented in Fluide_reel_base, and Milieu_composite.
creer_champ()
void Milieu_base::creer_champ (const Motcle & motlu) inline override virtual
Implements Champs_compris_interface.
Reimplemented in Fluide_Dilatable_base.
Referenced by Probleme_base::creer_champ(), and Fluide_Dilatable_base::creer_champ().
get_champ()
const Champ_base & Milieu_base::get_champ (const Motcle & nom) const override virtual
Implements Champs_compris_interface.
Reimplemented in Fluide_Dilatable_base.
References champs_compris_, and Champs_compris_T< FIELD_TYPE >::get_champ().
get_noms_champs_postraitables()
void Milieu_base::get_noms_champs_postraitables (Noms & nom, Option opt = NONE) const override virtual
Implements Champs_compris_interface.
Reimplemented in Fluide_Dilatable_base.
References TRUST_Vector< _CLASSE_ >::add(), champs_compris_, Champs_compris_T< FIELD_TYPE >::liste_noms_compris(), and Objet_U::que_suis_je().
Referenced by Equation_base::get_noms_champs_postraitables(), Probleme_base::get_noms_champs_postraitables(), and Fluide_Dilatable_base::get_noms_champs_postraitables().
has_champ() [1/2]
bool Milieu_base::has_champ (const Motcle & nom, TRUST_Ref< Champ_base * > & ref_champ) const override virtual
Implements Champs_compris_interface.
Reimplemented in Fluide_Dilatable_base.
References champs_compris_, and Champs_compris_T< FIELD_TYPE >::has_champ().
Referenced by Probleme_base::get_champ(), Fluide_Dilatable_base::get_champ(), Probleme_base::has_champ(), and Fluide_Dilatable_base::has_champ().
has_champ() [2/2]
bool Milieu_base::has_champ (const Motcle & nom) const override virtual
Implements Champs_compris_interface.
Reimplemented in Fluide_Dilatable_base.
References champs_compris_, and Champs_compris_T< FIELD_TYPE >::has_champ().
has_hydr_diam()
const bool & Milieu_base::has_hydr_diam () inline
Referenced by Solide::discretiser().
set_id_composite()
void Milieu_base::set_id_composite (const int i)
References id_composite_.
champs_don()
const TRUST_List< TRUST_Ref< Champ_Don_base * > > & Milieu_base::champs_don () const inline
References champs_don_.
is_dilatable()
virtual bool Milieu_base::is_dilatable () const inline virtual
Reimplemented in Fluide_Dilatable_base.
Referenced by Probleme_base::is_dilatable().
calculer_alpha()
void Milieu_base::calculer_alpha () protected virtual
Calcul de alpha=lambda/(rho*Cp).
Suivant lambda, rho et Cp alpha peut-etre type comme un champ uniforme ou un champ uniforme par morceau.
Exceptions
violation d'une precondition
impossible de calculer alpha car le type des champs lambda,rho,Cp n'est pas compatible ou pas gere.
Reimplemented in Fluide_Dilatable_base.
References ch_alpha_, ch_alpha_fois_rho_, ch_Cp_, ch_lambda_, ch_rho_, Objet_U_ptr::non_nul(), TRUST_Deriv< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), and Champ_Proto::valeurs().
Referenced by initialiser(), and mettre_a_jour().
ecrire()
void Milieu_base::ecrire (Sortie & os) const protected
Ecrit un objet milieu sur un flot de sortie.
Ecrit les caracteristiques du milieu:
masse volumique
conductivite
capacite calorifique
beta_th
porosite
Parameters
(Sortie& os) le flot de sortie pour l'ecriture
References ch_beta_th_, ch_Cp_, ch_lambda_, ch_porosites_, and ch_rho_.
Referenced by printOn(), Fluide_Dilatable_base::printOn(), Fluide_base::printOn(), and Fluide_Ostwald::printOn().
creer_alpha()
void Milieu_base::creer_alpha () protected
References ch_alpha_, ch_alpha_fois_rho_, ch_Cp_, ch_lambda_, ch_rho_, Field_base::nommer(), and Objet_U_ptr::non_nul().
Referenced by creer_champs_non_lus().
discretiser_porosite()
void Milieu_base::discretiser_porosite (const Probleme_base & pb, const Discretisation_base & dis) protected
References MD_Vector_tools::creer_tableau_distribue(), Equation_base::domaine_dis(), Probleme_base::equation(), TRUSTVect< _TYPE_, _SIZE_ >::get_md_vector(), MD_Vector::non_nul(), TRUST_Ref< _CLASSE_ >::non_nul(), porosite_face_, Probleme_base::schema_temps(), Schema_Temps_base::temps_courant(), TRUST_Ref< _CLASSE_ >::valeur(), and zdb_.
Referenced by discretiser(), Fluide_Diphasique::discretiser(), Fluide_reel_base::discretiser(), and Milieu_composite::discretiser().
discretiser_diametre_hydro()
void Milieu_base::discretiser_diametre_hydro (const Probleme_base & pb, const Discretisation_base & dis) protected
References MD_Vector_tools::creer_tableau_distribue(), diametre_hydraulique_face_, Equation_base::domaine_dis(), Probleme_base::equation(), TRUSTVect< _TYPE_, _SIZE_ >::get_md_vector(), MD_Vector::non_nul(), TRUST_Ref< _CLASSE_ >::non_nul(), Probleme_base::schema_temps(), Schema_Temps_base::temps_courant(), TRUST_Ref< _CLASSE_ >::valeur(), and zdb_.
Referenced by discretiser(), Fluide_Diphasique::discretiser(), Fluide_reel_base::discretiser(), and Milieu_composite::discretiser().
set_additional_params()
void Milieu_base::set_additional_params (Param & param) protected virtual
References Param::ajouter(), ch_diametre_hyd_, ch_g_, and ch_porosites_.
Referenced by set_param(), Fluide_Diphasique::set_param(), and Fluide_reel_base::set_param().
calculate_face_porosity()
void Milieu_base::calculate_face_porosity () protected virtual
References ch_porosites_, TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_VF::face_voisins(), Domaine_VF::nb_faces_tot(), porosite_face_, TRUSTVect< _TYPE_, _SIZE_ >::size_totale(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), and zdb_.
Referenced by mettre_a_jour_porosite().
calculate_face_hydr_diam()
void Milieu_base::calculate_face_hydr_diam () protected virtual
References ch_diametre_hyd_, diametre_hydraulique_face_, Domaine_VF::face_voisins(), Domaine_VF::nb_faces_tot(), TRUSTVect< _TYPE_, _SIZE_ >::size_totale(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), and zdb_.
mettre_a_jour_porosite()
void Milieu_base::mettre_a_jour_porosite (double temps) protected
References calculate_face_porosity(), ch_diametre_hyd_, ch_porosites_, Champ_base::changer_temps(), fill_section_passage_face(), Champ_Don_base::mettre_a_jour(), Objet_U_ptr::non_nul(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by mettre_a_jour(), and Milieu_composite::mettre_a_jour().
fill_section_passage_face()
void Milieu_base::fill_section_passage_face () protected
References Domaine_VF::face_surfaces(), porosite_face_, TRUSTVect< _TYPE_, _SIZE_ >::resize(), section_passage_face_, TRUSTArray< _TYPE_, _SIZE_ >::size_array(), TRUST_Ref< _CLASSE_ >::valeur(), and zdb_.
Referenced by mettre_a_jour_porosite().
initialiser_porosite()
int Milieu_base::initialiser_porosite (const double temps) protected
References ch_diametre_hyd_, ch_porosites_, Champ_Don_base::initialiser(), and Objet_U_ptr::non_nul().
Referenced by initialiser(), Fluide_Diphasique::initialiser(), Fluide_reel_base::initialiser(), and Milieu_composite::initialiser().
check_gravity_vector()
void Milieu_base::check_gravity_vector () const protected
References ch_g_, Objet_U::dimension, Process::exit(), Field_base::nb_comp(), and Objet_U_ptr::non_nul().
Referenced by readOn().
Member Data Documentation
info_obj
const Type_info Milieu_base::info_obj static
id_composite_
int Milieu_base::id_composite_ = -1
Referenced by Fluide_reel_base::calculate_fluid_properties_enthalpie(), Fluide_reel_base::calculate_fluid_properties_enthalpie_incompressible(), Fluide_base::calculer_e_int(), Fluide_reel_base::check_unknown_range(), Fluide_reel_base::discretiser(), Fluide_reel_base::initialiser(), and set_id_composite().
zdb_
TRUST_Ref< Domaine_dis_base *> Milieu_base::zdb_ protected
Referenced by calculate_face_hydr_diam(), calculate_face_porosity(), discretiser_diametre_hydro(), discretiser_porosite(), and fill_section_passage_face().
ch_rho_
TRUST_Deriv< Champ_base > Milieu_base::ch_rho_ protected
Referenced by abortTimeStep(), Fluide_reel_base::abortTimeStep(), Fluide_reel_base::calculate_fluid_properties_enthalpie(), calculer_alpha(), Fluide_base::calculer_nu(), creer_alpha(), creer_champs_non_lus(), Fluide_base::creer_nu(), discretiser(), Fluide_Dilatable_base::discretiser(), Fluide_reel_base::discretiser(), Milieu_composite::discretiser(), ecrire(), has_masse_volumique(), initialiser(), Fluide_Dilatable_base::initialiser(), Fluide_reel_base::initialiser(), Milieu_composite::initialiser(), Fluide_reel_base::initTimeStep(), Milieu_composite::initTimeStep(), Fluide_Quasi_Compressible::lire_motcle_non_standard(), masse_volumique(), mettre_a_jour(), Fluide_reel_base::mettre_a_jour(), Milieu_composite::mettre_a_jour(), Fluide_Dilatable_base::mettre_a_jour(), Milieu_composite::mettre_a_jour_tabs(), resetTime(), set_param(), Fluide_Incompressible::set_param(), update_rho_cp(), Fluide_Dilatable_base::update_rho_cp(), Fluide_Dilatable_base::verifier_coherence_champs(), Fluide_base::verifier_coherence_champs(), Fluide_Incompressible::verifier_coherence_champs(), Fluide_Dilatable_base::write_mean_edo(), and Fluide_Weakly_Compressible::write_mean_edo().
ch_g_
TRUST_Deriv< Champ_Don_base > Milieu_base::ch_g_ protected
Referenced by a_gravite(), associer_gravite(), check_gravity_vector(), gravite(), initialiser(), Fluide_reel_base::initialiser(), mettre_a_jour(), readOn(), and set_additional_params().
ch_alpha_
TRUST_Deriv< Champ_Don_base > Milieu_base::ch_alpha_ protected
Referenced by calculer_alpha(), creer_alpha(), diffusivite(), discretiser(), Fluide_reel_base::discretiser(), Milieu_composite::discretiser(), has_diffusivite(), initialiser(), Fluide_reel_base::initialiser(), mettre_a_jour(), Fluide_reel_base::mettre_a_jour(), Milieu_composite::mettre_a_jour(), Milieu_composite::mettre_a_jour_tabs(), and readOn().
ch_lambda_
TRUST_Deriv< Champ_Don_base > Milieu_base::ch_lambda_ protected
Referenced by calculer_alpha(), conductivite(), creer_alpha(), creer_champs_non_lus(), Fluide_Dilatable_base::creer_champs_non_lus(), discretiser(), Fluide_Dilatable_base::discretiser(), Fluide_reel_base::discretiser(), Milieu_composite::discretiser(), ecrire(), has_conductivite(), initialiser(), Fluide_Dilatable_base::initialiser(), Fluide_reel_base::initialiser(), Fluide_Dilatable_base::lire_motcle_non_standard(), mettre_a_jour(), Fluide_reel_base::mettre_a_jour(), Milieu_composite::mettre_a_jour(), Fluide_Dilatable_base::mettre_a_jour(), Milieu_composite::mettre_a_jour_tabs(), readOn(), set_param(), Fluide_Dilatable_base::verifier_coherence_champs(), Fluide_base::verifier_coherence_champs(), and Solide::verifier_coherence_champs().
ch_alpha_fois_rho_
TRUST_Deriv< Champ_Don_base > Milieu_base::ch_alpha_fois_rho_ protected
Referenced by calculer_alpha(), creer_alpha(), diffusivite_fois_rho(), discretiser(), Fluide_reel_base::discretiser(), Milieu_composite::discretiser(), initialiser(), Fluide_reel_base::initialiser(), mettre_a_jour(), Fluide_reel_base::mettre_a_jour(), Milieu_composite::mettre_a_jour(), and Milieu_composite::mettre_a_jour_tabs().
ch_Cp_
TRUST_Deriv< Champ_Don_base > Milieu_base::ch_Cp_ protected
Referenced by calculer_alpha(), capacite_calorifique(), creer_alpha(), creer_champs_non_lus(), Fluide_Dilatable_base::creer_champs_non_lus(), discretiser(), Fluide_Dilatable_base::discretiser(), Fluide_reel_base::discretiser(), Milieu_composite::discretiser(), ecrire(), has_capacite_calorifique(), initialiser(), Fluide_Dilatable_base::initialiser(), Fluide_reel_base::initialiser(), mettre_a_jour(), Fluide_reel_base::mettre_a_jour(), Milieu_composite::mettre_a_jour(), Fluide_Dilatable_base::mettre_a_jour(), Milieu_composite::mettre_a_jour_tabs(), readOn(), Fluide_Dilatable_base::set_Cp(), set_param(), Espece::set_param(), update_rho_cp(), Fluide_Dilatable_base::update_rho_cp(), Fluide_Dilatable_base::verifier_coherence_champs(), Fluide_base::verifier_coherence_champs(), and Fluide_Incompressible::verifier_coherence_champs().
ch_beta_th_
TRUST_Deriv< Champ_Don_base > Milieu_base::ch_beta_th_ protected
Referenced by beta_t(), discretiser(), Fluide_reel_base::discretiser(), ecrire(), has_beta_t(), initialiser(), Fluide_reel_base::initialiser(), mettre_a_jour(), Fluide_reel_base::mettre_a_jour(), readOn(), set_param(), and Fluide_base::verifier_coherence_champs().
ch_porosites_
TRUST_Deriv< Champ_Don_base > Milieu_base::ch_porosites_ protected
Referenced by calculate_face_porosity(), ecrire(), get_porosites_champ(), has_porosites(), initialiser_porosite(), mettre_a_jour_porosite(), porosite_elem(), readOn(), Milieu_composite::readOn(), Milieu_MUSIG::readOn(), and set_additional_params().
ch_diametre_hyd_
TRUST_Deriv< Champ_Don_base > Milieu_base::ch_diametre_hyd_ protected
Referenced by calculate_face_hydr_diam(), diametre_hydraulique_elem(), initialiser_porosite(), mettre_a_jour_porosite(), readOn(), Milieu_composite::readOn(), Milieu_MUSIG::readOn(), and set_additional_params().
ch_rho_Cp_elem_
TRUST_Deriv< Champ_Fonc_base > Milieu_base::ch_rho_Cp_elem_ protected
Referenced by discretiser(), Fluide_reel_base::discretiser(), Fluide_Dilatable_base::initialiser(), update_rho_cp(), and Fluide_Dilatable_base::update_rho_cp().
ch_rho_Cp_comme_T_
TRUST_Deriv< Champ_Fonc_base > Milieu_base::ch_rho_Cp_comme_T_ protected
Referenced by discretiser(), Fluide_reel_base::discretiser(), initialiser(), Fluide_Dilatable_base::initialiser(), Fluide_reel_base::initialiser(), mettre_a_jour(), Fluide_reel_base::mettre_a_jour(), update_rho_cp(), and Fluide_Dilatable_base::update_rho_cp().
champs_compris_
Champs_compris Milieu_base::champs_compris_ protected
Referenced by Loi_Etat_base::champs_compris(), Fluide_Dilatable_base::creer_champ(), discretiser(), Fluide_Dilatable_base::discretiser(), Fluide_Weakly_Compressible::discretiser(), Fluide_base::discretiser(), Fluide_Ostwald::discretiser(), Fluide_reel_base::discretiser(), Milieu_composite::discretiser(), Solide::discretiser(), Constituant::discretiser_multi_concentration(), get_champ(), get_noms_champs_postraitables(), and has_champ().
porosite_face_
DoubleVect Milieu_base::porosite_face_ protected
Referenced by calculate_face_porosity(), discretiser_porosite(), fill_section_passage_face(), and porosite_face().
section_passage_face_
DoubleVect Milieu_base::section_passage_face_ protected
Referenced by fill_section_passage_face(), and section_passage_face().
diametre_hydraulique_face_
DoubleVect Milieu_base::diametre_hydraulique_face_ protected
Referenced by calculate_face_hydr_diam(), diametre_hydraulique_face(), and discretiser_diametre_hydro().
nom_
Nom Milieu_base::nom_ protected
Referenced by le_nom(), and nommer().
champs_don_
TRUST_List< TRUST_Ref< Champ_Don_base *> > Milieu_base::champs_don_ protected
Referenced by champs_don(), readOn(), Fluide_base::readOn(), and Solide::readOn().
indic_rayo_
Type_rayo Milieu_base::indic_rayo_ protected
Referenced by Fluide_base::fixer_type_rayo(), Fluide_Diphasique::Fluide_Diphasique(), Fluide_base::is_rayo_semi_transp(), Fluide_base::is_rayo_transp(), Milieu_base(), and Fluide_base::reset_type_rayo().
equation_
std::map<std::string, const Equation_base *> Milieu_base::equation_ mutable protected
Referenced by associer_equation(), Fluide_base::calculer_e_int(), Milieu_composite::calculer_masse_volumique(), Fluide_base::calculer_temperature_multiphase(), Fluide_base::creer_e_int(), Fluide_base::creer_temperature_multiphase(), equation(), Fluide_Dilatable_base::initialiser(), Milieu_composite::initialiser(), Fluide_base::initTimeStep(), Fluide_reel_base::initTimeStep(), Milieu_composite::initTimeStep(), update_rho_cp(), and Fluide_Dilatable_base::update_rho_cp().