TrioCFD: Champ_Fonc_P0_base Class Reference
Champ_Fonc_P0_base Class Reference
#include <Champ_Fonc_P0_base.h>
Public Member Functions
const Type_info * get_info () const override
DoubleTab & remplir_coord_noeuds (DoubleTab &positions) const override
int remplir_coord_noeuds_et_polys (DoubleTab &positions, IntVect &polys) const override
Public Member Functions inherited from Champ_Fonc_base
Champ_base & affecter_ (const Champ_base &) override
Champ_base & affecter_compo (const Champ_base &, int compo) override
int fixer_nb_valeurs_nodales (int nb_noeuds) override
const Type_info * get_info () const override
void mettre_a_jour (double temps) override
virtual DoubleTab & remplir_coord_noeuds (DoubleTab &) const
virtual DoubleTab & remplir_coord_noeuds_compo (DoubleTab &, int) const
virtual int remplir_coord_noeuds_et_polys (DoubleTab &, IntVect &) const
virtual int remplir_coord_noeuds_et_polys_compo (DoubleTab &, IntVect &, int) const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
DoubleTab & valeur_aux (const DoubleTab &, DoubleTab &) const override
Public Member Functions inherited from Champ_Don_base
void dimensionner (int, int)
int fixer_nb_valeurs_nodales (int nb_noeuds) override
const Type_info * get_info () const override
int imprime (Sortie &, int) const override
virtual int initialiser (const double temps)
void mettre_a_jour (double temps) override
int reprendre (Entree &) override
void resetTime (double time) override
int sauvegarder (Sortie &) const override
DoubleTab & valeurs () override
Public Member Functions inherited from Champ_base
Champ_base & affecter (const Champ_base &)
Champ_base ()
virtual double changer_temps (const double t)
const Type_info * get_info () const override
double temps () const
virtual DoubleTab & trace (const Frontiere_dis_base &, DoubleTab &, double, int distant) const
virtual DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const
virtual double valeur_a_compo (const DoubleVect &position, int ncomp) const
virtual DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &valeurs, int le_poly) const
virtual double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const
virtual DoubleVect & valeur_a_sommet (int, const Domaine &, DoubleVect &) const
virtual DoubleTab & valeur_aux (const DoubleTab &positions, DoubleTab &valeurs) const
virtual DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const
virtual DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const
virtual DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp) const
Public Member Functions inherited from Field_base
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
virtual void fixer_nb_comp (int i)
virtual const Nom & fixer_nom_compo (const Nom &)
virtual const Nom & fixer_nom_compo (int, const Nom &)
virtual const Noms & fixer_noms_compo (const Noms &)
virtual const Nom & fixer_unite (const Nom &)
virtual const Nom & fixer_unite (int i, const Nom &)
virtual const Noms & fixer_unites (const Noms &)
const Type_info * get_info () const override
const Nom & nom_compo (int) const
void nommer (const Nom &) override
const Nom & unite () const
const Nom & unite (int) const
const Noms & unites () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Champ_Proto
int lire_dimension (Entree &, const Nom &)
int lire_dimension (int dim, const Nom &le_nom_)
Public Member Functions inherited from Champ_implementation_P0
DoubleTab & valeur_aux_centres_de_gravite (const Domaine &, DoubleTab &valeurs) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Champ_Fonc_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Field_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Champ_Fonc_P0_base()
Champ_Fonc_P0_base::Champ_Fonc_P0_base ()
~Champ_Fonc_P0_base()
Champ_Fonc_P0_base::~Champ_Fonc_P0_base () override
Member Function Documentation
info()
const Type_info * Champ_Fonc_P0_base::info () static
get_info()
const Type_info * Champ_Fonc_P0_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
Reimplemented in Estimateur_Aposteriori_P0_VEF, Champ_Fonc_P0_MED, Champ_Fonc_Elem_PolyMAC, Champ_Fonc_Elem_PolyMAC_P0_rot, Champ_Fonc_Elem_PolyMAC_P0_TC, Champ_Fonc_Tabule_Elem_PolyMAC, grad_U_Champ_Face_PolyMAC, Champ_Ostwald, Champ_Fonc_P0_VDF, Champ_Fonc_Tabule_P0_VDF, Champ_Ostwald_VDF, Correlation_Vec_Sca_VDF, Critere_Q_Champ_Face, grad_U_Champ_Face, Rotationnel_Champ_Face, T_paroi_Champ_P0_VDF, Taux_cisaillement_P0_VDF, Y_plus_Champ_Face, Champ_Fonc_P0_VEF, Champ_Fonc_Tabule_P0_VEF, Champ_Ostwald_VEF, Critere_Q_Champ_P1NC, grad_T_Champ_P1NC, grad_U_Champ_P1NC, h_conv_Champ_P1NC, Rotationnel_Champ_P1NC, Rotationnel_Champ_Q1NC, T_paroi_Champ_P1NC, Taux_cisaillement_P0_VEF, and Y_plus_Champ_P1NC.
self_cast() [1/2]
Champ_Fonc_P0_base & Champ_Fonc_P0_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Champ_Fonc_P0_base & Champ_Fonc_P0_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Champ_Fonc_P0_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
Reimplemented in Estimateur_Aposteriori_P0_VEF, Champ_Fonc_P0_MED, Champ_Fonc_Elem_PolyMAC, Champ_Fonc_Elem_PolyMAC_P0_rot, Champ_Fonc_Elem_PolyMAC_P0_TC, Champ_Fonc_Tabule_Elem_PolyMAC, grad_U_Champ_Face_PolyMAC, Champ_Ostwald, Champ_Fonc_P0_VDF, Champ_Fonc_Tabule_P0_VDF, Champ_Ostwald_VDF, Correlation_Vec_Sca_VDF, Critere_Q_Champ_Face, grad_U_Champ_Face, Rotationnel_Champ_Face, T_paroi_Champ_P0_VDF, Taux_cisaillement_P0_VDF, Y_plus_Champ_Face, Champ_Fonc_P0_VEF, Champ_Fonc_Tabule_P0_VEF, Champ_Ostwald_VEF, Critere_Q_Champ_P1NC, grad_T_Champ_P1NC, grad_U_Champ_P1NC, h_conv_Champ_P1NC, Rotationnel_Champ_P1NC, Rotationnel_Champ_Q1NC, T_paroi_Champ_P1NC, Taux_cisaillement_P0_VEF, and Y_plus_Champ_P1NC.
References Field_base::le_nom(), and Objet_U::que_suis_je().
Referenced by Champ_Fonc_Interp::printOn().
readOn()
Entree & Champ_Fonc_P0_base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
Reimplemented in Estimateur_Aposteriori_P0_VEF, Champ_Fonc_P0_MED, Champ_Fonc_Elem_PolyMAC, Champ_Fonc_Elem_PolyMAC_P0_rot, Champ_Fonc_Elem_PolyMAC_P0_TC, Champ_Fonc_Tabule_Elem_PolyMAC, grad_U_Champ_Face_PolyMAC, Champ_Ostwald, Champ_Fonc_P0_VDF, Champ_Fonc_Tabule_P0_VDF, Champ_Ostwald_VDF, Correlation_Vec_Sca_VDF, Critere_Q_Champ_Face, grad_U_Champ_Face, Rotationnel_Champ_Face, T_paroi_Champ_P0_VDF, Taux_cisaillement_P0_VDF, Y_plus_Champ_Face, Champ_Fonc_P0_VEF, Champ_Fonc_Tabule_P0_VEF, Champ_Ostwald_VEF, Critere_Q_Champ_P1NC, grad_T_Champ_P1NC, grad_U_Champ_P1NC, h_conv_Champ_P1NC, Rotationnel_Champ_P1NC, Rotationnel_Champ_Q1NC, T_paroi_Champ_P1NC, Taux_cisaillement_P0_VEF, and Y_plus_Champ_P1NC.
trace()
DoubleTab & Champ_Fonc_P0_base::trace (const Frontiere_dis_base & fr, DoubleTab & x, double tps, int distant) const override virtual
Trace du champ P0 sur la frontiere.
Reimplemented from Champ_base.
References Champ_implementation_P0::trace(), and Champ_Don_base::valeurs().
affecter_()
Champ_base & Champ_Fonc_P0_base::affecter_ (const Champ_base & ch) override virtual
Implements Champ_base.
Reimplemented in Champ_Ostwald, and Champ_Fonc_Elem_PolyMAC.
References Champ_implementation_P0::affecter_(), and Champ_Fonc_base::affecter_().
fixer_nb_valeurs_nodales()
int Champ_Fonc_P0_base::fixer_nb_valeurs_nodales (int n) override virtual
Reimplemented from Champ_base.
Reimplemented in Champ_Ostwald.
References Champ_Fonc_base::creer_tableau_distribue(), Domaine_dis_base::domaine(), Domaine_32_64< _SIZE_ >::md_vector_elements(), and Domaine_32_64< _SIZE_ >::nb_elem().
Referenced by Modele_turbulence_hyd_LES_DSGS_VDF::associer(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::associer(), EF_discretisation::creer_champ_vorticite(), PolyMAC_P0_discretisation::creer_champ_vorticite(), VDF_discretisation::creer_champ_vorticite(), VEF_discretisation::creer_champ_vorticite(), VDF_discretisation::critere_Q(), VEF_discretisation::critere_Q(), EF_discretisation::distance_paroi(), PolyMAC_discretisation::distance_paroi(), VEF_discretisation::distance_paroi(), VDF_discretisation::grad_u(), VEF_discretisation::grad_u(), PolyMAC_discretisation::grad_u(), VEF_discretisation::h_conv(), VDF_discretisation::t_paroi(), VEF_discretisation::t_paroi(), PolyMAC_P0_discretisation::taux_cisaillement(), VDF_discretisation::taux_cisaillement(), VEF_discretisation::taux_cisaillement(), EF_discretisation::vorticite(), VDF_discretisation::vorticite(), VEF_discretisation::vorticite(), VDF_discretisation::y_plus(), EF_discretisation::y_plus(), and VEF_discretisation::y_plus().
moyenne() [1/2]
double Champ_Fonc_P0_base::moyenne (const DoubleVect & porosite_elem, int ncomp) const
References Champ_Fonc_base::le_dom_VF, Process::mp_sum(), Domaine_dis_base::nb_elem(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), and Domaine_VF::volumes().
moyenne() [2/2]
DoubleVect Champ_Fonc_P0_base::moyenne (const DoubleVect & porosite_elem) const
References Champ_Fonc_base::le_dom_VF, Field_base::nb_comp(), Domaine_dis_base::nb_elem(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), and Domaine_VF::volumes().
imprime()
int Champ_Fonc_P0_base::imprime (Sortie & os, int ncomp) const override virtual
Implements Champ_base.
Reimplemented in Champ_Fonc_P0_VDF.
References Champ_implementation_P0::imprime_P0().
mettre_a_jour()
void Champ_Fonc_P0_base::mettre_a_jour (double) override virtual
mettre_a_jour de la classe de base Champ_base :ne fait rien !
Reimplemented from Champ_base.
Reimplemented in Champ_Ostwald, Champ_Ostwald_VDF, Champ_Ostwald_VEF, Champ_Fonc_Elem_PolyMAC_P0_rot, Estimateur_Aposteriori_P0_VEF, Champ_Fonc_P0_MED, Champ_Fonc_Elem_PolyMAC_P0_TC, Champ_Fonc_Tabule_Elem_PolyMAC, grad_U_Champ_Face_PolyMAC, Champ_Fonc_Tabule_P0_VDF, Correlation_Vec_Sca_VDF, Critere_Q_Champ_Face, grad_U_Champ_Face, Rotationnel_Champ_Face, T_paroi_Champ_P0_VDF, Taux_cisaillement_P0_VDF, Y_plus_Champ_Face, Champ_Fonc_Tabule_P0_VEF, Critere_Q_Champ_P1NC, grad_T_Champ_P1NC, grad_U_Champ_P1NC, h_conv_Champ_P1NC, Rotationnel_Champ_P1NC, Rotationnel_Champ_Q1NC, T_paroi_Champ_P1NC, Taux_cisaillement_P0_VEF, and Y_plus_Champ_P1NC.
References Champ_Fonc_base::mettre_a_jour().
Referenced by Champ_Fonc_Interp::mettre_a_jour().
valeur_au_bord()
double Champ_Fonc_P0_base::valeur_au_bord (int face) const
References Domaine_VF::face_voisins(), Champ_Fonc_base::le_dom_VF, TRUST_Ref< _CLASSE_ >::valeur(), and Champ_Don_base::valeurs().
valeur_a_elem()
DoubleVect & Champ_Fonc_P0_base::valeur_a_elem (const DoubleVect & position, DoubleVect & result, int poly) const inline override virtual
Implements Champ_implementation.
References Champ_implementation_P0::valeur_a_elem().
valeur_a_elem_compo()
double Champ_Fonc_P0_base::valeur_a_elem_compo (const DoubleVect & position, int poly, int ncomp) const inline override virtual
Implements Champ_implementation.
References Champ_implementation_P0::valeur_a_elem_compo().
valeur_aux_centres_de_gravite()
DoubleTab & Champ_Fonc_P0_base::valeur_aux_centres_de_gravite (const Domaine & dom, DoubleTab & valeurs) const inline override virtual
Cette methode, generique mais lente (calcul des centres de gravite, remplissage les_poly, utilisation des fonctions de forme dans le Champ discretise) peut etre surchargee par le champ dicretise pour une implementation beaucoup plus rapide.
Reimplemented from Champ_base.
References Champ_implementation_P0::valeur_aux_centres_de_gravite().
valeur_aux_elems()
DoubleTab & Champ_Fonc_P0_base::valeur_aux_elems (const DoubleTab & positions, const IntVect & polys, DoubleTab & result) const inline override virtual
Implements Champ_implementation.
References Champ_implementation_P0::valeur_aux_elems().
Referenced by Champ_Fonc_Tabule_P0_EF::mettre_a_jour(), Champ_Fonc_Tabule_Elem_PolyMAC::mettre_a_jour(), Champ_Fonc_Tabule_P0_VDF::mettre_a_jour(), and Champ_Fonc_Tabule_P0_VEF::mettre_a_jour().
valeur_aux_elems_compo()
DoubleVect & Champ_Fonc_P0_base::valeur_aux_elems_compo (const DoubleTab & positions, const IntVect & polys, DoubleVect & result, int ncomp) const inline override virtual
Implements Champ_implementation.
References Champ_implementation_P0::valeur_aux_elems_compo().
valeur_aux_sommets()
DoubleTab & Champ_Fonc_P0_base::valeur_aux_sommets (const Domaine & domain, DoubleTab & result) const inline override virtual
Reimplemented from Champ_implementation.
References Champ_implementation::valeur_aux_sommets().
valeur_aux_sommets_compo()
DoubleVect & Champ_Fonc_P0_base::valeur_aux_sommets_compo (const Domaine & domain, DoubleVect & result, int ncomp) const inline override virtual
Reimplemented from Champ_implementation.
References Champ_implementation::valeur_aux_sommets_compo().
remplir_coord_noeuds()
DoubleTab & Champ_Fonc_P0_base::remplir_coord_noeuds (DoubleTab & coord) const inline override virtual
NE FAIT RIEN A surcharger dans les classes derivees.
Parameters
(DoubleTab& coord)
Returns
(DoubleTab&) renvoie toujours le parametre coord
Reimplemented from Champ_Fonc_base.
References Champ_implementation_P0::remplir_coord_noeuds().
Referenced by Champ_Ostwald::affecter_().
remplir_coord_noeuds_et_polys()
int Champ_Fonc_P0_base::remplir_coord_noeuds_et_polys (DoubleTab & , IntVect &) const inline override virtual
NE FAIT RIEN A surcharger dans les classes derivees.
Parameters
(DoubleTab&)
(IntVect&)
Returns
(int) renvoie toujours 0
Reimplemented from Champ_Fonc_base.
References Champ_implementation_P0::remplir_coord_noeuds_et_polys().
Referenced by Champ_Ostwald::affecter_().
le_champ() [1/2]
Champ_base & Champ_Fonc_P0_base::le_champ () inline override protected virtual
Implements Champ_implementation.
Referenced by Champ_Fonc_P1_DG::valeur_aux_elems().
le_champ() [2/2]
const Champ_base & Champ_Fonc_P0_base::le_champ () const inline override protected virtual
Implements Champ_implementation.
Member Data Documentation
info_obj
const Type_info Champ_Fonc_P0_base::info_obj static