TrioCFD: Modele_Rayonnement_Milieu_Transparent Class Reference
Modele_Rayonnement_Milieu_Transparent Class Reference
#include <Modele_Rayonnement_Milieu_Transparent.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
~Modele_Rayonnement_Milieu_Transparent()
Modele_Rayonnement_Milieu_Transparent::~Modele_Rayonnement_Milieu_Transparent ()
Modele_Rayonnement_Milieu_Transparent()
Modele_Rayonnement_Milieu_Transparent::Modele_Rayonnement_Milieu_Transparent (double Sigma = 5.67e-8) inline
Member Function Documentation
cree_instance()
Objet_U * Modele_Rayonnement_Milieu_Transparent::cree_instance () static
taille_memoire()
unsigned Modele_Rayonnement_Milieu_Transparent::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Modele_Rayonnement_Milieu_Transparent::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Modele_Rayonnement_Milieu_Transparent::info () static
get_info()
const Type_info * Modele_Rayonnement_Milieu_Transparent::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Modele_Rayonnement_base.
self_cast() [1/2]
Modele_Rayonnement_Milieu_Transparent & Modele_Rayonnement_Milieu_Transparent::self_cast (Objet_U & r) static
self_cast() [2/2]
const Modele_Rayonnement_Milieu_Transparent & Modele_Rayonnement_Milieu_Transparent::self_cast (const Objet_U & r) static
printOn()
Sortie & Modele_Rayonnement_Milieu_Transparent::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Modele_Rayonnement_base.
readOn()
Entree & Modele_Rayonnement_Milieu_Transparent::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Modele_Rayonnement_base.
References Process::abort(), Process::exit(), fic_mat_ray_inv_bin_, Fluide_base::fixer_type_rayo(), Objet_U::interprete(), inversion_debut_, lire_fichiers(), lire_matrice_inv_, Probleme_base::milieu(), nom_pb_rayonnant_, Objet_U::que_suis_je(), relaxation_, and Motcles::search().
discretiser()
void Modele_Rayonnement_Milieu_Transparent::discretiser (const Discretisation_base & dis, const Domaine & domaine) override virtual
Implements Modele_Rayonnement_base.
References Face_Rayonnante::ensembles_faces_bord(), face_rayonnante(), Ensemble_Faces_base::lire(), Face_Rayonnante::nb_ensembles_faces(), nb_faces_totales(), Face_Rayonnante::nom_bord_rayo(), Face_Rayonnante::nom_bord_rayo_lu(), and Objet_U::que_suis_je().
mettre_a_jour()
void Modele_Rayonnement_Milieu_Transparent::mettre_a_jour (double temps) override virtual
Implements Modele_Rayonnement_base.
preparer_calcul()
void Modele_Rayonnement_Milieu_Transparent::preparer_calcul () override virtual
Implements Modele_Rayonnement_base.
References TRUSTTab< _TYPE_, _SIZE_ >::decomp_LU(), Face_Rayonnante::emissivite(), Process::exit(), fic_mat_ray_inv_bin_, Sortie_Fichier_base::flush(), inversion_debut_, Process::je_suis_maitre(), lire_matrice_inv_, nb_faces_rayonnantes(), nb_faces_totales(), nom_fic_mat_ray_inv_, Sortie_Fichier_base::precision(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTTab< _TYPE_, _SIZE_ >::resoud_LU(), Sortie_Fichier_base::setf(), and SIGMA.
flux_radiatif()
double Modele_Rayonnement_Milieu_Transparent::flux_radiatif (int num_face_global) const
References Ensemble_Faces_base::contient(), Process::exit(), Frontiere_dis_base::frontiere(), Cond_lim_base::frontiere_dis(), Ensemble_Faces_base::la_cl_base(), Process::me(), Frontiere_32_64< _SIZE_ >::nb_faces(), Ensemble_Faces_base::nb_faces_bord(), nb_faces_totales(), Frontiere_32_64< _SIZE_ >::num_premiere_face(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), and TRUSTVect< _TYPE_, _SIZE_ >::size().
Referenced by Echange_contact_Rayo_transp_VDF::calculer_Teta_paroi(), and Champ_front_contact_rayo_transp_VEF::mettre_a_jour_flux_radiatif().
nb_faces_rayonnantes()
int Modele_Rayonnement_Milieu_Transparent::nb_faces_rayonnantes () const inline
Referenced by Pb_Couple_Rayonnement::completer(), lire_fichiers(), and preparer_calcul().
nb_faces_totales()
int Modele_Rayonnement_Milieu_Transparent::nb_faces_totales () const inline
Referenced by Pb_Couple_Rayonnement::completer(), discretiser(), flux_radiatif(), and preparer_calcul().
ordre_matrice_fac_forme()
int Modele_Rayonnement_Milieu_Transparent::ordre_matrice_fac_forme () const inline
face_rayonnante() [1/2]
const Face_Rayonnante & Modele_Rayonnement_Milieu_Transparent::face_rayonnante (int j) const inline
Referenced by Pb_Couple_Rayonnement::completer(), and discretiser().
face_rayonnante() [2/2]
Face_Rayonnante & Modele_Rayonnement_Milieu_Transparent::face_rayonnante (int j) inline
lire_fichiers() [1/2]
void Modele_Rayonnement_Milieu_Transparent::lire_fichiers (Nom & nom1, Nom & nom2)
References TRUST_Vector< _CLASSE_ >::dimensionner(), Process::exit(), lire_matrice_inv_, nb_faces_rayonnantes(), and TRUSTTab< _TYPE_, _SIZE_ >::resize().
Referenced by lire_fichiers(), and readOn().
lire_fichiers() [2/2]
void Modele_Rayonnement_Milieu_Transparent::lire_fichiers (Nom & nom1, Nom & nom2, Nom & nom3)
References Process::exit(), inversion_debut_, lire_fichiers(), lire_matrice_inv_, and nom_fic_mat_ray_inv_.
processeur_rayonnant() [1/2]
int Modele_Rayonnement_Milieu_Transparent::processeur_rayonnant () inline
References processeur_rayonnant_.
Referenced by Pb_Couple_Rayonnement::postraiter().
processeur_rayonnant() [2/2]
int Modele_Rayonnement_Milieu_Transparent::processeur_rayonnant () const inline
References processeur_rayonnant_.
associer_processeur_rayonnant()
void Modele_Rayonnement_Milieu_Transparent::associer_processeur_rayonnant (int proc) inline
References processeur_rayonnant_.
Referenced by Pb_Couple_Rayonnement::completer().
relaxation()
double Modele_Rayonnement_Milieu_Transparent::relaxation () const inline
References relaxation_.
Referenced by Echange_contact_Rayo_transp_VDF::calculer_Teta_paroi().
nom_pb_rayonnant() [1/2]
const Nom & Modele_Rayonnement_Milieu_Transparent::nom_pb_rayonnant () const inline
References nom_pb_rayonnant_.
Referenced by Pb_Couple_Rayonnement::completer().
nom_pb_rayonnant() [2/2]
Nom & Modele_Rayonnement_Milieu_Transparent::nom_pb_rayonnant () inline
References nom_pb_rayonnant_.
Member Data Documentation
info_obj
const Type_info Modele_Rayonnement_Milieu_Transparent::info_obj static
SIGMA
double Modele_Rayonnement_Milieu_Transparent::SIGMA protected
Referenced by preparer_calcul().
inversion_debut_
int Modele_Rayonnement_Milieu_Transparent::inversion_debut_ protected
Referenced by lire_fichiers(), preparer_calcul(), and readOn().
lire_matrice_inv_
int Modele_Rayonnement_Milieu_Transparent::lire_matrice_inv_ protected
Referenced by lire_fichiers(), preparer_calcul(), and readOn().
fic_mat_ray_inv_bin_
int Modele_Rayonnement_Milieu_Transparent::fic_mat_ray_inv_bin_ protected
Referenced by preparer_calcul(), and readOn().
nom_fic_mat_ray_inv_
Nom Modele_Rayonnement_Milieu_Transparent::nom_fic_mat_ray_inv_ protected
Referenced by lire_fichiers(), and preparer_calcul().
processeur_rayonnant_
int Modele_Rayonnement_Milieu_Transparent::processeur_rayonnant_ protected
Referenced by associer_processeur_rayonnant(), and processeur_rayonnant().
relaxation_
double Modele_Rayonnement_Milieu_Transparent::relaxation_ protected
Referenced by readOn(), and relaxation().
nom_pb_rayonnant_
Nom Modele_Rayonnement_Milieu_Transparent::nom_pb_rayonnant_ protected
Referenced by nom_pb_rayonnant(), and readOn().