TrioCFD: Transport_turbulent_GGDH Class Reference
Transport_turbulent_GGDH Class Reference
#include <Transport_turbulent_GGDH.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
< u'_i theta'> = - C_s * k / epsilon * <u'_i u'_j> * d_j theta
Constructor & Destructor Documentation
Transport_turbulent_GGDH()
Transport_turbulent_GGDH::Transport_turbulent_GGDH ()
~Transport_turbulent_GGDH()
Transport_turbulent_GGDH::~Transport_turbulent_GGDH ()
Member Function Documentation
cree_instance()
Objet_U * Transport_turbulent_GGDH::cree_instance () static
taille_memoire()
unsigned Transport_turbulent_GGDH::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Transport_turbulent_GGDH::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Transport_turbulent_GGDH::info () static
get_info()
const Type_info * Transport_turbulent_GGDH::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Transport_turbulent_base.
self_cast() [1/2]
Transport_turbulent_GGDH & Transport_turbulent_GGDH::self_cast (Objet_U & r) static
self_cast() [2/2]
const Transport_turbulent_GGDH & Transport_turbulent_GGDH::self_cast (const Objet_U & r) static
printOn()
Sortie & Transport_turbulent_GGDH::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Transport_turbulent_base.
readOn()
Entree & Transport_turbulent_GGDH::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Transport_turbulent_base.
References Param::ajouter(), Objet_U::dimension, Param::lire_avec_accolades_depuis(), and Objet_U::que_suis_je().
dimension_min_nu()
virtual int Transport_turbulent_GGDH::dimension_min_nu () const inline override virtual
Implements Transport_turbulent_base.
References Objet_U::dimension.
gradu_required()
virtual int Transport_turbulent_GGDH::gradu_required () const inline override virtual
Reimplemented from Transport_turbulent_base.
modifier_mu()
void Transport_turbulent_GGDH::modifier_mu (const Convection_Diffusion_std & eq, const Viscosite_turbulente_base & visc_turb, DoubleTab & nu) const override virtual
Implements Transport_turbulent_base.
References MD_Vector_tools::creer_tableau_distribue(), Convection_Diffusion_std::diffusivite_pour_pas_de_temps(), Convection_Diffusion_std::diffusivite_pour_transport(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, TRUSTVect< _TYPE_, _SIZE_ >::get_md_vector(), Viscosite_turbulente_base::k_over_eps(), Viscosite_turbulente_base::limiteur(), Champ_Proto::passe(), Correlation_base::pb_, Viscosite_turbulente_base::reynolds_stress(), and TRUST_Ref< _CLASSE_ >::valeur().
Member Data Documentation
info_obj
const Type_info Transport_turbulent_GGDH::info_obj static