TrioCFD: Parcours_interface Class Reference
Parcours_interface Class Reference
#include <Parcours_interface.h>
Public Member Functions
void associer_domaine_dis (const Domaine_dis_base &domaine_dis)
int calculer_face_sortie_element (const Domaine_VF &domaine_vf, const int num_element, double x0, double y0, double z0, double x1, double y1, double z1, double &pos_intersection) const
int calculer_sortie_face_bord (const int face_0, const int num_element, double x0, double y0, double z0, double x1, double y1, double z1, double &x, double &y, double &z) const
double get_erreur_geometrique () const
const Type_info * get_info () const override
void projeter_vecteur_sur_face (const int num_face, double &x_, double &y_, double &z_) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
int calcul_intersection_facelem_3D (const Domaine_VF &domaine_vf, Maillage_FT_Disc &maillage, int num_facette, int num_element) const
CutFace_Properties coupe_face_rectangulaire (const Domaine_VF &domaine_vf, int num_element, int num_face, const DoubleTab &poly_reelles, const FTd_vecteur3 &norme, const ArrOfInt &polygone_plan_coupe, double epsilon) const
int eloigner_sommets_des_faces (Maillage_FT_Disc &maillage) const
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
void transformation_2d (const FTd_vecteur2 &origine, const FTd_matrice22 &matrice, double x, double y, double &u, double &v) const
double uzawa2 (const Domaine_VF &domaine_vf, const int elem, double &x, double &y, double &z) const
CutCell_Properties volume_barycentre_hexaedre (const Domaine_VF &domaine_vf, int num_element, const DoubleTab &poly_reelles, const FTd_vecteur3 &norme, const FTd_vecteur3 &centre_de_gravite, const ArrOfInt &polygone_plan_coupe, double epsilon) const
double volume_barycentre_rectangle (const Domaine_VF &domaine_vf, int num_element, double x0, double y0, double x1, double y1, double epsilon, double liquid_barycentre[3]) const
double volume_tetraedre (const Domaine_VF &domaine_vf, int num_element, int num_facette, const Maillage_FT_Disc &maillage, const DoubleTab &poly_reelles, const FTd_vecteur3 &centre_de_gravite, double epsilon) const
double volume_tetraedre_reference (const DoubleTab &poly_reelles_ref, const FTd_vecteur3 &norme_ref, const FTd_vecteur3 &centre_de_gravite_ref, double epsilon) const
double volume_triangle (const Domaine_VF &domaine_vf, int num_element, double x0, double y0, double x1, double y1, int plan_coupe0, int plan_coupe1) const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Static Protected Member Functions
static void calcul_inverse_matrice33 (const FTd_matrice33 &matrice, FTd_matrice33 &matrice_inv)
static void calcul_produit_matrice33_vecteur (const FTd_matrice33 &matrice, const FTd_vecteur3 &vect, FTd_vecteur3 &res)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Member Enumeration Documentation
anonymous enum
anonymous enum protected
Enumerator
TRIANGLE
RECTANGLE
TETRA
HEXA
Constructor & Destructor Documentation
~Parcours_interface()
Parcours_interface::~Parcours_interface ()
Parcours_interface()
Parcours_interface::Parcours_interface ()
References correction_parcours_thomas_, domaine_elem_ptr, domaine_sommets_ptr, Erreur_max_coordonnees_, Erreur_relative_maxi_, parcours_sans_tolerance_, and Valeur_max_coordonnees_.
Member Function Documentation
cree_instance()
Objet_U * Parcours_interface::cree_instance () static
taille_memoire()
unsigned Parcours_interface::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Parcours_interface::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Parcours_interface::info () static
get_info()
const Type_info * Parcours_interface::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
Parcours_interface & Parcours_interface::self_cast (Objet_U & r) static
self_cast() [2/2]
const Parcours_interface & Parcours_interface::self_cast (const Objet_U & r) static
printOn()
Sortie & Parcours_interface::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
readOn()
Entree & Parcours_interface::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
References Param::ajouter(), Param::ajouter_flag(), correction_parcours_thomas_, Erreur_relative_maxi_, Param::lire_avec_accolades_depuis(), TRUST_Ref< _CLASSE_ >::non_nul(), parcours_sans_tolerance_, Objet_U::que_suis_je(), refdomaine_vf_, and update_erreur_coords_max().
associer_domaine_dis()
void Parcours_interface::associer_domaine_dis (const Domaine_dis_base & domaine_dis)
Remplissage des variables persistantes de la classe (refdomaine_vf_, nb_faces_elem_, nb_elements_reels_, type_element_,.
equations_plans_faces_).
References Objet_U::bidim_axi, Objet_U::dimension, Domaine_dis_base::domaine(), domaine_elem_ptr, domaine_sommets_ptr, drapeaux_elements_parcourus_, equations_plans_faces_, Process::exit(), Domaine_VF::face_normales(), HEXA, Domaine_32_64< _SIZE_ >::nb_elem(), nb_elements_reels_, Domaine_VF::nb_faces(), Domaine_32_64< _SIZE_ >::nb_faces_elem(), nb_faces_elem_, Domaine_VF::nb_som_face(), nb_sommets_par_face_, TRUST_Ref< _CLASSE_ >::non_nul(), Objet_U::que_suis_je(), RECTANGLE, refdomaine_vf_, TRUSTTab< _TYPE_, _SIZE_ >::resize(), ArrOfBit_32_64< _SIZE_ >::resize_array(), TETRA, TRIANGLE, Domaine_32_64< _SIZE_ >::type_elem(), type_element_, update_erreur_coords_max(), and Domaine_VF::xv().
Referenced by Transport_Interfaces_FT_Disc::discretiser(), and IJK_Interfaces::initialize().
associer_connectivite_frontieres()
void Parcours_interface::associer_connectivite_frontieres (const Connectivite_frontieres & connect)
References refconnect_front_.
Referenced by Transport_Interfaces_FT_Disc::discretiser(), and IJK_Interfaces::initialize().
calculer_face_sortie_element()
int Parcours_interface::calculer_face_sortie_element (const Domaine_VF & domaine_vf, const int num_element, double x0, double y0, double z0, double x1, double y1, double z1, double & pos_intersection) const
Pour un point P0 (x0, y0, z0) a l'INTERIEUR de l'element num_element et un autre point P1 (x1, y1, z1), calcule l'intersection du segment (P0,P1)
avec les bords de l'element. Si le point P1 est sur un bord de l'element (a epsilon pres), on considere qu'il est a l'interieur et on ne reporte aucune intersection. Si on trouve une intersection I, on met dans pos_intersection la coordonnee barycentrique de l'intersection definie par I = (1-pos) * P0 + pos * P1 Si on ne trouve pas d'intersection, pos_intersection est inchange. Valeur de retour: Si une intersection a ete trouvee, numero de la face de sortie dans le domaine_vf (peut servir d'index dans face_voisins par exemple). Sinon, renvoie -1.
References calcul_eq_plan(), Domaine_VF::elem_faces(), Erreur_max_coordonnees_, and nb_faces_elem_.
Referenced by calculer_sortie_face_bord(), and Maillage_FT_Disc::deplacer_un_point().
calculer_sortie_face_bord()
int Parcours_interface::calculer_sortie_face_bord (const int face_0, const int num_element, double x0, double y0, double z0, double x1, double y1, double z1, double & x, double & y, double & z) const
Methode outil de Maillage_FT_Disc::deplacer_un_point dans le cas d'un marqueur de la ligne de contact.
P0 est la position initiale du marqueur en contact (sur la face_bord) P1 est la position finale visee apres le deplacement Pour un point P0(x0,y0,z0) sur la face "face_bord" et un point P1(x1,y1,z1), on determine la projection orthogonale p(P1) de P1 sur le plan contenant la face, et on calcule l'intersection (x,y,z) du segment [P0,p(P1)] avec les bords de la face. S'il n'y a pas d'intersection, (x,y,z)=p(P1) et la valeur de retour est -1, sinon la valeur de retour est le numero de l'arete de la face qui est coupee par le segment [P0,p(P1)] (aretes telles qu'elles sont definies dans la classe Connectivite_frontieres).
Parameters
(domaine_vf) le Domaine_VF a laquelle se rapportent les indices de face et d'element
(face_0) le numero de la face reelle sur laquelle se trouve le point P0
(num_element) un numero d'element voisin de la face face_0
(x0,y0,z0) Coordonnees du point P0 (en 2D, z0 est ignore)
(x1,y1,z1) Coordonnees du point P1 (en 2D, z1 est ignore)
(x,y,z) On met dans (x,y,z) les coordonnees de l'intersection s'il y en a une, sinon on y met les coordonnees de p(P1) qui est sur la face "face_0" Valeur de retour: -1 s'il n'y a pas d'intersection sinon le numero de la face de bord ou passe le sommet
References calculer_face_sortie_element(), Connectivite_frontieres::def_face_aretes(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, equations_plans_faces_, Process::exit(), Domaine_VF::face_sommets(), Domaine_VF::face_voisins(), Connectivite_frontieres::faces_voisins(), Process::me(), nb_sommets_par_face_, refconnect_front_, refdomaine_vf_, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Maillage_FT_Disc::deplacer_un_point().
distance_sommet_faces()
double Parcours_interface::distance_sommet_faces (const Domaine_VF & domaine_vf, const int num_element, double x, double y, double z) const
References calcul_eq_plan(), and nb_faces_elem_.
Referenced by Maillage_FT_Disc::check_sommets(), and eloigner_sommets_des_faces().
get_erreur_geometrique()
double Parcours_interface::get_erreur_geometrique () const
Renvoie une estimation de l'erreur geometrique (valeur homogene a une distance).
Par exemple si le domaine a une dimension caracteristique de 1e-3 et si la precision relative des calculs Erreur_relative_maxi_ est fixee a 1E-14 (valeur fixee dans le code source) alors get_erreur_geometrique renvoie 1E-17. Cette valeur est identique sur tous les processeurs et est calculee a partir de la taille du domaine.
References Erreur_max_coordonnees_.
Referenced by Maillage_FT_Disc::check_sommets().
get_correction_parcours_thomas()
int Parcours_interface::get_correction_parcours_thomas () const inline
References correction_parcours_thomas_.
Referenced by IJK_Interfaces::activate_cut_cell(), and IJK_Interfaces::printOn().
get_parcours_sans_tolerance()
int Parcours_interface::get_parcours_sans_tolerance () const inline
References parcours_sans_tolerance_.
Referenced by IJK_Interfaces::activate_cut_cell(), and IJK_Interfaces::printOn().
set_correction_parcours_thomas()
void Parcours_interface::set_correction_parcours_thomas () inline
References correction_parcours_thomas_.
Referenced by IJK_Interfaces::activate_cut_cell().
set_parcours_sans_tolerance()
void Parcours_interface::set_parcours_sans_tolerance () inline
References parcours_sans_tolerance_.
Referenced by IJK_Interfaces::activate_cut_cell().
projeter_vecteur_sur_face()
void Parcours_interface::projeter_vecteur_sur_face (const int num_face, double & x_, double & y_, double & z_) const
Methode outil utilisee pour le traitement des lignes de contact.
Projection du vecteur x_, y_, z_ sur le plan parallele a la face num_face passant par l'origine (permet d'obtenir la direction de deplacement d'un sommet sur une ligne de contact).
References equations_plans_faces_.
Referenced by Maillage_FT_Disc::calcul_courbure_sommets(), and Remaillage_FT::redistribuer_sommets().
calculer_normale_face_bord()
void Parcours_interface::calculer_normale_face_bord (int num_face, double x, double y, double z, double & nx_, double & ny_, double & nz_) const
References equations_plans_faces_, and refdomaine_vf_.
Referenced by Maillage_FT_Disc::calcul_courbure_sommets(), Triple_Line_Model_FT_Disc::compute_local_cos_theta(), and Remaillage_FT::supprimer_facettes_bord().
update_erreur_coords_max()
void Parcours_interface::update_erreur_coords_max () protected
References Erreur_max_coordonnees_, Erreur_relative_maxi_, refdomaine_vf_, and Valeur_max_coordonnees_.
Referenced by associer_domaine_dis(), and readOn().
parcourir()
void Parcours_interface::parcourir (Maillage_FT_Disc & maillage) const protected
References Process::check_int_overflow(), compteur_erreur_grossiere, correction_parcours_thomas_, Maillage_FT_Disc::desc_sommets(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Domaine_dis_base::domaine(), domaine_elem_ptr, domaine_sommets_ptr, Desc_Structure_FT::echange_espace_virtuel(), Maillage_FT_Disc::echanger_facettes(), eloigner_sommets_des_faces(), Maillage_FT_Disc::facettes_, Maillage_FT_Disc::intersections_elem_facettes_, Process::Journal(), Domaine_32_64< _SIZE_ >::les_elems(), Domaine_32_64< _SIZE_ >::les_sommets(), Process::mp_sum(), Domaine_dis_base::nb_elem(), TRUST_Ref< _CLASSE_ >::non_nul(), parcours_facette(), refdomaine_vf_, Intersections_Elem_Facettes::reset(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), Maillage_FT_Disc::sommet_elem_, Maillage_FT_Disc::sommets(), Maillage_FT_Disc::sommets_, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Maillage_FT_Disc::parcourir_maillage().
parcours_facette()
void Parcours_interface::parcours_facette (const Domaine_VF & domaine_vf, Maillage_FT_Disc & maillage, ArrOfInt & echange_facettes_numfacette, ArrOfInt & echange_facettes_numelement, int num_facette, int element_depart) const protected
References TRUSTArray< _TYPE_, _SIZE_ >::append_array(), calcul_intersection_facelem_2D(), calcul_intersection_facelem_3D(), Objet_U::dimension, drapeaux_elements_parcourus_, Domaine_VF::elem_faces(), Domaine_VF::face_voisins(), Intersections_Elem_Facettes::get_liste_elements_traverses(), Maillage_FT_Disc::intersections_elem_facettes_, Process::Journal(), nb_elements_reels_, nb_faces_elem_, TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), ArrOfBit_32_64< _SIZE_ >::setbit(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and ArrOfBit_32_64< _SIZE_ >::testsetbit().
Referenced by parcourir().
calcul_intersection_facelem_2D()
int Parcours_interface::calcul_intersection_facelem_2D (const Domaine_VF & domaine_vf, Maillage_FT_Disc & maillage, int num_facette, int num_element) const protected
References Intersections_Elem_Facettes::ajoute_intersection(), calcul_eq_plan(), compteur_erreur_grossiere, correction_parcours_thomas_, Objet_U::dimension, Erreur_max_coordonnees_, Process::exit(), Maillage_FT_Disc::facettes_, Maillage_FT_Disc::intersections_elem_facettes_, nb_faces_elem_, parcours_sans_tolerance_, Objet_U::precision_geom, RECTANGLE, Maillage_FT_Disc::sommet_ligne_contact(), Maillage_FT_Disc::sommets_, TRIANGLE, type_element_, volume_barycentre_rectangle(), and volume_triangle().
Referenced by parcours_facette().
calcul_intersection_facelem_3D()
int Parcours_interface::calcul_intersection_facelem_3D (const Domaine_VF & domaine_vf, Maillage_FT_Disc & maillage, int num_facette, int num_element) const protected
Cette methode permet de calculer l'intersection entre une facette et un element du maillage eulerien.
Precondition: dimension = 3
Parameters
(domaine_vf) domaine du calcul
(maillage) description du maillage de l'interface
(num_facette) indice de la facette intersectant
(num_element) indice de l'element intersecte
Returns
(int) 1 si ok, 0 si ??.
References Intersections_Elem_Facettes::ajoute_intersection(), TRUSTArray< _TYPE_, _SIZE_ >::append_array(), calcul_eq_plan(), Maillage_FT_Disc::calcul_normale_3D(), compteur_erreur_grossiere, correction_parcours_thomas_, coupe_face_rectangulaire(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Erreur_max_coordonnees_, Process::exit(), Maillage_FT_Disc::facettes_, HEXA, Maillage_FT_Disc::intersections_elem_facettes_, nb_faces_elem_, parcours_sans_tolerance_, Objet_U::precision_geom, TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), Maillage_FT_Disc::sommet_ligne_contact(), Maillage_FT_Disc::sommets_, TETRA, type_element_, volume_barycentre_hexaedre(), and volume_tetraedre().
Referenced by parcours_facette().
calcul_eq_plan()
double Parcours_interface::calcul_eq_plan (const Domaine_VF & domaine_vf, const int num_element, const int num_face_element, double & a, double & b, double & c, double & d) const inline protected
References Domaine_VF::elem_faces(), equations_plans_faces_, Domaine_VF::face_voisins(), refdomaine_vf_, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by calcul_intersection_facelem_2D(), calcul_intersection_facelem_3D(), calculer_face_sortie_element(), distance_sommet_faces(), and uzawa2().
volume_rectangle()
double Parcours_interface::volume_rectangle (const Domaine_VF & domaine_vf, int num_element, double x0, double y0, double x1, double y1, double epsilon) const inline protected
References Maillage_FT_Disc::angle_bidim_axi(), Objet_U::bidim_axi, Domaine_VF::elem_faces(), Erreur_relative_maxi_, and Domaine_VF::xv().
volume_barycentre_rectangle()
double Parcours_interface::volume_barycentre_rectangle (const Domaine_VF & domaine_vf, int num_element, double x0, double y0, double x1, double y1, double epsilon, double bary[3]) const protected
Calcul de la matrice 2x2 de transformation pour passer d'une coordonnee dans le repere (x,y) global a une coordonnee (u,v,1-u-v) barycentrique.
dans un element fini triangulaire. Le point 0 du triangle aura pour coordonnees (0,0,1) Le point 1 (1,0,0) Le point 2 (0,1,0)
References Maillage_FT_Disc::angle_bidim_axi(), Objet_U::bidim_axi, Domaine_VF::elem_faces(), Erreur_relative_maxi_, and Domaine_VF::xv().
Referenced by calcul_intersection_facelem_2D().
volume_triangle()
double Parcours_interface::volume_triangle (const Domaine_VF & domaine_vf, int num_element, double x0, double y0, double x1, double y1, int plan_coupe0, int plan_coupe1) const inline protected
Calcul de la contribution de volume d'une facette a la valeur de l'indicatrice dans un element.
(x0,y0) et (x1,y1) sont les coordonnees de l'extremite du segment (obligatoirement a l'interieur du triangle ou sur un bord). plan_coupe* donne le numero de la face du triangle sur laquelle se trouve chacun des deux sommets du segment ou -1 si le sommet est strictement a l'interieur du triangle. C'est une fraction du volume de l'element comprise entre Erreur_relative_maxi et 1.-Erreur_relative_maxi
sommet2 ^ ordonnee=v |. | . | . | . face 0 (opposee au sommet 0) | . | 0—1. | : A :. | : :B. -----— -> abscisse=u (coordonnees dans le triangle de reference : u,v) sommet0 sommet1
References Objet_U::bidim_axi, Erreur_relative_maxi_, matrice_triangle(), and transformation_2d().
Referenced by calcul_intersection_facelem_2D().
volume_tetraedre()
double Parcours_interface::volume_tetraedre (const Domaine_VF & domaine_vf, int num_element, int num_facette, const Maillage_FT_Disc & maillage, const DoubleTab & poly_reelles, const FTd_vecteur3 & centre_de_gravite, double epsilon) const protected
Calcul de la contribution de volume d'une facette a la valeur de l'indicatrice dans un element.
C'est une fraction du volume de l'element comprise entre epsilon et 1.-epsilon
Precondition: dimension = 3
Parameters
(domaine_vf) domaine du calcul
(num_element) indice de l'element intersecte
(poly_reelles) coordonnees (reelles) des sommets definissant une surface contenue dans l'element (en pratique : surface d'intersection entre une facette d'interface et l'element)
(centre_de_gravite) centre de gravite de la surface
(epsilon) erreur relative
Returns
(double) contribution du volume engendre par la surface dans l'element
References calcul_inverse_matrice33(), calcul_produit_matrice33_vecteur(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, domaine_sommets_ptr, Maillage_FT_Disc::facettes_, Maillage_FT_Disc::sommets_, and volume_tetraedre_reference().
Referenced by calcul_intersection_facelem_3D().
volume_tetraedre_reference()
double Parcours_interface::volume_tetraedre_reference (const DoubleTab & poly_reelles_ref, const FTd_vecteur3 & norme_ref, const FTd_vecteur3 & centre_de_gravite_ref, double epsilon) const protected
Calcul de la contribution de volume d'une facette a la valeur de l'indicatrice dans le tetraedre de reference.
Dans ce tetraedre, on utilise le plan OXZ comme plan de projection (projection selon OY donc)
Precondition: la surface doit etre un triangle (nb_sommets_poly==3)
Parameters
(poly_reelles_ref) coordonnees (reelles) des sommets l'element de reference
(norme) normale a la surface, dans l'element de reference
(centre_de_gravite,dans l'element de reference) centre de gravite de la surface
(epsilon) erreur relative
Returns
(double) contribution du volume engendre par la surface dans l'element
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, and Erreur_relative_maxi_.
Referenced by volume_tetraedre().
volume_barycentre_hexaedre()
CutCell_Properties Parcours_interface::volume_barycentre_hexaedre (const Domaine_VF & domaine_vf, int num_element, const DoubleTab & poly_reelles, const FTd_vecteur3 & norme, const FTd_vecteur3 & centre_de_gravite, const ArrOfInt & polygone_plan_coupe, double epsilon) const protected
Calcul de la contribution de volume d'une facette a la valeur de l'indicatrice dans un element.
C'est une fraction du volume de l'element comprise entre epsilon et 1.-epsilon
Precondition: dimension = 3
Parameters
(domaine_vf) domaine du calcul
(num_element) indice de l'element intersecte
(poly_reelles) coordonnees (reelles) des sommets definissant une surface contenue dans l'element (en pratique : surface d'intersection entre une facette d'interface et l'element)
(norme) normale a la facette
(centre_de_gravite) centre de gravite de la surface
(epsilon) erreur relative
Returns
(double) contribution du volume engendre par la surface dans l'element
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Domaine_VF::elem_faces(), Erreur_relative_maxi_, and Domaine_VF::xv().
Referenced by calcul_intersection_facelem_3D().
coupe_face_rectangulaire()
CutFace_Properties Parcours_interface::coupe_face_rectangulaire (const Domaine_VF & domaine_vf, int num_element, int num_face, const DoubleTab & poly_reelles, const FTd_vecteur3 & norme, const ArrOfInt & polygone_plan_coupe, double epsilon) const protected
Calcul de la contribution d'une facette a l'indicatrice surfacique et au barycentre sur une face d'un element.
Precondition: dimension = 3
Parameters
(domaine_vf) domaine du calcul
(num_element) indice de l'element intersecte
(num_face) indice de la face, au sein de l'element
(poly_reelles) coordonnees (reelles) des sommets definissant une surface contenue dans l'element (en pratique : surface d'intersection entre une facette d'interface et l'element)
(norme) normale a la facette
(epsilon) erreur relative
Returns
(CutFace_Properties) contribution de la surface engendre par le segment sur la face, et au barycentre de cette surface
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Domaine_VF::elem_faces(), Erreur_relative_maxi_, and Domaine_VF::xv().
Referenced by calcul_intersection_facelem_3D().
matrice_triangle()
void Parcours_interface::matrice_triangle (int num_element, FTd_vecteur2 & origine, FTd_matrice22 & matrice, double & surface) const inline protected
Referenced by volume_triangle().
transformation_2d()
void Parcours_interface::transformation_2d (const FTd_vecteur2 & origine, const FTd_matrice22 & matrice, double x, double y, double & u, double & v) const inline protected
Applique la transformation calculee par matrice_triangle a une coordonnee (x,y).
Le resultat est stocke dans (u,v). La troisieme coordonnee barycentrique est implicitement egale a 1-u-v.
Referenced by volume_triangle().
calcul_inverse_matrice33()
void Parcours_interface::calcul_inverse_matrice33 (const FTd_matrice33 & matrice, FTd_matrice33 & matrice_inv) static protected
Cette methode (statique) permet d'inverser une matrice 3x3.
Precondition: des denominateurs non nuls
Parameters
(matrice) matrice 3x3 a inverser
(matrice_inv) inverse de la matrice 3x3
Returns
(rien)
References Process::exit().
Referenced by volume_tetraedre().
calcul_produit_matrice33_vecteur()
void Parcours_interface::calcul_produit_matrice33_vecteur (const FTd_matrice33 & matrice, const FTd_vecteur3 & vect, FTd_vecteur3 & res) static protected
Cette methode (statique) permet de calculer le produit d'une matrice 3x3 avec un vecteur 3.
Parameters
(matrice) matrice 3x3 a inverser
(vect) vecteur 3 a multiplier
(vect) vecteur 3 resultat
Returns
(rien)
Referenced by volume_tetraedre().
eloigner_sommets_des_faces()
int Parcours_interface::eloigner_sommets_des_faces (Maillage_FT_Disc & maillage) const protected
Pour chaque sommet, s'il est trop pres d'une face eulerienne, deplace le sommet pour l'en eloigner.
Mise a jour de l'espace virtuel des sommets
References Process::check_int_overflow(), Maillage_FT_Disc::desc_sommets(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), distance_sommet_faces(), Desc_Structure_FT::echange_espace_virtuel(), Erreur_max_coordonnees_, Process::je_suis_maitre(), Process::Journal(), Process::mp_sum(), Maillage_FT_Disc::nb_sommets(), refdomaine_vf_, Maillage_FT_Disc::sommet_elem_, Maillage_FT_Disc::sommet_virtuel(), Maillage_FT_Disc::sommets_, uzawa2(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by parcourir().
uzawa2()
double Parcours_interface::uzawa2 (const Domaine_VF & domaine_vf, const int elem, double & x, double & y, double & z) const protected
Algorithme base sur une version initiale de Thomas (recode par BM) Ramene le point (x,y,z) a l'interieur de l'element elem du domaine_vf a une.
distance >= Erreur_max_coordonnees_ par un algorithme d'Uzawa. Valeur de retour: distance finale du sommet aux faces de l'element (positive si le sommet est a l'interieur)
References calcul_eq_plan(), Domaine_VF::elem_faces(), Erreur_max_coordonnees_, and Process::Journal().
Referenced by eloigner_sommets_des_faces().
Friends And Related Function Documentation
Maillage_FT_Disc::parcourir_maillage
void Maillage_FT_Disc::parcourir_maillage () friend
Member Data Documentation
info_obj
const Type_info Parcours_interface::info_obj static
refdomaine_vf_
TRUST_Ref< Domaine_VF *> Parcours_interface::refdomaine_vf_ protected
Referenced by associer_domaine_dis(), calcul_eq_plan(), calculer_normale_face_bord(), calculer_sortie_face_bord(), eloigner_sommets_des_faces(), parcourir(), readOn(), and update_erreur_coords_max().
refconnect_front_
TRUST_Ref< Connectivite_frontieres *> Parcours_interface::refconnect_front_ protected
Referenced by associer_connectivite_frontieres(), and calculer_sortie_face_bord().
nb_faces_elem_
int Parcours_interface::nb_faces_elem_ = -123 protected
Referenced by associer_domaine_dis(), calcul_intersection_facelem_2D(), calcul_intersection_facelem_3D(), calculer_face_sortie_element(), distance_sommet_faces(), and parcours_facette().
nb_elements_reels_
int Parcours_interface::nb_elements_reels_ = -123 protected
Referenced by associer_domaine_dis(), and parcours_facette().
nb_sommets_par_face_
int Parcours_interface::nb_sommets_par_face_ = -123 protected
Referenced by associer_domaine_dis(), and calculer_sortie_face_bord().
enum { ... } Parcours_interface::type_element_
Referenced by associer_domaine_dis(), calcul_intersection_facelem_2D(), and calcul_intersection_facelem_3D().
equations_plans_faces_
DoubleTabFT Parcours_interface::equations_plans_faces_ protected
Referenced by associer_domaine_dis(), calcul_eq_plan(), calculer_normale_face_bord(), calculer_sortie_face_bord(), and projeter_vecteur_sur_face().
compteur_erreur_grossiere
int Parcours_interface::compteur_erreur_grossiere = -123 mutable protected
Referenced by calcul_intersection_facelem_2D(), calcul_intersection_facelem_3D(), and parcourir().
domaine_elem_ptr
const IntTab* Parcours_interface::domaine_elem_ptr = nullptr mutable protected
Referenced by associer_domaine_dis(), parcourir(), and Parcours_interface().
domaine_sommets_ptr
const DoubleTab* Parcours_interface::domaine_sommets_ptr = nullptr mutable protected
Referenced by associer_domaine_dis(), parcourir(), Parcours_interface(), and volume_tetraedre().
drapeaux_elements_parcourus_
ArrOfBit Parcours_interface::drapeaux_elements_parcourus_ mutable protected
Referenced by associer_domaine_dis(), and parcours_facette().
Erreur_relative_maxi_
double Parcours_interface::Erreur_relative_maxi_ protected
Referenced by coupe_face_rectangulaire(), Parcours_interface(), readOn(), update_erreur_coords_max(), volume_barycentre_hexaedre(), volume_barycentre_rectangle(), volume_rectangle(), volume_tetraedre_reference(), and volume_triangle().
Valeur_max_coordonnees_
double Parcours_interface::Valeur_max_coordonnees_ = 0. protected
Referenced by Parcours_interface(), and update_erreur_coords_max().
Erreur_max_coordonnees_
double Parcours_interface::Erreur_max_coordonnees_ = 0. protected
Referenced by calcul_intersection_facelem_2D(), calcul_intersection_facelem_3D(), calculer_face_sortie_element(), eloigner_sommets_des_faces(), get_erreur_geometrique(), Parcours_interface(), update_erreur_coords_max(), and uzawa2().
correction_parcours_thomas_
int Parcours_interface::correction_parcours_thomas_ = 0 protected
Referenced by calcul_intersection_facelem_2D(), calcul_intersection_facelem_3D(), get_correction_parcours_thomas(), parcourir(), Parcours_interface(), readOn(), and set_correction_parcours_thomas().
parcours_sans_tolerance_
int Parcours_interface::parcours_sans_tolerance_ = 0 protected
Referenced by calcul_intersection_facelem_2D(), calcul_intersection_facelem_3D(), get_parcours_sans_tolerance(), Parcours_interface(), readOn(), and set_parcours_sans_tolerance().