TrioCFD: SourceFiltree_FT_disc_VEF_P1NC Class Reference
SourceFiltree_FT_disc_VEF_P1NC Class Reference
#include <SourceFiltree_FT_disc_VEF_P1NC.h>
Public Member Functions
void completer () override
const Type_info * get_info () const override
void mettre_a_jour (double temps) override
Public Member Functions inherited from Source_base
virtual int a_pour_Champ_Fonc (const Motcle &mot, TRUST_Ref< Champ_base * > &ch_ref) const
virtual void associer_champ_rho (const Champ_base &champ_rho)
virtual void completer ()
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
virtual void resetTime (double t)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Entree & lire (Entree &is)
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from SourceFiltree_FT_disc_base
Entree & lire_donnees (Entree &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
sur une phase donnee
See also
Probleme_FT_Disc_gen
Constructor & Destructor Documentation
SourceFiltree_FT_disc_VEF_P1NC()
SourceFiltree_FT_disc_VEF_P1NC::SourceFiltree_FT_disc_VEF_P1NC ()
~SourceFiltree_FT_disc_VEF_P1NC()
SourceFiltree_FT_disc_VEF_P1NC::~SourceFiltree_FT_disc_VEF_P1NC ()
Member Function Documentation
cree_instance()
Objet_U * SourceFiltree_FT_disc_VEF_P1NC::cree_instance () static
taille_memoire()
unsigned SourceFiltree_FT_disc_VEF_P1NC::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int SourceFiltree_FT_disc_VEF_P1NC::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * SourceFiltree_FT_disc_VEF_P1NC::info () static
get_info()
const Type_info * SourceFiltree_FT_disc_VEF_P1NC::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Source_base.
self_cast() [1/2]
SourceFiltree_FT_disc_VEF_P1NC & SourceFiltree_FT_disc_VEF_P1NC::self_cast (Objet_U & r) static
self_cast() [2/2]
const SourceFiltree_FT_disc_VEF_P1NC & SourceFiltree_FT_disc_VEF_P1NC::self_cast (const Objet_U & r) static
printOn()
Sortie & SourceFiltree_FT_disc_VEF_P1NC::printOn (Sortie & os) const override protected virtual
DOES NOTHING - to override in derived classes.
Imprime la source sur un flot de sortie.
Parameters
(Sortie& os) le flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Source_base.
References SourceFiltree_FT_disc_base::ecrire_donnees(), and Objet_U::que_suis_je().
readOn()
Entree & SourceFiltree_FT_disc_VEF_P1NC::readOn (Entree & is) override protected virtual
DOES NOTHING - to override in derived classes.
Lecture d'un terme source sur un flot d'entree.
Parameters
(Entree& is) le flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Source_base.
References lire().
ajouter()
DoubleTab & SourceFiltree_FT_disc_VEF_P1NC::ajouter (DoubleTab & resu) const override virtual
Reimplemented from Source_base.
References Objet_U::dimension, SourceFiltree_FT_disc_base::dimension_, MorEqn::equation(), Parser::eval(), Domaine_VF::face_voisins(), SourceFiltree_FT_disc_base::fI_xyz_t, Indic_, le_dom_Cl_VEF, le_dom_VEF, Domaine_Cl_dis_base::les_conditions_limites(), Equation_base::milieu(), Domaine_VF::nb_faces(), Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), Milieu_base::porosite_face(), Domaine_VF::premiere_face_int(), Parser::setVar(), SourceFiltree_FT_disc_base::temps_, TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), Domaine_VF::volumes_entrelaces(), and Domaine_VF::xv().
Referenced by calculer().
calculer()
DoubleTab & SourceFiltree_FT_disc_VEF_P1NC::calculer (DoubleTab & resu) const override virtual
Reimplemented from Source_base.
References ajouter().
mettre_a_jour()
void SourceFiltree_FT_disc_VEF_P1NC::mettre_a_jour (double temps) override virtual
DOES NOTHING - to override in derived classes.
Mise a jour en temps du terme source.
Parameters
(double) le pas de temps de mise a jour
Reimplemented from Source_base.
References SourceFiltree_FT_disc_base::temps_.
completer()
void SourceFiltree_FT_disc_VEF_P1NC::completer () override virtual
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees: Source_base::associer_domaines(const Domaine_dis_base& ,const Domaine_Cl_dis_base&) Source_base::associer_pb(const Probleme_base&)
Reimplemented from Source_base.
References Source_base::completer().
lire()
Entree & SourceFiltree_FT_disc_VEF_P1NC::lire (Entree & is) protected
Lit les parametres du terme source a partir d'un flot d'entree.
Parameters
(Entree& is) un flot d'entree
References SourceFiltree_FT_disc_base::lire_donnees().
Referenced by readOn().
associer_domaines()
void SourceFiltree_FT_disc_VEF_P1NC::associer_domaines (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis) override protected virtual
Implements Source_base.
References le_dom_Cl_VEF, and le_dom_VEF.
associer_pb()
void SourceFiltree_FT_disc_VEF_P1NC::associer_pb (const Probleme_base & pb) override protected virtual
Implements Source_base.
References Probleme_FT_Disc_gen::equation_interfaces(), Transport_Interfaces_FT_Disc::inconnue(), Indic_, SourceFiltree_FT_disc_base::nom_eq_transport_, and Objet_U::que_suis_je().
Member Data Documentation
info_obj
const Type_info SourceFiltree_FT_disc_VEF_P1NC::info_obj static
le_dom_VEF
TRUST_Ref< Domaine_VEF *> SourceFiltree_FT_disc_VEF_P1NC::le_dom_VEF protected
Referenced by ajouter(), and associer_domaines().
le_dom_Cl_VEF
TRUST_Ref< Domaine_Cl_VEF *> SourceFiltree_FT_disc_VEF_P1NC::le_dom_Cl_VEF protected
Referenced by ajouter(), and associer_domaines().
Indic_
TRUST_Ref< Champ_Inc_base *> SourceFiltree_FT_disc_VEF_P1NC::Indic_ protected
Referenced by ajouter(), and associer_pb().