TrioCFD: Traitement_particulier_NS_chmoy_faceperio_VEF Class Reference
Traitement_particulier_NS_chmoy_faceperio_VEF Class Reference
#include <Traitement_particulier_NS_chmoy_faceperio_VEF.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
pour le calcul d'un canal plan :
    * conservation du debit
    * calculs de moyennes
See also
Navier_Stokes_Turbulent, Traitement_particulier_base, Traitement_particulier_VEF
Constructor & Destructor Documentation
Traitement_particulier_NS_chmoy_faceperio_VEF()
Traitement_particulier_NS_chmoy_faceperio_VEF::Traitement_particulier_NS_chmoy_faceperio_VEF ()
~Traitement_particulier_NS_chmoy_faceperio_VEF()
Traitement_particulier_NS_chmoy_faceperio_VEF::~Traitement_particulier_NS_chmoy_faceperio_VEF ()
Member Function Documentation
cree_instance()
Objet_U * Traitement_particulier_NS_chmoy_faceperio_VEF::cree_instance () static
taille_memoire()
unsigned Traitement_particulier_NS_chmoy_faceperio_VEF::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Traitement_particulier_NS_chmoy_faceperio_VEF::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Traitement_particulier_NS_chmoy_faceperio_VEF::info () static
get_info()
const Type_info * Traitement_particulier_NS_chmoy_faceperio_VEF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Traitement_particulier_NS_chmoy_faceperio.
self_cast() [1/2]
Traitement_particulier_NS_chmoy_faceperio_VEF & Traitement_particulier_NS_chmoy_faceperio_VEF::self_cast (Objet_U & r) static
self_cast() [2/2]
const Traitement_particulier_NS_chmoy_faceperio_VEF & Traitement_particulier_NS_chmoy_faceperio_VEF::self_cast (const Objet_U & r) static
printOn()
Sortie & Traitement_particulier_NS_chmoy_faceperio_VEF::printOn (Sortie & is) const override protected virtual
Parameters
(Sortie& is) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Traitement_particulier_NS_chmoy_faceperio.
readOn()
Entree & Traitement_particulier_NS_chmoy_faceperio_VEF::readOn (Entree & is) override protected virtual
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Traitement_particulier_NS_chmoy_faceperio.
init_calcul_stats()
void Traitement_particulier_NS_chmoy_faceperio_VEF::init_calcul_stats () override protected virtual
Implements Traitement_particulier_NS_chmoy_faceperio.
References Traitement_particulier_NS_chmoy_faceperio::chmoy_faceperio, EcrFicPartage::close(), Objet_U::dimension, Objet_U::format_precision_geom, Process::je_suis_maitre(), Domaine_Cl_dis_base::les_conditions_limites(), Traitement_particulier_NS_base::mon_equation, Process::mp_sum(), Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), EcrFicPartage::precision(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Sortie_Fichier_base::setf(), EcrFicPartage::syncfile(), TRUST_Deriv< _CLASSE_ >::valeur(), and Domaine_VF::xv().
calcul_chmoy_faceperio()
void Traitement_particulier_NS_chmoy_faceperio_VEF::calcul_chmoy_faceperio (double un_temps_deb, double temps, double dt) override protected virtual
Implements Traitement_particulier_NS_chmoy_faceperio.
References Traitement_particulier_NS_chmoy_faceperio::chmoy_faceperio, EcrFicPartage::close(), Objet_U::dimension, Objet_U::format_precision_geom, Process::je_suis_maitre(), Domaine_Cl_dis_base::les_conditions_limites(), Traitement_particulier_NS_base::mon_equation, Process::mp_sum(), Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), EcrFicPartage::precision(), Sortie_Fichier_base::setf(), EcrFicPartage::syncfile(), and TRUST_Deriv< _CLASSE_ >::valeur().
Member Data Documentation
info_obj
const Type_info Traitement_particulier_NS_chmoy_faceperio_VEF::info_obj static