TrioCFD: Operateur_Div_base Class Reference
Operateur_Div_base Class Reference abstract
#include <Operateur_Div_base.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Operateur_base
void associer_eqn (const Equation_base &)
virtual double calculer_dt_stab () const
virtual void completer ()
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual void mettre_a_jour (double temps)
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
le calcul de la divergence d'un champ dans une equation.
See also
Operateur_base
Constructor & Destructor Documentation
Operateur_Div_base()
Operateur_Div_base::Operateur_Div_base ()
~Operateur_Div_base()
Operateur_Div_base::~Operateur_Div_base () override
Member Function Documentation
info()
const Type_info * Operateur_Div_base::info () static
get_info()
const Type_info * Operateur_Div_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Operateur_base.
Reimplemented in Op_Div_PolyMAC, Op_Div_PolyMAC_P0, Op_Div_PolyMAC_P0P1NC, Op_Div_VDF_base, Op_Div_VDF_Elem, and Op_Div_VEFP1B_Elem.
self_cast() [1/2]
Operateur_Div_base & Operateur_Div_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Operateur_Div_base & Operateur_Div_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Operateur_Div_base::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN A surcharger dans les classes derivees.
Parameters
(Sortie& os) un flot de sortie
Returns
(Sortie&) le flot de sortie
Reimplemented from Operateur_base.
Reimplemented in Op_Div_PolyMAC, Op_Div_PolyMAC_P0, Op_Div_PolyMAC_P0P1NC, Op_Div_VDF_base, Op_Div_VDF_Elem, and Op_Div_VEFP1B_Elem.
readOn()
Entree & Operateur_Div_base::readOn (Entree & is) override protected virtual
NE FAIT RIEN A surcharger dans les classes derivees.
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree
Reimplemented from Operateur_base.
Reimplemented in Op_Div_PolyMAC, Op_Div_PolyMAC_P0, Op_Div_PolyMAC_P0P1NC, Op_Div_VDF_base, Op_Div_VDF_Elem, and Op_Div_VEFP1B_Elem.
multvect()
DoubleVect & Operateur_Div_base::multvect (const DoubleTab & x, DoubleTab & b) const
References Operateur_base::calculer().
volumique()
virtual void Operateur_Div_base::volumique (DoubleTab &) const pure virtual
Implemented in Op_Div_EF, Op_Div_PolyMAC, Op_Div_VDF_Elem, and Op_Div_VEFP1B_Elem.
Referenced by Operateur_Div::volumique().
ajouter_blocs_ext()
virtual void Operateur_Div_base::ajouter_blocs_ext (const DoubleTab & vit, matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = {}) const inline virtual
Reimplemented in Op_Div_PolyMAC_P0P1NC.
Referenced by ajouter().
ajouter_blocs()
void Operateur_Div_base::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = {}) const inline override virtual
Reimplemented from Operateur_base.
ajouter()
DoubleTab & Operateur_Div_base::ajouter (const DoubleTab & vit, DoubleTab & div) const inline override virtual
Reimplemented from Operateur_base.
Reimplemented in Op_Div_PolyMAC, Op_Div_PolyMAC_P0, Op_Div_VEFP1B_Elem, and Op_Div_VDF_base.
References ajouter_blocs_ext().
Referenced by Operateur_Div::ajouter(), and Op_Div_PolyMAC::ajouter().
Member Data Documentation
info_obj
const Type_info Operateur_Div_base::info_obj static
Flux_div
SFichier Operateur_Div_base::Flux_div mutable protected
Referenced by Op_Div_EF::impr(), Op_Div_PolyMAC::impr(), and Op_Div_VEFP1B_Elem::impr().