TrioCFD: Op_Diff_Turbulent_PolyMAC_P0_Face Class Reference
Op_Diff_Turbulent_PolyMAC_P0_Face Class Reference
#include <Op_Diff_Turbulent_PolyMAC_P0_Face.h>
Public Member Functions
void completer () override
const Type_info * get_info () const override
void mettre_a_jour (double temps) override
Public Member Functions inherited from Op_Diff_PolyMAC_P0_Face
double calculer_dt_stab () const override
void completer () override
const Type_info * get_info () const override
void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const override
void completer () override
const Type_info * get_info () const override
void mettre_a_jour (double t) override
Public Member Functions inherited from Op_Diff_PolyMAC_Gen_base
const Type_info * get_info () const override
int impr (Sortie &os) const override
Public Member Functions inherited from Operateur_Diff_base
virtual void associer_diffusivite_pour_pas_de_temps (const Champ_base &)
const Type_info * get_info () const override
Public Member Functions inherited from Operateur_base
void associer_eqn (const Equation_base &)
virtual double calculer_dt_stab () const
virtual void completer ()
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual void mettre_a_jour (double temps)
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Operateur_Diff_base
virtual const Champ_base & diffusivite_pour_pas_de_temps () const
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
Operateur de diffusion de vitesse prenant en compte l'effet de la turbulence par le biais d'une correlation de type Viscosite_turbulente_base.
Constructor & Destructor Documentation
Op_Diff_Turbulent_PolyMAC_P0_Face()
Op_Diff_Turbulent_PolyMAC_P0_Face::Op_Diff_Turbulent_PolyMAC_P0_Face ()
~Op_Diff_Turbulent_PolyMAC_P0_Face()
Op_Diff_Turbulent_PolyMAC_P0_Face::~Op_Diff_Turbulent_PolyMAC_P0_Face ()
Member Function Documentation
cree_instance()
Objet_U * Op_Diff_Turbulent_PolyMAC_P0_Face::cree_instance () static
taille_memoire()
unsigned Op_Diff_Turbulent_PolyMAC_P0_Face::taille_memoire () const override virtual
Reimplemented from Op_Diff_PolyMAC_P0_Face.
duplique()
int Op_Diff_Turbulent_PolyMAC_P0_Face::duplique () const override virtual
Reimplemented from Op_Diff_PolyMAC_P0_Face.
info()
const Type_info * Op_Diff_Turbulent_PolyMAC_P0_Face::info () static
get_info()
const Type_info * Op_Diff_Turbulent_PolyMAC_P0_Face::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Op_Diff_PolyMAC_P0_Face.
self_cast() [1/2]
Op_Diff_Turbulent_PolyMAC_P0_Face & Op_Diff_Turbulent_PolyMAC_P0_Face::self_cast (Objet_U & r) static
self_cast() [2/2]
const Op_Diff_Turbulent_PolyMAC_P0_Face & Op_Diff_Turbulent_PolyMAC_P0_Face::self_cast (const Objet_U & r) static
printOn()
Sortie & Op_Diff_Turbulent_PolyMAC_P0_Face::printOn (Sortie & os) const override protected virtual
DOES NOTHING - to override in derived classes.
Imprime l'operateur sur un flot de sortie.
Parameters
(Sortie& os) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Op_Diff_PolyMAC_P0_Face.
References Op_Diff_PolyMAC_P0_base::printOn().
readOn()
Entree & Op_Diff_Turbulent_PolyMAC_P0_Face::readOn (Entree & is) override protected virtual
DOES NOTHING - to override in derived classes.
Lit un operateur sur un flot d'entree.
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Op_Diff_PolyMAC_P0_Face.
References Op_Dift_Multiphase_proto::ajout_champs_proto_face(), Op_Dift_Multiphase_proto::associer_proto(), Operateur_base::champs_compris_, Op_Dift_Multiphase_proto::corr_, MorEqn::equation(), and Correlation_base::typer_lire_correlation().
creer_champ()
void Op_Diff_Turbulent_PolyMAC_P0_Face::creer_champ (const Motcle & motlu) override virtual
Reimplemented from Operateur_base.
References Operateur_base::creer_champ(), and Op_Dift_Multiphase_proto::creer_champ_proto_face().
get_noms_champs_postraitables()
void Op_Diff_Turbulent_PolyMAC_P0_Face::get_noms_champs_postraitables (Noms & nom, Option opt = NONE) const override virtual
Reimplemented from Operateur_base.
References Operateur_base::get_noms_champs_postraitables(), Op_Dift_Multiphase_proto::get_noms_champs_postraitables_proto(), and Objet_U::que_suis_je().
preparer_calcul()
void Op_Diff_Turbulent_PolyMAC_P0_Face::preparer_calcul () override virtual
Reimplemented from Operateur_base.
References Op_Dift_Multiphase_proto::call_compute_nu_turb(), and Operateur_base::preparer_calcul().
mettre_a_jour()
void Op_Diff_Turbulent_PolyMAC_P0_Face::mettre_a_jour (double temps) override virtual
DOES NOTHING - to override in derived classes.
Mise a jour de l'operateur
Parameters
(double) un pas de temps
Reimplemented from Op_Diff_PolyMAC_P0_base.
References Op_Dift_Multiphase_proto::call_compute_nu_turb(), Op_Diff_PolyMAC_P0_base::mettre_a_jour(), Op_Dift_Multiphase_proto::mettre_a_jour_proto_face(), and Op_Dift_Multiphase_proto::nu_ou_lambda_turb_.
completer()
void Op_Diff_Turbulent_PolyMAC_P0_Face::completer () override virtual
Associe l'operateur au domaine_dis, le domaine_Cl_dis, et a l'inconnue de son equation.
Exceptions
pas d'equation associee
Reimplemented from Op_Diff_PolyMAC_P0_Face.
References Op_Diff_PolyMAC_P0_Face::completer(), Op_Dift_Multiphase_proto::completer_proto_face(), and Op_Diff_PolyMAC_Gen_base::nu_constant_.
modifier_mu()
void Op_Diff_Turbulent_PolyMAC_P0_Face::modifier_mu (DoubleTab & mu) const override virtual
Reimplemented from Op_Diff_PolyMAC_Gen_base.
References Process::abort(), Op_Dift_Multiphase_proto::corr_, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), MorEqn::equation(), Objet_U_ptr::est_nul(), Equation_base::inconnue(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Milieu_base::masse_volumique(), Equation_base::milieu(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Op_Dift_Multiphase_proto::nu_ou_lambda_turb_, Champ_Proto::passe(), and Champ_Inc_base::valeurs().
is_turb()
bool Op_Diff_Turbulent_PolyMAC_P0_Face::is_turb () const inline override virtual
Reimplemented from Operateur_Diff_base.
correlation_viscosite_turbulente()
const Correlation_base * Op_Diff_Turbulent_PolyMAC_P0_Face::correlation_viscosite_turbulente () const inline override virtual
Reimplemented from Operateur_Diff_base.
References Op_Dift_Multiphase_proto::corr_, and TRUST_Deriv< _CLASSE_ >::valeur().
Member Data Documentation
info_obj
const Type_info Op_Diff_Turbulent_PolyMAC_P0_Face::info_obj static