TrioCFD: Diffusion_croisee_echelle_temp_taux_diss_turb_VDF Class Reference
Diffusion_croisee_echelle_temp_taux_diss_turb_VDF Class Reference
#include <Diffusion_croisee_echelle_temp_taux_diss_turb_VDF.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Sources_Multiphase_base
const Type_info * get_info () const override
void mettre_a_jour (double temps) override
Public Member Functions inherited from Source_base
virtual int a_pour_Champ_Fonc (const Motcle &mot, TRUST_Ref< Champ_base * > &ch_ref) const
virtual void associer_champ_rho (const Champ_base &champ_rho)
virtual void completer ()
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
virtual void resetTime (double t)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
Terme de diffusion croisee dans l'equation de transport de tau (tau = 1 / omega) ou de omega dans les modeles de turbulence k-tau et k-omega Cd = sigma_d * alpha * rho *tau * min(grad k, grad tau, 0)
la phase dont la turbulence est decrite avec le modele k-tau doit etre ecrite en premier dans le bloc phases { } du jeu de donnees Actuellement k et tau sont necessairement scalaires. Si cela est amene a evolue pour permettre de la turbulence dans plusieurs phases, il faudra alors revoir cette classe en iterant sur les id_composites des phases turbulentes. en l'etat, si plusieurs phases sont turbulentes et sont decrites par le modele k-tau, alors elles doivent se suivre dans le bloc phases { } du jeu de donnees
Constructor & Destructor Documentation
Diffusion_croisee_echelle_temp_taux_diss_turb_VDF()
Diffusion_croisee_echelle_temp_taux_diss_turb_VDF::Diffusion_croisee_echelle_temp_taux_diss_turb_VDF ()
~Diffusion_croisee_echelle_temp_taux_diss_turb_VDF()
Diffusion_croisee_echelle_temp_taux_diss_turb_VDF::~Diffusion_croisee_echelle_temp_taux_diss_turb_VDF ()
Member Function Documentation
cree_instance()
Objet_U * Diffusion_croisee_echelle_temp_taux_diss_turb_VDF::cree_instance () static
taille_memoire()
unsigned Diffusion_croisee_echelle_temp_taux_diss_turb_VDF::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Diffusion_croisee_echelle_temp_taux_diss_turb_VDF::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Diffusion_croisee_echelle_temp_taux_diss_turb_VDF::info () static
get_info()
const Type_info * Diffusion_croisee_echelle_temp_taux_diss_turb_VDF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Source_Diffusion_croisee_echelle_temp_taux_diss_turb.
self_cast() [1/2]
Diffusion_croisee_echelle_temp_taux_diss_turb_VDF & Diffusion_croisee_echelle_temp_taux_diss_turb_VDF::self_cast (Objet_U & r) static
self_cast() [2/2]
const Diffusion_croisee_echelle_temp_taux_diss_turb_VDF & Diffusion_croisee_echelle_temp_taux_diss_turb_VDF::self_cast (const Objet_U & r) static
printOn()
Sortie & Diffusion_croisee_echelle_temp_taux_diss_turb_VDF::printOn (Sortie & os) const override protected virtual
DOES NOTHING - to override in derived classes.
Imprime la source sur un flot de sortie.
Parameters
(Sortie& os) le flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Source_Diffusion_croisee_echelle_temp_taux_diss_turb.
References Source_Diffusion_croisee_echelle_temp_taux_diss_turb::printOn().
readOn()
Entree & Diffusion_croisee_echelle_temp_taux_diss_turb_VDF::readOn (Entree & is) override protected virtual
DOES NOTHING - to override in derived classes.
Lecture d'un terme source sur un flot d'entree.
Parameters
(Entree& is) le flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Source_Diffusion_croisee_echelle_temp_taux_diss_turb.
References Source_Diffusion_croisee_echelle_temp_taux_diss_turb::readOn().
ajouter_blocs()
void Diffusion_croisee_echelle_temp_taux_diss_turb_VDF::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = {}) const override virtual
Implements Source_Diffusion_croisee_echelle_temp_taux_diss_turb.
References Operateur_Grad::calculer(), Objet_U::dimension, TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), MorEqn::equation(), Process::exit(), face_to_elem(), Source_base::get_champ(), Nom::getString(), Field_base::le_nom(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Equation_base::milieu(), Convection_diffusion_turbulence_multiphase::operateur_gradient_inconnue(), Champ_Inc_base::passe(), Milieu_base::porosite_elem(), Objet_U::que_suis_je(), Source_Diffusion_croisee_echelle_temp_taux_diss_turb::sigma_d, and Champ_Inc_base::valeurs().
face_to_elem()
void Diffusion_croisee_echelle_temp_taux_diss_turb_VDF::face_to_elem (const Domaine_VF & domaine, const DoubleTab & tab_faces, DoubleTab & tab_elems) const protected
References Objet_U::dimension, TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), and TRUSTVect< _TYPE_, _SIZE_ >::line_size().
Referenced by ajouter_blocs().
Member Data Documentation
info_obj
const Type_info Diffusion_croisee_echelle_temp_taux_diss_turb_VDF::info_obj static