TrioCFD: Modele_turbulence_scal_LES_dyn_VDF Class Reference
Modele_turbulence_scal_LES_dyn_VDF Class Reference
#include <Modele_turbulence_scal_LES_dyn_VDF.h>
Public Member Functions
void associer (const Domaine_dis_base &, const Domaine_Cl_dis_base &) override
const Type_info * get_info () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
Public Member Functions inherited from Modele_turbulence_scal_base
virtual void associer (const Domaine_dis_base &, const Domaine_Cl_dis_base &)
void associer_eqn (const Equation_base &)
const Type_info * get_info () const override
virtual void imprimer (Sortie &) const
int limpr_nusselt (double, double, double, double) const
int lire_motcle_non_standard (const Motcle &, Entree &) override
Turbulence_paroi_scal_base & loi_paroi ()
const Turbulence_paroi_scal_base & loi_paroi () const
int loi_paroi_non_nulle () const
virtual int preparer_calcul ()
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Modele_turbulence_scal_LES_dyn_VDF()
Modele_turbulence_scal_LES_dyn_VDF::Modele_turbulence_scal_LES_dyn_VDF ()
~Modele_turbulence_scal_LES_dyn_VDF()
Modele_turbulence_scal_LES_dyn_VDF::~Modele_turbulence_scal_LES_dyn_VDF ()
Member Function Documentation
cree_instance()
Objet_U * Modele_turbulence_scal_LES_dyn_VDF::cree_instance () static
taille_memoire()
unsigned Modele_turbulence_scal_LES_dyn_VDF::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Modele_turbulence_scal_LES_dyn_VDF::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Modele_turbulence_scal_LES_dyn_VDF::info () static
get_info()
const Type_info * Modele_turbulence_scal_LES_dyn_VDF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Modele_turbulence_scal_base.
self_cast() [1/2]
Modele_turbulence_scal_LES_dyn_VDF & Modele_turbulence_scal_LES_dyn_VDF::self_cast (Objet_U & r) static
self_cast() [2/2]
const Modele_turbulence_scal_LES_dyn_VDF & Modele_turbulence_scal_LES_dyn_VDF::self_cast (const Objet_U & r) static
printOn()
Sortie & Modele_turbulence_scal_LES_dyn_VDF::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Modele_turbulence_scal_base.
References Objet_U::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Modele_turbulence_scal_LES_dyn_VDF::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Modele_turbulence_scal_base.
References dynamique_y2, and Modele_turbulence_scal_base::readOn().
associer()
void Modele_turbulence_scal_LES_dyn_VDF::associer (const Domaine_dis_base & , const Domaine_Cl_dis_base &) override virtual
NE FAIT RIEN.
Parameters
(Domaine_dis_base&) un domaine discretise
(Domaine_Cl_dis_base&) un domaine de conditions aux limites discretisees
Reimplemented from Modele_turbulence_scal_base.
set_param()
void Modele_turbulence_scal_LES_dyn_VDF::set_param (Param & titi) override virtual
Reimplemented from Modele_turbulence_scal_base.
References Param::ajouter(), Param::ajouter_non_std(), dynamique_y2, and Modele_turbulence_scal_base::set_param().
lire_motcle_non_standard()
int Modele_turbulence_scal_LES_dyn_VDF::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
< liste stockant tous les noms de frontiere du domaine
Reimplemented from Modele_turbulence_scal_base.
References calc_elem_elem(), calcul_tableaux_correspondance(), compt_c_, corresp_c_, Process::exit(), Modele_turbulence_scal_base::lire_motcle_non_standard(), methode_stabilise, N_c_, Objet_U::que_suis_je(), and Motcles::search().
mettre_a_jour()
void Modele_turbulence_scal_LES_dyn_VDF::mettre_a_jour (double) override protected virtual
Implements Modele_turbulence_scal_base.
References calculer_diffusivite_turbulente(), Milieu_base::capacite_calorifique(), Modele_turbulence_scal_base::conductivite_turbulente_, Modele_turbulence_scal_base::diffusivite_turbulente_, TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Modele_turbulence_scal_base::equation(), Milieu_base::masse_volumique(), Probleme_base::milieu(), Modele_turbulence_scal_base::mon_equation_, Equation_base::probleme(), TRUSTVect< _TYPE_, _SIZE_ >::size(), Champ_Don_base::valeurs(), and Champ_Proto::valeurs().
calculer_diffusivite_turbulente()
Champ_Fonc_base & Modele_turbulence_scal_LES_dyn_VDF::calculer_diffusivite_turbulente () protected
References Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calculer_cell_cent_vel(), calculer_filter_coeff(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calculer_filter_field(), calculer_grad_teta(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calculer_length_scale(), calculer_Lj(), calculer_Mj(), calculer_model_coefficient(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calculer_S_norme(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calculer_Sij(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calculer_Sij_vel_filt(), cell_cent_vel, Champ_base::changer_temps(), Modele_turbulence_scal_base::diffusivite_turbulente_, Objet_U::dimension, Modele_turbulence_scal_base::equation(), Probleme_base::equation(), Equation_base::get_modele(), Equation_base::inconnue(), Convection_Diffusion_std::inconnue(), model_coeff, Equation_base::probleme(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), Champ_base::temps(), TRUST_Ref< _CLASSE_ >::valeur(), TRUST_Ref_Objet_U::valeur(), Champ_Don_base::valeurs(), Champ_Inc_base::valeurs(), Debog::verifier(), and Modele_turbulence_hyd_base::viscosite_turbulente().
Referenced by mettre_a_jour().
calc_elem_elem()
void Modele_turbulence_scal_LES_dyn_VDF::calc_elem_elem () protected
References Domaine_dis_base::domaine(), elem_elem_, Domaine_VF::elem_faces(), Domaine_VF::face_voisins(), Domaine_32_64< _SIZE_ >::nb_elem_tot(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by lire_motcle_non_standard().
calcul_tableaux_correspondance()
void Modele_turbulence_scal_LES_dyn_VDF::calcul_tableaux_correspondance (int & N_c, IntVect & compt_c, IntVect & corresp_c) protected
References Domaine_dis_base::domaine(), Process::exit(), Modele_turbulence_scal_base::mon_equation_, Domaine_32_64< _SIZE_ >::nb_elem(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), and Domaine_VF::xp().
Referenced by lire_motcle_non_standard().
stabilise_moyenne()
void Modele_turbulence_scal_LES_dyn_VDF::stabilise_moyenne (const DoubleTab & haut, const DoubleTab & bas) protected
References Process::exit(), methode_stabilise, stabilise_moyenne_6_points(), stabilise_moyenne_euler(), stabilise_moyenne_lagrange(), and stabilise_moyenne_plans_paralleles().
Referenced by calculer_model_coefficient().
stabilise_moyenne_euler()
void Modele_turbulence_scal_LES_dyn_VDF::stabilise_moyenne_euler (const DoubleTab & haut, const DoubleTab & bas) protected
References Domaine_dis_base::domaine(), Modele_turbulence_scal_base::mon_equation_, Domaine_32_64< _SIZE_ >::nb_elem_tot(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by stabilise_moyenne().
stabilise_moyenne_lagrange()
void Modele_turbulence_scal_LES_dyn_VDF::stabilise_moyenne_lagrange (const DoubleTab & haut, const DoubleTab & bas) protected
References Domaine_dis_base::domaine(), Modele_turbulence_scal_base::mon_equation_, Domaine_32_64< _SIZE_ >::nb_elem_tot(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by stabilise_moyenne().
calcul_voisins()
void Modele_turbulence_scal_LES_dyn_VDF::calcul_voisins (const int element_number, IntVect & num, DoubleVect & dist) protected
References cell_cent_vel, elem_elem_, Modele_turbulence_scal_base::equation(), Probleme_base::equation(), Schema_Temps_base::pas_de_temps(), Equation_base::probleme(), Equation_base::schema_temps(), TRUST_Ref< _CLASSE_ >::valeur(), and Domaine_VF::xp().
calculer_model_coefficient()
void Modele_turbulence_scal_LES_dyn_VDF::calculer_model_coefficient (const DoubleTab & Lj, const DoubleTab & Mj) protected
References Objet_U::dimension, dynamique_y2, model_coeff, and stabilise_moyenne().
Referenced by calculer_diffusivite_turbulente().
stabilise_moyenne_6_points()
void Modele_turbulence_scal_LES_dyn_VDF::stabilise_moyenne_6_points (const DoubleTab & haut, const DoubleTab & bas) protected
References Objet_U::dimension, Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), Domaine_VF::face_voisins(), model_coeff, Domaine_32_64< _SIZE_ >::nb_elem_tot(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by stabilise_moyenne().
stabilise_moyenne_plans_paralleles()
void Modele_turbulence_scal_LES_dyn_VDF::stabilise_moyenne_plans_paralleles (const DoubleTab & haut, const DoubleTab & bas) protected
References Process::check_int_overflow(), compt_c_, corresp_c_, Domaine_dis_base::domaine(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), model_coeff, Process::mp_sum(), N_c_, Domaine_32_64< _SIZE_ >::nb_elem(), Domaine_32_64< _SIZE_ >::nb_elem_tot(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by stabilise_moyenne().
calculer_filter_coeff()
void Modele_turbulence_scal_LES_dyn_VDF::calculer_filter_coeff (const DoubleTab & coeff, DoubleTab & filt_coeff) protected
References Objet_U::dimension, Domaine_dis_base::domaine(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_VF::elem_faces(), Domaine_VF::face_voisins(), Domaine_32_64< _SIZE_ >::nb_elem(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by calculer_diffusivite_turbulente().
calculer_Lj()
void Modele_turbulence_scal_LES_dyn_VDF::calculer_Lj (const DoubleTab & teta, const DoubleTab & filt_teta, const DoubleTab & vel, const DoubleTab & filt_vel, DoubleTab & Lj) protected
References Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calculer_filter_field(), Objet_U::dimension, Domaine_dis_base::domaine(), Domaine_32_64< _SIZE_ >::nb_elem_tot(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by calculer_diffusivite_turbulente().
calculer_grad_teta()
void Modele_turbulence_scal_LES_dyn_VDF::calculer_grad_teta (const DoubleVect & teta, DoubleTab & grad_teta) protected
References Operateur_base::ajouter(), Milieu_base::conductivite(), Objet_U::dimension, TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Modele_turbulence_scal_base::equation(), Operateur_base::flux_bords(), Probleme_base::milieu(), Modele_turbulence_scal_base::mon_equation_, Equation_base::probleme(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and Champ_Don_base::valeurs().
Referenced by calculer_diffusivite_turbulente().
calculer_Mj()
void Modele_turbulence_scal_LES_dyn_VDF::calculer_Mj (const DoubleTab & S_grid_scale_norme, const DoubleTab & S_test_scale_norme, const DoubleTab & grad_teta, const DoubleTab & filt_grad_teta, const DoubleTab & l, DoubleTab & Mj) protected
References Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calculer_filter_field(), Objet_U::dimension, Domaine_dis_base::domaine(), Domaine_32_64< _SIZE_ >::nb_elem_tot(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by calculer_diffusivite_turbulente().
Member Data Documentation
info_obj
const Type_info Modele_turbulence_scal_LES_dyn_VDF::info_obj static
methode_stabilise
Motcle Modele_turbulence_scal_LES_dyn_VDF::methode_stabilise protected
Referenced by lire_motcle_non_standard(), and stabilise_moyenne().
dynamique_y2
int Modele_turbulence_scal_LES_dyn_VDF::dynamique_y2 protected
Referenced by calculer_model_coefficient(), readOn(), and set_param().
N_c_
int Modele_turbulence_scal_LES_dyn_VDF::N_c_ protected
Referenced by lire_motcle_non_standard(), and stabilise_moyenne_plans_paralleles().
compt_c_
IntVect Modele_turbulence_scal_LES_dyn_VDF::compt_c_ protected
Referenced by lire_motcle_non_standard(), and stabilise_moyenne_plans_paralleles().
corresp_c_
IntVect Modele_turbulence_scal_LES_dyn_VDF::corresp_c_ protected
Referenced by lire_motcle_non_standard(), and stabilise_moyenne_plans_paralleles().
elem_elem_
IntTab Modele_turbulence_scal_LES_dyn_VDF::elem_elem_ protected
Referenced by calc_elem_elem(), and calcul_voisins().
cell_cent_vel
DoubleTab Modele_turbulence_scal_LES_dyn_VDF::cell_cent_vel protected
Referenced by calcul_voisins(), and calculer_diffusivite_turbulente().
model_coeff
DoubleVect Modele_turbulence_scal_LES_dyn_VDF::model_coeff protected
Referenced by calculer_diffusivite_turbulente(), calculer_model_coefficient(), stabilise_moyenne_6_points(), and stabilise_moyenne_plans_paralleles().