TrioCFD: Modele_turbulence_hyd_combinaison Class Reference
Modele_turbulence_hyd_combinaison Class Reference
#include <Modele_turbulence_hyd_combinaison.h>
Public Member Functions
const Type_info * get_info () const override
void imprimer (Sortie &is) const override
int preparer_calcul () override
int reprendre (Entree &is) override
const Type_info * get_info () const override
void imprimer (Sortie &) const override
int reprendre (Entree &is) override
Public Member Functions inherited from Modele_turbulence_hyd_base
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Type_info * get_info () const override
virtual void imprimer (Sortie &) const
void lire_distance_paroi ()
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual int preparer_calcul ()
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
et (ou) des variables d espace et de temps pour l equation de Navier Stokes La syntaxe a respecter est la suivante : Modele_turbulence combinaison { nb_var nb_sources_a_specif fonction ... turbulence_paroi ... } -Mot cle nb_var : nb_sources_a_specif est a preciser par l utilisateur : correspond aux nombre de champs sources qui interviendront dans l expression du modele (0 par defaut) -Mot cle fonction : Une expression doit etre specifiee par l utilisateur f(x,y,z,t,nom_champs_sources) -Mot cle turbulence_paroi : Choix d une loi de paroi (eventuellement negligeable) a preciser par l utilisateur
See also
Modele_turbulence_hyd_0_eq_base
Constructor & Destructor Documentation
~Modele_turbulence_hyd_combinaison()
Modele_turbulence_hyd_combinaison::~Modele_turbulence_hyd_combinaison ()
Modele_turbulence_hyd_combinaison()
Modele_turbulence_hyd_combinaison::Modele_turbulence_hyd_combinaison ()
References TRUST_Vector< _CLASSE_ >::dimensionner(), and les_var.
Member Function Documentation
cree_instance()
Objet_U * Modele_turbulence_hyd_combinaison::cree_instance () static
taille_memoire()
unsigned Modele_turbulence_hyd_combinaison::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Modele_turbulence_hyd_combinaison::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Modele_turbulence_hyd_combinaison::info () static
get_info()
const Type_info * Modele_turbulence_hyd_combinaison::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Modele_turbulence_hyd_0_eq_base.
self_cast() [1/2]
Modele_turbulence_hyd_combinaison & Modele_turbulence_hyd_combinaison::self_cast (Objet_U & r) static
self_cast() [2/2]
const Modele_turbulence_hyd_combinaison & Modele_turbulence_hyd_combinaison::self_cast (const Objet_U & r) static
printOn()
Sortie & Modele_turbulence_hyd_combinaison::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Modele_turbulence_hyd_0_eq_base.
References Modele_turbulence_hyd_0_eq_base::printOn().
readOn()
Entree & Modele_turbulence_hyd_combinaison::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Modele_turbulence_hyd_0_eq_base.
References Modele_turbulence_hyd_0_eq_base::readOn().
set_param()
void Modele_turbulence_hyd_combinaison::set_param (Param & param) override virtual
Reimplemented from Modele_turbulence_hyd_0_eq_base.
References Param::ajouter(), la_fct_, les_var, Param::REQUIRED, and Modele_turbulence_hyd_base::set_param().
completer()
void Modele_turbulence_hyd_combinaison::completer () override virtual
Reimplemented from Modele_turbulence_hyd_0_eq_base.
References TRUST_Vector< _CLASSE_ >::dimensionner(), fxyz_, la_fct_, les_var, nb_var_, and TRUST_Vector< _CLASSE_ >::size().
mettre_a_jour()
void Modele_turbulence_hyd_combinaison::mettre_a_jour (double temps) override virtual
Reimplemented from Modele_turbulence_hyd_0_eq_base.
References Statistiques::begin_count(), Turbulence_paroi_base::calculer_hyd(), calculer_viscosite_turbulente(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Statistiques::end_count(), Modele_turbulence_hyd_0_eq_base::energie_cinetique_turbulente(), Modele_turbulence_hyd_base::equation(), Modele_turbulence_hyd_base::la_viscosite_turbulente_, Modele_turbulence_hyd_base::limiter_viscosite_turbulente(), Modele_turbulence_hyd_base::loipar_, and Champ_Don_base::valeurs().
Referenced by preparer_calcul().
preparer_calcul()
int Modele_turbulence_hyd_combinaison::preparer_calcul () override virtual
Prepare le calcul.
Initialise la loi de paroi. Remplit le champ wall_length en cas de post traitemetn de la distance_paroi
Returns
(int) code de retour de Turbulence_paroi::init_lois_paroi()
Reimplemented from Modele_turbulence_hyd_base.
References mettre_a_jour(), and Modele_turbulence_hyd_base::preparer_calcul().
calculer_viscosite_turbulente()
Champ_Fonc_base & Modele_turbulence_hyd_combinaison::calculer_viscosite_turbulente () override virtual
Implements Modele_turbulence_hyd_0_eq_base.
References Champ_base::changer_temps(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Modele_turbulence_hyd_base::equation(), Process::exit(), fxyz_, Probleme_base::get_champ(), Equation_base::inconnue(), Modele_turbulence_hyd_base::la_viscosite_turbulente_, les_var, TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Domaine_dis_base::nb_elem(), nb_var_, Equation_base::probleme(), Champ_base::temps(), Champ_Don_base::valeurs(), and Domaine_VF::xp().
Referenced by mettre_a_jour().
calculer_energie_cinetique_turb()
void Modele_turbulence_hyd_combinaison::calculer_energie_cinetique_turb () inline override virtual
Implements Modele_turbulence_hyd_0_eq_base.
nombre_sources()
int Modele_turbulence_hyd_combinaison::nombre_sources () inline
References nb_var_.
Referenced by Paroi_std_hyd_VEF_diphasique::calculer_hyd(), and Paroi_std_hyd_EF::calculer_hyd().
reprendre()
int Modele_turbulence_hyd_combinaison::reprendre (Entree &) inline override virtual
Reprise d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree&) flot d'entree a utiliser pour la reprise
Returns
(int) code de retour
Reimplemented from Modele_turbulence_hyd_0_eq_base.
References Modele_turbulence_hyd_base::reprendre().
imprimer()
void Modele_turbulence_hyd_combinaison::imprimer (Sortie & os) const inline override virtual
Effectue l'impression si cela est necessaire.
Returns
renvoie toujours 1
Reimplemented from Modele_turbulence_hyd_0_eq_base.
References Modele_turbulence_hyd_base::imprimer().
Member Data Documentation
info_obj
const Type_info Modele_turbulence_hyd_combinaison::info_obj static
la_fct_
Nom Modele_turbulence_hyd_combinaison::la_fct_ protected
Referenced by completer(), and set_param().
nb_var_
int Modele_turbulence_hyd_combinaison::nb_var_ = 0 protected
Referenced by calculer_viscosite_turbulente(), completer(), and nombre_sources().
les_var
Noms Modele_turbulence_hyd_combinaison::les_var protected
Referenced by calculer_viscosite_turbulente(), completer(), Modele_turbulence_hyd_combinaison(), and set_param().
fxyz_
TRUST_Vector< Parser_U > Modele_turbulence_hyd_combinaison::fxyz_ mutable protected
Referenced by calculer_viscosite_turbulente(), and completer().