TrioCFD: Eval_Darcy_VEF_Face Class Reference
Eval_Darcy_VEF_Face Class Reference
#include <Eval_Darcy_VEF_Face.h>
Constructor & Destructor Documentation
Eval_Darcy_VEF_Face() [1/2]
Eval_Darcy_VEF_Face::Eval_Darcy_VEF_Face () inline
Eval_Darcy_VEF_Face() [2/2]
Eval_Darcy_VEF_Face::Eval_Darcy_VEF_Face (const Eval_Darcy_VEF_Face & eval) inline
Member Function Documentation
mettre_a_jour()
void Eval_Darcy_VEF_Face::mettre_a_jour () inline override virtual
Implements Evaluateur_Source.
References Evaluateur_Source::le_dom, and TRUST_Ref< _CLASSE_ >::valeur().
calculer_terme_source_standard()
template<typename Type_Double > void Eval_Darcy_VEF_Face::calculer_terme_source_standard (const int num_face, Type_Double & source) const inline
References Evaluateur_Source_Face::volumes_entrelaces.
calculer_terme_source_non_standard()
template<typename Type_Double > void Eval_Darcy_VEF_Face::calculer_terme_source_non_standard (const int num_face, Type_Double & source) const inline
References Evaluateur_Source_VEF_Face::volumes_entrelaces_Cl.
associer() [1/2]
void Eval_Darcy_VEF_Face::associer (const Champ_Don_base & diffu) inline
References Evaluateur_Source::le_dom, TRUSTTab< _TYPE_, _SIZE_ >::resize(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Source_Darcy_VEF_Face::associer_pb().
associer() [2/2]
void Eval_Darcy_VEF_Face::associer (const Champ_Inc_base & v) inline
getPorosite()
double & Eval_Darcy_VEF_Face::getPorosite () inline
Referenced by Source_Darcy_VEF_Face::lire_motcle_non_standard().
Member Data Documentation
modK_
TRUST_Deriv< Modele_Permeabilite_base > Eval_Darcy_VEF_Face::modK_
Referenced by Source_Darcy_VEF_Face::lire_motcle_non_standard().