TrioCFD: Diffu_k Class Reference
Diffu_k Class Reference
#include <Diffu_k.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Diffu_totale_hyd_base
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Diffu_totale_hyd_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
de la diffusivite_totale
Constructor & Destructor Documentation
Diffu_k()
Diffu_k::Diffu_k ()
~Diffu_k()
Diffu_k::~Diffu_k ()
Member Function Documentation
cree_instance()
Objet_U * Diffu_k::cree_instance () static
taille_memoire()
unsigned Diffu_k::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Diffu_k::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Diffu_k::info () static
get_info()
const Type_info * Diffu_k::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
Diffu_k & Diffu_k::self_cast (Objet_U & r) static
self_cast() [2/2]
const Diffu_k & Diffu_k::self_cast (const Objet_U & r) static
printOn()
Sortie & Diffu_k::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
readOn()
Entree & Diffu_k::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
calculer_a_local()
double Diffu_k::calculer_a_local (int ind) override virtual
Implements Diffu_totale_hyd_base.
References Objet_U::dimension, Diffu_totale_base::eq_couch_lim, Diffu_totale_hyd_base::eq_couch_lim_T, Eq_couch_lim::get_N(), Eq_couch_lim::get_Unp1(), Eq_couch_lim::get_y(), mod_echelle_LRM_base, Diffu_totale_base::mu_lambda, and TRUST_Ref< _CLASSE_ >::valeur().
associer_modele_echelles()
void Diffu_k::associer_modele_echelles (Mod_echelle_LRM_base & mod) inline
References mod_echelle_LRM_base.
Referenced by ParoiVDF_TBLE_LRM::init_lois_paroi().
calculer_D_local()
double Diffu_k::calculer_D_local (int ind) inline override virtual
Implements Diffu_totale_base.
Member Data Documentation
info_obj
const Type_info Diffu_k::info_obj static
mod_echelle_LRM_base
TRUST_Ref< Mod_echelle_LRM_base *> Diffu_k::mod_echelle_LRM_base protected
Referenced by associer_modele_echelles(), and calculer_a_local().