TrioCFD: Paroi_ODVM_scal_VDF Class Reference
Paroi_ODVM_scal_VDF Class Reference
#include <Paroi_ODVM_scal_VDF.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Turbulence_paroi_scal_base
void associer_modele (const Modele_turbulence_scal_base &)
const Type_info * get_info () const override
void imprimer_nusselt_mean_only (Sortie &, int, const TRUST_List< Nom > &, const Nom &) const
void imprimer_premiere_ligne_nusselt (int, const TRUST_List< Nom > &, const Nom &) const
int reprendre (Entree &is) override
int sauvegarder (Sortie &os) const override
virtual bool use_equivalent_distance () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Turbulence_paroi_scal_base
static void typer_lire_turbulence_paroi_scal (TRUST_Deriv< Turbulence_paroi_scal_base > &, const Modele_turbulence_scal_base &, Entree &)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
.SECTION voir aussi Turbulence_paroi_base
Constructor & Destructor Documentation
~Paroi_ODVM_scal_VDF()
Paroi_ODVM_scal_VDF::~Paroi_ODVM_scal_VDF ()
Member Function Documentation
cree_instance()
Objet_U * Paroi_ODVM_scal_VDF::cree_instance () static
taille_memoire()
unsigned Paroi_ODVM_scal_VDF::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Paroi_ODVM_scal_VDF::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Paroi_ODVM_scal_VDF::info () static
get_info()
const Type_info * Paroi_ODVM_scal_VDF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Paroi_scal_hyd_base_VDF.
self_cast() [1/2]
Paroi_ODVM_scal_VDF & Paroi_ODVM_scal_VDF::self_cast (Objet_U & r) static
self_cast() [2/2]
const Paroi_ODVM_scal_VDF & Paroi_ODVM_scal_VDF::self_cast (const Objet_U & r) static
printOn()
Sortie & Paroi_ODVM_scal_VDF::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Paroi_scal_hyd_base_VDF.
References Objet_U::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Paroi_ODVM_scal_VDF::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Paroi_scal_hyd_base_VDF.
References check, compt, dt_impr, Process::exit(), facteur, gamma, N, Motcles::search(), stats, temps_deb_stats, and temps_dern_post_inst.
calculer_scal()
int Paroi_ODVM_scal_VDF::calculer_scal (Champ_Fonc_base & diffusivite_turb) override virtual
Implements Turbulence_paroi_scal_base.
References Sources::calculer(), Milieu_base::capacite_calorifique(), check, compt, Milieu_base::conductivite(), Milieu_base::diffusivite(), Equation_base::domaine_Cl_dis(), dt_impr, eq_odvm, Turbulence_paroi_scal_base::equivalent_distance_, Process::exit(), Domaine_VF::face_voisins(), Domaine_VF::front_VF(), Equation_base::get_modele(), Echange_contact_VDF::h_autre_pb(), Convection_Diffusion_std::inconnue(), Turbulence_paroi_scal_base::le_dom_Cl_dis_, Turbulence_paroi_scal_base::le_dom_dis_, Frontiere_dis_base::le_nom(), Domaine_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_, _SIZE_ >::local_min_vect(), Modele_turbulence_hyd_base::loi_paroi(), Milieu_base::masse_volumique(), Equation_base::milieu(), Turbulence_paroi_scal_base::mon_modele_turb_scal, N, Field_base::nb_comp(), Domaine_dis_base::nb_elem(), Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_local_face(), Front_VF::num_premiere_face(), Schema_Temps_base::pas_de_temps(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Equation_base::schema_temps(), Equation_base::sources(), stats, Echange_contact_VDF::T_autre_pb(), Echange_impose_base::T_ext(), Turbulence_paroi_base::tab_u_star(), Tau, Schema_Temps_base::temps_courant(), temps_deb_stats, temps_dern_post_inst, TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), TRUST_Ref_Objet_U::valeur(), Champ_Don_base::valeurs(), Champ_Inc_base::valeurs(), Champ_Proto::valeurs(), Champ_front_base::valeurs_au_temps(), Fluide_base::viscosite_cinematique(), and Domaine_VF::xv().
init_lois_paroi()
int Paroi_ODVM_scal_VDF::init_lois_paroi () override virtual
Reimplemented from Paroi_scal_hyd_base_VDF.
References Objet_U::axi, Milieu_base::capacite_calorifique(), Milieu_base::conductivite(), TRUST_Vector< _CLASSE_ >::dimensionner(), Domaine_VDF::dist_norm_bord(), Domaine_VDF::dist_norm_bord_axi(), Equation_base::domaine_Cl_dis(), eq_odvm, Process::exit(), Domaine_VF::face_voisins(), facteur, gamma, Equation_base::inconnue(), Turbulence_paroi_scal_base::le_dom_Cl_dis_, Turbulence_paroi_scal_base::le_dom_dis_, Domaine_Cl_dis_base::les_conditions_limites(), Milieu_base::masse_volumique(), Champ_front_calc::milieu(), Equation_base::milieu(), Turbulence_paroi_scal_base::mon_modele_turb_scal, N, Front_VF::nb_faces(), Domaine_VF::nb_faces_bord(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), Equation_base::schema_temps(), stats, Echange_contact_VDF::T_autre_pb(), Echange_impose_base::T_ext(), Tau, Schema_Temps_base::temps_courant(), TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), Champ_Inc_base::valeurs(), and Champ_Proto::valeurs().
get_Tf0() [1/2]
double Paroi_ODVM_scal_VDF::get_Tf0 (int num_face) const inline
Referenced by Echange_contact_ODVM_VDF::calculer_Teta_equiv().
get_Tf0() [2/2]
const DoubleVect & Paroi_ODVM_scal_VDF::get_Tf0 () const inline
Member Data Documentation
info_obj
const Type_info Paroi_ODVM_scal_VDF::info_obj static
N
int Paroi_ODVM_scal_VDF::N protected
Referenced by calculer_scal(), init_lois_paroi(), and readOn().
CHT
int Paroi_ODVM_scal_VDF::CHT protected
Timp
int Paroi_ODVM_scal_VDF::Timp protected
diff_unif
int Paroi_ODVM_scal_VDF::diff_unif protected
stats
int Paroi_ODVM_scal_VDF::stats protected
Referenced by calculer_scal(), init_lois_paroi(), and readOn().
compt
int Paroi_ODVM_scal_VDF::compt protected
Referenced by calculer_scal(), and readOn().
check
int Paroi_ODVM_scal_VDF::check protected
Referenced by calculer_scal(), and readOn().
gamma
double Paroi_ODVM_scal_VDF::gamma protected
Referenced by init_lois_paroi(), and readOn().
temps_deb_stats
double Paroi_ODVM_scal_VDF::temps_deb_stats protected
Referenced by calculer_scal(), and readOn().
dt_impr
double Paroi_ODVM_scal_VDF::dt_impr protected
Referenced by calculer_scal(), and readOn().
Tau
double Paroi_ODVM_scal_VDF::Tau protected
Referenced by calculer_scal(), and init_lois_paroi().
temps_dern_post_inst
double Paroi_ODVM_scal_VDF::temps_dern_post_inst protected
Referenced by calculer_scal(), and readOn().
facteur
double Paroi_ODVM_scal_VDF::facteur protected
Referenced by init_lois_paroi(), and readOn().
eq_odvm
TRUST_Vector< Eq_ODVM > Paroi_ODVM_scal_VDF::eq_odvm protected
Referenced by calculer_scal(), and init_lois_paroi().