TrioCFD: Op_VDF_Face Class Reference
Op_VDF_Face Class Reference
#include <Op_VDF_Face.h>
Member Function Documentation
dimensionner()
void Op_VDF_Face::dimensionner (const Domaine_VDF & le_dom, const Domaine_Cl_VDF & le_dom_cl, Matrice_Morse & la_matrice) const
References Objet_U::dimension, Matrice_Morse::dimensionner(), Domaine_VF::elem_faces(), MorEqn::equation(), Domaine_VDF::face_amont_princ(), Domaine_VDF::face_bord_amont(), Domaine_VF::face_voisins(), Matrice_Morse::get_set_coeff(), Matrice_Morse::get_set_tab1(), Matrice_Morse::get_set_tab2(), Equation_base::inconnue(), Domaine_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Front_VF::nb_faces(), Domaine_VF::nb_faces_tot(), Front_VF::num_premiere_face(), Domaine_VDF::orientation(), TRUST_Deriv< _CLASSE_ >::valeur(), and Champ_Inc_base::valeurs().
Referenced by Op_Diff_VDF_Face_Axi_base::dimensionner(), Op_Dift_VDF_Face_Axi_base::dimensionner(), Op_Diff_VDF_Face_base::dimensionner_blocs(), Op_Dift_VDF_Face_base::dimensionner_blocs(), and Op_Conv_VDF< OP_TYPE >::dimensionner_face().
modifier_pour_Cl()
void Op_VDF_Face::modifier_pour_Cl (const Domaine_VDF & le_dom, const Domaine_Cl_VDF & le_dom_cl, Matrice_Morse & la_matrice, DoubleTab & secmem) const
References MorEqn::equation(), Equation_base::inconnue(), Domaine_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), Domaine_VDF::orientation(), Dirichlet::val_imp(), Dirichlet_homogene::val_imp(), TRUST_Deriv< _CLASSE_ >::valeur(), and Champ_Inc_base::valeurs().
Referenced by Op_Diff_VDF_Face_Axi_base::modifier_pour_Cl(), Op_Diff_VDF_Face_base::modifier_pour_Cl(), Op_Dift_VDF_Face_Axi_base::modifier_pour_Cl(), Op_Dift_VDF_Face_base::modifier_pour_Cl(), and Op_Conv_VDF< OP_TYPE >::modifier_pour_Cl_face().