TrioCFD: Perte_Charge_VEF_Face Class Reference
Perte_Charge_VEF_Face Class Reference abstract
#include <Perte_Charge_VEF_Face.h>
Public Member Functions
const Type_info * get_info () const override
void mettre_a_jour (double) override
Public Member Functions inherited from Source_base
virtual int a_pour_Champ_Fonc (const Motcle &mot, TRUST_Ref< Champ_base * > &ch_ref) const
virtual void associer_champ_rho (const Champ_base &champ_rho)
virtual void completer ()
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
virtual void resetTime (double t)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Terme_Source_Qdm
const Champ_Don_base & source () const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
See also
Source_base
Constructor & Destructor Documentation
Perte_Charge_VEF_Face()
Perte_Charge_VEF_Face::Perte_Charge_VEF_Face ()
~Perte_Charge_VEF_Face()
Perte_Charge_VEF_Face::~Perte_Charge_VEF_Face () override
Member Function Documentation
info()
const Type_info * Perte_Charge_VEF_Face::info () static
get_info()
const Type_info * Perte_Charge_VEF_Face::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Source_base.
self_cast() [1/2]
Perte_Charge_VEF_Face & Perte_Charge_VEF_Face::self_cast (Objet_U & r) static
self_cast() [2/2]
const Perte_Charge_VEF_Face & Perte_Charge_VEF_Face::self_cast (const Objet_U & r) static
printOn()
Sortie & Perte_Charge_VEF_Face::printOn (Sortie & os) const override protected virtual
DOES NOTHING - to override in derived classes.
Imprime la source sur un flot de sortie.
Parameters
(Sortie& os) le flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Source_base.
References Objet_U::que_suis_je().
readOn()
Entree & Perte_Charge_VEF_Face::readOn (Entree & is) override protected virtual
DOES NOTHING - to override in derived classes.
Lecture d'un terme source sur un flot d'entree.
Parameters
(Entree& is) le flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Source_base.
ajouter()
DoubleTab & Perte_Charge_VEF_Face::ajouter (DoubleTab &) const override pure virtual
Reimplemented from Source_base.
Implemented in Perte_Charge_Reguliere_QC_VEF_P1NC, Perte_Charge_Singuliere_QC_VEF_P1NC, Perte_Charge_Reguliere_VEF_P1NC, Perte_Charge_Singuliere_VEF_Face, and DP_Impose_VEF_Face.
associer_pb()
void Perte_Charge_VEF_Face::associer_pb (const Probleme_base & pb) override virtual
Implements Source_base.
References associer_domaines(), Equation_base::domaine_Cl_dis(), Equation_base::domaine_dis(), Probleme_base::equation(), Process::exit(), Equation_base::inconnue(), la_vitesse, le_fluide, Equation_base::milieu(), and Probleme_base::nombre_d_equations().
mettre_a_jour()
void Perte_Charge_VEF_Face::mettre_a_jour (double temps) override virtual
DOES NOTHING - to override in derived classes.
Mise a jour en temps du terme source.
Parameters
(double) le pas de temps de mise a jour
Reimplemented from Source_base.
Referenced by Perte_Charge_Singuliere_VEF_Face::mettre_a_jour().
associer_domaines()
void Perte_Charge_VEF_Face::associer_domaines (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis) override protected virtual
Implements Source_base.
References le_dom_Cl_VEF, and le_dom_VEF.
Referenced by associer_pb().
Member Data Documentation
info_obj
const Type_info Perte_Charge_VEF_Face::info_obj static
la_vitesse
TRUST_Ref< Champ_Inc_base *> Perte_Charge_VEF_Face::la_vitesse protected
Referenced by Perte_Charge_Reguliere_VEF_P1NC::ajouter(), Perte_Charge_Singuliere_VEF_Face::ajouter(), associer_pb(), Perte_Charge_Reguliere_VEF_P1NC::contribuer_a_avec(), and Perte_Charge_Singuliere_VEF_Face::contribuer_a_avec().
le_dom_VEF
TRUST_Ref< Domaine_VEF *> Perte_Charge_VEF_Face::le_dom_VEF protected
Referenced by Perte_Charge_Singuliere_VEF_Face::ajouter(), associer_domaines(), Perte_Charge_Singuliere_VEF_Face::contribuer_a_avec(), and Perte_Charge_Reguliere_VEF_P1NC::remplir_num_faces().
le_dom_Cl_VEF
TRUST_Ref< Domaine_Cl_VEF *> Perte_Charge_VEF_Face::le_dom_Cl_VEF protected
Referenced by associer_domaines().
le_fluide
TRUST_Ref< Fluide_base *> Perte_Charge_VEF_Face::le_fluide protected
Referenced by Perte_Charge_Reguliere_VEF_P1NC::ajouter(), associer_pb(), and Perte_Charge_Reguliere_VEF_P1NC::contribuer_a_avec().
num_faces
IntVect Perte_Charge_VEF_Face::num_faces protected
Referenced by Perte_Charge_Singuliere_VEF_Face::ajouter(), DP_Impose_VEF_Face::ajouter_blocs(), Perte_Charge_Singuliere_VEF_Face::contribuer_a_avec(), DP_Impose_VEF_Face::dimensionner_blocs(), DP_Impose_VEF_Face::mettre_a_jour(), Perte_Charge_Singuliere_VEF_Face::mettre_a_jour(), DP_Impose_VEF_Face::remplir_num_faces(), and Perte_Charge_Singuliere_VEF_Face::remplir_num_faces().