TrioCFD: Statistiques_dns_ijk Class Reference
Statistiques_dns_ijk Class Reference
#include <Statistiques_dns_ijk.h>
Public Member Functions
const IJK_Field_double & get_IJK_field (const Motcle &nom) override
const Type_info * get_info () const override
bool is_post_required (const Motcle &nom) const
int lire_motcle_non_standard (const Motcle &mot, Entree &is) override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Public Types inherited from Champs_compris_IJK_interface
using FieldInfo_t = std::tuple< Motcle, Entity, Nature_du_champ, bool >
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Statistiques_dns_ijk()
Statistiques_dns_ijk::Statistiques_dns_ijk ()
References check_converge_, TRUST_Vector< _CLASSE_ >::dimensionner(), kval_, noms_k_, noms_moyennes_, nval_, t_integration_, and t_integration_k_.
~Statistiques_dns_ijk()
Statistiques_dns_ijk::~Statistiques_dns_ijk ()
Member Function Documentation
cree_instance()
Objet_U * Statistiques_dns_ijk::cree_instance () static
taille_memoire()
unsigned Statistiques_dns_ijk::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Statistiques_dns_ijk_FT, Statistiques_dns_ijk_monophasique, and Statistiques_dns_qc_ijk.
duplique()
int Statistiques_dns_ijk::duplique () const override virtual
Implements Objet_U.
Reimplemented in Statistiques_dns_ijk_FT, Statistiques_dns_ijk_monophasique, and Statistiques_dns_qc_ijk.
info()
const Type_info * Statistiques_dns_ijk::info () static
get_info()
const Type_info * Statistiques_dns_ijk::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
Reimplemented in Statistiques_dns_ijk_FT, Statistiques_dns_ijk_monophasique, and Statistiques_dns_qc_ijk.
self_cast() [1/2]
Statistiques_dns_ijk & Statistiques_dns_ijk::self_cast (Objet_U & r) static
self_cast() [2/2]
const Statistiques_dns_ijk & Statistiques_dns_ijk::self_cast (const Objet_U & r) static
printOn()
Sortie & Statistiques_dns_ijk::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
Reimplemented in Statistiques_dns_ijk_FT, Statistiques_dns_ijk_monophasique, and Statistiques_dns_qc_ijk.
References check_converge_, completer_print(), integrale_k_, integrale_temporelle_, Process::je_suis_maitre(), kval_, noms_k_, noms_moyennes_, nval_, t_integration_, and t_integration_k_.
Referenced by Statistiques_dns_ijk_FT::printOn(), Statistiques_dns_ijk_monophasique::printOn(), and Statistiques_dns_qc_ijk::printOn().
readOn()
Entree & Statistiques_dns_ijk::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
Reimplemented in Statistiques_dns_ijk_FT, Statistiques_dns_ijk_monophasique, and Statistiques_dns_qc_ijk.
References Param::ajouter(), Param::ajouter_flag(), Param::ajouter_non_std(), check_converge_, completer_read(), integrale_k_, integrale_temporelle_, kval_, Param::lire_avec_accolades(), noms_k_, noms_moyennes_, nval_, Objet_U::que_suis_je(), t_integration_, and t_integration_k_.
Referenced by Statistiques_dns_ijk_FT::readOn(), Statistiques_dns_ijk_monophasique::readOn(), and Statistiques_dns_qc_ijk::readOn().
completer_print()
virtual Sortie & Statistiques_dns_ijk::completer_print (Sortie & os) const inline virtual
Reimplemented in Statistiques_dns_ijk_FT.
Referenced by printOn().
completer_read()
virtual void Statistiques_dns_ijk::completer_read (Param & param) inline virtual
Reimplemented in Statistiques_dns_ijk_FT, and Statistiques_dns_qc_ijk.
References Process::exit(), and Objet_U::que_suis_je().
Referenced by readOn().
postraiter()
void Statistiques_dns_ijk::postraiter (Sortie & os, int flag_valeur_instantanee = 0) const
References elem_coord_, Process::exit(), integrale_temporelle_, Process::je_suis_maitre(), moyenne_spatiale_instantanee_, noms_moyennes_, nval_, TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and t_integration_.
Referenced by Statistiques_dns_ijk_FT::postraiter(), DNS_QC_double::posttraiter_champs_instantanes(), and DNS_QC_double::save_stats().
postraiter_k()
void Statistiques_dns_ijk::postraiter_k (Sortie & os, int flag_valeur_instantanee = 0) const
References elem_coord_, Process::exit(), integrale_k_, Process::je_suis_maitre(), kval_, moyenne_spatiale_ec_, noms_k_, TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and t_integration_k_.
Referenced by DNS_QC_double::posttraiter_champs_instantanes(), and DNS_QC_double::save_stats().
update_stat()
void Statistiques_dns_ijk::update_stat (const IJK_Field_vector3_double & vitesse, const IJK_Field_double & pression, const IJK_Field_double & temperature, const IJK_Field_double & masse_vol, const IJK_Field_double & champ_mu, const IJK_Field_double & champ_lambda, const ArrOfDouble_with_ghost & delta_z_local_pour_delta, const bool flag_nu_anisotropic, const int flag_turbulent_viscosity, const IJK_Field_double & champ_turbulent_mu_xx, const IJK_Field_double & champ_turbulent_mu_xy, const IJK_Field_double & champ_turbulent_mu_xz, const IJK_Field_double & champ_turbulent_mu_yy, const IJK_Field_double & champ_turbulent_mu_yz, const IJK_Field_double & champ_turbulent_mu_zz, const bool flag_kappa_anisotropic, const int flag_turbulent_diffusivity, const IJK_Field_double & champ_turbulent_kappa_x, const IJK_Field_double & champ_turbulent_kappa_y, const IJK_Field_double & champ_turbulent_kappa_z, const int flag_structural_uu, const FixedVector< IJK_Field_double, 6 > & structural_uu_tensor, const int flag_structural_uscalar, const IJK_Field_vector3_double & structural_uscalar_vector, const int flag_formulation_favre, const int flag_formulation_velocity, const double cp_gaz, const double pression_thermodynamique, double dt)
References elem_coord_, Process::exit(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by DNS_QC_double::run().
update_stat_k()
void Statistiques_dns_ijk::update_stat_k (const IJK_Field_vector3_double & vitesse, const IJK_Field_double & pression, const IJK_Field_double & masse_vol, const IJK_Field_double & champ_mu, const double pression_thermodynamique, const double terme_source_acceleration, double dt)
References elem_coord_, Process::exit(), nu_moy_, rho_moy_, TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and vit_moy_.
Referenced by DNS_QC_double::run().
lire_motcle_non_standard()
int Statistiques_dns_ijk::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Objet_U.
Reimplemented in Statistiques_dns_ijk_FT.
References Param::ajouter(), Process::exit(), integrale_temporelle_, Param::lire_avec_accolades(), noms_moyennes_, nval_, and Objet_U::que_suis_je().
Referenced by Statistiques_dns_ijk_FT::lire_motcle_non_standard().
initialize() [1/2]
virtual void Statistiques_dns_ijk::initialize (const Domaine_IJK &) inline virtual
Reimplemented in Statistiques_dns_ijk_FT, Statistiques_dns_ijk_monophasique, Statistiques_dns_qc_ijk, and Statistiques_dns_ijk_monophasique.
References Process::exit().
initialize() [2/2]
void Statistiques_dns_ijk::initialize (const Domaine_IJK & geom, const double T_KMAX, const double T_KMIN, const double constante_specifique_gaz) virtual
Reimplemented in Statistiques_dns_ijk_FT, Statistiques_dns_ijk_monophasique, and Statistiques_dns_qc_ijk.
References check_converge_, constante_specifique_gaz_, dx_, dy_, elem_coord_, Process::exit(), Domaine_IJK::get_constant_delta(), Domaine_IJK::get_delta(), Domaine_IJK::get_nb_elem_tot(), Domaine_IJK::get_node_coordinates(), integrale_k_, integrale_temporelle_, Process::je_suis_maitre(), kval_, moyenne_spatiale_ec_, moyenne_spatiale_instantanee_, nu_moy_, nval_, TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), rho_moy_, t_integration_, t_integration_k_, tab_dz_, TCL_kmax_, TCL_kmin_, and vit_moy_.
has_champ()
bool Statistiques_dns_ijk::has_champ (const Motcle & nom) const inline override virtual
Implements Champs_compris_IJK_interface.
References champs_compris_, and Champs_compris_T< FIELD_TYPE >::has_champ().
Referenced by Postprocessing_IJK::get_IJK_field(), get_IJK_field(), Statistiques_dns_ijk_FT::get_IJK_field(), and Postprocessing_IJK::has_champ().
has_champ_vectoriel()
bool Statistiques_dns_ijk::has_champ_vectoriel (const Motcle & nom) const inline override virtual
Implements Champs_compris_IJK_interface.
References champs_compris_, and Champs_compris_IJK::has_champ_vectoriel().
Referenced by Postprocessing_IJK::get_IJK_field_vector(), get_IJK_field_vector(), Statistiques_dns_ijk_FT::get_IJK_field_vector(), and Postprocessing_IJK::has_champ_vectoriel().
get_IJK_field_vector()
const IJK_Field_vector3_double & Statistiques_dns_ijk::get_IJK_field_vector (const Motcle & nom) override virtual
Implements Champs_compris_IJK_interface.
Reimplemented in Statistiques_dns_ijk_FT.
References champs_compris_, Champs_compris_IJK::get_champ_vectoriel(), and has_champ_vectoriel().
get_IJK_field()
const IJK_Field_double & Statistiques_dns_ijk::get_IJK_field (const Motcle & nom) override virtual
Retrieve requested field for postprocessing, potentially updating it.
Implements Champs_compris_IJK_interface.
Reimplemented in Statistiques_dns_ijk_FT.
References champs_compris_, Champs_compris_T< FIELD_TYPE >::get_champ(), and has_champ().
associer_domaine()
void Statistiques_dns_ijk::associer_domaine (Domaine_IJK & dom_ijk)
References domaine_ijk_.
Referenced by Postprocessing_IJK::associer_domaines().
is_stats_plans_activated()
bool Statistiques_dns_ijk::is_stats_plans_activated () const
References ref_ijk_ft_.
is_post_required()
bool Statistiques_dns_ijk::is_post_required (const Motcle & nom) const
Was the field of name 'nom' requested for postprocessing?
References ref_ijk_ft_.
Fill_postprocessable_fields()
void Statistiques_dns_ijk::Fill_postprocessable_fields (std::vector< FieldInfo_t > & chps) static
References Nom::getString().
Referenced by Probleme_FTD_IJK_base::Fill_postprocessable_fields().
get_noms_champs_postraitables()
void Statistiques_dns_ijk::get_noms_champs_postraitables (Noms & noms, Option opt = NONE) const
References TRUST_Vector< _CLASSE_ >::add(), champs_compris_, Champs_compris_IJK::liste_noms_compris(), and Champs_compris_IJK::liste_noms_compris_vectoriel().
Referenced by Postprocessing_IJK::get_noms_champs_postraitables().
t_integration()
const double & Statistiques_dns_ijk::t_integration () const inline
References t_integration_.
Referenced by DNS_QC_double::ecrire_fichier_sauv(), DNS_QC_double::posttraiter_champs_instantanes(), Postprocessing_IJK::posttraiter_statistiques_plans(), Postprocessing_IJK::sauvegarder_post_maitre(), and DNS_QC_double::save_stats().
t_integration_k()
double Statistiques_dns_ijk::t_integration_k () const inline
References t_integration_k_.
Referenced by DNS_QC_double::posttraiter_champs_instantanes(), and DNS_QC_double::save_stats().
check_converge()
int Statistiques_dns_ijk::check_converge () const inline
References check_converge_.
Referenced by DNS_QC_double::posttraiter_champs_instantanes(), DNS_QC_double::run(), and DNS_QC_double::save_stats().
vitesse_moyenne()
TRUST_Vector< ArrOfDouble > Statistiques_dns_ijk::vitesse_moyenne () const inline
References vit_moy_.
Referenced by DNS_QC_double::initialise().
masse_volumique_moyenne()
ArrOfDouble Statistiques_dns_ijk::masse_volumique_moyenne () const inline
References rho_moy_.
Referenced by DNS_QC_double::initialise().
viscosite_cinematique_moyenne()
ArrOfDouble Statistiques_dns_ijk::viscosite_cinematique_moyenne () const inline
References nu_moy_.
Referenced by DNS_QC_double::initialise().
is_converge()
int Statistiques_dns_ijk::is_converge () const inline
References check_converge_.
Referenced by DNS_QC_double::initialise().
compute_and_store_gradU_cell()
void Statistiques_dns_ijk::compute_and_store_gradU_cell (const IJK_Field_double & vitesse_i, const IJK_Field_double & vitesse_j, const IJK_Field_double & vitesse_k)
References compute_and_store_gradU_cell(), dx_, dy_, IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel(), Domaine_IJK::ELEM, IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_domaine(), Domaine_IJK::get_nb_items_global(), Domaine_IJK::get_nb_items_local(), Domaine_IJK::get_offset_local(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost(), tab_dz_, and vect_post_fields_.
Referenced by compute_and_store_gradU_cell(), and Postprocessing_IJK::update_gradU_lambda2().
cell_to_cell_gradient()
void Statistiques_dns_ijk::cell_to_cell_gradient (const int i, const int j, const int k, const IJK_Field_double & dudx, const IJK_Field_double & dvdy, const IJK_Field_double & dwdx, const IJK_Field_double & dudz, const IJK_Field_double & dvdz, const IJK_Field_double & dwdz, double & ddudxy, double & ddudxz, double & ddudyz, double & ddvdxy, double & ddvdxz, double & ddvdyz, double & ddwdxy, double & ddwdxz, double & ddwdyz) const
References dx_, and dy_.
face_to_cell_gradient()
double Statistiques_dns_ijk::face_to_cell_gradient (const IJK_Field_double & vitesse_i, const IJK_Field_double & vitesse_j, const IJK_Field_double & vitesse_k, const int i, const int j, const int k, const double dz, double & duidx, double & dujdx, double & dukdx, double & duidy, double & dujdy, double & dukdy, double & duidz, double & dujdz, double & dukdz, const bool on_the_first_cell, const bool on_the_last_cell, const int bc_type) const
References dx_, dy_, IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_domaine(), and Domaine_IJK::get_periodic_flag().
calculer_gradients_vitesse()
double Statistiques_dns_ijk::calculer_gradients_vitesse (const IJK_Field_double & vitesse_i, const IJK_Field_double & vitesse_j, const IJK_Field_double & vitesse_k, const int i, const int j, const int k, const double dz, double & duidx, double & dujdx, double & dukdx, double & duidy, double & dujdy, double & dukdy, double & duidz, double & dujdz, double & dukdz, double & dduidxx, double & ddujdxx, double & ddukdxx, double & dduidyy, double & ddujdyy, double & ddukdyy, double & dduidzz, double & ddujdzz, double & ddukdzz, const bool on_the_first_cell, const bool on_the_last_cell) const
References dx_, and dy_.
calculer_vraie_dissipation()
double Statistiques_dns_ijk::calculer_vraie_dissipation (const double & pseudo_dissip, const double & duidx, const double & duidy, const double & duidz, const double & dujdx, const double & dujdy, const double & dujdz, const double & dukdx, const double & dukdy, const double & dukdz) const
calculer_produit_scalaire_faces_to_center()
double Statistiques_dns_ijk::calculer_produit_scalaire_faces_to_center (const IJK_Field_double & ui, const IJK_Field_double & uj, const IJK_Field_double & uk, const IJK_Field_double & vi, const IJK_Field_double & vj, const IJK_Field_double & vk, const int i, const int j, const int k)
compute_and_store_scalar_product_face_to_face()
IJK_Field_double Statistiques_dns_ijk::compute_and_store_scalar_product_face_to_face (const IJK_Field_double & v1_i, const IJK_Field_double & v1_j, const IJK_Field_double & v1_k, const IJK_Field_double & v2_i, const IJK_Field_double & v2_j, const IJK_Field_double & v2_k)
References IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::data(), Domaine_IJK::ELEM, IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_domaine(), and Domaine_IJK::get_nb_items_local().
compute_vecA_minus_vecB_in_vecA()
void Statistiques_dns_ijk::compute_vecA_minus_vecB_in_vecA (IJK_Field_vector3_double & vecA, const IJK_Field_vector3_double & vecB)
References Domaine_IJK::ELEM, IJK_Field_vector< T, N >::get_domaine(), and Domaine_IJK::get_nb_items_local().
Member Data Documentation
info_obj
const Type_info Statistiques_dns_ijk::info_obj static
elem_coord_
ArrOfDouble Statistiques_dns_ijk::elem_coord_ protected
Referenced by Statistiques_dns_ijk_FT::completer_print(), Statistiques_dns_ijk_FT::compute_desequil_alpha(), Statistiques_dns_ijk_monophasique::initialize(), initialize(), Statistiques_dns_ijk_FT::initialize(), postraiter(), postraiter_k(), Statistiques_dns_ijk_FT::postraiter_thermique(), update_stat(), Statistiques_dns_ijk_monophasique::update_stat(), and update_stat_k().
dx_
double Statistiques_dns_ijk::dx_ protected
Referenced by calculer_gradients_vitesse(), cell_to_cell_gradient(), compute_and_store_gradU_cell(), face_to_cell_gradient(), Statistiques_dns_ijk_monophasique::initialize(), initialize(), and Statistiques_dns_ijk_FT::initialize().
dy_
double Statistiques_dns_ijk::dy_ protected
Referenced by calculer_gradients_vitesse(), cell_to_cell_gradient(), compute_and_store_gradU_cell(), face_to_cell_gradient(), Statistiques_dns_ijk_monophasique::initialize(), initialize(), and Statistiques_dns_ijk_FT::initialize().
tab_dz_
ArrOfDouble Statistiques_dns_ijk::tab_dz_ protected
Referenced by compute_and_store_gradU_cell(), Statistiques_dns_ijk_monophasique::initialize(), initialize(), and Statistiques_dns_ijk_FT::initialize().
ref_ijk_ft_
TRUST_Ref< Probleme_FTD_IJK_base *> Statistiques_dns_ijk::ref_ijk_ft_ protected
Referenced by Statistiques_dns_ijk_FT::associer_probleme(), Statistiques_dns_ijk_FT::get_IJK_field_vector(), Statistiques_dns_ijk_FT::initialize(), is_post_required(), and is_stats_plans_activated().
domaine_ijk_
TRUST_Ref< Domaine_IJK *> Statistiques_dns_ijk::domaine_ijk_ protected
Referenced by Statistiques_dns_ijk_FT::alloc_fields(), and associer_domaine().
moyenne_spatiale_instantanee_
TRUST_Vector< ArrOfDouble > Statistiques_dns_ijk::moyenne_spatiale_instantanee_ protected
Referenced by Statistiques_dns_ijk_FT::compute_desequil_alpha(), Statistiques_dns_ijk_monophasique::initialize(), initialize(), Statistiques_dns_ijk_FT::initialize(), and postraiter().
moyenne_spatiale_ec_
TRUST_Vector< ArrOfDouble > Statistiques_dns_ijk::moyenne_spatiale_ec_ protected
Referenced by initialize(), and postraiter_k().
integrale_temporelle_
TRUST_Vector< ArrOfDouble > Statistiques_dns_ijk::integrale_temporelle_ protected
Referenced by Statistiques_dns_ijk_monophasique::initialize(), initialize(), Statistiques_dns_ijk_FT::initialize(), lire_motcle_non_standard(), postraiter(), printOn(), and readOn().
t_integration_
double Statistiques_dns_ijk::t_integration_ protected
Referenced by Statistiques_dns_ijk_FT::completer_print(), Statistiques_dns_ijk_monophasique::initialize(), initialize(), Statistiques_dns_ijk_FT::initialize(), postraiter(), Statistiques_dns_ijk_FT::postraiter_thermique(), printOn(), readOn(), Statistiques_dns_ijk(), and t_integration().
noms_moyennes_
TRUST_Vector< Nom > Statistiques_dns_ijk::noms_moyennes_ protected
Referenced by lire_motcle_non_standard(), postraiter(), printOn(), readOn(), Statistiques_dns_ijk(), Statistiques_dns_ijk_FT::Statistiques_dns_ijk_FT(), and Statistiques_dns_ijk_monophasique::Statistiques_dns_ijk_monophasique().
noms_k_
TRUST_Vector< Nom > Statistiques_dns_ijk::noms_k_ protected
Referenced by postraiter_k(), printOn(), readOn(), and Statistiques_dns_ijk().
nval_
int Statistiques_dns_ijk::nval_ protected
Referenced by Statistiques_dns_ijk_monophasique::initialize(), initialize(), Statistiques_dns_ijk_FT::initialize(), lire_motcle_non_standard(), Statistiques_dns_ijk_FT::lire_motcle_non_standard(), postraiter(), printOn(), readOn(), Statistiques_dns_ijk(), Statistiques_dns_ijk_FT::Statistiques_dns_ijk_FT(), and Statistiques_dns_ijk_monophasique::Statistiques_dns_ijk_monophasique().
kval_
int Statistiques_dns_ijk::kval_ protected
Referenced by initialize(), postraiter_k(), printOn(), readOn(), and Statistiques_dns_ijk().
t_integration_k_
double Statistiques_dns_ijk::t_integration_k_ protected
Referenced by initialize(), postraiter_k(), printOn(), readOn(), Statistiques_dns_ijk(), and t_integration_k().
check_converge_
int Statistiques_dns_ijk::check_converge_ protected
Referenced by check_converge(), Statistiques_dns_ijk_monophasique::initialize(), initialize(), Statistiques_dns_ijk_FT::initialize(), is_converge(), printOn(), readOn(), and Statistiques_dns_ijk().
integrale_k_
TRUST_Vector< ArrOfDouble > Statistiques_dns_ijk::integrale_k_ protected
Referenced by initialize(), postraiter_k(), printOn(), and readOn().
vit_moy_
TRUST_Vector< ArrOfDouble > Statistiques_dns_ijk::vit_moy_ protected
Referenced by Statistiques_dns_ijk_monophasique::initialize(), initialize(), Statistiques_dns_ijk_FT::initialize(), update_stat_k(), and vitesse_moyenne().
rho_moy_
ArrOfDouble Statistiques_dns_ijk::rho_moy_ protected
Referenced by initialize(), masse_volumique_moyenne(), and update_stat_k().
nu_moy_
ArrOfDouble Statistiques_dns_ijk::nu_moy_ protected
Referenced by initialize(), update_stat_k(), and viscosite_cinematique_moyenne().
TCL_kmax_
double Statistiques_dns_ijk::TCL_kmax_ protected
Referenced by initialize().
TCL_kmin_
double Statistiques_dns_ijk::TCL_kmin_ protected
Referenced by initialize().
constante_specifique_gaz_
double Statistiques_dns_ijk::constante_specifique_gaz_ protected
Referenced by initialize().
scalar_post_fields_
std::map<Motcle, IJK_Field_double> Statistiques_dns_ijk::scalar_post_fields_ protected
vect_post_fields_
std::map<Motcle, IJK_Field_vector3_double> Statistiques_dns_ijk::vect_post_fields_ protected
Referenced by Statistiques_dns_ijk_FT::alloc_fields(), compute_and_store_gradU_cell(), and Statistiques_dns_ijk_FT::get_IJK_field_vector().
champs_compris_
Champs_compris_IJK Statistiques_dns_ijk::champs_compris_ protected
the actual fields registered and managed by the post-processing part (=all the extra fields, not the main unknowns)
Referenced by Statistiques_dns_ijk_FT::alloc_fields(), get_IJK_field(), Statistiques_dns_ijk_FT::get_IJK_field(), get_IJK_field_vector(), Statistiques_dns_ijk_FT::get_IJK_field_vector(), get_noms_champs_postraitables(), has_champ(), and has_champ_vectoriel().