TrioCFD: Transport_Flux_Chaleur_Turbulente Class Reference
Transport_Flux_Chaleur_Turbulente Class Reference
#include <Transport_Flux_Chaleur_Turbulente.h>
Public Member Functions
void completer () override
void discretiser () override
const Motcle & domaine_application () const override
const Type_info * get_info () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
int nombre_d_operateurs () const override
const Operateur & operateur (int) const override
Operateur & operateur (int) override
Public Member Functions inherited from Convection_Diffusion_std
void associer_vitesse (const Champ_base &)
const Type_info * get_info () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
int nombre_d_operateurs () const override
const Operateur & operateur (int) const override
Operateur & operateur (int) override
const Champ_Inc_base & vitesse_transportante () const
Public Member Functions inherited from Equation_base
virtual void abortTimeStep ()
virtual void associer_domaine_dis (const Domaine_dis_base &)
virtual void associer_pb_base (const Probleme_base &)
virtual void associer_sch_tps_base (const Schema_Temps_base &)
virtual double calculer_pas_de_temps () const
virtual void completer ()
virtual std::vector< YAML_data > data_a_sauvegarder () const
DoubleTab & derivee_en_temps_conv (DoubleTab &, const DoubleTab &)
virtual DoubleTab & derivee_en_temps_inco (DoubleTab &)
const Discretisation_base & discretisation () const
virtual void discretiser ()
virtual const Motcle & domaine_application () const
virtual Domaine_Cl_dis_base & domaine_Cl_dis ()
virtual const Domaine_Cl_dis_base & domaine_Cl_dis () const
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual void imprimer (Sortie &os) const
virtual bool initTimeStep (double dt)
const Nom & le_nom () const override
int limpr () const
virtual void mettre_a_jour (double temps)
virtual int preparer_calcul ()
Probleme_base & probleme ()
const Probleme_base & probleme () const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Schema_Temps_base & schema_temps ()
const Schema_Temps_base & schema_temps () const
Solveur_Masse_base & solv_masse ()
const Solveur_Masse_base & solv_masse () const
Sources & sources ()
const Sources & sources () const
virtual void valider_iteration ()
virtual void verifie_ch_init_nb_comp (const Champ_Inc_base &ch_ref, const int nb_comp) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Equation_base
virtual Entree & lire_cl (Entree &)
virtual Entree & lire_cond_init (Entree &)
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual Entree & lire_sources (Entree &)
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
virtual int verif_Cl () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
~Transport_Flux_Chaleur_Turbulente()
Transport_Flux_Chaleur_Turbulente::~Transport_Flux_Chaleur_Turbulente ()
Transport_Flux_Chaleur_Turbulente()
Transport_Flux_Chaleur_Turbulente::Transport_Flux_Chaleur_Turbulente ()
Member Function Documentation
cree_instance()
Objet_U * Transport_Flux_Chaleur_Turbulente::cree_instance () static
taille_memoire()
unsigned Transport_Flux_Chaleur_Turbulente::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Transport_Flux_Chaleur_Turbulente::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Transport_Flux_Chaleur_Turbulente::info () static
get_info()
const Type_info * Transport_Flux_Chaleur_Turbulente::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Convection_Diffusion_std.
self_cast() [1/2]
Transport_Flux_Chaleur_Turbulente & Transport_Flux_Chaleur_Turbulente::self_cast (Objet_U & r) static
self_cast() [2/2]
const Transport_Flux_Chaleur_Turbulente & Transport_Flux_Chaleur_Turbulente::self_cast (const Objet_U & r) static
printOn()
Sortie & Transport_Flux_Chaleur_Turbulente::printOn (Sortie & is) const override protected virtual
Simple appel a Equation_base::printOn(Sortie&)
Parameters
(Sortie& is) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Convection_Diffusion_std.
References Objet_U::que_suis_je().
readOn()
Entree & Transport_Flux_Chaleur_Turbulente::readOn (Entree & is) override protected virtual
cf Convection_Diffusion_std::readOn(is)
Reimplemented from Convection_Diffusion_std.
References TRUST_List< _CLASSE_ >::add(), TRUST_List< _CLASSE_ >::est_vide(), Equation_base::les_sources, Equation_base::probleme(), Convection_Diffusion_std::readOn(), and Source::typer().
set_param()
void Transport_Flux_Chaleur_Turbulente::set_param (Param & titi) override virtual
Reimplemented from Convection_Diffusion_std.
References Convection_Diffusion_std::set_param().
lire_motcle_non_standard()
int Transport_Flux_Chaleur_Turbulente::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Convection_Diffusion_std.
References Convection_Diffusion_std::lire_motcle_non_standard(), and terme_diffusif.
associer_vitesse()
void Transport_Flux_Chaleur_Turbulente::associer_vitesse (const Champ_Inc_base & vit) inline
References la_vitesse_transportante.
Referenced by associer_modele_turbulence().
associer_milieu_base()
void Transport_Flux_Chaleur_Turbulente::associer_milieu_base (const Milieu_base & un_milieu) override virtual
Implements Equation_base.
References le_fluide.
Referenced by associer_modele_turbulence().
associer_modele_turbulence()
void Transport_Flux_Chaleur_Turbulente::associer_modele_turbulence (const Modele_turbulence_scal_Fluctuation_Temperature & modele)
References Equation_base::associer_domaine_dis(), associer_milieu_base(), Equation_base::associer_pb_base(), Equation_base::associer_sch_tps_base(), associer_vitesse(), discretiser(), Equation_base::domaine_dis(), Modele_turbulence_scal_base::equation(), Equation_base::inconnue(), Equation_base::milieu(), mon_modele_fluctu, Equation_base::probleme(), and Equation_base::schema_temps().
Referenced by Modele_turbulence_scal_Fluctuation_Temperature::lire_motcle_non_standard().
discretiser()
void Transport_Flux_Chaleur_Turbulente::discretiser () override virtual
Discretise l'equation.
Type le domaine_Cl_dis, la formatte, l'associe a l'equation. Type le solveur masse, lui associe le domaine discretisee et le domaine des conditions aux limites discretisees.
Reimplemented from Equation_base.
References Champs_compris_T< FIELD_TYPE >::ajoute_champ(), Equation_base::champs_compris_, Equation_base::discretisation(), Equation_base::discretiser(), Equation_base::domaine_dis(), Discret_Thermique::Flux_Chaleur_Turb(), le_Flux_Chaleur_Turbulente, Objet_U::que_suis_je(), and Equation_base::schema_temps().
Referenced by associer_modele_turbulence().
completer()
void Transport_Flux_Chaleur_Turbulente::completer () override virtual
Complete la construction (initialisation) des objets associes a l'equation.
Complete les sources, associe l'equation a l'inconnue complete les operateurs, complete les conditions aux limites discretisees. Voir les methodes Source_base::completer(), Operateur_base::completer() Domaine_Cl_dis_base::completer() Domaine_Cl_dis_base::completer(const Domaine_dis_base&)
Reimplemented from Equation_base.
References Champ_Inc_base::associer_eqn(), Domaine_Cl_dis_base::completer(), Operateur::completer(), Sources::completer(), inconnue(), Equation_base::le_dom_Cl_dis, Equation_base::les_sources, nombre_d_operateurs(), and operateur().
Referenced by Modele_turbulence_scal_Fluctuation_Temperature::completer().
milieu() [1/2]
const Milieu_base & Transport_Flux_Chaleur_Turbulente::milieu () const override virtual
Implements Equation_base.
References Process::exit(), le_fluide, TRUST_Ref< _CLASSE_ >::non_nul(), and TRUST_Ref< _CLASSE_ >::valeur().
milieu() [2/2]
Milieu_base & Transport_Flux_Chaleur_Turbulente::milieu () override virtual
Implements Equation_base.
References Process::exit(), le_fluide, TRUST_Ref< _CLASSE_ >::non_nul(), and TRUST_Ref< _CLASSE_ >::valeur().
modele_turbulence() [1/2]
const Modele_turbulence_scal_Fluctuation_Temperature & Transport_Flux_Chaleur_Turbulente::modele_turbulence () const inline
References mon_modele_fluctu, TRUST_Ref< _CLASSE_ >::non_nul(), and TRUST_Ref< _CLASSE_ >::valeur().
modele_turbulence() [2/2]
Modele_turbulence_scal_Fluctuation_Temperature & Transport_Flux_Chaleur_Turbulente::modele_turbulence () inline
References mon_modele_fluctu, TRUST_Ref< _CLASSE_ >::non_nul(), and TRUST_Ref< _CLASSE_ >::valeur().
nombre_d_operateurs()
int Transport_Flux_Chaleur_Turbulente::nombre_d_operateurs () const override virtual
surcharge de la methode d'Equation_base.
renvoie le nombre d'operateurs.
Reimplemented from Convection_Diffusion_std.
Referenced by completer(), and operateur().
operateur() [1/2]
const Operateur & Transport_Flux_Chaleur_Turbulente::operateur (int i) const override virtual
surcharge de la methode d'Equation_base.
renvoie le ieme operateur.
Reimplemented from Convection_Diffusion_std.
References Process::exit(), nombre_d_operateurs(), terme_convectif, and terme_diffusif.
Referenced by completer().
operateur() [2/2]
Operateur & Transport_Flux_Chaleur_Turbulente::operateur (int i) override virtual
surcharge de la methode d'Equation_base.
renvoie le ieme operateur.
Reimplemented from Convection_Diffusion_std.
References Process::exit(), nombre_d_operateurs(), terme_convectif, and terme_diffusif.
vitesse_transportante()
const Champ_Inc_base & Transport_Flux_Chaleur_Turbulente::vitesse_transportante () inline
inconnue() [1/2]
const Champ_Inc_base & Transport_Flux_Chaleur_Turbulente::inconnue () const inline override virtual
renvoie le champ inconnue.
Implements Convection_Diffusion_std.
References le_Flux_Chaleur_Turbulente.
Referenced by Source_Transport_Fluctuation_Temperature_VDF_Elem::ajouter(), completer(), and Modele_turbulence_scal_Fluctuation_Temperature::Flux_Chaleur_Turb().
inconnue() [2/2]
Champ_Inc_base & Transport_Flux_Chaleur_Turbulente::inconnue () inline override virtual
renvoie le champ inconnue.
Implements Convection_Diffusion_std.
References le_Flux_Chaleur_Turbulente.
domaine_application()
const Motcle & Transport_Flux_Chaleur_Turbulente::domaine_application () const override virtual
Renvoie "indetermine" Navier_Stokes_standard par exemple surcharge cette methode.
pour renvoyer "Hydraulique"
Returns
(Motcle&) le nom du domaine d'aplication
Reimplemented from Equation_base.
controler_grandeur()
int Transport_Flux_Chaleur_Turbulente::controler_grandeur ()
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), le_Flux_Chaleur_Turbulente, and Champ_Inc_base::valeurs().
Referenced by Modele_turbulence_scal_Fluctuation_Temperature::mettre_a_jour().
Member Data Documentation
info_obj
const Type_info Transport_Flux_Chaleur_Turbulente::info_obj static
le_Flux_Chaleur_Turbulente
TRUST_Deriv< Champ_Inc_base > Transport_Flux_Chaleur_Turbulente::le_Flux_Chaleur_Turbulente protected
Referenced by controler_grandeur(), discretiser(), and inconnue().
terme_diffusif
Op_Diff_Flux_Chaleur_Turb Transport_Flux_Chaleur_Turbulente::terme_diffusif protected
Referenced by lire_motcle_non_standard(), and operateur().
terme_convectif
Operateur_Conv Transport_Flux_Chaleur_Turbulente::terme_convectif protected
Referenced by operateur().
le_fluide
TRUST_Ref< Fluide_base *> Transport_Flux_Chaleur_Turbulente::le_fluide protected
Referenced by associer_milieu_base(), and milieu().
la_vitesse_transportante
TRUST_Ref< Champ_Inc_base *> Transport_Flux_Chaleur_Turbulente::la_vitesse_transportante protected
Referenced by associer_vitesse().
mon_modele_fluctu
TRUST_Ref< Modele_turbulence_scal_Fluctuation_Temperature *> Transport_Flux_Chaleur_Turbulente::mon_modele_fluctu protected
Referenced by associer_modele_turbulence(), and modele_turbulence().