TrioCFD: Discret_Thermique Class Reference
Discret_Thermique Class Reference
#include <Discret_Thermique.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Discretisation_base
virtual void discretiser_champ (const Motcle &directive, const Domaine_dis_base &z, Nature_du_champ nature, const Noms &nom, const Noms &unite, int nb_comp, int nb_pas_dt, double temps, TRUST_Deriv< Champ_Inc_base > &champ, const Nom &sous_type=NOM_VIDE) const
const Type_info * get_info () const override
virtual Nom get_name_of_type_for (const Nom &class_operateur, const Nom &type_operteur, const Equation_base &eqn, const TRUST_Ref< Champ_base * > &champ_supp=TRUST_Ref< Champ_base * >()) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Discretisation_base
static void creer_champ (TRUST_Deriv< Champ_Don_base > &ch, const Domaine_dis_base &z, const Nom &type, const Nom &nom, const Nom &unite, int nb_comp, int nb_ddl, double temps, const Nom &directive=NOM_VIDE, const Nom &nom_discretisation=NOM_VIDE)
static void creer_champ (TRUST_Deriv< Champ_Fonc_base > &ch, const Domaine_dis_base &z, const Nom &type, const Nom &nom, const Nom &unite, int nb_comp, int nb_ddl, double temps, const Nom &directive=NOM_VIDE, const Nom &nom_discretisation=NOM_VIDE)
static void creer_champ (TRUST_Deriv< Champ_Inc_base > &ch, const Domaine_dis_base &z, const Nom &type, const Nom &nom, const Nom &unite, int nb_comp, int nb_ddl, int nb_pas_dt, double temps, const Nom &directive=NOM_VIDE, const Nom &nom_discretisation=NOM_VIDE)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
spatiale appliquee aux problemes thermiques. Les methodes virtuelles pures sont a implementer dans les classes derivees pour typer et discretiser les champs portes par les equations liees a la discretisation.
See also
Discretisation_base, Classe abstraite, Methodes abstraites, void temperature(const Schema_Temps_base&, Domaine_dis_base&, Champ_Inc_base&) const, void proprietes_physiques_milieu(Domaine_dis_base& ,Milieu_base& ,const Champ_Inc_base&) const
Constructor & Destructor Documentation
Discret_Thermique()
Discret_Thermique::Discret_Thermique ()
~Discret_Thermique()
Discret_Thermique::~Discret_Thermique () override
Member Function Documentation
info()
const Type_info * Discret_Thermique::info () static
get_info()
const Type_info * Discret_Thermique::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Discretisation_base.
Reimplemented in VDF_discretisation, and VEF_discretisation.
self_cast() [1/2]
Discret_Thermique & Discret_Thermique::self_cast (Objet_U & r) static
self_cast() [2/2]
const Discret_Thermique & Discret_Thermique::self_cast (const Objet_U & r) static
printOn()
Sortie & Discret_Thermique::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Discretisation_base.
Reimplemented in VDF_discretisation, and VEF_discretisation.
readOn()
Entree & Discret_Thermique::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Discretisation_base.
Reimplemented in VDF_discretisation, and VEF_discretisation.
temperature()
void Discret_Thermique::temperature (const Schema_Temps_base & sch, Domaine_dis_base & z, TRUST_Deriv< Champ_Inc_base > & ch, int nb_comp = 1) const
References Discretisation_base::discretiser_champ(), Schema_Temps_base::nb_valeurs_temporelles(), and Schema_Temps_base::temps_courant().
Referenced by Equation_rayonnement_base::discretiser(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::discretiser(), Convection_Diffusion_Temperature::discretiser(), Energie_Multiphase::discretiser(), and Conduction::discretiser().
enthalpie()
void Discret_Thermique::enthalpie (const Schema_Temps_base & sch, Domaine_dis_base & z, TRUST_Deriv< Champ_Inc_base > & ch, int nb_comp = 1) const
References Discretisation_base::discretiser_champ(), Schema_Temps_base::nb_valeurs_temporelles(), and Schema_Temps_base::temps_courant().
Referenced by Energie_Multiphase_Enthalpie::discretiser().
flux_neutronique()
void Discret_Thermique::flux_neutronique (const Schema_Temps_base & sch, Domaine_dis_base & z, TRUST_Deriv< Champ_Inc_base > & ch, int nb_comp = 1) const
References Discretisation_base::discretiser_champ(), Schema_Temps_base::nb_valeurs_temporelles(), and Schema_Temps_base::temps_courant().
Fluctu_Temperature()
void Discret_Thermique::Fluctu_Temperature (const Schema_Temps_base & sch, Domaine_dis_base & z, TRUST_Deriv< Champ_Inc_base > & ch) const
References Discretisation_base::discretiser_champ(), Schema_Temps_base::nb_valeurs_temporelles(), Field_base::nommer(), and Schema_Temps_base::temps_courant().
Referenced by Transport_Fluctuation_Temperature::discretiser(), and Transport_Fluctuation_Temperature_W::discretiser().
Flux_Chaleur_Turb()
void Discret_Thermique::Flux_Chaleur_Turb (const Schema_Temps_base & sch, Domaine_dis_base & z, TRUST_Deriv< Champ_Inc_base > & ch) const
References Objet_U::dimension, Discretisation_base::discretiser_champ(), Schema_Temps_base::nb_valeurs_temporelles(), and Schema_Temps_base::temps_courant().
Referenced by Transport_Flux_Chaleur_Turbulente::discretiser().
t_paroi()
virtual void Discret_Thermique::t_paroi (const Domaine_dis_base & z, const Domaine_Cl_dis_base & zcl, const Champ_Inc_base & , TRUST_Deriv< Champ_Fonc_base > & ch) const inline virtual
Reimplemented in VDF_discretisation, and VEF_discretisation.
References Process::exit(), and Objet_U::que_suis_je().
Referenced by Convection_Diffusion_Temperature_base::creer_champ(), and Conduction::creer_champ().
Member Data Documentation
info_obj
const Type_info Discret_Thermique::info_obj static