TrioCFD: Fluide_Diphasique_IJK Class Reference
Fluide_Diphasique_IJK Class Reference
#include <Fluide_Diphasique_IJK.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Fluide_Diphasique
const Champ_Don_base & beta_t () const override
Champ_Don_base & beta_t () override
const Champ_Don_base & capacite_calorifique () const override
Champ_Don_base & capacite_calorifique () override
const Champ_Don_base & conductivite () const override
Champ_Don_base & conductivite () override
const Champ_Don_base & diffusivite () const override
Champ_Don_base & diffusivite () override
const Type_info * get_info () const override
const Champ_base & masse_volumique () const override
Champ_base & masse_volumique () override
Public Member Functions inherited from Milieu_base
virtual int a_gravite () const
int associer_ (Objet_U &) override
virtual void associer_gravite (const Champ_Don_base &)
virtual Champ_Don_base & beta_t ()
virtual const Champ_Don_base & beta_t () const
virtual Champ_Don_base & capacite_calorifique ()
virtual const Champ_Don_base & capacite_calorifique () const
virtual Champ_Don_base & conductivite ()
virtual const Champ_Don_base & conductivite () const
virtual Champ_Don_base & diffusivite ()
virtual const Champ_Don_base & diffusivite () const
virtual int est_deja_associe ()
const Type_info * get_info () const override
virtual Champ_Don_base & gravite ()
virtual const Champ_Don_base & gravite () const
const Nom & le_nom () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual Champ_base & masse_volumique ()
virtual const Champ_base & masse_volumique () const
void nommer (const Nom &) override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Fluide_Diphasique
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Milieu_base
virtual void calculer_alpha ()
void ecrire (Sortie &) const
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Fluide_Diphasique_IJK()
Fluide_Diphasique_IJK::Fluide_Diphasique_IJK ()
~Fluide_Diphasique_IJK()
Fluide_Diphasique_IJK::~Fluide_Diphasique_IJK ()
Member Function Documentation
cree_instance()
Objet_U * Fluide_Diphasique_IJK::cree_instance () static
taille_memoire()
unsigned Fluide_Diphasique_IJK::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Fluide_Diphasique_IJK::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Fluide_Diphasique_IJK::info () static
get_info()
const Type_info * Fluide_Diphasique_IJK::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Milieu_base.
self_cast() [1/2]
Fluide_Diphasique_IJK & Fluide_Diphasique_IJK::self_cast (Objet_U & r) static
self_cast() [2/2]
const Fluide_Diphasique_IJK & Fluide_Diphasique_IJK::self_cast (const Objet_U & r) static
printOn()
Sortie & Fluide_Diphasique_IJK::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Milieu_base.
readOn()
Entree & Fluide_Diphasique_IJK::readOn (Entree & is) override protected virtual
Lecture d'un milieu sur un flot d'entree.
Format: { grandeur_physique type_champ bloc de lecture du champ } cf set_param method to know the understood keywords cf Param class to know possible options reading
Parameters
(Entree& is) le flot d'entree pour la lecture des parametres du milieu
Returns
(Entree&) le flot d'entree modifie
Exceptions
accolade ouvrante attendue
Reimplemented from Milieu_base.
References Fluide_Diphasique::readOn().
get_mu_liquid()
double Fluide_Diphasique_IJK::get_mu_liquid () const inline
References Fluide_Diphasique::phase1_, and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by Navier_Stokes_FTD_IJK::calculer_terme_source_acceleration(), Navier_Stokes_FTD_IJK::compute_correction_for_momentum_balance(), Schema_Temps_IJK_base::find_timestep(), Navier_Stokes_FTD_IJK::initialise_ns_fields(), Navier_Stokes_FTD_IJK::maj_indicatrice_rho_mu(), and Navier_Stokes_FTD_IJK::preparer_calcul().
get_mu_vapour()
double Fluide_Diphasique_IJK::get_mu_vapour () const inline
References Fluide_Diphasique::phase0_, and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by Schema_Temps_IJK_base::find_timestep(), Navier_Stokes_FTD_IJK::initialise_ns_fields(), and Navier_Stokes_FTD_IJK::maj_indicatrice_rho_mu().
get_delta_rho()
double Fluide_Diphasique_IJK::get_delta_rho () const inline
References Fluide_Diphasique::phase0_, Fluide_Diphasique::phase1_, and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by Navier_Stokes_FTD_IJK::calculer_terme_asservissement(), Navier_Stokes_FTD_IJK::projeter(), Probleme_FTD_IJK_base::sauver(), and Probleme_FTD_IJK_base::update_indicator_field().
get_rho_liquid()
double Fluide_Diphasique_IJK::get_rho_liquid () const inline
References Fluide_Diphasique::phase1_, and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by Navier_Stokes_FTD_IJK::calculer_dv(), Navier_Stokes_FTD_IJK::calculer_terme_asservissement(), Navier_Stokes_FTD_IJK::calculer_terme_source_acceleration(), Navier_Stokes_FTD_IJK::compute_and_add_qdm_corrections_monophasic(), Navier_Stokes_FTD_IJK::compute_correction_for_momentum_balance(), Schema_Temps_IJK_base::find_timestep(), Navier_Stokes_FTD_IJK::initialise_ijk_fields(), Navier_Stokes_FTD_IJK::initialise_ns_fields(), Navier_Stokes_FTD_IJK::maj_indicatrice_rho_mu(), and Navier_Stokes_FTD_IJK::preparer_calcul().
get_rho_vapour()
double Fluide_Diphasique_IJK::get_rho_vapour () const inline
References Fluide_Diphasique::phase0_, and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by Navier_Stokes_FTD_IJK::calculer_terme_source_acceleration(), Navier_Stokes_FTD_IJK::compute_correction_for_momentum_balance(), Schema_Temps_IJK_base::find_timestep(), Navier_Stokes_FTD_IJK::initialise_ijk_fields(), Navier_Stokes_FTD_IJK::initialise_ns_fields(), Navier_Stokes_FTD_IJK::maj_indicatrice_rho_mu(), and Navier_Stokes_FTD_IJK::preparer_calcul().
get_cp_liquid()
double Fluide_Diphasique_IJK::get_cp_liquid (int i) const inline
References Fluide_Diphasique::phase1_, and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by IJK_Thermal_base::associer_milieu_base().
get_cp_vapour()
double Fluide_Diphasique_IJK::get_cp_vapour (int i) const inline
References Fluide_Diphasique::phase0_, and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by IJK_Thermal_base::associer_milieu_base().
get_set_cp_vapour()
double & Fluide_Diphasique_IJK::get_set_cp_vapour (int i) inline
References Fluide_Diphasique::phase0_, and TRUST_Deriv< _CLASSE_ >::valeur().
get_lambda_liquid()
double Fluide_Diphasique_IJK::get_lambda_liquid (int i) const inline
References Fluide_Diphasique::phase1_, and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by IJK_Thermal_base::associer_milieu_base().
get_lambda_vapour()
double Fluide_Diphasique_IJK::get_lambda_vapour (int i) const inline
References Fluide_Diphasique::phase0_, and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by IJK_Thermal_base::associer_milieu_base().
get_set_lambda_vapour()
double & Fluide_Diphasique_IJK::get_set_lambda_vapour (int i) inline
References Fluide_Diphasique::phase0_, and TRUST_Deriv< _CLASSE_ >::valeur().
get_gravite_norm()
double Fluide_Diphasique_IJK::get_gravite_norm () const
References Milieu_base::a_gravite(), Milieu_base::gravite(), Vecteur3::length(), and Champ_Don_base::valeurs().
Referenced by Navier_Stokes_FTD_IJK::initialise_ijk_fields().
get_direction_gravite()
int Fluide_Diphasique_IJK::get_direction_gravite () const inline
References direction_gravite_.
Referenced by Navier_Stokes_FTD_IJK::calculer_terme_asservissement(), Navier_Stokes_FTD_IJK::calculer_terme_source_acceleration(), Navier_Stokes_FTD_IJK::compute_correction_for_momentum_balance(), and Navier_Stokes_FTD_IJK::euler_time_step().
calculate_direction_gravite()
void Fluide_Diphasique_IJK::calculate_direction_gravite ()
References direction_gravite_, Process::exit(), and Milieu_base::gravite().
Referenced by Probleme_FTD_IJK_base::completer().
Member Data Documentation
info_obj
const Type_info Fluide_Diphasique_IJK::info_obj static
direction_gravite_
int Fluide_Diphasique_IJK::direction_gravite_ = 0 protected
Referenced by calculate_direction_gravite(), and get_direction_gravite().