TrioCFD: Milieu_MUSIG Class Reference
Milieu_MUSIG Class Reference
#include <Milieu_MUSIG.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Milieu_composite
const Type_info * get_info () const override
void mettre_a_jour (double temps) override
Public Member Functions inherited from Fluide_base
const Type_info * get_info () const override
void mettre_a_jour (double) override
void verifier_coherence_champs (int &err, Nom &message) override
Public Member Functions inherited from Milieu_base
virtual int a_gravite () const
int associer_ (Objet_U &) override
virtual void associer_gravite (const Champ_Don_base &)
virtual Champ_Don_base & beta_t ()
virtual const Champ_Don_base & beta_t () const
virtual Champ_Don_base & capacite_calorifique ()
virtual const Champ_Don_base & capacite_calorifique () const
virtual Champ_Don_base & conductivite ()
virtual const Champ_Don_base & conductivite () const
virtual Champ_Don_base & diffusivite ()
virtual const Champ_Don_base & diffusivite () const
virtual int est_deja_associe ()
const Type_info * get_info () const override
virtual Champ_Don_base & gravite ()
virtual const Champ_Don_base & gravite () const
const Nom & le_nom () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual Champ_base & masse_volumique ()
virtual const Champ_base & masse_volumique () const
void nommer (const Nom &) override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Fluide_base
void creer_nu ()
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Milieu_base
virtual void calculer_alpha ()
void ecrire (Sortie &) const
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Milieu_MUSIG()
Milieu_MUSIG::Milieu_MUSIG ()
~Milieu_MUSIG()
Milieu_MUSIG::~Milieu_MUSIG ()
Member Function Documentation
cree_instance()
Objet_U * Milieu_MUSIG::cree_instance () static
taille_memoire()
unsigned Milieu_MUSIG::taille_memoire () const override virtual
Reimplemented from Milieu_composite.
duplique()
int Milieu_MUSIG::duplique () const override virtual
Reimplemented from Milieu_composite.
info()
const Type_info * Milieu_MUSIG::info () static
get_info()
const Type_info * Milieu_MUSIG::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Milieu_composite.
self_cast() [1/2]
Milieu_MUSIG & Milieu_MUSIG::self_cast (Objet_U & r) static
self_cast() [2/2]
const Milieu_MUSIG & Milieu_MUSIG::self_cast (const Objet_U & r) static
printOn()
Sortie & Milieu_MUSIG::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Milieu_composite.
References Objet_U::printOn().
readOn()
Entree & Milieu_MUSIG::readOn (Entree & is) override protected virtual
Lit les caracteristiques du fluide a partir d'un flot d'entree.
Format: Fluide_base { Mu type_champ bloc de lecture de champ Rho Champ_Uniforme 1 vrel [Cp Champ_Uniforme 1 vrel] [Lambda type_champ bloc de lecture de champ] [Beta_th type_champ bloc de lecture de champ] [Beta_co type_champ bloc de lecture de champ] } cf Milieu_base::readOn
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Exceptions
accolade ouvrante attendue
Reimplemented from Milieu_composite.
References TRUST_Vector< _CLASSE_ >::add(), Milieu_base::ch_diametre_hyd_, Milieu_base::ch_porosites_, Milieu_composite::check_fluid_name(), Nom::debute_par(), Process::exit(), Milieu_composite::fluides_, Fluide_MUSIG::get_Fluide(), Fluide_MUSIG::get_NbSubPhase(), Saturation_base::get_Pref(), Milieu_composite::has_interface(), Milieu_composite::has_interface_, Milieu_composite::has_saturation(), Milieu_composite::has_saturation_, Saturation_base::Hls(), Saturation_base::Hvs(), Milieu_composite::inter_lu_, Objet_U::nommer(), Milieu_composite::noms_phases_, Objet_U::que_suis_je(), Milieu_composite::sat_lu_, Milieu_composite::tab_interface_, Saturation_base::Tsat(), TRUST_Deriv< _CLASSE_ >::typer_lire_simple(), and TRUST_Deriv< _CLASSE_ >::valeur().
get_Diameter_Inf()
double Milieu_MUSIG::get_Diameter_Inf (int iPhaseMilieu) const
References Process::exit(), Fluide_MUSIG::get_Diametres(), Objet_U::que_suis_je(), and TRUSTVect< _TYPE_, _SIZE_ >::size().
Referenced by get_Diameter_Sauter(), and Diametre_bulles_musig::readOn().
get_Diameter_Sup()
double Milieu_MUSIG::get_Diameter_Sup (int iPhaseMilieu) const
References Process::exit(), Fluide_MUSIG::get_Diametres(), Objet_U::que_suis_je(), and TRUSTVect< _TYPE_, _SIZE_ >::size().
Referenced by get_Diameter_Sauter(), and Diametre_bulles_musig::readOn().
get_Diameter_Sauter()
double Milieu_MUSIG::get_Diameter_Sauter (int iPhaseMilieu) const
References Process::exit(), get_Diameter_Inf(), get_Diameter_Sup(), and Objet_U::que_suis_je().
Referenced by Diametre_bulles_musig::readOn().
has_dispersed_gas()
bool Milieu_MUSIG::has_dispersed_gas (int k) const
References Milieu_composite::fluides_, and Milieu_base::le_nom().
Referenced by Diametre_bulles_musig::readOn().
has_carrier_liquid()
bool Milieu_MUSIG::has_carrier_liquid (int k) const
References Milieu_composite::fluides_, and Milieu_base::le_nom().
Referenced by Frottement_interfacial_bulles_constant::readOn().
has_dispersed_liquid()
bool Milieu_MUSIG::has_dispersed_liquid (int k) const
References Milieu_composite::fluides_, and Milieu_base::le_nom().
Referenced by Diametre_bulles_musig::readOn().
has_carrier_gas()
bool Milieu_MUSIG::has_carrier_gas (int k) const
References Milieu_composite::fluides_, and Milieu_base::le_nom().
Referenced by Frottement_interfacial_bulles_constant::readOn().
Member Data Documentation
info_obj
const Type_info Milieu_MUSIG::info_obj static