TrioCFD: TRUST_Ref< _CLASSE_ > Class Template Reference
TRUST_Ref< _CLASSE_ > Class Template Reference
#include <TRUST_Ref.h>
Constructor & Destructor Documentation
~TRUST_Ref()
template<typename _CLASSE_ > TRUST_Ref< _CLASSE_ >::~TRUST_Ref () default
TRUST_Ref() [1/3]
template<typename _CLASSE_ > TRUST_Ref< _CLASSE_ >::TRUST_Ref () default
TRUST_Ref() [2/3]
template<typename _CLASSE_ > TRUST_Ref< _CLASSE_ >::TRUST_Ref (const value_type & t) inline
TRUST_Ref() [3/3]
template<typename _CLASSE_ > TRUST_Ref< _CLASSE_ >::TRUST_Ref (const TRUST_Ref< _CLASSE_ > & t) inline
Member Function Documentation
operator=() [1/2]
template<typename _CLASSE_ > const TRUST_Ref & TRUST_Ref< _CLASSE_ >::operator= (const value_type & t) inline
operator=() [2/2]
template<typename _CLASSE_ > const TRUST_Ref & TRUST_Ref< _CLASSE_ >::operator= (const TRUST_Ref< _CLASSE_ > & t) inline
operator const value_type &()
template<typename _CLASSE_ > TRUST_Ref< _CLASSE_ >::operator const value_type & () const inline
References TRUST_Ref< _CLASSE_ >::valeur().
operator value_type &()
template<typename _CLASSE_ > TRUST_Ref< _CLASSE_ >::operator value_type & () inline
References TRUST_Ref< _CLASSE_ >::valeur().
valeur() [1/2]
template<typename _CLASSE_ > const value_type & TRUST_Ref< _CLASSE_ >::valeur () const inline
Referenced by Operateur_Conv_sensibility_VEF::add_diffusion_scalar_term(), Operateur_Conv_sensibility_VEF::add_diffusion_term(), Champ_Face_PolyMAC::affecter_(), Champ_Fonc_Face_PolyMAC::affecter_(), Champ_Elem_DG::affecter_(), Champ_Fonc_Elem_DG::affecter_(), Champ_Fonc_P1_DG::affecter_(), Champ_Elem_PolyMAC::affecter_(), Champ_Fonc_Elem_PolyMAC::affecter_(), Operateur_Conv_sensibility_VEF::ajouter(), Op_Diff_K_Eps_QC_VEF_Face::ajouter(), Op_Diff_K_Omega_VEF_Face::ajouter(), Op_Diff_EF::ajouter(), Op_Dift_EF_Q1::ajouter(), Op_Diff_PolyMAC_Elem::ajouter(), Op_Div_PolyMAC::ajouter(), Op_Div_PolyMAC_P0::ajouter(), Op_Grad_PolyMAC_Face::ajouter(), Op_Conv_Amont_old_VEF_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Centre_EF_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_EF_VEF_P1NC::ajouter(), Op_Conv_EF_VEF_P1NC_Stab::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_Muscl_New_VEF_Face::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Conv_Vort_VEF_Face::ajouter(), Op_Diff_VEF_Anisotrope_Face::ajouter(), Op_Diff_VEF_Face::ajouter(), Op_Diff_VEF_Face_Q1::ajouter(), Op_Diff_VEF_Face_Stab::ajouter(), Op_Curl_VEFP1B::ajouter(), Op_Div_VEFP1B_Elem::ajouter(), Op_Grad_P1NC_to_P0::ajouter(), Op_Grad_VEF_P1B_Face::ajouter(), Op_Rot_VEFP1B::ajouter(), Op_Conv_EF_Stab_PolyMAC_Face::ajouter(), Op_Diff_PolyMAC_Face::ajouter(), Op_Conv_RT_VEF_Face::ajouter(), SourceFiltree_FT_disc_VEF_P1NC::ajouter(), Terme_Boussinesq_Sensibility_VEFPreP1B_Face::ajouter(), Source_Transport_Fluctuation_Temperature_VDF_Elem::ajouter(), Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::ajouter(), Source_Transport_Fluctuation_Temperature_W_VDF_Elem::ajouter(), Source_Transport_Flux_Chaleur_Turbulente_VDF_Face::ajouter(), Source_Transport_K_Realisable_VEF_Face::ajouter(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_VEF_Face::ajouter(), Source_Transport_K_Eps_Bas_Reynolds_VEF_Face::ajouter(), Source_Robin::ajouter(), Source_Robin_Scalaire::ajouter(), Source_Qdm_EF::ajouter(), Source_Scalaire_EF::ajouter(), Perte_Charge_Singuliere_PolyMAC_Face::ajouter(), Source_Generique_Face_PolyMAC::ajouter(), Source_Generique_Face_PolyMAC_P0P1NC::ajouter(), Terme_Source_Qdm_Face_PolyMAC::ajouter(), Terme_Source_Canal_perio_VEF_P1NC::ajouter(), Terme_Source_Canal_RANS_LES_VEF_Face::ajouter(), Source_QC_Gravite_VEF::ajouter(), Source_WC_Gravite_VEF::ajouter(), Perte_Charge_Singuliere_VEF_Face::ajouter(), Perte_Charge_VEF::ajouter(), Terme_Boussinesq_VEF_Face::ajouter(), Terme_Boussinesq_VEFPreP1B_Face::ajouter(), Terme_Puissance_Thermique_Echange_Impose_VEF_Face::ajouter(), Terme_Source_Acceleration_VEF_Face::ajouter(), Terme_Source_Decroissance_Radioactive_VEF_Face::ajouter(), Terme_Source_Qdm_lambdaup_VEF_Face::ajouter(), Terme_Source_Qdm_VEF_Face::ajouter(), Terme_Source_Rappel_T_VEF_Face::ajouter(), Terme_Source_Th_TdivU_VEF_Face::ajouter(), Perte_Charge_Reguliere_VDF_Face::ajouter_(), Source_PDF_EF::ajouter_(), Source_QC_Chaleur::ajouter_(), Source_WC_Chaleur::ajouter_(), Source_Transport_VDF_Elem_base::ajouter_anisotherme(), Source_Transport_VEF_Face_base::ajouter_anisotherme(), Source_Transport_VDF_Elem_base::ajouter_anisotherme_concen(), Source_Transport_VEF_Face_base::ajouter_anisotherme_concen(), Op_Diff_VEF_Face_Stab::ajouter_antidiffusion(), Op_Div_VEFP1B_Elem::ajouter_aretes(), Op_Grad_VEF_P1B_Face::ajouter_aretes(), Tenseur_Reynolds_Externe_VDF_Face::ajouter_blocs(), Source_Transport_Bas_Reynolds_VDF_Elem_base::ajouter_blocs(), Source_Transport_K_Realisable_VDF_Elem::ajouter_blocs(), Source_Transport_K_Eps_Bas_Reynolds_aniso_therm_concen_VDF_Elem::ajouter_blocs(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_VDF_Elem::ajouter_blocs(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_W_VDF_Elem::ajouter_blocs(), Source_Transport_K_KEps_VDF_Elem::ajouter_blocs(), Op_Grad_P0_to_Face::ajouter_blocs(), Op_Grad_VDF_Face::ajouter_blocs(), Terme_Source_Canal_perio_VDF_Face::ajouter_blocs(), Terme_Source_Canal_perio_VDF_P0::ajouter_blocs(), Terme_Source_Canal_RANS_LES_VDF_Elem::ajouter_blocs(), Terme_Source_Canal_RANS_LES_VDF_Face::ajouter_blocs(), Source_QC_Gravite_VDF::ajouter_blocs(), Source_WC_Gravite_VDF::ajouter_blocs(), Force_Centrifuge_VDF_Face_Axi::ajouter_blocs(), Perte_Charge_Singuliere_VDF_Face::ajouter_blocs(), Terme_Boussinesq_VDF_Face::ajouter_blocs(), Terme_Source_Acceleration_VDF_Face::ajouter_blocs(), Terme_Source_Coriolis_VDF_Face::ajouter_blocs(), Terme_Source_inc_th_VDF_Face::ajouter_blocs(), Terme_Source_inc_VDF_Face::ajouter_blocs(), Terme_Source_Qdm_VDF_Face::ajouter_blocs(), Terme_Source_Solide_SWIFT_VDF::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_P0_Face::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Face::ajouter_blocs(), Op_Diff_PolyMAC_P0_Face::ajouter_blocs(), Op_Grad_PolyMAC_P0_Face::ajouter_blocs(), Op_Grad_PolyMAC_P0P1NC_Face::ajouter_blocs(), Couplage_Parietal_PolyMAC_helper::ajouter_blocs(), Nucleation_paroi_PolyMAC_P0::ajouter_blocs(), Op_Diff_DG_Elem::ajouter_blocs(), Dispersion_bulles_PolyMAC_P0::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::ajouter_blocs(), Terme_Boussinesq_PolyMAC_Face::ajouter_blocs(), Terme_Puissance_Thermique_Echange_Impose_Elem_base::ajouter_blocs(), Source_Flux_interfacial_base::ajouter_blocs(), Dispersion_bulles_VDF::ajouter_blocs(), Masse_PolyMAC_P0_Face::ajouter_blocs(), Correction_Lubchenko_PolyMAC_P0::ajouter_blocs_disp(), Op_Div_PolyMAC_P0P1NC::ajouter_blocs_ext(), Op_Diff_PolyMAC_P0P1NC_Elem::ajouter_blocs_ext(), Op_Diff_PolyMAC_P0P1NC_Face::ajouter_blocs_ext(), Correction_Lubchenko_PolyMAC_P0::ajouter_blocs_lift(), Solveur_Masse_Face_proto::ajouter_blocs_proto(), Solveur_Masse_Elem_proto::ajouter_blocs_proto(), Op_Diff_EF::ajouter_bords(), Op_Dift_EF_Q1::ajouter_bords(), Source_Transport_VDF_Elem_base::ajouter_concen(), Source_Transport_VEF_Face_base::ajouter_concen(), Op_Diff_EF::ajouter_contribution(), Op_Dift_EF_Q1::ajouter_contribution(), Op_Conv_Amont_old_VEF_Face::ajouter_contribution(), Op_Conv_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution(), Op_Diff_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Face_Q1::ajouter_contribution(), Op_Diff_VEF_Face_Stab::ajouter_contribution(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution(), Op_Conv_RT_VEF_Face::ajouter_contribution(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution_elem(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face_Stab::ajouter_contribution_multi_scalaire(), Op_Diff_EF::ajouter_contribution_new(), Op_Dift_EF_Q1::ajouter_contribution_new(), Transport_Interfaces_FT_Disc::ajouter_contribution_saut_vitesse(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution_som(), Op_Conv_EF::ajouter_contribution_sous_cond(), Op_Diff_EF::ajouter_contributions_bords(), Op_Dift_EF_Q1::ajouter_contributions_bords(), Operateur_Conv_sensibility_VEF::ajouter_conv_term(), Op_Diff_VEF_Face_Stab::ajouter_diffusion(), Op_Div_VEFP1B_Elem::ajouter_elem(), Op_Grad_VEF_P1B_Face::ajouter_elem(), Source_Masse_Fluide_Dilatable_VEF::ajouter_eq_espece(), Source_Transport_VDF_Elem_base::ajouter_keps(), Source_Transport_VEF_Face_base::ajouter_keps(), Source_Transport_K_Omega_VDF_Elem_base::ajouter_komega(), Source_Transport_K_Omega_VEF_Face_base::ajouter_komega(), Operateur_Conv_sensibility_VEF::ajouter_Lsensibility_state_Amont(), Operateur_Conv_sensibility_VEF::ajouter_Lstate_sensibility_Amont(), Masse_PolyMAC_Elem::ajouter_masse(), Op_Diff_EF::ajouter_new(), Op_Dift_EF_Q1::ajouter_new(), Op_Diff_VEF_Face_Stab::ajouter_operateur_centre(), Source_Masse_Fluide_Dilatable_VDF::ajouter_projection(), Source_Masse_Fluide_Dilatable_VEF::ajouter_projection(), Op_Grad_VEF_P1B_Face::ajouter_som(), Op_Div_VEFP1B_Elem::ajouter_som(), IJK_Interfaces::ajouter_terme_source_interfaces(), Op_Diff_PolyMAC_Elem::ajouter_termes_croises(), Op_Conv_ALE_VEF::ajouterALE(), Solveur_Masse_EF::appliquer_impl(), Masse_PolyMAC_Elem::appliquer_impl(), Masse_PolyMAC_Face::appliquer_impl(), Masse_PolyMAC_P0_Face::appliquer_impl(), Masse_PolyMAC_P0P1NC_Face::appliquer_impl(), Masse_VDF_Elem::appliquer_impl(), Masse_VDF_Face::appliquer_impl(), Masse_VEF_P1NC::appliquer_impl(), Solveur_Masse_Elem_proto::appliquer_impl_proto(), Solveur_Masse_Face_proto::appliquer_impl_proto(), Assembleur_P_EF::assembler(), Assembleur_P_VDF::assembler(), Assembleur_P_PolyMAC_P0P1NC::assembler_continuite(), Equation_IBM_proto::assembler_ibm_proto(), Assembleur_P_EF::assembler_mat(), Assembleur_P_PolyMAC::assembler_mat(), Assembleur_P_PolyMAC_P0::assembler_mat(), Assembleur_P_PolyMAC_P0P1NC::assembler_mat(), Assembleur_P_VEFPreP1B::assembler_mat(), Assembleur_P_VEF::assembler_mat(), Source_Con_Phase_field::assembler_matrice_point_fixe(), Assembleur_P_VDF::assembler_QC(), Assembleur_P_EF::assembler_rho_variable(), Assembleur_P_VDF::assembler_rho_variable(), Eval_Darcy_VDF_Face::associer(), Eval_Darcy_VEF_Face::associer(), Op_Diff_EF_base::associer(), Op_Diff_VEF_base::associer(), Modele_turbulence_hyd_LES_DSGS_VDF::associer(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::associer(), Op_Conv_VDF_base::associer_champ_convecte_elem(), Op_Conv_VDF_base::associer_champ_convecte_face(), Op_Diff_K_Omega_VDF_base::associer_diffusivite_turbulente(), Op_Diff_K_Eps_Bas_Re_VDF_base::associer_diffusivite_turbulente_impl(), Champ_Elem_DG::associer_domaine_dis_base(), Champ_front_contact_VEF::associer_front_vf_et_ch_front_autre_pb(), Transport_K_Eps::associer_modele_turbulence(), Transport_K_Eps_Bas_Reynolds::associer_modele_turbulence(), Transport_K_Eps_Realisable::associer_modele_turbulence(), Transport_K_KEps::associer_modele_turbulence(), Transport_K_Omega::associer_modele_turbulence(), Transport_K_ou_Eps::associer_modele_turbulence(), Transport_K_ou_Eps_Realisable::associer_modele_turbulence(), Source_PDF_EF::associer_pb(), IJK_Interfaces::associer_pb_base(), Op_Dift_Multiphase_proto::associer_proto(), Eval_Puiss_Neutr_VDF_Elem::associer_repartition(), Pb_Hydraulique_ALE::associer_sch_tps_base(), Pb_Hydraulique_Turbulent_ALE::associer_sch_tps_base(), Schema_Comm::begin_comm(), Terme_Boussinesq_base::beta(), Terme_Source_inc_th_VDF_Face::beta(), Champ_Elem_DG::build_mass_matrix(), Champ_Elem_DG::build_transition_matrix(), Probleme_FTD_IJK_base::build_vdf_domaine(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calc_elem_elem(), Modele_turbulence_scal_LES_dyn_VDF::calc_elem_elem(), Champ_Elem_PolyMAC_P0::calc_grad(), Maillage_FT_Disc::calcul_courbure_sommets(), Parcours_interface::calcul_eq_plan(), Champ_front_contact_VEF::calcul_grads_locaux(), Maillage_FT_Disc::calcul_indicatrice(), Transport_Interfaces_FT_Disc::calcul_indicatrice_faces(), Champ_front_recyclage::calcul_moyenne_imposee(), Champ_front_recyclage::calcul_moyenne_recyclee(), Traitement_particulier_NS_THI_VEF::calcul_nu_t(), Traitement_particulier_NS_canal::calcul_reynolds_tau(), Tenseur_Reynolds_Externe_VDF_Face::Calcul_RSLambda(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calcul_tableaux_correspondance(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calcul_voisins(), Modele_turbulence_scal_LES_dyn_VDF::calcul_voisins(), Champ_Q1_EF::calcul_y_plus(), Milieu_base::calculate_face_hydr_diam(), Milieu_base::calculate_face_porosity(), Op_Conv_ALE_VEF::calculateALEjacobian(), Op_Conv_ALE_VEF::calculateALEMeshVelocityGradientOnFaces(), Op_Diff_P1NC_barprim::calculer(), Diffu_k::calculer_a_local(), Diffu_lm::calculer_a_local(), Diffu_scal_lm::calculer_a_local(), Source_Con_Phase_field::calculer_alpha_gradC_carre(), Op_Dift_EF_base::calculer_borne_locale(), Modele_turbulence_hyd_LES_DSGS_VDF::calculer_cell_cent_vel(), Source_Con_Phase_field::calculer_champ_fonc_c(), Op_Diff_VEF_Face_Stab::calculer_coefficients(), Loi_Etat_TPPI_WC_base::calculer_Cp(), Diffu_lm::calculer_D_local(), Terme_Source_Canal_perio_VDF_Face::calculer_debit(), Terme_Source_Canal_perio_VEF_P1NC::calculer_debit(), Modele_turbulence_scal_LES_dyn_VDF::calculer_diffusivite_turbulente(), Source_Con_Phase_field::calculer_div_alpha_rho_gradC(), Op_Diff_P1NC_barprim::calculer_divergence(), Op_Diff_VEFP1NCP1B_Face::calculer_divergence_som(), Op_Conv_VEF_base::calculer_dt_local(), Op_Conv_ALE_VEF::calculer_dt_stab(), Operateur_Conv_sensibility_VEF::calculer_dt_stab(), Op_Diff_DG_base::calculer_dt_stab(), Op_Conv_EF::calculer_dt_stab(), Op_Diff_EF_base::calculer_dt_stab(), Op_Dift_EF_Q1::calculer_dt_stab(), Op_Conv_EF_Stab_PolyMAC_P0_Face::calculer_dt_stab(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::calculer_dt_stab(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Face::calculer_dt_stab(), Op_Diff_PolyMAC_base::calculer_dt_stab(), Op_Diff_PolyMAC_P0_Elem::calculer_dt_stab(), Op_Diff_PolyMAC_P0_Face::calculer_dt_stab(), Op_Diff_PolyMAC_P0P1NC_Elem::calculer_dt_stab(), Op_Diff_PolyMAC_P0P1NC_Face::calculer_dt_stab(), Op_Diff_VDF_Face_Axi_base::calculer_dt_stab(), Op_Dift_VDF_Face_Axi_base::calculer_dt_stab(), Op_Conv_Muscl_New_VEF_Face::calculer_dt_stab(), Op_Conv_VEF_base::calculer_dt_stab(), Op_Diff_P1NC_barprim::calculer_dt_stab(), Op_Diff_VEF_base::calculer_dt_stab(), Op_Diff_VEF_Face_Q1::calculer_dt_stab(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab_elem(), Modele_turbulence_hyd_LES_VDF::calculer_energie_cinetique_turb(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calculer_energie_cinetique_turb(), Modele_turbulence_hyd_Longueur_Melange_VEF::calculer_f_amortissement(), Modele_turbulence_scal_LES_dyn_VDF::calculer_filter_coeff(), Modele_turbulence_hyd_LES_DSGS_VDF::calculer_filter_coeff(), Modele_turbulence_hyd_LES_DSGS_VDF::calculer_filter_field(), Modele_turbulence_hyd_LES_DSGS_VDF::calculer_filter_tensor(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calculer_filter_tensor(), Op_Grad_EF::calculer_flux_bords(), Op_Grad_VDF_Face::calculer_flux_bords(), Op_Diff_VEFP1NCP1B_Face::calculer_flux_bords_elem(), Op_Diff_VEFP1NCP1B_Face::calculer_flux_bords_som(), Modele_turbulence_hyd_LES_VDF::calculer_fonction_structure(), Modele_turbulence_hyd_LES_1elt_VEF::calculer_fonction_structure(), Modele_turbulence_hyd_LES_VEF::calculer_fonction_structure(), Modele_turbulence_hyd_LES_axi_VDF::calculer_fonction_structure(), Terme_Source_Coriolis_VDF_Face::calculer_force_de_Coriolis(), EDO_Pression_th_VDF::calculer_grad(), EDO_Pression_th_VEF::calculer_grad(), Convection_Diffusion_Temperature_FT_Disc::calculer_grad_t(), Op_Diff_VEFP1NCP1B_Face::calculer_gradient_som(), Op_Diff_VEF_Face_Stab::calculer_gradients(), LoiParoiHybride_VDF::calculer_hyd(), ParoiVDF_TBLE_LRM::calculer_hyd(), LoiParoiHybride_VEF::calculer_hyd(), Paroi_std_hyd_VEF::calculer_hyd(), Paroi_negligeable_VDF::calculer_hyd(), Paroi_negligeable_VEF::calculer_hyd(), Paroi_std_hyd_VDF_diphasique::calculer_hyd(), Paroi_std_hyd_VEF_diphasique::calculer_hyd(), Paroi_loi_WW_hyd_EF::calculer_hyd(), Paroi_std_hyd_EF::calculer_hyd(), Paroi_2couches_VDF::calculer_hyd(), Paroi_loi_Ciofalo_hyd_VDF::calculer_hyd(), Paroi_loi_WW_hyd_VDF::calculer_hyd(), Paroi_loi_WW_hyd_VEF::calculer_hyd(), Paroi_std_hyd_VDF::calculer_hyd(), Paroi_UTAU_IMP_VDF::calculer_hyd(), ParoiVDF_TBLE::calculer_hyd(), ParoiVEF_TBLE::calculer_hyd(), LoiParoiHybride_VDF::calculer_hyd_BiK(), Paroi_std_hyd_VDF::calculer_hyd_BiK(), Paroi_UTAU_IMP_VDF::calculer_hyd_BiK(), ParoiVDF_TBLE::calculer_hyd_BiK(), ParoiVDF_TBLE_LRM::calculer_hyd_BiK(), LoiParoiHybride_VEF::calculer_hyd_BiK(), Paroi_std_hyd_VEF::calculer_hyd_BiK(), ParoiVEF_TBLE::calculer_hyd_BiK(), IJK_Interfaces::calculer_indicatrice(), IJK_Interfaces::calculer_indicatrices(), Modele_turbulence_hyd_LES_DSGS_VDF::calculer_Lij(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calculer_Lij(), Modele_turbulence_scal_LES_dyn_VDF::calculer_Lj(), Remaillage_FT::calculer_longueurIdeale2_arete(), Modele_turbulence_hyd_LES_VDF_base::calculer_longueurs_caracteristiques(), Modele_turbulence_hyd_LES_VEF_base::calculer_longueurs_caracteristiques(), Loi_Etat_Multi_GP_WC::calculer_masse_molaire(), Loi_Etat_Binaire_GP_WC::calculer_masse_volumique(), Loi_Etat_GP_WC::calculer_masse_volumique(), Loi_Etat_Multi_GP_WC::calculer_masse_volumique(), Loi_Etat_TPPI_WC_base::calculer_masse_volumique(), Op_Diff_VEF_Face_Stab::calculer_max(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calculer_Mij(), Modele_turbulence_hyd_LES_DSGS_VDF::calculer_Mij(), Op_Diff_VEF_Face_Stab::calculer_min(), Modele_turbulence_scal_LES_dyn_VDF::calculer_Mj(), Modele_turbulence_hyd_LES_DSGS_VDF::calculer_model_coefficient(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calculer_model_coefficient(), Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_nut(), Paroi_std_hyd_VDF::calculer_moyennes_parois(), Modele_turbulence_hyd_LES_Wale_VDF::calculer_OP1_OP2(), Equation_base::calculer_pas_de_temps(), Pb_Multiphase::calculer_pas_de_temps(), IJK_Interfaces::calculer_phi_repuls_sommet(), Source_Con_Phase_field::calculer_point_fixe(), Senseur_Interface::calculer_position(), Op_Conv_VEF_base::calculer_pour_post(), Op_Diff_VEF_base::calculer_pour_post(), Modele_turbulence_hyd_LES_Fst_VEF::calculer_racine(), Modele_turbulence_hyd_LES_Smago_VDF::calculer_S_barre(), Modele_turbulence_hyd_LES_Smago_VEF::calculer_S_barre(), Modele_turbulence_hyd_LES_Smago_filtre_VEF::calculer_S_barre(), Paroi_std_scal_hyd_EF::calculer_scal(), Loi_Paroi_Nu_Impose_VDF::calculer_scal(), Paroi_loi_WW_scal_VDF::calculer_scal(), Paroi_ODVM_scal_VDF::calculer_scal(), Paroi_std_scal_hyd_VDF::calculer_scal(), Paroi_TBLE_scal_VDF::calculer_scal(), Loi_Paroi_Nu_Impose_VEF::calculer_scal(), Paroi_loi_WW_scal_VEF::calculer_scal(), Paroi_scal_analytique_VEF::calculer_scal(), Paroi_std_scal_hyd_VEF::calculer_scal(), ParoiVEF_TBLE_scal::calculer_scal(), Modele_turbulence_hyd_LES_DSGS_VDF::calculer_Sij(), Modele_turbulence_hyd_Longueur_Melange_VDF::calculer_Sij2(), Modele_turbulence_hyd_Longueur_Melange_VEF::calculer_Sij2(), Parcours_interface::calculer_sortie_face_bord(), Loi_Etat_Multi_GP_WC::calculer_tab_Cp(), Champ_front_contact_rayo_transp_VEF::calculer_temperature_bord(), Champ_front_contact_rayo_semi_transp_VEF::calculer_temperature_bord(), Eval_Puiss_Th_DG_Elem::calculer_terme_source(), Eval_Puiss_Th_PolyMAC_Elem::calculer_terme_source(), Eval_Source_C_PolyMAC_Elem::calculer_terme_source(), Eval_Puiss_Th_VDF_Elem::calculer_terme_source(), Eval_Source_C_VDF_Elem::calculer_terme_source(), Eval_Puiss_Th_EF::calculer_terme_source(), Eval_Puiss_Th_QC_EF::calculer_terme_source(), Paroi_flux_impose_Rayo_transp::calculer_Teta_i_VDF(), Echange_contact_Rayo_transp_VDF::calculer_Teta_paroi(), Source_Con_Phase_field::calculer_u2_elem(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_W_VDF_Elem::calculer_u_teta_W(), Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::calculer_u_teta_W(), Source_Transport_Fluctuation_Temperature_W_VDF_Elem::calculer_u_teta_W(), IJK_Interfaces::calculer_var_volume_remaillage(), Source_PDF_EF::calculer_variable_imposee_elem_fluid(), Source_PDF_EF::calculer_variable_imposee_hybrid(), Source_PDF_EF::calculer_variable_imposee_mean_grad(), Modele_turbulence_hyd_LES_axi_VDF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_DSGS_VDF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_VDF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_1elt_VEF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_Fst_VEF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_VEF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_Smago_VDF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_Wale_VDF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_Longueur_Melange_VDF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_Smago_VEF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_Wale_VEF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_Longueur_Melange_VEF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calculer_viscosite_turbulente(), Terme_Source_Acceleration_VDF_Face::calculer_vitesse_faces(), Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl(), Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl_u_star(), Transport_Interfaces_FT_Disc::calculer_vitesse_transport_interpolee(), Maillage_FT_Disc::calculer_voisinage_facettes(), Champ_Fonc_Elem_PolyMAC_P0_rot::champ_a_deriver(), Champ_Fonc_Elem_PolyMAC_P0_TC::champ_a_deriver(), grad_Champ_Face_PolyMAC_P0::champ_a_deriver(), Maillage_FT_Disc::check_sommets(), Paroi_std_hyd_VEF::check_turbulence_model(), Frottement_interfacial_Weber::coefficient(), Portance_interfaciale_Sugrue_Modifiee::coefficient(), Triple_Line_Model_FT_Disc::completer(), Pb_Couple_Rayonnement::completer(), Operateur_base::completer(), EDO_Pression_th_base::completer(), Flux_interfacial_constant_Nu::completer(), Vitesse_derive_Spelt_Biesheuvel::completer(), Loi_paroi_Ramstorfer::completer(), Viscosite_turbulente_k_omega::completer(), IJK_Thermals::completer(), Schema_Temps_IJK_base::completer(), Probleme_FTD_IJK_base::completer(), Convection_Diffusion_Temperature_FT_Disc::completer(), Paroi_flux_impose_Rayo_transp::completer(), Op_Diff_K_Eps_VDF_base::completer(), Op_Diff_K_Omega_VDF_base::completer(), Op_Diff_K_Eps_VEF_base::completer(), Op_Diff_DG_Elem::completer(), Evaluateur_Source_Elem::completer(), Evaluateur_Source_Face::completer(), Op_Conv_EF_Stab_PolyMAC_Face::completer(), Op_Conv_EF_Stab_PolyMAC_P0_Face::completer(), Op_Diff_PolyMAC_P0_base::completer(), Op_Diff_PolyMAC_Elem::completer(), Op_Diff_PolyMAC_Face::completer(), Op_Diff_PolyMAC_P0_Elem::completer(), Op_Diff_PolyMAC_P0_Face::completer(), Op_Diff_PolyMAC_P0P1NC_Elem::completer(), Op_Diff_PolyMAC_P0P1NC_Face::completer(), Op_Grad_PolyMAC_P0_Face::completer(), Op_Grad_PolyMAC_P0P1NC_Face::completer(), Masse_PolyMAC_P0_Face::completer(), Masse_PolyMAC_P0P1NC_Face::completer(), Navier_Stokes_Fluide_Dilatable_base::completer(), Flux_interfacial_Chen_Mayinger::completer(), Flux_interfacial_Kim_Park::completer(), Flux_interfacial_Ranz_Marshall::completer(), Flux_interfacial_Wolfert::completer(), Flux_interfacial_Wolfert_composant::completer(), Flux_interfacial_Zeitoun::completer(), Frottement_interfacial_bulles_constant::completer(), Vitesse_derive_Forces::completer(), Op_Diff_VDF_base::completer(), Masse_VDF_Face::completer(), EDO_Pression_th_VEF::completer(), Op_Conv_EF_VEF_P1NC_Stab::completer(), Op_Conv_VEF_Face::completer(), Op_Diff_VEF_Face_Stab::completer(), Perte_Charge_VEF::completer(), Eval_Puiss_Th_QC_VEF_Face::completer(), Eval_Puiss_Th_VEF_Face::completer(), Eval_Source_C_VEF_Face::completer(), Evaluateur_Source_VEF_Face::completer(), Champ_Post_Operateur_Eqn::completer(), Iterateur_Source_Face< _TYPE_ >::completer_(), Iterateur_Source_VEF_Face< _TYPE_ >::completer_(), Source_Transport_K_Omega_VEF_Face::compute_blending_F1(), IJK_Interfaces::compute_cell_phase_with_interface_normal(), Source_PDF_EF::compute_coeff_elem(), Source_PDF_EF::compute_coeff_matrice(), Convection_Diffusion_Temperature_FT_Disc::compute_divergence_free_velocity_extension(), IJK_Interfaces::compute_drapeaux_vapeur_v4(), Post_Processing_Hydrodynamic_Forces::compute_friction_force_complet_tensor(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_friction_force_complet_tensor(), Post_Processing_Hydrodynamic_Forces::compute_friction_force_projected_tensor(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_friction_force_projected_tensor(), Post_Processing_Hydrodynamic_Forces::compute_heat_transfer(), Post_Processing_Hydrodynamic_Forces::compute_hydrodynamic_forces(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_hydrodynamic_forces(), Source_PDF_EF::compute_indicateur_nodal_champ_aire(), Source_WC_Chaleur_VDF::compute_interpolate_gradP(), Source_WC_Chaleur_VEF::compute_interpolate_gradP(), Paroi_std_hyd_VDF::compute_law_komega(), Post_Processing_Hydrodynamic_Forces::compute_neighbors_coordinates_fluid_fa7(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_neighbors_coordinates_fluid_fa7(), Paroi_scal_hyd_base_VDF::compute_nusselt(), Transport_Interfaces_FT_Disc::compute_particles_rms(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_pressure_force_trilinear_linear(), Post_Processing_Hydrodynamic_Forces::compute_pressure_force_trilinear_linear(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_pressure_interf(), Champ_Elem_DG::compute_stab_param(), Triple_Line_Model_FT_Disc::compute_TCL_fluxes_in_all_boundary_cells(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_vinf_Stokes(), Post_Processing_Hydrodynamic_Forces::compute_viscosity_edges_sphere(), Pb_Couple_Rayonnement::cond_l_base(), Convection_Diffusion_Concentration::constituant(), AssembleurPVDF_PF::construire(), Assembleur_P_VDF::construire(), Marching_Cubes::construire_noeuds_joints(), Marching_Cubes::construire_noeuds_uniques(), Source_Con_Phase_field::construire_systeme(), Op_Conv_Amont_old_VEF_Face::contribue_au_second_membre(), Op_Conv_VEF_Face::contribue_au_second_membre(), Op_Diff_VEF_Anisotrope_Face::contribue_au_second_membre(), Op_Diff_VEF_Face::contribue_au_second_membre(), Op_Diff_VEF_Face_Q1::contribue_au_second_membre(), Op_Diff_K_Omega_VEF_Face::contribuer_a_avec(), Source_Transport_Realisable_VEF_Face_base::contribuer_a_avec(), Source_Transport_K_Omega_VEF_Face::contribuer_a_avec(), Source_PDF_EF::contribuer_a_avec(), Op_Conv_EF_Stab_PolyMAC_Face::contribuer_a_avec(), Op_Diff_PolyMAC_Elem::contribuer_a_avec(), Op_Diff_PolyMAC_Face::contribuer_a_avec(), Perte_Charge_Singuliere_PolyMAC_Face::contribuer_a_avec(), Perte_Charge_Singuliere_VEF_Face::contribuer_a_avec(), Perte_Charge_VEF::contribuer_a_avec(), Terme_Puissance_Thermique_Echange_Impose_VEF_Face::contribuer_a_avec(), Terme_Source_Decroissance_Radioactive_VEF_Face::contribuer_a_avec(), Op_Div_PolyMAC::contribuer_a_avec(), Op_Div_PolyMAC_P0::contribuer_a_avec(), Op_Grad_PolyMAC_Face::contribuer_a_avec(), Op_Diff_DG_Elem::contribuer_au_second_membre(), Op_Diff_PolyMAC_Elem::contribuer_termes_croises(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::controler_grandeurs_turbulentes(), IJK_Interfaces::convert_to_IntVect(), Op_Conv_kschemas_centre_VEF::convkschemas_centre(), Source_PDF_EF::correct_incr_pressure(), Convection_Diffusion_Temperature_FT_Disc::correct_mpoint(), Source_Dispersion_bulles_base::correlation(), Corrige_flux_FT_temperature_conv::corrige_flux_faceIJ(), Op_Diff_VEFP1NCP1B_Face::corriger_Cl_test(), Op_Diff_VEFP1NCP1B_Face::corriger_div_pour_Cl(), Schema_Temps_base::corriger_dt_calcule(), Schema_Euler_Implicite_Stationnaire::corriger_dt_calcule(), Masse_PolyMAC_P0P1NC_Face::corriger_solution(), Traitement_particulier_NS_CEG::critere_cea_jaea(), Facettes_Interp_FT::cut_cell_perform_interpolation_facettes_next(), Facettes_Interp_FT::cut_cell_perform_interpolation_facettes_old(), Modele_turbulence_hyd_LES_selectif_mod_VDF::cutoff(), Modele_turbulence_hyd_LES_selectif_VDF::cutoff(), Modele_turbulence_hyd_LES_1elt_selectif_mod_VEF::cutoff(), Modele_turbulence_hyd_LES_Fst_sel_VEF::cutoff(), Convection_Diffusion_Espece_Binaire_WC::data_a_sauvegarder(), Op_Div_VEFP1B_Elem::degres_liberte(), Transport_Interfaces_FT_Disc::deplacer_maillage_ft_v_fluide(), Maillage_FT_Disc::deplacer_sommets(), Maillage_FT_IJK::deplacer_sommets(), Loi_paroi_Ramstorfer::deriv_u_plus_de_y_plus(), Convection_Diffusion_Temperature_FT_Disc::derivee_en_temps_inco(), Navier_Stokes_phase_field::derivee_en_temps_inco(), Eval_Diff_K_Eps_VDF::diffusivite(), Eval_Diff_K_Omega_VDF::diffusivite(), Operateur_Diff::diffusivite(), Op_Diff_DG_base::diffusivite(), Op_Diff_negligeable::diffusivite(), Op_Diff_PolyMAC_Gen_base::diffusivite(), Op_Diff_VEF_Anisotrope_Face::diffusivite(), Op_Diff_VEF_Face::diffusivite(), Op_Diff_VEF_Face_Q1::diffusivite(), Op_Dift_VEF_base::diffusivite(), Operateur_Diff_base::diffusivite_pour_pas_de_temps(), Transport_K_Eps_non_std::diffusivite_pour_transport(), Transport_K_Eps_Realisable::diffusivite_pour_transport(), Transport_K_ou_Eps_non_std::diffusivite_pour_transport(), Eval_Diff_K_Eps_Bas_Re_VDF_var::diffusivite_turbulente(), Eval_Diff_K_Eps_VDF::diffusivite_turbulente(), Eval_Diff_K_Omega_VDF::diffusivite_turbulente(), Op_Diff_Turbulent_base::diffusivite_turbulente(), Eval_Dift_VDF::diffusivite_turbulente(), Op_Conv_ALE_VEF::dimensionner(), Op_Grad_PolyMAC_Face::dimensionner(), Op_Conv_Amont_old_VEF_Face::dimensionner(), Op_Conv_EF_VEF_P1NC::dimensionner(), Op_Conv_VEF_Face::dimensionner(), Op_Diff_VEF_Anisotrope_Face::dimensionner(), Op_Diff_VEF_Face::dimensionner(), Op_Diff_VEF_Face_Q1::dimensionner(), Op_Diff_VEFP1NCP1B_Face::dimensionner(), Op_Conv_EF_Stab_PolyMAC_Face::dimensionner(), Op_Diff_PolyMAC_Elem::dimensionner(), Op_Diff_PolyMAC_Face::dimensionner(), Op_Conv_EF::dimensionner(), Op_Diff_EF::dimensionner(), Op_Dift_EF_Q1::dimensionner(), Op_Div_PolyMAC::dimensionner(), Op_Div_PolyMAC_P0::dimensionner(), Op_Diff_VDF_Face_Axi_base::dimensionner(), Op_Dift_VDF_Face_Axi_base::dimensionner(), Op_Dift_VEF_base::dimensionner(), Masse_PolyMAC_Elem::dimensionner(), Op_Grad_VDF_Face::dimensionner_blocs(), Perte_Charge_Singuliere_VDF_Face::dimensionner_blocs(), Op_Conv_EF_Stab_PolyMAC_P0_Face::dimensionner_blocs(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Face::dimensionner_blocs(), Op_Diff_PolyMAC_P0_Face::dimensionner_blocs(), Op_Div_PolyMAC_P0P1NC::dimensionner_blocs(), Op_Grad_PolyMAC_P0_Face::dimensionner_blocs(), Op_Grad_PolyMAC_P0P1NC_Face::dimensionner_blocs(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::dimensionner_blocs(), Op_Diff_PolyMAC_P0_Elem::dimensionner_blocs(), Op_Diff_PolyMAC_P0P1NC_Elem::dimensionner_blocs_ext(), Op_Diff_PolyMAC_P0P1NC_Face::dimensionner_blocs_ext(), Solveur_Masse_Face_proto::dimensionner_blocs_proto(), Solveur_Masse_Elem_proto::dimensionner_blocs_proto(), Assembleur_P_PolyMAC_P0P1NC::dimensionner_continuite(), Op_Diff_PolyMAC_Elem::dimensionner_termes_croises(), Probleme_base::discretisation(), Sous_domaine_VF::discretiser(), Convection_Diffusion_Temperature::discretiser(), Milieu_base::discretiser_diametre_hydro(), Milieu_base::discretiser_porosite(), Source_Con_Phase_field::div_kappa_grad(), EOS_Tools_VEF::divu_discvit(), Iterateur_PolyMAC_base::domaine(), Iterateur_VDF_base::domaine(), Iterateur_PolyMAC_base::domaine_Cl(), Iterateur_VDF_base::domaine_Cl(), Cond_lim_base::domaine_Cl_dis(), Champ_Inc_base::domaine_Cl_dis(), Y_plus_Champ_Q1::domaine_Cl_dis_base(), Critere_Q_Champ_Face::domaine_Cl_dis_base(), T_paroi_Champ_P0_VDF::domaine_Cl_dis_base(), Y_plus_Champ_Face::domaine_Cl_dis_base(), grad_T_Champ_P1NC::domaine_Cl_dis_base(), grad_U_Champ_P1NC::domaine_Cl_dis_base(), h_conv_Champ_P1NC::domaine_Cl_dis_base(), T_paroi_Champ_P1NC::domaine_Cl_dis_base(), Y_plus_Champ_P1NC::domaine_Cl_dis_base(), AssembleurPVDF_PF::domaine_Cl_dis_base(), Assembleur_P_EF::domaine_Cl_dis_base(), Assembleur_P_PolyMAC::domaine_Cl_dis_base(), Assembleur_P_VDF::domaine_Cl_dis_base(), Assembleur_P_VDF_Q4::domaine_Cl_dis_base(), Assembleur_P_VEF::domaine_Cl_dis_base(), Op_Diff_PolyMAC_Gen_base::domaine_cl_poly(), Op_Grad_VDF_Face_base::domaine_Cl_VDF(), Op_Diff_VEF_base::domaine_cl_vef(), Op_Diff_VEFP1NCP1B_Face::domaine_Cl_VEFPreP1B(), Equation_base::domaine_dis(), Frontiere_dis_base::domaine_dis(), Probleme_base::domaine_dis(), Sous_domaine_dis_base::domaine_dis(), AssembleurPVDF_PF::domaine_dis_base(), Assembleur_P_EF::domaine_dis_base(), Champ_Fonc_base::domaine_dis_base(), Champ_Inc_base::domaine_dis_base(), Champ_Fonc_P0_MED::domaine_dis_base(), Champ_Fonc_P1_MED::domaine_dis_base(), Champ_Fonc_Q1_MED::domaine_dis_base(), Assembleur_P_PolyMAC::domaine_dis_base(), Assembleur_P_VDF::domaine_dis_base(), Assembleur_P_VDF_Q4::domaine_dis_base(), Assembleur_P_VEF::domaine_dis_base(), Champ_Fonc_P1_EF::domaine_EF(), Champ_Fonc_Q1_EF::domaine_EF(), Champ_P0_EF::domaine_EF(), Champ_P1_EF::domaine_EF(), Champ_Q1_EF::domaine_EF(), Probleme_FTD_IJK_base::domaine_ijk(), Op_Diff_PolyMAC_Gen_base::domaine_poly(), Champ_Elem_PolyMAC_P0::domaine_PolyMAC_P0(), Champ_Face_PolyMAC_P0::domaine_PolyMAC_P0(), Champ_Elem_PolyMAC_P0P1NC::domaine_PolyMAC_P0P1NC(), Champ_Face_PolyMAC_P0P1NC::domaine_PolyMAC_P0P1NC(), Op_Grad_VDF_Face_base::domaine_VDF(), Champ_P0_VDF::domaine_VDF(), Faces_VDF::domaine_VDF(), Champ_Face_VDF::domaine_vdf(), Champ_Fonc_Face_VDF::domaine_vdf(), Champ_P0_VEF::domaine_vef(), Op_Diff_RotRot::domaine_vef(), Op_Diff_VEF_base::domaine_vef(), Op_Diff_VEFP1NCP1B_Face::domaine_vef(), Op_Grad_VEF_P1B_Face::domaine_vef(), Assembleur_P_VEFPreP1B::domaine_Vef(), Champ_Fonc_P1_isoP1Bulle::domaine_vef(), Champ_Fonc_P1NC::domaine_vef(), Champ_Fonc_Q1NC::domaine_vef(), Champ_P1_isoP1Bulle::domaine_vef(), Champ_P1NC::domaine_vef(), Champ_Q1NC::domaine_vef(), Champ_Fonc_base::domaine_vf(), Champ_Inc_base::domaine_vf(), IJK_Interfaces::dupliquer_bulle_perio(), Fluide_reel_base::H_to_T::dX_dP_T(), Schema_Comm::echange_messages(), Schema_Comm::echange_taille(), Maillage_FT_Disc::echanger_facettes(), Maillage_FT_Disc::echanger_sommets_PE(), Format_Post_Med::ecrire_champ_med(), Format_Post_Med::ecrire_domaine_dual(), Format_Post_Med::ecrire_domaine_med(), Postraitement_ft_lata::ecrire_maillage_ft_disc(), Viscosite_turbulente_k_omega::eddy_viscosity(), Iterateur_Source_VEF_Face< _TYPE_ >::elem_faces(), Post_Processing_Hydrodynamic_Forces::elem_faces_for_interp(), Triple_Line_Model_FT_Disc::elems(), Parcours_interface::eloigner_sommets_des_faces(), Schema_Comm::end_comm(), Terme_Source_Coriolis_base::eq_hydraulique(), Terme_Source_inc_base::eq_hydraulique(), Terme_Source_inc_th::eq_hydraulique(), Convection_Diffusion_Temperature_FT_Disc::eq_interface(), Terme_Source_inc_th::eq_thermique(), Modele_turbulence_hyd_base::equation(), Modele_turbulence_scal_base::equation(), Modele_Fonc_Bas_Reynolds_Base::equation(), Modele_Fonc_Bas_Reynolds_Thermique_Base::equation(), Modele_Fonc_Realisable_base::equation(), Assembleur_P_EF::equation(), MorEqn::equation(), Assembleur_P_PolyMAC::equation(), Assembleur_P_VEF::equation(), Assembleur_P_VEFPreP1B::equation(), Modele_turbulence_scal_Fluctuation_Temperature_W::equation_Fluctu(), Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re::equation_Fluctu(), Terme_Boussinesq_base::equation_scalaire(), Maillage_FT_Disc::equation_transport(), Navier_Stokes_FTD_IJK::euler_time_step(), Champ_Elem_DG::eval_bfunc(), Champ_Elem_DG::eval_bfunc_on_facets(), Champ_Elem_DG::eval_elem(), Champ_Elem_DG::eval_grad_bfunc(), Champ_Elem_DG::eval_grad_bfunc_on_facets(), Champ_Elem_DG::eval_invMassMatrix(), Vitesse_derive_Spelt_Biesheuvel::evaluate_C0_vg0(), Vitesse_derive_Forces::evaluate_C0_vg0(), PE_Groups::exit_group(), Iterateur_Source_VEF_Face< _TYPE_ >::face_voisins(), Post_Processing_Hydrodynamic_Forces::face_voisins_for_interp(), Iterateur_Source_Face< _TYPE_ >::faces_doubles(), Iterateur_Source_VEF_Face< _TYPE_ >::faces_doubles(), Transport_Interfaces_FT_Disc::fill_ftab_local_reference_frame_velocity(), Transport_Interfaces_FT_Disc::fill_ftab_velocity(), Milieu_base::fill_section_passage_face(), Post_Processing_Hydrodynamic_Forces_Stokes::fill_sigma_Stokes_th(), Post_Processing_Hydrodynamic_Forces_Stokes::fill_Stokes_pressure_field(), Post_Processing_Hydrodynamic_Forces_Stokes::fill_Stokes_velocity_field(), Source_PDF_EF::filtre_CLD(), Post_Processing_Hydrodynamic_Forces::find_neighboring_elements(), Post_Processing_Hydrodynamic_Forces::find_neighboring_faces(), Schema_Temps_IJK_base::find_timestep(), Equation_rayonnement_base::fluide(), Convection_Diffusion_Fluide_Dilatable_base::fluide(), Convection_Diffusion_Temperature_base::fluide(), Navier_Stokes_std::fluide(), Masse_Multiphase::fluide(), Champ_front_base::frontiere_dis(), Triple_Line_Model_FT_Disc::get_any_tcl_face(), Source_PDF_EF::get_champ(), Paroi_hyd_base_EF::get_champ(), Champ_Post_Operateur_Eqn::get_champ(), Champ_Generique_modifier_pour_QC::get_champ(), Support_Champ_Masse_Volumique::get_champ_masse_volumique(), Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::get_cut_cell_disc(), TRUSTTabFT_cut_cell< _TYPE_ >::get_cut_cell_disc(), Cut_cell_data::get_cut_cell_disc(), Eval_Diff_VDF::get_diffusivite(), Facettes_Interp_FT::get_distance_interpolation_1(), Facettes_Interp_FT::get_distance_interpolation_2(), Maillage_FT_IJK::get_domaine(), Probleme_FTD_IJK_base::get_domaine(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_domaine(), IJK_Interfaces::get_domaine_dis(), Champ_Face_base::get_elem_vector(), Champ_Face_base::get_elem_vector_field(), Convection_Diffusion_Temperature_FT_Disc::get_eq_interface(), Schema_Comm::get_group(), Maillage_FT_IJK::get_ijk_cell_index(), Triple_Line_Model_FT_Disc::get_in_out_coords(), Eval_Conv_VDF::get_la_zcl(), Eq_couch_lim::get_milieu(), Op_Dift_VEF_base::get_modele_turbulence(), PE_Groups::get_node_group(), PE_Groups::get_node_master(), Op_Dift_Multiphase_proto::get_noms_champs_postraitables_proto(), Fluide_Dilatable_base::get_problem(), Transport_Interfaces_FT_Disc::get_probleme_base(), Triple_Line_Model_FT_Disc::get_Qtcl(), Champ_Generique_refChamp::get_ref_champ_base(), Champ_Generique_Extraction::get_ref_domaine_dis_base(), Champ_Generique_Interpolation::get_ref_domaine_dis_base(), Champ_Generique_refChamp::get_ref_pb_base(), Champ_Generique_refChamp_special::get_ref_values(), Convection_Diffusion_Temperature_sensibility::get_temperature_state(), Triple_Line_Model_FT_Disc::get_theta_app(), Convection_Diffusion_Temperature_sensibility::get_velocity_state(), Milieu_base::gravite(), Terme_Boussinesq_base::gravite(), PE_Groups::groupe_TRUST(), Op_Grad_VEF_P1B_Face::impr(), Op_Grad_EF::impr(), Op_Grad_VDF_Face::impr(), Loi_Paroi_Nu_Impose_VDF::imprimer_nusselt(), Loi_Paroi_Nu_Impose_VEF::imprimer_nusselt(), Paroi_scal_hyd_base_VDF::imprimer_nusselt(), Paroi_std_hyd_EF::imprimer_ustar(), Paroi_std_hyd_VDF::imprimer_ustar(), ParoiVDF_TBLE::imprimer_ustar(), Paroi_std_hyd_VEF::imprimer_ustar(), ParoiVEF_TBLE::imprimer_ustar(), Paroi_2couches_VDF::imprimer_ustar(), ParoiVDF_TBLE_LRM::imprimer_ustar(), Fluide_Dilatable_base::inco_chaleur(), Champ_front_calc::inconnue(), Champ_front_contact_VEF::inconnue(), Champ_front_contact_rayo_transp_VEF::inconnue1(), Champ_front_contact_rayo_semi_transp_VEF::inconnue1(), Champ_front_contact_rayo_transp_VEF::inconnue2(), Champ_front_contact_rayo_semi_transp_VEF::inconnue2(), Postraitement::init(), Sonde::init_bords(), Champ_Face_base::init_fcl(), Champ_Elem_PolyMAC_P0::init_grad(), ParoiVDF_TBLE::init_lois_paroi(), ParoiVDF_TBLE_LRM::init_lois_paroi(), Paroi_ODVM_scal_VDF::init_lois_paroi(), Paroi_TBLE_scal_VDF::init_lois_paroi(), ParoiVEF_TBLE::init_lois_paroi(), ParoiVEF_TBLE_scal::init_lois_paroi(), Paroi_scal_hyd_base_VDF::init_lois_paroi(), Paroi_hyd_base_EF::init_lois_paroi_(), Paroi_hyd_base_VEF::init_lois_paroi_(), Couplage_Parietal_PolyMAC_helper::init_op_ext(), Op_Diff_PolyMAC_P0P1NC_Elem::init_op_ext(), Transport_Interfaces_FT_Disc::init_particles_position_velocity(), Probleme_FTD_IJK_base::initialise_ijk_fields(), Probleme_FTD_IJK_base::initialise_interfaces(), Sonde::initialiser(), Champ_front_recyclage::initialiser(), Champ_front_contact_VEF::initialiser(), Loi_Etat_Multi_GP_WC::initialiser_inco_ch(), Champ_front_recyclage::initialiser_moyenne_imposee(), Champ_front_recyclage::initialiser_moyenne_recyclee(), Triple_Line_Model_FT_Disc::initialize(), Probleme_FTD_IJK::initialize(), Probleme_FTD_IJK_base::initialize(), Probleme_FTD_IJK_cut_cell::initialize(), IJK_Thermal_cut_cell::initialize(), Navier_Stokes_Fluide_Dilatable_base::initTimeStep(), Navier_Stokes_std::initTimeStep(), Navier_Stokes_Turbulent_QC::initTimeStep(), Interprete_bloc::interprete_courant(), Op_Diff_VEFP1NCP1B_Face::isFaceOfSymetry(), Op_Correlation::la_moyenne_a(), Op_Correlation::la_moyenne_b(), Sonde::le_champ(), Perte_Charge_PolyMAC::le_dom_poly(), EOS_Tools_VDF::le_fluide(), EOS_Tools_VEF::le_fluide(), Pb_Couple_Rayonnement::le_modele_rayo(), Traitement_particulier_NS_canal::lire(), Modele_turbulence_hyd_Longueur_Melange_VEF::lire_distance_paroi(), Modele_Lam_Bremhorst_VEF::lire_distance_paroi(), Postraitement_ft_lata::lire_entete_bloc_interface(), Pb_Multiphase::lire_equations(), Convection_Diffusion_Concentration_FT_Disc::lire_motcle_non_standard(), Convection_Diffusion_Concentration_Turbulent_FT_Disc::lire_motcle_non_standard(), Transport_Interfaces_FT_Disc::lire_motcle_non_standard(), Transport_K_Eps::lire_motcle_non_standard(), Transport_K_Omega::lire_motcle_non_standard(), Transport_K_ou_Eps::lire_motcle_non_standard(), Transport_K_ou_Eps_Realisable::lire_motcle_non_standard(), Modele_turbulence_scal_Fluctuation_Temperature_W::lire_motcle_non_standard(), Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re::lire_motcle_non_standard(), Op_Diff_VEFP1NCP1B_Face::liste_face(), EDO_Pression_th_VDF::masse_totale(), EDO_Pression_th_VEF::masse_totale(), Paroi_frottante_simple::me_calculer(), Cond_lim_k_complique_transition_flux_nul_demi::me_calculer(), Cond_lim_k_simple_flux_nul::me_calculer(), Cond_lim_omega_demi::me_calculer(), Cond_lim_omega_dix::me_calculer(), Champ_Fonc_Elem_PolyMAC_P0_TC::me_calculer(), grad_U_Champ_Face::me_calculer(), T_paroi_Champ_P0_VDF::me_calculer(), grad_U_Champ_P1NC::me_calculer(), Y_plus_Champ_Q1::me_calculer(), Critere_Q_Champ_Face::me_calculer(), Y_plus_Champ_Face::me_calculer(), grad_T_Champ_P1NC::me_calculer(), h_conv_Champ_P1NC::me_calculer(), Y_plus_Champ_P1NC::me_calculer(), Source_Qdm_VDF_Phase_field::methode_1(), Source_Qdm_VDF_Phase_field::methode_2(), Source_Qdm_VDF_Phase_field::methode_3(), Source_Qdm_VDF_Phase_field::methode_4(), Eval_Diff_K_Eps_VDF::mettre_a_jour(), Eval_Diff_K_Omega_VDF::mettre_a_jour(), Eval_Darcy_VDF_Face::mettre_a_jour(), Eval_Darcy_VEF_Face::mettre_a_jour(), Source_Masse_Fluide_Dilatable_base::mettre_a_jour(), Convection_Diffusion_Temperature_FT_Disc::mettre_a_jour(), Transport_Interfaces_FT_Disc::mettre_a_jour(), Champ_front_recyclage::mettre_a_jour(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::mettre_a_jour(), Champ_front_pression_from_u::mettre_a_jour(), Champ_front_synt::mettre_a_jour(), Champ_front_debit_QC::mettre_a_jour(), Champ_front_debit_QC_fonc_t::mettre_a_jour(), Champ_front_contact_fictif_VEF::mettre_a_jour(), Champ_front_contact_VEF::mettre_a_jour(), Interface_base::mettre_a_jour(), Estimateur_Aposteriori_P0_VEF::mettre_a_jour(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::mettre_a_jour(), Modele_turbulence_scal_Fluctuation_Temperature_W::mettre_a_jour(), Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re::mettre_a_jour(), Champ_Fonc_Tabule_Elem_PolyMAC::mettre_a_jour(), Terme_Puissance_Thermique_Echange_Impose_Elem_base::mettre_a_jour(), Saturation_base::mettre_a_jour(), Champ_Fonc_Tabule_P0_VDF::mettre_a_jour(), Taux_cisaillement_P0_VDF::mettre_a_jour(), Op_Conv_VDF_base::mettre_a_jour(), Terme_Source_Canal_RANS_LES_VDF_Elem::mettre_a_jour(), Terme_Source_Canal_RANS_LES_VDF_Face::mettre_a_jour(), Champ_Fonc_Tabule_P0_VEF::mettre_a_jour(), Taux_cisaillement_P0_VEF::mettre_a_jour(), Terme_Source_Canal_RANS_LES_VEF_Face::mettre_a_jour(), Terme_Puissance_Thermique_Echange_Impose_VEF_Face::mettre_a_jour(), Sonde::mettre_a_jour_bords(), Convection_Diffusion_Concentration_FT_Disc::mettre_a_jour_chimie(), Convection_Diffusion_Concentration_Turbulent_FT_Disc::mettre_a_jour_chimie(), EDO_Pression_th_base::mettre_a_jour_CL(), Champ_front_contact_rayo_transp_VEF::mettre_a_jour_flux_radiatif(), Champ_front_contact_rayo_semi_transp_VEF::mettre_a_jour_flux_radiatif(), IJK_Thermal_base::milieu(), Convection_diffusion_turbulence_multiphase::milieu(), IJK_Thermals::milieu(), Navier_Stokes_FTD_IJK::milieu(), Equation_rayonnement_base::milieu(), Transport_Fluctuation_Temperature::milieu(), Transport_Fluctuation_Temperature_W::milieu(), Transport_Fluctuation_Temperature_W_Bas_Re::milieu(), Transport_Flux_Chaleur_Turbulente::milieu(), List_Equations_Scalaires_Passifs_Especes::milieu(), Navier_Stokes_std::milieu(), Aire_interfaciale::milieu(), Transport_Interfaces_FT_Disc::milieu(), Transport_2eq_base::milieu(), Equation_rayonnement_base::Modele(), Pb_Couple_rayo_semi_transp::modele(), Source_rayo_semi_transp_base::Modele(), Cond_Lim_rayo_semi_transp::modele(), Transport_K_Eps_Bas_Reynolds::modele_fonc(), Transport_K_Eps_Realisable::modele_fonc(), Cond_Lim_Rayo::modele_rayo(), Champ_front_contact_rayo_semi_transp_VEF::modele_rayo(), Transport_Fluctuation_Temperature_W_Bas_Re::modele_turbulence(), Transport_2eq_base::modele_turbulence(), Transport_Fluctuation_Temperature::modele_turbulence(), Transport_Fluctuation_Temperature_W::modele_turbulence(), Transport_Flux_Chaleur_Turbulente::modele_turbulence(), Modele_Fonc_Bas_Reynolds_Thermique_Base::modele_turbulence_Bas_Re(), Op_Diff_VEF_Face_Stab::modifie_pour_Cl(), Op_Grad_VEF_P1B_Face::modifier_grad_pour_Cl(), Transport_turbulent_GGDH::modifier_mu(), Transport_turbulent_SGDH::modifier_mu(), Op_Diff_K_Eps_VDF_base::modifier_pour_Cl(), Op_Diff_K_Omega_VDF_base::modifier_pour_Cl(), Op_Conv_Amont_old_VEF_Face::modifier_pour_Cl(), Op_Conv_EF_VEF_P1NC::modifier_pour_Cl(), Op_Conv_VEF_Face::modifier_pour_Cl(), Op_Diff_VEF_Anisotrope_Face::modifier_pour_Cl(), Op_Diff_VEF_Face::modifier_pour_Cl(), Op_Diff_VEF_Face_Q1::modifier_pour_Cl(), Op_Conv_EF::modifier_pour_Cl(), Op_Diff_EF::modifier_pour_Cl(), Op_Dift_EF_Q1::modifier_pour_Cl(), Op_Diff_VDF_Face_Axi_base::modifier_pour_Cl(), Op_Dift_VDF_Face_Axi_base::modifier_pour_Cl(), Op_Dift_VEF_base::modifier_pour_Cl(), AssembleurPVDF_PF::modifier_secmem(), Assembleur_P_EF::modifier_secmem(), Assembleur_P_PolyMAC::modifier_secmem(), Assembleur_P_VDF::modifier_secmem(), Assembleur_P_VEF::modifier_secmem(), Assembleur_P_VEFPreP1B::modifier_secmem(), Assembleur_P_VEFPreP1B::modifier_secmem_elem(), Assembleur_P_PolyMAC_P0P1NC::modifier_secmem_pour_incr_p(), AssembleurPVDF_PF::modifier_secmem_pression_imposee(), Assembleur_P_VDF::modifier_secmem_pression_imposee(), Assembleur_P_VEFPreP1B::modifier_secmem_som(), AssembleurPVDF_PF::modifier_secmem_vitesse_imposee(), Assembleur_P_VDF::modifier_secmem_vitesse_imposee(), Rotationnel_Champ_P1_EF::mon_champ(), Rotationnel_Champ_Q1_EF::mon_champ(), Y_plus_Champ_Q1::mon_champ(), Critere_Q_Champ_Face::mon_champ(), Rotationnel_Champ_Face::mon_champ(), T_paroi_Champ_P0_VDF::mon_champ(), Y_plus_Champ_Face::mon_champ(), Critere_Q_Champ_P1NC::mon_champ(), grad_T_Champ_P1NC::mon_champ(), grad_U_Champ_P1NC::mon_champ(), h_conv_Champ_P1NC::mon_champ(), Rotationnel_Champ_P1NC::mon_champ(), Rotationnel_Champ_Q1NC::mon_champ(), T_paroi_Champ_P1NC::mon_champ(), Y_plus_Champ_P1NC::mon_champ(), Correlation_Vec_Sca_VDF::mon_champ_Sca(), Correlation_Vec_Sca_VEF::mon_champ_Sca(), Correlation_Vec_Sca_VDF::mon_champ_Vec(), Correlation_Vec_Sca_VEF::mon_champ_Vec(), Champ_Ostwald_VDF::mon_champs(), Champ_Ostwald_VEF::mon_champs(), Champ_Ostwald::mon_fluide(), Operateur::mon_inconnue(), Operateur_base::mon_inconnue(), Loi_Fermeture_base::mon_probleme(), Terme_Source_Canal_RANS_LES_VDF_Face::moy_spat(), Op_Ecart_type::moyenne(), Champ_Fonc_P0_base::moyenne(), EOS_Tools_VEF::moyenne_vol(), Source_PDF_EF::multiply_coeff_volume(), Source_Con_Phase_field::non_lin_gmres(), Terme_Source_Qdm_lambdaup_VEF_Face::norme_H1(), Terme_Source_Qdm_lambdaup_VEF_Face::norme_L2(), Terme_Source_Canal_RANS_LES_VDF_Face::norme_vit(), TRUST_Ref< _CLASSE_ >::operator const value_type &(), TRUST_Ref< _CLASSE_ >::operator value_type &(), Schema_Comm::operator=(), Parcours_interface::parcourir(), Maillage_FT_Disc::parcourir_maillage(), Schema_Temps_base::pb_base(), Op_Conv_DI_L2_VEF_Face::poly_DI_L2_2d(), Op_Conv_DI_L2_VEF_Face::poly_DI_L2_3d(), Postraitement_ft_lata::postprocess_field_values(), Pb_Couple_Rayonnement::postraiter(), Postraitement::postraiter_champs(), Postraitement::postraiter_tableau(), Precond_local::preconditionner_(), Source_Con_Phase_field::premier_demi_dt(), Convection_Diffusion_Temperature_FT_Disc::preparer_calcul(), Transport_Interfaces_FT_Disc::preparer_calcul(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::preparer_calcul(), Masse_PolyMAC_P0P1NC_Elem::preparer_calcul(), Masse_VDF_Elem::preparer_calcul(), Probleme_base::printOn(), Modele_rayo_semi_transp::probleme(), Equation_base::probleme(), Postraitement::probleme(), Probleme_FTD_IJK_base::probleme(), Navier_Stokes_FT_Disc::probleme_ft(), IJK_Interfaces::probleme_ijk(), Navier_Stokes_FTD_IJK::probleme_ijk(), Flux_parietal_Kommajosyula::qp(), Flux_parietal_adaptatif::qp(), Convection_Diffusion_Concentration_FT_Disc::ramasse_miette_simple(), Convection_Diffusion_Concentration_Turbulent_FT_Disc::ramasse_miette_simple(), Op_Conv_ALE_VEF::readOn(), Coalescence_bulles_1groupe_Yao_Morel::readOn(), Dispersion_bulles_turbulente_Bazin::readOn(), Dispersion_bulles_turbulente_Bertodano::readOn(), Dispersion_bulles_turbulente_Burns::readOn(), Dispersion_bulles_turbulente_constante::readOn(), Dispersion_bulles_turbulente_Lavieville::readOn(), Flux_parietal_Hibiki::readOn(), Flux_parietal_Kommajosyula::readOn(), Flux_parietal_Kurul_Podowski::readOn(), Frottement_interfacial_Ishii_Zuber_Deformable::readOn(), Frottement_interfacial_Kumar_Brooks::readOn(), Frottement_interfacial_Tomiyama_complet::readOn(), Masse_ajoutee_Cai::readOn(), Portance_interfaciale_Sugrue_Modifiee::readOn(), Portance_interfaciale_Tomiyama_complet::readOn(), Rupture_bulles_1groupe_Yao_Morel::readOn(), Viscosite_turbulente_sato::readOn(), Postraitement_ft_lata::readOn(), Operateur_Conv_sensibility_VEF::readOn(), LoiParoiHybride_VDF::readOn(), LoiParoiHybride_VEF::readOn(), List_Equations_Scalaires_Passifs_Especes::readOn(), Sources::readOn(), Postraitement::readOn(), Sondes::readOn(), Sondes_Int::readOn(), Navier_Stokes_QC::readOn(), Navier_Stokes_WC::readOn(), Diametre_bulles_champ::readOn(), Diametre_bulles_constant::readOn(), Diametre_bulles_musig::readOn(), Dispersion_bulles_constante::readOn(), Flux_interfacial_Coef_Constant::readOn(), Flux_parietal_diphasique_simple_lineaire::readOn(), Frottement_interfacial_bulles_composant::readOn(), Frottement_interfacial_bulles_constant::readOn(), Frottement_interfacial_Garnier::readOn(), Frottement_interfacial_Ishii_Zuber::readOn(), Frottement_interfacial_Rusche::readOn(), Frottement_interfacial_Simonnet::readOn(), Frottement_interfacial_Sonnenburg::readOn(), Frottement_interfacial_Tomiyama::readOn(), Frottement_interfacial_Wallis::readOn(), Frottement_interfacial_Weber::readOn(), Frottement_interfacial_Zenit::readOn(), Gravite_Multiphase::readOn(), Masse_ajoutee_Coef_Constant::readOn(), Masse_ajoutee_Wijngaarden::readOn(), Masse_ajoutee_Zuber::readOn(), Multiplicateur_diphasique_Friedel::readOn(), Multiplicateur_diphasique_homogene::readOn(), Multiplicateur_diphasique_Lottes_Flinn::readOn(), Multiplicateur_diphasique_Muhler_Steinhagen::readOn(), Portance_interfaciale_Constante::readOn(), Portance_interfaciale_Sugrue::readOn(), Portance_interfaciale_Tomiyama::readOn(), Vitesse_relative_base::readOn(), QDM_Multiphase::readOn(), Source_Flux_interfacial_base::readOn(), Viscosite_turbulente_multiple::readOn(), Navier_Stokes_Turbulent_QC::readOn(), Terme_Source_Solide_SWIFT_VDF::readOn(), Source_QC_QDM_Gen::readOn_spec(), Op_Conv_DI_L2_VEF_Face::reconst_DI_L2_2d(), Op_Conv_DI_L2_VEF_Face::reconst_DI_L2_3d(), IJK_Interfaces::recursive_calcul_distance_chez_voisin(), Remaillage_FT::redistribuer_sommets(), Postraitement_ft_lata::register_interface_field(), Assembleur_P_VEF::remplir(), AssembleurPVDF_PF::remplir(), Assembleur_P_VDF::remplir(), Champ_front_contact_VEF::remplir_connect_bords(), Op_Conv_EF_VEF_P1NC_Stab::remplir_fluent(), Op_Conv_Muscl_New_VEF_Face::remplir_fluent(), Op_Conv_VEF_Face::remplir_fluent(), Operateur_Conv_sensibility_VEF::remplir_fluent(), Op_Conv_ALE_VEF::remplir_fluent_ALEincluded(), Op_Diff_VEF_base::remplir_nu(), Op_Diff_EF::remplir_nu(), Op_Dift_EF_Q1::remplir_nu(), Op_Diff_PolyMAC_base::remplir_nu_ef(), Perte_Charge_Reguliere_VEF_P1NC::remplir_num_faces(), Maillage_FT_Disc::reprendre(), ParoiVDF_TBLE::reprendre(), Paroi_TBLE_scal_VDF::reprendre(), ParoiVEF_TBLE::reprendre(), ParoiVEF_TBLE_scal::reprendre(), Convection_Diffusion_Chaleur_WC::reprendre(), Convection_Diffusion_Espece_Binaire_WC::reprendre(), Champ_Elem_PolyMAC_P0::reprendre(), Champ_Face_PolyMAC_P0::reprendre(), EDO_Pression_th_VDF_Gaz_Parfait::resoudre(), EDO_Pression_th_VDF_Gaz_Reel::resoudre(), EDO_Pression_th_VEF_Gaz_Parfait::resoudre(), Source_PDF_EF::rotate_imposed_velocity(), Maillage_FT_Disc::sauvegarder(), ParoiVDF_TBLE::sauvegarder(), Paroi_TBLE_scal_VDF::sauvegarder(), ParoiVEF_TBLE::sauvegarder(), ParoiVEF_TBLE_scal::sauvegarder(), Schema_Temps_base::sauvegarder(), Convection_Diffusion_Chaleur_WC::sauvegarder(), Convection_Diffusion_Espece_Binaire_WC::sauvegarder(), Navier_Stokes_FTD_IJK::sauvegarder_equation(), Equation_base::schema_temps(), Probleme_base::schema_temps(), Navier_Stokes_FTD_IJK::schema_temps_ijk(), Probleme_FTD_IJK_base::schema_temps_ijk(), Modele_turbulence_hyd_RANS_Bicephale_base::seconde_equation(), Modele_Fonc_Bas_Reynolds_Base::seconde_equation(), Modele_Fonc_Realisable_base::seconde_equation(), Schema_Comm::set_group(), Maillage_FT_IJK::set_ijk_cell_index(), Schema_Comm::set_send_recv_pe_list(), Conduction::solide(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::stabilise_moyenne_6_points(), Modele_turbulence_scal_LES_dyn_VDF::stabilise_moyenne_6_points(), Modele_turbulence_scal_LES_dyn_VDF::stabilise_moyenne_euler(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::stabilise_moyenne_euler_lagrange(), Modele_turbulence_scal_LES_dyn_VDF::stabilise_moyenne_lagrange(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::stabilise_moyenne_plans_paralleles(), Modele_turbulence_scal_LES_dyn_VDF::stabilise_moyenne_plans_paralleles(), IJK_Interfaces::supprimer_certaines_bulles_reelles(), Remaillage_FT::supprimer_facettes_bord(), Transport_Interfaces_FT_Disc::swap_particles_lagrangian_position_velocity(), Op_Diff_VEFP1NCP1B_Face::test(), Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_elem(), Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_face(), Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_face_sommets(), Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_gradU_elem(), Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_gradU_elem_P1(), Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_gradU_face(), Operateur_Conv::typer(), Operateur_Diff::typer(), Operateur_Div::typer(), Operateur_Evanescence::typer(), Probleme_base::typer_lire_milieu(), Probleme_FT_Disc_gen::typer_lire_milieu(), Pb_Phase_field::typer_lire_milieu(), Pb_Multiphase::typer_lire_milieu(), Loi_paroi_Ramstorfer::u_plus_de_y_plus(), Op_Diff_PolyMAC_P0P1NC_base::update_aux(), Op_Diff_PolyMAC_Elem::update_delta(), Op_Diff_PolyMAC_Elem::update_delta_int(), Eval_Diff_VDF::update_diffusivite(), Eval_Dift_Multiphase_VDF::update_diffusivite_turbulente(), Op_Grad_PolyMAC_P0_Face::update_grad(), Op_Diff_PolyMAC_base::update_nu(), Op_Diff_PolyMAC_P0_base::update_nu(), Op_Diff_PolyMAC_P0P1NC_base::update_nu(), Op_Diff_PolyMAC_P0_base::update_phif(), Tube_libre::update_vitesse_position(), Champ_Fonc_P0_base::valeur_au_bord(), Champ_Elem_DG::valeur_aux(), Champ_Elem_DG::valeur_aux_elems(), Champ_Fonc_P1_DG::valeur_aux_elems(), Champ_Elem_PolyMAC::valeur_aux_faces(), Op_Diff_RotRot::vecteur_normal(), Op_Curl_VEFP1B::vecteur_normal(), Op_Rot_VEFP1B::vecteur_normal(), Source_PDF_EF::verif_ajouter_contrib(), Op_Diff_VEF_Anisotrope_Face::verifier(), Op_Diff_VEF_Face::verifier(), Assembleur_P_VEFPreP1B::verifier_dirichlet(), Champ_front_contact_VEF::verifier_scalaire_bord(), Op_Diff_VEF_base::viscA(), Operateur_Conv_sensibility_VEF::viscA(), Operateur_Conv_sensibility::vitesse(), Op_Conv_EF_base::vitesse(), Op_Conv_negligeable::vitesse(), Operateur_Conv::vitesse(), Eval_Conv_PolyMAC::vitesse(), Fluide_Dilatable_base::vitesse(), Courant_maille_Champ_Face::vitesse(), Reynolds_maille_Champ_Face::vitesse(), Eval_Conv_VDF::vitesse(), Op_Conv_VEF_base::vitesse(), Convection_Diffusion_std::vitesse_transportante(), Iterateur_Source_VEF_Face< _TYPE_ >::volumes_entrelaces(), Op_Div_EF::volumique(), Op_Div_PolyMAC::volumique(), Op_Div_VDF_Elem::volumique(), Op_Div_VEFP1B_Elem::volumique(), and Champ_Input_Proto::z_probleme().
valeur() [2/2]
template<typename _CLASSE_ > value_type & TRUST_Ref< _CLASSE_ >::valeur () inline
operator->() [1/2]
template<typename _CLASSE_ > const value_type * TRUST_Ref< _CLASSE_ >::operator-> () const inline
operator->() [2/2]
template<typename _CLASSE_ > value_type * TRUST_Ref< _CLASSE_ >::operator-> () inline
non_nul()
template<typename _CLASSE_ > bool TRUST_Ref< _CLASSE_ >::non_nul () const inline
Referenced by Milieu_base::a_gravite(), Debog::active(), Op_Grad_VDF_Face::ajouter_blocs(), Op_Diff_PolyMAC_P0_Face::ajouter_blocs(), Op_Grad_PolyMAC_P0_Face::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::ajouter_blocs(), Op_Diff_PolyMAC_P0P1NC_Elem::ajouter_blocs_ext(), Op_Diff_PolyMAC_P0P1NC_Face::ajouter_blocs_ext(), Masse_PolyMAC_Face::appliquer_impl(), Masse_VDF_Face::appliquer_impl(), Op_Conv_VDF_base::associer_champ_convecte_elem(), Op_Conv_VDF_base::associer_champ_convecte_face(), Op_Diff_K_Omega_VDF_base::associer_diffusivite_turbulente(), Op_Diff_K_Eps_Bas_Re_VDF_base::associer_diffusivite_turbulente_impl(), Parcours_interface::associer_domaine_dis(), Milieu_base::associer_gravite(), Op_Correlation::associer_op_stat(), Transport_Interfaces_FT_Disc::associer_pb_base(), Probleme_base::associer_sch_tps_base(), Pb_Couple_rayo_semi_transp::associer_sch_tps_base(), Schema_Comm::begin_comm(), Maillage_FT_Disc::calcul_courbure_sommets(), Op_Conv_PolyMAC_iterateur_base::calculer_dt_stab(), Op_Conv_VDF_base::calculer_dt_stab(), Probleme_FT_Disc_gen::calculer_pas_de_temps(), Op_Conv_VEF_base::calculer_pour_post(), Op_Diff_VEF_base::calculer_pour_post(), Op_Dift_VEF_base::calculer_pour_post(), Sortie_libre_Gradient_Pression_impose_VEFPreP1B::calculer_trace_pression(), Operateur::completer(), Operateur_base::completer(), Correction_Lubchenko_PolyMAC_P0::completer(), Probleme_FT_Disc_gen::completer(), Op_Diff_PolyMAC_P0_Face::completer(), Op_Diff_PolyMAC_P0P1NC_Elem::completer(), Op_Diff_PolyMAC_P0P1NC_Face::completer(), Op_Diff_VDF_base::completer(), Op_Ecart_type::completer(), Convection_Diffusion_Concentration::constituant(), Marching_Cubes::construire_iso(), Connectivite_frontieres::def_face_aretes(), Operateur_Diff_base::diffusivite_pour_pas_de_temps(), Op_Grad_VDF_Face::dimensionner_blocs(), Op_Grad_PolyMAC_P0_Face::dimensionner_blocs(), Op_Diff_PolyMAC_P0P1NC_Elem::dimensionner_blocs_ext(), Op_Diff_PolyMAC_P0P1NC_Face::dimensionner_blocs_ext(), Equation_base::discretisation(), Probleme_base::discretisation(), Convection_Diffusion_Concentration::discretiser(), Milieu_base::discretiser_diametre_hydro(), Milieu_base::discretiser_porosite(), Champ_Inc_base::domaine_Cl_dis(), Equation_base::domaine_dis(), Champ_Fonc_base::domaine_dis_base(), Champ_Fonc_base::domaine_vf(), Schema_Comm::echange_messages(), Schema_Comm::echange_taille(), Format_Post_Med::ecrire_champ_med(), Format_Post_Med::ecrire_domaine_dual(), Format_Post_Med::ecrire_domaine_med(), Schema_Comm::end_comm(), Modele_turbulence_scal_base::equation(), Modele_Fonc_Bas_Reynolds_Base::equation(), Assembleur_P_EF::equation(), Champ_front_calc::equation(), MorEqn::equation(), Assembleur_P_VEFPreP1B::equation(), Connectivite_frontieres::faces_voisins(), Transport_Interfaces_FT_Disc::fill_ftab_local_reference_frame_velocity(), Transport_Interfaces_FT_Disc::fill_ftab_velocity(), Convection_Diffusion_Fluide_Dilatable_base::fluide(), Masse_Multiphase::fluide(), Support_Champ_Masse_Volumique::get_champ_masse_volumique(), Eval_Diff_VDF::get_diffusivite(), Schema_Comm::get_group(), PE_Groups::get_node_group(), PE_Groups::get_node_master(), Schema_Comm::get_recv_pe_list(), Champ_Generique_refChamp::get_ref_champ_base(), Schema_Comm::get_send_pe_list(), Milieu_base::gravite(), Operateur_base::has_champ_inco(), Support_Champ_Masse_Volumique::has_champ_masse_volumique(), Op_Diff_Turbulent_base::has_diffusivite_turbulente(), Modele_Fonc_Bas_Reynolds_Base::has_seconde_equation(), Modele_Fonc_Realisable_base::has_seconde_equation(), Postraitement::init(), Echange_contact_PolyMAC_P0::init_op(), Echange_contact_PolyMAC_P0P1NC::init_op(), Milieu_base::initialiser(), Triple_Line_Model_FT_Disc::initialize(), IJK_Thermal_base::initialize(), IJK_Thermal_Onefluid::initialize(), Interprete_bloc::Interprete_bloc(), Interprete_bloc::interpreter_bloc(), Probleme_base::is_coupled(), Ensemble_Faces_base::is_ok(), Pb_Couple_rayo_semi_transp::le_modele_rayo_associe(), Postraitement_ft_lata::lire_entete_bloc_interface(), Convection_Diffusion_Temperature_FT_Disc::lire_motcle_non_standard(), Milieu_base::mettre_a_jour(), Probleme_FT_Disc_gen::mettre_a_jour(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::mettre_a_jour(), Sortie_libre_Gradient_Pression_libre_VEF::mettre_a_jour(), Sortie_libre_Gradient_Pression_impose::mettre_a_jour(), Sortie_libre_Pression_imposee_Orlansky::mettre_a_jour(), Op_Conv_VDF_base::mettre_a_jour(), Op_Diff_K_Eps_VDF_base::mettre_a_jour_diffusivite(), Op_Diff_K_Omega_VDF_base::mettre_a_jour_diffusivite(), Equation_rayonnement_base::milieu(), Transport_Fluctuation_Temperature::milieu(), Transport_Fluctuation_Temperature_W::milieu(), Transport_Fluctuation_Temperature_W_Bas_Re::milieu(), Transport_Flux_Chaleur_Turbulente::milieu(), Convection_Diffusion_Temperature_FT_Disc::milieu(), Transport_Interfaces_FT_Disc::milieu(), Transport_2eq_base::milieu(), Cond_Lim_rayo_semi_transp::modele(), Transport_Fluctuation_Temperature_W_Bas_Re::modele_turbulence(), Transport_2eq_base::modele_turbulence(), Transport_Fluctuation_Temperature::modele_turbulence(), Transport_Fluctuation_Temperature_W::modele_turbulence(), Transport_Flux_Chaleur_Turbulente::modele_turbulence(), Modele_Fonc_Bas_Reynolds_Thermique_Base::modele_turbulence_Bas_Re(), MorEqn::mon_equation_non_nul(), Sonde::ouvrir_fichier(), Parcours_interface::parcourir(), Postraitement_ft_lata::postprocess_field_values(), Probleme_base::postraiter(), Postraitement::postraiter_champs(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::preparer_calcul(), Nucleation_paroi_PolyMAC_P0::readOn(), Convection_diffusion_turbulence_multiphase::readOn(), Energie_cinetique_turbulente_WIT::readOn(), Parcours_interface::readOn(), Domaine_Cl_dis_base::readOn(), Postraitement::readOn(), Sonde::readOn(), Sonde_Int::readOn(), Sondes::readOn(), Sondes_Int::readOn(), Convection_Diffusion_Fluide_Dilatable_base::readOn(), Navier_Stokes_QC::readOn(), Navier_Stokes_WC::readOn(), Convection_Diffusion_Temperature::readOn(), Aire_interfaciale::readOn(), Energie_Multiphase::readOn(), Masse_Multiphase::readOn(), QDM_Multiphase::readOn(), Navier_Stokes_Turbulent_QC::readOn(), Schema_Comm::recv_buffer(), Maillage_FT_Disc::reprendre(), ParoiVDF_TBLE::reprendre(), Paroi_TBLE_scal_VDF::reprendre(), ParoiVEF_TBLE::reprendre(), ParoiVEF_TBLE_scal::reprendre(), Champ_Elem_PolyMAC_P0::reprendre(), Champ_Face_PolyMAC_P0::reprendre(), Modele_turbulence_scal_Fluctuation_Temperature::reprendre(), Modele_turbulence_scal_Fluctuation_Temperature_W::reprendre(), Modele_turbulence_hyd_RANS_Bicephale_base::reprendre(), Modele_turbulence_hyd_RANS_K_Eps_base::reprendre(), Modele_turbulence_hyd_RANS_K_Omega_base::reprendre(), Operateurs_Statistique_tps::reprendre(), Ch_front_Vortex::reprendre_vortex(), Ch_front_Vortex::sauvegarder_vortex(), Equation_base::schema_temps(), Probleme_base::schema_temps(), Modele_Fonc_Bas_Reynolds_Base::seconde_equation(), Modele_Fonc_Realisable_base::seconde_equation(), Schema_Comm::send_buffer(), Sondes::set_noms_champs_postraitables(), Champ_Generique_refChamp::set_ref_champ(), Conduction::solide(), Operateur_Diff::typer(), Op_Diff_PolyMAC_P0P1NC_base::update_aux(), Eval_Dift_VDF::update_equivalent_distance(), Op_Grad_PolyMAC_P0_Face::update_grad(), Champ_Inc_P0_base::valeur_au_bord(), and Postraitement_ft_lata::write_extra_mesh().
est_nul()
template<typename _CLASSE_ > bool TRUST_Ref< _CLASSE_ >::est_nul () const inline
Referenced by Fluide_Dilatable_base::completer(), Fluide_Dilatable_base::discretiser(), Modele_turbulence_hyd_base::equation(), Champ_front_contact_VEF::equation(), Assembleur_P_VEF::equation(), Convection_Diffusion_Fluide_Dilatable_base::fluide(), Convection_Diffusion_Temperature_base::fluide(), Masse_Multiphase::fluide(), Champ_Generique_Interpolation::get_ref_domaine_dis_base(), Eval_Dift_VDF_Elem::init_ind_fluctu_term(), PE_Groups::initialize_node(), PE_Groups::initialize_node_master(), Champ_front_contact_fictif_VEF::mettre_a_jour(), Champ_front_contact_VEF::mettre_a_jour(), IJK_Thermal_base::milieu(), IJK_Thermals::milieu(), Navier_Stokes_FTD_IJK::milieu(), Navier_Stokes_std::milieu(), Modele_turbulence_hyd_RANS_Bicephale_base::seconde_equation(), Conduction::solide(), Champ_Face_PolyMAC::valeur_aux_elems_(), Champ_Face_PolyMAC::valeur_aux_elems_compo(), and Ecrire_fichier_xyz_valeur::write_fields().
le_nom()
template<typename _CLASSE_ > const Nom & TRUST_Ref< _CLASSE_ >::le_nom () const delete
Referenced by Couplage_Parietal_PolyMAC_helper::ajouter_blocs(), Solveur_Masse_Face_proto::ajouter_blocs_proto(), Op_Conv_EF::ajouter_contribution_sous_cond(), Solveur_Masse_Elem_proto::appliquer_impl_proto(), Probleme_base::associer_sch_tps_base(), Op_Conv_EF::calculer_dt_stab(), Paroi_contact::complement(), Paroi_contact_fictif::complement(), Paroi_contact_rayo::complement(), Equation_base::completer(), Sonde::completer(), Source_Masse_Fluide_Dilatable_base::completer(), Echange_contact_VDF_FT_Disc::completer(), Sonde::create_champ_generique(), Postraitement::creer_champ_post(), Postraitement::creer_champ_post_moreqn(), Couplage_Parietal_PolyMAC_helper::dimensionner_blocs(), Solveur_Masse_Face_proto::dimensionner_blocs_proto(), Champ_Generique_refChamp_special::get_champ(), Champ_Generique_Morceau_Equation::get_property(), Traitement_particulier_NS_CEG::imprimer(), Echange_contact_PolyMAC_P0P1NC::init_f_dist(), Echange_contact_PolyMAC_P0::init_fs_dist(), Echange_contact_PolyMAC_P0::init_op(), Echange_contact_PolyMAC_P0P1NC::init_op(), Sonde::initialiser(), Champ_Fonc_Tabule_Morceaux_Interp::initialiser(), Loi_Etat_GR_base::initialiser_inco_ch(), Equation_IBM_proto::initTimeStep_ibm_proto(), Postraitement_ft_lata::lire_entete_bloc_interface(), Save_Restart::lire_sauvegarde_reprise(), Echange_contact_VDF_FT_Disc::mettre_a_jour(), Echange_contact_VDF_FT_Disc_solid::mettre_a_jour(), IJK_Thermal_base::milieu(), Champ_Generique_Morceau_Equation::nommer_source(), Operateur_Conv::readOn(), Terme_Source_Solide_SWIFT_VDF::readOn(), Equation_IBM_proto::readOn_ibm_proto(), Save_Restart::sauver(), Save_Restart::sauver_xyz(), Champ_input_P0::setValue(), Champ_Input_Proto::setValueOnTab(), Champ_front_contact_VEF::test_faces_coin(), and Champ_Fonc_Interp::update_fields().
reset()
template<typename _CLASSE_ > void TRUST_Ref< _CLASSE_ >::reset () inline
Referenced by PE_Groups::finalize(), Postraitement_ft_lata::lire_motcle_non_standard(), Champ_Generique_Champ::lire_motcle_non_standard(), and Champ_Generique_refChamp::reset().
Member Data Documentation
HAS_POINTER
template<typename _CLASSE_ > constexpr bool TRUST_Ref< _CLASSE_ >::HAS_POINTER = true static constexpr