TrioCFD: Flux_interfacial_Zeitoun Class Reference
Flux_interfacial_Zeitoun Class Reference
#include <Flux_interfacial_Zeitoun.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Flux_interfacial_Zeitoun()
Flux_interfacial_Zeitoun::Flux_interfacial_Zeitoun ()
~Flux_interfacial_Zeitoun()
Flux_interfacial_Zeitoun::~Flux_interfacial_Zeitoun ()
Member Function Documentation
cree_instance()
Objet_U * Flux_interfacial_Zeitoun::cree_instance () static
taille_memoire()
unsigned Flux_interfacial_Zeitoun::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Flux_interfacial_Zeitoun::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Flux_interfacial_Zeitoun::info () static
get_info()
const Type_info * Flux_interfacial_Zeitoun::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Flux_interfacial_base.
self_cast() [1/2]
Flux_interfacial_Zeitoun & Flux_interfacial_Zeitoun::self_cast (Objet_U & r) static
self_cast() [2/2]
const Flux_interfacial_Zeitoun & Flux_interfacial_Zeitoun::self_cast (const Objet_U & r) static
printOn()
Sortie & Flux_interfacial_Zeitoun::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Flux_interfacial_base.
readOn()
Entree & Flux_interfacial_Zeitoun::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Flux_interfacial_base.
References Param::ajouter(), Flux_interfacial_base::dv_min_, Param::lire_avec_accolades_depuis(), and Objet_U::que_suis_je().
coeffs()
void Flux_interfacial_Zeitoun::coeffs (const input_t & in, output_t & out) const override virtual
Implements Flux_interfacial_base.
References a_min, a_min_coeff, a_res_, Flux_interfacial_base::input_t::alpha, Flux_interfacial_base::input_t::Cp, Flux_interfacial_base::input_t::d_bulles, Flux_interfacial_base::output_t::da_hi, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Flux_interfacial_base::output_t::dp_hi, Flux_interfacial_base::input_t::dP_Lvap, Flux_interfacial_base::output_t::dT_hi, Flux_interfacial_base::output_t::hi, Flux_interfacial_base::input_t::lambda, Flux_interfacial_base::input_t::Lvap, Flux_interfacial_base::input_t::mu, n_l, Flux_interfacial_base::input_t::nv, Flux_interfacial_base::input_t::rho, and Flux_interfacial_base::input_t::T.
completer()
void Flux_interfacial_Zeitoun::completer () override virtual
Reimplemented from Correlation_base.
References a_res_, Nom::debute_par(), Process::exit(), Probleme_base::has_champ(), n_l, Pb_Multiphase::nb_phases(), Pb_Multiphase::nom_phase(), Correlation_base::pb_, Objet_U::que_suis_je(), and TRUST_Ref< _CLASSE_ >::valeur().
Member Data Documentation
info_obj
const Type_info Flux_interfacial_Zeitoun::info_obj static
n_l
int Flux_interfacial_Zeitoun::n_l = -1 protected
Referenced by coeffs(), and completer().
a_min_coeff
double Flux_interfacial_Zeitoun::a_min_coeff = 1.e-1 protected
Referenced by coeffs().
a_min
double Flux_interfacial_Zeitoun::a_min = 1.e-2 protected
Referenced by coeffs().
a_res_
double Flux_interfacial_Zeitoun::a_res_ = -1. protected
Referenced by coeffs(), and completer().