TrioCFD: Cut_cell_surface_efficace Class Reference
Cut_cell_surface_efficace Class Reference
#include <Cut_cell_surface_efficace.h>
Member Function Documentation
calcul_surface_interface_efficace_initiale()
void Cut_cell_surface_efficace::calcul_surface_interface_efficace_initiale (int methode_explicite, const IJK_Field_double & old_indicatrice_ns, const IJK_Field_double & next_indicatrice_ns, const IJK_Field_double & surface_interface_ns_old, const IJK_Field_double & surface_interface_ns_next, const IJK_Field_vector3_double & normal_of_interf_ns_old, const IJK_Field_vector3_double & normal_of_interf_ns_next, DoubleTabFT_cut_cell_vector3 & normale_deplacement_interface, DoubleTabFT_cut_cell_scalar & surface_efficace_interface, DoubleTabFT_cut_cell_scalar & surface_efficace_interface_initial) static
References IJK_Interfaces::devient_diphasique(), IJK_Interfaces::devient_pure(), IJK_Interfaces::est_pure(), TRUSTTabFT_cut_cell< _TYPE_ >::get_cut_cell_disc(), Cut_cell_FT_Disc::get_ijk(), and Cut_cell_FT_Disc::get_n_tot().
Referenced by IJK_Interfaces::calcul_surface_efficace_interface(), and IJK_Interfaces::calcul_surface_efficace_interface_initial().
calcul_vitesse_interface()
void Cut_cell_surface_efficace::calcul_vitesse_interface (const IJK_Field_vector3_double & velocity, const IJK_Field_double & old_indicatrice_ns, const IJK_Field_double & next_indicatrice_ns, const IJK_Field_vector3_double & barycentre_phase1_ns_old, const IJK_Field_vector3_double & barycentre_phase1_ns_next, DoubleTabFT_cut_cell_vector3 & coord_deplacement_interface, DoubleTabFT_cut_cell_vector3 & vitesse_deplacement_interface) static
References TRUSTTabFT_cut_cell< _TYPE_ >::echange_espace_virtuel(), Domaine_IJK::get_constant_delta(), TRUSTTabFT_cut_cell< _TYPE_ >::get_cut_cell_disc(), Cut_cell_FT_Disc::get_domaine(), Cut_cell_FT_Disc::get_ijk(), Cut_cell_FT_Disc::get_n_loc(), Domaine_IJK::get_offset_local(), and Domaine_IJK::get_origin().
calcul_surface_interface_efficace()
void Cut_cell_surface_efficace::calcul_surface_interface_efficace (double timestep, const IJK_Field_vector3_double & velocity, const IJK_Field_double & old_indicatrice_ns, const IJK_Field_double & next_indicatrice_ns, const DoubleTabFT_cut_cell_vector3 & vitesse_deplacement_interface, const DoubleTabFT_cut_cell_vector3 & normale_deplacement_interface, DoubleTabFT_cut_cell_scalar & surface_efficace_interface) static
References Statistiques::begin_count(), TRUSTTabFT_cut_cell< _TYPE_ >::echange_espace_virtuel(), Statistiques::end_count(), Domaine_IJK::get_constant_delta(), TRUSTTabFT_cut_cell< _TYPE_ >::get_cut_cell_disc(), Domaine_IJK::get_delta(), Cut_cell_FT_Disc::get_domaine(), Cut_cell_FT_Disc::get_ijk(), Cut_cell_FT_Disc::get_n_loc(), Domaine_IJK::get_offset_local(), and Statistiques::new_counter().
calcul_surface_face_efficace_initiale() [1/2]
void Cut_cell_surface_efficace::calcul_surface_face_efficace_initiale (int methode_explicite, const IJK_Field_vector3_double & old_indicatrice_surfacique_face_ns, const IJK_Field_vector3_double & next_indicatrice_surfacique_face_ns, DoubleTabFT_cut_cell_vector3 & indicatrice_surfacique_efficace_face, DoubleTabFT_cut_cell_vector3 & indicatrice_surfacique_efficace_face_initial) static
References IJK_Interfaces::devient_diphasique(), IJK_Interfaces::devient_pure(), TRUSTTabFT_cut_cell< _TYPE_ >::get_cut_cell_disc(), Cut_cell_FT_Disc::get_ijk(), and Cut_cell_FT_Disc::get_n_tot().
Referenced by IJK_Interfaces::calcul_surface_efficace_face_initial(), and IJK_Interfaces::calculer_var_volume_remaillage().
calcul_surface_face_efficace_initiale() [2/2]
void Cut_cell_surface_efficace::calcul_surface_face_efficace_initiale (int methode_explicite, const IJK_Field_vector3_double & old_indicatrice_surfacique_face_ns, const IJK_Field_vector3_double & next_indicatrice_surfacique_face_ns, IJK_Field_vector3_double & indicatrice_surfacique_efficace_face, IJK_Field_vector3_double & indicatrice_surfacique_efficace_face_initial) static
References IJK_Interfaces::devient_diphasique(), and IJK_Interfaces::devient_pure().
calcul_surface_face_efficace_iteratif()
void Cut_cell_surface_efficace::calcul_surface_face_efficace_iteratif (int verbosite_surface_efficace_face, double timestep, const Cut_field_vector3_double & velocity, int & iteration_solver_surface_efficace_face, const IJK_Field_double & old_indicatrice_ns, const IJK_Field_double & next_indicatrice_ns, const IJK_Field_vector3_double & old_indicatrice_surfacique_face_ns, const IJK_Field_vector3_double & next_indicatrice_surfacique_face_ns, DoubleTabFT_cut_cell_vector3 & indicatrice_surfacique_efficace_face, const DoubleTabFT_cut_cell_vector3 & indicatrice_surfacique_efficace_face_initial, DoubleTabFT_cut_cell_vector6 & indicatrice_surfacique_efficace_face_correction, DoubleTabFT_cut_cell_scalar & indicatrice_surfacique_efficace_face_absolute_error) static
References Statistiques::begin_count(), IJK_Interfaces::devient_diphasique(), IJK_Interfaces::devient_pure(), TRUSTTabFT_cut_cell< _TYPE_ >::echange_espace_virtuel(), Statistiques::end_count(), Domaine_IJK::get_constant_delta(), TRUSTTabFT_cut_cell< _TYPE_ >::get_cut_cell_disc(), Domaine_IJK::get_delta(), Cut_cell_FT_Disc::get_domaine(), Cut_cell_FT_Disc::get_ijk(), Cut_cell_FT_Disc::get_n(), Cut_cell_FT_Disc::get_n_face(), Cut_cell_FT_Disc::get_n_loc(), Domaine_IJK::get_offset_local(), imprimer_informations_surface_efficace_face(), Process::mp_max(), and Statistiques::new_counter().
imprimer_informations_surface_efficace_interface()
void Cut_cell_surface_efficace::imprimer_informations_surface_efficace_interface (int verbosite_surface_efficace_interface, double timestep, const IJK_Field_vector3_double & velocity, const IJK_Field_double & old_indicatrice_ns, const IJK_Field_double & next_indicatrice_ns, const DoubleTabFT_cut_cell_scalar & surface_efficace_interface, const DoubleTabFT_cut_cell_scalar & surface_efficace_interface_initial, const DoubleTabFT_cut_cell_vector3 & normale_deplacement_interface, const DoubleTabFT_cut_cell_vector3 & vitesse_deplacement_interface) static
References Process::check_int_overflow(), IJK_Interfaces::devient_diphasique(), IJK_Interfaces::devient_pure(), IJK_Interfaces::est_pure(), Process::exit(), Domaine_IJK::get_constant_delta(), TRUSTTabFT_cut_cell< _TYPE_ >::get_cut_cell_disc(), Domaine_IJK::get_delta(), Cut_cell_FT_Disc::get_domaine(), Cut_cell_FT_Disc::get_ijk(), Cut_cell_FT_Disc::get_n_loc(), Domaine_IJK::get_offset_local(), Process::mp_max(), and Process::mp_sum().
imprimer_informations_surface_efficace_face()
void Cut_cell_surface_efficace::imprimer_informations_surface_efficace_face (int verbosite_surface_efficace_face, int iteration_solver_surface_efficace_face, double timestep, const Cut_field_vector3_double & velocity, const IJK_Field_double & old_indicatrice_ns, const IJK_Field_double & next_indicatrice_ns, const DoubleTabFT_cut_cell_vector3 & indicatrice_surfacique_efficace_face, const DoubleTabFT_cut_cell_vector3 & indicatrice_surfacique_efficace_face_initial) static
References Process::check_int_overflow(), IJK_Interfaces::devient_diphasique(), IJK_Interfaces::devient_pure(), IJK_Interfaces::est_pure(), Process::exit(), Domaine_IJK::get_constant_delta(), TRUSTTabFT_cut_cell< _TYPE_ >::get_cut_cell_disc(), Domaine_IJK::get_delta(), Cut_cell_FT_Disc::get_domaine(), Cut_cell_FT_Disc::get_ijk(), Cut_cell_FT_Disc::get_n_face(), Cut_cell_FT_Disc::get_n_loc(), Domaine_IJK::get_offset_local(), Process::mp_max(), and Process::mp_sum().
Referenced by calcul_surface_face_efficace_iteratif().
calcul_delta_volume_theorique_bilan()
void Cut_cell_surface_efficace::calcul_delta_volume_theorique_bilan (int compo, const DoubleTab & bounding_box_bulles, double timestep, const IJK_Field_double & indicatrice_avant_deformation, const IJK_Field_double & indicatrice_apres_deformation, const IJK_Field_vector3_double & indicatrice_surfacique_efficace_deformation_face, const Cut_field_vector3_double & deformation_velocity, IJK_Field_double & delta_volume_theorique_bilan) static
References IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel(), Domaine_IJK::get_constant_delta(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_domaine(), Cut_cell_FT_Disc::get_n(), Cut_cell_FT_Disc::get_n_face(), Domaine_IJK::get_offset_local(), Domaine_IJK::get_origin(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost(), Domaine_IJK::is_uniform(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), and IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk().
Referenced by IJK_Interfaces::calculer_var_volume_remaillage().