TrioCFD: Polygone_32_64< _SIZE_ > Class Template Reference
Polygone_32_64< _SIZE_ > Class Template Reference
#include <Polygone.h>
Public Member Functions
void calculer_centres_gravite (DoubleTab_t &xp) const override
void calculer_volumes (DoubleVect_t &vols) const override
int contient (const ArrOfDouble &pos, int_t elem) const override
int contient (const SmallArrOfTID_t &soms, int_t elem) const override
int face_sommet (int i, int j) const override
const Type_info * get_info () const override
int get_tab_faces_sommets_locaux (IntTab &faces_som_local) const override
int nb_faces (int=0) const override
int nb_som () const override
int nb_som_face (int=0) const override
const Nom & nom_lml () const override
Type_Face type_face (int=0) const override
Public Member Functions inherited from Poly_geom_base_32_64< _SIZE_ >
const Type_info * get_info () const override
int get_tab_faces_sommets_locaux (IntTab &faces_som_local) const override=0
int nb_type_face () const override
Public Member Functions inherited from Elem_geom_base_32_64< _SIZE_ >
virtual void calculer_centres_gravite (DoubleTab_t &) const
virtual void calculer_normales (const IntTab_t &faces_sommets, DoubleTab_t &face_normales) const
void creer_faces_elem (Faces_t &, int_t) const
virtual void creer_faces_elem (Faces_t &, int_t, Type_Face) const
const Type_info * get_info () const override
virtual void get_tab_aretes_sommets_locaux (IntTab &aretes_som_local) const
virtual int get_tab_faces_sommets_locaux (IntTab &faces_som_local) const
virtual int nb_type_face () const
virtual int num_face (int face, Type_Face &type) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Attributes
ArrOfInt_t PolygonIndex_
Protected Attributes inherited from Poly_geom_base_32_64< _SIZE_ >
ArrOfInt_t FacesIndex_
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
template<typename _SIZE_>
class Polygone_32_64< _SIZE_ >
Un polyedre est un element defini par ses faces de type Type_Face::polygone_3D
See also
Poly_geom_base Elem_geom
Member Typedef Documentation
int_t
template<typename _SIZE_ > using Polygone_32_64< _SIZE_ >::int_t = _SIZE_
ArrOfInt_t
template<typename _SIZE_ > using Polygone_32_64< _SIZE_ >::ArrOfInt_t = ArrOfInt_T<_SIZE_>
IntTab_t
template<typename _SIZE_ > using Polygone_32_64< _SIZE_ >::IntTab_t = IntTab_T<_SIZE_>
SmallArrOfTID_t
template<typename _SIZE_ > using Polygone_32_64< _SIZE_ >::SmallArrOfTID_t = SmallArrOfTID_T<_SIZE_>
DoubleVect_t
template<typename _SIZE_ > using Polygone_32_64< _SIZE_ >::DoubleVect_t = DoubleVect_T<_SIZE_>
DoubleTab_t
template<typename _SIZE_ > using Polygone_32_64< _SIZE_ >::DoubleTab_t = DoubleTab_T<_SIZE_>
Domaine_t
template<typename _SIZE_ > using Polygone_32_64< _SIZE_ >::Domaine_t = Domaine_32_64<_SIZE_>
Constructor & Destructor Documentation
Polygone_32_64()
template<typename _SIZE_ > Polygone_32_64< _SIZE_ >::Polygone_32_64
References Poly_geom_base_32_64< _SIZE_ >::FacesIndex_, Poly_geom_base_32_64< _SIZE_ >::nb_face_elem_max_, Poly_geom_base_32_64< _SIZE_ >::nb_som_elem_max_, Polygone_32_64< _SIZE_ >::PolygonIndex_, and TRUSTArray< _TYPE_, _SIZE_ >::resize().
~Polygone_32_64()
template<typename _T_ > Polygone_32_64< _T_ >::~Polygone_32_64
Member Function Documentation
cree_instance()
template<typename _T_ > Objet_U * Polygone_32_64< _T_ >::cree_instance static
taille_memoire()
template<typename _T_ > unsigned Polygone_32_64< _T_ >::taille_memoire override virtual
Implements Objet_U.
duplique()
template<typename _T_ > int Polygone_32_64< _T_ >::duplique override virtual
Implements Objet_U.
info()
template<typename _T_ > const Type_info * Polygone_32_64< _T_ >::info static
get_info()
template<typename _T_ > const Type_info * Polygone_32_64< _T_ >::get_info override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Poly_geom_base_32_64< _SIZE_ >.
self_cast() [1/2]
template<typename _T_ > Polygone_32_64< _T_ > & Polygone_32_64< _T_ >::self_cast (Objet_U & r) static
self_cast() [2/2]
template<typename _T_ > const Polygone_32_64< _T_ > & Polygone_32_64< _T_ >::self_cast (const Objet_U & r) static
printOn()
template<typename _SIZE_ > Sortie & Polygone_32_64< _SIZE_ >::printOn (Sortie & s) const override protected virtual
NE FAIT RIEN.
Parameters
(Sortie& s) un flot de sortie
Returns
(Sortie&) le flot de sortie
Reimplemented from Poly_geom_base_32_64< _SIZE_ >.
readOn()
template<typename _SIZE_ > Entree & Polygone_32_64< _SIZE_ >::readOn (Entree & s) override protected virtual
NE FAIT RIEN.
Parameters
(Entree& s) un flot d'entree
Returns
(Entree&) le flot d'entree
Reimplemented from Poly_geom_base_32_64< _SIZE_ >.
face_sommet()
template<typename _SIZE_ > int Polygone_32_64< _SIZE_ >::face_sommet (int face, int sommet) const inline override virtual
Renvoie le numero du j-ieme sommet de la i-ieme face de l'element.
Parameters
(int i) un numero de face
(int j) un numero de sommet
Returns
(int) le numero du j-ieme sommet de la i-ieme face
Implements Elem_geom_base_32_64< _SIZE_ >.
nb_som()
template<typename _SIZE_ > int Polygone_32_64< _SIZE_ >::nb_som inline override virtual
Renvoie le nombre de sommets d'un Polygone.
Returns
(int) le nombre de sommets maximum d'un polyedre
Implements Elem_geom_base_32_64< _SIZE_ >.
References Polygone_32_64< _SIZE_ >::get_nb_som_elem_max().
nb_faces()
template<typename _SIZE_ > int Polygone_32_64< _SIZE_ >::nb_faces (int i = 0) const inline override virtual
Renvoie le nombre de faces du type specifie que possede l'element geometrique.
Un Polygone a 1 type de faces: polygon_3D
Parameters
(int i) le type de face
Implements Elem_geom_base_32_64< _SIZE_ >.
References Process::exit(), and Polygone_32_64< _SIZE_ >::get_nb_face_elem_max().
nb_som_face()
template<typename _SIZE_ > int Polygone_32_64< _SIZE_ >::nb_som_face (int i = 0) const inline override virtual
Renvoie le nombre maximum de sommets des faces du type specifie.
Parameters
(int i) le type de face
Returns
(int) le nombre de sommets des faces de type i
Implements Elem_geom_base_32_64< _SIZE_ >.
nom_lml()
template<typename _SIZE_ > const Nom & Polygone_32_64< _SIZE_ >::nom_lml override virtual
Renvoie le nom LML d'un polyedre = "POLYEDRE_"+nb_som_max.
Returns
(Nom&) toujours egal a "PRISM6"
Implements Elem_geom_base_32_64< _SIZE_ >.
contient() [1/2]
template<typename _SIZE_ > int Polygone_32_64< _SIZE_ >::contient (const ArrOfDouble & pos_r, int_t num_poly) const override virtual
NE FAIT RIEN: A CODER, renvoie toujours 0.
Renvoie 1 si l'element "element" du domaine associe a l'element geometrique contient le point de coordonnees specifiees par le parametre "pos". Renvoie 0 sinon.
Parameters
(DoubleVect& pos) coordonnees du point que l'on cherche a localiser
(int element) le numero de l'element du domaine dans lequel on cherche le point.
Returns
(int) 1 si le point de coordonnees specifiees appartient a l'element "element" 0 sinon
Implements Elem_geom_base_32_64< _SIZE_ >.
contient() [2/2]
template<typename _SIZE_ > int Polygone_32_64< _SIZE_ >::contient (const SmallArrOfTID_t & pos, int_t element) const override virtual
NE FAIT RIEN: A CODER, renvoie toujours 0 Renvoie 1 si les sommets specifies par le parametre "pos".
sont les sommets de l'element "element" du domaine associe a l'element geometrique.
Parameters
(IntVect& pos) les numeros des sommets a comparer avec ceux de l'elements "element"
(int element) le numero de l'element du domaine dont on veut comparer les sommets
Returns
(int) 1 si les sommets passes en parametre sont ceux de l'element specifie, 0 sinon
Implements Elem_geom_base_32_64< _SIZE_ >.
type_face()
template<typename _SIZE_ > Type_Face Polygone_32_64< _SIZE_ >::type_face (int i = 0) const inline override virtual
Renvoie le i-ieme type de face.
Un polyedre a 2 types de face: quadrangle et triangle
Parameters
(int i) le rang du type de face a renvoyer
Returns
(Type_Face) le type de la face i
Implements Elem_geom_base_32_64< _SIZE_ >.
calculer_volumes()
template<typename _SIZE_ > void Polygone_32_64< _SIZE_ >::calculer_volumes (DoubleVect_t & volumes) const override virtual
NE FAIT RIEN: A CODER Calcule les volumes des elements du domaine associe.
Parameters
(DoubleVect& volumes) le vecteur contenant les valeurs des des volumes des elements du domaine
Implements Elem_geom_base_32_64< _SIZE_ >.
References TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), and TRUSTVect< _TYPE_, _SIZE_ >::size_totale().
calculer_centres_gravite()
template<typename _SIZE_ > void Polygone_32_64< _SIZE_ >::calculer_centres_gravite (DoubleTab_t & tab_xp) const override virtual
Compute all centers of mass of all elements in the domain.
Calcule les centres de gravites de tous les elements du domaine associe a l'element goemetrique.
Parameters
(DoubleTab& xp) le tableau contenant les coordonnees des centres de gravite
Reimplemented from Elem_geom_base_32_64< _SIZE_ >.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), and TRUSTTab< _TYPE_, _SIZE_ >::resize().
calculer_un_centre_gravite()
template<typename _SIZE_ > void Polygone_32_64< _SIZE_ >::calculer_un_centre_gravite (const int_t elem, DoubleVect & xp) const override virtual
Implements Poly_geom_base_32_64< _SIZE_ >.
References TRUSTVect< _TYPE_, _SIZE_ >::resize().
get_tab_faces_sommets_locaux() [1/2]
template<typename _SIZE_ > int Polygone_32_64< _SIZE_ >::get_tab_faces_sommets_locaux (IntTab & faces_som_local) const override virtual
remplit le tableau faces_som_local(i,j)
Celui-ci donne pour 0 <= i < nb_faces() et 0 <= j < nb_som_face(i) le numero local du sommet sur l'element.
On a 0 <= faces_sommets_locaux(i,j) < nb_som()
Si toutes les faces de l'element n'ont pas le meme nombre de sommets, le nombre de colonnes du tableau est le plus grand nombre de sommets, et les cases inutilisees du tableau sont mises a -1 On renvoie 1 si toutes les faces ont le meme nombre d'elements, 0 sinon.
Implements Poly_geom_base_32_64< _SIZE_ >.
get_tab_faces_sommets_locaux() [2/2]
template<typename _SIZE_ > int Polygone_32_64< _SIZE_ >::get_tab_faces_sommets_locaux (IntTab & faces_som_local, int_t elem) const override virtual
Implements Poly_geom_base_32_64< _SIZE_ >.
References TRUSTTab< _TYPE_, _SIZE_ >::resize().
affecte_connectivite_numero_global()
template<typename _SIZE_ > void Polygone_32_64< _SIZE_ >::affecte_connectivite_numero_global (const ArrOfInt_t & FacesIndex, const ArrOfInt_t & PolygonIndex, IntTab_t & les_elems)
References TRUSTList< _TYPE_ >::add_if_not(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTList< _TYPE_ >::size(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and TRUSTList< _TYPE_ >::vide().
get_nb_som_elem_max()
template<typename _SIZE_ > int Polygone_32_64< _SIZE_ >::get_nb_som_elem_max
Referenced by Polygone_32_64< _SIZE_ >::nb_som().
get_nb_face_elem_max()
template<typename _SIZE_ > int Polygone_32_64< _SIZE_ >::get_nb_face_elem_max () const inline
References Poly_geom_base_32_64< _SIZE_ >::nb_face_elem_max_.
Referenced by Polygone_32_64< _SIZE_ >::nb_faces().
get_somme_nb_faces_elem()
template<typename _SIZE_ > _SIZE_ Polygone_32_64< _SIZE_ >::get_somme_nb_faces_elem override virtual
Implements Poly_geom_base_32_64< _SIZE_ >.
getPolygonIndex()
template<typename _SIZE_ > const ArrOfInt_t & Polygone_32_64< _SIZE_ >::getPolygonIndex () const inline
References Polygone_32_64< _SIZE_ >::PolygonIndex_.
getElemIndex()
template<typename _SIZE_ > const ArrOfInt_t & Polygone_32_64< _SIZE_ >::getElemIndex () const inline override virtual
Implements Poly_geom_base_32_64< _SIZE_ >.
References Polygone_32_64< _SIZE_ >::PolygonIndex_.
rebuild_index()
template<typename _SIZE_ > void Polygone_32_64< _SIZE_ >::rebuild_index
References TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot().
build_reduced()
template<typename _SIZE_ > void Polygone_32_64< _SIZE_ >::build_reduced (TRUST_Deriv< Elem_geom_base_32_64< int > > & type_elem, const ArrOfInt_t & elems_sous_part) const override virtual
Implements Poly_geom_base_32_64< _SIZE_ >.
References TRUSTArray< _TYPE_, _SIZE_ >::append_array(), Poly_geom_base_32_64< _SIZE_ >::FacesIndex_, Poly_geom_base_32_64< _SIZE_ >::nb_face_elem_max_, Poly_geom_base_32_64< _SIZE_ >::nb_som_elem_max_, Polygone_32_64< _SIZE_ >::PolygonIndex_, TRUSTArray< _TYPE_, _SIZE_ >::resize(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
compute_virtual_index()
template<typename _SIZE_ > void Polygone_32_64< _SIZE_ >::compute_virtual_index override virtual
Implements Poly_geom_base_32_64< _SIZE_ >.
info_obj() [1/2]
const Type_info Polygone_32_64< int >::info_obj ("Polygone" , Polygone_32_64< int >::cree_instance , 1 , Polygone_32_64bases< int >)
info_obj() [2/2]
const Type_info Polygone_32_64< trustIdType >::info_obj ("Polygone" "_64" , Polygone_32_64< trustIdType >::cree_instance , 1 , Polygone_32_64bases< trustIdType >)
Friends And Related Function Documentation
Polygone_32_64
template<typename _SIZE_ > template<class T > friend class Polygone_32_64 friend
Member Data Documentation
info_obj
template<typename _SIZE_ > const Type_info Polygone_32_64< _SIZE_ >::info_obj static
PolygonIndex_
template<typename _SIZE_ > ArrOfInt_t Polygone_32_64< _SIZE_ >::PolygonIndex_ protected
PolygonIndex_[ele] gives the index of the first face of element 'ele' See FaceIndex_ in base class.
Referenced by Polygone_32_64< _SIZE_ >::build_reduced(), Polygone_32_64< _SIZE_ >::getElemIndex(), Polygone_32_64< _SIZE_ >::getPolygonIndex(), and Polygone_32_64< _SIZE_ >::Polygone_32_64().
dimension
template<typename _SIZE_ > int Objet_U::dimension static protected