TrioCFD: Champ_front_uniforme Class Reference
Champ_front_uniforme Class Reference
#include <Champ_front_uniforme.h>
Public Member Functions
Champ_front_base & affecter_ (const Champ_front_base &ch) override
const Type_info * get_info () const override
void valeurs_face (int, DoubleVect &) const override
Public Member Functions inherited from Champ_front_base
virtual void associer_fr_dis_base (const Frontiere_dis_base &)
virtual int avancer (double temps)
virtual void calculer_coeffs_echange (double temps)
virtual void fixer_nb_valeurs_temporelles (int nb_cases)
virtual Frontiere_dis_base & frontiere_dis ()
virtual const Frontiere_dis_base & frontiere_dis () const
const Type_info * get_info () const override
virtual int initialiser (double temps, const Champ_Inc_base &inco)
virtual void mettre_a_jour (double temps)
virtual int reculer (double temps)
virtual const DoubleTab & valeurs () const override
virtual DoubleTab & valeurs () override
virtual void valeurs_face (int, DoubleVect &) const
Public Member Functions inherited from Field_base
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
virtual void fixer_nb_comp (int i)
virtual const Nom & fixer_nom_compo (const Nom &)
virtual const Nom & fixer_nom_compo (int, const Nom &)
virtual const Noms & fixer_noms_compo (const Noms &)
virtual const Nom & fixer_unite (const Nom &)
virtual const Nom & fixer_unite (int i, const Nom &)
virtual const Noms & fixer_unites (const Noms &)
const Type_info * get_info () const override
const Nom & nom_compo (int) const
void nommer (const Nom &) override
const Nom & unite () const
const Nom & unite (int) const
const Noms & unites () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Champ_Proto
int lire_dimension (Entree &, const Nom &)
int lire_dimension (int dim, const Nom &le_nom_)
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Champ_front_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Field_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
champs aux frontieres uniformes en espace et constants dans
le temps
See also
Champ_front_base Champ_Uniforme
Constructor & Destructor Documentation
Champ_front_uniforme()
Champ_front_uniforme::Champ_front_uniforme ()
~Champ_front_uniforme()
Champ_front_uniforme::~Champ_front_uniforme ()
Member Function Documentation
cree_instance()
Objet_U * Champ_front_uniforme::cree_instance () static
taille_memoire()
unsigned Champ_front_uniforme::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Boundary_field_uniform_keps_from_ud.
duplique()
int Champ_front_uniforme::duplique () const override virtual
Implements Objet_U.
Reimplemented in Boundary_field_uniform_keps_from_ud.
info()
const Type_info * Champ_front_uniforme::info () static
get_info()
const Type_info * Champ_front_uniforme::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
Reimplemented in Boundary_field_uniform_keps_from_ud.
self_cast() [1/2]
Champ_front_uniforme & Champ_front_uniforme::self_cast (Objet_U & r) static
self_cast() [2/2]
const Champ_front_uniforme & Champ_front_uniforme::self_cast (const Objet_U & r) static
printOn()
Sortie & Champ_front_uniforme::printOn (Sortie & os) const override protected virtual
Imprime le champ sur flot de sortie.
Imprime la taille du champ et la valeur (constante) sur la frontiere.
Parameters
(Sortie& os) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Objet_U.
Reimplemented in Boundary_field_uniform_keps_from_ud.
References TRUSTVect< _TYPE_, _SIZE_ >::size(), and Champ_front_base::valeurs().
readOn()
Entree & Champ_front_uniforme::readOn (Entree & is) override protected virtual
Lit le champ a partir d'un flot d'entree.
Format: Champ_front_uniforme nb_compo vrel_1 ... [vrel_i]
Parameters
(Entree& is) un flot d'entree
Returns
(Entree& is) le flot d'entree modifie
Reimplemented from Objet_U.
Reimplemented in Boundary_field_uniform_keps_from_ud.
References Field_base::fixer_nb_comp(), Champ_front_base::les_valeurs, Champ_Proto::lire_dimension(), Objet_U::que_suis_je(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), and Roue::valeurs().
valeurs_au_temps() [1/2]
DoubleTab & Champ_front_uniforme::valeurs_au_temps (double temps) override virtual
Renvoie les valeurs sans s'occuper du temps puisque le champ est stationnaire.
Implements Champ_front_base.
References Champ_front_base::les_valeurs, and Roue::valeurs().
valeurs_au_temps() [2/2]
const DoubleTab & Champ_front_uniforme::valeurs_au_temps (double temps) const override virtual
Renvoie les valeurs sans s'occuper du temps puisque le champ est stationnaire.
Implements Champ_front_base.
References Champ_front_base::les_valeurs, and Roue::valeurs().
avancer()
int Champ_front_uniforme::avancer (double temps) override virtual
Avance en temps : rien a faire pour un champ stationnaire !
Reimplemented from Champ_front_base.
reculer()
int Champ_front_uniforme::reculer (double temps) override virtual
Recule en temps : rien a faire pour un champ stationnaire !
Reimplemented from Champ_front_base.
affecter_()
Champ_front_base & Champ_front_uniforme::affecter_ (const Champ_front_base & ch) override virtual
Renvoie l'objet upcaste en Champ_front_base&.
Parameters
(Champ_front_base& ch)
Returns
(Champ_front_base&) (*this) upcaste en Champ_front_base&
Implements Champ_front_base.
valeurs_face()
void Champ_front_uniforme::valeurs_face (int face, DoubleVect & var) const override virtual
Renvoie le vecteur des valeurs du champ pour la face donnee.
Returns
le tableau des valeurs du champ
Reimplemented from Champ_front_base.
References Field_base::nb_compo_, TRUSTVect< _TYPE_, _SIZE_ >::resize(), and Champ_front_base::valeurs().
changer_temps_futur()
void Champ_front_uniforme::changer_temps_futur (double temps, int i) override virtual
rien a faire pour un champ stationnaire !
Reimplemented from Champ_front_base.
Member Data Documentation
info_obj
const Type_info Champ_front_uniforme::info_obj static