TrioCFD: Traitement_particulier_NS_Profils_thermo_VDF Class Reference
Traitement_particulier_NS_Profils_thermo_VDF Class Reference
#include <Traitement_particulier_NS_Profils_thermo_VDF.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Traitement_particulier_NS_Profils_VDF
const Type_info * get_info () const override
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Traitement_particulier_NS_Profils_VDF
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
See also
Navier_Stokes_Turbulent, Traitement_particulier_base, Traitement_particulier_VDF, Trait_part_NS_Profils_VDF
Constructor & Destructor Documentation
Traitement_particulier_NS_Profils_thermo_VDF()
Traitement_particulier_NS_Profils_thermo_VDF::Traitement_particulier_NS_Profils_thermo_VDF ()
~Traitement_particulier_NS_Profils_thermo_VDF()
Traitement_particulier_NS_Profils_thermo_VDF::~Traitement_particulier_NS_Profils_thermo_VDF ()
Member Function Documentation
cree_instance()
Objet_U * Traitement_particulier_NS_Profils_thermo_VDF::cree_instance () static
taille_memoire()
unsigned Traitement_particulier_NS_Profils_thermo_VDF::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Traitement_particulier_NS_Profils_thermo_VDF::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Traitement_particulier_NS_Profils_thermo_VDF::info () static
get_info()
const Type_info * Traitement_particulier_NS_Profils_thermo_VDF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Traitement_particulier_NS_Profils.
self_cast() [1/2]
Traitement_particulier_NS_Profils_thermo_VDF & Traitement_particulier_NS_Profils_thermo_VDF::self_cast (Objet_U & r) static
self_cast() [2/2]
const Traitement_particulier_NS_Profils_thermo_VDF & Traitement_particulier_NS_Profils_thermo_VDF::self_cast (const Objet_U & r) static
printOn()
Sortie & Traitement_particulier_NS_Profils_thermo_VDF::printOn (Sortie & is) const override protected virtual
Parameters
(Sortie& is) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Traitement_particulier_NS_Profils.
readOn()
Entree & Traitement_particulier_NS_Profils_thermo_VDF::readOn (Entree & is) override protected virtual
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Traitement_particulier_NS_Profils.
lire() [1/2]
Entree & Traitement_particulier_NS_Profils_thermo_VDF::lire (Entree & is) override virtual
Reimplemented from Traitement_particulier_NS_Profils.
References Traitement_particulier_NS_Profils_VDF::lire().
lire() [2/2]
Entree & Traitement_particulier_NS_Profils_thermo_VDF::lire (const Motcle & motlu, Entree & is) override virtual
Implements Traitement_particulier_NS_Profils.
References fich_repr_stats_thermo, Traitement_particulier_NS_Profils_VDF::lire(), oui_repr_stats_thermo, oui_stats_thermo, and tmin_tmax.
reprendre_stat()
void Traitement_particulier_NS_Profils_thermo_VDF::reprendre_stat () override virtual
Reimplemented from Traitement_particulier_NS_Profils.
References Process::exit(), fich_repr_stats_thermo, Traitement_particulier_NS_base::mon_equation, Traitement_particulier_NS_Profils::n_probes, Traitement_particulier_NS_Profils::Nap, Traitement_particulier_NS_Profils::Nuv, oui_repr_stats_thermo, Traitement_particulier_NS_Profils::oui_stat, Traitement_particulier_NS_Profils::reprendre_stat(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Traitement_particulier_NS_Profils::temps_deb, Tmoy_temp, Trms_temp, upTp_temp, vpTp_temp, and wpTp_temp.
sauver_stat()
void Traitement_particulier_NS_Profils_thermo_VDF::sauver_stat () const override virtual
Reimplemented from Traitement_particulier_NS_Profils.
References Sortie_Fichier_base::close(), Sortie_Fichier_base::flush(), Traitement_particulier_NS_base::mon_equation, Traitement_particulier_NS_Profils::n_probes, Traitement_particulier_NS_Profils::Nuv, Traitement_particulier_NS_Profils::oui_stat, Traitement_particulier_NS_Profils::sauver_stat(), Traitement_particulier_NS_Profils::temps_deb, Traitement_particulier_NS_Profils::temps_fin, Tmoy_temp, Trms_temp, upTp_temp, vpTp_temp, and wpTp_temp.
associer_eqn()
void Traitement_particulier_NS_Profils_thermo_VDF::associer_eqn (const Equation_base & eq_ns) override virtual
Reimplemented from Traitement_particulier_NS_base.
References Traitement_particulier_NS_base::associer_eqn(), Probleme_base::equation(), Process::exit(), Traitement_particulier_NS_base::mon_equation, mon_equation_NRJ, and Probleme_base::nombre_d_equations().
ecriture_fichier_moy_spat_thermo()
void Traitement_particulier_NS_Profils_thermo_VDF::ecriture_fichier_moy_spat_thermo (const DoubleTab & Tmoy_m, const DoubleTab & Trms_m, const DoubleTab & upTp_m, const DoubleTab & vpTp_m, const DoubleTab & wpTp_m, const DoubleTab & Tmoy_p, const DoubleTab & Trms_p, const DoubleTab & upTp_p, const DoubleTab & vpTp_p, const DoubleTab & wpTp_p, const DoubleTab & Y, const IntVect & NN, const DoubleVect & delta_m, const DoubleVect & delta_p)
References Traitement_particulier_NS_Profils::dir_profil, Process::je_suis_maitre(), Traitement_particulier_NS_base::mon_equation, Traitement_particulier_NS_Profils::n_probes, and Traitement_particulier_NS_Profils::positions.
Referenced by post_traitement_particulier().
ecriture_fichier_moy_temp_thermo()
void Traitement_particulier_NS_Profils_thermo_VDF::ecriture_fichier_moy_temp_thermo (const DoubleTab & Tmoy, const DoubleTab & Trms, const DoubleTab & upTp, const DoubleTab & vpTp, const DoubleTab & wpTp, const DoubleTab & Y, const double dt, const IntVect & NN)
References Traitement_particulier_NS_Profils::dir_profil, Process::je_suis_maitre(), Traitement_particulier_NS_base::mon_equation, Traitement_particulier_NS_Profils::n_probes, and Traitement_particulier_NS_Profils::positions.
Referenced by post_traitement_particulier().
calculer_moyennes_spatiales_thermo()
void Traitement_particulier_NS_Profils_thermo_VDF::calculer_moyennes_spatiales_thermo (DoubleTab & tmoy, DoubleTab & trms, DoubleTab & uptp, DoubleTab & vptp, DoubleTab & wptp, const IntTab & corresp, const IntTab & compt, const IntVect & NN, const DoubleTab & xUV)
References Sortie_Fichier_base::close(), Objet_U::dimension, Traitement_particulier_NS_Profils::dir_profil, Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), Sortie_Fichier_base::flush(), Process::je_suis_maitre(), Process::me(), Traitement_particulier_NS_base::mon_equation, mon_equation_NRJ, Traitement_particulier_NS_Profils::n_probes, Traitement_particulier_NS_Profils::Nap, Domaine_32_64< _SIZE_ >::nb_elem(), Process::nproc(), tmin_tmax, and Domaine_VF::xp().
Referenced by post_traitement_particulier().
calculer_integrales_temporelles()
void Traitement_particulier_NS_Profils_thermo_VDF::calculer_integrales_temporelles (DoubleTab & moy_temp, const DoubleTab & moy_spat_m, const DoubleTab & moy_spat_p, const DoubleVect & delta_m, const DoubleVect & delta_p)
References TRUSTVect< _TYPE_, _SIZE_ >::ajoute_sans_ech_esp_virt(), Process::je_suis_maitre(), Traitement_particulier_NS_base::mon_equation, Traitement_particulier_NS_Profils::n_probes, and Traitement_particulier_NS_Profils::Nap.
Referenced by post_traitement_particulier().
post_traitement_particulier()
void Traitement_particulier_NS_Profils_thermo_VDF::post_traitement_particulier () override virtual
Implements Traitement_particulier_NS_Profils.
References calculer_integrales_temporelles(), calculer_moyennes_spatiales_thermo(), Traitement_particulier_NS_Profils_VDF::compt_uv_m, Traitement_particulier_NS_Profils_VDF::compt_uv_p, Traitement_particulier_NS_Profils_VDF::corresp_uv_m, Traitement_particulier_NS_Profils_VDF::corresp_uv_p, Traitement_particulier_NS_Profils_VDF::delta_UVm, Traitement_particulier_NS_Profils_VDF::delta_UVp, Traitement_particulier_NS_Profils::dt_post_inst, Traitement_particulier_NS_Profils::dt_post_stat, ecriture_fichier_moy_spat_thermo(), ecriture_fichier_moy_temp_thermo(), Traitement_particulier_NS_base::mon_equation, Traitement_particulier_NS_Profils::n_probes, Traitement_particulier_NS_Profils::Nap, Traitement_particulier_NS_Profils::Nuv, Traitement_particulier_NS_Profils::oui_repr, Traitement_particulier_NS_Profils::oui_stat, oui_stats_thermo, Traitement_particulier_NS_Profils::oui_u_inst, Traitement_particulier_NS_Profils_VDF::post_traitement_particulier(), Traitement_particulier_NS_Profils::temps_deb, Traitement_particulier_NS_Profils::temps_fin, Tmoy_temp, Trms_temp, upTp_temp, vpTp_temp, wpTp_temp, Traitement_particulier_NS_Profils_VDF::xUVm, Traitement_particulier_NS_Profils_VDF::xUVp, and Traitement_particulier_NS_Profils_VDF::Yuv_m.
init_calcul_moyenne()
void Traitement_particulier_NS_Profils_thermo_VDF::init_calcul_moyenne () override virtual
Implements Traitement_particulier_NS_Profils.
References Traitement_particulier_NS_Profils_VDF::init_calcul_moyenne().
preparer_calcul_particulier()
void Traitement_particulier_NS_Profils_thermo_VDF::preparer_calcul_particulier () override virtual
Reimplemented from Traitement_particulier_NS_Profils.
References Traitement_particulier_NS_Profils_VDF::init_calcul_moyenne(), init_calcul_stats(), Traitement_particulier_NS_Profils::oui_profil_nu_t, Traitement_particulier_NS_Profils::oui_stat, and Traitement_particulier_NS_Profils::oui_u_inst.
init_calcul_stats()
void Traitement_particulier_NS_Profils_thermo_VDF::init_calcul_stats ()
References Traitement_particulier_NS_Profils::init_calcul_stats(), Traitement_particulier_NS_Profils::n_probes, Traitement_particulier_NS_Profils::Nap, oui_repr_stats_thermo, TRUSTTab< _TYPE_, _SIZE_ >::resize(), Tmoy_temp, Trms_temp, upTp_temp, vpTp_temp, and wpTp_temp.
Referenced by preparer_calcul_particulier().
Member Data Documentation
info_obj
const Type_info Traitement_particulier_NS_Profils_thermo_VDF::info_obj static
mon_equation_NRJ
TRUST_Ref< Convection_Diffusion_std *> Traitement_particulier_NS_Profils_thermo_VDF::mon_equation_NRJ protected
Referenced by associer_eqn(), and calculer_moyennes_spatiales_thermo().
oui_stats_thermo
int Traitement_particulier_NS_Profils_thermo_VDF::oui_stats_thermo = 0 protected
Referenced by lire(), and post_traitement_particulier().
oui_repr_stats_thermo
int Traitement_particulier_NS_Profils_thermo_VDF::oui_repr_stats_thermo = 0 protected
Referenced by init_calcul_stats(), lire(), and reprendre_stat().
tmin_tmax
int Traitement_particulier_NS_Profils_thermo_VDF::tmin_tmax = 0 protected
Referenced by calculer_moyennes_spatiales_thermo(), and lire().
fich_repr_stats_thermo
Nom Traitement_particulier_NS_Profils_thermo_VDF::fich_repr_stats_thermo protected
Referenced by lire(), and reprendre_stat().
Tmoy_temp
DoubleTab Traitement_particulier_NS_Profils_thermo_VDF::Tmoy_temp protected
Referenced by init_calcul_stats(), post_traitement_particulier(), reprendre_stat(), and sauver_stat().
Trms_temp
DoubleTab Traitement_particulier_NS_Profils_thermo_VDF::Trms_temp protected
Referenced by init_calcul_stats(), post_traitement_particulier(), reprendre_stat(), and sauver_stat().
upTp_temp
DoubleTab Traitement_particulier_NS_Profils_thermo_VDF::upTp_temp protected
Referenced by init_calcul_stats(), post_traitement_particulier(), reprendre_stat(), and sauver_stat().
vpTp_temp
DoubleTab Traitement_particulier_NS_Profils_thermo_VDF::vpTp_temp protected
Referenced by init_calcul_stats(), post_traitement_particulier(), reprendre_stat(), and sauver_stat().
wpTp_temp
DoubleTab Traitement_particulier_NS_Profils_thermo_VDF::wpTp_temp protected
Referenced by init_calcul_stats(), post_traitement_particulier(), reprendre_stat(), and sauver_stat().