TrioCFD: Eval_Puiss_Th_VDF_Elem Class Reference
Eval_Puiss_Th_VDF_Elem Class Reference
#include <Eval_Puiss_Th_VDF_Elem.h>
Member Function Documentation
calculer_terme_source()
template<typename Type_Double > void Eval_Puiss_Th_VDF_Elem::calculer_terme_source (const int num_elem, Type_Double & source) const
References la_puissance, Evaluateur_Source_Elem::porosite_vol, puissance, TRUST_Ref< _CLASSE_ >::valeur(), and Evaluateur_Source_Elem::volumes.
associer_champs()
void Eval_Puiss_Th_VDF_Elem::associer_champs (const Champ_Don_base & Q) inline
References la_puissance, puissance, TRUSTTab< _TYPE_, _SIZE_ >::ref(), and Champ_Don_base::valeurs().
Referenced by Terme_Puissance_Thermique_VDF_Elem::associer_pb().
mettre_a_jour()
void Eval_Puiss_Th_VDF_Elem::mettre_a_jour () inline override virtual
Implements Evaluateur_Source.
Member Data Documentation
la_puissance
TRUST_Ref< Champ_Don_base *> Eval_Puiss_Th_VDF_Elem::la_puissance protected
Referenced by associer_champs(), and calculer_terme_source().
puissance
DoubleTab Eval_Puiss_Th_VDF_Elem::puissance protected
Referenced by associer_champs(), and calculer_terme_source().