TrioCFD: Op_Diff_Fluctu_Temp Class Reference
Op_Diff_Fluctu_Temp Class Reference
#include <Op_Diff_Fluctu_Temp_Base.h>
Public Member Functions
void completer () override
const Type_info * get_info () const override
Public Member Functions inherited from Operateur
DoubleTab & ajouter (const Champ_Inc_base &, DoubleTab &) const
DoubleTab & ajouter (DoubleTab &) const
DoubleTab & calculer (const Champ_Inc_base &, DoubleTab &) const
DoubleTab & calculer (DoubleTab &) const
virtual void completer ()
const Discretisation_base & discretisation () const
int impr (Sortie &os) const
void imprimer (Sortie &os) const
int limpr () const
Entree & lire (Entree &)
virtual void mettre_a_jour (double temps)
const Champ_Inc_base & mon_inconnue () const
const Nom & type () const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Objet_U_ptr
int associer_ (Objet_U &objet) override
const Type_info * get_info () const override
const Nom & le_nom () const override
Objet_U * typer (const char *nom_type)
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from TRUST_Deriv< Op_Diff_Fluctu_Temp_Base >
Sortie & printOn (Sortie &os) const override
Entree & readOn (Entree &is) override
Protected Member Functions inherited from Objet_U_ptr
int change_num (const int *const) override
Objet_U * get_Objet_U_ptr_check () const
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
void recopie (const Objet_U &)
~Objet_U_ptr () override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Op_Diff_Fluctu_Temp()
Op_Diff_Fluctu_Temp::Op_Diff_Fluctu_Temp ()
~Op_Diff_Fluctu_Temp()
Op_Diff_Fluctu_Temp::~Op_Diff_Fluctu_Temp ()
Member Function Documentation
cree_instance()
Objet_U * Op_Diff_Fluctu_Temp::cree_instance () static
taille_memoire()
unsigned Op_Diff_Fluctu_Temp::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Op_Diff_Fluctu_Temp::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Op_Diff_Fluctu_Temp::info () static
get_info()
const Type_info * Op_Diff_Fluctu_Temp::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U_ptr.
self_cast() [1/2]
Op_Diff_Fluctu_Temp & Op_Diff_Fluctu_Temp::self_cast (Objet_U & r) static
self_cast() [2/2]
const Op_Diff_Fluctu_Temp & Op_Diff_Fluctu_Temp::self_cast (const Objet_U & r) static
printOn()
Sortie & Op_Diff_Fluctu_Temp::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U_ptr.
References Objet_U::que_suis_je().
readOn()
Entree & Op_Diff_Fluctu_Temp::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U_ptr.
References Operateur::lire().
l_op_base() [1/2]
Operateur_base & Op_Diff_Fluctu_Temp::l_op_base () inline override virtual
Implements Operateur.
References Objet_U_ptr::non_nul(), and TRUST_Deriv< Op_Diff_Fluctu_Temp_Base >::valeur().
l_op_base() [2/2]
const Operateur_base & Op_Diff_Fluctu_Temp::l_op_base () const inline override virtual
Implements Operateur.
References Objet_U_ptr::non_nul(), and TRUST_Deriv< Op_Diff_Fluctu_Temp_Base >::valeur().
ajouter()
DoubleTab & Op_Diff_Fluctu_Temp::ajouter (const DoubleTab & inconnue, DoubleTab & resu) const inline override virtual
Implements Operateur.
References Operateur_base::ajouter(), and TRUST_Deriv< Op_Diff_Fluctu_Temp_Base >::valeur().
calculer()
DoubleTab & Op_Diff_Fluctu_Temp::calculer (const DoubleTab & inconnue, DoubleTab & resu) const inline override virtual
Implements Operateur.
References Operateur_base::calculer(), and TRUST_Deriv< Op_Diff_Fluctu_Temp_Base >::valeur().
typer()
void Op_Diff_Fluctu_Temp::typer () override virtual
Implements Operateur.
References Operateur_base::associer_eqn(), Objet_U::axi, Equation_base::discretisation(), MorEqn::equation(), Equation_base::inconnue(), Objet_U::que_suis_je(), Nom::suffix(), Operateur::typ, typer(), and TRUST_Deriv< Op_Diff_Fluctu_Temp_Base >::valeur().
Referenced by typer().
op_non_nul()
int Op_Diff_Fluctu_Temp::op_non_nul () const inline override virtual
Implements Operateur.
References Objet_U_ptr::non_nul().
completer()
void Op_Diff_Fluctu_Temp::completer () override virtual
Met a jour les references des objets associes a l'operateur.
Operateur::le_champ_inco, Operateur::champ_inco Appelle Operateur_base::completer()
Reimplemented from Operateur.
References Op_Diff_Fluctu_Temp_Base::associer_diffusivite_turbulente(), Operateur::completer(), and TRUST_Deriv< Op_Diff_Fluctu_Temp_Base >::valeur().
Member Data Documentation
info_obj
const Type_info Op_Diff_Fluctu_Temp::info_obj static