TrioCFD: Marqueur_FT Class Reference
Marqueur_FT Class Reference
#include <Marqueur_FT.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
-on attribue a cette classe un objet de type Maillage_FT_Disc pour beneficier de la structure gerant un suivi Lagrangien On ne retient que le suivi des sommets qui constituent les points suivis
See also
Marqueur_Lagrange_base
Constructor & Destructor Documentation
Marqueur_FT()
Marqueur_FT::Marqueur_FT ()
~Marqueur_FT()
Marqueur_FT::~Marqueur_FT ()
Member Function Documentation
cree_instance()
Objet_U * Marqueur_FT::cree_instance () static
taille_memoire()
unsigned Marqueur_FT::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Marqueur_FT::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Marqueur_FT::info () static
get_info()
const Type_info * Marqueur_FT::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Marqueur_Lagrange_base.
self_cast() [1/2]
Marqueur_FT & Marqueur_FT::self_cast (Objet_U & r) static
self_cast() [2/2]
const Marqueur_FT & Marqueur_FT::self_cast (const Objet_U & r) static
printOn()
Sortie & Marqueur_FT::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Marqueur_Lagrange_base.
readOn()
Entree & Marqueur_FT::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Marqueur_Lagrange_base.
References Process::exit().
discretiser()
void Marqueur_FT::discretiser (const Probleme_base & pb, const Discretisation_base & dis) override virtual
Reimplemented from Marqueur_Lagrange_base.
References Process::exit().
ensemble_points() [1/2]
Ensemble_Lagrange_base & Marqueur_FT::ensemble_points () inline override virtual
Implements Marqueur_Lagrange_base.
References ensemble_points_.
ensemble_points() [2/2]
const Ensemble_Lagrange_base & Marqueur_FT::ensemble_points () const inline override virtual
Implements Marqueur_Lagrange_base.
References ensemble_points_.
calculer_valeurs_champs()
void Marqueur_FT::calculer_valeurs_champs () override virtual
Implements Marqueur_Lagrange_base.
References Process::exit().
Member Data Documentation
info_obj
const Type_info Marqueur_FT::info_obj static
ensemble_points_
Maillage_FT_Disc Marqueur_FT::ensemble_points_ protected
Referenced by ensemble_points().