TrioCFD: Loi_expert_scalaire_VEF Class Reference
Loi_expert_scalaire_VEF Class Reference
#include <Paroi_std_scal_hyd_VEF.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Turbulence_paroi_scal_base
void associer_modele (const Modele_turbulence_scal_base &)
const Type_info * get_info () const override
void imprimer_nusselt_mean_only (Sortie &, int, const TRUST_List< Nom > &, const Nom &) const
void imprimer_premiere_ligne_nusselt (int, const TRUST_List< Nom > &, const Nom &) const
int reprendre (Entree &is) override
int sauvegarder (Sortie &os) const override
virtual bool use_equivalent_distance () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Turbulence_paroi_scal_base
static void typer_lire_turbulence_paroi_scal (TRUST_Deriv< Turbulence_paroi_scal_base > &, const Modele_turbulence_scal_base &, Entree &)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
Elle est reservee aux experts.
Constructor & Destructor Documentation
Loi_expert_scalaire_VEF()
Loi_expert_scalaire_VEF::Loi_expert_scalaire_VEF ()
~Loi_expert_scalaire_VEF()
Loi_expert_scalaire_VEF::~Loi_expert_scalaire_VEF ()
Member Function Documentation
cree_instance()
Objet_U * Loi_expert_scalaire_VEF::cree_instance () static
taille_memoire()
unsigned Loi_expert_scalaire_VEF::taille_memoire () const override virtual
Reimplemented from Paroi_std_scal_hyd_VEF.
duplique()
int Loi_expert_scalaire_VEF::duplique () const override virtual
Reimplemented from Paroi_std_scal_hyd_VEF.
info()
const Type_info * Loi_expert_scalaire_VEF::info () static
get_info()
const Type_info * Loi_expert_scalaire_VEF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Paroi_std_scal_hyd_VEF.
self_cast() [1/2]
Loi_expert_scalaire_VEF & Loi_expert_scalaire_VEF::self_cast (Objet_U & r) static
self_cast() [2/2]
const Loi_expert_scalaire_VEF & Loi_expert_scalaire_VEF::self_cast (const Objet_U & r) static
printOn()
Sortie & Loi_expert_scalaire_VEF::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Paroi_std_scal_hyd_VEF.
readOn()
Entree & Loi_expert_scalaire_VEF::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Paroi_std_scal_hyd_VEF.
References Param::ajouter(), Param::ajouter_condition(), Turbulence_paroi_scal_base::calcul_ldp_en_flux_impose_, Param::lire_avec_accolades_depuis(), Turbulence_paroi_scal_base::Prdt_sur_kappa_, and Objet_U::que_suis_je().
Member Data Documentation
info_obj
const Type_info Loi_expert_scalaire_VEF::info_obj static