TrioCFD: Sources Class Reference
Sources Class Reference
#include <Sources.h>
Public Member Functions
virtual int a_pour_Champ_Fonc (const Motcle &mot, TRUST_Ref< Champ_base * > &ch_ref) const
DoubleTab & ajouter (DoubleTab &) const
virtual void associer_champ_rho (const Champ_base &champ_rho)
DoubleTab & calculer (DoubleTab &) const
void completer ()
void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
int impr (Sortie &) const
int initialiser (double temps)
void mettre_a_jour (double temps)
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from TRUST_List< Source >
Sortie & printOn (Sortie &os) const override
Entree & readOn (Entree &is) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
Une equation contient un membres Equation_base::les_sources de type
Sources. Un objet Sources est un morceaux d'equation, cette classe
herite donc de MorEqn.
See also
Source MorEqn
Constructor & Destructor Documentation
Sources()
Sources::Sources ()
~Sources()
Sources::~Sources ()
Member Function Documentation
cree_instance()
Objet_U * Sources::cree_instance () static
taille_memoire()
unsigned Sources::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Sources::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Sources::info () static
get_info()
const Type_info * Sources::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
Sources & Sources::self_cast (Objet_U & r) static
self_cast() [2/2]
const Sources & Sources::self_cast (const Objet_U & r) static
printOn()
Sortie & Sources::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
References printOn().
Referenced by printOn().
readOn()
Entree & Sources::readOn (Entree & is) override protected virtual
Lecture d'une liste de sources sur un flot d'entree.
Lit une liste de sources separees par des virgules et le sajoute a la liste. format: { bloc de lecture d'une source [, bloc de lecture d'une source] ... }
Parameters
(Entree& is) le flot d'entree
Returns
(Entree&) le flot d'entree modifie
Exceptions
accolade ouvrante attendue
accolade fermante ou virgule attendue
Reimplemented from Objet_U.
References TRUST_List< Source >::add(), Process::exit(), MorEqn::mon_equation, Source::typer(), TRUST_Deriv< _CLASSE_ >::valeur(), and TRUST_Ref< _CLASSE_ >::valeur().
ajouter()
DoubleTab & Sources::ajouter (DoubleTab & xx) const
Ajoute la contribution de toutes les sources de la liste au tableau passe en parametre, et renvoie ce tableau.
Parameters
(DoubleTab& xx) le tableau dans lequel on doit accumuler la contribution des termes sources
Returns
(DoubleTab&) le parametre xx modifie
Referenced by Equation_base::assembler(), Convection_Diffusion_Espece_Multi_QC::assembler(), Convection_Diffusion_Temperature::assembler(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_avec_inertie_impl(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_impl(), Equation_base::derivee_en_temps_inco(), Navier_Stokes_phase_field::derivee_en_temps_inco(), Convection_Diffusion_Espece_Multi_QC::derivee_en_temps_inco(), Navier_Stokes_std::derivee_en_temps_inco(), Navier_Stokes_FT_Disc::derivee_en_temps_inco(), Convection_Diffusion_Fluide_Dilatable_Proto::derivee_en_temps_inco_sans_solveur_masse_impl(), Transport_Marqueur_FT::initTimeStep(), and Navier_Stokes_std::preparer_calcul().
calculer()
DoubleTab & Sources::calculer (DoubleTab & xx) const
Calcule la contribution de toutes les sources de la liste stocke le resultat dans le tableau passe en parametre,.
et renvoie ce tableau.
Parameters
(DoubleTab& xx) le tableau dans lequel on doit stocker la somme des contributions des sources
Returns
(DoubleTab&) le parametre xx modifie
Referenced by ParoiVDF_TBLE_LRM::calculer_hyd(), ParoiVDF_TBLE_LRM::calculer_hyd_BiK(), Paroi_ODVM_scal_VDF::calculer_scal(), Paroi_TBLE_scal_VDF::calculer_scal(), ParoiVEF_TBLE_scal::calculer_scal(), and Paroi_TBLE_scal_VDF::init_lois_paroi().
contribuer_jacobienne()
void Sources::contribuer_jacobienne (Matrice_Bloc & matrice, int n) const
References Source_base::contribuer_jacobienne(), and TRUST_Deriv< _CLASSE_ >::valeur().
mettre_a_jour()
void Sources::mettre_a_jour (double temps)
Mise a jour en temps, de toute les sources de la liste.
Parameters
(double temps) le pas de temps de mise a jour
Referenced by Equation_base::mettre_a_jour(), Probleme_base::postraiter(), Convection_Diffusion_Phase_field::preparer_calcul(), Navier_Stokes_IBM::preparer_calcul(), Navier_Stokes_std::preparer_calcul(), and Equation_base::updateGivenFields().
resetTime()
void Sources::resetTime (double temps)
Rest all sources to a given time See ProblemeTrio::resetTime()
Referenced by Equation_base::resetTime().
completer()
void Sources::completer ()
Appelle Source::completer() sur toutes les sources de la liste.
voir Source_base::completer().
Referenced by Equation_base::completer(), Transport_Marqueur_FT::completer(), Transport_Fluctuation_Temperature::completer(), and Transport_Flux_Chaleur_Turbulente::completer().
dimensionner()
void Sources::dimensionner (Matrice_Morse & matrice) const
Dimensionnement de la matrice implicite des termes sources.
Parcours toutes les sources de la liste pour dimensionner.
References Source_base::dimensionner(), Matrice_Morse::nb_colonnes(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by Equation_base::dimensionner_matrice_sans_mem().
contribuer_a_avec()
void Sources::contribuer_a_avec (const DoubleTab & a, Matrice_Morse & matrice) const
contribution a la matrice implicite des termes sources par defaut pas de contribution
References Source_base::contribuer_a_avec(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by Equation_base::assembler(), Convection_Diffusion_Espece_Multi_QC::assembler(), Convection_Diffusion_Temperature::assembler(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_avec_inertie_impl(), and Convection_Diffusion_Fluide_Dilatable_Proto::assembler_impl().
associer_champ_rho()
void Sources::associer_champ_rho (const Champ_base & champ_rho) virtual
Pour chaque source de la liste, appel a associer_champ_rho de la source.
Si la masse volumique est variable, il faut declarer le champ de rho aux sources avec cette methode (front-tracking) Sinon, par defaut, les calculs sont faits avec rho=1
References Source_base::associer_champ_rho(), and TRUST_Deriv< _CLASSE_ >::valeur().
a_pour_Champ_Fonc()
int Sources::a_pour_Champ_Fonc (const Motcle & mot, TRUST_Ref< Champ_base * > & ch_ref) const virtual
Pour chaque source de la liste, appel a a_pour_Champ_Fonc(mot,ch_ref).
Cette methode est appelee par Equation_base::a_pour_Champ_Fonc.
References Source_base::a_pour_Champ_Fonc(), and TRUST_Deriv< _CLASSE_ >::valeur().
impr()
int Sources::impr (Sortie & os) const
Appelle Source::impr() sur toutes les sources de la liste.
voir Source_base::impr().
Referenced by Equation_base::impr().
initialiser()
int Sources::initialiser (double temps)
Appelle Source::initialiser(temps) sur toutes les sources de la liste.
voir Source_base::initialiser(double temps).
Referenced by Equation_base::preparer_calcul().
check_multiphase_compatibility()
void Sources::check_multiphase_compatibility () const override virtual
Reimplemented from MorEqn.
References MorEqn::check_multiphase_compatibility(), and TRUST_Deriv< _CLASSE_ >::valeur().
Member Data Documentation
info_obj
const Type_info Sources::info_obj static