TrioCFD: Echange_contact_ODVM_VDF Class Reference
Echange_contact_ODVM_VDF Class Reference
#include <Echange_contact_ODVM_VDF.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Echange_contact_VDF
const Type_info * get_info () const override
int initialiser (double temps) override
void mettre_a_jour (double) override
Public Member Functions inherited from Echange_global_impose
int compatible_avec_discr (const Discretisation_base &discr) const override
const Type_info * get_info () const override
int initialiser (double temps) override
void mettre_a_jour (double temps) override
Public Member Functions inherited from Echange_impose_base
int a_mettre_a_jour_ss_pas_dt () override
void associer_fr_dis_base (const Frontiere_dis_base &) override
double emissivite (int num) const
double emissivite (int num, int k) const
const Type_info * get_info () const override
virtual double h_imp (int num) const
virtual double h_imp (int num, int k) const
int initialiser (double temps) override
void mettre_a_jour (double) override
virtual Champ_front_base & T_ext ()
virtual double T_ext (int num) const
virtual double T_ext (int num, int k) const
Public Member Functions inherited from Cond_lim_base
virtual int a_mettre_a_jour_ss_pas_dt ()
virtual void associer_domaine_cl_dis_base (const Domaine_Cl_dis_base &)
virtual void associer_fr_dis_base (const Frontiere_dis_base &)
virtual void calculer_coeffs_echange (double temps)
virtual int compatible_avec_discr (const Discretisation_base &) const
Domaine_Cl_dis_base & domaine_Cl_dis ()
const Domaine_Cl_dis_base & domaine_Cl_dis () const
virtual Frontiere_dis_base & frontiere_dis ()
virtual const Frontiere_dis_base & frontiere_dis () const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
void set_modifier_val_imp (int)
virtual void verifie_ch_init_nb_comp () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Cond_lim_base
void err_pas_compatible (const Discretisation_base &) const
void err_pas_compatible (const Equation_base &) const
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Echange_contact_ODVM_VDF()
Echange_contact_ODVM_VDF::Echange_contact_ODVM_VDF ()
~Echange_contact_ODVM_VDF()
Echange_contact_ODVM_VDF::~Echange_contact_ODVM_VDF ()
Member Function Documentation
cree_instance()
Objet_U * Echange_contact_ODVM_VDF::cree_instance () static
taille_memoire()
unsigned Echange_contact_ODVM_VDF::taille_memoire () const override virtual
Reimplemented from Echange_contact_VDF.
duplique()
int Echange_contact_ODVM_VDF::duplique () const override virtual
Reimplemented from Echange_contact_VDF.
info()
const Type_info * Echange_contact_ODVM_VDF::info () static
get_info()
const Type_info * Echange_contact_ODVM_VDF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Echange_contact_VDF.
self_cast() [1/2]
Echange_contact_ODVM_VDF & Echange_contact_ODVM_VDF::self_cast (Objet_U & r) static
self_cast() [2/2]
const Echange_contact_ODVM_VDF & Echange_contact_ODVM_VDF::self_cast (const Objet_U & r) static
printOn()
Sortie & Echange_contact_ODVM_VDF::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Echange_contact_VDF.
References Objet_U::que_suis_je().
readOn()
Entree & Echange_contact_ODVM_VDF::readOn (Entree & s) override protected virtual
Simple appel a Echange_impose_base::readOn(Entree&) Lit les specifications des conditions aux limites.
a partir d'un flot d'entree.
Parameters
(Entree& s) un flot d'entree
Returns
(Entree&) le flot de sortie modifie
Reimplemented from Echange_contact_VDF.
References Echange_contact_VDF::readOn().
calculer_Teta_equiv()
void Echange_contact_ODVM_VDF::calculer_Teta_equiv (DoubleTab & Teta_equiv, const DoubleTab & mon_h, const DoubleTab & autre_h, int is_pb_fluide, double temps) override virtual
remplit Teta_eq utilise T_autre_pb au temps passe en parametre
Reimplemented from Echange_contact_VDF.
References Cond_lim_base::domaine_Cl_dis(), MorEqn::equation(), Probleme_base::equation(), Process::exit(), Domaine_VF::face_voisins(), Cond_lim_base::frontiere_dis(), Equation_base::get_champ(), Equation_base::get_modele(), Paroi_ODVM_scal_VDF::get_Tf0(), Equation_base::has_champ(), Champ_front_calc::inconnue(), Equation_base::inconnue(), Modele_turbulence_scal_base::loi_paroi(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), Equation_base::probleme(), Echange_contact_VDF::T_autre_pb(), TRUST_Ref_Objet_U::valeur(), Champ_Inc_base::valeurs(), and Champ_front_base::valeurs_au_temps().
Member Data Documentation
info_obj
const Type_info Echange_contact_ODVM_VDF::info_obj static