TrioCFD: UserUnaryFunction Class Reference
UserUnaryFunction Class Reference
#include <UserUnaryFunction.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
See also
=
Constructor & Destructor Documentation
UserUnaryFunction()
UserUnaryFunction::UserUnaryFunction ()
~UserUnaryFunction()
UserUnaryFunction::~UserUnaryFunction ()
Member Function Documentation
cree_instance()
Objet_U * UserUnaryFunction::cree_instance () static
taille_memoire()
unsigned UserUnaryFunction::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int UserUnaryFunction::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * UserUnaryFunction::info () static
get_info()
const Type_info * UserUnaryFunction::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from UnaryFunction.
self_cast() [1/2]
UserUnaryFunction & UserUnaryFunction::self_cast (Objet_U & r) static
self_cast() [2/2]
const UserUnaryFunction & UserUnaryFunction::self_cast (const Objet_U & r) static
printOn()
Sortie & UserUnaryFunction::printOn (Sortie & os) const override protected virtual
Ecriture sur un flot de sortie Ecrit la valeur de la constante.
Parameters
(Sortie& os) le flot de sortie a utiliser
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from UnaryFunction.
readOn()
Entree & UserUnaryFunction::readOn (Entree & is) override protected virtual
Lit la valeur de la constante.
Parameters
(Entree& is) le flot d'entree a utiliser
Returns
(Entree&) le flot d'entree modifie
Reimplemented from UnaryFunction.
References Process::exit(), Parser_U::parseString(), and setFunction().
eval()
double UserUnaryFunction::eval (double x) override virtual
Implements UnaryFunction.
References Parser_U::eval(), and Parser_U::setVar().
getName()
const Nom & UserUnaryFunction::getName () const inline override virtual
Implements UnaryFunction.
setFunction()
void UserUnaryFunction::setFunction (Nom & name, Nom & inco, Nom & func)
References Parser_U::addVar(), Nom::getChar(), Nom::getString(), and Parser_U::setString().
Referenced by readOn().
Member Data Documentation
info_obj
const Type_info UserUnaryFunction::info_obj static