TrioCFD: Turbulence_paroi_base Class Reference
Turbulence_paroi_base Class Reference abstract
#include <Turbulence_paroi_base.h>
Public Member Functions
void associer_modele (const Modele_turbulence_hyd_base &)
int calculer_hyd (Champ_Fonc_base &, Champ_Fonc_base &)
int calculer_hyd (Champ_Inc_base &)
const Type_info * get_info () const override
virtual void imprimer_premiere_ligne_ustar (int, const TRUST_List< Nom > &, const Nom &) const
virtual void imprimer_ustar_mean_only (Sortie &, int, const TRUST_List< Nom > &, const Nom &) const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions
static void typer_lire_turbulence_paroi (TRUST_Deriv< Turbulence_paroi_base > &, const Modele_turbulence_hyd_base &, Entree &)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
de calcul des grandeurs turbulentes aux voisinages des parois. Contient une reference a un modele de turbulence.
See also
Paroi_std_hyd_VDF Paroi_std_scal_hyd_VDF, Classe abstraite, Methodes abstraites, void associer(const Domaine_dis_base&, const Domaine_Cl_dis_base&), int init_lois_paroi(), int calculer_hyd(DoubleTab&), int calculer_hyd(DoubleTab& , DoubleTab&)
Constructor & Destructor Documentation
Turbulence_paroi_base()
Turbulence_paroi_base::Turbulence_paroi_base ()
~Turbulence_paroi_base()
Turbulence_paroi_base::~Turbulence_paroi_base () override
Member Function Documentation
info()
const Type_info * Turbulence_paroi_base::info () static
get_info()
const Type_info * Turbulence_paroi_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
Reimplemented in Paroi_std_hyd_VDF_diphasique, Paroi_std_hyd_VEF_diphasique, Paroi_loi_WW_hyd_EF, Paroi_std_hyd_EF, Loi_expert_hydr_EF, LoiParoiHybride_VDF, Paroi_2couches_VDF, Paroi_loi_Ciofalo_hyd_VDF, Paroi_loi_WW_hyd_VDF, Paroi_std_hyd_VDF, Loi_expert_hydr_VDF, Paroi_TAU_NUL_VDF, Paroi_UTAU_IMP_VDF, ParoiVDF_TBLE, ParoiVDF_TBLE_LRM, LoiParoiHybride_VEF, Paroi_Cisaillement_Imp_VEF, Paroi_loi_WW_hyd_VEF, Paroi_std_hyd_VEF, Loi_expert_hydr_VEF, Paroi_std_hyd_VEF_3couches, ParoiVEF_TBLE, Paroi_hyd_base_VDF, Paroi_negligeable_VDF, Paroi_hyd_base_VEF, and Paroi_negligeable_VEF.
self_cast() [1/2]
Turbulence_paroi_base & Turbulence_paroi_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Turbulence_paroi_base & Turbulence_paroi_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Turbulence_paroi_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
Reimplemented in Paroi_std_hyd_VDF_diphasique, Paroi_std_hyd_VEF_diphasique, Paroi_loi_WW_hyd_EF, Paroi_std_hyd_EF, Loi_expert_hydr_EF, LoiParoiHybride_VDF, Paroi_2couches_VDF, Paroi_loi_Ciofalo_hyd_VDF, Paroi_loi_WW_hyd_VDF, Paroi_std_hyd_VDF, Loi_expert_hydr_VDF, Paroi_TAU_NUL_VDF, Paroi_UTAU_IMP_VDF, ParoiVDF_TBLE, ParoiVDF_TBLE_LRM, LoiParoiHybride_VEF, Paroi_Cisaillement_Imp_VEF, Paroi_loi_WW_hyd_VEF, Paroi_std_hyd_VEF, Loi_expert_hydr_VEF, Paroi_std_hyd_VEF_3couches, ParoiVEF_TBLE, Paroi_hyd_base_VDF, Paroi_negligeable_VDF, Paroi_hyd_base_VEF, and Paroi_negligeable_VEF.
References Objet_U::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Turbulence_paroi_base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
Reimplemented in Paroi_std_hyd_VDF_diphasique, Paroi_std_hyd_VEF_diphasique, Paroi_loi_WW_hyd_EF, Paroi_std_hyd_EF, Loi_expert_hydr_EF, LoiParoiHybride_VDF, Paroi_2couches_VDF, Paroi_loi_Ciofalo_hyd_VDF, Paroi_loi_WW_hyd_VDF, Paroi_std_hyd_VDF, Loi_expert_hydr_VDF, Paroi_TAU_NUL_VDF, Paroi_UTAU_IMP_VDF, ParoiVDF_TBLE, ParoiVDF_TBLE_LRM, LoiParoiHybride_VEF, Paroi_Cisaillement_Imp_VEF, Paroi_loi_WW_hyd_VEF, Paroi_std_hyd_VEF, Loi_expert_hydr_VEF, Paroi_std_hyd_VEF_3couches, ParoiVEF_TBLE, Paroi_hyd_base_VDF, Paroi_negligeable_VDF, Paroi_hyd_base_VEF, and Paroi_negligeable_VEF.
Referenced by Paroi_hyd_base_EF::readOn(), Paroi_hyd_base_VDF::readOn(), and Paroi_hyd_base_VEF::readOn().
typer_lire_turbulence_paroi()
void Turbulence_paroi_base::typer_lire_turbulence_paroi (TRUST_Deriv< Turbulence_paroi_base > & loi_par, const Modele_turbulence_hyd_base & mod_turb_hyd, Entree & s) static
Lit les caracteristques de la loi de parois a partir d'un flot d'entree.
Format: type_de_loi_de_paroi Les valeurs possibles du type de loi de paroi sont:
"loi_standard_hydr"
"negligeable"
"loi_VanDriest"
References associer(), associer_modele(), Equation_base::discretisation(), Equation_base::domaine_Cl_dis(), Equation_base::domaine_dis(), Modele_turbulence_hyd_base::equation(), Process::exit(), and Objet_U::que_suis_je().
Referenced by Modele_turbulence_hyd_base::lire_motcle_non_standard().
set_param()
virtual void Turbulence_paroi_base::set_param (Param & param) inline virtual
Reimplemented in Paroi_loi_WW_hyd_EF, Paroi_std_hyd_EF, Paroi_2couches_VDF, Paroi_loi_WW_hyd_VDF, Paroi_std_hyd_VDF, ParoiVDF_TBLE, Paroi_loi_WW_hyd_VEF, Paroi_std_hyd_VEF, and ParoiVEF_TBLE.
Referenced by Paroi_std_hyd_EF::set_param(), Paroi_2couches_VDF::set_param(), Paroi_std_hyd_VDF::set_param(), ParoiVDF_TBLE::set_param(), Paroi_std_hyd_VEF::set_param(), and ParoiVEF_TBLE::set_param().
associer_modele()
void Turbulence_paroi_base::associer_modele (const Modele_turbulence_hyd_base & le_modele) inline
Associe un modele de turbulence a l'objet.
Parameters
(Modele_turbulence_hyd_base& le_modele) le modele de turbulence hydraulique a associer a l'objet
References mon_modele_turb_hyd.
Referenced by Modele_turbulence_hyd_null::readOn(), typer_lire_turbulence_paroi(), and Modele_turbulence_hyd_LES_base::verifie_loi_paroi_diphasique().
associer()
virtual void Turbulence_paroi_base::associer (const Domaine_dis_base & , const Domaine_Cl_dis_base &) pure virtual
Implemented in LoiParoiHybride_VDF, LoiParoiHybride_VEF, Paroi_hyd_base_EF, Paroi_hyd_base_VDF, and Paroi_hyd_base_VEF.
Referenced by Modele_turbulence_hyd_null::readOn(), typer_lire_turbulence_paroi(), and Modele_turbulence_hyd_LES_base::verifie_loi_paroi_diphasique().
completer()
virtual void Turbulence_paroi_base::completer () inline virtual
Referenced by Navier_Stokes_IBM_Turbulent::completer(), and Navier_Stokes_Turbulent::completer().
init_lois_paroi()
virtual int Turbulence_paroi_base::init_lois_paroi () pure virtual
Implemented in Paroi_std_hyd_EF, LoiParoiHybride_VDF, Paroi_2couches_VDF, Paroi_std_hyd_VDF, Paroi_UTAU_IMP_VDF, ParoiVDF_TBLE, ParoiVDF_TBLE_LRM, LoiParoiHybride_VEF, Paroi_Cisaillement_Imp_VEF, Paroi_std_hyd_VEF, ParoiVEF_TBLE, Paroi_negligeable_EF, Paroi_negligeable_VDF, and Paroi_negligeable_VEF.
Referenced by Modele_turbulence_hyd_base::preparer_calcul(), Navier_Stokes_Turbulent_ALE::preparer_calcul(), Navier_Stokes_IBM_Turbulent::preparer_calcul(), and Navier_Stokes_Turbulent::preparer_calcul().
calculer_hyd() [1/4]
int Turbulence_paroi_base::calculer_hyd (Champ_Inc_base & ch) inline
Simple appel a int calculer_hyd(DoubleTab&).
Parameters
(Champ_Inc_base& ch)
Returns
(int) code de retour propage
References calculer_hyd(), and Champ_Inc_base::valeurs().
Referenced by calculer_hyd(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::mettre_a_jour(), Modele_turbulence_hyd_combinaison::mettre_a_jour(), and Modele_turbulence_hyd_0_eq_base::mettre_a_jour().
calculer_hyd() [2/4]
int Turbulence_paroi_base::calculer_hyd (Champ_Fonc_base & ch1, Champ_Fonc_base & ch2) inline
Simple appel a int calculer_hyd(DoubleTab&, DoubleTab&).
Parameters
(Champ_Inc_base& ch1)
(Champ_Inc_base& ch2)
Returns
(int) code de retour propage
References calculer_hyd(), and Champ_Don_base::valeurs().
calculer_hyd() [3/4]
virtual int Turbulence_paroi_base::calculer_hyd (DoubleTab &) pure virtual
Implemented in Paroi_std_hyd_VDF_diphasique, Paroi_std_hyd_VEF_diphasique, Paroi_loi_WW_hyd_EF, Paroi_std_hyd_EF, LoiParoiHybride_VDF, Paroi_2couches_VDF, Paroi_loi_Ciofalo_hyd_VDF, Paroi_loi_WW_hyd_VDF, Paroi_std_hyd_VDF, Paroi_TAU_NUL_VDF, Paroi_UTAU_IMP_VDF, ParoiVDF_TBLE, ParoiVDF_TBLE_LRM, LoiParoiHybride_VEF, Paroi_Cisaillement_Imp_VEF, Paroi_loi_WW_hyd_VEF, Paroi_std_hyd_VEF, ParoiVEF_TBLE, Paroi_negligeable_EF, Paroi_negligeable_VDF, and Paroi_negligeable_VEF.
calculer_hyd() [4/4]
virtual int Turbulence_paroi_base::calculer_hyd (DoubleTab & , DoubleTab &) pure virtual
Implemented in Paroi_std_hyd_VDF_diphasique, Paroi_std_hyd_VEF_diphasique, Paroi_loi_WW_hyd_EF, Paroi_std_hyd_EF, LoiParoiHybride_VDF, Paroi_2couches_VDF, Paroi_loi_Ciofalo_hyd_VDF, Paroi_loi_WW_hyd_VDF, Paroi_std_hyd_VDF, Paroi_TAU_NUL_VDF, Paroi_UTAU_IMP_VDF, ParoiVDF_TBLE, ParoiVDF_TBLE_LRM, LoiParoiHybride_VEF, Paroi_Cisaillement_Imp_VEF, Paroi_loi_WW_hyd_VEF, Paroi_std_hyd_VEF, ParoiVEF_TBLE, Paroi_negligeable_EF, Paroi_negligeable_VDF, and Paroi_negligeable_VEF.
calculer_hyd_BiK()
virtual int Turbulence_paroi_base::calculer_hyd_BiK (DoubleTab & , DoubleTab &) pure virtual
Implemented in Paroi_std_hyd_EF, LoiParoiHybride_VDF, Paroi_2couches_VDF, Paroi_std_hyd_VDF, Paroi_TAU_NUL_VDF, Paroi_UTAU_IMP_VDF, ParoiVDF_TBLE, ParoiVDF_TBLE_LRM, LoiParoiHybride_VEF, Paroi_Cisaillement_Imp_VEF, Paroi_std_hyd_VEF, ParoiVEF_TBLE, Paroi_negligeable_EF, Paroi_negligeable_VDF, and Paroi_negligeable_VEF.
corriger_derivee_impl()
virtual DoubleTab & Turbulence_paroi_base::corriger_derivee_impl (DoubleTab & d) const inline virtual
Reimplemented in Paroi_hyd_base_EF, and Paroi_hyd_base_VEF.
Referenced by Transport_K_Eps::corriger_derivee_impl(), Transport_K_Omega::corriger_derivee_impl(), Transport_K_ou_Eps::corriger_derivee_impl(), and Transport_K_ou_Eps_Realisable::corriger_derivee_impl().
imprimer_ustar()
virtual void Turbulence_paroi_base::imprimer_ustar (Sortie &) const inline virtual
Reimplemented in Paroi_std_hyd_EF, Paroi_std_hyd_VDF, ParoiVDF_TBLE, Paroi_std_hyd_VEF, ParoiVEF_TBLE, Paroi_2couches_VDF, and ParoiVDF_TBLE_LRM.
Referenced by Modele_turbulence_hyd_base::imprimer().
imprimer_premiere_ligne_ustar()
void Turbulence_paroi_base::imprimer_premiere_ligne_ustar (int boundaries_, const TRUST_List< Nom > & boundaries_list, const Nom & nom_fichier_) const virtual
Writes header line for u* (friction velocity) statistics file.
Parameters
boundaries_ Flag to control boundary selection (0: all boundaries, 1: specified boundaries)
boundaries_list List of boundary names to process
nom_fichier_ Output filename
Creates header line with column names for u* and d+ statistics. Format: "Time Mean(u*) Mean(d+) [boundary1(u*) boundary1(d+) ...]" Writes warning messages if specified boundaries are not of correct wall type (Dirichlet_paroi_fixe or Dirichlet_paroi_defilante).
References Nom::contient(), Process::je_suis_maitre(), le_dom_Cl_dis_, le_dom_dis_, Objet_U_ptr::le_nom(), ouvrir_fichier_partage(), EcrFicPartage::syncfile(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by Modele_turbulence_hyd_base::preparer_calcul().
imprimer_ustar_mean_only()
void Turbulence_paroi_base::imprimer_ustar_mean_only (Sortie & os, int boundaries_, const TRUST_List< Nom > & boundaries_list, const Nom & nom_fichier_) const virtual
Prints mean friction velocity (u*) statistics to a file for specified boundaries.
Parameters
os Output stream for messages
boundaries_ Flag to control boundary selection (0: all boundaries, 1: specified boundaries)
boundaries_list List of boundary names to process when boundaries_=1
nom_fichier_ Output filename
Calculates and writes average u* (friction velocity) and d+ values for wall boundaries. Results are written for all boundaries combined and then for each boundary separately. Only processes fixed walls (Dirichlet_paroi_fixe) and moving walls (Dirichlet_paroi_defilante). Output format: time mean_u* mean_d+ [boundary1_u* boundary1_d+ boundary2_u* boundary2_d+ ...]
References Nom::contient(), Process::je_suis_maitre(), le_dom_Cl_dis_, le_dom_dis_, Frontiere_dis_base::le_nom(), mon_modele_turb_hyd, Front_VF::nb_faces(), Front_VF::num_premiere_face(), ouvrir_fichier_partage(), Probleme_base::schema_temps(), EcrFicPartage::syncfile(), tab_d_plus(), tab_u_star(), Schema_Temps_base::temps_courant(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by Modele_turbulence_hyd_base::imprimer().
Cisaillement_paroi()
const DoubleTab & Turbulence_paroi_base::Cisaillement_paroi () const inline
References Cisaillement_paroi_.
Referenced by Source_Robin::ajouter(), Traitement_particulier_NS_canal::calcul_reynolds_tau(), Paroi_std_hyd_VEF::calculer_hyd(), Modele_turbulence_hyd_K_Eps::calculer_viscosite_turbulente(), Modele_turbulence_hyd_K_Eps_Bicephale::calculer_viscosite_turbulente(), Champ_P1NC_implementation::filtrer_L2(), Source_Transport_Eps_Realisable_VEF_Face::mettre_a_jour(), Source_Transport_K_Realisable_VEF_Face::mettre_a_jour(), and Source_Transport_K_Eps_Realisable_VEF_Face::mettre_a_jour().
tab_u_star() [1/2]
const DoubleVect & Turbulence_paroi_base::tab_u_star () const inline
References tab_u_star_.
Referenced by Paroi_loi_WW_hyd_EF::calculer_couche_puissance(), Paroi_loi_WW_hyd_VDF::calculer_couche_puissance(), Paroi_loi_WW_hyd_VEF::calculer_couche_puissance(), ParoiVDF_TBLE_LRM::calculer_hyd(), Paroi_std_hyd_VDF_diphasique::calculer_hyd(), Paroi_loi_WW_hyd_EF::calculer_hyd(), Paroi_2couches_VDF::calculer_hyd(), Paroi_loi_Ciofalo_hyd_VDF::calculer_hyd(), Paroi_loi_WW_hyd_VDF::calculer_hyd(), Paroi_loi_WW_hyd_VEF::calculer_hyd(), Paroi_std_hyd_VEF::calculer_hyd(), Paroi_negligeable_VEF::calculer_hyd(), Paroi_std_hyd_VDF::calculer_hyd(), ParoiVDF_TBLE::calculer_hyd(), ParoiVEF_TBLE::calculer_hyd(), Paroi_std_hyd_VDF::calculer_hyd_BiK(), ParoiVDF_TBLE::calculer_hyd_BiK(), ParoiVDF_TBLE_LRM::calculer_hyd_BiK(), ParoiVEF_TBLE::calculer_hyd_BiK(), Paroi_loi_Ciofalo_hyd_VDF::calculer_local(), Paroi_std_scal_hyd_EF::calculer_scal(), Paroi_loi_WW_scal_VDF::calculer_scal(), Paroi_ODVM_scal_VDF::calculer_scal(), Paroi_std_scal_hyd_VDF::calculer_scal(), Paroi_loi_WW_scal_VEF::calculer_scal(), Paroi_scal_analytique_VEF::calculer_scal(), Paroi_std_scal_hyd_VEF::calculer_scal(), Paroi_std_hyd_VDF::calculer_sous_couche_log(), Paroi_std_hyd_VDF::calculer_sous_couche_tampon(), Paroi_std_hyd_VDF::calculer_sous_couche_visq(), Paroi_std_hyd_VDF::compute_law_komega(), Paroi_std_hyd_VDF::compute_log_layer(), Paroi_std_hyd_EF::imprimer_ustar(), Paroi_std_hyd_VDF::imprimer_ustar(), ParoiVDF_TBLE::imprimer_ustar(), Paroi_std_hyd_VEF::imprimer_ustar(), ParoiVEF_TBLE::imprimer_ustar(), Paroi_2couches_VDF::imprimer_ustar(), ParoiVDF_TBLE_LRM::imprimer_ustar(), and imprimer_ustar_mean_only().
tab_u_star() [2/2]
double Turbulence_paroi_base::tab_u_star (int face) const inline
References tab_u_star_.
tab_d_plus() [1/2]
const DoubleVect & Turbulence_paroi_base::tab_d_plus () const inline
References tab_d_plus_.
Referenced by Champ_Q1_EF::calcul_y_plus(), Champ_P1NC::calcul_y_plus(), Champ_Face_VDF::calcul_y_plus(), Champ_P1NC::calcul_y_plus_diphasique(), Champ_Face_VDF::calcul_y_plus_diphasique(), Paroi_std_hyd_VEF::calculer_hyd(), ParoiVDF_TBLE::calculer_hyd(), ParoiVEF_TBLE::calculer_hyd(), ParoiVDF_TBLE::calculer_hyd_BiK(), ParoiVEF_TBLE::calculer_hyd_BiK(), Paroi_std_hyd_EF::imprimer_ustar(), Paroi_std_hyd_VDF::imprimer_ustar(), Paroi_std_hyd_VEF::imprimer_ustar(), Paroi_2couches_VDF::imprimer_ustar(), and imprimer_ustar_mean_only().
tab_d_plus() [2/2]
double Turbulence_paroi_base::tab_d_plus (int face) const inline
References tab_d_plus_.
sauvegarder()
int Turbulence_paroi_base::sauvegarder (Sortie &) const inline override virtual
Sauvegarde d'un Objet_U sur un flot de sortie Methode a surcharger.
Parameters
(Sortie&) flot de sortie a utiliser pour la sauvegarde
Returns
(int) code de retour
Reimplemented from Objet_U.
Reimplemented in ParoiVDF_TBLE, and ParoiVEF_TBLE.
Referenced by Modele_turbulence_hyd_base::sauvegarder().
reprendre()
int Turbulence_paroi_base::reprendre (Entree &) inline override virtual
Reprise d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree&) flot d'entree a utiliser pour la reprise
Returns
(int) code de retour
Reimplemented from Objet_U.
Reimplemented in ParoiVDF_TBLE, and ParoiVEF_TBLE.
Referenced by Modele_turbulence_hyd_base::reprendre().
data_a_sauvegarder()
virtual std::vector< YAML_data > Turbulence_paroi_base::data_a_sauvegarder () const inline virtual
Referenced by Modele_turbulence_hyd_base::data_a_sauvegarder().
creer_champ()
void Turbulence_paroi_base::creer_champ (const Motcle & motlu) override virtual
Implements Champs_compris_interface.
References Champs_compris_T< FIELD_TYPE >::ajoute_champ(), champ_u_star_, champs_compris_, Probleme_base::discretisation(), Discretisation_base::discretiser_champ(), Equation_base::domaine_dis(), Objet_U_ptr::est_nul(), mon_modele_turb_hyd, and Equation_base::probleme().
Referenced by Modele_turbulence_hyd_base::creer_champ().
get_champ()
const Champ_base & Turbulence_paroi_base::get_champ (const Motcle & nom) const override virtual
Implements Champs_compris_interface.
References champ_u_star_, champs_compris_, Equation_base::domaine_Cl_dis(), Equation_base::domaine_dis(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Champs_compris_T< FIELD_TYPE >::get_champ(), Objet_U_ptr::le_nom(), Domaine_Cl_dis_base::les_conditions_limites(), Champ_Fonc_base::mettre_a_jour(), mon_modele_turb_hyd, Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), Equation_base::schema_temps(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), tab_u_star_, Schema_Temps_base::temps_courant(), and Champ_Don_base::valeurs().
Referenced by has_champ().
get_noms_champs_postraitables()
void Turbulence_paroi_base::get_noms_champs_postraitables (Noms & nom, Option opt = NONE) const override virtual
Implements Champs_compris_interface.
References TRUST_Vector< _CLASSE_ >::add(), champs_compris_, Champs_compris_T< FIELD_TYPE >::liste_noms_compris(), and Objet_U::que_suis_je().
Referenced by Paroi_hyd_base_EF::get_noms_champs_postraitables(), and Modele_turbulence_hyd_base::get_noms_champs_postraitables().
has_champ() [1/2]
bool Turbulence_paroi_base::has_champ (const Motcle & nom, TRUST_Ref< Champ_base * > & ref_champ) const override virtual
Implements Champs_compris_interface.
References champ_u_star_, champs_compris_, get_champ(), Champs_compris_T< FIELD_TYPE >::has_champ(), and Objet_U_ptr::le_nom().
Referenced by Modele_turbulence_hyd_base::get_champ(), and Modele_turbulence_hyd_base::has_champ().
has_champ() [2/2]
bool Turbulence_paroi_base::has_champ (const Motcle & nom) const override virtual
Implements Champs_compris_interface.
References champ_u_star_, champs_compris_, Champs_compris_T< FIELD_TYPE >::has_champ(), and Objet_U_ptr::le_nom().
ouvrir_fichier_partage() [1/2]
void Turbulence_paroi_base::ouvrir_fichier_partage (EcrFicPartage & Ustar, const Nom & extension) const
Ouverture/creation d'un fichier d'impression de Face, uplus_, dplus_, tab_u_star, Cisaillement_paroi_.
References Process::je_suis_maitre(), Probleme_U::le_nom(), mon_modele_turb_hyd, nb_impr_, Objet_U::nom_du_cas(), EcrFicPartage::ouvrir(), Probleme_base::reprise_effectuee(), Probleme_base::schema_temps(), and Schema_Temps_base::temps_courant().
Referenced by imprimer_premiere_ligne_ustar(), Paroi_std_hyd_EF::imprimer_ustar(), Paroi_std_hyd_VDF::imprimer_ustar(), Paroi_std_hyd_VEF::imprimer_ustar(), Paroi_2couches_VDF::imprimer_ustar(), and imprimer_ustar_mean_only().
ouvrir_fichier_partage() [2/2]
void Turbulence_paroi_base::ouvrir_fichier_partage (EcrFicPartage & fichier, const Nom & nom_fichier, const Nom & extension) const
Ouverture/creation d'un fichier d'impression de moyennes de uplus_, dplus_, tab_u_star.
References mon_modele_turb_hyd, nb_impr0_, EcrFicPartage::ouvrir(), and Probleme_base::reprise_effectuee().
use_shear()
virtual bool Turbulence_paroi_base::use_shear () const inline virtual
Reimplemented in Paroi_2couches_VDF, Paroi_negligeable_EF, Paroi_negligeable_VDF, and Paroi_negligeable_VEF.
Referenced by Champ_Q1_EF::calcul_y_plus(), Champ_P1NC::calcul_y_plus(), Champ_Face_VDF::calcul_y_plus(), Champ_P1NC::calcul_y_plus_diphasique(), and Modele_turbulence_hyd_base::utiliser_loi_paroi().
Member Data Documentation
info_obj
const Type_info Turbulence_paroi_base::info_obj static
mon_modele_turb_hyd
TRUST_Ref< Modele_turbulence_hyd_base *> Turbulence_paroi_base::mon_modele_turb_hyd protected
Referenced by associer_modele(), ParoiVDF_TBLE_LRM::calculer_hyd(), Paroi_std_hyd_VEF::calculer_hyd(), Paroi_negligeable_VDF::calculer_hyd(), Paroi_negligeable_VEF::calculer_hyd(), Paroi_std_hyd_VDF_diphasique::calculer_hyd(), Paroi_std_hyd_VEF_diphasique::calculer_hyd(), Paroi_loi_WW_hyd_EF::calculer_hyd(), Paroi_std_hyd_EF::calculer_hyd(), Paroi_2couches_VDF::calculer_hyd(), Paroi_loi_Ciofalo_hyd_VDF::calculer_hyd(), Paroi_loi_WW_hyd_VDF::calculer_hyd(), Paroi_loi_WW_hyd_VEF::calculer_hyd(), Paroi_std_hyd_VDF::calculer_hyd(), Paroi_UTAU_IMP_VDF::calculer_hyd(), ParoiVDF_TBLE::calculer_hyd(), ParoiVEF_TBLE::calculer_hyd(), Paroi_std_hyd_VDF::calculer_hyd_BiK(), Paroi_UTAU_IMP_VDF::calculer_hyd_BiK(), ParoiVDF_TBLE::calculer_hyd_BiK(), ParoiVDF_TBLE_LRM::calculer_hyd_BiK(), Paroi_std_hyd_VEF::calculer_hyd_BiK(), ParoiVEF_TBLE::calculer_hyd_BiK(), Paroi_std_hyd_VDF::calculer_moyennes_parois(), Paroi_std_hyd_VEF::check_turbulence_model(), Paroi_std_hyd_VDF::compute_law_komega(), Paroi_hyd_base_EF::creer_champ(), creer_champ(), Paroi_hyd_base_EF::get_champ(), get_champ(), ParoiVDF_TBLE::getPbBase(), ParoiVEF_TBLE::getPbBase(), ParoiVDF_TBLE::imprimer_ustar(), ParoiVEF_TBLE::imprimer_ustar(), ParoiVDF_TBLE_LRM::imprimer_ustar(), imprimer_ustar_mean_only(), ParoiVDF_TBLE::init_lois_paroi(), ParoiVDF_TBLE_LRM::init_lois_paroi(), ParoiVEF_TBLE::init_lois_paroi(), Paroi_std_hyd_EF::init_lois_paroi_hydraulique(), Paroi_2couches_VDF::init_lois_paroi_hydraulique(), Paroi_std_hyd_VDF::init_lois_paroi_hydraulique(), Paroi_std_hyd_VEF::init_lois_paroi_hydraulique(), Paroi_loi_WW_hyd_EF::init_lois_paroi_hydraulique(), Paroi_loi_Ciofalo_hyd_VDF::init_lois_paroi_hydraulique(), Paroi_loi_WW_hyd_VDF::init_lois_paroi_hydraulique(), Paroi_loi_WW_hyd_VEF::init_lois_paroi_hydraulique(), Paroi_std_hyd_VDF::initialize_wall_law_komega(), ouvrir_fichier_partage(), LoiParoiHybride_VDF::readOn(), LoiParoiHybride_VEF::readOn(), ParoiVDF_TBLE::reprendre(), ParoiVEF_TBLE::reprendre(), ParoiVDF_TBLE::sauvegarder(), and ParoiVEF_TBLE::sauvegarder().
Cisaillement_paroi_
DoubleTab Turbulence_paroi_base::Cisaillement_paroi_ protected
Referenced by LoiParoiHybride_VDF::calculer_hyd(), ParoiVDF_TBLE_LRM::calculer_hyd(), LoiParoiHybride_VEF::calculer_hyd(), Paroi_std_hyd_VEF::calculer_hyd(), Paroi_std_hyd_VDF_diphasique::calculer_hyd(), Paroi_std_hyd_VEF_diphasique::calculer_hyd(), Paroi_loi_WW_hyd_EF::calculer_hyd(), Paroi_std_hyd_EF::calculer_hyd(), Paroi_2couches_VDF::calculer_hyd(), Paroi_loi_Ciofalo_hyd_VDF::calculer_hyd(), Paroi_loi_WW_hyd_VDF::calculer_hyd(), Paroi_loi_WW_hyd_VEF::calculer_hyd(), Paroi_std_hyd_VDF::calculer_hyd(), Paroi_UTAU_IMP_VDF::calculer_hyd(), ParoiVDF_TBLE::calculer_hyd(), ParoiVEF_TBLE::calculer_hyd(), LoiParoiHybride_VDF::calculer_hyd_BiK(), Paroi_std_hyd_VDF::calculer_hyd_BiK(), Paroi_UTAU_IMP_VDF::calculer_hyd_BiK(), ParoiVDF_TBLE::calculer_hyd_BiK(), ParoiVDF_TBLE_LRM::calculer_hyd_BiK(), LoiParoiHybride_VEF::calculer_hyd_BiK(), Paroi_std_hyd_VEF::calculer_hyd_BiK(), ParoiVEF_TBLE::calculer_hyd_BiK(), Cisaillement_paroi(), Paroi_std_hyd_VDF::compute_law_komega(), Paroi_std_hyd_EF::imprimer_ustar(), Paroi_std_hyd_VDF::imprimer_ustar(), Paroi_std_hyd_VEF::imprimer_ustar(), Paroi_2couches_VDF::imprimer_ustar(), Paroi_std_hyd_EF::init_lois_paroi(), LoiParoiHybride_VDF::init_lois_paroi(), ParoiVDF_TBLE_LRM::init_lois_paroi(), LoiParoiHybride_VEF::init_lois_paroi(), Paroi_std_hyd_VEF::init_lois_paroi(), Paroi_hyd_base_EF::init_lois_paroi_(), Paroi_hyd_base_VDF::init_lois_paroi_(), Paroi_hyd_base_VEF::init_lois_paroi_(), and Paroi_std_hyd_VDF::tau_tang().
tab_u_star_
DoubleVect Turbulence_paroi_base::tab_u_star_ protected
Referenced by ParoiVDF_TBLE_LRM::calculer_hyd(), Paroi_std_hyd_VEF::calculer_hyd(), Paroi_negligeable_VDF::calculer_hyd(), Paroi_negligeable_VEF::calculer_hyd(), Paroi_std_hyd_VDF_diphasique::calculer_hyd(), Paroi_std_hyd_VEF_diphasique::calculer_hyd(), Paroi_std_hyd_EF::calculer_hyd(), Paroi_2couches_VDF::calculer_hyd(), Paroi_std_hyd_VDF::calculer_hyd(), ParoiVDF_TBLE::calculer_hyd(), ParoiVEF_TBLE::calculer_hyd(), Paroi_std_hyd_VDF::calculer_hyd_BiK(), ParoiVDF_TBLE::calculer_hyd_BiK(), ParoiVDF_TBLE_LRM::calculer_hyd_BiK(), Paroi_std_hyd_VEF::calculer_hyd_BiK(), ParoiVEF_TBLE::calculer_hyd_BiK(), Paroi_loi_Ciofalo_hyd_VDF::calculer_u_star_couche_log(), Paroi_loi_WW_hyd_EF::calculer_u_star_couche_puissance(), Paroi_loi_WW_hyd_VDF::calculer_u_star_couche_puissance(), Paroi_loi_WW_hyd_VEF::calculer_u_star_couche_puissance(), Paroi_2couches_VDF::calculer_u_star_sous_couche_log(), Paroi_std_hyd_VDF::calculer_u_star_sous_couche_log(), Paroi_2couches_VDF::calculer_u_star_sous_couche_tampon(), Paroi_std_hyd_VDF::calculer_u_star_sous_couche_tampon(), Paroi_loi_WW_hyd_EF::calculer_u_star_sous_couche_visq(), Paroi_loi_Ciofalo_hyd_VDF::calculer_u_star_sous_couche_visq(), Paroi_std_hyd_VDF::calculer_u_star_sous_couche_visq(), Paroi_loi_WW_hyd_VEF::calculer_u_star_sous_couche_visq(), Paroi_std_hyd_VDF::compute_buffer_layer(), Paroi_std_hyd_VDF::compute_law_komega(), Paroi_hyd_base_EF::get_champ(), get_champ(), Paroi_std_hyd_EF::init_lois_paroi(), Paroi_std_hyd_VEF::init_lois_paroi(), Paroi_hyd_base_EF::init_lois_paroi_(), Paroi_hyd_base_VDF::init_lois_paroi_(), Paroi_hyd_base_VEF::init_lois_paroi_(), and tab_u_star().
tab_d_plus_
DoubleVect Turbulence_paroi_base::tab_d_plus_ protected
Referenced by ParoiVDF_TBLE_LRM::calculer_hyd(), Paroi_std_hyd_VEF::calculer_hyd(), Paroi_std_hyd_VDF_diphasique::calculer_hyd(), Paroi_std_hyd_VEF_diphasique::calculer_hyd(), Paroi_std_hyd_EF::calculer_hyd(), Paroi_2couches_VDF::calculer_hyd(), Paroi_std_hyd_VDF::calculer_hyd(), ParoiVDF_TBLE::calculer_hyd(), ParoiVEF_TBLE::calculer_hyd(), Paroi_std_hyd_VDF::calculer_hyd_BiK(), ParoiVDF_TBLE::calculer_hyd_BiK(), ParoiVDF_TBLE_LRM::calculer_hyd_BiK(), Paroi_std_hyd_VEF::calculer_hyd_BiK(), ParoiVEF_TBLE::calculer_hyd_BiK(), Paroi_loi_Ciofalo_hyd_VDF::calculer_local(), Paroi_loi_WW_hyd_EF::calculer_u_star_couche_puissance(), Paroi_loi_WW_hyd_EF::calculer_u_star_sous_couche_visq(), Paroi_std_hyd_VDF::compute_law_komega(), Paroi_std_hyd_EF::init_lois_paroi(), Paroi_std_hyd_VEF::init_lois_paroi(), Paroi_hyd_base_EF::init_lois_paroi_(), Paroi_hyd_base_VDF::init_lois_paroi_(), Paroi_hyd_base_VEF::init_lois_paroi_(), and tab_d_plus().
champ_u_star_
TRUST_Deriv< Champ_Fonc_base > Turbulence_paroi_base::champ_u_star_ mutable protected
Referenced by Paroi_hyd_base_EF::creer_champ(), creer_champ(), Paroi_hyd_base_EF::get_champ(), get_champ(), Paroi_hyd_base_EF::has_champ(), and has_champ().
nb_impr_
int Turbulence_paroi_base::nb_impr_ = 0 mutable protected
Referenced by ouvrir_fichier_partage().
nb_impr0_
int Turbulence_paroi_base::nb_impr0_ = 0 protected
Referenced by ouvrir_fichier_partage().
champs_compris_
Champs_compris Turbulence_paroi_base::champs_compris_ protected
Referenced by Paroi_hyd_base_EF::creer_champ(), creer_champ(), Paroi_hyd_base_EF::get_champ(), get_champ(), get_noms_champs_postraitables(), Paroi_hyd_base_EF::has_champ(), and has_champ().
le_dom_dis_
TRUST_Ref< Domaine_VF *> Turbulence_paroi_base::le_dom_dis_ protected
Referenced by Paroi_hyd_base_EF::associer(), Paroi_hyd_base_VDF::associer(), Paroi_hyd_base_VEF::associer(), LoiParoiHybride_VDF::calculer_hyd(), ParoiVDF_TBLE_LRM::calculer_hyd(), Paroi_std_hyd_VEF::calculer_hyd(), Paroi_negligeable_VDF::calculer_hyd(), Paroi_negligeable_VEF::calculer_hyd(), Paroi_std_hyd_VDF_diphasique::calculer_hyd(), Paroi_std_hyd_VEF_diphasique::calculer_hyd(), Paroi_loi_WW_hyd_EF::calculer_hyd(), Paroi_std_hyd_EF::calculer_hyd(), Paroi_2couches_VDF::calculer_hyd(), Paroi_loi_Ciofalo_hyd_VDF::calculer_hyd(), Paroi_loi_WW_hyd_VDF::calculer_hyd(), Paroi_loi_WW_hyd_VEF::calculer_hyd(), Paroi_std_hyd_VDF::calculer_hyd(), Paroi_UTAU_IMP_VDF::calculer_hyd(), ParoiVDF_TBLE::calculer_hyd(), ParoiVEF_TBLE::calculer_hyd(), LoiParoiHybride_VDF::calculer_hyd_BiK(), Paroi_std_hyd_VDF::calculer_hyd_BiK(), Paroi_UTAU_IMP_VDF::calculer_hyd_BiK(), ParoiVDF_TBLE::calculer_hyd_BiK(), ParoiVDF_TBLE_LRM::calculer_hyd_BiK(), Paroi_std_hyd_VEF::calculer_hyd_BiK(), ParoiVEF_TBLE::calculer_hyd_BiK(), Paroi_std_hyd_VDF::calculer_moyennes_parois(), Paroi_std_hyd_VDF::compute_law_komega(), Paroi_hyd_base_EF::get_champ(), imprimer_premiere_ligne_ustar(), Paroi_std_hyd_EF::imprimer_ustar(), Paroi_std_hyd_VDF::imprimer_ustar(), ParoiVDF_TBLE::imprimer_ustar(), Paroi_std_hyd_VEF::imprimer_ustar(), ParoiVEF_TBLE::imprimer_ustar(), Paroi_2couches_VDF::imprimer_ustar(), ParoiVDF_TBLE_LRM::imprimer_ustar(), imprimer_ustar_mean_only(), Paroi_std_hyd_EF::init_lois_paroi(), LoiParoiHybride_VDF::init_lois_paroi(), Paroi_2couches_VDF::init_lois_paroi(), Paroi_std_hyd_VDF::init_lois_paroi(), ParoiVDF_TBLE::init_lois_paroi(), ParoiVDF_TBLE_LRM::init_lois_paroi(), Paroi_std_hyd_VEF::init_lois_paroi(), ParoiVEF_TBLE::init_lois_paroi(), Paroi_negligeable_VEF::init_lois_paroi(), Paroi_hyd_base_EF::init_lois_paroi_(), Paroi_hyd_base_VDF::init_lois_paroi_(), Paroi_hyd_base_VEF::init_lois_paroi_(), Paroi_std_hyd_VDF::initialize_wall_law_komega(), Paroi_std_hyd_VDF::preparer_calcul_hyd(), LoiParoiHybride_VDF::readOn(), ParoiVDF_TBLE::reprendre(), ParoiVEF_TBLE::reprendre(), ParoiVDF_TBLE::sauvegarder(), ParoiVEF_TBLE::sauvegarder(), and Paroi_std_hyd_VDF::tau_tang().
le_dom_Cl_dis_
TRUST_Ref< Domaine_Cl_dis_base *> Turbulence_paroi_base::le_dom_Cl_dis_ protected
Referenced by Paroi_hyd_base_EF::associer(), Paroi_hyd_base_VDF::associer(), Paroi_hyd_base_VEF::associer(), LoiParoiHybride_VDF::calculer_hyd(), ParoiVDF_TBLE_LRM::calculer_hyd(), Paroi_std_hyd_VEF::calculer_hyd(), Paroi_negligeable_VDF::calculer_hyd(), Paroi_negligeable_VEF::calculer_hyd(), Paroi_std_hyd_VDF_diphasique::calculer_hyd(), Paroi_std_hyd_VEF_diphasique::calculer_hyd(), Paroi_loi_WW_hyd_EF::calculer_hyd(), Paroi_std_hyd_EF::calculer_hyd(), Paroi_2couches_VDF::calculer_hyd(), Paroi_loi_Ciofalo_hyd_VDF::calculer_hyd(), Paroi_loi_WW_hyd_VDF::calculer_hyd(), Paroi_loi_WW_hyd_VEF::calculer_hyd(), Paroi_std_hyd_VDF::calculer_hyd(), Paroi_UTAU_IMP_VDF::calculer_hyd(), ParoiVDF_TBLE::calculer_hyd(), ParoiVEF_TBLE::calculer_hyd(), LoiParoiHybride_VDF::calculer_hyd_BiK(), Paroi_std_hyd_VDF::calculer_hyd_BiK(), Paroi_UTAU_IMP_VDF::calculer_hyd_BiK(), ParoiVDF_TBLE::calculer_hyd_BiK(), ParoiVDF_TBLE_LRM::calculer_hyd_BiK(), Paroi_std_hyd_VEF::calculer_hyd_BiK(), ParoiVEF_TBLE::calculer_hyd_BiK(), Paroi_std_hyd_VDF::calculer_moyennes_parois(), Paroi_std_hyd_VDF::compute_law_komega(), imprimer_premiere_ligne_ustar(), Paroi_std_hyd_EF::imprimer_ustar(), Paroi_std_hyd_VDF::imprimer_ustar(), Paroi_std_hyd_VEF::imprimer_ustar(), Paroi_2couches_VDF::imprimer_ustar(), imprimer_ustar_mean_only(), ParoiVDF_TBLE::init_lois_paroi(), ParoiVDF_TBLE_LRM::init_lois_paroi(), ParoiVEF_TBLE::init_lois_paroi(), Paroi_negligeable_VEF::init_lois_paroi(), Paroi_std_hyd_VDF::preparer_calcul_hyd(), LoiParoiHybride_VDF::readOn(), ParoiVDF_TBLE::reprendre(), ParoiVEF_TBLE::reprendre(), ParoiVDF_TBLE::sauvegarder(), and ParoiVEF_TBLE::sauvegarder().