TrioCFD: Solid_Particle_base Class Reference
Solid_Particle_base Class Reference
#include <Solid_Particle_base.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Fluide_Incompressible
const Type_info * get_info () const override
void verifier_coherence_champs (int &err, Nom &message) override
Public Member Functions inherited from Fluide_base
const Type_info * get_info () const override
void mettre_a_jour (double) override
void verifier_coherence_champs (int &err, Nom &message) override
Public Member Functions inherited from Milieu_base
virtual int a_gravite () const
int associer_ (Objet_U &) override
virtual void associer_gravite (const Champ_Don_base &)
virtual Champ_Don_base & beta_t ()
virtual const Champ_Don_base & beta_t () const
virtual Champ_Don_base & capacite_calorifique ()
virtual const Champ_Don_base & capacite_calorifique () const
virtual Champ_Don_base & conductivite ()
virtual const Champ_Don_base & conductivite () const
virtual Champ_Don_base & diffusivite ()
virtual const Champ_Don_base & diffusivite () const
virtual int est_deja_associe ()
const Type_info * get_info () const override
virtual Champ_Don_base & gravite ()
virtual const Champ_Don_base & gravite () const
const Nom & le_nom () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual Champ_base & masse_volumique ()
virtual const Champ_base & masse_volumique () const
void nommer (const Nom &) override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Fluide_base
void creer_nu ()
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Milieu_base
virtual void calculer_alpha ()
void ecrire (Sortie &) const
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
Description: This class describes spherical solid particles. This class is used in the module fluid_particle_interaction. Solid particles must be modeled with a high viscosity ratio relative to the fluid. suffix sphere :for sphere flow, therefore all particles have the same physical properties. The radius and e_dry coeff are used for the computation of the solid-solid interactions. See Modele_Collision_FT Location: ${TrioCFD_ROOT}/src/Multiphase/fluid_particle_interaction
Constructor & Destructor Documentation
~Solid_Particle_base()
Solid_Particle_base::~Solid_Particle_base () override
Solid_Particle_base()
Solid_Particle_base::Solid_Particle_base ()
Member Function Documentation
info()
const Type_info * Solid_Particle_base::info () static
get_info()
const Type_info * Solid_Particle_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Fluide_Incompressible.
Reimplemented in Solid_Particle_sphere, and Solid_Particle_spheroid.
self_cast() [1/2]
Solid_Particle_base & Solid_Particle_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Solid_Particle_base & Solid_Particle_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Solid_Particle_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Fluide_Incompressible.
Reimplemented in Solid_Particle_sphere, and Solid_Particle_spheroid.
References e_dry_, and Fluide_Incompressible::printOn().
readOn()
Entree & Solid_Particle_base::readOn (Entree & is) override protected virtual
Lit les caracteristiques du fluide a partir d'un flot d'entree.
Format: Fluide_base { Mu type_champ bloc de lecture de champ Rho Champ_Uniforme 1 vrel [Cp Champ_Uniforme 1 vrel] [Lambda type_champ bloc de lecture de champ] [Beta_th type_champ bloc de lecture de champ] [Beta_co type_champ bloc de lecture de champ] } cf Milieu_base::readOn
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Exceptions
accolade ouvrante attendue
Reimplemented from Fluide_Incompressible.
Reimplemented in Solid_Particle_sphere, and Solid_Particle_spheroid.
References Fluide_Incompressible::readOn().
Referenced by Solid_Particle_arbitrary::readOn(), Solid_Particle_sphere::readOn(), and Solid_Particle_spheroid::readOn().
set_param()
void Solid_Particle_base::set_param (Param & param) override virtual
Reimplemented from Fluide_Incompressible.
Reimplemented in Solid_Particle_sphere, and Solid_Particle_spheroid.
References Param::ajouter(), e_dry_, Param::REQUIRED, and Fluide_Incompressible::set_param().
Referenced by Solid_Particle_arbitrary::set_param(), Solid_Particle_sphere::set_param(), and Solid_Particle_spheroid::set_param().
set_volume()
void Solid_Particle_base::set_volume (const double volume) inline
References volume_.
Referenced by Solid_Particle_sphere::readOn().
set_mass()
void Solid_Particle_base::set_mass (const double mass) inline
References mass_.
Referenced by Solid_Particle_sphere::readOn().
set_equivalent_diameter()
void Solid_Particle_base::set_equivalent_diameter (const double equivalent_diameter) inline
References equivalent_diameter_.
Referenced by Solid_Particle_sphere::readOn(), and Solid_Particle_spheroid::readOn().
set_equivalent_radius()
void Solid_Particle_base::set_equivalent_radius (const double equivalent_radius) inline
References equivalent_radius_.
Referenced by Solid_Particle_sphere::readOn(), and Solid_Particle_spheroid::readOn().
get_e_dry()
const double & Solid_Particle_base::get_e_dry () const inline
References e_dry_.
Referenced by Collision_Model_FT_base::set_spring_properties().
get_volume()
const double & Solid_Particle_base::get_volume () const inline
References volume_.
get_mass()
const double & Solid_Particle_base::get_mass () const inline
References mass_.
Referenced by Collision_Model_FT_base::set_spring_properties().
get_equivalent_radius()
const double & Solid_Particle_base::get_equivalent_radius () const inline
References equivalent_radius_.
Referenced by Post_Processing_Hydrodynamic_Forces_Stokes::compute_friction_force_complet_tensor(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_friction_force_projected_tensor(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_neighbors_coordinates_fluid_fa7(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_pressure_force_trilinear_linear(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_pressure_interf(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_vinf_Stokes(), Post_Processing_Hydrodynamic_Forces::compute_viscosity_edges_sphere(), Post_Processing_Hydrodynamic_Forces_Stokes::fill_sigma_Stokes_th(), Post_Processing_Hydrodynamic_Forces_Stokes::fill_Stokes_pressure_field(), and Post_Processing_Hydrodynamic_Forces_Stokes::fill_Stokes_velocity_field().
get_equivalent_diameter()
const double & Solid_Particle_base::get_equivalent_diameter () const inline
References equivalent_diameter_.
Referenced by Collision_Model_FT_base::preparer_calcul().
Member Data Documentation
info_obj
const Type_info Solid_Particle_base::info_obj static
e_dry_
double Solid_Particle_base::e_dry_ =0. protected
Referenced by get_e_dry(), printOn(), and set_param().
volume_
double Solid_Particle_base::volume_ =0. protected
Referenced by get_volume(), Solid_Particle_sphere::readOn(), and set_volume().
mass_
double Solid_Particle_base::mass_ =0. protected
Referenced by get_mass(), and set_mass().
equivalent_radius_
double Solid_Particle_base::equivalent_radius_ =0 protected
Referenced by get_equivalent_radius(), and set_equivalent_radius().
equivalent_diameter_
double Solid_Particle_base::equivalent_diameter_ =0 protected
Referenced by get_equivalent_diameter(), and set_equivalent_diameter().