TrioCFD: Typer_Lire Class Reference
Typer_Lire Class Reference
#include <Typer_Lire.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Additional Inherited Members
Static Public Member Functions inherited from Interprete
static Objet_U & objet (const Nom &)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Constructor & Destructor Documentation
Typer_Lire()
Typer_Lire::Typer_Lire ()
~Typer_Lire()
Typer_Lire::~Typer_Lire ()
Member Function Documentation
cree_instance()
Objet_U * Typer_Lire::cree_instance () static
taille_memoire()
unsigned Typer_Lire::taille_memoire () const override virtual
Reimplemented from Lire.
duplique()
int Typer_Lire::duplique () const override virtual
Reimplemented from Lire.
info()
const Type_info * Typer_Lire::info () static
get_info()
const Type_info * Typer_Lire::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Lire.
self_cast() [1/2]
Typer_Lire & Typer_Lire::self_cast (Objet_U & r) static
self_cast() [2/2]
const Typer_Lire & Typer_Lire::self_cast (const Objet_U & r) static
printOn()
Sortie & Typer_Lire::printOn (Sortie & x) const override protected virtual
appel a la methode printOn de la classe Interprete
Reimplemented from Lire.
References Lire::printOn().
readOn()
Entree & Typer_Lire::readOn (Entree & is) override protected virtual
appel a la methode readOn de la classe Interprete
Reimplemented from Lire.
References Lire::readOn().
interpreter()
Entree & Typer_Lire::interpreter (Entree & is) override virtual
Read an object.
Reimplemented from Lire.
References Interprete_bloc::ajouter(), Interprete_bloc::interprete_courant(), Interprete::objet(), Interprete::objet_existant(), and Objet_U_ptr::typer().
Member Data Documentation
info_obj
const Type_info Typer_Lire::info_obj static