TrioCFD: Ch_front_var_instationnaire_dep Class Reference
Ch_front_var_instationnaire_dep Class Reference
#include <Ch_front_var_instationnaire_dep.h>
Public Member Functions
const Type_info * get_info () const override
int initialiser (double temps, const Champ_Inc_base &inco) override
Public Member Functions inherited from Champ_front_var_instationnaire
int avancer (double temps) override
const Type_info * get_info () const override
int initialiser (double temps, const Champ_Inc_base &inco) override
int reculer (double temps) override
const DoubleTab & valeurs_au_temps (double temps) const override
DoubleTab & valeurs_au_temps (double temps) override
const Type_info * get_info () const override
int initialiser (double temps, const Champ_Inc_base &inco) override
Public Member Functions inherited from Champ_front_base
virtual void associer_fr_dis_base (const Frontiere_dis_base &)
virtual int avancer (double temps)
virtual void calculer_coeffs_echange (double temps)
virtual void fixer_nb_valeurs_temporelles (int nb_cases)
virtual Frontiere_dis_base & frontiere_dis ()
virtual const Frontiere_dis_base & frontiere_dis () const
const Type_info * get_info () const override
virtual int initialiser (double temps, const Champ_Inc_base &inco)
virtual void mettre_a_jour (double temps)
virtual int reculer (double temps)
virtual const DoubleTab & valeurs () const override
virtual DoubleTab & valeurs () override
virtual void valeurs_face (int, DoubleVect &) const
Public Member Functions inherited from Field_base
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
virtual void fixer_nb_comp (int i)
virtual const Nom & fixer_nom_compo (const Nom &)
virtual const Nom & fixer_nom_compo (int, const Nom &)
virtual const Noms & fixer_noms_compo (const Noms &)
virtual const Nom & fixer_unite (const Nom &)
virtual const Nom & fixer_unite (int i, const Nom &)
virtual const Noms & fixer_unites (const Noms &)
const Type_info * get_info () const override
const Nom & nom_compo (int) const
void nommer (const Nom &) override
const Nom & unite () const
const Nom & unite (int) const
const Noms & unites () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Champ_Proto
int lire_dimension (Entree &, const Nom &)
int lire_dimension (int dim, const Nom &le_nom_)
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Champ_front_var_instationnaire
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Field_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
variable en espace, instationnaire en temps, et pouvant
dependre de donnees exterieures au champ.
De ce fait, la methode mettre_a_jour utilise des donnees
externes, et la methode initialiser ne peut pas appeler la
methode mettre_a_jour.  Elle peut en revanche utiliser
l'inconnue qui lui est passee en parametre comme une premiere
estimation (c'est ce qui est code par defaut).
Constructor & Destructor Documentation
Ch_front_var_instationnaire_dep()
Ch_front_var_instationnaire_dep::Ch_front_var_instationnaire_dep ()
~Ch_front_var_instationnaire_dep()
Ch_front_var_instationnaire_dep::~Ch_front_var_instationnaire_dep ()
Member Function Documentation
cree_instance()
Objet_U * Ch_front_var_instationnaire_dep::cree_instance () static
taille_memoire()
unsigned Ch_front_var_instationnaire_dep::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Ch_front_input_ALE, Champ_front_ALE, Champ_front_ALE_Beam, Champ_front_ALE_projection, Champ_front_contact_rayo_transp_VEF, Champ_front_contact_rayo_semi_transp_VEF, Boundary_field_keps_from_ud, Champ_front_recyclage, Champ_front_pression_from_u, Champ_front_synt, Champ_front_fonc_gradient_VDF, Champ_front_contact_fictif_VEF, Champ_front_contact_VEF, Champ_front_fonc_gradient_VEF, and Champ_front_tangentiel_VEF.
duplique()
int Ch_front_var_instationnaire_dep::duplique () const override virtual
Implements Objet_U.
Reimplemented in Ch_front_input_ALE, Champ_front_ALE, Champ_front_ALE_Beam, Champ_front_ALE_projection, Champ_front_contact_rayo_transp_VEF, Champ_front_contact_rayo_semi_transp_VEF, Boundary_field_keps_from_ud, Champ_front_recyclage, Champ_front_pression_from_u, Champ_front_synt, Champ_front_fonc_gradient_VDF, Champ_front_contact_fictif_VEF, Champ_front_contact_VEF, Champ_front_fonc_gradient_VEF, and Champ_front_tangentiel_VEF.
info()
const Type_info * Ch_front_var_instationnaire_dep::info () static
get_info()
const Type_info * Ch_front_var_instationnaire_dep::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
Reimplemented in Ch_front_input_ALE, Champ_front_ALE, Champ_front_ALE_Beam, Champ_front_ALE_projection, Champ_front_contact_rayo_transp_VEF, Champ_front_contact_rayo_semi_transp_VEF, Boundary_field_keps_from_ud, Champ_front_recyclage, Champ_front_pression_from_u, Champ_front_synt, Champ_front_fonc_gradient_VDF, Champ_front_contact_fictif_VEF, Champ_front_contact_VEF, Champ_front_fonc_gradient_VEF, and Champ_front_tangentiel_VEF.
self_cast() [1/2]
Ch_front_var_instationnaire_dep & Ch_front_var_instationnaire_dep::self_cast (Objet_U & r) static
self_cast() [2/2]
const Ch_front_var_instationnaire_dep & Ch_front_var_instationnaire_dep::self_cast (const Objet_U & r) static
printOn()
Sortie & Ch_front_var_instationnaire_dep::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
Reimplemented in Ch_front_input_ALE, Champ_front_ALE, Champ_front_ALE_Beam, Champ_front_ALE_projection, Champ_front_contact_rayo_transp_VEF, Champ_front_contact_rayo_semi_transp_VEF, Boundary_field_keps_from_ud, Champ_front_recyclage, Champ_front_pression_from_u, Champ_front_synt, Champ_front_fonc_gradient_VDF, Champ_front_contact_fictif_VEF, Champ_front_contact_VEF, Champ_front_fonc_gradient_VEF, and Champ_front_tangentiel_VEF.
References Field_base::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Ch_front_var_instationnaire_dep::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
Reimplemented in Ch_front_input_ALE, Champ_front_ALE, Champ_front_ALE_Beam, Champ_front_ALE_projection, Champ_front_contact_rayo_transp_VEF, Champ_front_contact_rayo_semi_transp_VEF, Boundary_field_keps_from_ud, Champ_front_recyclage, Champ_front_pression_from_u, Champ_front_synt, Champ_front_fonc_gradient_VDF, Champ_front_contact_fictif_VEF, Champ_front_contact_VEF, Champ_front_fonc_gradient_VEF, and Champ_front_tangentiel_VEF.
References Field_base::fixer_nb_comp().
initialiser()
int Ch_front_var_instationnaire_dep::initialiser (double temps, const Champ_Inc_base & inco) override virtual
Initialisation en debut de calcul.
Imperativement cette methode ne doit pas utiliser de donnees externes a l'equation (couplage). Si mettre_a_jour le fait, alors initialiser ne doit pas appeler mettre_a_jour.
Returns
(0 en cas d'erreur, 1 sinon.)
Reimplemented from Champ_front_base.
Reimplemented in Ch_front_input_ALE, Champ_front_ALE, Champ_front_contact_rayo_transp_VEF, Champ_front_contact_rayo_semi_transp_VEF, Boundary_field_keps_from_ud, Champ_front_recyclage, Champ_front_pression_from_u, Champ_front_synt, Champ_front_contact_VEF, and Champ_front_tangentiel_VEF.
References Objet_U::dimension, Champ_Inc_base::domaine_dis_base(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Frontiere_dis_base::frontiere(), Champ_front_base::frontiere_dis(), Champ_front_var_instationnaire::initialiser(), Champ_front_base::les_valeurs, Field_base::nb_comp(), Domaine_dis_base::nb_elem(), Objet_U::que_suis_je(), Champ_base::temps(), Roue::valeurs(), and Champ_Inc_base::valeurs().
Referenced by Champ_front_ALE::initialiser(), Boundary_field_keps_from_ud::initialiser(), Ch_front_input::initialiser(), Champ_front_recyclage::initialiser(), Champ_front_pression_from_u::initialiser(), Champ_front_synt::initialiser(), Champ_front_contact_VEF::initialiser(), Champ_front_tangentiel_VEF::initialiser(), Boundary_field_inward::initialiser(), Champ_front_xyz_debit::initialiser(), and Champ_front_calc::initialiser().
affecter_()
Champ_front_base & Ch_front_var_instationnaire_dep::affecter_ (const Champ_front_base & ch) override virtual
Implements Champ_front_base.
Reimplemented in Ch_front_input_ALE, Champ_front_ALE, Champ_front_contact_rayo_transp_VEF, Champ_front_contact_rayo_semi_transp_VEF, Champ_front_synt, and Champ_front_contact_VEF.
Member Data Documentation
info_obj
const Type_info Ch_front_var_instationnaire_dep::info_obj static