TrioCFD: LecFicDiffuseBin Class Reference
LecFicDiffuseBin Class Reference
#include <LecFicDiffuseBin.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from LecFicDiffuse
const Type_info * get_info () const override
LecFicDiffuse (const char *name, std::ios_base::openmode mode=ios::in)
int ouvrir (const char *name, std::ios_base::openmode mode=ios::in) override
Public Member Functions inherited from Lec_Diffuse_base
int get (char *buf, std::streamsize bufsize) override
const Type_info * get_info () const override
void set_bin (bool bin) override
void set_check_types (bool flag) override
const Type_info * get_info () const override
const Type_info * get_info () const override
virtual int get (char *buf, std::streamsize bufsize)
void set_bin (bool bin) override
virtual void set_check_types (bool flag)
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Entree
virtual int error_handle_ (int fail_flag)
Protected Member Functions inherited from AbstractIO
template<typename _TYPE_ >
bool must_convert () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Attributes inherited from AbstractIO
bool avoid_conversion_
Detailed Description
This class implements the operators and virtual methods of the EFichier class in the following way: The file to read is physically locate on the disk of the machine hosting the master task of the Trio-U application (the process of rank 0 in the "tous" group) and each item read from this file is published to all other processes of the "tous" group. It is the same for the methods of inspection of the state of a file.
Constructor & Destructor Documentation
~LecFicDiffuseBin()
LecFicDiffuseBin::~LecFicDiffuseBin ()
LecFicDiffuseBin() [1/2]
LecFicDiffuseBin::LecFicDiffuseBin () inline
References Lec_Diffuse_base::set_bin().
LecFicDiffuseBin() [2/2]
LecFicDiffuseBin::LecFicDiffuseBin (const char * name, std::ios_base::openmode mode = ios::in) inline
References LecFicDiffuse::ouvrir(), and Lec_Diffuse_base::set_bin().
Member Function Documentation
cree_instance()
Objet_U * LecFicDiffuseBin::cree_instance () static
taille_memoire()
unsigned LecFicDiffuseBin::taille_memoire () const override virtual
Reimplemented from LecFicDiffuse.
duplique()
int LecFicDiffuseBin::duplique () const override virtual
Reimplemented from LecFicDiffuse.
info()
const Type_info * LecFicDiffuseBin::info () static
get_info()
const Type_info * LecFicDiffuseBin::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from LecFicDiffuse.
self_cast() [1/2]
LecFicDiffuseBin & LecFicDiffuseBin::self_cast (Objet_U & r) static
self_cast() [2/2]
const LecFicDiffuseBin & LecFicDiffuseBin::self_cast (const Objet_U & r) static
printOn()
Sortie & LecFicDiffuseBin::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from LecFicDiffuse.
readOn()
Entree & LecFicDiffuseBin::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from LecFicDiffuse.
Member Data Documentation
info_obj
const Type_info LecFicDiffuseBin::info_obj static