TrioCFD: Loi_paroi_Ramstorfer Class Reference
Loi_paroi_Ramstorfer Class Reference
#include <Loi_paroi_Ramstorfer.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
Methodes implementees :
Constructor & Destructor Documentation
Loi_paroi_Ramstorfer()
Loi_paroi_Ramstorfer::Loi_paroi_Ramstorfer ()
~Loi_paroi_Ramstorfer()
Loi_paroi_Ramstorfer::~Loi_paroi_Ramstorfer ()
Member Function Documentation
cree_instance()
Objet_U * Loi_paroi_Ramstorfer::cree_instance () static
taille_memoire()
unsigned Loi_paroi_Ramstorfer::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Loi_paroi_Ramstorfer::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Loi_paroi_Ramstorfer::info () static
get_info()
const Type_info * Loi_paroi_Ramstorfer::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Loi_paroi_base.
self_cast() [1/2]
Loi_paroi_Ramstorfer & Loi_paroi_Ramstorfer::self_cast (Objet_U & r) static
self_cast() [2/2]
const Loi_paroi_Ramstorfer & Loi_paroi_Ramstorfer::self_cast (const Objet_U & r) static
printOn()
Sortie & Loi_paroi_Ramstorfer::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Loi_paroi_base.
readOn()
Entree & Loi_paroi_Ramstorfer::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Loi_paroi_base.
References Loi_paroi_base::readOn().
completer()
void Loi_paroi_Ramstorfer::completer () override virtual
Reimplemented from Loi_paroi_base.
References Loi_paroi_base::completer(), Process::exit(), Pb_Multiphase::nb_phases(), Correlation_base::pb_, Objet_U::que_suis_je(), and TRUST_Ref< _CLASSE_ >::valeur().
calc_y_plus()
void Loi_paroi_Ramstorfer::calc_y_plus (const DoubleTab & vit, const DoubleTab & nu_visc) override virtual
Implements Loi_paroi_base.
References calc_y_plus_loc(), Objet_U::dimension, TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Process::exit(), Loi_paroi_base::Faces_a_calculer_, Champ_Face_base::get_elem_vector_field(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Correlation_base::pb_, Loi_paroi_base::valeurs_loi_paroi_, and Loi_paroi_base::y_p_min_.
calc_y_plus_loc()
double Loi_paroi_Ramstorfer::calc_y_plus_loc (double u_par, double nu, double y, double yp, const double * d_bulles, const double * alpha) protected
References deriv_u_plus_de_y_plus(), Loi_paroi_base::eps_y_p_, and u_plus_de_y_plus().
Referenced by calc_y_plus().
u_plus_de_y_plus()
double Loi_paroi_Ramstorfer::u_plus_de_y_plus (double u_tau, double nu, double y, const double * d_bulles, const double * alpha) protected
References C_kr_, limiteur_y_p, Pb_Multiphase::nb_phases(), Correlation_base::pb_, TRUST_Ref< _CLASSE_ >::valeur(), and von_karman_.
Referenced by calc_y_plus_loc().
deriv_u_plus_de_y_plus()
double Loi_paroi_Ramstorfer::deriv_u_plus_de_y_plus (double u_tau, double nu, double y, const double * d_bulles, const double * alpha) protected
References C_kr_, limiteur_y_p, Pb_Multiphase::nb_phases(), Correlation_base::pb_, TRUST_Ref< _CLASSE_ >::valeur(), and von_karman_.
Referenced by calc_y_plus_loc().
Member Data Documentation
info_obj
const Type_info Loi_paroi_Ramstorfer::info_obj static
von_karman_
double Loi_paroi_Ramstorfer::von_karman_ = 0.41 protected
Referenced by deriv_u_plus_de_y_plus(), and u_plus_de_y_plus().
limiteur_y_p
double Loi_paroi_Ramstorfer::limiteur_y_p = 0.01 protected
Referenced by deriv_u_plus_de_y_plus(), and u_plus_de_y_plus().
C_kr_
double Loi_paroi_Ramstorfer::C_kr_ = .5 protected
Referenced by deriv_u_plus_de_y_plus(), and u_plus_de_y_plus().