TrioCFD: Paroi_2couches_VDF Class Reference
Paroi_2couches_VDF Class Reference
#include <Paroi_2couches_VDF.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Turbulence_paroi_base
void associer_modele (const Modele_turbulence_hyd_base &)
int calculer_hyd (Champ_Fonc_base &, Champ_Fonc_base &)
int calculer_hyd (Champ_Inc_base &)
const Type_info * get_info () const override
virtual void imprimer_premiere_ligne_ustar (int, const TRUST_List< Nom > &, const Nom &) const
virtual void imprimer_ustar_mean_only (Sortie &, int, const TRUST_List< Nom > &, const Nom &) const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Turbulence_paroi_base
static void typer_lire_turbulence_paroi (TRUST_Deriv< Turbulence_paroi_base > &, const Modele_turbulence_hyd_base &, Entree &)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
.SECTION voir aussi Turbulence_paroi_base
Constructor & Destructor Documentation
~Paroi_2couches_VDF()
Paroi_2couches_VDF::~Paroi_2couches_VDF ()
Member Function Documentation
cree_instance()
Objet_U * Paroi_2couches_VDF::cree_instance () static
taille_memoire()
unsigned Paroi_2couches_VDF::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Paroi_2couches_VDF::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Paroi_2couches_VDF::info () static
get_info()
const Type_info * Paroi_2couches_VDF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Paroi_hyd_base_VDF.
self_cast() [1/2]
Paroi_2couches_VDF & Paroi_2couches_VDF::self_cast (Objet_U & r) static
self_cast() [2/2]
const Paroi_2couches_VDF & Paroi_2couches_VDF::self_cast (const Objet_U & r) static
printOn()
Sortie & Paroi_2couches_VDF::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Paroi_hyd_base_VDF.
References Objet_U::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Paroi_2couches_VDF::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Paroi_hyd_base_VDF.
References Paroi_hyd_base_VDF::readOn().
set_param()
void Paroi_2couches_VDF::set_param (Param & param) override virtual
Reimplemented from Turbulence_paroi_base.
References Paroi_log_QDM::set_param(), and Turbulence_paroi_base::set_param().
init_lois_paroi()
int Paroi_2couches_VDF::init_lois_paroi () override virtual
Implements Turbulence_paroi_base.
References Paroi_hyd_base_VDF::init_lois_paroi_(), init_lois_paroi_hydraulique(), Turbulence_paroi_base::le_dom_dis_, TRUSTVect< _TYPE_, _SIZE_ >::resize(), and uplus_.
calculer_hyd() [1/2]
int Paroi_2couches_VDF::calculer_hyd (DoubleTab & tab_k_eps) override virtual
Implements Turbulence_paroi_base.
calculer_hyd_BiK()
int Paroi_2couches_VDF::calculer_hyd_BiK (DoubleTab & tab_k, DoubleTab & tab_eps) override virtual
Implements Turbulence_paroi_base.
calculer_hyd() [2/2]
int Paroi_2couches_VDF::calculer_hyd (DoubleTab & tab_nu_t, DoubleTab & tab_k_eps) override virtual
Implements Turbulence_paroi_base.
References calculer_u_star_sous_couche_log(), calculer_u_star_sous_couche_tampon(), calculer_uplus_dplus(), Turbulence_paroi_base::Cisaillement_paroi_, Objet_U::dimension, Domaine_VDF::distance_normale(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_VF::elem_faces(), Modele_turbulence_hyd_K_Eps_2_Couches::eqn_transp_K_Eps(), Process::exit(), Domaine_VF::face_voisins(), Modele_turbulence_hyd_K_Eps_2_Couches::get_nbcouches(), Modele_turbulence_hyd_K_Eps_2_Couches::get_nutswitch(), Modele_turbulence_hyd_K_Eps_2_Couches::get_switch(), Modele_turbulence_hyd_K_Eps_2_Couches::get_yswitch(), Equation_base::inconnue(), Turbulence_paroi_base::le_dom_Cl_dis_, Turbulence_paroi_base::le_dom_dis_, Loi_2couches_base::LepsLmu(), TRUSTVect< _TYPE_, _SIZE_ >::local_min_vect(), Equation_base::milieu(), Turbulence_paroi_base::mon_modele_turb_hyd, Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), Domaine_VDF::orientation(), Turbulence_paroi_base::tab_d_plus_, Turbulence_paroi_base::tab_u_star(), Turbulence_paroi_base::tab_u_star_, Paroi_log_QDM::table_hyd, uplus_, Table::val(), Dirichlet::val_imp(), TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), Champ_Inc_base::valeurs(), Debog::verifier(), and Fluide_base::viscosite_cinematique().
calculer_uplus_dplus()
void Paroi_2couches_VDF::calculer_uplus_dplus (DoubleVect & uplus, DoubleVect & dplus, DoubleVect & tab_ustar, int num_face, double dist, double d_visco, double norm_v)
Referenced by calculer_hyd().
tab_u_plus()
const DoubleVect & Paroi_2couches_VDF::tab_u_plus () const inline
References uplus_.
imprimer_ustar()
void Paroi_2couches_VDF::imprimer_ustar (Sortie & os) const override virtual
Reimplemented from Turbulence_paroi_base.
References Process::check_int_overflow(), Turbulence_paroi_base::Cisaillement_paroi_, Objet_U::dimension, Process::je_suis_maitre(), Turbulence_paroi_base::le_dom_Cl_dis_, Turbulence_paroi_base::le_dom_dis_, Frontiere_dis_base::le_nom(), Process::mp_sum(), Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), Turbulence_paroi_base::ouvrir_fichier_partage(), EcrFicPartage::syncfile(), Turbulence_paroi_base::tab_d_plus(), Turbulence_paroi_base::tab_u_star(), uplus_, TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), and Domaine_VF::xv().
use_shear()
bool Paroi_2couches_VDF::use_shear () const inline override virtual
Reimplemented from Turbulence_paroi_base.
init_lois_paroi_hydraulique()
int Paroi_2couches_VDF::init_lois_paroi_hydraulique () protected
References Paroi_log_QDM::Cmu_, Paroi_log_QDM::init_lois_paroi_hydraulique_(), and Turbulence_paroi_base::mon_modele_turb_hyd.
Referenced by init_lois_paroi().
calculer_u_star_sous_couche_tampon()
int Paroi_2couches_VDF::calculer_u_star_sous_couche_tampon (double & d_plus, double u_plus_d_plus, double d_visco, double dist, int face) protected
References Turbulence_paroi_base::tab_u_star_, Paroi_log_QDM::table_hyd, and Table::val().
Referenced by calculer_hyd().
calculer_u_star_sous_couche_log()
int Paroi_2couches_VDF::calculer_u_star_sous_couche_log (double norm_vit, double d_visco, double dist, int face) protected
References Erugu, Kappa, and Turbulence_paroi_base::tab_u_star_.
Referenced by calculer_hyd().
Member Data Documentation
info_obj
const Type_info Paroi_2couches_VDF::info_obj static
Cmu
double Paroi_2couches_VDF::Cmu protected
Kappa
double Paroi_2couches_VDF::Kappa protected
Referenced by calculer_u_star_sous_couche_log().
Erugu
double Paroi_2couches_VDF::Erugu protected
Referenced by calculer_u_star_sous_couche_log().
A_plus
double Paroi_2couches_VDF::A_plus protected
uplus_
DoubleVect Paroi_2couches_VDF::uplus_ protected
Referenced by calculer_hyd(), imprimer_ustar(), init_lois_paroi(), and tab_u_plus().
dplus_
DoubleVect Paroi_2couches_VDF::dplus_ protected