TrioCFD: Eval_Puiss_Neutr_VDF_Elem Class Reference
Eval_Puiss_Neutr_VDF_Elem Class Reference
#include <Eval_Puiss_Neutr_VDF_Elem.h>
Constructor & Destructor Documentation
Eval_Puiss_Neutr_VDF_Elem()
Eval_Puiss_Neutr_VDF_Elem::Eval_Puiss_Neutr_VDF_Elem () inline
Member Function Documentation
associer_champs()
void Eval_Puiss_Neutr_VDF_Elem::associer_champs (const Champ_Don_base & Q)
References la_puissance, puissance, and Champ_Don_base::valeurs().
Referenced by Source_Neutronique_VDF::associer_pb().
associer_repartition()
void Eval_Puiss_Neutr_VDF_Elem::associer_repartition (const Nom & fxyz, const Nom & nom_ssz)
References Parser::addVar(), Objet_U::dimension, Parser::eval(), fxyz, Nom::getString(), Evaluateur_Source::le_dom, Sous_Domaine_32_64< _SIZE_ >::nb_elem_tot(), Parser::parseString(), rep, TRUSTTab< _TYPE_, _SIZE_ >::resize(), Parser::setVar(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Source_Neutronique_VDF::associer_pb().
mettre_a_jour()
void Eval_Puiss_Neutr_VDF_Elem::mettre_a_jour () override virtual
Implements Evaluateur_Source.
References la_puissance, and puissance.
completer()
void Eval_Puiss_Neutr_VDF_Elem::completer () override virtual
Reimplemented from Evaluateur_Source_Elem.
References Evaluateur_Source_Elem::completer().
calculer_terme_source()
template<typename Type_Double > void Eval_Puiss_Neutr_VDF_Elem::calculer_terme_source (const int num_elem, Type_Double & source) const
References Evaluateur_Source_Elem::porosite_vol, puissance, rep, and Evaluateur_Source_Elem::volumes.
Member Data Documentation
la_puissance
TRUST_Ref< Champ_Uniforme *> Eval_Puiss_Neutr_VDF_Elem::la_puissance protected
Referenced by associer_champs(), and mettre_a_jour().
puissance
double Eval_Puiss_Neutr_VDF_Elem::puissance protected
Referenced by associer_champs(), calculer_terme_source(), and mettre_a_jour().
rep
DoubleTab Eval_Puiss_Neutr_VDF_Elem::rep protected
Referenced by associer_repartition(), and calculer_terme_source().
fxyz
Nom Eval_Puiss_Neutr_VDF_Elem::fxyz protected
Referenced by associer_repartition().