TrioCFD: TRUSTTab< _TYPE_, _SIZE_ > Class Template Reference
TRUSTTab< _TYPE_, _SIZE_ > Class Template Reference
#include <TRUSTTab.h>
Public Member Functions
void ref_data (_TYPE_ *ptr, _SIZE_ size) override
void reset () override
Public Member Functions inherited from TRUSTVect< _TYPE_, _SIZE_ >
void ref_data (_TYPE_ *ptr, _SIZE_ new_size) override
TRUSTVect (_SIZE_ n)
TRUSTVect (const TRUSTVect &v)
Public Member Functions inherited from TRUSTArray< _TYPE_, _SIZE_ >
void append_array (_TYPE_ valeur)
void from_tid_to_int (TRUSTArray< int, int > &out) const
TRUSTArray & inject_array (const TRUSTArray &source, _SIZE_ nb_elements=-1, _SIZE_ first_element_dest=0, _SIZE_ first_element_source=0)
TRUSTArray & operator*= (const _TYPE_ dy)
TRUSTArray & operator+= (const _TYPE_ dy)
TRUSTArray & operator+= (const TRUSTArray &y)
TRUSTArray & operator-= (const _TYPE_ dy)
TRUSTArray & operator-= (const TRUSTArray &y)
TRUSTArray & operator/= (const _TYPE_ dy)
TRUSTArray & operator= (_TYPE_ x)
void ref_as_small (TRUSTArray< float, int > &out) const
int ref_count () const
virtual void ref_data (_TYPE_ *ptr, _SIZE_ size)
virtual void reset ()
void set_mem_storage (const STORAGE storage)
_SIZE_ size_array () const
TRUSTArray (const TRUSTArray &A)
Public Member Functions inherited from Array_base
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from TRUSTVect< _TYPE_, _SIZE_ >
Sortie & printOn (Sortie &os) const override
Entree & readOn (Entree &is) override
Protected Member Functions inherited from TRUSTArray< _TYPE_, _SIZE_ >
Sortie & printOn (Sortie &os) const override
Entree & readOn (Entree &is) override
void resize_array_ (_SIZE_ n, RESIZE_OPTIONS opt=RESIZE_OPTIONS::COPY_INIT)
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
template<typename _TYPE_, typename _SIZE_>
class TRUSTTab< _TYPE_, _SIZE_ >
Repose sur un TRUSTVect avec calculs de l'indice corespondant
Constructor & Destructor Documentation
TRUSTTab() [1/6]
template<typename _TYPE_ , typename _SIZE_ > TRUSTTab< _TYPE_, _SIZE_ >::TRUSTTab () inline
References TRUSTArray< _TYPE_, _SIZE_ >::nb_dim_.
TRUSTTab() [2/6]
template<typename _TYPE_ , typename _SIZE_ > TRUSTTab< _TYPE_, _SIZE_ >::TRUSTTab (const TRUSTTab< _TYPE_, _SIZE_ > & dbt) inline
References TRUSTArray< _TYPE_, _SIZE_ >::nb_dim_.
TRUSTTab() [3/6]
template<typename _TYPE_ , typename _SIZE_ > TRUSTTab< _TYPE_, _SIZE_ >::TRUSTTab (_SIZE_ n) inline
References TRUSTArray< _TYPE_, _SIZE_ >::nb_dim_.
TRUSTTab() [4/6]
template<typename _TYPE_ , typename _SIZE_ > TRUSTTab< _TYPE_, _SIZE_ >::TRUSTTab (_SIZE_ n1, int n2) inline
References Process::exit(), TRUSTArray< _TYPE_, _SIZE_ >::nb_dim_, and TRUSTVect< _TYPE_, _SIZE_ >::set_line_size_().
TRUSTTab() [5/6]
template<typename _TYPE_ , typename _SIZE_ > TRUSTTab< _TYPE_, _SIZE_ >::TRUSTTab (_SIZE_ n1, int n2, int n3) inline
References Process::exit(), TRUSTArray< _TYPE_, _SIZE_ >::nb_dim_, and TRUSTVect< _TYPE_, _SIZE_ >::set_line_size_().
TRUSTTab() [6/6]
template<typename _TYPE_ , typename _SIZE_ > TRUSTTab< _TYPE_, _SIZE_ >::TRUSTTab (_SIZE_ n1, int n2, int n3, int n4) inline
References Process::exit(), TRUSTArray< _TYPE_, _SIZE_ >::nb_dim_, and TRUSTVect< _TYPE_, _SIZE_ >::set_line_size_().
Member Function Documentation
taille_memoire()
template<typename _TYPE_ , typename _SIZE_ > unsigned TRUSTTab< _TYPE_, _SIZE_ >::taille_memoire () const inline override protected virtual
Reimplemented from TRUSTArray< _TYPE_, _SIZE_ >.
duplique()
template<typename _TYPE_ , typename _SIZE_ > int TRUSTTab< _TYPE_, _SIZE_ >::duplique () const inline override protected virtual
Reimplemented from TRUSTArray< _TYPE_, _SIZE_ >.
References Process::exit(), Objet_U::numero(), and TRUSTTab< _TYPE_, _SIZE_ >::TRUSTTab.
printOn()
template<typename _TYPE_ , typename _SIZE_ > Sortie & TRUSTTab< _TYPE_, _SIZE_ >::printOn (Sortie & os) const inline override protected virtual
ecriture d'un tableau sequentiel (idem que TRUSTVect::printOn() on ne sait pas quoi faire de pertinent pour un tableau distribue).
Reimplemented from TRUSTArray< _TYPE_, _SIZE_ >.
References TRUSTArray< _TYPE_, _SIZE_ >::addr(), TRUSTArray< _TYPE_, _SIZE_ >::data(), Process::exit(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), TRUSTArray< _TYPE_, _SIZE_ >::nb_dim_, Sortie::put(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by TRUSTTrav< _TYPE_ >::printOn().
readOn()
template<typename _TYPE_ , typename _SIZE_ > Entree & TRUSTTab< _TYPE_, _SIZE_ >::readOn (Entree & is) inline override protected virtual
lecture d'un tableau sequentiel
Reimplemented from TRUSTArray< _TYPE_, _SIZE_ >.
References Process::exit(), Entree::get(), TRUSTArray< _TYPE_, _SIZE_ >::nb_dim_, TRUSTVect< _TYPE_, _SIZE_ >::readOn(), TRUSTVect< _TYPE_, _SIZE_ >::set_line_size_(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by TRUSTTrav< _TYPE_ >::readOn().
resize_dim0()
template<typename _TYPE_ , typename _SIZE_ > void TRUSTTab< _TYPE_, _SIZE_ >::resize_dim0 (_SIZE_ n, RESIZE_OPTIONS opt = RESIZE_OPTIONS::COPY_INIT) inline
Referenced by Champ_Elem_PolyMAC_P0P1NC::init_auxiliary_variables(), Champ_Face_PolyMAC_P0P1NC::init_auxiliary_variables(), and Champ_Face_PolyMAC_P0::init_auxiliary_variables().
resize() [1/5]
template<typename _TYPE_ , typename _SIZE_ > void TRUSTTab< _TYPE_, _SIZE_ >::resize (_SIZE_ n, RESIZE_OPTIONS opt = RESIZE_OPTIONS::COPY_INIT) inline
Referenced by Cut_cell_FT_Disc::add_and_remove_local_elements(), Operateur_Conv_sensibility_VEF::add_diffusion_scalar_term(), Operateur_Conv_sensibility_VEF::add_diffusion_term(), Cut_cell_FT_Disc::add_to_lazy_data(), Cut_cell_FT_Disc::add_to_persistent_data(), Cut_cell_FT_Disc::add_to_transient_data(), Polygone_32_64< _SIZE_ >::affecte_connectivite_numero_global(), Polyedre_32_64< _SIZE_ >::affecte_connectivite_numero_global(), Champ_Face_PolyMAC_P0::affecter_(), Champ_Face_VDF::affecter_(), Champ_P1NC::affecter_(), Integrale_tps_produit_champs::ajoute_produit_tensoriel(), Operateur_Conv_sensibility_VEF::ajouter(), Op_Diff_K_Eps_VEF_Face::ajouter(), Op_Diff_K_Omega_VEF_Face::ajouter(), Op_Div_EF::ajouter(), Iterateur_PolyMAC_Elem< _TYPE_ >::ajouter(), Op_Div_PolyMAC::ajouter(), Op_Div_PolyMAC_P0::ajouter(), Op_Conv_Amont_old_VEF_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Centre_EF_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_EF_VEF_P1NC_Stab::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_Muscl_New_VEF_Face::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Conv_Vort_VEF_Face::ajouter(), Op_Diff_VEF_Face::ajouter(), Op_Diff_VEFP1NCP1B_Face::ajouter(), Op_Dift_Stab_VEF_Face::ajouter(), Op_Dift_VEF_Face::ajouter(), Op_Div_VEFP1B_Elem::ajouter(), Terme_Boussinesq_VEFPreP1B_Face::ajouter(), Terme_Source_Constituant_Vortex_VEF_Face::ajouter(), Source_Transport_Eps_VDF_Elem::ajouter_blocs(), Source_Transport_K_VDF_Elem::ajouter_blocs(), Source_Transport_K_Eps_VDF_Elem::ajouter_blocs(), Terme_Source_Qdm_VDF_Face::ajouter_blocs(), Flux_2groupes_PolyMAC_P0::ajouter_blocs(), Dispersion_bulles_PolyMAC_P0::ajouter_blocs(), Portance_interfaciale_PolyMAC_P0::ajouter_blocs(), Perte_Charge_PolyMAC::ajouter_blocs(), Op_Evanescence_Homogene_Face_base::ajouter_blocs(), Source_Flux_interfacial_base::ajouter_blocs(), Dispersion_bulles_VDF::ajouter_blocs(), Portance_interfaciale_VDF::ajouter_blocs(), Op_Conv_Amont_VPoly_VDF_Face::ajouter_blocs(), Perte_Charge_VDF_base::ajouter_blocs(), Op_Evanescence_Homogene_PolyMAC_P0_Face::ajouter_blocs_aux(), Correction_Lubchenko_PolyMAC_P0::ajouter_blocs_disp(), Op_Div_PolyMAC_P0P1NC::ajouter_blocs_ext(), Op_Diff_PolyMAC_P0P1NC_Face::ajouter_blocs_ext(), Correction_Lubchenko_PolyMAC_P0::ajouter_blocs_lift(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Face::ajouter_cas_vectoriel(), Iterateur_PolyMAC_Elem< _TYPE_ >::ajouter_contribution(), Operateur_Conv_sensibility_VEF::ajouter_conv_term(), Polyedre_32_64< _SIZE_ >::ajouter_elements(), Operateur_Conv_sensibility_VEF::ajouter_Lsensibility_state_Amont(), Operateur_Conv_sensibility_VEF::ajouter_Lstate_sensibility_Amont(), Maillage_FT_Disc::ajouter_maillage(), Proprietes_part_vol::ajouter_proprietes(), Op_Grad_VEF_P1B_Face::ajouter_som(), Op_Div_VEFP1B_Elem::ajouter_som(), Domaine_PolyMAC::ajouter_stabilisation(), Op_Conv_ALE_VEF::ajouterALE(), Matrix_tools::allocate_for_scaled_addition(), Matrix_tools::allocate_for_symmetric_scaled_addition(), Champ_Elem_DG::allocate_mass_matrix(), Champ_Elem_DG::allocate_transition_matrix(), Assembleur_P_EF::assembler_mat(), Assembleur_P_PolyMAC::assembler_mat(), Eval_Darcy_VDF_Face::associer(), Eval_Darcy_VEF_Face::associer(), Op_Diff_EF_base::associer(), Op_Diff_VEF_base::associer(), Parcours_interface::associer_domaine_dis(), Ensemble_Faces_base::associer_les_cl(), Terme_Source_Coriolis_VDF_Face::associer_pb(), Eval_Puiss_Neutr_VDF_Elem::associer_repartition(), Beam_model::Beam_model(), Refine_Mesh::build_edges(), Domaine_VF::build_mc_dual_mesh(), Refine_Mesh::build_new_cells_2D(), Refine_Mesh::build_new_cells_3D(), Refine_Mesh::build_new_frontier_faces_2D(), Refine_Mesh::build_new_frontier_faces_3D(), Refine_Mesh::build_new_nodes(), Domaine_DG::build_nfaces_elem_(), Matrice_Bloc::build_stencil(), Ch_front_input::buildSommetsFaces(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calc_elem_elem(), Modele_turbulence_scal_LES_dyn_VDF::calc_elem_elem(), Couplage_Tubes_IBC::calcul_F_pression(), Couplage_Tubes_IBC::calcul_F_pression2(), Parcours_interface::calcul_intersection_facelem_3D(), Intersection_Interface_ijk_face::calcul_projection_bary_face_mouillee_interface_moy(), Intersection_Interface_ijk_cell::calcul_projection_centre_faces_sur_interface_moy(), Intersection_Interface_ijk_cell::calcul_projection_centre_sur_interface_moy(), Traitement_particulier_NS_THI_VEF::calcul_spectre(), Maillage_FT_Disc::calcul_surface_normale(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calcul_tableaux_correspondance(), Modele_turbulence_scal_LES_dyn_VDF::calcul_tableaux_correspondance(), Transport_Interfaces_FT_Disc::calcul_vitesse(), Champ_Q1_EF::calcul_y_plus(), Champ_P1NC::calcul_y_plus(), Champ_Face_VDF::calcul_y_plus(), Champ_P1NC::calcul_y_plus_diphasique(), Champ_Face_VDF::calcul_y_plus_diphasique(), Fluide_reel_base::calculate_fluid_properties_enthalpie(), Fluide_reel_base::calculate_fluid_properties_enthalpie_incompressible(), Op_Conv_ALE_VEF::calculateALEMeshVelocityGradientOnFaces(), Masse_Multiphase::calculer_alpha_rho(), Energie_Multiphase::calculer_alpha_rho_e(), Energie_Multiphase::calculer_alpha_rho_h(), Energie_cinetique_turbulente::calculer_alpha_rho_k(), Energie_cinetique_turbulente_WIT::calculer_alpha_rho_k_WIT(), Remaillage_FT::calculer_barycentre_facettes_voisines(), Domaine_EF::calculer_Bij(), IJK_Interfaces::calculer_bounding_box_bulles(), Aretes::calculer_centre_de_gravite(), Elem_geom_base_32_64< _SIZE_ >::calculer_centres_gravite(), Rectangle_axi_32_64< _SIZE_ >::calculer_centres_gravite(), Hexaedre_axi_32_64< _SIZE_ >::calculer_centres_gravite(), Polyedre_32_64< _SIZE_ >::calculer_centres_gravite(), Polygone_32_64< _SIZE_ >::calculer_centres_gravite(), Faces_32_64< _SIZE_ >::Calculer_centres_gravite(), Domaine_32_64< _SIZE_ >::calculer_centres_gravite_aretes(), Equation_base::calculer_champ_conserve(), Switch_double::calculer_coeff(), Marching_Cubes::calculer_coord_noeuds(), Maillage_FT_Disc::calculer_coord_noeuds(), Maillage_FT_Disc::calculer_costheta_minmax(), Maillage_FT_IJK::calculer_costheta_minmax(), Navier_Stokes_FT_Disc::calculer_delta_u_interface(), Champ_front_base::calculer_derivee_en_temps(), Champ_front_Parametrique::calculer_derivee_en_temps(), Remaillage_FT::calculer_differentielle_volume(), Modele_turbulence_scal_LES_dyn_VDF::calculer_diffusivite_turbulente(), Op_Conv_VDF_base::calculer_dt_stab(), Op_Conv_Muscl_New_VEF_Face::calculer_dt_stab(), Fluide_base::calculer_e_int(), Milieu_composite::calculer_energie_interne(), Milieu_composite::calculer_enthalpie(), Iterateur_PolyMAC_Elem< _TYPE_ >::calculer_flux_bord(), Op_Grad_EF::calculer_flux_bords(), Op_Grad_VDF_Face::calculer_flux_bords(), Op_Grad_VEF_P1B_Face::calculer_flux_bords(), Flux_radiatif_VDF::calculer_flux_radiatif(), Flux_radiatif_VEF::calculer_flux_radiatif(), Partitionneur_base_32_64< _SIZE_ >::calculer_graphe_connexions_periodiques(), ParoiVDF_TBLE_LRM::calculer_hyd(), ParoiVDF_TBLE::calculer_hyd(), ParoiVDF_TBLE::calculer_hyd_BiK(), ParoiVDF_TBLE_LRM::calculer_hyd_BiK(), Assembleur_P_VEF::calculer_inv_volume(), Domaine_EF::calculer_IPhi(), Domaine_EF_axi::calculer_IPhi(), Milieu_composite::calculer_masse_volumique(), Taux_dissipation_turbulent::calculer_omega(), IJK_Interfaces::calculer_poussee_bulles(), Transport_Marqueur_FT::calculer_proprietes_fluide_pos_particules(), Scatter::calculer_renum_items_communs(), Paroi_ODVM_scal_VDF::calculer_scal(), Paroi_TBLE_scal_VDF::calculer_scal(), ParoiVEF_TBLE_scal::calculer_scal(), Transport_Interfaces_FT_Disc::calculer_scalaire_interpole(), Echelle_temporelle_turbulente::calculer_tau(), Milieu_composite::calculer_temperature_multiphase(), Navier_Stokes_FTD_IJK::calculer_terme_asservissement(), Echange_contact_VDF::calculer_Teta_paroi(), Echange_contact_rayo_semi_transp_VDF::calculer_Teta_paroi(), Champ_base::calculer_valeurs_elem_compo_post(), Champ_base::calculer_valeurs_elem_post(), Champ_base::calculer_valeurs_som_compo_post(), Champ_base::calculer_valeurs_som_post(), IJK_Interfaces::calculer_vecteurs_de_deplacement_rigide(), Modele_turbulence_hyd_K_Eps::calculer_viscosite_turbulente(), Modele_turbulence_hyd_K_Eps_Bicephale::calculer_viscosite_turbulente(), Terme_Source_Acceleration_VDF_Face::calculer_vitesse_faces(), Transport_Interfaces_FT_Disc::calculer_vitesse_repere_local(), Transport_Interfaces_FT_Disc::calculer_vitesse_transport_interpolee(), Maillage_FT_Disc::calculer_voisinage_facettes(), Hexaedre_VEF_32_64< _SIZE_ >::calculer_volumes(), Quadrangle_VEF_32_64< _SIZE_ >::calculer_volumes(), Domaine_VDF::calculer_volumes_entrelaces(), Domaine_PolyMAC::calculer_volumes_entrelaces(), Domaine_PolyMAC_P0P1NC::calculer_volumes_entrelaces(), Desc_Structure_FT::check(), Maillage_FT_Disc_Data_Cache::clear(), IJK_Thermal_Subresolution::complete_field_thermal_wake_slice_ij_values(), Proprietes_part_vol::completer(), Echange_contact_VDF_FT_Disc::completer(), Flux_radiatif_base::completer(), Neumann_paroi_rayo_semi_transp_VDF::completer(), Neumann_paroi_rayo_semi_transp_VEF::completer(), Op_Diff_DG_base::completer(), Op_Diff_DG_Elem::completer(), Op_Diff_PolyMAC_base::completer(), Op_Diff_PolyMAC_P0_base::completer(), Op_Diff_PolyMAC_P0P1NC_base::completer(), Op_Diff_PolyMAC_Elem::completer(), Op_Diff_PolyMAC_P0_Elem::completer(), Op_Diff_PolyMAC_P0_Face::completer(), Op_Diff_PolyMAC_P0P1NC_Elem::completer(), Op_Diff_PolyMAC_P0P1NC_Face::completer(), Sortie_libre_pression_moyenne_imposee::completer(), Source_Flux_interfacial_base::completer(), Loi_paroi_base::completer(), Source_Neutronique::completer(), Echange_contact_Correlation_VDF::completer(), Echange_interne_impose::completer(), Echange_contact_Correlation_VEF::completer(), Op_Diff_VEF_Face_Stab::completer(), Op_Dift_Stab_VEF_Face::completer(), Op_Correlation::completer(), FT_Field::completer_compo_connexe_partielle(), Couplage_Parietal_PolyMAC_helper::completer_d_nuc(), Schema_Adams_Bashforth_order_2::compute_adams_bashforth_coefficients(), Schema_Adams_Bashforth_order_3::compute_adams_bashforth_coefficients(), Schema_Adams_Moulton_order_2::compute_adams_moulton_coefficients(), Schema_Adams_Moulton_order_3::compute_adams_moulton_coefficients(), Triple_Line_Model_FT_Disc::compute_approximate_interface_inout(), Schema_Backward_Differentiation_order_2::compute_backward_differentiation_coefficients(), Schema_Backward_Differentiation_order_3::compute_backward_differentiation_coefficients(), Navier_Stokes_FTD_IJK::compute_correction_for_momentum_balance(), Source_Transport_K_Omega_VEF_Face::compute_cross_diffusion(), Postprocessing_IJK::compute_extended_pressures(), Post_Processing_Hydrodynamic_Forces::compute_friction_force_projected_tensor(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_friction_force_projected_tensor(), Maillage_FT_Disc::compute_gravity_center_fa7(), Post_Processing_Hydrodynamic_Forces::compute_heat_transfer(), Post_Processing_Hydrodynamic_Forces::compute_hydrodynamic_forces(), Quadrature_Ord1_Polygone::compute_integ_points(), Quadrature_Ord3_Polygone::compute_integ_points(), Quadrature_Ord5_Polygone::compute_integ_points(), Quadrature_Ord1_Polygone::compute_integ_points_on_facet(), Quadrature_Ord3_Polygone::compute_integ_points_on_facet(), Quadrature_Ord5_Polygone::compute_integ_points_on_facet(), IJK_Thermal_base::compute_interfacial_temperature2(), IJK_Thermal_cut_cell::compute_interfacial_temperature2(), Operator_FT_Disc::Compute_interfaciale_source(), Source_WC_Chaleur_VEF::compute_interpolate_gradP(), IJK_One_Dimensional_Subproblem::compute_local_discretisation(), Domaine_DG::compute_mesh_param(), Redistribute_Field::compute_send_blocs(), Champ_Elem_DG::compute_stab_param(), IJK_Interfaces::compute_vinterp(), Transport_Marqueur_FT::construction_ensemble_proprietes(), Domaine_32_64< _SIZE_ >::construire_elem_virt_pe_num(), Marching_Cubes::construire_iso(), Maillage_FT_Disc::construire_noeuds(), Marching_Cubes::construire_noeuds_et_facettes(), Marching_Cubes::construire_noeuds_liste_faces(), Marching_Cubes::construire_noeuds_uniques(), Domaine_VF::construire_num_fac_loc(), Matrice_Morse::construire_sous_bloc(), Solv_Externe::construit_renum(), Op_Conv_VEF_Face::contribue_au_second_membre(), Maillage_FT_Disc::copier_sommet(), Marching_Cubes::correspondance_espaces_distant_virtuel(), Domaine_VDF::creer_elements_fictifs(), Remove_elem::creer_faces(), Faces_builder::creer_faces_reeles(), Hexa_VEF::creer_facette_normales(), Quadri_VEF::creer_facette_normales(), Tetra_VEF::creer_facette_normales(), Tri_VEF::creer_facette_normales(), Maillage_FT_Disc::creer_facettes_virtuelles(), Fluide_base::creer_nu(), Champ_Fonc_base::creer_tableau_distribue(), Champ_Inc_base::creer_tableau_distribue(), Traitement_particulier_NS_CEG::critere_cea_jaea(), Cut_cell_FT_Disc::Cut_cell_FT_Disc(), Tetraedriser_homogene_compact::decoupe(), Tetraedriser_homogene_fin::decoupe(), Decouper_Bord_coincident::decouper_(), Maillage_FT_Disc::deplacer_sommets(), Maillage_FT_Disc::deplacer_un_sommet(), Traitement_particulier_NS_THI_VEF::determine_tab_fft_VEF_1D(), Traitement_particulier_NS_THI_VEF::determine_tab_fft_VEF_3D(), Op_EF_base::dimensionner(), Matrice_Dense::dimensionner(), Roue::dimensionner(), Aretes::dimensionner(), Op_Div_PolyMAC::dimensionner(), Op_PolyMAC_Elem::dimensionner_bloc_vitesse(), Op_Diff_PolyMAC_P0_Elem::dimensionner_blocs(), Op_Diff_PolyMAC_P0P1NC_Face::dimensionner_blocs_ext(), Champ_Face_VDF::dimensionner_tenseur_Grad(), Transport_Interfaces_FT_Disc::discretiser(), Domaine_DG::discretiser(), Domaine_EF::discretiser(), Domaine_Poly_base::discretiser(), Sous_domaine_VF::discretiser(), Domaine_VEF::discretiser(), Domaine_VEF::discretiser_arete(), Domaine_Poly_base::discretiser_aretes(), Remaillage_FT::diviser_grandes_aretes(), Remaillage_FT_IJK::diviser_grandes_aretes(), Maillage_FT_Disc::echanger_sommets_PE(), Postprocessing_IJK::ecrire_statistiques_bulles(), Sauvegarde_Reprise_Maillage_FT::ecrire_xyz(), Domaine_Poly_base::elem_arete_d(), Domaine_Poly_base::elem_som_d(), SETS::eliminer(), Ensemble_Lagrange_base::Ensemble_Lagrange_base(), Flux_radiatif_VDF::evaluer_cl_rayonnement(), FT_Field::exchange_compo_connexe(), FT_Field::exchange_data(), Matrix_tools::extend_matrix_stencil(), TroisDto2D_32_64< _SIZE_ >::extraire_2D(), Domaine_bord_32_64< _SIZE_ >::extraire_domaine_bord(), ExtrudeParoi::extrude(), Extruder::extruder(), Extruder_en3::extruder(), Extruder::extruder_hexa(), Operator_FT_Disc::Facette_to_Sommets(), Domaine_PolyMAC_P0::fgrad(), LireMED_32_64< _SIZE_ >::fill_frontieres(), OpConvCentre2IJK_double::fill_g_compo(), OpConvCentre4IJK_double::fill_g_compo(), Sonde_IJK::fill_local_values(), Postraitement_ft_lata::filter_out_array(), Postraitement_ft_lata::filter_out_virtual_fa7(), LireMED_32_64< _SIZE_ >::finalize_sommets(), Champ_Don_base::fixer_nb_valeurs_nodales(), Champ_Ostwald::fixer_nb_valeurs_nodales(), Champ_P1NC_implementation::fixer_nb_valeurs_nodales(), Neumann::flux_impose(), Couplage_Tubes_IBC::force_ibc_velocity_symetrie_plane(), Ensemble_Lagrange_base::generer_marqueurs_sz(), Champ_Generique_Extraction::get_champ(), Champ_Generique_Transformation::get_champ(), Transport_Interfaces_FT_Disc::get_champ_post_FT(), Champ_front_recyclage::get_coord_faces(), Transport_Interfaces_FT_Disc::get_expression_vitesse_imposee(), IJK_One_Dimensional_Subproblem::get_field_profile_at_point(), Triple_Line_Model_FT_Disc::get_in_out_coords(), Domaine_VF::get_position(), Intersection_Interface_ijk::get_position_interpolation_normal_interf(), IJK_One_Dimensional_Subproblem::get_single_point_coordinates(), Matrice_Bloc::get_stencil(), Matrice_Dense::get_stencil(), Matrice_Diagonale::get_stencil(), Matrice_Morse::get_stencil(), Matrice_Nulle::get_stencil(), Matrice_Diagonale::get_stencil_and_coefficients(), Matrice_Nulle::get_stencil_and_coefficients(), Matrice_Bloc::get_stencil_coeff_templ(), Matrice_Morse::get_stencil_coeff_templ(), Matrice_Bloc_Sym::get_symmetric_stencil(), Matrice_Morse_Sym::get_symmetric_stencil(), Matrice_Bloc_Sym::get_symmetric_stencil_and_coefficients(), Matrice_Morse_Sym::get_symmetric_stencil_and_coefficients(), Tetraedre_32_64< _SIZE_ >::get_tab_aretes_sommets_locaux(), Hexaedre_32_64< _SIZE_ >::get_tab_faces_sommets_locaux(), Hexaedre_VEF_32_64< _SIZE_ >::get_tab_faces_sommets_locaux(), Point_32_64< _SIZE_ >::get_tab_faces_sommets_locaux(), Prisme_32_64< _SIZE_ >::get_tab_faces_sommets_locaux(), Quadrangle_VEF_32_64< _SIZE_ >::get_tab_faces_sommets_locaux(), Rectangle_32_64< _SIZE_ >::get_tab_faces_sommets_locaux(), Segment_32_64< _SIZE_ >::get_tab_faces_sommets_locaux(), Tetraedre_32_64< _SIZE_ >::get_tab_faces_sommets_locaux(), Triangle_32_64< _SIZE_ >::get_tab_faces_sommets_locaux(), Polyedre_32_64< _SIZE_ >::get_tab_faces_sommets_locaux(), Polygone_32_64< _SIZE_ >::get_tab_faces_sommets_locaux(), Hexa_VEF::Hexa_VEF(), Couplage_Tubes_IBC::ibc_localisee_velocity_cube(), Couplage_Tubes_IBC::ibc_localisee_velocity_cube_qdm(), IJK_Interfaces::IJK_Interfaces(), Iterateur_PolyMAC_Elem< _TYPE_ >::impr(), Champ_Fonc_P0_VDF::imprime(), Champ_P0_VDF::imprime(), Champ_Face_VDF_implementation::imprime_Face(), Terme_Source_Canal_RANS_LES_VDF_Elem::init(), Terme_Source_Canal_RANS_LES_VDF_Face::init(), Echange_contact_Correlation_VEF::init(), Terme_Source_Canal_RANS_LES_VEF_Face::init(), Sonde::init_bords(), Traitement_particulier_NS_THI_VEF_new::init_calc_spectre(), Traitement_particulier_NS_Profils_VDF::init_calcul_moyenne(), Traitement_particulier_NS_Profils::init_calcul_stats(), Traitement_particulier_NS_Profils_thermo_VDF::init_calcul_stats(), Traitement_particulier_NS_chmoy_faceperio_VEF::init_calcul_stats(), Domaine_VF::init_dist_paroi_globale(), Domaine_PolyMAC::init_equiv(), Modele_turbulence_hyd_K_Omega::init_F1_F2_enstrophy(), Echange_contact_PolyMAC_P0P1NC::init_f_dist(), Champ_Inc_P0_base::init_fcl(), Champ_Face_base::init_fcl(), Champ_implementation_P1::init_from_file(), Echange_contact_PolyMAC_P0::init_fs_dist(), Paroi_std_hyd_EF::init_lois_paroi(), LoiParoiHybride_VDF::init_lois_paroi(), ParoiVDF_TBLE_LRM::init_lois_paroi(), Paroi_TBLE_scal_VDF::init_lois_paroi(), LoiParoiHybride_VEF::init_lois_paroi(), Paroi_std_hyd_VEF::init_lois_paroi(), ParoiVEF_TBLE::init_lois_paroi(), Paroi_scal_hyd_base_EF::init_lois_paroi(), Paroi_scal_hyd_base_VDF::init_lois_paroi(), Paroi_scal_hyd_base_VEF::init_lois_paroi(), Paroi_TBLE_QDM::init_lois_paroi(), Paroi_TBLE_QDM_Scal::init_lois_paroi(), Paroi_hyd_base_EF::init_lois_paroi_(), Paroi_hyd_base_VDF::init_lois_paroi_(), Paroi_hyd_base_VEF::init_lois_paroi_(), Domaine_PolyMAC::init_m1_2d(), Domaine_PolyMAC::init_m1_3d(), Couplage_Parietal_PolyMAC_helper::init_op_ext(), Transport_Interfaces_FT_Disc::init_particles_position_velocity(), Champ_Face_PolyMAC::init_ra(), Domaine_PolyMAC::init_rf(), Domaine_PolyMAC_P0::init_stencils(), Echange_contact_Correlation_VDF::init_tab_echange(), Modele_Lam_Bremhorst_VEF::init_tenseur_elem(), Modele_Shih_Zhu_Lumley_VEF::init_tenseur_elem(), Modele_Lam_Bremhorst_VEF::init_tenseur_face(), Modele_Shih_Zhu_Lumley_VEF::init_tenseur_face(), Champ_Face_PolyMAC::init_va(), Domaine_PolyMAC::init_ve(), Champ_Face_PolyMAC_P0::init_ve2(), Domaine_PolyMAC::init_we(), Domaine_PolyMAC::init_we_2d(), Domaine_PolyMAC::init_we_3d(), Structural_dynamic_mesh_model::initDynamicMeshProblem(), Raccord_distant_homogene_32_64< _SIZE_ >::initialise(), Cut_cell_FT_Disc::initialise(), Cut_cell_FT_Disc::initialise_independent_index(), Sonde::initialiser(), Op_Diff_VEFP1NCP1B_Face::initialiser(), Loi_Etat_GR_base::initialiser(), Sonde_Int::initialiser(), Paroi_frottante_simple::initialiser(), Dirichlet_loi_paroi::initialiser(), Echange_contact_PolyMAC::initialiser(), Echange_global_impose_turbulent::initialiser(), Echange_contact_VDF::initialiser(), Boundary_field_keps_from_ud::initialiser(), Ch_front_input_P1::initialiser(), Champ_front_var::initialiser(), Champ_front_recyclage::initialiser(), Domaine_ALE::initialiser(), Champ_front_xyz_debit::initialiser(), Champ_Fonc_Interp::initialiser(), Champ_front_xyz_debit::initialiser_coefficient(), Loi_Etat_Multi_GP_base::initialiser_inco_ch(), Loi_Etat_rhoT_GP_QC::initialiser_rho(), Couplage_Tubes_IBC::initialize(), Fourier_trans::initialize(), Redistribute_Field::initialize(), Corrige_flux_FT_temperature_conv::initialize(), IJK_Interfaces::initialize(), Statistiques_dns_ijk_FT::initialize(), Domaine_IJK::initialize_splitting(), Transport_Marqueur_FT::initTimeStep(), Remaillage_FT::inserer_tab_aretes(), Corrige_flux_FT_temperature_conv::interp_back_to_bary_faces(), Moyenne_volumique::interpreter(), Lata_2_Other::interpreter(), Extraire_domaine::interpreter_(), Extraire_plan::interpreter_(), Lire_Tgrid::interpreter_(), VerifierCoin::interpreter_(), Simple::iterer_eqs(), Traitement_particulier_NS_Brech_VEF::lire(), Proprietes_part_vol::lire_distribution(), Paroi_TBLE_QDM_Scal::lire_donnees(), Modele_Rayonnement_Milieu_Transparent::lire_fichiers(), Pave_32_64< _SIZE_ >::lire_front(), Transport_Interfaces_FT_Disc::lire_maillage_ft_cao(), Maillage_FT_IJK::lire_maillage_ft_dans_lata(), Paroi_TBLE_QDM::lire_motcle_non_standard(), Prepro_IBM_base::lire_motcle_non_standard(), Fluide_Quasi_Compressible::lire_motcle_non_standard(), Convection_Diffusion_Temperature::lire_motcle_non_standard(), Statistiques_dns_ijk_FT::lire_motcle_non_standard(), Sauvegarde_Reprise_Maillage_FT::lire_xyz(), Domaine_PolyMAC_P0P1NC::M1(), Domaine_PolyMAC::M2(), Remaillage_FT::marquer_aretes(), Domaine_32_64< _SIZE_ >::merge_wo_vertices_with(), Source_Qdm_VDF_Phase_field::methode_1(), Champ_front_xyz_debit::mettre_a_jour(), Portance_interfaciale_PolyMAC_P0::mettre_a_jour(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::mettre_a_jour(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::mettre_a_jour(), PlaqThVDF::mettre_a_jour(), Champ_front_contact_rayo_transp_VEF::mettre_a_jour_flux_radiatif(), Op_Diff_VEF_Face_Stab::modifie_pour_Cl(), Proprietes_part_vol::nettoyer(), Maillage_FT_Disc::nettoyer_maillage(), Maillage_FT_Disc::nettoyer_noeuds_virtuels_et_frontieres(), Maillage_FT_Disc::nettoyer_phase(), Operator_FT_Disc::Operator_Gradient_FT_sommets(), Parcours_interface::parcourir(), Traitement_particulier_NS_canal::post_traitement_particulier(), Postraitement_ft_lata::postprocess_field_values(), SSOR::prepare_(), Transport_Interfaces_FT_Disc::preparer_calcul(), Transport_Marqueur_FT::preparer_calcul(), Modele_Rayonnement_Milieu_Transparent::preparer_calcul(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::preparer_calcul(), Traitement_particulier_NS_canal::preparer_calcul_particulier(), Proprietes_part_vol::Proprietes_part_vol(), Quadri_VEF::Quadri_VEF(), Raffiner_anisotrope_32_64< _SIZE_ >::raffiner_(), Domaine_ALE::read_beam(), LireMED_32_64< _SIZE_ >::read_boundaries(), Maillage_FT_Disc::readOn(), Triple_Line_Model_FT_Disc::readOn(), Boundary_field_uniform_keps_from_ud::readOn(), Field_uniform_keps_from_ud::readOn(), ParoiVDF_TBLE_LRM::readOn(), Champ_Front_Composite::readOn(), Champ_Front_MUSIG::readOn(), Champ_front_uniforme::readOn(), Champ_input_P0::readOn(), Ch_input_uniforme::readOn(), Champ_Fonc_Tabule_Morceaux::readOn(), Champ_Uniforme_Morceaux::readOn(), Champ_Uniforme_Morceaux_Tabule_Temps::readOn(), Champ_front_MED::readOn(), Sonde::readOn(), Sonde_Int::readOn(), Sortie_libre_pression_imposee_QC::readOn(), Loi_Etat_rhoT_GR_QC::readOn(), Sortie_libre_pression_imposee::readOn(), Sortie_libre_pression_moyenne_imposee::readOn(), Flux_interfacial_Coef_Constant::readOn(), Fluide_MUSIG::readOn(), Sortie_libre_Gradient_Pression_impose::readOn(), Sortie_libre_Pression_imposee_Orlansky::readOn(), Sortie_libre_Gradient_Pression_impose_VEF::readOn(), Sortie_libre_Gradient_Pression_libre_VEF::readOn(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::readOn(), Remove_elem::recreer_faces(), IJK_Interfaces::recursive_calcul_distance_chez_voisin(), FT_Field::reinit_remeshing_table(), Cut_cell_FT_Disc::remove_dead_and_virtual_cells(), Remove_elem::remove_elem_(), Assembleur_P_VEF::remplir(), Champ_P0_VDF::remplir_coord_noeuds(), Champ_implementation_P0::remplir_coord_noeuds(), Champ_implementation_sommet::remplir_coord_noeuds(), Champ_P1iP1B_implementation::remplir_coord_noeuds(), Champ_implementation_sommet::remplir_coord_noeuds_et_polys(), Marching_Cubes::remplir_data_marching_cubes(), Connectivite_frontieres::remplir_def_face_aretes(), Domaine_VF::remplir_face_numero_bord(), Connectivite_frontieres::remplir_faces_voisins(), Op_Diff_VEF_base::remplir_nu(), Ensemble_Lagrange_base::remplir_sommets_tmp(), Traitement_particulier_NS_canal_VDF::remplir_Tab_recap(), Domaine_EF_axi::remplir_tableau_origine(), Ch_front_input_ALE::remplir_vit_som_bord_ALE(), Champ_front_ALE::remplir_vit_som_bord_ALE(), Champ_front_ALE_Beam::remplir_vit_som_bord_ALE(), Scatter::reordonner_faces_de_joint(), Transport_Interfaces_FT_Disc::reprendre(), Paroi_TBLE_QDM::reprendre(), Paroi_TBLE_QDM_Scal::reprendre(), Champ_Elem_PolyMAC_P0::reprendre(), Champ_Face_PolyMAC_P0::reprendre(), Collision_Model_FT_base::reprendre(), Traitement_particulier_NS_Profils::reprendre_stat(), Traitement_particulier_NS_Profils_thermo_VDF::reprendre_stat(), Traitement_particulier_NS_canal::reprendre_stat_canal(), Collision_Model_FT_base::reset(), Maillage_FT_Disc::reset(), Post_Processing_Hydrodynamic_Forces::resize_and_init_tables(), Post_Processing_Hydrodynamic_Forces_Stokes::resize_and_init_tables(), Post_Processing_Hydrodynamic_Forces::resize_coord_neighbor_fluid_fa7(), Post_Processing_Hydrodynamic_Forces::resize_data_fa7(), Post_Processing_Hydrodynamic_Forces_Stokes::resize_data_fa7(), Post_Processing_Hydrodynamic_Forces::resize_gradU_P1(), Post_Processing_Hydrodynamic_Forces_Stokes::resize_gradU_P1(), Post_Processing_Hydrodynamic_Forces::resize_gradU_P2(), Post_Processing_Hydrodynamic_Forces_Stokes::resize_gradU_P2(), Collision_Model_FT_base::resize_lagrangian_contact_force(), Collision_Model_FT_base::resize_particles_collision_number(), Post_Processing_Hydrodynamic_Forces::resize_sigma(), Post_Processing_Hydrodynamic_Forces_Stokes::resize_sigma(), Champ_Inc_base::resize_val_bord(), IJK_Interfaces::RK3_G_store_vi_resize(), Maillage_FT_IJK::sauv_facette_indexation_avant_transport(), FT_Field::sauvegarder_triangle(), Collision_Model_FT_base::set_LC_zones(), Simple::Simple(), Solv_Gen::solve(), Operator_FT_Disc::Sommets_to_Facettes(), Traitement_particulier_NS_THI_VEF::sorties_globales(), IJK_Interfaces::supprimer_certaines_bulles_reelles(), Remaillage_FT::supprimer_doublons_facettes(), IJK_Interfaces::supprimer_duplicata_bulles(), Remaillage_FT_IJK::supprimer_petites_aretes(), Domaine_PolyMAC_P0P1NC::surf_elem_arete(), Tetra_VEF::Tetra_VEF(), Champ_Elem_PolyMAC::trace(), Raccord_distant_homogene_32_64< _SIZE_ >::trace_elem_distant(), Frontiere_32_64< _SIZE_ >::trace_elem_local(), Raccord_distant_homogene_32_64< _SIZE_ >::trace_face_distant(), Frontiere_32_64< _SIZE_ >::trace_som_local(), Moyenne_volumique::traiter_champs(), Champ_Q1NC_implementation::transforme_coord2D(), Champ_Q1NC_implementation::transforme_coord3D(), IJK_Interfaces::transporter_maillage_deformation(), IJK_Interfaces::transporter_maillage_remaillage(), Tri_VEF::Tri_VEF(), Tetraedriser_homogene::trianguler(), Tetraedriser_homogene_compact::trianguler(), Tetraedriser_homogene_fin::trianguler(), Trianguler_fin::trianguler(), Trianguler_H::trianguler(), Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_elem(), TRUSTTabFT< _TYPE_ >::TRUSTTabFT(), Matrice_Sym::unsymmetrize_stencil(), Matrice_Sym::unsymmetrize_stencil_and_coefficients(), Cut_cell_FT_Disc::update(), Echange_contact_PolyMAC::update_coeffs(), Cut_cell_FT_Disc::update_index_sorted_by_k(), Cut_cell_FT_Disc::update_index_sorted_by_statut_diphasique(), Maillage_FT_Disc::update_tableau_apres_transport(), Corrige_flux_FT_temperature_conv::update_temperature_ghost(), Neumann_sortie_libre::val_ext(), Dirichlet::val_imp(), Champ_implementation_P0::valeur_aux_centres_de_gravite(), Champ_P1NC_implementation::valeur_aux_centres_de_gravite(), Champ_Elem_DG::valeur_aux_elems(), Champ_Fonc_P1_DG::valeur_aux_elems(), Champ_P1iP1B_implementation::valeur_aux_elems(), Champ_P1NC_implementation::valeur_aux_elems(), Champ_implementation_P0::valeur_aux_elems(), Champ_Face_PolyMAC::valeur_aux_faces(), Champ_Face_PolyMAC_P0P1NC::valeur_aux_faces(), Champ_Fonc_Face_PolyMAC::valeur_aux_faces(), Champ_implementation_Q1::value_interpolation(), Domaine_VEF::vecteur_face_facette(), Domaine_Poly_base::vol_elem_som(), Domaine_PolyMAC_P0P1NC::W1(), Domaine_PolyMAC::W2(), Domaine_PolyMAC::W_stabiliser(), and Domaine_VF::xv_bord().
resize() [2/5]
template<typename _TYPE_ , typename _SIZE_ > void TRUSTTab< _TYPE_, _SIZE_ >::resize (_SIZE_ n1, int n2, RESIZE_OPTIONS opt = RESIZE_OPTIONS::COPY_INIT) inline
resize() [3/5]
template<typename _TYPE_ , typename _SIZE_ > void TRUSTTab< _TYPE_, _SIZE_ >::resize (_SIZE_ n1, int n2, int n3, RESIZE_OPTIONS opt = RESIZE_OPTIONS::COPY_INIT) inline
resize() [4/5]
template<typename _TYPE_ , typename _SIZE_ > void TRUSTTab< _TYPE_, _SIZE_ >::resize (_SIZE_ n1, int n2, int n3, int n4, RESIZE_OPTIONS opt = RESIZE_OPTIONS::COPY_INIT) inline
resize() [5/5]
template<typename _TYPE_ , typename _SIZE_ > void TRUSTTab< _TYPE_, _SIZE_ >::resize (const TRUSTArray< _SIZE_, int > & tailles, RESIZE_OPTIONS opt = RESIZE_OPTIONS::COPY_INIT) inline
copy()
template<typename _TYPE_ , typename _SIZE_ > void TRUSTTab< _TYPE_, _SIZE_ >::copy (const TRUSTTab< _TYPE_, _SIZE_ > & , RESIZE_OPTIONS opt = RESIZE_OPTIONS::COPY_INIT) inline
Referenced by Solveur_Masse_base::ajouter_masse(), Solveur_Masse_base::ajouter_masse_dt_local(), Masse_DG_Elem::appliquer_impl(), Convection_Diffusion_Temperature::calcul_indic_pena_global(), Navier_Stokes_FT_Disc::calculer_dI_dt(), Op_Moyenne::completer(), Domaine_VEF::construire_ok_arete(), Equation_base::derivee_en_temps_conv(), Convection_Diffusion_Temperature::derivee_en_temps_inco(), Navier_Stokes_FT_Disc::derivee_en_temps_inco(), Navier_Stokes_Fluide_Dilatable_Proto::derivee_en_temps_inco_impl(), Solveur_Masse_base::get_masse_divide_by_local_dt(), Solveur_Masse_base::get_masse_dt_local(), and Navier_Stokes_std::uzawa().
append_line() [1/4]
template<typename _TYPE_ , typename _SIZE_ > void TRUSTTab< _TYPE_, _SIZE_ >::append_line (_TYPE_) inline
Referenced by Champ_Elem_DG::allocate_mass_matrix(), Champ_Elem_DG::allocate_transition_matrix(), SETS::assembler(), Assembleur_P_PolyMAC::assembler_mat(), Assembleur_P_PolyMAC_P0::assembler_mat(), Assembleur_P_PolyMAC_P0P1NC::assembler_mat(), Maillage_FT_Disc::calcul_indicatrice(), Redistribute_Field::compute_send_blocs(), Maillage_FT_Disc::creer_sommets_virtuels(), Op_Grad_PolyMAC_Face::dimensionner(), Op_Conv_EF_Stab_PolyMAC_Face::dimensionner(), Op_Diff_PolyMAC_Elem::dimensionner(), Op_Diff_PolyMAC_Face::dimensionner(), Op_Div_PolyMAC_P0::dimensionner(), Masse_PolyMAC_Elem::dimensionner(), Masse_PolyMAC_Face::dimensionner(), Source_Transport_Eps_VDF_Elem::dimensionner_blocs(), Masse_PolyMAC_P0_Face::dimensionner_blocs(), Op_Grad_VDF_Face::dimensionner_blocs(), Perte_Charge_Singuliere_VDF_Face::dimensionner_blocs(), Op_Conv_EF_Stab_PolyMAC_P0_Face::dimensionner_blocs(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Face::dimensionner_blocs(), Op_Div_PolyMAC_P0P1NC::dimensionner_blocs(), Op_Grad_PolyMAC_P0_Face::dimensionner_blocs(), Op_Grad_PolyMAC_P0P1NC_Face::dimensionner_blocs(), Coalescence_bulles_1groupe_PolyMAC_P0::dimensionner_blocs(), Coalescence_bulles_2groupes_PolyMAC_P0::dimensionner_blocs(), Flux_2groupes_PolyMAC_P0::dimensionner_blocs(), Rupture_bulles_1groupe_PolyMAC_P0::dimensionner_blocs(), Rupture_bulles_2groupes_PolyMAC_P0::dimensionner_blocs(), Variation_rho::dimensionner_blocs(), Diffusion_supplementaire_echelle_temp_turb_PolyMAC_P0::dimensionner_blocs(), Source_Diffusion_supplementaire_echelle_temp_turb::dimensionner_blocs(), Source_Dissipation_energie_cin_turb::dimensionner_blocs(), Source_Production_echelle_temp_taux_diss_turb::dimensionner_blocs(), Source_Production_energie_cin_turb::dimensionner_blocs(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::dimensionner_blocs(), Op_Diff_PolyMAC_P0_Elem::dimensionner_blocs(), Perte_Charge_Singuliere_PolyMAC_P0P1NC_Face::dimensionner_blocs(), Terme_Source_Decroissance_Radioactive_Elem_PolyMAC::dimensionner_blocs(), Op_Evanescence_Homogene_Elem_base::dimensionner_blocs(), Op_Evanescence_Homogene_Face_base::dimensionner_blocs(), Source_Flux_interfacial_base::dimensionner_blocs(), Source_Force_Tchen_base::dimensionner_blocs(), Source_Frottement_interfacial_base::dimensionner_blocs(), Source_Travail_pression_Elem_base::dimensionner_blocs(), DP_Impose_VEF_Face::dimensionner_blocs(), Dispersion_bulles_PolyMAC_P0::dimensionner_blocs_aux(), Force_Tchen_PolyMAC_P0::dimensionner_blocs_aux(), Frottement_interfacial_PolyMAC_P0::dimensionner_blocs_aux(), Op_Evanescence_Homogene_PolyMAC_P0_Face::dimensionner_blocs_aux(), Op_Conv_VDF_base::dimensionner_blocs_elem(), Op_Diff_PolyMAC_P0P1NC_Face::dimensionner_blocs_ext(), Op_Conv_VDF_base::dimensionner_blocs_face(), Solveur_Masse_Face_proto::dimensionner_blocs_proto(), Solveur_Masse_Elem_proto::dimensionner_blocs_proto(), Assembleur_P_PolyMAC_P0::dimensionner_continuite(), Assembleur_P_PolyMAC_P0P1NC::dimensionner_continuite(), Assembleur_P_VDF::dimensionner_continuite(), Op_Diff_PolyMAC_Elem::dimensionner_termes_croises(), Op_Diff_VDF_Elem_base::dimensionner_termes_croises(), SETS::eliminer(), Matrice_Dense::get_stencil(), Matrice_Morse_Sym::get_symmetric_stencil(), Matrice_Morse_Sym::get_symmetric_stencil_and_coefficients(), Domaine_PolyMAC::init_m1_2d(), Domaine_PolyMAC::init_m1_3d(), Domaine_PolyMAC::init_m2solv(), Couplage_Parietal_PolyMAC_helper::init_op_ext(), Champ_Face_PolyMAC::init_ra(), Domaine_PolyMAC::init_rf(), Domaine_PolyMAC_P0::init_stencils(), Champ_Face_PolyMAC::init_va(), Domaine_PolyMAC::init_ve(), Champ_Face_PolyMAC_P0::init_ve2(), Domaine_PolyMAC::init_we_2d(), Domaine_PolyMAC::init_we_3d(), Cut_cell_FT_Disc::initialise_communications(), IJK_Interfaces::recursive_calcul_distance_chez_voisin(), Collision_Model_FT_base::set_LC_zones(), Remaillage_FT::supprimer_petites_aretes(), Remaillage_FT_IJK::supprimer_petites_aretes(), and Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_elem().
append_line() [2/4]
template<typename _TYPE_ , typename _SIZE_ > void TRUSTTab< _TYPE_, _SIZE_ >::append_line (_TYPE_ , _TYPE_) inline
append_line() [3/4]
template<typename _TYPE_ , typename _SIZE_ > void TRUSTTab< _TYPE_, _SIZE_ >::append_line (_TYPE_ , _TYPE_ , _TYPE_) inline
append_line() [4/4]
template<typename _TYPE_ , typename _SIZE_ > void TRUSTTab< _TYPE_, _SIZE_ >::append_line (_TYPE_ , _TYPE_ , _TYPE_ , _TYPE_) inline
dimension()
template<typename _TYPE_ , typename _SIZE_ > _SIZE_ TRUSTTab< _TYPE_, _SIZE_ >::dimension (int d) const
Referenced by Cut_cell_FT_Disc::add_and_remove_local_elements(), Operateur_Conv_sensibility_VEF::add_diffusion_term(), Matrix_tools::add_scaled_matrices(), Matrix_tools::add_symmetric_scaled_matrices(), Matrice_Grossiere::add_virt_bloc(), Champ_Face_VDF::affecter(), Champ_Inc_base::affecter_(), Champ_Face_VDF::affecter_(), Champ_P1NC::affecter_(), Champ_Elem_DG::affecter_(), Champ_Fonc_P1_DG::affecter_(), Champ_Uniforme_Morceaux::affecter_(), Op_Diff_VDF_base::ajoute_terme_pour_axi(), Op_Dift_VDF_base::ajoute_terme_pour_axi_turb(), Masse_ajoutee_Cai::ajouter(), Masse_ajoutee_Coef_Constant::ajouter(), Masse_ajoutee_Wijngaarden::ajouter(), Masse_ajoutee_Zuber::ajouter(), Operateur_Conv_sensibility_VEF::ajouter(), Iterateur_PolyMAC_Elem< _TYPE_ >::ajouter(), Op_Diff_PolyMAC_Elem::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Centre_EF_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_EF_VEF_P1NC::ajouter(), Op_Conv_EF_VEF_P1NC_Stab::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_Muscl_New_VEF_Face::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Conv_Vort_VEF_Face::ajouter(), Op_Diff_VEF_Anisotrope_Face::ajouter(), Op_Diff_VEF_Face::ajouter(), Op_Diff_VEF_Face_Q1::ajouter(), Op_Div_VEFP1B_Elem::ajouter(), Domaine_32_64< _SIZE_ >::ajouter(), Faces_32_64< _SIZE_ >::ajouter(), Source_Flottabilite::ajouter(), Source_Masse_Ajoutee::ajouter(), Source_Trainee::ajouter(), Source_Reaction_Particules_VDF::ajouter(), Source_Reaction_Particules_VEF::ajouter(), Perte_Charge_PolyMAC::ajouter(), Terme_Boussinesq_VEF_Face::ajouter(), Terme_Boussinesq_VEFPreP1B_Face::ajouter(), Terme_Source_Acceleration_VEF_Face::ajouter(), Terme_Source_Constituant_Vortex_VEF_Face::ajouter(), Source_PDF_EF::ajouter_(), Source_QC_Chaleur::ajouter_(), Source_WC_Chaleur::ajouter_(), Op_Diff_VEF_Face_Stab::ajouter_antidiffusion(), Source_Transport_Eps_VDF_Elem::ajouter_blocs(), Source_Transport_K_VDF_Elem::ajouter_blocs(), Source_Transport_K_Eps_VDF_Elem::ajouter_blocs(), Source_Transport_K_Omega_VDF_Elem::ajouter_blocs(), Terme_Source_Acceleration_VDF_Face::ajouter_blocs(), Terme_Source_Qdm_VDF_Face::ajouter_blocs(), Op_Grad_PolyMAC_P0P1NC_Face::ajouter_blocs(), Flux_2groupes_PolyMAC_P0::ajouter_blocs(), Source_injection_masse_base::ajouter_blocs(), Diffusion_supplementaire_echelle_temp_turb_PolyMAC_P0::ajouter_blocs(), Dissipation_WIT_PolyMAC_P0::ajouter_blocs(), Production_energie_cin_turb_PolyMAC_P0::ajouter_blocs(), Production_WIT_PolyMAC_P0::ajouter_blocs(), Source_BIF_PolyMAC_P0::ajouter_blocs(), Source_Dissipation_energie_cin_turb::ajouter_blocs(), Diffusion_supplementaire_echelle_temp_turb_VDF::ajouter_blocs(), Production_energie_cin_turb_VDF::ajouter_blocs(), Perte_Charge_PolyMAC::ajouter_blocs(), Perte_Charge_VDF_base::ajouter_blocs(), Correction_Lubchenko_PolyMAC_P0::ajouter_blocs_BIF(), Op_Div_PolyMAC_P0P1NC::ajouter_blocs_ext(), Op_Diff_PolyMAC_P0P1NC_Elem::ajouter_blocs_ext(), Op_Diff_PolyMAC_P0P1NC_Face::ajouter_blocs_ext(), Op_Grad_EF::ajouter_bord(), Sonde::ajouter_bords(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_scalaire(), Op_Conv_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution(), Op_Diff_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Face_Stab::ajouter_contribution(), Iterateur_PolyMAC_Elem< _TYPE_ >::ajouter_contribution(), Op_Conv_RT_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face_Stab::ajouter_contribution_multi_scalaire(), Transport_Interfaces_FT_Disc::ajouter_contribution_saut_vitesse(), Iterateur_PolyMAC_Elem< _TYPE_ >::ajouter_contribution_vitesse(), Operateur_Conv_sensibility_VEF::ajouter_conv_term(), Op_Diff_VEF_Face_Stab::ajouter_diffusion(), Polyedre_32_64< _SIZE_ >::ajouter_elements(), Masse_ajoutee_Cai::ajouter_inj(), Masse_ajoutee_Coef_Constant::ajouter_inj(), Masse_ajoutee_Wijngaarden::ajouter_inj(), Masse_ajoutee_Zuber::ajouter_inj(), Operateur_Conv_sensibility_VEF::ajouter_Lsensibility_state_Amont(), Operateur_Conv_sensibility_VEF::ajouter_Lstate_sensibility_Amont(), Maillage_FT_Disc::ajouter_maillage(), Matrice_Morse::ajouter_multTab_(), Matrice_Morse_Sym::ajouter_multTab_(), Matrice_Diagonale::ajouter_multTab_(), Op_Diff_VEF_Face_Stab::ajouter_operateur_centre(), Proprietes_part_vol::ajouter_proprietes(), Domaine_PolyMAC::ajouter_stabilisation(), Terme_Source_Constituant_Vortex_VEF_Face::ajouter_terme_div_u(), Op_Diff_PolyMAC_Elem::ajouter_termes_croises(), Op_Conv_ALE_VEF::ajouterALE(), Matrix_tools::allocate_for_scaled_addition(), Matrix_tools::allocate_for_symmetric_scaled_addition(), Matrix_tools::allocate_morse_matrix(), Matrix_tools::allocate_symmetric_morse_matrix(), Solveur_Masse_EF::appliquer_impl(), Masse_PolyMAC_Elem::appliquer_impl(), Masse_VDF_Elem::appliquer_impl(), Masse_VDF_Face::appliquer_impl(), Masse_VEF_P1NC::appliquer_impl(), Refine_Mesh::apply_2D(), Refine_Mesh::apply_3D(), Cut_cell_FT_Disc::apply_permutation(), Convection_Diffusion_Espece_Multi_QC::assembler(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_blocs(), Convection_Diffusion_Espece_Multi_QC::assembler_blocs_avec_inertie(), Assembleur_P_PolyMAC_P0P1NC::assembler_continuite(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_impl(), Assembleur_P_EF::assembler_mat(), Assembleur_P_PolyMAC::assembler_mat(), Assembleur_P_PolyMAC_P0P1NC::assembler_mat(), Simpler_Base::assembler_matrice_pression_implicite(), Op_Diff_VEF_base::associer(), Eval_Dift_VDF::associer_diff_turb(), Ensemble_Faces_base::associer_les_cl(), Source_PDF_EF::associer_pb(), Octree_Int_32_64< _SIZE_ >::build(), Refine_Mesh::build_edges(), Refine_Mesh::build_incidence_from_node_to_edges(), Domaine_VF::build_mc_dual_mesh(), Domaine_VF::build_mc_face_mesh(), Matrix_tools::build_morse_matrix(), Refine_Mesh::build_new_cells_2D(), Refine_Mesh::build_new_cells_3D(), Refine_Mesh::build_new_frontier_faces_2D(), Refine_Mesh::build_new_frontier_faces_3D(), Refine_Mesh::build_new_nodes(), Domaine_DG::build_nfaces_elem_(), Matrice_Bloc::build_stencil(), Matrix_tools::build_symmetric_morse_matrix(), Ch_front_input::buildSommetsFaces(), Loi_paroi_adaptative::calc_y_plus(), Loi_paroi_log::calc_y_plus(), Modele_Lam_Bremhorst_VEF::Calcul_Cmu(), Modele_Lam_Bremhorst_VEF::Calcul_Cmu_BiK(), Modele_Lam_Bremhorst_VEF::Calcul_Cmu_Paroi(), Modele_Lam_Bremhorst_VEF::Calcul_Cmu_Paroi_BiK(), Maillage_FT_Disc::calcul_courbure_sommets(), Transport_Interfaces_FT_Disc::calcul_effort_fluide_interface(), Champ_P1NC::calcul_h_conv(), Maillage_FT_Disc::calcul_indicatrice(), Parcours_interface::calcul_intersection_facelem_3D(), Modele_Lam_Bremhorst_VEF::calcul_norme_elem(), Transport_Marqueur_FT::calcul_proprietes_geometriques(), Transport_Interfaces_FT_Disc::calcul_source(), Traitement_particulier_NS_THI_VEF::calcul_spectre(), Maillage_FT_Disc::calcul_surface_normale(), Traitement_particulier_NS_temperature_VEF::calcul_temperature(), Corrige_flux_FT_temperature_conv::calcul_temperature_flux_interface(), Modele_Lam_Bremhorst_VEF::calcul_tenseur_Re(), Modele_Lam_Bremhorst_VEF::calcul_tenseur_Re_BiK(), Modele_Lam_Bremhorst_VEF::calcul_tenseur_Re_elem_BiK(), Modele_Lam_Bremhorst_VEF::calcul_tenseur_Re_elem_shih(), Modele_Lam_Bremhorst_VEF::calcul_tenseur_Re_shih(), Modele_Shih_Zhu_Lumley_VEF::Calcul_Tenseurs_S_et_R_elem(), Modele_Shih_Zhu_Lumley_VEF::Calcul_Tenseurs_S_et_R_elem_Paroi(), Transport_Interfaces_FT_Disc::calcul_vitesse(), Transport_Marqueur_FT::calcul_vitesse_p(), FT_Field::Calculate_Facette_Intersection_Area(), Maillage_FT_Disc::calcule_equation_plan_areteFa7(), Source_Con_Phase_field::calculer_alpha_gradC_carre(), Op_Dift_EF_base::calculer_borne_locale(), Op_Dift_VEF_base::calculer_borne_locale(), IJK_Interfaces::calculer_bounding_box_bulles(), Aretes::calculer_centre_de_gravite(), Elem_geom_base_32_64< _SIZE_ >::calculer_centres_gravite(), Polyedre_32_64< _SIZE_ >::calculer_centres_gravite(), Polygone_32_64< _SIZE_ >::calculer_centres_gravite(), Navier_Stokes_FT_Disc::calculer_champ_forces_superficielles(), Op_Diff_VEF_Face_Stab::calculer_coefficients(), Maillage_FT_IJK::calculer_compo_connexe_sommets(), Remaillage_FT::calculer_connectivites_sommetFacettes(), Moyenne_volumique::calculer_convolution(), Moyenne_volumique::calculer_convolution_champ_elem(), Marching_Cubes::calculer_coord_noeuds(), Maillage_FT_Disc::calculer_coord_noeuds(), Remaillage_FT::calculer_correction_deplacement(), Simple::calculer_correction_en_vitesse(), Loi_Etat_TPPI_QC_base::calculer_Cp(), Loi_Etat_TPPI_WC_base::calculer_Cp(), Navier_Stokes_FT_Disc::calculer_delta_u_interface(), Champ_front_base::calculer_derivee_en_temps(), Champ_front_Parametrique::calculer_derivee_en_temps(), Navier_Stokes_FT_Disc::calculer_dI_dt(), Remaillage_FT::calculer_differentielle_volume(), Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re::calculer_diffusivite_turbulente(), IJK_Interfaces::calculer_distance_autres_compo_connexe_ijk(), IJK_Interfaces::calculer_distance_autres_compo_connexe_octree(), Source_Con_Phase_field::calculer_div_alpha_gradC(), Navier_Stokes_FT_Disc::calculer_div_normale_interface(), Op_Diff_DG_base::calculer_dt_stab(), Op_Dift_EF_Q1::calculer_dt_stab(), Op_Conv_EF_Stab_PolyMAC_P0_Face::calculer_dt_stab(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::calculer_dt_stab(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Face::calculer_dt_stab(), Op_Diff_PolyMAC_base::calculer_dt_stab(), Op_Diff_PolyMAC_P0_Elem::calculer_dt_stab(), Op_Diff_PolyMAC_P0_Face::calculer_dt_stab(), Op_Diff_PolyMAC_P0P1NC_Elem::calculer_dt_stab(), Op_Diff_PolyMAC_P0P1NC_Face::calculer_dt_stab(), Op_Dift_Multiphase_VDF_Elem::calculer_dt_stab(), Op_Dift_Multiphase_VDF_Face::calculer_dt_stab(), Op_Conv_Muscl_New_VEF_Face::calculer_dt_stab(), Op_Dift_VEF_base::calculer_dt_stab(), Op_Dift_VDF_Face_base::calculer_dt_stab(), Op_Diff_VDF_base::calculer_dt_stab_(), Scatter::calculer_espace_distant(), Iterateur_PolyMAC_Elem< _TYPE_ >::calculer_flux_bord(), Op_Grad_VEF_P1B_Face::calculer_flux_bords(), Op_Dift_VEF_P1NCP1B_Face::calculer_gradient_som(), Partitionneur_base_32_64< _SIZE_ >::calculer_graphe_connexions_periodiques(), Loi_Etat_rhoT_GR_QC::calculer_H(), Echange_contact_VDF::calculer_h_autre_pb(), Terme_Source_Acceleration::calculer_la_source(), Op_Diff_VEF_Face_Stab::calculer_max(), Op_Diff_VEF_Face_Stab::calculer_min(), Traitement_particulier_NS_canal_VDF::calculer_moyenne_spatiale_vitesse_rho_mu(), Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_vitesse_rho_mu(), Source_Con_Phase_field::calculer_mutilde(), Source_Con_Phase_field::calculer_mutilde_demi(), Hexaedre_32_64< _SIZE_ >::calculer_normales(), Rectangle_32_64< _SIZE_ >::calculer_normales(), Tetraedre_32_64< _SIZE_ >::calculer_normales(), Triangle_32_64< _SIZE_ >::calculer_normales(), Op_Dift_VEF_base::calculer_pour_post(), Navier_Stokes_std::calculer_pression_hydrostatique(), Transport_Marqueur_FT::calculer_proprietes_fluide_pos_particules(), Navier_Stokes_phase_field::calculer_rho(), Transport_Interfaces_FT_Disc::calculer_scalaire_interpole(), Parcours_interface::calculer_sortie_face_bord(), Faces_32_64< _SIZE_ >::calculer_surfaces(), Echange_contact_rayo_semi_transp_VDF::calculer_Teta_equiv(), Echange_contact_VDF::calculer_Teta_equiv(), Paroi_flux_impose_Rayo_transp::calculer_Teta_i_VDF(), IJK_Interfaces::calculer_var_volume_remaillage(), Source_PDF_EF::calculer_variable_imposee_elem_fluid(), Source_PDF_EF::calculer_variable_imposee_hybrid(), Source_PDF_EF::calculer_variable_imposee_mean_grad(), Remaillage_FT::calculer_variation_volume(), Modele_turbulence_hyd_combinaison::calculer_viscosite_turbulente(), Modele_turbulence_hyd_K_Eps::calculer_viscosite_turbulente(), Modele_turbulence_hyd_K_Eps_2_Couches::calculer_viscosite_turbulente(), Modele_turbulence_hyd_K_Eps_Bas_Reynolds::calculer_viscosite_turbulente(), Modele_turbulence_hyd_K_Eps_Bicephale::calculer_viscosite_turbulente(), Modele_turbulence_hyd_K_Eps_Realisable::calculer_viscosite_turbulente(), Modele_turbulence_hyd_K_Eps_Realisable_Bicephale::calculer_viscosite_turbulente(), Modele_turbulence_hyd_K_Omega::calculer_viscosite_turbulente(), Terme_Source_Acceleration_VDF_Face::calculer_vitesse_faces(), Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl(), Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl_u_star(), Transport_Interfaces_FT_Disc::calculer_vitesse_transport_interpolee(), Transport_Interfaces_FT_Disc::calculer_vmoy_composantes_connexes(), IJK_Interfaces::calculer_vmoy_rotation_composantes_connexes(), IJK_Interfaces::calculer_vmoy_translation_composantes_connexes(), Maillage_FT_Disc::calculer_voisinage_facettes(), Remaillage_FT::calculer_volume_sommets_supprimes(), Discretisation_tools::cells_to_faces(), Discretisation_tools::cells_to_nodes(), Echange_global_impose::champ_exterieur(), Echange_couplage_thermique::champ_exterieur(), Assembleur_P_VEFPreP1B::changer_base(), Desc_Structure_FT::check(), Rectify_Mesh::check_cell_enumeration_3D(), Rectify_Mesh::check_cell_orientation_2D(), Rectify_Mesh::check_cell_orientation_3D(), Reordonner_faces_periodiques_32_64< _SIZE_ >::check_faces_periodiques(), Maillage_FT_Disc::check_mesh(), Maillage_FT_Disc::check_sommets(), Maillage_FT_IJK::check_sommets(), Fluide_reel_base::check_unknown_range(), Scatter::Chercher_Correspondance(), Faces_builder::chercher_face_element(), Op_Diff_VEFP1NCP1B_Face::coeff_matrice_som(), Op_Diff_VEFP1NCP1B_Face::coeff_matrice_som_CL(), Op_Diff_VEFP1NCP1B_Face::coeff_matrice_som_perio(), Op_Diff_VEFP1NCP1B_Face::coeff_matrice_som_symetrie(), Frottement_interfacial_Ishii_Zuber_Deformable::coefficient(), Frottement_interfacial_Kumar_Brooks::coefficient(), Frottement_interfacial_Tomiyama_complet::coefficient(), Frottement_interfacial_bulles_composant::coefficient(), Frottement_interfacial_bulles_constant::coefficient(), Frottement_interfacial_Garnier::coefficient(), Frottement_interfacial_Ishii_Zuber::coefficient(), Frottement_interfacial_Rusche::coefficient(), Frottement_interfacial_Simonnet::coefficient(), Frottement_interfacial_Tomiyama::coefficient(), Frottement_interfacial_Zenit::coefficient(), Coalescence_bulles_1groupe_Yao_Morel::coefficient(), Rupture_bulles_1groupe_Yao_Morel::coefficient(), Dispersion_bulles_turbulente_Bazin::coefficient(), Dispersion_bulles_turbulente_Bertodano::coefficient(), Dispersion_bulles_turbulente_Burns::coefficient(), Dispersion_bulles_turbulente_constante::coefficient(), Dispersion_bulles_turbulente_Lavieville::coefficient(), Portance_interfaciale_Sugrue_Modifiee::coefficient(), Portance_interfaciale_Tomiyama_complet::coefficient(), Dispersion_bulles_constante::coefficient(), Portance_interfaciale_Constante::coefficient(), Portance_interfaciale_Sugrue::coefficient(), Portance_interfaciale_Tomiyama::coefficient(), Frottement_interfacial_Ishii_Zuber_Deformable::coefficient_CD(), Frottement_interfacial_Kumar_Brooks::coefficient_CD(), Frottement_interfacial_Tomiyama_complet::coefficient_CD(), Frottement_interfacial_Ishii_Zuber::coefficient_CD(), Frottement_interfacial_Tomiyama::coefficient_CD(), Flux_interfacial_constant_Nu::coeffs(), Flux_interfacial_Chen_Mayinger::coeffs(), Flux_interfacial_Kim_Park::coeffs(), Flux_interfacial_Ranz_Marshall::coeffs(), Flux_interfacial_Wolfert::coeffs(), Flux_interfacial_Wolfert_composant::coeffs(), Flux_interfacial_Zeitoun::coeffs(), Flux_interfacial_Coef_Constant::coeffs(), Raccord_distant_homogene_32_64< _SIZE_ >::completer(), Champ_Generique_Reduction_0D::completer(), Op_Correlation::completer(), FT_Field::completer_compo_connexe_partielle(), Navier_Stokes_FT_Disc::compute_boussinesq_additional_gravity(), Source_PDF_EF::compute_coeff_elem(), Source_PDF_EF::compute_coeff_matrice(), Source_Transport_K_Omega_VEF_Face::compute_cross_diffusion(), Convection_Diffusion_Temperature_FT_Disc::compute_divergence_free_velocity_extension(), IJK_Thermal_cut_cell::compute_interfacial_temperature2(), Redistribute_Field::compute_send_blocs(), Triple_Line_Model_FT_Disc::compute_TCL_fluxes_in_all_boundary_cells(), Source_PDF_EF::compute_variable_imposee_projete(), IJK_Interfaces::compute_vinterp(), Cut_cell_FT_Disc::compute_virtual_independent_index(), Transport_Marqueur_FT::construction_ensemble_proprietes(), Domaine_32_64< _SIZE_ >::construire_elem_virt_pe_num(), Domain_Graph::construire_graph_elem_elem(), Maillage_FT_Disc::construire_noeuds(), Marching_Cubes::construire_noeuds_liste_faces(), Marching_Cubes::construire_noeuds_uniques(), Domaine_VF::construire_num_fac_loc(), Domaine_VEF::construire_ok_arete(), Partitionneur_Partition::construire_partition(), Op_Conv_VEF_Face::contribue_au_second_membre(), Op_Diff_VEF_Face::contribue_au_second_membre(), Source_Transport_K_Eps_VEF_Face::contribuer_a_avec(), Source_Transport_K_Omega_VEF_Face::contribuer_a_avec(), Source_PDF_EF::contribuer_a_avec(), Op_Diff_PolyMAC_Elem::contribuer_a_avec(), Perte_Charge_PolyMAC::contribuer_a_avec(), Terme_Puissance_Thermique_Echange_Impose_VEF_Face::contribuer_a_avec(), Iterateur_PolyMAC_Elem< _TYPE_ >::contribuer_au_second_membre(), Op_Diff_DG_Elem::contribuer_au_second_membre(), Op_Diff_PolyMAC_Elem::contribuer_termes_croises(), Op_Diff_VDF_Elem_base::contribuer_termes_croises(), Transport_Fluctuation_Temperature::controler_grandeur(), Transport_Fluctuation_Temperature_W::controler_grandeur(), Transport_Flux_Chaleur_Turbulente::controler_grandeur(), Transport_K_Eps_base::controler_K_Eps(), Transport_K_Omega_base::controler_K_Omega(), Transport_K_ou_Eps_base::controler_variable(), Navier_Stokes_FT_Disc::correct_at_exit_bad_gradient(), Source_PDF_EF::correct_incr_pressure(), Source_PDF_EF::correct_variable(), Marching_Cubes::correspondance_espaces_distant_virtuel(), Corriger_frontiere_periodique_32_64< _SIZE_ >::corriger_coordonnees_sommets_perio(), Partitionneur_base_32_64< _SIZE_ >::corriger_multiperiodique(), Maillage_FT_Disc::corriger_proprietaires_facettes(), Partitionneur_base_32_64< _SIZE_ >::corriger_sommets_bord(), Parcours_interface::coupe_face_rectangulaire(), Remove_elem::creer_faces(), Faces_builder::creer_faces_reeles(), Maillage_FT_Disc::creer_facettes_virtuelles(), Maillage_FT_Disc::creer_sommets_virtuels(), Tetraedriser_homogene_compact::decoupe(), Tetraedriser_homogene_fin::decoupe(), Decouper_Bord_coincident::decouper_(), Polynome::degre(), Transport_Interfaces_FT_Disc::deplacer_maillage_ft_v_fluide(), Maillage_FT_Disc::deplacer_sommets(), Maillage_FT_IJK::deplacer_sommets(), Maillage_FT_Disc::deplacer_un_sommet(), Navier_Stokes_FT_Disc::derivee_en_temps_inco(), Equation_IBM_proto::derivee_en_temps_inco_ibm_proto(), Op_EF_base::dimensionner(), Op_PolyMAC_Elem::dimensionner(), Matrice_Morse::dimensionner(), Roue::dimensionner(), Op_Diff_DG_Elem::dimensionner(), Op_Conv_EF_Stab_PolyMAC_Face::dimensionner(), Op_Diff_PolyMAC_Elem::dimensionner(), Op_Div_PolyMAC_P0P1NC::dimensionner_blocs(), Op_Grad_PolyMAC_P0P1NC_Face::dimensionner_blocs(), Op_Diff_PolyMAC_P0_Elem::dimensionner_blocs(), Source_Travail_pression_Elem_base::dimensionner_blocs(), Op_Diff_PolyMAC_P0P1NC_Elem::dimensionner_blocs_ext(), Op_Diff_PolyMAC_P0P1NC_Face::dimensionner_blocs_ext(), Assembleur_P_PolyMAC_P0P1NC::dimensionner_continuite(), Op_Diff_PolyMAC_Elem::dimensionner_termes_croises(), Op_Diff_VDF_Elem_base::dimensionner_termes_croises(), Domaine_DG::discretiser(), Domaine_Poly_base::discretiser(), Domaine_VEF::discretiser_arete(), Domaine_Poly_base::discretiser_aretes(), Source_Con_Phase_field::div_kappa_grad(), Remaillage_FT::diviser_grandes_aretes(), Remaillage_FT_IJK::diviser_grandes_aretes(), Source_Con_Phase_field::drhodc(), Source_Con_Phase_field::dWdc_naire_analytique_quaternaire(), Source_Con_Phase_field::dWdc_naire_analytique_ternaire(), Source_Con_Phase_field::dWdc_naire_defaut(), Maillage_FT_Disc::echanger_sommets_PE(), Format_Post_Lml::ecrire_champ_lml(), Format_Post_XYZ::ecrire_champ_xyz(), Format_Post_Lata::ecrire_domaine_low_level(), Convection_Diffusion_Temperature::ecrire_fichier_pena_th(), Format_Post_Lml::ecrire_item_int_lml(), Postraitement_ft_lata::ecrire_maillage_ft_disc(), Maillage_FT_Disc::ecrire_plot(), Postprocessing_IJK::ecrire_statistiques_bulles(), Sauvegarde_Reprise_Maillage_FT::ecrire_xyz(), EcritureLectureSpecial::ecriture_special(), Viscosite_turbulente_k_omega::eddy_viscosity(), Viscosite_turbulente_k_tau::eddy_viscosity(), Viscosite_turbulente_l_melange::eddy_viscosity(), Viscosite_turbulente_multiple::eddy_viscosity(), Viscosite_turbulente_Smagorinsky::eddy_viscosity(), Viscosite_turbulente_WALE::eddy_viscosity(), Domaine_Poly_base::elem_arete_d(), Domaine_Poly_base::elem_som_d(), Parcours_interface::eloigner_sommets_des_faces(), Echange_impose_base::emissivite(), Viscosite_turbulente_k_omega::eps(), Viscosite_turbulente_k_tau::eps(), Viscosite_turbulente_multiple::eps(), Champ_Elem_DG::eval_bfunc(), Champ_Elem_DG::eval_bfunc_on_facets(), Champ_Elem_DG::eval_elem(), Parser_Eval::eval_fct(), Moyenne_volumique::eval_filtre(), Champ_Elem_DG::eval_grad_bfunc(), Champ_Elem_DG::eval_grad_bfunc_on_facets(), Vitesse_derive_Spelt_Biesheuvel::evaluate_C0_vg0(), Vitesse_derive_Forces::evaluate_C0_vg0(), Vitesse_derive_Ishii::evaluate_C0_vg0(), FT_Field::exchange_data(), Matrix_tools::extend_matrix_stencil(), TroisDto2D_32_64< _SIZE_ >::extraire_2D(), Domaine_bord_32_64< _SIZE_ >::extraire_domaine_bord(), ExtrudeParoi::extrude(), Extruder::extruder(), Extruder_en20::extruder(), Extruder_en3::extruder(), Extruder::extruder_hexa(), Domaine_VF::face_virt_pe_num(), Discretisation_tools::faces_to_cells(), Maillage_FT_Disc::facette_PE_owner(), Maillage_FT_Disc::facettes_voisines(), Domaine_PolyMAC_P0::fgrad(), Cut_cell_FT_Disc::fill_buffer_with_variable(), Matrix_tools::fill_csr_arrays(), LireMED_32_64< _SIZE_ >::fill_frontieres(), Modele_turbulence_hyd_K_Omega::fill_turbulent_viscosity_tab(), Cut_cell_FT_Disc::fill_variable_with_buffer(), Postraitement_ft_lata::filter_out_array(), Postraitement_ft_lata::filter_out_virtual_fa7(), Source_PDF_EF::filtre_CLD(), Champ_P1NC_implementation::filtrer_H1(), Champ_P1NC_implementation::filtrer_resu(), LireMED_32_64< _SIZE_ >::finalize_sommets(), Cut_cell_FT_Disc::find_value_unsorted(), Sonde::fix_probe_position_grav(), Neumann::flux_impose(), Paroi_Rayo_transp::flux_impose(), Flux_radiatif_base::flux_impose(), Neumann_paroi_rayo_semi_transp_VDF::flux_impose(), Neumann_paroi_rayo_semi_transp_VEF::flux_impose(), Sortie_libre_pression_imposee_QC::flux_impose(), Sortie_libre_pression_moyenne_imposee::flux_impose(), Sortie_libre_Text_H_ext::flux_impose(), Sortie_libre_pression_imposee::flux_impose(), Ensemble_Lagrange_base::generer_marqueurs_sz(), Champ_Generique_Reduction_0D::get_champ(), Champ_Generique_Transformation::get_champ(), Champ_Post_Operateur_Eqn::get_champ(), Champ_Generique_Interpolation::get_champ_with_calculer_champ_post(), Champ_front_recyclage::get_coord_faces(), Champ_Generique_refChamp::get_dimension(), Transport_Interfaces_FT_Disc::get_expression_vitesse_imposee(), FT_Field::get_Grad_FT_field_Array(), FT_Field::get_interfacial_source_term_sommets(), FT_Field::get_interfacial_source_term_sommets_non_const(), Operator_FT_Disc::get_n_sommet(), Intersection_Interface_ijk_cell::get_nb_diph(), FT_Field::get_nb_triangle_finaux(), FT_Field::get_nb_triangle_initiaux(), Domaine_VF::get_position(), Intersection_Interface_ijk::get_position_interpolation_normal_interf(), Triple_Line_Model_FT_Disc::get_Qtcl(), Matrice_Bloc::get_stencil(), Matrice_Dense::get_stencil(), Matrice_Morse::get_stencil_and_coeff_ptrs(), Matrice_Bloc::get_stencil_and_coefficients(), Matrice_Morse::get_stencil_and_coefficients(), Matrice_Bloc::get_stencil_coeff_templ(), Matrice_Base::get_stencil_size(), Matrice_Bloc_Sym::get_symmetric_stencil(), Matrice_Morse_Sym::get_symmetric_stencil(), Matrice_Bloc_Sym::get_symmetric_stencil_and_coefficients(), Matrice_Morse_Sym::get_symmetric_stencil_and_coefficients(), Triple_Line_Model_FT_Disc::get_theta_app(), Convection_Diffusion_Temperature_FT_Disc::get_Twall_at_elem(), Ch_front_input::getTemplate(), Champ_input_P0::getTemplate(), Ch_front_input_P1::getTemplate(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::Grad_P_lib_VEFPreP1B(), Champ_Q1_EF::gradient(), Champ_Q1NC::gradient(), Op_Diff_VEFP1NCP1B_Face::gradient_som(), Op_Diff_VEFP1NCP1B_Face::gradient_som_CL(), Echange_impose_base::h_imp(), Mass_Redistribution_Phase_Field::impose_mass_redistribution(), Transport_Marqueur_FT::imposer_cond_lim(), Domaine_Cl_EF::imposer_cond_lim(), Domaine_Cl_EF::imposer_symetrie(), Domaine_Cl_EF::imposer_symetrie_matrice_secmem(), Domaine_Cl_EF::imposer_symetrie_partiellement(), Source_PDF_EF::impr(), Op_EF_base::impr(), Op_VEF_Face::impr(), Transport_Interfaces_FT_Disc::impr(), Op_Div_EF::impr(), Iterateur_PolyMAC_Elem< _TYPE_ >::impr(), Op_Conv_PolyMAC_base::impr(), Op_Diff_PolyMAC_Gen_base::impr(), Op_Div_PolyMAC::impr(), Op_Div_VEFP1B_Elem::impr(), Transport_Interfaces_FT_Disc::impr_effort_fluide_interface(), Modele_turbulence_hyd_0_eq_base::imprimer(), Domaine_32_64< _SIZE_ >::indice_elements(), Postraitement::init(), Champ_Elem_PolyMAC_P0P1NC::init_auxiliary_variables(), Equation_base::init_champ_conserve(), Energie_Multiphase::init_champ_convecte(), Domaine_PolyMAC::init_equiv(), Echange_contact_PolyMAC_P0::init_fs_dist(), Domaine_PolyMAC::init_m1_2d(), Domaine_PolyMAC::init_m1_3d(), Couplage_Parietal_PolyMAC_helper::init_op_ext(), Transport_Interfaces_FT_Disc::init_particles_position_velocity(), Champ_Face_PolyMAC::init_ra(), Domaine_PolyMAC::init_rf(), Scatter::init_sequential_domain(), Domaine_PolyMAC_P0::init_stencils(), Champ_Face_PolyMAC::init_va(), Domaine_PolyMAC::init_ve(), Champ_Face_PolyMAC_P0::init_ve2(), Domaine_PolyMAC::init_we(), Domaine_PolyMAC::init_we_2d(), Domaine_PolyMAC::init_we_3d(), Cut_cell_FT_Disc::initialise(), Cut_cell_FT_Disc::initialise_communications(), Cut_cell_FT_Disc::initialise_independent_index(), Sonde::initialiser(), Loi_Etat_GR_base::initialiser(), Sonde_Int::initialiser(), Echange_contact_VDF_FT_Disc::initialiser(), Ch_front_input_uniforme::initialiser(), Ch_front_input_P1::initialiser(), Champ_front_var::initialiser(), Loi_Etat_GR_base::initialiser_inco_ch(), Redistribute_Field::initialize(), Domaine_IJK::initialize_mapping(), Domaine_IJK::initialize_splitting(), Domaine_IJK::initialize_with_mapping(), Navier_Stokes_std::initTimeStep(), Remaillage_FT::inserer_tab_aretes(), Table::instationnaire(), Champ_Fonc_Face_PolyMAC::interp_valeurs_elem(), Champ_Face_PolyMAC::interp_ve(), Champ_Face_PolyMAC_P0P1NC::interp_ve(), Transport_Interfaces_FT_Disc::interpoler_vitesse_face(), Ecr_fic_Ansys::interpreter(), Integrer_champ_med::interpreter(), Moyenne_volumique::interpreter(), Decouper_multi::interpreter(), MaillerParallel::interpreter(), Lata_2_Other::interpreter(), Distanceparoi::interpreter_(), Extraire_domaine::interpreter_(), Redresser_hexaedres_vdf::interpreter_(), VerifierCoin::interpreter_(), Corriger_frontiere_periodique_32_64< _SIZE_ >::interpreter_(), FT_Field::is_compo_in_proc(), Matrix_tools::is_diagonal_stencil(), Matrix_tools::is_normalized_stencil(), Matrix_tools::is_normalized_symmetric_stencil(), Matrix_tools::is_null_stencil(), Viscosite_turbulente_k_omega::k_over_eps(), Viscosite_turbulente_k_tau::k_over_eps(), Viscosite_turbulente_multiple::k_over_eps(), Source_Con_Phase_field::kappa_func_auto_diffusion(), Source_Con_Phase_field::laplacien(), Domaine_ALE::laplacien(), Traitement_particulier_NS_CEG::lire(), Terme_Source_Acceleration::lire_data(), Scatter::lire_domaine(), Champ_front_recyclage::lire_fichier_format1(), Transport_Interfaces_FT_Disc::lire_maillage_ft_cao(), Maillage_FT_IJK::lire_maillage_ft_dans_lata(), Proprietes_part_vol::lire_motcle_non_standard(), PDF_model::lire_motcle_non_standard(), Sauvegarde_Reprise_Maillage_FT::lire_xyz(), Domaine_PolyMAC_P0P1NC::M1(), Domaine_PolyMAC::M2(), Remaillage_FT::marquer_aretes(), Convection_Diffusion_Concentration_FT_Disc::marquer_faces_sous_domaine(), Convection_Diffusion_Concentration_Turbulent_FT_Disc::marquer_faces_sous_domaine(), EDO_Pression_th_VEF::masse_totale(), Matrice33::Matrice33(), Paroi_frottante_simple::me_calculer(), Cond_lim_k_complique_transition_flux_nul_demi::me_calculer(), Cond_lim_k_simple_flux_nul::me_calculer(), Cond_lim_omega_demi::me_calculer(), Cond_lim_omega_dix::me_calculer(), T_paroi_Champ_P0_VDF::me_calculer(), Domaine_32_64< _SIZE_ >::merge_wo_vertices_with(), Discretisation_base::mesh_numbering(), Source_Qdm_VDF_Phase_field::methode_1(), Chimie::mettre_a_jour(), Transport_Interfaces_FT_Disc::mettre_a_jour(), Echange_contact_rayo_semi_transp_VDF::mettre_a_jour(), Boundary_field_keps_from_ud::mettre_a_jour(), Champ_front_calc_interne::mettre_a_jour(), Champ_Front_Fonction::mettre_a_jour(), Champ_Fonc_Tabule_Morceaux::mettre_a_jour(), Champ_Fonc_Tabule_Morceaux_Interp::mettre_a_jour(), Echange_contact_VDF_FT_Disc::mettre_a_jour(), Echange_contact_VDF_FT_Disc_solid::mettre_a_jour(), Source_Qdm_VDF_Phase_field::mettre_a_jour(), Echange_contact_Rayo_transp_VDF::mettre_a_jour(), Champ_Fonc_Tabule_P0_EF::mettre_a_jour(), Champ_Fonc_Tabule_Elem_PolyMAC::mettre_a_jour(), Champ_Fonc_Tabule_P0_VDF::mettre_a_jour(), Champ_front_fonc_gradient_VDF::mettre_a_jour(), Echange_contact_Correlation_VDF::mettre_a_jour(), Echange_contact_VDF::mettre_a_jour(), Op_Conv_VDF_base::mettre_a_jour(), Champ_Fonc_Tabule_P0_VEF::mettre_a_jour(), Echange_contact_Correlation_VEF::mettre_a_jour(), Sonde::mettre_a_jour_bords(), Convection_Diffusion_Concentration_FT_Disc::mettre_a_jour_chimie(), Convection_Diffusion_Concentration_Turbulent_FT_Disc::mettre_a_jour_chimie(), Maillage_FT_IJK::minimum_longueur_arrete(), Convection_Diffusion_Temperature::mise_en_place_domaine_fantome(), Op_Diff_VEF_Face_Stab::modifie_pour_Cl(), Op_EF_base::modifier_flux(), Op_VEF_Face::modifier_flux(), Assembleur_P_VEFPreP1B::modifier_matrice(), Transport_turbulent_GGDH_WIT::modifier_mu(), Transport_turbulent_SGDH_WIT::modifier_mu(), Transport_turbulent_aire_interfaciale::modifier_mu(), Transport_turbulent_GGDH::modifier_mu(), Transport_turbulent_Prandtl::modifier_mu(), Transport_turbulent_SGDH::modifier_mu(), Op_Diff_Turbulent_PolyMAC_P0_Face::modifier_mu(), Viscosite_turbulente_base::modifier_mu(), Op_EF_base::modifier_pour_Cl(), Op_Diff_K_Eps_VEF_Face::modifier_pour_Cl(), Op_Diff_K_Omega_VEF_Face::modifier_pour_Cl(), Transport_Interfaces_FT_Disc::modifier_vpoint_pour_imposer_vit(), EOS_Tools_VDF::moyenne_vol(), Source_PDF_EF::multiply_coeff_volume(), Domaine_32_64< _SIZE_ >::nb_aretes(), Matrice_Dense::nb_colonnes(), Domaine_32_64< _SIZE_ >::nb_elem(), Faces_32_64< _SIZE_ >::nb_faces(), Domaine_VF::nb_faces(), Maillage_FT_Disc::nb_facettes(), Maillage_FT_Disc::nb_facettes_reelle_totale(), Maillage_FT_Disc::nb_facettes_reelles(), Maillage_FT_IJK::nb_facettes_sans_duplicata(), Maillage_FT_Disc::nb_facettes_totale(), Matrice_Dense::nb_lignes(), Domaine_32_64< _SIZE_ >::nb_som(), Domaine_VF::nb_som_face(), Maillage_FT_Disc::nb_sommets(), Champ_Don_base::nb_valeurs_nodales(), Champ_Inc_base::nb_valeurs_nodales(), Champ_Parametrique::nb_valeurs_nodales(), NettoieNoeuds_32_64< _SIZE_ >::nettoie(), FT_Field::nettoyer_espace_virtuel_facette(), Maillage_FT_Disc::nettoyer_maillage(), Maillage_FT_IJK::nettoyer_maillage(), Maillage_FT_Disc::nettoyer_noeuds_virtuels_et_frontieres(), Maillage_FT_Disc::nettoyer_phase(), Discretisation_tools::nodes_to_cells(), Polyedre_poly::normale(), Domaine_VF::numero_face_local(), Polynome::operator()(), Champ_Elem_DG::orthonormalize(), Sonde::ouvrir_fichier(), Sonde_Int::ouvrir_fichier(), Parcours_interface::parcourir(), Convection_Diffusion_Temperature::penalisation_L2(), Polyedriser_32_64< _SIZE_ >::polyedriser(), Postraitement_ft_lata::postprocess_field_values(), Sonde::postraiter(), Sonde_Int::postraiter(), Postraitement::postraiter_champs(), Postraitement::postraiter_tableau(), IJK_Interfaces::posttraiter_champs_instantanes(), Transport_Interfaces_FT_Disc::PPP_face_interface(), Transport_Interfaces_FT_Disc::PPP_face_interface_voisin(), Transport_Interfaces_FT_Disc::PPP_face_voisin(), Navier_Stokes_FT_Disc::preparer_calcul(), Collision_Model_FT_base::preparer_calcul(), Maillage_FT_Disc::preparer_tableau_avant_transport(), Maillage_FT_Disc::printFa7(), Beam_model::printOutputBeam3D(), Transport_Interfaces_FT_Disc::projete_point_face_fluide(), Transport_Interfaces_FT_Disc::projete_point_face_interface(), Raffiner_anisotrope_32_64< _SIZE_ >::raffiner_(), Convection_Diffusion_Concentration_FT_Disc::ramasse_miette_simple(), Convection_Diffusion_Concentration_Turbulent_FT_Disc::ramasse_miette_simple(), OctreeRoot_32_64< _SIZE_ >::rang_arete(), OctreeRoot_32_64< _SIZE_ >::rang_elem(), OctreeRoot_32_64< _SIZE_ >::rang_elem_depuis(), OctreeRoot_32_64< _SIZE_ >::rang_sommet(), IJK_Interfaces::readOn(), Champ_Fonc_MED::readOn(), Loi_Etat_rhoT_GR_QC::readOn(), Remove_elem::recreer_faces(), IJK_Interfaces::recursive_calcul_distance_chez_voisin(), Remaillage_FT::redistribuer_sommets(), Raffiner_Simplexes_32_64< _SIZE_ >::refine_domain(), Remaillage_FT::regulariser_courbure(), FT_Field::remailler_FT_Field(), Topologie_Maillage_FT::remailler_interface(), Cut_cell_FT_Disc::remove_dead_and_virtual_cells(), Remove_elem::remove_elem_(), Champ_front_contact_VEF::remplir_connect_bords(), Champ_P0_VDF::remplir_coord_noeuds(), Champ_Face_VDF_implementation::remplir_coord_noeuds(), Champ_P1NC_implementation::remplir_coord_noeuds(), Champ_Q1NC_implementation::remplir_coord_noeuds(), Connectivite_frontieres::remplir_faces_voisins(), Remove_elem::remplir_liste(), Op_Diff_EF::remplir_nu(), Op_Dift_EF_Q1::remplir_nu(), Op_Diff_PolyMAC_base::remplir_nu_ef(), Marching_Cubes::remplir_renum_virt_loc(), Ensemble_Lagrange_base::remplir_sommets_tmp(), Maillage_FT_Disc::remplir_structure(), Loi_Etat_GR_base::remplir_T(), Champ_front_MED::remplir_tab(), Domaine_Cl_EF::remplir_type_elem_Cl(), Ch_front_input_ALE::remplir_vit_som_bord_ALE(), Frontiere_32_64< _SIZE_ >::renum(), Marching_Cubes::renum_sommets_dist_loc(), Domaine_VF::renumeroter(), Transport_Interfaces_FT_Disc::RenumFa7(), Domaine_VDF::reordonner(), Scatter::reordonner_faces_de_joint(), Reordonner_faces_periodiques_32_64< _SIZE_ >::reordonner_faces_periodiques(), Reorienter_tetraedres_32_64< _SIZE_ >::reorienter(), Reorienter_triangles_32_64< _SIZE_ >::reorienter(), Maillage_FT_Disc::reprendre(), Navier_Stokes_FT_Disc::reprendre(), Transport_Interfaces_FT_Disc::reprendre(), Collision_Model_FT_base::reprendre(), Traitement_particulier_NS_canal::reprendre_stat(), EDO_Pression_th_VDF_Gaz_Parfait::resoudre(), EDO_Pression_th_VDF_Gaz_Reel::resoudre(), IJK_One_Dimensional_Subproblems_Interfaces_Fields::retrieve_interfacial_surface_quantity(), Viscosite_turbulente_k_omega::reynolds_stress(), Viscosite_turbulente_k_tau::reynolds_stress(), Viscosite_turbulente_sato::reynolds_stress(), Viscosite_turbulente_WIF::reynolds_stress(), Viscosite_turbulente_WIT::reynolds_stress(), Navier_Stokes_Fluide_Dilatable_Proto::rho_vitesse_impl(), Source_PDF_EF::rotate_imposed_velocity(), Transport_Interfaces_FT_Disc::sauvegarder(), Collision_Model_FT_base::sauvegarder(), FT_Field::sauvegarder_triangle(), Traitement_particulier_NS_canal::sauver_stat_canal(), Cut_cell_FT_Disc::set_coord(), Collision_Model_FT_base::set_LC_zones(), Champ_input_P0::setValue(), Champ_Input_Proto::setValueOnTab(), Traitement_particulier_NS_THI_VEF::sorties_globales(), Transport_Interfaces_FT_Disc::StockageFa7(), Topologie_Maillage_FT::suppression_interfaces(), Remaillage_FT::supprimer_doublons_facettes(), Remaillage_FT::supprimer_facettes_bord(), Remaillage_FT::supprimer_facettes_nulles(), Remaillage_FT::supprimer_petites_aretes(), Remaillage_FT_IJK::supprimer_petites_aretes(), Navier_Stokes_FT_Disc::swap_particles_eulerian_id_number(), Transport_Interfaces_FT_Disc::swap_particles_lagrangian_position_velocity(), Echange_impose_base::T_ext(), Echange_externe_impose_H::T_ext(), Eval_Dift_VDF_Face::tau_tan_impl(), Paroi_std_hyd_VDF::tau_tang(), Operateur_base::tester_contribuer_a_avec(), Echange_contact_VDF_FT_Disc::Ti_wall(), Champ_Face_VDF_implementation::trace(), Champ_P1iP1B_implementation::trace(), Champ_Elem_PolyMAC::trace(), Raccord_distant_homogene_32_64< _SIZE_ >::trace_elem_distant(), Frontiere_32_64< _SIZE_ >::trace_elem_local(), Raccord_distant_homogene_32_64< _SIZE_ >::trace_face_distant(), Frontiere_32_64< _SIZE_ >::trace_face_local(), Frontiere_32_64< _SIZE_ >::trace_som_local(), Remaillage_FT::traite_decollement(), Moyenne_volumique::traiter_champs(), Transformer_32_64< _SIZE_ >::transformer(), Convection_Diffusion_Temperature::transport_ibc(), Maillage_FT_Disc::transporter(), IJK_Interfaces::transporter_maillage_deformation(), IJK_Interfaces::transporter_maillage_remaillage(), IJK_Interfaces::transporter_maillage_rigide(), Maillage_FT_Disc::transporter_simple(), Tetraedriser::trianguler(), Tetraedriser_homogene::trianguler(), Tetraedriser_homogene_compact::trianguler(), Tetraedriser_homogene_fin::trianguler(), Tetraedriser_par_prisme::trianguler(), Trianguler::trianguler(), Trianguler_fin::trianguler(), Trianguler_H::trianguler(), Marching_Cubes::trier_les_noeuds(), Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_elem(), Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_face(), Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_face_sommets(), Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_gradU_elem(), Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_gradU_elem_P1(), Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_gradU_face(), Matrice_Sym::unsymmetrize_stencil(), Matrice_Sym::unsymmetrize_stencil_and_coefficients(), Cut_cell_FT_Disc::update(), Echange_contact_PolyMAC::update_coeffs(), Echange_contact_PolyMAC::update_delta(), Op_Diff_PolyMAC_Elem::update_delta_int(), Transport_Marqueur_FT::update_delta_v(), Eval_Diff_VDF::update_diffusivite(), Eval_Dift_Multiphase_VDF::update_diffusivite_turbulente(), Champ_Fonc_Interp::update_fields(), grad_Champ_Face_PolyMAC_P0::update_ge(), Op_Diff_DG_base::update_nu(), Op_Diff_PolyMAC_base::update_nu(), Maillage_FT_IJK::update_surfactant_apres_transport(), Maillage_FT_Disc::update_tableau_apres_transport(), Champ_Face_PolyMAC_P0::update_ve(), Transport_Interfaces_FT_Disc::uzawa(), Sortie_libre_Text_H_ext::val_ext(), Neumann_sortie_libre_Temp_H::val_ext(), Neumann_sortie_libre::val_ext(), Dirichlet::val_imp(), Entree_fluide_temperature_imposee_H::val_imp(), Temperature_imposee_paroi_H::val_imp(), Entree_fluide_T_h_imposee::val_imp(), Dirichlet::val_imp_au_temps(), Frontiere_ouverte_rho_u_impose::val_imp_au_temps(), Champ_implementation_P0::valeur_a_elem(), Ch_front_input_P1::valeur_au_temps_et_au_point(), Champ_Elem_DG::valeur_aux(), champ_init_canal_sinal::valeur_aux(), Init_par_partie::valeur_aux(), Tayl_Green::valeur_aux(), Champ_implementation_sommet::valeur_aux_bords(), Champ_implementation_P0::valeur_aux_centres_de_gravite(), Champ_base::valeur_aux_centres_de_gravite(), Champ_P1NC_implementation::valeur_aux_centres_de_gravite(), Champ_Fonc_Face_VDF::valeur_aux_compo(), Champ_base::valeur_aux_compo(), champ_init_canal_sinal::valeur_aux_compo(), Tayl_Green::valeur_aux_compo(), TRUSTChamp_Divers_generique< _TYPE_ >::valeur_aux_elems(), Champ_som_lu::valeur_aux_elems(), Champ_P1iP1B_implementation::valeur_aux_elems(), Champ_implementation_sommet::valeur_aux_elems(), Champ_Fonc_Face_PolyMAC::valeur_aux_elems(), Champ_Face_PolyMAC::valeur_aux_elems_(), Champ_implementation_sommet::valeur_aux_elems_compo(), Champ_P1NC_implementation::valeur_aux_elems_smooth(), Champ_Elem_PolyMAC::valeur_aux_faces(), Champ_base::valeur_aux_sommets(), Champ_base::valeur_aux_sommets_compo(), Champ_implementation_sommet::valeur_aux_sommets_compo_impl(), Champ_implementation_P0::valeur_aux_sommets_impl(), Champ_implementation_sommet::valeur_aux_sommets_impl(), Champ_implementation_Q1::value_interpolation(), Source_PDF_EF::verif_ajouter_contrib(), NettoieNoeuds_32_64< _SIZE_ >::verifie_noeuds(), Op_Diff_VEF_Anisotrope_Face::verifier(), Op_Diff_VEF_Face::verifier(), Cut_cell_FT_Disc::verifier_pas_de_doublons(), Cut_cell_FT_Disc::verifier_tableau_jamais_nul(), DebogFT::verifier_tableau_sommets(), Cut_cell_FT_Disc::verifier_taille_tableaux(), Cut_cell_FT_Disc::verifier_toujours_meme_signe_et_non_nul(), Cut_cell_FT_Disc::verifier_valide_permutation(), Transport_Interfaces_FT_Disc::verifprojete(), Parcours_interface::volume_barycentre_hexaedre(), Parcours_interface::volume_tetraedre(), Parcours_interface::volume_tetraedre_reference(), Domaine_PolyMAC_P0P1NC::W1(), and Domaine_PolyMAC::W2().
dimension_int()
template<typename _TYPE_ , typename _SIZE_ > int TRUSTTab< _TYPE_, _SIZE_ >::dimension_int (int d) const
Referenced by Frontiere_32_64< _SIZE_ >::add(), Domaine_32_64< _SIZE_ >::ajouter(), Polyedre_32_64< _SIZE_ >::ajouter_elements(), Domaine_VF::build_mc_face_mesh(), Polyedre_32_64< _SIZE_ >::calculer_centres_gravite(), Faces_32_64< _SIZE_ >::Calculer_centres_gravite(), Polyedre_32_64< _SIZE_ >::calculer_volumes(), OctreeRoot_32_64< _SIZE_ >::construire(), Polyedre_32_64< _SIZE_ >::contient(), Partitionneur_base_32_64< _SIZE_ >::corriger_multiperiodique(), Partitionneur_base_32_64< _SIZE_ >::corriger_sommets_bord(), TroisDto2D_32_64< _SIZE_ >::extraire_2D(), LireMED_32_64< _SIZE_ >::fill_frontieres(), Lata_2_Other::interpreter(), Maillage_FT_IJK::lire_maillage_ft_dans_lata(), Domaine_32_64< _SIZE_ >::merge_wo_vertices_with(), NettoieNoeuds_32_64< _SIZE_ >::nettoie(), OctreeRoot_32_64< _SIZE_ >::rang_arete(), Frontiere_32_64< _SIZE_ >::renum(), Reordonner_faces_periodiques_32_64< _SIZE_ >::renum_som_perio(), Octree_Double_32_64< _SIZE_ >::search_nodes_close_to(), and Frontiere_32_64< _SIZE_ >::trace_som_local().
nb_dim()
template<typename _TYPE_ , typename _SIZE_ > int TRUSTTab< _TYPE_, _SIZE_ >::nb_dim () const inline
References TRUSTArray< _TYPE_, _SIZE_ >::nb_dim_.
Referenced by Navier_Stokes_phase_field::_aff_donnee_P0(), Navier_Stokes_phase_field::_aff_donnee_P1(), Navier_Stokes_phase_field::_aff_donnee_P1Bulle(), Frontiere_32_64< _SIZE_ >::add(), Operateur_Conv_sensibility_VEF::add_diffusion_term(), Champ_Face_VDF::affecter(), Op_Dift_VDF_base::ajoute_terme_pour_axi_turb(), Iterateur_PolyMAC_Elem< _TYPE_ >::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Centre_EF_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_Muscl_New_VEF_Face::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Conv_Vort_VEF_Face::ajouter(), Op_Diff_VEF_Anisotrope_Face::ajouter(), Op_Diff_VEF_Face::ajouter(), Op_Diff_VEF_Face_Q1::ajouter(), Source_Trainee::ajouter(), Iterateur_Source_EF_Som< _TYPE_ >::ajouter(), Iterateur_Source_Elem< _TYPE_ >::ajouter(), Iterateur_Source_Face< _TYPE_ >::ajouter(), Iterateur_Source_VEF_Face< _TYPE_ >::ajouter(), Terme_Boussinesq_VEF_Face::ajouter(), Op_Diff_VEF_Face_Stab::ajouter_antidiffusion(), Op_Diff_PolyMAC_P0P1NC_Face::ajouter_blocs_ext(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_scalaire(), Op_Conv_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution(), Op_Diff_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Face_Stab::ajouter_contribution(), Iterateur_PolyMAC_Elem< _TYPE_ >::ajouter_contribution(), Op_Conv_RT_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face_Stab::ajouter_contribution_multi_scalaire(), Iterateur_PolyMAC_Elem< _TYPE_ >::ajouter_contribution_vitesse(), Operateur_Conv_sensibility_VEF::ajouter_conv_term(), Op_Diff_VEF_Face_Stab::ajouter_diffusion(), Operateur_Conv_sensibility_VEF::ajouter_Lsensibility_state_Amont(), Operateur_Conv_sensibility_VEF::ajouter_Lstate_sensibility_Amont(), Matrice_Morse::ajouter_multTab_(), Matrice_Morse_Sym::ajouter_multTab_(), Matrice_Diagonale::ajouter_multTab_(), Op_Diff_VEF_Face_Stab::ajouter_operateur_centre(), Op_Conv_ALE_VEF::ajouterALE(), Solveur_Masse_EF::appliquer_impl(), Masse_PolyMAC_Elem::appliquer_impl(), Masse_PolyMAC_Face::appliquer_impl(), Masse_VDF_Elem::appliquer_impl(), Simpler_Base::assembler_matrice_pression_implicite(), Op_Diff_VEF_base::associer(), Champ_front_contact_VEF::calcul_grads_locaux(), Champ_P1NC::calcul_y_plus_diphasique(), Champ_Face_VDF::calcul_y_plus_diphasique(), Source_Con_Phase_field::calculer_alpha_gradC_carre(), Source_Con_Phase_field::calculer_champ_fonc_c(), Op_Diff_VEF_Face_Stab::calculer_coefficients(), Simple::calculer_correction_en_vitesse(), Modele_turbulence_scal_Prandtl::calculer_diffusivite_turbulente(), Op_Dift_EF_Q1::calculer_dt_stab(), Iterateur_PolyMAC_Elem< _TYPE_ >::calculer_flux_bord(), Paroi_std_hyd_VDF_diphasique::calculer_hyd(), Paroi_std_hyd_VEF_diphasique::calculer_hyd(), Paroi_std_hyd_EF::calculer_hyd(), Op_Diff_VEF_Face_Stab::calculer_max(), Op_Diff_VEF_Face_Stab::calculer_min(), Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_vitesse_rho_mu(), Operateur_base::calculer_pour_post(), Transport_Marqueur_FT::calculer_proprietes_fluide_pos_particules(), Modele_turbulence_hyd_combinaison::calculer_viscosite_turbulente(), Discretisation_tools::cells_to_faces(), Scatter::Chercher_Correspondance(), Op_Diff_VEFP1NCP1B_Face::coeff_matrice_som(), Op_Diff_VEFP1NCP1B_Face::coeff_matrice_som_CL(), Op_Diff_VEFP1NCP1B_Face::coeff_matrice_som_perio(), Op_Diff_VEFP1NCP1B_Face::coeff_matrice_som_symetrie(), Op_Correlation::completer(), Convection_Diffusion_Temperature_FT_Disc::compute_divergence_free_velocity_extension(), Op_Conv_VEF_Face::contribue_au_second_membre(), Op_Diff_VEF_Face::contribue_au_second_membre(), Iterateur_PolyMAC_Elem< _TYPE_ >::contribuer_au_second_membre(), Champ_Fonc_base::data_a_sauvegarder(), Champ_Inc_base::data_a_sauvegarder(), Navier_Stokes_std_ALE::data_a_sauvegarder(), Op_Correlation::data_a_sauvegarder(), Op_Ecart_type::data_a_sauvegarder(), Op_Moyenne::data_a_sauvegarder(), Navier_Stokes_FT_Disc::derivee_en_temps_inco(), Op_PolyMAC_Elem::dimensionner(), Matrice_Morse::dimensionner(), Roue::dimensionner(), Op_Diff_PolyMAC_P0P1NC_Face::dimensionner_blocs_ext(), Navier_Stokes_phase_field::discretiser(), Source_Con_Phase_field::drhodc(), Format_Post_Lml::ecrire_champ_lml(), Format_Post_XYZ::ecrire_champ_xyz(), EcritureLectureSpecial::ecriture_special(), Domaine_Poly_base::equiv(), Parser_Eval::eval_fct(), Champ_P1NC_implementation::fixer_nb_valeurs_nodales(), Champ_Generique_Reduction_0D::get_champ(), ICoCo::ProblemTrio::getDirectAccessToUnknown(), Ch_front_input::getTemplate(), Ch_front_input_P1::getTemplate(), Op_Diff_VEFP1NCP1B_Face::gradient_som(), Op_Diff_VEFP1NCP1B_Face::gradient_som_CL(), Op_EF_base::impr(), Op_VEF_Face::impr(), Iterateur_PolyMAC_Elem< _TYPE_ >::impr(), Op_Conv_PolyMAC_base::impr(), Op_Diff_PolyMAC_Gen_base::impr(), Champ_front_var::initialiser(), Navier_Stokes_std::initTimeStep(), Champ_Fonc_Face_PolyMAC::interp_valeurs_elem(), Traitement_particulier_NS_CEG::lire(), Maillage_FT_IJK::lire_maillage_ft_dans_lata(), Matrice33::Matrice33(), Champ_front_calc_interne::mettre_a_jour(), Op_Diff_VEF_Face_Stab::modifie_pour_Cl(), Op_VEF_Face::modifier_flux(), Transport_turbulent_aire_interfaciale::modifier_mu(), Transport_turbulent_Prandtl::modifier_mu(), Transport_turbulent_SGDH::modifier_mu(), Op_Diff_Turbulent_PolyMAC_P0_Face::modifier_mu(), Viscosite_turbulente_base::modifier_mu(), Domaine_EF::modifier_pour_Cl(), Assembleur_P_EF::modifier_secmem(), Assembleur_P_PolyMAC::modifier_secmem(), Assembleur_P_VEF::modifier_secmem(), Assembleur_P_VEFPreP1B::modifier_secmem(), AssembleurPVDF_PF::modifier_secmem_vitesse_imposee(), Assembleur_P_VDF::modifier_secmem_vitesse_imposee(), Domaine_Poly_base::nu_dot(), Champ_Elem_DG::orthonormalize(), Operateur_base::ouvrir_fichier(), Postraitement_ft_lata::postprocess_field_values(), Paroi_std_hyd_VDF::preparer_calcul_hyd(), Champ_Fonc_reprise::readOn(), Op_Conv_ALE_VEF::remplir_fluent_ALEincluded(), Op_Diff_EF::remplir_nu(), Op_Dift_EF_Q1::remplir_nu(), Navier_Stokes_std_ALE::sauvegarder(), Convection_Diffusion_Fluide_Dilatable_Proto::Sauvegarder_WC(), Eval_Puiss_Th_QC_VEF_Face_View::set(), TRUST_2_PDI::share_TRUSTTab_dimensions(), Domaine_PolyMAC_P0P1NC::surf_elem_arete(), Champ_Elem_PolyMAC::trace(), Raccord_distant_homogene_32_64< _SIZE_ >::trace_face_distant(), Navier_Stokes_std::update_y_plus(), Frontiere_ouverte_rho_u_impose::val_imp_au_temps(), Champ_implementation_P0::valeur_a_elem(), Champ_implementation_P0::valeur_aux_centres_de_gravite(), Champ_P1NC_implementation::valeur_aux_centres_de_gravite(), Champ_Elem_DG::valeur_aux_elems(), Champ_Fonc_P1_DG::valeur_aux_elems(), Champ_som_lu::valeur_aux_elems(), Champ_P1iP1B_implementation::valeur_aux_elems(), Champ_P1NC_implementation::valeur_aux_elems(), Champ_Q1NC_implementation::valeur_aux_elems(), Champ_som_lu_VEF::valeur_aux_elems(), Champ_implementation_P0::valeur_aux_elems(), Champ_Fonc_Face_PolyMAC::valeur_aux_elems(), Champ_Face_PolyMAC::valeur_aux_elems_(), Champ_P1NC_implementation::valeur_aux_elems_smooth(), Champ_Elem_PolyMAC::valeur_aux_faces(), Champ_implementation_sommet::valeur_aux_sommets_compo_impl(), Champ_implementation_P0::valeur_aux_sommets_impl(), and Champ_implementation_Q1::value_interpolation().
from_tid_to_int()
template<typename _TYPE_ , typename _SIZE_ > void TRUSTTab< _TYPE_, _SIZE_ >::from_tid_to_int (TRUSTTab< int, int > & out) const inline
ref_as_big()
template<typename _TYPE_ , typename _SIZE_ > void TRUSTTab< _TYPE_, _SIZE_ >::ref_as_big (TRUSTTab< _TYPE_, trustIdType > & out) const inline
ref_as_small()
template<typename _TYPE_ , typename _SIZE_ > void TRUSTTab< _TYPE_, _SIZE_ >::ref_as_small (TRUSTTab< _TYPE_, int > & out) const inline
Referenced by Maillage_FT_IJK::lire_maillage_ft_dans_lata().
operator=() [1/3]
template<typename _TYPE_ , typename _SIZE_ > TRUSTTab & TRUSTTab< _TYPE_, _SIZE_ >::operator= (const TRUSTTab< _TYPE_, _SIZE_ > &) inline
Referenced by TRUSTTabFT< _TYPE_ >::operator=(), TRUSTTrav< _TYPE_ >::operator=(), and TRUSTTabFT< _TYPE_ >::TRUSTTabFT().
operator=() [2/3]
template<typename _TYPE_ , typename _SIZE_ > TRUSTTab & TRUSTTab< _TYPE_, _SIZE_ >::operator= (const TRUSTVect< _TYPE_, _SIZE_ > &) inline
operator=() [3/3]
template<typename _TYPE_ , typename _SIZE_ > TRUSTTab & TRUSTTab< _TYPE_, _SIZE_ >::operator= (_TYPE_ d) inline
operator()() [1/10]
template<typename _TYPE_ , typename _SIZE_ > _TYPE_ & TRUSTTab< _TYPE_, _SIZE_ >::operator() (const TRUSTArray< _SIZE_, int > & indice) inline
operator()() [2/10]
template<typename _TYPE_ , typename _SIZE_ > _TYPE_ TRUSTTab< _TYPE_, _SIZE_ >::operator() (const TRUSTArray< _SIZE_, int > & indice) const inline
operator[]() [1/2]
template<typename _TYPE_ , typename _SIZE_ > _TYPE_ & TRUSTTab< _TYPE_, _SIZE_ >::operator[] (_SIZE_ i) inline
operator[]() [2/2]
template<typename _TYPE_ , typename _SIZE_ > const _TYPE_ & TRUSTTab< _TYPE_, _SIZE_ >::operator[] (_SIZE_ i) const inline
operator()() [3/10]
template<typename _TYPE_ , typename _SIZE_ > _TYPE_ & TRUSTTab< _TYPE_, _SIZE_ >::operator() (_SIZE_ i) inline
operator()() [4/10]
template<typename _TYPE_ , typename _SIZE_ > const _TYPE_ & TRUSTTab< _TYPE_, _SIZE_ >::operator() (_SIZE_ i) const inline
operator()() [5/10]
template<typename _TYPE_ , typename _SIZE_ > _TYPE_ & TRUSTTab< _TYPE_, _SIZE_ >::operator() (_SIZE_ i1, int i2) inline
operator()() [6/10]
template<typename _TYPE_ , typename _SIZE_ > const _TYPE_ & TRUSTTab< _TYPE_, _SIZE_ >::operator() (_SIZE_ i1, int i2) const inline
operator()() [7/10]
template<typename _TYPE_ , typename _SIZE_ > _TYPE_ & TRUSTTab< _TYPE_, _SIZE_ >::operator() (_SIZE_ i1, int i2, int i3) inline
operator()() [8/10]
template<typename _TYPE_ , typename _SIZE_ > const _TYPE_ & TRUSTTab< _TYPE_, _SIZE_ >::operator() (_SIZE_ i1, int i2, int i3) const inline
operator()() [9/10]
template<typename _TYPE_ , typename _SIZE_ > _TYPE_ & TRUSTTab< _TYPE_, _SIZE_ >::operator() (_SIZE_ i1, int i2, int i3, int i4) inline
operator()() [10/10]
template<typename _TYPE_ , typename _SIZE_ > const _TYPE_ & TRUSTTab< _TYPE_, _SIZE_ >::operator() (_SIZE_ i1, int i2, int i3, int i4) const inline
ajoute_produit_tensoriel() [1/2]
template<typename _TYPE_ , typename _SIZE_ > template<typename _T_ > void TRUSTTab< _TYPE_, _SIZE_ >::ajoute_produit_tensoriel (_T_ alpha, const TRUSTTab< _T_, _SIZE_ > & , const TRUSTTab< _T_, _SIZE_ > &) inline
Referenced by Integrale_tps_produit_champs::ajoute_produit_tensoriel().
resoud_LU() [1/2]
template<typename _TYPE_ , typename _SIZE_ > template<typename _T_ > void TRUSTTab< _TYPE_, _SIZE_ >::resoud_LU (_SIZE_ , TRUSTArray< int, _SIZE_ > & , const TRUSTArray< _T_, _SIZE_ > & , TRUSTArray< _T_, _SIZE_ > &) inline
Referenced by Modele_Rayonnement_Milieu_Transparent::preparer_calcul().
inverse_LU() [1/2]
template<typename _TYPE_ , typename _SIZE_ > template<typename _T_ > bool TRUSTTab< _TYPE_, _SIZE_ >::inverse_LU (const TRUSTArray< _T_, _SIZE_ > & , TRUSTArray< _T_, _SIZE_ > &) inline
decomp_LU() [1/2]
template<typename _TYPE_ , typename _SIZE_ > template<typename _T_ > bool TRUSTTab< _TYPE_, _SIZE_ >::decomp_LU (_SIZE_ , TRUSTArray< int, _SIZE_ > & , TRUSTTab< _T_, _SIZE_ > &) inline
Referenced by Modele_Rayonnement_Milieu_Transparent::preparer_calcul().
max_du_u() [1/2]
template<typename _TYPE_ , typename _SIZE_ > template<typename _T_ > _T_ TRUSTTab< _TYPE_, _SIZE_ >::max_du_u (const TRUSTTab< _T_, _SIZE_ > &) inline
ajoute_produit_tensoriel() [2/2]
template<typename _TYPE_ , typename _SIZE_ > void TRUSTTab< _TYPE_, _SIZE_ >::ajoute_produit_tensoriel (int alpha, const TRUSTTab< int, _SIZE_ > & , const TRUSTTab< int, _SIZE_ > &) delete
resoud_LU() [2/2]
template<typename _TYPE_ , typename _SIZE_ > void TRUSTTab< _TYPE_, _SIZE_ >::resoud_LU (int , TRUSTArray< int, _SIZE_ > & , const TRUSTArray< int, _SIZE_ > & , TRUSTArray< int, _SIZE_ > &) delete
inverse_LU() [2/2]
template<typename _TYPE_ , typename _SIZE_ > int TRUSTTab< _TYPE_, _SIZE_ >::inverse_LU (const TRUSTArray< int, _SIZE_ > & , TRUSTArray< int, _SIZE_ > &) delete
decomp_LU() [2/2]
template<typename _TYPE_ , typename _SIZE_ > int TRUSTTab< _TYPE_, _SIZE_ >::decomp_LU (int , TRUSTArray< int, _SIZE_ > & , TRUSTTab< int, _SIZE_ > &) delete
max_du_u() [2/2]
template<typename _TYPE_ , typename _SIZE_ > int TRUSTTab< _TYPE_, _SIZE_ >::max_du_u (const TRUSTTab< int, _SIZE_ > &) delete
dimension_tot()
template<typename _TYPE_ , typename _SIZE_ > _SIZE_ TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot (int) const inline override virtual
Reimplemented from TRUSTArray< _TYPE_, _SIZE_ >.
Referenced by Champ_Face_PolyMAC::affecter_(), Champ_Face_PolyMAC_P0::affecter_(), Champ_Fonc_Face_PolyMAC::affecter_(), Champ_Elem_PolyMAC_P0P1NC::affecter_(), Integrale_tps_produit_champs::ajoute_produit_tensoriel(), Op_Dift_VDF_base::ajoute_terme_pour_axi_turb(), Op_Diff_K_Eps_QC_VEF_Face::ajouter(), Op_Diff_K_Eps_VEF_Face::ajouter(), Op_Diff_K_Omega_VEF_Face::ajouter(), Op_Diff_PolyMAC_Face::ajouter(), Terme_Source_Th_TdivU_VEF_Face::ajouter(), Source_Transport_Eps_VDF_Elem::ajouter_blocs(), Source_Transport_K_VDF_Elem::ajouter_blocs(), Source_Transport_K_Eps_VDF_Elem::ajouter_blocs(), Coalescence_bulles_1groupe_PolyMAC_P0::ajouter_blocs(), Rupture_bulles_1groupe_PolyMAC_P0::ajouter_blocs(), Diffusion_croisee_echelle_temp_taux_diss_turb_VDF::ajouter_blocs(), Diffusion_supplementaire_echelle_temp_turb_VDF::ajouter_blocs(), Terme_Boussinesq_PolyMAC_Face::ajouter_blocs(), Terme_Source_Qdm_Face_PolyMAC_P0P1NC::ajouter_blocs(), Op_Evanescence_Homogene_Elem_base::ajouter_blocs(), Op_Evanescence_Homogene_Face_base::ajouter_blocs(), Masse_DG_base::ajouter_blocs(), Masse_VDF_base::ajouter_blocs(), Masse_VDF_Face::ajouter_blocs(), Op_Div_PolyMAC_P0P1NC::ajouter_blocs_ext(), Masse_PolyMAC_Elem::ajouter_masse(), Solveur_Masse_base::ajouter_masse(), Masse_PolyMAC_Face::appliquer_impl(), Masse_PolyMAC_P0_Face::appliquer_impl(), Solveur_Masse_Elem_proto::appliquer_impl_proto(), SETS::assembler(), Simpler_Base::assembler_matrice_pression_implicite(), Source_PDF_EF::associer_pb(), Ch_front_input::buildSommetsFaces(), Op_Evanescence_Homogene_PolyMAC_P0_Face::calc_vort_elem(), Op_Evanescence_Homogene_Face_base::calc_vort_faces(), Loi_paroi_adaptative::calc_y_plus(), Loi_paroi_Ramstorfer::calc_y_plus(), Champ_P1NC::calcul_duidxj_paroi(), Convection_Diffusion_Temperature::calcul_indic_pena_global(), Transport_Interfaces_FT_Disc::calcul_indicatrice_faces(), Fluide_reel_base::calculate_fluid_properties_enthalpie(), Fluide_reel_base::calculate_fluid_properties_enthalpie_incompressible(), Masse_Multiphase::calculer_alpha_rho(), Energie_Multiphase::calculer_alpha_rho_e(), Energie_Multiphase::calculer_alpha_rho_h(), Energie_cinetique_turbulente::calculer_alpha_rho_k(), Energie_cinetique_turbulente_WIT::calculer_alpha_rho_k_WIT(), Faces_32_64< _SIZE_ >::Calculer_centres_gravite(), Equation_base::calculer_champ_conserve(), Transport_Interfaces_FT_Disc::calculer_distance_interface_faces(), Transport_Interfaces_FT_Disc::calculer_distance_interface_sommets(), Source_Con_Phase_field::calculer_div_alpha_gradC(), Fluide_base::calculer_e_int(), Milieu_composite::calculer_energie_interne(), Milieu_composite::calculer_enthalpie(), Milieu_composite::calculer_masse_volumique(), Source_Con_Phase_field::calculer_mutilde_demi(), Fluide_base::calculer_nu(), Taux_dissipation_turbulent::calculer_omega(), Fluide_Dilatable_base::calculer_pression_tot(), Echelle_temporelle_turbulente::calculer_tau(), Milieu_composite::calculer_temperature_multiphase(), Modele_turbulence_hyd_K_Eps::calculer_viscosite_turbulente(), Modele_turbulence_hyd_K_Eps_Bicephale::calculer_viscosite_turbulente(), Transport_Interfaces_FT_Disc::calculer_vmoy_composantes_connexes(), Discretisation_tools::cells_to_faces(), Discretisation_tools::cells_to_nodes(), Fluide_reel_base::check_unknown_range(), Loi_paroi_base::completer(), Fluide_Weakly_Compressible::completer(), Op_Correlation::completer(), Source_Transport_K_Omega_VEF_Face::compute_cross_diffusion(), Source_WC_Chaleur_VDF::compute_interpolate_gradP(), Source_WC_Chaleur_VEF::compute_interpolate_gradP(), OctreeRoot_32_64< _SIZE_ >::construire(), Scatter::construire_espace_virtuel_traduction(), Remailleur_Collision_FT_Thomas::construire_voisinage_sommet(), Op_Diff_K_Eps_VEF_Face::contribuer_a_avec(), Op_Diff_K_Omega_VEF_Face::contribuer_a_avec(), Paroi_hyd_base_EF::corriger_derivee_impl(), Paroi_hyd_base_VEF::corriger_derivee_impl(), Solveur_Masse_base::corriger_solution(), Fluide_base::creer_nu(), Convection_Diffusion_Espece_Multi_QC::derivee_en_temps_inco(), Solveur_Masse_base::dimensionner(), Masse_DG_base::dimensionner_blocs(), Masse_VDF_base::dimensionner_blocs(), Coalescence_bulles_1groupe_PolyMAC_P0::dimensionner_blocs(), Coalescence_bulles_2groupes_PolyMAC_P0::dimensionner_blocs(), Flux_2groupes_PolyMAC_P0::dimensionner_blocs(), Rupture_bulles_1groupe_PolyMAC_P0::dimensionner_blocs(), Rupture_bulles_2groupes_PolyMAC_P0::dimensionner_blocs(), Variation_rho::dimensionner_blocs(), Source_Diffusion_supplementaire_echelle_temp_turb::dimensionner_blocs(), Source_Dissipation_energie_cin_turb::dimensionner_blocs(), Source_Production_echelle_temp_taux_diss_turb::dimensionner_blocs(), Source_Production_energie_cin_turb::dimensionner_blocs(), Solveur_Masse_Elem_proto::dimensionner_blocs_proto(), Domaine_VDF::discretiser(), Domaine_Poly_base::discretiser_aretes(), Source_Con_Phase_field::div_kappa_grad(), Format_Post_Lata::ecrire_domaine_low_level(), Viscosite_turbulente_l_melange::eddy_viscosity(), Viscosite_turbulente_multiple::eddy_viscosity(), Source_Transport_K_Omega_VEF_Face_base::elem_to_face(), Viscosite_turbulente_multiple::eps(), Diffusion_croisee_echelle_temp_taux_diss_turb_VDF::face_to_elem(), Diffusion_supplementaire_echelle_temp_turb_VDF::face_to_elem(), Discretisation_tools::faces_to_cells(), Post_Processing_Hydrodynamic_Forces_Stokes::fill_Stokes_pressure_field(), Post_Processing_Hydrodynamic_Forces_Stokes::fill_Stokes_velocity_field(), Champ_P1NC_implementation::filtrer_L2(), Champ_P1NC_implementation::filtrer_resu(), Neumann::flux_impose(), Champ_Generique_Transformation::get_champ(), Champ_Generique_Interpolation::get_champ_with_calculer_champ_post(), ICoCo::ProblemTrio::getDirectAccessToUnknown(), Champ_Q1_EF::gradient(), Equation_base::Gradient_conjugue_diff_impl(), Domaine_Cl_EF::imposer_symetrie(), Equation_base::imprime_residu(), Transport_Interfaces_FT_Disc::init_particles_position_velocity(), Sonde::initialiser(), Echange_contact_PolyMAC::initialiser(), Echange_contact_VDF::initialiser(), QDM_Multiphase::initTimeStep(), Viscosite_turbulente_multiple::k_over_eps(), Source_Con_Phase_field::laplacien(), Domaine_PolyMAC_P0P1NC::M1(), Domaine_PolyMAC::M2(), Op_EF_base::marque_elem(), Source_Qdm_VDF_Phase_field::methode_1(), Source_Transport_Eps_Realisable_VEF_Face::mettre_a_jour(), Source_Transport_K_Realisable_VEF_Face::mettre_a_jour(), Source_Transport_K_Eps_Realisable_VEF_Face::mettre_a_jour(), Champ_Front_Fonction::mettre_a_jour(), Champ_Fonc_Tabule_Morceaux::mettre_a_jour(), Aire_interfaciale::mettre_a_jour(), QDM_Multiphase::mettre_a_jour(), Fluide_reel_base::mettre_a_jour(), Domaine_ALE::mettre_a_jour(), Interface_base::mettre_a_jour(), Milieu_composite::mettre_a_jour_tabs(), Op_Diff_Turbulent_PolyMAC_P0_Elem::modifier_mu(), Source_PDF_EF::multiply_coeff_volume(), Domaine_32_64< _SIZE_ >::nb_aretes_tot(), Domaine_32_64< _SIZE_ >::nb_elem_tot(), Remailleur_Collision_FT_Thomas::nb_elements_voisins_a_distance_plus_petite(), Faces_32_64< _SIZE_ >::nb_faces_tot(), Domaine_VF::nb_faces_tot(), Domaine_32_64< _SIZE_ >::nb_som_tot(), Discretisation_tools::nodes_to_cells(), Convection_Diffusion_Temperature::penalisation_L2(), Navier_Stokes_std::projeter(), Champ_input_P0::readOn(), Champ_Input_P0_Composite::readOn(), Champ_Fonc_reprise::readOn(), Diametre_bulles_constant::readOn(), Diametre_bulles_musig::readOn(), Polygone_32_64< _SIZE_ >::rebuild_index(), Polyedre_32_64< _SIZE_ >::remplir_Nodes_glob(), Marching_Cubes::remplir_renum_virt_loc(), Transport_Interfaces_FT_Disc::RenumFa7(), Fluide_Weakly_Compressible::Resoudre_EDO_PT(), Navier_Stokes_std_ALE::sauvegarder(), Convection_Diffusion_Fluide_Dilatable_Proto::Sauvegarder_WC(), Vecteur3::set(), Equation_base::set_residuals(), Champ_Input_Proto::setValueOnTab(), TRUST_2_PDI::share_TRUSTTab_dimensions(), Transport_Interfaces_FT_Disc::StockageFa7(), Navier_Stokes_FT_Disc::swap_particles_eulerian_id_number(), Eval_Dift_VDF_Face::tau_tan_impl(), Paroi_std_hyd_VDF::tau_tang(), Champ_Elem_PolyMAC::trace(), Remailleur_Collision_FT_Thomas::traite_RuptureCoalescenceInterfaces_Conservatif(), Remailleur_Collision_FT_Thomas::transport_volume_perdu_sur_element(), Remailleur_Collision_FT_Thomas::transport_volume_perdu_sur_sommet(), SETS::unknown_positivation(), Champ_Fonc_Interp::update_fields(), Op_Diff_DG_base::update_nu(), Op_Diff_PolyMAC_base::update_nu(), Op_Diff_PolyMAC_P0_base::update_nu(), Op_Diff_PolyMAC_P0P1NC_base::update_nu(), Navier_Stokes_std::update_y_plus(), Dirichlet::val_imp(), Champ_implementation_P0::valeur_a_elem(), Champ_implementation_P0::valeur_a_elem_compo(), Champ_Composite::valeur_aux(), TRUSTChamp_Divers_generique< _TYPE_ >::valeur_aux(), Champ_base::valeur_aux_bords(), Champ_P1NC_implementation::valeur_aux_centres_de_gravite(), Champ_Elem_DG::valeur_aux_elems(), Champ_Fonc_P1_DG::valeur_aux_elems(), Champ_P1iP1B_implementation::valeur_aux_elems(), Champ_P1NC_implementation::valeur_aux_elems(), Champ_implementation_sommet::valeur_aux_elems(), Champ_Fonc_Face_PolyMAC::valeur_aux_elems(), Champ_Face_PolyMAC::valeur_aux_elems_(), Champ_P1NC_implementation::valeur_aux_elems_smooth(), Champ_Elem_PolyMAC::valeur_aux_faces(), Champ_P1NC_implementation::valeur_aux_sommets(), Champ_implementation_P0::valeur_aux_sommets_impl(), Champ_implementation_sommet::valeur_aux_sommets_impl(), Champ_implementation_P1::value_interpolation(), Champ_implementation_Q1::value_interpolation(), Vecteur3::Vecteur3(), Domaine_PolyMAC_P0P1NC::W1(), Domaine_PolyMAC::W2(), VDF_discretisation::y_plus(), and PolyMAC_P0P1NC_discretisation::y_plus().
ref() [1/2]
template<typename _TYPE_ , typename _SIZE_ > virtual void TRUSTTab< _TYPE_, _SIZE_ >::ref (const TRUSTTab< _TYPE_, _SIZE_ > &) inline virtual
Referenced by Op_Conv_VEF_Face::ajouter(), Operateur_Conv_sensibility_VEF::ajouter_conv_term(), Source_Transport_VDF_Elem_base::ajouter_keps(), Op_Conv_ALE_VEF::ajouterALE(), Solveur_Masse_base::appliquer(), Masse_DG_base::appliquer_coef(), Masse_PolyMAC_base::appliquer_coef(), Eval_Conv_PolyMAC::associer(), Eval_Conv_VDF::associer(), Op_Grad_PolyMAC_Face::associer(), Op_Diff_VDF_Face_Axi_base::associer(), Op_Dift_VDF_Face_Axi_base::associer(), Op_Grad_VDF_Face_base::associer(), Eval_Puiss_Th_DG_Elem::associer_champs(), Eval_Puiss_Th_EF::associer_champs(), Eval_Puiss_Th_PolyMAC_Elem::associer_champs(), Eval_Source_C_PolyMAC_Elem::associer_champs(), Eval_Puiss_Th_VDF_Elem::associer_champs(), Eval_Source_C_VDF_Elem::associer_champs(), Eval_Puiss_Th_VEF_Face::associer_champs(), Eval_Source_C_VEF_Face::associer_champs(), Eval_Echange_Himp_VDF_Elem::associer_champs(), Eval_Dift_VDF::associer_diff_turb(), Force_Centrifuge_VDF_Face_Axi::associer_domaines(), Evaluateur_PolyMAC::associer_domaines(), Evaluateur_VDF::associer_domaines(), Eval_Puiss_Th_QC_EF::associer_puissance(), Eval_Puiss_Th_QC_VEF_Face::associer_puissance(), Eval_Puiss_Th_QC_VDF_Elem::associer_puissance(), Traitement_particulier_NS_canal::calcul_reynolds_tau(), Traitement_particulier_NS_THI_VEF::calcul_spectre(), Champ_Q1_EF::calcul_y_plus(), Champ_P1NC::calcul_y_plus(), Champ_Face_VDF::calcul_y_plus(), Champ_P1NC::calcul_y_plus_diphasique(), Champ_Face_VDF::calcul_y_plus_diphasique(), Eval_Puiss_Th_QC_VEF_Face::completer(), Eval_Source_C_VEF_Face::completer(), Evaluateur_Source_VEF_Face::completer(), Iterateur_VDF_Elem< _TYPE_ >::completer_(), Remove_elem::creer_faces(), Tetraedriser_homogene_compact::decoupe(), Tetraedriser_homogene_fin::decoupe(), Decouper_Bord_coincident::decouper_(), Discret_Thyd::diametre_hydraulique_face(), Eval_Conv_PolyMAC::Eval_Conv_PolyMAC(), Eval_Conv_VDF::Eval_Conv_VDF(), Evaluateur_PolyMAC::Evaluateur_PolyMAC(), Evaluateur_Source_VEF_Face::Evaluateur_Source_VEF_Face(), Evaluateur_VDF::Evaluateur_VDF(), ExtrudeParoi::extrude(), Extruder::extruder(), Extruder_en20::extruder(), Extruder_en3::extruder(), Extruder::extruder_hexa(), Champ_P1NC_implementation::filtrer_L2(), Loi_Etat_GR_base::initialiser(), Iterateur_PolyMAC_Elem< _TYPE_ >::Iterateur_PolyMAC_Elem(), Iterateur_VDF_Elem< _TYPE_ >::Iterateur_VDF_Elem(), Eval_Conv_PolyMAC::mettre_a_jour(), Eval_Conv_VDF::mettre_a_jour(), Eval_Dift_VDF_Face::mettre_a_jour(), Eval_Echange_Himp_VDF_Elem::mettre_a_jour(), Op_Dift_EF_base::mettre_a_jour(), Op_Dift_VEF_base::mettre_a_jour(), Op_Dift_VDF_Face_Axi_base::mettre_a_jour(), Raffiner_anisotrope_32_64< _SIZE_ >::raffiner_(), Remove_elem::recreer_faces(), Remove_elem::remove_elem_(), Table::remplir(), Champ_P0_VDF::remplir_coord_noeuds(), Champ_Face_VDF_implementation::remplir_coord_noeuds(), Champ_P1NC_implementation::remplir_coord_noeuds(), Champ_Q1NC_implementation::remplir_coord_noeuds(), Tetraedriser::trianguler(), Tetraedriser_homogene::trianguler(), Tetraedriser_homogene_compact::trianguler(), Tetraedriser_homogene_fin::trianguler(), Tetraedriser_par_prisme::trianguler(), Trianguler::trianguler(), Trianguler_fin::trianguler(), Trianguler_H::trianguler(), Refine_Mesh::update_boundary_faces(), Refine_Mesh::update_cells(), Refine_Mesh::update_connector_faces(), Eval_Diff_VDF::update_diffusivite(), Refine_Mesh::update_internal_frontier_faces(), Refine_Mesh::update_nodes(), and Champ_Inc_base::valeur_aux_bords().
ref_tab()
template<typename _TYPE_ , typename _SIZE_ > virtual void TRUSTTab< _TYPE_, _SIZE_ >::ref_tab (TRUSTTab< _TYPE_, _SIZE_ > & , _SIZE_ start_line = 0, _SIZE_ nb_lines = -1) inline virtual
Referenced by Champ_Inc_base::affecter_(), and Champ_Elem_DG::affecter_().
set_md_vector()
template<typename _TYPE_ , typename _SIZE_ > void TRUSTTab< _TYPE_, _SIZE_ >::set_md_vector (const MD_Vector &) inline override virtual
Reimplemented from TRUSTVect< _TYPE_, _SIZE_ >.
Referenced by Domaine_32_64< _SIZE_ >::ajouter(), Faces_32_64< _SIZE_ >::Calculer_centres_gravite(), Scatter::construire_espace_virtuel_traduction(), Scatter::construire_structures_paralleles(), Champ_Elem_PolyMAC_P0P1NC::init_auxiliary_variables(), Champ_Face_PolyMAC_P0P1NC::init_auxiliary_variables(), Champ_Face_PolyMAC_P0::init_auxiliary_variables(), Scatter::init_sequential_domain(), Debog_Pb::read_geometry_data(), Champ_Elem_PolyMAC_P0::reprendre(), Champ_Face_PolyMAC_P0::reprendre(), Solv_Gen::solve(), and Scatter::uninit_sequential_domain().
jump()
template<typename _TYPE_ , typename _SIZE_ > void TRUSTTab< _TYPE_, _SIZE_ >::jump (Entree &) inline override virtual
Reimplemented from TRUSTVect< _TYPE_, _SIZE_ >.
Referenced by Champ_Generique_Statistiques_base::lire_bidon(), Champ_Fonc_base::reprendre(), Champ_Inc_base::reprendre(), Modele_turbulence_scal_Fluctuation_Temperature::reprendre(), Modele_turbulence_scal_Fluctuation_Temperature_W::reprendre(), Postraitement::reprendre(), Operateurs_Statistique_tps::reprendre(), and Modele_turbulence_hyd_2_eq_base::reprendre_generique().
lit()
template<typename _TYPE_ , typename _SIZE_ > void TRUSTTab< _TYPE_, _SIZE_ >::lit (Entree & , bool resize_and_read = true) inline override virtual
Reimplemented from TRUSTVect< _TYPE_, _SIZE_ >.
Referenced by Domaine_VF::readOn(), Sous_domaine_VF::readOn(), Domaine_VDF::readOn(), Champ_Fonc_base::reprendre(), and Champ_Inc_base::reprendre().
ecrit()
template<typename _TYPE_ , typename _SIZE_ > void TRUSTTab< _TYPE_, _SIZE_ >::ecrit (Sortie &) const inline override virtual
Reimplemented from TRUSTVect< _TYPE_, _SIZE_ >.
Referenced by Domaine_Poly_base::ecrit(), Domaine_VF::printOn(), Sous_domaine_VF::printOn(), Domaine_VDF::printOn(), Champ_Fonc_base::sauvegarder(), and Champ_Inc_base::sauvegarder().
ref() [2/2]
template<typename _TYPE_ , typename _SIZE_ > void TRUSTTab< _TYPE_, _SIZE_ >::ref (const TRUSTVect< _TYPE_, _SIZE_ > &) inline override virtual
Reimplemented from TRUSTVect< _TYPE_, _SIZE_ >.
ref_data()
template<typename _TYPE_ , typename _SIZE_ > void TRUSTTab< _TYPE_, _SIZE_ >::ref_data (_TYPE_ * ptr, _SIZE_ size) inline override virtual
Construction de tableaux qui pointent vers des donnees existantes !!! Utiliser ref_data avec precaution
Reimplemented from TRUSTArray< _TYPE_, _SIZE_ >.
ref_array()
template<typename _TYPE_ , typename _SIZE_ > void TRUSTTab< _TYPE_, _SIZE_ >::ref_array (TRUSTArray< _TYPE_, _SIZE_ > & , _SIZE_ start = 0, _SIZE_ sz = -1) inline override virtual
Reimplemented from TRUSTArray< _TYPE_, _SIZE_ >.
Referenced by Solv_Gen::solve().
reset()
template<typename _TYPE_ , typename _SIZE_ > void TRUSTTab< _TYPE_, _SIZE_ >::reset () inline override virtual
Remet le tableau dans l'etat obtenu avec le constructeur par defaut (libere la memoire mais conserve le mode d'allocation memoire actuel)
Reimplemented from TRUSTArray< _TYPE_, _SIZE_ >.
Referenced by Terme_Boussinesq_Sensibility_VEFPreP1B_Face::ajouter(), Domaine_ALE::clear(), Op_Ecart_type::completer(), Solv_Externe::construit_renum(), Hexa_VEF::creer_facette_normales(), Tetra_VEF::creer_facette_normales(), Tri_VEF::creer_facette_normales(), ExtrudeParoi::extrude(), Extruder_en20::extruder(), Champ_P1NC_implementation::fixer_nb_valeurs_nodales(), Remailleur_Collision_FT_Thomas::initialiser_data(), Domaine_ALE::mettre_a_jour(), SSOR::prepare_(), Remove_elem::recreer_faces(), Operateurs_Statistique_tps::reprendre(), Faces_builder::reset(), Roue::supprimer_case(), and Moyenne_volumique::traiter_champs().
resize_tab()
template<typename _TYPE_ , typename _SIZE_ > void TRUSTTab< _TYPE_, _SIZE_ >::resize_tab (_SIZE_ n, RESIZE_OPTIONS opt = RESIZE_OPTIONS::COPY_INIT) inline override virtual
Reimplemented from TRUSTArray< _TYPE_, _SIZE_ >.
Referenced by Modele_Shih_Zhu_Lumley_VDF::Initialisation(), and Modele_Shih_Zhu_Lumley_VEF::Initialisation().
reshape() [1/3]
template<typename _TYPE_ , typename _SIZE_ > void TRUSTTab< _TYPE_, _SIZE_ >::reshape (_SIZE_ n1, int n2) inline
reshape() [2/3]
template<typename _TYPE_ , typename _SIZE_ > void TRUSTTab< _TYPE_, _SIZE_ >::reshape (_SIZE_ n1, int n2, int n3) inline
reshape() [3/3]
template<typename _TYPE_ , typename _SIZE_ > void TRUSTTab< _TYPE_, _SIZE_ >::reshape (_SIZE_ n1, int n2, int n3, int n4) inline
view_ro() [1/2]
template<typename _TYPE_ , typename _SIZE_ > template<int _SHAPE_ = 2, typename EXEC_SPACE = Kokkos::DefaultExecutionSpace> std::enable_if_t< is_default_exec_space< EXEC_SPACE >, ConstView< _TYPE_, _SHAPE_ > > TRUSTTab< _TYPE_, _SIZE_ >::view_ro () const inline
Referenced by Op_Conv_VEF_Face::ajouter(), Op_Div_VEFP1B_Elem::ajouter(), Terme_Boussinesq_VEF_Face::ajouter(), Terme_Boussinesq_VEFPreP1B_Face::ajouter(), Op_Diff_VEF_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Face::ajouter_cas_vectoriel(), Op_Diff_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Div_VEFP1B_Elem::ajouter_elem(), Op_Grad_VEF_P1B_Face::ajouter_elem(), Source_Masse_Fluide_Dilatable_VEF::ajouter_eq_espece(), Source_Masse_Fluide_Dilatable_VEF::ajouter_projection(), Op_Grad_VEF_P1B_Face::ajouter_som(), Op_Div_VEFP1B_Elem::ajouter_som(), Champ_P1NC::cal_rot_ordre1(), Champ_P1NC::calcul_critere_Q(), Champ_P1NC::calcul_duidxj_paroi(), Champ_P1NC::calcul_grad_U(), Champ_P1NC::calcul_S_barre(), Champ_P1NC::calcul_y_plus(), Loi_Etat_GP_base::calculer_alpha(), Op_Dift_VEF_base::calculer_borne_locale(), Elem_geom_base_32_64< _SIZE_ >::calculer_centres_gravite(), Terme_Source_Canal_perio_VEF_P1NC::calculer_debit(), Op_Dift_VEF_base::calculer_dt_stab(), Modele_turbulence_hyd_LES_base::calculer_energie_cinetique_turb(), Op_Grad_VEF_P1B_Face::calculer_flux_bords(), Paroi_std_hyd_VEF::calculer_hyd(), Paroi_negligeable_VEF::calculer_hyd(), Loi_Etat_rhoT_GP_QC::calculer_masse_volumique(), Loi_Etat_base::calculer_nu(), Modele_turbulence_hyd_LES_Wale_VEF::calculer_viscosite_turbulente(), Discretisation_tools::cells_to_faces(), Assembleur_P_VEFPreP1B::changer_base(), Champ_Generique_Transformation::get_champ(), Champ_Generique_Interpolation::get_champ_with_calculer_champ_post(), Domaine_VF::get_position(), Champ_Fonc_Tabule_P0_VEF::mettre_a_jour(), Assembleur_P_VEFPreP1B::modifier_secmem(), Assembleur_P_VEFPreP1B::modifier_secmem_elem(), Assembleur_P_VEFPreP1B::modifier_secmem_som(), Champ_P1NC::norme_H1(), Postraitement::postraiter_tableau(), Op_Conv_VEF_Face::remplir_fluent(), Navier_Stokes_Fluide_Dilatable_Proto::rho_vitesse_impl(), Eval_Puiss_Th_QC_VEF_Face_View::set(), Eval_Puiss_Th_VEF_Face_View::set(), Eval_Source_C_VEF_Face_View::set(), TRUSTChamp_Divers_generique< _TYPE_ >::valeur_aux(), Champ_implementation_P0::valeur_aux_centres_de_gravite(), Champ_P1NC_implementation::valeur_aux_centres_de_gravite(), TRUSTChamp_Divers_generique< _TYPE_ >::valeur_aux_elems(), Champ_P1iP1B_implementation::valeur_aux_elems(), Champ_P1NC_implementation::valeur_aux_elems(), Champ_P1NC_implementation::valeur_aux_sommets(), and Champ_implementation_P0::valeur_aux_sommets_impl().
view_ro() [2/2]
template<typename _TYPE_ , typename _SIZE_ > template<int _SHAPE_ = 2, typename EXEC_SPACE = Kokkos::DefaultExecutionSpace> std::enable_if_t< gpu_enabled_is_host_exec_space< EXEC_SPACE >, ConstHostView< _TYPE_, _SHAPE_ > > TRUSTTab< _TYPE_, _SIZE_ >::view_ro () const inline
view_wo() [1/2]
template<typename _TYPE_ , typename _SIZE_ > template<int _SHAPE_ = 2, typename EXEC_SPACE = Kokkos::DefaultExecutionSpace> std::enable_if_t< is_default_exec_space< EXEC_SPACE >, View< _TYPE_, _SHAPE_ > > TRUSTTab< _TYPE_, _SIZE_ >::view_wo () inline
Referenced by Op_Conv_VEF_Face::ajouter(), Terme_Boussinesq_VEFPreP1B_Face::ajouter(), Op_Diff_VEF_Face::ajouter_cas_vectoriel(), Op_Div_VEFP1B_Elem::ajouter_som(), Champ_P1NC::cal_rot_ordre1(), Champ_P1NC::calcul_grad_U(), Loi_Etat_GP_base::calculer_alpha(), Elem_geom_base_32_64< _SIZE_ >::calculer_centres_gravite(), Op_Grad_VEF_P1B_Face::calculer_flux_bords(), Paroi_std_hyd_VEF::calculer_hyd(), Loi_Etat_rhoT_GP_QC::calculer_masse_volumique(), Modele_turbulence_hyd_LES_Smago_VEF::calculer_viscosite_turbulente(), Champ_Generique_Transformation::get_champ(), Champ_Generique_Interpolation::get_champ_with_calculer_champ_post(), Domaine_VF::get_position(), Domaine_Cl_VEF::imposer_cond_lim(), Champ_Fonc_Tabule_P0_VEF::mettre_a_jour(), Taux_cisaillement_P0_VEF::mettre_a_jour(), Op_Grad_VEF_P1B_Face::modifier_grad_pour_Cl(), Assembleur_P_VEFPreP1B::modifier_secmem(), Postraitement::postraiter_tableau(), Navier_Stokes_Fluide_Dilatable_Proto::rho_vitesse_impl(), Champ_implementation_P0::valeur_aux_centres_de_gravite(), Champ_base::valeur_aux_centres_de_gravite(), Champ_P1NC_implementation::valeur_aux_centres_de_gravite(), and Champ_P1NC_implementation::valeur_aux_elems().
view_wo() [2/2]
template<typename _TYPE_ , typename _SIZE_ > template<int _SHAPE_ = 2, typename EXEC_SPACE = Kokkos::DefaultExecutionSpace> std::enable_if_t< gpu_enabled_is_host_exec_space< EXEC_SPACE >, HostView< _TYPE_, _SHAPE_ > > TRUSTTab< _TYPE_, _SIZE_ >::view_wo () inline
view_rw() [1/2]
template<typename _TYPE_ , typename _SIZE_ > template<int _SHAPE_ = 2, typename EXEC_SPACE = Kokkos::DefaultExecutionSpace> std::enable_if_t< is_default_exec_space< EXEC_SPACE >, View< _TYPE_, _SHAPE_ > > TRUSTTab< _TYPE_, _SIZE_ >::view_rw () inline
Referenced by Op_Conv_VEF_Face::ajouter(), Terme_Source_Canal_perio_VEF_P1NC::ajouter(), Terme_Boussinesq_VEF_Face::ajouter(), Terme_Boussinesq_VEFPreP1B_Face::ajouter(), Source_QC_Chaleur::ajouter_(), Op_Diff_VEF_Face::ajouter_cas_vectoriel(), Op_Div_VEFP1B_Elem::ajouter_elem(), Op_Grad_VEF_P1B_Face::ajouter_elem(), Source_Masse_Fluide_Dilatable_VEF::ajouter_eq_espece(), Source_Fluide_Dilatable_VEF_Proto::ajouter_impl(), Source_Masse_Fluide_Dilatable_VEF::ajouter_projection(), Op_Grad_VEF_P1B_Face::ajouter_som(), Masse_VEF_P1NC::appliquer_impl(), Champ_P1NC::calcul_duidxj_paroi(), Discretisation_tools::cells_to_faces(), Domaine_Cl_VEF::imposer_cond_lim(), Op_VEF_Face::modifier_flux(), Op_Grad_VEF_P1B_Face::modifier_grad_pour_Cl(), TRUSTChamp_Divers_generique< _TYPE_ >::valeur_aux(), TRUSTChamp_Divers_generique< _TYPE_ >::valeur_aux_elems(), Champ_P1iP1B_implementation::valeur_aux_elems(), Champ_P1iP1B_implementation::valeur_aux_sommets(), Champ_P1NC_implementation::valeur_aux_sommets(), and Champ_implementation_P0::valeur_aux_sommets_impl().
view_rw() [2/2]
template<typename _TYPE_ , typename _SIZE_ > template<int _SHAPE_ = 2, typename EXEC_SPACE = Kokkos::DefaultExecutionSpace> std::enable_if_t< gpu_enabled_is_host_exec_space< EXEC_SPACE >, HostView< _TYPE_, _SHAPE_ > > TRUSTTab< _TYPE_, _SIZE_ >::view_rw () inline
Friends And Related Function Documentation
TRUSTTab
template<typename _TYPE_ , typename _SIZE_ > template<typename _TYPE2_ , typename _SIZE2_ > friend class TRUSTTab friend
Referenced by TRUSTTab< _TYPE_, _SIZE_ >::duplique().