TrioCFD: Modele_turbulence_hyd_LES_Fst_sel_VEF Class Reference
Modele_turbulence_hyd_LES_Fst_sel_VEF Class Reference
#include <Modele_turbulence_hyd_LES_Fst_sel_VEF.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Modele_turbulence_hyd_LES_Fst_VEF
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Modele_turbulence_hyd_LES_base
const Type_info * get_info () const override
void imprimer (Sortie &is) const override
int preparer_calcul () override
int reprendre (Entree &is) override
const Type_info * get_info () const override
void imprimer (Sortie &) const override
int reprendre (Entree &is) override
Public Member Functions inherited from Modele_turbulence_hyd_base
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Type_info * get_info () const override
virtual void imprimer (Sortie &) const
void lire_distance_paroi ()
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual int preparer_calcul ()
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Modele_turbulence_hyd_LES_Fst_VEF
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
maille fonction de structure selectif modifie en VEF La modification concerne l angle de coupure : il depend du pas du maillage Le calcul de la fonction de structure se fait comme dans Modele_turbulence_hyd_LES_1elt_VEF
.SECTION voir aussi Modele_turbulence_hyd_LES_1elt_VEF
Constructor & Destructor Documentation
~Modele_turbulence_hyd_LES_Fst_sel_VEF()
Modele_turbulence_hyd_LES_Fst_sel_VEF::~Modele_turbulence_hyd_LES_Fst_sel_VEF ()
Modele_turbulence_hyd_LES_Fst_sel_VEF()
Modele_turbulence_hyd_LES_Fst_sel_VEF::Modele_turbulence_hyd_LES_Fst_sel_VEF ()
References Modele_turbulence_hyd_LES_Fst_VEF::C1_.
Member Function Documentation
cree_instance()
Objet_U * Modele_turbulence_hyd_LES_Fst_sel_VEF::cree_instance () static
taille_memoire()
unsigned Modele_turbulence_hyd_LES_Fst_sel_VEF::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Modele_turbulence_hyd_LES_Fst_sel_VEF::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Modele_turbulence_hyd_LES_Fst_sel_VEF::info () static
get_info()
const Type_info * Modele_turbulence_hyd_LES_Fst_sel_VEF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Modele_turbulence_hyd_LES_VEF_base.
self_cast() [1/2]
Modele_turbulence_hyd_LES_Fst_sel_VEF & Modele_turbulence_hyd_LES_Fst_sel_VEF::self_cast (Objet_U & r) static
self_cast() [2/2]
const Modele_turbulence_hyd_LES_Fst_sel_VEF & Modele_turbulence_hyd_LES_Fst_sel_VEF::self_cast (const Objet_U & r) static
printOn()
Sortie & Modele_turbulence_hyd_LES_Fst_sel_VEF::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Modele_turbulence_hyd_LES_VEF_base.
References Objet_U::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Modele_turbulence_hyd_LES_Fst_sel_VEF::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Modele_turbulence_hyd_LES_VEF_base.
References Modele_turbulence_hyd_LES_Fst_VEF::readOn().
a_pour_Champ_Fonc()
int Modele_turbulence_hyd_LES_Fst_sel_VEF::a_pour_Champ_Fonc (const Motcle & mot, TRUST_Ref< Champ_base * > & ch_ref) const
References Modele_turbulence_hyd_0_eq_base::energie_cinetique_turb_, Modele_turbulence_hyd_base::la_viscosite_turbulente_, la_vorticite_, Motcles::search(), and TRUST_Deriv< _CLASSE_ >::valeur().
discretiser()
void Modele_turbulence_hyd_LES_Fst_sel_VEF::discretiser () override virtual
Discretise le modele de turbulence.
Reimplemented from Modele_turbulence_hyd_0_eq_base.
References Objet_U::dimension, Modele_turbulence_hyd_0_eq_base::discretiser(), Process::exit(), la_vorticite_, Modele_turbulence_hyd_base::mon_equation_, and VEF_discretisation::vorticite().
calculer_racine()
void Modele_turbulence_hyd_LES_Fst_sel_VEF::calculer_racine () override virtual
Reimplemented from Modele_turbulence_hyd_LES_Fst_VEF.
References Modele_turbulence_hyd_LES_Fst_VEF::calculer_racine(), and cutoff().
cutoff()
void Modele_turbulence_hyd_LES_Fst_sel_VEF::cutoff () protected
References TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_VF::elem_faces(), Domaine_VF::face_voisins(), Modele_turbulence_hyd_LES_base::l_, la_vorticite_, Modele_turbulence_hyd_0_eq_base::le_dom_VF_, Champ_Fonc_base::mettre_a_jour(), Modele_turbulence_hyd_base::mon_equation_, Domaine_dis_base::nb_elem(), Modele_turbulence_hyd_LES_Fst_VEF::Racine_, Champ_base::temps(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), and Domaine_VF::xp().
Referenced by calculer_racine().
Member Data Documentation
info_obj
const Type_info Modele_turbulence_hyd_LES_Fst_sel_VEF::info_obj static
la_vorticite_
TRUST_Deriv< Champ_Fonc_base > Modele_turbulence_hyd_LES_Fst_sel_VEF::la_vorticite_ protected
Referenced by a_pour_Champ_Fonc(), cutoff(), and discretiser().