TrioCFD: Modele_turbulence_hyd_LES_SMAGO_DYN_VDF Class Reference
Modele_turbulence_hyd_LES_SMAGO_DYN_VDF Class Reference
#include <Modele_turbulence_hyd_LES_SMAGO_DYN_VDF.h>
Public Member Functions
const Type_info * get_info () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
int preparer_calcul () override
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Modele_turbulence_hyd_LES_base
const Type_info * get_info () const override
void imprimer (Sortie &is) const override
int preparer_calcul () override
int reprendre (Entree &is) override
const Type_info * get_info () const override
void imprimer (Sortie &) const override
int reprendre (Entree &is) override
Public Member Functions inherited from Modele_turbulence_hyd_base
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Type_info * get_info () const override
virtual void imprimer (Sortie &) const
void lire_distance_paroi ()
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual int preparer_calcul ()
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Modele_turbulence_hyd_LES_SMAGO_DYN_VDF()
Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::Modele_turbulence_hyd_LES_SMAGO_DYN_VDF ()
~Modele_turbulence_hyd_LES_SMAGO_DYN_VDF()
Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::~Modele_turbulence_hyd_LES_SMAGO_DYN_VDF ()
Member Function Documentation
cree_instance()
Objet_U * Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::cree_instance () static
taille_memoire()
unsigned Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::taille_memoire () const override virtual
Reimplemented from Modele_turbulence_hyd_LES_Smago_VDF.
duplique()
int Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::duplique () const override virtual
Reimplemented from Modele_turbulence_hyd_LES_Smago_VDF.
info()
const Type_info * Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::info () static
get_info()
const Type_info * Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Modele_turbulence_hyd_LES_Smago_VDF.
self_cast() [1/2]
Modele_turbulence_hyd_LES_SMAGO_DYN_VDF & Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::self_cast (Objet_U & r) static
self_cast() [2/2]
const Modele_turbulence_hyd_LES_SMAGO_DYN_VDF & Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::self_cast (const Objet_U & r) static
printOn()
Sortie & Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Modele_turbulence_hyd_LES_Smago_VDF.
References Objet_U::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Modele_turbulence_hyd_LES_Smago_VDF.
References Modele_turbulence_hyd_LES_Smago_VDF::readOn().
set_param()
void Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::set_param (Param & param) override virtual
Reimplemented from Modele_turbulence_hyd_LES_Smago_VDF.
References Param::ajouter_non_std(), Param::REQUIRED, and Modele_turbulence_hyd_LES_Smago_VDF::set_param().
lire_motcle_non_standard()
int Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
< liste stockant tous les noms de frontiere du domaine
Reimplemented from Modele_turbulence_hyd_base.
References calc_elem_elem(), calcul_tableaux_correspondance(), compt_c_, corresp_c_, Process::exit(), Modele_turbulence_hyd_base::lire_motcle_non_standard(), methode_stabilise_, N_c_, Objet_U::que_suis_je(), and Motcles::search().
associer()
void Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::associer (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis) override virtual
Reimplemented from Modele_turbulence_hyd_0_eq_base.
References Champs_compris_T< FIELD_TYPE >::ajoute_champ(), Modele_turbulence_hyd_0_eq_base::associer(), Champ_Fonc_base::associer_domaine_dis_base(), Modele_turbulence_hyd_base::champs_compris_, Champ_base::changer_temps(), coeff_field_, Field_base::fixer_nb_comp(), Champ_Fonc_P0_base::fixer_nb_valeurs_nodales(), Field_base::fixer_unite(), Modele_turbulence_hyd_0_eq_base::le_dom_VF_, Field_base::nommer(), Objet_U_ptr::typer(), TRUST_Deriv< _CLASSE_ >::valeur(), and TRUST_Ref< _CLASSE_ >::valeur().
mettre_a_jour()
void Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::mettre_a_jour (double temps) override virtual
Reimplemented from Modele_turbulence_hyd_0_eq_base.
References Statistiques::begin_count(), calculer_cell_cent_vel(), calculer_energie_cinetique_turb(), calculer_filter_field(), Turbulence_paroi_base::calculer_hyd(), calculer_length_scale(), calculer_Lij(), calculer_Mij(), calculer_model_coefficient(), calculer_S_norme(), calculer_Sij(), calculer_Sij_vel_filt(), calculer_viscosite_turbulente(), cell_cent_vel_, Champ_base::changer_temps(), coeff_field_, controler_grandeurs_turbulentes(), Domaine_32_64< _SIZE_ >::creer_tableau_elements(), Objet_U::dimension, Domaine_dis_base::domaine(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Statistiques::end_count(), Modele_turbulence_hyd_0_eq_base::energie_cinetique_turbulente(), Modele_turbulence_hyd_base::la_viscosite_turbulente_, Modele_turbulence_hyd_0_eq_base::le_dom_Cl_, Modele_turbulence_hyd_0_eq_base::le_dom_VF_, Modele_turbulence_hyd_base::limiter_viscosite_turbulente(), Modele_turbulence_hyd_base::loipar_, Modele_turbulence_hyd_base::mon_equation_, Domaine_32_64< _SIZE_ >::nb_elem_tot(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), and Debog::verifier().
Referenced by preparer_calcul().
preparer_calcul()
int Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::preparer_calcul () override virtual
Prepare le calcul.
Initialise la loi de paroi. Remplit le champ wall_length en cas de post traitemetn de la distance_paroi
Returns
(int) code de retour de Turbulence_paroi::init_lois_paroi()
Reimplemented from Modele_turbulence_hyd_LES_base.
References mettre_a_jour(), and Modele_turbulence_hyd_LES_base::preparer_calcul().
calculer_length_scale()
void Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calculer_length_scale (DoubleVect & l, const Domaine_VDF & domaine_VDF) static
References Domaine_VDF::dim_elem(), Objet_U::dimension, Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), Domaine_32_64< _SIZE_ >::nb_elem_tot(), and Domaine_VDF::orientation().
Referenced by Modele_turbulence_scal_LES_dyn_VDF::calculer_diffusivite_turbulente(), mettre_a_jour(), and stabilise_moyenne_euler_lagrange().
calculer_cell_cent_vel()
void Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calculer_cell_cent_vel (DoubleTab & cell_cent_vel, const Domaine_VDF & domaine_VDF, Champ_Inc_base & inco) static
References Objet_U::dimension, Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), Domaine_32_64< _SIZE_ >::nb_elem_tot(), and Champ_Inc_base::valeurs().
Referenced by Modele_turbulence_scal_LES_dyn_VDF::calculer_diffusivite_turbulente(), and mettre_a_jour().
calculer_filter_field()
void Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calculer_filter_field (const DoubleTab & in_vel, DoubleTab & out_vel, const Domaine_VDF & domaine_VDF) static
References Objet_U::dimension, Domaine_dis_base::domaine(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_VF::elem_faces(), Domaine_VF::face_voisins(), and Domaine_32_64< _SIZE_ >::nb_elem().
Referenced by Modele_turbulence_scal_LES_dyn_VDF::calculer_diffusivite_turbulente(), Modele_turbulence_scal_LES_dyn_VDF::calculer_Lj(), Modele_turbulence_scal_LES_dyn_VDF::calculer_Mj(), and mettre_a_jour().
calculer_Sij()
void Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calculer_Sij (DoubleTab & Sij, const Domaine_VDF & domaine_VDF, const Domaine_Cl_VDF & domaine_Cl_VDF, Champ_Inc_base & inco) static
References Champ_Face_VDF::calcul_duidxj(), Objet_U::dimension, TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Domaine_dis_base::nb_elem(), Domaine_dis_base::nb_elem_tot(), and Champ_Inc_base::valeurs().
Referenced by Modele_turbulence_scal_LES_dyn_VDF::calculer_diffusivite_turbulente(), and mettre_a_jour().
calculer_Sij_vel_filt()
void Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calculer_Sij_vel_filt (const DoubleTab & in_vel, DoubleTab & out_vel, const Domaine_VDF & domaine_VDF) static
References Domaine_VDF::dim_elem(), Objet_U::dimension, Domaine_dis_base::domaine(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_VF::elem_faces(), Domaine_VF::face_voisins(), and Domaine_32_64< _SIZE_ >::nb_elem().
Referenced by Modele_turbulence_scal_LES_dyn_VDF::calculer_diffusivite_turbulente(), and mettre_a_jour().
calculer_S_norme()
void Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calculer_S_norme (const DoubleTab & Sij, DoubleVect & S_norme, int nb_elem_tot) static
References Objet_U::dimension.
Referenced by Modele_turbulence_scal_LES_dyn_VDF::calculer_diffusivite_turbulente(), calculer_Mij(), and mettre_a_jour().
interpole()
void Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::interpole (const IntVect & num, const DoubleVect & dist, const DoubleVect & val, double & val_int) static
Referenced by stabilise_moyenne_euler_lagrange().
calculer_filter_tensor()
void Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calculer_filter_tensor (DoubleTab & in_vel) protected
References Objet_U::dimension, Domaine_dis_base::domaine(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_VF::elem_faces(), Domaine_VF::face_voisins(), Modele_turbulence_hyd_0_eq_base::le_dom_VF_, Domaine_32_64< _SIZE_ >::nb_elem(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by calculer_Lij(), and calculer_Mij().
calculer_Lij()
void Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calculer_Lij (const DoubleTab & cell_cent_vel, const DoubleTab & filt_vel, DoubleTab & Lij) protected
References calculer_filter_tensor(), Objet_U::dimension, Domaine_dis_base::domaine(), Modele_turbulence_hyd_0_eq_base::le_dom_VF_, Domaine_32_64< _SIZE_ >::nb_elem_tot(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by mettre_a_jour().
calculer_Mij()
void Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calculer_Mij (const DoubleTab & Sij_grid_scale, const DoubleTab & Sij_test_scale, const DoubleVect & l, DoubleTab & Mij) protected
References calculer_filter_tensor(), calculer_S_norme(), Objet_U::dimension, Domaine_dis_base::domaine(), Modele_turbulence_hyd_0_eq_base::le_dom_VF_, Domaine_32_64< _SIZE_ >::nb_elem_tot(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by mettre_a_jour().
calculer_model_coefficient()
void Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calculer_model_coefficient (const DoubleTab & Lij, const DoubleTab & Mij) protected
References coeff_field_, Domaine_32_64< _SIZE_ >::creer_tableau_elements(), Objet_U::dimension, Domaine_dis_base::domaine(), Modele_turbulence_hyd_0_eq_base::le_dom_VF_, Domaine_32_64< _SIZE_ >::nb_elem_tot(), stabilise_moyenne(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), and Debog::verifier().
Referenced by mettre_a_jour().
calculer_viscosite_turbulente() [1/2]
Champ_Fonc_base & Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calculer_viscosite_turbulente (const DoubleVect & SMA_barre, const DoubleVect & l) protected
References Champ_base::changer_temps(), coeff_field_, Domaine_dis_base::domaine(), Process::exit(), Modele_turbulence_hyd_base::la_viscosite_turbulente_, Modele_turbulence_hyd_0_eq_base::le_dom_VF_, Modele_turbulence_hyd_base::mon_equation_, Domaine_32_64< _SIZE_ >::nb_elem(), TRUSTVect< _TYPE_, _SIZE_ >::size(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), and Debog::verifier().
calculer_viscosite_turbulente() [2/2]
Champ_Fonc_base & Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calculer_viscosite_turbulente () override protected virtual
Reimplemented from Modele_turbulence_hyd_LES_Smago_VDF.
References Modele_turbulence_hyd_base::la_viscosite_turbulente_.
Referenced by mettre_a_jour().
calculer_energie_cinetique_turb() [1/2]
void Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calculer_energie_cinetique_turb () override protected virtual
Reimplemented from Modele_turbulence_hyd_LES_base.
Referenced by mettre_a_jour().
calculer_energie_cinetique_turb() [2/2]
Champ_Fonc_base & Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calculer_energie_cinetique_turb (const DoubleVect & SMA_barre, const DoubleVect & l) protected
References Champ_base::changer_temps(), coeff_field_, Domaine_dis_base::domaine(), Modele_turbulence_hyd_0_eq_base::energie_cinetique_turb_, Modele_turbulence_hyd_0_eq_base::le_dom_VF_, Modele_turbulence_hyd_base::mon_equation_, Domaine_32_64< _SIZE_ >::nb_elem_tot(), TRUST_Ref< _CLASSE_ >::valeur(), and Champ_Don_base::valeurs().
controler_grandeurs_turbulentes()
void Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::controler_grandeurs_turbulentes () protected
References Domaine_dis_base::domaine(), Modele_turbulence_hyd_0_eq_base::energie_cinetique_turb_, Modele_turbulence_hyd_base::la_viscosite_turbulente_, Modele_turbulence_hyd_0_eq_base::le_dom_VF_, Domaine_32_64< _SIZE_ >::nb_elem_tot(), TRUST_Ref< _CLASSE_ >::valeur(), and Champ_Don_base::valeurs().
Referenced by mettre_a_jour().
stabilise_moyenne()
void Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::stabilise_moyenne (const DoubleTab & haut, const DoubleTab & bas) protected
References Process::exit(), methode_stabilise_, stabilise_moyenne_6_points(), stabilise_moyenne_euler_lagrange(), and stabilise_moyenne_plans_paralleles().
Referenced by calculer_model_coefficient().
stabilise_moyenne_6_points()
void Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::stabilise_moyenne_6_points (const DoubleTab & haut, const DoubleTab & bas) protected
References coeff_field_, Objet_U::dimension, Domaine_dis_base::domaine(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_VF::elem_faces(), Domaine_VF::face_voisins(), Modele_turbulence_hyd_0_eq_base::le_dom_VF_, Domaine_32_64< _SIZE_ >::nb_elem(), Domaine_32_64< _SIZE_ >::nb_elem_tot(), TRUST_Ref< _CLASSE_ >::valeur(), and Champ_Don_base::valeurs().
Referenced by stabilise_moyenne().
stabilise_moyenne_plans_paralleles()
void Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::stabilise_moyenne_plans_paralleles (const DoubleTab & haut, const DoubleTab & bas) protected
References Process::check_int_overflow(), coeff_field_, compt_c_, corresp_c_, Domaine_dis_base::domaine(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Modele_turbulence_hyd_0_eq_base::le_dom_VF_, Process::mp_sum(), N_c_, Domaine_32_64< _SIZE_ >::nb_elem(), Domaine_32_64< _SIZE_ >::nb_elem_tot(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), and Debog::verifier().
Referenced by stabilise_moyenne().
stabilise_moyenne_euler_lagrange()
void Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::stabilise_moyenne_euler_lagrange (const DoubleTab & haut, const DoubleTab & bas) protected
References calcul_voisins(), calculer_length_scale(), coeff_field_, Domaine_32_64< _SIZE_ >::creer_tableau_elements(), Domaine_dis_base::domaine(), interpole(), Modele_turbulence_hyd_0_eq_base::le_dom_VF_, methode_stabilise_, Modele_turbulence_hyd_base::mon_equation_, TRUSTVect< _TYPE_, _SIZE_ >::size_totale(), TRUST_Ref< _CLASSE_ >::valeur(), and Champ_Don_base::valeurs().
Referenced by stabilise_moyenne().
calcul_voisins()
void Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calcul_voisins (const int element_number, IntVect & num, DoubleVect & dist) protected
References cell_cent_vel_, elem_elem_, Process::exit(), Modele_turbulence_hyd_0_eq_base::le_dom_VF_, Modele_turbulence_hyd_base::mon_equation_, TRUST_Ref< _CLASSE_ >::valeur(), and Domaine_VF::xp().
Referenced by stabilise_moyenne_euler_lagrange().
calc_elem_elem()
void Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calc_elem_elem () protected
References Domaine_dis_base::domaine(), elem_elem_, Domaine_VF::elem_faces(), Domaine_VF::face_voisins(), Modele_turbulence_hyd_0_eq_base::le_dom_VF_, Domaine_32_64< _SIZE_ >::nb_elem_tot(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by lire_motcle_non_standard().
calcul_tableaux_correspondance()
void Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calcul_tableaux_correspondance (int & N_c, IntVect & compt_c, IntVect & corresp_c) protected
References Domaine_32_64< _SIZE_ >::creer_tableau_elements(), Domaine_dis_base::domaine(), Process::exit(), Modele_turbulence_hyd_0_eq_base::le_dom_VF_, Domaine_32_64< _SIZE_ >::nb_elem(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), TRUST_Ref< _CLASSE_ >::valeur(), and Domaine_VF::xp().
Referenced by lire_motcle_non_standard().
Member Data Documentation
info_obj
const Type_info Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::info_obj static
coeff_field_
TRUST_Deriv< Champ_Fonc_base > Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::coeff_field_ protected
Referenced by associer(), calculer_energie_cinetique_turb(), calculer_model_coefficient(), calculer_viscosite_turbulente(), mettre_a_jour(), stabilise_moyenne_6_points(), stabilise_moyenne_euler_lagrange(), and stabilise_moyenne_plans_paralleles().
methode_stabilise_
Motcle Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::methode_stabilise_ protected
Referenced by lire_motcle_non_standard(), stabilise_moyenne(), and stabilise_moyenne_euler_lagrange().
N_c_
int Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::N_c_ = -123 protected
Referenced by lire_motcle_non_standard(), and stabilise_moyenne_plans_paralleles().
compt_c_
IntVect Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::compt_c_ protected
Referenced by lire_motcle_non_standard(), and stabilise_moyenne_plans_paralleles().
corresp_c_
IntVect Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::corresp_c_ protected
Referenced by lire_motcle_non_standard(), and stabilise_moyenne_plans_paralleles().
elem_elem_
IntTab Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::elem_elem_ protected
Referenced by calc_elem_elem(), and calcul_voisins().
cell_cent_vel_
DoubleTab Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::cell_cent_vel_ protected
Referenced by calcul_voisins(), and mettre_a_jour().