TrioCFD: Collision_Model_FT_base Class Reference
Collision_Model_FT_base Class Reference abstract
#include <Collision_Model_FT_base.h>
Public Member Functions
const Type_info * get_info () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
int reprendre (Entree &is) override
int sauvegarder (Sortie &os) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
Description: This class enables to compute solid-solid interactions for fpi module under the framework of soft-sphere collision model. Under this framework, multiple collisions can occurs at the same time (ie a particle can collide with 2 or more particles). The collision is spread out on multiple time steps. A slight overlap (less than the mesh grid size) occurs during the process.
Member Enumeration Documentation
Collision_model
enum class Collision_Model_FT_base::Collision_model strong protected
Enumerator
HYBRID_ESI
BREUGEM
Detection_method
enum class Collision_Model_FT_base::Detection_method strong protected
Enumerator
CHECK_ALL
VERLET
LC_VERLET
Constructor & Destructor Documentation
~Collision_Model_FT_base()
Collision_Model_FT_base::~Collision_Model_FT_base () override
Collision_Model_FT_base()
Collision_Model_FT_base::Collision_Model_FT_base ()
References Objet_U::dimension, fictive_wall_coordinates_, and TRUSTVect< _TYPE_, _SIZE_ >::resize().
Member Function Documentation
info()
const Type_info * Collision_Model_FT_base::info () static
get_info()
const Type_info * Collision_Model_FT_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
Reimplemented in Collision_Model_FT_sphere, and Collision_Model_FT_spheroid.
self_cast() [1/2]
Collision_Model_FT_base & Collision_Model_FT_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Collision_Model_FT_base & Collision_Model_FT_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Collision_Model_FT_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
Reimplemented in Collision_Model_FT_sphere, and Collision_Model_FT_spheroid.
References Process::exit().
readOn()
Entree & Collision_Model_FT_base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
Reimplemented in Collision_Model_FT_sphere, and Collision_Model_FT_spheroid.
References Param::lire_avec_accolades_depuis(), Objet_U::que_suis_je(), and set_param().
Referenced by Collision_Model_FT_arbitrary::readOn(), Collision_Model_FT_sphere::readOn(), and Collision_Model_FT_spheroid::readOn().
lire_motcle_non_standard()
int Collision_Model_FT_base::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Objet_U.
References TRUST_Vector< _CLASSE_ >::add(), BREUGEM, CHECK_ALL, collision_model_, detection_method_, detection_thickness_Verlet_, Process::exit(), HYBRID_ESI, LC_VERLET, nb_dt_max_Verlet_, Objet_U::que_suis_je(), Motcles::search(), and VERLET.
reprendre()
int Collision_Model_FT_base::reprendre (Entree &) override virtual
Reprise d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree&) flot d'entree a utiliser pour la reprise
Returns
(int) code de retour
Reimplemented from Objet_U.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, e_eff_, Process::exit(), F_old_, EcritureLectureSpecial::is_lecture_special(), nb_particles_tot_, Objet_U::que_suis_je(), and TRUSTTab< _TYPE_, _SIZE_ >::resize().
Referenced by Transport_Interfaces_FT_Disc::reprendre().
sauvegarder()
int Collision_Model_FT_base::sauvegarder (Sortie &) const override virtual
Sauvegarde d'un Objet_U sur un flot de sortie Methode a surcharger.
Parameters
(Sortie&) flot de sortie a utiliser pour la sauvegarde
Returns
(int) code de retour
Reimplemented from Objet_U.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), e_eff_, F_old_, EcritureLectureSpecial::is_ecriture_special(), Process::je_suis_maitre(), nb_particles_tot_, Objet_U::que_suis_je(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by Transport_Interfaces_FT_Disc::sauvegarder().
preparer_calcul()
int Collision_Model_FT_base::preparer_calcul (const Domaine_VDF & domain_vdf, const int nb_particles_tot, const Navier_Stokes_FT_Disc & ns, const Transport_Interfaces_FT_Disc & eq_transport, const Schema_Comm & schema_comm_FT)
References associate_transport_equation(), compute_fictive_wall_coordinates(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), F_now_, F_old_, Navier_Stokes_FT_Disc::fluide_diphasique(), Fluide_Diphasique::fluide_phase(), Solid_Particle_base::get_equivalent_diameter(), Fluide_Diphasique::get_id_fluid_phase(), is_LC_activated(), reset(), resize_lagrangian_contact_force(), resize_particles_collision_number(), set_activation_distance(), set_geometric_parameters(), set_LC_zones(), set_nb_particles_tot(), set_nb_real_particles(), and set_spring_properties().
Referenced by Transport_Interfaces_FT_Disc::preparer_calcul().
set_param()
void Collision_Model_FT_base::set_param (Param & p)
References activation_distance_percentage_diameter_, Param::ajouter(), Param::ajouter_non_std(), collision_duration_, is_collision_activated_before_impact_, is_force_on_two_phase_elem_, and Param::REQUIRED.
Referenced by readOn().
reset()
void Collision_Model_FT_base::reset ()
References Objet_U::dimension, e_eff_, F_now_, F_old_, nb_particles_tot_, and TRUSTTab< _TYPE_, _SIZE_ >::resize().
Referenced by preparer_calcul().
resize_geometric_parameters()
void Collision_Model_FT_base::resize_geometric_parameters ()
References Objet_U::dimension, domain_dimensions_, nb_nodes_, origin_, and TRUSTVect< _TYPE_, _SIZE_ >::resize().
Referenced by set_geometric_parameters().
resize_lagrangian_contact_force()
void Collision_Model_FT_base::resize_lagrangian_contact_force () inline
References Objet_U::dimension, lagrangian_contact_forces_, nb_particles_tot_, and TRUSTTab< _TYPE_, _SIZE_ >::resize().
Referenced by preparer_calcul().
resize_particles_collision_number()
void Collision_Model_FT_base::resize_particles_collision_number () inline
References nb_particles_tot_, particles_collision_number_, and TRUSTTab< _TYPE_, _SIZE_ >::resize().
Referenced by preparer_calcul().
associate_transport_equation()
void Collision_Model_FT_base::associate_transport_equation (const Equation_base & equation)
References refequation_transport_.
Referenced by preparer_calcul().
check_for_duplicates()
int Collision_Model_FT_base::check_for_duplicates (ArrOfInt & vector)
Check if two particles have the same ID Very important function to stop computation if two particles coalesce.
References TRUSTArray< _TYPE_, _SIZE_ >::ordonne_array(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by Transport_Interfaces_FT_Disc::swap_particles_lagrangian_position_velocity().
compute_fictive_wall_coordinates()
void Collision_Model_FT_base::compute_fictive_wall_coordinates (const double & radius)
References activation_distance_, Objet_U::dimension, domain_dimensions_, Process::exit(), fictive_wall_coordinates_, is_collision_activated_before_impact_, and origin_.
Referenced by preparer_calcul().
compute_lagrangian_contact_forces()
virtual void Collision_Model_FT_base::compute_lagrangian_contact_forces (const Fluide_Diphasique & two_phase_fluid, const DoubleTab & particles_position, const DoubleTab & particles_velocity, const double & deltat_simu) pure virtual
Implemented in Collision_Model_FT_arbitrary, Collision_Model_FT_sphere, and Collision_Model_FT_spheroid.
Referenced by Navier_Stokes_FT_Disc::compute_eulerian_field_contact_forces().
discretize_contact_forces_eulerian_field()
void Collision_Model_FT_base::discretize_contact_forces_eulerian_field (const DoubleTab & volumic_phase_indicator_function, const Domaine_VF & domain_vf, const IntTab & particles_eulerian_id_number, DoubleTab & contact_force_source_term) pure virtual
Implemented in Collision_Model_FT_arbitrary, Collision_Model_FT_sphere, and Collision_Model_FT_spheroid.
References Process::exit().
Referenced by Navier_Stokes_FT_Disc::compute_eulerian_field_contact_forces().
research_collision_pairs_Verlet()
void Collision_Model_FT_base::research_collision_pairs_Verlet (const Navier_Stokes_FT_Disc & eq_ns, const Transport_Interfaces_FT_Disc & eq_transport)
References TRUSTArray< _TYPE_, _SIZE_ >::append_array(), compute_Verlet_tables(), detection_method_, detection_thickness_Verlet_, TRUSTLists< _TYPE_ >::dimensionner(), Equation_base::domaine_dis(), Navier_Stokes_FT_Disc::fluide_diphasique(), Fluide_Diphasique::fluide_phase(), Transport_Interfaces_FT_Disc::get_gravity_center_elem(), Fluide_Diphasique::get_id_fluid_phase(), get_list_lower_zone(), Transport_Interfaces_FT_Disc::get_particles_position(), Transport_Interfaces_FT_Disc::get_particles_velocity(), Maillage_FT_Disc::get_schema_comm_FT(), LC_VERLET, list_real_particles_, Transport_Interfaces_FT_Disc::maillage_interface(), Process::mp_max(), nb_dt_compute_Verlet_, nb_dt_max_Verlet_, nb_dt_Verlet_, Domaine_dis_base::nb_elem(), nb_particles_tot_, nb_real_particles_, Schema_Temps_base::pas_de_temps(), TRUSTArray< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), Equation_base::schema_temps(), TRUSTLists< _TYPE_ >::size(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and Verlet_tables_.
Referenced by Navier_Stokes_FT_Disc::compute_eulerian_field_contact_forces().
compute_Verlet_tables()
void Collision_Model_FT_base::compute_Verlet_tables (const DoubleTab & particles_position, const DoubleTab & particles_velocity, double & max_vi, const double & radius, const ArrOfInt & list_particles_to_check_LC)
References detection_thickness_Verlet_, Objet_U::dimension, fictive_wall_coordinates_, get_id(), get_last_id(), nb_particles_tot_, nb_real_particles_, and Verlet_tables_.
Referenced by research_collision_pairs_Verlet().
compute_contact_force()
DoubleTab Collision_Model_FT_base::compute_contact_force (const double & next_dist_int, const DoubleTab & norm, const DoubleTab & dUn, const int & particle_i, const int & particle_j, const int & is_compression_step, const double & is_collision_part_part)
References BREUGEM, collision_model_, damper_breugem_part_part_, damper_breugem_wall_part_, Objet_U::dimension, e_eff_, Process::exit(), HYBRID_ESI, stiffness_breugem_part_part_, and stiffness_breugem_wall_part_.
Referenced by Collision_Model_FT_sphere::compute_lagrangian_contact_forces().
compute_ewet_legendre()
double Collision_Model_FT_base::compute_ewet_legendre (const double & St) inline
Referenced by Collision_Model_FT_sphere::compute_lagrangian_contact_forces().
compute_stiffness_breugem()
double Collision_Model_FT_base::compute_stiffness_breugem (const double & mass_eff, const double & e_dry) inline
References collision_duration_.
Referenced by set_spring_properties().
compute_damper_breugem()
double Collision_Model_FT_base::compute_damper_breugem (const double & mass_eff, const double & e_dry) inline
References collision_duration_.
Referenced by set_spring_properties().
add_collision()
void Collision_Model_FT_base::add_collision (const int part_i, const int part_j, const bool is_part_part_collision)
References nb_particles_tot_, and particles_collision_number_.
Referenced by Collision_Model_FT_sphere::compute_lagrangian_contact_forces().
is_Verlet_activated()
bool Collision_Model_FT_base::is_Verlet_activated ()
References CHECK_ALL, and detection_method_.
Referenced by Navier_Stokes_FT_Disc::compute_eulerian_field_contact_forces().
is_LC_activated()
bool Collision_Model_FT_base::is_LC_activated ()
References detection_method_, and LC_VERLET.
Referenced by preparer_calcul().
set_nb_particles_tot()
void Collision_Model_FT_base::set_nb_particles_tot (int nb_particles_tot) inline
References nb_particles_tot_.
Referenced by preparer_calcul().
set_nb_real_particles()
void Collision_Model_FT_base::set_nb_real_particles (int nb_real_particles) inline
References nb_real_particles_.
Referenced by preparer_calcul().
set_activation_distance()
void Collision_Model_FT_base::set_activation_distance (const double & diameter) inline
References activation_distance_, and activation_distance_percentage_diameter_.
Referenced by preparer_calcul().
set_spring_properties()
void Collision_Model_FT_base::set_spring_properties (const Solid_Particle_base & solid_particle)
References BREUGEM, collision_duration_, collision_model_, compute_damper_breugem(), compute_stiffness_breugem(), damper_breugem_part_part_, damper_breugem_wall_part_, Solid_Particle_base::get_e_dry(), Solid_Particle_base::get_mass(), stiffness_breugem_part_part_, and stiffness_breugem_wall_part_.
Referenced by preparer_calcul().
set_domain_dimensions()
void Collision_Model_FT_base::set_domain_dimensions (DoubleVect & Longueurs) inline
References domain_dimensions_.
Referenced by set_geometric_parameters().
set_origin()
void Collision_Model_FT_base::set_origin (DoubleVect & Origin) inline
References origin_.
Referenced by set_geometric_parameters().
set_geometric_parameters()
void Collision_Model_FT_base::set_geometric_parameters (const Domaine_VDF & domaine_vdf)
Recover the geometric parameters of the domain: number of nodes in each direction origin of the domain dimensions of the domain.
References Process::check_int_overflow(), Objet_U::dimension, Domaine_dis_base::domaine(), Domaine_32_64< _SIZE_ >::faces_bord(), Domaine_32_64< _SIZE_ >::getBoundingBox(), Process::mp_max(), Process::mp_min(), Process::mp_sum(), Bords_32_64< _SIZE_ >::nb_bords(), nb_nodes_, Domaine_VDF::orientation(), resize_geometric_parameters(), set_domain_dimensions(), and set_origin().
Referenced by preparer_calcul().
set_LC_zones()
void Collision_Model_FT_base::set_LC_zones (const Domaine_VF & domaine_vf, const Schema_Comm & schema_com)
References TRUSTArray< _TYPE_, _SIZE_ >::append_array(), TRUSTTab< _TYPE_, _SIZE_ >::append_line(), Schema_Comm::begin_comm(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Schema_Comm::echange_taille_et_messages(), Schema_Comm::end_comm(), Entree::eof(), Process::exit(), Schema_Comm::get_recv_pe_list(), Domaine_VF::joint(), list_lower_zone_, list_upper_zone_, Process::me(), Process::mp_max(), Domaine_dis_base::nb_elem(), Domaine_dis_base::nb_elem_tot(), Domaine_VF::nb_joints(), Joint_32_64< _SIZE_ >::PEvoisin(), Schema_Comm::recv_buffer(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), Schema_Comm::send_buffer(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and Domaine_VF::xp().
Referenced by preparer_calcul().
get_nb_dt_Verlet()
const int & Collision_Model_FT_base::get_nb_dt_Verlet () const inline
References nb_dt_Verlet_.
get_nb_dt_compute_Verlet()
const int & Collision_Model_FT_base::get_nb_dt_compute_Verlet () const inline
References nb_dt_compute_Verlet_.
Referenced by Navier_Stokes_FT_Disc::compute_eulerian_field_contact_forces().
get_nb_dt_max_Verlet()
const int & Collision_Model_FT_base::get_nb_dt_max_Verlet () const inline
References nb_dt_max_Verlet_.
get_is_force_on_two_phase_elem()
const int & Collision_Model_FT_base::get_is_force_on_two_phase_elem () const inline
References is_force_on_two_phase_elem_.
Referenced by Navier_Stokes_FT_Disc::compute_particles_eulerian_id_number().
get_collision_number()
const int & Collision_Model_FT_base::get_collision_number () const inline
References collision_number_.
Referenced by Transport_Interfaces_FT_Disc::impr().
get_nb_real_particles()
const int & Collision_Model_FT_base::get_nb_real_particles () const inline
References nb_real_particles_.
get_last_id()
int Collision_Model_FT_base::get_last_id (const ArrOfInt & list_particles_to_check_LC)
References CHECK_ALL, detection_method_, Process::exit(), LC_VERLET, nb_particles_tot_, TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and VERLET.
Referenced by compute_Verlet_tables().
get_id()
int Collision_Model_FT_base::get_id (const ArrOfInt & list_particle, const int ind_id_particle)
References CHECK_ALL, detection_method_, Process::exit(), LC_VERLET, and VERLET.
Referenced by compute_Verlet_tables().
get_duration_collision()
const double & Collision_Model_FT_base::get_duration_collision () const inline
References collision_duration_.
get_delta_n()
const double & Collision_Model_FT_base::get_delta_n () const inline
References activation_distance_percentage_diameter_.
get_s_Verlet()
const double & Collision_Model_FT_base::get_s_Verlet () const inline
References detection_thickness_Verlet_.
get_wall_coordinates()
const DoubleVect & Collision_Model_FT_base::get_wall_coordinates () const inline
References fictive_wall_coordinates_.
get_origin()
const DoubleVect & Collision_Model_FT_base::get_origin () const inline
References origin_.
get_domain_dimensions()
const DoubleVect & Collision_Model_FT_base::get_domain_dimensions () const inline
References domain_dimensions_.
get_lagrangian_contact_forces()
const DoubleTab & Collision_Model_FT_base::get_lagrangian_contact_forces () const inline
References lagrangian_contact_forces_.
Referenced by Transport_Interfaces_FT_Disc::impr().
get_particles_collision_number()
const DoubleTab & Collision_Model_FT_base::get_particles_collision_number () const inline
References particles_collision_number_.
Referenced by Transport_Interfaces_FT_Disc::impr().
get_list_upper_zone()
const ArrOfInt & Collision_Model_FT_base::get_list_upper_zone () const inline
References list_upper_zone_.
get_list_lower_zone()
const ArrOfInt & Collision_Model_FT_base::get_list_lower_zone () const inline
References list_lower_zone_.
Referenced by research_collision_pairs_Verlet().
get_Verlet_table()
const IntLists & Collision_Model_FT_base::get_Verlet_table () const inline
References Verlet_tables_.
get_set_collisions_detected()
DoubleVect & Collision_Model_FT_base::get_set_collisions_detected () inline
References collision_detected_.
get_set_e_eff()
DoubleTab & Collision_Model_FT_base::get_set_e_eff () inline
References e_eff_.
get_set_F_old()
DoubleTab & Collision_Model_FT_base::get_set_F_old () inline
References F_old_.
get_set_F_now()
DoubleTab & Collision_Model_FT_base::get_set_F_now () inline
References F_now_.
get_set_lagrangian_contact_forces()
DoubleTab & Collision_Model_FT_base::get_set_lagrangian_contact_forces () inline
References lagrangian_contact_forces_.
get_set_nb_dt_Verlet()
int & Collision_Model_FT_base::get_set_nb_dt_Verlet () inline
References nb_dt_Verlet_.
Referenced by Navier_Stokes_FT_Disc::compute_eulerian_field_contact_forces().
compute_dX_dU()
void Collision_Model_FT_base::compute_dX_dU (DoubleTab & dX, DoubleTab & dU, const int & particle, const int & neighbor, const DoubleTab & particles_position, const DoubleTab & particles_velocity, const bool is_particle_particle_collision) protected
References Objet_U::dimension, fictive_wall_coordinates_, and nb_particles_tot_.
Referenced by Collision_Model_FT_sphere::compute_lagrangian_contact_forces().
get_nb_particles_j()
int Collision_Model_FT_base::get_nb_particles_j (const int ind_particle_i) const protected
References CHECK_ALL, detection_method_, Objet_U::dimension, LC_VERLET, nb_particles_tot_, VERLET, and Verlet_tables_.
Referenced by Collision_Model_FT_sphere::compute_lagrangian_contact_forces().
get_ind_start_particles_j()
int Collision_Model_FT_base::get_ind_start_particles_j (const int ind_particle_i) const protected
References CHECK_ALL, and detection_method_.
Referenced by Collision_Model_FT_sphere::compute_lagrangian_contact_forces().
get_particle_i()
int Collision_Model_FT_base::get_particle_i (const int ind_particle_i) protected
References detection_method_, LC_VERLET, and list_real_particles_.
Referenced by Collision_Model_FT_sphere::compute_lagrangian_contact_forces().
get_particle_j()
int Collision_Model_FT_base::get_particle_j (const int ind_particle_i, const int ind_particle_j) protected
References CHECK_ALL, detection_method_, LC_VERLET, VERLET, and Verlet_tables_.
Referenced by Collision_Model_FT_sphere::compute_lagrangian_contact_forces().
Member Data Documentation
info_obj
const Type_info Collision_Model_FT_base::info_obj static
is_collision_activated_before_impact_
int Collision_Model_FT_base::is_collision_activated_before_impact_ = 1 protected
Referenced by compute_fictive_wall_coordinates(), and set_param().
is_force_on_two_phase_elem_
int Collision_Model_FT_base::is_force_on_two_phase_elem_ = 0 protected
Referenced by get_is_force_on_two_phase_elem(), and set_param().
nb_particles_tot_
int Collision_Model_FT_base::nb_particles_tot_ = 0 protected
Referenced by add_collision(), compute_dX_dU(), Collision_Model_FT_sphere::compute_lagrangian_contact_forces(), compute_Verlet_tables(), get_last_id(), get_nb_particles_j(), reprendre(), research_collision_pairs_Verlet(), reset(), resize_lagrangian_contact_force(), resize_particles_collision_number(), sauvegarder(), and set_nb_particles_tot().
nb_dt_Verlet_
int Collision_Model_FT_base::nb_dt_Verlet_ = 0 protected
Referenced by get_nb_dt_Verlet(), get_set_nb_dt_Verlet(), and research_collision_pairs_Verlet().
nb_dt_compute_Verlet_
int Collision_Model_FT_base::nb_dt_compute_Verlet_ = 0 protected
Referenced by get_nb_dt_compute_Verlet(), and research_collision_pairs_Verlet().
nb_dt_max_Verlet_
int Collision_Model_FT_base::nb_dt_max_Verlet_ = 0 protected
Referenced by get_nb_dt_max_Verlet(), lire_motcle_non_standard(), and research_collision_pairs_Verlet().
collision_number_
int Collision_Model_FT_base::collision_number_ = 0 protected
Referenced by Collision_Model_FT_sphere::compute_lagrangian_contact_forces(), and get_collision_number().
no_collision_model_
int Collision_Model_FT_base::no_collision_model_ =0 protected
activation_distance_percentage_diameter_
double Collision_Model_FT_base::activation_distance_percentage_diameter_ = 0 protected
Referenced by get_delta_n(), set_activation_distance(), and set_param().
activation_distance_
double Collision_Model_FT_base::activation_distance_ = 0 protected
Referenced by compute_fictive_wall_coordinates(), and set_activation_distance().
collision_duration_
double Collision_Model_FT_base::collision_duration_ = 0. protected
Referenced by compute_damper_breugem(), compute_stiffness_breugem(), get_duration_collision(), set_param(), and set_spring_properties().
detection_thickness_Verlet_
double Collision_Model_FT_base::detection_thickness_Verlet_ = 0. protected
Referenced by compute_Verlet_tables(), get_s_Verlet(), lire_motcle_non_standard(), and research_collision_pairs_Verlet().
particles_collision_number_
DoubleTab Collision_Model_FT_base::particles_collision_number_ protected
Referenced by add_collision(), Collision_Model_FT_sphere::compute_lagrangian_contact_forces(), get_particles_collision_number(), and resize_particles_collision_number().
e_eff_
DoubleTab Collision_Model_FT_base::e_eff_ protected
Referenced by compute_contact_force(), Collision_Model_FT_sphere::compute_lagrangian_contact_forces(), get_set_e_eff(), reprendre(), reset(), and sauvegarder().
F_old_
DoubleTab Collision_Model_FT_base::F_old_ protected
Referenced by Collision_Model_FT_sphere::compute_lagrangian_contact_forces(), get_set_F_old(), preparer_calcul(), reprendre(), reset(), and sauvegarder().
F_now_
DoubleTab Collision_Model_FT_base::F_now_ protected
Referenced by Collision_Model_FT_sphere::compute_lagrangian_contact_forces(), get_set_F_now(), preparer_calcul(), and reset().
lagrangian_contact_forces_
DoubleTab Collision_Model_FT_base::lagrangian_contact_forces_ protected
Referenced by Collision_Model_FT_sphere::compute_lagrangian_contact_forces(), Collision_Model_FT_sphere::discretize_contact_forces_eulerian_field(), get_lagrangian_contact_forces(), get_set_lagrangian_contact_forces(), and resize_lagrangian_contact_force().
collision_detected_
DoubleVect Collision_Model_FT_base::collision_detected_ protected
Referenced by get_set_collisions_detected().
list_upper_zone_
ArrOfInt Collision_Model_FT_base::list_upper_zone_ protected
Referenced by get_list_upper_zone(), and set_LC_zones().
list_lower_zone_
ArrOfInt Collision_Model_FT_base::list_lower_zone_ protected
Referenced by get_list_lower_zone(), and set_LC_zones().
refequation_transport_
TRUST_Ref< Transport_Interfaces_FT_Disc *> Collision_Model_FT_base::refequation_transport_ protected
Referenced by associate_transport_equation().
ref_domaine
TRUST_Ref< Domaine *> Collision_Model_FT_base::ref_domaine protected
nb_nodes_
IntVect Collision_Model_FT_base::nb_nodes_ protected
Referenced by resize_geometric_parameters(), and set_geometric_parameters().
origin_
DoubleVect Collision_Model_FT_base::origin_ protected
Referenced by compute_fictive_wall_coordinates(), get_origin(), resize_geometric_parameters(), and set_origin().
domain_dimensions_
DoubleVect Collision_Model_FT_base::domain_dimensions_ protected
Referenced by compute_fictive_wall_coordinates(), get_domain_dimensions(), resize_geometric_parameters(), and set_domain_dimensions().
fictive_wall_coordinates_
DoubleVect Collision_Model_FT_base::fictive_wall_coordinates_ protected
Referenced by Collision_Model_FT_base(), compute_dX_dU(), compute_fictive_wall_coordinates(), compute_Verlet_tables(), and get_wall_coordinates().
Verlet_tables_
IntLists Collision_Model_FT_base::Verlet_tables_ protected
Referenced by compute_Verlet_tables(), get_nb_particles_j(), get_particle_j(), get_Verlet_table(), and research_collision_pairs_Verlet().
list_real_particles_
ArrOfInt Collision_Model_FT_base::list_real_particles_ protected
Referenced by get_particle_i(), and research_collision_pairs_Verlet().
nb_real_particles_
int Collision_Model_FT_base::nb_real_particles_ protected
Referenced by Collision_Model_FT_sphere::compute_lagrangian_contact_forces(), compute_Verlet_tables(), get_nb_real_particles(), research_collision_pairs_Verlet(), and set_nb_real_particles().
stiffness_breugem_part_part_
double Collision_Model_FT_base::stiffness_breugem_part_part_ = 0 protected
Referenced by compute_contact_force(), and set_spring_properties().
stiffness_breugem_wall_part_
double Collision_Model_FT_base::stiffness_breugem_wall_part_ = 0 protected
Referenced by compute_contact_force(), and set_spring_properties().
damper_breugem_part_part_
double Collision_Model_FT_base::damper_breugem_part_part_ = 0 protected
Referenced by compute_contact_force(), and set_spring_properties().
damper_breugem_wall_part_
double Collision_Model_FT_base::damper_breugem_wall_part_ = 0 protected
Referenced by compute_contact_force(), and set_spring_properties().
collision_model_
Collision_model Collision_Model_FT_base::collision_model_ = Collision_model::HYBRID_ESI protected
Referenced by compute_contact_force(), lire_motcle_non_standard(), and set_spring_properties().
detection_method_
Detection_method Collision_Model_FT_base::detection_method_ = Detection_method::CHECK_ALL protected
Referenced by Collision_Model_FT_sphere::compute_lagrangian_contact_forces(), get_id(), get_ind_start_particles_j(), get_last_id(), get_nb_particles_j(), get_particle_i(), get_particle_j(), is_LC_activated(), is_Verlet_activated(), lire_motcle_non_standard(), and research_collision_pairs_Verlet().