TrioCFD: Field_base Class Reference
Field_base Class Reference
#include <Field_base.h>
Public Member Functions
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
virtual void fixer_nb_comp (int i)
virtual const Nom & fixer_nom_compo (const Nom &)
virtual const Nom & fixer_nom_compo (int, const Nom &)
virtual const Noms & fixer_noms_compo (const Noms &)
virtual const Nom & fixer_unite (const Nom &)
virtual const Nom & fixer_unite (int i, const Nom &)
virtual const Noms & fixer_unites (const Noms &)
const Type_info * get_info () const override
const Nom & nom_compo (int) const
void nommer (const Nom &) override
const Nom & unite () const
const Nom & unite (int) const
const Noms & unites () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
~Field_base()
Field_base::~Field_base () override
Field_base() [1/2]
Field_base::Field_base ()
Field_base() [2/2]
Field_base::Field_base (const Field_base & other) default
Member Function Documentation
info()
const Type_info * Field_base::info () static
get_info()
const Type_info * Field_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
Reimplemented in Ch_front_input_ALE, Champ_front_ALE, Champ_front_ALE_Beam, Champ_front_ALE_projection, Champ_Fonc_reprise_IJK, Estimateur_Aposteriori_P0_VEF, Champ_front_contact_rayo_transp_VEF, Champ_front_rayonnement, Champ_front_contact_rayo_semi_transp_VEF, Boundary_field_keps_from_ud, Boundary_field_uniform_keps_from_ud, Field_uniform_keps_from_ud, Champ_Fonc_MED, Champ_Fonc_MED_Table_Temps, Champ_Fonc_MED_Tabule, Champ_Fonc_P0_MED, Champ_Fonc_P1_MED, Champ_Fonc_Q1_MED, Champ_front_MED, Champ_Fonc_reprise, Champ_front_recyclage, Champ_front_softanalytique, Champ_Elem_PolyMAC, Champ_Elem_PolyMAC_P0, Champ_Elem_PolyMAC_P0P1NC, Champ_Face_PolyMAC, Champ_Face_PolyMAC_P0, Champ_Face_PolyMAC_P0P1NC, Champ_Fonc_Elem_PolyMAC, Champ_Fonc_Elem_PolyMAC_P0_rot, Champ_Fonc_Elem_PolyMAC_P0_TC, Champ_Fonc_Face_PolyMAC, Champ_Fonc_Som_PolyMAC, Champ_Fonc_Tabule_Elem_PolyMAC, Champ_Som_PolyMAC, grad_Champ_Face_PolyMAC_P0, grad_U_Champ_Face_PolyMAC, Champ_front_pression_from_u, Champ_front_synt, Champ_Ostwald, Champ_Don_Face_lu, Champ_Face_VDF, Champ_Fonc_Face_VDF, Champ_Fonc_P0_VDF, Champ_Fonc_P1_VDF, Champ_Fonc_Q1_VDF, Champ_Fonc_Tabule_P0_VDF, Champ_front_debit_QC, Champ_front_debit_QC_fonc_t, Champ_front_fonc_gradient_VDF, Champ_Ostwald_VDF, Champ_P0_VDF, Champ_som_lu_VDF, Champ_val_tot_sur_vol_VDF, Correlation_Vec_Sca_VDF, Courant_maille_Champ_Face, Critere_Q_Champ_Face, grad_U_Champ_Face, Reynolds_maille_Champ_Face, Rotationnel_Champ_Face, T_paroi_Champ_P0_VDF, Taux_cisaillement_P0_VDF, Y_plus_Champ_Face, Champ_Fonc_P0_VEF, Champ_Fonc_P1_isoP1Bulle, Champ_Fonc_P1_VEF, Champ_Fonc_P1NC, Champ_Fonc_Q1_VEF, Champ_Fonc_Q1NC, Champ_Fonc_Tabule_P0_VEF, Champ_front_contact_fictif_VEF, Champ_front_contact_VEF, Champ_front_fonc_gradient_VEF, Champ_front_tangentiel_VEF, Champ_Ostwald_VEF, Champ_P0_VEF, Champ_P1_isoP1Bulle, Champ_P1NC, Champ_Q1NC, Champ_som_lu_VEF, Champ_val_tot_sur_vol_VEF, Correlation_Vec_Sca_VEF, Critere_Q_Champ_P1NC, grad_T_Champ_P1NC, grad_U_Champ_P1NC, h_conv_Champ_P1NC, Rotationnel_Champ_P1NC, Rotationnel_Champ_Q1NC, T_paroi_Champ_P1NC, Taux_cisaillement_P0_VEF, and Y_plus_Champ_P1NC.
self_cast() [1/2]
Field_base & Field_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Field_base & Field_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Field_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
Reimplemented in TRUSTChamp_Don_generique< _TYPE_ >, TRUSTChamp_Don_generique< Champ_Don_Type::TXYZ >, TRUSTChamp_Don_generique< Champ_Don_Type::XYZ >, TRUSTChamp_Don_generique< Champ_Don_Type::LU >, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >, IJK_Field_local_template< double, ArrOfDouble >, IJK_Field_local_template< int, ArrOfInt >, IJK_Field_local_template< _TYPE_, TRUSTArray< _TYPE_ > >, IJK_Field_local_template< double, TRUSTArray >, IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >, IJK_Field_template< double, ArrOfDouble >, IJK_Field_template< int, ArrOfInt >, IJK_Field_template< _TYPE_, TRUSTArray< _TYPE_ > >, IJK_Field_vector< T, N >, IJK_Field_vector< double, 3 >, IJK_Field_vector< int, 3 >, IJK_Field_vector< double, max_authorized_nb_of_groups_ >, IJK_Field_vector< double, N >, Ch_front_input_ALE, Champ_front_ALE, Champ_front_ALE_Beam, Champ_front_ALE_projection, Champ_Fonc_reprise_IJK, Estimateur_Aposteriori_P0_VEF, Champ_front_contact_rayo_transp_VEF, Champ_front_rayonnement, Champ_front_contact_rayo_semi_transp_VEF, Boundary_field_keps_from_ud, Boundary_field_uniform_keps_from_ud, Field_uniform_keps_from_ud, Champ_Fonc_MED, Champ_Fonc_MED_Table_Temps, Champ_Fonc_MED_Tabule, Champ_Fonc_P0_MED, Champ_Fonc_P1_MED, Champ_Fonc_Q1_MED, Champ_front_MED, Champ_Fonc_reprise, Champ_front_recyclage, Champ_front_softanalytique, Champ_Elem_PolyMAC, Champ_Elem_PolyMAC_P0, Champ_Elem_PolyMAC_P0P1NC, Champ_Face_PolyMAC, Champ_Face_PolyMAC_P0, Champ_Face_PolyMAC_P0P1NC, Champ_Fonc_Elem_PolyMAC, Champ_Fonc_Elem_PolyMAC_P0_rot, Champ_Fonc_Elem_PolyMAC_P0_TC, Champ_Fonc_Face_PolyMAC, Champ_Fonc_Som_PolyMAC, Champ_Fonc_Tabule_Elem_PolyMAC, Champ_Som_PolyMAC, grad_Champ_Face_PolyMAC_P0, grad_U_Champ_Face_PolyMAC, Champ_front_pression_from_u, Champ_front_synt, Champ_Ostwald, Champ_Don_Face_lu, Champ_Face_VDF, Champ_Fonc_Face_VDF, Champ_Fonc_P0_VDF, Champ_Fonc_P1_VDF, Champ_Fonc_Q1_VDF, Champ_Fonc_Tabule_P0_VDF, Champ_front_debit_QC, Champ_front_debit_QC_fonc_t, Champ_front_fonc_gradient_VDF, Champ_Ostwald_VDF, Champ_P0_VDF, Champ_som_lu_VDF, Champ_val_tot_sur_vol_VDF, Correlation_Vec_Sca_VDF, Courant_maille_Champ_Face, Critere_Q_Champ_Face, grad_U_Champ_Face, Reynolds_maille_Champ_Face, Rotationnel_Champ_Face, T_paroi_Champ_P0_VDF, Taux_cisaillement_P0_VDF, Y_plus_Champ_Face, Champ_Fonc_P0_VEF, Champ_Fonc_P1_isoP1Bulle, Champ_Fonc_P1_VEF, Champ_Fonc_P1NC, Champ_Fonc_Q1_VEF, Champ_Fonc_Q1NC, Champ_Fonc_Tabule_P0_VEF, Champ_front_contact_fictif_VEF, Champ_front_contact_VEF, Champ_front_fonc_gradient_VEF, Champ_front_tangentiel_VEF, Champ_Ostwald_VEF, Champ_P0_VEF, Champ_P1_isoP1Bulle, Champ_P1NC, Champ_Q1NC, Champ_som_lu_VEF, Champ_val_tot_sur_vol_VEF, Correlation_Vec_Sca_VEF, Critere_Q_Champ_P1NC, grad_T_Champ_P1NC, grad_U_Champ_P1NC, h_conv_Champ_P1NC, Rotationnel_Champ_P1NC, Rotationnel_Champ_Q1NC, T_paroi_Champ_P1NC, Taux_cisaillement_P0_VEF, and Y_plus_Champ_P1NC.
readOn()
Entree & Field_base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
Reimplemented in Ch_front_input_ALE, Champ_front_ALE, Champ_front_ALE_Beam, Champ_front_ALE_projection, Champ_Fonc_reprise_IJK, Estimateur_Aposteriori_P0_VEF, Champ_front_contact_rayo_transp_VEF, Champ_front_rayonnement, Champ_front_contact_rayo_semi_transp_VEF, Boundary_field_keps_from_ud, Boundary_field_uniform_keps_from_ud, Field_uniform_keps_from_ud, Champ_Fonc_MED, Champ_Fonc_MED_Table_Temps, Champ_Fonc_MED_Tabule, Champ_Fonc_P0_MED, Champ_Fonc_P1_MED, Champ_Fonc_Q1_MED, Champ_front_MED, Champ_Fonc_reprise, Champ_front_recyclage, Champ_front_softanalytique, Champ_Elem_PolyMAC, Champ_Elem_PolyMAC_P0, Champ_Elem_PolyMAC_P0P1NC, Champ_Face_PolyMAC, Champ_Face_PolyMAC_P0, Champ_Face_PolyMAC_P0P1NC, Champ_Fonc_Elem_PolyMAC, Champ_Fonc_Elem_PolyMAC_P0_rot, Champ_Fonc_Elem_PolyMAC_P0_TC, Champ_Fonc_Face_PolyMAC, Champ_Fonc_Som_PolyMAC, Champ_Fonc_Tabule_Elem_PolyMAC, Champ_Som_PolyMAC, grad_Champ_Face_PolyMAC_P0, grad_U_Champ_Face_PolyMAC, Champ_front_pression_from_u, Champ_front_synt, Champ_Ostwald, Champ_Don_Face_lu, Champ_Face_VDF, Champ_Fonc_Face_VDF, Champ_Fonc_P0_VDF, Champ_Fonc_P1_VDF, Champ_Fonc_Q1_VDF, Champ_Fonc_Tabule_P0_VDF, Champ_front_debit_QC, Champ_front_debit_QC_fonc_t, Champ_front_fonc_gradient_VDF, Champ_Ostwald_VDF, Champ_P0_VDF, Champ_som_lu_VDF, Champ_val_tot_sur_vol_VDF, Correlation_Vec_Sca_VDF, Courant_maille_Champ_Face, Critere_Q_Champ_Face, grad_U_Champ_Face, Reynolds_maille_Champ_Face, Rotationnel_Champ_Face, T_paroi_Champ_P0_VDF, Taux_cisaillement_P0_VDF, Y_plus_Champ_Face, Champ_Fonc_P0_VEF, Champ_Fonc_P1_isoP1Bulle, Champ_Fonc_P1_VEF, Champ_Fonc_P1NC, Champ_Fonc_Q1_VEF, Champ_Fonc_Q1NC, Champ_Fonc_Tabule_P0_VEF, Champ_front_contact_fictif_VEF, Champ_front_contact_VEF, Champ_front_fonc_gradient_VEF, Champ_front_tangentiel_VEF, Champ_Ostwald_VEF, Champ_P0_VEF, Champ_P1_isoP1Bulle, Champ_P1NC, Champ_Q1NC, Champ_som_lu_VEF, Champ_val_tot_sur_vol_VEF, Correlation_Vec_Sca_VEF, Critere_Q_Champ_P1NC, grad_T_Champ_P1NC, grad_U_Champ_P1NC, h_conv_Champ_P1NC, Rotationnel_Champ_P1NC, Rotationnel_Champ_Q1NC, T_paroi_Champ_P1NC, Taux_cisaillement_P0_VEF, Y_plus_Champ_P1NC, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >, IJK_Field_local_template< double, ArrOfDouble >, IJK_Field_local_template< int, ArrOfInt >, IJK_Field_local_template< _TYPE_, TRUSTArray< _TYPE_ > >, IJK_Field_local_template< double, TRUSTArray >, IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >, IJK_Field_template< double, ArrOfDouble >, IJK_Field_template< int, ArrOfInt >, IJK_Field_template< _TYPE_, TRUSTArray< _TYPE_ > >, IJK_Field_vector< T, N >, IJK_Field_vector< double, 3 >, IJK_Field_vector< int, 3 >, IJK_Field_vector< double, max_authorized_nb_of_groups_ >, and IJK_Field_vector< double, N >.
nommer()
void Field_base::nommer (const Nom & name) override virtual
Donne un nom au champ.
Parameters
(Nom& name) le nom a donner au champ
Reimplemented from Objet_U.
Reimplemented in IJK_Field_vector< T, N >, IJK_Field_vector< double, 3 >, IJK_Field_vector< int, 3 >, IJK_Field_vector< double, max_authorized_nb_of_groups_ >, and IJK_Field_vector< double, N >.
References nom_.
Referenced by Op_Diff_RotRot::associer(), Modele_turbulence_hyd_LES_DSGS_VDF::associer(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::associer(), Champ_base::Champ_base(), Modele_turbulence_hyd_RANS_Gen< MODELE >::complete_viscosity_field(), Flux_radiatif_base::completer(), Modele_turbulence_hyd_0_eq_base::completer(), Op_Correlation::completer(), Op_Ecart_type::completer(), Op_Moyenne::completer(), Discret_Thyd::concentration(), Champ_front_contact_VEF::connectivity_failed(), VDF_discretisation::courant_maille(), Champ_Fonc_MED::creer(), Milieu_base::creer_alpha(), Pb_MED::creer_champ(), EF_discretisation::creer_champ_vorticite(), PolyMAC_P0_discretisation::creer_champ_vorticite(), VDF_discretisation::creer_champ_vorticite(), VEF_discretisation::creer_champ_vorticite(), Fluide_base::creer_nu(), Fluide_base::creer_temperature_multiphase(), VDF_discretisation::critere_Q(), VEF_discretisation::critere_Q(), Navier_Stokes_FT_Disc::discretiser(), Equation_rayonnement_base::discretiser(), Transport_K_Eps_base::discretiser(), Transport_K_Omega_base::discretiser(), Transport_K_ou_Eps_base::discretiser(), Navier_Stokes_Fluide_Dilatable_base::discretiser(), Navier_Stokes_Turbulent_QC::discretiser(), Modele_rayo_semi_transp::discretiser(), EF_discretisation::distance_paroi(), PolyMAC_discretisation::distance_paroi(), VEF_discretisation::distance_paroi(), fixer_nom_compo(), Discret_Thermique::Fluctu_Temperature(), VDF_discretisation::grad_u(), VEF_discretisation::grad_u(), PolyMAC_discretisation::grad_u(), PolyMAC_P0_discretisation::grad_u(), VEF_discretisation::h_conv(), Equation_base::init_champ_conserve(), Energie_Multiphase::init_champ_convecte(), Navier_Stokes_FTD_IJK::initialise_ns_fields(), Loi_Etat_Multi_GP_WC::initialiser_inco_ch(), Traitement_particulier_NS_Pression_VDF::lire(), Traitement_particulier_NS_Brech_VEF::lire(), Traitement_particulier_NS_Pression_VEF::lire(), Terme_Puissance_Thermique::lire_donnees(), Fluide_Dilatable_base::lire_motcle_non_standard(), Convection_Diffusion_Concentration::lire_motcle_non_standard(), Discretisation_base::mesh_numbering(), IJK_Field_vector< T, N >::nommer(), Discretisation_base::nommer_completer_champ_physique(), Pb_Dilatable_base::preparer_calcul(), Source_injection_masse_base::readOn(), Champ_Fonc_reprise_IJK::readOn(), Champ_Front_Composite::readOn(), Champ_Front_MUSIG::readOn(), Champ_Composite::readOn(), Champ_MUSIG::readOn(), List_Equations_Scalaires_Passifs_Especes::readOn(), Champ_Fonc_MED::readOn(), Champ_Fonc_reprise::readOn(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::readOn(), Convection_Diffusion_Espece_Binaire_base::readOn(), Energie_Multiphase_Enthalpie::readOn(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::reprendre(), Convection_Diffusion_Fluide_Dilatable_Proto::Reprendre_WC(), VDF_discretisation::reynolds_maille(), Convection_Diffusion_Fluide_Dilatable_Proto::Sauvegarder_WC(), Ch_front_input::set_name(), Champ_input_P0::set_name(), Ch_front_input_uniforme::set_name(), Ch_input_uniforme::set_name(), VDF_discretisation::t_paroi(), VEF_discretisation::t_paroi(), PolyMAC_P0_discretisation::taux_cisaillement(), VDF_discretisation::taux_cisaillement(), VEF_discretisation::taux_cisaillement(), EF_discretisation::vorticite(), VDF_discretisation::vorticite(), VEF_discretisation::vorticite(), VDF_discretisation::y_plus(), EF_discretisation::y_plus(), and VEF_discretisation::y_plus().
le_nom()
const Nom & Field_base::le_nom () const override virtual
Renvoie le nom du champ.
Reimplemented from Objet_U.
References nom_.
Referenced by Probleme_base_interface_proto::addInputField_impl(), Champ_implementation_P0::affecter_(), Champ_Fonc_Tabule::affecter_(), Champs_compris_IJK::ajoute_champ_vectoriel(), Op_Diff_VDF_base::ajoute_terme_pour_axi(), Op_Dift_VDF_base::ajoute_terme_pour_axi_turb(), Operateur_base::ajouter(), Perte_Charge_Singuliere_VDF_Face::ajouter_(), Op_Diff_K_Eps_VDF_base::ajouter_blocs(), Op_Diff_K_Omega_VDF_base::ajouter_blocs(), Source_Transport_Realisable_VDF_Elem_base::ajouter_blocs(), Source_Transport_Eps_VDF_Elem::ajouter_blocs(), Source_Transport_K_VDF_Elem::ajouter_blocs(), Source_Transport_K_Eps_VDF_Elem::ajouter_blocs(), Source_Transport_K_Omega_VDF_Elem::ajouter_blocs(), Acceleration_QC_VDF_Face::ajouter_blocs(), Source_qdm_QC_VDF_Face::ajouter_blocs(), Perte_Charge_Reguliere_QC_VDF_Face::ajouter_blocs(), Perte_Charge_Singuliere_QC_VDF_Face::ajouter_blocs(), Darcy_QC_VDF_Face::ajouter_blocs(), Forchheimer_QC_VDF_Face::ajouter_blocs(), Perte_Charge_Reguliere_VDF_Face::ajouter_blocs(), Perte_Charge_Singuliere_VDF_Face::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_P0_Face::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Face::ajouter_blocs(), Op_Diff_PolyMAC_P0_Face::ajouter_blocs(), Op_Grad_PolyMAC_P0_Face::ajouter_blocs(), Injection_QDM_nulle_PolyMAC_P0::ajouter_blocs(), Injection_QDM_nulle_VDF::ajouter_blocs(), Diffusion_croisee_echelle_temp_taux_diss_turb_PolyMAC_P0::ajouter_blocs(), Diffusion_croisee_echelle_temp_taux_diss_turb_VDF::ajouter_blocs(), Op_Diff_DG_Elem::ajouter_blocs(), Frottement_interfacial_PolyMAC_P0::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::ajouter_blocs(), Op_Diff_PolyMAC_P0_Elem::ajouter_blocs(), DP_Impose_PolyMAC_Face::ajouter_blocs(), Perte_Charge_PolyMAC::ajouter_blocs(), Perte_Charge_Singuliere_PolyMAC_P0P1NC_Face::ajouter_blocs(), Terme_Source_Decroissance_Radioactive_Elem_PolyMAC::ajouter_blocs(), Op_Evanescence_Homogene_Elem_base::ajouter_blocs(), Op_Evanescence_Homogene_Face_base::ajouter_blocs(), Source_Force_Tchen_base::ajouter_blocs(), Frottement_interfacial_VDF::ajouter_blocs(), Op_Conv_Amont_VPoly_VDF_Face::ajouter_blocs(), Perte_Charge_VDF_base::ajouter_blocs(), DP_Impose_VEF_Face::ajouter_blocs(), Masse_DG_base::ajouter_blocs(), Masse_PolyMAC_P0_Face::ajouter_blocs(), Masse_VDF_base::ajouter_blocs(), Masse_VDF_Face::ajouter_blocs(), Op_Evanescence_Homogene_PolyMAC_P0_Face::ajouter_blocs_aux(), Force_Tchen_PolyMAC_P0::ajouter_blocs_aux(), Op_Diff_PolyMAC_P0P1NC_Face::ajouter_blocs_ext(), Solveur_Masse_base::ajouter_masse(), Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::allocate_ephemere(), Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::allocate_paresseux(), Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::allocate_persistant(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_blocs(), Equation_base::assembler_blocs(), Convection_Diffusion_Temperature::assembler_blocs(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_blocs_avec_inertie(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::assembler_blocs_avec_inertie(), Convection_Diffusion_Espece_Binaire_base::assembler_blocs_avec_inertie(), Convection_Diffusion_Espece_Multi_QC::assembler_blocs_avec_inertie(), Convection_Diffusion_Espece_Multi_WC::assembler_blocs_avec_inertie(), Equation_base::assembler_blocs_avec_inertie(), Eval_Diff_VDF_Elem_aniso::associer(), Op_Conv_VDF_base::associer_champ_convecte_elem(), Op_Conv_VDF_base::associer_champ_convecte_face(), Source_base::associer_champ_rho(), Terme_Source_Acceleration_VDF_Face::associer_champ_rho(), Terme_Source_Acceleration_VEF_Face::associer_champ_rho(), Operateur_Diff_base::associer_diffusivite_pour_pas_de_temps(), Champ_base::associer_domaine_dis_base(), Milieu_base::associer_equation(), Operateur_Conv_base::associer_norme_vitesse(), Terme_Boussinesq_base::associer_pb(), Equation_base::calculer_champ_conserve(), Terme_Source_Canal_perio_VEF_P1NC::calculer_debit(), Fluide_base::calculer_e_int(), Champ_base::calculer_valeurs_som_compo_post(), Champ_base::calculer_valeurs_som_post(), Operateur_base::completer(), Navier_Stokes_Fluide_Dilatable_base::completer(), QDM_Multiphase::completer(), Op_Diff_VDF_base::completer(), Champ_Generique_Extraction::completer(), Champ_Generique_Gradient::completer(), Champ_Generique_Morceau_Equation::completer(), Champ_Generique_Transformation::completer(), Champ_Post_Operateur_Eqn::completer(), Chimie::completer(), Champ_front_contact_VEF::connectivity_failed(), Operateur_base::contribuer_a_avec(), Source_base::contribuer_a_avec(), Operateur_base::contribuer_termes_croises(), Champ_base::corriger_unite_nom_compo(), Champ_Fonc_MED::creer(), Champ_front_contact_VEF::creer(), Equation_base::creer_champ(), Postraitement::creer_champ_post_moreqn(), Operateur_base::dimensionner(), Source_base::dimensionner(), Solveur_Masse_base::dimensionner(), Op_Diff_K_Eps_Bas_Re_VDF_base::dimensionner_blocs(), Op_Diff_K_Eps_VDF_base::dimensionner_blocs(), Op_Diff_K_Omega_VDF_base::dimensionner_blocs(), Source_Transport_Eps_VDF_Elem::dimensionner_blocs(), Masse_DG_base::dimensionner_blocs(), Masse_PolyMAC_P0_Face::dimensionner_blocs(), Op_Diff_VDF_Elem_base::dimensionner_blocs(), Op_Diff_VDF_Face_base::dimensionner_blocs(), Op_Dift_VDF_Elem_base::dimensionner_blocs(), Op_Dift_VDF_Face_base::dimensionner_blocs(), Masse_VDF_base::dimensionner_blocs(), Perte_Charge_Singuliere_VDF_Face::dimensionner_blocs(), Op_Conv_EF_Stab_PolyMAC_P0_Face::dimensionner_blocs(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Face::dimensionner_blocs(), Op_Diff_PolyMAC_P0_Face::dimensionner_blocs(), Op_Grad_PolyMAC_P0_Face::dimensionner_blocs(), Op_Diff_DG_Elem::dimensionner_blocs(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::dimensionner_blocs(), Op_Diff_PolyMAC_P0_Elem::dimensionner_blocs(), Perte_Charge_Singuliere_PolyMAC_P0P1NC_Face::dimensionner_blocs(), Terme_Source_Decroissance_Radioactive_Elem_PolyMAC::dimensionner_blocs(), Op_Evanescence_Homogene_Face_base::dimensionner_blocs(), Source_Force_Tchen_base::dimensionner_blocs(), Source_Frottement_interfacial_base::dimensionner_blocs(), DP_Impose_VEF_Face::dimensionner_blocs(), Op_Conv_VDF_base::dimensionner_blocs_elem(), Op_Diff_PolyMAC_P0P1NC_Face::dimensionner_blocs_ext(), Op_Conv_VDF_base::dimensionner_blocs_face(), Operateur_base::dimensionner_termes_croises(), Equation_base::discretiser(), Champ_base::domaine_dis_base(), Eq_rayo_semi_transp_VDF::evaluer_cl_rayonnement(), Equation_base::expression_residu(), Convection_Diffusion_Temperature::get_champ(), Champ_Generique_Divergence::get_champ(), Champ_Generique_Extraction::get_champ(), Champ_Generique_refChamp::get_champ(), Equation_base::get_fonc_champ_conserve(), Ch_front_input::get_name(), Ch_front_input_uniforme::get_name(), Champ_input_P0::get_name(), Ch_input_uniforme::get_name(), Discretisation_base::get_name_of_type_for(), Champ_Inc_base::get_PDI_dname(), ICoCo::ProblemTrio::getDirectAccessToUnknown(), Ch_front_input::getTemplate(), Ch_front_input_uniforme::getTemplate(), Champ_input_P0::getTemplate(), Ch_input_uniforme::getTemplate(), Ch_front_input_P1::getTemplate(), Convection_Diffusion_Temperature::has_champ(), Source_PDF_EF::impr(), Op_EF_base::impr(), Op_VEF_Face::impr(), Equation_base::imprime_residu(), Champ_Fonc_Interp::init_fields(), Terme_Puissance_Thermique_Echange_Impose_Elem_base::initialiser(), Terme_Puissance_Thermique_Echange_Impose_VEF_Face::initialiser(), Champ_Fonc_Interp::initialiser(), Ecrire_Champ_MED::interpreter(), Simple::iterer_eqs(), Champ_Fonc_Tabule::le_champ_tabule_discretise(), Op_Correlation::le_nom(), Op_Ecart_type::le_nom(), Op_Moyenne::le_nom(), Equation_base::lire_cond_init(), Terme_Puissance_Thermique::lire_donnees(), Convection_Diffusion_Concentration::lire_motcle_non_standard(), Champ_Inc_base::mettre_a_jour(), Champ_Fonc_Interp::mettre_a_jour(), PlaqThVDF::mettre_a_jour(), Champ_front_contact_rayo_semi_transp_VEF::mettre_a_jour_flux_radiatif(), Op_VEF_Face::modifier_flux(), nom_compo(), Champ_Generique_refChamp::nommer_source(), Operateur_base::ouvrir_fichier(), Op_Diff_VEF_base::phi_psi_diffuse(), Op_Conv_EF_base::phi_u_transportant(), Op_Conv_VEF_base::phi_u_transportant(), Champ_Fonc_reprise_IJK::printOn(), Estimateur_Aposteriori_P0_VEF::printOn(), Champ_Elem_DG::printOn(), Champ_Fonc_Elem_DG::printOn(), Champ_Fonc_P1_DG::printOn(), Champ_Fonc_P0_EF::printOn(), Champ_Fonc_P1_EF::printOn(), Champ_Fonc_Q1_EF::printOn(), Champ_Fonc_Tabule_P0_EF::printOn(), Champ_P0_EF::printOn(), Champ_P1_EF::printOn(), Champ_Q1_EF::printOn(), Rotationnel_Champ_P1_EF::printOn(), Rotationnel_Champ_Q1_EF::printOn(), Y_plus_Champ_Q1::printOn(), Champ_front_fonc::printOn(), Champ_front_fonc_pois_ipsn::printOn(), Champ_front_fonc_pois_tube::printOn(), Champ_Fonc_P0_base::printOn(), Champ_Fonc_P1_base::printOn(), Champ_Fonc_Q1_base::printOn(), Champ_Inc_P0_base::printOn(), Champ_Inc_P1_base::printOn(), Champ_Inc_Q1_base::printOn(), Ch_front_var_instationnaire_dep::printOn(), Ch_front_var_instationnaire_indep::printOn(), Ch_front_var_stationnaire::printOn(), Champ_base::printOn(), Champ_front_base::printOn(), Champ_front_var::printOn(), Champ_front_var_instationnaire::printOn(), Champ_Fonc_MED::printOn(), Champ_Fonc_P0_MED::printOn(), Champ_Fonc_P1_MED::printOn(), Champ_Fonc_Q1_MED::printOn(), Champ_Fonc_reprise::printOn(), Champ_Elem_PolyMAC::printOn(), Champ_Elem_PolyMAC_P0::printOn(), Champ_Elem_PolyMAC_P0P1NC::printOn(), Champ_Face_PolyMAC::printOn(), Champ_Face_PolyMAC_P0::printOn(), Champ_Face_PolyMAC_P0P1NC::printOn(), Champ_Fonc_Elem_PolyMAC::printOn(), Champ_Fonc_Elem_PolyMAC_P0_rot::printOn(), Champ_Fonc_Elem_PolyMAC_P0_TC::printOn(), Champ_Fonc_Face_PolyMAC::printOn(), Champ_Fonc_Som_PolyMAC::printOn(), Champ_Fonc_Tabule_Elem_PolyMAC::printOn(), Champ_Som_PolyMAC::printOn(), grad_Champ_Face_PolyMAC_P0::printOn(), grad_U_Champ_Face_PolyMAC::printOn(), Champ_Face_VDF::printOn(), Champ_Fonc_Face_VDF::printOn(), Champ_Fonc_P0_VDF::printOn(), Champ_Fonc_P1_VDF::printOn(), Champ_Fonc_Q1_VDF::printOn(), Champ_Fonc_Tabule_P0_VDF::printOn(), Champ_P0_VDF::printOn(), Correlation_Vec_Sca_VDF::printOn(), Courant_maille_Champ_Face::printOn(), Critere_Q_Champ_Face::printOn(), grad_U_Champ_Face::printOn(), Reynolds_maille_Champ_Face::printOn(), Rotationnel_Champ_Face::printOn(), T_paroi_Champ_P0_VDF::printOn(), Taux_cisaillement_P0_VDF::printOn(), Y_plus_Champ_Face::printOn(), Champ_Fonc_P0_VEF::printOn(), Champ_Fonc_P1_isoP1Bulle::printOn(), Champ_Fonc_P1_VEF::printOn(), Champ_Fonc_P1NC::printOn(), Champ_Fonc_Q1_VEF::printOn(), Champ_Fonc_Q1NC::printOn(), Champ_Fonc_Tabule_P0_VEF::printOn(), Champ_P0_VEF::printOn(), Champ_P1NC::printOn(), Champ_Q1NC::printOn(), Correlation_Vec_Sca_VEF::printOn(), Critere_Q_Champ_P1NC::printOn(), grad_T_Champ_P1NC::printOn(), grad_U_Champ_P1NC::printOn(), h_conv_Champ_P1NC::printOn(), Rotationnel_Champ_P1NC::printOn(), Rotationnel_Champ_Q1NC::printOn(), T_paroi_Champ_P1NC::printOn(), Taux_cisaillement_P0_VEF::printOn(), Y_plus_Champ_P1NC::printOn(), Source_injection_masse_base::readOn(), Champ_Fonc_reprise_IJK::readOn(), Convection_Diffusion_Temperature_FT_Disc::readOn(), Sutherland::readOn(), List_Equations_Scalaires_Passifs_Especes::readOn(), Champ_Fonc_reprise::readOn(), Convection_Diffusion_Espece_Multi_base::readOn(), Convection_Diffusion_Concentration::readOn(), Convection_Diffusion_Temperature::readOn(), VDF_discretisation::residu(), VEF_discretisation::residu(), PolyMAC_P0_discretisation::residu(), PolyMAC_P0P1NC_discretisation::residu(), Eq_rayo_semi_transp_VDF::resoudre(), Eq_rayo_semi_transp_VEF::resoudre(), Moyenne_volumique::traiter_champs(), Champ_Fonc_Interp::update_fields(), Champ_Inc_base::valeur_aux_bords(), Champ_Face_PolyMAC::valeur_aux_elems_(), Champ_P1NC_implementation::valeur_aux_elems_compo_smooth(), Champ_P1NC_implementation::valeur_aux_elems_smooth(), and Equation_base::verifie_ch_init_nb_comp().
get_synonyms()
const Noms & Field_base::get_synonyms () const inline
References noms_synonymes_.
Referenced by Champs_compris_IJK::ajoute_champ_vectoriel(), and Champ_Generique_refChamp::get_property().
add_synonymous()
virtual void Field_base::add_synonymous (const Nom & nom) inline virtual
Reimplemented in IJK_Field_vector< T, N >, IJK_Field_vector< double, 3 >, IJK_Field_vector< int, 3 >, IJK_Field_vector< double, max_authorized_nb_of_groups_ >, and IJK_Field_vector< double, N >.
References TRUST_Vector< _CLASSE_ >::add(), and noms_synonymes_.
Referenced by IJK_Field_vector< T, N >::add_synonymous(), Navier_Stokes_std_ALE::discretiser(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::discretiser(), Navier_Stokes_std::discretiser(), Navier_Stokes_FTD_IJK::initialise_ns_fields(), Convection_Diffusion_Espece_Multi_base::readOn(), VDF_discretisation::t_paroi(), and VEF_discretisation::t_paroi().
nb_comp()
virtual int Field_base::nb_comp () const inline virtual
Reimplemented in Champ_front_Parametrique.
References nb_compo_.
Referenced by Champs_compris_IJK::ajoute_champ_vectoriel(), Integrale_tps_produit_champs::ajoute_produit_tensoriel(), Terme_Boussinesq_Sensibility_VEFPreP1B_Face::ajouter(), Source_Scalaire_EF::ajouter(), Terme_Boussinesq_VEFPreP1B_Face::ajouter(), Source_rayo_semi_transp_VDF_P0_VDF::ajouter(), Source_rayo_semi_transp_VEF_P1NC::ajouter(), Eval_Diff_VDF_Elem_aniso::associer(), Milieu_base::associer_gravite(), Champ_P1NC::calcul_h_conv(), Champ_front_xyz_debit::calculer_champ_vitesse(), Flux_radiatif_VDF::calculer_flux_radiatif(), Flux_radiatif_VEF::calculer_flux_radiatif(), Echange_contact_VDF::calculer_h_autre_pb(), Echange_contact_Correlation_VEF::calculer_h_solide(), Echange_contact_Correlation_VDF::calculer_h_solide(), Champ_front_xyz_debit::calculer_normales_et_integrale(), Loi_Paroi_Nu_Impose_VDF::calculer_scal(), Paroi_loi_WW_scal_VDF::calculer_scal(), Paroi_ODVM_scal_VDF::calculer_scal(), Loi_Paroi_Nu_Impose_VEF::calculer_scal(), Paroi_loi_WW_scal_VEF::calculer_scal(), Paroi_scal_analytique_VEF::calculer_scal(), ParoiVEF_TBLE_scal::calculer_scal(), Neumann_paroi_rayo_semi_transp_VDF::calculer_temperature_bord(), Calcul_Production_K_VEF::calculer_terme_destruction_K_gen(), Milieu_base::check_gravity_vector(), Source_base::completer(), Echange_contact_Correlation_VEF::completer(), Terme_Source_Constituant::completer(), Champ_Generique_Transformation::completer(), Op_Correlation::completer(), Op_Ecart_type::completer(), Champ_base::completer_post_champ(), Champ_P1NC::compo_normale_sortante(), Champ_Q1NC::compo_normale_sortante(), Paroi_scal_hyd_base_EF::compute_nusselt(), Paroi_scal_hyd_base_VDF::compute_nusselt(), Milieu_base::discretiser(), Flux_radiatif_VDF::evaluer_cl_rayonnement(), Flux_radiatif_VEF::evaluer_cl_rayonnement(), fixer_nom_compo(), fixer_unites(), Champ_Generique_Correlation::get_champ(), Champ_Generique_Ecart_Type::get_champ(), Champ_Generique_Extraction::get_champ(), Champ_Generique_Moyenne::get_champ(), Champ_Generique_Reduction_0D::get_champ(), Champ_Generique_Transformation::get_champ(), Champ_Generique_modifier_pour_QC::get_champ(), Champ_Generique_Interpolation::get_champ_with_calculer_champ_post(), Champ_Generique_Correlation::get_champ_without_evaluation(), Champ_Generique_Ecart_Type::get_champ_without_evaluation(), Champ_Generique_Extraction::get_champ_without_evaluation(), Champ_Generique_Interpolation::get_champ_without_evaluation(), Champ_Generique_Moyenne::get_champ_without_evaluation(), Champ_Generique_Reduction_0D::get_champ_without_evaluation(), Champ_Generique_modifier_pour_QC::get_champ_without_evaluation(), Discretisation_base::get_name_of_type_for(), Ch_front_input::getTemplate(), Ch_front_input_uniforme::getTemplate(), Champ_input_P0::getTemplate(), Ch_input_uniforme::getTemplate(), Ch_front_input_P1::getTemplate(), Domaine_Cl_EF::imposer_cond_lim(), Domaine_Cl_VEF::imposer_cond_lim(), Champ_Q4_implementation::imprime_Q4(), Loi_Paroi_Nu_Impose_VDF::imprimer_nusselt(), Loi_Paroi_Nu_Impose_VEF::imprimer_nusselt(), Postraitement::init(), Echange_contact_PolyMAC::initialiser(), Echange_contact_VDF::initialiser(), Champ_front_fonc_pois_ipsn::initialiser(), Champ_front_fonc_pois_tube::initialiser(), Champ_front_lu::initialiser(), Ch_front_input_P1::initialiser(), Ch_front_var_instationnaire_dep::initialiser(), Champ_front_instationnaire_base::initialiser(), Champ_front_var::initialiser(), Champ_front_softanalytique::initialiser(), Champ_front_xyz_debit::initialiser(), Champ_front_xyz_debit::initialiser_coefficient(), Postraitement::lire_champs_a_postraiter(), Navier_Stokes_std::lire_cond_init(), QDM_Multiphase::lire_cond_init(), Terme_Puissance_Thermique::lire_donnees(), Paroi_UTAU_IMP_Impl::lire_donnees(), Convection_Diffusion_Turbulent::lire_op_diff_turbulent(), Navier_Stokes_Turbulent_ALE::lire_op_diff_turbulent(), Transport_2eq_base::lire_op_diff_turbulent(), Navier_Stokes_IBM_Turbulent::lire_op_diff_turbulent(), Navier_Stokes_Turbulent::lire_op_diff_turbulent(), Champ_Uniforme_Morceaux_Tabule_Temps::me_calculer(), Ch_front_input_ALE::mettre_a_jour(), Champ_front_ALE::mettre_a_jour(), Echange_contact_rayo_semi_transp_VDF::mettre_a_jour(), Champ_front_bruite::mettre_a_jour(), Champ_front_t::mettre_a_jour(), Champ_front_txyz::mettre_a_jour(), Champ_front_synt::mettre_a_jour(), Champ_front_debit_QC::mettre_a_jour(), Champ_front_debit_QC_fonc_t::mettre_a_jour(), Echange_contact_VDF_FT_Disc::mettre_a_jour(), Echange_contact_VDF_FT_Disc_solid::mettre_a_jour(), Echange_contact_Rayo_transp_VDF::mettre_a_jour(), Echange_contact_VDF::mettre_a_jour(), Iterateur_PolyMAC_Elem< _TYPE_ >::modifier_flux(), Eq_rayo_semi_transp_VDF::modifier_matrice(), Eq_rayo_semi_transp_VEF::modifier_matrice(), Champ_Fonc_P0_base::moyenne(), Champ_P0_VDF::moyenne(), Champ_front_Parametrique::nb_comp(), Constituant::nb_constituants(), nom_compo(), Champ_P1NC::norme_H1(), Terme_Source_Constituant::ouvrir_fichier(), Champ_Generique_Transformation::preparer_macro(), Source_injection_masse_base::readOn(), Champ_Fonc_reprise_IJK::readOn(), Loi_Paroi_Nu_Impose_VDF::readOn(), Loi_Paroi_Nu_Impose_VEF::readOn(), Source_Qdm_EF::readOn(), Source_Scalaire_EF::readOn(), Champ_front_debit::readOn(), Champ_front_xyz_debit::readOn(), Champ_Input_P0_Composite::readOn(), Champ_front_MED::readOn(), Champ_Fonc_reprise::readOn(), Perte_Charge_Anisotrope_PolyMAC_Face::readOn(), Perte_Charge_Circulaire_PolyMAC_Face::readOn(), Perte_Charge_Directionnelle_PolyMAC_Face::readOn(), Terme_Source_Qdm_Face_PolyMAC::readOn(), Perte_Charge_Gen::readOn(), Perte_Charge_Anisotrope_VDF_Face::readOn(), Perte_Charge_Circulaire_VDF_Face::readOn(), Perte_Charge_Directionnelle_VDF_Face::readOn(), Terme_Source_Qdm_VDF_Face::readOn(), Perte_Charge_Anisotrope_VEF_P1NC::readOn(), Perte_Charge_Circulaire_VEF_P1NC::readOn(), Perte_Charge_Directionnelle_VEF_P1NC::readOn(), Perte_Charge_VEF::readOn(), Terme_Source_Qdm_VEF_Face::readOn(), Ch_front_input_ALE::remplir_vit_som_bord_ALE(), Champ_front_ALE::remplir_vit_som_bord_ALE(), Champ_front_ALE_Beam::remplir_vit_som_bord_ALE(), Ch_front_input_ALE::setValue(), Champ_Face_PolyMAC::trace(), Champ_Face_PolyMAC_P0::trace(), Champ_Face_PolyMAC_P0P1NC::trace(), Moyenne_volumique::traiter_champs(), Echange_contact_PolyMAC::update_coeffs(), Echange_contact_PolyMAC::update_delta(), Champ_front_softanalytique::valeur_a(), Champ_base::valeur_a_compo(), Champ_implementation_P0::valeur_a_elem(), Champ_implementation_sommet::valeur_a_elem(), Champ_Q4_implementation::valeur_a_elem(), Champ_P1NC_implementation::valeur_a_elem(), Champ_Q1NC_implementation::valeur_a_elem(), Champ_Q4_implementation::valeur_a_elem_compo(), Champ_implementation_P0::valeur_a_elem_compo(), Champ_implementation_sommet::valeur_a_elem_compo(), TRUSTChamp_Divers_generique< _TYPE_ >::valeur_aux(), Champ_implementation_P0::valeur_aux_centres_de_gravite(), Champ_P1NC_implementation::valeur_aux_centres_de_gravite(), Champ_base::valeur_aux_compo(), TRUSTChamp_Divers_generique< _TYPE_ >::valeur_aux_elems(), Champ_Q4_implementation::valeur_aux_elems(), Champ_P1iP1B_implementation::valeur_aux_elems(), Champ_P1NC_implementation::valeur_aux_elems(), Champ_Q1NC_implementation::valeur_aux_elems(), Champ_implementation_P0::valeur_aux_elems(), Champ_Fonc_Face_PolyMAC::valeur_aux_elems(), Champ_Face_PolyMAC::valeur_aux_elems_(), Champ_Q4_implementation::valeur_aux_elems_compo(), Champ_implementation_sommet::valeur_aux_elems_compo(), Champ_P1NC_implementation::valeur_aux_elems_compo_smooth(), Champ_P1NC_implementation::valeur_aux_elems_smooth(), Champ_Face_PolyMAC::valeur_aux_faces(), Champ_Face_PolyMAC_P0P1NC::valeur_aux_faces(), Champ_Fonc_Face_PolyMAC::valeur_aux_faces(), Champ_Q4_implementation::valeur_aux_sommets(), Champ_P1iP1B_implementation::valeur_aux_sommets(), Champ_Q1NC_implementation::valeur_aux_sommets(), Champ_P1NC_implementation::valeur_aux_sommets(), Champ_Q4_implementation::valeur_aux_sommets_compo(), Champ_implementation_P0::valeur_aux_sommets_compo_impl(), Champ_implementation_sommet::valeur_aux_sommets_compo_impl(), Champ_implementation_P0::valeur_aux_sommets_impl(), Champ_Front_Composite::valeurs_face(), Echange_global_impose_rayo_semi_transp::verifie_ch_init_nb_comp(), Dirichlet::verifie_ch_init_nb_comp(), Echange_externe_impose::verifie_ch_init_nb_comp(), Neumann_paroi::verifie_ch_init_nb_comp(), Neumann_sortie_libre::verifie_ch_init_nb_comp(), Equation_base::verifie_ch_init_nb_comp(), Champ_P1NC::verifie_valeurs_cl(), Champ_Q1NC::verifie_valeurs_cl(), and Ecrire_fichier_xyz_valeur::write_fields().
fixer_nb_comp()
void Field_base::fixer_nb_comp (int i) virtual
Fixe le nombre de composantes du champ.
Le champ est vectoriel s'il est de meme dimension que l'espace.
Parameters
(int i) le nombre de composantes du champs
Reimplemented in Champ_front_Parametrique.
References Objet_U::dimension, TRUST_Vector< _CLASSE_ >::dimensionner(), fixer_nature_du_champ(), nb_compo_, and noms_compo_.
Referenced by Op_Diff_RotRot::associer(), Modele_turbulence_hyd_LES_DSGS_VDF::associer(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::associer(), EOS_Tools_VDF::associer_domaines(), Modele_turbulence_hyd_RANS_Gen< MODELE >::complete_viscosity_field(), Echange_contact_VDF_FT_Disc::completer(), Echange_contact_rayo_semi_transp_VDF::completer(), Neumann_paroi_rayo_semi_transp_VDF::completer(), Neumann_paroi_rayo_semi_transp_VEF::completer(), Echange_global_impose::completer(), Paroi_Knudsen_non_negligeable::completer(), Echange_couplage_thermique::completer(), Op_Correlation::completer(), Op_Ecart_type::completer(), Champ_front_contact_VEF::connectivity_failed(), VDF_discretisation::courant_maille(), Champ_Fonc_MED::creer(), Champ_front_calc::creer(), EF_discretisation::creer_champ_vorticite(), PolyMAC_P0_discretisation::creer_champ_vorticite(), VDF_discretisation::creer_champ_vorticite(), VEF_discretisation::creer_champ_vorticite(), VDF_discretisation::critere_Q(), VEF_discretisation::critere_Q(), Champ_Don_base::dimensionner(), Modele_rayo_semi_transp::discretiser(), EF_discretisation::distance_paroi(), PolyMAC_discretisation::distance_paroi(), VEF_discretisation::distance_paroi(), Champ_front_Parametrique::fixer_nb_comp(), Champ_Generique_Extraction::get_champ(), VDF_discretisation::grad_u(), VEF_discretisation::grad_u(), PolyMAC_discretisation::grad_u(), PolyMAC_P0_discretisation::grad_u(), VEF_discretisation::h_conv(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::IJK_Field_local_template(), Echange_contact_PolyMAC::initialiser(), Echange_contact_VDF::initialiser(), Traitement_particulier_NS_Pression_VDF::lire(), Traitement_particulier_NS_Brech_VEF::lire(), Traitement_particulier_NS_Pression_VEF::lire(), Terme_Puissance_Thermique::lire_donnees(), Champ_Fonc_MED_Table_Temps::lire_donnees_champ(), PlaqThVDF::mettre_a_jour(), IJK_Field_vector< T, N >::nommer(), VDF_discretisation::proprietes_physiques_fluide_Ostwald(), VEF_discretisation::proprietes_physiques_fluide_Ostwald(), Champ_front_ALE::readOn(), Champ_front_ALE_projection::readOn(), Champ_Fonc_reprise_IJK::readOn(), Paroi_FT_disc::readOn(), Echange_contact_VDF_FT_Disc::readOn(), Echange_contact_VDF_FT_Disc_solid::readOn(), Champ_front_contact_rayo_transp_VEF::readOn(), Flux_radiatif_base::readOn(), Champ_front_contact_rayo_semi_transp_VEF::readOn(), Boundary_field_keps_from_ud::readOn(), Boundary_field_uniform_keps_from_ud::readOn(), Field_uniform_keps_from_ud::readOn(), Ch_front_Vortex::readOn(), Champ_Fonc_Fonction::readOn(), Champ_Fonc_Fonction_txyz::readOn(), Champ_Fonc_Tabule::readOn(), Champ_front_bruite::readOn(), Champ_front_calc::readOn(), Champ_Front_Composite::readOn(), Champ_front_debit::readOn(), Champ_front_fonc_pois_ipsn::readOn(), Champ_front_fonc_pois_tube::readOn(), Champ_Front_Fonction::readOn(), Champ_front_lu::readOn(), Champ_Front_MUSIG::readOn(), Champ_front_normal::readOn(), Champ_front_t::readOn(), Champ_front_Tabule::readOn(), Champ_front_tangentiel::readOn(), Champ_front_txyz::readOn(), Champ_front_uniforme::readOn(), Champ_front_xyz_debit::readOn(), Champ_Composite::readOn(), Champ_Fonc_Tabule_Morceaux::readOn(), Champ_MUSIG::readOn(), Champ_som_lu::readOn(), Champ_Uniforme_Morceaux::readOn(), Init_par_partie::readOn(), Symetrie::readOn(), Ch_front_var_instationnaire_dep::readOn(), Champ_front_var::readOn(), Champ_Parametrique::readOn(), Champ_front_MED::readOn(), Champ_Fonc_reprise::readOn(), Champ_front_softanalytique::readOn(), Echange_contact_PolyMAC::readOn(), Echange_contact_PolyMAC_P0P1NC::readOn(), Champ_front_pression_from_u::readOn(), Champ_front_synt::readOn(), Dirichlet_paroi_fixe::readOn(), Paroi_Knudsen_non_negligeable::readOn(), Sortie_libre_pression_moyenne_imposee::readOn(), Paroi_decalee_Robin::readOn(), Champ_front_debit_QC::readOn(), Champ_front_debit_QC_fonc_t::readOn(), Champ_front_fonc_gradient_VDF::readOn(), Echange_contact_Correlation_VDF::readOn(), Echange_contact_VDF::readOn(), Sortie_libre_Pression_imposee_Orlansky::readOn(), Champ_front_contact_VEF::readOn(), Champ_front_fonc_gradient_VEF::readOn(), Champ_front_tangentiel_VEF::readOn(), Echange_contact_Correlation_VEF::readOn(), Sortie_libre_Gradient_Pression_libre_VEF::readOn(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::readOn(), VDF_discretisation::reynolds_maille(), Ch_front_input::set_nb_comp(), Ch_front_input_uniforme::set_nb_comp(), Champ_input_P0::set_nb_comp(), Ch_input_uniforme::set_nb_comp(), VDF_discretisation::t_paroi(), VEF_discretisation::t_paroi(), PolyMAC_P0_discretisation::taux_cisaillement(), VDF_discretisation::taux_cisaillement(), VEF_discretisation::taux_cisaillement(), EF_discretisation::vorticite(), VDF_discretisation::vorticite(), VEF_discretisation::vorticite(), VDF_discretisation::y_plus(), EF_discretisation::y_plus(), and VEF_discretisation::y_plus().
noms_compo()
const Noms & Field_base::noms_compo () const
Renvoie le tableau des noms des composantes du champ.
References noms_compo_.
Referenced by Operateur_base::completer(), Terme_Source_Constituant::completer(), Op_Correlation::completer(), Champ_base::completer_post_champ(), Postraitement::creer_champ_post_stat(), Champ_Generique_Correlation::get_property(), Champ_Generique_refChamp::get_property(), Modele_turbulence_hyd_0_eq_base::imprimer(), Ecrire_Champ_MED::interpreter(), Terme_Source_Constituant::ouvrir_fichier(), Operateur_base::ouvrir_fichier(), and Moyenne_volumique::traiter_champs().
nom_compo() [1/2]
const Nom & Field_base::nom_compo (int i) const
Renvoie le nom de la ieme composante du champ.
Parameters
(int i) l'index de la composante du champ dont on veut specifier le nom
Returns
(Nom& nom) le nom de i-eme composante du champ
Exceptions
index de la composante du champ invalide
References nb_comp(), and noms_compo_.
Referenced by Equation_base::expression_residu().
nom_compo() [2/2]
const Nom & Field_base::nom_compo () const
Renvoie le nom d'un champ scalaire.
References le_nom(), and nb_comp().
Referenced by Champ_base::corriger_unite_nom_compo(), and IJK_Field_vector< T, N >::nommer().
fixer_noms_compo()
const Noms & Field_base::fixer_noms_compo (const Noms & noms) virtual
Fixe le nom des composantes du champ.
Parameters
(Noms& noms) le tableau des noms a donner aux composantes du champ
Returns
(Noms&) le tableau des noms des composantes du champ
References noms_compo_.
Referenced by Modele_turbulence_hyd_0_eq_base::completer(), Op_Correlation::completer(), Champ_base::corriger_unite_nom_compo(), EF_discretisation::discretiser_champ(), PolyMAC_discretisation::discretiser_champ(), PolyMAC_P0P1NC_discretisation::discretiser_champ(), VDF_discretisation::discretiser_champ(), and IJK_Field_vector< T, N >::nommer().
fixer_nom_compo() [1/2]
const Nom & Field_base::fixer_nom_compo (int i, const Nom & nom) virtual
Fixe le nom de la i-eme composante du champ.
Parameters
(int i) l'index de la composante du champ dont on veut specifier le nom
(Nom& nom) le nom a donner a la i-eme composante du champ
Returns
(Nom&) le nom de i-eme composante du champ
Exceptions
index de la composante du champ invalide
References nb_comp(), and noms_compo_.
Referenced by Discret_Thyd::concentration(), VDF_discretisation::courant_maille(), EF_discretisation::creer_champ_vorticite(), PolyMAC_P0_discretisation::creer_champ_vorticite(), VDF_discretisation::creer_champ_vorticite(), VEF_discretisation::creer_champ_vorticite(), Echelle_temporelle_turbulente::discretiser(), Energie_cinetique_turbulente::discretiser(), Energie_cinetique_turbulente_WIT::discretiser(), Taux_dissipation_turbulent::discretiser(), Aire_interfaciale::discretiser(), Energie_Multiphase::discretiser(), Energie_Multiphase_Enthalpie::discretiser(), Masse_Multiphase::discretiser(), VDF_discretisation::grad_u(), VEF_discretisation::grad_u(), PolyMAC_discretisation::grad_u(), PolyMAC_P0_discretisation::grad_u(), Terme_Puissance_Thermique::lire_donnees(), Source_injection_masse_base::readOn(), VDF_discretisation::reynolds_maille(), PolyMAC_P0_discretisation::taux_cisaillement(), EF_discretisation::vorticite(), VDF_discretisation::vorticite(), and VEF_discretisation::vorticite().
fixer_nom_compo() [2/2]
const Nom & Field_base::fixer_nom_compo (const Nom & nom) virtual
Fixe le nom d'un champ scalaire.
Parameters
(Nom& nom) le nom a donner au champ (scalaire)
Returns
(Nom&) le nom du champ scalaire
Exceptions
le champ n'est pas scalaire
References TRUST_Vector< _CLASSE_ >::dimensionner_force(), nb_comp(), nommer(), and noms_compo_.
unites()
const Noms & Field_base::unites () const
Renvoie les unites des composantes du champ.
Returns
(Noms&) les noms des unites des composantes du champ
References unite_.
Referenced by Op_Ecart_type::completer(), Champ_Generique_Correlation::get_property(), Champ_Generique_refChamp::get_property(), Modele_turbulence_hyd_0_eq_base::imprimer(), Ecrire_Champ_MED::interpreter(), and Moyenne_volumique::traiter_champs().
unite() [1/2]
const Nom & Field_base::unite () const
Renvoie l'unite d'un champ scalaire dont toutes les composantes ont la meme unite.
Returns
(Nom&) l'unite (commune) des composantes du champ
References TRUST_Vector< _CLASSE_ >::size(), and unite_.
Referenced by Operateur_Diff_base::associer_diffusivite_pour_pas_de_temps(), Operateur_Conv_base::associer_norme_vitesse(), and Op_Ecart_type::completer().
unite() [2/2]
const Nom & Field_base::unite (int i) const
Renvoie l'unite de la i-eme composante du champ.
Parameters
(int i) l'index de la composante du champ dont on veut connaitre l'unite
Returns
(Nom&) l'unite de la i-eme composante du champ
References unite_.
fixer_unites()
const Noms & Field_base::fixer_unites (const Noms & noms) virtual
Specifie les unites des composantes du champ.
Ces unites sont specifiees grace a un tableau de Nom et peuvent etre differentes pour chaque composante du champ.
Parameters
(Noms& noms) les noms des unites des composantes du champ
References TRUST_Vector< _CLASSE_ >::dimensionner_force(), fixer_nature_du_champ(), nb_comp(), and unite_.
Referenced by Modele_turbulence_hyd_0_eq_base::completer(), Op_Correlation::completer(), Op_Ecart_type::completer(), EF_discretisation::discretiser_champ(), PolyMAC_discretisation::discretiser_champ(), PolyMAC_P0P1NC_discretisation::discretiser_champ(), and VDF_discretisation::discretiser_champ().
fixer_unite() [1/2]
const Nom & Field_base::fixer_unite (const Nom & nom) virtual
Specifie l'unite d'un champ scalaire ou dont toutes les composantes ont la meme unite.
Parameters
(Nom& nom) l'unite a specifier
Returns
(Nom&) l'unite du champ
Reimplemented in Champ_Input_P0_Composite.
References TRUST_Vector< _CLASSE_ >::dimensionner_force(), and unite_.
Referenced by Op_Diff_RotRot::associer(), Modele_turbulence_hyd_LES_DSGS_VDF::associer(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::associer(), Champ_base::Champ_base(), Modele_turbulence_hyd_RANS_Gen< MODELE >::complete_viscosity_field(), Op_Correlation::completer(), Op_Ecart_type::completer(), VDF_discretisation::courant_maille(), EF_discretisation::creer_champ_vorticite(), PolyMAC_P0_discretisation::creer_champ_vorticite(), VDF_discretisation::creer_champ_vorticite(), VEF_discretisation::creer_champ_vorticite(), VDF_discretisation::critere_Q(), VEF_discretisation::critere_Q(), Equation_rayonnement_base::discretiser(), Modele_rayo_semi_transp::discretiser(), EF_discretisation::distance_paroi(), PolyMAC_discretisation::distance_paroi(), VEF_discretisation::distance_paroi(), Champ_Input_P0_Composite::fixer_unite(), VDF_discretisation::grad_u(), VEF_discretisation::grad_u(), PolyMAC_discretisation::grad_u(), PolyMAC_P0_discretisation::grad_u(), VEF_discretisation::h_conv(), Traitement_particulier_NS_Pression_VDF::lire(), Traitement_particulier_NS_Brech_VEF::lire(), Traitement_particulier_NS_Pression_VEF::lire(), Discretisation_base::nommer_completer_champ_physique(), VDF_discretisation::reynolds_maille(), VDF_discretisation::t_paroi(), VEF_discretisation::t_paroi(), PolyMAC_P0_discretisation::taux_cisaillement(), VDF_discretisation::taux_cisaillement(), VEF_discretisation::taux_cisaillement(), EF_discretisation::vorticite(), VDF_discretisation::vorticite(), VEF_discretisation::vorticite(), VDF_discretisation::y_plus(), EF_discretisation::y_plus(), and VEF_discretisation::y_plus().
fixer_unite() [2/2]
const Nom & Field_base::fixer_unite (int i, const Nom & nom) virtual
Specifie l'unite de la i-eme composante du champ Signification: l'index de la composante du champ dont on veut specifier l'unite.
Parameters
(Nom& nom) le type de l'unite a specifier
Returns
(Nom&) le type de l'unite de la i-eme composante du champ
Reimplemented in Champ_Input_P0_Composite.
References fixer_nature_du_champ(), and unite_.
nature_du_champ()
virtual Nature_du_champ Field_base::nature_du_champ () const inline virtual
Reimplemented in Champ_front_Parametrique.
References nature_.
Referenced by Op_Diff_EF::ajouter(), Op_Dift_EF_Q1::ajouter(), Op_Diff_VEF_Anisotrope_Face::ajouter(), Op_Diff_VEF_Face::ajouter(), Solveur_Masse_EF::appliquer_impl(), Masse_VEF_P1NC::appliquer_impl(), Op_Diff_VEFP1NCP1B_Face::associer(), Op_Dift_EF_Q1::calculer_dt_stab(), Champ_Generique_Transformation::completer(), Champ_base::completer_post_champ(), Op_Diff_VEF_Anisotrope_Face::contribuer_a_avec(), Op_Diff_VEF_Face::contribuer_a_avec(), Op_Diff_VEF_Face_Stab::contribuer_a_avec(), Champ_Generique_Ecart_Type::get_champ(), Champ_Generique_Extraction::get_champ(), Champ_Generique_Moyenne::get_champ(), Champ_Generique_Reduction_0D::get_champ(), Champ_Generique_modifier_pour_QC::get_champ(), Champ_Generique_Tparoi_VEF::get_champ(), Champ_Generique_Interpolation::get_champ_with_calculer_champ_post(), Champ_Generique_Ecart_Type::get_champ_without_evaluation(), Champ_Generique_Extraction::get_champ_without_evaluation(), Champ_Generique_Interpolation::get_champ_without_evaluation(), Champ_Generique_Moyenne::get_champ_without_evaluation(), Champ_Generique_Reduction_0D::get_champ_without_evaluation(), Champ_Generique_modifier_pour_QC::get_champ_without_evaluation(), Champ_Generique_Tparoi_VEF::get_champ_without_evaluation(), Domaine_Cl_DG::imposer_cond_lim(), Domaine_Cl_EF::imposer_cond_lim(), Domaine_Cl_PolyMAC::imposer_cond_lim(), Domaine_Cl_VDF::imposer_cond_lim(), Domaine_Cl_VEF::imposer_cond_lim(), Postraitement::init(), Op_EF_base::modifier_pour_Cl(), Op_VEF_Face::modifier_pour_Cl(), Champ_front_Parametrique::nature_du_champ(), Postraitement::postprocess_field_values(), Postprocessing_IJK::postraiter_champs(), Champ_Generique_Transformation::preparer_macro(), Domaine_Cl_EF::remplir_type_elem_Cl(), Moyenne_volumique::traiter_champs(), and Equation_base::verifie_ch_init_nb_comp().
fixer_nature_du_champ()
Nature_du_champ Field_base::fixer_nature_du_champ (Nature_du_champ n) virtual
Fixer la nature d'un champ: scalaire, multiscalaire, vectoriel.
Le type (enum) Nature_du_champ est defini dans Ch_base.h.
Parameters
(Nature_du_champ n) la nature a donner au champ
Reimplemented in Champ_front_Parametrique.
References nature_.
Referenced by Solveur_Masse_EF::ajouter_masse(), Masse_VEF_P1NC::ajouter_masse(), Champ_base::Champ_base(), Discret_Thyd::concentration(), PolyMAC_P0_discretisation::creer_champ_vorticite(), Echelle_temporelle_turbulente::discretiser(), Energie_cinetique_turbulente::discretiser(), Energie_cinetique_turbulente_WIT::discretiser(), Taux_dissipation_turbulent::discretiser(), Aire_interfaciale::discretiser(), Energie_Multiphase::discretiser(), Energie_Multiphase_Enthalpie::discretiser(), Masse_Multiphase::discretiser(), Milieu_base::discretiser(), DG_discretisation::discretiser_champ(), EF_discretisation::discretiser_champ(), PolyMAC_discretisation::discretiser_champ(), PolyMAC_P0P1NC_discretisation::discretiser_champ(), VDF_discretisation::discretiser_champ(), Champ_front_Parametrique::fixer_nature_du_champ(), fixer_nb_comp(), fixer_unite(), fixer_unites(), Champ_Generique_Extraction::get_champ(), VDF_discretisation::grad_u(), VEF_discretisation::grad_u(), PolyMAC_discretisation::grad_u(), PolyMAC_P0_discretisation::grad_u(), and PolyMAC_P0_discretisation::taux_cisaillement().
Member Data Documentation
info_obj
const Type_info Field_base::info_obj static
nom_
Nom Field_base::nom_ protected
Referenced by Champ_Elem_DG::associer_domaine_dis_base(), Champ_Fonc_base::get_pdi_name(), le_nom(), nommer(), Champ_Fonc_Interp::readOn(), Champ_base::readOn(), Champ_Fonc_base::reprendre(), Champ_Inc_base::reprendre(), Champ_Fonc_reprise_IJK::reprendre_IJK(), Champ_Fonc_base::sauvegarder(), and Champ_Inc_base::sauvegarder().
noms_synonymes_
Noms Field_base::noms_synonymes_ protected
Referenced by add_synonymous(), and get_synonyms().
noms_compo_
Noms Field_base::noms_compo_ protected
Referenced by fixer_nb_comp(), fixer_nom_compo(), fixer_noms_compo(), nom_compo(), and noms_compo().
unite_
Noms Field_base::unite_ protected
Referenced by Champ_base::corriger_unite_nom_compo(), fixer_unite(), fixer_unites(), unite(), and unites().
nb_compo_
int Field_base::nb_compo_ protected
Referenced by Champ_Fonc_Face_PolyMAC::affecter_(), Champ_P1NC::affecter_(), Champ_front_recyclage::calcul_moyenne_imposee(), Champ_front_recyclage::calcul_moyenne_recyclee(), Champ_base::calculer_valeurs_elem_post(), Champ_base::calculer_valeurs_som_post(), Champ_base::Champ_base(), Champ_base::corriger_unite_nom_compo(), Champ_Fonc_base::creer_tableau_distribue(), Champ_Inc_base::creer_tableau_distribue(), Champ_val_tot_sur_vol_base::evaluer(), fixer_nb_comp(), Champ_Face_PolyMAC::fixer_nb_valeurs_nodales(), Champ_Face_PolyMAC_P0::fixer_nb_valeurs_nodales(), Champ_Face_PolyMAC_P0P1NC::fixer_nb_valeurs_nodales(), Champ_Fonc_Face_PolyMAC::fixer_nb_valeurs_nodales(), grad_Champ_Face_PolyMAC_P0::fixer_nb_valeurs_nodales(), Champ_Don_base::fixer_nb_valeurs_nodales(), Champ_Ostwald::fixer_nb_valeurs_nodales(), Champ_Face_VDF::fixer_nb_valeurs_nodales(), Champ_Fonc_Face_VDF::fixer_nb_valeurs_nodales(), IJK_Field_vector< T, N >::IJK_Field_vector(), Champ_Elem_DG::imprime(), Champ_Fonc_P1_EF::imprime(), Champ_Fonc_Q1_EF::imprime(), Champ_P0_EF::imprime(), Champ_P1_EF::imprime(), Champ_Q1_EF::imprime(), Champ_Elem_PolyMAC::imprime(), Champ_Fonc_Som_PolyMAC::imprime(), Champ_Som_PolyMAC::imprime(), Champ_Fonc_P0_VDF::imprime(), Champ_Fonc_Q1_VDF::imprime(), Champ_Fonc_Q1_VEF::imprime(), Champ_P0_VDF::imprime(), Champ_front_recyclage::initialiser(), Champ_Fonc_Interp::initialiser(), Champ_front_recyclage::initialiser_moyenne_imposee(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::k_layer(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::k_stride(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::linear_index(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::linear_index_relaxed_test(), Champ_front_recyclage::lire_fichier_format2(), Champ_front_recyclage::mettre_a_jour(), nb_comp(), Champ_Fonc_reprise_IJK::readOn(), Champ_Front_Composite::readOn(), Champ_Front_MUSIG::readOn(), Champ_input_P0::readOn(), Ch_input_uniforme::readOn(), Champ_Tabule_Temps::readOn(), Champ_Fonc_reprise::readOn(), Champ_input_P0::setValue(), Champ_Fonc_Interp::update_fields(), champ_init_canal_sinal::valeur_a(), champ_init_canal_sinal::valeur_aux(), Champ_som_lu::valeur_aux_elems(), Champ_som_lu_VEF::valeur_aux_elems(), Champ_front_base::valeurs_face(), Champ_Front_Composite::valeurs_face(), Champ_front_uniforme::valeurs_face(), and Champ_front_instationnaire_base::valeurs_face().
nature_
Nature_du_champ Field_base::nature_ protected
Referenced by fixer_nature_du_champ(), IJK_Field_vector< T, N >::IJK_Field_vector(), Champ_Fonc_Interp::init_fields(), nature_du_champ(), and Champ_Fonc_Interp::readOn().