TrioCFD: Convection_Diffusion_Fluide_Dilatable_base Class Reference
Convection_Diffusion_Fluide_Dilatable_base Class Reference abstract
#include <Convection_Diffusion_Fluide_Dilatable_base.h>
Public Member Functions
const Type_info * get_info () const override
int impr (Sortie &os) const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
Public Member Functions inherited from Convection_Diffusion_std
void associer_vitesse (const Champ_base &)
const Type_info * get_info () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
int nombre_d_operateurs () const override
const Operateur & operateur (int) const override
Operateur & operateur (int) override
const Champ_Inc_base & vitesse_transportante () const
Public Member Functions inherited from Equation_base
virtual void abortTimeStep ()
virtual void associer_domaine_dis (const Domaine_dis_base &)
virtual void associer_pb_base (const Probleme_base &)
virtual void associer_sch_tps_base (const Schema_Temps_base &)
virtual double calculer_pas_de_temps () const
virtual void completer ()
virtual std::vector< YAML_data > data_a_sauvegarder () const
DoubleTab & derivee_en_temps_conv (DoubleTab &, const DoubleTab &)
virtual DoubleTab & derivee_en_temps_inco (DoubleTab &)
const Discretisation_base & discretisation () const
virtual void discretiser ()
virtual const Motcle & domaine_application () const
virtual Domaine_Cl_dis_base & domaine_Cl_dis ()
virtual const Domaine_Cl_dis_base & domaine_Cl_dis () const
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual void imprimer (Sortie &os) const
virtual bool initTimeStep (double dt)
const Nom & le_nom () const override
int limpr () const
virtual void mettre_a_jour (double temps)
virtual int preparer_calcul ()
Probleme_base & probleme ()
const Probleme_base & probleme () const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Schema_Temps_base & schema_temps ()
const Schema_Temps_base & schema_temps () const
Solveur_Masse_base & solv_masse ()
const Solveur_Masse_base & solv_masse () const
Sources & sources ()
const Sources & sources () const
virtual void valider_iteration ()
virtual void verifie_ch_init_nb_comp (const Champ_Inc_base &ch_ref, const int nb_comp) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Convection_Diffusion_std
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Equation_base
virtual Entree & lire_cl (Entree &)
virtual Entree & lire_cond_init (Entree &)
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual Entree & lire_sources (Entree &)
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
virtual int verif_Cl () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Convection_Diffusion_Fluide_Dilatable_Proto
DoubleTab & derivee_en_temps_inco_sans_solveur_masse_impl (Convection_Diffusion_Fluide_Dilatable_base &eqn, DoubleTab &derivee, const bool is_expl)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
See also
Conv_Diffusion_std Convection_Diffusion_Temperature
Constructor & Destructor Documentation
Convection_Diffusion_Fluide_Dilatable_base()
Convection_Diffusion_Fluide_Dilatable_base::Convection_Diffusion_Fluide_Dilatable_base ()
~Convection_Diffusion_Fluide_Dilatable_base()
Convection_Diffusion_Fluide_Dilatable_base::~Convection_Diffusion_Fluide_Dilatable_base () override
Member Function Documentation
info()
const Type_info * Convection_Diffusion_Fluide_Dilatable_base::info () static
get_info()
const Type_info * Convection_Diffusion_Fluide_Dilatable_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Equation_base.
Reimplemented in Convection_Diffusion_Chaleur_QC, Convection_Diffusion_Espece_Binaire_QC, Convection_Diffusion_Espece_Multi_QC, Convection_Diffusion_Chaleur_WC, Convection_Diffusion_Espece_Binaire_WC, Convection_Diffusion_Espece_Multi_WC, Convection_Diffusion_Chaleur_Turbulent_QC, Convection_Diffusion_Espece_Binaire_Turbulent_QC, and Convection_Diffusion_Espece_Multi_Turbulent_QC.
self_cast() [1/2]
Convection_Diffusion_Fluide_Dilatable_base & Convection_Diffusion_Fluide_Dilatable_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Convection_Diffusion_Fluide_Dilatable_base & Convection_Diffusion_Fluide_Dilatable_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Convection_Diffusion_Fluide_Dilatable_base::printOn (Sortie & os) const override protected virtual
Surcharge Objet_U::printOn Imprime l'equation et ses composants sur un flot de sortie.
Imprime le nom de l'equation, le solveur masse, les termes sources les conditions aux limites discretisees, les inconnues et les operateurs.
Parameters
(Sortie& os) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Equation_base.
Reimplemented in Convection_Diffusion_Chaleur_QC, Convection_Diffusion_Espece_Binaire_QC, Convection_Diffusion_Espece_Multi_QC, Convection_Diffusion_Chaleur_WC, Convection_Diffusion_Espece_Binaire_WC, Convection_Diffusion_Espece_Multi_WC, Convection_Diffusion_Chaleur_Turbulent_QC, Convection_Diffusion_Espece_Binaire_Turbulent_QC, and Convection_Diffusion_Espece_Multi_Turbulent_QC.
References Convection_Diffusion_std::printOn().
Referenced by Convection_Diffusion_Chaleur_Fluide_Dilatable_base::printOn(), and Convection_Diffusion_Espece_Fluide_Dilatable_base::printOn().
readOn()
Entree & Convection_Diffusion_Fluide_Dilatable_base::readOn (Entree & is) override protected virtual
Lecture d'une equation sur un flot d'entree.
Le format est le suivant: { [Source { [sou_1], [sour_2], ...} ] Conditions_limites { [cl_1] [cl_2] ... } Conditions_initiales { [cl_init] } }
Parameters
(Entree& is) un flot d'entree pour lire l'equation
Returns
(Entree&) le flot d'entree modifie
Exceptions
mauvais format de lecture, accolade ouvrante attendue
pas de conditions initiales, il faut initialiser l'inconnue
pas de conditions aux limites, il faut donner des conditions aux limites
Reimplemented from Equation_base.
Reimplemented in Convection_Diffusion_Chaleur_QC, Convection_Diffusion_Espece_Binaire_QC, Convection_Diffusion_Espece_Multi_QC, Convection_Diffusion_Chaleur_WC, Convection_Diffusion_Espece_Binaire_WC, Convection_Diffusion_Espece_Multi_WC, Convection_Diffusion_Chaleur_Turbulent_QC, Convection_Diffusion_Espece_Binaire_Turbulent_QC, and Convection_Diffusion_Espece_Multi_Turbulent_QC.
References l_inco_ch, le_fluide, Objet_U_ptr::non_nul(), TRUST_Ref< _CLASSE_ >::non_nul(), and Convection_Diffusion_std::readOn().
Referenced by Convection_Diffusion_Chaleur_Fluide_Dilatable_base::readOn(), and Convection_Diffusion_Espece_Fluide_Dilatable_base::readOn().
associer_fluide()
void Convection_Diffusion_Fluide_Dilatable_base::associer_fluide (const Fluide_Dilatable_base & un_fluide)
References le_fluide.
Referenced by associer_milieu_base().
associer_milieu_base()
void Convection_Diffusion_Fluide_Dilatable_base::associer_milieu_base (const Milieu_base & un_milieu) override virtual
Implements Equation_base.
References associer_fluide().
impr()
int Convection_Diffusion_Fluide_Dilatable_base::impr (Sortie & os) const override virtual
Imprime les operateurs de l'equation sur un flot de sortie, de facon inconditionnelle.
appelle Operateur_base::impr(os)
Parameters
(Sortie& os) le flot de sortie
Returns
(int) renvoie toujours 1
Reimplemented from Equation_base.
References Equation_base::impr().
diffusivite_pour_transport()
const Champ_Don_base & Convection_Diffusion_Fluide_Dilatable_base::diffusivite_pour_transport () const override virtual
Reimplemented from Convection_Diffusion_std.
References Milieu_base::conductivite(), is_thermal(), le_fluide, and milieu().
Referenced by Convection_Diffusion_Espece_Binaire_base::lire_motcle_non_standard(), Convection_Diffusion_Espece_Multi_base::lire_motcle_non_standard(), Convection_Diffusion_Espece_Multi_QC::lire_motcle_non_standard(), Convection_Diffusion_Chaleur_Turbulent_QC::lire_motcle_non_standard(), Convection_Diffusion_Espece_Binaire_Turbulent_QC::lire_motcle_non_standard(), and Convection_Diffusion_Espece_Multi_Turbulent_QC::lire_motcle_non_standard().
fluide() [1/2]
const Fluide_Dilatable_base & Convection_Diffusion_Fluide_Dilatable_base::fluide () const
References TRUST_Ref< _CLASSE_ >::est_nul(), Process::exit(), le_fluide, Probleme_U::le_nom(), Equation_base::probleme(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Convection_Diffusion_Fluide_Dilatable_Proto::assembler_blocs(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_impl(), Convection_Diffusion_Espece_Multi_QC::completer(), Convection_Diffusion_Espece_Multi_WC::completer(), Convection_Diffusion_Fluide_Dilatable_Proto::derivee_en_temps_inco_sans_solveur_masse_impl(), and milieu().
fluide() [2/2]
Fluide_Dilatable_base & Convection_Diffusion_Fluide_Dilatable_base::fluide ()
References le_fluide, TRUST_Ref< _CLASSE_ >::non_nul(), and TRUST_Ref< _CLASSE_ >::valeur().
milieu() [1/2]
const Milieu_base & Convection_Diffusion_Fluide_Dilatable_base::milieu () const override virtual
Implements Equation_base.
References fluide().
Referenced by Convection_Diffusion_Chaleur_Fluide_Dilatable_base::diffusivite_pour_pas_de_temps(), and diffusivite_pour_transport().
milieu() [2/2]
Milieu_base & Convection_Diffusion_Fluide_Dilatable_base::milieu () override virtual
Implements Equation_base.
References fluide().
set_param()
void Convection_Diffusion_Fluide_Dilatable_base::set_param (Param & titi) override virtual
Reimplemented from Equation_base.
Reimplemented in Convection_Diffusion_Chaleur_QC, Convection_Diffusion_Espece_Multi_QC, Convection_Diffusion_Chaleur_WC, Convection_Diffusion_Chaleur_Turbulent_QC, Convection_Diffusion_Espece_Binaire_Turbulent_QC, and Convection_Diffusion_Espece_Multi_Turbulent_QC.
References Convection_Diffusion_std::set_param().
Referenced by Convection_Diffusion_Espece_Binaire_base::set_param(), Convection_Diffusion_Espece_Multi_base::set_param(), Convection_Diffusion_Chaleur_QC::set_param(), and Convection_Diffusion_Chaleur_WC::set_param().
lire_motcle_non_standard()
int Convection_Diffusion_Fluide_Dilatable_base::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Equation_base.
Reimplemented in Convection_Diffusion_Chaleur_QC, Convection_Diffusion_Espece_Multi_QC, Convection_Diffusion_Chaleur_WC, Convection_Diffusion_Chaleur_Turbulent_QC, Convection_Diffusion_Espece_Binaire_Turbulent_QC, and Convection_Diffusion_Espece_Multi_Turbulent_QC.
References Convection_Diffusion_std::lire_motcle_non_standard().
Referenced by Convection_Diffusion_Espece_Binaire_base::lire_motcle_non_standard(), Convection_Diffusion_Espece_Multi_base::lire_motcle_non_standard(), Convection_Diffusion_Chaleur_QC::lire_motcle_non_standard(), Convection_Diffusion_Espece_Multi_QC::lire_motcle_non_standard(), and Convection_Diffusion_Chaleur_WC::lire_motcle_non_standard().
calculer_div_u_ou_div_rhou()
void Convection_Diffusion_Fluide_Dilatable_base::calculer_div_u_ou_div_rhou (DoubleTab & res) const override pure virtual
Implements Convection_Diffusion_Fluide_Dilatable_Proto.
Implemented in Convection_Diffusion_Espece_Fluide_Dilatable_base, Convection_Diffusion_Chaleur_QC, Convection_Diffusion_Chaleur_WC, and Convection_Diffusion_Chaleur_Fluide_Dilatable_base.
is_thermal()
bool Convection_Diffusion_Fluide_Dilatable_base::is_thermal () const override pure virtual
Implements Convection_Diffusion_Fluide_Dilatable_Proto.
Implemented in Convection_Diffusion_Chaleur_Fluide_Dilatable_base, and Convection_Diffusion_Espece_Fluide_Dilatable_base.
Referenced by diffusivite_pour_transport().
is_generic()
bool Convection_Diffusion_Fluide_Dilatable_base::is_generic () const override pure virtual
Implements Convection_Diffusion_Fluide_Dilatable_Proto.
Implemented in Convection_Diffusion_Espece_Fluide_Dilatable_base, Convection_Diffusion_Chaleur_QC, Convection_Diffusion_Chaleur_WC, and Convection_Diffusion_Chaleur_Fluide_Dilatable_base.
inconnue() [1/2]
const Champ_Inc_base & Convection_Diffusion_Fluide_Dilatable_base::inconnue () const inline override virtual
Implements Convection_Diffusion_std.
References l_inco_ch.
Referenced by Convection_Diffusion_Fluide_Dilatable_Proto::assembler_blocs(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::assembler_blocs_avec_inertie(), Convection_Diffusion_Espece_Binaire_base::assembler_blocs_avec_inertie(), Convection_Diffusion_Espece_Multi_QC::assembler_blocs_avec_inertie(), Convection_Diffusion_Espece_Multi_WC::assembler_blocs_avec_inertie(), Convection_Diffusion_Fluide_Dilatable_Proto::calculer_div_rho_u_impl(), Convection_Diffusion_Chaleur_WC::completer(), Convection_Diffusion_Espece_Multi_QC::derivee_en_temps_inco(), Convection_Diffusion_Fluide_Dilatable_Proto::derivee_en_temps_inco_sans_solveur_masse_impl(), Convection_Diffusion_Espece_Multi_base::readOn(), and Convection_Diffusion_Chaleur_Fluide_Dilatable_base::sauvegarder().
inconnue() [2/2]
Champ_Inc_base & Convection_Diffusion_Fluide_Dilatable_base::inconnue () inline override virtual
Implements Convection_Diffusion_std.
References l_inco_ch.
domaine_cl_modif() [1/2]
const Domaine_Cl_dis_base & Convection_Diffusion_Fluide_Dilatable_base::domaine_cl_modif () const inline
References TRUST_Deriv< _CLASSE_ >::valeur(), and zcl_modif_.
Referenced by Convection_Diffusion_Fluide_Dilatable_Proto::calculer_div_rho_u_impl().
domaine_cl_modif() [2/2]
Domaine_Cl_dis_base & Convection_Diffusion_Fluide_Dilatable_base::domaine_cl_modif () inline
References TRUST_Deriv< _CLASSE_ >::valeur(), and zcl_modif_.
Member Data Documentation
info_obj
const Type_info Convection_Diffusion_Fluide_Dilatable_base::info_obj static
l_inco_ch
TRUST_Deriv< Champ_Inc_base > Convection_Diffusion_Fluide_Dilatable_base::l_inco_ch protected
Referenced by Convection_Diffusion_Espece_Multi_QC::completer(), Convection_Diffusion_Espece_Multi_WC::completer(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::discretiser(), Convection_Diffusion_Espece_Fluide_Dilatable_base::discretiser(), inconnue(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::readOn(), Convection_Diffusion_Espece_Binaire_base::readOn(), Convection_Diffusion_Espece_Multi_base::readOn(), readOn(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::reprendre(), Convection_Diffusion_Chaleur_WC::reprendre(), and Convection_Diffusion_Espece_Binaire_WC::reprendre().
zcl_modif_
TRUST_Deriv< Domaine_Cl_dis_base > Convection_Diffusion_Fluide_Dilatable_base::zcl_modif_ protected
Referenced by Convection_Diffusion_Espece_Multi_QC::completer(), domaine_cl_modif(), Convection_Diffusion_Espece_Binaire_base::preparer_calcul(), Convection_Diffusion_Espece_Fluide_Dilatable_base::preparer_calcul(), and Convection_Diffusion_Chaleur_Fluide_Dilatable_base::remplir_cl_modifiee().
le_fluide
TRUST_Ref< Fluide_Dilatable_base *> Convection_Diffusion_Fluide_Dilatable_base::le_fluide protected
Referenced by associer_fluide(), Convection_Diffusion_Espece_Binaire_QC::completer(), Convection_Diffusion_Espece_Binaire_WC::completer(), Convection_Diffusion_Espece_Binaire_WC::data_a_sauvegarder(), Convection_Diffusion_Espece_Binaire_base::diffusivite_pour_pas_de_temps(), Convection_Diffusion_Espece_Multi_QC::diffusivite_pour_pas_de_temps(), Convection_Diffusion_Espece_Multi_WC::diffusivite_pour_pas_de_temps(), diffusivite_pour_transport(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::discretiser(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::domaine_application(), fluide(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::readOn(), Convection_Diffusion_Espece_Binaire_base::readOn(), readOn(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::reprendre(), Convection_Diffusion_Chaleur_WC::reprendre(), Convection_Diffusion_Espece_Binaire_WC::reprendre(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::sauvegarder(), Convection_Diffusion_Chaleur_WC::sauvegarder(), and Convection_Diffusion_Espece_Binaire_WC::sauvegarder().