TrioCFD: Operateur_base Class Reference
Operateur_base Class Reference abstract
#include <Operateur_base.h>
Public Member Functions
void associer_eqn (const Equation_base &)
virtual double calculer_dt_stab () const
virtual void completer ()
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual void mettre_a_jour (double temps)
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
operateur utilise dans des equations de TRUST. Ses membres sont
les attributs et les methodes communs a toutes les classes qui
representent un operateur. Un Operateur est un morceau d'equation
c'est pourquoi il derive de MorEqn qui lui permet d'avoir une
reference sur l'equation auquel il est attache.
Exemple de classe d'operateur: Op_Diff_K_Eps_negligeable,
                               Operateur_Div_base
See also
MorEqn Operateur Equation_base
Classe abstraite. Un certain nombre de methodes DOIVENT etre, surchargees dans les classes derivees.
Constructor & Destructor Documentation
Operateur_base()
Operateur_base::Operateur_base ()
References col_width_, decal_temps, and nb_ss_pas_de_temps.
~Operateur_base()
Operateur_base::~Operateur_base () override
Member Function Documentation
info()
const Type_info * Operateur_base::info () static
get_info()
const Type_info * Operateur_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
Reimplemented in Op_Conv_ALE_VDF, Op_Conv_ALE_VEF, Op_Conv_RT_VEF_Face, Operateur_Conv_sensibility, Operateur_Conv_sensibility_VEF, Op_Diff_Fluctu_Temp_Base, Op_Diff_Fluctu_Temp_negligeable, Op_Diff_Flux_Chaleur_Turb_Base, Op_Diff_Flux_Chaleur_Turb_negligeable, Op_Diff_K_Eps_Bas_Re_VDF_base, Op_Diff_K_Eps_Bas_Re_VDF_Elem_Axi, Op_Diff_K_Eps_Bas_Re_VDF_Elem, Op_Diff_K_Eps_Bas_Re_VDF_var_Elem, Op_Diff_K_Eps_VDF_base, Op_Diff_K_Eps_VDF_Elem, Op_Diff_K_Eps_VDF_Elem_Axi, Op_Diff_K_Eps_QC_VDF_Elem, Op_Diff_K_Eps_var_VDF_Elem, Op_Diff_K_Eps_var_QC_VDF_Elem, Op_Diff_K_VDF_Elem, Op_Diff_Eps_VDF_Elem, Op_Diff_K_Omega_VDF_base, Op_Diff_K_Omega_VDF_Elem, Op_Diff_K_Omega_var_VDF_Elem, Op_Diff_K_Eps_QC_VEF_Face, Op_Diff_K_Eps_VEF_base, Op_Diff_K_Eps_VEF_Face, Op_Diff_K_Omega_VEF_base, Op_Diff_K_Omega_VEF_Face, Op_Conv_negligeable, Op_Diff_negligeable, Op_Dift_negligeable, Operateur_Conv_base, Operateur_Diff_base, Operateur_Div_base, Operateur_Grad_base, Op_Evanescence_Homogene_PolyMAC_P0_Face, Op_Evanescence_Homogene_PolyMAC_P0P1NC_Elem, Op_Evanescence_Homogene_PolyMAC_P0P1NC_Face, Op_Conv_Amont_PolyMAC_Elem, Op_Conv_Centre_PolyMAC_Elem, Op_Conv_PolyMAC_iterateur_base, Op_Conv_EF_Stab_PolyMAC_Face, Op_Conv_Amont_PolyMAC_Face, Op_Conv_Centre_PolyMAC_Face, Op_Conv_EF_Stab_PolyMAC_P0_Face, Op_Conv_Amont_PolyMAC_P0_Face, Op_Conv_Centre_PolyMAC_P0_Face, Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem, Op_Conv_Amont_PolyMAC_P0P1NC_Elem, Op_Conv_Centre_PolyMAC_P0P1NC_Elem, Op_Conv_EF_Stab_PolyMAC_P0P1NC_Face, Op_Conv_Amont_PolyMAC_P0P1NC_Face, Op_Conv_Centre_PolyMAC_P0P1NC_Face, Op_Conv_PolyMAC_base, Op_Diff_PolyMAC_base, Op_Diff_PolyMAC_Gen_base, Op_Diff_PolyMAC_P0_base, Op_Diff_PolyMAC_P0P1NC_base, Op_Diff_PolyMAC_Elem, Op_Diff_Nonlinear_PolyMAC_Elem, Op_Dift_PolyMAC_Elem, Op_Dift_Nonlinear_PolyMAC_Elem, Op_Diff_PolyMAC_Face, Op_Diff_PolyMAC_P0_Elem, Op_Dift_PolyMAC_P0_Elem, Op_Diff_PolyMAC_P0_Face, Op_Diff_PolyMAC_P0P1NC_Elem, Op_Diff_PolyMAC_P0P1NC_Face, Op_Diff_Turbulent_PolyMAC_P0_Elem, Op_Diff_Turbulent_PolyMAC_P0_Face, Op_Div_PolyMAC, Op_Div_PolyMAC_P0, Op_Div_PolyMAC_P0P1NC, Op_Grad_PolyMAC_Face, Op_Grad_PolyMAC_P0_Face, Op_Grad_PolyMAC_P0P1NC_Face, Op_Conv_ALE, Op_Evanescence_Homogene_Elem_base, Op_Evanescence_Homogene_Face_base, Operateur_Evanescence_base, Op_Evanescence_Homogene_VDF_Elem, Op_Evanescence_Homogene_VDF_Face, Op_Conv_Amont_VPoly_VDF_Face, Op_Conv_VDF_base, Op_Conv_Amont_VDF_Elem, Op_Conv_Centre_VDF_Elem, Op_Conv_Centre4_VDF_Elem, Op_Conv_Quick_VDF_Elem, Op_Conv_Amont_VDF_Face, Op_Conv_Centre_VDF_Face, Op_Conv_Centre4_VDF_Face, Op_Conv_Quick_VDF_Face_Axi, Op_Conv_Quick_VDF_Face, Op_Diff_VDF_base, Op_Diff_VDF_Elem_base, Op_Diff_VDF_Face_Axi_base, Op_Diff_VDF_Face_base, Op_Dift_VDF_base, Op_Dift_VDF_Elem_base, Op_Dift_VDF_Face_Axi_base, Op_Dift_VDF_Face_base, Op_Diff_VDF_Elem, Op_Diff_VDF_Elem_Axi, Op_Diff_VDF_Elem_aniso, Op_Diff_VDF_Multi_inco_Elem, Op_Diff_VDF_Multi_inco_Multi_scalar_Elem, Op_Diff_VDF_Multi_inco_Elem_Axi, Op_Diff_VDF_Face, Op_Diff_VDF_Face_Axi, Op_Dift_Multiphase_VDF_Elem, Op_Dift_Multiphase_VDF_Face, Op_Dift_VDF_Elem, Op_Dift_VDF_Elem_Axi, Op_Dift_VDF_Multi_inco_Elem, Op_Dift_VDF_Multi_inco_Elem_Axi, Op_Dift_VDF_Face, Op_Dift_VDF_Face_Axi, Op_Div_VDF_base, Op_Div_VDF_Elem, Op_Grad_P0_to_Face, Op_Grad_VDF_Face, Op_Grad_VDF_Face_base, Op_Conv_Amont_old_VEF_Face, Op_Conv_Amont_VEF_Face, Op_Conv_AmontNew_VEF_Face, Op_Conv_Centre_EF_VEF_Face, Op_Conv_Centre_old_VEF_Face, Op_Conv_Centre_VEF_Face, Op_Conv_DI_L2_VEF_Face, Op_Conv_EF_VEF_P1NC, Op_Conv_EF_VEF_P1NC_Stab, Op_Conv_kschemas_centre_VEF, Op_Conv_kschemas_VEF, Op_Conv_Muscl3_VEF_Face, Op_Conv_Muscl_New_VEF_Face, Op_Conv_Muscl_old_VEF_Face, Op_Conv_Muscl_VEF_Face, Op_Conv_VEF_base, Op_Conv_VEF_Face, Op_Conv_Vort_VEF_Face, OpVEF_Centre, OpVEF_Centre4, OpVEF_Quick, Op_Diff_P1NC_barprim, Op_Diff_RotRot, Op_Diff_VEF_Anisotrope_Face, Op_Diff_VEF_base, Op_Diff_VEF_Face, Op_Diff_VEF_Face_Penalise, Op_Diff_VEF_Face_Q1, Op_Diff_VEF_Face_Stab, Op_Diff_VEFP1NCP1B_Face, Op_Dift_Stab_VEF_Face, Op_Dift_standard_VEF_Face, Op_Dift_VEF_base, Op_Dift_VEF_Face, Op_Dift_VEF_Face_Q1, Op_Dift_VEF_P1NCP1B_Face, Op_Curl_VEFP1B, Op_Div_VEFP1B_Elem, Op_Grad_P1NC_to_P0, Op_Grad_VEF_P1B_Face, and Op_Rot_VEFP1B.
self_cast() [1/2]
Operateur_base & Operateur_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Operateur_base & Operateur_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Operateur_base::printOn (Sortie & os) const override protected virtual
DOES NOTHING - to override in derived classes.
Imprime l'operateur sur un flot de sortie.
Parameters
(Sortie& os) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Objet_U.
Reimplemented in Op_Conv_ALE_VDF, Op_Conv_ALE_VEF, Op_Conv_RT_VEF_Face, Operateur_Conv_sensibility, Operateur_Conv_sensibility_VEF, Op_Diff_Fluctu_Temp_Base, Op_Diff_Fluctu_Temp_negligeable, Op_Diff_Flux_Chaleur_Turb_Base, Op_Diff_Flux_Chaleur_Turb_negligeable, Op_Diff_K_Eps_Bas_Re_VDF_base, Op_Diff_K_Eps_Bas_Re_VDF_Elem_Axi, Op_Diff_K_Eps_Bas_Re_VDF_Elem, Op_Diff_K_Eps_Bas_Re_VDF_var_Elem, Op_Diff_K_Eps_VDF_base, Op_Diff_K_Eps_VDF_Elem, Op_Diff_K_Eps_VDF_Elem_Axi, Op_Diff_K_Eps_QC_VDF_Elem, Op_Diff_K_Eps_var_VDF_Elem, Op_Diff_K_Eps_var_QC_VDF_Elem, Op_Diff_K_VDF_Elem, Op_Diff_Eps_VDF_Elem, Op_Diff_K_Omega_VDF_base, Op_Diff_K_Omega_VDF_Elem, Op_Diff_K_Omega_var_VDF_Elem, Op_Diff_K_Eps_QC_VEF_Face, Op_Diff_K_Eps_VEF_base, Op_Diff_K_Eps_VEF_Face, Op_Diff_K_Omega_VEF_base, Op_Diff_K_Omega_VEF_Face, Op_Conv_negligeable, Op_Diff_negligeable, Op_Dift_negligeable, Operateur_Conv_base, Operateur_Diff_base, Operateur_Div_base, Operateur_Grad_base, Op_Evanescence_Homogene_PolyMAC_P0_Face, Op_Evanescence_Homogene_PolyMAC_P0P1NC_Elem, Op_Evanescence_Homogene_PolyMAC_P0P1NC_Face, Op_Conv_Amont_PolyMAC_Elem, Op_Conv_Centre_PolyMAC_Elem, Op_Conv_PolyMAC_iterateur_base, Op_Conv_EF_Stab_PolyMAC_Face, Op_Conv_Amont_PolyMAC_Face, Op_Conv_Centre_PolyMAC_Face, Op_Conv_EF_Stab_PolyMAC_P0_Face, Op_Conv_Amont_PolyMAC_P0_Face, Op_Conv_Centre_PolyMAC_P0_Face, Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem, Op_Conv_Amont_PolyMAC_P0P1NC_Elem, Op_Conv_Centre_PolyMAC_P0P1NC_Elem, Op_Conv_EF_Stab_PolyMAC_P0P1NC_Face, Op_Conv_Amont_PolyMAC_P0P1NC_Face, Op_Conv_Centre_PolyMAC_P0P1NC_Face, Op_Conv_PolyMAC_base, Op_Diff_PolyMAC_base, Op_Diff_PolyMAC_Gen_base, Op_Diff_PolyMAC_P0_base, Op_Diff_PolyMAC_P0P1NC_base, Op_Diff_PolyMAC_Elem, Op_Diff_Nonlinear_PolyMAC_Elem, Op_Dift_PolyMAC_Elem, Op_Dift_Nonlinear_PolyMAC_Elem, Op_Diff_PolyMAC_Face, Op_Diff_PolyMAC_P0_Elem, Op_Dift_PolyMAC_P0_Elem, Op_Diff_PolyMAC_P0_Face, Op_Diff_PolyMAC_P0P1NC_Elem, Op_Diff_PolyMAC_P0P1NC_Face, Op_Diff_Turbulent_PolyMAC_P0_Elem, Op_Diff_Turbulent_PolyMAC_P0_Face, Op_Div_PolyMAC, Op_Div_PolyMAC_P0, Op_Div_PolyMAC_P0P1NC, Op_Grad_PolyMAC_Face, Op_Grad_PolyMAC_P0_Face, Op_Grad_PolyMAC_P0P1NC_Face, Op_Conv_ALE, Op_Evanescence_Homogene_Elem_base, Op_Evanescence_Homogene_Face_base, Operateur_Evanescence_base, Op_Evanescence_Homogene_VDF_Elem, Op_Evanescence_Homogene_VDF_Face, Op_Conv_Amont_VPoly_VDF_Face, Op_Conv_VDF_base, Op_Conv_Amont_VDF_Elem, Op_Conv_Centre_VDF_Elem, Op_Conv_Centre4_VDF_Elem, Op_Conv_Quick_VDF_Elem, Op_Conv_Amont_VDF_Face, Op_Conv_Centre_VDF_Face, Op_Conv_Centre4_VDF_Face, Op_Conv_Quick_VDF_Face_Axi, Op_Conv_Quick_VDF_Face, Op_Diff_VDF_base, Op_Diff_VDF_Elem_base, Op_Diff_VDF_Face_Axi_base, Op_Diff_VDF_Face_base, Op_Dift_VDF_base, Op_Dift_VDF_Elem_base, Op_Dift_VDF_Face_Axi_base, Op_Dift_VDF_Face_base, Op_Diff_VDF_Elem, Op_Diff_VDF_Elem_Axi, Op_Diff_VDF_Elem_aniso, Op_Diff_VDF_Multi_inco_Elem, Op_Diff_VDF_Multi_inco_Multi_scalar_Elem, Op_Diff_VDF_Multi_inco_Elem_Axi, Op_Diff_VDF_Face, Op_Diff_VDF_Face_Axi, Op_Dift_Multiphase_VDF_Elem, Op_Dift_Multiphase_VDF_Face, Op_Dift_VDF_Elem, Op_Dift_VDF_Elem_Axi, Op_Dift_VDF_Multi_inco_Elem, Op_Dift_VDF_Multi_inco_Elem_Axi, Op_Dift_VDF_Face, Op_Dift_VDF_Face_Axi, Op_Div_VDF_base, Op_Div_VDF_Elem, Op_Grad_P0_to_Face, Op_Grad_VDF_Face, Op_Grad_VDF_Face_base, Op_Conv_Amont_old_VEF_Face, Op_Conv_Amont_VEF_Face, Op_Conv_AmontNew_VEF_Face, Op_Conv_Centre_EF_VEF_Face, Op_Conv_Centre_old_VEF_Face, Op_Conv_Centre_VEF_Face, Op_Conv_DI_L2_VEF_Face, Op_Conv_EF_VEF_P1NC, Op_Conv_EF_VEF_P1NC_Stab, Op_Conv_kschemas_centre_VEF, Op_Conv_kschemas_VEF, Op_Conv_Muscl3_VEF_Face, Op_Conv_Muscl_New_VEF_Face, Op_Conv_Muscl_old_VEF_Face, Op_Conv_Muscl_VEF_Face, Op_Conv_VEF_base, Op_Conv_VEF_Face, Op_Conv_Vort_VEF_Face, OpVEF_Centre, OpVEF_Centre4, OpVEF_Quick, Op_Diff_P1NC_barprim, Op_Diff_RotRot, Op_Diff_VEF_Anisotrope_Face, Op_Diff_VEF_base, Op_Diff_VEF_Face, Op_Diff_VEF_Face_Penalise, Op_Diff_VEF_Face_Q1, Op_Diff_VEF_Face_Stab, Op_Diff_VEFP1NCP1B_Face, Op_Dift_Stab_VEF_Face, Op_Dift_standard_VEF_Face, Op_Dift_VEF_base, Op_Dift_VEF_Face, Op_Dift_VEF_Face_Q1, Op_Dift_VEF_P1NCP1B_Face, Op_Curl_VEFP1B, Op_Div_VEFP1B_Elem, Op_Grad_P1NC_to_P0, Op_Grad_VEF_P1B_Face, and Op_Rot_VEFP1B.
readOn()
Entree & Operateur_base::readOn (Entree & is) override protected virtual
DOES NOTHING - to override in derived classes.
Lit un operateur sur un flot d'entree.
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Objet_U.
Reimplemented in Op_Conv_ALE_VDF, Op_Conv_ALE_VEF, Op_Conv_RT_VEF_Face, Operateur_Conv_sensibility, Operateur_Conv_sensibility_VEF, Op_Diff_Fluctu_Temp_Base, Op_Diff_Fluctu_Temp_negligeable, Op_Diff_Flux_Chaleur_Turb_Base, Op_Diff_Flux_Chaleur_Turb_negligeable, Op_Diff_K_Eps_Bas_Re_VDF_base, Op_Diff_K_Eps_Bas_Re_VDF_Elem_Axi, Op_Diff_K_Eps_Bas_Re_VDF_Elem, Op_Diff_K_Eps_Bas_Re_VDF_var_Elem, Op_Diff_K_Eps_VDF_base, Op_Diff_K_Eps_VDF_Elem, Op_Diff_K_Eps_VDF_Elem_Axi, Op_Diff_K_Eps_QC_VDF_Elem, Op_Diff_K_Eps_var_VDF_Elem, Op_Diff_K_Eps_var_QC_VDF_Elem, Op_Diff_K_VDF_Elem, Op_Diff_Eps_VDF_Elem, Op_Diff_K_Omega_VDF_base, Op_Diff_K_Omega_VDF_Elem, Op_Diff_K_Omega_var_VDF_Elem, Op_Diff_K_Eps_QC_VEF_Face, Op_Diff_K_Eps_VEF_base, Op_Diff_K_Eps_VEF_Face, Op_Diff_K_Omega_VEF_base, Op_Diff_K_Omega_VEF_Face, Op_Conv_negligeable, Op_Diff_negligeable, Op_Dift_negligeable, Operateur_Conv_base, Operateur_Diff_base, Operateur_Div_base, Operateur_Grad_base, Op_Evanescence_Homogene_PolyMAC_P0_Face, Op_Evanescence_Homogene_PolyMAC_P0P1NC_Elem, Op_Evanescence_Homogene_PolyMAC_P0P1NC_Face, Op_Conv_Amont_PolyMAC_Elem, Op_Conv_Centre_PolyMAC_Elem, Op_Conv_PolyMAC_iterateur_base, Op_Conv_EF_Stab_PolyMAC_Face, Op_Conv_Amont_PolyMAC_Face, Op_Conv_Centre_PolyMAC_Face, Op_Conv_EF_Stab_PolyMAC_P0_Face, Op_Conv_Amont_PolyMAC_P0_Face, Op_Conv_Centre_PolyMAC_P0_Face, Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem, Op_Conv_Amont_PolyMAC_P0P1NC_Elem, Op_Conv_Centre_PolyMAC_P0P1NC_Elem, Op_Conv_EF_Stab_PolyMAC_P0P1NC_Face, Op_Conv_Amont_PolyMAC_P0P1NC_Face, Op_Conv_Centre_PolyMAC_P0P1NC_Face, Op_Conv_PolyMAC_base, Op_Diff_PolyMAC_base, Op_Diff_PolyMAC_Gen_base, Op_Diff_PolyMAC_P0_base, Op_Diff_PolyMAC_P0P1NC_base, Op_Diff_PolyMAC_Elem, Op_Diff_Nonlinear_PolyMAC_Elem, Op_Dift_PolyMAC_Elem, Op_Dift_Nonlinear_PolyMAC_Elem, Op_Diff_PolyMAC_Face, Op_Diff_PolyMAC_P0_Elem, Op_Dift_PolyMAC_P0_Elem, Op_Diff_PolyMAC_P0_Face, Op_Diff_PolyMAC_P0P1NC_Elem, Op_Diff_PolyMAC_P0P1NC_Face, Op_Diff_Turbulent_PolyMAC_P0_Elem, Op_Diff_Turbulent_PolyMAC_P0_Face, Op_Div_PolyMAC, Op_Div_PolyMAC_P0, Op_Div_PolyMAC_P0P1NC, Op_Grad_PolyMAC_Face, Op_Grad_PolyMAC_P0_Face, Op_Grad_PolyMAC_P0P1NC_Face, Op_Conv_ALE, Op_Evanescence_Homogene_Elem_base, Op_Evanescence_Homogene_Face_base, Operateur_Evanescence_base, Op_Evanescence_Homogene_VDF_Elem, Op_Evanescence_Homogene_VDF_Face, Op_Conv_Amont_VPoly_VDF_Face, Op_Conv_VDF_base, Op_Conv_Amont_VDF_Elem, Op_Conv_Centre_VDF_Elem, Op_Conv_Centre4_VDF_Elem, Op_Conv_Quick_VDF_Elem, Op_Conv_Amont_VDF_Face, Op_Conv_Centre_VDF_Face, Op_Conv_Centre4_VDF_Face, Op_Conv_Quick_VDF_Face_Axi, Op_Conv_Quick_VDF_Face, Op_Diff_VDF_base, Op_Diff_VDF_Elem_base, Op_Diff_VDF_Face_Axi_base, Op_Diff_VDF_Face_base, Op_Dift_VDF_base, Op_Dift_VDF_Elem_base, Op_Dift_VDF_Face_Axi_base, Op_Dift_VDF_Face_base, Op_Diff_VDF_Elem, Op_Diff_VDF_Elem_Axi, Op_Diff_VDF_Elem_aniso, Op_Diff_VDF_Multi_inco_Elem, Op_Diff_VDF_Multi_inco_Multi_scalar_Elem, Op_Diff_VDF_Multi_inco_Elem_Axi, Op_Diff_VDF_Face, Op_Diff_VDF_Face_Axi, Op_Dift_Multiphase_VDF_Elem, Op_Dift_Multiphase_VDF_Face, Op_Dift_VDF_Elem, Op_Dift_VDF_Elem_Axi, Op_Dift_VDF_Multi_inco_Elem, Op_Dift_VDF_Multi_inco_Elem_Axi, Op_Dift_VDF_Face, Op_Dift_VDF_Face_Axi, Op_Div_VDF_base, Op_Div_VDF_Elem, Op_Grad_P0_to_Face, Op_Grad_VDF_Face, Op_Grad_VDF_Face_base, Op_Conv_Amont_old_VEF_Face, Op_Conv_Amont_VEF_Face, Op_Conv_AmontNew_VEF_Face, Op_Conv_Centre_EF_VEF_Face, Op_Conv_Centre_old_VEF_Face, Op_Conv_Centre_VEF_Face, Op_Conv_DI_L2_VEF_Face, Op_Conv_EF_VEF_P1NC, Op_Conv_EF_VEF_P1NC_Stab, Op_Conv_kschemas_centre_VEF, Op_Conv_kschemas_VEF, Op_Conv_Muscl3_VEF_Face, Op_Conv_Muscl_New_VEF_Face, Op_Conv_Muscl_old_VEF_Face, Op_Conv_Muscl_VEF_Face, Op_Conv_VEF_base, Op_Conv_VEF_Face, Op_Conv_Vort_VEF_Face, OpVEF_Centre, OpVEF_Centre4, OpVEF_Quick, Op_Diff_P1NC_barprim, Op_Diff_RotRot, Op_Diff_VEF_Anisotrope_Face, Op_Diff_VEF_base, Op_Diff_VEF_Face, Op_Diff_VEF_Face_Penalise, Op_Diff_VEF_Face_Q1, Op_Diff_VEF_Face_Stab, Op_Diff_VEFP1NCP1B_Face, Op_Dift_Stab_VEF_Face, Op_Dift_standard_VEF_Face, Op_Dift_VEF_base, Op_Dift_VEF_Face, Op_Dift_VEF_Face_Q1, Op_Dift_VEF_P1NCP1B_Face, Op_Curl_VEFP1B, Op_Div_VEFP1B_Elem, Op_Grad_P1NC_to_P0, Op_Grad_VEF_P1B_Face, and Op_Rot_VEFP1B.
ajouter()
DoubleTab & Operateur_base::ajouter (const DoubleTab & inco, DoubleTab & secmem) const virtual
Reimplemented in Operateur_Conv_sensibility, Operateur_Conv_sensibility_VEF, Op_Diff_Fluctu_Temp_negligeable, Op_Diff_Flux_Chaleur_Turb_negligeable, Op_Diff_K_Eps_QC_VEF_Face, Op_Diff_K_Eps_VEF_Face, Op_Diff_K_Omega_VEF_Face, Op_Conv_EF, Op_Diff_EF, Op_Dift_EF_Q1, Op_Div_EF, Op_Grad_EF, Op_Diff_negligeable, Op_Diff_PolyMAC_Elem, Op_Div_PolyMAC, Op_Div_PolyMAC_P0, Op_Grad_PolyMAC_Face, Op_Conv_ALE, Op_Conv_Amont_old_VEF_Face, Op_Conv_AmontNew_VEF_Face, Op_Conv_Centre_EF_VEF_Face, Op_Conv_Centre_old_VEF_Face, Op_Conv_DI_L2_VEF_Face, Op_Conv_EF_VEF_P1NC, Op_Conv_EF_VEF_P1NC_Stab, Op_Conv_kschemas_centre_VEF, Op_Conv_kschemas_VEF, Op_Conv_Muscl_New_VEF_Face, Op_Conv_Muscl_old_VEF_Face, Op_Conv_VEF_Face, Op_Conv_Vort_VEF_Face, Op_Diff_P1NC_barprim, Op_Diff_RotRot, Op_Diff_VEF_Anisotrope_Face, Op_Diff_VEF_Face, Op_Diff_VEF_Face_Q1, Op_Diff_VEF_Face_Stab, Op_Diff_VEFP1NCP1B_Face, Op_Dift_Stab_VEF_Face, Op_Dift_standard_VEF_Face, Op_Dift_VEF_Face, Op_Dift_VEF_Face_Q1, Op_Dift_VEF_P1NCP1B_Face, Op_Curl_VEFP1B, Op_Div_VEFP1B_Elem, Op_Grad_P1NC_to_P0, Op_Grad_VEF_P1B_Face, Op_Rot_VEFP1B, Op_Conv_PolyMAC_iterateur_base, Op_Conv_EF_Stab_PolyMAC_Face, Op_Diff_PolyMAC_Face, Op_Div_VDF_base, Operateur_Grad_base, Op_Diff_VEF_Face_Penalise, Op_Conv_RT_VEF_Face, and Operateur_Div_base.
References ajouter_blocs(), MorEqn::equation(), Process::exit(), Nom::getString(), has_interface_blocs(), Equation_base::inconnue(), Field_base::le_nom(), and Objet_U::que_suis_je().
Referenced by Op_Diff_Fluctu_Temp::ajouter(), Op_Diff_Flux_Chaleur_Turb::ajouter(), Operateur_Conv::ajouter(), Operateur_Diff::ajouter(), Operateur_Evanescence::ajouter(), Op_Conv_EF_Stab_PolyMAC_Face::ajouter(), ajouter_contribution_explicite_au_second_membre(), calculer(), Op_Diff_DG_base::calculer(), Op_Conv_EF_base::calculer(), Op_Diff_PolyMAC_Gen_base::calculer(), Op_Diff_VDF_base::calculer(), Op_Conv_VEF_base::calculer(), Op_Conv_PolyMAC_base::calculer(), Modele_turbulence_scal_LES_dyn_VDF::calculer_grad_teta(), Domaine_ALE::computeFluidForceOnBeam(), Champ_Post_Operateur_Eqn::get_champ(), Op_Conv_EF_base::remplir_fluent(), and Op_Conv_VEF_base::remplir_fluent().
calculer()
DoubleTab & Operateur_base::calculer (const DoubleTab & inco, DoubleTab & secmem) const virtual
Reimplemented in Operateur_Conv_sensibility, Op_Diff_Fluctu_Temp_negligeable, Op_Diff_Flux_Chaleur_Turb_negligeable, Op_Diff_DG_base, Op_Conv_EF_base, Op_Diff_EF, Op_Dift_EF_Q1, Op_Div_EF, Op_Grad_EF, Op_Diff_negligeable, Op_Diff_PolyMAC_Gen_base, Op_Div_PolyMAC, Op_Grad_PolyMAC_Face, Op_Conv_ALE, Op_Diff_VDF_base, Op_Diff_VDF_Face_Axi_base, Op_Dift_VDF_Face_Axi_base, Op_Grad_VDF_Face_base, Op_Conv_VEF_base, Op_Diff_P1NC_barprim, Op_Diff_RotRot, Op_Diff_VEF_Anisotrope_Face, Op_Diff_VEF_Face, Op_Diff_VEF_Face_Q1, Op_Diff_VEFP1NCP1B_Face, Op_Curl_VEFP1B, Op_Grad_P1NC_to_P0, Op_Rot_VEFP1B, Op_Diff_K_Eps_Bas_Re_VDF_base, Op_Diff_K_Eps_VDF_base, Op_Diff_K_Omega_VDF_base, Op_Conv_PolyMAC_iterateur_base, Op_Conv_PolyMAC_base, Op_Conv_VDF_base, Op_Div_VDF_base, and Op_Diff_VEF_Face_Penalise.
References ajouter().
Referenced by Op_Diff_Fluctu_Temp::calculer(), Op_Diff_Flux_Chaleur_Turb::calculer(), Operateur_Conv::calculer(), Operateur_Diff::calculer(), Operateur_Div::calculer(), Operateur_Grad::calculer(), Operateur_Evanescence::calculer(), Operateur_Div_base::multvect(), Operateur_Grad_base::multvect(), and tester_contribuer_a_avec().
associer_champ()
void Operateur_base::associer_champ (const Champ_Inc_base & ch, const std::string & nom_ch) virtual
References le_champ_inco, and nom_inco_.
Referenced by Operateur::associer_champ().
associer()
virtual void Operateur_base::associer (const Domaine_dis_base & , const Domaine_Cl_dis_base & , const Champ_Inc_base & inco) pure virtual
Implemented in Op_Conv_ALE_VEF, Operateur_Conv_sensibility_VEF, Op_Diff_Fluctu_Temp_negligeable, Op_Diff_Flux_Chaleur_Turb_negligeable, Op_Diff_DG_base, Op_Conv_EF_base, Op_Diff_EF_base, Op_Div_EF, Op_Grad_EF, Op_Conv_negligeable, Op_Diff_negligeable, Op_Conv_Amont_PolyMAC_Elem, Op_Conv_Centre_PolyMAC_Elem, Op_Conv_PolyMAC_base, Op_Diff_PolyMAC_Gen_base, Op_Div_PolyMAC, Op_Grad_PolyMAC_Face, Op_Diff_VDF_Face_Axi_base, Op_Dift_VDF_Face_Axi_base, Op_Div_VDF_Elem, Op_Grad_VDF_Face_base, Op_Conv_Centre_old_VEF_Face, Op_Conv_kschemas_VEF, Op_Conv_VEF_base, Op_Diff_P1NC_barprim, Op_Diff_RotRot, Op_Diff_VEF_base, Op_Diff_VEFP1NCP1B_Face, Op_Dift_VEF_base, Op_Dift_VEF_P1NCP1B_Face, Op_Curl_VEFP1B, Op_Div_VEFP1B_Elem, Op_Grad_P1NC_to_P0, Op_Grad_VEF_P1B_Face, Op_Rot_VEFP1B, Operateur_Conv_sensibility, Op_Conv_ALE, Operateur_Evanescence_base, Op_Diff_K_Eps_Bas_Re_VDF_Elem_Axi, Op_Diff_K_Eps_Bas_Re_VDF_Elem, Op_Diff_K_Eps_Bas_Re_VDF_var_Elem, Op_Conv_Amont_VDF_Elem, Op_Conv_Centre_VDF_Elem, Op_Conv_Centre4_VDF_Elem, Op_Conv_Quick_VDF_Elem, Op_Conv_Amont_VDF_Face, Op_Conv_Centre_VDF_Face, Op_Conv_Centre4_VDF_Face, Op_Conv_Quick_VDF_Face_Axi, Op_Conv_Quick_VDF_Face, Op_Diff_VDF_Elem, Op_Diff_VDF_Elem_Axi, Op_Diff_VDF_Elem_aniso, Op_Diff_VDF_Multi_inco_Elem, Op_Diff_VDF_Multi_inco_Multi_scalar_Elem, Op_Diff_VDF_Multi_inco_Elem_Axi, Op_Diff_VDF_Face, Op_Dift_Multiphase_VDF_Elem, Op_Dift_Multiphase_VDF_Face, Op_Dift_VDF_Elem, Op_Dift_VDF_Elem_Axi, Op_Dift_VDF_Multi_inco_Elem, Op_Dift_VDF_Multi_inco_Elem_Axi, Op_Dift_VDF_Face, Op_Diff_K_Eps_VDF_Elem, Op_Diff_K_Eps_VDF_Elem_Axi, Op_Diff_K_Eps_QC_VDF_Elem, Op_Diff_K_Eps_var_VDF_Elem, Op_Diff_K_Eps_var_QC_VDF_Elem, Op_Diff_K_VDF_Elem, Op_Diff_Eps_VDF_Elem, Op_Diff_K_Omega_VDF_Elem, and Op_Diff_K_Omega_var_VDF_Elem.
Referenced by Operateur_Conv_sensibility::associer(), Op_Conv_ALE::associer(), completer(), and Convection_Diffusion_Temperature_FT_Disc::compute_divergence_free_velocity_extension().
associer_domaine_cl_dis()
void Operateur_base::associer_domaine_cl_dis (const Domaine_Cl_dis_base &) virtual
Reimplemented in Op_Conv_EF_base, Op_Conv_negligeable, Op_Conv_PolyMAC_iterateur_base, Op_Conv_PolyMAC_base, Op_Conv_VEF_base, and Op_Conv_VDF_base.
References Process::exit().
Referenced by Terme_Source_Th_TdivU_VEF_Face::ajouter().
dimensionner()
void Operateur_base::dimensionner (Matrice_Morse & mat) const virtual
DOES NOTHING - to override in derived classes.
Parameters
(Matrice_Morse&) une matrice au format Morse
Exceptions
methode a surcharger
Reimplemented in Op_Conv_ALE_VEF, Op_Diff_Fluctu_Temp_negligeable, Op_Diff_Flux_Chaleur_Turb_negligeable, Op_Diff_negligeable, Operateur_Grad_base, Op_Conv_Amont_PolyMAC_Elem, Op_Conv_Centre_PolyMAC_Elem, Op_Grad_PolyMAC_Face, Op_Conv_Amont_old_VEF_Face, Op_Conv_EF_VEF_P1NC, Op_Conv_VEF_Face, Op_Diff_P1NC_barprim, Op_Diff_VEF_Anisotrope_Face, Op_Diff_VEF_Face, Op_Diff_VEF_Face_Q1, Op_Diff_VEFP1NCP1B_Face, Op_Div_VEFP1B_Elem, Op_Diff_DG_Elem, Op_Conv_EF_Stab_PolyMAC_Face, Op_Diff_PolyMAC_Elem, Op_Diff_PolyMAC_Face, Op_Conv_EF, Op_Diff_EF, Op_Dift_EF_Q1, Op_Div_PolyMAC, Op_Div_PolyMAC_P0, Op_Diff_VDF_Face_Axi_base, Op_Dift_VDF_Face_Axi_base, and Op_Dift_VEF_base.
References dimensionner_blocs(), MorEqn::equation(), Process::exit(), Nom::getString(), has_interface_blocs(), Equation_base::inconnue(), Field_base::le_nom(), and Objet_U::que_suis_je().
Referenced by Equation_base::derivee_en_temps_inco(), Op_Conv_EF_Stab_PolyMAC_Face::dimensionner(), Op_Div_PolyMAC::dimensionner(), and Equation_base::dimensionner_matrice_sans_mem().
dimensionner_bloc_vitesse()
void Operateur_base::dimensionner_bloc_vitesse (Matrice_Morse & matrice) const virtual
Reimplemented in Op_Conv_Amont_PolyMAC_Elem, and Op_Conv_Centre_PolyMAC_Elem.
References dimensionner_blocs(), and has_interface_blocs().
modifier_pour_Cl()
void Operateur_base::modifier_pour_Cl (Matrice_Morse & , DoubleTab &) const virtual
DOES NOTHING - to override in derived classes.
Parameters
(Matrice_Morse&) une matrice au format Morse
(DoubleTab&) un tableau de valeur (double)
Exceptions
methode a surcharger
Reimplemented in Op_Diff_Fluctu_Temp_negligeable, Op_Diff_Flux_Chaleur_Turb_negligeable, Op_Diff_K_Eps_VDF_base, Op_Diff_K_Omega_VDF_base, Op_Conv_negligeable, Op_Diff_negligeable, Op_Conv_Amont_PolyMAC_Elem, Op_Conv_Centre_PolyMAC_Elem, Op_Conv_EF_Stab_PolyMAC_Face, Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem, Op_Diff_PolyMAC_Face, Op_Diff_PolyMAC_P0_Face, Op_Diff_PolyMAC_P0P1NC_Face, Op_Conv_Amont_old_VEF_Face, Op_Conv_EF_VEF_P1NC, Op_Conv_EF_VEF_P1NC_Stab, Op_Conv_Muscl_New_VEF_Face, Op_Conv_VEF_Face, Op_Diff_P1NC_barprim, Op_Diff_VEF_Anisotrope_Face, Op_Diff_VEF_Face, Op_Diff_VEF_Face_Q1, Op_Div_VEFP1B_Elem, Op_Diff_DG_Elem, Op_Diff_PolyMAC_Elem, Op_Diff_PolyMAC_P0_Elem, Op_Diff_PolyMAC_P0P1NC_Elem, Op_Conv_ALE_VEF, Op_Diff_K_Eps_Bas_Re_VDF_base, Op_Diff_K_Eps_VEF_Face, Op_Diff_K_Omega_VEF_Face, Op_Conv_EF, Op_Diff_EF, Op_Dift_EF_Q1, Op_Conv_Amont_VDF_Elem, Op_Conv_Centre_VDF_Elem, Op_Conv_Quick_VDF_Elem, Op_Conv_Amont_VDF_Face, Op_Conv_Centre_VDF_Face, Op_Conv_Quick_VDF_Face, Op_Diff_VDF_Elem_base, Op_Diff_VDF_Face_Axi_base, Op_Diff_VDF_Face_base, Op_Dift_VDF_Elem_base, Op_Dift_VDF_Face_Axi_base, Op_Dift_VDF_Face_base, and Op_Dift_VEF_base.
References MorEqn::equation(), Process::exit(), Equation_base::probleme(), Objet_U::que_suis_je(), and Probleme_base::schema_temps().
Referenced by Navier_Stokes_Fluide_Dilatable_Proto::assembler_avec_inertie_impl(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_blocs_avec_inertie(), and Equation_base::modifier_pour_Cl().
contribuer_a_avec()
void Operateur_base::contribuer_a_avec (const DoubleTab & inco, Matrice_Morse & matrice) const virtual
DOES NOTHING - to override in derived classes.
Parameters
(DoubleTab&) un tableau de valeur (double)
(Matrice_Morse&) une matrice au format Morse
Exceptions
methode a surcharger
Reimplemented in Op_Conv_ALE_VEF, Op_Diff_Fluctu_Temp_negligeable, Op_Diff_Flux_Chaleur_Turb_negligeable, Op_Diff_K_Eps_VEF_Face, Op_Diff_K_Omega_VEF_Face, Op_Diff_negligeable, Operateur_Grad_base, Op_Conv_EF_Stab_PolyMAC_Face, Op_Diff_PolyMAC_Elem, Op_Diff_PolyMAC_Face, Op_Conv_Amont_old_VEF_Face, Op_Conv_EF_VEF_P1NC, Op_Conv_EF_VEF_P1NC_Stab, Op_Conv_Muscl_New_VEF_Face, Op_Conv_VEF_Face, Op_Diff_P1NC_barprim, Op_Diff_VEF_Anisotrope_Face, Op_Diff_VEF_Face, Op_Diff_VEF_Face_Q1, Op_Diff_VEF_Face_Stab, Op_Diff_VEFP1NCP1B_Face, Op_Dift_Stab_VEF_Face, Op_Dift_VEF_Face, Op_Dift_VEF_Face_Q1, Op_Div_VEFP1B_Elem, Op_Div_PolyMAC, Op_Div_PolyMAC_P0, Op_Conv_EF, Op_Diff_EF, Op_Dift_EF_Q1, Op_Conv_PolyMAC_iterateur_base, Op_Grad_PolyMAC_Face, Op_Diff_VDF_Face_Axi_base, and Op_Dift_VDF_Face_Axi_base.
References ajouter_blocs(), MorEqn::equation(), Process::exit(), Nom::getString(), has_interface_blocs(), Equation_base::inconnue(), Field_base::le_nom(), and Objet_U::que_suis_je().
Referenced by Equation_base::assembler(), Convection_Diffusion_Espece_Multi_QC::assembler(), Convection_Diffusion_Temperature::assembler(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_avec_inertie_impl(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_impl(), Op_Conv_EF_Stab_PolyMAC_Face::contribuer_a_avec(), Op_Div_PolyMAC::contribuer_a_avec(), Equation_base::derivee_en_temps_inco(), and tester_contribuer_a_avec().
contribuer_bloc_vitesse()
void Operateur_base::contribuer_bloc_vitesse (const DoubleTab & inco, Matrice_Morse & matrice) const virtual
Reimplemented in Op_Conv_PolyMAC_iterateur_base.
References ajouter_blocs(), and has_interface_blocs().
contribuer_au_second_membre()
void Operateur_base::contribuer_au_second_membre (DoubleTab &) const virtual
DOES NOTHING - to override in derived classes.
Parameters
(DoubleTab&) un tableau de valeur (double)
Exceptions
methode a surcharger
Reimplemented in Op_Diff_Fluctu_Temp_negligeable, Op_Diff_Flux_Chaleur_Turb_negligeable, Op_Diff_EF, Op_Dift_EF_Q1, Op_Conv_negligeable, Op_Diff_negligeable, Op_Dift_VDF_base, Op_Conv_Amont_old_VEF_Face, Op_Conv_EF_VEF_P1NC, Op_Conv_VEF_Face, Op_Diff_P1NC_barprim, Op_Diff_VEF_Anisotrope_Face, Op_Diff_VEF_Face, Op_Diff_VEF_Face_Q1, Op_Diff_VEFP1NCP1B_Face, Op_Dift_VEF_Face_Q1, Op_Div_VEFP1B_Elem, Op_Diff_DG_Elem, Op_Conv_EF, Op_Conv_PolyMAC_iterateur_base, Op_Conv_VDF_base, Op_Diff_VDF_base, Op_Diff_VDF_Face_Axi_base, Op_Dift_VDF_Face_Axi_base, and Op_Dift_VEF_Face.
References Process::exit(), and Objet_U::que_suis_je().
Referenced by Equation_base::assembler(), Convection_Diffusion_Temperature::assembler(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_impl(), Equation_base::derivee_en_temps_inco(), and tester_contribuer_a_avec().
tester_contribuer_a_avec()
void Operateur_base::tester_contribuer_a_avec (const DoubleTab & inco, const Matrice_Morse & matrice)
References calculer(), contribuer_a_avec(), contribuer_au_second_membre(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Process::exit(), Matrice_Morse::get_set_coeff(), Matrice_Morse::get_set_tab1(), Matrice_Morse::get_set_tab2(), MorEqn::mon_equation, TRUSTVect< _TYPE_, _SIZE_ >::mp_max_abs_vect(), and Objet_U::que_suis_je().
Referenced by Equation_base::assembler(), and Convection_Diffusion_Temperature::assembler().
has_interface_blocs()
virtual int Operateur_base::has_interface_blocs () const inline virtual
Reimplemented in Op_Diff_K_Eps_Bas_Re_VDF_base, Op_Diff_K_Eps_VDF_base, Op_Diff_K_Omega_VDF_base, Op_Diff_DG_Elem, Op_Conv_negligeable, Op_Diff_negligeable, Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem, Op_Conv_EF_Stab_PolyMAC_P0P1NC_Face, Op_Diff_PolyMAC_P0P1NC_base, Op_Diff_PolyMAC_P0_Elem, Op_Diff_PolyMAC_P0_Face, Op_Diff_PolyMAC_P0P1NC_Face, Op_Div_PolyMAC_P0P1NC, Op_Grad_PolyMAC_P0P1NC_Face, Op_Evanescence_Homogene_Elem_base, Op_Evanescence_Homogene_Face_base, Op_Conv_VDF_base, Op_Diff_VDF_base, and Op_Grad_VDF_Face_base.
Referenced by ajouter(), Op_Div_PolyMAC::ajouter(), Op_Grad_PolyMAC_Face::ajouter(), Op_Conv_EF_Stab_PolyMAC_Face::ajouter(), Operateur_Grad_base::ajouter(), contribuer_a_avec(), Operateur_Grad_base::contribuer_a_avec(), Op_Conv_EF_Stab_PolyMAC_Face::contribuer_a_avec(), Op_Div_PolyMAC::contribuer_a_avec(), Op_Grad_PolyMAC_Face::contribuer_a_avec(), contribuer_bloc_vitesse(), contribuer_termes_croises(), dimensionner(), Operateur_Grad_base::dimensionner(), Op_Grad_PolyMAC_Face::dimensionner(), Op_Conv_EF_Stab_PolyMAC_Face::dimensionner(), Op_Div_PolyMAC::dimensionner(), dimensionner_bloc_vitesse(), dimensionner_termes_croises(), and Equation_base::has_interface_blocs().
dimensionner_blocs()
void Operateur_base::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl = { }) const virtual
Reimplemented in Op_Diff_K_Eps_Bas_Re_VDF_base, Op_Diff_K_Eps_VDF_base, Op_Diff_K_Omega_VDF_base, Op_Diff_VDF_Elem_base, Op_Diff_VDF_Face_base, Op_Dift_VDF_Elem_base, Op_Dift_VDF_Face_base, Op_Grad_P0_to_Face, Op_Grad_VDF_Face, Op_Diff_negligeable, Op_Conv_EF_Stab_PolyMAC_P0_Face, Op_Conv_EF_Stab_PolyMAC_P0P1NC_Face, Op_Diff_PolyMAC_P0P1NC_base, Op_Diff_PolyMAC_P0_Face, Op_Div_PolyMAC_P0P1NC, Op_Grad_PolyMAC_P0_Face, Op_Grad_PolyMAC_P0P1NC_Face, Op_Diff_DG_Elem, Op_Conv_negligeable, Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem, Op_Diff_PolyMAC_P0_Elem, Op_Evanescence_Homogene_Elem_base, Op_Evanescence_Homogene_Face_base, Op_Conv_Amont_VPoly_VDF_Face, Op_Conv_Amont_VDF_Elem, Op_Conv_Centre_VDF_Elem, Op_Conv_Quick_VDF_Elem, Op_Conv_Amont_VDF_Face, Op_Conv_Centre_VDF_Face, and Op_Conv_Quick_VDF_Face.
References Process::exit(), and Objet_U::que_suis_je().
Referenced by dimensionner(), Operateur_Grad_base::dimensionner(), dimensionner_bloc_vitesse(), Equation_base::dimensionner_blocs(), and dimensionner_termes_croises().
ajouter_blocs()
void Operateur_base::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = { }) const virtual
Reimplemented in Op_Diff_negligeable, Op_Diff_K_Eps_Bas_Re_VDF_base, Op_Diff_K_Eps_VDF_base, Op_Diff_K_Omega_VDF_base, Op_Diff_VDF_Elem_base, Op_Diff_VDF_Face_base, Op_Dift_VDF_base, Op_Grad_P0_to_Face, Op_Grad_VDF_Face, Op_Conv_EF_Stab_PolyMAC_P0_Face, Op_Conv_EF_Stab_PolyMAC_P0P1NC_Face, Op_Diff_PolyMAC_P0P1NC_base, Op_Diff_PolyMAC_P0_Face, Op_Grad_PolyMAC_P0_Face, Op_Grad_PolyMAC_P0P1NC_Face, Op_Diff_DG_Elem, Op_Conv_negligeable, Operateur_Div_base, Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem, Op_Diff_PolyMAC_P0_Elem, Op_Evanescence_Homogene_Elem_base, Op_Evanescence_Homogene_Face_base, Op_Conv_Amont_VPoly_VDF_Face, and Op_Conv_VDF_base.
References Process::exit(), and Objet_U::que_suis_je().
Referenced by ajouter(), Operateur_Grad_base::ajouter(), Source_Flux_interfacial_base::ajouter_blocs(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_blocs(), Equation_base::assembler_blocs(), Convection_Diffusion_Temperature::assembler_blocs(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_blocs_avec_inertie(), Convection_Diffusion_Espece_Multi_QC::assembler_blocs_avec_inertie(), contribuer_a_avec(), Operateur_Grad_base::contribuer_a_avec(), contribuer_bloc_vitesse(), and contribuer_termes_croises().
dimensionner_termes_croises()
void Operateur_base::dimensionner_termes_croises (Matrice_Morse & mat, const Probleme_base & autre_pb, int nl, int nc) const virtual
Reimplemented in Op_Diff_DG_Elem, Op_Diff_PolyMAC_Elem, and Op_Diff_VDF_Elem_base.
References dimensionner_blocs(), MorEqn::equation(), Nom::getString(), has_interface_blocs(), Equation_base::inconnue(), Field_base::le_nom(), Probleme_U::le_nom(), and Equation_base::probleme().
Referenced by Equation_base::dimensionner_termes_croises().
ajouter_termes_croises()
void Operateur_base::ajouter_termes_croises (const DoubleTab & inco, const Probleme_base & autre_pb, const DoubleTab & autre_inco, DoubleTab & resu) const virtual
Reimplemented in Op_Diff_DG_Elem, and Op_Diff_PolyMAC_Elem.
Referenced by Equation_base::ajouter_termes_croises().
contribuer_termes_croises()
void Operateur_base::contribuer_termes_croises (const DoubleTab & inco, const Probleme_base & autre_pb, const DoubleTab & autre_inco, Matrice_Morse & matrice) const virtual
Reimplemented in Op_Diff_DG_Elem, Op_Diff_PolyMAC_Elem, and Op_Diff_VDF_Elem_base.
References ajouter_blocs(), MorEqn::equation(), Nom::getString(), has_interface_blocs(), Equation_base::inconnue(), Field_base::le_nom(), Probleme_U::le_nom(), and Equation_base::probleme().
Referenced by Equation_base::contribuer_termes_croises().
calculer_dt_stab()
double Operateur_base::calculer_dt_stab () const virtual
Calcul dt_stab.
Returns
(double) renvoie toujours 1.e30
Reimplemented in Op_Conv_ALE_VEF, Operateur_Conv_sensibility_VEF, Op_Diff_K_Eps_Bas_Re_VDF_var_Elem, Op_Diff_DG_base, Op_Conv_EF, Op_Conv_EF_base, Op_Diff_EF_base, Op_Dift_EF_Q1, Op_Conv_PolyMAC_iterateur_base, Op_Conv_EF_Stab_PolyMAC_P0_Face, Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem, Op_Conv_EF_Stab_PolyMAC_P0P1NC_Face, Op_Conv_PolyMAC_base, Op_Diff_PolyMAC_base, Op_Diff_PolyMAC_P0_Elem, Op_Diff_PolyMAC_P0_Face, Op_Diff_PolyMAC_P0P1NC_Elem, Op_Diff_PolyMAC_P0P1NC_Face, Op_Conv_VDF_base, Op_Diff_VDF_Elem_base, Op_Diff_VDF_Face_Axi_base, Op_Diff_VDF_Face_base, Op_Dift_VDF_Face_Axi_base, Op_Dift_VDF_Face_base, Op_Dift_Multiphase_VDF_Elem, Op_Dift_Multiphase_VDF_Face, Op_Dift_VDF_Elem, Op_Dift_VDF_Elem_Axi, Op_Dift_VDF_Multi_inco_Elem, Op_Dift_VDF_Multi_inco_Elem_Axi, Op_Conv_Muscl_New_VEF_Face, Op_Conv_VEF_base, Op_Diff_P1NC_barprim, Op_Diff_VEF_base, Op_Diff_VEF_Face_Q1, Op_Diff_VEFP1NCP1B_Face, Op_Dift_VEF_base, Op_Dift_VEF_Face_Q1, and Op_Dift_VEF_P1NCP1B_Face.
Referenced by Op_Conv_EF::calculer_dt_stab(), Operateur::calculer_pas_de_temps(), and Op_Diff_negligeable::calculer_pour_post().
calculer_dt_local()
void Operateur_base::calculer_dt_local (DoubleTab & dt) const virtual
Reimplemented in Op_Conv_VDF_base, and Op_Conv_VEF_base.
References Process::exit(), and Objet_U::que_suis_je().
Referenced by Operateur::calculer_pas_de_temps_locaux().
completer()
void Operateur_base::completer () virtual
Associe l'operateur au domaine_dis, le domaine_Cl_dis, et a l'inconnue de son equation.
Exceptions
pas d'equation associee
Reimplemented in Op_Conv_ALE_VEF, Op_Diff_K_Eps_Bas_Re_VDF_base, Op_Diff_K_Eps_Bas_Re_VDF_var_Elem, Op_Diff_K_Eps_VDF_base, Op_Diff_K_Omega_VDF_base, Op_Diff_K_Eps_VEF_base, Op_Diff_K_Omega_VEF_base, Op_Diff_DG_base, Op_Diff_DG_Elem, Op_Conv_EF, Op_Conv_BTD_EF, Op_Conv_EF_base, Op_Diff_EF, Op_Dift_EF_base, Op_Conv_PolyMAC_iterateur_base, Op_Conv_EF_Stab_PolyMAC_Face, Op_Conv_EF_Stab_PolyMAC_P0_Face, Op_Conv_PolyMAC_base, Op_Diff_PolyMAC_base, Op_Diff_PolyMAC_P0_base, Op_Diff_PolyMAC_P0P1NC_base, Op_Diff_PolyMAC_Elem, Op_Diff_PolyMAC_Face, Op_Diff_PolyMAC_P0_Elem, Op_Diff_PolyMAC_P0_Face, Op_Diff_PolyMAC_P0P1NC_Elem, Op_Diff_PolyMAC_P0P1NC_Face, Op_Diff_Turbulent_PolyMAC_P0_Elem, Op_Diff_Turbulent_PolyMAC_P0_Face, Op_Grad_PolyMAC_P0_Face, Op_Grad_PolyMAC_P0P1NC_Face, Op_Conv_VDF_base, Op_Diff_VDF_base, Op_Dift_VDF_Face_Axi_base, Op_Diff_VDF_Elem, Op_Diff_VDF_Elem_Axi, Op_Diff_VDF_Elem_aniso, Op_Diff_VDF_Multi_inco_Elem, Op_Diff_VDF_Multi_inco_Multi_scalar_Elem, Op_Diff_VDF_Multi_inco_Elem_Axi, Op_Diff_VDF_Face, Op_Dift_Multiphase_VDF_Elem, Op_Dift_Multiphase_VDF_Face, Op_Dift_VDF_Elem, Op_Dift_VDF_Elem_Axi, Op_Dift_VDF_Multi_inco_Elem, Op_Dift_VDF_Multi_inco_Elem_Axi, Op_Dift_VDF_Face, Op_Div_VDF_base, Op_Conv_EF_VEF_P1NC_Stab, Op_Conv_Muscl_New_VEF_Face, Op_Conv_VEF_Face, Op_Diff_P1NC_barprim, Op_Diff_VEF_Anisotrope_Face, Op_Diff_VEF_Face, Op_Diff_VEF_Face_Q1, Op_Diff_VEF_Face_Stab, Op_Diff_VEFP1NCP1B_Face, Op_Dift_Stab_VEF_Face, and Op_Dift_VEF_base.
References associer(), col_width_, Equation_base::domaine_Cl_dis(), Equation_base::domaine_dis(), MorEqn::equation(), Nom::getSuffix(), Equation_base::inconnue(), le_champ_inco, Field_base::le_nom(), Frontiere_dis_base::le_nom(), Domaine_Cl_dis_base::les_conditions_limites(), Nom::longueur(), MorEqn::mon_equation, Field_base::noms_compo(), TRUST_Ref< _CLASSE_ >::non_nul(), TRUST_Vector< _CLASSE_ >::size(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Operateur::completer(), Op_Conv_ALE_VEF::completer(), Op_Diff_K_Eps_Bas_Re_VDF_base::completer(), Op_Diff_K_Eps_VDF_base::completer(), Op_Diff_K_Omega_VDF_base::completer(), Op_Diff_K_Omega_VEF_base::completer(), Op_Diff_DG_base::completer(), Op_Conv_EF_base::completer(), Op_Diff_EF::completer(), Op_Dift_EF_base::completer(), Op_Conv_PolyMAC_iterateur_base::completer(), Op_Conv_PolyMAC_base::completer(), Op_Diff_PolyMAC_base::completer(), Op_Diff_PolyMAC_P0_base::completer(), Op_Diff_PolyMAC_P0P1NC_base::completer(), Op_Grad_PolyMAC_P0_Face::completer(), Op_Grad_PolyMAC_P0P1NC_Face::completer(), Op_Conv_VDF_base::completer(), Op_Diff_VDF_base::completer(), Op_Div_VDF_base::completer(), Op_Conv_VEF_Face::completer(), Op_Diff_P1NC_barprim::completer(), Op_Diff_VEF_Anisotrope_Face::completer(), Op_Diff_VEF_Face::completer(), Op_Diff_VEF_Face_Q1::completer(), and Op_Dift_VEF_base::completer().
mettre_a_jour()
void Operateur_base::mettre_a_jour (double temps) virtual
DOES NOTHING - to override in derived classes.
Mise a jour de l'operateur
Parameters
(double) un pas de temps
Reimplemented in Op_Diff_DG_base, Op_Diff_PolyMAC_base, Op_Diff_PolyMAC_P0_base, Op_Diff_PolyMAC_P0P1NC_base, Op_Diff_PolyMAC_Elem, Op_Diff_PolyMAC_P0_Elem, Op_Dift_EF_base, Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem, Op_Diff_Turbulent_PolyMAC_P0_Elem, Op_Diff_Turbulent_PolyMAC_P0_Face, Op_Diff_VDF_Face_Axi_base, Op_Dift_VEF_base, Op_Grad_EF, Op_Conv_negligeable, Op_Diff_negligeable, Op_Conv_VDF_base, Op_Dift_VDF_Face_Axi_base, Op_Diff_VDF_Face, Op_Dift_Multiphase_VDF_Elem, and Op_Dift_Multiphase_VDF_Face.
Referenced by Op_Diff_DG_base::mettre_a_jour(), Op_Diff_PolyMAC_base::mettre_a_jour(), Op_Diff_PolyMAC_P0_base::mettre_a_jour(), Op_Diff_PolyMAC_P0P1NC_base::mettre_a_jour(), Operateur::mettre_a_jour(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::mettre_a_jour(), Op_Grad_EF::mettre_a_jour(), Op_Conv_VDF_base::mettre_a_jour(), Op_Dift_Multiphase_VDF_Elem::mettre_a_jour(), and Equation_base::updateGivenFields().
abortTimeStep()
void Operateur_base::abortTimeStep () virtual
Reimplemented in Op_Conv_VEF_base.
Referenced by Equation_base::abortTimeStep(), and Op_Conv_VEF_base::abortTimeStep().
resetTime()
void Operateur_base::resetTime (double time) virtual
Referenced by Equation_base::resetTime().
impr()
int Operateur_base::impr (Sortie & os) const virtual
DOES NOTHING - to override in derived classes.
Imprime l'operateur sur un flot de sortie.
Parameters
(Sortie& os)
Returns
(int) renvoie toujours 1
Reimplemented in Op_Grad_VEF_P1B_Face, Op_Diff_DG_base, Op_Conv_EF_base, Op_Diff_EF_base, Op_Div_EF, Op_Grad_EF, Op_Conv_PolyMAC_iterateur_base, Op_Conv_PolyMAC_base, Op_Diff_PolyMAC_Gen_base, Op_Div_PolyMAC, Op_Grad_PolyMAC_Face, Op_Conv_VDF_base, Op_Diff_VDF_base, Op_Div_VDF_base, Op_Grad_VDF_Face, Op_Grad_VDF_Face_base, Op_Conv_VEF_base, Op_Diff_VEF_base, and Op_Div_VEFP1B_Elem.
Referenced by Operateur::impr(), and Operateur::imprimer().
associer_eqn()
void Operateur_base::associer_eqn (const Equation_base & eqn) inline
Associe une equation a l'operateur.
Simple Appel a MorEqn::associer_eqn(const Equation_base&)
Parameters
(Equation_base& eqn) l'equation a laquelle l'operateur doit etre associe
References MorEqn::associer_eqn().
Referenced by Convection_diffusion_turbulence_multiphase::completer(), Transport_K_Omega::completer(), Convection_Diffusion_Chaleur_WC::completer(), Masse_Multiphase::completer(), Champ_Generique_Divergence::completer(), Champ_Generique_Gradient::completer(), Convection_Diffusion_Temperature_FT_Disc::compute_divergence_free_velocity_extension(), Convection_Diffusion_Phase_field::discretiser(), Navier_Stokes_std::discretiser(), Operateur::lire(), Convection_Diffusion_Turbulent::lire_op_diff_turbulent(), Navier_Stokes_Turbulent_ALE::lire_op_diff_turbulent(), Transport_2eq_base::lire_op_diff_turbulent(), Navier_Stokes_IBM_Turbulent::lire_op_diff_turbulent(), Navier_Stokes_Turbulent::lire_op_diff_turbulent(), Op_Evanescence_Homogene_VDF_Face::preparer_calcul(), Equation_rayonnement_base::readOn(), Op_Diff_Fluctu_Temp::typer(), and Op_Diff_Flux_Chaleur_Turb::typer().
get_decal_temps()
int Operateur_base::get_decal_temps () const inline
References decal_temps.
Referenced by Equation_base::completer(), Equation_base::derivee_en_temps_inco(), and Navier_Stokes_std::derivee_en_temps_inco().
set_decal_temps()
int Operateur_base::set_decal_temps (int i) inline
References decal_temps.
Referenced by Operateur::lire().
get_nb_ss_pas_de_temps()
int Operateur_base::get_nb_ss_pas_de_temps () const inline
References nb_ss_pas_de_temps.
Referenced by Operateur::ajouter().
set_nb_ss_pas_de_temps()
int Operateur_base::set_nb_ss_pas_de_temps (int i) inline
References nb_ss_pas_de_temps.
Referenced by Operateur::lire().
get_matrice()
const Matrice & Operateur_base::get_matrice () const inline
References matrice_.
Referenced by Equation_base::derivee_en_temps_inco(), and Navier_Stokes_std::derivee_en_temps_inco().
set_matrice()
Matrice & Operateur_base::set_matrice () inline
References matrice_.
Referenced by Equation_base::derivee_en_temps_inco(), and Navier_Stokes_std::derivee_en_temps_inco().
get_solveur()
const SolveurSys & Operateur_base::get_solveur () const inline
References solveur.
Referenced by Equation_base::derivee_en_temps_inco(), and Navier_Stokes_std::derivee_en_temps_inco().
set_solveur()
SolveurSys & Operateur_base::set_solveur () inline
References solveur.
Referenced by Equation_base::derivee_en_temps_inco(), and Navier_Stokes_std::derivee_en_temps_inco().
lire_solveur()
Entree & Operateur_base::lire_solveur (Entree & is) inline
References solveur.
Referenced by Operateur::lire().
systeme_invariant()
int Operateur_base::systeme_invariant () const virtual
Referenced by Equation_base::completer().
ajouter_contribution_explicite_au_second_membre()
void Operateur_base::ajouter_contribution_explicite_au_second_membre (const Champ_Inc_base & inconnue, DoubleTab & derivee) const virtual
References ajouter(), and Champ_Inc_base::valeurs().
Referenced by Operateur::ajouter_contribution_explicite_au_second_membre().
mon_inconnue()
const Champ_Inc_base & Operateur_base::mon_inconnue () const inline
References le_champ_inco, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Op_Diff_PolyMAC_P0_Elem::ajouter_blocs(), Op_Diff_PolyMAC_P0P1NC_Elem::ajouter_blocs_ext(), and Op_Diff_PolyMAC_P0P1NC_Elem::dimensionner_blocs_ext().
has_champ_inco()
bool Operateur_base::has_champ_inco () const inline
References le_champ_inco, and TRUST_Ref< _CLASSE_ >::non_nul().
Referenced by Op_Diff_PolyMAC_P0_Elem::ajouter_blocs(), Op_Diff_PolyMAC_P0P1NC_Elem::ajouter_blocs_ext(), Op_Diff_PolyMAC_P0P1NC_Elem::dimensionner_blocs_ext(), and nom_inconnue().
nom_inconnue()
const std::string & Operateur_base::nom_inconnue () const inline
References has_champ_inco(), and nom_inco_.
Referenced by Op_Conv_VDF_base::associer_champ_convecte_elem(), Op_Conv_VDF_base::associer_champ_convecte_face(), and Op_Diff_VDF_base::completer().
ouvrir_fichier()
void Operateur_base::ouvrir_fichier (SFichier & os, const Nom & type, const int flag = 1) const
Ouverture/creation d'un fichier d'impression d'un operateur A surcharger dans les classes derivees.
Exceptions
methode a surcharger
References Process::abort(), TRUST_List< _CLASSE_ >::add(), Sortie::add_col(), Domaine_base::bords_a_imprimer_sum(), col_width_, TRUST_List< _CLASSE_ >::contient(), description(), Objet_U::dimension, Domaine_dis_base::domaine(), Champ_Inc_base::domaine_Cl_dis(), Equation_base::domaine_dis(), MorEqn::equation(), Process::exit(), flux_bords_, Probleme_base::get_set_out_files(), Nom::getChar(), Nom::getSuffix(), Schema_Temps_base::gnuplot_header(), Equation_base::inconnue(), Sortie_Fichier_base::is_open(), Process::je_suis_maitre(), Field_base::le_nom(), Frontiere_dis_base::le_nom(), Probleme_U::le_nom(), Domaine_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Schema_Temps_base::nb_impr(), Objet_U::nom_du_cas(), Field_base::noms_compo(), out_, Sortie_Fichier_base::ouvrir(), Sortie_Fichier_base::precision(), Schema_Temps_base::precision_impr(), Equation_base::probleme(), Objet_U::que_suis_je(), Probleme_base::reprise_effectuee(), Probleme_base::schema_temps(), Sortie::set_col_width(), Sortie_Fichier_base::setf(), TRUST_Vector< _CLASSE_ >::size(), and Schema_Temps_base::wcol().
Referenced by Op_Grad_VEF_P1B_Face::impr(), Op_EF_base::impr(), Op_VEF_Face::impr(), Op_Div_EF::impr(), Op_Grad_EF::impr(), Op_Conv_PolyMAC_base::impr(), Op_Diff_PolyMAC_Gen_base::impr(), Op_Div_PolyMAC::impr(), Op_Grad_VDF_Face::impr(), and Op_Div_VEFP1B_Elem::impr().
ouvrir_fichier_partage()
void Operateur_base::ouvrir_fichier_partage (EcrFicPartage & os, const Nom & type, const int flag = 1) const
Ouverture/creation d'un fichier d'impression d'un operateur A surcharger dans les classes derivees.
Exceptions
methode a surcharger
References MorEqn::equation(), Schema_Temps_base::nb_impr(), out_, EcrFicPartage::ouvrir(), EcrFicPartage::precision(), Schema_Temps_base::precision_impr(), Equation_base::probleme(), Probleme_base::reprise_effectuee(), Probleme_base::schema_temps(), and Sortie_Fichier_base::setf().
Referenced by Op_Grad_VEF_P1B_Face::impr(), Op_EF_base::impr(), Op_VEF_Face::impr(), Op_Div_EF::impr(), Op_Grad_EF::impr(), Op_Conv_PolyMAC_base::impr(), Op_Diff_PolyMAC_Gen_base::impr(), Op_Div_PolyMAC::impr(), Op_Grad_VDF_Face::impr(), and Op_Div_VEFP1B_Elem::impr().
set_fichier()
void Operateur_base::set_fichier (const Nom & nom)
References MorEqn::equation(), Process::exit(), Probleme_U::le_nom(), Objet_U::nom_du_cas(), out_, Equation_base::probleme(), and Objet_U::que_suis_je().
Referenced by Operateur::set_fichier().
fichier()
const Nom Operateur_base::fichier () const inline
References out_.
set_description()
void Operateur_base::set_description (const Nom & nom) inline
References description_.
Referenced by Operateur::set_description().
description()
const Nom Operateur_base::description () const inline
References description_.
Referenced by ouvrir_fichier().
flux_bords() [1/2]
DoubleTab & Operateur_base::flux_bords () inline
References flux_bords_.
Referenced by Terme_Source_Th_TdivU_VEF_Face::ajouter(), Op_Conv_Amont_VPoly_VDF_Face::ajouter_blocs(), Op_Diff_VEF_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Face::ajouter_cas_vectoriel(), Champ_P1NC::calcul_h_conv(), Modele_turbulence_scal_LES_dyn_VDF::calculer_grad_teta(), Terme_Source_Canal_perio::compute_heat_flux(), Domaine_ALE::computeFluidForceOnBeam(), Op_EF_base::impr(), Op_VEF_Face::impr(), Op_Conv_PolyMAC_base::impr(), Op_Diff_PolyMAC_Gen_base::impr(), Op_EF_base::modifier_flux(), Op_VEF_Face::modifier_flux(), and Domaine_ALE::update_ALE_projection().
flux_bords() [2/2]
DoubleTab & Operateur_base::flux_bords () const inline
References flux_bords_.
creer_champ()
void Operateur_base::creer_champ (const Motcle & motlu) inline override virtual
Implements Champs_compris_interface.
Reimplemented in Op_Conv_VDF_base, Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem, Op_Diff_Turbulent_PolyMAC_P0_Elem, Op_Diff_Turbulent_PolyMAC_P0_Face, Op_Dift_Multiphase_VDF_Elem, and Op_Dift_Multiphase_VDF_Face.
Referenced by Op_Conv_VDF_base::creer_champ(), Equation_base::creer_champ(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::creer_champ(), Op_Diff_Turbulent_PolyMAC_P0_Elem::creer_champ(), Op_Diff_Turbulent_PolyMAC_P0_Face::creer_champ(), Op_Dift_Multiphase_VDF_Elem::creer_champ(), and Op_Dift_Multiphase_VDF_Face::creer_champ().
get_champ()
const Champ_base & Operateur_base::get_champ (const Motcle & nom) const override virtual
Implements Champs_compris_interface.
References champs_compris_, and Champs_compris_T< FIELD_TYPE >::get_champ().
Referenced by Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::ajouter_blocs(), and Op_Conv_EF::get_champ().
has_champ() [1/2]
bool Operateur_base::has_champ (const Motcle & nom, TRUST_Ref< Champ_base * > & ref_champ) const override virtual
Implements Champs_compris_interface.
References champs_compris_, and Champs_compris_T< FIELD_TYPE >::has_champ().
Referenced by Equation_base::get_champ(), Op_Conv_EF::has_champ(), and Equation_base::has_champ().
has_champ() [2/2]
bool Operateur_base::has_champ (const Motcle & nom) const override virtual
Implements Champs_compris_interface.
References champs_compris_, and Champs_compris_T< FIELD_TYPE >::has_champ().
get_noms_champs_postraitables()
void Operateur_base::get_noms_champs_postraitables (Noms & nom, Option opt = NONE) const override virtual
Implements Champs_compris_interface.
Reimplemented in Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem, Op_Diff_Turbulent_PolyMAC_P0_Elem, Op_Diff_Turbulent_PolyMAC_P0_Face, Op_Conv_VDF_base, Op_Dift_Multiphase_VDF_Elem, and Op_Dift_Multiphase_VDF_Face.
References TRUST_Vector< _CLASSE_ >::add(), champs_compris_, Champs_compris_T< FIELD_TYPE >::liste_noms_compris(), and Objet_U::que_suis_je().
Referenced by Equation_base::get_noms_champs_postraitables(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::get_noms_champs_postraitables(), Op_Diff_Turbulent_PolyMAC_P0_Elem::get_noms_champs_postraitables(), Op_Diff_Turbulent_PolyMAC_P0_Face::get_noms_champs_postraitables(), Op_Conv_VDF_base::get_noms_champs_postraitables(), Op_Dift_Multiphase_VDF_Elem::get_noms_champs_postraitables(), and Op_Dift_Multiphase_VDF_Face::get_noms_champs_postraitables().
calculer_pour_post()
void Operateur_base::calculer_pour_post (Champ_base & espace_stockage, const Nom & option, int comp) const override virtual
Reimplemented from MorEqn.
Reimplemented in Op_Diff_negligeable, Op_Conv_PolyMAC_iterateur_base, Op_Conv_VDF_base, Op_Conv_VEF_base, Op_Diff_VEF_base, and Op_Dift_VEF_base.
References Equation_base::domaine_Cl_dis(), Equation_base::domaine_dis(), MorEqn::equation(), Process::exit(), flux_bords_, Domaine_Cl_dis_base::les_conditions_limites(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), and Champ_Proto::valeurs().
Referenced by Op_Diff_negligeable::calculer_pour_post(), Op_Conv_PolyMAC_iterateur_base::calculer_pour_post(), Op_Conv_VDF_base::calculer_pour_post(), Op_Conv_VEF_base::calculer_pour_post(), and Op_Diff_VEF_base::calculer_pour_post().
get_localisation_pour_post()
Motcle Operateur_base::get_localisation_pour_post (const Nom & option) const override virtual
Reimplemented from MorEqn.
Reimplemented in Op_Diff_negligeable, Op_Conv_PolyMAC_iterateur_base, Op_Conv_VDF_base, Op_Conv_VEF_base, and Op_Diff_VEF_base.
References MorEqn::equation(), Process::exit(), and Objet_U::que_suis_je().
Referenced by Op_Conv_PolyMAC_iterateur_base::get_localisation_pour_post(), Op_Conv_VDF_base::get_localisation_pour_post(), Op_Conv_VEF_base::get_localisation_pour_post(), and Op_Diff_VEF_base::get_localisation_pour_post().
ajouter_flux()
void Operateur_base::ajouter_flux (const DoubleTab & inconnue, DoubleTab & contribution) const virtual
Reimplemented in Op_Conv_negligeable, and Op_Diff_negligeable.
References Process::exit().
Referenced by calculer_flux().
calculer_flux()
void Operateur_base::calculer_flux (const DoubleTab & inconnue, DoubleTab & flux) const virtual
Reimplemented in Op_Conv_negligeable, and Op_Diff_negligeable.
References ajouter_flux().
preparer_calcul()
void Operateur_base::preparer_calcul () virtual
Reimplemented in Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem, Op_Diff_Turbulent_PolyMAC_P0_Face, Op_Evanescence_Homogene_VDF_Face, Op_Conv_VDF_base, Op_Conv_Amont_VDF_Elem, Op_Conv_Centre_VDF_Elem, Op_Conv_Centre4_VDF_Elem, Op_Conv_Quick_VDF_Elem, Op_Conv_Amont_VDF_Face, Op_Conv_Centre_VDF_Face, Op_Conv_Centre4_VDF_Face, Op_Conv_Quick_VDF_Face_Axi, Op_Conv_Quick_VDF_Face, and Op_Dift_Multiphase_VDF_Face.
Referenced by Equation_base::preparer_calcul(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::preparer_calcul(), Op_Diff_Turbulent_PolyMAC_P0_Face::preparer_calcul(), Op_Evanescence_Homogene_VDF_Face::preparer_calcul(), Op_Conv_VDF_base::preparer_calcul(), and Op_Dift_Multiphase_VDF_Face::preparer_calcul().
has_impr_file()
bool Operateur_base::has_impr_file () const inline
References out_.
Member Data Documentation
info_obj
const Type_info Operateur_base::info_obj static
col_width_
int Operateur_base::col_width_
Referenced by completer(), Operateur_base(), and ouvrir_fichier().
decal_temps
int Operateur_base::decal_temps protected
Referenced by get_decal_temps(), Operateur_base(), and set_decal_temps().
nb_ss_pas_de_temps
int Operateur_base::nb_ss_pas_de_temps protected
Referenced by get_nb_ss_pas_de_temps(), Operateur_base(), and set_nb_ss_pas_de_temps().
solveur
SolveurSys Operateur_base::solveur protected
Referenced by Op_Diff_RotRot::associer(), get_solveur(), lire_solveur(), and set_solveur().
matrice_
Matrice Operateur_base::matrice_ protected
Referenced by get_matrice(), and set_matrice().
out_
Nom Operateur_base::out_ protected
Referenced by fichier(), has_impr_file(), ouvrir_fichier(), ouvrir_fichier_partage(), and set_fichier().
description_
Nom Operateur_base::description_ protected
Referenced by description(), and set_description().
flux_bords_
DoubleTab Operateur_base::flux_bords_ mutable protected
Referenced by Operateur_Conv_sensibility_VEF::add_diffusion_scalar_term(), Operateur_Conv_sensibility_VEF::add_diffusion_term(), Operateur_Conv_sensibility_VEF::ajouter(), Op_Diff_K_Eps_VEF_Face::ajouter(), Op_Diff_K_Omega_VEF_Face::ajouter(), Op_Div_EF::ajouter(), Op_Diff_PolyMAC_Elem::ajouter(), Op_Div_PolyMAC::ajouter(), Op_Div_PolyMAC_P0::ajouter(), Op_Conv_Amont_old_VEF_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Centre_EF_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_EF_VEF_P1NC_Stab::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_Muscl_New_VEF_Face::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Conv_Vort_VEF_Face::ajouter(), Op_Diff_VEF_Anisotrope_Face::ajouter(), Op_Diff_VEF_Face::ajouter(), Op_Dift_Stab_VEF_Face::ajouter(), Op_Dift_VEF_Face::ajouter(), Op_Div_VEFP1B_Elem::ajouter(), Op_Diff_PolyMAC_P0_Elem::ajouter_blocs(), Op_Div_PolyMAC_P0P1NC::ajouter_blocs_ext(), Op_Diff_PolyMAC_P0P1NC_Elem::ajouter_blocs_ext(), Op_Diff_EF::ajouter_bords(), Op_Dift_EF_Q1::ajouter_bords(), Operateur_Conv_sensibility_VEF::ajouter_Lsensibility_state_Amont(), Operateur_Conv_sensibility_VEF::ajouter_Lstate_sensibility_Amont(), Op_Conv_ALE_VEF::ajouterALE(), Op_Diff_EF_base::associer(), Op_Diff_VEF_base::associer(), Op_Grad_EF::calculer_flux_bords(), Op_Grad_VDF_Face::calculer_flux_bords(), Op_Grad_VEF_P1B_Face::calculer_flux_bords(), Op_Diff_VEFP1NCP1B_Face::calculer_flux_bords_elem(), Op_Diff_VEFP1NCP1B_Face::calculer_flux_bords_som(), calculer_pour_post(), Op_Diff_DG_Elem::completer(), Op_Diff_PolyMAC_Elem::completer(), Op_Diff_PolyMAC_P0_Elem::completer(), Op_Diff_PolyMAC_P0_Face::completer(), Op_Diff_PolyMAC_P0P1NC_Elem::completer(), Op_Diff_PolyMAC_P0P1NC_Face::completer(), flux_bords(), Op_Grad_VEF_P1B_Face::impr(), Op_Div_EF::impr(), Op_Grad_EF::impr(), Op_Div_PolyMAC::impr(), Op_Grad_VDF_Face::impr(), Op_Div_VEFP1B_Elem::impr(), Op_Diff_VEFP1NCP1B_Face::initialiser(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::mettre_a_jour(), Op_Diff_VEF_Face_Stab::modifie_pour_Cl(), ouvrir_fichier(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::preparer_calcul(), Op_Conv_EF_base::remplir_fluent(), and Op_Conv_VEF_base::remplir_fluent().
champs_compris_
Champs_compris Operateur_base::champs_compris_ protected
Referenced by Op_Conv_VDF_base::creer_champ(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::creer_champ(), get_champ(), get_noms_champs_postraitables(), has_champ(), Op_Diff_Turbulent_PolyMAC_P0_Elem::readOn(), Op_Diff_Turbulent_PolyMAC_P0_Face::readOn(), Op_Dift_Multiphase_VDF_Elem::readOn(), and Op_Dift_Multiphase_VDF_Face::readOn().
le_champ_inco
TRUST_Ref< Champ_Inc_base *> Operateur_base::le_champ_inco protected
Referenced by Op_Grad_VDF_Face::ajouter_blocs(), Op_Diff_PolyMAC_P0_Face::ajouter_blocs(), Op_Grad_PolyMAC_P0_Face::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::ajouter_blocs(), Op_Diff_PolyMAC_P0P1NC_Elem::ajouter_blocs_ext(), Op_Diff_PolyMAC_P0P1NC_Face::ajouter_blocs_ext(), associer_champ(), Op_Conv_VDF_base::associer_champ_convecte_elem(), Op_Conv_VDF_base::associer_champ_convecte_face(), completer(), Op_Diff_PolyMAC_P0_Face::completer(), Op_Diff_PolyMAC_P0P1NC_Elem::completer(), Op_Diff_PolyMAC_P0P1NC_Face::completer(), Op_Diff_VDF_base::completer(), Op_Grad_VDF_Face::dimensionner_blocs(), Op_Grad_PolyMAC_P0_Face::dimensionner_blocs(), Op_Diff_PolyMAC_P0P1NC_Elem::dimensionner_blocs_ext(), Op_Diff_PolyMAC_P0P1NC_Face::dimensionner_blocs_ext(), has_champ_inco(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::mettre_a_jour(), Op_Conv_VDF_base::mettre_a_jour(), mon_inconnue(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::preparer_calcul(), Op_Diff_PolyMAC_P0P1NC_base::update_aux(), and Op_Grad_PolyMAC_P0_Face::update_grad().
nom_inco_
std::string Operateur_base::nom_inco_ protected
Referenced by associer_champ(), and nom_inconnue().