TrioCFD: IJK_One_Dimensional_Subproblems_Interfaces_Fields Class Reference
IJK_One_Dimensional_Subproblems_Interfaces_Fields Class Reference
#include <IJK_One_Dimensional_Subproblems_Interfaces_Fields.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
IJK_One_Dimensional_Subproblems_Interfaces_Fields()
IJK_One_Dimensional_Subproblems_Interfaces_Fields::IJK_One_Dimensional_Subproblems_Interfaces_Fields ()
~IJK_One_Dimensional_Subproblems_Interfaces_Fields()
IJK_One_Dimensional_Subproblems_Interfaces_Fields::~IJK_One_Dimensional_Subproblems_Interfaces_Fields ()
Member Function Documentation
cree_instance()
Objet_U * IJK_One_Dimensional_Subproblems_Interfaces_Fields::cree_instance () static
taille_memoire()
unsigned IJK_One_Dimensional_Subproblems_Interfaces_Fields::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int IJK_One_Dimensional_Subproblems_Interfaces_Fields::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * IJK_One_Dimensional_Subproblems_Interfaces_Fields::info () static
get_info()
const Type_info * IJK_One_Dimensional_Subproblems_Interfaces_Fields::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
IJK_One_Dimensional_Subproblems_Interfaces_Fields & IJK_One_Dimensional_Subproblems_Interfaces_Fields::self_cast (Objet_U & r) static
self_cast() [2/2]
const IJK_One_Dimensional_Subproblems_Interfaces_Fields & IJK_One_Dimensional_Subproblems_Interfaces_Fields::self_cast (const Objet_U & r) static
printOn()
Sortie & IJK_One_Dimensional_Subproblems_Interfaces_Fields::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
References Objet_U::printOn().
readOn()
Entree & IJK_One_Dimensional_Subproblems_Interfaces_Fields::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
References Objet_U::readOn().
initialise()
void IJK_One_Dimensional_Subproblems_Interfaces_Fields::initialise (const Domaine_IJK & splitting, IJK_One_Dimensional_Subproblems & thermal_local_subproblems, const int & debug)
References IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::allocate(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::data(), debug_, IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel(), Domaine_IJK::ELEM, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost(), ref_ijk_ft_, thermal_local_subproblems_, tmp_field_val_, and tmp_ft_field_val_.
Referenced by IJK_Thermal_Subresolution::set_subproblems_interfaces_fields().
associer()
void IJK_One_Dimensional_Subproblems_Interfaces_Fields::associer (const Probleme_FTD_IJK_base & ijk_ft)
References Postprocessing_IJK::get_liste_post_instantanes(), Probleme_FTD_IJK_base::get_post(), liste_post_instantanes_, and ref_ijk_ft_.
Referenced by IJK_Thermal_base::associer().
set_subproblems_interfaces_fields()
void IJK_One_Dimensional_Subproblems_Interfaces_Fields::set_subproblems_interfaces_fields (const int & interface_field_type)
References interface_field_type_.
Referenced by IJK_Thermal_Subresolution::set_subproblems_interfaces_fields().
copy_previous_interface_state()
void IJK_One_Dimensional_Subproblems_Interfaces_Fields::copy_previous_interface_state ()
References interface_field_type_.
Referenced by IJK_Thermal_base::copy_previous_interface_state().
reset_flags()
void IJK_One_Dimensional_Subproblems_Interfaces_Fields::reset_flags ()
References counter_call_, updated_interfacial_heat_flux_, updated_interfacial_heat_flux_sol_, updated_temperature_, updated_temperature_gradient_, updated_temperature_gradient_sol_, updated_temperature_sol_, and updated_velocity_magnitude_.
Referenced by posttraiter_champs_instantanes().
posttraiter_tous_champs()
void IJK_One_Dimensional_Subproblems_Interfaces_Fields::posttraiter_tous_champs (Motcles & liste) const
References TRUST_Vector< _CLASSE_ >::add().
posttraiter_champs_instantanes()
int IJK_One_Dimensional_Subproblems_Interfaces_Fields::posttraiter_champs_instantanes (const Motcles & liste_post_instantanes, const char * lata_name, const int lata_step)
References Motcles::contient_(), interface_field_type_, interfacial_heat_flux_, interfacial_heat_flux_sol_, reset_flags(), retrieve_interfacial_surface_quantities(), temperature_, temperature_gradient_, temperature_gradient_sol_, temperature_sol_, and velocity_magnitude_.
Referenced by IJK_Thermal_base::post_process_quantities_from_subresolution().
retrieve_interfacial_surface_quantities()
bool IJK_One_Dimensional_Subproblems_Interfaces_Fields::retrieve_interfacial_surface_quantities (const Nom & surface_post_name) protected
References interfacial_heat_flux_, interfacial_heat_flux_sol_, retrieve_interfacial_surface_quantity(), temperature_, temperature_gradient_, temperature_gradient_sol_, temperature_sol_, updated_interfacial_heat_flux_, updated_interfacial_heat_flux_sol_, updated_temperature_, updated_temperature_gradient_, updated_temperature_gradient_sol_, updated_temperature_sol_, updated_velocity_magnitude_, and velocity_magnitude_.
Referenced by posttraiter_champs_instantanes().
retrieve_interfacial_surface_quantity()
bool IJK_One_Dimensional_Subproblems_Interfaces_Fields::retrieve_interfacial_surface_quantity (ArrOfDouble & surface_quantity, bool & has_been_updated, const int & val_index) protected
References TRUSTArray< _TYPE_, _SIZE_ >::append_array(), averaged_by_vertex_surface(), Domaine_IJK::convert_ijk_cell_to_packed(), Domaine_IJK::convert_packed_to_ijk_cell(), counter_call_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::data(), Intersections_Elem_Facettes::data_intersection(), debug_, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Domaine_dis_base::domaine(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel(), elem_crossed_, eulerian_values_, Maillage_FT_Disc::facettes(), Intersections_Elem_Facettes_Data::fraction_surface_intersection_, IJK_Interfaces::get_domaine_dis(), IJK_One_Dimensional_Subproblems::get_effective_subproblems_counter(), get_surrounding_value(), IJK_One_Dimensional_Subproblems::get_thermal_subproblem_value_at_ijk_index(), Maillage_FT_Disc::get_update_surface_facettes(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost(), Intersections_Elem_Facettes::index_elem(), Intersections_Elem_Facettes_Data::index_facette_suivante_, Maillage_FT_Disc::intersections_elem_facettes(), IJK_Interfaces::maillage_ft_ijk(), Domaine_32_64< _SIZE_ >::nb_elem(), Intersections_Elem_Facettes_Data::numero_facette_, ref_ijk_ft_, TRUSTArray< _TYPE_, _SIZE_ >::reset(), TRUSTArray< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), Maillage_FT_Disc::sommet_elem(), Maillage_FT_Disc::sommets(), thermal_local_subproblems_, tmp_field_val_, tmp_ft_field_val_, and vertices_surface_.
Referenced by retrieve_interfacial_surface_quantities().
averaged_by_vertex_surface()
void IJK_One_Dimensional_Subproblems_Interfaces_Fields::averaged_by_vertex_surface (ArrOfDouble & surface_quantity) protected
References debug_, TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and vertices_surface_.
Referenced by retrieve_interfacial_surface_quantity().
get_surrounding_value()
void IJK_One_Dimensional_Subproblems_Interfaces_Fields::get_surrounding_value (const int & i, const int & j, const int & k, double & eulerian_value) protected
References tmp_ft_field_val_.
Referenced by retrieve_interfacial_surface_quantity().
Member Data Documentation
info_obj
const Type_info IJK_One_Dimensional_Subproblems_Interfaces_Fields::info_obj static
ref_ijk_ft_
TRUST_Ref< Probleme_FTD_IJK_base *> IJK_One_Dimensional_Subproblems_Interfaces_Fields::ref_ijk_ft_ protected
Referenced by associer(), initialise(), and retrieve_interfacial_surface_quantity().
liste_post_instantanes_
Motcles IJK_One_Dimensional_Subproblems_Interfaces_Fields::liste_post_instantanes_ protected
Referenced by associer().
thermal_local_subproblems_
IJK_One_Dimensional_Subproblems* IJK_One_Dimensional_Subproblems_Interfaces_Fields::thermal_local_subproblems_ = nullptr protected
Referenced by initialise(), and retrieve_interfacial_surface_quantity().
interface_field_type_
int IJK_One_Dimensional_Subproblems_Interfaces_Fields::interface_field_type_ = 0 protected
Referenced by copy_previous_interface_state(), posttraiter_champs_instantanes(), and set_subproblems_interfaces_fields().
counter_call_
int IJK_One_Dimensional_Subproblems_Interfaces_Fields::counter_call_ = 0 protected
Referenced by reset_flags(), and retrieve_interfacial_surface_quantity().
debug_
int IJK_One_Dimensional_Subproblems_Interfaces_Fields::debug_ = 0 protected
Referenced by averaged_by_vertex_surface(), initialise(), and retrieve_interfacial_surface_quantity().
ft_vertices_
DoubleTab IJK_One_Dimensional_Subproblems_Interfaces_Fields::ft_vertices_ protected
elem_crossed_
ArrOfInt IJK_One_Dimensional_Subproblems_Interfaces_Fields::elem_crossed_ protected
Referenced by retrieve_interfacial_surface_quantity().
eulerian_values_
ArrOfDouble IJK_One_Dimensional_Subproblems_Interfaces_Fields::eulerian_values_ protected
Referenced by retrieve_interfacial_surface_quantity().
vertices_surface_
ArrOfDouble IJK_One_Dimensional_Subproblems_Interfaces_Fields::vertices_surface_ protected
Referenced by averaged_by_vertex_surface(), and retrieve_interfacial_surface_quantity().
interfacial_heat_flux_
ArrOfDouble IJK_One_Dimensional_Subproblems_Interfaces_Fields::interfacial_heat_flux_ protected
Referenced by posttraiter_champs_instantanes(), and retrieve_interfacial_surface_quantities().
interfacial_heat_flux_sol_
ArrOfDouble IJK_One_Dimensional_Subproblems_Interfaces_Fields::interfacial_heat_flux_sol_ protected
Referenced by posttraiter_champs_instantanes(), and retrieve_interfacial_surface_quantities().
velocity_magnitude_
ArrOfDouble IJK_One_Dimensional_Subproblems_Interfaces_Fields::velocity_magnitude_ protected
Referenced by posttraiter_champs_instantanes(), and retrieve_interfacial_surface_quantities().
temperature_
ArrOfDouble IJK_One_Dimensional_Subproblems_Interfaces_Fields::temperature_ protected
Referenced by posttraiter_champs_instantanes(), and retrieve_interfacial_surface_quantities().
temperature_sol_
ArrOfDouble IJK_One_Dimensional_Subproblems_Interfaces_Fields::temperature_sol_ protected
Referenced by posttraiter_champs_instantanes(), and retrieve_interfacial_surface_quantities().
temperature_gradient_
ArrOfDouble IJK_One_Dimensional_Subproblems_Interfaces_Fields::temperature_gradient_ protected
Referenced by posttraiter_champs_instantanes(), and retrieve_interfacial_surface_quantities().
temperature_gradient_sol_
ArrOfDouble IJK_One_Dimensional_Subproblems_Interfaces_Fields::temperature_gradient_sol_ protected
Referenced by posttraiter_champs_instantanes(), and retrieve_interfacial_surface_quantities().
tmp_field_val_
IJK_Field_double IJK_One_Dimensional_Subproblems_Interfaces_Fields::tmp_field_val_ protected
Referenced by initialise(), and retrieve_interfacial_surface_quantity().
tmp_ft_field_val_
IJK_Field_double IJK_One_Dimensional_Subproblems_Interfaces_Fields::tmp_ft_field_val_ protected
Referenced by get_surrounding_value(), initialise(), and retrieve_interfacial_surface_quantity().
tmp_field_double_
IJK_Field_double IJK_One_Dimensional_Subproblems_Interfaces_Fields::tmp_field_double_ protected
tmp_ft_field_double_
IJK_Field_double IJK_One_Dimensional_Subproblems_Interfaces_Fields::tmp_ft_field_double_ protected
tmp_ft_field_int_
IJK_Field_int IJK_One_Dimensional_Subproblems_Interfaces_Fields::tmp_ft_field_int_ protected
surface_facettes_
ArrOfDouble IJK_One_Dimensional_Subproblems_Interfaces_Fields::surface_facettes_ protected
facettes_
IntTab IJK_One_Dimensional_Subproblems_Interfaces_Fields::facettes_ protected
updated_interfacial_heat_flux_
bool IJK_One_Dimensional_Subproblems_Interfaces_Fields::updated_interfacial_heat_flux_ = false protected
Referenced by reset_flags(), and retrieve_interfacial_surface_quantities().
updated_interfacial_heat_flux_sol_
bool IJK_One_Dimensional_Subproblems_Interfaces_Fields::updated_interfacial_heat_flux_sol_ = false protected
Referenced by reset_flags(), and retrieve_interfacial_surface_quantities().
updated_velocity_magnitude_
bool IJK_One_Dimensional_Subproblems_Interfaces_Fields::updated_velocity_magnitude_ = false protected
Referenced by reset_flags(), and retrieve_interfacial_surface_quantities().
updated_temperature_
bool IJK_One_Dimensional_Subproblems_Interfaces_Fields::updated_temperature_ = false protected
Referenced by reset_flags(), and retrieve_interfacial_surface_quantities().
updated_temperature_sol_
bool IJK_One_Dimensional_Subproblems_Interfaces_Fields::updated_temperature_sol_ = false protected
Referenced by reset_flags(), and retrieve_interfacial_surface_quantities().
updated_temperature_gradient_
bool IJK_One_Dimensional_Subproblems_Interfaces_Fields::updated_temperature_gradient_ = false protected
Referenced by reset_flags(), and retrieve_interfacial_surface_quantities().
updated_temperature_gradient_sol_
bool IJK_One_Dimensional_Subproblems_Interfaces_Fields::updated_temperature_gradient_sol_ = false protected
Referenced by reset_flags(), and retrieve_interfacial_surface_quantities().