TrioCFD: Paroi_hyd_base_VDF Class Reference
Paroi_hyd_base_VDF Class Reference
#include <Paroi_hyd_base_VDF.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Turbulence_paroi_base
void associer_modele (const Modele_turbulence_hyd_base &)
int calculer_hyd (Champ_Fonc_base &, Champ_Fonc_base &)
int calculer_hyd (Champ_Inc_base &)
const Type_info * get_info () const override
virtual void imprimer_premiere_ligne_ustar (int, const TRUST_List< Nom > &, const Nom &) const
virtual void imprimer_ustar_mean_only (Sortie &, int, const TRUST_List< Nom > &, const Nom &) const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Turbulence_paroi_base
static void typer_lire_turbulence_paroi (TRUST_Deriv< Turbulence_paroi_base > &, const Modele_turbulence_hyd_base &, Entree &)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Paroi_hyd_base_VDF()
Paroi_hyd_base_VDF::Paroi_hyd_base_VDF ()
~Paroi_hyd_base_VDF()
Paroi_hyd_base_VDF::~Paroi_hyd_base_VDF () override
Member Function Documentation
info()
const Type_info * Paroi_hyd_base_VDF::info () static
get_info()
const Type_info * Paroi_hyd_base_VDF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Turbulence_paroi_base.
Reimplemented in Paroi_std_hyd_VDF_diphasique, LoiParoiHybride_VDF, Paroi_2couches_VDF, Paroi_loi_Ciofalo_hyd_VDF, Paroi_loi_WW_hyd_VDF, Paroi_std_hyd_VDF, Loi_expert_hydr_VDF, Paroi_TAU_NUL_VDF, Paroi_UTAU_IMP_VDF, ParoiVDF_TBLE, ParoiVDF_TBLE_LRM, and Paroi_negligeable_VDF.
self_cast() [1/2]
Paroi_hyd_base_VDF & Paroi_hyd_base_VDF::self_cast (Objet_U & r) static
self_cast() [2/2]
const Paroi_hyd_base_VDF & Paroi_hyd_base_VDF::self_cast (const Objet_U & r) static
printOn()
Sortie & Paroi_hyd_base_VDF::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Turbulence_paroi_base.
Reimplemented in Paroi_std_hyd_VDF_diphasique, LoiParoiHybride_VDF, Paroi_2couches_VDF, Paroi_loi_Ciofalo_hyd_VDF, Paroi_loi_WW_hyd_VDF, Paroi_std_hyd_VDF, Loi_expert_hydr_VDF, Paroi_TAU_NUL_VDF, Paroi_UTAU_IMP_VDF, ParoiVDF_TBLE, ParoiVDF_TBLE_LRM, and Paroi_negligeable_VDF.
References Objet_U::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Paroi_hyd_base_VDF::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Turbulence_paroi_base.
Reimplemented in Paroi_std_hyd_VDF_diphasique, LoiParoiHybride_VDF, Paroi_2couches_VDF, Paroi_loi_Ciofalo_hyd_VDF, Paroi_loi_WW_hyd_VDF, Paroi_std_hyd_VDF, Loi_expert_hydr_VDF, Paroi_TAU_NUL_VDF, Paroi_UTAU_IMP_VDF, ParoiVDF_TBLE, ParoiVDF_TBLE_LRM, and Paroi_negligeable_VDF.
References Turbulence_paroi_base::readOn().
Referenced by Paroi_2couches_VDF::readOn(), and Paroi_std_hyd_VDF::readOn().
associer()
void Paroi_hyd_base_VDF::associer (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis) override virtual
Implements Turbulence_paroi_base.
Reimplemented in LoiParoiHybride_VDF.
References Turbulence_paroi_base::le_dom_Cl_dis_, and Turbulence_paroi_base::le_dom_dis_.
Referenced by LoiParoiHybride_VDF::associer().
init_lois_paroi_()
void Paroi_hyd_base_VDF::init_lois_paroi_ ()
References Turbulence_paroi_base::Cisaillement_paroi_, Objet_U::dimension, TRUSTVect< _TYPE_, _SIZE_ >::get_md_vector(), Turbulence_paroi_base::le_dom_dis_, MD_Vector::non_nul(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), Turbulence_paroi_base::tab_d_plus_, and Turbulence_paroi_base::tab_u_star_.
Referenced by Paroi_2couches_VDF::init_lois_paroi(), Paroi_std_hyd_VDF::init_lois_paroi(), Paroi_UTAU_IMP_VDF::init_lois_paroi(), ParoiVDF_TBLE::init_lois_paroi(), Paroi_negligeable_VDF::init_lois_paroi(), and Paroi_std_hyd_VDF::initialize_wall_law_komega().
Member Data Documentation
info_obj
const Type_info Paroi_hyd_base_VDF::info_obj static