TrioCFD: Dispersion_bulles_turbulente_constante Class Reference
Dispersion_bulles_turbulente_constante Class Reference
#include <Dispersion_bulles_turbulente_constante.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
based on the model from Lance and Lopez de Bertodano (1994)
Constructor & Destructor Documentation
Dispersion_bulles_turbulente_constante()
Dispersion_bulles_turbulente_constante::Dispersion_bulles_turbulente_constante ()
~Dispersion_bulles_turbulente_constante()
Dispersion_bulles_turbulente_constante::~Dispersion_bulles_turbulente_constante ()
Member Function Documentation
cree_instance()
Objet_U * Dispersion_bulles_turbulente_constante::cree_instance () static
taille_memoire()
unsigned Dispersion_bulles_turbulente_constante::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Dispersion_bulles_turbulente_constante::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Dispersion_bulles_turbulente_constante::info () static
get_info()
const Type_info * Dispersion_bulles_turbulente_constante::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Dispersion_bulles_base.
self_cast() [1/2]
Dispersion_bulles_turbulente_constante & Dispersion_bulles_turbulente_constante::self_cast (Objet_U & r) static
self_cast() [2/2]
const Dispersion_bulles_turbulente_constante & Dispersion_bulles_turbulente_constante::self_cast (const Objet_U & r) static
printOn()
Sortie & Dispersion_bulles_turbulente_constante::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Dispersion_bulles_base.
readOn()
Entree & Dispersion_bulles_turbulente_constante::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Dispersion_bulles_base.
References Param::ajouter(), C_td_, Nom::debute_par(), Process::exit(), Param::lire_avec_accolades_depuis(), n_l, Pb_Multiphase::nb_phases(), Pb_Multiphase::nom_phase(), Correlation_base::pb_, Objet_U::que_suis_je(), and TRUST_Ref< _CLASSE_ >::valeur().
coefficient()
void Dispersion_bulles_turbulente_constante::coefficient (const input_t & input, output_t & output) const override virtual
Implements Dispersion_bulles_base.
References C_td_, Dispersion_bulles_base::output_t::Ctd, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Dispersion_bulles_base::input_t::k_turb, n_l, and Dispersion_bulles_base::input_t::rho.
Member Data Documentation
info_obj
const Type_info Dispersion_bulles_turbulente_constante::info_obj static
n_l
int Dispersion_bulles_turbulente_constante::n_l = -1 protected
Referenced by coefficient(), and readOn().
C_td_
double Dispersion_bulles_turbulente_constante::C_td_ = .1 protected
Referenced by coefficient(), and readOn().