TrioCFD: Joints_32_64< _SIZE_ > Class Template Reference
Joints_32_64< _SIZE_ > Class Template Reference
#include <Joints.h>
Public Member Functions
void associer_domaine (const Domaine_t &)
const Type_info * get_info () const override
Joint_t & joint_PE (int pe)
int_t nb_faces () const
int_t nb_faces (Type_Face type) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from TRUST_List< Joint_32_64< _SIZE_ > >
Sortie & printOn (Sortie &os) const override
Entree & readOn (Entree &is) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
template<typename _SIZE_>
class Joints_32_64< _SIZE_ >
See also
Joint
Member Typedef Documentation
int_t
template<typename _SIZE_ > using Joints_32_64< _SIZE_ >::int_t = _SIZE_
Domaine_t
template<typename _SIZE_ > using Joints_32_64< _SIZE_ >::Domaine_t = Domaine_32_64<_SIZE_>
Joint_t
template<typename _SIZE_ > using Joints_32_64< _SIZE_ >::Joint_t = Joint_32_64<_SIZE_>
Constructor & Destructor Documentation
Joints_32_64()
template<typename _T_ > Joints_32_64< _T_ >::Joints_32_64
~Joints_32_64()
template<typename _T_ > Joints_32_64< _T_ >::~Joints_32_64
Member Function Documentation
cree_instance()
template<typename _T_ > Objet_U * Joints_32_64< _T_ >::cree_instance static
taille_memoire()
template<typename _T_ > unsigned Joints_32_64< _T_ >::taille_memoire override virtual
Implements Objet_U.
duplique()
template<typename _T_ > int Joints_32_64< _T_ >::duplique override virtual
Implements Objet_U.
info()
template<typename _T_ > const Type_info * Joints_32_64< _T_ >::info static
get_info()
template<typename _T_ > const Type_info * Joints_32_64< _T_ >::get_info override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
template<typename _T_ > Joints_32_64< _T_ > & Joints_32_64< _T_ >::self_cast (Objet_U & r) static
self_cast() [2/2]
template<typename _T_ > const Joints_32_64< _T_ > & Joints_32_64< _T_ >::self_cast (const Objet_U & r) static
printOn()
template<typename _SIZE_ > Sortie & Joints_32_64< _SIZE_ >::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
readOn()
template<typename _SIZE_ > Entree & Joints_32_64< _SIZE_ >::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
associer_domaine()
template<typename _SIZE_ > void Joints_32_64< _SIZE_ >::associer_domaine (const Domaine_t & un_domaine)
Associe un domaine a tous les joints de la liste.
Les joints de la liste feront partie de cet domaine.
Parameters
(Domaine& un_domaine) le domaine a associer aux joints
Referenced by Interprete_geometrique_base_32_64< _SIZE_ >::interpreter(), and Domaine_32_64< _SIZE_ >::merge_wo_vertices_with().
nb_faces() [1/2]
template<typename _SIZE_ > _SIZE_ Joints_32_64< _SIZE_ >::nb_faces
Renvoie le nombre de face total des Joints_32_64 de la liste.
(la somme des faces de tous les joints de la liste).
Returns
(int) le nombre de face total des Joints_32_64 de la liste
Referenced by Domaine_32_64< _SIZE_ >::nb_faces_joint().
nb_faces() [2/2]
template<typename _SIZE_ > _SIZE_ Joints_32_64< _SIZE_ >::nb_faces (Type_Face type) const
Renvoie le nombre de faces du type specifie contenues dans la liste de joints.
(somme des faces de ce type sur tous les joints de la liste)
Parameters
(Type_Face type) le type des faces a compter
Returns
(int) le nombre de faces du type specifie contenues dans la liste de joints
nb_joints()
template<typename _SIZE_ > int Joints_32_64< _SIZE_ >::nb_joints () const inline
References TRUST_List< Joint_32_64< _SIZE_ > >::size().
Referenced by Domaine_32_64< _SIZE_ >::nb_joints().
comprimer()
template<typename _SIZE_ > void Joints_32_64< _SIZE_ >::comprimer
Comprime la liste de joints.
References Joint_32_64< _SIZE_ >::ajouter_faces(), Joint_32_64< _SIZE_ >::dimensionner(), Process::exit(), Frontiere_32_64< _SIZE_ >::le_nom(), Frontiere_32_64< _SIZE_ >::les_sommets_des_faces(), Frontiere_32_64< _SIZE_ >::nb_faces(), Frontiere_32_64< _SIZE_ >::nommer(), and Joint_32_64< _SIZE_ >::PEvoisin().
joint_PE()
template<typename _SIZE_ > Joints_32_64< _SIZE_ >::Joint_t & Joints_32_64< _SIZE_ >::joint_PE (int pe)
Renvoie une reference sur le joint qui a pour voisin le PE specifie.
Parameters
(int pe) un numero de PE
Returns
(Joint&) le joint qui a pour voisin le PE specifie
Exceptions
PE voisin specifie non trouve dans la liste des joints.
References Process::exit(), and Joint_32_64< _SIZE_ >::PEvoisin().
info_obj()
const Type_info Joints_32_64< trustIdType >::info_obj ("Joints" "_64" , Joints_32_64< trustIdType >::cree_instance , 1 , Joints_32_64bases< trustIdType >)
Member Data Documentation
info_obj
template<typename _SIZE_ > const Type_info Joints_32_64< _SIZE_ >::info_obj static