TrioCFD: Convection_Diffusion_Temperature_base Class Reference
Convection_Diffusion_Temperature_base Class Reference
#include <Convection_Diffusion_Temperature_base.h>
Public Member Functions
void associer_milieu_base (const Milieu_base &) override
Fluide_base & fluide ()
const Type_info * get_info () const override
Public Member Functions inherited from Convection_Diffusion_std
void associer_vitesse (const Champ_base &)
const Type_info * get_info () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
int nombre_d_operateurs () const override
const Operateur & operateur (int) const override
Operateur & operateur (int) override
const Champ_Inc_base & vitesse_transportante () const
Public Member Functions inherited from Equation_base
virtual void abortTimeStep ()
virtual void associer_domaine_dis (const Domaine_dis_base &)
virtual void associer_pb_base (const Probleme_base &)
virtual void associer_sch_tps_base (const Schema_Temps_base &)
virtual double calculer_pas_de_temps () const
virtual void completer ()
virtual std::vector< YAML_data > data_a_sauvegarder () const
DoubleTab & derivee_en_temps_conv (DoubleTab &, const DoubleTab &)
virtual DoubleTab & derivee_en_temps_inco (DoubleTab &)
const Discretisation_base & discretisation () const
virtual void discretiser ()
virtual const Motcle & domaine_application () const
virtual Domaine_Cl_dis_base & domaine_Cl_dis ()
virtual const Domaine_Cl_dis_base & domaine_Cl_dis () const
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual void imprimer (Sortie &os) const
virtual bool initTimeStep (double dt)
const Nom & le_nom () const override
int limpr () const
virtual void mettre_a_jour (double temps)
virtual int preparer_calcul ()
Probleme_base & probleme ()
const Probleme_base & probleme () const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Schema_Temps_base & schema_temps ()
const Schema_Temps_base & schema_temps () const
Solveur_Masse_base & solv_masse ()
const Solveur_Masse_base & solv_masse () const
Sources & sources ()
const Sources & sources () const
virtual void valider_iteration ()
virtual void verifie_ch_init_nb_comp (const Champ_Inc_base &ch_ref, const int nb_comp) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Equation_base
virtual Entree & lire_cl (Entree &)
virtual Entree & lire_cond_init (Entree &)
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual Entree & lire_sources (Entree &)
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
virtual int verif_Cl () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Convection_Diffusion_Temperature_base()
Convection_Diffusion_Temperature_base::Convection_Diffusion_Temperature_base ()
~Convection_Diffusion_Temperature_base()
Convection_Diffusion_Temperature_base::~Convection_Diffusion_Temperature_base () override
Member Function Documentation
info()
const Type_info * Convection_Diffusion_Temperature_base::info () static
get_info()
const Type_info * Convection_Diffusion_Temperature_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Convection_Diffusion_std.
Reimplemented in Convection_Diffusion_Temperature_FT_Disc, Convection_Diffusion_Temperature_sensibility, Energie_Multiphase, Energie_Multiphase_Enthalpie, and Convection_Diffusion_Temperature_Turbulent.
self_cast() [1/2]
Convection_Diffusion_Temperature_base & Convection_Diffusion_Temperature_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Convection_Diffusion_Temperature_base & Convection_Diffusion_Temperature_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Convection_Diffusion_Temperature_base::printOn (Sortie & is) const override protected virtual
Simple appel a Equation_base::printOn(Sortie&)
Parameters
(Sortie& is) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Convection_Diffusion_std.
Reimplemented in Convection_Diffusion_Temperature_FT_Disc, Convection_Diffusion_Temperature_sensibility, Energie_Multiphase, Energie_Multiphase_Enthalpie, and Convection_Diffusion_Temperature_Turbulent.
References Convection_Diffusion_std::printOn().
Referenced by Convection_Diffusion_Temperature::printOn(), and Energie_Multiphase::printOn().
readOn()
Entree & Convection_Diffusion_Temperature_base::readOn (Entree & is) override protected virtual
cf Equation_base::readOn(Entree&)
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Exceptions
terme diffusif non specifie
terme convectif non specifie
Reimplemented from Convection_Diffusion_std.
Reimplemented in Convection_Diffusion_Temperature_FT_Disc, Convection_Diffusion_Temperature_sensibility, Energie_Multiphase, Energie_Multiphase_Enthalpie, and Convection_Diffusion_Temperature_Turbulent.
References Convection_Diffusion_std::readOn().
Referenced by Convection_Diffusion_Temperature::readOn(), and Energie_Multiphase::readOn().
associer_fluide()
void Convection_Diffusion_Temperature_base::associer_fluide (const Fluide_base & un_fluide) inline
References le_fluide.
Referenced by Convection_Diffusion_Temperature::associer_milieu_base(), and associer_milieu_base().
milieu() [1/2]
const Milieu_base & Convection_Diffusion_Temperature_base::milieu () const inline override virtual
Implements Equation_base.
Reimplemented in Convection_Diffusion_Temperature_FT_Disc.
References fluide().
Referenced by diffusivite_pour_pas_de_temps(), Energie_Multiphase_Enthalpie::diffusivite_pour_pas_de_temps(), diffusivite_pour_transport(), Energie_Multiphase_Enthalpie::diffusivite_pour_transport(), Convection_Diffusion_Temperature::ecrire_fichier_pena_th(), and Convection_Diffusion_Temperature::get_time_factor().
milieu() [2/2]
Milieu_base & Convection_Diffusion_Temperature_base::milieu () inline override virtual
Implements Equation_base.
Reimplemented in Convection_Diffusion_Temperature_FT_Disc.
References fluide().
fluide() [1/2]
const Fluide_base & Convection_Diffusion_Temperature_base::fluide () const
References TRUST_Ref< _CLASSE_ >::est_nul(), Process::exit(), le_fluide, Probleme_U::le_nom(), Equation_base::probleme(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Operateur_Conv_sensibility_VEF::ajouter(), Terme_Source_inc_th_VDF_Face::associer_pb(), and milieu().
fluide() [2/2]
Fluide_base & Convection_Diffusion_Temperature_base::fluide ()
Renvoie le fluide associe a l'equation.
Returns
(Fluide_base&) le fluide associe a l'equation
Exceptions
pas de fluide associe a l'eqaution
References TRUST_Ref< _CLASSE_ >::est_nul(), Process::exit(), le_fluide, Probleme_U::le_nom(), Equation_base::probleme(), and TRUST_Ref< _CLASSE_ >::valeur().
associer_milieu_base()
void Convection_Diffusion_Temperature_base::associer_milieu_base (const Milieu_base & un_milieu) override virtual
Associe un milieu physique a l'equation, le milieu est en fait caste en Fluide_base.
Parameters
(Milieu_base& un_milieu)
Exceptions
le milieu n'est pas un Fluide_base
Implements Equation_base.
Reimplemented in Convection_Diffusion_Temperature_FT_Disc.
References associer_fluide(), Process::exit(), and Objet_U::que_suis_je().
Referenced by Pb_Multiphase_Enthalpie::associer_milieu_base().
diffusivite_pour_transport()
const Champ_Don_base & Convection_Diffusion_Temperature_base::diffusivite_pour_transport () const inline override virtual
Reimplemented from Convection_Diffusion_std.
Reimplemented in Energie_Multiphase_Enthalpie.
References Milieu_base::conductivite(), and milieu().
Referenced by Convection_Diffusion_Temperature_IBM_Turbulent::lire_motcle_non_standard(), and Convection_Diffusion_Temperature_Turbulent::lire_motcle_non_standard().
diffusivite_pour_pas_de_temps()
const Champ_base & Convection_Diffusion_Temperature_base::diffusivite_pour_pas_de_temps () const inline override virtual
Reimplemented from Convection_Diffusion_std.
Reimplemented in Energie_Multiphase_Enthalpie.
References Milieu_base::diffusivite(), and milieu().
Referenced by Convection_Diffusion_Temperature_IBM_Turbulent::lire_motcle_non_standard(), and Convection_Diffusion_Temperature_Turbulent::lire_motcle_non_standard().
t_paroi_thyd() [1/2]
const Champ_Fonc_base & Convection_Diffusion_Temperature_base::t_paroi_thyd () const inline
References temperature_paroi_, and TRUST_Deriv< _CLASSE_ >::valeur().
t_paroi_thyd() [2/2]
Champ_Fonc_base & Convection_Diffusion_Temperature_base::t_paroi_thyd () inline
References temperature_paroi_, and TRUST_Deriv< _CLASSE_ >::valeur().
creer_champ()
void Convection_Diffusion_Temperature_base::creer_champ (const Motcle & motlu) override virtual
Reimplemented from Equation_base.
Reimplemented in Convection_Diffusion_Temperature_Turbulent.
References Champs_compris_T< FIELD_TYPE >::ajoute_champ(), Equation_base::champs_compris_, Equation_base::creer_champ(), Equation_base::discretisation(), Equation_base::domaine_Cl_dis(), Equation_base::domaine_dis(), Objet_U_ptr::est_nul(), Convection_Diffusion_std::inconnue(), Discret_Thermique::t_paroi(), and temperature_paroi_.
Referenced by Convection_Diffusion_Temperature::creer_champ().
get_champ()
const Champ_base & Convection_Diffusion_Temperature_base::get_champ (const Motcle & nom) const override virtual
Reimplemented from Equation_base.
Reimplemented in Convection_Diffusion_Temperature_Turbulent.
References Equation_base::champs_compris_, Champs_compris_T< FIELD_TYPE >::get_champ(), Nom::getString(), Equation_base::has_champ(), Convection_Diffusion_std::inconnue(), Champ_Fonc_base::mettre_a_jour(), Equation_base::schema_temps(), temperature_paroi_, Champ_base::temps(), Schema_Temps_base::temps_init(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by Convection_Diffusion_Temperature::get_champ(), and has_champ().
has_champ() [1/2]
bool Convection_Diffusion_Temperature_base::has_champ (const Motcle & nom, TRUST_Ref< Champ_base * > & ref_champ) const override virtual
Reimplemented from Equation_base.
Reimplemented in Convection_Diffusion_Temperature_Turbulent.
References get_champ(), and Equation_base::has_champ().
Referenced by Convection_Diffusion_Temperature::has_champ().
has_champ() [2/2]
bool Convection_Diffusion_Temperature_base::has_champ (const Motcle & nom) const override virtual
Reimplemented from Equation_base.
Reimplemented in Convection_Diffusion_Temperature_Turbulent.
References Equation_base::has_champ().
get_noms_champs_postraitables()
void Convection_Diffusion_Temperature_base::get_noms_champs_postraitables (Noms & nom, Option opt = NONE) const override virtual
Reimplemented from Equation_base.
Reimplemented in Convection_Diffusion_Temperature_Turbulent.
References TRUST_Vector< _CLASSE_ >::add(), Equation_base::champs_compris_, Equation_base::get_noms_champs_postraitables(), Champs_compris_T< FIELD_TYPE >::liste_noms_compris(), and Objet_U::que_suis_je().
Referenced by Convection_Diffusion_Temperature::get_noms_champs_postraitables().
Member Data Documentation
info_obj
const Type_info Convection_Diffusion_Temperature_base::info_obj static
le_fluide
TRUST_Ref< Fluide_base *> Convection_Diffusion_Temperature_base::le_fluide protected
Referenced by associer_fluide(), Convection_Diffusion_Temperature::discretiser(), fluide(), Convection_Diffusion_Temperature::readOn(), and Energie_Multiphase::readOn().
temperature_paroi_
TRUST_Deriv< Champ_Fonc_base > Convection_Diffusion_Temperature_base::temperature_paroi_ protected
Referenced by creer_champ(), get_champ(), and t_paroi_thyd().