TrioCFD: Eq_rayo_semi_transp_VDF Class Reference
Eq_rayo_semi_transp_VDF Class Reference
#include <Eq_rayo_semi_transp_VDF.h>
Public Member Functions
void completer () override
const Type_info * get_info () const override
void modifier_matrice () override
void resoudre (double temps) override
Public Member Functions inherited from Equation_rayonnement_base
void associer_fluide (const Fluide_base &)
void associer_milieu_base (const Milieu_base &) override
void associer_modele_rayonnement (const Modele_rayo_semi_transp &)
void associer_pb_base (const Probleme_base &pb) override
void completer () override
const Discretisation_base & discretisation () const
Fluide_base & fluide ()
const Fluide_base & fluide () const
const Type_info * get_info () const override
int impr (Sortie &os) const override
const Champ_Inc_base & inconnue () const override
Champ_Inc_base & inconnue () override
bool initTimeStep (double dt) override
int lire_motcle_non_standard (const Motcle &, Entree &) override
const Milieu_base & milieu () const override
Milieu_base & milieu () override
Modele_rayo_semi_transp & Modele ()
const Modele_rayo_semi_transp & Modele () const
int nombre_d_operateurs () const override
const Operateur & operateur (int) const override
Operateur & operateur (int) override
Public Member Functions inherited from Equation_base
virtual void abortTimeStep ()
virtual void associer_domaine_dis (const Domaine_dis_base &)
virtual void associer_pb_base (const Probleme_base &)
virtual void associer_sch_tps_base (const Schema_Temps_base &)
virtual double calculer_pas_de_temps () const
virtual void completer ()
virtual std::vector< YAML_data > data_a_sauvegarder () const
DoubleTab & derivee_en_temps_conv (DoubleTab &, const DoubleTab &)
virtual DoubleTab & derivee_en_temps_inco (DoubleTab &)
const Discretisation_base & discretisation () const
virtual void discretiser ()
virtual const Motcle & domaine_application () const
virtual Domaine_Cl_dis_base & domaine_Cl_dis ()
virtual const Domaine_Cl_dis_base & domaine_Cl_dis () const
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual void imprimer (Sortie &os) const
virtual bool initTimeStep (double dt)
const Nom & le_nom () const override
int limpr () const
virtual void mettre_a_jour (double temps)
virtual int preparer_calcul ()
Probleme_base & probleme ()
const Probleme_base & probleme () const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Schema_Temps_base & schema_temps ()
const Schema_Temps_base & schema_temps () const
Solveur_Masse_base & solv_masse ()
const Solveur_Masse_base & solv_masse () const
Sources & sources ()
const Sources & sources () const
virtual void valider_iteration ()
virtual void verifie_ch_init_nb_comp (const Champ_Inc_base &ch_ref, const int nb_comp) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Equation_base
virtual Entree & lire_cl (Entree &)
virtual Entree & lire_cond_init (Entree &)
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual Entree & lire_sources (Entree &)
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
virtual int verif_Cl () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
dans un milieu semi transparent. elle est associee au modele de rayonnement semi transparent Elle definit la methode resoudre et calcule l'irradiance.
See also
Equation_rayonnement
Constructor & Destructor Documentation
Eq_rayo_semi_transp_VDF()
Eq_rayo_semi_transp_VDF::Eq_rayo_semi_transp_VDF ()
~Eq_rayo_semi_transp_VDF()
Eq_rayo_semi_transp_VDF::~Eq_rayo_semi_transp_VDF ()
Member Function Documentation
cree_instance()
Objet_U * Eq_rayo_semi_transp_VDF::cree_instance () static
taille_memoire()
unsigned Eq_rayo_semi_transp_VDF::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Eq_rayo_semi_transp_VDF::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Eq_rayo_semi_transp_VDF::info () static
get_info()
const Type_info * Eq_rayo_semi_transp_VDF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Equation_rayonnement_base.
self_cast() [1/2]
Eq_rayo_semi_transp_VDF & Eq_rayo_semi_transp_VDF::self_cast (Objet_U & r) static
self_cast() [2/2]
const Eq_rayo_semi_transp_VDF & Eq_rayo_semi_transp_VDF::self_cast (const Objet_U & r) static
printOn()
Sortie & Eq_rayo_semi_transp_VDF::printOn (Sortie & s) const override protected virtual
Imprime le type de l'equation sur un flot de sortie.
Parameters
(Sortie& s) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Equation_rayonnement_base.
References Objet_U::que_suis_je().
readOn()
Entree & Eq_rayo_semi_transp_VDF::readOn (Entree & s) override protected virtual
Parameters
(Entree& s) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Equation_rayonnement_base.
References Equation_rayonnement_base::readOn().
modifier_matrice()
void Eq_rayo_semi_transp_VDF::modifier_matrice () override virtual
modifie la matrice pour prendre en compte la presence de faces rayonnantes au voisinage des elements de bord
Returns
le flot d'entree modifie
Implements Equation_rayonnement_base.
References Flux_radiatif_base::A(), Domaine_VDF::dist_norm_bord(), Equation_base::domaine_Cl_dis(), Equation_base::domaine_dis(), Flux_radiatif_base::emissivite(), Process::exit(), Domaine_VF::face_surfaces(), Domaine_VF::face_voisins(), Equation_rayonnement_base::fluide(), Fluide_base::kappa(), Equation_rayonnement_base::la_matrice, Domaine_Cl_dis_base::les_conditions_limites(), Fluide_base::longueur_rayo(), Field_base::nb_comp(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), TRUST_Vector< _CLASSE_ >::size(), TRUST_Deriv< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), and Champ_front_base::valeurs().
Referenced by assembler_matrice().
resoudre()
void Eq_rayo_semi_transp_VDF::resoudre (double temps) override virtual
Calcule le champ de l'irradiance en fonction des CLs au temps donne en parametre et de la temperature au temps par defaut.
Met le resultat dans inconnue.valeurs() Suppose que le schema en temps est Euler explicite...
Implements Equation_rayonnement_base.
References Equation_base::domaine_dis(), Probleme_base::equation(), Equation_rayonnement_base::fluide(), Equation_base::inconnue(), Equation_rayonnement_base::inconnue(), Fluide_base::indice(), Fluide_base::kappa(), Field_base::le_nom(), Equation_rayonnement_base::Modele(), Domaine_dis_base::nb_elem(), Modele_rayo_semi_transp::probleme(), Modele_rayo_semi_transp::valeur_sigma(), Champ_Don_base::valeurs(), Champ_Inc_base::valeurs(), and Domaine_VF::volumes().
evaluer_cl_rayonnement()
void Eq_rayo_semi_transp_VDF::evaluer_cl_rayonnement (double temps) override virtual
Implements Equation_rayonnement_base.
References Frontiere_ouverte_rayo_semi_transp::calculer_temperature_bord(), Frontiere_ouverte_temperature_imposee_rayo_semi_transp::calculer_temperature_bord(), Echange_contact_rayo_semi_transp_VDF::calculer_temperature_bord(), Echange_externe_impose_rayo_semi_transp::calculer_temperature_bord(), Echange_global_impose_rayo_semi_transp::calculer_temperature_bord(), Neumann_paroi_rayo_semi_transp_VDF::calculer_temperature_bord(), Equation_base::domaine_Cl_dis(), Equation_base::domaine_dis(), Probleme_base::equation(), Flux_radiatif_VDF::evaluer_cl_rayonnement(), Process::exit(), Equation_rayonnement_base::fluide(), Equation_base::inconnue(), Field_base::le_nom(), Objet_U_ptr::le_nom(), Domaine_Cl_dis_base::les_conditions_limites(), Equation_rayonnement_base::Modele(), Modele_rayo_semi_transp::probleme(), Objet_U::que_suis_je(), TRUST_Vector< _CLASSE_ >::size(), Frontiere_ouverte_rayo_semi_transp::temperature_bord(), Frontiere_ouverte_temperature_imposee_rayo_semi_transp::temperature_bord(), Echange_contact_rayo_semi_transp_VDF::temperature_bord(), Echange_externe_impose_rayo_semi_transp::temperature_bord(), Echange_global_impose_rayo_semi_transp::temperature_bord(), Neumann_paroi_rayo_semi_transp_VDF::temperature_bord(), and TRUST_Deriv< _CLASSE_ >::valeur().
completer()
void Eq_rayo_semi_transp_VDF::completer () override virtual
Complete la construction (initialisation) des objets associes a l'equation.
Complete les sources, associe l'equation a l'inconnue complete les operateurs, complete les conditions aux limites discretisees. Voir les methodes Source_base::completer(), Operateur_base::completer() Domaine_Cl_dis_base::completer() Domaine_Cl_dis_base::completer(const Domaine_dis_base&)
Reimplemented from Equation_rayonnement_base.
References assembler_matrice(), Equation_rayonnement_base::completer(), Equation_base::domaine_dis(), Domaine_dis_base::frontiere_dis(), Equation_base::le_dom_Cl_dis, Domaine_Cl_dis_base::les_conditions_limites(), and Domaine_dis_base::nb_front_Cl().
typer_op_grad()
void Eq_rayo_semi_transp_VDF::typer_op_grad () override virtual
Implements Equation_rayonnement_base.
assembler_matrice()
void Eq_rayo_semi_transp_VDF::assembler_matrice () override virtual
Implements Equation_rayonnement_base.
References Matrice_Morse::clean(), Equation_base::domaine_dis(), Process::exit(), Equation_rayonnement_base::fluide(), Equation_rayonnement_base::irradiance_, Fluide_base::kappa(), Equation_rayonnement_base::la_matrice, modifier_matrice(), Domaine_dis_base::nb_elem_tot(), Matrice_Morse::ordre(), Equation_rayonnement_base::terme_diffusif, Champ_Don_base::valeurs(), Champ_Inc_base::valeurs(), and Domaine_VF::volumes().
Referenced by completer().
nb_colonnes_tot()
int Eq_rayo_semi_transp_VDF::nb_colonnes_tot () override virtual
Implements Equation_rayonnement_base.
References Domaine_dis_base::domaine(), Equation_base::domaine_dis(), and Domaine_32_64< _SIZE_ >::nb_elem_tot().
nb_colonnes()
int Eq_rayo_semi_transp_VDF::nb_colonnes () override virtual
Implements Equation_rayonnement_base.
References Domaine_dis_base::domaine(), Equation_base::domaine_dis(), and Domaine_32_64< _SIZE_ >::nb_elem().
Member Data Documentation
info_obj
const Type_info Eq_rayo_semi_transp_VDF::info_obj static