TrioCFD: Domaine_dis_base Class Reference
Domaine_dis_base Class Reference abstract
#include <Domaine_dis_base.h>
Public Member Functions
void associer_domaine (const Domaine &)
const Domaine & domaine () const
void ecrire_noms_bords (Sortie &) const
virtual IntTab & face_sommets ()
const Frontiere_dis_base & frontiere_dis (const Nom &) const
const Type_info * get_info () const override
int nombre_de_sous_domaines_dis () const
int rang_frontiere (const Nom &) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
Un objet Domaine est associe au domaine discretise.
A chaque discretisation spatiale (VDF, VEF, PolyMAC_P0P1NC, ...)  de TRUST correspond une classe derivant
de Domaine_dis_base implementant les outils necessaires a la methode.
Constructor & Destructor Documentation
Domaine_dis_base()
Domaine_dis_base::Domaine_dis_base ()
~Domaine_dis_base()
Domaine_dis_base::~Domaine_dis_base () override
Member Function Documentation
info()
const Type_info * Domaine_dis_base::info () static
get_info()
const Type_info * Domaine_dis_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
Reimplemented in Domaine_Poly_base, Domaine_VF, Domaine_VF_inst, Domaine_PolyMAC, Domaine_PolyMAC_P0, Domaine_PolyMAC_P0P1NC, Domaine_VDF, and Domaine_VEF.
self_cast() [1/2]
Domaine_dis_base & Domaine_dis_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Domaine_dis_base & Domaine_dis_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Domaine_dis_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
Reimplemented in Domaine_Poly_base, Domaine_VF, Domaine_VF_inst, Domaine_PolyMAC, Domaine_PolyMAC_P0, Domaine_PolyMAC_P0P1NC, Domaine_VDF, and Domaine_VEF.
readOn()
Entree & Domaine_dis_base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
Reimplemented in Domaine_Poly_base, Domaine_VF, Domaine_VF_inst, Domaine_PolyMAC, Domaine_PolyMAC_P0, Domaine_PolyMAC_P0P1NC, Domaine_VDF, and Domaine_VEF.
domaine() [1/2]
const Domaine & Domaine_dis_base::domaine () const inline
Accessors and shortcuts
References le_dom.
Referenced by Navier_Stokes_phase_field::_aff_donnee_P1Bulle(), Operateur_Conv_sensibility_VEF::add_diffusion_scalar_term(), Operateur_Conv_sensibility_VEF::add_diffusion_term(), Champ_implementation_P0::affecter_(), Champ_P1_isoP1Bulle::affecter_(), Op_Diff_EF::ajouter(), Op_Dift_EF_Q1::ajouter(), Op_Div_EF::ajouter(), Op_Conv_Amont_old_VEF_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Centre_EF_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Conv_Vort_VEF_Face::ajouter(), Op_Diff_VEF_Face_Q1::ajouter(), Op_Diff_VEF_Face_Stab::ajouter(), Op_Diff_VEFP1NCP1B_Face::ajouter(), Op_Dift_VEF_Face_Q1::ajouter(), Op_Dift_VEF_P1NCP1B_Face::ajouter(), Op_Curl_VEFP1B::ajouter(), Op_Rot_VEFP1B::ajouter(), Op_Conv_RT_VEF_Face::ajouter(), Source_Reaction_Particules_VDF::ajouter(), Source_Reaction_Particules_VEF::ajouter(), Terme_Boussinesq_Sensibility_VEFPreP1B_Face::ajouter(), Source_Transport_Fluctuation_Temperature_VDF_Elem::ajouter(), Source_Qdm_EF::ajouter(), Source_Scalaire_EF::ajouter(), Terme_Boussinesq_VEFPreP1B_Face::ajouter(), Terme_Source_Qdm_VEF_Face::ajouter(), Source_PDF_EF::ajouter_(), Op_Diff_VEF_Face_Stab::ajouter_antidiffusion(), Op_Div_VEFP1B_Elem::ajouter_aretes(), Op_Grad_VEF_P1B_Face::ajouter_aretes(), Op_Grad_EF::ajouter_bord(), Op_Diff_EF::ajouter_bords(), Op_Dift_EF_Q1::ajouter_bords(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Face::ajouter_cas_vectoriel(), Op_Diff_EF::ajouter_contribution(), Op_Dift_EF_Q1::ajouter_contribution(), Op_Conv_Amont_old_VEF_Face::ajouter_contribution(), Op_Conv_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution(), Op_Diff_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Face_Q1::ajouter_contribution(), Op_Diff_VEF_Face_Stab::ajouter_contribution(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution(), Op_Conv_RT_VEF_Face::ajouter_contribution(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution_elem(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face_Stab::ajouter_contribution_multi_scalaire(), Op_Diff_EF::ajouter_contribution_new(), Op_Dift_EF_Q1::ajouter_contribution_new(), Op_Conv_EF::ajouter_contribution_sous_cond(), Operateur_Conv_sensibility_VEF::ajouter_conv_term(), Op_Diff_VEF_Face_Stab::ajouter_diffusion(), Op_Div_VEFP1B_Elem::ajouter_elem(), Op_Grad_VEF_P1B_Face::ajouter_elem(), Source_Transport_VDF_Elem_base::ajouter_keps(), Source_Transport_K_Omega_VDF_Elem_base::ajouter_komega(), Operateur_Conv_sensibility_VEF::ajouter_Lsensibility_state_Amont(), Operateur_Conv_sensibility_VEF::ajouter_Lstate_sensibility_Amont(), Op_Diff_EF::ajouter_new(), Op_Dift_EF_Q1::ajouter_new(), Op_Diff_VEF_Face_Stab::ajouter_operateur_centre(), Source_Masse_Fluide_Dilatable_VEF::ajouter_projection(), Op_Grad_VEF_P1B_Face::ajouter_som(), Op_Div_VEFP1B_Elem::ajouter_som(), Op_Conv_EF::ajouter_sous_cond(), Terme_Source_Constituant_Vortex_VEF_Face::ajouter_terme_div_u(), Op_Conv_ALE_VEF::ajouterALE(), Masse_PolyMAC_Face::appliquer_impl(), Assembleur_P_EF::assembler_mat(), Assembleur_P_VEFPreP1B::assembler_mat(), Op_Diff_RotRot::assembler_matrice(), Parcours_interface::associer_domaine_dis(), Maillage_FT_Disc::associer_domaine_dis_parcours(), Marching_Cubes::associer_domaine_vf(), Source_Dirac_VDF_Elem::associer_domaines(), Source_Dirac_VEF_Face::associer_domaines(), Domaine_VF::build_map_mc_Cmesh(), Domaine_VF::build_mc_dual_mesh(), Domaine_VF::build_mc_face_mesh(), Champ_Q1_EF::cal_rot_ordre1(), Champ_Q1NC::cal_rot_ordre1(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calc_elem_elem(), Modele_turbulence_scal_LES_dyn_VDF::calc_elem_elem(), Modele_Jones_Launder_VEF::Calcul_D(), Modele_Launder_Sharma_VEF::Calcul_D(), Modele_Jones_Launder_VEF::Calcul_D_BiK(), Modele_Launder_Sharma_VEF::Calcul_D_BiK(), Champ_Face_VDF::calcul_duidxj(), Modele_Jones_Launder_VDF::Calcul_E(), Modele_Jones_Launder_VEF::Calcul_E(), Modele_Launder_Sharma_VEF::Calcul_E(), Modele_Jones_Launder_Thermique_VDF::Calcul_E(), Traitement_particulier_NS_THI_VDF::calcul_Ec_D(), Transport_Interfaces_FT_Disc::calcul_effort_fluide_interface(), Champ_front_contact_VEF::calcul_grads_locaux(), Maillage_FT_Disc::calcul_indicatrice(), Terme_Source_Solide_SWIFT_VDF::calcul_moyenne(), Champ_Face_VDF::calcul_S_barre_sans_contrib_paroi(), Traitement_particulier_NS_THI_VDF::calcul_spectre(), Traitement_particulier_NS_THI_VEF_new::calcul_spectre(), Traitement_particulier_NS_THI_VDF::calcul_spectre_operateur(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calcul_tableaux_correspondance(), Modele_turbulence_scal_LES_dyn_VDF::calcul_tableaux_correspondance(), Modele_Lam_Bremhorst_VEF::calcul_tenseur_Re_elem(), Champ_Q1_EF::calcul_y_plus(), Champ_P1NC::calcul_y_plus(), Source_Con_Phase_field::calculer_alpha_gradC_carre(), Domaine_EF::calculer_Bij(), Domaine_EF::calculer_Bij_gen(), Domaine_EF_axi::calculer_Bij_gen(), Modele_turbulence_hyd_LES_DSGS_VDF::calculer_cell_cent_vel(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calculer_cell_cent_vel(), Op_Diff_VEF_Face_Stab::calculer_coefficients(), Topologie_Maillage_FT::calculer_composantes_connexes_pour_suppression(), Moyenne_volumique::calculer_convolution_champ_elem(), Transport_Interfaces_FT_Disc::calculer_distance_interface(), Transport_Interfaces_FT_Disc::calculer_distance_interface_sommets(), Op_Diff_P1NC_barprim::calculer_divergence(), Op_Dift_VEF_P1NCP1B_Face::calculer_divergence_elem(), Op_Diff_VEFP1NCP1B_Face::calculer_divergence_elem(), Op_Dift_VEF_P1NCP1B_Face::calculer_divergence_som(), Op_Diff_VEFP1NCP1B_Face::calculer_divergence_som(), Op_Conv_EF::calculer_dt_stab(), Op_Diff_EF_base::calculer_dt_stab(), Op_Dift_EF_Q1::calculer_dt_stab(), Op_Conv_PolyMAC_iterateur_base::calculer_dt_stab(), Op_Conv_VDF_base::calculer_dt_stab(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab(), Op_Dift_VEF_base::calculer_dt_stab(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab_elem(), Op_Dift_VEF_base::calculer_dt_stab_P1NCP1B(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calculer_energie_cinetique_turb(), Modele_turbulence_hyd_Longueur_Melange_VEF::calculer_f_amortissement(), Modele_turbulence_scal_LES_dyn_VDF::calculer_filter_coeff(), Modele_turbulence_hyd_LES_DSGS_VDF::calculer_filter_coeff(), Modele_turbulence_hyd_LES_DSGS_VDF::calculer_filter_field(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calculer_filter_field(), Modele_turbulence_hyd_LES_DSGS_VDF::calculer_filter_tensor(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calculer_filter_tensor(), Op_Diff_VEFP1NCP1B_Face::calculer_flux_bords_som(), Modele_turbulence_hyd_LES_VDF::calculer_fonction_structure(), Modele_turbulence_hyd_LES_1elt_VEF::calculer_fonction_structure(), Modele_turbulence_hyd_LES_axi_VDF::calculer_fonction_structure(), Terme_Source_Coriolis_VDF_Face::calculer_force_de_Coriolis(), EDO_Pression_th_VEF::calculer_grad(), Op_Dift_VEF_P1NCP1B_Face::calculer_gradient_elem(), Op_Diff_VEFP1NCP1B_Face::calculer_gradient_elem(), Navier_Stokes_FT_Disc::calculer_gradient_indicatrice(), Op_Dift_VEF_P1NCP1B_Face::calculer_gradient_som(), Op_Diff_VEFP1NCP1B_Face::calculer_gradient_som(), Op_Diff_VEF_Face_Stab::calculer_gradients(), Echange_contact_VDF::calculer_h_autre_pb(), Domaine_EF::calculer_h_carre(), Domaine_Poly_base::calculer_h_carre(), Domaine_VEF::calculer_h_carre(), Domaine_PolyMAC::calculer_h_carre(), Paroi_std_hyd_VEF::calculer_hyd(), Paroi_std_hyd_VEF_diphasique::calculer_hyd(), Paroi_loi_WW_hyd_EF::calculer_hyd(), Paroi_std_hyd_EF::calculer_hyd(), Paroi_negligeable_VEF::calculer_hyd(), ParoiVEF_TBLE::calculer_hyd(), Paroi_std_hyd_VEF::calculer_hyd_BiK(), ParoiVEF_TBLE::calculer_hyd_BiK(), IJK_Interfaces::calculer_indicatrices(), Domaine_EF::calculer_IPhi(), Domaine_EF_axi::calculer_IPhi(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calculer_length_scale(), Modele_turbulence_hyd_LES_DSGS_VDF::calculer_Lij(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calculer_Lij(), Modele_turbulence_scal_LES_dyn_VDF::calculer_Lj(), Modele_turbulence_hyd_LES_VDF_base::calculer_longueurs_caracteristiques(), Op_Diff_VEF_Face_Stab::calculer_max(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calculer_Mij(), Modele_turbulence_hyd_LES_DSGS_VDF::calculer_Mij(), Op_Diff_VEF_Face_Stab::calculer_min(), Modele_turbulence_scal_LES_dyn_VDF::calculer_Mj(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calculer_model_coefficient(), Traitement_particulier_NS_canal_VDF::calculer_moyenne_spatiale_nut(), Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_nut(), Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_uv(), Traitement_particulier_NS_canal_VDF::calculer_moyenne_spatiale_vitesse_rho_mu(), Traitement_particulier_NS_Profils_thermo_VDF::calculer_moyennes_spatiales_thermo(), Traitement_particulier_Solide_canal_VDF::calculer_moyennes_spatiales_thermo(), Modele_turbulence_hyd_LES_Wale_VDF::calculer_OP1_OP2(), Senseur_Interface::calculer_position(), Op_Conv_PolyMAC_iterateur_base::calculer_pour_post(), Op_Conv_VDF_base::calculer_pour_post(), Op_Dift_VEF_base::calculer_pour_post(), Navier_Stokes_std::calculer_pression_hydrostatique(), Source_Transport_Fluctuation_Temperature_VDF_Elem::calculer_Prod_uteta_T(), Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::calculer_Prod_uteta_T(), Source_Transport_Fluctuation_Temperature_W_VDF_Elem::calculer_Prod_uteta_T(), Modele_turbulence_hyd_LES_Smago_filtre_VEF::calculer_S_barre(), Loi_Paroi_Nu_Impose_VEF::calculer_scal(), ParoiVEF_TBLE_scal::calculer_scal(), Modele_turbulence_hyd_LES_DSGS_VDF::calculer_Sij(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calculer_Sij_vel_filt(), Echange_contact_rayo_semi_transp_VDF::calculer_temperature_bord(), Calcul_Production_K_VDF::calculer_terme_destruction_K(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_W_VDF_Elem::calculer_terme_destruction_K_W(), Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::calculer_terme_destruction_K_W(), Source_Transport_Fluctuation_Temperature_W_VDF_Elem::calculer_terme_destruction_K_W(), Calcul_Production_K_VDF::calculer_terme_production_K(), Calcul_Production_K_VDF::calculer_terme_production_K_BiK(), Paroi_flux_impose_Rayo_transp::calculer_Teta_i_VDF(), Echange_contact_Rayo_transp_VDF::calculer_Teta_paroi(), Source_Con_Phase_field::calculer_u2_elem(), IJK_Interfaces::calculer_var_volume_remaillage(), Source_PDF_EF::calculer_variable_imposee_elem_fluid(), Source_PDF_EF::calculer_variable_imposee_hybrid(), Source_PDF_EF::calculer_variable_imposee_mean_grad(), Modele_turbulence_hyd_LES_axi_VDF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_VDF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_VEF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_Smago_VDF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_Wale_VDF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_K_Eps::calculer_viscosite_turbulente(), Modele_turbulence_hyd_K_Eps_Bicephale::calculer_viscosite_turbulente(), Modele_turbulence_hyd_K_Omega::calculer_viscosite_turbulente(), Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl(), Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl_u_star(), Transport_Interfaces_FT_Disc::calculer_vitesse_transport_interpolee(), Transport_Interfaces_FT_Disc::calculer_vmoy_composantes_connexes(), Maillage_FT_Disc::calculer_voisinage_facettes(), Domaine_EF::calculer_volumes_entrelaces(), Domaine_VEF::calculer_volumes_entrelaces(), Domaine_EF::calculer_volumes_sommets(), Op_Diff_RotRot::calculer_vorticite(), Domaine_VF::calculer_xgr(), Discretisation_tools::cells_to_nodes(), Traitement_particulier_NS_THI_VDF::ch_vit_pour_fft(), Traitement_particulier_NS_THI_VDF::ch_vit_pour_fft_operateur(), Assembleur_P_VEFPreP1B::changer_base(), Convection_Diffusion_Temperature_FT_Disc::completer(), Terme_Source_Rappel_T_VEF_Face::completer(), Domaine_Cl_VDF::completer(), Champ_Generique_Reduction_0D::completer(), Champ_Generique_Transformation::completer(), Source_PDF_EF::compute_coeff_elem(), Source_PDF_EF::compute_coeff_matrice(), Post_Processing_Hydrodynamic_Forces::compute_friction_force_projected_tensor(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_friction_force_projected_tensor(), Post_Processing_Hydrodynamic_Forces::compute_heat_transfer(), Source_PDF_EF::compute_indicateur_nodal_champ_aire(), Domaine_DG::compute_mesh_param(), Post_Processing_Hydrodynamic_Forces::compute_neighbors_coordinates_fluid_fa7(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_neighbors_coordinates_fluid_fa7(), Interpolation_IBM_elem_fluid::computeFluidElems(), Interpolation_IBM_mean_gradient_proto::computeSommetsVoisins(), Champ_front_contact_VEF::connectivity_failed(), Scatter::construire_correspondance_aretes_par_coordonnees(), Domaine_VEF::construire_ok_arete(), Domaine_VEF::construire_renum_arete_perio(), Remailleur_Collision_FT_Thomas::construire_voisinage_sommet(), Source_PDF_EF::contribuer_a_avec(), Op_Dift_VEF_Face_Q1::contribuer_a_avec(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::controler_grandeurs_turbulentes(), Transport_K_Eps_base::controler_K_Eps(), Transport_K_Omega_base::controler_K_Omega(), Transport_K_ou_Eps_base::controler_variable(), IJK_Interfaces::convert_to_IntVect(), Source_PDF_EF::correct_incr_pressure(), Modele_turbulence_hyd_LES_selectif_mod_VDF::cutoff(), Modele_turbulence_hyd_LES_selectif_VDF::cutoff(), Op_Div_VEFP1B_Elem::degres_liberte(), Transport_Interfaces_FT_Disc::deplacer_maillage_ft_v_fluide(), Domaine_Poly_base::detecter_faces_non_planes(), Transport_Marqueur_FT::detection_groupes_a_supprimer(), Op_EF_base::dimensionner(), Op_PolyMAC_Elem::dimensionner(), Op_VEF_Face::dimensionner(), Navier_Stokes_FT_Disc::discretiser(), Transport_Interfaces_FT_Disc::discretiser(), Transport_Marqueur_FT::discretiser(), Domaine_EF::discretiser(), Domaine_EF_axi::discretiser(), Domaine_Poly_base::discretiser(), Domaine_VF::discretiser(), Domaine_PolyMAC_P0::discretiser(), Domaine_VDF::discretiser(), Domaine_VEF::discretiser(), Domaine_VEF::discretiser_arete(), Domaine_Poly_base::discretiser_aretes(), PolyMAC_discretisation::discretiser_champ(), PolyMAC_P0P1NC_discretisation::discretiser_champ(), Domaine_VF::discretiser_no_face(), Domaine_VEF::discretiser_suite(), Domaine_VDF::dist_face_period(), Domaine_Cl_dis_base::domaine(), Champ_Fonc_base::domaine(), Champ_Inc_base::domaine(), Domaine_EF_axi::domaine_axi(), Maillage_FT_Disc::echanger_facettes(), Maillage_FT_Disc::echanger_sommets_PE(), ecrire_noms_bords(), Domaine_Poly_base::elem_arete_d(), Domaine_Poly_base::elem_som_d(), Op_Diff_RotRot::elements_pour_sommet(), Remailleur_Collision_FT_Thomas::elements_voisins(), Champ_val_tot_sur_vol_VEF::eval_contrib_loc(), Champ_Generique_Reduction_0D::extraire(), Extraire_surface::extraire_surface_without_cleaning(), Domaine_PolyMAC_P0::fgrad(), IJK_Composantes_Connex::fill_mixed_cell_compo(), Champ_P1NC_implementation::filtrer_H1(), Champ_P1NC_implementation::filtrer_L2(), Champ_P1NC_implementation::filtrer_resu(), Post_Processing_Hydrodynamic_Forces::find_neighboring_elements(), Post_Processing_Hydrodynamic_Forces::find_neighboring_faces(), Champ_Fonc_P0_base::fixer_nb_valeurs_nodales(), Champ_Inc_P0_base::fixer_nb_valeurs_nodales(), Champ_Ostwald::fixer_nb_valeurs_nodales(), Champ_P1NC_implementation::fixer_nb_valeurs_nodales(), Source_PDF_EF::get_champ(), Champ_Generique_Transformation::get_champ(), Champ_Generique_Tparoi_VEF::get_champ(), Champ_implementation::get_domaine_geom(), Champ_Generique_refChamp::get_ref_connectivity(), Champ_Generique_base::get_ref_domain(), Champ_input_P0::getTemplate(), Champ_Q1_EF::gradient(), Op_Diff_VEFP1NCP1B_Face::gradient_som(), Op_Diff_VEFP1NCP1B_Face::gradient_som_CL(), Mass_Redistribution_Phase_Field::impose_mass_redistribution(), Domaine_Cl_EF::imposer_cond_lim(), Domaine_Cl_EF::imposer_symetrie(), Domaine_Cl_EF::imposer_symetrie_matrice_secmem(), Op_Grad_VEF_P1B_Face::impr(), Op_EF_base::impr(), Op_VEF_Face::impr(), Transport_Interfaces_FT_Disc::impr(), Op_Grad_EF::impr(), Op_Grad_VDF_Face::impr(), Champ_Elem_DG::imprime(), Champ_Fonc_P1_EF::imprime(), Champ_Fonc_Q1_EF::imprime(), Champ_P0_EF::imprime(), Champ_P1_EF::imprime(), Champ_Q1_EF::imprime(), Champ_Elem_PolyMAC::imprime(), Champ_Fonc_Som_PolyMAC::imprime(), Champ_Som_PolyMAC::imprime(), Champ_Fonc_Q1_VDF::imprime(), Champ_Fonc_Q1_VEF::imprime(), Loi_Paroi_Nu_Impose_VEF::imprimer_nusselt(), Domaine_VF::ind_faces_virt_bord(), Domaine_VF::info_elem_som(), Domaine_VF::infobord(), Echange_contact_Correlation_VEF::init(), Traitement_particulier_NS_THI_VDF::init_calc_spectre(), Traitement_particulier_NS_THI_VEF_new::init_calc_spectre(), Traitement_particulier_NS_Profils_VDF::init_calcul_moyenne(), Traitement_particulier_Solide_canal_VDF::init_calcul_moyenne(), Terme_Source_Solide_SWIFT_VDF::init_calcul_moyenne(), Terme_Source_Canal_RANS_LES_VDF_Face::init_calcul_moyenne_spat(), Domaine_VF::init_dist_paroi_globale(), Domaine_PolyMAC::init_equiv(), ParoiVEF_TBLE::init_lois_paroi(), ParoiVEF_TBLE_scal::init_lois_paroi(), Domaine_PolyMAC::init_m1_2d(), Domaine_PolyMAC::init_m1_3d(), Transport_Interfaces_FT_Disc::init_particles_position_velocity(), Domaine_PolyMAC::init_rf(), Domaine_PolyMAC_P0::init_stencils(), Modele_Lam_Bremhorst_VEF::init_tenseur_elem(), Modele_Shih_Zhu_Lumley_VEF::init_tenseur_elem(), Domaine_PolyMAC::init_ve(), Domaine_VDF::init_virt_e_map(), Domaine_PolyMAC::init_virt_ef_map(), Domaine_PolyMAC::init_we(), Domaine_PolyMAC::init_we_2d(), Raccord_distant_homogene_32_64< _SIZE_ >::initialise(), Sonde::initialiser(), Op_Diff_VEFP1NCP1B_Face::initialiser(), Echange_contact_VDF::initialiser(), Champ_front_contact_VEF::initialiser(), Champ_front_calc::initialiser(), Remailleur_Collision_FT_Thomas::initialiser_data(), IJK_Interfaces::initialize(), Transport_Interfaces_FT_Disc::interpoler_vitesse_face(), Integrer_champ_med::interpreter(), Extraire_surface_ALE::interpreter_(), Extraire_domaine::interpreter_(), Extraire_plan::interpreter_(), Extraire_surface::interpreter_(), Op_Diff_VEFP1NCP1B_Face::isInStencil(), Domaine_VF::joint(), Domaine_VEF::lecture_ok_arete(), Modele_turbulence_hyd_base::limiter_viscosite_turbulente(), Transport_Interfaces_FT_Disc::lire_maillage_ft_cao(), Convection_Diffusion_Temperature::lire_motcle_non_standard(), Perte_Charge_Singuliere::lire_surfaces(), Sauvegarde_Reprise_Maillage_FT::lire_xyz(), Op_Diff_VEFP1NCP1B_Face::liste_face(), Domaine_PolyMAC_P0P1NC::M1(), Convection_Diffusion_Concentration_FT_Disc::marquer_faces_sous_domaine(), Convection_Diffusion_Concentration_Turbulent_FT_Disc::marquer_faces_sous_domaine(), Discretisation_base::mesh_numbering(), Convection_Diffusion_Temperature_FT_Disc::mettre_a_jour(), Echange_contact_rayo_semi_transp_VDF::mettre_a_jour(), Estimateur_Aposteriori_P0_VEF::mettre_a_jour(), Echange_contact_Rayo_transp_VDF::mettre_a_jour(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::mettre_a_jour(), PlaqThVDF::mettre_a_jour(), Remailleur_Collision_FT_Thomas::mettre_a_jour_data(), Assembleur_P_VEFPreP1B::modifier_matrice(), Domaine_EF::modifier_pour_Cl(), Domaine_Poly_base::modifier_pour_Cl(), Domaine_PolyMAC::modifier_pour_Cl(), Domaine_VEF::modifier_pour_Cl(), Assembleur_P_VEFPreP1B::modifier_secmem(), Assembleur_P_VEFPreP1B::modifier_secmem_som(), Assembleur_P_VEFPreP1B::modifier_solution(), Eq_rayo_semi_transp_VDF::nb_colonnes(), Eq_rayo_semi_transp_VDF::nb_colonnes_tot(), nb_elem(), nb_elem_tot(), Domaine_VF::nb_faces_bord(), nb_front_Cl(), Domaine_VF::nb_joints(), nb_som(), nb_som_tot(), Discretisation_tools::nodes_to_cells(), Champ_P1NC::norme_H1(), Terme_Source_Qdm_lambdaup_VEF_Face::norme_H1(), Champ_P1_isoP1Bulle::norme_L2(), Domaine_VF::numero_sommet_local(), Domaine_Poly_base::orthocentrer(), Operateur_base::ouvrir_fichier(), Parcours_interface::parcourir(), Op_Conv_DI_L2_VEF_Face::poly_DI_L2_2d(), Op_Conv_DI_L2_VEF_Face::poly_DI_L2_3d(), Source_Con_Phase_field::premier_demi_dt(), Assembleur_P_VEFPreP1B::projete_L2(), Domaine_Poly_base::pvol_som(), Transport_Interfaces_FT_Disc::ramasse_miettes(), rang_frontiere(), Transport_Interfaces_FT_Disc::readOn(), IJK_VDF_converter::readOn(), Domaine_Cl_dis_base::readOn(), Op_Conv_DI_L2_VEF_Face::reconst_DI_L2_2d(), Op_Conv_DI_L2_VEF_Face::reconst_DI_L2_3d(), Assembleur_P_VEF::remplir(), Porosites::remplir_champ(), Champ_front_contact_VEF::remplir_connect_bords(), Champ_P0_VDF::remplir_coord_noeuds(), Champ_P1iP1B_implementation::remplir_coord_noeuds(), Connectivite_frontieres::remplir_def_face_aretes(), Domaine_VF::remplir_face_numero_bord(), Connectivite_frontieres::remplir_faces_voisins(), Op_Conv_VEF_Face::remplir_fluent(), Operateur_Conv_sensibility_VEF::remplir_fluent(), Domaine_Cl_VEF::remplir_normales_facettes_Cl(), Op_Diff_VEF_base::remplir_nu(), Op_Diff_EF::remplir_nu(), Op_Dift_EF_Q1::remplir_nu(), Op_Diff_VEFP1NCP1B_Face::remplir_nu_p1(), Perte_Charge_Reguliere_VEF_P1NC::remplir_num_faces(), Traitement_particulier_NS_canal_VDF::remplir_Tab_recap(), Domaine_Cl_EF::remplir_type_elem_Cl(), Domaine_Cl_VEF::remplir_type_elem_Cl(), Domaine_Cl_VEF::remplir_volumes_entrelaces_Cl(), Traitement_particulier_NS_canal_VDF::remplir_Y(), Traitement_particulier_NS_THI_VDF::renorm_Ec(), Domaine_VF::renumeroter(), Domaine_EF::reordonner(), Domaine_Poly_base::reordonner(), Domaine_VDF::reordonner(), Domaine_VEF::reordonner(), Transport_Interfaces_FT_Disc::reprendre(), Champ_Fonc_reprise_IJK::reprendre_IJK(), Precond_local::res_syst_loc_hybride(), IJK_One_Dimensional_Subproblems_Interfaces_Fields::retrieve_interfacial_surface_quantity(), Source_PDF_EF::rotate_imposed_velocity(), Champ_Fonc_base::sauvegarder(), Collision_Model_FT_base::set_geometric_parameters(), Domaine_Poly_base::som_elem(), Op_Diff_RotRot::sommets_pour_element(), Op_Diff_RotRot::sommets_voisins(), Terme_Source_Canal_perio::source_convection_diffusion(), Terme_Source_Canal_perio_VDF_P0::source_convection_diffusion(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::stabilise_moyenne_6_points(), Modele_turbulence_scal_LES_dyn_VDF::stabilise_moyenne_6_points(), Modele_turbulence_scal_LES_dyn_VDF::stabilise_moyenne_euler(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::stabilise_moyenne_euler_lagrange(), Modele_turbulence_scal_LES_dyn_VDF::stabilise_moyenne_lagrange(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::stabilise_moyenne_plans_paralleles(), Modele_turbulence_scal_LES_dyn_VDF::stabilise_moyenne_plans_paralleles(), Convection_Diffusion_Temperature_FT_Disc::suppression_interfaces(), Domaine_PolyMAC_P0P1NC::surf_elem_arete(), Transport_Interfaces_FT_Disc::swap_particles_lagrangian_position_velocity(), Op_Diff_VEFP1NCP1B_Face::test(), Transport_Interfaces_FT_Disc::test_suppression_interfaces_sous_domaine(), Champ_Face_PolyMAC_P0P1NC::trace(), Remailleur_Collision_FT_Juric::traite_RuptureCoalescenceInterfaces(), Remailleur_Collision_FT_Thomas::traite_RuptureCoalescenceInterfaces_Conservatif(), Remailleur_Collision_FT_Thomas::transport_volume_perdu_sur_element(), Remailleur_Collision_FT_Thomas::transport_volume_perdu_sur_sommet(), Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_elem(), Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_gradU_face(), Domaine_VF::typer_discretiser_ss_domaine(), Milieu_base::update_rho_cp(), Champ_Inc_base::valeur_a(), Champ_Fonc_MED::valeur_a(), Champ_Face_VDF_implementation::valeur_a_elem_compo(), Champ_P1_isoP1Bulle::valeur_au_bord(), Champ_Fonc_base::valeur_aux(), Champ_Elem_DG::valeur_aux(), Champ_Inc_base::valeur_aux(), Champ_P1NC_implementation::valeur_aux_centres_de_gravite(), Champ_Fonc_Face_VDF::valeur_aux_compo(), Champ_Inc_base::valeur_aux_compo(), Champ_P1iP1B_implementation::valeur_aux_elems(), Champ_Fonc_Face_PolyMAC::valeur_aux_elems(), Champ_Face_PolyMAC::valeur_aux_elems_(), Champ_P1NC_implementation::valeur_aux_elems_compo_smooth(), Champ_P1NC_implementation::valeur_aux_elems_smooth(), Champ_P1iP1B_implementation::valeur_aux_sommets(), Champ_Q1NC_implementation::valeur_aux_sommets(), Champ_Q1NC_implementation::valeur_aux_sommets_compo(), Domaine_VEF::vecteur_face_facette(), Source_PDF_EF::verif_ajouter_contrib(), Domaine_EF::verifie_compatibilite_domaine(), Domaine_EF_axi::verifie_compatibilite_domaine(), Domaine_VEF::verifie_ok_arete(), Echange_contact_VDF::verifier_correspondance(), Assembleur_P_VEFPreP1B::verifier_dirichlet(), Domaine_Poly_base::vol_elem_som(), Op_Div_EF::volumique(), Op_Div_PolyMAC::volumique(), Op_Div_VDF_Elem::volumique(), and Domaine_PolyMAC_P0P1NC::W1().
domaine() [2/2]
Domaine & Domaine_dis_base::domaine () inline
References le_dom.
nb_elem()
int Domaine_dis_base::nb_elem () const inline
References domaine(), and Domaine_32_64< _SIZE_ >::nb_elem().
Referenced by Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_Vort_VEF_Face::ajouter(), Source_Transport_Fluctuation_Temperature_VDF_Elem::ajouter(), Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::ajouter(), Source_Transport_Fluctuation_Temperature_W_VDF_Elem::ajouter(), Source_Transport_Flux_Chaleur_Turbulente_VDF_Face::ajouter(), Terme_Source_Rappel_T_VEF_Face::ajouter(), Source_rayo_semi_transp_VDF_P0_VDF::ajouter(), Source_Transport_K_Eps_Bas_Reynolds_aniso_therm_concen_VDF_Elem::ajouter_blocs(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_VDF_Elem::ajouter_blocs(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_QC_VDF_Elem::ajouter_blocs(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_W_VDF_Elem::ajouter_blocs(), Source_Transport_K_KEps_VDF_Elem::ajouter_blocs(), Terme_Source_Canal_perio_VDF_P0::ajouter_blocs(), Terme_Source_Canal_RANS_LES_VDF_Elem::ajouter_blocs(), Force_Centrifuge_VDF_Face_Axi::ajouter_blocs(), Terme_Source_Solide_SWIFT_VDF::ajouter_blocs(), Masse_PolyMAC_Elem::appliquer_impl(), Masse_VDF_Elem::appliquer_impl(), Op_Diff_RotRot::associer(), Source_Dirac_VDF_Elem::associer_domaines(), Source_Dirac_VEF_Face::associer_domaines(), Domaine_VF::build_mc_dual_mesh(), Champ_Q1NC::cal_rot_ordre1(), Champ_P1NC::cal_rot_ordre1(), Champ_Face_VDF::calcul_critere_Q(), Champ_P1NC::calcul_critere_Q(), Traitement_particulier_NS_THI_VEF::calcul_Df_spatial(), Modele_Jones_Launder_VEF::Calcul_E(), Modele_Launder_Sharma_VEF::Calcul_E(), Modele_Jones_Launder_Thermique_VDF::Calcul_E(), Modele_Jones_Launder_Thermique_VDF::Calcul_F1(), Modele_Jones_Launder_VDF::Calcul_F1(), Modele_Jones_Launder_VDF::Calcul_F1_BiK(), Modele_Jones_Launder_Thermique_VDF::Calcul_F2(), Modele_Jones_Launder_VDF::Calcul_F2(), Modele_Jones_Launder_VDF::Calcul_F2_BiK(), Modele_Jones_Launder_Thermique_VDF::Calcul_F3(), Modele_Jones_Launder_Thermique_VDF::Calcul_F4(), Modele_Jones_Launder_Thermique_VDF::Calcul_Flambda(), Modele_Jones_Launder_VDF::Calcul_Fmu(), Modele_Launder_Sharma_VDF::Calcul_Fmu(), Modele_Jones_Launder_VDF::Calcul_Fmu_BiK(), Modele_Launder_Sharma_VDF::Calcul_Fmu_BiK(), Champ_P1NC::calcul_grad_U(), Champ_Face_VDF::calcul_grad_u(), Traitement_particulier_NS_THI_VEF::calcul_nu_t(), Transport_Marqueur_FT::calcul_proprietes_geometriques(), Champ_Face_VDF::calcul_S_barre(), Champ_P1NC::calcul_S_barre(), Traitement_particulier_NS_THI_VEF::calcul_Sk(), Traitement_particulier_NS_THI_VEF::calcul_volume_elem(), Source_Con_Phase_field::calculer_alpha_gradC_carre(), Op_Dift_EF_base::calculer_borne_locale(), Op_Dift_VDF_Face_base::calculer_borne_locale(), Op_Dift_VEF_base::calculer_borne_locale(), Source_Con_Phase_field::calculer_champ_fonc_c(), Champ_Face_VDF::calculer_dercov_axi(), Champ_Ostwald_VEF::calculer_dscald(), Champ_Face_VDF::calculer_dscald_centre_element(), Op_Diff_K_Eps_Bas_Re_VDF_var_Elem::calculer_dt_stab(), Op_Diff_EF_base::calculer_dt_stab(), Op_Conv_PolyMAC_iterateur_base::calculer_dt_stab(), Op_Conv_VDF_base::calculer_dt_stab(), Op_Dift_Multiphase_VDF_Elem::calculer_dt_stab(), Op_Dift_Multiphase_VDF_Face::calculer_dt_stab(), Op_Diff_VEF_base::calculer_dt_stab(), Op_Dift_VDF_Face_base::calculer_dt_stab(), Op_Diff_VDF_base::calculer_dt_stab_(), Op_Dift_VDF_Elem_base::calculer_dt_stab_elem(), Op_Dift_VDF_Elem_base::calculer_dt_stab_elem_axi(), Op_Dift_VDF_Elem_base::calculer_dt_stab_elem_var_axi(), Modele_turbulence_hyd_Longueur_Melange_VEF::calculer_f_amortissement(), Modele_turbulence_hyd_LES_1elt_VEF::calculer_fonction_structure(), EDO_Pression_th_VEF::calculer_grad(), Source_Transport_Flux_Chaleur_Turbulente_VDF_Face::calculer_Grad_U(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_W_VDF_Elem::calculer_gteta2(), Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::calculer_gteta2(), Source_Transport_Fluctuation_Temperature_W_VDF_Elem::calculer_gteta2(), Source_Transport_Flux_Chaleur_Turbulente_VDF_Face::calculer_gteta2(), Domaine_EF::calculer_h_carre(), Domaine_VEF::calculer_h_carre(), Domaine_DG::calculer_h_carre(), Domaine_PolyMAC::calculer_h_carre(), Transport_Interfaces_FT_Disc::calculer_integrale_indicatrice(), Algorithmes_Transport_FT_Disc::calculer_moments_indicatrice(), Op_Conv_PolyMAC_iterateur_base::calculer_pour_post(), Op_Conv_VDF_base::calculer_pour_post(), Op_Diff_VEF_base::calculer_pour_post(), Source_Transport_Fluctuation_Temperature_VDF_Elem::calculer_Prod_uteta_T(), Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::calculer_Prod_uteta_T(), Source_Transport_Fluctuation_Temperature_W_VDF_Elem::calculer_Prod_uteta_T(), Modele_turbulence_hyd_LES_Fst_VEF::calculer_racine(), Champ_Face_VDF::calculer_rotationnel_ordre2_centre_element(), Modele_turbulence_hyd_LES_Smago_filtre_VEF::calculer_S_barre(), Paroi_ODVM_scal_VDF::calculer_scal(), Paroi_TBLE_scal_VDF::calculer_scal(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calculer_Sij(), Calcul_Production_K_VDF::calculer_terme_destruction_K(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_W_VDF_Elem::calculer_terme_destruction_K_W(), Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::calculer_terme_destruction_K_W(), Source_Transport_Fluctuation_Temperature_W_VDF_Elem::calculer_terme_destruction_K_W(), Calcul_Production_K_VDF::calculer_terme_production_K_Axi(), Calcul_Production_K_VDF::calculer_terme_production_K_BiK_Axi(), Calcul_Production_K_VDF::calculer_terme_production_K_for_komega(), Source_Transport_Fluctuation_Temperature_W_VDF_Elem::calculer_u_teta_W(), Source_Transport_Flux_Chaleur_Turbulente_VDF_Face::calculer_uiuj(), Modele_turbulence_hyd_LES_1elt_VEF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_Fst_VEF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_VEF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_combinaison::calculer_viscosite_turbulente(), Modele_turbulence_hyd_Longueur_Melange_VDF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_Smago_VEF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_Wale_VEF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_Longueur_Melange_VEF::calculer_viscosite_turbulente(), Transport_Interfaces_FT_Disc::calculer_vitesse_transport_interpolee(), Maillage_FT_Disc::check_sommets(), Terme_Source_Rappel_T_VEF_Face::completer(), Domaine_VF::compute_L1_norm(), Domaine_DG::compute_L1_norm(), Domaine_VF::compute_L2_norm(), Domaine_DG::compute_L2_norm(), Navier_Stokes_FT_Disc::compute_particles_eulerian_id_number(), Transport_Interfaces_FT_Disc::compute_particles_rms(), Interpolation_IBM_elem_fluid::computeFluidElems(), Interpolation_IBM_mean_gradient_proto::computeSommetsVoisins(), Champ_front_contact_VEF::connectivity_failed(), AssembleurPVDF_PF::construire(), Assembleur_P_VDF::construire(), EF_discretisation::creer_champ_vorticite(), VDF_discretisation::creer_champ_vorticite(), VEF_discretisation::creer_champ_vorticite(), Domaine_VDF::creer_elements_fictifs(), Traitement_particulier_NS_CEG::critere_cea_jaea(), VDF_discretisation::critere_Q(), EF_discretisation::critere_Q(), VEF_discretisation::critere_Q(), Modele_turbulence_hyd_LES_1elt_selectif_mod_VEF::cutoff(), Modele_turbulence_hyd_LES_Fst_sel_VEF::cutoff(), Transport_Interfaces_FT_Disc::deplacer_maillage_ft_v_fluide(), Maillage_FT_Disc::deplacer_un_sommet(), Terme_Source_Decroissance_Radioactive_Elem_PolyMAC::dimensionner_blocs(), DG_discretisation::discretiser_champ(), EF_discretisation::discretiser_champ(), PolyMAC_discretisation::discretiser_champ(), PolyMAC_P0P1NC_discretisation::discretiser_champ(), VDF_discretisation::discretiser_champ(), EF_discretisation::distance_paroi(), PolyMAC_discretisation::distance_paroi(), VEF_discretisation::distance_paroi(), Champ_val_tot_sur_vol_VDF::eval_contrib_loc(), Champ_val_tot_sur_vol_VEF::eval_contrib_loc(), Champ_val_tot_sur_vol_base::evaluer(), Champ_Generique_Reduction_0D::extraire(), Extraire_surface::extraire_surface_without_cleaning(), Discretisation_tools::faces_to_cells(), Domaine_VF::get_position(), Convection_Diffusion_Temperature::get_time_factor(), Champ_input_P0::getTemplate(), EF_discretisation::grad_T(), VEF_discretisation::grad_T(), VDF_discretisation::grad_u(), VEF_discretisation::grad_u(), PolyMAC_discretisation::grad_u(), Champ_Q1NC::gradient(), EF_discretisation::h_conv(), VEF_discretisation::h_conv(), Terme_Source_Canal_RANS_LES_VDF_Elem::init(), Terme_Source_Canal_RANS_LES_VDF_Face::init(), Traitement_particulier_NS_THI_VEF::init_calc_spectre(), Domaine_VF::init_dist_paroi_globale(), Paroi_TBLE_scal_VDF::init_lois_paroi(), Paroi_TBLE_QDM::init_lois_paroi(), Domaine_PolyMAC::init_m1_3d(), Domaine_VDF::init_virt_e_map(), Domaine_PolyMAC::init_virt_ef_map(), Modele_Shih_Zhu_Lumley_VDF::Initialisation(), Ch_front_var_instationnaire_dep::initialiser(), Champ_P0_VDF::integrale_espace(), Transport_Interfaces_FT_Disc::interpoler_vitesse_face(), Extraire_domaine::interpreter_(), Champ_Fonc_MED::lire(), Champ_Fonc_MED_Table_Temps::lire(), Traitement_particulier_NS_Pression_VDF::lire(), Traitement_particulier_NS_Brech_VEF::lire(), Traitement_particulier_NS_Pression_VEF::lire(), Champ_Fonc_MED_Table_Temps::lire_donnees_champ(), Navier_Stokes_FT_Disc::mettre_a_jour(), Transport_Interfaces_FT_Disc::mettre_a_jour(), QDM_Multiphase::mettre_a_jour(), Estimateur_Aposteriori_P0_VEF::mettre_a_jour(), Champ_Fonc_Tabule_Elem_PolyMAC::mettre_a_jour(), Champ_Fonc_Tabule_P0_VDF::mettre_a_jour(), Terme_Source_Canal_RANS_LES_VDF_Elem::mettre_a_jour(), Terme_Source_Canal_RANS_LES_VDF_Face::mettre_a_jour(), Champ_Fonc_Tabule_P0_VEF::mettre_a_jour(), Champ_P0_VDF::moyenne(), Champ_Fonc_P0_base::moyenne(), Domaine_EF::nb_elem_Cl(), Domaine_Poly_base::nb_elem_Cl(), Domaine_VEF::nb_elem_Cl(), Discretisation_tools::nodes_to_cells(), Terme_Source_Canal_RANS_LES_VDF_Face::norme_vit(), Parcours_interface::parcourir(), Transport_Interfaces_FT_Disc::PPP_face_interface(), EF_discretisation::proprietes_physiques_fluide_Ostwald(), VDF_discretisation::proprietes_physiques_fluide_Ostwald(), VEF_discretisation::proprietes_physiques_fluide_Ostwald(), AssembleurPVDF_PF::remplir(), Assembleur_P_VDF::remplir(), Champ_P0_VDF::remplir_coord_noeuds(), DP_Impose_PolyMAC_Face::remplir_num_faces(), Perte_Charge_Singuliere_PolyMAC_Face::remplir_num_faces(), Perte_Charge_Singuliere_VDF_Face::remplir_num_faces(), DP_Impose_VEF_Face::remplir_num_faces(), Perte_Charge_Singuliere_VEF_Face::remplir_num_faces(), Domaine_EF_axi::remplir_tableau_origine(), Domaine_EF::reordonner(), Domaine_Poly_base::reordonner(), Collision_Model_FT_base::research_collision_pairs_Verlet(), Eq_rayo_semi_transp_VDF::resoudre(), EDO_Pression_th_VDF_Gaz_Reel::resoudre(), Collision_Model_FT_base::set_LC_zones(), Terme_Source_Canal_perio_VDF_P0::source_convection_diffusion(), VDF_discretisation::t_paroi(), VEF_discretisation::t_paroi(), VDF_discretisation::taux_cisaillement(), VEF_discretisation::taux_cisaillement(), Moyenne_volumique::traiter_champs(), Champ_P1NC_implementation::valeur_aux_elems(), Champ_Fonc_Face_PolyMAC::valeur_aux_elems(), Champ_Face_PolyMAC::valeur_aux_elems_(), EF_discretisation::vorticite(), VDF_discretisation::vorticite(), VEF_discretisation::vorticite(), VDF_discretisation::y_plus(), EF_discretisation::y_plus(), and VEF_discretisation::y_plus().
nb_elem_tot()
int Domaine_dis_base::nb_elem_tot () const inline
References domaine(), and Domaine_32_64< _SIZE_ >::nb_elem_tot().
Referenced by Navier_Stokes_phase_field::_aff_donnee_P0(), Navier_Stokes_phase_field::_aff_donnee_P1Bulle(), Op_Diff_VDF_base::ajoute_terme_pour_axi(), Op_Dift_VDF_base::ajoute_terme_pour_axi_turb(), Op_Diff_K_Omega_VEF_Face::ajouter(), Op_Conv_Amont_old_VEF_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Centre_EF_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_EF_VEF_P1NC::ajouter(), Op_Conv_EF_VEF_P1NC_Stab::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_Muscl_New_VEF_Face::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Conv_Vort_VEF_Face::ajouter(), Op_Diff_VEF_Face_Stab::ajouter(), Op_Conv_RT_VEF_Face::ajouter(), Terme_Boussinesq_Sensibility_VEFPreP1B_Face::ajouter(), Source_Transport_Fluctuation_Temperature_VDF_Elem::ajouter(), Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::ajouter(), Source_Transport_Fluctuation_Temperature_W_VDF_Elem::ajouter(), Terme_Boussinesq_VEFPreP1B_Face::ajouter(), Terme_Source_Qdm_VEF_Face::ajouter(), Op_Diff_VEF_Face_Stab::ajouter_antidiffusion(), Source_Transport_K_Eps_Bas_Reynolds_aniso_therm_concen_VDF_Elem::ajouter_blocs(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_VDF_Elem::ajouter_blocs(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_QC_VDF_Elem::ajouter_blocs(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_W_VDF_Elem::ajouter_blocs(), Source_Transport_K_KEps_VDF_Elem::ajouter_blocs(), Couplage_Parietal_PolyMAC_helper::ajouter_blocs(), Op_Conv_Amont_old_VEF_Face::ajouter_contribution(), Op_Conv_VEF_Face::ajouter_contribution(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution(), Op_Conv_RT_VEF_Face::ajouter_contribution(), Operateur_Conv_sensibility_VEF::ajouter_conv_term(), Op_Diff_VEF_Face_Stab::ajouter_diffusion(), Operateur_Conv_sensibility_VEF::ajouter_Lsensibility_state_Amont(), Operateur_Conv_sensibility_VEF::ajouter_Lstate_sensibility_Amont(), Op_Diff_VEF_Face_Stab::ajouter_operateur_centre(), Source_Masse_Fluide_Dilatable_VEF::ajouter_projection(), Op_Conv_ALE_VEF::ajouterALE(), Eq_rayo_semi_transp_VDF::assembler_matrice(), Source_Con_Phase_field::assembler_matrice_point_fixe(), Domaine_DG::build_nfaces_elem_(), Champ_P1NC::cal_rot_ordre1(), Modele_Shih_Zhu_Lumley_VDF::Calcul_Cmu_et_S(), Modele_Shih_Zhu_Lumley_VDF::Calcul_Cmu_et_S_BiK(), Champ_Face_VDF::calcul_critere_Q(), Champ_P1NC::calcul_critere_Q(), Modele_Jones_Launder_VDF::Calcul_D(), Modele_Jones_Launder_VEF::Calcul_D(), Modele_Launder_Sharma_VEF::Calcul_D(), Modele_Jones_Launder_VDF::Calcul_D_BiK(), Modele_Jones_Launder_VEF::Calcul_D_BiK(), Modele_Launder_Sharma_VEF::Calcul_D_BiK(), Modele_Jones_Launder_VDF::Calcul_E(), Modele_Jones_Launder_Thermique_VDF::Calcul_E(), Champ_P1NC::calcul_grad_U(), Champ_Face_VDF::calcul_grad_u(), Tenseur_Reynolds_Externe_VDF_Face::Calcul_RSLambda(), Modele_Shih_Zhu_Lumley_VDF::Calcul_S(), Champ_Face_VDF::calcul_S_barre(), Champ_P1NC::calcul_S_barre(), Traitement_particulier_NS_THI_VEF::calcul_Sk(), Op_Conv_ALE_VEF::calculateALEMeshVelocityGradientOnFaces(), Domaine_EF::calculer_Bij(), Domaine_EF::calculer_Bij_gen(), Domaine_EF_axi::calculer_Bij_gen(), Op_Diff_VEF_Face_Stab::calculer_coefficients(), Op_Diff_VEFP1NCP1B_Face::calculer_divergence_elem(), Op_Diff_VEFP1NCP1B_Face::calculer_divergence_som(), Champ_Ostwald_VEF::calculer_dscald(), Op_Dift_EF_Q1::calculer_dt_stab(), Op_Conv_Muscl_New_VEF_Face::calculer_dt_stab(), Op_Dift_VEF_base::calculer_dt_stab(), Source_Transport_Flux_Chaleur_Turbulente_VDF_Face::calculer_Grad_U(), Op_Diff_VEFP1NCP1B_Face::calculer_gradient_som(), Domaine_Poly_base::calculer_h_carre(), Domaine_DG::calculer_h_carre(), Modele_turbulence_hyd_LES_VEF_base::calculer_longueurs_caracteristiques(), Op_Diff_VEF_Face_Stab::calculer_max(), Op_Diff_VEF_Face_Stab::calculer_min(), Modele_turbulence_hyd_LES_Wale_VDF::calculer_OP1_OP2(), Source_Con_Phase_field::calculer_point_fixe(), Op_Diff_VEF_base::calculer_pour_post(), Op_Dift_VEF_base::calculer_pour_post(), Modele_turbulence_hyd_LES_Fst_VEF::calculer_racine(), Modele_turbulence_hyd_LES_Smago_VDF::calculer_S_barre(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calculer_Sij(), Modele_turbulence_hyd_Longueur_Melange_VDF::calculer_Sij2(), Modele_turbulence_hyd_Longueur_Melange_VEF::calculer_Sij2(), Calcul_Production_K_VEF::calculer_terme_destruction_K_gen(), Calcul_Production_K_VEF::calculer_terme_production_K(), Calcul_Production_K_VEF::calculer_terme_production_K_BiK(), Source_Con_Phase_field::calculer_u2_elem(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_W_VDF_Elem::calculer_u_teta_W(), Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::calculer_u_teta_W(), Source_Transport_Flux_Chaleur_Turbulente_VDF_Face::calculer_uiuj(), Modele_turbulence_hyd_LES_Fst_VEF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_Smago_VDF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_Wale_VDF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_Longueur_Melange_VDF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_Smago_VEF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_Wale_VEF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_Longueur_Melange_VEF::calculer_viscosite_turbulente(), Discretisation_tools::cells_to_faces(), Discretisation_tools::cells_to_nodes(), Assembleur_P_VEFPreP1B::changer_base(), Op_Conv_VEF_Face::completer(), Tensors_Computation_VEF::compute_enstrophy(), Domaine_DG::compute_mesh_param(), Interpolation_IBM_elem_fluid::computeFluidElems(), Interpolation_IBM_mean_gradient_proto::computeSommetsVoisins(), AssembleurPVDF_PF::construire(), Assembleur_P_VDF::construire(), Source_Con_Phase_field::construire_systeme(), Op_Diff_K_Omega_VEF_Face::contribuer_a_avec(), Domaine_VDF::creer_elements_fictifs(), Op_Grad_PolyMAC_Face::dimensionner(), Op_Div_PolyMAC::dimensionner(), Op_PolyMAC_Elem::dimensionner_bloc_vitesse(), Op_Diff_VDF_Elem_base::dimensionner_blocs(), Domaine_DG::discretiser(), Domaine_Poly_base::discretiser(), Domaine_Poly_base::discretiser_aretes(), Viscosite_turbulente_WALE::eddy_viscosity(), Domaine_Poly_base::elem_arete_d(), Domaine_Poly_base::elem_som_d(), Discretisation_tools::faces_to_cells(), Domaine_PolyMAC_P0::fgrad(), Champ_Generique_Transformation::get_champ(), Domaine_PolyMAC::init_m1_2d(), Domaine_PolyMAC::init_m1_3d(), Domaine_PolyMAC::init_m2solv(), Domaine_PolyMAC_P0::init_stencils(), Domaine_PolyMAC::init_ve(), Domaine_VDF::init_virt_e_map(), Domaine_PolyMAC::init_virt_ef_map(), Domaine_PolyMAC::init_we_2d(), Domaine_PolyMAC::init_we_3d(), Echange_contact_PolyMAC::initialiser(), Transport_Interfaces_FT_Disc::interpoler_vitesse_face(), Imprimer_Fichiers_RANS_VDF::interpreter(), Op_Diff_VEFP1NCP1B_Face::liste_face(), Estimateur_Aposteriori_P0_VEF::mettre_a_jour(), Champ_Fonc_Tabule_Elem_PolyMAC::mettre_a_jour(), Champ_Fonc_Tabule_P0_VDF::mettre_a_jour(), Champ_Fonc_Tabule_P0_VEF::mettre_a_jour(), Discretisation_tools::nodes_to_cells(), Source_Con_Phase_field::non_lin_gmres(), Domaine_VEF::numero_premier_sommet(), Domaine_VEF::numero_premiere_arete(), Source_Con_Phase_field::premier_demi_dt(), Domaine_Poly_base::pvol_som(), Champ_P1iP1B_implementation::remplir_coord_noeuds(), Op_Conv_VEF_Face::remplir_fluent(), Operateur_Conv_sensibility_VEF::remplir_fluent(), Op_Dift_EF_Q1::remplir_marqueur_elem_CL_paroi(), Perte_Charge_Reguliere_VDF_Face::remplir_num_faces(), Perte_Charge_Reguliere_VEF_P1NC::remplir_num_faces(), Collision_Model_FT_base::set_LC_zones(), Domaine_PolyMAC_P0P1NC::surf_elem_arete(), Champ_Q1NC_implementation::transforme_coord2D(), Champ_Q1NC_implementation::transforme_coord3D(), Echange_contact_PolyMAC::update_coeffs(), Champ_Fonc_Face_PolyMAC::valeur_aux_elems(), Domaine_VEF::vecteur_face_facette(), Domaine_Poly_base::vol_elem_som(), and Op_Div_VEFP1B_Elem::volumique().
nb_som()
int Domaine_dis_base::nb_som () const inline
References domaine(), and Domaine_32_64< _SIZE_ >::nb_som().
Referenced by Navier_Stokes_phase_field::_aff_donnee_P1Bulle(), Solveur_Masse_EF::appliquer_impl(), Op_Diff_RotRot::associer(), Op_Diff_VEFP1NCP1B_Face::calculer_gradient_som(), Domaine_EF::calculer_porosites_sommets(), Domaine_EF::calculer_volumes_sommets(), Discretisation_tools::cells_to_nodes(), Interpolation_IBM_elem_fluid::computeFluidElems(), Interpolation_IBM_mean_gradient_proto::computeSommetsVoisins(), Domaine_VEF::construire_ok_arete(), Op_EF_base::dimensionner(), EF_discretisation::discretiser_champ(), PolyMAC_discretisation::discretiser_champ(), PolyMAC_P0P1NC_discretisation::discretiser_champ(), Domaine_VEF::modifier_pour_Cl(), Champ_P1iP1B_implementation::valeur_aux_sommets(), and Domaine_VEF::verifie_ok_arete().
nb_som_tot()
int Domaine_dis_base::nb_som_tot () const inline
References domaine(), and Domaine_32_64< _SIZE_ >::nb_som_tot().
Referenced by PDF_model::affecter_variable_imposee(), Op_Conv_VEF_Face::ajouter(), Operateur_Conv_sensibility_VEF::ajouter_conv_term(), Operateur_Conv_sensibility_VEF::ajouter_Lsensibility_state_Amont(), Operateur_Conv_sensibility_VEF::ajouter_Lstate_sensibility_Amont(), Op_Conv_ALE_VEF::ajouterALE(), Masse_PolyMAC_Face::appliquer_impl(), Op_Diff_VEFP1NCP1B_Face::calculer_gradient_som(), Discretisation_tools::cells_to_nodes(), Interpolation_IBM_elem_fluid::computeFluidElems(), Interpolation_IBM_mean_gradient_proto::computeSommetsVoisins(), Op_EF_base::dimensionner(), Domaine_Poly_base::discretiser_aretes(), Domaine_Cl_VEF::imposer_cond_lim(), Domaine_PolyMAC::init_m1_2d(), Domaine_PolyMAC::init_we(), Discretisation_tools::nodes_to_cells(), Domaine_VEF::numero_premiere_arete(), Champ_P1iP1B_implementation::remplir_coord_noeuds(), Domaine_Poly_base::som_elem(), and Op_Div_VEFP1B_Elem::volumique().
nb_front_Cl()
int Domaine_dis_base::nb_front_Cl () const inline
References domaine(), and Domaine_32_64< _SIZE_ >::nb_front_Cl().
Referenced by Operateur_Conv_sensibility_VEF::add_diffusion_scalar_term(), Operateur_Conv_sensibility_VEF::add_diffusion_term(), Op_Grad_PolyMAC_Face::ajouter(), Op_Conv_Amont_old_VEF_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Centre_EF_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_EF_VEF_P1NC::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Conv_Vort_VEF_Face::ajouter(), Op_Diff_VEF_Face_Q1::ajouter(), Op_Dift_VEF_Face_Q1::ajouter(), Op_Div_VEFP1B_Elem::ajouter(), Source_Reaction_Particules_VDF::ajouter(), Source_Reaction_Particules_VEF::ajouter(), SourceFiltree_FT_disc_VEF_P1NC::ajouter(), Terme_Boussinesq_Sensibility_VEFPreP1B_Face::ajouter(), Source_Transport_Flux_Chaleur_Turbulente_VDF_Face::ajouter(), Source_Robin::ajouter(), Source_Robin_Scalaire::ajouter(), Terme_Source_Qdm_Face_PolyMAC::ajouter(), Terme_Boussinesq_VEFPreP1B_Face::ajouter(), Terme_Source_Qdm_VEF_Face::ajouter(), Tenseur_Reynolds_Externe_VDF_Face::ajouter_blocs(), Source_Transport_K_KEps_VDF_Elem::ajouter_blocs(), Op_Grad_P0_to_Face::ajouter_blocs(), Op_Grad_VDF_Face::ajouter_blocs(), Terme_Source_Canal_perio_VDF_Face::ajouter_blocs(), Force_Centrifuge_VDF_Face_Axi::ajouter_blocs(), Terme_Boussinesq_VDF_Face::ajouter_blocs(), Terme_Source_Acceleration_VDF_Face::ajouter_blocs(), Terme_Source_Coriolis_VDF_Face::ajouter_blocs(), Terme_Source_inc_th_VDF_Face::ajouter_blocs(), Terme_Source_inc_VDF_Face::ajouter_blocs(), Terme_Source_Qdm_VDF_Face::ajouter_blocs(), Op_Grad_EF::ajouter_bord(), Op_Dift_EF_Q1::ajouter_bords(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Face::ajouter_cas_vectoriel(), Op_Conv_Amont_old_VEF_Face::ajouter_contribution(), Op_Conv_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution(), Op_Diff_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Face_Q1::ajouter_contribution(), Op_Diff_VEF_Face_Stab::ajouter_contribution(), Op_Conv_RT_VEF_Face::ajouter_contribution(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution_elem(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face_Stab::ajouter_contribution_multi_scalaire(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution_som(), Operateur_Conv_sensibility_VEF::ajouter_conv_term(), Operateur_Conv_sensibility_VEF::ajouter_Lsensibility_state_Amont(), Operateur_Conv_sensibility_VEF::ajouter_Lstate_sensibility_Amont(), Op_Conv_ALE_VEF::ajouterALE(), Tensors_Computation_VEF::antisym_loop_edge_faces(), Masse_VDF_Face::appliquer_impl(), Masse_VEF_P1NC::appliquer_impl(), Assembleur_P_EF::assembler_mat(), LoiParoiHybride::associer(), Traitement_particulier_NS_chmoy_faceperio_VEF::calcul_chmoy_faceperio(), Modele_Jones_Launder_VDF::Calcul_D(), Modele_Jones_Launder_Thermique_VDF::Calcul_D(), Modele_Jones_Launder_VDF::Calcul_D_BiK(), Modele_Jones_Launder_VDF::Calcul_E(), Modele_Jones_Launder_Thermique_VDF::Calcul_E(), Champ_P1NC::calcul_h_conv(), Traitement_particulier_NS_temperature_VEF::calcul_temperature(), Champ_Q1_EF::calcul_y_plus(), Champ_P1NC::calcul_y_plus(), Champ_Face_VDF::calcul_y_plus(), Champ_P1NC::calcul_y_plus_diphasique(), Champ_Face_VDF::calcul_y_plus_diphasique(), Terme_Source_Canal_perio_VDF_Face::calculer_debit(), Terme_Source_Canal_perio_VEF_P1NC::calculer_debit(), Op_Conv_VDF_base::calculer_dt_local(), Op_Conv_VEF_base::calculer_dt_local(), Op_Conv_ALE_VEF::calculer_dt_stab(), Operateur_Conv_sensibility_VEF::calculer_dt_stab(), Op_Conv_PolyMAC_iterateur_base::calculer_dt_stab(), Op_Conv_VDF_base::calculer_dt_stab(), Op_Conv_VEF_base::calculer_dt_stab(), Traitement_particulier_NS_EC::calculer_Ec(), Op_Grad_EF::calculer_flux_bords(), Op_Grad_VDF_Face::calculer_flux_bords(), Op_Diff_VEFP1NCP1B_Face::calculer_flux_bords_elem(), Op_Diff_VEFP1NCP1B_Face::calculer_flux_bords_som(), Modele_turbulence_hyd_LES_VDF::calculer_fonction_structure(), Modele_turbulence_hyd_LES_axi_VDF::calculer_fonction_structure(), EDO_Pression_th_VEF::calculer_grad(), Navier_Stokes_FT_Disc::calculer_gradient_indicatrice(), ParoiVDF_TBLE_LRM::calculer_hyd(), Paroi_std_hyd_VEF::calculer_hyd(), Paroi_negligeable_VDF::calculer_hyd(), Paroi_negligeable_VEF::calculer_hyd(), Paroi_std_hyd_VDF_diphasique::calculer_hyd(), Paroi_std_hyd_VEF_diphasique::calculer_hyd(), Paroi_loi_WW_hyd_EF::calculer_hyd(), Paroi_std_hyd_EF::calculer_hyd(), Paroi_2couches_VDF::calculer_hyd(), Paroi_loi_Ciofalo_hyd_VDF::calculer_hyd(), Paroi_loi_WW_hyd_VDF::calculer_hyd(), Paroi_loi_WW_hyd_VEF::calculer_hyd(), Paroi_std_hyd_VDF::calculer_hyd(), Paroi_UTAU_IMP_VDF::calculer_hyd(), LoiParoiHybride::calculer_hyd(), ParoiVDF_TBLE::calculer_hyd(), ParoiVEF_TBLE::calculer_hyd(), Paroi_std_hyd_VDF::calculer_hyd_BiK(), Paroi_UTAU_IMP_VDF::calculer_hyd_BiK(), ParoiVDF_TBLE::calculer_hyd_BiK(), ParoiVDF_TBLE_LRM::calculer_hyd_BiK(), Paroi_std_hyd_VEF::calculer_hyd_BiK(), ParoiVEF_TBLE::calculer_hyd_BiK(), LoiParoiHybride::calculer_hyd_BiK(), Paroi_std_hyd_VDF::calculer_moyennes_parois(), Operateur_base::calculer_pour_post(), Op_Conv_PolyMAC_iterateur_base::calculer_pour_post(), Op_Conv_VDF_base::calculer_pour_post(), Op_Conv_VEF_base::calculer_pour_post(), Source_Transport_Fluctuation_Temperature_VDF_Elem::calculer_Prod_uteta_T(), Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::calculer_Prod_uteta_T(), Source_Transport_Fluctuation_Temperature_W_VDF_Elem::calculer_Prod_uteta_T(), Paroi_std_scal_hyd_EF::calculer_scal(), Loi_Paroi_Nu_Impose_VDF::calculer_scal(), Paroi_loi_WW_scal_VDF::calculer_scal(), Paroi_ODVM_scal_VDF::calculer_scal(), Paroi_std_scal_hyd_VDF::calculer_scal(), Paroi_TBLE_scal_VDF::calculer_scal(), Loi_Paroi_Nu_Impose_VEF::calculer_scal(), Paroi_loi_WW_scal_VEF::calculer_scal(), Paroi_scal_analytique_VEF::calculer_scal(), Paroi_std_scal_hyd_VEF::calculer_scal(), ParoiVEF_TBLE_scal::calculer_scal(), Calcul_Production_K_VEF::calculer_terme_production_K(), Calcul_Production_K_VEF::calculer_terme_production_K_BiK(), Calcul_Production_K_VEF::calculer_terme_production_K_EASM(), Calcul_Production_K_VDF::calculer_u_conc(), Calcul_Production_K_VDF::calculer_u_teta(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_W_VDF_Elem::calculer_u_teta_W(), Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::calculer_u_teta_W(), Source_Transport_Fluctuation_Temperature_W_VDF_Elem::calculer_u_teta_W(), Domaine_ALE::calculer_vitesse(), Eq_rayo_semi_transp_VDF::completer(), Eq_rayo_semi_transp_VEF::completer(), Terme_Source_Canal_perio::completer(), Domaine_Cl_VDF::completer(), Terme_Source_Canal_perio::compute_heat_flux(), Paroi_std_hyd_VDF::compute_law_komega(), Paroi_scal_hyd_base_VDF::compute_nusselt(), Calcul_Production_K_VEF::compute_utheta_nbConsti_gt_1_nbCompo_eq_0(), Calcul_Production_K_VEF::compute_utheta_nbConsti_gt_1_nbCompo_eq_1(), Calcul_Production_K_VEF::compute_utheta_nbConsti_gt_1_nbCompo_gt_1(), Calcul_Production_K_VEF::compute_utheta_nbConsti_le_1_nbCompo_eq_0(), Calcul_Production_K_VEF::compute_utheta_nbConsti_le_1_nbCompo_eq_1(), Calcul_Production_K_VEF::compute_utheta_nbConsti_le_1_nbCompo_gt_1(), Op_Conv_Amont_old_VEF_Face::contribue_au_second_membre(), Op_Conv_VEF_Face::contribue_au_second_membre(), Op_Diff_VEF_Anisotrope_Face::contribue_au_second_membre(), Op_Diff_VEF_Face::contribue_au_second_membre(), Op_Diff_VEF_Face_Q1::contribue_au_second_membre(), Op_Dift_VEF_Face_Q1::contribuer_a_avec(), Op_Grad_PolyMAC_Face::contribuer_a_avec(), Op_Dift_VEF_Face::contribuer_au_second_membre(), Navier_Stokes_FT_Disc::correct_at_exit_bad_gradient(), Domaine_VDF::creer_elements_fictifs(), Champ_val_tot_sur_vol_VEF::eval_contrib_loc(), Champ_P1NC_implementation::filtrer_resu(), Paroi_hyd_base_EF::get_champ(), Turbulence_paroi_base::get_champ(), Champ_Generique_Tparoi_VEF::get_champ(), Op_Grad_VEF_P1B_Face::impr(), Op_EF_base::impr(), Op_VEF_Face::impr(), Op_Grad_EF::impr(), Op_Grad_VDF_Face::impr(), Loi_Paroi_Nu_Impose_VDF::imprimer_nusselt(), Loi_Paroi_Nu_Impose_VEF::imprimer_nusselt(), Paroi_scal_hyd_base_VDF::imprimer_nusselt(), Paroi_std_hyd_EF::imprimer_ustar(), Paroi_std_hyd_VDF::imprimer_ustar(), Paroi_std_hyd_VEF::imprimer_ustar(), Paroi_2couches_VDF::imprimer_ustar(), Traitement_particulier_NS_chmoy_faceperio_VEF::init_calcul_stats(), ParoiVDF_TBLE::init_lois_paroi(), ParoiVDF_TBLE_LRM::init_lois_paroi(), Paroi_ODVM_scal_VDF::init_lois_paroi(), Paroi_TBLE_scal_VDF::init_lois_paroi(), ParoiVEF_TBLE::init_lois_paroi(), ParoiVEF_TBLE_scal::init_lois_paroi(), Paroi_scal_hyd_base_VDF::init_lois_paroi(), Paroi_TBLE_QDM::init_lois_paroi(), Paroi_TBLE_QDM_Scal::init_lois_paroi(), Op_Diff_VDF_base::init_op_ext(), Op_Diff_VEFP1NCP1B_Face::isFaceOfSymetry(), Domaine_ALE::laplacien(), Op_Diff_VEFP1NCP1B_Face::liste_face(), T_paroi_Champ_P0_VDF::me_calculer(), T_paroi_Champ_P1NC::me_calculer(), Domaine_ALE::mettre_a_jour(), Op_VEF_Face::modifier_matrice_pour_periodique_apres_contribuer(), rang_frontiere(), Op_Conv_VEF_Face::remplir_fluent(), Operateur_Conv_sensibility_VEF::remplir_fluent(), Op_Dift_EF_Q1::remplir_marqueur_elem_CL_paroi(), Iterateur_Source_VEF_Face< _TYPE_ >::remplir_volumes_cl_dirichlet(), Paroi_TBLE_QDM::reprendre(), Paroi_TBLE_QDM_Scal::reprendre(), EDO_Pression_th_VDF_Gaz_Reel::resoudre(), Paroi_TBLE_QDM::sauvegarder(), Paroi_TBLE_QDM_Scal::sauvegarder(), and Op_Diff_VEFP1NCP1B_Face::test().
nombre_de_sous_domaines_dis()
int Domaine_dis_base::nombre_de_sous_domaines_dis () const
Sous_domaines_dis
References les_sous_domaines_dis, and TRUST_Vector< _CLASSE_ >::size().
Referenced by Op_Conv_EF_VEF_P1NC_Stab::completer(), and Perte_Charge_VEF::completer().
sous_domaine_dis() [1/2]
const Sous_domaine_dis_base & Domaine_dis_base::sous_domaine_dis (int i) const
References les_sous_domaines_dis.
Referenced by Op_Conv_EF_VEF_P1NC_Stab::completer(), and Perte_Charge_VEF::completer().
sous_domaine_dis() [2/2]
Sous_domaine_dis_base & Domaine_dis_base::sous_domaine_dis (int i)
References les_sous_domaines_dis.
ecrire_noms_bords()
void Domaine_dis_base::ecrire_noms_bords (Sortie & os) const
Ecriture des noms des bords sur un flot de sortie.
Bord and Frontiere
Parameters
(Sortie& os) un flot de sortie
References domaine(), and Domaine_32_64< _SIZE_ >::ecrire_noms_bords().
Referenced by Domaine_Cl_dis_base::readOn().
rang_frontiere() [1/2]
int Domaine_dis_base::rang_frontiere (const Nom & nom)
References domaine(), Process::exit(), frontiere_dis(), Frontiere_dis_base::le_nom(), Domaine_base::le_nom(), and nb_front_Cl().
Referenced by Champ_front_contact_VEF::calcul_coeff_amort(), frontiere_dis(), Champ_Generique_Extraction::get_champ(), Echange_contact_PolyMAC_P0::init_op(), Echange_contact_PolyMAC_P0P1NC::init_op(), Modele_turbulence_hyd_Longueur_Melange_VEF::lire_distance_paroi(), Modele_Lam_Bremhorst_VEF::lire_distance_paroi(), Champ_front_contact_VEF::remplir_connect_bords(), Champ_front_contact_VEF::remplir_elems_voisin_bord(), and Champ_front_contact_VEF::test_faces_coin().
rang_frontiere() [2/2]
int Domaine_dis_base::rang_frontiere (const Nom & nom) const
Renvoie le rang de la frontiere de Nom nom Renvoie -1 si aucune frontiere ne s'appelle nom.
Parameters
(Nom& nom) le nom de la frontiere dont cherche le rang
Returns
(int) le rang de la frontiere si elle existe -1 sinon
Exceptions
pas de frontiere de Nom nom trouvee
References domaine(), Process::exit(), frontiere_dis(), Frontiere_dis_base::le_nom(), Domaine_base::le_nom(), and nb_front_Cl().
frontiere_dis() [1/4]
const Frontiere_dis_base & Domaine_dis_base::frontiere_dis (const Nom & nom) const
Renvoie la frontiere de Nom nom.
(On indexe les frontiere avec leur nom)
Parameters
(Nom& nom) le nom de la frontiere a indexer
Returns
(Frontiere_dis_base&) la frontiere discretisee indexee
Exceptions
frontiere de nom inconnu leve par rang_frontiere(Nom&)
References frontiere_dis(), and rang_frontiere().
Referenced by Domaine_ALE::calculer_vitesse(), Eq_rayo_semi_transp_VDF::completer(), Eq_rayo_semi_transp_VEF::completer(), Champ_Generique_Extraction::completer(), Champ_front_calc::front_dis(), Champ_front_contact_VEF::front_dis(), frontiere_dis(), Champ_Generique_Extraction::get_champ(), Echange_contact_rayo_semi_transp_VDF::mettre_a_jour(), Champ_front_calc::mettre_a_jour(), Echange_contact_Rayo_transp_VDF::mettre_a_jour(), and rang_frontiere().
frontiere_dis() [2/4]
Frontiere_dis_base & Domaine_dis_base::frontiere_dis (const Nom & nom)
References frontiere_dis(), and rang_frontiere().
frontiere_dis() [3/4]
virtual Frontiere_dis_base & Domaine_dis_base::frontiere_dis (int) pure virtual
Implemented in Domaine_VF.
frontiere_dis() [4/4]
virtual const Frontiere_dis_base & Domaine_dis_base::frontiere_dis (int) const pure virtual
Implemented in Domaine_VF.
face_sommets() [1/2]
IntTab & Domaine_dis_base::face_sommets () virtual
Mappings
Reimplemented in Domaine_VF.
References Process::exit(), and Objet_U::que_suis_je().
face_sommets() [2/2]
const IntTab & Domaine_dis_base::face_sommets () const virtual
Reimplemented in Domaine_VF.
References Process::exit(), and Objet_U::que_suis_je().
face_voisins() [1/2]
IntTab & Domaine_dis_base::face_voisins () virtual
Reimplemented in Domaine_VF.
References Process::exit(), and Objet_U::que_suis_je().
Referenced by Transport_Interfaces_FT_Disc::calcul_vitesse(), Navier_Stokes_FT_Disc::calculer_dI_dt(), Navier_Stokes_FT_Disc::calculer_gradient_indicatrice(), Transport_Interfaces_FT_Disc::get_compute_indicatrice_faces(), T_paroi_Champ_P1NC::me_calculer(), Echange_contact_VDF_FT_Disc_solid::mettre_a_jour(), and Transport_Interfaces_FT_Disc::modifier_vpoint_pour_imposer_vit().
face_voisins() [2/2]
const IntTab & Domaine_dis_base::face_voisins () const virtual
Reimplemented in Domaine_VF.
References Process::exit(), and Objet_U::que_suis_je().
associer_domaine()
void Domaine_dis_base::associer_domaine (const Domaine & un_domaine)
Associe un Domaine a l'objet.
Various
Parameters
(Domaine& un_domaine) le domaine a associer au domaine discretise
References le_dom.
Referenced by Champ_Fonc_MED::creer(), Discretiser_domaine::interpreter_(), and Champ_Fonc_MED_Table_Temps::lire_donnees_champ().
discretiser_root()
void Domaine_dis_base::discretiser_root (const Nom & typ)
References build_map_mc_Cmesh(), Build_Map_to_Structured::BUILD_MAP_TO_STRUCTURED, TRUST_Vector< _CLASSE_ >::dimensionner(), discretiser(), discretiser_no_face(), Sous_Domaine_32_64< _SIZE_ >::domaine(), Objet_U::est_egal_a(), Process::exit(), le_dom, les_sous_domaines_dis, Domaine_32_64< _SIZE_ >::nb_ss_domaines(), Domaine_32_64< _SIZE_ >::ss_domaine(), Nom::suffix(), and typer_discretiser_ss_domaine().
discretiser()
virtual void Domaine_dis_base::discretiser () inline virtual
Reimplemented in Domaine_DG, Domaine_EF, Domaine_EF_axi, Domaine_Poly_base, Domaine_VF, Domaine_PolyMAC, Domaine_PolyMAC_P0, Domaine_PolyMAC_P0P1NC, Domaine_VDF, and Domaine_VEF.
Referenced by Domaine_VF::discretiser(), and discretiser_root().
build_map_mc_Cmesh()
virtual void Domaine_dis_base::build_map_mc_Cmesh (const bool with_faces) inline virtual
Reimplemented in Domaine_VF.
Referenced by discretiser_root().
discretiser_no_face()
virtual void Domaine_dis_base::discretiser_no_face () pure virtual
Implemented in Domaine_VF.
Referenced by discretiser_root().
typer_discretiser_ss_domaine()
virtual void Domaine_dis_base::typer_discretiser_ss_domaine (int i) pure virtual
Implemented in Domaine_VF.
Referenced by discretiser_root().
modifier_pour_Cl()
virtual void Domaine_dis_base::modifier_pour_Cl (const Conds_lim &) pure virtual
Implemented in Domaine_EF, Domaine_Poly_base, Domaine_VF, Domaine_PolyMAC, Domaine_VEF, and Domaine_VDF.
Referenced by Probleme_base::preparer_calcul().
creer_elements_fictifs()
void Domaine_dis_base::creer_elements_fictifs (const Domaine_Cl_dis_base &) virtual
Reimplemented in Domaine_VDF.
References Process::exit(), and Objet_U::que_suis_je().
y_elem()
virtual const DoubleTab & Domaine_dis_base::y_elem () const inline virtual
References y_elem_.
y_faces()
virtual const DoubleTab & Domaine_dis_base::y_faces () const inline virtual
References y_faces_.
init_dist_paroi_globale()
virtual void Domaine_dis_base::init_dist_paroi_globale (const Conds_lim & conds_lim) inline virtual
Reimplemented in Domaine_VF.
References Process::exit(), and Objet_U::que_suis_je().
volume_maille()
const Champ_Fonc_base & Domaine_dis_base::volume_maille () const inline
References volume_maille_.
Referenced by get_champ(), and has_champ().
mesh_numbering()
const Champ_Fonc_base & Domaine_dis_base::mesh_numbering () const inline
References mesh_numbering_.
Referenced by get_champ(), and has_champ().
get_noms_champs_postraitables()
void Domaine_dis_base::get_noms_champs_postraitables (Noms & nom, Option opt = NONE) const override virtual
Implements Champs_compris_interface.
References TRUST_Vector< _CLASSE_ >::add(), champs_compris_, Champs_compris_T< FIELD_TYPE >::liste_noms_compris(), and Objet_U::que_suis_je().
Referenced by Probleme_base::get_noms_champs_postraitables().
creer_champ() [1/2]
void Domaine_dis_base::creer_champ (const Motcle & motlu) inline override virtual
Implements Champs_compris_interface.
References Process::exit().
Referenced by Probleme_base::creer_champ().
creer_champ() [2/2]
void Domaine_dis_base::creer_champ (const Motcle & motlu, const Probleme_base & pb)
References Champs_compris_T< FIELD_TYPE >::ajoute_champ(), champs_compris_, Probleme_base::discretisation(), Probleme_base::domaine_dis(), Objet_U_ptr::est_nul(), Discretisation_base::mesh_numbering(), mesh_numbering_, Probleme_base::schema_temps(), Discretisation_base::volume_maille(), and volume_maille_.
get_champ()
const Champ_base & Domaine_dis_base::get_champ (const Motcle & un_nom) const override virtual
Implements Champs_compris_interface.
References Nom::getString(), mesh_numbering(), and volume_maille().
has_champ() [1/2]
bool Domaine_dis_base::has_champ (const Motcle & nom, TRUST_Ref< Champ_base * > & ref_champ) const override virtual
Implements Champs_compris_interface.
References mesh_numbering(), and volume_maille().
has_champ() [2/2]
bool Domaine_dis_base::has_champ (const Motcle & nom) const override virtual
Implements Champs_compris_interface.
Member Data Documentation
info_obj
const Type_info Domaine_dis_base::info_obj static
le_dom
TRUST_Ref< Domaine *> Domaine_dis_base::le_dom protected
Referenced by associer_domaine(), discretiser_root(), and domaine().
les_sous_domaines_dis
TRUST_Vector<TRUST_Deriv< Sous_domaine_dis_base > > Domaine_dis_base::les_sous_domaines_dis protected
Referenced by discretiser_root(), nombre_de_sous_domaines_dis(), sous_domaine_dis(), and Domaine_VF::typer_discretiser_ss_domaine().
dist_paroi_initialisee_
int Domaine_dis_base::dist_paroi_initialisee_ = 0 protected
Referenced by Domaine_VF::init_dist_paroi_globale().
y_elem_
DoubleTab Domaine_dis_base::y_elem_ protected
Referenced by Domaine_VF::init_dist_paroi_globale(), and y_elem().
y_faces_
DoubleTab Domaine_dis_base::y_faces_ protected
Referenced by Domaine_VF::init_dist_paroi_globale(), and y_faces().
champs_compris_
Champs_compris Domaine_dis_base::champs_compris_ protected
Referenced by creer_champ(), and get_noms_champs_postraitables().
volume_maille_
TRUST_Deriv< Champ_Fonc_base > Domaine_dis_base::volume_maille_ protected
Referenced by creer_champ(), and volume_maille().
mesh_numbering_
TRUST_Deriv< Champ_Fonc_base > Domaine_dis_base::mesh_numbering_ protected
Referenced by creer_champ(), and mesh_numbering().