TrioCFD: Prepro_IBM_Ponderation Class Reference
Prepro_IBM_Ponderation Class Reference
#include <Prepro_IBM_Ponderation.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Prepro_IBM_base
int lire_motcle_non_standard (const Motcle &, Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Prepro_IBM_Ponderation()
Prepro_IBM_Ponderation::Prepro_IBM_Ponderation ()
~Prepro_IBM_Ponderation()
Prepro_IBM_Ponderation::~Prepro_IBM_Ponderation ()
Member Function Documentation
cree_instance()
Objet_U * Prepro_IBM_Ponderation::cree_instance () static
taille_memoire()
unsigned Prepro_IBM_Ponderation::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Prepro_IBM_Ponderation::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Prepro_IBM_Ponderation::info () static
get_info()
const Type_info * Prepro_IBM_Ponderation::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Prepro_IBM_base.
self_cast() [1/2]
Prepro_IBM_Ponderation & Prepro_IBM_Ponderation::self_cast (Objet_U & r) static
self_cast() [2/2]
const Prepro_IBM_Ponderation & Prepro_IBM_Ponderation::self_cast (const Objet_U & r) static
printOn()
Sortie & Prepro_IBM_Ponderation::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Prepro_IBM_base.
References Prepro_IBM_base::printOn().
readOn()
Entree & Prepro_IBM_Ponderation::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Prepro_IBM_base.
References Process::exit(), Param::lire_avec_accolades_depuis(), Objet_U::que_suis_je(), and Prepro_IBM_base::readOn().
Friends And Related Function Documentation
Source_PDF_EF
friend class Source_PDF_EF friend
Member Data Documentation
info_obj
const Type_info Prepro_IBM_Ponderation::info_obj static