TrioCFD: Mod_echelle_cv_naturelle Class Reference
Mod_echelle_cv_naturelle Class Reference
#include <Mod_echelle_cv_naturelle.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Mod_echelle_LRM_base
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Mod_echelle_LRM_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Mod_echelle_cv_naturelle()
Mod_echelle_cv_naturelle::Mod_echelle_cv_naturelle ()
~Mod_echelle_cv_naturelle()
Mod_echelle_cv_naturelle::~Mod_echelle_cv_naturelle ()
Member Function Documentation
cree_instance()
Objet_U * Mod_echelle_cv_naturelle::cree_instance () static
taille_memoire()
unsigned Mod_echelle_cv_naturelle::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Mod_echelle_cv_naturelle::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Mod_echelle_cv_naturelle::info () static
get_info()
const Type_info * Mod_echelle_cv_naturelle::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
Mod_echelle_cv_naturelle & Mod_echelle_cv_naturelle::self_cast (Objet_U & r) static
self_cast() [2/2]
const Mod_echelle_cv_naturelle & Mod_echelle_cv_naturelle::self_cast (const Objet_U & r) static
printOn()
Sortie & Mod_echelle_cv_naturelle::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
References Objet_U::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Mod_echelle_cv_naturelle::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
calculer_l_eps()
double Mod_echelle_cv_naturelle::calculer_l_eps (double y, double k, double u, double visco_cin) override virtual
Implements Mod_echelle_LRM_base.
References calculer_vv_bar().
calculer_l_mu()
double Mod_echelle_cv_naturelle::calculer_l_mu (double y, double k, double u, double visco_cin) override virtual
Implements Mod_echelle_LRM_base.
References calculer_vv_bar().
calculer_vv_bar()
double Mod_echelle_cv_naturelle::calculer_vv_bar (double y, double k, double u, double visco_cin) override virtual
Implements Mod_echelle_LRM_base.
Referenced by calculer_l_eps(), and calculer_l_mu().
Member Data Documentation
info_obj
const Type_info Mod_echelle_cv_naturelle::info_obj static