TrioCFD: Loi_2couches_base Class Reference
Loi_2couches_base Class Reference abstract
#include <Loi_2couches_base.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Loi_2couches_base()
Loi_2couches_base::Loi_2couches_base ()
~Loi_2couches_base()
Loi_2couches_base::~Loi_2couches_base () override
Member Function Documentation
info()
const Type_info * Loi_2couches_base::info () static
get_info()
const Type_info * Loi_2couches_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
Reimplemented in Loi_convforcee, Loi_convnat, and Loi_perso.
self_cast() [1/2]
Loi_2couches_base & Loi_2couches_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Loi_2couches_base & Loi_2couches_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Loi_2couches_base::printOn (Sortie & s) const override protected virtual
Imprime le type de l'equation sur un flot de sortie.
Parameters
(Sortie& s) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Objet_U.
Reimplemented in Loi_convforcee, Loi_convnat, and Loi_perso.
References Objet_U::que_suis_je().
readOn()
Entree & Loi_2couches_base::readOn (Entree & s) override protected virtual
Lit les specifications d'une equation de transport K-epsilon a partir d'un flot d'entree.
Controle dynamique du type du terme source.
Parameters
(Entree& s) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Objet_U.
Reimplemented in Loi_convforcee, Loi_convnat, and Loi_perso.
LepsLmu()
virtual void Loi_2couches_base::LepsLmu (double k, double nu, double dist, double y_etoile, double & Leps, double & Lmu, double & vvSqRt) pure virtual
Implemented in Loi_convforcee, Loi_convnat, and Loi_perso.
Referenced by Source_Transport_K_KEps_VDF_Elem::ajouter_blocs(), and Paroi_2couches_VDF::calculer_hyd().
Member Data Documentation
info_obj
const Type_info Loi_2couches_base::info_obj static