TrioCFD: Ecrire_fichier_xyz_valeur Class Reference
Ecrire_fichier_xyz_valeur Class Reference
#include <Ecrire_fichier_xyz_valeur.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Ecrire_fichier_xyz_valeur()
Ecrire_fichier_xyz_valeur::Ecrire_fichier_xyz_valeur ()
~Ecrire_fichier_xyz_valeur()
Ecrire_fichier_xyz_valeur::~Ecrire_fichier_xyz_valeur ()
Member Function Documentation
cree_instance()
Objet_U * Ecrire_fichier_xyz_valeur::cree_instance () static
taille_memoire()
unsigned Ecrire_fichier_xyz_valeur::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Ecrire_fichier_xyz_valeur::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Ecrire_fichier_xyz_valeur::info () static
get_info()
const Type_info * Ecrire_fichier_xyz_valeur::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
Ecrire_fichier_xyz_valeur & Ecrire_fichier_xyz_valeur::self_cast (Objet_U & r) static
self_cast() [2/2]
const Ecrire_fichier_xyz_valeur & Ecrire_fichier_xyz_valeur::self_cast (const Objet_U & r) static
printOn()
Sortie & Ecrire_fichier_xyz_valeur::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
readOn()
Entree & Ecrire_fichier_xyz_valeur::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
References Param::lire_avec_accolades_depuis(), Objet_U::que_suis_je(), and set_param().
set_param()
void Ecrire_fichier_xyz_valeur::set_param (Param & param)
References Param::ajouter(), and Param::ajouter_flag().
Referenced by readOn().
write_fields()
void Ecrire_fichier_xyz_valeur::write_fields () const
References Faces_32_64< _SIZE_ >::calculer_centres_gravite(), Operateur_Statistique_tps_base::calculer_valeurs(), TRUST_Ref< _CLASSE_ >::est_nul(), Process::exit(), Frontiere_32_64< _SIZE_ >::faces(), Frontiere_dis_base::frontiere(), Cond_lim_base::frontiere_dis(), Nom::getString(), Frontiere_32_64< _SIZE_ >::le_nom(), Nom::majuscule(), Field_base::nb_comp(), Frontiere_32_64< _SIZE_ >::nb_faces(), TRUST_Vector< _CLASSE_ >::size(), Champ_base::valeur_aux(), and Champ_Proto::valeurs().
Referenced by Equation_base::imprimer().
associer_eqn()
void Ecrire_fichier_xyz_valeur::associer_eqn (const Equation_base & eqn) inline
Referenced by Equation_base::lire_motcle_non_standard().
Member Data Documentation
info_obj
const Type_info Ecrire_fichier_xyz_valeur::info_obj static