TrioCFD: Echange_contact_VDF_FT_Disc Class Reference
Echange_contact_VDF_FT_Disc Class Reference
#include <Echange_contact_VDF_FT_Disc.h>
Public Member Functions
const Type_info * get_info () const override
int initialiser (double temps) override
void mettre_a_jour (double) override
const Type_info * get_info () const override
int initialiser (double temps) override
void mettre_a_jour (double) override
Public Member Functions inherited from Echange_global_impose
int compatible_avec_discr (const Discretisation_base &discr) const override
const Type_info * get_info () const override
int initialiser (double temps) override
void mettre_a_jour (double temps) override
Public Member Functions inherited from Echange_impose_base
int a_mettre_a_jour_ss_pas_dt () override
void associer_fr_dis_base (const Frontiere_dis_base &) override
double emissivite (int num) const
double emissivite (int num, int k) const
const Type_info * get_info () const override
virtual double h_imp (int num) const
virtual double h_imp (int num, int k) const
int initialiser (double temps) override
void mettre_a_jour (double) override
virtual Champ_front_base & T_ext ()
virtual double T_ext (int num) const
virtual double T_ext (int num, int k) const
Public Member Functions inherited from Cond_lim_base
virtual int a_mettre_a_jour_ss_pas_dt ()
virtual void associer_domaine_cl_dis_base (const Domaine_Cl_dis_base &)
virtual void associer_fr_dis_base (const Frontiere_dis_base &)
virtual void calculer_coeffs_echange (double temps)
virtual int compatible_avec_discr (const Discretisation_base &) const
Domaine_Cl_dis_base & domaine_Cl_dis ()
const Domaine_Cl_dis_base & domaine_Cl_dis () const
virtual Frontiere_dis_base & frontiere_dis ()
virtual const Frontiere_dis_base & frontiere_dis () const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
void set_modifier_val_imp (int)
virtual void verifie_ch_init_nb_comp () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Cond_lim_base
void err_pas_compatible (const Discretisation_base &) const
void err_pas_compatible (const Equation_base &) const
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
Constructor & Destructor Documentation
Echange_contact_VDF_FT_Disc()
Echange_contact_VDF_FT_Disc::Echange_contact_VDF_FT_Disc ()
~Echange_contact_VDF_FT_Disc()
Echange_contact_VDF_FT_Disc::~Echange_contact_VDF_FT_Disc ()
Member Function Documentation
cree_instance()
Objet_U * Echange_contact_VDF_FT_Disc::cree_instance () static
taille_memoire()
unsigned Echange_contact_VDF_FT_Disc::taille_memoire () const override virtual
Reimplemented from Echange_contact_VDF.
Reimplemented in Echange_contact_VDF_FT_Disc_solid.
duplique()
int Echange_contact_VDF_FT_Disc::duplique () const override virtual
Reimplemented from Echange_contact_VDF.
Reimplemented in Echange_contact_VDF_FT_Disc_solid.
info()
const Type_info * Echange_contact_VDF_FT_Disc::info () static
get_info()
const Type_info * Echange_contact_VDF_FT_Disc::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Echange_contact_VDF.
Reimplemented in Echange_contact_VDF_FT_Disc_solid.
self_cast() [1/2]
Echange_contact_VDF_FT_Disc & Echange_contact_VDF_FT_Disc::self_cast (Objet_U & r) static
self_cast() [2/2]
const Echange_contact_VDF_FT_Disc & Echange_contact_VDF_FT_Disc::self_cast (const Objet_U & r) static
printOn()
Sortie & Echange_contact_VDF_FT_Disc::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Echange_contact_VDF.
Reimplemented in Echange_contact_VDF_FT_Disc_solid.
References Echange_contact_VDF::printOn().
Referenced by Echange_contact_VDF_FT_Disc_solid::printOn().
readOn()
Entree & Echange_contact_VDF_FT_Disc::readOn (Entree & s) override protected virtual
Simple appel a Echange_impose_base::readOn(Entree&) Lit les specifications des conditions aux limites.
a partir d'un flot d'entree.
Parameters
(Entree& s) un flot d'entree
Returns
(Entree&) le flot de sortie modifie
Reimplemented from Echange_contact_VDF.
Reimplemented in Echange_contact_VDF_FT_Disc_solid.
References Param::ajouter(), Cond_lim_base::app_domains, Field_base::fixer_nb_comp(), Echange_contact_VDF::h_paroi, indicatrice_ref_, Cond_lim_base::le_champ_front, Param::lire_avec_accolades(), Echange_contact_VDF::nom_autre_pb_, Echange_contact_VDF::nom_bord, nom_bord_oppose_, Echange_contact_VDF::nom_champ, nom_champ_indicatrice_, Param::REQUIRED, Echange_contact_VDF::T_autre_pb_, Echange_impose_base::T_ext(), and Objet_U_ptr::typer().
mettre_a_jour()
void Echange_contact_VDF_FT_Disc::mettre_a_jour (double temps) override virtual
Effectue une mise a jour en temps de la condition aux limites.
Parameters
(double temps) le pas de temps de mise a jour
Reimplemented from Echange_contact_VDF.
Reimplemented in Echange_contact_VDF_FT_Disc_solid.
References Echange_contact_VDF::autre_h, Echange_contact_VDF::calculer_h_autre_pb(), Echange_contact_VDF::calculer_h_mon_pb(), Echange_contact_VDF::calculer_Teta_equiv(), Echange_contact_VDF::calculer_Teta_paroi(), Milieu_base::conductivite(), TRUSTVect< _TYPE_, _SIZE_ >::detach_vect(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Process::exit(), Domaine_VF::face_surfaces(), Domaine_VF::face_voisins(), Frontiere_dis_base::frontiere(), Cond_lim_base::frontiere_dis(), Echange_impose_base::h_imp_, indicatrice_, indicatrice_ref_, TRUST_Ref< _CLASSE_ >::le_nom(), Champ_front_base::mettre_a_jour(), Echange_global_impose::mettre_a_jour(), Champ_front_calc::milieu(), Cond_lim_base::mon_dom_cl_dis, Process::mp_max(), Process::mp_sum(), Field_base::nb_comp(), Frontiere_32_64< _SIZE_ >::num_premiere_face(), Interprete::objet(), Echange_global_impose::phi_ext_, Triple_Line_Model_FT_Disc::Q(), Triple_Line_Model_FT_Disc::Rc_inject(), Triple_Line_Model_FT_Disc::ready_inject_tcl(), Triple_Line_Model_FT_Disc::reinjection_tcl(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), Echange_contact_VDF::T_autre_pb(), Echange_impose_base::T_ext(), Probleme_FT_Disc_gen::tcl(), Triple_Line_Model_FT_Disc::tempC_tcl(), Ti_wall_, Champ_front_base::valeurs(), Champ_front_base::valeurs_au_temps(), and Domaine_VF::xv().
initialiser()
int Echange_contact_VDF_FT_Disc::initialiser (double temps) override virtual
Initialisation en debut de calcul.
A appeler avant tout calculer_coeffs_echange ou mettre_a_jour Contrairementaux methodes mettre_a_jour, les methodes initialiser des CLs ne peuvent pas dependre de l'exterieur (lui-meme peut ne pas etre initialise)
Returns
(0 en cas d'erreur, 1 sinon.)
Reimplemented from Echange_contact_VDF.
Reimplemented in Echange_contact_VDF_FT_Disc_solid.
References Echange_contact_VDF::calculer_h_autre_pb(), Echange_contact_VDF::calculer_h_mon_pb(), Echange_contact_VDF::calculer_Teta_paroi(), TRUSTVect< _TYPE_, _SIZE_ >::detach_vect(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Cond_lim_base::domaine_Cl_dis(), indicatrice_, Echange_contact_VDF::initialiser(), Champ_front_calc::initialiser(), Ti_wall_, TRUST_Deriv< _CLASSE_ >::valeur(), and Champ_front_base::valeurs().
Referenced by Echange_contact_VDF_FT_Disc_solid::initialiser().
completer()
void Echange_contact_VDF_FT_Disc::completer () override virtual
NE FAIT RIEN A surcharger dans les classes derivees.
Reimplemented from Echange_contact_VDF.
Reimplemented in Echange_contact_VDF_FT_Disc_solid.
References Champ_front_base::associer_fr_dis_base(), Champ_front_base::completer(), Echange_contact_VDF::completer(), Champ_front_calc::creer(), Echange_global_impose::derivee_phi_ext_, Cond_lim_base::domaine_Cl_dis(), MorEqn::equation(), Field_base::fixer_nb_comp(), Echange_impose_base::fixer_nb_valeurs_temporelles(), Champ_front_var_instationnaire::fixer_nb_valeurs_temporelles(), Frontiere_dis_base::frontiere(), Cond_lim_base::frontiere_dis(), indicatrice_, Triple_Line_Model_FT_Disc::is_activated(), TRUST_Ref< _CLASSE_ >::le_nom(), Frontiere_32_64< _SIZE_ >::le_nom(), Cond_lim_base::mon_dom_cl_dis, Frontiere_32_64< _SIZE_ >::nb_faces(), Schema_Temps_base::nb_valeurs_temporelles(), Echange_contact_VDF::nom_autre_pb_, nom_bord_oppose_, nom_champ_indicatrice_, Interprete::objet(), Echange_global_impose::phi_ext_, Echange_global_impose::phi_ext_lu_, TRUSTTab< _TYPE_, _SIZE_ >::resize(), Equation_base::schema_temps(), Champ_front_calc::set_distant(), Echange_impose_base::T_ext(), Probleme_FT_Disc_gen::tcl(), Ti_wall_, Objet_U_ptr::typer(), TRUST_Deriv< _CLASSE_ >::valeur(), and Champ_front_base::valeurs().
Referenced by Echange_contact_VDF_FT_Disc_solid::completer().
Ti_wall()
double Echange_contact_VDF_FT_Disc::Ti_wall (int num) const virtual
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Process::exit(), TRUSTVect< _TYPE_, _SIZE_ >::size(), Ti_wall_, and Champ_front_base::valeurs().
Referenced by Convection_Diffusion_Temperature_FT_Disc::get_flux_and_Twall(), Triple_Line_Model_FT_Disc::get_theta_app(), and Echange_contact_VDF_FT_Disc_solid::mettre_a_jour().
changer_temps_futur()
void Echange_contact_VDF_FT_Disc::changer_temps_futur (double temps, int i) override virtual
Change le i-eme temps futur de la CL.
Reimplemented from Echange_contact_VDF.
Reimplemented in Echange_contact_VDF_FT_Disc_solid.
References Champ_front_base::changer_temps_futur(), changer_temps_futur(), Echange_contact_VDF::changer_temps_futur(), indicatrice_, and Ti_wall_.
Referenced by changer_temps_futur(), and Echange_contact_VDF_FT_Disc_solid::changer_temps_futur().
avancer()
int Echange_contact_VDF_FT_Disc::avancer (double temps) override virtual
Tourne la roue de la CL.
Reimplemented from Echange_contact_VDF.
Reimplemented in Echange_contact_VDF_FT_Disc_solid.
References Champ_front_base::avancer(), avancer(), Echange_contact_VDF::avancer(), indicatrice_, and Ti_wall_.
Referenced by avancer(), and Echange_contact_VDF_FT_Disc_solid::avancer().
reculer()
int Echange_contact_VDF_FT_Disc::reculer (double temps) override virtual
Tourne la roue de la CL.
Reimplemented from Echange_contact_VDF.
Reimplemented in Echange_contact_VDF_FT_Disc_solid.
References indicatrice_, Champ_front_base::reculer(), reculer(), Echange_contact_VDF::reculer(), and Ti_wall_.
Referenced by reculer(), and Echange_contact_VDF_FT_Disc_solid::reculer().
set_temps_defaut()
void Echange_contact_VDF_FT_Disc::set_temps_defaut (double temps) override virtual
Change le i-eme temps futur de la cl.
Reimplemented from Echange_global_impose.
References indicatrice_, Objet_U_ptr::non_nul(), Champ_front_base::set_temps_defaut(), Echange_global_impose::set_temps_defaut(), and Ti_wall_.
Member Data Documentation
info_obj
const Type_info Echange_contact_VDF_FT_Disc::info_obj static
indicatrice_
TRUST_Deriv< Champ_front_base > Echange_contact_VDF_FT_Disc::indicatrice_ protected
Referenced by avancer(), changer_temps_futur(), completer(), initialiser(), mettre_a_jour(), Echange_contact_VDF_FT_Disc_solid::mettre_a_jour(), reculer(), and set_temps_defaut().
Ti_wall_
TRUST_Deriv< Champ_front_base > Echange_contact_VDF_FT_Disc::Ti_wall_ protected
Referenced by avancer(), changer_temps_futur(), completer(), initialiser(), mettre_a_jour(), Echange_contact_VDF_FT_Disc_solid::mettre_a_jour(), reculer(), set_temps_defaut(), and Ti_wall().
indicatrice_ref_
double Echange_contact_VDF_FT_Disc::indicatrice_ref_ protected
Referenced by mettre_a_jour(), and readOn().
nom_champ_indicatrice_
Nom Echange_contact_VDF_FT_Disc::nom_champ_indicatrice_ protected
Referenced by completer(), readOn(), and Echange_contact_VDF_FT_Disc_solid::readOn().
nom_bord_oppose_
Nom Echange_contact_VDF_FT_Disc::nom_bord_oppose_ protected
Referenced by completer(), Echange_contact_VDF_FT_Disc_solid::completer(), readOn(), and Echange_contact_VDF_FT_Disc_solid::readOn().