TrioCFD: IJK_Finite_Difference_One_Dimensional_Matrix_Assembler Class Reference
IJK_Finite_Difference_One_Dimensional_Matrix_Assembler Class Reference
#include <IJK_Finite_Difference_One_Dimensional_Matrix_Assembler.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Member Enumeration Documentation
Fd_coefficient_type_
enum IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::Fd_coefficient_type_ protected
Enumerator
identity
forward
centred
backward
Precision_Order_
enum IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::Precision_Order_ protected
Enumerator
first_order
second_order
Derivative_Order_
enum IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::Derivative_Order_ protected
Enumerator
first
second
Boundary_conditions
enum IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::Boundary_conditions protected
Enumerator
default_bc
dirichlet
neumann
flux_jump
implicit
Remove_zero_coeff
enum IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::Remove_zero_coeff protected
Enumerator
keep_zeros
remove_zeros
remove_close_zeros
Equation_type
enum IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::Equation_type protected
Enumerator
advection_diffusion
linear_diffusion
Constructor & Destructor Documentation
IJK_Finite_Difference_One_Dimensional_Matrix_Assembler()
IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::IJK_Finite_Difference_One_Dimensional_Matrix_Assembler ()
References first_order_derivative_backward_, first_order_derivative_backward_vector_, first_order_derivative_centred_, first_order_derivative_centred_vector_, first_order_derivative_forward_, first_order_derivative_forward_vector_, identity_coefficient_, second_order_derivative_backward_, second_order_derivative_backward_vector_, second_order_derivative_centred_, second_order_derivative_centred_vector_, second_order_derivative_forward_, second_order_derivative_forward_vector_, and set_operators_indices().
~IJK_Finite_Difference_One_Dimensional_Matrix_Assembler()
IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::~IJK_Finite_Difference_One_Dimensional_Matrix_Assembler ()
Member Function Documentation
cree_instance()
Objet_U * IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::cree_instance () static
taille_memoire()
unsigned IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::info () static
get_info()
const Type_info * IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
IJK_Finite_Difference_One_Dimensional_Matrix_Assembler & IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::self_cast (Objet_U & r) static
self_cast() [2/2]
const IJK_Finite_Difference_One_Dimensional_Matrix_Assembler & IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::self_cast (const Objet_U & r) static
printOn()
Sortie & IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
References precision_order_, and reduce_side_precision_.
Referenced by readOn().
readOn()
Entree & IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
References Param::lire_avec_accolades(), printOn(), Objet_U::que_suis_je(), and set_param().
set_param()
void IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::set_param (Param & param)
References Param::ajouter(), Param::ajouter_flag(), precision_order_, and reduce_side_precision_.
Referenced by readOn().
build()
int IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::build (Matrice & matrix, const int & nb_elem, const int & derivative_order)
References build_with_known_pattern(), build_with_unknown_pattern(), and known_pattern_.
Referenced by IJK_Thermal_Subresolution::compute_first_order_operator_raw(), IJK_Thermal_Subresolution::compute_overall_probes_parameters(), and IJK_Thermal_Subresolution::compute_second_order_operator_raw().
build_with_unknown_pattern()
int IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::build_with_unknown_pattern (Matrice & matrix, const int & nb_elem, const int & derivative_order)
References Matrice_Morse::compacte(), Matrice_Morse::dimensionner(), first, first_order_derivative_backward_, first_order_derivative_centred_, first_order_derivative_forward_, Matrice_Morse::get_set_coeff(), Matrice_Morse::get_set_tab1(), Matrice_Morse::get_set_tab2(), identity, identity_coefficient_, non_zero_stencil_values(), precision_order_, remove_zeros, second, second_order_derivative_backward_, second_order_derivative_centred_, second_order_derivative_forward_, TRUSTVect< _TYPE_, _SIZE_ >::size(), Objet_U_ptr::typer(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by build().
build_with_known_pattern()
int IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::build_with_known_pattern (Matrice & matrix, const int & nb_elem, const int & derivative_order)
References backward_left_offset_, backward_right_offset_, centred_left_offset_, centred_right_offset_, compute_stencil_properties(), Matrice_Morse::dimensionner(), first, first_order_derivative_backward_, first_order_derivative_centred_, first_order_derivative_forward_, forward_left_offset_, forward_right_offset_, Matrice_Morse::get_set_coeff(), Matrice_Morse::get_set_tab1(), Matrice_Morse::get_set_tab2(), identity, identity_coefficient_, non_zero_elem_, precision_order_, second, second_order_derivative_backward_, second_order_derivative_centred_, second_order_derivative_forward_, Objet_U_ptr::typer(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by build().
modify_rhs_for_bc()
void IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::modify_rhs_for_bc (Matrice & modified_matrix, DoubleVect & modified_rhs, const int & ini_boundary_conditions, const int & end_boundary_conditions)
References Matrice_Morse::compacte(), default_bc, dirichlet, flux_jump, Matrice_Morse::get_set_coeff(), Matrice_Morse::get_set_tab1(), Matrice_Morse::get_set_tab2(), known_pattern_, Matrice_Base::multvect(), Matrice_Morse::nb_colonnes(), Matrice_Morse::nb_lignes(), neumann, remove_zeros, TRUSTVect< _TYPE_, _SIZE_ >::size(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by impose_boundary_conditions().
scale_matrix_by_vector()
void IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::scale_matrix_by_vector (Matrice & matrix, const DoubleVect & vector, const int & boundary_conditions)
References Matrice_Morse::compacte(), known_pattern_, remove_zeros, TRUSTVect< _TYPE_, _SIZE_ >::size(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by scale_matrix_subproblem_by_vector().
scale_matrix_subproblem_by_vector()
void IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::scale_matrix_subproblem_by_vector (Matrice * matrix, const DoubleVect & vector, const int & subproblem_index, const int & boundary_conditions, const int & use_sparse_matrix, const FixedVector< ArrOfInt, 6 > * first_indices_sparse_matrix)
References Matrice_Bloc::get_bloc(), make_operation_on_sub_matrix_sparse(), recombined_local_sub_matrix_with_matrix(), and scale_matrix_by_vector().
make_operation_on_sub_matrix_sparse()
void IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::make_operation_on_sub_matrix_sparse (Matrice & local_sub_matrix, Matrice * matrix, const int & subproblem_index, const FixedVector< ArrOfInt, 6 > * first_indices_sparse_matrix)
References Matrice_Morse::dimensionner(), Matrice_Morse::get_coeff(), Matrice_Morse::get_set_coeff(), Matrice_Morse::get_set_tab1(), Matrice_Morse::get_set_tab2(), Matrice_Morse::get_tab1(), Matrice_Morse::get_tab2(), Objet_U_ptr::typer(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by impose_boundary_conditions_subproblem(), and scale_matrix_subproblem_by_vector().
recombined_local_sub_matrix_with_matrix()
void IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::recombined_local_sub_matrix_with_matrix (Matrice & local_sub_matrix, Matrice * matrix, const int & subproblem_index, const FixedVector< ArrOfInt, 6 > * first_indices_sparse_matrix)
References Matrice_Morse::get_coeff(), Matrice_Morse::get_set_coeff(), Matrice_Morse::get_set_tab1(), Matrice_Morse::get_set_tab2(), Matrice_Morse::get_tab1(), Matrice_Morse::get_tab2(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by impose_boundary_conditions_subproblem(), and scale_matrix_subproblem_by_vector().
impose_boundary_conditions()
void IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::impose_boundary_conditions (Matrice & modified_matrix, DoubleVect & mdified_rhs, const int & ini_boundary_conditions, const double & interfacial_value, const int & end_boundary_conditions, const double & end_values, const double & dr_inv, const int & first_time_step_temporal, const int & first_time_step_explicit, const DoubleVect & temperature_ini_temporal_schemes)
References Matrice_Morse::compacte(), dirichlet, first_order_derivative_backward_, first_order_derivative_centred_, first_order_derivative_forward_, flux_jump, Matrice_Morse::get_set_coeff(), Matrice_Morse::get_set_tab1(), implicit, known_pattern_, modify_rhs_for_bc(), Matrice_Morse::nb_coeff(), Matrice_Morse::nb_lignes(), Matrice_Morse::nb_vois(), neumann, non_zero_stencil_values(), precision_order_, remove_zeros, TRUSTVect< _TYPE_, _SIZE_ >::size(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by impose_boundary_conditions_subproblem().
impose_boundary_conditions_subproblem()
void IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::impose_boundary_conditions_subproblem (Matrice * matrix, DoubleVect * global_rhs, DoubleVect & local_rhs, const int & ini_boundary_conditions, const double & interfacial_value, const int & end_boundary_conditions, const double & end_value, const int & subproblem_index, const double & dr_inv, const int & first_time_step_temporal, const int & first_time_step_explicit, const DoubleVect & temperature_ini_temporal_schemes, const int & start_index, const FixedVector< ArrOfInt, 6 > * first_indices_sparse_matrix, const int & use_sparse_matrix)
References Matrice_Bloc::get_bloc(), impose_boundary_conditions(), make_operation_on_sub_matrix_sparse(), recombined_local_sub_matrix_with_matrix(), and TRUSTVect< _TYPE_, _SIZE_ >::size().
sum_any_matrices_subproblems()
void IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::sum_any_matrices_subproblems (Matrice & matrix_A, Matrice & matrix_B, const int & use_sparse_matrix, const int & debug)
References sum_matrices_subproblems(), and sum_sparse_matrices_subproblems().
Referenced by IJK_Thermal_Subresolution::prepare_temporal_schemes().
sum_sparse_matrices_subproblems()
void IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::sum_sparse_matrices_subproblems (Matrice & matrix_A, Matrice & matrix_B, const int & debug)
References Matrice_Morse::get_tab1(), known_pattern_, TRUSTArray< _TYPE_, _SIZE_ >::size_array(), Matrice_Morse::sort_stencil(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by sum_any_matrices_subproblems().
sum_matrices_subproblems()
void IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::sum_matrices_subproblems (Matrice & matrix_A, Matrice & matrix_B)
References Matrice_Bloc::dim(), Matrice_Bloc::get_bloc(), known_pattern_, Matrice_Morse::sort_stencil(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by sum_any_matrices_subproblems().
sum_matrices()
void IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::sum_matrices (Matrice & matrix_A, Matrice & matrix_B)
References TRUST_Deriv< _CLASSE_ >::valeur().
initialise_sparse_matrix_subproblems()
void IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::initialise_sparse_matrix_subproblems (Matrice & matrix_subproblems, Matrice & fd_operator, const int & nb_subproblems, const int & first_time_step_varying_probes, FixedVector< ArrOfInt, 6 > & first_indices_sparse_matrix, const int & first_initialisation, int & initialise_sparse_indices)
References Matrice_Morse::dimensionner(), Matrice_Morse::get_coeff(), Matrice_Morse::get_set_coeff(), Matrice_Morse::get_set_tab1(), Matrice_Morse::get_set_tab2(), Matrice_Morse::get_tab1(), Matrice_Morse::get_tab2(), Matrice_Morse::nb_coeff(), Matrice_Morse::nb_colonnes(), Matrice_Morse::nb_lignes(), Objet_U_ptr::typer(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by IJK_Thermal_Subresolution::initialise_identity_matrices_sparse(), IJK_Thermal_Subresolution::initialise_radial_convection_operator_sparse(), and IJK_Thermal_Subresolution::initialise_radial_diffusion_operator_sparse().
initialise_matrix_subproblems()
void IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::initialise_matrix_subproblems (Matrice & matrix_subproblems, Matrice & fd_operator, const int & subproblems, const int & first_time_step_varying_probes)
References Matrice_Morse::compacte(), Matrice_Bloc::dimensionner(), Matrice_Morse::dimensionner(), Matrice_Bloc::get_bloc(), Matrice_Morse::nb_coeff(), Matrice_Morse::nb_colonnes(), Matrice_Morse::nb_lignes(), remove_zeros, Objet_U_ptr::typer(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by IJK_Thermal_Subresolution::initialise_identity_matrices(), IJK_Thermal_Subresolution::initialise_radial_convection_operator(), and IJK_Thermal_Subresolution::initialise_radial_diffusion_operator().
reinitialise_any_matrix_subproblem()
void IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::reinitialise_any_matrix_subproblem (Matrice * matrix_subproblems, const Matrice * fd_operator, const int & nb_subproblems, const int & use_sparse_matrix, FixedVector< ArrOfInt, 6 > * first_indices_sparse_matrix, const int & first_initialisation, const int & keep_global_probes_discretisation)
References reinitialise_matrix_subproblem(), and reinitialise_sparse_matrix_subproblem().
reinitialise_sparse_matrix_subproblem()
void IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::reinitialise_sparse_matrix_subproblem (Matrice * matrix_subproblems, const Matrice * fd_operator, const int & nb_subproblems, FixedVector< ArrOfInt, 6 > * first_indices_sparse_matrix, const int & first_initialisation, const int & keep_global_probes_discretisation)
References Matrice_Morse::dimensionner(), Matrice_Morse::get_coeff(), Matrice_Morse::get_set_coeff(), Matrice_Morse::get_set_tab1(), Matrice_Morse::get_set_tab2(), Matrice_Morse::get_tab1(), Matrice_Morse::get_tab2(), Matrice_Morse::nb_coeff(), Matrice_Morse::nb_colonnes(), and Matrice_Morse::nb_lignes().
Referenced by reinitialise_any_matrix_subproblem().
reinitialise_matrix_subproblem()
void IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::reinitialise_matrix_subproblem (Matrice * matrix_subproblems, const Matrice * fd_operator, const int & nb_subproblems, const int & keep_global_probes_discretisation)
References Matrice_Bloc::get_bloc(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by reinitialise_any_matrix_subproblem().
add_source_terms()
void IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::add_source_terms (DoubleVect * thermal_subproblems_rhs_assembly, DoubleVect & rhs_assembly, const DoubleVect & source_terms, const int & index_start, const int & boundary_condition_interface, const int & boundary_condition_end)
References dirichlet, flux_jump, implicit, neumann, and TRUSTVect< _TYPE_, _SIZE_ >::size().
compute_operator()
void IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::compute_operator (const Matrice * fd_operator, const DoubleVect & solution, DoubleVect & res)
References Matrice_Base::multvect().
apply_euler_time_step()
void IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::apply_euler_time_step (Matrice * convection_matrix, Matrice * diffusion_matrix, const int & subproblem_index, const double & local_time_step, const double & alpha)
References Matrice_Bloc::get_bloc().
correct_sign_temporal_schemes_subproblems()
void IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::correct_sign_temporal_schemes_subproblems (Matrice * convection_matrix, Matrice * diffusion_matrix, const int & subproblem_index, const double & local_time_step, const double & alpha)
References Matrice_Bloc::get_bloc().
pre_initialise_matrix_subproblems()
void IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::pre_initialise_matrix_subproblems (Matrice & matrice, Matrice & fd_operator, const int & max_subproblems_predicted)
References Matrice_Morse::compacte(), Matrice_Bloc::dimensionner(), Matrice_Morse::dimensionner(), Matrice_Bloc::get_bloc(), Matrice_Morse::nb_coeff(), Matrice_Morse::nb_colonnes(), Matrice_Morse::nb_lignes(), remove_zeros, Objet_U_ptr::typer(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by IJK_Thermal_Subresolution::pre_initialise_thermal_subproblems_matrices().
pre_initialise_sparse_matrix_subproblems()
void IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::pre_initialise_sparse_matrix_subproblems (Matrice & matrix_subproblems, Matrice & fd_operator, const int & max_subproblems_predicted)
References Matrice_Morse::dimensionner(), Matrice_Morse::nb_coeff(), Matrice_Morse::nb_colonnes(), Matrice_Morse::nb_lignes(), Objet_U_ptr::typer(), and TRUST_Deriv< _CLASSE_ >::valeur().
complete_empty_matrices_initialisation()
void IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::complete_empty_matrices_initialisation (Matrice & matrix_subproblems, Matrice & fd_operator, const int & empty_problem_start_index, const int & empty_problem_end_index)
References Matrice_Bloc::get_bloc(), Matrice_Morse::get_coeff(), Matrice_Morse::get_set_coeff(), Matrice_Morse::get_set_tab1(), Matrice_Morse::get_set_tab2(), Matrice_Morse::get_tab1(), Matrice_Morse::get_tab2(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by IJK_Thermal_Subresolution::pre_initialise_thermal_subproblems_matrices().
reduce_solver_matrix()
void IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::reduce_solver_matrix (const Matrice_Morse & thermal_subproblems_matrix_assembly_for_solver, Matrice_Morse & thermal_subproblems_matrix_assembly_for_solver_reduced, const int & nb_points, const int & pre_initialise_thermal_subproblems_list)
References Matrice_Morse::dimensionner(), Matrice_Morse::get_coeff(), Matrice_Morse::get_set_coeff(), Matrice_Morse::get_set_tab1(), Matrice_Morse::get_set_tab2(), Matrice_Morse::get_tab1(), Matrice_Morse::get_tab2(), and TRUSTVect< _TYPE_, _SIZE_ >::size().
Referenced by IJK_Thermal_Subresolution::convert_into_sparse_matrix().
set_operators_size()
void IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::set_operators_size (const std::vector< std::vector< double > > & fd_operator_vector, FixedVector< FixedVector< DoubleVect, 2 >, 4 > & fd_operator) protected
Referenced by set_operators_indices().
set_operators_indices()
void IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::set_operators_indices (const std::vector< std::vector< double > > & fd_operator_vector, FixedVector< FixedVector< DoubleVect, 2 >, 4 > & fd_operator, const int & fd_coefficient_type) protected
References backward, centred, forward, and set_operators_size().
Referenced by IJK_Finite_Difference_One_Dimensional_Matrix_Assembler().
non_zero_stencil_values()
int IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::non_zero_stencil_values (const FixedVector< FixedVector< DoubleVect, 2 >, 4 > & fd_operator) protected
References precision_order_.
Referenced by build_with_unknown_pattern(), and impose_boundary_conditions().
get_max_operators()
int IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::get_max_operators (const FixedVector< FixedVector< DoubleVect, 2 >, 4 > & fd_operator_conv, const FixedVector< FixedVector< DoubleVect, 2 >, 4 > & fd_operator_diff, int(&) stencil_left_offset[3], int(&) stencil_right_offset[3]) protected
References precision_order_.
Referenced by get_max_stencil().
get_max_stencil()
void IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::get_max_stencil (const int & nb_elem, int & non_zero_elem_max, int & stencil_forward_max, int & stencil_centred_max, int & stencil_backward_max) protected
References advection_diffusion, backward_left_offset_, backward_right_offset_, centred_left_offset_, centred_right_offset_, equation_type_, first_order_derivative_backward_, first_order_derivative_centred_, first_order_derivative_forward_, forward_left_offset_, forward_right_offset_, get_max_operators(), linear_diffusion, precision_order_, second_order_derivative_backward_, second_order_derivative_centred_, and second_order_derivative_forward_.
Referenced by compute_stencil_properties().
compute_stencil_properties()
void IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::compute_stencil_properties (const int nb_elem) protected
References computed_stencil_, get_max_stencil(), nb_elem_, non_zero_elem_, stencil_backward_max_, stencil_centred_max_, and stencil_forward_max_.
Referenced by build_with_known_pattern().
fill_lines()
void IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::fill_lines (Matrice & matrix) protected
Member Data Documentation
info_obj
const Type_info IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::info_obj static
identity_coefficient_
FixedVector<FixedVector<DoubleVect,2>, 4 > IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::identity_coefficient_ protected
Referenced by build_with_known_pattern(), build_with_unknown_pattern(), and IJK_Finite_Difference_One_Dimensional_Matrix_Assembler().
first_order_derivative_forward_vector_
const std::vector<std::vector<double> > IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::first_order_derivative_forward_vector_ protected
Initial value:
= {{-1., 1.},
    {-3./2., 2., -1./2.},
    {-11./6., 3., -3./2., 1./3.},
    {-25./12., 4., -3., 4./3., -1./4.}
  }
Referenced by IJK_Finite_Difference_One_Dimensional_Matrix_Assembler().
first_order_derivative_forward_
FixedVector<FixedVector<DoubleVect,2>, 4 > IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::first_order_derivative_forward_ protected
Referenced by build_with_known_pattern(), build_with_unknown_pattern(), get_max_stencil(), IJK_Finite_Difference_One_Dimensional_Matrix_Assembler(), and impose_boundary_conditions().
first_order_derivative_centred_vector_
const std::vector<std::vector<double> > IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::first_order_derivative_centred_vector_ protected
Initial value:
= {{-1./2., 0., 1./2.},
    {-1./2., 0., 1./2.},
    {1./12., -2./3., 0., 2./3., -1./12.},
    {1./12., -2./3., 0., 2./3., -1./12.}
  }
Referenced by IJK_Finite_Difference_One_Dimensional_Matrix_Assembler().
first_order_derivative_centred_
FixedVector<FixedVector<DoubleVect,2>, 4 > IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::first_order_derivative_centred_ protected
Referenced by build_with_known_pattern(), build_with_unknown_pattern(), get_max_stencil(), IJK_Finite_Difference_One_Dimensional_Matrix_Assembler(), and impose_boundary_conditions().
first_order_derivative_backward_vector_
const std::vector<std::vector<double> > IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::first_order_derivative_backward_vector_ protected
Initial value:
= {{1., -1.},
    {3./2., -2., 1./2.},
    {11./6., -3., 3./2., -1./3.},
    {25./12., -4., 3., -4./3., 1./4.}
  }
Referenced by IJK_Finite_Difference_One_Dimensional_Matrix_Assembler().
first_order_derivative_backward_
FixedVector<FixedVector<DoubleVect,2>, 4 > IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::first_order_derivative_backward_ protected
Referenced by build_with_known_pattern(), build_with_unknown_pattern(), get_max_stencil(), IJK_Finite_Difference_One_Dimensional_Matrix_Assembler(), and impose_boundary_conditions().
second_order_derivative_forward_vector_
const std::vector<std::vector<double> > IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::second_order_derivative_forward_vector_ protected
Initial value:
= {{1., -2., 1.},
    {2., -5., 4., -1.},
    {35./12., -26./3., 19./2., -14./3., 11./12.},
    {15./4., -77./6., 107./6., -13., 61./12., -5./6.}
  }
Referenced by IJK_Finite_Difference_One_Dimensional_Matrix_Assembler().
second_order_derivative_forward_
FixedVector<FixedVector<DoubleVect,2>, 4 > IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::second_order_derivative_forward_ protected
Referenced by build_with_known_pattern(), build_with_unknown_pattern(), get_max_stencil(), and IJK_Finite_Difference_One_Dimensional_Matrix_Assembler().
second_order_derivative_centred_vector_
const std::vector<std::vector<double> > IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::second_order_derivative_centred_vector_ protected
Initial value:
= {{1., -2., 1.},
    {1., -2., 1.},
    {-2., -1., 0., 1., 2.},
    {-2., -1., 0., 1., 2.}
  }
Referenced by IJK_Finite_Difference_One_Dimensional_Matrix_Assembler().
second_order_derivative_centred_
FixedVector<FixedVector<DoubleVect,2>, 4 > IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::second_order_derivative_centred_ protected
Referenced by build_with_known_pattern(), build_with_unknown_pattern(), get_max_stencil(), and IJK_Finite_Difference_One_Dimensional_Matrix_Assembler().
second_order_derivative_backward_vector_
const std::vector<std::vector<double> > IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::second_order_derivative_backward_vector_ protected
Initial value:
= {{1., -2., 1.},
    {-2., 5., -4., 1.},
    {35./12., -26./3., 19./2., -14./3., 11./12.},
    {15./4., -77./6., 107./6., -13., 61./12., -5./6.}
  }
Referenced by IJK_Finite_Difference_One_Dimensional_Matrix_Assembler().
second_order_derivative_backward_
FixedVector<FixedVector<DoubleVect,2>, 4 > IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::second_order_derivative_backward_ protected
Referenced by build_with_known_pattern(), build_with_unknown_pattern(), get_max_stencil(), and IJK_Finite_Difference_One_Dimensional_Matrix_Assembler().
precision_order_
int IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::precision_order_ = 2 protected
Referenced by build_with_known_pattern(), build_with_unknown_pattern(), get_max_operators(), get_max_stencil(), impose_boundary_conditions(), non_zero_stencil_values(), printOn(), and set_param().
reduce_side_precision_
int IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::reduce_side_precision_ = 0 protected
Referenced by printOn(), and set_param().
core_matrix_type_
int IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::core_matrix_type_ = centred protected
equation_type_
int IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::equation_type_ = advection_diffusion protected
Referenced by get_max_stencil().
nb_elem_
int IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::nb_elem_ = 0 protected
Referenced by compute_stencil_properties().
non_zero_elem_
int IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::non_zero_elem_ = 0 protected
Referenced by build_with_known_pattern(), and compute_stencil_properties().
stencil_forward_max_
int IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::stencil_forward_max_ = 0 protected
Referenced by compute_stencil_properties().
stencil_centred_max_
int IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::stencil_centred_max_ = 0 protected
Referenced by compute_stencil_properties().
stencil_backward_max_
int IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::stencil_backward_max_ = 0 protected
Referenced by compute_stencil_properties().
forward_left_offset_
int IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::forward_left_offset_[3] = {0, 0, 0} protected
Referenced by build_with_known_pattern(), and get_max_stencil().
forward_right_offset_
int IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::forward_right_offset_[3] = {0, 0, 0} protected
Referenced by build_with_known_pattern(), and get_max_stencil().
centred_left_offset_
int IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::centred_left_offset_[3] = {0, 0, 0} protected
Referenced by build_with_known_pattern(), and get_max_stencil().
centred_right_offset_
int IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::centred_right_offset_[3] = {0, 0, 0} protected
Referenced by build_with_known_pattern(), and get_max_stencil().
backward_left_offset_
int IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::backward_left_offset_[3] = {0, 0, 0} protected
Referenced by build_with_known_pattern(), and get_max_stencil().
backward_right_offset_
int IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::backward_right_offset_[3] = {0, 0, 0} protected
Referenced by build_with_known_pattern(), and get_max_stencil().
computed_stencil_
bool IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::computed_stencil_ = false protected
Referenced by compute_stencil_properties().
known_pattern_
int IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::known_pattern_ =1 protected
Referenced by build(), impose_boundary_conditions(), modify_rhs_for_bc(), scale_matrix_by_vector(), sum_matrices_subproblems(), and sum_sparse_matrices_subproblems().