TrioCFD: DP_Impose Class Reference
DP_Impose Class Reference
#include <DP_Impose.h>
Public Member Functions
Entree & lire_donnees (Entree &)
Public Member Functions inherited from Perte_Charge_Singuliere
double K () const
Entree & lire_donnees (Entree &)
Public Member Functions inherited from Perte_Charge
int direction_perte_charge () const
Detailed Description
impose un Delta P (pour simuler une pompe) depuis un champ exterieur
See also
Perte_Charge Perte_Charge_Reguliere
Constructor & Destructor Documentation
~DP_Impose()
DP_Impose::~DP_Impose () inline override
Member Function Documentation
lire_donnees()
Entree & DP_Impose::lire_donnees (Entree & is)
Lit les specifications d'un Delta P impose a partir d'un flot d'entree.
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Exceptions
pas un champ
References Parser_U::addVar(), Param::ajouter(), Perte_Charge_Singuliere::deb_cible_, DP_, dp_regul_, Perte_Charge_Singuliere::eps_, Process::exit(), Param::lire_avec_accolades(), Parser_U::parseString(), Perte_Charge_Singuliere::regul_, Param::REQUIRED, Parser_U::setNbVar(), and Parser_U::setString().
Referenced by DP_Impose_PolyMAC_Face::readOn(), and DP_Impose_VEF_Face::readOn().
mettre_a_jour()
void DP_Impose::mettre_a_jour (double temps)
References DP_, Champ_Don_base::mettre_a_jour(), and Perte_Charge_Singuliere::regul_.
Referenced by DP_Impose_PolyMAC_Face::mettre_a_jour(), and DP_Impose_VEF_Face::mettre_a_jour().
update_dp_regul()
void DP_Impose::update_dp_regul (const Equation_base & eqn, double deb, DoubleVect & bilan)
References Perte_Charge_Singuliere::deb_cible_, dp_regul_, Perte_Charge_Singuliere::eps_, Parser_U::eval(), Process::me(), Schema_Temps_base::pas_de_temps(), Equation_base::probleme(), Perte_Charge_Singuliere::regul_, Probleme_base::schema_temps(), Parser_U::setVar(), and Schema_Temps_base::temps_courant().
Referenced by DP_Impose_PolyMAC_Face::mettre_a_jour(), and DP_Impose_VEF_Face::mettre_a_jour().
Member Data Documentation
DP_
TRUST_Deriv< Champ_Don_base > DP_Impose::DP_ protected
Referenced by DP_Impose_PolyMAC_Face::ajouter_blocs(), DP_Impose_VEF_Face::ajouter_blocs(), lire_donnees(), and mettre_a_jour().
dp_regul_
double DP_Impose::dp_regul_ = 1e+38 protected
Referenced by DP_Impose_PolyMAC_Face::ajouter_blocs(), DP_Impose_VEF_Face::ajouter_blocs(), lire_donnees(), and update_dp_regul().