TrioCFD: KerasLayerActivation Class Reference
KerasLayerActivation Class Reference
#include <keras_model.h>
Member Enumeration Documentation
ActivationType
enum KerasLayerActivation::ActivationType
Enumerator
kLinear
kRelu
kSoftPlus
kSigmoid
kTanh
kHardSigmoid
Constructor & Destructor Documentation
KerasLayerActivation()
KerasLayerActivation::KerasLayerActivation () inline
~KerasLayerActivation()
KerasLayerActivation::~KerasLayerActivation () inline override
Member Function Documentation
LoadLayer()
bool KerasLayerActivation::LoadLayer (std::ifstream * file) override virtual
Implements KerasLayer.
References kHardSigmoid, kLinear, kRelu, kSigmoid, kSoftPlus, and kTanh.
Referenced by KerasLayerDense::LoadLayer(), KerasLayerConvolution2d::LoadLayer(), and KerasLayerLSTM::LoadLayer().
Apply()
bool KerasLayerActivation::Apply (Tensor * in, Tensor * out) override virtual
Implements KerasLayer.
References Tensor::data_, kHardSigmoid, kLinear, kRelu, kSigmoid, kSoftPlus, and kTanh.
Referenced by KerasLayerDense::Apply(), and KerasLayerConvolution2d::Apply().