TrioCFD: LecFicDiffuse Class Reference
LecFicDiffuse Class Reference
#include <LecFicDiffuse.h>
Public Member Functions
const Type_info * get_info () const override
LecFicDiffuse (const char *name, std::ios_base::openmode mode=ios::in)
int ouvrir (const char *name, std::ios_base::openmode mode=ios::in) override
Public Member Functions inherited from Lec_Diffuse_base
int get (char *buf, std::streamsize bufsize) override
const Type_info * get_info () const override
void set_bin (bool bin) override
void set_check_types (bool flag) override
const Type_info * get_info () const override
const Type_info * get_info () const override
virtual int get (char *buf, std::streamsize bufsize)
void set_bin (bool bin) override
virtual void set_check_types (bool flag)
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Entree
virtual int error_handle_ (int fail_flag)
Protected Member Functions inherited from AbstractIO
template<typename _TYPE_ >
bool must_convert () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Attributes inherited from AbstractIO
bool avoid_conversion_
Detailed Description
et chaque item lu dans ce fichier est diffuse a tous les autres processus du groupe tous. Il en est de meme pour les methodes d'inspection de l'etat d'un fichier.
Constructor & Destructor Documentation
~LecFicDiffuse()
LecFicDiffuse::~LecFicDiffuse ()
LecFicDiffuse() [1/2]
LecFicDiffuse::LecFicDiffuse ()
References Entree::ERROR_CONTINUE, file_, and Entree::set_error_action().
LecFicDiffuse() [2/2]
LecFicDiffuse::LecFicDiffuse (const char * name, std::ios_base::openmode mode = ios::in)
ouverture du fichier name.
Cette methode doit etre appelee sur tous les processeurs. En cas d'echec : exit()
References Entree::ERROR_CONTINUE, Process::exit(), file_, Process::je_suis_maitre(), ouvrir(), and Entree::set_error_action().
Member Function Documentation
cree_instance()
Objet_U * LecFicDiffuse::cree_instance () static
taille_memoire()
unsigned LecFicDiffuse::taille_memoire () const override virtual
Reimplemented from EFichier.
Reimplemented in LecFicDiffuseBin.
duplique()
int LecFicDiffuse::duplique () const override virtual
Reimplemented from EFichier.
Reimplemented in LecFicDiffuseBin.
info()
const Type_info * LecFicDiffuse::info () static
get_info()
const Type_info * LecFicDiffuse::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Lec_Diffuse_base.
Reimplemented in LecFicDiffuseBin.
self_cast() [1/2]
LecFicDiffuse & LecFicDiffuse::self_cast (Objet_U & r) static
self_cast() [2/2]
const LecFicDiffuse & LecFicDiffuse::self_cast (const Objet_U & r) static
printOn()
Sortie & LecFicDiffuse::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Lec_Diffuse_base.
Reimplemented in LecFicDiffuseBin.
readOn()
Entree & LecFicDiffuse::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Lec_Diffuse_base.
Reimplemented in LecFicDiffuseBin.
ouvrir()
int LecFicDiffuse::ouvrir (const char * name, std::ios_base::openmode mode = ios::in) override virtual
Ouverture du fichier.
Cette methode doit etre appelee par tous les processeurs du groupe. Valeur de retour: 1 si ok, 0 sinon
Reimplemented from Entree_Fichier_base.
References file_, Process::je_suis_maitre(), and Entree_Fichier_base::ouvrir().
Referenced by Champ_front_lu::initialiser(), VerifierCoin::interpreter_(), LecFicDiffuse(), LecFicDiffuseBin::LecFicDiffuseBin(), Modele_turbulence_hyd_base::lire_distance_paroi(), Modele_turbulence_hyd_Longueur_Melange_VEF::lire_distance_paroi(), Modele_Lam_Bremhorst_VEF::lire_distance_paroi(), and Triple_Line_Model_FT_Disc::readOn().
get_istream() [1/2]
istream & LecFicDiffuse::get_istream () override virtual
Reimplemented from Entree.
References Process::exit(), file_, Entree::get_istream(), and Process::je_suis_maitre().
get_istream() [2/2]
const istream & LecFicDiffuse::get_istream () const override virtual
Reimplemented from Entree.
References Process::exit(), file_, Entree::get_istream(), and Process::je_suis_maitre().
get_entree_master()
Entree & LecFicDiffuse::get_entree_master () inline override protected virtual
Implements Lec_Diffuse_base.
References file_.
Member Data Documentation
info_obj
const Type_info LecFicDiffuse::info_obj static
file_
EFichier LecFicDiffuse::file_ protected
Referenced by get_entree_master(), get_istream(), LecFicDiffuse(), and ouvrir().