TrioCFD: Op_Conv_EF_base Class Reference
Op_Conv_EF_base Class Reference
#include <Op_Conv_EF_base.h>
Public Member Functions
double calculer_dt_stab () const override
void completer () override
const Type_info * get_info () const override
int impr (Sortie &os) const override
Public Member Functions inherited from Operateur_Conv_base
const Type_info * get_info () const override
Public Member Functions inherited from Operateur_base
void associer_eqn (const Equation_base &)
virtual double calculer_dt_stab () const
virtual void completer ()
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual void mettre_a_jour (double temps)
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Op_EF_base
void dimensionner (const Domaine_EF &, const Domaine_Cl_EF &, Matrice_Morse &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Operateur_Conv_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
Classe de base des operateurs de convection EF
Constructor & Destructor Documentation
Op_Conv_EF_base()
Op_Conv_EF_base::Op_Conv_EF_base ()
~Op_Conv_EF_base()
Op_Conv_EF_base::~Op_Conv_EF_base () override
Member Function Documentation
info()
const Type_info * Op_Conv_EF_base::info () static
get_info()
const Type_info * Op_Conv_EF_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
Reimplemented in Op_Conv_SUPG_EF.
self_cast() [1/2]
Op_Conv_EF_base & Op_Conv_EF_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Op_Conv_EF_base & Op_Conv_EF_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Op_Conv_EF_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
Reimplemented in Op_Conv_SUPG_EF.
References Objet_U::que_suis_je().
readOn()
Entree & Op_Conv_EF_base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
Reimplemented in Op_Conv_SUPG_EF.
associer_vitesse()
void Op_Conv_EF_base::associer_vitesse (const Champ_base & vit) override virtual
Implements Operateur_Conv_base.
References vitesse_.
vitesse() [1/2]
const Champ_Inc_base & Op_Conv_EF_base::vitesse () const
References TRUST_Ref< _CLASSE_ >::valeur(), and vitesse_.
vitesse() [2/2]
Champ_Inc_base & Op_Conv_EF_base::vitesse ()
References TRUST_Ref< _CLASSE_ >::valeur(), and vitesse_.
associer()
void Op_Conv_EF_base::associer (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_cl_dis, const Champ_Inc_base &) override virtual
Implements Operateur_base.
References la_zcl_EF, and le_dom_EF.
calculer()
DoubleTab & Op_Conv_EF_base::calculer (const DoubleTab & transporte, DoubleTab & resu) const override virtual
Reimplemented from Operateur_base.
References Operateur_base::ajouter().
calculer_dt_stab()
double Op_Conv_EF_base::calculer_dt_stab () const override virtual
Calcul dt_stab.
Returns
(double) renvoie toujours 1.e30
Reimplemented from Operateur_base.
References Operateur_Conv_base::fixer_dt_stab_conv(), and Process::mp_min().
calculer_pour_post()
void Op_Conv_EF_base::calculer_pour_post (Champ_base & espace_stockage, const Nom & option, int) const override virtual
Reimplemented from MorEqn.
References Process::exit().
remplir_fluent()
void Op_Conv_EF_base::remplir_fluent () const virtual
References Operateur_base::ajouter(), MorEqn::equation(), and Operateur_base::flux_bords_.
impr()
int Op_Conv_EF_base::impr (Sortie & os) const override virtual
DOES NOTHING - to override in derived classes.
Imprime l'operateur sur un flot de sortie.
Parameters
(Sortie& os)
Returns
(int) renvoie toujours 1
Reimplemented from Operateur_base.
References Op_EF_base::impr().
associer_domaine_cl_dis()
void Op_Conv_EF_base::associer_domaine_cl_dis (const Domaine_Cl_dis_base & domaine_cl_dis) override virtual
Reimplemented from Operateur_base.
References la_zcl_EF.
phi_u_transportant()
int Op_Conv_EF_base::phi_u_transportant (const Equation_base & eq) const
definit si l'on convecte psi avec phi*u ou avec u
References Equation_base::inconnue(), and Field_base::le_nom().
completer()
void Op_Conv_EF_base::completer () override virtual
Associe l'operateur au domaine_dis, le domaine_Cl_dis, et a l'inconnue de son equation.
Exceptions
pas d'equation associee
Reimplemented from Operateur_base.
References Operateur_base::completer(), MorEqn::equation(), and Op_EF_base::marque_elem().
Referenced by Op_Conv_EF::completer(), and Op_Conv_BTD_EF::completer().
Member Data Documentation
info_obj
const Type_info Op_Conv_EF_base::info_obj static
le_dom_EF
TRUST_Ref< Domaine_EF *> Op_Conv_EF_base::le_dom_EF protected
Referenced by associer(), Op_Conv_EF::dimensionner(), and Op_Conv_EF::modifier_pour_Cl().
la_zcl_EF
TRUST_Ref< Domaine_Cl_EF *> Op_Conv_EF_base::la_zcl_EF protected
Referenced by associer(), associer_domaine_cl_dis(), Op_Conv_EF::dimensionner(), and Op_Conv_EF::modifier_pour_Cl().
vitesse_
TRUST_Ref< Champ_Inc_base *> Op_Conv_EF_base::vitesse_ protected
Referenced by Op_Conv_EF::ajouter_contribution_sous_cond(), associer_vitesse(), Op_Conv_EF::calculer_dt_stab(), and vitesse().
fluent_
DoubleVect Op_Conv_EF_base::fluent_ mutable protected