TrioCFD: Intersections_Elem_Facettes Class Reference
Intersections_Elem_Facettes Class Reference
#include <Intersections_Elem_Facettes_Data.h>
Public Member Functions
void ajoute_intersection (int num_facette, int num_element, double surface_intersection, double contrib_volume_phase1, double contrib_barycentre_phase1[3], double contrib_aire_faces_phase1[3], double contrib_barycentre_faces_phase1[3][2], double barycentre_u, double barycentre_v, double barycentre_w)
Intersections_Elem_Facettes_Data & get_set_data_intersection (int index)
const ArrOfInt & index_elem () const
const ArrOfInt & index_facette () const
Detailed Description
Cette classe contient les donnees des intersections entre les facettes de l'interface et les elements euleriens sous la forme d'une liste doublement chainee. Pour parcourir les facettes qui coupent un element "elem", on fait:
int index=index_elem()[elem]; while (index >= 0) { const Intersections_Elem_Facettes_Data & data = data_intersection(index); ... // faire quelque chose avec data index = data.index_facette_suivante_; }
Pour parcourir les elements qui sont coupes par une facette "facette":
int index=index_facette()[facette]; while (index >= 0) { const Intersections_Elem_Facettes_Data & data = data_intersection(index); ... // faire quelque chose avec data index = data.index_element_suivant_; }
Constructor & Destructor Documentation
Intersections_Elem_Facettes()
Intersections_Elem_Facettes::Intersections_Elem_Facettes ()
~Intersections_Elem_Facettes()
Intersections_Elem_Facettes::~Intersections_Elem_Facettes ()
Member Function Documentation
get_liste_elements_traverses()
void Intersections_Elem_Facettes::get_liste_elements_traverses (int num_facette, ArrOfInt & liste_elements) const
References TRUSTArray< _TYPE_, _SIZE_ >::append_array(), Intersections_Elem_Facettes_Data::index_element_suivant_, Intersections_Elem_Facettes_Data::numero_element_, TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by Parcours_interface::parcours_facette().
get_liste_facettes_traversantes()
void Intersections_Elem_Facettes::get_liste_facettes_traversantes (int num_element, ArrOfInt & liste_facettes) const
References TRUSTArray< _TYPE_, _SIZE_ >::append_array(), Intersections_Elem_Facettes_Data::index_facette_suivante_, Intersections_Elem_Facettes_Data::numero_facette_, and TRUSTArray< _TYPE_, _SIZE_ >::resize_array().
Referenced by Maillage_FT_Disc::calculer_voisinage_facettes(), and IJK_Interfaces::compute_cell_phase_with_interface_normal().
ajoute_intersection()
void Intersections_Elem_Facettes::ajoute_intersection (int num_facette, int num_element, double fraction_surface_intersection, double contrib_volume_phase1, double contrib_barycentre_phase1[3], double contrib_aire_faces_phase1[3], double contrib_barycentre_faces_phase1[3][2], double barycentre_u, double barycentre_v, double barycentre_w)
Ajoute une entree a la liste doublement chainee d'intersections entre la facette d'interface num_facette et l'element eulerien num_element.
Le numero d'element doit verifier 0 <= num_element < domaine.nb_elem() Si le numero de facette est superieur a la taille de l'index des facettes, on agrandit l'index.
References Intersections_Elem_Facettes_Data::barycentre_, Intersections_Elem_Facettes_Data::contrib_aire_faces_phase1_, Intersections_Elem_Facettes_Data::contrib_barycentre_faces_phase1_, Intersections_Elem_Facettes_Data::contrib_barycentre_phase1_, Intersections_Elem_Facettes_Data::contrib_volume_phase1_, Intersections_Elem_Facettes_Data::fraction_surface_intersection_, Intersections_Elem_Facettes_Data::index_element_suivant_, Intersections_Elem_Facettes_Data::index_facette_suivante_, Intersections_Elem_Facettes_Data::numero_element_, Intersections_Elem_Facettes_Data::numero_facette_, TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by Parcours_interface::calcul_intersection_facelem_2D(), and Parcours_interface::calcul_intersection_facelem_3D().
reset()
void Intersections_Elem_Facettes::reset (int nb_elements_euleriens = 0, int nb_facettes = 0)
References TRUSTArray< _TYPE_, _SIZE_ >::resize_array().
Referenced by Maillage_FT_Disc::maillage_modifie(), Parcours_interface::parcourir(), and Maillage_FT_Disc::reset().
index_elem()
const ArrOfInt & Intersections_Elem_Facettes::index_elem () const
Renvoie un tableau de taille domaine.
nb_elem(): pour un element 0 <= elem < domaine.nb_elem(), index_elem()[elem] est l'indice de la premiere intersection entre l'element et les facettes du maillage lagrangien (voir description de la classe)
Referenced by Maillage_FT_Disc::calcul_indicatrice(), Transport_Interfaces_FT_Disc::calcul_maxfa7(), Transport_Interfaces_FT_Disc::calcul_nb_traverse(), Transport_Interfaces_FT_Disc::calcul_OutElemFa7(), IJK_Interfaces::calculer_barycentre(), Transport_Interfaces_FT_Disc::calculer_distance_interface(), Navier_Stokes_FT_Disc::calculer_gradient_indicatrice(), ComputeValParCompoInCell::calculer_indic_elem_pour_compo(), IJK_Interfaces::calculer_indicatrice(), IJK_Interfaces::calculer_indicatrice_optim(), IJK_Interfaces::calculer_indicatrice_surfacique_barycentre_face(), IJK_Interfaces::calculer_indicatrice_surfacique_face(), IJK_Interfaces::calculer_indicatrices(), IJK_Interfaces::calculer_indicatrices_optim(), ComputeValParCompoInCell::calculer_moy_field_fa7_par_compo(), ComputeValParCompoInCell::calculer_moy_field_sommet_par_compo(), ComputeValParCompoInCell::calculer_moyennes_interface_element_pour_compo(), ComputeValParCompoInCell::calculer_somme_field_sommet_par_compo(), IJK_Interfaces::calculer_surface_interface(), Triple_Line_Model_FT_Disc::compute_approximate_interface_inout(), IJK_Interfaces::compute_cell_phase_with_interface_normal(), IJK_Interfaces::compute_drapeaux_vapeur_v4(), ComputeValParCompoInCell::compute_list_compo_connex_in_element(), Maillage_FT_Disc::compute_normale_element(), Maillage_FT_Disc::compute_surface_and_normale_element(), Triple_Line_Model_FT_Disc::compute_TCL_fluxes_in_all_boundary_cells(), IJK_Composantes_Connex::fill_mixed_cell_compo(), Triple_Line_Model_FT_Disc::get_in_out_coords(), Transport_Interfaces_FT_Disc::lire_maillage_ft_cao(), Transport_Interfaces_FT_Disc::mettre_a_jour(), operator=(), Transport_Interfaces_FT_Disc::PPP_face_interface(), IJK_One_Dimensional_Subproblems_Interfaces_Fields::retrieve_interfacial_surface_quantity(), Transport_Interfaces_FT_Disc::StockageFa7(), Topologie_Maillage_FT::test_collision_facettes(), Transport_Interfaces_FT_Disc::transfert_conservatif_eulerien_vers_lagrangien_sommets(), and Remailleur_Collision_FT_Thomas::transport_volume_perdu_sur_sommet().
index_facette()
const ArrOfInt & Intersections_Elem_Facettes::index_facette () const
Renvoie un tableau de taille "nombre de facettes de l'interface" pour un element 0 <= facette < nb_facettes,.
index_facette()[facette] est l'indice de la premiere intersection entre la facette et les elements du maillage lagrangien (voir description de la classe)
Referenced by IJK_Interfaces::calculer_aire_interfaciale(), IJK_Interfaces::calculer_aire_interfaciale_for_compo(), Navier_Stokes_FT_Disc::calculer_delta_u_interface(), IJK_Interfaces::calculer_kappa_ft(), IJK_Interfaces::calculer_normales_et_aires_interfaciales(), IJK_Interfaces::compute_drapeaux_vapeur_v4(), Triple_Line_Model_FT_Disc::compute_TCL_fluxes_in_all_boundary_cells(), Remailleur_Collision_FT_Thomas::mettre_a_jour_data(), operator=(), and Topologie_Maillage_FT::test_collision_facettes().
data_intersection()
const Intersections_Elem_Facettes_Data & Intersections_Elem_Facettes::data_intersection (int index) const inline
Renvoie les donnees de l'intersection stockee a l'indice "index" dans le tableau "data" (0 <= index < data_real_size_)
Referenced by Maillage_FT_Disc::calcul_indicatrice(), Transport_Interfaces_FT_Disc::calcul_maxfa7(), Transport_Interfaces_FT_Disc::calcul_nb_traverse(), Transport_Interfaces_FT_Disc::calcul_OutElemFa7(), IJK_Interfaces::calculer_aire_interfaciale(), IJK_Interfaces::calculer_aire_interfaciale_for_compo(), IJK_Interfaces::calculer_barycentre(), Navier_Stokes_FT_Disc::calculer_delta_u_interface(), Transport_Interfaces_FT_Disc::calculer_distance_interface(), ComputeValParCompoInCell::calculer_indic_elem_pour_compo(), IJK_Interfaces::calculer_indicatrice(), IJK_Interfaces::calculer_indicatrice_optim(), IJK_Interfaces::calculer_indicatrice_surfacique_barycentre_face(), IJK_Interfaces::calculer_indicatrice_surfacique_face(), IJK_Interfaces::calculer_indicatrices(), IJK_Interfaces::calculer_indicatrices_optim(), IJK_Interfaces::calculer_kappa_ft(), ComputeValParCompoInCell::calculer_moy_field_fa7_par_compo(), ComputeValParCompoInCell::calculer_moy_field_sommet_par_compo(), ComputeValParCompoInCell::calculer_moyennes_interface_element_pour_compo(), IJK_Interfaces::calculer_normales_et_aires_interfaciales(), ComputeValParCompoInCell::calculer_somme_field_sommet_par_compo(), IJK_Interfaces::calculer_surface_interface(), Triple_Line_Model_FT_Disc::compute_approximate_interface_inout(), IJK_Interfaces::compute_cell_phase_with_interface_normal(), IJK_Interfaces::compute_drapeaux_vapeur_v4(), ComputeValParCompoInCell::compute_list_compo_connex_in_element(), Maillage_FT_Disc::compute_normale_element(), Maillage_FT_Disc::compute_surface_and_normale_element(), Triple_Line_Model_FT_Disc::compute_TCL_fluxes_in_all_boundary_cells(), IJK_Composantes_Connex::fill_mixed_cell_compo(), Triple_Line_Model_FT_Disc::get_in_out_coords(), Transport_Interfaces_FT_Disc::mettre_a_jour(), Remailleur_Collision_FT_Thomas::mettre_a_jour_data(), Transport_Interfaces_FT_Disc::PPP_face_interface(), IJK_One_Dimensional_Subproblems_Interfaces_Fields::retrieve_interfacial_surface_quantity(), Transport_Interfaces_FT_Disc::StockageFa7(), Topologie_Maillage_FT::test_collision_facettes(), Transport_Interfaces_FT_Disc::transfert_conservatif_eulerien_vers_lagrangien_sommets(), and Remailleur_Collision_FT_Thomas::transport_volume_perdu_sur_sommet().
get_set_data_intersection()
Intersections_Elem_Facettes_Data & Intersections_Elem_Facettes::get_set_data_intersection (int index) inline
Renvoie les donnees de l'intersection stockee a l'indice "index" dans le tableau "data" (0 <= index < data_real_size_)
ATTENTION A SON UTILISATION !!!
operator=()
const Intersections_Elem_Facettes & Intersections_Elem_Facettes::operator= (const Intersections_Elem_Facettes & ief)
operateur de copie
References index_elem(), index_facette(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().