TrioCFD: Op_Diff_Flux_Chaleur_Turb_negligeable Class Reference
Op_Diff_Flux_Chaleur_Turb_negligeable Class Reference
#include <Op_Diff_Flux_Chaleur_Turb_Base.h>
Public Member Functions
void dimensionner (Matrice_Morse &) const override
const Type_info * get_info () const override
void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const override
Public Member Functions inherited from Operateur_negligeable
DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const
DoubleTab & calculer (const DoubleTab &, DoubleTab &) const
void mettre_a_jour (double)
const Type_info * get_info () const override
Public Member Functions inherited from Operateur_base
void associer_eqn (const Equation_base &)
virtual double calculer_dt_stab () const
virtual void completer ()
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual void mettre_a_jour (double temps)
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Operateur_negligeable
void associer (const Domaine_dis_base &, const Domaine_Cl_dis_base &, const Champ_Inc_base &)
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Op_Diff_Flux_Chaleur_Turb_negligeable()
Op_Diff_Flux_Chaleur_Turb_negligeable::Op_Diff_Flux_Chaleur_Turb_negligeable ()
~Op_Diff_Flux_Chaleur_Turb_negligeable()
Op_Diff_Flux_Chaleur_Turb_negligeable::~Op_Diff_Flux_Chaleur_Turb_negligeable ()
Member Function Documentation
cree_instance()
Objet_U * Op_Diff_Flux_Chaleur_Turb_negligeable::cree_instance () static
taille_memoire()
unsigned Op_Diff_Flux_Chaleur_Turb_negligeable::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Op_Diff_Flux_Chaleur_Turb_negligeable::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Op_Diff_Flux_Chaleur_Turb_negligeable::info () static
get_info()
const Type_info * Op_Diff_Flux_Chaleur_Turb_negligeable::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Op_Diff_Flux_Chaleur_Turb_Base.
self_cast() [1/2]
Op_Diff_Flux_Chaleur_Turb_negligeable & Op_Diff_Flux_Chaleur_Turb_negligeable::self_cast (Objet_U & r) static
self_cast() [2/2]
const Op_Diff_Flux_Chaleur_Turb_negligeable & Op_Diff_Flux_Chaleur_Turb_negligeable::self_cast (const Objet_U & r) static
printOn()
Sortie & Op_Diff_Flux_Chaleur_Turb_negligeable::printOn (Sortie & os) const override protected virtual
DOES NOTHING - to override in derived classes.
Imprime l'operateur sur un flot de sortie.
Parameters
(Sortie& os) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Op_Diff_Flux_Chaleur_Turb_Base.
References Objet_U::que_suis_je().
readOn()
Entree & Op_Diff_Flux_Chaleur_Turb_negligeable::readOn (Entree & is) override protected virtual
DOES NOTHING - to override in derived classes.
Lit un operateur sur un flot d'entree.
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Op_Diff_Flux_Chaleur_Turb_Base.
associer()
void Op_Diff_Flux_Chaleur_Turb_negligeable::associer (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_cl_dis, const Champ_Inc_base & inco) inline override virtual
Implements Operateur_base.
References Operateur_negligeable::associer().
ajouter()
DoubleTab & Op_Diff_Flux_Chaleur_Turb_negligeable::ajouter (const DoubleTab & x, DoubleTab & y) const inline override virtual
Reimplemented from Operateur_base.
References Operateur_negligeable::ajouter().
calculer()
DoubleTab & Op_Diff_Flux_Chaleur_Turb_negligeable::calculer (const DoubleTab & x, DoubleTab & y) const inline override virtual
Reimplemented from Operateur_base.
References Operateur_negligeable::calculer().
contribuer_a_avec()
void Op_Diff_Flux_Chaleur_Turb_negligeable::contribuer_a_avec (const DoubleTab & inco, Matrice_Morse & matrice) const inline override virtual
on assemble la matrice.
Reimplemented from Operateur_base.
contribuer_au_second_membre()
void Op_Diff_Flux_Chaleur_Turb_negligeable::contribuer_au_second_membre (DoubleTab & resu) const inline override virtual
on ajoute la contribution du second membre.
Reimplemented from Operateur_base.
modifier_pour_Cl()
void Op_Diff_Flux_Chaleur_Turb_negligeable::modifier_pour_Cl (Matrice_Morse & , DoubleTab &) const inline override virtual
DOES NOTHING - to override in derived classes.
Parameters
(Matrice_Morse&) une matrice au format Morse
(DoubleTab&) un tableau de valeur (double)
Exceptions
methode a surcharger
Reimplemented from Operateur_base.
dimensionner()
void Op_Diff_Flux_Chaleur_Turb_negligeable::dimensionner (Matrice_Morse & mat) const inline override virtual
DOES NOTHING - to override in derived classes.
Parameters
(Matrice_Morse&) une matrice au format Morse
Exceptions
methode a surcharger
Reimplemented from Operateur_base.
associer_diffusivite_turbulente()
void Op_Diff_Flux_Chaleur_Turb_negligeable::associer_diffusivite_turbulente () inline override virtual
Implements Op_Diff_Flux_Chaleur_Turb_Base.
Member Data Documentation
info_obj
const Type_info Op_Diff_Flux_Chaleur_Turb_negligeable::info_obj static