TrioCFD: Modele_Launder_Sharma_VEF Class Reference
Modele_Launder_Sharma_VEF Class Reference
#include <Modele_Launder_Sharma_VEF.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Modele_Fonc_Bas_Reynolds_Base
const Type_info * get_info () const override
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Modele_Fonc_Bas_Reynolds_Base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Modele_Launder_Sharma_VEF()
Modele_Launder_Sharma_VEF::Modele_Launder_Sharma_VEF ()
~Modele_Launder_Sharma_VEF()
Modele_Launder_Sharma_VEF::~Modele_Launder_Sharma_VEF ()
Member Function Documentation
cree_instance()
Objet_U * Modele_Launder_Sharma_VEF::cree_instance () static
taille_memoire()
unsigned Modele_Launder_Sharma_VEF::taille_memoire () const override virtual
Reimplemented from Modele_Lam_Bremhorst_VEF.
duplique()
int Modele_Launder_Sharma_VEF::duplique () const override virtual
Reimplemented from Modele_Lam_Bremhorst_VEF.
info()
const Type_info * Modele_Launder_Sharma_VEF::info () static
get_info()
const Type_info * Modele_Launder_Sharma_VEF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Modele_Lam_Bremhorst_VEF.
self_cast() [1/2]
Modele_Launder_Sharma_VEF & Modele_Launder_Sharma_VEF::self_cast (Objet_U & r) static
self_cast() [2/2]
const Modele_Launder_Sharma_VEF & Modele_Launder_Sharma_VEF::self_cast (const Objet_U & r) static
printOn()
Sortie & Modele_Launder_Sharma_VEF::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Modele_Lam_Bremhorst_VEF.
readOn()
Entree & Modele_Launder_Sharma_VEF::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Modele_Lam_Bremhorst_VEF.
References Modele_Fonc_Bas_Reynolds_Base::is_Cmu_constant_, Modele_Fonc_Bas_Reynolds_Base::is_Reynolds_stress_isotrope_, Param::lire_avec_accolades_depuis(), Objet_U::que_suis_je(), and Modele_Lam_Bremhorst_VEF::set_param().
Calcul_D()
DoubleTab & Modele_Launder_Sharma_VEF::Calcul_D (DoubleTab & D, const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const DoubleTab & vitesse, const DoubleTab & K_eps_Bas_Re, const Champ_Don_base & ch_visco) const override virtual
Reimplemented from Modele_Lam_Bremhorst_VEF.
References Objet_U::dimension, Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), Domaine_VF::face_normales(), Domaine_dis_base::nb_elem_tot(), Domaine_VF::nb_faces(), Domaine_VEF::oriente_normale(), Champ_Don_base::valeurs(), Domaine_VF::volumes(), and Domaine_VF::volumes_entrelaces().
Calcul_E()
DoubleTab & Modele_Launder_Sharma_VEF::Calcul_E (DoubleTab & E, const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const DoubleTab & transporte, const DoubleTab & K_eps_Bas_Re, const Champ_Don_base & ch_visco, const DoubleTab & visco_turb) const override virtual
Reimplemented from Modele_Lam_Bremhorst_VEF.
References Domaine_32_64< _SIZE_ >::creer_tableau_elements(), Domaine_VF::creer_tableau_faces(), Objet_U::dimension, Domaine_dis_base::domaine(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Modele_Fonc_Bas_Reynolds_Base::eq_hydraulique, Domaine_VF::face_voisins(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Domaine_dis_base::nb_elem(), Domaine_VF::nb_faces(), Domaine_VF::premiere_face_int(), Champ_Don_base::valeurs(), and Domaine_VF::volumes().
Referenced by Calcul_E_BiK().
Calcul_F1()
DoubleTab & Modele_Launder_Sharma_VEF::Calcul_F1 (DoubleTab & F1, const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const DoubleTab & P, const DoubleTab & K_eps_Bas_Re, const Champ_base & ch_visco) const override virtual
Reimplemented from Modele_Lam_Bremhorst_VEF.
References Domaine_VF::nb_faces().
Calcul_F2()
DoubleTab & Modele_Launder_Sharma_VEF::Calcul_F2 (DoubleTab & F2, DoubleTab & Deb, const Domaine_dis_base & domaine_dis, const DoubleTab & K_eps_Bas_Re, const Champ_base & ch_visco) const override virtual
Reimplemented from Modele_Lam_Bremhorst_VEF.
References Domaine_VF::face_voisins(), Domaine_VF::nb_faces(), Champ_Proto::valeurs(), and Domaine_VF::volumes().
Calcul_Fmu()
DoubleTab & Modele_Launder_Sharma_VEF::Calcul_Fmu (DoubleTab & Fmu, const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const DoubleTab & K_eps_Bas_Re, const Champ_Don_base & ch_visco) const override virtual
Reimplemented from Modele_Lam_Bremhorst_VEF.
References Domaine_VF::face_voisins(), Domaine_VF::nb_faces(), Champ_Don_base::valeurs(), and Domaine_VF::volumes().
lire_distance_paroi()
void Modele_Launder_Sharma_VEF::lire_distance_paroi () override virtual
Reimplemented from Modele_Lam_Bremhorst_VEF.
Calcul_D_BiK()
DoubleTab & Modele_Launder_Sharma_VEF::Calcul_D_BiK (DoubleTab & D, const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const DoubleTab & vitesse, const DoubleTab & K_Bas_Re, const DoubleTab & eps_Bas_Re, const Champ_Don_base & ch_visco) const override virtual
Reimplemented from Modele_Lam_Bremhorst_VEF.
References Objet_U::dimension, Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), Domaine_VF::face_normales(), Domaine_dis_base::nb_elem_tot(), Domaine_VF::nb_faces(), Domaine_VEF::oriente_normale(), Champ_Don_base::valeurs(), Domaine_VF::volumes(), and Domaine_VF::volumes_entrelaces().
Calcul_E_BiK()
DoubleTab & Modele_Launder_Sharma_VEF::Calcul_E_BiK (DoubleTab & E, const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const DoubleTab & transporte, const DoubleTab & K_Bas_Re, const DoubleTab & eps_Bas_Re, const Champ_Don_base & ch_visco, const DoubleTab & visco_turb) const override virtual
Reimplemented from Modele_Lam_Bremhorst_VEF.
References Calcul_E().
Calcul_F1_BiK()
DoubleTab & Modele_Launder_Sharma_VEF::Calcul_F1_BiK (DoubleTab & F1, const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const DoubleTab & P, const DoubleTab & K_Bas_Re, const DoubleTab & eps_Bas_Re, const Champ_base & ch_visco) const override virtual
Reimplemented from Modele_Lam_Bremhorst_VEF.
References Domaine_VF::nb_faces().
Calcul_F2_BiK()
DoubleTab & Modele_Launder_Sharma_VEF::Calcul_F2_BiK (DoubleTab & F2, DoubleTab & Deb, const Domaine_dis_base & domaine_dis, const DoubleTab & K_Bas_Re, const DoubleTab & eps_Bas_Re, const Champ_base & ch_visco) const override virtual
Reimplemented from Modele_Lam_Bremhorst_VEF.
References Domaine_VF::face_voisins(), Domaine_VF::nb_faces(), Champ_Proto::valeurs(), and Domaine_VF::volumes().
Calcul_Fmu_BiK()
DoubleTab & Modele_Launder_Sharma_VEF::Calcul_Fmu_BiK (DoubleTab & Fmu, const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const DoubleTab & K_Bas_Re, const DoubleTab & eps_Bas_Re, const Champ_Don_base & ch_visco) const override virtual
Reimplemented from Modele_Lam_Bremhorst_VEF.
References Domaine_VF::face_voisins(), TRUSTVect< _TYPE_, _SIZE_ >::mp_max_vect(), TRUSTVect< _TYPE_, _SIZE_ >::mp_min_vect(), Domaine_VF::nb_faces(), Champ_Don_base::valeurs(), and Domaine_VF::volumes().
Member Data Documentation
info_obj
const Type_info Modele_Launder_Sharma_VEF::info_obj static
le_dom_VEF
TRUST_Ref< Domaine_VEF *> Modele_Launder_Sharma_VEF::le_dom_VEF protected
le_dom_Cl_VEF
TRUST_Ref< Domaine_Cl_VEF *> Modele_Launder_Sharma_VEF::le_dom_Cl_VEF protected