TrioCFD: Vecteur3 Class Reference
Vecteur3 Class Reference
#include <Vecteur3.h>
Constructor & Destructor Documentation
Vecteur3() [1/5]
Vecteur3::Vecteur3 () inline
Vecteur3() [2/5]
Vecteur3::Vecteur3 (const Vecteur3 & w) inline
References v.
Vecteur3() [3/5]
Vecteur3::Vecteur3 (double x, double y, double z) inline
References v.
Vecteur3() [4/5]
Vecteur3::Vecteur3 (const DoubleTab & tab, int i) inline
References TRUSTArray< _TYPE_, _SIZE_ >::addr(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), and v.
Vecteur3() [5/5]
Vecteur3::Vecteur3 (const ArrOfDouble & arr) inline
References TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and v.
Member Function Documentation
set() [1/2]
void Vecteur3::set (double x, double y, double z) inline
References v.
set() [2/2]
void Vecteur3::set (const DoubleTab & tab, int i) inline
References TRUSTArray< _TYPE_, _SIZE_ >::addr(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), and v.
length()
double Vecteur3::length () const inline
References v.
Referenced by IJK_One_Dimensional_Subproblem::compute_colinearity(), IJK_One_Dimensional_Subproblem_Geometry::compute_colinearity(), IJK_One_Dimensional_Subproblem::compute_colinearity_cell_faces(), IJK_One_Dimensional_Subproblem_Geometry::compute_colinearity_cell_faces(), IJK_One_Dimensional_Subproblem::compute_distance_cell_centre(), IJK_One_Dimensional_Subproblem_Geometry::compute_distance_cell_centre(), IJK_One_Dimensional_Subproblem::compute_distance_faces_centres(), IJK_One_Dimensional_Subproblem_Geometry::compute_distance_faces_centres(), IJK_One_Dimensional_Subproblems::compute_dynamics_per_bubbles(), IJK_One_Dimensional_Subproblem::compute_interface_basis_vectors(), IJK_One_Dimensional_Subproblem::compute_local_shear_stress(), IJK_One_Dimensional_Subproblems::compute_overall_quantities(), IJK_One_Dimensional_Subproblem::compute_vertex_position(), IJK_One_Dimensional_Subproblem_Geometry::compute_vertex_position(), IJK_One_Dimensional_Subproblem::compute_weighting_coefficient(), and Fluide_Diphasique_IJK::get_gravite_norm().
operator=() [1/2]
Vecteur3 & Vecteur3::operator= (double x) inline
References v.
operator*=()
Vecteur3 & Vecteur3::operator*= (double x) inline
References v.
operator+=()
Vecteur3 & Vecteur3::operator+= (const Vecteur3 & x) inline
References v.
operator=() [2/2]
Vecteur3 & Vecteur3::operator= (const Vecteur3 & w) inline
References v.
operator[]() [1/2]
double Vecteur3::operator[] (int i) const inline
References v.
operator[]() [2/2]
double & Vecteur3::operator[] (int i) inline
References v.
norme_Linfini()
double Vecteur3::norme_Linfini () inline
norme L_infini, c'est le max des abs(v[i])
References v.
produit_vectoriel()
void Vecteur3::produit_vectoriel (const Vecteur3 & x, const Vecteur3 & y, Vecteur3 & resu) inline static
References v.
Referenced by IJK_Interfaces::calculer_vitesse_de_deformation(), IJK_Interfaces::calculer_vmoy_rotation_composantes_connexes(), IJK_Interfaces::compute_cell_phase_with_interface_normal(), IJK_Interfaces::compute_drapeaux_vapeur_v4(), IJK_One_Dimensional_Subproblem::compute_interface_basis_vectors(), Polyedre_32_64< _SIZE_ >::contient(), Polyedre_poly::normale(), IJK_Interfaces::transporter_maillage_deformation(), and IJK_Interfaces::transporter_maillage_rigide().
produit_scalaire()
double Vecteur3::produit_scalaire (const Vecteur3 & x, const Vecteur3 & y) inline static
References v.
Referenced by IJK_Interfaces::ajouter_terme_source_interfaces(), IJK_One_Dimensional_Subproblem::approximate_temperature_material_derivatives(), IJK_Interfaces::calculer_vmoy_rotation_composantes_connexes(), IJK_One_Dimensional_Subproblem::compute_colinearity(), IJK_One_Dimensional_Subproblem_Geometry::compute_colinearity(), IJK_One_Dimensional_Subproblem::compute_distance_cell_centre(), IJK_One_Dimensional_Subproblem_Geometry::compute_distance_cell_centre(), IJK_One_Dimensional_Subproblem::compute_distance_cell_centres_neighbours(), IJK_One_Dimensional_Subproblem_Geometry::compute_distance_cell_centres_neighbours(), IJK_One_Dimensional_Subproblem::compute_distance_cell_faces(), IJK_One_Dimensional_Subproblem_Geometry::compute_distance_cell_faces(), IJK_One_Dimensional_Subproblem::compute_distance_faces_centres(), IJK_One_Dimensional_Subproblem_Geometry::compute_distance_faces_centres(), IJK_One_Dimensional_Subproblem::compute_distance_last_cell_faces_neighbours(), IJK_One_Dimensional_Subproblem_Geometry::compute_distance_last_cell_faces_neighbours(), IJK_One_Dimensional_Subproblem::compute_interface_basis_vectors(), IJK_One_Dimensional_Subproblem::compute_vertex_position(), IJK_One_Dimensional_Subproblem_Geometry::compute_vertex_position(), Polyedre_32_64< _SIZE_ >::contient(), Intersection_Interface_ijk::distance_point_point(), Intersection_Interface_ijk::distance_point_point_signe(), Corrige_flux_FT_temperature_conv::extrapolation_amont_1_depuis_l_interface(), IJK_One_Dimensional_Subproblem::get_field_discrete_value_recursive(), Polyedre_poly::normale(), Intersection_Interface_ijk::projete_interface(), and IJK_One_Dimensional_Subproblem::retrieve_previous_temperature_on_probe().
init()
void Vecteur3::init () inline protected
References v.
Referenced by Matrice33::produit().
Friends And Related Function Documentation
Matrice33
friend class Matrice33 friend
operator-
Vecteur3 operator- (const Vecteur3 & , const Vecteur3 &) friend
Member Data Documentation
v
double Vecteur3::v[3] protected
Referenced by init(), length(), norme_Linfini(), operator*=(), operator+=(), operator=(), operator[](), Matrice33::produit(), produit_scalaire(), produit_vectoriel(), set(), and Vecteur3().