TrioCFD: Descripteur_FT Class Reference
Descripteur_FT Class Reference
#include <Descripteur_FT.h>
Public Member Functions
int ajoute_element (int PE_voisin, int element)
int ajoute_elements (int PE_voisin, const ArrOfInt &elements)
void calcul_liste_pe_voisins ()
const Type_info * get_info () const override
void retirer_elements (const ArrOfInt &nouveau_pe, Descripteur_FT &elements_retires)
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
See also
Desc_Structure_FT
Constructor & Destructor Documentation
~Descripteur_FT()
Descripteur_FT::~Descripteur_FT ()
Descripteur_FT() [1/2]
Descripteur_FT::Descripteur_FT ()
References Process::nproc(), and TRUSTArray< _TYPE_, _SIZE_ >::resize_array().
Descripteur_FT() [2/2]
Descripteur_FT::Descripteur_FT (const Descripteur_FT &) default
Member Function Documentation
cree_instance()
Objet_U * Descripteur_FT::cree_instance () static
taille_memoire()
unsigned Descripteur_FT::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Descripteur_FT::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Descripteur_FT::info () static
get_info()
const Type_info * Descripteur_FT::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
Descripteur_FT & Descripteur_FT::self_cast (Objet_U & r) static
self_cast() [2/2]
const Descripteur_FT & Descripteur_FT::self_cast (const Objet_U & r) static
printOn()
Sortie & Descripteur_FT::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
References Objet_U::que_suis_je(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
readOn()
Entree & Descripteur_FT::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
References Process::exit(), Objet_U::que_suis_je(), reset(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
operator=()
Descripteur_FT & Descripteur_FT::operator= (const Descripteur_FT & src)
References Process::nproc().
reset()
void Descripteur_FT::reset ()
References TRUSTArray< _TYPE_, _SIZE_ >::resize_array().
Referenced by readOn(), Desc_Structure_FT::reset(), and retirer_elements().
ajoute_element()
int Descripteur_FT::ajoute_element (int PE_voisin, int element)
Ajoute l'element au tableau du PE_voisin.
renvoie le rang de l'element ajoute dans le tableau d'elements du PE.
References TRUSTArray< _TYPE_, _SIZE_ >::append_array(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by Marching_Cubes::construire_noeuds_uniques(), Maillage_FT_Disc::creer_facettes_virtuelles(), Maillage_FT_Disc::creer_sommets_virtuels(), Desc_Structure_FT::echanger_elements(), and Cut_cell_FT_Disc::initialise_communications().
ajoute_elements()
int Descripteur_FT::ajoute_elements (int PE_voisin, const ArrOfInt & NVelements)
Ajoute l'element au tableau du PE_voisin.
renvoie la taiile du tableau d'elements du PE.
References TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by Maillage_FT_Disc::ajouter_maillage().
pe_voisins()
const ArrOfInt & Descripteur_FT::pe_voisins () const inline
Renvoie la liste des PE pour lesquels la liste d'elements est non vide, dans l'ordre croissant des numeros de PE.
Referenced by Maillage_FT_Disc::ajouter_maillage(), Desc_Structure_FT::calcul_schema_comm(), Desc_Structure_FT::check(), Maillage_FT_Disc::check_mesh(), Maillage_FT_Disc::check_sommets(), Maillage_FT_IJK::check_sommets(), Marching_Cubes::correspondance_espaces_distant_virtuel(), Desc_Structure_FT::echanger_elements(), Maillage_FT_Disc::nettoyer_maillage(), Maillage_FT_Disc::nettoyer_noeuds_virtuels_et_frontieres(), Maillage_FT_Disc::nettoyer_phase(), Maillage_FT_Disc::preparer_tableau_avant_transport(), and Desc_Structure_FT::remplir_element_pe().
elements()
const ArrOfInt & Descripteur_FT::elements (int pe_voisin) const inline
Renvoie la liste des elements distants/virtuels du pe en parametre.
Referenced by Maillage_FT_Disc::ajouter_maillage(), Desc_Structure_FT::check(), Maillage_FT_Disc::check_mesh(), Maillage_FT_Disc::check_sommets(), Maillage_FT_IJK::check_sommets(), Maillage_FT_Disc::convertir_numero_distant_local(), Marching_Cubes::correspondance_espaces_distant_virtuel(), Desc_Structure_FT::echanger_elements(), Maillage_FT_Disc::nettoyer_maillage(), Maillage_FT_Disc::nettoyer_noeuds_virtuels_et_frontieres(), Maillage_FT_Disc::nettoyer_phase(), Maillage_FT_Disc::preparer_tableau_avant_transport(), and Desc_Structure_FT::remplir_element_pe().
all_elements()
const TRUST_Vector< ArrOfInt > & Descripteur_FT::all_elements () const inline
Referenced by Desc_Structure_FT::calcul_schema_comm().
set_elements()
void Descripteur_FT::set_elements (int PE_voisin, const ArrOfInt & elements)
Remplace la liste des elements par celle en parametre.
Referenced by Marching_Cubes::correspondance_espaces_distant_virtuel(), Maillage_FT_Disc::nettoyer_maillage(), Maillage_FT_Disc::nettoyer_noeuds_virtuels_et_frontieres(), Maillage_FT_Disc::nettoyer_phase(), and retirer_elements().
contient_element()
int Descripteur_FT::contient_element (int pe, int element) const
Renvoie "pas zero" si l'element est deja dans le descripteur pour le pe donne, 0 sinon.
References TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by Maillage_FT_Disc::creer_facettes_virtuelles(), Maillage_FT_Disc::creer_sommets_virtuels(), and Cut_cell_FT_Disc::initialise_communications().
calcul_liste_pe_voisins()
void Descripteur_FT::calcul_liste_pe_voisins ()
Calcule la liste des PEs dont la liste d'elements est non vide, tries dans l'ordre croissant de numero de PE.
Le statut passe a OK.
References TRUSTArray< _TYPE_, _SIZE_ >::append_array(), and TRUSTArray< _TYPE_, _SIZE_ >::resize_array().
Referenced by Maillage_FT_Disc::ajouter_maillage(), Marching_Cubes::construire_noeuds_uniques(), Marching_Cubes::correspondance_espaces_distant_virtuel(), Maillage_FT_Disc::creer_facettes_virtuelles(), Maillage_FT_Disc::creer_sommets_virtuels(), Desc_Structure_FT::echanger_elements(), Cut_cell_FT_Disc::initialise_communications(), Maillage_FT_Disc::nettoyer_maillage(), Maillage_FT_Disc::nettoyer_noeuds_virtuels_et_frontieres(), Maillage_FT_Disc::nettoyer_phase(), Maillage_FT_Disc::remplir_structure(), and retirer_elements().
retirer_elements()
void Descripteur_FT::retirer_elements (const ArrOfInt & nouveau_pe, Descripteur_FT & elements_retires)
Pour chaque PE du descripteur, et pour 0 <= i < elements_[pe].
size_array() on considere l'element suivante: elem = elements_[pe][i] Si nouveau_pe[elem] >= 0, on retire elem du tableau elements_[pe] et on l'ajoute au tableau elements_retires.elements_[pe].
Parameters
(nouveau_pe) pour chaque element i (sommet ou facette), nouveau_pe[i] indique si l'element doit etre retire (nouveau_pe[i] >= 0) ou non (nouveau_pe[i] < 0) du descripteur Contrainte: la taille du tableau doit etre superieure au plus grand numero d'element stocke dans le descripteur.
(elements_retires) descripteur contenant les elements retires.
References TRUSTArray< _TYPE_, _SIZE_ >::append_array(), calcul_liste_pe_voisins(), reset(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), set_elements(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by Desc_Structure_FT::echanger_elements().
Member Data Documentation
info_obj
const Type_info Descripteur_FT::info_obj static