TrioCFD: Masse_ajoutee_Coef_Constant Class Reference
Masse_ajoutee_Coef_Constant Class Reference
#include <Masse_ajoutee_Coef_Constant.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
avec beta un coefficient constant (0.5 par defaut) et rho_m la masse volumique du melange
Constructor & Destructor Documentation
Masse_ajoutee_Coef_Constant()
Masse_ajoutee_Coef_Constant::Masse_ajoutee_Coef_Constant ()
~Masse_ajoutee_Coef_Constant()
Masse_ajoutee_Coef_Constant::~Masse_ajoutee_Coef_Constant ()
Member Function Documentation
cree_instance()
Objet_U * Masse_ajoutee_Coef_Constant::cree_instance () static
taille_memoire()
unsigned Masse_ajoutee_Coef_Constant::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Masse_ajoutee_Coef_Constant::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Masse_ajoutee_Coef_Constant::info () static
get_info()
const Type_info * Masse_ajoutee_Coef_Constant::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Masse_ajoutee_base.
self_cast() [1/2]
Masse_ajoutee_Coef_Constant & Masse_ajoutee_Coef_Constant::self_cast (Objet_U & r) static
self_cast() [2/2]
const Masse_ajoutee_Coef_Constant & Masse_ajoutee_Coef_Constant::self_cast (const Objet_U & r) static
printOn()
Sortie & Masse_ajoutee_Coef_Constant::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Masse_ajoutee_base.
readOn()
Entree & Masse_ajoutee_Coef_Constant::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Masse_ajoutee_base.
References Param::ajouter(), beta, Nom::debute_par(), Process::exit(), inj_ajoutee_gaz_, inj_ajoutee_liquide_, Masse_ajoutee_base::limiter_liquid_, Param::lire_avec_accolades_depuis(), n_l, Pb_Multiphase::nb_phases(), Pb_Multiphase::nom_phase(), Correlation_base::pb_, Objet_U::que_suis_je(), and TRUST_Ref< _CLASSE_ >::valeur().
ajouter()
void Masse_ajoutee_Coef_Constant::ajouter (const double * alpha, const double * rho, DoubleTab & a_r) const override virtual
Implements Masse_ajoutee_base.
References beta, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Masse_ajoutee_base::limiter_liquid_, and n_l.
coefficient()
void Masse_ajoutee_Coef_Constant::coefficient (const double * alpha, const double * rho, DoubleTab & coeff) const override virtual
Reimplemented from Masse_ajoutee_base.
References beta, coeff(), Masse_ajoutee_base::limiter_liquid_, and n_l.
ajouter_inj()
void Masse_ajoutee_Coef_Constant::ajouter_inj (const double * flux_alpha, const double * alpha, const double * rho, DoubleTab & f_a_r) const override virtual
Implements Masse_ajoutee_base.
References beta, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), inj_ajoutee_gaz_, inj_ajoutee_liquide_, Masse_ajoutee_base::limiter_liquid_, and n_l.
coeff()
void Masse_ajoutee_Coef_Constant::coeff (const DoubleTab & alpha, const DoubleTab & rho, DoubleTab & coeff) const override virtual
Implements Masse_ajoutee_base.
References beta, coeff(), Masse_ajoutee_base::limiter_liquid_, and n_l.
Referenced by coeff(), and coefficient().
Member Data Documentation
info_obj
const Type_info Masse_ajoutee_Coef_Constant::info_obj static
beta
double Masse_ajoutee_Coef_Constant::beta = 0.5 protected
Referenced by ajouter(), ajouter_inj(), coeff(), coefficient(), and readOn().
n_l
int Masse_ajoutee_Coef_Constant::n_l = -1 protected
Referenced by ajouter(), ajouter_inj(), coeff(), coefficient(), and readOn().
inj_ajoutee_liquide_
double Masse_ajoutee_Coef_Constant::inj_ajoutee_liquide_ = 1. protected
Referenced by ajouter_inj(), and readOn().
inj_ajoutee_gaz_
double Masse_ajoutee_Coef_Constant::inj_ajoutee_gaz_ = 1. protected
Referenced by ajouter_inj(), and readOn().