TrioCFD: Op_Diff_Dift_VDF< OP_TYPE > Class Template Reference
Op_Diff_Dift_VDF< OP_TYPE > Class Template Reference
#include <Op_Diff_Dift_VDF.h>
Member Function Documentation
associer_impl() [1/2]
template<typename OP_TYPE > template<Type_Operateur _TYPE_, typename EVAL_TYPE > std::enable_if_t< _TYPE_==Type_Operateur::Op_DIFF_ELEM||_TYPE_==Type_Operateur::Op_DIFT_ELEM||_TYPE_==Type_Operateur::Op_DIFT_MULTIPHASE_ELEM, void > Op_Diff_Dift_VDF< OP_TYPE >::associer_impl (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_cl_dis, const Champ_Inc_base & ch_diffuse) inline protected
associer_impl() [2/2]
template<typename OP_TYPE > template<Type_Operateur _TYPE_, typename EVAL_TYPE > std::enable_if_t< _TYPE_==Type_Operateur::Op_DIFF_FACE||_TYPE_==Type_Operateur::Op_DIFT_FACE||_TYPE_==Type_Operateur::Op_DIFT_MULTIPHASE_FACE, void > Op_Diff_Dift_VDF< OP_TYPE >::associer_impl (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_cl_dis, const Champ_Inc_base & ch_diffuse) inline protected
associer_diffusivite_impl()
template<typename OP_TYPE > template<typename EVAL_TYPE > void Op_Diff_Dift_VDF< OP_TYPE >::associer_diffusivite_impl (const Champ_base & ch_diff) inline protected
References Iterateur_VDF_base::evaluateur().
associer_pb()
template<typename OP_TYPE > template<typename EVAL_TYPE > void Op_Diff_Dift_VDF< OP_TYPE >::associer_pb (const Probleme_base & pb) inline protected
References Iterateur_VDF_base::evaluateur().
associer_corr_impl()
template<typename OP_TYPE > template<Type_Operateur _TYPE_, typename EVAL_TYPE > std::enable_if_t< _TYPE_==Type_Operateur::Op_DIFT_MULTIPHASE_FACE||_TYPE_==Type_Operateur::Op_DIFT_MULTIPHASE_ELEM, void > Op_Diff_Dift_VDF< OP_TYPE >::associer_corr_impl (const Correlation_base & corr) inline protected
References Iterateur_VDF_base::evaluateur().
get_diffusivite_turbulente_multiphase_impl()
template<typename OP_TYPE > template<Type_Operateur _TYPE_, typename EVAL_TYPE > std::enable_if_t< _TYPE_==Type_Operateur::Op_DIFT_MULTIPHASE_FACE||_TYPE_==Type_Operateur::Op_DIFT_MULTIPHASE_ELEM, const DoubleTab & > Op_Diff_Dift_VDF< OP_TYPE >::get_diffusivite_turbulente_multiphase_impl () const inline protected
References Iterateur_VDF_base::evaluateur().
set_nut_impl() [1/2]
template<typename OP_TYPE > template<Type_Operateur _TYPE_, typename EVAL_TYPE > std::enable_if_t< _TYPE_==Type_Operateur::Op_DIFT_MULTIPHASE_FACE, void > Op_Diff_Dift_VDF< OP_TYPE >::set_nut_impl (const DoubleTab & nut) inline protected
References Iterateur_VDF_base::evaluateur().
set_nut_impl() [2/2]
template<typename OP_TYPE > template<Type_Operateur _TYPE_, typename EVAL_TYPE > std::enable_if_t< _TYPE_==Type_Operateur::Op_DIFT_MULTIPHASE_ELEM, void > Op_Diff_Dift_VDF< OP_TYPE >::set_nut_impl (const DoubleTab & nut) inline protected
References Iterateur_VDF_base::evaluateur().
diffusivite_impl()
template<typename OP_TYPE > template<typename EVAL_TYPE > const Champ_base & Op_Diff_Dift_VDF< OP_TYPE >::diffusivite_impl () const inline protected
References Iterateur_VDF_base::evaluateur().
alpha_impl()
template<typename OP_TYPE > template<typename EVAL_TYPE > const double & Op_Diff_Dift_VDF< OP_TYPE >::alpha_impl (const int i) const inline protected
References Iterateur_VDF_base::evaluateur(), and Champ_Proto::valeurs().
tab_alpha_impl()
template<typename OP_TYPE > template<typename EVAL_TYPE > const DoubleTab & Op_Diff_Dift_VDF< OP_TYPE >::tab_alpha_impl () const inline protected
References Iterateur_VDF_base::evaluateur(), and Champ_Proto::valeurs().
mettre_a_jour_impl()
template<typename OP_TYPE > template<Type_Operateur _TYPE_, typename EVAL_TYPE > std::enable_if_t< _TYPE_==Type_Operateur::Op_DIFF_FACE, void > Op_Diff_Dift_VDF< OP_TYPE >::mettre_a_jour_impl () inline protected
References Iterateur_VDF_base::evaluateur().
associer_diffusivite_turbulente_impl()
template<typename OP_TYPE > template<Type_Operateur _TYPE_, typename EVAL_TYPE > std::enable_if_t< _TYPE_==Type_Operateur::Op_DIFT_ELEM||_TYPE_==Type_Operateur::Op_DIFT_FACE, void > Op_Diff_Dift_VDF< OP_TYPE >::associer_diffusivite_turbulente_impl (const Champ_Fonc_base & visc_ou_diff_turb) inline protected
References Iterateur_VDF_base::evaluateur().
associer_loipar_impl()
template<typename OP_TYPE > template<Type_Operateur _TYPE_, typename EVAL_TYPE > std::enable_if_t< _TYPE_==Type_Operateur::Op_DIFT_ELEM, void > Op_Diff_Dift_VDF< OP_TYPE >::associer_loipar_impl (const Turbulence_paroi_scal_base & loi_paroi) inline protected
References Iterateur_VDF_base::evaluateur().
completer_impl() [1/2]
template<typename OP_TYPE > template<Type_Operateur _TYPE_, typename EVAL_TYPE > std::enable_if_t< _TYPE_==Type_Operateur::Op_DIFT_ELEM, void > Op_Diff_Dift_VDF< OP_TYPE >::completer_impl () inline protected
References Modele_turbulence_scal_base::conductivite_turbulente(), Iterateur_VDF_base::evaluateur(), Modele_turbulence_scal_base::loi_paroi(), Modele_turbulence_scal_base::loi_paroi_non_nulle(), TRUST_Ref_Objet_U::valeur(), and Modele_turbulence_hyd_base::viscosite_turbulente().
completer_impl() [2/2]
template<typename OP_TYPE > template<Type_Operateur _TYPE_, typename EVAL_TYPE > std::enable_if_t< _TYPE_==Type_Operateur::Op_DIFT_FACE, void > Op_Diff_Dift_VDF< OP_TYPE >::completer_impl () inline protected
References Iterateur_VDF_base::evaluateur(), TRUST_Ref_Objet_U::valeur(), and Modele_turbulence_hyd_base::viscosite_turbulente().