TrioCFD: Champ_Proto Class Reference
Champ_Proto Class Reference abstract
#include <Champ_Proto.h>
Public Member Functions
int lire_dimension (Entree &, const Nom &)
int lire_dimension (int dim, const Nom &le_nom_)
Detailed Description
Tous les classes representant des champs derivent de Champ_proto. Champ_proto offre des methodes classiques sur des champs (min, max, norme, += ...) mais ne contient pas de membre representant des donnees. La plupart des methodes de Champ_proto font appel aux methodes de meme nom d'un objet DoubleTab renvoye par la methode abstraite de Champ_proto valeurs().
See also
Champ_base DoubleTab, Classe abstraite., Methode abstraite:, DoubleTab& valeurs()=0, const DoubleTab& valeurs() const
Constructor & Destructor Documentation
~Champ_Proto()
virtual Champ_Proto::~Champ_Proto () inline virtual
Member Function Documentation
valeurs() [1/4]
virtual DoubleTab & Champ_Proto::valeurs () pure virtual
Implemented in Champ_Fonc_reprise_IJK, Champ_Fonc_Tabule, Champ_Input_P0_Composite, Champ_Don_base, Champ_front_base, Champ_front_Parametrique, Champ_Inc_base, Champ_Parametrique, Champ_Fonc_MED, Champ_Fonc_reprise, Champ_Input_P0_Composite, Champ_Don_base, Champ_front_base, and Champ_front_Parametrique.
Referenced by Champ_base::affecter(), Champ_Fonc_Tabule::affecter_(), Champ_Face_PolyMAC::affecter_(), Champ_Face_PolyMAC_P0::affecter_(), Champ_Fonc_Face_PolyMAC::affecter_(), Champ_Face_VDF::affecter_(), Champ_Fonc_Face_VDF::affecter_(), Champ_P1_isoP1Bulle::affecter_(), Champ_Uniforme::affecter_(), Champ_Elem_PolyMAC_P0P1NC::affecter_(), Integrale_tps_produit_champs::ajoute_produit_tensoriel(), Op_Diff_VDF_base::ajoute_terme_pour_axi(), Op_Dift_VDF_base::ajoute_terme_pour_axi_turb(), Op_Diff_K_Eps_QC_VEF_Face::ajouter(), Source_Reaction_Particules_VDF::ajouter(), Source_Reaction_Particules_VEF::ajouter(), Iterateur_Source_EF_Som< _TYPE_ >::ajouter(), Source_Generique_P0_Elem::ajouter(), Source_Generique_Face_PolyMAC::ajouter(), Source_Generique_Face_PolyMAC_P0P1NC::ajouter(), Source_Generique_VEF::ajouter(), Terme_Source_Th_TdivU_VEF_Face::ajouter(), Source_QC_Gravite_VDF::ajouter_blocs(), Source_Generique_VDF_Face::ajouter_blocs(), Coalescence_bulles_1groupe_PolyMAC_P0::ajouter_blocs(), Coalescence_bulles_2groupes_PolyMAC_P0::ajouter_blocs(), Flux_2groupes_PolyMAC_P0::ajouter_blocs(), Nucleation_paroi_PolyMAC_P0::ajouter_blocs(), Rupture_bulles_1groupe_PolyMAC_P0::ajouter_blocs(), Rupture_bulles_2groupes_PolyMAC_P0::ajouter_blocs(), Variation_rho::ajouter_blocs(), Diffusion_supplementaire_echelle_temp_turb_PolyMAC_P0::ajouter_blocs(), Dissipation_WIT_PolyMAC_P0::ajouter_blocs(), Production_echelle_temp_taux_diss_turb_PolyMAC_P0::ajouter_blocs(), Production_energie_cin_turb_PolyMAC_P0::ajouter_blocs(), Production_HZDR_PolyMAC_P0::ajouter_blocs(), Production_WIT_PolyMAC_P0::ajouter_blocs(), Source_BIF_PolyMAC_P0::ajouter_blocs(), Source_Dissipation_HZDR_PolyMAC_P0::ajouter_blocs(), Source_Dissipation_energie_cin_turb::ajouter_blocs(), Production_echelle_temp_taux_diss_turb_VDF::ajouter_blocs(), Production_energie_cin_turb_VDF::ajouter_blocs(), Correction_Antal_PolyMAC_P0::ajouter_blocs(), Correction_Tomiyama_PolyMAC_P0::ajouter_blocs(), Dispersion_bulles_PolyMAC_P0::ajouter_blocs(), Frottement_interfacial_PolyMAC_P0::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::ajouter_blocs(), DP_Impose_PolyMAC_Face::ajouter_blocs(), Op_Evanescence_Homogene_Elem_base::ajouter_blocs(), Op_Evanescence_Homogene_Face_base::ajouter_blocs(), Source_Flux_interfacial_base::ajouter_blocs(), Correction_Antal_VDF::ajouter_blocs(), Dispersion_bulles_VDF::ajouter_blocs(), Frottement_interfacial_VDF::ajouter_blocs(), Portance_interfaciale_VDF::ajouter_blocs(), DP_Impose_VEF_Face::ajouter_blocs(), Masse_PolyMAC_P0_Face::ajouter_blocs(), Op_Evanescence_Homogene_PolyMAC_P0_Face::ajouter_blocs_aux(), Correction_Lubchenko_PolyMAC_P0::ajouter_blocs_BIF(), Correction_Lubchenko_PolyMAC_P0::ajouter_blocs_disp(), Correction_Lubchenko_PolyMAC_P0::ajouter_blocs_lift(), Op_Conv_EF::ajouter_contribution_sous_cond(), Source_Masse_Fluide_Dilatable_VEF::ajouter_eq_espece(), Op_Dift_VDF_Multi_inco_Elem::alpha_(), Op_Dift_VDF_Multi_inco_Elem_Axi::alpha_(), Op_Diff_Dift_VDF< OP_TYPE >::alpha_impl(), Convection_Diffusion_Espece_Multi_QC::assembler(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_blocs(), Convection_Diffusion_Espece_Multi_QC::assembler_blocs_avec_inertie(), Assembleur_P_PolyMAC_P0P1NC::assembler_continuite(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_impl(), Eval_Diff_K_Eps_VDF::associer(), Eval_Diff_K_Omega_VDF::associer(), Eval_Diff_K_Eps_VDF::associer_mvolumique(), Eval_Diff_K_Omega_VDF::associer_mvolumique(), Op_Evanescence_Homogene_PolyMAC_P0_Face::calc_vort_elem(), Transport_Interfaces_FT_Disc::calcul_effort_fluide_interface(), Modele_EASM_Baglietto_VEF::Calcul_F1(), Modele_Lam_Bremhorst_VEF::Calcul_F1(), Modele_EASM_Baglietto_VEF::Calcul_F1_BiK(), Modele_Lam_Bremhorst_VEF::Calcul_F1_BiK(), Modele_Jones_Launder_VDF::Calcul_F2(), Modele_EASM_Baglietto_VEF::Calcul_F2(), Modele_Jones_Launder_VEF::Calcul_F2(), Modele_Lam_Bremhorst_VEF::Calcul_F2(), Modele_Launder_Sharma_VEF::Calcul_F2(), Modele_Jones_Launder_VDF::Calcul_F2_BiK(), Modele_EASM_Baglietto_VEF::Calcul_F2_BiK(), Modele_Jones_Launder_VEF::Calcul_F2_BiK(), Modele_Lam_Bremhorst_VEF::Calcul_F2_BiK(), Modele_Launder_Sharma_VEF::Calcul_F2_BiK(), Champ_P1NC::calcul_h_conv(), Convection_Diffusion_Temperature::calcul_indic_pena_global(), Maillage_FT_Disc::calcul_indicatrice(), Transport_Interfaces_FT_Disc::calcul_indicatrice_faces(), Implicit_steady::calcul_mat_masse_diviser_par_dt_vdf(), Implicit_steady::calcul_mat_masse_diviser_par_dt_vef(), Traitement_particulier_NS_canal::calcul_reynolds_tau(), Traitement_particulier_NS_temperature_VEF::calcul_temperature(), Transport_Interfaces_FT_Disc::calcul_vitesse(), Perte_Charge_Singuliere::calculate_Q(), Champ_Q1NC_implementation::calcule_valeur_a_elem_compo(), Op_Diff_P1NC_barprim::calculer(), Milieu_base::calculer_alpha(), Masse_Multiphase::calculer_alpha_rho(), Energie_Multiphase::calculer_alpha_rho_e(), Energie_Multiphase::calculer_alpha_rho_h(), Op_Dift_EF_base::calculer_borne_locale(), Op_Dift_VDF_Face_base::calculer_borne_locale(), Op_Dift_VEF_base::calculer_borne_locale(), Equation_base::calculer_champ_conserve(), Navier_Stokes_FT_Disc::calculer_champ_forces_superficielles(), Transport_Interfaces_FT_Disc::calculer_composantes_connexes_pour_suppression(), Navier_Stokes_FT_Disc::calculer_delta_u_interface(), Navier_Stokes_FT_Disc::calculer_dI_dt(), Modele_turbulence_scal_Fluctuation_Temperature_W::calculer_diffusivite_turbulente(), Navier_Stokes_FT_Disc::calculer_div_normale_interface(), Op_Diff_K_Eps_Bas_Re_VDF_var_Elem::calculer_dt_stab(), Op_Diff_DG_base::calculer_dt_stab(), Op_Conv_EF::calculer_dt_stab(), Op_Diff_EF_base::calculer_dt_stab(), Op_Dift_EF_Q1::calculer_dt_stab(), Op_Conv_PolyMAC_iterateur_base::calculer_dt_stab(), Op_Diff_PolyMAC_base::calculer_dt_stab(), Op_Diff_PolyMAC_P0_Elem::calculer_dt_stab(), Op_Diff_PolyMAC_P0_Face::calculer_dt_stab(), Op_Diff_PolyMAC_P0P1NC_Elem::calculer_dt_stab(), Op_Diff_PolyMAC_P0P1NC_Face::calculer_dt_stab(), Op_Conv_VDF_base::calculer_dt_stab(), Op_Diff_VDF_Elem_base::calculer_dt_stab(), Op_Dift_Multiphase_VDF_Elem::calculer_dt_stab(), Op_Dift_Multiphase_VDF_Face::calculer_dt_stab(), Op_Diff_VEF_base::calculer_dt_stab(), Op_Dift_VEF_base::calculer_dt_stab(), Op_Dift_VDF_Face_base::calculer_dt_stab(), Op_Diff_VDF_base::calculer_dt_stab_(), Fluide_base::calculer_e_int(), Traitement_particulier_NS_EC::calculer_Ec(), Terme_Source_Coriolis_VDF_Face::calculer_force_de_Coriolis(), Convection_Diffusion_Temperature_FT_Disc::calculer_grad_t(), Navier_Stokes_FT_Disc::calculer_gradient_indicatrice(), Navier_Stokes_std::calculer_la_pression_en_pa(), Loi_Etat_Binaire_GP_QC::calculer_masse_volumique(), Loi_Etat_Multi_GP_QC::calculer_masse_volumique(), Loi_Etat_GP_QC::calculer_masse_volumique(), Traitement_particulier_NS_canal_VDF::calculer_moyenne_spatiale_vitesse_rho_mu(), Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_vitesse_rho_mu(), Convection_Diffusion_Temperature_FT_Disc::calculer_mpoint(), Loi_Etat_Binaire_GP_base::calculer_mu_sur_Sc(), Loi_Etat_Multi_GP_WC::calculer_mu_sur_Sc(), Fluide_base::calculer_nu(), Senseur_Interface::calculer_position(), Operateur_base::calculer_pour_post(), Op_Diff_negligeable::calculer_pour_post(), Op_Conv_PolyMAC_iterateur_base::calculer_pour_post(), Op_Conv_VDF_base::calculer_pour_post(), Op_Conv_VEF_base::calculer_pour_post(), Op_Diff_VEF_base::calculer_pour_post(), Op_Dift_VEF_base::calculer_pour_post(), Navier_Stokes_std::calculer_pression_hydrostatique(), Transport_Marqueur_FT::calculer_proprietes_fluide_pos_particules(), Convection_Diffusion_Temperature::calculer_rho_cp_T(), Paroi_ODVM_scal_VDF::calculer_scal(), Paroi_TBLE_scal_VDF::calculer_scal(), ParoiVEF_TBLE_scal::calculer_scal(), Transport_Interfaces_FT_Disc::calculer_scalaire_interpole(), Neumann_paroi_rayo_semi_transp_VDF::calculer_temperature_bord(), Fluide_base::calculer_temperature_multiphase(), Paroi_flux_impose_Rayo_transp::calculer_Teta_i_VDF(), Modele_turbulence_hyd_K_Eps::calculer_viscosite_turbulente(), Modele_turbulence_hyd_K_Eps_2_Couches::calculer_viscosite_turbulente(), Modele_turbulence_hyd_K_Eps_Bas_Reynolds::calculer_viscosite_turbulente(), Modele_turbulence_hyd_K_Eps_Bicephale::calculer_viscosite_turbulente(), Modele_turbulence_hyd_K_Eps_Realisable::calculer_viscosite_turbulente(), Modele_turbulence_hyd_K_Eps_Realisable_Bicephale::calculer_viscosite_turbulente(), Modele_turbulence_hyd_K_Omega::calculer_viscosite_turbulente(), Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl(), Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl_u_star(), Transport_Interfaces_FT_Disc::calculer_vitesse_transport_interpolee(), Discretisation_tools::cells_to_faces(), Discretisation_tools::cells_to_nodes(), Echange_global_impose::champ_exterieur(), Echange_couplage_thermique::champ_exterieur(), Fluide_reel_base::check_unknown_range(), Triple_Line_Model_FT_Disc::completer(), Op_Diff_PolyMAC_P0_base::completer(), Champ_Generique_Transformation::completer(), Fluide_Weakly_Compressible::completer(), Op_Ecart_type::completer(), Op_Moyenne::completer(), Convection_Diffusion_Temperature_FT_Disc::compute_divergence_free_velocity_extension(), Triple_Line_Model_FT_Disc::compute_TCL_fluxes_in_all_boundary_cells(), Transport_Marqueur_FT::construction_ensemble_proprietes(), Convection_Diffusion_Temperature_FT_Disc::correct_mpoint(), Fluide_base::creer_nu(), Convection_Diffusion_Temperature_FT_Disc::derivee_en_temps_inco(), Convection_Diffusion_Fluide_Dilatable_Proto::derivee_en_temps_inco_sans_solveur_masse_impl(), Op_Dift_EF_Q1::diffusivite(), Op_Dift_VEF_base::diffusivite(), Coalescence_bulles_1groupe_PolyMAC_P0::dimensionner_blocs(), Coalescence_bulles_2groupes_PolyMAC_P0::dimensionner_blocs(), Flux_2groupes_PolyMAC_P0::dimensionner_blocs(), Rupture_bulles_1groupe_PolyMAC_P0::dimensionner_blocs(), Rupture_bulles_2groupes_PolyMAC_P0::dimensionner_blocs(), Variation_rho::dimensionner_blocs(), Source_Diffusion_supplementaire_echelle_temp_turb::dimensionner_blocs(), Source_Dissipation_energie_cin_turb::dimensionner_blocs(), Source_Production_echelle_temp_taux_diss_turb::dimensionner_blocs(), Source_Production_energie_cin_turb::dimensionner_blocs(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::dimensionner_blocs(), Terme_Source_Decroissance_Radioactive_Elem_PolyMAC::dimensionner_blocs(), Source_Flux_interfacial_base::dimensionner_blocs(), Source_Travail_pression_Elem_base::dimensionner_blocs(), Op_Conv_VDF_base::dimensionner_blocs_elem(), Assembleur_P_PolyMAC_P0P1NC::dimensionner_continuite(), Convection_Diffusion_Temperature::ecrire_fichier_pena_th(), EcritureLectureSpecial::ecriture_special(), Champ_Elem_DG::eval_elem(), Discretisation_tools::faces_to_cells(), Champ_P1iP1B_implementation::filtrage(), Champ_P1NC_implementation::filtrer_L2(), Post_Processing_Hydrodynamic_Forces::find_neighboring_elements(), Champ_P1NC_implementation::fixer_nb_valeurs_nodales(), Sortie_libre_pression_imposee_QC::flux_impose(), Sortie_libre_pression_moyenne_imposee::flux_impose(), Sortie_libre_pression_imposee::flux_impose(), futur(), Champ_Generique_Divergence::get_champ(), Champ_Generique_Extraction::get_champ(), Champ_Generique_Gradient::get_champ(), Champ_Generique_Morceau_Equation::get_champ(), Champ_Generique_Reduction_0D::get_champ(), Champ_Generique_Transformation::get_champ(), Champ_Generique_modifier_pour_QC::get_champ(), Champ_Generique_Tparoi_VEF::get_champ(), Champ_Generique_Interpolation::get_champ_with_calculer_champ_post(), Transport_Interfaces_FT_Disc::get_compute_indicatrice_faces(), Champ_Generique_refChamp::get_ref_values(), Convection_Diffusion_Temperature::get_time_factor(), Transport_Interfaces_FT_Disc::get_update_distance_interface_faces(), Transport_Interfaces_FT_Disc::get_update_distance_interface_sommets(), Sortie_libre_Gradient_Pression_impose::grad_P_imp(), Transport_Interfaces_FT_Disc::impr_effort_fluide_interface(), Champ_implementation_P0::imprime_P0(), Champ_P1NC_implementation::imprime_P1NC(), Champ_Q4_implementation::imprime_Q4(), Paroi_ODVM_scal_VDF::init_lois_paroi(), Paroi_TBLE_scal_VDF::init_lois_paroi(), Fluide_Dilatable_base::initialiser(), Fluide_reel_base::initialiser(), MuLambda_TBLE_Fcts_T::initialiser(), Champ_Fonc_Interp::initialiser(), Loi_Etat_rhoT_GP_QC::initialiser_rho(), Transport_Interfaces_FT_Disc::interpoler_vitesse_face(), EcritureLectureSpecial::lecture_special(), Fluide_Quasi_Compressible::lire_motcle_non_standard(), Op_EF_base::marque_elem(), Convection_Diffusion_Temperature_FT_Disc::mettre_a_jour(), Transport_Interfaces_FT_Disc::mettre_a_jour(), Aire_interfaciale::mettre_a_jour(), Fluide_reel_base::mettre_a_jour(), Estimateur_Aposteriori_P0_VEF::mettre_a_jour(), Modele_turbulence_scal_LES_dyn_VDF::mettre_a_jour(), Modele_turbulence_scal_Prandtl::mettre_a_jour(), PlaqThVDF::mettre_a_jour(), Op_Conv_VDF_base::mettre_a_jour(), Integrale_tps_Champ::mettre_a_jour_integrale(), Milieu_composite::mettre_a_jour_tabs(), Iterateur_PolyMAC_Elem< _TYPE_ >::modifier_flux(), Op_EF_base::modifier_flux(), Op_VEF_Face::modifier_flux(), Assembleur_P_PolyMAC_P0P1NC::modifier_secmem_pour_incr_p(), Transport_Interfaces_FT_Disc::modifier_vpoint_pour_imposer_vit(), Discretisation_tools::nodes_to_cells(), passe(), Convection_Diffusion_Temperature::penalisation_L2(), Postraitement::postprocess_field_values(), Transport_Interfaces_FT_Disc::preparer_calcul(), Convection_Diffusion_Concentration_FT_Disc::ramasse_miette_simple(), Convection_Diffusion_Concentration_Turbulent_FT_Disc::ramasse_miette_simple(), Transport_Interfaces_FT_Disc::ramasse_miettes(), Solid_Particle_sphere::readOn(), Topologie_Maillage_FT::remailler_interface(), Op_Diff_VEF_base::remplir_nu(), Op_Diff_EF::remplir_nu(), Op_Dift_EF_Q1::remplir_nu(), Champ_Fonc_reprise_IJK::reprendre_IJK(), Source_PDF_EF::rotate_imposed_velocity(), Op_Diff_Dift_VDF< OP_TYPE >::tab_alpha_impl(), Transport_Interfaces_FT_Disc::test_suppression_interfaces_sous_domaine(), Remailleur_Collision_FT_Juric::traite_RuptureCoalescenceInterfaces(), Remailleur_Collision_FT_Thomas::traite_RuptureCoalescenceInterfaces_Conservatif(), Transport_Marqueur_FT::transformation(), Transport_Interfaces_FT_Disc::transporter_sans_changement_topologie(), Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_elem(), Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_gradU_elem_P1(), Champ_front_debit_massique::update_coeff(), Champ_Fonc_Interp::update_fields(), Op_Diff_DG_base::update_nu(), Op_Diff_PolyMAC_base::update_nu(), Op_Diff_PolyMAC_P0_base::update_nu(), Op_Diff_PolyMAC_P0P1NC_base::update_nu(), Milieu_base::update_rho_cp(), Fluide_Dilatable_base::update_rho_cp(), Champ_implementation_P0::valeur_a_elem(), Champ_implementation_sommet::valeur_a_elem(), Champ_Q4_implementation::valeur_a_elem(), Champ_P1NC_implementation::valeur_a_elem(), Champ_Q1NC_implementation::valeur_a_elem(), Champ_Q4_implementation::valeur_a_elem_compo(), Champ_Face_VDF_implementation::valeur_a_elem_compo(), Champ_P1NC_implementation::valeur_a_elem_compo(), Champ_implementation_P0::valeur_a_elem_compo(), Champ_implementation_sommet::valeur_a_elem_compo(), Champ_P1NC_implementation::valeur_a_sommet_compo(), Champ_implementation_sommet::valeur_aux_bords(), Champ_base::valeur_aux_bords(), Champ_implementation_P0::valeur_aux_centres_de_gravite(), Champ_P1NC_implementation::valeur_aux_centres_de_gravite(), Champ_Elem_DG::valeur_aux_elems(), Champ_Fonc_P1_DG::valeur_aux_elems(), Champ_Q4_implementation::valeur_aux_elems(), Champ_P1NC_implementation::valeur_aux_elems(), Champ_Q1NC_implementation::valeur_aux_elems(), Champ_implementation_P0::valeur_aux_elems(), Champ_implementation_sommet::valeur_aux_elems(), Champ_Fonc_Face_PolyMAC::valeur_aux_elems(), Champ_Q4_implementation::valeur_aux_elems_compo(), Champ_P1NC_implementation::valeur_aux_elems_compo(), Champ_Q1NC_implementation::valeur_aux_elems_compo(), Champ_implementation_P0::valeur_aux_elems_compo(), Champ_implementation_sommet::valeur_aux_elems_compo(), Champ_Face_PolyMAC::valeur_aux_elems_compo(), Champ_P1NC_implementation::valeur_aux_elems_compo_smooth(), Champ_P1NC_implementation::valeur_aux_elems_smooth(), Champ_Face_PolyMAC::valeur_aux_faces(), Champ_Face_PolyMAC_P0P1NC::valeur_aux_faces(), Champ_Fonc_Face_PolyMAC::valeur_aux_faces(), Champ_Q4_implementation::valeur_aux_sommets(), Champ_Face_VDF_implementation::valeur_aux_sommets(), Champ_P1NC_implementation::valeur_aux_sommets(), Champ_Q4_implementation::valeur_aux_sommets_compo(), Champ_P1NC_implementation::valeur_aux_sommets_compo(), Champ_implementation_P0::valeur_aux_sommets_compo_impl(), Champ_implementation_sommet::valeur_aux_sommets_compo_impl(), Champ_implementation_P0::valeur_aux_sommets_impl(), Champ_implementation_sommet::valeur_aux_sommets_impl(), Fluide_base::verifier_coherence_champs(), Ecrire_fichier_xyz_valeur::write_fields(), Fluide_Dilatable_base::write_mean_edo(), and Fluide_Weakly_Compressible::write_mean_edo().
valeurs() [2/4]
virtual const DoubleTab & Champ_Proto::valeurs () const pure virtual
Implemented in Champ_Fonc_reprise_IJK, Champ_Fonc_Tabule, Champ_Input_P0_Composite, Champ_Don_base, Champ_front_base, Champ_front_Parametrique, Champ_Inc_base, Champ_Parametrique, Champ_Fonc_MED, Champ_Fonc_reprise, Champ_Input_P0_Composite, Champ_Don_base, Champ_front_base, and Champ_front_Parametrique.
valeurs() [3/4]
virtual DoubleTab & Champ_Proto::valeurs (double temps) inline virtual
Reimplemented in Champ_Input_P0_Composite, Champ_Don_base, Champ_front_base, Champ_front_Parametrique, Champ_Inc_base, and Champ_Parametrique.
References valeurs().
Referenced by valeurs().
valeurs() [4/4]
virtual const DoubleTab & Champ_Proto::valeurs (double temps) const inline virtual
Reimplemented in Champ_Input_P0_Composite, Champ_Don_base, Champ_front_base, Champ_front_Parametrique, Champ_Inc_base, and Champ_Parametrique.
References valeurs().
Referenced by valeurs().
futur() [1/2]
virtual DoubleTab & Champ_Proto::futur (int i = 1) inline virtual
Reimplemented in Champ_Inc_base.
References valeurs().
futur() [2/2]
virtual const DoubleTab & Champ_Proto::futur (int i = 1) const inline virtual
Reimplemented in Champ_Inc_base.
References valeurs().
passe() [1/2]
virtual DoubleTab & Champ_Proto::passe (int i = 1) inline virtual
Reimplemented in Champ_Inc_base.
References valeurs().
Referenced by Terme_Source_Qdm_VDF_Face::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_P0_Face::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Face::ajouter_blocs(), Coalescence_bulles_1groupe_PolyMAC_P0::ajouter_blocs(), Coalescence_bulles_2groupes_PolyMAC_P0::ajouter_blocs(), Flux_2groupes_PolyMAC_P0::ajouter_blocs(), Injection_QDM_nulle_PolyMAC_P0::ajouter_blocs(), Nucleation_paroi_PolyMAC_P0::ajouter_blocs(), Rupture_bulles_1groupe_PolyMAC_P0::ajouter_blocs(), Rupture_bulles_2groupes_PolyMAC_P0::ajouter_blocs(), Source_injection_masse_base::ajouter_blocs(), Injection_QDM_nulle_VDF::ajouter_blocs(), Dissipation_WIT_PolyMAC_P0::ajouter_blocs(), Production_echelle_temp_taux_diss_turb_PolyMAC_P0::ajouter_blocs(), Production_energie_cin_turb_PolyMAC_P0::ajouter_blocs(), Production_HZDR_PolyMAC_P0::ajouter_blocs(), Production_WIT_PolyMAC_P0::ajouter_blocs(), Source_BIF_PolyMAC_P0::ajouter_blocs(), Source_Dissipation_HZDR_PolyMAC_P0::ajouter_blocs(), Source_Dissipation_energie_cin_turb::ajouter_blocs(), Production_echelle_temp_taux_diss_turb_VDF::ajouter_blocs(), Production_energie_cin_turb_VDF::ajouter_blocs(), Correction_Antal_PolyMAC_P0::ajouter_blocs(), Correction_Tomiyama_PolyMAC_P0::ajouter_blocs(), Dispersion_bulles_PolyMAC_P0::ajouter_blocs(), Frottement_interfacial_PolyMAC_P0::ajouter_blocs(), Portance_interfaciale_PolyMAC_P0::ajouter_blocs(), Terme_Boussinesq_PolyMAC_Face::ajouter_blocs(), Terme_Source_Qdm_Face_PolyMAC_P0P1NC::ajouter_blocs(), Op_Evanescence_Homogene_Face_base::ajouter_blocs(), Source_Flux_interfacial_base::ajouter_blocs(), Source_Force_Tchen_base::ajouter_blocs(), Correction_Antal_VDF::ajouter_blocs(), Dispersion_bulles_VDF::ajouter_blocs(), Frottement_interfacial_VDF::ajouter_blocs(), Portance_interfaciale_VDF::ajouter_blocs(), Op_Conv_Amont_VPoly_VDF_Face::ajouter_blocs(), Masse_PolyMAC_P0_Face::ajouter_blocs(), Masse_VDF_Face::ajouter_blocs(), Op_Evanescence_Homogene_PolyMAC_P0_Face::ajouter_blocs_aux(), Force_Tchen_PolyMAC_P0::ajouter_blocs_aux(), Correction_Lubchenko_PolyMAC_P0::ajouter_blocs_BIF(), Correction_Lubchenko_PolyMAC_P0::ajouter_blocs_disp(), Op_Diff_PolyMAC_P0P1NC_Elem::ajouter_blocs_ext(), Correction_Lubchenko_PolyMAC_P0::ajouter_blocs_lift(), Op_Evanescence_Homogene_Face_base::calc_vort_faces(), Op_Dift_Multiphase_VDF_Face::calculer_dt_stab(), Paroi_frottante_simple::me_calculer(), Cond_lim_k_complique_transition_flux_nul_demi::me_calculer(), Cond_lim_k_simple_flux_nul::me_calculer(), Champ_Fonc_Elem_PolyMAC_P0_rot::me_calculer_2D(), Champ_Fonc_Elem_PolyMAC_P0_rot::me_calculer_3D(), Portance_interfaciale_PolyMAC_P0::mettre_a_jour(), Aire_interfaciale::mettre_a_jour(), Transport_turbulent_GGDH_WIT::modifier_mu(), Transport_turbulent_SGDH_WIT::modifier_mu(), Transport_turbulent_aire_interfaciale::modifier_mu(), Transport_turbulent_GGDH::modifier_mu(), Transport_turbulent_Prandtl::modifier_mu(), Transport_turbulent_SGDH::modifier_mu(), Op_Diff_Turbulent_PolyMAC_P0_Face::modifier_mu(), and Viscosite_turbulente_sato::reynolds_stress().
passe() [2/2]
virtual const DoubleTab & Champ_Proto::passe (int i = 1) const inline virtual
Reimplemented in Champ_Inc_base.
References valeurs().
lire_dimension() [1/2]
int Champ_Proto::lire_dimension (Entree & is, const Nom & le_nom_)
Verification de la dimension du champ Renvoie la dimension du champ.
Returns
(int) la dimension du champ
References lire_dimension().
Referenced by lire_dimension(), Champ_Fonc_Tabule::readOn(), Champ_front_bruite::readOn(), Champ_front_fonc_pois_ipsn::readOn(), Champ_front_fonc_pois_tube::readOn(), Champ_Front_Fonction::readOn(), Champ_front_lu::readOn(), Champ_front_t::readOn(), Champ_front_Tabule::readOn(), Champ_front_Tabule_lu::readOn(), Champ_front_txyz::readOn(), Champ_front_uniforme::readOn(), Champ_Tabule_lu::readOn(), Champ_Don_Fonc_xyz::readOn(), Champ_Don_lu::readOn(), Champ_Fonc_Morceaux::readOn(), Champ_Fonc_t::readOn(), Champ_Fonc_Tabule_Morceaux::readOn(), champ_init_canal_sinal::readOn(), Champ_Tabule_Temps::readOn(), Champ_Uniforme::readOn(), Champ_Uniforme_Morceaux::readOn(), Champ_Uniforme_Morceaux_Tabule_Temps::readOn(), Init_par_partie::readOn(), Champ_front_softanalytique::readOn(), and Champ_front_synt::readOn().
lire_dimension() [2/2]
int Champ_Proto::lire_dimension (int dim, const Nom & le_nom_)
Verification de la dimension du champ Renvoie la dimension du champ.
Returns
(int) la dimension du champ
References Process::exit().
operator()() [1/4]
double Champ_Proto::operator() (int i, int j) const delete
operator()() [2/4]
double & Champ_Proto::operator() (int i, int j) delete
operator()() [3/4]
double Champ_Proto::operator() (int i) const delete
operator()() [4/4]
double & Champ_Proto::operator() (int i) delete