TrioCFD: Noms Class Reference
Noms Class Reference
#include <Noms.h>
Public Member Functions
const Type_info * get_info () const override
Noms (int)
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from TRUST_Vector< Nom >
Sortie & printOn (Sortie &s) const override
Entree & readOn (Entree &s) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Noms() [1/2]
Noms::Noms ()
~Noms()
Noms::~Noms ()
Noms() [2/2]
Noms::Noms (int i) inline
Constructeur Construit un tableau de i noms.
Parameters
(int i) nombre d'elements du tableau
Member Function Documentation
cree_instance()
Objet_U * Noms::cree_instance () static
taille_memoire()
unsigned Noms::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Noms::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Noms::info () static
get_info()
const Type_info * Noms::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
Noms & Noms::self_cast (Objet_U & r) static
self_cast() [2/2]
const Noms & Noms::self_cast (const Objet_U & r) static
printOn()
Sortie & Noms::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
References printOn().
Referenced by printOn().
readOn()
Entree & Noms::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
References readOn().
Referenced by readOn().
rang()
int Noms::rang (const char *const ch) const
References TRUST_Vector< Nom >::size().
Referenced by contient_(), Sondes::get_from_cache(), Domaine_Cl_EF::imposer_symetrie_partiellement(), Create_domain_from_sub_domain::interpreter_(), Postraitement::lire_motcle_non_standard(), Probleme_FT_Disc_gen::lire_solved_equations(), Probleme_FTD_IJK_base::lire_solved_equations(), Probleme_base::read_optional_equations(), search(), and Parser::searchVar().
contient_()
int Noms::contient_ (const char *const ch) const
References rang().
Referenced by Partitionneur_base_32_64< _SIZE_ >::calculer_graphe_connexions_periodiques(), Convection_Diffusion_Temperature_FT_Disc::completer(), Partitionneur_Sous_Domaines::construire_partition(), Partitionneur_base_32_64< _SIZE_ >::corriger_sommets_bord(), Champ_Fonc_MED::creer(), Probleme_base::discretiser(), Format_Post_Lata::ecrire_champ(), Format_Post_Lata::ecrire_domaine_low_level(), Format_Post_CGNS::ecrire_entete(), IJK_Ghost_Fluid_Fields::get_IJK_field(), IJK_Thermal_base::get_IJK_field_vector(), IJK_Ghost_Fluid_Fields::get_IJK_field_vector(), IJK_Thermal_base::has_champ(), IJK_Ghost_Fluid_Fields::has_champ(), and Postraitement::init().
search()
int Noms::search (const Nom & t) const
References Nom::getString(), and rang().
Referenced by Interprete_bloc::ajouter(), Source_Robin_Scalaire::ajouter(), LireMED_32_64< _SIZE_ >::fill_frontieres(), Interprete_bloc::objet_local(), and Interprete_bloc::objet_local_existant().
search_without_checking_Motcle()
int Noms::search_without_checking_Motcle (const Nom & t) const
References Nom::getString(), TRUST_Vector< Nom >::operator[](), and TRUST_Vector< Nom >::size().
Member Data Documentation
info_obj
const Type_info Noms::info_obj static