TrioCFD: Pb_Hydraulique_Turbulent_ALE Class Reference
Pb_Hydraulique_Turbulent_ALE Class Reference
#include <Pb_Hydraulique_Turbulent_ALE.h>
Public Member Functions
void associer_milieu_base (const Milieu_base &) override
void associer_sch_tps_base (const Schema_Temps_base &) override
const Equation_base & equation (int) const override
Equation_base & equation (int) override
const Type_info * get_info () const override
int nombre_d_equations () const override
int verifier () override
const Champ_Fonc_base & viscosite_turbulente () const
void associer_milieu_base (const Milieu_base &) override
Equation_base & equation (int) override
const Type_info * get_info () const override
int nombre_d_equations () const override
int verifier () override
const Type_info * get_info () const override
Public Member Functions inherited from Probleme_base
void abortTimeStep () override
int associer_ (Objet_U &) override
virtual void associer_domaine (const Domaine &)
virtual void associer_milieu_base (const Milieu_base &)
virtual void associer_sch_tps_base (const Schema_Temps_base &)
virtual double calculer_pas_de_temps () const
virtual void completer ()
double computeTimeStep (bool &stop) const override
const Discretisation_base & discretisation () const
virtual void discretiser (Discretisation_base &)
Domaine & domaine ()
const Domaine & domaine () const
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
Equation_base & equation (const Nom &)
const Equation_base & equation (const Nom &) const
TRUST_Ref< Field_base * > findInputField (const Nom &name) const override
virtual void finir ()
double futureTime () const override
const Type_info * get_info () const override
void getInputFieldsNames (Noms &noms) const override
void getOutputFieldsNames (Noms &noms) const override
virtual void imprimer (Sortie &os) const
void initialize () override
bool initTimeStep (double dt) override
bool isStationary () const override
bool iterateTimeStep (bool &converged) override
int limpr () const override
int lsauv () const override
virtual void mettre_a_jour (double temps)
virtual Milieu_base & milieu ()
virtual const Milieu_base & milieu () const
int postraiter (int force=1) override
double presentTime () const override
int reprendre (Entree &) override
void resetTime (double time) override
int sauvegarder (Sortie &) const override
Schema_Temps_base & schema_temps ()
const Schema_Temps_base & schema_temps () const
void terminate () override
bool updateGivenFields () override
void validateTimeStep () override
virtual int verifier ()
Public Member Functions inherited from Probleme_U
virtual void abortTimeStep ()
virtual double computeTimeStep (bool &stop) const
virtual TRUST_Ref< Field_base * > findInputField (const Nom &name) const
virtual double futureTime () const
const Type_info * get_info () const override
virtual void getInputFieldsNames (Noms &noms) const
virtual void getOutputFieldsNames (Noms &noms) const
virtual void initialize ()
virtual bool initTimeStep (double dt)
virtual bool isStationary () const
virtual bool iterateTimeStep (bool &converged)
const Nom & le_nom () const override
void nommer (const Nom &name) override
virtual int postraiter (int force=1)
virtual double presentTime () const
virtual void resetTime (double time)
virtual bool run ()
virtual bool runUntil (double time)
virtual void terminate ()
virtual bool updateGivenFields ()
virtual void validateTimeStep ()
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
lequel on resout les equations de Navier Stokes en regime turbulent
pour un fluide incompressible et en maillage mobile (ALE)
La formulation est de type vitesse pression
See also
Pb_Fluide_base Navier_Stokes_Turbulent_ALE Pb_Hydraulique
Constructor & Destructor Documentation
Pb_Hydraulique_Turbulent_ALE()
Pb_Hydraulique_Turbulent_ALE::Pb_Hydraulique_Turbulent_ALE ()
~Pb_Hydraulique_Turbulent_ALE()
Pb_Hydraulique_Turbulent_ALE::~Pb_Hydraulique_Turbulent_ALE ()
Member Function Documentation
cree_instance()
Objet_U * Pb_Hydraulique_Turbulent_ALE::cree_instance () static
taille_memoire()
unsigned Pb_Hydraulique_Turbulent_ALE::taille_memoire () const override virtual
Reimplemented from Pb_Hydraulique_Turbulent.
duplique()
int Pb_Hydraulique_Turbulent_ALE::duplique () const override virtual
Reimplemented from Pb_Hydraulique_Turbulent.
info()
const Type_info * Pb_Hydraulique_Turbulent_ALE::info () static
get_info()
const Type_info * Pb_Hydraulique_Turbulent_ALE::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Pb_Hydraulique_Turbulent.
self_cast() [1/2]
Pb_Hydraulique_Turbulent_ALE & Pb_Hydraulique_Turbulent_ALE::self_cast (Objet_U & r) static
self_cast() [2/2]
const Pb_Hydraulique_Turbulent_ALE & Pb_Hydraulique_Turbulent_ALE::self_cast (const Objet_U & r) static
printOn()
Sortie & Pb_Hydraulique_Turbulent_ALE::printOn (Sortie & os) const override protected virtual
Simple appel a: Pb_Fluide_base::printOn(Sortie&) Ecrit le probleme sur un flot de sortie.
Parameters
(Sortie& os) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Pb_Hydraulique_Turbulent.
References Pb_Hydraulique_Turbulent::printOn().
readOn()
Entree & Pb_Hydraulique_Turbulent_ALE::readOn (Entree & is) override protected virtual
Simple appel a: Pb_Fluide_base::readOn(Entree&) Lit le probleme a partir d'un flot d'entree.
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Pb_Hydraulique_Turbulent.
References Pb_Hydraulique_Turbulent::readOn().
nombre_d_equations()
int Pb_Hydraulique_Turbulent_ALE::nombre_d_equations () const override virtual
Renvoie le nombre d'equation, Renvoie 1 car il y a seulement 1 equation a un probleme.
hydraulique turbulent: l'equation de Navier Stokes avec Turbulence
Returns
(int) le nombre d'equation
Reimplemented from Pb_Hydraulique_Turbulent.
equation() [1/2]
const Equation_base & Pb_Hydraulique_Turbulent_ALE::equation (int i) const override virtual
Renvoie l' equation d'hydraulique de type Navier_Stokes_Turbulent si i=0 sort (exit) sinon.
(version const)
Parameters
(int i) l'index de l'equation a renvoyer
Returns
(Equation_base&) l'equation d'hydraulique de type Navier_Stokes_Turbulent
Reimplemented from Pb_Hydraulique_Turbulent.
References eq_hydraulique, and Process::exit().
equation() [2/2]
Equation_base & Pb_Hydraulique_Turbulent_ALE::equation (int i) override virtual
Renvoie l' equation d'hydraulique de type Navier_Stokes_Turbulent si i=0 sort (exit) sinon.
Parameters
(int i) l'index de l'equation a renvoyer
Returns
(Equation_base&) l'equation d'hydraulique de type Navier_Stokes_Turbulent
Reimplemented from Pb_Hydraulique_Turbulent.
References eq_hydraulique, and Process::exit().
viscosite_turbulente()
const Champ_Fonc_base & Pb_Hydraulique_Turbulent_ALE::viscosite_turbulente () const inline
Renvoie le champ representant la viscosite turbulente du probleme.
Returns
(Champ_Fonc_base&) le champ representant la viscosite turbulente
References eq_hydraulique, and Navier_Stokes_Turbulent_ALE::viscosite_turbulente().
associer_milieu_base()
void Pb_Hydraulique_Turbulent_ALE::associer_milieu_base (const Milieu_base & mil) override virtual
Associe le milieu au probleme.
Le milieu doit etre de type fluide incompressible.
Parameters
(Milieu_base& mil) le milieu physique a associer au probleme
Exceptions
le milieu n'est pas du type Fluide_Incompressible
Reimplemented from Pb_Hydraulique_Turbulent.
References Navier_Stokes_std::associer_milieu_base(), eq_hydraulique, Process::exit(), and Objet_U::que_suis_je().
verifier()
int Pb_Hydraulique_Turbulent_ALE::verifier () override virtual
Teste la compatibilite des equations de convection-diffusion et de l'hydraulique.
Le test se fait sur les conditions aux limites discretisees de chaque equation. Appel la fonction de librairie hors classe: tester_compatibilite_hydr_turb(const Domaine_Cl_dis_base&)
Returns
(int) code de retour propage
Reimplemented from Pb_Hydraulique_Turbulent.
References Equation_base::domaine_Cl_dis(), eq_hydraulique, Modele_turbulence_hyd_RANS_K_Eps_base::eqn_transp_K_Eps(), Navier_Stokes_Turbulent_ALE::get_modele(), and TRUST_Ref_Objet_U::valeur().
associer_sch_tps_base()
void Pb_Hydraulique_Turbulent_ALE::associer_sch_tps_base (const Schema_Temps_base & un_schema_en_temps) override virtual
Associe un schema en temps au probleme.
Associe ensuite le schema en temps a toutes les equations du probleme.
Parameters
(Schema_Temps_base& un_schema_en_temps) le schema en temps a associer
Reimplemented from Probleme_base.
References Probleme_base::associer_sch_tps_base(), Process::exit(), Probleme_base::le_schema_en_temps_, Objet_U::que_suis_je(), Schema_Implicite_base::solveur(), TRUST_Deriv< _CLASSE_ >::valeur(), and TRUST_Ref< _CLASSE_ >::valeur().
Member Data Documentation
info_obj
const Type_info Pb_Hydraulique_Turbulent_ALE::info_obj static
eq_hydraulique
Navier_Stokes_Turbulent_ALE Pb_Hydraulique_Turbulent_ALE::eq_hydraulique protected
Referenced by associer_milieu_base(), equation(), verifier(), and viscosite_turbulente().