TrioCFD: Tensor Class Reference
Tensor Class Reference
#include <keras_model.h>
Constructor & Destructor Documentation
Tensor() [1/5]
Tensor::Tensor () inline
Referenced by Unpack().
Tensor() [2/5]
Tensor::Tensor (int i) inline
References Resize().
Tensor() [3/5]
Tensor::Tensor (int i, int j) inline
References Resize().
Tensor() [4/5]
Tensor::Tensor (int i, int j, int k) inline
References Resize().
Tensor() [5/5]
Tensor::Tensor (int i, int j, int k, int l) inline
References Resize().
Member Function Documentation
Resize() [1/4]
void Tensor::Resize (int i) inline
References data_, and dims_.
Referenced by KerasLayerDense::LoadLayer(), KerasLayerConvolution2d::LoadLayer(), KerasLayerLSTM::LoadLayer(), KerasLayerEmbedding::LoadLayer(), and Tensor().
Resize() [2/4]
void Tensor::Resize (int i, int j) inline
References data_, and dims_.
Resize() [3/4]
void Tensor::Resize (int i, int j, int k) inline
References data_, and dims_.
Resize() [4/4]
void Tensor::Resize (int i, int j, int k, int l) inline
References data_, and dims_.
Flatten()
void Tensor::Flatten () inline
References dims_.
Referenced by KerasLayerFlatten::Apply().
operator()() [1/5]
float & Tensor::operator() (int i) inline
References data_, and dims_.
operator()() [2/5]
float & Tensor::operator() (int i, int j) inline
References data_, and dims_.
operator()() [3/5]
float Tensor::operator() (int i, int j) const inline
References data_, and dims_.
operator()() [4/5]
float & Tensor::operator() (int i, int j, int k) inline
References data_, and dims_.
operator()() [5/5]
float & Tensor::operator() (int i, int j, int k, int l) inline
References data_, and dims_.
Fill()
void Tensor::Fill (float value) inline
References data_.
Referenced by KerasLayerLSTM::Apply().
Unpack()
Tensor Tensor::Unpack (int row) const inline
References data_, dims_, and Tensor().
Referenced by Select().
Select()
Tensor Tensor::Select (int row) const inline
References dims_, and Unpack().
Referenced by KerasLayerLSTM::Apply().
operator+()
Tensor Tensor::operator+ (const Tensor & other) inline
References data_, and dims_.
Multiply()
Tensor Tensor::Multiply (const Tensor & other) inline
References data_, and dims_.
Dot()
Tensor Tensor::Dot (const Tensor & other) inline
References dims_.
Print()
void Tensor::Print () inline
References dims_.
PrintShape()
void Tensor::PrintShape () inline
References dims_.
Member Data Documentation
dims_
std::vector<int> Tensor::dims_
Referenced by KerasLayerDense::Apply(), KerasLayerConvolution2d::Apply(), KerasLayerMaxPooling2d::Apply(), KerasLayerLSTM::Apply(), KerasLayerEmbedding::Apply(), Dot(), Flatten(), Multiply(), operator()(), operator+(), Print(), PrintShape(), Resize(), Select(), and Unpack().
data_
std::vector<float> Tensor::data_
Referenced by KerasLayerActivation::Apply(), KerasLayerElu::Apply(), KerasLayerLSTM::Apply(), KerasLayerEmbedding::Apply(), Fill(), KerasLayerDense::LoadLayer(), KerasLayerConvolution2d::LoadLayer(), KerasLayerLSTM::LoadLayer(), KerasLayerEmbedding::LoadLayer(), Multiply(), operator()(), operator+(), Resize(), and Unpack().