TrioCFD: Modele_F1F2FMU_unitaire_VDF Class Reference
Modele_F1F2FMU_unitaire_VDF Class Reference
#include <Modele_F1F2FMU_unitaire_VDF.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Modele_Jones_Launder_VDF
const Type_info * get_info () const override
Public Member Functions inherited from Modele_Fonc_Bas_Reynolds_Base
const Type_info * get_info () const override
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Modele_Jones_Launder_VDF
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Modele_Fonc_Bas_Reynolds_Base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Modele_F1F2FMU_unitaire_VDF()
Modele_F1F2FMU_unitaire_VDF::Modele_F1F2FMU_unitaire_VDF ()
~Modele_F1F2FMU_unitaire_VDF()
Modele_F1F2FMU_unitaire_VDF::~Modele_F1F2FMU_unitaire_VDF ()
Member Function Documentation
cree_instance()
Objet_U * Modele_F1F2FMU_unitaire_VDF::cree_instance () static
taille_memoire()
unsigned Modele_F1F2FMU_unitaire_VDF::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Modele_F1F2FMU_unitaire_VDF::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Modele_F1F2FMU_unitaire_VDF::info () static
get_info()
const Type_info * Modele_F1F2FMU_unitaire_VDF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
Modele_F1F2FMU_unitaire_VDF & Modele_F1F2FMU_unitaire_VDF::self_cast (Objet_U & r) static
self_cast() [2/2]
const Modele_F1F2FMU_unitaire_VDF & Modele_F1F2FMU_unitaire_VDF::self_cast (const Objet_U & r) static
printOn()
Sortie & Modele_F1F2FMU_unitaire_VDF::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
References Modele_Jones_Launder_VDF::printOn().
readOn()
Entree & Modele_F1F2FMU_unitaire_VDF::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
References Modele_Jones_Launder_VDF::readOn().
Calcul_Fmu()
DoubleTab & Modele_F1F2FMU_unitaire_VDF::Calcul_Fmu (DoubleTab & Fmu, const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const DoubleTab & K_eps_Bas_Re, const Champ_Don_base & ch_visco) const override virtual
Implements Modele_Fonc_Bas_Reynolds_Base.
Calcul_F1()
DoubleTab & Modele_F1F2FMU_unitaire_VDF::Calcul_F1 (DoubleTab & F1, const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const DoubleTab & P, const DoubleTab & K_eps_Bas_Re, const Champ_base & ch_visco) const override virtual
Implements Modele_Fonc_Bas_Reynolds_Base.
Calcul_F2()
DoubleTab & Modele_F1F2FMU_unitaire_VDF::Calcul_F2 (DoubleTab & F2, DoubleTab & D, const Domaine_dis_base & domaine_dis, const DoubleTab & K_eps_Bas_Re, const Champ_base & ch_visco) const override virtual
Implements Modele_Fonc_Bas_Reynolds_Base.
Calcul_F1_BiK()
DoubleTab & Modele_F1F2FMU_unitaire_VDF::Calcul_F1_BiK (DoubleTab & F1, const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const DoubleTab & P, const DoubleTab & K_Bas_Re, const DoubleTab & eps_Bas_Re, const Champ_base & ch_visco) const override virtual
Implements Modele_Fonc_Bas_Reynolds_Base.
Calcul_F2_BiK()
DoubleTab & Modele_F1F2FMU_unitaire_VDF::Calcul_F2_BiK (DoubleTab & F2, DoubleTab & D, const Domaine_dis_base & domaine_dis, const DoubleTab & K_Bas_Re, const DoubleTab & eps_Bas_Re, const Champ_base & ch_visco) const override virtual
Implements Modele_Fonc_Bas_Reynolds_Base.
Calcul_Fmu_BiK()
DoubleTab & Modele_F1F2FMU_unitaire_VDF::Calcul_Fmu_BiK (DoubleTab & Fmu, const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const DoubleTab & K_Bas_Re, const DoubleTab & eps_Bas_Re, const Champ_Don_base & ch_visco) const override virtual
Implements Modele_Fonc_Bas_Reynolds_Base.
References TRUSTVect< _TYPE_, _SIZE_ >::mp_max_vect(), and TRUSTVect< _TYPE_, _SIZE_ >::mp_min_vect().
associer()
void Modele_F1F2FMU_unitaire_VDF::associer (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis) override virtual
Implements Modele_Fonc_Bas_Reynolds_Base.
lire()
Entree & Modele_F1F2FMU_unitaire_VDF::lire (const Motcle & , Entree & is)
Member Data Documentation
info_obj
const Type_info Modele_F1F2FMU_unitaire_VDF::info_obj static
le_dom_VDF
TRUST_Ref< Domaine_VDF *> Modele_F1F2FMU_unitaire_VDF::le_dom_VDF protected
le_dom_Cl_VDF
TRUST_Ref< Domaine_Cl_VDF *> Modele_F1F2FMU_unitaire_VDF::le_dom_Cl_VDF protected