TrioCFD: Eval_Diff_K_Omega_VDF Class Reference
Eval_Diff_K_Omega_VDF Class Reference
#include <Eval_Diff_K_Omega_VDF.h>
Constructor & Destructor Documentation
~Eval_Diff_K_Omega_VDF()
virtual Eval_Diff_K_Omega_VDF::~Eval_Diff_K_Omega_VDF () inline virtual
Eval_Diff_K_Omega_VDF()
Eval_Diff_K_Omega_VDF::Eval_Diff_K_Omega_VDF (double Prandt_K = PRDT_K_DEFAUT, double Prandt_Omega = PRDT_OMEGA_DEFAUT) inline
References Prdt.
Member Function Documentation
associer_diff_turb()
void Eval_Diff_K_Omega_VDF::associer_diff_turb (const Champ_Fonc_base & diffu) inline
References diffusivite_turbulente_.
Referenced by Op_Diff_K_Omega_VDF_base::associer_diffusivite_turbulente().
associer_mvolumique()
void Eval_Diff_K_Omega_VDF::associer_mvolumique (const Champ_base & mvol) inline
References dv_mvol, masse_volumique_, TRUSTVect< _TYPE_, _SIZE_ >::ref(), and Champ_Proto::valeurs().
Referenced by Op_Diff_K_Omega_VDF_base::associer_diffusivite_turbulente().
associer_Pr_K_Omega()
void Eval_Diff_K_Omega_VDF::associer_Pr_K_Omega (double Pr_K, double Pr_Omega) inline
References Prdt, Prdt_K, and Prdt_Omega.
Referenced by Op_Diff_K_Omega_VDF_base::completer().
associer()
void Eval_Diff_K_Omega_VDF::associer (const Champ_base & diffu) inline
References db_diffusivite, diffusivite_, and Champ_Proto::valeurs().
Referenced by Op_Diff_K_Omega_VDF_base::associer_diffusivite().
mettre_a_jour()
virtual void Eval_Diff_K_Omega_VDF::mettre_a_jour () inline virtual
Reimplemented in Eval_Diff_K_Omega_VDF_var.
References db_diffusivite, diffusivite_, diffusivite_turbulente_, dv_diffusivite_turbulente, TRUSTVect< _TYPE_, _SIZE_ >::ref(), and TRUST_Ref< _CLASSE_ >::valeur().
diffusivite_turbulente()
const Champ_Fonc_base & Eval_Diff_K_Omega_VDF::diffusivite_turbulente () const inline
References diffusivite_turbulente_, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Op_Diff_K_Omega_VDF_base::diffusivite_turbulente().
diffusivite()
const Champ_base & Eval_Diff_K_Omega_VDF::diffusivite () const inline
References diffusivite_, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Op_Diff_K_Omega_VDF_base::diffusivite().
get_ind_Fluctu_Term()
int Eval_Diff_K_Omega_VDF::get_ind_Fluctu_Term () const inline
get_equivalent_distance()
double Eval_Diff_K_Omega_VDF::get_equivalent_distance (int boundary_index, int local_face) const inline
get_dv_mvol()
double Eval_Diff_K_Omega_VDF::get_dv_mvol (const int i) const inline
References dv_mvol.
Member Data Documentation
PRDT_K_DEFAUT
constexpr double Eval_Diff_K_Omega_VDF::PRDT_K_DEFAUT = 2 static constexpr protected
PRDT_OMEGA_DEFAUT
constexpr double Eval_Diff_K_Omega_VDF::PRDT_OMEGA_DEFAUT = 2 static protected
Prdt_K
double Eval_Diff_K_Omega_VDF::Prdt_K protected
Referenced by associer_Pr_K_Omega().
Prdt_Omega
double Eval_Diff_K_Omega_VDF::Prdt_Omega protected
Referenced by associer_Pr_K_Omega().
db_diffusivite
double Eval_Diff_K_Omega_VDF::db_diffusivite protected
Referenced by associer(), mettre_a_jour(), and Eval_Diff_K_Omega_VDF_const::nu_1_impl().
Prdt
double Eval_Diff_K_Omega_VDF::Prdt[2] protected
Referenced by associer_Pr_K_Omega(), Eval_Diff_K_Omega_VDF(), Eval_Diff_K_Omega_VDF_const::nu_1_impl(), and Eval_Diff_K_Omega_VDF_var::nu_1_impl().
dv_diffusivite_turbulente
DoubleVect Eval_Diff_K_Omega_VDF::dv_diffusivite_turbulente protected
Referenced by mettre_a_jour(), Eval_Diff_K_Omega_VDF_var::mettre_a_jour(), Eval_Diff_K_Omega_VDF_const::nu_1_impl(), and Eval_Diff_K_Omega_VDF_var::nu_1_impl().
dv_mvol
DoubleVect Eval_Diff_K_Omega_VDF::dv_mvol protected
Referenced by associer_mvolumique(), and get_dv_mvol().
diffusivite_turbulente_
TRUST_Ref< Champ_Fonc_base *> Eval_Diff_K_Omega_VDF::diffusivite_turbulente_ protected
Referenced by associer_diff_turb(), diffusivite_turbulente(), mettre_a_jour(), and Eval_Diff_K_Omega_VDF_var::mettre_a_jour().
masse_volumique_
TRUST_Ref< Champ_base *> Eval_Diff_K_Omega_VDF::masse_volumique_ protected
Referenced by associer_mvolumique().
diffusivite_
TRUST_Ref< Champ_base *> Eval_Diff_K_Omega_VDF::diffusivite_ protected
Referenced by associer(), Eval_Diff_K_Omega_VDF_var::associer(), diffusivite(), mettre_a_jour(), and Eval_Diff_K_Omega_VDF_var::mettre_a_jour().