TrioCFD: IJK_Thermal_Subresolution Class Reference
IJK_Thermal_Subresolution Class Reference
#include <IJK_Thermal_Subresolution.h>
Public Member Functions
const Type_info * get_info () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Public Types inherited from Champs_compris_IJK_interface
using FieldInfo_t = std::tuple< Motcle, Entity, Nature_du_champ, bool >
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Member Enumeration Documentation
temperature_ini_dict
enum IJK_Thermal_Subresolution::temperature_ini_dict protected
Enumerator
local_criteria
integral_criteria
derivative_criteria
time_criteria
Constructor & Destructor Documentation
IJK_Thermal_Subresolution()
IJK_Thermal_Subresolution::IJK_Thermal_Subresolution ()
References boundary_condition_end_dict_, boundary_condition_interface_dict_, fd_solver_type_, fd_solvers_, fd_solvers_jdd_, and source_terms_type_dict_.
~IJK_Thermal_Subresolution()
IJK_Thermal_Subresolution::~IJK_Thermal_Subresolution ()
Member Function Documentation
cree_instance()
Objet_U * IJK_Thermal_Subresolution::cree_instance () static
taille_memoire()
unsigned IJK_Thermal_Subresolution::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int IJK_Thermal_Subresolution::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * IJK_Thermal_Subresolution::info () static
get_info()
const Type_info * IJK_Thermal_Subresolution::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from IJK_Thermal_base.
self_cast() [1/2]
IJK_Thermal_Subresolution & IJK_Thermal_Subresolution::self_cast (Objet_U & r) static
self_cast() [2/2]
const IJK_Thermal_Subresolution & IJK_Thermal_Subresolution::self_cast (const Objet_U & r) static
printOn()
Sortie & IJK_Thermal_Subresolution::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from IJK_Thermal_base.
References advected_frame_of_reference_, allow_temperature_correction_for_visu_, approximate_temperature_increment_, boundary_condition_end_, boundary_condition_end_dict_, boundary_condition_interface_, boundary_condition_interface_dict_, clip_temperature_values_, coeff_distance_diagonal_, compute_normal_derivatives_on_reference_probes_, compute_radial_displacement_, conserve_max_interfacial_fluxes_, convective_flux_correction_, correct_neighbours_using_probe_length_, correct_temperature_cell_neighbours_first_iter_, debug_probe_collision_, delta_T_subcooled_overheated_, diffusive_flux_correction_, disable_distance_cell_faces_from_lrs_, disable_fo_flux_correction_, disable_post_processing_probes_out_files_, disable_probe_weak_gradient_, disable_probe_weak_gradient_gfm_, disable_slice_to_nearest_plane_, disable_spherical_diffusion_start_, disable_subresolution_, discrete_integral_, enable_mixed_cells_increment_, enable_probe_collision_detection_, enable_resize_probe_collision_, end_boundary_condition_value_, enforce_periodic_boundary_value_, find_cell_neighbours_for_fluxes_spherical_correction_, find_reachable_fluxes_, find_temperature_cell_neighbours_, finite_difference_assembler_, first_step_thermals_post_, first_time_step_implicit_, first_time_step_temporal_, first_time_step_varying_probes_, fluxes_correction_conservations_, fluxes_corrections_weighting_, implicit_solver_from_previous_probe_field_, impose_boundary_condition_interface_from_simulation_, impose_user_boundary_condition_end_value_, interfacial_boundary_condition_value_, interp_eulerian_, keep_first_reachable_fluxes_, keep_max_flux_correction_, local_cfl_, local_diffusion_fourier_priority_, local_fourier_, max_u_radial_, modified_time_init_, nb_diam_slice_, nb_phi_post_pro_, nb_probes_post_pro_, nb_slices_, nb_thermal_concentric_circles_, nb_thermal_line_points_, nb_thermal_lines_, nb_theta_post_pro_, neglect_frame_of_reference_radial_advection_, neighbours_colinearity_distance_weighting_, neighbours_colinearity_weighting_, neighbours_corrected_rank_, neighbours_distance_weighting_, neighbours_last_faces_colinearity_face_weighting_, neighbours_last_faces_colinearity_weighting_, neighbours_last_faces_distance_colinearity_face_weighting_, neighbours_last_faces_distance_weighting_, one_dimensional_advection_diffusion_thermal_solver_, override_vapour_mixed_values_, points_per_thermal_subproblem_, post_process_all_probes_, post_process_thermal_lines_, post_process_thermal_slices_, pre_factor_subproblems_number_, pre_initialise_thermal_subproblems_list_, IJK_Thermal_base::printOn(), probe_variations_priority_, probes_end_value_coeff_, quadtree_levels_, readjust_probe_length_from_vertices_, reconstruct_previous_probe_field_, reference_gfm_on_probes_, remove_append_subproblems_, smooth_temperature_field_, source_terms_type_, source_terms_type_dict_, store_cell_faces_corrected_, temperature_ini_type_, thermal_slices_regions_, time_ini_user_, upstream_dir_line_, upstream_dir_slice_, use_cell_neighbours_for_fluxes_spherical_correction_, use_corrected_velocity_convection_, use_normal_gradient_for_flux_corr_, use_reachable_fluxes_, use_sparse_matrix_, use_temperature_cell_neighbours_, and use_velocity_cartesian_grid_.
Referenced by IJK_Thermal_Multiple_Subresolutions::printOn().
readOn()
Entree & IJK_Thermal_Subresolution::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from IJK_Thermal_base.
References approximate_temperature_increment_, boundary_condition_end_, boundary_condition_interface_, IJK_Thermal_base::compute_grad_T_elem_, convective_flux_correction_, diffusive_flux_correction_, end_boundary_condition_value_, IJK_Thermal_base::ghost_fluid_, impose_boundary_condition_interface_from_simulation_, impose_user_boundary_condition_end_value_, interfacial_boundary_condition_value_, override_vapour_mixed_values_, and IJK_Thermal_base::readOn().
Referenced by IJK_Thermal_Multiple_Subresolutions::readOn().
initialize()
void IJK_Thermal_Subresolution::initialize (const Domaine_IJK & splitting, const int idx) override virtual
Reimplemented from IJK_Thermal_base.
References IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::allocate(), approximate_temperature_increment_, IJK_One_Dimensional_Subproblems::associer(), IJK_Thermal_base::calulate_grad_T_, IJK_SolveSys_FD_thermal::cast_direct_solver_by_default(), cell_faces_corrected_bool_, cell_faces_corrected_convective_, cell_faces_corrected_diffusive_, cell_faces_neighbours_corrected_all_bool_, cell_faces_neighbours_corrected_convective_, cell_faces_neighbours_corrected_convective_frame_of_reference_, cell_faces_neighbours_corrected_diag_bool_, cell_faces_neighbours_corrected_diffusive_, cell_faces_neighbours_corrected_min_max_bool_, cell_faces_neighbours_corrected_velocity_temperature_, IJK_Thermal_base::compute_curvature_, IJK_Thermal_base::compute_distance_, IJK_Thermal_base::compute_eulerian_compo_, IJK_Thermal_base::compute_grad_T_elem_, IJK_Thermal_base::compute_grad_T_interface_, IJK_Thermal_base::compute_hess_cross_T_elem_, IJK_Thermal_base::compute_hess_diag_T_elem_, IJK_Thermal_base::compute_hess_T_elem_, compute_normal_derivatives_on_reference_probes_, compute_overall_probes_parameters(), IJK_Thermal_base::compute_rising_velocities_, IJK_Thermal_base::conv_temperature_negligible_, convective_flux_correction_, copy_fluxes_on_every_procs_, copy_temperature_on_every_procs_, correct_temperature_cell_neighbours_first_iter_, IJK_Thermal_base::corrige_flux_, IJK_Thermal_base::cp_liquid_, IJK_Thermal_base::cp_vapour_, IJK_Thermal_base::d_temperature_uncorrected_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::data(), IJK_Thermal_base::debug_, debug_LRS_cells_, debug_probe_collision_, IJK_Thermal_base::diff_temperature_negligible_, diffusive_flux_correction_, disable_distance_cell_faces_from_lrs_, disable_first_step_thermals_post_, disable_fo_flux_correction_, disable_mixed_cells_increment_, disable_spherical_diffusion_start_, disable_subresolution_, discrete_integral_, distance_cell_faces_from_lrs_, IJK_Thermal_base::div_coeff_grad_T_volume_uncorrected_, IJK_Field_vector< T, N >::echange_espace_virtuel(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel(), Domaine_IJK::ELEM, enable_mixed_cells_increment_, Objet_U_ptr::est_nul(), IJK_Thermal_base::eulerian_normal_vectors_ns_normed_, find_cell_neighbours_for_fluxes_spherical_correction_, find_reachable_fluxes_, find_temperature_cell_neighbours_, first_step_thermals_post_, first_time_step_explicit_, first_time_step_implicit_, first_time_step_temporal_, first_time_step_varying_probes_, fluxes_correction_conservations_, IJK_Thermal_base::fo_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost(), IJK_Thermal_base::ghost_cells_, IJK_Thermal_base::ghost_fluid_, impose_fo_flux_correction_, initialise_thermal_subproblems_list(), Operateur_IJK_elem_conv::initialize(), Operateur_IJK_elem_diff::initialize(), IJK_Thermal_base::initialize(), Corrige_flux_FT_base::initialize_with_subproblems(), interfacial_heat_flux_contrib_, interfacial_heat_flux_current_, interfacial_heat_flux_dispatched_, is_first_time_step_, keep_first_reachable_fluxes_, keep_max_flux_correction_, IJK_Thermal_base::lambda_liquid_, IJK_Thermal_base::lambda_vapour_, neighbours_colinearity_distance_weighting_, neighbours_colinearity_weighting_, neighbours_distance_weighting_, neighbours_faces_weighting_colinearity_, neighbours_last_faces_colinearity_face_weighting_, neighbours_last_faces_colinearity_weighting_, neighbours_last_faces_distance_colinearity_face_weighting_, neighbours_last_faces_distance_colinearity_weighting_, neighbours_last_faces_distance_weighting_, neighbours_last_faces_weighting_, neighbours_temperature_colinearity_weighting_, neighbours_temperature_to_correct_, neighbours_temperature_to_correct_trimmed_, neighbours_weighting_, one_dimensional_advection_diffusion_thermal_solver_, IJK_Thermal_base::prandtl_number_, pre_initialise_thermal_subproblems_list_, probe_collision_debug_field_, probe_variations_enabled_, quadtree_levels_, Objet_U::que_suis_je(), readjust_probe_length_from_vertices_, IJK_Thermal_base::ref_ijk_ft_, reference_gfm_on_probes_, remove_append_subproblems_, Corrige_flux_FT_base::set_cell_faces_neighbours_corrected_bool(), Operateur_IJK_elem_diff::set_conductivity_coefficient(), Corrige_flux_FT_base::set_convection_diffusion_correction(), Corrige_flux_FT_base::set_convection_negligible(), Corrige_flux_FT_base::set_correction_cell_faces_neighbours(), Corrige_flux_FT_base::set_correction_cell_neighbours(), Corrige_flux_FT_base::set_debug(), Corrige_flux_FT_base::set_diffusion_negligible(), Corrige_flux_FT_base::set_distance_cell_faces_from_lrs(), Corrige_flux_FT_base::set_eulerian_normal_vectors_ns_normed(), Corrige_flux_FT_base::set_fluxes_feedback_params(), Corrige_flux_FT_base::set_physical_parameters(), set_subproblems_interfaces_fields(), Corrige_flux_FT_base::set_temperature_fluxes_periodic_sharing_strategy_on_processors(), Operateur_IJK_elem_diff_base_double::set_uniform_lambda(), smooth_temperature_field_, store_cell_faces_corrected_, IJK_Thermal_base::store_flux_operators_for_energy_balance_, IJK_Thermal_base::temperature_, IJK_Thermal_base::temperature_before_extrapolation_, temperature_cell_neighbours_, temperature_cell_neighbours_debug_, IJK_Thermal_base::temperature_convection_op_, IJK_Thermal_base::temperature_diffusion_op_, IJK_Thermal_base::temperature_hess_flux_op_centre_, thermal_local_subproblems_, Objet_U_ptr::typer(), IJK_Thermal_base::uniform_alpha_, IJK_Thermal_base::uniform_lambda_, use_cell_neighbours_for_fluxes_spherical_correction_, use_reachable_fluxes_, use_sparse_matrix_, use_temperature_cell_neighbours_, and zero_liquid_neighbours_.
Referenced by IJK_Thermal_Multiple_Subresolutions::initialize().
update_thermal_properties()
void IJK_Thermal_Subresolution::update_thermal_properties () override virtual
Reimplemented from IJK_Thermal_base.
References IJK_Thermal_base::update_thermal_properties().
Referenced by IJK_Thermal_Multiple_Subresolutions::update_thermal_properties().
post_process_after_temperature_increment()
void IJK_Thermal_Subresolution::post_process_after_temperature_increment () override virtual
Reimplemented from IJK_Thermal_base.
References compute_mean_liquid_temperature(), compute_Nusselt_spherical_diffusion(), IJK_Thermal_base::debug_, and IJK_Thermal_base::post_process_after_temperature_increment().
set_param()
void IJK_Thermal_Subresolution::set_param (Param & param) override virtual
Reimplemented from IJK_Thermal_base.
References advected_frame_of_reference_, Param::ajouter(), Param::ajouter_flag(), allow_temperature_correction_for_visu_, approximate_temperature_increment_, boundary_condition_end_, boundary_condition_interface_, clip_temperature_values_, coeff_distance_diagonal_, compute_normal_derivatives_on_reference_probes_, compute_radial_displacement_, conserve_max_interfacial_fluxes_, convective_flux_correction_, correct_neighbours_using_probe_length_, correct_temperature_cell_neighbours_first_iter_, debug_probe_collision_, delta_T_subcooled_overheated_, Param::dictionnaire(), diffusive_flux_correction_, disable_distance_cell_faces_from_lrs_, disable_first_step_thermals_post_, disable_fo_flux_correction_, disable_mixed_cells_increment_, disable_post_processing_probes_out_files_, disable_probe_weak_gradient_, disable_probe_weak_gradient_gfm_, disable_slice_to_nearest_plane_, disable_spherical_diffusion_start_, disable_subresolution_, discrete_integral_, enable_mixed_cells_increment_, enable_probe_collision_detection_, enable_resize_probe_collision_, end_boundary_condition_value_, enforce_periodic_boundary_value_, find_cell_neighbours_for_fluxes_spherical_correction_, find_reachable_fluxes_, find_temperature_cell_neighbours_, finite_difference_assembler_, first_time_step_implicit_, first_time_step_temporal_, first_time_step_varying_probes_, fluxes_correction_conservations_, fluxes_corrections_weighting_, implicit_solver_from_previous_probe_field_, impose_boundary_condition_interface_from_simulation_, impose_user_boundary_condition_end_value_, interfacial_boundary_condition_value_, interp_eulerian_, keep_first_reachable_fluxes_, keep_max_flux_correction_, local_cfl_, local_diffusion_fourier_priority_, local_fourier_, max_u_radial_, modified_time_init_, nb_diam_slice_, nb_diam_thermal_line_length_, nb_phi_post_pro_, nb_probes_post_pro_, nb_slices_, nb_thermal_concentric_circles_, nb_thermal_line_points_, nb_thermal_lines_, nb_theta_post_pro_, neglect_frame_of_reference_radial_advection_, neighbours_colinearity_distance_weighting_, neighbours_colinearity_weighting_, neighbours_corrected_rank_, neighbours_distance_weighting_, neighbours_last_faces_colinearity_face_weighting_, neighbours_last_faces_colinearity_weighting_, neighbours_last_faces_distance_colinearity_face_weighting_, neighbours_last_faces_distance_colinearity_weighting_, neighbours_last_faces_distance_weighting_, one_dimensional_advection_diffusion_thermal_solver_, override_vapour_mixed_values_, points_per_thermal_subproblem_, post_process_all_probes_, post_process_thermal_lines_, post_process_thermal_slices_, pre_factor_subproblems_number_, pre_initialise_thermal_subproblems_list_, probe_variations_priority_, probes_end_value_coeff_, quadtree_levels_, readjust_probe_length_from_vertices_, reconstruct_previous_probe_field_, reference_gfm_on_probes_, remove_append_subproblems_, IJK_Thermal_base::set_param(), smooth_temperature_field_, source_terms_correction_, source_terms_type_, store_cell_faces_corrected_, temperature_ini_type_, thermal_slices_regions_, time_ini_user_, upstream_dir_line_, upstream_dir_slice_, use_cell_neighbours_for_fluxes_spherical_correction_, use_corrected_velocity_convection_, use_normal_gradient_for_flux_corr_, use_reachable_fluxes_, use_sparse_matrix_, use_temperature_cell_neighbours_, and use_velocity_cartesian_grid_.
compute_ghost_cell_numbers_for_subproblems()
void IJK_Thermal_Subresolution::compute_ghost_cell_numbers_for_subproblems (const Domaine_IJK & splitting, int ghost_init) override virtual
Reimplemented from IJK_Thermal_base.
References IJK_Thermal_base::cell_diagonal_, coeff_distance_diagonal_, IJK_Thermal_base::compute_cell_diagonal(), Domaine_IJK::get_constant_delta(), and IJK_Thermal_base::ghost_cells_.
get_probes_length()
double IJK_Thermal_Subresolution::get_probes_length ()
References IJK_Thermal_base::cell_diagonal_, and coeff_distance_diagonal_.
Referenced by compute_spherical_steady_dirichlet_left_right_derivative_value(), compute_spherical_steady_dirichlet_left_right_integral(), compute_spherical_steady_dirichlet_left_right_value(), compute_temperature_init(), find_time_dichotomy_derivative(), find_time_dichotomy_integral(), and get_time_inflection_derivative().
lire_motcle_non_standard()
int IJK_Thermal_Subresolution::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Objet_U.
References Param::ajouter(), enforce_periodic_boundary_value_, Param::lire_avec_accolades_depuis(), Param::lire_sans_accolade(), Objet_U::que_suis_je(), Param::REQUIRED, and stencil_periodic_boundary_value_.
set_thermal_subresolution_outputs()
void IJK_Thermal_Subresolution::set_thermal_subresolution_outputs (const Nom & interfacial_quantities_thermal_probes, const Nom & shell_quantities_thermal_probes, const Nom & overall_bubbles_quantities, const Nom & local_quantities_thermal_probes_time_index_folder) override virtual
Reimplemented from IJK_Thermal_base.
References IJK_One_Dimensional_Subproblems::compute_overall_bubbles_quantities(), IJK_Thermal_base::debug_, disable_subresolution_, nb_phi_post_pro_, nb_theta_post_pro_, post_process_all_probes_, IJK_Thermal_base::rang_, reference_gfm_on_probes_, IJK_One_Dimensional_Subproblems::sort_limited_probes_spherical_coords_post_processing(), thermal_local_subproblems_, and IJK_One_Dimensional_Subproblems::thermal_subresolution_outputs_parallel().
post_process_thermal_downstream_lines()
void IJK_Thermal_Subresolution::post_process_thermal_downstream_lines (const Nom & local_quantities_thermal_lines_time_index_folder) override virtual
Reimplemented from IJK_Thermal_base.
References find_cocentric_line_coordinates(), find_points_on_proc(), initialise_thermal_dowstreamlines_tabs(), initialise_thermal_line_points(), interpolate_convective_term_on_downstream_line(), interpolate_diffusive_term_on_downstream_line(), interpolate_temperature_increment_on_downstream_line(), interpolate_temperature_on_downstream_line(), interpolate_velocity_on_downstream_line(), nb_thermal_concentric_circles_, nb_thermal_line_points_, nb_thermal_lines_, post_process_thermal_lines_, post_processed_fields_on_downstream_line(), IJK_Thermal_base::ref_ijk_ft_, TRUSTArray< _TYPE_, _SIZE_ >::resize(), and upstream_dir_line_.
initialise_thermal_dowstreamlines_tabs() [1/4]
void IJK_Thermal_Subresolution::initialise_thermal_dowstreamlines_tabs (std::vector< std::vector< FixedVector< ArrOfInt, 3 > > > & parameters, const int & nb_thermal_circles, const int & nb_thermal_lines)
References nb_thermal_line_points_.
Referenced by post_process_thermal_downstream_lines().
initialise_thermal_dowstreamlines_tabs() [2/4]
void IJK_Thermal_Subresolution::initialise_thermal_dowstreamlines_tabs (std::vector< std::vector< FixedVector< ArrOfDouble, 2 > > > & parameters, const int & nb_thermal_circles, const int & nb_thermal_lines)
References nb_thermal_line_points_.
initialise_thermal_dowstreamlines_tabs() [3/4]
void IJK_Thermal_Subresolution::initialise_thermal_dowstreamlines_tabs (std::vector< std::vector< ArrOfInt > > & parameters, const int & nb_thermal_circles, const int & nb_thermal_lines)
References nb_thermal_line_points_.
initialise_thermal_dowstreamlines_tabs() [4/4]
void IJK_Thermal_Subresolution::initialise_thermal_dowstreamlines_tabs (std::vector< std::vector< ArrOfDouble > > & parameters, const int & nb_thermal_circles, const int & nb_thermal_lines)
References nb_thermal_line_points_.
initialise_thermal_line_points()
void IJK_Thermal_Subresolution::initialise_thermal_line_points (const int & line_dir, ArrOfDouble & linear_coord, FixedVector< ArrOfDouble, 3 > & coordinates_line, double & diameter)
References Domaine_IJK::get_domain_length(), Domaine_IJK::get_origin(), Domaine_IJK::get_periodic_flag(), nb_diam_thermal_line_length_, nb_thermal_line_points_, IJK_Thermal_base::ref_ijk_ft_, and IJK_Thermal_base::temperature_.
Referenced by post_process_thermal_downstream_lines().
find_thermal_line_points_in_procs()
void IJK_Thermal_Subresolution::find_thermal_line_points_in_procs (std::vector< std::vector< ArrOfInt > > & parameters)
find_cocentric_line_coordinates()
void IJK_Thermal_Subresolution::find_cocentric_line_coordinates (const int & nb_thermal_circles, const int & nb_thermal_lines, const double & diameter_approx, std::vector< std::vector< FixedVector< ArrOfDouble, 2 > > > & coordinates_sides)
Referenced by post_process_thermal_downstream_lines().
find_points_on_proc()
void IJK_Thermal_Subresolution::find_points_on_proc (std::vector< std::vector< ArrOfInt > > & is_point_on_proc, std::vector< std::vector< FixedVector< ArrOfInt, 3 > > > & ijk_indices, const FixedVector< ArrOfDouble, 3 > & coordinates_line, const std::vector< std::vector< FixedVector< ArrOfDouble, 2 > > > & coordinates_sides, const int & line_dir)
References Domaine_IJK::get_constant_delta(), Domaine_IJK::get_domain_length(), Domaine_IJK::get_offset_local(), min_max_ldir(), and IJK_Thermal_base::temperature_.
Referenced by post_process_thermal_downstream_lines().
min_max_ldir()
void IJK_Thermal_Subresolution::min_max_ldir (const int & dir, const Domaine_IJK & geom, double & min_dir, double & max_dir)
References Domaine_IJK::get_domain_length(), and Domaine_IJK::get_origin().
Referenced by find_points_on_proc().
interpolate_fields_on_downstream_line()
void IJK_Thermal_Subresolution::interpolate_fields_on_downstream_line (const int & dir, const int & nb_thermal_circles, const int & index_circle, const int & index_line, const std::vector< std::vector< ArrOfInt > > & is_point_on_proc, const FixedVector< ArrOfDouble, 3 > & coordinates_line, const std::vector< std::vector< FixedVector< ArrOfDouble, 2 > > > & coordinates_sides, const IJK_Field_double & field, const IJK_Field_vector3_double & field_gradient, const IJK_Field_vector3_double & velocity, DoubleVect & values, const int field_type)
Referenced by interpolate_convective_term_on_downstream_line(), interpolate_diffusive_term_on_downstream_line(), interpolate_temperature_increment_on_downstream_line(), interpolate_temperature_on_downstream_line(), and interpolate_velocity_on_downstream_line().
interpolate_temperature_on_downstream_line()
void IJK_Thermal_Subresolution::interpolate_temperature_on_downstream_line (const int & dir, const int & nb_thermal_circles, const int & index_circle, const int & index_line, const std::vector< std::vector< ArrOfInt > > & is_point_on_proc, const FixedVector< ArrOfDouble, 3 > & coordinates_line, const std::vector< std::vector< FixedVector< ArrOfDouble, 2 > > > & coordinates_sides, DoubleVect & values)
References IJK_Thermal_base::grad_T_elem_, interpolate_fields_on_downstream_line(), IJK_Thermal_base::ref_ijk_ft_, and IJK_Thermal_base::temperature_.
Referenced by post_process_thermal_downstream_lines().
interpolate_velocity_on_downstream_line()
void IJK_Thermal_Subresolution::interpolate_velocity_on_downstream_line (const int & dir, const int & nb_thermal_circles, const int & index_circle, const int & index_line, const std::vector< std::vector< ArrOfInt > > & is_point_on_proc, const FixedVector< ArrOfDouble, 3 > & coordinates_line, const std::vector< std::vector< FixedVector< ArrOfDouble, 2 > > > & coordinates_sides, DoubleVect & values)
References IJK_Thermal_base::grad_T_elem_, interpolate_fields_on_downstream_line(), IJK_Thermal_base::ref_ijk_ft_, and IJK_Thermal_base::temperature_.
Referenced by post_process_thermal_downstream_lines().
interpolate_convective_term_on_downstream_line()
void IJK_Thermal_Subresolution::interpolate_convective_term_on_downstream_line (const int & dir, const int & nb_thermal_circles, const int & index_circle, const int & index_line, const std::vector< std::vector< ArrOfInt > > & is_point_on_proc, const FixedVector< ArrOfDouble, 3 > & coordinates_line, const std::vector< std::vector< FixedVector< ArrOfDouble, 2 > > > & coordinates_sides, DoubleVect & values)
References IJK_Thermal_base::cp_liquid_, IJK_Thermal_base::debug_, delta_T_subcooled_overheated_, IJK_Thermal_base::grad_T_elem_, interpolate_fields_on_downstream_line(), IJK_Thermal_base::ref_ijk_ft_, TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and IJK_Thermal_base::temperature_.
Referenced by post_process_thermal_downstream_lines().
interpolate_diffusive_term_on_downstream_line()
void IJK_Thermal_Subresolution::interpolate_diffusive_term_on_downstream_line (const int & dir, const int & nb_thermal_circles, const int & index_circle, const int & index_line, const std::vector< std::vector< ArrOfInt > > & is_point_on_proc, const FixedVector< ArrOfDouble, 3 > & coordinates_line, const std::vector< std::vector< FixedVector< ArrOfDouble, 2 > > > & coordinates_sides, DoubleVect & values)
References IJK_Thermal_base::grad_T_elem_, interpolate_fields_on_downstream_line(), IJK_Thermal_base::ref_ijk_ft_, IJK_Thermal_base::temperature_, and IJK_Thermal_base::uniform_lambda_.
Referenced by post_process_thermal_downstream_lines().
interpolate_temperature_increment_on_downstream_line()
void IJK_Thermal_Subresolution::interpolate_temperature_increment_on_downstream_line (const int & dir, const int & nb_thermal_circles, const int & index_circle, const int & index_line, const std::vector< std::vector< ArrOfInt > > & is_point_on_proc, const FixedVector< ArrOfDouble, 3 > & coordinates_line, const std::vector< std::vector< FixedVector< ArrOfDouble, 2 > > > & coordinates_sides, DoubleVect & values)
References IJK_Thermal_base::d_temperature_, IJK_Thermal_base::grad_T_elem_, interpolate_fields_on_downstream_line(), and IJK_Thermal_base::ref_ijk_ft_.
Referenced by post_process_thermal_downstream_lines().
post_processed_fields_on_downstream_line()
void IJK_Thermal_Subresolution::post_processed_fields_on_downstream_line (const Nom & local_quantities_thermal_lines_time_index_folder, const int & line_dir, const int & linear_circle_line_index, const int & index_circle, const int & index_line, const double & diameter_approx, std::vector< std::vector< ArrOfInt > > & is_point_on_proc, const std::vector< std::vector< FixedVector< ArrOfInt, 3 > > > & indices_ijk, const ArrOfDouble & linear_coord, const FixedVector< ArrOfDouble, 3 > & coordinates_line, const std::vector< std::vector< FixedVector< ArrOfDouble, 2 > > > & coordinates_sides, const DoubleVect & temperature_line, const DoubleVect & velocity_line, const DoubleVect & convective_term_line, const DoubleVect & diffusive_term_line, const DoubleVect & temperature_incr_line)
References Sortie_Fichier_base::close(), Process::je_suis_maitre(), IJK_Thermal_base::latastep_reprise_ini_, Process::me(), IJK_Thermal_base::rang_, IJK_Thermal_base::ref_ijk_ft_, and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by post_process_thermal_downstream_lines().
post_process_thermal_wake_slices()
void IJK_Thermal_Subresolution::post_process_thermal_wake_slices (const Nom & local_quantities_thermal_slices_time_index_folder) override virtual
Reimplemented from IJK_Thermal_base.
References TRUSTArray< _TYPE_, _SIZE_ >::append_array(), nb_diam_slice_, nb_slices_, post_process_thermal_slices_, post_process_thermal_wake_slice(), IJK_Thermal_base::ref_ijk_ft_, and thermal_slices_regions_.
post_process_thermal_wake_slice()
void IJK_Thermal_Subresolution::post_process_thermal_wake_slice (const int & slice, const double & nb_diam_slice, const Nom & local_quantities_thermal_slices_time_index_folder)
References complete_field_thermal_wake_slice_ij_convection(), complete_field_thermal_wake_slice_ij_diffusion(), complete_field_thermal_wake_slice_ij_indices_coords(), complete_field_thermal_wake_slice_ij_temperature(), complete_field_thermal_wake_slice_ij_temperature_incr(), complete_field_thermal_wake_slice_ij_velocity(), post_process_thermal_wake_slice_index_dir(), post_processed_field_thermal_wake_slice_ij(), IJK_Thermal_base::ref_ijk_ft_, and upstream_dir_slice_.
Referenced by post_process_thermal_wake_slices().
post_process_thermal_wake_slice_index_dir()
double IJK_Thermal_Subresolution::post_process_thermal_wake_slice_index_dir (int & index_dir_local, int & index_dir_global, int & n_cross_section_1, int & n_cross_section_2, int & dir, const double & nb_diam, int upstream_dir, int gravity_dir, double & diameter)
References Domaine_IJK::get_constant_delta(), Domaine_IJK::get_domain_length(), Domaine_IJK::get_nb_elem_tot(), Domaine_IJK::get_offset_local(), Domaine_IJK::get_origin(), Domaine_IJK::get_periodic_flag(), IJK_Thermal_base::ref_ijk_ft_, and IJK_Thermal_base::temperature_.
Referenced by post_process_thermal_wake_slice().
complete_field_thermal_wake_slice_ij_values()
void IJK_Thermal_Subresolution::complete_field_thermal_wake_slice_ij_values (int & index_dir_local, const int & dir, const double & slice_pos, FixedVector< IntTab, 2 > & ij_indices, FixedVector< DoubleTab, 3 > & ij_coords, const IJK_Field_double & field, const IJK_Field_vector3_double & field_gradient, const IJK_Field_vector3_double & velocity, DoubleTab & values, const int field_type, const int slice_to_nearest_plane, const int compute_indices = 0)
References Domaine_IJK::ELEM, IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_domaine(), Domaine_IJK::get_offset_local(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), IJK_Thermal_base::ref_ijk_ft_, and TRUSTTab< _TYPE_, _SIZE_ >::resize().
Referenced by complete_field_thermal_wake_slice_ij_convection(), complete_field_thermal_wake_slice_ij_diffusion(), complete_field_thermal_wake_slice_ij_indices_coords(), complete_field_thermal_wake_slice_ij_temperature(), complete_field_thermal_wake_slice_ij_temperature_incr(), and complete_field_thermal_wake_slice_ij_velocity().
complete_field_thermal_wake_slice_ij_indices_coords()
void IJK_Thermal_Subresolution::complete_field_thermal_wake_slice_ij_indices_coords (const int & slice, int & index_dir_local, const int & dir, const double & slice_pos, FixedVector< IntTab, 2 > & ij_indices, FixedVector< DoubleTab, 3 > & ij_coords, DoubleTab & values, const Nom & local_quantities_thermal_slices_time_index_folder)
References complete_field_thermal_wake_slice_ij_values(), disable_slice_to_nearest_plane_, IJK_Thermal_base::grad_T_elem_, IJK_Thermal_base::ref_ijk_ft_, and IJK_Thermal_base::temperature_.
Referenced by post_process_thermal_wake_slice().
complete_field_thermal_wake_slice_ij_temperature()
void IJK_Thermal_Subresolution::complete_field_thermal_wake_slice_ij_temperature (const int & slice, int & index_dir_local, const int & dir, const double & slice_pos, FixedVector< IntTab, 2 > & ij_indices, FixedVector< DoubleTab, 3 > & ij_coords, DoubleTab & values, const Nom & local_quantities_thermal_slices_time_index_folder)
References complete_field_thermal_wake_slice_ij_values(), disable_slice_to_nearest_plane_, IJK_Thermal_base::grad_T_elem_, IJK_Thermal_base::ref_ijk_ft_, and IJK_Thermal_base::temperature_.
Referenced by post_process_thermal_wake_slice().
complete_field_thermal_wake_slice_ij_velocity()
void IJK_Thermal_Subresolution::complete_field_thermal_wake_slice_ij_velocity (const int & slice, int & index_dir_local, const int & dir, const double & slice_pos, FixedVector< IntTab, 2 > & ij_indices, FixedVector< DoubleTab, 3 > & ij_coords, DoubleTab & velocity_values, const Nom & local_quantities_thermal_slices_time_index_folder)
References complete_field_thermal_wake_slice_ij_values(), disable_slice_to_nearest_plane_, IJK_Thermal_base::grad_T_elem_, IJK_Thermal_base::ref_ijk_ft_, and IJK_Thermal_base::temperature_.
Referenced by post_process_thermal_wake_slice().
complete_field_thermal_wake_slice_ij_convection()
void IJK_Thermal_Subresolution::complete_field_thermal_wake_slice_ij_convection (const int & slice, int & index_dir_local, const int & dir, const double & slice_pos, FixedVector< IntTab, 2 > & ij_indices, FixedVector< DoubleTab, 3 > & ij_coords, DoubleTab & values, DoubleTab & velocity_values, const Nom & local_quantities_thermal_slices_time_index_folder)
References complete_field_thermal_wake_slice_ij_values(), IJK_Thermal_base::cp_liquid_, IJK_Thermal_base::debug_, delta_T_subcooled_overheated_, disable_slice_to_nearest_plane_, IJK_Thermal_base::grad_T_elem_, IJK_Thermal_base::ref_ijk_ft_, and IJK_Thermal_base::temperature_.
Referenced by post_process_thermal_wake_slice().
complete_field_thermal_wake_slice_ij_diffusion()
void IJK_Thermal_Subresolution::complete_field_thermal_wake_slice_ij_diffusion (const int & slice, int & index_dir_local, const int & dir, const double & slice_pos, FixedVector< IntTab, 2 > & ij_indices, FixedVector< DoubleTab, 3 > & ij_coords, DoubleTab & values, const Nom & local_quantities_thermal_slices_time_index_folder)
References complete_field_thermal_wake_slice_ij_values(), disable_slice_to_nearest_plane_, IJK_Thermal_base::grad_T_elem_, IJK_Thermal_base::ref_ijk_ft_, IJK_Thermal_base::temperature_, and IJK_Thermal_base::uniform_lambda_.
Referenced by post_process_thermal_wake_slice().
complete_field_thermal_wake_slice_ij_temperature_incr()
void IJK_Thermal_Subresolution::complete_field_thermal_wake_slice_ij_temperature_incr (const int & slice, int & index_dir_local, const int & dir, const double & slice_pos, FixedVector< IntTab, 2 > & ij_indices, FixedVector< DoubleTab, 3 > & ij_coords, DoubleTab & values, const Nom & local_quantities_thermal_slices_time_index_folder)
References complete_field_thermal_wake_slice_ij_values(), IJK_Thermal_base::d_temperature_, disable_slice_to_nearest_plane_, IJK_Thermal_base::grad_T_elem_, and IJK_Thermal_base::ref_ijk_ft_.
Referenced by post_process_thermal_wake_slice().
post_processed_field_thermal_wake_slice_ij()
void IJK_Thermal_Subresolution::post_processed_field_thermal_wake_slice_ij (const int & slice, const Nom & local_quantities_thermal_slices_time_index_folder, const double & diameter_approx, const double & nb_diam_slice, const int & n_cross_section_1, const int & n_cross_section_2, const FixedVector< IntTab, 2 > ij_indices, const FixedVector< DoubleTab, 3 > & ij_coords, const DoubleTab & temperature_slice, const DoubleTab & velocity_slice, const DoubleTab & convection_slice, const DoubleTab & diffusion_slice, const DoubleTab & temperature_incr_slice)
References Sortie_Fichier_base::close(), IJK_Thermal_base::debug_, Process::je_suis_maitre(), IJK_Thermal_base::latastep_reprise_ini_, IJK_Thermal_base::rang_, and IJK_Thermal_base::ref_ijk_ft_.
Referenced by post_process_thermal_wake_slice().
get_debug_lrs_cells()
const IJK_Field_double & IJK_Thermal_Subresolution::get_debug_lrs_cells () const inline override virtual
Reimplemented from IJK_Thermal_base.
References debug_LRS_cells_.
get_temperature_cell_neighbours_debug()
const IJK_Field_double & IJK_Thermal_Subresolution::get_temperature_cell_neighbours_debug () const inline override virtual
Reimplemented from IJK_Thermal_base.
References IJK_Thermal_base::debug_, IJK_Thermal_base::dummy_double_field_, find_temperature_cell_neighbours_, and temperature_cell_neighbours_debug_.
get_temperature_cell_neighbours()
const IJK_Field_double & IJK_Thermal_Subresolution::get_temperature_cell_neighbours () const inline override virtual
Reimplemented from IJK_Thermal_base.
References IJK_Thermal_base::dummy_double_field_, find_temperature_cell_neighbours_, and temperature_cell_neighbours_.
get_cell_neighbours_corrected()
const IJK_Field_int & IJK_Thermal_Subresolution::get_cell_neighbours_corrected () const inline override virtual
Reimplemented from IJK_Thermal_base.
References IJK_Thermal_base::dummy_int_field_, find_temperature_cell_neighbours_, and neighbours_temperature_to_correct_.
get_neighbours_temperature_colinearity_weighting()
const IJK_Field_double & IJK_Thermal_Subresolution::get_neighbours_temperature_colinearity_weighting () const inline override virtual
Reimplemented from IJK_Thermal_base.
References IJK_Thermal_base::dummy_double_field_, find_temperature_cell_neighbours_, and neighbours_temperature_colinearity_weighting_.
get_cell_faces_corrected_diffusive()
const IJK_Field_vector3_double & IJK_Thermal_Subresolution::get_cell_faces_corrected_diffusive () const inline override virtual
Reimplemented from IJK_Thermal_base.
References cell_faces_corrected_diffusive_, convective_flux_correction_, diffusive_flux_correction_, IJK_Thermal_base::dummy_double_vect_, and store_cell_faces_corrected_.
get_cell_faces_corrected_convective()
const IJK_Field_vector3_double & IJK_Thermal_Subresolution::get_cell_faces_corrected_convective () const inline override virtual
Reimplemented from IJK_Thermal_base.
References cell_faces_corrected_convective_, convective_flux_correction_, diffusive_flux_correction_, IJK_Thermal_base::dummy_double_vect_, and store_cell_faces_corrected_.
get_cell_faces_corrected_bool()
const IJK_Field_vector3_int & IJK_Thermal_Subresolution::get_cell_faces_corrected_bool () const inline override virtual
Reimplemented from IJK_Thermal_base.
References cell_faces_corrected_bool_, convective_flux_correction_, diffusive_flux_correction_, IJK_Thermal_base::dummy_int_vect_, and store_cell_faces_corrected_.
get_cell_faces_neighbours_corrected_diag_bool()
const IJK_Field_vector3_int & IJK_Thermal_Subresolution::get_cell_faces_neighbours_corrected_diag_bool () const inline override virtual
Reimplemented from IJK_Thermal_base.
References cell_faces_neighbours_corrected_diag_bool_, IJK_Thermal_base::dummy_int_vect_, and find_cell_neighbours_for_fluxes_spherical_correction_.
get_cell_faces_neighbours_corrected_all_bool()
const IJK_Field_vector3_int & IJK_Thermal_Subresolution::get_cell_faces_neighbours_corrected_all_bool () const inline override virtual
Reimplemented from IJK_Thermal_base.
References cell_faces_neighbours_corrected_all_bool_, IJK_Thermal_base::dummy_int_vect_, and find_reachable_fluxes_.
get_cell_faces_neighbours_corrected_min_max_bool()
const IJK_Field_vector3_int & IJK_Thermal_Subresolution::get_cell_faces_neighbours_corrected_min_max_bool () const inline override virtual
Reimplemented from IJK_Thermal_base.
References cell_faces_neighbours_corrected_min_max_bool_, IJK_Thermal_base::dummy_int_vect_, and find_reachable_fluxes_.
get_cell_faces_neighbours_corrected_convective()
const IJK_Field_vector3_double & IJK_Thermal_Subresolution::get_cell_faces_neighbours_corrected_convective () const inline override virtual
Reimplemented from IJK_Thermal_base.
References cell_faces_neighbours_corrected_convective_, convective_flux_correction_, IJK_Thermal_base::dummy_double_vect_, and use_reachable_fluxes_.
get_cell_faces_neighbours_corrected_convective_frame_of_ref()
const IJK_Field_vector3_double & IJK_Thermal_Subresolution::get_cell_faces_neighbours_corrected_convective_frame_of_ref () const inline override virtual
Reimplemented from IJK_Thermal_base.
References cell_faces_neighbours_corrected_convective_frame_of_reference_, convective_flux_correction_, IJK_Thermal_base::dummy_double_vect_, IJK_Thermal_base::store_flux_operators_for_energy_balance_, and use_reachable_fluxes_.
get_cell_faces_neighbours_corrected_velocity_temperature()
const IJK_Field_vector3_double & IJK_Thermal_Subresolution::get_cell_faces_neighbours_corrected_velocity_temperature () const inline override virtual
Reimplemented from IJK_Thermal_base.
References cell_faces_neighbours_corrected_velocity_temperature_, convective_flux_correction_, IJK_Thermal_base::dummy_double_vect_, IJK_Thermal_base::store_flux_operators_for_energy_balance_, and use_reachable_fluxes_.
get_cell_faces_neighbours_corrected_diffusive()
const IJK_Field_vector3_double & IJK_Thermal_Subresolution::get_cell_faces_neighbours_corrected_diffusive () const inline override virtual
Reimplemented from IJK_Thermal_base.
References cell_faces_neighbours_corrected_diffusive_, diffusive_flux_correction_, IJK_Thermal_base::dummy_double_vect_, and use_reachable_fluxes_.
get_neighbours_faces_weighting_colinearity()
const IJK_Field_vector3_double & IJK_Thermal_Subresolution::get_neighbours_faces_weighting_colinearity () const inline override virtual
Reimplemented from IJK_Thermal_base.
References IJK_Thermal_base::dummy_double_vect_, neighbours_colinearity_weighting_, neighbours_faces_weighting_colinearity_, and use_reachable_fluxes_.
get_cell_neighbours_corrected_trimmed()
const IJK_Field_int & IJK_Thermal_Subresolution::get_cell_neighbours_corrected_trimmed () const inline override virtual
Reimplemented from IJK_Thermal_base.
References IJK_Thermal_base::dummy_int_field_, find_reachable_fluxes_, and neighbours_temperature_to_correct_trimmed_.
get_probe_collision_debug_field()
const IJK_Field_double & IJK_Thermal_Subresolution::get_probe_collision_debug_field () const inline override virtual
Reimplemented from IJK_Thermal_base.
References debug_probe_collision_, IJK_Thermal_base::dummy_double_field_, and probe_collision_debug_field_.
get_interfacial_heat_flux_dispatched()
const IJK_Field_vector3_double & IJK_Thermal_Subresolution::get_interfacial_heat_flux_dispatched () const inline override virtual
Reimplemented from IJK_Thermal_base.
References IJK_Thermal_base::dummy_double_vect_, fluxes_correction_conservations_, and interfacial_heat_flux_dispatched_.
get_interfacial_heat_flux_contrib()
const IJK_Field_vector3_double & IJK_Thermal_Subresolution::get_interfacial_heat_flux_contrib () const inline override virtual
Reimplemented from IJK_Thermal_base.
References IJK_Thermal_base::dummy_double_vect_, fluxes_correction_conservations_, and interfacial_heat_flux_contrib_.
get_interfacial_heat_flux_current()
const IJK_Field_vector3_double & IJK_Thermal_Subresolution::get_interfacial_heat_flux_current () const inline override virtual
Reimplemented from IJK_Thermal_base.
References IJK_Thermal_base::dummy_double_vect_, fluxes_correction_conservations_, and interfacial_heat_flux_current_.
get_disable_post_processing_probes_out_files()
int IJK_Thermal_Subresolution::get_disable_post_processing_probes_out_files () const inline override virtual
Reimplemented from IJK_Thermal_base.
References disable_post_processing_probes_out_files_.
get_first_step_thermals_post()
int IJK_Thermal_Subresolution::get_first_step_thermals_post () inline override virtual
Reimplemented from IJK_Thermal_base.
References first_step_thermals_post_.
set_subproblems_interfaces_fields()
void IJK_Thermal_Subresolution::set_subproblems_interfaces_fields (const Domaine_IJK & splitting) override virtual
Reimplemented from IJK_Thermal_base.
References IJK_Thermal_base::debug_, disable_subresolution_, IJK_One_Dimensional_Subproblems_Interfaces_Fields::initialise(), reference_gfm_on_probes_, IJK_One_Dimensional_Subproblems_Interfaces_Fields::set_subproblems_interfaces_fields(), thermal_local_subproblems_, and IJK_Thermal_base::thermal_local_subproblems_interfaces_fields_.
Referenced by initialize().
reset_subresolution_distributed_vectors()
void IJK_Thermal_Subresolution::reset_subresolution_distributed_vectors () protected
References TRUSTVect< _TYPE_, _SIZE_ >::detach_vect(), first_time_step_explicit_, first_time_step_temporal_, IJK_One_Dimensional_Subproblems::get_effective_subproblems_counter(), points_per_thermal_subproblem_, TRUSTVect< _TYPE_, _SIZE_ >::reset(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), thermal_local_subproblems_, thermal_subproblems_rhs_assembly_, thermal_subproblems_temperature_solution_, and thermal_subproblems_temperature_solution_ini_.
Referenced by compute_thermal_subproblems().
compute_thermal_subproblems()
void IJK_Thermal_Subresolution::compute_thermal_subproblems () override protected virtual
Reimplemented from IJK_Thermal_base.
References approximate_temperature_increment_material_derivative(), Statistiques::begin_count(), compute_local_substep(), compute_radial_subresolution_convection_diffusion_operators(), compute_source_terms_impose_subresolution_boundary_conditions(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::data(), IJK_Thermal_base::debug_, debug_LRS_cells_, debug_probe_collision_, detect_probe_collision(), enable_resize_probe_collision_, Statistiques::end_count(), first_step_thermals_post_, first_time_step_temporal_, first_time_step_varying_probes_, initialise_thermal_subproblems(), interpolate_project_velocities_on_probes(), is_first_time_step_, Statistiques::new_counter(), pre_initialise_thermal_subproblems_any_matrices(), prepare_temporal_schemes(), prepare_thermal_flux_correction(), probe_collision_debug_field_, probe_variations_enabled_, readjust_probe_length_from_vertices_, reajust_probes_length(), IJK_Thermal_base::ref_ijk_ft_, reset_subresolution_distributed_vectors(), solve_thermal_subproblems(), store_previous_temperature_indicator_velocities(), IJK_Thermal_base::temperature_, and update_intersections().
compute_diffusion_increment()
void IJK_Thermal_Subresolution::compute_diffusion_increment () override protected virtual
Implements IJK_Thermal_base.
References Motcles::contient_(), IJK_Thermal_base::cp_liquid_, IJK_Thermal_base::d_temperature_, IJK_Thermal_base::debug_, IJK_Thermal_base::div_coeff_grad_T_, IJK_Thermal_base::div_coeff_grad_T_volume_, IJK_Thermal_base::liste_post_instantanes_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), IJK_Thermal_base::ref_ijk_ft_, IJK_Thermal_base::temperature_diffusion_op_, and IJK_Thermal_base::vol_.
correct_temperature_increment_for_interface_leaving_cell()
void IJK_Thermal_Subresolution::correct_temperature_increment_for_interface_leaving_cell () override protected virtual
Reimplemented from IJK_Thermal_base.
References IJK_Thermal_base::d_temperature_, disable_mixed_cells_increment_, disable_subresolution_, IJK_Thermal_base::ghost_fluid_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), and IJK_Thermal_base::ref_ijk_ft_.
Referenced by set_zero_temperature_increment().
correct_any_temperature_fields_for_eulerian_fluxes()
void IJK_Thermal_Subresolution::correct_any_temperature_fields_for_eulerian_fluxes (IJK_Field_double & temperature) protected
References IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), and IJK_Thermal_base::ref_ijk_ft_.
Referenced by correct_temperature_for_eulerian_fluxes(), and set_field_T_ana().
correct_temperature_for_eulerian_fluxes()
void IJK_Thermal_Subresolution::correct_temperature_for_eulerian_fluxes () override protected virtual
Implements IJK_Thermal_base.
References correct_any_temperature_fields_for_eulerian_fluxes(), override_vapour_mixed_values_, and IJK_Thermal_base::temperature_.
store_temperature_before_extrapolation()
void IJK_Thermal_Subresolution::store_temperature_before_extrapolation () override protected virtual
Reimplemented from IJK_Thermal_base.
References IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::data(), delta_T_subcooled_overheated_, IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), IJK_Thermal_base::ref_ijk_ft_, IJK_Thermal_base::temperature_, and IJK_Thermal_base::temperature_before_extrapolation_.
compare_temperature_fields()
void IJK_Thermal_Subresolution::compare_temperature_fields (const IJK_Field_double & temperature, const IJK_Field_double & temperature_ana, IJK_Field_double & error_temperature_ana, IJK_Field_double & error_temperature_ana_rel) protected
References IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::data(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), and IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk().
Referenced by set_field_T_ana().
evaluate_total_liquid_absolute_parameter()
void IJK_Thermal_Subresolution::evaluate_total_liquid_absolute_parameter (const IJK_Field_double & field, double & total_parameter) protected
References Process::mp_sum(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), IJK_Thermal_base::ref_ijk_ft_, and IJK_Thermal_base::vol_.
Referenced by set_field_T_ana().
evaluate_total_liquid_parameter_squared()
void IJK_Thermal_Subresolution::evaluate_total_liquid_parameter_squared (const IJK_Field_double & field, double & total_parameter) protected
References Process::mp_sum(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), IJK_Thermal_base::ref_ijk_ft_, and IJK_Thermal_base::vol_.
Referenced by set_field_T_ana().
correct_any_temperature_field_for_visu()
void IJK_Thermal_Subresolution::correct_any_temperature_field_for_visu (IJK_Field_double & temperature) protected
References IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), and IJK_Thermal_base::ref_ijk_ft_.
Referenced by correct_temperature_for_visu(), and set_field_T_ana().
correct_temperature_for_visu()
void IJK_Thermal_Subresolution::correct_temperature_for_visu () override protected virtual
Reimplemented from IJK_Thermal_base.
References allow_temperature_correction_for_visu_, Motcles::contient_(), correct_any_temperature_field_for_visu(), IJK_Thermal_base::div_coeff_grad_T_, IJK_Thermal_base::div_coeff_grad_T_volume_, IJK_Thermal_base::liste_post_instantanes_, IJK_Thermal_base::temperature_, IJK_Thermal_base::u_T_convective_, and IJK_Thermal_base::u_T_convective_volume_.
Referenced by compute_temperature_init().
clip_min_temperature_values()
void IJK_Thermal_Subresolution::clip_min_temperature_values () override protected virtual
Reimplemented from IJK_Thermal_base.
References clip_temperature_values_, delta_T_subcooled_overheated_, IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), and IJK_Thermal_base::temperature_.
clip_max_temperature_values()
void IJK_Thermal_Subresolution::clip_max_temperature_values () override protected virtual
Reimplemented from IJK_Thermal_base.
References clip_temperature_values_, IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), IJK_Thermal_base::ref_ijk_ft_, and IJK_Thermal_base::temperature_.
compute_mean_liquid_temperature()
void IJK_Thermal_Subresolution::compute_mean_liquid_temperature () protected
References mean_liquid_temperature_, Process::mp_sum(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), IJK_Thermal_base::ref_ijk_ft_, IJK_Thermal_base::temperature_, and IJK_Thermal_base::vol_.
Referenced by post_process_after_temperature_increment().
compute_overall_probes_parameters()
void IJK_Thermal_Subresolution::compute_overall_probes_parameters () protected
References IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::build(), IJK_Thermal_base::cell_diagonal_, coeff_distance_diagonal_, compute_radial_first_second_order_operators(), IJK_Thermal_base::debug_, disable_subresolution_, dr_, finite_difference_assembler_, first_time_step_temporal_, identity_matrix_explicit_implicit_, implicit_solver_from_previous_probe_field_, points_per_thermal_subproblem_, probe_length_, radial_coordinates_, radial_first_order_operator_, radial_first_order_operator_raw_, radial_second_order_operator_, radial_second_order_operator_raw_, reference_gfm_on_probes_, thermal_subproblems_matrix_assembly_for_solver_, thermal_subproblems_matrix_assembly_for_solver_reduced_, Objet_U_ptr::typer(), and use_sparse_matrix_.
Referenced by initialize().
pre_initialise_thermal_subproblems_any_matrices()
void IJK_Thermal_Subresolution::pre_initialise_thermal_subproblems_any_matrices () protected
References pre_initialise_thermal_subproblems_matrices().
Referenced by compute_thermal_subproblems().
pre_initialise_thermal_subproblems_matrices()
void IJK_Thermal_Subresolution::pre_initialise_thermal_subproblems_matrices () protected
References Process::check_int_overflow(), IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::complete_empty_matrices_initialisation(), disable_subresolution_, finite_difference_assembler_, first_time_step_temporal_, IJK_One_Dimensional_Subproblems::get_effective_subproblems_counter(), identity_matrix_subproblems_, Process::mp_sum(), pre_factor_subproblems_number_, IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::pre_initialise_matrix_subproblems(), pre_initialise_thermal_subproblems_list_, radial_convection_matrix_, radial_diffusion_matrix_, radial_first_order_operator_raw_, radial_second_order_operator_raw_, IJK_Thermal_base::ref_ijk_ft_, thermal_local_subproblems_, and thermal_subproblems_matrix_assembly_.
Referenced by pre_initialise_thermal_subproblems_any_matrices().
interpolate_indicator_on_probes()
void IJK_Thermal_Subresolution::interpolate_indicator_on_probes () protected
References disable_subresolution_, IJK_One_Dimensional_Subproblems::interpolate_indicator_on_probes(), reference_gfm_on_probes_, and thermal_local_subproblems_.
Referenced by detect_probe_collision().
clear_sort_problems_colliding_bubbles()
void IJK_Thermal_Subresolution::clear_sort_problems_colliding_bubbles () protected
References IJK_One_Dimensional_Subproblems::clear_sort_problems_colliding_bubbles(), disable_subresolution_, reference_gfm_on_probes_, and thermal_local_subproblems_.
Referenced by detect_probe_collision().
interpolate_project_velocities_on_probes()
void IJK_Thermal_Subresolution::interpolate_project_velocities_on_probes () protected
References disable_subresolution_, IJK_One_Dimensional_Subproblems::interpolate_project_velocities_on_probes(), reference_gfm_on_probes_, and thermal_local_subproblems_.
Referenced by compute_thermal_subproblems().
reajust_probes_length_collisions()
void IJK_Thermal_Subresolution::reajust_probes_length_collisions () protected
References IJK_One_Dimensional_Subproblems::compute_modified_probe_length(), disable_subresolution_, probe_variations_enabled_, readjust_probe_length_from_vertices_, IJK_One_Dimensional_Subproblems::reajust_probes_length(), and thermal_local_subproblems_.
Referenced by detect_probe_collision().
reajust_probes_length()
void IJK_Thermal_Subresolution::reajust_probes_length () protected
References IJK_One_Dimensional_Subproblems::compute_modified_probe_length(), disable_subresolution_, first_time_step_varying_probes_, IJK_One_Dimensional_Subproblems::get_probe_variations_enabled(), probe_variations_enabled_, probe_variations_priority_, readjust_probe_length_from_vertices_, IJK_One_Dimensional_Subproblems::reajust_probes_length(), and thermal_local_subproblems_.
Referenced by compute_thermal_subproblems().
compute_radial_subresolution_convection_diffusion_operators()
void IJK_Thermal_Subresolution::compute_radial_subresolution_convection_diffusion_operators () protected
References IJK_One_Dimensional_Subproblems::compute_radial_convection_diffusion_operators(), disable_subresolution_, first_time_step_temporal_, identity_matrix_explicit_implicit_, identity_matrix_subproblems_, implicit_solver_from_previous_probe_field_, initialise_identity_matrices(), initialise_identity_matrices_sparse(), initialise_radial_convection_operator(), initialise_radial_convection_operator_sparse(), initialise_radial_diffusion_operator(), initialise_radial_diffusion_operator_sparse(), initialise_sparse_indices_, pre_initialise_thermal_subproblems_list_, radial_convection_matrix_, radial_diffusion_matrix_, radial_first_order_operator_, radial_second_order_operator_, thermal_local_subproblems_, and use_sparse_matrix_.
Referenced by compute_thermal_subproblems().
compute_local_substep()
void IJK_Thermal_Subresolution::compute_local_substep () protected
References IJK_Thermal_base::debug_, disable_subresolution_, first_time_step_temporal_, IJK_One_Dimensional_Subproblems::get_local_dt_cfl(), IJK_One_Dimensional_Subproblems::get_local_dt_cfl_min_delta_xyz(), IJK_One_Dimensional_Subproblems::get_local_min_cfl_time_step_probe_length(), IJK_One_Dimensional_Subproblems::get_local_min_fourier_time_step_probe_length(), IJK_One_Dimensional_Subproblems::get_min_euler_time_step(), local_cfl_time_step_probe_length_, local_diffusion_fourier_priority_, local_dt_cfl_, local_dt_cfl_counter_, local_dt_cfl_min_delta_xyz_, local_dt_fourier_counter_, local_fourier_time_step_probe_length_, nb_iter_explicit_local_, IJK_Thermal_base::ref_ijk_ft_, IJK_One_Dimensional_Subproblems::set_local_time_step(), and thermal_local_subproblems_.
Referenced by compute_thermal_subproblems().
prepare_temporal_schemes()
void IJK_Thermal_Subresolution::prepare_temporal_schemes () protected
References IJK_Thermal_base::debug_, disable_subresolution_, finite_difference_assembler_, first_time_step_temporal_, identity_matrix_subproblems_, implicit_solver_from_previous_probe_field_, IJK_One_Dimensional_Subproblems::prepare_temporal_schemes(), radial_convection_matrix_, radial_diffusion_matrix_, IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::sum_any_matrices_subproblems(), thermal_local_subproblems_, thermal_subproblems_matrix_assembly_, and use_sparse_matrix_.
Referenced by compute_thermal_subproblems().
compute_source_terms_impose_subresolution_boundary_conditions()
void IJK_Thermal_Subresolution::compute_source_terms_impose_subresolution_boundary_conditions () protected
References boundary_condition_end_, boundary_condition_interface_, IJK_One_Dimensional_Subproblems::compute_source_terms_impose_boundary_conditions(), disable_subresolution_, end_boundary_condition_value_, impose_boundary_condition_interface_from_simulation_, impose_user_boundary_condition_end_value_, interfacial_boundary_condition_value_, and thermal_local_subproblems_.
Referenced by compute_thermal_subproblems().
compute_add_subresolution_source_terms()
void IJK_Thermal_Subresolution::compute_add_subresolution_source_terms () protected
compute_subresolution_temporal_explicit_implicit_matrices()
void IJK_Thermal_Subresolution::compute_subresolution_temporal_explicit_implicit_matrices () protected
approximate_temperature_increment_material_derivative()
void IJK_Thermal_Subresolution::approximate_temperature_increment_material_derivative () protected
References IJK_One_Dimensional_Subproblems::approximate_temperature_increment_material_derivative(), disable_subresolution_, reference_gfm_on_probes_, and thermal_local_subproblems_.
Referenced by compute_thermal_subproblems().
compute_radial_first_second_order_operators()
void IJK_Thermal_Subresolution::compute_radial_first_second_order_operators (Matrice & radial_first_order_operator_raw, Matrice & radial_second_order_operator_raw, Matrice & radial_first_order_operator, Matrice & radial_second_order_operator) protected
References compute_first_order_operator(), compute_first_order_operator_raw(), compute_second_order_operator(), compute_second_order_operator_raw(), and dr_.
Referenced by compute_overall_probes_parameters().
compute_first_order_operator_raw()
void IJK_Thermal_Subresolution::compute_first_order_operator_raw (Matrice & radial_first_order_operator) protected
References IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::build(), IJK_Thermal_base::debug_, finite_difference_assembler_, and points_per_thermal_subproblem_.
Referenced by compute_radial_first_second_order_operators().
compute_first_order_operator()
void IJK_Thermal_Subresolution::compute_first_order_operator (Matrice & radial_first_order_operator, double dr) protected
Referenced by compute_radial_first_second_order_operators().
compute_second_order_operator()
void IJK_Thermal_Subresolution::compute_second_order_operator (Matrice & radial_second_order_operator, double dr) protected
Referenced by compute_radial_first_second_order_operators().
compute_second_order_operator_raw()
void IJK_Thermal_Subresolution::compute_second_order_operator_raw (Matrice & radial_second_order_operator) protected
References IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::build(), finite_difference_assembler_, and points_per_thermal_subproblem_.
Referenced by compute_radial_first_second_order_operators().
initialise_identity_matrices()
void IJK_Thermal_Subresolution::initialise_identity_matrices (Matrice & identity_matrix, Matrice & identity_matrix_subproblems) protected
References IJK_Thermal_base::debug_, finite_difference_assembler_, first_time_step_varying_probes_, IJK_One_Dimensional_Subproblems::get_effective_subproblems_counter(), IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::initialise_matrix_subproblems(), and thermal_local_subproblems_.
Referenced by compute_radial_subresolution_convection_diffusion_operators().
initialise_identity_matrices_sparse()
void IJK_Thermal_Subresolution::initialise_identity_matrices_sparse (Matrice & identity_matrix, Matrice & identity_matrix_subproblems) protected
References IJK_Thermal_base::debug_, finite_difference_assembler_, first_indices_sparse_matrix_, first_time_step_varying_probes_, IJK_One_Dimensional_Subproblems::get_effective_subproblems_counter(), initialise_sparse_indices_, IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::initialise_sparse_matrix_subproblems(), IJK_Thermal_base::ref_ijk_ft_, and thermal_local_subproblems_.
Referenced by compute_radial_subresolution_convection_diffusion_operators().
initialise_radial_convection_operator()
void IJK_Thermal_Subresolution::initialise_radial_convection_operator (Matrice & radial_first_order_operator, Matrice & radial_convection_matrix) protected
References IJK_Thermal_base::debug_, finite_difference_assembler_, first_time_step_varying_probes_, IJK_One_Dimensional_Subproblems::get_effective_subproblems_counter(), IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::initialise_matrix_subproblems(), and thermal_local_subproblems_.
Referenced by compute_radial_subresolution_convection_diffusion_operators().
initialise_radial_convection_operator_sparse()
void IJK_Thermal_Subresolution::initialise_radial_convection_operator_sparse (Matrice & radial_first_order_operator, Matrice & radial_convection_matrix) protected
References IJK_Thermal_base::debug_, finite_difference_assembler_, first_indices_sparse_matrix_, first_time_step_varying_probes_, IJK_One_Dimensional_Subproblems::get_effective_subproblems_counter(), initialise_sparse_indices_, IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::initialise_sparse_matrix_subproblems(), IJK_Thermal_base::ref_ijk_ft_, and thermal_local_subproblems_.
Referenced by compute_radial_subresolution_convection_diffusion_operators().
initialise_radial_diffusion_operator()
void IJK_Thermal_Subresolution::initialise_radial_diffusion_operator (Matrice & radial_second_order_operator, Matrice & radial_diffusion_matrix) protected
References IJK_Thermal_base::debug_, finite_difference_assembler_, first_time_step_varying_probes_, IJK_One_Dimensional_Subproblems::get_effective_subproblems_counter(), IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::initialise_matrix_subproblems(), and thermal_local_subproblems_.
Referenced by compute_radial_subresolution_convection_diffusion_operators().
initialise_radial_diffusion_operator_sparse()
void IJK_Thermal_Subresolution::initialise_radial_diffusion_operator_sparse (Matrice & radial_second_order_operator, Matrice & radial_diffusion_matrix) protected
References IJK_Thermal_base::debug_, finite_difference_assembler_, first_indices_sparse_matrix_, first_time_step_varying_probes_, IJK_One_Dimensional_Subproblems::get_effective_subproblems_counter(), initialise_sparse_indices_, IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::initialise_sparse_matrix_subproblems(), IJK_Thermal_base::ref_ijk_ft_, and thermal_local_subproblems_.
Referenced by compute_radial_subresolution_convection_diffusion_operators().
convert_into_sparse_matrix()
void IJK_Thermal_Subresolution::convert_into_sparse_matrix () protected
References Matrice_Bloc::block_to_morse(), finite_difference_assembler_, IJK_One_Dimensional_Subproblems::get_effective_subproblems_counter(), points_per_thermal_subproblem_, pre_initialise_thermal_subproblems_list_, IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::reduce_solver_matrix(), thermal_local_subproblems_, thermal_subproblems_matrix_assembly_, thermal_subproblems_matrix_assembly_for_solver_, thermal_subproblems_matrix_assembly_for_solver_reduced_, thermal_subproblems_matrix_assembly_for_solver_ref_, use_sparse_matrix_, and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by solve_thermal_subproblems().
compute_md_vector()
void IJK_Thermal_Subresolution::compute_md_vector () protected
References MD_Vector::copy(), MD_Vector_tools::creer_tableau_distribue(), md_, one_dimensional_advection_diffusion_thermal_solver_, TRUSTArray< _TYPE_, _SIZE_ >::resize(), TRUST_Vector< _CLASSE_ >::resize(), TRUSTVect< _TYPE_, _SIZE_ >::size(), thermal_subproblems_rhs_assembly_, and thermal_subproblems_temperature_solution_.
Referenced by solve_thermal_subproblems().
retrieve_temperature_solution()
void IJK_Thermal_Subresolution::retrieve_temperature_solution () protected
References disable_subresolution_, reference_gfm_on_probes_, IJK_One_Dimensional_Subproblems::retrieve_radial_quantities(), and thermal_local_subproblems_.
Referenced by solve_thermal_subproblems().
store_previous_temperature_indicator_velocities()
void IJK_Thermal_Subresolution::store_previous_temperature_indicator_velocities () protected
References disable_subresolution_, reconstruct_previous_probe_field_, reference_gfm_on_probes_, IJK_One_Dimensional_Subproblems::store_previous_temperature_indicator_velocities(), and thermal_local_subproblems_.
Referenced by compute_thermal_subproblems().
check_wrong_values_rhs()
void IJK_Thermal_Subresolution::check_wrong_values_rhs () protected
References IJK_Thermal_base::debug_, dr_, TRUSTVect< _TYPE_, _SIZE_ >::size(), and thermal_subproblems_rhs_assembly_.
Referenced by solve_thermal_subproblems().
initialise_thermal_subproblems_list()
void IJK_Thermal_Subresolution::initialise_thermal_subproblems_list () protected
References IJK_One_Dimensional_Subproblems::initialise_thermal_subproblems_list_params(), pre_factor_subproblems_number_, pre_initialise_thermal_subproblems_list_, remove_append_subproblems_, thermal_local_subproblems_, and use_sparse_matrix_.
Referenced by initialize().
initialise_thermal_subproblems()
void IJK_Thermal_Subresolution::initialise_thermal_subproblems () protected
References IJK_One_Dimensional_Subproblems::associate_sub_problem_to_inputs(), IJK_One_Dimensional_Subproblems::associate_variables_for_post_processing(), IJK_One_Dimensional_Subproblems::compute_global_indices(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::data(), IJK_Thermal_base::debug_, debug_LRS_cells_, disable_subresolution_, IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel(), enable_probe_collision_detection_, fluxes_correction_conservations_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost(), IJK_Thermal_base::ref_ijk_ft_, reference_gfm_on_probes_, IJK_One_Dimensional_Subproblems::set_effective_subproblems(), IJK_Thermal_base::temperature_, thermal_local_subproblems_, and zero_liquid_neighbours_.
Referenced by compute_thermal_subproblems().
detect_probe_collision()
void IJK_Thermal_Subresolution::detect_probe_collision () protected
References clear_sort_problems_colliding_bubbles(), enable_probe_collision_detection_, interpolate_indicator_on_probes(), and reajust_probes_length_collisions().
Referenced by compute_thermal_subproblems().
solve_thermal_subproblems()
void IJK_Thermal_Subresolution::solve_thermal_subproblems () protected
References Statistiques::begin_count(), IJK_SolveSys_FD_thermal::cast_direct_solver_by_default(), check_wrong_values_rhs(), compute_md_vector(), convert_into_sparse_matrix(), disable_subresolution_, Statistiques::end_count(), Objet_U_ptr::est_nul(), first_time_step_explicit_, first_time_step_temporal_, nb_iter_explicit_local_, Statistiques::new_counter(), one_dimensional_advection_diffusion_thermal_solver_, one_dimensional_advection_diffusion_thermal_solver_implicit_, SolveurSys::resoudre_systeme(), retrieve_temperature_solution(), thermal_subproblems_rhs_assembly_, thermal_subproblems_temperature_solution_, and thermal_subproblems_temperature_solution_ini_.
Referenced by compute_thermal_subproblems().
prepare_thermal_flux_correction()
void IJK_Thermal_Subresolution::prepare_thermal_flux_correction () protected
References IJK_Thermal_base::corrige_flux_, disable_subresolution_, and Corrige_flux_FT_base::update().
Referenced by compute_thermal_subproblems().
compute_min_max_reachable_fluxes()
void IJK_Thermal_Subresolution::compute_min_max_reachable_fluxes () protected
References cell_faces_neighbours_corrected_all_bool_, cell_faces_neighbours_corrected_convective_, cell_faces_neighbours_corrected_diffusive_, cell_faces_neighbours_corrected_min_max_bool_, cell_faces_neighbours_corrected_velocity_temperature_, complete_convective_flux_frame_of_reference(), Corrige_flux_FT_base::compute_cell_neighbours_faces_indices_to_correct(), Corrige_flux_FT_base::compute_min_max_ijk_any_reachable_fluxes(), IJK_Thermal_base::corrige_flux_, neighbours_faces_weighting_colinearity_, neighbours_temperature_to_correct_, neighbours_temperature_to_correct_trimmed_, and Corrige_flux_FT_base::replace_cell_neighbours_thermal_convective_diffusive_fluxes_faces().
Referenced by compute_convective_diffusive_fluxes_face_centre().
complete_convective_flux_frame_of_reference()
void IJK_Thermal_Subresolution::complete_convective_flux_frame_of_reference () protected
References cell_faces_neighbours_corrected_convective_, cell_faces_neighbours_corrected_convective_frame_of_reference_, cell_faces_neighbours_corrected_velocity_temperature_, convective_flux_correction_, IJK_Thermal_base::cp_liquid_, keep_first_reachable_fluxes_, IJK_Thermal_base::ref_ijk_ft_, IJK_Thermal_base::store_flux_operators_for_energy_balance_, and use_reachable_fluxes_.
Referenced by compute_min_max_reachable_fluxes().
update_intersections()
void IJK_Thermal_Subresolution::update_intersections () override protected virtual
Reimplemented from IJK_Thermal_base.
References IJK_Thermal_base::corrige_flux_, disable_subresolution_, and Corrige_flux_FT_base::update_intersections().
Referenced by compute_thermal_subproblems().
compute_convective_diffusive_fluxes_face_centre()
void IJK_Thermal_Subresolution::compute_convective_diffusive_fluxes_face_centre () override protected virtual
Reimplemented from IJK_Thermal_base.
References Statistiques::begin_count(), complete_thermal_fluxes_face_centre(), Corrige_flux_FT_base::compute_cell_neighbours_faces_indices_for_spherical_correction(), compute_convective_fluxes_face_centre(), compute_diffusive_fluxes_face_centre(), compute_min_max_reachable_fluxes(), IJK_Thermal_base::conv_temperature_negligible_, IJK_Thermal_base::corrige_flux_, IJK_Thermal_base::diff_temperature_negligible_, IJK_One_Dimensional_Subproblems::dispatch_interfacial_heat_flux_correction(), Statistiques::end_count(), fluxes_correction_conservations_, ijk_indices_flux_contrib_, Corrige_flux_FT_base::initialise_cell_neighbours_indices_to_correct(), interfacial_heat_flux_contrib_, interfacial_heat_flux_current_, IJK_Thermal_base::n_iter_distance_, Statistiques::new_counter(), thermal_flux_out_contrib_, and thermal_local_subproblems_.
compute_convective_fluxes_face_centre()
void IJK_Thermal_Subresolution::compute_convective_fluxes_face_centre () override protected virtual
Reimplemented from IJK_Thermal_base.
References Corrige_flux_FT_base::compute_thermal_convective_fluxes(), convective_flux_correction_, IJK_Thermal_base::corrige_flux_, diffusive_flux_correction_, disable_subresolution_, fluxes_correction_conservations_, and use_reachable_fluxes_.
Referenced by compute_convective_diffusive_fluxes_face_centre().
compute_diffusive_fluxes_face_centre()
void IJK_Thermal_Subresolution::compute_diffusive_fluxes_face_centre () override protected virtual
Reimplemented from IJK_Thermal_base.
References Corrige_flux_FT_base::compute_thermal_diffusive_fluxes(), IJK_Thermal_base::corrige_flux_, diffusive_flux_correction_, disable_subresolution_, fluxes_correction_conservations_, and use_reachable_fluxes_.
Referenced by compute_convective_diffusive_fluxes_face_centre().
complete_thermal_fluxes_face_centre()
void IJK_Thermal_Subresolution::complete_thermal_fluxes_face_centre (const int & fluxes_correction_conservations) protected
References Corrige_flux_FT_base::complete_thermal_fluxes_face_centre(), convective_flux_correction_, IJK_Thermal_base::corrige_flux_, diffusive_flux_correction_, disable_subresolution_, fluxes_correction_conservations_, and use_reachable_fluxes_.
Referenced by compute_convective_diffusive_fluxes_face_centre().
compute_temperature_cell_centres()
void IJK_Thermal_Subresolution::compute_temperature_cell_centres (const int first_corr) override protected virtual
Reimplemented from IJK_Thermal_base.
References compute_temperature_cell_centres_first_correction(), compute_temperature_cell_centres_second_correction(), and disable_subresolution_.
compute_temperature_cell_centres_first_correction()
void IJK_Thermal_Subresolution::compute_temperature_cell_centres_first_correction () protected
References Corrige_flux_FT_base::compute_temperature_cell_centre(), Corrige_flux_FT_base::compute_temperature_cell_centre_neighbours(), correct_first_iter_deactivate_cell_neighbours_, correct_temperature_cell_neighbours_first_iter_, IJK_Thermal_base::corrige_flux_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::data(), IJK_Thermal_base::debug_, find_temperature_cell_neighbours_, keep_max_flux_correction_, neighbours_temperature_colinearity_weighting_, neighbours_temperature_to_correct_, neighbours_weighting_, IJK_Thermal_base::ref_ijk_ft_, Corrige_flux_FT_base::replace_temperature_cell_centre_neighbours(), replace_temperature_cell_centres_neighbours(), Corrige_flux_FT_base::set_correction_cell_neighbours(), smooth_temperature_field_, IJK_Thermal_base::temperature_, temperature_cell_neighbours_, temperature_cell_neighbours_debug_, and use_temperature_cell_neighbours_.
Referenced by compute_temperature_cell_centres().
compute_temperature_cell_centres_second_correction()
void IJK_Thermal_Subresolution::compute_temperature_cell_centres_second_correction () protected
References IJK_Thermal_base::debug_, disable_mixed_cells_increment_, keep_first_reachable_fluxes_, replace_temperature_cell_centres_neighbours(), and use_reachable_fluxes_.
Referenced by compute_temperature_cell_centres().
replace_temperature_cell_centres_neighbours()
void IJK_Thermal_Subresolution::replace_temperature_cell_centres_neighbours (const int & use_neighbours_temperature_to_correct_trimmed) protected
References Corrige_flux_FT_base::compute_temperature_cell_centre(), correct_temperature_cell_neighbours_first_iter_, IJK_Thermal_base::corrige_flux_, keep_first_reachable_fluxes_, neighbours_temperature_colinearity_weighting_, neighbours_temperature_to_correct_, neighbours_temperature_to_correct_trimmed_, IJK_Thermal_base::ref_ijk_ft_, Corrige_flux_FT_base::replace_temperature_cell_centre_neighbours(), IJK_Thermal_base::temperature_, temperature_cell_neighbours_, and use_temperature_cell_neighbours_.
Referenced by compute_temperature_cell_centres_first_correction(), and compute_temperature_cell_centres_second_correction().
prepare_ij_fluxes_k_layers()
void IJK_Thermal_Subresolution::prepare_ij_fluxes_k_layers () override protected virtual
Reimplemented from IJK_Thermal_base.
References cell_faces_corrected_bool_, cell_faces_corrected_convective_, cell_faces_corrected_diffusive_, Corrige_flux_FT_base::compute_ijk_pure_faces_indices(), convective_flux_correction_, IJK_Thermal_base::corrige_flux_, diffusive_flux_correction_, disable_subresolution_, Corrige_flux_FT_base::sort_ijk_intersections_subproblems_indices_by_k_layers(), Corrige_flux_FT_base::store_cell_faces_corrected(), store_cell_faces_corrected_, and use_reachable_fluxes_.
set_zero_temperature_increment()
void IJK_Thermal_Subresolution::set_zero_temperature_increment () override protected virtual
Reimplemented from IJK_Thermal_base.
References correct_temperature_increment_for_interface_leaving_cell(), IJK_Thermal_base::corrige_flux_, IJK_Thermal_base::d_temperature_, disable_mixed_cells_increment_, disable_subresolution_, and Corrige_flux_FT_base::set_zero_temperature_increment().
clean_thermal_subproblems()
void IJK_Thermal_Subresolution::clean_thermal_subproblems () override protected virtual
Reimplemented from IJK_Thermal_base.
References IJK_One_Dimensional_Subproblems::clean(), Corrige_flux_FT_base::clear_vectors(), IJK_Thermal_base::corrige_flux_, disable_subresolution_, IJK_Thermal_base::ref_ijk_ft_, reference_gfm_on_probes_, and thermal_local_subproblems_.
clean_ijk_intersections()
void IJK_Thermal_Subresolution::clean_ijk_intersections () override protected virtual
Reimplemented from IJK_Thermal_base.
References Corrige_flux_FT_base::clean(), IJK_Thermal_base::corrige_flux_, and disable_subresolution_.
clean_add_thermal_subproblems()
void IJK_Thermal_Subresolution::clean_add_thermal_subproblems () protected
enforce_periodic_temperature_boundary_value()
void IJK_Thermal_Subresolution::enforce_periodic_temperature_boundary_value () override protected virtual
Reimplemented from IJK_Thermal_base.
References delta_T_subcooled_overheated_, disable_subresolution_, enforce_periodic_boundary_value_, IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_domaine(), Domaine_IJK::get_nb_elem_tot(), Domaine_IJK::get_offset_local(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), IJK_Thermal_base::ref_ijk_ft_, stencil_periodic_boundary_value_, and IJK_Thermal_base::temperature_.
correct_operators_for_visu()
void IJK_Thermal_Subresolution::correct_operators_for_visu () override protected virtual
Reimplemented from IJK_Thermal_base.
References IJK_Thermal_base::conv_temperature_negligible_, IJK_Thermal_base::diff_temperature_negligible_, IJK_Thermal_base::div_coeff_grad_T_volume_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), IJK_Thermal_base::ref_ijk_ft_, and IJK_Thermal_base::u_T_convective_volume_.
get_modified_time()
double IJK_Thermal_Subresolution::get_modified_time () override protected virtual
Reimplemented from IJK_Thermal_base.
References disable_spherical_diffusion_start_, modified_time_init_, and IJK_Thermal_base::ref_ijk_ft_.
compute_temperature_init()
void IJK_Thermal_Subresolution::compute_temperature_init () override protected virtual
Reimplemented from IJK_Thermal_base.
References approx_erf_inverse(), compute_quasi_static_spherical_diffusion_expression(), compute_spherical_steady_dirichlet_left_right_derivative_value(), compute_spherical_steady_dirichlet_left_right_integral(), IJK_Thermal_base::compute_temperature_init(), correct_temperature_for_visu(), IJK_Thermal_base::cp_liquid_, IJK_Thermal_base::debug_, delta_T_subcooled_overheated_, derivative_criteria, disable_spherical_diffusion_start_, find_time_dichotomy_derivative(), find_time_dichotomy_integral(), get_probes_length(), get_time_inflection_derivative(), integral_criteria, IJK_Thermal_base::lambda_liquid_, local_criteria, modified_time_init_, probes_end_value_coeff_, IJK_Thermal_base::ref_ijk_ft_, set_field_temperature_per_bubble(), single_centred_bubble_, single_centred_bubble_radius_ini_, IJK_Thermal_base::temperature_for_ini_per_bubble_, temperature_ini_type_, time_criteria, and time_ini_user_.
Referenced by recompute_temperature_init().
recompute_temperature_init()
void IJK_Thermal_Subresolution::recompute_temperature_init () override protected virtual
Reimplemented from IJK_Thermal_base.
References compute_temperature_init().
set_field_temperature_per_bubble()
void IJK_Thermal_Subresolution::set_field_temperature_per_bubble (const int index_bubble) protected
References delta_T_subcooled_overheated_, probes_end_value_coeff_, IJK_Thermal_base::ref_ijk_ft_, IJK_Thermal_base::temperature_, and IJK_Thermal_base::temperature_for_ini_per_bubble_.
Referenced by compute_temperature_init().
compute_quasi_static_spherical_diffusion_expression()
Nom IJK_Thermal_Subresolution::compute_quasi_static_spherical_diffusion_expression (const double & time_scope, const int index_bubble, const int index_bubble_real) protected
References computed_centred_bubble_start_, generate_expression_temperature_ini(), IJK_Thermal_base::ref_ijk_ft_, and IJK_Thermal_base::temperature_.
Referenced by compute_temperature_init(), and set_field_T_ana().
generate_expression_temperature_ini()
Nom IJK_Thermal_Subresolution::generate_expression_temperature_ini (const double & time_scope, const double x, const double y, const double z) protected
References IJK_Thermal_base::cp_liquid_, delta_T_subcooled_overheated_, IJK_Thermal_base::lambda_liquid_, IJK_Thermal_base::ref_ijk_ft_, and single_centred_bubble_radius_ini_.
Referenced by compute_quasi_static_spherical_diffusion_expression().
approx_erf_inverse()
void IJK_Thermal_Subresolution::approx_erf_inverse (const double & x, double & res) protected
Referenced by compute_temperature_init().
set_field_T_ana()
void IJK_Thermal_Subresolution::set_field_T_ana () override protected virtual
Reimplemented from IJK_Thermal_base.
References compare_temperature_fields(), compute_quasi_static_spherical_diffusion_expression(), Motcles::contient_(), correct_any_temperature_field_for_visu(), correct_any_temperature_fields_for_eulerian_fluxes(), delta_T_subcooled_overheated_, IJK_Thermal_base::ecart_t_ana_, IJK_Thermal_base::ecart_t_ana_rel_, error_temperature_ana_rel_total_, error_temperature_ana_squared_total_, error_temperature_ana_total_, evaluate_total_liquid_absolute_parameter(), evaluate_total_liquid_parameter_squared(), IJK_Thermal_base::liste_post_instantanes_, IJK_Thermal_base::ref_ijk_ft_, spherical_diffusion_, IJK_Thermal_base::temperature_, and IJK_Thermal_base::temperature_ana_.
calculer_ecart_T_ana()
void IJK_Thermal_Subresolution::calculer_ecart_T_ana () inline override protected virtual
Reimplemented from IJK_Thermal_base.
compute_spherical_steady_dirichlet_left_right_value()
double IJK_Thermal_Subresolution::compute_spherical_steady_dirichlet_left_right_value (const double & r) protected
References delta_T_subcooled_overheated_, get_probes_length(), and single_centred_bubble_radius_ini_.
compute_spherical_steady_dirichlet_left_right_derivative_value()
double IJK_Thermal_Subresolution::compute_spherical_steady_dirichlet_left_right_derivative_value (const double & r, const double & temperature_prev) protected
References get_probes_length(), and single_centred_bubble_radius_ini_.
Referenced by compute_temperature_init().
compute_spherical_steady_dirichlet_left_right_integral()
double IJK_Thermal_Subresolution::compute_spherical_steady_dirichlet_left_right_integral (const double & temperature_end_prev) protected
References get_probes_length(), and single_centred_bubble_radius_ini_.
Referenced by compute_temperature_init().
find_time_dichotomy_integral()
double IJK_Thermal_Subresolution::find_time_dichotomy_integral (const double & temperature_integral, double & temperature_end_prev) protected
References IJK_Thermal_base::cp_liquid_, IJK_Thermal_base::debug_, delta_T_subcooled_overheated_, get_probes_length(), IJK_Thermal_base::lambda_liquid_, IJK_Thermal_base::ref_ijk_ft_, and single_centred_bubble_radius_ini_.
Referenced by compute_temperature_init().
compute_Nusselt_spherical_diffusion()
void IJK_Thermal_Subresolution::compute_Nusselt_spherical_diffusion () protected
References IJK_Thermal_base::cp_liquid_, delta_T_subcooled_overheated_, heat_flux_spherical_, IJK_Thermal_base::lambda_liquid_, mean_liquid_temperature_, nusselt_spherical_diffusion_, nusselt_spherical_diffusion_liquid_, IJK_Thermal_base::ref_ijk_ft_, and single_centred_bubble_radius_ini_.
Referenced by post_process_after_temperature_increment().
get_time_inflection_derivative()
double IJK_Thermal_Subresolution::get_time_inflection_derivative (double & temperature_end_min) protected
References IJK_Thermal_base::cp_liquid_, delta_T_subcooled_overheated_, get_probes_length(), IJK_Thermal_base::lambda_liquid_, IJK_Thermal_base::ref_ijk_ft_, and single_centred_bubble_radius_ini_.
Referenced by compute_temperature_init(), and find_time_dichotomy_derivative().
find_time_dichotomy_derivative()
double IJK_Thermal_Subresolution::find_time_dichotomy_derivative (const double & temperature_derivative, double & temperature_limit_left, double & temperature_limit_right) protected
References IJK_Thermal_base::cp_liquid_, IJK_Thermal_base::debug_, delta_T_subcooled_overheated_, get_probes_length(), get_time_inflection_derivative(), IJK_Thermal_base::lambda_liquid_, IJK_Thermal_base::ref_ijk_ft_, and single_centred_bubble_radius_ini_.
Referenced by compute_temperature_init().
compute_rho_cp_u_mean()
double IJK_Thermal_Subresolution::compute_rho_cp_u_mean (const IJK_Field_double & vx) inline override protected virtual
Reimplemented from IJK_Thermal_base.
References IJK_Thermal_base::compute_rho_cp_u_mean().
compare_fluxes_thermal_subproblems()
void IJK_Thermal_Subresolution::compare_fluxes_thermal_subproblems () override protected virtual
Reimplemented from IJK_Thermal_base.
References cell_faces_neighbours_corrected_convective_frame_of_reference_, cell_faces_neighbours_corrected_diffusive_, IJK_One_Dimensional_Subproblems::compare_fluxes_thermal_subproblems(), IJK_Thermal_base::conv_temperature_negligible_, IJK_Thermal_base::diff_temperature_negligible_, disable_subresolution_, IJK_Thermal_base::div_coeff_grad_T_raw_, keep_first_reachable_fluxes_, reference_gfm_on_probes_, IJK_Thermal_base::rho_cp_u_T_convective_raw_, IJK_Thermal_base::store_flux_operators_for_energy_balance_, thermal_local_subproblems_, and use_reachable_fluxes_.
Friends And Related Function Documentation
IJK_One_Dimensional_Subproblems
friend class IJK_One_Dimensional_Subproblems friend
IJK_One_Dimensional_Subproblem
friend class IJK_One_Dimensional_Subproblem friend
Member Data Documentation
info_obj
const Type_info IJK_Thermal_Subresolution::info_obj static
enable_probe_collision_detection_
int IJK_Thermal_Subresolution::enable_probe_collision_detection_ = 0 protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), detect_probe_collision(), initialise_thermal_subproblems(), printOn(), and set_param().
enable_resize_probe_collision_
int IJK_Thermal_Subresolution::enable_resize_probe_collision_ = 0 protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), compute_thermal_subproblems(), printOn(), and set_param().
debug_probe_collision_
int IJK_Thermal_Subresolution::debug_probe_collision_ = 0 protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), compute_thermal_subproblems(), get_probe_collision_debug_field(), initialize(), printOn(), and set_param().
probe_collision_debug_field_
IJK_Field_double IJK_Thermal_Subresolution::probe_collision_debug_field_ protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), compute_thermal_subproblems(), get_probe_collision_debug_field(), and initialize().
reference_gfm_on_probes_
int IJK_Thermal_Subresolution::reference_gfm_on_probes_ = 0 protected
Referenced by approximate_temperature_increment_material_derivative(), IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), IJK_One_Dimensional_Subproblems::associate_variables_for_post_processing(), clean_thermal_subproblems(), clear_sort_problems_colliding_bubbles(), compare_fluxes_thermal_subproblems(), compute_overall_probes_parameters(), initialise_thermal_subproblems(), initialize(), interpolate_indicator_on_probes(), interpolate_project_velocities_on_probes(), printOn(), retrieve_temperature_solution(), set_param(), set_subproblems_interfaces_fields(), set_thermal_subresolution_outputs(), and store_previous_temperature_indicator_velocities().
compute_normal_derivatives_on_reference_probes_
int IJK_Thermal_Subresolution::compute_normal_derivatives_on_reference_probes_ = 0 protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), initialize(), printOn(), and set_param().
disable_probe_weak_gradient_
int IJK_Thermal_Subresolution::disable_probe_weak_gradient_ = 0 protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), printOn(), and set_param().
disable_probe_weak_gradient_gfm_
int IJK_Thermal_Subresolution::disable_probe_weak_gradient_gfm_ = 0 protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), printOn(), and set_param().
reconstruct_previous_probe_field_
int IJK_Thermal_Subresolution::reconstruct_previous_probe_field_ = 0 protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), printOn(), set_param(), and store_previous_temperature_indicator_velocities().
implicit_solver_from_previous_probe_field_
int IJK_Thermal_Subresolution::implicit_solver_from_previous_probe_field_ = 0 protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), compute_overall_probes_parameters(), compute_radial_subresolution_convection_diffusion_operators(), prepare_temporal_schemes(), printOn(), and set_param().
disable_spherical_diffusion_start_
int IJK_Thermal_Subresolution::disable_spherical_diffusion_start_ = 0 protected
Referenced by compute_temperature_init(), get_modified_time(), initialize(), printOn(), and set_param().
single_centred_bubble_
int IJK_Thermal_Subresolution::single_centred_bubble_ = 1 protected
Referenced by compute_temperature_init().
computed_centred_bubble_start_
int IJK_Thermal_Subresolution::computed_centred_bubble_start_ = 1 protected
Referenced by compute_quasi_static_spherical_diffusion_expression().
single_centred_bubble_radius_ini_
double IJK_Thermal_Subresolution::single_centred_bubble_radius_ini_ = 1.e-3 protected
Referenced by compute_Nusselt_spherical_diffusion(), IJK_One_Dimensional_Subproblems::compute_overall_bubbles_quantities(), compute_spherical_steady_dirichlet_left_right_derivative_value(), compute_spherical_steady_dirichlet_left_right_integral(), compute_spherical_steady_dirichlet_left_right_value(), compute_temperature_init(), find_time_dichotomy_derivative(), find_time_dichotomy_integral(), generate_expression_temperature_ini(), and get_time_inflection_derivative().
probes_end_value_start_
double IJK_Thermal_Subresolution::probes_end_value_start_ = -1 protected
probes_end_value_coeff_
double IJK_Thermal_Subresolution::probes_end_value_coeff_ = 0.05 protected
Referenced by compute_temperature_init(), printOn(), set_field_temperature_per_bubble(), and set_param().
temperature_ini_type_
int IJK_Thermal_Subresolution::temperature_ini_type_ = 1 protected
Referenced by compute_temperature_init(), printOn(), and set_param().
modified_time_init_
double IJK_Thermal_Subresolution::modified_time_init_ = 0. protected
Referenced by compute_temperature_init(), get_modified_time(), printOn(), and set_param().
spherical_diffusion_
int IJK_Thermal_Subresolution::spherical_diffusion_ = 1 protected
Referenced by set_field_T_ana().
nusselt_spherical_diffusion_
double IJK_Thermal_Subresolution::nusselt_spherical_diffusion_ = 2. protected
Referenced by compute_Nusselt_spherical_diffusion(), and IJK_One_Dimensional_Subproblems::compute_overall_bubbles_quantities().
nusselt_spherical_diffusion_liquid_
double IJK_Thermal_Subresolution::nusselt_spherical_diffusion_liquid_ = 2. protected
Referenced by compute_Nusselt_spherical_diffusion(), and IJK_One_Dimensional_Subproblems::compute_overall_bubbles_quantities().
heat_flux_spherical_
double IJK_Thermal_Subresolution::heat_flux_spherical_ = 0. protected
Referenced by compute_Nusselt_spherical_diffusion(), and IJK_One_Dimensional_Subproblems::compute_overall_bubbles_quantities().
mean_liquid_temperature_
double IJK_Thermal_Subresolution::mean_liquid_temperature_ = -1 protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), compute_mean_liquid_temperature(), compute_Nusselt_spherical_diffusion(), and IJK_One_Dimensional_Subproblems::compute_overall_bubbles_quantities().
time_ini_user_
double IJK_Thermal_Subresolution::time_ini_user_ = 0. protected
Referenced by compute_temperature_init(), printOn(), and set_param().
disable_mixed_cells_increment_
int IJK_Thermal_Subresolution::disable_mixed_cells_increment_ = 0 protected
Referenced by compute_temperature_cell_centres_second_correction(), correct_temperature_increment_for_interface_leaving_cell(), initialize(), set_param(), and set_zero_temperature_increment().
enable_mixed_cells_increment_
int IJK_Thermal_Subresolution::enable_mixed_cells_increment_ = 1 protected
Referenced by initialize(), printOn(), and set_param().
allow_temperature_correction_for_visu_
int IJK_Thermal_Subresolution::allow_temperature_correction_for_visu_ = 0 protected
Referenced by correct_temperature_for_visu(), printOn(), and set_param().
disable_subresolution_
int IJK_Thermal_Subresolution::disable_subresolution_ = 0 protected
Referenced by approximate_temperature_increment_material_derivative(), clean_ijk_intersections(), clean_thermal_subproblems(), clear_sort_problems_colliding_bubbles(), compare_fluxes_thermal_subproblems(), complete_thermal_fluxes_face_centre(), compute_convective_fluxes_face_centre(), compute_diffusive_fluxes_face_centre(), compute_local_substep(), compute_overall_probes_parameters(), compute_radial_subresolution_convection_diffusion_operators(), compute_source_terms_impose_subresolution_boundary_conditions(), compute_temperature_cell_centres(), correct_temperature_increment_for_interface_leaving_cell(), enforce_periodic_temperature_boundary_value(), initialise_thermal_subproblems(), initialize(), interpolate_indicator_on_probes(), interpolate_project_velocities_on_probes(), pre_initialise_thermal_subproblems_matrices(), prepare_ij_fluxes_k_layers(), prepare_temporal_schemes(), prepare_thermal_flux_correction(), printOn(), reajust_probes_length(), reajust_probes_length_collisions(), retrieve_temperature_solution(), set_param(), set_subproblems_interfaces_fields(), set_thermal_subresolution_outputs(), set_zero_temperature_increment(), solve_thermal_subproblems(), store_previous_temperature_indicator_velocities(), and update_intersections().
diffusive_flux_correction_
int IJK_Thermal_Subresolution::diffusive_flux_correction_ = 0 protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), complete_thermal_fluxes_face_centre(), compute_convective_fluxes_face_centre(), compute_diffusive_fluxes_face_centre(), get_cell_faces_corrected_bool(), get_cell_faces_corrected_convective(), get_cell_faces_corrected_diffusive(), get_cell_faces_neighbours_corrected_diffusive(), initialize(), prepare_ij_fluxes_k_layers(), printOn(), readOn(), and set_param().
convective_flux_correction_
int IJK_Thermal_Subresolution::convective_flux_correction_ = 0 protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), complete_convective_flux_frame_of_reference(), complete_thermal_fluxes_face_centre(), compute_convective_fluxes_face_centre(), get_cell_faces_corrected_bool(), get_cell_faces_corrected_convective(), get_cell_faces_corrected_diffusive(), get_cell_faces_neighbours_corrected_convective(), get_cell_faces_neighbours_corrected_convective_frame_of_ref(), get_cell_faces_neighbours_corrected_velocity_temperature(), initialize(), prepare_ij_fluxes_k_layers(), printOn(), readOn(), and set_param().
fluxes_correction_conservations_
int IJK_Thermal_Subresolution::fluxes_correction_conservations_ = 0 protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), complete_thermal_fluxes_face_centre(), compute_convective_diffusive_fluxes_face_centre(), compute_convective_fluxes_face_centre(), compute_diffusive_fluxes_face_centre(), get_interfacial_heat_flux_contrib(), get_interfacial_heat_flux_current(), get_interfacial_heat_flux_dispatched(), initialise_thermal_subproblems(), initialize(), printOn(), and set_param().
conserve_max_interfacial_fluxes_
int IJK_Thermal_Subresolution::conserve_max_interfacial_fluxes_ = 0 protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), printOn(), and set_param().
fluxes_corrections_weighting_
int IJK_Thermal_Subresolution::fluxes_corrections_weighting_ = 0 protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), printOn(), and set_param().
impose_fo_flux_correction_
int IJK_Thermal_Subresolution::impose_fo_flux_correction_ = 1 protected
Referenced by initialize().
disable_fo_flux_correction_
int IJK_Thermal_Subresolution::disable_fo_flux_correction_ = 0 protected
Referenced by initialize(), printOn(), and set_param().
subproblem_temperature_extension_
int IJK_Thermal_Subresolution::subproblem_temperature_extension_ = 0 protected
override_vapour_mixed_values_
int IJK_Thermal_Subresolution::override_vapour_mixed_values_ = 0 protected
Referenced by correct_temperature_for_eulerian_fluxes(), IJK_Thermal_Multiple_Subresolutions::correct_temperature_vapour_for_eulerian_fluxes(), printOn(), readOn(), and set_param().
thermal_local_subproblems_
IJK_One_Dimensional_Subproblems IJK_Thermal_Subresolution::thermal_local_subproblems_ protected
Referenced by approximate_temperature_increment_material_derivative(), clean_thermal_subproblems(), clear_sort_problems_colliding_bubbles(), compare_fluxes_thermal_subproblems(), compute_convective_diffusive_fluxes_face_centre(), compute_local_substep(), compute_radial_subresolution_convection_diffusion_operators(), compute_source_terms_impose_subresolution_boundary_conditions(), convert_into_sparse_matrix(), initialise_identity_matrices(), initialise_identity_matrices_sparse(), initialise_radial_convection_operator(), initialise_radial_convection_operator_sparse(), initialise_radial_diffusion_operator(), initialise_radial_diffusion_operator_sparse(), initialise_thermal_subproblems(), initialise_thermal_subproblems_list(), initialize(), interpolate_indicator_on_probes(), interpolate_project_velocities_on_probes(), pre_initialise_thermal_subproblems_matrices(), prepare_temporal_schemes(), reajust_probes_length(), reajust_probes_length_collisions(), reset_subresolution_distributed_vectors(), retrieve_temperature_solution(), set_subproblems_interfaces_fields(), set_thermal_subresolution_outputs(), and store_previous_temperature_indicator_velocities().
points_per_thermal_subproblem_
int IJK_Thermal_Subresolution::points_per_thermal_subproblem_ = 32 protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), IJK_One_Dimensional_Subproblems::associate_variables_for_post_processing(), compute_first_order_operator_raw(), compute_overall_probes_parameters(), compute_second_order_operator_raw(), convert_into_sparse_matrix(), printOn(), reset_subresolution_distributed_vectors(), and set_param().
coeff_distance_diagonal_
double IJK_Thermal_Subresolution::coeff_distance_diagonal_ = 2. protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), compute_ghost_cell_numbers_for_subproblems(), compute_overall_probes_parameters(), get_probes_length(), printOn(), and set_param().
probe_length_
double IJK_Thermal_Subresolution::probe_length_ = 0. protected
Referenced by compute_overall_probes_parameters().
dr_
double IJK_Thermal_Subresolution::dr_ = 0. protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), check_wrong_values_rhs(), compute_overall_probes_parameters(), and compute_radial_first_second_order_operators().
radial_coordinates_
DoubleVect IJK_Thermal_Subresolution::radial_coordinates_ protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), and compute_overall_probes_parameters().
identity_matrix_explicit_implicit_
Matrice IJK_Thermal_Subresolution::identity_matrix_explicit_implicit_ protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), compute_overall_probes_parameters(), and compute_radial_subresolution_convection_diffusion_operators().
radial_first_order_operator_raw_
Matrice IJK_Thermal_Subresolution::radial_first_order_operator_raw_ protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), compute_overall_probes_parameters(), and pre_initialise_thermal_subproblems_matrices().
radial_second_order_operator_raw_
Matrice IJK_Thermal_Subresolution::radial_second_order_operator_raw_ protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), compute_overall_probes_parameters(), and pre_initialise_thermal_subproblems_matrices().
radial_first_order_operator_
Matrice IJK_Thermal_Subresolution::radial_first_order_operator_ protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), compute_overall_probes_parameters(), and compute_radial_subresolution_convection_diffusion_operators().
radial_second_order_operator_
Matrice IJK_Thermal_Subresolution::radial_second_order_operator_ protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), compute_overall_probes_parameters(), and compute_radial_subresolution_convection_diffusion_operators().
identity_matrix_subproblems_
Matrice IJK_Thermal_Subresolution::identity_matrix_subproblems_ protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), compute_radial_subresolution_convection_diffusion_operators(), pre_initialise_thermal_subproblems_matrices(), and prepare_temporal_schemes().
radial_diffusion_matrix_
Matrice IJK_Thermal_Subresolution::radial_diffusion_matrix_ protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), compute_radial_subresolution_convection_diffusion_operators(), pre_initialise_thermal_subproblems_matrices(), and prepare_temporal_schemes().
radial_convection_matrix_
Matrice IJK_Thermal_Subresolution::radial_convection_matrix_ protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), compute_radial_subresolution_convection_diffusion_operators(), pre_initialise_thermal_subproblems_matrices(), and prepare_temporal_schemes().
radial_diffusion_matrix_test_
Matrice IJK_Thermal_Subresolution::radial_diffusion_matrix_test_ protected
first_indices_sparse_matrix_
FixedVector<ArrOfInt, 6> IJK_Thermal_Subresolution::first_indices_sparse_matrix_ protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), initialise_identity_matrices_sparse(), initialise_radial_convection_operator_sparse(), and initialise_radial_diffusion_operator_sparse().
initialise_sparse_indices_
int IJK_Thermal_Subresolution::initialise_sparse_indices_ = 0 protected
Referenced by compute_radial_subresolution_convection_diffusion_operators(), initialise_identity_matrices_sparse(), initialise_radial_convection_operator_sparse(), and initialise_radial_diffusion_operator_sparse().
finite_difference_assembler_
IJK_Finite_Difference_One_Dimensional_Matrix_Assembler IJK_Thermal_Subresolution::finite_difference_assembler_ protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), compute_first_order_operator_raw(), compute_overall_probes_parameters(), compute_second_order_operator_raw(), convert_into_sparse_matrix(), initialise_identity_matrices(), initialise_identity_matrices_sparse(), initialise_radial_convection_operator(), initialise_radial_convection_operator_sparse(), initialise_radial_diffusion_operator(), initialise_radial_diffusion_operator_sparse(), pre_initialise_thermal_subproblems_matrices(), prepare_temporal_schemes(), printOn(), and set_param().
thermal_subproblems_matrix_assembly_
Matrice IJK_Thermal_Subresolution::thermal_subproblems_matrix_assembly_ protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), convert_into_sparse_matrix(), pre_initialise_thermal_subproblems_matrices(), and prepare_temporal_schemes().
thermal_subproblems_temperature_solution_ini_
DoubleVect IJK_Thermal_Subresolution::thermal_subproblems_temperature_solution_ini_ protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), reset_subresolution_distributed_vectors(), and solve_thermal_subproblems().
thermal_subproblems_rhs_assembly_
DoubleVect IJK_Thermal_Subresolution::thermal_subproblems_rhs_assembly_ protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), check_wrong_values_rhs(), compute_md_vector(), reset_subresolution_distributed_vectors(), and solve_thermal_subproblems().
thermal_subproblems_temperature_solution_
DoubleVect IJK_Thermal_Subresolution::thermal_subproblems_temperature_solution_ protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), compute_md_vector(), reset_subresolution_distributed_vectors(), and solve_thermal_subproblems().
thermal_subproblems_matrix_assembly_for_solver_ref_
Matrice* IJK_Thermal_Subresolution::thermal_subproblems_matrix_assembly_for_solver_ref_ = nullptr protected
Referenced by convert_into_sparse_matrix().
thermal_subproblems_matrix_assembly_for_solver_
Matrice IJK_Thermal_Subresolution::thermal_subproblems_matrix_assembly_for_solver_ protected
Referenced by compute_overall_probes_parameters(), and convert_into_sparse_matrix().
thermal_subproblems_matrix_assembly_for_solver_reduced_
Matrice IJK_Thermal_Subresolution::thermal_subproblems_matrix_assembly_for_solver_reduced_ protected
Referenced by compute_overall_probes_parameters(), and convert_into_sparse_matrix().
one_dimensional_advection_diffusion_thermal_solver_
IJK_SolveSys_FD_thermal IJK_Thermal_Subresolution::one_dimensional_advection_diffusion_thermal_solver_ protected
Referenced by compute_md_vector(), initialize(), printOn(), set_param(), and solve_thermal_subproblems().
one_dimensional_advection_diffusion_thermal_solver_implicit_
IJK_SolveSys_FD_thermal IJK_Thermal_Subresolution::one_dimensional_advection_diffusion_thermal_solver_implicit_ protected
Referenced by solve_thermal_subproblems().
md_
MD_Vector IJK_Thermal_Subresolution::md_ protected
Referenced by compute_md_vector().
fd_solvers_
Motcles IJK_Thermal_Subresolution::fd_solvers_ protected
Referenced by IJK_Thermal_Subresolution().
fd_solvers_jdd_
Motcles IJK_Thermal_Subresolution::fd_solvers_jdd_ protected
Referenced by IJK_Thermal_Subresolution().
fd_solver_rank_
int IJK_Thermal_Subresolution::fd_solver_rank_ = 0 protected
fd_solver_type_
Nom IJK_Thermal_Subresolution::fd_solver_type_ protected
Referenced by IJK_Thermal_Subresolution().
discrete_integral_
int IJK_Thermal_Subresolution::discrete_integral_ = 0 protected
Referenced by initialize(), printOn(), and set_param().
quadtree_levels_
int IJK_Thermal_Subresolution::quadtree_levels_ = 1 protected
Referenced by initialize(), printOn(), and set_param().
compute_tangential_variables_
int IJK_Thermal_Subresolution::compute_tangential_variables_ = 0 protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs().
boundary_condition_interface_
int IJK_Thermal_Subresolution::boundary_condition_interface_ = -1 protected
Referenced by compute_source_terms_impose_subresolution_boundary_conditions(), printOn(), readOn(), and set_param().
boundary_condition_interface_dict_
Motcles IJK_Thermal_Subresolution::boundary_condition_interface_dict_ protected
Referenced by IJK_Thermal_Subresolution(), and printOn().
interfacial_boundary_condition_value_
double IJK_Thermal_Subresolution::interfacial_boundary_condition_value_ = 0. protected
Referenced by compute_source_terms_impose_subresolution_boundary_conditions(), printOn(), readOn(), and set_param().
impose_boundary_condition_interface_from_simulation_
int IJK_Thermal_Subresolution::impose_boundary_condition_interface_from_simulation_ = 0 protected
Referenced by compute_source_terms_impose_subresolution_boundary_conditions(), printOn(), readOn(), and set_param().
boundary_condition_end_
int IJK_Thermal_Subresolution::boundary_condition_end_ = 0 protected
Referenced by compute_source_terms_impose_subresolution_boundary_conditions(), printOn(), readOn(), and set_param().
boundary_condition_end_dict_
Motcles IJK_Thermal_Subresolution::boundary_condition_end_dict_ protected
Referenced by IJK_Thermal_Subresolution(), and printOn().
end_boundary_condition_value_
double IJK_Thermal_Subresolution::end_boundary_condition_value_ = -1. protected
Referenced by compute_source_terms_impose_subresolution_boundary_conditions(), printOn(), readOn(), and set_param().
impose_user_boundary_condition_end_value_
int IJK_Thermal_Subresolution::impose_user_boundary_condition_end_value_ = 0 protected
Referenced by compute_source_terms_impose_subresolution_boundary_conditions(), printOn(), readOn(), and set_param().
source_terms_type_
int IJK_Thermal_Subresolution::source_terms_type_ = 2 protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), printOn(), and set_param().
source_terms_type_dict_
Motcles IJK_Thermal_Subresolution::source_terms_type_dict_ protected
Referenced by IJK_Thermal_Subresolution(), and printOn().
source_terms_correction_
int IJK_Thermal_Subresolution::source_terms_correction_ = 0 protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), and set_param().
advected_frame_of_reference_
int IJK_Thermal_Subresolution::advected_frame_of_reference_ = 0 protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), printOn(), and set_param().
neglect_frame_of_reference_radial_advection_
int IJK_Thermal_Subresolution::neglect_frame_of_reference_radial_advection_ = 0 protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), printOn(), and set_param().
approximate_temperature_increment_
int IJK_Thermal_Subresolution::approximate_temperature_increment_ = 0 protected
Referenced by initialize(), printOn(), readOn(), and set_param().
is_first_time_step_
bool IJK_Thermal_Subresolution::is_first_time_step_ = false protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), compute_thermal_subproblems(), and initialize().
first_time_step_temporal_
int IJK_Thermal_Subresolution::first_time_step_temporal_ = 0 protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), compute_local_substep(), compute_overall_probes_parameters(), compute_radial_subresolution_convection_diffusion_operators(), compute_thermal_subproblems(), initialize(), pre_initialise_thermal_subproblems_matrices(), prepare_temporal_schemes(), printOn(), reset_subresolution_distributed_vectors(), set_param(), and solve_thermal_subproblems().
first_time_step_explicit_
int IJK_Thermal_Subresolution::first_time_step_explicit_ = 0 protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), initialize(), reset_subresolution_distributed_vectors(), and solve_thermal_subproblems().
first_time_step_implicit_
int IJK_Thermal_Subresolution::first_time_step_implicit_ = 0 protected
Referenced by initialize(), printOn(), and set_param().
local_diffusion_fourier_priority_
int IJK_Thermal_Subresolution::local_diffusion_fourier_priority_ = 0 protected
Referenced by compute_local_substep(), printOn(), and set_param().
nb_iter_explicit_local_
int IJK_Thermal_Subresolution::nb_iter_explicit_local_ = 0 protected
Referenced by compute_local_substep(), and solve_thermal_subproblems().
local_fourier_
double IJK_Thermal_Subresolution::local_fourier_ = 1. protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), printOn(), and set_param().
local_cfl_
double IJK_Thermal_Subresolution::local_cfl_ = 1. protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), printOn(), and set_param().
delta_T_subcooled_overheated_
double IJK_Thermal_Subresolution::delta_T_subcooled_overheated_ =-1. protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), clip_min_temperature_values(), complete_field_thermal_wake_slice_ij_convection(), compute_Nusselt_spherical_diffusion(), IJK_One_Dimensional_Subproblems::compute_overall_bubbles_quantities(), compute_spherical_steady_dirichlet_left_right_value(), compute_temperature_init(), enforce_periodic_temperature_boundary_value(), find_time_dichotomy_derivative(), find_time_dichotomy_integral(), generate_expression_temperature_ini(), get_time_inflection_derivative(), interpolate_convective_term_on_downstream_line(), printOn(), set_field_T_ana(), set_field_temperature_per_bubble(), set_param(), and store_temperature_before_extrapolation().
convection_diffusion_time_scale_factor_
double IJK_Thermal_Subresolution::convection_diffusion_time_scale_factor_ = 1. protected
local_fourier_time_step_probe_length_
double IJK_Thermal_Subresolution::local_fourier_time_step_probe_length_ = 0. protected
Referenced by compute_local_substep().
local_cfl_time_step_probe_length_
double IJK_Thermal_Subresolution::local_cfl_time_step_probe_length_ = 0. protected
Referenced by compute_local_substep().
local_dt_cfl_
double IJK_Thermal_Subresolution::local_dt_cfl_ = 0. protected
Referenced by compute_local_substep().
local_dt_cfl_min_delta_xyz_
double IJK_Thermal_Subresolution::local_dt_cfl_min_delta_xyz_ = 0. protected
Referenced by compute_local_substep().
local_dt_cfl_counter_
double IJK_Thermal_Subresolution::local_dt_cfl_counter_ = 0. protected
Referenced by compute_local_substep().
local_dt_fourier_counter_
double IJK_Thermal_Subresolution::local_dt_fourier_counter_ = 0. protected
Referenced by compute_local_substep().
error_temperature_ana_total_
double IJK_Thermal_Subresolution::error_temperature_ana_total_ = 0. protected
Referenced by IJK_One_Dimensional_Subproblems::compute_overall_bubbles_quantities(), and set_field_T_ana().
error_temperature_ana_squared_total_
double IJK_Thermal_Subresolution::error_temperature_ana_squared_total_ = 0. protected
Referenced by IJK_One_Dimensional_Subproblems::compute_overall_bubbles_quantities(), and set_field_T_ana().
error_temperature_ana_rel_total_
double IJK_Thermal_Subresolution::error_temperature_ana_rel_total_ = 0. protected
Referenced by IJK_One_Dimensional_Subproblems::compute_overall_bubbles_quantities(), and set_field_T_ana().
first_time_step_varying_probes_
int IJK_Thermal_Subresolution::first_time_step_varying_probes_ = 0 protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), compute_thermal_subproblems(), initialise_identity_matrices(), initialise_identity_matrices_sparse(), initialise_radial_convection_operator(), initialise_radial_convection_operator_sparse(), initialise_radial_diffusion_operator(), initialise_radial_diffusion_operator_sparse(), initialize(), printOn(), reajust_probes_length(), and set_param().
probe_variations_enabled_
int IJK_Thermal_Subresolution::probe_variations_enabled_ = 0 protected
Referenced by compute_thermal_subproblems(), initialize(), reajust_probes_length(), and reajust_probes_length_collisions().
probe_variations_priority_
int IJK_Thermal_Subresolution::probe_variations_priority_ = 0 protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), printOn(), reajust_probes_length(), and set_param().
disable_interpolation_in_mixed_cells_
int IJK_Thermal_Subresolution::disable_interpolation_in_mixed_cells_ = 0 protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs().
keep_temperature_extrapolated_from_LRS_
int IJK_Thermal_Subresolution::keep_temperature_extrapolated_from_LRS_ = 0 protected
max_u_radial_
int IJK_Thermal_Subresolution::max_u_radial_ =0 protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), printOn(), and set_param().
debug_LRS_cells_
IJK_Field_double IJK_Thermal_Subresolution::debug_LRS_cells_ protected
Referenced by compute_thermal_subproblems(), get_debug_lrs_cells(), initialise_thermal_subproblems(), and initialize().
distance_cell_faces_from_lrs_
int IJK_Thermal_Subresolution::distance_cell_faces_from_lrs_ = 1 protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), and initialize().
disable_distance_cell_faces_from_lrs_
int IJK_Thermal_Subresolution::disable_distance_cell_faces_from_lrs_ = 0 protected
Referenced by initialize(), printOn(), and set_param().
pre_initialise_thermal_subproblems_list_
int IJK_Thermal_Subresolution::pre_initialise_thermal_subproblems_list_ = 0 protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), compute_radial_subresolution_convection_diffusion_operators(), convert_into_sparse_matrix(), initialise_thermal_subproblems_list(), initialize(), pre_initialise_thermal_subproblems_matrices(), printOn(), and set_param().
pre_factor_subproblems_number_
double IJK_Thermal_Subresolution::pre_factor_subproblems_number_ = 3. protected
Referenced by initialise_thermal_subproblems_list(), pre_initialise_thermal_subproblems_matrices(), printOn(), and set_param().
remove_append_subproblems_
int IJK_Thermal_Subresolution::remove_append_subproblems_ = 0 protected
Referenced by initialise_thermal_subproblems_list(), initialize(), printOn(), and set_param().
use_sparse_matrix_
int IJK_Thermal_Subresolution::use_sparse_matrix_ = 0 protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), compute_overall_probes_parameters(), compute_radial_subresolution_convection_diffusion_operators(), convert_into_sparse_matrix(), initialise_thermal_subproblems_list(), initialize(), prepare_temporal_schemes(), printOn(), and set_param().
global_probes_characteristics_
int IJK_Thermal_Subresolution::global_probes_characteristics_ = 1 protected
correct_temperature_cell_neighbours_first_iter_
int IJK_Thermal_Subresolution::correct_temperature_cell_neighbours_first_iter_ = 0 protected
Referenced by compute_temperature_cell_centres_first_correction(), initialize(), printOn(), replace_temperature_cell_centres_neighbours(), and set_param().
correct_first_iter_deactivate_cell_neighbours_
int IJK_Thermal_Subresolution::correct_first_iter_deactivate_cell_neighbours_ = 0 protected
Referenced by compute_temperature_cell_centres_first_correction().
find_temperature_cell_neighbours_
int IJK_Thermal_Subresolution::find_temperature_cell_neighbours_ = 0 protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), compute_temperature_cell_centres_first_correction(), get_cell_neighbours_corrected(), get_neighbours_temperature_colinearity_weighting(), get_temperature_cell_neighbours(), get_temperature_cell_neighbours_debug(), initialize(), printOn(), and set_param().
use_temperature_cell_neighbours_
int IJK_Thermal_Subresolution::use_temperature_cell_neighbours_ = 0 protected
Referenced by compute_temperature_cell_centres_first_correction(), initialize(), printOn(), replace_temperature_cell_centres_neighbours(), and set_param().
correct_neighbours_using_probe_length_
int IJK_Thermal_Subresolution::correct_neighbours_using_probe_length_ = 0 protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), printOn(), and set_param().
neighbours_corrected_rank_
int IJK_Thermal_Subresolution::neighbours_corrected_rank_ = 1 protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), printOn(), and set_param().
neighbours_weighting_
int IJK_Thermal_Subresolution::neighbours_weighting_ = 0 protected
Referenced by compute_temperature_cell_centres_first_correction(), and initialize().
neighbours_colinearity_weighting_
int IJK_Thermal_Subresolution::neighbours_colinearity_weighting_ = 0 protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), get_neighbours_faces_weighting_colinearity(), initialize(), printOn(), and set_param().
neighbours_distance_weighting_
int IJK_Thermal_Subresolution::neighbours_distance_weighting_ = 0 protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), initialize(), printOn(), and set_param().
neighbours_colinearity_distance_weighting_
int IJK_Thermal_Subresolution::neighbours_colinearity_distance_weighting_ = 0 protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), initialize(), printOn(), and set_param().
smooth_temperature_field_
int IJK_Thermal_Subresolution::smooth_temperature_field_ = 0 protected
Referenced by compute_temperature_cell_centres_first_correction(), initialize(), printOn(), and set_param().
readjust_probe_length_from_vertices_
int IJK_Thermal_Subresolution::readjust_probe_length_from_vertices_ = 0 protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), compute_thermal_subproblems(), initialize(), printOn(), reajust_probes_length(), reajust_probes_length_collisions(), and set_param().
temperature_cell_neighbours_
IJK_Field_double IJK_Thermal_Subresolution::temperature_cell_neighbours_ protected
Referenced by compute_temperature_cell_centres_first_correction(), get_temperature_cell_neighbours(), initialize(), and replace_temperature_cell_centres_neighbours().
temperature_cell_neighbours_debug_
IJK_Field_double IJK_Thermal_Subresolution::temperature_cell_neighbours_debug_ protected
Referenced by compute_temperature_cell_centres_first_correction(), get_temperature_cell_neighbours_debug(), and initialize().
neighbours_temperature_to_correct_
IJK_Field_int IJK_Thermal_Subresolution::neighbours_temperature_to_correct_ protected
Referenced by compute_min_max_reachable_fluxes(), compute_temperature_cell_centres_first_correction(), get_cell_neighbours_corrected(), initialize(), and replace_temperature_cell_centres_neighbours().
neighbours_temperature_colinearity_weighting_
IJK_Field_double IJK_Thermal_Subresolution::neighbours_temperature_colinearity_weighting_ protected
Referenced by compute_temperature_cell_centres_first_correction(), get_neighbours_temperature_colinearity_weighting(), initialize(), and replace_temperature_cell_centres_neighbours().
keep_max_flux_correction_
int IJK_Thermal_Subresolution::keep_max_flux_correction_ = 0 protected
Referenced by compute_temperature_cell_centres_first_correction(), initialize(), printOn(), and set_param().
clip_temperature_values_
int IJK_Thermal_Subresolution::clip_temperature_values_ = 0 protected
Referenced by clip_max_temperature_values(), clip_min_temperature_values(), printOn(), and set_param().
enforce_periodic_boundary_value_
int IJK_Thermal_Subresolution::enforce_periodic_boundary_value_ = 0 protected
Referenced by enforce_periodic_temperature_boundary_value(), lire_motcle_non_standard(), printOn(), and set_param().
stencil_periodic_boundary_value_
int IJK_Thermal_Subresolution::stencil_periodic_boundary_value_ = 2 protected
Referenced by enforce_periodic_temperature_boundary_value(), and lire_motcle_non_standard().
disable_post_processing_probes_out_files_
int IJK_Thermal_Subresolution::disable_post_processing_probes_out_files_ = 0 protected
Referenced by get_disable_post_processing_probes_out_files(), printOn(), and set_param().
cell_faces_corrected_diffusive_
IJK_Field_vector3_double IJK_Thermal_Subresolution::cell_faces_corrected_diffusive_ protected
Referenced by get_cell_faces_corrected_diffusive(), initialize(), and prepare_ij_fluxes_k_layers().
cell_faces_corrected_convective_
IJK_Field_vector3_double IJK_Thermal_Subresolution::cell_faces_corrected_convective_ protected
Referenced by get_cell_faces_corrected_convective(), initialize(), and prepare_ij_fluxes_k_layers().
cell_faces_corrected_bool_
IJK_Field_vector3_int IJK_Thermal_Subresolution::cell_faces_corrected_bool_ protected
Referenced by get_cell_faces_corrected_bool(), initialize(), and prepare_ij_fluxes_k_layers().
store_cell_faces_corrected_
int IJK_Thermal_Subresolution::store_cell_faces_corrected_ = 0 protected
Referenced by get_cell_faces_corrected_bool(), get_cell_faces_corrected_convective(), get_cell_faces_corrected_diffusive(), initialize(), prepare_ij_fluxes_k_layers(), printOn(), and set_param().
cell_faces_neighbours_corrected_diag_bool_
IJK_Field_vector3_int IJK_Thermal_Subresolution::cell_faces_neighbours_corrected_diag_bool_ protected
Referenced by get_cell_faces_neighbours_corrected_diag_bool(), and initialize().
find_cell_neighbours_for_fluxes_spherical_correction_
int IJK_Thermal_Subresolution::find_cell_neighbours_for_fluxes_spherical_correction_ = 0 protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), get_cell_faces_neighbours_corrected_diag_bool(), initialize(), printOn(), and set_param().
use_cell_neighbours_for_fluxes_spherical_correction_
int IJK_Thermal_Subresolution::use_cell_neighbours_for_fluxes_spherical_correction_ = 0 protected
Referenced by initialize(), printOn(), and set_param().
find_reachable_fluxes_
int IJK_Thermal_Subresolution::find_reachable_fluxes_ = 0 protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), get_cell_faces_neighbours_corrected_all_bool(), get_cell_faces_neighbours_corrected_min_max_bool(), get_cell_neighbours_corrected_trimmed(), initialize(), printOn(), and set_param().
use_reachable_fluxes_
int IJK_Thermal_Subresolution::use_reachable_fluxes_ = 0 protected
Referenced by compare_fluxes_thermal_subproblems(), complete_convective_flux_frame_of_reference(), complete_thermal_fluxes_face_centre(), compute_convective_fluxes_face_centre(), compute_diffusive_fluxes_face_centre(), compute_temperature_cell_centres_second_correction(), get_cell_faces_neighbours_corrected_convective(), get_cell_faces_neighbours_corrected_convective_frame_of_ref(), get_cell_faces_neighbours_corrected_diffusive(), get_cell_faces_neighbours_corrected_velocity_temperature(), get_neighbours_faces_weighting_colinearity(), initialize(), prepare_ij_fluxes_k_layers(), printOn(), and set_param().
keep_first_reachable_fluxes_
int IJK_Thermal_Subresolution::keep_first_reachable_fluxes_ = 0 protected
Referenced by compare_fluxes_thermal_subproblems(), complete_convective_flux_frame_of_reference(), compute_temperature_cell_centres_second_correction(), initialize(), printOn(), replace_temperature_cell_centres_neighbours(), and set_param().
cell_faces_neighbours_corrected_all_bool_
IJK_Field_vector3_int IJK_Thermal_Subresolution::cell_faces_neighbours_corrected_all_bool_ protected
Referenced by compute_min_max_reachable_fluxes(), get_cell_faces_neighbours_corrected_all_bool(), and initialize().
cell_faces_neighbours_corrected_velocity_temperature_
IJK_Field_vector3_double IJK_Thermal_Subresolution::cell_faces_neighbours_corrected_velocity_temperature_ protected
Referenced by complete_convective_flux_frame_of_reference(), compute_min_max_reachable_fluxes(), get_cell_faces_neighbours_corrected_velocity_temperature(), and initialize().
cell_faces_neighbours_corrected_convective_frame_of_reference_
IJK_Field_vector3_double IJK_Thermal_Subresolution::cell_faces_neighbours_corrected_convective_frame_of_reference_ protected
Referenced by compare_fluxes_thermal_subproblems(), complete_convective_flux_frame_of_reference(), get_cell_faces_neighbours_corrected_convective_frame_of_ref(), and initialize().
cell_faces_neighbours_corrected_convective_
IJK_Field_vector3_double IJK_Thermal_Subresolution::cell_faces_neighbours_corrected_convective_ protected
Referenced by complete_convective_flux_frame_of_reference(), compute_min_max_reachable_fluxes(), get_cell_faces_neighbours_corrected_convective(), and initialize().
cell_faces_neighbours_corrected_diffusive_
IJK_Field_vector3_double IJK_Thermal_Subresolution::cell_faces_neighbours_corrected_diffusive_ protected
Referenced by compare_fluxes_thermal_subproblems(), compute_min_max_reachable_fluxes(), get_cell_faces_neighbours_corrected_diffusive(), and initialize().
neighbours_faces_weighting_colinearity_
IJK_Field_vector3_double IJK_Thermal_Subresolution::neighbours_faces_weighting_colinearity_ protected
Referenced by compute_min_max_reachable_fluxes(), get_neighbours_faces_weighting_colinearity(), and initialize().
cell_faces_neighbours_corrected_min_max_bool_
IJK_Field_vector3_int IJK_Thermal_Subresolution::cell_faces_neighbours_corrected_min_max_bool_ protected
Referenced by compute_min_max_reachable_fluxes(), get_cell_faces_neighbours_corrected_min_max_bool(), and initialize().
neighbours_temperature_to_correct_trimmed_
IJK_Field_int IJK_Thermal_Subresolution::neighbours_temperature_to_correct_trimmed_ protected
Referenced by compute_min_max_reachable_fluxes(), get_cell_neighbours_corrected_trimmed(), initialize(), and replace_temperature_cell_centres_neighbours().
neighbours_last_faces_weighting_
int IJK_Thermal_Subresolution::neighbours_last_faces_weighting_ = 0 protected
Referenced by initialize().
neighbours_last_faces_colinearity_weighting_
int IJK_Thermal_Subresolution::neighbours_last_faces_colinearity_weighting_ = 0 protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), initialize(), printOn(), and set_param().
neighbours_last_faces_colinearity_face_weighting_
int IJK_Thermal_Subresolution::neighbours_last_faces_colinearity_face_weighting_ = 0 protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), initialize(), printOn(), and set_param().
neighbours_last_faces_distance_weighting_
int IJK_Thermal_Subresolution::neighbours_last_faces_distance_weighting_ = 0 protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), initialize(), printOn(), and set_param().
neighbours_last_faces_distance_colinearity_weighting_
int IJK_Thermal_Subresolution::neighbours_last_faces_distance_colinearity_weighting_ = 0 protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), initialize(), and set_param().
neighbours_last_faces_distance_colinearity_face_weighting_
int IJK_Thermal_Subresolution::neighbours_last_faces_distance_colinearity_face_weighting_ = 0 protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), initialize(), printOn(), and set_param().
post_process_all_probes_
int IJK_Thermal_Subresolution::post_process_all_probes_ = 0 protected
Referenced by printOn(), set_param(), and set_thermal_subresolution_outputs().
nb_theta_post_pro_
int IJK_Thermal_Subresolution::nb_theta_post_pro_ = 10 protected
Referenced by printOn(), set_param(), and set_thermal_subresolution_outputs().
nb_phi_post_pro_
int IJK_Thermal_Subresolution::nb_phi_post_pro_ = 4 protected
Referenced by printOn(), set_param(), and set_thermal_subresolution_outputs().
nb_probes_post_pro_
int IJK_Thermal_Subresolution::nb_probes_post_pro_ = 40 protected
Referenced by printOn(), and set_param().
interp_eulerian_
int IJK_Thermal_Subresolution::interp_eulerian_ = 0 protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), printOn(), and set_param().
first_step_thermals_post_
int IJK_Thermal_Subresolution::first_step_thermals_post_ = 1 protected
Referenced by compute_thermal_subproblems(), get_first_step_thermals_post(), initialize(), and printOn().
disable_first_step_thermals_post_
int IJK_Thermal_Subresolution::disable_first_step_thermals_post_ = 0 protected
Referenced by initialize(), and set_param().
copy_fluxes_on_every_procs_
int IJK_Thermal_Subresolution::copy_fluxes_on_every_procs_ = 1 protected
Referenced by initialize().
copy_temperature_on_every_procs_
int IJK_Thermal_Subresolution::copy_temperature_on_every_procs_ = 1 protected
Referenced by initialize().
post_process_thermal_slices_
int IJK_Thermal_Subresolution::post_process_thermal_slices_ = 0 protected
Referenced by post_process_thermal_wake_slices(), printOn(), and set_param().
thermal_slices_regions_
int IJK_Thermal_Subresolution::thermal_slices_regions_ = 0 protected
Referenced by post_process_thermal_wake_slices(), printOn(), and set_param().
nb_diam_slice_
double IJK_Thermal_Subresolution::nb_diam_slice_ = -1 protected
Referenced by post_process_thermal_wake_slices(), printOn(), and set_param().
nb_slices_
int IJK_Thermal_Subresolution::nb_slices_ = 1 protected
Referenced by post_process_thermal_wake_slices(), printOn(), and set_param().
upstream_dir_slice_
int IJK_Thermal_Subresolution::upstream_dir_slice_ = -1 protected
Referenced by post_process_thermal_wake_slice(), printOn(), and set_param().
disable_slice_to_nearest_plane_
int IJK_Thermal_Subresolution::disable_slice_to_nearest_plane_ = 0 protected
Referenced by complete_field_thermal_wake_slice_ij_convection(), complete_field_thermal_wake_slice_ij_diffusion(), complete_field_thermal_wake_slice_ij_indices_coords(), complete_field_thermal_wake_slice_ij_temperature(), complete_field_thermal_wake_slice_ij_temperature_incr(), complete_field_thermal_wake_slice_ij_velocity(), printOn(), and set_param().
post_process_thermal_lines_
int IJK_Thermal_Subresolution::post_process_thermal_lines_ = 0 protected
Referenced by post_process_thermal_downstream_lines(), printOn(), and set_param().
upstream_dir_line_
int IJK_Thermal_Subresolution::upstream_dir_line_ = -1 protected
Referenced by post_process_thermal_downstream_lines(), printOn(), and set_param().
nb_thermal_lines_
int IJK_Thermal_Subresolution::nb_thermal_lines_ = 1 protected
Referenced by post_process_thermal_downstream_lines(), printOn(), and set_param().
nb_thermal_concentric_circles_
int IJK_Thermal_Subresolution::nb_thermal_concentric_circles_ = 1 protected
Referenced by post_process_thermal_downstream_lines(), printOn(), and set_param().
nb_thermal_line_points_
int IJK_Thermal_Subresolution::nb_thermal_line_points_ = 100 protected
Referenced by initialise_thermal_dowstreamlines_tabs(), initialise_thermal_line_points(), post_process_thermal_downstream_lines(), printOn(), and set_param().
nb_diam_thermal_line_length_
double IJK_Thermal_Subresolution::nb_diam_thermal_line_length_ = -1 protected
Referenced by initialise_thermal_line_points(), and set_param().
use_corrected_velocity_convection_
int IJK_Thermal_Subresolution::use_corrected_velocity_convection_ = 0 protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), printOn(), and set_param().
use_velocity_cartesian_grid_
int IJK_Thermal_Subresolution::use_velocity_cartesian_grid_ = 0 protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), printOn(), and set_param().
compute_radial_displacement_
int IJK_Thermal_Subresolution::compute_radial_displacement_ = 0 protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), printOn(), and set_param().
use_normal_gradient_for_flux_corr_
int IJK_Thermal_Subresolution::use_normal_gradient_for_flux_corr_ = 0 protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), printOn(), and set_param().
interfacial_heat_flux_dispatched_
IJK_Field_vector3_double IJK_Thermal_Subresolution::interfacial_heat_flux_dispatched_ protected
Referenced by get_interfacial_heat_flux_dispatched(), and initialize().
ijk_indices_flux_out_
FixedVector<ArrOfInt, 3> IJK_Thermal_Subresolution::ijk_indices_flux_out_ protected
thermal_flux_out_
FixedVector<ArrOfDouble, 3> IJK_Thermal_Subresolution::thermal_flux_out_ protected
zero_liquid_neighbours_
IJK_Field_int IJK_Thermal_Subresolution::zero_liquid_neighbours_ protected
Referenced by IJK_One_Dimensional_Subproblem::associate_sub_problem_to_inputs(), initialise_thermal_subproblems(), and initialize().
interfacial_heat_flux_contrib_
IJK_Field_vector3_double IJK_Thermal_Subresolution::interfacial_heat_flux_contrib_ protected
Referenced by compute_convective_diffusive_fluxes_face_centre(), get_interfacial_heat_flux_contrib(), and initialize().
interfacial_heat_flux_current_
IJK_Field_vector3_double IJK_Thermal_Subresolution::interfacial_heat_flux_current_ protected
Referenced by compute_convective_diffusive_fluxes_face_centre(), get_interfacial_heat_flux_current(), and initialize().
ijk_indices_flux_contrib_
FixedVector<ArrOfInt, 4> IJK_Thermal_Subresolution::ijk_indices_flux_contrib_ protected
Referenced by compute_convective_diffusive_fluxes_face_centre().
thermal_flux_out_contrib_
ArrOfDouble IJK_Thermal_Subresolution::thermal_flux_out_contrib_ protected
Referenced by compute_convective_diffusive_fluxes_face_centre().