TrioCFD: TRUSTProblem_List_Concentration_Gen< _DERIVED_TYPE_, _EQUATION_TYPE_, _MEDIUM_TYPE_ > Class Template Reference
TRUSTProblem_List_Concentration_Gen< _DERIVED_TYPE_, _EQUATION_TYPE_, _MEDIUM_TYPE_ > Class Template Reference
#include <TRUSTProblem_List_Concentration_Gen.h>
Member Function Documentation
taille_memoire()
template<typename _DERIVED_TYPE_ , typename _EQUATION_TYPE_ = Convection_Diffusion_Concentration, typename _MEDIUM_TYPE_ = Constituant> unsigned TRUSTProblem_List_Concentration_Gen< _DERIVED_TYPE_, _EQUATION_TYPE_, _MEDIUM_TYPE_ >::taille_memoire () const inline override protected
duplique()
template<typename _DERIVED_TYPE_ , typename _EQUATION_TYPE_ = Convection_Diffusion_Concentration, typename _MEDIUM_TYPE_ = Constituant> int TRUSTProblem_List_Concentration_Gen< _DERIVED_TYPE_, _EQUATION_TYPE_, _MEDIUM_TYPE_ >::duplique () const inline override protected
References Process::exit().
readOn()
template<typename _DERIVED_TYPE_ , typename _EQUATION_TYPE_ = Convection_Diffusion_Concentration, typename _MEDIUM_TYPE_ = Constituant> Entree & TRUSTProblem_List_Concentration_Gen< _DERIVED_TYPE_, _EQUATION_TYPE_, _MEDIUM_TYPE_ >::readOn (Entree & is) inline override protected
Referenced by Pb_Thermohydraulique_List_Concentration::readOn(), and Pb_Hydraulique_List_Concentration::readOn().
add_concentration_equations()
template<typename _DERIVED_TYPE_ , typename _EQUATION_TYPE_ = Convection_Diffusion_Concentration, typename _MEDIUM_TYPE_ = Constituant> void TRUSTProblem_List_Concentration_Gen< _DERIVED_TYPE_, _EQUATION_TYPE_, _MEDIUM_TYPE_ >::add_concentration_equations () protected
lire_equations()
template<typename _DERIVED_TYPE_ , typename _EQUATION_TYPE_ = Convection_Diffusion_Concentration, typename _MEDIUM_TYPE_ = Constituant> Entree & TRUSTProblem_List_Concentration_Gen< _DERIVED_TYPE_, _EQUATION_TYPE_, _MEDIUM_TYPE_ >::lire_equations (Entree & is, Motcle & dernier_mot) override protected
associer_milieu_base()
template<typename _DERIVED_TYPE_ , typename _EQUATION_TYPE_ = Convection_Diffusion_Concentration, typename _MEDIUM_TYPE_ = Constituant> void TRUSTProblem_List_Concentration_Gen< _DERIVED_TYPE_, _EQUATION_TYPE_, _MEDIUM_TYPE_ >::associer_milieu_base (const Milieu_base &) override
verifier()
template<typename _DERIVED_TYPE_ , typename _EQUATION_TYPE_ = Convection_Diffusion_Concentration, typename _MEDIUM_TYPE_ = Constituant> int TRUSTProblem_List_Concentration_Gen< _DERIVED_TYPE_, _EQUATION_TYPE_, _MEDIUM_TYPE_ >::verifier () override
typer_lire_milieu()
template<typename _DERIVED_TYPE_ , typename _EQUATION_TYPE_ = Convection_Diffusion_Concentration, typename _MEDIUM_TYPE_ = Constituant> void TRUSTProblem_List_Concentration_Gen< _DERIVED_TYPE_, _EQUATION_TYPE_, _MEDIUM_TYPE_ >::typer_lire_milieu (Entree &) override