TrioCFD: Switch_double Class Reference
Switch_double Class Reference abstract
#include <IJK_switch.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Interprete
static Objet_U & objet (const Nom &)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Switch_double()
Switch_double::Switch_double ()
~Switch_double()
Switch_double::~Switch_double () override
Member Function Documentation
info()
const Type_info * Switch_double::info () static
get_info()
const Type_info * Switch_double::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Interprete.
Reimplemented in Switch_FT_double.
self_cast() [1/2]
Switch_double & Switch_double::self_cast (Objet_U & r) static
self_cast() [2/2]
const Switch_double & Switch_double::self_cast (const Objet_U & r) static
printOn()
Sortie & Switch_double::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Interprete.
Reimplemented in Switch_FT_double.
readOn()
Entree & Switch_double::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Interprete.
Reimplemented in Switch_FT_double.
interpreter()
Entree & Switch_double::interpreter (Entree & is) override virtual
Implements Interprete.
References Param::lire_avec_accolades(), prepare_run(), Objet_U::que_suis_je(), run(), and set_param().
run()
void Switch_double::run ()
References allocate_fields(), calculer_coeff(), calculer_coords_elem(), calculer_coords_Vi(), Sortie_Fichier_base::close(), compute_and_write_extra_fields(), compute_and_write_extra_fields_direct(), direct_write_, IJK_Field_vector< T, N >::echange_espace_virtuel(), ecrire_fichier_reprise(), ecrire_header_lata(), Domaine_IJK::get_local_mesh_delta(), initialise(), new_mesh_, new_ni_, new_nj_, new_nk_, new_velocity_, new_x_, new_y_, new_z_, nom_sauvegarde_, old_mesh_, old_velocity_, old_x_, old_y_, old_z_, Sortie_Fichier_base::ouvrir(), perio_k_, prepare_thermals(), Sortie::set_bin(), switch_vit(), switch_vit_direct(), and write_velocity().
Referenced by interpreter().
initialise()
void Switch_double::initialise () protected virtual
Reimplemented in Switch_FT_double.
References Domaine_IJK::ELEM, fichier_old_vitesse_, Domaine_IJK::get_nb_items_local(), Domaine_base::le_nom(), new_mesh_, new_ni_, new_nj_, new_nk_, old_mesh_, old_ni_, old_nj_, old_nk_, old_velocity_, and timestep_reprise_vitesse_.
Referenced by Switch_FT_double::initialise(), and run().
allocate_fields()
void Switch_double::allocate_fields (double & sz_arr) protected virtual
References direct_write_, init_thermals(), new_mesh_, new_velocity_, old_mesh_, and old_velocity_.
Referenced by run().
prepare_run()
void Switch_double::prepare_run () protected virtual
Reimplemented in Switch_FT_double.
References Domaine_IJK::get_periodic_flag(), lire_fichier_reprise(), new_mesh_, new_mesh_name_, nom_reprise_, Interprete_bloc::objet_global(), old_mesh_, old_mesh_name_, and perio_k_.
Referenced by interpreter(), and Switch_FT_double::prepare_run().
set_param()
void Switch_double::set_param (Param & param) protected virtual
Reimplemented in Switch_FT_double.
References Param::ajouter(), direct_write_, new_mesh_name_, nom_reprise_, nom_sauvegarde_, old_mesh_name_, perio_k_, and Param::REQUIRED.
Referenced by interpreter(), and Switch_FT_double::set_param().
ecrire_fichier_reprise()
virtual void Switch_double::ecrire_fichier_reprise (const char * fichier_sauvegarde, const bool and_lata = true) protected pure virtual
Implemented in Switch_FT_double.
Referenced by run().
set_param_reprise()
void Switch_double::set_param_reprise (Param & param) protected virtual
Reimplemented in Switch_FT_double.
References Param::ajouter(), current_time_, fichier_old_vitesse_, terme_source_acceleration_, and timestep_reprise_vitesse_.
Referenced by lire_fichier_reprise(), and Switch_FT_double::set_param_reprise().
lire_fichier_reprise()
void Switch_double::lire_fichier_reprise (const char * fichier_reprise) protected virtual
References Param::lire_avec_accolades(), Objet_U::que_suis_je(), and set_param_reprise().
Referenced by prepare_run().
ecrire_header_lata()
void Switch_double::ecrire_header_lata (const Nom lata_name) protected virtual
Reimplemented in Switch_FT_double.
References current_time_, and new_velocity_.
Referenced by Switch_FT_double::ecrire_header_lata(), and run().
compute_and_write_extra_fields()
virtual void Switch_double::compute_and_write_extra_fields (const Nom & lata_name, DoubleTab & coeff_i, IntTab Indice_i, DoubleTab & coeff_j, IntTab Indice_j, DoubleTab & coeff_k, IntTab Indice_k) protected pure virtual
Implemented in Switch_FT_double.
Referenced by run().
compute_and_write_extra_fields_direct()
virtual void Switch_double::compute_and_write_extra_fields_direct (SFichier & file, DoubleTab & coeff_i, IntTab Indice_i, DoubleTab & coeff_j, IntTab Indice_j, DoubleTab & coeff_k, IntTab Indice_k) protected pure virtual
Implemented in Switch_FT_double.
Referenced by run().
init_thermals()
virtual void Switch_double::init_thermals () inline protected virtual
Reimplemented in Switch_FT_double.
Referenced by allocate_fields().
prepare_thermals()
virtual void Switch_double::prepare_thermals (const Nom lata_name) inline protected virtual
Reimplemented in Switch_FT_double.
Referenced by run().
write_velocity()
void Switch_double::write_velocity (const Nom lata_name) const protected
References direct_write_, Domaine_IJK::get_nb_elem_tot(), Process::je_suis_maitre(), Domaine_base::le_nom(), new_mesh_, new_velocity_, and Sortie_Fichier_base::ouvrir().
Referenced by Switch_FT_double::ecrire_fichier_reprise(), and run().
calculer_coords()
void Switch_double::calculer_coords (const Domaine_IJK::Localisation loc) protected
References Domaine_IJK::get_constant_delta(), Domaine_IJK::get_coords_of_dof(), Domaine_IJK::get_delta(), Domaine_IJK::get_nb_elem_tot(), Domaine_IJK::get_offset_local(), new_mesh_, new_ni_, new_nj_, new_nk_, new_x_, new_y_, new_z_, old_mesh_, old_ni_, old_nj_, old_nk_, old_x_, old_y_, old_z_, and perio_k_.
Referenced by calculer_coords_elem(), and calculer_coords_Vi().
calculer_coords_elem()
void Switch_double::calculer_coords_elem () protected
References calculer_coords(), and Domaine_IJK::ELEM.
Referenced by IJK_Thermals::compute_new_thermal_field(), and run().
calculer_coords_Vi()
void Switch_double::calculer_coords_Vi (const int dir) protected
References calculer_coords(), Process::exit(), Domaine_IJK::FACES_I, Domaine_IJK::FACES_J, and Domaine_IJK::FACES_K.
Referenced by run(), and switch_vit_direct().
remplir_gost()
void Switch_double::remplir_gost () protected
calculer_coeff()
void Switch_double::calculer_coeff (DoubleTab & coeff_i, IntTab & Indice_i, DoubleTab & coeff_j, IntTab & Indice_j, DoubleTab & coeff_k, IntTab & Indice_k) protected
References Domaine_IJK::get_nb_elem_tot(), Domaine_IJK::get_offset_local(), IJKArray_with_ghost< _TYPE_, _TYPE_ARRAY_ >::ghost(), new_ni_, new_nj_, new_nk_, new_x_, new_y_, new_z_, old_mesh_, old_ni_, old_nj_, old_nk_, old_x_, old_y_, old_z_, perio_k_, and TRUSTTab< _TYPE_, _SIZE_ >::resize().
Referenced by IJK_Thermals::compute_new_thermal_field(), run(), and switch_vit_direct().
switch_vit()
void Switch_double::switch_vit (DoubleTab coeff_i, IntTab Indice_i, DoubleTab coeff_j, IntTab Indice_j, DoubleTab coeff_k, IntTab Indice_k, const int dir) protected
References new_ni_, new_nj_, new_nk_, new_velocity_, and old_velocity_.
Referenced by run().
switch_scalar_field()
void Switch_double::switch_scalar_field (const IJK_Field_double & oldf, IJK_Field_double & newf, DoubleTab coeff_i, IntTab Indice_i, DoubleTab coeff_j, IntTab Indice_j, DoubleTab coeff_k, IntTab Indice_k) const protected
References IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), and IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk().
Referenced by IJK_Thermals::compute_new_thermal_field().
switch_scalar_field_direct()
void Switch_double::switch_scalar_field_direct (SFichier & binary_file, const IJK_Field_double & fld, DoubleTab coeff_i, IntTab Indice_i, DoubleTab coeff_j, IntTab Indice_j, DoubleTab coeff_k, IntTab Indice_k) protected
References TRUSTArray< _TYPE_, _SIZE_ >::addr(), new_ni_, new_nj_, new_nk_, Sortie::put(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
switch_vit_direct()
void Switch_double::switch_vit_direct (SFichier & binary_file) protected
References TRUSTArray< _TYPE_, _SIZE_ >::addr(), calculer_coeff(), calculer_coords_Vi(), new_ni_, new_nj_, new_nk_, old_velocity_, Sortie::put(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by run().
Member Data Documentation
info_obj
const Type_info Switch_double::info_obj static
old_mesh_name_
Nom Switch_double::old_mesh_name_ protected
Referenced by prepare_run(), and set_param().
new_mesh_name_
Nom Switch_double::new_mesh_name_ protected
Referenced by prepare_run(), and set_param().
new_mesh_
Domaine_IJK Switch_double::new_mesh_ protected
Referenced by allocate_fields(), calculer_coords(), Switch_FT_double::compute_and_write_extra_fields(), initialise(), Switch_FT_double::initialise(), prepare_run(), run(), and write_velocity().
old_mesh_
Domaine_IJK Switch_double::old_mesh_ protected
Referenced by allocate_fields(), calculer_coeff(), calculer_coords(), Switch_FT_double::init_thermals(), initialise(), Switch_FT_double::initialise(), prepare_run(), and run().
direct_write_
int Switch_double::direct_write_ = 1 protected
Referenced by allocate_fields(), run(), set_param(), and write_velocity().
perio_k_
int Switch_double::perio_k_ = 1 protected
Referenced by calculer_coeff(), calculer_coords(), prepare_run(), run(), and set_param().
new_velocity_
IJK_Field_vector3_double Switch_double::new_velocity_ protected
Referenced by allocate_fields(), ecrire_header_lata(), run(), switch_vit(), and write_velocity().
old_velocity_
IJK_Field_vector3_double Switch_double::old_velocity_ protected
Referenced by allocate_fields(), initialise(), run(), switch_vit(), and switch_vit_direct().
new_rho_
IJK_Field_double Switch_double::new_rho_ protected
old_rho_
IJK_Field_double Switch_double::old_rho_ protected
old_x_
ArrOfDouble_with_ghost Switch_double::old_x_ protected
Referenced by calculer_coeff(), calculer_coords(), and run().
new_x_
ArrOfDouble_with_ghost Switch_double::new_x_ protected
Referenced by calculer_coeff(), calculer_coords(), and run().
old_y_
ArrOfDouble_with_ghost Switch_double::old_y_ protected
Referenced by calculer_coeff(), calculer_coords(), and run().
new_y_
ArrOfDouble_with_ghost Switch_double::new_y_ protected
Referenced by calculer_coeff(), calculer_coords(), and run().
old_z_
ArrOfDouble_with_ghost Switch_double::old_z_ protected
Referenced by calculer_coeff(), calculer_coords(), and run().
new_z_
ArrOfDouble_with_ghost Switch_double::new_z_ protected
Referenced by calculer_coeff(), calculer_coords(), and run().
old_ni_
int Switch_double::old_ni_ = 0 protected
Referenced by calculer_coeff(), calculer_coords(), initialise(), and Switch_FT_double::initialise().
old_nj_
int Switch_double::old_nj_ = 0 protected
Referenced by calculer_coeff(), calculer_coords(), initialise(), and Switch_FT_double::initialise().
old_nk_
int Switch_double::old_nk_ = 0 protected
Referenced by calculer_coeff(), calculer_coords(), initialise(), and Switch_FT_double::initialise().
new_ni_
int Switch_double::new_ni_ = 0 protected
Referenced by calculer_coeff(), calculer_coords(), initialise(), Switch_FT_double::initialise(), run(), switch_scalar_field_direct(), switch_vit(), and switch_vit_direct().
new_nj_
int Switch_double::new_nj_ = 0 protected
Referenced by calculer_coeff(), calculer_coords(), initialise(), Switch_FT_double::initialise(), run(), switch_scalar_field_direct(), switch_vit(), and switch_vit_direct().
new_nk_
int Switch_double::new_nk_ = 0 protected
Referenced by calculer_coeff(), calculer_coords(), initialise(), Switch_FT_double::initialise(), run(), switch_scalar_field_direct(), switch_vit(), and switch_vit_direct().
current_time_
double Switch_double::current_time_ = 0. protected
Referenced by Switch_FT_double::ecrire_fichier_reprise(), ecrire_header_lata(), and set_param_reprise().
terme_source_acceleration_
double Switch_double::terme_source_acceleration_ = 0. protected
Referenced by Switch_FT_double::ecrire_fichier_reprise(), and set_param_reprise().
nom_sauvegarde_
Nom Switch_double::nom_sauvegarde_ protected
Referenced by Switch_FT_double::initialise(), run(), and set_param().
nom_reprise_
Nom Switch_double::nom_reprise_ protected
Referenced by prepare_run(), Switch_FT_double::prepare_run(), and set_param().
fichier_old_vitesse_
Nom Switch_double::fichier_old_vitesse_ protected
Referenced by initialise(), Switch_FT_double::prepare_run(), and set_param_reprise().
fichier_new_vitesse_
Nom Switch_double::fichier_new_vitesse_ protected
timestep_reprise_vitesse_
int Switch_double::timestep_reprise_vitesse_ = 0 protected
Referenced by initialise(), and set_param_reprise().