TrioCFD: Eq_couch_lim Class Reference
Eq_couch_lim Class Reference
#include <Eq_couch_lim.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Eq_couch_lim()
Eq_couch_lim::Eq_couch_lim ()
~Eq_couch_lim()
Eq_couch_lim::~Eq_couch_lim () override
Member Function Documentation
cree_instance()
Objet_U * Eq_couch_lim::cree_instance () static
taille_memoire()
unsigned Eq_couch_lim::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Eq_couch_lim::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Eq_couch_lim::info () static
get_info()
const Type_info * Eq_couch_lim::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
Eq_couch_lim & Eq_couch_lim::self_cast (Objet_U & r) static
self_cast() [2/2]
const Eq_couch_lim & Eq_couch_lim::self_cast (const Objet_U & r) static
printOn()
Sortie & Eq_couch_lim::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
readOn()
Entree & Eq_couch_lim::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
initialiser()
void Eq_couch_lim::initialiser (int n1, int n2, double n8, double epsilon, int max_ite, int dyn_nu_t)
References mailler_fin(), and TRUSTArray< _TYPE_, _SIZE_ >::resize_array().
Referenced by ParoiVEF_TBLE::init_lois_paroi(), and ParoiVEF_TBLE_scal::init_lois_paroi().
aller_au_temps()
void Eq_couch_lim::aller_au_temps (double t_final)
References Diffu_totale_base::calculer_a_local(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by aller_jusqu_a_convergence(), ParoiVEF_TBLE::calculer_hyd(), ParoiVEF_TBLE::calculer_hyd_BiK(), and ParoiVEF_TBLE_scal::calculer_scal().
aller_jusqu_a_convergence()
void Eq_couch_lim::aller_jusqu_a_convergence (int itmax, double erreur)
References aller_au_temps().
Referenced by ParoiVEF_TBLE::calculer_hyd(), ParoiVEF_TBLE::calculer_hyd_BiK(), and ParoiVEF_TBLE_scal::calculer_scal().
mailler_fin()
void Eq_couch_lim::mailler_fin ()
References Process::je_suis_maitre().
Referenced by initialiser().
set_F() [1/2]
void Eq_couch_lim::set_F (int j, double f) inline
Referenced by ParoiVEF_TBLE::calculer_hyd(), ParoiVEF_TBLE::calculer_hyd_BiK(), and ParoiVEF_TBLE_scal::calculer_scal().
set_F() [2/2]
void Eq_couch_lim::set_F (int j, int i, double f) inline
get_F0()
double Eq_couch_lim::get_F0 (int j) const inline
get_F()
double Eq_couch_lim::get_F (int j, int i) const inline
set_y0()
void Eq_couch_lim::set_y0 (double y) inline
Referenced by ParoiVEF_TBLE::init_lois_paroi(), and ParoiVEF_TBLE_scal::init_lois_paroi().
set_yn()
void Eq_couch_lim::set_yn (double y) inline
Referenced by ParoiVEF_TBLE::init_lois_paroi(), and ParoiVEF_TBLE_scal::init_lois_paroi().
set_u_y0()
void Eq_couch_lim::set_u_y0 (int j, double u) inline
Referenced by ParoiVEF_TBLE::calculer_hyd(), ParoiVEF_TBLE::calculer_hyd_BiK(), ParoiVEF_TBLE_scal::calculer_scal(), ParoiVEF_TBLE::init_lois_paroi(), and ParoiVEF_TBLE_scal::init_lois_paroi().
set_u_yn()
void Eq_couch_lim::set_u_yn (int j, double u) inline
Referenced by ParoiVEF_TBLE::calculer_hyd(), ParoiVEF_TBLE::calculer_hyd_BiK(), ParoiVEF_TBLE_scal::calculer_scal(), ParoiVEF_TBLE::init_lois_paroi(), and ParoiVEF_TBLE_scal::init_lois_paroi().
set_nu_t_yn()
void Eq_couch_lim::set_nu_t_yn (double nu_t) inline
Referenced by ParoiVEF_TBLE::calculer_hyd().
set_Uinit_lin()
void Eq_couch_lim::set_Uinit_lin (int comp, double f1, double f2) inline
Referenced by ParoiVEF_TBLE::init_lois_paroi(), and ParoiVEF_TBLE_scal::init_lois_paroi().
set_Uinit()
void Eq_couch_lim::set_Uinit (int comp, int i, double val) inline
Referenced by ParoiVEF_TBLE::init_lois_paroi(), and ParoiVEF_TBLE_scal::init_lois_paroi().
set_diffu()
void Eq_couch_lim::set_diffu (Motcle modele) inline
References Diffu_totale_base::associer_eqn(), and Objet_U_ptr::typer().
set_dt()
void Eq_couch_lim::set_dt (double delta_t) inline
Referenced by ParoiVEF_TBLE::calculer_hyd(), ParoiVEF_TBLE::calculer_hyd_BiK(), and ParoiVEF_TBLE_scal::calculer_scal().
set_Un_old()
void Eq_couch_lim::set_Un_old (int j, int i, double u) inline
set_Unp1()
void Eq_couch_lim::set_Unp1 (int j, int i, double u) inline
set_v()
void Eq_couch_lim::set_v (int i, double u) inline
get_it()
int Eq_couch_lim::get_it () inline
Referenced by ParoiVEF_TBLE::calculer_hyd(), ParoiVEF_TBLE::calculer_hyd_BiK(), and ParoiVEF_TBLE_scal::calculer_scal().
get_N()
int Eq_couch_lim::get_N () inline
Referenced by Diffu_k::calculer_a_local(), and Diffu_lm::calculer_a_local().
get_N_comp()
int Eq_couch_lim::get_N_comp () inline
Referenced by Diffu_lm::calculer_a_local().
get_y0()
double Eq_couch_lim::get_y0 () inline
get_yn()
double Eq_couch_lim::get_yn () inline
get_nu_t_yn()
double Eq_couch_lim::get_nu_t_yn () inline
Referenced by Diffu_lm::calculer_a_local(), and ParoiVEF_TBLE::calculer_hyd().
get_nu_t_dyn()
double Eq_couch_lim::get_nu_t_dyn () inline
Referenced by Diffu_lm::calculer_a_local().
get_visco_tot()
double Eq_couch_lim::get_visco_tot (int i) const inline
get_nut()
double Eq_couch_lim::get_nut (int i) inline
References Diffu_totale_base::calculer_a_local(), and TRUST_Deriv< _CLASSE_ >::valeur().
get_D()
double Eq_couch_lim::get_D (int i) inline
References Diffu_totale_base::calculer_D_local(), and TRUST_Deriv< _CLASSE_ >::valeur().
get_Unp1() [1/2]
double Eq_couch_lim::get_Unp1 (int j, int i) inline
Referenced by Diffu_k::calculer_a_local(), Diffu_lm::calculer_a_local(), ParoiVDF_TBLE_LRM::calculer_hyd(), ParoiVDF_TBLE::calculer_hyd(), ParoiVEF_TBLE::calculer_hyd(), ParoiVDF_TBLE::calculer_hyd_BiK(), ParoiVDF_TBLE_LRM::calculer_hyd_BiK(), ParoiVEF_TBLE::calculer_hyd_BiK(), and ParoiVEF_TBLE_scal::calculer_scal().
get_Un_old() [1/2]
double Eq_couch_lim::get_Un_old (int j, int i) inline
get_v() [1/2]
double Eq_couch_lim::get_v (int i) inline
get_cis() [1/2]
double Eq_couch_lim::get_cis (int j) inline
Referenced by ParoiVEF_TBLE::calculer_hyd(), and ParoiVEF_TBLE::calculer_hyd_BiK().
get_utau_old() [1/2]
double Eq_couch_lim::get_utau_old () inline
Referenced by Diffu_lm::calculer_a_local(), and Diffu_lm::calculer_D_local().
get_y() [1/2]
double Eq_couch_lim::get_y (int i) inline
Referenced by Diffu_k::calculer_a_local(), Diffu_lm::calculer_a_local(), Diffu_lm::calculer_D_local(), and ParoiVEF_TBLE_scal::calculer_scal().
get_yc() [1/2]
double Eq_couch_lim::get_yc (int i) inline
get_Unp1() [2/2]
double Eq_couch_lim::get_Unp1 (int j, int i) const inline
get_Un_old() [2/2]
double Eq_couch_lim::get_Un_old (int j, int i) const inline
get_v() [2/2]
double Eq_couch_lim::get_v (int i) const inline
get_cis() [2/2]
double Eq_couch_lim::get_cis (int j) const inline
get_utau_old() [2/2]
double Eq_couch_lim::get_utau_old () const inline
get_utau()
double Eq_couch_lim::get_utau () const inline
get_y() [2/2]
double Eq_couch_lim::get_y (int i) const inline
get_yc() [2/2]
double Eq_couch_lim::get_yc (int i) const inline
get_diffu()
Diffu_totale_base & Eq_couch_lim::get_diffu () inline
References TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by ParoiVEF_TBLE::init_lois_paroi().
associer_milieu()
void Eq_couch_lim::associer_milieu (const Milieu_base & m) inline
get_milieu()
Milieu_base & Eq_couch_lim::get_milieu () inline
References TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Diffu_lm::calculer_D_local().
Member Data Documentation
info_obj
const Type_info Eq_couch_lim::info_obj static