TrioCFD: Op_Conv_VDF_base Class Reference
Op_Conv_VDF_base Class Reference abstract
#include <Op_Conv_VDF_base.h>
Public Member Functions
double calculer_dt_stab () const override
void completer () override
void contribuer_au_second_membre (DoubleTab &resu) const override
const Type_info * get_info () const override
int impr (Sortie &os) const override
void mettre_a_jour (double) override
const Type_info * get_info () const override
Public Member Functions inherited from Operateur_base
void associer_eqn (const Equation_base &)
virtual double calculer_dt_stab () const
virtual void completer ()
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual void mettre_a_jour (double temps)
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Op_Conv_VDF_base() [1/2]
Op_Conv_VDF_base::Op_Conv_VDF_base ()
~Op_Conv_VDF_base()
Op_Conv_VDF_base::~Op_Conv_VDF_base () override
Op_Conv_VDF_base() [2/2]
Op_Conv_VDF_base::Op_Conv_VDF_base (const Iterateur_VDF_base & iter_base) inline
References iter_.
Member Function Documentation
info()
const Type_info * Op_Conv_VDF_base::info () static
get_info()
const Type_info * Op_Conv_VDF_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Operateur_Conv_base.
Reimplemented in Op_Conv_Amont_VDF_Elem, Op_Conv_Centre_VDF_Elem, Op_Conv_Centre4_VDF_Elem, Op_Conv_Quick_VDF_Elem, Op_Conv_Amont_VDF_Face, Op_Conv_Centre_VDF_Face, Op_Conv_Centre4_VDF_Face, Op_Conv_Quick_VDF_Face_Axi, and Op_Conv_Quick_VDF_Face.
self_cast() [1/2]
Op_Conv_VDF_base & Op_Conv_VDF_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Op_Conv_VDF_base & Op_Conv_VDF_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Op_Conv_VDF_base::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN A surcharger dans les classes derivees.
Parameters
(Sortie& os) un flot de sortie
Returns
(Sortie&) le flot de sortie
Reimplemented from Operateur_Conv_base.
Reimplemented in Op_Conv_Amont_VDF_Elem, Op_Conv_Centre_VDF_Elem, Op_Conv_Centre4_VDF_Elem, Op_Conv_Quick_VDF_Elem, Op_Conv_Amont_VDF_Face, Op_Conv_Centre_VDF_Face, Op_Conv_Centre4_VDF_Face, Op_Conv_Quick_VDF_Face_Axi, and Op_Conv_Quick_VDF_Face.
References Objet_U::que_suis_je().
readOn()
Entree & Op_Conv_VDF_base::readOn (Entree & is) override protected virtual
NE FAIT RIEN A surcharger dans les classes derivees.
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree
Reimplemented from Operateur_Conv_base.
Reimplemented in Op_Conv_Amont_VDF_Elem, Op_Conv_Centre_VDF_Elem, Op_Conv_Centre4_VDF_Elem, Op_Conv_Quick_VDF_Elem, Op_Conv_Amont_VDF_Face, Op_Conv_Centre_VDF_Face, Op_Conv_Centre4_VDF_Face, Op_Conv_Quick_VDF_Face_Axi, and Op_Conv_Quick_VDF_Face.
References TRUST_Vector< _CLASSE_ >::dimensionner(), MorEqn::equation(), Pb_Multiphase::nb_phases(), and Pb_Multiphase::nom_phase().
Referenced by Op_Conv_Amont_VDF_Elem::readOn().
completer()
void Op_Conv_VDF_base::completer () override virtual
Associe l'operateur au domaine_dis, le domaine_Cl_dis, et a l'inconnue de son equation.
Exceptions
pas d'equation associee
Reimplemented from Operateur_base.
References Operateur_base::completer(), Iterateur_VDF_base::completer_(), and iter_.
preparer_calcul()
void Op_Conv_VDF_base::preparer_calcul () override virtual
Reimplemented from Operateur_base.
Reimplemented in Op_Conv_Amont_VDF_Elem, Op_Conv_Centre_VDF_Elem, Op_Conv_Centre4_VDF_Elem, Op_Conv_Quick_VDF_Elem, Op_Conv_Amont_VDF_Face, Op_Conv_Centre_VDF_Face, Op_Conv_Centre4_VDF_Face, Op_Conv_Quick_VDF_Face_Axi, and Op_Conv_Quick_VDF_Face.
References MorEqn::equation(), iter_, Operateur_base::preparer_calcul(), and Iterateur_VDF_base::set_convective_op_pb_type().
Referenced by associer_champ_convecte_elem(), and associer_champ_convecte_face().
associer_domaine_cl_dis()
void Op_Conv_VDF_base::associer_domaine_cl_dis (const Domaine_Cl_dis_base & zcl) inline override virtual
Reimplemented from Operateur_base.
References Iterateur_VDF_base::associer_domaine_cl_dis(), and iter_.
calculer_dt_local()
void Op_Conv_VDF_base::calculer_dt_local (DoubleTab & dt_face) const override virtual
Reimplemented from Operateur_base.
References Iterateur_VDF_base::domaine(), Iterateur_VDF_base::domaine_Cl(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), MorEqn::equation(), Periodique::face_associee(), Domaine_VF::face_surfaces(), Equation_base::inconnue(), iter_, Objet_U::le_nom(), Domaine_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_, _SIZE_ >::mp_max_abs_vect(), Domaine_VF::nb_faces(), Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_face(), Front_VF::num_premiere_face(), Domaine_VF::premiere_face_int(), TRUSTVect< _TYPE_, _SIZE_ >::size(), TRUST_Deriv< _CLASSE_ >::valeur(), Champ_Inc_base::valeurs(), vitesse(), and Domaine_VF::volumes_entrelaces().
calculer_pour_post()
void Op_Conv_VDF_base::calculer_pour_post (Champ_base & espace_stockage, const Nom & option, int comp) const override virtual
Reimplemented from Operateur_base.
References Operateur_base::calculer_pour_post(), Domaine_dis_base::domaine(), Iterateur_VDF_base::domaine(), Iterateur_VDF_base::domaine_Cl(), MorEqn::equation(), Domaine_VF::face_surfaces(), Domaine_VF::face_voisins(), iter_, Objet_U::le_nom(), Domaine_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Domaine_dis_base::nb_elem(), Domaine_32_64< _SIZE_ >::nb_elem_tot(), Domaine_VF::nb_faces(), Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), Domaine_VF::premiere_face_int(), TRUST_Deriv< _CLASSE_ >::valeur(), Champ_Proto::valeurs(), vitesse(), and Domaine_VF::volumes().
creer_champ()
void Op_Conv_VDF_base::creer_champ (const Motcle & motlu) override virtual
Reimplemented from Operateur_base.
References Champs_compris_T< FIELD_TYPE >::ajoute_champ(), Operateur_base::champs_compris_, Operateur_base::creer_champ(), Objet_U::dimension, Equation_base::discretisation(), Discretisation_base::discretiser_champ(), MorEqn::equation(), and Motcles::rang().
get_noms_champs_postraitables()
void Op_Conv_VDF_base::get_noms_champs_postraitables (Noms & nom, Option opt = NONE) const override virtual
Reimplemented from Operateur_base.
References TRUST_Vector< _CLASSE_ >::add(), MorEqn::equation(), Operateur_base::get_noms_champs_postraitables(), and Pb_Multiphase::nb_phases().
mettre_a_jour()
void Op_Conv_VDF_base::mettre_a_jour (double temps) override virtual
DOES NOTHING - to override in derived classes.
Mise a jour de l'operateur
Parameters
(double) un pas de temps
Reimplemented from Operateur_base.
References Equation_base::champ_convecte(), Champ_Inc_base::changer_temps(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Iterateur_VDF_base::domaine(), MorEqn::equation(), Equation_base::inconnue(), iter_, Operateur_base::le_champ_inco, TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Operateur_base::mettre_a_jour(), Equation_base::milieu(), TRUST_Ref< _CLASSE_ >::non_nul(), Milieu_base::porosite_elem(), Milieu_base::porosite_face(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_Inc_base::valeur_aux_bords(), Champ_Inc_base::valeurs(), Champ_Proto::valeurs(), and vitesse().
calculer_dt_stab()
double Op_Conv_VDF_base::calculer_dt_stab () const override virtual
Calcul dt_stab.
Returns
(double) renvoie toujours 1.e30
Reimplemented from Operateur_base.
References Domaine_32_64< _SIZE_ >::creer_tableau_elements(), Domaine_dis_base::domaine(), Iterateur_VDF_base::domaine(), Iterateur_VDF_base::domaine_Cl(), MorEqn::equation(), Domaine_VF::face_surfaces(), Domaine_VF::face_voisins(), Operateur_Conv_base::fixer_dt_stab_conv(), TRUSTVect< _TYPE_, _SIZE_ >::get_md_vector(), iter_, Objet_U::le_nom(), Domaine_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Process::mp_min(), Domaine_dis_base::nb_elem(), Domaine_VF::nb_faces(), Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), MD_Vector::non_nul(), TRUST_Ref< _CLASSE_ >::non_nul(), Front_VF::num_premiere_face(), Domaine_VF::premiere_face_int(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUST_Deriv< _CLASSE_ >::valeur(), Champ_Proto::valeurs(), vitesse(), Operateur_Conv_base::vitesse_pour_pas_de_temps_, and Domaine_VF::volumes().
impr()
int Op_Conv_VDF_base::impr (Sortie & os) const override virtual
DOES NOTHING - to override in derived classes.
Imprime l'operateur sur un flot de sortie.
Parameters
(Sortie& os)
Returns
(int) renvoie toujours 1
Reimplemented from Operateur_base.
References Iterateur_VDF_base::impr(), and iter_.
get_localisation_pour_post()
Motcle Op_Conv_VDF_base::get_localisation_pour_post (const Nom & option) const override virtual
Reimplemented from Operateur_base.
References Operateur_base::get_localisation_pour_post().
vitesse() [1/2]
virtual const Champ_base & Op_Conv_VDF_base::vitesse () const pure virtual
Implemented in Op_Conv_Amont_VDF_Elem, Op_Conv_Centre_VDF_Elem, Op_Conv_Centre4_VDF_Elem, Op_Conv_Quick_VDF_Elem, Op_Conv_Amont_VDF_Face, Op_Conv_Centre_VDF_Face, Op_Conv_Centre4_VDF_Face, Op_Conv_Quick_VDF_Face_Axi, and Op_Conv_Quick_VDF_Face.
Referenced by associer_champ_convecte_elem(), associer_champ_convecte_face(), calculer_dt_local(), calculer_dt_stab(), calculer_pour_post(), dimensionner_blocs_elem(), and mettre_a_jour().
vitesse() [2/2]
virtual Champ_base & Op_Conv_VDF_base::vitesse () pure virtual
Implemented in Op_Conv_Amont_VDF_Elem, Op_Conv_Centre_VDF_Elem, Op_Conv_Centre4_VDF_Elem, Op_Conv_Quick_VDF_Elem, Op_Conv_Amont_VDF_Face, Op_Conv_Centre_VDF_Face, Op_Conv_Centre4_VDF_Face, Op_Conv_Quick_VDF_Face_Axi, and Op_Conv_Quick_VDF_Face.
calculer()
DoubleTab & Op_Conv_VDF_base::calculer (const DoubleTab & inco, DoubleTab & resu) const inline override virtual
Reimplemented from Operateur_base.
References Iterateur_VDF_base::calculer(), and iter_.
get_iter() [1/2]
const TRUST_Deriv< Iterateur_VDF_base > & Op_Conv_VDF_base::get_iter () const inline
References iter_.
get_iter() [2/2]
TRUST_Deriv< Iterateur_VDF_base > & Op_Conv_VDF_base::get_iter () inline
References iter_.
has_interface_blocs()
int Op_Conv_VDF_base::has_interface_blocs () const inline override virtual
Reimplemented from Operateur_base.
set_incompressible()
void Op_Conv_VDF_base::set_incompressible (const int flag) inline override virtual
Reimplemented from Operateur_Conv_base.
References Operateur_Conv_base::incompressible_, iter_, Objet_U::que_suis_je(), and Iterateur_VDF_base::set_incompressible().
ajouter_blocs()
void Op_Conv_VDF_base::ajouter_blocs (matrices_t mats, DoubleTab & secmem, const tabs_t & semi_impl) const override virtual
Reimplemented from Operateur_base.
References Iterateur_VDF_base::ajouter_blocs(), Statistiques::begin_count(), Statistiques::end_count(), and iter_.
dimensionner_blocs_elem()
void Op_Conv_VDF_base::dimensionner_blocs_elem (matrices_t mats, const tabs_t & semi_impl) const
References Matrix_tools::allocate_morse_matrix(), TRUSTTab< _TYPE_, _SIZE_ >::append_line(), Equation_base::champ_convecte(), Champ_Inc_base::derivees(), Iterateur_VDF_base::domaine(), MorEqn::equation(), Probleme_base::get_champ(), Nom::getString(), Equation_base::has_champ_convecte(), Equation_base::inconnue(), iter_, Field_base::le_nom(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Equation_base::probleme(), TRUSTVect< _TYPE_, _SIZE_ >::size_totale(), Champ_Inc_base::valeurs(), Champ_Proto::valeurs(), and vitesse().
Referenced by Op_Conv_Amont_VDF_Elem::dimensionner_blocs(), and Op_Conv_Centre_VDF_Elem::dimensionner_blocs().
dimensionner_blocs_face()
void Op_Conv_VDF_base::dimensionner_blocs_face (matrices_t matrices, const tabs_t & semi_impl) const
References Matrix_tools::allocate_morse_matrix(), TRUSTTab< _TYPE_, _SIZE_ >::append_line(), Iterateur_VDF_base::domaine(), MorEqn::equation(), Champ_Face_base::fcl(), Probleme_base::get_correlation(), Nom::getString(), Probleme_base::has_correlation(), Equation_base::inconnue(), iter_, Field_base::le_nom(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Matrice_Morse::nb_colonnes(), TRUSTVect< _TYPE_, _SIZE_ >::size_totale(), and Champ_Inc_base::valeurs().
Referenced by Op_Conv_Amont_VPoly_VDF_Face::dimensionner_blocs(), and Op_Conv_Amont_VDF_Face::dimensionner_blocs().
associer_champ_temp()
void Op_Conv_VDF_base::associer_champ_temp (const Champ_Inc_base & ch_unite, bool use_base) const override virtual
Reimplemented from Operateur_Conv_base.
References iter_.
contribuer_au_second_membre()
void Op_Conv_VDF_base::contribuer_au_second_membre (DoubleTab &) const inline override virtual
DOES NOTHING - to override in derived classes.
Parameters
(DoubleTab&) un tableau de valeur (double)
Exceptions
methode a surcharger
Reimplemented from Operateur_base.
References Process::exit().
associer_champ_convecte_elem()
void Op_Conv_VDF_base::associer_champ_convecte_elem () protected
References Iterateur_VDF_base::associer_champ_convecte_ou_inc(), Equation_base::champ_convecte(), MorEqn::equation(), Nom::getString(), Equation_base::has_champ_convecte(), Equation_base::inconnue(), Equation_base::init_champ_convecte(), iter_, Operateur_base::le_champ_inco, Field_base::le_nom(), Operateur_base::nom_inconnue(), TRUST_Ref< _CLASSE_ >::non_nul(), preparer_calcul(), Iterateur_VDF_base::set_name_champ_inco(), TRUST_Ref< _CLASSE_ >::valeur(), and vitesse().
Referenced by Op_Conv_Amont_VDF_Elem::preparer_calcul(), Op_Conv_Centre_VDF_Elem::preparer_calcul(), Op_Conv_Centre4_VDF_Elem::preparer_calcul(), and Op_Conv_Quick_VDF_Elem::preparer_calcul().
associer_champ_convecte_face()
void Op_Conv_VDF_base::associer_champ_convecte_face () protected
References Iterateur_VDF_base::associer_champ_convecte_ou_inc(), MorEqn::equation(), Nom::getString(), Equation_base::inconnue(), iter_, Operateur_base::le_champ_inco, Field_base::le_nom(), Operateur_base::nom_inconnue(), TRUST_Ref< _CLASSE_ >::non_nul(), preparer_calcul(), Iterateur_VDF_base::set_name_champ_inco(), TRUST_Ref< _CLASSE_ >::valeur(), and vitesse().
Referenced by Op_Conv_Amont_VDF_Face::preparer_calcul(), Op_Conv_Centre_VDF_Face::preparer_calcul(), Op_Conv_Centre4_VDF_Face::preparer_calcul(), Op_Conv_Quick_VDF_Face_Axi::preparer_calcul(), and Op_Conv_Quick_VDF_Face::preparer_calcul().
Member Data Documentation
info_obj
const Type_info Op_Conv_VDF_base::info_obj static
iter_
TRUST_Deriv< Iterateur_VDF_base > Op_Conv_VDF_base::iter_ protected
Referenced by Op_Conv_Amont_VPoly_VDF_Face::ajouter_blocs(), ajouter_blocs(), associer_champ_convecte_elem(), associer_champ_convecte_face(), associer_champ_temp(), associer_domaine_cl_dis(), calculer(), calculer_dt_local(), calculer_dt_stab(), calculer_pour_post(), completer(), dimensionner_blocs_elem(), dimensionner_blocs_face(), get_iter(), impr(), mettre_a_jour(), Op_Conv_VDF_base(), preparer_calcul(), and set_incompressible().