TrioCFD: Op_Diff_PolyMAC_Elem Class Reference
Op_Diff_PolyMAC_Elem Class Reference
#include <Op_Diff_PolyMAC_Elem.h>
Public Member Functions
void completer () override
void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const override
void dimensionner (Matrice_Morse &mat) const override
const Type_info * get_info () const override
void mettre_a_jour (double t) override
void modifier_pour_Cl (Matrice_Morse &la_matrice, DoubleTab &secmem) const override
Public Member Functions inherited from Op_Diff_PolyMAC_base
double calculer_dt_stab () const override
void completer () override
const Type_info * get_info () const override
void mettre_a_jour (double t) override
Public Member Functions inherited from Op_Diff_PolyMAC_Gen_base
const Type_info * get_info () const override
int impr (Sortie &os) const override
Public Member Functions inherited from Operateur_Diff_base
virtual void associer_diffusivite_pour_pas_de_temps (const Champ_base &)
const Type_info * get_info () const override
Public Member Functions inherited from Operateur_base
void associer_eqn (const Equation_base &)
virtual double calculer_dt_stab () const
virtual void completer ()
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual void mettre_a_jour (double temps)
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Operateur_Diff_base
virtual const Champ_base & diffusivite_pour_pas_de_temps () const
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Op_Diff_PolyMAC_Elem()
Op_Diff_PolyMAC_Elem::Op_Diff_PolyMAC_Elem ()
~Op_Diff_PolyMAC_Elem()
Op_Diff_PolyMAC_Elem::~Op_Diff_PolyMAC_Elem ()
Member Function Documentation
cree_instance()
Objet_U * Op_Diff_PolyMAC_Elem::cree_instance () static
taille_memoire()
unsigned Op_Diff_PolyMAC_Elem::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Op_Diff_Nonlinear_PolyMAC_Elem, Op_Dift_PolyMAC_Elem, and Op_Dift_Nonlinear_PolyMAC_Elem.
duplique()
int Op_Diff_PolyMAC_Elem::duplique () const override virtual
Implements Objet_U.
Reimplemented in Op_Diff_Nonlinear_PolyMAC_Elem, Op_Dift_PolyMAC_Elem, and Op_Dift_Nonlinear_PolyMAC_Elem.
info()
const Type_info * Op_Diff_PolyMAC_Elem::info () static
get_info()
const Type_info * Op_Diff_PolyMAC_Elem::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Op_Diff_PolyMAC_base.
Reimplemented in Op_Diff_Nonlinear_PolyMAC_Elem, Op_Dift_PolyMAC_Elem, and Op_Dift_Nonlinear_PolyMAC_Elem.
self_cast() [1/2]
Op_Diff_PolyMAC_Elem & Op_Diff_PolyMAC_Elem::self_cast (Objet_U & r) static
self_cast() [2/2]
const Op_Diff_PolyMAC_Elem & Op_Diff_PolyMAC_Elem::self_cast (const Objet_U & r) static
printOn()
Sortie & Op_Diff_PolyMAC_Elem::printOn (Sortie & os) const override protected virtual
DOES NOTHING - to override in derived classes.
Imprime l'operateur sur un flot de sortie.
Parameters
(Sortie& os) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Op_Diff_PolyMAC_base.
Reimplemented in Op_Diff_Nonlinear_PolyMAC_Elem, Op_Dift_PolyMAC_Elem, and Op_Dift_Nonlinear_PolyMAC_Elem.
References Op_Diff_PolyMAC_base::printOn().
readOn()
Entree & Op_Diff_PolyMAC_Elem::readOn (Entree & is) override protected virtual
DOES NOTHING - to override in derived classes.
Lit un operateur sur un flot d'entree.
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Op_Diff_PolyMAC_base.
Reimplemented in Op_Diff_Nonlinear_PolyMAC_Elem, Op_Dift_PolyMAC_Elem, and Op_Dift_Nonlinear_PolyMAC_Elem.
References Op_Diff_PolyMAC_base::readOn().
ajouter()
DoubleTab & Op_Diff_PolyMAC_Elem::ajouter (const DoubleTab & inco, DoubleTab & resu) const override virtual
Reimplemented from Operateur_base.
References delta_e, delta_f, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), MorEqn::equation(), Champ_Inc_P0_base::fcl(), Operateur_base::flux_bords_, Op_Diff_PolyMAC_Gen_base::la_zcl_poly_, Op_Diff_PolyMAC_Gen_base::le_dom_poly_, TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Op_Diff_PolyMAC_base::remplir_nu_ef(), TRUST_Vector< _CLASSE_ >::size(), stab_, update_delta(), Op_Diff_PolyMAC_base::update_nu(), and TRUST_Ref< _CLASSE_ >::valeur().
calculer_flux_bord()
virtual void Op_Diff_PolyMAC_Elem::calculer_flux_bord (const DoubleTab & inco) const virtual delete
contribuer_a_avec()
void Op_Diff_PolyMAC_Elem::contribuer_a_avec (const DoubleTab & inco, Matrice_Morse & matrice) const override virtual
DOES NOTHING - to override in derived classes.
Parameters
(DoubleTab&) un tableau de valeur (double)
(Matrice_Morse&) une matrice au format Morse
Exceptions
methode a surcharger
Reimplemented from Operateur_base.
References Echange_contact_PolyMAC::coeff, Echange_contact_PolyMAC::delta, delta_e, delta_f, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), MorEqn::equation(), Champ_Inc_P0_base::fcl(), Echange_contact_PolyMAC::item, Op_Diff_PolyMAC_Gen_base::la_zcl_poly_, Op_Diff_PolyMAC_Gen_base::le_dom_poly_, TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Op_Diff_PolyMAC_base::remplir_nu_ef(), TRUST_Vector< _CLASSE_ >::size(), stab_, update_delta(), Op_Diff_PolyMAC_base::update_nu(), and TRUST_Ref< _CLASSE_ >::valeur().
modifier_pour_Cl()
void Op_Diff_PolyMAC_Elem::modifier_pour_Cl (Matrice_Morse & , DoubleTab &) const inline override virtual
DOES NOTHING - to override in derived classes.
Parameters
(Matrice_Morse&) une matrice au format Morse
(DoubleTab&) un tableau de valeur (double)
Exceptions
methode a surcharger
Reimplemented from Operateur_base.
completer()
void Op_Diff_PolyMAC_Elem::completer () override virtual
Associe l'operateur au domaine_dis, le domaine_Cl_dis, et a l'inconnue de son equation.
Exceptions
pas d'equation associee
Reimplemented from Op_Diff_PolyMAC_base.
References Op_Diff_Turbulent_base::associer_diffusivite_turbulente(), Op_Diff_PolyMAC_base::completer(), Modele_turbulence_scal_base::conductivite_turbulente(), Nom::debute_par(), delta_e, delta_f, delta_f_int, MorEqn::equation(), Process::exit(), Champ_Inc_P0_base::fcl(), Nom::find(), Operateur_base::flux_bords_, Equation_base::get_modele(), Op_Diff_PolyMAC_Gen_base::le_dom_poly_, TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Objet_U::que_suis_je(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), stab_, TRUST_Ref< _CLASSE_ >::valeur(), TRUST_Ref_Objet_U::valeur(), and Champ_Inc_base::valeurs().
mettre_a_jour()
void Op_Diff_PolyMAC_Elem::mettre_a_jour (double temps) inline override virtual
DOES NOTHING - to override in derived classes.
Mise a jour de l'operateur
Parameters
(double) un pas de temps
Reimplemented from Op_Diff_PolyMAC_base.
References Op_Diff_PolyMAC_base::mettre_a_jour(), and stab_.
dimensionner()
void Op_Diff_PolyMAC_Elem::dimensionner (Matrice_Morse & mat) const override virtual
DOES NOTHING - to override in derived classes.
Parameters
(Matrice_Morse&) une matrice au format Morse
Exceptions
methode a surcharger
Reimplemented from Operateur_base.
References Matrix_tools::allocate_morse_matrix(), TRUSTTab< _TYPE_, _SIZE_ >::append_line(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), MorEqn::equation(), Op_Diff_PolyMAC_Gen_base::le_dom_poly_, TRUSTVect< _TYPE_, _SIZE_ >::line_size(), TRUST_Ref< _CLASSE_ >::valeur(), and Champ_Inc_base::valeurs().
dimensionner_termes_croises()
void Op_Diff_PolyMAC_Elem::dimensionner_termes_croises (Matrice_Morse & matrice, const Probleme_base & autre_pb, int nl, int nc) const override virtual
Reimplemented from Operateur_base.
References Matrix_tools::allocate_morse_matrix(), TRUSTTab< _TYPE_, _SIZE_ >::append_line(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), MorEqn::equation(), Cond_lim_base::frontiere_dis(), Echange_contact_PolyMAC::item, Op_Diff_PolyMAC_Gen_base::la_zcl_poly_, Op_Diff_PolyMAC_Gen_base::le_dom_poly_, Probleme_U::le_nom(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Echange_contact_PolyMAC::nom_autre_pb(), Front_VF::num_face(), TRUST_Vector< _CLASSE_ >::size(), TRUST_Ref< _CLASSE_ >::valeur(), and Champ_Inc_base::valeurs().
ajouter_termes_croises()
void Op_Diff_PolyMAC_Elem::ajouter_termes_croises (const DoubleTab & inco, const Probleme_base & autre_pb, const DoubleTab & autre_inco, DoubleTab & resu) const override virtual
Reimplemented from Operateur_base.
References Echange_contact_PolyMAC::coeff, Echange_contact_PolyMAC::delta, delta_f, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), MorEqn::equation(), Cond_lim_base::frontiere_dis(), Echange_contact_PolyMAC::item, Op_Diff_PolyMAC_Gen_base::la_zcl_poly_, Op_Diff_PolyMAC_Gen_base::le_dom_poly_, Probleme_U::le_nom(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Front_VF::nb_faces(), Echange_contact_PolyMAC::nom_autre_pb(), Front_VF::num_face(), TRUST_Vector< _CLASSE_ >::size(), stab_, update_delta(), Op_Diff_PolyMAC_base::update_nu(), TRUST_Ref< _CLASSE_ >::valeur(), and Champ_Inc_base::valeurs().
contribuer_termes_croises()
void Op_Diff_PolyMAC_Elem::contribuer_termes_croises (const DoubleTab & inco, const Probleme_base & autre_pb, const DoubleTab & autre_inco, Matrice_Morse & matrice) const override virtual
Reimplemented from Operateur_base.
References Echange_contact_PolyMAC::coeff, Echange_contact_PolyMAC::delta, delta_f, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), MorEqn::equation(), Cond_lim_base::frontiere_dis(), Echange_contact_PolyMAC::item, Op_Diff_PolyMAC_Gen_base::la_zcl_poly_, Op_Diff_PolyMAC_Gen_base::le_dom_poly_, Probleme_U::le_nom(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Front_VF::nb_faces(), Echange_contact_PolyMAC::nom_autre_pb(), Front_VF::num_face(), TRUST_Vector< _CLASSE_ >::size(), stab_, update_delta(), Op_Diff_PolyMAC_base::update_nu(), TRUST_Ref< _CLASSE_ >::valeur(), and Champ_Inc_base::valeurs().
update_delta_int()
void Op_Diff_PolyMAC_Elem::update_delta_int () const
References delta_e, delta_f_int, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), MorEqn::equation(), Equation_base::inconnue(), Op_Diff_PolyMAC_Gen_base::le_dom_poly_, TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Op_Diff_PolyMAC_base::remplir_nu_ef(), Op_Diff_PolyMAC_base::update_nu(), TRUST_Ref< _CLASSE_ >::valeur(), and Champ_Inc_base::valeurs().
Referenced by Echange_contact_PolyMAC::update_coeffs(), and update_delta().
update_delta()
void Op_Diff_PolyMAC_Elem::update_delta () const
References delta_f, delta_f_int, TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), MorEqn::equation(), Champ_Inc_P0_base::fcl(), Op_Diff_PolyMAC_Gen_base::la_zcl_poly_, Op_Diff_PolyMAC_Gen_base::le_dom_poly_, TRUSTVect< _TYPE_, _SIZE_ >::line_size(), TRUST_Vector< _CLASSE_ >::size(), update_delta_int(), TRUST_Ref< _CLASSE_ >::valeur(), and Champ_Inc_base::valeurs().
Referenced by ajouter(), ajouter_termes_croises(), contribuer_a_avec(), contribuer_termes_croises(), and Echange_contact_PolyMAC::update_delta().
Member Data Documentation
info_obj
const Type_info Op_Diff_PolyMAC_Elem::info_obj static
stab_
int Op_Diff_PolyMAC_Elem::stab_ = 0
Referenced by ajouter(), ajouter_termes_croises(), completer(), contribuer_a_avec(), contribuer_termes_croises(), and mettre_a_jour().
delta_f_int
DoubleTab Op_Diff_PolyMAC_Elem::delta_f_int mutable
Referenced by completer(), Echange_contact_PolyMAC::update_coeffs(), update_delta(), and update_delta_int().
delta_e
DoubleTab Op_Diff_PolyMAC_Elem::delta_e mutable
Referenced by ajouter(), completer(), contribuer_a_avec(), Echange_contact_PolyMAC::update_delta(), and update_delta_int().
delta_f
DoubleTab Op_Diff_PolyMAC_Elem::delta_f
Referenced by ajouter(), ajouter_termes_croises(), completer(), contribuer_a_avec(), contribuer_termes_croises(), Echange_contact_PolyMAC::update_delta(), and update_delta().