TrioCFD: Diametre_bulles_musig Class Reference
Diametre_bulles_musig Class Reference
#include <Diametre_bulles_musig.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Diametre_bulles_musig()
Diametre_bulles_musig::Diametre_bulles_musig ()
~Diametre_bulles_musig()
Diametre_bulles_musig::~Diametre_bulles_musig ()
Member Function Documentation
cree_instance()
Objet_U * Diametre_bulles_musig::cree_instance () static
taille_memoire()
unsigned Diametre_bulles_musig::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Diametre_bulles_musig::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Diametre_bulles_musig::info () static
get_info()
const Type_info * Diametre_bulles_musig::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Correlation_base.
self_cast() [1/2]
Diametre_bulles_musig & Diametre_bulles_musig::self_cast (Objet_U & r) static
self_cast() [2/2]
const Diametre_bulles_musig & Diametre_bulles_musig::self_cast (const Objet_U & r) static
printOn()
Sortie & Diametre_bulles_musig::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Correlation_base.
readOn()
Entree & Diametre_bulles_musig::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Correlation_base.
References Champs_compris_T< FIELD_TYPE >::ajoute_champ(), Param::ajouter(), Correlation_base::champs_compris_, d_bulle_, diametres_, TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Probleme_base::discretisation(), Discretisation_base::discretiser_champ(), Probleme_base::domaine_dis(), Process::exit(), Milieu_MUSIG::get_Diameter_Inf(), Milieu_MUSIG::get_Diameter_Sauter(), Milieu_MUSIG::get_Diameter_Sup(), Milieu_MUSIG::has_dispersed_gas(), Milieu_MUSIG::has_dispersed_liquid(), Process::je_suis_maitre(), Param::lire_avec_accolades_depuis(), Probleme_base::milieu(), Pb_Multiphase::nb_phases(), Correlation_base::pb_, Objet_U::que_suis_je(), Param::REQUIRED, TRUST_Ref< _CLASSE_ >::valeur(), and Champ_Don_base::valeurs().
get_champ()
const Champ_base & Diametre_bulles_musig::get_champ (const Motcle & nom) const override virtual
Reimplemented from Correlation_base.
References Correlation_base::champs_compris_, Champs_compris_T< FIELD_TYPE >::get_champ(), and Nom::getString().
has_champ() [1/2]
bool Diametre_bulles_musig::has_champ (const Motcle & nom, TRUST_Ref< Champ_base * > & ref_champ) const override virtual
Reimplemented from Correlation_base.
References Correlation_base::champs_compris_, and Champs_compris_T< FIELD_TYPE >::has_champ().
has_champ() [2/2]
bool Diametre_bulles_musig::has_champ (const Motcle & nom) const override virtual
Reimplemented from Correlation_base.
Member Data Documentation
info_obj
const Type_info Diametre_bulles_musig::info_obj static
d_bulle_
double Diametre_bulles_musig::d_bulle_ = -100. protected
Referenced by readOn().
diametres_
TRUST_Deriv< Champ_Fonc_base > Diametre_bulles_musig::diametres_ protected
Referenced by readOn().
n_l
int Diametre_bulles_musig::n_l = -1 protected