TrioCFD: Modele_Lam_Bremhorst_VEF Class Reference
Modele_Lam_Bremhorst_VEF Class Reference
#include <Modele_Lam_Bremhorst_VEF.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Modele_Fonc_Bas_Reynolds_Base
const Type_info * get_info () const override
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Modele_Fonc_Bas_Reynolds_Base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Modele_Lam_Bremhorst_VEF()
Modele_Lam_Bremhorst_VEF::Modele_Lam_Bremhorst_VEF ()
~Modele_Lam_Bremhorst_VEF()
Modele_Lam_Bremhorst_VEF::~Modele_Lam_Bremhorst_VEF ()
Member Function Documentation
cree_instance()
Objet_U * Modele_Lam_Bremhorst_VEF::cree_instance () static
taille_memoire()
unsigned Modele_Lam_Bremhorst_VEF::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Modele_Launder_Sharma_VEF, and Modele_standard_KEps_VEF.
duplique()
int Modele_Lam_Bremhorst_VEF::duplique () const override virtual
Implements Objet_U.
Reimplemented in Modele_Launder_Sharma_VEF, and Modele_standard_KEps_VEF.
info()
const Type_info * Modele_Lam_Bremhorst_VEF::info () static
get_info()
const Type_info * Modele_Lam_Bremhorst_VEF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
Reimplemented in Modele_Launder_Sharma_VEF, and Modele_standard_KEps_VEF.
self_cast() [1/2]
Modele_Lam_Bremhorst_VEF & Modele_Lam_Bremhorst_VEF::self_cast (Objet_U & r) static
self_cast() [2/2]
const Modele_Lam_Bremhorst_VEF & Modele_Lam_Bremhorst_VEF::self_cast (const Objet_U & r) static
printOn()
Sortie & Modele_Lam_Bremhorst_VEF::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
Reimplemented in Modele_Launder_Sharma_VEF, and Modele_standard_KEps_VEF.
readOn()
Entree & Modele_Lam_Bremhorst_VEF::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
Reimplemented in Modele_Launder_Sharma_VEF, and Modele_standard_KEps_VEF.
References Modele_Fonc_Bas_Reynolds_Base::is_Cmu_constant_, Modele_Fonc_Bas_Reynolds_Base::is_Reynolds_stress_isotrope_, Param::lire_avec_accolades_depuis(), Objet_U::que_suis_je(), and set_param().
set_param()
void Modele_Lam_Bremhorst_VEF::set_param (Param & param) virtual
References Param::ajouter(), Modele_Fonc_Bas_Reynolds_Base::is_Cmu_constant_, Modele_Fonc_Bas_Reynolds_Base::is_Reynolds_stress_isotrope_, and Modele_Fonc_Bas_Reynolds_Base::nom_fic.
Referenced by Modele_EASM_Baglietto_VEF::readOn(), readOn(), Modele_Launder_Sharma_VEF::readOn(), and Modele_standard_KEps_VEF::readOn().
Calcul_D()
DoubleTab & Modele_Lam_Bremhorst_VEF::Calcul_D (DoubleTab & D, const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const DoubleTab & vitesse, const DoubleTab & K_eps_Bas_Re, const Champ_Don_base & ch_visco) const override virtual
Implements Modele_Fonc_Bas_Reynolds_Base.
Reimplemented in Modele_Launder_Sharma_VEF, and Modele_standard_KEps_VEF.
Calcul_E()
DoubleTab & Modele_Lam_Bremhorst_VEF::Calcul_E (DoubleTab & E, const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const DoubleTab & transporte, const DoubleTab & K_eps_Bas_Re, const Champ_Don_base & ch_visco, const DoubleTab & visco_turb) const override virtual
Implements Modele_Fonc_Bas_Reynolds_Base.
Reimplemented in Modele_Launder_Sharma_VEF, and Modele_standard_KEps_VEF.
Calcul_Cmu()
DoubleTab & Modele_Lam_Bremhorst_VEF::Calcul_Cmu (DoubleTab & Cmu, const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const DoubleTab & vitesse, const DoubleTab & K_Eps, const double EPS_MIN) const override virtual
Reimplemented from Modele_Fonc_Bas_Reynolds_Base.
References Champ_P1NC::calcul_gradient(), calcul_tenseur_face(), Domaine_VF::creer_tableau_faces(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), init_tenseur_elem(), and init_tenseur_face().
Calcul_Cmu_Paroi()
DoubleTab & Modele_Lam_Bremhorst_VEF::Calcul_Cmu_Paroi (DoubleTab & Cmu, const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const DoubleTab & visco, const DoubleTab & visco_turb, const DoubleTab & loi_paroi, const int idt, const DoubleTab & vitesse, const DoubleTab & K_Eps, const double EPS_MIN) const override virtual
Reimplemented from Modele_Fonc_Bas_Reynolds_Base.
References Champ_P1NC::calcul_duidxj_paroi(), Champ_P1NC::calcul_gradient(), calcul_tenseur_face(), Domaine_VF::creer_tableau_faces(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), init_tenseur_elem(), and init_tenseur_face().
Calcul_F1()
DoubleTab & Modele_Lam_Bremhorst_VEF::Calcul_F1 (DoubleTab & F1, const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const DoubleTab & P, const DoubleTab & K_eps_Bas_Re, const Champ_base & ch_visco) const override virtual
Implements Modele_Fonc_Bas_Reynolds_Base.
Reimplemented in Modele_Launder_Sharma_VEF, and Modele_standard_KEps_VEF.
References Modele_Fonc_Bas_Reynolds_Base::BR_wall_length_, Domaine_VF::creer_tableau_faces(), Domaine_VF::face_voisins(), Domaine_VF::nb_faces(), Champ_Don_base::valeurs(), and Champ_Proto::valeurs().
Calcul_is_Reynolds_stress_isotrope()
int Modele_Lam_Bremhorst_VEF::Calcul_is_Reynolds_stress_isotrope () const override virtual
Reimplemented from Modele_Fonc_Bas_Reynolds_Base.
References Modele_Fonc_Bas_Reynolds_Base::is_Reynolds_stress_isotrope_.
Calcul_is_Cmu_constant()
int Modele_Lam_Bremhorst_VEF::Calcul_is_Cmu_constant () const override virtual
Reimplemented from Modele_Fonc_Bas_Reynolds_Base.
References Modele_Fonc_Bas_Reynolds_Base::is_Cmu_constant_.
init_tenseur_elem()
void Modele_Lam_Bremhorst_VEF::init_tenseur_elem (DoubleTab & Tenseur, const Domaine_VEF & domaine_VEF, const int ndim) const
References Domaine_32_64< _SIZE_ >::creer_tableau_elements(), Objet_U::dimension, Domaine_dis_base::domaine(), TRUSTVect< _TYPE_, _SIZE_ >::get_md_vector(), MD_Vector::non_nul(), and TRUSTTab< _TYPE_, _SIZE_ >::resize().
Referenced by Calcul_Cmu(), Calcul_Cmu_BiK(), Calcul_Cmu_Paroi(), Calcul_Cmu_Paroi_BiK(), calcul_norme_elem(), calcul_tenseur_Re(), calcul_tenseur_Re_BiK(), calcul_tenseur_Re_elem(), calcul_tenseur_Re_elem_BiK(), calcul_tenseur_Re_elem_shih(), and calcul_tenseur_Re_shih().
init_tenseur_face()
void Modele_Lam_Bremhorst_VEF::init_tenseur_face (DoubleTab & Tenseur, const Domaine_VEF & domaine_VEF, const int ndim) const
References Domaine_VF::creer_tableau_faces(), Objet_U::dimension, TRUSTVect< _TYPE_, _SIZE_ >::get_md_vector(), MD_Vector::non_nul(), and TRUSTTab< _TYPE_, _SIZE_ >::resize().
Referenced by Calcul_Cmu(), Calcul_Cmu_BiK(), Calcul_Cmu_Paroi(), and Calcul_Cmu_Paroi_BiK().
calcul_norme_elem()
DoubleTab Modele_Lam_Bremhorst_VEF::calcul_norme_elem (const Domaine_VEF & domaine_VEF, const DoubleTab Tenseur) const virtual
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, and init_tenseur_elem().
Referenced by calcul_tenseur_Re(), calcul_tenseur_Re_BiK(), and calcul_tenseur_Re_shih().
calcul_tenseur_face()
DoubleTab & Modele_Lam_Bremhorst_VEF::calcul_tenseur_face (DoubleTab & Tenseur_face, const DoubleTab & Tenseur_elem, const Domaine_VEF & domaine_VEF, const Domaine_Cl_VEF & domaine_Cl_VEF) const virtual
References Objet_U::dimension, Domaine_VF::face_voisins(), Domaine_Cl_dis_base::les_conditions_limites(), Domaine_VF::nb_faces(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), Domaine_VF::premiere_face_int(), TRUST_Vector< _CLASSE_ >::size(), TRUST_Deriv< _CLASSE_ >::valeur(), and Domaine_VF::volumes().
Referenced by Calcul_Cmu(), Calcul_Cmu_BiK(), Calcul_Cmu_Paroi(), and Calcul_Cmu_Paroi_BiK().
calcul_tenseur_Re()
bool Modele_Lam_Bremhorst_VEF::calcul_tenseur_Re (const DoubleTab & nu_turb, const DoubleTab & G, DoubleTab & Re) const override virtual
Reimplemented from Modele_Fonc_Bas_Reynolds_Base.
References calcul_norme_elem(), calcul_tenseur_Re_elem(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, init_tenseur_elem(), and Modele_Fonc_Bas_Reynolds_Base::mon_equation.
calcul_tenseur_Re_elem()
DoubleTab Modele_Lam_Bremhorst_VEF::calcul_tenseur_Re_elem (const Discretisation_base & dis, const Domaine_dis_base & domaine_dis, const DoubleTab & G, const DoubleTab & S, const DoubleTab & R, const DoubleTab & Sn, const Champ_base & K_Eps) const virtual
References Objet_U::dimension, Discretisation_base::discretiser_champ(), Domaine_dis_base::domaine(), init_tenseur_elem(), Domaine_32_64< _SIZE_ >::nb_elem(), and Debog::verifier().
Referenced by calcul_tenseur_Re().
Calcul_F2()
DoubleTab & Modele_Lam_Bremhorst_VEF::Calcul_F2 (DoubleTab & F2, DoubleTab & Deb, const Domaine_dis_base & domaine_dis, const DoubleTab & K_eps_Bas_Re, const Champ_base & ch_visco) const override virtual
Implements Modele_Fonc_Bas_Reynolds_Base.
Reimplemented in Modele_Launder_Sharma_VEF, and Modele_standard_KEps_VEF.
References Domaine_VF::face_voisins(), Domaine_VF::nb_faces(), Champ_Proto::valeurs(), and Domaine_VF::volumes().
Calcul_Fmu()
DoubleTab & Modele_Lam_Bremhorst_VEF::Calcul_Fmu (DoubleTab & Fmu, const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const DoubleTab & K_eps_Bas_Re, const Champ_Don_base & ch_visco) const override virtual
Implements Modele_Fonc_Bas_Reynolds_Base.
Reimplemented in Modele_Launder_Sharma_VEF, and Modele_standard_KEps_VEF.
References Modele_Fonc_Bas_Reynolds_Base::BR_wall_length_, Domaine_VF::creer_tableau_faces(), Domaine_VF::face_voisins(), Domaine_VF::nb_faces(), and Champ_Don_base::valeurs().
lire()
Entree & Modele_Lam_Bremhorst_VEF::lire (const Motcle & , Entree & is)
associer()
void Modele_Lam_Bremhorst_VEF::associer (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis) override virtual
Implements Modele_Fonc_Bas_Reynolds_Base.
References le_dom_Cl_VEF, and le_dom_VEF.
mettre_a_jour()
void Modele_Lam_Bremhorst_VEF::mettre_a_jour (double temps) override virtual
Implements Modele_Fonc_Bas_Reynolds_Base.
lire_distance_paroi()
void Modele_Lam_Bremhorst_VEF::lire_distance_paroi () override virtual
Reimplemented from Modele_Fonc_Bas_Reynolds_Base.
Reimplemented in Modele_Launder_Sharma_VEF, and Modele_standard_KEps_VEF.
References Modele_Fonc_Bas_Reynolds_Base::BR_wall_length_, Process::exit(), Process::je_suis_maitre(), le_dom_VEF, EcritureLectureSpecial::lecture_special(), Modele_Fonc_Bas_Reynolds_Base::nom_fic, LecFicDiffuse::ouvrir(), Domaine_dis_base::rang_frontiere(), Lec_Diffuse_base::set_bin(), TRUST_Vector< _CLASSE_ >::size(), TRUST_Ref< _CLASSE_ >::valeur(), and Champ_Don_base::valeurs().
calcul_tenseur_Re_elem_shih()
DoubleTab Modele_Lam_Bremhorst_VEF::calcul_tenseur_Re_elem_shih (const Discretisation_base & dis, const Domaine_dis_base & domaine_dis, const DoubleTab & G, const DoubleTab & S, const DoubleTab & R, const DoubleTab & Sn, const DoubleTab & Rn, const Champ_base & K_Eps) const
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Discretisation_base::discretiser_champ(), and init_tenseur_elem().
Referenced by calcul_tenseur_Re_shih().
calcul_tenseur_Re_shih()
DoubleTab Modele_Lam_Bremhorst_VEF::calcul_tenseur_Re_shih (const Discretisation_base & dis, const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const DoubleTab & G, const Champ_base & K_Eps) const
References calcul_norme_elem(), calcul_tenseur_Re_elem_shih(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, and init_tenseur_elem().
Calcul_Cmu_BiK()
DoubleTab & Modele_Lam_Bremhorst_VEF::Calcul_Cmu_BiK (DoubleTab & Cmu, const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const DoubleTab & vitesse, const DoubleTab & K, const DoubleTab & Eps, const double EPS_MIN) const override virtual
Reimplemented from Modele_Fonc_Bas_Reynolds_Base.
References Champ_P1NC::calcul_gradient(), calcul_tenseur_face(), Domaine_VF::creer_tableau_faces(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), init_tenseur_elem(), and init_tenseur_face().
Calcul_Cmu_Paroi_BiK()
DoubleTab & Modele_Lam_Bremhorst_VEF::Calcul_Cmu_Paroi_BiK (DoubleTab & Cmu, const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const DoubleTab & visco, const DoubleTab & visco_turb, const DoubleTab & loi_paroi, const int idt, const DoubleTab & vitesse, const DoubleTab & K, const DoubleTab & Eps, const double EPS_MIN) const override virtual
Reimplemented from Modele_Fonc_Bas_Reynolds_Base.
References Champ_P1NC::calcul_duidxj_paroi(), Champ_P1NC::calcul_gradient(), calcul_tenseur_face(), Domaine_VF::creer_tableau_faces(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), init_tenseur_elem(), and init_tenseur_face().
calcul_tenseur_Re_BiK()
bool Modele_Lam_Bremhorst_VEF::calcul_tenseur_Re_BiK (const DoubleTab & nu_turb, const DoubleTab & G, DoubleTab & Re) const override virtual
Reimplemented from Modele_Fonc_Bas_Reynolds_Base.
References calcul_norme_elem(), calcul_tenseur_Re_elem_BiK(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, init_tenseur_elem(), Modele_Fonc_Bas_Reynolds_Base::ma_seconde_equation, and Modele_Fonc_Bas_Reynolds_Base::mon_equation.
calcul_tenseur_Re_elem_BiK()
DoubleTab Modele_Lam_Bremhorst_VEF::calcul_tenseur_Re_elem_BiK (const Discretisation_base & dis, const Domaine_dis_base & domaine_dis, const DoubleTab & G, const DoubleTab & S, const DoubleTab & R, const DoubleTab & Sn, const Champ_base & K, const Champ_base & Eps) const virtual
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Discretisation_base::discretiser_champ(), and init_tenseur_elem().
Referenced by calcul_tenseur_Re_BiK().
Calcul_D_BiK()
DoubleTab & Modele_Lam_Bremhorst_VEF::Calcul_D_BiK (DoubleTab & D, const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const DoubleTab & vitesse, const DoubleTab & K_Bas_Re, const DoubleTab & eps_Bas_Re, const Champ_Don_base & ch_visco) const override virtual
Implements Modele_Fonc_Bas_Reynolds_Base.
Reimplemented in Modele_Launder_Sharma_VEF, and Modele_standard_KEps_VEF.
Calcul_E_BiK()
DoubleTab & Modele_Lam_Bremhorst_VEF::Calcul_E_BiK (DoubleTab & E, const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const DoubleTab & transporte, const DoubleTab & K_Bas_Re, const DoubleTab & eps_Bas_Re, const Champ_Don_base & ch_visco, const DoubleTab & visco_turb) const override virtual
Implements Modele_Fonc_Bas_Reynolds_Base.
Reimplemented in Modele_Launder_Sharma_VEF, and Modele_standard_KEps_VEF.
Calcul_F1_BiK()
DoubleTab & Modele_Lam_Bremhorst_VEF::Calcul_F1_BiK (DoubleTab & F1, const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const DoubleTab & P, const DoubleTab & K_Bas_Re, const DoubleTab & eps_Bas_Re, const Champ_base & ch_visco) const override virtual
Implements Modele_Fonc_Bas_Reynolds_Base.
Reimplemented in Modele_Launder_Sharma_VEF, and Modele_standard_KEps_VEF.
References Modele_Fonc_Bas_Reynolds_Base::BR_wall_length_, Domaine_VF::creer_tableau_faces(), Domaine_VF::face_voisins(), TRUSTVect< _TYPE_, _SIZE_ >::mp_max_vect(), TRUSTVect< _TYPE_, _SIZE_ >::mp_min_vect(), Domaine_VF::nb_faces(), Champ_Don_base::valeurs(), and Champ_Proto::valeurs().
Calcul_F2_BiK()
DoubleTab & Modele_Lam_Bremhorst_VEF::Calcul_F2_BiK (DoubleTab & F2, DoubleTab & Deb, const Domaine_dis_base & domaine_dis, const DoubleTab & K_Bas_Re, const DoubleTab & eps_Bas_Re, const Champ_base & ch_visco) const override virtual
Implements Modele_Fonc_Bas_Reynolds_Base.
Reimplemented in Modele_Launder_Sharma_VEF, and Modele_standard_KEps_VEF.
References Domaine_VF::face_voisins(), TRUSTVect< _TYPE_, _SIZE_ >::mp_max_vect(), TRUSTVect< _TYPE_, _SIZE_ >::mp_min_vect(), Domaine_VF::nb_faces(), Champ_Proto::valeurs(), and Domaine_VF::volumes().
Calcul_Fmu_BiK()
DoubleTab & Modele_Lam_Bremhorst_VEF::Calcul_Fmu_BiK (DoubleTab & Fmu, const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const DoubleTab & K_Bas_Re, const DoubleTab & eps_Bas_Re, const Champ_Don_base & ch_visco) const override virtual
Implements Modele_Fonc_Bas_Reynolds_Base.
Reimplemented in Modele_Launder_Sharma_VEF, and Modele_standard_KEps_VEF.
References Modele_Fonc_Bas_Reynolds_Base::BR_wall_length_, Domaine_VF::creer_tableau_faces(), Domaine_VF::face_voisins(), TRUSTVect< _TYPE_, _SIZE_ >::mp_max_vect(), TRUSTVect< _TYPE_, _SIZE_ >::mp_min_vect(), Domaine_VF::nb_faces(), and Champ_Don_base::valeurs().
Member Data Documentation
info_obj
const Type_info Modele_Lam_Bremhorst_VEF::info_obj static
le_dom_VEF
TRUST_Ref< Domaine_VEF *> Modele_Lam_Bremhorst_VEF::le_dom_VEF protected
Referenced by associer(), and lire_distance_paroi().
le_dom_Cl_VEF
TRUST_Ref< Domaine_Cl_VEF *> Modele_Lam_Bremhorst_VEF::le_dom_Cl_VEF protected
Referenced by associer().