TrioCFD: Cut_cell_diffusion_auxiliaire Class Reference
Cut_cell_diffusion_auxiliaire Class Reference
#include <Cut_cell_diffusion_auxiliaire.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Cut_cell_schema_auxiliaire
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Cut_cell_schema_auxiliaire
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Cut_cell_diffusion_auxiliaire()
Cut_cell_diffusion_auxiliaire::Cut_cell_diffusion_auxiliaire ()
References Cut_cell_schema_auxiliaire::methode_valeur_remplissage_.
~Cut_cell_diffusion_auxiliaire()
Cut_cell_diffusion_auxiliaire::~Cut_cell_diffusion_auxiliaire ()
Member Function Documentation
cree_instance()
Objet_U * Cut_cell_diffusion_auxiliaire::cree_instance () static
taille_memoire()
unsigned Cut_cell_diffusion_auxiliaire::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Cut_cell_diffusion_auxiliaire::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Cut_cell_diffusion_auxiliaire::info () static
get_info()
const Type_info * Cut_cell_diffusion_auxiliaire::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
Cut_cell_diffusion_auxiliaire & Cut_cell_diffusion_auxiliaire::self_cast (Objet_U & r) static
self_cast() [2/2]
const Cut_cell_diffusion_auxiliaire & Cut_cell_diffusion_auxiliaire::self_cast (const Objet_U & r) static
printOn()
Sortie & Cut_cell_diffusion_auxiliaire::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
References Objet_U::printOn().
readOn()
Entree & Cut_cell_diffusion_auxiliaire::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
References Param::lire_avec_accolades(), Objet_U::que_suis_je(), and set_param().
associer()
void Cut_cell_diffusion_auxiliaire::associer (DoubleTabFT_cut_cell_scalar & flux_interface_efficace)
References flux_interface_efficace_ptr_.
Referenced by IJK_Thermal_cut_cell::initialize().
set_param()
void Cut_cell_diffusion_auxiliaire::set_param (Param & param)
References Param::ajouter_flag(), deactivate_correction_petites_cellules_diffusion_, and Cut_cell_schema_auxiliaire::set_param().
Referenced by readOn().
dying_cells_flux()
double Cut_cell_diffusion_auxiliaire::dying_cells_flux (int num_face, int phase, int n, const Cut_field_vector3_double & cut_field_total_velocity, const Cut_field_double & cut_field) override protected virtual
Implements Cut_cell_schema_auxiliaire.
References Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::get_cut_cell_disc(), Cut_cell_FT_Disc::get_ijk(), IJK_Interfaces::get_indicatrice_surfacique_efficace_face(), Cut_cell_FT_Disc::get_interfaces(), Cut_cell_FT_Disc::get_n_face(), IJK_Interfaces::get_normale_deplacement_interface(), IJK_Interfaces::I(), and select_flux_interface().
small_nascent_cells_flux()
double Cut_cell_diffusion_auxiliaire::small_nascent_cells_flux (int num_face, int phase, int n, const Cut_field_vector3_double & cut_field_total_velocity, const Cut_field_double & cut_field) override protected virtual
Implements Cut_cell_schema_auxiliaire.
References Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::get_cut_cell_disc(), Cut_cell_FT_Disc::get_ijk(), IJK_Interfaces::get_indicatrice_surfacique_efficace_face(), Cut_cell_FT_Disc::get_interfaces(), Cut_cell_FT_Disc::get_n_face(), IJK_Interfaces::get_normale_deplacement_interface(), IJK_Interfaces::In(), and select_flux_interface().
select_flux_interface()
const DoubleTabFT_cut_cell_scalar & Cut_cell_diffusion_auxiliaire::select_flux_interface (int phase) protected
References Process::exit(), and flux_interface_efficace_ptr_.
Referenced by dying_cells_flux(), and small_nascent_cells_flux().
Member Data Documentation
info_obj
const Type_info Cut_cell_diffusion_auxiliaire::info_obj static
deactivate_correction_petites_cellules_diffusion_
int Cut_cell_diffusion_auxiliaire::deactivate_correction_petites_cellules_diffusion_
Referenced by IJK_Thermal_cut_cell::perform_thermal_step(), and set_param().
flux_interface_efficace_ptr_
DoubleTabFT_cut_cell_scalar* Cut_cell_diffusion_auxiliaire::flux_interface_efficace_ptr_ = nullptr
Referenced by associer(), and select_flux_interface().