TrioCFD: Modele_turbulence_hyd_RANS_K_Eps_base Class Reference
Modele_turbulence_hyd_RANS_K_Eps_base Class Reference abstract
#include <Modele_turbulence_hyd_RANS_K_Eps_base.h>
Public Member Functions
const Type_info * get_info () const override
int reprendre (Entree &is) override
int sauvegarder (Sortie &os) const override
const Type_info * get_info () const override
Public Member Functions inherited from Modele_turbulence_hyd_base
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Type_info * get_info () const override
virtual void imprimer (Sortie &) const
void lire_distance_paroi ()
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual int preparer_calcul ()
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
See also
Modele_turbulence_hyd_base
Constructor & Destructor Documentation
Modele_turbulence_hyd_RANS_K_Eps_base()
Modele_turbulence_hyd_RANS_K_Eps_base::Modele_turbulence_hyd_RANS_K_Eps_base ()
~Modele_turbulence_hyd_RANS_K_Eps_base()
Modele_turbulence_hyd_RANS_K_Eps_base::~Modele_turbulence_hyd_RANS_K_Eps_base () override
Member Function Documentation
info()
const Type_info * Modele_turbulence_hyd_RANS_K_Eps_base::info () static
get_info()
const Type_info * Modele_turbulence_hyd_RANS_K_Eps_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Modele_turbulence_hyd_2_eq_base.
self_cast() [1/2]
Modele_turbulence_hyd_RANS_K_Eps_base & Modele_turbulence_hyd_RANS_K_Eps_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Modele_turbulence_hyd_RANS_K_Eps_base & Modele_turbulence_hyd_RANS_K_Eps_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Modele_turbulence_hyd_RANS_K_Eps_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Modele_turbulence_hyd_2_eq_base.
References Modele_turbulence_hyd_2_eq_base::printOn().
readOn()
Entree & Modele_turbulence_hyd_RANS_K_Eps_base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Modele_turbulence_hyd_2_eq_base.
References Modele_turbulence_hyd_2_eq_base::readOn().
Referenced by Modele_turbulence_hyd_K_Eps::readOn(), Modele_turbulence_hyd_K_Eps_2_Couches::readOn(), Modele_turbulence_hyd_K_Eps_Bas_Reynolds::readOn(), and Modele_turbulence_hyd_K_Eps_Realisable::readOn().
set_param()
void Modele_turbulence_hyd_RANS_K_Eps_base::set_param (Param & param) override virtual
Reimplemented from Modele_turbulence_hyd_2_eq_base.
References Param::ajouter(), Modele_turbulence_hyd_2_eq_base::EPS_MAX_, Modele_turbulence_hyd_2_eq_base::EPS_MIN_, and Modele_turbulence_hyd_2_eq_base::set_param().
Referenced by Modele_turbulence_hyd_K_Eps::set_param(), Modele_turbulence_hyd_K_Eps_2_Couches::set_param(), Modele_turbulence_hyd_K_Eps_Bas_Reynolds::set_param(), and Modele_turbulence_hyd_K_Eps_Realisable::set_param().
completer()
void Modele_turbulence_hyd_RANS_K_Eps_base::completer () override virtual
Reimplemented from Modele_turbulence_hyd_base.
References Equation_base::completer(), eqn_transp_K_Eps(), and Modele_turbulence_hyd_2_eq_base::verifie_loi_paroi().
sauvegarder()
int Modele_turbulence_hyd_RANS_K_Eps_base::sauvegarder (Sortie & os) const override virtual
Sauvegarde le modele de turbulence sur un flot de sortie.
(en vue d'une reprise) Sauvegarde le type de l'objet et l'equation de transport K-epsilon associee.
Parameters
(Sortie& os) un flot de sortie
Returns
(int) code de retour propage de: Transport_K_Eps::sauvegarder(Sortie&)
Reimplemented from Modele_turbulence_hyd_base.
References eqn_transp_K_Eps(), Equation_base::sauvegarder(), and Modele_turbulence_hyd_base::sauvegarder().
reprendre()
int Modele_turbulence_hyd_RANS_K_Eps_base::reprendre (Entree & is) override virtual
Reprise du modele a partir d'un flot d'entree.
Si l'equation portee par l'objet est non nulle on effectue une reprise "bidon".
Parameters
(Entree& is) un flot d'entree
Returns
(int) code de retour propage de: Transport_K_Eps::sauvegarder(Sortie&) ou 1 si la reprise est bidon.
Reimplemented from Modele_turbulence_hyd_base.
References eqn_transp_K_Eps(), Modele_turbulence_hyd_base::mon_equation_, TRUST_Ref< _CLASSE_ >::non_nul(), Equation_base::reprendre(), Modele_turbulence_hyd_base::reprendre(), and Modele_turbulence_hyd_2_eq_base::reprendre_generique().
data_a_sauvegarder()
std::vector< YAML_data > Modele_turbulence_hyd_RANS_K_Eps_base::data_a_sauvegarder () const override virtual
for PDI IO: retrieve name, type and dimensions of the fields to save/restore
Reimplemented from Modele_turbulence_hyd_base.
References Equation_base::data_a_sauvegarder(), Modele_turbulence_hyd_base::data_a_sauvegarder(), and eqn_transp_K_Eps().
get_champ()
const Champ_base & Modele_turbulence_hyd_RANS_K_Eps_base::get_champ (const Motcle & nom) const override virtual
Reimplemented from Modele_turbulence_hyd_base.
References equation_k_eps(), Nom::getString(), Equation_base::has_champ(), Modele_turbulence_hyd_base::has_champ(), and Modele_turbulence_hyd_2_eq_base::nombre_d_equations().
has_champ() [1/2]
bool Modele_turbulence_hyd_RANS_K_Eps_base::has_champ (const Motcle & nom, TRUST_Ref< Champ_base * > & ref_champ) const override virtual
Reimplemented from Modele_turbulence_hyd_base.
References equation_k_eps(), Equation_base::has_champ(), Modele_turbulence_hyd_base::has_champ(), and Modele_turbulence_hyd_2_eq_base::nombre_d_equations().
Referenced by Modele_turbulence_hyd_K_Eps::get_champ(), Modele_turbulence_hyd_K_Eps_Bas_Reynolds::get_champ(), Modele_turbulence_hyd_K_Eps_Realisable::get_champ(), Modele_turbulence_hyd_K_Eps::has_champ(), Modele_turbulence_hyd_K_Eps_Bas_Reynolds::has_champ(), and Modele_turbulence_hyd_K_Eps_Realisable::has_champ().
has_champ() [2/2]
bool Modele_turbulence_hyd_RANS_K_Eps_base::has_champ (const Motcle & nom) const override virtual
Reimplemented from Modele_turbulence_hyd_base.
References equation_k_eps(), Equation_base::has_champ(), Modele_turbulence_hyd_base::has_champ(), and Modele_turbulence_hyd_2_eq_base::nombre_d_equations().
get_noms_champs_postraitables()
void Modele_turbulence_hyd_RANS_K_Eps_base::get_noms_champs_postraitables (Noms & nom, Option opt = NONE) const override virtual
Reimplemented from Modele_turbulence_hyd_base.
References equation_k_eps(), Equation_base::get_noms_champs_postraitables(), Modele_turbulence_hyd_base::get_noms_champs_postraitables(), and Modele_turbulence_hyd_2_eq_base::nombre_d_equations().
Referenced by Modele_turbulence_hyd_K_Eps::get_noms_champs_postraitables(), Modele_turbulence_hyd_K_Eps_Bas_Reynolds::get_noms_champs_postraitables(), and Modele_turbulence_hyd_K_Eps_Realisable::get_noms_champs_postraitables().
eqn_transp_K_Eps() [1/2]
virtual Transport_K_Eps_base & Modele_turbulence_hyd_RANS_K_Eps_base::eqn_transp_K_Eps () pure virtual
Implemented in Modele_turbulence_hyd_K_Eps, Modele_turbulence_hyd_K_Eps_2_Couches, Modele_turbulence_hyd_K_Eps_Bas_Reynolds, and Modele_turbulence_hyd_K_Eps_Realisable.
Referenced by completer(), Champ_Generique_Morceau_Equation::completer(), Champ_Post_Operateur_Eqn::completer(), data_a_sauvegarder(), reprendre(), sauvegarder(), Pb_Hydraulique_Turbulent_ALE::verifier(), Pb_Hydraulique_Concentration_Turbulent::verifier(), Pb_Hydraulique_Melange_Binaire_Turbulent_QC::verifier(), Pb_Hydraulique_Turbulent::verifier(), Pb_Thermohydraulique_Concentration_Turbulent::verifier(), Pb_Thermohydraulique_Turbulent::verifier(), and Pb_Thermohydraulique_Turbulent_QC::verifier().
eqn_transp_K_Eps() [2/2]
virtual const Transport_K_Eps_base & Modele_turbulence_hyd_RANS_K_Eps_base::eqn_transp_K_Eps () const pure virtual
Implemented in Modele_turbulence_hyd_K_Eps, Modele_turbulence_hyd_K_Eps_2_Couches, Modele_turbulence_hyd_K_Eps_Bas_Reynolds, and Modele_turbulence_hyd_K_Eps_Realisable.
equation_k_eps()
virtual const Equation_base & Modele_turbulence_hyd_RANS_K_Eps_base::equation_k_eps (int) const pure virtual
Implemented in Modele_turbulence_hyd_K_Eps, Modele_turbulence_hyd_K_Eps_2_Couches, Modele_turbulence_hyd_K_Eps_Bas_Reynolds, and Modele_turbulence_hyd_K_Eps_Realisable.
Referenced by get_champ(), get_noms_champs_postraitables(), and has_champ().
associe_modele_fonction() [1/2]
TRUST_Deriv< Modele_Fonc_Bas_Reynolds_Base > & Modele_turbulence_hyd_RANS_K_Eps_base::associe_modele_fonction () inline
References mon_modele_fonc_.
Referenced by Source_Transport_K_Eps_Bas_Reynolds_anisotherme_VEF_Face::ajouter(), Source_Transport_K_Eps_Bas_Reynolds_VEF_Face::ajouter(), Source_Transport_Bas_Reynolds_VDF_Elem_base::ajouter_blocs(), Source_Transport_K_Eps_Bas_Reynolds_aniso_therm_concen_VDF_Elem::ajouter_blocs(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_VDF_Elem::ajouter_blocs(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_QC_VDF_Elem::ajouter_blocs(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_W_VDF_Elem::ajouter_blocs(), calcul_tenseur_Re(), and Modele_turbulence_hyd_K_Eps::verifie_loi_paroi().
associe_modele_fonction() [2/2]
const TRUST_Deriv< Modele_Fonc_Bas_Reynolds_Base > & Modele_turbulence_hyd_RANS_K_Eps_base::associe_modele_fonction () const inline
References mon_modele_fonc_.
calcul_tenseur_Re()
bool Modele_turbulence_hyd_RANS_K_Eps_base::calcul_tenseur_Re (const DoubleTab & nu_turb, const DoubleTab & grad, DoubleTab & Re) const inline override virtual
Reimplemented from Modele_turbulence_hyd_base.
References associe_modele_fonction(), and Modele_Fonc_Bas_Reynolds_Base::calcul_tenseur_Re().
Member Data Documentation
info_obj
const Type_info Modele_turbulence_hyd_RANS_K_Eps_base::info_obj static
mon_modele_fonc_
TRUST_Deriv< Modele_Fonc_Bas_Reynolds_Base > Modele_turbulence_hyd_RANS_K_Eps_base::mon_modele_fonc_ protected
Referenced by associe_modele_fonction(), Modele_turbulence_hyd_K_Eps::calculer_viscosite_turbulente(), Modele_turbulence_hyd_K_Eps_Bas_Reynolds::calculer_viscosite_turbulente(), Modele_turbulence_hyd_K_Eps::fill_turbulent_viscosity_tab(), Modele_turbulence_hyd_K_Eps::get_champ(), Modele_turbulence_hyd_K_Eps_Bas_Reynolds::get_champ(), Modele_turbulence_hyd_K_Eps::get_noms_champs_postraitables(), Modele_turbulence_hyd_K_Eps_Bas_Reynolds::get_noms_champs_postraitables(), Modele_turbulence_hyd_K_Eps::has_champ(), Modele_turbulence_hyd_K_Eps_Bas_Reynolds::has_champ(), Modele_turbulence_hyd_K_Eps::lire_motcle_non_standard(), and Modele_turbulence_hyd_K_Eps_Bas_Reynolds::lire_motcle_non_standard().