TrioCFD: grad_Champ_Face_PolyMAC_P0 Class Reference
grad_Champ_Face_PolyMAC_P0 Class Reference
#include <grad_Champ_Face_PolyMAC_P0.h>
Public Member Functions
int fixer_nb_valeurs_nodales (int n) override
const Type_info * get_info () const override
void mettre_a_jour (double) override
Public Member Functions inherited from Champ_Fonc_Face_PolyMAC
Champ_base & affecter_ (const Champ_base &) override
int fixer_nb_valeurs_nodales (int n) override
const Type_info * get_info () const override
void mettre_a_jour (double) override
DoubleTab & remplir_coord_noeuds (DoubleTab &positions) const override
int remplir_coord_noeuds_et_polys (DoubleTab &positions, IntVect &polys) const override
DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &result, int poly) const override
double valeur_a_elem_compo (const DoubleVect &position, int poly, int ncomp) const override
DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &polys, DoubleTab &result) const override
DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &polys, DoubleVect &result, int ncomp) const override
Public Member Functions inherited from Champ_Fonc_base
Champ_base & affecter_ (const Champ_base &) override
Champ_base & affecter_compo (const Champ_base &, int compo) override
int fixer_nb_valeurs_nodales (int nb_noeuds) override
const Type_info * get_info () const override
void mettre_a_jour (double temps) override
virtual DoubleTab & remplir_coord_noeuds (DoubleTab &) const
virtual DoubleTab & remplir_coord_noeuds_compo (DoubleTab &, int) const
virtual int remplir_coord_noeuds_et_polys (DoubleTab &, IntVect &) const
virtual int remplir_coord_noeuds_et_polys_compo (DoubleTab &, IntVect &, int) const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
DoubleTab & valeur_aux (const DoubleTab &, DoubleTab &) const override
Public Member Functions inherited from Champ_Don_base
void dimensionner (int, int)
int fixer_nb_valeurs_nodales (int nb_noeuds) override
const Type_info * get_info () const override
int imprime (Sortie &, int) const override
virtual int initialiser (const double temps)
void mettre_a_jour (double temps) override
int reprendre (Entree &) override
void resetTime (double time) override
int sauvegarder (Sortie &) const override
DoubleTab & valeurs () override
Public Member Functions inherited from Champ_base
Champ_base & affecter (const Champ_base &)
Champ_base ()
virtual double changer_temps (const double t)
const Type_info * get_info () const override
double temps () const
virtual DoubleTab & trace (const Frontiere_dis_base &, DoubleTab &, double, int distant) const
virtual DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const
virtual double valeur_a_compo (const DoubleVect &position, int ncomp) const
virtual DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &valeurs, int le_poly) const
virtual double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const
virtual DoubleVect & valeur_a_sommet (int, const Domaine &, DoubleVect &) const
virtual DoubleTab & valeur_aux (const DoubleTab &positions, DoubleTab &valeurs) const
virtual DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const
virtual DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const
virtual DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp) const
Public Member Functions inherited from Field_base
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
virtual void fixer_nb_comp (int i)
virtual const Nom & fixer_nom_compo (const Nom &)
virtual const Nom & fixer_nom_compo (int, const Nom &)
virtual const Noms & fixer_noms_compo (const Noms &)
virtual const Nom & fixer_unite (const Nom &)
virtual const Nom & fixer_unite (int i, const Nom &)
virtual const Noms & fixer_unites (const Noms &)
const Type_info * get_info () const override
const Nom & nom_compo (int) const
void nommer (const Nom &) override
const Nom & unite () const
const Nom & unite (int) const
const Noms & unites () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Champ_Proto
int lire_dimension (Entree &, const Nom &)
int lire_dimension (int dim, const Nom &le_nom_)
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
 grad_u(f, n*D + dU) returns the gradient of the dU velocity component in the phase n at face f
 grad_u(nf_tot + e*D + dX, n*D + dU) returns the gradient of the dU velocity component in the phase n in element e along the dX component
   (i.e. = dU/dX)
 In 2D, the gradient at the element e in phase n is equal to :
             |   grad_u(nf_tot + e*D + 0, n*D + 0)   grad_u(nf_tot + e*D + 1, n*D + 0)   |
   grad_u =  |                                                                           |
             |   grad_u(nf_tot + e*D + 0, n*D + 1)   grad_u(nf_tot + e*D + 1, n*D + 1)   |
 The gradient is calculated using past values of the velocity
   We compute the gradient at the faces for all velocity components, then interpolate it to obtain the gradient at the elements
Constructor & Destructor Documentation
grad_Champ_Face_PolyMAC_P0()
grad_Champ_Face_PolyMAC_P0::grad_Champ_Face_PolyMAC_P0 ()
~grad_Champ_Face_PolyMAC_P0()
grad_Champ_Face_PolyMAC_P0::~grad_Champ_Face_PolyMAC_P0 ()
Member Function Documentation
cree_instance()
Objet_U * grad_Champ_Face_PolyMAC_P0::cree_instance () static
taille_memoire()
unsigned grad_Champ_Face_PolyMAC_P0::taille_memoire () const override virtual
Reimplemented from Champ_Fonc_Face_PolyMAC.
duplique()
int grad_Champ_Face_PolyMAC_P0::duplique () const override virtual
Reimplemented from Champ_Fonc_Face_PolyMAC.
info()
const Type_info * grad_Champ_Face_PolyMAC_P0::info () static
get_info()
const Type_info * grad_Champ_Face_PolyMAC_P0::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Champ_Fonc_Face_PolyMAC.
self_cast() [1/2]
grad_Champ_Face_PolyMAC_P0 & grad_Champ_Face_PolyMAC_P0::self_cast (Objet_U & r) static
self_cast() [2/2]
const grad_Champ_Face_PolyMAC_P0 & grad_Champ_Face_PolyMAC_P0::self_cast (const Objet_U & r) static
printOn()
Sortie & grad_Champ_Face_PolyMAC_P0::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Champ_Fonc_Face_PolyMAC.
References Field_base::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & grad_Champ_Face_PolyMAC_P0::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Champ_Fonc_Face_PolyMAC.
fixer_nb_valeurs_nodales()
int grad_Champ_Face_PolyMAC_P0::fixer_nb_valeurs_nodales (int nb_noeuds) override virtual
Fixe le nombre de degres de liberte par composante.
Parameters
(int nb_noeuds) le nombre de degre de liberte par composante
Reimplemented from Champ_Fonc_Face_PolyMAC.
References Champ_Fonc_base::creer_tableau_distribue(), Objet_U::dimension, Champ_Fonc_base::domaine(), Champ_Fonc_base::domaine_dis_base(), and Field_base::nb_compo_.
Referenced by PolyMAC_P0_discretisation::grad_u().
mettre_a_jour()
void grad_Champ_Face_PolyMAC_P0::mettre_a_jour (double un_temps) override virtual
Mise a jour en temps du champ.
Parameters
(double temps) le temps de mise a jour
Reimplemented from Champ_Fonc_Face_PolyMAC.
References me_calculer(), Champ_Fonc_base::mettre_a_jour(), and Champ_base::temps().
me_calculer()
void grad_Champ_Face_PolyMAC_P0::me_calculer (double tps)
References calc_gradfve(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), init_grad(), is_init, update_ge(), update_tab_grad(), and Champ_Don_base::valeurs().
Referenced by mettre_a_jour().
champ_a_deriver() [1/2]
virtual Champ_Face_PolyMAC_P0 & grad_Champ_Face_PolyMAC_P0::champ_a_deriver () inline virtual
References champ_, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by calc_gradfve(), and update_tab_grad().
champ_a_deriver() [2/2]
virtual const Champ_Face_PolyMAC_P0 & grad_Champ_Face_PolyMAC_P0::champ_a_deriver () const inline virtual
References champ_, and TRUST_Ref< _CLASSE_ >::valeur().
associer_champ()
void grad_Champ_Face_PolyMAC_P0::associer_champ (const Champ_Face_PolyMAC_P0 & ch) inline
References champ_.
Referenced by PolyMAC_P0_discretisation::grad_u().
associer_domaine_Cl_dis_base()
void grad_Champ_Face_PolyMAC_P0::associer_domaine_Cl_dis_base (const Domaine_Cl_dis_base & le_dom_Cl_dis_base) inline
References le_Dom_Cl_PolyMAC_P0P1NC.
Referenced by PolyMAC_P0_discretisation::grad_u().
update_tab_grad()
void grad_Champ_Face_PolyMAC_P0::update_tab_grad (int full_stencil)
References champ_a_deriver(), Champ_Fonc_base::domaine(), Champ_Inc_base::domaine_Cl_dis(), Champ_Fonc_base::domaine_vf(), Champ_Face_base::fcl(), gradve_d, gradve_e, gradve_w, Domaine_Cl_dis_base::les_conditions_limites(), and Champ_Don_base::valeurs().
Referenced by me_calculer().
calc_gradfve()
void grad_Champ_Face_PolyMAC_P0::calc_gradfve ()
References champ_a_deriver(), Objet_U::dimension, Champ_Fonc_base::domaine(), Champ_Inc_base::domaine_Cl_dis(), Champ_Fonc_base::domaine_vf(), Champ_Face_base::fcl(), gradve_d, gradve_e, gradve_w, Domaine_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Domaine_32_64< _SIZE_ >::nb_elem_tot(), Champ_Inc_base::passe(), Champ_Don_base::valeurs(), and Champ_Inc_base::valeurs().
Referenced by me_calculer().
update_ge()
void grad_Champ_Face_PolyMAC_P0::update_ge ()
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Champ_Fonc_base::domaine(), Champ_Fonc_base::domaine_vf(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Domaine_32_64< _SIZE_ >::nb_elem_tot(), and Champ_Don_base::valeurs().
Referenced by me_calculer().
init_grad()
void grad_Champ_Face_PolyMAC_P0::init_grad ()
References is_init.
Referenced by me_calculer().
init_ge2()
void grad_Champ_Face_PolyMAC_P0::init_ge2 () const protected
update_ge2()
void grad_Champ_Face_PolyMAC_P0::update_ge2 (DoubleTab & val, int incr = 0) const protected
Member Data Documentation
info_obj
const Type_info grad_Champ_Face_PolyMAC_P0::info_obj static
gradve_d
IntTab grad_Champ_Face_PolyMAC_P0::gradve_d mutable
Referenced by calc_gradfve(), and update_tab_grad().
gradve_e
IntTab grad_Champ_Face_PolyMAC_P0::gradve_e
Referenced by calc_gradfve(), and update_tab_grad().
gradve_w
DoubleTab grad_Champ_Face_PolyMAC_P0::gradve_w mutable
Referenced by calc_gradfve(), and update_tab_grad().
le_Dom_Cl_PolyMAC_P0P1NC
TRUST_Ref< Domaine_Cl_PolyMAC *> grad_Champ_Face_PolyMAC_P0::le_Dom_Cl_PolyMAC_P0P1NC protected
Referenced by associer_domaine_Cl_dis_base().
champ_
TRUST_Ref< Champ_Face_PolyMAC_P0 *> grad_Champ_Face_PolyMAC_P0::champ_ protected
Referenced by associer_champ(), and champ_a_deriver().
is_init
int grad_Champ_Face_PolyMAC_P0::is_init = 0 protected
Referenced by init_grad(), and me_calculer().
ve2d
IntTab grad_Champ_Face_PolyMAC_P0::ve2d mutable protected
ve2j
IntTab grad_Champ_Face_PolyMAC_P0::ve2j protected
ve2bj
IntTab grad_Champ_Face_PolyMAC_P0::ve2bj protected
ve2c
DoubleTab grad_Champ_Face_PolyMAC_P0::ve2c mutable protected
ve2bc
DoubleTab grad_Champ_Face_PolyMAC_P0::ve2bc protected