TrioCFD: IJK_Field_vector< T, N > Class Template Reference
IJK_Field_vector< T, N > Class Template Reference
#include <IJK_Field_vector.h>
Public Member Functions
void nommer (const Nom &nam) override
Sortie & printOn (Sortie &os) const override
Entree & readOn (Entree &is) override
Public Member Functions inherited from Field_base
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
virtual void fixer_nb_comp (int i)
virtual const Nom & fixer_nom_compo (const Nom &)
virtual const Nom & fixer_nom_compo (int, const Nom &)
virtual const Noms & fixer_noms_compo (const Noms &)
virtual const Nom & fixer_unite (const Nom &)
virtual const Nom & fixer_unite (int i, const Nom &)
virtual const Noms & fixer_unites (const Noms &)
const Type_info * get_info () const override
const Nom & nom_compo (int) const
void nommer (const Nom &) override
const Nom & unite () const
const Nom & unite (int) const
const Noms & unites () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
template<class T, int N>
class IJK_Field_vector< T, N >
For example, the velocity is a fixed vector with 3 components. Each component is a (smart) pointer, thus allowing any derived class of IJK_Field_template to be used (this is used for example in cut-cell methods).
The bracket '[]' operator allows the direct retrieval of a reference to one of the components.
The function IJK_Navier_stokes_tools.h::allocate_velocity() gives an example on how the object is instanciated:
  // Construction of the IJK_Field_template objects
  v.get_ptr(0) = std::make_shared<IJK_Field_template<T,TRUSTArray<T>>>();
  v.get_ptr(1) = std::make_shared<IJK_Field_template<T,TRUSTArray<T>>>();
  v.get_ptr(2) = std::make_shared<IJK_Field_template<T,TRUSTArray<T>>>();
  // Allocation of the fields
  v[0].allocate(s, Domaine_IJK::FACES_I, ghost);
  v[1].allocate(s, Domaine_IJK::FACES_J, ghost);
  v[2].allocate(s, Domaine_IJK::FACES_K, ghost);
The class inherits from Field_base and a IJK_Field_vector can thus be named. It has a default Nature of 'vectoriel'.
Constructor & Destructor Documentation
IJK_Field_vector()
template<class T , int N> IJK_Field_vector< T, N >::IJK_Field_vector () inline
References Field_base::nature_, and Field_base::nb_compo_.
Referenced by IJK_Field_vector< T, N >::duplique().
Member Function Documentation
taille_memoire()
template<class T , int N> unsigned IJK_Field_vector< T, N >::taille_memoire () const inline override virtual
Implements Objet_U.
duplique()
template<class T , int N> int IJK_Field_vector< T, N >::duplique () const inline override virtual
Implements Objet_U.
References Process::exit(), IJK_Field_vector< T, N >::IJK_Field_vector(), and Objet_U::numero().
printOn()
template<class T , int N> Sortie & IJK_Field_vector< T, N >::printOn (Sortie & s) const inline override virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Field_base.
readOn()
template<class T , int N> Entree & IJK_Field_vector< T, N >::readOn (Entree & s) inline override virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Field_base.
nommer()
template<class T , int N> void IJK_Field_vector< T, N >::nommer (const Nom & name) inline override virtual
Donne un nom au champ.
Parameters
(Nom& name) le nom a donner au champ
Reimplemented from Field_base.
References FixedVector< std::shared_ptr< IJK_Field_template< T, TRUSTArray< T > > >, N >::data_, Field_base::fixer_nb_comp(), Field_base::fixer_noms_compo(), Field_base::nom_compo(), and Field_base::nommer().
Referenced by Force_ph::initialise(), and Navier_Stokes_FTD_IJK::initialise_ns_fields().
add_synonymous()
template<class T , int N> void IJK_Field_vector< T, N >::add_synonymous (const Nom & nam) inline override virtual
Reimplemented from Field_base.
References IJK_Field_vector< T, N >::add_synonymous(), Field_base::add_synonymous(), and FixedVector< std::shared_ptr< IJK_Field_template< T, TRUSTArray< T > > >, N >::data_.
Referenced by IJK_Field_vector< T, N >::add_synonymous(), and Navier_Stokes_FTD_IJK::initialise_ns_fields().
localisation() [1/2]
template<class T , int N> Entity & IJK_Field_vector< T, N >::localisation () inline
Referenced by Postprocessing_IJK::postraiter_champs().
localisation() [2/2]
template<class T , int N> const Entity & IJK_Field_vector< T, N >::localisation () const inline
operator[]() [1/2]
template<class T , int N> IJK_Field_template< T, TRUSTArray< T > > & IJK_Field_vector< T, N >::operator[] (int i) inline
References FixedVector< std::shared_ptr< IJK_Field_template< T, TRUSTArray< T > > >, N >::data_.
Referenced by Cut_field_vector< T, N >::operator[]().
operator[]() [2/2]
template<class T , int N> const IJK_Field_template< T, TRUSTArray< T > > & IJK_Field_vector< T, N >::operator[] (int i) const inline
References FixedVector< std::shared_ptr< IJK_Field_template< T, TRUSTArray< T > > >, N >::data_.
get_ptr() [1/2]
template<class T , int N> std::shared_ptr< IJK_Field_template< T, TRUSTArray< T > > > & IJK_Field_vector< T, N >::get_ptr (int i) inline
References FixedVector< std::shared_ptr< IJK_Field_template< T, TRUSTArray< T > > >, N >::data_.
Referenced by Postprocessing_IJK::postraiter_champs().
get_ptr() [2/2]
template<class T , int N> const std::shared_ptr< IJK_Field_template< T, TRUSTArray< T > > > & IJK_Field_vector< T, N >::get_ptr (int i) const inline
References FixedVector< std::shared_ptr< IJK_Field_template< T, TRUSTArray< T > > >, N >::data_.
echange_espace_virtuel()
template<class T , int N> void IJK_Field_vector< T, N >::echange_espace_virtuel () inline
References FixedVector< std::shared_ptr< IJK_Field_template< T, TRUSTArray< T > > >, N >::data_, and IJK_Field_vector< T, N >::echange_espace_virtuel().
Referenced by DNS_QC_double::calculer_convection_vitesse(), Navier_Stokes_FTD_IJK::calculer_dv(), OpGradFluxCentre2IJKScalar_double::calculer_grad_flux(), OpGradFluxQuickIJKScalar_double::calculer_grad_flux(), Navier_Stokes_FTD_IJK::calculer_grad_p_moyen(), Navier_Stokes_FTD_IJK::calculer_grad_p_over_rho_moyen(), Postprocessing_IJK::calculer_gradient_indicatrice(), OpHessFluxCentre2IJKScalar_double::calculer_hess_flux(), IJK_Interfaces::calculer_indicatrice_intermediaire(), Navier_Stokes_FTD_IJK::calculer_inv_rho_grad_p_moyen(), DNS_QC_double::calculer_structural_diffusion_vitesse(), SurfaceVapeurIJKComputation::calculer_surfaces_et_barys_faces_mouillees_vapeur(), DNS_QC_double::calculer_turbulent_diffusion_vitesse(), Corrige_flux_FT_temperature_subresolution::complete_neighbours_and_weighting_colinearity(), Navier_Stokes_FTD_IJK::compute_add_THI_force_sur_d_velocity(), Corrige_flux_FT_temperature_subresolution::compute_cell_neighbours_faces_indices_to_correct(), Corrige_flux_FT_temperature_subresolution::compute_cell_neighbours_mixed_cell_faces_any_field(), Corrige_flux_FT_temperature_subresolution::compute_cell_neighbours_mixed_cell_faces_indices_to_correct(), IJK_Ghost_Fluid_Fields::compute_eulerian_curvature_from_interface(), IJK_Ghost_Fluid_Fields::compute_eulerian_distance(), Corrige_flux_FT_temperature_subresolution::compute_min_max_ijk_any_reachable_fluxes(), Corrige_flux_FT_temperature_subresolution::compute_min_max_ijk_reachable_fluxes(), IJK_Thermal_base::compute_temperature_convective_fluxes(), IJK_Thermal_base::compute_temperature_diffusive_fluxes(), IJK_Thermal_base::compute_temperature_gradient_elem(), IJK_Thermal_base::compute_temperature_hessian_cross_elem(), IJK_Thermal_base::compute_temperature_hessian_diag_elem(), IJK_Field_vector< T, N >::echange_espace_virtuel(), Force_ph::from_spect_to_phys_opti2(), Force_ph::from_spect_to_phys_opti2_advection(), Navier_Stokes_FTD_IJK::initialise_ns_fields(), Navier_Stokes_FTD_IJK::initialise_velocity_from_file(), Navier_Stokes_FTD_IJK::initialise_velocity_using_expression(), IJK_Ghost_Fluid_Fields::initialize(), IJK_Thermal_base::initialize(), IJK_Thermal_Subresolution::initialize(), DNS_QC_double::rk3_sub_step(), DNS_QC_double::run(), Switch_double::run(), DNS_QC_double::sauvegarder_qc(), Fourier_trans::update(), Navier_Stokes_FTD_IJK::update_rho_v(), and Navier_Stokes_FTD_IJK::update_v_or_rhov().
get_domaine()
template<class T , int N> const Domaine_IJK & IJK_Field_vector< T, N >::get_domaine () const inline
References FixedVector< std::shared_ptr< IJK_Field_template< T, TRUSTArray< T > > >, N >::data_.
Referenced by IJK_Interfaces::calculer_barycentre(), Navier_Stokes_FTD_IJK::calculer_dv(), IJK_Interfaces::calculer_indicatrice_surfacique_barycentre_face(), IJK_Interfaces::calculer_indicatrice_surfacique_face(), IJK_Interfaces::calculer_indicatrices(), IJK_Interfaces::calculer_indicatrices_optim(), DNS_QC_double::calculer_moyennes_flux(), SurfaceVapeurIJKComputation::calculer_surfaces_et_barys_faces_mouillees_vapeur(), Navier_Stokes_FTD_IJK::calculer_terme_asservissement(), Navier_Stokes_FTD_IJK::calculer_terme_source_acceleration(), IJK_Interfaces::calculer_vitesse_de_deformation(), IJK_Interfaces::compute_external_forces_(), Statistiques_dns_ijk::compute_vecA_minus_vecB_in_vecA(), Navier_Stokes_FTD_IJK::initialise_ijk_fields(), Navier_Stokes_FTD_IJK::initialise_velocity_from_file(), and DNS_QC_double::run().