TrioCFD: Op_Diff_VDF_base Class Reference
Op_Diff_VDF_base Class Reference
#include <Op_Diff_VDF_base.h>
Public Member Functions
void completer () override
void contribuer_au_second_membre (DoubleTab &resu) const override
const Type_info * get_info () const override
int impr (Sortie &os) const override
Public Member Functions inherited from Operateur_Diff_base
virtual void associer_diffusivite_pour_pas_de_temps (const Champ_base &)
const Type_info * get_info () const override
Public Member Functions inherited from Operateur_base
void associer_eqn (const Equation_base &)
virtual double calculer_dt_stab () const
virtual void completer ()
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual void mettre_a_jour (double temps)
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Operateur_Diff_base
virtual const Champ_base & diffusivite_pour_pas_de_temps () const
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Op_Diff_VDF_base() [1/2]
Op_Diff_VDF_base::Op_Diff_VDF_base ()
~Op_Diff_VDF_base()
Op_Diff_VDF_base::~Op_Diff_VDF_base () override
Op_Diff_VDF_base() [2/2]
Op_Diff_VDF_base::Op_Diff_VDF_base (const Iterateur_VDF_base & iter_base) inline
References iter_.
Member Function Documentation
info()
const Type_info * Op_Diff_VDF_base::info () static
get_info()
const Type_info * Op_Diff_VDF_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Operateur_Diff_base.
Reimplemented in Op_Diff_K_Eps_Bas_Re_VDF_base, Op_Diff_K_Eps_Bas_Re_VDF_Elem_Axi, Op_Diff_K_Eps_Bas_Re_VDF_Elem, Op_Diff_K_Eps_Bas_Re_VDF_var_Elem, Op_Diff_K_Eps_VDF_base, Op_Diff_K_Eps_VDF_Elem, Op_Diff_K_Eps_VDF_Elem_Axi, Op_Diff_K_Eps_QC_VDF_Elem, Op_Diff_K_Eps_var_VDF_Elem, Op_Diff_K_Eps_var_QC_VDF_Elem, Op_Diff_K_VDF_Elem, Op_Diff_Eps_VDF_Elem, Op_Diff_K_Omega_VDF_base, Op_Diff_K_Omega_VDF_Elem, Op_Diff_K_Omega_var_VDF_Elem, Op_Diff_VDF_Elem_base, Op_Diff_VDF_Face_Axi_base, Op_Diff_VDF_Face_base, Op_Dift_VDF_base, Op_Dift_VDF_Elem_base, Op_Dift_VDF_Face_Axi_base, Op_Dift_VDF_Face_base, Op_Diff_VDF_Elem, Op_Diff_VDF_Elem_Axi, Op_Diff_VDF_Elem_aniso, Op_Diff_VDF_Multi_inco_Elem, Op_Diff_VDF_Multi_inco_Multi_scalar_Elem, Op_Diff_VDF_Multi_inco_Elem_Axi, Op_Diff_VDF_Face, Op_Diff_VDF_Face_Axi, Op_Dift_Multiphase_VDF_Elem, Op_Dift_Multiphase_VDF_Face, Op_Dift_VDF_Elem, Op_Dift_VDF_Elem_Axi, Op_Dift_VDF_Multi_inco_Elem, Op_Dift_VDF_Multi_inco_Elem_Axi, Op_Dift_VDF_Face, and Op_Dift_VDF_Face_Axi.
self_cast() [1/2]
Op_Diff_VDF_base & Op_Diff_VDF_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Op_Diff_VDF_base & Op_Diff_VDF_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Op_Diff_VDF_base::printOn (Sortie & os) const override protected virtual
DOES NOTHING - to override in derived classes.
Imprime l'operateur sur un flot de sortie.
Parameters
(Sortie& os) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Operateur_Diff_base.
Reimplemented in Op_Diff_K_Eps_Bas_Re_VDF_base, Op_Diff_K_Eps_Bas_Re_VDF_Elem_Axi, Op_Diff_K_Eps_Bas_Re_VDF_Elem, Op_Diff_K_Eps_Bas_Re_VDF_var_Elem, Op_Diff_K_Eps_VDF_base, Op_Diff_K_Eps_VDF_Elem, Op_Diff_K_Eps_VDF_Elem_Axi, Op_Diff_K_Eps_QC_VDF_Elem, Op_Diff_K_Eps_var_VDF_Elem, Op_Diff_K_Eps_var_QC_VDF_Elem, Op_Diff_K_VDF_Elem, Op_Diff_Eps_VDF_Elem, Op_Diff_K_Omega_VDF_base, Op_Diff_K_Omega_VDF_Elem, Op_Diff_K_Omega_var_VDF_Elem, Op_Diff_VDF_Elem_base, Op_Diff_VDF_Face_Axi_base, Op_Diff_VDF_Face_base, Op_Dift_VDF_base, Op_Dift_VDF_Elem_base, Op_Dift_VDF_Face_Axi_base, Op_Dift_VDF_Face_base, Op_Diff_VDF_Elem, Op_Diff_VDF_Elem_Axi, Op_Diff_VDF_Elem_aniso, Op_Diff_VDF_Multi_inco_Elem, Op_Diff_VDF_Multi_inco_Multi_scalar_Elem, Op_Diff_VDF_Multi_inco_Elem_Axi, Op_Diff_VDF_Face, Op_Diff_VDF_Face_Axi, Op_Dift_Multiphase_VDF_Elem, Op_Dift_Multiphase_VDF_Face, Op_Dift_VDF_Elem, Op_Dift_VDF_Elem_Axi, Op_Dift_VDF_Multi_inco_Elem, Op_Dift_VDF_Multi_inco_Elem_Axi, Op_Dift_VDF_Face, and Op_Dift_VDF_Face_Axi.
References Objet_U::que_suis_je().
Referenced by Op_Dift_VDF_base::printOn().
readOn()
Entree & Op_Diff_VDF_base::readOn (Entree & is) override protected virtual
DOES NOTHING - to override in derived classes.
Lit un operateur sur un flot d'entree.
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Operateur_Diff_base.
Reimplemented in Op_Diff_K_Eps_Bas_Re_VDF_base, Op_Diff_K_Eps_Bas_Re_VDF_Elem_Axi, Op_Diff_K_Eps_Bas_Re_VDF_Elem, Op_Diff_K_Eps_Bas_Re_VDF_var_Elem, Op_Diff_K_Eps_VDF_base, Op_Diff_K_Eps_VDF_Elem, Op_Diff_K_Eps_VDF_Elem_Axi, Op_Diff_K_Eps_QC_VDF_Elem, Op_Diff_K_Eps_var_VDF_Elem, Op_Diff_K_Eps_var_QC_VDF_Elem, Op_Diff_K_VDF_Elem, Op_Diff_Eps_VDF_Elem, Op_Diff_K_Omega_VDF_base, Op_Diff_K_Omega_VDF_Elem, Op_Diff_K_Omega_var_VDF_Elem, Op_Diff_VDF_Elem_base, Op_Diff_VDF_Face_Axi_base, Op_Diff_VDF_Face_base, Op_Dift_VDF_base, Op_Dift_VDF_Elem_base, Op_Dift_VDF_Face_Axi_base, Op_Dift_VDF_Face_base, Op_Diff_VDF_Elem, Op_Diff_VDF_Elem_Axi, Op_Diff_VDF_Elem_aniso, Op_Diff_VDF_Multi_inco_Elem, Op_Diff_VDF_Multi_inco_Multi_scalar_Elem, Op_Diff_VDF_Multi_inco_Elem_Axi, Op_Diff_VDF_Face, Op_Diff_VDF_Face_Axi, Op_Dift_Multiphase_VDF_Elem, Op_Dift_Multiphase_VDF_Face, Op_Dift_VDF_Elem, Op_Dift_VDF_Elem_Axi, Op_Dift_VDF_Multi_inco_Elem, Op_Dift_VDF_Multi_inco_Elem_Axi, Op_Dift_VDF_Face, and Op_Dift_VDF_Face_Axi.
Referenced by Op_Dift_VDF_base::readOn().
completer()
void Op_Diff_VDF_base::completer () override virtual
Associe l'operateur au domaine_dis, le domaine_Cl_dis, et a l'inconnue de son equation.
Exceptions
pas d'equation associee
Reimplemented from Operateur_base.
Reimplemented in Op_Diff_K_Eps_Bas_Re_VDF_base, Op_Diff_K_Eps_Bas_Re_VDF_var_Elem, Op_Diff_K_Eps_VDF_base, Op_Diff_K_Omega_VDF_base, Op_Dift_VDF_Face_Axi_base, Op_Diff_VDF_Elem, Op_Diff_VDF_Elem_Axi, Op_Diff_VDF_Elem_aniso, Op_Diff_VDF_Multi_inco_Elem, Op_Diff_VDF_Multi_inco_Multi_scalar_Elem, Op_Diff_VDF_Multi_inco_Elem_Axi, Op_Diff_VDF_Face, Op_Dift_Multiphase_VDF_Elem, Op_Dift_Multiphase_VDF_Face, Op_Dift_VDF_Elem, Op_Dift_VDF_Elem_Axi, Op_Dift_VDF_Multi_inco_Elem, Op_Dift_VDF_Multi_inco_Elem_Axi, and Op_Dift_VDF_Face.
References Iterateur_VDF_base::associer_champ_convecte_ou_inc(), Iterateur_VDF_base::associer_correlation_flux_parietal(), Operateur_base::completer(), Iterateur_VDF_base::completer_(), Iterateur_VDF_base::creer_champ_T_paroi_pour_flux_parietal(), MorEqn::equation(), Probleme_base::get_correlation(), Nom::getString(), Probleme_base::has_correlation(), Equation_base::inconnue(), iter_, Operateur_base::le_champ_inco, Field_base::le_nom(), Operateur_base::nom_inconnue(), Objet_U_ptr::non_nul(), TRUST_Ref< _CLASSE_ >::non_nul(), Iterateur_VDF_base::set_convective_op_pb_type(), Iterateur_VDF_base::set_multiscalar_diff(), Iterateur_VDF_base::set_name_champ_inco(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Op_Dift_VDF_Face_Axi_base::completer(), Op_Diff_VDF_Elem::completer(), Op_Diff_VDF_Elem_Axi::completer(), Op_Diff_VDF_Elem_aniso::completer(), Op_Diff_VDF_Multi_inco_Elem::completer(), Op_Diff_VDF_Multi_inco_Multi_scalar_Elem::completer(), Op_Diff_VDF_Multi_inco_Elem_Axi::completer(), Op_Diff_VDF_Face::completer(), and Op_Dift_VDF_base::completer_Op_Dift_VDF_base().
calculer()
DoubleTab & Op_Diff_VDF_base::calculer (const DoubleTab & inco, DoubleTab & resu) const override virtual
calcule la contribution de la diffusion, la range dans resu
Reimplemented from Operateur_base.
Reimplemented in Op_Diff_VDF_Face_Axi_base, Op_Dift_VDF_Face_Axi_base, Op_Diff_K_Eps_Bas_Re_VDF_base, Op_Diff_K_Eps_VDF_base, and Op_Diff_K_Omega_VDF_base.
References Operateur_base::ajouter().
impr()
int Op_Diff_VDF_base::impr (Sortie & os) const override virtual
DOES NOTHING - to override in derived classes.
Imprime l'operateur sur un flot de sortie.
Parameters
(Sortie& os)
Returns
(int) renvoie toujours 1
Reimplemented from Operateur_base.
References Iterateur_VDF_base::impr(), iter_, and Objet_U_ptr::non_nul().
get_iter() [1/2]
const TRUST_Deriv< Iterateur_VDF_base > & Op_Diff_VDF_base::get_iter () const inline
References iter_.
Referenced by T_paroi_Champ_P0_VDF::me_calculer().
get_iter() [2/2]
TRUST_Deriv< Iterateur_VDF_base > & Op_Diff_VDF_base::get_iter () inline
References iter_.
has_interface_blocs()
int Op_Diff_VDF_base::has_interface_blocs () const inline override virtual
Reimplemented from Operateur_base.
Reimplemented in Op_Diff_K_Eps_Bas_Re_VDF_base, Op_Diff_K_Eps_VDF_base, and Op_Diff_K_Omega_VDF_base.
init_op_ext()
void Op_Diff_VDF_base::init_op_ext () const override virtual
Reimplemented from Operateur_Diff_base.
References Iterateur_VDF_base::domaine(), Iterateur_VDF_base::domaine_Cl(), Champ_front_calc::equation(), iter_, Operateur::l_op_base(), Domaine_Cl_dis_base::les_conditions_limites(), Domaine_dis_base::nb_front_Cl(), Operateur_Diff_base::op_ext, op_ext_init_, Equation_base::operateur(), Echange_contact_VDF::T_autre_pb(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by Op_Diff_VDF_Elem_base::ajouter_blocs(), and Op_Diff_VDF_Elem_base::dimensionner_blocs().
calculer_flux_bord()
virtual void Op_Diff_VDF_base::calculer_flux_bord (const DoubleTab & inco, const DoubleTab & val_b) const virtual delete
contribuer_au_second_membre()
void Op_Diff_VDF_base::contribuer_au_second_membre (DoubleTab &) const inline override virtual
DOES NOTHING - to override in derived classes.
Parameters
(DoubleTab&) un tableau de valeur (double)
Exceptions
methode a surcharger
Reimplemented from Operateur_base.
Reimplemented in Op_Dift_VDF_base, Op_Diff_VDF_Face_Axi_base, and Op_Dift_VDF_Face_Axi_base.
References Iterateur_VDF_base::contribuer_au_second_membre(), and iter_.
check_multiphase_compatibility()
void Op_Diff_VDF_base::check_multiphase_compatibility () const inline override virtual
Reimplemented from MorEqn.
calculer_dt_stab_()
double Op_Diff_VDF_base::calculer_dt_stab_ (const Domaine_VDF & zone_VDF) const protected
References Operateur_Diff_base::diffusivite(), Operateur_Diff_base::diffusivite_pour_pas_de_temps(), Domaine_VDF::dim_elem(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, MorEqn::equation(), Support_Champ_Masse_Volumique::get_champ_masse_volumique(), Support_Champ_Masse_Volumique::has_champ_masse_volumique(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Process::mp_min(), Domaine_dis_base::nb_elem(), TRUSTVect< _TYPE_, _SIZE_ >::size(), and Champ_Proto::valeurs().
Referenced by Op_Diff_VDF_Elem_base::calculer_dt_stab(), Op_Diff_VDF_Face_Axi_base::calculer_dt_stab(), and Op_Diff_VDF_Face_base::calculer_dt_stab().
ajoute_terme_pour_axi()
void Op_Diff_VDF_base::ajoute_terme_pour_axi (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl) const protected
References Objet_U::bidim_axi, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Iterateur_VDF_base::domaine(), MorEqn::equation(), Iterateur_VDF_base::evaluateur(), Process::exit(), Domaine_VF::face_voisins(), Eval_Diff_VDF::get_diffusivite(), Nom::getString(), Equation_base::inconnue(), iter_, Field_base::le_nom(), Domaine_dis_base::nb_elem_tot(), Domaine_VF::nb_faces(), Domaine_VDF::orientation(), Objet_U::que_suis_je(), TRUSTVect< _TYPE_, _SIZE_ >::size(), Champ_Inc_base::valeurs(), Champ_Proto::valeurs(), Domaine_VF::volumes_entrelaces(), and Domaine_VF::xv().
Referenced by Op_Diff_VDF_Elem_base::ajouter_blocs(), and Op_Diff_VDF_Face_base::ajouter_blocs().
Member Data Documentation
info_obj
const Type_info Op_Diff_VDF_base::info_obj static
iter_
TRUST_Deriv< Iterateur_VDF_base > Op_Diff_VDF_base::iter_ protected
Referenced by ajoute_terme_pour_axi(), Op_Dift_VDF_base::ajoute_terme_pour_axi_turb(), Op_Diff_VDF_Elem_base::ajouter_blocs(), Op_Diff_VDF_Face_base::ajouter_blocs(), Op_Dift_VDF_base::ajouter_blocs(), Op_Dift_VDF_Face_base::calculer_borne_locale(), Op_Diff_VDF_Elem_base::calculer_dt_stab(), Op_Diff_VDF_Face_base::calculer_dt_stab(), Op_Dift_VDF_Face_base::calculer_dt_stab(), Op_Dift_Multiphase_VDF_Elem::calculer_dt_stab(), Op_Dift_Multiphase_VDF_Face::calculer_dt_stab(), Op_Dift_VDF_Elem_base::calculer_dt_stab_elem(), Op_Dift_VDF_Elem_base::calculer_dt_stab_elem_axi(), Op_Dift_VDF_Elem_base::calculer_dt_stab_elem_var_axi(), completer(), contribuer_au_second_membre(), Op_Diff_VDF_Elem_base::contribuer_termes_croises(), Op_Diff_VDF_Elem_base::dimensionner_blocs(), Op_Diff_VDF_Face_base::dimensionner_blocs(), Op_Dift_VDF_Elem_base::dimensionner_blocs(), Op_Dift_VDF_Face_base::dimensionner_blocs(), Op_Diff_VDF_Elem_base::dimensionner_termes_croises(), get_iter(), impr(), init_op_ext(), Op_Diff_VDF_Elem_base::modifier_pour_Cl(), Op_Diff_VDF_Face_base::modifier_pour_Cl(), Op_Dift_VDF_Elem_base::modifier_pour_Cl(), Op_Dift_VDF_Face_base::modifier_pour_Cl(), and Op_Diff_VDF_base().
op_ext_init_
int Op_Diff_VDF_base::op_ext_init_ = 0 mutable protected
Referenced by Op_Diff_VDF_Elem_base::ajouter_blocs(), Op_Diff_VDF_Elem_base::dimensionner_blocs(), and init_op_ext().