TrioCFD: Corrige_flux_FT_base Class Reference
Corrige_flux_FT_base Class Reference abstract
#include <Corrige_flux_FT_base.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Corrige_flux_FT_base()
Corrige_flux_FT_base::Corrige_flux_FT_base ()
~Corrige_flux_FT_base()
Corrige_flux_FT_base::~Corrige_flux_FT_base () override
Member Function Documentation
info()
const Type_info * Corrige_flux_FT_base::info () static
get_info()
const Type_info * Corrige_flux_FT_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
Reimplemented in Corrige_flux_FT_temperature_conv, and Corrige_flux_FT_temperature_subresolution.
self_cast() [1/2]
Corrige_flux_FT_base & Corrige_flux_FT_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Corrige_flux_FT_base & Corrige_flux_FT_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Corrige_flux_FT_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
Reimplemented in Corrige_flux_FT_temperature_conv, and Corrige_flux_FT_temperature_subresolution.
References Objet_U::printOn().
Referenced by Corrige_flux_FT_temperature_conv::printOn(), and Corrige_flux_FT_temperature_subresolution::printOn().
readOn()
Entree & Corrige_flux_FT_base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
Reimplemented in Corrige_flux_FT_temperature_conv, and Corrige_flux_FT_temperature_subresolution.
References Objet_U::readOn().
Referenced by Corrige_flux_FT_temperature_conv::readOn(), and Corrige_flux_FT_temperature_subresolution::readOn().
initialize()
void Corrige_flux_FT_base::initialize (const Domaine_IJK & dom, const IJK_Field_double & field, const IJK_Interfaces & interfaces, const Probleme_FTD_IJK_base & ijk_ft, Intersection_Interface_ijk_face & intersection_ijk_face, Intersection_Interface_ijk_cell & intersection_ijk_cell) virtual
Reimplemented in Corrige_flux_FT_temperature_conv.
References domaine_, field_, interfaces_, intersection_ijk_cell_, intersection_ijk_face_, and ref_ijk_ft_.
Referenced by Corrige_flux_FT_temperature_conv::initialize(), and initialize_with_subproblems().
initialize_with_subproblems()
void Corrige_flux_FT_base::initialize_with_subproblems (const Domaine_IJK & splitting, const IJK_Field_double & field, const IJK_Interfaces & interfaces, const Probleme_FTD_IJK_base & ijk_ft, Intersection_Interface_ijk_face & intersection_ijk_face, Intersection_Interface_ijk_cell & intersection_ijk_cell, IJK_One_Dimensional_Subproblems & thermal_local_subproblems) virtual
Reimplemented in Corrige_flux_FT_temperature_subresolution.
References initialize().
Referenced by IJK_Thermal_Subresolution::initialize(), and Corrige_flux_FT_temperature_subresolution::initialize_with_subproblems().
set_fluxes_feedback_params()
virtual void Corrige_flux_FT_base::set_fluxes_feedback_params (const int discrete_integral, const int levels) inline virtual
Reimplemented in Corrige_flux_FT_temperature_subresolution.
Referenced by IJK_Thermal_Subresolution::initialize().
set_physical_parameters()
void Corrige_flux_FT_base::set_physical_parameters (const double rhocpl, const double rhocpv, const double ldal, const double ldav)
References lda_l_, lda_v_, rhocp_l_, and rhocp_v_.
Referenced by IJK_Thermal_Subresolution::initialize().
set_convection_diffusion_correction()
virtual void Corrige_flux_FT_base::set_convection_diffusion_correction (const int & convective_flux_correction, const int & diffusive_flux_correction) inline virtual
Reimplemented in Corrige_flux_FT_temperature_subresolution.
Referenced by IJK_Thermal_Subresolution::initialize().
corrige_flux_faceIJ()
virtual void Corrige_flux_FT_base::corrige_flux_faceIJ (IJK_Field_local_double *const flux, const int k_layer, const int dir) pure virtual
Implemented in Corrige_flux_FT_temperature_conv, and Corrige_flux_FT_temperature_subresolution.
Referenced by OpConvQuickInterfaceIJKScalar_double::correct_flux(), and OpConvQuickInterfaceOnefluidIJKScalar_double::correct_flux().
corrige_flux_diff_faceIJ()
virtual void Corrige_flux_FT_base::corrige_flux_diff_faceIJ (IJK_Field_local_double *const flux, const int k_layer, const int dir) inline virtual
Reimplemented in Corrige_flux_FT_temperature_subresolution.
correct_flux_spherical()
virtual void Corrige_flux_FT_base::correct_flux_spherical (Simd_double & a, Simd_double & b, const int & i, const int & j, const int & k_layer, const int dir) inline virtual
Reimplemented in Corrige_flux_FT_temperature_subresolution.
Referenced by OpConvQuickInterfaceIJKScalar_double::correct_flux_spherical().
update_intersections()
virtual void Corrige_flux_FT_base::update_intersections () inline virtual
Reimplemented in Corrige_flux_FT_temperature_subresolution.
Referenced by IJK_Thermal_Subresolution::update_intersections().
update()
virtual void Corrige_flux_FT_base::update () pure virtual
Implemented in Corrige_flux_FT_temperature_conv, and Corrige_flux_FT_temperature_subresolution.
Referenced by OpConvQuickInterfaceOnefluidIJKScalar_double::correct_flux(), and IJK_Thermal_Subresolution::prepare_thermal_flux_correction().
calcul_temperature_flux_interface()
virtual void Corrige_flux_FT_base::calcul_temperature_flux_interface (const IJK_Field_double & temperature, const double ldal, const double ldav, const double dist, const DoubleTab & positions, const DoubleTab & normale, ArrOfDouble & temperature_interp, ArrOfDouble & flux_normal_interp, ArrOfDouble & temp_liqu, ArrOfDouble & temp_vap, DoubleTab & coo_liqu, DoubleTab & coo_vap) const pure virtual
Implemented in Corrige_flux_FT_temperature_conv, and Corrige_flux_FT_temperature_subresolution.
Referenced by IJK_Thermal_base::compute_interfacial_temperature2().
compute_temperature_cell_centre()
virtual void Corrige_flux_FT_base::compute_temperature_cell_centre (IJK_Field_double & temperature) const inline virtual
Reimplemented in Corrige_flux_FT_temperature_subresolution.
Referenced by IJK_Thermal_Subresolution::compute_temperature_cell_centres_first_correction(), and IJK_Thermal_Subresolution::replace_temperature_cell_centres_neighbours().
set_zero_temperature_increment()
virtual void Corrige_flux_FT_base::set_zero_temperature_increment (IJK_Field_double & d_temperature) const inline virtual
Reimplemented in Corrige_flux_FT_temperature_subresolution.
Referenced by IJK_Thermal_Subresolution::set_zero_temperature_increment().
compute_thermal_convective_fluxes()
virtual void Corrige_flux_FT_base::compute_thermal_convective_fluxes (const int & last_flux) inline virtual
Reimplemented in Corrige_flux_FT_temperature_subresolution.
Referenced by IJK_Thermal_Subresolution::compute_convective_fluxes_face_centre().
compute_thermal_diffusive_fluxes()
virtual void Corrige_flux_FT_base::compute_thermal_diffusive_fluxes (const int & last_flux) inline virtual
Reimplemented in Corrige_flux_FT_temperature_subresolution.
Referenced by IJK_Thermal_Subresolution::compute_diffusive_fluxes_face_centre().
complete_thermal_fluxes_face_centre()
virtual void Corrige_flux_FT_base::complete_thermal_fluxes_face_centre (const int & fluxes_correction_conservations) inline virtual
Reimplemented in Corrige_flux_FT_temperature_subresolution.
Referenced by IJK_Thermal_Subresolution::complete_thermal_fluxes_face_centre().
set_convection_negligible()
virtual void Corrige_flux_FT_base::set_convection_negligible (const int & convection_negligible) inline virtual
Reimplemented in Corrige_flux_FT_temperature_subresolution.
Referenced by IJK_Thermal_Subresolution::initialize().
set_diffusion_negligible()
virtual void Corrige_flux_FT_base::set_diffusion_negligible (const int & diffusion_negligible) inline virtual
Reimplemented in Corrige_flux_FT_temperature_subresolution.
Referenced by IJK_Thermal_Subresolution::initialize().
clean()
virtual void Corrige_flux_FT_base::clean () inline virtual
Reimplemented in Corrige_flux_FT_temperature_subresolution.
Referenced by IJK_Thermal_Subresolution::clean_ijk_intersections().
compute_ijk_pure_faces_indices()
virtual void Corrige_flux_FT_base::compute_ijk_pure_faces_indices () inline virtual
Reimplemented in Corrige_flux_FT_temperature_subresolution.
Referenced by IJK_Thermal_Subresolution::prepare_ij_fluxes_k_layers().
sort_ijk_intersections_subproblems_indices_by_k_layers()
virtual void Corrige_flux_FT_base::sort_ijk_intersections_subproblems_indices_by_k_layers () inline virtual
Reimplemented in Corrige_flux_FT_temperature_subresolution.
Referenced by IJK_Thermal_Subresolution::prepare_ij_fluxes_k_layers().
set_debug()
virtual void Corrige_flux_FT_base::set_debug (const int & debug) inline virtual
Reimplemented in Corrige_flux_FT_temperature_subresolution.
Referenced by IJK_Thermal_Subresolution::initialize().
set_distance_cell_faces_from_lrs()
virtual void Corrige_flux_FT_base::set_distance_cell_faces_from_lrs (const int & distance_cell_faces_from_lrs) inline virtual
Reimplemented in Corrige_flux_FT_temperature_subresolution.
Referenced by IJK_Thermal_Subresolution::initialize().
set_correction_cell_neighbours()
virtual void Corrige_flux_FT_base::set_correction_cell_neighbours (const int & correct_temperature_cell_neighbours, const int & neighbours_colinearity_weighting, const int & keep_max_flux_correction, const int & smooth_temperature_field) inline virtual
Reimplemented in Corrige_flux_FT_temperature_subresolution.
Referenced by IJK_Thermal_Subresolution::compute_temperature_cell_centres_first_correction(), and IJK_Thermal_Subresolution::initialize().
set_cell_faces_neighbours_corrected_bool()
virtual void Corrige_flux_FT_base::set_cell_faces_neighbours_corrected_bool (IJK_Field_vector3_int & cell_faces_neighbours_corrected_bool) inline virtual
Reimplemented in Corrige_flux_FT_temperature_subresolution.
Referenced by IJK_Thermal_Subresolution::initialize().
set_eulerian_normal_vectors_ns_normed()
virtual void Corrige_flux_FT_base::set_eulerian_normal_vectors_ns_normed (const IJK_Field_vector3_double * eulerian_normal_vectors_ns_normed) inline virtual
Reimplemented in Corrige_flux_FT_temperature_subresolution.
Referenced by IJK_Thermal_Subresolution::initialize().
set_correction_cell_faces_neighbours()
virtual void Corrige_flux_FT_base::set_correction_cell_faces_neighbours (const int & find_cell_neighbours_for_fluxes_spherical_correction, const int & use_cell_neighbours_for_fluxes_spherical_correction, const int & find_reachable_fluxes, const int & use_reachable_fluxes, const int & keep_first_reachable_fluxes, const int & store_flux_operators_for_energy_balance) inline virtual
Reimplemented in Corrige_flux_FT_temperature_subresolution.
Referenced by IJK_Thermal_Subresolution::initialize().
initialise_cell_neighbours_indices_to_correct()
virtual void Corrige_flux_FT_base::initialise_cell_neighbours_indices_to_correct () inline virtual
Reimplemented in Corrige_flux_FT_temperature_subresolution.
Referenced by IJK_Thermal_Subresolution::compute_convective_diffusive_fluxes_face_centre().
compute_cell_neighbours_faces_indices_for_spherical_correction()
virtual void Corrige_flux_FT_base::compute_cell_neighbours_faces_indices_for_spherical_correction (const int & n_iter_distance) inline virtual
Reimplemented in Corrige_flux_FT_temperature_subresolution.
Referenced by IJK_Thermal_Subresolution::compute_convective_diffusive_fluxes_face_centre().
compute_cell_neighbours_faces_indices_to_correct()
virtual void Corrige_flux_FT_base::compute_cell_neighbours_faces_indices_to_correct (IJK_Field_vector3_int & cell_faces_neighbours_corrected_bool, IJK_Field_vector3_double & cell_faces_neighbours_corrected_velocity_temperature, IJK_Field_vector3_double & cell_faces_neighbours_corrected_convective, IJK_Field_vector3_double & cell_faces_neighbours_corrected_diffusive, IJK_Field_vector3_double & neighbours_weighting_colinearity) inline virtual
Reimplemented in Corrige_flux_FT_temperature_subresolution.
Referenced by IJK_Thermal_Subresolution::compute_min_max_reachable_fluxes().
compute_temperature_cell_centre_neighbours()
virtual void Corrige_flux_FT_base::compute_temperature_cell_centre_neighbours (IJK_Field_double & temperature_neighbours, IJK_Field_int & neighbours_weighting, IJK_Field_double & neighbours_weighting_colinearity) inline virtual
Reimplemented in Corrige_flux_FT_temperature_subresolution.
Referenced by IJK_Thermal_Subresolution::compute_temperature_cell_centres_first_correction().
replace_temperature_cell_centre_neighbours()
virtual void Corrige_flux_FT_base::replace_temperature_cell_centre_neighbours (IJK_Field_double & temperature, IJK_Field_double & temperature_neighbours, IJK_Field_int & neighbours_weighting, IJK_Field_double & neighbours_weighting_colinearity) const inline virtual
Reimplemented in Corrige_flux_FT_temperature_subresolution.
Referenced by IJK_Thermal_Subresolution::compute_temperature_cell_centres_first_correction(), and IJK_Thermal_Subresolution::replace_temperature_cell_centres_neighbours().
store_cell_faces_corrected()
virtual void Corrige_flux_FT_base::store_cell_faces_corrected (IJK_Field_vector3_int & cell_faces_corrected_bool, IJK_Field_vector3_double & cell_faces_corrected_convective, IJK_Field_vector3_double & cell_faces_corrected_diffusive) inline virtual
Reimplemented in Corrige_flux_FT_temperature_subresolution.
Referenced by IJK_Thermal_Subresolution::prepare_ij_fluxes_k_layers().
clear_vectors()
virtual void Corrige_flux_FT_base::clear_vectors () inline virtual
Reimplemented in Corrige_flux_FT_temperature_subresolution.
Referenced by IJK_Thermal_Subresolution::clean_thermal_subproblems().
compute_min_max_ijk_reachable_fluxes()
virtual void Corrige_flux_FT_base::compute_min_max_ijk_reachable_fluxes (const IJK_Field_vector3_int & cell_faces_neighbours_corrected_all_bool, const IJK_Field_int & neighbours_temperature_to_correct, IJK_Field_vector3_int & cell_faces_neighbours_corrected_min_max_bool, const int & max_flux_per_dir, const int & check_cell_center_neighbour, const int & remove_external_neighbour_values, IJK_Field_int & neighbours_temperature_to_correct_trimmed) inline virtual
Reimplemented in Corrige_flux_FT_temperature_subresolution.
compute_min_max_ijk_any_reachable_fluxes()
virtual void Corrige_flux_FT_base::compute_min_max_ijk_any_reachable_fluxes (const IJK_Field_vector3_int & cell_faces_neighbours_corrected_all_bool, const IJK_Field_int & neighbours_temperature_to_correct, IJK_Field_vector3_int & cell_faces_neighbours_corrected_min_max_bool, const int & max_flux_per_dir, const int & check_cell_center_neighbour, const int & remove_external_neighbour_values, IJK_Field_int & neighbours_temperature_to_correct_trimmed) inline virtual
Reimplemented in Corrige_flux_FT_temperature_subresolution.
Referenced by IJK_Thermal_Subresolution::compute_min_max_reachable_fluxes().
replace_cell_neighbours_thermal_convective_diffusive_fluxes_faces()
virtual void Corrige_flux_FT_base::replace_cell_neighbours_thermal_convective_diffusive_fluxes_faces (const IJK_Field_vector3_int & cell_faces_neighbours_corrected_min_max_bool, const IJK_Field_vector3_int & cell_faces_neighbours_corrected_all_bool, const IJK_Field_vector3_double & cell_faces_neighbours_fluxes_corrected, const int & fluxes_type) inline virtual
Reimplemented in Corrige_flux_FT_temperature_subresolution.
Referenced by IJK_Thermal_Subresolution::compute_min_max_reachable_fluxes().
set_temperature_fluxes_periodic_sharing_strategy_on_processors()
virtual void Corrige_flux_FT_base::set_temperature_fluxes_periodic_sharing_strategy_on_processors (const int & copy_fluxes_on_every_procs, const int & copy_temperature_on_every_procs) inline virtual
Reimplemented in Corrige_flux_FT_temperature_subresolution.
Referenced by IJK_Thermal_Subresolution::initialize().
test_if_stencil_inclut_bout_interface_liquide()
bool Corrige_flux_FT_base::test_if_stencil_inclut_bout_interface_liquide () const protected
References ParcoursIJKDir::elem(), ParcoursIJKDir::face(), ParcoursIJKDir::i(), ParcoursIJKDir::j(), ParcoursIJKDir::k(), parcours_, and ref_ijk_ft_.
test_if_stencil_inclut_bout_interface_vapeur()
bool Corrige_flux_FT_base::test_if_stencil_inclut_bout_interface_vapeur () const protected
References ParcoursIJKDir::elem(), ParcoursIJKDir::face(), ParcoursIJKDir::i(), ParcoursIJKDir::j(), ParcoursIJKDir::k(), parcours_, and ref_ijk_ft_.
Member Data Documentation
info_obj
const Type_info Corrige_flux_FT_base::info_obj static
interfaces_
TRUST_Ref< IJK_Interfaces *> Corrige_flux_FT_base::interfaces_ protected
Referenced by Corrige_flux_FT_temperature_conv::corrige_flux_faceIJ(), and initialize().
domaine_
TRUST_Ref< Domaine_IJK *> Corrige_flux_FT_base::domaine_ protected
Referenced by Corrige_flux_FT_temperature_conv::calcul_temp_flux_interf_pour_bary_cell(), Corrige_flux_FT_temperature_conv::calcul_temp_flux_interf_pour_bary_face(), Corrige_flux_FT_temperature_subresolution::compute_cell_neighbours_thermal_fluxes_face_centre(), Corrige_flux_FT_temperature_subresolution::compute_thermal_fluxes_face_centre(), Corrige_flux_FT_temperature_conv::corrige_flux_faceIJ(), Corrige_flux_FT_temperature_conv::extrapolation_amont_1_depuis_l_interface(), initialize(), and Corrige_flux_FT_temperature_conv::interp_back_to_bary_faces().
ref_ijk_ft_
TRUST_Ref< Probleme_FTD_IJK_base *> Corrige_flux_FT_base::ref_ijk_ft_ protected
Referenced by Corrige_flux_FT_temperature_subresolution::combine_all_fluxes_from_outisde_frontier_on_procs(), Corrige_flux_FT_temperature_subresolution::combine_fluxes_from_frontier_on_procs(), Corrige_flux_FT_temperature_subresolution::compute_cell_neighbours_faces_indices_for_spherical_correction(), Corrige_flux_FT_temperature_subresolution::compute_cell_neighbours_faces_indices_to_correct(), Corrige_flux_FT_temperature_subresolution::compute_cell_neighbours_mixed_cell_faces_indices_to_correct(), Corrige_flux_FT_temperature_subresolution::compute_min_max_ijk_any_reachable_fluxes(), Corrige_flux_FT_temperature_subresolution::compute_temperature_cell_centre(), Corrige_flux_FT_temperature_conv::get_ghost_temp_if_cell_is_diph(), Corrige_flux_FT_temperature_subresolution::get_linear_index_global(), Corrige_flux_FT_temperature_subresolution::get_linear_index_local(), Corrige_flux_FT_temperature_subresolution::initialise_any_cell_neighbours_indices_to_correct(), Corrige_flux_FT_temperature_subresolution::initialise_any_cell_neighbours_indices_to_correct_with_flux(), initialize(), Corrige_flux_FT_temperature_subresolution::remove_non_overlapping_fluxes_values(), Corrige_flux_FT_temperature_conv::remplace_flux_par_quick_ghost_amont_1(), Corrige_flux_FT_temperature_conv::remplace_flux_par_somme_rhocpf_Tf_v_Sf(), Corrige_flux_FT_temperature_subresolution::replace_temperature_cell_centre_neighbours(), Corrige_flux_FT_temperature_subresolution::smooth_temperature_cell_centre_neighbours(), Corrige_flux_FT_temperature_subresolution::sort_ijk_intersections_subproblems_indices_fluxes_by_k_layers(), Corrige_flux_FT_temperature_subresolution::store_any_cell_faces_corrected(), test_if_stencil_inclut_bout_interface_liquide(), and test_if_stencil_inclut_bout_interface_vapeur().
field_
const IJK_Field_double* Corrige_flux_FT_base::field_ = nullptr protected
Referenced by Corrige_flux_FT_temperature_conv::calcul_temp_flux_interf_pour_bary_cell(), Corrige_flux_FT_temperature_conv::calcul_temp_flux_interf_pour_bary_face(), Corrige_flux_FT_temperature_conv::corrige_flux_faceIJ(), Corrige_flux_FT_temperature_conv::get_ghost_temp_if_cell_is_diph(), and initialize().
rhocp_l_
double Corrige_flux_FT_base::rhocp_l_ = 0. protected
Referenced by Corrige_flux_FT_temperature_conv::initialize(), Corrige_flux_FT_temperature_conv::remplace_flux_par_somme_rhocpf_Tf_v_Sf(), and set_physical_parameters().
rhocp_v_
double Corrige_flux_FT_base::rhocp_v_ = 0. protected
Referenced by Corrige_flux_FT_temperature_conv::initialize(), Corrige_flux_FT_temperature_conv::remplace_flux_par_somme_rhocpf_Tf_v_Sf(), and set_physical_parameters().
lda_l_
double Corrige_flux_FT_base::lda_l_ = 0. protected
Referenced by Corrige_flux_FT_temperature_conv::calcul_temp_flux_interf_pour_bary_cell(), Corrige_flux_FT_temperature_conv::calcul_temp_flux_interf_pour_bary_face(), Corrige_flux_FT_temperature_conv::extrapolation_amont_1_depuis_l_interface(), Corrige_flux_FT_temperature_conv::initialize(), set_physical_parameters(), and Corrige_flux_FT_temperature_conv::update_temperature_ghost().
lda_v_
double Corrige_flux_FT_base::lda_v_ = 0. protected
Referenced by Corrige_flux_FT_temperature_conv::calcul_temp_flux_interf_pour_bary_cell(), Corrige_flux_FT_temperature_conv::calcul_temp_flux_interf_pour_bary_face(), Corrige_flux_FT_temperature_conv::extrapolation_amont_1_depuis_l_interface(), Corrige_flux_FT_temperature_conv::initialize(), set_physical_parameters(), and Corrige_flux_FT_temperature_conv::update_temperature_ghost().
intersection_ijk_face_
Intersection_Interface_ijk_face* Corrige_flux_FT_base::intersection_ijk_face_ = nullptr protected
Referenced by Corrige_flux_FT_temperature_conv::calcul_temp_flux_interf_pour_bary_face(), initialize(), Corrige_flux_FT_temperature_conv::initialize(), Corrige_flux_FT_temperature_conv::interp_back_to_bary_faces(), and Corrige_flux_FT_temperature_conv::update().
intersection_ijk_cell_
Intersection_Interface_ijk_cell* Corrige_flux_FT_base::intersection_ijk_cell_ = nullptr protected
Referenced by Corrige_flux_FT_temperature_subresolution::associate_indices_and_check_subproblems_consistency(), Corrige_flux_FT_temperature_conv::calcul_temp_flux_interf_pour_bary_cell(), Corrige_flux_FT_temperature_subresolution::clean(), Corrige_flux_FT_temperature_subresolution::complete_thermal_fluxes_face_centre(), Corrige_flux_FT_temperature_subresolution::compute_ijk_pure_faces_indices(), Corrige_flux_FT_temperature_subresolution::compute_temperature_cell_centre(), Corrige_flux_FT_temperature_subresolution::compute_thermal_fluxes_face_centre(), Corrige_flux_FT_temperature_subresolution::compute_thermal_fluxes_face_centre_discrete_integral(), Corrige_flux_FT_temperature_conv::extrapolation_amont_1_depuis_l_interface(), initialize(), Corrige_flux_FT_temperature_conv::initialize(), Corrige_flux_FT_temperature_conv::update(), Corrige_flux_FT_temperature_subresolution::update_intersections(), and Corrige_flux_FT_temperature_conv::update_temperature_ghost().
parcours_
ParcoursIJKDir Corrige_flux_FT_base::parcours_ protected
Referenced by Corrige_flux_FT_temperature_conv::corrige_flux_faceIJ(), Corrige_flux_FT_temperature_conv::extrapolation_amont_1_depuis_l_interface(), Corrige_flux_FT_temperature_conv::interpolation_quick_avec_1_ghost(), Corrige_flux_FT_temperature_conv::multiplie_par_rho_cp_de_la_face_monophasique(), Corrige_flux_FT_temperature_conv::remplace_flux_par_quick_ghost_amont_1(), Corrige_flux_FT_temperature_conv::remplace_flux_par_somme_rhocpf_Tf_v_Sf(), test_if_stencil_inclut_bout_interface_liquide(), and test_if_stencil_inclut_bout_interface_vapeur().