TrioCFD: DG_discretisation Class Reference
DG_discretisation Class Reference
#include <DG_discretisation.h>
Public Member Functions
void discretiser_champ (const Motcle &directive, const Domaine_dis_base &z, Nature_du_champ nature, const Noms &nom, const Noms &unite, int nb_comp, double temps, TRUST_Deriv< Champ_Don_base > &champ) const override
void discretiser_champ (const Motcle &directive, const Domaine_dis_base &z, Nature_du_champ nature, const Noms &nom, const Noms &unite, int nb_comp, double temps, TRUST_Deriv< Champ_Fonc_base > &champ) const override
void discretiser_champ (const Motcle &directive, const Domaine_dis_base &z, Nature_du_champ nature, const Noms &nom, const Noms &unite, int nb_comp, int nb_pas_dt, double temps, TRUST_Deriv< Champ_Inc_base > &champ, const Nom &sous_type=NOM_VIDE) const override
const Type_info * get_info () const override
Public Member Functions inherited from Discret_Thyd
const Type_info * get_info () const override
Public Member Functions inherited from Discret_Thermique
const Type_info * get_info () const override
virtual void discretiser_champ (const Motcle &directive, const Domaine_dis_base &z, Nature_du_champ nature, const Noms &nom, const Noms &unite, int nb_comp, int nb_pas_dt, double temps, TRUST_Deriv< Champ_Inc_base > &champ, const Nom &sous_type=NOM_VIDE) const
const Type_info * get_info () const override
virtual Nom get_name_of_type_for (const Nom &class_operateur, const Nom &type_operteur, const Equation_base &eqn, const TRUST_Ref< Champ_base * > &champ_supp=TRUST_Ref< Champ_base * >()) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Discret_Thyd
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Discret_Thermique
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Discretisation_base
static void creer_champ (TRUST_Deriv< Champ_Don_base > &ch, const Domaine_dis_base &z, const Nom &type, const Nom &nom, const Nom &unite, int nb_comp, int nb_ddl, double temps, const Nom &directive=NOM_VIDE, const Nom &nom_discretisation=NOM_VIDE)
static void creer_champ (TRUST_Deriv< Champ_Fonc_base > &ch, const Domaine_dis_base &z, const Nom &type, const Nom &nom, const Nom &unite, int nb_comp, int nb_ddl, double temps, const Nom &directive=NOM_VIDE, const Nom &nom_discretisation=NOM_VIDE)
static void creer_champ (TRUST_Deriv< Champ_Inc_base > &ch, const Domaine_dis_base &z, const Nom &type, const Nom &nom, const Nom &unite, int nb_comp, int nb_ddl, int nb_pas_dt, double temps, const Nom &directive=NOM_VIDE, const Nom &nom_discretisation=NOM_VIDE)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
DG_discretisation()
DG_discretisation::DG_discretisation ()
~DG_discretisation()
DG_discretisation::~DG_discretisation ()
Member Function Documentation
cree_instance()
Objet_U * DG_discretisation::cree_instance () static
taille_memoire()
unsigned DG_discretisation::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int DG_discretisation::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * DG_discretisation::info () static
get_info()
const Type_info * DG_discretisation::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
DG_discretisation & DG_discretisation::self_cast (Objet_U & r) static
self_cast() [2/2]
const DG_discretisation & DG_discretisation::self_cast (const Objet_U & r) static
printOn()
Sortie & DG_discretisation::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
readOn()
Entree & DG_discretisation::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
discretiser_champ() [1/3]
void DG_discretisation::discretiser_champ (const Motcle & directive, const Domaine_dis_base & dom_dis, Nature_du_champ nature, const Noms & noms, const Noms & unites, int nb_comp, int nb_pas_dt, double temps, TRUST_Deriv< Champ_Inc_base > & champ, const Nom & sous_type = NOM_VIDE) const override virtual
Discretisation of a field for DG formulation.
TODO, refactor this after stokes. And decide if we want to put this on Option_DG or not
La directive est un Motcle comme "vitesse", "pression", "temperature", "champ_elem" (cree un champ de type P0), ... Cette methode determine le type du champ a creer en fonction du type d'element et de la directive de discretisation. Elle determine ensuite le nombre de ddl et fixe l'ensemble des parametres du champ (type, nb_compo, nb_ddl, nb_pas_dt, nom(s), unite(s) et nature du champ) et associe la Domaine_dis au champ. Voir le code pour avoir la correspondance entre les directives et le type de champ cree.
Reimplemented from Discretisation_base.
References Discretisation_base::creer_champ(), Nom::debute_par(), Discretisation_base::DEMANDE_DESCRIPTION, Discretisation_base::discretiser_champ(), Field_base::fixer_nature_du_champ(), Option_DG::Get_order_for(), Option_DG::Nb_col_from_order(), Domaine_dis_base::nb_elem(), Discretisation_base::NOM_VIDE, Objet_U::que_suis_je(), Motcles::search(), and Discretisation_base::verifie_sous_type().
Referenced by distance_paroi_globale().
discretiser_champ() [2/3]
void DG_discretisation::discretiser_champ (const Motcle & directive, const Domaine_dis_base & z, Nature_du_champ nature, const Noms & noms, const Noms & unites, int nb_comp, double temps, TRUST_Deriv< Champ_Fonc_base > & champ) const override virtual
Idem que DG_discretisation::discretiser_champ(.
.. , Champ_Inc)
Reimplemented from Discretisation_base.
discretiser_champ() [3/3]
void DG_discretisation::discretiser_champ (const Motcle & directive, const Domaine_dis_base & z, Nature_du_champ nature, const Noms & noms, const Noms & unites, int nb_comp, double temps, TRUST_Deriv< Champ_Don_base > & champ) const override virtual
Idem que DG_discretisation::discretiser_champ(.
.. , Champ_Inc)
Reimplemented from Discretisation_base.
domaine_cl_dis_type()
Nom DG_discretisation::domaine_cl_dis_type () const inline override virtual
Implements Discretisation_base.
distance_paroi()
void DG_discretisation::distance_paroi (const Schema_Temps_base & sch, Domaine_dis_base & z, TRUST_Deriv< Champ_Fonc_base > & ch) const
distance_paroi_globale()
void DG_discretisation::distance_paroi_globale (const Schema_Temps_base & sch, Domaine_dis_base & z, TRUST_Deriv< Champ_Fonc_base > & ch) const override virtual
Reimplemented from Discret_Thyd.
References discretiser_champ().
grad_u()
void DG_discretisation::grad_u (const Domaine_dis_base & z, const Domaine_Cl_dis_base & zcl, const Champ_Inc_base & ch_vitesse, TRUST_Deriv< Champ_Fonc_base > & ch) const override virtual
Reimplemented from Discret_Thyd.
codage_du_calcul_du_residu()
type_calcul_du_residu DG_discretisation::codage_du_calcul_du_residu () const inline override virtual
Reimplemented from Discretisation_base.
References Discretisation_base::VIA_CONTRIBUER_AU_SECOND_MEMBRE.
get_name_of_type_for()
Nom DG_discretisation::get_name_of_type_for (const Nom & class_operateur, const Nom & type_operateur, const Equation_base & eqn, const TRUST_Ref< Champ_base * > & champ_sup) const override virtual
Old copy paste, give the name to fields. Name used to allocate size of matrixes in discretiser.
Reimplemented from Discretisation_base.
References Nom::debute_par(), Discretisation_base::get_name_of_type_for(), Equation_base::inconnue(), Objet_U::que_suis_je(), and Nom::suffix().
is_dg()
bool DG_discretisation::is_dg () const inline override virtual
Reimplemented from Discretisation_base.
is_polymac_family()
bool DG_discretisation::is_polymac_family () const inline override virtual
Reimplemented from Discretisation_base.
Member Data Documentation
info_obj
const Type_info DG_discretisation::info_obj static