TrioCFD: Solv_rocALUTION Class Reference
Solv_rocALUTION Class Reference
#include <Solv_rocALUTION.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from SolveurSys_base
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from SolveurSys_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Solv_rocALUTION() [1/2]
Solv_rocALUTION::Solv_rocALUTION ()
Solv_rocALUTION() [2/2]
Solv_rocALUTION::Solv_rocALUTION (const Solv_rocALUTION & org)
References SolveurSys_base::get_chaine_lue(), and readOn().
~Solv_rocALUTION()
Solv_rocALUTION::~Solv_rocALUTION () override
Member Function Documentation
cree_instance()
Objet_U * Solv_rocALUTION::cree_instance () static
taille_memoire()
unsigned Solv_rocALUTION::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Solv_rocALUTION::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Solv_rocALUTION::info () static
get_info()
const Type_info * Solv_rocALUTION::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Solv_Externe.
self_cast() [1/2]
Solv_rocALUTION & Solv_rocALUTION::self_cast (Objet_U & r) static
self_cast() [2/2]
const Solv_rocALUTION & Solv_rocALUTION::self_cast (const Objet_U & r) static
printOn()
Sortie & Solv_rocALUTION::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Solv_Externe.
References SolveurSys_base::chaine_lue_.
readOn()
Entree & Solv_rocALUTION::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Solv_Externe.
References create_solver().
Referenced by Solv_rocALUTION().
solveur_direct()
int Solv_rocALUTION::solveur_direct () const inline override virtual
Implements SolveurSys_base.
resoudre_systeme() [1/2]
int Solv_rocALUTION::resoudre_systeme (const Matrice_Base & a, const DoubleVect & b, DoubleVect & x, int niter_max) inline override virtual
Reimplemented from SolveurSys_base.
References resoudre_systeme().
Referenced by resoudre_systeme().
resoudre_systeme() [2/2]
int Solv_rocALUTION::resoudre_systeme (const Matrice_Base & a, const DoubleVect & b, DoubleVect & x) override virtual
Implements SolveurSys_base.
References TRUSTArray< _TYPE_, _SIZE_ >::addr(), Statistiques::begin_count(), Solv_Externe::construit_matrice_morse_intermediaire(), Solv_Externe::construit_renum(), PE_Groups::current_group(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), TRUSTVect< _TYPE_, _SIZE_ >::ecrit(), Statistiques::end_count(), TRUSTArray< _TYPE_, _SIZE_ >::ensureDataOnHost(), Process::exit(), SolveurSys_base::fixer_nouvelle_matrice(), Matrice_Morse::imprimer_formatte(), TRUSTArray< _TYPE_, _SIZE_ >::isDataOnDevice(), Process::Journal(), Solv_Externe::lhs_, SolveurSys_base::limpr(), TRUSTVect< _TYPE_, _SIZE_ >::mp_norme_vect(), Matrice_Base::multvect(), Solv_Externe::nb_rows_, Solv_Externe::nb_rows_tot_, SolveurSys_base::nouvelle_matrice(), Solv_Externe::renum_, TRUSTArray< _TYPE_, _SIZE_ >::resize(), Solv_Externe::rhs_, and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
create_solver()
void Solv_rocALUTION::create_solver (Entree & entree)
References Process::exit(), SolveurSys_base::fixer_limpr(), SolveurSys_base::get_chaine_lue(), EChaine::init(), and SolveurSys_base::lecture().
Referenced by readOn().
Member Data Documentation
info_obj
const Type_info Solv_rocALUTION::info_obj static