TrioCFD: Modele_turbulence_scal_null Class Reference
Modele_turbulence_scal_null Class Reference
#include <Modele_turbulence_scal_null.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Modele_turbulence_scal_base
virtual void associer (const Domaine_dis_base &, const Domaine_Cl_dis_base &)
void associer_eqn (const Equation_base &)
const Type_info * get_info () const override
virtual void imprimer (Sortie &) const
int limpr_nusselt (double, double, double, double) const
int lire_motcle_non_standard (const Motcle &, Entree &) override
Turbulence_paroi_scal_base & loi_paroi ()
const Turbulence_paroi_scal_base & loi_paroi () const
int loi_paroi_non_nulle () const
virtual int preparer_calcul ()
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Modele_turbulence_scal_null()
Modele_turbulence_scal_null::Modele_turbulence_scal_null ()
~Modele_turbulence_scal_null()
Modele_turbulence_scal_null::~Modele_turbulence_scal_null ()
Member Function Documentation
cree_instance()
Objet_U * Modele_turbulence_scal_null::cree_instance () static
taille_memoire()
unsigned Modele_turbulence_scal_null::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Modele_turbulence_scal_null::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Modele_turbulence_scal_null::info () static
get_info()
const Type_info * Modele_turbulence_scal_null::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Modele_turbulence_scal_base.
self_cast() [1/2]
Modele_turbulence_scal_null & Modele_turbulence_scal_null::self_cast (Objet_U & r) static
self_cast() [2/2]
const Modele_turbulence_scal_null & Modele_turbulence_scal_null::self_cast (const Objet_U & r) static
printOn()
Sortie & Modele_turbulence_scal_null::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Modele_turbulence_scal_base.
References Objet_U::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Modele_turbulence_scal_null::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Modele_turbulence_scal_base.
References Turbulence_paroi_scal_base::associer(), Turbulence_paroi_scal_base::associer_modele(), Equation_base::domaine_Cl_dis(), Equation_base::domaine_dis(), Probleme_base::equation(), Process::exit(), Equation_base::get_modele(), Param::lire_avec_accolades_depuis(), Modele_turbulence_scal_base::loipar_, Modele_turbulence_scal_base::mon_equation_, Objet_U::que_suis_je(), Objet_U_ptr::typer(), and TRUST_Ref_Objet_U::valeur().
mettre_a_jour()
void Modele_turbulence_scal_null::mettre_a_jour (double) inline override virtual
Implements Modele_turbulence_scal_base.
Member Data Documentation
info_obj
const Type_info Modele_turbulence_scal_null::info_obj static