TrioCFD: Modele_turbulence_hyd_LES_base Class Reference
Modele_turbulence_hyd_LES_base Class Reference abstract
#include <Modele_turbulence_hyd_LES_base.h>
Public Member Functions
const Type_info * get_info () const override
void imprimer (Sortie &is) const override
int preparer_calcul () override
int reprendre (Entree &is) override
const Type_info * get_info () const override
void imprimer (Sortie &) const override
int reprendre (Entree &is) override
Public Member Functions inherited from Modele_turbulence_hyd_base
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Type_info * get_info () const override
virtual void imprimer (Sortie &) const
void lire_distance_paroi ()
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual int preparer_calcul ()
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
equations de Navier-Stokes.
See also
Modele_turbulence_hyd_0_eq_base
Constructor & Destructor Documentation
~Modele_turbulence_hyd_LES_base()
Modele_turbulence_hyd_LES_base::~Modele_turbulence_hyd_LES_base () override
Modele_turbulence_hyd_LES_base()
Modele_turbulence_hyd_LES_base::Modele_turbulence_hyd_LES_base ()
References methode_.
Member Function Documentation
info()
const Type_info * Modele_turbulence_hyd_LES_base::info () static
get_info()
const Type_info * Modele_turbulence_hyd_LES_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Modele_turbulence_hyd_0_eq_base.
Reimplemented in Modele_turbulence_hyd_LES_axi_VDF, Modele_turbulence_hyd_LES_DSGS_VDF, Modele_turbulence_hyd_LES_selectif_mod_VDF, Modele_turbulence_hyd_LES_selectif_VDF, Modele_turbulence_hyd_LES_SMAGO_DYN_VDF, Modele_turbulence_hyd_LES_VDF, Modele_turbulence_hyd_LES_1elt_selectif_mod_VEF, Modele_turbulence_hyd_LES_1elt_VEF, Modele_turbulence_hyd_LES_Fst_sel_VEF, Modele_turbulence_hyd_LES_Fst_VEF, Modele_turbulence_hyd_LES_Smago_filtre_VEF, Modele_turbulence_hyd_LES_VEF, Modele_turbulence_hyd_LES_Smago_VDF, Modele_turbulence_hyd_LES_VDF_base, Modele_turbulence_hyd_LES_Wale_VDF, Modele_turbulence_hyd_LES_Smago_VEF, Modele_turbulence_hyd_LES_VEF_base, and Modele_turbulence_hyd_LES_Wale_VEF.
self_cast() [1/2]
Modele_turbulence_hyd_LES_base & Modele_turbulence_hyd_LES_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Modele_turbulence_hyd_LES_base & Modele_turbulence_hyd_LES_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Modele_turbulence_hyd_LES_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Modele_turbulence_hyd_0_eq_base.
Reimplemented in Modele_turbulence_hyd_LES_axi_VDF, Modele_turbulence_hyd_LES_DSGS_VDF, Modele_turbulence_hyd_LES_selectif_mod_VDF, Modele_turbulence_hyd_LES_selectif_VDF, Modele_turbulence_hyd_LES_SMAGO_DYN_VDF, Modele_turbulence_hyd_LES_VDF, Modele_turbulence_hyd_LES_1elt_selectif_mod_VEF, Modele_turbulence_hyd_LES_1elt_VEF, Modele_turbulence_hyd_LES_Fst_sel_VEF, Modele_turbulence_hyd_LES_Fst_VEF, Modele_turbulence_hyd_LES_Smago_filtre_VEF, Modele_turbulence_hyd_LES_VEF, Modele_turbulence_hyd_LES_Smago_VDF, Modele_turbulence_hyd_LES_VDF_base, Modele_turbulence_hyd_LES_Wale_VDF, Modele_turbulence_hyd_LES_Smago_VEF, Modele_turbulence_hyd_LES_VEF_base, and Modele_turbulence_hyd_LES_Wale_VEF.
References Modele_turbulence_hyd_0_eq_base::printOn().
readOn()
Entree & Modele_turbulence_hyd_LES_base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Modele_turbulence_hyd_0_eq_base.
Reimplemented in Modele_turbulence_hyd_LES_axi_VDF, Modele_turbulence_hyd_LES_DSGS_VDF, Modele_turbulence_hyd_LES_selectif_mod_VDF, Modele_turbulence_hyd_LES_selectif_VDF, Modele_turbulence_hyd_LES_SMAGO_DYN_VDF, Modele_turbulence_hyd_LES_VDF, Modele_turbulence_hyd_LES_1elt_selectif_mod_VEF, Modele_turbulence_hyd_LES_1elt_VEF, Modele_turbulence_hyd_LES_Fst_sel_VEF, Modele_turbulence_hyd_LES_Fst_VEF, Modele_turbulence_hyd_LES_Smago_filtre_VEF, Modele_turbulence_hyd_LES_VEF, Modele_turbulence_hyd_LES_Smago_VDF, Modele_turbulence_hyd_LES_VDF_base, Modele_turbulence_hyd_LES_Wale_VDF, Modele_turbulence_hyd_LES_Smago_VEF, Modele_turbulence_hyd_LES_VEF_base, and Modele_turbulence_hyd_LES_Wale_VEF.
References Modele_turbulence_hyd_0_eq_base::readOn().
Referenced by Modele_turbulence_hyd_LES_VDF_base::readOn(), and Modele_turbulence_hyd_LES_VEF_base::readOn().
set_param()
void Modele_turbulence_hyd_LES_base::set_param (Param & param) override virtual
Reimplemented from Modele_turbulence_hyd_0_eq_base.
Reimplemented in Modele_turbulence_hyd_LES_selectif_mod_VDF, Modele_turbulence_hyd_LES_SMAGO_DYN_VDF, Modele_turbulence_hyd_LES_VDF, Modele_turbulence_hyd_LES_Smago_VDF, Modele_turbulence_hyd_LES_Wale_VDF, Modele_turbulence_hyd_LES_Smago_VEF, and Modele_turbulence_hyd_LES_Wale_VEF.
References Param::ajouter(), methode_, and Modele_turbulence_hyd_base::set_param().
Referenced by Modele_turbulence_hyd_LES_VDF::set_param(), Modele_turbulence_hyd_LES_Smago_VDF::set_param(), Modele_turbulence_hyd_LES_Wale_VDF::set_param(), Modele_turbulence_hyd_LES_Smago_VEF::set_param(), and Modele_turbulence_hyd_LES_Wale_VEF::set_param().
verifie_loi_paroi_diphasique()
void Modele_turbulence_hyd_LES_base::verifie_loi_paroi_diphasique ()
References Turbulence_paroi_base::associer(), Turbulence_paroi_base::associer_modele(), Equation_base::discretisation(), Modele_turbulence_hyd_base::equation(), Process::exit(), Modele_turbulence_hyd_base::loipar_, Equation_base::milieu(), Objet_U::que_suis_je(), and Objet_U_ptr::typer().
Referenced by completer().
preparer_calcul()
int Modele_turbulence_hyd_LES_base::preparer_calcul () override virtual
Prepare le calcul.
Initialise la loi de paroi. Remplit le champ wall_length en cas de post traitemetn de la distance_paroi
Returns
(int) code de retour de Turbulence_paroi::init_lois_paroi()
Reimplemented from Modele_turbulence_hyd_base.
Reimplemented in Modele_turbulence_hyd_LES_SMAGO_DYN_VDF.
References calculer_longueurs_caracteristiques(), methode_, Modele_turbulence_hyd_0_eq_base::mettre_a_jour(), and Modele_turbulence_hyd_base::preparer_calcul().
Referenced by Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::preparer_calcul().
completer()
void Modele_turbulence_hyd_LES_base::completer () override virtual
Reimplemented from Modele_turbulence_hyd_0_eq_base.
References verifie_loi_paroi_diphasique().
calculer_longueurs_caracteristiques()
virtual void Modele_turbulence_hyd_LES_base::calculer_longueurs_caracteristiques () pure virtual
Implemented in Modele_turbulence_hyd_LES_axi_VDF, Modele_turbulence_hyd_LES_VDF_base, and Modele_turbulence_hyd_LES_VEF_base.
Referenced by preparer_calcul().
calculer_energie_cinetique_turb()
void Modele_turbulence_hyd_LES_base::calculer_energie_cinetique_turb () override virtual
Implements Modele_turbulence_hyd_0_eq_base.
Reimplemented in Modele_turbulence_hyd_LES_SMAGO_DYN_VDF, and Modele_turbulence_hyd_LES_VDF.
References Champ_base::changer_temps(), Modele_turbulence_hyd_0_eq_base::energie_cinetique_turb_, Process::exit(), l_, Modele_turbulence_hyd_base::la_viscosite_turbulente_, Modele_turbulence_hyd_base::mon_equation_, TRUSTVect< _TYPE_, _SIZE_ >::size(), Champ_Don_base::valeurs(), TRUSTArray< _TYPE_, _SIZE_ >::view_ro(), TRUSTTab< _TYPE_, _SIZE_ >::view_ro(), and TRUSTArray< _TYPE_, _SIZE_ >::view_rw().
reprendre()
int Modele_turbulence_hyd_LES_base::reprendre (Entree &) inline override virtual
Reprise d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree&) flot d'entree a utiliser pour la reprise
Returns
(int) code de retour
Reimplemented from Modele_turbulence_hyd_0_eq_base.
References Modele_turbulence_hyd_base::reprendre().
imprimer()
void Modele_turbulence_hyd_LES_base::imprimer (Sortie & os) const inline override virtual
Effectue l'impression si cela est necessaire.
Returns
renvoie toujours 1
Reimplemented from Modele_turbulence_hyd_0_eq_base.
References Modele_turbulence_hyd_base::imprimer().
Member Data Documentation
info_obj
const Type_info Modele_turbulence_hyd_LES_base::info_obj static
l_
DoubleVect Modele_turbulence_hyd_LES_base::l_ protected
Referenced by calculer_energie_cinetique_turb(), Modele_turbulence_hyd_LES_VDF::calculer_fonction_structure(), Modele_turbulence_hyd_LES_1elt_VEF::calculer_fonction_structure(), Modele_turbulence_hyd_LES_VDF_base::calculer_longueurs_caracteristiques(), Modele_turbulence_hyd_LES_VEF_base::calculer_longueurs_caracteristiques(), Modele_turbulence_hyd_LES_DSGS_VDF::calculer_Mij(), Modele_turbulence_hyd_LES_Fst_VEF::calculer_racine(), Modele_turbulence_hyd_LES_Smago_filtre_VEF::calculer_S_barre(), Modele_turbulence_hyd_LES_DSGS_VDF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_VDF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_1elt_VEF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_Fst_VEF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_Smago_VDF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_Wale_VDF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_Smago_VEF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_Wale_VEF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_1elt_selectif_mod_VEF::cutoff(), and Modele_turbulence_hyd_LES_Fst_sel_VEF::cutoff().
methode_
Motcle Modele_turbulence_hyd_LES_base::methode_ protected
Referenced by Modele_turbulence_hyd_LES_VDF_base::calculer_longueurs_caracteristiques(), Modele_turbulence_hyd_LES_VEF_base::calculer_longueurs_caracteristiques(), Modele_turbulence_hyd_LES_base(), preparer_calcul(), and set_param().
CSM1
constexpr double Modele_turbulence_hyd_LES_base::CSM1 = 0.063 static constexpr protected
Referenced by Modele_turbulence_hyd_LES_axi_VDF::calculer_viscosite_turbulente(), and Modele_turbulence_hyd_LES_VEF::calculer_viscosite_turbulente().
CSMS1
constexpr double Modele_turbulence_hyd_LES_base::CSMS1 = 0.112 static protected
Referenced by Modele_turbulence_hyd_LES_selectif_VDF::Modele_turbulence_hyd_LES_selectif_VDF().
CSM2
constexpr double Modele_turbulence_hyd_LES_base::CSM2 = 0.37 static constexpr protected