TrioCFD: Post_Processing_Hydrodynamic_Forces_Stokes Class Reference
Post_Processing_Hydrodynamic_Forces_Stokes Class Reference
#include <Post_Processing_Hydrodynamic_Forces_Stokes.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Post_Processing_Hydrodynamic_Forces
const Type_info * get_info () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
~Post_Processing_Hydrodynamic_Forces_Stokes()
Post_Processing_Hydrodynamic_Forces_Stokes::~Post_Processing_Hydrodynamic_Forces_Stokes ()
Post_Processing_Hydrodynamic_Forces_Stokes()
Post_Processing_Hydrodynamic_Forces_Stokes::Post_Processing_Hydrodynamic_Forces_Stokes ()
Member Function Documentation
cree_instance()
Objet_U * Post_Processing_Hydrodynamic_Forces_Stokes::cree_instance () static
taille_memoire()
unsigned Post_Processing_Hydrodynamic_Forces_Stokes::taille_memoire () const override virtual
Reimplemented from Post_Processing_Hydrodynamic_Forces.
duplique()
int Post_Processing_Hydrodynamic_Forces_Stokes::duplique () const override virtual
Reimplemented from Post_Processing_Hydrodynamic_Forces.
info()
const Type_info * Post_Processing_Hydrodynamic_Forces_Stokes::info () static
get_info()
const Type_info * Post_Processing_Hydrodynamic_Forces_Stokes::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Post_Processing_Hydrodynamic_Forces.
self_cast() [1/2]
Post_Processing_Hydrodynamic_Forces_Stokes & Post_Processing_Hydrodynamic_Forces_Stokes::self_cast (Objet_U & r) static
self_cast() [2/2]
const Post_Processing_Hydrodynamic_Forces_Stokes & Post_Processing_Hydrodynamic_Forces_Stokes::self_cast (const Objet_U & r) static
printOn()
Sortie & Post_Processing_Hydrodynamic_Forces_Stokes::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Post_Processing_Hydrodynamic_Forces.
References Process::exit().
readOn()
Entree & Post_Processing_Hydrodynamic_Forces_Stokes::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Post_Processing_Hydrodynamic_Forces.
References Process::exit().
compute_hydrodynamic_forces()
void Post_Processing_Hydrodynamic_Forces_Stokes::compute_hydrodynamic_forces () override virtual
Reimplemented from Post_Processing_Hydrodynamic_Forces.
References compute_friction_force_complet_tensor(), compute_friction_force_projected_tensor(), compute_neighbors_coordinates_fluid_fa7(), compute_pressure_force_trilinear_linear(), compute_vinf_Stokes(), fill_Stokes_pressure_field(), fill_Stokes_velocity_field(), Post_Processing_Hydrodynamic_Forces::flag_force_computation_, Maillage_FT_Disc::get_gravity_center_fa7(), Navier_Stokes_FT_Disc::get_particles_eulerian_id_number(), Maillage_FT_Disc::get_update_normale_facettes(), Maillage_FT_Disc::get_update_surface_facettes(), Transport_Interfaces_FT_Disc::maillage_interface_pour_post(), Post_Processing_Hydrodynamic_Forces::method_friction_force_computation_, Maillage_FT_Disc::nb_facettes(), Post_Processing_Hydrodynamic_Forces::ptr_eq_ns_, Post_Processing_Hydrodynamic_Forces::ptr_eq_transport_, Post_Processing_Hydrodynamic_Forces::raise_the_flag(), resize_and_init_tables(), Post_Processing_Hydrodynamic_Forces::resize_coord_neighbor_fluid_fa7(), resize_data_fa7(), Post_Processing_Hydrodynamic_Forces::total_friction_force_, Post_Processing_Hydrodynamic_Forces::total_pressure_force_, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Transport_Interfaces_FT_Disc::get_champ_post_FT(), and Transport_Interfaces_FT_Disc::mettre_a_jour().
set_param()
void Post_Processing_Hydrodynamic_Forces_Stokes::set_param (const Post_Processing_Hydrodynamic_Forces & post_process_hydro_forces_)
References Post_Processing_Hydrodynamic_Forces::get_interpolation_distance_gradU_P1(), Post_Processing_Hydrodynamic_Forces::get_interpolation_distance_gradU_P2(), Post_Processing_Hydrodynamic_Forces::get_interpolation_distance_pressure_P1(), Post_Processing_Hydrodynamic_Forces::get_interpolation_distance_pressure_P2(), Post_Processing_Hydrodynamic_Forces::get_is_compute_forces(), Post_Processing_Hydrodynamic_Forces::get_is_compute_forces_Stokes_th(), Post_Processing_Hydrodynamic_Forces::get_is_post_process_friction_force_fa7(), Post_Processing_Hydrodynamic_Forces::get_is_post_process_pressure_fa7(), Post_Processing_Hydrodynamic_Forces::get_is_post_process_pressure_force_fa7(), Post_Processing_Hydrodynamic_Forces::get_is_post_process_stress_tensor_fa7(), Post_Processing_Hydrodynamic_Forces::get_location_stress_tensor(), Post_Processing_Hydrodynamic_Forces::get_method_pressure_force_computation(), Post_Processing_Hydrodynamic_Forces::interpolation_distance_gradU_P1_, Post_Processing_Hydrodynamic_Forces::interpolation_distance_gradU_P2_, Post_Processing_Hydrodynamic_Forces::interpolation_distance_pressure_P1_, Post_Processing_Hydrodynamic_Forces::interpolation_distance_pressure_P2_, Post_Processing_Hydrodynamic_Forces::is_compute_forces_, Post_Processing_Hydrodynamic_Forces::is_compute_stokes_theoretical_forces_, Post_Processing_Hydrodynamic_Forces::is_post_process_friction_force_fa7_, Post_Processing_Hydrodynamic_Forces::is_post_process_pressure_fa7_, Post_Processing_Hydrodynamic_Forces::is_post_process_pressure_force_fa7_, Post_Processing_Hydrodynamic_Forces::is_post_process_stress_tensor_fa7_, Post_Processing_Hydrodynamic_Forces::location_stress_tensor_, and Post_Processing_Hydrodynamic_Forces::method_pressure_force_computation_.
Referenced by Transport_Interfaces_FT_Disc::preparer_calcul().
get_pressure_force_Stokes_th()
const DoubleTab & Post_Processing_Hydrodynamic_Forces_Stokes::get_pressure_force_Stokes_th () const inline
get_friction_force_Stokes_th()
const DoubleTab & Post_Processing_Hydrodynamic_Forces_Stokes::get_friction_force_Stokes_th () const inline
get_pressure_force_Stokes_th_fa7()
const DoubleTab & Post_Processing_Hydrodynamic_Forces_Stokes::get_pressure_force_Stokes_th_fa7 () const inline
get_friction_force_Stokes_th_fa7()
const DoubleTab & Post_Processing_Hydrodynamic_Forces_Stokes::get_friction_force_Stokes_th_fa7 () const inline
resize_and_init_tables()
void Post_Processing_Hydrodynamic_Forces_Stokes::resize_and_init_tables (int nb_particles_tot) override virtual
Reimplemented from Post_Processing_Hydrodynamic_Forces.
References Objet_U::dimension, TRUSTTab< _TYPE_, _SIZE_ >::resize(), Post_Processing_Hydrodynamic_Forces::total_friction_force_, and Post_Processing_Hydrodynamic_Forces::total_pressure_force_.
Referenced by compute_hydrodynamic_forces(), and Transport_Interfaces_FT_Disc::preparer_calcul().
get_sigma_xx_fa7_Stokes_th()
const DoubleTab & Post_Processing_Hydrodynamic_Forces_Stokes::get_sigma_xx_fa7_Stokes_th () const inline
get_sigma_xy_fa7_Stokes_th()
const DoubleTab & Post_Processing_Hydrodynamic_Forces_Stokes::get_sigma_xy_fa7_Stokes_th () const inline
get_sigma_xz_fa7_Stokes_th()
const DoubleTab & Post_Processing_Hydrodynamic_Forces_Stokes::get_sigma_xz_fa7_Stokes_th () const inline
get_sigma_yy_fa7_Stokes_th()
const DoubleTab & Post_Processing_Hydrodynamic_Forces_Stokes::get_sigma_yy_fa7_Stokes_th () const inline
get_sigma_yz_fa7_Stokes_th()
const DoubleTab & Post_Processing_Hydrodynamic_Forces_Stokes::get_sigma_yz_fa7_Stokes_th () const inline
get_sigma_zz_fa7_Stokes_th()
const DoubleTab & Post_Processing_Hydrodynamic_Forces_Stokes::get_sigma_zz_fa7_Stokes_th () const inline
get_dUdx_P1_Stokes_th()
const DoubleTab & Post_Processing_Hydrodynamic_Forces_Stokes::get_dUdx_P1_Stokes_th () inline
get_dUdz_P1_Stokes_th()
const DoubleTab & Post_Processing_Hydrodynamic_Forces_Stokes::get_dUdz_P1_Stokes_th () inline
get_dVdz_P1_Stokes_th()
const DoubleTab & Post_Processing_Hydrodynamic_Forces_Stokes::get_dVdz_P1_Stokes_th () inline
get_dWdx_P1_Stokes_th()
const DoubleTab & Post_Processing_Hydrodynamic_Forces_Stokes::get_dWdx_P1_Stokes_th () inline
get_dWdy_P1_Stokes_th()
const DoubleTab & Post_Processing_Hydrodynamic_Forces_Stokes::get_dWdy_P1_Stokes_th () inline
get_dWdz_P1_Stokes_th()
const DoubleTab & Post_Processing_Hydrodynamic_Forces_Stokes::get_dWdz_P1_Stokes_th () inline
get_dUdx_P2_Stokes_th()
const DoubleTab & Post_Processing_Hydrodynamic_Forces_Stokes::get_dUdx_P2_Stokes_th () inline
get_dUdz_P2_Stokes_th()
const DoubleTab & Post_Processing_Hydrodynamic_Forces_Stokes::get_dUdz_P2_Stokes_th () inline
get_dVdz_P2_Stokes_th()
const DoubleTab & Post_Processing_Hydrodynamic_Forces_Stokes::get_dVdz_P2_Stokes_th () inline
get_dWdx_P2_Stokes_th()
const DoubleTab & Post_Processing_Hydrodynamic_Forces_Stokes::get_dWdx_P2_Stokes_th () inline
get_dWdy_P2_Stokes_th()
const DoubleTab & Post_Processing_Hydrodynamic_Forces_Stokes::get_dWdy_P2_Stokes_th () inline
get_dWdz_P2_Stokes_th()
const DoubleTab & Post_Processing_Hydrodynamic_Forces_Stokes::get_dWdz_P2_Stokes_th () inline
get_U_P1_Stokes_th()
const DoubleTab & Post_Processing_Hydrodynamic_Forces_Stokes::get_U_P1_Stokes_th () const inline
get_U_P2_Stokes_th()
const DoubleTab & Post_Processing_Hydrodynamic_Forces_Stokes::get_U_P2_Stokes_th () const inline
get_pressure_fa7_Stokes_th()
const DoubleVect & Post_Processing_Hydrodynamic_Forces_Stokes::get_pressure_fa7_Stokes_th () const inline
Referenced by Transport_Interfaces_FT_Disc::fill_ftab_Stokes_pressure_th().
resize_data_fa7()
void Post_Processing_Hydrodynamic_Forces_Stokes::resize_data_fa7 (int nb_fa7) override protected virtual
Reimplemented from Post_Processing_Hydrodynamic_Forces.
References Objet_U::dimension, Post_Processing_Hydrodynamic_Forces::friction_force_fa7_, Post_Processing_Hydrodynamic_Forces::is_post_process_pressure_fa7_, Post_Processing_Hydrodynamic_Forces::is_post_process_stress_tensor_fa7_, Post_Processing_Hydrodynamic_Forces::pressure_fa7_, Post_Processing_Hydrodynamic_Forces::pressure_force_fa7_, TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), resize_gradU_P1(), resize_gradU_P2(), resize_sigma(), Post_Processing_Hydrodynamic_Forces::U_P1_, and Post_Processing_Hydrodynamic_Forces::U_P2_.
Referenced by compute_hydrodynamic_forces().
resize_sigma()
void Post_Processing_Hydrodynamic_Forces_Stokes::resize_sigma (int nb_fa7) override protected virtual
Reimplemented from Post_Processing_Hydrodynamic_Forces.
References TRUSTTab< _TYPE_, _SIZE_ >::resize(), Post_Processing_Hydrodynamic_Forces::sigma_xx_fa7_, Post_Processing_Hydrodynamic_Forces::sigma_xy_fa7_, Post_Processing_Hydrodynamic_Forces::sigma_xz_fa7_, Post_Processing_Hydrodynamic_Forces::sigma_yx_fa7_, Post_Processing_Hydrodynamic_Forces::sigma_yy_fa7_, Post_Processing_Hydrodynamic_Forces::sigma_yz_fa7_, Post_Processing_Hydrodynamic_Forces::sigma_zx_fa7_, Post_Processing_Hydrodynamic_Forces::sigma_zy_fa7_, and Post_Processing_Hydrodynamic_Forces::sigma_zz_fa7_.
Referenced by resize_data_fa7().
resize_gradU_P1()
void Post_Processing_Hydrodynamic_Forces_Stokes::resize_gradU_P1 (int nb_fa7) override protected virtual
Reimplemented from Post_Processing_Hydrodynamic_Forces.
References Post_Processing_Hydrodynamic_Forces::dUdx_P1_, Post_Processing_Hydrodynamic_Forces::dUdy_P1_, Post_Processing_Hydrodynamic_Forces::dUdz_P1_, Post_Processing_Hydrodynamic_Forces::dVdx_P1_, Post_Processing_Hydrodynamic_Forces::dVdy_P1_, Post_Processing_Hydrodynamic_Forces::dVdz_P1_, Post_Processing_Hydrodynamic_Forces::dWdx_P1_, Post_Processing_Hydrodynamic_Forces::dWdy_P1_, Post_Processing_Hydrodynamic_Forces::dWdz_P1_, and TRUSTTab< _TYPE_, _SIZE_ >::resize().
Referenced by resize_data_fa7().
resize_gradU_P2()
void Post_Processing_Hydrodynamic_Forces_Stokes::resize_gradU_P2 (int nb_fa7) override protected virtual
Reimplemented from Post_Processing_Hydrodynamic_Forces.
References Post_Processing_Hydrodynamic_Forces::dUdx_P2_, Post_Processing_Hydrodynamic_Forces::dUdy_P2_, Post_Processing_Hydrodynamic_Forces::dUdz_P2_, Post_Processing_Hydrodynamic_Forces::dVdx_P2_, Post_Processing_Hydrodynamic_Forces::dVdy_P2_, Post_Processing_Hydrodynamic_Forces::dVdz_P2_, Post_Processing_Hydrodynamic_Forces::dWdx_P2_, Post_Processing_Hydrodynamic_Forces::dWdy_P2_, Post_Processing_Hydrodynamic_Forces::dWdz_P2_, and TRUSTTab< _TYPE_, _SIZE_ >::resize().
Referenced by resize_data_fa7().
fill_Stokes_velocity_field()
void Post_Processing_Hydrodynamic_Forces_Stokes::fill_Stokes_velocity_field () protected
References compute_Stokes_Ux_fluid(), compute_Stokes_Uy_fluid(), compute_Stokes_Uz_fluid(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Equation_base::domaine_dis(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Navier_Stokes_FT_Disc::fluide_diphasique(), Fluide_Diphasique::fluide_phase(), Solid_Particle_base::get_equivalent_radius(), Fluide_Diphasique::get_id_fluid_phase(), Navier_Stokes_FT_Disc::get_set_velocity_field_Stokes_th(), get_vinf_Stokes(), Domaine_VDF::orientation(), Post_Processing_Hydrodynamic_Forces::ptr_eq_ns_, TRUST_Ref< _CLASSE_ >::valeur(), and Domaine_VF::xv().
Referenced by compute_hydrodynamic_forces().
fill_Stokes_pressure_field()
void Post_Processing_Hydrodynamic_Forces_Stokes::fill_Stokes_pressure_field () protected
References TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Equation_base::domaine_dis(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Navier_Stokes_FT_Disc::fluide_diphasique(), Fluide_Diphasique::fluide_phase(), Solid_Particle_base::get_equivalent_radius(), Fluide_Diphasique::get_id_fluid_phase(), Navier_Stokes_FT_Disc::get_set_pressure_field_Stokes_th(), get_vinf_Stokes(), Post_Processing_Hydrodynamic_Forces::ptr_eq_ns_, TRUST_Ref< _CLASSE_ >::valeur(), and Domaine_VF::xp().
Referenced by compute_hydrodynamic_forces().
compute_vinf_Stokes()
void Post_Processing_Hydrodynamic_Forces_Stokes::compute_vinf_Stokes () protected
References Objet_U::dimension, Navier_Stokes_FT_Disc::fluide_diphasique(), Fluide_Diphasique::fluide_phase(), Solid_Particle_base::get_equivalent_radius(), Fluide_Diphasique::get_id_fluid_phase(), Milieu_base::gravite(), Navier_Stokes_FT_Disc::milieu(), Post_Processing_Hydrodynamic_Forces::ptr_eq_ns_, TRUST_Ref< _CLASSE_ >::valeur(), and Champ_Don_base::valeurs().
Referenced by compute_hydrodynamic_forces().
compute_UP1_UP2_Stokes()
void Post_Processing_Hydrodynamic_Forces_Stokes::compute_UP1_UP2_Stokes (int fa7, double vinf_Stokes, double particle_radius, double phi_mu) protected
References compute_Stokes_Ux_fluid(), compute_Stokes_Uy_fluid(), compute_Stokes_Uz_fluid(), Post_Processing_Hydrodynamic_Forces::coord_neighbor_fluid_fa7_pressure_1_, and Post_Processing_Hydrodynamic_Forces::coord_neighbor_fluid_fa7_pressure_2_.
Referenced by compute_neighbors_coordinates_fluid_fa7().
compute_pressure_interf()
double Post_Processing_Hydrodynamic_Forces_Stokes::compute_pressure_interf (double x, double y, double z) protected
References Navier_Stokes_FT_Disc::fluide_diphasique(), Fluide_Diphasique::fluide_phase(), Solid_Particle_base::get_equivalent_radius(), Fluide_Diphasique::get_id_fluid_phase(), get_vinf_Stokes(), Post_Processing_Hydrodynamic_Forces::ptr_eq_ns_, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by compute_pressure_force_trilinear_linear().
compute_Stokes_Ux_fluid()
double Post_Processing_Hydrodynamic_Forces_Stokes::compute_Stokes_Ux_fluid (double x, double y, double z, double vinf_Stokes, double particle_radius, double phi_mu) protected
Referenced by compute_UP1_UP2_Stokes(), and fill_Stokes_velocity_field().
compute_Stokes_Uy_fluid()
double Post_Processing_Hydrodynamic_Forces_Stokes::compute_Stokes_Uy_fluid (double x, double y, double z, double vinf_Stokes, double particle_radius, double phi_mu) protected
Referenced by compute_UP1_UP2_Stokes(), and fill_Stokes_velocity_field().
compute_Stokes_Uz_fluid()
double Post_Processing_Hydrodynamic_Forces_Stokes::compute_Stokes_Uz_fluid (double x, double y, double z, double vinf_Stokes, double particle_radius, double phi_mu) protected
Referenced by compute_UP1_UP2_Stokes(), and fill_Stokes_velocity_field().
get_vinf_Stokes()
const double & Post_Processing_Hydrodynamic_Forces_Stokes::get_vinf_Stokes () const inline protected
Referenced by compute_dUdx_Stokes_th(), compute_dUdz_Stokes_th(), compute_dVdz_Stokes_th(), compute_dWdx_Stokes_th(), compute_dWdy_Stokes_th(), compute_dWdz_Stokes_th(), compute_friction_force_complet_tensor(), compute_friction_force_projected_tensor(), compute_neighbors_coordinates_fluid_fa7(), compute_pressure_force_trilinear_linear(), compute_pressure_interf(), fill_sigma_Stokes_th(), fill_Stokes_pressure_field(), and fill_Stokes_velocity_field().
compute_neighbors_coordinates_fluid_fa7()
void Post_Processing_Hydrodynamic_Forces_Stokes::compute_neighbors_coordinates_fluid_fa7 (const int nb_fa7, const int is_discr_elem_diph, const DoubleTab & gravity_center_fa7, const Maillage_FT_Disc & mesh, const DoubleTab & tab_fa7_normal, const IntTab & particles_eulerian_id_number) override protected virtual
Reimplemented from Post_Processing_Hydrodynamic_Forces.
References Domaine_32_64< _SIZE_ >::chercher_elements(), compute_UP1_UP2_Stokes(), Post_Processing_Hydrodynamic_Forces::coord_neighbor_fluid_fa7_gradU_1_, Post_Processing_Hydrodynamic_Forces::coord_neighbor_fluid_fa7_gradU_2_, Post_Processing_Hydrodynamic_Forces::coord_neighbor_fluid_fa7_pressure_1_, Post_Processing_Hydrodynamic_Forces::coord_neighbor_fluid_fa7_pressure_2_, Objet_U::dimension, Domaine_VDF::dist_elem(), Domaine_dis_base::domaine(), Equation_base::domaine_dis(), Post_Processing_Hydrodynamic_Forces::elem_faces_for_interp(), Post_Processing_Hydrodynamic_Forces::face_voisins_for_interp(), Maillage_FT_Disc::facette_virtuelle(), Navier_Stokes_FT_Disc::fluide_diphasique(), Fluide_Diphasique::fluide_phase(), Solid_Particle_base::get_equivalent_radius(), Fluide_Diphasique::get_id_fluid_phase(), get_vinf_Stokes(), Post_Processing_Hydrodynamic_Forces::interpolation_distance_gradU_P1_, Post_Processing_Hydrodynamic_Forces::interpolation_distance_gradU_P2_, Post_Processing_Hydrodynamic_Forces::interpolation_distance_pressure_P1_, Post_Processing_Hydrodynamic_Forces::interpolation_distance_pressure_P2_, Post_Processing_Hydrodynamic_Forces::ptr_eq_ns_, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by compute_hydrodynamic_forces().
compute_pressure_force_trilinear_linear()
void Post_Processing_Hydrodynamic_Forces_Stokes::compute_pressure_force_trilinear_linear (int nb_fa7, const Maillage_FT_Disc & mesh, Convection_Diffusion_Temperature_FT_Disc::Thermal_correction_discretization_method dummy_value, const IntVect & compo_connexes_fa7, const ArrOfDouble & fa7_surface, const DoubleTab & tab_fa7_normal) override protected virtual
Reimplemented from Post_Processing_Hydrodynamic_Forces.
References compute_pressure_interf(), Post_Processing_Hydrodynamic_Forces::coord_neighbor_fluid_fa7_pressure_1_, Post_Processing_Hydrodynamic_Forces::coord_neighbor_fluid_fa7_pressure_2_, Objet_U::dimension, Maillage_FT_Disc::facette_virtuelle(), Navier_Stokes_FT_Disc::fluide_diphasique(), Fluide_Diphasique::fluide_phase(), Solid_Particle_base::get_equivalent_radius(), Maillage_FT_Disc::get_gravity_center_fa7(), Fluide_Diphasique::get_id_fluid_phase(), Navier_Stokes_FT_Disc::get_set_pressure_field_Stokes_th(), get_vinf_Stokes(), Post_Processing_Hydrodynamic_Forces::interpolation_distance_pressure_P1_, Post_Processing_Hydrodynamic_Forces::interpolation_distance_pressure_P2_, Post_Processing_Hydrodynamic_Forces::pressure_fa7_, Post_Processing_Hydrodynamic_Forces::pressure_force_fa7_, Post_Processing_Hydrodynamic_Forces::ptr_eq_ns_, Post_Processing_Hydrodynamic_Forces::total_pressure_force_, Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_elem(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by compute_hydrodynamic_forces().
compute_friction_force_complet_tensor()
void Post_Processing_Hydrodynamic_Forces_Stokes::compute_friction_force_complet_tensor (int nb_fa7, const Maillage_FT_Disc & mesh, const IntVect & compo_connexes_fa7, const ArrOfDouble & fa7_surface, const DoubleTab & tab_fa7_normal) override protected virtual
Reimplemented from Post_Processing_Hydrodynamic_Forces.
References Post_Processing_Hydrodynamic_Forces::coord_neighbor_fluid_fa7_gradU_1_, Post_Processing_Hydrodynamic_Forces::coord_neighbor_fluid_fa7_gradU_2_, Objet_U::dimension, Post_Processing_Hydrodynamic_Forces::ELEMENTS, Post_Processing_Hydrodynamic_Forces::FACES_NORMALE_X, Maillage_FT_Disc::facette_virtuelle(), Post_Processing_Hydrodynamic_Forces::fill_gradU_P1(), fill_gradU_P1_Stokes_th(), Post_Processing_Hydrodynamic_Forces::fill_gradU_P2(), fill_gradU_P2_Stokes_th(), Post_Processing_Hydrodynamic_Forces::fill_sigma(), fill_sigma_Stokes_th(), Navier_Stokes_FT_Disc::fluide_diphasique(), Fluide_Diphasique::fluide_phase(), Post_Processing_Hydrodynamic_Forces::friction_force_fa7_, Solid_Particle_base::get_equivalent_radius(), Maillage_FT_Disc::get_gravity_center_fa7(), Fluide_Diphasique::get_id_fluid_phase(), Navier_Stokes_FT_Disc::get_set_velocity_field_Stokes_th(), get_vinf_Stokes(), Post_Processing_Hydrodynamic_Forces::interpolation_distance_gradU_P1_, Post_Processing_Hydrodynamic_Forces::interpolation_distance_gradU_P2_, Post_Processing_Hydrodynamic_Forces::is_post_process_stress_tensor_fa7_, Post_Processing_Hydrodynamic_Forces::location_stress_tensor_, Post_Processing_Hydrodynamic_Forces::ptr_eq_ns_, Post_Processing_Hydrodynamic_Forces::total_friction_force_, Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_gradU_elem(), Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_gradU_face(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by compute_hydrodynamic_forces().
compute_friction_force_projected_tensor()
void Post_Processing_Hydrodynamic_Forces_Stokes::compute_friction_force_projected_tensor (int nb_fa7, const Maillage_FT_Disc & mesh, const IntVect & compo_connexes_fa7, const ArrOfDouble & fa7_surface, const DoubleTab & tab_fa7_normal) override protected virtual
Reimplemented from Post_Processing_Hydrodynamic_Forces.
References Domaine_32_64< _SIZE_ >::chercher_elements(), Post_Processing_Hydrodynamic_Forces::coord_neighbor_fluid_fa7_gradU_1_, Post_Processing_Hydrodynamic_Forces::coord_neighbor_fluid_fa7_gradU_2_, Objet_U::dimension, Domaine_VDF::dist_elem(), Domaine_dis_base::domaine(), Equation_base::domaine_dis(), Domaine_VF::elem_faces(), Post_Processing_Hydrodynamic_Forces::ELEMENTS, Domaine_VF::face_voisins(), Maillage_FT_Disc::facette_virtuelle(), Navier_Stokes_FT_Disc::fluide_diphasique(), Fluide_Diphasique::fluide_phase(), Post_Processing_Hydrodynamic_Forces::friction_force_fa7_, Solid_Particle_base::get_equivalent_radius(), Maillage_FT_Disc::get_gravity_center_fa7(), Fluide_Diphasique::get_id_fluid_phase(), Transport_Interfaces_FT_Disc::get_particles_position(), Navier_Stokes_FT_Disc::get_set_velocity_field_Stokes_th(), get_vinf_Stokes(), Post_Processing_Hydrodynamic_Forces::location_stress_tensor_, Post_Processing_Hydrodynamic_Forces::ptr_eq_ns_, Post_Processing_Hydrodynamic_Forces::ptr_eq_transport_, TRUSTTab< _TYPE_, _SIZE_ >::resize(), Post_Processing_Hydrodynamic_Forces::total_friction_force_, Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_face(), Post_Processing_Hydrodynamic_Forces::U_P1_, Post_Processing_Hydrodynamic_Forces::U_P2_, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by compute_hydrodynamic_forces().
compute_dUdx_Stokes_th()
double Post_Processing_Hydrodynamic_Forces_Stokes::compute_dUdx_Stokes_th (int fa7, double x_fa7, double y_fa7, double z_fa7, double r_fa7, double phi_mu, double particle_radius) protected
References get_vinf_Stokes().
Referenced by fill_gradU_P1_Stokes_th(), and fill_gradU_P2_Stokes_th().
compute_dUdz_Stokes_th()
double Post_Processing_Hydrodynamic_Forces_Stokes::compute_dUdz_Stokes_th (int fa7, double x_fa7, double y_fa7, double z_fa7, double r_fa7, double phi_mu, double particle_radius) protected
References get_vinf_Stokes().
Referenced by fill_gradU_P1_Stokes_th(), and fill_gradU_P2_Stokes_th().
compute_dVdz_Stokes_th()
double Post_Processing_Hydrodynamic_Forces_Stokes::compute_dVdz_Stokes_th (int fa7, double x_fa7, double y_fa7, double z_fa7, double r_fa7, double phi_mu, double particle_radius) protected
References get_vinf_Stokes().
Referenced by fill_gradU_P1_Stokes_th(), and fill_gradU_P2_Stokes_th().
compute_dWdx_Stokes_th()
double Post_Processing_Hydrodynamic_Forces_Stokes::compute_dWdx_Stokes_th (int fa7, double x_fa7, double y_fa7, double z_fa7, double r_fa7, double phi_mu, double particle_radius) protected
References get_vinf_Stokes().
Referenced by fill_gradU_P1_Stokes_th(), and fill_gradU_P2_Stokes_th().
compute_dWdy_Stokes_th()
double Post_Processing_Hydrodynamic_Forces_Stokes::compute_dWdy_Stokes_th (int fa7, double x_fa7, double y_fa7, double z_fa7, double r_fa7, double phi_mu, double particle_radius) protected
References get_vinf_Stokes().
Referenced by fill_gradU_P1_Stokes_th(), and fill_gradU_P2_Stokes_th().
compute_dWdz_Stokes_th()
double Post_Processing_Hydrodynamic_Forces_Stokes::compute_dWdz_Stokes_th (int fa7, double x_fa7, double y_fa7, double z_fa7, double r_fa7, double phi_mu, double particle_radius) protected
References get_vinf_Stokes().
Referenced by fill_gradU_P1_Stokes_th(), and fill_gradU_P2_Stokes_th().
fill_gradU_P1_Stokes_th()
void Post_Processing_Hydrodynamic_Forces_Stokes::fill_gradU_P1_Stokes_th (int fa7, double phi_mu, double particle_radius) protected
References compute_dUdx_Stokes_th(), compute_dUdz_Stokes_th(), compute_dVdz_Stokes_th(), compute_dWdx_Stokes_th(), compute_dWdy_Stokes_th(), compute_dWdz_Stokes_th(), and Post_Processing_Hydrodynamic_Forces::coord_neighbor_fluid_fa7_gradU_1_.
Referenced by compute_friction_force_complet_tensor().
fill_gradU_P2_Stokes_th()
void Post_Processing_Hydrodynamic_Forces_Stokes::fill_gradU_P2_Stokes_th (int fa7, double phi_mu, double particle_radius) protected
References compute_dUdx_Stokes_th(), compute_dUdz_Stokes_th(), compute_dVdz_Stokes_th(), compute_dWdx_Stokes_th(), compute_dWdy_Stokes_th(), compute_dWdz_Stokes_th(), and Post_Processing_Hydrodynamic_Forces::coord_neighbor_fluid_fa7_gradU_2_.
Referenced by compute_friction_force_complet_tensor().
fill_sigma_Stokes_th()
void Post_Processing_Hydrodynamic_Forces_Stokes::fill_sigma_Stokes_th (int fa7) protected
References Navier_Stokes_FT_Disc::fluide_diphasique(), Fluide_Diphasique::fluide_phase(), Solid_Particle_base::get_equivalent_radius(), Maillage_FT_Disc::get_gravity_center_fa7(), Fluide_Diphasique::get_id_fluid_phase(), get_vinf_Stokes(), Transport_Interfaces_FT_Disc::maillage_interface_pour_post(), Post_Processing_Hydrodynamic_Forces::ptr_eq_ns_, Post_Processing_Hydrodynamic_Forces::ptr_eq_transport_, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by compute_friction_force_complet_tensor().
Member Data Documentation
info_obj
const Type_info Post_Processing_Hydrodynamic_Forces_Stokes::info_obj static