TrioCFD: Option_DG Class Reference
Option_DG Class Reference
#include <Option_DG.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Interprete
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions
static int Nb_col_from_order (const int order)
Static Public Member Functions inherited from Interprete
static Objet_U & objet (const Nom &)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Interprete
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Constructor & Destructor Documentation
Option_DG()
Option_DG::Option_DG ()
~Option_DG()
Option_DG::~Option_DG ()
Member Function Documentation
cree_instance()
Objet_U * Option_DG::cree_instance () static
taille_memoire()
unsigned Option_DG::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Option_DG::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Option_DG::info () static
get_info()
const Type_info * Option_DG::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
Option_DG & Option_DG::self_cast (Objet_U & r) static
self_cast() [2/2]
const Option_DG & Option_DG::self_cast (const Objet_U & r) static
printOn()
Sortie & Option_DG::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
References Interprete::printOn().
readOn()
Entree & Option_DG::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
interpreter()
Entree & Option_DG::interpreter (Entree & is) override virtual
Implements Interprete.
References Param::ajouter(), DEFAULT_ORDER, GRAM_SCHMIDT, Param::lire_avec_accolades_depuis(), ORDER_OVERRIDE, and Objet_U::que_suis_je().
Get_order_for()
int Option_DG::Get_order_for (const Nom & n) static
References DEFAULT_ORDER, Nom::getString(), and ORDER_OVERRIDE.
Referenced by Champ_Elem_DG::associer_domaine_dis_base(), and DG_discretisation::discretiser_champ().
Nb_col_from_order()
int Option_DG::Nb_col_from_order (const int order) static
Returns
the number of columns necessary in the unknown vector for a given method order. For example order 1 and 2D means we deal with the basis {1, X, Y}, so 3 cols.
References Objet_U::dimension.
Referenced by Champ_Elem_DG::associer_domaine_dis_base(), Op_Diff_DG_Elem::dimensionner(), and DG_discretisation::discretiser_champ().
Member Data Documentation
info_obj
const Type_info Option_DG::info_obj static
DEFAULT_ORDER
int Option_DG::DEFAULT_ORDER = 1 static
Referenced by Get_order_for(), and interpreter().
GRAM_SCHMIDT
int Option_DG::GRAM_SCHMIDT = 1 static
Referenced by Domaine_DG::discretiser(), and interpreter().
ORDER_OVERRIDE
std::map< std::string, int > Option_DG::ORDER_OVERRIDE = {} static
Referenced by Get_order_for(), and interpreter().
QUAD_ORDER
int Option_DG::QUAD_ORDER static