TrioCFD: Source_Masse_Fluide_Dilatable_VEF Class Reference
Source_Masse_Fluide_Dilatable_VEF Class Reference
#include <Source_Masse_Fluide_Dilatable_VEF.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Source_Masse_Fluide_Dilatable_VEF()
Source_Masse_Fluide_Dilatable_VEF::Source_Masse_Fluide_Dilatable_VEF ()
~Source_Masse_Fluide_Dilatable_VEF()
Source_Masse_Fluide_Dilatable_VEF::~Source_Masse_Fluide_Dilatable_VEF ()
Member Function Documentation
cree_instance()
Objet_U * Source_Masse_Fluide_Dilatable_VEF::cree_instance () static
taille_memoire()
unsigned Source_Masse_Fluide_Dilatable_VEF::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Source_Masse_Fluide_Dilatable_VEF::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Source_Masse_Fluide_Dilatable_VEF::info () static
get_info()
const Type_info * Source_Masse_Fluide_Dilatable_VEF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Source_Masse_Fluide_Dilatable_base.
self_cast() [1/2]
Source_Masse_Fluide_Dilatable_VEF & Source_Masse_Fluide_Dilatable_VEF::self_cast (Objet_U & r) static
self_cast() [2/2]
const Source_Masse_Fluide_Dilatable_VEF & Source_Masse_Fluide_Dilatable_VEF::self_cast (const Objet_U & r) static
printOn()
Sortie & Source_Masse_Fluide_Dilatable_VEF::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Source_Masse_Fluide_Dilatable_base.
readOn()
Entree & Source_Masse_Fluide_Dilatable_VEF::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Source_Masse_Fluide_Dilatable_base.
References Source_Masse_Fluide_Dilatable_base::readOn().
ajouter_eq_espece()
void Source_Masse_Fluide_Dilatable_VEF::ajouter_eq_espece (const Convection_Diffusion_Fluide_Dilatable_base & eqn, const Fluide_Dilatable_base & fluide, const bool is_expl, DoubleVect & resu) const override virtual
Implements Source_Masse_Fluide_Dilatable_base.
References Source_Masse_Fluide_Dilatable_base::ch_front_source_, Source_Masse_Fluide_Dilatable_base::domaine_cl_dis_, Domaine_Cl_dis_base::domaine_dis(), Domaine_VF::elem_faces(), Domaine_VF::face_surfaces(), Domaine_VF::face_voisins(), Fluide_Dilatable_base::has_source_masse_espece_champ(), Frontiere_dis_base::le_nom(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Milieu_base::masse_volumique(), Domaine_VF::nb_faces(), Front_VF::nb_faces(), Source_Masse_Fluide_Dilatable_base::nom_bord_, Front_VF::num_premiere_face(), TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_front_base::valeurs(), Champ_Proto::valeurs(), TRUSTArray< _TYPE_, _SIZE_ >::view_ro(), TRUSTTab< _TYPE_, _SIZE_ >::view_ro(), TRUSTArray< _TYPE_, _SIZE_ >::view_rw(), TRUSTTab< _TYPE_, _SIZE_ >::view_rw(), and Domaine_VF::volumes_entrelaces().
ajouter_projection()
void Source_Masse_Fluide_Dilatable_VEF::ajouter_projection (const Fluide_Dilatable_base & fluide, DoubleVect & resu) const override virtual
Implements Source_Masse_Fluide_Dilatable_base.
References Source_Masse_Fluide_Dilatable_base::ch_front_source_, Domaine_dis_base::domaine(), Source_Masse_Fluide_Dilatable_base::domaine_cl_dis_, Domaine_Cl_dis_base::domaine_dis(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_VF::elem_faces(), Domaine_VF::face_sommets(), Domaine_VF::face_surfaces(), Domaine_VF::face_voisins(), Domaine_VEF::get_alphaE(), Domaine_VEF::get_alphaS(), Domaine_32_64< _SIZE_ >::get_renum_som_perio(), Fluide_Dilatable_base::has_source_masse_projection_champ(), Fluide_Dilatable_base::inco_chaleur(), Frontiere_dis_base::le_nom(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Domaine_dis_base::nb_elem_tot(), Domaine_VF::nb_faces(), Front_VF::nb_faces(), Domaine_32_64< _SIZE_ >::nb_faces_elem(), Domaine_VF::nb_faces_tot(), Domaine_VF::nb_som_face(), Domaine_32_64< _SIZE_ >::nb_som_tot(), Source_Masse_Fluide_Dilatable_base::nom_bord_, Front_VF::num_premiere_face(), Champ_base::temps(), TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_front_base::valeurs(), Champ_Inc_base::valeurs(), TRUSTArray< _TYPE_, _SIZE_ >::view_ro(), TRUSTTab< _TYPE_, _SIZE_ >::view_ro(), TRUSTArray< _TYPE_, _SIZE_ >::view_rw(), TRUSTTab< _TYPE_, _SIZE_ >::view_rw(), Domaine_VF::volumes(), and Domaine_VF::volumes_entrelaces().
Member Data Documentation
info_obj
const Type_info Source_Masse_Fluide_Dilatable_VEF::info_obj static