TrioCFD: Schema_Implicite_base Class Reference
Schema_Implicite_base Class Reference
#include <Schema_Implicite_base.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Schema_Temps_base
virtual void changer_temps_courant (const double)
virtual bool corriger_dt_calcule (double &dt) const
int diffusion_implicite () const
double & facteur_securite_pas ()
double facteur_securite_pas () const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual int impr (Sortie &os, Probleme_base &pb) const
virtual void imprimer (Sortie &os) const
void imprimer (Sortie &os, Probleme_base &pb) const
virtual bool isStationary () const
const Nom & le_nom () const override
int limpr () const
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual int mettre_a_jour ()
int nb_impr () const
int nb_pas_dt () const
int nb_pas_dt_max () const
int nb_pas_dt_max_atteint () const
int nb_sauv_max () const
void nommer (const Nom &) override
double pas_de_temps () const
double & pas_temps_max ()
double pas_temps_max () const
double & pas_temps_min ()
double pas_temps_min () const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Schema_Temps_base ()
double seuil_statio () const
virtual int stop () const
int stop_lu () const
double temps_calcul () const
double temps_courant () const
int temps_final_atteint () const
double temps_impr () const
double temps_init () const
double temps_max () const
double temps_precedent () const
double temps_sauv () const
void update_critere_statio (const DoubleTab &tab_critere, Equation_base &equation)
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
Il porte un objet de type Solveur (ex le Simpler)
Constructor & Destructor Documentation
Schema_Implicite_base()
Schema_Implicite_base::Schema_Implicite_base ()
~Schema_Implicite_base()
Schema_Implicite_base::~Schema_Implicite_base () override
Member Function Documentation
info()
const Type_info * Schema_Implicite_base::info () static
get_info()
const Type_info * Schema_Implicite_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Schema_Temps_base.
Reimplemented in Schema_Euler_Implicite_Stationnaire, Schema_Implicite_Multi_TimeStep_base, Schema_Backward_Differentiation_base, Schema_Backward_Differentiation_order_2, and Schema_Backward_Differentiation_order_3.
self_cast() [1/2]
Schema_Implicite_base & Schema_Implicite_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Schema_Implicite_base & Schema_Implicite_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Schema_Implicite_base::printOn (Sortie & os) const override protected virtual
Surcharge Objet_U::printOn(Sortie&) Imprime le schema en temps sur un flot de sortie.
!! Attention n'est pas symetrique de la lecture !! On ecrit les differents parametres du schema en temps.
Parameters
(Sortie& os) le flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Schema_Temps_base.
Reimplemented in Schema_Euler_Implicite_Stationnaire, Schema_Implicite_Multi_TimeStep_base, Schema_Backward_Differentiation_base, Schema_Backward_Differentiation_order_2, and Schema_Backward_Differentiation_order_3.
References le_solveur, and Schema_Temps_base::printOn().
Referenced by Schema_Euler_Implicite_Stationnaire::printOn(), Schema_Adams_Moulton_base::printOn(), Schema_Euler_Implicite::printOn(), and Schema_Implicite_Multi_TimeStep_base::printOn().
readOn()
Entree & Schema_Implicite_base::readOn (Entree & is) override protected virtual
Lecture d'un schema en temps a partir d'un flot d'entree.
Le format de lecture attendu est le suivant: { [Motcle valeur_reelle] } Les mots clefs peuvent etre: tinit, tmax, nb_pas_dt_max, dt_min, dt_max, dt_sauv, dt_impr, facsec, seuil_statio,
Parameters
(Entree& is) le flot d'entree
Returns
(Entree&) le flot d'entree modifie
Exceptions
accolade ouvrante attendue
motclef inconnu a cet endroit
Reimplemented from Schema_Temps_base.
Reimplemented in Schema_Euler_Implicite_Stationnaire, Schema_Implicite_Multi_TimeStep_base, Schema_Backward_Differentiation_base, Schema_Backward_Differentiation_order_2, and Schema_Backward_Differentiation_order_3.
References Schema_Temps_base::readOn().
Referenced by Schema_Euler_Implicite_Stationnaire::readOn(), Schema_Euler_Implicite::readOn(), and Schema_Implicite_Multi_TimeStep_base::readOn().
solveur() [1/2]
TRUST_Deriv< Solveur_Implicite_base > & Schema_Implicite_base::solveur () inline
References le_solveur.
Referenced by Pb_Hydraulique_ALE::associer_sch_tps_base(), Pb_Hydraulique_Turbulent_ALE::associer_sch_tps_base(), and Pb_Multiphase::lire_equations().
solveur() [2/2]
const TRUST_Deriv< Solveur_Implicite_base > & Schema_Implicite_base::solveur () const inline
References le_solveur.
set_param()
void Schema_Implicite_base::set_param (Param & param) override virtual
Reimplemented from Schema_Temps_base.
Reimplemented in Schema_Euler_Implicite_Stationnaire, and Schema_Implicite_Multi_TimeStep_base.
References Param::ajouter(), le_solveur, Param::REQUIRED, and Schema_Temps_base::set_param().
Referenced by Schema_Euler_Implicite_Stationnaire::set_param(), Schema_Euler_Implicite::set_param(), and Schema_Implicite_Multi_TimeStep_base::set_param().
Member Data Documentation
info_obj
const Type_info Schema_Implicite_base::info_obj static
le_solveur
TRUST_Deriv< Solveur_Implicite_base > Schema_Implicite_base::le_solveur protected
Referenced by Schema_Euler_Implicite::faire_un_pas_de_temps_eqn_base(), Schema_Implicite_Multi_TimeStep_base::faire_un_pas_de_temps_eqn_base(), Schema_Euler_Implicite::faire_un_pas_de_temps_pb_couple(), Schema_Implicite_Multi_TimeStep_base::Iterer_Pb(), Schema_Euler_Implicite::Iterer_Pb(), printOn(), Schema_Euler_Implicite_Stationnaire::readOn(), Schema_Euler_Implicite::readOn(), Schema_Implicite_Multi_TimeStep_base::readOn(), set_param(), and solveur().