TrioCFD: Op_Dift_VDF_base Class Reference
Op_Dift_VDF_base Class Reference
#include <Op_Dift_VDF_base.h>
Public Member Functions
void contribuer_au_second_membre (DoubleTab &) const override
const Type_info * get_info () const override
Public Member Functions inherited from Op_Diff_VDF_base
void completer () override
void contribuer_au_second_membre (DoubleTab &resu) const override
const Type_info * get_info () const override
int impr (Sortie &os) const override
Public Member Functions inherited from Operateur_Diff_base
virtual void associer_diffusivite_pour_pas_de_temps (const Champ_base &)
const Type_info * get_info () const override
Public Member Functions inherited from Operateur_base
void associer_eqn (const Equation_base &)
virtual double calculer_dt_stab () const
virtual void completer ()
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual void mettre_a_jour (double temps)
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Operateur_Diff_base
virtual const Champ_base & diffusivite_pour_pas_de_temps () const
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Op_Dift_VDF_base() [1/2]
Op_Dift_VDF_base::Op_Dift_VDF_base ()
~Op_Dift_VDF_base()
Op_Dift_VDF_base::~Op_Dift_VDF_base () override
Op_Dift_VDF_base() [2/2]
Op_Dift_VDF_base::Op_Dift_VDF_base (const Iterateur_VDF_base & iter_base) inline
Member Function Documentation
info()
const Type_info * Op_Dift_VDF_base::info () static
get_info()
const Type_info * Op_Dift_VDF_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Op_Diff_VDF_base.
Reimplemented in Op_Diff_K_Eps_Bas_Re_VDF_base, Op_Diff_K_Eps_Bas_Re_VDF_Elem_Axi, Op_Diff_K_Eps_Bas_Re_VDF_Elem, Op_Diff_K_Eps_Bas_Re_VDF_var_Elem, Op_Diff_K_Eps_VDF_base, Op_Diff_K_Eps_VDF_Elem, Op_Diff_K_Eps_VDF_Elem_Axi, Op_Diff_K_Eps_QC_VDF_Elem, Op_Diff_K_Eps_var_VDF_Elem, Op_Diff_K_Eps_var_QC_VDF_Elem, Op_Diff_K_VDF_Elem, Op_Diff_Eps_VDF_Elem, Op_Diff_K_Omega_VDF_base, Op_Diff_K_Omega_VDF_Elem, Op_Diff_K_Omega_var_VDF_Elem, Op_Dift_VDF_Elem_base, Op_Dift_VDF_Face_Axi_base, Op_Dift_VDF_Face_base, Op_Dift_Multiphase_VDF_Elem, Op_Dift_Multiphase_VDF_Face, Op_Dift_VDF_Elem, Op_Dift_VDF_Elem_Axi, Op_Dift_VDF_Multi_inco_Elem, Op_Dift_VDF_Multi_inco_Elem_Axi, Op_Dift_VDF_Face, and Op_Dift_VDF_Face_Axi.
self_cast() [1/2]
Op_Dift_VDF_base & Op_Dift_VDF_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Op_Dift_VDF_base & Op_Dift_VDF_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Op_Dift_VDF_base::printOn (Sortie & os) const override protected virtual
DOES NOTHING - to override in derived classes.
Imprime l'operateur sur un flot de sortie.
Parameters
(Sortie& os) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Op_Diff_VDF_base.
Reimplemented in Op_Diff_K_Eps_Bas_Re_VDF_base, Op_Diff_K_Eps_Bas_Re_VDF_Elem_Axi, Op_Diff_K_Eps_Bas_Re_VDF_Elem, Op_Diff_K_Eps_Bas_Re_VDF_var_Elem, Op_Diff_K_Eps_VDF_base, Op_Diff_K_Eps_VDF_Elem, Op_Diff_K_Eps_VDF_Elem_Axi, Op_Diff_K_Eps_QC_VDF_Elem, Op_Diff_K_Eps_var_VDF_Elem, Op_Diff_K_Eps_var_QC_VDF_Elem, Op_Diff_K_VDF_Elem, Op_Diff_Eps_VDF_Elem, Op_Diff_K_Omega_VDF_base, Op_Diff_K_Omega_VDF_Elem, Op_Diff_K_Omega_var_VDF_Elem, Op_Dift_VDF_Elem_base, Op_Dift_VDF_Face_Axi_base, Op_Dift_VDF_Face_base, Op_Dift_Multiphase_VDF_Elem, Op_Dift_Multiphase_VDF_Face, Op_Dift_VDF_Elem, Op_Dift_VDF_Elem_Axi, Op_Dift_VDF_Multi_inco_Elem, Op_Dift_VDF_Multi_inco_Elem_Axi, Op_Dift_VDF_Face, and Op_Dift_VDF_Face_Axi.
References Op_Diff_VDF_base::printOn().
readOn()
Entree & Op_Dift_VDF_base::readOn (Entree & is) override protected virtual
DOES NOTHING - to override in derived classes.
Lit un operateur sur un flot d'entree.
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Op_Diff_VDF_base.
Reimplemented in Op_Diff_K_Eps_Bas_Re_VDF_base, Op_Diff_K_Eps_Bas_Re_VDF_Elem_Axi, Op_Diff_K_Eps_Bas_Re_VDF_Elem, Op_Diff_K_Eps_Bas_Re_VDF_var_Elem, Op_Diff_K_Eps_VDF_base, Op_Diff_K_Eps_VDF_Elem, Op_Diff_K_Eps_VDF_Elem_Axi, Op_Diff_K_Eps_QC_VDF_Elem, Op_Diff_K_Eps_var_VDF_Elem, Op_Diff_K_Eps_var_QC_VDF_Elem, Op_Diff_K_VDF_Elem, Op_Diff_Eps_VDF_Elem, Op_Diff_K_Omega_VDF_base, Op_Diff_K_Omega_VDF_Elem, Op_Diff_K_Omega_var_VDF_Elem, Op_Dift_VDF_Elem_base, Op_Dift_VDF_Face_Axi_base, Op_Dift_VDF_Face_base, Op_Dift_Multiphase_VDF_Elem, Op_Dift_Multiphase_VDF_Face, Op_Dift_VDF_Elem, Op_Dift_VDF_Elem_Axi, Op_Dift_VDF_Multi_inco_Elem, Op_Dift_VDF_Multi_inco_Elem_Axi, Op_Dift_VDF_Face, and Op_Dift_VDF_Face_Axi.
References Op_Diff_VDF_base::readOn().
ajouter_blocs()
void Op_Dift_VDF_base::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl) const override virtual
Reimplemented from Operateur_base.
Reimplemented in Op_Diff_K_Eps_Bas_Re_VDF_base, Op_Diff_K_Eps_VDF_base, and Op_Diff_K_Omega_VDF_base.
References ajoute_terme_pour_axi_turb(), Iterateur_VDF_base::ajouter_blocs(), Statistiques::begin_count(), Statistiques::end_count(), and Op_Diff_VDF_base::iter_.
contribuer_au_second_membre()
void Op_Dift_VDF_base::contribuer_au_second_membre (DoubleTab &) const inline override virtual
DOES NOTHING - to override in derived classes.
Parameters
(DoubleTab&) un tableau de valeur (double)
Exceptions
methode a surcharger
Reimplemented from Op_Diff_VDF_base.
Reimplemented in Op_Dift_VDF_Face_Axi_base.
References Process::exit().
associer_diffusivite_turbulente_base()
void Op_Dift_VDF_base::associer_diffusivite_turbulente_base (const Champ_Fonc_base & diff_turb) inline
References Op_Diff_Turbulent_base::associer_diffusivite_turbulente().
completer_Op_Dift_VDF_base()
void Op_Dift_VDF_base::completer_Op_Dift_VDF_base () inline
References Op_Diff_VDF_base::completer().
Referenced by Op_Dift_Multiphase_VDF_Elem::completer(), and Op_Dift_Multiphase_VDF_Face::completer().
ajoute_terme_pour_axi_turb()
void Op_Dift_VDF_base::ajoute_terme_pour_axi_turb (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl) const protected
References Objet_U::bidim_axi, Equation_base::champ_conserve(), Eval_Dift_VDF::diffusivite_turbulente(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Iterateur_VDF_base::domaine(), MorEqn::equation(), Probleme_base::equation(), Iterateur_VDF_base::evaluateur(), Process::exit(), Domaine_VF::face_voisins(), Eval_Diff_VDF::get_diffusivite(), Equation_base::get_modele(), Nom::getString(), Equation_base::inconnue(), Operateur_Diff_base::is_turb(), Op_Diff_VDF_base::iter_, Field_base::le_nom(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Domaine_dis_base::nb_elem_tot(), Domaine_VF::nb_faces(), Domaine_VDF::orientation(), Champ_Inc_base::passe(), Equation_base::probleme(), Objet_U::que_suis_je(), Eval_Dift_Multiphase_VDF::tab_nu_t(), TRUST_Ref_Objet_U::valeur(), Champ_Don_base::valeurs(), Champ_Inc_base::valeurs(), Champ_Proto::valeurs(), Domaine_VF::volumes_entrelaces(), and Domaine_VF::xv().
Referenced by ajouter_blocs().
Member Data Documentation
info_obj
const Type_info Op_Dift_VDF_base::info_obj static