TrioCFD: Eval_Dift_VDF_Face Class Reference
Eval_Dift_VDF_Face Class Reference
#include <Eval_Dift_VDF_leaves.h>
Detailed Description
Le champ diffuse est un Champ_Face_VDF
Member Function Documentation
associer_modele_turbulence()
void Eval_Dift_VDF_Face::associer_modele_turbulence (const Modele_turbulence_hyd_base & mod) inline
uses_wall()
bool Eval_Dift_VDF_Face::uses_wall () const inline
mettre_a_jour()
void Eval_Dift_VDF_Face::mettre_a_jour () override virtual
Reimplemented from Eval_Dift_VDF.
References Eval_Dift_VDF::mettre_a_jour(), TRUSTTab< _TYPE_, _SIZE_ >::ref(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
tau_tan_impl()
double Eval_Dift_VDF_Face::tau_tan_impl (int face, int k) const
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Process::exit(), and Evaluateur_VDF::le_dom.
Member Data Documentation
IS_TURB
constexpr bool Eval_Dift_VDF_Face::IS_TURB = true static constexpr
CALC_FA7_SORTIE_LIB
constexpr bool Eval_Dift_VDF_Face::CALC_FA7_SORTIE_LIB = true static
CALC_ARR_PAR_FL
constexpr bool Eval_Dift_VDF_Face::CALC_ARR_PAR_FL = false static