TrioCFD: Op_Dift_Multiphase_VDF_Elem Class Reference
Op_Dift_Multiphase_VDF_Elem Class Reference
#include <Op_Dift_Multiphase_VDF_Elem.h>
Public Member Functions
double calculer_dt_stab () const override
void completer () override
const Type_info * get_info () const override
void mettre_a_jour (double) override
Public Member Functions inherited from Op_Dift_VDF_Elem_base
const Type_info * get_info () const override
void modifier_pour_Cl (Matrice_Morse &matrice, DoubleTab &secmem) const override
Public Member Functions inherited from Op_Dift_VDF_base
void contribuer_au_second_membre (DoubleTab &) const override
const Type_info * get_info () const override
Public Member Functions inherited from Op_Diff_VDF_base
void completer () override
void contribuer_au_second_membre (DoubleTab &resu) const override
const Type_info * get_info () const override
int impr (Sortie &os) const override
Public Member Functions inherited from Operateur_Diff_base
virtual void associer_diffusivite_pour_pas_de_temps (const Champ_base &)
const Type_info * get_info () const override
Public Member Functions inherited from Operateur_base
void associer_eqn (const Equation_base &)
virtual double calculer_dt_stab () const
virtual void completer ()
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual void mettre_a_jour (double temps)
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Operateur_Diff_base
virtual const Champ_base & diffusivite_pour_pas_de_temps () const
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
~Op_Dift_Multiphase_VDF_Elem()
Op_Dift_Multiphase_VDF_Elem::~Op_Dift_Multiphase_VDF_Elem ()
Op_Dift_Multiphase_VDF_Elem()
Op_Dift_Multiphase_VDF_Elem::Op_Dift_Multiphase_VDF_Elem () inline
Member Function Documentation
cree_instance()
Objet_U * Op_Dift_Multiphase_VDF_Elem::cree_instance () static
taille_memoire()
unsigned Op_Dift_Multiphase_VDF_Elem::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Op_Dift_Multiphase_VDF_Elem::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Op_Dift_Multiphase_VDF_Elem::info () static
get_info()
const Type_info * Op_Dift_Multiphase_VDF_Elem::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Op_Dift_VDF_Elem_base.
self_cast() [1/2]
Op_Dift_Multiphase_VDF_Elem & Op_Dift_Multiphase_VDF_Elem::self_cast (Objet_U & r) static
self_cast() [2/2]
const Op_Dift_Multiphase_VDF_Elem & Op_Dift_Multiphase_VDF_Elem::self_cast (const Objet_U & r) static
printOn()
Sortie & Op_Dift_Multiphase_VDF_Elem::printOn (Sortie & os) const override protected virtual
DOES NOTHING - to override in derived classes.
Imprime l'operateur sur un flot de sortie.
Parameters
(Sortie& os) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Op_Dift_VDF_Elem_base.
References Objet_U::que_suis_je().
readOn()
Entree & Op_Dift_Multiphase_VDF_Elem::readOn (Entree & is) override protected virtual
DOES NOTHING - to override in derived classes.
Lit un operateur sur un flot d'entree.
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Op_Dift_VDF_Elem_base.
References Op_Dift_Multiphase_proto::ajout_champs_proto_elem(), Op_Dift_Multiphase_proto::associer_proto(), Operateur_base::champs_compris_, Op_Dift_Multiphase_proto::corr_, MorEqn::equation(), and Correlation_base::typer_lire_correlation().
creer_champ()
void Op_Dift_Multiphase_VDF_Elem::creer_champ (const Motcle & motlu) override virtual
Reimplemented from Operateur_base.
References Operateur_base::creer_champ(), and Op_Dift_Multiphase_proto::creer_champ_proto_elem().
get_noms_champs_postraitables()
void Op_Dift_Multiphase_VDF_Elem::get_noms_champs_postraitables (Noms & nom, Option opt = NONE) const override virtual
Reimplemented from Operateur_base.
References Operateur_base::get_noms_champs_postraitables(), Op_Dift_Multiphase_proto::get_noms_champs_postraitables_proto(), and Objet_U::que_suis_je().
completer()
void Op_Dift_Multiphase_VDF_Elem::completer () override virtual
Associe l'operateur au domaine_dis, le domaine_Cl_dis, et a l'inconnue de son equation.
Exceptions
pas d'equation associee
Reimplemented from Op_Diff_VDF_base.
References Op_Dift_VDF_base::completer_Op_Dift_VDF_base(), Op_Dift_Multiphase_proto::completer_proto_elem(), Op_Dift_Multiphase_proto::corr_, MorEqn::equation(), Objet_U_ptr::non_nul(), and Op_Dift_Multiphase_proto::nu_ou_lambda_turb_.
mettre_a_jour()
void Op_Dift_Multiphase_VDF_Elem::mettre_a_jour (double temps) override virtual
DOES NOTHING - to override in derived classes.
Mise a jour de l'operateur
Parameters
(double) un pas de temps
Reimplemented from Operateur_base.
References Op_Dift_Multiphase_proto::call_compute_diff_turb(), MorEqn::equation(), Probleme_base::equation(), Process::exit(), Operateur::l_op_base(), Operateur_base::mettre_a_jour(), Op_Dift_Multiphase_proto::mettre_a_jour_proto_elem(), Op_Dift_Multiphase_proto::nu_ou_lambda_turb_, Equation_base::operateur(), Equation_base::probleme(), and Objet_U::que_suis_je().
associer_loipar()
void Op_Dift_Multiphase_VDF_Elem::associer_loipar (const Turbulence_paroi_scal_base &) inline
associer_diffusivite_turbulente()
void Op_Dift_Multiphase_VDF_Elem::associer_diffusivite_turbulente (const Champ_Fonc_base & ch) inline
is_turb()
bool Op_Dift_Multiphase_VDF_Elem::is_turb () const inline override virtual
Reimplemented from Operateur_Diff_base.
calculer_dt_stab()
double Op_Dift_Multiphase_VDF_Elem::calculer_dt_stab () const override virtual
Calcul dt_stab.
Returns
(double) renvoie toujours 1.e30
Reimplemented from Operateur_base.
References alpha_(), Operateur_Diff_base::diffusivite_pour_pas_de_temps(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Domaine_VDF::dist_face(), Iterateur_VDF_base::domaine(), Domaine_VF::elem_faces(), MorEqn::equation(), Op_Diff_VDF_base::iter_, TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Process::mp_max(), Domaine_dis_base::nb_elem(), Op_Dift_Multiphase_proto::nu_ou_lambda_turb_, and Champ_Proto::valeurs().
alpha_() [1/2]
double Op_Dift_Multiphase_VDF_Elem::alpha_ (const int i) const inline override virtual
Implements Op_Dift_VDF_Elem_base.
correlation_viscosite_turbulente()
const Correlation_base * Op_Dift_Multiphase_VDF_Elem::correlation_viscosite_turbulente () const inline override virtual
Reimplemented from Operateur_Diff_base.
References Op_Dift_Multiphase_proto::corr_, and TRUST_Deriv< _CLASSE_ >::valeur().
correlation()
const Correlation_base & Op_Dift_Multiphase_VDF_Elem::correlation () const inline
References Op_Dift_Multiphase_proto::corr_, and TRUST_Deriv< _CLASSE_ >::valeur().
alpha_() [2/2]
const DoubleTab & Op_Dift_Multiphase_VDF_Elem::alpha_ () const inline
Referenced by calculer_dt_stab().
associer()
void Op_Dift_Multiphase_VDF_Elem::associer (const Domaine_dis_base & zd, const Domaine_Cl_dis_base & zcd, const Champ_Inc_base & ch) inline override virtual
Implements Operateur_base.
associer_diffusivite()
void Op_Dift_Multiphase_VDF_Elem::associer_diffusivite (const Champ_base & ch) inline override virtual
Implements Operateur_Diff_base.
diffusivite()
const Champ_base & Op_Dift_Multiphase_VDF_Elem::diffusivite () const inline override virtual
Implements Operateur_Diff_base.
dimension_min_nu()
int Op_Dift_Multiphase_VDF_Elem::dimension_min_nu () const inline
get_diffusivite_turbulente()
const DoubleTab & Op_Dift_Multiphase_VDF_Elem::get_diffusivite_turbulente () const inline
Member Data Documentation
info_obj
const Type_info Op_Dift_Multiphase_VDF_Elem::info_obj static