TrioCFD: Modele_turbulence_hyd_LES_VEF Class Reference
Modele_turbulence_hyd_LES_VEF Class Reference
#include <Modele_turbulence_hyd_LES_VEF.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Modele_turbulence_hyd_LES_base
const Type_info * get_info () const override
void imprimer (Sortie &is) const override
int preparer_calcul () override
int reprendre (Entree &is) override
const Type_info * get_info () const override
void imprimer (Sortie &) const override
int reprendre (Entree &is) override
Public Member Functions inherited from Modele_turbulence_hyd_base
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Type_info * get_info () const override
virtual void imprimer (Sortie &) const
void lire_distance_paroi ()
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual int preparer_calcul ()
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
maille fonction de structure en VEF
Constructor & Destructor Documentation
Modele_turbulence_hyd_LES_VEF()
Modele_turbulence_hyd_LES_VEF::Modele_turbulence_hyd_LES_VEF ()
~Modele_turbulence_hyd_LES_VEF()
Modele_turbulence_hyd_LES_VEF::~Modele_turbulence_hyd_LES_VEF ()
Member Function Documentation
cree_instance()
Objet_U * Modele_turbulence_hyd_LES_VEF::cree_instance () static
taille_memoire()
unsigned Modele_turbulence_hyd_LES_VEF::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Modele_turbulence_hyd_LES_VEF::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Modele_turbulence_hyd_LES_VEF::info () static
get_info()
const Type_info * Modele_turbulence_hyd_LES_VEF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Modele_turbulence_hyd_LES_VEF_base.
self_cast() [1/2]
Modele_turbulence_hyd_LES_VEF & Modele_turbulence_hyd_LES_VEF::self_cast (Objet_U & r) static
self_cast() [2/2]
const Modele_turbulence_hyd_LES_VEF & Modele_turbulence_hyd_LES_VEF::self_cast (const Objet_U & r) static
printOn()
Sortie & Modele_turbulence_hyd_LES_VEF::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Modele_turbulence_hyd_LES_VEF_base.
References Objet_U::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Modele_turbulence_hyd_LES_VEF::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Modele_turbulence_hyd_LES_VEF_base.
References Modele_turbulence_hyd_LES_VEF_base::readOn().
calculer_viscosite_turbulente()
Champ_Fonc_base & Modele_turbulence_hyd_LES_VEF::calculer_viscosite_turbulente () override protected virtual
Implements Modele_turbulence_hyd_0_eq_base.
References calculer_fonction_structure(), Champ_base::changer_temps(), Modele_turbulence_hyd_LES_base::CSM1, Domaine_dis_base::domaine(), Process::exit(), F2_, Domaine_VF::face_voisins(), Modele_turbulence_hyd_base::la_viscosite_turbulente_, Modele_turbulence_hyd_0_eq_base::le_dom_Cl_, Modele_turbulence_hyd_0_eq_base::le_dom_VF_, Domaine_Cl_dis_base::les_conditions_limites(), Modele_turbulence_hyd_base::mon_equation_, Domaine_dis_base::nb_elem(), Domaine_VF::nb_faces(), Front_VF::nb_faces(), Domaine_32_64< _SIZE_ >::nb_faces_elem(), Domaine_VF::nb_faces_tot(), Front_VF::num_premiere_face(), r_, TRUSTVect< _TYPE_, _SIZE_ >::resize(), TRUSTVect< _TYPE_, _SIZE_ >::size(), TRUST_Vector< _CLASSE_ >::size(), TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), and Champ_Don_base::valeurs().
calculer_fonction_structure()
void Modele_turbulence_hyd_LES_VEF::calculer_fonction_structure () protected virtual
References Objet_U::dimension, Periodique::direction_periodicite(), Periodique::distance(), Domaine_VF::elem_faces(), Process::exit(), F2_, Domaine_VF::face_voisins(), Modele_turbulence_hyd_0_eq_base::le_dom_Cl_, Modele_turbulence_hyd_0_eq_base::le_dom_VF_, Domaine_Cl_dis_base::les_conditions_limites(), Modele_turbulence_hyd_base::mon_equation_, Domaine_VF::nb_faces(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), r_, TRUST_Vector< _CLASSE_ >::size(), TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), and Domaine_VF::xv().
Referenced by calculer_viscosite_turbulente().
Member Data Documentation
info_obj
const Type_info Modele_turbulence_hyd_LES_VEF::info_obj static
F2_
DoubleVect Modele_turbulence_hyd_LES_VEF::F2_ protected
Referenced by calculer_fonction_structure(), and calculer_viscosite_turbulente().
r_
DoubleVect Modele_turbulence_hyd_LES_VEF::r_ protected
Referenced by calculer_fonction_structure(), and calculer_viscosite_turbulente().