TrioCFD: Eval_Diff_K_Eps_VDF_const Class Reference
Eval_Diff_K_Eps_VDF_const Class Reference
#include <Eval_Diff_K_Eps_VDF_const.h>
Member Function Documentation
nu_1_impl()
double Eval_Diff_K_Eps_VDF_const::nu_1_impl (int i, int compo) const inline
References Eval_Diff_K_Eps_VDF::db_diffusivite, Eval_Diff_K_Eps_VDF::dv_diffusivite_turbulente, and Eval_Diff_K_Eps_VDF::Prdt.
Referenced by compute_heq_impl(), and nu_2_impl().
nu_2_impl()
double Eval_Diff_K_Eps_VDF_const::nu_2_impl (int i, int compo) const inline
References nu_1_impl().
compute_heq_impl()
double Eval_Diff_K_Eps_VDF_const::compute_heq_impl (double d0, int i, double d1, int j, int compo) const inline
References nu_1_impl().