TrioCFD: Source_Transport_K_Realisable_VDF_Elem Class Reference
Source_Transport_K_Realisable_VDF_Elem Class Reference
#include <Source_Transport_K_Realisable_VDF_Elem.h>
Public Member Functions
const Type_info * get_info () const override
void mettre_a_jour (double temps) override
const Type_info * get_info () const override
const Type_info * get_info () const override
void mettre_a_jour (double t) override
Public Member Functions inherited from Source_base
virtual int a_pour_Champ_Fonc (const Motcle &mot, TRUST_Ref< Champ_base * > &ch_ref) const
virtual void associer_champ_rho (const Champ_base &champ_rho)
virtual void completer ()
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
virtual void resetTime (double t)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Source_Transport_K_Realisable_VDF_Elem()
Source_Transport_K_Realisable_VDF_Elem::Source_Transport_K_Realisable_VDF_Elem ()
~Source_Transport_K_Realisable_VDF_Elem()
Source_Transport_K_Realisable_VDF_Elem::~Source_Transport_K_Realisable_VDF_Elem ()
Member Function Documentation
cree_instance()
Objet_U * Source_Transport_K_Realisable_VDF_Elem::cree_instance () static
taille_memoire()
unsigned Source_Transport_K_Realisable_VDF_Elem::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Source_Transport_K_Realisable_VDF_Elem::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Source_Transport_K_Realisable_VDF_Elem::info () static
get_info()
const Type_info * Source_Transport_K_Realisable_VDF_Elem::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Source_Transport_Realisable_VDF_Elem_base.
self_cast() [1/2]
Source_Transport_K_Realisable_VDF_Elem & Source_Transport_K_Realisable_VDF_Elem::self_cast (Objet_U & r) static
self_cast() [2/2]
const Source_Transport_K_Realisable_VDF_Elem & Source_Transport_K_Realisable_VDF_Elem::self_cast (const Objet_U & r) static
printOn()
Sortie & Source_Transport_K_Realisable_VDF_Elem::printOn (Sortie & os) const override protected virtual
DOES NOTHING - to override in derived classes.
Imprime la source sur un flot de sortie.
Parameters
(Sortie& os) le flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Source_Transport_Realisable_VDF_Elem_base.
References Objet_U::que_suis_je().
readOn()
Entree & Source_Transport_K_Realisable_VDF_Elem::readOn (Entree & is) override protected virtual
DOES NOTHING - to override in derived classes.
Lecture d'un terme source sur un flot d'entree.
Parameters
(Entree& is) le flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Source_Transport_Realisable_VDF_Elem_base.
References Objet_U::que_suis_je(), and Source_Transport_proto::readOn_nothing().
ajouter_blocs()
void Source_Transport_K_Realisable_VDF_Elem::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl) const override virtual
Reimplemented from Source_Transport_Realisable_VDF_Elem_base.
References Source_Transport_Realisable_VDF_Elem_base::ajouter_blocs(), Objet_U::axi, Calcul_Production_K_VDF::calculer_terme_production_K_BiK(), Calcul_Production_K_VDF::calculer_terme_production_K_BiK_Axi(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Source_Transport_proto::eq_hydraulique, eqn_eps_Rea, eqn_k_Rea, Source_Transport_VDF_Elem_base::le_dom_Cl_VDF, Source_Transport_VDF_Elem_base::le_dom_VDF, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Source_Transport_K_Realisable_aniso_concen_VDF_Elem::ajouter_blocs(), Source_Transport_K_Realisable_aniso_therm_concen_VDF_Elem::ajouter_blocs(), and Source_Transport_K_Realisable_anisotherme_VDF_Elem::ajouter_blocs().
mettre_a_jour()
void Source_Transport_K_Realisable_VDF_Elem::mettre_a_jour (double temps) override virtual
DOES NOTHING - to override in derived classes.
Mise a jour en temps du terme source.
Parameters
(double) le pas de temps de mise a jour
Reimplemented from Source_Transport_VDF_Elem_base.
References Modele_Fonc_Realisable_base::Contributions_Sources_BiK(), Source_Transport_proto::eq_hydraulique, eqn_eps_Rea, eqn_k_Rea, and Source_Transport_VDF_Elem_base::mettre_a_jour().
associer_pb()
void Source_Transport_K_Realisable_VDF_Elem::associer_pb (const Probleme_base & pb) override virtual
Reimplemented from Source_Transport_VDF_Elem_base.
References Source_Transport_VDF_Elem_base::associer_pb(), eqn_eps_Rea, eqn_k_Rea, Modele_turbulence_hyd_K_Eps_Realisable_Bicephale::eqn_transp_Eps(), and MorEqn::equation().
Referenced by Source_Transport_K_Realisable_aniso_concen_VDF_Elem::associer_pb(), Source_Transport_K_Realisable_aniso_therm_concen_VDF_Elem::associer_pb(), and Source_Transport_K_Realisable_anisotherme_VDF_Elem::associer_pb().
Member Data Documentation
info_obj
const Type_info Source_Transport_K_Realisable_VDF_Elem::info_obj static
eqn_k_Rea
TRUST_Ref< Transport_K_ou_Eps_Realisable *> Source_Transport_K_Realisable_VDF_Elem::eqn_k_Rea protected
Referenced by ajouter_blocs(), associer_pb(), and mettre_a_jour().
eqn_eps_Rea
TRUST_Ref< Transport_K_ou_Eps_Realisable *> Source_Transport_K_Realisable_VDF_Elem::eqn_eps_Rea protected
Referenced by ajouter_blocs(), associer_pb(), and mettre_a_jour().