TrioCFD: Sous_domaine_dis_base Class Reference
Sous_domaine_dis_base Class Reference abstract
#include <Sous_domaine_dis_base.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
Les classes qui heritent de Sous_domaine_dis_base doivent surcharger la methode discretiser();
L Sous_Domaine definit un sous-ensemble des elements du Domaine. De meme, le Sous_domaine_dis_base definit un sous_ensemble des attributs du Domaine_dis, en particulier des faces.
See also
Domaine_dis, Sous_Domaine, Domaine_dis_base, Sous_Domaine_VF
Constructor & Destructor Documentation
Sous_domaine_dis_base()
Sous_domaine_dis_base::Sous_domaine_dis_base ()
~Sous_domaine_dis_base()
Sous_domaine_dis_base::~Sous_domaine_dis_base () override
Member Function Documentation
info()
const Type_info * Sous_domaine_dis_base::info () static
get_info()
const Type_info * Sous_domaine_dis_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
Reimplemented in Sous_domaine_VF.
self_cast() [1/2]
Sous_domaine_dis_base & Sous_domaine_dis_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Sous_domaine_dis_base & Sous_domaine_dis_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Sous_domaine_dis_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
Reimplemented in Sous_domaine_VF.
readOn()
Entree & Sous_domaine_dis_base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
Reimplemented in Sous_domaine_VF.
associer_sous_domaine()
void Sous_domaine_dis_base::associer_sous_domaine (const Sous_Domaine & un_sous_domaine)
Associe un Sous_Domaine a l'objet.
References le_sous_domaine.
associer_domaine_dis()
void Sous_domaine_dis_base::associer_domaine_dis (const Domaine_dis_base & un_domaine_dis)
Associe un Domaine_dis a l'objet.
References le_dom_dis.
sous_domaine() [1/2]
const Sous_Domaine & Sous_domaine_dis_base::sous_domaine () const
References le_sous_domaine.
Referenced by Op_Conv_EF_VEF_P1NC_Stab::completer(), and Perte_Charge_VEF::completer().
sous_domaine() [2/2]
Sous_Domaine & Sous_domaine_dis_base::sous_domaine ()
References le_sous_domaine.
domaine_dis() [1/2]
const Domaine_dis_base & Sous_domaine_dis_base::domaine_dis () const
References le_dom_dis, and TRUST_Ref< _CLASSE_ >::valeur().
domaine_dis() [2/2]
Domaine_dis_base & Sous_domaine_dis_base::domaine_dis ()
References le_dom_dis, and TRUST_Ref< _CLASSE_ >::valeur().
discretiser()
virtual void Sous_domaine_dis_base::discretiser () pure virtual
Implemented in Sous_domaine_VF.
Member Data Documentation
info_obj
const Type_info Sous_domaine_dis_base::info_obj static
le_sous_domaine
TRUST_Ref< Sous_Domaine *> Sous_domaine_dis_base::le_sous_domaine protected
Referenced by associer_sous_domaine(), Sous_domaine_VF::discretiser(), and sous_domaine().
le_dom_dis
TRUST_Ref< Domaine_dis_base *> Sous_domaine_dis_base::le_dom_dis protected
Referenced by associer_domaine_dis(), Sous_domaine_VF::discretiser(), and domaine_dis().