TrioCFD: Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re Class Reference
Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re Class Reference
#include <Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re.h>
Public Member Functions
const Type_info * get_info () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
int preparer_calcul () override
Public Member Functions inherited from Modele_turbulence_scal_Fluctuation_Temperature_W
const Type_info * get_info () const override
void imprimer (Sortie &) const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
int preparer_calcul () override
int reprendre (Entree &is) override
int sauvegarder (Sortie &os) const override
Public Member Functions inherited from Modele_turbulence_scal_base
virtual void associer (const Domaine_dis_base &, const Domaine_Cl_dis_base &)
void associer_eqn (const Equation_base &)
const Type_info * get_info () const override
virtual void imprimer (Sortie &) const
int limpr_nusselt (double, double, double, double) const
int lire_motcle_non_standard (const Motcle &, Entree &) override
Turbulence_paroi_scal_base & loi_paroi ()
const Turbulence_paroi_scal_base & loi_paroi () const
int loi_paroi_non_nulle () const
virtual int preparer_calcul ()
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re()
Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re::Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re ()
~Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re()
Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re::~Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re ()
Member Function Documentation
cree_instance()
Objet_U * Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re::cree_instance () static
taille_memoire()
unsigned Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re::taille_memoire () const override virtual
Reimplemented from Modele_turbulence_scal_Fluctuation_Temperature_W.
duplique()
int Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re::duplique () const override virtual
Reimplemented from Modele_turbulence_scal_Fluctuation_Temperature_W.
info()
const Type_info * Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re::info () static
get_info()
const Type_info * Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Modele_turbulence_scal_Fluctuation_Temperature_W.
self_cast() [1/2]
Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re & Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re::self_cast (Objet_U & r) static
self_cast() [2/2]
const Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re & Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re::self_cast (const Objet_U & r) static
printOn()
Sortie & Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Modele_turbulence_scal_Fluctuation_Temperature_W.
References Objet_U::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Modele_turbulence_scal_Fluctuation_Temperature_W.
References Modele_turbulence_scal_base::dt_impr_nusselt_, Modele_turbulence_scal_Fluctuation_Temperature_W::eqn, Modele_turbulence_scal_base::readOn(), Objet_U_ptr::typer(), and TRUST_Deriv< _CLASSE_ >::valeur().
completer()
void Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re::completer () override virtual
Complete le modele de turbulence: met a jour des references de l'objet.
Reimplemented from Modele_turbulence_scal_Fluctuation_Temperature_W.
References Modele_turbulence_scal_Fluctuation_Temperature_W::associer_viscosite_turbulente(), Probleme_base::equation(), Equation_base::get_modele(), Modele_turbulence_scal_base::mon_equation_, TRUST_Ref_Objet_U::valeur(), and Modele_turbulence_hyd_base::viscosite_turbulente().
preparer_calcul()
int Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re::preparer_calcul () override virtual
NE FAIT RIEN.
Returns
(int) renvoie toujours 1
Reimplemented from Modele_turbulence_scal_Fluctuation_Temperature_W.
References calculer_diffusivite_turbulente(), Modele_turbulence_scal_base::diffusivite_turbulente_, TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Modele_turbulence_scal_base::preparer_calcul(), and Champ_Don_base::valeurs().
mettre_a_jour()
void Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re::mettre_a_jour (double temps) override virtual
Reimplemented from Modele_turbulence_scal_Fluctuation_Temperature_W.
References calculer_diffusivite_turbulente(), Modele_turbulence_scal_base::diffusivite_turbulente_, TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Schema_Temps_base::faire_un_pas_de_temps_eqn_base(), TRUST_Ref< _CLASSE_ >::valeur(), and Champ_Don_base::valeurs().
Fluctu_Temperature() [1/2]
Champ_Inc_base & Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re::Fluctu_Temperature () inline override virtual
Reimplemented from Modele_turbulence_scal_Fluctuation_Temperature_W.
Fluctu_Temperature() [2/2]
const Champ_Inc_base & Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re::Fluctu_Temperature () const inline override virtual
Reimplemented from Modele_turbulence_scal_Fluctuation_Temperature_W.
equation_Fluctu() [1/2]
Transport_Fluctuation_Temperature_W & Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re::equation_Fluctu () inline override virtual
Reimplemented from Modele_turbulence_scal_Fluctuation_Temperature_W.
References TRUST_Ref< _CLASSE_ >::valeur().
equation_Fluctu() [2/2]
const Transport_Fluctuation_Temperature_W & Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re::equation_Fluctu () const inline override virtual
Reimplemented from Modele_turbulence_scal_Fluctuation_Temperature_W.
References TRUST_Ref< _CLASSE_ >::valeur().
associe_modele_fonction() [1/2]
Modele_Fonc_Bas_Reynolds_Thermique_Base & Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re::associe_modele_fonction () inline
References TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::ajouter().
associe_modele_fonction() [2/2]
const Modele_Fonc_Bas_Reynolds_Thermique_Base & Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re::associe_modele_fonction () const inline
References TRUST_Deriv< _CLASSE_ >::valeur().
calculer_diffusivite_turbulente()
Champ_Fonc_base & Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re::calculer_diffusivite_turbulente () override virtual
Reimplemented from Modele_turbulence_scal_Fluctuation_Temperature_W.
References Modele_Fonc_Bas_Reynolds_Thermique_Base::Calcul_Flambda(), Champ_base::changer_temps(), Milieu_base::diffusivite(), Modele_turbulence_scal_base::diffusivite_turbulente_, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Modele_turbulence_hyd_K_Eps_Bas_Reynolds::eqn_transp_K_Eps(), Probleme_base::equation(), Process::exit(), Equation_base::get_modele(), Transport_K_Eps_base::inconnue(), Modele_turbulence_scal_Fluctuation_Temperature_W::la_viscosite_turbulente, Equation_base::milieu(), Modele_turbulence_scal_base::mon_equation_, TRUSTVect< _TYPE_, _SIZE_ >::size(), Champ_base::temps(), TRUST_Ref_Objet_U::valeur(), Champ_Don_base::valeurs(), Champ_Inc_base::valeurs(), and Fluide_base::viscosite_cinematique().
Referenced by mettre_a_jour(), and preparer_calcul().
set_param()
void Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re::set_param (Param & param) override virtual
Reimplemented from Modele_turbulence_scal_Fluctuation_Temperature_W.
References Param::ajouter_non_std(), and Modele_turbulence_scal_base::set_param().
lire_motcle_non_standard()
int Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
< liste stockant tous les noms de frontiere du domaine
Reimplemented from Modele_turbulence_scal_Fluctuation_Temperature_W.
References Modele_Fonc_Bas_Reynolds_Thermique_Base::discretiser(), Modele_turbulence_scal_base::lire_motcle_non_standard(), Objet_U::que_suis_je(), Motcles::search(), Modele_Fonc_Bas_Reynolds_Thermique_Base::typer_lire_Modele_Fonc_Bas_Reynolds_Thermique(), and TRUST_Ref< _CLASSE_ >::valeur().
get_champ()
const Champ_base & Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re::get_champ (const Motcle & nom) const override virtual
Reimplemented from Modele_turbulence_scal_Fluctuation_Temperature_W.
References Nom::getString(), Modele_turbulence_scal_Fluctuation_Temperature_W::has_champ(), Modele_Fonc_Bas_Reynolds_Thermique_Base::has_champ(), and Objet_U_ptr::non_nul().
has_champ() [1/2]
bool Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re::has_champ (const Motcle & nom, TRUST_Ref< Champ_base * > & ref_champ) const override virtual
Reimplemented from Modele_turbulence_scal_Fluctuation_Temperature_W.
References Modele_turbulence_scal_Fluctuation_Temperature_W::has_champ(), Modele_Fonc_Bas_Reynolds_Thermique_Base::has_champ(), and Objet_U_ptr::non_nul().
has_champ() [2/2]
bool Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re::has_champ (const Motcle & nom) const override virtual
Reimplemented from Modele_turbulence_scal_Fluctuation_Temperature_W.
References Modele_turbulence_scal_Fluctuation_Temperature_W::has_champ(), Modele_Fonc_Bas_Reynolds_Thermique_Base::has_champ(), and Objet_U_ptr::non_nul().
get_noms_champs_postraitables()
void Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re::get_noms_champs_postraitables (Noms & nom, Option opt = NONE) const override virtual
Reimplemented from Modele_turbulence_scal_Fluctuation_Temperature_W.
References Modele_turbulence_scal_Fluctuation_Temperature_W::get_noms_champs_postraitables(), Modele_Fonc_Bas_Reynolds_Thermique_Base::get_noms_champs_postraitables(), and Objet_U_ptr::non_nul().
Member Data Documentation
info_obj
const Type_info Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re::info_obj static