TrioCFD: Equation_rayonnement_base Class Reference
Equation_rayonnement_base Class Reference abstract
#include <Equation_rayonnement_base.h>
Public Member Functions
void associer_fluide (const Fluide_base &)
void associer_milieu_base (const Milieu_base &) override
void associer_modele_rayonnement (const Modele_rayo_semi_transp &)
void associer_pb_base (const Probleme_base &pb) override
void completer () override
const Discretisation_base & discretisation () const
Fluide_base & fluide ()
const Fluide_base & fluide () const
const Type_info * get_info () const override
int impr (Sortie &os) const override
const Champ_Inc_base & inconnue () const override
Champ_Inc_base & inconnue () override
bool initTimeStep (double dt) override
int lire_motcle_non_standard (const Motcle &, Entree &) override
const Milieu_base & milieu () const override
Milieu_base & milieu () override
Modele_rayo_semi_transp & Modele ()
const Modele_rayo_semi_transp & Modele () const
int nombre_d_operateurs () const override
const Operateur & operateur (int) const override
Operateur & operateur (int) override
Public Member Functions inherited from Equation_base
virtual void abortTimeStep ()
virtual void associer_domaine_dis (const Domaine_dis_base &)
virtual void associer_pb_base (const Probleme_base &)
virtual void associer_sch_tps_base (const Schema_Temps_base &)
virtual double calculer_pas_de_temps () const
virtual void completer ()
virtual std::vector< YAML_data > data_a_sauvegarder () const
DoubleTab & derivee_en_temps_conv (DoubleTab &, const DoubleTab &)
virtual DoubleTab & derivee_en_temps_inco (DoubleTab &)
const Discretisation_base & discretisation () const
virtual void discretiser ()
virtual const Motcle & domaine_application () const
virtual Domaine_Cl_dis_base & domaine_Cl_dis ()
virtual const Domaine_Cl_dis_base & domaine_Cl_dis () const
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual void imprimer (Sortie &os) const
virtual bool initTimeStep (double dt)
const Nom & le_nom () const override
int limpr () const
virtual void mettre_a_jour (double temps)
virtual int preparer_calcul ()
Probleme_base & probleme ()
const Probleme_base & probleme () const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Schema_Temps_base & schema_temps ()
const Schema_Temps_base & schema_temps () const
Solveur_Masse_base & solv_masse ()
const Solveur_Masse_base & solv_masse () const
Sources & sources ()
const Sources & sources () const
virtual void valider_iteration ()
virtual void verifie_ch_init_nb_comp (const Champ_Inc_base &ch_ref, const int nb_comp) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Equation_base
virtual Entree & lire_cl (Entree &)
virtual Entree & lire_cond_init (Entree &)
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual Entree & lire_sources (Entree &)
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
virtual int verif_Cl () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
~Equation_rayonnement_base()
Equation_rayonnement_base::~Equation_rayonnement_base () override
Equation_rayonnement_base()
Equation_rayonnement_base::Equation_rayonnement_base ()
Member Function Documentation
info()
const Type_info * Equation_rayonnement_base::info () static
get_info()
const Type_info * Equation_rayonnement_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Equation_base.
Reimplemented in Eq_rayo_semi_transp_VDF, and Eq_rayo_semi_transp_VEF.
self_cast() [1/2]
Equation_rayonnement_base & Equation_rayonnement_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Equation_rayonnement_base & Equation_rayonnement_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Equation_rayonnement_base::printOn (Sortie & s) const override protected virtual
Imprime le type de l'equation sur un flot de sortie.
Parameters
(Sortie& s) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Equation_base.
Reimplemented in Eq_rayo_semi_transp_VDF, and Eq_rayo_semi_transp_VEF.
References Objet_U::que_suis_je().
readOn()
Entree & Equation_rayonnement_base::readOn (Entree & is) override protected virtual
cf Equation_base::readOn(Entree& is)
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Exceptions
solveur pression non defini dans jeu de donnees
Reimplemented from Equation_base.
Reimplemented in Eq_rayo_semi_transp_VDF, and Eq_rayo_semi_transp_VEF.
References Operateur_Diff::associer_diffusivite(), Operateur_base::associer_eqn(), Objet_U::axi, Operateur::completer(), Operateur_Diff::diffusivite(), discretisation(), Process::exit(), fluide(), Fluide_base::has_kappa(), inconnue(), Operateur_Diff::l_op_base(), la_matrice, Fluide_base::longueur_rayo(), Objet_U::que_suis_je(), Equation_base::readOn(), Nom::suffix(), terme_diffusif, and Operateur_Diff::typer().
Referenced by Eq_rayo_semi_transp_VDF::readOn(), and Eq_rayo_semi_transp_VEF::readOn().
set_param()
void Equation_rayonnement_base::set_param (Param & titi) override virtual
Reimplemented from Equation_base.
References Param::ajouter_non_std(), and Param::REQUIRED.
lire_motcle_non_standard()
int Equation_rayonnement_base::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Equation_base.
References Equation_base::lire_cl(), SolveurSys::nommer(), solveur, Objet_U_ptr::typer(), TRUST_Deriv< _CLASSE_ >::valeur(), and Equation_base::verif_Cl().
initTimeStep()
bool Equation_rayonnement_base::initTimeStep (double dt) override virtual
Allocation et initialisation de l'inconnue et des CLs jusqu'a present+dt.
autres initialisations pour les calculs sur le prochain pas de temps : operateurs, solveur_masse->
Returns
(0 en cas d'erreur, 1 sinon)
Reimplemented from Equation_base.
References Equation_base::initTimeStep(), Equation_base::schema_temps(), and Schema_Temps_base::set_dt().
Referenced by Modele_rayo_semi_transp::initTimeStep().
solve()
bool Equation_rayonnement_base::solve () virtual
References resoudre(), and Equation_base::schema_temps().
Referenced by Modele_rayo_semi_transp::iterateTimeStep().
associer_milieu_base()
void Equation_rayonnement_base::associer_milieu_base (const Milieu_base & un_milieu) override virtual
Associe un milieu physique a l'equation.
Parameters
(Milieu_base& un_milieu) le milieu physique a associer a l'equation
Implements Equation_base.
References associer_fluide(), Process::exit(), fluide(), le_fluide, and Objet_U::que_suis_je().
associer_fluide()
void Equation_rayonnement_base::associer_fluide (const Fluide_base & un_fluide) inline
Associe un fluide incompressible semi transparent a l'equation.
Parameters
(Fluide_base& un_fluide) le fluide incompressible semi transparent a associer
References le_fluide.
Referenced by associer_milieu_base(), and Modele_rayo_semi_transp::discretiser().
associer_modele_rayonnement()
void Equation_rayonnement_base::associer_modele_rayonnement (const Modele_rayo_semi_transp & un_modele)
Associe le modele de rayonnement a l'equation de rayonnement.
Parameters
(Modele_rayo_semi_transp& un_modele) le modele de rayonnement associe a l'equation de rayonnement
References le_modele.
Referenced by Modele_rayo_semi_transp::discretiser().
milieu() [1/2]
Milieu_base & Equation_rayonnement_base::milieu () override virtual
Renvoie le milieu physique de l'equation (le Fluide_base upcaste en Milieu_base)
(version const)
Returns
(Milieu_base&) le Fluide_base de l'equation upcaste en Milieu_base
Implements Equation_base.
References Process::exit(), le_fluide, Probleme_U::le_nom(), TRUST_Ref< _CLASSE_ >::non_nul(), Equation_base::probleme(), and TRUST_Ref< _CLASSE_ >::valeur().
milieu() [2/2]
const Milieu_base & Equation_rayonnement_base::milieu () const override virtual
Renvoie le milieu physique de l'equation (le Fluide_base upcaste en Milieu_base)
Returns
(Milieu_base&) le Fluide_base de l'equation upcaste en Milieu_base
Implements Equation_base.
References Process::exit(), le_fluide, Probleme_U::le_nom(), TRUST_Ref< _CLASSE_ >::non_nul(), Equation_base::probleme(), and TRUST_Ref< _CLASSE_ >::valeur().
Modele() [1/2]
const Modele_rayo_semi_transp & Equation_rayonnement_base::Modele () const inline
Renvoie le modele de rayonnement semi transparent Precondition :
Parametre : Signification : Contraintes : Acces : Retour Signification : Contraintes : reference constante Exception : Effets de bord : Postcondition : Postcondition :
References le_modele, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Flux_radiatif_VDF::calculer_flux_radiatif(), Flux_radiatif_VEF::calculer_flux_radiatif(), Eq_rayo_semi_transp_VDF::evaluer_cl_rayonnement(), Eq_rayo_semi_transp_VEF::evaluer_cl_rayonnement(), Eq_rayo_semi_transp_VDF::resoudre(), and Eq_rayo_semi_transp_VEF::resoudre().
Modele() [2/2]
Modele_rayo_semi_transp & Equation_rayonnement_base::Modele () inline
Renvoie le modele de rayonnement semi transparent Precondition :
Parametre : Signification : Contraintes : Acces : Retour Signification : Contraintes : Exception : Effets de bord : Postcondition : Postcondition :
References le_modele, and TRUST_Ref< _CLASSE_ >::valeur().
nombre_d_operateurs()
int Equation_rayonnement_base::nombre_d_operateurs () const override virtual
Renvoie le nombre d'operateurs de l'equation.
Ici 1.
Returns
(int) le nombre d'operateurs de l'equation
Implements Equation_base.
Referenced by operateur().
operateur() [1/2]
const Operateur & Equation_rayonnement_base::operateur (int i) const override virtual
Renvoie l'operateur specifie par son index: renvoie terme_diffusif si i = 0.
exit si i>0
(version const)
Parameters
(int i) l'index de l'operateur a renvoyer
Returns
(Operateur&) l'operateur specifie
Exceptions
l'equation n'a pas plus de 1 operateur
Implements Equation_base.
References Process::exit(), nombre_d_operateurs(), and terme_diffusif.
operateur() [2/2]
Operateur & Equation_rayonnement_base::operateur (int i) override virtual
Renvoie l'operateur specifie par son index: renvoie terme_diffusif si i = 0.
exit si i>0
(version const)
Parameters
(int i) l'index de l'operateur a renvoyer
Returns
(Operateur&) l'operateur specifie
Exceptions
l'equation n'a pas plus de 1 operateur
Implements Equation_base.
References Process::exit(), nombre_d_operateurs(), and terme_diffusif.
inconnue() [1/2]
const Champ_Inc_base & Equation_rayonnement_base::inconnue () const override virtual
Renvoie l'irradiance (champ inconnue de l'equation de rayonnement) (version const)
Returns
(Champ_Inc_base&) le champ inconnue representant l'irradience
Implements Equation_base.
References irradiance_.
Referenced by Source_rayo_semi_transp_VDF_P0_VDF::ajouter(), Source_rayo_semi_transp_VEF_P1NC::ajouter(), Flux_radiatif_VDF::calculer_flux_radiatif(), Flux_radiatif_VEF::calculer_flux_radiatif(), Modele_rayo_semi_transp::put_irradience(), readOn(), Eq_rayo_semi_transp_VDF::resoudre(), and Eq_rayo_semi_transp_VEF::resoudre().
inconnue() [2/2]
Champ_Inc_base & Equation_rayonnement_base::inconnue () override virtual
Renvoie l'irradiance (champ inconnue de l'equation de rayonnement) (version const)
Returns
(Champ_Inc_base&) le champ inconnue representant l'irradience
Implements Equation_base.
References irradiance_.
discretiser()
void Equation_rayonnement_base::discretiser () override virtual
Dicretise l'equation.
Reimplemented from Equation_base.
References Champs_compris_T< FIELD_TYPE >::ajoute_champ(), Equation_base::champs_compris_, discretisation(), Equation_base::discretiser(), Equation_base::domaine_dis(), Champ_Inc_base::fixer_nb_valeurs_temporelles(), Field_base::fixer_unite(), irradiance_, Field_base::nommer(), Equation_base::schema_temps(), and Discret_Thermique::temperature().
fluide() [1/2]
Fluide_base & Equation_rayonnement_base::fluide () inline
renvoie le fluide semi transparent associe a l'equation de rayonnement
Returns
(le fluide associe a l'equation de rayonnement)
References le_fluide, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Source_rayo_semi_transp_VDF_P0_VDF::ajouter(), Source_rayo_semi_transp_VEF_P1NC::ajouter(), Eq_rayo_semi_transp_VDF::assembler_matrice(), Eq_rayo_semi_transp_VEF::assembler_matrice(), associer_milieu_base(), Flux_radiatif_VDF::calculer_flux_radiatif(), Flux_radiatif_VEF::calculer_flux_radiatif(), Eq_rayo_semi_transp_VDF::evaluer_cl_rayonnement(), Eq_rayo_semi_transp_VEF::evaluer_cl_rayonnement(), Eq_rayo_semi_transp_VDF::modifier_matrice(), readOn(), Eq_rayo_semi_transp_VDF::resoudre(), and Eq_rayo_semi_transp_VEF::resoudre().
fluide() [2/2]
const Fluide_base & Equation_rayonnement_base::fluide () const inline
renvoie le fluide semi transparent associe a l'equation de rayonnement
Returns
(le fluide associe a l'equation de rayonnement)
References le_fluide, and TRUST_Ref< _CLASSE_ >::valeur().
impr()
int Equation_rayonnement_base::impr (Sortie & os) const inline override virtual
Imprime les operateurs de l'equation sur un flot de sortie, de facon inconditionnelle.
appelle Operateur_base::impr(os)
Parameters
(Sortie& os) le flot de sortie
Returns
(int) renvoie toujours 1
Reimplemented from Equation_base.
nb_colonnes_tot()
virtual int Equation_rayonnement_base::nb_colonnes_tot () pure virtual
Implemented in Eq_rayo_semi_transp_VDF, and Eq_rayo_semi_transp_VEF.
Referenced by dimensionner_Mat_Bloc_Morse_Sym(), and Mat_Morse_to_Mat_Bloc().
nb_colonnes()
virtual int Equation_rayonnement_base::nb_colonnes () pure virtual
Implemented in Eq_rayo_semi_transp_VDF, and Eq_rayo_semi_transp_VEF.
Referenced by dimensionner_Mat_Bloc_Morse_Sym(), and Mat_Morse_to_Mat_Bloc().
Mat_Morse_to_Mat_Bloc()
void Equation_rayonnement_base::Mat_Morse_to_Mat_Bloc (Matrice & matrice_tmp)
References Matrice_Bloc::get_bloc(), Matrice_Morse::get_coeff(), Matrice_Morse::get_set_coeff(), Matrice_Morse::get_set_tab1(), Matrice_Morse::get_set_tab2(), Matrice_Morse::get_tab1(), Matrice_Morse::get_tab2(), la_matrice, nb_colonnes(), nb_colonnes_tot(), and TRUST_Deriv< _CLASSE_ >::valeur().
dimensionner_Mat_Bloc_Morse_Sym()
void Equation_rayonnement_base::dimensionner_Mat_Bloc_Morse_Sym (Matrice & matrice_tmp)
References Matrice_Bloc::dimensionner(), Matrice_Morse::dimensionner(), Matrice_Bloc::get_bloc(), Matrice_Morse::get_set_tab1(), Matrice_Morse::get_set_tab2(), la_matrice, nb_colonnes(), nb_colonnes_tot(), Objet_U_ptr::typer(), and TRUST_Deriv< _CLASSE_ >::valeur().
discretisation()
const Discretisation_base & Equation_rayonnement_base::discretisation () const
Renvoie la discretisation associee a l'equation.
Returns
(Discretisation_base&) a discretisation associee a l'equation
Exceptions
pas de probleme associe
References le_modele.
Referenced by discretiser(), and readOn().
operateur_gradient() [1/2]
Operateur_Grad & Equation_rayonnement_base::operateur_gradient ()
References gradient.
operateur_gradient() [2/2]
const Operateur_Grad & Equation_rayonnement_base::operateur_gradient () const
References gradient.
typer_op_grad()
virtual void Equation_rayonnement_base::typer_op_grad () pure virtual
Implemented in Eq_rayo_semi_transp_VDF, and Eq_rayo_semi_transp_VEF.
associer_pb_base()
void Equation_rayonnement_base::associer_pb_base (const Probleme_base & pb) override virtual
S'associe au Probleme passe en parametre.
Associe egalement les sources, les operateurs et le solveur de masse a l'equation.
Parameters
(Probleme_base& pb) le probleme auquel l'equation doit s'associer
Reimplemented from Equation_base.
References MorEqn::associer_eqn(), Equation_base::associer_pb_base(), and gradient.
resoudre()
virtual void Equation_rayonnement_base::resoudre (double temps) pure virtual
Implemented in Eq_rayo_semi_transp_VDF, and Eq_rayo_semi_transp_VEF.
Referenced by Pb_Couple_rayo_semi_transp::initialize(), and solve().
assembler_matrice()
virtual void Equation_rayonnement_base::assembler_matrice () pure virtual
Implemented in Eq_rayo_semi_transp_VDF, and Eq_rayo_semi_transp_VEF.
modifier_matrice()
virtual void Equation_rayonnement_base::modifier_matrice () pure virtual
Implemented in Eq_rayo_semi_transp_VDF, and Eq_rayo_semi_transp_VEF.
evaluer_cl_rayonnement()
virtual void Equation_rayonnement_base::evaluer_cl_rayonnement (double temps) pure virtual
Implemented in Eq_rayo_semi_transp_VDF, and Eq_rayo_semi_transp_VEF.
completer()
void Equation_rayonnement_base::completer () override virtual
Complete la construction (initialisation) des objets associes a l'equation.
Complete les sources, associe l'equation a l'inconnue complete les operateurs, complete les conditions aux limites discretisees. Voir les methodes Source_base::completer(), Operateur_base::completer() Domaine_Cl_dis_base::completer() Domaine_Cl_dis_base::completer(const Domaine_dis_base&)
Reimplemented from Equation_base.
Reimplemented in Eq_rayo_semi_transp_VDF, and Eq_rayo_semi_transp_VEF.
References Equation_base::completer().
Referenced by Eq_rayo_semi_transp_VDF::completer(), Eq_rayo_semi_transp_VEF::completer(), and Modele_rayo_semi_transp::preparer_calcul().
Member Data Documentation
info_obj
const Type_info Equation_rayonnement_base::info_obj static
le_fluide
TRUST_Ref< Fluide_base *> Equation_rayonnement_base::le_fluide protected
Referenced by associer_fluide(), associer_milieu_base(), fluide(), and milieu().
le_modele
TRUST_Ref< Modele_rayo_semi_transp *> Equation_rayonnement_base::le_modele protected
Referenced by associer_modele_rayonnement(), discretisation(), and Modele().
terme_diffusif
Operateur_Diff Equation_rayonnement_base::terme_diffusif protected
Referenced by Eq_rayo_semi_transp_VDF::assembler_matrice(), Eq_rayo_semi_transp_VEF::assembler_matrice(), operateur(), and readOn().
irradiance_
TRUST_Deriv< Champ_Inc_base > Equation_rayonnement_base::irradiance_ protected
Referenced by Eq_rayo_semi_transp_VDF::assembler_matrice(), Eq_rayo_semi_transp_VEF::assembler_matrice(), discretiser(), and inconnue().
solveur
SolveurSys Equation_rayonnement_base::solveur protected
Referenced by lire_motcle_non_standard().
la_matrice
Matrice_Morse Equation_rayonnement_base::la_matrice protected
Referenced by Eq_rayo_semi_transp_VDF::assembler_matrice(), Eq_rayo_semi_transp_VEF::assembler_matrice(), dimensionner_Mat_Bloc_Morse_Sym(), Mat_Morse_to_Mat_Bloc(), Eq_rayo_semi_transp_VDF::modifier_matrice(), Eq_rayo_semi_transp_VEF::modifier_matrice(), and readOn().
gradient
Operateur_Grad Equation_rayonnement_base::gradient protected
Referenced by associer_pb_base(), and operateur_gradient().