TrioCFD: Mailler_32_64< _SIZE_ > Class Template Reference
Mailler_32_64< _SIZE_ > Class Template Reference
#include <Mailler.h>
Public Member Functions
const Type_info * get_info () const override
Entree & interpreter_ (Entree &) override
Public Member Functions inherited from Interprete_geometrique_base_32_64< _SIZE_ >
const Type_info * get_info () const override
void mettre_a_jour_sous_domaine (Domaine_t &domaine, int_t &elem, int_t num_premier_elem, int_t nb_elem) const
Public Member Functions inherited from Interprete
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Interprete
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Interprete
static Objet_U & objet (const Nom &)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
template<typename _SIZE_>
class Mailler_32_64< _SIZE_ >
Structure du jeu de donnee (en dimension 2) : Mailler dom { [Epsilon eps] Pave nompave1 { Origine OX OY Longueurs LX LY Nombre_de_Noeuds NX NY } { Bord nom_bord1 X = X0 Y0 <= Y <= Y1 Bord nom_bord2 X = X0 Y1 <= Y <= Y2 Bord nom_bord2 Y = Y0 X1 <= X <= X2 ... } , Pave nompave2 ... } Deux points seront confondus des que la distance entre eux est inferieure a Epsilon.
See also
Interprete Pave, Actuellement le seul tyep d'objet reconnu par TRUST pour mailler, un domaine est l'objet Pave
Member Typedef Documentation
Domaine_t
template<typename _SIZE_ > using Mailler_32_64< _SIZE_ >::Domaine_t = Domaine_32_64<_SIZE_>
Constructor & Destructor Documentation
Mailler_32_64()
template<typename _T_ > Mailler_32_64< _T_ >::Mailler_32_64
~Mailler_32_64()
template<typename _T_ > Mailler_32_64< _T_ >::~Mailler_32_64
Member Function Documentation
cree_instance()
template<typename _T_ > Objet_U * Mailler_32_64< _T_ >::cree_instance static
taille_memoire()
template<typename _T_ > unsigned Mailler_32_64< _T_ >::taille_memoire override virtual
Implements Objet_U.
duplique()
template<typename _T_ > int Mailler_32_64< _T_ >::duplique override virtual
Implements Objet_U.
info()
template<typename _T_ > const Type_info * Mailler_32_64< _T_ >::info static
get_info()
template<typename _T_ > const Type_info * Mailler_32_64< _T_ >::get_info override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Interprete_geometrique_base_32_64< _SIZE_ >.
self_cast() [1/2]
template<typename _T_ > Mailler_32_64< _T_ > & Mailler_32_64< _T_ >::self_cast (Objet_U & r) static
self_cast() [2/2]
template<typename _T_ > const Mailler_32_64< _T_ > & Mailler_32_64< _T_ >::self_cast (const Objet_U & r) static
printOn()
template<typename _SIZE_ > Sortie & Mailler_32_64< _SIZE_ >::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Interprete_geometrique_base_32_64< _SIZE_ >.
References Interprete::printOn().
readOn()
template<typename _SIZE_ > Entree & Mailler_32_64< _SIZE_ >::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Interprete_geometrique_base_32_64< _SIZE_ >.
References Interprete::readOn().
interpreter_()
template<typename _SIZE_ > Entree & Mailler_32_64< _SIZE_ >::interpreter_ (Entree & is) override virtual
Fonction principale de l'interprete Mailler Structure du jeu de donnee (en dimension 2) :
Mailler dom { [Epsilon eps] [objet1] , [objet2] ... } Deux points seront confondus des que la distance entre eux est inferieure a Epsilon.
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree
Exceptions
l'objet a mailler n'est pas du type Domaine_t
accolade ouvrante attendue
accolade fermante ou virgule attendue
Implements Interprete_geometrique_base_32_64< _SIZE_ >.
References Process::exit(), Domaine_32_64< _SIZE_ >::fill_from_list(), Domaine_base::fixer_epsilon(), Domaine_32_64< _SIZE_ >::fixer_premieres_faces_frontiere(), Scatter::init_sequential_domain(), Process::is_parallel(), NettoieNoeuds_32_64< _SIZE_ >::nettoie(), and Scatter::uninit_sequential_domain().
info_obj() [1/2]
const Type_info Mailler_32_64< int >::info_obj ("Mailler" , Mailler_32_64< int >::cree_instance , 1 , Mailler_32_64bases< int >)
info_obj() [2/2]
const Type_info Mailler_32_64< trustIdType >::info_obj ("Mailler" "_64" , Mailler_32_64< trustIdType >::cree_instance , 1 , Mailler_32_64bases< trustIdType >)
Member Data Documentation
info_obj
template<typename _SIZE_ > const Type_info Mailler_32_64< _SIZE_ >::info_obj static