TrioCFD: Terme_Puissance_Thermique_VDF_base Class Reference
Terme_Puissance_Thermique_VDF_base Class Reference
#include <Terme_Puissance_Thermique_VDF_base.h>
Public Member Functions
const Type_info * get_info () const override
int initialiser (double temps) override
virtual void resetTime (double temps) override
Public Member Functions inherited from Terme_Puissance_Thermique
void lire_donnees (Entree &, const Equation_base &eqn)
Public Member Functions inherited from Terme_Source_VDF_base
void completer () override
const Type_info * get_info () const override
Public Member Functions inherited from Source_base
virtual int a_pour_Champ_Fonc (const Motcle &mot, TRUST_Ref< Champ_base * > &ch_ref) const
virtual void associer_champ_rho (const Champ_base &champ_rho)
virtual void completer ()
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
virtual void resetTime (double t)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Terme_Source_VDF_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Terme_Puissance_Thermique_VDF_base() [1/2]
Terme_Puissance_Thermique_VDF_base::Terme_Puissance_Thermique_VDF_base ()
~Terme_Puissance_Thermique_VDF_base()
Terme_Puissance_Thermique_VDF_base::~Terme_Puissance_Thermique_VDF_base () override
Terme_Puissance_Thermique_VDF_base() [2/2]
Terme_Puissance_Thermique_VDF_base::Terme_Puissance_Thermique_VDF_base (const Iterateur_Source_base & iter_base) inline
Member Function Documentation
info()
const Type_info * Terme_Puissance_Thermique_VDF_base::info () static
get_info()
const Type_info * Terme_Puissance_Thermique_VDF_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Source_base.
Reimplemented in Terme_Puissance_Thermique_VDF_Elem.
self_cast() [1/2]
Terme_Puissance_Thermique_VDF_base & Terme_Puissance_Thermique_VDF_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Terme_Puissance_Thermique_VDF_base & Terme_Puissance_Thermique_VDF_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Terme_Puissance_Thermique_VDF_base::printOn (Sortie & os) const override protected virtual
DOES NOTHING - to override in derived classes.
Imprime la source sur un flot de sortie.
Parameters
(Sortie& os) le flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Source_base.
Reimplemented in Terme_Puissance_Thermique_VDF_Elem.
References Objet_U::que_suis_je().
readOn()
Entree & Terme_Puissance_Thermique_VDF_base::readOn (Entree & is) override protected virtual
DOES NOTHING - to override in derived classes.
Lecture d'un terme source sur un flot d'entree.
Parameters
(Entree& is) le flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Source_base.
Reimplemented in Terme_Puissance_Thermique_VDF_Elem.
References TRUST_List< _CLASSE_ >::add(), Champs_compris_T< FIELD_TYPE >::ajoute_champ(), Source_base::champs_compris_, Source_base::champs_don_, MorEqn::equation(), Terme_Puissance_Thermique::la_puissance, Terme_Puissance_Thermique::la_puissance_lu, Terme_Puissance_Thermique::lire_donnees(), Terme_Puissance_Thermique::modify_name_file(), Objet_U_ptr::non_nul(), Source_base::set_description(), Source_base::set_fichier(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by Source_Dirac_VDF_Elem::readOn(), Terme_Puissance_Thermique_QC_VDF_Elem::readOn(), and Terme_Puissance_Thermique_VDF_Elem::readOn().
initialiser()
int Terme_Puissance_Thermique_VDF_base::initialiser (double temps) override virtual
Contrairement aux methodes mettre_a_jour, les methodes initialiser des sources ne peuvent pas dependre de l'exterieur.
(lui-meme peut ne pas etre initialise) Par defaut, mettre_a_jour
Reimplemented from Source_base.
References MorEqn::equation(), Source_base::initialiser(), and Terme_Puissance_Thermique::initialiser_champ_puissance().
resetTime()
virtual void Terme_Puissance_Thermique_VDF_base::resetTime (double t) inline override virtual
DOES NOTHING - to override in derived classes.
Reset current time.
Parameters
(double) new current time to be set.
Reimplemented from Source_base.
References Terme_Puissance_Thermique::resetTime().
associer_domaines()
void Terme_Puissance_Thermique_VDF_base::associer_domaines (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_cl_dis) override virtual
Implements Source_base.
Reimplemented in Terme_Puissance_Thermique_VDF_Elem.
References Iterateur_Source_base::associer_domaines(), and Terme_Source_VDF_base::iter_.
Referenced by Source_Dirac_VDF_Elem::associer_domaines(), Terme_Puissance_Thermique_QC_VDF_Elem::associer_domaines(), and Terme_Puissance_Thermique_VDF_Elem::associer_domaines().
Member Data Documentation
info_obj
const Type_info Terme_Puissance_Thermique_VDF_base::info_obj static