TrioCFD: Energie_cinetique_turbulente Class Reference
Energie_cinetique_turbulente Class Reference
#include <Energie_cinetique_turbulente.h>
Public Member Functions
void discretiser () override
const Type_info * get_info () const override
void mettre_a_jour (double) override
Public Member Functions inherited from Convection_diffusion_turbulence_multiphase
void associer_milieu_base (const Milieu_base &) override
void completer () override
const Motcle & domaine_application () const override
const Type_info * get_info () const override
int impr (Sortie &os) const override
const Champ_Inc_base & inconnue () const override
Champ_Inc_base & inconnue () override
const Milieu_base & milieu () const override
Milieu_base & milieu () override
Public Member Functions inherited from Convection_Diffusion_std
void associer_vitesse (const Champ_base &)
const Type_info * get_info () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
int nombre_d_operateurs () const override
const Operateur & operateur (int) const override
Operateur & operateur (int) override
const Champ_Inc_base & vitesse_transportante () const
Public Member Functions inherited from Equation_base
virtual void abortTimeStep ()
virtual void associer_domaine_dis (const Domaine_dis_base &)
virtual void associer_pb_base (const Probleme_base &)
virtual void associer_sch_tps_base (const Schema_Temps_base &)
virtual double calculer_pas_de_temps () const
virtual void completer ()
virtual std::vector< YAML_data > data_a_sauvegarder () const
DoubleTab & derivee_en_temps_conv (DoubleTab &, const DoubleTab &)
virtual DoubleTab & derivee_en_temps_inco (DoubleTab &)
const Discretisation_base & discretisation () const
virtual void discretiser ()
virtual const Motcle & domaine_application () const
virtual Domaine_Cl_dis_base & domaine_Cl_dis ()
virtual const Domaine_Cl_dis_base & domaine_Cl_dis () const
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual void imprimer (Sortie &os) const
virtual bool initTimeStep (double dt)
const Nom & le_nom () const override
int limpr () const
virtual void mettre_a_jour (double temps)
virtual int preparer_calcul ()
Probleme_base & probleme ()
const Probleme_base & probleme () const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Schema_Temps_base & schema_temps ()
const Schema_Temps_base & schema_temps () const
Solveur_Masse_base & solv_masse ()
const Solveur_Masse_base & solv_masse () const
Sources & sources ()
const Sources & sources () const
virtual void valider_iteration ()
virtual void verifie_ch_init_nb_comp (const Champ_Inc_base &ch_ref, const int nb_comp) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Equation_base
virtual Entree & lire_cl (Entree &)
virtual Entree & lire_cond_init (Entree &)
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual Entree & lire_sources (Entree &)
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
virtual int verif_Cl () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
See also
Conv_Diffusion_std Convection_Diffusion_Temperature Convection_diffusion_turbulence_multiphase
Constructor & Destructor Documentation
Energie_cinetique_turbulente()
Energie_cinetique_turbulente::Energie_cinetique_turbulente ()
~Energie_cinetique_turbulente()
Energie_cinetique_turbulente::~Energie_cinetique_turbulente ()
Member Function Documentation
cree_instance()
Objet_U * Energie_cinetique_turbulente::cree_instance () static
taille_memoire()
unsigned Energie_cinetique_turbulente::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Energie_cinetique_turbulente::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Energie_cinetique_turbulente::info () static
get_info()
const Type_info * Energie_cinetique_turbulente::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Convection_diffusion_turbulence_multiphase.
self_cast() [1/2]
Energie_cinetique_turbulente & Energie_cinetique_turbulente::self_cast (Objet_U & r) static
self_cast() [2/2]
const Energie_cinetique_turbulente & Energie_cinetique_turbulente::self_cast (const Objet_U & r) static
printOn()
Sortie & Energie_cinetique_turbulente::printOn (Sortie & is) const override protected virtual
Simple appel a: Convection_Diffusion_std::printOn(Sortie&)
Parameters
(Sortie& is) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Convection_diffusion_turbulence_multiphase.
References Convection_diffusion_turbulence_multiphase::printOn().
readOn()
Entree & Energie_cinetique_turbulente::readOn (Entree & is) override protected virtual
Verifie si l'equation a une inconnue et un fluide associe et appelle Convection_Diffusion_std::readOn(Entree&).
Parameters
(Entree& is) un flot d'entree
Returns
(Entree& is) le flot d'entree modifie
Reimplemented from Convection_diffusion_turbulence_multiphase.
References Convection_diffusion_turbulence_multiphase::readOn(), Operateur::set_description(), Operateur::set_fichier(), Convection_Diffusion_std::terme_convectif, and Convection_Diffusion_std::terme_diffusif.
set_param()
void Energie_cinetique_turbulente::set_param (Param & titi) override virtual
Reimplemented from Convection_Diffusion_std.
References Param::ajouter(), Param::ajouter_flag(), coef_limit_, limit_k_, and Convection_Diffusion_std::set_param().
discretiser()
void Energie_cinetique_turbulente::discretiser () override virtual
Discretise l'equation.
Type le domaine_Cl_dis, la formatte, l'associe a l'equation. Type le solveur masse, lui associe le domaine discretisee et le domaine des conditions aux limites discretisees.
Reimplemented from Equation_base.
References Champs_compris_T< FIELD_TYPE >::ajoute_champ(), Equation_base::champs_compris_, Equation_base::discretisation(), Equation_base::discretiser(), Discretisation_base::discretiser_champ(), Equation_base::domaine_dis(), Field_base::fixer_nature_du_champ(), Field_base::fixer_nom_compo(), Convection_diffusion_turbulence_multiphase::l_inco_ch, Schema_Temps_base::nb_valeurs_temporelles(), Equation_base::schema_temps(), and Schema_Temps_base::temps_courant().
mettre_a_jour()
void Energie_cinetique_turbulente::mettre_a_jour (double temps) override virtual
La valeur de l'inconnue sur le pas de temps a ete calculee.
Cette methode avance le present jusqu'au temps passe en parametre. Elle met aussi a jour les proprietes du milieu.
Parameters
(double temps) le pas de temps de mise a jour
Reimplemented from Equation_base.
References coef_limit_, Objet_U::dimension, Equation_base::discretisation(), Equation_base::domaine_dis(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Convection_diffusion_turbulence_multiphase::inconnue(), limit_k_, TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Equation_base::mettre_a_jour(), Champ_Inc_base::passe(), Equation_base::probleme(), Equation_base::schema_temps(), Champ_Inc_base::valeurs(), and Navier_Stokes_std::vitesse().
diffusivite_pour_transport()
const Champ_Don_base & Energie_cinetique_turbulente::diffusivite_pour_transport () const override virtual
Reimplemented from Convection_Diffusion_std.
References Convection_diffusion_turbulence_multiphase::milieu().
diffusivite_pour_pas_de_temps()
const Champ_base & Energie_cinetique_turbulente::diffusivite_pour_pas_de_temps () const override virtual
Reimplemented from Convection_Diffusion_std.
References Convection_diffusion_turbulence_multiphase::milieu().
calculer_alpha_rho_k()
void Energie_cinetique_turbulente::calculer_alpha_rho_k (const Objet_U & obj, DoubleTab & val, DoubleTab & bval, tabs_t & deriv) static
References TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Equation_base::inconnue(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Champ_Inc_base::valeur_aux_bords(), and Champ_Inc_base::valeurs().
Referenced by get_fonc_champ_conserve().
get_fonc_champ_conserve()
std::pair< std::string, fonc_calc_t > Energie_cinetique_turbulente::get_fonc_champ_conserve () const inline override virtual
Reimplemented from Equation_base.
References calculer_alpha_rho_k().
Member Data Documentation
info_obj
const Type_info Energie_cinetique_turbulente::info_obj static
coef_limit_
double Energie_cinetique_turbulente::coef_limit_ = -1 protected
Referenced by mettre_a_jour(), and set_param().
limit_k_
int Energie_cinetique_turbulente::limit_k_ = 0 protected
Referenced by mettre_a_jour(), and set_param().