TrioCFD: FT_Field Class Reference
FT_Field Class Reference
#include <FT_Field.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
~FT_Field()
FT_Field::~FT_Field ()
FT_Field()
FT_Field::FT_Field ()
Member Function Documentation
cree_instance()
Objet_U * FT_Field::cree_instance () static
taille_memoire()
unsigned FT_Field::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int FT_Field::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * FT_Field::info () static
get_info()
const Type_info * FT_Field::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
FT_Field & FT_Field::self_cast (Objet_U & r) static
self_cast() [2/2]
const FT_Field & FT_Field::self_cast (const Objet_U & r) static
printOn()
Sortie & FT_Field::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
readOn()
Entree & FT_Field::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
References Param::ajouter(), Gamma_inf_, Param::lire_avec_accolades(), Objet_U::que_suis_je(), R_, sigma0_, and T_.
initialize()
void FT_Field::initialize (const Maillage_FT_IJK & mesh, const DoubleTab & centre_mass)
References Maillage_FT_IJK::compo_connexe_facettes(), Maillage_FT_Disc::desc_facettes(), Desc_Structure_FT::echange_espace_virtuel(), Maillage_FT_Disc::facettes(), FT_field_Array_, FT_field_Array_sommets_, Maillage_FT_Disc::get_update_surface_facettes(), Process::mp_sum(), Maillage_FT_Disc::nb_facettes(), norme(), TRUSTArray< _TYPE_, _SIZE_ >::resize(), Maillage_FT_Disc::sommets(), update_Field_sommets(), and Point3D::x.
Referenced by IJK_Interfaces::initialize().
update_gradient_laplacien_FT()
void FT_Field::update_gradient_laplacien_FT (const Maillage_FT_IJK & mesh)
References FT_field_Array_, Grad_FT_field_Array_, Laplacian_FT_field_Array_, Operator_FT_Disc::Operator_Laplacian_FT_element(), and OpFTDisc_.
Referenced by avancer_en_temps(), and Maillage_FT_IJK::update_gradient_laplacien_Surfactant().
update_sigma_and_interfacial_source_term_sommet()
DoubleTab FT_Field::update_sigma_and_interfacial_source_term_sommet (const Maillage_FT_IJK & mesh, const Domaine_IJK & splitting, bool compute_interfacial_source, bool use_tryggvason_formulation)
References calculer_volume_bulles(), Maillage_FT_IJK::compo_connexe_facettes(), Operator_FT_Disc::Compute_interfaciale_source(), Maillage_FT_Disc::desc_facettes(), Desc_Structure_FT::echange_espace_virtuel(), Maillage_FT_Disc::facette_virtuelle(), Maillage_FT_Disc::facettes(), FT_field_Array_, Domaine_IJK::get_domain_length(), interfacial_source_term_sommet_, Maillage_FT_Disc::nb_facettes(), Maillage_FT_Disc::nb_sommets(), OpFTDisc_, R_, TRUSTArray< _TYPE_, _SIZE_ >::resize(), sigma0_, sigma_facettes_, sigma_sommets_, Maillage_FT_Disc::sommets(), T_, update_Field_sommets(), and Point3D::x.
Referenced by Maillage_FT_IJK::update_sigma_and_interfacial_source_term_sommet().
dimensionner_remaillage_FT_Field()
void FT_Field::dimensionner_remaillage_FT_Field (Maillage_FT_IJK & mesh, const ArrOfIntFT & table_old_new)
sauvegarder_triangle()
void FT_Field::sauvegarder_triangle (const Maillage_FT_IJK & mesh, const int i, const int avant_apres_remaillage)
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), and TRUSTTab< _TYPE_, _SIZE_ >::resize().
Referenced by Maillage_FT_IJK::deplacer_sommets(), and Remaillage_FT_IJK::supprimer_petites_aretes().
echanger_triangles()
void FT_Field::echanger_triangles (Maillage_FT_IJK & mesh)
remailler_FT_Field()
void FT_Field::remailler_FT_Field (Maillage_FT_IJK & mesh)
References Calculate_Facette_Intersection_Area(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Process::exit(), Process::Journal(), removeDuplicates(), TRUSTArray< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and triangleArea3D().
Referenced by Maillage_FT_IJK::deplacer_sommets(), and Remaillage_FT_IJK::supprimer_petites_aretes().
check_conservation()
ArrOfDouble FT_Field::check_conservation (const Maillage_FT_IJK & mesh)
References Maillage_FT_IJK::compo_connexe_facettes(), Maillage_FT_Disc::facette_virtuelle(), FT_field_Array_, Maillage_FT_Disc::get_update_surface_facettes(), Process::mp_max(), Process::mp_sum(), Maillage_FT_Disc::nb_facettes(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by Remaillage_FT_IJK::barycentrer_lisser_systematique_ijk(), correction_conservation_globale(), Remaillage_FT_IJK::remaillage_local_interface(), and IJK_Interfaces::transporter_maillage_deformation().
correction_conservation_globale()
void FT_Field::correction_conservation_globale (const Maillage_FT_IJK & mesh, const ArrOfDouble & surfactant_avant_remaillage, const ArrOfDouble & surfactant_apres_remaillage)
References check_conservation(), Maillage_FT_IJK::compo_connexe_facettes(), Maillage_FT_Disc::facette_virtuelle(), FT_field_Array_, Maillage_FT_Disc::get_surface_facettes(), Process::mp_max(), Process::mp_sum(), Maillage_FT_Disc::nb_facettes(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by Remaillage_FT_IJK::barycentrer_lisser_systematique_ijk(), Remaillage_FT_IJK::remaillage_local_interface(), and IJK_Interfaces::transporter_maillage_deformation().
avancer_en_temps()
void FT_Field::avancer_en_temps (const Maillage_FT_IJK & mesh, const double time_step)
References Maillage_FT_Disc::desc_facettes(), Desc_Structure_FT::echange_espace_virtuel(), Process::exit(), Maillage_FT_Disc::facette_virtuelle(), FT_field_Array_, Laplacian_FT_field_Array_, passer_variable_extensive(), passer_variable_intensive(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and update_gradient_laplacien_FT().
Referenced by IJK_Interfaces::transporter_maillage_deformation().
passer_variable_extensive()
void FT_Field::passer_variable_extensive (const Maillage_FT_IJK & mesh)
References Maillage_FT_Disc::desc_facettes(), Desc_Structure_FT::echange_espace_virtuel(), Maillage_FT_Disc::facette_virtuelle(), FT_field_Array_, Maillage_FT_Disc::get_update_surface_facettes(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by avancer_en_temps(), Remaillage_FT_IJK::barycentrer_lisser_apres_remaillage(), Remaillage_FT_IJK::barycentrer_lisser_systematique_ijk(), Remaillage_FT_IJK::remaillage_local_interface(), and IJK_Interfaces::transporter_maillage_deformation().
passer_variable_intensive()
void FT_Field::passer_variable_intensive (const Maillage_FT_IJK & mesh)
References Maillage_FT_Disc::desc_facettes(), Desc_Structure_FT::echange_espace_virtuel(), Maillage_FT_Disc::facette_virtuelle(), FT_field_Array_, Maillage_FT_Disc::get_update_surface_facettes(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by avancer_en_temps(), Remaillage_FT_IJK::barycentrer_lisser_apres_remaillage(), Remaillage_FT_IJK::barycentrer_lisser_systematique_ijk(), Remaillage_FT_IJK::remaillage_local_interface(), and IJK_Interfaces::transporter_maillage_deformation().
preparer_tableau_avant_transport()
void FT_Field::preparer_tableau_avant_transport ()
update_tableau_apres_transport()
void FT_Field::update_tableau_apres_transport ()
nettoyer_espace_virtuel_facette()
void FT_Field::nettoyer_espace_virtuel_facette (const Maillage_FT_IJK & mesh)
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Maillage_FT_Disc::facette_virtuelle(), Maillage_FT_Disc::facettes(), FT_field_Array_, and TRUSTArray< _TYPE_, _SIZE_ >::resize().
set_field_facettes()
void FT_Field::set_field_facettes (ArrOfDouble field)
set_field_sommets()
void FT_Field::set_field_sommets (ArrOfDouble field)
update_Field_sommets()
void FT_Field::update_Field_sommets (const Maillage_FT_IJK & FTmesh, const ArrOfDouble & Field_facettes, ArrOfDouble & field_sommet)
References Desc_Structure_FT::collecter_espace_virtuel(), Maillage_FT_Disc::desc_sommets(), Desc_Structure_FT::echange_espace_virtuel(), MD_Vector_tools::EV_SOMME, Maillage_FT_Disc::facette_virtuelle(), Maillage_FT_Disc::facettes(), Maillage_FT_Disc::get_surface_facettes(), Maillage_FT_Disc::nb_facettes(), Maillage_FT_Disc::nb_sommets(), TRUSTArray< _TYPE_, _SIZE_ >::resize(), and Maillage_FT_Disc::sommet_virtuel().
Referenced by initialize(), and update_sigma_and_interfacial_source_term_sommet().
exchange_data()
void FT_Field::exchange_data (int pe_send_, int pe_recv_, const Maillage_FT_IJK & mesh, const DoubleTab & liste_sommets_avant_deplacement, const DoubleTab & liste_sommets_apres_deplacement, const ArrOfInt & compo_connexe_sommets_deplace)
References Maillage_FT_IJK::compo_connexe_facettes(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Maillage_FT_Disc::facette_virtuelle(), Maillage_FT_Disc::facettes(), FT_field_Array_, Maillage_FT_Disc::get_update_normale_facettes(), is_compo_in_proc(), Process::me(), Maillage_FT_Disc::nb_facettes(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), sauv_num_pe_echange(), and Maillage_FT_Disc::sommets().
Referenced by completer_compo_connexe_partielle().
champ_sommet_from_facettes()
void FT_Field::champ_sommet_from_facettes (const ArrOfInt & compo_connexe_facettes, const Maillage_FT_IJK & mesh)
References Desc_Structure_FT::collecter_espace_virtuel(), Maillage_FT_Disc::desc_sommets(), MD_Vector_tools::EV_MAX, Maillage_FT_Disc::facette_virtuelle(), Maillage_FT_Disc::facettes(), Maillage_FT_Disc::nb_sommets(), TRUSTArray< _TYPE_, _SIZE_ >::resize(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by completer_compo_connexe_partielle(), Maillage_FT_IJK::deplacer_sommets(), and Remaillage_FT_IJK::supprimer_petites_aretes().
exchange_compo_connexe()
void FT_Field::exchange_compo_connexe (int pe_send_, int pe_recv_, const Maillage_FT_IJK & mesh)
References Maillage_FT_IJK::compo_connexe_facettes(), Maillage_FT_Disc::facette_virtuelle(), Process::me(), Maillage_FT_Disc::nb_facettes(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::resize(), sauv_num_pe_echange(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by completer_compo_connexe_partielle().
update_FT_Field_local_from_full_compo()
void FT_Field::update_FT_Field_local_from_full_compo (const Maillage_FT_IJK & mesh)
References FT_field_Array_, and Maillage_FT_Disc::nb_facettes().
Referenced by Maillage_FT_IJK::deplacer_sommets(), and Remaillage_FT_IJK::supprimer_petites_aretes().
completer_compo_connexe_partielle()
void FT_Field::completer_compo_connexe_partielle (const Maillage_FT_IJK & mesh, const Domaine_IJK & splitting, const DoubleTab & liste_sommets_apres_deplacement, const DoubleTab & liste_sommets_avant_deplacement, const ArrOfInt & compo_connexe_sommets_deplace)
References Process::barrier(), champ_sommet_from_facettes(), Maillage_FT_IJK::compo_connexe_facettes(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), exchange_compo_connexe(), exchange_data(), Process::exit(), Domaine_IJK::get_local_slice_index(), Domaine_IJK::get_nprocessor_per_direction(), Domaine_IJK::get_processor_by_ijk(), Process::mp_max(), Maillage_FT_Disc::nb_facettes(), Maillage_FT_Disc::nb_sommets(), norme(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and sortAndTrackIndices().
Referenced by Maillage_FT_IJK::deplacer_sommets(), and Remaillage_FT_IJK::supprimer_petites_aretes().
sauv_num_pe_echange()
bool FT_Field::sauv_num_pe_echange (int pe)
References TRUSTArray< _TYPE_, _SIZE_ >::resize(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by exchange_compo_connexe(), and exchange_data().
is_compo_in_proc()
bool FT_Field::is_compo_in_proc (const int compo_connexe, const int pe_send)
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Process::exit(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by exchange_data().
calculer_volume_bulles()
void FT_Field::calculer_volume_bulles (ArrOfDouble & volumes, DoubleTab & centre_gravite, const Maillage_FT_IJK & mesh) const
References Maillage_FT_IJK::compo_connexe_facettes(), Process::mp_max(), Maillage_FT_Disc::nb_facettes(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by update_sigma_and_interfacial_source_term_sommet().
sortAndTrackIndices()
void FT_Field::sortAndTrackIndices (const std::vector< double > & arr, std::vector< size_t > & indices)
Referenced by completer_compo_connexe_partielle().
det()
double FT_Field::det (const Point2D & a, const Point2D & b, const Point2D & c)
References Point2D::x, and Point2D::y.
Referenced by isPointInTriangle().
isPointInTriangle()
bool FT_Field::isPointInTriangle (const Point2D & pt, const Point2D & v1, const Point2D & v2, const Point2D & v3)
References det().
Referenced by intersectionArea().
Calculate_Facette_Intersection_Area()
void FT_Field::Calculate_Facette_Intersection_Area (DoubleTab & Surface_fa7init, DoubleTab & Surface_fa7fin, DoubleTab & Surface_intersection, vector< Point3D > points_fa7_originale, vector< Point3D > points_fa7_finale, IntTab points_triangle_originaux, IntTab points_triangle_finaux, IntTab & normale_triangle_originaux, IntTab & normale_triangle_finaux)
References computeCentroid(), crossProduct(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), intersectionArea(), Main_2D_plane_eigenvectors(), orientation_triangle(), projectPointToPlane(), triangleArea(), Point2D::x, and Point2D::y.
Referenced by remailler_FT_Field().
lineIntersection()
bool FT_Field::lineIntersection (const Point2D & a, const Point2D & b, const Point2D & c, const Point2D & d, Point2D & intersection)
References Point2D::x, and Point2D::y.
Referenced by intersectionArea().
polygonArea()
double FT_Field::polygonArea (const std::vector< Point2D > & vertices)
Referenced by intersectionArea().
intersectionArea()
double FT_Field::intersectionArea (Point2D t1[3], Point2D t2[3])
References intersectionArea(), isPointInTriangle(), lineIntersection(), polygonArea(), Point2D::x, and Point2D::y.
Referenced by Calculate_Facette_Intersection_Area(), and intersectionArea().
norme()
double FT_Field::norme (const Point3D & pt)
References Point3D::x, Point3D::y, and Point3D::z.
Referenced by completer_compo_connexe_partielle(), and initialize().
removeDuplicates()
std::vector< Point3D > FT_Field::removeDuplicates (std::vector< Point3D > & points)
Referenced by remailler_FT_Field().
computeCentroid()
Point3D FT_Field::computeCentroid (const vector< Point3D > & points)
References Point3D::x, Point3D::y, and Point3D::z.
Referenced by Calculate_Facette_Intersection_Area(), and Main_2D_plane_eigenvectors().
computeCovarianceMatrix()
void FT_Field::computeCovarianceMatrix (const vector< Point3D > & points, const Point3D & centroid, double cov[3][3])
References Point3D::x, Point3D::y, and Point3D::z.
Referenced by Main_2D_plane_eigenvectors().
powerIteration()
void FT_Field::powerIteration (const double cov[3][3], double eigenVector[3], double & eigenValue)
Referenced by Main_2D_plane_eigenvectors().
projectPointToPlane()
Point2D FT_Field::projectPointToPlane (const Point3D & point, const Point3D & centroid, const array< double, 3 > & eigenVector1, const array< double, 3 > & eigenVector2)
References Point2D::x, Point3D::x, Point2D::y, Point3D::y, and Point3D::z.
Referenced by Calculate_Facette_Intersection_Area().
orientation_triangle()
int FT_Field::orientation_triangle (const Point3D & normale, const array< double, 3 > & eigenVector1, const array< double, 3 > & eigenVector2)
References crossProduct(), and scalarProduct().
Referenced by Calculate_Facette_Intersection_Area().
Main_2D_plane_eigenvectors()
vector< pair< double, array< double, 3 > > > FT_Field::Main_2D_plane_eigenvectors (vector< Point3D > points)
References computeCentroid(), computeCovarianceMatrix(), and powerIteration().
Referenced by Calculate_Facette_Intersection_Area().
triangleArea()
double FT_Field::triangleArea (const Point2D & p1, const Point2D & p2, const Point2D & p3)
References Point2D::x, and Point2D::y.
Referenced by Calculate_Facette_Intersection_Area().
crossProduct()
Point3D FT_Field::crossProduct (const Point3D & u, const Point3D & v)
References Point3D::x, Point3D::y, and Point3D::z.
Referenced by Calculate_Facette_Intersection_Area(), calculer_normale_apres_deplacement(), orientation_triangle(), and triangleArea3D().
scalarProduct()
double FT_Field::scalarProduct (const Point3D & u, const Point3D & v)
References Point3D::x, Point3D::y, and Point3D::z.
Referenced by calculer_normale_apres_deplacement(), and orientation_triangle().
magnitude()
double FT_Field::magnitude (const Point3D & v)
References Point3D::x, Point3D::y, and Point3D::z.
Referenced by triangleArea3D().
triangleArea3D()
double FT_Field::triangleArea3D (const Point3D & A, const Point3D & B, const Point3D & C)
References crossProduct(), magnitude(), Point3D::x, Point3D::y, and Point3D::z.
Referenced by remailler_FT_Field().
calculer_normale_apres_deplacement()
Point3D FT_Field::calculer_normale_apres_deplacement (const int fa, const int somfa7, const Vecteur3 pos_apres_dep)
References crossProduct(), and scalarProduct().
Referenced by Maillage_FT_IJK::deplacer_sommets(), and Remaillage_FT_IJK::supprimer_petites_aretes().
copy_FT_Field()
void FT_Field::copy_FT_Field (FT_Field copy) inline
References TRUSTArray< _TYPE_, _SIZE_ >::copy_array(), FT_field_Array_, FT_field_Array_sommets_, Grad_FT_field_Array_, interfacial_source_term_sommet_, Laplacian_FT_field_Array_, OpFTDisc_, and sigma_facettes_.
Referenced by Maillage_FT_IJK::recopie().
inject_array()
void FT_Field::inject_array (const FT_Field & source, int nb_elements, int first_element_dest, int first_element_source) inline
References FT_field_Array_, and TRUSTArray< _TYPE_, _SIZE_ >::inject_array().
Referenced by Maillage_FT_IJK::ajouter_maillage_IJK().
resize_array()
void FT_Field::resize_array (int index) inline
References FT_field_Array_, and TRUSTArray< _TYPE_, _SIZE_ >::resize_array().
Referenced by Maillage_FT_IJK::ajouter_maillage_IJK(), Maillage_FT_IJK::creer_facettes_virtuelles(), Remaillage_FT_IJK::diviser_grandes_aretes(), Maillage_FT_IJK::lire_maillage_ft_dans_lata(), and Maillage_FT_IJK::nettoyer_maillage().
resize()
void FT_Field::resize (int index) inline
References FT_field_Array_, and TRUSTArray< _TYPE_, _SIZE_ >::resize().
Referenced by Maillage_FT_IJK::update_surfactant_apres_transport().
operator()()
double & FT_Field::operator() (int index) inline
References FT_field_Array_.
operator[]()
double & FT_Field::operator[] (int index) inline
References FT_field_Array_.
echange_espace_virtuel()
void FT_Field::echange_espace_virtuel (const Maillage_FT_Disc & mesh)
References Maillage_FT_Disc::desc_facettes(), Desc_Structure_FT::echange_espace_virtuel(), and FT_field_Array_.
Referenced by Maillage_FT_IJK::creer_facettes_virtuelles(), Maillage_FT_IJK::deplacer_sommets(), Remaillage_FT_IJK::diviser_grandes_aretes(), Remaillage_FT_IJK::remaillage_local_interface(), Remaillage_FT_IJK::supprimer_petites_aretes(), and Maillage_FT_IJK::update_surfactant_apres_transport().
size()
int FT_Field::size () const inline
References FT_field_Array_, and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
size_array()
int FT_Field::size_array () const inline
References FT_field_Array_, and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by Maillage_FT_IJK::check_mesh().
size_sommets()
int FT_Field::size_sommets () const inline
References FT_field_Array_sommets_, and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
get_only_remaillage()
int FT_Field::get_only_remaillage () const inline
Referenced by Remaillage_FT_IJK::remaillage_local_interface(), and IJK_Interfaces::remailler_interface().
get_OpFTDisc()
Operator_FT_Disc FT_Field::get_OpFTDisc () const inline
References OpFTDisc_.
get_FT_field_Array()
ArrOfDouble FT_Field::get_FT_field_Array () const inline
References FT_field_Array_.
Referenced by IJK_Interfaces::calculer_surfactant(), and IJK_Interfaces::get_IJK_field().
get_disable_surfactant()
bool FT_Field::get_disable_surfactant () const inline
Referenced by Maillage_FT_IJK::ajouter_maillage_IJK(), Remaillage_FT_IJK::barycentrer_lisser_apres_remaillage(), Remaillage_FT_IJK::barycentrer_lisser_systematique_ijk(), IJK_Interfaces::calculer_phi_repuls_par_compo(), IJK_Interfaces::calculer_phi_repuls_sommet(), IJK_Interfaces::calculer_surfactant(), Maillage_FT_IJK::check_mesh(), Maillage_FT_IJK::corriger_proprietaires_facettes(), Maillage_FT_IJK::creer_facettes_virtuelles(), Maillage_FT_IJK::deplacer_sommets(), Remaillage_FT_IJK::diviser_grandes_aretes(), IJK_Interfaces::dupliquer_bulle_perio(), Maillage_FT_IJK::lire_maillage_ft_dans_lata(), Maillage_FT_IJK::nettoyer_maillage(), IJK_Interfaces::parcourir_maillage(), Maillage_FT_IJK::parcourir_maillage(), Remaillage_FT_IJK::remaillage_local_interface(), Remaillage_FT_IJK::supprimer_petites_aretes(), IJK_Interfaces::transporter_maillage_deformation(), IJK_Interfaces::transporter_maillage_remaillage(), and Maillage_FT_IJK::update_sigma_and_interfacial_source_term_sommet().
get_disable_marangoni_source_term()
int FT_Field::get_disable_marangoni_source_term () const inline
Referenced by IJK_Interfaces::ajouter_terme_source_interfaces(), and Maillage_FT_IJK::update_sigma_and_interfacial_source_term_sommet().
set_disable_surfactant()
void FT_Field::set_disable_surfactant (bool disable_surfactant) inline
Referenced by IJK_Interfaces::dupliquer_bulle_perio().
get_compo_connexe_sommets()
ArrOfInt FT_Field::get_compo_connexe_sommets () const inline
Referenced by Maillage_FT_IJK::deplacer_sommets(), and Remaillage_FT_IJK::supprimer_petites_aretes().
get_FT_field_Array_non_const()
ArrOfDouble FT_Field::get_FT_field_Array_non_const () inline
References FT_field_Array_.
get_FT_field_Array_sommets()
ArrOfDouble FT_Field::get_FT_field_Array_sommets () const inline
References FT_field_Array_sommets_.
get_Grad_FT_field_Array()
ArrOfDouble FT_Field::get_Grad_FT_field_Array (int dir) const inline
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Grad_FT_field_Array_, and TRUSTArray< _TYPE_, _SIZE_ >::resize().
Referenced by IJK_Interfaces::get_IJK_field().
get_sigma_facettes()
ArrOfDouble FT_Field::get_sigma_facettes () const inline
References sigma_facettes_.
get_sigma_sommets()
ArrOfDouble FT_Field::get_sigma_sommets () const inline
References sigma_sommets_.
Referenced by IJK_Interfaces::calculer_phi_repuls_sommet(), and IJK_Interfaces::get_IJK_field().
get_interfacial_source_term_sommets() [1/2]
DoubleTab FT_Field::get_interfacial_source_term_sommets () const inline
References interfacial_source_term_sommet_.
Referenced by IJK_Interfaces::get_IJK_field().
get_interfacial_source_term_sommets() [2/2]
ArrOfDouble FT_Field::get_interfacial_source_term_sommets (int dir) const inline
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), interfacial_source_term_sommet_, and TRUSTArray< _TYPE_, _SIZE_ >::resize().
get_interfacial_source_term_sommets_non_const()
ArrOfDouble FT_Field::get_interfacial_source_term_sommets_non_const (int dir) inline
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), interfacial_source_term_sommet_, and TRUSTArray< _TYPE_, _SIZE_ >::resize().
get_Laplacian_FT_field_Array()
ArrOfDouble FT_Field::get_Laplacian_FT_field_Array () const inline
References Laplacian_FT_field_Array_.
Referenced by IJK_Interfaces::get_IJK_field().
get_sommet_bouge()
DoubleTab FT_Field::get_sommet_bouge () const inline
get_facettes_sommets_full_compo_non_const()
DoubleTab & FT_Field::get_facettes_sommets_full_compo_non_const () inline
Referenced by Maillage_FT_IJK::deplacer_sommets(), and Remaillage_FT_IJK::supprimer_petites_aretes().
get_liste_sommets_et_deplacements_non_const()
DoubleTab & FT_Field::get_liste_sommets_et_deplacements_non_const () inline
Referenced by Maillage_FT_IJK::deplacer_sommets(), and Remaillage_FT_IJK::supprimer_petites_aretes().
get_sorted_index()
const ArrOfInt FT_Field::get_sorted_index () inline
Referenced by Maillage_FT_IJK::deplacer_sommets(), and Remaillage_FT_IJK::supprimer_petites_aretes().
get_nb_triangle_finaux()
int FT_Field::get_nb_triangle_finaux () inline
References TRUSTTab< _TYPE_, _SIZE_ >::dimension().
get_nb_triangle_initiaux()
int FT_Field::get_nb_triangle_initiaux () inline
References TRUSTTab< _TYPE_, _SIZE_ >::dimension().
reinit_remeshing_table()
void FT_Field::reinit_remeshing_table () inline
References TRUSTTab< _TYPE_, _SIZE_ >::resize().
Referenced by Maillage_FT_IJK::deplacer_sommets(), and Remaillage_FT_IJK::supprimer_petites_aretes().
set_tolerance_point_identique()
void FT_Field::set_tolerance_point_identique (double longueur_cara_fa7) inline
References Point2D::tol, and Point3D::tol.
Referenced by Maillage_FT_IJK::deplacer_sommets(), and Remaillage_FT_IJK::supprimer_petites_aretes().
get_tolerance_point_identique()
double FT_Field::get_tolerance_point_identique () inline
References Point3D::tol.
Member Data Documentation
info_obj
const Type_info FT_Field::info_obj static
FT_field_Array_
ArrOfDouble FT_Field::FT_field_Array_
Referenced by avancer_en_temps(), check_conservation(), copy_FT_Field(), correction_conservation_globale(), echange_espace_virtuel(), exchange_data(), get_FT_field_Array(), get_FT_field_Array_non_const(), initialize(), inject_array(), nettoyer_espace_virtuel_facette(), operator()(), operator[](), passer_variable_extensive(), passer_variable_intensive(), resize(), resize_array(), size(), size_array(), update_FT_Field_local_from_full_compo(), update_gradient_laplacien_FT(), and update_sigma_and_interfacial_source_term_sommet().
FT_field_Array_sommets_
ArrOfDouble FT_Field::FT_field_Array_sommets_
Referenced by copy_FT_Field(), get_FT_field_Array_sommets(), initialize(), and size_sommets().
Grad_FT_field_Array_
DoubleTab FT_Field::Grad_FT_field_Array_
Referenced by copy_FT_Field(), get_Grad_FT_field_Array(), and update_gradient_laplacien_FT().
Laplacian_FT_field_Array_
ArrOfDouble FT_Field::Laplacian_FT_field_Array_
Referenced by avancer_en_temps(), copy_FT_Field(), get_Laplacian_FT_field_Array(), and update_gradient_laplacien_FT().
OpFTDisc_
Operator_FT_Disc FT_Field::OpFTDisc_
Referenced by copy_FT_Field(), get_OpFTDisc(), update_gradient_laplacien_FT(), and update_sigma_and_interfacial_source_term_sommet().
sigma0_
double FT_Field::sigma0_
Referenced by readOn(), and update_sigma_and_interfacial_source_term_sommet().
R_
double FT_Field::R_
Referenced by readOn(), and update_sigma_and_interfacial_source_term_sommet().
T_
double FT_Field::T_
Referenced by readOn(), and update_sigma_and_interfacial_source_term_sommet().
Gamma_inf_
double FT_Field::Gamma_inf_
Referenced by readOn().
sigma_sommets_
ArrOfDouble FT_Field::sigma_sommets_
Referenced by get_sigma_sommets(), and update_sigma_and_interfacial_source_term_sommet().
sigma_facettes_
ArrOfDouble FT_Field::sigma_facettes_
Referenced by copy_FT_Field(), get_sigma_facettes(), and update_sigma_and_interfacial_source_term_sommet().
interfacial_source_term_sommet_
DoubleTab FT_Field::interfacial_source_term_sommet_
Referenced by copy_FT_Field(), get_interfacial_source_term_sommets(), get_interfacial_source_term_sommets_non_const(), and update_sigma_and_interfacial_source_term_sommet().