TrioCFD: Force_ph Class Reference
Force_ph Class Reference
#include <Force_ph.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Force_ph()
Force_ph::Force_ph ()
~Force_ph()
Force_ph::~Force_ph ()
Member Function Documentation
cree_instance()
Objet_U * Force_ph::cree_instance () static
taille_memoire()
unsigned Force_ph::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Force_ph::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Force_ph::info () static
get_info()
const Type_info * Force_ph::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
Force_ph & Force_ph::self_cast (Objet_U & r) static
self_cast() [2/2]
const Force_ph & Force_ph::self_cast (const Objet_U & r) static
printOn()
Sortie & Force_ph::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
References Objet_U::printOn().
readOn()
Entree & Force_ph::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
References Objet_U::readOn().
initialise()
void Force_ph::initialise (int nproc_tot, int ni, int nj, int nk, int nl, int nm, int nn, double Lx, double Ly, double Lz, double Ox, double Oy, double Oz, int momin, int momax, double kmin, double kmax, std::string nom_fichier, const Domaine_IJK & splitting, int a_i_offset, int a_j_offset, int a_k_offset)
References IJK_Field_vector< T, N >::nommer().
Referenced by init_forcage_THI::compute_initial_chouippe().
from_spect_to_phys2()
void Force_ph::from_spect_to_phys2 (const std::vector< double > & coeff_force)
from_spect_to_phys_opti2()
void Force_ph::from_spect_to_phys_opti2 (ArrOfDouble & coeff_force)
References IJK_Field_vector< T, N >::echange_espace_virtuel().
Referenced by init_forcage_THI::compute_THI_force().
from_spect_to_phys_opti2_advection()
void Force_ph::from_spect_to_phys_opti2_advection (ArrOfDouble & coeff_force, const ArrOfDouble & advection_length)
References IJK_Field_vector< T, N >::echange_espace_virtuel().
Referenced by init_forcage_THI::compute_THI_force().
from_spect_to_phys_bis()
void Force_ph::from_spect_to_phys_bis (const std::vector< std::vector< std::vector< double > > > & coeff_force)
set_zero()
void Force_ph::set_zero ()
Referenced by init_forcage_THI::compute_THI_force().
cheat_function()
void Force_ph::cheat_function ()
Referenced by init_forcage_THI::compute_THI_force().
write()
void Force_ph::write (std::string nom_fichier_sortie, double t)
write_separate()
void Force_ph::write_separate (std::string nom_fichier_sortie, double t)
write_offset_index_position()
void Force_ph::write_offset_index_position (const Domaine_IJK & my_splitting)
References Domaine_IJK::get_offset_local().
compute_energie()
void Force_ph::compute_energie ()
get_energie()
double Force_ph::get_energie ()
get_force_attribute()
IJK_Field_vector3_double Force_ph::get_force_attribute ()
Referenced by init_forcage_THI::get_force_ph().
get_force_attribute2()
IJK_Field_vector3_double & Force_ph::get_force_attribute2 ()
Referenced by init_forcage_THI::get_force_ph2().
gbz_gather()
void Force_ph::gbz_gather (IJK_Field_vector3_double force_)
Member Data Documentation
info_obj
const Type_info Force_ph::info_obj static