TrioCFD: Navier_Stokes_FTD_IJK Class Reference
Navier_Stokes_FTD_IJK Class Reference
#include <Navier_Stokes_FTD_IJK.h>
Public Member Functions
void associer_pb_base (const Probleme_base &) override
void completer () override
void discretiser () override
const Type_info * get_info () const override
int preparer_calcul () override
Public Member Functions inherited from Equation_base
virtual void abortTimeStep ()
virtual void associer_domaine_dis (const Domaine_dis_base &)
virtual void associer_pb_base (const Probleme_base &)
virtual void associer_sch_tps_base (const Schema_Temps_base &)
virtual double calculer_pas_de_temps () const
virtual void completer ()
virtual std::vector< YAML_data > data_a_sauvegarder () const
DoubleTab & derivee_en_temps_conv (DoubleTab &, const DoubleTab &)
virtual DoubleTab & derivee_en_temps_inco (DoubleTab &)
const Discretisation_base & discretisation () const
virtual void discretiser ()
virtual const Motcle & domaine_application () const
virtual Domaine_Cl_dis_base & domaine_Cl_dis ()
virtual const Domaine_Cl_dis_base & domaine_Cl_dis () const
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual void imprimer (Sortie &os) const
virtual bool initTimeStep (double dt)
const Nom & le_nom () const override
int limpr () const
virtual void mettre_a_jour (double temps)
virtual int preparer_calcul ()
Probleme_base & probleme ()
const Probleme_base & probleme () const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Schema_Temps_base & schema_temps ()
const Schema_Temps_base & schema_temps () const
Solveur_Masse_base & solv_masse ()
const Solveur_Masse_base & solv_masse () const
Sources & sources ()
const Sources & sources () const
virtual void valider_iteration ()
virtual void verifie_ch_init_nb_comp (const Champ_Inc_base &ch_ref, const int nb_comp) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Equation_base
virtual Entree & lire_cl (Entree &)
virtual Entree & lire_cond_init (Entree &)
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual Entree & lire_sources (Entree &)
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
virtual int verif_Cl () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Public Types inherited from Champs_compris_IJK_interface
using FieldInfo_t = std::tuple< Motcle, Entity, Nature_du_champ, bool >
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Member Typedef Documentation
FieldInfo_t
using Navier_Stokes_FTD_IJK::FieldInfo_t = Champs_compris_IJK_interface::FieldInfo_t
Member Enumeration Documentation
velocity_diffusion_options_
enum Navier_Stokes_FTD_IJK::velocity_diffusion_options_ protected
Enumerator
simple_arithmetic
full_arithmetic
full_adaptative
velocity_convection_options_
enum Navier_Stokes_FTD_IJK::velocity_convection_options_ protected
Enumerator
non_conservative_simple
non_conservative_rhou
conservative
Constructor & Destructor Documentation
~Navier_Stokes_FTD_IJK()
Navier_Stokes_FTD_IJK::~Navier_Stokes_FTD_IJK ()
Navier_Stokes_FTD_IJK()
Navier_Stokes_FTD_IJK::Navier_Stokes_FTD_IJK ()
References correction_force_, TRUST_Vector< _CLASSE_ >::dimensionner_force(), expression_variable_source_, expression_vitesse_initiale_, TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), terme_source_correction_, and vol_bulles_.
Member Function Documentation
cree_instance()
Objet_U * Navier_Stokes_FTD_IJK::cree_instance () static
taille_memoire()
unsigned Navier_Stokes_FTD_IJK::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Navier_Stokes_FTD_IJK::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Navier_Stokes_FTD_IJK::info () static
get_info()
const Type_info * Navier_Stokes_FTD_IJK::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Equation_base.
self_cast() [1/2]
Navier_Stokes_FTD_IJK & Navier_Stokes_FTD_IJK::self_cast (Objet_U & r) static
self_cast() [2/2]
const Navier_Stokes_FTD_IJK & Navier_Stokes_FTD_IJK::self_cast (const Objet_U & r) static
printOn()
Sortie & Navier_Stokes_FTD_IJK::printOn (Sortie & os) const override protected virtual
Surcharge Objet_U::printOn Imprime l'equation et ses composants sur un flot de sortie.
Imprime le nom de l'equation, le solveur masse, les termes sources les conditions aux limites discretisees, les inconnues et les operateurs.
Parameters
(Sortie& os) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Equation_base.
References Equation_base::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Navier_Stokes_FTD_IJK::readOn (Entree & is) override protected virtual
Lecture d'une equation sur un flot d'entree.
Le format est le suivant: { [Source { [sou_1], [sour_2], ...} ] Conditions_limites { [cl_1] [cl_2] ... } Conditions_initiales { [cl_init] } }
Parameters
(Entree& is) un flot d'entree pour lire l'equation
Returns
(Entree&) le flot d'entree modifie
Exceptions
mauvais format de lecture, accolade ouvrante attendue
pas de conditions initiales, il faut initialiser l'inconnue
pas de conditions aux limites, il faut donner des conditions aux limites
Reimplemented from Equation_base.
References Param::lire_avec_accolades_depuis(), Objet_U::que_suis_je(), and set_param().
set_param()
void Navier_Stokes_FTD_IJK::set_param (Param & titi) override virtual
Reimplemented from Equation_base.
References add_initial_field_, Param::ajouter(), Param::ajouter_flag(), boundary_conditions_, coef_ammortissement_, coef_force_time_n_, coef_immobilisation_, coef_mean_force_, coef_rayon_force_rappel_, coeff_evol_volume_, compute_force_init_, correction_force_, correction_semi_locale_volume_bulle_, diam_bulle_monodisperse_, diffusion_alternative_, disable_convection_qdm_, disable_diffusion_qdm_, disable_solveur_poisson_, disable_source_interf_, epaisseur_maille_, expression_derivee_acceleration_, expression_derivee_facteur_variable_source_, expression_potential_phi_, expression_pression_initiale_, expression_variable_source_, expression_vitesse_initiale_, expression_vitesse_upstream_, facteur_variable_source_, fichier_reprise_vitesse_, forcage_, frozen_velocity_, harmonic_nu_in_calc_with_indicatrice_, harmonic_nu_in_diff_operator_, improved_initial_pressure_guess_, include_pressure_gradient_in_ustar_, Kd_, Ki_, Kp_, liq_velocity_tmoy_, nb_diam_ortho_shear_perio_, nb_diam_upstream_, p_seuil_max_, p_seuil_min_, poisson_solver_, projection_initiale_demandee_, qdm_corrections_, refuse_patch_conservation_QdM_RK3_source_interf_, Param::REQUIRED, resolution_fluctuations_, stencil_vitesse_entree_, suppression_rejetons_, terme_source_acceleration_, test_etapes_et_bilan_, timestep_reprise_vitesse_, upstream_dir_, upstream_stencil_, upstream_velocity_bubble_factor_, upstream_velocity_bubble_factor_deriv_, upstream_velocity_bubble_factor_integral_, upstream_velocity_measured_, use_harmonic_viscosity_, use_inv_rho_for_mass_solver_and_calculer_rho_v_, use_inv_rho_in_poisson_solver_, vap_velocity_tmoy_, velocity_bubble_scope_, velocity_convection_op_, velocity_diffusion_op_, velocity_reset_, vitesse_entree_, vitesse_entree_compo_to_force_, vitesse_entree_dir_, vitesse_upstream_, vol_bulle_monodisperse_, and vol_bulles_.
Referenced by readOn().
set_param_reprise_pb()
void Navier_Stokes_FTD_IJK::set_param_reprise_pb (Param & param)
References Param::ajouter(), fichier_reprise_vitesse_, forcage_, liq_velocity_tmoy_, qdm_corrections_, terme_source_acceleration_, timestep_reprise_vitesse_, vap_velocity_tmoy_, velocity_bubble_old_, and vitesse_upstream_reprise_.
Referenced by Probleme_FTD_IJK_base::reprendre_probleme().
completer()
void Navier_Stokes_FTD_IJK::completer () override virtual
Complete la construction (initialisation) des objets associes a l'equation.
Complete les sources, associe l'equation a l'inconnue complete les operateurs, complete les conditions aux limites discretisees. Voir les methodes Source_base::completer(), Operateur_base::completer() Domaine_Cl_dis_base::completer() Domaine_Cl_dis_base::completer(const Domaine_dis_base&)
Reimplemented from Equation_base.
References Parser::addVar(), diam_bulle_monodisperse_, diffusion_alternative_, Option_IJK::DISABLE_DIPHASIQUE, disable_solveur_poisson_, Process::exit(), expression_derivee_acceleration_, expression_derivee_facteur_variable_source_, expression_potential_phi_, expression_pression_initiale_, expression_variable_source_, frozen_velocity_, Probleme_FTD_IJK_base::get_domaine_ft(), include_pressure_gradient_in_ustar_, interfaces_, parser_derivee_acceleration_, parser_derivee_facteur_variable_source_, Parser::parseString(), probleme_ijk(), Domaine_IJK::set_extension_from_bulle_param(), Parser::setNbVar(), Parser::setString(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), use_inv_rho_, use_inv_rho_for_mass_solver_and_calculer_rho_v_, use_inv_rho_in_poisson_solver_, vol_bulle_monodisperse_, and vol_bulles_.
associer_pb_base()
void Navier_Stokes_FTD_IJK::associer_pb_base (const Probleme_base & pb) override virtual
S'associe au Probleme passe en parametre.
Associe egalement les sources, les operateurs et le solveur de masse a l'equation.
Parameters
(Probleme_base& pb) le probleme auquel l'equation doit s'associer
Reimplemented from Equation_base.
References Process::exit(), Probleme_U::le_nom(), Equation_base::mon_probleme, Equation_base::nom_, and Objet_U::que_suis_je().
discretiser()
void Navier_Stokes_FTD_IJK::discretiser () inline override virtual
Discretise l'equation.
Type le domaine_Cl_dis, la formatte, l'associe a l'equation. Type le solveur masse, lui associe le domaine discretisee et le domaine des conditions aux limites discretisees.
Reimplemented from Equation_base.
preparer_calcul()
int Navier_Stokes_FTD_IJK::preparer_calcul () override virtual
Tout ce qui ne depend pas des autres problemes eventuels.
Returns
(int) renvoie toujours 1
Reimplemented from Equation_base.
References compute_add_external_forces(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::data(), Option_IJK::DISABLE_DIPHASIQUE, Fluide_Diphasique_IJK::get_mu_liquid(), Probleme_FTD_IJK_base::get_post(), Fluide_Diphasique_IJK::get_rho_liquid(), Fluide_Diphasique_IJK::get_rho_vapour(), interfaces_, Postprocessing_IJK::is_post_required(), milieu_ijk(), molecular_mu_, probleme_ijk(), projeter(), rho_field_, rho_moyen_, Probleme_FTD_IJK_base::update_thermal_properties(), and velocity_.
Referenced by Probleme_FTD_IJK_base::preparer_calcul().
projeter()
void Navier_Stokes_FTD_IJK::projeter ()
References Postprocessing_IJK::coords(), correction_semi_locale_volume_bulle_, d_velocity_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::data(), Option_IJK::DISABLE_DIPHASIQUE, disable_solveur_poisson_, IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel(), euler_explicit_update(), Fluide_Diphasique_IJK::get_delta_rho(), Probleme_FTD_IJK_base::get_post(), Milieu_base::gravite(), improved_initial_pressure_guess_, interfaces_, inv_rho_field_, maj_indicatrice_rho_mu(), milieu_ijk(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), poisson_solver_, pressure_, pressure_ghost_cells_, pressure_rhs_, probleme_ijk(), projection_initiale_demandee_, redistribute_from_splitting_ft_faces_, rho_field_, Fluide_Diphasique::sigma(), terme_abs_repulsion_interfaces_ft_, terme_repulsion_interfaces_ft_, terme_source_interfaces_ft_, Probleme_FTD_IJK_base::update_thermal_properties(), use_inv_rho_in_poisson_solver_, Champ_Don_base::valeurs(), and velocity_.
Referenced by preparer_calcul().
milieu() [1/2]
const Milieu_base & Navier_Stokes_FTD_IJK::milieu () const override virtual
Implements Equation_base.
References TRUST_Ref< _CLASSE_ >::est_nul(), Process::exit(), le_fluide_, Probleme_U::le_nom(), Equation_base::probleme(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by milieu_ijk().
milieu() [2/2]
Milieu_base & Navier_Stokes_FTD_IJK::milieu () override virtual
Implements Equation_base.
References TRUST_Ref< _CLASSE_ >::est_nul(), Process::exit(), le_fluide_, Probleme_U::le_nom(), Equation_base::probleme(), and TRUST_Ref< _CLASSE_ >::valeur().
associer_milieu_base()
void Navier_Stokes_FTD_IJK::associer_milieu_base (const Milieu_base & un_milieu) override virtual
Implements Equation_base.
References Process::exit(), and le_fluide_.
nombre_d_operateurs()
int Navier_Stokes_FTD_IJK::nombre_d_operateurs () const inline override virtual
Implements Equation_base.
operateur() [1/2]
const Operateur & Navier_Stokes_FTD_IJK::operateur (int) const inline override virtual
Implements Equation_base.
operateur() [2/2]
Operateur & Navier_Stokes_FTD_IJK::operateur (int) inline override virtual
Implements Equation_base.
inconnue() [1/2]
const Champ_Inc_base & Navier_Stokes_FTD_IJK::inconnue () const inline override virtual
Implements Equation_base.
inconnue() [2/2]
Champ_Inc_base & Navier_Stokes_FTD_IJK::inconnue () inline override virtual
Implements Equation_base.
probleme_ijk() [1/2]
Probleme_FTD_IJK_base & Navier_Stokes_FTD_IJK::probleme_ijk ()
References Equation_base::mon_probleme, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by build_redistribute_extended_splitting_ft(), calculer_dv(), calculer_grad_p_moyen(), calculer_grad_p_over_rho_moyen(), calculer_inv_rho_grad_p_moyen(), calculer_terme_source_acceleration(), calculer_vitesse_ft(), completer(), compute_add_external_forces(), compute_add_THI_force(), compute_add_THI_force_sur_d_velocity(), compute_correction_for_momentum_balance(), deplacer_interfaces(), deplacer_interfaces_rk3(), fill_variable_source_and_potential_phi(), get_IJK_field_vector(), initialise_ijk_fields(), initialise_ns_fields(), maj_indicatrice_rho_mu(), preparer_calcul(), projeter(), sauvegarder_equation(), update_v_ghost_from_rho_v(), write_check_etapes_et_termes(), and write_qdm_corrections_information().
probleme_ijk() [2/2]
const Probleme_FTD_IJK_base & Navier_Stokes_FTD_IJK::probleme_ijk () const
References Equation_base::mon_probleme, and TRUST_Ref< _CLASSE_ >::valeur().
has_champ() [1/2]
bool Navier_Stokes_FTD_IJK::has_champ (const Motcle & nom) const inline override virtual
Reimplemented from Equation_base.
References champs_compris_, and Champs_compris_T< FIELD_TYPE >::has_champ().
Referenced by get_IJK_field(), Probleme_FTD_IJK_base::get_IJK_field(), and Probleme_FTD_IJK_base::has_champ().
has_champ() [2/2]
bool Navier_Stokes_FTD_IJK::has_champ (const Motcle & nom, TRUST_Ref< Champ_base * > & ref_champ) const inline override virtual
Reimplemented from Equation_base.
has_champ_vectoriel()
bool Navier_Stokes_FTD_IJK::has_champ_vectoriel (const Motcle & nom) const inline override virtual
Implements Champs_compris_IJK_interface.
References champs_compris_, and Champs_compris_IJK::has_champ_vectoriel().
Referenced by get_IJK_field_vector(), Probleme_FTD_IJK_base::get_IJK_field_vector(), and Probleme_FTD_IJK_base::has_champ_vectoriel().
get_IJK_field()
const IJK_Field_double & Navier_Stokes_FTD_IJK::get_IJK_field (const Motcle & nom) override virtual
Implements Champs_compris_IJK_interface.
References champs_compris_, Champs_compris_T< FIELD_TYPE >::get_champ(), and has_champ().
Referenced by Probleme_FTD_IJK_base::get_IJK_field().
get_IJK_field_vector()
const IJK_Field_vector3_double & Navier_Stokes_FTD_IJK::get_IJK_field_vector (const Motcle & nom) override virtual
Implements Champs_compris_IJK_interface.
References champs_compris_, coef_immobilisation_, force_rappel_, force_rappel_ft_, Champs_compris_IJK::get_champ_vectoriel(), has_champ_vectoriel(), probleme_ijk(), and redistribute_from_splitting_ft_faces_.
Referenced by Probleme_FTD_IJK_base::get_IJK_field_vector().
Fill_postprocessable_fields()
void Navier_Stokes_FTD_IJK::Fill_postprocessable_fields (std::vector< FieldInfo_t > & chps) static
Referenced by Probleme_FTD_IJK_base::Fill_postprocessable_fields().
get_noms_champs_postraitables()
void Navier_Stokes_FTD_IJK::get_noms_champs_postraitables (Noms & noms, Option opt = NONE) const override virtual
Reimplemented from Equation_base.
References TRUST_Vector< _CLASSE_ >::add(), champs_compris_, Champs_compris_IJK::liste_noms_compris(), and Champs_compris_IJK::liste_noms_compris_vectoriel().
Referenced by Probleme_FTD_IJK_base::get_noms_champs_postraitables().
initialise_ijk_fields()
void Navier_Stokes_FTD_IJK::initialise_ijk_fields ()
References Champs_compris_IJK::ajoute_champ_vectoriel(), Statistiques::begin_count(), boundary_conditions_, champs_compris_, coef_immobilisation_, compute_force_init_, init_forcage_THI::compute_initial_chouippe(), IJK_Shear_Periodic_helpler::defilement_, Probleme_FTD_IJK_base::domaine_ijk(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel(), expression_pression_initiale_, expression_vitesse_initiale_, fichier_reprise_vitesse_, forcage_, force_rappel_, force_rappel_ft_, Boundary_Conditions::get_correction_interp_monofluide(), Schema_Temps_IJK_base::get_current_time(), IJK_Field_vector< T, N >::get_domaine(), Probleme_FTD_IJK_base::get_domaine_ft(), Boundary_Conditions::get_dU_perio(), init_forcage_THI::get_force_ph2(), Fluide_Diphasique_IJK::get_gravite_norm(), Domaine_IJK::get_offset_local(), Probleme_FTD_IJK_base::get_post(), Fluide_Diphasique_IJK::get_rho_liquid(), Fluide_Diphasique_IJK::get_rho_vapour(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_shear_BC_helpler(), Boundary_Conditions::get_t0_shear(), init_forcage_THI::get_type_forcage(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost(), I_ns_, Postprocessing_IJK::initialise_stats(), initialise_velocity_from_file(), initialise_velocity_using_expression(), interfaces_, inv_rho_field_, kappa_ft_, kappa_ns_, maj_indicatrice_rho_mu(), Process::me(), milieu_ijk(), molecular_mu_, Process::mp_sum(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), Probleme_FTD_IJK_base::nom_sauvegarde(), Process::nproc(), pressure_, probleme_ijk(), Redistribute_Field::redistribute(), redistribute_from_splitting_ft_elem_ghostz_max_, redistribute_from_splitting_ft_elem_ghostz_min_, rho_field_, schema_temps_ijk(), IJK_Shear_Periodic_helpler::set_I_sig_kappa_zmax_(), IJK_Shear_Periodic_helpler::set_I_sig_kappa_zmin_(), IJK_Shear_Periodic_helpler::set_indicatrice_ghost_zmax_(), IJK_Shear_Periodic_helpler::set_indicatrice_ghost_zmin_(), IJK_Shear_Periodic_helpler::shear_x_time_, Fluide_Diphasique::sigma(), terme_source_acceleration_, use_inv_rho_, velocity_, vol_bulle_monodisperse_, and vol_bulles_.
Referenced by Probleme_FTD_IJK_base::initialise_ijk_fields().
initialise_ns_fields()
void Navier_Stokes_FTD_IJK::initialise_ns_fields ()
References IJK_Field_vector< T, N >::add_synonymous(), Field_base::add_synonymous(), Champs_compris_T< FIELD_TYPE >::ajoute_champ(), Champs_compris_IJK::ajoute_champ_vectoriel(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::allocate(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::allocate_shear_BC(), backup_terme_source_interfaces_ft_, backup_terme_source_interfaces_ns_, boundary_conditions_, champs_compris_, d_pressure_, d_v_diff_et_conv_, d_velocity_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::data(), IJK_Shear_Periodic_helpler::defilement_, diffusion_alternative_, Option_IJK::DISABLE_DIPHASIQUE, disable_solveur_poisson_, div_rhou_, Probleme_FTD_IJK_base::domaine_ijk(), IJK_Field_vector< T, N >::echange_espace_virtuel(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel(), Domaine_IJK::ELEM, Process::exit(), expression_potential_phi_, expression_variable_source_, flag_variable_source_, Operateur_IJK_faces_conv::get_convection_op_option_rank(), Boundary_Conditions::get_correction_interp_monofluide(), Probleme_FTD_IJK_base::get_domaine_ft(), Fluide_Diphasique_IJK::get_mu_liquid(), Fluide_Diphasique_IJK::get_mu_vapour(), Domaine_IJK::get_nb_elem_local(), Domaine_IJK::get_offset_local(), Fluide_Diphasique_IJK::get_rho_liquid(), Fluide_Diphasique_IJK::get_rho_vapour(), Probleme_FTD_IJK_base::get_thermal_probes_ghost_cells(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost(), harmonic_nu_in_diff_operator_, I_ns_, include_pressure_gradient_in_ustar_, Multigrille_Adrien::initialize(), Operateur_IJK_faces_conv::initialize(), Operateur_IJK_faces_diff::initialize(), inv_rho_field_, kappa_ft_, kappa_ns_, laplacien_velocity_, milieu_ijk(), molecular_mu_, Field_base::nommer(), IJK_Field_vector< T, N >::nommer(), non_conservative_rhou, poisson_solver_, potential_phi_, pressure_, pressure_ghost_cells_, pressure_rhs_, probleme_ijk(), psi_velocity_, rho_du_euler_ap_prediction_champ_, rho_du_euler_ap_projection_champ_, rho_field_, IJK_Shear_Periodic_helpler::rho_liq_ref_for_poisson_, rho_u_euler_ap_projection_champ_, rho_u_euler_ap_rho_mu_ind_champ_, rho_u_euler_av_prediction_champ_, rho_u_euler_av_rho_mu_ind_champ_, rho_v_, IJK_Shear_Periodic_helpler::rho_vap_ref_for_poisson_, RK3_F_pressure_, RK3_F_velocity_, schema_temps_ijk(), terme_abs_repulsion_interfaces_ft_, terme_abs_repulsion_interfaces_ns_, terme_convection_mass_solver_, terme_diffusion_local_, terme_diffusion_mass_solver_, terme_pression_in_ustar_local_, terme_pression_local_, terme_repulsion_interfaces_ft_, terme_repulsion_interfaces_ns_, terme_source_interfaces_ft_, terme_source_interfaces_ns_, test_etapes_et_bilan_, unit_, use_inv_rho_, use_inv_rho_in_poisson_solver_, variable_source_, velocity_, velocity_convection_op_, velocity_diffusion_op_, velocity_ft_, and zero_field_ft_.
Referenced by Probleme_FTD_IJK_base::initialize().
complete_initialise_ijk_fields()
void Navier_Stokes_FTD_IJK::complete_initialise_ijk_fields ()
References boundary_conditions_, IJK_Shear_Periodic_helpler::defilement_, Boundary_Conditions::get_correction_interp_monofluide(), Schema_Temps_IJK_base::get_current_time(), Boundary_Conditions::get_dU_perio(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_shear_BC_helpler(), Boundary_Conditions::get_t0_shear(), I_ns_, interfaces_, inv_rho_field_, kappa_ft_, kappa_ns_, milieu_ijk(), molecular_mu_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), pressure_, Redistribute_Field::redistribute(), redistribute_from_splitting_ft_elem_ghostz_max_, redistribute_from_splitting_ft_elem_ghostz_min_, rho_field_, schema_temps_ijk(), IJK_Shear_Periodic_helpler::set_I_sig_kappa_zmax_(), IJK_Shear_Periodic_helpler::set_I_sig_kappa_zmin_(), IJK_Shear_Periodic_helpler::set_indicatrice_ghost_zmax_(), IJK_Shear_Periodic_helpler::set_indicatrice_ghost_zmin_(), IJK_Shear_Periodic_helpler::shear_x_time_, Fluide_Diphasique::sigma(), and use_inv_rho_.
Referenced by Probleme_FTD_IJK_base::initialise_ijk_fields().
get_boundary_conditions()
const Boundary_Conditions & Navier_Stokes_FTD_IJK::get_boundary_conditions () const inline
References boundary_conditions_.
Referenced by Probleme_FTD_IJK::initialize(), Probleme_FTD_IJK_cut_cell::initialize(), Probleme_FTD_IJK_base::reprendre_probleme(), and Probleme_FTD_IJK_base::solveTimeStep().
get_pressure()
const IJK_Field_double & Navier_Stokes_FTD_IJK::get_pressure () const inline
References pressure_.
get_pressure_ghost_cells()
const IJK_Field_double & Navier_Stokes_FTD_IJK::get_pressure_ghost_cells () const inline
References pressure_ghost_cells_.
get_vitesse_upstream()
double Navier_Stokes_FTD_IJK::get_vitesse_upstream () const inline
References vitesse_upstream_.
Referenced by IJK_Thermal_base::calculer_dT().
get_nb_diam_upstream()
double Navier_Stokes_FTD_IJK::get_nb_diam_upstream () const inline
References nb_diam_upstream_.
Referenced by IJK_Thermal_base::calculer_dT().
get_upstream_dir()
int Navier_Stokes_FTD_IJK::get_upstream_dir () const inline
References upstream_dir_.
Referenced by IJK_Thermal_base::calculer_dT().
get_upstream_stencil()
int Navier_Stokes_FTD_IJK::get_upstream_stencil () const inline
References upstream_stencil_.
Referenced by IJK_Thermal_base::calculer_dT().
get_rho_field()
const IJK_Field_double & Navier_Stokes_FTD_IJK::get_rho_field () const inline
References rho_field_.
get_rho_field_ijk()
double Navier_Stokes_FTD_IJK::get_rho_field_ijk (int i, int j, int k) const inline
References rho_field_.
get_velocity() [1/2]
const IJK_Field_vector3_double & Navier_Stokes_FTD_IJK::get_velocity () const inline
References velocity_.
Referenced by Schema_Temps_IJK_base::find_timestep(), Probleme_FTD_IJK::initialize(), Probleme_FTD_IJK_cut_cell::initialize(), and Probleme_FTD_IJK_base::sauvegarder_probleme().
get_velocity() [2/2]
IJK_Field_vector3_double & Navier_Stokes_FTD_IJK::get_velocity () inline
References velocity_.
get_disable_diffusion_qdm()
int Navier_Stokes_FTD_IJK::get_disable_diffusion_qdm () const inline
References disable_diffusion_qdm_.
Referenced by Schema_Temps_IJK_base::find_timestep().
get_disable_convection_qdm()
int Navier_Stokes_FTD_IJK::get_disable_convection_qdm () const inline
References disable_convection_qdm_.
Referenced by Schema_Temps_IJK_base::find_timestep().
get_compute_rising_velocities() [1/2]
int Navier_Stokes_FTD_IJK::get_compute_rising_velocities () const inline
References compute_rising_velocities_.
Referenced by Probleme_FTD_IJK_base::initialise_ijk_fields().
get_fill_rising_velocities() [1/2]
int Navier_Stokes_FTD_IJK::get_fill_rising_velocities () const inline
References fill_rising_velocities_.
Referenced by Probleme_FTD_IJK_base::initialise_ijk_fields().
get_use_bubbles_velocities_from_interface() [1/2]
int Navier_Stokes_FTD_IJK::get_use_bubbles_velocities_from_interface () const inline
References use_bubbles_velocities_from_interface_.
Referenced by Probleme_FTD_IJK_base::initialise_ijk_fields().
get_use_bubbles_velocities_from_barycentres() [1/2]
int Navier_Stokes_FTD_IJK::get_use_bubbles_velocities_from_barycentres () const inline
References use_bubbles_velocities_from_barycentres_.
Referenced by Probleme_FTD_IJK_base::initialise_ijk_fields().
get_upstream_velocity_measured() [1/2]
int Navier_Stokes_FTD_IJK::get_upstream_velocity_measured () const inline
References upstream_velocity_measured_.
Referenced by Probleme_FTD_IJK_base::initialise_ijk_fields().
get_compute_rising_velocities() [2/2]
int & Navier_Stokes_FTD_IJK::get_compute_rising_velocities () inline
References compute_rising_velocities_.
get_fill_rising_velocities() [2/2]
int & Navier_Stokes_FTD_IJK::get_fill_rising_velocities () inline
References fill_rising_velocities_.
get_use_bubbles_velocities_from_interface() [2/2]
int & Navier_Stokes_FTD_IJK::get_use_bubbles_velocities_from_interface () inline
References use_bubbles_velocities_from_interface_.
get_use_bubbles_velocities_from_barycentres() [2/2]
int & Navier_Stokes_FTD_IJK::get_use_bubbles_velocities_from_barycentres () inline
References use_bubbles_velocities_from_barycentres_.
get_upstream_velocity_measured() [2/2]
int & Navier_Stokes_FTD_IJK::get_upstream_velocity_measured () inline
References upstream_velocity_measured_.
get_velocity_ft()
const IJK_Field_vector3_double & Navier_Stokes_FTD_IJK::get_velocity_ft () const inline
References velocity_ft_.
associer_interfaces()
void Navier_Stokes_FTD_IJK::associer_interfaces (const IJK_Interfaces & inter) inline
References interfaces_.
Referenced by Probleme_FTD_IJK_base::completer().
milieu_ijk() [1/2]
Fluide_Diphasique_IJK & Navier_Stokes_FTD_IJK::milieu_ijk () inline
References milieu().
Referenced by calculer_dv(), calculer_terme_asservissement(), calculer_terme_source_acceleration(), complete_initialise_ijk_fields(), compute_and_add_qdm_corrections(), compute_and_add_qdm_corrections_monophasic(), compute_correction_for_momentum_balance(), euler_time_step(), initialise_ijk_fields(), initialise_ns_fields(), maj_indicatrice_rho_mu(), preparer_calcul(), projeter(), rk3_sub_step(), terme_source_gravite(), and update_indicatrice_variables_monofluides().
milieu_ijk() [2/2]
const Fluide_Diphasique_IJK & Navier_Stokes_FTD_IJK::milieu_ijk () const inline
References milieu().
schema_temps_ijk() [1/2]
Schema_Temps_IJK_base & Navier_Stokes_FTD_IJK::schema_temps_ijk () inline
References Equation_base::le_schema_en_temps, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by calculer_dv(), calculer_terme_asservissement(), calculer_terme_source_acceleration(), complete_initialise_ijk_fields(), compute_add_external_forces(), compute_correction_for_momentum_balance(), create_forced_dilation(), deplacer_interfaces(), deplacer_interfaces_rk3(), euler_explicit_update(), euler_time_step(), initialise_ijk_fields(), initialise_ns_fields(), sauvegarder_equation(), set_time_for_corrections(), write_check_etapes_et_termes(), and write_qdm_corrections_information().
schema_temps_ijk() [2/2]
const Schema_Temps_IJK_base & Navier_Stokes_FTD_IJK::schema_temps_ijk () const inline
References Equation_base::le_schema_en_temps, and TRUST_Ref< _CLASSE_ >::valeur().
redistribute_to_splitting_ft_elem()
void Navier_Stokes_FTD_IJK::redistribute_to_splitting_ft_elem (const IJK_Field_double & input_field, IJK_Field_double & output_field)
References Redistribute_Field::redistribute(), and redistribute_to_splitting_ft_elem_.
redistribute_from_splitting_ft_elem()
void Navier_Stokes_FTD_IJK::redistribute_from_splitting_ft_elem (const IJK_Field_double & input_field, IJK_Field_double & output_field)
References Redistribute_Field::redistribute(), and redistribute_from_splitting_ft_elem_.
Referenced by IJK_Ghost_Fluid_Fields::compute_eulerian_distance().
redistrib_to_ft_elem()
Redistribute_Field & Navier_Stokes_FTD_IJK::redistrib_to_ft_elem () inline
References redistribute_to_splitting_ft_elem_.
redistrib_from_ft_elem()
Redistribute_Field & Navier_Stokes_FTD_IJK::redistrib_from_ft_elem () inline
References redistribute_from_splitting_ft_elem_.
Referenced by IJK_Interfaces::calculer_indicatrice_next().
get_redistribute_from_splitting_ft_faces()
void Navier_Stokes_FTD_IJK::get_redistribute_from_splitting_ft_faces (const IJK_Field_vector3_double & faces_ft, IJK_Field_vector3_double & faces_ns) inline
References redistribute_from_splitting_ft_faces_.
Referenced by IJK_Interfaces::calculer_indicatrice_next().
maj_indicatrice_rho_mu()
void Navier_Stokes_FTD_IJK::maj_indicatrice_rho_mu (const bool parcourir = true)
References Statistiques::begin_count(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::data(), Option_IJK::DISABLE_DIPHASIQUE, IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel(), Statistiques::end_count(), Fluide_Diphasique_IJK::get_mu_liquid(), Fluide_Diphasique_IJK::get_mu_vapour(), Fluide_Diphasique_IJK::get_rho_liquid(), Fluide_Diphasique_IJK::get_rho_vapour(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost(), harmonic_nu_in_calc_with_indicatrice_, interfaces_, inv_rho_field_, milieu_ijk(), molecular_mu_, Statistiques::new_counter(), Probleme_FTD_IJK_base::parcourir_maillage(), probleme_ijk(), rho_field_, and use_inv_rho_.
Referenced by initialise_ijk_fields(), projeter(), Probleme_FTD_IJK_base::solveTimeStep_Euler(), and Probleme_FTD_IJK_base::solveTimeStep_RK3().
update_v_ghost_from_rho_v()
void Navier_Stokes_FTD_IJK::update_v_ghost_from_rho_v ()
References boundary_conditions_, Probleme_FTD_IJK_base::domaine_ijk(), Domaine_IJK::ELEM, Boundary_Conditions::get_dU_perio(), Domaine_IJK::get_nb_items_global(), Domaine_IJK::get_offset_local(), probleme_ijk(), rho_field_, rho_v_, and velocity_.
Referenced by update_v_or_rhov().
update_rho_v()
void Navier_Stokes_FTD_IJK::update_rho_v ()
References IJK_Field_vector< T, N >::echange_espace_virtuel(), rho_field_, rho_v_, use_inv_rho_for_mass_solver_and_calculer_rho_v_, and velocity_.
Referenced by calculer_dv(), calculer_terme_asservissement(), calculer_terme_source_acceleration(), compute_correction_for_momentum_balance(), forcage_control_ecoulement(), and update_v_or_rhov().
transfer_ft_to_ns()
void Navier_Stokes_FTD_IJK::transfer_ft_to_ns ()
References redistribute_from_splitting_ft_faces_, terme_abs_repulsion_interfaces_ft_, terme_abs_repulsion_interfaces_ns_, terme_repulsion_interfaces_ft_, and terme_repulsion_interfaces_ns_.
Referenced by Postprocessing_IJK::update_stat_ft().
calculer_terme_asservissement()
void Navier_Stokes_FTD_IJK::calculer_terme_asservissement (double & ax, double & ay, double & az)
References Fluide_Diphasique_IJK::get_delta_rho(), Fluide_Diphasique_IJK::get_direction_gravite(), Domaine_IJK::get_domain_length(), IJK_Field_vector< T, N >::get_domaine(), Fluide_Diphasique_IJK::get_rho_liquid(), Schema_Temps_IJK_base::get_timestep(), int_x_, int_y_, int_z_, interfaces_, Kd_, Ki_, Kp_, milieu_ijk(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), rho_v_, schema_temps_ijk(), update_rho_v(), velocity_, and vol_bulle_monodisperse_.
Referenced by calculer_dv().
calculer_vitesse_gauche()
void Navier_Stokes_FTD_IJK::calculer_vitesse_gauche (const IJK_Field_double & vx, const IJK_Field_double & vy, const IJK_Field_double & vz, double & vx_moy, double & vy_moy, double & vz_moy)
References IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_domaine(), Domaine_IJK::get_local_slice_index(), interfaces_, Process::mp_sum(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), and IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj().
Referenced by Postprocessing_IJK::ecrire_statistiques_cisaillement(), euler_time_step(), and rk3_sub_step().
calculer_vitesse_droite()
void Navier_Stokes_FTD_IJK::calculer_vitesse_droite (const IJK_Field_double & vx, const IJK_Field_double & vy, const IJK_Field_double & vz, double & vx_moy, double & vy_moy, double & vz_moy)
References IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_domaine(), Domaine_IJK::get_local_slice_index(), Domaine_IJK::get_nprocessor_per_direction(), interfaces_, Process::mp_sum(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), and IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk().
Referenced by Postprocessing_IJK::ecrire_statistiques_cisaillement().
calculer_terme_source_acceleration() [1/2]
void Navier_Stokes_FTD_IJK::calculer_terme_source_acceleration (IJK_Field_double & vx, const double time, const double timestep, const int rk_step)
References Statistiques::begin_count(), Sortie_Fichier_base::close(), coef_immobilisation_, Option_IJK::DISABLE_DIPHASIQUE, Statistiques::end_count(), Parser::eval(), expression_derivee_acceleration_, expression_derivee_facteur_variable_source_, facteur_variable_source_, forcage_, force_rappel_, Fluide_Diphasique_IJK::get_direction_gravite(), Domaine_IJK::get_domain_length(), IJK_Field_vector< T, N >::get_domaine(), init_forcage_THI::get_force_ph2(), Fluide_Diphasique_IJK::get_mu_liquid(), Probleme_FTD_IJK_base::get_reprise(), Fluide_Diphasique_IJK::get_rho_liquid(), Fluide_Diphasique_IJK::get_rho_vapour(), Schema_RK3_IJK::get_store_RK3_fac_sv(), Schema_RK3_IJK::get_store_RK3_source_acc(), Schema_Temps_IJK_base::get_tstep(), init_forcage_THI::get_type_forcage(), interfaces_, corrections_qdm::is_type_gb(), Process::je_suis_maitre(), liq_velocity_tmoy_, milieu_ijk(), parser_derivee_acceleration_, parser_derivee_facteur_variable_source_, probleme_ijk(), qdm_corrections_, rho_field_, rho_v_, schema_temps_ijk(), Parser::setVar(), terme_source_acceleration_, terme_source_interfaces_ns_, update_rho_v(), vap_velocity_tmoy_, velocity_, and vol_bulle_monodisperse_.
Referenced by calculer_terme_source_acceleration(), Probleme_FTD_IJK_base::solveTimeStep_Euler(), and Probleme_FTD_IJK_base::solveTimeStep_RK3().
calculer_terme_source_acceleration() [2/2]
void Navier_Stokes_FTD_IJK::calculer_terme_source_acceleration (const double time, const double timestep, const int rk_step, const int dir)
References calculer_terme_source_acceleration(), and velocity_.
compute_correction_for_momentum_balance()
void Navier_Stokes_FTD_IJK::compute_correction_for_momentum_balance (const int rk_step)
References Sortie_Fichier_base::close(), correction_force_, Domaine_IJK::get_constant_delta(), Schema_Temps_IJK_base::get_current_time(), Fluide_Diphasique_IJK::get_direction_gravite(), Domaine_IJK::get_domain_length(), Probleme_FTD_IJK_base::get_domaine(), Fluide_Diphasique_IJK::get_mu_liquid(), Probleme_FTD_IJK_base::get_reprise(), Fluide_Diphasique_IJK::get_rho_liquid(), Fluide_Diphasique_IJK::get_rho_vapour(), Schema_Temps_IJK_base::get_timestep(), Schema_Temps_IJK_base::get_tstep(), Milieu_base::gravite(), integrated_residu_, interfaces_, Process::je_suis_maitre(), milieu_ijk(), pressure_, probleme_ijk(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), rho_v_, schema_temps_ijk(), store_rhov_moy_, terme_convection_, terme_diffusion_, terme_pression_, terme_source_acceleration_, terme_source_correction_, terme_source_interfaces_ns_, update_rho_v(), Champ_Don_base::valeurs(), and velocity_.
Referenced by calculer_dv().
calculer_dv()
void Navier_Stokes_FTD_IJK::calculer_dv (const double timestep, const double time, const int rk_step)
References Statistiques::begin_count(), calculer_terme_asservissement(), compute_add_external_forces(), compute_add_THI_force_sur_d_velocity(), compute_correction_for_momentum_balance(), conservative, Motcles::contient_(), correction_force_, d_v_diff_et_conv_, d_velocity_, diffusion_alternative_, disable_convection_qdm_, disable_diffusion_qdm_, Option_IJK::DISABLE_DIPHASIQUE, disable_source_interf_, div_rhou_, Probleme_FTD_IJK_base::domaine_ijk(), IJK_Field_vector< T, N >::echange_espace_virtuel(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel(), Statistiques::end_count(), Process::exit(), expression_potential_phi_, expression_variable_source_, facteur_variable_source_, Postprocessing_IJK::fill_op_conv(), Postprocessing_IJK::fill_surface_force(), fill_variable_source_and_potential_phi(), forcage_, Domaine_IJK::get_constant_delta(), Operateur_IJK_faces_conv::get_convection_op(), Operateur_IJK_faces_conv::get_convection_op_option_rank(), Probleme_FTD_IJK_base::get_delta_z_local(), Operateur_IJK_faces_diff::get_diffusion_op_option(), IJK_Field_vector< T, N >::get_domaine(), init_forcage_THI::get_facteur_forcage(), Postprocessing_IJK::get_liste_post_instantanes(), Domaine_IJK::get_periodic_flag(), Probleme_FTD_IJK_base::get_post(), Fluide_Diphasique_IJK::get_rho_liquid(), Schema_Temps_IJK_base::get_timestep(), Schema_Temps_IJK_base::get_tstep(), init_forcage_THI::get_type_forcage(), Milieu_base::gravite(), Probleme_FTD_IJK_base::has_interface(), include_pressure_gradient_in_ustar_, interfaces_, inv_rho_field_, Kd_, Ki_, Kp_, laplacien_velocity_, milieu_ijk(), molecular_mu_, Statistiques::new_counter(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), non_conservative_rhou, non_conservative_simple, pressure_, probleme_ijk(), redistribute_from_splitting_ft_faces_, refuse_patch_conservation_QdM_RK3_source_interf_, TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), rho_field_, rho_v_, schema_temps_ijk(), terme_abs_repulsion_interfaces_ft_, terme_convection_, terme_convection_mass_solver_, terme_diffusion_, terme_diffusion_local_, terme_diffusion_mass_solver_, terme_interfaces_, terme_interfaces_af_mass_solver_, terme_interfaces_bf_mass_solver_, terme_interfaces_bf_mass_solver_bis_, terme_interfaces_conv_diff_mass_solver_, terme_moyen_convection_mass_solver_, terme_moyen_diffusion_mass_solver_, terme_pression_bis_, terme_pression_in_ustar_, terme_pression_in_ustar_local_, terme_pression_ter_, terme_repulsion_interfaces_ft_, terme_repulsion_interfaces_ns_, terme_source_acceleration_, terme_source_correction_, terme_source_interfaces_ft_, terme_source_interfaces_ns_, test_etapes_et_bilan_, unit_, update_rho_v(), use_inv_rho_for_mass_solver_and_calculer_rho_v_, Champ_Don_base::valeurs(), variable_source_, velocity_, velocity_convection_op_, velocity_diffusion_op_, velocity_reset_, and write_check_etapes_et_termes().
Referenced by euler_time_step(), and rk3_sub_step().
compute_add_THI_force()
void Navier_Stokes_FTD_IJK::compute_add_THI_force (const IJK_Field_vector3_double & vitesse, const int time_iteration, const double dt, const double current_time, const Domaine_IJK & my_splitting)
References Statistiques::begin_count(), calculer_moyenne_de_phase_liq(), init_forcage_THI::compute_THI_force(), d_velocity_, Statistiques::end_count(), forcage_, init_forcage_THI::get_force_ph2(), init_forcage_THI::get_forced_advection(), probleme_ijk(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), init_forcage_THI::update_advection_length(), init_forcage_THI::update_advection_velocity(), and velocity_.
compute_add_THI_force_sur_d_velocity()
void Navier_Stokes_FTD_IJK::compute_add_THI_force_sur_d_velocity (const IJK_Field_vector3_double & vitesse, const int time_iteration, const double dt, const double current_time, const Domaine_IJK & my_splitting, const int facteur)
References Statistiques::begin_count(), calculer_true_moyenne_de_phase_liq(), init_forcage_THI::compute_THI_force(), d_velocity_, IJK_Field_vector< T, N >::echange_espace_virtuel(), Statistiques::end_count(), forcage_, init_forcage_THI::get_force_ph2(), init_forcage_THI::get_forced_advection(), interfaces_, probleme_ijk(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), rho_field_, rho_moyen_, init_forcage_THI::update_advection_length(), and init_forcage_THI::update_advection_velocity().
Referenced by calculer_dv().
calculer_moyenne_de_phase_liq()
double Navier_Stokes_FTD_IJK::calculer_moyenne_de_phase_liq (const IJK_Field_double & vx)
References Domaine_IJK::get_delta(), Domaine_IJK::get_domain_length(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_domaine(), Domaine_IJK::get_nb_elem_tot(), interfaces_, Process::mp_sum(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), and IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk().
Referenced by calculer_true_moyenne_de_phase_liq(), and compute_add_THI_force().
compute_and_add_qdm_corrections()
void Navier_Stokes_FTD_IJK::compute_and_add_qdm_corrections ()
References calculer_true_moyenne_de_phase_liq(), calculer_true_moyenne_de_phase_vap(), corrections_qdm::compute_correct_velocity_one_direction(), corrections_qdm::compute_correction_value_one_direction(), corrections_qdm::get_correct_velocitiy_one_direction(), corrections_qdm::get_need_for_vitesse_relative(), corrections_qdm::get_need_to_compute_correction_value_one_direction(), interfaces_, milieu_ijk(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), qdm_corrections_, rho_field_, rho_v_, corrections_qdm::set_rho_liquide(), corrections_qdm::set_rho_moyen_alpha_l(), corrections_qdm::set_rho_vel_moyen(), corrections_qdm::set_vitesse_relative(), and velocity_.
Referenced by corriger_qdm().
fill_variable_source_and_potential_phi()
void Navier_Stokes_FTD_IJK::fill_variable_source_and_potential_phi (const double time)
References IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel(), expression_potential_phi_, expression_variable_source_, Postprocessing_IJK::get_grad_I_ns(), Probleme_FTD_IJK_base::get_post(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost(), interfaces_, potential_phi_, probleme_ijk(), and variable_source_.
Referenced by calculer_dv().
write_check_etapes_et_termes()
void Navier_Stokes_FTD_IJK::write_check_etapes_et_termes (const int rk_step)
References Sortie_Fichier_base::close(), Schema_Temps_IJK_base::get_current_time(), Probleme_FTD_IJK_base::get_reprise(), Schema_Temps_IJK_base::get_tstep(), Process::je_suis_maitre(), pression_ap_proj_, probleme_ijk(), rho_du_euler_ap_prediction_, rho_du_euler_ap_projection_, rho_u_euler_ap_projection_, rho_u_euler_ap_rho_mu_ind_, rho_u_euler_av_prediction_, rho_u_euler_av_rho_mu_ind_, schema_temps_ijk(), terme_convection_, terme_diffusion_, terme_interfaces_, terme_interfaces_af_mass_solver_, terme_interfaces_bf_mass_solver_, terme_interfaces_bf_mass_solver_bis_, terme_moyen_convection_mass_solver_, terme_moyen_diffusion_mass_solver_, terme_pression_bis_, terme_pression_ter_, test_etapes_et_bilan_, and u_euler_ap_rho_mu_ind_.
Referenced by calculer_dv().
compute_add_external_forces()
void Navier_Stokes_FTD_IJK::compute_add_external_forces (const int dir)
References coef_ammortissement_, coef_force_time_n_, coef_immobilisation_, coef_mean_force_, coef_rayon_force_rappel_, d_velocity_, force_rappel_, force_rappel_ft_, interfaces_, probleme_ijk(), redistribute_from_splitting_ft_faces_, schema_temps_ijk(), and velocity_.
Referenced by calculer_dv(), and preparer_calcul().
calculer_true_moyenne_de_phase_vap()
double Navier_Stokes_FTD_IJK::calculer_true_moyenne_de_phase_vap (const IJK_Field_double & vx)
References calculer_moyenne_de_phase_vap(), and interfaces_.
Referenced by compute_and_add_qdm_corrections().
calculer_moyenne_de_phase_vap()
double Navier_Stokes_FTD_IJK::calculer_moyenne_de_phase_vap (const IJK_Field_double & vx)
References Domaine_IJK::get_delta(), Domaine_IJK::get_domain_length(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_domaine(), Domaine_IJK::get_nb_elem_tot(), interfaces_, Process::mp_sum(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), and IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk().
Referenced by calculer_true_moyenne_de_phase_vap().
calculer_true_moyenne_de_phase_liq()
double Navier_Stokes_FTD_IJK::calculer_true_moyenne_de_phase_liq (const IJK_Field_double & vx)
References calculer_moyenne_de_phase_liq(), and interfaces_.
Referenced by compute_add_THI_force_sur_d_velocity(), compute_and_add_qdm_corrections(), and compute_and_add_qdm_corrections_monophasic().
terme_source_gravite()
void Navier_Stokes_FTD_IJK::terme_source_gravite (IJK_Field_double & dv, int k_index, int dir) const
References Milieu_base::gravite(), milieu_ijk(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), and Champ_Don_base::valeurs().
set_time_for_corrections()
void Navier_Stokes_FTD_IJK::set_time_for_corrections ()
References qdm_corrections_, schema_temps_ijk(), and corrections_qdm::set_time().
Referenced by corriger_qdm().
compute_and_add_qdm_corrections_monophasic()
void Navier_Stokes_FTD_IJK::compute_and_add_qdm_corrections_monophasic ()
References calculer_true_moyenne_de_phase_liq(), corrections_qdm::compute_correct_velocity_one_direction(), corrections_qdm::compute_correction_value_one_direction(), corrections_qdm::get_correct_velocitiy_one_direction(), corrections_qdm::get_need_for_vitesse_relative(), corrections_qdm::get_need_to_compute_correction_value_one_direction(), Fluide_Diphasique_IJK::get_rho_liquid(), milieu_ijk(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), qdm_corrections_, rho_v_, corrections_qdm::set_rho_liquide(), corrections_qdm::set_rho_moyen_alpha_l(), corrections_qdm::set_rho_vel_moyen(), corrections_qdm::set_vitesse_relative(), and velocity_.
Referenced by corriger_qdm().
compute_var_volume_par_bulle()
void Navier_Stokes_FTD_IJK::compute_var_volume_par_bulle (ArrOfDouble & var_volume_par_bulle)
References correction_semi_locale_volume_bulle_, interfaces_, TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and vol_bulles_.
Referenced by Probleme_FTD_IJK_base::solveTimeStep(), and Probleme_FTD_IJK_base::solveTimeStep_Euler().
write_qdm_corrections_information()
void Navier_Stokes_FTD_IJK::write_qdm_corrections_information ()
References Sortie_Fichier_base::close(), corrections_qdm::get_correction_values(), Schema_Temps_IJK_base::get_current_time(), Probleme_FTD_IJK_base::get_reprise(), Schema_Temps_IJK_base::get_tstep(), corrections_qdm::get_velocity_corrections(), Process::je_suis_maitre(), probleme_ijk(), qdm_corrections_, rho_field_, schema_temps_ijk(), and velocity_.
Referenced by corriger_qdm().
calculer_inv_rho_grad_p_moyen()
Vecteur3 Navier_Stokes_FTD_IJK::calculer_inv_rho_grad_p_moyen (const IJK_Field_double & inv_rho, const IJK_Field_double & pression)
References IJK_Field_vector< T, N >::echange_espace_virtuel(), and probleme_ijk().
calculer_grad_p_moyen()
Vecteur3 Navier_Stokes_FTD_IJK::calculer_grad_p_moyen (const IJK_Field_double & pression)
References IJK_Field_vector< T, N >::echange_espace_virtuel(), and probleme_ijk().
Referenced by euler_time_step(), and rk3_sub_step().
calculer_grad_p_over_rho_moyen()
Vecteur3 Navier_Stokes_FTD_IJK::calculer_grad_p_over_rho_moyen (const IJK_Field_double & pression)
References IJK_Field_vector< T, N >::echange_espace_virtuel(), and probleme_ijk().
Referenced by euler_time_step(), and rk3_sub_step().
euler_explicit_update()
void Navier_Stokes_FTD_IJK::euler_explicit_update (const IJK_Field_double & dv, IJK_Field_double & v, const int k_layer) const
References Schema_Temps_IJK_base::get_timestep(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), and schema_temps_ijk().
Referenced by euler_time_step(), and projeter().
forcage_control_ecoulement()
void Navier_Stokes_FTD_IJK::forcage_control_ecoulement ()
References rho_v_, store_rhov_moy_, and update_rho_v().
Referenced by Probleme_FTD_IJK_base::preparer_calcul().
get_molecular_mu()
const IJK_Field_double & Navier_Stokes_FTD_IJK::get_molecular_mu () const inline
References molecular_mu_.
get_improved_initial_pressure_guess()
int Navier_Stokes_FTD_IJK::get_improved_initial_pressure_guess () const inline
References improved_initial_pressure_guess_.
get_suppression_rejetons()
int Navier_Stokes_FTD_IJK::get_suppression_rejetons () const inline
References suppression_rejetons_.
Referenced by Probleme_FTD_IJK_base::preparer_calcul().
rk3_sub_step()
void Navier_Stokes_FTD_IJK::rk3_sub_step (const int rk_step, const double total_timestep, const double fractionnal_timestep, const double time)
References boundary_conditions_, calculer_dv(), calculer_grad_p_moyen(), calculer_grad_p_over_rho_moyen(), calculer_vitesse_gauche(), d_pressure_, d_velocity_, IJK_Shear_Periodic_helpler::defilement_, disable_solveur_poisson_, epaisseur_maille_, Process::exit(), frozen_velocity_, include_pressure_gradient_in_ustar_, interfaces_, inv_rho_field_, Process::je_suis_maitre(), Statistiques::last_time(), milieu_ijk(), nb_diam_ortho_shear_perio_, nb_diam_upstream_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), poisson_solver_, pression_ap_proj_, pressure_, pressure_rhs_, rho_field_, RK3_F_pressure_, RK3_F_velocity_, stencil_vitesse_entree_, terme_pression_bis_, terme_pression_ter_, update_v_or_rhov(), upstream_dir_, upstream_stencil_, use_inv_rho_in_poisson_solver_, velocity_, vitesse_entree_, vitesse_entree_compo_to_force_, vitesse_entree_dir_, and vitesse_upstream_.
euler_time_step()
void Navier_Stokes_FTD_IJK::euler_time_step (ArrOfDouble & var_volume_par_bulle)
References Parser::addVar(), boundary_conditions_, calculer_dv(), calculer_grad_p_moyen(), calculer_grad_p_over_rho_moyen(), calculer_vitesse_gauche(), d_pressure_, d_velocity_, IJK_Shear_Periodic_helpler::defilement_, disable_solveur_poisson_, epaisseur_maille_, euler_explicit_update(), Parser::eval(), expression_vitesse_upstream_, frozen_velocity_, Fluide_Diphasique_IJK::get_direction_gravite(), Schema_Temps_IJK_base::get_timestep(), Schema_Temps_IJK_base::get_tstep(), include_pressure_gradient_in_ustar_, interfaces_, inv_rho_field_, Statistiques::last_time(), milieu_ijk(), nb_diam_ortho_shear_perio_, nb_diam_upstream_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), Parser::parseString(), poisson_solver_, pression_ap_proj_, pressure_, pressure_ghost_cells_, pressure_rhs_, rho_du_euler_ap_prediction_, rho_du_euler_ap_prediction_champ_, rho_du_euler_ap_projection_, rho_du_euler_ap_projection_champ_, rho_field_, rho_u_euler_ap_projection_, rho_u_euler_ap_projection_champ_, rho_u_euler_av_prediction_, rho_u_euler_av_prediction_champ_, schema_temps_ijk(), Parser::setNbVar(), Parser::setString(), Parser::setVar(), stencil_vitesse_entree_, terme_pression_bis_, terme_pression_ter_, test_etapes_et_bilan_, update_v_or_rhov(), upstream_dir_, upstream_stencil_, upstream_velocity_bubble_factor_, upstream_velocity_bubble_factor_deriv_, upstream_velocity_bubble_factor_integral_, upstream_velocity_measured_, use_inv_rho_in_poisson_solver_, TRUST_Ref< _CLASSE_ >::valeur(), velocity_, velocity_bubble_integral_err_, velocity_bubble_new_, velocity_bubble_old_, velocity_bubble_scope_, vitesse_entree_, vitesse_entree_compo_to_force_, vitesse_entree_dir_, vitesse_upstream_, and vitesse_upstream_reprise_.
Referenced by Probleme_FTD_IJK_base::euler_time_step().
update_v_or_rhov()
void Navier_Stokes_FTD_IJK::update_v_or_rhov (bool with_p = false)
References boundary_conditions_, IJK_Field_vector< T, N >::echange_espace_virtuel(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel(), Boundary_Conditions::get_correction_conserv_qdm(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost(), pressure_, rho_field_, update_rho_v(), update_v_ghost_from_rho_v(), and velocity_.
Referenced by euler_time_step(), Probleme_FTD_IJK_base::euler_time_step(), rk3_sub_step(), and Probleme_FTD_IJK_base::solveTimeStep().
corriger_qdm()
void Navier_Stokes_FTD_IJK::corriger_qdm ()
References compute_and_add_qdm_corrections(), compute_and_add_qdm_corrections_monophasic(), Option_IJK::DISABLE_DIPHASIQUE, corrections_qdm::is_type_none(), qdm_corrections_, set_time_for_corrections(), terme_source_acceleration_, corrections_qdm::write_me(), and write_qdm_corrections_information().
Referenced by Probleme_FTD_IJK_base::solveTimeStep().
build_redistribute_extended_splitting_ft()
void Navier_Stokes_FTD_IJK::build_redistribute_extended_splitting_ft ()
References Probleme_FTD_IJK_base::domaine_ijk(), Domaine_IJK::ELEM, Domaine_IJK::FACES_I, Domaine_IJK::FACES_J, Domaine_IJK::FACES_K, Domaine_IJK::ft_extension(), Probleme_FTD_IJK_base::get_domaine_ft(), Domaine_IJK::get_nb_items_global(), Domaine_IJK::get_periodic_flag(), Redistribute_Field::initialize(), probleme_ijk(), redistribute_from_splitting_ft_elem_, redistribute_from_splitting_ft_elem_ghostz_max_, redistribute_from_splitting_ft_elem_ghostz_min_, redistribute_from_splitting_ft_faces_, redistribute_to_splitting_ft_elem_, and redistribute_to_splitting_ft_faces_.
test_etapes_et_bilan_rho_u_euler()
void Navier_Stokes_FTD_IJK::test_etapes_et_bilan_rho_u_euler (bool apres)
References rho_field_, rho_u_euler_ap_rho_mu_ind_, rho_u_euler_ap_rho_mu_ind_champ_, rho_u_euler_av_rho_mu_ind_, rho_u_euler_av_rho_mu_ind_champ_, test_etapes_et_bilan_, u_euler_ap_rho_mu_ind_, and velocity_.
Referenced by Probleme_FTD_IJK_base::solveTimeStep_Euler(), and Probleme_FTD_IJK_base::solveTimeStep_RK3().
deplacer_interfaces()
void Navier_Stokes_FTD_IJK::deplacer_interfaces (const double timestep, const int rk_step, ArrOfDouble & var_volume_par_bulle, const int first_step_interface_smoothing)
References centre_gravite_bulles_, correction_semi_locale_volume_bulle_, interfaces_, mean_bubble_rotation_vector_, probleme_ijk(), schema_temps_ijk(), Probleme_FTD_IJK_base::update_post_remeshing_indicator_field(), Probleme_FTD_IJK_base::update_pre_remeshing_indicator_field(), and vitesses_translation_bulles_.
Referenced by Probleme_FTD_IJK_base::deplacer_interfaces().
deplacer_interfaces_rk3()
void Navier_Stokes_FTD_IJK::deplacer_interfaces_rk3 (const double timestep, const int rk_step, ArrOfDouble & var_volume_par_bulle)
References Statistiques::begin_count(), calculer_vitesse_ft(), centre_gravite_bulles_, correction_semi_locale_volume_bulle_, Statistiques::end_count(), interfaces_, mean_bubble_rotation_vector_, Statistiques::new_counter(), probleme_ijk(), schema_temps_ijk(), Probleme_FTD_IJK_base::update_indicator_field(), update_indicatrice_variables_monofluides(), Probleme_FTD_IJK_base::update_post_remeshing_indicator_field(), Probleme_FTD_IJK_base::update_pre_remeshing_indicator_field(), and vitesses_translation_bulles_.
calculer_vitesse_ft()
void Navier_Stokes_FTD_IJK::calculer_vitesse_ft ()
References boundary_conditions_, IJK_Shear_Periodic_helpler::defilement_, Probleme_FTD_IJK_base::domaine_ijk(), Domaine_IJK::ft_extension(), Boundary_Conditions::get_dU_perio(), Boundary_Conditions::get_resolution_u_prime_(), probleme_ijk(), redistribute_to_splitting_ft_faces_, velocity_, and velocity_ft_.
Referenced by Probleme_FTD_IJK_base::deplacer_interfaces(), and deplacer_interfaces_rk3().
update_indicatrice_variables_monofluides()
void Navier_Stokes_FTD_IJK::update_indicatrice_variables_monofluides ()
References boundary_conditions_, IJK_Shear_Periodic_helpler::defilement_, Boundary_Conditions::get_correction_interp_monofluide(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_shear_BC_helpler(), I_ns_, interfaces_, inv_rho_field_, kappa_ft_, kappa_ns_, milieu_ijk(), molecular_mu_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), pressure_, Redistribute_Field::redistribute(), redistribute_from_splitting_ft_elem_ghostz_max_, redistribute_from_splitting_ft_elem_ghostz_min_, rho_field_, IJK_Shear_Periodic_helpler::set_I_sig_kappa_zmax_(), IJK_Shear_Periodic_helpler::set_I_sig_kappa_zmin_(), IJK_Shear_Periodic_helpler::set_indicatrice_ghost_zmax_(), IJK_Shear_Periodic_helpler::set_indicatrice_ghost_zmin_(), and use_inv_rho_.
Referenced by Probleme_FTD_IJK_base::deplacer_interfaces(), and deplacer_interfaces_rk3().
sauvegarder_equation()
void Navier_Stokes_FTD_IJK::sauvegarder_equation (const Nom & lataname, SFichier & fichier) const
References forcage_, Schema_Temps_IJK_base::get_current_time(), interfaces_, liq_velocity_tmoy_, probleme_ijk(), qdm_corrections_, schema_temps_ijk(), terme_source_acceleration_, TRUST_Ref< _CLASSE_ >::valeur(), vap_velocity_tmoy_, velocity_bubble_old_, and vitesse_upstream_reprise_.
Referenced by Probleme_FTD_IJK_base::sauvegarder_probleme().
set_fichier_reprise_vitesse()
void Navier_Stokes_FTD_IJK::set_fichier_reprise_vitesse (const Nom & prefix) inline
References fichier_reprise_vitesse_.
Referenced by Probleme_FTD_IJK_base::reprendre_probleme().
create_forced_dilation()
void Navier_Stokes_FTD_IJK::create_forced_dilation ()
References coeff_evol_volume_, Schema_Temps_IJK_base::get_timestep(), interfaces_, schema_temps_ijk(), vol_bulle_monodisperse_, and vol_bulles_.
get_flag_variable_source()
bool Navier_Stokes_FTD_IJK::get_flag_variable_source () const inline
References flag_variable_source_.
initialise_velocity_using_expression()
void Navier_Stokes_FTD_IJK::initialise_velocity_using_expression (const Noms & expression_vitesse_initiale) protected
References IJK_Field_vector< T, N >::echange_espace_virtuel(), Process::exit(), expression_vitesse_initiale_, TRUST_Vector< _CLASSE_ >::size(), and velocity_.
Referenced by initialise_ijk_fields().
initialise_velocity_from_file()
void Navier_Stokes_FTD_IJK::initialise_velocity_from_file (const Nom & fichier_reprise_vitesse) protected
References add_initial_field_, IJK_Field_vector< T, N >::echange_espace_virtuel(), expression_vitesse_initiale_, IJK_Field_vector< T, N >::get_domaine(), Domaine_base::le_nom(), timestep_reprise_vitesse_, and velocity_.
Referenced by initialise_ijk_fields().
Friends And Related Function Documentation
Postprocessing_IJK
friend class Postprocessing_IJK friend
Statistiques_dns_ijk_FT
friend class Statistiques_dns_ijk_FT friend
Member Data Documentation
info_obj
const Type_info Navier_Stokes_FTD_IJK::info_obj static
interfaces_
TRUST_Ref< IJK_Interfaces *> Navier_Stokes_FTD_IJK::interfaces_ protected
Referenced by associer_interfaces(), calculer_dv(), calculer_moyenne_de_phase_liq(), calculer_moyenne_de_phase_vap(), calculer_terme_asservissement(), calculer_terme_source_acceleration(), calculer_true_moyenne_de_phase_liq(), calculer_true_moyenne_de_phase_vap(), calculer_vitesse_droite(), calculer_vitesse_gauche(), complete_initialise_ijk_fields(), completer(), compute_add_external_forces(), compute_add_THI_force_sur_d_velocity(), compute_and_add_qdm_corrections(), compute_correction_for_momentum_balance(), compute_var_volume_par_bulle(), create_forced_dilation(), deplacer_interfaces(), deplacer_interfaces_rk3(), euler_time_step(), fill_variable_source_and_potential_phi(), initialise_ijk_fields(), maj_indicatrice_rho_mu(), preparer_calcul(), projeter(), rk3_sub_step(), sauvegarder_equation(), and update_indicatrice_variables_monofluides().
rho_moyen_
double Navier_Stokes_FTD_IJK::rho_moyen_ = 0. protected
Referenced by compute_add_THI_force_sur_d_velocity(), and preparer_calcul().
rho_field_
IJK_Field_double Navier_Stokes_FTD_IJK::rho_field_ protected
Referenced by calculer_dv(), calculer_terme_source_acceleration(), complete_initialise_ijk_fields(), compute_add_THI_force_sur_d_velocity(), compute_and_add_qdm_corrections(), euler_time_step(), get_rho_field(), get_rho_field_ijk(), initialise_ijk_fields(), initialise_ns_fields(), maj_indicatrice_rho_mu(), preparer_calcul(), projeter(), rk3_sub_step(), test_etapes_et_bilan_rho_u_euler(), update_indicatrice_variables_monofluides(), update_rho_v(), update_v_ghost_from_rho_v(), update_v_or_rhov(), and write_qdm_corrections_information().
inv_rho_field_
IJK_Field_double Navier_Stokes_FTD_IJK::inv_rho_field_ protected
Referenced by calculer_dv(), complete_initialise_ijk_fields(), euler_time_step(), initialise_ijk_fields(), initialise_ns_fields(), maj_indicatrice_rho_mu(), projeter(), rk3_sub_step(), and update_indicatrice_variables_monofluides().
molecular_mu_
IJK_Field_double Navier_Stokes_FTD_IJK::molecular_mu_ protected
Referenced by calculer_dv(), complete_initialise_ijk_fields(), get_molecular_mu(), initialise_ijk_fields(), initialise_ns_fields(), maj_indicatrice_rho_mu(), preparer_calcul(), and update_indicatrice_variables_monofluides().
use_harmonic_viscosity_
int Navier_Stokes_FTD_IJK::use_harmonic_viscosity_ = 0 protected
Referenced by set_param().
velocity_diffusion_op_
Operateur_IJK_faces_diff Navier_Stokes_FTD_IJK::velocity_diffusion_op_ protected
Referenced by calculer_dv(), initialise_ns_fields(), and set_param().
velocity_convection_op_
Operateur_IJK_faces_conv Navier_Stokes_FTD_IJK::velocity_convection_op_ protected
Referenced by calculer_dv(), initialise_ns_fields(), and set_param().
redistribute_to_splitting_ft_faces_
FixedVector<Redistribute_Field, 3> Navier_Stokes_FTD_IJK::redistribute_to_splitting_ft_faces_ protected
Referenced by build_redistribute_extended_splitting_ft(), and calculer_vitesse_ft().
redistribute_from_splitting_ft_faces_
FixedVector<Redistribute_Field, 3> Navier_Stokes_FTD_IJK::redistribute_from_splitting_ft_faces_ protected
Referenced by build_redistribute_extended_splitting_ft(), calculer_dv(), compute_add_external_forces(), get_IJK_field_vector(), get_redistribute_from_splitting_ft_faces(), projeter(), and transfer_ft_to_ns().
redistribute_from_splitting_ft_elem_
Redistribute_Field Navier_Stokes_FTD_IJK::redistribute_from_splitting_ft_elem_ protected
Referenced by build_redistribute_extended_splitting_ft(), redistrib_from_ft_elem(), redistribute_from_splitting_ft_elem(), and Postprocessing_IJK::update_stat_ft().
redistribute_from_splitting_ft_elem_ghostz_
Redistribute_Field Navier_Stokes_FTD_IJK::redistribute_from_splitting_ft_elem_ghostz_ protected
redistribute_from_splitting_ft_elem_ghostz_min_
Redistribute_Field Navier_Stokes_FTD_IJK::redistribute_from_splitting_ft_elem_ghostz_min_ protected
Referenced by build_redistribute_extended_splitting_ft(), complete_initialise_ijk_fields(), initialise_ijk_fields(), and update_indicatrice_variables_monofluides().
redistribute_from_splitting_ft_elem_ghostz_max_
Redistribute_Field Navier_Stokes_FTD_IJK::redistribute_from_splitting_ft_elem_ghostz_max_ protected
Referenced by build_redistribute_extended_splitting_ft(), complete_initialise_ijk_fields(), initialise_ijk_fields(), and update_indicatrice_variables_monofluides().
redistribute_to_splitting_ft_elem_
Redistribute_Field Navier_Stokes_FTD_IJK::redistribute_to_splitting_ft_elem_ protected
Referenced by build_redistribute_extended_splitting_ft(), Postprocessing_IJK::compute_extended_pressures(), redistrib_to_ft_elem(), and redistribute_to_splitting_ft_elem().
le_fluide_
TRUST_Ref< Milieu_base *> Navier_Stokes_FTD_IJK::le_fluide_ protected
Referenced by associer_milieu_base(), and milieu().
poisson_solver_
Multigrille_Adrien Navier_Stokes_FTD_IJK::poisson_solver_ protected
Referenced by euler_time_step(), initialise_ns_fields(), projeter(), rk3_sub_step(), and set_param().
expression_vitesse_initiale_
Noms Navier_Stokes_FTD_IJK::expression_vitesse_initiale_ protected
Referenced by initialise_ijk_fields(), initialise_velocity_from_file(), initialise_velocity_using_expression(), Navier_Stokes_FTD_IJK(), and set_param().
expression_pression_initiale_
Nom Navier_Stokes_FTD_IJK::expression_pression_initiale_ protected
Referenced by completer(), initialise_ijk_fields(), and set_param().
expression_vitesse_upstream_
Nom Navier_Stokes_FTD_IJK::expression_vitesse_upstream_ protected
Referenced by euler_time_step(), and set_param().
upstream_dir_
int Navier_Stokes_FTD_IJK::upstream_dir_ = -1 protected
Referenced by euler_time_step(), get_upstream_dir(), rk3_sub_step(), and set_param().
upstream_stencil_
int Navier_Stokes_FTD_IJK::upstream_stencil_ = 3 protected
Referenced by euler_time_step(), get_upstream_stencil(), rk3_sub_step(), and set_param().
upstream_velocity_measured_
int Navier_Stokes_FTD_IJK::upstream_velocity_measured_ = 0 protected
Referenced by euler_time_step(), get_upstream_velocity_measured(), and set_param().
harmonic_nu_in_diff_operator_
int Navier_Stokes_FTD_IJK::harmonic_nu_in_diff_operator_ = 0 protected
Referenced by initialise_ns_fields(), and set_param().
harmonic_nu_in_calc_with_indicatrice_
int Navier_Stokes_FTD_IJK::harmonic_nu_in_calc_with_indicatrice_ = 0 protected
Referenced by maj_indicatrice_rho_mu(), and set_param().
vitesse_entree_dir_
int Navier_Stokes_FTD_IJK::vitesse_entree_dir_ = 0 protected
Referenced by euler_time_step(), rk3_sub_step(), and set_param().
vitesse_entree_compo_to_force_
int Navier_Stokes_FTD_IJK::vitesse_entree_compo_to_force_ = -1 protected
Referenced by euler_time_step(), rk3_sub_step(), and set_param().
stencil_vitesse_entree_
int Navier_Stokes_FTD_IJK::stencil_vitesse_entree_ = 3 protected
Referenced by euler_time_step(), rk3_sub_step(), and set_param().
test_etapes_et_bilan_
int Navier_Stokes_FTD_IJK::test_etapes_et_bilan_ = 0 protected
Referenced by calculer_dv(), euler_time_step(), initialise_ns_fields(), set_param(), test_etapes_et_bilan_rho_u_euler(), and write_check_etapes_et_termes().
add_initial_field_
int Navier_Stokes_FTD_IJK::add_initial_field_ = 0 protected
Referenced by initialise_velocity_from_file(), and set_param().
diffusion_alternative_
int Navier_Stokes_FTD_IJK::diffusion_alternative_ = 0 protected
Referenced by calculer_dv(), completer(), initialise_ns_fields(), and set_param().
suppression_rejetons_
int Navier_Stokes_FTD_IJK::suppression_rejetons_ = 0 protected
Referenced by get_suppression_rejetons(), and set_param().
use_inv_rho_for_mass_solver_and_calculer_rho_v_
int Navier_Stokes_FTD_IJK::use_inv_rho_for_mass_solver_and_calculer_rho_v_ = 0 protected
Referenced by calculer_dv(), completer(), set_param(), and update_rho_v().
use_inv_rho_in_poisson_solver_
int Navier_Stokes_FTD_IJK::use_inv_rho_in_poisson_solver_ = 0 protected
Referenced by completer(), euler_time_step(), initialise_ns_fields(), projeter(), rk3_sub_step(), and set_param().
use_inv_rho_
int Navier_Stokes_FTD_IJK::use_inv_rho_ = 0 protected
Referenced by complete_initialise_ijk_fields(), completer(), initialise_ijk_fields(), initialise_ns_fields(), maj_indicatrice_rho_mu(), and update_indicatrice_variables_monofluides().
improved_initial_pressure_guess_
int Navier_Stokes_FTD_IJK::improved_initial_pressure_guess_ = 0 protected
Referenced by get_improved_initial_pressure_guess(), projeter(), and set_param().
include_pressure_gradient_in_ustar_
int Navier_Stokes_FTD_IJK::include_pressure_gradient_in_ustar_ = 0 protected
Referenced by calculer_dv(), completer(), euler_time_step(), initialise_ns_fields(), rk3_sub_step(), and set_param().
correction_bilan_qdm_
int Navier_Stokes_FTD_IJK::correction_bilan_qdm_ = 0 protected
refuse_patch_conservation_QdM_RK3_source_interf_
int Navier_Stokes_FTD_IJK::refuse_patch_conservation_QdM_RK3_source_interf_ = 0 protected
Referenced by calculer_dv(), and set_param().
disable_solveur_poisson_
int Navier_Stokes_FTD_IJK::disable_solveur_poisson_ = 0 protected
Referenced by completer(), euler_time_step(), initialise_ns_fields(), projeter(), rk3_sub_step(), and set_param().
resolution_fluctuations_
int Navier_Stokes_FTD_IJK::resolution_fluctuations_ = 0 protected
Referenced by set_param().
projection_initiale_demandee_
int Navier_Stokes_FTD_IJK::projection_initiale_demandee_ = 0 protected
Referenced by projeter(), and set_param().
disable_diffusion_qdm_
int Navier_Stokes_FTD_IJK::disable_diffusion_qdm_ = 0 protected
Referenced by calculer_dv(), get_disable_diffusion_qdm(), and set_param().
disable_convection_qdm_
int Navier_Stokes_FTD_IJK::disable_convection_qdm_ = 0 protected
Referenced by calculer_dv(), get_disable_convection_qdm(), and set_param().
disable_source_interf_
int Navier_Stokes_FTD_IJK::disable_source_interf_ = 0 protected
Referenced by calculer_dv(), and set_param().
frozen_velocity_
int Navier_Stokes_FTD_IJK::frozen_velocity_ = 0 protected
Referenced by completer(), euler_time_step(), rk3_sub_step(), and set_param().
velocity_reset_
int Navier_Stokes_FTD_IJK::velocity_reset_ = 0 protected
Referenced by calculer_dv(), and set_param().
nb_diam_upstream_
double Navier_Stokes_FTD_IJK::nb_diam_upstream_ = 0. protected
Referenced by euler_time_step(), get_nb_diam_upstream(), rk3_sub_step(), and set_param().
nb_diam_ortho_shear_perio_
double Navier_Stokes_FTD_IJK::nb_diam_ortho_shear_perio_ = -1.1e20 protected
Referenced by euler_time_step(), rk3_sub_step(), and set_param().
vitesse_entree_
double Navier_Stokes_FTD_IJK::vitesse_entree_ = -1.1e20 protected
Referenced by euler_time_step(), rk3_sub_step(), and set_param().
vitesse_upstream_
double Navier_Stokes_FTD_IJK::vitesse_upstream_ = -1.1e20 protected
Referenced by euler_time_step(), get_vitesse_upstream(), rk3_sub_step(), and set_param().
vitesse_upstream_reprise_
double Navier_Stokes_FTD_IJK::vitesse_upstream_reprise_ = -1.1e20 protected
Referenced by euler_time_step(), sauvegarder_equation(), and set_param_reprise_pb().
velocity_bubble_new_
double Navier_Stokes_FTD_IJK::velocity_bubble_new_ = 0. protected
Referenced by euler_time_step().
velocity_bubble_old_
double Navier_Stokes_FTD_IJK::velocity_bubble_old_ = -1.1e20 protected
Referenced by euler_time_step(), sauvegarder_equation(), and set_param_reprise_pb().
velocity_bubble_integral_err_
double Navier_Stokes_FTD_IJK::velocity_bubble_integral_err_ = 0. protected
Referenced by euler_time_step().
velocity_bubble_scope_
double Navier_Stokes_FTD_IJK::velocity_bubble_scope_ = 0. protected
Referenced by euler_time_step(), and set_param().
upstream_velocity_bubble_factor_
double Navier_Stokes_FTD_IJK::upstream_velocity_bubble_factor_ = 1. protected
Referenced by euler_time_step(), and set_param().
upstream_velocity_bubble_factor_deriv_
double Navier_Stokes_FTD_IJK::upstream_velocity_bubble_factor_deriv_ = 0. protected
Referenced by euler_time_step(), and set_param().
upstream_velocity_bubble_factor_integral_
double Navier_Stokes_FTD_IJK::upstream_velocity_bubble_factor_integral_ = 0. protected
Referenced by euler_time_step(), and set_param().
coef_immobilisation_
double Navier_Stokes_FTD_IJK::coef_immobilisation_ = 0. protected
Referenced by calculer_terme_source_acceleration(), compute_add_external_forces(), get_IJK_field_vector(), Postprocessing_IJK::init_integrated_and_ana(), initialise_ijk_fields(), and set_param().
coef_ammortissement_
double Navier_Stokes_FTD_IJK::coef_ammortissement_ = 0. protected
Referenced by compute_add_external_forces(), and set_param().
coef_mean_force_
double Navier_Stokes_FTD_IJK::coef_mean_force_ = 0. protected
Referenced by compute_add_external_forces(), and set_param().
coef_force_time_n_
double Navier_Stokes_FTD_IJK::coef_force_time_n_ = 0. protected
Referenced by compute_add_external_forces(), and set_param().
coef_rayon_force_rappel_
double Navier_Stokes_FTD_IJK::coef_rayon_force_rappel_ = 0. protected
Referenced by compute_add_external_forces(), and set_param().
p_seuil_max_
double Navier_Stokes_FTD_IJK::p_seuil_max_ = 10000000 protected
Referenced by set_param().
p_seuil_min_
double Navier_Stokes_FTD_IJK::p_seuil_min_ = -10000000 protected
Referenced by set_param().
force_rappel_
IJK_Field_vector3_double Navier_Stokes_FTD_IJK::force_rappel_ protected
Referenced by calculer_terme_source_acceleration(), compute_add_external_forces(), get_IJK_field_vector(), and initialise_ijk_fields().
force_rappel_ft_
IJK_Field_vector3_double Navier_Stokes_FTD_IJK::force_rappel_ft_ protected
Referenced by compute_add_external_forces(), get_IJK_field_vector(), and initialise_ijk_fields().
pressure_rhs_
IJK_Field_double Navier_Stokes_FTD_IJK::pressure_rhs_ protected
Referenced by euler_time_step(), initialise_ns_fields(), projeter(), and rk3_sub_step().
pressure_
IJK_Field_double Navier_Stokes_FTD_IJK::pressure_ protected
Referenced by calculer_dv(), complete_initialise_ijk_fields(), compute_correction_for_momentum_balance(), euler_time_step(), get_pressure(), initialise_ijk_fields(), initialise_ns_fields(), projeter(), rk3_sub_step(), update_indicatrice_variables_monofluides(), Statistiques_dns_ijk_FT::update_stat(), and update_v_or_rhov().
pressure_ghost_cells_
IJK_Field_double Navier_Stokes_FTD_IJK::pressure_ghost_cells_ protected
Referenced by euler_time_step(), get_pressure_ghost_cells(), initialise_ns_fields(), and projeter().
velocity_
IJK_Field_vector3_double Navier_Stokes_FTD_IJK::velocity_ protected
Referenced by calculer_dv(), calculer_terme_asservissement(), calculer_terme_source_acceleration(), calculer_vitesse_ft(), compute_add_external_forces(), compute_add_THI_force(), compute_and_add_qdm_corrections(), compute_and_add_qdm_corrections_monophasic(), compute_correction_for_momentum_balance(), euler_time_step(), get_velocity(), initialise_ijk_fields(), initialise_ns_fields(), initialise_velocity_from_file(), initialise_velocity_using_expression(), preparer_calcul(), projeter(), rk3_sub_step(), test_etapes_et_bilan_rho_u_euler(), update_rho_v(), Statistiques_dns_ijk_FT::update_stat(), update_v_ghost_from_rho_v(), update_v_or_rhov(), and write_qdm_corrections_information().
terme_convection_mass_solver_
IJK_Field_vector3_double Navier_Stokes_FTD_IJK::terme_convection_mass_solver_ protected
Referenced by calculer_dv(), and initialise_ns_fields().
terme_diffusion_mass_solver_
IJK_Field_vector3_double Navier_Stokes_FTD_IJK::terme_diffusion_mass_solver_ protected
Referenced by calculer_dv(), and initialise_ns_fields().
rho_u_euler_av_prediction_champ_
IJK_Field_vector3_double Navier_Stokes_FTD_IJK::rho_u_euler_av_prediction_champ_ protected
Referenced by euler_time_step(), and initialise_ns_fields().
rho_du_euler_ap_prediction_champ_
IJK_Field_vector3_double Navier_Stokes_FTD_IJK::rho_du_euler_ap_prediction_champ_ protected
Referenced by euler_time_step(), and initialise_ns_fields().
rho_u_euler_ap_projection_champ_
IJK_Field_vector3_double Navier_Stokes_FTD_IJK::rho_u_euler_ap_projection_champ_ protected
Referenced by euler_time_step(), and initialise_ns_fields().
rho_du_euler_ap_projection_champ_
IJK_Field_vector3_double Navier_Stokes_FTD_IJK::rho_du_euler_ap_projection_champ_ protected
Referenced by euler_time_step(), and initialise_ns_fields().
rho_u_euler_av_rho_mu_ind_champ_
IJK_Field_vector3_double Navier_Stokes_FTD_IJK::rho_u_euler_av_rho_mu_ind_champ_ protected
Referenced by initialise_ns_fields(), and test_etapes_et_bilan_rho_u_euler().
rho_u_euler_ap_rho_mu_ind_champ_
IJK_Field_vector3_double Navier_Stokes_FTD_IJK::rho_u_euler_ap_rho_mu_ind_champ_ protected
Referenced by initialise_ns_fields(), and test_etapes_et_bilan_rho_u_euler().
terme_diffusion_local_
IJK_Field_vector3_double Navier_Stokes_FTD_IJK::terme_diffusion_local_ protected
Referenced by calculer_dv(), and initialise_ns_fields().
terme_pression_local_
IJK_Field_vector3_double Navier_Stokes_FTD_IJK::terme_pression_local_ protected
Referenced by initialise_ns_fields().
terme_pression_in_ustar_local_
IJK_Field_vector3_double Navier_Stokes_FTD_IJK::terme_pression_in_ustar_local_ protected
Referenced by calculer_dv(), and initialise_ns_fields().
d_v_diff_et_conv_
IJK_Field_vector3_double Navier_Stokes_FTD_IJK::d_v_diff_et_conv_ protected
Referenced by calculer_dv(), and initialise_ns_fields().
rho_u_euler_av_prediction_
Vecteur3 Navier_Stokes_FTD_IJK::rho_u_euler_av_prediction_ = {0.,0.,0.} protected
Referenced by euler_time_step(), and write_check_etapes_et_termes().
rho_du_euler_ap_prediction_
Vecteur3 Navier_Stokes_FTD_IJK::rho_du_euler_ap_prediction_ = {0.,0.,0.} protected
Referenced by euler_time_step(), and write_check_etapes_et_termes().
rho_u_euler_ap_projection_
Vecteur3 Navier_Stokes_FTD_IJK::rho_u_euler_ap_projection_ = {0.,0.,0.} protected
Referenced by euler_time_step(), and write_check_etapes_et_termes().
rho_du_euler_ap_projection_
Vecteur3 Navier_Stokes_FTD_IJK::rho_du_euler_ap_projection_ = {0.,0.,0.} protected
Referenced by euler_time_step(), and write_check_etapes_et_termes().
rho_u_euler_av_rho_mu_ind_
Vecteur3 Navier_Stokes_FTD_IJK::rho_u_euler_av_rho_mu_ind_ = {0.,0.,0.} protected
Referenced by test_etapes_et_bilan_rho_u_euler(), and write_check_etapes_et_termes().
rho_u_euler_ap_rho_mu_ind_
Vecteur3 Navier_Stokes_FTD_IJK::rho_u_euler_ap_rho_mu_ind_ = {0.,0.,0.} protected
Referenced by test_etapes_et_bilan_rho_u_euler(), and write_check_etapes_et_termes().
u_euler_ap_rho_mu_ind_
Vecteur3 Navier_Stokes_FTD_IJK::u_euler_ap_rho_mu_ind_ = {0.,0.,0.} protected
Referenced by test_etapes_et_bilan_rho_u_euler(), and write_check_etapes_et_termes().
terme_diffusion_
Vecteur3 Navier_Stokes_FTD_IJK::terme_diffusion_ = {0.,0.,0.} protected
Referenced by calculer_dv(), compute_correction_for_momentum_balance(), and write_check_etapes_et_termes().
terme_convection_
Vecteur3 Navier_Stokes_FTD_IJK::terme_convection_ = {0.,0.,0.} protected
Referenced by calculer_dv(), compute_correction_for_momentum_balance(), and write_check_etapes_et_termes().
terme_pression_
Vecteur3 Navier_Stokes_FTD_IJK::terme_pression_ = {0.,0.,0.} protected
Referenced by compute_correction_for_momentum_balance().
terme_pression_bis_
Vecteur3 Navier_Stokes_FTD_IJK::terme_pression_bis_ = {0.,0.,0.} protected
Referenced by calculer_dv(), euler_time_step(), rk3_sub_step(), and write_check_etapes_et_termes().
terme_pression_ter_
Vecteur3 Navier_Stokes_FTD_IJK::terme_pression_ter_ = {0.,0.,0.} protected
Referenced by calculer_dv(), euler_time_step(), rk3_sub_step(), and write_check_etapes_et_termes().
terme_interfaces_
Vecteur3 Navier_Stokes_FTD_IJK::terme_interfaces_ protected
Referenced by calculer_dv(), and write_check_etapes_et_termes().
terme_pression_in_ustar_
Vecteur3 Navier_Stokes_FTD_IJK::terme_pression_in_ustar_ = {0.,0.,0.} protected
Referenced by calculer_dv().
terme_moyen_convection_mass_solver_
Vecteur3 Navier_Stokes_FTD_IJK::terme_moyen_convection_mass_solver_ = {0.,0.,0.} protected
Referenced by calculer_dv(), and write_check_etapes_et_termes().
terme_moyen_diffusion_mass_solver_
Vecteur3 Navier_Stokes_FTD_IJK::terme_moyen_diffusion_mass_solver_ = {0.,0.,0.} protected
Referenced by calculer_dv(), and write_check_etapes_et_termes().
div_rhou_
IJK_Field_double Navier_Stokes_FTD_IJK::div_rhou_ protected
Referenced by calculer_dv(), and initialise_ns_fields().
d_velocity_
IJK_Field_vector3_double Navier_Stokes_FTD_IJK::d_velocity_ protected
Referenced by calculer_dv(), compute_add_external_forces(), compute_add_THI_force(), compute_add_THI_force_sur_d_velocity(), euler_time_step(), initialise_ns_fields(), projeter(), and rk3_sub_step().
RK3_F_velocity_
IJK_Field_vector3_double Navier_Stokes_FTD_IJK::RK3_F_velocity_ protected
Referenced by initialise_ns_fields(), and rk3_sub_step().
pression_ap_proj_
double Navier_Stokes_FTD_IJK::pression_ap_proj_ = 0. protected
Referenced by euler_time_step(), rk3_sub_step(), and write_check_etapes_et_termes().
vap_velocity_tmoy_
double Navier_Stokes_FTD_IJK::vap_velocity_tmoy_ = 0. protected
Referenced by calculer_terme_source_acceleration(), sauvegarder_equation(), set_param(), and set_param_reprise_pb().
liq_velocity_tmoy_
double Navier_Stokes_FTD_IJK::liq_velocity_tmoy_ = 0. protected
Referenced by calculer_terme_source_acceleration(), sauvegarder_equation(), set_param(), and set_param_reprise_pb().
compute_rising_velocities_
int Navier_Stokes_FTD_IJK::compute_rising_velocities_ = 0 protected
Referenced by get_compute_rising_velocities().
fill_rising_velocities_
int Navier_Stokes_FTD_IJK::fill_rising_velocities_ = 0 protected
Referenced by get_fill_rising_velocities().
qdm_corrections_
corrections_qdm Navier_Stokes_FTD_IJK::qdm_corrections_ protected
Referenced by calculer_terme_source_acceleration(), compute_and_add_qdm_corrections(), compute_and_add_qdm_corrections_monophasic(), corriger_qdm(), sauvegarder_equation(), set_param(), set_param_reprise_pb(), set_time_for_corrections(), and write_qdm_corrections_information().
vol_bulle_monodisperse_
double Navier_Stokes_FTD_IJK::vol_bulle_monodisperse_ = -1 protected
Referenced by calculer_terme_asservissement(), calculer_terme_source_acceleration(), completer(), create_forced_dilation(), initialise_ijk_fields(), and set_param().
diam_bulle_monodisperse_
double Navier_Stokes_FTD_IJK::diam_bulle_monodisperse_ = -1 protected
Referenced by completer(), and set_param().
vol_bulles_
ArrOfDouble Navier_Stokes_FTD_IJK::vol_bulles_ protected
Referenced by completer(), compute_var_volume_par_bulle(), create_forced_dilation(), initialise_ijk_fields(), Navier_Stokes_FTD_IJK(), and set_param().
coeff_evol_volume_
double Navier_Stokes_FTD_IJK::coeff_evol_volume_ = 0. protected
Referenced by create_forced_dilation(), and set_param().
d_pressure_
IJK_Field_double Navier_Stokes_FTD_IJK::d_pressure_ protected
Referenced by euler_time_step(), initialise_ns_fields(), and rk3_sub_step().
RK3_F_pressure_
IJK_Field_double Navier_Stokes_FTD_IJK::RK3_F_pressure_ protected
Referenced by initialise_ns_fields(), and rk3_sub_step().
terme_source_interfaces_ft_
IJK_Field_vector3_double Navier_Stokes_FTD_IJK::terme_source_interfaces_ft_ protected
Referenced by calculer_dv(), initialise_ns_fields(), projeter(), and Statistiques_dns_ijk_FT::update_stat().
terme_repulsion_interfaces_ft_
IJK_Field_vector3_double Navier_Stokes_FTD_IJK::terme_repulsion_interfaces_ft_ protected
Referenced by calculer_dv(), initialise_ns_fields(), projeter(), transfer_ft_to_ns(), and Statistiques_dns_ijk_FT::update_stat().
terme_abs_repulsion_interfaces_ft_
IJK_Field_vector3_double Navier_Stokes_FTD_IJK::terme_abs_repulsion_interfaces_ft_ protected
Referenced by calculer_dv(), initialise_ns_fields(), projeter(), and transfer_ft_to_ns().
terme_source_interfaces_ns_
IJK_Field_vector3_double Navier_Stokes_FTD_IJK::terme_source_interfaces_ns_ protected
Referenced by calculer_dv(), calculer_terme_source_acceleration(), compute_correction_for_momentum_balance(), and initialise_ns_fields().
backup_terme_source_interfaces_ns_
IJK_Field_vector3_double Navier_Stokes_FTD_IJK::backup_terme_source_interfaces_ns_ protected
Referenced by initialise_ns_fields().
backup_terme_source_interfaces_ft_
IJK_Field_vector3_double Navier_Stokes_FTD_IJK::backup_terme_source_interfaces_ft_ protected
Referenced by initialise_ns_fields().
terme_repulsion_interfaces_ns_
IJK_Field_vector3_double Navier_Stokes_FTD_IJK::terme_repulsion_interfaces_ns_ protected
Referenced by calculer_dv(), initialise_ns_fields(), and transfer_ft_to_ns().
terme_abs_repulsion_interfaces_ns_
IJK_Field_vector3_double Navier_Stokes_FTD_IJK::terme_abs_repulsion_interfaces_ns_ protected
Referenced by initialise_ns_fields(), and transfer_ft_to_ns().
unit_
IJK_Field_double Navier_Stokes_FTD_IJK::unit_ protected
Referenced by calculer_dv(), and initialise_ns_fields().
zero_field_ft_
IJK_Field_vector3_double Navier_Stokes_FTD_IJK::zero_field_ft_ protected
Referenced by initialise_ns_fields().
laplacien_velocity_
IJK_Field_vector3_double Navier_Stokes_FTD_IJK::laplacien_velocity_ protected
Referenced by calculer_dv(), and initialise_ns_fields().
kappa_ft_
IJK_Field_double Navier_Stokes_FTD_IJK::kappa_ft_ protected
Referenced by complete_initialise_ijk_fields(), initialise_ijk_fields(), initialise_ns_fields(), and update_indicatrice_variables_monofluides().
kappa_ns_
IJK_Field_double Navier_Stokes_FTD_IJK::kappa_ns_ protected
Referenced by complete_initialise_ijk_fields(), initialise_ijk_fields(), initialise_ns_fields(), and update_indicatrice_variables_monofluides().
I_ns_
IJK_Field_double Navier_Stokes_FTD_IJK::I_ns_ protected
Referenced by complete_initialise_ijk_fields(), initialise_ijk_fields(), initialise_ns_fields(), and update_indicatrice_variables_monofluides().
terme_interfaces_bf_mass_solver_
Vecteur3 Navier_Stokes_FTD_IJK::terme_interfaces_bf_mass_solver_ = {0.,0.,0.} protected
Referenced by calculer_dv(), and write_check_etapes_et_termes().
terme_interfaces_bf_mass_solver_bis_
Vecteur3 Navier_Stokes_FTD_IJK::terme_interfaces_bf_mass_solver_bis_ = {0.,0.,0.} protected
Referenced by calculer_dv(), and write_check_etapes_et_termes().
terme_interfaces_af_mass_solver_
Vecteur3 Navier_Stokes_FTD_IJK::terme_interfaces_af_mass_solver_ = {0.,0.,0.} protected
Referenced by calculer_dv(), and write_check_etapes_et_termes().
terme_interfaces_conv_diff_mass_solver_
Vecteur3 Navier_Stokes_FTD_IJK::terme_interfaces_conv_diff_mass_solver_ = {0.,0.,0.} protected
Referenced by calculer_dv().
use_bubbles_velocities_from_interface_
int Navier_Stokes_FTD_IJK::use_bubbles_velocities_from_interface_ = 0 protected
Referenced by get_use_bubbles_velocities_from_interface().
use_bubbles_velocities_from_barycentres_
int Navier_Stokes_FTD_IJK::use_bubbles_velocities_from_barycentres_ = 0 protected
Referenced by get_use_bubbles_velocities_from_barycentres().
type_surface_efficace_face_
TYPE_SURFACE_EFFICACE_FACE Navier_Stokes_FTD_IJK::type_surface_efficace_face_ = TYPE_SURFACE_EFFICACE_FACE::NON_INITIALISE protected
type_surface_efficace_interface_
TYPE_SURFACE_EFFICACE_INTERFACE Navier_Stokes_FTD_IJK::type_surface_efficace_interface_ = TYPE_SURFACE_EFFICACE_INTERFACE::NON_INITIALISE protected
deactivate_remeshing_velocity_
int Navier_Stokes_FTD_IJK::deactivate_remeshing_velocity_ = 0 protected
vitesses_translation_bulles_
DoubleTab Navier_Stokes_FTD_IJK::vitesses_translation_bulles_ protected
Referenced by deplacer_interfaces(), and deplacer_interfaces_rk3().
mean_bubble_rotation_vector_
DoubleTab Navier_Stokes_FTD_IJK::mean_bubble_rotation_vector_ protected
Referenced by deplacer_interfaces(), and deplacer_interfaces_rk3().
centre_gravite_bulles_
DoubleTab Navier_Stokes_FTD_IJK::centre_gravite_bulles_ protected
Referenced by deplacer_interfaces(), and deplacer_interfaces_rk3().
correction_semi_locale_volume_bulle_
int Navier_Stokes_FTD_IJK::correction_semi_locale_volume_bulle_ = 0 protected
Referenced by compute_var_volume_par_bulle(), deplacer_interfaces(), deplacer_interfaces_rk3(), projeter(), and set_param().
velocity_ft_
IJK_Field_vector3_double Navier_Stokes_FTD_IJK::velocity_ft_ protected
Referenced by calculer_vitesse_ft(), get_velocity_ft(), and initialise_ns_fields().
Kp_
double Navier_Stokes_FTD_IJK::Kp_ = 0. protected
Referenced by calculer_dv(), calculer_terme_asservissement(), and set_param().
Kd_
double Navier_Stokes_FTD_IJK::Kd_ = 0. protected
Referenced by calculer_dv(), calculer_terme_asservissement(), and set_param().
Ki_
double Navier_Stokes_FTD_IJK::Ki_ = 0. protected
Referenced by calculer_dv(), calculer_terme_asservissement(), and set_param().
int_x_
double Navier_Stokes_FTD_IJK::int_x_ = 0. protected
Referenced by calculer_terme_asservissement().
int_y_
double Navier_Stokes_FTD_IJK::int_y_ = 0. protected
Referenced by calculer_terme_asservissement().
int_z_
double Navier_Stokes_FTD_IJK::int_z_ = 0. protected
Referenced by calculer_terme_asservissement().
epaisseur_maille_
int Navier_Stokes_FTD_IJK::epaisseur_maille_ = 8 protected
Referenced by euler_time_step(), rk3_sub_step(), and set_param().
expression_derivee_acceleration_
Nom Navier_Stokes_FTD_IJK::expression_derivee_acceleration_ = "0" protected
Referenced by calculer_terme_source_acceleration(), completer(), and set_param().
parser_derivee_acceleration_
Parser Navier_Stokes_FTD_IJK::parser_derivee_acceleration_ protected
Referenced by calculer_terme_source_acceleration(), and completer().
expression_variable_source_
Noms Navier_Stokes_FTD_IJK::expression_variable_source_ protected
Referenced by calculer_dv(), completer(), fill_variable_source_and_potential_phi(), initialise_ns_fields(), Navier_Stokes_FTD_IJK(), and set_param().
expression_potential_phi_
Nom Navier_Stokes_FTD_IJK::expression_potential_phi_ = "??" protected
Referenced by calculer_dv(), completer(), fill_variable_source_and_potential_phi(), initialise_ns_fields(), and set_param().
store_rhov_moy_
Vecteur3 Navier_Stokes_FTD_IJK::store_rhov_moy_ protected
Referenced by compute_correction_for_momentum_balance(), and forcage_control_ecoulement().
integrated_residu_
Vecteur3 Navier_Stokes_FTD_IJK::integrated_residu_ = {0.,0.,0.} protected
Referenced by compute_correction_for_momentum_balance().
terme_source_acceleration_
double Navier_Stokes_FTD_IJK::terme_source_acceleration_ = 0. protected
Referenced by calculer_dv(), calculer_terme_source_acceleration(), compute_correction_for_momentum_balance(), corriger_qdm(), initialise_ijk_fields(), sauvegarder_equation(), set_param(), and set_param_reprise_pb().
compute_force_init_
int Navier_Stokes_FTD_IJK::compute_force_init_ = 0 protected
Referenced by initialise_ijk_fields(), and set_param().
terme_source_correction_
ArrOfDouble Navier_Stokes_FTD_IJK::terme_source_correction_ protected
Referenced by calculer_dv(), compute_correction_for_momentum_balance(), and Navier_Stokes_FTD_IJK().
correction_force_
ArrOfInt Navier_Stokes_FTD_IJK::correction_force_ protected
Referenced by calculer_dv(), compute_correction_for_momentum_balance(), Navier_Stokes_FTD_IJK(), and set_param().
rho_v_
IJK_Field_vector3_double Navier_Stokes_FTD_IJK::rho_v_ protected
Referenced by calculer_dv(), calculer_terme_asservissement(), calculer_terme_source_acceleration(), compute_and_add_qdm_corrections(), compute_and_add_qdm_corrections_monophasic(), compute_correction_for_momentum_balance(), forcage_control_ecoulement(), initialise_ns_fields(), update_rho_v(), and update_v_ghost_from_rho_v().
psi_velocity_
IJK_Field_vector3_double Navier_Stokes_FTD_IJK::psi_velocity_ protected
Referenced by initialise_ns_fields().
variable_source_
IJK_Field_vector3_double Navier_Stokes_FTD_IJK::variable_source_ protected
Referenced by calculer_dv(), fill_variable_source_and_potential_phi(), and initialise_ns_fields().
expression_derivee_facteur_variable_source_
Nom Navier_Stokes_FTD_IJK::expression_derivee_facteur_variable_source_ = "0" protected
Referenced by calculer_terme_source_acceleration(), completer(), and set_param().
parser_derivee_facteur_variable_source_
Parser Navier_Stokes_FTD_IJK::parser_derivee_facteur_variable_source_ protected
Referenced by calculer_terme_source_acceleration(), and completer().
facteur_variable_source_
double Navier_Stokes_FTD_IJK::facteur_variable_source_ = 1. protected
Referenced by calculer_dv(), calculer_terme_source_acceleration(), and set_param().
potential_phi_
IJK_Field_double Navier_Stokes_FTD_IJK::potential_phi_ protected
Referenced by fill_variable_source_and_potential_phi(), and initialise_ns_fields().
boundary_conditions_
Boundary_Conditions Navier_Stokes_FTD_IJK::boundary_conditions_ protected
Referenced by calculer_vitesse_ft(), complete_initialise_ijk_fields(), euler_time_step(), get_boundary_conditions(), initialise_ijk_fields(), initialise_ns_fields(), rk3_sub_step(), set_param(), update_indicatrice_variables_monofluides(), update_v_ghost_from_rho_v(), and update_v_or_rhov().
fichier_reprise_vitesse_
Nom Navier_Stokes_FTD_IJK::fichier_reprise_vitesse_ = "??" protected
Referenced by Postprocessing_IJK::init_integrated_and_ana(), initialise_ijk_fields(), set_fichier_reprise_vitesse(), set_param(), and set_param_reprise_pb().
timestep_reprise_vitesse_
int Navier_Stokes_FTD_IJK::timestep_reprise_vitesse_ = 1 protected
Referenced by initialise_velocity_from_file(), set_param(), and set_param_reprise_pb().
forcage_
init_forcage_THI Navier_Stokes_FTD_IJK::forcage_ protected
Referenced by calculer_dv(), calculer_terme_source_acceleration(), compute_add_THI_force(), compute_add_THI_force_sur_d_velocity(), initialise_ijk_fields(), sauvegarder_equation(), set_param(), and set_param_reprise_pb().
champs_compris_
Champs_compris_IJK Navier_Stokes_FTD_IJK::champs_compris_ protected
Referenced by get_IJK_field(), get_IJK_field_vector(), get_noms_champs_postraitables(), has_champ(), has_champ_vectoriel(), initialise_ijk_fields(), and initialise_ns_fields().
flag_variable_source_
bool Navier_Stokes_FTD_IJK::flag_variable_source_ = false protected
Referenced by get_flag_variable_source(), and initialise_ns_fields().