TrioCFD: Cond_lim_base Class Reference
Cond_lim_base Class Reference
#include <Cond_lim_base.h>
Public Member Functions
virtual int a_mettre_a_jour_ss_pas_dt ()
virtual void associer_domaine_cl_dis_base (const Domaine_Cl_dis_base &)
virtual void associer_fr_dis_base (const Frontiere_dis_base &)
virtual void calculer_coeffs_echange (double temps)
virtual int compatible_avec_discr (const Discretisation_base &) const
Domaine_Cl_dis_base & domaine_Cl_dis ()
const Domaine_Cl_dis_base & domaine_Cl_dis () const
virtual Frontiere_dis_base & frontiere_dis ()
virtual const Frontiere_dis_base & frontiere_dis () const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
void set_modifier_val_imp (int)
virtual void verifie_ch_init_nb_comp () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
void err_pas_compatible (const Discretisation_base &) const
void err_pas_compatible (const Equation_base &) const
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
Un objet condition aux limite sert a definir, pour une equation donnee, les conditions aux limites a appliquer sur une frontiere d'un domaine.
Chaque objet Cond_lim_base contient une reference vers l'objet Domaine_Cl_dis_base dont il fait partie.
Chaque objet contient egalement un objet OWN_PTR(Champ_front_base) contenant les valeurs a imposer sur la frontiere.
See also
Cond_lim Domaine_Cl_dis_base Frontiere_dis_base, Classe abstraite dont toutes les objets representant des conditions, aux limites doivent deriver., Methode abstraite:, int compatible_avec_eqn(const Equation_base&) const
Constructor & Destructor Documentation
Cond_lim_base()
Cond_lim_base::Cond_lim_base ()
~Cond_lim_base()
Cond_lim_base::~Cond_lim_base () override
Member Function Documentation
info()
const Type_info * Cond_lim_base::info () static
get_info()
const Type_info * Cond_lim_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
Reimplemented in Entree_fluide_vitesse_imposee_ALE, Cond_lim_k_complique_transition_flux_nul_demi, Cond_lim_k_simple_flux_nul, Cond_lim_omega_demi, Cond_lim_omega_dix, Paroi_frottante_loi, Paroi_frottante_simple, Frontiere_ouverte_vitesse_vortex, Paroi_FT_disc, Sortie_libre_rho_variable, Echange_contact_VDF_FT_Disc, Echange_contact_VDF_FT_Disc_solid, Frontiere_Ouverte_Rayo_transp, Frontiere_Ouverte_temperature_imposee_Rayo_transp, Paroi_Rayo_transp, Echange_contact_Rayo_transp_VDF, Echange_contact_Rayo_transp_sans_relax_VDF, Echange_externe_impose_rayo_transp, Paroi_flux_impose_Rayo_transp, Temperature_imposee_paroi_rayo_transp, Flux_radiatif_base, Frontiere_ouverte_rayo_semi_transp, Frontiere_ouverte_temperature_imposee_rayo_semi_transp, Echange_contact_rayo_semi_transp_VDF, Echange_externe_impose_rayo_semi_transp, Echange_global_impose_rayo_semi_transp, Flux_radiatif_VDF, Neumann_paroi_rayo_semi_transp_VDF, Flux_radiatif_VEF, Neumann_paroi_rayo_semi_transp_VEF, Temperature_imposee_paroi_rayo_semi_transp, Echange_contact_ODVM_VDF, Entree_fluide_K_Eps_impose, Entree_fluide_K_Omega_impose, Paroi_rugueuse, Cond_lim_utilisateur_base, Periodique, Echange_contact_PolyMAC, Echange_contact_PolyMAC_P0, Echange_contact_PolyMAC_P0P1NC, Echange_externe_impose_H, Entree_fluide_temperature_imposee_H, Frontiere_ouverte_rho_u_impose, Neumann_sortie_libre_Temp_H, Temperature_imposee_paroi_H, Sortie_libre_pression_imposee_QC, Dirichlet_paroi_fixe, Entree_fluide_concentration_imposee, Entree_fluide_T_h_imposee, Frottement_externe_impose, Frottement_global_impose, Frottement_impose_base, Neumann_paroi_adiabatique, Neumann_paroi_flux_nul, Neumann_sortie_libre, Paroi_Knudsen_non_negligeable, Sortie_libre_pression_imposee, Sortie_libre_pression_moyenne_imposee, Sortie_libre_Text_H_ext, Temperature_imposee_paroi, Echange_global_impose_turbulent, Paroi_decalee_Robin, Echange_couplage_thermique, Echange_interne_global_impose, Echange_interne_global_parfait, Echange_contact_Colburn_VDF, Echange_contact_Correlation_VDF, Echange_contact_VDF, Echange_contact_VDF_Plaque_Flux_Cte, Echange_interne_impose, Echange_interne_parfait, PlaqThVDF, Sortie_libre_Gradient_Pression_impose, Sortie_libre_Pression_imposee_Orlansky, Echange_contact_Correlation_VEF, Sortie_libre_Gradient_Pression_impose_VEF, Sortie_libre_Gradient_Pression_impose_VEFPreP1B, Sortie_libre_Gradient_Pression_libre_VEF, and Sortie_libre_Gradient_Pression_libre_VEFPreP1B.
self_cast() [1/2]
Cond_lim_base & Cond_lim_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Cond_lim_base & Cond_lim_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Cond_lim_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
Reimplemented in Entree_fluide_vitesse_imposee_ALE, Cond_lim_k_complique_transition_flux_nul_demi, Cond_lim_k_simple_flux_nul, Cond_lim_omega_demi, Cond_lim_omega_dix, Paroi_frottante_loi, Paroi_frottante_simple, Frontiere_ouverte_vitesse_vortex, Paroi_FT_disc, Sortie_libre_rho_variable, Echange_contact_VDF_FT_Disc, Echange_contact_VDF_FT_Disc_solid, Frontiere_Ouverte_Rayo_transp, Frontiere_Ouverte_temperature_imposee_Rayo_transp, Paroi_Rayo_transp, Echange_contact_Rayo_transp_VDF, Echange_contact_Rayo_transp_sans_relax_VDF, Echange_externe_impose_rayo_transp, Paroi_flux_impose_Rayo_transp, Temperature_imposee_paroi_rayo_transp, Flux_radiatif_base, Frontiere_ouverte_rayo_semi_transp, Frontiere_ouverte_temperature_imposee_rayo_semi_transp, Echange_contact_rayo_semi_transp_VDF, Echange_externe_impose_rayo_semi_transp, Echange_global_impose_rayo_semi_transp, Flux_radiatif_VDF, Neumann_paroi_rayo_semi_transp_VDF, Flux_radiatif_VEF, Neumann_paroi_rayo_semi_transp_VEF, Temperature_imposee_paroi_rayo_semi_transp, Echange_contact_ODVM_VDF, Entree_fluide_K_Eps_impose, Entree_fluide_K_Omega_impose, Paroi_rugueuse, Cond_lim_utilisateur_base, Periodique, Echange_contact_PolyMAC, Echange_contact_PolyMAC_P0, Echange_contact_PolyMAC_P0P1NC, Echange_externe_impose_H, Entree_fluide_temperature_imposee_H, Frontiere_ouverte_rho_u_impose, Neumann_sortie_libre_Temp_H, Temperature_imposee_paroi_H, Sortie_libre_pression_imposee_QC, Dirichlet_paroi_fixe, Entree_fluide_concentration_imposee, Entree_fluide_T_h_imposee, Frottement_externe_impose, Frottement_global_impose, Frottement_impose_base, Neumann_paroi_adiabatique, Neumann_paroi_flux_nul, Neumann_sortie_libre, Paroi_Knudsen_non_negligeable, Sortie_libre_pression_imposee, Sortie_libre_pression_moyenne_imposee, Sortie_libre_Text_H_ext, Temperature_imposee_paroi, Echange_global_impose_turbulent, Paroi_decalee_Robin, Echange_couplage_thermique, Echange_interne_global_impose, Echange_interne_global_parfait, Echange_contact_Colburn_VDF, Echange_contact_Correlation_VDF, Echange_contact_VDF, Echange_contact_VDF_Plaque_Flux_Cte, Echange_interne_impose, Echange_interne_parfait, PlaqThVDF, Sortie_libre_Gradient_Pression_impose, Sortie_libre_Pression_imposee_Orlansky, Echange_contact_Correlation_VEF, Sortie_libre_Gradient_Pression_impose_VEF, Sortie_libre_Gradient_Pression_impose_VEFPreP1B, Sortie_libre_Gradient_Pression_libre_VEF, and Sortie_libre_Gradient_Pression_libre_VEFPreP1B.
References le_champ_front.
readOn()
Entree & Cond_lim_base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
Reimplemented in Entree_fluide_vitesse_imposee_ALE, Cond_lim_k_complique_transition_flux_nul_demi, Cond_lim_k_simple_flux_nul, Cond_lim_omega_demi, Cond_lim_omega_dix, Paroi_frottante_loi, Paroi_frottante_simple, Frontiere_ouverte_vitesse_vortex, Paroi_FT_disc, Sortie_libre_rho_variable, Echange_contact_VDF_FT_Disc, Echange_contact_VDF_FT_Disc_solid, Frontiere_Ouverte_Rayo_transp, Frontiere_Ouverte_temperature_imposee_Rayo_transp, Paroi_Rayo_transp, Echange_contact_Rayo_transp_VDF, Echange_contact_Rayo_transp_sans_relax_VDF, Echange_externe_impose_rayo_transp, Paroi_flux_impose_Rayo_transp, Temperature_imposee_paroi_rayo_transp, Flux_radiatif_base, Frontiere_ouverte_rayo_semi_transp, Frontiere_ouverte_temperature_imposee_rayo_semi_transp, Echange_contact_rayo_semi_transp_VDF, Echange_externe_impose_rayo_semi_transp, Echange_global_impose_rayo_semi_transp, Flux_radiatif_VDF, Neumann_paroi_rayo_semi_transp_VDF, Flux_radiatif_VEF, Neumann_paroi_rayo_semi_transp_VEF, Temperature_imposee_paroi_rayo_semi_transp, Echange_contact_ODVM_VDF, Entree_fluide_K_Eps_impose, Entree_fluide_K_Omega_impose, Paroi_rugueuse, Cond_lim_utilisateur_base, Periodique, Echange_contact_PolyMAC, Echange_contact_PolyMAC_P0, Echange_contact_PolyMAC_P0P1NC, Echange_externe_impose_H, Entree_fluide_temperature_imposee_H, Frontiere_ouverte_rho_u_impose, Neumann_sortie_libre_Temp_H, Temperature_imposee_paroi_H, Sortie_libre_pression_imposee_QC, Dirichlet_paroi_fixe, Entree_fluide_concentration_imposee, Entree_fluide_T_h_imposee, Frottement_externe_impose, Frottement_global_impose, Frottement_impose_base, Neumann_paroi_adiabatique, Neumann_paroi_flux_nul, Neumann_sortie_libre, Paroi_Knudsen_non_negligeable, Sortie_libre_pression_imposee, Sortie_libre_pression_moyenne_imposee, Sortie_libre_Text_H_ext, Temperature_imposee_paroi, Echange_global_impose_turbulent, Paroi_decalee_Robin, Echange_couplage_thermique, Echange_interne_global_impose, Echange_interne_global_parfait, Echange_contact_Colburn_VDF, Echange_contact_Correlation_VDF, Echange_contact_VDF, Echange_contact_VDF_Plaque_Flux_Cte, Echange_interne_impose, Echange_interne_parfait, PlaqThVDF, Sortie_libre_Gradient_Pression_impose, Sortie_libre_Pression_imposee_Orlansky, Echange_contact_Correlation_VEF, Sortie_libre_Gradient_Pression_impose_VEF, Sortie_libre_Gradient_Pression_impose_VEFPreP1B, Sortie_libre_Gradient_Pression_libre_VEF, and Sortie_libre_Gradient_Pression_libre_VEFPreP1B.
References le_champ_front.
Referenced by Dirichlet::readOn(), Dirichlet_entree_fluide::readOn(), Dirichlet_paroi_defilante::readOn(), Neumann::readOn(), and Neumann_val_ext::readOn().
completer()
void Cond_lim_base::completer () virtual
NE FAIT RIEN A surcharger dans les classes derivees.
Reimplemented in Cond_lim_k_complique_transition_flux_nul_demi, Cond_lim_k_simple_flux_nul, Cond_lim_omega_demi, Cond_lim_omega_dix, Paroi_frottante_loi, Paroi_frottante_simple, Sortie_libre_rho_variable, Echange_contact_VDF_FT_Disc, Echange_contact_VDF_FT_Disc_solid, Frontiere_Ouverte_Rayo_transp, Frontiere_Ouverte_temperature_imposee_Rayo_transp, Echange_contact_Rayo_transp_VDF, Echange_externe_impose_rayo_transp, Paroi_flux_impose_Rayo_transp, Temperature_imposee_paroi_rayo_transp, Flux_radiatif_base, Frontiere_ouverte_rayo_semi_transp, Frontiere_ouverte_temperature_imposee_rayo_semi_transp, Echange_contact_rayo_semi_transp_VDF, Echange_externe_impose_rayo_semi_transp, Echange_global_impose_rayo_semi_transp, Neumann_paroi_rayo_semi_transp_VDF, Neumann_paroi_rayo_semi_transp_VEF, Temperature_imposee_paroi_rayo_semi_transp, Dirichlet_loi_paroi, Dirichlet_paroi_defilante, Echange_global_impose, Periodique, Echange_contact_PolyMAC, Echange_externe_impose_H, Entree_fluide_temperature_imposee_H, Frontiere_ouverte_rho_u_impose, Neumann_sortie_libre_Temp_H, Temperature_imposee_paroi_H, Sortie_libre_pression_imposee_QC, Frottement_impose_base, Paroi_Knudsen_non_negligeable, Sortie_libre_pression_imposee, Sortie_libre_pression_moyenne_imposee, Echange_couplage_thermique, Echange_interne_global_impose, Echange_contact_Correlation_VDF, Echange_contact_VDF, Echange_interne_impose, Sortie_libre_Gradient_Pression_impose, Sortie_libre_Pression_imposee_Orlansky, Echange_contact_Correlation_VEF, Sortie_libre_Gradient_Pression_libre_VEF, and Sortie_libre_Gradient_Pression_libre_VEFPreP1B.
References champ_front(), and Champ_front_base::completer().
Referenced by Frontiere_Ouverte_Rayo_transp::completer(), Frontiere_Ouverte_temperature_imposee_Rayo_transp::completer(), Echange_externe_impose_rayo_transp::completer(), Temperature_imposee_paroi_rayo_transp::completer(), Flux_radiatif_base::completer(), Frontiere_ouverte_rayo_semi_transp::completer(), Frontiere_ouverte_temperature_imposee_rayo_semi_transp::completer(), Echange_externe_impose_rayo_semi_transp::completer(), Neumann_paroi_rayo_semi_transp_VDF::completer(), Neumann_paroi_rayo_semi_transp_VEF::completer(), Temperature_imposee_paroi_rayo_semi_transp::completer(), Echange_global_impose::completer(), Echange_contact_PolyMAC::completer(), Echange_externe_impose_H::completer(), Echange_contact_Correlation_VDF::completer(), Echange_interne_impose::completer(), and Terme_Source_Th_TdivU_VEF_Face::modifier_domaine_cl().
initialiser()
int Cond_lim_base::initialiser (double temps) virtual
Initialisation en debut de calcul.
A appeler avant tout calculer_coeffs_echange ou mettre_a_jour Contrairementaux methodes mettre_a_jour, les methodes initialiser des CLs ne peuvent pas dependre de l'exterieur (lui-meme peut ne pas etre initialise)
Returns
(0 en cas d'erreur, 1 sinon.)
Reimplemented in Cond_lim_k_simple_flux_nul, Paroi_frottante_simple, Echange_contact_VDF_FT_Disc, Echange_contact_VDF_FT_Disc_solid, Dirichlet_loi_paroi, Echange_global_impose, Echange_impose_base, Echange_contact_PolyMAC, Neumann_sortie_libre, Echange_global_impose_turbulent, Echange_couplage_thermique, Echange_contact_VDF, Echange_interne_impose, Sortie_libre_Gradient_Pression_impose_VEFPreP1B, Sortie_libre_Gradient_Pression_libre_VEF, Sortie_libre_Gradient_Pression_libre_VEFPreP1B, and Frottement_impose_base.
References domaine_Cl_dis(), Champ_front_base::initialiser(), and le_champ_front.
Referenced by Echange_impose_base::initialiser(), Neumann_sortie_libre::initialiser(), Sortie_libre_Gradient_Pression_impose_VEFPreP1B::initialiser(), Sortie_libre_Gradient_Pression_libre_VEF::initialiser(), and Sortie_libre_Gradient_Pression_libre_VEFPreP1B::initialiser().
mettre_a_jour()
void Cond_lim_base::mettre_a_jour (double temps) virtual
Effectue une mise a jour en temps de la condition aux limites.
Parameters
(double temps) le pas de temps de mise a jour
Reimplemented in Frontiere_ouverte_vitesse_vortex, Paroi_flux_impose_Rayo_transp, Temperature_imposee_paroi_rayo_transp, Echange_contact_rayo_semi_transp_VDF, Neumann_paroi_rayo_semi_transp_VEF, Echange_global_impose, Periodique, Echange_contact_PolyMAC_P0P1NC, Neumann_sortie_libre, Echange_couplage_thermique, Sortie_libre_Gradient_Pression_libre_VEF, Sortie_libre_Gradient_Pression_libre_VEFPreP1B, Paroi_frottante_simple, Dirichlet_loi_paroi, Echange_global_impose_turbulent, Echange_interne_impose, Echange_contact_VDF_FT_Disc, Echange_contact_VDF_FT_Disc_solid, Frontiere_Ouverte_Rayo_transp, Frontiere_Ouverte_temperature_imposee_Rayo_transp, Echange_contact_Rayo_transp_VDF, Echange_externe_impose_rayo_transp, Echange_impose_base, Echange_contact_PolyMAC, Sortie_libre_pression_moyenne_imposee, Echange_contact_Correlation_VDF, Echange_contact_VDF, PlaqThVDF, Sortie_libre_Gradient_Pression_impose, Sortie_libre_Pression_imposee_Orlansky, Echange_contact_Correlation_VEF, and Sortie_libre_Gradient_Pression_impose_VEFPreP1B.
References le_champ_front, and Champ_front_base::mettre_a_jour().
Referenced by Paroi_flux_impose_Rayo_transp::mettre_a_jour(), Neumann_sortie_libre::mettre_a_jour(), Sortie_libre_Gradient_Pression_libre_VEF::mettre_a_jour(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::mettre_a_jour(), Frontiere_Ouverte_temperature_imposee_Rayo_transp::mettre_a_jour(), Echange_impose_base::mettre_a_jour(), Sortie_libre_pression_moyenne_imposee::mettre_a_jour(), Sortie_libre_Gradient_Pression_impose::mettre_a_jour(), Sortie_libre_Pression_imposee_Orlansky::mettre_a_jour(), Echange_contact_Correlation_VEF::mettre_a_jour(), Sortie_libre_Gradient_Pression_impose_VEFPreP1B::mettre_a_jour(), Domaine_Cl_dis_base::mettre_a_jour_ss_pas_dt(), and resetTime().
resetTime()
void Cond_lim_base::resetTime (double time) virtual
References mettre_a_jour().
calculer_coeffs_echange()
void Cond_lim_base::calculer_coeffs_echange (double temps) virtual
Calcul des coefficient d'echange pour un couplage par Champ_front_contact_VEF.
Ces calculs sont locaux au probleme et dependant uniquement de l'inconnue. Ils doivent donc etre faits chaque fois que l'inconnue est modifiee. Ils sont disponibles pour l'exterieur et stockes dans les CLs. WEC : Les Champ_front_contact_VEF devraient disparaitre et cette methode avec !!!
Parameters
(double temps) le pas de temps de mise a jour
Reimplemented in Dirichlet_loi_paroi, Frottement_impose_base, and Echange_global_impose_turbulent.
References Champ_front_base::calculer_coeffs_echange(), and le_champ_front.
verifie_ch_init_nb_comp()
void Cond_lim_base::verifie_ch_init_nb_comp () const virtual
Appel la verification du champ lu par l intermediaire de l equation pour laquelle on considere la condition limite.
La methode est surchargee dans les cas ou l utilisateur doit specifier le champ frontiere
Reimplemented in Echange_global_impose_rayo_semi_transp, Dirichlet, Dirichlet_loi_paroi, Echange_externe_impose, Neumann_paroi, Echange_contact_PolyMAC_P0P1NC, Frottement_impose_base, Neumann_sortie_libre, Echange_global_impose_turbulent, Echange_interne_global_impose, and Echange_interne_impose.
frontiere_dis() [1/2]
Frontiere_dis_base & Cond_lim_base::frontiere_dis () inline virtual
Renvoie la frontiere discretisee a laquelle les conditions aux limites s'appliquent.
Returns
(Frontiere_dis_base&) la frontiere discretisee a laquelle les conditions aux limites sont associees
Reimplemented in Dirichlet_loi_paroi, Frottement_impose_base, and Echange_global_impose_turbulent.
References Champ_front_base::frontiere_dis(), and le_champ_front.
Referenced by Op_Conv_VEF_Face::ajouter(), Operateur_Conv_sensibility_VEF::ajouter_conv_term(), Operateur_Conv_sensibility_VEF::ajouter_Lsensibility_state_Amont(), Operateur_Conv_sensibility_VEF::ajouter_Lstate_sensibility_Amont(), Op_Diff_PolyMAC_Elem::ajouter_termes_croises(), Op_Conv_ALE_VEF::ajouterALE(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_avec_inertie_impl(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_blocs_avec_inertie(), Champ_front_contact_VEF::associer_front_vf_et_ch_front_autre_pb(), Ensemble_Faces_base::associer_les_cl(), Maillage_FT_Disc::calcul_courbure_sommets(), Traitement_particulier_NS_THI_VDF::calcul_skewness_ordre_2(), Maillage_FT_Disc::calculer_costheta_minmax(), Flux_radiatif_VDF::calculer_flux_radiatif(), Flux_radiatif_VEF::calculer_flux_radiatif(), Echange_contact_VDF::calculer_h_autre_pb(), Echange_contact_Correlation_VDF::calculer_h_mon_pb(), Echange_contact_VDF::calculer_h_mon_pb(), Echange_contact_Correlation_VEF::calculer_h_solide(), Echange_contact_Correlation_VDF::calculer_Q(), Echange_contact_Correlation_VEF::calculer_Q(), Face_Rayonnante::calculer_temperature(), Echange_contact_rayo_semi_transp_VDF::calculer_temperature_bord(), Neumann_paroi_rayo_semi_transp_VDF::calculer_temperature_bord(), Neumann_paroi_rayo_semi_transp_VEF::calculer_temperature_bord(), Echange_contact_ODVM_VDF::calculer_Teta_equiv(), Echange_contact_rayo_semi_transp_VDF::calculer_Teta_equiv(), Echange_contact_VDF::calculer_Teta_equiv(), Frontiere_Ouverte_Rayo_transp::calculer_Teta_i(), Frontiere_Ouverte_temperature_imposee_Rayo_transp::calculer_Teta_i(), Echange_externe_impose_rayo_transp::calculer_Teta_i(), Temperature_imposee_paroi_rayo_transp::calculer_Teta_i(), Paroi_flux_impose_Rayo_transp::calculer_Teta_i_VDF(), Paroi_flux_impose_Rayo_transp::calculer_Teta_i_VEF(), Echange_contact_VDF::calculer_Teta_paroi(), Echange_contact_Rayo_transp_VDF::calculer_Teta_paroi(), Echange_contact_rayo_semi_transp_VDF::calculer_Teta_paroi(), Sortie_libre_Gradient_Pression_impose_VEFPreP1B::calculer_trace_pression(), Equation_base::completer(), Echange_contact_VDF_FT_Disc::completer(), Echange_contact_VDF_FT_Disc_solid::completer(), Frontiere_Ouverte_Rayo_transp::completer(), Frontiere_Ouverte_temperature_imposee_Rayo_transp::completer(), Echange_contact_Rayo_transp_VDF::completer(), Echange_externe_impose_rayo_transp::completer(), Paroi_flux_impose_Rayo_transp::completer(), Temperature_imposee_paroi_rayo_transp::completer(), Neumann_paroi_rayo_semi_transp_VDF::completer(), Neumann_paroi_rayo_semi_transp_VEF::completer(), Echange_global_impose::completer(), Periodique::completer(), Echange_contact_PolyMAC::completer(), Sortie_libre_pression_moyenne_imposee::completer(), Echange_couplage_thermique::completer(), Echange_interne_global_impose::completer(), Echange_contact_Correlation_VDF::completer(), Echange_contact_VDF::completer(), Echange_interne_impose::completer(), Echange_contact_Correlation_VEF::completer(), Domaine_Cl_VDF::completer(), Domaine_VEF::construire_renum_arete_perio(), Op_Diff_PolyMAC_Elem::contribuer_termes_croises(), Op_Diff_VDF_Elem_base::contribuer_termes_croises(), Op_EF_base::dimensionner(), Op_Diff_PolyMAC_Elem::dimensionner_termes_croises(), Op_Diff_VDF_Elem_base::dimensionner_termes_croises(), Flux_radiatif_VDF::evaluer_cl_rayonnement(), Flux_radiatif_VEF::evaluer_cl_rayonnement(), Neumann::flux_impose(), Paroi_Rayo_transp::flux_impose(), Neumann_paroi_rayo_semi_transp_VDF::flux_impose(), Neumann_paroi_rayo_semi_transp_VEF::flux_impose(), Modele_Rayonnement_Milieu_Transparent::flux_radiatif(), Domaine_Cl_EF::imposer_cond_lim(), Domaine_Cl_PolyMAC::imposer_cond_lim(), Domaine_Cl_VDF::imposer_cond_lim(), Domaine_Cl_VEF::imposer_cond_lim(), Domaine_Cl_EF::imposer_symetrie_partiellement(), Echange_contact_Correlation_VDF::imprimer(), Echange_contact_Correlation_VEF::imprimer(), Echange_contact_Correlation_VEF::init(), Echange_contact_PolyMAC_P0::init_op(), Echange_contact_PolyMAC_P0P1NC::init_op(), Echange_contact_PolyMAC::initialiser(), Echange_couplage_thermique::initialiser(), Echange_contact_VDF::initialiser(), Sortie_libre_Gradient_Pression_libre_VEF::initialiser(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::initialiser(), Domaine_Cl_dis_base::la_cl_de_la_face(), Echange_contact_rayo_semi_transp_VDF::la_Cl_opposee(), AssembleurPVDF_PF::liste_faces_periodiques(), Assembleur_P_VDF::liste_faces_periodiques(), Domaine_VF::marquer_faces_double_contrib(), Echange_contact_rayo_semi_transp_VDF::mettre_a_jour(), Sortie_libre_Gradient_Pression_libre_VEF::mettre_a_jour(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::mettre_a_jour(), Echange_interne_impose::mettre_a_jour(), Echange_contact_VDF_FT_Disc::mettre_a_jour(), Echange_contact_VDF_FT_Disc_solid::mettre_a_jour(), Echange_contact_Rayo_transp_VDF::mettre_a_jour(), Echange_contact_Correlation_VDF::mettre_a_jour(), PlaqThVDF::mettre_a_jour(), Sortie_libre_Gradient_Pression_impose::mettre_a_jour(), Sortie_libre_Pression_imposee_Orlansky::mettre_a_jour(), Echange_contact_Correlation_VEF::mettre_a_jour(), Domaine_EF::modifier_pour_Cl(), Domaine_Poly_base::modifier_pour_Cl(), Domaine_VF::modifier_pour_Cl(), Domaine_PolyMAC::modifier_pour_Cl(), Domaine_VEF::modifier_pour_Cl(), Domaine_VDF::modifier_pour_Cl(), AssembleurPVDF_PF::modifier_secmem(), Assembleur_P_EF::modifier_secmem(), Assembleur_P_PolyMAC::modifier_secmem(), Assembleur_P_VDF::modifier_secmem(), Assembleur_P_VEF::modifier_secmem(), Assembleur_P_VEFPreP1B::modifier_secmem(), Assembleur_P_VEFPreP1B::modifier_secmem_elem(), Assembleur_P_VEFPreP1B::modifier_secmem_som(), Cond_Lim_rayo_semi_transp::recherche_emissivite_et_A(), AssembleurPVDF_PF::remplir(), Assembleur_P_VDF::remplir(), EDO_Pression_th_VDF_Gaz_Parfait::resoudre(), Echange_contact_Correlation_VDF::trier_coord(), Echange_interne_impose::update_inv_lambda(), Neumann_sortie_libre::val_ext(), Dirichlet::val_imp(), Champ_Face_VDF::verifie_valeurs_cl(), Champ_P1NC::verifie_valeurs_cl(), Champ_Q1NC::verifie_valeurs_cl(), Echange_contact_VDF::verifier_correspondance(), and Ecrire_fichier_xyz_valeur::write_fields().
frontiere_dis() [2/2]
const Frontiere_dis_base & Cond_lim_base::frontiere_dis () const inline virtual
Renvoie la frontiere discretisee a laquelle les conditions aux limites s'appliquent.
(version const)
Returns
(Frontiere_dis_base&) la frontiere discretisee a laquelle les conditions aux limites sont associees
Reimplemented in Dirichlet_loi_paroi, Frottement_impose_base, and Echange_global_impose_turbulent.
References Champ_front_base::frontiere_dis(), and le_champ_front.
associer_fr_dis_base()
void Cond_lim_base::associer_fr_dis_base (const Frontiere_dis_base & fr) virtual
Associe la frontiere a l'objet.
L'objet Frontiere_dis_base est en fait associe au membre OWN_PTR(Champ_front_base) de l'objet Cond_lim_base qui represente le champ des conditions aux limites imposees a la frontiere.
Parameters
(Frontiere_dis_base& fr) la frontiere sur laquelle on impose les conditions aux limites
Reimplemented in Echange_impose_base, Neumann_sortie_libre, Dirichlet_loi_paroi, Frottement_impose_base, Echange_global_impose_turbulent, and Echange_interne_impose.
References Champ_front_base::associer_fr_dis_base(), le_champ_front, modifier_val_imp, and Objet_U_ptr::non_nul().
Referenced by Echange_impose_base::associer_fr_dis_base(), Neumann_sortie_libre::associer_fr_dis_base(), and Terme_Source_Th_TdivU_VEF_Face::modifier_domaine_cl().
domaine_Cl_dis() [1/2]
Domaine_Cl_dis_base & Cond_lim_base::domaine_Cl_dis () inline
Renvoie le domaine des conditions aux limites discretisee dont l'objet fait partie.
Returns
(Domaine_Cl_dis_base&) le domaine des conditions aux limites discretisee dont l'objet fait partie
References mon_dom_cl_dis, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Echange_contact_Correlation_VDF::calculer_CL(), Echange_contact_Correlation_VEF::calculer_CL(), Flux_radiatif_VDF::calculer_flux_radiatif(), Flux_radiatif_VEF::calculer_flux_radiatif(), Echange_contact_VDF::calculer_h_autre_pb(), Echange_contact_Correlation_VDF::calculer_h_mon_pb(), Echange_contact_VDF::calculer_h_mon_pb(), Echange_contact_Correlation_VEF::calculer_h_solide(), Echange_contact_Correlation_VDF::calculer_Q(), Echange_contact_Correlation_VEF::calculer_Q(), Echange_contact_rayo_semi_transp_VDF::calculer_temperature_bord(), Neumann_paroi_rayo_semi_transp_VDF::calculer_temperature_bord(), Neumann_paroi_rayo_semi_transp_VEF::calculer_temperature_bord(), Echange_contact_ODVM_VDF::calculer_Teta_equiv(), Paroi_flux_impose_Rayo_transp::calculer_Teta_i_VDF(), Echange_contact_VDF::calculer_Teta_paroi(), Echange_contact_Rayo_transp_VDF::calculer_Teta_paroi(), Echange_contact_rayo_semi_transp_VDF::calculer_Teta_paroi(), Echange_contact_Correlation_VDF::calculer_Tfluide(), Echange_contact_Correlation_VEF::calculer_Tfluide(), Cond_lim_k_complique_transition_flux_nul_demi::completer(), Cond_lim_k_simple_flux_nul::completer(), Cond_lim_omega_demi::completer(), Cond_lim_omega_dix::completer(), Paroi_frottante_loi::completer(), Paroi_frottante_simple::completer(), Echange_contact_VDF_FT_Disc::completer(), Echange_contact_VDF_FT_Disc_solid::completer(), Frontiere_Ouverte_Rayo_transp::completer(), Frontiere_Ouverte_temperature_imposee_Rayo_transp::completer(), Echange_contact_Rayo_transp_VDF::completer(), Echange_externe_impose_rayo_transp::completer(), Paroi_flux_impose_Rayo_transp::completer(), Temperature_imposee_paroi_rayo_transp::completer(), Neumann_paroi_rayo_semi_transp_VDF::completer(), Periodique::completer(), Paroi_Knudsen_non_negligeable::completer(), Echange_interne_global_impose::completer(), Echange_contact_Correlation_VDF::completer(), Echange_contact_VDF::completer(), Echange_interne_impose::completer(), Sortie_libre_Gradient_Pression_impose::completer(), Sortie_libre_Pression_imposee_Orlansky::completer(), Echange_contact_Correlation_VEF::completer(), Sortie_libre_Gradient_Pression_libre_VEF::completer(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::completer(), Neumann_paroi_rayo_semi_transp_VDF::flux_impose(), Sortie_libre_Gradient_Pression_libre_VEF::flux_impose(), Echange_contact_Correlation_VDF::imprimer(), Echange_contact_Correlation_VEF::imprimer(), Echange_contact_Correlation_VEF::init(), Echange_contact_PolyMAC_P0::init_op(), Echange_contact_PolyMAC_P0P1NC::init_op(), Echange_contact_Correlation_VDF::init_tab_echange(), initialiser(), Paroi_frottante_simple::initialiser(), Echange_contact_VDF_FT_Disc::initialiser(), Echange_contact_VDF_FT_Disc_solid::initialiser(), Dirichlet_loi_paroi::initialiser(), Echange_global_impose::initialiser(), Echange_impose_base::initialiser(), Echange_contact_PolyMAC::initialiser(), Neumann_sortie_libre::initialiser(), Echange_global_impose_turbulent::initialiser(), Echange_couplage_thermique::initialiser(), Echange_contact_VDF::initialiser(), Sortie_libre_Gradient_Pression_impose_VEFPreP1B::initialiser(), Sortie_libre_Gradient_Pression_libre_VEF::initialiser(), Echange_contact_Correlation_VDF::limpr(), Echange_contact_Correlation_VEF::limpr(), Paroi_frottante_simple::me_calculer(), Cond_lim_k_complique_transition_flux_nul_demi::me_calculer(), Cond_lim_k_simple_flux_nul::me_calculer(), Cond_lim_omega_demi::me_calculer(), Cond_lim_omega_dix::me_calculer(), Frontiere_ouverte_vitesse_vortex::mettre_a_jour(), Echange_contact_rayo_semi_transp_VDF::mettre_a_jour(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::mettre_a_jour(), Echange_contact_VDF_FT_Disc_solid::mettre_a_jour(), Echange_contact_Rayo_transp_VDF::mettre_a_jour(), Echange_contact_Correlation_VDF::mettre_a_jour(), Echange_contact_Correlation_VEF::mettre_a_jour(), Domaine_VDF::modifier_pour_Cl(), Echange_contact_Correlation_VDF::trier_coord(), Echange_global_impose_rayo_semi_transp::verifie_ch_init_nb_comp(), Dirichlet::verifie_ch_init_nb_comp(), Echange_externe_impose::verifie_ch_init_nb_comp(), Neumann_paroi::verifie_ch_init_nb_comp(), Neumann_sortie_libre::verifie_ch_init_nb_comp(), and Echange_contact_VDF::verifier_correspondance().
domaine_Cl_dis() [2/2]
const Domaine_Cl_dis_base & Cond_lim_base::domaine_Cl_dis () const inline
Renvoie le domaine des conditions aux limites discretisee dont l'objet fait partie.
(version const)
Returns
(Domaine_Cl_dis_base&) le domaine des conditions aux limites discretisee dont l'objet fait partie
References mon_dom_cl_dis, and TRUST_Ref< _CLASSE_ >::valeur().
associer_domaine_cl_dis_base()
void Cond_lim_base::associer_domaine_cl_dis_base (const Domaine_Cl_dis_base & zcl) virtual
Associe le Domaine_Cl_dis_base (Domaine des conditions aux limites discretisees) a l'objet.
Ce Domaine_Cl_dis_base stocke (reference) toutes les conditions aux limites relative a un Domaine geometrique.
Parameters
(Domaine_Cl_dis_base& zcl) un Domaine des conditions aux limites discretisees a laquelle l'objet Cond_lim_base se rapporte
Reimplemented in Dirichlet_loi_paroi, Frottement_impose_base, and Echange_global_impose_turbulent.
References le_champ_front, mon_dom_cl_dis, and Champ_front_base::verifier().
champ_front() [1/3]
Champ_front_base & Cond_lim_base::champ_front () inline
References le_champ_front.
Referenced by Op_Grad_P0_to_Face::ajouter_blocs(), Champ_front_contact_VEF::associer_front_vf_et_ch_front_autre_pb(), avancer(), Maillage_FT_Disc::calculer_costheta_minmax(), Op_Diff_VEFP1NCP1B_Face::calculer_gradient_som(), Echange_contact_Correlation_VEF::calculer_Q(), changer_temps_futur(), completer(), Flux_radiatif_base::completer(), Echange_contact_Correlation_VEF::completer(), Op_Diff_DG_Elem::contribuer_au_second_membre(), fixer_nb_valeurs_temporelles(), Convection_Diffusion_Temperature_FT_Disc::get_flux_and_Twall(), Convection_Diffusion_Temperature_FT_Disc::get_flux_to_face(), Domaine_Cl_EF::imposer_cond_lim(), Echange_contact_Correlation_VEF::mettre_a_jour(), Assembleur_P_EF::modifier_secmem(), Assembleur_P_PolyMAC::modifier_secmem(), Assembleur_P_VEF::modifier_secmem(), Assembleur_P_VEFPreP1B::modifier_secmem(), Assembleur_P_VEFPreP1B::modifier_secmem_elem(), AssembleurPVDF_PF::modifier_secmem_pression_imposee(), Assembleur_P_VEFPreP1B::modifier_secmem_som(), AssembleurPVDF_PF::modifier_secmem_vitesse_imposee(), Assembleur_P_VDF::modifier_secmem_vitesse_imposee(), Probleme_base::newCompute(), Flux_radiatif_base::readOn(), Echange_contact_Correlation_VEF::readOn(), reculer(), and set_temps_defaut().
champ_front() [2/3]
const Champ_front_base & Cond_lim_base::champ_front () const inline
References le_champ_front.
set_temps_defaut()
void Cond_lim_base::set_temps_defaut (double temps) virtual
Change le i-eme temps futur de la cl.
Reimplemented in Echange_contact_VDF_FT_Disc, Dirichlet_loi_paroi, Echange_global_impose, Echange_impose_base, Frottement_impose_base, Neumann_sortie_libre, Echange_global_impose_turbulent, Echange_couplage_thermique, and Echange_interne_impose.
References champ_front(), and Champ_front_base::set_temps_defaut().
Referenced by Echange_impose_base::set_temps_defaut(), and Neumann_sortie_libre::set_temps_defaut().
fixer_nb_valeurs_temporelles()
void Cond_lim_base::fixer_nb_valeurs_temporelles (int nb_cases) virtual
Appele par Conds_lim::completer Appel cha_front_base::fixer_nb_valeurs_temporelles.
Reimplemented in Dirichlet_loi_paroi, Echange_impose_base, Frottement_impose_base, Neumann_sortie_libre, Echange_global_impose_turbulent, and Echange_interne_impose.
References champ_front(), and Champ_front_base::fixer_nb_valeurs_temporelles().
Referenced by Echange_impose_base::fixer_nb_valeurs_temporelles(), and Neumann_sortie_libre::fixer_nb_valeurs_temporelles().
champ_front() [3/3]
void Cond_lim_base::champ_front (int face, DoubleVect & var) const virtual
References le_champ_front, and Champ_front_base::valeurs_face().
compatible_avec_eqn()
int Cond_lim_base::compatible_avec_eqn (const Equation_base & eqn) const virtual
Reimplemented in Paroi_FT_disc, Frontiere_Ouverte_temperature_imposee_Rayo_transp, Paroi_Rayo_transp, Echange_contact_Rayo_transp_VDF, Echange_externe_impose_rayo_transp, Temperature_imposee_paroi_rayo_transp, Flux_radiatif_base, Frontiere_ouverte_rayo_semi_transp, Frontiere_ouverte_temperature_imposee_rayo_semi_transp, Echange_contact_rayo_semi_transp_VDF, Echange_externe_impose_rayo_semi_transp, Echange_global_impose_rayo_semi_transp, Neumann_paroi_rayo_semi_transp_VDF, Neumann_paroi_rayo_semi_transp_VEF, Temperature_imposee_paroi_rayo_semi_transp, Dirichlet_loi_paroi, Navier, Cond_lim_utilisateur_base, Periodique, Frontiere_ouverte_rho_u_impose, Echange_global_impose_turbulent, and Paroi_decalee_Robin.
References app_domains, Equation_base::domaine_application(), err_pas_compatible(), and Process::exit().
Referenced by Frontiere_ouverte_rho_u_impose::compatible_avec_eqn().
compatible_avec_discr()
int Cond_lim_base::compatible_avec_discr (const Discretisation_base & discr) const virtual
Renvoie 1 si la condition aux limites est compatible avec la discretisation passee en parametre.
Parameters
(Discretisation_base&) la discretisation avec laquelle on veut verifier la compatibilite
Reimplemented in Echange_global_impose, and Echange_interne_global_parfait.
References err_pas_compatible(), Objet_U::que_suis_je(), and supp_discs.
injecter_dans_champ_inc()
void Cond_lim_base::injecter_dans_champ_inc (const Champ_Inc_base &) const virtual
References Process::exit().
a_mettre_a_jour_ss_pas_dt()
int Cond_lim_base::a_mettre_a_jour_ss_pas_dt () virtual
Cette methode indique si cette condition aux limites doit etre mise a jour dans des sous pas de temps d'un schema en temps tel que RK.
Par defaut elle renvoie 0 pour indiquer qu'aucune mise a jour n'est necessaire ; il faut la surcharger pour renvoyer 1 au besoin (exemple Echange_impose_base)
Parameters
(double temps) le pas de temps de mise a jour
Reimplemented in Echange_impose_base.
Referenced by Domaine_Cl_dis_base::mettre_a_jour_ss_pas_dt().
set_modifier_val_imp()
void Cond_lim_base::set_modifier_val_imp (int drap) inline
Positionne le drapeau modifier_val_imp a la valeur donnee : - si drap == 1 : modifier_val_imp=1.
sinon : modifier_val_imp=0 Ce drapeau permet a la CL de savoir si elle doit renvoyer la valeur stockee telle quelle, ou si elle doit la traduire pour l'objet appelant A la CL de savoir ensuite quelle traduction faire. Voir application dans Temperature_imposee_paroi_H, ou la CL renvoie l'enthalpie par defaut (modifier_val_imp=1), ou la temperature sinon (cas de l'operateur de diffusion) Le drapeau est positionne dans le equation.derivee_en_temps_inco selon l'operateur qui va etre appele
Parameters
(drap) valeur a donner au drapeau
References modifier_val_imp.
changer_temps_futur()
void Cond_lim_base::changer_temps_futur (double temps, int i) virtual
Change le i-eme temps futur de la CL.
Reimplemented in Echange_contact_VDF_FT_Disc, Echange_contact_VDF_FT_Disc_solid, Dirichlet_loi_paroi, Echange_global_impose, Echange_impose_base, Frottement_impose_base, Neumann_sortie_libre, Echange_global_impose_turbulent, Echange_couplage_thermique, Echange_contact_VDF, and Echange_interne_impose.
References champ_front(), and Champ_front_base::changer_temps_futur().
Referenced by Echange_impose_base::changer_temps_futur(), Neumann_sortie_libre::changer_temps_futur(), and Echange_contact_VDF::changer_temps_futur().
avancer()
int Cond_lim_base::avancer (double temps) virtual
Tourne la roue de la CL.
Reimplemented in Paroi_frottante_simple, Echange_contact_VDF_FT_Disc, Echange_contact_VDF_FT_Disc_solid, Dirichlet_loi_paroi, Echange_global_impose, Echange_impose_base, Neumann_sortie_libre, Echange_global_impose_turbulent, Echange_couplage_thermique, Echange_contact_VDF, and Echange_interne_impose.
References Champ_front_base::avancer(), and champ_front().
Referenced by Echange_impose_base::avancer(), Neumann_sortie_libre::avancer(), and Echange_contact_VDF::avancer().
reculer()
int Cond_lim_base::reculer (double temps) virtual
Tourne la roue de la CL.
Reimplemented in Echange_contact_VDF_FT_Disc, Echange_contact_VDF_FT_Disc_solid, Echange_global_impose, Echange_impose_base, Neumann_sortie_libre, Echange_couplage_thermique, Echange_contact_VDF, and Echange_interne_impose.
References champ_front(), and Champ_front_base::reculer().
Referenced by Echange_impose_base::reculer(), Neumann_sortie_libre::reculer(), and Echange_contact_VDF::reculer().
err_pas_compatible() [1/2]
void Cond_lim_base::err_pas_compatible (const Equation_base & eqn) const protected
Cette methode est appelee quand la condition aux limites n'est pas compatible avec l'equation sur laquelle on essaye.
de l'appliquer.
Parameters
(Equation_base& eqn) l'equation avec laquelle la condition aux limites est incompatible
References Process::exit(), and Objet_U::que_suis_je().
Referenced by compatible_avec_discr(), Echange_interne_global_parfait::compatible_avec_discr(), compatible_avec_eqn(), Paroi_FT_disc::compatible_avec_eqn(), Echange_contact_rayo_semi_transp_VDF::compatible_avec_eqn(), Neumann_paroi_rayo_semi_transp_VDF::compatible_avec_eqn(), Neumann_paroi_rayo_semi_transp_VEF::compatible_avec_eqn(), Temperature_imposee_paroi_rayo_semi_transp::compatible_avec_eqn(), Dirichlet_loi_paroi::compatible_avec_eqn(), Echange_global_impose_turbulent::compatible_avec_eqn(), and Paroi_decalee_Robin::compatible_avec_eqn().
err_pas_compatible() [2/2]
void Cond_lim_base::err_pas_compatible (const Discretisation_base & discr) const protected
Cette methode est appelee quand la condition aux limites n'est pas compatible avec la discretisation sur laquelle on essaye.
de l'appliquer.
Parameters
(Discretisation_base& discr) la discretisation avec laquelle la condition aux limites est incompatible
References Process::exit(), and Objet_U::que_suis_je().
Member Data Documentation
info_obj
const Type_info Cond_lim_base::info_obj static
app_domains
std::vector<Motcle> Cond_lim_base::app_domains protected
Referenced by compatible_avec_eqn(), Paroi_frottante_loi::readOn(), Paroi_frottante_simple::readOn(), Echange_contact_VDF_FT_Disc::readOn(), Echange_contact_VDF_FT_Disc_solid::readOn(), Entree_fluide_K_Eps_impose::readOn(), Entree_fluide_K_Omega_impose::readOn(), Entree_fluide_vitesse_imposee::readOn(), Entree_fluide_Fluctu_Temperature_imposee::readOn(), Entree_fluide_temperature_imposee::readOn(), Entree_fluide_V2_impose::readOn(), Entree_fluide_fraction_massique_imposee::readOn(), Entree_fluide_alpha_impose::readOn(), Entree_fluide_Flux_Chaleur_Turbulente_imposee::readOn(), Dirichlet_paroi_defilante::readOn(), Echange_externe_radiatif::readOn(), Echange_impose_base::readOn(), Neumann_paroi::readOn(), Scalaire_impose_paroi::readOn(), Echange_contact_PolyMAC_P0P1NC::readOn(), Echange_externe_impose_H::readOn(), Entree_fluide_temperature_imposee_H::readOn(), Neumann_sortie_libre_Temp_H::readOn(), Temperature_imposee_paroi_H::readOn(), Sortie_libre_pression_imposee_QC::readOn(), Dirichlet_paroi_fixe::readOn(), Entree_fluide_concentration_imposee::readOn(), Entree_fluide_T_h_imposee::readOn(), Neumann_paroi_adiabatique::readOn(), Neumann_paroi_flux_nul::readOn(), Neumann_sortie_libre::readOn(), Paroi_Knudsen_non_negligeable::readOn(), Sortie_libre_pression_imposee::readOn(), Sortie_libre_pression_moyenne_imposee::readOn(), Sortie_libre_Text_H_ext::readOn(), Temperature_imposee_paroi::readOn(), Echange_couplage_thermique::readOn(), Echange_interne_global_impose::readOn(), Echange_interne_global_parfait::readOn(), Echange_contact_Correlation_VDF::readOn(), Echange_contact_VDF::readOn(), Echange_interne_impose::readOn(), Echange_interne_parfait::readOn(), PlaqThVDF::readOn(), Sortie_libre_Gradient_Pression_impose::readOn(), Sortie_libre_Pression_imposee_Orlansky::readOn(), Echange_contact_Correlation_VEF::readOn(), Sortie_libre_Gradient_Pression_impose_VEF::readOn(), Sortie_libre_Gradient_Pression_libre_VEF::readOn(), and Sortie_libre_Gradient_Pression_libre_VEFPreP1B::readOn().
supp_discs
std::vector<Nom> Cond_lim_base::supp_discs protected
Referenced by compatible_avec_discr(), Echange_externe_radiatif::readOn(), Echange_impose_base::readOn(), Scalaire_impose_paroi::readOn(), Temperature_imposee_paroi_H::readOn(), Temperature_imposee_paroi::readOn(), Echange_couplage_thermique::readOn(), Sortie_libre_Gradient_Pression_impose::readOn(), Sortie_libre_Pression_imposee_Orlansky::readOn(), Echange_contact_Correlation_VEF::readOn(), Sortie_libre_Gradient_Pression_impose_VEFPreP1B::readOn(), Sortie_libre_Gradient_Pression_libre_VEF::readOn(), and Sortie_libre_Gradient_Pression_libre_VEFPreP1B::readOn().
le_champ_front
TRUST_Deriv< Champ_front_base > Cond_lim_base::le_champ_front protected
Referenced by associer_domaine_cl_dis_base(), associer_fr_dis_base(), Temperature_imposee_paroi_rayo_semi_transp::associer_modele(), Temperature_imposee_paroi_rayo_transp::associer_modele_rayo(), calculer_coeffs_echange(), Neumann_paroi_rayo_semi_transp_VDF::calculer_temperature_bord(), Temperature_imposee_paroi_rayo_semi_transp::calculer_temperature_bord(), Temperature_imposee_paroi_rayo_transp::calculer_Teta_i(), Paroi_flux_impose_Rayo_transp::calculer_Teta_i_VDF(), champ_front(), Flux_radiatif_base::completer(), Paroi_Knudsen_non_negligeable::completer(), Sortie_libre_pression_moyenne_imposee::completer(), Flux_radiatif_VDF::evaluer_cl_rayonnement(), Flux_radiatif_VEF::evaluer_cl_rayonnement(), Neumann::flux_impose(), Sortie_libre_rho_variable::flux_impose(), Paroi_Rayo_transp::flux_impose(), Flux_radiatif_base::flux_impose(), Neumann_paroi_rayo_semi_transp_VDF::flux_impose(), Neumann_paroi_rayo_semi_transp_VEF::flux_impose(), Sortie_libre_pression_imposee_QC::flux_impose(), Sortie_libre_pression_moyenne_imposee::flux_impose(), Sortie_libre_pression_imposee::flux_impose(), Sortie_libre_Gradient_Pression_impose::flux_impose(), Sortie_libre_Pression_imposee_Orlansky::flux_impose(), Sortie_libre_Gradient_Pression_impose_VEF::flux_impose(), frontiere_dis(), Sortie_libre_Gradient_Pression_impose::grad_P_imp(), Sortie_libre_Gradient_Pression_libre_VEF::Grad_P_lib_VEF(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::Grad_P_lib_VEFPreP1B(), Echange_interne_global_impose::init(), Echange_interne_impose::init(), initialiser(), Echange_couplage_thermique::initialiser(), mettre_a_jour(), Frontiere_ouverte_vitesse_vortex::mettre_a_jour(), Sortie_libre_pression_moyenne_imposee::mettre_a_jour(), Sortie_libre_Pression_imposee_Orlansky::mettre_a_jour(), printOn(), Cond_lim_omega_demi::readOn(), Cond_lim_omega_dix::readOn(), Paroi_frottante_loi::readOn(), Paroi_frottante_simple::readOn(), Frontiere_ouverte_vitesse_vortex::readOn(), Paroi_FT_disc::readOn(), Echange_contact_VDF_FT_Disc::readOn(), Echange_contact_VDF_FT_Disc_solid::readOn(), Echange_externe_impose_rayo_transp::readOn(), Flux_radiatif_base::readOn(), Echange_externe_impose_rayo_semi_transp::readOn(), Echange_global_impose_rayo_semi_transp::readOn(), Neumann_paroi_rayo_semi_transp_VDF::readOn(), Neumann_paroi_rayo_semi_transp_VEF::readOn(), Dirichlet_homogene::readOn(), Dirichlet_loi_paroi::readOn(), Echange_externe_radiatif::readOn(), Echange_impose_base::readOn(), Neumann_homogene::readOn(), Symetrie::readOn(), readOn(), Periodique::readOn(), Echange_contact_PolyMAC::readOn(), Echange_contact_PolyMAC_P0P1NC::readOn(), Neumann_sortie_libre_Temp_H::readOn(), Sortie_libre_pression_imposee_QC::readOn(), Dirichlet_paroi_fixe::readOn(), Entree_fluide_T_h_imposee::readOn(), Neumann_sortie_libre::readOn(), Paroi_Knudsen_non_negligeable::readOn(), Sortie_libre_pression_imposee::readOn(), Sortie_libre_pression_moyenne_imposee::readOn(), Sortie_libre_Text_H_ext::readOn(), Echange_global_impose_turbulent::readOn(), Paroi_decalee_Robin::readOn(), Echange_couplage_thermique::readOn(), Echange_contact_Correlation_VDF::readOn(), Echange_contact_VDF::readOn(), PlaqThVDF::readOn(), Sortie_libre_Gradient_Pression_impose::readOn(), Sortie_libre_Pression_imposee_Orlansky::readOn(), Echange_contact_Correlation_VEF::readOn(), Sortie_libre_Gradient_Pression_impose_VEF::readOn(), Sortie_libre_Gradient_Pression_libre_VEF::readOn(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::readOn(), Echange_impose_base::T_ext(), Echange_externe_impose_H::T_ext(), Frontiere_ouverte_rayo_semi_transp::temperature_bord(), Frontiere_ouverte_temperature_imposee_rayo_semi_transp::temperature_bord(), Temperature_imposee_paroi_rayo_semi_transp::temperature_bord(), Dirichlet::val_imp(), Entree_fluide_temperature_imposee_H::val_imp(), Temperature_imposee_paroi_H::val_imp(), Dirichlet::val_imp_au_temps(), Frontiere_ouverte_rho_u_impose::val_imp_au_temps(), Echange_global_impose_rayo_semi_transp::verifie_ch_init_nb_comp(), Dirichlet::verifie_ch_init_nb_comp(), Echange_externe_impose::verifie_ch_init_nb_comp(), Neumann_paroi::verifie_ch_init_nb_comp(), and Neumann_sortie_libre::verifie_ch_init_nb_comp().
mon_dom_cl_dis
TRUST_Ref< Domaine_Cl_dis_base *> Cond_lim_base::mon_dom_cl_dis protected
Referenced by associer_domaine_cl_dis_base(), Dirichlet_loi_paroi::associer_domaine_cl_dis_base(), Frottement_impose_base::associer_domaine_cl_dis_base(), Echange_global_impose_turbulent::associer_domaine_cl_dis_base(), Neumann_paroi_rayo_semi_transp_VDF::calculer_temperature_bord(), Paroi_flux_impose_Rayo_transp::calculer_Teta_i_VDF(), Paroi_flux_impose_Rayo_transp::calculer_Teta_i_VEF(), Echange_contact_rayo_semi_transp_VDF::calculer_Teta_paroi(), Echange_global_impose::champ_exterieur(), Echange_couplage_thermique::champ_exterieur(), Frontiere_ouverte_rho_u_impose::compatible_avec_eqn(), Echange_contact_VDF_FT_Disc::completer(), Paroi_flux_impose_Rayo_transp::completer(), Echange_externe_impose_H::completer(), Entree_fluide_temperature_imposee_H::completer(), Frontiere_ouverte_rho_u_impose::completer(), Neumann_sortie_libre_Temp_H::completer(), Temperature_imposee_paroi_H::completer(), Sortie_libre_pression_imposee_QC::completer(), Sortie_libre_pression_imposee::completer(), Sortie_libre_pression_moyenne_imposee::completer(), Echange_couplage_thermique::completer(), domaine_Cl_dis(), Sortie_libre_pression_imposee_QC::flux_impose(), Sortie_libre_pression_moyenne_imposee::flux_impose(), Sortie_libre_pression_imposee::flux_impose(), Sortie_libre_Gradient_Pression_impose::grad_P_imp(), Sortie_libre_Gradient_Pression_libre_VEF::Grad_P_lib_VEF(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::Grad_P_lib_VEFPreP1B(), Echange_contact_VDF_FT_Disc::mettre_a_jour(), Echange_contact_VDF_FT_Disc_solid::mettre_a_jour(), Sortie_libre_pression_moyenne_imposee::mettre_a_jour(), and PlaqThVDF::mettre_a_jour().
modifier_val_imp
int Cond_lim_base::modifier_val_imp = 0 protected
Referenced by associer_fr_dis_base(), Neumann_sortie_libre::associer_fr_dis_base(), Echange_externe_impose_H::completer(), Entree_fluide_temperature_imposee_H::completer(), Neumann_sortie_libre_Temp_H::completer(), Temperature_imposee_paroi_H::completer(), set_modifier_val_imp(), Echange_externe_impose_H::T_ext(), Neumann_sortie_libre_Temp_H::val_ext(), Entree_fluide_temperature_imposee_H::val_imp(), and Temperature_imposee_paroi_H::val_imp().