TrioCFD: Source_Transport_VDF_Elem_base Class Reference
Source_Transport_VDF_Elem_base Class Reference abstract
#include <Source_Transport_VDF_Elem_base.h>
Public Member Functions
const Type_info * get_info () const override
void mettre_a_jour (double t) override
Public Member Functions inherited from Source_base
virtual int a_pour_Champ_Fonc (const Motcle &mot, TRUST_Ref< Champ_base * > &ch_ref) const
virtual void associer_champ_rho (const Champ_base &champ_rho)
virtual void completer ()
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
virtual void resetTime (double t)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
~Source_Transport_VDF_Elem_base()
Source_Transport_VDF_Elem_base::~Source_Transport_VDF_Elem_base () override
Source_Transport_VDF_Elem_base() [1/2]
Source_Transport_VDF_Elem_base::Source_Transport_VDF_Elem_base () inline
Source_Transport_VDF_Elem_base() [2/2]
Source_Transport_VDF_Elem_base::Source_Transport_VDF_Elem_base (double cs1, double cs2) inline
Member Function Documentation
info()
const Type_info * Source_Transport_VDF_Elem_base::info () static
get_info()
const Type_info * Source_Transport_VDF_Elem_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Source_base.
Reimplemented in Source_Transport_Eps_aniso_therm_concen_VDF_Elem, Source_Transport_Eps_anisotherme_VDF_Elem, Source_Transport_Eps_concen_VDF_Elem, Source_Transport_Eps_Realisable_aniso_concen_VDF_Elem, Source_Transport_Eps_Realisable_aniso_therm_concen_VDF_Elem, Source_Transport_Eps_Realisable_anisotherme_VDF_Elem, Source_Transport_Eps_Realisable_VDF_Elem, Source_Transport_Eps_VDF_Elem, Source_Transport_K_aniso_therm_concen_VDF_Elem, Source_Transport_K_anisotherme_VDF_Elem, Source_Transport_K_concen_VDF_Elem, Source_Transport_K_Realisable_aniso_concen_VDF_Elem, Source_Transport_K_Realisable_aniso_therm_concen_VDF_Elem, Source_Transport_K_Realisable_anisotherme_VDF_Elem, Source_Transport_K_Realisable_VDF_Elem, Source_Transport_K_VDF_Elem, Source_Transport_K_Eps_aniso_therm_concen_VDF_Elem, Source_Transport_K_Eps_anisotherme_VDF_Elem, Source_Transport_K_Eps_Bas_Reynolds_aniso_therm_concen_VDF_Elem, Source_Transport_K_Eps_Bas_Reynolds_anisotherme_VDF_Elem, Source_Transport_K_Eps_Bas_Reynolds_anisotherme_QC_VDF_Elem, Source_Transport_K_Eps_Bas_Reynolds_anisotherme_W_VDF_Elem, Source_Transport_K_Eps_Bas_Reynolds_VDF_Elem, Source_Transport_K_Eps_Bas_Reynolds_W_VDF_Elem, Source_Transport_K_Eps_concen_VDF_Elem, Source_Transport_K_Eps_Realisable_aniso_concen_VDF_Elem, Source_Transport_K_Eps_Realisable_aniso_therm_concen_VDF_Elem, Source_Transport_K_Eps_Realisable_anisotherme_VDF_Elem, Source_Transport_K_Eps_Realisable_VDF_Elem, Source_Transport_K_Eps_VDF_Elem, Source_Transport_K_KEps_anisotherme_VDF_Elem, and Source_Transport_K_KEps_VDF_Elem.
self_cast() [1/2]
Source_Transport_VDF_Elem_base & Source_Transport_VDF_Elem_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Source_Transport_VDF_Elem_base & Source_Transport_VDF_Elem_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Source_Transport_VDF_Elem_base::printOn (Sortie & os) const override protected virtual
DOES NOTHING - to override in derived classes.
Imprime la source sur un flot de sortie.
Parameters
(Sortie& os) le flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Source_base.
Reimplemented in Source_Transport_Eps_aniso_therm_concen_VDF_Elem, Source_Transport_Eps_anisotherme_VDF_Elem, Source_Transport_Eps_concen_VDF_Elem, Source_Transport_Eps_Realisable_aniso_concen_VDF_Elem, Source_Transport_Eps_Realisable_aniso_therm_concen_VDF_Elem, Source_Transport_Eps_Realisable_anisotherme_VDF_Elem, Source_Transport_Eps_Realisable_VDF_Elem, Source_Transport_Eps_VDF_Elem, Source_Transport_K_aniso_therm_concen_VDF_Elem, Source_Transport_K_anisotherme_VDF_Elem, Source_Transport_K_concen_VDF_Elem, Source_Transport_K_Realisable_aniso_concen_VDF_Elem, Source_Transport_K_Realisable_aniso_therm_concen_VDF_Elem, Source_Transport_K_Realisable_anisotherme_VDF_Elem, Source_Transport_K_Realisable_VDF_Elem, Source_Transport_K_VDF_Elem, Source_Transport_K_Eps_aniso_therm_concen_VDF_Elem, Source_Transport_K_Eps_anisotherme_VDF_Elem, Source_Transport_K_Eps_Bas_Reynolds_aniso_therm_concen_VDF_Elem, Source_Transport_K_Eps_Bas_Reynolds_anisotherme_VDF_Elem, Source_Transport_K_Eps_Bas_Reynolds_anisotherme_QC_VDF_Elem, Source_Transport_K_Eps_Bas_Reynolds_anisotherme_W_VDF_Elem, Source_Transport_K_Eps_Bas_Reynolds_VDF_Elem, Source_Transport_K_Eps_Bas_Reynolds_W_VDF_Elem, Source_Transport_K_Eps_concen_VDF_Elem, Source_Transport_K_Eps_Realisable_aniso_concen_VDF_Elem, Source_Transport_K_Eps_Realisable_aniso_therm_concen_VDF_Elem, Source_Transport_K_Eps_Realisable_anisotherme_VDF_Elem, Source_Transport_K_Eps_Realisable_VDF_Elem, Source_Transport_K_Eps_VDF_Elem, Source_Transport_K_KEps_anisotherme_VDF_Elem, and Source_Transport_K_KEps_VDF_Elem.
References Objet_U::que_suis_je().
readOn()
Entree & Source_Transport_VDF_Elem_base::readOn (Entree & is) override protected virtual
DOES NOTHING - to override in derived classes.
Lecture d'un terme source sur un flot d'entree.
Parameters
(Entree& is) le flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Source_base.
Reimplemented in Source_Transport_Eps_aniso_therm_concen_VDF_Elem, Source_Transport_Eps_anisotherme_VDF_Elem, Source_Transport_Eps_concen_VDF_Elem, Source_Transport_Eps_Realisable_aniso_concen_VDF_Elem, Source_Transport_Eps_Realisable_aniso_therm_concen_VDF_Elem, Source_Transport_Eps_Realisable_anisotherme_VDF_Elem, Source_Transport_Eps_Realisable_VDF_Elem, Source_Transport_Eps_VDF_Elem, Source_Transport_K_aniso_therm_concen_VDF_Elem, Source_Transport_K_anisotherme_VDF_Elem, Source_Transport_K_concen_VDF_Elem, Source_Transport_K_Realisable_aniso_concen_VDF_Elem, Source_Transport_K_Realisable_aniso_therm_concen_VDF_Elem, Source_Transport_K_Realisable_anisotherme_VDF_Elem, Source_Transport_K_Realisable_VDF_Elem, Source_Transport_K_VDF_Elem, Source_Transport_K_Eps_aniso_therm_concen_VDF_Elem, Source_Transport_K_Eps_anisotherme_VDF_Elem, Source_Transport_K_Eps_Bas_Reynolds_aniso_therm_concen_VDF_Elem, Source_Transport_K_Eps_Bas_Reynolds_anisotherme_VDF_Elem, Source_Transport_K_Eps_Bas_Reynolds_anisotherme_QC_VDF_Elem, Source_Transport_K_Eps_Bas_Reynolds_anisotherme_W_VDF_Elem, Source_Transport_K_Eps_Bas_Reynolds_VDF_Elem, Source_Transport_K_Eps_Bas_Reynolds_W_VDF_Elem, Source_Transport_K_Eps_concen_VDF_Elem, Source_Transport_K_Eps_Realisable_aniso_concen_VDF_Elem, Source_Transport_K_Eps_Realisable_aniso_therm_concen_VDF_Elem, Source_Transport_K_Eps_Realisable_anisotherme_VDF_Elem, Source_Transport_K_Eps_Realisable_VDF_Elem, Source_Transport_K_Eps_VDF_Elem, Source_Transport_K_KEps_anisotherme_VDF_Elem, and Source_Transport_K_KEps_VDF_Elem.
References Objet_U::que_suis_je(), and Source_Transport_proto::readOn_proto().
Referenced by Source_Transport_Bas_Reynolds_VDF_Elem_base::readOn(), Source_Transport_Eps_VDF_Elem::readOn(), Source_Transport_K_Eps_VDF_Elem::readOn(), and Source_Transport_K_KEps_VDF_Elem::readOn().
calculer()
DoubleTab & Source_Transport_VDF_Elem_base::calculer (DoubleTab & resu) const override virtual
Reimplemented from Source_base.
References Source_base::ajouter().
associer_domaines()
void Source_Transport_VDF_Elem_base::associer_domaines (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis) override virtual
Implements Source_base.
References le_dom_Cl_VDF, and le_dom_VDF.
associer_pb()
void Source_Transport_VDF_Elem_base::associer_pb (const Probleme_base & pb) override virtual
Implements Source_base.
Reimplemented in Source_Transport_Eps_aniso_therm_concen_VDF_Elem, Source_Transport_Eps_anisotherme_VDF_Elem, Source_Transport_Eps_concen_VDF_Elem, Source_Transport_Eps_Realisable_aniso_concen_VDF_Elem, Source_Transport_Eps_Realisable_aniso_therm_concen_VDF_Elem, Source_Transport_Eps_Realisable_anisotherme_VDF_Elem, Source_Transport_Eps_Realisable_VDF_Elem, Source_Transport_K_aniso_therm_concen_VDF_Elem, Source_Transport_K_anisotherme_VDF_Elem, Source_Transport_K_concen_VDF_Elem, Source_Transport_K_Realisable_aniso_concen_VDF_Elem, Source_Transport_K_Realisable_aniso_therm_concen_VDF_Elem, Source_Transport_K_Realisable_anisotherme_VDF_Elem, Source_Transport_K_Realisable_VDF_Elem, Source_Transport_K_Eps_aniso_therm_concen_VDF_Elem, Source_Transport_K_Eps_anisotherme_VDF_Elem, Source_Transport_K_Eps_Bas_Reynolds_aniso_therm_concen_VDF_Elem, Source_Transport_K_Eps_Bas_Reynolds_anisotherme_VDF_Elem, Source_Transport_K_Eps_Bas_Reynolds_anisotherme_W_VDF_Elem, Source_Transport_K_Eps_concen_VDF_Elem, Source_Transport_K_Eps_Realisable_aniso_concen_VDF_Elem, Source_Transport_K_Eps_Realisable_aniso_therm_concen_VDF_Elem, Source_Transport_K_Eps_Realisable_anisotherme_VDF_Elem, Source_Transport_K_Eps_Realisable_VDF_Elem, Source_Transport_K_KEps_anisotherme_VDF_Elem, Source_Transport_Eps_VDF_Elem, Source_Transport_K_VDF_Elem, Source_Transport_K_Eps_VDF_Elem, and Source_Transport_K_KEps_VDF_Elem.
References Source_Transport_proto::associer_pb_proto().
Referenced by Source_Transport_Bas_Reynolds_VDF_Elem_base::associer_pb(), Source_Transport_Eps_Realisable_VDF_Elem::associer_pb(), Source_Transport_K_Realisable_VDF_Elem::associer_pb(), Source_Transport_K_Eps_Realisable_VDF_Elem::associer_pb(), Source_Transport_Eps_VDF_Elem::associer_pb(), Source_Transport_K_VDF_Elem::associer_pb(), Source_Transport_K_Eps_VDF_Elem::associer_pb(), and Source_Transport_K_KEps_VDF_Elem::associer_pb().
has_interface_blocs()
int Source_Transport_VDF_Elem_base::has_interface_blocs () const inline override virtual
Reimplemented from Source_base.
dimensionner_blocs()
void Source_Transport_VDF_Elem_base::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl) const inline override virtual
Reimplemented from Source_base.
Reimplemented in Source_Transport_Eps_VDF_Elem.
ajouter_blocs()
void Source_Transport_VDF_Elem_base::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl) const override pure virtual
Reimplemented from Source_base.
Implemented in Source_Transport_Bas_Reynolds_VDF_Elem_base, Source_Transport_Realisable_VDF_Elem_base, Source_Transport_Eps_aniso_therm_concen_VDF_Elem, Source_Transport_Eps_anisotherme_VDF_Elem, Source_Transport_Eps_concen_VDF_Elem, Source_Transport_Eps_Realisable_aniso_concen_VDF_Elem, Source_Transport_Eps_Realisable_aniso_therm_concen_VDF_Elem, Source_Transport_Eps_Realisable_anisotherme_VDF_Elem, Source_Transport_Eps_Realisable_VDF_Elem, Source_Transport_Eps_VDF_Elem, Source_Transport_K_aniso_therm_concen_VDF_Elem, Source_Transport_K_anisotherme_VDF_Elem, Source_Transport_K_concen_VDF_Elem, Source_Transport_K_Realisable_aniso_concen_VDF_Elem, Source_Transport_K_Realisable_aniso_therm_concen_VDF_Elem, Source_Transport_K_Realisable_anisotherme_VDF_Elem, Source_Transport_K_Realisable_VDF_Elem, Source_Transport_K_VDF_Elem, Source_Transport_K_Eps_aniso_therm_concen_VDF_Elem, Source_Transport_K_Eps_anisotherme_VDF_Elem, Source_Transport_K_Eps_Bas_Reynolds_aniso_therm_concen_VDF_Elem, Source_Transport_K_Eps_Bas_Reynolds_anisotherme_VDF_Elem, Source_Transport_K_Eps_Bas_Reynolds_anisotherme_QC_VDF_Elem, Source_Transport_K_Eps_Bas_Reynolds_anisotherme_W_VDF_Elem, Source_Transport_K_Eps_concen_VDF_Elem, Source_Transport_K_Eps_Realisable_aniso_concen_VDF_Elem, Source_Transport_K_Eps_Realisable_aniso_therm_concen_VDF_Elem, Source_Transport_K_Eps_Realisable_anisotherme_VDF_Elem, Source_Transport_K_Eps_Realisable_VDF_Elem, Source_Transport_K_Eps_VDF_Elem, Source_Transport_K_KEps_anisotherme_VDF_Elem, and Source_Transport_K_KEps_VDF_Elem.
mettre_a_jour()
void Source_Transport_VDF_Elem_base::mettre_a_jour (double temps) inline override virtual
DOES NOTHING - to override in derived classes.
Mise a jour en temps du terme source.
Parameters
(double) le pas de temps de mise a jour
Reimplemented from Source_base.
Reimplemented in Source_Transport_Eps_Realisable_VDF_Elem, Source_Transport_K_Realisable_VDF_Elem, and Source_Transport_K_Eps_Realisable_VDF_Elem.
References Calcul_Production_K_VDF::mettre_a_jour().
Referenced by Source_Transport_Eps_Realisable_VDF_Elem::mettre_a_jour(), Source_Transport_K_Realisable_VDF_Elem::mettre_a_jour(), and Source_Transport_K_Eps_Realisable_VDF_Elem::mettre_a_jour().
ajouter_keps()
DoubleTab & Source_Transport_VDF_Elem_base::ajouter_keps (DoubleTab & resu) const protected
References Domaine_32_64< _SIZE_ >::creer_tableau_elements(), Domaine_dis_base::domaine(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Source_Transport_proto::eq_hydraulique, MorEqn::equation(), le_dom_VDF, TRUSTTab< _TYPE_, _SIZE_ >::ref(), TRUST_Ref< _CLASSE_ >::valeur(), Debog::verifier(), and Fluide_base::viscosite_cinematique().
Referenced by Source_Transport_Eps_VDF_Elem::ajouter_blocs(), Source_Transport_K_VDF_Elem::ajouter_blocs(), and Source_Transport_K_Eps_VDF_Elem::ajouter_blocs().
ajouter_anisotherme()
DoubleTab & Source_Transport_VDF_Elem_base::ajouter_anisotherme (DoubleTab & resu) const protected
References Source_Transport_proto::beta_t, Calcul_Production_K_VDF::calculer_terme_destruction_K(), Modele_turbulence_scal_base::diffusivite_turbulente(), Source_Transport_proto::eq_thermique, Source_Transport_proto::gravite, le_dom_Cl_VDF, le_dom_VDF, TRUST_Ref< _CLASSE_ >::valeur(), and Champ_Don_base::valeurs().
Referenced by Source_Transport_Eps_anisotherme_VDF_Elem::ajouter_blocs(), Source_Transport_Eps_Realisable_anisotherme_VDF_Elem::ajouter_blocs(), Source_Transport_K_anisotherme_VDF_Elem::ajouter_blocs(), Source_Transport_K_Realisable_anisotherme_VDF_Elem::ajouter_blocs(), Source_Transport_K_Eps_anisotherme_VDF_Elem::ajouter_blocs(), Source_Transport_K_Eps_Realisable_anisotherme_VDF_Elem::ajouter_blocs(), and Source_Transport_K_KEps_anisotherme_VDF_Elem::ajouter_blocs().
ajouter_concen()
DoubleTab & Source_Transport_VDF_Elem_base::ajouter_concen (DoubleTab & resu) const protected
References Source_Transport_proto::beta_c, Calcul_Production_K_VDF::calculer_terme_destruction_K(), Modele_turbulence_scal_base::conductivite_turbulente(), Source_Transport_proto::eq_concentration, Source_Transport_proto::gravite, le_dom_Cl_VDF, le_dom_VDF, TRUST_Ref< _CLASSE_ >::valeur(), and Champ_Don_base::valeurs().
Referenced by Source_Transport_Eps_concen_VDF_Elem::ajouter_blocs(), Source_Transport_Eps_Realisable_aniso_concen_VDF_Elem::ajouter_blocs(), Source_Transport_K_concen_VDF_Elem::ajouter_blocs(), Source_Transport_K_Realisable_aniso_concen_VDF_Elem::ajouter_blocs(), Source_Transport_K_Eps_concen_VDF_Elem::ajouter_blocs(), and Source_Transport_K_Eps_Realisable_aniso_concen_VDF_Elem::ajouter_blocs().
ajouter_anisotherme_concen()
DoubleTab & Source_Transport_VDF_Elem_base::ajouter_anisotherme_concen (DoubleTab & resu) const protected
References Source_Transport_proto::beta_c, Source_Transport_proto::beta_t, Calcul_Production_K_VDF::calculer_terme_destruction_K(), Modele_turbulence_scal_base::conductivite_turbulente(), Source_Transport_proto::eq_concentration, Source_Transport_proto::eq_thermique, Source_Transport_proto::gravite, le_dom_Cl_VDF, le_dom_VDF, TRUST_Ref< _CLASSE_ >::valeur(), and Champ_Don_base::valeurs().
Referenced by Source_Transport_Eps_aniso_therm_concen_VDF_Elem::ajouter_blocs(), Source_Transport_Eps_Realisable_aniso_therm_concen_VDF_Elem::ajouter_blocs(), Source_Transport_K_aniso_therm_concen_VDF_Elem::ajouter_blocs(), Source_Transport_K_Realisable_aniso_therm_concen_VDF_Elem::ajouter_blocs(), Source_Transport_K_Eps_aniso_therm_concen_VDF_Elem::ajouter_blocs(), and Source_Transport_K_Eps_Realisable_aniso_therm_concen_VDF_Elem::ajouter_blocs().
Member Data Documentation
info_obj
const Type_info Source_Transport_VDF_Elem_base::info_obj static
le_dom_VDF
TRUST_Ref< Domaine_VDF *> Source_Transport_VDF_Elem_base::le_dom_VDF protected
Referenced by ajouter_anisotherme(), ajouter_anisotherme_concen(), Source_Transport_Bas_Reynolds_VDF_Elem_base::ajouter_blocs(), Source_Transport_Realisable_VDF_Elem_base::ajouter_blocs(), Source_Transport_Eps_VDF_Elem::ajouter_blocs(), Source_Transport_K_Realisable_VDF_Elem::ajouter_blocs(), Source_Transport_K_VDF_Elem::ajouter_blocs(), Source_Transport_K_Eps_VDF_Elem::ajouter_blocs(), Source_Transport_K_KEps_VDF_Elem::ajouter_blocs(), ajouter_concen(), ajouter_keps(), Source_Transport_Realisable_VDF_Elem_base::ajouter_keps_real(), and associer_domaines().
le_dom_Cl_VDF
TRUST_Ref< Domaine_Cl_VDF *> Source_Transport_VDF_Elem_base::le_dom_Cl_VDF protected
Referenced by ajouter_anisotherme(), ajouter_anisotherme_concen(), Source_Transport_Bas_Reynolds_VDF_Elem_base::ajouter_blocs(), Source_Transport_Realisable_VDF_Elem_base::ajouter_blocs(), Source_Transport_Eps_VDF_Elem::ajouter_blocs(), Source_Transport_K_Realisable_VDF_Elem::ajouter_blocs(), Source_Transport_K_VDF_Elem::ajouter_blocs(), Source_Transport_K_Eps_Bas_Reynolds_aniso_therm_concen_VDF_Elem::ajouter_blocs(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_VDF_Elem::ajouter_blocs(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_QC_VDF_Elem::ajouter_blocs(), Source_Transport_K_Eps_VDF_Elem::ajouter_blocs(), Source_Transport_K_KEps_VDF_Elem::ajouter_blocs(), ajouter_concen(), and associer_domaines().