TrioCFD: DomaineAxi1d_32_64< _SIZE_ > Class Template Reference
DomaineAxi1d_32_64< _SIZE_ > Class Template Reference
#include <DomaineAxi1d.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Domaine_32_64< _SIZE_ >
void ajouter (const DoubleTab_t &soms)
void ajouter (const DoubleTab_t &soms, IntVect_t &nums)
int associer_ (Objet_U &) override
Bord_Interne_t & bords_interne (int i)
void build_mc_mesh () const
void calculer_centres_gravite (DoubleTab_t &xp) const
void calculer_centres_gravite_aretes (DoubleTab_t &xa) const
void calculer_volumes (DoubleVect_t &volumes, DoubleVect_t &inv_volumes) const
SmallArrOfTID_t & chercher_aretes (const DoubleTab &pos, SmallArrOfTID_t &arr, int reel=0) const
SmallArrOfTID_t & chercher_elements (const DoubleTab &pos, SmallArrOfTID_t &elem, int reel=0) const
SmallArrOfTID_t & chercher_elements (const DoubleVect &pos, SmallArrOfTID_t &elem, int reel=0) const
int_t chercher_elements (double x, double y=0, double z=0, int reel=0) const
SmallArrOfTID_t & chercher_sommets (const DoubleTab &pos, SmallArrOfTID_t &som, int reel=0) const
int_t chercher_sommets (double x, double y=0, double z=0, int reel=0) const
virtual void clear ()
void construire_elem_virt_pe_num ()
void correct_type_of_borders_after_merge ()
virtual void creer_tableau_elements (Array_base &, RESIZE_OPTIONS opt=RESIZE_OPTIONS::COPY_INIT) const
virtual void creer_tableau_sommets (Array_base &, RESIZE_OPTIONS opt=RESIZE_OPTIONS::COPY_INIT) const
const TRUST_List< TRUST_Ref< Domaine_32_64 * > > & domaines_frontieres () const
void ecrire_noms_bords (Sortie &) const
int_t face_bords_interne_conjuguee (int_t face) const
void fill_from_list (std::list< Domaine_32_64 * > &lst)
const Frontiere_t & frontiere (int i) const
const Type_info * get_info () const override
const ArrOfInt_t & ind_faces_virt_bord () const
SmallArrOfTID_t & indice_elements (const IntTab &som, SmallArrOfTID_t &elem, int reel=0) const
void init_renum_perio ()
int nb_bords () const
int nb_faces_elem (int=0) const
int_t nb_faces_frontiere (Type_Face type) const
int_t nb_faces_specifiques () const
int_t nb_faces_specifiques (Type_Face type) const
int nb_groupes_faces () const
int nb_joints () const
int nb_raccords () const
int nb_som_elem () const
void renum (const IntVect_t &nums)
void renum_joint_common_items (const IntVect_t &nums, const int_t elem_offset)
void typer (const Nom &)
Public Member Functions inherited from Domaine_base
const Type_info * get_info () const override
const Nom & le_nom () const override
void nommer (const Nom &nom) override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Domaine_32_64< _SIZE_ >
static int identifie_item_unique (IntList &item_possible, DoubleTab &coord_possible, const DoubleVect &coord_ref)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
template<typename _SIZE_>
class DomaineAxi1d_32_64< _SIZE_ >
Member Typedef Documentation
int_t
template<typename _SIZE_ > using DomaineAxi1d_32_64< _SIZE_ >::int_t = _SIZE_
DoubleTab_t
template<typename _SIZE_ > using DomaineAxi1d_32_64< _SIZE_ >::DoubleTab_t = DoubleTab_T<_SIZE_>
Constructor & Destructor Documentation
DomaineAxi1d_32_64()
template<typename _SIZE_ > DomaineAxi1d_32_64< _SIZE_ >::DomaineAxi1d_32_64
~DomaineAxi1d_32_64()
template<typename _T_ > DomaineAxi1d_32_64< _T_ >::~DomaineAxi1d_32_64
Member Function Documentation
cree_instance()
template<typename _T_ > Objet_U * DomaineAxi1d_32_64< _T_ >::cree_instance static
taille_memoire()
template<typename _T_ > unsigned DomaineAxi1d_32_64< _T_ >::taille_memoire override virtual
Reimplemented from Domaine_32_64< _SIZE_ >.
duplique()
template<typename _T_ > int DomaineAxi1d_32_64< _T_ >::duplique override virtual
Reimplemented from Domaine_32_64< _SIZE_ >.
info()
template<typename _T_ > const Type_info * DomaineAxi1d_32_64< _T_ >::info static
get_info()
template<typename _T_ > const Type_info * DomaineAxi1d_32_64< _T_ >::get_info override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Domaine_32_64< _SIZE_ >.
self_cast() [1/2]
template<typename _T_ > DomaineAxi1d_32_64< _T_ > & DomaineAxi1d_32_64< _T_ >::self_cast (Objet_U & r) static
self_cast() [2/2]
template<typename _T_ > const DomaineAxi1d_32_64< _T_ > & DomaineAxi1d_32_64< _T_ >::self_cast (const Objet_U & r) static
printOn()
template<typename _SIZE_ > Sortie & DomaineAxi1d_32_64< _SIZE_ >::printOn (Sortie & s) const override protected virtual
Ecrit la Domaine sur un flot de sortie.
On ecrit le nom, le type des elements, les elements et les bords, les bords periodiques, les joints, les raccords et les bords internes.
Parameters
(Sortie& s) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Domaine_32_64< _SIZE_ >.
References Domaine_32_64< _SIZE_ >::printOn().
readOn()
template<typename _SIZE_ > Entree & DomaineAxi1d_32_64< _SIZE_ >::readOn (Entree & s) override protected virtual
Lit les objets constituant un Domaine a partir d'un flot d'entree.
Une fois les objets lus on les associe au domaine.
Parameters
(Entree& s) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Domaine_32_64< _SIZE_ >.
References Param::lire_avec_accolades_depuis().
champ_origine() [1/2]
template<typename _SIZE_ > const Champ_base & DomaineAxi1d_32_64< _SIZE_ >::champ_origine () const inline
References DomaineAxi1d_32_64< _SIZE_ >::champ_orig, and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by Domaine_EF_axi::remplir_tableau_origine().
champ_origine() [2/2]
template<typename _SIZE_ > const Champ_base & DomaineAxi1d_32_64< _SIZE_ >::champ_origine () inline
References DomaineAxi1d_32_64< _SIZE_ >::champ_orig, and TRUST_Deriv< _CLASSE_ >::valeur().
has_champ_origine()
template<typename _SIZE_ > bool DomaineAxi1d_32_64< _SIZE_ >::has_champ_origine () const inline
References DomaineAxi1d_32_64< _SIZE_ >::champ_orig, and Objet_U_ptr::non_nul().
Referenced by Domaine_EF_axi::remplir_tableau_origine().
origine_repere() [1/4]
template<typename _SIZE_ > const DoubleTab_t & DomaineAxi1d_32_64< _SIZE_ >::origine_repere () inline
References DomaineAxi1d_32_64< _SIZE_ >::ref_origine_.
Referenced by Segment_axi_32_64< _SIZE_ >::calculer_volumes(), and Segment_EF_axi::normale().
origine_repere() [2/4]
template<typename _SIZE_ > const DoubleTab_t & DomaineAxi1d_32_64< _SIZE_ >::origine_repere () const inline
References DomaineAxi1d_32_64< _SIZE_ >::ref_origine_.
associer_origine_repere()
template<typename _SIZE_ > void DomaineAxi1d_32_64< _SIZE_ >::associer_origine_repere (const DoubleTab_t & orig) inline
References DomaineAxi1d_32_64< _SIZE_ >::ref_origine_.
Referenced by Domaine_EF_axi::remplir_tableau_origine().
origine_repere() [3/4]
template<typename _SIZE_ > double DomaineAxi1d_32_64< _SIZE_ >::origine_repere (int_t i, int j) inline
References DomaineAxi1d_32_64< _SIZE_ >::ref_origine_.
origine_repere() [4/4]
template<typename _SIZE_ > double DomaineAxi1d_32_64< _SIZE_ >::origine_repere (int_t i, int j) const inline
References DomaineAxi1d_32_64< _SIZE_ >::ref_origine_.
set_param()
template<typename _SIZE_ > void DomaineAxi1d_32_64< _SIZE_ >::set_param (Param & param) protected
References Param::ajouter(), and Param::REQUIRED.
info_obj() [1/2]
const Type_info DomaineAxi1d_32_64< int >::info_obj ("DomaineAxi1d" , DomaineAxi1d_32_64< int >::cree_instance , 1 , DomaineAxi1d_32_64bases< int >)
info_obj() [2/2]
const Type_info DomaineAxi1d_32_64< trustIdType >::info_obj ("DomaineAxi1d" "_64" , DomaineAxi1d_32_64< trustIdType >::cree_instance , 1 , DomaineAxi1d_32_64bases< trustIdType >)
Member Data Documentation
info_obj
template<typename _SIZE_ > const Type_info DomaineAxi1d_32_64< _SIZE_ >::info_obj static
champ_orig
template<typename _SIZE_ > TRUST_Deriv< Champ_base > DomaineAxi1d_32_64< _SIZE_ >::champ_orig protected
Referenced by DomaineAxi1d_32_64< _SIZE_ >::champ_origine(), and DomaineAxi1d_32_64< _SIZE_ >::has_champ_origine().
ref_origine_
template<typename _SIZE_ > TRUST_Ref< DoubleTab_t *> DomaineAxi1d_32_64< _SIZE_ >::ref_origine_ protected
Referenced by DomaineAxi1d_32_64< _SIZE_ >::associer_origine_repere(), and DomaineAxi1d_32_64< _SIZE_ >::origine_repere().