TrioCFD: Changement_phase_Silver_Simpson Class Reference
Changement_phase_Silver_Simpson Class Reference
#include <Changement_phase_Silver_Simpson.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Changement_phase_Silver_Simpson()
Changement_phase_Silver_Simpson::Changement_phase_Silver_Simpson ()
~Changement_phase_Silver_Simpson()
Changement_phase_Silver_Simpson::~Changement_phase_Silver_Simpson ()
Member Function Documentation
cree_instance()
Objet_U * Changement_phase_Silver_Simpson::cree_instance () static
taille_memoire()
unsigned Changement_phase_Silver_Simpson::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Changement_phase_Silver_Simpson::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Changement_phase_Silver_Simpson::info () static
get_info()
const Type_info * Changement_phase_Silver_Simpson::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Changement_phase_base.
self_cast() [1/2]
Changement_phase_Silver_Simpson & Changement_phase_Silver_Simpson::self_cast (Objet_U & r) static
self_cast() [2/2]
const Changement_phase_Silver_Simpson & Changement_phase_Silver_Simpson::self_cast (const Objet_U & r) static
printOn()
Sortie & Changement_phase_Silver_Simpson::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Changement_phase_base.
readOn()
Entree & Changement_phase_Silver_Simpson::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Changement_phase_base.
References Param::ajouter(), alpha_min, lambda_ec, Param::lire_avec_accolades_depuis(), M, Objet_U::que_suis_je(), and Param::REQUIRED.
calculer()
double Changement_phase_Silver_Simpson::calculer (int k, int l, const double dh, const double * alpha, const double * T, const double p, const double * nv, const double * lambda, const double * mu, const double * rho, const double * Cp, const Saturation_base & sat, DoubleTab & dT_G, DoubleTab & da_G, double & dp_G) const override virtual
Implements Changement_phase_base.
References alpha_min, and Saturation_base::Psat().
Member Data Documentation
info_obj
const Type_info Changement_phase_Silver_Simpson::info_obj static
lambda_ec
double Changement_phase_Silver_Simpson::lambda_ec[2] = { 1, 1 } protected
Referenced by readOn().
M
double Changement_phase_Silver_Simpson::M = -100. protected
Referenced by readOn().
alpha_min
double Changement_phase_Silver_Simpson::alpha_min = 0.1 protected
Referenced by calculer(), and readOn().