TrioCFD: EDO_Pression_th_VEF Class Reference
EDO_Pression_th_VEF Class Reference
#include <EDO_Pression_th_VEF.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from EDO_Pression_th_base
void associer_fluide (const Fluide_Dilatable_base &)
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
de calcul pour les fluides faiblement compressibles, et relatif a
discretisation de type VEF.
See also
Fluide_Quasi_Compressible EDO_Pression_th_base
Constructor & Destructor Documentation
EDO_Pression_th_VEF()
EDO_Pression_th_VEF::EDO_Pression_th_VEF ()
~EDO_Pression_th_VEF()
EDO_Pression_th_VEF::~EDO_Pression_th_VEF () override
Member Function Documentation
info()
const Type_info * EDO_Pression_th_VEF::info () static
get_info()
const Type_info * EDO_Pression_th_VEF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from EDO_Pression_th_base.
Reimplemented in EDO_Pression_th_VEF_Gaz_Parfait, and EDO_Pression_th_VEF_Gaz_Reel.
self_cast() [1/2]
EDO_Pression_th_VEF & EDO_Pression_th_VEF::self_cast (Objet_U & r) static
self_cast() [2/2]
const EDO_Pression_th_VEF & EDO_Pression_th_VEF::self_cast (const Objet_U & r) static
printOn()
Sortie & EDO_Pression_th_VEF::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from EDO_Pression_th_base.
Reimplemented in EDO_Pression_th_VEF_Gaz_Parfait, and EDO_Pression_th_VEF_Gaz_Reel.
References EDO_Pression_th_base::printOn().
readOn()
Entree & EDO_Pression_th_VEF::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from EDO_Pression_th_base.
Reimplemented in EDO_Pression_th_VEF_Gaz_Parfait, and EDO_Pression_th_VEF_Gaz_Reel.
References EDO_Pression_th_base::readOn().
completer()
void EDO_Pression_th_VEF::completer () override virtual
Reimplemented from EDO_Pression_th_base.
References EDO_Pression_th_base::completer(), Process::exit(), EDO_Pression_th_base::le_dom, and TRUST_Ref< _CLASSE_ >::valeur().
calculer_grad()
void EDO_Pression_th_VEF::calculer_grad (const DoubleTab & inco, DoubleTab & grad)
References Domaine_32_64< _SIZE_ >::coord_sommets(), Objet_U::dimension, Domaine_dis_base::domaine(), Domaine_VF::face_normales(), Domaine_VF::face_sommets(), Domaine_VF::face_voisins(), EDO_Pression_th_base::le_dom, EDO_Pression_th_base::le_dom_Cl, Domaine_32_64< _SIZE_ >::les_elems(), Domaine_dis_base::nb_elem(), Domaine_VF::nb_faces(), Front_VF::nb_faces(), Domaine_VEF::nb_faces_joint(), Domaine_dis_base::nb_front_Cl(), Domaine_32_64< _SIZE_ >::nb_som(), Domaine_32_64< _SIZE_ >::nb_som_elem(), Front_VF::num_premiere_face(), Domaine_VF::premiere_face_int(), Domaine_VEF::premiere_face_std(), TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), Domaine_VF::volumes(), Domaine_VF::volumes_entrelaces(), and Domaine_VF::xp().
Referenced by EDO_Pression_th_VEF_Gaz_Reel::resoudre().
masse_totale() [1/2]
double EDO_Pression_th_VEF::masse_totale (double P, const DoubleTab & T) override virtual
Implements EDO_Pression_th_base.
References TRUSTVect< _TYPE_, _SIZE_ >::copy(), EDO_Pression_th_base::le_dom, EDO_Pression_th_base::le_fluide_, Domaine_VF::nb_faces(), and TRUST_Ref< _CLASSE_ >::valeur().
masse_totale() [2/2]
double EDO_Pression_th_VEF::masse_totale (const DoubleTab & P, const DoubleTab & T) override virtual
Implements EDO_Pression_th_base.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), EDO_Pression_th_base::le_dom, Domaine_VF::nb_faces(), and TRUST_Ref< _CLASSE_ >::valeur().
Member Data Documentation
info_obj
const Type_info EDO_Pression_th_VEF::info_obj static