TrioCFD: Convection_Diffusion_Phase_field Class Reference
Convection_Diffusion_Phase_field Class Reference
#include <Convection_Diffusion_Phase_field.h>
Public Member Functions
void completer () override
const Type_info * get_info () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
int preparer_calcul () override
Public Member Functions inherited from Convection_Diffusion_Concentration
void associer_constituant (const Constituant &)
void associer_milieu_base (const Milieu_base &) override
Constituant & constituant ()
const Constituant & constituant () const
const Motcle & domaine_application () const override
const Type_info * get_info () const override
int impr (Sortie &os) const override
const Champ_Inc_base & inconnue () const override
Champ_Inc_base & inconnue () override
int lire_motcle_non_standard (const Motcle &, Entree &) override
void mettre_a_jour (double) override
const Milieu_base & milieu () const override
Milieu_base & milieu () override
int nb_constituants () const
int preparer_calcul () override
Public Member Functions inherited from Convection_Diffusion_std
void associer_vitesse (const Champ_base &)
const Type_info * get_info () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
int nombre_d_operateurs () const override
const Operateur & operateur (int) const override
Operateur & operateur (int) override
const Champ_Inc_base & vitesse_transportante () const
Public Member Functions inherited from Equation_base
virtual void abortTimeStep ()
virtual void associer_domaine_dis (const Domaine_dis_base &)
virtual void associer_pb_base (const Probleme_base &)
virtual void associer_sch_tps_base (const Schema_Temps_base &)
virtual double calculer_pas_de_temps () const
virtual void completer ()
virtual std::vector< YAML_data > data_a_sauvegarder () const
DoubleTab & derivee_en_temps_conv (DoubleTab &, const DoubleTab &)
virtual DoubleTab & derivee_en_temps_inco (DoubleTab &)
const Discretisation_base & discretisation () const
virtual void discretiser ()
virtual const Motcle & domaine_application () const
virtual Domaine_Cl_dis_base & domaine_Cl_dis ()
virtual const Domaine_Cl_dis_base & domaine_Cl_dis () const
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual void imprimer (Sortie &os) const
virtual bool initTimeStep (double dt)
const Nom & le_nom () const override
int limpr () const
virtual void mettre_a_jour (double temps)
virtual int preparer_calcul ()
Probleme_base & probleme ()
const Probleme_base & probleme () const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Schema_Temps_base & schema_temps ()
const Schema_Temps_base & schema_temps () const
Solveur_Masse_base & solv_masse ()
const Solveur_Masse_base & solv_masse () const
Sources & sources ()
const Sources & sources () const
virtual void valider_iteration ()
virtual void verifie_ch_init_nb_comp (const Champ_Inc_base &ch_ref, const int nb_comp) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Equation_base
virtual Entree & lire_cl (Entree &)
virtual Entree & lire_cond_init (Entree &)
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual Entree & lire_sources (Entree &)
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
virtual int verif_Cl () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
pour un ou plusieurs constituants.
Dans le cas de plusieurs constituants les champs
concentration et diffusivite sont vectoriels.
See also
Convection_Diffusion_Concentration
Constructor & Destructor Documentation
~Convection_Diffusion_Phase_field()
Convection_Diffusion_Phase_field::~Convection_Diffusion_Phase_field ()
Convection_Diffusion_Phase_field()
Convection_Diffusion_Phase_field::Convection_Diffusion_Phase_field ()
References mutype_.
Member Function Documentation
cree_instance()
Objet_U * Convection_Diffusion_Phase_field::cree_instance () static
taille_memoire()
unsigned Convection_Diffusion_Phase_field::taille_memoire () const override virtual
Reimplemented from Convection_Diffusion_Concentration.
duplique()
int Convection_Diffusion_Phase_field::duplique () const override virtual
Reimplemented from Convection_Diffusion_Concentration.
info()
const Type_info * Convection_Diffusion_Phase_field::info () static
get_info()
const Type_info * Convection_Diffusion_Phase_field::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Convection_Diffusion_Concentration.
self_cast() [1/2]
Convection_Diffusion_Phase_field & Convection_Diffusion_Phase_field::self_cast (Objet_U & r) static
self_cast() [2/2]
const Convection_Diffusion_Phase_field & Convection_Diffusion_Phase_field::self_cast (const Objet_U & r) static
printOn()
Sortie & Convection_Diffusion_Phase_field::printOn (Sortie & os) const override protected virtual
Surcharge Objet_U::printOn Imprime l'equation et ses composants sur un flot de sortie.
Imprime le nom de l'equation, le solveur masse, les termes sources les conditions aux limites discretisees, les inconnues et les operateurs.
Parameters
(Sortie& os) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Convection_Diffusion_Concentration.
References Convection_Diffusion_Concentration::printOn().
readOn()
Entree & Convection_Diffusion_Phase_field::readOn (Entree & is) override protected virtual
Verifie si l'equation a une concentration et un constituant associe et appelle Convection_Diffusion_std::readOn(Entree&).
Parameters
(Entree& is) un flot d'entree
Returns
(Entree& is) le flot d'entree modifie
Reimplemented from Convection_Diffusion_Concentration.
References Convection_Diffusion_Concentration::readOn().
set_param()
void Convection_Diffusion_Phase_field::set_param (Param & titi) override virtual
Reimplemented from Convection_Diffusion_Concentration.
References Param::ajouter_non_std(), Param::REQUIRED, and Convection_Diffusion_Concentration::set_param().
lire_motcle_non_standard()
int Convection_Diffusion_Phase_field::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Convection_Diffusion_Concentration.
References Process::exit(), Convection_Diffusion_Concentration::lire_motcle_non_standard(), and mutype_.
discretiser()
void Convection_Diffusion_Phase_field::discretiser () override virtual
Discretise l'equation.
Reimplemented from Convection_Diffusion_Concentration.
References Champs_compris_T< FIELD_TYPE >::ajoute_champ(), MorEqn::associer_eqn(), Operateur_base::associer_eqn(), ch_mutilde, Equation_base::champs_compris_, Convection_Diffusion_Concentration::constituant(), Equation_base::discretisation(), Convection_Diffusion_Concentration::discretiser(), Discretisation_base::discretiser_champ(), Equation_base::domaine_dis(), gradient, Operateur_Grad::l_op_base(), Convection_Diffusion_Concentration::nb_constituants(), Equation_base::probleme(), Equation_base::schema_temps(), and Operateur_Grad::typer().
set_mutilde_()
Champ_Fonc_base & Convection_Diffusion_Phase_field::set_mutilde_ () inline
References ch_mutilde.
Referenced by Source_Con_Phase_field::mettre_a_jour(), and Source_Con_Phase_field::premier_demi_dt().
set_mutilde()
DoubleTab & Convection_Diffusion_Phase_field::set_mutilde () inline
References mutilde.
set_mutilde_demi()
DoubleTab & Convection_Diffusion_Phase_field::set_mutilde_demi () inline
References mutilde_demi.
Referenced by Source_Con_Phase_field::premier_demi_dt().
set_c_demi()
DoubleTab & Convection_Diffusion_Phase_field::set_c_demi () inline
References c_demi.
Referenced by Source_Con_Phase_field::premier_demi_dt().
set_div_alpha_rho_gradC()
DoubleTab & Convection_Diffusion_Phase_field::set_div_alpha_rho_gradC () inline
References div_alpha_rho_gradC.
set_div_alpha_gradC()
DoubleTab & Convection_Diffusion_Phase_field::set_div_alpha_gradC () inline
References div_alpha_gradC.
Referenced by Source_Con_Phase_field::premier_demi_dt().
set_alpha_gradC_carre()
DoubleTab & Convection_Diffusion_Phase_field::set_alpha_gradC_carre () inline
References alpha_gradC_carre.
set_pression_thermo()
DoubleTab & Convection_Diffusion_Phase_field::set_pression_thermo () inline
References pression_thermo.
get_mutilde_()
const Champ_Fonc_base & Convection_Diffusion_Phase_field::get_mutilde_ () const inline
References ch_mutilde.
Referenced by Source_Qdm_VDF_Phase_field::methode_1().
get_mutilde()
const DoubleTab & Convection_Diffusion_Phase_field::get_mutilde () const inline
References mutilde.
get_mutilde_demi()
const DoubleTab & Convection_Diffusion_Phase_field::get_mutilde_demi () const inline
References mutilde_demi.
get_c_demi()
const DoubleTab & Convection_Diffusion_Phase_field::get_c_demi () const inline
References c_demi.
Referenced by Schema_Phase_field::deuxieme_dt().
get_div_alpha_rho_gradC()
const DoubleTab & Convection_Diffusion_Phase_field::get_div_alpha_rho_gradC () const inline
References div_alpha_rho_gradC.
Referenced by Source_Qdm_VDF_Phase_field::methode_2(), Source_Qdm_VDF_Phase_field::methode_3(), and Source_Qdm_VDF_Phase_field::methode_4().
get_div_alpha_gradC()
const DoubleTab & Convection_Diffusion_Phase_field::get_div_alpha_gradC () const inline
References div_alpha_gradC.
Referenced by Source_Con_Phase_field::calculer_mutilde(), and Source_Con_Phase_field::calculer_pression_thermo().
get_alpha_gradC_carre()
const DoubleTab & Convection_Diffusion_Phase_field::get_alpha_gradC_carre () const inline
References alpha_gradC_carre.
Referenced by Source_Qdm_VDF_Phase_field::methode_3().
get_pression_thermo()
const DoubleTab & Convection_Diffusion_Phase_field::get_pression_thermo () const inline
References pression_thermo.
preparer_calcul()
int Convection_Diffusion_Phase_field::preparer_calcul () override virtual
Tout ce qui ne depend pas des autres problemes eventuels.
Returns
(int) renvoie toujours 1
Reimplemented from Convection_Diffusion_Concentration.
References alpha_gradC_carre, div_alpha_gradC, div_alpha_rho_gradC, Convection_Diffusion_Concentration::inconnue(), Sources::mettre_a_jour(), mutilde, Convection_Diffusion_Concentration::preparer_calcul(), Equation_base::schema_temps(), Equation_base::sources(), and Champ_Inc_base::valeurs().
operateur_gradient() [1/2]
Operateur_Grad & Convection_Diffusion_Phase_field::operateur_gradient ()
References gradient.
operateur_gradient() [2/2]
const Operateur_Grad & Convection_Diffusion_Phase_field::operateur_gradient () const
References gradient.
completer()
void Convection_Diffusion_Phase_field::completer () override virtual
Complete la construction (initialisation) des objets associes a l'equation.
Complete les sources, associe l'equation a l'inconnue complete les operateurs, complete les conditions aux limites discretisees. Voir les methodes Source_base::completer(), Operateur_base::completer() Domaine_Cl_dis_base::completer() Domaine_Cl_dis_base::completer(const Domaine_dis_base&)
Reimplemented from Equation_base.
References Equation_base::completer(), Operateur::completer(), and gradient.
get_mutype_() [1/2]
int & Convection_Diffusion_Phase_field::get_mutype_ () inline
References mutype_.
Referenced by Source_Con_Phase_field::associer_pb(), and Source_Qdm_VDF_Phase_field::methode_1().
get_mutype_() [2/2]
int Convection_Diffusion_Phase_field::get_mutype_ () const inline
References mutype_.
Member Data Documentation
info_obj
const Type_info Convection_Diffusion_Phase_field::info_obj static
ch_mutilde
TRUST_Deriv< Champ_Fonc_base > Convection_Diffusion_Phase_field::ch_mutilde protected
Referenced by discretiser(), get_mutilde_(), and set_mutilde_().
gradient
Operateur_Grad Convection_Diffusion_Phase_field::gradient protected
Referenced by completer(), discretiser(), and operateur_gradient().
div_alpha_gradC
DoubleTab Convection_Diffusion_Phase_field::div_alpha_gradC protected
Referenced by get_div_alpha_gradC(), preparer_calcul(), and set_div_alpha_gradC().
div_alpha_rho_gradC
DoubleTab Convection_Diffusion_Phase_field::div_alpha_rho_gradC protected
Referenced by get_div_alpha_rho_gradC(), preparer_calcul(), and set_div_alpha_rho_gradC().
alpha_gradC_carre
DoubleTab Convection_Diffusion_Phase_field::alpha_gradC_carre protected
Referenced by get_alpha_gradC_carre(), preparer_calcul(), and set_alpha_gradC_carre().
pression_thermo
DoubleTab Convection_Diffusion_Phase_field::pression_thermo protected
Referenced by get_pression_thermo(), and set_pression_thermo().
mutilde
DoubleTab Convection_Diffusion_Phase_field::mutilde protected
Referenced by get_mutilde(), preparer_calcul(), and set_mutilde().
c_demi
DoubleTab Convection_Diffusion_Phase_field::c_demi protected
Referenced by get_c_demi(), and set_c_demi().
mutilde_demi
DoubleTab Convection_Diffusion_Phase_field::mutilde_demi protected
Referenced by get_mutilde_demi(), and set_mutilde_demi().
mutype_
int Convection_Diffusion_Phase_field::mutype_ protected
Referenced by Convection_Diffusion_Phase_field(), get_mutype_(), and lire_motcle_non_standard().