TrioCFD: Eval_Darcy_VDF_Face Class Reference
Eval_Darcy_VDF_Face Class Reference
#include <Eval_Darcy_VDF_Face.h>
Constructor & Destructor Documentation
Eval_Darcy_VDF_Face() [1/2]
Eval_Darcy_VDF_Face::Eval_Darcy_VDF_Face () inline
Eval_Darcy_VDF_Face() [2/2]
Eval_Darcy_VDF_Face::Eval_Darcy_VDF_Face (const Eval_Darcy_VDF_Face & eval) inline
Member Function Documentation
getPorosite()
double & Eval_Darcy_VDF_Face::getPorosite () inline
References porosite_.
Referenced by Source_Darcy_VDF_Face::lire_motcle_non_standard().
calculer_terme_source()
template<typename Type_Double > void Eval_Darcy_VDF_Face::calculer_terme_source (const int num_face, Type_Double & source) const
References db_diffusivite_, Modele_Permeabilite_base::getK(), modK_, porosite_, Evaluateur_Source_Face::porosite_surf, vitesse_, and Evaluateur_Source_Face::volumes_entrelaces.
Referenced by calculer_terme_source_bord().
calculer_terme_source_bord()
template<typename Type_Double > void Eval_Darcy_VDF_Face::calculer_terme_source_bord (int num_face, Type_Double & source) const inline
References calculer_terme_source().
mettre_a_jour()
void Eval_Darcy_VDF_Face::mettre_a_jour () inline override virtual
Implements Evaluateur_Source.
References db_diffusivite_, diffusivite_, Evaluateur_Source::le_dom, and TRUST_Ref< _CLASSE_ >::valeur().
associer() [1/2]
void Eval_Darcy_VDF_Face::associer (const Champ_Don_base & diffu) inline
associe le champ de diffusivite
References db_diffusivite_, Evaluateur_Source::le_dom, TRUSTTab< _TYPE_, _SIZE_ >::resize(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Source_Darcy_VDF_Face::associer_pb().
associer() [2/2]
void Eval_Darcy_VDF_Face::associer (const Champ_Inc_base & vit) inline
References vitesse_.
Member Data Documentation
modK_
TRUST_Deriv< Modele_Permeabilite_base > Eval_Darcy_VDF_Face::modK_
Referenced by calculer_terme_source(), and Source_Darcy_VDF_Face::lire_motcle_non_standard().
vitesse_
TRUST_Ref< Champ_Inc_base *> Eval_Darcy_VDF_Face::vitesse_ protected
Referenced by associer(), and calculer_terme_source().
diffusivite_
TRUST_Ref< Champ_Don_base *> Eval_Darcy_VDF_Face::diffusivite_ protected
Referenced by mettre_a_jour().
db_diffusivite_
DoubleTab Eval_Darcy_VDF_Face::db_diffusivite_ protected
Referenced by associer(), calculer_terme_source(), and mettre_a_jour().
porosite_
double Eval_Darcy_VDF_Face::porosite_ protected
Referenced by calculer_terme_source(), and getPorosite().