TrioCFD: Senseur_Interface Class Reference
Senseur_Interface Class Reference
#include <Senseur_Interface.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Senseur_Interface()
Senseur_Interface::Senseur_Interface ()
~Senseur_Interface()
Senseur_Interface::~Senseur_Interface ()
Member Function Documentation
cree_instance()
Objet_U * Senseur_Interface::cree_instance () static
taille_memoire()
unsigned Senseur_Interface::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Senseur_Interface::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Senseur_Interface::info () static
get_info()
const Type_info * Senseur_Interface::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
Senseur_Interface & Senseur_Interface::self_cast (Objet_U & r) static
self_cast() [2/2]
const Senseur_Interface & Senseur_Interface::self_cast (const Objet_U & r) static
printOn()
Sortie & Senseur_Interface::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
readOn()
Entree & Senseur_Interface::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
References Param::ajouter(), Objet_U::dimension, equation_, equation_interface_, Process::exit(), Param::lire_avec_accolades_depuis(), nb_points_tests_, probleme_, Objet_U::que_suis_je(), Param::REQUIRED, segment_senseur_1_, segment_senseur_2_, and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
associer_pb()
virtual void Senseur_Interface::associer_pb (const Probleme_base & pb) inline virtual
References probleme_.
Referenced by Terme_Source_Constituant_Vortex_VEF_Face::readOn().
calculer_position()
int Senseur_Interface::calculer_position (ArrOfDouble & pos) const virtual
References Domaine_dis_base::domaine(), Equation_base::domaine_dis(), equation_, Transport_Interfaces_FT_Disc::get_update_distance_interface(), Transport_Interfaces_FT_Disc::get_update_normale_interface(), Transport_Interfaces_FT_Disc::inconnue(), Process::mp_min(), nb_points_tests_, TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), segment_senseur_1_, segment_senseur_2_, TRUSTArray< _TYPE_, _SIZE_ >::size_array(), TRUST_Ref< _CLASSE_ >::valeur(), and Champ_Proto::valeurs().
Referenced by Terme_Source_Constituant_Vortex_VEF_Face::mettre_a_jour().
Member Data Documentation
info_obj
const Type_info Senseur_Interface::info_obj static
equation_interface_
Nom Senseur_Interface::equation_interface_ protected
Referenced by readOn().
probleme_
TRUST_Ref< Probleme_base *> Senseur_Interface::probleme_ protected
Referenced by associer_pb(), and readOn().
equation_
TRUST_Ref< Equation_base *> Senseur_Interface::equation_ protected
Referenced by calculer_position(), and readOn().
segment_senseur_1_
ArrOfDouble Senseur_Interface::segment_senseur_1_ protected
Referenced by calculer_position(), and readOn().
segment_senseur_2_
ArrOfDouble Senseur_Interface::segment_senseur_2_ protected
Referenced by calculer_position(), and readOn().
nb_points_tests_
int Senseur_Interface::nb_points_tests_ protected
Referenced by calculer_position(), and readOn().