TrioCFD: Debog_Pb Class Reference
Debog_Pb Class Reference
#include <Debog_Pb.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
void error_function ()
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Debog_Pb() [1/2]
Debog_Pb::Debog_Pb ()
~Debog_Pb()
Debog_Pb::~Debog_Pb ()
Debog_Pb() [2/2]
Debog_Pb::Debog_Pb (const Debog_Pb &) inline protected
Member Function Documentation
cree_instance()
Objet_U * Debog_Pb::cree_instance () static
taille_memoire()
unsigned Debog_Pb::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Debog_Pb::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Debog_Pb::info () static
get_info()
const Type_info * Debog_Pb::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
Debog_Pb & Debog_Pb::self_cast (Objet_U & r) static
self_cast() [2/2]
const Debog_Pb & Debog_Pb::self_cast (const Objet_U & r) static
printOn()
Sortie & Debog_Pb::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
References Process::exit().
readOn()
Entree & Debog_Pb::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
References Param::ajouter(), debog_data_file_, detailed_log_file_, Param::dictionnaire(), Entree::ERROR_EXIT, Process::exit(), exit_on_error_, fichier_debog_, fichier_domaine_, fichier_faces_, instance_debog_, Process::je_suis_maitre(), Param::lire_avec_accolades(), log_file_, mode_db_, msg_a_ignorer_, noeuds_doubles_ignores_, nom_pb_, Interprete::objet(), Entree_Fichier_base::ouvrir(), Sortie_Fichier_base::ouvrir(), EcrFicCollecte::ouvrir(), Sortie_Fichier_base::precision(), Objet_U::que_suis_je(), read_geometry_data(), ref_pb_, Param::REQUIRED, Entree::set_error_action(), Sortie_Fichier_base::setf(), seuil_absolu_, seuil_relatif_, write_debog_data_file_, and write_geometry_data().
set_nom_pb_actuel()
void Debog_Pb::set_nom_pb_actuel (const Nom & nom)
References nom_pb_actuel_.
verifier_matrice()
void Debog_Pb::verifier_matrice (const char *const msg, const Matrice_Base & matrice, const MD_Vector & md_lignes, const MD_Vector & md_colonnes)
md_lignes: descripteur des indices de lignes (cad descripteur du vecteur b dans A*x=b) mb_colonnes: idem, indices colonnes (cad descripteur du vecteur x dans A*x=b)
References MD_Vector_tools::creer_tableau_distribue(), Process::exit(), find_renum_vector(), mode_db_, Matrice_Base::multvect(), MD_Vector_base::nb_items_seq_tot(), TRUSTVect< _TYPE_, _SIZE_ >::size_totale(), and verifier().
Referenced by verifier_Mat_elems().
verifier_Mat_elems()
void Debog_Pb::verifier_Mat_elems (const char *const msg, const Matrice_Base & la_matrice)
References Process::exit(), known_md_, renum_id_, TRUST_Vector< _CLASSE_ >::size(), and verifier_matrice().
get_debog_instance()
static TRUST_Ref< Debog_Pb * > & Debog_Pb::get_debog_instance () inline static
References instance_debog_.
Referenced by Debog::active(), Debog::set_nom_pb_actuel(), Debog::verifier(), Debog::verifier_getref(), and Debog::verifier_Mat_elems().
verifier() [1/2]
template<typename _TYPE_ > std::enable_if_t<(std::is_convertible< _TYPE_, double >::value)||(std::is_convertible< _TYPE_, int >::value), void > Debog_Pb::verifier (const char *const msg, _TYPE_ , _TYPE_ * refvalue = 0)
Referenced by verifier_matrice().
verifier() [2/2]
template<typename _TYPE_ > void Debog_Pb::verifier (const char *const msg, const TRUSTVect< _TYPE_ > & , TRUSTVect< _TYPE_ > * refvalue = 0)
test_ignore_msg()
int Debog_Pb::test_ignore_msg (const char *const msg) protected
References msg_a_ignorer_, and Motcles::rang().
goto_msg()
void Debog_Pb::goto_msg (const char *const msg) protected
References debog_data_file_, debog_msg_count_, Nom::debute_par(), detailed_log_file_, Process::exit(), Nom::finit_par(), Process::je_suis_maitre(), log_file_, mode_db_, Nom::prefix(), and Nom::suffix().
write_geometry_data()
void Debog_Pb::write_geometry_data () protected
References Domaine_VF::elem_faces(), Process::exit(), Domaine_VF::face_voisins(), fichier_domaine_, fichier_faces_, Process::is_parallel(), Domaine_VF::md_vector_aretes(), Domaine_32_64< _SIZE_ >::md_vector_elements(), Domaine_VF::md_vector_faces(), Domaine_32_64< _SIZE_ >::md_vector_sommets(), MD_Vector::non_nul(), Sortie_Fichier_base::precision(), ref_pb_, register_item(), Domaine_VF::xa(), and Domaine_VF::xv().
Referenced by readOn().
register_item()
void Debog_Pb::register_item (const MD_Vector & md, const Nom & id) protected
References TRUST_Vector< _CLASSE_ >::add(), known_md_, and renum_id_.
Referenced by add_renum_item(), and write_geometry_data().
add_renum_item()
void Debog_Pb::add_renum_item (const DoubleTab & coord_ref, const DoubleTab & coord_par, const MD_Vector & md, const Nom & id) protected
References TRUST_Vector< _CLASSE_ >::add(), Octree_Double_32_64< _SIZE_ >::build_nodes(), MD_Vector_tools::creer_tableau_distribue(), Objet_U::precision_geom, register_item(), renum_array_, and TRUST_Vector< _CLASSE_ >::size().
Referenced by read_geometry_data().
read_geometry_data()
void Debog_Pb::read_geometry_data () protected
References add_renum_item(), Elem_geom_base_32_64< _SIZE_ >::calculer_centres_gravite(), Domaine_32_64< _SIZE_ >::coord_sommets(), PE_Groups::create_group(), PE_Groups::enter_group(), Entree::ERROR_EXCEPTION, PE_Groups::exit_group(), fichier_domaine_, fichier_faces_, TRUSTVect< _TYPE_, _SIZE_ >::get_md_vector(), Process::je_suis_maitre(), Domaine_32_64< _SIZE_ >::les_elems(), Domaine_VF::md_vector_aretes(), Domaine_VF::md_vector_faces(), Entree_Fichier_base::precision(), ref_pb_, Entree::set_error_action(), TRUSTTab< _TYPE_, _SIZE_ >::set_md_vector(), Domaine_32_64< _SIZE_ >::type_elem(), TRUST_Deriv< _CLASSE_ >::valeur(), Domaine_VF::xa(), Domaine_VF::xp(), and Domaine_VF::xv().
Referenced by readOn().
find_renum_vector()
const IntVect & Debog_Pb::find_renum_vector (const MD_Vector & mdv, Nom & id) const protected
References TRUSTVect< _TYPE_, _SIZE_ >::get_md_vector(), renum_array_, renum_id_, and TRUST_Vector< _CLASSE_ >::size().
Referenced by verifier_matrice().
ecrire_partie()
template<typename _TYPE_ > void Debog_Pb::ecrire_partie (const TRUSTVect< _TYPE_ > & arr) protected
ecrire_gen()
template<typename _TYPE_ > void Debog_Pb::ecrire_gen (const char *const msg, const TRUSTVect< _TYPE_ > & arr, int num_deb = -1) protected
verifier_partie_std()
template<typename _TYPE_ > void Debog_Pb::verifier_partie_std (const TRUSTVect< _TYPE_ > & reference, const TRUSTVect< _TYPE_ > & arr, TRUSTVect< _TYPE_ > * arr_ref = 0) inline protected
verifier_partie()
template<typename _TYPE_ > void Debog_Pb::verifier_partie (const TRUSTVect< _TYPE_ > & reference, const TRUSTVect< _TYPE_ > & arr, TRUSTVect< _TYPE_ > * arr_ref = 0) inline protected
verifier_gen()
template<typename _TYPE_ > void Debog_Pb::verifier_gen (const char *const msg, const TRUSTVect< _TYPE_ > & arr, TRUSTVect< _TYPE_ > * arr_ref = 0) inline protected
error_function()
void Debog_Pb::error_function () protected
methode appelee des qu'une erreur est trouvee dans l'espace reel.
(utile pour poser un breakpoint dans gdb)
References Process::exit(), and exit_on_error_.
Member Data Documentation
info_obj
const Type_info Debog_Pb::info_obj static
debog_msg_count_
int Debog_Pb::debog_msg_count_ = 0 protected
Referenced by goto_msg().
nom_pb_
Nom Debog_Pb::nom_pb_ protected
Referenced by readOn().
ref_pb_
TRUST_Ref< Probleme_base *> Debog_Pb::ref_pb_ protected
Referenced by read_geometry_data(), readOn(), and write_geometry_data().
fichier_domaine_
Nom Debog_Pb::fichier_domaine_ protected
Referenced by read_geometry_data(), readOn(), and write_geometry_data().
fichier_faces_
Nom Debog_Pb::fichier_faces_ protected
Referenced by read_geometry_data(), readOn(), and write_geometry_data().
fichier_debog_
Nom Debog_Pb::fichier_debog_ protected
Referenced by readOn().
seuil_absolu_
double Debog_Pb::seuil_absolu_ = 1e-10 protected
Referenced by readOn().
seuil_relatif_
double Debog_Pb::seuil_relatif_ = 1e-10 protected
Referenced by readOn().
noeuds_doubles_ignores_
int Debog_Pb::noeuds_doubles_ignores_ = 0 protected
Referenced by readOn().
msg_a_ignorer_
Motcles Debog_Pb::msg_a_ignorer_ protected
Referenced by readOn(), and test_ignore_msg().
mode_db_
int Debog_Pb::mode_db_ = 0 protected
Referenced by goto_msg(), readOn(), and verifier_matrice().
exit_on_error_
int Debog_Pb::exit_on_error_ = 0 protected
Referenced by error_function(), and readOn().
known_md_
TRUST_Vector< MD_Vector > Debog_Pb::known_md_ protected
Referenced by register_item(), and verifier_Mat_elems().
renum_id_
Noms Debog_Pb::renum_id_ protected
Referenced by find_renum_vector(), register_item(), and verifier_Mat_elems().
renum_array_
IntVects Debog_Pb::renum_array_ protected
Referenced by add_renum_item(), and find_renum_vector().
write_debog_data_file_
SFichier Debog_Pb::write_debog_data_file_ protected
Referenced by readOn().
debog_data_file_
EFichier Debog_Pb::debog_data_file_ protected
Referenced by goto_msg(), and readOn().
log_file_
SFichier Debog_Pb::log_file_ protected
Referenced by goto_msg(), and readOn().
detailed_log_file_
EcrFicCollecte Debog_Pb::detailed_log_file_ protected
Referenced by goto_msg(), and readOn().
nom_pb_actuel_
Nom Debog_Pb::nom_pb_actuel_ protected
Referenced by set_nom_pb_actuel().
instance_debog_
TRUST_Ref< Debog_Pb * > Debog_Pb::instance_debog_ static protected
Referenced by get_debog_instance(), and readOn().