TrioCFD: TRUST_Vector< _CLASSE_ > Class Template Reference
TRUST_Vector< _CLASSE_ > Class Template Reference
#include <TRUST_Vector.h>
Protected Member Functions
Sortie & printOn (Sortie &s) const override
Entree & readOn (Entree &s) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
template<typename _CLASSE_>
class TRUST_Vector< _CLASSE_ >
La classe template TRUST_Vector est utilisable pour n'importe quelle classe
Utilisation (par exemple):
TRUST_Vector<MD_Vector>
TRUST_Vector<Milieu_base>
TRUST_Vector<TRUSTArray<double>>
Constructor & Destructor Documentation
~TRUST_Vector()
template<typename _CLASSE_ > TRUST_Vector< _CLASSE_ >::~TRUST_Vector () inline
TRUST_Vector() [1/3]
template<typename _CLASSE_ > TRUST_Vector< _CLASSE_ >::TRUST_Vector () default
TRUST_Vector() [2/3]
template<typename _CLASSE_ > TRUST_Vector< _CLASSE_ >::TRUST_Vector (int i) inline explicit
References TRUST_Vector< _CLASSE_ >::dimensionner_force().
TRUST_Vector() [3/3]
template<typename _CLASSE_ > TRUST_Vector< _CLASSE_ >::TRUST_Vector (const TRUST_Vector< _CLASSE_ > & avect) inline
References TRUST_Vector< _CLASSE_ >::clear(), and TRUST_Vector< _CLASSE_ >::size().
Member Function Documentation
taille_memoire()
template<typename _CLASSE_ > unsigned TRUST_Vector< _CLASSE_ >::taille_memoire () const inline override protected virtual
Implements Objet_U.
duplique()
template<typename _CLASSE_ > int TRUST_Vector< _CLASSE_ >::duplique () const inline override protected virtual
Implements Objet_U.
printOn()
template<typename _CLASSE_ > Sortie & TRUST_Vector< _CLASSE_ >::printOn (Sortie & s) const inline override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
readOn()
template<typename _CLASSE_ > Entree & TRUST_Vector< _CLASSE_ >::readOn (Entree & s) inline override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
get_stl_vect() [1/2]
template<typename _CLASSE_ > const STLVect & TRUST_Vector< _CLASSE_ >::get_stl_vect () const inline
Referenced by TRUST_Vector< _CLASSE_ >::add().
get_stl_vect() [2/2]
template<typename _CLASSE_ > STLVect & TRUST_Vector< _CLASSE_ >::get_stl_vect () inline
begin() [1/2]
template<typename _CLASSE_ > IteratorWrapper TRUST_Vector< _CLASSE_ >::begin () inline
end() [1/2]
template<typename _CLASSE_ > IteratorWrapper TRUST_Vector< _CLASSE_ >::end () inline
begin() [2/2]
template<typename _CLASSE_ > const ConstIteratorWrapper TRUST_Vector< _CLASSE_ >::begin () const inline
end() [2/2]
template<typename _CLASSE_ > const ConstIteratorWrapper TRUST_Vector< _CLASSE_ >::end () const inline
operator[]() [1/2]
template<typename _CLASSE_ > const value_type & TRUST_Vector< _CLASSE_ >::operator[] (int i) const inline
operator[]() [2/2]
template<typename _CLASSE_ > value_type & TRUST_Vector< _CLASSE_ >::operator[] (int i) inline
operator()() [1/2]
template<typename _CLASSE_ > const value_type & TRUST_Vector< _CLASSE_ >::operator() (int i) const delete
operator()() [2/2]
template<typename _CLASSE_ > value_type & TRUST_Vector< _CLASSE_ >::operator() (int i) delete
add() [1/4]
template<typename _CLASSE_ > value_type & TRUST_Vector< _CLASSE_ >::add () delete
Referenced by Objet_a_lire::add_dict(), MD_Vector_composite::add_part(), Debog_Pb::add_renum_item(), Field_base::add_synonymous(), Interprete_bloc::ajouter(), Champ_Generique_Transformation::completer(), Chimie::completer(), Corriger_frontiere_periodique_32_64< _SIZE_ >::corriger_coordonnees_sommets_perio(), Champ_Fonc_MED::creer(), Champ_Gen_de_Champs_Gen::creer_espace_stockage(), Champ_Generique_Morceau_Equation::creer_espace_stockage(), Probleme_base::discretiser(), Discretisation_base::discretiser_champ(), Format_Post_Lata::ecrire_champ(), Format_Post_Lata::ecrire_domaine_low_level(), Format_Post_CGNS::ecrire_entete(), Champ_Generique_Tparoi_VEF::get_champ(), Champ_Generique_Tparoi_VEF::get_champ_without_evaluation(), Sondes::get_from_cache(), Sonde_IJK::get_noms_champ(), Chimie::get_noms_champs_postraitables(), Transport_Marqueur_FT::get_noms_champs_postraitables(), Navier_Stokes_Aposteriori::get_noms_champs_postraitables(), Source_Transport_K_Omega_VEF_Face::get_noms_champs_postraitables(), Modele_Fonc_Bas_Reynolds_Base::get_noms_champs_postraitables(), Modele_Fonc_Bas_Reynolds_Thermique_Base::get_noms_champs_postraitables(), Modele_Fonc_Realisable_base::get_noms_champs_postraitables(), Source_PDF_EF::get_noms_champs_postraitables(), Puissance_Thermique_QC_EF::get_noms_champs_postraitables(), Domaine_dis_base::get_noms_champs_postraitables(), Equation_base::get_noms_champs_postraitables(), Loi_Fermeture_base::get_noms_champs_postraitables(), Milieu_base::get_noms_champs_postraitables(), Operateur_base::get_noms_champs_postraitables(), Source_base::get_noms_champs_postraitables(), Pb_MED::get_noms_champs_postraitables(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::get_noms_champs_postraitables(), Loi_Etat_base::get_noms_champs_postraitables(), Convection_Diffusion_Temperature::get_noms_champs_postraitables(), Convection_Diffusion_Temperature_base::get_noms_champs_postraitables(), Navier_Stokes_std::get_noms_champs_postraitables(), Marqueur_Lagrange_base::get_noms_champs_postraitables(), Traitement_particulier_NS_base::get_noms_champs_postraitables(), QDM_Multiphase::get_noms_champs_postraitables(), Turbulence_paroi_base::get_noms_champs_postraitables(), Turbulence_paroi_scal_base::get_noms_champs_postraitables(), Modele_turbulence_hyd_base::get_noms_champs_postraitables(), Modele_turbulence_scal_base::get_noms_champs_postraitables(), Conduction::get_noms_champs_postraitables(), Traitement_particulier_Solide_base::get_noms_champs_postraitables(), Op_Conv_VDF_base::get_noms_champs_postraitables(), Probleme_FTD_IJK_base::get_noms_champs_postraitables(), IJK_Thermal_base::get_noms_champs_postraitables(), Postprocessing_IJK::get_noms_champs_postraitables(), Statistiques_dns_ijk::get_noms_champs_postraitables(), IJK_Ghost_Fluid_Fields::get_noms_champs_postraitables(), IJK_Interfaces::get_noms_champs_postraitables(), Navier_Stokes_FTD_IJK::get_noms_champs_postraitables(), Op_Dift_Multiphase_proto::get_noms_champs_postraitables_proto(), Champ_Generique_refChamp::get_property_names(), Probleme_base_interface_proto::getInputFieldsNames_impl(), Probleme_base_interface_proto::getOutputFieldsNames_impl(), Postraitement::init(), Transport_Interfaces_FT_Disc::lire_maillage_ft_cao(), Collision_Model_FT_base::lire_motcle_non_standard(), Post_Processing_Hydrodynamic_Forces::lire_motcle_non_standard(), Navier_Stokes_FT_Disc::lire_motcle_non_standard(), Transport_Interfaces_FT_Disc::lire_motcle_non_standard(), Create_domain_from_sub_domain::lire_motcle_non_standard(), Convection_Diffusion_Temperature::lire_motcle_non_standard(), Probleme_FT_Disc_gen::lire_solved_equations(), Probleme_FTD_IJK_base::lire_solved_equations(), Champs_compris_T< FIELD_TYPE >::liste_noms_compris(), Champs_compris_IJK::liste_noms_compris(), Champs_compris_IJK::liste_noms_compris_vectoriel(), Champ_Fonc_Tabule_P0_EF::mettre_a_jour(), Champ_Fonc_Tabule_Elem_PolyMAC::mettre_a_jour(), Champ_Fonc_Tabule_P0_VDF::mettre_a_jour(), Champ_Fonc_Tabule_P0_VEF::mettre_a_jour(), Postraitement_ft_lata::postprocess_field_values(), DNS_QC_double::posttraiter_champs_instantanes(), IJK_Interfaces::posttraiter_tous_champs(), IJK_One_Dimensional_Subproblems_Interfaces_Fields::posttraiter_tous_champs(), Postprocessing_IJK::posttraiter_tous_champs_energie(), IJK_Thermal_base::posttraiter_tous_champs_thermal(), Postprocessing_IJK::posttraiter_tous_champs_thermique(), Domaine_ALE::read_beam(), Probleme_base::read_optional_equations(), Domaine_ALE::reading_ALE_Neumann_BC_for_grid_problem(), Domaine_ALE::reading_projection_ALE_boundary(), Champ_Fonc_Fonction::readOn(), Champ_Fonc_Fonction_txyz::readOn(), Champ_Fonc_Tabule::readOn(), Champ_Fonc_Tabule_Morceaux::readOn(), MD_Vector_composite::readOn(), DP_Impose_PolyMAC_Face::readOn(), Perte_Charge_Singuliere_PolyMAC_Face::readOn(), Terme_Puissance_Thermique_Echange_Impose_Elem_base::readOn(), Milieu_composite::readOn(), Milieu_MUSIG::readOn(), DP_Impose_VEF_Face::readOn(), Postraitement_ft_lata::register_interface_field(), Debog_Pb::register_item(), DNS_QC_double::save_raw_data(), and Moyenne_volumique::traiter_champs().
size()
template<typename _CLASSE_ > int TRUST_Vector< _CLASSE_ >::size () const inline
Referenced by TRUST_Vector< _CLASSE_ >::add(), MD_Vector_composite::add_part(), Debog_Pb::add_renum_item(), Champs_compris_T< FIELD_TYPE >::ajoute_champ(), Champs_compris_IJK::ajoute_champ_vectoriel(), Op_Diff_PolyMAC_Elem::ajouter(), Op_Grad_VEF_P1B_Face::ajouter_aretes(), Op_Grad_VEF_P1B_Face::ajouter_elem(), Op_Grad_VEF_P1B_Face::ajouter_som(), Op_Div_VEFP1B_Elem::ajouter_som(), Op_Diff_PolyMAC_Elem::ajouter_termes_croises(), LoiParoiHybride::associer(), Champ_P1NC::calcul_duidxj_paroi(), Traitement_particulier_NS_THI_VEF::calcul_Ec_spatial(), Modele_EASM_Baglietto_VEF::Calcul_F1(), Modele_EASM_Baglietto_VEF::Calcul_F1_BiK(), Couplage_Tubes_IBC::calcul_F_pression(), Couplage_Tubes_IBC::calcul_F_pression2(), Modele_EASM_Baglietto_VEF::Calcul_Fmu(), Modele_EASM_Baglietto_VEF::Calcul_Fmu_BiK(), Traitement_particulier_NS_THI_VEF::calcul_moyenne(), Modele_Lam_Bremhorst_VEF::calcul_tenseur_face(), Modele_Shih_Zhu_Lumley_VEF::calcul_tenseur_face(), Calcul_Production_K_VEF::calcul_tenseur_face(), Traitement_particulier_NS_THI_VEF::calcul_vitesse_moyenne(), Op_Conv_ALE_VEF::calculateALEMeshVelocityGradientOnFaces(), Op_Dift_VEF_P1NCP1B_Face::calculer_divergence_som(), Op_Diff_VEFP1NCP1B_Face::calculer_divergence_som(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab_elem(), Scatter::calculer_espace_distant(), Modele_rayo_semi_transp::calculer_flux_radiatif(), Flux_radiatif_VDF::calculer_flux_radiatif(), Flux_radiatif_VEF::calculer_flux_radiatif(), Modele_turbulence_hyd_LES_VEF::calculer_fonction_structure(), Op_Dift_VEF_P1NCP1B_Face::calculer_gradient_som(), Op_Diff_VEFP1NCP1B_Face::calculer_gradient_som(), LoiParoiHybride::calculer_hyd(), LoiParoiHybride::calculer_hyd_BiK(), Op_Diff_VEF_Face_Stab::calculer_max(), Op_Diff_VEF_Face_Stab::calculer_min(), Modele_turbulence_hyd_LES_VEF::calculer_viscosite_turbulente(), Operateur_base::completer(), Modele_turbulence_hyd_combinaison::completer(), Convection_Diffusion_Espece_Multi_QC::completer(), Op_Diff_VEF_Face_Stab::completer(), Op_Dift_Stab_VEF_Face::completer(), Champ_P1iP1B_implementation::completer(), Reaction::completer(), Champ_Generique_Transformation::completer(), Op_Correlation::completer(), Chimie::completer(), Champ_Generique_base::composante(), Pb_MED::comprend_champ(), Domain_Graph::construire_graph_elem_elem(), Partitionneur_Fichier_Decoupage::construire_partition(), Partitionneur_Sous_Domaines::construire_partition(), Scatter::construire_structures_paralleles(), Op_Diff_PolyMAC_Elem::contribuer_a_avec(), Op_Diff_PolyMAC_Elem::contribuer_termes_croises(), Partitionneur_base_32_64< _SIZE_ >::corriger_bords_avec_graphe(), Op_Diff_VEFP1NCP1B_Face::corriger_Cl_test(), Op_Diff_VEFP1NCP1B_Face::corriger_div_pour_Cl(), Op_Dift_VEF_P1NCP1B_Face::corriger_div_pour_Cl(), Champ_base::corriger_unite_nom_compo(), Champ_Fonc_MED::creer(), Pb_MED::creer_champ(), Postraitement::creer_champ_post(), Postraitement::creer_champ_post_stat(), Op_PolyMAC_Elem::dimensionner(), Op_Diff_PolyMAC_Elem::dimensionner_termes_croises(), Op_Diff_VDF_Elem_base::dimensionner_termes_croises(), Domaine_Poly_base::dist_norm_bord(), Domaine_VDF::dist_norm_bord(), Format_Post_Med::ecrire_champ_med(), Turbulence_paroi_scal_base::equivalent_distance(), Parser_Eval::eval_fct(), Eq_rayo_semi_transp_VDF::evaluer_cl_rayonnement(), Eq_rayo_semi_transp_VEF::evaluer_cl_rayonnement(), Reaction::extract_coef(), Champ_P1NC_implementation::filtrer_L2(), Debog_Pb::find_renum_vector(), Modele_rayo_semi_transp::flux_radiatif(), Couplage_Tubes_IBC::force_ibc_velocity(), Couplage_Tubes_IBC::force_ibc_velocity_anticipe_cube(), Couplage_Tubes_IBC::force_ibc_velocity_frac_vol(), Couplage_Tubes_IBC::force_ibc_velocity_miroir(), Couplage_Tubes_IBC::force_ibc_velocity_symetrie_plane(), Champ_Generique_Transformation::get_champ(), Champ_Generique_base::get_champ_post(), Champ_Generique_Correlation::get_info_type_post(), Sonde::get_nb_compo_champ(), Champ_Generique_Ecart_Type::get_property(), Champ_Generique_Extraction::get_property(), Champ_Generique_Interpolation::get_property(), Champ_Generique_Moyenne::get_property(), Champ_Generique_Reduction_0D::get_property(), Champ_Generique_refChamp::get_property(), Champ_Generique_Tparoi_VEF::get_property(), MD_Vector_composite::get_seq_flags_impl(), Champ_Generique_base::has_champ_post(), Couplage_Tubes_IBC::ibc0_force_cube(), Couplage_Tubes_IBC::ibc0_velocity_cube(), Couplage_Tubes_IBC::ibc_diffuse_force_cube(), Couplage_Tubes_IBC::ibc_diffuse_velocity_cube(), Couplage_Tubes_IBC::ibc_localisee_velocity_cube(), Couplage_Tubes_IBC::ibc_localisee_velocity_cube_qdm(), Postraitement::init(), Domaine_VF::init_dist_paroi_globale(), Champ_Inc_P0_base::init_fcl(), Champ_Face_base::init_fcl(), LoiParoiHybride::init_lois_paroi(), Paroi_negligeable_VEF::init_lois_paroi(), Couplage_Parietal_PolyMAC_helper::init_op_ext(), Op_Diff_PolyMAC_P0P1NC_Elem::init_op_ext(), DNS_QC_double::initialise(), Navier_Stokes_FTD_IJK::initialise_velocity_using_expression(), Domaine_Cl_VEF::initialiser(), Domaine_ALE::initialiser(), Couplage_Tubes_IBC::initialize(), IJK_Thermal_base::initialize(), Moyenne_volumique::interpreter(), Execute_parallel::interpreter(), Lata_2_Other::interpreter(), Create_domain_from_sub_domain::interpreter_(), DecoupeBord_32_64< _SIZE_ >::interpreter_(), Extraire_plan::interpreter_(), Extruder_en3::interpreter_(), Domaine_Cl_dis_base::la_cl_de_la_face(), Domaine_ALE::laplacien(), LoiParoiHybride::lire(), Postraitement::lire_champs_a_postraiter(), Modele_turbulence_hyd_Longueur_Melange_VEF::lire_distance_paroi(), Modele_Lam_Bremhorst_VEF::lire_distance_paroi(), Navier_Stokes_FT_Disc::lire_motcle_non_standard(), Operateur_IJK_faces_conv::lire_motcle_non_standard(), Operateur_IJK_faces_diff::lire_motcle_non_standard(), Postraitement::lire_tableaux_a_postraiter(), AssembleurPVDF_PF::liste_faces_periodiques(), Assembleur_P_VDF::liste_faces_periodiques(), Champ_Fonc_t::me_calculer(), Chimie::mettre_a_jour(), Convection_Diffusion_Concentration_FT_Disc::mettre_a_jour(), Convection_Diffusion_Concentration_Turbulent_FT_Disc::mettre_a_jour(), Transport_Interfaces_FT_Disc::mettre_a_jour(), Champ_Fonc_Tabule_P0_EF::mettre_a_jour(), Champ_Fonc_Tabule_Elem_PolyMAC::mettre_a_jour(), Champ_Fonc_Tabule_P0_VDF::mettre_a_jour(), Champ_Fonc_Tabule_P0_VEF::mettre_a_jour(), Convection_Diffusion_Concentration_FT_Disc::mettre_a_jour_chimie(), Convection_Diffusion_Concentration_Turbulent_FT_Disc::mettre_a_jour_chimie(), Op_Diff_VEF_Face_Stab::modifie_pour_Cl(), Terme_Source_Th_TdivU_VEF_Face::modifier_domaine_cl(), Op_Grad_VEF_P1B_Face::modifier_grad_pour_Cl(), Eq_rayo_semi_transp_VDF::modifier_matrice(), Eq_rayo_semi_transp_VEF::modifier_matrice(), Assembleur_P_VEFPreP1B::modifier_matrice(), Domaine_Poly_base::modifier_pour_Cl(), Domaine_PolyMAC::modifier_pour_Cl(), Domaine_VDF::modifier_pour_Cl(), Op_Diff_K_Eps_VDF_base::modifier_pour_Cl(), Op_Diff_K_Omega_VDF_base::modifier_pour_Cl(), Domaine_Cl_DG::nb_bord_periodicite(), Domaine_Cl_PolyMAC::nb_bord_periodicite(), Domaine_Cl_dis_base::nb_cond_lim(), Domaine_VF::nb_frontiere_dis(), Multigrille_Adrien::nb_grid_levels(), MD_Vector_composite::nb_parts(), Pb_Multiphase::nb_phases(), Domaine_dis_base::nombre_de_sous_domaines_dis(), Discretisation_base::nommer_completer_champ_physique(), TRUST_Vector< _CLASSE_ >::operator=(), Operateur_base::ouvrir_fichier(), Source_base::ouvrir_fichier(), Convection_Diffusion_Temperature::penalisation_L2(), IJK_Thermal_base::post_process_std_thermal_field(), Postraitement_ft_lata::postprocess_field_values(), Sonde::postraiter(), Postraitement::postraiter_tenseur(), DNS_QC_double::posttraiter_champs_instantanes(), Convection_Diffusion_Espece_Fluide_Dilatable_base::preparer_calcul(), Traitement_particulier_NS_CEG::preparer_calcul_particulier(), Champ_Generique_Transformation::preparer_macro(), Objet_a_lire::print(), MD_Vector_composite::printOn(), Objet_a_lire::read(), Domaine_ALE::read_beam(), Domaine_ALE::reading_ALE_Neumann_BC_for_grid_problem(), Maillage_FT_Disc::readOn(), Convection_Diffusion_Concentration_FT_Disc::readOn(), Convection_Diffusion_Concentration_Turbulent_FT_Disc::readOn(), Champ_Fonc_Tabule::readOn(), Sonde_Int::readOn(), Cond_Lim_rayo_semi_transp::recherche_emissivite_et_A(), Table::remplir(), Assembleur_P_VEF::remplir(), AssembleurPVDF_PF::remplir(), Assembleur_P_VDF::remplir(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::remplir_cl_modifiee(), Champ_front_contact_VEF::remplir_faces_coin(), Domaine_Cl_EF::remplir_type_elem_Cl(), Domaine_Cl_VEF::remplir_type_elem_Cl(), Domaine_Cl_VEF::remplir_volumes_entrelaces_Cl(), DNS_QC_double::run(), Couplage_Tubes_IBC::sauvegarder_pression(), DNS_QC_double::save_raw_data(), Static_Int_Lists_32_64< _SIZE_ >::set(), Operateur_IJK_faces_conv::set_convection_option_type(), Sondes::set_noms_champs_postraitables(), TRUSTTab_parts< _TYPE_ >::size(), ConstTRUSTTab_parts< _TYPE_ >::size(), Probleme_Couple::solveTimeStep(), Turbulence_paroi_scal_base::tab_equivalent_distance(), Turbulence_paroi_scal_base::tab_equivalent_distance_size(), Op_Diff_VEFP1NCP1B_Face::test(), Champ_front_contact_VEF::test_faces_coin(), Moyenne_volumique::traiter_champs(), TRUST_Vector< _CLASSE_ >::TRUST_Vector(), Field_base::unite(), Domaine_ALE::update_ALE_projection(), Domaine_ALE::update_coord_dom_extrait_surface(), Op_Diff_PolyMAC_Elem::update_delta(), Op_Diff_PolyMAC_base::update_nu(), Table::val(), Table::val_simple(), Table::valeurs(), Transport_Interfaces_FT_Disc::verif_Cl(), Postraitement::verifie_nom_et_sources(), Champ_Generique_Transformation::verifier_coherence_donnees(), Assembleur_P_VEFPreP1B::verifier_dirichlet(), Debog_Pb::verifier_Mat_elems(), and Ecrire_fichier_xyz_valeur::write_fields().
reset()
template<typename _CLASSE_ > void TRUST_Vector< _CLASSE_ >::reset () inline
Referenced by Sondes::clear_cache(), Probleme_FTD_IJK_base::get_noms_champs_postraitables(), and Create_domain_from_sub_domain::lire_motcle_non_standard().
clear()
template<typename _CLASSE_ > void TRUST_Vector< _CLASSE_ >::clear () inline
Referenced by Postraitement::finir(), TRUST_Vector< _CLASSE_ >::operator=(), and TRUST_Vector< _CLASSE_ >::TRUST_Vector().
resize()
template<typename _CLASSE_ > void TRUST_Vector< _CLASSE_ >::resize (int i) inline
References TRUST_Vector< _CLASSE_ >::dimensionner().
Referenced by IJK_Thermal_Subresolution::compute_md_vector(), Octree_32_64< _SIZE_ >::construire(), Domaine_VF::init_dist_paroi_globale(), Paroi_scal_hyd_base_VDF::init_lois_paroi(), Raccord_distant_homogene_32_64< _SIZE_ >::initialise(), and Champ_front_recyclage::mettre_a_jour().
back()
template<typename _CLASSE_ > value_type & TRUST_Vector< _CLASSE_ >::back () inline
front()
template<typename _CLASSE_ > value_type & TRUST_Vector< _CLASSE_ >::front () inline
dimensionner()
template<typename _CLASSE_ > void TRUST_Vector< _CLASSE_ >::dimensionner (int i) inline
Referenced by Probleme_Couple::associer_sch_tps_base(), Refine_Mesh::build_new_boundary_faces_2D(), Refine_Mesh::build_new_boundary_faces_3D(), Refine_Mesh::build_new_connector_faces_2D(), Refine_Mesh::build_new_connector_faces_3D(), Refine_Mesh::build_new_internal_frontier_faces_2D(), Refine_Mesh::build_new_internal_frontier_faces_3D(), Refine_Mesh::build_new_sub_domaines_descriptions(), Modele_turbulence_hyd_combinaison::completer(), Champ_Generique_Transformation::completer(), Op_Correlation::completer(), Chimie::completer(), Multigrille_Adrien::completer_double_for_residue(), Matrice_Bloc::dimensionner(), Matrice_Bloc_Sym::dimensionner(), Domaine_dis_base::discretiser_root(), Field_base::fixer_nb_comp(), Matrice_Morse::imprimer_formatte(), Matrice_Morse::imprimer_image(), ParoiVDF_TBLE_LRM::init_lois_paroi(), Paroi_ODVM_scal_VDF::init_lois_paroi(), Paroi_scal_hyd_base_EF::init_lois_paroi(), Paroi_scal_hyd_base_VDF::init_lois_paroi(), Paroi_scal_hyd_base_VEF::init_lois_paroi(), Paroi_TBLE_QDM::init_lois_paroi(), Paroi_TBLE_QDM_Scal::init_lois_paroi(), Postprocessing_IJK::initialise_stats(), Sonde::initialiser(), Champ_front_recyclage::initialiser_moyenne_imposee(), DNS_QC_double::interpreter(), Create_domain_from_sub_domain::interpreter_(), Rotation::interpreter_(), Transformer_32_64< _SIZE_ >::interpreter_(), LoiParoiHybride::lire(), Paroi_TBLE_QDM_Scal::lire_donnees(), Modele_Rayonnement_Milieu_Transparent::lire_fichiers(), Champ_front_recyclage::lire_info_moyenne_imposee(), Paroi_TBLE_QDM::lire_motcle_non_standard(), Champ_Generique_Transformation::lire_motcle_non_standard(), PDF_model::lire_motcle_non_standard(), Terme_Boussinesq_base::lire_motcle_non_standard(), Modele_turbulence_hyd_combinaison::Modele_turbulence_hyd_combinaison(), Postprocessing_IJK::Postprocessing_IJK(), Champ_Generique_Transformation::preparer_macro(), Domaine_ALE::reading_projection_ALE_boundary(), Domaine_ALE::reading_vit_bords_ALE(), Champ_front_ALE::readOn(), Champ_front_ALE_projection::readOn(), Maillage_FT_Disc::readOn(), Tube_impose::readOn(), Face_Rayonnante::readOn(), ParoiVDF_TBLE_LRM::readOn(), Source_Robin_Scalaire::readOn(), Champ_front_t::readOn(), Champ_front_txyz::readOn(), Champ_Fonc_t::readOn(), Domaine_Cl_dis_base::readOn(), Matrice_Bloc::readOn(), Champ_front_softanalytique::readOn(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::readOn(), QDM_Multiphase::readOn(), Champ_front_debit_QC_fonc_t::readOn(), Op_Conv_VDF_base::readOn(), Op_Conv_EF_VEF_P1NC_Stab::readOn(), Table::remplir(), TRUST_Vector< _CLASSE_ >::resize(), Statistiques_dns_ijk::Statistiques_dns_ijk(), Eval_Dift_VDF::update_equivalent_distance(), and Champ_Generique_Transformation::verifier_coherence_donnees().
dimensionner_force()
template<typename _CLASSE_ > void TRUST_Vector< _CLASSE_ >::dimensionner_force (int i) inline
Referenced by IJK_Interfaces::compute_external_forces_parser(), Champ_base::corriger_unite_nom_compo(), Field_base::fixer_nom_compo(), Field_base::fixer_unite(), Field_base::fixer_unites(), Postprocessing_IJK::improved_initial_pressure_guess(), Navier_Stokes_FTD_IJK::Navier_Stokes_FTD_IJK(), DNS_QC_double::posttraiter_champs_instantanes(), TRUSTTab_parts< _TYPE_ >::reset(), ConstTRUSTTab_parts< _TYPE_ >::reset(), DNS_QC_double::save_raw_data(), Sondes::set_noms_champs_postraitables(), Postprocessing_IJK::set_param(), Parser::setNbVar(), Statistiques_dns_ijk_FT::Statistiques_dns_ijk_FT(), Statistiques_dns_ijk_monophasique::Statistiques_dns_ijk_monophasique(), and TRUST_Vector< _CLASSE_ >::TRUST_Vector().
lit()
template<typename _CLASSE_ > Entree & TRUST_Vector< _CLASSE_ >::lit (Entree & s) inline
operator=()
template<typename _CLASSE_ > TRUST_Vector & TRUST_Vector< _CLASSE_ >::operator= (const TRUST_Vector< _CLASSE_ > & avect) inline
References TRUST_Vector< _CLASSE_ >::clear(), and TRUST_Vector< _CLASSE_ >::size().
add() [2/4]
template<typename _CLASSE_ > value_type & TRUST_Vector< _CLASSE_ >::add (value_type && data_to_add) inline
add() [3/4]
template<typename _CLASSE_ > value_type & TRUST_Vector< _CLASSE_ >::add (const value_type & data_to_add) inline
add() [4/4]
template<typename _CLASSE_ > void TRUST_Vector< _CLASSE_ >::add (const TRUST_Vector< _CLASSE_ > & v2) inline
References TRUST_Vector< _CLASSE_ >::get_stl_vect(), and TRUST_Vector< _CLASSE_ >::size().