TrioCFD: OpGradQuickIJKScalar_double Class Reference
OpGradQuickIJKScalar_double Class Reference
#include <OpGradQuickIJKScalar.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
~OpGradQuickIJKScalar_double()
OpGradQuickIJKScalar_double::~OpGradQuickIJKScalar_double ()
OpGradQuickIJKScalar_double()
OpGradQuickIJKScalar_double::OpGradQuickIJKScalar_double () inline
References Operateur_IJK_elem_conv_base_double::is_grad_.
Member Function Documentation
cree_instance()
Objet_U * OpGradQuickIJKScalar_double::cree_instance () static
taille_memoire()
unsigned OpGradQuickIJKScalar_double::taille_memoire () const override virtual
Reimplemented from OpConvQuickIJKScalar_double.
Reimplemented in OpGradFluxQuickIJKScalar_double.
duplique()
int OpGradQuickIJKScalar_double::duplique () const override virtual
Reimplemented from OpConvQuickIJKScalar_double.
Reimplemented in OpGradFluxQuickIJKScalar_double.
info()
const Type_info * OpGradQuickIJKScalar_double::info () static
get_info()
const Type_info * OpGradQuickIJKScalar_double::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from OpConvQuickIJKScalar_double.
Reimplemented in OpGradFluxQuickIJKScalar_double.
self_cast() [1/2]
OpGradQuickIJKScalar_double & OpGradQuickIJKScalar_double::self_cast (Objet_U & r) static
self_cast() [2/2]
const OpGradQuickIJKScalar_double & OpGradQuickIJKScalar_double::self_cast (const Objet_U & r) static
printOn()
Sortie & OpGradQuickIJKScalar_double::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from OpConvQuickIJKScalar_double.
Reimplemented in OpGradFluxQuickIJKScalar_double.
References Objet_U::printOn().
readOn()
Entree & OpGradQuickIJKScalar_double::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from OpConvQuickIJKScalar_double.
Reimplemented in OpGradFluxQuickIJKScalar_double.
References Objet_U::readOn().
calculer_grad()
void OpGradQuickIJKScalar_double::calculer_grad (const IJK_Field_double & field, IJK_Field_vector3_double & result)
References IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::allocate(), Operateur_IJK_elem_base_double::compute_grad(), Operateur_IJK_elem_conv_base_double::input_field_, Operateur_IJK_elem_conv_base_double::input_velocity_x_, Operateur_IJK_elem_conv_base_double::input_velocity_y_, Operateur_IJK_elem_conv_base_double::input_velocity_z_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), and Operateur_IJK_elem_conv_base_double::tmp_curv_fram_.
Referenced by OpGradFluxQuickIJKScalar_double::calculer_grad_flux().
calculer_grad_x()
void OpGradQuickIJKScalar_double::calculer_grad_x (const IJK_Field_double & field, IJK_Field_double & result)
References IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::allocate(), Operateur_IJK_elem_base_double::compute_grad_x(), Operateur_IJK_elem_conv_base_double::input_field_, Operateur_IJK_elem_conv_base_double::input_velocity_x_, Operateur_IJK_elem_conv_base_double::input_velocity_y_, Operateur_IJK_elem_conv_base_double::input_velocity_z_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), and Operateur_IJK_elem_conv_base_double::tmp_curv_fram_.
calculer_grad_y()
void OpGradQuickIJKScalar_double::calculer_grad_y (const IJK_Field_double & field, IJK_Field_double & result)
References IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::allocate(), Operateur_IJK_elem_base_double::compute_grad_y(), Operateur_IJK_elem_conv_base_double::input_field_, Operateur_IJK_elem_conv_base_double::input_velocity_x_, Operateur_IJK_elem_conv_base_double::input_velocity_y_, Operateur_IJK_elem_conv_base_double::input_velocity_z_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), and Operateur_IJK_elem_conv_base_double::tmp_curv_fram_.
calculer_grad_z()
void OpGradQuickIJKScalar_double::calculer_grad_z (const IJK_Field_double & field, IJK_Field_double & result)
References IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::allocate(), Operateur_IJK_elem_base_double::compute_grad_z(), Operateur_IJK_elem_conv_base_double::input_field_, Operateur_IJK_elem_conv_base_double::input_velocity_x_, Operateur_IJK_elem_conv_base_double::input_velocity_y_, Operateur_IJK_elem_conv_base_double::input_velocity_z_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), and Operateur_IJK_elem_conv_base_double::tmp_curv_fram_.
fill_grad_field_x_y_()
void OpGradQuickIJKScalar_double::fill_grad_field_x_y_ (IJK_Field_local_double & flux, IJK_Field_double & resu, int k, int dir) override protected virtual
Reimplemented from Operateur_IJK_elem_base_double.
Reimplemented in OpGradFluxQuickIJKScalar_double.
References IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), and IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj().
fill_grad_field_z_()
void OpGradQuickIJKScalar_double::fill_grad_field_z_ (IJK_Field_local_double & flux_min, IJK_Field_local_double & flux_max, IJK_Field_double & resu, int k) override protected virtual
Reimplemented from Operateur_IJK_elem_base_double.
Reimplemented in OpGradFluxQuickIJKScalar_double.
References Operateur_IJK_elem_conv_base_double::channel_data_, Operateur_IJK_data_channel::get_delta_z(), Operateur_IJK_elem_conv_base_double::is_flux_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), and IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj().
Member Data Documentation
info_obj
const Type_info OpGradQuickIJKScalar_double::info_obj static