TrioCFD: EcrFicCollecte Class Reference
EcrFicCollecte Class Reference
#include <EcrFicCollecte.h>
Public Member Functions
EcrFicCollecte (const char *name, std::ios_base::openmode mode=ios::out)
const Type_info * get_info () const override
int ouvrir (const char *name, std::ios_base::openmode mode=ios::out) override
Public Member Functions inherited from SFichier
const Type_info * get_info () const override
Public Member Functions inherited from Sortie_Fichier_base
Sortie & flush () override
const Type_info * get_info () const override
Public Member Functions inherited from Sortie
virtual Sortie & operator<< (const char *ob)
virtual Sortie & operator<< (const Objet_U &ob)
void set_bin (bool bin) override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from SFichier
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Sortie_Fichier_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from AbstractIO
template<typename _TYPE_ >
bool must_convert () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Attributes inherited from Sortie_Fichier_base
ofstream * ofstream_ = nullptr
Protected Attributes inherited from Sortie
std::unique_ptr< ostream > ostream_
Protected Attributes inherited from AbstractIO
bool avoid_conversion_
Detailed Description
Il y a autant de fichiers que de processus, physiquement localises sur le disque de la machine hebergeant la tache maitre de l'application Trio-U (le processus de rang 0 dans le groupe "tous") Le processus maitre recoit chaque item a ecrire de chacun des processus et dans chacun chacun des fichiers. il en est de meme pour les methodes d'inspection de l'etat d'un fichier.
Constructor & Destructor Documentation
~EcrFicCollecte()
EcrFicCollecte::~EcrFicCollecte ()
References Sortie_Fichier_base::close().
EcrFicCollecte() [1/2]
EcrFicCollecte::EcrFicCollecte () inline
EcrFicCollecte() [2/2]
EcrFicCollecte::EcrFicCollecte (const char * name, std::ios_base::openmode mode = ios::out)
Constructeur Ouvre le fichier avec les parametres mode et prot donnes.
Ces parametres sont les parametres de la methode open standard
Parameters
(const char* name) nom du fichier
(int mode) parametre passe a open
(int prot) parametre passe a open
References ouvrir().
Member Function Documentation
cree_instance()
Objet_U * EcrFicCollecte::cree_instance () static
taille_memoire()
unsigned EcrFicCollecte::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in EcrFicCollecteBin.
duplique()
int EcrFicCollecte::duplique () const override virtual
Implements Objet_U.
Reimplemented in EcrFicCollecteBin.
info()
const Type_info * EcrFicCollecte::info () static
get_info()
const Type_info * EcrFicCollecte::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
Reimplemented in EcrFicCollecteBin.
self_cast() [1/2]
EcrFicCollecte & EcrFicCollecte::self_cast (Objet_U & r) static
self_cast() [2/2]
const EcrFicCollecte & EcrFicCollecte::self_cast (const Objet_U & r) static
printOn()
Sortie & EcrFicCollecte::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
Reimplemented in EcrFicCollecteBin.
readOn()
Entree & EcrFicCollecte::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
Reimplemented in EcrFicCollecteBin.
ouvrir()
int EcrFicCollecte::ouvrir (const char * name, std::ios_base::openmode mode = ios::out) override virtual
Ouvre le fichier avec les parametres mode et prot donnes Ces parametres sont les parametres de la methode open standard.
Parameters
(const char* name) nom du fichier
(int mode) parametre passe a open
(int prot) parametre passe a open
Reimplemented from Sortie_Fichier_base.
References Process::is_parallel(), Process::je_suis_maitre(), Process::me(), Nom::nom_me(), and Sortie_Fichier_base::ouvrir().
Referenced by EcrFicCollecte(), EcrFicCollecteBin::EcrFicCollecteBin(), Raffiner_isotrope_parallele::interpreter(), Debog_Pb::readOn(), and SolveurSys_base::save_matrice_secmem_conditionnel().
Member Data Documentation
info_obj
const Type_info EcrFicCollecte::info_obj static