TrioCFD: Multiplicateur_diphasique_Lottes_Flinn Class Reference
Multiplicateur_diphasique_Lottes_Flinn Class Reference
#include <Multiplicateur_diphasique_Lottes_Flinn.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
   alpha < alpha_min -> seule la phase liquide frotte avec phi = 1 / (1-alpha)^2
   alpha > alpha_max -> seule la vapeur frotte
 parametres :
  - alpha_min -> debut de la transition
  - alpha_fin -> fin de la transition
Constructor & Destructor Documentation
Multiplicateur_diphasique_Lottes_Flinn()
Multiplicateur_diphasique_Lottes_Flinn::Multiplicateur_diphasique_Lottes_Flinn ()
~Multiplicateur_diphasique_Lottes_Flinn()
Multiplicateur_diphasique_Lottes_Flinn::~Multiplicateur_diphasique_Lottes_Flinn ()
Member Function Documentation
cree_instance()
Objet_U * Multiplicateur_diphasique_Lottes_Flinn::cree_instance () static
taille_memoire()
unsigned Multiplicateur_diphasique_Lottes_Flinn::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Multiplicateur_diphasique_Lottes_Flinn::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Multiplicateur_diphasique_Lottes_Flinn::info () static
get_info()
const Type_info * Multiplicateur_diphasique_Lottes_Flinn::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Multiplicateur_diphasique_base.
self_cast() [1/2]
Multiplicateur_diphasique_Lottes_Flinn & Multiplicateur_diphasique_Lottes_Flinn::self_cast (Objet_U & r) static
self_cast() [2/2]
const Multiplicateur_diphasique_Lottes_Flinn & Multiplicateur_diphasique_Lottes_Flinn::self_cast (const Objet_U & r) static
printOn()
Sortie & Multiplicateur_diphasique_Lottes_Flinn::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Multiplicateur_diphasique_base.
readOn()
Entree & Multiplicateur_diphasique_Lottes_Flinn::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Multiplicateur_diphasique_base.
References Param::ajouter(), alpha_max_, alpha_min_, Nom::debute_par(), Process::exit(), Param::lire_avec_accolades_depuis(), n_g, n_l, Pb_Multiphase::nb_phases(), Pb_Multiphase::nom_phase(), Correlation_base::pb_, Objet_U::que_suis_je(), and TRUST_Ref< _CLASSE_ >::valeur().
coefficient()
void Multiplicateur_diphasique_Lottes_Flinn::coefficient (const double * alpha, const double * rho, const double * v, const double * f, const double * mu, const double Dh, const double gamma, const double * Fk, const double Fm, DoubleTab & coeff) const override virtual
Implements Multiplicateur_diphasique_base.
References alpha_max_, alpha_min_, n_g, and n_l.
Member Data Documentation
info_obj
const Type_info Multiplicateur_diphasique_Lottes_Flinn::info_obj static
alpha_min_
double Multiplicateur_diphasique_Lottes_Flinn::alpha_min_ = 0.9 protected
Referenced by coefficient(), and readOn().
alpha_max_
double Multiplicateur_diphasique_Lottes_Flinn::alpha_max_ = 0.95 protected
Referenced by coefficient(), and readOn().
n_l
int Multiplicateur_diphasique_Lottes_Flinn::n_l = -1 protected
Referenced by coefficient(), and readOn().
n_g
int Multiplicateur_diphasique_Lottes_Flinn::n_g = -1 protected
Referenced by coefficient(), and readOn().