TrioCFD: Paroi_std_scal_hyd_VDF Class Reference
Paroi_std_scal_hyd_VDF Class Reference
#include <Paroi_std_scal_hyd_VDF.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Turbulence_paroi_scal_base
void associer_modele (const Modele_turbulence_scal_base &)
const Type_info * get_info () const override
void imprimer_nusselt_mean_only (Sortie &, int, const TRUST_List< Nom > &, const Nom &) const
void imprimer_premiere_ligne_nusselt (int, const TRUST_List< Nom > &, const Nom &) const
int reprendre (Entree &is) override
int sauvegarder (Sortie &os) const override
virtual bool use_equivalent_distance () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Turbulence_paroi_scal_base
static void typer_lire_turbulence_paroi_scal (TRUST_Deriv< Turbulence_paroi_scal_base > &, const Modele_turbulence_scal_base &, Entree &)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
.SECTION voir aussi Paroi_std_hyd_VDF
Constructor & Destructor Documentation
~Paroi_std_scal_hyd_VDF()
Paroi_std_scal_hyd_VDF::~Paroi_std_scal_hyd_VDF ()
Member Function Documentation
cree_instance()
Objet_U * Paroi_std_scal_hyd_VDF::cree_instance () static
taille_memoire()
unsigned Paroi_std_scal_hyd_VDF::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Loi_expert_scalaire_VDF, and Paroi_TBLE_scal_VDF.
duplique()
int Paroi_std_scal_hyd_VDF::duplique () const override virtual
Implements Objet_U.
Reimplemented in Loi_expert_scalaire_VDF, and Paroi_TBLE_scal_VDF.
info()
const Type_info * Paroi_std_scal_hyd_VDF::info () static
get_info()
const Type_info * Paroi_std_scal_hyd_VDF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Paroi_scal_hyd_base_VDF.
Reimplemented in Loi_expert_scalaire_VDF, and Paroi_TBLE_scal_VDF.
self_cast() [1/2]
Paroi_std_scal_hyd_VDF & Paroi_std_scal_hyd_VDF::self_cast (Objet_U & r) static
self_cast() [2/2]
const Paroi_std_scal_hyd_VDF & Paroi_std_scal_hyd_VDF::self_cast (const Objet_U & r) static
printOn()
Sortie & Paroi_std_scal_hyd_VDF::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Paroi_scal_hyd_base_VDF.
Reimplemented in Loi_expert_scalaire_VDF, and Paroi_TBLE_scal_VDF.
References Objet_U::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Paroi_std_scal_hyd_VDF::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Paroi_scal_hyd_base_VDF.
Reimplemented in Loi_expert_scalaire_VDF, and Paroi_TBLE_scal_VDF.
init_lois_paroi()
int Paroi_std_scal_hyd_VDF::init_lois_paroi () override virtual
Reimplemented from Paroi_scal_hyd_base_VDF.
Reimplemented in Paroi_TBLE_scal_VDF.
References Paroi_scal_hyd_base_VDF::init_lois_paroi(), and init_lois_paroi_scalaire().
Referenced by Paroi_TBLE_scal_VDF::init_lois_paroi().
calculer_scal()
int Paroi_std_scal_hyd_VDF::calculer_scal (Champ_Fonc_base & diffusivite_turb) override virtual
Implements Turbulence_paroi_scal_base.
Reimplemented in Paroi_TBLE_scal_VDF.
References Objet_U::axi, Milieu_base::diffusivite(), Domaine_VDF::dim_elem(), Objet_U::dimension, Domaine_VDF::dist_norm_bord(), Domaine_VDF::dist_norm_bord_axi(), Turbulence_paroi_scal_base::equivalent_distance_, Process::exit(), Domaine_VF::face_voisins(), Domaine_VF::front_VF(), Equation_base::get_modele(), Turbulence_paroi_scal_base::le_dom_Cl_dis_, Turbulence_paroi_scal_base::le_dom_dis_, Frontiere_dis_base::le_nom(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), TRUSTVect< _TYPE_, _SIZE_ >::local_min_vect(), Modele_turbulence_hyd_base::loi_paroi(), Equation_base::milieu(), Turbulence_paroi_scal_base::mon_modele_turb_scal, Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_local_face(), Front_VF::num_premiere_face(), Domaine_VDF::orientation(), Turbulence_paroi_scal_base::T_plus(), Turbulence_paroi_base::tab_u_star(), TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), TRUST_Ref_Objet_U::valeur(), Champ_Don_base::valeurs(), and Fluide_base::viscosite_cinematique().
init_lois_paroi_scalaire()
int Paroi_std_scal_hyd_VDF::init_lois_paroi_scalaire () protected
Referenced by init_lois_paroi().
Member Data Documentation
info_obj
const Type_info Paroi_std_scal_hyd_VDF::info_obj static