TrioCFD: Tetraedre_32_64< _SIZE_ > Class Template Reference
Tetraedre_32_64< _SIZE_ > Class Template Reference
#include <Tetraedre.h>
Public Member Functions
void calculer_normales (const IntTab_t &faces_sommets, DoubleTab_t &face_normales) const override
void calculer_volumes (DoubleVect_t &vols) const override
int contient (const ArrOfDouble &pos, int_t elem) const override
int contient (const SmallArrOfTID_t &soms, int_t elem) const override
int face_sommet (int i, int j) const override
int face_sommet0 (int i) const
int face_sommet1 (int i) const
int face_sommet2 (int i) const
int face_sommet3 (int i) const
const Type_info * get_info () const override
void get_tab_aretes_sommets_locaux (IntTab &aretes_som_local) const override
int nb_faces (int=0) const override
int nb_som_face (int=0) const override
const Nom & nom_lml () const override
Type_Face type_face (int=0) const override
Public Member Functions inherited from Elem_geom_base_32_64< _SIZE_ >
virtual void calculer_centres_gravite (DoubleTab_t &) const
virtual void calculer_normales (const IntTab_t &faces_sommets, DoubleTab_t &face_normales) const
void creer_faces_elem (Faces_t &, int_t) const
virtual void creer_faces_elem (Faces_t &, int_t, Type_Face) const
const Type_info * get_info () const override
virtual void get_tab_aretes_sommets_locaux (IntTab &aretes_som_local) const
virtual int get_tab_faces_sommets_locaux (IntTab &faces_som_local) const
virtual int nb_type_face () const
virtual int num_face (int face, Type_Face &type) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions
static void matrice_base_tetraedre (const IntTab &polys, const DoubleTab &coords, int num_elem, Matrice33 &m)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
template<typename _SIZE_>
class Tetraedre_32_64< _SIZE_ >
Un tetraedre est un polyedre qui a 4 faces, 4 sommets et un seul type de face ayant 3 sommets par face.
See also
Elem_geom_base Elem_geom, C'est un element utilisable en 3D
Member Typedef Documentation
int_t
template<typename _SIZE_ > using Tetraedre_32_64< _SIZE_ >::int_t = _SIZE_
IntTab_t
template<typename _SIZE_ > using Tetraedre_32_64< _SIZE_ >::IntTab_t = IntTab_T<_SIZE_>
SmallArrOfTID_t
template<typename _SIZE_ > using Tetraedre_32_64< _SIZE_ >::SmallArrOfTID_t = SmallArrOfTID_T<_SIZE_>
DoubleVect_t
template<typename _SIZE_ > using Tetraedre_32_64< _SIZE_ >::DoubleVect_t = DoubleVect_T<_SIZE_>
DoubleTab_t
template<typename _SIZE_ > using Tetraedre_32_64< _SIZE_ >::DoubleTab_t = DoubleTab_T<_SIZE_>
Domaine_t
template<typename _SIZE_ > using Tetraedre_32_64< _SIZE_ >::Domaine_t = Domaine_32_64<_SIZE_>
Constructor & Destructor Documentation
Tetraedre_32_64()
template<typename _T_ > Tetraedre_32_64< _T_ >::Tetraedre_32_64
~Tetraedre_32_64()
template<typename _T_ > Tetraedre_32_64< _T_ >::~Tetraedre_32_64
Member Function Documentation
cree_instance()
template<typename _T_ > Objet_U * Tetraedre_32_64< _T_ >::cree_instance static
taille_memoire()
template<typename _T_ > unsigned Tetraedre_32_64< _T_ >::taille_memoire override virtual
Implements Objet_U.
duplique()
template<typename _T_ > int Tetraedre_32_64< _T_ >::duplique override virtual
Implements Objet_U.
info()
template<typename _T_ > const Type_info * Tetraedre_32_64< _T_ >::info static
get_info()
template<typename _T_ > const Type_info * Tetraedre_32_64< _T_ >::get_info override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Elem_geom_base_32_64< _SIZE_ >.
self_cast() [1/2]
template<typename _T_ > Tetraedre_32_64< _T_ > & Tetraedre_32_64< _T_ >::self_cast (Objet_U & r) static
self_cast() [2/2]
template<typename _T_ > const Tetraedre_32_64< _T_ > & Tetraedre_32_64< _T_ >::self_cast (const Objet_U & r) static
printOn()
template<typename _SIZE_ > Sortie & Tetraedre_32_64< _SIZE_ >::printOn (Sortie & s) const override protected virtual
NE FAIT RIEN.
Parameters
(Sortie& s) un flot de sortie
Returns
(Sortie&) le flot de sortie
Reimplemented from Elem_geom_base_32_64< _SIZE_ >.
readOn()
template<typename _SIZE_ > Entree & Tetraedre_32_64< _SIZE_ >::readOn (Entree & s) override protected virtual
NE FAIT RIEN.
Parameters
(Entree& s) un flot d'entree
Returns
(Entree&) le flot d'entree
Reimplemented from Elem_geom_base_32_64< _SIZE_ >.
face_sommet()
template<typename _SIZE_ > int Tetraedre_32_64< _SIZE_ >::face_sommet (int i, int j) const inline override virtual
Renvoie le numero du j-ieme sommet de la i-ieme face de l'element.
Parameters
(int i) un numero de face
(int j) un numero de sommet
Returns
(int) le numero du j-ieme sommet de la i-ieme face
Implements Elem_geom_base_32_64< _SIZE_ >.
face_sommet0()
template<typename _SIZE_ > int Tetraedre_32_64< _SIZE_ >::face_sommet0 (int i) const inline
Renvoie le numero du i-ieme sommet de la face 0.
Parameters
(int i) le numero du sommet a renvoyer
Returns
(int) le numero du i-ieme sommet de la face 0
face_sommet1()
template<typename _SIZE_ > int Tetraedre_32_64< _SIZE_ >::face_sommet1 (int i) const inline
Renvoie le numero du i-ieme sommet de la face 1.
Parameters
(int i) le numero du sommet a renvoyer
Returns
(int) le numero du i-ieme sommet de la face 1
face_sommet2()
template<typename _SIZE_ > int Tetraedre_32_64< _SIZE_ >::face_sommet2 (int i) const inline
Renvoie le numero du i-ieme sommet de la face 2.
Parameters
(int i) le numero du sommet a renvoyer
Returns
(int) le numero du i-ieme sommet de la face 2
face_sommet3()
template<typename _SIZE_ > int Tetraedre_32_64< _SIZE_ >::face_sommet3 (int i) const inline
Renvoie le numero du i-ieme sommet de la face 3.
Parameters
(int i) le numero du sommet a renvoyer
Returns
(int) le numero du i-ieme sommet de la face 3
nb_som()
template<typename _SIZE_ > int Tetraedre_32_64< _SIZE_ >::nb_som () const inline override virtual
Nb of vertices for the element.
Implements Elem_geom_base_32_64< _SIZE_ >.
nb_faces()
template<typename _SIZE_ > int Tetraedre_32_64< _SIZE_ >::nb_faces (int i = 0) const inline override virtual
Renvoie le nombre de faces du type specifie que possede l'element geometrique.
Parameters
(int i) le type de face
Returns
(int) le nombre de faces de type i
Implements Elem_geom_base_32_64< _SIZE_ >.
nb_som_face()
template<typename _SIZE_ > int Tetraedre_32_64< _SIZE_ >::nb_som_face (int i = 0) const inline override virtual
Renvoie le nombre de sommets des faces du type specifie.
Parameters
(int i) le type de face
Returns
(int) le nombre de sommets des faces de type i
Implements Elem_geom_base_32_64< _SIZE_ >.
est_structure()
template<typename _SIZE_ > bool Tetraedre_32_64< _SIZE_ >::est_structure () const inline override virtual
Implements Elem_geom_base_32_64< _SIZE_ >.
nom_lml()
template<typename _SIZE_ > const Nom & Tetraedre_32_64< _SIZE_ >::nom_lml override virtual
Renvoie le nom LML d'un tetraedre = "TETRA4".
Returns
(Nom&) toujours egal a "TETRA4"
Implements Elem_geom_base_32_64< _SIZE_ >.
contient() [1/2]
template<typename _SIZE_ > int Tetraedre_32_64< _SIZE_ >::contient (const ArrOfDouble & pos, int_t ielem) const override virtual
Renvoie 1 si l'element ielem du domaine associe a l'element geometrique contient le point.
         de coordonnees specifiees par le parametre "pos".
Renvoie 0 sinon.
Parameters
(DoubleVect& pos) coordonnees du point que l'on cherche a localiser
(int ielem) le numero de l'element du domaine dans lequel on cherche le point.
Returns
(int) 1 si le point de coordonnees specifiees appartient a l'element ielem 0 sinon
Implements Elem_geom_base_32_64< _SIZE_ >.
References Objet_U::precision_geom, and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
contient() [2/2]
template<typename _SIZE_ > int Tetraedre_32_64< _SIZE_ >::contient (const SmallArrOfTID_t & som, int_t element) const override virtual
Renvoie 1 si les sommets specifies par le parametre "pos" sont les sommets de l'element "element" du domaine associe a.
l'element geometrique.
Parameters
(IntVect& pos) les numeros des sommets a comparer avec ceux de l'elements "element"
(int element) le numero de l'element du domaine dont on veut comparer les sommets
Returns
(int) 1 si les sommets passes en parametre sont ceux de l'element specifie, 0 sinon
Implements Elem_geom_base_32_64< _SIZE_ >.
type_face()
template<typename _SIZE_ > Type_Face Tetraedre_32_64< _SIZE_ >::type_face (int i = 0) const inline override virtual
Renvoie le i-ieme type de face.
Un tetraedre n'a qu'un seul type de face.
Parameters
(int i) le rang du type de face a renvoyer
Returns
(Type_Face) un type de face
Implements Elem_geom_base_32_64< _SIZE_ >.
calculer_volumes()
template<typename _SIZE_ > void Tetraedre_32_64< _SIZE_ >::calculer_volumes (DoubleVect_t & volumes) const override virtual
Calcule les volumes des elements du domaine associe.
Parameters
(DoubleVect& volumes) le vecteur contenant les valeurs des des volumes des elements du domaine
Implements Elem_geom_base_32_64< _SIZE_ >.
References Domaine_32_64< _SIZE_ >::coord(), and TRUSTVect< _TYPE_, _SIZE_ >::size_totale().
calculer_normales()
template<typename _SIZE_ > void Tetraedre_32_64< _SIZE_ >::calculer_normales (const IntTab_t & Face_sommets, DoubleTab_t & face_normales) const override virtual
Calcule les normales aux faces des elements du domaine associe.
Parameters
(IntTab& face_sommets) les numeros des sommets des faces dans la liste des sommets du domaine associe
(DoubleTab& face_normales)
Reimplemented from Elem_geom_base_32_64< _SIZE_ >.
References Domaine_32_64< _SIZE_ >::coord_sommets(), and TRUSTTab< _TYPE_, _SIZE_ >::dimension().
get_tab_faces_sommets_locaux()
template<typename _SIZE_ > int Tetraedre_32_64< _SIZE_ >::get_tab_faces_sommets_locaux (IntTab & faces_som_local) const override virtual
voir ElemGeomBase::get_tab_faces_sommets_locaux
Reimplemented from Elem_geom_base_32_64< _SIZE_ >.
References TRUSTTab< _TYPE_, _SIZE_ >::resize().
get_tab_aretes_sommets_locaux()
template<typename _SIZE_ > void Tetraedre_32_64< _SIZE_ >::get_tab_aretes_sommets_locaux (IntTab & aretes_som_local) const override virtual
idem que Elem_geom_base::get_tab_faces_sommets_locaux mais pour les aretes: aretes_som_local.
dimension(0) = nombre d'aretes sur l'element de reference aretes_som_local.dimension(1) = 2 (nombre de sommets par arete) aretes_som_local(i,j) = numero d'un sommet de l'element (0 <= n < nb_sommets_par_element)
Reimplemented from Elem_geom_base_32_64< _SIZE_ >.
References TRUSTTab< _TYPE_, _SIZE_ >::resize().
matrice_base_tetraedre() [1/2]
template<typename _SIZE_ > void Tetraedre_32_64< _SIZE_ >::matrice_base_tetraedre (const IntTab & polys, const DoubleTab & coords, int num_elem, Matrice33 & m, Vecteur3 & origine) inline static
Idem que la precedente, mais remplit en plus "origine" avec les coordonnees du premier sommet.
matrice_base_tetraedre() [2/2]
template<typename _SIZE_ > void Tetraedre_32_64< _SIZE_ >::matrice_base_tetraedre (const IntTab & polys, const DoubleTab & coords, int num_elem, Matrice33 & m) inline static
remplit la matrice m avec les trois vecteurs de base du tetraedre demande (le premier sommet du tetra est pris comme origine).
polys est le tableau des elements du domaine, coords le tableau des coordonnees num_elem le numero du tetraedre a calculer. m est rempli avec la matrice m(i,j) = coord(polys(num_elem, j+1), i) - coord(polys(num_elem, 0), i)
info_obj() [1/2]
const Type_info Tetraedre_32_64< int >::info_obj ("Tetraedre" , Tetraedre_32_64< int >::cree_instance , 1 , Tetraedre_32_64bases< int >)
info_obj() [2/2]
const Type_info Tetraedre_32_64< trustIdType >::info_obj ("Tetraedre" "_64" , Tetraedre_32_64< trustIdType >::cree_instance , 1 , Tetraedre_32_64bases< trustIdType >)
Member Data Documentation
info_obj
template<typename _SIZE_ > const Type_info Tetraedre_32_64< _SIZE_ >::info_obj static
dimension
template<typename _SIZE_ > int Objet_U::dimension static protected