TrioCFD: Diffu_lm Class Reference
Diffu_lm Class Reference
#include <Diffu_lm.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Diffu_totale_hyd_base
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Diffu_totale_hyd_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
de la diffusivite_totale
Constructor & Destructor Documentation
Diffu_lm()
Diffu_lm::Diffu_lm ()
~Diffu_lm()
Diffu_lm::~Diffu_lm ()
Member Function Documentation
cree_instance()
Objet_U * Diffu_lm::cree_instance () static
taille_memoire()
unsigned Diffu_lm::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Diffu_lm::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Diffu_lm::info () static
get_info()
const Type_info * Diffu_lm::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
Diffu_lm & Diffu_lm::self_cast (Objet_U & r) static
self_cast() [2/2]
const Diffu_lm & Diffu_lm::self_cast (const Objet_U & r) static
printOn()
Sortie & Diffu_lm::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
readOn()
Entree & Diffu_lm::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
calculer_a_local()
double Diffu_lm::calculer_a_local (int ind) override virtual
Implements Diffu_totale_hyd_base.
References Diffu_totale_base::eq_couch_lim, Diffu_totale_hyd_base::eq_couch_lim_T, Eq_couch_lim::get_N(), Eq_couch_lim::get_N_comp(), Eq_couch_lim::get_nu_t_dyn(), Eq_couch_lim::get_nu_t_yn(), Eq_couch_lim::get_Unp1(), Eq_couch_lim::get_utau_old(), Eq_couch_lim::get_y(), Diffu_totale_base::getKappa(), Diffu_totale_base::mu_lambda, and TRUST_Ref< _CLASSE_ >::valeur().
calculer_D_local()
double Diffu_lm::calculer_D_local (int ind) override virtual
Implements Diffu_totale_base.
References Diffu_totale_base::eq_couch_lim, Eq_couch_lim::get_milieu(), Eq_couch_lim::get_utau_old(), Eq_couch_lim::get_y(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), and Fluide_base::viscosite_cinematique().
Member Data Documentation
info_obj
const Type_info Diffu_lm::info_obj static