TrioCFD: Discretisation_base Class Reference
Discretisation_base Class Reference abstract
#include <Discretisation_base.h>
Public Member Functions
virtual void discretiser_champ (const Motcle &directive, const Domaine_dis_base &z, Nature_du_champ nature, const Noms &nom, const Noms &unite, int nb_comp, int nb_pas_dt, double temps, TRUST_Deriv< Champ_Inc_base > &champ, const Nom &sous_type=NOM_VIDE) const
const Type_info * get_info () const override
virtual Nom get_name_of_type_for (const Nom &class_operateur, const Nom &type_operteur, const Equation_base &eqn, const TRUST_Ref< Champ_base * > &champ_supp=TRUST_Ref< Champ_base * >()) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions
static void creer_champ (TRUST_Deriv< Champ_Don_base > &ch, const Domaine_dis_base &z, const Nom &type, const Nom &nom, const Nom &unite, int nb_comp, int nb_ddl, double temps, const Nom &directive=NOM_VIDE, const Nom &nom_discretisation=NOM_VIDE)
static void creer_champ (TRUST_Deriv< Champ_Fonc_base > &ch, const Domaine_dis_base &z, const Nom &type, const Nom &nom, const Nom &unite, int nb_comp, int nb_ddl, double temps, const Nom &directive=NOM_VIDE, const Nom &nom_discretisation=NOM_VIDE)
static void creer_champ (TRUST_Deriv< Champ_Inc_base > &ch, const Domaine_dis_base &z, const Nom &type, const Nom &nom, const Nom &unite, int nb_comp, int nb_ddl, int nb_pas_dt, double temps, const Nom &directive=NOM_VIDE, const Nom &nom_discretisation=NOM_VIDE)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
sera associe a un probleme. Discretisation_base est la classe
abstraite qui est a la base de la hierarchie des discretisations
en espace.
See also
Probleme_base, Classe abstraite dont toutes les discretisations en espace doivent, deriver., Methode abstraite:, void domaine_Cl_dis(Domaine_dis_base& , Domaine_Cl_dis_base&) const
Member Enumeration Documentation
type_calcul_du_residu
enum Discretisation_base::type_calcul_du_residu
Enumerator
VIA_CONTRIBUER_AU_SECOND_MEMBRE
VIA_AJOUTER
Constructor & Destructor Documentation
Discretisation_base()
Discretisation_base::Discretisation_base ()
~Discretisation_base()
Discretisation_base::~Discretisation_base () override
Member Function Documentation
info()
const Type_info * Discretisation_base::info () static
get_info()
const Type_info * Discretisation_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
Reimplemented in IJK_discretisation, Discr_inst, PolyMAC_discretisation, PolyMAC_P0_discretisation, PolyMAC_P0P1NC_discretisation, Discret_Thyd, Discret_Thermique, VDF_discretisation, and VEF_discretisation.
self_cast() [1/2]
Discretisation_base & Discretisation_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Discretisation_base & Discretisation_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Discretisation_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
Reimplemented in IJK_discretisation, Discr_inst, PolyMAC_discretisation, PolyMAC_P0_discretisation, PolyMAC_P0P1NC_discretisation, Discret_Thyd, Discret_Thermique, VDF_discretisation, and VEF_discretisation.
readOn()
Entree & Discretisation_base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
Reimplemented in IJK_discretisation, Discr_inst, PolyMAC_discretisation, PolyMAC_P0_discretisation, PolyMAC_P0P1NC_discretisation, Discret_Thyd, Discret_Thermique, VDF_discretisation, and VEF_discretisation.
codage_du_calcul_du_residu()
virtual type_calcul_du_residu Discretisation_base::codage_du_calcul_du_residu () const inline virtual
Reimplemented in DG_discretisation, EF_discretisation, PolyMAC_discretisation, and PolyMAC_P0P1NC_discretisation.
References VIA_AJOUTER.
Referenced by Equation_base::assembler(), and Convection_Diffusion_Temperature::assembler().
associer_domaine()
void Discretisation_base::associer_domaine (const Domaine & dom)
References le_domaine_.
Referenced by Probleme_base::discretiser(), and Modele_rayo_semi_transp::discretiser().
domaine_cl_dis_type()
virtual Nom Discretisation_base::domaine_cl_dis_type () const pure virtual
Implemented in DG_discretisation, EF_discretisation, IJK_discretisation, Discr_inst, PolyMAC_discretisation, VDF_discretisation, and VEF_discretisation.
discretiser_variables()
void Discretisation_base::discretiser_variables () const virtual
References Process::exit().
discretiser()
Domaine_dis_base & Discretisation_base::discretiser () const virtual
References Domaine_dis_cache::Build_or_get(), le_domaine_, and Objet_U::que_suis_je().
Referenced by Probleme_base::discretiser(), and Modele_rayo_semi_transp::discretiser().
discretiser_champ() [1/6]
void Discretisation_base::discretiser_champ (const Motcle & directive, const Domaine_dis_base & z, const Nom & nom, const Nom & unite, int nb_comp, int nb_pas_dt, double temps, TRUST_Deriv< Champ_Inc_base > & champ, const Nom & sous_type = NOM_VIDE) const
References TRUST_Vector< _CLASSE_ >::add(), and discretiser_champ().
Referenced by Op_Grad_EF::associer(), Source_PDF_EF::associer_pb(), Modele_Lam_Bremhorst_VEF::calcul_tenseur_Re_elem(), Modele_Lam_Bremhorst_VEF::calcul_tenseur_Re_elem_BiK(), Modele_Lam_Bremhorst_VEF::calcul_tenseur_Re_elem_shih(), Modele_turbulence_hyd_0_eq_base::completer(), Discret_Thyd::concentration(), Op_Conv_VDF_base::creer_champ(), Transport_Marqueur_FT::creer_champ(), Navier_Stokes_phase_field::creer_champ(), Source_PDF_EF::creer_champ(), Paroi_hyd_base_EF::creer_champ(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::creer_champ(), Navier_Stokes_std::creer_champ(), QDM_Multiphase::creer_champ(), Source_Portance_interfaciale_base::creer_champ(), Turbulence_paroi_base::creer_champ(), Fluide_base::creer_e_int(), Champ_Gen_de_Champs_Gen::creer_espace_stockage(), Champ_Generique_Morceau_Equation::creer_espace_stockage(), Discret_Thyd::diametre_hydraulique_face(), Interpolation_IBM_hybrid::discretise(), Interpolation_IBM_power_law_tbl_u_star::discretise(), Interpolation_IBM_elem_fluid::discretise(), Interpolation_IBM_mean_gradient::discretise(), Modele_Fonc_Bas_Reynolds_Base::discretiser(), Modele_Fonc_Realisable_base::discretiser(), Equation_base::discretiser(), Modele_turbulence_hyd_base::discretiser(), Modele_turbulence_scal_base::discretiser(), Navier_Stokes_std_ALE::discretiser(), Echelle_temporelle_turbulente::discretiser(), Energie_cinetique_turbulente::discretiser(), Energie_cinetique_turbulente_WIT::discretiser(), Taux_dissipation_turbulent::discretiser(), Convection_Diffusion_Temperature_FT_Disc::discretiser(), Navier_Stokes_FT_Disc::discretiser(), Transport_Interfaces_FT_Disc::discretiser(), Transport_Marqueur_FT::discretiser(), Convection_Diffusion_Phase_field::discretiser(), Transport_K_Eps_base::discretiser(), Transport_K_Omega_base::discretiser(), Transport_K_ou_Eps_base::discretiser(), Convection_Diffusion_Espece_Fluide_Dilatable_base::discretiser(), Aire_interfaciale::discretiser(), Masse_Multiphase::discretiser(), Loi_Fermeture_Test::discretiser(), Milieu_base::discretiser(), Marqueur_Lagrange_base::discretiser(), Fluide_Dilatable_base::discretiser(), Fluide_Quasi_Compressible::discretiser(), Fluide_Weakly_Compressible::discretiser(), Fluide_base::discretiser(), Fluide_reel_base::discretiser(), Milieu_composite::discretiser(), Solide::discretiser(), discretiser_champ(), DG_discretisation::discretiser_champ(), EF_discretisation::discretiser_champ(), PolyMAC_discretisation::discretiser_champ(), PolyMAC_P0P1NC_discretisation::discretiser_champ(), VDF_discretisation::discretiser_champ(), Modele_turbulence_hyd_base::discretiser_corr_visc_turb(), Modele_turbulence_hyd_base::discretiser_K(), Reaction::discretiser_omega(), Interface_base::discretiser_sigma(), Saturation_base::discretiser_Tsat(), Modele_turbulence_hyd_base::discretiser_visc_turb(), Discret_Thyd::divergence_U(), Discret_Thyd::entcor(), Discret_Thermique::enthalpie(), Discret_Thermique::Fluctu_Temperature(), Discret_Thermique::Flux_Chaleur_Turb(), Discret_Thermique::flux_neutronique(), Champ_Generique_Tparoi_VEF::get_champ(), Champ_Generique_Tparoi_VEF::get_champ_without_evaluation(), Discret_Thyd::gradient_P(), Terme_Source_Acceleration::lire_data(), Terme_Puissance_Thermique::lire_donnees(), mesh_numbering(), Navier_Stokes_FT_Disc::preparer_calcul(), Discret_Thyd::pression(), Discret_Thyd::pression_en_pa(), Source_injection_masse_base::readOn(), Source_Scalaire_EF::readOn(), Champ_Input_P0_Composite::readOn(), Diametre_bulles_champ::readOn(), Diametre_bulles_constant::readOn(), Diametre_bulles_musig::readOn(), Gravite_Multiphase::readOn(), Domaine_Cl_EF::remplir_type_elem_Cl(), VDF_discretisation::residu(), VEF_discretisation::residu(), Discret_Thyd::section_passage(), Discret_Thermique::temperature(), Discret_Thyd::translation(), Discret_Thyd::vitesse(), and volume_maille().
discretiser_champ() [2/6]
void Discretisation_base::discretiser_champ (const Motcle & directive, const Domaine_dis_base & z, const Nom & nom, const Nom & unite, int nb_comp, double temps, TRUST_Deriv< Champ_Fonc_base > & champ) const
References TRUST_Vector< _CLASSE_ >::add(), and discretiser_champ().
discretiser_champ() [3/6]
void Discretisation_base::discretiser_champ (const Motcle & directive, const Domaine_dis_base & z, const Nom & nom, const Nom & unite, int nb_comp, double temps, TRUST_Deriv< Champ_Don_base > & champ) const
References TRUST_Vector< _CLASSE_ >::add(), and discretiser_champ().
discretiser_champ() [4/6]
void Discretisation_base::discretiser_champ (const Motcle & directive, const Domaine_dis_base & z, Nature_du_champ nature, const Noms & noms, const Noms & unites, int nb_comp, int nb_pas_dt, double temps, TRUST_Deriv< Champ_Inc_base > & champ, const Nom & sous_type = NOM_VIDE) const virtual
Discretisation d'un champ en fonction de la directive et des autres parametres.
Voir les classes derivees. Cette methode ne traite aucune directive, elle affiche la liste des directives comprises par les classes derivees. Voir par exemple VDF_discretisation.cpp et VEF...
Reimplemented in DG_discretisation, EF_discretisation, Discr_inst, PolyMAC_discretisation, PolyMAC_P0P1NC_discretisation, PolyMAC_P0P1NC_discretisation, VDF_discretisation, and VEF_discretisation.
References DEMANDE_DESCRIPTION, discretiser_champ(), Process::exit(), and Objet_U::que_suis_je().
discretiser_champ() [5/6]
void Discretisation_base::discretiser_champ (const Motcle & directive, const Domaine_dis_base & z, Nature_du_champ nature, const Noms & nom, const Noms & unite, int nb_comp, double temps, TRUST_Deriv< Champ_Fonc_base > & champ) const virtual
idem
Reimplemented in DG_discretisation, EF_discretisation, Discr_inst, PolyMAC_discretisation, PolyMAC_P0P1NC_discretisation, VDF_discretisation, and VEF_discretisation.
References DEMANDE_DESCRIPTION, discretiser_champ(), Process::exit(), and Objet_U::que_suis_je().
discretiser_champ() [6/6]
void Discretisation_base::discretiser_champ (const Motcle & directive, const Domaine_dis_base & z, Nature_du_champ nature, const Noms & nom, const Noms & unite, int nb_comp, double temps, TRUST_Deriv< Champ_Don_base > & champ) const virtual
idem
Reimplemented in DG_discretisation, EF_discretisation, Discr_inst, PolyMAC_discretisation, PolyMAC_P0P1NC_discretisation, VDF_discretisation, and VEF_discretisation.
References DEMANDE_DESCRIPTION, discretiser_champ(), Process::exit(), and Objet_U::que_suis_je().
nommer_completer_champ_physique()
void Discretisation_base::nommer_completer_champ_physique (const Domaine_dis_base & domaine_vdf, const Nom & nom_champ, const Nom & unite, Champ_base & champ, const Probleme_base & pbi) const
References Field_base::fixer_unite(), Probleme_base::get_champ(), Field_base::nommer(), Interprete::objet(), and TRUST_Vector< _CLASSE_ >::size().
Referenced by Puissance_Thermique_EF::associer_pb(), Puissance_Thermique_QC_EF::associer_pb(), Terme_Source_Constituant_PolyMAC_Elem::associer_pb(), Terme_Source_Constituant_VDF_Elem::associer_pb(), Terme_Source_Constituant_VEF_Face::associer_pb(), Navier_Stokes_phase_field::creer_champ(), Milieu_base::discretiser(), Fluide_base::discretiser(), Fluide_Ostwald::discretiser(), Fluide_reel_base::discretiser(), Solide::discretiser(), Constituant::discretiser_multi_concentration(), Terme_Source_Qdm_Face_PolyMAC_P0P1NC::initialiser(), Terme_Puissance_Thermique_Echange_Impose_Elem_base::initialiser(), Terme_Source_Qdm_VDF_Face::initialiser(), Terme_Puissance_Thermique_Echange_Impose_VEF_Face::initialiser(), Terme_Puissance_Thermique::lire_donnees(), Navier_Stokes_phase_field::lire_motcle_non_standard(), Source_injection_masse_base::readOn(), and Source_Scalaire_EF::readOn().
verifie_sous_type()
int Discretisation_base::verifie_sous_type (Nom & type, const Nom & sous_type, const Motcle & directive) const
References Nom::debute_par(), Process::exit(), Type_info::has_base(), Objet_U::que_suis_je(), and Type_info::type_info_from_name().
Referenced by DG_discretisation::discretiser_champ(), PolyMAC_discretisation::discretiser_champ(), PolyMAC_P0P1NC_discretisation::discretiser_champ(), and VDF_discretisation::discretiser_champ().
volume_maille()
void Discretisation_base::volume_maille (const Schema_Temps_base & sch, const Domaine_dis_base & z, TRUST_Deriv< Champ_Fonc_base > & ch) const
References discretiser_champ(), Schema_Temps_base::temps_courant(), Champ_Don_base::valeurs(), and Domaine_VF::volumes().
Referenced by Domaine_dis_base::creer_champ().
mesh_numbering()
void Discretisation_base::mesh_numbering (const Schema_Temps_base & sch, const Domaine_dis_base & z, TRUST_Deriv< Champ_Fonc_base > & ch) const
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), discretiser_champ(), Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), Domaine_32_64< _SIZE_ >::les_elems(), Field_base::nommer(), Schema_Temps_base::temps_courant(), and Champ_Don_base::valeurs().
Referenced by Domaine_dis_base::creer_champ().
residu()
void Discretisation_base::residu (const Domaine_dis_base & , const Champ_Inc_base & , TRUST_Deriv< Champ_Fonc_base > &) const virtual
Reimplemented in VDF_discretisation, VEF_discretisation, PolyMAC_P0_discretisation, and PolyMAC_P0P1NC_discretisation.
References Process::exit(), and Objet_U::que_suis_je().
Referenced by Equation_base::creer_champ().
creer_champ() [1/3]
void Discretisation_base::creer_champ (TRUST_Deriv< Champ_Inc_base > & ch, const Domaine_dis_base & z, const Nom & type, const Nom & nom, const Nom & unite, int nb_comp, int nb_ddl, int nb_pas_dt, double temps, const Nom & directive = NOM_VIDE, const Nom & nom_discretisation = NOM_VIDE) static
Methode statique qui cree un OWN_PTR(Champ_Inc_base) du type specifie.
Les parametres "directive" et "nom_discretisation" sont utilises pour l'affichage uniquement et sont optionnels
References Champ_Inc_base::fixer_nb_valeurs_temporelles().
Referenced by DG_discretisation::discretiser_champ(), EF_discretisation::discretiser_champ(), PolyMAC_discretisation::discretiser_champ(), PolyMAC_P0P1NC_discretisation::discretiser_champ(), VDF_discretisation::discretiser_champ(), VEF_discretisation::discretiser_champ(), VEF_discretisation::grad_T(), Equation_base::init_champ_conserve(), and Energie_Multiphase::init_champ_convecte().
creer_champ() [2/3]
void Discretisation_base::creer_champ (TRUST_Deriv< Champ_Fonc_base > & ch, const Domaine_dis_base & z, const Nom & type, const Nom & nom, const Nom & unite, int nb_comp, int nb_ddl, double temps, const Nom & directive = NOM_VIDE, const Nom & nom_discretisation = NOM_VIDE) static
Methode statique qui cree un OWN_PTR(Champ_Fonc_base) du type specifie.
Les parametres "directive" et "nom_discretisation" sont utilises pour l'affichage uniquement et sont optionnels
creer_champ() [3/3]
void Discretisation_base::creer_champ (TRUST_Deriv< Champ_Don_base > & ch, const Domaine_dis_base & z, const Nom & type, const Nom & nom, const Nom & unite, int nb_comp, int nb_ddl, double temps, const Nom & directive = NOM_VIDE, const Nom & nom_discretisation = NOM_VIDE) static
Methode statique qui cree un OWN_PTR(Champ_Don_base) du type specifie.
Les parametres "directive" et "nom_discretisation" sont utilises pour l'affichage uniquement et sont optionnels
get_name_of_type_for()
Nom Discretisation_base::get_name_of_type_for (const Nom & class_operateur, const Nom & type_operateur, const Equation_base & eqn, const TRUST_Ref< Champ_base * > & champ_sup = TRUST_Ref< Champ_base *>()) const virtual
remplit le Nom type en focntion de la classe de operateur, du type de l'operateur et de l'equation
Parameters
(class_operateur) Ce nom correspond au type de la classe de base de l'objet que l'on veut construire exemples: "source","Op_conv","Op_diff","Op_div","Op_grad","solveur_masse" Exemple get_name_of_type_for("Op_conv","amont",eqn,type); get_name_of_type_for("Op_diff"," ",eqn,type,champ_diffusisivite);
Reimplemented in DG_discretisation, EF_discretisation, PolyMAC_discretisation, and PolyMAC_P0P1NC_discretisation.
References Objet_U::axi, Nom::debute_par(), Equation_base::diffusion_multi_scalaire(), Equation_base::discretisation(), Process::exit(), Equation_base::inconnue(), Probleme_base::is_dilatable(), Field_base::le_nom(), Field_base::nb_comp(), Equation_base::probleme(), Objet_U::que_suis_je(), and Nom::suffix().
Referenced by Convection_Diffusion_Temperature_FT_Disc::compute_divergence_free_velocity_extension(), Equation_base::discretiser(), DG_discretisation::get_name_of_type_for(), EF_discretisation::get_name_of_type_for(), PolyMAC_discretisation::get_name_of_type_for(), PolyMAC_P0P1NC_discretisation::get_name_of_type_for(), Operateur_Conv::typer(), Operateur_Diff::typer(), Operateur_Div::typer(), Operateur_Grad::typer(), Operateur_Evanescence::typer(), and Source::typer().
is_ef()
virtual bool Discretisation_base::is_ef () const inline virtual
Reimplemented in EF_discretisation.
Referenced by Champ_Generique_Extraction::get_champ().
is_dg()
virtual bool Discretisation_base::is_dg () const inline virtual
Reimplemented in DG_discretisation.
Referenced by Milieu_base::discretiser(), and Terme_Puissance_Thermique::lire_donnees().
is_vdf()
virtual bool Discretisation_base::is_vdf () const inline virtual
Reimplemented in VDF_discretisation.
Referenced by Champ_Generique_Extraction::get_champ(), Terme_Puissance_Thermique::lire_donnees(), and QDM_Multiphase::mettre_a_jour().
is_vef()
virtual bool Discretisation_base::is_vef () const inline virtual
Reimplemented in VEF_discretisation.
Referenced by Champ_Generique_Extraction::get_champ(), and Terme_Puissance_Thermique::lire_donnees().
is_polymac()
virtual bool Discretisation_base::is_polymac () const inline virtual
Reimplemented in PolyMAC_discretisation, PolyMAC_P0_discretisation, and PolyMAC_P0P1NC_discretisation.
Referenced by Solveur_U_P::iterer_NS().
is_polymac_p0()
virtual bool Discretisation_base::is_polymac_p0 () const inline virtual
Reimplemented in PolyMAC_P0_discretisation.
is_polymac_p0p1nc()
virtual bool Discretisation_base::is_polymac_p0p1nc () const inline virtual
Reimplemented in PolyMAC_P0_discretisation, and PolyMAC_P0P1NC_discretisation.
is_polymac_family()
virtual bool Discretisation_base::is_polymac_family () const inline virtual
Reimplemented in DG_discretisation, and PolyMAC_discretisation.
Referenced by Terme_Puissance_Thermique::lire_donnees().
Member Data Documentation
info_obj
const Type_info Discretisation_base::info_obj static
DEMANDE_DESCRIPTION
const Motcle Discretisation_base::DEMANDE_DESCRIPTION = Motcle("demande_description") static protected
Referenced by discretiser_champ(), DG_discretisation::discretiser_champ(), EF_discretisation::discretiser_champ(), PolyMAC_discretisation::discretiser_champ(), PolyMAC_P0P1NC_discretisation::discretiser_champ(), VDF_discretisation::discretiser_champ(), and VEF_discretisation::discretiser_champ().
NOM_VIDE
const Nom Discretisation_base::NOM_VIDE = Nom("-") static protected
Referenced by DG_discretisation::discretiser_champ(), PolyMAC_discretisation::discretiser_champ(), PolyMAC_P0P1NC_discretisation::discretiser_champ(), and VDF_discretisation::discretiser_champ().
le_domaine_
TRUST_Ref< Domaine *> Discretisation_base::le_domaine_ protected
Referenced by associer_domaine(), and discretiser().