TrioCFD: Navier_Stokes_Turbulent_QC Class Reference
Navier_Stokes_Turbulent_QC Class Reference
#include <Navier_Stokes_Turbulent_QC.h>
Public Member Functions
void completer () override
DoubleTab & derivee_en_temps_inco (DoubleTab &) override
const Type_info * get_info () const override
int impr (Sortie &) const override
void imprimer (Sortie &os) const override
bool initTimeStep (double dt) override
int preparer_calcul () override
Public Member Functions inherited from Navier_Stokes_Turbulent
void completer () override
const Type_info * get_info () const override
void imprimer (Sortie &) const override
bool initTimeStep (double dt) override
int lire_motcle_non_standard (const Motcle &, Entree &) override
void mettre_a_jour (double) override
int preparer_calcul () override
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Public Member Functions inherited from Navier_Stokes_std
void abortTimeStep () override
void associer_milieu_base (const Milieu_base &) override
void associer_pb_base (const Probleme_base &) override
virtual void calculer_la_pression_en_pa ()
void completer () override
DoubleTab & derivee_en_temps_inco (DoubleTab &) override
const Motcle & domaine_application () const override
Fluide_base & fluide ()
const Fluide_base & fluide () const
const Type_info * get_info () const override
int impr (Sortie &os) const override
const Champ_Inc_base & inconnue () const override
Champ_Inc_base & inconnue () override
bool initTimeStep (double dt) override
Entree & lire_cond_init (Entree &) override
int lire_motcle_non_standard (const Motcle &, Entree &) override
void mettre_a_jour (double temps) override
const Milieu_base & milieu () const override
Milieu_base & milieu () override
int nombre_d_operateurs () const override
const Operateur & operateur (int) const override
Operateur & operateur (int) override
Operateur_Div & operateur_divergence ()
const Operateur_Div & operateur_divergence () const
Operateur_Grad & operateur_gradient ()
const Operateur_Grad & operateur_gradient () const
int preparer_calcul () override
virtual void projeter ()
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
SolveurSys & solveur_pression ()
int verif_Cl () const override
Public Member Functions inherited from Equation_base
virtual void abortTimeStep ()
virtual void associer_domaine_dis (const Domaine_dis_base &)
virtual void associer_pb_base (const Probleme_base &)
virtual void associer_sch_tps_base (const Schema_Temps_base &)
virtual double calculer_pas_de_temps () const
virtual void completer ()
virtual std::vector< YAML_data > data_a_sauvegarder () const
DoubleTab & derivee_en_temps_conv (DoubleTab &, const DoubleTab &)
virtual DoubleTab & derivee_en_temps_inco (DoubleTab &)
const Discretisation_base & discretisation () const
virtual void discretiser ()
virtual const Motcle & domaine_application () const
virtual Domaine_Cl_dis_base & domaine_Cl_dis ()
virtual const Domaine_Cl_dis_base & domaine_Cl_dis () const
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual void imprimer (Sortie &os) const
virtual bool initTimeStep (double dt)
const Nom & le_nom () const override
int limpr () const
virtual void mettre_a_jour (double temps)
virtual int preparer_calcul ()
Probleme_base & probleme ()
const Probleme_base & probleme () const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Schema_Temps_base & schema_temps ()
const Schema_Temps_base & schema_temps () const
Solveur_Masse_base & solv_masse ()
const Solveur_Masse_base & solv_masse () const
Sources & sources ()
const Sources & sources () const
virtual void valider_iteration ()
virtual void verifie_ch_init_nb_comp (const Champ_Inc_base &ch_ref, const int nb_comp) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Navier_Stokes_Fluide_Dilatable_Proto
DoubleTab & derivee_en_temps_inco_impl (Navier_Stokes_std &, DoubleTab &res)
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Navier_Stokes_std
virtual void discretiser_assembleur_pression ()
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Equation_base
virtual Entree & lire_cl (Entree &)
virtual Entree & lire_cond_init (Entree &)
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual Entree & lire_sources (Entree &)
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
virtual int verif_Cl () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
visqueux verifiant la condition d'incompressibilite div U = 0 avec
modelisation de la turbulence.
Un membre de type OWN_PTR(Modele_turbulence_hyd_base)  representera le modele de turbulence.
See also
Navier_Stokes_Turbulent OWN_PTR(Modele_turbulence_hyd_base) Pb_Thermohydraulique_Turbulent_QC
Constructor & Destructor Documentation
Navier_Stokes_Turbulent_QC()
Navier_Stokes_Turbulent_QC::Navier_Stokes_Turbulent_QC ()
~Navier_Stokes_Turbulent_QC()
Navier_Stokes_Turbulent_QC::~Navier_Stokes_Turbulent_QC ()
Member Function Documentation
cree_instance()
Objet_U * Navier_Stokes_Turbulent_QC::cree_instance () static
taille_memoire()
unsigned Navier_Stokes_Turbulent_QC::taille_memoire () const override virtual
Reimplemented from Navier_Stokes_Turbulent.
duplique()
int Navier_Stokes_Turbulent_QC::duplique () const override virtual
Reimplemented from Navier_Stokes_Turbulent.
info()
const Type_info * Navier_Stokes_Turbulent_QC::info () static
get_info()
const Type_info * Navier_Stokes_Turbulent_QC::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Navier_Stokes_Turbulent.
self_cast() [1/2]
Navier_Stokes_Turbulent_QC & Navier_Stokes_Turbulent_QC::self_cast (Objet_U & r) static
self_cast() [2/2]
const Navier_Stokes_Turbulent_QC & Navier_Stokes_Turbulent_QC::self_cast (const Objet_U & r) static
printOn()
Sortie & Navier_Stokes_Turbulent_QC::printOn (Sortie & os) const override protected virtual
Surcharge Objet_U::printOn Imprime l'equation et ses composants sur un flot de sortie.
Imprime le nom de l'equation, le solveur masse, les termes sources les conditions aux limites discretisees, les inconnues et les operateurs.
Parameters
(Sortie& os) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Navier_Stokes_Turbulent.
References Equation_base::printOn().
readOn()
Entree & Navier_Stokes_Turbulent_QC::readOn (Entree & is) override protected virtual
Appel Equation_base::readOn(Entree& is) En sortie verifie que l'on a bien lu:
   - le terme diffusif,
   - le terme convectif,
   - le solveur en pression
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Exceptions
terme diffusif non specifie dans jeu de donnees, specifier un type negligeable pour l'operateur si il est a negliger
terme convectif non specifie dans jeu de donnees, specifier un type negligeable pour l'operateur si il est a negliger
solveur pression non defini dans jeu de donnees
Reimplemented from Navier_Stokes_Turbulent.
References Navier_Stokes_std::divergence, Process::exit(), Navier_Stokes_std::le_fluide, TRUST_Ref< _CLASSE_ >::non_nul(), Objet_U::que_suis_je(), Navier_Stokes_Turbulent::readOn(), Operateur::set_description(), and TRUST_Ref< _CLASSE_ >::valeur().
completer()
void Navier_Stokes_Turbulent_QC::completer () override virtual
Appels successifs a: Navier_Stokes_std::completer()
 Mod_Turb_Hyd::completer() [sur le membre concerne]
Reimplemented from Navier_Stokes_Turbulent.
References TRUST_List< _CLASSE_ >::add(), Navier_Stokes_Turbulent::completer(), Equation_base::discretisation(), Navier_Stokes_std::le_fluide, Equation_base::les_sources, Objet_U::que_suis_je(), and Source::typer_direct().
mettre_a_jour()
void Navier_Stokes_Turbulent_QC::mettre_a_jour (double temps) override virtual
appel Navier_Stokes_Turbulent::mettre_a_jour et Convection_Diffusion_Chaleur_Turbulent_QC::mettre_a_jour_modele
Reimplemented from Navier_Stokes_Turbulent.
References Navier_Stokes_Turbulent::mettre_a_jour(), Equation_base::probleme(), and Objet_U::que_suis_je().
initTimeStep()
bool Navier_Stokes_Turbulent_QC::initTimeStep (double dt) override virtual
Allocation et initialisation de l'inconnue et des CLs jusqu'a present+dt.
autres initialisations pour les calculs sur le prochain pas de temps : operateurs, solveur_masse->
Returns
(0 en cas d'erreur, 1 sinon)
Reimplemented from Navier_Stokes_Turbulent.
References Navier_Stokes_std::inconnue(), Navier_Stokes_Turbulent::initTimeStep(), Navier_Stokes_std::le_fluide, Fluide_Dilatable_base::rho_discvit(), Navier_Stokes_Fluide_Dilatable_Proto::rho_la_vitesse_, Navier_Stokes_Fluide_Dilatable_Proto::rho_vitesse_impl(), TRUST_Ref< _CLASSE_ >::valeur(), and Champ_Inc_base::valeurs().
preparer_calcul()
int Navier_Stokes_Turbulent_QC::preparer_calcul () override virtual
cf Equation_base::preparer_calcul() Assemblage du solveur pression et
initialisation de la pression.
Returns
(int) renvoie toujours 1
Reimplemented from Navier_Stokes_Turbulent.
References Navier_Stokes_Turbulent::preparer_calcul().
impr()
int Navier_Stokes_Turbulent_QC::impr (Sortie & os) const override virtual
Effectue quelques impressions sur un flot de sortie: - maximum de div U.
  - terme convectif
  - terme diffusif
  - divergence
  - gradient
Parameters
(Sortie& os) un flot de sortie
Returns
(int) renvoie toujours 1
Reimplemented from Navier_Stokes_std.
References Navier_Stokes_std::impr(), and Navier_Stokes_Fluide_Dilatable_Proto::impr_impl().
imprimer()
void Navier_Stokes_Turbulent_QC::imprimer (Sortie & os) const override virtual
Imprime les operateurs de l'equation si le schema en temps indique que c'est necessaire.
[SI limpr() ALORS impr(os)]
Parameters
(Sortie& os) le flot de sortie
Reimplemented from Navier_Stokes_Turbulent.
References Navier_Stokes_Turbulent::imprimer().
derivee_en_temps_inco()
DoubleTab & Navier_Stokes_Turbulent_QC::derivee_en_temps_inco (DoubleTab & vpoint) override virtual
Calcule la derivee en temps de l'inconnue vitesse, i.
e. l'acceleration dU/dt et la renvoie. Appelle Equation_base::derivee_en_temps_inco(DoubleTab&) Calcule egalement la pression.
Parameters
(DoubleTab& vpoint) le tableau des valeurs de l'acceleration dU/dt
Returns
(DoubleTab&) le tableau des valeurs de l'acceleration (derivee de la vitesse)
Reimplemented from Navier_Stokes_std.
References Navier_Stokes_Fluide_Dilatable_Proto::derivee_en_temps_inco_impl().
assembler()
void Navier_Stokes_Turbulent_QC::assembler (Matrice_Morse & mat_morse, const DoubleTab & present, DoubleTab & secmem) override virtual
Reimplemented from Equation_base.
References Navier_Stokes_Fluide_Dilatable_Proto::assembler_impl().
assembler_avec_inertie()
void Navier_Stokes_Turbulent_QC::assembler_avec_inertie (Matrice_Morse & mat_morse, const DoubleTab & present, DoubleTab & secmem) override virtual
Reimplemented from Equation_base.
References Navier_Stokes_Fluide_Dilatable_Proto::assembler_avec_inertie_impl().
rho_la_vitesse()
const Champ_Inc_base & Navier_Stokes_Turbulent_QC::rho_la_vitesse () const inline override virtual
Reimplemented from Navier_Stokes_std.
References Navier_Stokes_Fluide_Dilatable_Proto::rho_la_vitesse_.
Referenced by get_champ(), and has_champ().
discretiser()
void Navier_Stokes_Turbulent_QC::discretiser () override virtual
Dicretise l'equation.
Reimplemented from Navier_Stokes_std.
References Equation_base::discretisation(), Navier_Stokes_std::discretiser(), Equation_base::domaine_dis(), Field_base::nommer(), Navier_Stokes_Fluide_Dilatable_Proto::rho_la_vitesse_, Equation_base::schema_temps(), and Discret_Thyd::vitesse().
get_champ()
const Champ_base & Navier_Stokes_Turbulent_QC::get_champ (const Motcle & nom) const override virtual
Reimplemented from Navier_Stokes_Turbulent.
References Nom::getString(), Navier_Stokes_Turbulent::has_champ(), has_champ(), Navier_Stokes_std::milieu(), and rho_la_vitesse().
has_champ() [1/2]
bool Navier_Stokes_Turbulent_QC::has_champ (const Motcle & nom, TRUST_Ref< Champ_base * > & ref_champ) const override virtual
Reimplemented from Navier_Stokes_Turbulent.
References Navier_Stokes_Turbulent::has_champ(), has_champ(), Navier_Stokes_std::milieu(), and rho_la_vitesse().
Referenced by get_champ(), and has_champ().
has_champ() [2/2]
bool Navier_Stokes_Turbulent_QC::has_champ (const Motcle & nom) const override virtual
Reimplemented from Navier_Stokes_Turbulent.
References Navier_Stokes_Turbulent::has_champ(), has_champ(), and Navier_Stokes_std::milieu().
diffusivite_pour_transport()
const Champ_Don_base & Navier_Stokes_Turbulent_QC::diffusivite_pour_transport () const override virtual
Reimplemented from Navier_Stokes_Turbulent.
References Navier_Stokes_std::fluide(), and Fluide_base::viscosite_dynamique().
Member Data Documentation
info_obj
const Type_info Navier_Stokes_Turbulent_QC::info_obj static