TrioCFD: Op_Conv_PolyMAC_base Class Reference
Op_Conv_PolyMAC_base Class Reference
#include <Op_Conv_PolyMAC_base.h>
Public Member Functions
double calculer_dt_stab () const override
void completer () override
const Type_info * get_info () const override
int impr (Sortie &os) const override
const Type_info * get_info () const override
Public Member Functions inherited from Operateur_base
void associer_eqn (const Equation_base &)
virtual double calculer_dt_stab () const
virtual void completer ()
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual void mettre_a_jour (double temps)
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Op_Conv_PolyMAC_base()
Op_Conv_PolyMAC_base::Op_Conv_PolyMAC_base ()
~Op_Conv_PolyMAC_base()
Op_Conv_PolyMAC_base::~Op_Conv_PolyMAC_base () override
Member Function Documentation
info()
const Type_info * Op_Conv_PolyMAC_base::info () static
get_info()
const Type_info * Op_Conv_PolyMAC_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Operateur_Conv_base.
self_cast() [1/2]
Op_Conv_PolyMAC_base & Op_Conv_PolyMAC_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Op_Conv_PolyMAC_base & Op_Conv_PolyMAC_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Op_Conv_PolyMAC_base::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN A surcharger dans les classes derivees.
Parameters
(Sortie& os) un flot de sortie
Returns
(Sortie&) le flot de sortie
Reimplemented from Operateur_Conv_base.
References Objet_U::que_suis_je().
Referenced by Op_Conv_EF_Stab_PolyMAC_Face::printOn(), Op_Conv_Amont_PolyMAC_Face::printOn(), Op_Conv_Centre_PolyMAC_Face::printOn(), Op_Conv_EF_Stab_PolyMAC_P0_Face::printOn(), Op_Conv_Amont_PolyMAC_P0_Face::printOn(), Op_Conv_Centre_PolyMAC_P0_Face::printOn(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::printOn(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Face::printOn(), Op_Conv_Amont_PolyMAC_P0P1NC_Face::printOn(), and Op_Conv_Centre_PolyMAC_P0P1NC_Face::printOn().
readOn()
Entree & Op_Conv_PolyMAC_base::readOn (Entree & is) override protected virtual
NE FAIT RIEN A surcharger dans les classes derivees.
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree
Reimplemented from Operateur_Conv_base.
Referenced by Op_Conv_EF_Stab_PolyMAC_Face::readOn(), Op_Conv_Amont_PolyMAC_Face::readOn(), Op_Conv_Centre_PolyMAC_Face::readOn(), Op_Conv_Amont_PolyMAC_P0_Face::readOn(), Op_Conv_Centre_PolyMAC_P0_Face::readOn(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::readOn(), Op_Conv_Amont_PolyMAC_P0P1NC_Face::readOn(), and Op_Conv_Centre_PolyMAC_P0P1NC_Face::readOn().
completer()
void Op_Conv_PolyMAC_base::completer () override virtual
Associe l'operateur au domaine_dis, le domaine_Cl_dis, et a l'inconnue de son equation.
Exceptions
pas d'equation associee
Reimplemented from Operateur_base.
References Operateur_base::completer().
Referenced by Op_Conv_EF_Stab_PolyMAC_Face::completer().
calculer_dt_stab()
double Op_Conv_PolyMAC_base::calculer_dt_stab () const override virtual
Calcul dt_stab.
Returns
(double) renvoie toujours 1.e30
Reimplemented from Operateur_base.
calculer()
DoubleTab & Op_Conv_PolyMAC_base::calculer (const DoubleTab & inco, DoubleTab & resu) const inline override virtual
calcule la contribution de la convection, la range dans resu renvoie resu
Reimplemented from Operateur_base.
References Operateur_base::ajouter().
impr()
int Op_Conv_PolyMAC_base::impr (Sortie & os) const override virtual
DOES NOTHING - to override in derived classes.
Imprime l'operateur sur un flot de sortie.
Parameters
(Sortie& os)
Returns
(int) renvoie toujours 1
Reimplemented from Operateur_base.
References Sortie::add_col(), Domaine_base::bords_a_imprimer(), Domaine_base::bords_a_imprimer_sum(), TRUST_List< _CLASSE_ >::contient(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, TRUST_List< _CLASSE_ >::est_vide(), Flux, Operateur_base::flux_bords(), Flux_moment, Flux_sum, Schema_Temps_base::imprimer_temps_courant(), Process::je_suis_maitre(), la_zcl_poly_, le_dom_poly_, Frontiere_dis_base::le_nom(), Domaine_base::moments_a_imprimer(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), Operateur_base::ouvrir_fichier(), Operateur_base::ouvrir_fichier_partage(), EcrFicPartage::syncfile(), and Schema_Temps_base::temps_courant().
associer_domaine_cl_dis()
void Op_Conv_PolyMAC_base::associer_domaine_cl_dis (const Domaine_Cl_dis_base & zcl) override virtual
Reimplemented from Operateur_base.
References la_zcl_poly_.
associer()
void Op_Conv_PolyMAC_base::associer (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & zcl, const Champ_Inc_base &) override virtual
Implements Operateur_base.
References la_zcl_poly_, and le_dom_poly_.
associer_vitesse()
void Op_Conv_PolyMAC_base::associer_vitesse (const Champ_base & ch) override virtual
Implements Operateur_Conv_base.
References vitesse_.
Member Data Documentation
info_obj
const Type_info Op_Conv_PolyMAC_base::info_obj static
le_dom_poly_
TRUST_Ref< Domaine_PolyMAC *> Op_Conv_PolyMAC_base::le_dom_poly_ protected
Referenced by Op_Conv_EF_Stab_PolyMAC_Face::ajouter(), Op_Conv_EF_Stab_PolyMAC_P0_Face::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Face::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::ajouter_blocs(), associer(), Op_Conv_EF_Stab_PolyMAC_P0_Face::calculer_dt_stab(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::calculer_dt_stab(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Face::calculer_dt_stab(), Op_Conv_EF_Stab_PolyMAC_Face::completer(), Op_Conv_EF_Stab_PolyMAC_Face::contribuer_a_avec(), Op_Conv_EF_Stab_PolyMAC_Face::dimensionner(), Op_Conv_EF_Stab_PolyMAC_P0_Face::dimensionner_blocs(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Face::dimensionner_blocs(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::dimensionner_blocs(), impr(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::mettre_a_jour(), and Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::preparer_calcul().
la_zcl_poly_
TRUST_Ref< Domaine_Cl_PolyMAC *> Op_Conv_PolyMAC_base::la_zcl_poly_ protected
Referenced by Op_Conv_EF_Stab_PolyMAC_Face::ajouter(), Op_Conv_EF_Stab_PolyMAC_P0_Face::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Face::ajouter_blocs(), associer(), associer_domaine_cl_dis(), and impr().
vitesse_
TRUST_Ref< Champ_base *> Op_Conv_PolyMAC_base::vitesse_ protected
Referenced by Op_Conv_EF_Stab_PolyMAC_Face::ajouter(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::ajouter_blocs(), associer_vitesse(), Op_Conv_EF_Stab_PolyMAC_P0_Face::calculer_dt_stab(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::calculer_dt_stab(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Face::calculer_dt_stab(), Op_Conv_EF_Stab_PolyMAC_P0_Face::completer(), Op_Conv_EF_Stab_PolyMAC_Face::contribuer_a_avec(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::dimensionner_blocs(), and Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::mettre_a_jour().
Flux
SFichier Op_Conv_PolyMAC_base::Flux mutable protected
Referenced by impr().
Flux_moment
SFichier Op_Conv_PolyMAC_base::Flux_moment protected
Referenced by impr().
Flux_sum
SFichier Op_Conv_PolyMAC_base::Flux_sum protected
Referenced by impr().