TrioCFD: Champs_compris_IJK Class Reference
Champs_compris_IJK Class Reference
#include <Champs_compris_IJK.h>
Public Member Functions
bool has_champ_vectoriel (const Motcle &nom) const
Detailed Description
Note that this class has no member of type "Champs_compris_IJK". This member is kept separate and inserted in Navier_Stokes_FTD_IJK, IJK_Interfaces, etc., because in some cases (typically at the probleme level Probleme_FTD_IJK_base) we do not need the member, just the abstract interface below.
Member Function Documentation
ajoute_champ_vectoriel()
void Champs_compris_IJK::ajoute_champ_vectoriel (const IJK_Field_vector3_double & champ)
References Champs_compris_T< FIELD_TYPE >::ajoute_champ(), Process::exit(), Field_base::get_synonyms(), has_champ_vectoriel(), Field_base::le_nom(), Field_base::nb_comp(), and TRUST_Vector< _CLASSE_ >::size().
Referenced by Postprocessing_IJK::alloc_fields(), Statistiques_dns_ijk_FT::alloc_fields(), Postprocessing_IJK::alloc_velocity_and_co(), Postprocessing_IJK::init_integrated_and_ana(), Navier_Stokes_FTD_IJK::initialise_ijk_fields(), Navier_Stokes_FTD_IJK::initialise_ns_fields(), and IJK_Interfaces::initialize().
has_champ_vectoriel()
bool Champs_compris_IJK::has_champ_vectoriel (const Motcle & nom) const
A vectorial field is considered present in the structure if all its three components are there
References Nom::getString().
Referenced by ajoute_champ_vectoriel(), IJK_Thermal_base::has_champ(), IJK_Ghost_Fluid_Fields::has_champ(), IJK_Interfaces::has_champ_vectoriel(), Navier_Stokes_FTD_IJK::has_champ_vectoriel(), Postprocessing_IJK::has_champ_vectoriel(), and Statistiques_dns_ijk::has_champ_vectoriel().
get_champ_vectoriel()
const IJK_Field_vector3_double & Champs_compris_IJK::get_champ_vectoriel (const Motcle & nom) const
References Nom::getString().
Referenced by IJK_Interfaces::get_IJK_field_vector(), IJK_Thermal_base::get_IJK_field_vector(), Navier_Stokes_FTD_IJK::get_IJK_field_vector(), Postprocessing_IJK::get_IJK_field_vector(), Statistiques_dns_ijk::get_IJK_field_vector(), Statistiques_dns_ijk_FT::get_IJK_field_vector(), and IJK_Ghost_Fluid_Fields::get_IJK_field_vector().
liste_noms_compris_vectoriel()
const Noms Champs_compris_IJK::liste_noms_compris_vectoriel () const
References TRUST_Vector< _CLASSE_ >::add().
Referenced by IJK_Thermal_base::get_IJK_field_vector(), IJK_Ghost_Fluid_Fields::get_IJK_field_vector(), IJK_Thermal_base::get_noms_champs_postraitables(), Postprocessing_IJK::get_noms_champs_postraitables(), Statistiques_dns_ijk::get_noms_champs_postraitables(), IJK_Ghost_Fluid_Fields::get_noms_champs_postraitables(), IJK_Interfaces::get_noms_champs_postraitables(), Navier_Stokes_FTD_IJK::get_noms_champs_postraitables(), IJK_Thermal_base::has_champ(), and IJK_Ghost_Fluid_Fields::has_champ().
liste_noms_compris()
const Noms Champs_compris_IJK::liste_noms_compris () const
References TRUST_Vector< _CLASSE_ >::add(), and Champs_compris_T< FIELD_TYPE >::liste_champs_.
Referenced by IJK_Ghost_Fluid_Fields::get_IJK_field(), IJK_Thermal_base::get_noms_champs_postraitables(), Postprocessing_IJK::get_noms_champs_postraitables(), Statistiques_dns_ijk::get_noms_champs_postraitables(), IJK_Ghost_Fluid_Fields::get_noms_champs_postraitables(), IJK_Interfaces::get_noms_champs_postraitables(), Navier_Stokes_FTD_IJK::get_noms_champs_postraitables(), IJK_Thermal_base::has_champ(), IJK_Ghost_Fluid_Fields::has_champ(), and IJK_Thermal_base::noms_compris().
switch_ft_fields()
void Champs_compris_IJK::switch_ft_fields ()
References Champs_compris_T< FIELD_TYPE >::liste_champs_.
Referenced by IJK_Interfaces::switch_indicatrice_next_old().