TrioCFD: Process Class Reference
Process Class Reference
#include <Process.h>
Static Public Member Functions
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
Elle fournit quelques services de base accessibles de partout dans le code (ces services etaient historiquement des methodes non statiques, depuis que tous ces services sont statiques, cette classe n'a plus vraiment d'autre fonction que de ranger ces methodes quelque part)
See also
Objet_U
Constructor & Destructor Documentation
~Process()
virtual Process::~Process () inline virtual
Member Function Documentation
me()
int Process::me () static
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
References PE_Groups::current_group(), and Comm_Group::rank().
Referenced by Matrice_Grossiere::add_dist_bloc(), Matrice_Grossiere::add_virt_bloc(), Terme_Source_inc_th_VDF_Face::ajouter_blocs(), Terme_Source_inc_VDF_Face::ajouter_blocs(), DP_Impose_PolyMAC_Face::ajouter_blocs(), DP_Impose_VEF_Face::ajouter_blocs(), SETS::assembler(), Assembleur_P_PolyMAC::assembler_mat(), Assembleur_P_PolyMAC_P0::assembler_mat(), Assembleur_P_PolyMAC_P0P1NC::assembler_mat(), Maillage_FT_Disc::calcul_courbure_sommets(), Maillage_FT_Disc::calcul_indicatrice(), Echange_contact_Correlation_VDF::calculer_CL(), Scatter::calculer_espace_distant(), Paroi_std_hyd_VEF::calculer_hyd(), Paroi_std_hyd_VEF::calculer_hyd_BiK(), Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_nut(), Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_uv(), Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_vitesse(), Traitement_particulier_NS_Profils_thermo_VDF::calculer_moyennes_spatiales_thermo(), Traitement_particulier_Solide_canal_VDF::calculer_moyennes_spatiales_thermo(), IJK_Interfaces::calculer_phi_repuls_sommet(), Parcours_interface::calculer_sortie_face_bord(), EcrFicPartageMPIIO::check(), Desc_Structure_FT::check(), Scatter::check_consistancy_remote_items(), Maillage_FT_Disc::check_mesh(), Objet_U_ptr::check_Objet_U_ptr_type(), Maillage_FT_Disc::check_sommets(), EcrFicPartage::close(), Pb_Couple_Rayonnement::completer(), Modele_turbulence_hyd_0_eq_base::completer(), Champ_Gen_de_Champs_Gen::completer(), Champ_Generique_Reduction_0D::completer(), Force_sp::compute_dirac_point_uniX_alongX(), Force_sp::compute_dirac_point_uniX_alongY(), Postprocessing_IJK::compute_extended_pressures(), IJK_One_Dimensional_Subproblems::compute_global_indices(), Scatter::construire_espace_virtuel_traduction(), Domain_Graph::construire_graph_elem_elem(), Scatter::construire_md_vector(), Maillage_FT_Disc::construire_noeuds(), Marching_Cubes::construire_noeuds_et_facettes(), Marching_Cubes::construire_noeuds_uniques(), Maillage_FT_Disc::convertir_numero_distant_local(), Maillage_FT_Disc::copier_sommet(), Maillage_FT_Disc::corriger_proprietaires_facettes(), Maillage_FT_Disc::creer_facettes_virtuelles(), Maillage_FT_Disc::creer_sommets_virtuels(), Maillage_FT_Disc::creer_sommets_virtuels_numowner(), Traitement_particulier_NS_CEG::critere_areva(), Traitement_particulier_NS_CEG::critere_cea_jaea(), Op_Div_VEFP1B_Elem::degres_liberte(), Maillage_FT_IJK::deplacer_sommets(), Domaine_Poly_base::detecter_faces_non_planes(), Remaillage_FT::diviser_grandes_aretes(), Remaillage_FT_IJK::diviser_grandes_aretes(), mon_main::dowork(), Statistiques::dump(), IJK_Interfaces::dumplata_ft_mesh(), IJK_Interfaces::dupliquer_bulle_perio(), Schema_Comm::echange_messages(), Desc_Structure_FT::echanger_elements(), Maillage_FT_Disc::echanger_facettes(), Maillage_FT_Disc::echanger_sommets_PE(), Postraiter_domaine::ecrire(), Format_Post_Med::ecrire_champ_med(), Format_Post_Med::ecrire_domaine_dis(), DomaineCutter_32_64< _SIZE_ >::ecrire_domaines(), Maillage_FT_Disc::ecrire_plot(), EFichier::EFichier(), Schema_Comm::end_comm(), FT_Field::exchange_compo_connexe(), FT_Field::exchange_data(), exit(), Fichier_Lata::Fichier_Lata(), Format_Post_Med::finir(), Modele_Rayonnement_Milieu_Transparent::flux_radiatif(), Transport_Interfaces_FT_Disc::get_champ_post_FT(), Objet_U_ptr::get_Objet_U_ptr_check(), Echange_contact_Correlation_VDF::imprimer(), Echange_contact_Correlation_VEF::imprimer(), Modele_turbulence_hyd_0_eq_base::imprimer(), Matrice_Morse::imprimer_formatte(), Matrice_Morse::imprimer_image(), imprimer_ram_totale(), Echange_contact_Correlation_VEF::init(), Domaine_VF::init_dist_paroi_globale(), Echange_contact_Correlation_VDF::init_tab_echange(), Domaine_VDF::init_virt_e_map(), Domaine_PolyMAC::init_virt_ef_map(), Raccord_distant_homogene_32_64< _SIZE_ >::initialise(), Navier_Stokes_FTD_IJK::initialise_ijk_fields(), Sonde::initialiser(), Echange_contact_PolyMAC::initialiser(), Echange_contact_VDF::initialiser(), Champ_front_lu::initialiser(), Redistribute_Field::initialize(), VDF_to_IJK::initialize(), Domaine_IJK::initialize_mapping(), Domaine_IJK::initialize_with_mapping(), Ecrire::interpreter(), Execute_parallel::interpreter(), MaillerParallel::interpreter(), Raffiner_isotrope_parallele::interpreter(), Extraire_domaine::interpreter_(), Extraire_plan::interpreter_(), SETS::iterer_NS(), Scatter::lire_domaine(), ScatterMED::lire_domaine(), Maillage_FT_IJK::lire_maillage_ft_dans_lata(), Sauvegarde_Reprise_Maillage_FT::lire_xyz(), Remaillage_FT::marquer_aretes(), DP_Impose_PolyMAC_Face::mettre_a_jour(), DP_Impose_VEF_Face::mettre_a_jour(), Champ_Fonc_Interp::mettre_a_jour(), Echange_contact_Correlation_VDF::mettre_a_jour(), Echange_contact_Correlation_VEF::mettre_a_jour(), Assembleur_P_VEF::modifier_matrice(), Assembleur_P_VEFPreP1B::modifier_matrice(), LecFicDistribue::ouvrir(), EcrFicCollecte::ouvrir(), IJK_Thermal_Subresolution::post_processed_fields_on_downstream_line(), Traitement_particulier_NS_canal::post_traitement_particulier(), Sonde::postraiter(), Sonde_Int::postraiter(), Fourier_trans::postraiter(), StatComm::print_stat(), Champ_Don_lu::readOn(), Champ_Fonc_MED::readOn(), Champ_Fonc_reprise::readOn(), Corrige_flux_FT_temperature_subresolution::receive_all_fluxes_from_outisde_frontier_on_procs(), Corrige_flux_FT_temperature_subresolution::receive_fluxes_from_frontier_on_procs(), Corrige_flux_FT_temperature_subresolution::receive_temperature_cell_centre_neighbours_from_procs(), Schema_Comm::recv_buffer(), Desc_Structure_FT::remplir_element_pe(), Connectivite_frontieres::remplir_faces_voisins(), Traitement_particulier_NS_canal::remplir_reordonne_Y_tot(), Reordonner_faces_periodiques_32_64< _SIZE_ >::renum_som_perio(), Scatter::reordonner_faces_de_joint(), Paroi_TBLE_QDM::reprendre(), Paroi_TBLE_QDM_Scal::reprendre(), Ch_front_Vortex::reprendre_vortex(), Paroi_TBLE_QDM::sauvegarder(), Paroi_TBLE_QDM_Scal::sauvegarder(), Ch_front_Vortex::sauvegarder_vortex(), Schema_Comm::send_buffer(), Collision_Model_FT_base::set_LC_zones(), SFichier::SFichier(), IJK_One_Dimensional_Subproblems::share_boundary_previous_values(), IJK_One_Dimensional_Subproblems::share_interfacial_heat_flux_correction_on_procs(), Remaillage_FT::supprimer_petites_aretes(), Remaillage_FT_IJK::supprimer_petites_aretes(), EcrFicPartage::syncfile(), Op_Diff_VEFP1NCP1B_Face::test(), IJK_One_Dimensional_Subproblems::thermal_subresolution_outputs(), IJK_One_Dimensional_Subproblems::thermal_subresolution_outputs_parallel(), Aretes::trier_pour_debog(), DP_Impose::update_dp_regul(), Perte_Charge_Singuliere::update_K(), and Domaine_VEF::verifie_ok_arete().
nproc()
int Process::nproc () static
renvoie le nombre de processeurs dans le groupe courant Voir Comm_Group::nproc() et PE_Groups::current_group()
References PE_Groups::current_group(), and Comm_Group::nproc().
Referenced by IJK_Composantes_Connex::allocate_fields(), Save_Restart::allocation(), Schema_Comm_Vecteurs::begin_init(), Traitement_particulier_NS_THI_VEF::calcul_correlations(), Desc_Structure_FT::calcul_schema_comm(), Traitement_particulier_NS_THI_VDF::calcul_spectre(), Traitement_particulier_NS_THI_VEF::calcul_spectre(), Moyenne_volumique::calculer_convolution(), Scatter::calculer_espace_distant(), Scatter::calculer_espace_distant_elements(), ParoiVDF_TBLE_LRM::calculer_hyd(), ParoiVDF_TBLE_LRM::calculer_hyd_BiK(), Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_nut(), Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_uv(), Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_vitesse(), Traitement_particulier_NS_Profils_thermo_VDF::calculer_moyennes_spatiales_thermo(), Traitement_particulier_Solide_canal_VDF::calculer_moyennes_spatiales_thermo(), IJK_Interfaces::calculer_phi_repuls_sommet(), Desc_Structure_FT::check(), Schema_Comm::check_send_recv_pe_list(), Solv_Cholesky::Cholesky(), IJK_One_Dimensional_Subproblems::complete_boundary_previous_values(), Pb_Couple_Rayonnement::completer(), Raccord_distant_homogene_32_64< _SIZE_ >::completer(), Champ_Generique_Reduction_0D::completer(), IJK_Composantes_Connex::compute_bounding_box_fill_compo_connex(), Corrige_flux_FT_temperature_subresolution::compute_cell_neighbours_faces_indices_to_correct(), IJK_One_Dimensional_Subproblems::compute_global_indices(), Stat_Results::compute_min_max_avg(), Domain_Graph::construire_graph_elem_elem(), Maillage_FT_Disc::construire_noeuds(), Marching_Cubes::construire_noeuds_joints(), Marching_Cubes::construire_noeuds_liste_faces(), Marching_Cubes::construire_noeuds_uniques(), Transport_K_Eps_base::controler_K_Eps(), Transport_K_Omega_base::controler_K_Omega(), Transport_K_ou_Eps_base::controler_variable(), Corriger_frontiere_periodique_32_64< _SIZE_ >::corriger_coordonnees_sommets_perio(), Solv_Petsc::create_solver(), Maillage_FT_Disc::creer_facettes_virtuelles(), Maillage_FT_Disc::creer_sommets_virtuels_numowner(), Traitement_particulier_NS_CEG::critere_cea_jaea(), Maillage_FT_IJK::deplacer_sommets(), Descripteur_FT::Descripteur_FT(), Domaine_Poly_base::detecter_faces_non_planes(), mon_main::dowork(), Statistiques::dump(), IJK_Interfaces::dumplata_ft_mesh(), IJK_Interfaces::dupliquer_bulle_perio(), Maillage_FT_Disc::echanger_facettes(), Postraiter_domaine::ecrire(), Format_Post_Med::ecrire_domaine_med(), DomaineCutter_32_64< _SIZE_ >::ecrire_domaines(), Maillage_FT_Disc::ecrire_plot(), Schema_Comm_Vecteurs::end_init(), exit(), ILU_SP::factorisation(), Ensemble_Lagrange_base::generer_marqueurs_sz(), Parallel_io_parameters::get_nb_writing_processes(), Navier_Stokes_std::impr(), Echange_contact_Correlation_VDF::imprimer(), Echange_contact_Correlation_VEF::imprimer(), Matrice_Morse::imprimer_formatte(), Matrice_Morse::imprimer_image(), Echange_contact_Correlation_VEF::init(), Traitement_particulier_NS_THI_VDF::init_calc_spectre(), Traitement_particulier_NS_THI_VEF::init_calc_spectre(), Domaine_VF::init_dist_paroi_globale(), Champ_Fonc_Interp::init_fields(), mon_main::init_parallel(), Echange_contact_Correlation_VDF::init_tab_echange(), Switch_FT_double::initialise(), Raccord_distant_homogene_32_64< _SIZE_ >::initialise(), Corrige_flux_FT_temperature_subresolution::initialise_any_cell_neighbours_indices_to_correct_on_processors(), Corrige_flux_FT_temperature_subresolution::initialise_cell_neighbours_indices_to_correct(), Navier_Stokes_FTD_IJK::initialise_ijk_fields(), Sonde::initialiser(), Champ_front_calc::initialiser(), VDF_to_IJK::initialize(), Domaine_IJK::initialize_mapping(), Maillage_FT_IJK::initialize_processor_neighbourhood(), Domaine_IJK::initialize_splitting(), Domaine_IJK::initialize_with_mapping(), Ecrire::interpreter(), Execute_parallel::interpreter(), MaillerParallel::interpreter(), Raffiner_isotrope_parallele::interpreter(), Create_domain_from_sub_domain::interpreter_(), Ecrire_Fichier::interpreter_(), is_parallel(), is_sequential(), Traitement_particulier_NS_THI_VEF::isotropie(), Scatter::lire_domaine(), Postraitement_ft_lata::lire_entete_bloc_interface(), LireMED_32_64< _SIZE_ >::lire_geom(), Maillage_FT_IJK::lire_maillage_ft_dans_lata(), Save_Restart::lire_sauvegarde_reprise(), Sauvegarde_Reprise_Maillage_FT::lire_xyz(), Remaillage_FT::marquer_aretes(), Champ_front_recyclage::mettre_a_jour(), Champ_Fonc_Interp::mettre_a_jour(), Echange_contact_Correlation_VDF::mettre_a_jour(), Nom::nom_me(), Descripteur_FT::operator=(), Traitement_particulier_NS_canal::post_traitement_particulier(), Sonde::postraiter(), Sonde_Int::postraiter(), SSOR::prepare_(), TRUST_2_PDI::prepareRestart(), Statistiques::print_communciation_tracking_details(), Domaine_IJK::readOn(), Solv_AMG::readOn(), Champ_Fonc_MED::readOn(), Champ_Fonc_reprise::readOn(), Corrige_flux_FT_temperature_subresolution::receive_all_fluxes_from_outisde_frontier_on_procs(), Corrige_flux_FT_temperature_subresolution::receive_fluxes_from_frontier_on_procs(), Corrige_flux_FT_temperature_subresolution::receive_temperature_cell_centre_neighbours_from_procs(), IJK_Interfaces::recursive_calcul_distance_chez_voisin(), Marching_Cubes::remplir_renum_virt_loc(), Traitement_particulier_NS_canal::remplir_reordonne_Y_tot(), Navier_Stokes_std_ALE::reprendre(), Ch_front_Vortex::reprendre_vortex(), Navier_Stokes_std_ALE::sauvegarder(), Ch_front_Vortex::sauvegarder_vortex(), Save_Restart::sauver(), Schema_Comm::Schema_Comm(), IJK_One_Dimensional_Subproblems::share_boundary_previous_values(), IJK_One_Dimensional_Subproblems::share_interfacial_heat_flux_correction_on_procs(), Corrige_flux_FT_temperature_subresolution::sort_ijk_intersections_subproblems_indices_fluxes_by_k_layers(), Corrige_flux_FT_temperature_subresolution::store_any_cell_faces_corrected(), EcrFicPartage::syncfile(), and IJK_One_Dimensional_Subproblems::thermal_subresolution_outputs().
is_parallel()
bool Process::is_parallel () static
References nproc().
Referenced by MD_Vector_composite::add_part(), Ecrire_YAML::add_pb_base(), Assembleur_P_VEFPreP1B::assembler_mat(), Op_Conv_kschemas_VEF::associer(), Echange_contact_Correlation_VDF::calculer_CL(), Reordonner_faces_periodiques_32_64< _SIZE_ >::check_faces_periodiques(), Domain_Graph::construire_graph_elem_elem(), Partitionneur_base_32_64< _SIZE_ >::corriger_bords_avec_graphe(), Solv_Petsc::create_solver(), Op_Div_VEFP1B_Elem::degres_liberte(), mon_main::dowork(), Statistiques::dump(), Format_Post_Lata::ecrire_domaine_low_level(), exit(), Domaine_bord_32_64< _SIZE_ >::extraire_domaine_bord(), Domaine_32_64< _SIZE_ >::fill_from_list(), Champ_front_contact_VEF::initialiser(), Link_CGNS_Files::interpreter(), Dilate::interpreter_(), Distanceparoi::interpreter_(), Mailler_32_64< _SIZE_ >::interpreter_(), Polyedriser_32_64< _SIZE_ >::interpreter_(), Redresser_hexaedres_vdf::interpreter_(), Triangulation_base::interpreter_(), VerifierCoin::interpreter_(), Matrice_Morse::inverse(), Partitionneur_Metis_32_64< _SIZE_ >::lire_motcle_non_standard(), Echange_contact_Correlation_VEF::mettre_a_jour(), LecFicDistribue::ouvrir(), EcrFicCollecte::ouvrir(), Precond_local::precond(), Sous_Domaine_32_64< _SIZE_ >::readOn(), Solv_AMG::readOn(), Solv_Cholesky::readOn(), Champ_Fonc_MED::readOn(), Champ_front_contact_VEF::readOn(), Reordonner_faces_periodiques_32_64< _SIZE_ >::renum_som_perio(), Convection_Diffusion_Fluide_Dilatable_Proto::Reprendre_WC(), Solv_Gmres::resoudre_systeme(), Convection_Diffusion_Fluide_Dilatable_Proto::Sauvegarder_WC(), Fichier_Lata::syncfile(), Op_Diff_VEFP1NCP1B_Face::test(), Champ_front_contact_VEF::trace_face_raccord(), Debog_Pb::write_geometry_data(), and Matrice_Morse::WriteFileMTX().
exit() [1/2]
void Process::exit (int i = -1) static
Routine de sortie de TRUST dans une region Kokkos.
Routine de sortie de TRUST sur une erreur.
Sauvegarde la memoire et de la hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump"
References exit(), EChaineJDD::file_cur_line_, Nom::getString(), and Objet_U::nom_du_cas().
Referenced by Modele_turbulence_hyd_0_eq_base::a_pour_Champ_Fonc(), abort(), Memoire::add(), Liste_bloc::add_deplace(), Ecrire_YAML::add_field(), MD_Vector_composite::add_part(), Ecrire_YAML::add_scalar(), IJK_Thermal_base::add_temperature_source(), DeviceMemory::addrOnDevice(), Parser::addVar(), Champ_Face_VDF::affecter(), Champ_Inc_base::affecter_(), Champ_Uniforme::affecter_(), Champ_Uniforme_Morceaux::affecter_(), Champ_Front_Fonction::affecter_(), Champ_base::affecter_erreur(), PDF_model::affecter_variable_imposee(), Champs_compris_T< FIELD_TYPE >::ajoute_champ(), Champs_compris_IJK::ajoute_champ_vectoriel(), Op_Diff_VDF_base::ajoute_terme_pour_axi(), Op_Dift_VDF_base::ajoute_terme_pour_axi_turb(), Operateur_base::ajouter(), Operateur_Conv_sensibility_VEF::ajouter(), Op_Diff_EF::ajouter(), Op_Dift_EF_Q1::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Centre_EF_VEF_Face::ajouter(), Op_Curl_VEFP1B::ajouter(), Op_Rot_VEFP1B::ajouter(), Operateur_Grad_base::ajouter(), Domaine_32_64< _SIZE_ >::ajouter(), Interprete_bloc::ajouter(), Source_base::ajouter(), Source_Portance::ajouter(), Terme_Boussinesq_Sensibility_VEFPreP1B_Face::ajouter(), Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::ajouter(), Source_Transport_Flux_Chaleur_Turbulente_VDF_Face::ajouter(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_VEF_Face::ajouter(), Source_Transport_K_Eps_Bas_Reynolds_VEF_Face::ajouter(), Iterateur_Source_EF_Som< _TYPE_ >::ajouter(), Perte_Charge_Reguliere_VEF_P1NC::ajouter(), Terme_Source_Th_TdivU_VEF_Face::ajouter(), Probleme_Couple::ajouter(), Perte_Charge_Reguliere_VDF_Face::ajouter_(), Source_PDF_EF::ajouter_(), Terme_Source_Qdm_VDF_Face::ajouter_blocs(), Operateur_base::ajouter_blocs(), Source_base::ajouter_blocs(), Diffusion_supplementaire_echelle_temp_turb_PolyMAC_P0::ajouter_blocs(), Dissipation_WIT_PolyMAC_P0::ajouter_blocs(), Production_echelle_temp_taux_diss_turb_PolyMAC_P0::ajouter_blocs(), Production_energie_cin_turb_PolyMAC_P0::ajouter_blocs(), Production_WIT_PolyMAC_P0::ajouter_blocs(), Source_BIF_PolyMAC_P0::ajouter_blocs(), Diffusion_croisee_echelle_temp_taux_diss_turb_VDF::ajouter_blocs(), Production_echelle_temp_taux_diss_turb_VDF::ajouter_blocs(), Dispersion_bulles_PolyMAC_P0::ajouter_blocs(), Frottement_interfacial_PolyMAC_P0::ajouter_blocs(), Dispersion_bulles_VDF::ajouter_blocs(), Frottement_interfacial_VDF::ajouter_blocs(), Portance_interfaciale_VDF::ajouter_blocs(), Solveur_Masse_base::ajouter_blocs(), Correction_Lubchenko_PolyMAC_P0::ajouter_blocs_BIF(), Op_Dift_EF_Q1::ajouter_bords(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_vectoriel(), Op_Conv_EF_VEF_P1NC::ajouter_contribution(), Operateur_base::ajouter_flux(), Source_Fluide_Dilatable_VEF_Proto::ajouter_impl(), Schema_Euler_Implicite_Stationnaire::ajouter_inertie(), Operateur_Conv_sensibility_VEF::ajouter_Lsensibility_state_Amont(), Operateur_Conv_sensibility_VEF::ajouter_Lstate_sensibility_Amont(), Maillage_FT_IJK::ajouter_maillage(), Matrice_Morse_Diag::ajouter_multTab_(), Matrice_Bloc::ajouter_multTab_(), Matrice_Petsc::ajouter_multTab_(), Matrice_Bloc_Sym::ajouter_multTab_(), Matrice_Petsc::ajouter_multvect_(), Matrice_Morse_Diag::ajouter_multvectT_(), Matrice_Morse_Sym::ajouter_multvectT_(), Matrice_Petsc::ajouter_multvectT_(), Matrice_Bloc_Sym::ajouter_multvectT_(), Synonyme_info::ajouter_synonyme(), Op_Conv_ALE_VDF::ajouterALE(), Postprocessing_IJK::alloc_fields(), Save_Restart::allocation(), QDM_Multiphase::alpha_res(), Operateur_Evanescence_base::alpha_res(), Op_Conv_ALE_VEF::application_LIMITEUR(), Operateur_Conv_sensibility_VEF::application_LIMITEUR(), Solveur_Masse_EF::appliquer_impl(), Masse_PolyMAC_Elem::appliquer_impl(), Masse_PolyMAC_Face::appliquer_impl(), Masse_VDF_Elem::appliquer_impl(), Masse_VDF_Face::appliquer_impl(), Masse_VEF_P1NC::appliquer_impl(), Equation_base::assembler(), Convection_Diffusion_Espece_Multi_QC::assembler(), Convection_Diffusion_Temperature::assembler(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_blocs(), Assembleur_base::assembler_continuite(), Equation_IBM_proto::assembler_ibm_proto(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_impl(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_impl(), Assembleur_base::assembler_mat(), Assembleur_P_VEFPreP1B::assembler_mat(), Eq_rayo_semi_transp_VDF::assembler_matrice(), Eq_rayo_semi_transp_VEF::assembler_matrice(), Source_Con_Phase_field::assembler_matrice_point_fixe(), Simpler_Base::assembler_matrice_pression_implicite(), Assembleur_base::assembler_QC(), AssembleurPVDF_PF::assembler_QC(), Assembleur_P_VDF::assembler_QC(), Assembleur_P_VEFPreP1B::assembler_rho_variable(), Assembleur_base::assembler_rho_variable(), Assembleur_P_EF::assembler_rho_variable(), Matrice_Bloc::assert_check_block_matrix_structure(), Matrice_Morse::assert_check_morse_matrix_structure(), Matrice_Morse::assert_check_sorted_morse_matrix_structure(), Matrice_Morse_Sym::assert_check_sorted_symmetric_morse_matrix_structure(), Matrice_Bloc_Sym::assert_check_symmetric_block_matrix_structure(), Matrice_Morse_Sym::assert_check_symmetric_morse_matrix_structure(), Convection_Diffusion_Temperature_sensibility::associate_evaluator_field(), Navier_Stokes_std_sensibility::associate_evaluator_field(), Corrige_flux_FT_temperature_subresolution::associate_indices_and_check_subproblems_consistency(), IJK_One_Dimensional_Subproblems::associate_sub_problem_to_inputs(), Eval_Diff_VDF_Elem_aniso::associer(), Op_Correlation::associer(), Op_Conv_kschemas_VEF::associer(), Op_Diff_VEFP1NCP1B_Face::associer(), Probleme_base::associer_(), Champ_front_recyclage::associer_champ_evaluateur(), Support_Champ_Masse_Volumique::associer_champ_masse_volumique(), Source_base::associer_champ_rho(), Terme_Source_Acceleration_VDF_Face::associer_champ_rho(), Terme_Source_Acceleration_VEF_Face::associer_champ_rho(), Iterateur_VDF_base::associer_correlation_flux_parietal(), Op_Diff_K_Omega_VDF_base::associer_diffusivite_turbulente(), Operateur_base::associer_domaine_cl_dis(), Parcours_interface::associer_domaine_dis(), Champ_base::associer_domaine_dis_base(), Traitement_particulier_NS_Profils_thermo_VDF::associer_eqn(), Milieu_base::associer_equation(), Champ_front_contact_VEF::associer_front_vf_et_ch_front_autre_pb(), Milieu_base::associer_gravite(), Ensemble_Faces_base::associer_les_cl(), IJK_Thermal_base::associer_milieu_base(), Pb_Hydraulique_ALE::associer_milieu_base(), Pb_Hydraulique_Turbulent_ALE::associer_milieu_base(), IJK_Thermals::associer_milieu_base(), Navier_Stokes_FTD_IJK::associer_milieu_base(), Pb_Phase_field::associer_milieu_base(), Pb_Hydraulique_Aposteriori::associer_milieu_base(), Equation_rayonnement_base::associer_milieu_base(), Pb_Hydraulique_sensibility::associer_milieu_base(), Pb_Thermohydraulique_sensibility::associer_milieu_base(), Pb_QC_base::associer_milieu_base(), Pb_WC_base::associer_milieu_base(), Pb_Hydraulique_IBM::associer_milieu_base(), Pb_Hydraulique_IBM_Turbulent::associer_milieu_base(), Pb_Thermohydraulique_IBM_Turbulent::associer_milieu_base(), Convection_Diffusion_Temperature::associer_milieu_base(), Convection_Diffusion_Temperature_base::associer_milieu_base(), Navier_Stokes_std::associer_milieu_base(), Pb_Hydraulique::associer_milieu_base(), Pb_Hydraulique_Concentration::associer_milieu_base(), Pb_Hydraulique_Concentration_Turbulent::associer_milieu_base(), Pb_Hydraulique_Turbulent::associer_milieu_base(), Pb_Thermohydraulique_Concentration_Turbulent::associer_milieu_base(), Pb_Thermohydraulique_Turbulent::associer_milieu_base(), Convection_Diffusion_Temperature_FT_Disc::associer_milieu_base(), Op_Correlation::associer_op_stat(), Source_Con_Phase_field::associer_pb(), Source_Qdm_VDF_Phase_field::associer_pb(), Tenseur_Reynolds_Externe_VDF_Face::associer_pb(), Perte_Charge_PolyMAC_Face::associer_pb(), Source_QC_QDM_Gen::associer_pb(), Perte_Charge_VDF_Face::associer_pb(), Source_Echange_Th_VDF::associer_pb(), Terme_Source_Coriolis_VDF_Face::associer_pb(), Terme_Source_inc_th_VDF_Face::associer_pb(), Terme_Source_inc_VDF_Face::associer_pb(), Perte_Charge_VEF_Face::associer_pb(), Terme_Source_Qdm_lambdaup_VEF_Face::associer_pb(), Terme_Source_Th_TdivU_VEF_Face::associer_pb(), Terme_Boussinesq_base::associer_pb(), Loi_Fermeture_base::associer_pb_base(), IJK_Interfaces::associer_pb_base(), IJK_Thermals::associer_pb_base(), Navier_Stokes_FTD_IJK::associer_pb_base(), Navier_Stokes_FT_Disc::associer_pb_base(), Transport_Interfaces_FT_Disc::associer_pb_base(), Sonde::associer_post(), Sonde_Int::associer_post(), Probleme_base::associer_sch_tps_base(), Pb_Hydraulique_ALE::associer_sch_tps_base(), Pb_Hydraulique_Turbulent_ALE::associer_sch_tps_base(), Pb_Dilatable_base::associer_sch_tps_base(), Pb_Couple_rayo_semi_transp::associer_sch_tps_base(), Schema_Explicite_Multi_TimeStep_base::authorized_equation(), Schema_Implicite_Multi_TimeStep_base::authorized_equation(), Op_Diff_VEF_Face_Penalise::autre_face(), Champ_front_base::avancer(), Champ_front_instationnaire_base::avancer(), Champ_front_var_instationnaire::avancer(), FT_Field::avancer_en_temps(), Comm_Group_MPI::barrier(), Schema_Comm_Vecteurs::begin_comm(), Matrice_Bloc_Sym::BlocSymToMatMorseSym(), Domaine_VF::build_map_mc_Cmesh(), Domaine_VF::build_mc_face_mesh(), Domaine_DG::build_nfaces_elem_(), Matrice_Base::build_stencil(), Op_Evanescence_Homogene_Face_base::calc_grad_alpha_faces(), Loi_paroi_adaptative::calc_y_plus(), Loi_paroi_Ramstorfer::calc_y_plus(), Loi_paroi_log::calc_y_plus(), Maillage_FT_Disc::calcul_courbure_sommets(), Champ_Face_VDF::calcul_critere_Q(), Modele_Jones_Launder_VDF::Calcul_D(), Modele_Jones_Launder_VDF::Calcul_D_BiK(), Modele_Jones_Launder_VDF::calcul_derivees_premieres_croisees(), Champ_Face_VDF::calcul_duidxj(), Couplage_Tubes_IBC::calcul_F_pression(), Couplage_Tubes_IBC::calcul_force_post_projection(), Convection_Diffusion_Temperature::calcul_indic_pena_global(), Transport_Interfaces_FT_Disc::calcul_indicatrice_faces(), Parcours_interface::calcul_intersection_facelem_2D(), Parcours_interface::calcul_intersection_facelem_3D(), Parcours_interface::calcul_inverse_matrice33(), Champ_front_recyclage::calcul_moyenne_imposee(), Champ_front_recyclage::calcul_moyenne_recyclee(), Transport_Interfaces_FT_Disc::calcul_nb_traverse(), Intersection_Interface_ijk_face::calcul_projection_bary_face_mouillee_interface_moy(), Reaction::calcul_proportion_implicite(), Traitement_particulier_NS_canal::calcul_reynolds_tau(), Transport_Interfaces_FT_Disc::calcul_source(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calcul_tableaux_correspondance(), Modele_turbulence_scal_LES_dyn_VDF::calcul_tableaux_correspondance(), Traitement_particulier_NS_temperature_VEF::calcul_temperature(), Modele_Fonc_Bas_Reynolds_Base::calcul_tenseur_Re(), Modele_Fonc_Bas_Reynolds_Base::calcul_tenseur_Re_BiK(), Transport_Interfaces_FT_Disc::calcul_vitesse(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calcul_voisins(), Champ_P1NC::calcul_y_plus(), Champ_P1NC::calcul_y_plus_diphasique(), Champ_Face_VDF::calcul_y_plus_diphasique(), Fluide_Diphasique_IJK::calculate_direction_gravite(), Fluide_reel_base::calculate_fluid_properties_enthalpie(), Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_semi_lagrangien_interpolate(), Domaine_EF::calculer_Bij(), Aretes::calculer_centre_de_gravite(), Source_Con_Phase_field::calculer_champ_fonc_c(), Echange_contact_Correlation_VDF::calculer_CL(), Echange_contact_Correlation_VEF::calculer_CL(), Op_Grad_VEF_P1B_Face::calculer_coef_som(), Moyenne_volumique::calculer_convolution_champ_face(), Switch_double::calculer_coords_Vi(), Maillage_FT_Disc::calculer_costheta_minmax(), Navier_Stokes_FT_Disc::calculer_delta_u_interface(), Champ_Face_VDF::calculer_dercov_axi(), DNS_QC_double::calculer_diffusion_scalar(), Modele_turbulence_scal_Schmidt::calculer_diffusion_turbulente(), Modele_turbulence_scal_Fluctuation_Temperature::calculer_diffusivite_turbulente(), Modele_turbulence_scal_Fluctuation_Temperature_W::calculer_diffusivite_turbulente(), Modele_turbulence_scal_Prandtl::calculer_diffusivite_turbulente(), Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re::calculer_diffusivite_turbulente(), IJK_Thermal_base::calculer_dT(), Operateur_base::calculer_dt_local(), Op_Conv_EF::calculer_dt_stab(), Op_Diff_PolyMAC_P0_Elem::calculer_dt_stab(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab_aretes(), Navier_Stokes_FTD_IJK::calculer_dv(), Traitement_particulier_NS_EC::calculer_Ec(), Modele_turbulence_hyd_LES_VDF::calculer_energie_cinetique_turb(), Modele_turbulence_hyd_LES_base::calculer_energie_cinetique_turb(), Modele_turbulence_hyd_Longueur_Melange_VEF::calculer_f_amortissement(), Iterateur_PolyMAC_base::calculer_flux_bord(), Iterateur_PolyMAC_Elem< _TYPE_ >::calculer_flux_bord(), Op_Diff_VEFP1NCP1B_Face::calculer_flux_bords_aretes(), Modele_rayo_semi_transp::calculer_flux_radiatif(), Flux_radiatif_VDF::calculer_flux_radiatif(), Flux_radiatif_VEF::calculer_flux_radiatif(), Modele_turbulence_hyd_LES_VDF::calculer_fonction_structure(), Modele_turbulence_hyd_LES_VEF::calculer_fonction_structure(), Modele_turbulence_hyd_LES_axi_VDF::calculer_fonction_structure(), Terme_Source_Coriolis_VDF_Face::calculer_force_de_Coriolis(), Navier_Stokes_FT_Disc::calculer_gradient_indicatrice(), Echange_contact_VDF::calculer_h_autre_pb(), Paroi_std_hyd_VEF::calculer_hyd(), Paroi_negligeable_VEF::calculer_hyd(), Paroi_std_hyd_VDF_diphasique::calculer_hyd(), Paroi_std_hyd_VEF_diphasique::calculer_hyd(), Paroi_loi_WW_hyd_EF::calculer_hyd(), Paroi_std_hyd_EF::calculer_hyd(), Paroi_2couches_VDF::calculer_hyd(), Paroi_loi_Ciofalo_hyd_VDF::calculer_hyd(), Paroi_loi_WW_hyd_VDF::calculer_hyd(), ParoiVDF_TBLE_LRM::calculer_hyd(), Paroi_loi_WW_hyd_VEF::calculer_hyd(), Paroi_std_hyd_VDF::calculer_hyd(), Paroi_UTAU_IMP_VDF::calculer_hyd(), ParoiVDF_TBLE::calculer_hyd(), ParoiVEF_TBLE::calculer_hyd(), Paroi_std_hyd_VDF::calculer_hyd_BiK(), Paroi_UTAU_IMP_VDF::calculer_hyd_BiK(), ParoiVDF_TBLE::calculer_hyd_BiK(), ParoiVDF_TBLE_LRM::calculer_hyd_BiK(), Paroi_std_hyd_VEF::calculer_hyd_BiK(), ParoiVEF_TBLE::calculer_hyd_BiK(), IJK_Interfaces::calculer_indicatrice_optim(), IJK_Interfaces::calculer_indicatrices(), Champ_P1NC::calculer_integrale_volumique(), Assembleur_P_VEF::calculer_inv_volume(), Loi_Etat_GP_base::calculer_lambda(), Paroi_std_hyd_VDF::calculer_local(), Remaillage_FT::calculer_longueurIdeale2_arete(), Remaillage_FT_IJK::calculer_longueurIdeale2_arete(), Modele_turbulence_hyd_LES_VDF_base::calculer_longueurs_caracteristiques(), Loi_Etat_Multi_GP_QC::calculer_masse_molaire(), Loi_Etat_Multi_GP_base::calculer_masse_volumique(), Modele_turbulence_hyd_LES_DSGS_VDF::calculer_Mij(), Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_vitesse_rho_mu(), ComputeValParCompoInCell::calculer_moyennes_interface_element_pour_compo(), Paroi_std_hyd_VDF::calculer_moyennes_parois(), Loi_Etat_base::calculer_mu(), Loi_Etat_Binaire_GP_base::calculer_mu(), Loi_Etat_Binaire_GP_base::calculer_mu_sur_Sc(), Loi_Etat_Multi_GP_WC::calculer_mu_sur_Sc(), Faces_VDF::calculer_orientation(), Equation_base::calculer_pas_de_temps_locaux(), MorEqn::calculer_pour_post(), Operateur_base::calculer_pour_post(), Op_Conv_EF_base::calculer_pour_post(), Navier_Stokes_std::calculer_pression_hydrostatique(), Transport_Marqueur_FT::calculer_proprietes_fluide_pos_particules(), Paroi_std_scal_hyd_EF::calculer_scal(), Loi_Paroi_Nu_Impose_VDF::calculer_scal(), Paroi_loi_WW_scal_VDF::calculer_scal(), Paroi_ODVM_scal_VDF::calculer_scal(), Paroi_std_scal_hyd_VDF::calculer_scal(), Paroi_TBLE_scal_VDF::calculer_scal(), Loi_Paroi_Nu_Impose_VEF::calculer_scal(), Paroi_loi_WW_scal_VEF::calculer_scal(), Paroi_scal_analytique_VEF::calculer_scal(), Paroi_std_scal_hyd_VEF::calculer_scal(), Transport_Interfaces_FT_Disc::calculer_scalaire_interpole(), Parcours_interface::calculer_sortie_face_bord(), Calcul_Production_K_VEF::calculer_terme_destruction_K_gen(), Calcul_Production_K_VEF::calculer_terme_production_K_EASM(), Eval_Puiss_Th_EF::calculer_terme_source(), Eval_Puiss_Th_QC_EF::calculer_terme_source(), Evaluateur_Source::calculer_terme_source(), Eval_Dirac_VEF_Face::calculer_terme_source(), Evaluateur_Source_Face::calculer_terme_source_bord(), Evaluateur_Source_VEF_Face::calculer_terme_source_non_standard(), Evaluateur_Source_VEF_Face::calculer_terme_source_standard(), Echange_contact_ODVM_VDF::calculer_Teta_equiv(), Echange_contact_Rayo_transp_VDF::calculer_Teta_equiv(), Paroi_flux_impose_Rayo_transp::calculer_Teta_i_VDF(), Echange_contact_Rayo_transp_VDF::calculer_Teta_paroi(), Echange_contact_rayo_semi_transp_VDF::calculer_Teta_paroi(), DNS_QC_double::calculer_turbulent_diffusion_vitesse(), Paroi_std_hyd_VDF::calculer_u_star(), Op_Ecart_type::calculer_valeurs(), Marqueur_FT::calculer_valeurs_champs(), Champ_base::calculer_valeurs_som_post(), Modele_turbulence_hyd_LES_axi_VDF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_DSGS_VDF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_VDF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_1elt_VEF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_Fst_VEF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_VEF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_combinaison::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_Smago_VDF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_Wale_VDF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_Longueur_Melange_VDF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_Smago_VEF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_Wale_VEF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_Longueur_Melange_VEF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_K_Eps::calculer_viscosite_turbulente(), Modele_turbulence_hyd_K_Eps_2_Couches::calculer_viscosite_turbulente(), Modele_turbulence_hyd_K_Eps_Bas_Reynolds::calculer_viscosite_turbulente(), Modele_turbulence_hyd_K_Eps_Bicephale::calculer_viscosite_turbulente(), Modele_turbulence_hyd_K_Eps_Realisable::calculer_viscosite_turbulente(), Modele_turbulence_hyd_K_Eps_Realisable_Bicephale::calculer_viscosite_turbulente(), Modele_turbulence_hyd_K_Omega::calculer_viscosite_turbulente(), Domaine_ALE::calculer_vitesse(), Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl(), Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl_u_star(), Transport_Interfaces_FT_Disc::calculer_vitesse_transport_interpolee(), Rectangle_32_64< _SIZE_ >::calculer_volumes(), Discretisation_tools::cells_to_faces(), Fluide_Diphasique::chaleur_latente(), Echange_global_impose::champ_exterieur(), Champ_Generique_erreur::Champ_Generique_erreur(), EcrFicPartageMPIIO::check(), Desc_Structure_FT::check(), Terme_Boussinesq_base::check(), Schema_Comm_Vecteurs::check_buffers_full(), Rectify_Mesh::check_cell_type(), Refine_Mesh::check_cell_type(), Rectify_Mesh::check_dimension(), Refine_Mesh::check_dimension(), Milieu_base::check_gravity_vector(), check_int_overflow(), Maillage_FT_Disc::check_mesh(), Maillage_FT_IJK::check_mesh(), MorEqn::check_multiphase_compatibility(), Objet_U_ptr::check_Objet_U_ptr_type(), Schema_Comm::check_send_recv_pe_list(), Maillage_FT_Disc::check_sommets(), Maillage_FT_IJK::check_sommets(), Fluide_Dilatable_base::checkTraitementPth(), Fluide_Weakly_Compressible::checkTraitementPth(), Postraitement::cherche_stat_dans_les_sources(), Partitionneur_Tranche_32_64< _SIZE_ >::chercher_direction_perio(), Domaine_32_64< _SIZE_ >::chercher_elements(), Solv_Cholesky::Cholesky(), Matrice_Base::clean(), EcrFicPartage::close(), Transport_Interfaces_FT_Disc_interne::close_save_file(), Matrice_Diagonale::coeff(), Masse_ajoutee_base::coefficient(), Portance_interfaciale_Sugrue_Modifiee::coefficient(), Op_Diff_VEF_Face_Penalise::coefficient_penalisation(), Comm_Group::Comm_Group(), Memoire::compacte(), Matrice_Morse::compacte(), Cond_lim_base::compatible_avec_eqn(), Cond_lim_utilisateur_base::compatible_avec_eqn(), Frontiere_ouverte_rho_u_impose::compatible_avec_eqn(), Paroi_contact::complement(), Paroi_contact_fictif_rayo::complement(), Paroi_contact_rayo::complement(), Proprietes_part_vol::completer(), Triple_Line_Model_FT_Disc::completer(), Cond_Lim_Rayo::completer(), Pb_Couple_Rayonnement::completer(), Equation_base::completer(), Source_Masse_Fluide_Dilatable_base::completer(), Flux_interfacial_constant_Nu::completer(), Frottement_interfacial_Tomiyama_complet::completer(), Vitesse_derive_Spelt_Biesheuvel::completer(), Correction_Lubchenko_PolyMAC_P0::completer(), Cond_lim_k_complique_transition_flux_nul_demi::completer(), Cond_lim_k_simple_flux_nul::completer(), Cond_lim_omega_demi::completer(), Cond_lim_omega_dix::completer(), Paroi_frottante_loi::completer(), Paroi_frottante_simple::completer(), Loi_paroi_Ramstorfer::completer(), Viscosite_turbulente_k_omega::completer(), Source_Dissipation_energie_cin_turb::completer(), Production_energie_cin_turb_VDF::completer(), Navier_Stokes_FTD_IJK::completer(), Convection_Diffusion_Temperature_FT_Disc::completer(), Source_Portance::completer(), Op_Diff_K_Omega_VDF_base::completer(), Op_Diff_DG_Elem::completer(), Op_Dift_EF_base::completer(), Champ_front_calc_interne::completer(), Periodique::completer(), Correction_Antal_PolyMAC_P0::completer(), Correction_Tomiyama_PolyMAC_P0::completer(), Op_Conv_EF_Stab_PolyMAC_Face::completer(), Op_Diff_PolyMAC_P0_base::completer(), Op_Diff_PolyMAC_P0P1NC_base::completer(), Op_Diff_PolyMAC_Elem::completer(), Op_Diff_PolyMAC_Face::completer(), Op_Diff_PolyMAC_P0_Elem::completer(), Op_Diff_PolyMAC_P0_Face::completer(), Op_Diff_PolyMAC_P0P1NC_Elem::completer(), Op_Diff_PolyMAC_P0P1NC_Face::completer(), Op_Grad_PolyMAC_P0_Face::completer(), Masse_PolyMAC_base::completer(), Navier_Stokes_Fluide_Dilatable_base::completer(), Terme_Source_Canal_perio::completer(), Flux_interfacial_Chen_Mayinger::completer(), Flux_interfacial_Kim_Park::completer(), Flux_interfacial_Ranz_Marshall::completer(), Flux_interfacial_Wolfert::completer(), Flux_interfacial_Wolfert_composant::completer(), Flux_interfacial_Zeitoun::completer(), Frottement_interfacial_bulles_constant::completer(), Frottement_interfacial_Ishii_Zuber::completer(), Frottement_interfacial_Tomiyama::completer(), Vitesse_derive_Forces::completer(), Source_Flux_interfacial_base::completer(), Source_Portance_interfaciale_base::completer(), Loi_paroi_base::completer(), Correction_Antal_VDF::completer(), EDO_Pression_th_VEF::completer(), Op_Conv_EF_VEF_P1NC_Stab::completer(), Op_Dift_VEF_base::completer(), Perte_Charge_VEF::completer(), Terme_Source_Rappel_T_VEF_Face::completer(), Domaine_Cl_EF::completer(), Domaine_Cl_VDF::completer(), Domaine_Cl_VEF::completer(), Reaction::completer(), Champ_Generique_Correlation::completer(), Champ_Generique_Ecart_Type::completer(), Champ_Generique_Extraction::completer(), Champ_Generique_Gradient::completer(), Champ_Generique_Interpolation::completer(), Champ_Generique_Morceau_Equation::completer(), Champ_Generique_Reduction_0D::completer(), Champ_Generique_Transformation::completer(), Champ_Post_Operateur_Eqn::completer(), Fluide_Quasi_Compressible::completer(), Fluide_Weakly_Compressible::completer(), Chimie::completer(), FT_Field::completer_compo_connexe_partielle(), Statistiques_dns_ijk::completer_read(), Champ_Generique_base::composante(), Pb_MED::comprend_champ(), Modele_turbulence_hyd_0_eq_base::comprend_champ(), Joints_32_64< _SIZE_ >::comprimer(), Triple_Line_Model_FT_Disc::compute_approximate_interface_inout(), Statistiques::compute_avg_min_max_var_per_step(), Source_PDF_EF::compute_coeff_elem(), Source_PDF_EF::compute_coeff_matrice(), Collision_Model_FT_base::compute_contact_force(), OpConvQuickIJKScalar_cut_cell_double::compute_cut_cell_divergence(), Statistiques_dns_ijk_FT::compute_desequil_alpha(), IJK_Thermal_Onefluid::compute_dT_rustine(), IJK_Interfaces::compute_external_forces_color_function(), Collision_Model_FT_base::compute_fictive_wall_coordinates(), IJK_Thermal_cut_cell::compute_global_energy(), Post_Processing_Hydrodynamic_Forces::compute_hydrodynamic_forces(), IJK_Thermal_cut_cell::compute_interfacial_temperature2(), Collision_Model_FT_arbitrary::compute_lagrangian_contact_forces(), Collision_Model_FT_spheroid::compute_lagrangian_contact_forces(), Paroi_std_hyd_VDF::compute_law_komega(), MD_Vector_tools::compute_sequential_items_index(), Triple_Line_Model_FT_Disc::compute_TCL_fluxes_in_all_boundary_cells(), Structural_dynamic_mesh_model::computeCriticalDt(), Interpolation_IBM_elem_fluid::computeFluidElems(), Structural_dynamic_mesh_model::computeInternalForces(), Interpolation_IBM_mean_gradient_proto::computeSommetsVoisins(), Champ_front_fonc_gradient::condition_limite(), Domaine_Cl_dis_base::condition_limite_de_la_frontiere(), Solv_Petsc::config(), Champ_front_contact_VEF::connectivity_failed(), Convection_Diffusion_Concentration::constituant(), Octree_32_64< _SIZE_ >::construire(), Scatter::construire_espace_virtuel_traduction(), Domain_Graph::construire_graph_elem_elem(), Marching_Cubes::construire_iso(), Maillage_FT_Disc::construire_noeuds(), Partitionneur_Metis_32_64< _SIZE_ >::construire_partition(), Partitionneur_Fichier_Decoupage::construire_partition(), Partitionneur_Fichier_MED::construire_partition(), Partitionneur_Parmetis::construire_partition(), Partitionneur_Partition::construire_partition(), Partitionneur_Ptscotch::construire_partition(), Partitionneur_Sous_Domaine::construire_partition(), Partitionneur_Sous_Domaines::construire_partition(), Partitionneur_Union::construire_partition(), Champ_Generique_Predefini::construit_expression(), Solv_Externe::construit_matrice_morse_intermediaire(), Prisme_32_64< _SIZE_ >::contient(), Op_Dift_VDF_Face_Axi_base::contribue_au_second_membre(), Op_Conv_EF_VEF_P1NC::contribue_au_second_membre(), Operateur_base::contribuer_a_avec(), Source_PDF_EF::contribuer_a_avec(), Operateur_Grad_base::contribuer_a_avec(), Perte_Charge_Reguliere_VEF_P1NC::contribuer_a_avec(), Operateur_base::contribuer_au_second_membre(), Source_base::contribuer_au_second_membre(), Iterateur_VDF_base::contribuer_au_second_membre(), Op_Dift_VDF_base::contribuer_au_second_membre(), Op_Dift_VEF_Face_Q1::contribuer_au_second_membre(), Op_Conv_VDF_base::contribuer_au_second_membre(), Op_Dift_VEF_Face::contribuer_au_second_membre(), Transport_K_Eps_base::controler_K_Eps(), Transport_K_Omega_base::controler_K_Omega(), Transport_K_ou_Eps_base::controler_variable(), IJK_Thermal_base::copie_pure_vers_diph_sans_interpolation(), Navier_Stokes_FT_Disc::correct_at_exit_bad_gradient(), Convection_Diffusion_Temperature_FT_Disc::correct_mpoint(), Domaine_IJK::correct_perio_i_local(), Triple_Line_Model_FT_Disc::correct_TCL_energy_evolution(), Corriger_frontiere_periodique_32_64< _SIZE_ >::corriger_coordonnees_sommets_perio(), Transport_K_Eps_ALE::corriger_derivee_impl_ALE(), Schema_Temps_base::corriger_dt_calcule(), Schema_Euler_Implicite_Stationnaire::corriger_dt_calcule(), Scatter::corriger_espace_distant_elements_perio(), Assembleur_base::corriger_vitesses(), Assembleur_P_PolyMAC_P0P1NC::corriger_vitesses(), Discret_Thyd::courant_maille(), IJK_Thermals::create_folders(), Param::create_or_get_objet_a_lire(), Solv_Petsc::create_solver(), Solv_rocALUTION::create_solver(), Domaine_32_64< int >::cree_instance(), Champ_Fonc_MED::creer(), Champ_front_calc::creer(), Champ_front_contact_VEF::creer(), Navier_Stokes_phase_field::creer_champ(), Domaine_dis_base::creer_champ(), Pb_MED::creer_champ(), Postraitement::creer_champ_post(), Postraitement::creer_champ_post_moreqn(), Postraitement::creer_champ_post_stat(), Iterateur_VDF_base::creer_champ_T_paroi_pour_flux_parietal(), Discret_Thyd::creer_champ_vorticite(), EF_discretisation::creer_champ_vorticite(), VEF_discretisation::creer_champ_vorticite(), Fluide_Dilatable_base::creer_champs_non_lus(), Domaine_dis_base::creer_elements_fictifs(), Faces_builder::creer_faces_reeles(), Quadri_VEF::creer_facette_normales(), MD_Vector_tools::creer_md_vect_renum(), Hexa_VEF::creer_normales_facettes_Cl(), Quadri_VEF::creer_normales_facettes_Cl(), Tetraedriser_homogene_fin::creer_sommet(), MD_Vector_tools::creer_tableau_distribue(), Champ_Fonc_base::creer_tableau_distribue(), Champ_Inc_base::creer_tableau_distribue(), Discret_Thyd::critere_Q(), Facettes_Interp_FT::cut_cell_perform_interpolation_facettes(), Modele_turbulence_hyd_LES_selectif_mod_VDF::cutoff(), Op_Diff_PolyMAC_P0_Elem::d_nucleation(), Tetraedriser_homogene_compact::decoupe(), Tetraedriser_homogene_fin::decoupe(), DecoupeBord_32_64< _SIZE_ >::decouper(), Decouper_Bord_coincident::decouper_(), Op_Div_VEFP1B_Elem::degres_liberte(), Maillage_FT_IJK::deplacer_sommets(), Equation_base::derivee_en_temps_inco(), Navier_Stokes_std::derivee_en_temps_inco(), Navier_Stokes_FT_Disc::derivee_en_temps_inco(), Equation_IBM_proto::derivee_en_temps_inco_ibm_proto(), Convection_Diffusion_Fluide_Dilatable_Proto::derivee_en_temps_inco_sans_solveur_masse_impl(), Domaine_Poly_base::detecter_faces_non_planes(), Traitement_particulier_NS_THI_VEF::determine_tab_fft_VEF_3D(), DeviceMemory::deviceMemGetInfo(), Matrice_Morse::diagmulmat(), Navier_Stokes_phase_field::diffusivite_pour_transport(), Op_EF_base::dimensionner(), Matrice_Bloc_Sym::dimensionner(), Operateur_base::dimensionner(), Operateur_Grad_base::dimensionner(), Op_Diff_VEFP1NCP1B_Face::dimensionner(), Operateur_base::dimensionner_blocs(), Source_base::dimensionner_blocs(), Solveur_Masse_base::dimensionner_blocs(), Assembleur_base::dimensionner_continuite(), OctreeLoc::direction(), Periodique::direction_periodicite(), Equation_base::discretisation(), Probleme_base::discretisation(), Navier_Stokes_phase_field::discretiser(), Navier_Stokes_Aposteriori::discretiser(), Modele_turbulence_hyd_LES_1elt_selectif_mod_VEF::discretiser(), Modele_turbulence_hyd_LES_Fst_sel_VEF::discretiser(), Transport_K_Eps_base::discretiser(), Transport_K_Omega_base::discretiser(), Transport_K_ou_Eps_base::discretiser(), Domaine_EF::discretiser(), Domaine_Poly_base::discretiser(), Convection_Diffusion_Temperature::discretiser(), Domaine_VDF::discretiser(), Domaine_VEF::discretiser(), Marqueur_FT::discretiser(), Fluide_reel_base::discretiser(), Solide::discretiser(), Probleme_base::discretiser(), Modele_rayo_semi_transp::discretiser(), Probleme_FTD_IJK_base::discretiser(), Discretisation_base::discretiser_champ(), EF_discretisation::discretiser_champ(), VEF_discretisation::discretiser_champ(), Champ_Generique_Interpolation::discretiser_domaine(), Domaine_dis_base::discretiser_root(), Discretisation_base::discretiser_variables(), Collision_Model_FT_arbitrary::discretize_contact_forces_eulerian_field(), Collision_Model_FT_spheroid::discretize_contact_forces_eulerian_field(), Collision_Model_FT_base::discretize_contact_forces_eulerian_field(), Discret_Thyd::distance_paroi_globale(), Equation_base::domaine_dis(), Champ_base::domaine_dis_base(), mon_main::dowork(), Source_Con_Phase_field::drhodc(), Statistiques::dump(), Grid_Level_Data_template< _TYPE_ >::duplique(), IJK_Vector< _TRUST_TABL_, _TYPE_, _TYPE_ARRAY_ >::duplique(), TRUSTProblem_sup_eqns< _DERIVED_TYPE_ >::duplique(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::duplique(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::duplique(), IJK_Field_vector< T, N >::duplique(), IJKArray_with_ghost< _TYPE_, _TYPE_ARRAY_ >::duplique(), TRUSTArray< _TYPE_, _SIZE_ >::duplique(), TRUSTTab< _TYPE_, _SIZE_ >::duplique(), TRUSTTrav< _TYPE_ >::duplique(), TRUSTVect< _TYPE_, _SIZE_ >::duplique(), TRUST_Deriv< _CLASSE_ >::duplique(), TRUSTProblem_Cloned_Concentration_Gen< _DERIVED_TYPE_, _EQUATION_TYPE_, _MEDIUM_TYPE_ >::duplique(), TRUSTProblem_List_Concentration_Gen< _DERIVED_TYPE_, _EQUATION_TYPE_, _MEDIUM_TYPE_ >::duplique(), IJK_Interfaces::dupliquer_bulle_perio(), IJK_Thermal_base::echange_diph_vers_pure_cellules_finalement_pures(), Schema_Comm::echange_messages(), IJK_Thermal_base::echange_pure_vers_diph_cellules_initialement_pures(), Decouper_32_64< _SIZE_ >::ecrire(), Postraiter_domaine::ecrire(), Format_Post_Lata::ecrire_domaine(), Format_Post_base::ecrire_domaine_dual(), Format_Post_Lml::ecrire_domaine_lml(), Format_Post_Lata::ecrire_domaine_low_level(), Format_Post_CGNS::ecrire_entete(), Fourier_trans::Ecrire_entete(), Format_Post_Lata::ecrire_entete_lata(), Postraitement_ft_lata::ecrire_maillage_ft_disc(), Maillage_FT_Disc::ecrire_plot(), EcritureLectureSpecial::ecriture_special(), EFichier::EFichier(), EFichierBin::EFichierBin(), Triple_Line_Model_FT_Disc::elems(), SETS::eliminer(), Echange_impose_base::emissivite(), Traitement_particulier_NS_THI_new::en_cours_de_resolution(), Schema_Comm_Vecteurs::end_init(), PE_Groups::enter_group(), Entree_Fichier_base::Entree_Fichier_base(), Viscosite_turbulente_LES_base::eps(), Modele_turbulence_hyd_base::equation(), Modele_turbulence_scal_base::equation(), Modele_Fonc_Bas_Reynolds_Base::equation(), Assembleur_P_EF::equation(), Champ_front_calc::equation(), MorEqn::equation(), Champ_front_contact_VEF::equation(), Assembleur_P_VEF::equation(), Assembleur_P_VEFPreP1B::equation(), Probleme_base::equation(), List_Equations_Scalaires_Passifs_Especes::equation(), TRUSTProblem_Concentration_Gen< _DERIVED_TYPE_, _EQUATION_TYPE_, _MEDIUM_TYPE_ >::equation(), Pb_Hydraulique_ALE::equation(), Pb_Hydraulique_Turbulent_ALE::equation(), Pb_Hydraulique_Aposteriori::equation(), Pb_Hydraulique_sensibility::equation(), Pb_Thermohydraulique_sensibility::equation(), Pb_MED::equation(), Pb_Hydraulique_IBM::equation(), Pb_Hydraulique_IBM_Turbulent::equation(), Pb_Thermohydraulique_IBM::equation(), Pb_Thermohydraulique_IBM_Turbulent::equation(), Pb_Hydraulique::equation(), Pb_Hydraulique_Concentration::equation(), Pb_Thermohydraulique::equation(), Pb_Multiphase::equation(), Pb_Hydraulique_Concentration_Turbulent::equation(), Pb_Hydraulique_Turbulent::equation(), Pb_Thermohydraulique_Concentration_Turbulent::equation(), Pb_Thermohydraulique_Turbulent::equation(), Probleme_FT_Disc_gen::equation_hydraulique(), Pb_Dilatable_Proto::equation_impl(), Probleme_FT_Disc_gen::equation_interfaces(), Cond_lim_base::err_pas_compatible(), Debog_Pb::error_function(), Entree::error_handle_(), Discret_Thyd::estimateur_aposteriori(), Parser::eval(), Champ_Elem_DG::eval_bfunc(), Champ_Elem_DG::eval_bfunc_on_facets(), Champ_base::eval_elem(), Moyenne_volumique::eval_filtre(), Champ_Elem_DG::eval_grad_bfunc(), Champ_Elem_DG::eval_grad_bfunc_on_facets(), Champ_Elem_DG::eval_invMassMatrix(), Parser::evalOp(), Eq_rayo_semi_transp_VDF::evaluer_cl_rayonnement(), Eq_rayo_semi_transp_VEF::evaluer_cl_rayonnement(), exit(), PE_Groups::exit_group(), Champ_Generique_Reduction_0D::extraire(), TroisDto2D_32_64< _SIZE_ >::extraire_2D(), ExtrudeParoi::extrude(), Extruder::extruder(), Extruder_en20::extruder(), Domaine_32_64< _SIZE_ >::face_bords_interne_conjuguee(), Prisme_32_64< _SIZE_ >::face_sommet0(), Hexaedre_VEF_32_64< _SIZE_ >::face_sommet1(), Prisme_32_64< _SIZE_ >::face_sommet1(), Prisme_32_64< _SIZE_ >::face_sommet2(), Hexaedre_VEF_32_64< _SIZE_ >::face_sommet4(), Domaine_dis_base::face_sommets(), Domaine_dis_base::face_voisins(), Solv_Cholesky::Fact_Cholesky(), ILU_SP::factoriser(), Sch_CN_iteratif::faire_un_pas_de_temps_eqn_base(), Schema_Euler_Implicite::faire_un_pas_de_temps_pb_couple(), Domaine_PolyMAC_P0::fgrad(), Fichier_Lata::Fichier_Lata(), FichierHDF::FichierHDF(), FichierHDFPar::FichierHDFPar(), Domaine_32_64< _SIZE_ >::fill_from_list(), Transport_Interfaces_FT_Disc::fill_ftab_local_reference_frame_velocity(), Transport_Interfaces_FT_Disc::fill_ftab_velocity(), Sonde_IJK::fill_local_values(), Champ_P1NC_implementation::filtrer_L2(), LireMED_32_64< _SIZE_ >::finalize_sommets(), Champ_base::fixer_nb_valeurs_nodales(), Champ_Fonc_base::fixer_nb_valeurs_nodales(), Champ_Inc_base::fixer_nb_valeurs_nodales(), Convection_Diffusion_Fluide_Dilatable_base::fluide(), Convection_Diffusion_Temperature_base::fluide(), Masse_Multiphase::fluide(), Navier_Stokes_FT_Disc::fluide_diphasique(), Eval_Diff_VDF_Face_Gen< DERIVED_T >::flux_arete(), Neumann::flux_impose(), Paroi_Rayo_transp::flux_impose(), Flux_radiatif_base::flux_impose(), Sortie_libre_pression_imposee_QC::flux_impose(), Sortie_libre_pression_moyenne_imposee::flux_impose(), Sortie_libre_Text_H_ext::flux_impose(), Sortie_libre_rho_variable::flux_impose(), Sortie_libre_pression_imposee::flux_impose(), Sortie_libre_Gradient_Pression_impose::flux_impose(), Sortie_libre_Gradient_Pression_impose_VEF::flux_impose(), Sortie_libre_Pression_imposee_Orlansky::flux_impose(), Sortie_libre_Gradient_Pression_libre_VEF::flux_impose(), Modele_rayo_semi_transp::flux_radiatif(), Modele_Rayonnement_Milieu_Transparent::flux_radiatif(), Champ_Q1NC_implementation::fonction_forme_2D_normalise(), Champ_Q1NC_implementation::fonction_forme_3D_normalise(), Couplage_Tubes_IBC::force_ibc(), Couplage_Tubes_IBC::force_ibc_velocity(), Couplage_Tubes_IBC::force_ibc_velocity_miroir(), TRUSTArray< _TYPE_, _SIZE_ >::from_tid_to_int(), Domaine_32_64< _SIZE_ >::frontiere(), Entree::get(), Lec_Diffuse_base::get(), Simpler_Base::get_and_set_parametre_equation(), Matrice_Bloc::get_bloc(), Matrice_Bloc_Sym::get_bloc(), Probleme_base::get_champ(), Pb_MED::get_champ(), Champ_Generique_Divergence::get_champ(), Champ_Generique_Extraction::get_champ(), Champ_Generique_Gradient::get_champ(), Champ_Generique_Interpolation::get_champ(), Champ_Generique_Morceau_Equation::get_champ(), Champ_Generique_Reduction_0D::get_champ(), Champ_Generique_refChamp_special::get_champ(), Champ_Generique_Transformation::get_champ(), Probleme_base::get_champ_post(), Transport_Marqueur_FT::get_champ_post_FT(), Transport_Interfaces_FT_Disc::get_champ_post_FT(), Champ_Generique_Interpolation::get_champ_with_calculer_champ_post(), Champ_Generique_Divergence::get_champ_without_evaluation(), Champ_Generique_Gradient::get_champ_without_evaluation(), Domaine_IJK::get_constant_delta(), IJK_Grid_Geometry::get_constant_delta(), Statistiques::get_counter_id_from_index_in_comm_tracking_info(), Probleme_FTD_IJK_base::get_cut_cell_disc(), Operateur_IJK_data_channel::get_delta(), Milieu_MUSIG::get_Diameter_Inf(), Milieu_MUSIG::get_Diameter_Sauter(), Milieu_MUSIG::get_Diameter_Sup(), Champ_Generique_Interpolation::get_directive_pour_discr(), Champ_Generique_refChamp::get_directive_pour_discr(), Champ_Generique_Transformation::get_directive_pour_discr(), Champ_implementation::get_domaine_dis(), Probleme_FT_Disc_gen::get_equation_by_name(), Convection_Diffusion_Temperature_FT_Disc::get_flux_and_Twall(), Convection_Diffusion_Temperature_FT_Disc::get_flux_to_face(), OpConvCentre2IJK_double::get_g(), OpConvCentre4IJK_double::get_g(), IJK_Interfaces::get_ghost_number_from_compo(), Domaine_IJK::get_i_along_dir_no_perio(), Collision_Model_FT_base::get_id(), Postprocessing_IJK::get_IJK_flag(), Triple_Line_Model_FT_Disc::get_in_out_coords(), Domaine_VF::get_ind_integ_points(), LecFicDiffuse::get_istream(), Collision_Model_FT_base::get_last_id(), Domaine_IJK::get_local_mesh_delta(), MorEqn::get_localisation_pour_post(), Operateur_base::get_localisation_pour_post(), Discretisation_base::get_name_of_type_for(), Domaine_VF::get_nb_integ_points(), Objet_U_ptr::get_Objet_U_ptr_check(), Champ_Inc_base::get_PDI_dname(), Topologie_Maillage_FT::get_phase_continue(), Champ_Generique_refChamp::get_property(), Domaine_DG::get_quadrature(), Champ_Generique_Extraction::get_ref_domain(), Champ_Generique_Extraction::get_ref_domaine_dis_base(), Champ_Generique_Interpolation::get_ref_domaine_dis_base(), Champ_Generique_refChamp::get_ref_zcl_dis_base(), Champ_Gen_de_Champs_Gen::get_source(), Matrice_Base::get_stencil(), Matrice_Base::get_stencil_and_coeff_ptrs(), Matrice_Base::get_stencil_and_coefficients(), Matrice_Nulle::get_symmetric_stencil(), Matrice_Nulle::get_symmetric_stencil_and_coefficients(), Triple_Line_Model_FT_Disc::get_theta_app(), Calcul_Production_K_VEF::get_turbulent_viscosity(), Convection_Diffusion_Temperature_FT_Disc::get_Twall_at_elem(), Objet_a_lire::get_value(), Param::get_value(), IJK_VDF_converter::get_vdf_to_ijk(), Paroi_TBLE_scal_VDF::getLoiParoiHydraulique(), ParoiVEF_TBLE_scal::getLoiParoiHydraulique(), ScalarRegister::getOutputDoubleValue(), ScalarRegister::getOutputIntValue(), Probleme_FT_Disc_gen::getset_equation_by_name(), ICoCo::ProblemTrio::getStationaryMode(), Debog_Pb::goto_msg(), Sortie_libre_Gradient_Pression_impose::grad_P_imp(), Sortie_libre_Gradient_Pression_libre_VEF::Grad_P_lib_VEF(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::Grad_P_lib_VEFPreP1B(), Discret_Thyd::grad_T(), Discret_Thyd::grad_u(), Milieu_base::gravite(), Discret_Thyd::h_conv(), Echange_global_impose_turbulent::h_imp(), Echange_impose_base::h_imp(), Echange_impose_base::h_imp_grad(), Domaine_Cl_DG::imposer_cond_lim(), Domaine_Cl_EF::imposer_cond_lim(), Domaine_Cl_PolyMAC::imposer_cond_lim(), Domaine_Cl_VDF::imposer_cond_lim(), Domaine_Cl_VEF::imposer_cond_lim(), Iterateur_Source_base::impr(), Source_PDF_EF::impr(), Op_EF_base::impr(), Op_VEF_Face::impr(), Navier_Stokes_std::impr(), Navier_Stokes_Fluide_Dilatable_Proto::impr_impl(), Champ_Don_base::imprime(), Champ_Inc_base::imprime(), Champ_Fonc_P0_VDF::imprime(), Champ_P0_VDF::imprime(), Equation_base::imprime_residu(), Matrice_Morse::imprimer_formatte(), Matrice_Morse::imprimer_image(), Cut_cell_surface_efficace::imprimer_informations_surface_efficace_face(), Cut_cell_surface_efficace::imprimer_informations_surface_efficace_interface(), Couplage_U::indice_probleme(), Echange_contact_Correlation_VEF::init(), Postraitement::init(), TRUST_2_PDI::init(), Traitement_particulier_NS_THI_VEF_new::init_calc_spectre(), Traitement_particulier_NS_Profils_VDF::init_calcul_moyenne(), Terme_Source_Canal_RANS_LES_VDF_Face::init_calcul_moyenne_spat(), Domaine_dis_base::init_dist_paroi_globale(), Domaine_VF::init_dist_paroi_globale(), Echange_contact_PolyMAC_P0P1NC::init_f_dist(), Champ_Inc_P0_base::init_fcl(), Champ_Face_base::init_fcl(), Echange_contact_PolyMAC_P0::init_fs_dist(), Comm_Group::init_group(), Comm_Group_MPI::init_group_trio(), Postprocessing_IJK::init_integrated_and_ana(), ParoiVDF_TBLE::init_lois_paroi(), ParoiVDF_TBLE_LRM::init_lois_paroi(), Paroi_ODVM_scal_VDF::init_lois_paroi(), Paroi_TBLE_scal_VDF::init_lois_paroi(), ParoiVEF_TBLE::init_lois_paroi(), ParoiVEF_TBLE_scal::init_lois_paroi(), Paroi_scal_hyd_base_EF::init_lois_paroi(), Paroi_scal_hyd_base_VEF::init_lois_paroi(), Paroi_TBLE_QDM::init_lois_paroi(), Echange_contact_PolyMAC_P0::init_op(), Echange_contact_PolyMAC_P0P1NC::init_op(), mon_main::init_parallel(), Probleme_base::init_postraitements(), Transport_Interfaces_FT_Disc_interne::init_save_file(), Echange_contact_Correlation_VDF::init_tab_echange(), DNS_QC_double::initialise(), Raccord_distant_homogene_32_64< _SIZE_ >::initialise(), Navier_Stokes_FTD_IJK::initialise_ns_fields(), Navier_Stokes_FTD_IJK::initialise_velocity_using_expression(), Sonde::initialiser(), DomaineCutter_32_64< _SIZE_ >::initialiser(), Champ_Ostwald::initialiser(), MuLambda_TBLE_Cte::initialiser(), MuLambda_TBLE_Fcts_T::initialiser(), Domaine_Cl_DG::initialiser(), Domaine_Cl_PolyMAC::initialiser(), Echange_contact_VDF::initialiser(), Ch_front_Vortex::initialiser(), Champ_front_lu::initialiser(), Champ_front_pression_from_u::initialiser(), Champ_front_contact_VEF::initialiser(), Domaine_ALE::initialiser(), Champ_front_xyz_debit::initialiser(), Iterateur_Source_base::initialiser(), Champ_front_calc::initialiser(), Loi_Etat_Multi_GP_WC::initialiser_inco_ch(), Statistiques_dns_ijk_monophasique::initialize(), Statistiques_dns_ijk::initialize(), Redistribute_Field::initialize(), IJK_Thermal_base::initialize(), IJK_Thermal_cut_cell::initialize(), IJK_Interfaces::initialize(), Format_Post_Lata::initialize(), Statistiques_dns_ijk_FT::initialize(), Domaine_IJK::initialize_from_unstructured(), IJK_Grid_Geometry::initialize_from_unstructured(), Domaine_IJK::initialize_splitting(), IJK_Thermal_base::initialize_switch(), Structural_dynamic_mesh_model::initMfrontBehaviour(), Navier_Stokes_std::initTimeStep(), Cond_lim_base::injecter_dans_champ_inc(), Type_info::instance(), Champ_Inc_base::integrale_espace(), Structural_dynamic_mesh_model::integrate_behaviour_(), Transport_Interfaces_FT_Disc::integrer_ensemble_lagrange(), Comm_Group_MPI::internal_collective(), DNS_QC_double::interpreter(), Ecr_fic_Ansys::interpreter(), Imprimer_Fichiers_RANS_VDF::interpreter(), Imprimer_Fichiers_RANS_VEF::interpreter(), IJK_Lata_Swap_JK::interpreter(), Associer::interpreter(), Diametre_hyd_champ::interpreter(), Discretiser::interpreter(), Porosites_champ::interpreter(), Resoudre::interpreter(), PrecisionGeom::interpreter(), Scatter::interpreter(), Pilote_ICoCo::interpreter(), Parallel_io_parameters::interpreter(), Integrer_champ_med::interpreter(), Ecrire_Champ_MED::interpreter(), Merge_MED::interpreter(), Option_CGNS::interpreter(), Moyenne_volumique::interpreter(), Execute_parallel::interpreter(), Lire_Fichier::interpreter(), Mkdir::interpreter(), Option_Interpolation::interpreter(), System::interpreter(), EcritureLectureSpecial::interpreter(), Decouper_multi::interpreter(), MaillerParallel::interpreter(), Raffiner_isotrope_parallele::interpreter(), Testeur_MEDCoupling::interpreter(), Lata_2_Other::interpreter(), Link_CGNS_Files::interpreter(), Extraire_surface_ALE::interpreter_(), Imposer_vit_bords_ALE::interpreter_(), ConcatAnsys::interpreter_(), Calculer_Moments::interpreter_(), Create_domain_from_sub_domain::interpreter_(), DecoupeBord_32_64< _SIZE_ >::interpreter_(), Decouper_Bord_coincident::interpreter_(), Dilate::interpreter_(), Distanceparoi::interpreter_(), Extraire_domaine::interpreter_(), Extraire_plan::interpreter_(), Extraire_surface::interpreter_(), ExtrudeBord::interpreter_(), Extruder_en3::interpreter_(), Lire_Tgrid::interpreter_(), Mailler_32_64< _SIZE_ >::interpreter_(), NettoieNoeuds_32_64< _SIZE_ >::interpreter_(), Polyedriser_32_64< _SIZE_ >::interpreter_(), Redresser_hexaedres_vdf::interpreter_(), Reorienter_tetraedres_32_64< _SIZE_ >::interpreter_(), Reorienter_triangles_32_64< _SIZE_ >::interpreter_(), Rotation::interpreter_(), SupprimeBord_32_64< _SIZE_ >::interpreter_(), Triangulation_base::interpreter_(), TroisDto2D_32_64< _SIZE_ >::interpreter_(), LireMED_32_64< _SIZE_ >::interpreter_(), Postraiter_domaine::interpreter_(), VerifierCoin::interpreter_(), Ecrire_Fichier::interpreter_(), Remove_Invalid_Internal_Boundaries::interpreter_(), Interprete_bloc::interpreter_bloc(), Matrice_Morse::inverse(), Matrice_Morse_Sym::inverse(), Matrice33::inverse(), Loi_Etat_GP_WC::inverser_Pth(), FT_Field::is_compo_in_proc(), RK3_FT::iterateTimeStep(), SETS::iterer_eqn(), Solveur_Implicite_base::iterer_eqs(), Implicit_steady::iterer_NS(), Simpler::iterer_NS(), Solveur_U_P::iterer_NS(), Joints_32_64< _SIZE_ >::joint_PE(), Viscosite_turbulente_LES_base::k_over_eps(), Kokkos_exit(), Domaine_Cl_dis_base::la_cl_de_la_face(), Echange_contact_rayo_semi_transp_VDF::la_Cl_opposee(), Champ_Fonc_Tabule::le_champ_tabule_discretise(), Pb_Couple_rayo_semi_transp::le_modele_rayo_associe(), LecFicDiffuse::LecFicDiffuse(), LecFicDiffuse_JDD::LecFicDiffuse_JDD(), SolveurSys_base::lecture(), EcritureLectureSpecial::lecture_special(), Type_info::les_sous_types(), Equation_base::lire(), SETS::lire(), Piso::lire(), Simple::lire(), Traitement_particulier_NS_Profils_VDF::lire(), Champ_Fonc_MED::lire(), Champ_Fonc_MED_Table_Temps::lire(), Operateur::lire(), Traitement_particulier_NS_THI_VEF::lire(), Traitement_particulier_NS_canal::lire(), Traitement_particulier_NS_chmoy_faceperio::lire(), Traitement_particulier_NS_EC::lire(), Traitement_particulier_NS_Profils::lire(), Traitement_particulier_NS_temperature::lire(), Traitement_particulier_NS_THI::lire(), Traitement_particulier_NS_THI_new::lire(), Traitement_particulier_Solide_canal::lire(), Traitement_particulier_NS_Pression_VDF::lire(), Traitement_particulier_NS_Brech_VEF::lire(), Traitement_particulier_NS_Pression_VEF::lire(), LoiParoiHybride::lire(), Param::lire_avec_accolades_depuis(), Domaine_base::lire_bords_a_imprimer(), Domaine_base::lire_bords_a_imprimer_sum(), Lecture_Champ::lire_champs(), Postraitement::lire_champs_a_postraiter(), Postraitement::lire_champs_operateurs(), Postraitement::lire_champs_stat_a_postraiter(), Equation_base::lire_cl(), Equation_base::lire_cond_init(), Navier_Stokes_std::lire_cond_init(), QDM_Multiphase::lire_cond_init(), Transport_Interfaces_FT_Disc::lire_cond_init(), Probleme_base::lire_correlations(), Terme_Source_Acceleration::lire_data(), Champ_Proto::lire_dimension(), Modele_turbulence_hyd_base::lire_distance_paroi(), Modele_turbulence_hyd_Longueur_Melange_VEF::lire_distance_paroi(), Modele_Lam_Bremhorst_VEF::lire_distance_paroi(), Scatter::lire_domaine(), Paroi_TBLE_QDM_Scal::lire_donnees(), SourceFiltree_FT_disc_base::lire_donnees(), Champ_Inc_base::lire_donnees(), DP_Impose::lire_donnees(), Perte_Charge_Reguliere::lire_donnees(), Perte_Charge_Singuliere::lire_donnees(), Terme_Source_inc_th::lire_donnees(), Paroi_UTAU_IMP_Impl::lire_donnees(), Champ_Fonc_MED_Table_Temps::lire_donnees_champ(), Postraitement_ft_lata::lire_entete_bloc_interface(), Postprocessing_IJK::lire_entete_bloc_interface(), Pb_Multiphase::lire_equations(), Champ_front_recyclage::lire_fichier_format1(), Champ_front_recyclage::lire_fichier_format2(), Champ_front_recyclage::lire_fichier_format3(), Modele_Rayonnement_Milieu_Transparent::lire_fichiers(), Pave_32_64< _SIZE_ >::lire_front(), LireMED_32_64< _SIZE_ >::lire_geom(), Champ_front_recyclage::lire_info_moyenne_imposee(), Champ_front_recyclage::lire_info_moyenne_recyclee(), Pave_32_64< _SIZE_ >::lire_longueurs(), Transport_Interfaces_FT_Disc::lire_maillage_ft_cao(), Maillage_FT_IJK::lire_maillage_ft_dans_lata(), Paroi_TBLE_QDM::lire_motcle_non_standard(), Navier_Stokes_Turbulent_ALE::lire_motcle_non_standard(), Collision_Model_FT_base::lire_motcle_non_standard(), Post_Processing_Hydrodynamic_Forces::lire_motcle_non_standard(), Proprietes_part_vol::lire_motcle_non_standard(), Convection_Diffusion_Concentration_FT_Disc::lire_motcle_non_standard(), Convection_Diffusion_Concentration_Turbulent_FT_Disc::lire_motcle_non_standard(), Convection_Diffusion_Temperature_FT_Disc::lire_motcle_non_standard(), Navier_Stokes_FT_Disc::lire_motcle_non_standard(), Transport_Interfaces_FT_Disc::lire_motcle_non_standard(), Transport_Marqueur_FT::lire_motcle_non_standard(), Convection_Diffusion_Phase_field::lire_motcle_non_standard(), Navier_Stokes_phase_field::lire_motcle_non_standard(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::lire_motcle_non_standard(), Modele_turbulence_hyd_LES_VDF::lire_motcle_non_standard(), Modele_turbulence_scal_LES_dyn_VDF::lire_motcle_non_standard(), Transport_K_Eps::lire_motcle_non_standard(), Transport_K_KEps::lire_motcle_non_standard(), Transport_K_Omega::lire_motcle_non_standard(), Transport_K_ou_Eps::lire_motcle_non_standard(), Transport_K_ou_Eps_Realisable::lire_motcle_non_standard(), Modele_turbulence_scal_Fluctuation_Temperature_W::lire_motcle_non_standard(), Champ_Gen_de_Champs_Gen::lire_motcle_non_standard(), Champ_Generique_refChamp::lire_motcle_non_standard(), Champ_Generique_Transformation::lire_motcle_non_standard(), PDF_model::lire_motcle_non_standard(), Schema_Temps_base::lire_motcle_non_standard(), Create_domain_from_sub_domain::lire_motcle_non_standard(), Decouper_multi::lire_motcle_non_standard(), Partitionneur_Metis_32_64< _SIZE_ >::lire_motcle_non_standard(), Champ_Fonc_MED_Table_Temps::lire_motcle_non_standard(), Format_Post_Lata::lire_motcle_non_standard(), Postraitement::lire_motcle_non_standard(), Postraiter_domaine::lire_motcle_non_standard(), Fluide_Dilatable_base::lire_motcle_non_standard(), Convection_Diffusion_Chaleur_QC::lire_motcle_non_standard(), Fluide_Quasi_Compressible::lire_motcle_non_standard(), Convection_Diffusion_Temperature::lire_motcle_non_standard(), Navier_Stokes_std::lire_motcle_non_standard(), Perte_Charge_Gen::lire_motcle_non_standard(), Terme_Source_Canal_perio::lire_motcle_non_standard(), Terme_Source_Coriolis_base::lire_motcle_non_standard(), Modele_turbulence_hyd_base::lire_motcle_non_standard(), Modele_turbulence_scal_base::lire_motcle_non_standard(), Conduction::lire_motcle_non_standard(), Source_Neutronique::lire_motcle_non_standard(), Option_VDF::lire_motcle_non_standard(), Source_Darcy_VDF_Face::lire_motcle_non_standard(), Source_Forchheimer_VDF_Face::lire_motcle_non_standard(), Perte_Charge_VEF::lire_motcle_non_standard(), Source_Darcy_VEF_Face::lire_motcle_non_standard(), Source_Forchheimer_VEF_Face::lire_motcle_non_standard(), Modele_turbulence_hyd_Longueur_Melange_VEF::lire_motcle_non_standard(), Statistiques_dns_ijk::lire_motcle_non_standard(), Convection_Diffusion_Temperature_sensibility::lire_motcle_non_standard(), Navier_Stokes_std_sensibility::lire_motcle_non_standard(), Terme_Puissance_Thermique_Echange_Impose_Elem_base::lire_motcle_non_standard(), Objet_U::lire_motcle_non_standard(), Reaction::lire_motcle_non_standard(), IJK_Interfaces::lire_motcle_non_standard(), Pave_32_64< _SIZE_ >::lire_noeuds(), Navier_Stokes_Turbulent_ALE::lire_op_diff_turbulent(), Transport_2eq_base::lire_op_diff_turbulent(), Navier_Stokes_IBM_Turbulent::lire_op_diff_turbulent(), Navier_Stokes_Turbulent::lire_op_diff_turbulent(), Probleme_base::lire_postraitement_interfaces(), Postraitements::lire_postraitements(), Schema_Temps_base::lire_residuals(), TRUSTProblem_Concentration_Gen< _DERIVED_TYPE_, _EQUATION_TYPE_, _MEDIUM_TYPE_ >::lire_resize_medium(), Param::lire_sans_accolade(), Save_Restart::lire_sauvegarde_reprise(), Probleme_FT_Disc_gen::lire_solved_equations(), Probleme_FTD_IJK_base::lire_solved_equations(), Perte_Charge_Singuliere::lire_surfaces(), Lecture_Table::lire_table(), Postraitement::lire_tableaux_a_postraiter(), Transport_Marqueur_FT::lire_transformation(), Sauvegarde_Reprise_Maillage_FT::lire_xyz(), KerasModel::LoadModel(), Sortie::lockfile(), Maillage_FT_Disc::Maillage_FT_Disc(), Domaine_32_64< _SIZE_ >::md_vector_elements(), Champ_Ostwald::me_calculer(), Source_base::mettre_a_jour(), Chimie::mettre_a_jour(), Convection_Diffusion_Concentration_FT_Disc::mettre_a_jour(), Convection_Diffusion_Concentration_Turbulent_FT_Disc::mettre_a_jour(), Transport_Interfaces_FT_Disc::mettre_a_jour(), Modele_rayo_semi_transp::mettre_a_jour(), Echange_contact_rayo_semi_transp_VDF::mettre_a_jour(), Champ_Inc_base::mettre_a_jour(), Champ_Fonc_MED_Tabule::mettre_a_jour(), Champ_front_synt::mettre_a_jour(), Champ_Ostwald::mettre_a_jour(), Loi_paroi_base::mettre_a_jour(), Champ_front_contact_fictif_VEF::mettre_a_jour(), Champ_front_contact_VEF::mettre_a_jour(), Champ_front_fonc_gradient_VEF::mettre_a_jour(), Domaine_ALE::mettre_a_jour(), Echange_contact_VDF_FT_Disc::mettre_a_jour(), Echange_contact_Rayo_transp_VDF::mettre_a_jour(), Champ_Fonc_P0_MED::mettre_a_jour(), Champ_Fonc_P1_MED::mettre_a_jour(), Champ_Fonc_Q1_MED::mettre_a_jour(), Echange_contact_Correlation_VDF::mettre_a_jour(), Op_Dift_Multiphase_VDF_Elem::mettre_a_jour(), Sortie_libre_Gradient_Pression_impose_VEFPreP1B::mettre_a_jour(), Terme_Source_Canal_RANS_LES_VEF_Face::mettre_a_jour(), Convection_Diffusion_Concentration_FT_Disc::mettre_a_jour_chimie(), Convection_Diffusion_Concentration_Turbulent_FT_Disc::mettre_a_jour_chimie(), Integrale_tps_Champ::mettre_a_jour_integrale(), Integrale_tps_produit_champs::mettre_a_jour_integrale(), Probleme_Couple::mettre_a_jour_modele_rayo(), IJK_Thermal_base::milieu(), IJK_Thermals::milieu(), Navier_Stokes_FTD_IJK::milieu(), Equation_rayonnement_base::milieu(), Transport_Fluctuation_Temperature::milieu(), Transport_Fluctuation_Temperature_W::milieu(), Transport_Fluctuation_Temperature_W_Bas_Re::milieu(), Transport_Flux_Chaleur_Turbulente::milieu(), Navier_Stokes_std::milieu(), Convection_Diffusion_Temperature_FT_Disc::milieu(), Transport_Interfaces_FT_Disc::milieu(), Transport_2eq_base::milieu(), Convection_Diffusion_Temperature::mise_en_place_domaine_fantome(), Tetra_VEF::modif_volumes_entrelaces(), Tri_VEF::modif_volumes_entrelaces(), Tetra_VEF::modif_volumes_entrelaces_faces_joints(), Tri_VEF::modif_volumes_entrelaces_faces_joints(), Discr_inst::modifier_champ_tabule(), Terme_Source_Th_TdivU_VEF_Face::modifier_domaine_cl(), Eq_rayo_semi_transp_VDF::modifier_matrice(), Eq_rayo_semi_transp_VEF::modifier_matrice(), Assembleur_P_VEFPreP1B::modifier_matrice(), Op_VEF_Face::modifier_matrice_pour_periodique_apres_contribuer(), Transport_turbulent_GGDH_WIT::modifier_mu(), Transport_turbulent_SGDH_WIT::modifier_mu(), Op_Diff_Turbulent_PolyMAC_P0_Elem::modifier_mu(), Op_EF_base::modifier_pour_Cl(), Operateur_base::modifier_pour_Cl(), Op_Diff_K_Eps_VDF_base::modifier_pour_Cl(), Op_Diff_K_Omega_VDF_base::modifier_pour_Cl(), AssembleurPVDF_PF::modifier_secmem(), Assembleur_P_VDF::modifier_secmem(), Assembleur_P_VEFPreP1B::modifier_secmem(), AssembleurPVDF_PF::modifier_secmem_pression_imposee(), Schema_Implicite_Multi_TimeStep_base::modifier_second_membre(), Schema_Implicite_Multi_TimeStep_base::modifier_second_membre_full_impl(), Assembleur_P_VEFPreP1B::modifier_solution(), Transport_Interfaces_FT_Disc::modifier_vpoint_pour_imposer_vit(), Paroi_std_hyd_VDF::modifs_valeurs_turb(), Source_PDF_EF::multiply_coeff_volume(), Matrice_Petsc::nb_colonnes(), Polyedre_32_64< _SIZE_ >::nb_faces(), Polygone_32_64< _SIZE_ >::nb_faces(), Prisme_32_64< _SIZE_ >::nb_faces(), Domaine_Cl_DG::nb_faces_sortie_libre(), Domaine_Cl_EF::nb_faces_sortie_libre(), Domaine_Cl_PolyMAC::nb_faces_sortie_libre(), Matrice_Petsc::nb_lignes(), Prisme_32_64< _SIZE_ >::nb_som_face(), Champ_base::nb_valeurs_nodales(), Statistiques::new_counter(), StringTokenizer::nextToken(), Nom::Nom(), Nom::nom_me(), Champ_Generique_Morceau_Equation::nommer_source(), Champ_Gen_de_Champs_Gen::nommer_sources(), Assembleur_base::norme_continuite(), Interprete_bloc::objet_global(), Interprete_bloc::objet_local(), Memoire::objet_u(), Memoire::objet_u_ptr(), Transport_Interfaces_FT_Disc::operateur(), Equation_rayonnement_base::operateur(), Transport_K_Eps::operateur(), Transport_K_Eps_non_std::operateur(), Transport_K_Eps_Realisable::operateur(), Transport_K_Omega::operateur(), Transport_K_ou_Eps::operateur(), Transport_K_ou_Eps_non_std::operateur(), Transport_K_ou_Eps_Realisable::operateur(), Transport_Fluctuation_Temperature::operateur(), Transport_Fluctuation_Temperature_W::operateur(), Transport_Fluctuation_Temperature_W_Bas_Re::operateur(), Transport_Flux_Chaleur_Turbulente::operateur(), Convection_Diffusion_std::operateur(), Navier_Stokes_std::operateur(), Aire_interfaciale::operateur(), Masse_Multiphase::operateur(), Conduction::operateur(), Equation_base::operateur_fonctionnel(), Navier_Stokes_std::operateur_fonctionnel(), Matrice_Morse::operator()(), Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::operator()(), EcrFicPartageMPIIO::operator<<(), Comm_Group::operator=(), Lec_Diffuse_base::operator=(), Maillage_FT_Disc::operator=(), Maillage_FT_IJK::operator=(), Sortie_Fichier_base::operator=(), Switch_FT_double::operator=(), TRUST_List< _CLASSE_ >::operator[](), Liste_bloc::operator[](), Matrice_Petsc::ordre(), Domaine_VF::orientation(), LecFicDiffuse_JDD::ouvrir(), Sortie_Fichier_base::ouvrir(), Source_PDF_base::ouvrir_fichier(), Operateur_base::ouvrir_fichier(), Source_base::ouvrir_fichier(), Maillage_FT_Disc::parcourir_maillage(), Parser::parserState0(), Parser::parserState1(), Parser::parserState2(), Parser::parseString(), Matrice_Morse::partie_sup(), Convection_Diffusion_Temperature::penalisation_L2(), Polyedriser_32_64< _SIZE_ >::polyedriser(), Postraitement_ft_lata::postprocess_field_values(), Statistiques_dns_ijk::postraiter(), Postprocessing_IJK::postraiter_champs(), Statistiques_dns_ijk::postraiter_k(), DNS_QC_double::posttraiter_champs_instantanes(), IJK_Interfaces::posttraiter_champs_instantanes(), Precond_local::precond(), SSOR::preconditionner_(), PrecondA::preconditionner_(), ILU_SP::prepare_(), Precond_local::prepare_(), Solv_GCP::prepare_data(), Transport_Interfaces_FT_Disc::preparer_calcul(), Modele_Rayonnement_Milieu_Transparent::preparer_calcul(), Modele_rayo_semi_transp::preparer_calcul(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::preparer_calcul(), Paroi_std_hyd_VDF::preparer_calcul_hyd(), Traitement_particulier_NS_CEG::preparer_calcul_particulier(), Traitement_particulier_NS_chmoy_faceperio::preparer_calcul_particulier(), Champ_Generique_Transformation::preparer_macro(), TRUST_2_PDI::prepareRestart(), PrePostNN::PrePostNN(), Objet_a_lire::print(), TRUSTTab< _TYPE_, _SIZE_ >::printOn(), TRUSTVect< _TYPE_, _SIZE_ >::printOn(), Collision_Model_FT_arbitrary::printOn(), Collision_Model_FT_base::printOn(), Collision_Model_FT_sphere::printOn(), Collision_Model_FT_spheroid::printOn(), Post_Processing_Hydrodynamic_Forces::printOn(), Post_Processing_Hydrodynamic_Forces_Stokes::printOn(), Solid_Particle_arbitrary::printOn(), Solid_Particle_sphere::printOn(), Solid_Particle_spheroid::printOn(), Maillage_FT_Disc_Data_Cache::printOn(), Proprietes_part_vol::printOn(), Connectivite_frontieres::printOn(), Marching_Cubes::printOn(), Remailleur_Collision_FT_Thomas::printOn(), Topologie_Maillage_FT::printOn(), Champ_Gen_de_Champs_Gen::printOn(), Champ_Generique_Extraction::printOn(), Champ_Generique_Interpolation::printOn(), Debog_Pb::printOn(), Debog_Pb_Wrapper::printOn(), Loi_Fermeture_base::printOn(), Decouper_32_64< _SIZE_ >::printOn(), Decouper_multi::printOn(), Partitionneur_Fichier_Decoupage::printOn(), Partitionneur_Fichier_MED::printOn(), Partitionneur_Metis_32_64< _SIZE_ >::printOn(), Partitionneur_Parmetis::printOn(), Partitionneur_Partition::printOn(), Partitionneur_Ptscotch::printOn(), Partitionneur_Sous_Domaine::printOn(), Partitionneur_Sous_Domaines::printOn(), Partitionneur_Tranche_32_64< _SIZE_ >::printOn(), Partitionneur_Union::printOn(), DomaineCutter_32_64< _SIZE_ >::printOn(), DescStructure::printOn(), Format_Post_base::printOn(), Format_Post_CGNS::printOn(), Format_Post_Lata::printOn(), Format_Post_Lml::printOn(), Format_Post_Med::printOn(), Format_Post_Med_major::printOn(), Format_Post_XYZ::printOn(), Lata_2_Other::printOn(), Comm_Group::printOn(), Comm_Group_MPI::printOn(), Comm_Group_Noparallel::printOn(), Execute_parallel::printOn(), Interprete::printOn(), Interprete_bloc::printOn(), Lire_Fichier::printOn(), Terme_Source_Acceleration::printOn(), TRUSTTravPool< _TYPE_ >::PrintStats(), Probleme_FTD_IJK_base::probleme(), Assembleur_P_VEFPreP1B::projete_L2(), Transport_Interfaces_FT_Disc::projete_point_face_interface(), Discret_Thyd::proprietes_physiques_fluide_Ostwald(), EcrFicPartageMPIIO::put(), Champ_lu_proto::put_file_into_nom(), Flux_parietal_Kommajosyula::qp(), Loi_Etat_Multi_GP_QC::rabot(), OctreeRoot_32_64< _SIZE_ >::rang_arete(), OctreeRoot_32_64< _SIZE_ >::rang_elem(), OctreeRoot_32_64< _SIZE_ >::rang_elem_depuis(), Domaine_dis_base::rang_frontiere(), Domaine_32_64< _SIZE_ >::rang_frontiere(), OctreeRoot_32_64< _SIZE_ >::rang_sommet(), Objet_a_lire::read(), Champ_Input_Proto::read(), Param::read(), Domaine_ALE::read_beam(), LireMED_32_64< _SIZE_ >::read_boundaries(), Scatter::read_domain_no_comm(), Domaine_32_64< _SIZE_ >::read_former_domaine(), Domaine_ALE::reading_ALE_Neumann_BC_for_grid_problem(), Domaine_ALE::reading_beam_model(), Domaine_ALE::reading_projection_ALE_boundary(), Domaine_ALE::reading_solver_moving_mesh_ALE(), Domaine_ALE::reading_structural_dynamic_mesh_model(), Domaine_ALE::reading_vit_bords_ALE(), Beam_model::readInputAbscFiles(), Beam_model::readInputCIFile(), Beam_model::readInputMassStiffnessFiles(), Beam_model::readInputModalDeformation(), Op_Conv_ALE_VDF::readOn(), Coalescence_bulles_1groupe_Yao_Morel::readOn(), Dispersion_bulles_turbulente_Bazin::readOn(), Dispersion_bulles_turbulente_Bertodano::readOn(), Dispersion_bulles_turbulente_Burns::readOn(), Dispersion_bulles_turbulente_constante::readOn(), Dispersion_bulles_turbulente_Lavieville::readOn(), Flux_parietal_Hibiki::readOn(), Flux_parietal_Kommajosyula::readOn(), Flux_parietal_Kurul_Podowski::readOn(), Frottement_interfacial_Ishii_Zuber_Deformable::readOn(), Frottement_interfacial_Kumar_Brooks::readOn(), Frottement_interfacial_Tomiyama_complet::readOn(), Masse_ajoutee_Cai::readOn(), Portance_interfaciale_Sugrue_Modifiee::readOn(), Portance_interfaciale_Tomiyama_complet::readOn(), Rupture_bulles_1groupe_Yao_Morel::readOn(), Fluide_eau_c3_gaz::readOn(), Fluide_eau_c3_liquide::readOn(), Fluide_R12_c1_gaz::readOn(), Fluide_R12_c1_liquide::readOn(), Saturation_eau_c3::readOn(), Saturation_R12_c1::readOn(), Coalescence_bulles_1groupe_PolyMAC_P0::readOn(), Coalescence_bulles_2groupes_PolyMAC_P0::readOn(), Correction_Lubchenko_PolyMAC_P0::readOn(), Flux_2groupes_PolyMAC_P0::readOn(), Nucleation_paroi_PolyMAC_P0::readOn(), Rupture_bulles_1groupe_PolyMAC_P0::readOn(), Rupture_bulles_2groupes_PolyMAC_P0::readOn(), Source_injection_masse_base::readOn(), Viscosite_turbulente_sato::readOn(), Dissipation_WIT_PolyMAC_P0::readOn(), Production_HZDR_PolyMAC_P0::readOn(), Production_WIT_PolyMAC_P0::readOn(), Source_BIF_PolyMAC_P0::readOn(), Source_Dissipation_HZDR_PolyMAC_P0::readOn(), Post_Processing_Hydrodynamic_Forces_Stokes::readOn(), Maillage_FT_Disc::readOn(), Maillage_FT_Disc_Data_Cache::readOn(), Marqueur_FT::readOn(), Proprietes_part_vol::readOn(), Remaillage_FT::readOn(), Senseur_Interface::readOn(), IJK_Thermals::readOn(), Champ_Fonc_reprise_IJK::readOn(), Remaillage_FT_IJK::readOn(), Probleme_FTD_IJK_base::readOn(), Frontiere_ouverte_vitesse_vortex::readOn(), Paroi_FT_disc::readOn(), Connectivite_frontieres::readOn(), Convection_Diffusion_Concentration_FT_Disc::readOn(), Convection_Diffusion_Concentration_Turbulent_FT_Disc::readOn(), Transport_Marqueur_FT::readOn(), Descripteur_FT::readOn(), Desc_Structure_FT::readOn(), Marching_Cubes::readOn(), Remailleur_Collision_FT_Thomas::readOn(), Topologie_Maillage_FT::readOn(), Postraitement_ft_lata::readOn(), Terme_Source_Constituant_Vortex_VEF_Face::readOn(), Triple_Line_Model_FT_Disc::readOn(), Navier_Stokes_phase_field::readOn(), Source_Con_Phase_field::readOn(), Source_Qdm_VDF_Phase_field::readOn(), Modele_Rayonnement_Milieu_Transparent::readOn(), Echange_externe_impose_rayo_transp::readOn(), Equation_rayonnement_base::readOn(), Flux_radiatif_base::readOn(), Echange_externe_impose_rayo_semi_transp::readOn(), Echange_global_impose_rayo_semi_transp::readOn(), Schema_Euler_Implicite_Stationnaire::readOn(), Boundary_field_keps_from_ud::readOn(), Tenseur_Reynolds_Externe_VDF_Face::readOn(), ParoiVDF_TBLE_LRM::readOn(), Loi_Paroi_Nu_Impose_VDF::readOn(), Paroi_ODVM_scal_VDF::readOn(), Paroi_TBLE_scal_VDF::readOn(), Modele_Jones_Launder_Thermique_VDF::readOn(), Modele_Jones_Launder_VDF::readOn(), Source_Transport_Fluctuation_Temperature_VDF_Elem::readOn(), Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::readOn(), Source_Transport_Fluctuation_Temperature_W_VDF_Elem::readOn(), Source_Transport_Flux_Chaleur_Turbulente_VDF_Face::readOn(), Loi_Paroi_Nu_Impose_VEF::readOn(), Modele_Jones_Launder_VEF::readOn(), Transport_Fluctuation_Temperature_W_Bas_Re::readOn(), Domaine_EF::readOn(), Op_Conv_EF::readOn(), Source_Qdm_EF::readOn(), Source_Scalaire_EF::readOn(), Boundary_Conditions_Thermique::readOn(), Multigrille_base::readOn(), IJK_VDF_converter::readOn(), Champ_front_normal_VEF::readOn(), Ch_front_Vortex::readOn(), Sutherland::readOn(), Champ_Fonc_Fonction_txyz::readOn(), Champ_Fonc_Tabule::readOn(), Champ_front_bruite::readOn(), Champ_Front_Composite::readOn(), Champ_Front_MUSIG::readOn(), Champ_front_Tabule::readOn(), Champ_front_tangentiel::readOn(), Champ_Generique_Reduction_0D::readOn(), Champ_Input_P0_Composite::readOn(), Champ_Composite::readOn(), Champ_Don_lu::readOn(), Champ_Fonc_Fonction_txyz_Morceaux::readOn(), Champ_Fonc_t::readOn(), Champ_Fonc_Tabule_Morceaux::readOn(), champ_init_canal_sinal::readOn(), Champ_MUSIG::readOn(), Champ_Tabule_Temps::readOn(), Champ_Uniforme_Morceaux::readOn(), Champ_Uniforme_Morceaux_Tabule_Temps::readOn(), Champ_Fonc_Interp::readOn(), Echange_externe_radiatif::readOn(), Echange_impose_base::readOn(), Paroi_contact_fictif_rayo::readOn(), Paroi_contact_rayo::readOn(), Champ_front_Parametrique::readOn(), Champ_Parametrique::readOn(), Debog_Pb::readOn(), Debog_Pb_Wrapper::readOn(), Domaine_Cl_dis_base::readOn(), PDF_model::readOn(), Source_PDF_base::readOn(), List_Equations_Scalaires_Passifs_Especes::readOn(), Loi_horaire::readOn(), Porosites::readOn(), Probleme_base::readOn(), Probleme_Couple::readOn(), Schema_Temps_base::readOn(), Sources::readOn(), Decouper_32_64< _SIZE_ >::readOn(), Decouper_multi::readOn(), Partitionneur_Partition::readOn(), Partitionneur_Sous_Domaine::readOn(), Partitionneur_Sous_Domaines::readOn(), Partitionneur_Tranche_32_64< _SIZE_ >::readOn(), DomaineCutter_32_64< _SIZE_ >::readOn(), Prepro_IBM_Ponderation::readOn(), Prepro_IBM_Uzawa::readOn(), Joint_32_64< _SIZE_ >::readOn(), Pave_32_64< _SIZE_ >::readOn(), Sous_Domaine_32_64< _SIZE_ >::readOn(), Domaine_IJK::readOn(), IJK_Grid_Geometry::readOn(), Solv_AMG::readOn(), Solv_Cholesky::readOn(), Solv_GCP::readOn(), UserUnaryFunction::readOn(), Champ_Fonc_MED::readOn(), Champ_Fonc_MED_Table_Temps::readOn(), Pbc_MED::readOn(), Operateur_Conv::readOn(), Lata_2_Other::readOn(), Postraitement::readOn(), Postraitements::readOn(), Sonde::readOn(), Sonde_Int::readOn(), Sondes::readOn(), Sondes_Int::readOn(), Schema_Euler_Implicite::readOn(), Schema_Implicite_Multi_TimeStep_base::readOn(), Moyenne_volumique::readOn(), Comm_Group::readOn(), Comm_Group_MPI::readOn(), Comm_Group_Noparallel::readOn(), Execute_parallel::readOn(), Interprete::readOn(), Interprete_bloc::readOn(), Lire_Fichier::readOn(), Objet_U_ptr::readOn(), Champ_Fonc_reprise::readOn(), Domaine_Poly_base::readOn(), Correction_Antal_PolyMAC_P0::readOn(), Correction_Tomiyama_PolyMAC_P0::readOn(), DP_Impose_PolyMAC_Face::readOn(), Perte_Charge_Anisotrope_PolyMAC_Face::readOn(), Perte_Charge_Circulaire_PolyMAC_Face::readOn(), Perte_Charge_Directionnelle_PolyMAC_Face::readOn(), Terme_Source_Decroissance_Radioactive_Elem_PolyMAC::readOn(), Terme_Source_Qdm_Face_PolyMAC::readOn(), Reaction::readOn(), Convection_Diffusion_Espece_Binaire_base::readOn(), Source_Masse_Fluide_Dilatable_base::readOn(), Navier_Stokes_QC::readOn(), Loi_Etat_rhoT_GP_QC::readOn(), Source_QC_QDM_Gen::readOn(), Navier_Stokes_WC::readOn(), Loi_Etat_GP_WC::readOn(), Loi_Etat_Multi_GP_WC::readOn(), Champ_front_synt::readOn(), Entree_fluide_T_h_imposee::readOn(), Neumann_sortie_libre::readOn(), Sortie_libre_Text_H_ext::readOn(), Perte_Charge_Gen::readOn(), Terme_Source_Acceleration::readOn(), Diametre_bulles_constant::readOn(), Diametre_bulles_musig::readOn(), Dispersion_bulles_constante::readOn(), Flux_parietal_diphasique_simple_lineaire::readOn(), Frottement_interfacial_bulles_composant::readOn(), Frottement_interfacial_bulles_constant::readOn(), Frottement_interfacial_Garnier::readOn(), Frottement_interfacial_Ishii_Zuber::readOn(), Frottement_interfacial_Rusche::readOn(), Frottement_interfacial_Simonnet::readOn(), Frottement_interfacial_Sonnenburg::readOn(), Frottement_interfacial_Tomiyama::readOn(), Frottement_interfacial_Wallis::readOn(), Frottement_interfacial_Weber::readOn(), Frottement_interfacial_Zenit::readOn(), Masse_ajoutee_Coef_Constant::readOn(), Masse_ajoutee_Wijngaarden::readOn(), Masse_ajoutee_Zuber::readOn(), Multiplicateur_diphasique_Friedel::readOn(), Multiplicateur_diphasique_homogene::readOn(), Multiplicateur_diphasique_Lottes_Flinn::readOn(), Multiplicateur_diphasique_Muhler_Steinhagen::readOn(), Portance_interfaciale_Constante::readOn(), Portance_interfaciale_Sugrue::readOn(), Portance_interfaciale_Tomiyama::readOn(), Vitesse_relative_base::readOn(), Aire_interfaciale::readOn(), QDM_Multiphase::readOn(), Fluide_MUSIG::readOn(), Fluide_reel_base::readOn(), Milieu_composite::readOn(), Milieu_MUSIG::readOn(), Saturation_constant::readOn(), Op_Evanescence_Homogene_Face_base::readOn(), Pb_Multiphase::readOn(), Source_Dispersion_bulles_base::readOn(), Source_Flux_interfacial_base::readOn(), Source_Force_Tchen_base::readOn(), Source_Frottement_interfacial_base::readOn(), Source_Portance_interfaciale_base::readOn(), Transport_turbulent_Prandtl::readOn(), Transport_turbulent_SGDH::readOn(), Viscosite_turbulente_multiple::readOn(), Viscosite_turbulente_Smagorinsky::readOn(), Viscosite_turbulente_WALE::readOn(), Simpler_Base::readOn(), Navier_Stokes_Turbulent_QC::readOn(), Modele_turbulence_hyd_base::readOn(), Modele_turbulence_hyd_null::readOn(), Modele_turbulence_scal_base::readOn(), Modele_turbulence_scal_null::readOn(), Echange_interne_global_impose::readOn(), Champ_Don_Face_lu::readOn(), Champ_front_debit_QC::readOn(), Champ_front_debit_QC_fonc_t::readOn(), Echange_interne_impose::readOn(), Correction_Antal_VDF::readOn(), Terme_Source_Canal_RANS_LES_VDF_Elem::readOn(), Terme_Source_Canal_RANS_LES_VDF_Face::readOn(), Perte_Charge_Anisotrope_VDF_Face::readOn(), Perte_Charge_Circulaire_VDF_Face::readOn(), Perte_Charge_Directionnelle_VDF_Face::readOn(), Terme_Source_Qdm_VDF_Face::readOn(), Terme_Source_Solide_SWIFT_VDF::readOn(), Domaine_VEF::readOn(), VEF_discretisation::readOn(), Op_Conv_EF_VEF_P1NC::readOn(), Op_Conv_EF_VEF_P1NC_Stab::readOn(), Op_Conv_Muscl3_VEF_Face::readOn(), Op_Conv_VEF_Face::readOn(), Op_Diff_VEF_Face_Penalise::readOn(), Op_Diff_VEF_Face_Stab::readOn(), Op_Diff_VEFP1NCP1B_Face::readOn(), Op_Dift_Stab_VEF_Face::readOn(), Op_Dift_standard_VEF_Face::readOn(), Terme_Source_Canal_RANS_LES_VEF_Face::readOn(), DP_Impose_VEF_Face::readOn(), Perte_Charge_Anisotrope_VEF_P1NC::readOn(), Perte_Charge_Circulaire_VEF_P1NC::readOn(), Perte_Charge_Directionnelle_VEF_P1NC::readOn(), Perte_Charge_VEF::readOn(), Terme_Source_Decroissance_Radioactive_VEF_Face::readOn(), Terme_Source_Qdm_lambdaup_VEF_Face::readOn(), Terme_Source_Qdm_VEF_Face::readOn(), Terme_Source_Rappel_T_VEF_Face::readOn(), Modele_turbulence_hyd_Longueur_Melange_VEF::readOn(), TRUSTArray< _TYPE_, _SIZE_ >::readOn(), TRUSTTab< _TYPE_, _SIZE_ >::readOn(), TRUSTVect< _TYPE_, _SIZE_ >::readOn(), TRUST_List< _CLASSE_ >::readOn(), Equation_IBM_proto::readOn_ibm_proto(), Source_Transport_proto::readOn_real(), Beam_model::readRestartFile(), Reaction::reagir(), Cond_Lim_rayo_semi_transp::recherche_emissivite_et_A(), Maillage_FT_IJK::recopie(), Maillage_FT_IJK::recopie_force_compo(), Champ_front_base::reculer(), Champ_front_instationnaire_base::reculer(), Champ_front_var_instationnaire::reculer(), Redistribute_Field::redistribute_(), TRUSTArray< _TYPE_, _SIZE_ >::ref_as_big(), TRUSTArray< _TYPE_, _SIZE_ >::ref_as_small(), Postprocessing_IJK::register_interface_field(), Postraitement_ft_lata::register_interface_field(), Precond_base::reinit(), FT_Field::remailler_FT_Field(), Table::remplir(), Assembleur_P_VEF::remplir(), Assembleur_P_VDF::remplir(), Porosites::remplir_champ(), Champ_front_contact_VEF::remplir_connect_bords(), Champ_Face_VDF_implementation::remplir_coord_noeuds(), Champ_P1NC_implementation::remplir_coord_noeuds(), Champ_Q1NC_implementation::remplir_coord_noeuds(), Champ_P1iP1B_implementation::remplir_coord_noeuds_et_polys(), Marching_Cubes::remplir_data_marching_cubes(), Connectivite_frontieres::remplir_def_face_aretes(), Domaine_VF::remplir_face_voisins_fictifs(), Connectivite_frontieres::remplir_faces_voisins(), Op_Dift_VEF_Face_Q1::remplir_nu(), Op_Dift_VEF_P1NCP1B_Face::remplir_nu(), Op_Diff_VEFP1NCP1B_Face::remplir_nu_pA(), DP_Impose_PolyMAC_Face::remplir_num_faces(), Perte_Charge_Singuliere_PolyMAC_Face::remplir_num_faces(), Perte_Charge_Singuliere_VDF_Face::remplir_num_faces(), DP_Impose_VEF_Face::remplir_num_faces(), Perte_Charge_Singuliere_VEF_Face::remplir_num_faces(), Traitement_particulier_NS_canal::remplir_reordonne_Y_tot(), Op_Diff_RotRot::remplir_som_som_EF(), IJK_Thermal_base::remplir_tableau_pure_cellules_diphasiques(), Domaine_Cl_VEF::remplir_type_elem_Cl(), Champ_front_ALE_Beam::remplir_vit_som_bord_ALE(), Navier_Stokes_std_ALE::renewing_jacobians(), Traitement_particulier_NS_THI_VEF::renorm_Ec(), Reordonner_faces_periodiques_32_64< _SIZE_ >::renum_som_perio(), Hexaedre_32_64< _SIZE_ >::reordonner(), Hexaedre_VEF_32_64< _SIZE_ >::reordonner(), Prisme_32_64< _SIZE_ >::reordonner(), Rectangle_32_64< _SIZE_ >::reordonner(), Scatter::reordonner_faces_de_joint(), Objet_U::reprendre(), Navier_Stokes_std_ALE::reprendre(), Maillage_FT_Disc::reprendre(), Remaillage_FT::reprendre(), Transport_Interfaces_FT_Disc::reprendre(), Champ_Fonc_base::reprendre(), Champ_Inc_base::reprendre(), Paroi_TBLE_QDM::reprendre(), Paroi_TBLE_QDM_Scal::reprendre(), Collision_Model_FT_base::reprendre(), Transport_Interfaces_FT_Disc_interne::reprendre(), Postraitement::reprendre(), Operateurs_Statistique_tps::reprendre(), Modele_turbulence_hyd_2_eq_base::reprendre_generique(), Champ_Fonc_reprise_IJK::reprendre_IJK(), Traitement_particulier_NS_Profils::reprendre_stat(), Traitement_particulier_NS_Profils_thermo_VDF::reprendre_stat(), Traitement_particulier_NS_canal::reprendre_stat_canal(), Ch_front_Vortex::reprendre_vortex(), Convection_Diffusion_Fluide_Dilatable_Proto::Reprendre_WC(), Precond_local::res_syst_loc_hybride(), Precond_local::res_syst_loc_simple(), Source_base::resetTime(), Format_Post_base::resetTime(), Discretisation_base::residu(), EDO_Pression_th_VDF_Gaz_Parfait::resoudre(), EDO_Pression_th_VDF_Gaz_Reel::resoudre(), EDO_Pression_th_VEF_Gaz_Parfait::resoudre(), EDO_Pression_th_VEF_Gaz_Reel::resoudre(), Fluide_Weakly_Compressible::Resoudre_EDO_PT(), Solv_Cholesky::resoudre_systeme(), Solv_Gen::resoudre_systeme(), Solv_Gmres::resoudre_systeme(), Solv_Petsc::resoudre_systeme(), Solv_GCP_NS::resoudre_systeme(), Solv_rocALUTION::resoudre_systeme(), Discret_Thyd::reynolds_maille(), Viscosite_turbulente_k_omega::reynolds_stress(), Viscosite_turbulente_k_tau::reynolds_stress(), Viscosite_turbulente_sato::reynolds_stress(), Viscosite_turbulente_WIF::reynolds_stress(), Viscosite_turbulente_WIT::reynolds_stress(), Viscosite_turbulente_LES_base::reynolds_stress(), Navier_Stokes_std::rho_la_vitesse(), DNS_QC_double::rk3_sub_step(), Navier_Stokes_FTD_IJK::rk3_sub_step(), IJK_Thermals::rk3_sub_step(), DNS_QC_double::run(), Objet_U::sauvegarder(), Maillage_FT_Disc::sauvegarder(), Remaillage_FT::sauvegarder(), Transport_Interfaces_FT_Disc::sauvegarder(), Champ_Inc_base::sauvegarder(), Save_Restart::sauver(), Probleme_Couple::sauver(), DNS_QC_double::save_raw_data(), Matrice_Petsc::scale(), Schema_Comm_Vecteurs::Schema_Comm_Vecteurs(), Equation_base::schema_temps(), Probleme_base::schema_temps(), Probleme_Couple::schema_temps(), Modele_turbulence_hyd_RANS_Bicephale_base::seconde_equation(), Modele_Fonc_Bas_Reynolds_Base::seconde_equation(), Modele_Fonc_Realisable_base::seconde_equation(), Cut_cell_diffusion_auxiliaire::select_flux_interface(), Comm_Group_MPI::send_recv_start(), Entree::set_bin(), Entree_Brute::set_bin(), Entree_complete::set_bin(), SChaine::set_bin(), Sortie::set_bin(), Sortie_Brute::set_bin(), Champ_Generique_Interpolation::set_domaine(), Operateur_base::set_fichier(), Operateur_Conv_base::set_incompressible(), Collision_Model_FT_base::set_LC_zones(), Champ_Generique_Interpolation::set_localisation(), Champ_Generique_Interpolation::set_methode(), Comm_Group_MPI::set_must_mpi_initialize(), Solveur_Masse_base::set_name_of_coefficient_temporel(), Navier_Stokes_std_sensibility::set_param(), Format_Post_Lata::set_param(), Postraitement::set_param(), CoolProp_to_TRUST::set_path_refprop(), IJK_Interfaces::set_seuil_indicatrice_petite(), Parametre_implicite::set_seuil_solveur_avec_seuil_convergence_solveur(), Format_Post_base::set_single_lata_option(), Comm_Group_MPI::set_trio_u_world(), ICoCo::ProblemTrio::setStationaryMode(), SFichier::SFichier(), Catch_SIGINIT::signal_callback_handler(), Conduction::solide(), Matrice_Dense::solve(), Solv_Gen::solve(), Multigrille_base::solve_ijk_in_storage_template(), Probleme_FTD_IJK_base::solveTimeStep(), Sortie::Sortie(), Terme_Source_Canal_perio::source(), Terme_Source_Canal_perio_VDF_P0::source_convection_diffusion(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::stabilise_moyenne(), Modele_turbulence_scal_LES_dyn_VDF::stabilise_moyenne(), Transport_Interfaces_FT_Disc::StockageFa7(), Param::supprimer(), Param::supprimer_condition(), Transport_Interfaces_FT_Disc::swap_particles_lagrangian_position_velocity(), Switch_FT_double::Switch_FT_double(), Sortie::syncfile(), Synonyme_info::Synonyme_info(), Echange_global_impose_turbulent::T_ext(), Echange_impose_base::T_ext(), Discret_Thermique::t_paroi(), Eval_Dift_VDF_Face::tau_tan_impl(), Paroi_std_hyd_VDF::tau_tang(), Discret_Thyd::taux_cisaillement(), Op_Diff_VEFP1NCP1B_Face::test(), Option_VDF::test_mot(), Operateur_base::tester_contribuer_a_avec(), Echange_contact_VDF_FT_Disc::Ti_wall(), Champ_base::trace(), Champ_P1_isoP1Bulle::trace(), Champ_Face_VDF_implementation::trace(), Frontiere_32_64< _SIZE_ >::trace_elem_distant(), Raccord_distant_homogene_32_64< _SIZE_ >::trace_elem_distant(), Frontiere_32_64< _SIZE_ >::trace_elem_local(), Frontiere_32_64< _SIZE_ >::trace_face_distant(), Frontiere_32_64< _SIZE_ >::trace_face_local(), Champ_front_contact_VEF::trace_face_raccord(), Frontiere_32_64< _SIZE_ >::trace_som_distant(), Frontiere_32_64< _SIZE_ >::trace_som_local(), Remailleur_Collision_FT_Juric::traite_RuptureCoalescenceInterfaces(), Fourier_trans::Traitement_spectral(), Moyenne_volumique::traiter_champs(), Transport_Marqueur_FT::transformer_particules(), Remailleur_Collision_FT_Thomas::transport_volume_perdu_sur_element(), IJK_Interfaces::transporter_maillage_remaillage(), Matrice_Morse::transpose(), Op_Diff_RotRot::Tri(), Tetraedriser::trianguler(), Tetraedriser_homogene::trianguler(), Tetraedriser_homogene_compact::trianguler(), Tetraedriser_homogene_fin::trianguler(), Trianguler_fin::trianguler(), Marching_Cubes::trier_les_noeuds(), Aretes::trier_pour_debog(), TRUSTTab< _TYPE_, _SIZE_ >::TRUSTTab(), Type_info::Type_info(), Maillage_FT_Disc::type_statut(), Objet_U_ptr::typer(), Domaine_VEF::typer_elem(), Domaine_EF::typer_elem(), Domaine_Poly_base::typer_elem(), Pb_Multiphase_HEM::typer_lire_correlation_hem(), Pb_Multiphase::typer_lire_milieu(), Turbulence_paroi_base::typer_lire_turbulence_paroi(), Turbulence_paroi_scal_base::typer_lire_turbulence_paroi_scal(), Sortie::unlockfile(), Schema_Temps_base::update_critere_statio(), Champ_Fonc_Interp::update_fields(), Milieu_base::update_rho_cp(), Maillage_FT_IJK::update_sigma_and_interfacial_source_term_sommet(), Statistiques_dns_ijk::update_stat(), Statistiques_dns_ijk_monophasique::update_stat(), Statistiques_dns_ijk::update_stat_k(), Domaine_IJK::update_volume_elem(), Navier_Stokes_std::update_y_plus(), Navier_Stokes_std::uzawa(), Table::val(), Sortie_libre_Text_H_ext::val_ext(), Neumann_sortie_libre::val_ext(), Entree_fluide_T_h_imposee::val_imp(), Dirichlet::val_imp_au_temps(), Dirichlet_loi_paroi::val_imp_au_temps(), Frontiere_ouverte_rho_u_impose::val_imp_au_temps(), ptrParam::valeur(), Champ_base::valeur_a_elem(), Champ_base::valeur_a_elem_compo(), champ_init_canal_sinal::valeur_a_elem_compo(), Champ_base::valeur_a_sommet_compo(), Champ_P1_isoP1Bulle::valeur_au_bord(), Champ_front_var_instationnaire::valeur_au_temps_et_au_point(), Ch_front_input_P1::valeur_au_temps_et_au_point(), Champ_base::valeur_aux(), Champ_Inc_base::valeur_aux_bords(), Champ_implementation_P0::valeur_aux_centres_de_gravite(), Champ_P1NC_implementation::valeur_aux_centres_de_gravite(), Champ_base::valeur_aux_elems(), Champ_P1iP1B_implementation::valeur_aux_elems(), Champ_P1NC_implementation::valeur_aux_elems(), Champ_Q1NC_implementation::valeur_aux_elems(), Champ_Fonc_Face_PolyMAC::valeur_aux_elems(), Champ_Face_PolyMAC::valeur_aux_elems_(), Champ_base::valeur_aux_elems_compo(), Champ_P1iP1B_implementation::valeur_aux_elems_compo(), Champ_som_lu_VEF::valeur_aux_elems_compo(), Champ_base::valeur_aux_elems_compo_smooth(), Champ_P1NC_implementation::valeur_aux_elems_compo_smooth(), Champ_base::valeur_aux_elems_smooth(), Champ_P1NC_implementation::valeur_aux_elems_smooth(), Champ_Face_PolyMAC::valeur_aux_faces(), Champ_Face_PolyMAC_P0P1NC::valeur_aux_faces(), Champ_Fonc_Face_PolyMAC::valeur_aux_faces(), Champ_Face_VDF_implementation::valeur_aux_sommets(), Champ_P1iP1B_implementation::valeur_aux_sommets(), Champ_Face_VDF_implementation::valeur_aux_sommets_compo(), Champ_P1iP1B_implementation::valeur_aux_sommets_compo(), Champ_Inc_base::valeurs(), Table::valeurs(), Champ_front_vide::valeurs_au_temps(), Champ_front_instationnaire_base::valeurs_au_temps(), Champ_front_var_instationnaire::valeurs_au_temps(), MD_Vector_base::validate(), Sonde_IJK::validate_position(), Sonde_IJK::validate_type(), Champ_implementation_Q1::value_interpolation(), Transport_Interfaces_FT_Disc::verif_Cl(), Champ_Post_Operateur_Eqn::verification_cas_compo(), Memoire::verifie(), Equation_base::verifie_ch_init_nb_comp(), Energie_Multiphase::verifie_ch_init_nb_comp_cl(), Domaine_EF::verifie_compatibilite_domaine(), Domaine_EF_axi::verifie_compatibilite_domaine(), Modele_turbulence_hyd_2_eq_base::verifie_loi_paroi(), Modele_turbulence_hyd_LES_base::verifie_loi_paroi_diphasique(), IJK_Thermals::verifie_milieu(), NettoieNoeuds_32_64< _SIZE_ >::verifie_noeuds(), Postraitement::verifie_nom_et_sources(), Discretisation_base::verifie_sous_type(), Pb_Hydraulique_Concentration_Turbulent::verifier(), Pb_Hydraulique_Melange_Binaire_Turbulent_QC::verifier(), Pb_Thermohydraulique_Concentration_Turbulent::verifier(), Pb_Thermohydraulique_Turbulent_QC::verifier(), Source_Transport_proto::verifier_beta_concen(), Milieu_base::verifier_coherence_champs(), Champ_Generique_Transformation::verifier_coherence_donnees(), Echange_contact_VDF::verifier_correspondance(), Assembleur_P_VEFPreP1B::verifier_dirichlet(), Champ_Generique_Transformation::verifier_localisation(), Debog_Pb::verifier_Mat_elems(), Debog_Pb::verifier_matrice(), Source_Transport_proto::verifier_pb_komega(), Loi_Etat_TPPI_base::verify_fields(), CoolProp_to_TRUST::verify_phase(), IJK_Thermal_base::vide_phase_invalide_cellules_diphasiques(), Discr_inst::volume_maille(), EF_discretisation::vorticite(), VEF_discretisation::vorticite(), Domaine_PolyMAC::W_stabiliser(), Champ_Fonc_Tabule::Warn_old_chp_fonc_syntax_V_184(), Probleme_base::warn_old_syntax(), Fluide_Dilatable_base::warn_syntax_Sutherland(), Ecrire_fichier_xyz_valeur::write_fields(), Terme_Source_Canal_perio::write_flow_rate(), Debog_Pb::write_geometry_data(), LireMED_32_64< _SIZE_ >::write_sub_dom_datasets(), and Discret_Thyd::y_plus().
mp_max() [1/3]
double Process::mp_max (double x) static
References Comm_Group::COLL_MAX.
Referenced by Op_Diff_VEF_Face_Stab::ajouter_antidiffusion(), DP_Impose_PolyMAC_Face::ajouter_blocs(), DP_Impose_VEF_Face::ajouter_blocs(), Masse_VDF_base::ajouter_blocs(), Solveur_Masse_base::ajouter_masse(), Solveur_Masse_base::ajouter_masse_dt_local(), Assembleur_P_EF::assembler_mat(), Maillage_FT_Disc::calcul_courbure_sommets(), Traitement_particulier_NS_THI_VEF::calcul_Df_spatial(), Traitement_particulier_NS_THI_VEF::calcul_nu_t(), Cut_cell_surface_efficace::calcul_surface_face_efficace_iteratif(), Traitement_particulier_NS_temperature_VEF::calcul_temperature(), Moyenne_volumique::calculer_convolution(), IJK_Thermal_base::calculer_dT(), Op_Diff_K_Eps_Bas_Re_VDF_var_Elem::calculer_dt_stab(), Op_Diff_DG_base::calculer_dt_stab(), Op_Conv_EF::calculer_dt_stab(), Op_Diff_PolyMAC_base::calculer_dt_stab(), Op_Dift_Multiphase_VDF_Elem::calculer_dt_stab(), Op_Dift_Multiphase_VDF_Face::calculer_dt_stab(), Op_Conv_Muscl_New_VEF_Face::calculer_dt_stab(), Op_Diff_VEF_base::calculer_dt_stab(), Op_Dift_VDF_Face_base::calculer_dt_stab(), Op_Dift_VDF_Elem_base::calculer_dt_stab_elem(), Scatter::calculer_espace_distant_elements(), Domaine_DG::calculer_h_carre(), IJK_Interfaces::calculer_surfactant(), Modele_turbulence_hyd_K_Eps::calculer_viscosite_turbulente(), Modele_turbulence_hyd_K_Eps_Bas_Reynolds::calculer_viscosite_turbulente(), Modele_turbulence_hyd_K_Eps_Bicephale::calculer_viscosite_turbulente(), Modele_turbulence_hyd_K_Eps_Realisable::calculer_viscosite_turbulente(), Modele_turbulence_hyd_K_Eps_Realisable_Bicephale::calculer_viscosite_turbulente(), Modele_turbulence_hyd_K_Omega::calculer_viscosite_turbulente(), FT_Field::calculer_volume_bulles(), FT_Field::check_conservation(), Reordonner_faces_periodiques_32_64< _SIZE_ >::check_faces_periodiques(), Fluide_reel_base::check_unknown_range(), Triple_Line_Model_FT_Disc::completer(), FT_Field::completer_compo_connexe_partielle(), Quadrature_Ord1_Polygone::compute_integ_points(), Quadrature_Ord3_Polygone::compute_integ_points(), Quadrature_Ord5_Polygone::compute_integ_points(), IJK_One_Dimensional_Subproblems::compute_overall_quantities_per_bubbles(), Convection_Diffusion_Temperature_FT_Disc::correct_mpoint(), FT_Field::correction_conservation_globale(), Traitement_particulier_NS_CEG::critere_areva(), Traitement_particulier_NS_CEG::critere_cea_jaea(), Maillage_FT_IJK::deplacer_sommets(), Statistiques::dump(), IJK_Interfaces::dupliquer_bulle_perio(), Decouper_32_64< _SIZE_ >::ecrire(), Schema_Temps_IJK_base::find_timestep(), Ensemble_Lagrange_base::generer_marqueurs_sz(), IJK_One_Dimensional_Subproblems::get_local_max_cfl_time_step_probe_length(), IJK_One_Dimensional_Subproblems::get_local_max_fourier_time_step_probe_length(), IJK_One_Dimensional_Subproblems::get_max_temperature(), IJK_One_Dimensional_Subproblems::get_max_temperature_domain_ends(), IJK_One_Dimensional_Subproblems::get_min_euler_time_step(), Ch_front_input::getTemplate(), Ch_front_input_P1::getTemplate(), Cut_cell_surface_efficace::imprimer_informations_surface_efficace_face(), Cut_cell_surface_efficace::imprimer_informations_surface_efficace_interface(), imprimer_ram_totale(), Domaine_VF::init_dist_paroi_globale(), Sonde::initialiser(), Sonde_Int::initialiser(), Echange_contact_PolyMAC::initialiser(), IJK_Interfaces::initialize(), MaillerParallel::interpreter(), Scatter::lire_domaine(), Transport_Interfaces_FT_Disc::lire_maillage_ft_cao(), Echange_contact_VDF_FT_Disc::mettre_a_jour(), Assembleur_P_VEFPreP1B::modifier_matrice(), Format_Post_Lata::modify_file_basename(), Champ_Fonc_MED::readOn(), DP_Impose_PolyMAC_Face::readOn(), DP_Impose_VEF_Face::readOn(), Assembleur_P_VEF::remplir(), Assembleur_P_VDF::remplir(), DP_Impose_PolyMAC_Face::remplir_num_faces(), Perte_Charge_Singuliere_PolyMAC_Face::remplir_num_faces(), DP_Impose_VEF_Face::remplir_num_faces(), Perte_Charge_Singuliere_VEF_Face::remplir_num_faces(), Collision_Model_FT_base::research_collision_pairs_Verlet(), Solv_Petsc::resoudre_systeme(), Collision_Model_FT_base::set_geometric_parameters(), Collision_Model_FT_base::set_LC_zones(), Topologie_Maillage_FT::test_collision_facettes(), and SETS::unknown_positivation().
mp_min() [1/3]
double Process::mp_min (double x) static
References Comm_Group::COLL_MIN.
Referenced by Op_Diff_VEF_Face_Stab::ajouter_antidiffusion(), Assembleur_P_PolyMAC_P0::assembler_mat(), Traitement_particulier_NS_THI_VEF::calcul_Df_spatial(), Traitement_particulier_NS_THI_VEF::calcul_nu_t(), Traitement_particulier_NS_temperature_VEF::calcul_temperature(), Transport_Interfaces_FT_Disc::calcul_vitesse(), IJK_Thermal_base::calculer_dT(), Op_Conv_ALE_VEF::calculer_dt_stab(), Operateur_Conv_sensibility_VEF::calculer_dt_stab(), Op_Diff_DG_base::calculer_dt_stab(), Op_Conv_EF::calculer_dt_stab(), Op_Conv_EF_base::calculer_dt_stab(), Op_Diff_EF_base::calculer_dt_stab(), Op_Dift_EF_Q1::calculer_dt_stab(), Op_Conv_PolyMAC_iterateur_base::calculer_dt_stab(), Op_Conv_EF_Stab_PolyMAC_P0_Face::calculer_dt_stab(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::calculer_dt_stab(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Face::calculer_dt_stab(), Op_Diff_PolyMAC_base::calculer_dt_stab(), Op_Diff_PolyMAC_P0_Elem::calculer_dt_stab(), Op_Diff_PolyMAC_P0_Face::calculer_dt_stab(), Op_Diff_PolyMAC_P0P1NC_Elem::calculer_dt_stab(), Op_Diff_PolyMAC_P0P1NC_Face::calculer_dt_stab(), Op_Conv_VDF_base::calculer_dt_stab(), Op_Diff_VDF_Elem_base::calculer_dt_stab(), Op_Conv_VEF_base::calculer_dt_stab(), Op_Diff_VEF_base::calculer_dt_stab(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab(), Op_Dift_VEF_base::calculer_dt_stab(), Op_Diff_VDF_base::calculer_dt_stab_(), Op_Dift_VEF_base::calculer_dt_stab_P1NCP1B(), Domaine_VEF::calculer_h_carre(), Operateur::calculer_pas_de_temps(), Probleme_FT_Disc_gen::calculer_pas_de_temps(), IJK_Interfaces::calculer_phi_repuls_sommet(), Senseur_Interface::calculer_position(), IJK_Interfaces::calculer_surfactant(), Fluide_reel_base::check_unknown_range(), Champ_Generique_Reduction_0D::completer(), Marching_Cubes::construire_noeuds_et_facettes(), Traitement_particulier_NS_CEG::critere_cea_jaea(), Statistiques::dump(), Champ_P1NC_implementation::filtrer_resu(), Schema_Temps_IJK_base::find_timestep(), Ensemble_Lagrange_base::generer_marqueurs_sz(), Champ_Generique_Interpolation::get_champ_with_calculer_champ_post(), IJK_One_Dimensional_Subproblems::get_local_dt_cfl(), IJK_One_Dimensional_Subproblems::get_local_dt_cfl_min_delta_xyz(), IJK_One_Dimensional_Subproblems::get_local_min_cfl_time_step_probe_length(), IJK_One_Dimensional_Subproblems::get_local_min_fourier_time_step_probe_length(), IJK_One_Dimensional_Subproblems::get_min_euler_time_step(), IJK_One_Dimensional_Subproblems::get_min_temperature(), IJK_One_Dimensional_Subproblems::get_min_temperature_domain_ends(), IJK_Interfaces::imprime_bilan_indicatrice(), Remailleur_Collision_FT_Thomas::mettre_a_jour_data(), Maillage_FT_IJK::minimum_longueur_arrete(), Assembleur_P_VEF::modifier_matrice(), Assembleur_P_VEFPreP1B::modifier_matrice(), Remaillage_FT::regulariser_courbure(), Collision_Model_FT_base::set_geometric_parameters(), and Domaine_ALE::solveDynamicMeshProblem().
mp_max() [2/3]
int Process::mp_max (int x) static
renvoie le plus grand int i sur l'ensemble des processeurs du groupe courant.
References Comm_Group::COLL_MAX.
mp_min() [2/3]
int Process::mp_min (int x) static
renvoie le plus petit int i sur l'ensemble des processeurs du groupe courant.
References Comm_Group::COLL_MIN.
mp_max() [3/3]
trustIdType Process::mp_max (trustIdType x) static
References Comm_Group::COLL_MAX.
mp_min() [3/3]
trustIdType Process::mp_min (trustIdType x) static
References Comm_Group::COLL_MIN.
mp_sum() [1/4]
double Process::mp_sum (double x) static
Calcule la somme de x sur tous les processeurs du groupe courant.
See also
mp_max()
References Comm_Group::COLL_SUM, PE_Groups::current_group(), and Comm_Group::mp_collective_op().
Referenced by Terme_Source_Constituant_Vortex_VEF_Face::ajouter_terme_div_u(), Assembleur_P_VEFPreP1B::assembler_mat(), Ensemble_Faces_base::associer_les_cl(), Traitement_particulier_NS_chmoy_faceperio_VEF::calcul_chmoy_faceperio(), Maillage_FT_Disc::calcul_courbure_sommets(), Traitement_particulier_NS_THI_VEF::calcul_Df_spatial(), Traitement_particulier_NS_THI_VDF::calcul_Ec_D(), Champ_P1NC::calcul_h_conv(), Champ_front_recyclage::calcul_moyenne_recyclee(), Traitement_particulier_NS_THI::calcul_nb_elem_dir(), Traitement_particulier_NS_THI::calcul_nb_som_dir(), Traitement_particulier_NS_THI_VEF::calcul_nu_t(), DNS_QC_double::calcul_p_thermo_et_bilan(), Traitement_particulier_NS_canal::calcul_reynolds_tau(), Traitement_particulier_NS_THI_VEF::calcul_Sk(), Traitement_particulier_NS_THI_VDF::calcul_skewness_ordre_2(), Traitement_particulier_NS_temperature_VEF::calcul_temperature(), Traitement_particulier_NS_THI_VEF::calcul_vitesse_moyenne(), Traitement_particulier_NS_THI_VEF::calcul_volume_elem(), Terme_Source_Constituant_Vortex_VEF_Face::calculer(), Terme_Source_Canal_perio_VDF_Face::calculer_debit(), Terme_Source_Canal_perio_VEF_P1NC::calculer_debit(), Traitement_particulier_NS_EC::calculer_Ec(), IJK_Thermal_base::calculer_ecart_T_ana(), Domaine_VEF::calculer_h_carre(), Transport_Interfaces_FT_Disc::calculer_integrale_indicatrice(), Algorithmes_Transport_FT_Disc::calculer_moments_indicatrice(), Navier_Stokes_FTD_IJK::calculer_moyenne_de_phase_liq(), Navier_Stokes_FTD_IJK::calculer_moyenne_de_phase_vap(), Champ_front_xyz_debit::calculer_normales_et_integrale(), IJK_Interfaces::calculer_phi_repuls_sommet(), IJK_Thermal_base::calculer_source_temperature_ana(), IJK_Interfaces::calculer_surfactant(), Face_Rayonnante::calculer_temperature(), IJK_Thermal_base::calculer_temperature_adim_bulles(), Remaillage_FT::calculer_variation_volume(), Navier_Stokes_FTD_IJK::calculer_vitesse_droite(), Navier_Stokes_FTD_IJK::calculer_vitesse_gauche(), FT_Field::check_conservation(), Schema_Comm::check_send_recv_pe_list(), EcrFicPartage::close(), IJK_One_Dimensional_Subproblems::complete_subproblems(), IJK_Thermal_Onefluid::compute_dT_rustine(), IJK_Thermal_base::compute_global_energy(), IJK_One_Dimensional_Subproblems::compute_global_indices(), Terme_Source_Canal_perio::compute_heat_flux(), Quadrature_base::compute_integral(), Collision_Model_FT_sphere::compute_lagrangian_contact_forces(), IJK_Thermal_Subresolution::compute_mean_liquid_temperature(), Triple_Line_Model_FT_Disc::compute_TCL_fluxes_in_all_boundary_cells(), Domain_Graph::construire_graph_elem_elem(), Solv_Externe::construit_renum(), Convection_Diffusion_Temperature_FT_Disc::correct_mpoint(), FT_Field::correction_conservation_globale(), Traitement_particulier_NS_CEG::critere_cea_jaea(), Transport_Interfaces_FT_Disc::deplacer_maillage_ft_v_fluide(), Maillage_FT_Disc::deplacer_sommets(), Maillage_FT_IJK::deplacer_sommets(), Convection_Diffusion_Temperature_FT_Disc::derivee_en_temps_inco(), Op_EF_base::dimensionner(), Sous_domaine_VF::discretiser(), Remaillage_FT::diviser_grandes_aretes(), Remaillage_FT_IJK::diviser_grandes_aretes(), IJK_Interfaces::dumplata_ft_mesh(), IJK_Interfaces::dupliquer_bulle_perio(), Postraiter_domaine::ecrire(), Format_Post_Lml::ecrire_champ_lml(), Format_Post_Lml::ecrire_domaine_lml(), Convection_Diffusion_Temperature::ecrire_fichier_pena_th(), Parcours_interface::eloigner_sommets_des_faces(), Schema_Comm_Vecteurs::end_init(), Champ_val_tot_sur_vol_VDF::eval_contrib_loc(), Champ_val_tot_sur_vol_VEF::eval_contrib_loc(), IJK_Thermal_Subresolution::evaluate_total_liquid_absolute_parameter(), IJK_Thermal_Subresolution::evaluate_total_liquid_parameter_squared(), MD_Vector_std::fill_md_vect_renum(), Postprocessing_IJK::get_IJK_field(), Postprocessing_IJK::get_IJK_field_vector(), Mass_Redistribution_Phase_Field::impose_mass_redistribution(), Iterateur_Source_EF_Som< _TYPE_ >::impr(), Op_EF_base::impr(), Op_Div_EF::impr(), Op_Grad_EF::impr(), Op_Div_PolyMAC::impr(), IJK_Interfaces::imprime_bilan_indicatrice(), Cut_cell_surface_efficace::imprimer_informations_surface_efficace_face(), Cut_cell_surface_efficace::imprimer_informations_surface_efficace_interface(), imprimer_ram_totale(), Paroi_2couches_VDF::imprimer_ustar(), Domaine_VF::info_elem_som(), Domaine_VF::infobord(), Traitement_particulier_NS_chmoy_faceperio_VEF::init_calcul_stats(), Navier_Stokes_FTD_IJK::initialise_ijk_fields(), Sonde::initialiser(), Champ_front_lu::initialiser(), FT_Field::initialize(), Scatter::lire_domaine(), Remaillage_FT::marquer_aretes(), Source_Masse_Fluide_Dilatable_base::mettre_a_jour(), Convection_Diffusion_Concentration_FT_Disc::mettre_a_jour(), Convection_Diffusion_Concentration_Turbulent_FT_Disc::mettre_a_jour(), Convection_Diffusion_Temperature_FT_Disc::mettre_a_jour(), Transport_Interfaces_FT_Disc::mettre_a_jour(), Champ_front_pression_from_u::mettre_a_jour(), Champ_front_synt::mettre_a_jour(), Champ_front_debit_QC::mettre_a_jour(), Champ_front_debit_QC_fonc_t::mettre_a_jour(), Echange_contact_VDF_FT_Disc::mettre_a_jour(), Sortie_libre_pression_moyenne_imposee::mettre_a_jour(), Champ_Fonc_P0_base::moyenne(), mp_sum_as_double(), Convection_Diffusion_Concentration_FT_Disc::multiplier_valeurs_faces(), Convection_Diffusion_Concentration_Turbulent_FT_Disc::multiplier_valeurs_faces(), Maillage_FT_Disc::nb_facettes_reelle_totale(), Maillage_FT_Disc::nb_facettes_totale(), Source_Con_Phase_field::non_lin_gmres(), Parcours_interface::parcourir(), IJK_Interfaces::posttraiter_tous_champs(), IJK_Thermal_Subresolution::pre_initialise_thermal_subproblems_matrices(), Transport_Marqueur_FT::preparer_tableaux_avant_transport(), Statistiques::print_communciation_tracking_details(), Champ_Don_Face_lu::readOn(), Corrige_flux_FT_temperature_subresolution::receive_all_fluxes_from_outisde_frontier_on_procs(), Corrige_flux_FT_temperature_subresolution::receive_fluxes_from_frontier_on_procs(), Corrige_flux_FT_temperature_subresolution::receive_temperature_cell_centre_neighbours_from_procs(), Remaillage_FT::regulariser_courbure(), Perte_Charge_Singuliere_VDF_Face::remplir_num_faces(), Hexaedre_32_64< _SIZE_ >::reordonner_elem(), EDO_Pression_th_VDF_Gaz_Parfait::resoudre(), Solv_GCP_NS::resoudre_systeme(), Modele_turbulence_hyd_base::sauvegarder(), Collision_Model_FT_base::set_geometric_parameters(), IJK_One_Dimensional_Subproblems::share_boundary_previous_values(), IJK_One_Dimensional_Subproblems::share_interfacial_heat_flux_correction_on_procs(), Solv_Gen::solve(), Domaine_ALE::solveDynamicMeshProblem(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::stabilise_moyenne_plans_paralleles(), Modele_turbulence_scal_LES_dyn_VDF::stabilise_moyenne_plans_paralleles(), Remaillage_FT::supprimer_facettes_bord(), Remaillage_FT::supprimer_petites_aretes(), Remaillage_FT_IJK::supprimer_petites_aretes(), Transport_Interfaces_FT_Disc::test_suppression_interfaces_sous_domaine(), Remailleur_Collision_FT_Thomas::traite_RuptureCoalescenceInterfaces_Conservatif(), Domaine_ALE::update_ALE_projection(), Transport_Marqueur_FT::update_delta_v(), and Transport_Marqueur_FT::update_tableaux_apres_transport().
mp_sum() [2/4]
float Process::mp_sum (float x) static
References Comm_Group::COLL_SUM, PE_Groups::current_group(), and Comm_Group::mp_collective_op().
mp_sum() [3/4]
static trustIdType Process::mp_sum (int v) inline static
References mp_sum().
Referenced by mp_sum().
mp_sum() [4/4]
trustIdType Process::mp_sum (trustIdType x) static
Calcule la somme de x sur tous les processeurs du groupe courant.
!!! Note that the sum of many int might result in a long !!!
See also
mp_max()
References Comm_Group::COLL_SUM, PE_Groups::current_group(), and Comm_Group::mp_collective_op().
mp_sum_as_double() [1/2]
static double Process::mp_sum_as_double (int v) inline static
References mp_sum().
Referenced by Traitement_particulier_NS_canal::calcul_reynolds_tau(), Op_Diff_PolyMAC_P0_Face::dimensionner_blocs(), Couplage_Parietal_PolyMAC_helper::dimensionner_blocs(), Op_Diff_PolyMAC_P0_Elem::dimensionner_blocs(), Op_Diff_PolyMAC_P0P1NC_Elem::dimensionner_blocs_ext(), Postprocessing_IJK::get_IJK_field_vector(), Domaine_32_64< _SIZE_ >::imprimer(), and Champ_front_synt::mettre_a_jour().
mp_sum_as_double() [2/2]
static double Process::mp_sum_as_double (trustIdType v) inline static
References mp_sum().
mppartial_sum() [1/2]
trustIdType Process::mppartial_sum (trustIdType x) static
Calul de la somme partielle de i sur les processeurs 0 a me()-1 (renvoie 0 sur le processeur 0).
Voir Comm_Group::mppartial_sum()
References Comm_Group::COLL_PARTIAL_SUM, PE_Groups::current_group(), and Comm_Group::mp_collective_op().
Referenced by Domain_Graph::construire_graph_elem_elem(), Solv_Externe::construit_renum(), IJK_Interfaces::dumplata_ft_mesh(), Format_Post_Lml::ecrire_champ_lml(), Format_Post_Lml::ecrire_domaine_lml(), Format_Post_Lata::ecrire_domaine_low_level(), Sauvegarde_Reprise_Maillage_FT::ecrire_xyz(), and Champ_Fonc_MED::readOn().
mppartial_sum() [2/2]
static trustIdType Process::mppartial_sum (int i) inline static
References mppartial_sum().
Referenced by mppartial_sum().
mpsum_multiple()
void Process::mpsum_multiple (double & x1, double & x2) static
References Comm_Group::COLL_SUM, PE_Groups::current_group(), and Comm_Group::mp_collective_op().
mp_and()
bool Process::mp_and (bool b) static
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
References Comm_Group::COLL_MIN, PE_Groups::current_group(), and Comm_Group::mp_collective_op().
mp_or()
bool Process::mp_or (bool b) static
References Comm_Group::COLL_MAX, PE_Groups::current_group(), and Comm_Group::mp_collective_op().
Referenced by Champ_front_lu::initialiser().
check_int_overflow()
int Process::check_int_overflow (trustIdType v) static
References exit().
Referenced by Domaine_VF::build_mc_dual_mesh(), Traitement_particulier_NS_THI_VDF::calcul_skewness_ordre_2(), IJK_Interfaces::calculer_phi_repuls_sommet(), IJK_One_Dimensional_Subproblems::complete_subproblems(), IJK_One_Dimensional_Subproblems::compute_global_indices(), Collision_Model_FT_sphere::compute_lagrangian_contact_forces(), Domain_Graph::construire_graph_elem_elem(), Traitement_particulier_NS_CEG::critere_cea_jaea(), Maillage_FT_Disc::deplacer_sommets(), Maillage_FT_IJK::deplacer_sommets(), Remaillage_FT::diviser_grandes_aretes(), Remaillage_FT_IJK::diviser_grandes_aretes(), IJK_Interfaces::dumplata_ft_mesh(), Sauvegarde_Reprise_Maillage_FT::ecrire_xyz(), Parcours_interface::eloigner_sommets_des_faces(), SurfaceVapeurIJKComputation::get_IJK_ind_from_ind2d(), Mass_Redistribution_Phase_Field::impose_mass_redistribution(), IJK_Interfaces::imprime_bilan_indicatrice(), Cut_cell_surface_efficace::imprimer_informations_surface_efficace_face(), Cut_cell_surface_efficace::imprimer_informations_surface_efficace_interface(), Paroi_2couches_VDF::imprimer_ustar(), Transport_Interfaces_FT_Disc::mettre_a_jour(), Maillage_FT_Disc::nb_facettes_reelle_totale(), Maillage_FT_Disc::nb_facettes_totale(), Parcours_interface::parcourir(), IJK_Thermal_Subresolution::pre_initialise_thermal_subproblems_matrices(), Corrige_flux_FT_temperature_subresolution::receive_all_fluxes_from_outisde_frontier_on_procs(), Corrige_flux_FT_temperature_subresolution::receive_fluxes_from_frontier_on_procs(), Corrige_flux_FT_temperature_subresolution::receive_temperature_cell_centre_neighbours_from_procs(), Remaillage_FT::regulariser_courbure(), Collision_Model_FT_base::set_geometric_parameters(), IJK_One_Dimensional_Subproblems::share_boundary_previous_values(), IJK_One_Dimensional_Subproblems::share_interfacial_heat_flux_correction_on_procs(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::stabilise_moyenne_plans_paralleles(), Modele_turbulence_scal_LES_dyn_VDF::stabilise_moyenne_plans_paralleles(), Remaillage_FT::supprimer_petites_aretes(), and Remaillage_FT_IJK::supprimer_petites_aretes().
je_suis_maitre()
int Process::je_suis_maitre () static
renvoie 1 si on est sur le processeur maitre du groupe courant (c'est a dire me() == 0), 0 sinon.
Voir Comm_Group::rank()
References PE_Groups::current_group(), and Comm_Group::rank().
Referenced by Op_Diff_VEF_Face_Stab::ajouter_antidiffusion(), Save_Restart::allocation(), Assembleur_P_VDF::assembler(), Assembleur_P_EF::assembler_mat(), Assembleur_P_VDF::assembler_mat(), AssembleurPVDF_PF::assembler_QC(), Assembleur_P_EF::assembler_QC(), Assembleur_P_PolyMAC::assembler_QC(), Assembleur_P_VDF::assembler_QC(), AssembleurPVDF_PF::assembler_rho_variable(), Assembleur_P_VDF::assembler_rho_variable(), Operateur_Diff_base::associer_diffusivite_pour_pas_de_temps(), Terme_Source_Acceleration_VDF_Face::associer_domaines(), Terme_Source_Acceleration_VEF_Face::associer_domaines(), Operateur_Conv_base::associer_norme_vitesse(), Remaillage_FT::barycentrer_lisser_apres_remaillage(), Remaillage_FT::barycentrer_lisser_systematique(), Matrice_Bloc_Sym::BlocSymToMatMorseSym(), Traitement_particulier_NS_chmoy_faceperio_VEF::calcul_chmoy_faceperio(), Traitement_particulier_NS_THI_VEF::calcul_Df_spatial(), Traitement_particulier_NS_THI_VEF::calcul_Ec_spatial(), Champ_P1NC::calcul_h_conv(), Traitement_particulier_NS_THI_VEF::calcul_nu_t(), Traitement_particulier_NS_canal::calcul_reynolds_tau(), Traitement_particulier_NS_THI_VEF::calcul_Sk(), Traitement_particulier_NS_THI_VEF::calcul_spectre(), Traitement_particulier_NS_temperature_VEF::calcul_temperature(), IJK_Thermal_base::calculer_ecart_T_ana(), Scatter::calculer_espace_distant_aretes(), Scatter::calculer_espace_distant_elements(), Scatter::calculer_espace_distant_faces(), Scatter::calculer_espace_distant_sommets(), ParoiVDF_TBLE_LRM::calculer_hyd(), ParoiVEF_TBLE::calculer_hyd(), ParoiVDF_TBLE_LRM::calculer_hyd_BiK(), ParoiVEF_TBLE::calculer_hyd_BiK(), Traitement_particulier_NS_Profils_VDF::calculer_integrale_temporelle(), Terme_Source_Canal_RANS_LES_VDF_Face::calculer_integrale_temporelle(), Traitement_particulier_NS_Profils_thermo_VDF::calculer_integrales_temporelles(), Traitement_particulier_Solide_canal_VDF::calculer_integrales_temporelles(), Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_nut(), Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_uv(), Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_vitesse(), Traitement_particulier_NS_Profils_thermo_VDF::calculer_moyennes_spatiales_thermo(), Traitement_particulier_Solide_canal_VDF::calculer_moyennes_spatiales_thermo(), IJK_Thermal_base::calculer_Nusselt(), IJK_Interfaces::calculer_phi_repuls_sommet(), IJK_Thermal_base::calculer_source_temperature_ana(), SurfaceVapeurIJKComputation::calculer_surfaces_et_barys_faces_mouillees_vapeur(), IJK_Thermal_base::calculer_temperature_adim_bulles(), Navier_Stokes_FTD_IJK::calculer_terme_source_acceleration(), IJK_Interfaces::calculer_vecteurs_de_deplacement_rigide(), Desc_Structure_FT::check(), Reordonner_faces_periodiques_32_64< _SIZE_ >::check_faces_periodiques(), Schema_Comm::check_send_recv_pe_list(), Schema_Temps_IJK_base::check_stop_criteria(), EcrFicPartage::close(), Transport_Interfaces_FT_Disc_interne::close_save_file(), Source_Masse_Fluide_Dilatable_base::completer(), Champ_Generique_Reduction_0D::completer(), Format_Post_Med::completer_post_med(), Statistiques_dns_ijk_FT::completer_print(), Navier_Stokes_FTD_IJK::compute_correction_for_momentum_balance(), Statistiques_dns_ijk_FT::compute_desequil_alpha(), Force_sp::compute_dirac_board(), Force_sp::compute_dirac_point(), Force_sp::compute_dirac_point_div_nulle(), Force_sp::compute_dirac_point_uniX_alongX(), Force_sp::compute_dirac_point_uniX_alongY(), Force_sp::compute_dirac_point_uniY(), Force_sp::compute_dirac_point_uniZ(), Force_sp::compute_diracs_for_cos_squarred(), Force_sp::compute_diracs_for_t_times_cos_squarred(), Force_sp::compute_door_cube(), Force_sp::compute_door_rope(), IJK_Interfaces::compute_drapeaux_vapeur_v4(), IJK_Interfaces::compute_external_forces_(), Force_sp::compute_force_kappa(), Force_sp::compute_step2(), Triple_Line_Model_FT_Disc::compute_TCL_fluxes_in_all_boundary_cells(), Domaine_ALE::computeFluidForceOnBeam(), Traitement_particulier_NS_THI_VEF::conservation_Ec(), Solv_Externe::construit_matrice_morse_intermediaire(), Transport_K_Eps_base::controler_K_Eps(), Transport_K_Omega_base::controler_K_Omega(), Transport_K_ou_Eps_base::controler_variable(), Scatter::corriger_espace_distant_elements_perio(), IJK_Thermals::create_folders(), Solv_Petsc::create_solver(), Traitement_particulier_NS_CEG::critere_cea_jaea(), Transport_Interfaces_FT_Disc::deplacer_maillage_ft_v_fluide(), Maillage_FT_Disc::deplacer_sommets(), Traitement_particulier_NS_THI_VEF::determine_tab_fft_VEF_1D(), Traitement_particulier_NS_THI_VEF::determine_tab_fft_VEF_3D(), Sous_domaine_VF::discretiser(), mon_main::dowork(), Statistiques::dump(), IJK_Interfaces::dumplata_ft_mesh(), IJK_Interfaces::dupliquer_bulle_perio(), Cond_lim_utilisateur_base::ecrire(), Postraiter_domaine::ecrire(), Format_Post_Lml::ecrire_champ_lml(), Format_Post_Med::ecrire_champ_med(), Format_Post_XYZ::ecrire_champ_xyz(), Format_Post_Lml::ecrire_domaine_lml(), Format_Post_Med::ecrire_domaine_med(), DomaineCutter_32_64< _SIZE_ >::ecrire_domaines(), Format_Post_Lml::ecrire_entete_lml(), Format_Post_Med::ecrire_entete_med(), Convection_Diffusion_Temperature::ecrire_fichier_pena_th(), Switch_FT_double::ecrire_fichier_reprise(), DNS_QC_double::ecrire_fichier_sauv(), Postprocessing_IJK::ecrire_statistiques_bulles(), IJK_Thermal_base::ecrire_statistiques_bulles(), Postprocessing_IJK::ecrire_statistiques_cisaillement(), Postprocessing_IJK::ecrire_statistiques_rmf(), Face_Rayonnante::ecrire_temperature_bord(), Format_Post_Lml::ecrire_temps_lml(), Format_Post_Med::ecrire_temps_med(), Sauvegarde_Reprise_Maillage_FT::ecrire_xyz(), Traitement_particulier_NS_Profils_thermo_VDF::ecriture_fichier_moy_spat_thermo(), Traitement_particulier_Solide_canal_VDF::ecriture_fichier_moy_spat_thermo(), Traitement_particulier_NS_Profils_thermo_VDF::ecriture_fichier_moy_temp_thermo(), Traitement_particulier_Solide_canal_VDF::ecriture_fichier_moy_temp_thermo(), Traitement_particulier_NS_Profils_VDF::ecriture_fichiers_moy_spat(), Traitement_particulier_NS_Profils_VDF::ecriture_fichiers_moy_spat_1col(), Traitement_particulier_NS_Profils_VDF::ecriture_fichiers_moy_temp(), Traitement_particulier_NS_Profils_VDF::ecriture_fichiers_moy_temp_1col(), EcritureLectureSpecial::ecriture_special(), Parcours_interface::eloigner_sommets_des_faces(), Lec_Diffuse_base::eof(), Probleme_FT_Disc_gen::equation_hydraulique(), Probleme_FT_Disc_gen::equation_interfaces(), exit(), Lec_Diffuse_base::fail(), Force_sp::field_advection(), Schema_Temps_IJK_base::find_timestep(), Save_Restart::finir(), Schema_Temps_base::finir(), Format_Post_Lml::finir_lml(), Format_Post_Med::finir_med(), Format_Post_Lata::finir_sans_reprise(), force_single_file(), Ensemble_Lagrange_base::generer_marqueurs_sz(), Lec_Diffuse_base::get(), Postprocessing_IJK::get_IJK_field(), Postprocessing_IJK::get_IJK_field_vector(), LecFicDiffuse::get_istream(), Lec_Diffuse_base::good(), Debog_Pb::goto_msg(), Source_PDF_EF::impr(), Op_Grad_VEF_P1B_Face::impr(), Op_EF_base::impr(), Op_VEF_Face::impr(), Source_base::impr(), Transport_Interfaces_FT_Disc::impr(), Op_Div_EF::impr(), Op_Grad_EF::impr(), Terme_Source_EF_base::impr(), Op_Conv_PolyMAC_base::impr(), Op_Diff_PolyMAC_Gen_base::impr(), Op_Div_PolyMAC::impr(), Op_Grad_VDF_Face::impr(), Op_Div_VEFP1B_Elem::impr(), Transport_Interfaces_FT_Disc::impr_effort_fluide_interface(), Traitement_particulier_NS_THI_VEF::impression_moyenne(), Equation_base::imprime_residu(), Loi_horaire::imprimer(), Echange_contact_Correlation_VDF::imprimer(), Echange_contact_Correlation_VEF::imprimer(), Schema_Temps_base::imprimer(), Loi_Paroi_Nu_Impose_VDF::imprimer_nusselt(), Loi_Paroi_Nu_Impose_VEF::imprimer_nusselt(), Paroi_scal_hyd_base_EF::imprimer_nusselt(), Paroi_scal_hyd_base_VDF::imprimer_nusselt(), Paroi_scal_hyd_base_VEF::imprimer_nusselt(), Turbulence_paroi_scal_base::imprimer_nusselt_mean_only(), Turbulence_paroi_scal_base::imprimer_premiere_ligne_nusselt(), Turbulence_paroi_base::imprimer_premiere_ligne_ustar(), Paroi_std_hyd_EF::imprimer_ustar(), Paroi_std_hyd_VDF::imprimer_ustar(), Paroi_std_hyd_VEF::imprimer_ustar(), Paroi_2couches_VDF::imprimer_ustar(), Turbulence_paroi_base::imprimer_ustar_mean_only(), Traitement_particulier_NS_chmoy_faceperio_VEF::init_calcul_stats(), ParoiVEF_TBLE::init_lois_paroi(), ParoiVEF_TBLE_scal::init_lois_paroi(), mon_main::init_parallel(), Sonde::initialiser(), Sonde_Int::initialiser(), Statistiques_dns_ijk_monophasique::initialize(), Statistiques_dns_ijk::initialize(), Statistiques_dns_ijk_FT::initialize(), Domaine_IJK::initialize_splitting(), DebogFT::interpreter(), Scatter::interpreter(), DebogIJK::interpreter(), Test_solveur::interpreter(), Mkdir::interpreter(), System::interpreter(), Debog_Pb_Wrapper::interpreter(), MaillerParallel::interpreter(), EcritureLectureSpecial::is_ecriture_special(), Fichier_Lata::is_master(), Traitement_particulier_NS_THI_VEF::isotropie(), Sch_CN_iteratif::iterateTimeStep(), LecFicDiffuse::LecFicDiffuse(), LecFicDiffuse_JDD::LecFicDiffuse_JDD(), Modele_turbulence_hyd_base::limiter_viscosite_turbulente(), Traitement_particulier_NS_THI_VEF::lire(), Transport_Interfaces_FT_Disc::lire_cond_init(), Terme_Source_Acceleration::lire_data(), Modele_turbulence_hyd_Longueur_Melange_VEF::lire_distance_paroi(), Modele_Lam_Bremhorst_VEF::lire_distance_paroi(), Scatter::lire_domaine(), SourceFiltree_FT_disc_base::lire_donnees(), Postraitement_ft_lata::lire_entete_bloc_interface(), Postprocessing_IJK::lire_entete_bloc_interface(), Maillage_FT_IJK::lire_maillage_ft_dans_lata(), Convection_Diffusion_Temperature_FT_Disc::lire_motcle_non_standard(), Navier_Stokes_FT_Disc::lire_motcle_non_standard(), Transport_Interfaces_FT_Disc::lire_motcle_non_standard(), Navier_Stokes_std::lire_motcle_non_standard(), Operateur_IJK_faces_conv::lire_motcle_non_standard(), Operateur_IJK_faces_diff::lire_motcle_non_standard(), Eq_couch_lim::mailler_fin(), Schema_Temps_base::mettre_a_jour(), Source_Masse_Fluide_Dilatable_base::mettre_a_jour(), Convection_Diffusion_Concentration_FT_Disc::mettre_a_jour(), Convection_Diffusion_Concentration_Turbulent_FT_Disc::mettre_a_jour(), Transport_Interfaces_FT_Disc::mettre_a_jour(), Echange_contact_VDF_FT_Disc_solid::mettre_a_jour(), Echange_contact_Correlation_VDF::mettre_a_jour(), Format_Post_Lata::modify_file_basename(), Traitement_particulier_NS_THI::msg_erreur_maillage(), Traitement_particulier_NS_THI_new::msg_erreur_maillage(), Random_process::next_step2(), Random_process::next_step3(), LecFicDistribue_sansnum::ouvrir(), LecFicDiffuse::ouvrir(), LecFicDiffuse_JDD::ouvrir(), LecFicDistribue::ouvrir(), Sortie_Fichier_base::ouvrir(), EcrFicCollecte::ouvrir(), EcrFicPartage::ouvrir(), EcrFicPartageMPIIO::ouvrir(), Sonde::ouvrir_fichier(), Sonde_Int::ouvrir_fichier(), Operateur_base::ouvrir_fichier(), Turbulence_paroi_base::ouvrir_fichier_partage(), Turbulence_paroi_scal_base::ouvrir_fichier_partage(), IJK_One_Dimensional_Subproblems::post_process_overall_bubbles_quantities(), IJK_Thermal_Subresolution::post_processed_field_thermal_wake_slice_ij(), IJK_Thermal_Subresolution::post_processed_fields_on_downstream_line(), Traitement_particulier_NS_canal::post_traitement_particulier(), Traitement_particulier_NS_EC::post_traitement_particulier(), Sonde::postraiter(), Sonde_Int::postraiter(), Fourier_trans::postraiter(), Statistiques_dns_ijk::postraiter(), IJK_Interfaces::postraiter_colors(), Statistiques_dns_ijk::postraiter_k(), Statistiques_dns_ijk_FT::postraiter_thermique(), DNS_QC_double::posttraiter_champs_instantanes(), Postprocessing_IJK::posttraiter_statistiques_plans(), Solv_Optimal::prepare_resol(), Save_Restart::preparer_calcul(), Navier_Stokes_FT_Disc::preparer_calcul(), Modele_Rayonnement_Milieu_Transparent::preparer_calcul(), Traitement_particulier_NS_THI_VEF::preparer_calcul_particulier(), Traitement_particulier_NS_EC::preparer_calcul_particulier(), IJK_Interfaces::preparer_duplicata_bulles(), IJK_Interfaces::preparer_duplicata_bulles_masque_6bit(), Format_Post_Med::preparer_post_med(), Statistiques_dns_ijk::printOn(), Beam_model::printOutputBeam1D(), Beam_model::printOutputBeam3D(), Beam_model::printOutputFluidForceOnBeam(), Navier_Stokes_FT_Disc::projeter(), Convection_Diffusion_Concentration_FT_Disc::ramasse_miette_simple(), Convection_Diffusion_Concentration_Turbulent_FT_Disc::ramasse_miette_simple(), Domaine_ALE::read_beam(), Debog_Pb::read_geometry_data(), Maillage_FT_Disc::readOn(), Convection_Diffusion_Concentration_FT_Disc::readOn(), Convection_Diffusion_Concentration_Turbulent_FT_Disc::readOn(), Topologie_Maillage_FT::readOn(), Coarsen_Operator_K::readOn(), Debog_Pb::readOn(), Joint_32_64< _SIZE_ >::readOn(), Domaine_IJK::readOn(), IJK_Grid_Geometry::readOn(), Sonde::readOn(), Diametre_bulles_musig::readOn(), Remaillage_FT::regulariser_courbure(), Remaillage_FT::remaillage_local_interface(), Remaillage_FT_IJK::remaillage_local_interface(), Topologie_Maillage_FT::remailler_interface(), DP_Impose_PolyMAC_Face::remplir_num_faces(), Perte_Charge_Singuliere_PolyMAC_Face::remplir_num_faces(), DP_Impose_VEF_Face::remplir_num_faces(), Perte_Charge_Singuliere_VEF_Face::remplir_num_faces(), Traitement_particulier_NS_canal::remplir_reordonne_Y_tot(), Traitement_particulier_NS_THI_VEF::renorm_Ec(), Hexaedre_32_64< _SIZE_ >::reordonner_elem(), Schema_Euler_Implicite::reprendre(), Schema_Implicite_Multi_TimeStep_base::reprendre(), Traitement_particulier_NS_canal::reprendre_stat(), Solv_Petsc::resoudre_systeme(), Solv_GCP_NS::resoudre_systeme(), Navier_Stokes_FTD_IJK::rk3_sub_step(), DNS_QC_double::run(), Probleme_U::runUntil(), Remaillage_FT::sauvegarder(), Transport_Interfaces_FT_Disc::sauvegarder(), Collision_Model_FT_base::sauvegarder(), Transport_Interfaces_FT_Disc_interne::sauvegarder(), Couplage_Tubes_IBC::sauvegarder_pression(), Probleme_FTD_IJK_base::sauvegarder_probleme(), Couplage_Tubes_IBC::sauvegarder_probleme(), Save_Restart::sauver(), Traitement_particulier_NS_canal::sauver_stat(), Save_Restart::sauver_xyz(), DNS_QC_double::save_stats(), Beam_model::saveBeamForRestart(), Fluide_Quasi_Compressible::secmembre_divU_Z(), Lec_Diffuse_base::set_bin(), Catch_SIGINIT::signal_callback_handler(), Solv_Gen::solve(), Traitement_particulier_NS_THI_VDF::sorties_globales(), Traitement_particulier_NS_THI_VEF::sorties_globales(), Terme_Source_Canal_perio::source(), Schema_Temps_base::stop_lu(), IJK_Interfaces::store_bubbles_barycentres(), Traitement_particulier_NS_THI_VEF::suppression_vitesse_moyenne(), IJK_Interfaces::supprimer_certaines_bulles_reelles(), EcrFicPartage::syncfile(), Schema_Temps_base::terminate(), Probleme_FTD_IJK_base::terminate(), Op_Diff_VEFP1NCP1B_Face::test(), IJK_One_Dimensional_Subproblems::thermal_subresolution_outputs_parallel(), IJK_Interfaces::transferer_bulle_perio(), Champ_front_recyclage::UPb(), Domaine_ALE::update_ALE_projection(), Navier_Stokes_std::uzawa(), DebogIJK::verifier(), DebogFT::verifier_(), Ecrire_YAML::write_champ_fonc_restart_file(), Navier_Stokes_FTD_IJK::write_check_etapes_et_termes(), Ecrire_YAML::write_checkpoint_file(), Schema_Temps_base::write_dt_ev(), Fluide_Dilatable_base::write_header_edo(), Fluide_Weakly_Compressible::write_header_edo(), Fluide_Dilatable_base::write_mean_edo(), Fluide_Weakly_Compressible::write_mean_edo(), Schema_Temps_base::write_progress(), Navier_Stokes_FTD_IJK::write_qdm_corrections_information(), Ecrire_YAML::write_restart_file(), LireMED_32_64< _SIZE_ >::write_sub_dom_datasets(), and Switch_double::write_velocity().
Kokkos_exit()
KOKKOS_INLINE_FUNCTION void Process::Kokkos_exit (const char * str) static
Routine de sortie de TRUST dans une region Kokkos.
References exit().
Referenced by Matrice_Morse_View::add(), Op_Div_VEFP1B_Elem::ajouter(), Evaluateur_Source_VEF_Face::calculer_terme_source_non_standard_view(), Eval_Darcy_VEF_Face_View::calculer_terme_source_non_standard_view(), Eval_Dirac_VEF_Face_View::calculer_terme_source_non_standard_view(), Eval_Forchheimer_VEF_Face_View::calculer_terme_source_non_standard_view(), Eval_Puiss_Th_QC_VEF_Face_View::calculer_terme_source_non_standard_view(), Eval_Puiss_Th_VEF_Face_View::calculer_terme_source_non_standard_view(), Evaluateur_Source_VEF_Face::calculer_terme_source_standard_view(), Eval_Darcy_VEF_Face_View::calculer_terme_source_standard_view(), Eval_Dirac_VEF_Face_View::calculer_terme_source_standard_view(), Eval_Forchheimer_VEF_Face_View::calculer_terme_source_standard_view(), Eval_Puiss_Th_QC_VEF_Face_View::calculer_terme_source_standard_view(), Eval_Puiss_Th_VEF_Face_View::calculer_terme_source_standard_view(), Parser::evalOp(), Champ_Generique_Transformation::get_champ(), and Matrice_Morse_View::operator()().
node_master()
int Process::node_master () static
renvoie 1 si on est sur le processeur maitre du noeud numa, 0 sinon.
References PE_Groups::get_node_group(), and Comm_Group::rank().
Referenced by TRUST_2_PDI::prepareRestart(), Schema_Temps_base::sauvegarder(), and Save_Restart::sauver().
exit() [2/2]
void Process::exit (const Nom & message, int exit_code = -1) static
References abort(), Comm_Group::abort(), exception_sur_exit, exit(), PE_Groups::finalize(), PE_Groups::groupe_TRUST(), Synonyme_info::hierarchie(), Type_info::hierarchie(), is_parallel(), je_suis_maitre(), Journal(), me(), Objet_U::nom_du_cas(), and nproc().
is_sequential()
bool Process::is_sequential () static
References nproc().
Referenced by MD_Vector_composite::add_part(), Op_Diff_RotRot::calculer_vorticite(), Scatter::construire_espace_virtuel_traduction(), Domain_Graph::construire_graph_elem_elem(), Scatter::construire_md_vector(), Solv_Petsc::create_solver(), Op_Div_VEFP1B_Elem::degres_liberte(), Fichier_Lata::Fichier_Lata(), EcritureLectureSpecial::get_Output(), Scatter::interpreter(), and Domaine_Cl_dis_base::readOn().
barrier()
void Process::barrier () static
Synchronise tous les processeurs du groupe courant (attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
References Comm_Group::barrier(), and PE_Groups::current_group().
Referenced by Save_Restart::allocation(), Loi_Fermeture_base::associer_pb_base(), Paroi_std_hyd_VEF::calculer_hyd(), Paroi_std_hyd_VEF::calculer_hyd_BiK(), Desc_Structure_FT::check(), Reordonner_faces_periodiques_32_64< _SIZE_ >::check_faces_periodiques(), Schema_Comm::check_send_recv_pe_list(), EcrFicPartage::close(), FT_Field::completer_compo_connexe_partielle(), Corriger_frontiere_periodique_32_64< _SIZE_ >::corriger_coordonnees_sommets_perio(), Domaine_32_64< int >::cree_instance(), mon_main::dowork(), Postraiter_domaine::ecrire(), Schema_Comm_Vecteurs::end_init(), Matrice_Morse::imprimer_formatte(), Matrice_Morse::imprimer_image(), Domaine_PolyMAC::init_m1_3d(), Scatter::interpreter(), Moyenne_volumique::interpreter(), Execute_parallel::interpreter(), System::interpreter(), MaillerParallel::interpreter(), Lata_2_Other::interpreter(), Ecrire_Fichier::interpreter_(), Transport_Interfaces_FT_Disc::lire_cond_init(), Scatter::lire_domaine(), ScatterMED::lire_domaine(), Transport_Interfaces_FT_Disc::lire_maillage_ft_cao(), Convection_Diffusion_Concentration_FT_Disc::lire_motcle_non_standard(), Convection_Diffusion_Concentration_Turbulent_FT_Disc::lire_motcle_non_standard(), Convection_Diffusion_Temperature_FT_Disc::lire_motcle_non_standard(), Navier_Stokes_FT_Disc::lire_motcle_non_standard(), Transport_Interfaces_FT_Disc::lire_motcle_non_standard(), Sauvegarde_Reprise_Maillage_FT::lire_xyz(), Convection_Diffusion_Concentration_FT_Disc::mettre_a_jour(), Convection_Diffusion_Concentration_Turbulent_FT_Disc::mettre_a_jour(), Transport_Interfaces_FT_Disc::mettre_a_jour(), Convection_Diffusion_Concentration_FT_Disc::mettre_a_jour_chimie(), Convection_Diffusion_Concentration_Turbulent_FT_Disc::mettre_a_jour_chimie(), Format_Post_Lata::modify_file_basename(), EcrFicPartage::ouvrir(), Objet_a_lire::read(), Remailleur_Collision_FT_Thomas::readOn(), Moyenne_volumique::readOn(), Champ_Don_Face_lu::readOn(), Moyenne_volumique::traiter_champs(), Ecrire_YAML::write_champ_fonc_restart_file(), Ecrire_YAML::write_checkpoint_file(), and Ecrire_YAML::write_restart_file().
abort()
void Process::abort () static
Routine de sortie de Trio-U sur une erreur abort()
References abort(), and exit().
Referenced by abort(), Champ_Fonc_Face_PolyMAC::affecter_(), Source_PDF_base::ajouter_(), Op_Grad_PolyMAC_P0_Face::ajouter_blocs(), Diffusion_croisee_echelle_temp_taux_diss_turb_PolyMAC_P0::ajouter_blocs(), Source_Dissipation_echelle_temp_taux_diss_turb::ajouter_blocs(), Source_Dissipation_energie_cin_turb::ajouter_blocs(), Op_Evanescence_Homogene_Elem_base::ajouter_blocs(), Op_Evanescence_Homogene_Face_base::ajouter_blocs(), Op_Evanescence_Homogene_PolyMAC_P0_Face::ajouter_blocs_aux(), Op_Diff_PolyMAC_P0P1NC_Elem::ajouter_blocs_ext(), Matrice_Dense::ajouter_multTab_(), Transport_Interfaces_FT_Disc::assembler(), Assembleur_P_PolyMAC_P0P1NC::assembler_continuite(), Assembleur_P_PolyMAC::assembler_QC(), Assembleur_P_PolyMAC::assembler_rho_variable(), Source_PDF_base::associer_domaines(), Source_PDF_EF::associer_pb(), Source_PDF_base::associer_pb(), Terme_Boussinesq_base::associer_pb(), Champ_Face_PolyMAC::calcul_S_barre_sans_contrib_paroi(), Point_EF::calcul_vc(), Point_EF::calcul_xg(), Op_Diff_PolyMAC_P0P1NC_Elem::calculer_dt_stab(), Source_PDF_base::calculer_variable_imposee_elem_fluid(), Source_PDF_base::calculer_variable_imposee_hybrid(), Source_PDF_base::calculer_variable_imposee_mean_grad(), Source_PDF_base::calculer_vitesse_imposee_power_law_tbl(), Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl(), Source_PDF_base::calculer_vitesse_imposee_power_law_tbl_u_star(), Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl_u_star(), Pb_Couple_Rayonnement::completer(), Transport_K_Eps_Bas_Reynolds::completer(), Transport_K_Eps_Realisable::completer(), Champ_Generique_Transformation::completer(), Source_PDF_base::compute_coeff_elem(), Source_PDF_base::compute_coeff_matrice(), Source_PDF_base::compute_indicateur_nodal_champ_aire(), Source_PDF_base::compute_variable_imposee_projete(), Source_PDF_base::contribuer_a_avec(), Source_PDF_base::correct_incr_pressure(), Source_PDF_base::correct_pressure(), Source_PDF_base::correct_variable(), Source_PDF_EF::correct_variable(), PolyMAC_P0_discretisation::creer_champ_vorticite(), Loi_Etat_base::De_DP(), Loi_Etat_GR_base::De_DP(), Loi_Etat_base::De_DT(), Loi_Etat_GR_base::De_DT(), Source_PDF_base::diag_coeff_elem(), Source_Dissipation_energie_cin_turb::dimensionner_blocs(), Source_Production_echelle_temp_taux_diss_turb::dimensionner_blocs(), Domaine_Poly_base::dist_face_elem0_period(), Domaine_Poly_base::dist_face_elem1_period(), Loi_Etat_base::Drho_DP(), Loi_Etat_base::Drho_DT(), Viscosite_turbulente_l_melange::eps(), exit(), Operateur_IJK_elem_conv::get_convection_op_type(), Operateur_IJK_faces_conv::get_convection_op_type(), Operateur_IJK_elem_diff::get_diffusion_op_type(), Operateur_IJK_faces_diff::get_diffusion_op_type(), Matrice_Bloc::get_stencil_and_coeff_ptrs(), Matrice_Morse::get_stencil_and_coeff_ptrs(), Matrice_Diagonale::get_stencil_and_coefficients(), Matrice_Morse::get_stencil_and_coefficients(), PolyMAC_P0P1NC_discretisation::grad_u(), Source_PDF_base::impr(), Domaine_Cl_EF::initialiser(), Matrice_Dense::inverse(), Loi_Etat_rhoT_GP_QC::inverser_Pth(), Loi_Etat_Binaire_GP_base::inverser_Pth(), Viscosite_turbulente_l_melange::k_over_eps(), Prepro_IBM_base::lire_motcle_non_standard(), Rotationnel_Champ_P1_EF::me_calculer(), QDM_Multiphase::mettre_a_jour(), Champ_Fonc_Tabule_Elem_PolyMAC::mettre_a_jour(), Schema_Temps_base::mettre_a_jour_dt(), Op_Diff_Turbulent_PolyMAC_P0_Face::modifier_mu(), Viscosite_turbulente_base::modifier_mu(), Traitement_particulier_NS_THI::msg_erreur_maillage(), Traitement_particulier_NS_THI_new::msg_erreur_maillage(), Source_PDF_base::multiply_coeff_volume(), Point_EF::normale(), ptrParam::operator=(), Operateur_base::ouvrir_fichier(), ptrParam::ptrParam(), Matrice_Dense::read_from_file(), Modele_Rayonnement_Milieu_Transparent::readOn(), Sutherland::readOn(), Partitionneur_Union::readOn(), Loi_Etat_Mono_GP_base::readOn(), Loi_Etat_rhoT_GR_QC::readOn(), Op_Diff_PolyMAC_base::remplir_nu_ef(), EDO_Pression_th_VDF_Gaz_Parfait::resoudre(), Fluide_Quasi_Compressible::Resoudre_EDO_PT(), Viscosite_turbulente_l_melange::reynolds_stress(), Source_PDF_base::rotate_imposed_velocity(), Operateur_IJK_elem_diff::set_conductivity_coefficient(), Matrice_Dense::solve(), Echange_externe_impose_H::T_ext(), IJK_Thermal_base::typer_lire_thermal_equation(), Op_Diff_PolyMAC_P0_base::update_nu(), Op_Diff_PolyMAC_P0P1NC_base::update_nu(), Neumann_sortie_libre_Temp_H::val_ext(), Entree_fluide_temperature_imposee_H::val_imp(), Temperature_imposee_paroi_H::val_imp(), Convection_Diffusion_Temperature_IBM::verify_scheme(), Navier_Stokes_IBM::verify_scheme(), and Conduction_IBM::verify_scheme().
Journal()
Sortie & Process::Journal (int message_level = 0) static
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon on l'envoie sur une Sortie_Nulle. Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
Referenced by DeviceMemory::add(), DeviceMemory::addrOnDevice(), Interprete_bloc::ajouter(), Comm_Group_MPI::barrier(), Remaillage_FT::barycentrer_lisser_apres_remaillage(), Remaillage_FT::barycentrer_lisser_systematique(), Statistiques::begin_count_(), Matrice_Bloc_Sym::BlocSymToMatMorseSym(), Maillage_FT_Disc::calcul_courbure_sommets(), Transport_Interfaces_FT_Disc::calcul_effort_fluide_interface(), Maillage_FT_Disc::calcul_indicatrice(), Maillage_FT_Disc::calcul_normale_3D(), Maillage_FT_Disc::calcul_surface_normale(), Remaillage_FT::calculer_correction_deplacement(), IJK_Thermal_base::calculer_ecart_T_ana(), Scatter::calculer_espace_distant(), Navier_Stokes_FT_Disc::calculer_gradient_indicatrice(), IJK_Thermal_base::calculer_source_temperature_ana(), Maillage_FT_Disc::calculer_voisinage_facettes(), Remaillage_FT::calculer_volume_sommets_supprimes(), Maillage_FT_Disc::check_mesh(), Maillage_FT_IJK::check_mesh(), Schema_Comm::check_send_recv_pe_list(), Maillage_FT_Disc::check_sommets(), Maillage_FT_IJK::check_sommets(), Scatter::Chercher_Correspondance(), Domaine_Cl_VDF::completer(), Champ_Generique_Reduction_0D::completer(), Champ_Generique_Transformation::completer(), Postprocessing_IJK::compute_extended_pressures(), Octree_32_64< _SIZE_ >::construire(), Op_Div_VEFP1B_Elem::degres_liberte(), DeviceMemory::del(), IJK_Interfaces::deplacer_bulle_perio(), Transport_Interfaces_FT_Disc::deplacer_maillage_ft_v_fluide(), Remaillage_FT::diviser_grandes_aretes(), Remaillage_FT_IJK::diviser_grandes_aretes(), mon_main::dowork(), Maillage_FT_Disc::ecrire_plot(), Post_Processing_Hydrodynamic_Forces::elem_faces_for_interp(), Parcours_interface::eloigner_sommets_des_faces(), Statistiques::end_communication_tracking(), Schema_Comm_Vecteurs::end_init(), Entree_complete::Entree_complete(), exit(), Post_Processing_Hydrodynamic_Forces::face_voisins_for_interp(), Maillage_FT_Disc::facettes_voisines(), Sonde::fix_probe_position_grav(), Postprocessing_IJK::get_IJK_field(), Postprocessing_IJK::get_IJK_field_vector(), imprimer_ram_totale(), Sonde::initialiser(), Domaine_IJK::initialize_mapping(), Domaine_IJK::initialize_with_mapping(), Execute_parallel::interpreter(), MaillerParallel::interpreter(), VerifierCoin::interpreter_(), Interprete_bloc::interpreter_bloc(), Maillage_FT_IJK::lire_maillage_ft_dans_lata(), Champ_Gen_de_Champs_Gen::lire_motcle_non_standard(), Remaillage_FT::marquer_aretes(), Domaine_VF::marquer_faces_double_contrib(), Transport_Interfaces_FT_Disc::mettre_a_jour(), Domaine_EF::modifier_pour_Cl(), Domaine_Poly_base::modifier_pour_Cl(), Domaine_PolyMAC::modifier_pour_Cl(), Domaine_VEF::modifier_pour_Cl(), Remaillage_FT::nettoyer_maillage(), LecFicDistribue_sansnum::ouvrir(), LecFicDiffuse_JDD::ouvrir(), LecFicDistribue::ouvrir(), Parcours_interface::parcourir(), Parcours_interface::parcours_facette(), Transport_Interfaces_FT_Disc::preparer_calcul(), Champ_Generique_Transformation::preparer_macro(), DeviceMemory::printMemoryMap(), Convection_Diffusion_Concentration_FT_Disc::ramasse_miette_simple(), Convection_Diffusion_Concentration_Turbulent_FT_Disc::ramasse_miette_simple(), Champ_Generique_base::readOn(), Domaine_Cl_dis_base::readOn(), Champ_Don_Face_lu::readOn(), Remaillage_FT::redistribuer_sommets(), Remaillage_FT::regulariser_courbure(), Remaillage_FT::remaillage_local_interface(), Remaillage_FT_IJK::remaillage_local_interface(), FT_Field::remailler_FT_Field(), Transport_Interfaces_FT_Disc::remailler_interface(), Topologie_Maillage_FT::remailler_interface(), Maillage_FT_Disc::remplir_structure(), Solv_rocALUTION::resoudre_systeme(), Remaillage_FT::supprimer_doublons_facettes(), Remaillage_FT::supprimer_facettes_bord(), Remaillage_FT::supprimer_facettes_nulles(), Reorienter_tetraedres_32_64< _SIZE_ >::test_orientation_tetra(), Reorienter_triangles_32_64< _SIZE_ >::test_orientation_triangle(), Remaillage_FT::traite_adherence(), Remaillage_FT::traite_decollement(), Remailleur_Collision_FT_Juric::traite_RuptureCoalescenceInterfaces(), Remailleur_Collision_FT_Thomas::traite_RuptureCoalescenceInterfaces_Conservatif(), IJK_Interfaces::transporter_maillage_deformation(), Parcours_interface::uzawa2(), DebogIJK::verifier(), DebogFT::verifier_(), and mon_main::~mon_main().
ram_processeur()
double Process::ram_processeur () static
Referenced by imprimer_ram_totale().
imprimer_ram_totale()
void Process::imprimer_ram_totale (int all_process = 0) static
References DeviceMemory::allocatedBytesOnDevice(), DeviceMemory::deviceMemGetInfo(), Journal(), me(), mp_max(), mp_sum(), and ram_processeur().
Referenced by Schema_Temps_base::corriger_dt_calcule(), Schema_Euler_Implicite_Stationnaire::corriger_dt_calcule(), mon_main::dowork(), and Interprete_geometrique_base_32_64< _SIZE_ >::interpreter().
force_single_file()
bool Process::force_single_file (const int ranks, const Nom & filename) static
References je_suis_maitre(), and multiple_files.
Referenced by mon_main::dowork(), Decouper_32_64< _SIZE_ >::ecrire(), Raffiner_isotrope_parallele::interpreter(), and Save_Restart::lire_sauvegarde_reprise().
Member Data Documentation
exception_sur_exit
int Process::exception_sur_exit =0 static
Referenced by exit(), ICoCo::ProblemTrio::initialize(), Execute_parallel::interpreter(), and Sortie_Fichier_base::ouvrir().
multiple_files
int Process::multiple_files =5120 static
Referenced by force_single_file(), and MultipleFiles::interpreter().