TrioCFD: Frontiere_32_64< _SIZE_ > Class Template Reference
Frontiere_32_64< _SIZE_ > Class Template Reference
#include <Frontiere.h>
Public Member Functions
void add (const Frontiere_32_64 &)
void ajouter_faces (const IntTab_t &)
void associer_domaine (const Domaine_t &)
Domaine_t & domaine ()
const Domaine_t & domaine () const
const Type_info * get_info () const override
const Nom & le_nom () const override
IntTab_t & les_sommets_des_faces ()
const IntTab_t & les_sommets_des_faces () const
void nommer (const Nom &) override
void renum (const IntVect_t &)
void typer_faces (const Motcle &)
void typer_faces (const Type_Face &)
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
template<typename _SIZE_>
class Frontiere_32_64< _SIZE_ >
Une Frontiere decrit une partie de la frontiere d'un Domaine, elle possede un Nom, elle porte des Faces et a un Domaine associe. Une Frontiere peut etre specialisee en un Bord, un Joint un Raccord ou une Face Interne.
See also
Domaine Bord Joint Raccord Faces_Interne
Member Typedef Documentation
int_t
template<typename _SIZE_ > using Frontiere_32_64< _SIZE_ >::int_t = _SIZE_
ArrOfInt_t
template<typename _SIZE_ > using Frontiere_32_64< _SIZE_ >::ArrOfInt_t = ArrOfInt_T<_SIZE_>
IntVect_t
template<typename _SIZE_ > using Frontiere_32_64< _SIZE_ >::IntVect_t = IntVect_T<_SIZE_>
IntTab_t
template<typename _SIZE_ > using Frontiere_32_64< _SIZE_ >::IntTab_t = IntTab_T<_SIZE_>
DoubleVect_t
template<typename _SIZE_ > using Frontiere_32_64< _SIZE_ >::DoubleVect_t = DoubleVect_T<_SIZE_>
DoubleTab_t
template<typename _SIZE_ > using Frontiere_32_64< _SIZE_ >::DoubleTab_t = DoubleTab_T<_SIZE_>
Domaine_t
template<typename _SIZE_ > using Frontiere_32_64< _SIZE_ >::Domaine_t = Domaine_32_64<_SIZE_>
Faces_t
template<typename _SIZE_ > using Frontiere_32_64< _SIZE_ >::Faces_t = Faces_32_64<_SIZE_>
Constructor & Destructor Documentation
Frontiere_32_64()
template<typename _T_ > Frontiere_32_64< _T_ >::Frontiere_32_64
~Frontiere_32_64()
template<typename _T_ > Frontiere_32_64< _T_ >::~Frontiere_32_64 override
Member Function Documentation
info()
template<typename _T_ > const Type_info * Frontiere_32_64< _T_ >::info static
get_info()
template<typename _T_ > const Type_info * Frontiere_32_64< _T_ >::get_info override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
Reimplemented in Groupe_Faces_32_64< _SIZE_ >, Joint_32_64< _SIZE_ >, Raccord_base_32_64< _SIZE_ >, Raccord_local_32_64< _SIZE_ >, Raccord_distant_32_64< _SIZE_ >, Raccord_local_homogene_32_64< _SIZE_ >, and Raccord_distant_homogene_32_64< _SIZE_ >.
self_cast() [1/2]
template<typename _T_ > Frontiere_32_64< _T_ > & Frontiere_32_64< _T_ >::self_cast (Objet_U & r) static
self_cast() [2/2]
template<typename _T_ > const Frontiere_32_64< _T_ > & Frontiere_32_64< _T_ >::self_cast (const Objet_U & r) static
printOn()
template<typename _SIZE_ > Sortie & Frontiere_32_64< _SIZE_ >::printOn (Sortie & os) const override protected virtual
Ecrit la frontiere sur un flot de sortie.
On ecrit: le nom de la frontiere les faces
Parameters
(Sortie& os) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Objet_U.
Reimplemented in Groupe_Faces_32_64< _SIZE_ >, Joint_32_64< _SIZE_ >, Raccord_base_32_64< _SIZE_ >, Raccord_local_32_64< _SIZE_ >, Raccord_distant_32_64< _SIZE_ >, Raccord_local_homogene_32_64< _SIZE_ >, and Raccord_distant_homogene_32_64< _SIZE_ >.
Referenced by Bord_32_64< _SIZE_ >::printOn(), Bord_Interne_32_64< _SIZE_ >::printOn(), Groupe_Faces_32_64< _SIZE_ >::printOn(), and Raccord_base_32_64< _SIZE_ >::printOn().
readOn()
template<typename _SIZE_ > Entree & Frontiere_32_64< _SIZE_ >::readOn (Entree & is) override protected virtual
Lit les specification d'une frontiere a partir d'un flot d'entree.
On lit: le nom les faces
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Objet_U.
Reimplemented in Groupe_Faces_32_64< _SIZE_ >, Joint_32_64< _SIZE_ >, Raccord_base_32_64< _SIZE_ >, Raccord_local_32_64< _SIZE_ >, Raccord_distant_32_64< _SIZE_ >, Raccord_local_homogene_32_64< _SIZE_ >, and Raccord_distant_homogene_32_64< _SIZE_ >.
Referenced by Bord_32_64< _SIZE_ >::readOn(), Bord_Interne_32_64< _SIZE_ >::readOn(), Groupe_Faces_32_64< _SIZE_ >::readOn(), and Raccord_base_32_64< _SIZE_ >::readOn().
associer_domaine()
template<typename _SIZE_ > void Frontiere_32_64< _SIZE_ >::associer_domaine (const Domaine_t & un_domaine)
Associe la frontiere au domaine dont elle depend.
Parameters
(Domaine& un_domaine) le domaine a associer a la frontiere
Referenced by Domaine_32_64< _SIZE_ >::comprimer(), TroisDto2D_32_64< _SIZE_ >::extraire_2D(), MaillerParallel::interpreter(), and Pave_32_64< _SIZE_ >::lire_front().
domaine() [1/2]
template<typename _SIZE_ > const Frontiere_32_64< _SIZE_ >::Domaine_t & Frontiere_32_64< _SIZE_ >::domaine
Renvoie le domaine associe a la frontiere.
(version const)
Returns
(Domaine&) le domaine associe a la frontiere
Referenced by Ensemble_Faces_base::associer_les_cl(), Reordonner_faces_periodiques_32_64< _SIZE_ >::check_faces_periodiques(), Periodique::completer(), Conds_lim::completer(), Domaine_32_64< _SIZE_ >::comprimer(), Champ_front_fonc_pois_ipsn::initialiser(), Champ_front_fonc_pois_tube::initialiser(), Champ_front_MED::remplir_tab(), Ch_front_input_ALE::remplir_vit_som_bord_ALE(), Champ_front_ALE::remplir_vit_som_bord_ALE(), and Champ_front_ALE_Beam::remplir_vit_som_bord_ALE().
domaine() [2/2]
template<typename _SIZE_ > Frontiere_32_64< _SIZE_ >::Domaine_t & Frontiere_32_64< _SIZE_ >::domaine
Renvoie le domaine associe a la frontiere.
Returns
(Domaine&) le domaine associe a la frontiere
le_nom()
template<typename _SIZE_ > const Nom & Frontiere_32_64< _SIZE_ >::le_nom () const inline override virtual
Donne le nom de l'Objet_U Methode a surcharger : renvoie "neant" dans cette implementation.
Returns
(Nom&) le nom de l'Objet_U
Reimplemented from Objet_U.
Referenced by Ensemble_Faces_base::associer_les_cl(), Partitionneur_base_32_64< _SIZE_ >::calculer_graphe_connexions_periodiques(), Echange_contact_VDF::calculer_h_autre_pb(), Echange_contact_rayo_semi_transp_VDF::calculer_temperature_bord(), Echange_contact_Rayo_transp_VDF::calculer_Teta_paroi(), Reordonner_faces_periodiques_32_64< _SIZE_ >::check_faces_periodiques(), Equation_base::completer(), Echange_contact_VDF_FT_Disc::completer(), Convection_Diffusion_Temperature_FT_Disc::completer(), Periodique::completer(), Domaine_32_64< _SIZE_ >::comprimer(), Joints_32_64< _SIZE_ >::comprimer(), Domaine_32_64< _SIZE_ >::comprimer_joints(), Domaine_Cl_dis_base::condition_limite_de_la_frontiere(), Partitionneur_base_32_64< _SIZE_ >::corriger_multiperiodique(), Partitionneur_base_32_64< _SIZE_ >::corriger_sommets_bord(), DecoupeBord_32_64< _SIZE_ >::decouper(), Postraiter_domaine::ecrire(), TroisDto2D_32_64< _SIZE_ >::extraire_2D(), ExtrudeParoi::extrude(), Echange_contact_Correlation_VDF::imprimer(), Echange_contact_Correlation_VEF::imprimer(), Raccord_distant_homogene_32_64< _SIZE_ >::initialise(), Echange_contact_VDF::initialiser(), Champ_front_lu::initialiser(), Champ_front_recyclage::initialiser(), Champ_front_contact_VEF::initialiser(), Champ_front_calc::initialiser(), ConcatAnsys::interpreter_(), RegroupeBord_32_64< _SIZE_ >::interpreter_(), Modele_turbulence_hyd_base::lire_motcle_non_standard(), Modele_turbulence_scal_base::lire_motcle_non_standard(), Echange_contact_rayo_semi_transp_VDF::mettre_a_jour(), Echange_contact_VDF_FT_Disc_solid::mettre_a_jour(), Echange_contact_Rayo_transp_VDF::mettre_a_jour(), Echange_contact_Correlation_VDF::mettre_a_jour(), Echange_contact_Correlation_VEF::mettre_a_jour(), RegroupeBord_32_64< _SIZE_ >::rassemble_bords(), RegroupeBord_32_64< _SIZE_ >::regroupe_bord(), Champ_front_ALE_Beam::remplir_vit_som_bord_ALE(), Champ_front_contact_VEF::trace_face_raccord(), and Ecrire_fichier_xyz_valeur::write_fields().
nommer()
template<typename _SIZE_ > void Frontiere_32_64< _SIZE_ >::nommer (const Nom & name) override virtual
Donne un nom a la frontiere.
Parameters
(Nom& name) le nom a donner a la frontiere
Reimplemented from Objet_U.
Referenced by Joints_32_64< _SIZE_ >::comprimer(), Extruder_en3::construire_bords(), DecoupeBord_32_64< _SIZE_ >::decouper(), TroisDto2D_32_64< _SIZE_ >::extraire_2D(), Extruder::extruder_dvt(), Extruder_en20::extruder_dvt(), Extruder::extruder_dvt_hexa(), Create_domain_from_sub_domain::interpreter_(), Extraire_domaine::interpreter_(), Pave_32_64< _SIZE_ >::lire_front(), and RegroupeBord_32_64< _SIZE_ >::regroupe_bord().
ajouter_faces()
template<typename _SIZE_ > void Frontiere_32_64< _SIZE_ >::ajouter_faces (const IntTab_t & sommets)
Ajoute une (ou plusieurs) face(s) a la frontiere, la (les) face(s) est (sont) specifiee(s) par un tableau.
contenant les numeros des sommets.
Parameters
(IntTab& sommets) tableau contenant les numeros des sommets des face a ajouter
Referenced by Pave_32_64< _SIZE_ >::lire_front().
typer_faces() [1/2]
template<typename _SIZE_ > void Frontiere_32_64< _SIZE_ >::typer_faces (const Motcle & typ)
Type les faces de la frontiere.
Parameters
(Motcle& typ) le type (geometrique) des faces
Referenced by TroisDto2D_32_64< _SIZE_ >::extraire_2D(), Extraire_domaine::interpreter_(), and Pave_32_64< _SIZE_ >::lire_front().
typer_faces() [2/2]
template<typename _SIZE_ > void Frontiere_32_64< _SIZE_ >::typer_faces (const Type_Face & typ)
Type les faces de la frontiere.
Parameters
(Type_Face& typ) le type (geometrique) des faces
faces() [1/2]
template<typename _SIZE_ > const Faces_t & Frontiere_32_64< _SIZE_ >::faces () const inline
Referenced by Frontiere_32_64< _SIZE_ >::add(), Ensemble_Faces_base::associer_les_cl(), Ch_front_input::buildSommetsFaces(), Champ_front_recyclage::calcul_moyenne_recyclee(), Partitionneur_base_32_64< _SIZE_ >::calculer_graphe_connexions_periodiques(), Champ_base::calculer_valeurs_som_compo_post(), Champ_base::calculer_valeurs_som_post(), Reordonner_faces_periodiques_32_64< _SIZE_ >::check_faces_periodiques(), Champ_Generique_Extraction::completer(), Extruder_en3::construire_bords(), Partitionneur_base_32_64< _SIZE_ >::corriger_multiperiodique(), Partitionneur_base_32_64< _SIZE_ >::corriger_sommets_bord(), DecoupeBord_32_64< _SIZE_ >::decouper(), Postraiter_domaine::ecrire(), TroisDto2D_32_64< _SIZE_ >::extraire_2D(), Domaine_bord_32_64< _SIZE_ >::extraire_domaine_bord(), Extruder::extruder_dvt(), Extruder_en20::extruder_dvt(), Extruder::extruder_dvt_hexa(), Ch_front_input::getTemplate(), Ch_front_Vortex::initialiser(), Champ_front_fonc_pois_ipsn::initialiser(), Champ_front_fonc_pois_tube::initialiser(), MaillerParallel::interpreter(), ConcatAnsys::interpreter_(), Extraire_domaine::interpreter_(), Corriger_frontiere_periodique_32_64< _SIZE_ >::interpreter_(), Scatter::lire_domaine(), Ch_front_input_ALE::mettre_a_jour(), Champ_front_ALE::mettre_a_jour(), Champ_front_synt::mettre_a_jour(), NettoieNoeuds_32_64< _SIZE_ >::nettoie(), RegroupeBord_32_64< _SIZE_ >::regroupe_bord(), Champ_front_MED::remplir_tab(), Ch_front_input_ALE::remplir_vit_som_bord_ALE(), Champ_front_ALE::remplir_vit_som_bord_ALE(), Champ_front_ALE_Beam::remplir_vit_som_bord_ALE(), Scatter::reordonner_faces_de_joint(), and Ecrire_fichier_xyz_valeur::write_fields().
faces() [2/2]
template<typename _SIZE_ > Faces_t & Frontiere_32_64< _SIZE_ >::faces () inline
les_sommets_des_faces() [1/2]
template<typename _SIZE_ > Frontiere_32_64< _SIZE_ >::IntTab_t & Frontiere_32_64< _SIZE_ >::les_sommets_des_faces
Renvoie les sommets des faces de la frontiere.
Returns
(IntTab&) le tableau contenant les numeros des sommets des faces de la frontiere
Referenced by Joints_32_64< _SIZE_ >::comprimer(), Scatter::corriger_espace_distant_elements_perio(), TroisDto2D_32_64< _SIZE_ >::extraire_2D(), ExtrudeParoi::extrude(), and Reordonner_faces_periodiques_32_64< _SIZE_ >::renum_som_perio().
les_sommets_des_faces() [2/2]
template<typename _SIZE_ > const Frontiere_32_64< _SIZE_ >::IntTab_t & Frontiere_32_64< _SIZE_ >::les_sommets_des_faces
Renvoie les sommets des faces de la frontiere.
Returns
(IntTab&) le tableau contenant les numeros des sommets des faces de la frontiere
nb_faces()
template<typename _SIZE_ > int_t Frontiere_32_64< _SIZE_ >::nb_faces () const inline
Renvoie le nombre de faces de la frontiere.
References Faces_32_64< _SIZE_ >::nb_faces().
Referenced by Op_Div_VEFP1B_Elem::ajouter_som(), Ensemble_Faces_base::associer_les_cl(), Traitement_particulier_NS_EC::calculer_Ec(), Partitionneur_base_32_64< _SIZE_ >::calculer_graphe_connexions_periodiques(), Face_Rayonnante::calculer_temperature(), Champ_front_contact_rayo_transp_VEF::calculer_temperature_bord(), Champ_front_contact_rayo_semi_transp_VEF::calculer_temperature_bord(), Reordonner_faces_periodiques_32_64< _SIZE_ >::chercher_direction_perio(), Triple_Line_Model_FT_Disc::completer(), Echange_contact_VDF_FT_Disc::completer(), Domaine_Cl_VDF::completer(), Champ_Generique_Extraction::completer(), Joints_32_64< _SIZE_ >::comprimer(), Triple_Line_Model_FT_Disc::compute_TCL_fluxes_in_all_boundary_cells(), Domaine_Cl_dis_base::condition_limite_de_la_face_reelle(), Domaine_Cl_dis_base::condition_limite_de_la_face_virtuelle(), Scatter::corriger_espace_distant_elements_perio(), ExtrudeParoi::extrude(), Modele_Rayonnement_Milieu_Transparent::flux_radiatif(), Champ_Generique_Extraction::get_champ(), Raccord_distant_homogene_32_64< _SIZE_ >::initialise(), Champ_front_contact_rayo_transp_VEF::initialiser(), Champ_front_contact_rayo_semi_transp_VEF::initialiser(), Ch_front_Vortex::initialiser(), Champ_front_fonc_pois_ipsn::initialiser(), Champ_front_fonc_pois_tube::initialiser(), Champ_front_lu::initialiser(), Champ_front_contact_VEF::initialiser(), Distanceparoi::interpreter_(), Domaine_Cl_dis_base::la_cl_de_la_face(), Scatter::lire_domaine(), Perte_Charge_Singuliere::lire_surfaces(), Ch_front_input_ALE::mettre_a_jour(), Champ_front_ALE::mettre_a_jour(), Champ_front_bruite::mettre_a_jour(), Champ_front_debit_QC::mettre_a_jour(), Champ_front_debit_QC_fonc_t::mettre_a_jour(), Champ_front_contact_fictif_VEF::mettre_a_jour(), Champ_front_contact_VEF::mettre_a_jour(), Echange_contact_VDF_FT_Disc_solid::mettre_a_jour(), Ch_front_Vortex::mettre_a_jour(), Champ_front_contact_rayo_transp_VEF::mettre_a_jour_flux_radiatif(), Champ_front_contact_rayo_semi_transp_VEF::mettre_a_jour_flux_radiatif(), Champ_front_contact_rayo_transp_VEF::modifie_gradients_pour_rayonnement(), Champ_front_contact_rayo_semi_transp_VEF::modifie_gradients_pour_rayonnement(), Front_VF::nb_faces(), Front_VF::nb_faces_tot(), RegroupeBord_32_64< _SIZE_ >::regroupe_bord(), Champ_front_contact_VEF::remplir_connect_bords(), Domaine_VF::remplir_face_numero_bord(), Champ_front_MED::remplir_tab(), Champ_front_ALE::remplir_vit_som_bord_ALE(), Champ_front_ALE_Beam::remplir_vit_som_bord_ALE(), Champ_front_base::valeurs_face(), Champ_front_contact_VEF::verifier_scalaire_bord(), and Ecrire_fichier_xyz_valeur::write_fields().
dimensionner()
template<typename _SIZE_ > void Frontiere_32_64< _SIZE_ >::dimensionner (int_t i) inline
Dimensionne la frontiere, i.e. fixe son nombre de faces.
References Faces_32_64< _SIZE_ >::dimensionner().
Referenced by Pave_32_64< _SIZE_ >::lire_front().
renum()
template<typename _SIZE_ > void Frontiere_32_64< _SIZE_ >::renum (const IntVect_t & Les_Nums)
Renumerote les noeuds (sommets) des faces.
Le noeud de numero k devient le noeud de numero Les_Nums[k]
Parameters
(IntVect& Les_Nums) le vecteur de renumerotation le_nouveau_sommet[i] = Les_Nums[ancien_sommet[i]]
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), and TRUSTTab< _TYPE_, _SIZE_ >::dimension_int().
add()
template<typename _SIZE_ > void Frontiere_32_64< _SIZE_ >::add (const Frontiere_32_64< _SIZE_ > & front)
Ajoute les sommets (et faces) de la frontiere passee en parametre a l'objet (Frontiere_32_64).
Parameters
(Frontiere_32_64& front) la frontiere a "ajouter" a l'objet
References TRUSTTab< _TYPE_, _SIZE_ >::dimension_int(), Frontiere_32_64< _SIZE_ >::faces(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Faces_32_64< _SIZE_ >::nb_faces(), Faces_32_64< _SIZE_ >::nb_som_faces(), Faces_32_64< _SIZE_ >::sommet(), Faces_32_64< _SIZE_ >::voisin(), and Faces_32_64< _SIZE_ >::voisins().
Referenced by Domaine_32_64< _SIZE_ >::comprimer(), Domaine_32_64< _SIZE_ >::comprimer_joints(), RegroupeBord_32_64< _SIZE_ >::interpreter_(), Modele_turbulence_hyd_base::lire_motcle_non_standard(), Modele_turbulence_scal_base::lire_motcle_non_standard(), and Pave_32_64< _SIZE_ >::readOn().
nb_faces_virt()
template<typename _SIZE_ > int_t Frontiere_32_64< _SIZE_ >::nb_faces_virt () const inline
References TRUSTArray< _TYPE_, _SIZE_ >::size_array().
face_virt()
template<typename _SIZE_ > int_t Frontiere_32_64< _SIZE_ >::face_virt (int_t i) const inline
num_premiere_face()
template<typename _SIZE_ > int_t Frontiere_32_64< _SIZE_ >::num_premiere_face () const inline
Referenced by Maillage_FT_Disc::calculer_costheta_minmax(), Traitement_particulier_NS_EC::calculer_Ec(), Triple_Line_Model_FT_Disc::completer(), Domaine_Cl_VDF::completer(), Champ_Generique_Extraction::completer(), Triple_Line_Model_FT_Disc::compute_TCL_fluxes_in_all_boundary_cells(), Domaine_Cl_dis_base::condition_limite_de_la_face_reelle(), ExtrudeParoi::extrude(), Modele_Rayonnement_Milieu_Transparent::flux_radiatif(), Raccord_distant_homogene_32_64< _SIZE_ >::initialise(), Ch_front_Vortex::initialiser(), Champ_front_lu::initialiser(), Distanceparoi::interpreter_(), Domaine_Cl_dis_base::la_cl_de_la_face(), Echange_contact_VDF_FT_Disc::mettre_a_jour(), Echange_contact_VDF_FT_Disc_solid::mettre_a_jour(), Ch_front_Vortex::mettre_a_jour(), Champ_front_contact_rayo_transp_VEF::mettre_a_jour_flux_radiatif(), Front_VF::num_premiere_face(), Domaine_VF::remplir_face_numero_bord(), and Frontiere_ouverte_rho_u_impose::val_imp_au_temps().
fixer_num_premiere_face()
template<typename _SIZE_ > void Frontiere_32_64< _SIZE_ >::fixer_num_premiere_face (int_t i) inline
get_faces_virt() [1/2]
template<typename _SIZE_ > const ArrOfInt_t & Frontiere_32_64< _SIZE_ >::get_faces_virt () const inline
Referenced by Domaine_Cl_dis_base::condition_limite_de_la_face_virtuelle(), Front_VF::nb_faces_tot(), Front_VF::num_face(), Front_VF::num_local_face(), Connectivite_frontieres::remplir_faces_voisins(), and Domaine_Cl_VEF::remplir_volumes_entrelaces_Cl().
get_faces_virt() [2/2]
template<typename _SIZE_ > ArrOfInt_t & Frontiere_32_64< _SIZE_ >::get_faces_virt () inline
get_aire()
template<typename _SIZE_ > const double & Frontiere_32_64< _SIZE_ >::get_aire () const inline
Referenced by Terme_Source_Canal_perio::completer().
set_aire()
template<typename _SIZE_ > void Frontiere_32_64< _SIZE_ >::set_aire (double & aire) inline
creer_tableau_faces()
template<typename _SIZE_ > void Frontiere_32_64< _SIZE_ >::creer_tableau_faces (Array_base & v, RESIZE_OPTIONS opt = RESIZE_OPTIONS::COPY_INIT) const virtual
Cree un tableau ayant une "ligne" par face de cette frontiere Voir MD_Vector_tools::creer_tableau_distribue()
References MD_Vector_tools::creer_tableau_distribue().
Referenced by Echange_interne_global_impose::completer(), Paroi_scal_hyd_base_EF::init_lois_paroi(), Paroi_scal_hyd_base_VEF::init_lois_paroi(), Echange_contact_PolyMAC::initialiser(), Echange_contact_VDF::initialiser(), and Champ_front_var::initialiser().
trace_elem_local() [1/2]
template<typename _SIZE_ > void Frontiere_32_64< _SIZE_ >::trace_elem_local (const DoubleTab & y, DoubleTab & x) const virtual
Referenced by Echange_contact_VDF_FT_Disc_solid::mettre_a_jour(), and Champ_implementation_P0::trace().
trace_face_local() [1/4]
template<typename _SIZE_ > void Frontiere_32_64< _SIZE_ >::trace_face_local (const DoubleTab & y, DoubleTab & x) const virtual
Referenced by Champ_P1NC_implementation::trace(), Champ_Q1NC_implementation::trace(), Champ_Elem_PolyMAC::trace(), Echange_contact_PolyMAC::update_coeffs(), and Echange_contact_PolyMAC::update_delta().
trace_face_local() [2/4]
template<typename _SIZE_ > void Frontiere_32_64< _SIZE_ >::trace_face_local (const DoubleVect & y, DoubleVect & x) const virtual
trace_elem_distant() [1/2]
template<typename _SIZE_ > void Frontiere_32_64< _SIZE_ >::trace_elem_distant (const DoubleTab & , DoubleTab &) const virtual
Reimplemented in Raccord_local_homogene_32_64< _SIZE_ >, Raccord_distant_homogene_32_64< _SIZE_ >, Raccord_local_homogene_32_64< _SIZE_ >, and Raccord_distant_homogene_32_64< _SIZE_ >.
Referenced by Echange_contact_VDF_FT_Disc_solid::mettre_a_jour(), and Champ_implementation_P0::trace().
trace_som_distant() [1/2]
template<typename _SIZE_ > void Frontiere_32_64< _SIZE_ >::trace_som_distant (const DoubleTab & , DoubleTab &) const virtual
Referenced by Champ_implementation_sommet::trace().
trace_face_distant() [1/4]
template<typename _SIZE_ > void Frontiere_32_64< _SIZE_ >::trace_face_distant (const DoubleTab & , DoubleTab &) const virtual
Reimplemented in Raccord_local_homogene_32_64< _SIZE_ >, Raccord_distant_homogene_32_64< _SIZE_ >, Raccord_local_homogene_32_64< _SIZE_ >, and Raccord_distant_homogene_32_64< _SIZE_ >.
Referenced by Echange_contact_Rayo_transp_VDF::calculer_Teta_paroi(), Champ_P1NC_implementation::trace(), Champ_Q1NC_implementation::trace(), Champ_Elem_PolyMAC::trace(), Champ_front_contact_VEF::trace_face_raccord(), Echange_contact_PolyMAC::update_coeffs(), and Echange_contact_PolyMAC::update_delta().
trace_face_distant() [2/4]
template<typename _SIZE_ > void Frontiere_32_64< _SIZE_ >::trace_face_distant (const DoubleVect & , DoubleVect &) const virtual
Reimplemented in Raccord_local_homogene_32_64< _SIZE_ >, Raccord_distant_homogene_32_64< _SIZE_ >, Raccord_local_homogene_32_64< _SIZE_ >, and Raccord_distant_homogene_32_64< _SIZE_ >.
trace_som_local() [1/2]
template<typename _SIZE_ > void Frontiere_32_64< _SIZE_ >::trace_som_local (const DoubleTab & y, DoubleTab & x) const virtual
Referenced by Champ_implementation_sommet::trace().
info_obj() [1/2]
const Type_info Frontiere_32_64< int >::info_obj ("Frontiere" , 1 , Frontiere_32_64bases< int >)
info_obj() [2/2]
const Type_info Frontiere_32_64< trustIdType >::info_obj ("Frontiere" "_64" , 1 , Frontiere_32_64bases< trustIdType >)
trace_elem_local() [2/2]
void Frontiere_32_64< int >::trace_elem_local (const DoubleTab & y, DoubleTab & x) const
Renvoie la trace sur la frontiere du tableau aux elements y.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Process::exit(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
trace_som_local() [2/2]
void Frontiere_32_64< int >::trace_som_local (const DoubleTab & y, DoubleTab & x) const
Renvoie la trace sur la frontiere du tableau aux noeuds y.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_int(), Process::exit(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
trace_face_local() [3/4]
void Frontiere_32_64< int >::trace_face_local (const DoubleVect & y, DoubleVect & x) const
Renvoie la trace sur la frontiere du tableau aux faces y.
References Process::exit().
trace_face_local() [4/4]
void Frontiere_32_64< int >::trace_face_local (const DoubleTab & y, DoubleTab & x) const
Renvoie la trace sur la frontiere du tableau aux faces y.
References TRUSTArray< _TYPE_, _SIZE_ >::addr(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), and TRUSTVect< _TYPE_, _SIZE_ >::line_size().
trace_som_distant() [2/2]
void Frontiere_32_64< int >::trace_som_distant (const DoubleTab & , DoubleTab &) const
References Process::exit().
trace_elem_distant() [2/2]
void Frontiere_32_64< int >::trace_elem_distant (const DoubleTab & , DoubleTab &) const
References Process::exit().
trace_face_distant() [3/4]
void Frontiere_32_64< int >::trace_face_distant (const DoubleTab & , DoubleTab &) const
References Process::exit().
trace_face_distant() [4/4]
void Frontiere_32_64< int >::trace_face_distant (const DoubleVect & , DoubleVect &) const
References Process::exit().
Member Data Documentation
info_obj
template<typename _SIZE_ > const Type_info Frontiere_32_64< _SIZE_ >::info_obj static