TrioCFD: Navier_Stokes_std_ALE Class Reference
Navier_Stokes_std_ALE Class Reference
#include <Navier_Stokes_std_ALE.h>
Public Member Functions
const Type_info * get_info () const override
void mettre_a_jour (double) override
virtual int reprendre (Entree &) override
virtual int sauvegarder (Sortie &) const override
Public Member Functions inherited from Navier_Stokes_std
void abortTimeStep () override
void associer_milieu_base (const Milieu_base &) override
void associer_pb_base (const Probleme_base &) override
virtual void calculer_la_pression_en_pa ()
void completer () override
DoubleTab & derivee_en_temps_inco (DoubleTab &) override
const Motcle & domaine_application () const override
Fluide_base & fluide ()
const Fluide_base & fluide () const
const Type_info * get_info () const override
int impr (Sortie &os) const override
const Champ_Inc_base & inconnue () const override
Champ_Inc_base & inconnue () override
bool initTimeStep (double dt) override
Entree & lire_cond_init (Entree &) override
int lire_motcle_non_standard (const Motcle &, Entree &) override
void mettre_a_jour (double temps) override
const Milieu_base & milieu () const override
Milieu_base & milieu () override
int nombre_d_operateurs () const override
const Operateur & operateur (int) const override
Operateur & operateur (int) override
Operateur_Div & operateur_divergence ()
const Operateur_Div & operateur_divergence () const
Operateur_Grad & operateur_gradient ()
const Operateur_Grad & operateur_gradient () const
int preparer_calcul () override
virtual void projeter ()
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
SolveurSys & solveur_pression ()
int verif_Cl () const override
Public Member Functions inherited from Equation_base
virtual void abortTimeStep ()
virtual void associer_domaine_dis (const Domaine_dis_base &)
virtual void associer_pb_base (const Probleme_base &)
virtual void associer_sch_tps_base (const Schema_Temps_base &)
virtual double calculer_pas_de_temps () const
virtual void completer ()
virtual std::vector< YAML_data > data_a_sauvegarder () const
DoubleTab & derivee_en_temps_conv (DoubleTab &, const DoubleTab &)
virtual DoubleTab & derivee_en_temps_inco (DoubleTab &)
const Discretisation_base & discretisation () const
virtual void discretiser ()
virtual const Motcle & domaine_application () const
virtual Domaine_Cl_dis_base & domaine_Cl_dis ()
virtual const Domaine_Cl_dis_base & domaine_Cl_dis () const
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual void imprimer (Sortie &os) const
virtual bool initTimeStep (double dt)
const Nom & le_nom () const override
int limpr () const
virtual void mettre_a_jour (double temps)
virtual int preparer_calcul ()
Probleme_base & probleme ()
const Probleme_base & probleme () const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Schema_Temps_base & schema_temps ()
const Schema_Temps_base & schema_temps () const
Solveur_Masse_base & solv_masse ()
const Solveur_Masse_base & solv_masse () const
Sources & sources ()
const Sources & sources () const
virtual void valider_iteration ()
virtual void verifie_ch_init_nb_comp (const Champ_Inc_base &ch_ref, const int nb_comp) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Navier_Stokes_std
virtual void discretiser_assembleur_pression ()
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Equation_base
virtual Entree & lire_cl (Entree &)
virtual Entree & lire_cond_init (Entree &)
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual Entree & lire_sources (Entree &)
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
virtual int verif_Cl () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Navier_Stokes_std_ALE()
Navier_Stokes_std_ALE::Navier_Stokes_std_ALE ()
~Navier_Stokes_std_ALE()
Navier_Stokes_std_ALE::~Navier_Stokes_std_ALE ()
Member Function Documentation
cree_instance()
Objet_U * Navier_Stokes_std_ALE::cree_instance () static
taille_memoire()
unsigned Navier_Stokes_std_ALE::taille_memoire () const override virtual
Reimplemented from Navier_Stokes_std.
Reimplemented in Navier_Stokes_Turbulent_ALE.
duplique()
int Navier_Stokes_std_ALE::duplique () const override virtual
Reimplemented from Navier_Stokes_std.
Reimplemented in Navier_Stokes_Turbulent_ALE.
info()
const Type_info * Navier_Stokes_std_ALE::info () static
get_info()
const Type_info * Navier_Stokes_std_ALE::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Navier_Stokes_std.
Reimplemented in Navier_Stokes_Turbulent_ALE.
self_cast() [1/2]
Navier_Stokes_std_ALE & Navier_Stokes_std_ALE::self_cast (Objet_U & r) static
self_cast() [2/2]
const Navier_Stokes_std_ALE & Navier_Stokes_std_ALE::self_cast (const Objet_U & r) static
printOn()
Sortie & Navier_Stokes_std_ALE::printOn (Sortie & os) const override protected virtual
Surcharge Objet_U::printOn Imprime l'equation et ses composants sur un flot de sortie.
Imprime le nom de l'equation, le solveur masse, les termes sources les conditions aux limites discretisees, les inconnues et les operateurs.
Parameters
(Sortie& os) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Navier_Stokes_std.
Reimplemented in Navier_Stokes_Turbulent_ALE.
References Navier_Stokes_std::printOn().
readOn()
Entree & Navier_Stokes_std_ALE::readOn (Entree & is) override protected virtual
Appel Equation_base::readOn(Entree& is) En sortie verifie que l'on a bien lu:
   - le terme diffusif,
   - le terme convectif,
   - le solveur en pression
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Exceptions
terme diffusif non specifie dans jeu de donnees, specifier un type negligeable pour l'operateur si il est a negliger
terme convectif non specifie dans jeu de donnees, specifier un type negligeable pour l'operateur si il est a negliger
solveur pression non defini dans jeu de donnees
Reimplemented from Navier_Stokes_std.
Reimplemented in Navier_Stokes_Turbulent_ALE.
References Navier_Stokes_std::readOn().
Referenced by Navier_Stokes_Turbulent_ALE::readOn().
renewing_jacobians()
void Navier_Stokes_std_ALE::renewing_jacobians (DoubleTab & derivee) override virtual
Reimplemented from Navier_Stokes_std.
References Op_Conv_ALE::ajouterALE(), Solveur_Masse_base::appliquer(), Op_Conv_ALE_VEF::calculateALEjacobian(), Equation_base::discretisation(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Process::exit(), Domaine_ALE::getNewJacobian(), Navier_Stokes_std::la_vitesse, Schema_Temps_base::nb_pas_dt(), Equation_base::probleme(), Objet_U::que_suis_je(), Probleme_base::schema_temps(), Equation_base::solveur_masse, Navier_Stokes_std::terme_convectif, Domaine_ALE::update_ALEjacobians(), TRUST_Deriv< _CLASSE_ >::valeur(), Champ_Inc_base::valeurs(), and Debog::verifier().
div_ale_derivative()
void Navier_Stokes_std_ALE::div_ale_derivative (DoubleTrav & deriveeALE, double timestep, DoubleTab & derivee, DoubleTrav & secmemP) override virtual
Reimplemented from Navier_Stokes_std.
References Navier_Stokes_std::assembleur_pression_, Operateur_Div::calculer(), Objet_U::dimension, Navier_Stokes_std::divergence, TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_ALE::getNewJacobian(), Domaine_ALE::getOldJacobian(), Navier_Stokes_std::la_vitesse, Assembleur_base::modifier_secmem(), Equation_base::probleme(), TRUSTVect< _TYPE_, _SIZE_ >::size(), Champ_Inc_base::valeurs(), Debog::verifier(), and Domaine_ALE::vitesse_faces().
update_pressure_matrix()
void Navier_Stokes_std_ALE::update_pressure_matrix () override virtual
Reimplemented from Navier_Stokes_std.
References Assembleur_base::assembler(), Navier_Stokes_std::assembleur_pression_, Navier_Stokes_std::matrice_pression_, Equation_base::probleme(), Navier_Stokes_std::solveur_pression_, and Domaine_ALE::update_or_not_matrix_coeffs().
discretiser()
void Navier_Stokes_std_ALE::discretiser () override virtual
Dicretise l'equation.
Reimplemented from Navier_Stokes_std.
References Field_base::add_synonymous(), Champs_compris_T< FIELD_TYPE >::ajoute_champ(), ALEMeshStructuralForces_, ALEMeshStructuralPressure_, ALEMeshStructuralVonMises_, ALEMeshTotalDisplacement_, ALEMeshVelocity_, Equation_base::champs_compris_, Objet_U::dimension, Equation_base::discretisation(), Navier_Stokes_std::discretiser(), Discretisation_base::discretiser_champ(), Equation_base::domaine_dis(), Domaine_ALE::getMeshMotionModel(), Equation_base::probleme(), Equation_base::schema_temps(), and TRUST_Deriv< _CLASSE_ >::valeur().
mettre_a_jour()
void Navier_Stokes_std_ALE::mettre_a_jour (double temps) override virtual
Effectue une mise a jour en temps de l'equation.
Appelle Equation_base::mettre_a_jour(double) et met a jour la pression. Integration des points suivis si le fluide est marque Mise a jour du champ postraitable correspondant
Parameters
(double temps) le temps de mise a jour
Reimplemented from Navier_Stokes_std.
Reimplemented in Navier_Stokes_Turbulent_ALE.
References ALEMeshStructuralForces_, ALEMeshStructuralPressure_, ALEMeshStructuralVonMises_, ALEMeshTotalDisplacement_, ALEMeshVelocity_, Objet_U::dimension, TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_ALE::getMeshMotionModel(), Domaine_ALE::getMeshPbForceFace(), Domaine_ALE::getMeshPbPressure(), Domaine_ALE::getMeshPbVonMises(), Champ_Inc_base::mettre_a_jour(), Navier_Stokes_std::mettre_a_jour(), Schema_Temps_base::pas_de_temps(), Equation_base::probleme(), Equation_base::schema_temps(), TRUSTVect< _TYPE_, _SIZE_ >::size(), Champ_Inc_base::valeurs(), and Domaine_ALE::vitesse_faces().
Referenced by Navier_Stokes_Turbulent_ALE::mettre_a_jour().
data_a_sauvegarder()
std::vector< YAML_data > Navier_Stokes_std_ALE::data_a_sauvegarder () const override virtual
for PDI IO: retrieve name, type and dimensions of the fields to save/restore
Reimplemented from Navier_Stokes_std.
Reimplemented in Navier_Stokes_Turbulent_ALE.
References Navier_Stokes_std::data_a_sauvegarder(), Nom::getString(), Probleme_U::le_nom(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Equation_base::probleme(), Champ_Inc_base::valeurs(), and Navier_Stokes_std::vitesse().
Referenced by Navier_Stokes_Turbulent_ALE::data_a_sauvegarder().
sauvegarder()
int Navier_Stokes_std_ALE::sauvegarder (Sortie & os) const override virtual
Appelle Equation_base::sauvegarder(Sortie&) et sauvegarde la pression sur un flot de sortie.
Parameters
(Sortie& os) un flot de sortie sur lequel sauvegarder
Returns
(int) renvoie toujours 1
Reimplemented from Navier_Stokes_std.
Reimplemented in Navier_Stokes_Turbulent_ALE.
References TRUSTArray< _TYPE_, _SIZE_ >::addr(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Domaine_ALE::getNewJacobian(), Domaine_ALE::getOldJacobian(), EcritureLectureSpecial::is_ecriture_special(), TRUST_2_PDI::is_PDI_checkpoint(), Probleme_U::le_nom(), Nom::majuscule(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Process::nproc(), Equation_base::probleme(), Navier_Stokes_std::sauvegarder(), TRUST_2_PDI::share_TRUSTTab_dimensions(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), TRUST_2_PDI::TRUST_start_sharing(), and Navier_Stokes_std::vitesse().
Referenced by Navier_Stokes_Turbulent_ALE::sauvegarder().
reprendre()
int Navier_Stokes_std_ALE::reprendre (Entree & is) override virtual
Effectue une reprise a partir d'un flot d'entree.
Appelle Equation_base::reprendre() et reprend la pression.
Parameters
(Entree& is) un flot d'entree
Returns
(int) renvoie toujours 1
Exceptions
la reprise a echoue, identificateur de la pression non trouve
Reimplemented from Navier_Stokes_std.
Reimplemented in Navier_Stokes_Turbulent_ALE.
References Probleme_base::domaine(), Process::exit(), EcritureLectureSpecial::is_lecture_special(), TRUST_2_PDI::is_PDI_restart(), Domaine_base::le_nom(), Process::nproc(), Equation_base::probleme(), Objet_U::que_suis_je(), Navier_Stokes_std::reprendre(), Domaine_ALE::resumptionJacobian(), Equation_base::schema_temps(), and Navier_Stokes_std::vitesse().
Referenced by Navier_Stokes_Turbulent_ALE::reprendre().
Member Data Documentation
info_obj
const Type_info Navier_Stokes_std_ALE::info_obj static
ALEMeshVelocity_
TRUST_Deriv< Champ_Inc_base > Navier_Stokes_std_ALE::ALEMeshVelocity_ protected
Referenced by discretiser(), and mettre_a_jour().
ALEMeshTotalDisplacement_
TRUST_Deriv< Champ_Inc_base > Navier_Stokes_std_ALE::ALEMeshTotalDisplacement_ protected
Referenced by discretiser(), and mettre_a_jour().
ALEMeshStructuralPressure_
TRUST_Deriv< Champ_Inc_base > Navier_Stokes_std_ALE::ALEMeshStructuralPressure_ protected
Referenced by discretiser(), and mettre_a_jour().
ALEMeshStructuralVonMises_
TRUST_Deriv< Champ_Inc_base > Navier_Stokes_std_ALE::ALEMeshStructuralVonMises_ protected
Referenced by discretiser(), and mettre_a_jour().
ALEMeshStructuralForces_
TRUST_Deriv< Champ_Inc_base > Navier_Stokes_std_ALE::ALEMeshStructuralForces_ protected
Referenced by discretiser(), and mettre_a_jour().