TrioCFD: Champs_compris_T< FIELD_TYPE > Class Template Reference
Champs_compris_T< FIELD_TYPE > Class Template Reference
#include <Champs_compris.h>
Detailed Description
template<typename FIELD_TYPE>
class Champs_compris_T< FIELD_TYPE >
Operateur, Source, Traitement_particulier.
Parametrized by the type of field: typically Champ_base or IJK_Field_double
Member Function Documentation
get_champ()
template<typename FIELD_TYPE > const FIELD_TYPE & Champs_compris_T< FIELD_TYPE >::get_champ (const Motcle & nom) const
References Nom::getString().
Referenced by Transport_Marqueur_FT::get_champ(), Navier_Stokes_Aposteriori::get_champ(), Transport_K_ou_Eps_base::get_champ(), Modele_Fonc_Bas_Reynolds_Base::get_champ(), Modele_Fonc_Bas_Reynolds_Thermique_Base::get_champ(), Modele_Fonc_Realisable_base::get_champ(), Source_PDF_EF::get_champ(), Paroi_hyd_base_EF::get_champ(), Loi_Fermeture_base::get_champ(), Milieu_base::get_champ(), Operateur_base::get_champ(), Source_base::get_champ(), Loi_Etat_base::get_champ(), Convection_Diffusion_Temperature::get_champ(), Convection_Diffusion_Temperature_base::get_champ(), Navier_Stokes_std::get_champ(), Marqueur_Lagrange_base::get_champ(), Traitement_particulier_NS_base::get_champ(), Diametre_bulles_champ::get_champ(), Diametre_bulles_constant::get_champ(), Diametre_bulles_musig::get_champ(), Gravite_Multiphase::get_champ(), Turbulence_paroi_base::get_champ(), Turbulence_paroi_scal_base::get_champ(), Conduction::get_champ(), Traitement_particulier_Solide_base::get_champ(), IJK_Interfaces::get_IJK_field(), IJK_Thermal_base::get_IJK_field(), Navier_Stokes_FTD_IJK::get_IJK_field(), Postprocessing_IJK::get_IJK_field(), Statistiques_dns_ijk::get_IJK_field(), Statistiques_dns_ijk_FT::get_IJK_field(), and IJK_Ghost_Fluid_Fields::get_IJK_field().
has_champ() [1/2]
template<typename FIELD_TYPE > bool Champs_compris_T< FIELD_TYPE >::has_champ (const Motcle & nom, TRUST_Ref< FIELD_TYPE * > & ref_champ) const
References Nom::getString().
Referenced by Puissance_Thermique_QC_EF::get_champ(), Equation_base::get_champ(), Modele_turbulence_hyd_base::get_champ(), Modele_turbulence_scal_base::get_champ(), IJK_Thermal_base::get_IJK_field(), IJK_Interfaces::has_champ(), IJK_Thermal_base::has_champ(), Navier_Stokes_FTD_IJK::has_champ(), Postprocessing_IJK::has_champ(), Statistiques_dns_ijk::has_champ(), IJK_Ghost_Fluid_Fields::has_champ(), Modele_Fonc_Bas_Reynolds_Base::has_champ(), Modele_Fonc_Bas_Reynolds_Thermique_Base::has_champ(), Modele_Fonc_Realisable_base::has_champ(), Source_PDF_EF::has_champ(), Puissance_Thermique_QC_EF::has_champ(), Paroi_hyd_base_EF::has_champ(), Correlation_base::has_champ(), Equation_base::has_champ(), Loi_Fermeture_base::has_champ(), Milieu_base::has_champ(), Operateur_base::has_champ(), Source_base::has_champ(), Loi_Etat_base::has_champ(), Marqueur_Lagrange_base::has_champ(), Traitement_particulier_NS_base::has_champ(), Diametre_bulles_champ::has_champ(), Diametre_bulles_constant::has_champ(), Diametre_bulles_musig::has_champ(), Gravite_Multiphase::has_champ(), Turbulence_paroi_base::has_champ(), Turbulence_paroi_scal_base::has_champ(), Modele_turbulence_hyd_base::has_champ(), Modele_turbulence_scal_base::has_champ(), and Traitement_particulier_Solide_base::has_champ().
has_champ() [2/2]
template<typename FIELD_TYPE > bool Champs_compris_T< FIELD_TYPE >::has_champ (const Motcle & nom) const
References Nom::getString().
ajoute_champ()
template<typename FIELD_TYPE > void Champs_compris_T< FIELD_TYPE >::ajoute_champ (const FIELD_TYPE & champ)
References Process::exit(), and TRUST_Vector< _CLASSE_ >::size().
Referenced by Equation_base::add_champs_compris(), Champs_compris_IJK::ajoute_champ_vectoriel(), Postprocessing_IJK::alloc_fields(), Modele_turbulence_hyd_LES_DSGS_VDF::associer(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::associer(), Source_Transport_K_Omega_VEF_Face::creer_champ(), Op_Conv_VDF_base::creer_champ(), Domaine_dis_base::creer_champ(), Transport_Marqueur_FT::creer_champ(), Navier_Stokes_phase_field::creer_champ(), Navier_Stokes_Aposteriori::creer_champ(), Source_PDF_EF::creer_champ(), Paroi_hyd_base_EF::creer_champ(), Equation_base::creer_champ(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::creer_champ(), Fluide_Dilatable_base::creer_champ(), Convection_Diffusion_Temperature::creer_champ(), Convection_Diffusion_Temperature_base::creer_champ(), Navier_Stokes_std::creer_champ(), QDM_Multiphase::creer_champ(), Source_Portance_interfaciale_base::creer_champ(), Turbulence_paroi_base::creer_champ(), Conduction::creer_champ(), Modele_Fonc_Bas_Reynolds_Base::discretiser(), Modele_Fonc_Realisable_base::discretiser(), Equation_base::discretiser(), Modele_turbulence_hyd_base::discretiser(), Modele_turbulence_scal_base::discretiser(), Navier_Stokes_std_ALE::discretiser(), Echelle_temporelle_turbulente::discretiser(), Energie_cinetique_turbulente::discretiser(), Energie_cinetique_turbulente_WIT::discretiser(), Taux_dissipation_turbulent::discretiser(), Convection_Diffusion_Temperature_FT_Disc::discretiser(), Navier_Stokes_FT_Disc::discretiser(), Transport_Interfaces_FT_Disc::discretiser(), Convection_Diffusion_Phase_field::discretiser(), Equation_rayonnement_base::discretiser(), Transport_K_Eps_base::discretiser(), Transport_K_Omega_base::discretiser(), Transport_K_ou_Eps_base::discretiser(), Transport_Fluctuation_Temperature::discretiser(), Transport_Fluctuation_Temperature_W::discretiser(), Transport_Flux_Chaleur_Turbulente::discretiser(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::discretiser(), Convection_Diffusion_Concentration::discretiser(), Convection_Diffusion_Temperature::discretiser(), Navier_Stokes_std::discretiser(), Aire_interfaciale::discretiser(), Energie_Multiphase::discretiser(), Energie_Multiphase_Enthalpie::discretiser(), Masse_Multiphase::discretiser(), Modele_turbulence_hyd_0_eq_base::discretiser(), Conduction::discretiser(), Loi_Fermeture_Test::discretiser(), Milieu_base::discretiser(), Marqueur_Lagrange_base::discretiser(), Fluide_Dilatable_base::discretiser(), Fluide_Quasi_Compressible::discretiser(), Fluide_Weakly_Compressible::discretiser(), Fluide_base::discretiser(), Fluide_Ostwald::discretiser(), Fluide_reel_base::discretiser(), Milieu_composite::discretiser(), Solide::discretiser(), Navier_Stokes_std::discretiser_grad_p(), Constituant::discretiser_multi_concentration(), Postprocessing_IJK::init_integrated_and_ana(), Navier_Stokes_FTD_IJK::initialise_ns_fields(), IJK_Thermal_base::initialize(), IJK_Thermal_Onefluid::initialize(), IJK_Interfaces::initialize(), IJK_Thermal_base::initialize_switch(), Traitement_particulier_NS_Pression_VDF::lire(), Traitement_particulier_NS_Brech_VEF::lire(), Traitement_particulier_NS_Pression_VEF::lire(), Terme_Source_Acceleration::lire_data(), Navier_Stokes_phase_field::lire_motcle_non_standard(), Convection_Diffusion_Concentration::lire_motcle_non_standard(), Navier_Stokes_FT_Disc::preparer_calcul(), Terme_Puissance_Thermique_DG_base::readOn(), Source_Scalaire_EF::readOn(), Puissance_Thermique_EF::readOn(), Puissance_Thermique_QC_EF::readOn(), Terme_Puissance_Thermique_PolyMAC_base::readOn(), Convection_Diffusion_Espece_Binaire_base::readOn(), Convection_Diffusion_Espece_Multi_base::readOn(), Diametre_bulles_champ::readOn(), Diametre_bulles_constant::readOn(), Diametre_bulles_musig::readOn(), Gravite_Multiphase::readOn(), Masse_Multiphase::readOn(), Terme_Puissance_Thermique_VDF_base::readOn(), Terme_Puissance_Thermique_VEF_base::readOn(), and IJK_Interfaces::register_fields().
liste_noms_compris()
template<typename FIELD_TYPE > const Noms Champs_compris_T< FIELD_TYPE >::liste_noms_compris
References TRUST_Vector< _CLASSE_ >::add().
Referenced by Transport_Marqueur_FT::get_noms_champs_postraitables(), Navier_Stokes_Aposteriori::get_noms_champs_postraitables(), Source_Transport_K_Omega_VEF_Face::get_noms_champs_postraitables(), Modele_Fonc_Bas_Reynolds_Base::get_noms_champs_postraitables(), Modele_Fonc_Bas_Reynolds_Thermique_Base::get_noms_champs_postraitables(), Modele_Fonc_Realisable_base::get_noms_champs_postraitables(), Source_PDF_EF::get_noms_champs_postraitables(), Puissance_Thermique_QC_EF::get_noms_champs_postraitables(), Domaine_dis_base::get_noms_champs_postraitables(), Equation_base::get_noms_champs_postraitables(), Loi_Fermeture_base::get_noms_champs_postraitables(), Milieu_base::get_noms_champs_postraitables(), Operateur_base::get_noms_champs_postraitables(), Source_base::get_noms_champs_postraitables(), Loi_Etat_base::get_noms_champs_postraitables(), Convection_Diffusion_Temperature::get_noms_champs_postraitables(), Convection_Diffusion_Temperature_base::get_noms_champs_postraitables(), Navier_Stokes_std::get_noms_champs_postraitables(), Marqueur_Lagrange_base::get_noms_champs_postraitables(), Traitement_particulier_NS_base::get_noms_champs_postraitables(), Turbulence_paroi_base::get_noms_champs_postraitables(), Turbulence_paroi_scal_base::get_noms_champs_postraitables(), Modele_turbulence_hyd_base::get_noms_champs_postraitables(), Modele_turbulence_scal_base::get_noms_champs_postraitables(), Conduction::get_noms_champs_postraitables(), and Traitement_particulier_Solide_base::get_noms_champs_postraitables().
clear_champs_compris()
template<typename FIELD_TYPE > void Champs_compris_T< FIELD_TYPE >::clear_champs_compris () inline
References Champs_compris_T< FIELD_TYPE >::liste_champs_.
Member Data Documentation
liste_champs_
template<typename FIELD_TYPE > std::unordered_map<std::string, TRUST_Ref< FIELD_TYPE *> > Champs_compris_T< FIELD_TYPE >::liste_champs_ protected
Referenced by Champs_compris_T< FIELD_TYPE >::clear_champs_compris(), Champs_compris_IJK::liste_noms_compris(), and Champs_compris_IJK::switch_ft_fields().