TrioCFD: Domaine_Cl_VDF Class Reference
Domaine_Cl_VDF Class Reference
#include <Domaine_Cl_VDF.h>
Public Member Functions
const Type_info * get_info () const override
const Cond_lim & la_cl_de_la_face (int numfa) const override
Public Member Functions inherited from Domaine_Cl_dis_base
virtual int calculer_coeffs_echange (double temps)
const Cond_lim_base & condition_limite_de_la_face_reelle (int face_globale, int &face_locale) const
const Cond_lim_base & condition_limite_de_la_face_virtuelle (int face_globale, int &face_locale) const
Cond_lim_base & condition_limite_de_la_frontiere (Nom frontiere)
const Cond_lim_base & condition_limite_de_la_frontiere (Nom frontiere) const
int contient_Cl (const Nom &)
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual const Cond_lim & la_cl_de_la_face (int num_face) const
const Nom & le_nom () const override
Conds_lim & les_conditions_limites ()
const Conds_lim & les_conditions_limites () const
Cond_lim & les_conditions_limites (int)
const Cond_lim & les_conditions_limites (int) const
virtual void mettre_a_jour (double temps)
virtual void mettre_a_jour_ss_pas_dt (double temps)
int nb_cond_lim () const
void nommer (const Nom &nom) override
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
See also
Domaine_Cl_dis_base
Constructor & Destructor Documentation
Domaine_Cl_VDF()
Domaine_Cl_VDF::Domaine_Cl_VDF ()
~Domaine_Cl_VDF()
Domaine_Cl_VDF::~Domaine_Cl_VDF ()
Member Function Documentation
cree_instance()
Objet_U * Domaine_Cl_VDF::cree_instance () static
taille_memoire()
unsigned Domaine_Cl_VDF::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Domaine_Cl_VDF::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Domaine_Cl_VDF::info () static
get_info()
const Type_info * Domaine_Cl_VDF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Domaine_Cl_dis_base.
self_cast() [1/2]
Domaine_Cl_VDF & Domaine_Cl_VDF::self_cast (Objet_U & r) static
self_cast() [2/2]
const Domaine_Cl_VDF & Domaine_Cl_VDF::self_cast (const Objet_U & r) static
printOn()
Sortie & Domaine_Cl_VDF::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Domaine_Cl_dis_base.
References Domaine_Cl_dis_base::printOn().
readOn()
Entree & Domaine_Cl_VDF::readOn (Entree & is) override protected virtual
Surcharge Objet_U::readOn(Sortie&) Lit les conditions aux limites discretisees a partir d'un flot d'entree.
Le format attendu est le suivant: { Nom Cond_lim [REPETER LECTURE AUTANT DE FOIS QUE NECESSAIRE] }
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Exceptions
accolade ouvrante attendue
nombre de conditions aux limites lues invalide
Reimplemented from Domaine_Cl_dis_base.
References Domaine_Cl_dis_base::readOn().
associer()
void Domaine_Cl_VDF::associer (const Domaine_dis_base & dom_dis) override virtual
Reimplemented from Domaine_Cl_dis_base.
References Domaine_VDF::nb_aretes_bord(), Domaine_VDF::nb_aretes_coin(), Domaine_VF::nb_faces_bord(), and TRUSTVect< _TYPE_, _SIZE_ >::resize().
Referenced by Convection_Diffusion_Temperature_FT_Disc::completer().
completer()
void Domaine_Cl_VDF::completer (const Domaine_dis_base & un_domaine_dis) override virtual
Implements Domaine_Cl_dis_base.
References Domaine_VF::creer_tableau_faces_bord(), Domaine_dis_base::domaine(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Process::exit(), TypeAreteBordVDF::FLUIDE_FLUIDE, TypeAreteCoinVDF::FLUIDE_FLUIDE, TypeAreteBordVDF::FLUIDE_NAVIER, TypeAreteCoinVDF::FLUIDE_NAVIER, TypeAreteCoinVDF::FLUIDE_PAROI, Frontiere_dis_base::frontiere(), Cond_lim_base::frontiere_dis(), Domaine_32_64< _SIZE_ >::ind_faces_virt_bord(), Process::Journal(), Domaine_Cl_dis_base::les_conditions_limites_, TypeAreteBordVDF::NAVIER_NAVIER, TypeAreteCoinVDF::NAVIER_NAVIER, Domaine_VDF::nb_aretes_bord(), Domaine_VDF::nb_aretes_coin(), Frontiere_32_64< _SIZE_ >::nb_faces(), Domaine_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), Frontiere_32_64< _SIZE_ >::num_premiere_face(), TypeAreteBordVDF::PAROI_FLUIDE, TypeAreteCoinVDF::PAROI_FLUIDE, TypeAreteBordVDF::PAROI_NAVIER, TypeAreteCoinVDF::PAROI_NAVIER, TypeAreteBordVDF::PAROI_PAROI, TypeAreteCoinVDF::PAROI_PAROI, TypeAreteCoinVDF::PERIO_FLUIDE, TypeAreteCoinVDF::PERIO_PAROI, TypeAreteBordVDF::PERIO_PERIO, TypeAreteCoinVDF::PERIO_PERIO, Domaine_VDF::premiere_arete_bord(), Domaine_VDF::premiere_arete_coin(), Domaine_VDF::Qdm(), TRUSTVect< _TYPE_, _SIZE_ >::size_reelle(), Option_VDF::traitement_coins, TypeAreteBordVDF::VIDE, and TypeAreteCoinVDF::VIDE.
imposer_cond_lim()
void Domaine_Cl_VDF::imposer_cond_lim (Champ_Inc_base & ch, double temps) override virtual
Impose les conditions aux limites a la valeur temporelle "temps" du Champ_Inc.
Implements Domaine_Cl_dis_base.
References Champ_Face_VDF::domaine_vdf(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Process::exit(), Periodique::face_associee(), Cond_lim_base::frontiere_dis(), Domaine_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Field_base::nature_du_champ(), Domaine_Cl_dis_base::nb_cond_lim(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), Domaine_VDF::orientation(), Objet_U::que_suis_je(), Dirichlet::val_imp_au_temps(), Champ_Inc_base::valeurs(), and Debog::verifier().
nb_faces_sortie_libre()
int Domaine_Cl_VDF::nb_faces_sortie_libre () const
References Domaine_Cl_dis_base::les_conditions_limites_, and Front_VF::nb_faces().
nb_faces_bord()
int Domaine_Cl_VDF::nb_faces_bord () const
References domaine_VDF(), and Domaine_VF::nb_faces_bord().
domaine_VDF() [1/2]
Domaine_VDF & Domaine_Cl_VDF::domaine_VDF ()
References Domaine_Cl_dis_base::domaine_dis().
Referenced by nb_faces_bord().
domaine_VDF() [2/2]
const Domaine_VDF & Domaine_Cl_VDF::domaine_VDF () const
References Domaine_Cl_dis_base::domaine_dis().
num_Cl_face()
int Domaine_Cl_VDF::num_Cl_face (int numfa) const inline
la_cl_de_la_face()
const Cond_lim & Domaine_Cl_VDF::la_cl_de_la_face (int num_face) const inline override virtual
A partir d'un indice de face de bord dans le Domaine_VF, renvoie la condition aux limites a laquelle cette face.
appartient, pour 0 <= num_face < nb_faces_Cl().
Reimplemented from Domaine_Cl_dis_base.
References Domaine_Cl_dis_base::les_conditions_limites_.
Referenced by Convection_Diffusion_Temperature_FT_Disc::get_flux_and_Twall(), Convection_Diffusion_Temperature_FT_Disc::get_flux_to_face(), and Triple_Line_Model_FT_Disc::get_theta_app().
type_arete_bord() [1/2]
int Domaine_Cl_VDF::type_arete_bord (int num_arete) const inline
Referenced by Op_Diff_VDF_Face_Axi_base::associer(), Op_Dift_VDF_Face_Axi_base::associer(), Modele_Jones_Launder_VDF::calcul_derivees_premieres_croisees(), Modele_Jones_Launder_VDF::calcul_derivees_secondes_croisees(), Champ_Face_VDF::calcul_duidxj(), Champ_Face_VDF::calcul_S_barre_sans_contrib_paroi(), Champ_Face_VDF::calculer_dercov_axi(), Modele_turbulence_hyd_LES_VDF::calculer_fonction_structure(), Modele_turbulence_hyd_LES_axi_VDF::calculer_fonction_structure(), and Domaine_VDF::modifier_pour_Cl().
type_arete_bord() [2/2]
const IntVect & Domaine_Cl_VDF::type_arete_bord () const inline
type_arete_coin() [1/2]
const int & Domaine_Cl_VDF::type_arete_coin (int num_arete) const inline
Referenced by Modele_Jones_Launder_VDF::calcul_derivees_premieres_croisees(), Modele_Jones_Launder_VDF::calcul_derivees_secondes_croisees(), Champ_Face_VDF::calcul_duidxj(), Champ_Face_VDF::calcul_S_barre_sans_contrib_paroi(), Modele_turbulence_hyd_LES_VDF::calculer_fonction_structure(), and Domaine_VDF::modifier_pour_Cl().
type_arete_coin() [2/2]
const IntVect & Domaine_Cl_VDF::type_arete_coin () const inline
Member Data Documentation
info_obj
const Type_info Domaine_Cl_VDF::info_obj static