TrioCFD: Neumann_paroi_rayo_semi_transp_VDF Class Reference
Neumann_paroi_rayo_semi_transp_VDF Class Reference
#include <Neumann_paroi_rayo_semi_transp_VDF.h>
Public Member Functions
double flux_impose (int i) const override
double flux_impose (int i, int j) const override
const Type_info * get_info () const override
Public Member Functions inherited from Cond_Lim_rayo_semi_transp
virtual void associer_modele (const Modele_rayo_semi_transp &)
Modele_rayo_semi_transp & modele ()
const Modele_rayo_semi_transp & modele () const
Public Member Functions inherited from Neumann_paroi
const Type_info * get_info () const override
void verifie_ch_init_nb_comp () const override
Public Member Functions inherited from Neumann
const DoubleTab & flux_impose (bool nb_faces_tot=false) const
virtual double flux_impose (int i) const
virtual double flux_impose (int i, int j) const
const Type_info * get_info () const override
Public Member Functions inherited from Cond_lim_base
virtual int a_mettre_a_jour_ss_pas_dt ()
virtual void associer_domaine_cl_dis_base (const Domaine_Cl_dis_base &)
virtual void associer_fr_dis_base (const Frontiere_dis_base &)
virtual void calculer_coeffs_echange (double temps)
virtual int compatible_avec_discr (const Discretisation_base &) const
Domaine_Cl_dis_base & domaine_Cl_dis ()
const Domaine_Cl_dis_base & domaine_Cl_dis () const
virtual Frontiere_dis_base & frontiere_dis ()
virtual const Frontiere_dis_base & frontiere_dis () const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
void set_modifier_val_imp (int)
virtual void verifie_ch_init_nb_comp () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Cond_lim_base
void err_pas_compatible (const Discretisation_base &) const
void err_pas_compatible (const Equation_base &) const
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
.SECTION
Constructor & Destructor Documentation
Neumann_paroi_rayo_semi_transp_VDF()
Neumann_paroi_rayo_semi_transp_VDF::Neumann_paroi_rayo_semi_transp_VDF ()
~Neumann_paroi_rayo_semi_transp_VDF()
Neumann_paroi_rayo_semi_transp_VDF::~Neumann_paroi_rayo_semi_transp_VDF ()
Member Function Documentation
cree_instance()
Objet_U * Neumann_paroi_rayo_semi_transp_VDF::cree_instance () static
taille_memoire()
unsigned Neumann_paroi_rayo_semi_transp_VDF::taille_memoire () const override virtual
Reimplemented from Neumann_paroi.
duplique()
int Neumann_paroi_rayo_semi_transp_VDF::duplique () const override virtual
Reimplemented from Neumann_paroi.
info()
const Type_info * Neumann_paroi_rayo_semi_transp_VDF::info () static
get_info()
const Type_info * Neumann_paroi_rayo_semi_transp_VDF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Neumann_paroi.
self_cast() [1/2]
Neumann_paroi_rayo_semi_transp_VDF & Neumann_paroi_rayo_semi_transp_VDF::self_cast (Objet_U & r) static
self_cast() [2/2]
const Neumann_paroi_rayo_semi_transp_VDF & Neumann_paroi_rayo_semi_transp_VDF::self_cast (const Objet_U & r) static
printOn()
Sortie & Neumann_paroi_rayo_semi_transp_VDF::printOn (Sortie & os) const override protected virtual
Parameters
(Sortie& os) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Neumann_paroi.
readOn()
Entree & Neumann_paroi_rayo_semi_transp_VDF::readOn (Entree & is) override protected virtual
Lecture des parametres de la condition Neumann_paroi Lecture de l'emissivite de la paroi.
Lecture du coefficient A
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Neumann_paroi.
References Cond_lim_base::le_champ_front.
compatible_avec_eqn()
int Neumann_paroi_rayo_semi_transp_VDF::compatible_avec_eqn (const Equation_base & eqn) const override virtual
Reimplemented from Cond_lim_base.
References Equation_base::domaine_application(), and Cond_lim_base::err_pas_compatible().
la_cl()
const Cond_lim_base & Neumann_paroi_rayo_semi_transp_VDF::la_cl () const override virtual
Implements Cond_Lim_rayo_semi_transp.
flux_impose() [1/2]
double Neumann_paroi_rayo_semi_transp_VDF::flux_impose (int i) const override virtual
Renvoie la valeur du flux impose sur la i-eme composante du champ representant le flux a la frontiere.
Parameters
(int i) indice suivant la premiere dimension du champ
Returns
(double) la valeur imposee sur la composante du champ specifiee
Exceptions
deuxieme dimension du champ de frontiere superieur a 1
Reimplemented from Neumann.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Cond_lim_base::domaine_Cl_dis(), Domaine_VF::face_voisins(), Modele_rayo_semi_transp::flux_radiatif(), Cond_lim_base::frontiere_dis(), Cond_lim_base::le_champ_front, Objet_U::le_nom(), Cond_Lim_rayo_semi_transp::modele(), Front_VF::num_premiere_face(), TRUSTVect< _TYPE_, _SIZE_ >::size(), and Champ_front_base::valeurs().
flux_impose() [2/2]
double Neumann_paroi_rayo_semi_transp_VDF::flux_impose (int i, int j) const override virtual
Renvoie la valeur du flux impose sur la (i,j)-eme composante du champ representant le flux a la frontiere.
Parameters
(int i) indice suivant la premiere dimension du champ
(int j) indice suivant la deuxieme dimension du champ
Returns
(double) la valeur imposee sur la composante du champ specifiee
Reimplemented from Neumann.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Cond_lim_base::domaine_Cl_dis(), Domaine_VF::face_voisins(), Modele_rayo_semi_transp::flux_radiatif(), Cond_lim_base::frontiere_dis(), Cond_lim_base::le_champ_front, Objet_U::le_nom(), Cond_Lim_rayo_semi_transp::modele(), Front_VF::num_premiere_face(), and Champ_front_base::valeurs().
temperature_bord() [1/2]
Champ_front_base & Neumann_paroi_rayo_semi_transp_VDF::temperature_bord () inline
References temperature_bord_.
Referenced by Flux_radiatif_VDF::calculer_flux_radiatif(), and Eq_rayo_semi_transp_VDF::evaluer_cl_rayonnement().
temperature_bord() [2/2]
const Champ_front_base & Neumann_paroi_rayo_semi_transp_VDF::temperature_bord () const inline
References temperature_bord_.
calculer_temperature_bord()
void Neumann_paroi_rayo_semi_transp_VDF::calculer_temperature_bord (double temps)
References Milieu_base::capacite_calorifique(), Milieu_base::conductivite(), Domaine_VDF::dist_norm_bord(), Cond_lim_base::domaine_Cl_dis(), Domaine_VF::face_voisins(), Modele_rayo_semi_transp::flux_radiatif(), Cond_lim_base::frontiere_dis(), TRUSTVect< _TYPE_, _SIZE_ >::get_md_vector(), Cond_lim_base::le_champ_front, Objet_U::le_nom(), Milieu_base::masse_volumique(), Cond_Lim_rayo_semi_transp::modele(), Cond_lim_base::mon_dom_cl_dis, Field_base::nb_comp(), Front_VF::nb_faces(), MD_Vector::non_nul(), Front_VF::num_premiere_face(), Schema_Temps_base::pas_de_temps(), temperature_bord_, TRUST_Deriv< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), Champ_front_base::valeurs(), Champ_Proto::valeurs(), and Champ_front_base::valeurs_au_temps().
Referenced by Eq_rayo_semi_transp_VDF::evaluer_cl_rayonnement().
completer()
void Neumann_paroi_rayo_semi_transp_VDF::completer () override virtual
NE FAIT RIEN A surcharger dans les classes derivees.
Reimplemented from Cond_lim_base.
References Cond_lim_base::completer(), Cond_lim_base::domaine_Cl_dis(), Domaine_VF::face_voisins(), Field_base::fixer_nb_comp(), Cond_lim_base::frontiere_dis(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), temperature_bord_, Objet_U_ptr::typer(), and Champ_front_base::valeurs().
Member Data Documentation
info_obj
const Type_info Neumann_paroi_rayo_semi_transp_VDF::info_obj static
temperature_bord_
TRUST_Deriv< Champ_front_base > Neumann_paroi_rayo_semi_transp_VDF::temperature_bord_ protected
Referenced by calculer_temperature_bord(), completer(), and temperature_bord().