TrioCFD: Perte_Charge_Reguliere_QC_VDF_Face Class Reference
Perte_Charge_Reguliere_QC_VDF_Face Class Reference
#include <Source_QC_VDF_Face.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Perte_Charge_Reguliere_VDF_Face
const Type_info * get_info () const override
Public Member Functions inherited from Perte_Charge_VDF_Face
const Type_info * get_info () const override
void mettre_a_jour (double temps) override
const Type_info * get_info () const override
Public Member Functions inherited from Source_base
virtual int a_pour_Champ_Fonc (const Motcle &mot, TRUST_Ref< Champ_base * > &ch_ref) const
virtual void associer_champ_rho (const Champ_base &champ_rho)
virtual void completer ()
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
virtual void resetTime (double t)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Perte_Charge_Reguliere
double a () const
double b () const
double calculer_Cf_blasius (double) const
double D () const
double d () const
Entree & lire_donnees (Entree &)
Public Member Functions inherited from Perte_Charge
int direction_perte_charge () const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Perte_Charge_Reguliere_VDF_Face
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Perte_Charge_VDF_Face
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Perte_Charge_Reguliere_QC_VDF_Face()
Perte_Charge_Reguliere_QC_VDF_Face::Perte_Charge_Reguliere_QC_VDF_Face ()
~Perte_Charge_Reguliere_QC_VDF_Face()
Perte_Charge_Reguliere_QC_VDF_Face::~Perte_Charge_Reguliere_QC_VDF_Face ()
Member Function Documentation
cree_instance()
Objet_U * Perte_Charge_Reguliere_QC_VDF_Face::cree_instance () static
taille_memoire()
unsigned Perte_Charge_Reguliere_QC_VDF_Face::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Perte_Charge_Reguliere_QC_VDF_Face::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Perte_Charge_Reguliere_QC_VDF_Face::info () static
get_info()
const Type_info * Perte_Charge_Reguliere_QC_VDF_Face::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Source_dep_inco_base.
self_cast() [1/2]
Perte_Charge_Reguliere_QC_VDF_Face & Perte_Charge_Reguliere_QC_VDF_Face::self_cast (Objet_U & r) static
self_cast() [2/2]
const Perte_Charge_Reguliere_QC_VDF_Face & Perte_Charge_Reguliere_QC_VDF_Face::self_cast (const Objet_U & r) static
printOn()
Sortie & Perte_Charge_Reguliere_QC_VDF_Face::printOn (Sortie & os) const override protected virtual
DOES NOTHING - to override in derived classes.
Imprime la source sur un flot de sortie.
Parameters
(Sortie& os) le flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Source_dep_inco_base.
References Perte_Charge_Reguliere_VDF_Face::printOn().
readOn()
Entree & Perte_Charge_Reguliere_QC_VDF_Face::readOn (Entree & is) override protected virtual
DOES NOTHING - to override in derived classes.
Lecture d'un terme source sur un flot d'entree.
Parameters
(Entree& is) le flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Source_dep_inco_base.
References Perte_Charge_Reguliere_VDF_Face::readOn().
ajouter_mere()
DoubleTab & Perte_Charge_Reguliere_QC_VDF_Face::ajouter_mere (DoubleTab & resu) const
References Perte_Charge_Reguliere_VDF_Face::ajouter_blocs().
dimensionner_blocs()
void Perte_Charge_Reguliere_QC_VDF_Face::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl) const inline override virtual
Reimplemented from Source_base.
ajouter_blocs()
void Perte_Charge_Reguliere_QC_VDF_Face::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl) const override virtual
Reimplemented from Source_base.
References Source_Fluide_Dilatable_Face< Perte_Charge_Reguliere_QC_VDF_Face >::ajouter_impl(), Source_Fluide_Dilatable_Face< Perte_Charge_Reguliere_QC_VDF_Face >::contribuer_a_avec_impl(), MorEqn::equation(), Nom::getString(), Equation_base::inconnue(), and Field_base::le_nom().
has_interface_blocs()
int Perte_Charge_Reguliere_QC_VDF_Face::has_interface_blocs () const inline override virtual
Reimplemented from Source_base.
Member Data Documentation
info_obj
const Type_info Perte_Charge_Reguliere_QC_VDF_Face::info_obj static