TrioCFD: Navier_Stokes_Aposteriori Class Reference
Navier_Stokes_Aposteriori Class Reference
#include <Navier_Stokes_Aposteriori.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Navier_Stokes_std
void abortTimeStep () override
void associer_milieu_base (const Milieu_base &) override
void associer_pb_base (const Probleme_base &) override
virtual void calculer_la_pression_en_pa ()
void completer () override
DoubleTab & derivee_en_temps_inco (DoubleTab &) override
const Motcle & domaine_application () const override
Fluide_base & fluide ()
const Fluide_base & fluide () const
const Type_info * get_info () const override
int impr (Sortie &os) const override
const Champ_Inc_base & inconnue () const override
Champ_Inc_base & inconnue () override
bool initTimeStep (double dt) override
Entree & lire_cond_init (Entree &) override
int lire_motcle_non_standard (const Motcle &, Entree &) override
void mettre_a_jour (double temps) override
const Milieu_base & milieu () const override
Milieu_base & milieu () override
int nombre_d_operateurs () const override
const Operateur & operateur (int) const override
Operateur & operateur (int) override
Operateur_Div & operateur_divergence ()
const Operateur_Div & operateur_divergence () const
Operateur_Grad & operateur_gradient ()
const Operateur_Grad & operateur_gradient () const
int preparer_calcul () override
virtual void projeter ()
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
SolveurSys & solveur_pression ()
int verif_Cl () const override
Public Member Functions inherited from Equation_base
virtual void abortTimeStep ()
virtual void associer_domaine_dis (const Domaine_dis_base &)
virtual void associer_pb_base (const Probleme_base &)
virtual void associer_sch_tps_base (const Schema_Temps_base &)
virtual double calculer_pas_de_temps () const
virtual void completer ()
virtual std::vector< YAML_data > data_a_sauvegarder () const
DoubleTab & derivee_en_temps_conv (DoubleTab &, const DoubleTab &)
virtual DoubleTab & derivee_en_temps_inco (DoubleTab &)
const Discretisation_base & discretisation () const
virtual void discretiser ()
virtual const Motcle & domaine_application () const
virtual Domaine_Cl_dis_base & domaine_Cl_dis ()
virtual const Domaine_Cl_dis_base & domaine_Cl_dis () const
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual void imprimer (Sortie &os) const
virtual bool initTimeStep (double dt)
const Nom & le_nom () const override
int limpr () const
virtual void mettre_a_jour (double temps)
virtual int preparer_calcul ()
Probleme_base & probleme ()
const Probleme_base & probleme () const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Schema_Temps_base & schema_temps ()
const Schema_Temps_base & schema_temps () const
Solveur_Masse_base & solv_masse ()
const Solveur_Masse_base & solv_masse () const
Sources & sources ()
const Sources & sources () const
virtual void valider_iteration ()
virtual void verifie_ch_init_nb_comp (const Champ_Inc_base &ch_ref, const int nb_comp) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Navier_Stokes_std
virtual void discretiser_assembleur_pression ()
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Equation_base
virtual Entree & lire_cl (Entree &)
virtual Entree & lire_cond_init (Entree &)
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual Entree & lire_sources (Entree &)
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
virtual int verif_Cl () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Navier_Stokes_Aposteriori()
Navier_Stokes_Aposteriori::Navier_Stokes_Aposteriori ()
~Navier_Stokes_Aposteriori()
Navier_Stokes_Aposteriori::~Navier_Stokes_Aposteriori ()
Member Function Documentation
cree_instance()
Objet_U * Navier_Stokes_Aposteriori::cree_instance () static
taille_memoire()
unsigned Navier_Stokes_Aposteriori::taille_memoire () const override virtual
Reimplemented from Navier_Stokes_std.
duplique()
int Navier_Stokes_Aposteriori::duplique () const override virtual
Reimplemented from Navier_Stokes_std.
info()
const Type_info * Navier_Stokes_Aposteriori::info () static
get_info()
const Type_info * Navier_Stokes_Aposteriori::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Navier_Stokes_std.
self_cast() [1/2]
Navier_Stokes_Aposteriori & Navier_Stokes_Aposteriori::self_cast (Objet_U & r) static
self_cast() [2/2]
const Navier_Stokes_Aposteriori & Navier_Stokes_Aposteriori::self_cast (const Objet_U & r) static
printOn()
Sortie & Navier_Stokes_Aposteriori::printOn (Sortie & os) const override protected virtual
Surcharge Objet_U::printOn Imprime l'equation et ses composants sur un flot de sortie.
Imprime le nom de l'equation, le solveur masse, les termes sources les conditions aux limites discretisees, les inconnues et les operateurs.
Parameters
(Sortie& os) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Navier_Stokes_std.
References Navier_Stokes_std::printOn().
readOn()
Entree & Navier_Stokes_Aposteriori::readOn (Entree & is) override protected virtual
Appel Equation_base::readOn(Entree& is) En sortie verifie que l'on a bien lu:
   - le terme diffusif,
   - le terme convectif,
   - le solveur en pression
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Exceptions
terme diffusif non specifie dans jeu de donnees, specifier un type negligeable pour l'operateur si il est a negliger
terme convectif non specifie dans jeu de donnees, specifier un type negligeable pour l'operateur si il est a negliger
solveur pression non defini dans jeu de donnees
Reimplemented from Navier_Stokes_std.
References Navier_Stokes_std::readOn().
discretiser()
void Navier_Stokes_Aposteriori::discretiser () override virtual
Dicretise l'equation.
Reimplemented from Navier_Stokes_std.
References Equation_base::discretisation(), Navier_Stokes_std::discretiser(), Process::exit(), and Objet_U::que_suis_je().
get_champ()
const Champ_base & Navier_Stokes_Aposteriori::get_champ (const Motcle & nom) const override virtual
Reimplemented from Navier_Stokes_std.
References Equation_base::champs_compris_, Champs_compris_T< FIELD_TYPE >::get_champ(), Navier_Stokes_std::get_champ(), Navier_Stokes_std::la_vitesse, Champ_Fonc_base::mettre_a_jour(), MorEqn::mon_equation_non_nul(), Equation_base::schema_temps(), Champ_base::temps(), Schema_Temps_base::temps_init(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by has_champ().
has_champ() [1/2]
bool Navier_Stokes_Aposteriori::has_champ (const Motcle & nom, TRUST_Ref< Champ_base * > & ref_champ) const override virtual
Reimplemented from Navier_Stokes_std.
References get_champ(), and Navier_Stokes_std::has_champ().
has_champ() [2/2]
bool Navier_Stokes_Aposteriori::has_champ (const Motcle & nom) const override virtual
Reimplemented from Navier_Stokes_std.
References Navier_Stokes_std::has_champ().
creer_champ()
void Navier_Stokes_Aposteriori::creer_champ (const Motcle & motlu) override virtual
Reimplemented from Navier_Stokes_std.
References Champs_compris_T< FIELD_TYPE >::ajoute_champ(), Equation_base::champs_compris_, Champ_Post_Operateur_Eqn::completer(), Navier_Stokes_std::creer_champ(), Probleme_U::le_nom(), Objet_U_ptr::non_nul(), and Equation_base::probleme().
get_noms_champs_postraitables()
void Navier_Stokes_Aposteriori::get_noms_champs_postraitables (Noms & nom, Option opt = NONE) const override virtual
Reimplemented from Navier_Stokes_std.
References TRUST_Vector< _CLASSE_ >::add(), Equation_base::champs_compris_, Navier_Stokes_std::get_noms_champs_postraitables(), and Champs_compris_T< FIELD_TYPE >::liste_noms_compris().
get_champ_source()
Champ_Post_Operateur_Eqn & Navier_Stokes_Aposteriori::get_champ_source () inline
Referenced by Estimateur_Aposteriori_P0_VEF::mettre_a_jour().
Member Data Documentation
info_obj
const Type_info Navier_Stokes_Aposteriori::info_obj static