TrioCFD: correction_one_direction Class Reference
correction_one_direction Class Reference
#include <corrections_qdm.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
< Correction : "vitesse_corrigee_ = vitesse - vitesse_correction_"
A partir de qdm_cible, calcule vitesse_correction_ et vitesse_corrigee_ pour une direction
         u_i * = u_i - {u_correction}_i
         correct_velocity_ = vel_ijk_t - value_correction_
                    value_correction_= ({rho u}_i _moyen - qdm_cible)  /  rho_moyen
qdm_cible : calculee par une des sous-classes.
‍
Member Enumeration Documentation
type_correction
enum correction_one_direction::type_correction
Enumerator
CIBLE_CONSTANTE
MOYENNE_PAR_MORCEAUX
MOYENNE_GLISSANTE
REGIME_ETABLI
CONSIGNE_INITIALE
Constructor & Destructor Documentation
~correction_one_direction()
correction_one_direction::~correction_one_direction ()
correction_one_direction()
correction_one_direction::correction_one_direction ()
Member Function Documentation
cree_instance()
Objet_U * correction_one_direction::cree_instance () static
taille_memoire()
unsigned correction_one_direction::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int correction_one_direction::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * correction_one_direction::info () static
get_info()
const Type_info * correction_one_direction::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
correction_one_direction & correction_one_direction::self_cast (Objet_U & r) static
self_cast() [2/2]
const correction_one_direction & correction_one_direction::self_cast (const Objet_U & r) static
printOn()
Sortie & correction_one_direction::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
References CIBLE_CONSTANTE, CONSIGNE_INITIALE, get_type_corr(), MOYENNE_GLISSANTE, MOYENNE_PAR_MORCEAUX, parametres_cible_constante_, parametres_consigne_initiale_, parametres_moyenne_glissante_, parametres_moyenne_par_morceaux_, and REGIME_ETABLI.
readOn()
Entree & correction_one_direction::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
References Param::ajouter(), CIBLE_CONSTANTE, CONSIGNE_INITIALE, Param::dictionnaire(), Param::lire_avec_accolades(), MOYENNE_GLISSANTE, MOYENNE_PAR_MORCEAUX, parametres_cible_constante_, parametres_consigne_initiale_, parametres_moyenne_glissante_, parametres_moyenne_par_morceaux_, Objet_U::que_suis_je(), REGIME_ETABLI, and type_corr_.
set_correction()
void correction_one_direction::set_correction (correction_one_direction & correction_in)
References get_cible_constante(), get_consigne_initiale(), get_moyenne_glissante(), get_moyenne_par_morceaux(), get_type_corr(), parametres_cible_constante_, parametres_consigne_initiale_, parametres_moyenne_glissante_, parametres_moyenne_par_morceaux_, and type_corr_.
Referenced by corrections_qdm::set_corrections().
get_type_corr()
correction_one_direction::type_correction correction_one_direction::get_type_corr () const
References type_corr_.
Referenced by compute_correction_value(), get_need_for_rho_liq(), get_need_for_vit_rel(), printOn(), set_correction(), set_rho_liq(), and set_time_for_correction().
get_value()
double correction_one_direction::get_value () inline
References value_correction_.
set_time_for_correction()
void correction_one_direction::set_time_for_correction (double time, double time_step, int time_iteration)
References CIBLE_CONSTANTE, CONSIGNE_INITIALE, get_type_corr(), MOYENNE_GLISSANTE, MOYENNE_PAR_MORCEAUX, parametres_cible_constante_, parametres_consigne_initiale_, parametres_moyenne_glissante_, parametres_moyenne_par_morceaux_, cible_donnee::set_time(), moyenne_par_morceaux::set_time(), moyenne_glissante::set_time(), and consigne_initiale::set_time().
Referenced by corrections_qdm::set_time().
set_rho_moyen_alpha_l_for_correction()
void correction_one_direction::set_rho_moyen_alpha_l_for_correction (double rho_moyen, double alpha_l)
References alpha_l_, and rho_moyen_.
Referenced by corrections_qdm::set_rho_moyen_alpha_l().
set_rho_vel_moyen_for_correction()
void correction_one_direction::set_rho_vel_moyen_for_correction (double rho_vel_moyen)
References rho_vel_moyen_.
Referenced by corrections_qdm::set_rho_vel_moyen().
set_mean_values_for_correction()
void correction_one_direction::set_mean_values_for_correction (double rho_vel_moyen, double rho_moyen, double alpha_l)
References alpha_l_, rho_moyen_, and rho_vel_moyen_.
Referenced by corrections_qdm::set_mean_values_for_corrections().
compute_correction_value()
void correction_one_direction::compute_correction_value ()
References alpha_l_, CIBLE_CONSTANTE, cible_donnee::compute_qdm_cible(), moyenne_par_morceaux::compute_qdm_cible(), moyenne_glissante::compute_qdm_cible(), consigne_initiale::compute_qdm_cible(), moyenne_glissante::compute_v_cible(), CONSIGNE_INITIALE, consigne_initiale::get_qdm_cible(), cible_donnee::get_qdm_cible(), moyenne_par_morceaux::get_qdm_cible(), moyenne_glissante::get_qdm_cible(), get_type_corr(), MOYENNE_GLISSANTE, MOYENNE_PAR_MORCEAUX, parametres_cible_constante_, parametres_consigne_initiale_, parametres_moyenne_glissante_, parametres_moyenne_par_morceaux_, qdm_cible_, rho_moyen_, rho_vel_moyen_, value_correction_, and vitesse_relative_.
Referenced by corrections_qdm::compute_correction_value_one_direction().
compute_correct_velocity()
void correction_one_direction::compute_correct_velocity (double vel_ijk_t)
References correct_velocity_, and value_correction_.
Referenced by corrections_qdm::compute_correct_velocity_one_direction().
get_correct_velocity()
double correction_one_direction::get_correct_velocity () inline
References correct_velocity_.
Referenced by corrections_qdm::get_correct_velocities(), and corrections_qdm::get_correct_velocitiy_one_direction().
get_velocity_correction()
double correction_one_direction::get_velocity_correction () inline
References value_correction_.
Referenced by corrections_qdm::get_velocity_corrections().
get_correction_value()
double correction_one_direction::get_correction_value () inline
References qdm_cible_.
Referenced by corrections_qdm::get_correction_values().
get_need_for_rho_liq()
int correction_one_direction::get_need_for_rho_liq ()
References CIBLE_CONSTANTE, CONSIGNE_INITIALE, consigne_initiale::get_need_for_rho_l(), cible_donnee::get_need_for_rho_l(), moyenne_par_morceaux::get_need_for_rho_l(), moyenne_glissante::get_need_for_rho_l(), get_type_corr(), MOYENNE_GLISSANTE, MOYENNE_PAR_MORCEAUX, parametres_cible_constante_, parametres_consigne_initiale_, parametres_moyenne_glissante_, and parametres_moyenne_par_morceaux_.
Referenced by corrections_qdm::set_rho_liquide().
get_need_for_vit_rel()
int correction_one_direction::get_need_for_vit_rel ()
References CIBLE_CONSTANTE, CONSIGNE_INITIALE, consigne_initiale::get_need_for_vl_vv(), cible_donnee::get_need_for_vl_vv(), moyenne_par_morceaux::get_need_for_vl_vv(), moyenne_glissante::get_need_for_vl_vv(), get_type_corr(), MOYENNE_GLISSANTE, MOYENNE_PAR_MORCEAUX, parametres_cible_constante_, parametres_consigne_initiale_, parametres_moyenne_glissante_, and parametres_moyenne_par_morceaux_.
Referenced by corrections_qdm::get_need_for_vitesse_relative(), and corrections_qdm::set_vitesse_relative().
get_need_to_compute_correction_value()
int correction_one_direction::get_need_to_compute_correction_value ()
Referenced by corrections_qdm::get_need_to_compute_correction_value_one_direction().
set_rho_liq()
void correction_one_direction::set_rho_liq (double rho_liquide)
References CIBLE_CONSTANTE, CONSIGNE_INITIALE, get_type_corr(), MOYENNE_GLISSANTE, MOYENNE_PAR_MORCEAUX, parametres_cible_constante_, parametres_moyenne_glissante_, parametres_moyenne_par_morceaux_, cible_donnee::set_rho_l(), moyenne_par_morceaux::set_rho_l(), and moyenne_glissante::set_rho_l().
Referenced by corrections_qdm::set_rho_liquide().
set_vl_vv()
void correction_one_direction::set_vl_vv (double vl_vv)
References vitesse_relative_.
Referenced by corrections_qdm::set_vitesse_relative().
get_cible_constante()
cible_donnee correction_one_direction::get_cible_constante () const
References parametres_cible_constante_.
Referenced by set_correction().
get_moyenne_par_morceaux()
moyenne_par_morceaux correction_one_direction::get_moyenne_par_morceaux () const
References parametres_moyenne_par_morceaux_.
Referenced by set_correction().
get_moyenne_glissante()
moyenne_glissante correction_one_direction::get_moyenne_glissante () const
References parametres_moyenne_glissante_.
Referenced by set_correction().
get_consigne_initiale()
consigne_initiale correction_one_direction::get_consigne_initiale () const
References parametres_consigne_initiale_.
Referenced by set_correction().
Member Data Documentation
info_obj
const Type_info correction_one_direction::info_obj static
value_correction_
double correction_one_direction::value_correction_ protected
Referenced by compute_correct_velocity(), compute_correction_value(), get_value(), and get_velocity_correction().
correct_velocity_
double correction_one_direction::correct_velocity_ protected
Referenced by compute_correct_velocity(), and get_correct_velocity().
type_corr_
int correction_one_direction::type_corr_ protected
Referenced by get_type_corr(), readOn(), and set_correction().
i_need_vitesse_relative_
int correction_one_direction::i_need_vitesse_relative_ protected
rho_vel_moyen_
double correction_one_direction::rho_vel_moyen_ protected
Referenced by compute_correction_value(), set_mean_values_for_correction(), and set_rho_vel_moyen_for_correction().
rho_moyen_
double correction_one_direction::rho_moyen_ protected
Referenced by compute_correction_value(), set_mean_values_for_correction(), and set_rho_moyen_alpha_l_for_correction().
alpha_l_
double correction_one_direction::alpha_l_ protected
Referenced by compute_correction_value(), set_mean_values_for_correction(), and set_rho_moyen_alpha_l_for_correction().
vitesse_relative_
double correction_one_direction::vitesse_relative_ protected
Referenced by compute_correction_value(), and set_vl_vv().
qdm_cible_
double correction_one_direction::qdm_cible_ protected
Referenced by compute_correction_value(), and get_correction_value().
parametres_cible_constante_
cible_donnee correction_one_direction::parametres_cible_constante_ protected
Referenced by compute_correction_value(), get_cible_constante(), get_need_for_rho_liq(), get_need_for_vit_rel(), printOn(), readOn(), set_correction(), set_rho_liq(), and set_time_for_correction().
parametres_moyenne_par_morceaux_
moyenne_par_morceaux correction_one_direction::parametres_moyenne_par_morceaux_ protected
Referenced by compute_correction_value(), get_moyenne_par_morceaux(), get_need_for_rho_liq(), get_need_for_vit_rel(), printOn(), readOn(), set_correction(), set_rho_liq(), and set_time_for_correction().
parametres_moyenne_glissante_
moyenne_glissante correction_one_direction::parametres_moyenne_glissante_ protected
Referenced by compute_correction_value(), get_moyenne_glissante(), get_need_for_rho_liq(), get_need_for_vit_rel(), printOn(), readOn(), set_correction(), set_rho_liq(), and set_time_for_correction().
parametres_consigne_initiale_
consigne_initiale correction_one_direction::parametres_consigne_initiale_ protected
Referenced by compute_correction_value(), get_consigne_initiale(), get_need_for_rho_liq(), get_need_for_vit_rel(), printOn(), readOn(), set_correction(), and set_time_for_correction().