TrioCFD: Cut_cell_data Class Reference
Cut_cell_data Class Reference
#include <TRUSTTabFT_cut_cell.h>
Member Function Documentation
associer_persistant()
void Cut_cell_data::associer_persistant (Cut_cell_FT_Disc & cut_cell_disc, int dimension)
References TRUSTTabFT_cut_cell< _TYPE_ >::associer_persistant(), cut_cell_disc_, diph_l_, and diph_v_.
Referenced by Cut_cell_double::associer_persistant().
associer_ephemere()
void Cut_cell_data::associer_ephemere (Cut_cell_FT_Disc & cut_cell_disc, int dimension)
References TRUSTTabFT_cut_cell< _TYPE_ >::associer_ephemere(), cut_cell_disc_, diph_l_, and diph_v_.
Referenced by Cut_cell_double::associer_ephemere().
associer_paresseux()
void Cut_cell_data::associer_paresseux (Cut_cell_FT_Disc & cut_cell_disc, int dimension)
References TRUSTTabFT_cut_cell< _TYPE_ >::associer_paresseux(), cut_cell_disc_, diph_l_, and diph_v_.
Referenced by Cut_cell_double::associer_paresseux().
get_cut_cell_disc()
const Cut_cell_FT_Disc & Cut_cell_data::get_cut_cell_disc () const inline
References cut_cell_disc_, and TRUST_Ref< _CLASSE_ >::valeur().
echange_espace_virtuel() [1/2]
void Cut_cell_data::echange_espace_virtuel ()
References diph_l_, diph_v_, and TRUSTTabFT_cut_cell< _TYPE_ >::echange_espace_virtuel().
echange_espace_virtuel() [2/2]
void Cut_cell_data::echange_espace_virtuel (MD_Vector_tools::Operations_echange op)
References diph_l_, diph_v_, and TRUSTTabFT_cut_cell< _TYPE_ >::echange_espace_virtuel().
Member Data Documentation
diph_l_
DoubleTabFT_cut_cell Cut_cell_data::diph_l_
Referenced by associer_ephemere(), associer_paresseux(), associer_persistant(), echange_espace_virtuel(), and Cut_cell_double::verify_consistency_within_layer().
diph_v_
DoubleTabFT_cut_cell Cut_cell_data::diph_v_
Referenced by associer_ephemere(), associer_paresseux(), associer_persistant(), echange_espace_virtuel(), and Cut_cell_double::verify_consistency_within_layer().
cut_cell_disc_
TRUST_Ref< Cut_cell_FT_Disc *> Cut_cell_data::cut_cell_disc_ protected
Referenced by associer_ephemere(), associer_paresseux(), associer_persistant(), get_cut_cell_disc(), and Cut_cell_double::verify_consistency_within_layer().