TrioCFD: OpConvCentre4IJK_double Class Reference
OpConvCentre4IJK_double Class Reference
#include <OpConvCentre4IJK.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Operateur_IJK_faces_conv_base_double
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Operateur_IJK_faces_conv_base_double
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
OpConvCentre4IJK_double()
OpConvCentre4IJK_double::OpConvCentre4IJK_double ()
References div_rho_u_, and last_computed_klayer_for_div_rhou_.
~OpConvCentre4IJK_double()
OpConvCentre4IJK_double::~OpConvCentre4IJK_double ()
Member Function Documentation
cree_instance()
Objet_U * OpConvCentre4IJK_double::cree_instance () static
taille_memoire()
unsigned OpConvCentre4IJK_double::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int OpConvCentre4IJK_double::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * OpConvCentre4IJK_double::info () static
get_info()
const Type_info * OpConvCentre4IJK_double::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
OpConvCentre4IJK_double & OpConvCentre4IJK_double::self_cast (Objet_U & r) static
self_cast() [2/2]
const OpConvCentre4IJK_double & OpConvCentre4IJK_double::self_cast (const Objet_U & r) static
printOn()
Sortie & OpConvCentre4IJK_double::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
readOn()
Entree & OpConvCentre4IJK_double::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
set_bc()
void OpConvCentre4IJK_double::set_bc (const Boundary_Conditions & bc) inline override virtual
Reimplemented from Operateur_IJK_faces_conv_base_double.
References ref_bc_.
Referenced by DNS_QC_double::run().
set_bc_thermique()
void OpConvCentre4IJK_double::set_bc_thermique (const Boundary_Conditions_Thermique & bc_th) inline override virtual
Reimplemented from Operateur_IJK_faces_conv_base_double.
References ref_bc_Thermique_.
initialize()
void OpConvCentre4IJK_double::initialize (const Domaine_IJK & splitting) override virtual
Reimplemented from Operateur_IJK_faces_conv_base_double.
References Operateur_IJK_faces_conv_base_double::channel_data_, fill_g_compo(), Operateur_IJK_data_channel::first_global_k_layer_flux(), g_compo_xy_dir_z_, g_compo_z_dir_z_, Operateur_IJK_data_channel::get_delta_z(), Domaine_IJK::get_nb_faces_local(), Operateur_IJK_faces_conv_base_double::initialize(), Operateur_IJK_data_channel::is_k_periodic(), Operateur_IJK_data_channel::last_global_k_layer_flux(), and Operateur_IJK_data_channel::offset_to_global_k_layer().
Referenced by DNS_QC_double::run().
calculer()
void OpConvCentre4IJK_double::calculer (const IJK_Field_double & inputx, const IJK_Field_double & inputy, const IJK_Field_double & inputz, const IJK_Field_double & vx, const IJK_Field_double & vy, const IJK_Field_double & vz, IJK_Field_double & dvx, IJK_Field_double & dvy, IJK_Field_double & dvz)
References Operateur_IJK_faces_conv_base_double::calculer(), and div_rho_u_.
Referenced by DNS_QC_double::rk3_sub_step().
ajouter()
void OpConvCentre4IJK_double::ajouter (const IJK_Field_double & inputx, const IJK_Field_double & inputy, const IJK_Field_double & inputz, const IJK_Field_double & vx, const IJK_Field_double & vy, const IJK_Field_double & vz, IJK_Field_double & dvx, IJK_Field_double & dvy, IJK_Field_double & dvz)
References Operateur_IJK_faces_conv_base_double::ajouter(), and div_rho_u_.
calculer_avec_u_div_rhou()
void OpConvCentre4IJK_double::calculer_avec_u_div_rhou (const IJK_Field_double & rhovx, const IJK_Field_double & rhovy, const IJK_Field_double & rhovz, const IJK_Field_double & vx, const IJK_Field_double & vy, const IJK_Field_double & vz, IJK_Field_double & dvx, IJK_Field_double & dvy, IJK_Field_double & dvz, IJK_Field_double & div_rho_u) override virtual
Reimplemented from Operateur_IJK_faces_conv_base_double.
References Statistiques::begin_count(), Operateur_IJK_faces_conv_base_double::channel_data_, Operateur_IJK_faces_base_double::compute_set(), div_rho_u_, Statistiques::end_count(), Operateur_IJK_faces_conv_base_double::inputx_, Operateur_IJK_faces_conv_base_double::inputy_, Operateur_IJK_faces_conv_base_double::inputz_, last_computed_klayer_for_div_rhou_, Operateur_IJK_faces_conv_base_double::vx_, Operateur_IJK_faces_conv_base_double::vy_, and Operateur_IJK_faces_conv_base_double::vz_.
ajouter_avec_u_div_rhou()
void OpConvCentre4IJK_double::ajouter_avec_u_div_rhou (const IJK_Field_double & rhovx, const IJK_Field_double & rhovy, const IJK_Field_double & rhovz, const IJK_Field_double & vx, const IJK_Field_double & vy, const IJK_Field_double & vz, IJK_Field_double & dvx, IJK_Field_double & dvy, IJK_Field_double & dvz, IJK_Field_double & div_rho_u) override virtual
Reimplemented from Operateur_IJK_faces_conv_base_double.
References Statistiques::begin_count(), Operateur_IJK_faces_conv_base_double::channel_data_, Operateur_IJK_faces_base_double::compute_add(), div_rho_u_, Statistiques::end_count(), Operateur_IJK_faces_conv_base_double::inputx_, Operateur_IJK_faces_conv_base_double::inputy_, Operateur_IJK_faces_conv_base_double::inputz_, last_computed_klayer_for_div_rhou_, Operateur_IJK_faces_conv_base_double::vx_, Operateur_IJK_faces_conv_base_double::vy_, and Operateur_IJK_faces_conv_base_double::vz_.
Referenced by DNS_QC_double::calculer_convection_vitesse().
compute_flux_x_vx()
void OpConvCentre4IJK_double::compute_flux_x_vx (IJK_Field_local_double & resu, const int k_layer) inline override protected virtual
Implements Operateur_IJK_faces_base_double.
compute_flux_x_vy()
void OpConvCentre4IJK_double::compute_flux_x_vy (IJK_Field_local_double & resu, const int k_layer) inline override protected virtual
Implements Operateur_IJK_faces_base_double.
compute_flux_x_vz()
void OpConvCentre4IJK_double::compute_flux_x_vz (IJK_Field_local_double & resu, const int k_layer) inline override protected virtual
Implements Operateur_IJK_faces_base_double.
compute_flux_y_vx()
void OpConvCentre4IJK_double::compute_flux_y_vx (IJK_Field_local_double & resu, const int k_layer) inline override protected virtual
Implements Operateur_IJK_faces_base_double.
compute_flux_y_vy()
void OpConvCentre4IJK_double::compute_flux_y_vy (IJK_Field_local_double & resu, const int k_layer) inline override protected virtual
Implements Operateur_IJK_faces_base_double.
compute_flux_y_vz()
void OpConvCentre4IJK_double::compute_flux_y_vz (IJK_Field_local_double & resu, const int k_layer) inline override protected virtual
Implements Operateur_IJK_faces_base_double.
compute_flux_z_vx()
void OpConvCentre4IJK_double::compute_flux_z_vx (IJK_Field_local_double & resu, const int k_layer) inline override protected virtual
Implements Operateur_IJK_faces_base_double.
compute_flux_z_vy()
void OpConvCentre4IJK_double::compute_flux_z_vy (IJK_Field_local_double & resu, const int k_layer) inline override protected virtual
Implements Operateur_IJK_faces_base_double.
compute_flux_z_vz()
void OpConvCentre4IJK_double::compute_flux_z_vz (IJK_Field_local_double & resu, const int k_layer) inline override protected virtual
Implements Operateur_IJK_faces_base_double.
exec_after_divergence_flux_x()
void OpConvCentre4IJK_double::exec_after_divergence_flux_x (IJK_Field_double & resu, const int k_layer) inline override protected virtual
Reimplemented from Operateur_IJK_faces_base_double.
exec_after_divergence_flux_y()
void OpConvCentre4IJK_double::exec_after_divergence_flux_y (IJK_Field_double & resu, const int k_layer) inline override protected virtual
Reimplemented from Operateur_IJK_faces_base_double.
exec_after_divergence_flux_z()
void OpConvCentre4IJK_double::exec_after_divergence_flux_z (IJK_Field_double & resu, const int k_layer) inline override protected virtual
Reimplemented from Operateur_IJK_faces_base_double.
get_g()
double OpConvCentre4IJK_double::get_g (int k_layer, int compo, int dir, int g_index) const inline protected
References Process::exit(), g_compo_xy_dir_z_, and g_compo_z_dir_z_.
calcul_g()
void OpConvCentre4IJK_double::calcul_g (const double & dxam, const double & dx, const double & dxav, double & g1, double & g2, double & g3, double & g4) protected
Referenced by fill_g_compo().
fill_g_compo()
void OpConvCentre4IJK_double::fill_g_compo (DoubleTab & g, int nb_values, int offset, int istart, int iend, const ArrOfDouble_with_ghost & delta_z, bool is_z_component, bool is_z_periodic) protected
References calcul_g(), and TRUSTTab< _TYPE_, _SIZE_ >::resize().
Referenced by initialize().
Member Data Documentation
info_obj
const Type_info OpConvCentre4IJK_double::info_obj static
g_compo_xy_dir_z_
DoubleTab OpConvCentre4IJK_double::g_compo_xy_dir_z_ protected
Referenced by get_g(), and initialize().
g_compo_z_dir_z_
DoubleTab OpConvCentre4IJK_double::g_compo_z_dir_z_ protected
Referenced by get_g(), and initialize().
div_rho_u_
IJK_Field_double* OpConvCentre4IJK_double::div_rho_u_ protected
Referenced by ajouter(), ajouter_avec_u_div_rhou(), calculer(), calculer_avec_u_div_rhou(), and OpConvCentre4IJK_double().
last_computed_klayer_for_div_rhou_
int OpConvCentre4IJK_double::last_computed_klayer_for_div_rhou_ protected
Referenced by ajouter_avec_u_div_rhou(), calculer_avec_u_div_rhou(), and OpConvCentre4IJK_double().
ref_bc_
TRUST_Ref< Boundary_Conditions *> OpConvCentre4IJK_double::ref_bc_ protected
Referenced by set_bc().
ref_bc_Thermique_
TRUST_Ref< Boundary_Conditions_Thermique *> OpConvCentre4IJK_double::ref_bc_Thermique_ protected
Referenced by set_bc_thermique().