TrioCFD: Op_Conv_ALE_VEF Class Reference
Op_Conv_ALE_VEF Class Reference
#include <Op_Conv_ALE_VEF.h>
Public Member Functions
double calculer_dt_stab () const override
void completer () override
void dimensionner (Matrice_Morse &) const override
const Type_info * get_info () const override
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Operateur_base
void associer_eqn (const Equation_base &)
virtual double calculer_dt_stab () const
virtual void completer ()
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual void mettre_a_jour (double temps)
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Op_VEF_Face
void dimensionner (const Domaine_VEF &, const Domaine_Cl_VEF &, Matrice_Morse &) const
void modifier_matrice_pour_periodique_apres_contribuer (Matrice_Morse &matrice, const Equation_base &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Op_Conv_ALE_VEF()
Op_Conv_ALE_VEF::Op_Conv_ALE_VEF ()
~Op_Conv_ALE_VEF()
Op_Conv_ALE_VEF::~Op_Conv_ALE_VEF ()
Member Function Documentation
cree_instance()
Objet_U * Op_Conv_ALE_VEF::cree_instance () static
taille_memoire()
unsigned Op_Conv_ALE_VEF::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Op_Conv_ALE_VEF::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Op_Conv_ALE_VEF::info () static
get_info()
const Type_info * Op_Conv_ALE_VEF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Op_Conv_ALE.
self_cast() [1/2]
Op_Conv_ALE_VEF & Op_Conv_ALE_VEF::self_cast (Objet_U & r) static
self_cast() [2/2]
const Op_Conv_ALE_VEF & Op_Conv_ALE_VEF::self_cast (const Objet_U & r) static
printOn()
Sortie & Op_Conv_ALE_VEF::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN A surcharger dans les classes derivees.
Parameters
(Sortie& os) un flot de sortie
Returns
(Sortie&) le flot de sortie
Reimplemented from Op_Conv_ALE.
readOn()
Entree & Op_Conv_ALE_VEF::readOn (Entree & is) override protected virtual
NE FAIT RIEN A surcharger dans les classes derivees.
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree
Reimplemented from Op_Conv_ALE.
References MorEqn::associer_eqn(), Operateur_Conv::associer_vitesse(), MorEqn::equation(), Op_Conv_ALE::la_vitesse, Operateur::lire(), Op_Conv_ALE::op_conv, and TRUST_Ref< _CLASSE_ >::valeur().
associer()
void Op_Conv_ALE_VEF::associer (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_cl_dis, const Champ_Inc_base & inco) override virtual
Reimplemented from Op_Conv_ALE.
References Op_Conv_ALE::dom, Champ_Inc_base::domaine(), la_zcl_vef, and le_dom_vef.
calculer_dt_stab()
double Op_Conv_ALE_VEF::calculer_dt_stab () const override virtual
Calcul dt_stab.
Returns
(double) renvoie toujours 1.e30
Reimplemented from Operateur_base.
References Operateur_Conv_base::fixer_dt_stab_conv(), la_zcl_vef, le_dom_vef, Domaine_Cl_dis_base::les_conditions_limites(), Process::mp_min(), Domaine_VF::nb_faces(), Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), Domaine_VF::premiere_face_int(), Domaine_VEF::premiere_face_std(), remplir_fluent_ALEincluded(), TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), Domaine_VF::volumes_entrelaces(), and Domaine_Cl_VEF::volumes_entrelaces_Cl().
remplir_fluent_ALEincluded()
void Op_Conv_ALE_VEF::remplir_fluent_ALEincluded (DoubleVect & tab_fluent) const virtual
References Objet_U::dimension, Op_Conv_ALE::dom, MorEqn::equation(), Domaine_VF::face_normales(), Equation_base::inconnue(), le_dom_vef, TRUSTVect< _TYPE_, _SIZE_ >::mp_norme_vect(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Domaine_VF::nb_faces(), TRUST_Ref< _CLASSE_ >::valeur(), and Champ_Inc_base::valeurs().
Referenced by calculer_dt_stab().
calculateALEMeshVelocityGradientOnFaces()
void Op_Conv_ALE_VEF::calculateALEMeshVelocityGradientOnFaces (DoubleTab & ALE_Mesh_Velocity_Gradient) const virtual
References Objet_U::dimension, Op_Conv_ALE::dom, MorEqn::equation(), Periodique::face_associee(), Domaine_VF::face_voisins(), la_zcl_vef, le_dom_vef, Equation_base::le_nom(), Domaine_Cl_dis_base::les_conditions_limites(), Domaine_dis_base::nb_elem_tot(), Domaine_VF::nb_faces(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), Domaine_VF::premiere_face_int(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUST_Vector< _CLASSE_ >::size(), TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), and Domaine_VF::volumes().
Referenced by calculateALEjacobian().
calculateALEjacobian()
void Op_Conv_ALE_VEF::calculateALEjacobian (DoubleTab & jacobianALE) const virtual
References calculateALEMeshVelocityGradientOnFaces(), Objet_U::dimension, MorEqn::equation(), Equation_base::inconnue(), le_dom_vef, Domaine_VF::nb_faces_tot(), Schema_Temps_base::pas_de_temps(), Equation_base::probleme(), Probleme_base::schema_temps(), TRUST_Ref< _CLASSE_ >::valeur(), and Champ_Inc_base::valeurs().
Referenced by Implicite_ALE::first_special_treatment(), and Navier_Stokes_std_ALE::renewing_jacobians().
application_LIMITEUR()
double Op_Conv_ALE_VEF::application_LIMITEUR (double grad1, double grad2, Motcle & type_limit) const
References Process::exit().
Referenced by ajouterALE().
ajouterALE()
DoubleTab & Op_Conv_ALE_VEF::ajouterALE (const DoubleTab & transporte, DoubleTab & resu) const override virtual
Implements Op_Conv_ALE.
References application_LIMITEUR(), Champ_P1NC::calcul_gradient(), Elem_VEF_base::calcul_vc(), Elem_VEF_base::calcul_xg(), Domaine_VF::creer_tableau_faces(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Op_Conv_ALE::dom, Domaine_dis_base::domaine(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_VF::elem_faces(), MorEqn::equation(), est_une_face_de_dirichlet_, Periodique::face_associee(), Domaine_VF::face_normales(), Domaine_VF::face_sommets(), Domaine_VF::face_voisins(), Domaine_VEF::facette_normales(), Operateur_base::flux_bords_, Cond_lim_base::frontiere_dis(), Op_Conv_VEF_Face::get_alpha(), Op_Conv_VEF_Face::get_ordre(), Op_Conv_VEF_Face::get_type_lim(), Equation_base::inconnue(), Elem_VEF_base::KEL(), la_zcl_vef, le_dom_vef, Domaine_Cl_dis_base::les_conditions_limites(), Equation_base::milieu(), Op_VEF_Face::modifier_flux(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Domaine_dis_base::nb_elem_tot(), Domaine_VF::nb_faces(), Front_VF::nb_faces(), Domaine_VF::nb_faces_bord(), Domaine_VF::nb_faces_tot(), Front_VF::nb_faces_tot(), Elem_VEF_base::nb_facette(), Domaine_dis_base::nb_front_Cl(), Domaine_dis_base::nb_som_tot(), Domaine_Cl_VEF::normales_facettes_Cl(), Front_VF::num_face(), Front_VF::num_premiere_face(), Op_Conv_ALE::op_conv, Op_Conv_VEF_base::phi_u_transportant(), Milieu_base::porosite_elem(), Milieu_base::porosite_face(), Domaine_VF::premiere_face_int(), Objet_U::que_suis_je(), Domaine_VEF::rang_elem_non_std(), TRUSTTab< _TYPE_, _SIZE_ >::ref(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), traitement_pres_bord_, Operateur::type(), Domaine_VEF::type_elem(), Domaine_Cl_VEF::type_elem_Cl(), Neumann_sortie_libre::val_ext(), TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_Inc_base::valeurs(), Domaine_Cl_VEF::vecteur_face_facette_Cl(), Domaine_ALE::vitesse(), Domaine_ALE::vitesse_faces(), and Domaine_VF::xv().
contribuer_a_avec()
void Op_Conv_ALE_VEF::contribuer_a_avec (const DoubleTab & inco, Matrice_Morse & matrice) const override virtual
On assemble la matrice des inconnues implicite.
Reimplemented from Operateur_base.
References Op_Conv_VEF_Face::ajouter_contribution(), Op_Conv_ALE::op_conv, and TRUST_Deriv< _CLASSE_ >::valeur().
modifier_pour_Cl()
void Op_Conv_ALE_VEF::modifier_pour_Cl (Matrice_Morse & matrice, DoubleTab & secmem) const override virtual
On modifie le second membre et la matrice dans le cas des conditions de dirichlet.
Reimplemented from Operateur_base.
References Op_Conv_VEF_Face::modifier_pour_Cl(), Op_Conv_ALE::op_conv, and TRUST_Deriv< _CLASSE_ >::valeur().
dimensionner()
void Op_Conv_ALE_VEF::dimensionner (Matrice_Morse & mat) const inline override virtual
DOES NOTHING - to override in derived classes.
Parameters
(Matrice_Morse&) une matrice au format Morse
Exceptions
methode a surcharger
Reimplemented from Operateur_base.
References Op_VEF_Face::dimensionner(), la_zcl_vef, le_dom_vef, and TRUST_Ref< _CLASSE_ >::valeur().
completer()
void Op_Conv_ALE_VEF::completer () override virtual
Associe l'operateur au domaine_dis, le domaine_Cl_dis, et a l'inconnue de son equation.
Exceptions
pas d'equation associee
Reimplemented from Operateur_base.
References Operateur::completer(), Operateur_base::completer(), and Op_Conv_ALE::op_conv.
Member Data Documentation
info_obj
const Type_info Op_Conv_ALE_VEF::info_obj static
le_dom_vef
TRUST_Ref< Domaine_VEF *> Op_Conv_ALE_VEF::le_dom_vef protected
Referenced by ajouterALE(), associer(), calculateALEjacobian(), calculateALEMeshVelocityGradientOnFaces(), calculer_dt_stab(), dimensionner(), and remplir_fluent_ALEincluded().
la_zcl_vef
TRUST_Ref< Domaine_Cl_VEF *> Op_Conv_ALE_VEF::la_zcl_vef protected
Referenced by ajouterALE(), associer(), calculateALEMeshVelocityGradientOnFaces(), calculer_dt_stab(), and dimensionner().
traitement_pres_bord_
ArrOfInt Op_Conv_ALE_VEF::traitement_pres_bord_ mutable protected
Referenced by ajouterALE().
est_une_face_de_dirichlet_
ArrOfInt Op_Conv_ALE_VEF::est_une_face_de_dirichlet_ mutable protected
Referenced by ajouterALE().