TrioCFD: Convection_Diffusion_Turbulent Class Reference
Convection_Diffusion_Turbulent Class Reference
#include <Convection_Diffusion_Turbulent.h>
Public Member Functions
virtual void mettre_a_jour (double)
int preparer_calcul ()
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Detailed Description
grandeurs scalaires (la temperature, une concentration ou plusieurs
concentrations) par un fluide verifiant la condition
d'incompressibilite div U = 0, avec modelisation de la turbulence.
Ce n'est pas (a elle seule) une classe de la hierarchie des equations
de TrioU, mais elle porte un modele de turbulence.
See also
Convection_Diffusion_std Mod_turb_scal, Convection_Diffusion_Temperature_Turbulent, Convection_Diffusion_Concentration_Turbulent, Cette est definie hors hierarchie Objet_U et Equation_base, ceci permet la definition des equations de convection-diffusion, turbulentes par heritage multiple, voir par exemple, Convection_Diffusion_Temperature_Turbulent.
Constructor & Destructor Documentation
~Convection_Diffusion_Turbulent()
virtual Convection_Diffusion_Turbulent::~Convection_Diffusion_Turbulent () inline virtual
Member Function Documentation
lire_modele()
Entree & Convection_Diffusion_Turbulent::lire_modele (Entree & is, const Equation_base & eqn)
References Modele_turbulence_scal_base::associer(), Modele_turbulence_scal_base::associer_eqn(), Equation_base::discretisation(), Modele_turbulence_scal_base::discretiser(), Equation_base::domaine_Cl_dis(), Equation_base::domaine_dis(), le_modele_turbulence, Objet_U::que_suis_je(), Objet_U_ptr::typer(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by Convection_Diffusion_Temperature_IBM_Turbulent::lire_motcle_non_standard(), Convection_Diffusion_Chaleur_Turbulent_QC::lire_motcle_non_standard(), Convection_Diffusion_Concentration_Turbulent::lire_motcle_non_standard(), Convection_Diffusion_Espece_Binaire_Turbulent_QC::lire_motcle_non_standard(), Convection_Diffusion_Espece_Multi_Turbulent_QC::lire_motcle_non_standard(), and Convection_Diffusion_Temperature_Turbulent::lire_motcle_non_standard().
completer()
void Convection_Diffusion_Turbulent::completer ()
Complete le modele de turbulence.
References Turbulence_paroi_scal_base::completer(), Modele_turbulence_scal_base::completer(), le_modele_turbulence, and Modele_turbulence_scal_base::loi_paroi().
Referenced by Convection_Diffusion_Temperature_IBM_Turbulent::completer(), Convection_Diffusion_Chaleur_Turbulent_QC::completer(), Convection_Diffusion_Concentration_Turbulent::completer(), and Convection_Diffusion_Temperature_Turbulent::completer().
initTimeStep()
bool Convection_Diffusion_Turbulent::initTimeStep (double dt) virtual
Reimplemented in Convection_Diffusion_Temperature_IBM_Turbulent, Convection_Diffusion_Chaleur_Turbulent_QC, Convection_Diffusion_Concentration_Turbulent, Convection_Diffusion_Espece_Binaire_Turbulent_QC, and Convection_Diffusion_Temperature_Turbulent.
References Modele_turbulence_scal_base::initTimeStep(), and le_modele_turbulence.
Referenced by Convection_Diffusion_Temperature_IBM_Turbulent::initTimeStep(), Convection_Diffusion_Chaleur_Turbulent_QC::initTimeStep(), Convection_Diffusion_Concentration_Turbulent::initTimeStep(), Convection_Diffusion_Espece_Binaire_Turbulent_QC::initTimeStep(), and Convection_Diffusion_Temperature_Turbulent::initTimeStep().
preparer_calcul()
int Convection_Diffusion_Turbulent::preparer_calcul ()
Prepare le calcul.
Returns
(int) renvoie toujours 1
References le_modele_turbulence, and Modele_turbulence_scal_base::preparer_calcul().
Referenced by Convection_Diffusion_Temperature_IBM_Turbulent::preparer_calcul(), Convection_Diffusion_Chaleur_Turbulent_QC::preparer_calcul(), Convection_Diffusion_Concentration_Turbulent::preparer_calcul(), and Convection_Diffusion_Temperature_Turbulent::preparer_calcul().
data_a_sauvegarder()
std::vector< YAML_data > Convection_Diffusion_Turbulent::data_a_sauvegarder () const virtual
for PDI IO: retrieve name, type and dimensions of the fields to save/restore
Reimplemented in Convection_Diffusion_Temperature_IBM_Turbulent, Convection_Diffusion_Chaleur_Turbulent_QC, Convection_Diffusion_Concentration_Turbulent, and Convection_Diffusion_Temperature_Turbulent.
References Modele_turbulence_scal_base::data_a_sauvegarder(), and le_modele_turbulence.
Referenced by Convection_Diffusion_Temperature_IBM_Turbulent::data_a_sauvegarder(), Convection_Diffusion_Chaleur_Turbulent_QC::data_a_sauvegarder(), Convection_Diffusion_Concentration_Turbulent::data_a_sauvegarder(), and Convection_Diffusion_Temperature_Turbulent::data_a_sauvegarder().
sauvegarder()
int Convection_Diffusion_Turbulent::sauvegarder (Sortie & os) const virtual
Simple appel a Modele_turbulence_scal_base::sauvegarder(Sortie&) sur le membre concerne.
Sauvegarde le modele de turbulence sur un flot de sortie.
Parameters
(Sortie& os) un flot de sortie
Returns
(int) code de retour propage
Reimplemented in Convection_Diffusion_Temperature_IBM_Turbulent, Convection_Diffusion_Chaleur_Turbulent_QC, Convection_Diffusion_Concentration_Turbulent, and Convection_Diffusion_Temperature_Turbulent.
References le_modele_turbulence, and Modele_turbulence_scal_base::sauvegarder().
Referenced by Convection_Diffusion_Temperature_IBM_Turbulent::sauvegarder(), Convection_Diffusion_Chaleur_Turbulent_QC::sauvegarder(), Convection_Diffusion_Concentration_Turbulent::sauvegarder(), and Convection_Diffusion_Temperature_Turbulent::sauvegarder().
reprendre()
int Convection_Diffusion_Turbulent::reprendre (Entree & is) virtual
Reprise (apres une sauvegarde) a partir d'un flot d'entree.
Parameters
(Entree& is) un flot d'entree
Returns
(int) renvoie toujours 1
Exceptions
fin de fichier atteinte pendant la reprise
Reimplemented in Convection_Diffusion_Temperature_IBM_Turbulent, Convection_Diffusion_Chaleur_Turbulent_QC, Convection_Diffusion_Concentration_Turbulent, and Convection_Diffusion_Temperature_Turbulent.
References le_modele_turbulence, and Modele_turbulence_scal_base::reprendre().
Referenced by Convection_Diffusion_Temperature_IBM_Turbulent::reprendre(), Convection_Diffusion_Chaleur_Turbulent_QC::reprendre(), Convection_Diffusion_Concentration_Turbulent::reprendre(), and Convection_Diffusion_Temperature_Turbulent::reprendre().
mettre_a_jour()
void Convection_Diffusion_Turbulent::mettre_a_jour (double temps) virtual
Mise a jour en temps du modele de turbulence.
Parameters
(double temps) le temps de mise a jour
Reimplemented in Convection_Diffusion_Concentration_Turbulent_FT_Disc, Convection_Diffusion_Temperature_IBM_Turbulent, Convection_Diffusion_Chaleur_Turbulent_QC, Convection_Diffusion_Concentration_Turbulent, and Convection_Diffusion_Temperature_Turbulent.
References le_modele_turbulence, and Modele_turbulence_scal_base::mettre_a_jour().
Referenced by Convection_Diffusion_Temperature_IBM_Turbulent::mettre_a_jour(), Convection_Diffusion_Concentration_Turbulent::mettre_a_jour(), Convection_Diffusion_Temperature_Turbulent::mettre_a_jour(), and Convection_Diffusion_Chaleur_Turbulent_QC::mettre_a_jour_modele().
lire_op_diff_turbulent()
Entree & Convection_Diffusion_Turbulent::lire_op_diff_turbulent (Entree & is, const Equation_base & eqn, Operateur_Diff & terme_diffusif) protected
References Operateur_Diff::associer_diffusivite(), Operateur_base::associer_eqn(), Objet_U::axi, Operateur_Diff::diffusivite(), Equation_base::discretisation(), Equation_base::inconnue(), Operateur_Diff::l_op_base(), Field_base::nb_comp(), Objet_U::que_suis_je(), Nom::suffix(), Operateur_Diff::typer(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by Convection_Diffusion_Temperature_IBM_Turbulent::lire_motcle_non_standard(), Convection_Diffusion_Chaleur_Turbulent_QC::lire_motcle_non_standard(), Convection_Diffusion_Concentration_Turbulent::lire_motcle_non_standard(), Convection_Diffusion_Espece_Binaire_Turbulent_QC::lire_motcle_non_standard(), Convection_Diffusion_Espece_Multi_Turbulent_QC::lire_motcle_non_standard(), and Convection_Diffusion_Temperature_Turbulent::lire_motcle_non_standard().
Member Data Documentation
le_modele_turbulence
TRUST_Deriv< Modele_turbulence_scal_base > Convection_Diffusion_Turbulent::le_modele_turbulence protected
Referenced by completer(), Convection_Diffusion_Temperature_IBM_Turbulent::creer_champ(), Convection_Diffusion_Chaleur_Turbulent_QC::creer_champ(), Convection_Diffusion_Concentration_Turbulent::creer_champ(), Convection_Diffusion_Espece_Binaire_Turbulent_QC::creer_champ(), Convection_Diffusion_Espece_Multi_Turbulent_QC::creer_champ(), Convection_Diffusion_Temperature_Turbulent::creer_champ(), data_a_sauvegarder(), Convection_Diffusion_Temperature_IBM_Turbulent::get_champ(), Convection_Diffusion_Chaleur_Turbulent_QC::get_champ(), Convection_Diffusion_Concentration_Turbulent::get_champ(), Convection_Diffusion_Espece_Binaire_Turbulent_QC::get_champ(), Convection_Diffusion_Espece_Multi_Turbulent_QC::get_champ(), Convection_Diffusion_Temperature_Turbulent::get_champ(), Convection_Diffusion_Temperature_IBM_Turbulent::get_noms_champs_postraitables(), Convection_Diffusion_Chaleur_Turbulent_QC::get_noms_champs_postraitables(), Convection_Diffusion_Concentration_Turbulent::get_noms_champs_postraitables(), Convection_Diffusion_Espece_Binaire_Turbulent_QC::get_noms_champs_postraitables(), Convection_Diffusion_Espece_Multi_Turbulent_QC::get_noms_champs_postraitables(), Convection_Diffusion_Temperature_Turbulent::get_noms_champs_postraitables(), Convection_Diffusion_Temperature_IBM_Turbulent::has_champ(), Convection_Diffusion_Chaleur_Turbulent_QC::has_champ(), Convection_Diffusion_Concentration_Turbulent::has_champ(), Convection_Diffusion_Espece_Binaire_Turbulent_QC::has_champ(), Convection_Diffusion_Espece_Multi_Turbulent_QC::has_champ(), Convection_Diffusion_Temperature_Turbulent::has_champ(), Convection_Diffusion_Temperature_IBM_Turbulent::imprimer(), Convection_Diffusion_Chaleur_Turbulent_QC::imprimer(), Convection_Diffusion_Temperature_Turbulent::imprimer(), initTimeStep(), lire_modele(), Convection_Diffusion_Temperature_IBM_Turbulent::lire_motcle_non_standard(), Convection_Diffusion_Chaleur_Turbulent_QC::lire_motcle_non_standard(), Convection_Diffusion_Concentration_Turbulent::lire_motcle_non_standard(), Convection_Diffusion_Espece_Binaire_Turbulent_QC::lire_motcle_non_standard(), Convection_Diffusion_Espece_Multi_Turbulent_QC::lire_motcle_non_standard(), Convection_Diffusion_Temperature_Turbulent::lire_motcle_non_standard(), mettre_a_jour(), preparer_calcul(), reprendre(), and sauvegarder().