TrioCFD: Y_plus_Champ_Face Class Reference
Y_plus_Champ_Face Class Reference
#include <Y_plus_Champ_Face.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Champ_Fonc_P0_base
const Type_info * get_info () const override
DoubleTab & remplir_coord_noeuds (DoubleTab &positions) const override
int remplir_coord_noeuds_et_polys (DoubleTab &positions, IntVect &polys) const override
Public Member Functions inherited from Champ_Fonc_base
Champ_base & affecter_ (const Champ_base &) override
Champ_base & affecter_compo (const Champ_base &, int compo) override
int fixer_nb_valeurs_nodales (int nb_noeuds) override
const Type_info * get_info () const override
void mettre_a_jour (double temps) override
virtual DoubleTab & remplir_coord_noeuds (DoubleTab &) const
virtual DoubleTab & remplir_coord_noeuds_compo (DoubleTab &, int) const
virtual int remplir_coord_noeuds_et_polys (DoubleTab &, IntVect &) const
virtual int remplir_coord_noeuds_et_polys_compo (DoubleTab &, IntVect &, int) const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
DoubleTab & valeur_aux (const DoubleTab &, DoubleTab &) const override
Public Member Functions inherited from Champ_Don_base
void dimensionner (int, int)
int fixer_nb_valeurs_nodales (int nb_noeuds) override
const Type_info * get_info () const override
int imprime (Sortie &, int) const override
virtual int initialiser (const double temps)
void mettre_a_jour (double temps) override
int reprendre (Entree &) override
void resetTime (double time) override
int sauvegarder (Sortie &) const override
DoubleTab & valeurs () override
Public Member Functions inherited from Champ_base
Champ_base & affecter (const Champ_base &)
Champ_base ()
virtual double changer_temps (const double t)
const Type_info * get_info () const override
double temps () const
virtual DoubleTab & trace (const Frontiere_dis_base &, DoubleTab &, double, int distant) const
virtual DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const
virtual double valeur_a_compo (const DoubleVect &position, int ncomp) const
virtual DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &valeurs, int le_poly) const
virtual double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const
virtual DoubleVect & valeur_a_sommet (int, const Domaine &, DoubleVect &) const
virtual DoubleTab & valeur_aux (const DoubleTab &positions, DoubleTab &valeurs) const
virtual DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const
virtual DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const
virtual DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp) const
Public Member Functions inherited from Field_base
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
virtual void fixer_nb_comp (int i)
virtual const Nom & fixer_nom_compo (const Nom &)
virtual const Nom & fixer_nom_compo (int, const Nom &)
virtual const Noms & fixer_noms_compo (const Noms &)
virtual const Nom & fixer_unite (const Nom &)
virtual const Nom & fixer_unite (int i, const Nom &)
virtual const Noms & fixer_unites (const Noms &)
const Type_info * get_info () const override
const Nom & nom_compo (int) const
void nommer (const Nom &) override
const Nom & unite () const
const Nom & unite (int) const
const Noms & unites () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Champ_Proto
int lire_dimension (Entree &, const Nom &)
int lire_dimension (int dim, const Nom &le_nom_)
Public Member Functions inherited from Champ_implementation_P0
DoubleTab & valeur_aux_centres_de_gravite (const Domaine &, DoubleTab &valeurs) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
See also
Champ_y_plus Champ_Fonc_P0_VDF
Constructor & Destructor Documentation
Y_plus_Champ_Face()
Y_plus_Champ_Face::Y_plus_Champ_Face ()
~Y_plus_Champ_Face()
Y_plus_Champ_Face::~Y_plus_Champ_Face ()
Member Function Documentation
cree_instance()
Objet_U * Y_plus_Champ_Face::cree_instance () static
taille_memoire()
unsigned Y_plus_Champ_Face::taille_memoire () const override virtual
Reimplemented from Champ_Fonc_P0_VDF.
duplique()
int Y_plus_Champ_Face::duplique () const override virtual
Reimplemented from Champ_Fonc_P0_VDF.
info()
const Type_info * Y_plus_Champ_Face::info () static
get_info()
const Type_info * Y_plus_Champ_Face::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Champ_Fonc_P0_VDF.
self_cast() [1/2]
Y_plus_Champ_Face & Y_plus_Champ_Face::self_cast (Objet_U & r) static
self_cast() [2/2]
const Y_plus_Champ_Face & Y_plus_Champ_Face::self_cast (const Objet_U & r) static
printOn()
Sortie & Y_plus_Champ_Face::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Champ_Fonc_P0_VDF.
References Field_base::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Y_plus_Champ_Face::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Champ_Fonc_P0_VDF.
mettre_a_jour()
void Y_plus_Champ_Face::mettre_a_jour (double) override virtual
mettre_a_jour de la classe de base Champ_base :ne fait rien !
Reimplemented from Champ_Fonc_P0_base.
References Champ_base::changer_temps(), me_calculer(), and Champ_Fonc_base::mettre_a_jour().
associer_champ()
void Y_plus_Champ_Face::associer_champ (const Champ_Face_VDF & un_champ)
References mon_champ_.
Referenced by VDF_discretisation::y_plus().
me_calculer()
void Y_plus_Champ_Face::me_calculer (double tps) override virtual
Implements Champ_y_plus.
References MorEqn::equation(), Equation_base::get_modele(), le_dom_Cl_VDF, Modele_turbulence_hyd_base::loi_paroi(), Equation_base::milieu(), mon_champ(), mon_champ_, Objet_U::que_suis_je(), TRUST_Ref< _CLASSE_ >::valeur(), TRUST_Ref_Objet_U::valeur(), and Champ_Don_base::valeurs().
Referenced by mettre_a_jour().
domaine_Cl_dis_base()
const Domaine_Cl_dis_base & Y_plus_Champ_Face::domaine_Cl_dis_base () const
References le_dom_Cl_VDF, and TRUST_Ref< _CLASSE_ >::valeur().
mon_champ()
const Champ_Face_VDF & Y_plus_Champ_Face::mon_champ () const inline
References mon_champ_, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by me_calculer().
associer_domaine_Cl_dis_base()
void Y_plus_Champ_Face::associer_domaine_Cl_dis_base (const Domaine_Cl_dis_base & le_dom_Cl_dis_base) inline
References le_dom_Cl_VDF.
Referenced by VDF_discretisation::y_plus().
Member Data Documentation
info_obj
const Type_info Y_plus_Champ_Face::info_obj static
mon_champ_
TRUST_Ref< Champ_Face_VDF *> Y_plus_Champ_Face::mon_champ_ protected
Referenced by associer_champ(), me_calculer(), and mon_champ().
le_dom_Cl_VDF
TRUST_Ref< Domaine_Cl_VDF *> Y_plus_Champ_Face::le_dom_Cl_VDF protected
Referenced by associer_domaine_Cl_dis_base(), domaine_Cl_dis_base(), and me_calculer().