TrioCFD: Domaine_IJK Class Reference
Domaine_IJK Class Reference
#include <Domaine_IJK.h>
Public Member Functions
int convert_ijk_cell_to_packed (const FixedVector< int, 3 > ijk) const
int convert_ijk_cell_to_packed (int i, int j, int k) const
FixedVector< int, 3 > convert_packed_to_ijk_cell (int index) const
double get_constant_delta (int direction) const
Vecteur3 get_coords_of_dof (int i, int j, int k, Localisation loc) const
const ArrOfDouble & get_delta (int direction) const
double get_domain_length (int direction) const
int get_independent_index (int i, int j, int k) const
const Type_info * get_info () const override
void get_local_mesh_delta (int direction, int ghost_cells, ArrOfDouble_with_ghost &delta) const
int get_local_slice_index (int direction) const
int get_nb_elem_local (int direction) const
int get_nb_elem_tot (int direction) const
int get_nb_faces_local (int compo, int direction) const
int get_nb_items_global (Localisation loc, int direction) const
int get_nb_items_local (Localisation loc, int direction) const
int get_nb_nodes_local (int direction) const
int get_neighbour_processor (int previous_or_next, int direction) const
const ArrOfDouble & get_node_coordinates (int direction) const
int get_nprocessor_per_direction (int direction) const
int get_offset_local (int direction) const
double get_origin (int direction) const
bool get_periodic_flag (int direction) const
int get_processor_by_ijk (const FixedVector< int, 3 > &slice) const
int get_processor_by_ijk (int slice_i, int slice_j, int slice_k) const
void get_processor_mapping (IntTab &mapping) const
int get_signed_independent_index (int phase, int i, int j, int k) const
void get_slice_offsets (int direction, ArrOfInt &tab) const
void get_slice_size (int direction, Localisation loc, ArrOfInt &tab) const
void init_subregion (const Domaine_IJK &src, int ni, int nj, int nk, int offset_i, int offset_j, int offset_k, const Nom &subregion, bool perio_x=false, bool perio_y=false, bool perio_z=false)
void initialize_mapping (Domaine_IJK &dom, const ArrOfInt &slice_size_i, const ArrOfInt &slice_size_j, const ArrOfInt &slice_size_k, const IntTab &processor_mapping)
void initialize_origin_deltas (double x0, double y0, double z0, const ArrOfDouble &delta_x, const ArrOfDouble &delta_y, const ArrOfDouble &delta_z, bool perio_x, bool perio_y, bool perio_z)
void initialize_splitting (Domaine_IJK &dom, int nproc_i, int nproc_j, int nproc_k, int process_grouping_i=1, int process_grouping_j=1, int process_grouping_k=1)
void initialize_with_mapping (const ArrOfInt &slice_size_i, const ArrOfInt &slice_size_j, const ArrOfInt &slice_size_k, const IntTab &processor_mapping)
bool is_uniform (int direction) const
int periodic_get_processor_by_ijk (int slice_i, int slice_j, int slice_k) const
void search_elem (const double &x, const double &y, const double &z, FixedVector< int, 3 > &ijk_global, FixedVector< int, 3 > &ijk_local, FixedVector< int, 3 > &ijk_me) const
bool within_ghost (int i, int j, int k, int negative_ghost_size, int positive_ghost_size) const
bool within_ghost_along_dir (int dir, int i, int j, int k, int negative_ghost_size, int positive_ghost_size) const
Public Member Functions inherited from Domaine_base
const Type_info * get_info () const override
const Nom & le_nom () const override
void nommer (const Nom &nom) override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions
static Localisation Faces_Dir_To_Localisation (int direction)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
Multiples methods regarding how to navigates through it, volume of the each cells, etc...
Member Enumeration Documentation
Localisation
enum Domaine_IJK::Localisation
Localisation sub class.
Enumerator
ELEM
NODES
FACES_I
FACES_J
FACES_K
grid_status
enum Domaine_IJK::grid_status
status sub class to not compute the same structure twitce when not needed
Enumerator
DEFAULT
INITIALIZED
DONE
Constructor & Destructor Documentation
~Domaine_IJK()
Domaine_IJK::~Domaine_IJK ()
Domaine_IJK()
Domaine_IJK::Domaine_IJK ()
References DEFAULT.
Member Function Documentation
cree_instance()
Objet_U * Domaine_IJK::cree_instance () static
taille_memoire()
unsigned Domaine_IJK::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Domaine_IJK::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Domaine_IJK::info () static
get_info()
const Type_info * Domaine_IJK::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Domaine_base.
self_cast() [1/2]
Domaine_IJK & Domaine_IJK::self_cast (Objet_U & r) static
self_cast() [2/2]
const Domaine_IJK & Domaine_IJK::self_cast (const Objet_U & r) static
printOn()
Sortie & Domaine_IJK::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Domaine_base.
readOn()
Entree & Domaine_IJK::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Domaine_base.
References TRUSTArray< _TYPE_, _SIZE_ >::append_array(), Objet_U::dimension, Entree_Fichier_base::eof(), Process::exit(), initialize_origin_deltas(), initialize_splitting(), Process::je_suis_maitre(), Domaine_base::le_nom(), Process::nproc(), Motcles::search(), and update_volume_elem().
Faces_Dir_To_Localisation()
static Localisation Domaine_IJK::Faces_Dir_To_Localisation (int direction) inline static
Returns the face according to the direction.
Parameters
direction In IJK, x(0), y(1) or z(2).
Returns
A face
References FACES_I, FACES_J, and FACES_K.
initialize_from_unstructured()
void Domaine_IJK::initialize_from_unstructured (const Domaine & domaine, int direction_for_x, int direction_for_y, int direction_for_z, bool perio_x, bool perio_y, bool perio_z)
References Process::exit(), Objet_U::precision_geom, TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by IJK_VDF_converter::readOn().
initialize_splitting()
void Domaine_IJK::initialize_splitting (Domaine_IJK & geom, int nproc_i, int nproc_j, int nproc_k, int process_grouping_i = 1, int process_grouping_j = 1, int process_grouping_k = 1)
Buils a splitting of the given deometry on the requested number of processors in each direction.
Process_grouping allows to rearrange process ranks by packets of ni*nj*nk processes to matc the topology of the cluster/node. ex: 8 cores node/machine => use groups of size 2x2x2 to minimize extra-node messages.
Parameters
nproc_i Number of processors in i direction.
nproc_j Number of processors in j direction.
nproc_k Number of processors in k direction.
process_grouping_i 1 by default. Number of processors per subdomain in i direction.
process_grouping_j 1 by default. Number of processors per subdomain in j direction.
process_grouping_k 1 by default. Number of processors per subdomain in k direction.
   Process_grouping allows to rearrange process ranks by packets of ni*nj*nk processes
   to matc the topology of the cluster/node. ex: 8 cores node/machine => use groups
   of size 2x2x2 to minimize extra-node messages.
Parameters
geom another domaine
nproc_i Number of processors in i direction.
nproc_j Number of processors in j direction.
nproc_k Number of processors in k direction.
process_grouping_i 1 by default. Number of processors per subdomain in i direction.
process_grouping_j 1 by default. Number of processors per subdomain in j direction.
process_grouping_k 1 by default. Number of processors per subdomain in k direction.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Process::exit(), get_nb_elem_tot(), initialize_mapping(), Process::je_suis_maitre(), Process::nproc(), and TRUSTTab< _TYPE_, _SIZE_ >::resize().
Referenced by init_subregion(), IJK_VDF_converter::readOn(), and readOn().
initialize_mapping()
void Domaine_IJK::initialize_mapping (Domaine_IJK & geom, const ArrOfInt & slice_size_i, const ArrOfInt & slice_size_j, const ArrOfInt & slice_size_k, const IntTab & processor_mapping)
Creates a splitting of the domain by specifying the slice sizes and the processor mapping.
The total cell number in directions i, j, and k must match the total number of cells in the whole geometry for each direction. The number of slices in each direction must match each corresponding dimensions of the mapping array. All processors do not have to be used!
Parameters
slice_size_i Contains for each slice in the i direction, the number of cells this slice.
slice_size_j Contains for each slice in the j direction, the number of cells this slice.
slice_size_k Contains for each slice in the k direction, the number of cells this slice.
processor_mapping Provides the rank of the mpi process that will own this subdomain.
   The total cell number in directions i, j, and k must match the
   total number of cells in the whole geometry for each direction.
   The number of slices in each direction must match each corresponding
   dimensions of the mapping array.
   All processors do not have to be used!
Parameters
slice_size_i Contains for each slice in the i direction, the number of cells this slice.
slice_size_j Contains for each slice in the j direction, the number of cells this slice.
slice_size_k Contains for each slice in the k direction, the number of cells this slice.
processor_mapping Provides the rank of the mpi process that will own this subdomain.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), get_nb_elem_tot(), get_periodic_flag(), Process::Journal(), Process::me(), Process::nproc(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by initialize_splitting().
initialize_origin_deltas()
void Domaine_IJK::initialize_origin_deltas (double x0, double y0, double z0, const ArrOfDouble & delta_x, const ArrOfDouble & delta_y, const ArrOfDouble & delta_z, bool perio_x, bool perio_y, bool perio_z)
Initializes class elements given dataset's parameters.
Parameters
x0 Origin of the whole domain on the x axis.
y0 Origin of the whole domain on the y axis.
z0 Origin of the whole domain on the z axis.
delta_x Array with the sizes of the elements on the x axis.
delta_y Array with the sizes of the elements on the y axis.
delta_z Array with the sizes of the elements on the z axis.
perio_x Periodic flag along x axis.
perio_y Periodic flag along y axis.
perio_z Periodic flag along z axis.
References Objet_U::precision_geom.
Referenced by init_subregion(), and readOn().
init_subregion()
void Domaine_IJK::init_subregion (const Domaine_IJK & src, int ni, int nj, int nk, int offset_i, int offset_j, int offset_k, const Nom & subregion_name, bool perio_x = false, bool perio_y = false, bool perio_z = false)
Builds the geometry, parallel splitting and DOF correspondance between a "father" region and a "son" region which is a subpart of the father region.
Only conformal subregion is supported for now, with ELEMENT types. Missing features: be able to build a subregion which is the boundary of another, eg: father is "3D elements", son is "2D faces".
Parameters
ni Number of elements in direction(0)
nj Number of elements in direction(1)
nk Number of elements in direction(2)
offset_i Offset along x axis for the "son" subregion
offset_j Offset along x axis for the "son" subregion
offset_k Offset along x axis for the "son" subregion
subregion_name Name of the "son" subregion
perio_x Whether if domain is periodic along x axis
perio_y Whether if domain is periodic along y axis
perio_z Whether if domain is periodic along z axis
   Only conformal subregion is supported for now, with ELEMENT types.
   Missing features: be able to build a subregion which is the boundary
   of another, eg: father is "3D elements", son is "2D faces".
Parameters
ni Number of elements in direction(0)
nj Number of elements in direction(1)
nk Number of elements in direction(2)
offset_i Offset along x axis for the "son" subregion
offset_j Offset along x axis for the "son" subregion
offset_k Offset along x axis for the "son" subregion
subregion_name Name of the "son" subregion
perio_x Whether if domain is periodic along x axis
perio_y Whether if domain is periodic along y axis
perio_z Whether if domain is periodic along z axis
References get_delta(), get_nb_elem_tot(), get_node_coordinates(), initialize_origin_deltas(), initialize_splitting(), Domaine_base::nommer(), and TRUSTArray< _TYPE_, _SIZE_ >::ref_array().
initialize_with_mapping()
void Domaine_IJK::initialize_with_mapping (const ArrOfInt & slice_size_i, const ArrOfInt & slice_size_j, const ArrOfInt & slice_size_k, const IntTab & processor_mapping)
Creates a splitting of the domain by specifying the mapping.
   The total cell number in directions i,j,k must match the total
   number of cells in each direction.
   The number of slices in direction i, j , k must match dimensions
   0,1 and 2 of the processor_mapping() array.
Parameters
slice_size_i Contains, for each slice in the x direction, the number of cells in this slice.
slice_size_j Contains, for each slice in the y direction, the number of cells in this slice.
slice_size_k Contains, for each slice in the z direction, the number of cells in this slice.
processor_mapping Provides the rank of the mpi process that will have this subdomain.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), get_nb_elem_tot(), get_periodic_flag(), Process::Journal(), Process::me(), Process::nproc(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
creer_faces()
Faces * Domaine_IJK::creer_faces ()
renvoie new(Faces) ! elle est surchargee par Domaine_VDF par ex.
get_nb_elem_local() [1/2]
int Domaine_IJK::get_nb_elem_local (int direction) const inline
Returns the number of elements owned by this processor in the given direction.
Parameters
direction In IJK, x(0), y(1) or z(2)
Returns
nb_elem_local_[direction]
Referenced by IJK_Interfaces::calculer_distance_autres_compo_connexe_ijk(), IJK_Interfaces::calculer_phi_repuls_par_compo(), SurfaceVapeurIJKComputation::calculer_surfaces_et_barys_faces_mouillees_vapeur(), Operateur_IJK_faces_base_double::compute_dtstab_convection_local(), Postprocessing_IJK::compute_extended_pressures(), Navier_Stokes_FTD_IJK::initialise_ns_fields(), Maillage_FT_IJK::initialize(), Fourier_trans::initialize(), VDF_to_IJK::initialize(), DNS_QC_double::interpreter(), Fourier_trans::postraiter_TFi(), Fourier_trans::postraiter_TFx(), Fourier_trans::postraiter_TFy(), DNS_QC_double::posttraiter_champs_instantanes(), IJK_Interfaces::recursive_calcul_distance_chez_voisin(), DNS_QC_double::sauvegarder_qc(), DNS_QC_double::save_raw_data(), Fourier_trans::Traitement_spectral(), Fourier_trans::Traitement_spectral_klayer_direct(), and Fourier_trans::Traitement_spectral_klayer_inverse().
get_nb_elem_local() [2/2]
int Domaine_IJK::get_nb_elem_local () const inline
Returns the number of element owned by this processor.
References Objet_U::dimension.
Referenced by convert_ijk_cell_to_packed(), convert_packed_to_ijk_cell(), correct_perio_i_local(), get_ijk_from_independent_index(), get_independent_index(), get_local_mesh_delta(), get_nb_items_local(), get_volume_elem(), search_elem(), update_volume_elem(), within_ghost(), and within_ghost_along_dir().
get_nb_nodes_local()
int Domaine_IJK::get_nb_nodes_local (int direction) const inline
Returns the number of nodes owned by this processor (generally equal to nb_elem_local())
The last node of the last element is owned by the next processor.
Parameters
direction In IJK, x(0), y(1) or z(2)
Returns
nb_nodes_local_[dir]
Referenced by get_nb_items_local().
get_nb_faces_local()
int Domaine_IJK::get_nb_faces_local (int compo, int direction) const inline
Returns the number, in requested direction, of faces that are oriented in direction of "compo".
The last face of the last element is owned by the next processor.
Parameters
compo direction In IJK, horizontal(0), vertical(1) or z-axis depth(2)
direction In IJK, x(0), y(1) or z(2)
Returns
nb_faces_local_[compo][direction]
Referenced by get_nb_items_local(), OpConvCentre2IJK_double::initialize(), and OpConvCentre4IJK_double::initialize().
get_nb_items_local()
int Domaine_IJK::get_nb_items_local (Localisation loc, int direction) const
Returns the number of local items (on this processor) for the given localisation in the requested direction.
Parameters
loc In IJK, ELEM, NODES, FACES_I, FACES_J or FACES_K
direction In IJK, x(0), y(1) or z(2)
Returns
Number of requested items
References ELEM, FACES_I, FACES_J, FACES_K, get_nb_elem_local(), get_nb_faces_local(), get_nb_nodes_local(), and NODES.
Referenced by Statistiques_dns_ijk::compute_and_store_gradU_cell(), Statistiques_dns_ijk::compute_and_store_scalar_product_face_to_face(), Redistribute_Field::compute_send_blocs(), Statistiques_dns_ijk::compute_vecA_minus_vecB_in_vecA(), and Switch_double::initialise().
get_nb_elem_tot() [1/2]
int Domaine_IJK::get_nb_elem_tot (int direction) const inline
Returns the total (global) number of mesh cells in requested direction.
Parameters
direction In IJK, x(0), y(1) or z(2).
Returns
Number of elements
References get_delta(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by Switch_double::calculer_coeff(), Switch_double::calculer_coords(), Navier_Stokes_FTD_IJK::calculer_moyenne_de_phase_liq(), Navier_Stokes_FTD_IJK::calculer_moyenne_de_phase_vap(), IJK_Thermal_base::calculer_temperature_adimensionnelle_theta(), Corrige_flux_FT_temperature_subresolution::compute_cell_neighbours_faces_indices_to_correct(), Corrige_flux_FT_temperature_subresolution::compute_temperature_cell_centre_neighbours(), IJK_One_Dimensional_Subproblem::dispatch_interfacial_heat_flux_correction(), IJK_Thermal_Subresolution::enforce_periodic_temperature_boundary_value(), Corrige_flux_FT_temperature_subresolution::get_linear_index_global(), init_subregion(), DNS_QC_double::initialise(), Statistiques_dns_ijk_monophasique::initialize(), Fourier_trans::initialize(), Statistiques_dns_ijk::initialize(), Operateur_IJK_data_channel::initialize(), Statistiques_dns_ijk_FT::initialize(), initialize_mapping(), initialize_splitting(), IJK_Thermal_Subresolution::post_process_thermal_wake_slice_index_dir(), Fourier_trans::postraiter_TFx(), Fourier_trans::postraiter_TFy(), Parallel_io_parameters::run_bench_read(), Parallel_io_parameters::run_bench_write(), Corrige_flux_FT_temperature_subresolution::sort_ijk_intersections_subproblems_indices_fluxes_by_k_layers(), and Switch_double::write_velocity().
get_nb_elem_tot() [2/2]
int Domaine_IJK::get_nb_elem_tot () const inline
Returns the total (global) number of mesh cells.
References Objet_U::dimension, get_delta(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by correct_perio_i_local(), get_domain_length(), get_local_mesh_delta(), get_nb_items_global(), initialize_with_mapping(), and search_elem().
get_domain_length()
double Domaine_IJK::get_domain_length (int direction) const
Returns the length of the entire domain in requested direction.
Parameters
direction In IJK, x(0), y(1) or z(2).
Returns
Global length of the domain
References get_nb_elem_tot(), get_node_coordinates(), and get_origin().
Referenced by IJK_Thermal_base::add_temperature_source(), Navier_Stokes_FTD_IJK::calculer_moyenne_de_phase_liq(), Navier_Stokes_FTD_IJK::calculer_moyenne_de_phase_vap(), IJK_Thermal_base::calculer_temperature_adimensionnelle_theta(), Navier_Stokes_FTD_IJK::calculer_terme_asservissement(), Navier_Stokes_FTD_IJK::calculer_terme_source_acceleration(), IJK_Interfaces::compute_bubbles_volume_and_barycentres(), Navier_Stokes_FTD_IJK::compute_correction_for_momentum_balance(), Statistiques_dns_ijk_FT::compute_desequil_alpha(), IJK_Interfaces::compute_external_forces_(), init_forcage_THI::compute_initial_chouippe(), IJK_Thermal_Subresolution::find_points_on_proc(), IJK_Thermal_base::force_upstream_temperature(), IJK_Thermal_Subresolution::initialise_thermal_line_points(), IJK_Interfaces::initialize(), IJK_Thermal_Subresolution::min_max_ldir(), IJK_Thermal_Subresolution::post_process_thermal_wake_slice_index_dir(), IJK_Interfaces::supprimer_certaines_bulles_reelles(), and FT_Field::update_sigma_and_interfacial_source_term_sommet().
get_nb_items_global()
int Domaine_IJK::get_nb_items_global (Localisation loc, int direction) const
Returns the number of local items (on this processor) for the given localisation in the requested direction.
If periodic along requested direction, need to add the last item for nodes and faces.
Parameters
loc In IJK, ELEM, NODES, FACES_I, FACES_J or FACES_K
direction In IJK, x(0), y(1) or z(2)
Returns
Number of requested items
References ELEM, FACES_I, FACES_J, FACES_K, get_nb_elem_tot(), and NODES.
Referenced by IJK_Interfaces::ajouter_terme_source_interfaces(), Navier_Stokes_FTD_IJK::build_redistribute_extended_splitting_ft(), IJK_Thermal_base::calculer_k_pour_bord(), DNS_QC_double::calculer_moyennes_flux(), IJK_Thermal_base::calculer_temperature_adim_bulles(), Statistiques_dns_ijk::compute_and_store_gradU_cell(), IJK_Thermal_Onefluid::compute_dT_rustine(), IJK_Interfaces::compute_external_forces_color_function(), IJK_Thermal_base::compute_global_energy(), Redistribute_Field::initialize(), VDF_to_IJK::initialize(), DNS_QC_double::run(), Fourier_trans::update(), IJK_Interfaces::update_indicatrice(), and Navier_Stokes_FTD_IJK::update_v_ghost_from_rho_v().
get_offset_local()
int Domaine_IJK::get_offset_local (int direction) const inline
Returns the local offset in requested direction.
Parameters
direction In IJK, x(0), y(1) or z(2)
Returns
offset_[direction]
Referenced by IJK_Interfaces::ajouter_terme_source_interfaces(), Cut_cell_surface_efficace::calcul_delta_volume_theorique_bilan(), Couplage_Tubes_IBC::calcul_F_pression2(), Cut_cell_surface_efficace::calcul_surface_face_efficace_iteratif(), Cut_cell_surface_efficace::calcul_surface_interface_efficace(), Cut_cell_surface_efficace::calcul_vitesse_interface(), Switch_double::calculer_coeff(), Switch_double::calculer_coords(), IJK_Thermal_base::calculer_flux_thermique_bord(), IJK_Thermal_base::calculer_k_pour_bord(), DNS_QC_double::calculer_moyennes_flux(), IJK_Thermal_base::calculer_temperature_adimensionnelle_theta(), IJK_Thermal_base::calculer_temperature_physique_T(), IJK_Interfaces::calculer_vitesse_de_deformation(), Corrige_flux_FT_temperature_subresolution::combine_all_fluxes_from_outisde_frontier_on_procs(), Corrige_flux_FT_temperature_subresolution::combine_fluxes_from_frontier_on_procs(), IJK_Thermal_Subresolution::complete_field_thermal_wake_slice_ij_values(), Statistiques_dns_ijk::compute_and_store_gradU_cell(), Corrige_flux_FT_temperature_subresolution::compute_cell_neighbours_faces_indices_to_correct(), Operateur_IJK_faces_base_double::compute_dtstab_convection_local(), IJK_Interfaces::compute_external_forces_color_function(), init_forcage_THI::compute_initial_chouippe(), Redistribute_Field::compute_send_blocs(), DebogIJK::compute_signature(), Corrige_flux_FT_temperature_subresolution::compute_temperature_cell_centre_neighbours(), IJK_One_Dimensional_Subproblem::dispatch_interfacial_heat_flux_correction(), IJK_Thermal_Subresolution::enforce_periodic_temperature_boundary_value(), IJK_Thermal_Subresolution::find_points_on_proc(), Couplage_Tubes_IBC::force_ibc_velocity(), Couplage_Tubes_IBC::force_ibc_velocity_anticipe_cube(), Couplage_Tubes_IBC::force_ibc_velocity_frac_vol(), Couplage_Tubes_IBC::force_ibc_velocity_miroir(), Couplage_Tubes_IBC::force_ibc_velocity_symetrie_plane(), IJK_Thermal_base::force_upstream_temperature(), get_i_along_dir_no_perio(), get_local_mesh_delta(), Couplage_Tubes_IBC::ibc0_force_cube(), Couplage_Tubes_IBC::ibc0_velocity_cube(), Couplage_Tubes_IBC::ibc_diffuse_force_cube(), Couplage_Tubes_IBC::ibc_diffuse_velocity_cube(), Couplage_Tubes_IBC::ibc_localisee_velocity_cube(), Couplage_Tubes_IBC::ibc_localisee_velocity_cube_qdm(), Cut_cell_surface_efficace::imprimer_informations_surface_efficace_face(), Cut_cell_surface_efficace::imprimer_informations_surface_efficace_interface(), Navier_Stokes_FTD_IJK::initialise_ijk_fields(), Navier_Stokes_FTD_IJK::initialise_ns_fields(), Operateur_IJK_data_channel::initialize(), IJK_Thermal_Subresolution::post_process_thermal_wake_slice_index_dir(), Fourier_trans::postraiter_TFi(), Fourier_trans::postraiter_TFx(), Fourier_trans::postraiter_TFy(), IJK_Interfaces::recursive_calcul_distance_chez_voisin(), IJK_One_Dimensional_Subproblems::retrieve_interfacial_heat_flux_correction_on_procs(), search_elem(), Corrige_flux_FT_temperature_subresolution::sort_ijk_intersections_subproblems_indices_fluxes_by_k_layers(), Fourier_trans::update(), IJK_Interfaces::update_indicatrice(), Navier_Stokes_FTD_IJK::update_v_ghost_from_rho_v(), and Force_ph::write_offset_index_position().
get_local_slice_index()
int Domaine_IJK::get_local_slice_index (int direction) const inline
Returns the position of the local subdomain in the requested direction.
Parameters
direction In IJK, x(0), y(1) or z(2)
Returns
processor_position_[direction]
Referenced by Navier_Stokes_FTD_IJK::calculer_vitesse_droite(), Navier_Stokes_FTD_IJK::calculer_vitesse_gauche(), FT_Field::completer_compo_connexe_partielle(), Fourier_trans::reprise(), DNS_QC_double::run(), and Fourier_trans::sauvegarde().
get_neighbour_processor()
int Domaine_IJK::get_neighbour_processor (int previous_or_next, int direction) const inline
Returns the index of the requested neighbour processor (-1 if no neighbour).
previous_or_next = 0 => get processor at left (in the direction of smaller indices). previous_or_next = 1 => get processor at right (in the direction of the larger indices).
Parameters
preivous_or_next 0 or 1, previous or next one respectively.
direction In IJK, x(0), y(1) or z(2).
Returns
neighbour_processors_[previous_or_next][dir]
Referenced by IJK_Interfaces::recursive_calcul_distance_chez_voisin().
get_nprocessor_per_direction()
int Domaine_IJK::get_nprocessor_per_direction (int direction) const inline
Returns the number of slices in the given direction.
Parameters
direction In IJK, x(0), y(1) or z(2).
Returns
nproc_per_direction_[direction]
Referenced by Navier_Stokes_FTD_IJK::calculer_vitesse_droite(), FT_Field::completer_compo_connexe_partielle(), DNS_QC_double::interpreter(), periodic_get_processor_by_ijk(), and DNS_QC_double::run().
get_node_coordinates()
const ArrOfDouble & Domaine_IJK::get_node_coordinates (int direction) const inline
Returns an array with the coordinates of all nodes in the mesh in requested direction.
Parameters
direction In IJK, x(0), y(1) or z(2).
Returns
node_coordinates_xyz_[direction]
Referenced by Couplage_Tubes_IBC::calcul_F_pression(), Couplage_Tubes_IBC::calcul_F_pression2(), IJK_Interfaces::calculer_phi_repuls_sommet(), Couplage_Tubes_IBC::force_ibc_velocity(), Couplage_Tubes_IBC::force_ibc_velocity_anticipe_cube(), Couplage_Tubes_IBC::force_ibc_velocity_frac_vol(), Couplage_Tubes_IBC::force_ibc_velocity_miroir(), Couplage_Tubes_IBC::force_ibc_velocity_symetrie_plane(), get_coord_of_dof_along_dir(), get_coords_of_dof(), get_domain_length(), Couplage_Tubes_IBC::ibc0_force_cube(), Couplage_Tubes_IBC::ibc0_velocity_cube(), Couplage_Tubes_IBC::ibc_diffuse_force_cube(), Couplage_Tubes_IBC::ibc_diffuse_velocity_cube(), Couplage_Tubes_IBC::ibc_localisee_velocity_cube(), Couplage_Tubes_IBC::ibc_localisee_velocity_cube_qdm(), init_subregion(), DNS_QC_double::initialise(), Statistiques_dns_ijk_monophasique::initialize(), Fourier_trans::initialize(), Statistiques_dns_ijk::initialize(), VDF_to_IJK::initialize(), Statistiques_dns_ijk_FT::initialize(), Fourier_trans::postraiter_TFx(), Fourier_trans::postraiter_TFy(), IJK_Interfaces::recursive_calcul_distance_chez_voisin(), and Tube_libre::update_vitesse_position().
get_origin()
double Domaine_IJK::get_origin (int direction) const inline
Returns the coordinate of the first node (global) of the mesh in the requested direction.
Parameters
direction In IJK, x(0), y(1) or z(2).
Returns
coordinate.
Referenced by Cut_cell_surface_efficace::calcul_delta_volume_theorique_bilan(), Cut_cell_surface_efficace::calcul_vitesse_interface(), IJK_Thermal_base::calculer_temperature_physique_T(), IJK_Interfaces::calculer_vitesse_de_deformation(), Statistiques_dns_ijk_FT::compute_desequil_alpha(), init_forcage_THI::compute_initial_chouippe(), IJK_Thermal_base::force_upstream_temperature(), get_domain_length(), get_i_along_dir_no_perio(), DNS_QC_double::initialise(), IJK_Thermal_Subresolution::initialise_thermal_line_points(), IJK_Interfaces::initialize(), IJK_Thermal_Subresolution::min_max_ldir(), IJK_Thermal_Subresolution::post_process_thermal_wake_slice_index_dir(), Fourier_trans::postraiter_TFx(), Fourier_trans::postraiter_TFy(), search_elem(), and IJK_Interfaces::supprimer_certaines_bulles_reelles().
get_delta()
const ArrOfDouble & Domaine_IJK::get_delta (int direction) const inline
Returns the array of mesh cell sizes in requested direction.
Parameters
direction In IJK, x(0), y(1) or z(2).
Returns
Array with the sizes.
Referenced by Cut_cell_surface_efficace::calcul_surface_face_efficace_iteratif(), Cut_cell_surface_efficace::calcul_surface_interface_efficace(), Switch_double::calculer_coords(), IJK_Thermal_base::calculer_flux_thermique_bord(), Navier_Stokes_FTD_IJK::calculer_moyenne_de_phase_liq(), Navier_Stokes_FTD_IJK::calculer_moyenne_de_phase_vap(), Operateur_IJK_faces_base_double::compute_dtstab_convection_local(), Schema_Temps_IJK_base::find_timestep(), get_coord_of_dof_along_dir(), get_coords_of_dof(), get_local_mesh_delta(), get_nb_elem_tot(), Cut_cell_surface_efficace::imprimer_informations_surface_efficace_face(), Cut_cell_surface_efficace::imprimer_informations_surface_efficace_interface(), init_subregion(), Statistiques_dns_ijk_monophasique::initialize(), Fourier_trans::initialize(), Statistiques_dns_ijk::initialize(), Statistiques_dns_ijk_FT::initialize(), and update_volume_elem().
get_constant_delta()
double Domaine_IJK::get_constant_delta (int direction) const inline
Returns the size of cells in a direction.
This requires the size of all cells in this direction to be the same, Which means is_uniform(direction) has to be true.
Parameters
direction In IJK, x(0), y(1) or z(2).
Returns
length of cells in this direction.
References Process::exit(), and is_uniform().
Referenced by IJK_Thermal_base::add_temperature_source(), IJK_Interfaces::ajouter_terme_source_interfaces(), Cut_cell_surface_efficace::calcul_delta_volume_theorique_bilan(), Couplage_Tubes_IBC::calcul_F_pression(), Couplage_Tubes_IBC::calcul_F_pression2(), Intersection_Interface_ijk_face::calcul_projection_bary_face_mouillee_interface_moy(), Cut_cell_surface_efficace::calcul_surface_face_efficace_iteratif(), Cut_cell_surface_efficace::calcul_surface_interface_efficace(), Cut_cell_surface_efficace::calcul_vitesse_interface(), Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_ponderation_voisin(), Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_semi_lagrangien(), Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_semi_lagrangien_interpolate(), IJK_Interfaces::calculer_aire_interfaciale(), IJK_Interfaces::calculer_aire_interfaciale_for_compo(), Switch_double::calculer_coords(), Navier_Stokes_FTD_IJK::calculer_dv(), IJK_Thermal_base::calculer_flux_thermique_bord(), DNS_QC_double::calculer_moyennes_flux(), IJK_Interfaces::calculer_normales_et_aires_interfaciales(), IJK_Interfaces::calculer_phi_repuls_sommet(), ParcoursIJKDir::calculer_surface_face(), IJK_Thermal_base::calculer_temperature_physique_T(), IJK_Interfaces::calculer_vitesse_de_deformation(), IJK_One_Dimensional_Subproblem::complete_frame_of_reference_lrs_fluxes_eval(), IJK_Thermal_base::compute_cell_diagonal(), IJK_Interfaces::compute_cell_phase_with_interface_normal(), IJK_Thermal_base::compute_cell_volume(), Navier_Stokes_FTD_IJK::compute_correction_for_momentum_balance(), IJK_One_Dimensional_Subproblem::compute_distance_cell_centres_neighbours(), IJK_One_Dimensional_Subproblem_Geometry::compute_distance_cell_centres_neighbours(), IJK_One_Dimensional_Subproblem::compute_distance_last_cell_faces_neighbours(), IJK_One_Dimensional_Subproblem_Geometry::compute_distance_last_cell_faces_neighbours(), IJK_Interfaces::compute_drapeaux_vapeur_v4(), Operateur_IJK_faces_base_double::compute_dtstab_convection_local(), Postprocessing_IJK::compute_extended_pressures(), IJK_Interfaces::compute_external_forces_color_function(), Cut_cell_schema_auxiliaire::compute_flux_dying_cells(), Cut_cell_schema_auxiliaire::compute_flux_small_nascent_cells(), IJK_Thermal_Subresolution::compute_ghost_cell_numbers_for_subproblems(), IJK_Thermal_base::compute_global_energy(), IJK_Thermal_base::compute_interfacial_temperature2(), IJK_Thermal_base::compute_min_cell_delta(), DNS_QC_double::compute_rho_bulk(), DNS_QC_double::compute_rho_t_bulk(), DNS_QC_double::compute_t_bulk(), IJK_Thermal_Onefluid::compute_T_rust(), IJK_Thermal_Onefluid::compute_temperature_convection_conservative(), IJK_One_Dimensional_Subproblem::compute_vertex_position(), IJK_One_Dimensional_Subproblem_Geometry::compute_vertex_position(), IJK_One_Dimensional_Subproblem::find_cell_related_indicator_on_probes(), IJK_One_Dimensional_Subproblem_Geometry::find_cell_related_indicator_on_probes(), IJK_Thermal_Subresolution::find_points_on_proc(), Schema_Temps_IJK_base::find_timestep(), DNS_QC_double::fixer_reference_pression(), Couplage_Tubes_IBC::force_ibc_velocity(), Couplage_Tubes_IBC::force_ibc_velocity_anticipe_cube(), Couplage_Tubes_IBC::force_ibc_velocity_frac_vol(), Couplage_Tubes_IBC::force_ibc_velocity_miroir(), Couplage_Tubes_IBC::force_ibc_velocity_symetrie_plane(), IJK_Thermal_base::force_upstream_temperature(), Remaillage_FT_IJK::get_delta_euler(), IJK_One_Dimensional_Subproblem::get_discrete_surface_at_level(), IJK_One_Dimensional_Subproblem::get_discrete_two_dimensional_spacing(), Facettes_Interp_FT::get_distance_interpolation_1(), Facettes_Interp_FT::get_distance_interpolation_2(), IJK_One_Dimensional_Subproblem::get_dxyz_increment_max(), IJK_One_Dimensional_Subproblem_Geometry::get_dxyz_increment_max(), IJK_One_Dimensional_Subproblem::get_dxyz_over_two_increment_max(), IJK_One_Dimensional_Subproblem_Geometry::get_dxyz_over_two_increment_max(), get_i_along_dir_no_perio(), Couplage_Tubes_IBC::ibc0_force_cube(), Couplage_Tubes_IBC::ibc0_velocity_cube(), Couplage_Tubes_IBC::ibc_diffuse_force_cube(), Couplage_Tubes_IBC::ibc_diffuse_velocity_cube(), Couplage_Tubes_IBC::ibc_localisee_velocity_cube(), Couplage_Tubes_IBC::ibc_localisee_velocity_cube_qdm(), IJK_Thermal_base::imposer_flux_thermique_bord(), Cut_cell_surface_efficace::imprimer_informations_surface_efficace_face(), Cut_cell_surface_efficace::imprimer_informations_surface_efficace_interface(), Switch_FT_double::initialise(), Statistiques_dns_ijk_monophasique::initialize(), Fourier_trans::initialize(), Statistiques_dns_ijk::initialize(), Operateur_IJK_data_channel::initialize(), OpConvQuickSharpIJK_double::initialize(), IJK_Interfaces::initialize(), Statistiques_dns_ijk_FT::initialize(), DNS_QC_double::interpreter(), IJK_Thermal_Subresolution::post_process_thermal_wake_slice_index_dir(), DNS_QC_double::rk3_sub_step(), search_elem(), set_extension_from_bulle_param(), IJK_Interfaces::supprimer_certaines_bulles_reelles(), Tube_libre::update_vitesse_position(), and update_volume_elem().
get_local_mesh_delta()
void Domaine_IJK::get_local_mesh_delta (int direction, int ghost_cells, ArrOfDouble_with_ghost & delta) const
Fills the "delta" array with the size of the cells owned by the processor in the requested direction.
"delta" is redimensionned with the specified number of ghost cells and filled. If domain is periodic, takes periodic mesh size in ghost cells on first and last subdomain, if domain is not periodic, copy the size of the first and last cell into ghost cells in the walls.
Parameters
direction In IJK, x(0), y(1) or z(2).
ghost_cells Size of the ghost cells
delta Size of cells in each direction
References Process::exit(), get_delta(), get_nb_elem_local(), get_nb_elem_tot(), get_offset_local(), get_periodic_flag(), and IJKArray_with_ghost< _TYPE_, _TYPE_ARRAY_ >::resize().
Referenced by Operateur_IJK_data_channel::initialize(), DNS_QC_double::interpreter(), and Switch_double::run().
get_processor_mapping()
void Domaine_IJK::get_processor_mapping (IntTab & mapping) const inline
Fills an array containing the mapping of processors.
For 3 slices indices i,j,k, the processor that owns the intersection of these slices is mapping(i,j,k).
Parameters
mapping Table in which we'll copy the mapping
Referenced by VDF_to_IJK::initialize().
get_slice_offsets()
void Domaine_IJK::get_slice_offsets (int direction, ArrOfInt & tab) const inline
Returns the indices of the first cell in requested direction of every slices in this direction.
Parameters
direction In IJK, x(0), y(1) or z(2).
tab Array in which we'll store the offsets in that direction
Referenced by Redistribute_Field::compute_send_blocs(), and VDF_to_IJK::initialize().
get_slice_size()
void Domaine_IJK::get_slice_size (int direction, Localisation loc, ArrOfInt & tab) const
Returns the number of items of given location (elements, nodes, faces...) for all slices in the requested direction.
Parameters
direction In IJK, x(0), y(1) or z(2).
loc In IJK, ELEM, NODES, FACES_I, FACES_J or FACES_K
tab Array in which we'll store the number of slices in given direction
References ELEM, FACES_I, FACES_J, FACES_K, NODES, and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by Redistribute_Field::compute_send_blocs(), and VDF_to_IJK::initialize().
get_processor_by_ijk() [1/2]
int Domaine_IJK::get_processor_by_ijk (const FixedVector< int, 3 > & slice) const inline
Return the global index of the processor according to its position.
Parameters
slice Vector with the x, y, and z coordinate of the processor.
Returns
mapping_(slice[0], slice[1], slice[2])
Referenced by FT_Field::completer_compo_connexe_partielle(), Redistribute_Field::initialize(), and periodic_get_processor_by_ijk().
get_processor_by_ijk() [2/2]
int Domaine_IJK::get_processor_by_ijk (int slice_i, int slice_j, int slice_k) const inline
Return the global index of the processor according to its position.
Parameters
slice_i First index of the processor in the global mapping
slice_j Second index of the processor in the global mapping
slice_k Third index of the processor in the global mapping
Returns
return mapping_(slice_i, slice_j, slice_k)
periodic_get_processor_by_ijk()
int Domaine_IJK::periodic_get_processor_by_ijk (int slice_i, int slice_j, int slice_k) const
Returns the processor associated with slice indices i,j,k accounting for periodicity e.g. a slice index -1 can refer to the last slice along a periodic direction.
References get_nprocessor_per_direction(), get_periodic_flag(), and get_processor_by_ijk().
get_coords_of_dof()
Vecteur3 Domaine_IJK::get_coords_of_dof (int i, int j, int k, Localisation loc) const
Determines the dof of an element along a localisation.
TODO: Not sure about the brief?
Parameters
i Local index of an element along x axis.
j Local index of an element along y axis.
k Local index of an element along z axis.
In IJK, ELEM, NODES, FACES_I, FACES_J or FACES_K.
Returns
A vector with the coordinates of dof
References ELEM, FACES_I, FACES_J, FACES_K, get_delta(), get_node_coordinates(), and NODES.
Referenced by IJK_Interfaces::ajouter_terme_source_interfaces(), Intersection_Interface_ijk_face::calcul_projection_bary_face_mouillee_interface_moy(), Intersection_Interface_ijk_cell::calcul_projection_centre_faces_sur_interface_moy(), Intersection_Interface_ijk_cell::calcul_projection_centre_sur_interface_moy(), and Switch_double::calculer_coords().
get_coord_of_dof_along_dir()
double Domaine_IJK::get_coord_of_dof_along_dir (int dir, int i, Localisation loc) const inline
References FACES_I, FACES_J, FACES_K, get_delta(), get_node_coordinates(), and NODES.
Referenced by Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_semi_lagrangien_interpolate().
get_independent_index()
int Domaine_IJK::get_independent_index (int i, int j, int k) const
independent_index adds a ghost_size to the packed index. It is similar to the linear_index defined in IJK_Field_local_template, but with a universal, predefined ghost_size of 256 instead of a field-dependent ghost_size. Since the ghost_size_ value is larger than any ghost_size expected to be used in practice, any virtual cell can be represented by the independent index.
References get_nb_elem_local().
Referenced by get_signed_independent_index().
get_ijk_from_independent_index()
Int3 Domaine_IJK::get_ijk_from_independent_index (int independent_index) const
References get_nb_elem_local().
get_signed_independent_index()
int Domaine_IJK::get_signed_independent_index (int phase, int i, int j, int k) const
signed_independent_index: encodes in the sign the phase of the cell in a two-phase flow: positive sign for phase 0, and negative sign for phase 1. With a cut-cell method, this can be used to disambiguate the sub-cell.
References get_independent_index().
get_independent_index_from_signed_independent_index()
int Domaine_IJK::get_independent_index_from_signed_independent_index (int signed_independent_index) const
get_phase_from_signed_independent_index()
int Domaine_IJK::get_phase_from_signed_independent_index (int signed_independent_index) const
within_ghost()
bool Domaine_IJK::within_ghost (int i, int j, int k, int negative_ghost_size, int positive_ghost_size) const
Check whether the cell (i,j,k) is contained within the specified ghost along any direction.
References get_nb_elem_local().
Referenced by Cut_cell_schema_auxiliaire::add_dying_cells(), Cut_cell_schema_auxiliaire::add_small_nascent_cells(), Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_copie_directe(), Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_ponderation_voisin(), Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_semi_lagrangien(), Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_semi_lagrangien_interpolate(), OpDiffIJKScalar_cut_cell_double::compute_cut_cell_divergence(), OpConvQuickIJKScalar_cut_cell_double::compute_cut_cell_divergence(), Cut_cell_schema_auxiliaire::compute_flux_dying_cells(), and Cut_cell_schema_auxiliaire::compute_flux_small_nascent_cells().
within_ghost_along_dir()
bool Domaine_IJK::within_ghost_along_dir (int dir, int i, int j, int k, int negative_ghost_size, int positive_ghost_size) const
Check whether the cell (i,j,k) is contained within the specified ghost along a specific direction.
References get_nb_elem_local().
Referenced by within_ghost_().
within_ghost_()
template<int _DIR_> bool Domaine_IJK::within_ghost_ (int i, int j, int k, int negative_ghost_size, int positive_ghost_size) const inline
References within_ghost_along_dir().
correct_perio_i_local()
int Domaine_IJK::correct_perio_i_local (int direction, int i) const
References Process::exit(), get_nb_elem_local(), get_nb_elem_tot(), get_periodic_flag(), and is_uniform().
Referenced by get_i_along_dir_perio().
get_i_along_dir_no_perio()
int Domaine_IJK::get_i_along_dir_no_perio (int direction, double coord_dir, Domaine_IJK::Localisation loc) const
References Process::exit(), FACES_I, FACES_J, FACES_K, get_constant_delta(), get_offset_local(), get_origin(), and is_uniform().
Referenced by get_i_along_dir_perio().
get_i_along_dir_perio()
int Domaine_IJK::get_i_along_dir_perio (int direction, double coord_dir, Domaine_IJK::Localisation loc) const
References correct_perio_i_local(), and get_i_along_dir_no_perio().
Referenced by get_ijk_from_coord().
get_ijk_from_coord()
Int3 Domaine_IJK::get_ijk_from_coord (double coord_x, double coord_y, double coord_z, Domaine_IJK::Localisation loc) const
References get_i_along_dir_perio().
convert_ijk_cell_to_packed() [1/2]
int Domaine_IJK::convert_ijk_cell_to_packed (const FixedVector< int, 3 > ijk) const inline
Converts the ijk index of an element to a cell index.
Adapted from Maillage_FT_IJK.h
Parameters
ijk Vector with the x, y, and z coordinates.
Returns
The LOCAL index of an element.
References convert_ijk_cell_to_packed().
Referenced by Intersection_Interface_ijk_cell::calcul_projection_centre_faces_sur_interface_moy(), Intersection_Interface_ijk_cell::calcul_projection_centre_sur_interface_moy(), IJK_Interfaces::calculer_barycentre(), IJK_Interfaces::calculer_indicatrice(), IJK_Interfaces::calculer_indicatrice_optim(), IJK_Interfaces::calculer_indicatrice_surfacique_barycentre_face(), IJK_Interfaces::calculer_indicatrice_surfacique_face(), IJK_Interfaces::calculer_indicatrices(), IJK_Interfaces::calculer_indicatrices_optim(), IJK_Interfaces::calculer_surface_interface(), IJK_Composantes_Connex::compute_compo_connex_from_interface(), IJK_Interfaces::compute_external_forces_color_function(), Intersection_Interface_ijk_face::compute_mean_interface_face(), convert_ijk_cell_to_packed(), Corrige_flux_FT_temperature_subresolution::replace_temperature_cell_centre_neighbours(), IJK_One_Dimensional_Subproblems_Interfaces_Fields::retrieve_interfacial_surface_quantity(), and Maillage_FT_IJK::set_ijk_cell_index().
convert_ijk_cell_to_packed() [2/2]
int Domaine_IJK::convert_ijk_cell_to_packed (int i, int j, int k) const
With three indices, find the local index of an element.
Parameters
i Local index of an element along x axis.
j Local index of an element along y axis.
k Local index of an element along z axis.
Returns
The LOCAL index of an element.
References get_nb_elem_local().
convert_packed_to_ijk_cell()
FixedVector< int, 3 > Domaine_IJK::convert_packed_to_ijk_cell (int index) const
Convert the local index of an element to a vector with IJK indices.
Adapted from Maillage_FT_IJK.h
Parameters
index Local index of the element.
Returns
Vector with IJK coordinates.
References get_nb_elem_local().
Referenced by IJK_Interfaces::calculer_aire_interfaciale(), IJK_Interfaces::calculer_aire_interfaciale_for_compo(), IJK_Interfaces::calculer_kappa_ft(), IJK_Interfaces::calculer_normales_et_aires_interfaciales(), IJK_Composantes_Connex::compute_compo_connex_from_interface(), Sonde_IJK::fill_local_values(), IJK_Composantes_Connex::fill_mixed_cell_compo(), Maillage_FT_IJK::get_ijk_cell_index(), Intersection_Interface_ijk::get_mean_interface_cell(), IJK_One_Dimensional_Subproblems_Interfaces_Fields::retrieve_interfacial_surface_quantity(), and Corrige_flux_FT_temperature_subresolution::smooth_temperature_cell_centre_neighbours().
search_elem()
void Domaine_IJK::search_elem (const double & x, const double & y, const double & z, FixedVector< int, 3 > & ijk_global, FixedVector< int, 3 > & ijk_local, FixedVector< int, 3 > & ijk_me) const
Find the element which contains the item's coodirnates.
The element's coordinates can be outside of this processor's subdomain.
Parameters
x First coordinate of an item in the mesh.
y Second coordinate of an item in the mesh.
z Third coordinate of an item in the mesh.
ijk_global The global coordinates of the cell.
ijk_local The local coordinates of the cell.
ijk_me A sort of 3D flag. Will be [1,1,1] if the element belongs to me.
References get_constant_delta(), get_nb_elem_local(), get_nb_elem_tot(), get_offset_local(), and get_origin().
Referenced by IJK_Interfaces::compute_external_forces_color_function().
get_periodic_flag()
bool Domaine_IJK::get_periodic_flag (int direction) const inline
Method returns true if periodic in this direction.
Parameters
direction In IJK, x(0), y(1) or z(2).
Returns
true or false
Referenced by IJK_Interfaces::ajouter_terme_source_interfaces(), Navier_Stokes_FTD_IJK::build_redistribute_extended_splitting_ft(), Navier_Stokes_FTD_IJK::calculer_dv(), IJK_Interfaces::calculer_phi_repuls_sommet(), IJK_Interfaces::compute_external_forces_color_function(), correct_perio_i_local(), Statistiques_dns_ijk::face_to_cell_gradient(), IJK_Thermal_base::force_upstream_temperature(), get_local_mesh_delta(), IJK_Thermal_Subresolution::initialise_thermal_line_points(), Operateur_IJK_data_channel::initialize(), Operateur_IJK_faces_conv_base_double::initialize(), Operateur_IJK_elem_conv_base_double::initialize(), Operateur_IJK_elem_diff_base_double::initialize(), Operateur_IJK_faces_diff_base_double::initialize(), IJK_Interfaces::initialize(), initialize_mapping(), initialize_with_mapping(), periodic_get_processor_by_ijk(), IJK_Thermal_Subresolution::post_process_thermal_wake_slice_index_dir(), and Switch_double::prepare_run().
is_uniform()
bool Domaine_IJK::is_uniform (int direction) const inline
Method returns true if uniform in this direction.
Parameters
direction In IJK, x(0), y(1) or z(2).
Returns
true or false
Referenced by Cut_cell_schema_auxiliaire::add_dying_cells(), Cut_cell_schema_auxiliaire::add_small_nascent_cells(), Cut_cell_surface_efficace::calcul_delta_volume_theorique_bilan(), Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_ponderation_voisin(), IJK_Interfaces::calculer_vitesse_de_deformation(), Cut_cell_schema_auxiliaire::compute_flux_dying_cells(), Cut_cell_schema_auxiliaire::compute_flux_small_nascent_cells(), correct_perio_i_local(), get_constant_delta(), get_i_along_dir_no_perio(), Operateur_IJK_data_channel::initialize(), and update_volume_elem().
update_volume_elem()
void Domaine_IJK::update_volume_elem ()
Updates volume_elem_ / ! \ If the grid changes, this needs to be called again!
References DONE, Process::exit(), get_constant_delta(), get_delta(), get_nb_elem_local(), is_uniform(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by readOn().
get_volume_elem()
const DoubleVect & Domaine_IJK::get_volume_elem () const inline
Returns volume_elem_.
References DONE, get_nb_elem_local(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
ft_extension()
int Domaine_IJK::ft_extension () const inline
Referenced by Navier_Stokes_FTD_IJK::build_redistribute_extended_splitting_ft(), and Navier_Stokes_FTD_IJK::calculer_vitesse_ft().
set_extension_from_bulle_param()
void Domaine_IJK::set_extension_from_bulle_param (double vol_bulle, double diam_bulle)
References get_constant_delta().
Referenced by Navier_Stokes_FTD_IJK::completer().
Member Data Documentation
info_obj
const Type_info Domaine_IJK::info_obj static