TrioCFD: Iterateur_Source_base Class Reference
Iterateur_Source_base Class Reference abstract
#include <Iterateur_Source_base.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Iterateur_Source_base()
Iterateur_Source_base::Iterateur_Source_base ()
~Iterateur_Source_base()
Iterateur_Source_base::~Iterateur_Source_base () override
Member Function Documentation
info()
const Type_info * Iterateur_Source_base::info () static
get_info()
const Type_info * Iterateur_Source_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
Iterateur_Source_base & Iterateur_Source_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Iterateur_Source_base & Iterateur_Source_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Iterateur_Source_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
References Objet_U::que_suis_je().
readOn()
Entree & Iterateur_Source_base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
ajouter()
virtual DoubleTab & Iterateur_Source_base::ajouter (DoubleTab &) const pure virtual
Implemented in Iterateur_Source_EF_Som< _TYPE_ >, Iterateur_Source_Elem< _TYPE_ >, Iterateur_Source_Face< _TYPE_ >, and Iterateur_Source_VEF_Face< _TYPE_ >.
Referenced by Terme_Source_EF_base::ajouter(), Terme_Source_VEF_base::ajouter(), Source_Neutronique_VDF::ajouter_blocs(), Terme_Source_VDF_base::ajouter_blocs(), and calculer().
evaluateur()
virtual Evaluateur_Source & Iterateur_Source_base::evaluateur () pure virtual
Implemented in Iterateur_Source_EF_Som< _TYPE_ >, Iterateur_Source_Elem< _TYPE_ >, Iterateur_Source_Face< _TYPE_ >, and Iterateur_Source_VEF_Face< _TYPE_ >.
Referenced by Terme_Puissance_Thermique_DG_Elem::associer_domaines(), Puissance_Thermique_EF::associer_domaines(), Puissance_Thermique_QC_EF::associer_domaines(), Terme_Puissance_Thermique_PolyMAC_Elem::associer_domaines(), Terme_Source_Constituant_PolyMAC_Elem::associer_domaines(), Source_Dirac_VDF_Elem::associer_domaines(), Source_Echange_Th_VDF::associer_domaines(), Source_Neutronique_VDF::associer_domaines(), Terme_Gravite_VDF_Face::associer_domaines(), Terme_Puissance_Thermique_QC_VDF_Elem::associer_domaines(), Terme_Puissance_Thermique_VDF_Elem::associer_domaines(), Terme_Source_Constituant_VDF_Elem::associer_domaines(), Source_Dirac_VEF_Face::associer_domaines(), Terme_Puissance_Thermique_QC_VEF_Face::associer_domaines(), Terme_Puissance_Thermique_VEF_Face::associer_domaines(), Terme_Source_Constituant_VEF_Face::associer_domaines(), Terme_Gravite_VDF_Face::associer_gravite(), Terme_Puissance_Thermique_DG_Elem::associer_pb(), Puissance_Thermique_EF::associer_pb(), Puissance_Thermique_QC_EF::associer_pb(), Terme_Puissance_Thermique_PolyMAC_Elem::associer_pb(), Terme_Source_Constituant_PolyMAC_Elem::associer_pb(), Source_Dirac_VDF_Elem::associer_pb(), Source_Echange_Th_VDF::associer_pb(), Source_Neutronique_VDF::associer_pb(), Terme_Puissance_Thermique_QC_VDF_Elem::associer_pb(), Terme_Puissance_Thermique_VDF_Elem::associer_pb(), Terme_Source_Constituant_VDF_Elem::associer_pb(), Source_Dirac_VEF_Face::associer_pb(), Terme_Puissance_Thermique_QC_VEF_Face::associer_pb(), Terme_Puissance_Thermique_VEF_Face::associer_pb(), Terme_Source_Constituant_VEF_Face::associer_pb(), Source_Darcy_VDF_Face::eval(), Source_Forchheimer_VDF_Face::eval(), Source_Darcy_VEF_Face::eval(), and Source_Forchheimer_VEF_Face::eval().
completer_()
virtual void Iterateur_Source_base::completer_ () pure virtual
Implemented in Iterateur_Source_EF_Som< _TYPE_ >, Iterateur_Source_Elem< _TYPE_ >, Iterateur_Source_Face< _TYPE_ >, and Iterateur_Source_VEF_Face< _TYPE_ >.
Referenced by Terme_Source_DG_base::completer(), Terme_Source_EF_base::completer(), Terme_Source_PolyMAC_base::completer(), Source_Neutronique_VDF::completer(), Terme_Source_VDF_base::completer(), and Terme_Source_VEF_base::completer().
calculer()
virtual DoubleTab & Iterateur_Source_base::calculer (DoubleTab & resu) const inline virtual
References ajouter().
Referenced by Terme_Source_EF_base::calculer(), Source_Neutronique_VDF::calculer(), Terme_Source_VDF_base::calculer(), and Terme_Source_VEF_base::calculer().
initialiser()
virtual int Iterateur_Source_base::initialiser (double) inline virtual
Reimplemented in Iterateur_Source_VEF_Face< _TYPE_ >.
References Process::exit().
Referenced by Terme_Source_VEF_base::initialiser().
associer()
void Iterateur_Source_base::associer (const Source_base & source) inline
References so_base.
Referenced by Terme_Source_DG_base::completer(), Terme_Source_PolyMAC_base::completer(), Terme_Source_VDF_base::completer(), and Terme_Source_VEF_base::completer().
equation_divisee_par_rho()
int Iterateur_Source_base::equation_divisee_par_rho () const inline
References Nom::debute_par(), and la_zcl.
associer_domaines()
void Iterateur_Source_base::associer_domaines (const Domaine_dis_base & domaine, const Domaine_Cl_dis_base & domaine_cl) inline
References la_zcl, and le_dom.
Referenced by Terme_Puissance_Thermique_DG_base::associer_domaines(), Puissance_Thermique_EF::associer_domaines(), Puissance_Thermique_QC_EF::associer_domaines(), Terme_Puissance_Thermique_PolyMAC_base::associer_domaines(), Terme_Source_Constituant_PolyMAC_Elem::associer_domaines(), Source_Darcy_VDF_Face::associer_domaines(), Source_Echange_Th_VDF::associer_domaines(), Source_Forchheimer_VDF_Face::associer_domaines(), Source_Neutronique_VDF::associer_domaines(), Terme_Gravite_VDF_Face::associer_domaines(), Terme_Puissance_Thermique_VDF_base::associer_domaines(), Terme_Source_Constituant_VDF_Elem::associer_domaines(), Source_Darcy_VEF_Face::associer_domaines(), Source_Forchheimer_VEF_Face::associer_domaines(), Terme_Puissance_Thermique_VEF_base::associer_domaines(), and Terme_Source_Constituant_VEF_Face::associer_domaines().
impr()
virtual int Iterateur_Source_base::impr (Sortie &) const inline virtual
Reimplemented in Iterateur_Source_EF_Som< _TYPE_ >.
References Process::exit().
Referenced by Terme_Source_EF_base::impr().
Member Data Documentation
info_obj
const Type_info Iterateur_Source_base::info_obj static
la_zcl
TRUST_Ref< Domaine_Cl_dis_base *> Iterateur_Source_base::la_zcl protected
Referenced by associer_domaines(), and equation_divisee_par_rho().
le_dom
TRUST_Ref< Domaine_dis_base *> Iterateur_Source_base::le_dom protected
Referenced by associer_domaines(), Iterateur_Source_EF_Som< _TYPE_ >::completer_(), Iterateur_Source_Elem< _TYPE_ >::completer_(), Iterateur_Source_Face< _TYPE_ >::completer_(), Iterateur_Source_VEF_Face< _TYPE_ >::completer_(), Iterateur_Source_VEF_Face< _TYPE_ >::elem_faces(), Iterateur_Source_VEF_Face< _TYPE_ >::face_voisins(), Iterateur_Source_Face< _TYPE_ >::faces_doubles(), Iterateur_Source_VEF_Face< _TYPE_ >::faces_doubles(), and Iterateur_Source_VEF_Face< _TYPE_ >::volumes_entrelaces().
so_base
TRUST_Ref< Source_base *> Iterateur_Source_base::so_base protected
Referenced by associer().