TrioCFD: ParoiVDF_TBLE_LRM Class Reference
ParoiVDF_TBLE_LRM Class Reference
#include <ParoiVDF_TBLE_LRM.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Turbulence_paroi_base
void associer_modele (const Modele_turbulence_hyd_base &)
int calculer_hyd (Champ_Fonc_base &, Champ_Fonc_base &)
int calculer_hyd (Champ_Inc_base &)
const Type_info * get_info () const override
virtual void imprimer_premiere_ligne_ustar (int, const TRUST_List< Nom > &, const Nom &) const
virtual void imprimer_ustar_mean_only (Sortie &, int, const TRUST_List< Nom > &, const Nom &) const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Turbulence_paroi_base
static void typer_lire_turbulence_paroi (TRUST_Deriv< Turbulence_paroi_base > &, const Modele_turbulence_hyd_base &, Entree &)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
.SECTION voir aussi Turbulence_paroi_base
Constructor & Destructor Documentation
~ParoiVDF_TBLE_LRM()
ParoiVDF_TBLE_LRM::~ParoiVDF_TBLE_LRM ()
Member Function Documentation
cree_instance()
Objet_U * ParoiVDF_TBLE_LRM::cree_instance () static
taille_memoire()
unsigned ParoiVDF_TBLE_LRM::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int ParoiVDF_TBLE_LRM::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * ParoiVDF_TBLE_LRM::info () static
get_info()
const Type_info * ParoiVDF_TBLE_LRM::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Paroi_hyd_base_VDF.
self_cast() [1/2]
ParoiVDF_TBLE_LRM & ParoiVDF_TBLE_LRM::self_cast (Objet_U & r) static
self_cast() [2/2]
const ParoiVDF_TBLE_LRM & ParoiVDF_TBLE_LRM::self_cast (const Objet_U & r) static
printOn()
Sortie & ParoiVDF_TBLE_LRM::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Paroi_hyd_base_VDF.
References Objet_U::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & ParoiVDF_TBLE_LRM::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Paroi_hyd_base_VDF.
References avec_boussi, Objet_U::dimension, TRUST_Vector< _CLASSE_ >::dimensionner(), epsilon, Process::exit(), fac, k_init, max_it, modele_visco, nb_comp, nb_post_pts, nb_pts, nom_pts, TRUSTTab< _TYPE_, _SIZE_ >::resize(), Motcles::search(), sonde_tble, and Objet_U_ptr::typer().
init_lois_paroi()
int ParoiVDF_TBLE_LRM::init_lois_paroi () override virtual
2D ////
3D ////
a voir :!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Implements Turbulence_paroi_base.
References Diffu_k::associer_modele_echelles(), Objet_U::axi, Turbulence_paroi_base::Cisaillement_paroi_, Domaine_VF::creer_tableau_faces_bord(), Objet_U::dimension, TRUST_Vector< _CLASSE_ >::dimensionner(), Domaine_VDF::dist_norm_bord(), Domaine_VDF::dist_norm_bord_axi(), Domaine_VF::elem_faces(), epsilon, eq_k_U_W, Process::exit(), fac, Domaine_VF::face_voisins(), Equation_base::inconnue(), k_init, Turbulence_paroi_base::le_dom_Cl_dis_, Turbulence_paroi_base::le_dom_dis_, max_it, Equation_base::milieu(), modele_visco, Turbulence_paroi_base::mon_modele_turb_hyd, nb_comp, Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), nb_post_pts, nb_pts, num_faces_post, num_faces_post2, Front_VF::num_premiere_face(), Domaine_VDF::orientation(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), sonde_tble, TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_Inc_base::valeurs(), and Domaine_VF::xv().
calculer_hyd() [1/2]
int ParoiVDF_TBLE_LRM::calculer_hyd (DoubleTab & tab_k_eps) override virtual
Implements Turbulence_paroi_base.
References avec_boussi, Objet_U::axi, Milieu_base::beta_t(), Operateur_Grad::calculer(), Sources::calculer(), Diffu_totale_base::calculer_a_local(), Mod_echelle_LRM_base::calculer_l_eps(), Mod_echelle_LRM_base::calculer_vv_bar(), Turbulence_paroi_base::Cisaillement_paroi_, Objet_U::dimension, Domaine_VDF::dist_norm(), Domaine_VDF::dist_norm_bord(), Domaine_VDF::dist_norm_bord_axi(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_VF::elem_faces(), eq_k_U_W, Process::exit(), Domaine_VDF::face_normales(), Domaine_VF::face_surfaces(), Domaine_VF::face_voisins(), Paroi_TBLE_QDM_Scal::get_eq_couche_lim_T(), Equation_base::get_modele(), Eq_couch_lim::get_Unp1(), Milieu_base::gravite(), Equation_base::inconnue(), Process::je_suis_maitre(), Turbulence_paroi_base::le_dom_Cl_dis_, Turbulence_paroi_base::le_dom_dis_, TRUSTVect< _TYPE_, _SIZE_ >::local_min_vect(), Modele_turbulence_scal_base::loi_paroi(), max_it, Equation_base::milieu(), Turbulence_paroi_base::mon_modele_turb_hyd, Domaine_VF::nb_faces(), Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), nb_post_pts, nb_pts, nom_pts, Process::nproc(), num_faces_post, Front_VF::num_premiere_face(), Navier_Stokes_std::operateur_gradient(), Domaine_VDF::orientation(), Schema_Temps_base::pas_de_temps(), Schema_Temps_base::pas_temps_min(), Navier_Stokes_std::pression(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), Terme_Boussinesq_base::Scalaire0(), Equation_base::schema_temps(), TRUST_List< _CLASSE_ >::size(), Equation_base::sources(), Turbulence_paroi_base::tab_d_plus_, Turbulence_paroi_base::tab_u_star(), Turbulence_paroi_base::tab_u_star_, Schema_Temps_base::temps_courant(), TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), TRUST_Ref_Objet_U::valeur(), Champ_Don_base::valeurs(), Champ_Inc_base::valeurs(), Fluide_base::viscosite_cinematique(), and Domaine_VF::volumes_entrelaces().
calculer_hyd_BiK()
int ParoiVDF_TBLE_LRM::calculer_hyd_BiK (DoubleTab & tab_k, DoubleTab & tab_eps) override virtual
Implements Turbulence_paroi_base.
References avec_boussi, Objet_U::axi, Milieu_base::beta_t(), Operateur_Grad::calculer(), Sources::calculer(), Diffu_totale_base::calculer_a_local(), Mod_echelle_LRM_base::calculer_l_eps(), Mod_echelle_LRM_base::calculer_vv_bar(), Turbulence_paroi_base::Cisaillement_paroi_, Objet_U::dimension, Domaine_VDF::dist_norm(), Domaine_VDF::dist_norm_bord(), Domaine_VDF::dist_norm_bord_axi(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_VF::elem_faces(), eq_k_U_W, Process::exit(), Domaine_VDF::face_normales(), Domaine_VF::face_surfaces(), Domaine_VF::face_voisins(), Paroi_TBLE_QDM_Scal::get_eq_couche_lim_T(), Equation_base::get_modele(), Eq_couch_lim::get_Unp1(), Milieu_base::gravite(), Equation_base::inconnue(), Process::je_suis_maitre(), Turbulence_paroi_base::le_dom_Cl_dis_, Turbulence_paroi_base::le_dom_dis_, TRUSTVect< _TYPE_, _SIZE_ >::local_min_vect(), Modele_turbulence_scal_base::loi_paroi(), max_it, Equation_base::milieu(), Turbulence_paroi_base::mon_modele_turb_hyd, Domaine_VF::nb_faces(), Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), nb_post_pts, nb_pts, nom_pts, Process::nproc(), num_faces_post, Front_VF::num_premiere_face(), Navier_Stokes_std::operateur_gradient(), Domaine_VDF::orientation(), Schema_Temps_base::pas_de_temps(), Schema_Temps_base::pas_temps_min(), Navier_Stokes_std::pression(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), Terme_Boussinesq_base::Scalaire0(), Equation_base::schema_temps(), TRUST_List< _CLASSE_ >::size(), Equation_base::sources(), Turbulence_paroi_base::tab_d_plus_, Turbulence_paroi_base::tab_u_star(), Turbulence_paroi_base::tab_u_star_, Schema_Temps_base::temps_courant(), TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), TRUST_Ref_Objet_U::valeur(), Champ_Don_base::valeurs(), Champ_Inc_base::valeurs(), Fluide_base::viscosite_cinematique(), and Domaine_VF::volumes_entrelaces().
calculer_hyd() [2/2]
int ParoiVDF_TBLE_LRM::calculer_hyd (DoubleTab & nu_t, DoubleTab & tab_k) override virtual
Implements Turbulence_paroi_base.
References Process::exit().
calculer_sous_couche_log()
int ParoiVDF_TBLE_LRM::calculer_sous_couche_log (DoubleTab & , double , int , int)
get_eq_couch_lim()
Eq_couch_lim & ParoiVDF_TBLE_LRM::get_eq_couch_lim (int i) inline
References eq_k_U_W.
imprimer_ustar()
void ParoiVDF_TBLE_LRM::imprimer_ustar (Sortie & os) const override virtual
Reimplemented from Turbulence_paroi_base.
References Objet_U::dimension, eq_k_U_W, Equation_base::inconnue(), Turbulence_paroi_base::le_dom_dis_, Turbulence_paroi_base::mon_modele_turb_hyd, nb_post_pts, nb_pts, nom_pts, num_faces_post, num_faces_post2, Domaine_VDF::orientation(), Turbulence_paroi_base::tab_u_star(), Champ_base::temps(), TRUST_Ref< _CLASSE_ >::valeur(), and Domaine_VF::xv().
Member Data Documentation
info_obj
const Type_info ParoiVDF_TBLE_LRM::info_obj static
nb_pts
int ParoiVDF_TBLE_LRM::nb_pts protected
Referenced by calculer_hyd(), calculer_hyd_BiK(), imprimer_ustar(), init_lois_paroi(), and readOn().
nb_comp
int ParoiVDF_TBLE_LRM::nb_comp protected
Referenced by init_lois_paroi(), and readOn().
oui_stats
int ParoiVDF_TBLE_LRM::oui_stats protected
max_it
int ParoiVDF_TBLE_LRM::max_it protected
Referenced by calculer_hyd(), calculer_hyd_BiK(), init_lois_paroi(), and readOn().
fac
double ParoiVDF_TBLE_LRM::fac protected
Referenced by init_lois_paroi(), and readOn().
epsilon
double ParoiVDF_TBLE_LRM::epsilon protected
Referenced by init_lois_paroi(), and readOn().
modele_visco
Motcle ParoiVDF_TBLE_LRM::modele_visco protected
Referenced by init_lois_paroi(), and readOn().
eq_k_U_W
TRUST_Vector< Eq_couch_lim > ParoiVDF_TBLE_LRM::eq_k_U_W protected
Referenced by calculer_hyd(), calculer_hyd_BiK(), get_eq_couch_lim(), imprimer_ustar(), and init_lois_paroi().
avec_boussi
int ParoiVDF_TBLE_LRM::avec_boussi protected
Referenced by calculer_hyd(), calculer_hyd_BiK(), and readOn().
k_init
double ParoiVDF_TBLE_LRM::k_init protected
Referenced by init_lois_paroi(), and readOn().
nb_post_pts
int ParoiVDF_TBLE_LRM::nb_post_pts protected
Referenced by calculer_hyd(), calculer_hyd_BiK(), imprimer_ustar(), init_lois_paroi(), and readOn().
sonde_tble
DoubleTab ParoiVDF_TBLE_LRM::sonde_tble protected
Referenced by init_lois_paroi(), and readOn().
nom_pts
Noms ParoiVDF_TBLE_LRM::nom_pts protected
Referenced by calculer_hyd(), calculer_hyd_BiK(), imprimer_ustar(), and readOn().
num_faces_post
IntTab ParoiVDF_TBLE_LRM::num_faces_post protected
Referenced by calculer_hyd(), calculer_hyd_BiK(), imprimer_ustar(), and init_lois_paroi().
num_faces_post2
IntTab ParoiVDF_TBLE_LRM::num_faces_post2 protected
Referenced by imprimer_ustar(), and init_lois_paroi().