TrioCFD: Eval_Puiss_Th_VEF_Face Class Reference
Eval_Puiss_Th_VEF_Face Class Reference
#include <Eval_Puiss_Th_VEF_Face.h>
Member Function Documentation
completer()
void Eval_Puiss_Th_VEF_Face::completer () override virtual
Reimplemented from Evaluateur_Source_Face.
References Evaluateur_Source_VEF_Face::completer(), Evaluateur_Source::le_dom, nb_faces_elem, TRUSTVect< _TYPE_, _SIZE_ >::ref(), tab_volumes, and TRUST_Ref< _CLASSE_ >::valeur().
associer_champs()
void Eval_Puiss_Th_VEF_Face::associer_champs (const Champ_Don_base & Q)
References la_puissance, TRUSTTab< _TYPE_, _SIZE_ >::ref(), tab_puissance, and Champ_Don_base::valeurs().
Referenced by Terme_Puissance_Thermique_VEF_Face::associer_pb().
mettre_a_jour()
void Eval_Puiss_Th_VEF_Face::mettre_a_jour () inline override virtual
Implements Evaluateur_Source.
Member Data Documentation
la_puissance
TRUST_Ref< Champ_Don_base *> Eval_Puiss_Th_VEF_Face::la_puissance protected
Referenced by associer_champs().
tab_puissance
DoubleTab Eval_Puiss_Th_VEF_Face::tab_puissance protected
Referenced by associer_champs(), and Eval_Puiss_Th_VEF_Face_View::set().
tab_volumes
DoubleVect Eval_Puiss_Th_VEF_Face::tab_volumes protected
Referenced by completer(), and Eval_Puiss_Th_VEF_Face_View::set().
nb_faces_elem
int Eval_Puiss_Th_VEF_Face::nb_faces_elem = 0 mutable protected
Referenced by Eval_Puiss_Th_VEF_Face_View::calculer_terme_source_non_standard_view(), Eval_Puiss_Th_VEF_Face_View::calculer_terme_source_standard_view(), completer(), and Eval_Puiss_Th_VEF_Face_View::set().