TrioCFD: Champ_Fonc_Tabule_Morceaux Class Reference
Champ_Fonc_Tabule_Morceaux Class Reference
#include <Champ_Fonc_Tabule_Morceaux.h>
Classes
struct CHTAB
Public Member Functions
const Type_info * get_info () const override
int initialiser (const double temps) override
Public Member Functions inherited from TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC_TABULE >
int initialiser (const double temps) override
void mettre_a_jour (double temps) override
DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const override
DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &valeurs, int le_poly) const override
double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const override
DoubleTab & valeur_aux (const DoubleTab &positions, DoubleTab &valeurs) const override
DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const override
DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const override
DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp) const override
Public Member Functions inherited from Champ_Don_base
void dimensionner (int, int)
int fixer_nb_valeurs_nodales (int nb_noeuds) override
const Type_info * get_info () const override
int imprime (Sortie &, int) const override
virtual int initialiser (const double temps)
void mettre_a_jour (double temps) override
int reprendre (Entree &) override
void resetTime (double time) override
int sauvegarder (Sortie &) const override
DoubleTab & valeurs () override
Public Member Functions inherited from Champ_base
Champ_base & affecter (const Champ_base &)
Champ_base ()
virtual double changer_temps (const double t)
const Type_info * get_info () const override
double temps () const
virtual DoubleTab & trace (const Frontiere_dis_base &, DoubleTab &, double, int distant) const
virtual DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const
virtual double valeur_a_compo (const DoubleVect &position, int ncomp) const
virtual DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &valeurs, int le_poly) const
virtual double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const
virtual DoubleVect & valeur_a_sommet (int, const Domaine &, DoubleVect &) const
virtual DoubleTab & valeur_aux (const DoubleTab &positions, DoubleTab &valeurs) const
virtual DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const
virtual DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const
virtual DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp) const
Public Member Functions inherited from Field_base
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
virtual void fixer_nb_comp (int i)
virtual const Nom & fixer_nom_compo (const Nom &)
virtual const Nom & fixer_nom_compo (int, const Nom &)
virtual const Noms & fixer_noms_compo (const Noms &)
virtual const Nom & fixer_unite (const Nom &)
virtual const Nom & fixer_unite (int i, const Nom &)
virtual const Noms & fixer_unites (const Noms &)
const Type_info * get_info () const override
const Nom & nom_compo (int) const
void nommer (const Nom &) override
const Nom & unite () const
const Nom & unite (int) const
const Noms & unites () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Champ_Proto
int lire_dimension (Entree &, const Nom &)
int lire_dimension (int dim, const Nom &le_nom_)
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Champ_Don_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Field_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
de l'espace et d'un autre champ scalaire passe en parametre .
See also
: TRUSTChamp_Morceaux_generique
Member Typedef Documentation
ArrStr
using Champ_Fonc_Tabule_Morceaux::ArrStr = std::array<std::string, 3> protected
Constructor & Destructor Documentation
Champ_Fonc_Tabule_Morceaux()
Champ_Fonc_Tabule_Morceaux::Champ_Fonc_Tabule_Morceaux ()
~Champ_Fonc_Tabule_Morceaux()
Champ_Fonc_Tabule_Morceaux::~Champ_Fonc_Tabule_Morceaux ()
Member Function Documentation
cree_instance()
Objet_U * Champ_Fonc_Tabule_Morceaux::cree_instance () static
taille_memoire()
unsigned Champ_Fonc_Tabule_Morceaux::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Champ_Fonc_Tabule_Morceaux_Interp.
duplique()
int Champ_Fonc_Tabule_Morceaux::duplique () const override virtual
Implements Objet_U.
Reimplemented in Champ_Fonc_Tabule_Morceaux_Interp.
info()
const Type_info * Champ_Fonc_Tabule_Morceaux::info () static
get_info()
const Type_info * Champ_Fonc_Tabule_Morceaux::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
Reimplemented in Champ_Fonc_Tabule_Morceaux_Interp.
self_cast() [1/2]
Champ_Fonc_Tabule_Morceaux & Champ_Fonc_Tabule_Morceaux::self_cast (Objet_U & r) static
self_cast() [2/2]
const Champ_Fonc_Tabule_Morceaux & Champ_Fonc_Tabule_Morceaux::self_cast (const Objet_U & r) static
printOn()
Sortie & Champ_Fonc_Tabule_Morceaux::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
Reimplemented in Champ_Fonc_Tabule_Morceaux_Interp.
References Champ_Don_base::valeurs().
Referenced by Champ_Fonc_Tabule_Morceaux_Interp::printOn().
readOn()
Entree & Champ_Fonc_Tabule_Morceaux::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
Reimplemented in Champ_Fonc_Tabule_Morceaux_Interp.
References TRUST_Vector< _CLASSE_ >::add(), TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC_TABULE >::domaine(), Process::exit(), Field_base::fixer_nb_comp(), Nom::getString(), i_mor, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC_TABULE >::interprete_get_domaine(), is_interp_, Champ_Fonc_Tabule_Morceaux::CHTAB::la_table, Sous_Domaine_32_64< _SIZE_ >::le_nom(), TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC_TABULE >::les_sous_domaines, Champ_Proto::lire_dimension(), m_pb_ch, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC_TABULE >::mon_domaine, morceaux, Sous_Domaine_32_64< _SIZE_ >::nb_elem_tot(), Objet_U::que_suis_je(), Table::remplir(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), s_pb_ch, and Champ_Don_base::valeurs_.
Referenced by Champ_Fonc_Tabule_Morceaux_Interp::readOn().
mettre_a_jour()
void Champ_Fonc_Tabule_Morceaux::mettre_a_jour (double) override virtual
mettre_a_jour de la classe de base Champ_base :ne fait rien !
Reimplemented from Champ_base.
Reimplemented in Champ_Fonc_Tabule_Morceaux_Interp.
References ch_param, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), TRUSTVect< _TYPE_, _SIZE_ >::get_md_vector(), Champ_Fonc_Tabule_Morceaux::CHTAB::i_ch, i_mor, Champ_Fonc_Tabule_Morceaux::CHTAB::la_table, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC_TABULE >::mon_domaine, morceaux, Table::val(), Table::val_simple(), and Champ_Don_base::valeurs().
initialiser()
int Champ_Fonc_Tabule_Morceaux::initialiser (const double un_temps) override virtual
NE FAIT RIEN.
A surcharger dans les classes derivees. Provoque l'initialisation du champ si necessaire
Reimplemented from Champ_Don_base.
Reimplemented in Champ_Fonc_Tabule_Morceaux_Interp.
References ch_param, TRUSTChamp_Morceaux_generique< _TYPE_ >::initialiser(), m_pb_ch, morceaux, Interprete::objet(), and s_pb_ch.
Member Data Documentation
info_obj
const Type_info Champ_Fonc_Tabule_Morceaux::info_obj static
is_interp_
bool Champ_Fonc_Tabule_Morceaux::is_interp_ = false protected
Referenced by readOn(), and Champ_Fonc_Tabule_Morceaux_Interp::readOn().
s_pb_ch
std::set<ArrStr> Champ_Fonc_Tabule_Morceaux::s_pb_ch protected
Referenced by initialiser(), Champ_Fonc_Tabule_Morceaux_Interp::initialiser(), and readOn().
m_pb_ch
std::vector<std::vector<ArrStr> > Champ_Fonc_Tabule_Morceaux::m_pb_ch protected
Referenced by initialiser(), Champ_Fonc_Tabule_Morceaux_Interp::initialiser(), and readOn().
ch_param
std::vector<const Champ_base *> Champ_Fonc_Tabule_Morceaux::ch_param protected
Referenced by initialiser(), and mettre_a_jour().
morceaux
std::vector<CHTAB> Champ_Fonc_Tabule_Morceaux::morceaux protected
Referenced by initialiser(), Champ_Fonc_Tabule_Morceaux_Interp::initialiser(), mettre_a_jour(), Champ_Fonc_Tabule_Morceaux_Interp::mettre_a_jour(), and readOn().
i_mor
IntVect Champ_Fonc_Tabule_Morceaux::i_mor protected
Referenced by mettre_a_jour(), Champ_Fonc_Tabule_Morceaux_Interp::mettre_a_jour(), and readOn().