TrioCFD: Champ_Front_Composite Class Reference
Champ_Front_Composite Class Reference
#include <Champ_Front_Composite.h>
Public Member Functions
int avancer (double temps) override
const Type_info * get_info () const override
int initialiser (double temps, const Champ_Inc_base &inco) override
void mettre_a_jour (double temps) override
int reculer (double temps) override
void valeurs_face (int, DoubleVect &) const override
Public Member Functions inherited from Champ_front_base
virtual void associer_fr_dis_base (const Frontiere_dis_base &)
virtual int avancer (double temps)
virtual void calculer_coeffs_echange (double temps)
virtual void fixer_nb_valeurs_temporelles (int nb_cases)
virtual Frontiere_dis_base & frontiere_dis ()
virtual const Frontiere_dis_base & frontiere_dis () const
const Type_info * get_info () const override
virtual int initialiser (double temps, const Champ_Inc_base &inco)
virtual void mettre_a_jour (double temps)
virtual int reculer (double temps)
virtual const DoubleTab & valeurs () const override
virtual DoubleTab & valeurs () override
virtual void valeurs_face (int, DoubleVect &) const
Public Member Functions inherited from Field_base
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
virtual void fixer_nb_comp (int i)
virtual const Nom & fixer_nom_compo (const Nom &)
virtual const Nom & fixer_nom_compo (int, const Nom &)
virtual const Noms & fixer_noms_compo (const Noms &)
virtual const Nom & fixer_unite (const Nom &)
virtual const Nom & fixer_unite (int i, const Nom &)
virtual const Noms & fixer_unites (const Noms &)
const Type_info * get_info () const override
const Nom & nom_compo (int) const
void nommer (const Nom &) override
const Nom & unite () const
const Nom & unite (int) const
const Noms & unites () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Champ_Proto
int lire_dimension (Entree &, const Nom &)
int lire_dimension (int dim, const Nom &le_nom_)
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Champ_front_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Field_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Champ_Front_Composite()
Champ_Front_Composite::Champ_Front_Composite ()
~Champ_Front_Composite()
Champ_Front_Composite::~Champ_Front_Composite ()
Member Function Documentation
cree_instance()
Objet_U * Champ_Front_Composite::cree_instance () static
taille_memoire()
unsigned Champ_Front_Composite::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Champ_Front_MUSIG.
duplique()
int Champ_Front_Composite::duplique () const override virtual
Implements Objet_U.
Reimplemented in Champ_Front_MUSIG.
info()
const Type_info * Champ_Front_Composite::info () static
get_info()
const Type_info * Champ_Front_Composite::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
Reimplemented in Champ_Front_MUSIG.
self_cast() [1/2]
Champ_Front_Composite & Champ_Front_Composite::self_cast (Objet_U & r) static
self_cast() [2/2]
const Champ_Front_Composite & Champ_Front_Composite::self_cast (const Objet_U & r) static
printOn()
Sortie & Champ_Front_Composite::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
Reimplemented in Champ_Front_MUSIG.
References Champ_front_base::printOn().
Referenced by Champ_Front_MUSIG::printOn().
readOn()
Entree & Champ_Front_Composite::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
Reimplemented in Champ_Front_MUSIG.
References dim_, Process::exit(), fill_valeurs_composite(), Field_base::fixer_nb_comp(), Champ_front_base::les_valeurs, Field_base::nb_compo_, Field_base::nommer(), Objet_U::que_suis_je(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Roue::valeurs(), and z_fld_.
avancer()
int Champ_Front_Composite::avancer (double temps) inline override virtual
A implementer dans les classes derivees.
Avance en temps : le nouveau temps present sera le temps passe en parametre.
Returns
(int) 1 si OK, 0 sinon
Reimplemented from Champ_front_base.
reculer()
int Champ_Front_Composite::reculer (double temps) inline override virtual
A implementer dans les classes derivees.
Recule en temps : le nouveau temps present sera le temps passe en parametre.
Returns
(int) 1 si OK, 0 sinon
Reimplemented from Champ_front_base.
initialiser()
int Champ_Front_Composite::initialiser (double temps, const Champ_Inc_base & inco) override virtual
Initialisation en debut de calcul.
Imperativement cette methode ne doit pas utiliser de donnees externes a l'equation (couplage). Si mettre_a_jour le fait, alors initialiser ne doit pas appeler mettre_a_jour.
Returns
(0 en cas d'erreur, 1 sinon.)
Reimplemented from Champ_front_base.
References z_fld_.
valeurs_au_temps() [1/2]
DoubleTab & Champ_Front_Composite::valeurs_au_temps (double temps) inline override virtual
Implements Champ_front_base.
References Champ_front_base::les_valeurs, and Roue::valeurs().
mettre_a_jour()
void Champ_Front_Composite::mettre_a_jour (double temps) override virtual
NE FAIT RIEN, a surcharger.
Cette methode est appelee au debut de chaque pas de temps ou sous-pas-de-temps, elle peut eventuellement utiliser des donnees exterieures a l'equation. A charge a l'algorithme de s'assurer que ces donnees sont pertinentes... Calcule la valeur de la condition aux limites au temps demande.
Parameters
(double)
Reimplemented from Champ_front_base.
References z_fld_.
valeurs_face()
void Champ_Front_Composite::valeurs_face (int num_face, DoubleVect & val) const override virtual
Renvoie le vecteur des valeurs du champ pour la face donnee.
Par defaut pour les champs fonc, on suppose que le tableau des valeurs porte nb_faces * nb_compo_ valeurs. Exemple de cas particulier: champ_front_uniforme::valeurs_face
Parameters
(num_face) l'indice d'une face sur la frontiere 0 <= num_face < frontiere_dis().frontiere().nb_faces()
(val) On resize ce tableau et on le remplit.
Reimplemented from Champ_front_base.
References dim_, Field_base::nb_comp(), Field_base::nb_compo_, TRUSTVect< _TYPE_, _SIZE_ >::resize(), TRUSTVect< _TYPE_, _SIZE_ >::size(), and z_fld_.
changer_temps_futur()
void Champ_Front_Composite::changer_temps_futur (double temps, int i) inline override virtual
Change la valeur du temps pour la ieme valeur temporelle apres le present.
Reimplemented from Champ_front_base.
valeurs_au_temps() [2/2]
const DoubleTab & Champ_Front_Composite::valeurs_au_temps (double temps) const inline override virtual
Implements Champ_front_base.
References Champ_front_base::les_valeurs, and Roue::valeurs().
affecter_()
Champ_front_base & Champ_Front_Composite::affecter_ (const Champ_front_base & ch) inline override virtual
Implements Champ_front_base.
fill_valeurs_composite()
void Champ_Front_Composite::fill_valeurs_composite () protected
References dim_, Champ_front_base::les_valeurs, Roue::valeurs(), Champ_front_base::valeurs(), and z_fld_.
Referenced by readOn(), and Champ_Front_MUSIG::readOn().
Member Data Documentation
info_obj
const Type_info Champ_Front_Composite::info_obj static
z_fld_
std::vector<TRUST_Deriv< Champ_front_base > > Champ_Front_Composite::z_fld_ protected
Referenced by fill_valeurs_composite(), initialiser(), mettre_a_jour(), readOn(), Champ_Front_MUSIG::readOn(), and valeurs_face().
dim_
int Champ_Front_Composite::dim_ = -1 protected
Referenced by fill_valeurs_composite(), readOn(), Champ_Front_MUSIG::readOn(), and valeurs_face().