TrioCFD: Pb_Dilatable_base Class Reference
Pb_Dilatable_base Class Reference
#include <Pb_Dilatable_base.h>
Public Member Functions
void associer_milieu_base (const Milieu_base &) override
void associer_sch_tps_base (const Schema_Temps_base &) override
const Type_info * get_info () const override
bool initTimeStep (double dt) override
bool iterateTimeStep (bool &converged) override
void mettre_a_jour (double temps) override
Public Member Functions inherited from Pb_Fluide_base
const Type_info * get_info () const override
Public Member Functions inherited from Probleme_base
void abortTimeStep () override
int associer_ (Objet_U &) override
virtual void associer_domaine (const Domaine &)
virtual void associer_milieu_base (const Milieu_base &)
virtual void associer_sch_tps_base (const Schema_Temps_base &)
virtual double calculer_pas_de_temps () const
virtual void completer ()
double computeTimeStep (bool &stop) const override
const Discretisation_base & discretisation () const
virtual void discretiser (Discretisation_base &)
Domaine & domaine ()
const Domaine & domaine () const
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
Equation_base & equation (const Nom &)
const Equation_base & equation (const Nom &) const
TRUST_Ref< Field_base * > findInputField (const Nom &name) const override
virtual void finir ()
double futureTime () const override
const Type_info * get_info () const override
void getInputFieldsNames (Noms &noms) const override
void getOutputFieldsNames (Noms &noms) const override
virtual void imprimer (Sortie &os) const
void initialize () override
bool initTimeStep (double dt) override
bool isStationary () const override
bool iterateTimeStep (bool &converged) override
int limpr () const override
int lsauv () const override
virtual void mettre_a_jour (double temps)
virtual Milieu_base & milieu ()
virtual const Milieu_base & milieu () const
int postraiter (int force=1) override
double presentTime () const override
int reprendre (Entree &) override
void resetTime (double time) override
int sauvegarder (Sortie &) const override
Schema_Temps_base & schema_temps ()
const Schema_Temps_base & schema_temps () const
void terminate () override
bool updateGivenFields () override
void validateTimeStep () override
virtual int verifier ()
Public Member Functions inherited from Probleme_U
virtual void abortTimeStep ()
virtual double computeTimeStep (bool &stop) const
virtual TRUST_Ref< Field_base * > findInputField (const Nom &name) const
virtual double futureTime () const
const Type_info * get_info () const override
virtual void getInputFieldsNames (Noms &noms) const
virtual void getOutputFieldsNames (Noms &noms) const
virtual void initialize ()
virtual bool initTimeStep (double dt)
virtual bool isStationary () const
virtual bool iterateTimeStep (bool &converged)
const Nom & le_nom () const override
void nommer (const Nom &name) override
virtual int postraiter (int force=1)
virtual double presentTime () const
virtual void resetTime (double time)
virtual bool run ()
virtual bool runUntil (double time)
virtual void terminate ()
virtual bool updateGivenFields ()
virtual void validateTimeStep ()
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Pb_Fluide_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
des problemes dilatables.
See also
Pb_Fluide_base
Constructor & Destructor Documentation
Pb_Dilatable_base()
Pb_Dilatable_base::Pb_Dilatable_base ()
~Pb_Dilatable_base()
Pb_Dilatable_base::~Pb_Dilatable_base () override
Member Function Documentation
info()
const Type_info * Pb_Dilatable_base::info () static
get_info()
const Type_info * Pb_Dilatable_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Probleme_base.
Reimplemented in Pb_Rayo_Thermohydraulique_QC, Pb_Rayo_Thermohydraulique_Turbulent_QC, Pb_Thermohydraulique_Especes_QC, Pb_Thermohydraulique_Especes_WC, Pb_Hydraulique_Melange_Binaire_QC, Pb_QC_base, Pb_Thermohydraulique_QC, Pb_Hydraulique_Melange_Binaire_WC, Pb_Thermohydraulique_WC, Pb_WC_base, Pb_Hydraulique_Melange_Binaire_Turbulent_QC, Pb_Thermohydraulique_Turbulent_QC, and Pb_Thermohydraulique_Especes_Turbulent_QC.
self_cast() [1/2]
Pb_Dilatable_base & Pb_Dilatable_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Pb_Dilatable_base & Pb_Dilatable_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Pb_Dilatable_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Probleme_base.
Reimplemented in TRUSTProblem_sup_eqns< Pb_Thermohydraulique_QC >, TRUSTProblem_sup_eqns< Pb_Thermohydraulique_Turbulent_QC >, TRUSTProblem_sup_eqns< Pb_Thermohydraulique_WC >, Pb_Rayo_Thermohydraulique_QC, Pb_Rayo_Thermohydraulique_Turbulent_QC, Pb_Thermohydraulique_Especes_QC, Pb_Thermohydraulique_Especes_WC, Pb_Hydraulique_Melange_Binaire_QC, Pb_QC_base, Pb_Thermohydraulique_QC, Pb_Hydraulique_Melange_Binaire_WC, Pb_Thermohydraulique_WC, Pb_WC_base, Pb_Hydraulique_Melange_Binaire_Turbulent_QC, Pb_Thermohydraulique_Turbulent_QC, and Pb_Thermohydraulique_Especes_Turbulent_QC.
References Pb_Fluide_base::printOn().
Referenced by Pb_QC_base::printOn(), and Pb_WC_base::printOn().
readOn()
Entree & Pb_Dilatable_base::readOn (Entree & is) override protected virtual
Lecture d'un probleme dans un flot d'entree, et ouverture du flot de sauvegarde.
Format: { nom_milieu bloc de lecture d'un milieu nom_equation bloc de lecture d'une equation Postraitement bloc de lecture postraitement reprise | sauvegarde | sauvegarde_simple formatte | binaire | pdi nom_de_fichier } L'option sauvegarde_simple permet de sauver le probleme dans le fichier choisi en ecrasant a chaque fois les sauvegardes precedentes : cela permet d'economiser de la place disque.
Parameters
(Entree& is) flot d'entree
Returns
(Entree&) le flot d'entre modifie
Exceptions
pas d'accolade ouvrante en debut de format
mot clef "Postraitement" n'est pas la
format de sauvegarde doit etre "binaire" ou "formatte"
pas d'accolade fermante en fin de jeu de donnee
Reimplemented from Probleme_base.
Reimplemented in Pb_Rayo_Thermohydraulique_QC, Pb_Rayo_Thermohydraulique_Turbulent_QC, Pb_Thermohydraulique_Especes_QC, Pb_Thermohydraulique_Especes_WC, Pb_Hydraulique_Melange_Binaire_QC, Pb_QC_base, Pb_Thermohydraulique_QC, Pb_Hydraulique_Melange_Binaire_WC, Pb_Thermohydraulique_WC, Pb_WC_base, Pb_Hydraulique_Melange_Binaire_Turbulent_QC, Pb_Thermohydraulique_Turbulent_QC, Pb_Thermohydraulique_Especes_Turbulent_QC, TRUSTProblem_sup_eqns< Pb_Thermohydraulique_QC >, TRUSTProblem_sup_eqns< Pb_Thermohydraulique_Turbulent_QC >, and TRUSTProblem_sup_eqns< Pb_Thermohydraulique_WC >.
References Pb_Fluide_base::readOn().
Referenced by Pb_QC_base::readOn(), and Pb_WC_base::readOn().
initTimeStep()
bool Pb_Dilatable_base::initTimeStep (double dt) override virtual
This method allocates and initializes the unknown and given fields for the future time step.
The value of the interval is imposed through the parameter dt. In case of error, returns false.
Parameters
(double dt) the time interval to allocate
Returns
(bool) true=OK, false=error, not able to tackle this dt
Exceptions
WrongContext,WrongArgument
Reimplemented from Probleme_base.
References Probleme_base::initTimeStep(), and le_fluide_.
preparer_calcul()
void Pb_Dilatable_base::preparer_calcul () override virtual
Prepare le calcul: initialise les parametres du milieu et prepare le calcul de chacune des equations.
Reimplemented from Probleme_base.
References Fluide_Dilatable_base::calculer_masse_volumique(), Fluide_Dilatable_base::completer(), Probleme_base::equation(), Equation_base::inconnue(), Probleme_base::milieu(), Field_base::nommer(), Probleme_base::preparer_calcul(), Fluide_Dilatable_base::preparer_calcul(), and Fluide_Dilatable_base::type_fluide().
mettre_a_jour()
void Pb_Dilatable_base::mettre_a_jour (double temps) override virtual
Effectue une mise a jour en temps du probleme.
Effectue la mise a jour sur toutes les equations du probleme.
Parameters
(double temps) le pas de temps de mise a jour
Reimplemented from Probleme_base.
References Probleme_base::domaine(), Probleme_base::domaine_dis(), Probleme_base::equation(), Probleme_U::le_nom(), Probleme_base::les_postraitements_, Probleme_base::liste_loi_fermeture_, Equation_base::mettre_a_jour(), Loi_Fermeture_base::mettre_a_jour(), Postraitements::mettre_a_jour(), Domaine_base::mettre_a_jour(), Probleme_base::nombre_d_equations(), and Debog::set_nom_pb_actuel().
associer_milieu_base()
void Pb_Dilatable_base::associer_milieu_base (const Milieu_base & mil) override virtual
Associe un milieu physique aux equations du probleme.
Choix du milieu physique.
Parameters
(Milieu_base& mil) le milieu a associer (Solide, Fluide Incompressible ...)
Reimplemented from Probleme_base.
Reimplemented in Pb_QC_base, Pb_WC_base, TRUSTProblem_sup_eqns< Pb_Thermohydraulique_QC >, TRUSTProblem_sup_eqns< Pb_Thermohydraulique_Turbulent_QC >, and TRUSTProblem_sup_eqns< Pb_Thermohydraulique_WC >.
References Probleme_base::associer_milieu_base(), and le_fluide_.
Referenced by Pb_QC_base::associer_milieu_base(), and Pb_WC_base::associer_milieu_base().
associer_sch_tps_base()
void Pb_Dilatable_base::associer_sch_tps_base (const Schema_Temps_base & un_schema_en_temps) override virtual
Associe un schema en temps au probleme.
Associe ensuite le schema en temps a toutes les equations du probleme.
Parameters
(Schema_Temps_base& un_schema_en_temps) le schema en temps a associer
Reimplemented from Probleme_base.
References Probleme_base::associer_sch_tps_base(), Process::exit(), Probleme_base::is_coupled(), and Objet_U::que_suis_je().
update_pressure_fields()
void Pb_Dilatable_base::update_pressure_fields (double t) virtual
References le_fluide_.
Referenced by iterateTimeStep().
iterateTimeStep()
bool Pb_Dilatable_base::iterateTimeStep (bool & converged) override virtual
In the case solveTimeStep uses an iterative process, this method executes a single iteration.
It is thus possible to modify the given fields between iterations. converged is set to true if the process has converged, ie if the unknown fields are solution to the problem on the next time step. Otherwise converged is set to false. The return value indicates if the convergence process behaves normally. If false, the Problem wishes to abort the time step resolution.
Parameters
(bool& converged) It is a return value : true if the process has converged, false otherwise.
Returns
(bool) true=OK, false=unable to converge
Exceptions
WrongContext
Reimplemented from Probleme_base.
References Statistiques::begin_count(), Domaine_Cl_dis_base::calculer_coeffs_echange(), Equation_base::domaine_Cl_dis(), Statistiques::end_count(), Probleme_base::equation(), Schema_Temps_base::faire_un_pas_de_temps_eqn_base(), Equation_base::inconnue(), le_fluide_, Probleme_U::le_nom(), Milieu_base::mettre_a_jour(), Champ_Inc_base::mettre_a_jour(), Equation_base::milieu(), Probleme_base::nombre_d_equations(), Schema_Temps_base::pas_de_temps(), Champ_Inc_base::reculer(), Probleme_base::schema_temps(), Debog::set_nom_pb_actuel(), Schema_Temps_base::temps_courant(), Schema_Temps_base::temps_defaut(), and update_pressure_fields().
Member Data Documentation
info_obj
const Type_info Pb_Dilatable_base::info_obj static
le_fluide_
TRUST_Ref< Fluide_Dilatable_base *> Pb_Dilatable_base::le_fluide_ protected
Referenced by associer_milieu_base(), initTimeStep(), iterateTimeStep(), and update_pressure_fields().