TrioCFD: KerasLayerConvolution2d Class Reference
KerasLayerConvolution2d Class Reference
#include <keras_model.h>
Constructor & Destructor Documentation
KerasLayerConvolution2d()
KerasLayerConvolution2d::KerasLayerConvolution2d () inline
~KerasLayerConvolution2d()
KerasLayerConvolution2d::~KerasLayerConvolution2d () inline override
Member Function Documentation
LoadLayer()
bool KerasLayerConvolution2d::LoadLayer (std::ifstream * file) override virtual
Implements KerasLayer.
References Tensor::data_, KerasLayerActivation::LoadLayer(), and Tensor::Resize().
Apply()
bool KerasLayerConvolution2d::Apply (Tensor * in, Tensor * out) override virtual
Implements KerasLayer.
References KerasLayerActivation::Apply(), and Tensor::dims_.