TrioCFD: Mass_Redistribution_Phase_Field Class Reference
Mass_Redistribution_Phase_Field Class Reference
#include <Mass_Redistribution_Phase_Field.h>
Constructor & Destructor Documentation
Mass_Redistribution_Phase_Field()
Mass_Redistribution_Phase_Field::Mass_Redistribution_Phase_Field () delete
~Mass_Redistribution_Phase_Field()
Mass_Redistribution_Phase_Field::~Mass_Redistribution_Phase_Field () delete
Member Function Documentation
impose_mass_redistribution()
void Mass_Redistribution_Phase_Field::impose_mass_redistribution (const Domaine_VDF & zvdf, DoubleTab & c_present, DoubleVect minX, DoubleVect maxX) static
References c_ini, Process::check_int_overflow(), MD_Vector_tools::creer_tableau_distribue(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Domaine_dis_base::domaine(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), epsilon_mass_redistribute, TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Domaine_32_64< _SIZE_ >::md_vector_elements(), and Process::mp_sum().
Referenced by RK3_MassRedistrib::faire_un_pas_de_temps_eqn_base(), and Schema_Euler_explicite_Phase_field::faire_un_pas_de_temps_eqn_base().
Member Data Documentation
c_ini
DoubleTab Mass_Redistribution_Phase_Field::c_ini static
Referenced by impose_mass_redistribution().
epsilon_mass_redistribute
double Mass_Redistribution_Phase_Field::epsilon_mass_redistribute = 1.0e-7 static
Referenced by impose_mass_redistribution().