TrioCFD: Source_Dispersion_bulles_base Class Reference
Source_Dispersion_bulles_base Class Reference abstract
#include <Source_Dispersion_bulles_base.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Sources_Multiphase_base
const Type_info * get_info () const override
void mettre_a_jour (double temps) override
Public Member Functions inherited from Source_base
virtual int a_pour_Champ_Fonc (const Motcle &mot, TRUST_Ref< Champ_base * > &ch_ref) const
virtual void associer_champ_rho (const Champ_base &champ_rho)
virtual void completer ()
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
virtual void resetTime (double t)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Sources_Multiphase_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
Cette classe implemente un operateur de dispersion turbulente
 F_{kl} = - F_{lk} = - C_{kl} grad(alpha{k}) + C_{lk} grad(alpha{l}) ou la phase
 l est la phase liquide porteuse et k != 0 une phase quelconque
le calcul de C_{n_l, k} est realise par la hierarchie Dispersion_turbulente_base
See also
Source_base
Constructor & Destructor Documentation
Source_Dispersion_bulles_base()
Source_Dispersion_bulles_base::Source_Dispersion_bulles_base ()
~Source_Dispersion_bulles_base()
Source_Dispersion_bulles_base::~Source_Dispersion_bulles_base () override
Member Function Documentation
info()
const Type_info * Source_Dispersion_bulles_base::info () static
get_info()
const Type_info * Source_Dispersion_bulles_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Source_base.
Reimplemented in Dispersion_bulles_VDF.
self_cast() [1/2]
Source_Dispersion_bulles_base & Source_Dispersion_bulles_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Source_Dispersion_bulles_base & Source_Dispersion_bulles_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Source_Dispersion_bulles_base::printOn (Sortie & os) const override protected virtual
DOES NOTHING - to override in derived classes.
Imprime la source sur un flot de sortie.
Parameters
(Sortie& os) le flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Source_base.
Reimplemented in Dispersion_bulles_VDF.
readOn()
Entree & Source_Dispersion_bulles_base::readOn (Entree & is) override protected virtual
DOES NOTHING - to override in derived classes.
Lecture d'un terme source sur un flot d'entree.
Parameters
(Entree& is) le flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Source_base.
Reimplemented in Dispersion_bulles_VDF.
References Param::ajouter(), beta_, correlation_, MorEqn::equation(), Process::exit(), Probleme_base::get_correlation(), Probleme_base::has_correlation(), Param::lire_avec_accolades_depuis(), Pb_Multiphase::nb_phases(), and Objet_U::que_suis_je().
Referenced by Dispersion_bulles_PolyMAC_P0::readOn(), and Dispersion_bulles_VDF::readOn().
dimensionner_blocs()
void Source_Dispersion_bulles_base::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl = {}) const inline override virtual
Reimplemented from Source_base.
ajouter_blocs()
void Source_Dispersion_bulles_base::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = {}) const override pure virtual
Reimplemented from Source_base.
Implemented in Dispersion_bulles_PolyMAC_P0, and Dispersion_bulles_VDF.
correlation()
const Correlation_base & Source_Dispersion_bulles_base::correlation () const inline
References correlation_, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Dispersion_bulles_PolyMAC_P0::ajouter_blocs().
dimensionner_blocs_aux()
virtual void Source_Dispersion_bulles_base::dimensionner_blocs_aux (IntTab &) const protected pure virtual
Implemented in Dispersion_bulles_PolyMAC_P0, and Dispersion_bulles_VDF.
Member Data Documentation
info_obj
const Type_info Source_Dispersion_bulles_base::info_obj static
correlation_
TRUST_Ref< Correlation_base *> Source_Dispersion_bulles_base::correlation_ protected
Referenced by Dispersion_bulles_PolyMAC_P0::ajouter_blocs(), Dispersion_bulles_VDF::ajouter_blocs(), correlation(), and readOn().
is_turb
int Source_Dispersion_bulles_base::is_turb = 0 protected
Referenced by Dispersion_bulles_PolyMAC_P0::ajouter_blocs(), Dispersion_bulles_VDF::ajouter_blocs(), Dispersion_bulles_PolyMAC_P0::readOn(), and Dispersion_bulles_VDF::readOn().
beta_
double Source_Dispersion_bulles_base::beta_ = 1. protected
Referenced by Dispersion_bulles_PolyMAC_P0::ajouter_blocs(), Dispersion_bulles_VDF::ajouter_blocs(), and readOn().