TrioCFD: TRUSTTabFT_cut_cell< _TYPE_ > Class Template Reference
TRUSTTabFT_cut_cell< _TYPE_ > Class Template Reference
#include <TRUSTTabFT_cut_cell.h>
Additional Inherited Members
Public Member Functions inherited from TRUSTTab< _TYPE_ >
void ref_data (_TYPE_ *ptr, _SIZE_ size) override
void reset () override
Public Member Functions inherited from TRUSTVect< _TYPE_, _SIZE_ >
void ref_data (_TYPE_ *ptr, _SIZE_ new_size) override
TRUSTVect (_SIZE_ n)
TRUSTVect (const TRUSTVect &v)
Public Member Functions inherited from TRUSTArray< _TYPE_, _SIZE_ >
void append_array (_TYPE_ valeur)
void from_tid_to_int (TRUSTArray< int, int > &out) const
TRUSTArray & inject_array (const TRUSTArray &source, _SIZE_ nb_elements=-1, _SIZE_ first_element_dest=0, _SIZE_ first_element_source=0)
TRUSTArray & operator*= (const _TYPE_ dy)
TRUSTArray & operator+= (const _TYPE_ dy)
TRUSTArray & operator+= (const TRUSTArray &y)
TRUSTArray & operator-= (const _TYPE_ dy)
TRUSTArray & operator-= (const TRUSTArray &y)
TRUSTArray & operator/= (const _TYPE_ dy)
TRUSTArray & operator= (_TYPE_ x)
void ref_as_small (TRUSTArray< float, int > &out) const
int ref_count () const
virtual void ref_data (_TYPE_ *ptr, _SIZE_ size)
virtual void reset ()
void set_mem_storage (const STORAGE storage)
_SIZE_ size_array () const
TRUSTArray (const TRUSTArray &A)
Public Member Functions inherited from Array_base
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Sortie & printOn (Sortie &os) const override
Entree & readOn (Entree &is) override
Protected Member Functions inherited from TRUSTArray< _TYPE_, _SIZE_ >
Sortie & printOn (Sortie &os) const override
Entree & readOn (Entree &is) override
void resize_array_ (_SIZE_ n, RESIZE_OPTIONS opt=RESIZE_OPTIONS::COPY_INIT)
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Member Function Documentation
associer_persistant()
template<typename _TYPE_ > void TRUSTTabFT_cut_cell< _TYPE_ >::associer_persistant (Cut_cell_FT_Disc & cut_cell_disc, int dimension)
Referenced by TRUSTTabFT_cut_cell_scalar< _TYPE_ >::associer_persistant(), TRUSTTabFT_cut_cell_vector2< _TYPE_ >::associer_persistant(), TRUSTTabFT_cut_cell_vector3< _TYPE_ >::associer_persistant(), TRUSTTabFT_cut_cell_vector6< _TYPE_ >::associer_persistant(), and Cut_cell_data::associer_persistant().
associer_ephemere()
template<typename _TYPE_ > void TRUSTTabFT_cut_cell< _TYPE_ >::associer_ephemere (Cut_cell_FT_Disc & cut_cell_disc, int dimension)
References Cut_cell_FT_Disc::add_to_transient_data().
Referenced by TRUSTTabFT_cut_cell_scalar< _TYPE_ >::associer_ephemere(), TRUSTTabFT_cut_cell_vector2< _TYPE_ >::associer_ephemere(), TRUSTTabFT_cut_cell_vector3< _TYPE_ >::associer_ephemere(), TRUSTTabFT_cut_cell_vector6< _TYPE_ >::associer_ephemere(), and Cut_cell_data::associer_ephemere().
associer_paresseux()
template<typename _TYPE_ > void TRUSTTabFT_cut_cell< _TYPE_ >::associer_paresseux (Cut_cell_FT_Disc & cut_cell_disc, int dimension)
References Cut_cell_FT_Disc::add_to_lazy_data().
Referenced by TRUSTTabFT_cut_cell_scalar< _TYPE_ >::associer_paresseux(), TRUSTTabFT_cut_cell_vector2< _TYPE_ >::associer_paresseux(), TRUSTTabFT_cut_cell_vector3< _TYPE_ >::associer_paresseux(), TRUSTTabFT_cut_cell_vector6< _TYPE_ >::associer_paresseux(), and Cut_cell_data::associer_paresseux().
get_cut_cell_disc()
template<typename _TYPE_ > const Cut_cell_FT_Disc & TRUSTTabFT_cut_cell< _TYPE_ >::get_cut_cell_disc () const inline
References TRUSTTabFT_cut_cell< _TYPE_ >::cut_cell_disc_, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Cut_cell_surface_efficace::calcul_surface_face_efficace_initiale(), Cut_cell_surface_efficace::calcul_surface_face_efficace_iteratif(), Cut_cell_surface_efficace::calcul_surface_interface_efficace(), Cut_cell_surface_efficace::calcul_surface_interface_efficace_initiale(), Cut_cell_surface_efficace::calcul_vitesse_interface(), IJK_Interfaces::imprime_bilan_indicatrice(), Cut_cell_surface_efficace::imprimer_informations_surface_efficace_face(), and Cut_cell_surface_efficace::imprimer_informations_surface_efficace_interface().
sort_tot() [1/2]
template<typename _TYPE_ > void TRUSTTabFT_cut_cell< _TYPE_ >::sort_tot (int colum)
Referenced by Cut_cell_FT_Disc::update_index_sorted_by_indicatrice(), Cut_cell_FT_Disc::update_index_sorted_by_k(), and Cut_cell_FT_Disc::update_index_sorted_by_statut_diphasique().
sort_tot() [2/2]
template<typename _TYPE_ > void TRUSTTabFT_cut_cell< _TYPE_ >::sort_tot (int column_1, int column_2)
echange_espace_virtuel() [1/2]
template<typename _TYPE_ > void TRUSTTabFT_cut_cell< _TYPE_ >::echange_espace_virtuel override virtual
Reimplemented from TRUSTVect< _TYPE_, _SIZE_ >.
Referenced by Cut_cell_surface_efficace::calcul_surface_face_efficace_iteratif(), Cut_cell_surface_efficace::calcul_surface_interface_efficace(), Cut_cell_surface_efficace::calcul_vitesse_interface(), and Cut_cell_data::echange_espace_virtuel().
echange_espace_virtuel() [2/2]
template<typename _TYPE_ > void TRUSTTabFT_cut_cell< _TYPE_ >::echange_espace_virtuel (MD_Vector_tools::Operations_echange op)
Member Data Documentation
cut_cell_disc_
template<typename _TYPE_ > TRUST_Ref< Cut_cell_FT_Disc *> TRUSTTabFT_cut_cell< _TYPE_ >::cut_cell_disc_ protected
Referenced by TRUSTTabFT_cut_cell< _TYPE_ >::get_cut_cell_disc().