TrioCFD: Solveur_Implicite_base Class Reference
Solveur_Implicite_base Class Reference abstract
#include <Solveur_Implicite_base.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Solveur_Implicite_base()
Solveur_Implicite_base::Solveur_Implicite_base ()
~Solveur_Implicite_base()
Solveur_Implicite_base::~Solveur_Implicite_base () override
Member Function Documentation
info()
const Type_info * Solveur_Implicite_base::info () static
get_info()
const Type_info * Solveur_Implicite_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
Reimplemented in Implicite_ALE, Implicit_steady, Solveur_lineaire, Solveur_Lineaire_Std, Solveur_non_lineaire, SETS, ICE, Piso, Implicite, Simple, Simpler, Simpler_Base, and Solveur_U_P.
self_cast() [1/2]
Solveur_Implicite_base & Solveur_Implicite_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Solveur_Implicite_base & Solveur_Implicite_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Solveur_Implicite_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
Reimplemented in Implicite_ALE, Implicit_steady, Solveur_lineaire, Solveur_Lineaire_Std, Solveur_non_lineaire, SETS, ICE, Piso, Implicite, Simple, Simpler, Simpler_Base, and Solveur_U_P.
Referenced by Solveur_lineaire::printOn(), and Solveur_non_lineaire::printOn().
readOn()
Entree & Solveur_Implicite_base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
Reimplemented in Implicite_ALE, Implicit_steady, Solveur_lineaire, Solveur_Lineaire_Std, Solveur_non_lineaire, SETS, ICE, Piso, Implicite, Simple, Simpler, Simpler_Base, and Solveur_U_P.
Referenced by Solveur_lineaire::readOn(), and Solveur_non_lineaire::readOn().
iterer_eqn()
virtual bool Solveur_Implicite_base::iterer_eqn (Equation_base & equation, const DoubleTab & inconnue, DoubleTab & result, double dt, int numero_iteration, int & ok) pure virtual
Implemented in Solveur_Lineaire_Std, SETS, Simple, and Simpler_Base.
Referenced by Schema_Euler_Implicite::faire_un_pas_de_temps_eqn_base(), Schema_Implicite_Multi_TimeStep_base::faire_un_pas_de_temps_eqn_base(), Schema_Euler_Implicite::faire_un_pas_de_temps_pb_couple(), Schema_Implicite_Multi_TimeStep_base::Iterer_Pb(), and Schema_Euler_Implicite::Iterer_Pb().
iterer_eqs()
bool Solveur_Implicite_base::iterer_eqs (TRUST_List< TRUST_Ref< Equation_base * > > eqs, int n, int & ok) virtual
Reimplemented in Simple.
References Process::exit().
Referenced by Schema_Euler_Implicite::faire_un_pas_de_temps_pb_couple().
est_compatible_avec_th_mono()
virtual bool Solveur_Implicite_base::est_compatible_avec_th_mono () const inline virtual
Reimplemented in ICE.
Referenced by Schema_Euler_Implicite::readOn().
nb_valeurs_temporelles_pression()
virtual int Solveur_Implicite_base::nb_valeurs_temporelles_pression () const inline virtual
Reimplemented in SETS.
get_default_facsec_max()
virtual double Solveur_Implicite_base::get_default_facsec_max () const inline virtual
Reimplemented in ICE.
Referenced by Schema_Euler_Implicite::readOn().
get_default_growth_factor()
virtual double Solveur_Implicite_base::get_default_growth_factor () const inline virtual
Reimplemented in SETS.
Referenced by Schema_Euler_Implicite::readOn().
get_and_set_parametre_equation()
virtual TRUST_Deriv< Parametre_equation_base > & Solveur_Implicite_base::get_and_set_parametre_equation (Equation_base & eqn) inline virtual
Reimplemented in Simpler_Base.
References Equation_base::parametre_equation().
Member Data Documentation
info_obj
const Type_info Solveur_Implicite_base::info_obj static