TrioCFD: Correction_Tomiyama_PolyMAC_P0 Class Reference
Correction_Tomiyama_PolyMAC_P0 Class Reference
#include <Correction_Tomiyama_PolyMAC_P0.h>
Public Member Functions
void completer () override
const Type_info * get_info () const override
void mettre_a_jour (double temps) override
Public Member Functions inherited from Source_base
virtual int a_pour_Champ_Fonc (const Motcle &mot, TRUST_Ref< Champ_base * > &ch_ref) const
virtual void associer_champ_rho (const Champ_base &champ_rho)
virtual void completer ()
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
virtual void resetTime (double t)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Correction_Tomiyama_PolyMAC_P0()
Correction_Tomiyama_PolyMAC_P0::Correction_Tomiyama_PolyMAC_P0 ()
~Correction_Tomiyama_PolyMAC_P0()
Correction_Tomiyama_PolyMAC_P0::~Correction_Tomiyama_PolyMAC_P0 ()
Member Function Documentation
cree_instance()
Objet_U * Correction_Tomiyama_PolyMAC_P0::cree_instance () static
taille_memoire()
unsigned Correction_Tomiyama_PolyMAC_P0::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Correction_Tomiyama_PolyMAC_P0::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Correction_Tomiyama_PolyMAC_P0::info () static
get_info()
const Type_info * Correction_Tomiyama_PolyMAC_P0::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Source_base.
self_cast() [1/2]
Correction_Tomiyama_PolyMAC_P0 & Correction_Tomiyama_PolyMAC_P0::self_cast (Objet_U & r) static
self_cast() [2/2]
const Correction_Tomiyama_PolyMAC_P0 & Correction_Tomiyama_PolyMAC_P0::self_cast (const Objet_U & r) static
printOn()
Sortie & Correction_Tomiyama_PolyMAC_P0::printOn (Sortie & os) const override protected virtual
DOES NOTHING - to override in derived classes.
Imprime la source sur un flot de sortie.
Parameters
(Sortie& os) le flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Source_base.
readOn()
Entree & Correction_Tomiyama_PolyMAC_P0::readOn (Entree & is) override protected virtual
DOES NOTHING - to override in derived classes.
Lecture d'un terme source sur un flot d'entree.
Parameters
(Entree& is) le flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Source_base.
References Param::ajouter(), Probleme_base::creer_champ(), Nom::debute_par(), MorEqn::equation(), Process::exit(), Param::lire_avec_accolades_depuis(), n_l, Pb_Multiphase::nb_phases(), Pb_Multiphase::nom_phase(), Objet_U::que_suis_je(), and secu_diam_.
has_interface_blocs()
int Correction_Tomiyama_PolyMAC_P0::has_interface_blocs () const inline override virtual
Reimplemented from Source_base.
dimensionner_blocs()
void Correction_Tomiyama_PolyMAC_P0::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl = {}) const inline override virtual
Reimplemented from Source_base.
ajouter_blocs()
void Correction_Tomiyama_PolyMAC_P0::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = {}) const override virtual
Reimplemented from Source_base.
References Objet_U::dimension, MorEqn::equation(), Champ_Face_base::fcl(), g_, Probleme_base::get_champ(), Milieu_composite::get_interface(), Milieu_composite::get_saturation(), Interface_base::get_sigma_tab(), Milieu_composite::has_interface(), Milieu_composite::has_saturation(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Milieu_base::masse_volumique(), Equation_base::milieu(), n_l, Champ_Proto::passe(), Champ_Inc_base::passe(), Milieu_base::porosite_elem(), Milieu_base::porosite_face(), Equation_base::probleme(), secu_diam_, and Champ_Proto::valeurs().
check_multiphase_compatibility()
void Correction_Tomiyama_PolyMAC_P0::check_multiphase_compatibility () const inline override virtual
Reimplemented from MorEqn.
completer()
void Correction_Tomiyama_PolyMAC_P0::completer () override virtual
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees: Source_base::associer_domaines(const Domaine_dis_base& ,const Domaine_Cl_dis_base&) Source_base::associer_pb(const Probleme_base&)
Reimplemented from Source_base.
References MorEqn::equation(), Process::exit(), and Probleme_base::has_champ().
associer_domaines()
void Correction_Tomiyama_PolyMAC_P0::associer_domaines (const Domaine_dis_base & , const Domaine_Cl_dis_base &) inline override virtual
Implements Source_base.
associer_pb()
void Correction_Tomiyama_PolyMAC_P0::associer_pb (const Probleme_base &) inline override virtual
Implements Source_base.
mettre_a_jour()
void Correction_Tomiyama_PolyMAC_P0::mettre_a_jour (double temps) inline override virtual
DOES NOTHING - to override in derived classes.
Mise a jour en temps du terme source.
Parameters
(double) le pas de temps de mise a jour
Reimplemented from Source_base.
Member Data Documentation
info_obj
const Type_info Correction_Tomiyama_PolyMAC_P0::info_obj static
n_l
int Correction_Tomiyama_PolyMAC_P0::n_l = -1 protected
Referenced by ajouter_blocs(), and readOn().
is_turb
int Correction_Tomiyama_PolyMAC_P0::is_turb = 0 protected
g_
double Correction_Tomiyama_PolyMAC_P0::g_ = 9.81 protected
Referenced by ajouter_blocs().
secu_diam_
double Correction_Tomiyama_PolyMAC_P0::secu_diam_ = 0.1 protected
Referenced by ajouter_blocs(), and readOn().