TrioCFD: Paroi_std_hyd_VEF_3couches Class Reference
Paroi_std_hyd_VEF_3couches Class Reference
#include <Paroi_std_hyd_VEF_3couches.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Turbulence_paroi_base
void associer_modele (const Modele_turbulence_hyd_base &)
int calculer_hyd (Champ_Fonc_base &, Champ_Fonc_base &)
int calculer_hyd (Champ_Inc_base &)
const Type_info * get_info () const override
virtual void imprimer_premiere_ligne_ustar (int, const TRUST_List< Nom > &, const Nom &) const
virtual void imprimer_ustar_mean_only (Sortie &, int, const TRUST_List< Nom > &, const Nom &) const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Turbulence_paroi_base
static void typer_lire_turbulence_paroi (TRUST_Deriv< Turbulence_paroi_base > &, const Modele_turbulence_hyd_base &, Entree &)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
.SECTION voir aussi Turbulence_paroi_base
Constructor & Destructor Documentation
Paroi_std_hyd_VEF_3couches()
Paroi_std_hyd_VEF_3couches::Paroi_std_hyd_VEF_3couches ()
~Paroi_std_hyd_VEF_3couches()
Paroi_std_hyd_VEF_3couches::~Paroi_std_hyd_VEF_3couches ()
Member Function Documentation
cree_instance()
Objet_U * Paroi_std_hyd_VEF_3couches::cree_instance () static
taille_memoire()
unsigned Paroi_std_hyd_VEF_3couches::taille_memoire () const override virtual
Reimplemented from Paroi_std_hyd_VEF.
duplique()
int Paroi_std_hyd_VEF_3couches::duplique () const override virtual
Reimplemented from Paroi_std_hyd_VEF.
info()
const Type_info * Paroi_std_hyd_VEF_3couches::info () static
get_info()
const Type_info * Paroi_std_hyd_VEF_3couches::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Paroi_std_hyd_VEF.
self_cast() [1/2]
Paroi_std_hyd_VEF_3couches & Paroi_std_hyd_VEF_3couches::self_cast (Objet_U & r) static
self_cast() [2/2]
const Paroi_std_hyd_VEF_3couches & Paroi_std_hyd_VEF_3couches::self_cast (const Objet_U & r) static
printOn()
Sortie & Paroi_std_hyd_VEF_3couches::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Paroi_std_hyd_VEF.
References Objet_U::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Paroi_std_hyd_VEF_3couches::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Paroi_std_hyd_VEF.
References Paroi_std_hyd_VEF::readOn().
calculer_k_eps()
int Paroi_std_hyd_VEF_3couches::calculer_k_eps (double & k, double & eps, double yp, double u_star, double d_visco, double dist) override virtual
Reimplemented from Paroi_std_hyd_VEF.
References Paroi_log_QDM::calcul_lm_plus(), Paroi_log_QDM::Cmu_, and Paroi_log_QDM::Kappa_.
Member Data Documentation
info_obj
const Type_info Paroi_std_hyd_VEF_3couches::info_obj static