TrioCFD: Op_Diff_VDF_Face Class Reference
Op_Diff_VDF_Face Class Reference
#include <Op_Diff_VDF_Face_leaves.h>
Public Member Functions
void completer () override
const Type_info * get_info () const override
void mettre_a_jour (double) override
Public Member Functions inherited from Op_Diff_VDF_Face_base
double calculer_dt_stab () const override
const Type_info * get_info () const override
void modifier_pour_Cl (Matrice_Morse &matrice, DoubleTab &secmem) const override
Public Member Functions inherited from Op_Diff_VDF_base
void completer () override
void contribuer_au_second_membre (DoubleTab &resu) const override
const Type_info * get_info () const override
int impr (Sortie &os) const override
Public Member Functions inherited from Operateur_Diff_base
virtual void associer_diffusivite_pour_pas_de_temps (const Champ_base &)
const Type_info * get_info () const override
Public Member Functions inherited from Operateur_base
void associer_eqn (const Equation_base &)
virtual double calculer_dt_stab () const
virtual void completer ()
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual void mettre_a_jour (double temps)
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Operateur_Diff_base
virtual const Champ_base & diffusivite_pour_pas_de_temps () const
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
La discretisation est VDF. Le champ diffuse est un Champ_Face_VDF. Le champ de diffusivite n'est pas uniforme L'iterateur associe est de type Iterateur_VDF_Face. L'evaluateur associe est de type Eval_Diff_VDF_Face
Constructor & Destructor Documentation
~Op_Diff_VDF_Face()
Op_Diff_VDF_Face::~Op_Diff_VDF_Face ()
Op_Diff_VDF_Face()
Op_Diff_VDF_Face::Op_Diff_VDF_Face ()
References Support_Champ_Masse_Volumique::declare_support_masse_volumique().
Member Function Documentation
cree_instance()
Objet_U * Op_Diff_VDF_Face::cree_instance () static
taille_memoire()
unsigned Op_Diff_VDF_Face::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Op_Diff_VDF_Face::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Op_Diff_VDF_Face::info () static
get_info()
const Type_info * Op_Diff_VDF_Face::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Op_Diff_VDF_Face_base.
self_cast() [1/2]
Op_Diff_VDF_Face & Op_Diff_VDF_Face::self_cast (Objet_U & r) static
self_cast() [2/2]
const Op_Diff_VDF_Face & Op_Diff_VDF_Face::self_cast (const Objet_U & r) static
printOn()
Sortie & Op_Diff_VDF_Face::printOn (Sortie & os) const override protected virtual
DOES NOTHING - to override in derived classes.
Imprime l'operateur sur un flot de sortie.
Parameters
(Sortie& os) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Op_Diff_VDF_Face_base.
References Objet_U::que_suis_je().
readOn()
Entree & Op_Diff_VDF_Face::readOn (Entree & is) override protected virtual
DOES NOTHING - to override in derived classes.
Lit un operateur sur un flot d'entree.
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Op_Diff_VDF_Face_base.
associer()
void Op_Diff_VDF_Face::associer (const Domaine_dis_base & zd, const Domaine_Cl_dis_base & zcd, const Champ_Inc_base & ch) inline override virtual
Implements Operateur_base.
associer_diffusivite()
void Op_Diff_VDF_Face::associer_diffusivite (const Champ_base & ch) inline override virtual
Implements Operateur_Diff_base.
diffusivite()
const Champ_base & Op_Diff_VDF_Face::diffusivite () const inline override virtual
Implements Operateur_Diff_base.
mettre_a_jour()
void Op_Diff_VDF_Face::mettre_a_jour (double temps) inline override virtual
DOES NOTHING - to override in derived classes.
Mise a jour de l'operateur
Parameters
(double) un pas de temps
Reimplemented from Operateur_base.
completer()
void Op_Diff_VDF_Face::completer () inline override virtual
Associe l'operateur au domaine_dis, le domaine_Cl_dis, et a l'inconnue de son equation.
Exceptions
pas d'equation associee
Reimplemented from Op_Diff_VDF_base.
References Op_Diff_VDF_base::completer(), and MorEqn::equation().
Member Data Documentation
info_obj
const Type_info Op_Diff_VDF_Face::info_obj static