TrioCFD: IJK_SolveSys_FD_thermal Class Reference
IJK_SolveSys_FD_thermal Class Reference
#include <IJK_SolveSys_FD_thermal.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from SolveurSys
const Type_info * get_info () const override
const Nom & le_nom () const override
void nommer (const Nom &nom) override
Public Member Functions inherited from Objet_U_ptr
int associer_ (Objet_U &objet) override
const Type_info * get_info () const override
const Nom & le_nom () const override
Objet_U * typer (const char *nom_type)
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from TRUST_Deriv< SolveurSys_base >
Sortie & printOn (Sortie &os) const override
Entree & readOn (Entree &is) override
Protected Member Functions inherited from Objet_U_ptr
int change_num (const int *const) override
Objet_U * get_Objet_U_ptr_check () const
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
void recopie (const Objet_U &)
~Objet_U_ptr () override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
IJK_SolveSys_FD_thermal()
IJK_SolveSys_FD_thermal::IJK_SolveSys_FD_thermal ()
~IJK_SolveSys_FD_thermal()
IJK_SolveSys_FD_thermal::~IJK_SolveSys_FD_thermal ()
Member Function Documentation
cree_instance()
Objet_U * IJK_SolveSys_FD_thermal::cree_instance () static
taille_memoire()
unsigned IJK_SolveSys_FD_thermal::taille_memoire () const override virtual
Reimplemented from SolveurSys.
duplique()
int IJK_SolveSys_FD_thermal::duplique () const override virtual
Reimplemented from SolveurSys.
info()
const Type_info * IJK_SolveSys_FD_thermal::info () static
get_info()
const Type_info * IJK_SolveSys_FD_thermal::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from SolveurSys.
self_cast() [1/2]
IJK_SolveSys_FD_thermal & IJK_SolveSys_FD_thermal::self_cast (Objet_U & r) static
self_cast() [2/2]
const IJK_SolveSys_FD_thermal & IJK_SolveSys_FD_thermal::self_cast (const Objet_U & r) static
printOn()
Sortie & IJK_SolveSys_FD_thermal::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from SolveurSys.
References SolveurSys::printOn().
readOn()
Entree & IJK_SolveSys_FD_thermal::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from SolveurSys.
References Param::ajouter(), cast_direct_solver_by_default(), cast_iterative_solver_by_default(), Nom::debute_par(), Nom::getString(), Param::lire_sans_accolade(), SolveurSys::nommer(), Objet_U::que_suis_je(), Param::REQUIRED, Objet_U_ptr::typer(), and TRUST_Deriv< SolveurSys_base >::valeur().
cast_iterative_solver_by_default()
void IJK_SolveSys_FD_thermal::cast_iterative_solver_by_default ()
References iterative_solver_by_default_, SolveurSys::nommer(), solv_iteratif::set_seuil(), Objet_U_ptr::typer(), and TRUST_Deriv< SolveurSys_base >::valeur().
Referenced by readOn().
cast_direct_solver_by_default()
void IJK_SolveSys_FD_thermal::cast_direct_solver_by_default ()
References direct_solver_by_default_, Nom::getChar(), SolveurSys::le_nom(), Objet_U::nommer(), SolveurSys::nommer(), petsc_solver_by_default_, Objet_U_ptr::typer(), and TRUST_Deriv< SolveurSys_base >::valeur().
Referenced by IJK_Thermal_Subresolution::initialize(), readOn(), and IJK_Thermal_Subresolution::solve_thermal_subproblems().
Member Data Documentation
info_obj
const Type_info IJK_SolveSys_FD_thermal::info_obj static
iterative_solver_by_default_
Nom IJK_SolveSys_FD_thermal::iterative_solver_by_default_ = "Solv_Gmres" protected
Referenced by cast_iterative_solver_by_default().
direct_solver_by_default_
Nom IJK_SolveSys_FD_thermal::direct_solver_by_default_ = "Solv_Petsc" protected
Referenced by cast_direct_solver_by_default().
petsc_solver_by_default_
Nom IJK_SolveSys_FD_thermal::petsc_solver_by_default_ = "LU" protected
Referenced by cast_direct_solver_by_default().