TrioCFD: Source_Transport_K_Eps_Bas_Reynolds_aniso_therm_concen_VDF_Elem Class Reference
Source_Transport_K_Eps_Bas_Reynolds_aniso_therm_concen_VDF_Elem Class Reference
#include <Source_Transport_K_Eps_Bas_Reynolds_aniso_therm_concen_VDF_Elem.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Source_Transport_K_Eps_Bas_Reynolds_VDF_Elem
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Source_Transport_VDF_Elem_base
const Type_info * get_info () const override
void mettre_a_jour (double t) override
Public Member Functions inherited from Source_base
virtual int a_pour_Champ_Fonc (const Motcle &mot, TRUST_Ref< Champ_base * > &ch_ref) const
virtual void associer_champ_rho (const Champ_base &champ_rho)
virtual void completer ()
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
virtual void resetTime (double t)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Source_Transport_K_Eps_Bas_Reynolds_VDF_Elem
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
~Source_Transport_K_Eps_Bas_Reynolds_aniso_therm_concen_VDF_Elem()
Source_Transport_K_Eps_Bas_Reynolds_aniso_therm_concen_VDF_Elem::~Source_Transport_K_Eps_Bas_Reynolds_aniso_therm_concen_VDF_Elem ()
Source_Transport_K_Eps_Bas_Reynolds_aniso_therm_concen_VDF_Elem()
Source_Transport_K_Eps_Bas_Reynolds_aniso_therm_concen_VDF_Elem::Source_Transport_K_Eps_Bas_Reynolds_aniso_therm_concen_VDF_Elem (double cte1 = C11__, double cte2 = C21__) inline
Member Function Documentation
cree_instance()
Objet_U * Source_Transport_K_Eps_Bas_Reynolds_aniso_therm_concen_VDF_Elem::cree_instance () static
taille_memoire()
unsigned Source_Transport_K_Eps_Bas_Reynolds_aniso_therm_concen_VDF_Elem::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Source_Transport_K_Eps_Bas_Reynolds_aniso_therm_concen_VDF_Elem::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Source_Transport_K_Eps_Bas_Reynolds_aniso_therm_concen_VDF_Elem::info () static
get_info()
const Type_info * Source_Transport_K_Eps_Bas_Reynolds_aniso_therm_concen_VDF_Elem::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Source_Transport_Bas_Reynolds_VDF_Elem_base.
self_cast() [1/2]
Source_Transport_K_Eps_Bas_Reynolds_aniso_therm_concen_VDF_Elem & Source_Transport_K_Eps_Bas_Reynolds_aniso_therm_concen_VDF_Elem::self_cast (Objet_U & r) static
self_cast() [2/2]
const Source_Transport_K_Eps_Bas_Reynolds_aniso_therm_concen_VDF_Elem & Source_Transport_K_Eps_Bas_Reynolds_aniso_therm_concen_VDF_Elem::self_cast (const Objet_U & r) static
printOn()
Sortie & Source_Transport_K_Eps_Bas_Reynolds_aniso_therm_concen_VDF_Elem::printOn (Sortie & os) const override protected virtual
DOES NOTHING - to override in derived classes.
Imprime la source sur un flot de sortie.
Parameters
(Sortie& os) le flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Source_Transport_Bas_Reynolds_VDF_Elem_base.
References Objet_U::que_suis_je().
readOn()
Entree & Source_Transport_K_Eps_Bas_Reynolds_aniso_therm_concen_VDF_Elem::readOn (Entree & is) override protected virtual
DOES NOTHING - to override in derived classes.
Lecture d'un terme source sur un flot d'entree.
Parameters
(Entree& is) le flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Source_Transport_Bas_Reynolds_VDF_Elem_base.
ajouter_blocs()
void Source_Transport_K_Eps_Bas_Reynolds_aniso_therm_concen_VDF_Elem::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl) const override virtual
Reimplemented from Source_Transport_Bas_Reynolds_VDF_Elem_base.
References Modele_turbulence_hyd_RANS_K_Eps_base::associe_modele_fonction(), Objet_U::axi, Source_Transport_proto::beta_c, Source_Transport_proto::beta_t, Source_Transport_proto::C1, Source_Transport_proto::C2, Modele_Fonc_Bas_Reynolds_Base::Calcul_D(), Modele_Fonc_Bas_Reynolds_Base::Calcul_E(), Modele_Fonc_Bas_Reynolds_Base::Calcul_F2(), Calcul_Production_K_VDF::calculer_terme_destruction_K(), Calcul_Production_K_VDF::calculer_terme_production_K(), Calcul_Production_K_VDF::calculer_terme_production_K_Axi(), Modele_turbulence_scal_base::diffusivite_turbulente(), Source_Transport_proto::eq_concentration, Source_Transport_proto::eq_hydraulique, Source_Transport_proto::eq_thermique, Source_Transport_Bas_Reynolds_VDF_Elem_base::eqn_keps_bas_re, Source_Transport_proto::gravite, Source_Transport_VDF_Elem_base::le_dom_Cl_VDF, Domaine_dis_base::nb_elem(), Domaine_dis_base::nb_elem_tot(), TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), Fluide_base::viscosite_cinematique(), and Domaine_VF::volumes().
associer_pb()
void Source_Transport_K_Eps_Bas_Reynolds_aniso_therm_concen_VDF_Elem::associer_pb (const Probleme_base & pb) override virtual
Reimplemented from Source_Transport_Bas_Reynolds_VDF_Elem_base.
References Source_Transport_Bas_Reynolds_VDF_Elem_base::associer_pb(), Source_Transport_proto::associer_pb_anisotherme_concen(), Objet_U::que_suis_je(), and Source_Transport_proto::verifier_milieu_anisotherme_concen().
Member Data Documentation
info_obj
const Type_info Source_Transport_K_Eps_Bas_Reynolds_aniso_therm_concen_VDF_Elem::info_obj static