TrioCFD: Modele_Shih_Zhu_Lumley_VDF Class Reference
Modele_Shih_Zhu_Lumley_VDF Class Reference
#include <Modele_Shih_Zhu_Lumley_VDF.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Modele_Fonc_Realisable_base
const Type_info * get_info () const override
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Modele_Fonc_Realisable_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Modele_Shih_Zhu_Lumley_VDF()
Modele_Shih_Zhu_Lumley_VDF::Modele_Shih_Zhu_Lumley_VDF ()
~Modele_Shih_Zhu_Lumley_VDF()
Modele_Shih_Zhu_Lumley_VDF::~Modele_Shih_Zhu_Lumley_VDF ()
Member Function Documentation
cree_instance()
Objet_U * Modele_Shih_Zhu_Lumley_VDF::cree_instance () static
taille_memoire()
unsigned Modele_Shih_Zhu_Lumley_VDF::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Modele_Shih_Zhu_Lumley_VDF::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Modele_Shih_Zhu_Lumley_VDF::info () static
get_info()
const Type_info * Modele_Shih_Zhu_Lumley_VDF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
Modele_Shih_Zhu_Lumley_VDF & Modele_Shih_Zhu_Lumley_VDF::self_cast (Objet_U & r) static
self_cast() [2/2]
const Modele_Shih_Zhu_Lumley_VDF & Modele_Shih_Zhu_Lumley_VDF::self_cast (const Objet_U & r) static
printOn()
Sortie & Modele_Shih_Zhu_Lumley_VDF::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
readOn()
Entree & Modele_Shih_Zhu_Lumley_VDF::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
References Modele_Fonc_Realisable_base::is_Cmu_constant_, Param::lire_avec_accolades_depuis(), Objet_U::que_suis_je(), and set_param().
set_param()
void Modele_Shih_Zhu_Lumley_VDF::set_param (Param & param) virtual
References A0_, and Param::ajouter().
Referenced by readOn().
mettre_a_jour()
void Modele_Shih_Zhu_Lumley_VDF::mettre_a_jour (double temps) override virtual
Implements Modele_Fonc_Realisable_base.
Calcul_S()
void Modele_Shih_Zhu_Lumley_VDF::Calcul_S (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const DoubleTab & vitesse) override virtual
Implements Modele_Fonc_Realisable_base.
References Objet_U::dimension, Modele_Fonc_Realisable_base::eq_hydraulique, TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Domaine_dis_base::nb_elem_tot(), nelem_, Modele_Fonc_Realisable_base::S_, and Champ_Inc_base::valeurs().
Calcul_C1()
void Modele_Shih_Zhu_Lumley_VDF::Calcul_C1 (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const DoubleTab & vitesse, const DoubleTab & K_Eps, const double EPS_MIN) override virtual
Implements Modele_Fonc_Realisable_base.
References Modele_Fonc_Realisable_base::C1_, nelem_, and Modele_Fonc_Realisable_base::S_.
Referenced by Contributions_Sources(), and Contributions_Sources_Paroi().
Calcul_Cmu_et_S()
void Modele_Shih_Zhu_Lumley_VDF::Calcul_Cmu_et_S (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const DoubleTab & vitesse, const DoubleTab & K_Eps, const double EPS_MIN) override virtual
Implements Modele_Fonc_Realisable_base.
References A0_, Modele_Fonc_Realisable_base::Cmu_, Objet_U::dimension, Modele_Fonc_Realisable_base::eq_hydraulique, TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Domaine_dis_base::nb_elem_tot(), nelem_, Modele_Fonc_Realisable_base::S_, and Champ_Inc_base::valeurs().
Referenced by Contributions_Sources(), and Contributions_Sources_Paroi().
Contributions_Sources()
void Modele_Shih_Zhu_Lumley_VDF::Contributions_Sources (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const DoubleTab & vitesse, const DoubleTab & K_Eps, const double EPS_MIN) override virtual
Implements Modele_Fonc_Realisable_base.
References Calcul_C1(), and Calcul_Cmu_et_S().
Contributions_Sources_Paroi()
void Modele_Shih_Zhu_Lumley_VDF::Contributions_Sources_Paroi (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const DoubleTab & vitesse, const DoubleTab & K_Eps, const double EPS_MIN, const DoubleTab & visco_tab, const DoubleTab & visco_turb, const DoubleTab & tab_paroi, const int idt) override virtual
Implements Modele_Fonc_Realisable_base.
References Calcul_C1(), and Calcul_Cmu_et_S().
Calcul_C1_BiK()
void Modele_Shih_Zhu_Lumley_VDF::Calcul_C1_BiK (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const DoubleTab & vitesse, const DoubleTab & K, const DoubleTab & Eps, const double EPS_MIN) override virtual
Implements Modele_Fonc_Realisable_base.
References Modele_Fonc_Realisable_base::C1_, nelem_, and Modele_Fonc_Realisable_base::S_.
Referenced by Contributions_Sources_BiK(), and Contributions_Sources_Paroi_BiK().
Calcul_Cmu_et_S_BiK()
void Modele_Shih_Zhu_Lumley_VDF::Calcul_Cmu_et_S_BiK (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const DoubleTab & vitesse, const DoubleTab & K, const DoubleTab & Eps, const double EPS_MIN) override virtual
Implements Modele_Fonc_Realisable_base.
References A0_, Modele_Fonc_Realisable_base::Cmu_, Objet_U::dimension, Modele_Fonc_Realisable_base::eq_hydraulique, TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Domaine_dis_base::nb_elem_tot(), nelem_, Modele_Fonc_Realisable_base::S_, and Champ_Inc_base::valeurs().
Referenced by Contributions_Sources_BiK(), and Contributions_Sources_Paroi_BiK().
Contributions_Sources_BiK()
void Modele_Shih_Zhu_Lumley_VDF::Contributions_Sources_BiK (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const DoubleTab & vitesse, const DoubleTab & K, const DoubleTab & Eps, const double EPS_MIN) override virtual
Implements Modele_Fonc_Realisable_base.
References Calcul_C1_BiK(), and Calcul_Cmu_et_S_BiK().
Contributions_Sources_Paroi_BiK()
void Modele_Shih_Zhu_Lumley_VDF::Contributions_Sources_Paroi_BiK (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const DoubleTab & vitesse, const DoubleTab & K, const DoubleTab & Eps, const double EPS_MIN, const DoubleTab & visco_tab, const DoubleTab & visco_turb, const DoubleTab & tab_paroi, const int idt) override virtual
Implements Modele_Fonc_Realisable_base.
References Calcul_C1_BiK(), and Calcul_Cmu_et_S_BiK().
associer()
void Modele_Shih_Zhu_Lumley_VDF::associer (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis) override virtual
Implements Modele_Fonc_Realisable_base.
References Initialisation(), le_dom_Cl_VDF, and le_dom_VDF.
Initialisation()
void Modele_Shih_Zhu_Lumley_VDF::Initialisation (const Domaine_dis_base & domaine_dis)
References Modele_Fonc_Realisable_base::C1_, Modele_Fonc_Realisable_base::Cmu_, Domaine_dis_base::nb_elem(), nelem_, TRUSTTab< _TYPE_, _SIZE_ >::resize_tab(), and Modele_Fonc_Realisable_base::S_.
Referenced by associer().
Member Data Documentation
info_obj
const Type_info Modele_Shih_Zhu_Lumley_VDF::info_obj static
nelem_
int Modele_Shih_Zhu_Lumley_VDF::nelem_ protected
Referenced by Calcul_C1(), Calcul_C1_BiK(), Calcul_Cmu_et_S(), Calcul_Cmu_et_S_BiK(), Calcul_S(), and Initialisation().
le_dom_VDF
TRUST_Ref< Domaine_VDF *> Modele_Shih_Zhu_Lumley_VDF::le_dom_VDF protected
Referenced by associer().
le_dom_Cl_VDF
TRUST_Ref< Domaine_Cl_VDF *> Modele_Shih_Zhu_Lumley_VDF::le_dom_Cl_VDF protected
Referenced by associer().
A0_
double Modele_Shih_Zhu_Lumley_VDF::A0_ protected
Referenced by Calcul_Cmu_et_S(), Calcul_Cmu_et_S_BiK(), and set_param().