TrioCFD: Boundary_Conditions_Thermique Class Reference
Boundary_Conditions_Thermique Class Reference
#include <Boundary_Conditions_Thermique.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
Member Enumeration Documentation
BCType
enum Boundary_Conditions_Thermique::BCType
Enumerator
Paroi_Temperature_imposee
Paroi_Flux_impose
Perio
Constructor & Destructor Documentation
Boundary_Conditions_Thermique()
Boundary_Conditions_Thermique::Boundary_Conditions_Thermique ()
References bctype_kmax_, bctype_kmin_, flux_impose_kmax_, flux_impose_kmin_, Paroi_Temperature_imposee, temperature_imposee_kmax_, and temperature_imposee_kmin_.
~Boundary_Conditions_Thermique()
Boundary_Conditions_Thermique::~Boundary_Conditions_Thermique ()
Member Function Documentation
cree_instance()
Objet_U * Boundary_Conditions_Thermique::cree_instance () static
taille_memoire()
unsigned Boundary_Conditions_Thermique::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Boundary_Conditions_Thermique::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Boundary_Conditions_Thermique::info () static
get_info()
const Type_info * Boundary_Conditions_Thermique::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
Boundary_Conditions_Thermique & Boundary_Conditions_Thermique::self_cast (Objet_U & r) static
self_cast() [2/2]
const Boundary_Conditions_Thermique & Boundary_Conditions_Thermique::self_cast (const Objet_U & r) static
printOn()
Sortie & Boundary_Conditions_Thermique::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
References Objet_U::printOn().
readOn()
Entree & Boundary_Conditions_Thermique::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
References Param::ajouter(), bctype_kmax_, bctype_kmin_, Param::dictionnaire(), Process::exit(), flux_impose_kmax_, flux_impose_kmin_, get_bctype_k_max(), get_bctype_k_min(), Param::lire_avec_accolades(), Paroi_Flux_impose, Perio, Objet_U::que_suis_je(), Param::REQUIRED, temperature_imposee_kmax_, and temperature_imposee_kmin_.
get_bctype_k_min()
BCType Boundary_Conditions_Thermique::get_bctype_k_min () const inline
References bctype_kmin_.
Referenced by IJK_Thermal_cut_cell::add_temperature_diffusion(), IJK_Thermal_base::compute_boundary_conditions_thermal(), IJK_Thermal_base::printOn(), and readOn().
get_bctype_k_max()
BCType Boundary_Conditions_Thermique::get_bctype_k_max () const inline
References bctype_kmax_.
Referenced by IJK_Thermal_cut_cell::add_temperature_diffusion(), IJK_Thermal_base::compute_boundary_conditions_thermal(), IJK_Thermal_base::printOn(), and readOn().
get_temperature_kmax()
double Boundary_Conditions_Thermique::get_temperature_kmax () const inline
References temperature_imposee_kmax_.
Referenced by IJK_Thermal_cut_cell::add_temperature_diffusion(), IJK_Thermal_base::compute_boundary_conditions_thermal(), and IJK_Thermal_base::printOn().
get_temperature_kmin()
double Boundary_Conditions_Thermique::get_temperature_kmin () const inline
References temperature_imposee_kmin_.
Referenced by IJK_Thermal_cut_cell::add_temperature_diffusion(), IJK_Thermal_base::compute_boundary_conditions_thermal(), and IJK_Thermal_base::printOn().
get_flux_kmax()
double Boundary_Conditions_Thermique::get_flux_kmax () const inline
References flux_impose_kmax_.
Referenced by IJK_Thermal_cut_cell::add_temperature_diffusion(), IJK_Thermal_base::add_temperature_source(), IJK_Thermal_base::compute_boundary_conditions_thermal(), and IJK_Thermal_base::printOn().
get_flux_kmin()
double Boundary_Conditions_Thermique::get_flux_kmin () const inline
References flux_impose_kmin_.
Referenced by IJK_Thermal_cut_cell::add_temperature_diffusion(), IJK_Thermal_base::compute_boundary_conditions_thermal(), and IJK_Thermal_base::printOn().
Member Data Documentation
info_obj
const Type_info Boundary_Conditions_Thermique::info_obj static
bctype_kmin_
int Boundary_Conditions_Thermique::bctype_kmin_ protected
Referenced by Boundary_Conditions_Thermique(), get_bctype_k_min(), and readOn().
bctype_kmax_
int Boundary_Conditions_Thermique::bctype_kmax_ protected
Referenced by Boundary_Conditions_Thermique(), get_bctype_k_max(), and readOn().
temperature_imposee_kmin_
double Boundary_Conditions_Thermique::temperature_imposee_kmin_ protected
Referenced by Boundary_Conditions_Thermique(), get_temperature_kmin(), and readOn().
temperature_imposee_kmax_
double Boundary_Conditions_Thermique::temperature_imposee_kmax_ protected
Referenced by Boundary_Conditions_Thermique(), get_temperature_kmax(), and readOn().
flux_impose_kmin_
double Boundary_Conditions_Thermique::flux_impose_kmin_ protected
Referenced by Boundary_Conditions_Thermique(), get_flux_kmin(), and readOn().
flux_impose_kmax_
double Boundary_Conditions_Thermique::flux_impose_kmax_ protected
Referenced by Boundary_Conditions_Thermique(), get_flux_kmax(), and readOn().