TrioCFD: MD_Vector_base Class Reference
MD_Vector_base Class Reference abstract
#include <MD_Vector_base.h>
Public Member Functions
const Type_info * get_info () const override
virtual bool use_blocks () const =0
virtual bool validate (trustIdType sz_array, int line_size) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions
static void append_item_to_blocs (ArrOfInt &blocs, int item)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
See also the MD_Vector class (which is a kind of DERIV() of this class), and see derived classes MD_Vector_std, MD_Vector_composite and MD_Vector_seq.
Constructor & Destructor Documentation
MD_Vector_base()
MD_Vector_base::MD_Vector_base ()
~MD_Vector_base()
MD_Vector_base::~MD_Vector_base () override
Member Function Documentation
info()
const Type_info * MD_Vector_base::info () static
get_info()
const Type_info * MD_Vector_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
Reimplemented in MD_Vector_composite, MD_Vector_mono, MD_Vector_seq, and MD_Vector_std.
self_cast() [1/2]
MD_Vector_base & MD_Vector_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const MD_Vector_base & MD_Vector_base::self_cast (const Objet_U & r) static
printOn()
Sortie & MD_Vector_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
Reimplemented in MD_Vector_composite, MD_Vector_mono, MD_Vector_seq, and MD_Vector_std.
References nb_items_reels_, nb_items_seq_local_, nb_items_seq_tot_, and nb_items_tot_.
Referenced by MD_Vector_composite::printOn(), and MD_Vector_mono::printOn().
readOn()
Entree & MD_Vector_base::readOn (Entree & is) override protected virtual
method used to dump/restore a descriptor in a file Each process writes a different descriptor.
See MD_Vector_tools::dump_vector_with_md()
Reimplemented from Objet_U.
Reimplemented in MD_Vector_composite, MD_Vector_mono, MD_Vector_seq, and MD_Vector_std.
References Param::ajouter(), Param::lire_avec_accolades(), nb_items_reels_, nb_items_seq_local_, nb_items_seq_tot_, and nb_items_tot_.
Referenced by MD_Vector_composite::readOn(), and MD_Vector_mono::readOn().
get_nb_items_reels()
virtual int MD_Vector_base::get_nb_items_reels () const inline virtual
Reimplemented in MD_Vector_seq.
References nb_items_reels_.
Referenced by MD_Vector_composite::add_part(), Scatter::construire_espace_virtuel_traduction(), and MD_Vector_std::fill_md_vect_renum().
get_nb_items_tot()
virtual int MD_Vector_base::get_nb_items_tot () const inline virtual
Reimplemented in MD_Vector_seq.
References nb_items_tot_.
Referenced by MD_Vector_composite::add_part(), Scatter::construire_espace_virtuel_traduction(), MD_Vector_std::fill_md_vect_renum(), get_seq_flags_impl(), get_sequential_items_flags(), Domaine_VF::nb_faces_bord_tot(), and validate().
nb_items_seq_tot()
virtual trustIdType MD_Vector_base::nb_items_seq_tot () const inline virtual
Reimplemented in MD_Vector_seq.
References nb_items_seq_tot_.
Referenced by MD_Vector_composite::add_part(), EcritureLectureSpecial::ecriture_special(), Domaine_VF::info_elem_som(), EcritureLectureSpecial::lecture_special(), Champ_Fonc_reprise_IJK::reprendre_IJK(), Solv_GCP::resoudre_(), and Debog_Pb::verifier_matrice().
nb_items_seq_local()
virtual int MD_Vector_base::nb_items_seq_local () const inline virtual
Reimplemented in MD_Vector_seq.
References nb_items_seq_local_.
Referenced by MD_Vector_composite::add_part().
get_items_to_compute()
virtual const ArrOfInt & MD_Vector_base::get_items_to_compute () const pure virtual
Implemented in MD_Vector_composite, and MD_Vector_mono.
Referenced by MD_Vector_composite::add_part().
get_items_to_sum()
virtual const ArrOfInt & MD_Vector_base::get_items_to_sum () const pure virtual
Implemented in MD_Vector_composite, and MD_Vector_mono.
Referenced by MD_Vector_composite::add_part(), and get_seq_flags_impl().
get_sequential_items_flags() [1/2]
int MD_Vector_base::get_sequential_items_flags (ArrOfBit & flags, int line_size = 1) const
References get_nb_items_tot(), get_seq_flags_impl(), and ArrOfBit_32_64< _SIZE_ >::resize_array().
Referenced by SETS::assembler(), Transport_Interfaces_FT_Disc::calcul_effort_fluide_interface(), Traitement_particulier_NS_THI_VEF::calcul_vitesse_moyenne(), Solv_Externe::construit_renum(), and Transport_Interfaces_FT_Disc::impr_effort_fluide_interface().
get_sequential_items_flags() [2/2]
int MD_Vector_base::get_sequential_items_flags (ArrOfInt & flags, int line_size = 1) const
References get_nb_items_tot(), get_seq_flags_impl(), and TRUSTArray< _TYPE_, _SIZE_ >::resize_array().
validate()
bool MD_Vector_base::validate (trustIdType sz_array, int line_size) const virtual
Check the consistency of array size as defined by the MD_Vector and as found in the array.
Reimplemented in MD_Vector_seq.
References Process::exit(), and get_nb_items_tot().
initialize_comm() [1/4]
virtual void MD_Vector_base::initialize_comm (const Echange_EV_Options & opt, Schema_Comm_Vecteurs & , DoubleVect &) const pure virtual
Implemented in MD_Vector_seq, MD_Vector_composite, and MD_Vector_std.
prepare_send_data() [1/4]
virtual void MD_Vector_base::prepare_send_data (const Echange_EV_Options & opt, Schema_Comm_Vecteurs & , DoubleVect &) const pure virtual
Implemented in MD_Vector_seq, MD_Vector_composite, and MD_Vector_std.
process_recv_data() [1/4]
virtual void MD_Vector_base::process_recv_data (const Echange_EV_Options & opt, Schema_Comm_Vecteurs & , DoubleVect &) const pure virtual
Implemented in MD_Vector_seq, MD_Vector_composite, and MD_Vector_std.
initialize_comm() [2/4]
virtual void MD_Vector_base::initialize_comm (const Echange_EV_Options & opt, Schema_Comm_Vecteurs & , FloatVect &) const pure virtual
Implemented in MD_Vector_seq, MD_Vector_composite, and MD_Vector_std.
prepare_send_data() [2/4]
virtual void MD_Vector_base::prepare_send_data (const Echange_EV_Options & opt, Schema_Comm_Vecteurs & , FloatVect &) const pure virtual
Implemented in MD_Vector_seq, MD_Vector_composite, and MD_Vector_std.
process_recv_data() [2/4]
virtual void MD_Vector_base::process_recv_data (const Echange_EV_Options & opt, Schema_Comm_Vecteurs & , FloatVect &) const pure virtual
Implemented in MD_Vector_seq, MD_Vector_composite, and MD_Vector_std.
initialize_comm() [3/4]
virtual void MD_Vector_base::initialize_comm (const Echange_EV_Options & opt, Schema_Comm_Vecteurs & , IntVect &) const pure virtual
Implemented in MD_Vector_seq, MD_Vector_composite, and MD_Vector_std.
prepare_send_data() [3/4]
virtual void MD_Vector_base::prepare_send_data (const Echange_EV_Options & opt, Schema_Comm_Vecteurs & , IntVect &) const pure virtual
Implemented in MD_Vector_seq, MD_Vector_composite, and MD_Vector_std.
process_recv_data() [3/4]
virtual void MD_Vector_base::process_recv_data (const Echange_EV_Options & opt, Schema_Comm_Vecteurs & , IntVect &) const pure virtual
Implemented in MD_Vector_seq, MD_Vector_composite, and MD_Vector_std.
initialize_comm() [4/4]
virtual void MD_Vector_base::initialize_comm (const Echange_EV_Options & opt, Schema_Comm_Vecteurs & , TIDVect &) const pure virtual
Implemented in MD_Vector_seq, MD_Vector_composite, and MD_Vector_std.
prepare_send_data() [4/4]
virtual void MD_Vector_base::prepare_send_data (const Echange_EV_Options & opt, Schema_Comm_Vecteurs & , TIDVect &) const pure virtual
Implemented in MD_Vector_seq, MD_Vector_composite, and MD_Vector_std.
process_recv_data() [4/4]
virtual void MD_Vector_base::process_recv_data (const Echange_EV_Options & opt, Schema_Comm_Vecteurs & , TIDVect &) const pure virtual
Implemented in MD_Vector_seq, MD_Vector_composite, and MD_Vector_std.
fill_md_vect_renum()
virtual void MD_Vector_base::fill_md_vect_renum (const IntVect & renum, MD_Vector & md_vect) const pure virtual
Implemented in MD_Vector_composite, MD_Vector_seq, and MD_Vector_std.
Referenced by MD_Vector_tools::creer_md_vect_renum().
append_item_to_blocs()
void MD_Vector_base::append_item_to_blocs (ArrOfInt & blocs, int item) static
methode outil pour ajouter un item a un tableau du genre "blocs" contenant des series de blocs.
.. alonge le bloc precedent ou commence un nouveau bloc si l'item n'est pas contigu avec le bloc precedent.
References TRUSTArray< _TYPE_, _SIZE_ >::append_array(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
use_blocks()
virtual bool MD_Vector_base::use_blocks () const pure virtual
Whether algorithms in TRUSTVect_tools should use the blocks stored in members MD_Vector_mono::blocs_items_to_*
Implemented in MD_Vector_composite, MD_Vector_seq, and MD_Vector_std.
get_seq_flags_impl()
int MD_Vector_base::get_seq_flags_impl (ArrOfBit & flags, int line_size) const protected virtual
Reimplemented in MD_Vector_composite, and MD_Vector_seq.
References TRUSTArray< _TYPE_, _SIZE_ >::addr(), ArrOfBit_32_64< _SIZE_ >::clearbit(), get_items_to_sum(), get_nb_items_tot(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by MD_Vector_composite::get_seq_flags_impl(), and get_sequential_items_flags().
append_blocs()
void MD_Vector_base::append_blocs (ArrOfInt & dest, const ArrOfInt & src, int offset = 0, int multiplier = 1) static protected
References TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by MD_Vector_composite::add_part(), and MD_Vector_std::append_from_other_std().
append_items()
void MD_Vector_base::append_items (ArrOfInt & dest, const ArrOfInt & src, int offset = 0, int multiplier = 1) static protected
References TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by MD_Vector_std::append_from_other_std().
Friends And Related Function Documentation
MD_Vector
friend class MD_Vector friend
Referenced by MD_Vector_composite::readOn().
Member Data Documentation
info_obj
const Type_info MD_Vector_base::info_obj static
nb_items_tot_
int MD_Vector_base::nb_items_tot_ = -1 protected
Referenced by MD_Vector_composite::add_part(), MD_Vector_std::fill_md_vect_renum(), get_nb_items_tot(), MD_Vector_std::MD_Vector_std(), printOn(), and readOn().
nb_items_reels_
int MD_Vector_base::nb_items_reels_ = -1 protected
Referenced by MD_Vector_composite::add_part(), MD_Vector_std::fill_md_vect_renum(), get_nb_items_reels(), MD_Vector_std::MD_Vector_std(), printOn(), and readOn().
nb_items_seq_tot_
trustIdType MD_Vector_base::nb_items_seq_tot_ = -1 protected
Referenced by MD_Vector_composite::add_part(), MD_Vector_std::fill_md_vect_renum(), MD_Vector_std::MD_Vector_std(), nb_items_seq_tot(), printOn(), and readOn().
nb_items_seq_local_
int MD_Vector_base::nb_items_seq_local_ = -1 protected
Referenced by MD_Vector_composite::add_part(), MD_Vector_std::fill_md_vect_renum(), MD_Vector_std::MD_Vector_std(), nb_items_seq_local(), printOn(), and readOn().