TrioCFD: Equation_base Class Reference
Equation_base Class Reference abstract
#include <Equation_base.h>
Public Member Functions
virtual void abortTimeStep ()
virtual void associer_domaine_dis (const Domaine_dis_base &)
virtual void associer_pb_base (const Probleme_base &)
virtual void associer_sch_tps_base (const Schema_Temps_base &)
virtual double calculer_pas_de_temps () const
virtual void completer ()
virtual std::vector< YAML_data > data_a_sauvegarder () const
DoubleTab & derivee_en_temps_conv (DoubleTab &, const DoubleTab &)
virtual DoubleTab & derivee_en_temps_inco (DoubleTab &)
const Discretisation_base & discretisation () const
virtual void discretiser ()
virtual const Motcle & domaine_application () const
virtual Domaine_Cl_dis_base & domaine_Cl_dis ()
virtual const Domaine_Cl_dis_base & domaine_Cl_dis () const
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual void imprimer (Sortie &os) const
virtual bool initTimeStep (double dt)
const Nom & le_nom () const override
int limpr () const
virtual void mettre_a_jour (double temps)
virtual int preparer_calcul ()
Probleme_base & probleme ()
const Probleme_base & probleme () const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Schema_Temps_base & schema_temps ()
const Schema_Temps_base & schema_temps () const
Solveur_Masse_base & solv_masse ()
const Solveur_Masse_base & solv_masse () const
Sources & sources ()
const Sources & sources () const
virtual void valider_iteration ()
virtual void verifie_ch_init_nb_comp (const Champ_Inc_base &ch_ref, const int nb_comp) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
virtual Entree & lire_cl (Entree &)
virtual Entree & lire_cond_init (Entree &)
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual Entree & lire_sources (Entree &)
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
virtual int verif_Cl () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
Ses membres sont les attributs et les methodes communs a toutes les classes qui representent des equations.
Une equation est modelisee de la facon suivante:
    M * dU_h/dt + Somme_i(Op_i(U_h)) = Somme(Sources);
M est la matrice masse representee par un objet "Solveur_Masse"
U_h est l'inconnue representee par un objet "Champ_Inc"
Op_i est le i-eme operateur de l'equation represente par un objet "Operateur"
Sources sont les termes sources (eventuellement inexistant) de l'equation represente par des objets "Source".
Une equation est lie a un probleme par une reference contenue dans le membre OBS_PTR(Probleme_base) mon_probleme.
Classe abstraite dont toutes les equations doivent deriver.
Methodes abstraites:
  int nombre_d_operateurs() const
  const Operateur& operateur(int) const
  Operateur& operateur(int)
  const Champ_Inc_base& inconnue() const
  Champ_Inc_base& inconnue()
  void associer_milieu_base(const Milieu_base&)
  const Milieu_base& milieu() const
  Milieu_base& milieu()
  Entree& lire(const Motcle&, Entree&) [protegee]
Constructor & Destructor Documentation
Equation_base()
Equation_base::Equation_base ()
References Parser_U::addVar(), has_time_factor_, implicite_, Parser_U::parseString(), set_calculate_time_derivative(), Parser_U::setNbVar(), Parser_U::setString(), and sys_invariant_.
~Equation_base()
Equation_base::~Equation_base () override
Member Function Documentation
info()
const Type_info * Equation_base::info () static
get_info()
const Type_info * Equation_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
Reimplemented in Navier_Stokes_std_ALE, Navier_Stokes_Turbulent_ALE, Transport_K_Eps_ALE, Convection_diffusion_turbulence_multiphase, Echelle_temporelle_turbulente, Energie_cinetique_turbulente, Energie_cinetique_turbulente_WIT, Taux_dissipation_turbulent, IJK_Interfaces, IJK_Thermals, Navier_Stokes_FTD_IJK, Convection_Diffusion_Concentration_FT_Disc, Convection_Diffusion_Concentration_Turbulent_FT_Disc, Convection_Diffusion_Temperature_FT_Disc, Navier_Stokes_FT_Disc, Transport_Interfaces_FT_Disc, Transport_Marqueur_FT, Convection_Diffusion_Phase_field, Navier_Stokes_phase_field, Navier_Stokes_Aposteriori, Equation_rayonnement_base, Eq_rayo_semi_transp_VDF, Eq_rayo_semi_transp_VEF, Convection_Diffusion_Temperature_sensibility, Navier_Stokes_std_sensibility, Transport_2eq_base, Transport_K_Eps, Transport_K_Eps_Bas_Reynolds, Transport_K_Eps_base, Transport_K_Eps_non_std, Transport_K_Eps_Realisable, Transport_K_KEps, Transport_K_Omega, Transport_K_Omega_base, Transport_K_ou_Eps, Transport_K_ou_Eps_base, Transport_K_ou_Eps_non_std, Transport_K_ou_Eps_Realisable, Transport_Fluctuation_Temperature, Transport_Fluctuation_Temperature_W, Transport_Fluctuation_Temperature_W_Bas_Re, Transport_Flux_Chaleur_Turbulente, List_Equations_Scalaires_Passifs_Especes, Convection_Diffusion_Chaleur_Fluide_Dilatable_base, Convection_Diffusion_Espece_Binaire_base, Convection_Diffusion_Espece_Fluide_Dilatable_base, Convection_Diffusion_Espece_Multi_base, Convection_Diffusion_Fluide_Dilatable_base, Navier_Stokes_Fluide_Dilatable_base, Convection_Diffusion_Chaleur_QC, Convection_Diffusion_Espece_Binaire_QC, Convection_Diffusion_Espece_Multi_QC, Navier_Stokes_QC, Convection_Diffusion_Chaleur_WC, Convection_Diffusion_Espece_Binaire_WC, Convection_Diffusion_Espece_Multi_WC, Navier_Stokes_WC, Convection_Diffusion_Temperature_IBM, Convection_Diffusion_Temperature_IBM_Turbulent, Navier_Stokes_IBM, Navier_Stokes_IBM_Turbulent, Convection_Diffusion_Concentration, Convection_Diffusion_std, Convection_Diffusion_Temperature, Convection_Diffusion_Temperature_base, Navier_Stokes_std, Transport_Interfaces_base, Aire_interfaciale, Energie_Multiphase, Energie_Multiphase_Enthalpie, Masse_Multiphase, QDM_Multiphase, Convection_Diffusion_Chaleur_Turbulent_QC, Convection_Diffusion_Concentration_Turbulent, Convection_Diffusion_Espece_Binaire_Turbulent_QC, Convection_Diffusion_Espece_Multi_Turbulent_QC, Convection_Diffusion_Temperature_Turbulent, Navier_Stokes_Turbulent, Navier_Stokes_Turbulent_QC, Conduction, and Conduction_IBM.
self_cast() [1/2]
Equation_base & Equation_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Equation_base & Equation_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Equation_base::printOn (Sortie & os) const override protected virtual
Surcharge Objet_U::printOn Imprime l'equation et ses composants sur un flot de sortie.
Imprime le nom de l'equation, le solveur masse, les termes sources les conditions aux limites discretisees, les inconnues et les operateurs.
Parameters
(Sortie& os) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Objet_U.
Reimplemented in Navier_Stokes_std_ALE, Navier_Stokes_Turbulent_ALE, Transport_K_Eps_ALE, Convection_diffusion_turbulence_multiphase, Echelle_temporelle_turbulente, Energie_cinetique_turbulente, Energie_cinetique_turbulente_WIT, Taux_dissipation_turbulent, IJK_Interfaces, IJK_Thermals, Navier_Stokes_FTD_IJK, Convection_Diffusion_Concentration_FT_Disc, Convection_Diffusion_Concentration_Turbulent_FT_Disc, Convection_Diffusion_Temperature_FT_Disc, Navier_Stokes_FT_Disc, Transport_Interfaces_FT_Disc, Transport_Marqueur_FT, Convection_Diffusion_Phase_field, Navier_Stokes_phase_field, Navier_Stokes_Aposteriori, Equation_rayonnement_base, Eq_rayo_semi_transp_VDF, Eq_rayo_semi_transp_VEF, Convection_Diffusion_Temperature_sensibility, Navier_Stokes_std_sensibility, Transport_2eq_base, Transport_K_Eps, Transport_K_Eps_Bas_Reynolds, Transport_K_Eps_base, Transport_K_Eps_non_std, Transport_K_Eps_Realisable, Transport_K_KEps, Transport_K_Omega, Transport_K_Omega_base, Transport_K_ou_Eps, Transport_K_ou_Eps_base, Transport_K_ou_Eps_non_std, Transport_K_ou_Eps_Realisable, Transport_Fluctuation_Temperature, Transport_Fluctuation_Temperature_W, Transport_Fluctuation_Temperature_W_Bas_Re, Transport_Flux_Chaleur_Turbulente, List_Equations_Scalaires_Passifs_Especes, Convection_Diffusion_Chaleur_Fluide_Dilatable_base, Convection_Diffusion_Espece_Binaire_base, Convection_Diffusion_Espece_Fluide_Dilatable_base, Convection_Diffusion_Espece_Multi_base, Convection_Diffusion_Fluide_Dilatable_base, Navier_Stokes_Fluide_Dilatable_base, Convection_Diffusion_Chaleur_QC, Convection_Diffusion_Espece_Binaire_QC, Convection_Diffusion_Espece_Multi_QC, Navier_Stokes_QC, Convection_Diffusion_Chaleur_WC, Convection_Diffusion_Espece_Binaire_WC, Convection_Diffusion_Espece_Multi_WC, Navier_Stokes_WC, Convection_Diffusion_Temperature_IBM, Convection_Diffusion_Temperature_IBM_Turbulent, Navier_Stokes_IBM, Navier_Stokes_IBM_Turbulent, Convection_Diffusion_Concentration, Convection_Diffusion_std, Convection_Diffusion_Temperature, Convection_Diffusion_Temperature_base, Navier_Stokes_std, Transport_Interfaces_base, Aire_interfaciale, Energie_Multiphase, Energie_Multiphase_Enthalpie, Masse_Multiphase, QDM_Multiphase, Convection_Diffusion_Chaleur_Turbulent_QC, Convection_Diffusion_Concentration_Turbulent, Convection_Diffusion_Espece_Binaire_Turbulent_QC, Convection_Diffusion_Espece_Multi_Turbulent_QC, Convection_Diffusion_Temperature_Turbulent, Navier_Stokes_Turbulent, Navier_Stokes_Turbulent_QC, Conduction, and Conduction_IBM.
References inconnue(), Operateur::l_op_base(), le_dom_Cl_dis, les_sources, nom_, nombre_d_operateurs(), operateur(), and solveur_masse.
Referenced by Navier_Stokes_Turbulent_ALE::printOn(), Convection_Diffusion_Temperature_IBM_Turbulent::printOn(), Navier_Stokes_IBM_Turbulent::printOn(), Convection_Diffusion_std::printOn(), Navier_Stokes_std::printOn(), Transport_Interfaces_base::printOn(), Masse_Multiphase::printOn(), QDM_Multiphase::printOn(), Convection_Diffusion_Chaleur_Turbulent_QC::printOn(), Convection_Diffusion_Concentration_Turbulent::printOn(), Convection_Diffusion_Temperature_Turbulent::printOn(), Navier_Stokes_Turbulent::printOn(), and Navier_Stokes_Turbulent_QC::printOn().
readOn()
Entree & Equation_base::readOn (Entree & is) override protected virtual
Lecture d'une equation sur un flot d'entree.
Le format est le suivant: { [Source { [sou_1], [sour_2], ...} ] Conditions_limites { [cl_1] [cl_2] ... } Conditions_initiales { [cl_init] } }
Parameters
(Entree& is) un flot d'entree pour lire l'equation
Returns
(Entree&) le flot d'entree modifie
Exceptions
mauvais format de lecture, accolade ouvrante attendue
pas de conditions initiales, il faut initialiser l'inconnue
pas de conditions aux limites, il faut donner des conditions aux limites
Reimplemented from Objet_U.
Reimplemented in Navier_Stokes_std_ALE, Navier_Stokes_Turbulent_ALE, Transport_K_Eps_ALE, Convection_diffusion_turbulence_multiphase, Echelle_temporelle_turbulente, Energie_cinetique_turbulente, Energie_cinetique_turbulente_WIT, Taux_dissipation_turbulent, IJK_Interfaces, IJK_Thermals, Navier_Stokes_FTD_IJK, Convection_Diffusion_Concentration_FT_Disc, Convection_Diffusion_Concentration_Turbulent_FT_Disc, Convection_Diffusion_Temperature_FT_Disc, Navier_Stokes_FT_Disc, Transport_Interfaces_FT_Disc, Transport_Marqueur_FT, Convection_Diffusion_Phase_field, Navier_Stokes_phase_field, Navier_Stokes_Aposteriori, Equation_rayonnement_base, Eq_rayo_semi_transp_VDF, Eq_rayo_semi_transp_VEF, Convection_Diffusion_Temperature_sensibility, Navier_Stokes_std_sensibility, Transport_2eq_base, Transport_K_Eps, Transport_K_Eps_Bas_Reynolds, Transport_K_Eps_base, Transport_K_Eps_non_std, Transport_K_Eps_Realisable, Transport_K_KEps, Transport_K_Omega, Transport_K_Omega_base, Transport_K_ou_Eps, Transport_K_ou_Eps_base, Transport_K_ou_Eps_non_std, Transport_K_ou_Eps_Realisable, Transport_Fluctuation_Temperature, Transport_Fluctuation_Temperature_W, Transport_Fluctuation_Temperature_W_Bas_Re, Transport_Flux_Chaleur_Turbulente, List_Equations_Scalaires_Passifs_Especes, Convection_Diffusion_Chaleur_Fluide_Dilatable_base, Convection_Diffusion_Espece_Binaire_base, Convection_Diffusion_Espece_Fluide_Dilatable_base, Convection_Diffusion_Espece_Multi_base, Convection_Diffusion_Fluide_Dilatable_base, Navier_Stokes_Fluide_Dilatable_base, Convection_Diffusion_Chaleur_QC, Convection_Diffusion_Espece_Binaire_QC, Convection_Diffusion_Espece_Multi_QC, Navier_Stokes_QC, Convection_Diffusion_Chaleur_WC, Convection_Diffusion_Espece_Binaire_WC, Convection_Diffusion_Espece_Multi_WC, Navier_Stokes_WC, Convection_Diffusion_Temperature_IBM, Convection_Diffusion_Temperature_IBM_Turbulent, Navier_Stokes_IBM, Navier_Stokes_IBM_Turbulent, Convection_Diffusion_Concentration, Convection_Diffusion_std, Convection_Diffusion_Temperature, Convection_Diffusion_Temperature_base, Navier_Stokes_std, Transport_Interfaces_base, Aire_interfaciale, Energie_Multiphase, Energie_Multiphase_Enthalpie, Masse_Multiphase, QDM_Multiphase, Convection_Diffusion_Chaleur_Turbulent_QC, Convection_Diffusion_Concentration_Turbulent, Convection_Diffusion_Espece_Binaire_Turbulent_QC, Convection_Diffusion_Espece_Multi_Turbulent_QC, Convection_Diffusion_Temperature_Turbulent, Navier_Stokes_Turbulent, Navier_Stokes_Turbulent_QC, Conduction, and Conduction_IBM.
References Param::ajouter(), Param::lire_avec_accolades_depuis(), matrice_init, Objet_U::que_suis_je(), set_param(), and Parser_U::setString().
Referenced by Transport_Marqueur_FT::readOn(), Equation_rayonnement_base::readOn(), Transport_2eq_base::readOn(), Transport_K_Eps_base::readOn(), Transport_K_Omega_base::readOn(), Transport_K_ou_Eps_base::readOn(), Convection_Diffusion_std::readOn(), Navier_Stokes_std::readOn(), Transport_Interfaces_base::readOn(), Masse_Multiphase::readOn(), and Conduction::readOn().
nommer()
void Equation_base::nommer (const Nom & nom) override virtual
Methode appelee lorsqu'on cree l'instance de l'objet dans le jeu de donnees (Interprete::ajouter)
Reimplemented from Objet_U.
References nom_.
Referenced by Probleme_FT_Disc_gen::add_FT_equation(), and List_Equations_Scalaires_Passifs_Especes::readOn().
avancer()
void Equation_base::avancer (int i = 1) virtual
References Champ_Inc_base::avancer(), champ_conserve_, champ_convecte_, inconnue(), and Objet_U_ptr::non_nul().
reculer()
void Equation_base::reculer (int i = 1) virtual
References champ_conserve_, champ_convecte_, inconnue(), Objet_U_ptr::non_nul(), and Champ_Inc_base::reculer().
nombre_d_operateurs()
virtual int Equation_base::nombre_d_operateurs () const pure virtual
Implemented in IJK_Interfaces, IJK_Thermals, Navier_Stokes_FTD_IJK, Transport_Interfaces_FT_Disc, Equation_rayonnement_base, Transport_K_Eps, Transport_K_Eps_non_std, Transport_K_Eps_Realisable, Transport_K_Omega, Transport_K_ou_Eps, Transport_K_ou_Eps_non_std, Transport_K_ou_Eps_Realisable, Transport_Fluctuation_Temperature, Transport_Fluctuation_Temperature_W, Transport_Flux_Chaleur_Turbulente, List_Equations_Scalaires_Passifs_Especes, Convection_Diffusion_std, Navier_Stokes_std, Aire_interfaciale, Masse_Multiphase, and Conduction.
Referenced by abortTimeStep(), ajouter_termes_croises(), assembler(), assembler_blocs(), associer_pb_base(), Transport_Interfaces_FT_Disc::calcul_vitesse(), calculer_pas_de_temps(), Pb_Multiphase::calculer_pas_de_temps(), calculer_pas_de_temps_locaux(), Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl(), Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl_u_star(), completer(), Masse_PolyMAC_base::completer(), contribuer_termes_croises(), creer_champ(), derivee_en_temps_inco(), dimensionner_blocs(), dimensionner_matrice_sans_mem(), dimensionner_termes_croises(), get_champ(), get_noms_champs_postraitables(), has_champ(), has_interface_blocs(), impr(), Echange_contact_PolyMAC_P0::init_op(), Echange_contact_PolyMAC_P0P1NC::init_op(), initTimeStep(), Postraitement::lire_champs_a_postraiter(), modifier_pour_Cl(), nombre_d_operateurs_tot(), preparer_calcul(), printOn(), resetTime(), and updateGivenFields().
nombre_d_operateurs_tot()
int Equation_base::nombre_d_operateurs_tot () const virtual
Reimplemented in Navier_Stokes_std.
References nombre_d_operateurs().
Referenced by Postraitement::lire_champs_a_postraiter().
operateur() [1/2]
virtual const Operateur & Equation_base::operateur (int) const pure virtual
Implemented in Transport_Interfaces_FT_Disc, IJK_Interfaces, IJK_Thermals, Navier_Stokes_FTD_IJK, Equation_rayonnement_base, Transport_K_Eps, Transport_K_Eps_non_std, Transport_K_Eps_Realisable, Transport_K_Omega, Transport_K_ou_Eps, Transport_K_ou_Eps_non_std, Transport_K_ou_Eps_Realisable, Transport_Fluctuation_Temperature, Transport_Fluctuation_Temperature_W, Transport_Fluctuation_Temperature_W_Bas_Re, Transport_Flux_Chaleur_Turbulente, List_Equations_Scalaires_Passifs_Especes, Convection_Diffusion_std, Navier_Stokes_std, Aire_interfaciale, Masse_Multiphase, and Conduction.
Referenced by abortTimeStep(), Terme_Source_Th_TdivU_VEF_Face::ajouter(), Nucleation_paroi_PolyMAC_P0::ajouter_blocs(), ajouter_termes_croises(), assembler(), assembler_blocs(), associer_pb_base(), Champ_P1NC::calcul_h_conv(), Transport_Interfaces_FT_Disc::calcul_vitesse(), calculer_pas_de_temps(), Pb_Multiphase::calculer_pas_de_temps(), calculer_pas_de_temps_locaux(), completer(), Travail_pression_VDF::completer(), Terme_Source_Canal_perio::compute_heat_flux(), contribuer_termes_croises(), creer_champ(), derivee_en_temps_conv(), derivee_en_temps_inco(), dimensionner_blocs(), dimensionner_matrice_sans_mem(), dimensionner_termes_croises(), get_champ(), get_noms_champs_postraitables(), has_champ(), has_interface_blocs(), impr(), Echange_contact_PolyMAC_P0::init_op(), Echange_contact_PolyMAC_P0P1NC::init_op(), Op_Diff_VDF_base::init_op_ext(), Echange_contact_PolyMAC::initialiser(), initTimeStep(), Op_Dift_Multiphase_VDF_Elem::mettre_a_jour(), Op_Diff_Turbulent_PolyMAC_P0_Elem::modifier_mu(), modifier_pour_Cl(), preparer_calcul(), printOn(), resetTime(), Echange_contact_PolyMAC::update_coeffs(), Echange_contact_PolyMAC::update_delta(), and updateGivenFields().
operateur() [2/2]
virtual Operateur & Equation_base::operateur (int) pure virtual
Implemented in Transport_Interfaces_FT_Disc, IJK_Interfaces, IJK_Thermals, Navier_Stokes_FTD_IJK, Equation_rayonnement_base, Transport_K_Eps, Transport_K_Eps_non_std, Transport_K_Eps_Realisable, Transport_K_Omega, Transport_K_ou_Eps, Transport_K_ou_Eps_non_std, Transport_K_ou_Eps_Realisable, Transport_Fluctuation_Temperature, Transport_Fluctuation_Temperature_W, Transport_Fluctuation_Temperature_W_Bas_Re, Transport_Flux_Chaleur_Turbulente, List_Equations_Scalaires_Passifs_Especes, Convection_Diffusion_std, Navier_Stokes_std, Aire_interfaciale, Masse_Multiphase, and Conduction.
operateur_fonctionnel() [1/2]
const Operateur & Equation_base::operateur_fonctionnel (int i) const virtual
Reimplemented in Navier_Stokes_std.
References Process::exit(), and Objet_U::que_suis_je().
operateur_fonctionnel() [2/2]
Operateur & Equation_base::operateur_fonctionnel (int i) virtual
Reimplemented in Navier_Stokes_std.
References Process::exit(), and Objet_U::que_suis_je().
inconnue() [1/2]
virtual const Champ_Inc_base & Equation_base::inconnue () const pure virtual
Implemented in Convection_diffusion_turbulence_multiphase, Energie_cinetique_turbulente_WIT, IJK_Interfaces, IJK_Thermals, Navier_Stokes_FTD_IJK, Transport_Interfaces_FT_Disc, Transport_Marqueur_FT, Equation_rayonnement_base, Transport_K_Eps_base, Transport_K_Omega_base, Transport_K_ou_Eps_base, Transport_Fluctuation_Temperature, Transport_Fluctuation_Temperature_W, Transport_Flux_Chaleur_Turbulente, List_Equations_Scalaires_Passifs_Especes, Convection_Diffusion_Fluide_Dilatable_base, Convection_Diffusion_Concentration, Convection_Diffusion_Temperature, Navier_Stokes_std, Aire_interfaciale, Energie_Multiphase, Masse_Multiphase, Conduction, and Convection_Diffusion_std.
Referenced by Modele_turbulence_hyd_base::a_faire(), abortTimeStep(), Schema_Adams_Moulton_base::add_multi_timestep_data(), Schema_Backward_Differentiation_base::add_multi_timestep_data(), Op_Diff_VDF_base::ajoute_terme_pour_axi(), Op_Dift_VDF_base::ajoute_terme_pour_axi_turb(), Operateur_base::ajouter(), Op_Diff_EF::ajouter(), Op_Dift_EF_Q1::ajouter(), Op_Diff_VEF_Anisotrope_Face::ajouter(), Op_Diff_VEF_Face::ajouter(), Source_Robin_Scalaire::ajouter(), Source_Scalaire_EF::ajouter(), Terme_Source_Decroissance_Radioactive_VEF_Face::ajouter(), Terme_Source_Th_TdivU_VEF_Face::ajouter(), Source_rayo_semi_transp_VDF_P0_VDF::ajouter(), Source_rayo_semi_transp_VEF_P1NC::ajouter(), Perte_Charge_Singuliere_VDF_Face::ajouter_(), Op_Diff_K_Eps_VDF_base::ajouter_blocs(), Op_Diff_K_Omega_VDF_base::ajouter_blocs(), Source_Transport_Realisable_VDF_Elem_base::ajouter_blocs(), Source_Transport_Eps_VDF_Elem::ajouter_blocs(), Source_Transport_K_VDF_Elem::ajouter_blocs(), Source_Transport_K_Eps_VDF_Elem::ajouter_blocs(), Source_Transport_K_Omega_VDF_Elem::ajouter_blocs(), Op_Grad_P0_to_Face::ajouter_blocs(), Acceleration_QC_VDF_Face::ajouter_blocs(), Source_qdm_QC_VDF_Face::ajouter_blocs(), Perte_Charge_Reguliere_QC_VDF_Face::ajouter_blocs(), Perte_Charge_Singuliere_QC_VDF_Face::ajouter_blocs(), Darcy_QC_VDF_Face::ajouter_blocs(), Forchheimer_QC_VDF_Face::ajouter_blocs(), Perte_Charge_Reguliere_VDF_Face::ajouter_blocs(), Perte_Charge_Singuliere_VDF_Face::ajouter_blocs(), Terme_Boussinesq_VDF_Face::ajouter_blocs(), Terme_Source_Qdm_VDF_Face::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_P0_Face::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Face::ajouter_blocs(), Op_Diff_PolyMAC_P0_Face::ajouter_blocs(), Coalescence_bulles_1groupe_PolyMAC_P0::ajouter_blocs(), Coalescence_bulles_2groupes_PolyMAC_P0::ajouter_blocs(), Flux_2groupes_PolyMAC_P0::ajouter_blocs(), Rupture_bulles_1groupe_PolyMAC_P0::ajouter_blocs(), Rupture_bulles_2groupes_PolyMAC_P0::ajouter_blocs(), Variation_rho::ajouter_blocs(), Dissipation_WIT_PolyMAC_P0::ajouter_blocs(), Production_echelle_temp_taux_diss_turb_PolyMAC_P0::ajouter_blocs(), Production_energie_cin_turb_PolyMAC_P0::ajouter_blocs(), Production_WIT_PolyMAC_P0::ajouter_blocs(), Source_Dissipation_echelle_temp_taux_diss_turb::ajouter_blocs(), Source_Dissipation_energie_cin_turb::ajouter_blocs(), Production_echelle_temp_taux_diss_turb_VDF::ajouter_blocs(), Production_energie_cin_turb_VDF::ajouter_blocs(), Op_Diff_DG_Elem::ajouter_blocs(), Dispersion_bulles_PolyMAC_P0::ajouter_blocs(), Frottement_interfacial_PolyMAC_P0::ajouter_blocs(), Portance_interfaciale_PolyMAC_P0::ajouter_blocs(), Op_Diff_PolyMAC_P0_Elem::ajouter_blocs(), DP_Impose_PolyMAC_Face::ajouter_blocs(), Perte_Charge_PolyMAC::ajouter_blocs(), Perte_Charge_Singuliere_PolyMAC_P0P1NC_Face::ajouter_blocs(), Terme_Source_Decroissance_Radioactive_Elem_PolyMAC::ajouter_blocs(), Terme_Source_Qdm_Face_PolyMAC_P0P1NC::ajouter_blocs(), Op_Evanescence_Homogene_Elem_base::ajouter_blocs(), Source_Flux_interfacial_base::ajouter_blocs(), Source_Travail_pression_Elem_base::ajouter_blocs(), Dispersion_bulles_VDF::ajouter_blocs(), Frottement_interfacial_VDF::ajouter_blocs(), Portance_interfaciale_VDF::ajouter_blocs(), Op_Conv_Amont_VPoly_VDF_Face::ajouter_blocs(), Perte_Charge_VDF_base::ajouter_blocs(), DP_Impose_VEF_Face::ajouter_blocs(), Masse_DG_base::ajouter_blocs(), Masse_PolyMAC_P0_Face::ajouter_blocs(), Masse_VDF_base::ajouter_blocs(), Masse_VDF_Face::ajouter_blocs(), Op_Evanescence_Homogene_PolyMAC_P0_Face::ajouter_blocs_aux(), Correction_Lubchenko_PolyMAC_P0::ajouter_blocs_disp(), Op_Diff_PolyMAC_P0P1NC_Elem::ajouter_blocs_ext(), Correction_Lubchenko_PolyMAC_P0::ajouter_blocs_lift(), Solveur_Masse_Face_proto::ajouter_blocs_proto(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution(), Op_Diff_VEF_Face::ajouter_contribution(), Op_Diff_EF::ajouter_contributions_bords(), Op_Dift_EF_Q1::ajouter_contributions_bords(), Schema_Temps_base::ajouter_inertie(), Schema_Euler_Implicite_Stationnaire::ajouter_inertie(), Schema_Implicite_Multi_TimeStep_base::ajouter_inertie(), Solveur_Masse_base::ajouter_masse(), Op_Conv_ALE_VEF::ajouterALE(), Solveur_Masse_base::appliquer(), Masse_DG_base::appliquer_coef(), Masse_PolyMAC_base::appliquer_coef(), Solveur_Masse_EF::appliquer_impl(), Masse_PolyMAC_P0_Face::appliquer_impl(), Masse_PolyMAC_P0P1NC_Face::appliquer_impl(), Masse_VEF_P1NC::appliquer_impl(), assembler_blocs(), assembler_blocs_avec_inertie(), Assembleur_P_PolyMAC_P0P1NC::assembler_continuite(), Simpler_Base::assembler_matrice_pression_implicite(), Op_Conv_VDF_base::associer_champ_convecte_elem(), Op_Conv_VDF_base::associer_champ_convecte_face(), Milieu_base::associer_equation(), Transport_K_Eps::associer_modele_turbulence(), Transport_K_Eps_Bas_Reynolds::associer_modele_turbulence(), Transport_K_Eps_Realisable::associer_modele_turbulence(), Transport_K_KEps::associer_modele_turbulence(), Transport_K_Omega::associer_modele_turbulence(), Transport_K_ou_Eps::associer_modele_turbulence(), Transport_K_ou_Eps_Realisable::associer_modele_turbulence(), Transport_Flux_Chaleur_Turbulente::associer_modele_turbulence(), Source_PDF_EF::associer_pb(), Perte_Charge_PolyMAC_Face::associer_pb(), Perte_Charge_Gen::associer_pb(), Perte_Charge_VDF_Face::associer_pb(), Source_Darcy_VDF_Face::associer_pb(), Source_Echange_Th_VDF::associer_pb(), Source_Forchheimer_VDF_Face::associer_pb(), Perte_Charge_VEF_Face::associer_pb(), Source_Darcy_VEF_Face::associer_pb(), Source_Forchheimer_VEF_Face::associer_pb(), Terme_Source_Qdm_lambdaup_VEF_Face::associer_pb(), Terme_Boussinesq_base::associer_pb(), avancer(), Op_Evanescence_Homogene_PolyMAC_P0_Face::calc_grad_alpha_elem(), Op_Evanescence_Homogene_PolyMAC_P0_Face::calc_grad_alpha_faces(), Op_Evanescence_Homogene_VDF_Face::calc_grad_alpha_faces(), Transport_Marqueur_FT::calcul_vitesse_p(), Champ_Q1_EF::calcul_y_plus(), Champ_P1NC::calcul_y_plus(), Fluide_reel_base::calculate_fluid_properties(), Fluide_reel_base::calculate_fluid_properties_enthalpie(), Fluide_reel_base::calculate_fluid_properties_enthalpie_incompressible(), Fluide_reel_base::calculate_fluid_properties_incompressible(), Perte_Charge_Singuliere::calculate_Q(), Op_Conv_ALE_VEF::calculateALEjacobian(), Source_PDF_base::calculer(), Masse_Multiphase::calculer_alpha_rho(), Energie_cinetique_turbulente::calculer_alpha_rho_k(), Energie_cinetique_turbulente_WIT::calculer_alpha_rho_k_WIT(), calculer_champ_conserve(), Terme_Source_Canal_perio_VDF_Face::calculer_debit(), Terme_Source_Canal_perio_VEF_P1NC::calculer_debit(), Modele_turbulence_scal_LES_dyn_VDF::calculer_diffusivite_turbulente(), Op_Conv_VDF_base::calculer_dt_local(), Op_Dift_EF_Q1::calculer_dt_stab(), Op_Diff_PolyMAC_P0_Elem::calculer_dt_stab(), Op_Diff_PolyMAC_P0_Face::calculer_dt_stab(), Op_Diff_PolyMAC_P0P1NC_Elem::calculer_dt_stab(), Op_Diff_PolyMAC_P0P1NC_Face::calculer_dt_stab(), Op_Conv_Muscl_New_VEF_Face::calculer_dt_stab(), Fluide_base::calculer_e_int(), ParoiVDF_TBLE_LRM::calculer_hyd(), Paroi_std_hyd_VEF::calculer_hyd(), Paroi_negligeable_VDF::calculer_hyd(), Paroi_negligeable_VEF::calculer_hyd(), Paroi_std_hyd_VDF_diphasique::calculer_hyd(), Paroi_std_hyd_VEF_diphasique::calculer_hyd(), Paroi_loi_WW_hyd_EF::calculer_hyd(), Paroi_std_hyd_EF::calculer_hyd(), Paroi_2couches_VDF::calculer_hyd(), Paroi_loi_Ciofalo_hyd_VDF::calculer_hyd(), Paroi_loi_WW_hyd_VDF::calculer_hyd(), Paroi_loi_WW_hyd_VEF::calculer_hyd(), Paroi_std_hyd_VDF::calculer_hyd(), Paroi_UTAU_IMP_VDF::calculer_hyd(), ParoiVDF_TBLE::calculer_hyd(), ParoiVEF_TBLE::calculer_hyd(), Paroi_std_hyd_VDF::calculer_hyd_BiK(), Paroi_UTAU_IMP_VDF::calculer_hyd_BiK(), ParoiVDF_TBLE::calculer_hyd_BiK(), ParoiVDF_TBLE_LRM::calculer_hyd_BiK(), Paroi_std_hyd_VEF::calculer_hyd_BiK(), ParoiVEF_TBLE::calculer_hyd_BiK(), Op_Diff_VEFP1NCP1B_Face::calculer_laplacien_som(), Paroi_std_hyd_VDF::calculer_moyennes_parois(), Taux_dissipation_turbulent::calculer_omega(), Echange_contact_Correlation_VDF::calculer_Q(), Convection_Diffusion_Temperature::calculer_rho_cp_T(), Loi_Paroi_Nu_Impose_VDF::calculer_scal(), Loi_Paroi_Nu_Impose_VEF::calculer_scal(), Echelle_temporelle_turbulente::calculer_tau(), Neumann_paroi_rayo_semi_transp_VEF::calculer_temperature_bord(), Fluide_base::calculer_temperature_multiphase(), Echange_contact_ODVM_VDF::calculer_Teta_equiv(), Echange_contact_VDF::calculer_Teta_paroi(), Echange_contact_Rayo_transp_VDF::calculer_Teta_paroi(), Echange_contact_rayo_semi_transp_VDF::calculer_Teta_paroi(), Champ_base::calculer_valeurs_som_compo_post(), Champ_base::calculer_valeurs_som_post(), Source_PDF_EF::calculer_variable_imposee_mean_grad(), Modele_turbulence_hyd_combinaison::calculer_viscosite_turbulente(), Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl_u_star(), Schema_Adams_Moulton_base::changer_temps(), Schema_Backward_Differentiation_base::changer_temps(), Fluide_reel_base::check_unknown_range(), completer(), Operateur_base::completer(), Source_base::completer(), Cond_lim_omega_demi::completer(), Cond_lim_omega_dix::completer(), Echange_contact_Rayo_transp_VDF::completer(), Op_Diff_PolyMAC_P0_base::completer(), Op_Diff_PolyMAC_P0P1NC_base::completer(), Op_Diff_PolyMAC_P0_Elem::completer(), Op_Diff_PolyMAC_P0P1NC_Elem::completer(), Op_Diff_PolyMAC_P0P1NC_Face::completer(), Masse_PolyMAC_P0_Face::completer(), Source_Flux_interfacial_base::completer(), Op_Diff_VDF_base::completer(), Op_Dift_VDF_Face_Axi_base::completer(), Echange_contact_Correlation_VEF::completer(), Champ_Generique_Gradient::completer(), Champ_Generique_Morceau_Equation::completer(), Champ_Generique_Transformation::completer(), Champ_Post_Operateur_Eqn::completer(), Fluide_Dilatable_base::completer(), Source_PDF_EF::compute_coeff_elem(), Source_PDF_EF::compute_coeff_matrice(), Paroi_std_hyd_VDF::compute_law_komega(), Paroi_scal_hyd_base_EF::compute_nusselt(), Paroi_scal_hyd_base_VDF::compute_nusselt(), Paroi_scal_hyd_base_VEF::compute_nusselt(), Source_PDF_EF::compute_variable_imposee_projete(), Operateur_base::contribuer_a_avec(), Source_base::contribuer_a_avec(), Source_Transport_K_Eps_VEF_Face::contribuer_a_avec(), Source_Transport_K_Omega_VEF_Face::contribuer_a_avec(), Source_PDF_EF::contribuer_a_avec(), Op_Diff_VEF_Anisotrope_Face::contribuer_a_avec(), Op_Diff_VEF_Face::contribuer_a_avec(), Op_Diff_VEF_Face_Stab::contribuer_a_avec(), Terme_Source_Decroissance_Radioactive_VEF_Face::contribuer_a_avec(), Op_Diff_EF::contribuer_au_second_membre(), Op_Dift_EF_Q1::contribuer_au_second_membre(), Op_Dift_VEF_Face::contribuer_au_second_membre(), Operateur_base::contribuer_termes_croises(), Masse_VDF_Face::corriger_solution(), Masse_PolyMAC_P0P1NC_Face::corriger_solution(), Champ_front_contact_VEF::creer(), creer_champ(), Fluide_base::creer_e_int(), Fluide_base::creer_temperature_multiphase(), data_a_sauvegarder(), Transport_Interfaces_FT_Disc::deplacer_maillage_ft_v_fluide(), derivee_en_temps_inco(), Op_EF_base::dimensionner(), Op_PolyMAC_Elem::dimensionner(), Op_VDF_Face::dimensionner(), Op_VEF_Face::dimensionner(), Operateur_base::dimensionner(), Source_base::dimensionner(), Op_Div_PolyMAC_P0::dimensionner(), Solveur_Masse_base::dimensionner(), Op_Diff_K_Eps_Bas_Re_VDF_base::dimensionner_blocs(), Op_Diff_K_Eps_VDF_base::dimensionner_blocs(), Op_Diff_K_Omega_VDF_base::dimensionner_blocs(), Source_Transport_Eps_VDF_Elem::dimensionner_blocs(), Masse_DG_base::dimensionner_blocs(), Masse_PolyMAC_P0_Face::dimensionner_blocs(), Op_Diff_VDF_Elem_base::dimensionner_blocs(), Op_Diff_VDF_Face_base::dimensionner_blocs(), Op_Dift_VDF_Elem_base::dimensionner_blocs(), Op_Dift_VDF_Face_base::dimensionner_blocs(), Masse_VDF_base::dimensionner_blocs(), Perte_Charge_Singuliere_VDF_Face::dimensionner_blocs(), Op_Conv_EF_Stab_PolyMAC_P0_Face::dimensionner_blocs(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Face::dimensionner_blocs(), Coalescence_bulles_1groupe_PolyMAC_P0::dimensionner_blocs(), Coalescence_bulles_2groupes_PolyMAC_P0::dimensionner_blocs(), Flux_2groupes_PolyMAC_P0::dimensionner_blocs(), Rupture_bulles_1groupe_PolyMAC_P0::dimensionner_blocs(), Rupture_bulles_2groupes_PolyMAC_P0::dimensionner_blocs(), Variation_rho::dimensionner_blocs(), Diffusion_supplementaire_echelle_temp_turb_PolyMAC_P0::dimensionner_blocs(), Source_Diffusion_supplementaire_echelle_temp_turb::dimensionner_blocs(), Source_Dissipation_energie_cin_turb::dimensionner_blocs(), Source_Production_echelle_temp_taux_diss_turb::dimensionner_blocs(), Source_Production_energie_cin_turb::dimensionner_blocs(), Op_Diff_DG_Elem::dimensionner_blocs(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::dimensionner_blocs(), Op_Diff_PolyMAC_P0_Elem::dimensionner_blocs(), Perte_Charge_Singuliere_PolyMAC_P0P1NC_Face::dimensionner_blocs(), Terme_Source_Decroissance_Radioactive_Elem_PolyMAC::dimensionner_blocs(), Op_Evanescence_Homogene_Elem_base::dimensionner_blocs(), Source_Travail_pression_Elem_base::dimensionner_blocs(), DP_Impose_VEF_Face::dimensionner_blocs(), Op_Conv_VDF_base::dimensionner_blocs_elem(), Op_Diff_PolyMAC_P0P1NC_Elem::dimensionner_blocs_ext(), Op_Conv_VDF_base::dimensionner_blocs_face(), Assembleur_P_PolyMAC_P0P1NC::dimensionner_continuite(), Operateur_base::dimensionner_termes_croises(), discretiser(), Fluide_reel_base::discretiser(), Milieu_composite::discretiser(), Eq_rayo_semi_transp_VDF::evaluer_cl_rayonnement(), expression_residu(), Schema_Euler_explicite_ALE::faire_un_pas_de_temps_eqn_base(), RK3_MassRedistrib::faire_un_pas_de_temps_eqn_base(), Schema_Euler_explicite_Phase_field::faire_un_pas_de_temps_eqn_base(), Leap_frog::faire_un_pas_de_temps_eqn_base(), Pred_Cor::faire_un_pas_de_temps_eqn_base(), Schema_Euler_explicite::faire_un_pas_de_temps_eqn_base(), Schema_Euler_Implicite::faire_un_pas_de_temps_eqn_base(), Schema_Explicite_Multi_TimeStep_base::faire_un_pas_de_temps_eqn_base(), Schema_Implicite_Multi_TimeStep_base::faire_un_pas_de_temps_eqn_base(), RRK2::faire_un_pas_de_temps_eqn_base(), RK3_FT::faire_un_pas_de_temps_pb_couple(), Schema_Euler_Implicite::faire_un_pas_de_temps_pb_couple(), Transport_Interfaces_FT_Disc::fill_ftab_local_reference_frame_velocity(), Transport_Interfaces_FT_Disc::fill_ftab_velocity(), get_champ(), get_fonc_champ_conserve(), DG_discretisation::get_name_of_type_for(), PolyMAC_discretisation::get_name_of_type_for(), PolyMAC_P0P1NC_discretisation::get_name_of_type_for(), Discretisation_base::get_name_of_type_for(), ICoCo::ProblemTrio::getDirectAccessToUnknown(), Champ_Q1_EF::gradient(), Champ_Q1NC::gradient(), has_champ(), Domaine_Cl_EF::imposer_symetrie_matrice_secmem(), Source_PDF_EF::impr(), Op_EF_base::impr(), Op_VEF_Face::impr(), imprime_residu(), Loi_Paroi_Nu_Impose_VDF::imprimer_nusselt(), Loi_Paroi_Nu_Impose_VEF::imprimer_nusselt(), ParoiVDF_TBLE::imprimer_ustar(), ParoiVEF_TBLE::imprimer_ustar(), ParoiVDF_TBLE_LRM::imprimer_ustar(), init_champ_conserve(), ParoiVDF_TBLE::init_lois_paroi(), ParoiVDF_TBLE_LRM::init_lois_paroi(), Paroi_ODVM_scal_VDF::init_lois_paroi(), Paroi_TBLE_scal_VDF::init_lois_paroi(), ParoiVEF_TBLE::init_lois_paroi(), ParoiVEF_TBLE_scal::init_lois_paroi(), Couplage_Parietal_PolyMAC_helper::init_op_ext(), initialise_residu(), Op_Diff_VEFP1NCP1B_Face::initialiser(), Echange_couplage_thermique::initialiser(), Schema_Euler_Implicite::Initialiser_Champs(), Schema_Implicite_Multi_TimeStep_base::Initialiser_Champs(), initTimeStep(), Imprimer_Fichiers_RANS_VDF::interpreter(), Imprimer_Fichiers_RANS_VEF::interpreter(), Schema_Temps_base::iterateTimeStep(), RK3_FT::iterateTimeStep(), Schema_Phase_field::iterateTimeStep(), Pb_Dilatable_base::iterateTimeStep(), Multi_Sch_ThHyd::iterateTimeStep(), Sch_CN_iteratif::iterateTimeStepOnEquation(), Sch_CN_EX_iteratif::iterateTimeStepOnNS(), Sch_CN_EX_iteratif::iterateTimeStepOnOther(), SETS::iterer_eqn(), Simple::iterer_eqn(), Simple::iterer_eqs(), Schema_Implicite_Multi_TimeStep_base::Iterer_Pb(), Schema_Euler_Implicite::Iterer_Pb(), Postraitement::lire_champs_a_postraiter(), lire_cond_init(), Transport_K_Eps::lire_motcle_non_standard(), Transport_K_Omega::lire_motcle_non_standard(), Transport_K_ou_Eps::lire_motcle_non_standard(), Transport_K_ou_Eps_Realisable::lire_motcle_non_standard(), Convection_Diffusion_Turbulent::lire_op_diff_turbulent(), Transport_2eq_base::lire_op_diff_turbulent(), Paroi_frottante_simple::me_calculer(), mettre_a_jour(), Portance_interfaciale_PolyMAC_P0::mettre_a_jour(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::mettre_a_jour(), Aire_interfaciale::mettre_a_jour(), Fluide_reel_base::mettre_a_jour(), Interface_base::mettre_a_jour(), Echange_contact_VDF_FT_Disc_solid::mettre_a_jour(), PlaqThVDF::mettre_a_jour(), Op_Conv_VDF_base::mettre_a_jour(), Echange_contact_Correlation_VEF::mettre_a_jour(), Convection_Diffusion_Concentration_FT_Disc::mettre_a_jour_chimie(), Convection_Diffusion_Concentration_Turbulent_FT_Disc::mettre_a_jour_chimie(), Schema_Adams_Moulton_base::mettre_a_jour_equation(), Schema_Backward_Differentiation_base::mettre_a_jour_equation(), Milieu_composite::mettre_a_jour_tabs(), Op_VEF_Face::modifier_flux(), Op_VEF_Face::modifier_matrice_pour_periodique_apres_contribuer(), Op_Diff_Turbulent_PolyMAC_P0_Face::modifier_mu(), Op_EF_base::modifier_pour_Cl(), Op_VDF_Face::modifier_pour_Cl(), Op_VEF_Face::modifier_pour_Cl(), Op_Diff_K_Eps_VEF_Face::modifier_pour_Cl(), Op_Diff_K_Omega_VEF_Face::modifier_pour_Cl(), Schema_Adams_Bashforth_base::modifier_second_membre(), Terme_Source_Constituant::ouvrir_fichier(), Operateur_base::ouvrir_fichier(), Op_Diff_VEF_base::phi_psi_diffuse(), Op_Conv_EF_base::phi_u_transportant(), Op_Conv_VEF_base::phi_u_transportant(), preparer_calcul(), Pb_Dilatable_base::preparer_calcul(), Op_Evanescence_Homogene_VDF_Face::preparer_calcul(), printOn(), Source_Scalaire_EF::readOn(), List_Equations_Scalaires_Passifs_Especes::readOn(), Terme_Source_Decroissance_Radioactive_Elem_PolyMAC::readOn(), Terme_Source_Qdm_VDF_Face::readOn(), Terme_Source_Decroissance_Radioactive_VEF_Face::readOn(), reculer(), Op_Conv_ALE_VEF::remplir_fluent_ALEincluded(), Domaine_Cl_EF::remplir_type_elem_Cl(), reprendre(), resetTime(), Eq_rayo_semi_transp_VDF::resoudre(), Eq_rayo_semi_transp_VEF::resoudre(), sauvegarder(), Implicite_ALE::second_special_treatment(), Op_Diff_VEFP1NCP1B_Face::test(), Schema_Euler_Implicite::test_stationnaire(), Schema_Implicite_Multi_TimeStep_base::test_stationnaire(), Transport_Marqueur_FT::transformation(), Op_Diff_Fluctu_Temp::typer(), Op_Diff_Flux_Chaleur_Turb::typer(), Op_Diff_PolyMAC_P0P1NC_base::update_aux(), Schema_Temps_base::update_critere_statio(), Op_Diff_PolyMAC_Elem::update_delta_int(), Op_Grad_PolyMAC_P0_Face::update_grad(), Op_Diff_PolyMAC_P0_base::update_nu(), Op_Diff_PolyMAC_P0P1NC_base::update_nu(), Op_Diff_PolyMAC_P0_base::update_phif(), Echange_global_impose_rayo_semi_transp::verifie_ch_init_nb_comp(), Dirichlet::verifie_ch_init_nb_comp(), Echange_externe_impose::verifie_ch_init_nb_comp(), Neumann_paroi::verifie_ch_init_nb_comp(), Neumann_sortie_libre::verifie_ch_init_nb_comp(), Transport_K_Eps_non_std::vitesse_pour_transport(), Transport_K_Eps_Realisable::vitesse_pour_transport(), and Transport_K_ou_Eps_non_std::vitesse_pour_transport().
inconnue() [2/2]
virtual Champ_Inc_base & Equation_base::inconnue () pure virtual
Implemented in Convection_diffusion_turbulence_multiphase, Energie_cinetique_turbulente_WIT, IJK_Interfaces, IJK_Thermals, Navier_Stokes_FTD_IJK, Transport_Interfaces_FT_Disc, Transport_Marqueur_FT, Equation_rayonnement_base, Transport_K_Eps_base, Transport_K_Omega_base, Transport_K_ou_Eps_base, Transport_Fluctuation_Temperature, Transport_Fluctuation_Temperature_W, Transport_Flux_Chaleur_Turbulente, List_Equations_Scalaires_Passifs_Especes, Convection_Diffusion_Fluide_Dilatable_base, Convection_Diffusion_Concentration, Convection_Diffusion_Temperature, Navier_Stokes_std, Aire_interfaciale, Energie_Multiphase, Masse_Multiphase, Conduction, and Convection_Diffusion_std.
associer_milieu_base()
virtual void Equation_base::associer_milieu_base (const Milieu_base &) pure virtual
Implemented in Convection_diffusion_turbulence_multiphase, Energie_cinetique_turbulente_WIT, IJK_Interfaces, IJK_Thermals, Navier_Stokes_FTD_IJK, Equation_rayonnement_base, Transport_2eq_base, Transport_K_Eps_Bas_Reynolds, Transport_K_Eps_Realisable, Transport_K_KEps, Transport_Fluctuation_Temperature, Transport_Fluctuation_Temperature_W, Transport_Flux_Chaleur_Turbulente, Convection_Diffusion_Fluide_Dilatable_base, Convection_Diffusion_Concentration, Convection_Diffusion_Temperature, Convection_Diffusion_Temperature_base, Navier_Stokes_std, Aire_interfaciale, Masse_Multiphase, Conduction, Navier_Stokes_FT_Disc, List_Equations_Scalaires_Passifs_Especes, Convection_Diffusion_Temperature_FT_Disc, and Transport_Interfaces_FT_Disc.
Referenced by Probleme_base::associer_milieu_base(), Pb_Multiphase::associer_milieu_base(), Pb_Multiphase_Enthalpie::associer_milieu_base(), Probleme_FT_Disc_gen::associer_milieu_base(), Probleme_base::read_optional_equations(), and List_Equations_Scalaires_Passifs_Especes::readOn().
milieu() [1/2]
virtual const Milieu_base & Equation_base::milieu () const pure virtual
Implemented in Convection_diffusion_turbulence_multiphase, Energie_cinetique_turbulente_WIT, IJK_Interfaces, IJK_Thermals, Navier_Stokes_FTD_IJK, Convection_Diffusion_Temperature_FT_Disc, Navier_Stokes_FT_Disc, Transport_Interfaces_FT_Disc, Equation_rayonnement_base, Transport_2eq_base, Transport_Fluctuation_Temperature, Transport_Fluctuation_Temperature_W, Transport_Fluctuation_Temperature_W_Bas_Re, Transport_Flux_Chaleur_Turbulente, List_Equations_Scalaires_Passifs_Especes, Convection_Diffusion_Fluide_Dilatable_base, Convection_Diffusion_Concentration, Convection_Diffusion_Temperature_base, Navier_Stokes_std, Aire_interfaciale, Masse_Multiphase, and Conduction.
Referenced by Op_Div_PolyMAC::ajouter(), Op_Div_PolyMAC_P0::ajouter(), Op_Conv_Amont_old_VEF_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Centre_EF_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_EF_VEF_P1NC::ajouter(), Op_Conv_EF_VEF_P1NC_Stab::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_Muscl_New_VEF_Face::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Diff_VEF_Anisotrope_Face::ajouter(), Op_Diff_VEF_Face::ajouter(), Op_Diff_VEF_Face_Stab::ajouter(), Op_Diff_VEFP1NCP1B_Face::ajouter(), Op_Dift_Stab_VEF_Face::ajouter(), Op_Dift_VEF_Face::ajouter(), Op_Dift_VEF_Face_Q1::ajouter(), Op_Div_VEFP1B_Elem::ajouter(), Op_Diff_PolyMAC_Face::ajouter(), Source_Trainee::ajouter(), Source_Reaction_Particules_VDF::ajouter(), Source_Reaction_Particules_VEF::ajouter(), SourceFiltree_FT_disc_VEF_P1NC::ajouter(), Terme_Boussinesq_Sensibility_VEFPreP1B_Face::ajouter(), Source_Transport_Fluctuation_Temperature_VDF_Elem::ajouter(), Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::ajouter(), Source_Transport_Fluctuation_Temperature_W_VDF_Elem::ajouter(), Source_Transport_Flux_Chaleur_Turbulente_VDF_Face::ajouter(), Iterateur_Source_EF_Som< _TYPE_ >::ajouter(), Perte_Charge_PolyMAC::ajouter(), Perte_Charge_Singuliere_PolyMAC_Face::ajouter(), Source_Generique_Face_PolyMAC::ajouter(), Source_Generique_Face_PolyMAC_P0P1NC::ajouter(), Terme_Source_Qdm_Face_PolyMAC::ajouter(), Terme_Source_Canal_perio_VEF_P1NC::ajouter(), Terme_Source_Canal_RANS_LES_VEF_Face::ajouter(), Perte_Charge_Reguliere_VEF_P1NC::ajouter(), Perte_Charge_Singuliere_VEF_Face::ajouter(), Perte_Charge_VEF::ajouter(), Source_Generique_VEF::ajouter(), Terme_Boussinesq_VEF_Face::ajouter(), Terme_Boussinesq_VEFPreP1B_Face::ajouter(), Terme_Source_Acceleration_VEF_Face::ajouter(), Terme_Source_Qdm_lambdaup_VEF_Face::ajouter(), Terme_Source_Th_TdivU_VEF_Face::ajouter(), Perte_Charge_Reguliere_VDF_Face::ajouter_(), Op_Grad_VEF_P1B_Face::ajouter_aretes(), Tenseur_Reynolds_Externe_VDF_Face::ajouter_blocs(), Terme_Source_Canal_perio_VDF_Face::ajouter_blocs(), Terme_Source_Canal_RANS_LES_VDF_Face::ajouter_blocs(), Perte_Charge_Singuliere_VDF_Face::ajouter_blocs(), Source_Generique_VDF_Face::ajouter_blocs(), Terme_Boussinesq_VDF_Face::ajouter_blocs(), Terme_Source_Acceleration_VDF_Face::ajouter_blocs(), Terme_Source_Coriolis_VDF_Face::ajouter_blocs(), Terme_Source_inc_th_VDF_Face::ajouter_blocs(), Terme_Source_inc_VDF_Face::ajouter_blocs(), Terme_Source_Qdm_VDF_Face::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_P0_Face::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Face::ajouter_blocs(), Op_Grad_PolyMAC_P0_Face::ajouter_blocs(), Op_Grad_PolyMAC_P0P1NC_Face::ajouter_blocs(), Coalescence_bulles_1groupe_PolyMAC_P0::ajouter_blocs(), Coalescence_bulles_2groupes_PolyMAC_P0::ajouter_blocs(), Flux_2groupes_PolyMAC_P0::ajouter_blocs(), Injection_QDM_nulle_PolyMAC_P0::ajouter_blocs(), Rupture_bulles_1groupe_PolyMAC_P0::ajouter_blocs(), Rupture_bulles_2groupes_PolyMAC_P0::ajouter_blocs(), Variation_rho::ajouter_blocs(), Source_injection_masse_base::ajouter_blocs(), Injection_QDM_nulle_VDF::ajouter_blocs(), Diffusion_croisee_echelle_temp_taux_diss_turb_PolyMAC_P0::ajouter_blocs(), Diffusion_supplementaire_echelle_temp_turb_PolyMAC_P0::ajouter_blocs(), Dissipation_WIT_PolyMAC_P0::ajouter_blocs(), Production_echelle_temp_taux_diss_turb_PolyMAC_P0::ajouter_blocs(), Production_energie_cin_turb_PolyMAC_P0::ajouter_blocs(), Production_HZDR_PolyMAC_P0::ajouter_blocs(), Production_WIT_PolyMAC_P0::ajouter_blocs(), Source_BIF_PolyMAC_P0::ajouter_blocs(), Source_Dissipation_HZDR_PolyMAC_P0::ajouter_blocs(), Source_Dissipation_echelle_temp_taux_diss_turb::ajouter_blocs(), Source_Dissipation_energie_cin_turb::ajouter_blocs(), Diffusion_croisee_echelle_temp_taux_diss_turb_VDF::ajouter_blocs(), Diffusion_supplementaire_echelle_temp_turb_VDF::ajouter_blocs(), Production_echelle_temp_taux_diss_turb_VDF::ajouter_blocs(), Production_energie_cin_turb_VDF::ajouter_blocs(), Correction_Antal_PolyMAC_P0::ajouter_blocs(), Correction_Tomiyama_PolyMAC_P0::ajouter_blocs(), Dispersion_bulles_PolyMAC_P0::ajouter_blocs(), Frottement_interfacial_PolyMAC_P0::ajouter_blocs(), Portance_interfaciale_PolyMAC_P0::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::ajouter_blocs(), DP_Impose_PolyMAC_Face::ajouter_blocs(), Perte_Charge_Singuliere_PolyMAC_P0P1NC_Face::ajouter_blocs(), Terme_Boussinesq_PolyMAC_Face::ajouter_blocs(), Terme_Source_Decroissance_Radioactive_Elem_PolyMAC::ajouter_blocs(), Terme_Source_Qdm_Face_PolyMAC_P0P1NC::ajouter_blocs(), Op_Evanescence_Homogene_Elem_base::ajouter_blocs(), Op_Evanescence_Homogene_Face_base::ajouter_blocs(), Source_Force_Tchen_base::ajouter_blocs(), Source_Travail_pression_Elem_base::ajouter_blocs(), Correction_Antal_VDF::ajouter_blocs(), Dispersion_bulles_VDF::ajouter_blocs(), Frottement_interfacial_VDF::ajouter_blocs(), Portance_interfaciale_VDF::ajouter_blocs(), Op_Conv_Amont_VPoly_VDF_Face::ajouter_blocs(), DP_Impose_VEF_Face::ajouter_blocs(), Masse_PolyMAC_P0_Face::ajouter_blocs(), Masse_VDF_Face::ajouter_blocs(), Op_Evanescence_Homogene_PolyMAC_P0_Face::ajouter_blocs_aux(), Force_Tchen_PolyMAC_P0::ajouter_blocs_aux(), Correction_Lubchenko_PolyMAC_P0::ajouter_blocs_BIF(), Correction_Lubchenko_PolyMAC_P0::ajouter_blocs_disp(), Op_Div_PolyMAC_P0P1NC::ajouter_blocs_ext(), Correction_Lubchenko_PolyMAC_P0::ajouter_blocs_lift(), Op_Conv_Amont_old_VEF_Face::ajouter_contribution(), Op_Conv_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution(), Op_Diff_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Face_Stab::ajouter_contribution(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution(), Op_Conv_RT_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face_Stab::ajouter_contribution_multi_scalaire(), Op_Grad_VEF_P1B_Face::ajouter_elem(), Masse_PolyMAC_Elem::ajouter_masse(), Masse_PolyMAC_Face::ajouter_masse(), Op_Grad_VEF_P1B_Face::ajouter_som(), Op_Conv_ALE_VEF::ajouterALE(), Masse_PolyMAC_Elem::appliquer_impl(), Masse_PolyMAC_P0_Face::appliquer_impl(), Masse_PolyMAC_P0P1NC_Face::appliquer_impl(), Masse_VDF_Elem::appliquer_impl(), Masse_VDF_Face::appliquer_impl(), Masse_VEF_P1NC::appliquer_impl(), Assembleur_P_PolyMAC_P0::assembler_continuite(), Assembleur_P_PolyMAC_P0P1NC::assembler_continuite(), Assembleur_P_PolyMAC_P0::assembler_mat(), Assembleur_P_PolyMAC_P0P1NC::assembler_mat(), associer_milieu_equation(), Transport_K_Eps::associer_modele_turbulence(), Transport_K_Eps_Bas_Reynolds::associer_modele_turbulence(), Transport_K_Eps_Realisable::associer_modele_turbulence(), Transport_K_KEps::associer_modele_turbulence(), Transport_K_Omega::associer_modele_turbulence(), Transport_K_ou_Eps::associer_modele_turbulence(), Transport_K_ou_Eps_Realisable::associer_modele_turbulence(), Transport_Fluctuation_Temperature::associer_modele_turbulence(), Transport_Flux_Chaleur_Turbulente::associer_modele_turbulence(), Transport_Fluctuation_Temperature_W::associer_modele_turbulence(), Transport_Fluctuation_Temperature_W_Bas_Re::associer_modele_turbulence(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_VDF_Elem::associer_pb(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_VEF_Face::associer_pb(), Perte_Charge_PolyMAC_Face::associer_pb(), Source_QC_QDM_Gen::associer_pb(), Perte_Charge_VDF_Face::associer_pb(), Perte_Charge_VEF_Face::associer_pb(), Source_Transport_proto::associer_pb_anisotherme(), Source_Transport_proto::associer_pb_anisotherme_concen(), Source_Transport_proto::associer_pb_concen(), Modele_Jones_Launder_VDF::Calcul_D(), Modele_Jones_Launder_Thermique_VDF::Calcul_D(), Modele_Jones_Launder_VDF::Calcul_D_BiK(), Champ_P1NC::calcul_duidxj_paroi(), Champ_P1NC::calcul_h_conv(), Segment_poly::calcul_vc(), Tetra_poly::calcul_vc(), Point_EF::calcul_vc(), Segment_EF::calcul_vc(), Tetra_EF::calcul_vc(), Tri_EF::calcul_vc(), Champ_Q1_EF::calcul_y_plus(), Champ_P1NC::calcul_y_plus(), Champ_Face_VDF::calcul_y_plus(), Champ_P1NC::calcul_y_plus_diphasique(), Champ_Face_VDF::calcul_y_plus_diphasique(), Perte_Charge_Singuliere::calculate_Q(), Terme_Source_Constituant_Vortex_VEF_Face::calculer(), Masse_Multiphase::calculer_alpha_rho(), Energie_Multiphase::calculer_alpha_rho_e(), Energie_Multiphase::calculer_alpha_rho_h(), Terme_Source_Canal_perio_VDF_Face::calculer_debit(), Terme_Source_Canal_perio_VEF_P1NC::calculer_debit(), Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re::calculer_diffusivite_turbulente(), Op_Diff_DG_base::calculer_dt_stab(), Op_Conv_EF_Stab_PolyMAC_P0_Face::calculer_dt_stab(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::calculer_dt_stab(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Face::calculer_dt_stab(), Op_Diff_PolyMAC_base::calculer_dt_stab(), Op_Diff_PolyMAC_P0_Elem::calculer_dt_stab(), Op_Diff_PolyMAC_P0_Face::calculer_dt_stab(), Op_Diff_PolyMAC_P0P1NC_Elem::calculer_dt_stab(), Op_Diff_PolyMAC_P0P1NC_Face::calculer_dt_stab(), Op_Dift_Multiphase_VDF_Face::calculer_dt_stab(), Op_Conv_Muscl_New_VEF_Face::calculer_dt_stab(), Op_Diff_VEF_base::calculer_dt_stab(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab(), Echange_contact_Correlation_VDF::calculer_h_mon_pb(), Echange_contact_VDF::calculer_h_mon_pb(), Echange_contact_Correlation_VEF::calculer_h_solide(), ParoiVDF_TBLE_LRM::calculer_hyd(), Paroi_std_hyd_VEF::calculer_hyd(), Paroi_negligeable_VDF::calculer_hyd(), Paroi_negligeable_VEF::calculer_hyd(), Paroi_std_hyd_VDF_diphasique::calculer_hyd(), Paroi_std_hyd_VEF_diphasique::calculer_hyd(), Paroi_loi_WW_hyd_EF::calculer_hyd(), Paroi_std_hyd_EF::calculer_hyd(), Paroi_2couches_VDF::calculer_hyd(), Paroi_loi_Ciofalo_hyd_VDF::calculer_hyd(), Paroi_loi_WW_hyd_VDF::calculer_hyd(), Paroi_loi_WW_hyd_VEF::calculer_hyd(), Paroi_std_hyd_VDF::calculer_hyd(), Paroi_UTAU_IMP_VDF::calculer_hyd(), ParoiVDF_TBLE::calculer_hyd(), ParoiVEF_TBLE::calculer_hyd(), Paroi_std_hyd_VDF::calculer_hyd_BiK(), Paroi_UTAU_IMP_VDF::calculer_hyd_BiK(), ParoiVDF_TBLE::calculer_hyd_BiK(), ParoiVDF_TBLE_LRM::calculer_hyd_BiK(), Paroi_std_hyd_VEF::calculer_hyd_BiK(), ParoiVEF_TBLE::calculer_hyd_BiK(), Assembleur_P_VEF::calculer_inv_volume(), Domaine_EF::calculer_IPhi(), Domaine_EF_axi::calculer_IPhi(), Op_Diff_VEFP1NCP1B_Face::calculer_laplacien_som(), Paroi_std_hyd_VDF::calculer_moyennes_parois(), Source_Transport_Fluctuation_Temperature_VDF_Elem::calculer_Prod_uteta_T(), Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::calculer_Prod_uteta_T(), Source_Transport_Fluctuation_Temperature_W_VDF_Elem::calculer_Prod_uteta_T(), Convection_Diffusion_Temperature::calculer_rho_cp_T(), Paroi_std_scal_hyd_EF::calculer_scal(), Loi_Paroi_Nu_Impose_VDF::calculer_scal(), Paroi_loi_WW_scal_VDF::calculer_scal(), Paroi_ODVM_scal_VDF::calculer_scal(), Paroi_std_scal_hyd_VDF::calculer_scal(), Paroi_TBLE_scal_VDF::calculer_scal(), Loi_Paroi_Nu_Impose_VEF::calculer_scal(), Paroi_loi_WW_scal_VEF::calculer_scal(), Paroi_scal_analytique_VEF::calculer_scal(), Paroi_std_scal_hyd_VEF::calculer_scal(), ParoiVEF_TBLE_scal::calculer_scal(), Calcul_Production_K_VDF::calculer_terme_destruction_K(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_W_VDF_Elem::calculer_terme_destruction_K_W(), Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::calculer_terme_destruction_K_W(), Source_Transport_Fluctuation_Temperature_W_VDF_Elem::calculer_terme_destruction_K_W(), Domaine_EF::calculer_volumes_sommets(), Op_Diff_PolyMAC_P0_base::completer(), Echange_contact_Correlation_VEF::completer(), Champ_Generique_modifier_pour_QC::completer(), Paroi_std_hyd_VDF::compute_law_komega(), Paroi_scal_hyd_base_EF::compute_nusselt(), Paroi_scal_hyd_base_VDF::compute_nusselt(), Paroi_scal_hyd_base_VEF::compute_nusselt(), Op_Diff_PolyMAC_Face::contribuer_a_avec(), Perte_Charge_PolyMAC::contribuer_a_avec(), Perte_Charge_Singuliere_PolyMAC_Face::contribuer_a_avec(), Op_Dift_Stab_VEF_Face::contribuer_a_avec(), Op_Dift_VEF_Face::contribuer_a_avec(), Op_Dift_VEF_Face_Q1::contribuer_a_avec(), Perte_Charge_Reguliere_VEF_P1NC::contribuer_a_avec(), Perte_Charge_Singuliere_VEF_Face::contribuer_a_avec(), Perte_Charge_VEF::contribuer_a_avec(), Op_Div_PolyMAC::contribuer_a_avec(), Op_Div_PolyMAC_P0::contribuer_a_avec(), Op_Dift_VEF_Face::contribuer_au_second_membre(), Convection_Diffusion_std::diffusivite_pour_transport(), Variation_rho::dimensionner_blocs(), Probleme_base::discretiser(), Champ_val_tot_sur_vol_VDF::eval_contrib_loc(), Champ_val_tot_sur_vol_VEF::eval_contrib_loc(), get_champ(), Probleme_base::get_champ(), get_noms_champs_postraitables(), has_champ(), Probleme_base::has_champ(), Loi_Paroi_Nu_Impose_VDF::imprimer_nusselt(), Loi_Paroi_Nu_Impose_VEF::imprimer_nusselt(), ParoiVDF_TBLE::init_lois_paroi(), ParoiVDF_TBLE_LRM::init_lois_paroi(), Paroi_ODVM_scal_VDF::init_lois_paroi(), Paroi_TBLE_scal_VDF::init_lois_paroi(), ParoiVEF_TBLE::init_lois_paroi(), Champ_Face_PolyMAC::init_va(), Champ_Face_PolyMAC_P0::init_ve2(), Champ_front_pression_from_u::initialiser(), Champ_front_debit_massique::initialiser_coefficient(), Champ_Face_PolyMAC::interp_ve(), Champ_Face_PolyMAC_P0P1NC::interp_ve(), Pb_Dilatable_base::iterateTimeStep(), Y_plus_Champ_Face::me_calculer(), Y_plus_Champ_P1NC::me_calculer(), Portance_interfaciale_PolyMAC_P0::mettre_a_jour(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::mettre_a_jour(), Champ_front_synt::mettre_a_jour(), Op_Conv_VDF_base::mettre_a_jour(), Terme_Source_Canal_RANS_LES_VDF_Face::mettre_a_jour(), Champ_front_calc::milieu(), Probleme_base::milieu(), Champ_front_contact_VEF::milieu(), Op_EF_base::modifier_flux(), Op_VEF_Face::modifier_flux(), Op_Diff_Turbulent_PolyMAC_P0_Face::modifier_mu(), Assembleur_P_VEFPreP1B::modifier_secmem(), Assembleur_P_PolyMAC_P0P1NC::norme_continuite(), Champ_front_debit_QC::readOn(), Champ_front_debit_QC_fonc_t::readOn(), Op_Conv_VEF_Face::remplir_fluent(), Op_Diff_VEFP1NCP1B_Face::test(), Transport_Marqueur_FT::transformer_particules(), Probleme_base::typer_lire_milieu(), Pb_Phase_field::typer_lire_milieu(), Pb_Multiphase::typer_lire_milieu(), Op_Diff_PolyMAC_base::update_nu(), Op_Diff_PolyMAC_P0_base::update_nu(), Op_Diff_PolyMAC_P0P1NC_base::update_nu(), Champ_Face_PolyMAC_P0::update_ve(), Modele_turbulence_hyd_LES_base::verifie_loi_paroi_diphasique(), Source_Transport_proto::verifier_milieu_anisotherme(), Source_Transport_proto::verifier_milieu_anisotherme_concen(), and Source_Transport_proto::verifier_milieu_concen().
milieu() [2/2]
virtual Milieu_base & Equation_base::milieu () pure virtual
Implemented in Convection_diffusion_turbulence_multiphase, Energie_cinetique_turbulente_WIT, IJK_Interfaces, IJK_Thermals, Navier_Stokes_FTD_IJK, Convection_Diffusion_Temperature_FT_Disc, Navier_Stokes_FT_Disc, Transport_Interfaces_FT_Disc, Equation_rayonnement_base, Transport_2eq_base, Transport_Fluctuation_Temperature, Transport_Fluctuation_Temperature_W, Transport_Fluctuation_Temperature_W_Bas_Re, Transport_Flux_Chaleur_Turbulente, List_Equations_Scalaires_Passifs_Especes, Convection_Diffusion_Fluide_Dilatable_base, Convection_Diffusion_Concentration, Convection_Diffusion_Temperature_base, Navier_Stokes_std, Aire_interfaciale, Masse_Multiphase, and Conduction.
data_a_sauvegarder()
std::vector< YAML_data > Equation_base::data_a_sauvegarder () const virtual
for PDI IO: retrieve name, type and dimensions of the data to save/restore. This has to be overrode for all the equations that either:
have extra fields (ie in addition to the unknown) or extra scalars to save/restore.
want to save the unknown but with a different name These data will then be written in a YAML file, to initialize PDI. They have to be shared with PDI afterwards, when they need to be read/written (via TRUST_2_PDI)
Reimplemented in Navier_Stokes_std_ALE, Navier_Stokes_Turbulent_ALE, Navier_Stokes_FT_Disc, Transport_Interfaces_FT_Disc, Convection_Diffusion_Chaleur_Fluide_Dilatable_base, Convection_Diffusion_Espece_Fluide_Dilatable_base, Convection_Diffusion_Espece_Binaire_WC, Convection_Diffusion_Temperature_IBM_Turbulent, Navier_Stokes_IBM_Turbulent, Navier_Stokes_std, Convection_Diffusion_Chaleur_Turbulent_QC, Convection_Diffusion_Concentration_Turbulent, Convection_Diffusion_Temperature_Turbulent, and Navier_Stokes_Turbulent.
References Champ_Inc_base::data_a_sauvegarder(), and inconnue().
Referenced by Transport_Interfaces_FT_Disc::data_a_sauvegarder(), Modele_turbulence_hyd_RANS_Bicephale_base::data_a_sauvegarder(), Modele_turbulence_hyd_RANS_K_Eps_base::data_a_sauvegarder(), Modele_turbulence_hyd_RANS_K_Omega_base::data_a_sauvegarder(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::data_a_sauvegarder(), Convection_Diffusion_Espece_Fluide_Dilatable_base::data_a_sauvegarder(), Convection_Diffusion_Temperature_IBM_Turbulent::data_a_sauvegarder(), Navier_Stokes_std::data_a_sauvegarder(), Convection_Diffusion_Concentration_Turbulent::data_a_sauvegarder(), Convection_Diffusion_Temperature_Turbulent::data_a_sauvegarder(), and Convection_Diffusion_std::data_a_sauvegarder_base().
sauvegarder()
int Equation_base::sauvegarder (Sortie & os) const override virtual
On sauvegarde l'inconnue de l'equation sur un flot de sortie.
Parameters
(Sortie& os)
Returns
(int) le code de retour de Champ_Inc::sauvegarder()
Reimplemented from Objet_U.
Reimplemented in Navier_Stokes_std_ALE, Navier_Stokes_Turbulent_ALE, Navier_Stokes_FT_Disc, Transport_Interfaces_FT_Disc, Transport_Marqueur_FT, Convection_Diffusion_Chaleur_Fluide_Dilatable_base, Convection_Diffusion_Espece_Fluide_Dilatable_base, Convection_Diffusion_Chaleur_WC, Convection_Diffusion_Espece_Binaire_WC, Convection_Diffusion_Temperature_IBM_Turbulent, Navier_Stokes_IBM_Turbulent, Navier_Stokes_std, Convection_Diffusion_Chaleur_Turbulent_QC, Convection_Diffusion_Concentration_Turbulent, Convection_Diffusion_Temperature_Turbulent, and Navier_Stokes_Turbulent.
References inconnue(), and Champ_Inc_base::sauvegarder().
Referenced by Transport_Interfaces_FT_Disc::sauvegarder(), Probleme_base::sauvegarder(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::sauvegarder(), Convection_Diffusion_Espece_Fluide_Dilatable_base::sauvegarder(), Convection_Diffusion_Temperature_IBM_Turbulent::sauvegarder(), Navier_Stokes_std::sauvegarder(), Convection_Diffusion_Concentration_Turbulent::sauvegarder(), Convection_Diffusion_Temperature_Turbulent::sauvegarder(), Modele_turbulence_scal_Fluctuation_Temperature::sauvegarder(), Modele_turbulence_scal_Fluctuation_Temperature_W::sauvegarder(), Modele_turbulence_hyd_RANS_K_Eps_base::sauvegarder(), Modele_turbulence_hyd_RANS_K_Omega_base::sauvegarder(), and Convection_Diffusion_std::sauvegarder_base().
reprendre()
int Equation_base::reprendre (Entree & fich) override virtual
On reprend l'inconnue a partir d'un flot d'entree.
[ON CHERCHE L'INCONNUE PAR SON NOM] [ON LIT L'INCONNUE] Voir Champ_Inc::reprendre(Entree&)
Parameters
(Entree& fich) le flot d'entree (fichier) a lire
Returns
(int) renvoie toujours 1
Exceptions
erreur de reprise, fin de fichier atteinte sans trouver l'inconnue
Reimplemented from Objet_U.
Reimplemented in Navier_Stokes_std_ALE, Navier_Stokes_Turbulent_ALE, Navier_Stokes_FT_Disc, Transport_Interfaces_FT_Disc, Transport_Marqueur_FT, Convection_Diffusion_Chaleur_Fluide_Dilatable_base, Convection_Diffusion_Espece_Fluide_Dilatable_base, Convection_Diffusion_Chaleur_WC, Convection_Diffusion_Espece_Binaire_WC, Convection_Diffusion_Temperature_IBM_Turbulent, Navier_Stokes_IBM_Turbulent, Navier_Stokes_std, Convection_Diffusion_Chaleur_Turbulent_QC, Convection_Diffusion_Concentration_Turbulent, Convection_Diffusion_Temperature_Turbulent, and Navier_Stokes_Turbulent.
References Probleme_base::domaine(), inconnue(), TRUST_2_PDI::is_PDI_restart(), le_nom(), Domaine_base::le_nom(), probleme(), Objet_U::que_suis_je(), Champ_Inc_base::reprendre(), schema_temps(), and Schema_Temps_base::temps_courant().
Referenced by Transport_Interfaces_FT_Disc::reprendre(), Probleme_base::reprendre(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::reprendre(), Convection_Diffusion_Espece_Fluide_Dilatable_base::reprendre(), Convection_Diffusion_Temperature_IBM_Turbulent::reprendre(), Navier_Stokes_std::reprendre(), Convection_Diffusion_Concentration_Turbulent::reprendre(), Convection_Diffusion_Temperature_Turbulent::reprendre(), Modele_turbulence_scal_Fluctuation_Temperature::reprendre(), Modele_turbulence_scal_Fluctuation_Temperature_W::reprendre(), Modele_turbulence_hyd_RANS_K_Eps_base::reprendre(), Modele_turbulence_hyd_RANS_K_Omega_base::reprendre(), and Convection_Diffusion_std::reprendre_base().
init_save_file()
virtual void Equation_base::init_save_file () inline virtual
Reimplemented in Transport_Interfaces_FT_Disc.
close_save_file()
virtual void Equation_base::close_save_file () inline virtual
Reimplemented in Transport_Interfaces_FT_Disc.
limpr()
int Equation_base::limpr () const
Demande au schema en temps si il faut effectuer une impression.
Renvoie 1 si il faut effectuer une impression. Appel simple a Schema_Temps_base::limpr()
Returns
(int) 1 si il faut effectuer une impression, 0 sinon.
References le_schema_en_temps.
Referenced by Transport_K_Eps_base::controler_K_Eps(), Transport_K_Omega_base::controler_K_Omega(), Navier_Stokes_std::corriger_derivee_impl(), imprime_residu(), imprimer(), Transport_Interfaces_FT_Disc::mettre_a_jour(), and Navier_Stokes_FT_Disc::projeter().
imprimer()
void Equation_base::imprimer (Sortie & os) const virtual
Imprime les operateurs de l'equation si le schema en temps indique que c'est necessaire.
[SI limpr() ALORS impr(os)]
Parameters
(Sortie& os) le flot de sortie
Reimplemented in Navier_Stokes_Turbulent_ALE, Navier_Stokes_IBM_Turbulent, Navier_Stokes_Turbulent, Convection_Diffusion_Temperature_IBM_Turbulent, Convection_Diffusion_Chaleur_Turbulent_QC, Convection_Diffusion_Temperature_Turbulent, and Navier_Stokes_Turbulent_QC.
References impr(), limpr(), and Ecrire_fichier_xyz_valeur::write_fields().
Referenced by Navier_Stokes_Turbulent_ALE::imprimer(), Navier_Stokes_IBM_Turbulent::imprimer(), Navier_Stokes_Turbulent::imprimer(), Probleme_base::imprimer(), Convection_Diffusion_Temperature_IBM_Turbulent::imprimer(), Convection_Diffusion_Chaleur_Turbulent_QC::imprimer(), and Convection_Diffusion_Temperature_Turbulent::imprimer().
impr()
int Equation_base::impr (Sortie & os) const virtual
Imprime les operateurs de l'equation sur un flot de sortie, de facon inconditionnelle.
appelle Operateur_base::impr(os)
Parameters
(Sortie& os) le flot de sortie
Returns
(int) renvoie toujours 1
Reimplemented in Navier_Stokes_Turbulent_QC, Convection_diffusion_turbulence_multiphase, Energie_cinetique_turbulente_WIT, Transport_Interfaces_FT_Disc, Equation_rayonnement_base, Convection_Diffusion_Fluide_Dilatable_base, Navier_Stokes_Fluide_Dilatable_base, Navier_Stokes_QC, Navier_Stokes_WC, Convection_Diffusion_Concentration, Navier_Stokes_std, Aire_interfaciale, Energie_Multiphase, QDM_Multiphase, and Conduction.
References Sources::impr(), Operateur::impr(), les_sources, nombre_d_operateurs(), and operateur().
Referenced by Convection_diffusion_turbulence_multiphase::impr(), Energie_cinetique_turbulente_WIT::impr(), Convection_Diffusion_Fluide_Dilatable_base::impr(), Convection_Diffusion_Concentration::impr(), Navier_Stokes_std::impr(), Aire_interfaciale::impr(), Energie_Multiphase::impr(), QDM_Multiphase::impr(), Conduction::impr(), and imprimer().
associer_milieu_equation()
void Equation_base::associer_milieu_equation () virtual
Reimplemented in List_Equations_Scalaires_Passifs_Especes.
References Milieu_base::associer_equation(), and milieu().
Referenced by List_Equations_Scalaires_Passifs_Especes::associer_milieu_equation(), Probleme_base::discretiser(), Probleme_base::read_optional_equations(), Probleme_base::typer_lire_milieu(), Probleme_FT_Disc_gen::typer_lire_milieu(), Pb_Phase_field::typer_lire_milieu(), and Pb_Multiphase::typer_lire_milieu().
derivee_en_temps_inco()
DoubleTab & Equation_base::derivee_en_temps_inco (DoubleTab & derivee) virtual
Returns the time derivative of the unknown I of the equation: dI/dt = M-1*(sum(operators(I) + sources))
In : derivee contains I (but immediatly set to 0) Out: derivee contains dI/dt
Reimplemented in Convection_Diffusion_Temperature_FT_Disc, Navier_Stokes_phase_field, Convection_Diffusion_Chaleur_Fluide_Dilatable_base, Convection_Diffusion_Espece_Binaire_base, Navier_Stokes_Fluide_Dilatable_base, Convection_Diffusion_Espece_Multi_QC, Convection_Diffusion_Espece_Multi_WC, Convection_Diffusion_Temperature, Navier_Stokes_std, Navier_Stokes_Turbulent_QC, Convection_Diffusion_Espece_Fluide_Dilatable_base, Transport_Interfaces_FT_Disc, and Navier_Stokes_FT_Disc.
References Operateur::ajouter(), Sources::ajouter(), Solveur_Masse_base::ajouter_masse(), Solveur_Masse_base::appliquer(), Parametre_implicite::calcul_explicite(), calculate_time_derivative(), Operateur::calculer(), Operateur_base::contribuer_a_avec(), Operateur_base::contribuer_au_second_membre(), corriger_derivee_expl(), corriger_derivee_impl(), Solveur_Masse_base::corriger_solution(), derivee_en_temps(), derivee_en_temps_conv(), Operateur_base::dimensionner(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Objet_U_ptr::est_nul(), Process::exit(), Operateur_base::get_decal_temps(), Operateur_base::get_matrice(), Operateur_base::get_solveur(), get_time_factor(), Gradient_conjugue_diff_impl(), has_time_factor_, implicite_, inconnue(), Operateur::l_op_base(), les_sources, Schema_Temps_base::modifier_second_membre(), nombre_d_operateurs(), Objet_U_ptr::non_nul(), operateur(), parametre_equation_, Schema_Temps_base::pas_de_temps(), Objet_U::que_suis_je(), SolveurSys::resoudre_systeme(), schema_temps(), Matrice_Sym::set_est_definie(), Operateur_base::set_matrice(), Operateur_base::set_solveur(), solv_masse(), solveur_masse, sys_invariant_, Objet_U_ptr::typer(), TRUST_Deriv< _CLASSE_ >::valeur(), and Champ_Inc_base::valeurs().
Referenced by Convection_Diffusion_Temperature::derivee_en_temps_inco(), Navier_Stokes_std::derivee_en_temps_inco(), derivee_en_temps_inco_transport(), Schema_Euler_explicite_ALE::faire_un_pas_de_temps_eqn_base(), RK3_MassRedistrib::faire_un_pas_de_temps_eqn_base(), Schema_Euler_explicite_Phase_field::faire_un_pas_de_temps_eqn_base(), Leap_frog::faire_un_pas_de_temps_eqn_base(), Pred_Cor::faire_un_pas_de_temps_eqn_base(), Schema_Euler_explicite::faire_un_pas_de_temps_eqn_base(), Schema_Explicite_Multi_TimeStep_base::faire_un_pas_de_temps_eqn_base(), RRK2::faire_un_pas_de_temps_eqn_base(), RK3_FT::faire_un_pas_de_temps_pb_couple(), Schema_Temps_base::iterateTimeStep(), RK3_FT::iterateTimeStep(), Schema_Phase_field::iterateTimeStep(), Multi_Sch_ThHyd::iterateTimeStep(), Sch_CN_iteratif::iterateTimeStepOnEquation(), Sch_CN_EX_iteratif::iterateTimeStepOnNS(), Sch_CN_EX_iteratif::iterateTimeStepOnOther(), and Simple::iterer_eqn().
derivee_en_temps_inco_transport()
virtual DoubleTab & Equation_base::derivee_en_temps_inco_transport (DoubleTab & derivee) inline virtual
References derivee_en_temps_inco().
corriger_derivee_expl()
DoubleTab & Equation_base::corriger_derivee_expl (DoubleTab & d) virtual
Reimplemented in Navier_Stokes_std.
Referenced by Schema_Adams_Moulton_base::add_multi_timestep_data(), derivee_en_temps_inco(), and Schema_Adams_Moulton_base::modifier_second_membre_full_impl().
corriger_derivee_impl()
DoubleTab & Equation_base::corriger_derivee_impl (DoubleTab & d) virtual
Reimplemented in Navier_Stokes_std, Transport_K_Eps, Transport_K_Omega, Transport_K_ou_Eps, and Transport_K_ou_Eps_Realisable.
Referenced by Transport_K_Eps::corriger_derivee_impl(), Transport_K_Omega::corriger_derivee_impl(), Transport_K_ou_Eps::corriger_derivee_impl(), Transport_K_ou_Eps_Realisable::corriger_derivee_impl(), and derivee_en_temps_inco().
mettre_a_jour()
void Equation_base::mettre_a_jour (double temps) virtual
La valeur de l'inconnue sur le pas de temps a ete calculee.
Cette methode avance le present jusqu'au temps passe en parametre. Elle met aussi a jour les proprietes du milieu.
Parameters
(double temps) le pas de temps de mise a jour
Reimplemented in Convection_Diffusion_Concentration_FT_Disc, Convection_Diffusion_Concentration_Turbulent_FT_Disc, Convection_Diffusion_Temperature_FT_Disc, Navier_Stokes_FT_Disc, Transport_Interfaces_FT_Disc, Transport_Marqueur_FT, Convection_Diffusion_Temperature_sensibility, Navier_Stokes_std_sensibility, Navier_Stokes_Fluide_Dilatable_base, Navier_Stokes_std, Aire_interfaciale, QDM_Multiphase, Conduction, Navier_Stokes_std_ALE, Navier_Stokes_Turbulent_ALE, Energie_cinetique_turbulente, Navier_Stokes_phase_field, Convection_Diffusion_Temperature_IBM_Turbulent, Navier_Stokes_IBM_Turbulent, Convection_Diffusion_Concentration, Convection_Diffusion_Chaleur_Turbulent_QC, Convection_Diffusion_Concentration_Turbulent, Convection_Diffusion_Temperature_Turbulent, Navier_Stokes_Turbulent, and Navier_Stokes_Turbulent_QC.
References Domaine_Cl_dis_base::avancer(), calculate_time_derivative(), derivee_en_temps(), domaine_Cl_dis(), inconnue(), les_sources, Sources::mettre_a_jour(), Champ_Inc_base::mettre_a_jour(), and schema_temps().
Referenced by RK3_FT::faire_un_pas_de_temps_pb_couple(), RK3_FT::iterateTimeStep(), Simple::iterer_eqs(), Probleme_base::mettre_a_jour(), Probleme_FT_Disc_gen::mettre_a_jour(), Convection_Diffusion_Temperature_FT_Disc::mettre_a_jour(), Convection_Diffusion_Temperature_sensibility::mettre_a_jour(), Pb_Dilatable_base::mettre_a_jour(), Navier_Stokes_std::mettre_a_jour(), Aire_interfaciale::mettre_a_jour(), QDM_Multiphase::mettre_a_jour(), Conduction::mettre_a_jour(), Energie_cinetique_turbulente::mettre_a_jour(), Modele_turbulence_scal_Fluctuation_Temperature::mettre_a_jour(), Modele_turbulence_hyd_K_Eps::mettre_a_jour(), Modele_turbulence_hyd_K_Eps_2_Couches::mettre_a_jour(), Modele_turbulence_hyd_K_Eps_Bas_Reynolds::mettre_a_jour(), Modele_turbulence_hyd_K_Eps_Bicephale::mettre_a_jour(), Modele_turbulence_hyd_K_Eps_Realisable::mettre_a_jour(), Modele_turbulence_hyd_K_Eps_Realisable_Bicephale::mettre_a_jour(), Modele_turbulence_hyd_K_Omega::mettre_a_jour(), Convection_Diffusion_Temperature_IBM_Turbulent::mettre_a_jour(), Convection_Diffusion_Concentration::mettre_a_jour(), Convection_Diffusion_Chaleur_Turbulent_QC::mettre_a_jour(), Convection_Diffusion_Temperature_Turbulent::mettre_a_jour(), and Modele_rayo_semi_transp::validateTimeStep().
abortTimeStep()
void Equation_base::abortTimeStep () virtual
Reinitialiser ce qui doit l'etre.
Cette methode est appelee lorsqu'un pas de temps est abandonne, par exemple parce que le calcul a diverge. Il faut donc nettoyer ce qui pourrait polluer la nouvelle resolution.
Exceptions
WrongContext
Reimplemented in Navier_Stokes_std, and QDM_Multiphase.
References Champ_base::abortTimeStep(), Operateur_base::abortTimeStep(), champ_conserve_, champ_convecte_, inconnue(), Operateur::l_op_base(), nombre_d_operateurs(), Objet_U_ptr::non_nul(), and operateur().
Referenced by Schema_Temps_base::abortTimeStep(), Navier_Stokes_std::abortTimeStep(), and QDM_Multiphase::abortTimeStep().
resetTime()
void Equation_base::resetTime (double time) virtual
Reset current time of the equation. Used from ICoCo. See documentation of Problem_base::resetTime()
Reimplemented in Navier_Stokes_std.
References champ_conserve_, champ_convecte_, inconnue(), Operateur::l_op_base(), le_dom_Cl_dis, les_sources, nombre_d_operateurs(), Objet_U_ptr::non_nul(), operateur(), Solveur_Masse_base::resetTime(), Sources::resetTime(), Domaine_Cl_dis_base::resetTime(), Operateur_base::resetTime(), Champ_Inc_base::resetTime(), and solveur_masse.
Referenced by Navier_Stokes_std::resetTime(), and Probleme_base_interface_proto::resetTimeWithDir_impl().
valider_iteration()
void Equation_base::valider_iteration () virtual
methode virtuelle permettant de corriger l'onconnue lors d'iterations implicites par exemple K-eps doivent rester positifs
les fractions massqiues entre 0 et 1
Reimplemented in Transport_K_Eps_base, Transport_K_Omega_base, and Transport_K_ou_Eps_base.
Referenced by Simple::iterer_eqn().
preparer_calcul()
int Equation_base::preparer_calcul () virtual
Tout ce qui ne depend pas des autres problemes eventuels.
Returns
(int) renvoie toujours 1
Reimplemented in Navier_Stokes_Turbulent_ALE, IJK_Interfaces, IJK_Thermals, Navier_Stokes_FTD_IJK, Convection_Diffusion_Temperature_FT_Disc, Navier_Stokes_FT_Disc, Transport_Interfaces_FT_Disc, Transport_Marqueur_FT, Convection_Diffusion_Phase_field, Navier_Stokes_phase_field, Convection_Diffusion_Chaleur_Fluide_Dilatable_base, Convection_Diffusion_Espece_Binaire_base, Convection_Diffusion_Espece_Fluide_Dilatable_base, Navier_Stokes_Fluide_Dilatable_base, Convection_Diffusion_Chaleur_QC, Convection_Diffusion_Chaleur_WC, Convection_Diffusion_Temperature_IBM, Convection_Diffusion_Temperature_IBM_Turbulent, Navier_Stokes_IBM, Navier_Stokes_IBM_Turbulent, Convection_Diffusion_Concentration, Convection_Diffusion_Temperature, Navier_Stokes_std, QDM_Multiphase, Convection_Diffusion_Chaleur_Turbulent_QC, Convection_Diffusion_Concentration_Turbulent, Convection_Diffusion_Temperature_Turbulent, Navier_Stokes_Turbulent, Navier_Stokes_Turbulent_QC, and Conduction_IBM.
References TRUSTList< _TYPE_ >::add(), calculate_time_derivative(), Champ_Inc_base::changer_temps(), derivee_en_temps(), domaine_Cl_dis(), dt_op_bak, TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_Cl_dis_base::imposer_cond_lim(), inconnue(), initialise_residu(), Domaine_Cl_dis_base::initialiser(), Sources::initialiser(), Operateur::l_op_base(), le_dom_Cl_dis, les_sources, nombre_d_operateurs(), operateur(), Operateur_base::preparer_calcul(), Solveur_Masse_base::preparer_calcul(), Objet_U::que_suis_je(), schema_temps(), solveur_masse, Schema_Temps_base::temps_courant(), Champ_Inc_base::valeurs(), Champ_Inc_base::verifie_valeurs_cl(), and Debog::verifier().
Referenced by Probleme_base::preparer_calcul(), Convection_Diffusion_Temperature_FT_Disc::preparer_calcul(), Navier_Stokes_FT_Disc::preparer_calcul(), Navier_Stokes_phase_field::preparer_calcul(), Modele_turbulence_scal_Fluctuation_Temperature::preparer_calcul(), Modele_turbulence_hyd_K_Eps::preparer_calcul(), Modele_turbulence_hyd_K_Eps_2_Couches::preparer_calcul(), Modele_turbulence_hyd_K_Eps_Bas_Reynolds::preparer_calcul(), Modele_turbulence_hyd_K_Eps_Bicephale::preparer_calcul(), Modele_turbulence_hyd_K_Eps_Realisable::preparer_calcul(), Modele_turbulence_hyd_K_Eps_Realisable_Bicephale::preparer_calcul(), Modele_turbulence_hyd_K_Omega::preparer_calcul(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::preparer_calcul(), Convection_Diffusion_Espece_Fluide_Dilatable_base::preparer_calcul(), Convection_Diffusion_Temperature_IBM::preparer_calcul(), Navier_Stokes_IBM::preparer_calcul(), Convection_Diffusion_Concentration::preparer_calcul(), Convection_Diffusion_Temperature::preparer_calcul(), Navier_Stokes_std::preparer_calcul(), QDM_Multiphase::preparer_calcul(), and Conduction_IBM::preparer_calcul().
initTimeStep()
bool Equation_base::initTimeStep (double dt) virtual
Allocation et initialisation de l'inconnue et des CLs jusqu'a present+dt.
autres initialisations pour les calculs sur le prochain pas de temps : operateurs, solveur_masse->
Returns
(0 en cas d'erreur, 1 sinon)
Reimplemented in Navier_Stokes_Turbulent_ALE, Transport_Marqueur_FT, Equation_rayonnement_base, Navier_Stokes_Fluide_Dilatable_base, Convection_Diffusion_Temperature_IBM, Convection_Diffusion_Temperature_IBM_Turbulent, Navier_Stokes_IBM, Navier_Stokes_IBM_Turbulent, Navier_Stokes_std, QDM_Multiphase, Convection_Diffusion_Chaleur_Turbulent_QC, Convection_Diffusion_Concentration_Turbulent, Convection_Diffusion_Espece_Binaire_Turbulent_QC, Convection_Diffusion_Temperature_Turbulent, Navier_Stokes_Turbulent, Navier_Stokes_Turbulent_QC, and Conduction_IBM.
References calculate_time_derivative(), champ_conserve(), champ_conserve_, champ_convecte(), champ_convecte_, Domaine_Cl_dis_base::changer_temps_futur(), Champ_Inc_base::changer_temps_futur(), derivee_en_temps(), domaine_Cl_dis(), Champ_Inc_base::futur(), inconnue(), Operateur::mettre_a_jour(), Solveur_Masse_base::mettre_a_jour(), Schema_Temps_base::nb_valeurs_futures(), nombre_d_operateurs(), Objet_U_ptr::non_nul(), operateur(), Schema_Temps_base::pas_de_temps(), schema_temps(), Domaine_Cl_dis_base::set_temps_defaut(), solveur_masse, Schema_Temps_base::temps_courant(), Schema_Temps_base::temps_defaut(), Schema_Temps_base::temps_futur(), and Champ_Inc_base::valeurs().
Referenced by RK3_FT::faire_un_pas_de_temps_pb_couple(), Transport_Marqueur_FT::initTimeStep(), Equation_rayonnement_base::initTimeStep(), Modele_turbulence_scal_Fluctuation_Temperature::initTimeStep(), Modele_turbulence_scal_Fluctuation_Temperature_W::initTimeStep(), Modele_turbulence_hyd_K_Eps::initTimeStep(), Modele_turbulence_hyd_K_Eps_2_Couches::initTimeStep(), Modele_turbulence_hyd_K_Eps_Bas_Reynolds::initTimeStep(), Modele_turbulence_hyd_K_Eps_Bicephale::initTimeStep(), Modele_turbulence_hyd_K_Eps_Realisable::initTimeStep(), Modele_turbulence_hyd_K_Eps_Realisable_Bicephale::initTimeStep(), Modele_turbulence_hyd_K_Omega::initTimeStep(), Convection_Diffusion_Temperature_IBM::initTimeStep(), Navier_Stokes_std::initTimeStep(), QDM_Multiphase::initTimeStep(), Convection_Diffusion_Chaleur_Turbulent_QC::initTimeStep(), Convection_Diffusion_Concentration_Turbulent::initTimeStep(), Convection_Diffusion_Espece_Binaire_Turbulent_QC::initTimeStep(), Convection_Diffusion_Temperature_Turbulent::initTimeStep(), Conduction_IBM::initTimeStep(), Probleme_base_interface_proto::initTimeStep_impl(), and RK3_FT::iterateTimeStep().
updateGivenFields()
bool Equation_base::updateGivenFields () virtual
References Domaine_Cl_dis_base::calculer_derivee_en_temps(), domaine_Cl_dis(), Operateur::l_op_base(), les_sources, Domaine_Cl_dis_base::mettre_a_jour(), Operateur_base::mettre_a_jour(), Sources::mettre_a_jour(), Schema_Temps_base::nb_valeurs_futures(), nombre_d_operateurs(), Operateur::op_non_nul(), operateur(), Schema_Temps_base::pas_de_temps(), schema_temps(), Schema_Temps_base::temps_courant(), and Schema_Temps_base::temps_futur().
Referenced by Probleme_base_interface_proto::updateGivenFields_impl().
discretiser()
void Equation_base::discretiser () virtual
Discretise l'equation.
Type le domaine_Cl_dis, la formatte, l'associe a l'equation. Type le solveur masse, lui associe le domaine discretisee et le domaine des conditions aux limites discretisees.
Reimplemented in Navier_Stokes_std_ALE, Echelle_temporelle_turbulente, Energie_cinetique_turbulente, Energie_cinetique_turbulente_WIT, Taux_dissipation_turbulent, IJK_Interfaces, IJK_Thermals, Navier_Stokes_FTD_IJK, Convection_Diffusion_Temperature_FT_Disc, Navier_Stokes_FT_Disc, Transport_Interfaces_FT_Disc, Transport_Marqueur_FT, Convection_Diffusion_Phase_field, Navier_Stokes_phase_field, Navier_Stokes_Aposteriori, Equation_rayonnement_base, Transport_K_Eps_base, Transport_K_Omega_base, Transport_K_ou_Eps_base, Transport_Fluctuation_Temperature, Transport_Fluctuation_Temperature_W, Transport_Flux_Chaleur_Turbulente, List_Equations_Scalaires_Passifs_Especes, Convection_Diffusion_Chaleur_Fluide_Dilatable_base, Convection_Diffusion_Espece_Fluide_Dilatable_base, Navier_Stokes_Fluide_Dilatable_base, Convection_Diffusion_Concentration, Convection_Diffusion_Temperature, Navier_Stokes_std, Aire_interfaciale, Energie_Multiphase, Energie_Multiphase_Enthalpie, Masse_Multiphase, Navier_Stokes_Turbulent_QC, and Conduction.
References Champs_compris_T< FIELD_TYPE >::ajoute_champ(), Domaine_Cl_dis_base::associer(), Solveur_Masse_base::associer_domaine_cl_dis_base(), Solveur_Masse_base::associer_domaine_dis_base(), MorEqn::associer_eqn(), Domaine_Cl_dis_base::associer_inconnue(), calculate_time_derivative(), champs_compris_, derivee_en_temps_, discretisation(), Discretisation_base::discretiser_champ(), domaine_dis(), Discretisation_base::get_name_of_type_for(), inconnue(), le_dom_Cl_dis, Field_base::le_nom(), schema_temps(), solveur_masse, Objet_U_ptr::typer(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by Echelle_temporelle_turbulente::discretiser(), Energie_cinetique_turbulente::discretiser(), Energie_cinetique_turbulente_WIT::discretiser(), Taux_dissipation_turbulent::discretiser(), Convection_Diffusion_Temperature_FT_Disc::discretiser(), Equation_rayonnement_base::discretiser(), Transport_K_Eps_base::discretiser(), Transport_K_Omega_base::discretiser(), Transport_K_ou_Eps_base::discretiser(), Transport_Fluctuation_Temperature::discretiser(), Transport_Fluctuation_Temperature_W::discretiser(), Transport_Flux_Chaleur_Turbulente::discretiser(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::discretiser(), Convection_Diffusion_Espece_Fluide_Dilatable_base::discretiser(), Convection_Diffusion_Concentration::discretiser(), Convection_Diffusion_Temperature::discretiser(), Navier_Stokes_std::discretiser(), Aire_interfaciale::discretiser(), Energie_Multiphase::discretiser(), Energie_Multiphase_Enthalpie::discretiser(), Masse_Multiphase::discretiser(), Conduction::discretiser(), Modele_rayo_semi_transp::discretiser(), Probleme_base::discretiser_equations(), Probleme_base::read_optional_equations(), and List_Equations_Scalaires_Passifs_Especes::readOn().
associer_pb_base()
void Equation_base::associer_pb_base (const Probleme_base & pb) virtual
S'associe au Probleme passe en parametre.
Associe egalement les sources, les operateurs et le solveur de masse a l'equation.
Parameters
(Probleme_base& pb) le probleme auquel l'equation doit s'associer
Reimplemented in IJK_Interfaces, IJK_Thermals, Navier_Stokes_FTD_IJK, Navier_Stokes_std, Equation_rayonnement_base, Navier_Stokes_FT_Disc, and Transport_Interfaces_FT_Disc.
References MorEqn::associer_eqn(), Probleme_U::le_nom(), les_sources, mon_probleme, nom_, nombre_d_operateurs(), operateur(), and Objet_U::que_suis_je().
Referenced by Probleme_FT_Disc_gen::add_FT_equation(), Probleme_base::associer(), Transport_2eq_base::associer(), Transport_Fluctuation_Temperature::associer_modele_turbulence(), Transport_Flux_Chaleur_Turbulente::associer_modele_turbulence(), Transport_Fluctuation_Temperature_W::associer_modele_turbulence(), Transport_Fluctuation_Temperature_W_Bas_Re::associer_modele_turbulence(), Navier_Stokes_std::associer_pb_base(), Equation_rayonnement_base::associer_pb_base(), Transport_Interfaces_FT_Disc::associer_pb_base(), Probleme_base::read_optional_equations(), and List_Equations_Scalaires_Passifs_Especes::readOn().
completer()
void Equation_base::completer () virtual
Complete la construction (initialisation) des objets associes a l'equation.
Complete les sources, associe l'equation a l'inconnue complete les operateurs, complete les conditions aux limites discretisees. Voir les methodes Source_base::completer(), Operateur_base::completer() Domaine_Cl_dis_base::completer() Domaine_Cl_dis_base::completer(const Domaine_dis_base&)
Reimplemented in Navier_Stokes_Turbulent_ALE, Convection_diffusion_turbulence_multiphase, IJK_Interfaces, IJK_Thermals, Navier_Stokes_FTD_IJK, Convection_Diffusion_Temperature_FT_Disc, Transport_Marqueur_FT, Convection_Diffusion_Phase_field, Navier_Stokes_phase_field, Equation_rayonnement_base, Eq_rayo_semi_transp_VDF, Eq_rayo_semi_transp_VEF, Transport_K_Eps_Bas_Reynolds, Transport_K_Eps_Realisable, Transport_K_Omega, Transport_Fluctuation_Temperature, Transport_Fluctuation_Temperature_W, Transport_Flux_Chaleur_Turbulente, Convection_Diffusion_Espece_Binaire_base, Navier_Stokes_Fluide_Dilatable_base, Convection_Diffusion_Espece_Binaire_QC, Convection_Diffusion_Espece_Multi_QC, Navier_Stokes_QC, Convection_Diffusion_Chaleur_WC, Convection_Diffusion_Espece_Binaire_WC, Convection_Diffusion_Espece_Multi_WC, Navier_Stokes_WC, Convection_Diffusion_Temperature_IBM_Turbulent, Navier_Stokes_IBM_Turbulent, Navier_Stokes_std, Masse_Multiphase, QDM_Multiphase, Convection_Diffusion_Chaleur_Turbulent_QC, Convection_Diffusion_Concentration_Turbulent, Convection_Diffusion_Temperature_Turbulent, Navier_Stokes_Turbulent, and Navier_Stokes_Turbulent_QC.
References Champ_Inc_base::associer_domaine_cl_dis(), Champ_Inc_base::associer_eqn(), Domaine_Cl_dis_base::completer(), Operateur::completer(), Solveur_Masse_base::completer(), Sources::completer(), Schema_Temps_base::completer(), Nom::debute_par(), Process::exit(), Frontiere_dis_base::frontiere(), Cond_lim_base::frontiere_dis(), Operateur_base::get_decal_temps(), implicite_, inconnue(), initialise_residu(), Operateur::l_op_base(), le_dom_Cl_dis, TRUST_Ref< _CLASSE_ >::le_nom(), Frontiere_32_64< _SIZE_ >::le_nom(), Domaine_Cl_dis_base::les_conditions_limites(), les_sources, liste_modeles_, mon_probleme, Domaine_Cl_dis_base::nb_cond_lim(), nombre_d_operateurs(), Objet_U_ptr::non_nul(), operateur(), Objet_U::que_suis_je(), schema_temps(), solv_masse(), solveur_masse, sys_invariant_, Operateur_base::systeme_invariant(), and Debog::verifier().
Referenced by Probleme_base::completer(), Convection_diffusion_turbulence_multiphase::completer(), Convection_Diffusion_Temperature_FT_Disc::completer(), Convection_Diffusion_Phase_field::completer(), Equation_rayonnement_base::completer(), Transport_K_Eps_Bas_Reynolds::completer(), Transport_K_Eps_Realisable::completer(), Transport_K_Omega::completer(), Transport_Fluctuation_Temperature_W::completer(), Modele_turbulence_hyd_K_Eps_2_Couches::completer(), Modele_turbulence_hyd_K_Eps_Bas_Reynolds::completer(), Modele_turbulence_hyd_RANS_Bicephale_base::completer(), Modele_turbulence_hyd_RANS_K_Eps_base::completer(), Modele_turbulence_hyd_RANS_K_Omega_base::completer(), Convection_Diffusion_Espece_Binaire_base::completer(), Convection_Diffusion_Espece_Multi_QC::completer(), Convection_Diffusion_Chaleur_WC::completer(), Convection_Diffusion_Espece_Multi_WC::completer(), Convection_Diffusion_Temperature_IBM_Turbulent::completer(), Navier_Stokes_std::completer(), Masse_Multiphase::completer(), Convection_Diffusion_Chaleur_Turbulent_QC::completer(), Convection_Diffusion_Concentration_Turbulent::completer(), and Convection_Diffusion_Temperature_Turbulent::completer().
calculer_pas_de_temps()
double Equation_base::calculer_pas_de_temps () const virtual
Calcul du prochain pas de temps.
Renvoie l'inverse de la somme des inverses des pas de temps calcules par les operateurs. Ces pas de temps sont ceux pour le schema d'Euler explicite. Le pas de temps n'est pas majore par dt_max, ceci est fait dans corriger_dt_calcule
Returns
(double) inverse de la somme des inverses des pas de temps calcules par les operateurs
Reimplemented in Transport_Interfaces_FT_Disc, Navier_Stokes_phase_field, and Transport_2eq_base.
References Operateur::calculer_pas_de_temps(), dt_op_bak, Operateur::l_op_base(), le_schema_en_temps, nombre_d_operateurs(), operateur(), Objet_U::que_suis_je(), TRUST_Ref< _CLASSE_ >::valeur(), and Debog::verifier().
Referenced by Probleme_base::calculer_pas_de_temps(), Transport_2eq_base::calculer_pas_de_temps(), Sch_CN_EX_iteratif::iterateTimeStepOnOther(), Sch_CN_EX_iteratif::mettre_a_jour_dt_stab(), Navier_Stokes_IBM::preparer_calcul(), Navier_Stokes_std::preparer_calcul(), and Navier_Stokes_std::projeter().
calculer_pas_de_temps_locaux()
void Equation_base::calculer_pas_de_temps_locaux (DoubleTab & dt_op) const
References Operateur::calculer_pas_de_temps_locaux(), Process::exit(), Operateur::l_op_base(), nombre_d_operateurs(), and operateur().
Referenced by Schema_Euler_Implicite_Stationnaire::calculer_pas_de_temps_local_pb().
sources() [1/2]
Sources & Equation_base::sources ()
Renvoie les termes sources asssocies a l'equation.
Returns
(Sources&) la liste des termes sources associees a l'equation
References les_sources.
Referenced by Source_Gravite_PF_VDF::ajouter(), Injection_QDM_nulle_PolyMAC_P0::ajouter_blocs(), Injection_QDM_nulle_VDF::ajouter_blocs(), Source_Flux_interfacial_base::ajouter_blocs(), assembler(), Convection_Diffusion_Temperature::assembler(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_avec_inertie_impl(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_blocs(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_blocs_avec_inertie(), Convection_Diffusion_Espece_Multi_QC::assembler_blocs_avec_inertie(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_impl(), ParoiVDF_TBLE_LRM::calculer_hyd(), ParoiVDF_TBLE::calculer_hyd(), ParoiVDF_TBLE::calculer_hyd_BiK(), ParoiVDF_TBLE_LRM::calculer_hyd_BiK(), Navier_Stokes_phase_field::calculer_mu(), Navier_Stokes_phase_field::calculer_rho(), Paroi_ODVM_scal_VDF::calculer_scal(), Paroi_TBLE_scal_VDF::calculer_scal(), ParoiVEF_TBLE_scal::calculer_scal(), Correction_Lubchenko_PolyMAC_P0::completer(), Source_Robin_Scalaire::completer(), Convection_Diffusion_Fluide_Dilatable_Proto::derivee_en_temps_inco_sans_solveur_masse_impl(), RK3_MassRedistrib::faire_un_pas_de_temps_eqn_base(), Schema_Euler_explicite_Phase_field::faire_un_pas_de_temps_eqn_base(), ParoiVDF_TBLE::init_lois_paroi(), Paroi_TBLE_scal_VDF::init_lois_paroi(), ParoiVEF_TBLE::init_lois_paroi(), Pb_Couple_rayo_semi_transp::initialize(), Navier_Stokes_IBM::initTimeStep(), Transport_Marqueur_FT::lire_motcle_non_standard(), Source_Qdm_VDF_Phase_field::methode_1(), Source_Qdm_VDF_Phase_field::methode_2(), Source_Qdm_VDF_Phase_field::methode_3(), Source_Qdm_VDF_Phase_field::methode_4(), Probleme_base::newCompute(), Probleme_base::postraiter(), Schema_Phase_field::premier_dt(), Convection_Diffusion_Phase_field::preparer_calcul(), Modele_rayo_semi_transp::preparer_calcul(), Navier_Stokes_IBM::preparer_calcul(), Navier_Stokes_std::preparer_calcul(), Flux_2groupes_PolyMAC_P0::readOn(), Nucleation_paroi_PolyMAC_P0::readOn(), Energie_Multiphase::readOn(), Masse_Multiphase::readOn(), and Equation_IBM_proto::readOn_ibm_proto().
sources() [2/2]
const Sources & Equation_base::sources () const
Renvoie les termes sources asssocies a l'equation (version const)
Returns
(Sources&) la liste des termes sources associees a l'equation
References les_sources.
solv_masse() [1/2]
Solveur_Masse_base & Equation_base::solv_masse () inline
Renvoie le solveur de masse associe a l'equation.
Returns
(Solveur_Masse_base&) le solveur de masse associe a l'equation
References solveur_masse.
Referenced by Schema_Adams_Moulton_base::add_multi_timestep_data(), Schema_Backward_Differentiation_base::add_multi_timestep_data(), Operateur::ajouter(), Schema_Temps_base::ajouter_blocs(), Schema_Temps_base::ajouter_inertie(), Schema_Euler_Implicite_Stationnaire::ajouter_inertie(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_avec_inertie_impl(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_blocs_avec_inertie(), assembler_blocs_avec_inertie(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_impl(), Transport_Interfaces_FT_Disc::calcul_effort_fluide_interface(), Source_Con_Phase_field::calculer_alpha_gradC_carre(), calculer_champ_conserve(), Source_Con_Phase_field::calculer_div_alpha_gradC(), Source_Con_Phase_field::calculer_div_alpha_rho_gradC(), Assembleur_P_VEF::calculer_inv_volume(), Source_Con_Phase_field::calculer_mutilde_demi(), Transport_Marqueur_FT::calculer_proprietes_fluide_pos_particules(), completer(), Convection_Diffusion_Temperature_FT_Disc::compute_divergence_free_velocity_extension(), derivee_en_temps_inco(), Navier_Stokes_std::derivee_en_temps_inco(), Convection_Diffusion_Fluide_Dilatable_Proto::derivee_en_temps_inco_sans_solveur_masse_impl(), dimensionner_blocs(), dimensionner_matrice_sans_mem(), Source_Con_Phase_field::div_kappa_grad(), Champ_Generique_Gradient::get_champ(), has_interface_blocs(), SETS::iterer_NS(), Source_Con_Phase_field::laplacien(), QDM_Multiphase::mettre_a_jour(), Schema_Adams_Bashforth_base::modifier_second_membre(), Schema_Adams_Moulton_base::modifier_second_membre_full_impl(), Transport_Interfaces_FT_Disc::modifier_vpoint_pour_imposer_vit(), Implicite_ALE::second_special_treatment(), Op_Diff_VEFP1NCP1B_Face::test(), and Navier_Stokes_std::uzawa().
solv_masse() [2/2]
const Solveur_Masse_base & Equation_base::solv_masse () const inline
Renvoie le solveur de masse associe a l'equation.
(version const)
Returns
(Solveur_Masse_base&) le solveur de masse associe a l'equation
References solveur_masse.
probleme() [1/2]
Probleme_base & Equation_base::probleme ()
Renvoie le probleme associe a l'equation.
Returns
(Probleme_base&) le probleme associe a l'equation
References mon_probleme, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Modele_turbulence_hyd_base::a_faire(), Modele_turbulence_scal_base::a_faire(), Op_Dift_VDF_base::ajoute_terme_pour_axi_turb(), Source_Flottabilite::ajouter(), Source_Trainee::ajouter(), Source_Reaction_Particules_VDF::ajouter(), Source_Reaction_Particules_VEF::ajouter(), Op_Grad_VDF_Face::ajouter_blocs(), Op_Grad_PolyMAC_P0_Face::ajouter_blocs(), Coalescence_bulles_1groupe_PolyMAC_P0::ajouter_blocs(), Coalescence_bulles_2groupes_PolyMAC_P0::ajouter_blocs(), Flux_2groupes_PolyMAC_P0::ajouter_blocs(), Rupture_bulles_1groupe_PolyMAC_P0::ajouter_blocs(), Rupture_bulles_2groupes_PolyMAC_P0::ajouter_blocs(), Variation_rho::ajouter_blocs(), Diffusion_supplementaire_echelle_temp_turb_PolyMAC_P0::ajouter_blocs(), Dissipation_WIT_PolyMAC_P0::ajouter_blocs(), Production_echelle_temp_taux_diss_turb_PolyMAC_P0::ajouter_blocs(), Production_energie_cin_turb_PolyMAC_P0::ajouter_blocs(), Production_HZDR_PolyMAC_P0::ajouter_blocs(), Production_WIT_PolyMAC_P0::ajouter_blocs(), Source_BIF_PolyMAC_P0::ajouter_blocs(), Source_Dissipation_HZDR_PolyMAC_P0::ajouter_blocs(), Source_Dissipation_energie_cin_turb::ajouter_blocs(), Production_echelle_temp_taux_diss_turb_VDF::ajouter_blocs(), Production_energie_cin_turb_VDF::ajouter_blocs(), Correction_Antal_PolyMAC_P0::ajouter_blocs(), Correction_Tomiyama_PolyMAC_P0::ajouter_blocs(), Dispersion_bulles_PolyMAC_P0::ajouter_blocs(), Frottement_interfacial_PolyMAC_P0::ajouter_blocs(), Portance_interfaciale_PolyMAC_P0::ajouter_blocs(), DP_Impose_PolyMAC_Face::ajouter_blocs(), Op_Evanescence_Homogene_Face_base::ajouter_blocs(), Source_Flux_interfacial_base::ajouter_blocs(), Source_Force_Tchen_base::ajouter_blocs(), Correction_Antal_VDF::ajouter_blocs(), Dispersion_bulles_VDF::ajouter_blocs(), Frottement_interfacial_VDF::ajouter_blocs(), Portance_interfaciale_VDF::ajouter_blocs(), DP_Impose_VEF_Face::ajouter_blocs(), Op_Evanescence_Homogene_PolyMAC_P0_Face::ajouter_blocs_aux(), Force_Tchen_PolyMAC_P0::ajouter_blocs_aux(), Correction_Lubchenko_PolyMAC_P0::ajouter_blocs_BIF(), Correction_Lubchenko_PolyMAC_P0::ajouter_blocs_disp(), Correction_Lubchenko_PolyMAC_P0::ajouter_blocs_lift(), Op_Conv_EF::ajouter_contribution_sous_cond(), QDM_Multiphase::alpha_res(), assembler(), Convection_Diffusion_Temperature::assembler(), assembler_blocs(), Convection_Diffusion_Temperature::assembler_blocs(), Assembleur_P_PolyMAC_P0P1NC::assembler_continuite(), Convection_Diffusion_Temperature_sensibility::associate_evaluator_field(), Navier_Stokes_std_sensibility::associate_evaluator_field(), Op_Grad_EF::associer(), Transport_2eq_base::associer(), Milieu_base::associer_equation(), Transport_Fluctuation_Temperature::associer_modele_turbulence(), Transport_Flux_Chaleur_Turbulente::associer_modele_turbulence(), Transport_Fluctuation_Temperature_W::associer_modele_turbulence(), Transport_Fluctuation_Temperature_W_Bas_Re::associer_modele_turbulence(), Op_Evanescence_Homogene_PolyMAC_P0_Face::calc_vort_elem(), Op_Evanescence_Homogene_Face_base::calc_vort_faces(), Modele_turbulence_scal_LES_dyn_VDF::calcul_voisins(), Champ_P1NC::calcul_y_plus_diphasique(), Champ_Face_VDF::calcul_y_plus_diphasique(), Modele_turbulence_hyd_RANS_Gen< MODELE >::calculate_limit_viscosity(), Perte_Charge_Singuliere::calculate_Q(), Op_Conv_ALE_VEF::calculateALEjacobian(), Energie_Multiphase::calculer_alpha_rho_e(), Energie_Multiphase::calculer_alpha_rho_h(), Terme_Source_Canal_perio_VEF_P1NC::calculer_debit(), Modele_turbulence_scal_LES_dyn_VDF::calculer_diffusivite_turbulente(), Convection_Diffusion_Chaleur_QC::calculer_div_u_ou_div_rhou(), Op_Conv_EF::calculer_dt_stab(), Terme_Source_Coriolis_VDF_Face::calculer_force_de_Coriolis(), Modele_turbulence_scal_LES_dyn_VDF::calculer_grad_teta(), Paroi_std_hyd_VDF_diphasique::calculer_hyd(), Paroi_std_hyd_VEF_diphasique::calculer_hyd(), Navier_Stokes_phase_field::calculer_pas_de_temps(), Transport_2eq_base::calculer_pas_de_temps(), Transport_Marqueur_FT::calculer_proprietes_fluide_pos_particules(), ParoiVEF_TBLE_scal::calculer_scal(), Echange_contact_ODVM_VDF::calculer_Teta_equiv(), Echange_contact_Rayo_transp_VDF::calculer_Teta_paroi(), Modele_turbulence_hyd_combinaison::calculer_viscosite_turbulente(), Terme_Boussinesq_base::check(), Source_base::completer(), Cond_lim_omega_demi::completer(), Cond_lim_omega_dix::completer(), Diffusion_croisee_echelle_temp_taux_diss_turb_PolyMAC_P0::completer(), Op_Diff_K_Eps_Bas_Re_VDF_var_Elem::completer(), Source_Robin_Scalaire::completer(), Transport_K_Eps_Bas_Reynolds::completer(), Transport_K_Eps_Realisable::completer(), Op_Diff_PolyMAC_P0_Elem::completer(), Navier_Stokes_Fluide_Dilatable_base::completer(), Perte_Charge_Gen::completer(), Modele_turbulence_scal_diffturb_base::completer(), Echange_interne_impose::completer(), Op_Conv_EF_VEF_P1NC_Stab::completer(), Perte_Charge_VEF::completer(), Source_PDF_EF::compute_coeff_elem(), Source_PDF_EF::compute_coeff_matrice(), Paroi_scal_hyd_base_EF::compute_nusselt(), Paroi_scal_hyd_base_VDF::compute_nusselt(), Paroi_scal_hyd_base_VEF::compute_nusselt(), Source_PDF_EF::compute_pond(), Convection_Diffusion_Concentration::constituant(), Transport_Marqueur_FT::construction_ensemble_proprietes(), Operateur_base::contribuer_termes_croises(), Transport_K_Eps_base::controler_K_Eps(), Transport_K_Omega_base::controler_K_Omega(), Transport_K_ou_Eps_base::controler_variable(), Navier_Stokes_std::corriger_derivee_impl(), Transport_K_Eps::corriger_derivee_impl(), Transport_K_Omega::corriger_derivee_impl(), Transport_Marqueur_FT::creer_champ(), Navier_Stokes_phase_field::creer_champ(), Navier_Stokes_Aposteriori::creer_champ(), Source_PDF_EF::creer_champ(), Paroi_hyd_base_EF::creer_champ(), QDM_Multiphase::creer_champ(), Turbulence_paroi_base::creer_champ(), Navier_Stokes_std_ALE::data_a_sauvegarder(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::data_a_sauvegarder(), Convection_Diffusion_Fluide_Dilatable_Proto::data_a_sauvegarder(), Convection_Diffusion_Temperature_FT_Disc::derivee_en_temps_inco(), Coalescence_bulles_1groupe_PolyMAC_P0::dimensionner_blocs(), Coalescence_bulles_2groupes_PolyMAC_P0::dimensionner_blocs(), Flux_2groupes_PolyMAC_P0::dimensionner_blocs(), Rupture_bulles_1groupe_PolyMAC_P0::dimensionner_blocs(), Rupture_bulles_2groupes_PolyMAC_P0::dimensionner_blocs(), Variation_rho::dimensionner_blocs(), Source_Diffusion_supplementaire_echelle_temp_turb::dimensionner_blocs(), Source_Dissipation_energie_cin_turb::dimensionner_blocs(), Source_Production_echelle_temp_taux_diss_turb::dimensionner_blocs(), Source_Production_energie_cin_turb::dimensionner_blocs(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::dimensionner_blocs(), Source_Flux_interfacial_base::dimensionner_blocs(), Op_Conv_VDF_base::dimensionner_blocs_elem(), dimensionner_matrice(), Operateur_base::dimensionner_termes_croises(), Navier_Stokes_std_ALE::discretiser(), Convection_Diffusion_Phase_field::discretiser(), Aire_interfaciale::discretiser(), Energie_Multiphase::discretiser(), Energie_Multiphase_Enthalpie::discretiser(), Masse_Multiphase::discretiser(), Modele_turbulence_hyd_base::discretiser_visc_turb(), QDM_Multiphase::discretiser_vitesse(), Navier_Stokes_std_ALE::div_ale_derivative(), Convection_Diffusion_Temperature::ecrire_fichier_pena_th(), expression_residu(), Schema_Euler_Implicite::faire_un_pas_de_temps_eqn_base(), Schema_Implicite_Multi_TimeStep_base::faire_un_pas_de_temps_eqn_base(), Schema_Euler_Implicite::faire_un_pas_de_temps_pb_couple(), Implicite_ALE::first_special_treatment(), Convection_Diffusion_Fluide_Dilatable_base::fluide(), Convection_Diffusion_Temperature_base::fluide(), Masse_Multiphase::fluide(), Source_PDF_base::fonct_coeff(), Simpler_Base::get_and_set_parametre_equation(), Convection_Diffusion_Espece_Multi_base::get_champ(), Discretisation_base::get_name_of_type_for(), QDM_Multiphase::get_noms_champs_postraitables(), Champ_Inc_base::get_PDI_dname(), Convection_Diffusion_Espece_Multi_base::has_champ(), Source_PDF_EF::impr(), Op_Grad_VEF_P1B_Face::impr(), Op_EF_base::impr(), Op_VEF_Face::impr(), Source_base::impr(), Op_Div_EF::impr(), Op_Grad_EF::impr(), Op_Div_PolyMAC::impr(), Navier_Stokes_std::impr(), Op_Grad_VDF_Face::impr(), Op_Div_VEFP1B_Elem::impr(), Navier_Stokes_Fluide_Dilatable_Proto::impr_impl(), Loi_Paroi_Nu_Impose_VDF::imprimer_nusselt(), Loi_Paroi_Nu_Impose_VEF::imprimer_nusselt(), Paroi_scal_hyd_base_EF::imprimer_nusselt(), Paroi_scal_hyd_base_VDF::imprimer_nusselt(), Paroi_scal_hyd_base_VEF::imprimer_nusselt(), Echange_contact_PolyMAC_P0::init_op(), Echange_contact_PolyMAC_P0P1NC::init_op(), Paroi_frottante_simple::initialiser(), Echange_global_impose_turbulent::initialiser(), Champ_Front_Fonction::initialiser(), Transport_Marqueur_FT::initTimeStep(), SETS::iterer_eqn(), Simple::iterer_eqs(), Implicit_steady::iterer_NS(), SETS::iterer_NS(), Simpler::iterer_NS(), Solveur_U_P::iterer_NS(), QDM_Multiphase::lire_cond_init(), Transport_Interfaces_FT_Disc::lire_cond_init(), Modele_turbulence_hyd_base::lire_distance_paroi(), Terme_Puissance_Thermique::lire_donnees(), Transport_Marqueur_FT::lire_injection(), Convection_Diffusion_Temperature_FT_Disc::lire_motcle_non_standard(), Transport_Marqueur_FT::lire_motcle_non_standard(), Navier_Stokes_phase_field::lire_motcle_non_standard(), Transport_K_Eps::lire_motcle_non_standard(), Transport_K_Omega::lire_motcle_non_standard(), Transport_K_ou_Eps::lire_motcle_non_standard(), Transport_K_ou_Eps_Realisable::lire_motcle_non_standard(), Convection_Diffusion_Espece_Multi_QC::lire_motcle_non_standard(), Convection_Diffusion_Temperature::lire_motcle_non_standard(), Modele_turbulence_hyd_base::lire_motcle_non_standard(), Modele_turbulence_scal_base::lire_motcle_non_standard(), Transport_Marqueur_FT::lire_transformation(), Paroi_frottante_simple::me_calculer(), Frontiere_ouverte_vitesse_vortex::mettre_a_jour(), Convection_Diffusion_Concentration_FT_Disc::mettre_a_jour(), Convection_Diffusion_Concentration_Turbulent_FT_Disc::mettre_a_jour(), Echange_contact_rayo_semi_transp_VDF::mettre_a_jour(), Portance_interfaciale_PolyMAC_P0::mettre_a_jour(), Aire_interfaciale::mettre_a_jour(), QDM_Multiphase::mettre_a_jour(), Navier_Stokes_std_ALE::mettre_a_jour(), Energie_cinetique_turbulente::mettre_a_jour(), Echange_contact_Rayo_transp_VDF::mettre_a_jour(), Modele_turbulence_scal_LES_dyn_VDF::mettre_a_jour(), Navier_Stokes_Turbulent_QC::mettre_a_jour(), Modele_turbulence_scal_Prandtl::mettre_a_jour(), Modele_turbulence_scal_Schmidt::mettre_a_jour(), Echange_contact_Correlation_VDF::mettre_a_jour(), PlaqThVDF::mettre_a_jour(), Op_Dift_Multiphase_VDF_Elem::mettre_a_jour(), Echange_contact_Correlation_VEF::mettre_a_jour(), IJK_Thermals::milieu(), Navier_Stokes_FTD_IJK::milieu(), Equation_rayonnement_base::milieu(), Navier_Stokes_std::milieu(), Convection_Diffusion_Temperature_FT_Disc::milieu(), Transport_Interfaces_FT_Disc::milieu(), Op_EF_base::modifier_flux(), Op_VEF_Face::modifier_flux(), Transport_turbulent_aire_interfaciale::modifier_mu(), Op_Diff_Turbulent_PolyMAC_P0_Elem::modifier_mu(), Operateur_base::modifier_pour_Cl(), Assembleur_P_PolyMAC_P0P1NC::modifier_secmem_pour_incr_p(), Maillage_FT_Disc::nettoyer_phase(), Terme_Source_Constituant::ouvrir_fichier(), Source_PDF_base::ouvrir_fichier(), Operateur_base::ouvrir_fichier(), Source_base::ouvrir_fichier(), Operateur_base::ouvrir_fichier_partage(), Terme_Puissance_Thermique_Echange_Impose_Elem_base::pid_process(), Transport_Interfaces_FT_Disc::preparer_calcul(), Modele_turbulence_hyd_K_Eps::preparer_calcul(), Modele_turbulence_hyd_K_Eps_Bicephale::preparer_calcul(), Navier_Stokes_IBM::preparer_calcul(), Navier_Stokes_std::preparer_calcul(), Navier_Stokes_std::projeter(), Source_injection_masse_base::readOn(), Source_Production_echelle_temp_taux_diss_turb::readOn(), Source_Production_energie_cin_turb::readOn(), Transport_Marqueur_FT::readOn(), Transport_K_Eps::readOn(), Transport_K_KEps::readOn(), Transport_K_Omega::readOn(), Transport_K_ou_Eps::readOn(), Transport_K_ou_Eps_Realisable::readOn(), Transport_Fluctuation_Temperature::readOn(), Transport_Fluctuation_Temperature_W::readOn(), Transport_Fluctuation_Temperature_W_Bas_Re::readOn(), Transport_Flux_Chaleur_Turbulente::readOn(), Source_Scalaire_EF::readOn(), Domaine_Cl_dis_base::readOn(), List_Equations_Scalaires_Passifs_Especes::readOn(), Aire_interfaciale::readOn(), Energie_Multiphase::readOn(), Masse_Multiphase::readOn(), QDM_Multiphase::readOn(), DP_Impose_PolyMAC_Face::remplir_num_faces(), Perte_Charge_Singuliere_PolyMAC_Face::remplir_num_faces(), Perte_Charge_Singuliere_VDF_Face::remplir_num_faces(), DP_Impose_VEF_Face::remplir_num_faces(), Perte_Charge_Singuliere_VEF_Face::remplir_num_faces(), Perte_Charge_Reguliere_VDF_Face::remplir_num_faces(), Perte_Charge_Reguliere_VEF_P1NC::remplir_num_faces(), Domaine_Cl_EF::remplir_type_elem_Cl(), Navier_Stokes_std_ALE::renewing_jacobians(), Navier_Stokes_std_ALE::reprendre(), Navier_Stokes_Turbulent_ALE::reprendre(), Navier_Stokes_FT_Disc::reprendre(), reprendre(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::reprendre(), Convection_Diffusion_Chaleur_WC::reprendre(), Convection_Diffusion_Espece_Binaire_WC::reprendre(), Navier_Stokes_IBM_Turbulent::reprendre(), Navier_Stokes_std::reprendre(), Navier_Stokes_Turbulent::reprendre(), Source_PDF_EF::rotate_imposed_velocity(), Navier_Stokes_std_ALE::sauvegarder(), Champ_Inc_base::sauvegarder(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::sauvegarder(), Modele_turbulence_hyd_null::sauvegarder(), Convection_Diffusion_Fluide_Dilatable_Proto::Sauvegarder_WC(), Implicite_ALE::second_special_treatment(), Operateur_base::set_fichier(), Source_base::set_fichier(), Conduction::solide(), Terme_Source_Canal_perio::source(), Transport_Interfaces_FT_Disc::test_suppression_interfaces_sous_domaine(), Transport_Marqueur_FT::transformer_particules(), Modele_Fonc_Bas_Reynolds_Base::typer_lire_Modele_Fonc_Bas_Reynolds(), Modele_Fonc_Realisable_base::typer_lire_Modele_Fonc_Realisable(), Turbulence_paroi_scal_base::typer_lire_turbulence_paroi_scal(), Domaine_ALE::update_ALE_projection(), DP_Impose::update_dp_regul(), Perte_Charge_Singuliere::update_K(), Navier_Stokes_std_ALE::update_pressure_matrix(), Energie_Multiphase::verifie_ch_init_nb_comp_cl(), Transport_K_Eps_non_std::vitesse_pour_transport(), Transport_K_Eps_Realisable::vitesse_pour_transport(), Transport_K_ou_Eps_non_std::vitesse_pour_transport(), Convection_Diffusion_std::vitesse_pour_transport(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::vitesse_pour_transport(), Convection_Diffusion_Espece_Binaire_base::vitesse_pour_transport(), Convection_Diffusion_Chaleur_QC::vitesse_pour_transport(), Convection_Diffusion_Espece_Multi_WC::vitesse_pour_transport(), Terme_Source_Canal_perio::write_flow_rate(), and VDF_discretisation::y_plus().
probleme() [2/2]
const Probleme_base & Equation_base::probleme () const
Renvoie le probleme associe a l'equation.
(version const)
Returns
(Probleme_base&) le probleme associe a l'equation
References mon_probleme, and TRUST_Ref< _CLASSE_ >::valeur().
schema_temps() [1/2]
Schema_Temps_base & Equation_base::schema_temps ()
Renvoie le schema en temps associe a l'equation.
Returns
(Schema_Temps_base&) le schema en temps associe a l'equation
Exceptions
pas de schema en temps associe a l'equation
References Process::exit(), le_schema_en_temps, TRUST_Ref< _CLASSE_ >::non_nul(), Objet_U::que_suis_je(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Operateur::ajouter(), Perte_Charge_PolyMAC::ajouter(), Perte_Charge_VEF::ajouter(), Perte_Charge_PolyMAC::ajouter_blocs(), Op_Evanescence_Homogene_Elem_base::ajouter_blocs(), Source_Flux_interfacial_base::ajouter_blocs(), Source_Travail_pression_Elem_base::ajouter_blocs(), Perte_Charge_VDF_base::ajouter_blocs(), Op_Diff_PolyMAC_P0P1NC_Elem::ajouter_blocs_ext(), Op_Diff_PolyMAC_P0P1NC_Face::ajouter_blocs_ext(), assembler_avec_inertie(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_avec_inertie_impl(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_blocs(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_blocs_avec_inertie(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::assembler_blocs_avec_inertie(), Convection_Diffusion_Espece_Binaire_base::assembler_blocs_avec_inertie(), Convection_Diffusion_Espece_Multi_QC::assembler_blocs_avec_inertie(), Convection_Diffusion_Espece_Multi_WC::assembler_blocs_avec_inertie(), assembler_blocs_avec_inertie(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_impl(), Source_Con_Phase_field::assembler_matrice_point_fixe(), Transport_2eq_base::associer(), Transport_Fluctuation_Temperature::associer_modele_turbulence(), Transport_Flux_Chaleur_Turbulente::associer_modele_turbulence(), Transport_Fluctuation_Temperature_W::associer_modele_turbulence(), Transport_Fluctuation_Temperature_W_Bas_Re::associer_modele_turbulence(), Champ_P1NC::calcul_h_conv(), Modele_turbulence_scal_LES_dyn_VDF::calcul_voisins(), Flux_radiatif_VDF::calculer_flux_radiatif(), Flux_radiatif_VEF::calculer_flux_radiatif(), Convection_Diffusion_Temperature_FT_Disc::calculer_grad_t(), Op_Diff_VEFP1NCP1B_Face::calculer_gradient_som(), ParoiVDF_TBLE_LRM::calculer_hyd(), ParoiVDF_TBLE::calculer_hyd(), ParoiVEF_TBLE::calculer_hyd(), ParoiVDF_TBLE::calculer_hyd_BiK(), ParoiVDF_TBLE_LRM::calculer_hyd_BiK(), ParoiVEF_TBLE::calculer_hyd_BiK(), Navier_Stokes_phase_field::calculer_mu(), Navier_Stokes_phase_field::calculer_pas_de_temps(), Navier_Stokes_phase_field::calculer_rho(), Paroi_ODVM_scal_VDF::calculer_scal(), Paroi_TBLE_scal_VDF::calculer_scal(), ParoiVEF_TBLE_scal::calculer_scal(), Echange_contact_Correlation_VDF::calculer_Tfluide(), Echange_contact_Correlation_VEF::calculer_Tfluide(), Op_Conv_EF::coefficient_btd(), completer(), Echange_contact_VDF_FT_Disc::completer(), Echange_contact_VDF_FT_Disc_solid::completer(), Masse_PolyMAC_base::completer(), Echange_contact_Correlation_VDF::completer(), Echange_contact_VDF::completer(), Echange_contact_Correlation_VEF::completer(), Convection_Diffusion_Temperature_FT_Disc::compute_divergence_free_velocity_extension(), Navier_Stokes_FT_Disc::compute_eulerian_field_contact_forces(), Triple_Line_Model_FT_Disc::compute_TCL_fluxes_in_all_boundary_cells(), Op_Dift_VDF_Face_Axi_base::contribue_au_second_membre(), Perte_Charge_PolyMAC::contribuer_a_avec(), Perte_Charge_VEF::contribuer_a_avec(), Op_Diff_DG_Elem::contribuer_au_second_membre(), Transport_K_Eps_base::controler_K_Eps(), Transport_K_Omega_base::controler_K_Omega(), Transport_K_ou_Eps_base::controler_variable(), Convection_Diffusion_Temperature_FT_Disc::correct_mpoint(), Navier_Stokes_std::corriger_derivee_impl(), Transport_Marqueur_FT::creer_champ(), Navier_Stokes_std::creer_champ(), QDM_Multiphase::creer_champ(), Transport_Interfaces_FT_Disc::deplacer_maillage_ft_v_fluide(), derivee_en_temps_inco(), Convection_Diffusion_Temperature_FT_Disc::derivee_en_temps_inco(), Navier_Stokes_phase_field::derivee_en_temps_inco(), Navier_Stokes_std::derivee_en_temps_inco(), Navier_Stokes_FT_Disc::derivee_en_temps_inco(), Convection_Diffusion_Fluide_Dilatable_Proto::derivee_en_temps_inco_sans_solveur_masse_impl(), discretiser(), Navier_Stokes_std_ALE::discretiser(), Echelle_temporelle_turbulente::discretiser(), Energie_cinetique_turbulente::discretiser(), Energie_cinetique_turbulente_WIT::discretiser(), Taux_dissipation_turbulent::discretiser(), Convection_Diffusion_Temperature_FT_Disc::discretiser(), Navier_Stokes_FT_Disc::discretiser(), Transport_Interfaces_FT_Disc::discretiser(), Transport_Marqueur_FT::discretiser(), Convection_Diffusion_Phase_field::discretiser(), Equation_rayonnement_base::discretiser(), Transport_K_Eps_base::discretiser(), Transport_K_Omega_base::discretiser(), Transport_K_ou_Eps_base::discretiser(), Transport_Fluctuation_Temperature::discretiser(), Transport_Fluctuation_Temperature_W::discretiser(), Transport_Flux_Chaleur_Turbulente::discretiser(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::discretiser(), Convection_Diffusion_Espece_Fluide_Dilatable_base::discretiser(), Navier_Stokes_Fluide_Dilatable_base::discretiser(), Convection_Diffusion_Concentration::discretiser(), Convection_Diffusion_Temperature::discretiser(), Navier_Stokes_std::discretiser(), Aire_interfaciale::discretiser(), Energie_Multiphase::discretiser(), Energie_Multiphase_Enthalpie::discretiser(), Masse_Multiphase::discretiser(), Navier_Stokes_Turbulent_QC::discretiser(), Conduction::discretiser(), Navier_Stokes_std::discretiser_grad_p(), Navier_Stokes_std::discretiser_vitesse(), QDM_Multiphase::discretiser_vitesse(), Convection_Diffusion_Temperature::ecrire_fichier_pena_th(), expression_residu(), Transport_Marqueur_FT::get_champ(), Navier_Stokes_Aposteriori::get_champ(), Transport_K_ou_Eps_base::get_champ(), Paroi_hyd_base_EF::get_champ(), get_champ(), Convection_Diffusion_Temperature::get_champ(), Convection_Diffusion_Temperature_base::get_champ(), Navier_Stokes_std::get_champ(), Turbulence_paroi_base::get_champ(), Conduction::get_champ(), Transport_Interfaces_FT_Disc::impr(), Navier_Stokes_std::impr(), Transport_Interfaces_FT_Disc::impr_effort_fluide_interface(), imprime_residu(), init_champ_conserve(), Energie_Multiphase::init_champ_convecte(), Paroi_ODVM_scal_VDF::init_lois_paroi(), ParoiVEF_TBLE_scal::init_lois_paroi(), Echange_contact_PolyMAC::initialiser(), Echange_contact_VDF::initialiser(), Boundary_field_keps_from_ud::initialiser(), initTimeStep(), Equation_rayonnement_base::initTimeStep(), Navier_Stokes_Fluide_Dilatable_base::initTimeStep(), QDM_Multiphase::initTimeStep(), Schema_Temps_base::iterateTimeStep(), Schema_Phase_field::iterateTimeStep(), Multi_Sch_ThHyd::iterateTimeStep(), Sch_CN_iteratif::iterateTimeStepOnEquation(), Simple::iterer_eqn(), Simple::iterer_eqs(), SETS::iterer_NS(), Echange_contact_Correlation_VDF::limpr(), Echange_contact_Correlation_VEF::limpr(), Terme_Source_Acceleration::lire_data(), mettre_a_jour(), Transport_Interfaces_FT_Disc::mettre_a_jour(), Champ_front_synt::mettre_a_jour(), Navier_Stokes_std_ALE::mettre_a_jour(), Energie_cinetique_turbulente::mettre_a_jour(), Modele_turbulence_scal_Fluctuation_Temperature::mettre_a_jour(), Modele_turbulence_hyd_K_Eps::mettre_a_jour(), Modele_turbulence_hyd_K_Eps_2_Couches::mettre_a_jour(), Modele_turbulence_hyd_K_Eps_Bas_Reynolds::mettre_a_jour(), Modele_turbulence_hyd_K_Eps_Bicephale::mettre_a_jour(), Modele_turbulence_hyd_K_Eps_Realisable::mettre_a_jour(), Modele_turbulence_hyd_K_Eps_Realisable_Bicephale::mettre_a_jour(), Modele_turbulence_hyd_K_Omega::mettre_a_jour(), Echange_contact_Correlation_VDF::mettre_a_jour(), Echange_contact_Correlation_VEF::mettre_a_jour(), Convection_Diffusion_Temperature::mise_en_place_domaine_fantome(), Champ_P1NC::norme_L2_H1(), Convection_Diffusion_Temperature::penalisation_L2(), preparer_calcul(), Navier_Stokes_FT_Disc::preparer_calcul(), Transport_Interfaces_FT_Disc::preparer_calcul(), Convection_Diffusion_Phase_field::preparer_calcul(), Navier_Stokes_phase_field::preparer_calcul(), Modele_turbulence_scal_Fluctuation_Temperature::preparer_calcul(), Navier_Stokes_IBM::preparer_calcul(), Convection_Diffusion_Concentration::preparer_calcul(), Navier_Stokes_std::preparer_calcul(), QDM_Multiphase::preparer_calcul(), Transport_Marqueur_FT::readOn(), List_Equations_Scalaires_Passifs_Especes::readOn(), Op_Conv_DI_L2_VEF_Face::reconst_DI_L2_2d(), Op_Conv_DI_L2_VEF_Face::reconst_DI_L2_3d(), Transport_Interfaces_FT_Disc::remailler_interface(), Navier_Stokes_std_ALE::reprendre(), Navier_Stokes_Turbulent_ALE::reprendre(), Navier_Stokes_FT_Disc::reprendre(), Transport_Interfaces_FT_Disc::reprendre(), reprendre(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::reprendre(), Convection_Diffusion_Chaleur_WC::reprendre(), Convection_Diffusion_Espece_Binaire_WC::reprendre(), Navier_Stokes_IBM_Turbulent::reprendre(), Navier_Stokes_std::reprendre(), Navier_Stokes_Turbulent::reprendre(), Collision_Model_FT_base::research_collision_pairs_Verlet(), Modele_turbulence_hyd_null::sauvegarder(), EOS_Tools_VDF::secmembre_divU_Z(), EOS_Tools_VEF::secmembre_divU_Z(), Navier_Stokes_std_sensibility::set_param(), Equation_rayonnement_base::solve(), Terme_Source_Canal_perio::source(), Transport_Interfaces_FT_Disc::update_critere_statio(), updateGivenFields(), and Terme_Source_Canal_perio::write_flow_rate().
schema_temps() [2/2]
const Schema_Temps_base & Equation_base::schema_temps () const
Renvoie le schema en temps associe a l'equation.
Returns
(Schema_Temps_base&) le schema en temps associe a l'equation
Exceptions
pas de schema en temps associe a l'equation
References Process::exit(), le_schema_en_temps, TRUST_Ref< _CLASSE_ >::non_nul(), Objet_U::que_suis_je(), and TRUST_Ref< _CLASSE_ >::valeur().
associer_sch_tps_base()
void Equation_base::associer_sch_tps_base (const Schema_Temps_base & un_schema_en_temps) virtual
S'associe au schema_en_temps.
Parameters
(Schema_Temps_base& un_schema_en_temps) le schema en temps a associer a l'equation
References le_schema_en_temps.
Referenced by Probleme_FT_Disc_gen::add_FT_equation(), Transport_2eq_base::associer(), Transport_Fluctuation_Temperature::associer_modele_turbulence(), Transport_Flux_Chaleur_Turbulente::associer_modele_turbulence(), Transport_Fluctuation_Temperature_W::associer_modele_turbulence(), Transport_Fluctuation_Temperature_W_Bas_Re::associer_modele_turbulence(), Probleme_base::associer_sch_tps_base(), Modele_rayo_semi_transp::discretiser(), Probleme_base::read_optional_equations(), and List_Equations_Scalaires_Passifs_Especes::readOn().
associer_domaine_dis()
void Equation_base::associer_domaine_dis (const Domaine_dis_base & z) virtual
Associe le domaine discretisee a l'equation.
Parameters
(Domaine_dis_base& z) le domaine discretisee a associee
References le_dom_dis.
Referenced by Transport_2eq_base::associer(), Transport_Fluctuation_Temperature::associer_modele_turbulence(), Transport_Flux_Chaleur_Turbulente::associer_modele_turbulence(), Transport_Fluctuation_Temperature_W::associer_modele_turbulence(), Transport_Fluctuation_Temperature_W_Bas_Re::associer_modele_turbulence(), Modele_rayo_semi_transp::discretiser(), Probleme_base::discretiser_equations(), Probleme_base::read_optional_equations(), and List_Equations_Scalaires_Passifs_Especes::readOn().
discretisation()
const Discretisation_base & Equation_base::discretisation () const
Renvoie la discretisation associee a l'equation.
Returns
(Discretisation_base&) a discretisation associee a l'equation
Exceptions
pas de probleme associe
References Process::exit(), mon_probleme, TRUST_Ref< _CLASSE_ >::non_nul(), and Objet_U::que_suis_je().
Referenced by Source_Fluide_Dilatable_VEF_Proto::ajouter_impl(), Convection_Diffusion_Temperature::assembler(), assembler_blocs(), Convection_Diffusion_Temperature::assembler_blocs(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::assembler_blocs_avec_inertie(), Convection_Diffusion_Espece_Binaire_base::assembler_blocs_avec_inertie(), Convection_Diffusion_Espece_Multi_QC::assembler_blocs_avec_inertie(), Convection_Diffusion_Espece_Multi_WC::assembler_blocs_avec_inertie(), assembler_blocs_avec_inertie(), Puissance_Thermique_EF::associer_pb(), Puissance_Thermique_QC_EF::associer_pb(), Terme_Source_Constituant_PolyMAC_Elem::associer_pb(), Terme_Source_Constituant_VDF_Elem::associer_pb(), Terme_Source_Constituant_VEF_Face::associer_pb(), Convection_Diffusion_Fluide_Dilatable_Proto::calculer_div_rho_u_impl(), Champ_base::calculer_valeurs_som_post(), Navier_Stokes_QC::completer(), Navier_Stokes_WC::completer(), Paroi_Knudsen_non_negligeable::completer(), Navier_Stokes_std::completer(), Masse_Multiphase::completer(), Navier_Stokes_Turbulent_QC::completer(), Fluide_Dilatable_base::completer(), Fluide_Weakly_Compressible::completer(), Fluide_Dilatable_base::completer_edo(), Convection_Diffusion_Temperature_FT_Disc::compute_divergence_free_velocity_extension(), Transport_K_Eps_ALE::corriger_derivee_impl_ALE(), Op_Conv_VDF_base::creer_champ(), Navier_Stokes_phase_field::creer_champ(), creer_champ(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::creer_champ(), Convection_Diffusion_Temperature::creer_champ(), Convection_Diffusion_Temperature_base::creer_champ(), Navier_Stokes_std::creer_champ(), QDM_Multiphase::creer_champ(), Conduction::creer_champ(), Fluide_base::creer_e_int(), dimensionner_matrice(), discretiser(), Navier_Stokes_std_ALE::discretiser(), Echelle_temporelle_turbulente::discretiser(), Energie_cinetique_turbulente::discretiser(), Energie_cinetique_turbulente_WIT::discretiser(), Taux_dissipation_turbulent::discretiser(), Convection_Diffusion_Temperature_FT_Disc::discretiser(), Navier_Stokes_FT_Disc::discretiser(), Transport_Interfaces_FT_Disc::discretiser(), Convection_Diffusion_Phase_field::discretiser(), Navier_Stokes_Aposteriori::discretiser(), Transport_K_Eps_base::discretiser(), Transport_K_Omega_base::discretiser(), Transport_K_ou_Eps_base::discretiser(), Transport_Fluctuation_Temperature::discretiser(), Transport_Fluctuation_Temperature_W::discretiser(), Transport_Flux_Chaleur_Turbulente::discretiser(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::discretiser(), Convection_Diffusion_Espece_Fluide_Dilatable_base::discretiser(), Navier_Stokes_Fluide_Dilatable_base::discretiser(), Convection_Diffusion_Concentration::discretiser(), Convection_Diffusion_Temperature::discretiser(), Navier_Stokes_std::discretiser(), Aire_interfaciale::discretiser(), Energie_Multiphase::discretiser(), Energie_Multiphase_Enthalpie::discretiser(), Masse_Multiphase::discretiser(), Navier_Stokes_Turbulent_QC::discretiser(), Conduction::discretiser(), Modele_rayo_semi_transp::discretiser(), Convection_Diffusion_Temperature_FT_Disc::discretiser_assembleur_pression(), Navier_Stokes_std::discretiser_assembleur_pression(), Navier_Stokes_FT_Disc::discretiser_assembleur_pression(), Navier_Stokes_std::discretiser_grad_p(), Reaction::discretiser_omega(), Navier_Stokes_std::discretiser_vitesse(), QDM_Multiphase::discretiser_vitesse(), Discretisation_base::get_name_of_type_for(), init_champ_conserve(), Energie_Multiphase::init_champ_convecte(), Terme_Source_Qdm_Face_PolyMAC_P0P1NC::initialiser(), Terme_Puissance_Thermique_Echange_Impose_Elem_base::initialiser(), Terme_Source_Qdm_VDF_Face::initialiser(), Terme_Puissance_Thermique_Echange_Impose_VEF_Face::initialiser(), Piso::iterer_NS(), Solveur_U_P::iterer_NS(), Terme_Source_Acceleration::lire_data(), Terme_Puissance_Thermique::lire_donnees(), Convection_Diffusion_Turbulent::lire_modele(), Navier_Stokes_Turbulent_ALE::lire_motcle_non_standard(), Navier_Stokes_phase_field::lire_motcle_non_standard(), Convection_Diffusion_Chaleur_QC::lire_motcle_non_standard(), Convection_Diffusion_Chaleur_WC::lire_motcle_non_standard(), Navier_Stokes_std::lire_motcle_non_standard(), Conduction::lire_motcle_non_standard(), Navier_Stokes_Fluide_Dilatable_base::lire_motcle_non_standard(), Convection_Diffusion_Turbulent::lire_op_diff_turbulent(), Navier_Stokes_Turbulent_ALE::lire_op_diff_turbulent(), Transport_2eq_base::lire_op_diff_turbulent(), Navier_Stokes_IBM_Turbulent::lire_op_diff_turbulent(), Navier_Stokes_Turbulent::lire_op_diff_turbulent(), QDM_Multiphase::mettre_a_jour(), Energie_cinetique_turbulente::mettre_a_jour(), Navier_Stokes_FT_Disc::preparer_calcul(), Source_injection_masse_base::readOn(), Navier_Stokes_phase_field::readOn(), Source_Scalaire_EF::readOn(), Aire_interfaciale::readOn(), Modele_turbulence_hyd_null::readOn(), Navier_Stokes_std_ALE::renewing_jacobians(), set_diffusion_multi_scalaire(), Op_Diff_Fluctu_Temp::typer(), Op_Diff_Flux_Chaleur_Turb::typer(), Operateur_Conv::typer(), Operateur_Diff::typer(), Operateur_Div::typer(), Operateur_Grad::typer(), Operateur_Evanescence::typer(), Source::typer(), Modele_Fonc_Bas_Reynolds_Base::typer_lire_Modele_Fonc_Bas_Reynolds(), Modele_Fonc_Bas_Reynolds_Thermique_Base::typer_lire_Modele_Fonc_Bas_Reynolds_Thermique(), Modele_Fonc_Realisable_base::typer_lire_Modele_Fonc_Realisable(), Turbulence_paroi_base::typer_lire_turbulence_paroi(), Turbulence_paroi_scal_base::typer_lire_turbulence_paroi_scal(), verif_Cl(), and Modele_turbulence_hyd_LES_base::verifie_loi_paroi_diphasique().
domaine_Cl_dis() [1/2]
Domaine_Cl_dis_base & Equation_base::domaine_Cl_dis () inline virtual
Renvoie le domaine des conditions aux limite discretisee associee a l'equation.
Returns
(Domaine_Cl_dis_base&) Domaine de condition aux limites discretisee
References le_dom_Cl_dis, Objet_U_ptr::non_nul(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by Source_Reaction_Particules_VDF::ajouter(), Source_Reaction_Particules_VEF::ajouter(), Terme_Boussinesq_VDF_Face::ajouter_blocs(), Op_Diff_PolyMAC_P0_Elem::ajouter_blocs(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_avec_inertie_impl(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_blocs_avec_inertie(), Champ_front_contact_VEF::associer_front_vf_et_ch_front_autre_pb(), Perte_Charge_PolyMAC_Face::associer_pb(), Perte_Charge_VDF_Face::associer_pb(), Perte_Charge_VEF_Face::associer_pb(), Terme_Source_Qdm_lambdaup_VEF_Face::associer_pb(), Maillage_FT_Disc::calcul_courbure_sommets(), Implicit_steady::calcul_mat_masse_diviser_par_dt_vef(), Traitement_particulier_NS_canal::calcul_reynolds_tau(), Champ_P1NC::calcul_y_plus_diphasique(), Champ_Face_VDF::calcul_y_plus_diphasique(), Terme_Source_Constituant_Vortex_VEF_Face::calculer(), Maillage_FT_Disc::calculer_costheta_minmax(), Convection_Diffusion_Fluide_Dilatable_Proto::calculer_div_rho_u_impl(), Modele_rayo_semi_transp::calculer_flux_radiatif(), Flux_radiatif_VDF::calculer_flux_radiatif(), Flux_radiatif_VEF::calculer_flux_radiatif(), Navier_Stokes_FT_Disc::calculer_gradient_indicatrice(), Paroi_std_hyd_VDF_diphasique::calculer_hyd(), Paroi_std_hyd_VEF_diphasique::calculer_hyd(), Operateur_base::calculer_pour_post(), Paroi_ODVM_scal_VDF::calculer_scal(), Paroi_TBLE_scal_VDF::calculer_scal(), Champ_base::calculer_valeurs_som_compo_post(), Champ_base::calculer_valeurs_som_post(), Modele_turbulence_hyd_K_Eps::calculer_viscosite_turbulente(), Modele_turbulence_hyd_K_Eps_Bas_Reynolds::calculer_viscosite_turbulente(), Modele_turbulence_hyd_K_Eps_Bicephale::calculer_viscosite_turbulente(), Domaine_ALE::calculer_vitesse(), Triple_Line_Model_FT_Disc::completer(), Pb_Couple_Rayonnement::completer(), Operateur_base::completer(), Source_base::completer(), Convection_diffusion_turbulence_multiphase::completer(), Diffusion_croisee_echelle_temp_taux_diss_turb_PolyMAC_P0::completer(), Source_Diffusion_supplementaire_echelle_temp_turb::completer(), Transport_K_Omega::completer(), Op_Diff_PolyMAC_P0_base::completer(), Convection_Diffusion_Espece_Multi_QC::completer(), Convection_Diffusion_Chaleur_WC::completer(), Navier_Stokes_std::completer(), Terme_Source_Canal_perio::completer(), Masse_Multiphase::completer(), Champ_Generique_Gradient::completer(), Fluide_Dilatable_base::completer(), Fluide_Weakly_Compressible::completer(), Fluide_Dilatable_base::completer_edo(), Terme_Source_Canal_perio::compute_heat_flux(), Paroi_scal_hyd_base_EF::compute_nusselt(), Paroi_scal_hyd_base_VDF::compute_nusselt(), Paroi_scal_hyd_base_VEF::compute_nusselt(), Triple_Line_Model_FT_Disc::compute_TCL_fluxes_in_all_boundary_cells(), Navier_Stokes_FT_Disc::correct_at_exit_bad_gradient(), Convection_Diffusion_Temperature::creer_champ(), Convection_Diffusion_Temperature_base::creer_champ(), Navier_Stokes_std::creer_champ(), Conduction::creer_champ(), Convection_Diffusion_Fluide_Dilatable_Proto::derivee_en_temps_inco_sans_solveur_masse_impl(), Champ_front_calc::domaine_Cl_dis(), Champ_Inc_base::domaine_Cl_dis(), Champ_front_contact_VEF::domaine_Cl_dis(), Eq_rayo_semi_transp_VDF::evaluer_cl_rayonnement(), Eq_rayo_semi_transp_VEF::evaluer_cl_rayonnement(), Schema_Euler_explicite_ALE::faire_un_pas_de_temps_eqn_base(), RK3_MassRedistrib::faire_un_pas_de_temps_eqn_base(), Schema_Euler_explicite_Phase_field::faire_un_pas_de_temps_eqn_base(), Leap_frog::faire_un_pas_de_temps_eqn_base(), Pred_Cor::faire_un_pas_de_temps_eqn_base(), Schema_Euler_explicite::faire_un_pas_de_temps_eqn_base(), Schema_Euler_Implicite::faire_un_pas_de_temps_eqn_base(), Schema_Explicite_Multi_TimeStep_base::faire_un_pas_de_temps_eqn_base(), Schema_Implicite_Multi_TimeStep_base::faire_un_pas_de_temps_eqn_base(), RRK2::faire_un_pas_de_temps_eqn_base(), RK3_FT::faire_un_pas_de_temps_pb_couple(), Schema_Euler_Implicite::faire_un_pas_de_temps_pb_couple(), Schema_Implicite_Multi_TimeStep_base::faire_un_pas_de_temps_pb_couple(), Champ_P1NC_implementation::filtrer_L2(), Champ_P1NC_implementation::filtrer_resu(), Modele_rayo_semi_transp::flux_radiatif(), Paroi_hyd_base_EF::get_champ(), Turbulence_paroi_base::get_champ(), Champ_Generique_Extraction::get_champ(), Champ_Generique_Tparoi_VEF::get_champ(), Convection_Diffusion_Temperature_FT_Disc::get_flux_and_Twall(), Convection_Diffusion_Temperature_FT_Disc::get_flux_to_face(), Op_EF_base::impr(), Op_VEF_Face::impr(), Loi_Paroi_Nu_Impose_VDF::imprimer_nusselt(), Loi_Paroi_Nu_Impose_VEF::imprimer_nusselt(), Paroi_scal_hyd_base_EF::imprimer_nusselt(), Paroi_scal_hyd_base_VDF::imprimer_nusselt(), Paroi_scal_hyd_base_VEF::imprimer_nusselt(), Paroi_ODVM_scal_VDF::init_lois_paroi(), Couplage_Parietal_PolyMAC_helper::init_op_ext(), Op_Diff_PolyMAC_P0P1NC_Elem::init_op_ext(), Domaine_ALE::initialiser(), Terme_Puissance_Thermique::initialiser_champ_puissance(), Pb_Couple_rayo_semi_transp::initialize(), initTimeStep(), Probleme_base_interface_proto::initTimeStep_impl(), RK3_FT::iterateTimeStep(), Schema_Phase_field::iterateTimeStep(), Pb_Dilatable_base::iterateTimeStep(), Multi_Sch_ThHyd::iterateTimeStep(), Probleme_base_interface_proto::iterateTimeStep_impl(), Sch_CN_iteratif::iterateTimeStepOnEquation(), Sch_CN_EX_iteratif::iterateTimeStepOnNS(), Sch_CN_EX_iteratif::iterateTimeStepOnOther(), Simple::iterer_eqs(), SETS::iterer_NS(), Schema_Implicite_Multi_TimeStep_base::Iterer_Pb(), Schema_Euler_Implicite::Iterer_Pb(), Domaine_ALE::laplacien(), Convection_Diffusion_Turbulent::lire_modele(), Navier_Stokes_Turbulent_ALE::lire_motcle_non_standard(), Navier_Stokes_Fluide_Dilatable_base::lire_motcle_non_standard(), Convection_Diffusion_Concentration_FT_Disc::marquer_faces_sous_domaine(), Convection_Diffusion_Concentration_Turbulent_FT_Disc::marquer_faces_sous_domaine(), mettre_a_jour(), Convection_Diffusion_Concentration_FT_Disc::mettre_a_jour(), Convection_Diffusion_Concentration_Turbulent_FT_Disc::mettre_a_jour(), Domaine_ALE::mettre_a_jour(), Modele_turbulence_scal_Fluctuation_Temperature::mettre_a_jour(), Modele_turbulence_hyd_K_Eps::mettre_a_jour(), Modele_turbulence_hyd_K_Eps_2_Couches::mettre_a_jour(), Modele_turbulence_hyd_K_Eps_Bas_Reynolds::mettre_a_jour(), Modele_turbulence_hyd_K_Eps_Bicephale::mettre_a_jour(), Modele_turbulence_hyd_K_Eps_Realisable::mettre_a_jour(), Modele_turbulence_hyd_K_Eps_Realisable_Bicephale::mettre_a_jour(), Modele_turbulence_hyd_K_Omega::mettre_a_jour(), Eq_rayo_semi_transp_VDF::modifier_matrice(), Eq_rayo_semi_transp_VEF::modifier_matrice(), Op_VEF_Face::modifier_matrice_pour_periodique_apres_contribuer(), Op_Diff_K_Eps_VDF_base::modifier_pour_Cl(), Op_Diff_K_Omega_VDF_base::modifier_pour_Cl(), Convection_Diffusion_Concentration_FT_Disc::multiplier_valeurs_faces(), Convection_Diffusion_Concentration_Turbulent_FT_Disc::multiplier_valeurs_faces(), Maillage_FT_Disc::nettoyer_noeuds_virtuels_et_frontieres(), Probleme_base::newCompute(), preparer_calcul(), Modele_rayo_semi_transp::preparer_calcul(), Convection_Diffusion_Espece_Fluide_Dilatable_base::preparer_calcul(), Op_Evanescence_Homogene_VDF_Face::preparer_calcul(), Modele_turbulence_hyd_null::readOn(), Modele_turbulence_scal_null::readOn(), Cond_Lim_rayo_semi_transp::recherche_emissivite_et_A(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::remplir_cl_modifiee(), Probleme_base_interface_proto::solveTimeStep_impl(), Schema_Euler_Implicite::test_stationnaire(), Schema_Implicite_Multi_TimeStep_base::test_stationnaire(), Modele_Fonc_Bas_Reynolds_Base::typer_lire_Modele_Fonc_Bas_Reynolds(), Modele_Fonc_Bas_Reynolds_Thermique_Base::typer_lire_Modele_Fonc_Bas_Reynolds_Thermique(), Modele_Fonc_Realisable_base::typer_lire_Modele_Fonc_Realisable(), Turbulence_paroi_base::typer_lire_turbulence_paroi(), Turbulence_paroi_scal_base::typer_lire_turbulence_paroi_scal(), updateGivenFields(), Champ_P1NC::verifie_valeurs_cl(), Champ_Q1NC::verifie_valeurs_cl(), Pb_Hydraulique_Turbulent_ALE::verifier(), Pb_Phase_field::verifier(), Pb_Thermohydraulique_sensibility::verifier(), Pb_Thermohydraulique_IBM::verifier(), Pb_Thermohydraulique_IBM_Turbulent::verifier(), Pb_Hydraulique_Concentration::verifier(), Pb_Thermohydraulique::verifier(), Pb_Thermohydraulique_Concentration::verifier(), Pb_Multiphase::verifier(), Pb_Multiphase_Enthalpie::verifier(), Pb_Hydraulique_Concentration_Turbulent::verifier(), Pb_Hydraulique_Melange_Binaire_Turbulent_QC::verifier(), Pb_Hydraulique_Turbulent::verifier(), Pb_Thermohydraulique_Concentration_Turbulent::verifier(), Pb_Thermohydraulique_Turbulent::verifier(), Pb_Thermohydraulique_Turbulent_QC::verifier(), and Pb_Dilatable_Proto::verifier_impl().
domaine_Cl_dis() [2/2]
const Domaine_Cl_dis_base & Equation_base::domaine_Cl_dis () const inline virtual
Renvoie le domaine des conditions aux limite discretisee associee a l'equation.
(version const)
Returns
(Domaine_Cl_dis_base&) Domaine de condition aux limites discretisee
References le_dom_Cl_dis, Objet_U_ptr::non_nul(), and TRUST_Deriv< _CLASSE_ >::valeur().
domaine_dis() [1/2]
Domaine_dis_base & Equation_base::domaine_dis ()
Renvoie le domaine discretisee associee a l'equation.
Returns
(Domaine_dis_base&) le domaine discretisee asscoiee a l'equation
Exceptions
l'objet domaine discretisee (Domaine_dis) est invalide, probleme associe non discretise.
References Process::exit(), le_dom_dis, TRUST_Ref< _CLASSE_ >::non_nul(), Objet_U::que_suis_je(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Navier_Stokes_phase_field::_aff_donnee_P0(), Navier_Stokes_phase_field::_aff_donnee_P1(), Navier_Stokes_phase_field::_aff_donnee_P1Bulle(), Source_Reaction_Particules_VDF::ajouter(), Source_Reaction_Particules_VEF::ajouter(), Source_rayo_semi_transp_VDF_P0_VDF::ajouter(), Source_rayo_semi_transp_VEF_P1NC::ajouter(), Terme_Source_Constituant_Vortex_VEF_Face::ajouter_terme_div_u(), Eq_rayo_semi_transp_VDF::assembler_matrice(), Eq_rayo_semi_transp_VEF::assembler_matrice(), Simpler_Base::assembler_matrice_pression_implicite(), Transport_2eq_base::associer(), Maillage_FT_Disc::associer_equation_transport(), Transport_Fluctuation_Temperature::associer_modele_turbulence(), Transport_Flux_Chaleur_Turbulente::associer_modele_turbulence(), Transport_Fluctuation_Temperature_W::associer_modele_turbulence(), Transport_Fluctuation_Temperature_W_Bas_Re::associer_modele_turbulence(), Puissance_Thermique_EF::associer_pb(), Puissance_Thermique_QC_EF::associer_pb(), Perte_Charge_PolyMAC_Face::associer_pb(), Terme_Source_Constituant_PolyMAC_Elem::associer_pb(), Perte_Charge_VDF_Face::associer_pb(), Terme_Source_Constituant_VDF_Elem::associer_pb(), Perte_Charge_VEF_Face::associer_pb(), Terme_Source_Constituant_VEF_Face::associer_pb(), Terme_Source_Qdm_lambdaup_VEF_Face::associer_pb(), Transport_Interfaces_FT_Disc::calcul_effort_fluide_interface(), Convection_Diffusion_Temperature::calcul_indic_pena_global(), Transport_Interfaces_FT_Disc::calcul_indicatrice_faces(), Implicit_steady::calcul_mat_masse_diviser_par_dt_vdf(), Implicit_steady::calcul_mat_masse_diviser_par_dt_vef(), Transport_Marqueur_FT::calcul_proprietes_geometriques(), Traitement_particulier_NS_canal::calcul_reynolds_tau(), Transport_Interfaces_FT_Disc::calcul_tolerance_projete_diphasique(), Transport_Interfaces_FT_Disc::calcul_tolerance_projete_monophasique(), Transport_Interfaces_FT_Disc::calcul_vitesse(), Perte_Charge_Singuliere::calculate_Q(), Terme_Source_Constituant_Vortex_VEF_Face::calculer(), Masse_Multiphase::calculer_alpha_rho(), Energie_Multiphase::calculer_alpha_rho_e(), Energie_Multiphase::calculer_alpha_rho_h(), Navier_Stokes_FT_Disc::calculer_champ_forces_superficielles(), Transport_Interfaces_FT_Disc::calculer_composantes_connexes_pour_suppression(), Maillage_FT_Disc::calculer_costheta_minmax(), Navier_Stokes_FT_Disc::calculer_delta_u_interface(), Navier_Stokes_FT_Disc::calculer_dI_dt(), Transport_Interfaces_FT_Disc::calculer_distance_interface(), Transport_Interfaces_FT_Disc::calculer_distance_interface_faces(), Transport_Interfaces_FT_Disc::calculer_distance_interface_sommets(), Navier_Stokes_FT_Disc::calculer_div_normale_interface(), Terme_Source_Coriolis_VDF_Face::calculer_force_de_Coriolis(), Convection_Diffusion_Temperature_FT_Disc::calculer_grad_t(), Navier_Stokes_FT_Disc::calculer_gradient_indicatrice(), Transport_Interfaces_FT_Disc::calculer_integrale_indicatrice(), Senseur_Interface::calculer_position(), Operateur_base::calculer_pour_post(), Navier_Stokes_std::calculer_pression_hydrostatique(), Modele_turbulence_hyd_K_Eps::calculer_viscosite_turbulente(), Modele_turbulence_hyd_K_Eps_2_Couches::calculer_viscosite_turbulente(), Modele_turbulence_hyd_K_Eps_Bas_Reynolds::calculer_viscosite_turbulente(), Modele_turbulence_hyd_K_Eps_Bicephale::calculer_viscosite_turbulente(), Modele_turbulence_hyd_K_Omega::calculer_viscosite_turbulente(), Transport_Interfaces_FT_Disc::calculer_vitesse_transport_interpolee(), Transport_Interfaces_FT_Disc::calculer_vmoy_composantes_connexes(), Triple_Line_Model_FT_Disc::completer(), Operateur_base::completer(), Source_base::completer(), Convection_diffusion_turbulence_multiphase::completer(), Convection_Diffusion_Temperature_FT_Disc::completer(), Eq_rayo_semi_transp_VDF::completer(), Eq_rayo_semi_transp_VEF::completer(), Transport_K_Omega::completer(), Convection_Diffusion_Chaleur_WC::completer(), Navier_Stokes_std::completer(), Terme_Source_Canal_perio::completer(), Masse_Multiphase::completer(), Sortie_libre_Gradient_Pression_impose::completer(), Sortie_libre_Pression_imposee_Orlansky::completer(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::completer(), Champ_Generique_Gradient::completer(), Fluide_Dilatable_base::completer(), Fluide_Dilatable_base::completer_edo(), Convection_Diffusion_Temperature_FT_Disc::compute_divergence_free_velocity_extension(), Navier_Stokes_FT_Disc::compute_eulerian_field_contact_forces(), Post_Processing_Hydrodynamic_Forces::compute_friction_force_projected_tensor(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_friction_force_projected_tensor(), Terme_Source_Canal_perio::compute_heat_flux(), Post_Processing_Hydrodynamic_Forces::compute_heat_transfer(), Post_Processing_Hydrodynamic_Forces::compute_neighbors_coordinates_fluid_fa7(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_neighbors_coordinates_fluid_fa7(), Navier_Stokes_FT_Disc::compute_particles_eulerian_id_number(), Transport_Interfaces_FT_Disc::compute_particles_rms(), Triple_Line_Model_FT_Disc::compute_TCL_fluxes_in_all_boundary_cells(), Post_Processing_Hydrodynamic_Forces::compute_viscosity_edges_sphere(), Domaine_ALE::computeFluidForceOnBeam(), Transport_K_Eps_base::controler_K_Eps(), Transport_K_Omega_base::controler_K_Omega(), Transport_K_ou_Eps_base::controler_variable(), Navier_Stokes_FT_Disc::correct_at_exit_bad_gradient(), Convection_Diffusion_Temperature_FT_Disc::correct_mpoint(), Transport_Marqueur_FT::creer_champ(), Navier_Stokes_phase_field::creer_champ(), Paroi_hyd_base_EF::creer_champ(), creer_champ(), Convection_Diffusion_Temperature::creer_champ(), Convection_Diffusion_Temperature_base::creer_champ(), Navier_Stokes_std::creer_champ(), QDM_Multiphase::creer_champ(), Turbulence_paroi_base::creer_champ(), Conduction::creer_champ(), Fluide_base::creer_e_int(), Transport_Interfaces_FT_Disc::deplacer_maillage_ft_v_fluide(), Navier_Stokes_phase_field::derivee_en_temps_inco(), Navier_Stokes_FT_Disc::derivee_en_temps_inco(), Transport_Marqueur_FT::detection_groupes_a_supprimer(), Terme_Source_Decroissance_Radioactive_Elem_PolyMAC::dimensionner_blocs(), discretiser(), Navier_Stokes_std_ALE::discretiser(), Echelle_temporelle_turbulente::discretiser(), Energie_cinetique_turbulente::discretiser(), Energie_cinetique_turbulente_WIT::discretiser(), Taux_dissipation_turbulent::discretiser(), Convection_Diffusion_Temperature_FT_Disc::discretiser(), Navier_Stokes_FT_Disc::discretiser(), Transport_Interfaces_FT_Disc::discretiser(), Transport_Marqueur_FT::discretiser(), Convection_Diffusion_Phase_field::discretiser(), Navier_Stokes_phase_field::discretiser(), Equation_rayonnement_base::discretiser(), Transport_K_Eps_base::discretiser(), Transport_K_Omega_base::discretiser(), Transport_K_ou_Eps_base::discretiser(), Transport_Fluctuation_Temperature::discretiser(), Transport_Fluctuation_Temperature_W::discretiser(), Transport_Flux_Chaleur_Turbulente::discretiser(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::discretiser(), Convection_Diffusion_Espece_Fluide_Dilatable_base::discretiser(), Navier_Stokes_Fluide_Dilatable_base::discretiser(), Convection_Diffusion_Concentration::discretiser(), Convection_Diffusion_Temperature::discretiser(), Navier_Stokes_std::discretiser(), Aire_interfaciale::discretiser(), Energie_Multiphase::discretiser(), Energie_Multiphase_Enthalpie::discretiser(), Masse_Multiphase::discretiser(), Navier_Stokes_Turbulent_QC::discretiser(), Conduction::discretiser(), Milieu_base::discretiser(), Marqueur_Lagrange_base::discretiser(), Fluide_Dilatable_base::discretiser(), Fluide_Quasi_Compressible::discretiser(), Fluide_Weakly_Compressible::discretiser(), Fluide_base::discretiser(), Fluide_Ostwald::discretiser(), Fluide_reel_base::discretiser(), Milieu_composite::discretiser(), Solide::discretiser(), Convection_Diffusion_Temperature_FT_Disc::discretiser_assembleur_pression(), Navier_Stokes_std::discretiser_assembleur_pression(), Navier_Stokes_FT_Disc::discretiser_assembleur_pression(), Milieu_base::discretiser_diametre_hydro(), Navier_Stokes_std::discretiser_grad_p(), Constituant::discretiser_multi_concentration(), Reaction::discretiser_omega(), Milieu_base::discretiser_porosite(), Navier_Stokes_std::discretiser_vitesse(), QDM_Multiphase::discretiser_vitesse(), Domaine_Cl_dis_base::domaine_dis(), Convection_Diffusion_Temperature::ecrire_fichier_pena_th(), Eq_rayo_semi_transp_VDF::evaluer_cl_rayonnement(), Eq_rayo_semi_transp_VEF::evaluer_cl_rayonnement(), RK3_MassRedistrib::faire_un_pas_de_temps_eqn_base(), Schema_Euler_explicite_Phase_field::faire_un_pas_de_temps_eqn_base(), Post_Processing_Hydrodynamic_Forces_Stokes::fill_Stokes_pressure_field(), Post_Processing_Hydrodynamic_Forces_Stokes::fill_Stokes_velocity_field(), Post_Processing_Hydrodynamic_Forces::find_neighboring_elements(), Post_Processing_Hydrodynamic_Forces::find_neighboring_faces(), Sortie_libre_Gradient_Pression_libre_VEF::flux_impose(), Paroi_hyd_base_EF::get_champ(), Turbulence_paroi_base::get_champ(), Champ_Generique_Tparoi_VEF::get_champ(), Transport_Interfaces_FT_Disc::get_compute_indicatrice_faces(), Transport_Interfaces_FT_Disc::get_expression_vitesse_imposee(), Transport_2eq_base::get_position_cells(), Transport_2eq_base::get_position_faces(), Triple_Line_Model_FT_Disc::get_theta_app(), Convection_Diffusion_Temperature::get_time_factor(), Convection_Diffusion_Temperature_FT_Disc::get_Twall(), Convection_Diffusion_Temperature_FT_Disc::get_Twall_at_elem(), Transport_Marqueur_FT::imposer_cond_lim(), Op_EF_base::impr(), Op_VEF_Face::impr(), Transport_Interfaces_FT_Disc::impr(), Transport_Interfaces_FT_Disc::impr_effort_fluide_interface(), init_champ_conserve(), Energie_Multiphase::init_champ_convecte(), Echange_contact_PolyMAC_P0::init_op(), Echange_contact_PolyMAC_P0P1NC::init_op(), Transport_Interfaces_FT_Disc::init_particles_position_velocity(), Sortie_libre_Gradient_Pression_libre_VEF::initialiser(), Terme_Puissance_Thermique::initialiser_champ_puissance(), IJK_Interfaces::initialize(), Transport_Interfaces_FT_Disc::interpoler_vitesse_face(), Imprimer_Fichiers_RANS_VDF::interpreter(), Imprimer_Fichiers_RANS_VEF::interpreter(), SETS::iterer_NS(), Modele_turbulence_hyd_base::limiter_viscosite_turbulente(), Terme_Source_Acceleration::lire_data(), Terme_Puissance_Thermique::lire_donnees(), Transport_Interfaces_FT_Disc::lire_maillage_ft_cao(), Convection_Diffusion_Turbulent::lire_modele(), Navier_Stokes_Turbulent_ALE::lire_motcle_non_standard(), Navier_Stokes_phase_field::lire_motcle_non_standard(), Convection_Diffusion_Temperature::lire_motcle_non_standard(), Convection_Diffusion_Concentration_FT_Disc::marquer_faces_sous_domaine(), Convection_Diffusion_Concentration_Turbulent_FT_Disc::marquer_faces_sous_domaine(), T_paroi_Champ_P1NC::me_calculer(), Convection_Diffusion_Concentration_FT_Disc::mettre_a_jour(), Convection_Diffusion_Concentration_Turbulent_FT_Disc::mettre_a_jour(), Convection_Diffusion_Temperature_FT_Disc::mettre_a_jour(), Navier_Stokes_FT_Disc::mettre_a_jour(), Transport_Interfaces_FT_Disc::mettre_a_jour(), Echange_contact_rayo_semi_transp_VDF::mettre_a_jour(), QDM_Multiphase::mettre_a_jour(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::mettre_a_jour(), Energie_cinetique_turbulente::mettre_a_jour(), Echange_contact_Rayo_transp_VDF::mettre_a_jour(), PlaqThVDF::mettre_a_jour(), Convection_Diffusion_Concentration_FT_Disc::mettre_a_jour_chimie(), Convection_Diffusion_Concentration_Turbulent_FT_Disc::mettre_a_jour_chimie(), Convection_Diffusion_Temperature::mise_en_place_domaine_fantome(), Op_EF_base::modifier_flux(), Op_VEF_Face::modifier_flux(), Eq_rayo_semi_transp_VDF::modifier_matrice(), Eq_rayo_semi_transp_VEF::modifier_matrice(), Op_VEF_Face::modifier_matrice_pour_periodique_apres_contribuer(), Transport_Interfaces_FT_Disc::modifier_vpoint_pour_imposer_vit(), Convection_Diffusion_Concentration_FT_Disc::multiplier_valeurs_faces(), Convection_Diffusion_Concentration_Turbulent_FT_Disc::multiplier_valeurs_faces(), Eq_rayo_semi_transp_VDF::nb_colonnes(), Eq_rayo_semi_transp_VEF::nb_colonnes(), Eq_rayo_semi_transp_VDF::nb_colonnes_tot(), Eq_rayo_semi_transp_VEF::nb_colonnes_tot(), Operateur_base::ouvrir_fichier(), Convection_Diffusion_Temperature::penalisation_L2(), Transport_Interfaces_FT_Disc::PPP_face_interface(), Transport_Interfaces_FT_Disc::PPP_face_interface_voisin(), Transport_Interfaces_FT_Disc::PPP_face_voisin(), Probleme_base::preparer_calcul(), Navier_Stokes_FT_Disc::preparer_calcul(), Transport_Interfaces_FT_Disc::preparer_calcul(), Op_Evanescence_Homogene_VDF_Face::preparer_calcul(), Transport_Interfaces_FT_Disc::projete_point_face_fluide(), Transport_Interfaces_FT_Disc::projete_point_face_interface(), Transport_Interfaces_FT_Disc::ramasse_miettes(), Transport_Interfaces_FT_Disc::readOn(), Domaine_Cl_dis_base::readOn(), List_Equations_Scalaires_Passifs_Especes::readOn(), Modele_turbulence_hyd_null::readOn(), Modele_turbulence_scal_null::readOn(), Transport_Interfaces_FT_Disc::reprendre(), Collision_Model_FT_base::research_collision_pairs_Verlet(), Eq_rayo_semi_transp_VDF::resoudre(), Eq_rayo_semi_transp_VEF::resoudre(), Navier_Stokes_phase_field::rho_aux_faces(), Convection_Diffusion_Temperature_FT_Disc::suppression_interfaces(), Transport_Interfaces_FT_Disc::swap_particles_lagrangian_position_velocity(), Transport_Interfaces_FT_Disc::test_suppression_interfaces_sous_domaine(), Remailleur_Collision_FT_Juric::traite_RuptureCoalescenceInterfaces(), Convection_Diffusion_Temperature::transport_ibc(), Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_face(), Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_face_sommets(), Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_gradU_elem(), Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_gradU_elem_P1(), Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_gradU_face(), Modele_Fonc_Bas_Reynolds_Base::typer_lire_Modele_Fonc_Bas_Reynolds(), Modele_Fonc_Bas_Reynolds_Thermique_Base::typer_lire_Modele_Fonc_Bas_Reynolds_Thermique(), Modele_Fonc_Realisable_base::typer_lire_Modele_Fonc_Realisable(), Turbulence_paroi_base::typer_lire_turbulence_paroi(), Turbulence_paroi_scal_base::typer_lire_turbulence_paroi_scal(), and Domaine_ALE::update_ALE_projection().
domaine_dis() [2/2]
const Domaine_dis_base & Equation_base::domaine_dis () const
Renvoie le domaine discretisee associee a l'equation.
(version const)
Returns
(Domaine_dis_base&) le domaine discretisee asssociee a l'equation
Exceptions
l'objet domaine discretisee (Domaine_dis) est invalide, probleme associe non discretise.
References Process::exit(), le_dom_dis, TRUST_Ref< _CLASSE_ >::non_nul(), Objet_U::que_suis_je(), and TRUST_Ref< _CLASSE_ >::valeur().
le_nom()
const Nom & Equation_base::le_nom () const inline override virtual
Renvoie le nom de l'equation.
Returns
(Nom&) le nom de l'equation
Reimplemented from Objet_U.
References nom_.
Referenced by Op_Conv_ALE::ajouter(), Source_Portance::ajouter(), Convection_Diffusion_Temperature_sensibility::associate_evaluator_field(), Navier_Stokes_std_sensibility::associate_evaluator_field(), Op_Conv_ALE_VEF::calculateALEMeshVelocityGradientOnFaces(), Source_Portance::completer(), Champ_Generique_Gradient::completer(), Convection_Diffusion_Temperature_FT_Disc::discretiser(), Navier_Stokes_FT_Disc::discretiser(), Transport_Interfaces_FT_Disc::discretiser(), Transport_Marqueur_FT::discretiser(), Probleme_FT_Disc_gen::equation_hydraulique(), Probleme_FT_Disc_gen::equation_interfaces(), Champ_P1NC_implementation::filtrer_L2(), get_champ(), Probleme_FT_Disc_gen::get_equation_by_name(), Probleme_FT_Disc_gen::getset_equation_by_name(), has_champ(), imprime_residu(), lire_cond_init(), Postprocessing_IJK::lire_entete_bloc_interface(), Convection_Diffusion_Concentration_FT_Disc::mettre_a_jour(), Convection_Diffusion_Concentration_Turbulent_FT_Disc::mettre_a_jour(), Transport_Interfaces_FT_Disc::mettre_a_jour(), Transport_Interfaces_FT_Disc::preparer_calcul(), Navier_Stokes_FTD_IJK::printOn(), Convection_Diffusion_Concentration_FT_Disc::readOn(), Convection_Diffusion_Concentration_Turbulent_FT_Disc::readOn(), List_Equations_Scalaires_Passifs_Especes::readOn(), Transport_Interfaces_FT_Disc::remailler_interface(), reprendre(), and verifie_ch_init_nb_comp().
get_residu()
DoubleVect & Equation_base::get_residu () inline
Referenced by Schema_Temps_base::update_critere_statio().
residu_initial()
DoubleVect & Equation_base::residu_initial () inline
Referenced by Schema_Temps_base::update_critere_statio().
initialise_residu()
void Equation_base::initialise_residu (int size = 0)
References inconnue(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), and Champ_Inc_base::valeurs().
Referenced by completer(), Transport_Marqueur_FT::completer(), Navier_Stokes_std::completer(), and preparer_calcul().
imprime_residu()
void Equation_base::imprime_residu (SFichier & fic) virtual
Reimplemented in Navier_Stokes_Turbulent_ALE, Navier_Stokes_IBM_Turbulent, and Navier_Stokes_Turbulent.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Process::exit(), inconnue(), Process::je_suis_maitre(), le_nom(), Field_base::le_nom(), limpr(), Objet_U::nom_du_cas(), Schema_Temps_base::norm_residu(), schema_temps(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and Champ_Inc_base::valeurs().
Referenced by Navier_Stokes_Turbulent_ALE::imprime_residu(), Navier_Stokes_IBM_Turbulent::imprime_residu(), Navier_Stokes_Turbulent::imprime_residu(), and Schema_Temps_base::write_dt_ev().
expression_residu()
Nom Equation_base::expression_residu () virtual
Reimplemented in Navier_Stokes_Turbulent_ALE, Navier_Stokes_IBM_Turbulent, and Navier_Stokes_Turbulent.
References inconnue(), Field_base::le_nom(), Probleme_U::le_nom(), Field_base::nom_compo(), Schema_Temps_base::norm_residu(), probleme(), schema_temps(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by Navier_Stokes_Turbulent_ALE::expression_residu(), Navier_Stokes_IBM_Turbulent::expression_residu(), Navier_Stokes_Turbulent::expression_residu(), and Schema_Temps_base::write_dt_ev().
dimensionner_matrice()
void Equation_base::dimensionner_matrice (Matrice_Morse & mat_morse) virtual
References dimensionner_matrice_sans_mem(), discretisation(), Matrice_Morse::get_set_coeff(), Matrice_Morse::get_set_tab1(), Matrice_Morse::get_set_tab2(), matrice_init, matrice_stockee, Matrice_Morse::nb_colonnes(), probleme(), TRUSTVect< _TYPE_, _SIZE_ >::ref_array(), Matrice_Morse::set_nb_columns(), Matrice_Morse::sort_stencil(), and Matrice_Morse::sorted_.
Referenced by Solveur_Lineaire_Std::iterer_eqn(), Simple::iterer_eqn(), and Simple::iterer_eqs().
dimensionner_matrice_sans_mem()
void Equation_base::dimensionner_matrice_sans_mem (Matrice_Morse & mat_morse) virtual
Reimplemented in Navier_Stokes_std, Energie_Multiphase, Masse_Multiphase, and QDM_Multiphase.
References Operateur_base::dimensionner(), Sources::dimensionner(), Solveur_Masse_base::dimensionner(), Matrice_Morse::get_set_coeff(), Matrice_Morse::get_set_tab1(), Matrice_Morse::get_set_tab2(), Operateur::l_op_base(), les_sources, matrice_init, matrice_stockee, Matrice_Morse::nb_colonnes(), nombre_d_operateurs(), operateur(), TRUSTVect< _TYPE_, _SIZE_ >::ref_array(), Matrice_Morse::set_nb_columns(), and solv_masse().
Referenced by dimensionner_matrice(), Navier_Stokes_std::dimensionner_matrice_sans_mem(), Energie_Multiphase::dimensionner_matrice_sans_mem(), and Masse_Multiphase::dimensionner_matrice_sans_mem().
assembler()
void Equation_base::assembler (Matrice_Morse & mat_morse, const DoubleTab & present, DoubleTab & secmem) virtual
Reimplemented in Convection_Diffusion_Chaleur_Fluide_Dilatable_base, Transport_Interfaces_FT_Disc, Convection_Diffusion_Espece_Binaire_base, Navier_Stokes_Fluide_Dilatable_base, Convection_Diffusion_Espece_Multi_QC, Convection_Diffusion_Espece_Multi_WC, Convection_Diffusion_Temperature_IBM, Navier_Stokes_IBM, Convection_Diffusion_Temperature, Navier_Stokes_Turbulent_QC, Conduction_IBM, and Convection_Diffusion_Espece_Fluide_Dilatable_base.
References Operateur::ajouter(), Sources::ajouter(), Matrice_Base::ajouter_multvect(), Statistiques::begin_count(), Discretisation_base::codage_du_calcul_du_residu(), Operateur_base::contribuer_a_avec(), Sources::contribuer_a_avec(), Operateur_base::contribuer_au_second_membre(), Probleme_base::discretisation(), Statistiques::end_count(), Process::exit(), Operateur::l_op_base(), nombre_d_operateurs(), operateur(), probleme(), sources(), Operateur_base::tester_contribuer_a_avec(), Discretisation_base::VIA_AJOUTER, and Discretisation_base::VIA_CONTRIBUER_AU_SECOND_MEMBRE.
Referenced by assembler_avec_inertie().
modifier_pour_Cl()
void Equation_base::modifier_pour_Cl (Matrice_Morse & mat_morse, DoubleTab & secmem) const virtual
References Operateur::l_op_base(), Operateur_base::modifier_pour_Cl(), nombre_d_operateurs(), and operateur().
Referenced by assembler_avec_inertie(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::assembler_blocs_avec_inertie(), Convection_Diffusion_Espece_Binaire_base::assembler_blocs_avec_inertie(), Convection_Diffusion_Espece_Multi_QC::assembler_blocs_avec_inertie(), Convection_Diffusion_Espece_Multi_WC::assembler_blocs_avec_inertie(), and assembler_blocs_avec_inertie().
assembler_avec_inertie()
void Equation_base::assembler_avec_inertie (Matrice_Morse & mat_morse, const DoubleTab & present, DoubleTab & secmem) virtual
Reimplemented in Navier_Stokes_Fluide_Dilatable_base, and Navier_Stokes_Turbulent_QC.
References Schema_Temps_base::ajouter_inertie(), assembler(), Statistiques::begin_count(), Statistiques::end_count(), modifier_pour_Cl(), and schema_temps().
Referenced by Solveur_Lineaire_Std::iterer_eqn(), and Simple::iterer_eqs().
dimensionner_termes_croises()
void Equation_base::dimensionner_termes_croises (Matrice_Morse & matrice, const Probleme_base & autre_pb, int nl, int nc) virtual
References Matrice_Morse::dimensionner(), Operateur_base::dimensionner_termes_croises(), Operateur::l_op_base(), Matrice_Morse::nb_colonnes(), nombre_d_operateurs(), and operateur().
Referenced by Simple::iterer_eqs().
ajouter_termes_croises()
void Equation_base::ajouter_termes_croises (const DoubleTab & inco, const Probleme_base & autre_pb, const DoubleTab & autre_inco, DoubleTab & resu) const virtual
References Operateur_base::ajouter_termes_croises(), Operateur::l_op_base(), nombre_d_operateurs(), and operateur().
Referenced by Simple::iterer_eqs().
contribuer_termes_croises()
void Equation_base::contribuer_termes_croises (const DoubleTab & inco, const Probleme_base & autre_pb, const DoubleTab & autre_inco, Matrice_Morse & matrice) const virtual
References Operateur_base::contribuer_termes_croises(), Operateur::l_op_base(), nombre_d_operateurs(), and operateur().
Referenced by Simple::iterer_eqs().
has_interface_blocs()
int Equation_base::has_interface_blocs () const virtual
Reimplemented in Navier_Stokes_std, Energie_Multiphase, Masse_Multiphase, and QDM_Multiphase.
References Operateur_base::has_interface_blocs(), Solveur_Masse_base::has_interface_blocs(), Operateur::l_op_base(), les_sources, nombre_d_operateurs(), operateur(), TRUST_List< _CLASSE_ >::size(), and solv_masse().
Referenced by Navier_Stokes_std::has_interface_blocs(), Energie_Multiphase::has_interface_blocs(), and Masse_Multiphase::has_interface_blocs().
get_time_factor()
virtual double Equation_base::get_time_factor () const inline virtual
Reimplemented in Convection_Diffusion_Temperature.
Referenced by derivee_en_temps_inco().
dimensionner_blocs()
void Equation_base::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl = {}) const virtual
Reimplemented in Navier_Stokes_std, Energie_Multiphase, Masse_Multiphase, and QDM_Multiphase.
References Operateur_base::dimensionner_blocs(), Solveur_Masse_base::dimensionner_blocs(), Operateur::l_op_base(), les_sources, nombre_d_operateurs(), operateur(), TRUST_List< _CLASSE_ >::size(), and solv_masse().
Referenced by Navier_Stokes_std::dimensionner_blocs(), Energie_Multiphase::dimensionner_blocs(), and Masse_Multiphase::dimensionner_blocs().
assembler_blocs()
void Equation_base::assembler_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = {}) const virtual
Reimplemented in Convection_Diffusion_Temperature, and Navier_Stokes_std.
References Operateur_base::ajouter_blocs(), Matrice_Base::ajouter_multvect(), Statistiques::begin_count(), discretisation(), Statistiques::end_count(), Nom::getString(), inconnue(), Operateur::l_op_base(), Field_base::le_nom(), les_sources, nombre_d_operateurs(), operateur(), probleme(), Objet_U::que_suis_je(), and TRUST_List< _CLASSE_ >::size().
Referenced by Convection_Diffusion_Temperature::assembler_blocs(), Navier_Stokes_std::assembler_blocs(), and assembler_blocs_avec_inertie().
assembler_blocs_avec_inertie()
void Equation_base::assembler_blocs_avec_inertie (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = {}) virtual
Reimplemented in Convection_Diffusion_Chaleur_Fluide_Dilatable_base, Convection_Diffusion_Espece_Binaire_base, Navier_Stokes_Fluide_Dilatable_base, Convection_Diffusion_Espece_Multi_QC, Convection_Diffusion_Espece_Multi_WC, Energie_Multiphase, Masse_Multiphase, and QDM_Multiphase.
References Schema_Temps_base::ajouter_blocs(), assembler_blocs(), Statistiques::begin_count(), discretisation(), Statistiques::end_count(), Nom::getString(), inconnue(), Field_base::le_nom(), modifier_pour_Cl(), schema_temps(), Solveur_Masse_base::set_penalisation_flag(), and solv_masse().
Referenced by Energie_Multiphase::assembler_blocs_avec_inertie(), Masse_Multiphase::assembler_blocs_avec_inertie(), QDM_Multiphase::assembler_blocs_avec_inertie(), and Simple::iterer_eqs().
champ_conserve()
Champ_Inc_base & Equation_base::champ_conserve () const inline
References champ_conserve_, and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by Op_Dift_VDF_base::ajoute_terme_pour_axi_turb(), Perte_Charge_Singuliere_VDF_Face::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_P0_Face::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Face::ajouter_blocs(), Source_Dissipation_energie_cin_turb::ajouter_blocs(), Perte_Charge_Singuliere_PolyMAC_P0P1NC_Face::ajouter_blocs(), Source_Flux_interfacial_base::ajouter_blocs(), Op_Conv_Amont_VPoly_VDF_Face::ajouter_blocs(), Masse_PolyMAC_P0_Face::ajouter_blocs(), Masse_VDF_Face::ajouter_blocs(), Solveur_Masse_Face_proto::ajouter_blocs_proto(), Assembleur_P_PolyMAC_P0P1NC::assembler_continuite(), and initTimeStep().
has_champ_conserve()
int Equation_base::has_champ_conserve () const inline
References champ_conserve_, and Objet_U_ptr::non_nul().
init_champ_conserve()
void Equation_base::init_champ_conserve () const
References Champ_Inc_base::associer_eqn(), champ_conserve_, Discretisation_base::creer_champ(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), discretisation(), domaine_dis(), get_fonc_champ_conserve(), inconnue(), Champ_Inc_base::init_champ_calcule(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Champ_Inc_base::nb_valeurs_temporelles(), Field_base::nommer(), Objet_U_ptr::non_nul(), Objet_U::que_suis_je(), schema_temps(), TRUSTVect< _TYPE_, _SIZE_ >::size_reelle_ok(), and Champ_Inc_base::valeurs().
Referenced by init_champ_convecte().
calculer_champ_conserve()
void Equation_base::calculer_champ_conserve (const Objet_U & obj, DoubleTab & val, DoubleTab & bval, tabs_t & deriv) static
References TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), get_champ(), Solveur_Masse_base::get_name_of_coefficient_temporel(), Nom::getString(), Solveur_Masse_base::has_coefficient_temporel(), inconnue(), Field_base::le_nom(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), solv_masse(), Champ_base::valeur_aux_bords(), Champ_Inc_base::valeur_aux_bords(), Champ_Inc_base::valeurs(), and Champ_Proto::valeurs().
Referenced by get_fonc_champ_conserve().
get_fonc_champ_conserve()
virtual std::pair< std::string, fonc_calc_t > Equation_base::get_fonc_champ_conserve () const inline virtual
Reimplemented in Echelle_temporelle_turbulente, Energie_cinetique_turbulente, Energie_cinetique_turbulente_WIT, Taux_dissipation_turbulent, Energie_Multiphase, and Masse_Multiphase.
References calculer_champ_conserve(), Nom::getString(), inconnue(), and Field_base::le_nom().
Referenced by init_champ_conserve().
champ_convecte()
virtual Champ_Inc_base & Equation_base::champ_convecte () const inline virtual
Reimplemented in Energie_Multiphase.
References champ_conserve_, and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::ajouter_blocs(), Op_Conv_VDF_base::associer_champ_convecte_elem(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::dimensionner_blocs(), Op_Conv_VDF_base::dimensionner_blocs_elem(), initTimeStep(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::mettre_a_jour(), and Op_Conv_VDF_base::mettre_a_jour().
has_champ_convecte()
virtual int Equation_base::has_champ_convecte () const inline virtual
Reimplemented in Energie_Multiphase.
References champ_conserve_, and Objet_U_ptr::non_nul().
Referenced by Op_Conv_VDF_base::associer_champ_convecte_elem(), and Op_Conv_VDF_base::dimensionner_blocs_elem().
init_champ_convecte()
virtual void Equation_base::init_champ_convecte () const inline virtual
Reimplemented in Energie_Multiphase.
References init_champ_conserve().
Referenced by Op_Conv_VDF_base::associer_champ_convecte_elem(), and Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::preparer_calcul().
mettre_a_jour_champs_conserves()
void Equation_base::mettre_a_jour_champs_conserves (double temps, int reset = 0) virtual
References champ_conserve_, champ_convecte_, Champ_Inc_base::mettre_a_jour(), Objet_U_ptr::non_nul(), and Champ_Inc_base::reset_champ_calcule().
Referenced by Probleme_base::mettre_a_jour(), and Probleme_base::preparer_calcul().
creer_champ()
void Equation_base::creer_champ (const Motcle & motlu) override virtual
Implements Champs_compris_interface.
Reimplemented in Navier_Stokes_Turbulent_ALE, Transport_Marqueur_FT, Navier_Stokes_phase_field, Navier_Stokes_Aposteriori, Convection_Diffusion_Temperature_IBM_Turbulent, Navier_Stokes_IBM_Turbulent, Convection_Diffusion_Temperature, Convection_Diffusion_Temperature_base, Navier_Stokes_std, QDM_Multiphase, Convection_Diffusion_Chaleur_Turbulent_QC, Convection_Diffusion_Concentration_Turbulent, Convection_Diffusion_Espece_Binaire_Turbulent_QC, Convection_Diffusion_Espece_Multi_Turbulent_QC, Convection_Diffusion_Temperature_Turbulent, Navier_Stokes_Turbulent, and Conduction.
References Champs_compris_T< FIELD_TYPE >::ajoute_champ(), champs_compris_, Operateur_base::creer_champ(), discretisation(), domaine_dis(), inconnue(), Operateur::l_op_base(), Field_base::le_nom(), les_sources, nombre_d_operateurs(), Objet_U_ptr::non_nul(), Operateur::op_non_nul(), operateur(), and Discretisation_base::residu().
Referenced by Transport_Marqueur_FT::creer_champ(), Probleme_base::creer_champ(), Convection_Diffusion_Temperature_base::creer_champ(), Navier_Stokes_std::creer_champ(), Convection_Diffusion_Chaleur_Turbulent_QC::creer_champ(), Convection_Diffusion_Concentration_Turbulent::creer_champ(), Convection_Diffusion_Espece_Binaire_Turbulent_QC::creer_champ(), Convection_Diffusion_Espece_Multi_Turbulent_QC::creer_champ(), Conduction::creer_champ(), and Transport_K_ou_Eps_base::discretiser().
get_champ()
const Champ_base & Equation_base::get_champ (const Motcle & nom) const override virtual
Implements Champs_compris_interface.
Reimplemented in Navier_Stokes_Turbulent_ALE, Transport_Marqueur_FT, Navier_Stokes_Aposteriori, Transport_K_ou_Eps_base, Convection_Diffusion_Espece_Multi_base, Navier_Stokes_Fluide_Dilatable_base, Convection_Diffusion_Temperature_IBM_Turbulent, Navier_Stokes_IBM_Turbulent, Convection_Diffusion_Temperature, Convection_Diffusion_Temperature_base, Navier_Stokes_std, Convection_Diffusion_Chaleur_Turbulent_QC, Convection_Diffusion_Concentration_Turbulent, Convection_Diffusion_Espece_Binaire_Turbulent_QC, Convection_Diffusion_Espece_Multi_Turbulent_QC, Convection_Diffusion_Temperature_Turbulent, Navier_Stokes_Turbulent, Navier_Stokes_Turbulent_QC, and Conduction.
References champs_compris_, Nom::getString(), has_champ(), Operateur_base::has_champ(), Champs_compris_T< FIELD_TYPE >::has_champ(), inconnue(), Operateur::l_op_base(), le_nom(), les_sources, list_champ_combi, Champ_Fonc_base::mettre_a_jour(), milieu(), nombre_d_operateurs(), Operateur::op_non_nul(), operateur(), schema_temps(), Champ_base::temps(), Schema_Temps_base::temps_init(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by Masse_PolyMAC_P0_Face::ajouter_blocs(), Solveur_Masse_base::appliquer(), Masse_DG_base::appliquer_coef(), Masse_PolyMAC_base::appliquer_coef(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_blocs(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_impl(), calculer_champ_conserve(), Echange_contact_ODVM_VDF::calculer_Teta_equiv(), Convection_Diffusion_Fluide_Dilatable_Proto::derivee_en_temps_inco_sans_solveur_masse_impl(), Assembleur_P_PolyMAC_P0P1NC::dimensionner_continuite(), Convection_Diffusion_Espece_Binaire_Turbulent_QC::get_champ(), has_champ(), and Op_EF_base::marque_elem().
get_noms_champs_postraitables()
void Equation_base::get_noms_champs_postraitables (Noms & nom, Option opt = NONE) const override virtual
Implements Champs_compris_interface.
Reimplemented in Navier_Stokes_Turbulent_ALE, Transport_Marqueur_FT, Navier_Stokes_Aposteriori, Convection_Diffusion_Temperature_IBM_Turbulent, Navier_Stokes_IBM_Turbulent, Convection_Diffusion_Temperature, Convection_Diffusion_Temperature_base, Navier_Stokes_std, QDM_Multiphase, Convection_Diffusion_Chaleur_Turbulent_QC, Convection_Diffusion_Concentration_Turbulent, Convection_Diffusion_Espece_Binaire_Turbulent_QC, Convection_Diffusion_Espece_Multi_Turbulent_QC, Convection_Diffusion_Temperature_Turbulent, Navier_Stokes_Turbulent, Conduction, IJK_Interfaces, IJK_Thermals, and Navier_Stokes_FTD_IJK.
References TRUST_Vector< _CLASSE_ >::add(), champs_compris_, Milieu_base::get_noms_champs_postraitables(), Operateur_base::get_noms_champs_postraitables(), Operateur::l_op_base(), les_sources, Champs_compris_T< FIELD_TYPE >::liste_noms_compris(), milieu(), nombre_d_operateurs(), Operateur::op_non_nul(), operateur(), and Objet_U::que_suis_je().
Referenced by Transport_Marqueur_FT::get_noms_champs_postraitables(), Modele_turbulence_scal_Fluctuation_Temperature::get_noms_champs_postraitables(), Modele_turbulence_scal_Fluctuation_Temperature_W::get_noms_champs_postraitables(), Modele_turbulence_hyd_RANS_Bicephale_base::get_noms_champs_postraitables(), Modele_turbulence_hyd_RANS_K_Eps_base::get_noms_champs_postraitables(), Modele_turbulence_hyd_RANS_K_Omega_base::get_noms_champs_postraitables(), Probleme_base::get_noms_champs_postraitables(), Convection_Diffusion_Temperature_base::get_noms_champs_postraitables(), Navier_Stokes_std::get_noms_champs_postraitables(), Convection_Diffusion_Chaleur_Turbulent_QC::get_noms_champs_postraitables(), Convection_Diffusion_Concentration_Turbulent::get_noms_champs_postraitables(), Convection_Diffusion_Espece_Binaire_Turbulent_QC::get_noms_champs_postraitables(), Convection_Diffusion_Espece_Multi_Turbulent_QC::get_noms_champs_postraitables(), and Conduction::get_noms_champs_postraitables().
has_champ() [1/2]
bool Equation_base::has_champ (const Motcle & nom, TRUST_Ref< Champ_base * > & ref_champ) const override virtual
Implements Champs_compris_interface.
Reimplemented in Navier_Stokes_Turbulent_ALE, IJK_Interfaces, IJK_Thermals, Navier_Stokes_FTD_IJK, Transport_Marqueur_FT, Navier_Stokes_Aposteriori, Transport_K_ou_Eps_base, Convection_Diffusion_Espece_Multi_base, Navier_Stokes_Fluide_Dilatable_base, Convection_Diffusion_Temperature_IBM_Turbulent, Navier_Stokes_IBM_Turbulent, Convection_Diffusion_Temperature, Convection_Diffusion_Temperature_base, Navier_Stokes_std, Convection_Diffusion_Chaleur_Turbulent_QC, Convection_Diffusion_Concentration_Turbulent, Convection_Diffusion_Espece_Binaire_Turbulent_QC, Convection_Diffusion_Espece_Multi_Turbulent_QC, Convection_Diffusion_Temperature_Turbulent, Navier_Stokes_Turbulent, Navier_Stokes_Turbulent_QC, and Conduction.
References champs_compris_, get_champ(), has_champ(), Operateur_base::has_champ(), Champs_compris_T< FIELD_TYPE >::has_champ(), inconnue(), Operateur::l_op_base(), le_nom(), les_sources, list_champ_combi, milieu(), nombre_d_operateurs(), Operateur::op_non_nul(), and operateur().
Referenced by Echange_contact_ODVM_VDF::calculer_Teta_equiv(), Transport_Marqueur_FT::get_champ(), Transport_K_ou_Eps_base::get_champ(), Modele_turbulence_scal_Fluctuation_Temperature::get_champ(), Modele_turbulence_scal_Fluctuation_Temperature_W::get_champ(), Modele_turbulence_hyd_RANS_Bicephale_base::get_champ(), Modele_turbulence_hyd_RANS_K_Eps_base::get_champ(), Modele_turbulence_hyd_RANS_K_Omega_base::get_champ(), get_champ(), Probleme_base::get_champ(), Convection_Diffusion_Espece_Multi_base::get_champ(), Convection_Diffusion_Temperature_base::get_champ(), Navier_Stokes_std::get_champ(), Convection_Diffusion_Chaleur_Turbulent_QC::get_champ(), Convection_Diffusion_Concentration_Turbulent::get_champ(), Convection_Diffusion_Espece_Binaire_Turbulent_QC::get_champ(), Conduction::get_champ(), Transport_Marqueur_FT::has_champ(), Transport_K_ou_Eps_base::has_champ(), Modele_turbulence_scal_Fluctuation_Temperature::has_champ(), Modele_turbulence_scal_Fluctuation_Temperature_W::has_champ(), Modele_turbulence_hyd_RANS_Bicephale_base::has_champ(), Modele_turbulence_hyd_RANS_K_Eps_base::has_champ(), Modele_turbulence_hyd_RANS_K_Omega_base::has_champ(), has_champ(), Probleme_base::has_champ(), Convection_Diffusion_Espece_Multi_base::has_champ(), Convection_Diffusion_Temperature_base::has_champ(), Navier_Stokes_std::has_champ(), Convection_Diffusion_Chaleur_Turbulent_QC::has_champ(), Convection_Diffusion_Concentration_Turbulent::has_champ(), Convection_Diffusion_Espece_Binaire_Turbulent_QC::has_champ(), Conduction::has_champ(), and Op_EF_base::marque_elem().
has_champ() [2/2]
bool Equation_base::has_champ (const Motcle & nom) const override virtual
Implements Champs_compris_interface.
Reimplemented in Navier_Stokes_Turbulent_ALE, IJK_Interfaces, IJK_Thermals, Navier_Stokes_FTD_IJK, Transport_Marqueur_FT, Navier_Stokes_Aposteriori, Transport_K_ou_Eps_base, Convection_Diffusion_Espece_Multi_base, Navier_Stokes_Fluide_Dilatable_base, Convection_Diffusion_Temperature_IBM_Turbulent, Navier_Stokes_IBM_Turbulent, Convection_Diffusion_Temperature, Convection_Diffusion_Temperature_base, Navier_Stokes_std, Convection_Diffusion_Chaleur_Turbulent_QC, Convection_Diffusion_Concentration_Turbulent, Convection_Diffusion_Espece_Binaire_Turbulent_QC, Convection_Diffusion_Espece_Multi_Turbulent_QC, Convection_Diffusion_Temperature_Turbulent, Navier_Stokes_Turbulent, Navier_Stokes_Turbulent_QC, and Conduction.
References champs_compris_, has_champ(), Operateur_base::has_champ(), Champs_compris_T< FIELD_TYPE >::has_champ(), inconnue(), Operateur::l_op_base(), le_nom(), les_sources, list_champ_combi, milieu(), nombre_d_operateurs(), Operateur::op_non_nul(), and operateur().
domaine_application()
const Motcle & Equation_base::domaine_application () const virtual
Renvoie "indetermine" Navier_Stokes_standard par exemple surcharge cette methode.
pour renvoyer "Hydraulique"
Returns
(Motcle&) le nom du domaine d'aplication
Reimplemented in Convection_diffusion_turbulence_multiphase, Energie_cinetique_turbulente_WIT, Transport_K_Eps, Transport_K_Eps_Bas_Reynolds, Transport_K_Eps_Realisable, Transport_K_KEps, Transport_K_Omega, Transport_K_ou_Eps, Transport_K_ou_Eps_Realisable, Transport_Fluctuation_Temperature, Transport_Fluctuation_Temperature_W, Transport_Flux_Chaleur_Turbulente, Convection_Diffusion_Chaleur_Fluide_Dilatable_base, Convection_Diffusion_Espece_Fluide_Dilatable_base, Convection_Diffusion_Concentration, Convection_Diffusion_Temperature, Navier_Stokes_std, Aire_interfaciale, Energie_Multiphase, Masse_Multiphase, and Conduction.
Referenced by Cond_lim_base::compatible_avec_eqn(), Echange_contact_rayo_semi_transp_VDF::compatible_avec_eqn(), Neumann_paroi_rayo_semi_transp_VDF::compatible_avec_eqn(), Neumann_paroi_rayo_semi_transp_VEF::compatible_avec_eqn(), Temperature_imposee_paroi_rayo_semi_transp::compatible_avec_eqn(), Dirichlet_loi_paroi::compatible_avec_eqn(), Echange_global_impose_turbulent::compatible_avec_eqn(), Schema_Euler_Implicite::faire_un_pas_de_temps_pb_couple(), Echange_contact_PolyMAC::initialiser(), and Echange_contact_VDF::initialiser().
verifie_ch_init_nb_comp()
void Equation_base::verifie_ch_init_nb_comp (const Champ_Inc_base & ch_ref, const int nb_comp) const virtual
Verification du nombre de composantes lues pour la specification d un champ.
Actuellement utilise pour la lecture d un condition initiale ou limite.
Parameters
(ch_ref : un champ inconnu de l equation consideree)
References Objet_U::dimension, Process::exit(), le_nom(), Field_base::le_nom(), Field_base::nature_du_champ(), and Field_base::nb_comp().
Referenced by lire_cond_init(), Navier_Stokes_std::lire_cond_init(), QDM_Multiphase::lire_cond_init(), Echange_global_impose_rayo_semi_transp::verifie_ch_init_nb_comp(), verifie_ch_init_nb_comp_cl(), and Energie_Multiphase::verifie_ch_init_nb_comp_cl().
verifie_ch_init_nb_comp_cl()
virtual void Equation_base::verifie_ch_init_nb_comp_cl (const Champ_Inc_base & ch_ref, const int nb_comp, const Cond_lim_base & cl) const inline virtual
Reimplemented in Energie_Multiphase.
References verifie_ch_init_nb_comp().
Referenced by Dirichlet::verifie_ch_init_nb_comp(), Echange_externe_impose::verifie_ch_init_nb_comp(), Neumann_paroi::verifie_ch_init_nb_comp(), and Neumann_sortie_libre::verifie_ch_init_nb_comp().
derivee_en_temps_conv()
DoubleTab & Equation_base::derivee_en_temps_conv (DoubleTab & secmem, const DoubleTab & solution)
Add convection term In: solution is the unknown I.
Out: secmem is increased by convection(I)
References Operateur::calculer_pas_de_temps(), TRUSTTab< _TYPE_, _SIZE_ >::copy(), le_schema_en_temps, and operateur().
Referenced by derivee_en_temps_inco(), Convection_Diffusion_Temperature::derivee_en_temps_inco(), Navier_Stokes_FT_Disc::derivee_en_temps_inco(), Source_PDF_EF::impr(), and Convection_Diffusion_Temperature::transport_ibc().
Gradient_conjugue_diff_impl() [1/2]
void Equation_base::Gradient_conjugue_diff_impl (DoubleTrav & secmem, DoubleTab & solution) inline
References Gradient_conjugue_diff_impl().
Referenced by derivee_en_temps_inco(), Convection_Diffusion_Fluide_Dilatable_Proto::derivee_en_temps_inco_sans_solveur_masse_impl(), and Gradient_conjugue_diff_impl().
Gradient_conjugue_diff_impl() [2/2]
void Equation_base::Gradient_conjugue_diff_impl (DoubleTrav & secmem, DoubleTab & solution, const DoubleTab & terme_mul) inline
References TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), and Gradient_conjugue_diff_impl().
parametre_equation() [1/2]
TRUST_Deriv< Parametre_equation_base > & Equation_base::parametre_equation () inline
References parametre_equation_.
Referenced by Simpler_Base::get_and_set_parametre_equation(), and Solveur_Implicite_base::get_and_set_parametre_equation().
parametre_equation() [2/2]
const TRUST_Deriv< Parametre_equation_base > & Equation_base::parametre_equation () const inline
References parametre_equation_.
get_modele()
const RefObjU & Equation_base::get_modele (Type_modele type) const virtual
Reimplemented in Navier_Stokes_Turbulent_ALE, Convection_Diffusion_Temperature_IBM_Turbulent, Navier_Stokes_IBM_Turbulent, Convection_Diffusion_Chaleur_Turbulent_QC, Convection_Diffusion_Concentration_Turbulent, Convection_Diffusion_Espece_Binaire_Turbulent_QC, Convection_Diffusion_Espece_Multi_Turbulent_QC, Convection_Diffusion_Temperature_Turbulent, and Navier_Stokes_Turbulent.
References liste_modeles_.
Referenced by Op_Dift_VDF_base::ajoute_terme_pour_axi_turb(), Source_Robin_Scalaire::ajouter(), Champ_front_contact_VEF::calcul_grads_locaux(), Champ_Q1_EF::calcul_y_plus(), Champ_P1NC::calcul_y_plus(), Champ_Face_VDF::calcul_y_plus(), Champ_P1NC::calcul_y_plus_diphasique(), Champ_Face_VDF::calcul_y_plus_diphasique(), Modele_turbulence_scal_LES_dyn_VDF::calculer_diffusivite_turbulente(), Modele_turbulence_scal_Fluctuation_Temperature_W::calculer_diffusivite_turbulente(), Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re::calculer_diffusivite_turbulente(), ParoiVDF_TBLE_LRM::calculer_hyd(), ParoiVDF_TBLE::calculer_hyd(), ParoiVEF_TBLE::calculer_hyd(), ParoiVDF_TBLE::calculer_hyd_BiK(), ParoiVDF_TBLE_LRM::calculer_hyd_BiK(), ParoiVEF_TBLE::calculer_hyd_BiK(), Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_nut(), Paroi_std_scal_hyd_EF::calculer_scal(), Paroi_loi_WW_scal_VDF::calculer_scal(), Paroi_ODVM_scal_VDF::calculer_scal(), Paroi_std_scal_hyd_VDF::calculer_scal(), Paroi_loi_WW_scal_VEF::calculer_scal(), Paroi_scal_analytique_VEF::calculer_scal(), Paroi_std_scal_hyd_VEF::calculer_scal(), Echange_contact_ODVM_VDF::calculer_Teta_equiv(), Op_Diff_K_Eps_VEF_base::completer(), Op_Diff_K_Omega_VEF_base::completer(), Transport_K_Eps_Bas_Reynolds::completer(), Modele_turbulence_scal_Fluctuation_Temperature::completer(), Modele_turbulence_scal_Fluctuation_Temperature_W::completer(), Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re::completer(), Op_Diff_DG_Elem::completer(), Op_Dift_EF_base::completer(), Op_Diff_PolyMAC_Elem::completer(), Op_Diff_PolyMAC_Face::completer(), Modele_turbulence_scal_diffturb_base::completer(), Op_Dift_VDF_Face_Axi_base::completer(), Op_Dift_VEF_base::completer(), Champ_Generique_Morceau_Equation::completer(), Champ_Post_Operateur_Eqn::completer(), Champ_P1NC_implementation::filtrer_L2(), Champ_Generique_Tparoi_VEF::get_champ(), Navier_Stokes_Turbulent_ALE::get_modele(), Convection_Diffusion_Temperature_IBM_Turbulent::get_modele(), Navier_Stokes_IBM_Turbulent::get_modele(), Convection_Diffusion_Chaleur_Turbulent_QC::get_modele(), Convection_Diffusion_Concentration_Turbulent::get_modele(), Convection_Diffusion_Espece_Binaire_Turbulent_QC::get_modele(), Convection_Diffusion_Espece_Multi_Turbulent_QC::get_modele(), Convection_Diffusion_Temperature_Turbulent::get_modele(), Navier_Stokes_Turbulent::get_modele(), Paroi_TBLE_scal_VDF::getLoiParoiHydraulique(), ParoiVEF_TBLE_scal::getLoiParoiHydraulique(), Paroi_TBLE_scal_VDF::init_lois_paroi(), ParoiVEF_TBLE_scal::init_lois_paroi(), Y_plus_Champ_Face::me_calculer(), Y_plus_Champ_P1NC::me_calculer(), PlaqThVDF::mettre_a_jour(), Convection_Diffusion_Concentration_FT_Disc::mettre_a_jour_chimie(), Convection_Diffusion_Concentration_Turbulent_FT_Disc::mettre_a_jour_chimie(), Modele_turbulence_hyd_K_Eps::preparer_calcul(), Modele_turbulence_hyd_K_Eps_Bicephale::preparer_calcul(), Modele_turbulence_scal_base::readOn(), Modele_turbulence_scal_null::readOn(), Turbulence_paroi_scal_base::typer_lire_turbulence_paroi_scal(), and Op_Diff_PolyMAC_base::update_nu().
equation_non_resolue()
int Equation_base::equation_non_resolue () const virtual
References Parser_U::eval(), Value_Input_Int::getName(), Parser_U::getString(), le_schema_en_temps, mon_probleme, and Parser_U::setVar().
Referenced by Schema_Euler_Implicite::faire_un_pas_de_temps_pb_couple(), Schema_Temps_base::iterateTimeStep(), RK3_FT::iterateTimeStep(), Schema_Phase_field::iterateTimeStep(), Multi_Sch_ThHyd::iterateTimeStep(), Sch_CN_iteratif::iterateTimeStepOnEquation(), Simple::iterer_eqn(), Convection_Diffusion_Temperature_IBM::verify_scheme(), Navier_Stokes_IBM::verify_scheme(), and Conduction_IBM::verify_scheme().
disable_equation_residual()
int Equation_base::disable_equation_residual () const inline
Referenced by Schema_Temps_base::update_critere_statio().
derivee_en_temps() [1/2]
virtual const Champ_Inc_base & Equation_base::derivee_en_temps () const inline virtual
References derivee_en_temps_.
Referenced by Schema_Adams_Moulton_base::add_multi_timestep_data(), Schema_Adams_Moulton_base::changer_temps(), derivee_en_temps_inco(), Navier_Stokes_phase_field::derivee_en_temps_inco(), initTimeStep(), mettre_a_jour(), Transport_Interfaces_FT_Disc::mettre_a_jour(), Schema_Adams_Moulton_base::mettre_a_jour_equation(), Schema_Adams_Bashforth_base::modifier_second_membre(), Schema_Adams_Moulton_base::modifier_second_membre_full_impl(), preparer_calcul(), Transport_Interfaces_FT_Disc::preparer_calcul(), and Schema_Adams_Moulton_base::update_time_derivative().
derivee_en_temps() [2/2]
virtual Champ_Inc_base & Equation_base::derivee_en_temps () inline virtual
References derivee_en_temps_.
set_calculate_time_derivative()
void Equation_base::set_calculate_time_derivative (int i) inline
References calculate_time_derivative_.
Referenced by Schema_Adams_Bashforth_base::associer_pb(), Schema_Adams_Moulton_base::associer_pb(), Transport_K_Eps_base::discretiser(), Transport_K_Omega_base::discretiser(), Transport_K_ou_Eps_base::discretiser(), and Equation_base().
calculate_time_derivative()
int Equation_base::calculate_time_derivative () const inline
References calculate_time_derivative_.
Referenced by derivee_en_temps_inco(), Navier_Stokes_phase_field::derivee_en_temps_inco(), discretiser(), Transport_Interfaces_FT_Disc::discretiser(), Transport_K_Eps_base::discretiser(), Transport_K_Omega_base::discretiser(), Transport_K_ou_Eps_base::discretiser(), initTimeStep(), mettre_a_jour(), Transport_Interfaces_FT_Disc::mettre_a_jour(), preparer_calcul(), and Transport_Interfaces_FT_Disc::preparer_calcul().
set_residuals()
void Equation_base::set_residuals (const DoubleTab & residual)
References TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Objet_U_ptr::non_nul(), and Champ_Don_base::valeurs().
Referenced by Schema_Temps_base::update_critere_statio().
positive_unkown()
virtual bool Equation_base::positive_unkown () inline virtual
Reimplemented in Convection_diffusion_turbulence_multiphase, Energie_cinetique_turbulente_WIT, and Aire_interfaciale.
Referenced by SETS::iterer_eqn().
add_champs_compris()
void Equation_base::add_champs_compris (const Champ_base & ch) inline
References Champs_compris_T< FIELD_TYPE >::ajoute_champ(), and champs_compris_.
Referenced by List_Equations_Scalaires_Passifs_Especes::readOn().
set_diffusion_multi_scalaire()
void Equation_base::set_diffusion_multi_scalaire (bool flg = true) inline
References diffusion_multi_scalaire_, and discretisation().
diffusion_multi_scalaire()
const bool & Equation_base::diffusion_multi_scalaire () const inline
References diffusion_multi_scalaire_.
Referenced by Discretisation_base::get_name_of_type_for().
set_param()
void Equation_base::set_param (Param & titi) protected virtual
Reimplemented in Transport_2eq_base, Transport_K_Eps_base, Transport_K_Omega_base, Conduction, Convection_Diffusion_Temperature_sensibility, Navier_Stokes_std_sensibility, Transport_K_Eps, Transport_K_Omega, Transport_K_ou_Eps, Transport_K_ou_Eps_Realisable, Navier_Stokes_Fluide_Dilatable_base, Energie_Multiphase, Masse_Multiphase, QDM_Multiphase, Navier_Stokes_Turbulent_ALE, Energie_cinetique_turbulente, IJK_Interfaces, IJK_Thermals, Navier_Stokes_FTD_IJK, Convection_Diffusion_Concentration_FT_Disc, Convection_Diffusion_Concentration_Turbulent_FT_Disc, Convection_Diffusion_Temperature_FT_Disc, Navier_Stokes_FT_Disc, Transport_Interfaces_FT_Disc, Transport_Marqueur_FT, Convection_Diffusion_Phase_field, Navier_Stokes_phase_field, Equation_rayonnement_base, Transport_K_Eps_non_std, Transport_K_Eps_Realisable, Transport_K_KEps, Transport_K_ou_Eps_non_std, Transport_Fluctuation_Temperature, Transport_Fluctuation_Temperature_W, Transport_Fluctuation_Temperature_W_Bas_Re, Transport_Flux_Chaleur_Turbulente, Convection_Diffusion_Espece_Binaire_base, Convection_Diffusion_Espece_Multi_base, Convection_Diffusion_Fluide_Dilatable_base, Convection_Diffusion_Chaleur_QC, Convection_Diffusion_Espece_Multi_QC, Convection_Diffusion_Chaleur_WC, Convection_Diffusion_Temperature_IBM, Convection_Diffusion_Temperature_IBM_Turbulent, Navier_Stokes_IBM, Navier_Stokes_IBM_Turbulent, Convection_Diffusion_Concentration, Convection_Diffusion_std, Convection_Diffusion_Temperature, Navier_Stokes_std, Convection_Diffusion_Chaleur_Turbulent_QC, Convection_Diffusion_Concentration_Turbulent, Convection_Diffusion_Espece_Binaire_Turbulent_QC, Convection_Diffusion_Espece_Multi_Turbulent_QC, Convection_Diffusion_Temperature_Turbulent, Navier_Stokes_Turbulent, and Conduction_IBM.
References Param::ajouter(), Param::ajouter_non_std(), parametre_equation_, and Param::REQUIRED.
Referenced by readOn(), Transport_2eq_base::set_param(), Conduction::set_param(), Masse_Multiphase::set_param(), Transport_Interfaces_FT_Disc::set_param(), Transport_Marqueur_FT::set_param(), Convection_Diffusion_std::set_param(), and Navier_Stokes_std::set_param().
lire_motcle_non_standard()
int Equation_base::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override protected virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Objet_U.
Reimplemented in Navier_Stokes_Turbulent_ALE, Convection_Diffusion_Concentration_FT_Disc, Convection_Diffusion_Concentration_Turbulent_FT_Disc, Convection_Diffusion_Temperature_FT_Disc, Navier_Stokes_FT_Disc, Transport_Interfaces_FT_Disc, Transport_Marqueur_FT, Convection_Diffusion_Phase_field, Navier_Stokes_phase_field, Equation_rayonnement_base, Transport_K_Eps, Transport_K_Eps_non_std, Transport_K_Eps_Realisable, Transport_K_KEps, Transport_K_Omega, Transport_K_ou_Eps, Transport_K_ou_Eps_non_std, Transport_K_ou_Eps_Realisable, Transport_Fluctuation_Temperature, Transport_Fluctuation_Temperature_W, Transport_Fluctuation_Temperature_W_Bas_Re, Transport_Flux_Chaleur_Turbulente, Convection_Diffusion_Espece_Binaire_base, Convection_Diffusion_Espece_Multi_base, Convection_Diffusion_Fluide_Dilatable_base, Convection_Diffusion_Chaleur_QC, Convection_Diffusion_Espece_Multi_QC, Convection_Diffusion_Chaleur_WC, Convection_Diffusion_Temperature_IBM_Turbulent, Navier_Stokes_IBM_Turbulent, Convection_Diffusion_Concentration, Convection_Diffusion_std, Convection_Diffusion_Temperature, Navier_Stokes_std, Energie_Multiphase, Masse_Multiphase, QDM_Multiphase, Convection_Diffusion_Chaleur_Turbulent_QC, Convection_Diffusion_Concentration_Turbulent, Convection_Diffusion_Espece_Binaire_Turbulent_QC, Convection_Diffusion_Espece_Multi_Turbulent_QC, Convection_Diffusion_Temperature_Turbulent, Navier_Stokes_Turbulent, Conduction, Convection_Diffusion_Temperature_sensibility, Navier_Stokes_std_sensibility, Navier_Stokes_Fluide_Dilatable_base, and IJK_Interfaces.
References Ecrire_fichier_xyz_valeur::associer_eqn(), lire_cl(), lire_cond_init(), lire_sources(), nom_, Parser_U::parseString(), Parser_U::setString(), and verif_Cl().
Referenced by Transport_Interfaces_FT_Disc::lire_motcle_non_standard(), Transport_Marqueur_FT::lire_motcle_non_standard(), Transport_K_Eps::lire_motcle_non_standard(), Transport_K_Eps_non_std::lire_motcle_non_standard(), Transport_K_Eps_Realisable::lire_motcle_non_standard(), Transport_K_Omega::lire_motcle_non_standard(), Transport_K_ou_Eps::lire_motcle_non_standard(), Transport_K_ou_Eps_non_std::lire_motcle_non_standard(), Transport_K_ou_Eps_Realisable::lire_motcle_non_standard(), Convection_Diffusion_std::lire_motcle_non_standard(), Navier_Stokes_std::lire_motcle_non_standard(), and Conduction::lire_motcle_non_standard().
lire_sources()
Entree & Equation_base::lire_sources (Entree & is) protected virtual
Lecture des termes sources dans un flot d'entree.
Parameters
(Entree& is) flot d'entree pour lire les termes sources
Returns
(Entree&) le flot d'entree modifie
References les_sources.
Referenced by lire_motcle_non_standard(), Energie_Multiphase::readOn(), and Masse_Multiphase::readOn().
lire_cond_init()
Entree & Equation_base::lire_cond_init (Entree & is) protected virtual
Lecture des conditions initiales dans un flot d'entree.
Le format de lecture est le suivant: { Nom [DOIT ETRE LE NOM DE L'INCONNUE] [LIRE UN CHAMP DONNE] }
Parameters
(Entree& is) le flot d'entree
Returns
(Entree&) le flot d'entree modifie
Exceptions
erreur de format, accolade ouvrante attendue
mauvais nom pour l'inconnue
erreur de format, accolade fermante attendue
Reimplemented in Navier_Stokes_std, QDM_Multiphase, Transport_Interfaces_FT_Disc, and Transport_Marqueur_FT.
References Champ_base::affecter(), Process::exit(), inconnue(), le_nom(), Field_base::le_nom(), Objet_U::que_suis_je(), and verifie_ch_init_nb_comp().
Referenced by lire_motcle_non_standard().
lire_cl()
Entree & Equation_base::lire_cl (Entree & is) protected virtual
Lecture des conditions limites sur un flot d'entree.
voir Domaine_Cl_dis_base::readOn
Parameters
(Entree& is) le flot d'entree
Returns
(Entree&) le flot d'entree modifie
Exceptions
le domaine des conditions aux limites discretisee est vide
Reimplemented in Transport_Marqueur_FT.
References Process::exit(), le_dom_Cl_dis, Objet_U_ptr::non_nul(), Objet_U::que_suis_je(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by Equation_rayonnement_base::lire_motcle_non_standard(), and lire_motcle_non_standard().
verif_Cl()
int Equation_base::verif_Cl () const protected virtual
Verifie la compatibilite des conditions limites avec l'equation.
voir Conds_lim::compatible_avec_eqn().
Returns
(int)
Reimplemented in Transport_Interfaces_FT_Disc, and Navier_Stokes_std.
References Conds_lim::compatible_avec_discr(), Conds_lim::compatible_avec_eqn(), discretisation(), le_dom_Cl_dis, and Domaine_Cl_dis_base::les_conditions_limites().
Referenced by Equation_rayonnement_base::lire_motcle_non_standard(), lire_motcle_non_standard(), and Navier_Stokes_std::verif_Cl().
lire()
virtual void Equation_base::lire () inline protected virtual
References Process::exit().
Member Data Documentation
info_obj
const Type_info Equation_base::info_obj static
diag_
Matrice_Morse_Diag Equation_base::diag_
nom_
Nom Equation_base::nom_ protected
Referenced by associer_pb_base(), IJK_Interfaces::associer_pb_base(), IJK_Thermals::associer_pb_base(), Navier_Stokes_FTD_IJK::associer_pb_base(), le_nom(), lire_motcle_non_standard(), nommer(), and printOn().
solveur_masse
TRUST_Deriv< Solveur_Masse_base > Equation_base::solveur_masse protected
Referenced by Convection_Diffusion_Espece_Multi_QC::assembler(), Navier_Stokes_FT_Disc::calculer_delta_u_interface(), Navier_Stokes_FT_Disc::calculer_div_normale_interface(), completer(), QDM_Multiphase::completer(), Navier_Stokes_std::corriger_derivee_impl(), Transport_K_Eps_ALE::corriger_derivee_impl_ALE(), derivee_en_temps_inco(), Convection_Diffusion_Temperature_FT_Disc::derivee_en_temps_inco(), Navier_Stokes_phase_field::derivee_en_temps_inco(), Convection_Diffusion_Espece_Multi_QC::derivee_en_temps_inco(), Navier_Stokes_FT_Disc::derivee_en_temps_inco(), discretiser(), initTimeStep(), Conduction::lire_motcle_non_standard(), Navier_Stokes_std::mettre_a_jour(), preparer_calcul(), Navier_Stokes_FT_Disc::preparer_calcul(), Navier_Stokes_IBM::preparer_calcul(), Navier_Stokes_std::preparer_calcul(), printOn(), Navier_Stokes_std::projeter(), Convection_Diffusion_Temperature_FT_Disc::readOn(), Convection_Diffusion_Temperature::readOn(), Navier_Stokes_std_ALE::renewing_jacobians(), resetTime(), and solv_masse().
les_sources
Sources Equation_base::les_sources protected
Referenced by Convection_Diffusion_Espece_Multi_QC::assembler(), assembler_blocs(), Convection_Diffusion_Temperature::assembler_blocs(), associer_pb_base(), completer(), Transport_Marqueur_FT::completer(), Transport_K_Eps_Bas_Reynolds::completer(), Transport_K_Eps_Realisable::completer(), Transport_Fluctuation_Temperature::completer(), Transport_Flux_Chaleur_Turbulente::completer(), Navier_Stokes_QC::completer(), Navier_Stokes_WC::completer(), Navier_Stokes_std::completer(), QDM_Multiphase::completer(), Navier_Stokes_Turbulent_QC::completer(), creer_champ(), derivee_en_temps_inco(), Navier_Stokes_phase_field::derivee_en_temps_inco(), Convection_Diffusion_Espece_Multi_QC::derivee_en_temps_inco(), Navier_Stokes_std::derivee_en_temps_inco(), Navier_Stokes_FT_Disc::derivee_en_temps_inco(), dimensionner_blocs(), dimensionner_matrice_sans_mem(), get_champ(), get_noms_champs_postraitables(), has_champ(), has_interface_blocs(), impr(), Transport_Marqueur_FT::initTimeStep(), Convection_Diffusion_Chaleur_QC::lire_motcle_non_standard(), Convection_Diffusion_Chaleur_WC::lire_motcle_non_standard(), lire_sources(), mettre_a_jour(), preparer_calcul(), printOn(), Transport_Marqueur_FT::readOn(), Navier_Stokes_phase_field::readOn(), Transport_K_Eps::readOn(), Transport_K_KEps::readOn(), Transport_K_Omega::readOn(), Transport_K_ou_Eps::readOn(), Transport_K_ou_Eps_Realisable::readOn(), Transport_Fluctuation_Temperature::readOn(), Transport_Fluctuation_Temperature_W::readOn(), Transport_Fluctuation_Temperature_W_Bas_Re::readOn(), Transport_Flux_Chaleur_Turbulente::readOn(), resetTime(), sources(), and updateGivenFields().
le_schema_en_temps
TRUST_Ref< Schema_Temps_base *> Equation_base::le_schema_en_temps protected
Referenced by associer_sch_tps_base(), Transport_Interfaces_FT_Disc::calcul_vitesse(), calculer_pas_de_temps(), Navier_Stokes_phase_field::calculer_pas_de_temps(), derivee_en_temps_conv(), Navier_Stokes_phase_field::derivee_en_temps_inco(), Convection_Diffusion_Temperature::ecrire_fichier_pena_th(), equation_non_resolue(), Transport_Interfaces_FT_Disc::get_expression_vitesse_imposee(), Navier_Stokes_std::impr(), Navier_Stokes_std::initTimeStep(), limpr(), Navier_Stokes_IBM::preparer_calcul(), Navier_Stokes_std::preparer_calcul(), Navier_Stokes_std::projection_a_faire(), Navier_Stokes_std::projeter(), schema_temps(), and Navier_Stokes_FTD_IJK::schema_temps_ijk().
le_dom_dis
TRUST_Ref< Domaine_dis_base *> Equation_base::le_dom_dis protected
Referenced by associer_domaine_dis(), Transport_Marqueur_FT::completer(), Transport_Marqueur_FT::construction_ensemble_proprietes(), Navier_Stokes_phase_field::derivee_en_temps_inco(), Navier_Stokes_FT_Disc::derivee_en_temps_inco(), and domaine_dis().
le_dom_Cl_dis
TRUST_Deriv< Domaine_Cl_dis_base > Equation_base::le_dom_Cl_dis protected
Referenced by completer(), Eq_rayo_semi_transp_VDF::completer(), Eq_rayo_semi_transp_VEF::completer(), Transport_Fluctuation_Temperature::completer(), Transport_Flux_Chaleur_Turbulente::completer(), Navier_Stokes_std::completer(), discretiser(), Transport_Interfaces_FT_Disc::discretiser(), domaine_Cl_dis(), lire_cl(), preparer_calcul(), Transport_Interfaces_FT_Disc::preparer_calcul(), Navier_Stokes_IBM::preparer_calcul(), Navier_Stokes_std::preparer_calcul(), printOn(), resetTime(), verif_Cl(), and Transport_Interfaces_FT_Disc::verif_Cl().
mon_probleme
TRUST_Ref< Probleme_base *> Equation_base::mon_probleme protected
Referenced by associer_pb_base(), IJK_Interfaces::associer_pb_base(), IJK_Thermals::associer_pb_base(), Navier_Stokes_FTD_IJK::associer_pb_base(), Navier_Stokes_phase_field::calculer_mu(), Navier_Stokes_phase_field::calculer_rho(), completer(), discretisation(), equation_non_resolue(), Convection_Diffusion_Concentration_FT_Disc::lire_motcle_non_standard(), Convection_Diffusion_Concentration_Turbulent_FT_Disc::lire_motcle_non_standard(), Convection_Diffusion_Concentration_FT_Disc::mettre_a_jour_chimie(), Convection_Diffusion_Concentration_Turbulent_FT_Disc::mettre_a_jour_chimie(), probleme(), IJK_Interfaces::probleme_ijk(), and Navier_Stokes_FTD_IJK::probleme_ijk().
dt_op_bak
DoubleList Equation_base::dt_op_bak mutable protected
Referenced by calculer_pas_de_temps(), and preparer_calcul().
sys_invariant_
int Equation_base::sys_invariant_ protected
Referenced by completer(), derivee_en_temps_inco(), Navier_Stokes_std::derivee_en_temps_inco(), and Equation_base().
implicite_
int Equation_base::implicite_ protected
Referenced by completer(), derivee_en_temps_inco(), Navier_Stokes_std::derivee_en_temps_inco(), and Equation_base().
has_time_factor_
bool Equation_base::has_time_factor_ protected
Referenced by derivee_en_temps_inco(), Convection_Diffusion_Temperature::derivee_en_temps_inco(), and Equation_base().
parametre_equation_
TRUST_Deriv< Parametre_equation_base > Equation_base::parametre_equation_ protected
Referenced by derivee_en_temps_inco(), Convection_Diffusion_Temperature_FT_Disc::derivee_en_temps_inco(), Navier_Stokes_FT_Disc::derivee_en_temps_inco(), parametre_equation(), and set_param().
liste_modeles_
TRUST_List< RefObjU > Equation_base::liste_modeles_ protected
Referenced by Transport_K_Eps::associer_modele_turbulence(), Transport_K_Eps_Bas_Reynolds::associer_modele_turbulence(), Transport_K_Eps_Realisable::associer_modele_turbulence(), Transport_K_KEps::associer_modele_turbulence(), Transport_K_Omega::associer_modele_turbulence(), Transport_K_ou_Eps::associer_modele_turbulence(), Transport_K_ou_Eps_Realisable::associer_modele_turbulence(), completer(), get_modele(), Navier_Stokes_Turbulent_ALE::get_modele(), Convection_Diffusion_Temperature_IBM_Turbulent::get_modele(), Navier_Stokes_IBM_Turbulent::get_modele(), Convection_Diffusion_Chaleur_Turbulent_QC::get_modele(), Convection_Diffusion_Concentration_Turbulent::get_modele(), Convection_Diffusion_Espece_Binaire_Turbulent_QC::get_modele(), Convection_Diffusion_Espece_Multi_Turbulent_QC::get_modele(), Convection_Diffusion_Temperature_Turbulent::get_modele(), Navier_Stokes_Turbulent::get_modele(), Navier_Stokes_Turbulent_ALE::lire_motcle_non_standard(), Convection_Diffusion_Temperature_IBM_Turbulent::lire_motcle_non_standard(), Convection_Diffusion_Chaleur_Turbulent_QC::lire_motcle_non_standard(), Convection_Diffusion_Concentration_Turbulent::lire_motcle_non_standard(), Convection_Diffusion_Espece_Binaire_Turbulent_QC::lire_motcle_non_standard(), Convection_Diffusion_Espece_Multi_Turbulent_QC::lire_motcle_non_standard(), and Convection_Diffusion_Temperature_Turbulent::lire_motcle_non_standard().
champs_compris_
Champs_compris Equation_base::champs_compris_ protected
Referenced by add_champs_compris(), Transport_Marqueur_FT::creer_champ(), Navier_Stokes_phase_field::creer_champ(), Navier_Stokes_Aposteriori::creer_champ(), creer_champ(), Convection_Diffusion_Temperature::creer_champ(), Convection_Diffusion_Temperature_base::creer_champ(), Navier_Stokes_std::creer_champ(), QDM_Multiphase::creer_champ(), Conduction::creer_champ(), discretiser(), Navier_Stokes_std_ALE::discretiser(), Echelle_temporelle_turbulente::discretiser(), Energie_cinetique_turbulente::discretiser(), Energie_cinetique_turbulente_WIT::discretiser(), Taux_dissipation_turbulent::discretiser(), Convection_Diffusion_Temperature_FT_Disc::discretiser(), Navier_Stokes_FT_Disc::discretiser(), Transport_Interfaces_FT_Disc::discretiser(), Convection_Diffusion_Phase_field::discretiser(), Equation_rayonnement_base::discretiser(), Transport_K_Eps_base::discretiser(), Transport_K_Omega_base::discretiser(), Transport_K_ou_Eps_base::discretiser(), Transport_Fluctuation_Temperature::discretiser(), Transport_Fluctuation_Temperature_W::discretiser(), Transport_Flux_Chaleur_Turbulente::discretiser(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::discretiser(), Convection_Diffusion_Concentration::discretiser(), Convection_Diffusion_Temperature::discretiser(), Navier_Stokes_std::discretiser(), Aire_interfaciale::discretiser(), Energie_Multiphase::discretiser(), Energie_Multiphase_Enthalpie::discretiser(), Masse_Multiphase::discretiser(), Conduction::discretiser(), Navier_Stokes_std::discretiser_grad_p(), Transport_Marqueur_FT::get_champ(), Navier_Stokes_Aposteriori::get_champ(), Transport_K_ou_Eps_base::get_champ(), get_champ(), Convection_Diffusion_Temperature::get_champ(), Convection_Diffusion_Temperature_base::get_champ(), Navier_Stokes_std::get_champ(), Conduction::get_champ(), Convection_Diffusion_Concentration::get_champ_compris(), Transport_Marqueur_FT::get_noms_champs_postraitables(), Navier_Stokes_Aposteriori::get_noms_champs_postraitables(), get_noms_champs_postraitables(), Convection_Diffusion_Temperature::get_noms_champs_postraitables(), Convection_Diffusion_Temperature_base::get_noms_champs_postraitables(), Navier_Stokes_std::get_noms_champs_postraitables(), Conduction::get_noms_champs_postraitables(), has_champ(), Navier_Stokes_phase_field::lire_motcle_non_standard(), Convection_Diffusion_Concentration::lire_motcle_non_standard(), Navier_Stokes_FT_Disc::preparer_calcul(), Convection_Diffusion_Espece_Binaire_base::readOn(), Convection_Diffusion_Espece_Multi_base::readOn(), and Masse_Multiphase::readOn().
list_champ_combi
Champs_Fonc Equation_base::list_champ_combi protected
Referenced by get_champ(), and has_champ().
matrice_stockee
Matrice_Morse Equation_base::matrice_stockee mutable protected
Referenced by dimensionner_matrice(), and dimensionner_matrice_sans_mem().
matrice_init
int Equation_base::matrice_init mutable protected
Referenced by dimensionner_matrice(), dimensionner_matrice_sans_mem(), and readOn().
champ_conserve_
TRUST_Deriv< Champ_Inc_base > Equation_base::champ_conserve_ mutable protected
Referenced by abortTimeStep(), avancer(), champ_conserve(), champ_convecte(), has_champ_conserve(), has_champ_convecte(), init_champ_conserve(), initTimeStep(), mettre_a_jour_champs_conserves(), reculer(), and resetTime().
champ_convecte_
TRUST_Deriv< Champ_Inc_base > Equation_base::champ_convecte_ mutable protected
Referenced by abortTimeStep(), avancer(), Energie_Multiphase::champ_convecte(), Energie_Multiphase::has_champ_convecte(), Energie_Multiphase::init_champ_convecte(), initTimeStep(), mettre_a_jour_champs_conserves(), reculer(), and resetTime().
derivee_en_temps_
TRUST_Deriv< Champ_Inc_base > Equation_base::derivee_en_temps_ protected
Referenced by derivee_en_temps(), discretiser(), and Transport_Interfaces_FT_Disc::discretiser().
calculate_time_derivative_
int Equation_base::calculate_time_derivative_ protected
Referenced by calculate_time_derivative(), and set_calculate_time_derivative().
diffusion_multi_scalaire_
bool Equation_base::diffusion_multi_scalaire_ = false protected
Referenced by diffusion_multi_scalaire(), Convection_Diffusion_Concentration::lire_motcle_non_standard(), and set_diffusion_multi_scalaire().