TrioCFD: Champ_implementation_sommet Class Reference
Champ_implementation_sommet Class Reference abstract
#include <Champ_implementation_sommet.h>
Detailed Description
Decrire ici la classe Champ_implementation_sommet
Constructor & Destructor Documentation
~Champ_implementation_sommet()
Champ_implementation_sommet::~Champ_implementation_sommet () inline override
Member Function Documentation
valeur_a_elem()
DoubleVect & Champ_implementation_sommet::valeur_a_elem (const DoubleVect & position, DoubleVect & result, int poly) const override virtual
Implements Champ_implementation.
Reimplemented in Champ_Inc_P1_base, and Champ_Inc_Q1_base.
References Objet_U::dimension, Champ_implementation::le_champ(), Field_base::nb_comp(), TRUSTVect< _TYPE_, _SIZE_ >::size(), Champ_Proto::valeurs(), and value_interpolation().
Referenced by Champ_Fonc_P1_base::valeur_a_elem(), Champ_Fonc_Q1_base::valeur_a_elem(), Champ_Inc_P1_base::valeur_a_elem(), and Champ_Inc_Q1_base::valeur_a_elem().
valeur_a_elem_compo()
double Champ_implementation_sommet::valeur_a_elem_compo (const DoubleVect & position, int poly, int ncomp) const override virtual
Implements Champ_implementation.
Reimplemented in Champ_Inc_P1_base, and Champ_Inc_Q1_base.
References Objet_U::dimension, Champ_implementation::le_champ(), Field_base::nb_comp(), TRUSTVect< _TYPE_, _SIZE_ >::size(), Champ_Proto::valeurs(), and value_interpolation().
Referenced by Champ_Fonc_P1_base::valeur_a_elem_compo(), Champ_Fonc_Q1_base::valeur_a_elem_compo(), Champ_Inc_P1_base::valeur_a_elem_compo(), and Champ_Inc_Q1_base::valeur_a_elem_compo().
valeur_aux_elems()
DoubleTab & Champ_implementation_sommet::valeur_aux_elems (const DoubleTab & positions, const IntVect & polys, DoubleTab & result) const override virtual
Implements Champ_implementation.
Reimplemented in Champ_Inc_P1_base, and Champ_Inc_Q1_base.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Champ_implementation::le_champ(), TRUSTVect< _TYPE_, _SIZE_ >::size(), Champ_Proto::valeurs(), and value_interpolation().
Referenced by Champ_Fonc_P1_base::valeur_aux_elems(), Champ_Fonc_Q1_base::valeur_aux_elems(), Champ_Inc_P1_base::valeur_aux_elems(), and Champ_Inc_Q1_base::valeur_aux_elems().
valeur_aux_elems_compo()
DoubleVect & Champ_implementation_sommet::valeur_aux_elems_compo (const DoubleTab & positions, const IntVect & polys, DoubleVect & result, int ncomp) const override virtual
Implements Champ_implementation.
Reimplemented in Champ_Inc_P1_base, and Champ_Inc_Q1_base.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Champ_implementation::le_champ(), Field_base::nb_comp(), TRUSTVect< _TYPE_, _SIZE_ >::size(), Champ_Proto::valeurs(), and value_interpolation().
Referenced by Champ_Fonc_P1_base::valeur_aux_elems_compo(), Champ_Fonc_Q1_base::valeur_aux_elems_compo(), Champ_Inc_P1_base::valeur_aux_elems_compo(), and Champ_Inc_Q1_base::valeur_aux_elems_compo().
valeur_aux_bords()
DoubleTab Champ_implementation_sommet::valeur_aux_bords () const
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Champ_implementation::get_domaine_dis(), Champ_implementation::le_champ(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), and Champ_Proto::valeurs().
Referenced by Champ_Fonc_P1_base::valeur_aux_bords().
remplir_coord_noeuds()
DoubleTab & Champ_implementation_sommet::remplir_coord_noeuds (DoubleTab & positions) const override virtual
Implements Champ_implementation.
Reimplemented in Champ_Inc_P1_base, and Champ_Inc_Q1_base.
References Objet_U::dimension, Champ_implementation::get_domaine_geom(), and TRUSTTab< _TYPE_, _SIZE_ >::resize().
Referenced by Champ_Fonc_P1_base::remplir_coord_noeuds(), Champ_Fonc_Q1_base::remplir_coord_noeuds(), Champ_Inc_P1_base::remplir_coord_noeuds(), and Champ_Inc_Q1_base::remplir_coord_noeuds().
remplir_coord_noeuds_et_polys()
int Champ_implementation_sommet::remplir_coord_noeuds_et_polys (DoubleTab & positions, IntVect & polys) const override virtual
Implements Champ_implementation.
Reimplemented in Champ_Inc_P1_base, and Champ_Inc_Q1_base.
References Objet_U::dimension, Champ_implementation::get_domaine_geom(), and TRUSTTab< _TYPE_, _SIZE_ >::resize().
Referenced by Champ_Fonc_P1_base::remplir_coord_noeuds_et_polys(), Champ_Fonc_Q1_base::remplir_coord_noeuds_et_polys(), Champ_Inc_P1_base::remplir_coord_noeuds_et_polys(), and Champ_Inc_Q1_base::remplir_coord_noeuds_et_polys().
valeur_aux_sommets_impl()
DoubleTab & Champ_implementation_sommet::valeur_aux_sommets_impl (DoubleTab & result) const override protected virtual
Implements Champ_implementation.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Champ_implementation::le_champ(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), and Champ_Proto::valeurs().
valeur_aux_sommets_compo_impl()
DoubleVect & Champ_implementation_sommet::valeur_aux_sommets_compo_impl (DoubleVect & result, int ncomp) const override protected virtual
Implements Champ_implementation.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Champ_implementation::le_champ(), Field_base::nb_comp(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), TRUSTVect< _TYPE_, _SIZE_ >::size(), and Champ_Proto::valeurs().
trace()
DoubleTab & Champ_implementation_sommet::trace (const Frontiere_dis_base & fr, const DoubleTab & y, DoubleTab & x, int distant) const inline protected
References Frontiere_dis_base::frontiere(), Frontiere_32_64< _SIZE_ >::trace_som_distant(), and Frontiere_32_64< _SIZE_ >::trace_som_local().
Referenced by Champ_Inc_P1_base::trace().
value_interpolation()
virtual void Champ_implementation_sommet::value_interpolation (const DoubleTab & positions, const ArrOfInt & cells, const DoubleTab & values, DoubleTab & resu, int ncomp = -1) const protected pure virtual
Implemented in Champ_implementation_P1, and Champ_implementation_Q1.
Referenced by valeur_a_elem(), valeur_a_elem_compo(), valeur_aux_elems(), and valeur_aux_elems_compo().