TrioCFD: OpConvQuickInterfaceIJKScalar_double Class Reference
OpConvQuickInterfaceIJKScalar_double Class Reference
#include <OpConvQuickInterfaceIJKScalar.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
~OpConvQuickInterfaceIJKScalar_double()
OpConvQuickInterfaceIJKScalar_double::~OpConvQuickInterfaceIJKScalar_double ()
OpConvQuickInterfaceIJKScalar_double()
OpConvQuickInterfaceIJKScalar_double::OpConvQuickInterfaceIJKScalar_double () inline
Member Function Documentation
cree_instance()
Objet_U * OpConvQuickInterfaceIJKScalar_double::cree_instance () static
taille_memoire()
unsigned OpConvQuickInterfaceIJKScalar_double::taille_memoire () const override virtual
Reimplemented from OpConvQuickIJKScalar_double.
duplique()
int OpConvQuickInterfaceIJKScalar_double::duplique () const override virtual
Reimplemented from OpConvQuickIJKScalar_double.
info()
const Type_info * OpConvQuickInterfaceIJKScalar_double::info () static
get_info()
const Type_info * OpConvQuickInterfaceIJKScalar_double::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from OpConvQuickIJKScalar_double.
self_cast() [1/2]
OpConvQuickInterfaceIJKScalar_double & OpConvQuickInterfaceIJKScalar_double::self_cast (Objet_U & r) static
self_cast() [2/2]
const OpConvQuickInterfaceIJKScalar_double & OpConvQuickInterfaceIJKScalar_double::self_cast (const Objet_U & r) static
printOn()
Sortie & OpConvQuickInterfaceIJKScalar_double::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from OpConvQuickIJKScalar_double.
References OpConvQuickIJKScalar_double::printOn().
readOn()
Entree & OpConvQuickInterfaceIJKScalar_double::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from OpConvQuickIJKScalar_double.
References OpConvQuickIJKScalar_double::readOn().
correct_flux()
void OpConvQuickInterfaceIJKScalar_double::correct_flux (IJK_Field_local_double *const flux, const int k_layer, const int dir) override protected virtual
Reimplemented from Operateur_IJK_elem_base_double.
References Operateur_IJK_elem_conv_base_double::corrige_flux_, and Corrige_flux_FT_base::corrige_flux_faceIJ().
correct_flux_spherical()
void OpConvQuickInterfaceIJKScalar_double::correct_flux_spherical (Simd_double & a, Simd_double & b, const int & i, const int & j, int k_layer, int dir) override protected virtual
Reimplemented from Operateur_IJK_elem_base_double.
References Corrige_flux_FT_base::correct_flux_spherical(), and Operateur_IJK_elem_conv_base_double::corrige_flux_.
Member Data Documentation
info_obj
const Type_info OpConvQuickInterfaceIJKScalar_double::info_obj static