TrioCFD: Op_Diff_Turbulent_PolyMAC_P0_Elem Class Reference
Op_Diff_Turbulent_PolyMAC_P0_Elem Class Reference
#include <Op_Diff_Turbulent_PolyMAC_P0_Elem.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Op_Diff_PolyMAC_P0_Elem
double calculer_dt_stab () const override
void completer () override
const Type_info * get_info () const override
void mettre_a_jour (double t) override
void modifier_pour_Cl (Matrice_Morse &la_matrice, DoubleTab &secmem) const override
void completer () override
const Type_info * get_info () const override
void mettre_a_jour (double t) override
Public Member Functions inherited from Op_Diff_PolyMAC_Gen_base
const Type_info * get_info () const override
int impr (Sortie &os) const override
Public Member Functions inherited from Operateur_Diff_base
virtual void associer_diffusivite_pour_pas_de_temps (const Champ_base &)
const Type_info * get_info () const override
Public Member Functions inherited from Operateur_base
void associer_eqn (const Equation_base &)
virtual double calculer_dt_stab () const
virtual void completer ()
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual void mettre_a_jour (double temps)
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Protected Member Functions
void completer () override
void mettre_a_jour (double temps) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Operateur_Diff_base
virtual const Champ_base & diffusivite_pour_pas_de_temps () const
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
Version de Op_Diff_PolyMAC_P0_Elem prenant en compte l'effet de la turbulence par le biais d'une correlation de type Transport_turbulent. (celle-ci reposera sur la modelisation de la viscosite turbulente fournie par la correlation Viscosite_turbulente de l'operateur de diffusion de la QDM)
Constructor & Destructor Documentation
Op_Diff_Turbulent_PolyMAC_P0_Elem()
Op_Diff_Turbulent_PolyMAC_P0_Elem::Op_Diff_Turbulent_PolyMAC_P0_Elem ()
~Op_Diff_Turbulent_PolyMAC_P0_Elem()
Op_Diff_Turbulent_PolyMAC_P0_Elem::~Op_Diff_Turbulent_PolyMAC_P0_Elem ()
Member Function Documentation
cree_instance()
Objet_U * Op_Diff_Turbulent_PolyMAC_P0_Elem::cree_instance () static
taille_memoire()
unsigned Op_Diff_Turbulent_PolyMAC_P0_Elem::taille_memoire () const override virtual
Reimplemented from Op_Diff_PolyMAC_P0_Elem.
duplique()
int Op_Diff_Turbulent_PolyMAC_P0_Elem::duplique () const override virtual
Reimplemented from Op_Diff_PolyMAC_P0_Elem.
info()
const Type_info * Op_Diff_Turbulent_PolyMAC_P0_Elem::info () static
get_info()
const Type_info * Op_Diff_Turbulent_PolyMAC_P0_Elem::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Op_Diff_PolyMAC_P0_Elem.
self_cast() [1/2]
Op_Diff_Turbulent_PolyMAC_P0_Elem & Op_Diff_Turbulent_PolyMAC_P0_Elem::self_cast (Objet_U & r) static
self_cast() [2/2]
const Op_Diff_Turbulent_PolyMAC_P0_Elem & Op_Diff_Turbulent_PolyMAC_P0_Elem::self_cast (const Objet_U & r) static
printOn()
Sortie & Op_Diff_Turbulent_PolyMAC_P0_Elem::printOn (Sortie & os) const override protected virtual
DOES NOTHING - to override in derived classes.
Imprime l'operateur sur un flot de sortie.
Parameters
(Sortie& os) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Op_Diff_PolyMAC_P0_Elem.
References Op_Diff_PolyMAC_P0_base::printOn().
readOn()
Entree & Op_Diff_Turbulent_PolyMAC_P0_Elem::readOn (Entree & is) override protected virtual
DOES NOTHING - to override in derived classes.
Lit un operateur sur un flot d'entree.
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Op_Diff_PolyMAC_P0_Elem.
References Op_Dift_Multiphase_proto::ajout_champs_proto_elem(), Op_Dift_Multiphase_proto::associer_proto(), Operateur_base::champs_compris_, Op_Dift_Multiphase_proto::corr_, MorEqn::equation(), and Correlation_base::typer_lire_correlation().
dimension_min_nu()
int Op_Diff_Turbulent_PolyMAC_P0_Elem::dimension_min_nu () const inline override protected virtual
Reimplemented from Op_Diff_PolyMAC_Gen_base.
References Op_Dift_Multiphase_proto::corr_, and TRUST_Deriv< _CLASSE_ >::valeur().
get_noms_champs_postraitables()
void Op_Diff_Turbulent_PolyMAC_P0_Elem::get_noms_champs_postraitables (Noms & nom, Option opt = NONE) const override protected virtual
Reimplemented from Operateur_base.
References Operateur_base::get_noms_champs_postraitables(), Op_Dift_Multiphase_proto::get_noms_champs_postraitables_proto(), and Objet_U::que_suis_je().
completer()
void Op_Diff_Turbulent_PolyMAC_P0_Elem::completer () override protected virtual
Associe l'operateur au domaine_dis, le domaine_Cl_dis, et a l'inconnue de son equation.
Exceptions
pas d'equation associee
Reimplemented from Op_Diff_PolyMAC_P0_Elem.
References Op_Diff_PolyMAC_P0_Elem::completer(), Op_Dift_Multiphase_proto::completer_proto_elem(), and Op_Diff_PolyMAC_Gen_base::nu_constant_.
modifier_mu()
void Op_Diff_Turbulent_PolyMAC_P0_Elem::modifier_mu (DoubleTab & mu) const override protected virtual
Reimplemented from Op_Diff_PolyMAC_Gen_base.
References Op_Dift_Multiphase_proto::corr_, TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), MorEqn::equation(), Probleme_base::equation(), Objet_U_ptr::est_nul(), Process::exit(), Operateur::l_op_base(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Op_Dift_Multiphase_proto::nu_ou_lambda_turb_, Equation_base::operateur(), Equation_base::probleme(), Objet_U::que_suis_je(), and TRUST_Deriv< _CLASSE_ >::valeur().
creer_champ()
void Op_Diff_Turbulent_PolyMAC_P0_Elem::creer_champ (const Motcle & motlu) override protected virtual
Reimplemented from Operateur_base.
References Operateur_base::creer_champ(), and Op_Dift_Multiphase_proto::creer_champ_proto_elem().
mettre_a_jour()
void Op_Diff_Turbulent_PolyMAC_P0_Elem::mettre_a_jour (double temps) override protected virtual
DOES NOTHING - to override in derived classes.
Mise a jour de l'operateur
Parameters
(double) un pas de temps
Reimplemented from Op_Diff_PolyMAC_P0_Elem.
References Op_Diff_PolyMAC_P0_Elem::mettre_a_jour(), and Op_Dift_Multiphase_proto::mettre_a_jour_proto_elem().
is_turb()
bool Op_Diff_Turbulent_PolyMAC_P0_Elem::is_turb () const inline override protected virtual
Reimplemented from Operateur_Diff_base.
correlation_viscosite_turbulente()
const Correlation_base * Op_Diff_Turbulent_PolyMAC_P0_Elem::correlation_viscosite_turbulente () const inline override protected virtual
Reimplemented from Operateur_Diff_base.
References Op_Dift_Multiphase_proto::corr_, and TRUST_Deriv< _CLASSE_ >::valeur().
Member Data Documentation
info_obj
const Type_info Op_Diff_Turbulent_PolyMAC_P0_Elem::info_obj static