TrioCFD: Domaine_Cl_dis_base Class Reference
Domaine_Cl_dis_base Class Reference abstract
#include <Domaine_Cl_dis_base.h>
Public Member Functions
virtual int calculer_coeffs_echange (double temps)
const Cond_lim_base & condition_limite_de_la_face_reelle (int face_globale, int &face_locale) const
const Cond_lim_base & condition_limite_de_la_face_virtuelle (int face_globale, int &face_locale) const
Cond_lim_base & condition_limite_de_la_frontiere (Nom frontiere)
const Cond_lim_base & condition_limite_de_la_frontiere (Nom frontiere) const
int contient_Cl (const Nom &)
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual const Cond_lim & la_cl_de_la_face (int num_face) const
const Nom & le_nom () const override
Conds_lim & les_conditions_limites ()
const Conds_lim & les_conditions_limites () const
Cond_lim & les_conditions_limites (int)
const Cond_lim & les_conditions_limites (int) const
virtual void mettre_a_jour (double temps)
virtual void mettre_a_jour_ss_pas_dt (double temps)
int nb_cond_lim () const
void nommer (const Nom &nom) override
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
discretisees. Domaine_Cl_dis_base est un morceau d'equation donc elle
herite de MorEqn, c'est grace a cet heritage que chaque objet
Domaine_Cl_dis_base contient une reference vers l'equation a laquelle il
se rapporte. Les conditions aux limites discretisees representent les
conditions aux limites du domaine discretisee associee a l'equation
reference par Domaine_Cl_dis_base.
Domaine_Cl_dis_base a un membre representant les conditions aux limites.
See also
MorEqn Conds_lim Cond_lim_base, Classe abstraite., Methodes abstraites:, void completer(const Domaine_dis_base&), void imposer_cond_lim(Champ_Inc_base&)
Constructor & Destructor Documentation
Domaine_Cl_dis_base()
Domaine_Cl_dis_base::Domaine_Cl_dis_base ()
~Domaine_Cl_dis_base()
Domaine_Cl_dis_base::~Domaine_Cl_dis_base () override
Member Function Documentation
info()
const Type_info * Domaine_Cl_dis_base::info () static
get_info()
const Type_info * Domaine_Cl_dis_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
Reimplemented in Domaine_Cl_PolyMAC, Domaine_Cl_VDF, and Domaine_Cl_VEF.
self_cast() [1/2]
Domaine_Cl_dis_base & Domaine_Cl_dis_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Domaine_Cl_dis_base & Domaine_Cl_dis_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Domaine_Cl_dis_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
Reimplemented in Domaine_Cl_PolyMAC, Domaine_Cl_VDF, and Domaine_Cl_VEF.
Referenced by Domaine_Cl_VDF::printOn().
readOn()
Entree & Domaine_Cl_dis_base::readOn (Entree & is) override protected virtual
Surcharge Objet_U::readOn(Sortie&) Lit les conditions aux limites discretisees a partir d'un flot d'entree.
Le format attendu est le suivant: { Nom Cond_lim [REPETER LECTURE AUTANT DE FOIS QUE NECESSAIRE] }
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Exceptions
accolade ouvrante attendue
nombre de conditions aux limites lues invalide
Reimplemented from Objet_U.
Reimplemented in Domaine_Cl_PolyMAC, Domaine_Cl_VDF, and Domaine_Cl_VEF.
References TRUST_Vector< _CLASSE_ >::dimensionner(), Domaine_dis_base::domaine(), domaine_dis(), Equation_base::domaine_dis(), Domaine_dis_base::ecrire_noms_bords(), MorEqn::equation(), Process::exit(), Domaine_32_64< _SIZE_ >::frontiere(), Process::is_sequential(), Process::Journal(), Cond_lim_utilisateur_base::la_cl(), Probleme_U::le_nom(), les_conditions_limites(), Cond_lim_utilisateur_base::lire(), MorEqn::mon_equation, Domaine_32_64< _SIZE_ >::nb_front_Cl(), TRUST_Ref< _CLASSE_ >::non_nul(), Equation_base::probleme(), Objet_U::que_suis_je(), and Domaine_32_64< _SIZE_ >::rang_frontiere().
Referenced by Domaine_Cl_DG::readOn(), Domaine_Cl_EF::readOn(), Domaine_Cl_PolyMAC::readOn(), Domaine_Cl_VDF::readOn(), and Domaine_Cl_VEF::readOn().
nommer()
void Domaine_Cl_dis_base::nommer (const Nom &) override virtual
Donne un nom a l'Objet_U Methode virtuelle a surcharger.
Parameters
(const Nom&) le nom a affectuer a l'Objet_U
Reimplemented from Objet_U.
References nom_.
les_conditions_limites() [1/4]
const Cond_lim & Domaine_Cl_dis_base::les_conditions_limites (int i) const
Renvoie la i-ieme condition aux limites.
(version const)
Parameters
(int i) le rang de la i-ieme condition aux limites
Returns
(Cond_lim&) la i-ieme condition aux limites
References les_conditions_limites_.
Referenced by Operateur_Conv_sensibility_VEF::add_diffusion_scalar_term(), Operateur_Conv_sensibility_VEF::add_diffusion_term(), Op_Grad_PolyMAC_Face::ajouter(), Op_Conv_Amont_old_VEF_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Centre_EF_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_EF_VEF_P1NC::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Conv_Vort_VEF_Face::ajouter(), Op_Diff_VEF_Face_Q1::ajouter(), Op_Dift_VEF_Face_Q1::ajouter(), Op_Div_VEFP1B_Elem::ajouter(), Source_Reaction_Particules_VDF::ajouter(), Source_Reaction_Particules_VEF::ajouter(), SourceFiltree_FT_disc_VEF_P1NC::ajouter(), Terme_Boussinesq_Sensibility_VEFPreP1B_Face::ajouter(), Source_Transport_Flux_Chaleur_Turbulente_VDF_Face::ajouter(), Source_Robin::ajouter(), Source_Robin_Scalaire::ajouter(), Source_Generique_Face_PolyMAC::ajouter(), Terme_Source_Qdm_Face_PolyMAC::ajouter(), Terme_Boussinesq_VEFPreP1B_Face::ajouter(), Terme_Source_Acceleration_VEF_Face::ajouter(), Terme_Source_Qdm_VEF_Face::ajouter(), Op_Grad_VEF_P1B_Face::ajouter_aretes(), Tenseur_Reynolds_Externe_VDF_Face::ajouter_blocs(), Source_Transport_K_KEps_VDF_Elem::ajouter_blocs(), Op_Grad_P0_to_Face::ajouter_blocs(), Op_Grad_VDF_Face::ajouter_blocs(), Terme_Source_Canal_perio_VDF_Face::ajouter_blocs(), Force_Centrifuge_VDF_Face_Axi::ajouter_blocs(), Terme_Boussinesq_VDF_Face::ajouter_blocs(), Terme_Source_Acceleration_VDF_Face::ajouter_blocs(), Terme_Source_Coriolis_VDF_Face::ajouter_blocs(), Terme_Source_inc_th_VDF_Face::ajouter_blocs(), Terme_Source_inc_VDF_Face::ajouter_blocs(), Terme_Source_Qdm_VDF_Face::ajouter_blocs(), Flux_2groupes_PolyMAC_P0::ajouter_blocs(), Injection_QDM_nulle_PolyMAC_P0::ajouter_blocs(), Injection_QDM_nulle_VDF::ajouter_blocs(), Diffusion_croisee_echelle_temp_taux_diss_turb_PolyMAC_P0::ajouter_blocs(), Diffusion_supplementaire_echelle_temp_turb_PolyMAC_P0::ajouter_blocs(), Diffusion_supplementaire_echelle_temp_turb_VDF::ajouter_blocs(), Dispersion_bulles_PolyMAC_P0::ajouter_blocs(), Op_Diff_PolyMAC_P0_Elem::ajouter_blocs(), Op_Conv_Amont_VPoly_VDF_Face::ajouter_blocs(), Op_Diff_PolyMAC_P0P1NC_Face::ajouter_blocs_ext(), Op_Grad_EF::ajouter_bord(), Op_Diff_EF::ajouter_bords(), Op_Dift_EF_Q1::ajouter_bords(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Face::ajouter_cas_vectoriel(), Op_Conv_Amont_old_VEF_Face::ajouter_contribution(), Op_Conv_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution(), Op_Diff_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Face_Q1::ajouter_contribution(), Op_Diff_VEF_Face_Stab::ajouter_contribution(), Op_Conv_RT_VEF_Face::ajouter_contribution(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution_elem(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face_Stab::ajouter_contribution_multi_scalaire(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution_som(), Op_Diff_EF::ajouter_contributions_bords(), Op_Dift_EF_Q1::ajouter_contributions_bords(), Operateur_Conv_sensibility_VEF::ajouter_conv_term(), Op_Grad_VEF_P1B_Face::ajouter_elem(), Operateur_Conv_sensibility_VEF::ajouter_Lsensibility_state_Amont(), Operateur_Conv_sensibility_VEF::ajouter_Lstate_sensibility_Amont(), Op_Grad_VEF_P1B_Face::ajouter_som(), Op_Div_VEFP1B_Elem::ajouter_som(), Op_Conv_ALE_VEF::ajouterALE(), Tensors_Computation_VEF::antisym_loop_edge_faces(), Solveur_Masse_EF::appliquer_impl(), Masse_VEF_P1NC::appliquer_impl(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_avec_inertie_impl(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_blocs_avec_inertie(), Assembleur_P_EF::assembler_mat(), Op_Diff_VEFP1NCP1B_Face::associer(), Champ_front_contact_VEF::associer_front_vf_et_ch_front_autre_pb(), BilanQdmVEF::bilan_energie(), BilanQdmVEF::bilan_qdm(), Champ_Elem_PolyMAC_P0::calc_grad(), Op_Evanescence_Homogene_PolyMAC_P0_Face::calc_grad_alpha_elem(), Op_Evanescence_Homogene_PolyMAC_P0_Face::calc_grad_alpha_faces(), grad_Champ_Face_PolyMAC_P0::calc_gradfve(), Traitement_particulier_NS_chmoy_faceperio_VEF::calcul_chmoy_faceperio(), Modele_Jones_Launder_VDF::Calcul_D(), Modele_Jones_Launder_Thermique_VDF::Calcul_D(), Modele_Jones_Launder_VDF::Calcul_D_BiK(), Champ_P1NC::calcul_duidxj_paroi(), Modele_Jones_Launder_VDF::Calcul_E(), Modele_Jones_Launder_Thermique_VDF::Calcul_E(), Traitement_particulier_NS_THI_VEF::calcul_Ec_spatial(), Modele_EASM_Baglietto_VEF::Calcul_F1(), Modele_EASM_Baglietto_VEF::Calcul_F1_BiK(), Modele_EASM_Baglietto_VEF::Calcul_Fmu(), Modele_EASM_Baglietto_VEF::Calcul_Fmu_BiK(), Champ_P1NC::calcul_h_conv(), Traitement_particulier_NS_THI_VEF::calcul_moyenne(), Traitement_particulier_NS_canal::calcul_reynolds_tau(), Traitement_particulier_NS_THI_VDF::calcul_skewness_ordre_2(), Traitement_particulier_NS_temperature_VEF::calcul_temperature(), Modele_Lam_Bremhorst_VEF::calcul_tenseur_face(), Modele_Shih_Zhu_Lumley_VEF::calcul_tenseur_face(), Calcul_Production_K_VEF::calcul_tenseur_face(), Traitement_particulier_NS_THI_VEF::calcul_vitesse_moyenne(), Champ_Q1_EF::calcul_y_plus(), Champ_P1NC::calcul_y_plus(), Champ_Face_VDF::calcul_y_plus(), Champ_P1NC::calcul_y_plus_diphasique(), Champ_Face_VDF::calcul_y_plus_diphasique(), Op_Conv_ALE_VEF::calculateALEMeshVelocityGradientOnFaces(), Terme_Source_Canal_perio_VDF_Face::calculer_debit(), Terme_Source_Canal_perio_VEF_P1NC::calculer_debit(), Op_Dift_VEF_P1NCP1B_Face::calculer_divergence_som(), Op_Diff_VEFP1NCP1B_Face::calculer_divergence_som(), Op_Conv_VDF_base::calculer_dt_local(), Op_Conv_VEF_base::calculer_dt_local(), Op_Conv_ALE_VEF::calculer_dt_stab(), Operateur_Conv_sensibility_VEF::calculer_dt_stab(), Op_Diff_DG_base::calculer_dt_stab(), Op_Conv_PolyMAC_iterateur_base::calculer_dt_stab(), Op_Diff_PolyMAC_base::calculer_dt_stab(), Op_Conv_VDF_base::calculer_dt_stab(), Op_Conv_Muscl_New_VEF_Face::calculer_dt_stab(), Op_Conv_VEF_base::calculer_dt_stab(), Op_Diff_VEF_base::calculer_dt_stab(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab_elem(), Op_Grad_EF::calculer_flux_bords(), Op_Grad_VDF_Face::calculer_flux_bords(), Op_Diff_VEFP1NCP1B_Face::calculer_flux_bords_elem(), Op_Diff_VEFP1NCP1B_Face::calculer_flux_bords_som(), Modele_rayo_semi_transp::calculer_flux_radiatif(), Flux_radiatif_VDF::calculer_flux_radiatif(), Flux_radiatif_VEF::calculer_flux_radiatif(), Modele_turbulence_hyd_LES_VDF::calculer_fonction_structure(), Modele_turbulence_hyd_LES_VEF::calculer_fonction_structure(), Modele_turbulence_hyd_LES_axi_VDF::calculer_fonction_structure(), Navier_Stokes_FT_Disc::calculer_gradient_indicatrice(), Op_Dift_VEF_P1NCP1B_Face::calculer_gradient_som(), Op_Diff_VEFP1NCP1B_Face::calculer_gradient_som(), LoiParoiHybride::calculer_hyd(), LoiParoiHybride::calculer_hyd_BiK(), Op_Diff_VEF_Face_Stab::calculer_max(), Op_Diff_VEF_Face_Stab::calculer_min(), Operateur_base::calculer_pour_post(), Op_Conv_PolyMAC_iterateur_base::calculer_pour_post(), Op_Conv_VDF_base::calculer_pour_post(), Op_Conv_VEF_base::calculer_pour_post(), Source_Transport_Fluctuation_Temperature_VDF_Elem::calculer_Prod_uteta_T(), Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::calculer_Prod_uteta_T(), Source_Transport_Fluctuation_Temperature_W_VDF_Elem::calculer_Prod_uteta_T(), Paroi_ODVM_scal_VDF::calculer_scal(), Paroi_TBLE_scal_VDF::calculer_scal(), Calcul_Production_K_VEF::calculer_terme_production_K(), Calcul_Production_K_VEF::calculer_terme_production_K_BiK(), Calcul_Production_K_VEF::calculer_terme_production_K_EASM(), Calcul_Production_K_VDF::calculer_u_conc(), Calcul_Production_K_VDF::calculer_u_teta(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_W_VDF_Elem::calculer_u_teta_W(), Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::calculer_u_teta_W(), Source_Transport_Fluctuation_Temperature_W_VDF_Elem::calculer_u_teta_W(), Champ_base::calculer_valeurs_som_compo_post(), Champ_base::calculer_valeurs_som_post(), Modele_turbulence_hyd_LES_VEF::calculer_viscosite_turbulente(), Domaine_ALE::calculer_vitesse(), Fluide_Dilatable_base::checkTraitementPth(), Triple_Line_Model_FT_Disc::completer(), Pb_Couple_Rayonnement::completer(), Equation_base::completer(), Operateur_base::completer(), Diffusion_croisee_echelle_temp_taux_diss_turb_PolyMAC_P0::completer(), Source_Diffusion_supplementaire_echelle_temp_turb::completer(), Eq_rayo_semi_transp_VDF::completer(), Eq_rayo_semi_transp_VEF::completer(), Op_Diff_PolyMAC_P0_base::completer(), Convection_Diffusion_Espece_Multi_QC::completer(), Terme_Source_Canal_perio::completer(), Op_Diff_VEF_Face_Stab::completer(), Op_Dift_Stab_VEF_Face::completer(), Champ_P1iP1B_implementation::completer(), Terme_Source_Canal_perio::compute_heat_flux(), Paroi_scal_hyd_base_EF::compute_nusselt(), Paroi_scal_hyd_base_VDF::compute_nusselt(), Paroi_scal_hyd_base_VEF::compute_nusselt(), Triple_Line_Model_FT_Disc::compute_TCL_fluxes_in_all_boundary_cells(), Calcul_Production_K_VEF::compute_utheta_nbConsti_gt_1_nbCompo_eq_0(), Calcul_Production_K_VEF::compute_utheta_nbConsti_gt_1_nbCompo_eq_1(), Calcul_Production_K_VEF::compute_utheta_nbConsti_gt_1_nbCompo_gt_1(), Calcul_Production_K_VEF::compute_utheta_nbConsti_le_1_nbCompo_eq_0(), Calcul_Production_K_VEF::compute_utheta_nbConsti_le_1_nbCompo_eq_1(), Calcul_Production_K_VEF::compute_utheta_nbConsti_le_1_nbCompo_gt_1(), Champ_front_fonc_gradient::condition_limite(), Op_Conv_Amont_old_VEF_Face::contribue_au_second_membre(), Op_Conv_VEF_Face::contribue_au_second_membre(), Op_Diff_VEF_Anisotrope_Face::contribue_au_second_membre(), Op_Diff_VEF_Face::contribue_au_second_membre(), Op_Diff_VEF_Face_Q1::contribue_au_second_membre(), Op_Dift_VEF_Face_Q1::contribuer_a_avec(), Op_Grad_PolyMAC_Face::contribuer_a_avec(), Op_Dift_VEF_Face::contribuer_au_second_membre(), Op_Diff_VDF_Elem_base::contribuer_termes_croises(), Navier_Stokes_FT_Disc::correct_at_exit_bad_gradient(), Source_WC_Chaleur::correct_grad_boundary(), Op_Diff_VEFP1NCP1B_Face::corriger_Cl_test(), Op_Diff_VEFP1NCP1B_Face::corriger_div_pour_Cl(), Op_Dift_VEF_P1NCP1B_Face::corriger_div_pour_Cl(), Domaine_VDF::creer_elements_fictifs(), Convection_Diffusion_Fluide_Dilatable_Proto::derivee_en_temps_inco_sans_solveur_masse_impl(), Op_EF_base::dimensionner(), Op_PolyMAC_Elem::dimensionner(), Op_VDF_Face::dimensionner(), Op_Diff_VDF_Elem_base::dimensionner_termes_croises(), Champ_val_tot_sur_vol_VEF::eval_contrib_loc(), Eq_rayo_semi_transp_VDF::evaluer_cl_rayonnement(), Eq_rayo_semi_transp_VEF::evaluer_cl_rayonnement(), Source_PDF_EF::filtre_CLD(), Champ_P1NC_implementation::filtrer_L2(), Champ_P1NC_implementation::filtrer_resu(), Modele_rayo_semi_transp::flux_radiatif(), Paroi_hyd_base_EF::get_champ(), Turbulence_paroi_base::get_champ(), Champ_Generique_Extraction::get_champ(), Champ_Generique_Tparoi_VEF::get_champ(), Op_Grad_VEF_P1B_Face::impr(), Op_EF_base::impr(), Op_VEF_Face::impr(), Op_Grad_EF::impr(), Op_Grad_VDF_Face::impr(), Loi_Paroi_Nu_Impose_VDF::imprimer_nusselt(), Loi_Paroi_Nu_Impose_VEF::imprimer_nusselt(), Paroi_scal_hyd_base_EF::imprimer_nusselt(), Paroi_scal_hyd_base_VDF::imprimer_nusselt(), Paroi_scal_hyd_base_VEF::imprimer_nusselt(), Sonde::init_bords(), Traitement_particulier_NS_chmoy_faceperio_VEF::init_calcul_stats(), Champ_Face_base::init_fcl(), Champ_Elem_PolyMAC_P0::init_grad(), Paroi_ODVM_scal_VDF::init_lois_paroi(), Paroi_TBLE_QDM::init_lois_paroi(), Paroi_TBLE_QDM_Scal::init_lois_paroi(), Couplage_Parietal_PolyMAC_helper::init_op_ext(), Op_Diff_PolyMAC_P0P1NC_Elem::init_op_ext(), Op_Diff_VDF_base::init_op_ext(), Domaine_ALE::initialiser(), Champ_Face_PolyMAC::interp_gve(), Champ_Face_PolyMAC::interp_ve(), Op_Diff_VEFP1NCP1B_Face::isFaceOfSymetry(), SETS::iterer_NS(), Echange_contact_rayo_semi_transp_VDF::la_Cl_opposee(), Domaine_ALE::laplacien(), Op_Diff_VEFP1NCP1B_Face::liste_face(), Domaine_ALE::mettre_a_jour(), Sonde::mettre_a_jour_bords(), Op_Diff_VEF_Face_Stab::modifie_pour_Cl(), Terme_Source_Th_TdivU_VEF_Face::modifier_domaine_cl(), Op_Grad_VEF_P1B_Face::modifier_grad_pour_Cl(), Eq_rayo_semi_transp_VDF::modifier_matrice(), Eq_rayo_semi_transp_VEF::modifier_matrice(), Op_VEF_Face::modifier_matrice_pour_periodique_apres_contribuer(), Op_EF_base::modifier_pour_Cl(), Op_VDF_Face::modifier_pour_Cl(), Op_VEF_Face::modifier_pour_Cl(), Op_Diff_K_Eps_VDF_base::modifier_pour_Cl(), Op_Diff_K_Omega_VDF_base::modifier_pour_Cl(), AssembleurPVDF_PF::modifier_secmem(), Assembleur_P_EF::modifier_secmem(), Assembleur_P_PolyMAC::modifier_secmem(), Assembleur_P_VDF::modifier_secmem(), Assembleur_P_VEF::modifier_secmem(), Assembleur_P_VEFPreP1B::modifier_secmem(), Assembleur_P_VEFPreP1B::modifier_secmem_elem(), Assembleur_P_VEFPreP1B::modifier_secmem_som(), Probleme_base::newCompute(), Operateur_base::ouvrir_fichier(), Modele_rayo_semi_transp::preparer_calcul(), Convection_Diffusion_Espece_Binaire_base::preparer_calcul(), Convection_Diffusion_Espece_Fluide_Dilatable_base::preparer_calcul(), Cond_Lim_rayo_semi_transp::recherche_emissivite_et_A(), Assembleur_P_VEF::remplir(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::remplir_cl_modifiee(), Champ_front_contact_VEF::remplir_faces_coin(), Op_Conv_VEF_Face::remplir_fluent(), Operateur_Conv_sensibility_VEF::remplir_fluent(), Op_Dift_EF_Q1::remplir_marqueur_elem_CL_paroi(), Iterateur_Source_VEF_Face< _TYPE_ >::remplir_volumes_cl_dirichlet(), Paroi_TBLE_QDM::reprendre(), Paroi_TBLE_QDM_Scal::reprendre(), Paroi_TBLE_QDM::sauvegarder(), Paroi_TBLE_QDM_Scal::sauvegarder(), Op_Diff_VEFP1NCP1B_Face::test(), Champ_front_contact_VEF::test_faces_coin(), grad_Champ_Face_PolyMAC_P0::update_tab_grad(), Champ_Face_PolyMAC_P0::update_ve2(), Champ_Inc_base::valeur_aux_bords(), Equation_base::verif_Cl(), Transport_Interfaces_FT_Disc::verif_Cl(), Champ_Face_VDF::verifie_valeurs_cl(), Champ_P1NC::verifie_valeurs_cl(), and Champ_Q1NC::verifie_valeurs_cl().
les_conditions_limites() [2/4]
Cond_lim & Domaine_Cl_dis_base::les_conditions_limites (int i)
Renvoie la i-ieme condition aux limites.
Parameters
(int i) le rang de la i-ieme condition aux limites
Returns
(Cond_lim&) la i-ieme condition aux limites
References les_conditions_limites_.
les_conditions_limites() [3/4]
Conds_lim & Domaine_Cl_dis_base::les_conditions_limites ()
Renvoie le tableaux des conditions aux limites.
Returns
(Conds_lim&) le tableau des conditions aux limites
References les_conditions_limites_.
Referenced by calculer_derivee_en_temps(), condition_limite_de_la_face_reelle(), condition_limite_de_la_face_virtuelle(), condition_limite_de_la_frontiere(), Domaine_Cl_EF::imposer_cond_lim(), Domaine_Cl_PolyMAC::imposer_cond_lim(), Domaine_Cl_VDF::imposer_cond_lim(), Domaine_Cl_VEF::imposer_cond_lim(), Domaine_Cl_EF::imposer_symetrie_partiellement(), and readOn().
les_conditions_limites() [4/4]
const Conds_lim & Domaine_Cl_dis_base::les_conditions_limites () const
Renvoie le tableaux des conditions aux limites.
(version const)
Returns
(Conds_lim&) le tableau des conditions aux limites
References les_conditions_limites_.
nb_cond_lim()
int Domaine_Cl_dis_base::nb_cond_lim () const
Renvoie le nombre de conditions aux limites.
Returns
(int) le nombre de conditions aux limites
References les_conditions_limites_, and TRUST_Vector< _CLASSE_ >::size().
Referenced by Op_Diff_EF::ajouter_bords(), Op_Dift_EF_Q1::ajouter_bords(), Op_Diff_EF::ajouter_contributions_bords(), Op_Dift_EF_Q1::ajouter_contributions_bords(), Solveur_Masse_EF::appliquer_impl(), Op_Diff_VEFP1NCP1B_Face::associer(), Champ_front_contact_VEF::associer_front_vf_et_ch_front_autre_pb(), avancer(), BilanQdmVEF::bilan_energie(), BilanQdmVEF::bilan_qdm(), calculer_derivee_en_temps(), Op_Diff_DG_base::calculer_dt_stab(), Op_Diff_PolyMAC_base::calculer_dt_stab(), Op_Conv_Muscl_New_VEF_Face::calculer_dt_stab(), Op_Diff_VEF_base::calculer_dt_stab(), Modele_turbulence_hyd_LES_axi_VDF::calculer_fonction_structure(), Champ_base::calculer_valeurs_som_compo_post(), Champ_base::calculer_valeurs_som_post(), changer_temps_futur(), Triple_Line_Model_FT_Disc::completer(), Pb_Couple_Rayonnement::completer(), Equation_base::completer(), Source_Diffusion_supplementaire_echelle_temp_turb::completer(), Triple_Line_Model_FT_Disc::compute_TCL_fluxes_in_all_boundary_cells(), Champ_front_fonc_gradient::condition_limite(), condition_limite_de_la_face_reelle(), condition_limite_de_la_face_virtuelle(), condition_limite_de_la_frontiere(), Op_EF_base::dimensionner(), Source_PDF_EF::filtre_CLD(), Domaine_Cl_EF::imposer_cond_lim(), Domaine_Cl_PolyMAC::imposer_cond_lim(), Domaine_Cl_VDF::imposer_cond_lim(), Domaine_Cl_VEF::imposer_cond_lim(), Domaine_Cl_EF::imposer_symetrie_partiellement(), Sonde::init_bords(), Echange_contact_rayo_semi_transp_VDF::la_Cl_opposee(), AssembleurPVDF_PF::modifier_secmem(), Assembleur_P_EF::modifier_secmem(), Assembleur_P_PolyMAC::modifier_secmem(), Assembleur_P_VDF::modifier_secmem(), Assembleur_P_VEF::modifier_secmem(), Assembleur_P_VEFPreP1B::modifier_secmem(), Assembleur_P_VEFPreP1B::modifier_secmem_elem(), Assembleur_P_VEFPreP1B::modifier_secmem_som(), Modele_rayo_semi_transp::preparer_calcul(), reculer(), set_temps_defaut(), Champ_Face_VDF::verifie_valeurs_cl(), Champ_P1NC::verifie_valeurs_cl(), and Champ_Q1NC::verifie_valeurs_cl().
mettre_a_jour()
void Domaine_Cl_dis_base::mettre_a_jour (double temps) virtual
Effectue une mise a jour en temps de toutes les conditions aux limites.
Parameters
(double temps) le pas de temps de mise a jour
References les_conditions_limites_, and Conds_lim::mettre_a_jour().
Referenced by RK3_FT::faire_un_pas_de_temps_pb_couple(), RK3_FT::iterateTimeStep(), Schema_Phase_field::iterateTimeStep(), Multi_Sch_ThHyd::iterateTimeStep(), Modele_turbulence_scal_Fluctuation_Temperature::mettre_a_jour(), Modele_turbulence_hyd_K_Eps::mettre_a_jour(), Modele_turbulence_hyd_K_Eps_2_Couches::mettre_a_jour(), Modele_turbulence_hyd_K_Eps_Bas_Reynolds::mettre_a_jour(), Modele_turbulence_hyd_K_Eps_Bicephale::mettre_a_jour(), Modele_turbulence_hyd_K_Eps_Realisable::mettre_a_jour(), Modele_turbulence_hyd_K_Eps_Realisable_Bicephale::mettre_a_jour(), Modele_turbulence_hyd_K_Omega::mettre_a_jour(), Navier_Stokes_IBM::preparer_calcul(), Navier_Stokes_std::preparer_calcul(), and Equation_base::updateGivenFields().
mettre_a_jour_ss_pas_dt()
void Domaine_Cl_dis_base::mettre_a_jour_ss_pas_dt (double temps) virtual
Effectue une mise a jour pour des sous pas de temps d'un schema en temps (par exemple dans RungeKutta)
pour toutes les Cond Lims renvoyant 1 par le biais de la methode int Cond_Lim_base::a_mettre_a_jour_ss_pas_dt();
Parameters
(double temps) le pas de temps de mise a jour
References Cond_lim_base::a_mettre_a_jour_ss_pas_dt(), les_conditions_limites_, and Cond_lim_base::mettre_a_jour().
resetTime()
void Domaine_Cl_dis_base::resetTime (double time)
References les_conditions_limites_, and Conds_lim::resetTime().
Referenced by Equation_base::resetTime().
completer() [1/2]
void Domaine_Cl_dis_base::completer ()
Appel Cond_lim_base::completer() sur chaque condition aux limites.
References completer(), Conds_lim::completer(), domaine_dis(), and les_conditions_limites_.
Referenced by completer(), Equation_base::completer(), Convection_Diffusion_Temperature_FT_Disc::completer(), Transport_Fluctuation_Temperature::completer(), and Transport_Flux_Chaleur_Turbulente::completer().
contient_Cl()
int Domaine_Cl_dis_base::contient_Cl (const Nom & type)
Renvoie 1 si l'objet contient une condition aux limites du Nom specifie.
Renvoie 0 sinon.
Parameters
(Nom& type) le nom de la condition aux limites a chercher
Returns
(int) 1 si la condition aux limites de nom specifie a ete trouve, 0 sinon.
References les_conditions_limites_.
domaine_dis() [1/2]
Domaine_dis_base & Domaine_Cl_dis_base::domaine_dis ()
Renvoie une reference sur le domaine discretisee associee aux conditions aux limites.
Cette Domaine_dis est associee au travers de l'equation associee et pas directement a l'objet Domaine_Cl_dis_base.
Returns
(Domaine_dis_base&) le domaine discretisee associee a l'equation associe aux conditions aux limites.
References Equation_base::domaine_dis(), and MorEqn::equation().
Referenced by Source_Masse_Fluide_Dilatable_VEF::ajouter_eq_espece(), Source_Masse_Fluide_Dilatable_VDF::ajouter_projection(), Source_Masse_Fluide_Dilatable_VEF::ajouter_projection(), BilanQdmVEF::bilan_energie(), BilanQdmVEF::bilan_qdm(), Echange_contact_VDF::calculer_h_autre_pb(), Echange_contact_rayo_semi_transp_VDF::calculer_temperature_bord(), Echange_contact_Rayo_transp_VDF::calculer_Teta_paroi(), completer(), domaine(), Domaine_Cl_EF::domaine_EF(), Domaine_Cl_VDF::domaine_VDF(), Domaine_Cl_VEF::domaine_vef(), Domaine_Cl_DG::domaine_vf(), Domaine_Cl_PolyMAC::domaine_vf(), Domaine_Cl_VEF::imposer_cond_lim(), Domaine_Cl_EF::imposer_symetrie(), Domaine_Cl_EF::imposer_symetrie_matrice_secmem(), Echange_contact_VDF::initialiser(), Domaine_Cl_VEF::initialiser(), Source_Masse_Fluide_Dilatable_base::mettre_a_jour(), Frontiere_ouverte_vitesse_vortex::mettre_a_jour(), Echange_contact_rayo_semi_transp_VDF::mettre_a_jour(), Echange_contact_Rayo_transp_VDF::mettre_a_jour(), Cond_Lim_Rayo::preparer_surface(), and readOn().
domaine_dis() [2/2]
const Domaine_dis_base & Domaine_Cl_dis_base::domaine_dis () const
Renvoie une reference sur le domaine discretisee associee aux conditions aux limites.
Cette Domaine_dis est associee au travers de l'equation associee et pas directement a l'objet Domaine_Cl_dis_base. (version const)
Returns
(Domaine_dis_base&) le domaine discretisee associee a l'equation associe aux conditions aux limites.
References Equation_base::domaine_dis(), and MorEqn::equation().
domaine() [1/2]
Domaine & Domaine_Cl_dis_base::domaine ()
References Domaine_dis_base::domaine(), and domaine_dis().
Referenced by Echange_contact_Correlation_VDF::calculer_CL(), Echange_contact_Correlation_VEF::calculer_CL(), Echange_contact_Correlation_VDF::init_tab_echange(), Frontiere_ouverte_vitesse_vortex::mettre_a_jour(), and nb_faces_Cl().
domaine() [2/2]
const Domaine & Domaine_Cl_dis_base::domaine () const
References Domaine_dis_base::domaine(), and domaine_dis().
associer()
virtual void Domaine_Cl_dis_base::associer (const Domaine_dis_base & ddb) inline virtual
Reimplemented in Domaine_Cl_VDF, and Domaine_Cl_VEF.
Referenced by Equation_base::discretiser(), and Transport_Interfaces_FT_Disc::discretiser().
calculer_coeffs_echange()
int Domaine_Cl_dis_base::calculer_coeffs_echange (double temps) virtual
Calcul des coefficients d'echange pour les problemes couples thermiques.
Returns
(int) renvoie toujours 1
References Conds_lim::calculer_coeffs_echange(), and les_conditions_limites_.
Referenced by Schema_Euler_Implicite::faire_un_pas_de_temps_pb_couple(), Schema_Implicite_Multi_TimeStep_base::faire_un_pas_de_temps_pb_couple(), Pb_Couple_rayo_semi_transp::initialize(), Probleme_base_interface_proto::initTimeStep_impl(), Pb_Dilatable_base::iterateTimeStep(), Probleme_base_interface_proto::iterateTimeStep_impl(), and Probleme_base_interface_proto::solveTimeStep_impl().
imposer_cond_lim()
virtual void Domaine_Cl_dis_base::imposer_cond_lim (Champ_Inc_base & , double) pure virtual
Implemented in Domaine_Cl_DG, Domaine_Cl_EF, Domaine_Cl_PolyMAC, Domaine_Cl_VDF, and Domaine_Cl_VEF.
Referenced by Schema_Euler_explicite_ALE::faire_un_pas_de_temps_eqn_base(), RK3_MassRedistrib::faire_un_pas_de_temps_eqn_base(), Schema_Euler_explicite_Phase_field::faire_un_pas_de_temps_eqn_base(), Leap_frog::faire_un_pas_de_temps_eqn_base(), Pred_Cor::faire_un_pas_de_temps_eqn_base(), Schema_Euler_explicite::faire_un_pas_de_temps_eqn_base(), Schema_Euler_Implicite::faire_un_pas_de_temps_eqn_base(), Schema_Explicite_Multi_TimeStep_base::faire_un_pas_de_temps_eqn_base(), Schema_Implicite_Multi_TimeStep_base::faire_un_pas_de_temps_eqn_base(), RRK2::faire_un_pas_de_temps_eqn_base(), Schema_Euler_Implicite::faire_un_pas_de_temps_pb_couple(), Sch_CN_iteratif::iterateTimeStepOnEquation(), Sch_CN_EX_iteratif::iterateTimeStepOnNS(), Sch_CN_EX_iteratif::iterateTimeStepOnOther(), Simple::iterer_eqs(), Schema_Implicite_Multi_TimeStep_base::Iterer_Pb(), Schema_Euler_Implicite::Iterer_Pb(), Equation_base::preparer_calcul(), Schema_Euler_Implicite::test_stationnaire(), and Schema_Implicite_Multi_TimeStep_base::test_stationnaire().
nb_faces_Cl()
int Domaine_Cl_dis_base::nb_faces_Cl () const
References domaine(), and Domaine_32_64< _SIZE_ >::nb_faces_frontiere().
Referenced by Assembleur_P_EF::assembler_mat(), and Assembleur_P_VEF::remplir().
la_cl_de_la_face()
const Cond_lim & Domaine_Cl_dis_base::la_cl_de_la_face (int num_face) const virtual
A partir d'un indice de face de bord dans le Domaine_VF, renvoie la condition aux limites a laquelle cette face.
appartient, pour 0 <= num_face < nb_faces_Cl().
Reimplemented in Domaine_Cl_VDF.
References Process::exit(), Frontiere_dis_base::frontiere(), Cond_lim_base::frontiere_dis(), les_conditions_limites_, Frontiere_32_64< _SIZE_ >::nb_faces(), Frontiere_32_64< _SIZE_ >::num_premiere_face(), and TRUST_Vector< _CLASSE_ >::size().
Referenced by Maillage_FT_Disc::calculer_costheta_minmax().
condition_limite_de_la_face_reelle()
const Cond_lim_base & Domaine_Cl_dis_base::condition_limite_de_la_face_reelle (int face_globale, int & face_locale) const
Renvoie la condition limite associee a une face reelle donnee.
Met dans face_locale le numero de la face dans la frontiere. Provoque une erreur si la face ne porte pas de CL.
References les_conditions_limites(), nb_cond_lim(), Frontiere_32_64< _SIZE_ >::nb_faces(), and Frontiere_32_64< _SIZE_ >::num_premiere_face().
Referenced by Maillage_FT_Disc::calcul_courbure_sommets(), and Maillage_FT_Disc::nettoyer_noeuds_virtuels_et_frontieres().
condition_limite_de_la_face_virtuelle()
const Cond_lim_base & Domaine_Cl_dis_base::condition_limite_de_la_face_virtuelle (int face_globale, int & face_locale) const
Renvoie la condition limite associee a une face virtuelle donnee.
Met dans face_locale le numero de la face dans la frontiere. Provoque une erreur si la face ne porte pas de CL.
References Frontiere_32_64< _SIZE_ >::get_faces_virt(), les_conditions_limites(), nb_cond_lim(), Frontiere_32_64< _SIZE_ >::nb_faces(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
condition_limite_de_la_frontiere() [1/2]
const Cond_lim_base & Domaine_Cl_dis_base::condition_limite_de_la_frontiere (Nom frontiere) const
Renvoie la condition limite associee a une frontiere de nom donne.
Provoque une erreur si aucune frontiere ne porte ce nom.
References Process::exit(), Frontiere_32_64< _SIZE_ >::le_nom(), les_conditions_limites(), and nb_cond_lim().
Referenced by Echange_contact_VDF_FT_Disc_solid::mettre_a_jour().
condition_limite_de_la_frontiere() [2/2]
Cond_lim_base & Domaine_Cl_dis_base::condition_limite_de_la_frontiere (Nom frontiere)
Renvoie la condition limite associee a une frontiere de nom donne.
Provoque une erreur si aucune frontiere ne porte ce nom.
References Process::exit(), Frontiere_32_64< _SIZE_ >::le_nom(), les_conditions_limites(), and nb_cond_lim().
changer_temps_futur()
void Domaine_Cl_dis_base::changer_temps_futur (double temps, int i)
Change le i-eme temps futur de toutes les CLs.
References changer_temps_futur(), les_conditions_limites_, and nb_cond_lim().
Referenced by changer_temps_futur(), and Equation_base::initTimeStep().
calculer_derivee_en_temps()
void Domaine_Cl_dis_base::calculer_derivee_en_temps (double t1, double t2)
Calcule le taux d'accroissement des CLs instationnaires entre t1 et t2.
References Champ_front_base::calculer_derivee_en_temps(), Champ_front_base::instationnaire(), les_conditions_limites(), and nb_cond_lim().
Referenced by RK3_FT::iterateTimeStep(), and Equation_base::updateGivenFields().
set_temps_defaut()
void Domaine_Cl_dis_base::set_temps_defaut (double temps)
Change le i-eme temps futur de toutes les CLs.
References les_conditions_limites_, nb_cond_lim(), and set_temps_defaut().
Referenced by Equation_base::initTimeStep(), and set_temps_defaut().
avancer()
int Domaine_Cl_dis_base::avancer (double temps)
Tourne la roue des CLs jusqu'au temps donne.
References avancer(), les_conditions_limites_, and nb_cond_lim().
Referenced by avancer(), and Equation_base::mettre_a_jour().
reculer()
int Domaine_Cl_dis_base::reculer (double temps)
Tourne la roue des CLsj usqu'au temps donne.
References les_conditions_limites_, nb_cond_lim(), and reculer().
Referenced by reculer().
initialiser()
int Domaine_Cl_dis_base::initialiser (double temps) virtual
Initialise les CLs Contrairement aux methodes mettre_a_jour, les methodes.
initialiser des CLs ne peuvent pas dependre de l'exterieur (lui-meme peut ne pas etre initialise)
Returns
(int) 1 si OK, 0 sinon
Reimplemented in Domaine_Cl_DG, Domaine_Cl_EF, Domaine_Cl_PolyMAC, and Domaine_Cl_VEF.
References Conds_lim::initialiser(), and les_conditions_limites_.
Referenced by Domaine_Cl_DG::initialiser(), Domaine_Cl_EF::initialiser(), Domaine_Cl_PolyMAC::initialiser(), Domaine_Cl_VEF::initialiser(), Equation_base::preparer_calcul(), and Transport_Interfaces_FT_Disc::preparer_calcul().
le_nom()
const Nom & Domaine_Cl_dis_base::le_nom () const inline override virtual
Donne le nom de l'Objet_U Methode a surcharger : renvoie "neant" dans cette implementation.
Returns
(Nom&) le nom de l'Objet_U
Reimplemented from Objet_U.
References nom_.
associer_inconnue()
void Domaine_Cl_dis_base::associer_inconnue (const Champ_Inc_base & inco) virtual
References mon_inconnue.
Referenced by Equation_base::discretiser(), and Transport_Interfaces_FT_Disc::discretiser().
inconnue() [1/2]
const Champ_Inc_base & Domaine_Cl_dis_base::inconnue () const virtual
References mon_inconnue.
inconnue() [2/2]
Champ_Inc_base & Domaine_Cl_dis_base::inconnue () virtual
References mon_inconnue.
completer() [2/2]
virtual void Domaine_Cl_dis_base::completer (const Domaine_dis_base &) protected pure virtual
Implemented in Domaine_Cl_DG, Domaine_Cl_EF, Domaine_Cl_PolyMAC, Domaine_Cl_VDF, and Domaine_Cl_VEF.
Member Data Documentation
info_obj
const Type_info Domaine_Cl_dis_base::info_obj static
nom_
Nom Domaine_Cl_dis_base::nom_ protected
Referenced by le_nom(), and nommer().
les_conditions_limites_
Conds_lim Domaine_Cl_dis_base::les_conditions_limites_ protected
Referenced by avancer(), calculer_coeffs_echange(), changer_temps_futur(), completer(), Domaine_Cl_VDF::completer(), contient_Cl(), initialiser(), Domaine_Cl_VEF::initialiser(), la_cl_de_la_face(), Domaine_Cl_VDF::la_cl_de_la_face(), les_conditions_limites(), mettre_a_jour(), mettre_a_jour_ss_pas_dt(), Domaine_Cl_DG::nb_bord_periodicite(), Domaine_Cl_EF::nb_bord_periodicite(), Domaine_Cl_PolyMAC::nb_bord_periodicite(), Domaine_Cl_VEF::nb_bord_periodicite(), nb_cond_lim(), Domaine_Cl_VDF::nb_faces_sortie_libre(), Domaine_Cl_VEF::nb_faces_sortie_libre(), reculer(), Domaine_Cl_EF::remplir_type_elem_Cl(), Domaine_Cl_VEF::remplir_type_elem_Cl(), Domaine_Cl_VEF::remplir_volumes_entrelaces_Cl(), resetTime(), and set_temps_defaut().
mon_inconnue
TRUST_Ref< Champ_Inc_base *> Domaine_Cl_dis_base::mon_inconnue protected
Referenced by associer_inconnue(), and inconnue().