TrioCFD: Ch_input_uniforme Class Reference
Ch_input_uniforme Class Reference
#include <Ch_input_uniforme.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Champ_Uniforme
const Type_info * get_info () const override
Public Member Functions inherited from TRUSTChamp_Divers_generique< Champ_Divers_Type::UNIFORME >
DoubleVect & valeur_a (const DoubleVect &, DoubleVect &tab_valeurs) const override
double valeur_a_compo (const DoubleVect &x, int ncomp) const override
DoubleVect & valeur_a_elem (const DoubleVect &positions, DoubleVect &tab_valeurs, int) const override
double valeur_a_elem_compo (const DoubleVect &, int, int ncomp) const override
DoubleTab & valeur_aux (const DoubleTab &, DoubleTab &tab_valeurs) const override
DoubleVect & valeur_aux_compo (const DoubleTab &, DoubleVect &tab_valeurs, int ncomp) const override
DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &, DoubleTab &tab_valeurs) const override
DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &, DoubleVect &tab_valeurs, int ncomp) const override
Public Member Functions inherited from Champ_Don_base
void dimensionner (int, int)
int fixer_nb_valeurs_nodales (int nb_noeuds) override
const Type_info * get_info () const override
int imprime (Sortie &, int) const override
virtual int initialiser (const double temps)
void mettre_a_jour (double temps) override
int reprendre (Entree &) override
void resetTime (double time) override
int sauvegarder (Sortie &) const override
DoubleTab & valeurs () override
Public Member Functions inherited from Champ_base
Champ_base & affecter (const Champ_base &)
Champ_base ()
virtual double changer_temps (const double t)
const Type_info * get_info () const override
double temps () const
virtual DoubleTab & trace (const Frontiere_dis_base &, DoubleTab &, double, int distant) const
virtual DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const
virtual double valeur_a_compo (const DoubleVect &position, int ncomp) const
virtual DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &valeurs, int le_poly) const
virtual double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const
virtual DoubleVect & valeur_a_sommet (int, const Domaine &, DoubleVect &) const
virtual DoubleTab & valeur_aux (const DoubleTab &positions, DoubleTab &valeurs) const
virtual DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const
virtual DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const
virtual DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp) const
Public Member Functions inherited from Field_base
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
virtual void fixer_nb_comp (int i)
virtual const Nom & fixer_nom_compo (const Nom &)
virtual const Nom & fixer_nom_compo (int, const Nom &)
virtual const Noms & fixer_noms_compo (const Noms &)
virtual const Nom & fixer_unite (const Nom &)
virtual const Nom & fixer_unite (int i, const Nom &)
virtual const Noms & fixer_unites (const Noms &)
const Type_info * get_info () const override
const Nom & nom_compo (int) const
void nommer (const Nom &) override
const Nom & unite () const
const Nom & unite (int) const
const Noms & unites () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Champ_Proto
int lire_dimension (Entree &, const Nom &)
int lire_dimension (int dim, const Nom &le_nom_)
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Champ_Uniforme
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Champ_Don_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Field_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Champ_Input_Proto
void read (Entree &is)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
Cette classe represente un champ uniforme accessible par setInputField
See also
Champ_Input_Proto
Constructor & Destructor Documentation
Ch_input_uniforme()
Ch_input_uniforme::Ch_input_uniforme ()
~Ch_input_uniforme()
Ch_input_uniforme::~Ch_input_uniforme ()
Member Function Documentation
cree_instance()
Objet_U * Ch_input_uniforme::cree_instance () static
taille_memoire()
unsigned Ch_input_uniforme::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Ch_input_uniforme::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Ch_input_uniforme::info () static
get_info()
const Type_info * Ch_input_uniforme::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
Ch_input_uniforme & Ch_input_uniforme::self_cast (Objet_U & r) static
self_cast() [2/2]
const Ch_input_uniforme & Ch_input_uniforme::self_cast (const Objet_U & r) static
printOn()
Sortie & Ch_input_uniforme::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
readOn()
Entree & Ch_input_uniforme::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
References Champ_Input_Proto::initial_value_, Champ_Input_Proto::mon_pb, Field_base::nb_compo_, Champ_Input_Proto::read(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), Champ_Input_Proto::sous_domaine_ok, and Champ_Don_base::valeurs().
affecter_()
Champ_base & Ch_input_uniforme::affecter_ (const Champ_base &) inline override virtual
Implements Champ_base.
getTemplate()
void Ch_input_uniforme::getTemplate (TrioField & afield) const override virtual
Provides afield with a dummy geometry, a name, a time interval, components, and no field ownership.
Implements Champ_Input_Proto.
References Field_base::le_nom(), Champ_Input_Proto::mon_pb, and Field_base::nb_comp().
setValue()
void Ch_input_uniforme::setValue (const TrioField & afield) override virtual
Uses the first value in afield as uniform value, regardless of geometry.
Implements Champ_Input_Proto.
References Champ_Input_Proto::setValueOnTab(), and Champ_Don_base::valeurs().
set_nb_comp()
void Ch_input_uniforme::set_nb_comp (int i) override protected virtual
Implements Champ_Input_Proto.
References Field_base::fixer_nb_comp().
set_name()
void Ch_input_uniforme::set_name (const Nom & name) override protected virtual
Implements Champ_Input_Proto.
References Field_base::nommer().
get_name()
const Nom & Ch_input_uniforme::get_name () const protected virtual
References Field_base::le_nom().
Member Data Documentation
info_obj
const Type_info Ch_input_uniforme::info_obj static