TrioCFD: Op_Evanescence_Homogene_Elem_base Class Reference
Op_Evanescence_Homogene_Elem_base Class Reference
#include <Op_Evanescence_Homogene_Elem_base.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Operateur_Evanescence_base
const Type_info * get_info () const override
Public Member Functions inherited from Operateur_base
void associer_eqn (const Equation_base &)
virtual double calculer_dt_stab () const
virtual void completer ()
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual void mettre_a_jour (double temps)
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Operateur_Evanescence_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
gestion de l'evanescence dans une equation aux elements (masse, energie ...)
See also
Operateur_Evanescence_base Operateur_base
Constructor & Destructor Documentation
Op_Evanescence_Homogene_Elem_base()
Op_Evanescence_Homogene_Elem_base::Op_Evanescence_Homogene_Elem_base ()
~Op_Evanescence_Homogene_Elem_base()
Op_Evanescence_Homogene_Elem_base::~Op_Evanescence_Homogene_Elem_base () override
Member Function Documentation
info()
const Type_info * Op_Evanescence_Homogene_Elem_base::info () static
get_info()
const Type_info * Op_Evanescence_Homogene_Elem_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Operateur_base.
Reimplemented in Op_Evanescence_Homogene_VDF_Elem.
self_cast() [1/2]
Op_Evanescence_Homogene_Elem_base & Op_Evanescence_Homogene_Elem_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Op_Evanescence_Homogene_Elem_base & Op_Evanescence_Homogene_Elem_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Op_Evanescence_Homogene_Elem_base::printOn (Sortie & os) const override protected virtual
DOES NOTHING - to override in derived classes.
Imprime l'operateur sur un flot de sortie.
Parameters
(Sortie& os) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Operateur_base.
Reimplemented in Op_Evanescence_Homogene_VDF_Elem.
readOn()
Entree & Op_Evanescence_Homogene_Elem_base::readOn (Entree & is) override protected virtual
DOES NOTHING - to override in derived classes.
Lit un operateur sur un flot d'entree.
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Operateur_base.
Reimplemented in Op_Evanescence_Homogene_VDF_Elem.
References Param::ajouter(), Param::lire_avec_accolades_depuis(), Objet_U::que_suis_je(), and Param::REQUIRED.
Referenced by Op_Evanescence_Homogene_PolyMAC_P0P1NC_Elem::readOn(), and Op_Evanescence_Homogene_VDF_Elem::readOn().
has_interface_blocs()
int Op_Evanescence_Homogene_Elem_base::has_interface_blocs () const inline override virtual
Reimplemented from Operateur_base.
dimensionner_blocs()
void Op_Evanescence_Homogene_Elem_base::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl = {}) const override virtual
Reimplemented from Operateur_base.
References Matrix_tools::allocate_morse_matrix(), TRUSTTab< _TYPE_, _SIZE_ >::append_line(), MorEqn::equation(), Matrice_Morse::get_tab1(), Matrice_Morse::get_tab2(), Equation_base::inconnue(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Matrice_Morse::nb_colonnes(), Matrice_Morse::nb_lignes(), and Champ_Inc_base::valeurs().
ajouter_blocs()
void Op_Evanescence_Homogene_Elem_base::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = {}) const override virtual
Reimplemented from Operateur_base.
References Process::abort(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Saturation_base::dP_Tsat(), MorEqn::equation(), Pb_Multiphase::equation_masse(), Pb_Multiphase::equation_qdm(), Milieu_composite::get_saturation(), Matrice_Morse::get_set_coeff(), Matrice_Morse::get_tab1(), Matrice_Morse::get_tab2(), Nom::getString(), Milieu_composite::has_saturation(), Equation_base::inconnue(), SETS::iteration_, Field_base::le_nom(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Milieu_base::masse_volumique(), Equation_base::milieu(), SETS::p_degen_, Equation_base::schema_temps(), Saturation_base::Tsat(), Champ_Inc_base::valeurs(), and Champ_Proto::valeurs().
alpha_res()
double Op_Evanescence_Homogene_Elem_base::alpha_res () const inline override virtual
Reimplemented from Operateur_Evanescence_base.
Member Data Documentation
info_obj
const Type_info Op_Evanescence_Homogene_Elem_base::info_obj static