TrioCFD: EF_discretisation Class Reference
EF_discretisation Class Reference
#include <EF_discretisation.h>
Public Member Functions
void discretiser_champ (const Motcle &directive, const Domaine_dis_base &z, Nature_du_champ nature, const Noms &nom, const Noms &unite, int nb_comp, double temps, TRUST_Deriv< Champ_Don_base > &champ) const override
void discretiser_champ (const Motcle &directive, const Domaine_dis_base &z, Nature_du_champ nature, const Noms &nom, const Noms &unite, int nb_comp, double temps, TRUST_Deriv< Champ_Fonc_base > &champ) const override
void discretiser_champ (const Motcle &directive, const Domaine_dis_base &z, Nature_du_champ nature, const Noms &nom, const Noms &unite, int nb_comp, int nb_pas_dt, double temps, TRUST_Deriv< Champ_Inc_base > &champ, const Nom &sous_type=NOM_VIDE) const override
const Type_info * get_info () const override
Nom get_name_of_type_for (const Nom &class_operateur, const Nom &type_operateur, const Equation_base &eqn, const TRUST_Ref< Champ_base * > &champ_sup) const override
void proprietes_physiques_fluide_Ostwald (const Domaine_dis_base &, Fluide_Ostwald &, const Navier_Stokes_std &, const Champ_Inc_base &) const override
Public Member Functions inherited from Discret_Thyd
const Type_info * get_info () const override
Public Member Functions inherited from Discret_Thermique
const Type_info * get_info () const override
virtual void discretiser_champ (const Motcle &directive, const Domaine_dis_base &z, Nature_du_champ nature, const Noms &nom, const Noms &unite, int nb_comp, int nb_pas_dt, double temps, TRUST_Deriv< Champ_Inc_base > &champ, const Nom &sous_type=NOM_VIDE) const
const Type_info * get_info () const override
virtual Nom get_name_of_type_for (const Nom &class_operateur, const Nom &type_operteur, const Equation_base &eqn, const TRUST_Ref< Champ_base * > &champ_supp=TRUST_Ref< Champ_base * >()) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Discret_Thyd
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Discret_Thermique
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Discretisation_base
static void creer_champ (TRUST_Deriv< Champ_Don_base > &ch, const Domaine_dis_base &z, const Nom &type, const Nom &nom, const Nom &unite, int nb_comp, int nb_ddl, double temps, const Nom &directive=NOM_VIDE, const Nom &nom_discretisation=NOM_VIDE)
static void creer_champ (TRUST_Deriv< Champ_Fonc_base > &ch, const Domaine_dis_base &z, const Nom &type, const Nom &nom, const Nom &unite, int nb_comp, int nb_ddl, double temps, const Nom &directive=NOM_VIDE, const Nom &nom_discretisation=NOM_VIDE)
static void creer_champ (TRUST_Deriv< Champ_Inc_base > &ch, const Domaine_dis_base &z, const Nom &type, const Nom &nom, const Nom &unite, int nb_comp, int nb_ddl, int nb_pas_dt, double temps, const Nom &directive=NOM_VIDE, const Nom &nom_discretisation=NOM_VIDE)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
EF_discretisation()
EF_discretisation::EF_discretisation ()
~EF_discretisation()
EF_discretisation::~EF_discretisation ()
Member Function Documentation
cree_instance()
Objet_U * EF_discretisation::cree_instance () static
taille_memoire()
unsigned EF_discretisation::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int EF_discretisation::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * EF_discretisation::info () static
get_info()
const Type_info * EF_discretisation::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
EF_discretisation & EF_discretisation::self_cast (Objet_U & r) static
self_cast() [2/2]
const EF_discretisation & EF_discretisation::self_cast (const Objet_U & r) static
printOn()
Sortie & EF_discretisation::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
Referenced by EF_axi_discretisation::printOn().
readOn()
Entree & EF_discretisation::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
Referenced by EF_axi_discretisation::readOn().
discretiser_champ() [1/3]
void EF_discretisation::discretiser_champ (const Motcle & directive, const Domaine_dis_base & z, Nature_du_champ nature, const Noms & noms, const Noms & unites, int nb_comp, int nb_pas_dt, double temps, TRUST_Deriv< Champ_Inc_base > & champ, const Nom & sous_type = NOM_VIDE) const override virtual
Discretisation d'un champ pour le EF en fonction d'une directive de discretisation.
La directive est un Motcle comme "vitesse", "pression", "temperature", "champ_elem" (cree un champ de type P0), ... Cette methode determine le type du champ a creer en fonction du type d'element et de la directive de discretisation. Elle determine ensuite le nombre de ddl et fixe l'ensemble des parametres du champ (type, nb_compo, nb_ddl, nb_pas_dt, nom(s), unite(s) et nature du champ) et associe le Domaine_dis au champ. Voir le code pour avoir la correspondance entre les directives et le type de champ cree.
Reimplemented from Discretisation_base.
References Discretisation_base::creer_champ(), Discretisation_base::DEMANDE_DESCRIPTION, Objet_U::dimension, Discretisation_base::discretiser_champ(), Process::exit(), Field_base::fixer_nature_du_champ(), Field_base::fixer_noms_compo(), Field_base::fixer_unites(), Domaine_dis_base::nb_elem(), Domaine_dis_base::nb_som(), Objet_U::que_suis_je(), Motcles::search(), and Domaine_EF::type_elem().
discretiser_champ() [2/3]
void EF_discretisation::discretiser_champ (const Motcle & directive, const Domaine_dis_base & z, Nature_du_champ nature, const Noms & noms, const Noms & unites, int nb_comp, double temps, TRUST_Deriv< Champ_Fonc_base > & champ) const override virtual
Idem que EF_discretisation::discretiser_champ(.
.. , Champ_Inc)
Reimplemented from Discretisation_base.
discretiser_champ() [3/3]
void EF_discretisation::discretiser_champ (const Motcle & directive, const Domaine_dis_base & z, Nature_du_champ nature, const Noms & noms, const Noms & unites, int nb_comp, double temps, TRUST_Deriv< Champ_Don_base > & champ) const override virtual
Idem que EF_discretisation::discretiser_champ(.
.. , Champ_Inc)
Reimplemented from Discretisation_base.
domaine_cl_dis_type()
Nom EF_discretisation::domaine_cl_dis_type () const inline override virtual
Implements Discretisation_base.
distance_paroi()
void EF_discretisation::distance_paroi (const Schema_Temps_base & sch, Domaine_dis_base & z, TRUST_Deriv< Champ_Fonc_base > & ch) const
References Champ_Fonc_base::associer_domaine_dis_base(), Champ_base::changer_temps(), Field_base::fixer_nb_comp(), Champ_Fonc_P0_base::fixer_nb_valeurs_nodales(), Field_base::fixer_unite(), Domaine_dis_base::nb_elem(), Field_base::nommer(), and Schema_Temps_base::temps_courant().
proprietes_physiques_fluide_Ostwald()
void EF_discretisation::proprietes_physiques_fluide_Ostwald (const Domaine_dis_base & z, Fluide_Ostwald & le_fluide, const Navier_Stokes_std & eqn_hydr, const Champ_Inc_base & ch_temper) const override virtual
discretise en EF le fluide incompressible, donc K e N
Parameters
(Domaine_dis_base&) domaine a discretiser
(Fluide_Ostwald&) fluide a discretiser
(Champ_Inc_base&) ch_vitesse
(Champ_Inc_base&) temperature
Reimplemented from Discret_Thyd.
References Navier_Stokes_std::inconnue(), Domaine_dis_base::nb_elem(), Champ_base::temps(), and Fluide_base::viscosite_dynamique().
vorticite()
void EF_discretisation::vorticite (Domaine_dis_base & z, const Champ_Inc_base & ch_vitesse, TRUST_Deriv< Champ_Fonc_base > & ch) const
References Rotationnel_Champ_P1_EF::associer_champ(), Rotationnel_Champ_Q1_EF::associer_champ(), Champ_Fonc_base::associer_domaine_dis_base(), Champ_base::changer_temps(), Objet_U::dimension, Process::exit(), Field_base::fixer_nb_comp(), Champ_Fonc_P0_base::fixer_nb_valeurs_nodales(), Field_base::fixer_nom_compo(), Field_base::fixer_unite(), Domaine_dis_base::nb_elem(), Field_base::nommer(), Champ_base::temps(), and Domaine_EF::type_elem().
creer_champ_vorticite()
void EF_discretisation::creer_champ_vorticite (const Schema_Temps_base & sch, const Champ_Inc_base & ch_vitesse, TRUST_Deriv< Champ_Fonc_base > & ch) const override virtual
Reimplemented from Discret_Thyd.
References Rotationnel_Champ_P1_EF::associer_champ(), Rotationnel_Champ_Q1_EF::associer_champ(), Champ_Fonc_base::associer_domaine_dis_base(), Champ_base::changer_temps(), Objet_U::dimension, Champ_Inc_base::domaine_dis_base(), Process::exit(), Field_base::fixer_nb_comp(), Champ_Fonc_P0_base::fixer_nb_valeurs_nodales(), Field_base::fixer_nom_compo(), Field_base::fixer_unite(), Domaine_dis_base::nb_elem(), Field_base::nommer(), and Schema_Temps_base::temps_courant().
critere_Q()
void EF_discretisation::critere_Q (const Domaine_dis_base & z, const Domaine_Cl_dis_base & zcl, const Champ_Inc_base & vitesse, TRUST_Deriv< Champ_Fonc_base > & ch) const override virtual
Reimplemented from Discret_Thyd.
References Domaine_dis_base::nb_elem(), and Champ_base::temps().
y_plus()
void EF_discretisation::y_plus (const Domaine_dis_base & z, const Domaine_Cl_dis_base & zcl, const Champ_Inc_base & vitesse, TRUST_Deriv< Champ_Fonc_base > & ch) const override virtual
Reimplemented from Discret_Thyd.
References Y_plus_Champ_Q1::associer_champ(), Y_plus_Champ_Q1::associer_domaine_Cl_dis_base(), Champ_Fonc_base::associer_domaine_dis_base(), Champ_base::changer_temps(), Field_base::fixer_nb_comp(), Champ_Fonc_P0_base::fixer_nb_valeurs_nodales(), Field_base::fixer_unite(), Domaine_dis_base::nb_elem(), Field_base::nommer(), and Champ_base::temps().
grad_T()
void EF_discretisation::grad_T (const Domaine_dis_base & z, const Domaine_Cl_dis_base & zcl, const Champ_Inc_base & temperature, TRUST_Deriv< Champ_Fonc_base > & ch) const override virtual
Reimplemented from Discret_Thyd.
References Objet_U::dimension, Domaine_dis_base::nb_elem(), and Champ_base::temps().
h_conv()
void EF_discretisation::h_conv (const Domaine_dis_base & z, const Domaine_Cl_dis_base & zcl, const Champ_Inc_base & temperature, TRUST_Deriv< Champ_Fonc_base > & ch, Motcle & nom, int temp_ref) const override virtual
Reimplemented from Discret_Thyd.
References Domaine_dis_base::nb_elem(), and Champ_base::temps().
codage_du_calcul_du_residu()
type_calcul_du_residu EF_discretisation::codage_du_calcul_du_residu () const inline override virtual
Reimplemented from Discretisation_base.
References Discretisation_base::VIA_CONTRIBUER_AU_SECOND_MEMBRE.
get_name_of_type_for()
Nom EF_discretisation::get_name_of_type_for (const Nom & class_operateur, const Nom & type_operateur, const Equation_base & eqn, const TRUST_Ref< Champ_base * > & champ_sup) const override virtual
remplit le Nom type en focntion de la classe de operateur, du type de l'operateur et de l'equation
Parameters
(class_operateur) Ce nom correspond au type de la classe de base de l'objet que l'on veut construire exemples: "source","Op_conv","Op_diff","Op_div","Op_grad","solveur_masse" Exemple get_name_of_type_for("Op_conv","amont",eqn,type); get_name_of_type_for("Op_diff"," ",eqn,type,champ_diffusisivite);
Reimplemented from Discretisation_base.
References Discretisation_base::get_name_of_type_for(), and Objet_U::que_suis_je().
is_ef()
bool EF_discretisation::is_ef () const inline override virtual
Reimplemented from Discretisation_base.
Member Data Documentation
info_obj
const Type_info EF_discretisation::info_obj static