TrioCFD: DebogFT Class Reference
DebogFT Class Reference
#include <DebogFT.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Interprete
static Objet_U & objet (const Nom &)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
Member Enumeration Documentation
DebogMode
enum DebogFT::DebogMode
Enumerator
DISABLED
WRITE_PASS
CHECK_PASS
Constructor & Destructor Documentation
DebogFT()
DebogFT::DebogFT ()
~DebogFT()
DebogFT::~DebogFT ()
Member Function Documentation
cree_instance()
Objet_U * DebogFT::cree_instance () static
taille_memoire()
unsigned DebogFT::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int DebogFT::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * DebogFT::info () static
get_info()
const Type_info * DebogFT::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Interprete.
self_cast() [1/2]
DebogFT & DebogFT::self_cast (Objet_U & r) static
self_cast() [2/2]
const DebogFT & DebogFT::self_cast (const Objet_U & r) static
printOn()
Sortie & DebogFT::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Interprete.
References Objet_U::printOn().
readOn()
Entree & DebogFT::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Interprete.
interpreter()
Entree & DebogFT::interpreter (Entree & is) override virtual
Implements Interprete.
References Param::ajouter(), CHECK_PASS, debog_mode_, Param::dictionnaire(), DISABLED, filename_, infile_, Process::je_suis_maitre(), Param::lire_avec_accolades(), outfile_, Entree_Fichier_base::ouvrir(), Sortie_Fichier_base::ouvrir(), Objet_U::que_suis_je(), seuil_absolu_, seuil_minimum_relatif_, seuil_relatif_, and WRITE_PASS.
verifier_maillage_ft()
void DebogFT::verifier_maillage_ft (const char * msg, const Maillage_FT_Disc & mesh) static
References compute_signature_sommets(), debog_mode_, DISABLED, Maillage_FT_Disc::nb_sommets(), and verifier_().
Referenced by Remaillage_FT::redistribuer_sommets().
verifier_tableau_sommets() [1/2]
void DebogFT::verifier_tableau_sommets (const char * msg, const Maillage_FT_Disc & mesh, const ArrOfDouble & data) static
References compute_signature_sommets(), debog_mode_, DISABLED, and verifier_().
Referenced by Remaillage_FT::redistribuer_sommets(), and Remaillage_FT::regulariser_maillage().
verifier_tableau_sommets() [2/2]
void DebogFT::verifier_tableau_sommets (const char * msg, const Maillage_FT_Disc & mesh, const DoubleTab & tab) static
References compute_signature_sommets(), debog_mode_, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), DISABLED, Maillage_FT_Disc::nb_sommets(), and verifier_().
verifier()
static void DebogFT::verifier (const double) static
verifier_()
void DebogFT::verifier_ (const char * msg, const ArrOfDouble & sig) static protected
References debog_mode_, Entree_Fichier_base::get_ifstream(), infile_, Process::je_suis_maitre(), Process::Journal(), outfile_, seuil_absolu_, seuil_minimum_relatif_, seuil_relatif_, TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and WRITE_PASS.
Referenced by verifier_maillage_ft(), and verifier_tableau_sommets().
compute_signature_sommets()
void DebogFT::compute_signature_sommets (const Maillage_FT_Disc & mesh, const ArrOfDouble & data, ArrOfDouble & signature) static protected
References Maillage_FT_Disc::nb_sommets(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), Maillage_FT_Disc::sommet_virtuel(), and Maillage_FT_Disc::sommets().
Referenced by verifier_maillage_ft(), and verifier_tableau_sommets().
Member Data Documentation
info_obj
const Type_info DebogFT::info_obj static
seuil_absolu_
double DebogFT::seuil_absolu_ = 1e-4 static protected
Referenced by interpreter(), and verifier_().
seuil_relatif_
double DebogFT::seuil_relatif_ = 1e-8 static protected
Referenced by interpreter(), and verifier_().
seuil_minimum_relatif_
double DebogFT::seuil_minimum_relatif_ = 1e-4 static protected
Referenced by interpreter(), and verifier_().
debog_mode_
int DebogFT::debog_mode_ = DebogFT::DISABLED static protected
Referenced by interpreter(), verifier_(), verifier_maillage_ft(), and verifier_tableau_sommets().
filename_
Nom DebogFT::filename_ static protected
Referenced by interpreter().
infile_
EFichier DebogFT::infile_ static protected
Referenced by interpreter(), and verifier_().
outfile_
SFichier DebogFT::outfile_ static protected
Referenced by interpreter(), and verifier_().