TrioCFD: Marching_Cubes Class Reference
Marching_Cubes Class Reference
#include <Marching_Cubes.h>
Public Member Functions
int construire_iso (const DoubleVect &valeurs_sommets, double isovaleur, Maillage_FT_Disc &maillage, DoubleVect &indicatrice_approchee, const Maillage_FT_Disc::AjoutPhase phase, int ignorer_collision=0) const
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
void construire_noeuds_liste_faces (const ArrOfBit &signe, const IntTab &faces_sommets, const int nb_faces_a_traiter, const int numero_PE, IntTab &def_noeud) const
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
~Marching_Cubes()
Marching_Cubes::~Marching_Cubes ()
Marching_Cubes()
Marching_Cubes::Marching_Cubes () inline
Member Function Documentation
cree_instance()
Objet_U * Marching_Cubes::cree_instance () static
taille_memoire()
unsigned Marching_Cubes::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Marching_Cubes::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Marching_Cubes::info () static
get_info()
const Type_info * Marching_Cubes::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
Marching_Cubes & Marching_Cubes::self_cast (Objet_U & r) static
self_cast() [2/2]
const Marching_Cubes & Marching_Cubes::self_cast (const Objet_U & r) static
printOn()
Sortie & Marching_Cubes::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
References Process::exit().
readOn()
Entree & Marching_Cubes::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
References Process::exit().
associer_domaine_vf()
void Marching_Cubes::associer_domaine_vf (const Domaine_VF & domaine_vf)
References Domaine_dis_base::domaine(), ref_domaine_vf_, remplir_data_marching_cubes(), and remplir_renum_virt_loc().
Referenced by Transport_Interfaces_FT_Disc::discretiser().
construire_iso() [1/2]
int Marching_Cubes::construire_iso (const DoubleVect & valeurs_sommets, double isovaleur, Maillage_FT_Disc & maillage, DoubleVect & indicatrice_approchee, const Maillage_FT_Disc::AjoutPhase phase, int ignorer_collision = 0) const
Construction d'un maillage en segments ou en triangles comme l'isovaleur d'une fonction discretisee aux sommets du maillage eulerien (associer_domaine_vf).
L'algorithme est un "marching cubes" generalise pour travailler avec un maillage vf en triangles, rectangles, cubes ou tetraedres. En cas d'erreur, le maillage est remis a zero (reset()).
Parameters
(valeurs_sommets) Un vecteur distribue de valeurs aux sommets du maillage vf dont on va construire l'isovaleur. L'espace virtuel doit etre a jour.
(isovaleur) L'isovaleur a construire
(maillage) L'objet maillage a construire. On efface completement son contenu et on le remplace par l'isovaleur.
(indicatrice_approchee) On y stocke 0 si valeurs_sommets[i] < isovaleur pour tous les sommets de la maille et si valeurs_sommets[i] > isovaleur Certaines mailles (traversees par l'interface) ont une valeur differente qu'on ne calcule pas (on met 0.5). Si phase != AJOUTE_TOUTES_PHASES, on suppose que indicatrice_approchee contient une approximation de l'indicatrice des interfaces existantes avant l'entree dans cette fonction (elle doit contenir 0 ou 1 dans les mailles non traversees par une interface, et une valeur intermediaire dans les mailles traversees). Ce tableau est ecrase quoi qu'il arrive (y compris en cas de valeur de retour=0) (faire une copie du tableau avant d'appeler la fonction si on veut revenir en arriere !)
(phase) Indique comment mettre a jour indicatrice_approchee. Ce parametre est utilise pour construire une interface en plusieurs etapes (reunion de plusieurs bulles, soustraction d'une phase, ...) phase == AJOUTE_TOUTES_PHASES : la valeur de l'indicatrice approchee est calculee partout phase == 0 : on met a 0 l'indicatrice si valeur<isovaleur, l'indicatrice est inchangee si valeur>isovaleur phase == 1 : on met a 1 l'indicatrice si valeur>isovaleur, l'indicatrice l'indicatrice est inchangee si valeur<isovaleur Valeur de retour: 1: construction reussie. 0: erreur: l'interface qu'on vient de construire entre en collision avec une interface existante (teste base sur la valeur de "indicatrice_approchee" a l'entree de la fonction)
References Process::exit(), last_def_noeud_size, TRUST_Ref< _CLASSE_ >::non_nul(), ref_domaine_vf_, and TRUSTTab< _TYPE_, _SIZE_ >::resize().
Referenced by construire_iso(), Transport_Interfaces_FT_Disc::lire_cond_init(), Transport_Interfaces_FT_Disc::mettre_a_jour(), and Remailleur_Collision_FT_Juric::traite_RuptureCoalescenceInterfaces().
construire_iso() [2/2]
int Marching_Cubes::construire_iso (const Nom & expression, double isovaleur, Maillage_FT_Disc & maillage, DoubleVect & indicatrice_approchee, const Maillage_FT_Disc::AjoutPhase phase, DoubleTab & eval_expression_sommets, int ignorer_collision = 0) const
References Parser::addVar(), construire_iso(), Objet_U::dimension, TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Parser::eval(), Process::exit(), TRUST_Ref< _CLASSE_ >::non_nul(), Parser::parseString(), ref_domaine_vf_, and Parser::setVar().
remplir_data_marching_cubes()
void Marching_Cubes::remplir_data_marching_cubes (const Domaine & domaine) protected
References Process::exit(), mcubes_def_aretes, mcubes_def_aretes_faces, mcubes_facettes, mcubes_index_facettes, mcubes_nb_facettes, nb_aretes_element, nb_aretes_faces, nb_sommets_element, nb_sommets_facette, nb_sommets_par_face, Objet_U::que_suis_je(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), and TRUSTArray< _TYPE_, _SIZE_ >::resize_array().
Referenced by associer_domaine_vf().
remplir_renum_virt_loc()
void Marching_Cubes::remplir_renum_virt_loc (const Domaine & domaine) protected
References TRUSTArray< _TYPE_, _SIZE_ >::addr(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), indice_joint_, Process::nproc(), Joint_32_64< _SIZE_ >::PEvoisin(), Joint_32_64< _SIZE_ >::renum_virt_loc(), renum_virt_loc_, and TRUSTArray< _TYPE_, _SIZE_ >::resize_array().
Referenced by associer_domaine_vf().
renum_sommets_dist_loc()
void Marching_Cubes::renum_sommets_dist_loc (const int pe_voisin, ArrOfInt & num_sommets) const protected
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), indice_joint_, renum_virt_loc_, and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by correspondance_espaces_distant_virtuel().
calculer_signe()
void Marching_Cubes::calculer_signe (const DoubleVect & valeurs_sommets, const double isovaleur, ArrOfBit & signe) const protected
References ref_domaine_vf_, ArrOfBit_32_64< _SIZE_ >::resize_array(), ArrOfBit_32_64< _SIZE_ >::setbit(), and TRUSTVect< _TYPE_, _SIZE_ >::size().
construire_noeuds_et_facettes()
int Marching_Cubes::construire_noeuds_et_facettes (const ArrOfBit & signe, IntTab & def_noeud, IntTab & facettes, DoubleVect & indicatrice_approchee, const Maillage_FT_Disc::AjoutPhase phase) const protected
References Maillage_FT_Disc::AJOUTE_TOUTES_PHASES, Objet_U::dimension, mcubes_def_aretes, mcubes_facettes, mcubes_index_facettes, mcubes_nb_facettes, Process::me(), Process::mp_min(), nb_aretes_element, nb_sommets_element, nb_sommets_facette, ref_domaine_vf_, and TRUSTTab< _TYPE_, _SIZE_ >::resize().
construire_noeuds_liste_faces()
void Marching_Cubes::construire_noeuds_liste_faces (const ArrOfBit & signe, const IntTab & faces_sommets, const int nb_faces_a_traiter, const int numero_PE, IntTab & def_noeud) const protected
Ajout des sommets situes sur des faces (bords ou joints) dans le tableau def_noeud.
Soit faces_sommets est une liste de faces d'un joint, dans ce cas, numero_PE est le PE_voisin du joint. Soit faces_sommets est la liste des faces du domaine et nb_faces_a_traiter est le nombre de faces de bord. Dans ce cas, numero_PE = nproc().
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), mcubes_def_aretes_faces, nb_aretes_element, nb_aretes_faces, nb_sommets_par_face, Process::nproc(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), and TRUSTArray< _TYPE_, _SIZE_ >::resize_array().
Referenced by construire_noeuds_joints().
construire_noeuds_joints()
void Marching_Cubes::construire_noeuds_joints (const ArrOfBit & signe, IntTab & def_noeud) const protected
References construire_noeuds_liste_faces(), Domaine_VF::face_sommets(), Domaine_VF::nb_faces_bord(), Process::nproc(), ref_domaine_vf_, and TRUST_Ref< _CLASSE_ >::valeur().
trier_les_noeuds()
void Marching_Cubes::trier_les_noeuds (IntTab & def_noeud) const protected
References TRUSTArray< _TYPE_, _SIZE_ >::addr(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), and Process::exit().
construire_noeuds_uniques()
void Marching_Cubes::construire_noeuds_uniques (IntTab & def_noeud, Maillage_FT_Disc & maillage) const protected
References Descripteur_FT::ajoute_element(), Descripteur_FT::calcul_liste_pe_voisins(), Desc_Structure_FT::calcul_schema_comm(), Maillage_FT_Disc::desc_sommets_, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Desc_Structure_FT::espace_distant(), Desc_Structure_FT::espace_virtuel(), Domaine_VF::face_voisins(), Maillage_FT_Disc::facettes_, Process::me(), Process::nproc(), ref_domaine_vf_, TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and TRUST_Ref< _CLASSE_ >::valeur().
calculer_coord_noeuds()
void Marching_Cubes::calculer_coord_noeuds (const DoubleVect & valeurs_sommets, const double isovaleur, const IntTab & def_noeud, Maillage_FT_Disc & maillage) const protected
References Maillage_FT_Disc::desc_sommets_, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Desc_Structure_FT::echange_espace_virtuel(), ref_domaine_vf_, TRUSTTab< _TYPE_, _SIZE_ >::resize(), and Maillage_FT_Disc::sommets_.
correspondance_espaces_distant_virtuel()
void Marching_Cubes::correspondance_espaces_distant_virtuel (const IntTab & def_noeud, Desc_Structure_FT & desc) const protected
References Descripteur_FT::calcul_liste_pe_voisins(), Desc_Structure_FT::calcul_schema_comm(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Desc_Structure_FT::echange_espace_virtuel(), Descripteur_FT::elements(), Desc_Structure_FT::espace_virtuel(), Descripteur_FT::pe_voisins(), renum_sommets_dist_loc(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), Descripteur_FT::set_elements(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Member Data Documentation
info_obj
const Type_info Marching_Cubes::info_obj static
ref_domaine_vf_
TRUST_Ref< Domaine_VF *> Marching_Cubes::ref_domaine_vf_ protected
Referenced by associer_domaine_vf(), calculer_coord_noeuds(), calculer_signe(), construire_iso(), construire_noeuds_et_facettes(), construire_noeuds_joints(), and construire_noeuds_uniques().
nb_sommets_element
int Marching_Cubes::nb_sommets_element = -1 protected
Referenced by construire_noeuds_et_facettes(), and remplir_data_marching_cubes().
nb_aretes_element
int Marching_Cubes::nb_aretes_element = -1 protected
Referenced by construire_noeuds_et_facettes(), construire_noeuds_liste_faces(), and remplir_data_marching_cubes().
mcubes_def_aretes
IntTabFT Marching_Cubes::mcubes_def_aretes protected
Referenced by construire_noeuds_et_facettes(), and remplir_data_marching_cubes().
nb_sommets_par_face
int Marching_Cubes::nb_sommets_par_face = -1 protected
Referenced by construire_noeuds_liste_faces(), and remplir_data_marching_cubes().
nb_aretes_faces
int Marching_Cubes::nb_aretes_faces = -1 protected
Referenced by construire_noeuds_liste_faces(), and remplir_data_marching_cubes().
mcubes_def_aretes_faces
IntTabFT Marching_Cubes::mcubes_def_aretes_faces protected
Referenced by construire_noeuds_liste_faces(), and remplir_data_marching_cubes().
nb_sommets_facette
int Marching_Cubes::nb_sommets_facette = -1 protected
Referenced by construire_noeuds_et_facettes(), and remplir_data_marching_cubes().
mcubes_index_facettes
ArrOfIntFT Marching_Cubes::mcubes_index_facettes protected
Referenced by construire_noeuds_et_facettes(), and remplir_data_marching_cubes().
mcubes_facettes
ArrOfIntFT Marching_Cubes::mcubes_facettes protected
Referenced by construire_noeuds_et_facettes(), and remplir_data_marching_cubes().
mcubes_nb_facettes
ArrOfIntFT Marching_Cubes::mcubes_nb_facettes protected
Referenced by construire_noeuds_et_facettes(), and remplir_data_marching_cubes().
renum_virt_loc_
TRUST_Vector< IntTab > Marching_Cubes::renum_virt_loc_ protected
Referenced by remplir_renum_virt_loc(), and renum_sommets_dist_loc().
indice_joint_
ArrOfInt Marching_Cubes::indice_joint_ protected
Referenced by remplir_renum_virt_loc(), and renum_sommets_dist_loc().
last_def_noeud_size
int Marching_Cubes::last_def_noeud_size = 0 mutable protected
Referenced by construire_iso().