TrioCFD: Intersection_Interface_ijk_cell Class Reference
Intersection_Interface_ijk_cell Class Reference
#include <Intersection_Interface_ijk.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
~Intersection_Interface_ijk_cell()
Intersection_Interface_ijk_cell::~Intersection_Interface_ijk_cell ()
Intersection_Interface_ijk_cell()
Intersection_Interface_ijk_cell::Intersection_Interface_ijk_cell () inline
Member Function Documentation
cree_instance()
Objet_U * Intersection_Interface_ijk_cell::cree_instance () static
taille_memoire()
unsigned Intersection_Interface_ijk_cell::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Intersection_Interface_ijk_cell::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Intersection_Interface_ijk_cell::info () static
get_info()
const Type_info * Intersection_Interface_ijk_cell::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Intersection_Interface_ijk.
self_cast() [1/2]
Intersection_Interface_ijk_cell & Intersection_Interface_ijk_cell::self_cast (Objet_U & r) static
self_cast() [2/2]
const Intersection_Interface_ijk_cell & Intersection_Interface_ijk_cell::self_cast (const Objet_U & r) static
printOn()
Sortie & Intersection_Interface_ijk_cell::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Intersection_Interface_ijk.
readOn()
Entree & Intersection_Interface_ijk_cell::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Intersection_Interface_ijk.
initialize()
int Intersection_Interface_ijk_cell::initialize (const Domaine_IJK & splitting, const IJK_Interfaces & interfaces) override virtual
Implements Intersection_Interface_ijk.
References IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::allocate(), Domaine_IJK::ELEM, idiph_ijk_, Intersection_Interface_ijk::interfaces_, Intersection_Interface_ijk::n_diph_, Intersection_Interface_ijk::projected_on_interface_flag_, and Intersection_Interface_ijk::splitting_.
Referenced by IJK_Interfaces::initialize().
operator()() [1/2]
const int & Intersection_Interface_ijk_cell::operator() (int i_diph, int dir) const inline
References ijk_interfaces_.
operator()() [2/2]
const int & Intersection_Interface_ijk_cell::operator() (int i, int j, int k) const inline
References idiph_ijk_.
pos_pure_faces_interf()
const DoubleTab & Intersection_Interface_ijk_cell::pos_pure_faces_interf () const inline
References positions_pure_faces_on_interf_.
dist_pure_faces_interf()
const DoubleTab & Intersection_Interface_ijk_cell::dist_pure_faces_interf () const inline
References dist_pure_faces_to_interf_.
Referenced by Corrige_flux_FT_temperature_subresolution::compute_thermal_fluxes_face_centre(), and Corrige_flux_FT_temperature_subresolution::compute_thermal_fluxes_face_centre_discrete_integral().
get_ijk_pure_face_neighbours()
const int & Intersection_Interface_ijk_cell::get_ijk_pure_face_neighbours (int i_diph, int neighbour) const inline
References ijk_pure_face_neighbours_.
Referenced by Corrige_flux_FT_temperature_subresolution::complete_thermal_fluxes_face_centre(), Corrige_flux_FT_temperature_subresolution::compute_ijk_pure_faces_indices(), Corrige_flux_FT_temperature_subresolution::compute_thermal_fluxes_face_centre(), and Corrige_flux_FT_temperature_subresolution::compute_thermal_fluxes_face_centre_discrete_integral().
get_set_ijk_pure_face_to_correct()
FixedVector< DoubleVect, 3 > & Intersection_Interface_ijk_cell::get_set_ijk_pure_face_to_correct () inline
References ijk_pure_face_to_correct_.
get_nb_diph()
int Intersection_Interface_ijk_cell::get_nb_diph () inline
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), and ijk_interfaces_.
Referenced by Corrige_flux_FT_temperature_subresolution::associate_indices_and_check_subproblems_consistency().
get_nb_faces_to_correct()
int Intersection_Interface_ijk_cell::get_nb_faces_to_correct () inline
References ijk_pure_face_to_correct_.
Referenced by Corrige_flux_FT_temperature_subresolution::compute_ijk_pure_faces_indices(), Corrige_flux_FT_temperature_subresolution::compute_thermal_fluxes_face_centre(), and Corrige_flux_FT_temperature_subresolution::compute_thermal_fluxes_face_centre_discrete_integral().
update_interpolations_cell_centres_on_interface() [1/2]
void Intersection_Interface_ijk_cell::update_interpolations_cell_centres_on_interface ()
References IJK_Interfaces::I(), Intersection_Interface_ijk::interfaces_, and update_interpolations_cell_centres_on_interface().
Referenced by Corrige_flux_FT_temperature_conv::update(), update_interpolations_cell_centres_on_interface(), update_interpolations_cell_centres_on_interface_new(), and Corrige_flux_FT_temperature_subresolution::update_intersections().
update_interpolations_cell_faces_on_interface() [1/2]
void Intersection_Interface_ijk_cell::update_interpolations_cell_faces_on_interface ()
References IJK_Interfaces::I(), Intersection_Interface_ijk::interfaces_, and update_interpolations_cell_faces_on_interface().
Referenced by update_interpolations_cell_faces_on_interface(), update_interpolations_cell_faces_on_interface_new(), and Corrige_flux_FT_temperature_subresolution::update_intersections().
update_interpolations_cell_centres_on_interface_new()
void Intersection_Interface_ijk_cell::update_interpolations_cell_centres_on_interface_new ()
References IJK_Interfaces::In(), Intersection_Interface_ijk::interfaces_, and update_interpolations_cell_centres_on_interface().
update_interpolations_cell_faces_on_interface_new()
void Intersection_Interface_ijk_cell::update_interpolations_cell_faces_on_interface_new ()
References IJK_Interfaces::In(), Intersection_Interface_ijk::interfaces_, and update_interpolations_cell_faces_on_interface().
update_interpolations_cell_centres_on_interface() [2/2]
void Intersection_Interface_ijk_cell::update_interpolations_cell_centres_on_interface (const IJK_Field_double & interfaces)
References calcul_projection_centre_sur_interface_moy(), Intersection_Interface_ijk::dist_to_interf_, ijk_interfaces_, Intersection_Interface_ijk::normal_on_interf_, Intersection_Interface_ijk::positions_on_interf_, and Intersection_Interface_ijk::projected_on_interface_flag_.
update_interpolations_cell_faces_on_interface() [2/2]
void Intersection_Interface_ijk_cell::update_interpolations_cell_faces_on_interface (const IJK_Field_double & interfaces)
References calcul_projection_centre_faces_sur_interface_moy(), compute_face_to_correct(), dist_pure_faces_to_interf_, face_centres_projected_on_interface_flag_, ijk_interfaces_, ijk_pure_face_neighbours_, ijk_pure_face_to_correct_, Intersection_Interface_ijk::normal_on_interf_, and positions_pure_faces_on_interf_.
set_pas_a_jour()
void Intersection_Interface_ijk_cell::set_pas_a_jour () inline override virtual
Reimplemented from Intersection_Interface_ijk.
References face_centres_projected_on_interface_flag_, and Intersection_Interface_ijk::projected_on_interface_flag_.
Referenced by Corrige_flux_FT_temperature_subresolution::clean().
is_a_jour()
bool Intersection_Interface_ijk_cell::is_a_jour () const inline override virtual
Reimplemented from Intersection_Interface_ijk.
References face_centres_projected_on_interface_flag_, and Intersection_Interface_ijk::projected_on_interface_flag_.
calcul_projection_centre_sur_interface_moy()
void Intersection_Interface_ijk_cell::calcul_projection_centre_sur_interface_moy (const IJK_Field_double & indicatrice, DoubleTab & positions, IntTab & indices, DoubleTab & normales_de_la_proj, DoubleTab & distance_centre_interface) protected
References Domaine_IJK::convert_ijk_cell_to_packed(), Intersection_Interface_ijk::distance_point_point_signe(), Domaine_IJK::ELEM, Domaine_IJK::get_coords_of_dof(), Intersection_Interface_ijk::get_mean_interface_cell(), idiph_ijk_, Intersection_Interface_ijk::n_diph_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), Intersection_Interface_ijk::projete_interface(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), and Intersection_Interface_ijk::splitting_.
Referenced by update_interpolations_cell_centres_on_interface().
calcul_projection_centre_faces_sur_interface_moy()
void Intersection_Interface_ijk_cell::calcul_projection_centre_faces_sur_interface_moy (const IJK_Field_double & indicatrice, const IntTab & indices, const DoubleTab & normale_interf, DoubleTab & positions, IntTab & indices_voisins, FixedVector< DoubleVect, 3 > & indices_faces_corrections, DoubleTab & distance_centre_faces_interface) const protected
References Domaine_IJK::convert_ijk_cell_to_packed(), Intersection_Interface_ijk::distance_point_point_signe(), Domaine_IJK::FACES_I, Domaine_IJK::FACES_J, Domaine_IJK::FACES_K, Domaine_IJK::get_coords_of_dof(), Intersection_Interface_ijk::get_mean_interface_cell(), Intersection_Interface_ijk::n_diph_, Intersection_Interface_ijk::projete_interface(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), and Intersection_Interface_ijk::splitting_.
Referenced by update_interpolations_cell_faces_on_interface().
compute_face_to_correct()
void Intersection_Interface_ijk_cell::compute_face_to_correct () protected
References ijk_interfaces_, ijk_pure_face_neighbours_, ijk_pure_face_to_correct_, and Intersection_Interface_ijk::n_diph_.
Referenced by update_interpolations_cell_faces_on_interface().
Member Data Documentation
info_obj
const Type_info Intersection_Interface_ijk_cell::info_obj static
ijk_interfaces_
IntTab Intersection_Interface_ijk_cell::ijk_interfaces_ protected
Referenced by compute_face_to_correct(), get_nb_diph(), operator()(), update_interpolations_cell_centres_on_interface(), and update_interpolations_cell_faces_on_interface().
ijk_pure_face_neighbours_
IntTab Intersection_Interface_ijk_cell::ijk_pure_face_neighbours_ protected
Referenced by compute_face_to_correct(), get_ijk_pure_face_neighbours(), and update_interpolations_cell_faces_on_interface().
ijk_pure_face_to_correct_
FixedVector<DoubleVect, 3> Intersection_Interface_ijk_cell::ijk_pure_face_to_correct_ protected
Referenced by compute_face_to_correct(), get_nb_faces_to_correct(), get_set_ijk_pure_face_to_correct(), and update_interpolations_cell_faces_on_interface().
idiph_ijk_
IJK_Field_int Intersection_Interface_ijk_cell::idiph_ijk_ protected
Referenced by calcul_projection_centre_sur_interface_moy(), initialize(), and operator()().
face_centres_projected_on_interface_flag_
bool Intersection_Interface_ijk_cell::face_centres_projected_on_interface_flag_ = false protected
Referenced by is_a_jour(), set_pas_a_jour(), and update_interpolations_cell_faces_on_interface().
positions_pure_faces_on_interf_
DoubleTab Intersection_Interface_ijk_cell::positions_pure_faces_on_interf_ protected
Referenced by pos_pure_faces_interf(), and update_interpolations_cell_faces_on_interface().
dist_pure_faces_to_interf_
DoubleTab Intersection_Interface_ijk_cell::dist_pure_faces_to_interf_ protected
Referenced by dist_pure_faces_interf(), and update_interpolations_cell_faces_on_interface().