TrioCFD: Operateur_IJK_elem_base_double Class Reference
Operateur_IJK_elem_base_double Class Reference abstract
#include <Operateur_IJK_base.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Operateur_IJK_elem_base_double()
Operateur_IJK_elem_base_double::Operateur_IJK_elem_base_double ()
~Operateur_IJK_elem_base_double()
Operateur_IJK_elem_base_double::~Operateur_IJK_elem_base_double () override
Member Function Documentation
info()
const Type_info * Operateur_IJK_elem_base_double::info () static
get_info()
const Type_info * Operateur_IJK_elem_base_double::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
Reimplemented in Operateur_IJK_elem_conv_base_double, Operateur_IJK_elem_diff_base_double, OpDiffUniformIJKScalar_double, OpDiffUniformIJKScalarCorrection_double, OpDiffIJKScalar_cut_cell_double, OpDiffIJKScalar_double, OpDiffAnisotropicIJKScalar_double, OpDiffVectorialIJKScalar_double, OpDiffVectorialAnisotropicIJKScalar_double, OpDiffStructuralOnlyIJKScalar_double, OpConvDiscQuickIJKScalar_double, OpConvQuickIJKScalar_cut_cell_double, OpConvQuickInterfaceIJKScalar_double, OpConvQuickInterfaceOnefluidIJKScalar_double, OpGradCentre2IJKScalar_double, OpGradFluxCentre2IJKScalar_double, OpGradQuickIJKScalar_double, OpGradFluxQuickIJKScalar_double, OpHessCentre2IJKScalar_double, and OpHessFluxCentre2IJKScalar_double.
self_cast() [1/2]
Operateur_IJK_elem_base_double & Operateur_IJK_elem_base_double::self_cast (Objet_U & r) static
self_cast() [2/2]
const Operateur_IJK_elem_base_double & Operateur_IJK_elem_base_double::self_cast (const Objet_U & r) static
printOn()
Sortie & Operateur_IJK_elem_base_double::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
Reimplemented in Operateur_IJK_elem_conv_base_double, Operateur_IJK_elem_diff_base_double, OpDiffUniformIJKScalar_double, OpDiffUniformIJKScalarCorrection_double, OpDiffIJKScalar_cut_cell_double, OpDiffIJKScalar_double, OpDiffAnisotropicIJKScalar_double, OpDiffVectorialIJKScalar_double, OpDiffVectorialAnisotropicIJKScalar_double, OpDiffStructuralOnlyIJKScalar_double, OpConvDiscQuickIJKScalar_double, OpConvQuickIJKScalar_cut_cell_double, OpConvQuickInterfaceIJKScalar_double, OpConvQuickInterfaceOnefluidIJKScalar_double, OpGradCentre2IJKScalar_double, OpGradFluxCentre2IJKScalar_double, OpGradQuickIJKScalar_double, OpGradFluxQuickIJKScalar_double, OpHessCentre2IJKScalar_double, and OpHessFluxCentre2IJKScalar_double.
readOn()
Entree & Operateur_IJK_elem_base_double::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
Reimplemented in Operateur_IJK_elem_conv_base_double, Operateur_IJK_elem_diff_base_double, OpDiffUniformIJKScalar_double, OpDiffUniformIJKScalarCorrection_double, OpDiffIJKScalar_cut_cell_double, OpDiffIJKScalar_double, OpDiffAnisotropicIJKScalar_double, OpDiffVectorialIJKScalar_double, OpDiffVectorialAnisotropicIJKScalar_double, OpDiffStructuralOnlyIJKScalar_double, OpConvDiscQuickIJKScalar_double, OpConvQuickIJKScalar_cut_cell_double, OpConvQuickInterfaceIJKScalar_double, OpConvQuickInterfaceOnefluidIJKScalar_double, OpGradCentre2IJKScalar_double, OpGradFluxCentre2IJKScalar_double, OpGradQuickIJKScalar_double, OpGradFluxQuickIJKScalar_double, OpHessCentre2IJKScalar_double, and OpHessFluxCentre2IJKScalar_double.
initialize()
virtual void Operateur_IJK_elem_base_double::initialize (const Domaine_IJK & splitting) pure virtual
Implemented in Operateur_IJK_elem_conv_base_double, and Operateur_IJK_elem_diff_base_double.
set_runge_kutta()
void Operateur_IJK_elem_base_double::set_runge_kutta (int rk_step, double dt_tot, IJK_Field_vector3_double & current_fluxes, IJK_Field_vector3_double & RK3_F_fluxes)
References current_fluxes_, dt_tot_, RK3_F_fluxes_, rk_step_, and runge_kutta_flux_correction_.
compute_set()
void Operateur_IJK_elem_base_double::compute_set (IJK_Field_double & dx) virtual
Referenced by Operateur_IJK_elem_conv_base_double::calculer(), and Operateur_IJK_elem_diff_base_double::calculer().
compute_add()
void Operateur_IJK_elem_base_double::compute_add (IJK_Field_double & dx) virtual
Referenced by Operateur_IJK_elem_conv_base_double::ajouter(), and Operateur_IJK_elem_diff_base_double::ajouter().
compute_grad()
void Operateur_IJK_elem_base_double::compute_grad (IJK_Field_vector3_double & dx) virtual
References IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::allocate(), compute_flux_x(), compute_flux_y(), and compute_flux_z().
Referenced by OpGradCentre2IJKScalar_double::calculer_grad(), OpGradQuickIJKScalar_double::calculer_grad(), and OpHessCentre2IJKScalar_double::calculer_hess().
compute_grad_x()
void Operateur_IJK_elem_base_double::compute_grad_x (IJK_Field_double & dx) virtual
References IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::allocate(), compute_flux_x(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), and IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ref_ij().
Referenced by OpGradCentre2IJKScalar_double::calculer_grad_x(), OpGradQuickIJKScalar_double::calculer_grad_x(), and OpHessCentre2IJKScalar_double::calculer_hess_xx().
compute_grad_y()
void Operateur_IJK_elem_base_double::compute_grad_y (IJK_Field_double & dx) virtual
References IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::allocate(), compute_flux_y(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), and IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ref_ij().
Referenced by OpGradCentre2IJKScalar_double::calculer_grad_y(), OpGradQuickIJKScalar_double::calculer_grad_y(), and OpHessCentre2IJKScalar_double::calculer_hess_yy().
compute_grad_z()
void Operateur_IJK_elem_base_double::compute_grad_z (IJK_Field_double & dx) virtual
References IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::allocate(), compute_flux_z(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), and IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk().
Referenced by OpGradCentre2IJKScalar_double::calculer_grad_z(), OpGradQuickIJKScalar_double::calculer_grad_z(), and OpHessCentre2IJKScalar_double::calculer_hess_zz().
Operator_IJK_div()
void Operateur_IJK_elem_base_double::Operator_IJK_div (const IJK_Field_local_double & flux_x, const IJK_Field_local_double & flux_y, const IJK_Field_local_double & flux_zmin, const IJK_Field_local_double & flux_zmax, IJK_Field_double & resu, int k_layer, bool add) protected virtual
Reimplemented in OpDiffIJKScalar_cut_cell_double, and OpConvQuickIJKScalar_cut_cell_double.
References ConstIJK_ptr< _TYPE_, _TYPE_ARRAY_ >::get_center_right(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), and Simd_template< _TYPE_ >::size().
Referenced by OpDiffIJKScalar_cut_cell_double::Operator_IJK_div(), and OpConvQuickIJKScalar_cut_cell_double::Operator_IJK_div().
correct_flux()
void Operateur_IJK_elem_base_double::correct_flux (IJK_Field_local_double *const flux, const int k_layer, const int dir) protected virtual
Reimplemented in OpConvQuickInterfaceIJKScalar_double, and OpConvQuickInterfaceOnefluidIJKScalar_double.
References current_fluxes_, dt_tot_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), RK3_F_fluxes_, rk_step_, and runge_kutta_flux_correction_.
correct_flux_spherical()
virtual void Operateur_IJK_elem_base_double::correct_flux_spherical (Simd_double & a, Simd_double & b, const int & i, const int & j, int k_layer, int dir) inline protected virtual
Reimplemented in OpConvQuickInterfaceIJKScalar_double.
compute_flux_x()
virtual void Operateur_IJK_elem_base_double::compute_flux_x (IJK_Field_local_double & resu, const int k_layer) protected pure virtual
Implemented in OpConvCentre2IJKScalar_double, OpConvQuickIJKScalar_double, Operateur_IJK_elem_diff_base_double, OpConvDiscQuickIJKScalar_double, and OpConvQuickIJKScalar_cut_cell_double.
Referenced by compute_grad(), and compute_grad_x().
compute_flux_y()
virtual void Operateur_IJK_elem_base_double::compute_flux_y (IJK_Field_local_double & resu, const int k_layer) protected pure virtual
Implemented in OpConvCentre2IJKScalar_double, OpConvQuickIJKScalar_double, Operateur_IJK_elem_diff_base_double, OpConvDiscQuickIJKScalar_double, and OpConvQuickIJKScalar_cut_cell_double.
Referenced by compute_grad(), and compute_grad_y().
compute_flux_z()
virtual void Operateur_IJK_elem_base_double::compute_flux_z (IJK_Field_local_double & resu, const int k_layer) protected pure virtual
Implemented in OpConvCentre2IJKScalar_double, OpConvQuickIJKScalar_double, Operateur_IJK_elem_diff_base_double, OpConvDiscQuickIJKScalar_double, and OpConvQuickIJKScalar_cut_cell_double.
Referenced by compute_grad(), and compute_grad_z().
compute_flux_local_x()
virtual double Operateur_IJK_elem_base_double::compute_flux_local_x (int i, int j, int k) inline protected virtual
Reimplemented in Operateur_IJK_elem_diff_base_double.
compute_flux_local_y()
virtual double Operateur_IJK_elem_base_double::compute_flux_local_y (int i, int j, int k) inline protected virtual
Reimplemented in Operateur_IJK_elem_diff_base_double.
compute_flux_local_z()
virtual double Operateur_IJK_elem_base_double::compute_flux_local_z (int i, int j, int k) inline protected virtual
Reimplemented in Operateur_IJK_elem_diff_base_double.
Member Data Documentation
info_obj
const Type_info Operateur_IJK_elem_base_double::info_obj static
runge_kutta_flux_correction_
bool Operateur_IJK_elem_base_double::runge_kutta_flux_correction_ = false protected
Referenced by correct_flux(), set_runge_kutta(), OpConvQuickIJKScalar_cut_cell_double::set_runge_kutta(), and OpDiffIJKScalar_cut_cell_double::set_runge_kutta().
rk_step_
int Operateur_IJK_elem_base_double::rk_step_ = -1 protected
Referenced by correct_flux(), set_runge_kutta(), OpConvQuickIJKScalar_cut_cell_double::set_runge_kutta(), and OpDiffIJKScalar_cut_cell_double::set_runge_kutta().
dt_tot_
double Operateur_IJK_elem_base_double::dt_tot_ = 0. protected
Referenced by correct_flux(), set_runge_kutta(), OpConvQuickIJKScalar_cut_cell_double::set_runge_kutta(), and OpDiffIJKScalar_cut_cell_double::set_runge_kutta().
current_fluxes_
IJK_Field_vector3_double* Operateur_IJK_elem_base_double::current_fluxes_ protected
Referenced by correct_flux(), set_runge_kutta(), OpConvQuickIJKScalar_cut_cell_double::set_runge_kutta(), and OpDiffIJKScalar_cut_cell_double::set_runge_kutta().
RK3_F_fluxes_
IJK_Field_vector3_double* Operateur_IJK_elem_base_double::RK3_F_fluxes_ protected
Referenced by correct_flux(), set_runge_kutta(), OpConvQuickIJKScalar_cut_cell_double::set_runge_kutta(), and OpDiffIJKScalar_cut_cell_double::set_runge_kutta().