TrioCFD: Domaine_VF_inst Class Reference
Domaine_VF_inst Class Reference
#include <Domaine_VF_inst.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Domaine_VF
void build_map_mc_Cmesh (const bool with_faces) override
void build_mc_dual_mesh () const
void build_mc_face_mesh () const
void construire_face_virt_pe_num ()
int elem_faces (int i, int j) const
int face_voisins (int num_face, int i) const
const Type_info * get_info () const override
void init_dist_paroi_globale (const Conds_lim &conds_lim) override
int nb_faces_bord () const
int nb_faces_bord_tot () const
int nb_faces_internes () const
int nb_faces_tot () const
int nb_som_face () const
int premiere_face_bord () const
int premiere_face_int () const
Public Member Functions inherited from Domaine_dis_base
void associer_domaine (const Domaine &)
const Domaine & domaine () const
void ecrire_noms_bords (Sortie &) const
virtual IntTab & face_sommets ()
const Frontiere_dis_base & frontiere_dis (const Nom &) const
const Type_info * get_info () const override
int nombre_de_sous_domaines_dis () const
int rang_frontiere (const Nom &) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
 Classe instanciable qui derive de Domaine_VF. Cette classe ne sait rien faire !!!!
 Elle permet juste d'appeler des methodes de type Champ_Inc_base::affecter avec un domaine_dis contenant une reference a un domaine.
Constructor & Destructor Documentation
Domaine_VF_inst()
Domaine_VF_inst::Domaine_VF_inst ()
~Domaine_VF_inst()
Domaine_VF_inst::~Domaine_VF_inst ()
Member Function Documentation
cree_instance()
Objet_U * Domaine_VF_inst::cree_instance () static
taille_memoire()
unsigned Domaine_VF_inst::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Domaine_VF_inst::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Domaine_VF_inst::info () static
get_info()
const Type_info * Domaine_VF_inst::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Domaine_VF.
self_cast() [1/2]
Domaine_VF_inst & Domaine_VF_inst::self_cast (Objet_U & r) static
self_cast() [2/2]
const Domaine_VF_inst & Domaine_VF_inst::self_cast (const Objet_U & r) static
printOn()
Sortie & Domaine_VF_inst::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Domaine_VF.
References Domaine_VF::printOn().
readOn()
Entree & Domaine_VF_inst::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Domaine_VF.
References Domaine_VF::readOn().
face_normales() [1/3]
double Domaine_VF_inst::face_normales (int , int) const inline override virtual
Reimplemented from Domaine_VF.
References Objet_U::que_suis_je().
face_normales() [2/3]
const DoubleTab & Domaine_VF_inst::face_normales () const inline override virtual
Reimplemented from Domaine_VF.
References Objet_U::que_suis_je().
face_normales() [3/3]
DoubleTab & Domaine_VF_inst::face_normales () inline override virtual
Reimplemented from Domaine_VF.
References Objet_U::que_suis_je().
Member Data Documentation
info_obj
const Type_info Domaine_VF_inst::info_obj static