TrioCFD: LireMED_32_64< _SIZE_ > Class Template Reference
LireMED_32_64< _SIZE_ > Class Template Reference
#include <LireMED.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Interprete_geometrique_base_32_64< _SIZE_ >
const Type_info * get_info () const override
void mettre_a_jour_sous_domaine (Domaine_t &domaine, int_t &elem, int_t num_premier_elem, int_t nb_elem) const
Public Member Functions inherited from Interprete
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
void finalize_sommets (const DoubleTab_t &sommets2, DoubleTab_t &sommets) const
Sortie & printOn (Sortie &x) const override
void read_boundaries (BigArrOfInt_ &familles, IntTab_t &all_faces_bords)
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Interprete
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Interprete
static Objet_U & objet (const Nom &)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Member Typedef Documentation
int_t
template<typename _SIZE_ > using LireMED_32_64< _SIZE_ >::int_t = _SIZE_
ArrOfInt_t
template<typename _SIZE_ > using LireMED_32_64< _SIZE_ >::ArrOfInt_t = ArrOfInt_T<_SIZE_>
IntTab_t
template<typename _SIZE_ > using LireMED_32_64< _SIZE_ >::IntTab_t = IntTab_T<_SIZE_>
BigArrOfInt_
template<typename _SIZE_ > using LireMED_32_64< _SIZE_ >::BigArrOfInt_ = TRUSTArray<int, _SIZE_>
DoubleTab_t
template<typename _SIZE_ > using LireMED_32_64< _SIZE_ >::DoubleTab_t = DoubleTab_T<_SIZE_>
Domaine_t
template<typename _SIZE_ > using LireMED_32_64< _SIZE_ >::Domaine_t = Domaine_32_64<_SIZE_>
Elem_geom_t
template<typename _SIZE_ > using LireMED_32_64< _SIZE_ >::Elem_geom_t = TRUST_Deriv< Elem_geom_base_32_64<_SIZE_> >
Constructor & Destructor Documentation
LireMED_32_64() [1/2]
template<typename _T_ > LireMED_32_64< _T_ >::LireMED_32_64
~LireMED_32_64()
template<typename _T_ > LireMED_32_64< _T_ >::~LireMED_32_64
LireMED_32_64() [2/2]
template<typename _SIZE_ > LireMED_32_64< _SIZE_ >::LireMED_32_64 (const Nom & file_name, const Nom & mesh_name)
Member Function Documentation
cree_instance()
template<typename _T_ > Objet_U * LireMED_32_64< _T_ >::cree_instance static
taille_memoire()
template<typename _T_ > unsigned LireMED_32_64< _T_ >::taille_memoire override virtual
Implements Objet_U.
Reimplemented in Read_MED_For_Testing_No_Verify_Option.
duplique()
template<typename _T_ > int LireMED_32_64< _T_ >::duplique override virtual
Implements Objet_U.
Reimplemented in Read_MED_For_Testing_No_Verify_Option.
info()
template<typename _T_ > const Type_info * LireMED_32_64< _T_ >::info static
get_info()
template<typename _T_ > const Type_info * LireMED_32_64< _T_ >::get_info override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Interprete_geometrique_base_32_64< _SIZE_ >.
Reimplemented in Read_MED_For_Testing_No_Verify_Option.
self_cast() [1/2]
template<typename _T_ > LireMED_32_64< _T_ > & LireMED_32_64< _T_ >::self_cast (Objet_U & r) static
self_cast() [2/2]
template<typename _T_ > const LireMED_32_64< _T_ > & LireMED_32_64< _T_ >::self_cast (const Objet_U & r) static
printOn()
template<typename _SIZE_ > Sortie & LireMED_32_64< _SIZE_ >::printOn (Sortie & os) const override protected virtual
Simple appel a: Interprete::printOn(Sortie&)
Parameters
(Sortie& os) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Interprete_geometrique_base_32_64< _SIZE_ >.
Reimplemented in Read_MED_For_Testing_No_Verify_Option.
References Interprete::printOn().
Referenced by Read_MED_For_Testing_No_Verify_Option::printOn().
readOn()
template<typename _SIZE_ > Entree & LireMED_32_64< _SIZE_ >::readOn (Entree & is) override protected virtual
Simple appel a: Interprete::readOn(Entree&)
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Interprete_geometrique_base_32_64< _SIZE_ >.
Reimplemented in Read_MED_For_Testing_No_Verify_Option.
References Interprete::readOn().
Referenced by Read_MED_For_Testing_No_Verify_Option::readOn().
interpreter_()
template<typename _SIZE_ > Entree & LireMED_32_64< _SIZE_ >::interpreter_ (Entree & is) override virtual
Implements Interprete_geometrique_base_32_64< _SIZE_ >.
Reimplemented in Read_MED_For_Testing_No_Verify_Option.
References Param::ajouter(), Param::ajouter_flag(), Process::exit(), Param::lire_avec_accolades(), Objet_U::nom_du_cas(), Nom::nom_me(), Nom::prefix(), and Param::REQUIRED.
Referenced by Read_MED_For_Testing_No_Verify_Option::interpreter_().
lire_geom()
template<typename _SIZE_ > void LireMED_32_64< _SIZE_ >::lire_geom (bool subDom = true)
References Objet_U::dimension, Process::exit(), Scatter::init_sequential_domain(), Domaine_base::le_nom(), Domaine_32_64< _SIZE_ >::les_elems(), Domaine_32_64< _SIZE_ >::les_sommets(), NettoieNoeuds_32_64< _SIZE_ >::nettoie(), Process::nproc(), Objet_U::que_suis_je(), Domaine_32_64< _SIZE_ >::reordonner(), Domaine_32_64< _SIZE_ >::set_mc_mesh_ready(), Domaine_32_64< _SIZE_ >::type_elem(), Domaine_32_64< _SIZE_ >::typer(), Scatter::uninit_sequential_domain(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by ScatterMED::lire_domaine(), Champ_Fonc_MED::readOn(), and Pb_MED::readOn().
retrieve_MC_objects()
template<typename _SIZE_ > void LireMED_32_64< _SIZE_ >::retrieve_MC_objects ()
Referenced by Champ_Fonc_MED::readOn().
type_medcoupling_to_type_geo_trio()
template<typename _SIZE_ > Nom LireMED_32_64< _SIZE_ >::type_medcoupling_to_type_geo_trio (int type_cell, bool cell_from_boundary) const protected
prepare_som_and_elem()
template<typename _SIZE_ > void LireMED_32_64< _SIZE_ >::prepare_som_and_elem (DoubleTab_t & sommets, IntTab_t & les_elems) protected
finalize_sommets()
template<typename _SIZE_ > void LireMED_32_64< _SIZE_ >::finalize_sommets (const DoubleTab_t & sommets2, DoubleTab_t & sommets) const protected
renvoie le type trio a partir du type medocoupling : http://docs.salome-platform.org/6/gui/MED/MEDLoader_8cxx.html
Load the mesh from the MED file as a MEDCouplingUMesh, and name it as the domain.
Fills in coords and connectivity array from the MC data.
Fills in sommets in the Domaine, potentially reducing the dimension (flat 3D -> 2D) by discarding a useless dimension (a flat 2D surface in a 3D space dim for example) TODO Fixme Adrien : rewrite this in MC style : buildUnique etc ...
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Process::exit(), Objet_U::precision_geom, and TRUSTTab< _TYPE_, _SIZE_ >::resize().
write_sub_dom_datasets()
template<typename _SIZE_ > void LireMED_32_64< _SIZE_ >::write_sub_dom_datasets protected
References Process::exit(), and Process::je_suis_maitre().
read_boundaries()
template<typename _SIZE_ > void LireMED_32_64< _SIZE_ >::read_boundaries (BigArrOfInt_ & fac_grp_id, IntTab_t & all_faces_bords) protected
Handles the boundaries found in the MED file.
Get the -1 level mesh, and extract boundaries by reading element groups on this mesh.
References Objet_U::dimension, Process::exit(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), and TRUSTArray< _TYPE_, _SIZE_ >::resize_array().
fill_frontieres()
template<typename _SIZE_ > void LireMED_32_64< _SIZE_ >::fill_frontieres (const BigArrOfInt_ & familles, const IntTab_t & all_faces_bords) protected
Fills in all the information relative to Joints, Raccords and Frontiere.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_int(), Domaine_32_64< _SIZE_ >::faces_bord(), Domaine_32_64< _SIZE_ >::faces_joint(), Domaine_32_64< _SIZE_ >::faces_raccord(), Domaine_32_64< _SIZE_ >::groupes_faces(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Noms::search(), and TRUST_List< _CLASSE_ >::vide().
info_obj() [1/2]
const Type_info LireMED_32_64< int >::info_obj ("Lire_MED" , LireMED_32_64< int >::cree_instance , 1 , LireMED_32_64bases< int >)
info_obj() [2/2]
const Type_info LireMED_32_64< trustIdType >::info_obj ("Lire_MED" "_64" , LireMED_32_64< trustIdType >::cree_instance , 1 , LireMED_32_64bases< trustIdType >)
Member Data Documentation
info_obj
template<typename _SIZE_ > const Type_info LireMED_32_64< _SIZE_ >::info_obj static
nom_fichier_
template<typename _SIZE_ > Nom LireMED_32_64< _SIZE_ >::nom_fichier_ protected
Name of the MED file to read.
nom_mesh_
template<typename _SIZE_ > Nom LireMED_32_64< _SIZE_ >::nom_mesh_ = "--any--" protected
Name of the mesh in the MED file to read.
axi1d_
template<typename _SIZE_ > bool LireMED_32_64< _SIZE_ >::axi1d_ = false protected
Are we in Axi1D.
convertAllToPoly_
template<typename _SIZE_ > bool LireMED_32_64< _SIZE_ >::convertAllToPoly_ = false protected
Should the mesh be converted to polygons/polyedrons.
isVEFForce_
template<typename _SIZE_ > bool LireMED_32_64< _SIZE_ >::isVEFForce_ = false protected
Should we force element type to be VEF compatible.
space_dim_
template<typename _SIZE_ > int LireMED_32_64< _SIZE_ >::space_dim_ = -1 protected
Space dimension read in the MED file.
type_elem_
template<typename _SIZE_ > Elem_geom_t LireMED_32_64< _SIZE_ >::type_elem_ protected
Highest dimension element type.
type_face_
template<typename _SIZE_ > Nom LireMED_32_64< _SIZE_ >::type_face_ protected
Boundary element type.
noms_bords_
template<typename _SIZE_ > Noms LireMED_32_64< _SIZE_ >::noms_bords_ protected
Names of the boundaries.
exclude_grps_
template<typename _SIZE_ > Noms LireMED_32_64< _SIZE_ >::exclude_grps_ protected
Names of the (face) groups to skip when reading the file.
internal_face_grps_
template<typename _SIZE_ > Noms LireMED_32_64< _SIZE_ >::internal_face_grps_ protected
Names of the internals face groups to read in the file.