TrioCFD: CoolProp_to_TRUST Class Reference
CoolProp_to_TRUST Class Reference
#include <CoolProp_to_TRUST.h>
Detailed Description
Interface commune pour TRUST et ses baltiks qui permet appeler les methodes de la lib CoolProp Methods disponibles en temperature et enthalpie, egalement pour la saturation
Constructor & Destructor Documentation
~CoolProp_to_TRUST()
CoolProp_to_TRUST::~CoolProp_to_TRUST () override default
Member Function Documentation
verify_phase()
void CoolProp_to_TRUST::verify_phase (const Motcle & phase_name) override virtual
Reimplemented from TPPI.
References Process::exit().
Referenced by set_phase().
set_phase()
void CoolProp_to_TRUST::set_phase (const Motcle & phase_name) override virtual
Reimplemented from TPPI.
References verify_phase().
set_path_refprop()
void CoolProp_to_TRUST::set_path_refprop () override virtual
Reimplemented from TPPI.
References Process::exit().
tppi_get_p_min()
double CoolProp_to_TRUST::tppi_get_p_min () const final override virtual
Implements TPPI.
tppi_get_p_max()
double CoolProp_to_TRUST::tppi_get_p_max () const final override virtual
Implements TPPI.
tppi_get_h_min()
double CoolProp_to_TRUST::tppi_get_h_min () const final override virtual
Implements TPPI.
References TPPI::tppi_get_h_pT().
tppi_get_h_max()
double CoolProp_to_TRUST::tppi_get_h_max () const final override virtual
Implements TPPI.
References TPPI::tppi_get_h_pT().
tppi_get_T_min()
double CoolProp_to_TRUST::tppi_get_T_min () const final override virtual
Implements TPPI.
tppi_get_T_max()
double CoolProp_to_TRUST::tppi_get_T_max () const final override virtual
Implements TPPI.
tppi_get_rho_min()
double CoolProp_to_TRUST::tppi_get_rho_min () const final override virtual
Implements TPPI.
tppi_get_rho_max()
double CoolProp_to_TRUST::tppi_get_rho_max () const final override virtual
Implements TPPI.
tppi_get_p_crit()
double CoolProp_to_TRUST::tppi_get_p_crit () const final override virtual
Implements TPPI.
tppi_get_h_crit()
double CoolProp_to_TRUST::tppi_get_h_crit () const final override virtual
Implements TPPI.
tppi_get_T_crit()
double CoolProp_to_TRUST::tppi_get_T_crit () const final override virtual
Implements TPPI.
tppi_get_rho_crit()
double CoolProp_to_TRUST::tppi_get_rho_crit () const final override virtual
Implements TPPI.