TrioCFD: OpConvQuickSharpIJK_double Class Reference
OpConvQuickSharpIJK_double Class Reference
#include <OpConvQuickSharpIJK.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Operateur_IJK_faces_conv_base_double
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Operateur_IJK_faces_conv_base_double
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
OpConvQuickSharpIJK_double()
OpConvQuickSharpIJK_double::OpConvQuickSharpIJK_double ()
~OpConvQuickSharpIJK_double()
OpConvQuickSharpIJK_double::~OpConvQuickSharpIJK_double ()
Member Function Documentation
cree_instance()
Objet_U * OpConvQuickSharpIJK_double::cree_instance () static
taille_memoire()
unsigned OpConvQuickSharpIJK_double::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int OpConvQuickSharpIJK_double::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * OpConvQuickSharpIJK_double::info () static
get_info()
const Type_info * OpConvQuickSharpIJK_double::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
OpConvQuickSharpIJK_double & OpConvQuickSharpIJK_double::self_cast (Objet_U & r) static
self_cast() [2/2]
const OpConvQuickSharpIJK_double & OpConvQuickSharpIJK_double::self_cast (const Objet_U & r) static
printOn()
Sortie & OpConvQuickSharpIJK_double::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
readOn()
Entree & OpConvQuickSharpIJK_double::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
initialize()
void OpConvQuickSharpIJK_double::initialize (const Domaine_IJK & splitting) override virtual
Reimplemented from Operateur_IJK_faces_conv_base_double.
References delta_x_, delta_y_, delta_z_, Domaine_IJK::get_constant_delta(), and Operateur_IJK_faces_conv_base_double::initialize().
Referenced by DNS_QC_double::run().
compute_flux_x_vx()
void OpConvQuickSharpIJK_double::compute_flux_x_vx (IJK_Field_local_double & resu, const int k_layer) inline override protected virtual
Implements Operateur_IJK_faces_base_double.
compute_flux_x_vy()
void OpConvQuickSharpIJK_double::compute_flux_x_vy (IJK_Field_local_double & resu, const int k_layer) inline override protected virtual
Implements Operateur_IJK_faces_base_double.
compute_flux_x_vz()
void OpConvQuickSharpIJK_double::compute_flux_x_vz (IJK_Field_local_double & resu, const int k_layer) inline override protected virtual
Implements Operateur_IJK_faces_base_double.
compute_flux_y_vx()
void OpConvQuickSharpIJK_double::compute_flux_y_vx (IJK_Field_local_double & resu, const int k_layer) inline override protected virtual
Implements Operateur_IJK_faces_base_double.
compute_flux_y_vy()
void OpConvQuickSharpIJK_double::compute_flux_y_vy (IJK_Field_local_double & resu, const int k_layer) inline override protected virtual
Implements Operateur_IJK_faces_base_double.
compute_flux_y_vz()
void OpConvQuickSharpIJK_double::compute_flux_y_vz (IJK_Field_local_double & resu, const int k_layer) inline override protected virtual
Implements Operateur_IJK_faces_base_double.
compute_flux_z_vx()
void OpConvQuickSharpIJK_double::compute_flux_z_vx (IJK_Field_local_double & resu, const int k_layer) inline override protected virtual
Implements Operateur_IJK_faces_base_double.
compute_flux_z_vy()
void OpConvQuickSharpIJK_double::compute_flux_z_vy (IJK_Field_local_double & resu, const int k_layer) inline override protected virtual
Implements Operateur_IJK_faces_base_double.
compute_flux_z_vz()
void OpConvQuickSharpIJK_double::compute_flux_z_vz (IJK_Field_local_double & resu, const int k_layer) inline override protected virtual
Implements Operateur_IJK_faces_base_double.
Member Data Documentation
info_obj
const Type_info OpConvQuickSharpIJK_double::info_obj static
delta_x_
double OpConvQuickSharpIJK_double::delta_x_ = 0 protected
Referenced by initialize().
delta_y_
double OpConvQuickSharpIJK_double::delta_y_ = 0 protected
Referenced by initialize().
delta_z_
double OpConvQuickSharpIJK_double::delta_z_ = 0 protected
Referenced by initialize().