TrioCFD: Calcul_Production_K_VDF Class Reference
Calcul_Production_K_VDF Class Reference
#include <Calcul_Production_K_VDF.h>
Constructor & Destructor Documentation
Calcul_Production_K_VDF()
Calcul_Production_K_VDF::Calcul_Production_K_VDF () inline protected
Member Function Documentation
calculer_terme_production_K()
DoubleVect & Calcul_Production_K_VDF::calculer_terme_production_K (const Domaine_VDF & domaine_VDF, const Domaine_Cl_VDF & domaine_Cl_VDF, DoubleVect & S, const DoubleTab & K_eps, const DoubleTab & vitesse, const Champ_Face_VDF & vit, const DoubleTab & visco_turb) const protected
References Champ_Face_VDF::calcul_S_barre_sans_contrib_paroi(), Domaine_VDF::dim_elem(), Objet_U::dimension, Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), Domaine_32_64< _SIZE_ >::nb_elem(), Domaine_VDF::orientation(), and Debog::verifier().
Referenced by Source_Transport_Fluctuation_Temperature_VDF_Elem::ajouter(), Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::ajouter(), Source_Transport_Fluctuation_Temperature_W_VDF_Elem::ajouter(), Source_Transport_Bas_Reynolds_VDF_Elem_base::ajouter_blocs(), Source_Transport_K_Eps_Bas_Reynolds_aniso_therm_concen_VDF_Elem::ajouter_blocs(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_VDF_Elem::ajouter_blocs(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_QC_VDF_Elem::ajouter_blocs(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_W_VDF_Elem::ajouter_blocs(), and Source_Transport_K_KEps_VDF_Elem::ajouter_blocs().
calculer_terme_production_K_for_komega()
DoubleVect & Calcul_Production_K_VDF::calculer_terme_production_K_for_komega (const Domaine_VDF & domaine_VDF, const Domaine_Cl_VDF & domaine_Cl_VDF, DoubleVect & S, const DoubleTab & K_Omega, const DoubleTab & vitesse, const Champ_Face_VDF & vit, const DoubleTab & visco_turb) const protected
References Champ_Face_VDF::calcul_S_barre(), Domaine_VDF::dim_elem(), Objet_U::dimension, Domaine_VF::elem_faces(), Domaine_dis_base::nb_elem(), Domaine_VDF::orientation(), and Debog::verifier().
calculer_terme_production_K_Axi()
DoubleVect & Calcul_Production_K_VDF::calculer_terme_production_K_Axi (const Domaine_VDF & domaine_VDF, const Champ_Face_VDF & vitesse, DoubleVect & P, const DoubleTab & K_Eps, const DoubleTab & visco_turb) const protected
References Objet_U::dimension, TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_VF::face_voisins(), Domaine_VDF::nb_aretes(), Domaine_VDF::nb_aretes_bord(), Domaine_dis_base::nb_elem(), Domaine_VDF::premiere_arete_bord(), Domaine_VDF::premiere_arete_interne(), Domaine_VDF::Qdm(), Champ_Face_VDF::tau_croises(), and Champ_Face_VDF::tau_diag().
Referenced by Source_Transport_Fluctuation_Temperature_VDF_Elem::ajouter(), Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::ajouter(), Source_Transport_Fluctuation_Temperature_W_VDF_Elem::ajouter(), Source_Transport_Bas_Reynolds_VDF_Elem_base::ajouter_blocs(), Source_Transport_K_Eps_Bas_Reynolds_aniso_therm_concen_VDF_Elem::ajouter_blocs(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_VDF_Elem::ajouter_blocs(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_W_VDF_Elem::ajouter_blocs(), and Source_Transport_K_KEps_VDF_Elem::ajouter_blocs().
calculer_terme_production_K_BiK()
DoubleVect & Calcul_Production_K_VDF::calculer_terme_production_K_BiK (const Domaine_VDF & domaine_VDF, const Domaine_Cl_VDF & domaine_Cl_VDF, DoubleVect & S, const DoubleTab & K, const DoubleTab & vitesse, const Champ_Face_VDF & vit, const DoubleTab & visco_turb) const protected
References Champ_Face_VDF::calcul_S_barre_sans_contrib_paroi(), Domaine_VDF::dim_elem(), Objet_U::dimension, Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), Domaine_32_64< _SIZE_ >::nb_elem(), Domaine_VDF::orientation(), and Debog::verifier().
Referenced by Source_Transport_K_Realisable_VDF_Elem::ajouter_blocs().
calculer_terme_production_K_BiK_Axi()
DoubleVect & Calcul_Production_K_VDF::calculer_terme_production_K_BiK_Axi (const Domaine_VDF & domaine_VDF, const Champ_Face_VDF & vitesse, DoubleVect & P, const DoubleTab & K, const DoubleTab & visco_turb) const protected
References Objet_U::dimension, TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_VF::face_voisins(), Domaine_VDF::nb_aretes(), Domaine_VDF::nb_aretes_bord(), Domaine_dis_base::nb_elem(), Domaine_VDF::premiere_arete_bord(), Domaine_VDF::premiere_arete_interne(), Domaine_VDF::Qdm(), Champ_Face_VDF::tau_croises(), and Champ_Face_VDF::tau_diag().
Referenced by Source_Transport_K_Realisable_VDF_Elem::ajouter_blocs().
calculer_terme_destruction_K() [1/3]
DoubleVect & Calcul_Production_K_VDF::calculer_terme_destruction_K (const Domaine_VDF & domaine_VDF, const Domaine_Cl_VDF & zcl_VDF, DoubleVect & G, const DoubleTab & temper, const DoubleTab & alpha_turb, const DoubleTab & beta, const DoubleVect & gravite) const protected
References calculer_u_teta(), Objet_U::dimension, Domaine_dis_base::domaine(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_VF::elem_faces(), MorEqn::equation(), Equation_base::milieu(), Domaine_dis_base::nb_elem(), Domaine_VF::nb_faces(), Domaine_32_64< _SIZE_ >::nb_faces_elem(), and Milieu_base::porosite_face().
Referenced by Source_Transport_Fluctuation_Temperature_W_VDF_Elem::ajouter(), Source_Transport_VDF_Elem_base::ajouter_anisotherme(), Source_Transport_VDF_Elem_base::ajouter_anisotherme_concen(), Source_Transport_K_Eps_Bas_Reynolds_aniso_therm_concen_VDF_Elem::ajouter_blocs(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_VDF_Elem::ajouter_blocs(), and Source_Transport_VDF_Elem_base::ajouter_concen().
calculer_terme_destruction_K() [2/3]
DoubleVect & Calcul_Production_K_VDF::calculer_terme_destruction_K (const Domaine_VDF & domaine_VDF, const Domaine_Cl_VDF & zcl_VDF, DoubleVect & G, const DoubleTab & temper, const DoubleTab & alpha_turb, double beta, const DoubleVect & gravite) const protected
References calculer_u_teta(), Objet_U::dimension, Domaine_dis_base::domaine(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_VF::elem_faces(), MorEqn::equation(), Equation_base::milieu(), Domaine_dis_base::nb_elem(), Domaine_VF::nb_faces(), Domaine_32_64< _SIZE_ >::nb_faces_elem(), and Milieu_base::porosite_face().
calculer_terme_destruction_K() [3/3]
DoubleVect & Calcul_Production_K_VDF::calculer_terme_destruction_K (const Domaine_VDF & domaine_VDF, const Domaine_Cl_VDF & zcl_VDF, DoubleVect & G, const DoubleTab & temper, const DoubleTab & alpha_turb, const DoubleVect & beta, const DoubleVect & gravite, int nb_consti) const protected
References calculer_u_conc(), Objet_U::dimension, Domaine_dis_base::domaine(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_VF::elem_faces(), MorEqn::equation(), Equation_base::milieu(), Domaine_dis_base::nb_elem(), Domaine_VF::nb_faces(), Domaine_32_64< _SIZE_ >::nb_faces_elem(), and Milieu_base::porosite_face().
mettre_a_jour()
void Calcul_Production_K_VDF::mettre_a_jour (double) inline protected
Referenced by Source_Transport_K_Omega_VDF_Elem_base::mettre_a_jour(), Source_Transport_VDF_Elem_base::mettre_a_jour(), Source_Transport_Fluctuation_Temperature_VDF_Elem::mettre_a_jour(), Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::mettre_a_jour(), and Source_Transport_Fluctuation_Temperature_W_VDF_Elem::mettre_a_jour().
calculer_u_teta()
DoubleTab & Calcul_Production_K_VDF::calculer_u_teta (const Domaine_VDF & domaine_VDF, const Domaine_Cl_VDF & zcl_VDF, const DoubleTab & temper, const DoubleTab & alpha_turb, DoubleTab & u_teta) const protected
References Objet_U::axi, Domaine_VDF::dist_norm(), Domaine_VDF::dist_norm_axi(), Domaine_VDF::dist_norm_bord(), Domaine_VDF::dist_norm_bord_axi(), Domaine_VF::face_voisins(), Domaine_Cl_dis_base::les_conditions_limites(), Domaine_VF::nb_faces(), Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), Domaine_VF::premiere_face_int(), Dirichlet::val_imp(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::ajouter(), Source_Transport_Fluctuation_Temperature_W_VDF_Elem::ajouter(), and calculer_terme_destruction_K().
calculer_u_conc()
DoubleTab & Calcul_Production_K_VDF::calculer_u_conc (const Domaine_VDF & domaine_VDF, const Domaine_Cl_VDF & zcl_VDF, const DoubleTab & conc, const DoubleTab & alpha_turb, DoubleTab & u_conc, int nb_consti) const protected
References Objet_U::axi, Domaine_VDF::dist_norm(), Domaine_VDF::dist_norm_axi(), Domaine_VDF::dist_norm_bord(), Domaine_VDF::dist_norm_bord_axi(), Domaine_VF::face_voisins(), Domaine_Cl_dis_base::les_conditions_limites(), Domaine_VF::nb_faces(), Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), Domaine_VF::premiere_face_int(), Dirichlet::val_imp(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by calculer_terme_destruction_K().