TrioCFD: Loi_paroi_log Class Reference
Loi_paroi_log Class Reference
#include <Loi_paroi_log.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
Methodes implementees :
Constructor & Destructor Documentation
Loi_paroi_log()
Loi_paroi_log::Loi_paroi_log ()
~Loi_paroi_log()
Loi_paroi_log::~Loi_paroi_log ()
Member Function Documentation
cree_instance()
Objet_U * Loi_paroi_log::cree_instance () static
taille_memoire()
unsigned Loi_paroi_log::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Loi_paroi_adaptative.
duplique()
int Loi_paroi_log::duplique () const override virtual
Implements Objet_U.
Reimplemented in Loi_paroi_adaptative.
info()
const Type_info * Loi_paroi_log::info () static
get_info()
const Type_info * Loi_paroi_log::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Loi_paroi_base.
Reimplemented in Loi_paroi_adaptative.
self_cast() [1/2]
Loi_paroi_log & Loi_paroi_log::self_cast (Objet_U & r) static
self_cast() [2/2]
const Loi_paroi_log & Loi_paroi_log::self_cast (const Objet_U & r) static
printOn()
Sortie & Loi_paroi_log::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Loi_paroi_base.
Reimplemented in Loi_paroi_adaptative.
readOn()
Entree & Loi_paroi_log::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Loi_paroi_base.
Reimplemented in Loi_paroi_adaptative.
References Loi_paroi_base::readOn().
Referenced by Loi_paroi_adaptative::readOn().
calc_y_plus()
void Loi_paroi_log::calc_y_plus (const DoubleTab & vit, const DoubleTab & nu_visc) override virtual
Implements Loi_paroi_base.
Reimplemented in Loi_paroi_adaptative.
References calc_y_plus_loc(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Process::exit(), Loi_paroi_base::Faces_a_calculer_, Champ_Face_base::get_elem_vector_field(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Correlation_base::pb_, Loi_paroi_base::valeurs_loi_paroi_, and Loi_paroi_base::y_p_min_.
u_plus_de_y_plus()
double Loi_paroi_log::u_plus_de_y_plus (double y_p) virtual
Reimplemented in Loi_paroi_adaptative.
References limiteur_y_p, and von_karman_.
Referenced by calc_y_plus_loc().
deriv_u_plus_de_y_plus()
double Loi_paroi_log::deriv_u_plus_de_y_plus (double y_p) virtual
Reimplemented in Loi_paroi_adaptative.
References limiteur_y_p, and von_karman_.
Referenced by calc_y_plus_loc().
calc_y_plus_loc()
double Loi_paroi_log::calc_y_plus_loc (double y_p, double nu, double y, double y_p_0) protected
References deriv_u_plus_de_y_plus(), Loi_paroi_base::eps_y_p_, limiteur_y_p, and u_plus_de_y_plus().
Referenced by Loi_paroi_adaptative::calc_y_plus(), and calc_y_plus().
Member Data Documentation
info_obj
const Type_info Loi_paroi_log::info_obj static
von_karman_
double Loi_paroi_log::von_karman_ = 0.41 protected
Referenced by deriv_u_plus_de_y_plus(), and u_plus_de_y_plus().
limiteur_y_p
double Loi_paroi_log::limiteur_y_p = 0.01 protected
Referenced by calc_y_plus_loc(), deriv_u_plus_de_y_plus(), and u_plus_de_y_plus().