TrioCFD: Cut_cell_FT_Disc Class Reference
Cut_cell_FT_Disc Class Reference
#include <Cut_cell_FT_Disc.h>
Member Enumeration Documentation
STATUT_DIPHASIQUE
enum Cut_cell_FT_Disc::STATUT_DIPHASIQUE : int
Enumerator
REGULIER
MOURRANT
MONOPHASIQUE
NAISSANT
DESEQUILIBRE_FINAL
DESEQUILIBRE_INITIAL
count
Constructor & Destructor Documentation
Cut_cell_FT_Disc()
Cut_cell_FT_Disc::Cut_cell_FT_Disc ()
References TRUSTTabFT_cut_cell_scalar< _TYPE_ >::associer_paresseux(), TRUSTTabFT_cut_cell_vector2< _TYPE_ >::associer_paresseux(), TRUSTTabFT_cut_cell_vector3< _TYPE_ >::associer_paresseux(), TRUSTTabFT_cut_cell_vector3< _TYPE_ >::associer_persistant(), coord_, independent_index_, index_sorted_by_indicatrice_, index_sorted_by_k_, index_sorted_by_statut_diphasique_, k_value_index_, permutation_, processed_, TRUSTTab< _TYPE_, _SIZE_ >::resize(), and statut_diphasique_value_index_.
Member Function Documentation
add_to_persistent_data() [1/2]
void Cut_cell_FT_Disc::add_to_persistent_data (DoubleTabFT_cut_cell & field, int dimension) inline
References n_tot_, persistent_double_data_, and TRUSTTab< _TYPE_, _SIZE_ >::resize().
Referenced by TRUSTTabFT_cut_cell< int >::echange_espace_virtuel().
add_to_transient_data() [1/2]
void Cut_cell_FT_Disc::add_to_transient_data (DoubleTabFT_cut_cell & field, int dimension) inline
References n_tot_, TRUSTTab< _TYPE_, _SIZE_ >::resize(), and transient_double_data_.
Referenced by TRUSTTabFT_cut_cell< _TYPE_ >::associer_ephemere().
add_to_lazy_data() [1/2]
void Cut_cell_FT_Disc::add_to_lazy_data (DoubleTabFT_cut_cell & field, int dimension) inline
References lazy_double_data_, n_tot_, and TRUSTTab< _TYPE_, _SIZE_ >::resize().
Referenced by TRUSTTabFT_cut_cell< _TYPE_ >::associer_paresseux().
add_to_persistent_data() [2/2]
void Cut_cell_FT_Disc::add_to_persistent_data (IntTabFT_cut_cell & field, int dimension) inline
References n_tot_, persistent_int_data_, and TRUSTTab< _TYPE_, _SIZE_ >::resize().
add_to_transient_data() [2/2]
void Cut_cell_FT_Disc::add_to_transient_data (IntTabFT_cut_cell & field, int dimension) inline
References n_tot_, TRUSTTab< _TYPE_, _SIZE_ >::resize(), and transient_int_data_.
add_to_lazy_data() [2/2]
void Cut_cell_FT_Disc::add_to_lazy_data (IntTabFT_cut_cell & field, int dimension) inline
References lazy_int_data_, n_tot_, and TRUSTTab< _TYPE_, _SIZE_ >::resize().
initialise() [1/2]
void Cut_cell_FT_Disc::initialise (IJK_Interfaces & interfaces, Domaine_IJK & splitting, Domaine_IJK::Localisation loc)
References IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::allocate(), compute_virtual_independent_index(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), echange_espace_virtuel(), ghost_size_, independent_index_, indice_diphasique_, initialise_communications(), initialise_schema_comm(), localisation_, n_loc_, n_tot_, permutation_, processed_, ref_domaine_, ref_interfaces_, remplir_indice_diphasique(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), resize_data(), set_coord(), update_index_sorted_by_k(), verifier_coherence_coord_independent_index(), verifier_taille_tableaux(), and write_buffer_.
Referenced by Probleme_FTD_IJK_cut_cell::initialize().
initialise() [2/2]
void Cut_cell_FT_Disc::initialise (IJK_Interfaces & interfaces, Domaine_IJK & splitting, Domaine_IJK::Localisation loc, const IJK_Field_double & old_indicatrice, const IJK_Field_double & next_indicatrice)
References IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::allocate(), compute_virtual_independent_index(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), echange_espace_virtuel(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_localisation(), ghost_size_, independent_index_, indice_diphasique_, initialise_communications(), initialise_independent_index(), initialise_permutation(), initialise_processed(), initialise_schema_comm(), localisation_, n_loc_, n_tot_, permutation_, processed_, ref_domaine_, ref_interfaces_, remplir_indice_diphasique(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), resize_data(), set_coord(), update_index_sorted_by_indicatrice(), update_index_sorted_by_k(), update_index_sorted_by_statut_diphasique(), verifier_coherence_coord_independent_index(), verifier_taille_tableaux(), and write_buffer_.
initialise_independent_index()
int Cut_cell_FT_Disc::initialise_independent_index (const IJK_Field_double & old_indicatrice, const IJK_Field_double & next_indicatrice)
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), get_ijk(), independent_index_, n_loc_, n_tot_, ref_domaine_, ref_interfaces_, and TRUSTTab< _TYPE_, _SIZE_ >::resize().
Referenced by initialise().
initialise_permutation()
void Cut_cell_FT_Disc::initialise_permutation ()
References n_loc_, and permutation_.
Referenced by initialise().
initialise_processed()
void Cut_cell_FT_Disc::initialise_processed ()
References n_loc_, processed_, and processed_count_.
Referenced by initialise().
set_coord()
void Cut_cell_FT_Disc::set_coord ()
References coord_, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Domaine_IJK::ELEM, get_ijk(), n_loc_, processed_, processed_count_, and ref_domaine_.
Referenced by initialise(), and update().
update()
void Cut_cell_FT_Disc::update (const IJK_Field_double & old_indicatrice, const IJK_Field_double & next_indicatrice)
References add_and_remove_local_elements(), compute_virtual_independent_index(), desc_, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), echange_espace_virtuel(), Domaine_IJK::ELEM, Domaine_IJK::FACES_I, Domaine_IJK::FACES_J, Domaine_IJK::FACES_K, IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_localisation(), independent_index_, initialise_communications(), localisation_, n_loc_, n_tot_, permutation_, processed_, processed_count_, remplir_indice_diphasique(), Desc_Structure_FT::reset(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), resize_data(), set_coord(), update_index_sorted_by_indicatrice(), update_index_sorted_by_k(), update_index_sorted_by_statut_diphasique(), verifier_coherence_coord_independent_index(), and verifier_taille_tableaux().
Referenced by Probleme_FTD_IJK_cut_cell::deplacer_interfaces(), Probleme_FTD_IJK_cut_cell::deplacer_interfaces_rk3(), and Probleme_FTD_IJK_cut_cell::update_twice_indicator_field().
add_and_remove_local_elements()
int Cut_cell_FT_Disc::add_and_remove_local_elements (const IJK_Field_double & old_indicatrice, const IJK_Field_double & next_indicatrice)
References apply_permutation(), coord_, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Domaine_IJK::ELEM, independent_index_, indice_diphasique_, n_loc_, n_tot_, permutation_, persistent_double_data_, persistent_int_data_, processed_, processed_count_, ref_domaine_, ref_interfaces_, TRUSTTab< _TYPE_, _SIZE_ >::resize(), resize_data(), verifier_coherence_coord_independent_index(), verifier_si_ordonne(), and verifier_valide_permutation().
Referenced by update().
resize_data()
void Cut_cell_FT_Disc::resize_data (int size)
References lazy_double_data_, lazy_int_data_, persistent_double_data_, persistent_int_data_, transient_double_data_, and transient_int_data_.
Referenced by add_and_remove_local_elements(), initialise(), remove_dead_and_virtual_cells(), and update().
compute_virtual_independent_index()
void Cut_cell_FT_Disc::compute_virtual_independent_index ()
References coord_, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Domaine_IJK::ELEM, independent_index_, n_loc_, n_tot_, and ref_domaine_.
Referenced by initialise(), and update().
initialise_schema_comm()
void Cut_cell_FT_Disc::initialise_schema_comm ()
References TRUSTArray< _TYPE_, _SIZE_ >::append_array(), ref_domaine_, schema_comm_, and Schema_Comm::set_send_recv_pe_list().
Referenced by initialise().
initialise_communications()
int Cut_cell_FT_Disc::initialise_communications ()
References Descripteur_FT::ajoute_element(), TRUSTTab< _TYPE_, _SIZE_ >::append_line(), Schema_Comm::begin_comm(), Descripteur_FT::calcul_liste_pe_voisins(), Desc_Structure_FT::calcul_schema_comm(), Descripteur_FT::contient_element(), coord_, desc_, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Schema_Comm::echange_taille_et_messages(), Domaine_IJK::ELEM, Schema_Comm::end_comm(), Entree::eof(), Desc_Structure_FT::espace_distant(), Desc_Structure_FT::espace_virtuel(), Schema_Comm::get_recv_pe_list(), ghost_size_, n_loc_, n_tot_, Schema_Comm::recv_buffer(), ref_domaine_, schema_comm_, Schema_Comm::send_buffer(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by initialise(), and update().
echange_espace_virtuel() [1/2]
void Cut_cell_FT_Disc::echange_espace_virtuel ()
References desc_, Desc_Structure_FT::echange_espace_virtuel(), persistent_double_data_, and persistent_int_data_.
Referenced by initialise(), and update().
echange_espace_virtuel() [2/2]
void Cut_cell_FT_Disc::echange_espace_virtuel (MD_Vector_tools::Operations_echange op)
References desc_, Desc_Structure_FT::echange_espace_virtuel(), persistent_double_data_, and persistent_int_data_.
update_index_sorted_by_k()
void Cut_cell_FT_Disc::update_index_sorted_by_k ()
References get_ijk(), ghost_size_, index_sorted_by_k_, k_value_index_, n_loc_, n_tot_, ref_domaine_, TRUSTTab< _TYPE_, _SIZE_ >::resize(), and TRUSTTabFT_cut_cell< _TYPE_ >::sort_tot().
Referenced by initialise(), and update().
update_index_sorted_by_indicatrice()
void Cut_cell_FT_Disc::update_index_sorted_by_indicatrice (const IJK_Field_double & old_indicatrice, const IJK_Field_double & next_indicatrice)
References get_ijk(), index_sorted_by_indicatrice_, n_loc_, n_tot_, and TRUSTTabFT_cut_cell< _TYPE_ >::sort_tot().
Referenced by initialise(), and update().
update_index_sorted_by_statut_diphasique()
void Cut_cell_FT_Disc::update_index_sorted_by_statut_diphasique (const IJK_Field_double & old_indicatrice, const IJK_Field_double & next_indicatrice)
References get_ijk(), get_n_from_indicatrice_index(), index_sorted_by_statut_diphasique_, n_tot_, ref_interfaces_, TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTTabFT_cut_cell< _TYPE_ >::sort_tot(), and statut_diphasique_value_index_.
Referenced by initialise(), and update().
fill_buffer_with_variable()
template<typename T > template void Cut_cell_FT_Disc::fill_buffer_with_variable< double > (const TRUSTTabFT< T > & array, int component = 0) const
References DESEQUILIBRE_FINAL, DESEQUILIBRE_INITIAL, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), get_ijk(), get_n_from_statut_diphasique_index(), get_statut_diphasique_value_index(), MOURRANT, NAISSANT, ref_domaine_, REGULIER, and write_buffer_.
fill_variable_with_buffer()
template<typename T > template void Cut_cell_FT_Disc::fill_variable_with_buffer< double > (TRUSTTabFT< T > & array, int component = 0) const
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), get_ijk(), and n_loc_.
remplir_indice_diphasique()
void Cut_cell_FT_Disc::remplir_indice_diphasique ()
References get_ijk(), ghost_size_, ijk_per_of_index(), indice_diphasique_, n_loc_, n_tot_, next_index_ijk_per(), and ref_domaine_.
Referenced by initialise(), remove_dead_and_virtual_cells(), and update().
remove_dead_and_virtual_cells()
void Cut_cell_FT_Disc::remove_dead_and_virtual_cells (const IJK_Field_double & next_indicatrice)
References apply_permutation(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), get_ijk(), independent_index_, n_loc_, n_tot_, permutation_, persistent_double_data_, persistent_int_data_, processed_, remplir_indice_diphasique(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), resize_data(), verifier_si_ordonne(), and verifier_valide_permutation().
Referenced by Probleme_FTD_IJK_cut_cell::update_indicator_field().
verifier_coherence_coord_independent_index()
bool Cut_cell_FT_Disc::verifier_coherence_coord_independent_index ()
References coord_, Domaine_IJK::ELEM, get_ijk(), n_loc_, n_tot_, and ref_domaine_.
Referenced by add_and_remove_local_elements(), initialise(), and update().
verifier_taille_tableaux()
bool Cut_cell_FT_Disc::verifier_taille_tableaux ()
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), independent_index_, lazy_double_data_, lazy_int_data_, n_tot_, persistent_double_data_, persistent_int_data_, transient_double_data_, and transient_int_data_.
Referenced by initialise(), and update().
imprime_elements_diphasiques()
void Cut_cell_FT_Disc::imprime_elements_diphasiques ()
References coord_, get_ijk(), n_loc_, n_tot_, and ref_domaine_.
imprime_elements_distants()
void Cut_cell_FT_Disc::imprime_elements_distants ()
References coord_, Domaine_IJK::ELEM, get_ijk(), ghost_size_, n_loc_, and ref_domaine_.
get_independent_index() [1/2]
const IntTabFT_cut_cell & Cut_cell_FT_Disc::get_independent_index () const inline
References independent_index_.
get_independent_index() [2/2]
int Cut_cell_FT_Disc::get_independent_index (int n) const inline
References independent_index_.
get_ghost_size()
int Cut_cell_FT_Disc::get_ghost_size () const inline
References ghost_size_.
get_n_loc()
int Cut_cell_FT_Disc::get_n_loc () const inline
References n_loc_.
Referenced by Cut_cell_surface_efficace::calcul_surface_face_efficace_iteratif(), Cut_cell_surface_efficace::calcul_surface_interface_efficace(), Cut_cell_surface_efficace::calcul_vitesse_interface(), IJK_Interfaces::imprime_bilan_indicatrice(), Cut_cell_surface_efficace::imprimer_informations_surface_efficace_face(), and Cut_cell_surface_efficace::imprimer_informations_surface_efficace_interface().
get_n_tot()
int Cut_cell_FT_Disc::get_n_tot () const inline
References n_tot_.
Referenced by Cut_cell_surface_efficace::calcul_surface_face_efficace_initiale(), Cut_cell_surface_efficace::calcul_surface_interface_efficace_initiale(), IJK_Thermal_cut_cell::compute_temperature_init(), and IJK_Thermal_cut_cell::recompute_temperature_init().
get_interfaces()
const IJK_Interfaces & Cut_cell_FT_Disc::get_interfaces () const
References ref_interfaces_.
Referenced by Cut_cell_schema_auxiliaire::add_dying_cells(), Cut_cell_schema_auxiliaire::add_small_nascent_cells(), Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_copie_directe(), Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_ponderation_voisin(), Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_semi_lagrangien(), Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_semi_lagrangien_interpolate(), IJK_Interfaces::calculer_vitesse_de_deformation(), Cut_cell_schema_auxiliaire::compute_flux_dying_cells(), Cut_cell_schema_auxiliaire::compute_flux_small_nascent_cells(), Cut_cell_convection_auxiliaire::dying_cells_flux(), Cut_cell_diffusion_auxiliaire::dying_cells_flux(), Cut_cell_convection_auxiliaire::small_nascent_cells_flux(), and Cut_cell_diffusion_auxiliaire::small_nascent_cells_flux().
get_domaine()
const Domaine_IJK & Cut_cell_FT_Disc::get_domaine () const
References ref_domaine_.
Referenced by Cut_cell_schema_auxiliaire::add_dying_cells(), Cut_cell_schema_auxiliaire::add_small_nascent_cells(), Cut_cell_surface_efficace::calcul_surface_face_efficace_iteratif(), Cut_cell_surface_efficace::calcul_surface_interface_efficace(), Cut_cell_surface_efficace::calcul_vitesse_interface(), Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_copie_directe(), Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_ponderation_voisin(), Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_semi_lagrangien(), Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_semi_lagrangien_interpolate(), OpDiffIJKScalar_cut_cell_double::compute_cut_cell_divergence(), OpConvQuickIJKScalar_cut_cell_double::compute_cut_cell_divergence(), Cut_cell_schema_auxiliaire::compute_flux_dying_cells(), Cut_cell_schema_auxiliaire::compute_flux_small_nascent_cells(), Cut_cell_surface_efficace::imprimer_informations_surface_efficace_face(), and Cut_cell_surface_efficace::imprimer_informations_surface_efficace_interface().
get_desc_structure()
const Desc_Structure_FT & Cut_cell_FT_Disc::get_desc_structure () const
References desc_.
get_write_buffer()
IJK_Field_double & Cut_cell_FT_Disc::get_write_buffer () const inline
References write_buffer_.
ijk_per_of_index()
Int3 Cut_cell_FT_Disc::ijk_per_of_index (int i, int j, int k, int index) const inline
References ghost_size_, and ref_domaine_.
Referenced by remplir_indice_diphasique().
next_index_ijk_per()
int Cut_cell_FT_Disc::next_index_ijk_per (int i, int j, int k, int index, int negative_ghost_size, int positive_ghost_size) const inline
References ref_domaine_.
Referenced by remplir_indice_diphasique().
get_ijk()
Int3 Cut_cell_FT_Disc::get_ijk (int n) const inline
References independent_index_, and ref_domaine_.
Referenced by Cut_cell_schema_auxiliaire::add_dying_cells(), Cut_cell_schema_auxiliaire::add_small_nascent_cells(), Cut_cell_surface_efficace::calcul_surface_face_efficace_initiale(), Cut_cell_surface_efficace::calcul_surface_face_efficace_iteratif(), Cut_cell_surface_efficace::calcul_surface_interface_efficace(), Cut_cell_surface_efficace::calcul_surface_interface_efficace_initiale(), Cut_cell_surface_efficace::calcul_vitesse_interface(), Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_copie_directe(), Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_ponderation_voisin(), Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_semi_lagrangien(), Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_semi_lagrangien_interpolate(), OpDiffIJKScalar_cut_cell_double::compute_cut_cell_divergence(), OpConvQuickIJKScalar_cut_cell_double::compute_cut_cell_divergence(), Cut_cell_schema_auxiliaire::compute_flux_dying_cells(), Cut_cell_schema_auxiliaire::compute_flux_small_nascent_cells(), Cut_cell_convection_auxiliaire::dying_cells_flux(), Cut_cell_diffusion_auxiliaire::dying_cells_flux(), fill_buffer_with_variable(), fill_variable_with_buffer(), IJK_Interfaces::imprime_bilan_indicatrice(), imprime_elements_diphasiques(), imprime_elements_distants(), Cut_cell_surface_efficace::imprimer_informations_surface_efficace_face(), Cut_cell_surface_efficace::imprimer_informations_surface_efficace_interface(), initialise_independent_index(), remove_dead_and_virtual_cells(), remplir_indice_diphasique(), set_coord(), Cut_cell_convection_auxiliaire::small_nascent_cells_flux(), Cut_cell_diffusion_auxiliaire::small_nascent_cells_flux(), update_index_sorted_by_indicatrice(), update_index_sorted_by_k(), update_index_sorted_by_statut_diphasique(), verifier_coherence_coord_independent_index(), within_ghost(), and within_ghost_().
get_n()
int Cut_cell_FT_Disc::get_n (int i, int j, int k) const inline
References indice_diphasique_, and n_tot_.
Referenced by Cut_cell_schema_auxiliaire::add_dying_cells(), Cut_cell_schema_auxiliaire::add_small_nascent_cells(), Cut_cell_surface_efficace::calcul_delta_volume_theorique_bilan(), Cut_cell_surface_efficace::calcul_surface_face_efficace_iteratif(), Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_ponderation_voisin(), Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_semi_lagrangien(), IJK_Interfaces::calculer_vitesse_de_deformation(), OpConvQuickIJKScalar_cut_cell_double::compute_cut_cell_divergence(), Cut_cell_convection_auxiliaire::dying_cells_flux(), get_n_face(), Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::get_value_location(), indic_pure(), and Cut_cell_convection_auxiliaire::small_nascent_cells_flux().
get_n_face()
int Cut_cell_FT_Disc::get_n_face (int num_face, int n, int i, int j, int k) const inline
References get_n().
Referenced by Cut_cell_schema_auxiliaire::add_small_nascent_cells(), Cut_cell_surface_efficace::calcul_delta_volume_theorique_bilan(), Cut_cell_surface_efficace::calcul_surface_face_efficace_iteratif(), Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_ponderation_voisin(), Cut_cell_schema_auxiliaire::compute_flux_dying_cells(), Cut_cell_schema_auxiliaire::compute_flux_small_nascent_cells(), Cut_cell_convection_auxiliaire::dying_cells_flux(), Cut_cell_diffusion_auxiliaire::dying_cells_flux(), Cut_cell_surface_efficace::imprimer_informations_surface_efficace_face(), Cut_cell_convection_auxiliaire::small_nascent_cells_flux(), and Cut_cell_diffusion_auxiliaire::small_nascent_cells_flux().
indic_pure()
double Cut_cell_FT_Disc::indic_pure (const int i, const int j, const int k) const
References get_n(), and ref_interfaces_.
Referenced by OpConvQuickIJKScalar_cut_cell_double::compute_cut_cell_divergence().
within_ghost()
bool Cut_cell_FT_Disc::within_ghost (int n, int negative_ghost_size, int positive_ghost_size) const inline
References get_ijk(), and ref_domaine_.
within_ghost_()
template<int _DIR_> bool Cut_cell_FT_Disc::within_ghost_ (int n, int negative_ghost_size, int positive_ghost_size) const inline
References get_ijk(), and ref_domaine_.
get_k_value_index()
int Cut_cell_FT_Disc::get_k_value_index (int k) const inline
References ghost_size_, and k_value_index_.
Referenced by OpDiffIJKScalar_cut_cell_double::compute_cut_cell_divergence(), and OpConvQuickIJKScalar_cut_cell_double::compute_cut_cell_divergence().
get_n_from_k_index()
int Cut_cell_FT_Disc::get_n_from_k_index (int index) const inline
References index_sorted_by_k_.
Referenced by OpDiffIJKScalar_cut_cell_double::compute_cut_cell_divergence(), and OpConvQuickIJKScalar_cut_cell_double::compute_cut_cell_divergence().
get_n_from_indicatrice_index()
int Cut_cell_FT_Disc::get_n_from_indicatrice_index (int index) const inline
References index_sorted_by_indicatrice_.
Referenced by update_index_sorted_by_statut_diphasique().
get_statut_diphasique_value_index()
int Cut_cell_FT_Disc::get_statut_diphasique_value_index (int statut_diphasique) const inline
References statut_diphasique_value_index_.
Referenced by Cut_cell_schema_auxiliaire::add_dying_cells(), Cut_cell_schema_auxiliaire::add_small_nascent_cells(), Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_copie_directe(), Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_ponderation_voisin(), Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_semi_lagrangien(), Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_semi_lagrangien_interpolate(), Cut_cell_schema_auxiliaire::compute_flux_dying_cells(), Cut_cell_schema_auxiliaire::compute_flux_small_nascent_cells(), and fill_buffer_with_variable().
get_n_from_statut_diphasique_index()
int Cut_cell_FT_Disc::get_n_from_statut_diphasique_index (int index) const inline
References index_sorted_by_statut_diphasique_.
Referenced by Cut_cell_schema_auxiliaire::add_dying_cells(), Cut_cell_schema_auxiliaire::add_small_nascent_cells(), Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_copie_directe(), Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_ponderation_voisin(), Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_semi_lagrangien(), Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_semi_lagrangien_interpolate(), Cut_cell_schema_auxiliaire::compute_flux_dying_cells(), Cut_cell_schema_auxiliaire::compute_flux_small_nascent_cells(), and fill_buffer_with_variable().
find_value_unsorted()
template<typename T > template int Cut_cell_FT_Disc::find_value_unsorted< double > (T value, const TRUSTTabFT< T > & array, int imin, int imax) static protected
References TRUSTTab< _TYPE_, _SIZE_ >::dimension().
Referenced by verifier_pas_de_doublons(), and verifier_valide_permutation().
verifier_toujours_meme_signe_et_non_nul()
bool Cut_cell_FT_Disc::verifier_toujours_meme_signe_et_non_nul (const IntTabFT_cut_cell & array) static protected
References TRUSTTab< _TYPE_, _SIZE_ >::dimension().
Referenced by apply_permutation().
verifier_tableau_jamais_nul()
bool Cut_cell_FT_Disc::verifier_tableau_jamais_nul (const DoubleTabFT_cut_cell & array) static protected
References TRUSTTab< _TYPE_, _SIZE_ >::dimension().
verifier_valide_permutation()
bool Cut_cell_FT_Disc::verifier_valide_permutation (const IntTabFT_cut_cell & array) static protected
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), and find_value_unsorted().
Referenced by add_and_remove_local_elements(), and remove_dead_and_virtual_cells().
verifier_pas_de_doublons()
bool Cut_cell_FT_Disc::verifier_pas_de_doublons (const IntTabFT_cut_cell & array) static protected
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), and find_value_unsorted().
apply_permutation()
template<typename T > void Cut_cell_FT_Disc::apply_permutation (TRUSTTabFT< T > & array, const IntTabFT_cut_cell & permutation_indices, IntTabFT_cut_cell & processed) static protected
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), and verifier_toujours_meme_signe_et_non_nul().
Referenced by add_and_remove_local_elements(), and remove_dead_and_virtual_cells().
verifier_si_ordonne()
bool Cut_cell_FT_Disc::verifier_si_ordonne (const IntTabFT_cut_cell & array, int imin, int imax) static protected
Referenced by add_and_remove_local_elements(), and remove_dead_and_virtual_cells().
Member Data Documentation
Postprocessing_IJK
friend Cut_cell_FT_Disc::Postprocessing_IJK protected
Probleme_FTD_IJK_cut_cell
friend Cut_cell_FT_Disc::Probleme_FTD_IJK_cut_cell protected
write_buffer_
IJK_Field_double Cut_cell_FT_Disc::write_buffer_ mutable protected
Referenced by fill_buffer_with_variable(), get_write_buffer(), and initialise().
indice_diphasique_
IJK_Field_int Cut_cell_FT_Disc::indice_diphasique_ protected
Referenced by add_and_remove_local_elements(), get_n(), initialise(), and remplir_indice_diphasique().
schema_comm_
Schema_Comm Cut_cell_FT_Disc::schema_comm_ protected
Referenced by initialise_communications(), and initialise_schema_comm().
desc_
Desc_Structure_FT Cut_cell_FT_Disc::desc_ protected
Referenced by echange_espace_virtuel(), get_desc_structure(), initialise_communications(), and update().
ref_interfaces_
TRUST_Ref< IJK_Interfaces *> Cut_cell_FT_Disc::ref_interfaces_ protected
Referenced by add_and_remove_local_elements(), get_interfaces(), indic_pure(), initialise(), initialise_independent_index(), and update_index_sorted_by_statut_diphasique().
ref_domaine_
TRUST_Ref< Domaine_IJK *> Cut_cell_FT_Disc::ref_domaine_ protected
Referenced by add_and_remove_local_elements(), compute_virtual_independent_index(), fill_buffer_with_variable(), get_domaine(), get_ijk(), ijk_per_of_index(), imprime_elements_diphasiques(), imprime_elements_distants(), initialise(), initialise_communications(), initialise_independent_index(), initialise_schema_comm(), next_index_ijk_per(), remplir_indice_diphasique(), set_coord(), update_index_sorted_by_k(), verifier_coherence_coord_independent_index(), within_ghost(), and within_ghost_().
localisation_
Domaine_IJK::Localisation Cut_cell_FT_Disc::localisation_ protected
Referenced by initialise(), and update().
ghost_size_
int Cut_cell_FT_Disc::ghost_size_ protected
Referenced by get_ghost_size(), get_k_value_index(), ijk_per_of_index(), imprime_elements_distants(), initialise(), initialise_communications(), remplir_indice_diphasique(), and update_index_sorted_by_k().
processed_count_
int Cut_cell_FT_Disc::processed_count_ protected
Referenced by add_and_remove_local_elements(), initialise_processed(), set_coord(), and update().
n_loc_
int Cut_cell_FT_Disc::n_loc_ protected
Referenced by add_and_remove_local_elements(), compute_virtual_independent_index(), fill_variable_with_buffer(), get_n_loc(), imprime_elements_diphasiques(), imprime_elements_distants(), initialise(), initialise_communications(), initialise_independent_index(), initialise_permutation(), initialise_processed(), remove_dead_and_virtual_cells(), remplir_indice_diphasique(), set_coord(), update(), update_index_sorted_by_indicatrice(), update_index_sorted_by_k(), and verifier_coherence_coord_independent_index().
n_tot_
int Cut_cell_FT_Disc::n_tot_ protected
Referenced by add_and_remove_local_elements(), add_to_lazy_data(), add_to_persistent_data(), add_to_transient_data(), compute_virtual_independent_index(), get_n(), get_n_tot(), imprime_elements_diphasiques(), initialise(), initialise_communications(), initialise_independent_index(), remove_dead_and_virtual_cells(), remplir_indice_diphasique(), update(), update_index_sorted_by_indicatrice(), update_index_sorted_by_k(), update_index_sorted_by_statut_diphasique(), verifier_coherence_coord_independent_index(), and verifier_taille_tableaux().
index_sorted_by_k_
IntTabFT_cut_cell_vector2 Cut_cell_FT_Disc::index_sorted_by_k_ protected
Referenced by Cut_cell_FT_Disc(), get_n_from_k_index(), and update_index_sorted_by_k().
k_value_index_
IntTabFT Cut_cell_FT_Disc::k_value_index_ protected
Referenced by Cut_cell_FT_Disc(), get_k_value_index(), and update_index_sorted_by_k().
index_sorted_by_indicatrice_
DoubleTabFT_cut_cell_vector3 Cut_cell_FT_Disc::index_sorted_by_indicatrice_ protected
Referenced by Cut_cell_FT_Disc(), get_n_from_indicatrice_index(), and update_index_sorted_by_indicatrice().
index_sorted_by_statut_diphasique_
IntTabFT_cut_cell_vector3 Cut_cell_FT_Disc::index_sorted_by_statut_diphasique_ protected
Referenced by Cut_cell_FT_Disc(), get_n_from_statut_diphasique_index(), and update_index_sorted_by_statut_diphasique().
statut_diphasique_value_index_
IntTabFT Cut_cell_FT_Disc::statut_diphasique_value_index_ protected
Referenced by Cut_cell_FT_Disc(), get_statut_diphasique_value_index(), and update_index_sorted_by_statut_diphasique().
independent_index_
IntTabFT_cut_cell_scalar Cut_cell_FT_Disc::independent_index_ protected
Referenced by add_and_remove_local_elements(), compute_virtual_independent_index(), Cut_cell_FT_Disc(), get_ijk(), get_independent_index(), initialise(), initialise_independent_index(), remove_dead_and_virtual_cells(), update(), and verifier_taille_tableaux().
permutation_
IntTabFT_cut_cell_scalar Cut_cell_FT_Disc::permutation_ protected
Referenced by add_and_remove_local_elements(), Cut_cell_FT_Disc(), initialise(), initialise_permutation(), remove_dead_and_virtual_cells(), and update().
processed_
IntTabFT_cut_cell_scalar Cut_cell_FT_Disc::processed_ protected
Referenced by add_and_remove_local_elements(), Cut_cell_FT_Disc(), initialise(), initialise_processed(), remove_dead_and_virtual_cells(), set_coord(), and update().
coord_
DoubleTabFT_cut_cell_vector3 Cut_cell_FT_Disc::coord_ protected
Referenced by add_and_remove_local_elements(), compute_virtual_independent_index(), Cut_cell_FT_Disc(), imprime_elements_diphasiques(), imprime_elements_distants(), initialise_communications(), set_coord(), and verifier_coherence_coord_independent_index().
persistent_double_data_
TRUST_List< TRUST_Ref< DoubleTabFT_cut_cell *> > Cut_cell_FT_Disc::persistent_double_data_ protected
Referenced by add_and_remove_local_elements(), add_to_persistent_data(), echange_espace_virtuel(), remove_dead_and_virtual_cells(), resize_data(), and verifier_taille_tableaux().
persistent_int_data_
TRUST_List< TRUST_Ref< IntTabFT_cut_cell *> > Cut_cell_FT_Disc::persistent_int_data_ protected
Referenced by add_and_remove_local_elements(), add_to_persistent_data(), echange_espace_virtuel(), remove_dead_and_virtual_cells(), resize_data(), and verifier_taille_tableaux().
transient_double_data_
TRUST_List< TRUST_Ref< DoubleTabFT_cut_cell *> > Cut_cell_FT_Disc::transient_double_data_ protected
Referenced by add_to_transient_data(), resize_data(), and verifier_taille_tableaux().
transient_int_data_
TRUST_List< TRUST_Ref< IntTabFT_cut_cell *> > Cut_cell_FT_Disc::transient_int_data_ protected
Referenced by add_to_transient_data(), resize_data(), and verifier_taille_tableaux().
lazy_double_data_
TRUST_List< TRUST_Ref< DoubleTabFT_cut_cell *> > Cut_cell_FT_Disc::lazy_double_data_ protected
Referenced by add_to_lazy_data(), resize_data(), and verifier_taille_tableaux().
lazy_int_data_
TRUST_List< TRUST_Ref< IntTabFT_cut_cell *> > Cut_cell_FT_Disc::lazy_int_data_ protected
Referenced by add_to_lazy_data(), resize_data(), and verifier_taille_tableaux().