TrioCFD: Fluide_Dilatable_base Class Reference
Fluide_Dilatable_base Class Reference abstract
#include <Fluide_Dilatable_base.h>
Public Member Functions
void calculer_alpha () override
virtual void completer (const Probleme_base &)
const Type_info * get_info () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
void set_Cp (double)
void verifier_coherence_champs (int &err, Nom &message) override
Public Member Functions inherited from Fluide_base
const Type_info * get_info () const override
void mettre_a_jour (double) override
void verifier_coherence_champs (int &err, Nom &message) override
Public Member Functions inherited from Milieu_base
virtual int a_gravite () const
int associer_ (Objet_U &) override
virtual void associer_gravite (const Champ_Don_base &)
virtual Champ_Don_base & beta_t ()
virtual const Champ_Don_base & beta_t () const
virtual Champ_Don_base & capacite_calorifique ()
virtual const Champ_Don_base & capacite_calorifique () const
virtual Champ_Don_base & conductivite ()
virtual const Champ_Don_base & conductivite () const
virtual Champ_Don_base & diffusivite ()
virtual const Champ_Don_base & diffusivite () const
virtual int est_deja_associe ()
const Type_info * get_info () const override
virtual Champ_Don_base & gravite ()
virtual const Champ_Don_base & gravite () const
const Nom & le_nom () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual Champ_base & masse_volumique ()
virtual const Champ_base & masse_volumique () const
void nommer (const Nom &) override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Fluide_base
void creer_nu ()
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Milieu_base
virtual void calculer_alpha ()
void ecrire (Sortie &) const
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
heritant de fluide base
See also
Milieu_base Fluide_base
Constructor & Destructor Documentation
Fluide_Dilatable_base()
Fluide_Dilatable_base::Fluide_Dilatable_base ()
~Fluide_Dilatable_base()
Fluide_Dilatable_base::~Fluide_Dilatable_base () override
Member Function Documentation
info()
const Type_info * Fluide_Dilatable_base::info () static
get_info()
const Type_info * Fluide_Dilatable_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Milieu_base.
Reimplemented in Espece, Fluide_Quasi_Compressible, and Fluide_Weakly_Compressible.
self_cast() [1/2]
Fluide_Dilatable_base & Fluide_Dilatable_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Fluide_Dilatable_base & Fluide_Dilatable_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Fluide_Dilatable_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Milieu_base.
Reimplemented in Espece, Fluide_Quasi_Compressible, and Fluide_Weakly_Compressible.
References Milieu_base::ecrire(), and Objet_U::que_suis_je().
Referenced by Fluide_Quasi_Compressible::printOn(), and Fluide_Weakly_Compressible::printOn().
readOn()
Entree & Fluide_Dilatable_base::readOn (Entree & is) override protected virtual
Lecture d'un milieu sur un flot d'entree.
Format: { grandeur_physique type_champ bloc de lecture du champ } cf set_param method to know the understood keywords cf Param class to know possible options reading
Parameters
(Entree& is) le flot d'entree pour la lecture des parametres du milieu
Returns
(Entree&) le flot d'entree modifie
Exceptions
accolade ouvrante attendue
Reimplemented from Milieu_base.
Reimplemented in Espece, Fluide_Quasi_Compressible, and Fluide_Weakly_Compressible.
References Fluide_base::readOn().
Referenced by Fluide_Quasi_Compressible::readOn(), and Fluide_Weakly_Compressible::readOn().
verifier_coherence_champs()
void Fluide_Dilatable_base::verifier_coherence_champs (int & err, Nom & msg) override virtual
Verifie que les champs lus l'ont ete correctement.
Exceptions
l'une des proprietes (rho mu Cp ou lambda) du fluide n'a pas ete definie
Reimplemented from Milieu_base.
Reimplemented in Espece.
References Milieu_base::ch_Cp_, Milieu_base::ch_lambda_, Fluide_base::ch_mu_, Milieu_base::ch_rho_, Objet_U_ptr::non_nul(), TRUST_Deriv< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), and Milieu_base::verifier_coherence_champs().
set_Cp()
void Fluide_Dilatable_base::set_Cp (double Cp_)
Complete le fluide avec un Cp constant.
Parameters
(double Cp) le cp du fluide
References Milieu_base::ch_Cp_, Champ_Don_base::dimensionner(), Objet_U_ptr::typer(), TRUST_Deriv< _CLASSE_ >::valeur(), and Champ_Don_base::valeurs().
update_rho_cp()
void Fluide_Dilatable_base::update_rho_cp (double temps) override virtual
Reimplemented from Milieu_base.
References Milieu_base::ch_Cp_, Milieu_base::ch_rho_, Milieu_base::ch_rho_Cp_comme_T_, Milieu_base::ch_rho_Cp_elem_, Champ_base::changer_temps(), Milieu_base::equation_, TRUST_Deriv< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), and Champ_Proto::valeurs().
Referenced by Convection_Diffusion_Fluide_Dilatable_Proto::assembler_blocs(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_impl(), Convection_Diffusion_Fluide_Dilatable_Proto::derivee_en_temps_inco_sans_solveur_masse_impl(), initialiser(), and mettre_a_jour().
creer_champs_non_lus()
void Fluide_Dilatable_base::creer_champs_non_lus () override virtual
Reimplemented from Milieu_base.
Reimplemented in Espece.
References Loi_Etat_base::calculer_lambda(), Milieu_base::ch_Cp_, Milieu_base::ch_lambda_, Fluide_base::ch_mu_, Objet_U_ptr::est_nul(), Process::exit(), Sutherland::get_A(), Objet_U::le_type(), Sutherland::lire_expression(), loi_etat_, Objet_U_ptr::non_nul(), Loi_Etat_base::Prandt(), Sutherland::set_A(), Objet_U_ptr::typer(), TRUST_Deriv< _CLASSE_ >::valeur(), and Champ_Don_base::valeurs().
initialiser_radiatives()
void Fluide_Dilatable_base::initialiser_radiatives (const double temps)
References Fluide_base::coeff_absorption_, Fluide_base::indice_refraction_, Champ_Don_base::initialiser(), Fluide_base::kappa(), Fluide_base::longueur_rayo(), Fluide_base::longueur_rayo_, Champ_Don_base::nb_valeurs_nodales(), and Champ_Don_base::valeurs().
Referenced by initialiser().
warn_syntax_Sutherland()
void Fluide_Dilatable_base::warn_syntax_Sutherland ()
References Process::exit().
Referenced by lire_motcle_non_standard().
initialiser()
int Fluide_Dilatable_base::initialiser (const double temps) override virtual
Initialise les parametres du fluide.
Reimplemented from Milieu_base.
References Milieu_base::ch_Cp_, Milieu_base::ch_lambda_, Fluide_base::ch_mu_, Milieu_base::ch_rho_, Milieu_base::ch_rho_Cp_comme_T_, Milieu_base::ch_rho_Cp_elem_, Fluide_base::coeff_absorption_, Milieu_base::equation_, Fluide_base::indice_refraction_, Champ_Don_base::initialiser(), initialiser_radiatives(), Objet_U_ptr::non_nul(), update_rho_cp(), TRUST_Deriv< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), and Champ_Proto::valeurs().
temperature()
const DoubleTab & Fluide_Dilatable_base::temperature () const
Renvoie le tableau des valeurs de le temperature.
References ch_temperature(), and Champ_Don_base::valeurs().
Referenced by Convection_Diffusion_Fluide_Dilatable_Proto::derivee_en_temps_inco_sans_solveur_masse_impl().
ch_temperature() [1/2]
const Champ_Don_base & Fluide_Dilatable_base::ch_temperature () const
Renvoie le champ de le temperature.
References Loi_Etat_base::ch_temperature(), and loi_etat_.
Referenced by Fluide_Quasi_Compressible::discretiser(), Fluide_Weakly_Compressible::discretiser(), mettre_a_jour(), and temperature().
ch_temperature() [2/2]
Champ_Don_base & Fluide_Dilatable_base::ch_temperature ()
References Loi_Etat_base::ch_temperature(), and loi_etat_.
calculer_pression_tot()
void Fluide_Dilatable_base::calculer_pression_tot () virtual
Calcule la pression totale : pression thermodynamique + pression hydrodynamique.
Reimplemented in Fluide_Weakly_Compressible.
References ch_pression_, ch_pression_tot_, TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), remplir_champ_pression_tot(), and Champ_Don_base::valeurs().
Referenced by Fluide_Weakly_Compressible::calculer_pression_tot(), and update_pressure_fields().
preparer_pas_temps()
void Fluide_Dilatable_base::preparer_pas_temps ()
Prepare le pas de temps.
References EDO_Pth_, eos_tools_, le_probleme_, loi_etat_, EOS_Tools_base::mettre_a_jour(), Loi_Etat_base::mettre_a_jour(), EDO_Pression_th_base::mettre_a_jour_CL(), Pth_, and traitement_PTh_.
abortTimeStep()
void Fluide_Dilatable_base::abortTimeStep () override virtual
Reimplemented from Milieu_base.
Reimplemented in Fluide_Weakly_Compressible.
References Loi_Etat_base::abortTimeStep(), loi_etat(), Pth_, and Pth_n_.
Referenced by Fluide_Weakly_Compressible::abortTimeStep().
set_param()
void Fluide_Dilatable_base::set_param (Param & param) override virtual
Reimplemented from Milieu_base.
Reimplemented in Espece, Fluide_Quasi_Compressible, and Fluide_Weakly_Compressible.
References Param::ajouter_non_std(), Param::REQUIRED, Fluide_base::set_param(), and Param::supprimer().
Referenced by Fluide_Quasi_Compressible::set_param(), and Fluide_Weakly_Compressible::set_param().
discretiser()
void Fluide_Dilatable_base::discretiser (const Probleme_base & pb, const Discretisation_base & dis) override virtual
Reimplemented from Milieu_base.
Reimplemented in Fluide_Quasi_Compressible, and Fluide_Weakly_Compressible.
References Champs_compris_T< FIELD_TYPE >::ajoute_champ(), Milieu_base::ch_Cp_, Milieu_base::ch_lambda_, ch_mu_sur_Sc, ch_nu_sur_Sc, ch_pression_tot_, Milieu_base::ch_rho_, ch_rho_comme_v_, ch_rho_gaz_, Milieu_base::champs_compris_, Fluide_base::discretiser(), Discretisation_base::discretiser_champ(), Equation_base::domaine_dis(), Probleme_base::equation(), Objet_U_ptr::est_nul(), TRUST_Ref< _CLASSE_ >::est_nul(), le_probleme_, Probleme_base::schema_temps(), Schema_Temps_base::temps_courant(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by Fluide_Quasi_Compressible::discretiser(), and Fluide_Weakly_Compressible::discretiser().
mettre_a_jour()
void Fluide_Dilatable_base::mettre_a_jour (double temps) override virtual
Reimplemented from Milieu_base.
References Milieu_base::ch_Cp_, Milieu_base::ch_lambda_, Fluide_base::ch_mu_, Milieu_base::ch_rho_, ch_temperature(), Champ_base::changer_temps(), Champ_Don_base::mettre_a_jour(), Champ_base::mettre_a_jour(), update_rho_cp(), and write_mean_edo().
update_pressure_fields()
void Fluide_Dilatable_base::update_pressure_fields (double temps) virtual
Reimplemented in Fluide_Weakly_Compressible.
References calculer_pression_tot(), ch_pression_tot_, and Champ_Don_base::mettre_a_jour().
Referenced by preparer_calcul(), and Fluide_Weakly_Compressible::update_pressure_fields().
preparer_calcul()
void Fluide_Dilatable_base::preparer_calcul () override virtual
Prepare le fluide au calcul.
Reimplemented from Milieu_base.
References calculer_coeff_T(), le_probleme_, loi_etat_, prepare_pressure_edo(), Loi_Etat_base::preparer_calcul(), and update_pressure_fields().
Referenced by Pb_Dilatable_base::preparer_calcul().
completer()
void Fluide_Dilatable_base::completer (const Probleme_base & pb) virtual
Complete le fluide avec les champs inconnus associes au probleme.
Parameters
(Pb_Thermohydraulique& pb) le probleme a resoudre
Reimplemented in Fluide_Quasi_Compressible, and Fluide_Weakly_Compressible.
References EOS_Tools_base::associer_domaines(), EOS_Tools_base::associer_fluide(), Loi_Etat_base::assoscier_probleme(), ch_inco_chaleur_, ch_pression_, ch_vitesse_, completer_edo(), Equation_base::discretisation(), Equation_base::domaine_Cl_dis(), Equation_base::domaine_dis(), eos_tools_, Probleme_base::equation(), TRUST_Ref< _CLASSE_ >::est_nul(), Equation_base::inconnue(), Loi_Etat_base::initialiser(), initialiser_inco_ch(), le_probleme_, loi_etat_, EOS_Tools_base::mettre_a_jour(), Objet_U::que_suis_je(), Probleme_base::schema_temps(), Schema_Temps_base::temps_courant(), traitement_PTh_, and Objet_U_ptr::typer().
Referenced by Fluide_Quasi_Compressible::completer(), Fluide_Weakly_Compressible::completer(), and Pb_Dilatable_base::preparer_calcul().
lire_motcle_non_standard()
int Fluide_Dilatable_base::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Milieu_base.
Reimplemented in Fluide_Quasi_Compressible.
References Loi_Etat_base::associer_fluide(), Milieu_base::ch_lambda_, Fluide_base::ch_mu_, Process::exit(), Sutherland::lire_expression(), Milieu_base::lire_motcle_non_standard(), loi_etat_, Field_base::nommer(), Objet_U::que_suis_je(), Motcles::search(), Sutherland::set_C(), Sutherland::set_prob(), Sutherland::set_Tref(), Sutherland::set_val_params(), traitement_PTh_, Objet_U_ptr::typer(), TRUST_Deriv< _CLASSE_ >::typer_lire(), TRUST_Deriv< _CLASSE_ >::valeur(), and warn_syntax_Sutherland().
Referenced by Fluide_Quasi_Compressible::lire_motcle_non_standard().
checkTraitementPth()
void Fluide_Dilatable_base::checkTraitementPth (const Domaine_Cl_dis_base & domaine_cl) virtual
Reimplemented in Fluide_Weakly_Compressible.
References Process::exit(), Domaine_Cl_dis_base::les_conditions_limites(), traitement_PTh_, and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by Fluide_Weakly_Compressible::checkTraitementPth().
prepare_pressure_edo()
void Fluide_Dilatable_base::prepare_pressure_edo ()
References EDO_Pression_th_base::completer(), EDO_Pth_, eos_tools_, le_probleme_, EOS_Tools_base::mettre_a_jour(), and traitement_PTh_.
Referenced by preparer_calcul().
write_mean_edo()
void Fluide_Dilatable_base::write_mean_edo (double temps) virtual
Reimplemented in Fluide_Weakly_Compressible.
References ch_inco_chaleur_, Milieu_base::ch_rho_, eos_tools_, Process::je_suis_maitre(), EOS_Tools_base::moyenne_vol(), output_file_, Pth_, traitement_PTh_, and Champ_Proto::valeurs().
Referenced by mettre_a_jour().
write_header_edo()
void Fluide_Dilatable_base::write_header_edo () virtual
Reimplemented in Fluide_Weakly_Compressible.
References Process::je_suis_maitre(), and output_file_.
Referenced by completer_edo().
secmembre_divU_Z()
virtual void Fluide_Dilatable_base::secmembre_divU_Z (DoubleTab &) const pure virtual
Implemented in Fluide_Quasi_Compressible, and Fluide_Weakly_Compressible.
Referenced by Navier_Stokes_Fluide_Dilatable_Proto::impr_impl().
Resoudre_EDO_PT()
virtual void Fluide_Dilatable_base::Resoudre_EDO_PT () pure virtual
Implemented in Fluide_Quasi_Compressible, and Fluide_Weakly_Compressible.
get_champ()
const Champ_base & Fluide_Dilatable_base::get_champ (const Motcle & nom) const override virtual
Reimplemented from Milieu_base.
References Nom::getString(), Milieu_base::has_champ(), Loi_Etat_base::has_champ(), and loi_etat_.
creer_champ()
void Fluide_Dilatable_base::creer_champ (const Motcle & motlu) override virtual
Reimplemented from Milieu_base.
References Champs_compris_T< FIELD_TYPE >::ajoute_champ(), ch_source_masse_esp_, ch_source_masse_proj_, Milieu_base::champs_compris_, Milieu_base::creer_champ(), Objet_U_ptr::est_nul(), and le_probleme_.
has_champ() [1/2]
bool Fluide_Dilatable_base::has_champ (const Motcle & nom, TRUST_Ref< Champ_base * > & ref_champ) const override virtual
Reimplemented from Milieu_base.
References Milieu_base::has_champ(), Loi_Etat_base::has_champ(), and loi_etat_.
has_champ() [2/2]
bool Fluide_Dilatable_base::has_champ (const Motcle & nom) const override virtual
Reimplemented from Milieu_base.
References Milieu_base::has_champ(), Loi_Etat_base::has_champ(), and loi_etat_.
get_noms_champs_postraitables()
void Fluide_Dilatable_base::get_noms_champs_postraitables (Noms & nom, Option opt = NONE) const override virtual
Reimplemented from Milieu_base.
References Milieu_base::get_noms_champs_postraitables(), Loi_Etat_base::get_noms_champs_postraitables(), and loi_etat_.
type_fluide()
const Nom Fluide_Dilatable_base::type_fluide () const inline
References loi_etat_, and Loi_Etat_base::type_fluide().
Referenced by Convection_Diffusion_Fluide_Dilatable_Proto::assembler_blocs(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_impl(), Convection_Diffusion_Fluide_Dilatable_Proto::derivee_en_temps_inco_sans_solveur_masse_impl(), Fluide_Quasi_Compressible::discretiser(), Fluide_Weakly_Compressible::discretiser(), and Pb_Dilatable_base::preparer_calcul().
loi_etat() [1/2]
const TRUST_Deriv< Loi_Etat_base > & Fluide_Dilatable_base::loi_etat () const inline
References loi_etat_.
Referenced by abortTimeStep(), Navier_Stokes_Fluide_Dilatable_base::completer(), Convection_Diffusion_Espece_Multi_QC::completer(), Convection_Diffusion_Espece_Multi_WC::completer(), Fluide_Quasi_Compressible::discretiser(), Fluide_Weakly_Compressible::discretiser(), and EOS_Tools_VDF::secmembre_divU_Z().
loi_etat() [2/2]
TRUST_Deriv< Loi_Etat_base > & Fluide_Dilatable_base::loi_etat () inline
References loi_etat_.
inco_chaleur() [1/2]
const Champ_Inc_base & Fluide_Dilatable_base::inco_chaleur () const inline
References ch_inco_chaleur_, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Source_Masse_Fluide_Dilatable_VDF::ajouter_projection(), Source_Masse_Fluide_Dilatable_VEF::ajouter_projection(), Convection_Diffusion_Fluide_Dilatable_Proto::data_a_sauvegarder(), Convection_Diffusion_Fluide_Dilatable_Proto::Reprendre_WC(), and Convection_Diffusion_Fluide_Dilatable_Proto::Sauvegarder_WC().
inco_chaleur() [2/2]
Champ_Inc_base & Fluide_Dilatable_base::inco_chaleur () inline
References ch_inco_chaleur_, and TRUST_Ref< _CLASSE_ >::valeur().
vitesse()
const Champ_Inc_base & Fluide_Dilatable_base::vitesse () const inline
References ch_vitesse_, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Convection_Diffusion_Fluide_Dilatable_Proto::derivee_en_temps_inco_sans_solveur_masse_impl(), EOS_Tools_VDF::secmembre_divU_Z(), and EOS_Tools_VEF::secmembre_divU_Z().
pression_tot() [1/2]
const Champ_Don_base & Fluide_Dilatable_base::pression_tot () const inline
References ch_pression_tot_.
pression_tot() [2/2]
Champ_Don_base & Fluide_Dilatable_base::pression_tot () inline
References ch_pression_tot_.
mu_sur_Schmidt() [1/2]
const Champ_Don_base & Fluide_Dilatable_base::mu_sur_Schmidt () const inline
References ch_mu_sur_Sc.
mu_sur_Schmidt() [2/2]
Champ_Don_base & Fluide_Dilatable_base::mu_sur_Schmidt () inline
References ch_mu_sur_Sc.
nu_sur_Schmidt() [1/2]
const Champ_Don_base & Fluide_Dilatable_base::nu_sur_Schmidt () const inline
References ch_nu_sur_Sc.
nu_sur_Schmidt() [2/2]
Champ_Don_base & Fluide_Dilatable_base::nu_sur_Schmidt () inline
References ch_nu_sur_Sc.
source_masse_espece() [1/2]
const Champ_Don_base & Fluide_Dilatable_base::source_masse_espece () const inline
References ch_source_masse_esp_, and Objet_U_ptr::non_nul().
source_masse_espece() [2/2]
Champ_Don_base & Fluide_Dilatable_base::source_masse_espece () inline
References ch_source_masse_esp_, and Objet_U_ptr::non_nul().
source_masse_projection() [1/2]
const Champ_Don_base & Fluide_Dilatable_base::source_masse_projection () const inline
References ch_source_masse_proj_, and Objet_U_ptr::non_nul().
source_masse_projection() [2/2]
Champ_Don_base & Fluide_Dilatable_base::source_masse_projection () inline
References ch_source_masse_proj_, and Objet_U_ptr::non_nul().
has_source_masse_espece_champ()
bool Fluide_Dilatable_base::has_source_masse_espece_champ () const inline
References ch_source_masse_esp_, and Objet_U_ptr::non_nul().
Referenced by Source_Masse_Fluide_Dilatable_VEF::ajouter_eq_espece().
has_source_masse_projection_champ()
bool Fluide_Dilatable_base::has_source_masse_projection_champ () const inline
References ch_source_masse_proj_, and Objet_U_ptr::non_nul().
Referenced by Source_Masse_Fluide_Dilatable_VDF::ajouter_projection(), and Source_Masse_Fluide_Dilatable_VEF::ajouter_projection().
rho_n()
const DoubleTab & Fluide_Dilatable_base::rho_n () const inline
References loi_etat_, and Loi_Etat_base::rho_n().
rho_np1()
const DoubleTab & Fluide_Dilatable_base::rho_np1 () const inline
References loi_etat_, and Loi_Etat_base::rho_np1().
calculer_coeff_T()
void Fluide_Dilatable_base::calculer_coeff_T () inline
References calculer_alpha(), calculer_Cp(), calculer_lambda(), calculer_mu(), calculer_mu_sur_Sc(), calculer_nu(), calculer_nu_sur_Sc(), loi_etat_, and Loi_Etat_base::remplir_T().
Referenced by preparer_calcul().
initialiser_inco_ch()
void Fluide_Dilatable_base::initialiser_inco_ch () inline
References Loi_Etat_base::initialiser_inco_ch(), and loi_etat_.
Referenced by completer().
calculer_Cp()
void Fluide_Dilatable_base::calculer_Cp () inline
References Loi_Etat_base::calculer_Cp(), and loi_etat_.
Referenced by calculer_coeff_T().
calculer_lambda()
void Fluide_Dilatable_base::calculer_lambda () inline
References Loi_Etat_base::calculer_lambda(), and loi_etat_.
Referenced by calculer_coeff_T().
calculer_mu()
void Fluide_Dilatable_base::calculer_mu () inline
References Loi_Etat_base::calculer_mu(), and loi_etat_.
Referenced by calculer_coeff_T().
calculer_nu()
void Fluide_Dilatable_base::calculer_nu () inline override virtual
Reimplemented from Fluide_base.
References Loi_Etat_base::calculer_nu(), and loi_etat_.
Referenced by calculer_coeff_T().
calculer_alpha()
void Fluide_Dilatable_base::calculer_alpha () inline override virtual
Calcul de alpha=lambda/(rho*Cp).
Suivant lambda, rho et Cp alpha peut-etre type comme un champ uniforme ou un champ uniforme par morceau.
Exceptions
violation d'une precondition
impossible de calculer alpha car le type des champs lambda,rho,Cp n'est pas compatible ou pas gere.
Reimplemented from Milieu_base.
References Loi_Etat_base::calculer_alpha(), and loi_etat_.
Referenced by calculer_coeff_T().
calculer_mu_sur_Sc()
void Fluide_Dilatable_base::calculer_mu_sur_Sc () inline
References calculer_mu_sur_Sc(), and loi_etat_.
Referenced by calculer_coeff_T(), and calculer_mu_sur_Sc().
calculer_nu_sur_Sc()
void Fluide_Dilatable_base::calculer_nu_sur_Sc () inline
References calculer_nu_sur_Sc(), and loi_etat_.
Referenced by calculer_coeff_T(), and calculer_nu_sur_Sc().
calculer_masse_volumique()
void Fluide_Dilatable_base::calculer_masse_volumique () inline
References Loi_Etat_base::calculer_masse_volumique(), and loi_etat_.
Referenced by Pb_Dilatable_base::preparer_calcul().
set_pression_th()
void Fluide_Dilatable_base::set_pression_th (double Pth) inline
References Pth_, and Pth_n_.
getTraitementPth()
int Fluide_Dilatable_base::getTraitementPth () const inline
References traitement_PTh_.
pression_th()
double Fluide_Dilatable_base::pression_th () const inline
References Pth_.
Referenced by Source_QC_Chaleur::ajouter_().
get_pression_th()
const double & Fluide_Dilatable_base::get_pression_th () const inline
References Pth_.
pression_thn()
double Fluide_Dilatable_base::pression_thn () const inline
References Pth_n_.
Referenced by Source_QC_Chaleur::ajouter_().
pression_th1()
double Fluide_Dilatable_base::pression_th1 () const inline
References Pth1_.
calculer_H()
double Fluide_Dilatable_base::calculer_H (double hh) const inline
References Loi_Etat_base::calculer_H(), loi_etat_, and Pth_.
get_problem()
Probleme_base & Fluide_Dilatable_base::get_problem () inline
References le_probleme_, and TRUST_Ref< _CLASSE_ >::valeur().
rho_discvit()
const DoubleTab & Fluide_Dilatable_base::rho_discvit () const inline
References eos_tools_, and EOS_Tools_base::rho_discvit().
Referenced by Source_QC_Gravite_VEF::ajouter(), Source_QC_Gravite_VDF::ajouter_blocs(), Navier_Stokes_Fluide_Dilatable_base::initTimeStep(), and Navier_Stokes_Turbulent_QC::initTimeStep().
rho_face_n()
const DoubleTab & Fluide_Dilatable_base::rho_face_n () const inline
References eos_tools_, and EOS_Tools_base::rho_face_n().
Referenced by Navier_Stokes_Fluide_Dilatable_Proto::assembler_avec_inertie_impl(), and Navier_Stokes_Fluide_Dilatable_Proto::assembler_blocs_avec_inertie().
rho_face_np1()
const DoubleTab & Fluide_Dilatable_base::rho_face_np1 () const inline
References eos_tools_, and EOS_Tools_base::rho_face_np1().
Referenced by Navier_Stokes_Fluide_Dilatable_Proto::assembler_avec_inertie_impl(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_blocs_avec_inertie(), and Navier_Stokes_Fluide_Dilatable_Proto::impr_impl().
calculer_rho_face()
void Fluide_Dilatable_base::calculer_rho_face (const DoubleTab & tab_rho) inline
References EOS_Tools_base::calculer_rho_face_np1(), and eos_tools_.
divu_discvit()
void Fluide_Dilatable_base::divu_discvit (DoubleTab & secmem1, DoubleTab & secmem2) inline
References EOS_Tools_base::divu_discvit(), and eos_tools_.
moyenne_vol()
double Fluide_Dilatable_base::moyenne_vol (const DoubleTab & A) const inline
References eos_tools_, and EOS_Tools_base::moyenne_vol().
Referenced by Source_QC_Gravite_VDF::ajouter_blocs().
is_dilatable()
bool Fluide_Dilatable_base::is_dilatable () const inline override virtual
Reimplemented from Milieu_base.
remplir_champ_pression_tot()
virtual void Fluide_Dilatable_base::remplir_champ_pression_tot (int n, const DoubleTab & PHydro, DoubleTab & PTot) protected pure virtual
Referenced by calculer_pression_tot().
completer_edo()
void Fluide_Dilatable_base::completer_edo (const Probleme_base & pb) protected
References EDO_Pression_th_base::associer_domaines(), EDO_Pression_th_base::associer_fluide(), Nom::debute_par(), Equation_base::discretisation(), Equation_base::domaine_Cl_dis(), Equation_base::domaine_dis(), EDO_Pth_, Probleme_base::equation(), Probleme_U::le_nom(), loi_etat_, EDO_Pression_th_base::mettre_a_jour_CL(), Objet_U::nom_du_cas(), output_file_, Pth_, Objet_U::que_suis_je(), traitement_PTh_, Loi_Etat_base::type_fluide(), Objet_U_ptr::typer(), and write_header_edo().
Referenced by completer().
Member Data Documentation
info_obj
const Type_info Fluide_Dilatable_base::info_obj static
traitement_PTh_
int Fluide_Dilatable_base::traitement_PTh_ = 0 protected
Referenced by checkTraitementPth(), Fluide_Weakly_Compressible::checkTraitementPth(), completer(), Fluide_Quasi_Compressible::completer(), completer_edo(), getTraitementPth(), lire_motcle_non_standard(), prepare_pressure_edo(), preparer_pas_temps(), Fluide_Weakly_Compressible::readOn(), Fluide_Quasi_Compressible::Resoudre_EDO_PT(), Fluide_Weakly_Compressible::Resoudre_EDO_PT(), write_mean_edo(), and Fluide_Weakly_Compressible::write_mean_edo().
Pth_
double Fluide_Dilatable_base::Pth_ = -1. protected
Referenced by abortTimeStep(), Fluide_Weakly_Compressible::abortTimeStep(), calculer_H(), Fluide_Quasi_Compressible::completer(), Fluide_Weakly_Compressible::completer(), completer_edo(), get_pression_th(), Fluide_Quasi_Compressible::lire_motcle_non_standard(), preparer_pas_temps(), pression_th(), Fluide_Quasi_Compressible::Resoudre_EDO_PT(), Fluide_Weakly_Compressible::Resoudre_EDO_PT(), Fluide_Weakly_Compressible::set_param(), set_pression_th(), Fluide_Weakly_Compressible::write_header_edo(), write_mean_edo(), and Fluide_Weakly_Compressible::write_mean_edo().
Pth_n_
double Fluide_Dilatable_base::Pth_n_ = -1. protected
Referenced by abortTimeStep(), Fluide_Weakly_Compressible::abortTimeStep(), Fluide_Weakly_Compressible::completer(), Fluide_Quasi_Compressible::lire_motcle_non_standard(), pression_thn(), Fluide_Quasi_Compressible::Resoudre_EDO_PT(), Fluide_Weakly_Compressible::Resoudre_EDO_PT(), and set_pression_th().
Pth1_
double Fluide_Dilatable_base::Pth1_ = -1. protected
Referenced by pression_th1().
ch_inco_chaleur_
TRUST_Ref< Champ_Inc_base *> Fluide_Dilatable_base::ch_inco_chaleur_ protected
Referenced by completer(), inco_chaleur(), write_mean_edo(), and Fluide_Weakly_Compressible::write_mean_edo().
ch_vitesse_
TRUST_Ref< Champ_Inc_base *> Fluide_Dilatable_base::ch_vitesse_ protected
Referenced by completer(), Fluide_Quasi_Compressible::secmembre_divU_Z(), and vitesse().
ch_pression_
TRUST_Ref< Champ_Inc_base *> Fluide_Dilatable_base::ch_pression_ protected
Referenced by calculer_pression_tot(), and completer().
le_probleme_
TRUST_Ref< Probleme_base *> Fluide_Dilatable_base::le_probleme_ protected
Referenced by completer(), Fluide_Weakly_Compressible::completer(), creer_champ(), discretiser(), get_problem(), prepare_pressure_edo(), preparer_calcul(), and preparer_pas_temps().
ch_pression_tot_
TRUST_Deriv< Champ_Don_base > Fluide_Dilatable_base::ch_pression_tot_ protected
Referenced by calculer_pression_tot(), discretiser(), pression_tot(), and update_pressure_fields().
ch_mu_sur_Sc
TRUST_Deriv< Champ_Don_base > Fluide_Dilatable_base::ch_mu_sur_Sc protected
Referenced by discretiser(), and mu_sur_Schmidt().
ch_nu_sur_Sc
TRUST_Deriv< Champ_Don_base > Fluide_Dilatable_base::ch_nu_sur_Sc protected
Referenced by discretiser(), and nu_sur_Schmidt().
ch_rho_gaz_
TRUST_Deriv< Champ_Don_base > Fluide_Dilatable_base::ch_rho_gaz_ protected
Referenced by discretiser().
ch_rho_comme_v_
TRUST_Deriv< Champ_Don_base > Fluide_Dilatable_base::ch_rho_comme_v_ protected
Referenced by discretiser().
ch_source_masse_esp_
TRUST_Deriv< Champ_Don_base > Fluide_Dilatable_base::ch_source_masse_esp_ protected
Referenced by creer_champ(), has_source_masse_espece_champ(), and source_masse_espece().
ch_source_masse_proj_
TRUST_Deriv< Champ_Don_base > Fluide_Dilatable_base::ch_source_masse_proj_ protected
Referenced by creer_champ(), has_source_masse_projection_champ(), and source_masse_projection().
loi_etat_
TRUST_Deriv< Loi_Etat_base > Fluide_Dilatable_base::loi_etat_ protected
Referenced by calculer_alpha(), calculer_coeff_T(), calculer_Cp(), calculer_H(), calculer_lambda(), calculer_masse_volumique(), calculer_mu(), calculer_mu_sur_Sc(), calculer_nu(), calculer_nu_sur_Sc(), ch_temperature(), completer(), Fluide_Quasi_Compressible::completer(), completer_edo(), creer_champs_non_lus(), Fluide_Quasi_Compressible::discretiser(), Fluide_Weakly_Compressible::discretiser(), get_champ(), get_noms_champs_postraitables(), has_champ(), initialiser_inco_ch(), lire_motcle_non_standard(), loi_etat(), preparer_calcul(), preparer_pas_temps(), rho_n(), rho_np1(), and type_fluide().
eos_tools_
TRUST_Deriv< EOS_Tools_base > Fluide_Dilatable_base::eos_tools_ protected
Referenced by calculer_rho_face(), completer(), divu_discvit(), moyenne_vol(), prepare_pressure_edo(), preparer_pas_temps(), rho_discvit(), rho_face_n(), rho_face_np1(), Fluide_Quasi_Compressible::secmembre_divU_Z(), Fluide_Weakly_Compressible::secmembre_divU_Z(), write_mean_edo(), and Fluide_Weakly_Compressible::write_mean_edo().
EDO_Pth_
TRUST_Deriv< EDO_Pression_th_base > Fluide_Dilatable_base::EDO_Pth_ protected
Referenced by completer_edo(), prepare_pressure_edo(), preparer_pas_temps(), Fluide_Quasi_Compressible::Resoudre_EDO_PT(), and Fluide_Weakly_Compressible::Resoudre_EDO_PT().
output_file_
Nom Fluide_Dilatable_base::output_file_ protected
Referenced by completer_edo(), write_header_edo(), Fluide_Weakly_Compressible::write_header_edo(), write_mean_edo(), and Fluide_Weakly_Compressible::write_mean_edo().