TrioCFD: Terme_Source_PolyMAC_base Class Reference
Terme_Source_PolyMAC_base Class Reference
#include <Terme_Source_PolyMAC_base.h>
Public Member Functions
void completer () override
const Type_info * get_info () const override
Public Member Functions inherited from Source_base
virtual int a_pour_Champ_Fonc (const Motcle &mot, TRUST_Ref< Champ_base * > &ch_ref) const
virtual void associer_champ_rho (const Champ_base &champ_rho)
virtual void completer ()
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
virtual void resetTime (double t)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Terme_Source_PolyMAC_base() [1/2]
Terme_Source_PolyMAC_base::Terme_Source_PolyMAC_base ()
~Terme_Source_PolyMAC_base()
Terme_Source_PolyMAC_base::~Terme_Source_PolyMAC_base () override
Terme_Source_PolyMAC_base() [2/2]
Terme_Source_PolyMAC_base::Terme_Source_PolyMAC_base (const Iterateur_Source_base & iter_base) inline
References iter_.
Member Function Documentation
info()
const Type_info * Terme_Source_PolyMAC_base::info () static
get_info()
const Type_info * Terme_Source_PolyMAC_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Source_base.
self_cast() [1/2]
Terme_Source_PolyMAC_base & Terme_Source_PolyMAC_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Terme_Source_PolyMAC_base & Terme_Source_PolyMAC_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Terme_Source_PolyMAC_base::printOn (Sortie & os) const override protected virtual
DOES NOTHING - to override in derived classes.
Imprime la source sur un flot de sortie.
Parameters
(Sortie& os) le flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Source_base.
References Objet_U::que_suis_je().
readOn()
Entree & Terme_Source_PolyMAC_base::readOn (Entree & is) override protected virtual
DOES NOTHING - to override in derived classes.
Lecture d'un terme source sur un flot d'entree.
Parameters
(Entree& is) le flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Source_base.
has_interface_blocs()
int Terme_Source_PolyMAC_base::has_interface_blocs () const inline override virtual
Reimplemented from Source_base.
dimensionner_blocs()
void Terme_Source_PolyMAC_base::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl = {}) const inline override virtual
Reimplemented from Source_base.
ajouter_blocs()
void Terme_Source_PolyMAC_base::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = {}) const inline override virtual
Reimplemented from Source_base.
completer()
void Terme_Source_PolyMAC_base::completer () override virtual
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees: Source_base::associer_domaines(const Domaine_dis_base& ,const Domaine_Cl_dis_base&) Source_base::associer_pb(const Probleme_base&)
Reimplemented from Source_base.
References Iterateur_Source_base::associer(), Source_base::completer(), Iterateur_Source_base::completer_(), and iter_.
Member Data Documentation
info_obj
const Type_info Terme_Source_PolyMAC_base::info_obj static
iter_
TRUST_Deriv< Iterateur_Source_base > Terme_Source_PolyMAC_base::iter_ protected
Referenced by Terme_Puissance_Thermique_PolyMAC_base::associer_domaines(), Terme_Puissance_Thermique_PolyMAC_Elem::associer_domaines(), Terme_Source_Constituant_PolyMAC_Elem::associer_domaines(), Terme_Puissance_Thermique_PolyMAC_Elem::associer_pb(), Terme_Source_Constituant_PolyMAC_Elem::associer_pb(), completer(), and Terme_Source_PolyMAC_base().