TrioCFD: RK3_FT Class Reference
RK3_FT Class Reference
#include <RK3_FT.h>
Public Member Functions
const Type_info * get_info () const override
bool iterateTimeStep (bool &converged) override
const Type_info * get_info () const override
Public Member Functions inherited from Schema_Temps_base
virtual void changer_temps_courant (const double)
virtual bool corriger_dt_calcule (double &dt) const
int diffusion_implicite () const
double & facteur_securite_pas ()
double facteur_securite_pas () const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual int impr (Sortie &os, Probleme_base &pb) const
virtual void imprimer (Sortie &os) const
void imprimer (Sortie &os, Probleme_base &pb) const
virtual bool isStationary () const
const Nom & le_nom () const override
int limpr () const
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual int mettre_a_jour ()
int nb_impr () const
int nb_pas_dt () const
int nb_pas_dt_max () const
int nb_pas_dt_max_atteint () const
int nb_sauv_max () const
void nommer (const Nom &) override
double pas_de_temps () const
double & pas_temps_max ()
double pas_temps_max () const
double & pas_temps_min ()
double pas_temps_min () const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Schema_Temps_base ()
double seuil_statio () const
virtual int stop () const
int stop_lu () const
double temps_calcul () const
double temps_courant () const
int temps_final_atteint () const
double temps_impr () const
double temps_init () const
double temps_max () const
double temps_precedent () const
double temps_sauv () const
void update_critere_statio (const DoubleTab &tab_critere, Equation_base &equation)
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
(cas 7 de Williamson) s'ecrit :
q1=h f(x0)
x1=x0+b1 q1
q2=h f(x1) +a2 q1
x2=x1+b2 q2
q3=h f(x2)+a3 q2
x3=x2+b3 q3
 avec a1=0, a2=-5/9, a3=-153/128
                         b1=1/3, b2=15/16, b3=8/15
See also
Schema_Temps_base
Constructor & Destructor Documentation
RK3_FT()
RK3_FT::RK3_FT ()
~RK3_FT()
RK3_FT::~RK3_FT ()
Member Function Documentation
cree_instance()
Objet_U * RK3_FT::cree_instance () static
taille_memoire()
unsigned RK3_FT::taille_memoire () const override virtual
Reimplemented from RK3.
duplique()
int RK3_FT::duplique () const override virtual
Reimplemented from RK3.
info()
const Type_info * RK3_FT::info () static
get_info()
const Type_info * RK3_FT::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from RK3.
self_cast() [1/2]
RK3_FT & RK3_FT::self_cast (Objet_U & r) static
self_cast() [2/2]
const RK3_FT & RK3_FT::self_cast (const Objet_U & r) static
printOn()
Sortie & RK3_FT::printOn (Sortie & os) const override protected virtual
Surcharge Objet_U::printOn(Sortie&) Imprime le schema en temps sur un flot de sortie.
!! Attention n'est pas symetrique de la lecture !! On ecrit les differents parametres du schema en temps.
Parameters
(Sortie& os) le flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from RK3.
References Schema_Temps_base::printOn().
readOn()
Entree & RK3_FT::readOn (Entree & is) override protected virtual
Lecture d'un schema en temps a partir d'un flot d'entree.
Le format de lecture attendu est le suivant: { [Motcle valeur_reelle] } Les mots clefs peuvent etre: tinit, tmax, nb_pas_dt_max, dt_min, dt_max, dt_sauv, dt_impr, facsec, seuil_statio,
Parameters
(Entree& is) le flot d'entree
Returns
(Entree&) le flot d'entree modifie
Exceptions
accolade ouvrante attendue
motclef inconnu a cet endroit
Reimplemented from RK3.
References Schema_Temps_base::readOn().
faire_un_pas_de_temps_eqn_base()
int RK3_FT::faire_un_pas_de_temps_eqn_base (Equation_base & eqn) override virtual
Implements Schema_Temps_base.
iterateTimeStep()
bool RK3_FT::iterateTimeStep (bool & converged) override virtual
Effectue un pas de temps de Runge Kutta d'ordre 3, sur l'equation passee en parametre.
Le schema de Runge Kutta d'ordre 3 (cas 7 de Williamson) s'ecrit : q1=h f(x0) x1=x0+b1 q1 q2=h f(x1) +a2 q1 x2=x1+b2 q2 q3=h f(x2)+a3 q2 x3=x2+b3 q3 avec a1=0, a2=-5/9, a3=-153/128 b1=1/3, b2=15/16, b3=8/15
Parameters
(Equation_base& eqn) l'equation que l'on veut faire avancer d'un pas de temps
Returns
(int) renvoie toujours 1
Reimplemented from Schema_Temps_base.
References TRUSTVect< _TYPE_, _SIZE_ >::ajoute_sans_ech_esp_virt(), Domaine_Cl_dis_base::calculer_derivee_en_temps(), Transport_Interfaces_FT_Disc::calculer_vitesse_transport_interpolee(), Equation_base::derivee_en_temps_inco(), Equation_base::domaine_Cl_dis(), Schema_Temps_base::dt_, Probleme_base::equation(), Equation_base::equation_non_resolue(), Process::exit(), Equation_base::inconnue(), Equation_base::initTimeStep(), Transport_Interfaces_FT_Disc::maillage_interface(), Domaine_Cl_dis_base::mettre_a_jour(), Equation_base::mettre_a_jour(), Probleme_base::nombre_d_equations(), Schema_Temps_base::pb_base(), Objet_U::que_suis_je(), Schema_Temps_base::temps_courant_, Transport_Interfaces_FT_Disc::transporter_sans_changement_topologie(), and Schema_Temps_base::update_critere_statio().
faire_un_pas_de_temps_pb_couple()
int RK3_FT::faire_un_pas_de_temps_pb_couple (Probleme_Couple & pbc)
References TRUSTVect< _TYPE_, _SIZE_ >::ajoute_sans_ech_esp_virt(), Transport_Interfaces_FT_Disc::calculer_vitesse_transport_interpolee(), Equation_base::derivee_en_temps_inco(), Equation_base::domaine_Cl_dis(), Schema_Temps_base::dt_, Probleme_base::equation(), Equation_base::inconnue(), Equation_base::initTimeStep(), Transport_Interfaces_FT_Disc::maillage_interface(), Domaine_Cl_dis_base::mettre_a_jour(), Equation_base::mettre_a_jour(), TRUSTVect< _TYPE_, _SIZE_ >::mp_max_abs_vect(), Couplage_U::nb_problemes(), Probleme_base::nombre_d_equations(), Couplage_U::probleme(), Objet_U::que_suis_je(), Schema_Temps_base::set_stationnaire_atteint(), Schema_Temps_base::seuil_statio_, Schema_Temps_base::temps_courant_, Transport_Interfaces_FT_Disc::transporter_sans_changement_topologie(), and Champ_Inc_base::valeurs().
Member Data Documentation
info_obj
const Type_info RK3_FT::info_obj static