TrioCFD: Domaine_ALE Class Reference
Domaine_ALE Class Reference
#include <Domaine_ALE.h>
Public Member Functions
void clear () override
const Type_info * get_info () const override
Public Member Functions inherited from Domaine_32_64< int >
void ajouter (const DoubleTab_t &soms)
void ajouter (const DoubleTab_t &soms, IntVect_t &nums)
int associer_ (Objet_U &) override
Bord_Interne_t & bords_interne (int i)
void build_mc_mesh () const
void calculer_centres_gravite (DoubleTab_t &xp) const
void calculer_centres_gravite_aretes (DoubleTab_t &xa) const
void calculer_volumes (DoubleVect_t &volumes, DoubleVect_t &inv_volumes) const
SmallArrOfTID_t & chercher_aretes (const DoubleTab &pos, SmallArrOfTID_t &arr, int reel=0) const
SmallArrOfTID_t & chercher_elements (const DoubleTab &pos, SmallArrOfTID_t &elem, int reel=0) const
SmallArrOfTID_t & chercher_elements (const DoubleVect &pos, SmallArrOfTID_t &elem, int reel=0) const
int_t chercher_elements (double x, double y=0, double z=0, int reel=0) const
SmallArrOfTID_t & chercher_sommets (const DoubleTab &pos, SmallArrOfTID_t &som, int reel=0) const
int_t chercher_sommets (double x, double y=0, double z=0, int reel=0) const
virtual void clear ()
void construire_elem_virt_pe_num ()
void correct_type_of_borders_after_merge ()
virtual void creer_tableau_elements (Array_base &, RESIZE_OPTIONS opt=RESIZE_OPTIONS::COPY_INIT) const
virtual void creer_tableau_sommets (Array_base &, RESIZE_OPTIONS opt=RESIZE_OPTIONS::COPY_INIT) const
const TRUST_List< TRUST_Ref< Domaine_32_64 * > > & domaines_frontieres () const
void ecrire_noms_bords (Sortie &) const
int_t face_bords_interne_conjuguee (int_t face) const
void fill_from_list (std::list< Domaine_32_64 * > &lst)
const Frontiere_t & frontiere (int i) const
const Type_info * get_info () const override
const ArrOfInt_t & ind_faces_virt_bord () const
SmallArrOfTID_t & indice_elements (const IntTab &som, SmallArrOfTID_t &elem, int reel=0) const
void init_renum_perio ()
int nb_bords () const
int nb_faces_elem (int=0) const
int_t nb_faces_frontiere (Type_Face type) const
int_t nb_faces_specifiques () const
int_t nb_faces_specifiques (Type_Face type) const
int nb_groupes_faces () const
int nb_joints () const
int nb_raccords () const
int nb_som_elem () const
void renum (const IntVect_t &nums)
void renum_joint_common_items (const IntVect_t &nums, const int_t elem_offset)
void typer (const Nom &)
Public Member Functions inherited from Domaine_base
const Type_info * get_info () const override
const Nom & le_nom () const override
void nommer (const Nom &nom) override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Domaine_32_64< int >
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Domaine_32_64< int >
static int identifie_item_unique (IntList &item_possible, DoubleTab &coord_possible, const DoubleVect &coord_ref)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
~Domaine_ALE()
Domaine_ALE::~Domaine_ALE ()
Domaine_ALE()
Domaine_ALE::Domaine_ALE ()
References clear().
Member Function Documentation
cree_instance()
Objet_U * Domaine_ALE::cree_instance () static
taille_memoire()
unsigned Domaine_ALE::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Domaine_ALE::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Domaine_ALE::info () static
get_info()
const Type_info * Domaine_ALE::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Domaine_base.
self_cast() [1/2]
Domaine_ALE & Domaine_ALE::self_cast (Objet_U & r) static
self_cast() [2/2]
const Domaine_ALE & Domaine_ALE::self_cast (const Objet_U & r) static
printOn()
Sortie & Domaine_ALE::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Domaine_base.
References Domaine_32_64< int >::printOn().
readOn()
Entree & Domaine_ALE::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Domaine_base.
References Domaine_32_64< int >::readOn().
clear()
void Domaine_ALE::clear () override virtual
Reset the Domaine completely except for its name.
Various
Reimplemented from Domaine_32_64< int >.
References ALE_mesh_velocity, ALEjacobian_new, ALEjacobian_old, associate_eq, beam, Domaine_32_64< int >::clear(), Domaine_base::deformable_, dt_, eq, extrait_surf_dom_deformable_, field_ALE_projection_, les_bords_ALE, les_champs_front, les_elems_extrait_surf_reference_, mat, name_ALE_boundary_projection_, name_boundary_with_Neumann_BC, nb_bords_ALE, nbBeam, TRUSTTab< _TYPE_, _SIZE_ >::reset(), resumption, solv, som_faces_bords, str_mesh_model, update_or_not_matrix_coeffs_, vf, and TRUST_List< _CLASSE_ >::vide().
Referenced by Domaine_ALE().
get_dt()
const double & Domaine_ALE::get_dt () const inline
References dt_.
Referenced by Champ_front_ALE_Beam::remplir_vit_som_bord_ALE().
set_dt()
void Domaine_ALE::set_dt (double & dt) override virtual
Reimplemented from Domaine_base.
References dt_.
vitesse()
const DoubleTab & Domaine_ALE::vitesse () const inline
References ALE_mesh_velocity.
Referenced by Op_Conv_ALE_VEF::ajouterALE().
vitesse_faces() [1/2]
DoubleTab & Domaine_ALE::vitesse_faces () inline
References vf.
Referenced by Op_Conv_ALE_VEF::ajouterALE(), Navier_Stokes_std_ALE::div_ale_derivative(), and Navier_Stokes_std_ALE::mettre_a_jour().
vitesse_faces() [2/2]
const DoubleTab & Domaine_ALE::vitesse_faces () const inline
References vf.
mettre_a_jour()
void Domaine_ALE::mettre_a_jour (double temps, Domaine_dis_base & le_domaine_dis, Probleme_base & pb) override virtual
Reimplemented from Domaine_base.
References ALE_mesh_velocity, Domaine_32_64< int >::calculer_centres_gravite(), Faces_32_64< _SIZE_ >::Calculer_centres_gravite(), Domaine_VF::calculer_face_surfaces(), Domaine_VEF::calculer_h_carre(), calculer_vitesse(), calculer_vitesse_faces(), Domaine_32_64< int >::calculer_volumes(), Domaine_VEF::calculer_volumes_entrelaces(), Domaine_32_64< int >::coord(), Domaine_32_64< int >::creer_mes_domaines_frontieres(), Objet_U::dimension, TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Equation_base::domaine_Cl_dis(), dt_, Domaine_VF::elem_faces(), Probleme_base::equation(), Process::exit(), Periodique::face_associee(), Domaine_VF::face_normales(), Domaine_VF::face_sommets(), Domaine_VF::face_voisins(), Domaine_VEF::facette_normales(), Domaine_32_64< int >::invalide_octree(), Domaine_VF::inverse_volumes(), Domaine_Cl_dis_base::les_conditions_limites(), Domaine_VF::nb_faces(), Front_VF::nb_faces_tot(), Domaine_dis_base::nb_front_Cl(), Domaine_VF::nb_som_face(), Domaine_32_64< int >::nb_som_tot(), Probleme_base::nombre_d_equations(), Front_VF::num_face(), Domaine_VEF::rang_elem_non_std(), Domaine_Cl_VEF::remplir_normales_facettes_Cl(), Domaine_Cl_VEF::remplir_volumes_entrelaces_Cl(), TRUSTTab< _TYPE_, _SIZE_ >::reset(), Domaine_32_64< int >::sommets_, Domaine_32_64< int >::type_elem(), Domaine_VEF::type_elem(), Elem_geom_base_32_64< _SIZE_ >::type_face(), update_coord_dom_extrait_surface(), update_or_not_matrix_coeffs_, TRUST_Deriv< _CLASSE_ >::valeur(), Domaine_VF::volumes(), Domaine_VF::volumes_entrelaces(), Domaine_VF::xp(), and Domaine_VF::xv().
update_after_post()
void Domaine_ALE::update_after_post (double temps) override virtual
Reimplemented from Domaine_base.
References update_ALE_projection().
initialiser()
void Domaine_ALE::initialiser (double temps, Domaine_dis_base & le_domaine_dis, Probleme_base & pb) override virtual
Reimplemented from Domaine_base.
References ALE_mesh_velocity, associate_eq, associer_equation(), calculer_vitesse(), calculer_vitesse_faces(), Nom::contient(), MD_Vector_tools::creer_tableau_distribue(), Objet_U::dimension, Equation_base::domaine_Cl_dis(), Probleme_base::equation(), Process::exit(), Domaine_VF::face_sommets(), Probleme_base::get_champ(), Structural_dynamic_mesh_model::initDynamicMeshProblem(), Ch_front_input_ALE::initialiser(), Structural_dynamic_mesh_model::initMfrontBehaviour(), Domaine_32_64< int >::invalide_octree(), Objet_U::le_nom(), les_bords_ALE, les_champs_front, Domaine_Cl_dis_base::les_conditions_limites(), Domaine_32_64< int >::md_vector_elements(), Domaine_VF::md_vector_faces(), Domaine_32_64< int >::md_vector_sommets(), meshMotionModel_, name_boundary_with_Neumann_BC, nb_bords_ALE, Domaine_32_64< int >::nb_elem(), Domaine_VF::nb_faces(), Domaine_VF::nb_faces_tot(), Domaine_32_64< int >::nb_som(), Domaine_VF::nb_som_face(), Objet_U::que_suis_je(), Domaine_32_64< int >::rang_frontiere(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUST_Vector< _CLASSE_ >::size(), str_mesh_model, TRUST_Deriv< _CLASSE_ >::valeur(), and vf.
calculer_vitesse()
DoubleTab Domaine_ALE::calculer_vitesse (double temps, Domaine_dis_base & le_domaine_dis, Probleme_base & pb, bool & check_NoZero_ALE)
References associate_eq, associer_equation(), Domaine_32_64< int >::coord(), MD_Vector_tools::creer_tableau_distribue(), Objet_U::dimension, Equation_base::domaine_Cl_dis(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Probleme_base::equation(), Process::exit(), Domaine_VF::face_sommets(), Domaine_dis_base::frontiere_dis(), laplacien(), Objet_U::le_nom(), les_bords_ALE, les_champs_front, Domaine_Cl_dis_base::les_conditions_limites(), Domaine_32_64< int >::les_elems(), Domaine_32_64< int >::md_vector_sommets(), meshMotionModel_, TRUSTVect< _TYPE_, _SIZE_ >::mp_max_abs_vect(), nb_bords_ALE, Domaine_32_64< int >::nb_elem(), Domaine_VF::nb_faces(), Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), Domaine_32_64< int >::nb_som(), Domaine_32_64< int >::nb_som_elem(), Domaine_VF::nb_som_face(), Domaine_32_64< int >::nb_som_tot(), Front_VF::num_premiere_face(), Objet_U::que_suis_je(), Domaine_32_64< int >::rang_frontiere(), solveDynamicMeshProblem(), str_mesh_model, update_or_not_matrix_coeffs_, Debog::verifier(), and Structural_dynamic_mesh_model::x.
Referenced by initialiser(), and mettre_a_jour().
calculer_vitesse_faces()
DoubleTab & Domaine_ALE::calculer_vitesse_faces (DoubleTab & vit_maillage, int nb_faces, int nb_som_face, IntTab & face_sommets)
References Objet_U::dimension, TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), TRUSTVect< _TYPE_, _SIZE_ >::mp_max_abs_vect(), Debog::verifier(), and vf.
Referenced by initialiser(), and mettre_a_jour().
reading_vit_bords_ALE()
void Domaine_ALE::reading_vit_bords_ALE (Entree & is)
References TRUST_List< _CLASSE_ >::add(), TRUST_Vector< _CLASSE_ >::dimensionner(), Process::exit(), Domaine_32_64< int >::faces_bord(), les_bords_ALE, les_champs_front, nb_bords_ALE, and Domaine_32_64< int >::rang_frontiere().
Referenced by Imposer_vit_bords_ALE::interpreter_().
reading_solver_moving_mesh_ALE()
void Domaine_ALE::reading_solver_moving_mesh_ALE (Entree & is)
References Process::exit(), SolveurSys::nommer(), and solv.
Referenced by Solver_moving_mesh_ALE::interpreter_().
reading_beam_model()
void Domaine_ALE::reading_beam_model (Entree & is)
References beam, Process::exit(), Domaine_base::le_nom(), les_bords_ALE, nb_bords_ALE, nbBeam, and read_beam().
Referenced by Beam_model::interpreter_().
read_beam()
void Domaine_ALE::read_beam (Entree & is, int & count)
References TRUST_Vector< _CLASSE_ >::add(), beam, Process::exit(), Process::je_suis_maitre(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), and TRUST_Vector< _CLASSE_ >::size().
Referenced by reading_beam_model().
reading_projection_ALE_boundary()
void Domaine_ALE::reading_projection_ALE_boundary (Entree & is)
References TRUST_Vector< _CLASSE_ >::add(), TRUST_Vector< _CLASSE_ >::dimensionner(), Process::exit(), field_ALE_projection_, and name_ALE_boundary_projection_.
Referenced by Projection_ALE_boundary::interpreter_().
reading_ALE_Neumann_BC_for_grid_problem()
void Domaine_ALE::reading_ALE_Neumann_BC_for_grid_problem (Entree & is)
References TRUST_Vector< _CLASSE_ >::add(), Process::exit(), name_boundary_with_Neumann_BC, and TRUST_Vector< _CLASSE_ >::size().
Referenced by ALE_Neumann_BC_for_grid_problem::interpreter_().
reading_structural_dynamic_mesh_model()
void Domaine_ALE::reading_structural_dynamic_mesh_model (Entree & is)
References Structural_dynamic_mesh_model::addMaterialProperty(), Process::exit(), Structural_dynamic_mesh_model::getDensity(), meshMotionModel_, Structural_dynamic_mesh_model::setConfigurationResetDt(), Structural_dynamic_mesh_model::setDensity(), Structural_dynamic_mesh_model::setDtSafetyCoefficient(), Structural_dynamic_mesh_model::setGridDtMin(), Structural_dynamic_mesh_model::setInertialDamping(), Structural_dynamic_mesh_model::setMaxAddedMassRatio(), Structural_dynamic_mesh_model::setMfrontHypothesis(), Structural_dynamic_mesh_model::setMfrontLibraryPath(), Structural_dynamic_mesh_model::setMfrontModelName(), and str_mesh_model.
Referenced by Structural_dynamic_mesh_model::interpreter_().
update_ALE_projection() [1/2]
void Domaine_ALE::update_ALE_projection (double temps, Nom & name_ALE_boundary_projection, Champ_front_ALE_projection & field_ALE_projection, int nb_mode)
References Objet_U::dimension, Equation_base::domaine_dis(), MorEqn::equation(), Champ_front_ALE_projection::evaluate(), Operateur_base::flux_bords(), getEquation(), Sortie_Fichier_base::is_open(), Process::je_suis_maitre(), Operateur_Diff::l_op_base(), Operateur_Grad::l_op_base(), Objet_U::le_nom(), les_bords_ALE, modalForceProjectionALE_, Process::mp_sum(), nb_bords_ALE, Bords_32_64< _SIZE_ >::nb_faces(), Schema_Temps_base::nb_pas_dt(), Objet_U::nom_du_cas(), Navier_Stokes_std::operateur_diff(), Navier_Stokes_std::operateur_gradient(), Sortie_Fichier_base::ouvrir(), Equation_base::probleme(), Probleme_base::reprise_effectuee(), Probleme_base::schema_temps(), Sortie_Fichier_base::setf(), TRUSTVect< _TYPE_, _SIZE_ >::size(), and Domaine_VF::xv().
Referenced by update_after_post().
update_ALE_projection() [2/2]
void Domaine_ALE::update_ALE_projection (const double temps)
References Objet_U::dimension, Equation_base::domaine_dis(), MorEqn::equation(), field_ALE_projection_, Operateur_base::flux_bords(), getEquation(), Sortie_Fichier_base::is_open(), Process::je_suis_maitre(), Operateur_Diff::l_op_base(), Operateur_Grad::l_op_base(), Objet_U::le_nom(), les_bords_ALE, modalForceProjectionALE_, name_ALE_boundary_projection_, nb_bords_ALE, Bords_32_64< _SIZE_ >::nb_faces(), Schema_Temps_base::nb_pas_dt(), Objet_U::nom_du_cas(), Navier_Stokes_std::operateur_diff(), Navier_Stokes_std::operateur_gradient(), Sortie_Fichier_base::ouvrir(), Equation_base::probleme(), Probleme_base::reprise_effectuee(), Probleme_base::schema_temps(), Sortie_Fichier_base::setf(), TRUSTVect< _TYPE_, _SIZE_ >::size(), TRUST_Vector< _CLASSE_ >::size(), and Domaine_VF::xv().
laplacien()
DoubleTab & Domaine_ALE::laplacien (Domaine_dis_base & le_domaine_dis, Probleme_base & pb, const DoubleTab & vit_bords, DoubleTab & ch_som)
References Matrice_Morse_Sym::compacte(), MD_Vector_tools::creer_tableau_distribue(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Matrice_Morse::dimensionner(), Equation_base::domaine_Cl_dis(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_VF::elem_faces(), Probleme_base::equation(), Domaine_VF::face_normales(), Domaine_VF::face_sommets(), Domaine_VF::face_voisins(), Frontiere_dis_base::le_nom(), Domaine_Cl_dis_base::les_conditions_limites(), Domaine_32_64< int >::les_elems(), mat, Domaine_32_64< int >::md_vector_sommets(), TRUSTVect< _TYPE_, _SIZE_ >::mp_max_abs_vect(), name_boundary_with_Neumann_BC, Domaine_32_64< int >::nb_elem_tot(), Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), Domaine_32_64< int >::nb_som(), Domaine_32_64< int >::nb_som_elem(), Domaine_32_64< int >::nb_som_tot(), Front_VF::num_premiere_face(), Domaine_VEF::oriente_normale(), Matrice_Morse::remplir(), SolveurSys::resoudre_systeme(), Matrice_Sym::set_est_definie(), TRUST_Vector< _CLASSE_ >::size(), solv, Debog::verifier(), and Domaine_VF::volumes().
Referenced by calculer_vitesse().
update_or_not_matrix_coeffs()
int Domaine_ALE::update_or_not_matrix_coeffs () const inline
References update_or_not_matrix_coeffs_.
Referenced by Navier_Stokes_std_ALE::update_pressure_matrix().
update_ALEjacobians()
void Domaine_ALE::update_ALEjacobians (DoubleTab & NewValueOf_ALEjacobian_old, DoubleTab & NewValueOf_ALEjacobian_new, int TimeStepNr)
References ALEjacobian_new, ALEjacobian_old, and resumption.
Referenced by Implicite_ALE::first_special_treatment(), and Navier_Stokes_std_ALE::renewing_jacobians().
resumptionJacobian()
void Domaine_ALE::resumptionJacobian (DoubleTab & ValueOf_ALEjacobian_old, DoubleTab & ValueOf_ALEjacobian_new)
References ALEjacobian_new, ALEjacobian_old, and resumption.
Referenced by Navier_Stokes_std_ALE::reprendre().
getOldJacobian() [1/2]
const DoubleTab & Domaine_ALE::getOldJacobian () inline
References ALEjacobian_old.
Referenced by Navier_Stokes_std_ALE::div_ale_derivative(), Schema_Euler_explicite_ALE::faire_un_pas_de_temps_eqn_base(), Navier_Stokes_std_ALE::sauvegarder(), and Implicite_ALE::second_special_treatment().
getOldJacobian() [2/2]
const DoubleTab & Domaine_ALE::getOldJacobian () const inline
References ALEjacobian_old.
getNewJacobian() [1/2]
const DoubleTab & Domaine_ALE::getNewJacobian () inline
References ALEjacobian_new.
Referenced by Navier_Stokes_std_ALE::div_ale_derivative(), Schema_Euler_explicite_ALE::faire_un_pas_de_temps_eqn_base(), Implicite_ALE::first_special_treatment(), Navier_Stokes_std_ALE::renewing_jacobians(), Navier_Stokes_std_ALE::sauvegarder(), and Implicite_ALE::second_special_treatment().
getNewJacobian() [2/2]
const DoubleTab & Domaine_ALE::getNewJacobian () const inline
References ALEjacobian_new.
getMeshMotionModel()
int Domaine_ALE::getMeshMotionModel () const inline
References meshMotionModel_.
Referenced by Navier_Stokes_std_ALE::discretiser(), and Navier_Stokes_std_ALE::mettre_a_jour().
interpolationOnThe3DSurface()
DoubleVect Domaine_ALE::interpolationOnThe3DSurface (const int & i, const double & x, const double & y, const double & z, const DoubleTab & u, const DoubleTab & R) const
References beam.
Referenced by computeFluidForceOnBeam(), and Champ_front_ALE_Beam::remplir_vit_som_bord_ALE().
getBeamDisplacement()
const DoubleTab & Domaine_ALE::getBeamDisplacement (const int & i, const int & j) const
References beam.
Referenced by computeFluidForceOnBeam(), and Champ_front_ALE_Beam::remplir_vit_som_bord_ALE().
getBeamRotation()
const DoubleTab & Domaine_ALE::getBeamRotation (const int & i, const int & j) const
References beam.
Referenced by computeFluidForceOnBeam(), and Champ_front_ALE_Beam::remplir_vit_som_bord_ALE().
getBeamDirection()
const int & Domaine_ALE::getBeamDirection (const int & i) const inline
References beam.
getBeamVelocity()
DoubleVect & Domaine_ALE::getBeamVelocity (const int & i, const double & tps, const double & dt)
References beam, and computeFluidForceOnBeam().
Referenced by Champ_front_ALE_Beam::remplir_vit_som_bord_ALE().
getBeamNbModes()
const int & Domaine_ALE::getBeamNbModes (const int & i) const
References beam.
Referenced by computeFluidForceOnBeam(), and Champ_front_ALE_Beam::remplir_vit_som_bord_ALE().
getBeamName()
const Nom & Domaine_ALE::getBeamName (const int & i) const
References beam.
Referenced by computeFluidForceOnBeam(), and Champ_front_ALE_Beam::remplir_vit_som_bord_ALE().
getBeamNbBeam()
const int & Domaine_ALE::getBeamNbBeam () const
References nbBeam.
Referenced by Champ_front_ALE_Beam::remplir_vit_som_bord_ALE().
computeFluidForceOnBeam()
void Domaine_ALE::computeFluidForceOnBeam (const int & i)
References Operateur_base::ajouter(), beam, Equation_base::domaine_dis(), MorEqn::equation(), Operateur_base::flux_bords(), getBeamDisplacement(), getBeamName(), getBeamNbModes(), getBeamRotation(), getEquation(), interpolationOnThe3DSurface(), Process::je_suis_maitre(), Operateur_Diff::l_op_base(), Operateur_Grad::l_op_base(), Domaine_base::le_nom(), les_bords_ALE, nb_bords_ALE, Bords_32_64< _SIZE_ >::nb_faces(), Navier_Stokes_std::operateur_diff(), Navier_Stokes_std::operateur_gradient(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), resumption, TRUSTVect< _TYPE_, _SIZE_ >::size(), Champ_Inc_base::valeurs(), Navier_Stokes_std::vitesse(), and Domaine_VF::xv().
Referenced by getBeamVelocity().
getEquation()
Equation_base & Domaine_ALE::getEquation ()
References eq.
Referenced by computeFluidForceOnBeam(), and update_ALE_projection().
associer_equation()
void Domaine_ALE::associer_equation (const Equation_base & une_eq) inline
References eq.
Referenced by calculer_vitesse(), and initialiser().
update_coord_dom_extrait_surface()
void Domaine_ALE::update_coord_dom_extrait_surface ()
References Domaine_32_64< int >::coord_sommets(), extrait_surf_dom_deformable_, Objet_U::interprete(), Interprete_bloc::interprete_courant(), Objet_U::le_type(), Domaine_32_64< _SIZE_ >::les_elems(), les_elems_extrait_surf_reference(), Interprete_bloc::les_noms(), Domaine_32_64< _SIZE_ >::les_sommets(), NettoieNoeuds_32_64< _SIZE_ >::nettoie(), TRUST_Vector< _CLASSE_ >::size(), and Scatter::uninit_sequential_domain().
Referenced by mettre_a_jour().
getMeshPbPressure()
const DoubleVect & Domaine_ALE::getMeshPbPressure () const
References Structural_dynamic_mesh_model::getMeshPbPressure(), and str_mesh_model.
Referenced by Navier_Stokes_std_ALE::mettre_a_jour().
getMeshPbVonMises()
const DoubleVect & Domaine_ALE::getMeshPbVonMises () const
References Structural_dynamic_mesh_model::getMeshPbVonMises(), and str_mesh_model.
Referenced by Navier_Stokes_std_ALE::mettre_a_jour().
getMeshPbForceFace()
const DoubleTab & Domaine_ALE::getMeshPbForceFace () const
References Structural_dynamic_mesh_model::getMeshPbForceFace(), and str_mesh_model.
Referenced by Navier_Stokes_std_ALE::mettre_a_jour().
les_elems_extrait_surf_reference()
const IntTab & Domaine_ALE::les_elems_extrait_surf_reference () const inline
References les_elems_extrait_surf_reference_.
Referenced by update_coord_dom_extrait_surface().
set_les_elems_extrait_surf_reference()
void Domaine_ALE::set_les_elems_extrait_surf_reference (const IntTab & ref) inline
References les_elems_extrait_surf_reference_.
Referenced by Extraire_surface_ALE::interpreter_().
extrait_surf_dom_deformable()
bool Domaine_ALE::extrait_surf_dom_deformable () const inline
References extrait_surf_dom_deformable_.
set_extrait_surf_dom_deformable()
void Domaine_ALE::set_extrait_surf_dom_deformable (bool def) inline
References extrait_surf_dom_deformable_.
solveDynamicMeshProblem()
void Domaine_ALE::solveDynamicMeshProblem (const double temps, const DoubleTab & imposedVelocity, const IntVect & imposedVelocityTag, DoubleTab & outputMeshVelocity, const int nbSom, const int nbElem, const int nbSomElem, const IntTab & sommets, const int nbFace, const int nbSomFace, const IntTab & face_sommets)
References Structural_dynamic_mesh_model::a, Structural_dynamic_mesh_model::AddedMassRatioExceeded, Structural_dynamic_mesh_model::applyDtCoefficient(), Structural_dynamic_mesh_model::checkElemOrientation(), Structural_dynamic_mesh_model::computeCriticalDt(), Structural_dynamic_mesh_model::computeForceFaces(), Structural_dynamic_mesh_model::computeInternalForces(), Structural_dynamic_mesh_model::configurationResetDt, Objet_U::dimension, Structural_dynamic_mesh_model::doConfigurationReset, TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), MD_Vector_tools::echange_espace_virtuel(), MD_Vector_tools::EV_SOMME_ECHANGE, Structural_dynamic_mesh_model::ff, Domaine_32_64< int >::get_renum_som_perio(), Structural_dynamic_mesh_model::getDampingCoefficient(), Structural_dynamic_mesh_model::getDensity(), Structural_dynamic_mesh_model::getGridDtMin(), Structural_dynamic_mesh_model::getNbNodesPerElem(), Structural_dynamic_mesh_model::gridDt, Structural_dynamic_mesh_model::gridNStep, Structural_dynamic_mesh_model::gridResetTime, Structural_dynamic_mesh_model::gridTime, Structural_dynamic_mesh_model::isMassBuilt, Structural_dynamic_mesh_model::mass, Structural_dynamic_mesh_model::maxAddedMassRatio, Process::mp_min(), Process::mp_sum(), Structural_dynamic_mesh_model::nodalScaleMass, Structural_dynamic_mesh_model::setGlobalFields(), Structural_dynamic_mesh_model::setLocalFields(), Structural_dynamic_mesh_model::setMassElem(), str_mesh_model, Structural_dynamic_mesh_model::totalMass, Structural_dynamic_mesh_model::u, Structural_dynamic_mesh_model::v, Structural_dynamic_mesh_model::vp, and Structural_dynamic_mesh_model::x.
Referenced by calculer_vitesse().
Member Data Documentation
info_obj
const Type_info Domaine_ALE::info_obj static
dt_
double Domaine_ALE::dt_ protected
Referenced by clear(), get_dt(), mettre_a_jour(), and set_dt().
ALE_mesh_velocity
DoubleTab Domaine_ALE::ALE_mesh_velocity protected
Referenced by clear(), initialiser(), mettre_a_jour(), and vitesse().
vf
DoubleTab Domaine_ALE::vf protected
Referenced by calculer_vitesse_faces(), clear(), initialiser(), and vitesse_faces().
som_faces_bords
IntTab Domaine_ALE::som_faces_bords protected
Referenced by clear().
solv
SolveurSys Domaine_ALE::solv protected
Referenced by clear(), laplacien(), and reading_solver_moving_mesh_ALE().
mat
Matrice_Morse_Sym Domaine_ALE::mat protected
Referenced by clear(), and laplacien().
les_champs_front
TRUST_Vector<TRUST_Deriv< Champ_front_base > > Domaine_ALE::les_champs_front protected
Referenced by calculer_vitesse(), clear(), initialiser(), and reading_vit_bords_ALE().
nb_bords_ALE
int Domaine_ALE::nb_bords_ALE protected
Referenced by calculer_vitesse(), clear(), computeFluidForceOnBeam(), initialiser(), reading_beam_model(), reading_vit_bords_ALE(), and update_ALE_projection().
les_bords_ALE
Bords Domaine_ALE::les_bords_ALE protected
Referenced by calculer_vitesse(), clear(), computeFluidForceOnBeam(), initialiser(), reading_beam_model(), reading_vit_bords_ALE(), and update_ALE_projection().
update_or_not_matrix_coeffs_
int Domaine_ALE::update_or_not_matrix_coeffs_ protected
Referenced by calculer_vitesse(), clear(), mettre_a_jour(), and update_or_not_matrix_coeffs().
ALEjacobian_old
DoubleTab Domaine_ALE::ALEjacobian_old protected
Referenced by clear(), getOldJacobian(), resumptionJacobian(), and update_ALEjacobians().
ALEjacobian_new
DoubleTab Domaine_ALE::ALEjacobian_new protected
Referenced by clear(), getNewJacobian(), resumptionJacobian(), and update_ALEjacobians().
resumption
int Domaine_ALE::resumption protected
Referenced by clear(), computeFluidForceOnBeam(), resumptionJacobian(), and update_ALEjacobians().
nbBeam
int Domaine_ALE::nbBeam protected
Referenced by clear(), getBeamNbBeam(), and reading_beam_model().
beam
std::vector<Beam_model> Domaine_ALE::beam protected
Referenced by clear(), computeFluidForceOnBeam(), getBeamDirection(), getBeamDisplacement(), getBeamName(), getBeamNbModes(), getBeamRotation(), getBeamVelocity(), interpolationOnThe3DSurface(), read_beam(), and reading_beam_model().
str_mesh_model
Structural_dynamic_mesh_model Domaine_ALE::str_mesh_model protected
Referenced by calculer_vitesse(), clear(), getMeshPbForceFace(), getMeshPbPressure(), getMeshPbVonMises(), initialiser(), reading_structural_dynamic_mesh_model(), and solveDynamicMeshProblem().
eq
TRUST_Ref< Equation_base *> Domaine_ALE::eq protected
Referenced by associer_equation(), clear(), and getEquation().
field_ALE_projection_
Champs_front_ALE_projection Domaine_ALE::field_ALE_projection_ protected
Referenced by clear(), reading_projection_ALE_boundary(), and update_ALE_projection().
name_ALE_boundary_projection_
Noms Domaine_ALE::name_ALE_boundary_projection_ protected
Referenced by clear(), reading_projection_ALE_boundary(), and update_ALE_projection().
associate_eq
bool Domaine_ALE::associate_eq protected
Referenced by calculer_vitesse(), clear(), and initialiser().
name_boundary_with_Neumann_BC
Noms Domaine_ALE::name_boundary_with_Neumann_BC protected
Referenced by clear(), initialiser(), laplacien(), and reading_ALE_Neumann_BC_for_grid_problem().
modalForceProjectionALE_
SFichier Domaine_ALE::modalForceProjectionALE_ mutable protected
Referenced by update_ALE_projection().
modalForceBeam_
SFichier Domaine_ALE::modalForceBeam_ mutable protected
les_elems_extrait_surf_reference_
IntTab Domaine_ALE::les_elems_extrait_surf_reference_ protected
Referenced by clear(), les_elems_extrait_surf_reference(), and set_les_elems_extrait_surf_reference().
extrait_surf_dom_deformable_
bool Domaine_ALE::extrait_surf_dom_deformable_ = false protected
Referenced by clear(), extrait_surf_dom_deformable(), set_extrait_surf_dom_deformable(), and update_coord_dom_extrait_surface().
meshMotionModel_
int Domaine_ALE::meshMotionModel_ = 0 protected
Referenced by calculer_vitesse(), getMeshMotionModel(), initialiser(), and reading_structural_dynamic_mesh_model().