TrioCFD: Paroi_loi_WW_hyd_VDF Class Reference
Paroi_loi_WW_hyd_VDF Class Reference
#include <Paroi_loi_WW_hyd_VDF.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Paroi_std_hyd_VDF
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Turbulence_paroi_base
void associer_modele (const Modele_turbulence_hyd_base &)
int calculer_hyd (Champ_Fonc_base &, Champ_Fonc_base &)
int calculer_hyd (Champ_Inc_base &)
const Type_info * get_info () const override
virtual void imprimer_premiere_ligne_ustar (int, const TRUST_List< Nom > &, const Nom &) const
virtual void imprimer_ustar_mean_only (Sortie &, int, const TRUST_List< Nom > &, const Nom &) const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Paroi_std_hyd_VDF
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Turbulence_paroi_base
static void typer_lire_turbulence_paroi (TRUST_Deriv< Turbulence_paroi_base > &, const Modele_turbulence_hyd_base &, Entree &)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
~Paroi_loi_WW_hyd_VDF()
Paroi_loi_WW_hyd_VDF::~Paroi_loi_WW_hyd_VDF ()
Paroi_loi_WW_hyd_VDF()
Paroi_loi_WW_hyd_VDF::Paroi_loi_WW_hyd_VDF () inline
Member Function Documentation
cree_instance()
Objet_U * Paroi_loi_WW_hyd_VDF::cree_instance () static
taille_memoire()
unsigned Paroi_loi_WW_hyd_VDF::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Paroi_loi_WW_hyd_VDF::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Paroi_loi_WW_hyd_VDF::info () static
get_info()
const Type_info * Paroi_loi_WW_hyd_VDF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Paroi_hyd_base_VDF.
self_cast() [1/2]
Paroi_loi_WW_hyd_VDF & Paroi_loi_WW_hyd_VDF::self_cast (Objet_U & r) static
self_cast() [2/2]
const Paroi_loi_WW_hyd_VDF & Paroi_loi_WW_hyd_VDF::self_cast (const Objet_U & r) static
printOn()
Sortie & Paroi_loi_WW_hyd_VDF::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Paroi_hyd_base_VDF.
References Objet_U::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Paroi_loi_WW_hyd_VDF::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Paroi_hyd_base_VDF.
References Param::lire_avec_accolades_depuis(), Objet_U::que_suis_je(), and set_param().
set_param()
void Paroi_loi_WW_hyd_VDF::set_param (Param & param) override virtual
Reimplemented from Turbulence_paroi_base.
References Param::ajouter_flag(), impr, and Paroi_std_hyd_VDF::set_param().
Referenced by readOn().
calculer_hyd() [1/2]
int Paroi_loi_WW_hyd_VDF::calculer_hyd (DoubleTab & tab_k_eps) override virtual
Implements Turbulence_paroi_base.
calculer_hyd() [2/2]
int Paroi_loi_WW_hyd_VDF::calculer_hyd (DoubleTab & tab_nu_t, DoubleTab & tab_k) override virtual
Implements Turbulence_paroi_base.
References Objet_U::axi, calculer_local(), Turbulence_paroi_base::Cisaillement_paroi_, Objet_U::dimension, Domaine_VDF::dist_norm_bord(), Domaine_VDF::dist_norm_bord_axi(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Process::exit(), Domaine_VF::face_voisins(), Equation_base::inconnue(), Turbulence_paroi_base::le_dom_Cl_dis_, Turbulence_paroi_base::le_dom_dis_, TRUSTVect< _TYPE_, _SIZE_ >::local_min_vect(), Equation_base::milieu(), Turbulence_paroi_base::mon_modele_turb_hyd, Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), Domaine_VDF::orientation(), Turbulence_paroi_base::tab_u_star(), Dirichlet::val_imp(), TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), Champ_Inc_base::valeurs(), and Fluide_base::viscosite_cinematique().
init_lois_paroi_hydraulique()
int Paroi_loi_WW_hyd_VDF::init_lois_paroi_hydraulique () override protected virtual
Reimplemented from Paroi_std_hyd_VDF.
References A, B, Paroi_log_QDM::Cmu_, Turbulence_paroi_base::mon_modele_turb_hyd, and Y0.
preparer_calcul_hyd()
int Paroi_loi_WW_hyd_VDF::preparer_calcul_hyd (DoubleTab & tab) override protected virtual
Reimplemented from Paroi_std_hyd_VDF.
calculer_u_star_couche_puissance()
int Paroi_loi_WW_hyd_VDF::calculer_u_star_couche_puissance (double norm_vit, double d_visco, double dist, int face) protected
References A, B, and Turbulence_paroi_base::tab_u_star_.
Referenced by calculer_local().
calculer_couche_puissance()
int Paroi_loi_WW_hyd_VDF::calculer_couche_puissance (DoubleTab & nu_t, DoubleTab & tab_k, double dist, int elem, int face) protected
References Paroi_log_QDM::Cmu_, Paroi_log_QDM::Kappa_, and Turbulence_paroi_base::tab_u_star().
Referenced by calculer_local().
calculer_local()
int Paroi_loi_WW_hyd_VDF::calculer_local (double d_visco, DoubleTab & tab_nu_t, DoubleTab & tab_k, double norm_vit, double dist, int elem, int num_face) protected
References calculer_couche_puissance(), Paroi_std_hyd_VDF::calculer_sous_couche_visq(), calculer_u_star_couche_puissance(), Paroi_std_hyd_VDF::calculer_u_star_sous_couche_visq(), impr, and Y0.
Referenced by calculer_hyd().
Member Data Documentation
info_obj
const Type_info Paroi_loi_WW_hyd_VDF::info_obj static
A
double Paroi_loi_WW_hyd_VDF::A protected
Referenced by calculer_u_star_couche_puissance(), and init_lois_paroi_hydraulique().
B
double Paroi_loi_WW_hyd_VDF::B protected
Referenced by calculer_u_star_couche_puissance(), and init_lois_paroi_hydraulique().
Y0
double Paroi_loi_WW_hyd_VDF::Y0 protected
Referenced by calculer_local(), and init_lois_paroi_hydraulique().
impr
int Paroi_loi_WW_hyd_VDF::impr protected
Referenced by calculer_local(), and set_param().