TrioCFD: Masse_VDF_Face Class Reference
Masse_VDF_Face Class Reference
#include <Masse_VDF_Face.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Solveur_Masse_base
virtual DoubleTab & appliquer (DoubleTab &) const
virtual void assembler ()
const Type_info * get_info () const override
virtual void mettre_a_jour (double temps)
virtual void resetTime (double temps)
void set_name_of_coefficient_temporel (const Nom &)
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Masse_VDF_Face()
Masse_VDF_Face::Masse_VDF_Face ()
~Masse_VDF_Face()
Masse_VDF_Face::~Masse_VDF_Face ()
Member Function Documentation
cree_instance()
Objet_U * Masse_VDF_Face::cree_instance () static
taille_memoire()
unsigned Masse_VDF_Face::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Masse_VDF_Face::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Masse_VDF_Face::info () static
get_info()
const Type_info * Masse_VDF_Face::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Masse_VDF_base.
self_cast() [1/2]
Masse_VDF_Face & Masse_VDF_Face::self_cast (Objet_U & r) static
self_cast() [2/2]
const Masse_VDF_Face & Masse_VDF_Face::self_cast (const Objet_U & r) static
printOn()
Sortie & Masse_VDF_Face::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Masse_VDF_base.
References Objet_U::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Masse_VDF_Face::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Masse_VDF_base.
completer()
void Masse_VDF_Face::completer () override virtual
Reimplemented from Solveur_Masse_base.
References Solveur_Masse_Face_proto::associer_masse_proto(), Masse_VDF_base::le_dom_VDF, and TRUST_Ref< _CLASSE_ >::valeur().
appliquer_impl()
DoubleTab & Masse_VDF_Face::appliquer_impl (DoubleTab & sm) const override virtual
Implements Solveur_Masse_base.
References Solveur_Masse_Face_proto::appliquer_impl_proto(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), MorEqn::equation(), Process::exit(), Masse_VDF_base::le_dom_Cl_VDF, Masse_VDF_base::le_dom_VDF, TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Equation_base::milieu(), Domaine_VF::nb_faces(), Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), TRUST_Ref< _CLASSE_ >::non_nul(), Front_VF::num_premiere_face(), Milieu_base::porosite_face(), Domaine_VF::premiere_face_int(), TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), and Domaine_VF::volumes_entrelaces().
dimensionner_blocs()
void Masse_VDF_Face::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl) const override virtual
Reimplemented from Masse_VDF_base.
References Masse_VDF_base::dimensionner_blocs(), Solveur_Masse_Face_proto::dimensionner_blocs_proto(), and MorEqn::equation().
ajouter_blocs()
void Masse_VDF_Face::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, double dt, const tabs_t & semi_impl, int resoudre_en_increments) const override virtual
Reimplemented from Masse_VDF_base.
References Masse_ajoutee_base::ajouter(), Masse_VDF_base::ajouter_blocs(), Equation_base::champ_conserve(), Objet_U::dimension, TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), MorEqn::equation(), Pb_Multiphase::equation_masse(), Probleme_base::get_correlation(), Nom::getString(), Probleme_base::has_correlation(), Equation_base::inconnue(), Field_base::le_nom(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Milieu_base::masse_volumique(), Equation_base::milieu(), Champ_Proto::passe(), Champ_Inc_base::passe(), Milieu_base::porosite_face(), and Champ_Inc_base::valeurs().
corriger_solution()
DoubleTab & Masse_VDF_Face::corriger_solution (DoubleTab & x, const DoubleTab & y, int incr) const override virtual
Reimplemented from Solveur_Masse_base.
References Solveur_Masse_base::corriger_solution(), Objet_U::dimension, MorEqn::equation(), Equation_base::inconnue(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), and Champ_Inc_base::valeurs().
Member Data Documentation
info_obj
const Type_info Masse_VDF_Face::info_obj static