TrioCFD: Lec_Diffuse_base Class Reference
Lec_Diffuse_base Class Reference abstract
#include <Lec_Diffuse_base.h>
Public Member Functions
int get (char *buf, std::streamsize bufsize) override
const Type_info * get_info () const override
void set_bin (bool bin) override
void set_check_types (bool flag) override
const Type_info * get_info () const override
const Type_info * get_info () const override
virtual int get (char *buf, std::streamsize bufsize)
void set_bin (bool bin) override
virtual void set_check_types (bool flag)
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Entree
virtual int error_handle_ (int fail_flag)
Protected Member Functions inherited from AbstractIO
template<typename _TYPE_ >
bool must_convert () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Attributes inherited from AbstractIO
bool avoid_conversion_
Detailed Description
sur tous les processeurs. Attention, les methodes operator>>(), get(), eof(), good() et bad() doivent etre appelees simultanement sur tous les processeurs. Les classes derivees doivent reimplementer get_entree_master(). La methode get_entree_master() doit renvoyer une reference a l'entree qui sert de source sur le processeur maitre, elle n'est jamais appellee sur les autres processeurs. Attention: l'entree source doit avoir set_error_action(ERROR_CONTINUE)
Constructor & Destructor Documentation
~Lec_Diffuse_base()
Lec_Diffuse_base::~Lec_Diffuse_base () override
Lec_Diffuse_base() [1/2]
Lec_Diffuse_base::Lec_Diffuse_base () protected
ne fait rien (constructeur protege car c'est une classe de base)
Lec_Diffuse_base() [2/2]
Lec_Diffuse_base::Lec_Diffuse_base (const Lec_Diffuse_base &) protected default
Member Function Documentation
info()
const Type_info * Lec_Diffuse_base::info () static
get_info()
const Type_info * Lec_Diffuse_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from EFichier.
Reimplemented in LecFicDiffuse, LecFicDiffuse_JDD, and LecFicDiffuseBin.
self_cast() [1/2]
Lec_Diffuse_base & Lec_Diffuse_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Lec_Diffuse_base & Lec_Diffuse_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Lec_Diffuse_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from EFichier.
Reimplemented in LecFicDiffuse, LecFicDiffuse_JDD, and LecFicDiffuseBin.
readOn()
Entree & Lec_Diffuse_base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from EFichier.
Reimplemented in LecFicDiffuse, LecFicDiffuse_JDD, and LecFicDiffuseBin.
operator>>() [1/16]
Entree & Lec_Diffuse_base::operator>> (True_int & ob) override virtual
Reimplemented from Entree.
operator>>() [2/16]
Entree & Lec_Diffuse_base::operator>> (long & ob) override virtual
Reimplemented from Entree.
operator>>() [3/16]
Entree & Lec_Diffuse_base::operator>> (long long & ob) override virtual
Reimplemented from Entree.
operator>>() [4/16]
Entree & Lec_Diffuse_base::operator>> (float & ob) override virtual
Reimplemented from Entree.
operator>>() [5/16]
Entree & Lec_Diffuse_base::operator>> (double & ob) override virtual
Reimplemented from Entree.
get() [1/6]
int Lec_Diffuse_base::get (True_int * ob, std::streamsize n) override virtual
Reimplemented from Entree.
Referenced by Champ_front_recyclage::lire_fichier_format2(), Champ_front_recyclage::lire_fichier_format3(), and Triple_Line_Model_FT_Disc::readOn().
get() [2/6]
int Lec_Diffuse_base::get (long * ob, std::streamsize n) override virtual
Reimplemented from Entree.
get() [3/6]
int Lec_Diffuse_base::get (long long * ob, std::streamsize n) override virtual
Reimplemented from Entree.
get() [4/6]
int Lec_Diffuse_base::get (float * ob, std::streamsize n) override virtual
Reimplemented from Entree.
get() [5/6]
int Lec_Diffuse_base::get (double * ob, std::streamsize n) override virtual
Reimplemented from Entree.
get() [6/6]
int Lec_Diffuse_base::get (char * ob, std::streamsize bufsize) override virtual
Lecture d'une chaine dans ostream_ bufsize est la taille du buffer alloue pour ob (y compris.
le caractere 0 final). La chaine contient toujours un 0 meme en cas d'echec. La methode renvoie 1 si la lecture est bonne, 0 sinon. Si le buffer est trop petit, pour l'instant on fait exit() mais par la suite on pourra tester: si strlen(ob)==bufsize-1, alors refaire lire() jusqu'a arriver au bout. Si le lire() suivant renvoie une chaine de longueur nulle, cela signifie que la taille de la chaine etait exactement bufsize-1. Attention: le comportement est different en binaire et en ascii. En binaire, on lit la chaine jusqu'au prochain '\0'. En ascii, on lit la chaine jusqu'au prochain separateur (espace, tab, fin ligne)
Reimplemented from Entree.
References Entree::diffuse_, Entree::ERROR_CONTINUE, Entree::error_handle(), Process::exit(), Entree::get(), get_entree_master(), Entree::get_error_action(), and Process::je_suis_maitre().
eof()
int Lec_Diffuse_base::eof () override virtual
Reimplemented from Entree_Fichier_base.
References Entree::diffuse_, Entree::eof(), get_entree_master(), and Process::je_suis_maitre().
Referenced by Champ_Don_lu::readOn().
good()
int Lec_Diffuse_base::good () override virtual
Reimplemented from Entree_Fichier_base.
References Entree::diffuse_, get_entree_master(), Entree::good(), and Process::je_suis_maitre().
Referenced by VerifierCoin::interpreter_().
fail()
int Lec_Diffuse_base::fail () override virtual
Reimplemented from Entree_Fichier_base.
References Entree::diffuse_, Entree::fail(), get_entree_master(), and Process::je_suis_maitre().
set_bin()
void Lec_Diffuse_base::set_bin (bool bin) override virtual
appelle get_entree_master().
set_bin(bin)
Reimplemented from Entree.
References Entree::diffuse_, get_entree_master(), Process::je_suis_maitre(), and Entree::set_bin().
Referenced by Champ_front_lu::initialiser(), LecFicDiffuseBin::LecFicDiffuseBin(), Modele_turbulence_hyd_base::lire_distance_paroi(), Modele_turbulence_hyd_Longueur_Melange_VEF::lire_distance_paroi(), and Modele_Lam_Bremhorst_VEF::lire_distance_paroi().
set_check_types()
void Lec_Diffuse_base::set_check_types (bool flag) override virtual
appelle get_entree_master().
set_check_types(flag)
Reimplemented from Entree.
References get_entree_master(), and Entree::set_check_types().
Referenced by mon_main::dowork(), Execute_parallel::interpreter(), and Lire_Fichier::interpreter().
set_diffuse()
void Lec_Diffuse_base::set_diffuse (bool diffuse) override virtual
ToDo TMA : commenter.
Reimplemented from Entree.
References Entree::diffuse_.
operator=()
Lec_Diffuse_base & Lec_Diffuse_base::operator= (const Lec_Diffuse_base &) protected
erreur
References Process::exit().
get_entree_master()
virtual Entree & Lec_Diffuse_base::get_entree_master () protected pure virtual
Implemented in LecFicDiffuse, and LecFicDiffuse_JDD.
Referenced by eof(), fail(), get(), good(), set_bin(), and set_check_types().
operator>>() [6/16]
Entree & Entree::operator>> (Entree &(*)(Entree &) f)
operator>>() [7/16]
Entree & Entree::operator>> (istream &(*)(istream &) f)
operator>>() [8/16]
Entree & Entree::operator>> (ios &(*)(ios &) f)
operator>>() [9/16]
template<typename T > Entree & Entree::operator>> (const TRUST_Ref< T > &) inline
operator>>() [10/16]
Entree & Entree::operator>> (const TRUST_Ref_Objet_U &) inline
operator>>() [11/16]
Entree & Entree::operator>> (True_int & ob) virtual
Reimplemented from Entree.
operator>>() [12/16]
Entree & Entree::operator>> (long & ob) virtual
Reimplemented from Entree.
operator>>() [13/16]
Entree & Entree::operator>> (long long & ob) virtual
Reimplemented from Entree.
operator>>() [14/16]
Entree & Entree::operator>> (float & ob) virtual
Reimplemented from Entree.
operator>>() [15/16]
Entree & Entree::operator>> (double & ob) virtual
Reimplemented from Entree.
operator>>() [16/16]
Entree & Entree::operator>> (Objet_U & ob) final virtual
Reimplemented from Entree.
Member Data Documentation
info_obj
const Type_info Lec_Diffuse_base::info_obj static