TrioCFD: Source_Diffusion_supplementaire_echelle_temp_turb Class Reference
Source_Diffusion_supplementaire_echelle_temp_turb Class Reference abstract
#include <Source_Diffusion_supplementaire_echelle_temp_turb.h>
Public Member Functions
void completer () override
const Type_info * get_info () const override
Public Member Functions inherited from Sources_Multiphase_base
const Type_info * get_info () const override
void mettre_a_jour (double temps) override
Public Member Functions inherited from Source_base
virtual int a_pour_Champ_Fonc (const Motcle &mot, TRUST_Ref< Champ_base * > &ch_ref) const
virtual void associer_champ_rho (const Champ_base &champ_rho)
virtual void completer ()
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
virtual void resetTime (double t)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
See also
Operateur_base
Constructor & Destructor Documentation
Source_Diffusion_supplementaire_echelle_temp_turb()
Source_Diffusion_supplementaire_echelle_temp_turb::Source_Diffusion_supplementaire_echelle_temp_turb ()
~Source_Diffusion_supplementaire_echelle_temp_turb()
Source_Diffusion_supplementaire_echelle_temp_turb::~Source_Diffusion_supplementaire_echelle_temp_turb () override
Member Function Documentation
info()
const Type_info * Source_Diffusion_supplementaire_echelle_temp_turb::info () static
get_info()
const Type_info * Source_Diffusion_supplementaire_echelle_temp_turb::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Sources_Multiphase_base.
Reimplemented in Diffusion_supplementaire_echelle_temp_turb_VDF.
self_cast() [1/2]
Source_Diffusion_supplementaire_echelle_temp_turb & Source_Diffusion_supplementaire_echelle_temp_turb::self_cast (Objet_U & r) static
self_cast() [2/2]
const Source_Diffusion_supplementaire_echelle_temp_turb & Source_Diffusion_supplementaire_echelle_temp_turb::self_cast (const Objet_U & r) static
printOn()
Sortie & Source_Diffusion_supplementaire_echelle_temp_turb::printOn (Sortie & os) const override protected virtual
DOES NOTHING - to override in derived classes.
Imprime la source sur un flot de sortie.
Parameters
(Sortie& os) le flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Sources_Multiphase_base.
Reimplemented in Diffusion_supplementaire_echelle_temp_turb_VDF.
Referenced by Diffusion_supplementaire_echelle_temp_turb_PolyMAC_P0::printOn(), and Diffusion_supplementaire_echelle_temp_turb_VDF::printOn().
readOn()
Entree & Source_Diffusion_supplementaire_echelle_temp_turb::readOn (Entree & is) override protected virtual
DOES NOTHING - to override in derived classes.
Lecture d'un terme source sur un flot d'entree.
Parameters
(Entree& is) le flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Sources_Multiphase_base.
Reimplemented in Diffusion_supplementaire_echelle_temp_turb_VDF.
Referenced by Diffusion_supplementaire_echelle_temp_turb_PolyMAC_P0::readOn(), and Diffusion_supplementaire_echelle_temp_turb_VDF::readOn().
dimensionner_blocs()
void Source_Diffusion_supplementaire_echelle_temp_turb::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl = {}) const override virtual
Reimplemented from Source_base.
Reimplemented in Diffusion_supplementaire_echelle_temp_turb_VDF.
References Matrix_tools::allocate_morse_matrix(), TRUSTTab< _TYPE_, _SIZE_ >::append_line(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), MorEqn::equation(), Probleme_base::get_champ(), Equation_base::inconnue(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Matrice_Morse::nb_colonnes(), Equation_base::probleme(), Champ_Inc_base::valeurs(), and Champ_Proto::valeurs().
Referenced by Diffusion_supplementaire_echelle_temp_turb_PolyMAC_P0::dimensionner_blocs().
ajouter_blocs()
void Source_Diffusion_supplementaire_echelle_temp_turb::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = {}) const override pure virtual
Reimplemented from Source_base.
Implemented in Diffusion_supplementaire_echelle_temp_turb_PolyMAC_P0, and Diffusion_supplementaire_echelle_temp_turb_VDF.
completer()
void Source_Diffusion_supplementaire_echelle_temp_turb::completer () override virtual
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees: Source_base::associer_domaines(const Domaine_dis_base& ,const Domaine_Cl_dis_base&) Source_base::associer_pb(const Probleme_base&)
Reimplemented from Source_base.
References Equation_base::domaine_Cl_dis(), MorEqn::equation(), f_grad_tau_fixe, Domaine_Cl_dis_base::les_conditions_limites(), Domaine_Cl_dis_base::nb_cond_lim(), and TRUST_Deriv< _CLASSE_ >::valeur().
Member Data Documentation
info_obj
const Type_info Source_Diffusion_supplementaire_echelle_temp_turb::info_obj static
limiter_
double Source_Diffusion_supplementaire_echelle_temp_turb::limiter_ = 5 protected
limiter_tau_
double Source_Diffusion_supplementaire_echelle_temp_turb::limiter_tau_ = 1.e-6 protected
sigma_tau_
double Source_Diffusion_supplementaire_echelle_temp_turb::sigma_tau_ = .5 protected
Referenced by Diffusion_supplementaire_echelle_temp_turb_PolyMAC_P0::ajouter_blocs().
f_grad_tau_fixe
int Source_Diffusion_supplementaire_echelle_temp_turb::f_grad_tau_fixe = 1 protected
Referenced by Diffusion_supplementaire_echelle_temp_turb_PolyMAC_P0::ajouter_blocs(), and completer().