TrioCFD: Source_Con_Phase_field Class Reference
Source_Con_Phase_field Class Reference
#include <Source_Con_Phase_field.h>
Public Member Functions
const Type_info * get_info () const override
void mettre_a_jour (double) override
const Type_info * get_info () const override
Public Member Functions inherited from Source_base
virtual int a_pour_Champ_Fonc (const Motcle &mot, TRUST_Ref< Champ_base * > &ch_ref) const
virtual void associer_champ_rho (const Champ_base &champ_rho)
virtual void completer ()
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
virtual void resetTime (double t)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
void calculer_alpha_gradC_carre (DoubleTab &) const
void calculer_div_alpha_gradC (DoubleTab &) const
void calculer_div_alpha_rho_gradC (DoubleTab &) const
virtual void calculer_mutilde (DoubleTab &) const
void calculer_pression_thermo (DoubleTab &) const
virtual int non_lin_gmres (const DoubleTab &, const DoubleTab &, const Matrice_Morse &, DoubleTab &, DoubleTab &)
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Source_Con_Phase_field()
Source_Con_Phase_field::Source_Con_Phase_field ()
~Source_Con_Phase_field()
Source_Con_Phase_field::~Source_Con_Phase_field ()
Member Function Documentation
cree_instance()
Objet_U * Source_Con_Phase_field::cree_instance () static
taille_memoire()
unsigned Source_Con_Phase_field::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Source_Con_Phase_field::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Source_Con_Phase_field::info () static
get_info()
const Type_info * Source_Con_Phase_field::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Source_Con_Phase_field_base.
self_cast() [1/2]
Source_Con_Phase_field & Source_Con_Phase_field::self_cast (Objet_U & r) static
self_cast() [2/2]
const Source_Con_Phase_field & Source_Con_Phase_field::self_cast (const Objet_U & r) static
printOn()
Sortie & Source_Con_Phase_field::printOn (Sortie & os) const override protected virtual
DOES NOTHING - to override in derived classes.
Imprime la source sur un flot de sortie.
Parameters
(Sortie& os) le flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Source_Con_Phase_field_base.
References Objet_U::que_suis_je().
readOn()
Entree & Source_Con_Phase_field::readOn (Entree & is) override protected virtual
DOES NOTHING - to override in derived classes.
Lecture d'un terme source sur un flot d'entree.
Parameters
(Entree& is) le flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Source_Con_Phase_field_base.
References a0Eq, a1Eq, a2Eq, alpha, alpha_ref, alphaMatrix, angle_alphaMatrix, angle_phi, angle_psi, beta, betaMatrix, coeff_auto_diffusion, Convection_Diffusion_Concentration::constituant(), couplage_, diagonal_coeff, dWdc, dWdc_defaut(), dWdc_general(), dWdc_naire, dWdc_naire_analytique_quater, dWdc_naire_analytique_quaternaire(), dWdc_naire_analytique_ter, dWdc_naire_analytique_ternaire(), dWdc_naire_defaut(), eps_, epsGMRES, epsilon_, eq1, eq2, Process::exit(), gmres_, implicitation_, kappa, kappa_forme_expr_, kappa_func_auto_diffusion(), kappa_func_c, kappa_func_c_defaut(), kappa_func_c_general(), kappa_moy_, kappaMatrix, kappaMatrix_func_c, le_probleme2, Table::lire_f(), maxX, minX, molarVolume, mult_kappa, Constituant::nb_constituants(), nb_equation_CH, nit, nkr, potentiel_chimique_expr_, prefactor, rec_max, rec_min, Motcles::search(), TRUSTVect< _TYPE_, _SIZE_ >::size(), temperature, tpsaff, type_alpha_rotation_, type_kappa_, type_kappa_auto_diffusion_, type_potentiel_analytique_, type_systeme_naire_, x0Eq, x1Eq, and x2Eq.
associer_pb()
void Source_Con_Phase_field::associer_pb (const Probleme_base & pb) override virtual
Implements Source_base.
References boussi_, couplage_, diff_boussi_, Navier_Stokes_phase_field::drhodc(), drhodc_, eps_, epsGMRES, epsilon_, Process::exit(), g_, Navier_Stokes_phase_field::get_boussi_(), Navier_Stokes_phase_field::get_diff_boussi_(), Navier_Stokes_phase_field::get_g_(), Convection_Diffusion_Phase_field::get_mutype_(), Navier_Stokes_phase_field::getset_terme_source_(), gmres_, implicitation_, kappa_ind, kappa_moy_, le_probleme2, mult_kappa, mutype_, nit, nkr, rec_max, rec_min, Navier_Stokes_phase_field::rho0(), rho0, tpsaff, type_kappa_, type_kappa_auto_diffusion_, and type_systeme_naire_.
ajouter()
DoubleTab & Source_Con_Phase_field::ajouter (DoubleTab & resu) const override virtual
Reimplemented from Source_base.
References accr.
Referenced by calculer().
calculer()
DoubleTab & Source_Con_Phase_field::calculer (DoubleTab & resu) const override virtual
Reimplemented from Source_base.
References ajouter().
mettre_a_jour()
void Source_Con_Phase_field::mettre_a_jour (double temps) override virtual
DOES NOTHING - to override in derived classes.
Mise a jour en temps du terme source.
Parameters
(double) le pas de temps de mise a jour
Reimplemented from Source_base.
References le_probleme2, Champ_Fonc_base::mettre_a_jour(), and Convection_Diffusion_Phase_field::set_mutilde_().
premier_demi_dt()
void Source_Con_Phase_field::premier_demi_dt () override virtual
Calcule le premier demi pas de temps dans le cas implicite Calcule le pas de temps dans le cas explicite.
Implements Source_Con_Phase_field_base.
References accr, assembler_matrice_point_fixe(), calculer_div_alpha_gradC(), calculer_point_fixe(), calculer_u2_elem(), Domaine_32_64< _SIZE_ >::creer_tableau_elements(), Domaine_dis_base::domaine(), gmres_, implicitation_, Convection_Diffusion_Concentration::inconnue(), le_dom_VDF, le_probleme2, Domaine_dis_base::nb_elem_tot(), Convection_Diffusion_Phase_field::set_c_demi(), Convection_Diffusion_Phase_field::set_div_alpha_gradC(), Convection_Diffusion_Phase_field::set_mutilde_(), Convection_Diffusion_Phase_field::set_mutilde_demi(), TRUSTVect< _TYPE_, _SIZE_ >::size_totale(), u_carre_, TRUST_Ref< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), and Champ_Inc_base::valeurs().
get_u_carre()
const DoubleVect & Source_Con_Phase_field::get_u_carre () inline override virtual
Implements Source_Con_Phase_field_base.
References u_carre_.
Referenced by Source_Qdm_VDF_Phase_field::methode_1().
get_maxX()
const DoubleVect & Source_Con_Phase_field::get_maxX () inline
References maxX.
Referenced by RK3_MassRedistrib::faire_un_pas_de_temps_eqn_base(), and Schema_Euler_explicite_Phase_field::faire_un_pas_de_temps_eqn_base().
get_minX()
const DoubleVect & Source_Con_Phase_field::get_minX () inline
References minX.
Referenced by RK3_MassRedistrib::faire_un_pas_de_temps_eqn_base(), and Schema_Euler_explicite_Phase_field::faire_un_pas_de_temps_eqn_base().
get_type_systeme_naire()
const int & Source_Con_Phase_field::get_type_systeme_naire () inline
References type_systeme_naire_.
Referenced by Source_Gravite_PF_VDF::ajouter(), Navier_Stokes_phase_field::calculer_rho(), Source_Qdm_VDF_Phase_field::methode_1(), Source_Qdm_VDF_Phase_field::methode_2(), Source_Qdm_VDF_Phase_field::methode_3(), and Source_Qdm_VDF_Phase_field::methode_4().
drhodc()
double Source_Con_Phase_field::drhodc (const int n_elem) const inline
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), drhodc_, Process::exit(), and TRUSTTab< _TYPE_, _SIZE_ >::nb_dim().
Referenced by calculer_mutilde(), calculer_mutilde_demi(), and Source_Qdm_VDF_Phase_field::methode_1().
calculer_champ_fonc_c()
void Source_Con_Phase_field::calculer_champ_fonc_c (const double t, Champ_Don_base & champ_fonc_c, const DoubleTab & val_c) const override virtual
Implements Source_Con_Phase_field_base.
References Process::exit(), Table::isfonction(), le_dom_VDF, TRUSTVect< _TYPE_, _SIZE_ >::line_size(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Domaine_dis_base::nb_elem(), Champ_Fonc_Tabule::table(), Table::val(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), Table::valeurs(), and Domaine_VF::xp().
associer_domaines()
void Source_Con_Phase_field::associer_domaines (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis) override protected virtual
Implements Source_base.
References le_dom_Cl_VDF, and le_dom_VDF.
laplacien()
DoubleTab & Source_Con_Phase_field::laplacien (const DoubleTab & F, DoubleTab & resu) const protected
References Solveur_Masse_base::appliquer(), Operateur_Div::calculer(), Operateur_Grad::calculer(), Convection_Diffusion_Concentration::constituant(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Navier_Stokes_std::inconnue(), le_probleme2, Constituant::nb_constituants(), Navier_Stokes_std::operateur_divergence(), Navier_Stokes_std::operateur_gradient(), prov_face_, TRUSTVect< _TYPE_, _SIZE_ >::size(), Equation_base::solv_masse(), type_systeme_naire_, and Champ_Inc_base::valeurs().
div_kappa_grad()
DoubleTab & Source_Con_Phase_field::div_kappa_grad (const DoubleTab & F, const DoubleTab & kappa_var, DoubleTab & resu) const protected
References Solveur_Masse_base::appliquer(), Operateur_Div::calculer(), Operateur_Grad::calculer(), Convection_Diffusion_Concentration::constituant(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Domaine_VF::face_voisins(), Convection_Diffusion_Concentration::inconnue(), Navier_Stokes_std::inconnue(), le_dom_VDF, le_probleme2, TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Constituant::nb_constituants(), Domaine_VF::nb_faces(), Navier_Stokes_std::operateur_divergence(), Navier_Stokes_std::operateur_gradient(), Domaine_VF::premiere_face_int(), prov_face_, TRUSTVect< _TYPE_, _SIZE_ >::size(), Equation_base::solv_masse(), type_systeme_naire_, TRUST_Ref< _CLASSE_ >::valeur(), Champ_Inc_base::valeurs(), and Domaine_VF::volumes().
calculer_alpha_gradC_carre()
void Source_Con_Phase_field::calculer_alpha_gradC_carre (DoubleTab & alpha_gradC_carre) const protected
Calcul de alpha*(Grad(C))^2 au centre des elements.
Parameters
(DoubleTab& alpha_gradC_carre) alpha*(Grad(C))^2 au centre des elements
References alpha, Solveur_Masse_base::appliquer(), Operateur_Grad::calculer(), TRUSTVect< _TYPE_, _SIZE_ >::carre(), Domaine_32_64< _SIZE_ >::coord(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Domaine_dis_base::domaine(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_VF::elem_faces(), Domaine_VF::face_sommets(), Convection_Diffusion_Concentration::inconnue(), Navier_Stokes_std::inconnue(), le_dom_VDF, le_probleme2, TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Domaine_dis_base::nb_elem(), Navier_Stokes_std::operateur_gradient(), prov_face_, TRUSTVect< _TYPE_, _SIZE_ >::size(), Equation_base::solv_masse(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_Inc_base::valeurs(), and Domaine_VF::xp().
calculer_div_alpha_rho_gradC()
void Source_Con_Phase_field::calculer_div_alpha_rho_gradC (DoubleTab & div_alpha_rho_gradC) const protected
Calcul de Div(alpha*rho*Grad((C)) au centre des elements.
Parameters
(DoubleTab& div_alpha_rho_gradC) Div(alpha*rho*Grad((C)) au centre des elements
References alpha, Solveur_Masse_base::appliquer(), boussi_, Operateur_Div::calculer(), Operateur_Grad::calculer(), Domaine_VF::face_voisins(), Convection_Diffusion_Concentration::inconnue(), Navier_Stokes_std::inconnue(), le_dom_VDF, le_probleme2, Domaine_VF::nb_faces(), Navier_Stokes_std::operateur_divergence(), Navier_Stokes_std::operateur_gradient(), Domaine_VF::premiere_face_int(), prov_face_, Navier_Stokes_phase_field::rho(), rho0, TRUSTVect< _TYPE_, _SIZE_ >::size(), Equation_base::solv_masse(), type_systeme_naire_, TRUST_Ref< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), Champ_Inc_base::valeurs(), and Domaine_VF::volumes().
calculer_div_alpha_gradC()
void Source_Con_Phase_field::calculer_div_alpha_gradC (DoubleTab & div_alpha_gradC) const protected
Calcul de Div(alpha*rho*Grad((C)) au centre des elements.
Parameters
(DoubleTab& div_alpha_gradC) Div(alpha*Grad((C)) au centre des elements
References alpha, alphaMatrix, Solveur_Masse_base::appliquer(), Operateur_Div::calculer(), Operateur_Grad::calculer(), Convection_Diffusion_Concentration::constituant(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Convection_Diffusion_Concentration::inconnue(), Navier_Stokes_std::inconnue(), le_probleme2, Constituant::nb_constituants(), Navier_Stokes_std::operateur_divergence(), Navier_Stokes_std::operateur_gradient(), prov_face_, TRUSTVect< _TYPE_, _SIZE_ >::size(), Equation_base::solv_masse(), type_systeme_naire_, and Champ_Inc_base::valeurs().
Referenced by premier_demi_dt().
calculer_pression_thermo()
void Source_Con_Phase_field::calculer_pression_thermo (DoubleTab & pression_thermo) const protected
Calcul de la pression thermodynamique aux elements.
Parameters
(DoubleTab& pression_thermo) pression thermodynamique aux elements
References Convection_Diffusion_Phase_field::get_div_alpha_gradC(), Convection_Diffusion_Concentration::inconnue(), le_probleme2, Navier_Stokes_std::pression_pa(), TRUSTVect< _TYPE_, _SIZE_ >::size(), and Champ_Inc_base::valeurs().
calculer_mutilde_demi()
void Source_Con_Phase_field::calculer_mutilde_demi (DoubleTab & mutilde_demi, DoubleTab & c_demi) const protected
References a0Eq, a1Eq, a2Eq, alpha, alphaMatrix, angle_phi, angle_psi, Solveur_Masse_base::appliquer(), beta, betaMatrix, Operateur_Div::calculer(), Operateur_Grad::calculer(), Convection_Diffusion_Concentration::constituant(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), drhodc(), dWdc, dWdc_naire, dWdc_naire_analytique_quater, dWdc_naire_analytique_ter, eq1, eq2, Navier_Stokes_std::inconnue(), le_probleme2, TRUSTVect< _TYPE_, _SIZE_ >::line_size(), mutype_, Constituant::nb_constituants(), nb_equation_CH, Navier_Stokes_std::operateur_divergence(), Navier_Stokes_std::operateur_gradient(), prov_face_, TRUSTVect< _TYPE_, _SIZE_ >::size(), Equation_base::solv_masse(), type_potentiel_analytique_, type_systeme_naire_, u_carre_, Champ_Inc_base::valeurs(), x0Eq, x1Eq, and x2Eq.
assembler_matrice_point_fixe()
void Source_Con_Phase_field::assembler_matrice_point_fixe (Matrice_Morse & matrice_diffusion_CH) protected virtual
Assemble la matrice pour le calcul du point fixe.
References alpha, alphaMatrix, coeff_auto_diffusion, Objet_U::dimension, Matrice_Morse::dimensionner(), Domaine_VF::elem_faces(), Process::exit(), Domaine_VF::face_voisins(), Matrice_Morse::get_set_coeff(), Matrice_Morse::get_set_tab1(), Matrice_Morse::get_set_tab2(), Convection_Diffusion_Concentration::inconnue(), kappa, kappa_func_c, kappa_ind, kappa_moy_, kappaMatrix, kappaMatrix_func_c, le_dom_VDF, le_probleme2, molarVolume, Domaine_dis_base::nb_elem_tot(), nb_equation_CH, Domaine_VDF::orientation(), Schema_Temps_base::pas_de_temps(), prefactor, Equation_base::schema_temps(), temperature, type_systeme_naire_, TRUST_Ref< _CLASSE_ >::valeur(), Champ_Inc_base::valeurs(), and Domaine_VF::xp().
Referenced by premier_demi_dt().
calculer_point_fixe()
void Source_Con_Phase_field::calculer_point_fixe (const DoubleTab & c, const DoubleTab & mutilde, const Matrice_Morse & matrice_diffusion_CH, DoubleTab & c_demi, DoubleTab & mutilde_demi) protected virtual
Calcul du point fixe.
References le_dom_VDF, Domaine_dis_base::nb_elem_tot(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by premier_demi_dt().
calculer_u2_elem()
void Source_Con_Phase_field::calculer_u2_elem (DoubleVect & u_carre) protected virtual
References TRUSTVect< _TYPE_, _SIZE_ >::carre(), Domaine_32_64< _SIZE_ >::coord(), Objet_U::dimension, Domaine_dis_base::domaine(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_VF::elem_faces(), Domaine_VF::face_sommets(), Convection_Diffusion_Concentration::inconnue(), Navier_Stokes_std::inconnue(), le_dom_VDF, le_probleme2, TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Domaine_dis_base::nb_elem_tot(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_Inc_base::valeurs(), and Domaine_VF::xp().
Referenced by premier_demi_dt().
calculer_mutilde()
void Source_Con_Phase_field::calculer_mutilde (DoubleTab & mutilde) const protected virtual
Calcul de mutilde au centre des elements.
Parameters
(mutilde) mutilde au centre des elements
References a0Eq, a1Eq, a2Eq, angle_phi, angle_psi, beta, betaMatrix, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), drhodc(), dWdc, dWdc_naire, dWdc_naire_analytique_quater, dWdc_naire_analytique_ter, eq1, eq2, Convection_Diffusion_Phase_field::get_div_alpha_gradC(), Convection_Diffusion_Concentration::inconnue(), le_probleme2, TRUSTVect< _TYPE_, _SIZE_ >::line_size(), mutype_, nb_equation_CH, TRUSTVect< _TYPE_, _SIZE_ >::size(), type_potentiel_analytique_, type_systeme_naire_, u_carre_, Champ_Inc_base::valeurs(), x0Eq, x1Eq, and x2Eq.
dWdc_defaut()
double Source_Con_Phase_field::dWdc_defaut (const double c) const inline protected
Referenced by readOn().
kappa_func_c_defaut()
double Source_Con_Phase_field::kappa_func_c_defaut (const double c) const inline protected
References kappa, and mult_kappa.
Referenced by readOn().
dWdc_general()
double Source_Con_Phase_field::dWdc_general (const double c) const inline protected
References potentiel_chimique_expr_, and Table::val().
Referenced by readOn().
kappa_func_c_general()
double Source_Con_Phase_field::kappa_func_c_general (const double c) const inline protected
References kappa, kappa_forme_expr_, mult_kappa, and Table::val().
Referenced by readOn().
kappa_func_auto_diffusion()
DoubleTab Source_Con_Phase_field::kappa_func_auto_diffusion (const DoubleTab & c, const DoubleVect & coeff_auto_diff) const inline protected
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), and nb_equation_CH.
Referenced by readOn().
dWdc_naire_defaut()
DoubleTab Source_Con_Phase_field::dWdc_naire_defaut (const DoubleTab & c, const DoubleVect & a, const DoubleVect & b) const inline protected
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), and TRUSTVect< _TYPE_, _SIZE_ >::line_size().
Referenced by readOn().
dWdc_naire_analytique_ternaire()
DoubleTab Source_Con_Phase_field::dWdc_naire_analytique_ternaire (const DoubleTab & c, const DoubleVect & psi_, const DoubleVect & cUEq, const DoubleVect & cZrEq, const DoubleVect & aUEq, const DoubleVect & aZrEq) const inline protected
References TRUSTTab< _TYPE_, _SIZE_ >::dimension().
Referenced by readOn().
dWdc_naire_analytique_quaternaire()
DoubleTab Source_Con_Phase_field::dWdc_naire_analytique_quaternaire (const DoubleTab & c, const DoubleVect & psi_, const DoubleVect & phi_, const DoubleVect & cUEq, const DoubleVect & cZrEq, const DoubleVect & cFeEq, const DoubleVect & aUEq, const DoubleVect & aZrEq, const DoubleVect & aFeEq) const inline protected
References TRUSTTab< _TYPE_, _SIZE_ >::dimension().
Referenced by readOn().
construire_systeme()
void Source_Con_Phase_field::construire_systeme (const DoubleTab & c, const Matrice_Morse & matrice_diffusion_CH, DoubleTab & v0, const DoubleTab & x1) protected virtual
Construire le residu du GMRES NL.
References le_dom_VDF, Domaine_dis_base::nb_elem_tot(), TRUSTVect< _TYPE_, _SIZE_ >::size_totale(), type_systeme_naire_, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by matvect(), and non_lin_gmres().
matvect()
void Source_Con_Phase_field::matvect (const DoubleTab & c, const Matrice_Morse & matrice_diffusion_CH, const DoubleTab & v0, const DoubleTab & x1, DoubleTab & v1) protected virtual
Construire le residu du GMRES NL.
References construire_systeme().
Referenced by non_lin_gmres().
non_lin_gmres()
int Source_Con_Phase_field::non_lin_gmres (const DoubleTab & c, const DoubleTab & mutilde, const Matrice_Morse & matrice_diffusion_CH, DoubleTab & c_demi, DoubleTab & mutilde_demi) protected virtual
Algorithme GMRES Non Lineaire.
Parameters
(mutilde) inverse A x = b
Returns
(int)
References construire_systeme(), epsGMRES, le_dom_VDF, matvect(), Process::mp_sum(), Domaine_dis_base::nb_elem_tot(), nb_equation_CH, nit, nkr, rec_max, rec_min, TRUSTVect< _TYPE_, _SIZE_ >::size(), TRUSTVect< _TYPE_, _SIZE_ >::size_totale(), type_systeme_naire_, and TRUST_Ref< _CLASSE_ >::valeur().
Member Data Documentation
info_obj
const Type_info Source_Con_Phase_field::info_obj static
tpsaff
int Source_Con_Phase_field::tpsaff protected
Referenced by associer_pb(), and readOn().
rho0
double Source_Con_Phase_field::rho0 protected
Referenced by associer_pb(), and calculer_div_alpha_rho_gradC().
drhodc_
TRUST_Ref< Champ_Don_base *> Source_Con_Phase_field::drhodc_ protected
Referenced by associer_pb(), and drhodc().
accr
DoubleTab Source_Con_Phase_field::accr protected
Referenced by ajouter(), and premier_demi_dt().
u_carre_
DoubleVect Source_Con_Phase_field::u_carre_ protected
Referenced by calculer_mutilde(), calculer_mutilde_demi(), get_u_carre(), and premier_demi_dt().
prov_face_
DoubleTab Source_Con_Phase_field::prov_face_ protected
Referenced by calculer_alpha_gradC_carre(), calculer_div_alpha_gradC(), calculer_div_alpha_rho_gradC(), calculer_mutilde_demi(), div_kappa_grad(), and laplacien().
prov_elem_
DoubleTab Source_Con_Phase_field::prov_elem_ protected
alpha
double Source_Con_Phase_field::alpha protected
Referenced by assembler_matrice_point_fixe(), calculer_alpha_gradC_carre(), calculer_div_alpha_gradC(), calculer_div_alpha_rho_gradC(), calculer_mutilde_demi(), and readOn().
beta
double Source_Con_Phase_field::beta protected
Referenced by calculer_mutilde(), calculer_mutilde_demi(), and readOn().
alphaMatrix
DoubleVect Source_Con_Phase_field::alphaMatrix protected
Referenced by assembler_matrice_point_fixe(), calculer_div_alpha_gradC(), calculer_mutilde_demi(), and readOn().
betaMatrix
DoubleVect Source_Con_Phase_field::betaMatrix protected
Referenced by calculer_mutilde(), calculer_mutilde_demi(), and readOn().
minX
DoubleVect Source_Con_Phase_field::minX protected
Referenced by get_minX(), and readOn().
maxX
DoubleVect Source_Con_Phase_field::maxX protected
Referenced by get_maxX(), and readOn().
angle_psi
DoubleVect Source_Con_Phase_field::angle_psi protected
Referenced by calculer_mutilde(), calculer_mutilde_demi(), and readOn().
angle_phi
DoubleVect Source_Con_Phase_field::angle_phi protected
Referenced by calculer_mutilde(), calculer_mutilde_demi(), and readOn().
x0Eq
DoubleVect Source_Con_Phase_field::x0Eq protected
Referenced by calculer_mutilde(), calculer_mutilde_demi(), and readOn().
x1Eq
DoubleVect Source_Con_Phase_field::x1Eq protected
Referenced by calculer_mutilde(), calculer_mutilde_demi(), and readOn().
x2Eq
DoubleVect Source_Con_Phase_field::x2Eq protected
Referenced by calculer_mutilde(), calculer_mutilde_demi(), and readOn().
a0Eq
DoubleVect Source_Con_Phase_field::a0Eq protected
Referenced by calculer_mutilde(), calculer_mutilde_demi(), and readOn().
a1Eq
DoubleVect Source_Con_Phase_field::a1Eq protected
Referenced by calculer_mutilde(), calculer_mutilde_demi(), and readOn().
a2Eq
DoubleVect Source_Con_Phase_field::a2Eq protected
Referenced by calculer_mutilde(), calculer_mutilde_demi(), and readOn().
nb_equation_CH
int Source_Con_Phase_field::nb_equation_CH protected
Referenced by assembler_matrice_point_fixe(), calculer_mutilde(), calculer_mutilde_demi(), kappa_func_auto_diffusion(), non_lin_gmres(), and readOn().
potentiel_chimique_expr_
Table Source_Con_Phase_field::potentiel_chimique_expr_ protected
Referenced by dWdc_general(), and readOn().
dWdc
double(Source_Con_Phase_field::* Source_Con_Phase_field::dWdc) (const double) const protected
Referenced by calculer_mutilde(), calculer_mutilde_demi(), and readOn().
dWdc_naire
DoubleTab(Source_Con_Phase_field::* Source_Con_Phase_field::dWdc_naire) (const DoubleTab &, const DoubleVect &, const DoubleVect &) const protected
Referenced by calculer_mutilde(), calculer_mutilde_demi(), and readOn().
dWdc_naire_analytique_ter
DoubleTab(Source_Con_Phase_field::* Source_Con_Phase_field::dWdc_naire_analytique_ter) (const DoubleTab &, const DoubleVect &, const DoubleVect &, const DoubleVect &, const DoubleVect &, const DoubleVect &) const protected
Referenced by calculer_mutilde(), calculer_mutilde_demi(), and readOn().
dWdc_naire_analytique_quater
DoubleTab(Source_Con_Phase_field::* Source_Con_Phase_field::dWdc_naire_analytique_quater) (const DoubleTab &, const DoubleVect &, const DoubleVect &,const DoubleVect &, const DoubleVect &, const DoubleVect &, const DoubleVect &, const DoubleVect &, const DoubleVect &) const protected
Referenced by calculer_mutilde(), calculer_mutilde_demi(), and readOn().
eq1
DoubleVect Source_Con_Phase_field::eq1 protected
Referenced by calculer_mutilde(), calculer_mutilde_demi(), and readOn().
eq2
DoubleVect Source_Con_Phase_field::eq2 protected
Referenced by calculer_mutilde(), calculer_mutilde_demi(), and readOn().
kappa
double Source_Con_Phase_field::kappa protected
Referenced by assembler_matrice_point_fixe(), kappa_func_c_defaut(), kappa_func_c_general(), and readOn().
kappaMatrix
DoubleVect Source_Con_Phase_field::kappaMatrix protected
Referenced by assembler_matrice_point_fixe(), and readOn().
kappaMatrix_func_c
DoubleTab(Source_Con_Phase_field::* Source_Con_Phase_field::kappaMatrix_func_c) (const DoubleTab &, const DoubleVect &) const protected
Referenced by assembler_matrice_point_fixe(), and readOn().
coeff_auto_diffusion
DoubleVect Source_Con_Phase_field::coeff_auto_diffusion protected
Referenced by assembler_matrice_point_fixe(), and readOn().
temperature
double Source_Con_Phase_field::temperature protected
Referenced by assembler_matrice_point_fixe(), and readOn().
molarVolume
double Source_Con_Phase_field::molarVolume protected
Referenced by assembler_matrice_point_fixe(), and readOn().
prefactor
double Source_Con_Phase_field::prefactor protected
Referenced by assembler_matrice_point_fixe(), and readOn().
alpha_ref
double Source_Con_Phase_field::alpha_ref protected
Referenced by readOn().
angle_alphaMatrix
double Source_Con_Phase_field::angle_alphaMatrix protected
Referenced by readOn().
diagonal_coeff
double Source_Con_Phase_field::diagonal_coeff protected
Referenced by readOn().
kappa_ind
int Source_Con_Phase_field::kappa_ind protected
Referenced by assembler_matrice_point_fixe(), and associer_pb().
type_kappa_
int Source_Con_Phase_field::type_kappa_ = -1 protected
Referenced by associer_pb(), and readOn().
type_kappa_auto_diffusion_
int Source_Con_Phase_field::type_kappa_auto_diffusion_ = -1 protected
Referenced by associer_pb(), and readOn().
type_alpha_rotation_
int Source_Con_Phase_field::type_alpha_rotation_ protected
Referenced by readOn().
type_potentiel_analytique_
int Source_Con_Phase_field::type_potentiel_analytique_ protected
Referenced by calculer_mutilde(), calculer_mutilde_demi(), and readOn().
type_systeme_naire_
int Source_Con_Phase_field::type_systeme_naire_ protected
Referenced by assembler_matrice_point_fixe(), associer_pb(), calculer_div_alpha_gradC(), calculer_div_alpha_rho_gradC(), calculer_mutilde(), calculer_mutilde_demi(), construire_systeme(), div_kappa_grad(), get_type_systeme_naire(), laplacien(), non_lin_gmres(), and readOn().
kappa_moy_
int Source_Con_Phase_field::kappa_moy_ protected
Referenced by assembler_matrice_point_fixe(), associer_pb(), and readOn().
mult_kappa
double Source_Con_Phase_field::mult_kappa protected
Referenced by associer_pb(), kappa_func_c_defaut(), kappa_func_c_general(), and readOn().
kappa_forme_expr_
Table Source_Con_Phase_field::kappa_forme_expr_ protected
Referenced by kappa_func_c_general(), and readOn().
kappa_func_c
double(Source_Con_Phase_field::* Source_Con_Phase_field::kappa_func_c) (const double) const protected
Referenced by assembler_matrice_point_fixe(), and readOn().
mu1
double Source_Con_Phase_field::mu1 protected
mu2
double Source_Con_Phase_field::mu2 protected
implicitation_
int Source_Con_Phase_field::implicitation_ protected
Referenced by associer_pb(), premier_demi_dt(), and readOn().
gmres_
int Source_Con_Phase_field::gmres_ protected
Referenced by associer_pb(), premier_demi_dt(), and readOn().
epsilon_
double Source_Con_Phase_field::epsilon_ protected
Referenced by associer_pb(), and readOn().
eps_
double Source_Con_Phase_field::eps_ protected
Referenced by associer_pb(), and readOn().
boussi_
int Source_Con_Phase_field::boussi_ protected
Referenced by associer_pb(), and calculer_div_alpha_rho_gradC().
diff_boussi_
int Source_Con_Phase_field::diff_boussi_ protected
Referenced by associer_pb().
g_
DoubleTab Source_Con_Phase_field::g_ protected
Referenced by associer_pb().
mutype_
int Source_Con_Phase_field::mutype_ protected
Referenced by associer_pb(), calculer_mutilde(), and calculer_mutilde_demi().
couplage_
int Source_Con_Phase_field::couplage_ protected
Referenced by associer_pb(), and readOn().
nkr
int Source_Con_Phase_field::nkr protected
Referenced by associer_pb(), non_lin_gmres(), and readOn().
nit
int Source_Con_Phase_field::nit protected
Referenced by associer_pb(), non_lin_gmres(), and readOn().
rec_min
double Source_Con_Phase_field::rec_min protected
Referenced by associer_pb(), non_lin_gmres(), and readOn().
rec_max
double Source_Con_Phase_field::rec_max protected
Referenced by associer_pb(), non_lin_gmres(), and readOn().
epsGMRES
double Source_Con_Phase_field::epsGMRES protected
Referenced by associer_pb(), non_lin_gmres(), and readOn().
le_probleme2
TRUST_Ref< Probleme_base *> Source_Con_Phase_field::le_probleme2 protected
Referenced by assembler_matrice_point_fixe(), associer_pb(), calculer_alpha_gradC_carre(), calculer_div_alpha_gradC(), calculer_div_alpha_rho_gradC(), calculer_mutilde(), calculer_mutilde_demi(), calculer_pression_thermo(), calculer_u2_elem(), div_kappa_grad(), laplacien(), mettre_a_jour(), premier_demi_dt(), and readOn().
le_dom_VDF
TRUST_Ref< Domaine_VDF *> Source_Con_Phase_field::le_dom_VDF protected
Referenced by assembler_matrice_point_fixe(), associer_domaines(), calculer_alpha_gradC_carre(), calculer_champ_fonc_c(), calculer_div_alpha_rho_gradC(), calculer_point_fixe(), calculer_u2_elem(), construire_systeme(), div_kappa_grad(), non_lin_gmres(), and premier_demi_dt().
le_dom_Cl_VDF
TRUST_Ref< Domaine_Cl_VDF *> Source_Con_Phase_field::le_dom_Cl_VDF protected
Referenced by associer_domaines().