TrioCFD: RegroupeBord_32_64< _SIZE_ > Class Template Reference
RegroupeBord_32_64< _SIZE_ > Class Template Reference
#include <RegroupeBord.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Interprete_geometrique_base_32_64< _SIZE_ >
const Type_info * get_info () const override
void mettre_a_jour_sous_domaine (Domaine_t &domaine, int_t &elem, int_t num_premier_elem, int_t nb_elem) const
Public Member Functions inherited from Interprete
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Interprete
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Interprete
static Objet_U & objet (const Nom &)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
template<typename _SIZE_>
class RegroupeBord_32_64< _SIZE_ >
regroupe les frontieres bord1 et bord2 dans une frontiere de type bord1 et de nom titi
See also
Interprete
Member Typedef Documentation
int_t
template<typename _SIZE_ > using RegroupeBord_32_64< _SIZE_ >::int_t = _SIZE_
IntTab_t
template<typename _SIZE_ > using RegroupeBord_32_64< _SIZE_ >::IntTab_t = IntTab_T<_SIZE_>
Domaine_t
template<typename _SIZE_ > using RegroupeBord_32_64< _SIZE_ >::Domaine_t = Domaine_32_64<_SIZE_>
Frontiere_t
template<typename _SIZE_ > using RegroupeBord_32_64< _SIZE_ >::Frontiere_t = Frontiere_32_64<_SIZE_>
Faces_t
template<typename _SIZE_ > using RegroupeBord_32_64< _SIZE_ >::Faces_t = Faces_32_64<_SIZE_>
Bords_t
template<typename _SIZE_ > using RegroupeBord_32_64< _SIZE_ >::Bords_t = Bords_32_64<_SIZE_>
Raccords_t
template<typename _SIZE_ > using RegroupeBord_32_64< _SIZE_ >::Raccords_t = Raccords_32_64<_SIZE_>
Constructor & Destructor Documentation
RegroupeBord_32_64()
template<typename _T_ > RegroupeBord_32_64< _T_ >::RegroupeBord_32_64
~RegroupeBord_32_64()
template<typename _T_ > RegroupeBord_32_64< _T_ >::~RegroupeBord_32_64
Member Function Documentation
cree_instance()
template<typename _T_ > Objet_U * RegroupeBord_32_64< _T_ >::cree_instance static
taille_memoire()
template<typename _T_ > unsigned RegroupeBord_32_64< _T_ >::taille_memoire override virtual
Implements Objet_U.
duplique()
template<typename _T_ > int RegroupeBord_32_64< _T_ >::duplique override virtual
Implements Objet_U.
info()
template<typename _T_ > const Type_info * RegroupeBord_32_64< _T_ >::info static
get_info()
template<typename _T_ > const Type_info * RegroupeBord_32_64< _T_ >::get_info override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Interprete_geometrique_base_32_64< _SIZE_ >.
self_cast() [1/2]
template<typename _T_ > RegroupeBord_32_64< _T_ > & RegroupeBord_32_64< _T_ >::self_cast (Objet_U & r) static
self_cast() [2/2]
template<typename _T_ > const RegroupeBord_32_64< _T_ > & RegroupeBord_32_64< _T_ >::self_cast (const Objet_U & r) static
printOn()
template<typename _SIZE_ > Sortie & RegroupeBord_32_64< _SIZE_ >::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Interprete_geometrique_base_32_64< _SIZE_ >.
References Interprete::printOn().
readOn()
template<typename _SIZE_ > Entree & RegroupeBord_32_64< _SIZE_ >::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Interprete_geometrique_base_32_64< _SIZE_ >.
References Interprete::readOn().
interpreter_()
template<typename _SIZE_ > Entree & RegroupeBord_32_64< _SIZE_ >::interpreter_ (Entree & is) override virtual
Implements Interprete_geometrique_base_32_64< _SIZE_ >.
References Frontiere_32_64< _SIZE_ >::add(), Domaine_32_64< _SIZE_ >::frontiere(), Domaine_base::le_nom(), Frontiere_32_64< _SIZE_ >::le_nom(), and Domaine_32_64< _SIZE_ >::nb_front_Cl().
regroupe_bord()
template<typename _SIZE_ > void RegroupeBord_32_64< _SIZE_ >::regroupe_bord (Domaine_t & dom, Nom nom, const TRUST_List< Nom > & nlistbord)
References Domaine_32_64< _SIZE_ >::bord(), Nom::contient(), Faces_32_64< _SIZE_ >::dimensionner(), Frontiere_32_64< _SIZE_ >::faces(), Domaine_32_64< _SIZE_ >::faces_bord(), Domaine_32_64< _SIZE_ >::faces_raccord(), Domaine_32_64< _SIZE_ >::fixer_premieres_faces_frontiere(), Domaine_32_64< _SIZE_ >::frontiere(), Frontiere_32_64< _SIZE_ >::le_nom(), Faces_32_64< _SIZE_ >::les_sommets(), Faces_32_64< _SIZE_ >::nb_faces(), Frontiere_32_64< _SIZE_ >::nb_faces(), Domaine_32_64< _SIZE_ >::nb_front_Cl(), Faces_32_64< _SIZE_ >::nb_som_faces(), Frontiere_32_64< _SIZE_ >::nommer(), Domaine_32_64< _SIZE_ >::raccord(), Domaine_32_64< _SIZE_ >::rang_frontiere(), TRUST_List< _CLASSE_ >::size(), and TRUST_List< _CLASSE_ >::suppr().
rassemble_bords()
template<typename _SIZE_ > void RegroupeBord_32_64< _SIZE_ >::rassemble_bords (Domaine_t & dom)
References Domaine_32_64< _SIZE_ >::frontiere(), Frontiere_32_64< _SIZE_ >::le_nom(), and Domaine_32_64< _SIZE_ >::nb_front_Cl().
info_obj() [1/2]
const Type_info RegroupeBord_32_64< int >::info_obj ("RegroupeBord" , RegroupeBord_32_64< int >::cree_instance , 1 , RegroupeBord_32_64bases< int >)
info_obj() [2/2]
const Type_info RegroupeBord_32_64< trustIdType >::info_obj ("RegroupeBord" "_64" , RegroupeBord_32_64< trustIdType >::cree_instance , 1 , RegroupeBord_32_64bases< trustIdType >)
Member Data Documentation
info_obj
template<typename _SIZE_ > const Type_info RegroupeBord_32_64< _SIZE_ >::info_obj static