TrioCFD: Transport_K_ou_Eps Class Reference
Transport_K_ou_Eps Class Reference
#include <Transport_K_ou_Eps.h>
Public Member Functions
void associer_Champ_Inconnu (const Champ_Inc_base &)
void associer_modele_turbulence (const Modele_turbulence_hyd_2_eq_base &) override
const Motcle & domaine_application () const override
const Type_info * get_info () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
int nombre_d_operateurs () const override
const Operateur & operateur (int) const override
Operateur & operateur (int) override
Public Member Functions inherited from Transport_K_ou_Eps_base
virtual int controler_variable ()
void discretiser () override
const Type_info * get_info () const override
const Champ_Inc_base & inconnue () const override
Champ_Inc_base & inconnue () override
Public Member Functions inherited from Transport_2eq_base
void associer_milieu_base (const Milieu_base &) override
double calculer_pas_de_temps () const override
const Type_info * get_info () const override
const Milieu_base & milieu () const override
Milieu_base & milieu () override
Modele_turbulence_hyd_2_eq_base & modele_turbulence ()
const Modele_turbulence_hyd_2_eq_base & modele_turbulence () const
Public Member Functions inherited from Equation_base
virtual void abortTimeStep ()
virtual void associer_domaine_dis (const Domaine_dis_base &)
virtual void associer_pb_base (const Probleme_base &)
virtual void associer_sch_tps_base (const Schema_Temps_base &)
virtual double calculer_pas_de_temps () const
virtual void completer ()
virtual std::vector< YAML_data > data_a_sauvegarder () const
DoubleTab & derivee_en_temps_conv (DoubleTab &, const DoubleTab &)
virtual DoubleTab & derivee_en_temps_inco (DoubleTab &)
const Discretisation_base & discretisation () const
virtual void discretiser ()
virtual const Motcle & domaine_application () const
virtual Domaine_Cl_dis_base & domaine_Cl_dis ()
virtual const Domaine_Cl_dis_base & domaine_Cl_dis () const
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual void imprimer (Sortie &os) const
virtual bool initTimeStep (double dt)
const Nom & le_nom () const override
int limpr () const
virtual void mettre_a_jour (double temps)
virtual int preparer_calcul ()
Probleme_base & probleme ()
const Probleme_base & probleme () const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Schema_Temps_base & schema_temps ()
const Schema_Temps_base & schema_temps () const
Solveur_Masse_base & solv_masse ()
const Solveur_Masse_base & solv_masse () const
Sources & sources ()
const Sources & sources () const
virtual void valider_iteration ()
virtual void verifie_ch_init_nb_comp (const Champ_Inc_base &ch_ref, const int nb_comp) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Transport_K_ou_Eps_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Equation_base
virtual Entree & lire_cl (Entree &)
virtual Entree & lire_cond_init (Entree &)
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual Entree & lire_sources (Entree &)
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
virtual int verif_Cl () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
turbulente K et du taux de dissipation epsilon (eps) associee au modele de turbulence (k,eps). On traite en une seule equation le transport des deux grandeurs turbulentes. Il s'agit donc d'une equation vectorielle, dont le champ inconnue possede 2 composantes: K et epsilon. On instanciera un objet de cette classe uniquement si on utilise le modele (k,eps) pour traiter la turbulence en mode "bicephale"
See also
Equation_base
Constructor & Destructor Documentation
Transport_K_ou_Eps()
Transport_K_ou_Eps::Transport_K_ou_Eps ()
~Transport_K_ou_Eps()
Transport_K_ou_Eps::~Transport_K_ou_Eps ()
Member Function Documentation
cree_instance()
Objet_U * Transport_K_ou_Eps::cree_instance () static
taille_memoire()
unsigned Transport_K_ou_Eps::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Transport_K_ou_Eps::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Transport_K_ou_Eps::info () static
get_info()
const Type_info * Transport_K_ou_Eps::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Transport_2eq_base.
self_cast() [1/2]
Transport_K_ou_Eps & Transport_K_ou_Eps::self_cast (Objet_U & r) static
self_cast() [2/2]
const Transport_K_ou_Eps & Transport_K_ou_Eps::self_cast (const Objet_U & r) static
printOn()
Sortie & Transport_K_ou_Eps::printOn (Sortie & s) const override protected virtual
Imprime le type de l'equation sur un flot de sortie.
Parameters
(Sortie& s) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Transport_2eq_base.
References Objet_U::que_suis_je().
readOn()
Entree & Transport_K_ou_Eps::readOn (Entree & s) override protected virtual
Lit les specifications d'une equation de transport K-epsilon a partir d'un flot d'entree.
Controle dynamique du type du terme source.
Parameters
(Entree& s) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Transport_2eq_base.
References TRUST_List< _CLASSE_ >::add(), TRUST_List< _CLASSE_ >::est_vide(), Equation_base::les_sources, Transport_2eq_base::milieu(), Equation_base::probleme(), Objet_U::que_suis_je(), Transport_K_ou_Eps_base::readOn(), Transport_K_ou_Eps_base::transporte_K_, Source::typer(), and with_nu_.
set_param()
void Transport_K_ou_Eps::set_param (Param & param) override virtual
Reimplemented from Transport_2eq_base.
References Param::ajouter(), Param::dictionnaire(), Transport_2eq_base::set_param(), and with_nu_.
lire_motcle_non_standard()
int Transport_K_ou_Eps::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Equation_base.
References Operateur_Diff::associer_diffusivite(), Transport_2eq_base::associer_vitesse(), Operateur_Conv::associer_vitesse(), Champ_don_nul_, Probleme_base::equation(), Process::exit(), Equation_base::inconnue(), Transport_2eq_base::le_fluide, Equation_base::lire_motcle_non_standard(), Transport_2eq_base::lire_op_diff_turbulent(), Equation_base::probleme(), Objet_U::que_suis_je(), Transport_2eq_base::terme_convectif, Transport_2eq_base::terme_diffusif, TRUST_Ref< _CLASSE_ >::valeur(), Fluide_base::viscosite_cinematique(), Fluide_base::viscosite_dynamique(), and with_nu_.
associer_Champ_Inconnu()
void Transport_K_ou_Eps::associer_Champ_Inconnu (const Champ_Inc_base & vit) inline
Associe un champ de vitesse (transportante)a l'equation.
Parameters
(Champ_Inc_base& vit) le champ de vitesse a associer a l'equation
References inco_eqn_associee.
associer_modele_turbulence()
void Transport_K_ou_Eps::associer_modele_turbulence (const Modele_turbulence_hyd_2_eq_base & modele) override virtual
Associe un modele de turbulence K-epsilon a l'equation.
Parameters
(Modele_turbulence_hyd_K_Eps& modele) le modele de turbulence K-epsilon a asoocier a l'equation
Implements Transport_2eq_base.
References Transport_2eq_base::associer(), Transport_2eq_base::associer_milieu_base(), Transport_2eq_base::associer_vitesse(), Transport_K_ou_Eps_base::discretiser(), Modele_turbulence_hyd_base::equation(), Equation_base::inconnue(), Equation_base::liste_modeles_, Equation_base::milieu(), Transport_2eq_base::mon_modele, and TRUST_Ref< _CLASSE_ >::valeur().
nombre_d_operateurs()
int Transport_K_ou_Eps::nombre_d_operateurs () const override virtual
Renvoie le nombre d'operateurs de l'equation.
Ici 2.
Returns
(int) le nombre d'operateurs de l'equation
Implements Equation_base.
Referenced by operateur().
operateur() [1/2]
const Operateur & Transport_K_ou_Eps::operateur (int i) const override virtual
Renvoie l'operateur specifie par son index: renvoie terme_diffusif si i = 0.
renvoie terme_convectif si i = 1
exit si i>1
(version const)
Parameters
(int i) l'index de l'operateur a renvoyer
Returns
(Operateur&) l'operateur specifie
Exceptions
l'equation n'a pas plus de 2 operateurs
Implements Equation_base.
References Process::exit(), nombre_d_operateurs(), Transport_2eq_base::terme_convectif, and Transport_2eq_base::terme_diffusif.
operateur() [2/2]
Operateur & Transport_K_ou_Eps::operateur (int i) override virtual
Renvoie l'operateur specifie par son index: renvoie terme_diffusif si i = 0.
renvoie terme_convectif si i = 1
exit si i>1
Parameters
(int i) l'index de l'operateur a renvoyer
Returns
(Operateur&) l'operateur specifie
Exceptions
l'equation n'a pas plus de 2 operateurs
Implements Equation_base.
References Process::exit(), nombre_d_operateurs(), Transport_2eq_base::terme_convectif, and Transport_2eq_base::terme_diffusif.
domaine_application()
const Motcle & Transport_K_ou_Eps::domaine_application () const override virtual
Renvoie le nom du domaine d'application de l'equation.
Ici "Transport_Keps".
Returns
(Motcle&) le nom du domaine d'application de l'equation
Reimplemented from Equation_base.
corriger_derivee_impl()
DoubleTab & Transport_K_ou_Eps::corriger_derivee_impl (DoubleTab & d) override virtual
Reimplemented from Equation_base.
References Equation_base::corriger_derivee_impl(), Turbulence_paroi_base::corriger_derivee_impl(), Modele_turbulence_hyd_base::loi_paroi(), and Transport_2eq_base::modele_turbulence().
Member Data Documentation
info_obj
const Type_info Transport_K_ou_Eps::info_obj static
with_nu_
int Transport_K_ou_Eps::with_nu_ protected
Referenced by lire_motcle_non_standard(), readOn(), and set_param().
inco_eqn_associee
TRUST_Ref< Champ_Inc_base *> Transport_K_ou_Eps::inco_eqn_associee protected
Referenced by associer_Champ_Inconnu().
Champ_don_nul_
TRUST_Deriv< Champ_Don_base > Transport_K_ou_Eps::Champ_don_nul_ protected
Referenced by lire_motcle_non_standard().