TrioCFD: Convection_Diffusion_Temperature_IBM_Turbulent Class Reference
Convection_Diffusion_Temperature_IBM_Turbulent Class Reference
#include <Convection_Diffusion_Temperature_IBM_Turbulent.h>
Public Member Functions
void completer () override
const Type_info * get_info () const override
void imprimer (Sortie &os) const override
bool initTimeStep (double dt) override
int lire_motcle_non_standard (const Motcle &, Entree &) override
void mettre_a_jour (double) override
int preparer_calcul () override
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Public Member Functions inherited from Convection_Diffusion_Turbulent
virtual void mettre_a_jour (double)
int preparer_calcul ()
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
const Type_info * get_info () const override
bool initTimeStep (double dt) override
int preparer_calcul () override
Public Member Functions inherited from Convection_Diffusion_Temperature
void associer_milieu_base (const Milieu_base &) override
DoubleTab & derivee_en_temps_inco (DoubleTab &) override
void discretiser () override
const Motcle & domaine_application () const override
const Type_info * get_info () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
int preparer_calcul () override
Public Member Functions inherited from Convection_Diffusion_Temperature_base
void associer_milieu_base (const Milieu_base &) override
Fluide_base & fluide ()
const Type_info * get_info () const override
Public Member Functions inherited from Convection_Diffusion_std
void associer_vitesse (const Champ_base &)
const Type_info * get_info () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
int nombre_d_operateurs () const override
const Operateur & operateur (int) const override
Operateur & operateur (int) override
const Champ_Inc_base & vitesse_transportante () const
Public Member Functions inherited from Equation_base
virtual void abortTimeStep ()
virtual void associer_domaine_dis (const Domaine_dis_base &)
virtual void associer_pb_base (const Probleme_base &)
virtual void associer_sch_tps_base (const Schema_Temps_base &)
virtual double calculer_pas_de_temps () const
virtual void completer ()
virtual std::vector< YAML_data > data_a_sauvegarder () const
DoubleTab & derivee_en_temps_conv (DoubleTab &, const DoubleTab &)
virtual DoubleTab & derivee_en_temps_inco (DoubleTab &)
const Discretisation_base & discretisation () const
virtual void discretiser ()
virtual const Motcle & domaine_application () const
virtual Domaine_Cl_dis_base & domaine_Cl_dis ()
virtual const Domaine_Cl_dis_base & domaine_Cl_dis () const
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual void imprimer (Sortie &os) const
virtual bool initTimeStep (double dt)
const Nom & le_nom () const override
int limpr () const
virtual void mettre_a_jour (double temps)
virtual int preparer_calcul ()
Probleme_base & probleme ()
const Probleme_base & probleme () const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Schema_Temps_base & schema_temps ()
const Schema_Temps_base & schema_temps () const
Solveur_Masse_base & solv_masse ()
const Solveur_Masse_base & solv_masse () const
Sources & sources ()
const Sources & sources () const
virtual void valider_iteration ()
virtual void verifie_ch_init_nb_comp (const Champ_Inc_base &ch_ref, const int nb_comp) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Convection_Diffusion_Temperature
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Convection_Diffusion_Temperature_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Equation_base
virtual Entree & lire_cl (Entree &)
virtual Entree & lire_cond_init (Entree &)
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual Entree & lire_sources (Entree &)
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
virtual int verif_Cl () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
convection diffusion turbulente lorsque l'inconnue
est la temperature.
Cette herite de Convection_Diffusion_Turbulent qui contient
le modele de turbulence et de Convection_Diffusion_Temperature_IBM
qui modelise l'equation non turbulente.
See also
Convection_Diffusion_Turbulent Convection_Diffusion_Temperature_IBM
Constructor & Destructor Documentation
Convection_Diffusion_Temperature_IBM_Turbulent()
Convection_Diffusion_Temperature_IBM_Turbulent::Convection_Diffusion_Temperature_IBM_Turbulent ()
~Convection_Diffusion_Temperature_IBM_Turbulent()
Convection_Diffusion_Temperature_IBM_Turbulent::~Convection_Diffusion_Temperature_IBM_Turbulent ()
Member Function Documentation
cree_instance()
Objet_U * Convection_Diffusion_Temperature_IBM_Turbulent::cree_instance () static
taille_memoire()
unsigned Convection_Diffusion_Temperature_IBM_Turbulent::taille_memoire () const override virtual
Reimplemented from Convection_Diffusion_Temperature_IBM.
duplique()
int Convection_Diffusion_Temperature_IBM_Turbulent::duplique () const override virtual
Reimplemented from Convection_Diffusion_Temperature_IBM.
info()
const Type_info * Convection_Diffusion_Temperature_IBM_Turbulent::info () static
get_info()
const Type_info * Convection_Diffusion_Temperature_IBM_Turbulent::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Convection_Diffusion_Temperature_IBM.
self_cast() [1/2]
Convection_Diffusion_Temperature_IBM_Turbulent & Convection_Diffusion_Temperature_IBM_Turbulent::self_cast (Objet_U & r) static
self_cast() [2/2]
const Convection_Diffusion_Temperature_IBM_Turbulent & Convection_Diffusion_Temperature_IBM_Turbulent::self_cast (const Objet_U & r) static
printOn()
Sortie & Convection_Diffusion_Temperature_IBM_Turbulent::printOn (Sortie & os) const override protected virtual
Surcharge Objet_U::printOn Imprime l'equation et ses composants sur un flot de sortie.
Imprime le nom de l'equation, le solveur masse, les termes sources les conditions aux limites discretisees, les inconnues et les operateurs.
Parameters
(Sortie& os) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Convection_Diffusion_Temperature_IBM.
References Equation_base::printOn().
readOn()
Entree & Convection_Diffusion_Temperature_IBM_Turbulent::readOn (Entree & is) override protected virtual
Lecture d'une equation sur un flot d'entree.
Le format est le suivant: { [Source { [sou_1], [sour_2], ...} ] Conditions_limites { [cl_1] [cl_2] ... } Conditions_initiales { [cl_init] } }
Parameters
(Entree& is) un flot d'entree pour lire l'equation
Returns
(Entree&) le flot d'entree modifie
Exceptions
mauvais format de lecture, accolade ouvrante attendue
pas de conditions initiales, il faut initialiser l'inconnue
pas de conditions aux limites, il faut donner des conditions aux limites
Reimplemented from Convection_Diffusion_Temperature_IBM.
References Convection_Diffusion_Temperature_IBM::readOn().
set_param()
void Convection_Diffusion_Temperature_IBM_Turbulent::set_param (Param & titi) override virtual
Reimplemented from Convection_Diffusion_Temperature_IBM.
References Param::ajouter_non_std(), Param::REQUIRED, and Convection_Diffusion_Temperature_IBM::set_param().
lire_motcle_non_standard()
int Convection_Diffusion_Temperature_IBM_Turbulent::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Equation_base.
References Operateur_Diff::associer_diffusivite(), Operateur_Diff::associer_diffusivite_pour_pas_de_temps(), Convection_Diffusion_Temperature_base::diffusivite_pour_pas_de_temps(), Convection_Diffusion_Temperature_base::diffusivite_pour_transport(), Convection_Diffusion_Turbulent::le_modele_turbulence, Convection_Diffusion_Turbulent::lire_modele(), Convection_Diffusion_Temperature::lire_motcle_non_standard(), Convection_Diffusion_Turbulent::lire_op_diff_turbulent(), Equation_base::liste_modeles_, Convection_Diffusion_std::terme_diffusif, and TRUST_Deriv< _CLASSE_ >::valeur().
completer()
void Convection_Diffusion_Temperature_IBM_Turbulent::completer () override virtual
Double appel a: Convection_Diffusion_Turbulent::completer()
Convection_Diffusion_Temperature_IBM::completer()
Reimplemented from Equation_base.
References Equation_base::completer(), and Convection_Diffusion_Turbulent::completer().
data_a_sauvegarder()
std::vector< YAML_data > Convection_Diffusion_Temperature_IBM_Turbulent::data_a_sauvegarder () const override virtual
for PDI IO: retrieve name, type and dimensions of the fields to save/restore
Reimplemented from Convection_Diffusion_Turbulent.
References Equation_base::data_a_sauvegarder(), and Convection_Diffusion_Turbulent::data_a_sauvegarder().
sauvegarder()
int Convection_Diffusion_Temperature_IBM_Turbulent::sauvegarder (Sortie & os) const override virtual
Sauvegarde sur un flot de sortie, double appel a: Convection_Diffusion_Temperature_IBM::sauvegarder(Sortie&);.
 Convection_Diffusion_Turbulent::sauvegarder(Sortie& );
Parameters
(Sortie& os) un flot de sortie
Returns
(int) renvoie toujours 1
Reimplemented from Convection_Diffusion_Turbulent.
References Convection_Diffusion_Turbulent::sauvegarder(), and Equation_base::sauvegarder().
reprendre()
int Convection_Diffusion_Temperature_IBM_Turbulent::reprendre (Entree & is) override virtual
Reprise a partir d'un flot d'entree, double appel a: Convection_Diffusion_Temperature_IBM::reprendre(Entree&);.
 Convection_Diffusion_Turbulent::reprendre(Entree&);
Parameters
(Entree& is) un flot d'entree
Returns
(int) renvoie toujours 1
Reimplemented from Convection_Diffusion_Turbulent.
References Convection_Diffusion_Turbulent::reprendre(), and Equation_base::reprendre().
mettre_a_jour()
void Convection_Diffusion_Temperature_IBM_Turbulent::mettre_a_jour (double temps) override virtual
Mise a jour en temps de l'equation, double appel a: Convection_Diffusion_Temperature_IBM::mettre_a_jour(double);.
 Convection_Diffusion_Turbulent::mettre_a_jour(double );
Parameters
(double temps) le temps de mise a jour
Reimplemented from Convection_Diffusion_Turbulent.
References Equation_base::mettre_a_jour(), and Convection_Diffusion_Turbulent::mettre_a_jour().
preparer_calcul()
int Convection_Diffusion_Temperature_IBM_Turbulent::preparer_calcul () override virtual
Double appel a: Convection_Diffusion_Turbulent::preparer_calcul()
 Convection_Diffusion_Temperature_IBM::preparer_calcul()
Returns
(int) renvoie toujours 1
Reimplemented from Convection_Diffusion_Temperature_IBM.
References Convection_Diffusion_Turbulent::preparer_calcul(), and Convection_Diffusion_Temperature_IBM::preparer_calcul().
initTimeStep()
bool Convection_Diffusion_Temperature_IBM_Turbulent::initTimeStep (double dt) override virtual
Allocation et initialisation de l'inconnue et des CLs jusqu'a present+dt.
autres initialisations pour les calculs sur le prochain pas de temps : operateurs, solveur_masse->
Returns
(0 en cas d'erreur, 1 sinon)
Reimplemented from Convection_Diffusion_Temperature_IBM.
References Convection_Diffusion_Turbulent::initTimeStep(), and Convection_Diffusion_Temperature_IBM::initTimeStep().
creer_champ()
void Convection_Diffusion_Temperature_IBM_Turbulent::creer_champ (const Motcle & motlu) override virtual
Reimplemented from Equation_base.
References Convection_Diffusion_Temperature::creer_champ(), Modele_turbulence_scal_base::creer_champ(), Convection_Diffusion_Turbulent::le_modele_turbulence, and Objet_U_ptr::non_nul().
get_champ()
const Champ_base & Convection_Diffusion_Temperature_IBM_Turbulent::get_champ (const Motcle & nom) const override virtual
Reimplemented from Equation_base.
References Nom::getString(), Convection_Diffusion_Temperature::has_champ(), Modele_turbulence_scal_base::has_champ(), Convection_Diffusion_Turbulent::le_modele_turbulence, and Objet_U_ptr::non_nul().
has_champ() [1/2]
bool Convection_Diffusion_Temperature_IBM_Turbulent::has_champ (const Motcle & nom, TRUST_Ref< Champ_base * > & ref_champ) const override virtual
Reimplemented from Equation_base.
References Convection_Diffusion_Temperature::has_champ(), Modele_turbulence_scal_base::has_champ(), Convection_Diffusion_Turbulent::le_modele_turbulence, and Objet_U_ptr::non_nul().
has_champ() [2/2]
bool Convection_Diffusion_Temperature_IBM_Turbulent::has_champ (const Motcle & nom) const override virtual
Reimplemented from Equation_base.
References Convection_Diffusion_Temperature::has_champ(), Modele_turbulence_scal_base::has_champ(), Convection_Diffusion_Turbulent::le_modele_turbulence, and Objet_U_ptr::non_nul().
get_noms_champs_postraitables()
void Convection_Diffusion_Temperature_IBM_Turbulent::get_noms_champs_postraitables (Noms & nom, Option opt = NONE) const override virtual
Reimplemented from Equation_base.
References Convection_Diffusion_Temperature::get_noms_champs_postraitables(), Modele_turbulence_scal_base::get_noms_champs_postraitables(), Convection_Diffusion_Turbulent::le_modele_turbulence, and Objet_U_ptr::non_nul().
imprimer()
void Convection_Diffusion_Temperature_IBM_Turbulent::imprimer (Sortie & os) const override virtual
Imprime les operateurs de l'equation si le schema en temps indique que c'est necessaire.
[SI limpr() ALORS impr(os)]
Parameters
(Sortie& os) le flot de sortie
Reimplemented from Equation_base.
References Modele_turbulence_scal_base::imprimer(), Equation_base::imprimer(), and Convection_Diffusion_Turbulent::le_modele_turbulence.
get_modele()
const RefObjU & Convection_Diffusion_Temperature_IBM_Turbulent::get_modele (Type_modele type) const override virtual
Reimplemented from Equation_base.
References Equation_base::get_modele(), Equation_base::liste_modeles_, TRUST_Ref_Objet_U::non_nul(), and TRUST_Ref_Objet_U::valeur().
Member Data Documentation
info_obj
const Type_info Convection_Diffusion_Temperature_IBM_Turbulent::info_obj static