TrioCFD: Terme_Puissance_Thermique_Echange_Impose_VEF_Face Class Reference
Terme_Puissance_Thermique_Echange_Impose_VEF_Face Class Reference
#include <Terme_Puissance_Thermique_Echange_Impose_VEF_Face.h>
Public Member Functions
const Type_info * get_info () const override
void mettre_a_jour (double) override
Public Member Functions inherited from Source_base
virtual int a_pour_Champ_Fonc (const Motcle &mot, TRUST_Ref< Champ_base * > &ch_ref) const
virtual void associer_champ_rho (const Champ_base &champ_rho)
virtual void completer ()
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
virtual void resetTime (double t)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
int initialiser (double temps) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
See also
Source_base
Constructor & Destructor Documentation
~Terme_Puissance_Thermique_Echange_Impose_VEF_Face()
Terme_Puissance_Thermique_Echange_Impose_VEF_Face::~Terme_Puissance_Thermique_Echange_Impose_VEF_Face ()
Member Function Documentation
cree_instance()
Objet_U * Terme_Puissance_Thermique_Echange_Impose_VEF_Face::cree_instance () static
taille_memoire()
unsigned Terme_Puissance_Thermique_Echange_Impose_VEF_Face::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Terme_Puissance_Thermique_Echange_Impose_VEF_Face::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Terme_Puissance_Thermique_Echange_Impose_VEF_Face::info () static
get_info()
const Type_info * Terme_Puissance_Thermique_Echange_Impose_VEF_Face::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Source_base.
self_cast() [1/2]
Terme_Puissance_Thermique_Echange_Impose_VEF_Face & Terme_Puissance_Thermique_Echange_Impose_VEF_Face::self_cast (Objet_U & r) static
self_cast() [2/2]
const Terme_Puissance_Thermique_Echange_Impose_VEF_Face & Terme_Puissance_Thermique_Echange_Impose_VEF_Face::self_cast (const Objet_U & r) static
printOn()
Sortie & Terme_Puissance_Thermique_Echange_Impose_VEF_Face::printOn (Sortie & os) const override protected virtual
DOES NOTHING - to override in derived classes.
Imprime la source sur un flot de sortie.
Parameters
(Sortie& os) le flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Source_base.
References Objet_U::que_suis_je().
readOn()
Entree & Terme_Puissance_Thermique_Echange_Impose_VEF_Face::readOn (Entree & is) override protected virtual
DOES NOTHING - to override in derived classes.
Lecture d'un terme source sur un flot d'entree.
Parameters
(Entree& is) le flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Source_base.
References Param::ajouter(), himp_, Param::lire_avec_accolades_depuis(), Objet_U::que_suis_je(), Param::REQUIRED, Source_base::set_description(), Source_base::set_fichier(), and Text_.
ajouter()
DoubleTab & Terme_Puissance_Thermique_Echange_Impose_VEF_Face::ajouter (DoubleTab & resu) const override virtual
Reimplemented from Source_base.
References himp_, le_dom_VEF, Text_, TRUST_Ref< _CLASSE_ >::valeur(), and Champ_Don_base::valeurs().
Referenced by calculer().
calculer()
DoubleTab & Terme_Puissance_Thermique_Echange_Impose_VEF_Face::calculer (DoubleTab & resu) const override virtual
Reimplemented from Source_base.
References ajouter().
mettre_a_jour()
void Terme_Puissance_Thermique_Echange_Impose_VEF_Face::mettre_a_jour (double temps) override virtual
DOES NOTHING - to override in derived classes.
Mise a jour en temps du terme source.
Parameters
(double) le pas de temps de mise a jour
Reimplemented from Source_base.
References himp_, le_dom_VEF, Text_, TRUST_Ref< _CLASSE_ >::valeur(), and Champ_Don_base::valeurs().
associer_pb()
void Terme_Puissance_Thermique_Echange_Impose_VEF_Face::associer_pb (const Probleme_base &) inline override virtual
Implements Source_base.
contribuer_a_avec()
void Terme_Puissance_Thermique_Echange_Impose_VEF_Face::contribuer_a_avec (const DoubleTab & , Matrice_Morse & mat) const override virtual
contribution a la matrice implicite des termes sources par defaut pas de contribution
Reimplemented from Source_base.
References TRUSTArray< _TYPE_, _SIZE_ >::addr(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), himp_, le_dom_VEF, TRUST_Ref< _CLASSE_ >::valeur(), and Champ_Don_base::valeurs().
associer_domaines()
void Terme_Puissance_Thermique_Echange_Impose_VEF_Face::associer_domaines (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis) override protected virtual
Implements Source_base.
References le_dom_Cl_VEF, and le_dom_VEF.
initialiser()
int Terme_Puissance_Thermique_Echange_Impose_VEF_Face::initialiser (double temps) override protected virtual
Contrairement aux methodes mettre_a_jour, les methodes initialiser des sources ne peuvent pas dependre de l'exterieur.
(lui-meme peut ne pas etre initialise) Par defaut, mettre_a_jour
Reimplemented from Source_base.
References Equation_base::discretisation(), MorEqn::equation(), himp_, Champ_Don_base::initialiser(), Source_base::initialiser(), Field_base::le_nom(), Discretisation_base::nommer_completer_champ_physique(), Text_, and TRUST_Deriv< _CLASSE_ >::valeur().
Member Data Documentation
info_obj
const Type_info Terme_Puissance_Thermique_Echange_Impose_VEF_Face::info_obj static
le_dom_VEF
TRUST_Ref< Domaine_VEF *> Terme_Puissance_Thermique_Echange_Impose_VEF_Face::le_dom_VEF protected
Referenced by ajouter(), associer_domaines(), contribuer_a_avec(), and mettre_a_jour().
le_dom_Cl_VEF
TRUST_Ref< Domaine_Cl_VEF *> Terme_Puissance_Thermique_Echange_Impose_VEF_Face::le_dom_Cl_VEF protected
Referenced by associer_domaines().
himp_
TRUST_Deriv< Champ_Don_base > Terme_Puissance_Thermique_Echange_Impose_VEF_Face::himp_ protected
Referenced by ajouter(), contribuer_a_avec(), initialiser(), mettre_a_jour(), and readOn().
Text_
TRUST_Deriv< Champ_Don_base > Terme_Puissance_Thermique_Echange_Impose_VEF_Face::Text_ protected
Referenced by ajouter(), initialiser(), mettre_a_jour(), and readOn().