TrioCFD: Prepro_IBM_base Class Reference
Prepro_IBM_base Class Reference
#include <Prepro_IBM_base.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
int lire_motcle_non_standard (const Motcle &, Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Prepro_IBM_base()
Prepro_IBM_base::Prepro_IBM_base ()
~Prepro_IBM_base()
Prepro_IBM_base::~Prepro_IBM_base () override
Member Function Documentation
info()
const Type_info * Prepro_IBM_base::info () static
get_info()
const Type_info * Prepro_IBM_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
Reimplemented in Prepro_IBM_Ponderation, and Prepro_IBM_Uzawa.
self_cast() [1/2]
Prepro_IBM_base & Prepro_IBM_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Prepro_IBM_base & Prepro_IBM_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Prepro_IBM_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
Reimplemented in Prepro_IBM_Ponderation, and Prepro_IBM_Uzawa.
References Objet_U::que_suis_je().
Referenced by Prepro_IBM_Ponderation::printOn(), and Prepro_IBM_Uzawa::printOn().
readOn()
Entree & Prepro_IBM_base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
Reimplemented in Prepro_IBM_Ponderation, and Prepro_IBM_Uzawa.
References Objet_U::que_suis_je(), and set_param().
Referenced by Prepro_IBM_Ponderation::readOn(), and Prepro_IBM_Uzawa::readOn().
set_param()
void Prepro_IBM_base::set_param (Param & param)
References aDomUMesh_, Param::ajouter(), Param::ajouter_flag(), Param::ajouter_non_std(), aSkinUMesh_, c_prepro_, eps_, Param::OPTIONAL, and save_prepro_.
Referenced by readOn().
lire_motcle_non_standard()
int Prepro_IBM_base::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override protected virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Objet_U.
References Process::abort(), c_prepro_, Objet_U::dimension, dimTab_, eps_, and TRUSTTab< _TYPE_, _SIZE_ >::resize().
Friends And Related Function Documentation
Source_PDF_base
friend class Source_PDF_base friend
Interpolation_IBM_base
friend class Interpolation_IBM_base friend
Member Data Documentation
info_obj
const Type_info Prepro_IBM_base::info_obj static
aDomUMesh_
TRUST_Deriv< Champ_Don_base > Prepro_IBM_base::aDomUMesh_ protected
Referenced by set_param().
aSkinUMesh_
TRUST_Deriv< Champ_Don_base > Prepro_IBM_base::aSkinUMesh_ protected
Referenced by set_param().
eps_
double Prepro_IBM_base::eps_ = 1.0e-12 protected
Referenced by lire_motcle_non_standard(), and set_param().
c_prepro_
double Prepro_IBM_base::c_prepro_ = 0. protected
Referenced by lire_motcle_non_standard(), and set_param().
dimTab_
IntTab Prepro_IBM_base::dimTab_ protected
Referenced by lire_motcle_non_standard().
save_prepro_
bool Prepro_IBM_base::save_prepro_ = false protected
Referenced by set_param().
fluid_points_
TRUST_Deriv< Champ_Don_base > Prepro_IBM_base::fluid_points_ protected
fluid_elems_
TRUST_Deriv< Champ_Don_base > Prepro_IBM_base::fluid_elems_ protected
solid_points_
TRUST_Deriv< Champ_Don_base > Prepro_IBM_base::solid_points_ protected
solid_elems_
TRUST_Deriv< Champ_Don_base > Prepro_IBM_base::solid_elems_ protected
corresp_elems_
TRUST_Deriv< Champ_Don_base > Prepro_IBM_base::corresp_elems_ protected
champ_rotation_
TRUST_Deriv< Champ_Don_base > Prepro_IBM_base::champ_rotation_ protected
champ_aire_
TRUST_Deriv< Champ_Don_base > Prepro_IBM_base::champ_aire_ protected