TrioCFD: cible_donnee Class Reference
cible_donnee Class Reference
#include <corrections_qdm.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
< S'OCCUPE DE CALCULER v_cible_ et qdm_cible_ UNIQUEMENT qdm_cible = alpha_l rho_l v_cible_ v_cible_ : constante utilisateur ou .sauv
‍
Constructor & Destructor Documentation
~cible_donnee()
cible_donnee::~cible_donnee ()
cible_donnee()
cible_donnee::cible_donnee ()
Member Function Documentation
cree_instance()
Objet_U * cible_donnee::cree_instance () static
taille_memoire()
unsigned cible_donnee::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int cible_donnee::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * cible_donnee::info () static
get_info()
const Type_info * cible_donnee::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
cible_donnee & cible_donnee::self_cast (Objet_U & r) static
self_cast() [2/2]
const cible_donnee & cible_donnee::self_cast (const Objet_U & r) static
printOn()
Sortie & cible_donnee::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
References Objet_U::printOn(), and v_cible_.
readOn()
Entree & cible_donnee::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
References Param::ajouter(), Param::lire_avec_accolades(), Objet_U::que_suis_je(), Objet_U::readOn(), and v_cible_.
set_time()
void cible_donnee::set_time () inline
Referenced by correction_one_direction::set_time_for_correction().
set_rho_l()
void cible_donnee::set_rho_l (double rho_liq) inline
References rho_liq_.
Referenced by correction_one_direction::set_rho_liq().
get_v_cible()
double cible_donnee::get_v_cible () inline
References v_cible_.
get_qdm_cible()
double cible_donnee::get_qdm_cible () inline
References qdm_cible_.
Referenced by correction_one_direction::compute_correction_value().
compute_qdm_cible()
void cible_donnee::compute_qdm_cible (double alpha_l)
References qdm_cible_, rho_liq_, and v_cible_.
Referenced by correction_one_direction::compute_correction_value().
get_need_for_vl_vv()
int cible_donnee::get_need_for_vl_vv () inline
Referenced by correction_one_direction::get_need_for_vit_rel().
get_need_for_rho_l()
int cible_donnee::get_need_for_rho_l () inline
Referenced by correction_one_direction::get_need_for_rho_liq().
Member Data Documentation
info_obj
const Type_info cible_donnee::info_obj static
rho_liq_
double cible_donnee::rho_liq_ protected
Referenced by compute_qdm_cible(), and set_rho_l().
v_cible_
double cible_donnee::v_cible_ protected
Referenced by compute_qdm_cible(), get_v_cible(), printOn(), and readOn().
qdm_cible_
double cible_donnee::qdm_cible_ protected
Referenced by compute_qdm_cible(), and get_qdm_cible().