TrioCFD: Champ_Inc_P0_base Class Reference
Champ_Inc_P0_base Class Reference
#include <Champ_Inc_P0_base.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Champ_Inc_base
Champ_base & affecter_ (const Champ_base &) override
Champ_base & affecter_compo (const Champ_base &, int compo) override
virtual void associer_eqn (const Equation_base &)
Champ_Inc_base & avancer (int i=1)
double changer_temps (const double temps) override
double changer_temps_futur (double, int i=1)
double changer_temps_passe (double, int i=1)
virtual int fixer_nb_valeurs_temporelles (int)
DoubleTab & futur (int i=1) override
const Type_info * get_info () const override
int lire_donnees (Entree &)
void mettre_a_jour (double temps) override
virtual int nb_valeurs_temporelles () const
DoubleTab & passe (int i=1) override
Champ_Inc_base & reculer (int i=1)
double recuperer_temps_futur (int i=1) const
double recuperer_temps_passe (int i=1) const
virtual DoubleTab & remplir_coord_noeuds_compo (DoubleTab &, int) const
virtual int remplir_coord_noeuds_et_polys (DoubleTab &, IntVect &) const
virtual int remplir_coord_noeuds_et_polys_compo (DoubleTab &, IntVect &, int) const
int reprendre (Entree &) override
void resetTime (double time) override
int sauvegarder (Sortie &) const override
DoubleTab & trace (const Frontiere_dis_base &, DoubleTab &, double, int distant) const override
DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const override
DoubleTab & valeur_aux (const DoubleTab &positions, DoubleTab &valeurs) const override
DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const override
DoubleTab & valeurs () override
const DoubleTab & valeurs (double temps) const override
DoubleTab & valeurs (double temps) override
Public Member Functions inherited from Champ_base
Champ_base & affecter (const Champ_base &)
Champ_base ()
virtual double changer_temps (const double t)
const Type_info * get_info () const override
double temps () const
virtual DoubleTab & trace (const Frontiere_dis_base &, DoubleTab &, double, int distant) const
virtual DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const
virtual double valeur_a_compo (const DoubleVect &position, int ncomp) const
virtual DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &valeurs, int le_poly) const
virtual double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const
virtual DoubleVect & valeur_a_sommet (int, const Domaine &, DoubleVect &) const
virtual DoubleTab & valeur_aux (const DoubleTab &positions, DoubleTab &valeurs) const
virtual DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const
virtual DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const
virtual DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp) const
Public Member Functions inherited from Field_base
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
virtual void fixer_nb_comp (int i)
virtual const Nom & fixer_nom_compo (const Nom &)
virtual const Nom & fixer_nom_compo (int, const Nom &)
virtual const Noms & fixer_noms_compo (const Noms &)
virtual const Nom & fixer_unite (const Nom &)
virtual const Nom & fixer_unite (int i, const Nom &)
virtual const Noms & fixer_unites (const Noms &)
const Type_info * get_info () const override
const Nom & nom_compo (int) const
void nommer (const Nom &) override
const Nom & unite () const
const Nom & unite (int) const
const Noms & unites () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Champ_Proto
int lire_dimension (Entree &, const Nom &)
int lire_dimension (int dim, const Nom &le_nom_)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Champ_implementation_P0
DoubleTab & valeur_aux_centres_de_gravite (const Domaine &, DoubleTab &valeurs) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Champ_Inc_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Field_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
Decrire ici la classe Champ_Inc_P0_base
Constructor & Destructor Documentation
Champ_Inc_P0_base()
Champ_Inc_P0_base::Champ_Inc_P0_base ()
~Champ_Inc_P0_base()
Champ_Inc_P0_base::~Champ_Inc_P0_base () override
Member Function Documentation
info()
const Type_info * Champ_Inc_P0_base::info () static
get_info()
const Type_info * Champ_Inc_P0_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
Reimplemented in Champ_Elem_PolyMAC, Champ_Elem_PolyMAC_P0, Champ_Elem_PolyMAC_P0P1NC, Champ_P0_VDF, and Champ_P0_VEF.
self_cast() [1/2]
Champ_Inc_P0_base & Champ_Inc_P0_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Champ_Inc_P0_base & Champ_Inc_P0_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Champ_Inc_P0_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
Reimplemented in Champ_Elem_PolyMAC, Champ_Elem_PolyMAC_P0, Champ_Elem_PolyMAC_P0P1NC, Champ_P0_VDF, and Champ_P0_VEF.
References Field_base::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Champ_Inc_P0_base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
Reimplemented in Champ_Elem_PolyMAC, Champ_Elem_PolyMAC_P0, Champ_Elem_PolyMAC_P0P1NC, Champ_P0_VDF, and Champ_P0_VEF.
References Champ_Inc_base::lire_donnees().
valeur_au_bord()
double Champ_Inc_P0_base::valeur_au_bord (int face) const
References Champ_Inc_base::le_dom_VF, TRUST_Ref< _CLASSE_ >::non_nul(), and Champ_Inc_base::valeurs().
trace()
DoubleTab & Champ_Inc_P0_base::trace (const Frontiere_dis_base & fr, DoubleTab & x, double tps, int distant) const override virtual
Trace du champ P0 sur la frontiere.
Reimplemented from Champ_base.
Reimplemented in Champ_Elem_PolyMAC.
References Champ_implementation_P0::trace(), and Champ_Inc_base::valeurs().
affecter_()
Champ_base & Champ_Inc_P0_base::affecter_ (const Champ_base & ch) override virtual
Implements Champ_base.
Reimplemented in Champ_Elem_PolyMAC, Champ_Elem_PolyMAC_P0, and Champ_Elem_PolyMAC_P0P1NC.
References Champ_implementation_P0::affecter_(), and Champ_Inc_base::affecter_().
Referenced by Champ_Elem_PolyMAC_P0::affecter_().
fixer_nb_valeurs_nodales()
int Champ_Inc_P0_base::fixer_nb_valeurs_nodales (int n) override virtual
Reimplemented from Champ_base.
Reimplemented in Champ_Elem_PolyMAC, and Champ_Elem_PolyMAC_P0P1NC.
References Champ_Inc_base::creer_tableau_distribue(), Domaine_dis_base::domaine(), Domaine_32_64< _SIZE_ >::md_vector_elements(), and Domaine_32_64< _SIZE_ >::nb_elem().
Referenced by Traitement_particulier_NS_Pression_VDF::lire().
fcl()
const IntTab & Champ_Inc_P0_base::fcl () const inline
References fcl_, fcl_init_, and init_fcl().
Referenced by Op_Diff_PolyMAC_Elem::ajouter(), Couplage_Parietal_PolyMAC_helper::ajouter_blocs(), Flux_2groupes_PolyMAC_P0::ajouter_blocs(), Injection_QDM_nulle_PolyMAC_P0::ajouter_blocs(), Injection_QDM_nulle_VDF::ajouter_blocs(), Diffusion_croisee_echelle_temp_taux_diss_turb_PolyMAC_P0::ajouter_blocs(), Diffusion_supplementaire_echelle_temp_turb_PolyMAC_P0::ajouter_blocs(), Source_BIF_PolyMAC_P0::ajouter_blocs(), Op_Diff_DG_Elem::ajouter_blocs(), Dispersion_bulles_PolyMAC_P0::ajouter_blocs(), Op_Diff_PolyMAC_P0_Elem::ajouter_blocs(), Correction_Lubchenko_PolyMAC_P0::ajouter_blocs_BIF(), Op_Diff_PolyMAC_P0P1NC_Elem::ajouter_blocs_ext(), Masse_PolyMAC_Elem::ajouter_masse(), Champ_Elem_PolyMAC_P0::calc_grad(), Op_Evanescence_Homogene_PolyMAC_P0_Face::calc_grad_alpha_elem(), Op_Evanescence_Homogene_PolyMAC_P0_Face::calc_grad_alpha_faces(), Op_Diff_PolyMAC_P0_Elem::calculer_dt_stab(), Op_Diff_DG_Elem::completer(), Op_Diff_PolyMAC_Elem::completer(), Op_Diff_PolyMAC_Elem::contribuer_a_avec(), Masse_PolyMAC_Elem::dimensionner(), Op_Diff_PolyMAC_P0P1NC_Elem::dimensionner_blocs_ext(), Champ_Elem_PolyMAC_P0::init_grad(), and Op_Diff_PolyMAC_Elem::update_delta().
valeur_a_elem()
DoubleVect & Champ_Inc_P0_base::valeur_a_elem (const DoubleVect & position, DoubleVect & result, int poly) const inline override virtual
Reimplemented from Champ_implementation_P0.
References Champ_implementation_P0::valeur_a_elem().
valeur_a_elem_compo()
double Champ_Inc_P0_base::valeur_a_elem_compo (const DoubleVect & position, int poly, int ncomp) const inline override virtual
Reimplemented from Champ_implementation_P0.
References Champ_implementation_P0::valeur_a_elem_compo().
valeur_aux_elems()
DoubleTab & Champ_Inc_P0_base::valeur_aux_elems (const DoubleTab & positions, const IntVect & polys, DoubleTab & result) const inline override virtual
Reimplemented from Champ_implementation_P0.
References Champ_implementation_P0::valeur_aux_elems().
valeur_aux_elems_compo()
DoubleVect & Champ_Inc_P0_base::valeur_aux_elems_compo (const DoubleTab & positions, const IntVect & polys, DoubleVect & result, int ncomp) const inline override virtual
Reimplemented from Champ_implementation_P0.
References Champ_implementation_P0::valeur_aux_elems_compo().
remplir_coord_noeuds()
DoubleTab & Champ_Inc_P0_base::remplir_coord_noeuds (DoubleTab & positions) const inline override virtual
Reimplemented from Champ_implementation_P0.
Reimplemented in Champ_P0_VDF.
References Champ_implementation_P0::remplir_coord_noeuds().
remplir_coord_noeuds_et_polys()
int Champ_Inc_P0_base::remplir_coord_noeuds_et_polys (DoubleTab & positions, IntVect & polys) const inline override virtual
Reimplemented from Champ_implementation_P0.
References Champ_implementation_P0::remplir_coord_noeuds_et_polys().
valeur_aux_sommets()
DoubleTab & Champ_Inc_P0_base::valeur_aux_sommets (const Domaine & domain, DoubleTab & result) const inline override virtual
Reimplemented from Champ_implementation.
References Champ_implementation::valeur_aux_sommets().
Referenced by Champ_P1iP1B_implementation::valeur_aux_sommets().
valeur_aux_sommets_compo()
DoubleVect & Champ_Inc_P0_base::valeur_aux_sommets_compo (const Domaine & domain, DoubleVect & result, int ncomp) const inline override virtual
Reimplemented from Champ_implementation.
References Champ_implementation::valeur_aux_sommets_compo().
le_champ() [1/2]
Champ_base & Champ_Inc_P0_base::le_champ () inline override protected virtual
Implements Champ_implementation.
Referenced by Champ_Elem_DG::eval_elem(), and Champ_Elem_DG::valeur_aux_elems().
le_champ() [2/2]
const Champ_base & Champ_Inc_P0_base::le_champ () const inline override protected virtual
Implements Champ_implementation.
init_fcl()
void Champ_Inc_P0_base::init_fcl () const protected virtual
References Nom::debute_par(), Champ_Inc_base::domaine(), Process::exit(), fcl_, fcl_init_, Champ_Inc_base::mon_dom_cl_dis, MorEqn::mon_equation, Front_VF::nb_faces_tot(), Front_VF::num_face(), Objet_U::que_suis_je(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), and TRUST_Vector< _CLASSE_ >::size().
Referenced by fcl().
Member Data Documentation
info_obj
const Type_info Champ_Inc_P0_base::info_obj static
fcl_
IntTab Champ_Inc_P0_base::fcl_ mutable protected
Referenced by fcl(), and init_fcl().
fcl_init_
int Champ_Inc_P0_base::fcl_init_ = 0 mutable protected
Referenced by fcl(), and init_fcl().