TrioCFD: Modele_Fonc_Bas_Reynolds_Base Class Reference
Modele_Fonc_Bas_Reynolds_Base Class Reference abstract
#include <Modele_Fonc_Bas_Reynolds_Base.h>
Public Member Functions
const Type_info * get_info () const override
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Modele_Fonc_Bas_Reynolds_Base()
Modele_Fonc_Bas_Reynolds_Base::Modele_Fonc_Bas_Reynolds_Base ()
~Modele_Fonc_Bas_Reynolds_Base()
Modele_Fonc_Bas_Reynolds_Base::~Modele_Fonc_Bas_Reynolds_Base () override
Member Function Documentation
info()
const Type_info * Modele_Fonc_Bas_Reynolds_Base::info () static
get_info()
const Type_info * Modele_Fonc_Bas_Reynolds_Base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
Modele_Fonc_Bas_Reynolds_Base & Modele_Fonc_Bas_Reynolds_Base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Modele_Fonc_Bas_Reynolds_Base & Modele_Fonc_Bas_Reynolds_Base::self_cast (const Objet_U & r) static
printOn()
Sortie & Modele_Fonc_Bas_Reynolds_Base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
References Objet_U::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Modele_Fonc_Bas_Reynolds_Base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
typer_lire_Modele_Fonc_Bas_Reynolds()
void Modele_Fonc_Bas_Reynolds_Base::typer_lire_Modele_Fonc_Bas_Reynolds (TRUST_Deriv< Modele_Fonc_Bas_Reynolds_Base > & mod, const Equation_base & eqn, Entree & is) static
References associer(), associer_eqn(), associer_eqn_2(), associer_pb(), Equation_base::discretisation(), Equation_base::domaine_Cl_dis(), Equation_base::domaine_dis(), has_seconde_equation(), Equation_base::probleme(), Objet_U::que_suis_je(), and seconde_equation().
Referenced by Modele_turbulence_hyd_K_Eps::lire_motcle_non_standard(), Modele_turbulence_hyd_K_Eps_Bas_Reynolds::lire_motcle_non_standard(), and Modele_turbulence_hyd_K_Eps_Bicephale::lire_motcle_non_standard().
equation() [1/2]
const Equation_base & Modele_Fonc_Bas_Reynolds_Base::equation () const inline
References Process::exit(), mon_equation, TRUST_Ref< _CLASSE_ >::non_nul(), and TRUST_Ref< _CLASSE_ >::valeur().
equation() [2/2]
Equation_base & Modele_Fonc_Bas_Reynolds_Base::equation () inline
References Process::exit(), mon_equation, TRUST_Ref< _CLASSE_ >::non_nul(), and TRUST_Ref< _CLASSE_ >::valeur().
seconde_equation() [1/2]
const Equation_base & Modele_Fonc_Bas_Reynolds_Base::seconde_equation () const inline
References Process::exit(), ma_seconde_equation, TRUST_Ref< _CLASSE_ >::non_nul(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by typer_lire_Modele_Fonc_Bas_Reynolds().
seconde_equation() [2/2]
Equation_base & Modele_Fonc_Bas_Reynolds_Base::seconde_equation () inline
References Process::exit(), ma_seconde_equation, TRUST_Ref< _CLASSE_ >::non_nul(), and TRUST_Ref< _CLASSE_ >::valeur().
preparer_calcul()
int Modele_Fonc_Bas_Reynolds_Base::preparer_calcul () virtual
mettre_a_jour()
virtual void Modele_Fonc_Bas_Reynolds_Base::mettre_a_jour (double) pure virtual
Implemented in Modele_Jones_Launder_VDF, Modele_Jones_Launder_VEF, and Modele_Lam_Bremhorst_VEF.
discretiser()
void Modele_Fonc_Bas_Reynolds_Base::discretiser () virtual
References Champs_compris_T< FIELD_TYPE >::ajoute_champ(), BR_wall_length_, D_, Discretisation_base::discretiser_champ(), E_, F1_, F2_, and mon_equation.
Referenced by Modele_turbulence_hyd_K_Eps::lire_motcle_non_standard(), Modele_turbulence_hyd_K_Eps_Bas_Reynolds::lire_motcle_non_standard(), and Modele_turbulence_hyd_K_Eps_Bicephale::lire_motcle_non_standard().
completer()
void Modele_Fonc_Bas_Reynolds_Base::completer () virtual
associer_pb()
void Modele_Fonc_Bas_Reynolds_Base::associer_pb (const Probleme_base & pb) virtual
References eq_hydraulique, and Probleme_base::equation().
Referenced by typer_lire_Modele_Fonc_Bas_Reynolds().
associer_eqn()
void Modele_Fonc_Bas_Reynolds_Base::associer_eqn (const Equation_base & eqn) virtual
References mon_equation.
Referenced by typer_lire_Modele_Fonc_Bas_Reynolds().
associer_eqn_2()
void Modele_Fonc_Bas_Reynolds_Base::associer_eqn_2 (const Equation_base & eqn) virtual
References ma_seconde_equation.
Referenced by Modele_turbulence_hyd_K_Eps_Bicephale::lire_motcle_non_standard(), and typer_lire_Modele_Fonc_Bas_Reynolds().
associer()
virtual void Modele_Fonc_Bas_Reynolds_Base::associer (const Domaine_dis_base & , const Domaine_Cl_dis_base &) pure virtual
Implemented in Modele_F1F2FMU_unitaire_VDF, Modele_Jones_Launder_VDF, Modele_Launder_Sharma_VDF, Modele_Jones_Launder_VEF, and Modele_Lam_Bremhorst_VEF.
Referenced by typer_lire_Modele_Fonc_Bas_Reynolds().
sauvegarder()
int Modele_Fonc_Bas_Reynolds_Base::sauvegarder (Sortie &) const override virtual
Sauvegarde d'un Objet_U sur un flot de sortie Methode a surcharger.
Parameters
(Sortie&) flot de sortie a utiliser pour la sauvegarde
Returns
(int) code de retour
Reimplemented from Objet_U.
reprendre()
int Modele_Fonc_Bas_Reynolds_Base::reprendre (Entree &) override virtual
Reprise d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree&) flot d'entree a utiliser pour la reprise
Returns
(int) code de retour
Reimplemented from Objet_U.
Calcul_D()
virtual DoubleTab & Modele_Fonc_Bas_Reynolds_Base::Calcul_D (DoubleTab & , const Domaine_dis_base & , const Domaine_Cl_dis_base & , const DoubleTab & , const DoubleTab & , const Champ_Don_base &) const pure virtual
Implemented in Modele_Jones_Launder_VDF, Modele_EASM_Baglietto_VEF, Modele_Jones_Launder_VEF, Modele_Lam_Bremhorst_VEF, Modele_Launder_Sharma_VEF, and Modele_standard_KEps_VEF.
Referenced by Source_Transport_K_Eps_Bas_Reynolds_anisotherme_VEF_Face::ajouter(), Source_Transport_K_Eps_Bas_Reynolds_VEF_Face::ajouter(), Source_Transport_Bas_Reynolds_VDF_Elem_base::ajouter_blocs(), Source_Transport_K_Eps_Bas_Reynolds_aniso_therm_concen_VDF_Elem::ajouter_blocs(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_VDF_Elem::ajouter_blocs(), and Source_Transport_K_Eps_Bas_Reynolds_anisotherme_W_VDF_Elem::ajouter_blocs().
Calcul_is_Reynolds_stress_isotrope()
int Modele_Fonc_Bas_Reynolds_Base::Calcul_is_Reynolds_stress_isotrope () const virtual
Reimplemented in Modele_Lam_Bremhorst_VEF.
Calcul_is_Cmu_constant()
int Modele_Fonc_Bas_Reynolds_Base::Calcul_is_Cmu_constant () const virtual
Reimplemented in Modele_Lam_Bremhorst_VEF.
Referenced by Modele_turbulence_hyd_K_Eps::calculer_viscosite_turbulente(), Modele_turbulence_hyd_K_Eps_Bicephale::calculer_viscosite_turbulente(), Modele_turbulence_hyd_K_Eps_Bicephale::fill_turbulent_viscosity_tab(), and Modele_turbulence_hyd_K_Eps::fill_turbulent_viscosity_tab().
Calcul_E()
virtual DoubleTab & Modele_Fonc_Bas_Reynolds_Base::Calcul_E (DoubleTab & , const Domaine_dis_base & , const Domaine_Cl_dis_base & , const DoubleTab & , const DoubleTab & , const Champ_Don_base & , const DoubleTab &) const pure virtual
Implemented in Modele_Jones_Launder_VDF, Modele_EASM_Baglietto_VEF, Modele_Jones_Launder_VEF, Modele_Lam_Bremhorst_VEF, Modele_Launder_Sharma_VEF, and Modele_standard_KEps_VEF.
Referenced by Source_Transport_K_Eps_Bas_Reynolds_anisotherme_VEF_Face::ajouter(), Source_Transport_K_Eps_Bas_Reynolds_VEF_Face::ajouter(), Source_Transport_Bas_Reynolds_VDF_Elem_base::ajouter_blocs(), Source_Transport_K_Eps_Bas_Reynolds_aniso_therm_concen_VDF_Elem::ajouter_blocs(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_VDF_Elem::ajouter_blocs(), and Source_Transport_K_Eps_Bas_Reynolds_anisotherme_W_VDF_Elem::ajouter_blocs().
Calcul_F1()
virtual DoubleTab & Modele_Fonc_Bas_Reynolds_Base::Calcul_F1 (DoubleTab & , const Domaine_dis_base & , const Domaine_Cl_dis_base & , const DoubleTab & , const DoubleTab & , const Champ_base &) const pure virtual
Implemented in Modele_F1F2FMU_unitaire_VDF, Modele_Jones_Launder_VDF, Modele_EASM_Baglietto_VEF, Modele_Jones_Launder_VEF, Modele_Lam_Bremhorst_VEF, Modele_Launder_Sharma_VEF, and Modele_standard_KEps_VEF.
Calcul_F2()
virtual DoubleTab & Modele_Fonc_Bas_Reynolds_Base::Calcul_F2 (DoubleTab & , DoubleTab & , const Domaine_dis_base & , const DoubleTab & , const Champ_base &) const pure virtual
Implemented in Modele_F1F2FMU_unitaire_VDF, Modele_Jones_Launder_VDF, Modele_EASM_Baglietto_VEF, Modele_Jones_Launder_VEF, Modele_Lam_Bremhorst_VEF, Modele_Launder_Sharma_VEF, and Modele_standard_KEps_VEF.
Referenced by Source_Transport_K_Eps_Bas_Reynolds_anisotherme_VEF_Face::ajouter(), Source_Transport_K_Eps_Bas_Reynolds_VEF_Face::ajouter(), Source_Transport_Bas_Reynolds_VDF_Elem_base::ajouter_blocs(), Source_Transport_K_Eps_Bas_Reynolds_aniso_therm_concen_VDF_Elem::ajouter_blocs(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_VDF_Elem::ajouter_blocs(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_QC_VDF_Elem::ajouter_blocs(), and Source_Transport_K_Eps_Bas_Reynolds_anisotherme_W_VDF_Elem::ajouter_blocs().
Calcul_Fmu()
virtual DoubleTab & Modele_Fonc_Bas_Reynolds_Base::Calcul_Fmu (DoubleTab & , const Domaine_dis_base & , const Domaine_Cl_dis_base & , const DoubleTab & , const Champ_Don_base &) const pure virtual
Implemented in Modele_F1F2FMU_unitaire_VDF, Modele_Jones_Launder_VDF, Modele_Launder_Sharma_VDF, Modele_Jones_Launder_VEF, Modele_Lam_Bremhorst_VEF, Modele_Launder_Sharma_VEF, Modele_standard_KEps_VEF, and Modele_EASM_Baglietto_VEF.
Referenced by Modele_turbulence_hyd_K_Eps::calculer_viscosite_turbulente(), and Modele_turbulence_hyd_K_Eps_Bas_Reynolds::calculer_viscosite_turbulente().
Calcul_Cmu()
DoubleTab & Modele_Fonc_Bas_Reynolds_Base::Calcul_Cmu (DoubleTab & Cmu, const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const DoubleTab & vitesse, const DoubleTab & K_Eps, const double EPS_MIN) const virtual
Reimplemented in Modele_Lam_Bremhorst_VEF.
Referenced by Modele_turbulence_hyd_K_Eps::calculer_viscosite_turbulente().
Calcul_Cmu_Paroi()
DoubleTab & Modele_Fonc_Bas_Reynolds_Base::Calcul_Cmu_Paroi (DoubleTab & Cmu, const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const DoubleTab & visco, const DoubleTab & visco_turb, const DoubleTab & loi_paroi, const int idt, const DoubleTab & vitesse, const DoubleTab & K_Eps, const double EPS_MIN) const virtual
Reimplemented in Modele_Lam_Bremhorst_VEF.
Referenced by Modele_turbulence_hyd_K_Eps::calculer_viscosite_turbulente().
calcul_tenseur_Re()
bool Modele_Fonc_Bas_Reynolds_Base::calcul_tenseur_Re (const DoubleTab & , const DoubleTab & , DoubleTab &) const virtual
Reimplemented in Modele_Lam_Bremhorst_VEF.
References Process::exit().
Referenced by Modele_turbulence_hyd_RANS_K_Eps_base::calcul_tenseur_Re().
Calcul_D_BiK()
virtual DoubleTab & Modele_Fonc_Bas_Reynolds_Base::Calcul_D_BiK (DoubleTab & , const Domaine_dis_base & , const Domaine_Cl_dis_base & , const DoubleTab & , const DoubleTab & , const DoubleTab & , const Champ_Don_base &) const pure virtual
Implemented in Modele_Jones_Launder_VDF, Modele_EASM_Baglietto_VEF, Modele_Jones_Launder_VEF, Modele_Lam_Bremhorst_VEF, Modele_Launder_Sharma_VEF, and Modele_standard_KEps_VEF.
Calcul_E_BiK()
virtual DoubleTab & Modele_Fonc_Bas_Reynolds_Base::Calcul_E_BiK (DoubleTab & , const Domaine_dis_base & , const Domaine_Cl_dis_base & , const DoubleTab & , const DoubleTab & , const DoubleTab & , const Champ_Don_base & , const DoubleTab &) const pure virtual
Implemented in Modele_Jones_Launder_VDF, Modele_EASM_Baglietto_VEF, Modele_Jones_Launder_VEF, Modele_Lam_Bremhorst_VEF, Modele_Launder_Sharma_VEF, and Modele_standard_KEps_VEF.
Calcul_F1_BiK()
virtual DoubleTab & Modele_Fonc_Bas_Reynolds_Base::Calcul_F1_BiK (DoubleTab & , const Domaine_dis_base & , const Domaine_Cl_dis_base & , const DoubleTab & , const DoubleTab & , const DoubleTab & , const Champ_base &) const pure virtual
Implemented in Modele_F1F2FMU_unitaire_VDF, Modele_Jones_Launder_VDF, Modele_EASM_Baglietto_VEF, Modele_Jones_Launder_VEF, Modele_Lam_Bremhorst_VEF, Modele_Launder_Sharma_VEF, and Modele_standard_KEps_VEF.
Calcul_F2_BiK()
virtual DoubleTab & Modele_Fonc_Bas_Reynolds_Base::Calcul_F2_BiK (DoubleTab & , DoubleTab & , const Domaine_dis_base & , const DoubleTab & , const DoubleTab & , const Champ_base &) const pure virtual
Implemented in Modele_F1F2FMU_unitaire_VDF, Modele_Jones_Launder_VDF, Modele_EASM_Baglietto_VEF, Modele_Jones_Launder_VEF, Modele_Lam_Bremhorst_VEF, Modele_Launder_Sharma_VEF, and Modele_standard_KEps_VEF.
Calcul_Fmu_BiK()
virtual DoubleTab & Modele_Fonc_Bas_Reynolds_Base::Calcul_Fmu_BiK (DoubleTab & , const Domaine_dis_base & , const Domaine_Cl_dis_base & , const DoubleTab & , const DoubleTab & , const Champ_Don_base &) const pure virtual
Implemented in Modele_F1F2FMU_unitaire_VDF, Modele_Jones_Launder_VDF, Modele_Launder_Sharma_VDF, Modele_EASM_Baglietto_VEF, Modele_Jones_Launder_VEF, Modele_Lam_Bremhorst_VEF, Modele_Launder_Sharma_VEF, and Modele_standard_KEps_VEF.
Referenced by Modele_turbulence_hyd_K_Eps_Bicephale::calculer_viscosite_turbulente().
Calcul_Cmu_BiK()
DoubleTab & Modele_Fonc_Bas_Reynolds_Base::Calcul_Cmu_BiK (DoubleTab & Cmu, const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const DoubleTab & vitesse, const DoubleTab & K, const DoubleTab & Eps, const double EPS_MIN) const virtual
Reimplemented in Modele_Lam_Bremhorst_VEF.
Referenced by Modele_turbulence_hyd_K_Eps_Bicephale::calculer_viscosite_turbulente().
Calcul_Cmu_Paroi_BiK()
DoubleTab & Modele_Fonc_Bas_Reynolds_Base::Calcul_Cmu_Paroi_BiK (DoubleTab & Cmu, const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const DoubleTab & visco, const DoubleTab & visco_turb, const DoubleTab & loi_paroi, const int idt, const DoubleTab & vitesse, const DoubleTab & K, const DoubleTab & Eps, const double EPS_MIN) const virtual
Reimplemented in Modele_Lam_Bremhorst_VEF.
Referenced by Modele_turbulence_hyd_K_Eps_Bicephale::calculer_viscosite_turbulente().
calcul_tenseur_Re_BiK()
bool Modele_Fonc_Bas_Reynolds_Base::calcul_tenseur_Re_BiK (const DoubleTab & , const DoubleTab & , DoubleTab &) const virtual
Reimplemented in Modele_Lam_Bremhorst_VEF.
References Process::exit().
creer_champ()
void Modele_Fonc_Bas_Reynolds_Base::creer_champ (const Motcle & motlu) override virtual
Implements Champs_compris_interface.
get_champ()
const Champ_base & Modele_Fonc_Bas_Reynolds_Base::get_champ (const Motcle & nom) const override virtual
Implements Champs_compris_interface.
References Champs_compris_T< FIELD_TYPE >::get_champ().
has_champ() [1/2]
bool Modele_Fonc_Bas_Reynolds_Base::has_champ (const Motcle & nom, TRUST_Ref< Champ_base * > & ref_champ) const override virtual
Implements Champs_compris_interface.
References Champs_compris_T< FIELD_TYPE >::has_champ().
Referenced by Modele_turbulence_hyd_K_Eps::get_champ(), Modele_turbulence_hyd_K_Eps_Bas_Reynolds::get_champ(), Modele_turbulence_hyd_K_Eps_Bicephale::get_champ(), Modele_turbulence_hyd_K_Eps::has_champ(), Modele_turbulence_hyd_K_Eps_Bas_Reynolds::has_champ(), and Modele_turbulence_hyd_K_Eps_Bicephale::has_champ().
has_champ() [2/2]
bool Modele_Fonc_Bas_Reynolds_Base::has_champ (const Motcle & nom) const override virtual
Implements Champs_compris_interface.
References Champs_compris_T< FIELD_TYPE >::has_champ().
get_noms_champs_postraitables()
void Modele_Fonc_Bas_Reynolds_Base::get_noms_champs_postraitables (Noms & nom, Option opt = NONE) const override virtual
Implements Champs_compris_interface.
References TRUST_Vector< _CLASSE_ >::add(), and Champs_compris_T< FIELD_TYPE >::liste_noms_compris().
Referenced by Modele_turbulence_hyd_K_Eps::get_noms_champs_postraitables(), Modele_turbulence_hyd_K_Eps_Bas_Reynolds::get_noms_champs_postraitables(), and Modele_turbulence_hyd_K_Eps_Bicephale::get_noms_champs_postraitables().
lire_distance_paroi()
void Modele_Fonc_Bas_Reynolds_Base::lire_distance_paroi () virtual
Reimplemented in Modele_Lam_Bremhorst_VEF, Modele_Launder_Sharma_VEF, and Modele_standard_KEps_VEF.
Referenced by Modele_turbulence_hyd_K_Eps::lire_motcle_non_standard(), and Modele_turbulence_hyd_K_Eps_Bicephale::lire_motcle_non_standard().
has_seconde_equation()
bool Modele_Fonc_Bas_Reynolds_Base::has_seconde_equation () const inline
References ma_seconde_equation, and TRUST_Ref< _CLASSE_ >::non_nul().
Referenced by typer_lire_Modele_Fonc_Bas_Reynolds().
Member Data Documentation
info_obj
const Type_info Modele_Fonc_Bas_Reynolds_Base::info_obj static
ma_seconde_equation
TRUST_Ref< Equation_base *> Modele_Fonc_Bas_Reynolds_Base::ma_seconde_equation
Referenced by associer_eqn_2(), Modele_Lam_Bremhorst_VEF::calcul_tenseur_Re_BiK(), has_seconde_equation(), and seconde_equation().
mon_equation
TRUST_Ref< Equation_base *> Modele_Fonc_Bas_Reynolds_Base::mon_equation protected
Referenced by associer_eqn(), Modele_Lam_Bremhorst_VEF::calcul_tenseur_Re(), Modele_Lam_Bremhorst_VEF::calcul_tenseur_Re_BiK(), discretiser(), and equation().
le_fluide
TRUST_Ref< Fluide_base *> Modele_Fonc_Bas_Reynolds_Base::le_fluide protected
la_vitesse_transportante
TRUST_Ref< Champ_Inc_base *> Modele_Fonc_Bas_Reynolds_Base::la_vitesse_transportante protected
eq_hydraulique
TRUST_Ref< Equation_base *> Modele_Fonc_Bas_Reynolds_Base::eq_hydraulique protected
Referenced by associer_pb(), Modele_Jones_Launder_VDF::calcul_derivees_premieres_croisees(), Modele_Jones_Launder_VDF::Calcul_E(), Modele_Jones_Launder_VEF::Calcul_E(), and Modele_Launder_Sharma_VEF::Calcul_E().
visco_
TRUST_Ref< Champ_Don_base *> Modele_Fonc_Bas_Reynolds_Base::visco_ protected
nom_fic
Nom Modele_Fonc_Bas_Reynolds_Base::nom_fic protected
Referenced by Modele_Lam_Bremhorst_VEF::lire_distance_paroi(), and Modele_Lam_Bremhorst_VEF::set_param().
BR_wall_length_
TRUST_Deriv< Champ_Fonc_base > Modele_Fonc_Bas_Reynolds_Base::BR_wall_length_ protected
Referenced by Modele_EASM_Baglietto_VEF::Calcul_F1(), Modele_Lam_Bremhorst_VEF::Calcul_F1(), Modele_EASM_Baglietto_VEF::Calcul_F1_BiK(), Modele_Lam_Bremhorst_VEF::Calcul_F1_BiK(), Modele_Lam_Bremhorst_VEF::Calcul_Fmu(), Modele_EASM_Baglietto_VEF::Calcul_Fmu(), Modele_EASM_Baglietto_VEF::Calcul_Fmu_BiK(), Modele_Lam_Bremhorst_VEF::Calcul_Fmu_BiK(), discretiser(), and Modele_Lam_Bremhorst_VEF::lire_distance_paroi().
is_Cmu_constant_
int Modele_Fonc_Bas_Reynolds_Base::is_Cmu_constant_ protected
Referenced by Modele_Lam_Bremhorst_VEF::Calcul_is_Cmu_constant(), Modele_EASM_Baglietto_VEF::readOn(), Modele_Lam_Bremhorst_VEF::readOn(), Modele_Launder_Sharma_VEF::readOn(), Modele_standard_KEps_VEF::readOn(), and Modele_Lam_Bremhorst_VEF::set_param().
is_Reynolds_stress_isotrope_
int Modele_Fonc_Bas_Reynolds_Base::is_Reynolds_stress_isotrope_ protected
Referenced by Modele_Lam_Bremhorst_VEF::Calcul_is_Reynolds_stress_isotrope(), Modele_EASM_Baglietto_VEF::readOn(), Modele_Lam_Bremhorst_VEF::readOn(), Modele_Launder_Sharma_VEF::readOn(), Modele_standard_KEps_VEF::readOn(), and Modele_Lam_Bremhorst_VEF::set_param().
D_
TRUST_Deriv< Champ_Don_base > Modele_Fonc_Bas_Reynolds_Base::D_ protected
Referenced by discretiser().
E_
TRUST_Deriv< Champ_Don_base > Modele_Fonc_Bas_Reynolds_Base::E_ protected
Referenced by discretiser().
F1_
TRUST_Deriv< Champ_Don_base > Modele_Fonc_Bas_Reynolds_Base::F1_ protected
Referenced by discretiser().
F2_
TRUST_Deriv< Champ_Don_base > Modele_Fonc_Bas_Reynolds_Base::F2_ protected
Referenced by discretiser().