TrioCFD: Fluide_Diphasique Class Reference
Fluide_Diphasique Class Reference
#include <Fluide_Diphasique.h>
Public Member Functions
const Champ_Don_base & beta_t () const override
Champ_Don_base & beta_t () override
const Champ_Don_base & capacite_calorifique () const override
Champ_Don_base & capacite_calorifique () override
const Champ_Don_base & conductivite () const override
Champ_Don_base & conductivite () override
const Champ_Don_base & diffusivite () const override
Champ_Don_base & diffusivite () override
const Type_info * get_info () const override
const Champ_base & masse_volumique () const override
Champ_base & masse_volumique () override
Public Member Functions inherited from Milieu_base
virtual int a_gravite () const
int associer_ (Objet_U &) override
virtual void associer_gravite (const Champ_Don_base &)
virtual Champ_Don_base & beta_t ()
virtual const Champ_Don_base & beta_t () const
virtual Champ_Don_base & capacite_calorifique ()
virtual const Champ_Don_base & capacite_calorifique () const
virtual Champ_Don_base & conductivite ()
virtual const Champ_Don_base & conductivite () const
virtual Champ_Don_base & diffusivite ()
virtual const Champ_Don_base & diffusivite () const
virtual int est_deja_associe ()
const Type_info * get_info () const override
virtual Champ_Don_base & gravite ()
virtual const Champ_Don_base & gravite () const
const Nom & le_nom () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual Champ_base & masse_volumique ()
virtual const Champ_base & masse_volumique () const
void nommer (const Nom &) override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Milieu_base
virtual void calculer_alpha ()
void ecrire (Sortie &) const
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
~Fluide_Diphasique()
Fluide_Diphasique::~Fluide_Diphasique ()
Fluide_Diphasique()
Fluide_Diphasique::Fluide_Diphasique () inline
References formule_mu_, Milieu_base::indic_rayo_, is_solid_particle_, and Milieu_base::NONRAYO.
Member Function Documentation
cree_instance()
Objet_U * Fluide_Diphasique::cree_instance () static
taille_memoire()
unsigned Fluide_Diphasique::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Fluide_Diphasique::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Fluide_Diphasique::info () static
get_info()
const Type_info * Fluide_Diphasique::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Milieu_base.
self_cast() [1/2]
Fluide_Diphasique & Fluide_Diphasique::self_cast (Objet_U & r) static
self_cast() [2/2]
const Fluide_Diphasique & Fluide_Diphasique::self_cast (const Objet_U & r) static
printOn()
Sortie & Fluide_Diphasique::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Milieu_base.
readOn()
Entree & Fluide_Diphasique::readOn (Entree & is) override protected virtual
Lecture d'un milieu sur un flot d'entree.
Format: { grandeur_physique type_champ bloc de lecture du champ } cf set_param method to know the understood keywords cf Param class to know possible options reading
Parameters
(Entree& is) le flot d'entree pour la lecture des parametres du milieu
Returns
(Entree&) le flot d'entree modifie
Exceptions
accolade ouvrante attendue
Reimplemented from Milieu_base.
References id_fluid_phase_, is_solid_particle_, phase0_, phase1_, Milieu_base::readOn(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by Fluide_Diphasique_IJK::readOn().
fluide_phase()
const Fluide_Incompressible & Fluide_Diphasique::fluide_phase (int la_phase) const
References phase0_, phase1_, and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by Champ_P1NC::calcul_y_plus_diphasique(), Champ_Face_VDF::calcul_y_plus_diphasique(), Navier_Stokes_FT_Disc::calculer_delta_u_interface(), Navier_Stokes_FT_Disc::calculer_dI_dt(), Paroi_std_hyd_VDF_diphasique::calculer_hyd(), Paroi_std_hyd_VEF_diphasique::calculer_hyd(), Transport_Marqueur_FT::calculer_proprietes_fluide_pos_particules(), Navier_Stokes_FT_Disc::compute_boussinesq_additional_gravity(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_friction_force_complet_tensor(), Post_Processing_Hydrodynamic_Forces::compute_friction_force_projected_tensor(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_friction_force_projected_tensor(), Post_Processing_Hydrodynamic_Forces::compute_heat_transfer(), Collision_Model_FT_sphere::compute_lagrangian_contact_forces(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_neighbors_coordinates_fluid_fa7(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_pressure_force_trilinear_linear(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_pressure_interf(), Triple_Line_Model_FT_Disc::compute_TCL_fluxes_in_all_boundary_cells(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_vinf_Stokes(), Post_Processing_Hydrodynamic_Forces::compute_viscosity_edges_sphere(), Transport_Marqueur_FT::construction_ensemble_proprietes(), Post_Processing_Hydrodynamic_Forces_Stokes::fill_sigma_Stokes_th(), Post_Processing_Hydrodynamic_Forces_Stokes::fill_Stokes_pressure_field(), Post_Processing_Hydrodynamic_Forces_Stokes::fill_Stokes_velocity_field(), Convection_Diffusion_Concentration_FT_Disc::mettre_a_jour_chimie(), Convection_Diffusion_Concentration_Turbulent_FT_Disc::mettre_a_jour_chimie(), Collision_Model_FT_base::preparer_calcul(), Collision_Model_FT_base::research_collision_pairs_Verlet(), Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_gradU_elem(), Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_gradU_elem_P1(), and IJK_Thermals::verifie_milieu().
sigma()
double Fluide_Diphasique::sigma () const
References sigma_, and Champ_Don_base::valeurs().
Referenced by Source_Trainee::ajouter(), Navier_Stokes_FTD_IJK::complete_initialise_ijk_fields(), Schema_Temps_IJK_base::find_timestep(), Navier_Stokes_FTD_IJK::initialise_ijk_fields(), and Navier_Stokes_FTD_IJK::projeter().
chaleur_latente()
double Fluide_Diphasique::chaleur_latente () const
References chaleur_latente_, Process::exit(), Objet_U_ptr::non_nul(), and Champ_Don_base::valeurs().
Referenced by Triple_Line_Model_FT_Disc::compute_TCL_fluxes_in_all_boundary_cells().
formule_mu()
int Fluide_Diphasique::formule_mu () const
References formule_mu_.
set_param()
void Fluide_Diphasique::set_param (Param & param) override virtual
Reimplemented from Milieu_base.
References Param::ajouter(), chaleur_latente_, formule_mu_, phase0_, phase1_, Param::REQUIRED, Milieu_base::set_additional_params(), and sigma_.
verifier_coherence_champs()
void Fluide_Diphasique::verifier_coherence_champs (int & err, Nom & message) override virtual
Reimplemented from Milieu_base.
References Milieu_base::a_gravite(), chaleur_latente_, Objet_U_ptr::non_nul(), phase0_, phase1_, sigma_, TRUST_Deriv< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), and Milieu_base::verifier_coherence_champs().
initialiser()
int Fluide_Diphasique::initialiser (const double temps) override virtual
Reimplemented from Milieu_base.
References Milieu_base::initialiser(), Milieu_base::initialiser_porosite(), phase0_, and phase1_.
mettre_a_jour()
void Fluide_Diphasique::mettre_a_jour (double temps) override virtual
Reimplemented from Milieu_base.
References Milieu_base::mettre_a_jour(), phase0_, and phase1_.
discretiser()
void Fluide_Diphasique::discretiser (const Probleme_base & pb, const Discretisation_base & dis) override virtual
Reimplemented from Milieu_base.
References Milieu_base::discretiser(), Milieu_base::discretiser_diametre_hydro(), Milieu_base::discretiser_porosite(), phase0_, and phase1_.
masse_volumique() [1/2]
const Champ_base & Fluide_Diphasique::masse_volumique () const inline override virtual
Renvoie la masse volumique du milieu.
(version const)
Returns
(Champ_base&) le champ donne representant la masse volumique
Reimplemented from Milieu_base.
masse_volumique() [2/2]
Champ_base & Fluide_Diphasique::masse_volumique () inline override virtual
Renvoie la masse volumique du milieu.
Returns
(Champ_base&) le champ donne representant la masse volumique
Reimplemented from Milieu_base.
diffusivite() [1/2]
const Champ_Don_base & Fluide_Diphasique::diffusivite () const inline override virtual
Renvoie la diffusivite du milieu.
(version const)
Returns
(Champ_Don_base&) le champ donne representant la diffusivite
Reimplemented from Milieu_base.
diffusivite() [2/2]
Champ_Don_base & Fluide_Diphasique::diffusivite () inline override virtual
Renvoie la diffusivite du milieu.
Returns
(Champ_Don_base&) le champ donne representant la diffusivite
Reimplemented from Milieu_base.
conductivite() [1/2]
const Champ_Don_base & Fluide_Diphasique::conductivite () const inline override virtual
Renvoie la conductivite du milieu.
(version const)
Returns
(Champ_Don_base&) le champ donne representant la conductivite
Reimplemented from Milieu_base.
conductivite() [2/2]
Champ_Don_base & Fluide_Diphasique::conductivite () inline override virtual
Renvoie la conductivite du milieu.
Returns
(Champ_Don_base&) le champ donne representant la conductivite
Reimplemented from Milieu_base.
capacite_calorifique() [1/2]
const Champ_Don_base & Fluide_Diphasique::capacite_calorifique () const inline override virtual
Renvoie la capacite calorifique du milieu.
(version const)
Returns
(Champ_Don_base&) le champ donne representant la capacite calorifique
Reimplemented from Milieu_base.
capacite_calorifique() [2/2]
Champ_Don_base & Fluide_Diphasique::capacite_calorifique () inline override virtual
Renvoie la capacite calorifique du milieu.
Returns
(Champ_Don_base&) le champ donne representant la capacite calorifique
Reimplemented from Milieu_base.
beta_t() [1/2]
const Champ_Don_base & Fluide_Diphasique::beta_t () const inline override virtual
Renvoie beta_t du milieu.
(version const)
Returns
(Champ_Don_base&) le champ donne representant beta_t
Reimplemented from Milieu_base.
beta_t() [2/2]
Champ_Don_base & Fluide_Diphasique::beta_t () inline override virtual
Renvoie beta_t du milieu.
Returns
(Champ_Don_base&) le champ donne representant beta_t
Reimplemented from Milieu_base.
get_is_solid_particle()
const bool & Fluide_Diphasique::get_is_solid_particle () const inline
References is_solid_particle_.
get_id_fluid_phase()
const int & Fluide_Diphasique::get_id_fluid_phase () const inline
References id_fluid_phase_.
Referenced by Transport_Interfaces_FT_Disc::calculer_vitesse_transport_interpolee(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_friction_force_complet_tensor(), Post_Processing_Hydrodynamic_Forces::compute_friction_force_projected_tensor(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_friction_force_projected_tensor(), Collision_Model_FT_sphere::compute_lagrangian_contact_forces(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_neighbors_coordinates_fluid_fa7(), Navier_Stokes_FT_Disc::compute_particles_eulerian_id_number(), Transport_Interfaces_FT_Disc::compute_particles_rms(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_pressure_force_trilinear_linear(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_pressure_interf(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_vinf_Stokes(), Post_Processing_Hydrodynamic_Forces::compute_viscosity_edges_sphere(), Post_Processing_Hydrodynamic_Forces_Stokes::fill_sigma_Stokes_th(), Post_Processing_Hydrodynamic_Forces_Stokes::fill_Stokes_pressure_field(), Post_Processing_Hydrodynamic_Forces_Stokes::fill_Stokes_velocity_field(), Collision_Model_FT_base::preparer_calcul(), Collision_Model_FT_base::research_collision_pairs_Verlet(), Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_gradU_elem(), and Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_gradU_elem_P1().
invalid_()
template<typename RETURN_TYPE > RETURN_TYPE Fluide_Diphasique::invalid_ (const char * nom_funct) const inline protected
Member Data Documentation
info_obj
const Type_info Fluide_Diphasique::info_obj static
phase0_
TRUST_Deriv< Milieu_base > Fluide_Diphasique::phase0_ protected
Referenced by discretiser(), fluide_phase(), Fluide_Diphasique_IJK::get_cp_vapour(), Fluide_Diphasique_IJK::get_delta_rho(), Fluide_Diphasique_IJK::get_lambda_vapour(), Fluide_Diphasique_IJK::get_mu_vapour(), Fluide_Diphasique_IJK::get_rho_vapour(), Fluide_Diphasique_IJK::get_set_cp_vapour(), Fluide_Diphasique_IJK::get_set_lambda_vapour(), initialiser(), mettre_a_jour(), readOn(), set_param(), and verifier_coherence_champs().
phase1_
TRUST_Deriv< Milieu_base > Fluide_Diphasique::phase1_ protected
Referenced by discretiser(), fluide_phase(), Fluide_Diphasique_IJK::get_cp_liquid(), Fluide_Diphasique_IJK::get_delta_rho(), Fluide_Diphasique_IJK::get_lambda_liquid(), Fluide_Diphasique_IJK::get_mu_liquid(), Fluide_Diphasique_IJK::get_rho_liquid(), initialiser(), mettre_a_jour(), readOn(), set_param(), and verifier_coherence_champs().
sigma_
TRUST_Deriv< Champ_Don_base > Fluide_Diphasique::sigma_ protected
Referenced by set_param(), sigma(), and verifier_coherence_champs().
chaleur_latente_
TRUST_Deriv< Champ_Don_base > Fluide_Diphasique::chaleur_latente_ protected
Referenced by chaleur_latente(), set_param(), and verifier_coherence_champs().
formule_mu_
Motcle Fluide_Diphasique::formule_mu_ protected
Referenced by Fluide_Diphasique(), formule_mu(), and set_param().
is_solid_particle_
bool Fluide_Diphasique::is_solid_particle_ protected
Referenced by Fluide_Diphasique(), get_is_solid_particle(), and readOn().
id_fluid_phase_
int Fluide_Diphasique::id_fluid_phase_ protected
Referenced by get_id_fluid_phase(), and readOn().