TrioCFD: ParcoursIJKDir Class Reference
ParcoursIJKDir Class Reference
#include <ParcoursIJKDir.h>
Public Member Functions
const Type_info * get_info () const override
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Constructor & Destructor Documentation
~ParcoursIJKDir()
ParcoursIJKDir::~ParcoursIJKDir ()
ParcoursIJKDir()
ParcoursIJKDir::ParcoursIJKDir () inline
References indices_to_keep_, next_elem_, and TRUSTArray< _TYPE_, _SIZE_ >::resize().
Member Function Documentation
cree_instance()
Objet_U * ParcoursIJKDir::cree_instance () static
taille_memoire()
unsigned ParcoursIJKDir::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int ParcoursIJKDir::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * ParcoursIJKDir::info () static
get_info()
const Type_info * ParcoursIJKDir::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
ParcoursIJKDir & ParcoursIJKDir::self_cast (Objet_U & r) static
self_cast() [2/2]
const ParcoursIJKDir & ParcoursIJKDir::self_cast (const Objet_U & r) static
printOn()
Sortie & ParcoursIJKDir::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
References Objet_U::printOn().
readOn()
Entree & ParcoursIJKDir::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
References Objet_U::readOn().
elem()
FixedVector< int, 3 > ParcoursIJKDir::elem (const int q) const inline
References i_, j_, k_, and next_elem_.
Referenced by Corrige_flux_FT_temperature_conv::extrapolation_amont_1_depuis_l_interface(), Corrige_flux_FT_temperature_conv::interpolation_quick_avec_1_ghost(), Corrige_flux_FT_temperature_conv::multiplie_par_rho_cp_de_la_face_monophasique(), Corrige_flux_FT_temperature_conv::remplace_flux_par_quick_ghost_amont_1(), Corrige_flux_FT_base::test_if_stencil_inclut_bout_interface_liquide(), and Corrige_flux_FT_base::test_if_stencil_inclut_bout_interface_vapeur().
i()
const int & ParcoursIJKDir::i () const inline
References i_.
Referenced by Corrige_flux_FT_temperature_conv::remplace_flux_par_somme_rhocpf_Tf_v_Sf(), Corrige_flux_FT_base::test_if_stencil_inclut_bout_interface_liquide(), and Corrige_flux_FT_base::test_if_stencil_inclut_bout_interface_vapeur().
j()
const int & ParcoursIJKDir::j () const inline
References j_.
Referenced by Corrige_flux_FT_temperature_conv::remplace_flux_par_somme_rhocpf_Tf_v_Sf(), Corrige_flux_FT_base::test_if_stencil_inclut_bout_interface_liquide(), and Corrige_flux_FT_base::test_if_stencil_inclut_bout_interface_vapeur().
k()
const int & ParcoursIJKDir::k () const inline
References k_.
Referenced by Corrige_flux_FT_temperature_conv::remplace_flux_par_somme_rhocpf_Tf_v_Sf(), Corrige_flux_FT_base::test_if_stencil_inclut_bout_interface_liquide(), and Corrige_flux_FT_base::test_if_stencil_inclut_bout_interface_vapeur().
face()
const int & ParcoursIJKDir::face () const inline
References dir_.
Referenced by Corrige_flux_FT_temperature_conv::extrapolation_amont_1_depuis_l_interface(), Corrige_flux_FT_temperature_conv::remplace_flux_par_quick_ghost_amont_1(), Corrige_flux_FT_temperature_conv::remplace_flux_par_somme_rhocpf_Tf_v_Sf(), Corrige_flux_FT_base::test_if_stencil_inclut_bout_interface_liquide(), and Corrige_flux_FT_base::test_if_stencil_inclut_bout_interface_vapeur().
set_dir()
void ParcoursIJKDir::set_dir (const int dir) inline
References dir_, set_indices_to_keep(), and set_next_elem().
Referenced by Corrige_flux_FT_temperature_conv::corrige_flux_faceIJ().
set_elem()
void ParcoursIJKDir::set_elem (const int i1, const int j1, const int k1) inline
References i_, j_, and k_.
Referenced by Corrige_flux_FT_temperature_conv::corrige_flux_faceIJ().
get_indices_to_keep()
const ArrOfInt & ParcoursIJKDir::get_indices_to_keep () const inline
References indices_to_keep_.
get_normale_vec()
const ArrOfInt & ParcoursIJKDir::get_normale_vec () const inline
References next_elem_.
Referenced by Corrige_flux_FT_temperature_conv::extrapolation_amont_1_depuis_l_interface().
calculer_surface_face()
double ParcoursIJKDir::calculer_surface_face (const Domaine_IJK & geom) const inline
References Domaine_IJK::get_constant_delta(), and indices_to_keep_.
Referenced by Corrige_flux_FT_temperature_conv::corrige_flux_faceIJ().
set_next_elem()
void ParcoursIJKDir::set_next_elem () protected
References dir_, and next_elem_.
Referenced by set_dir().
set_indices_to_keep()
void ParcoursIJKDir::set_indices_to_keep () protected
References dir_, and indices_to_keep_.
Referenced by set_dir().
Member Data Documentation
info_obj
const Type_info ParcoursIJKDir::info_obj static
dir_
int ParcoursIJKDir::dir_ =0 protected
Referenced by face(), set_dir(), set_indices_to_keep(), and set_next_elem().
i_
int ParcoursIJKDir::i_ =0 protected
Referenced by elem(), i(), and set_elem().
j_
int ParcoursIJKDir::j_ =0 protected
Referenced by elem(), j(), and set_elem().
k_
int ParcoursIJKDir::k_ =0 protected
Referenced by elem(), k(), and set_elem().
next_elem_
ArrOfInt ParcoursIJKDir::next_elem_ protected
Referenced by elem(), get_normale_vec(), ParcoursIJKDir(), and set_next_elem().
indices_to_keep_
ArrOfInt ParcoursIJKDir::indices_to_keep_ protected
Referenced by calculer_surface_face(), get_indices_to_keep(), ParcoursIJKDir(), and set_indices_to_keep().