TrioCFD: Source_Masse_Fluide_Dilatable_base Class Reference
Source_Masse_Fluide_Dilatable_base Class Reference abstract
#include <Source_Masse_Fluide_Dilatable_base.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Source_Masse_Fluide_Dilatable_base()
Source_Masse_Fluide_Dilatable_base::Source_Masse_Fluide_Dilatable_base ()
~Source_Masse_Fluide_Dilatable_base()
Source_Masse_Fluide_Dilatable_base::~Source_Masse_Fluide_Dilatable_base () override
Member Function Documentation
info()
const Type_info * Source_Masse_Fluide_Dilatable_base::info () static
get_info()
const Type_info * Source_Masse_Fluide_Dilatable_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
Reimplemented in Source_Masse_Fluide_Dilatable_VDF, and Source_Masse_Fluide_Dilatable_VEF.
self_cast() [1/2]
Source_Masse_Fluide_Dilatable_base & Source_Masse_Fluide_Dilatable_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Source_Masse_Fluide_Dilatable_base & Source_Masse_Fluide_Dilatable_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Source_Masse_Fluide_Dilatable_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
Reimplemented in Source_Masse_Fluide_Dilatable_VDF, and Source_Masse_Fluide_Dilatable_VEF.
readOn()
Entree & Source_Masse_Fluide_Dilatable_base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
Reimplemented in Source_Masse_Fluide_Dilatable_VDF, and Source_Masse_Fluide_Dilatable_VEF.
References Param::ajouter(), ch_front_source_, Process::exit(), Param::lire_avec_accolades_depuis(), nom_bord_, Objet_U::que_suis_je(), Param::REQUIRED, and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by Source_Masse_Fluide_Dilatable_VDF::readOn(), and Source_Masse_Fluide_Dilatable_VEF::readOn().
completer()
void Source_Masse_Fluide_Dilatable_base::completer ()
References Champ_front_base::associer_fr_dis_base(), ch_front_source_, domaine_cl_dis_, Process::exit(), file_out_, Champ_front_base::fixer_nb_valeurs_temporelles(), Champ_front_base::initialiser(), Process::je_suis_maitre(), TRUST_Ref< _CLASSE_ >::le_nom(), Frontiere_dis_base::le_nom(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), ncomp_, nom_bord_, Objet_U::nom_du_cas(), and Champ_front_base::valeurs().
Referenced by Navier_Stokes_Fluide_Dilatable_base::completer().
mettre_a_jour()
void Source_Masse_Fluide_Dilatable_base::mettre_a_jour (double temps)
References ch_front_source_, domaine_cl_dis_, Domaine_Cl_dis_base::domaine_dis(), Domaine_VF::face_surfaces(), file_out_, Process::je_suis_maitre(), Frontiere_dis_base::le_nom(), Process::mp_sum(), Front_VF::nb_faces(), ncomp_, nom_bord_, Front_VF::num_premiere_face(), Sortie_Fichier_base::setf(), TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), and Champ_front_base::valeurs().
Referenced by Navier_Stokes_Fluide_Dilatable_base::mettre_a_jour().
changer_temps_futur()
void Source_Masse_Fluide_Dilatable_base::changer_temps_futur (double temps, int i)
References ch_front_source_, and Champ_front_base::changer_temps_futur().
Referenced by Navier_Stokes_Fluide_Dilatable_base::initTimeStep().
set_temps_defaut()
void Source_Masse_Fluide_Dilatable_base::set_temps_defaut (double temps)
References ch_front_source_, and Champ_front_base::set_temps_defaut().
Referenced by Navier_Stokes_Fluide_Dilatable_base::initTimeStep().
associer_domaine_cl()
void Source_Masse_Fluide_Dilatable_base::associer_domaine_cl (const Domaine_Cl_dis_base & z) virtual
References domaine_cl_dis_.
Referenced by Navier_Stokes_Fluide_Dilatable_base::lire_motcle_non_standard().
nb_comp()
int Source_Masse_Fluide_Dilatable_base::nb_comp () inline
References ncomp_.
Referenced by Navier_Stokes_Fluide_Dilatable_base::completer().
fill_val_flux_tab()
void Source_Masse_Fluide_Dilatable_base::fill_val_flux_tab (DoubleTrav & val_flux) const
References ch_front_source_, domaine_cl_dis_, Frontiere_dis_base::le_nom(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Front_VF::nb_faces(), nom_bord_, Front_VF::num_premiere_face(), TRUST_Deriv< _CLASSE_ >::valeur(), and Champ_front_base::valeurs().
Referenced by Source_Masse_Fluide_Dilatable_VDF::ajouter_projection().
ajouter_eq_espece()
virtual void Source_Masse_Fluide_Dilatable_base::ajouter_eq_espece (const Convection_Diffusion_Fluide_Dilatable_base & eqn, const Fluide_Dilatable_base & fluide, const bool is_expl, DoubleVect & resu) const pure virtual
Implemented in Source_Masse_Fluide_Dilatable_VDF, and Source_Masse_Fluide_Dilatable_VEF.
Referenced by Convection_Diffusion_Fluide_Dilatable_Proto::derivee_en_temps_inco_sans_solveur_masse_impl().
ajouter_projection()
virtual void Source_Masse_Fluide_Dilatable_base::ajouter_projection (const Fluide_Dilatable_base & fluide, DoubleVect & resu) const pure virtual
Implemented in Source_Masse_Fluide_Dilatable_VDF, and Source_Masse_Fluide_Dilatable_VEF.
Referenced by EOS_Tools_VDF::secmembre_divU_Z().
Member Data Documentation
info_obj
const Type_info Source_Masse_Fluide_Dilatable_base::info_obj static
ncomp_
int Source_Masse_Fluide_Dilatable_base::ncomp_ = -1 protected
Referenced by completer(), mettre_a_jour(), and nb_comp().
nom_bord_
Nom Source_Masse_Fluide_Dilatable_base::nom_bord_ protected
Referenced by Source_Masse_Fluide_Dilatable_VEF::ajouter_eq_espece(), Source_Masse_Fluide_Dilatable_VDF::ajouter_projection(), Source_Masse_Fluide_Dilatable_VEF::ajouter_projection(), completer(), fill_val_flux_tab(), mettre_a_jour(), and readOn().
file_out_
Nom Source_Masse_Fluide_Dilatable_base::file_out_ protected
Referenced by completer(), and mettre_a_jour().
ch_front_source_
TRUST_Deriv< Champ_front_base > Source_Masse_Fluide_Dilatable_base::ch_front_source_ protected
Referenced by Source_Masse_Fluide_Dilatable_VEF::ajouter_eq_espece(), Source_Masse_Fluide_Dilatable_VEF::ajouter_projection(), changer_temps_futur(), completer(), fill_val_flux_tab(), mettre_a_jour(), readOn(), and set_temps_defaut().
domaine_cl_dis_
TRUST_Ref< Domaine_Cl_dis_base *> Source_Masse_Fluide_Dilatable_base::domaine_cl_dis_ protected
Referenced by Source_Masse_Fluide_Dilatable_VEF::ajouter_eq_espece(), Source_Masse_Fluide_Dilatable_VDF::ajouter_projection(), Source_Masse_Fluide_Dilatable_VEF::ajouter_projection(), associer_domaine_cl(), completer(), fill_val_flux_tab(), and mettre_a_jour().