TrioCFD: Operateur_IJK_faces_base_double Class Reference
Operateur_IJK_faces_base_double Class Reference abstract
#include <Operateur_IJK_base.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Operateur_IJK_faces_base_double()
Operateur_IJK_faces_base_double::Operateur_IJK_faces_base_double ()
~Operateur_IJK_faces_base_double()
Operateur_IJK_faces_base_double::~Operateur_IJK_faces_base_double () override
Member Function Documentation
info()
const Type_info * Operateur_IJK_faces_base_double::info () static
get_info()
const Type_info * Operateur_IJK_faces_base_double::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
Reimplemented in Operateur_IJK_faces_conv_base_double, Operateur_IJK_faces_diff_base_double, OpDiffIJK_double, OpDiffTurbIJK_double, OpDiffStdWithLaminarTransposeIJK_double, OpDiffStdWithLaminarTransposeAndDivergenceIJK_double, OpDiffAnisotropicIJK_double, OpDiffStdWithLaminarTransposeAnisotropicIJK_double, OpDiffStdWithLaminarTransposeAndDivergenceAnisotropicIJK_double, OpDiffTensorialZeroatwallIJK_double, OpDiffStdWithLaminarTransposeTensorialZeroatwallIJK_double, OpDiffTensorialAnisotropicZeroatwallIJK_double, OpDiffStdWithLaminarTransposeAndDivergenceTensorialZeroatwallIJK_double, OpDiffStdWithLaminarTransposeTensorialAnisotropicZeroatwallIJK_double, OpDiffStdWithLaminarTransposeAndDivergenceTensorialAnisotropicZeroatwallIJK_double, and OpDiffStructuralOnlyZeroatwallIJK_double.
self_cast() [1/2]
Operateur_IJK_faces_base_double & Operateur_IJK_faces_base_double::self_cast (Objet_U & r) static
self_cast() [2/2]
const Operateur_IJK_faces_base_double & Operateur_IJK_faces_base_double::self_cast (const Objet_U & r) static
printOn()
Sortie & Operateur_IJK_faces_base_double::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
Reimplemented in Operateur_IJK_faces_conv_base_double, Operateur_IJK_faces_diff_base_double, OpDiffIJK_double, OpDiffTurbIJK_double, OpDiffStdWithLaminarTransposeIJK_double, OpDiffStdWithLaminarTransposeAndDivergenceIJK_double, OpDiffAnisotropicIJK_double, OpDiffStdWithLaminarTransposeAnisotropicIJK_double, OpDiffStdWithLaminarTransposeAndDivergenceAnisotropicIJK_double, OpDiffTensorialZeroatwallIJK_double, OpDiffStdWithLaminarTransposeTensorialZeroatwallIJK_double, OpDiffTensorialAnisotropicZeroatwallIJK_double, OpDiffStdWithLaminarTransposeAndDivergenceTensorialZeroatwallIJK_double, OpDiffStdWithLaminarTransposeTensorialAnisotropicZeroatwallIJK_double, OpDiffStdWithLaminarTransposeAndDivergenceTensorialAnisotropicZeroatwallIJK_double, and OpDiffStructuralOnlyZeroatwallIJK_double.
readOn()
Entree & Operateur_IJK_faces_base_double::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
Reimplemented in Operateur_IJK_faces_conv_base_double, Operateur_IJK_faces_diff_base_double, OpDiffIJK_double, OpDiffTurbIJK_double, OpDiffStdWithLaminarTransposeIJK_double, OpDiffStdWithLaminarTransposeAndDivergenceIJK_double, OpDiffAnisotropicIJK_double, OpDiffStdWithLaminarTransposeAnisotropicIJK_double, OpDiffStdWithLaminarTransposeAndDivergenceAnisotropicIJK_double, OpDiffTensorialZeroatwallIJK_double, OpDiffStdWithLaminarTransposeTensorialZeroatwallIJK_double, OpDiffTensorialAnisotropicZeroatwallIJK_double, OpDiffStdWithLaminarTransposeAndDivergenceTensorialZeroatwallIJK_double, OpDiffStdWithLaminarTransposeTensorialAnisotropicZeroatwallIJK_double, OpDiffStdWithLaminarTransposeAndDivergenceTensorialAnisotropicZeroatwallIJK_double, and OpDiffStructuralOnlyZeroatwallIJK_double.
compute_dtstab_convection_local()
double Operateur_IJK_faces_base_double::compute_dtstab_convection_local (IJK_Field_double & dvx, IJK_Field_double & dvy, IJK_Field_double & dvz) virtual
References ConstIJK_ptr< _TYPE_, _TYPE_ARRAY_ >::get_center_right(), Domaine_IJK::get_constant_delta(), Domaine_IJK::get_delta(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_domaine(), Domaine_IJK::get_nb_elem_local(), and Domaine_IJK::get_offset_local().
Referenced by DNS_QC_double::run().
compute_set()
void Operateur_IJK_faces_base_double::compute_set (IJK_Field_double & dvx, IJK_Field_double & dvy, IJK_Field_double & dvz)
Referenced by Operateur_IJK_faces_conv_base_double::calculer(), Operateur_IJK_faces_diff_base_double::calculer(), OpConvCentre2IJK_double::calculer_avec_u_div_rhou(), and OpConvCentre4IJK_double::calculer_avec_u_div_rhou().
compute_add()
void Operateur_IJK_faces_base_double::compute_add (IJK_Field_double & dvx, IJK_Field_double & dvy, IJK_Field_double & dvz)
Referenced by Operateur_IJK_faces_conv_base_double::ajouter(), Operateur_IJK_faces_diff_base_double::ajouter(), OpConvCentre2IJK_double::ajouter_avec_u_div_rhou(), and OpConvCentre4IJK_double::ajouter_avec_u_div_rhou().
Operator_IJK_div()
void Operateur_IJK_faces_base_double::Operator_IJK_div (const IJK_Field_local_double & flux_x, const IJK_Field_local_double & flux_y, const IJK_Field_local_double & flux_zmin, const IJK_Field_local_double & flux_zmax, IJK_Field_double & resu, int k_layer, bool add) protected virtual
References ConstIJK_ptr< _TYPE_, _TYPE_ARRAY_ >::get_center_right(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), and Simd_template< _TYPE_ >::size().
correct_flux()
void Operateur_IJK_faces_base_double::correct_flux (IJK_Field_local_double *const flux, const int k_layer, const int dir, const int compo) protected virtual
correct_flux_spherical()
virtual void Operateur_IJK_faces_base_double::correct_flux_spherical (Simd_double & a, Simd_double & b, const int k_layer, const int dir) inline protected virtual
compute_flux_x_vx()
virtual void Operateur_IJK_faces_base_double::compute_flux_x_vx (IJK_Field_local_double & resu, const int k_layer) protected pure virtual
Implemented in OpConvAmontIJK_double, OpConvCentre2IJK_double, OpConvCentre4IJK_double, OpConvQuickSharpIJK_double, and Operateur_IJK_faces_diff_base_double.
compute_flux_x_vy()
virtual void Operateur_IJK_faces_base_double::compute_flux_x_vy (IJK_Field_local_double & resu, const int k_layer) protected pure virtual
Implemented in OpConvAmontIJK_double, OpConvCentre2IJK_double, OpConvCentre4IJK_double, OpConvQuickSharpIJK_double, and Operateur_IJK_faces_diff_base_double.
compute_flux_x_vz()
virtual void Operateur_IJK_faces_base_double::compute_flux_x_vz (IJK_Field_local_double & resu, const int k_layer) protected pure virtual
Implemented in OpConvAmontIJK_double, OpConvCentre2IJK_double, OpConvCentre4IJK_double, OpConvQuickSharpIJK_double, and Operateur_IJK_faces_diff_base_double.
compute_flux_y_vx()
virtual void Operateur_IJK_faces_base_double::compute_flux_y_vx (IJK_Field_local_double & resu, const int k_layer) protected pure virtual
Implemented in OpConvAmontIJK_double, OpConvCentre2IJK_double, OpConvCentre4IJK_double, OpConvQuickSharpIJK_double, and Operateur_IJK_faces_diff_base_double.
compute_flux_y_vy()
virtual void Operateur_IJK_faces_base_double::compute_flux_y_vy (IJK_Field_local_double & resu, const int k_layer) protected pure virtual
Implemented in OpConvAmontIJK_double, OpConvCentre2IJK_double, OpConvCentre4IJK_double, OpConvQuickSharpIJK_double, and Operateur_IJK_faces_diff_base_double.
compute_flux_y_vz()
virtual void Operateur_IJK_faces_base_double::compute_flux_y_vz (IJK_Field_local_double & resu, const int k_layer) protected pure virtual
Implemented in OpConvAmontIJK_double, OpConvCentre2IJK_double, OpConvCentre4IJK_double, OpConvQuickSharpIJK_double, and Operateur_IJK_faces_diff_base_double.
compute_flux_z_vx()
virtual void Operateur_IJK_faces_base_double::compute_flux_z_vx (IJK_Field_local_double & resu, const int k_layer) protected pure virtual
Implemented in OpConvAmontIJK_double, OpConvCentre2IJK_double, OpConvCentre4IJK_double, OpConvQuickSharpIJK_double, and Operateur_IJK_faces_diff_base_double.
compute_flux_z_vy()
virtual void Operateur_IJK_faces_base_double::compute_flux_z_vy (IJK_Field_local_double & resu, const int k_layer) protected pure virtual
Implemented in OpConvAmontIJK_double, OpConvCentre2IJK_double, OpConvCentre4IJK_double, OpConvQuickSharpIJK_double, and Operateur_IJK_faces_diff_base_double.
compute_flux_z_vz()
virtual void Operateur_IJK_faces_base_double::compute_flux_z_vz (IJK_Field_local_double & resu, const int k_layer) protected pure virtual
Implemented in OpConvAmontIJK_double, OpConvCentre2IJK_double, OpConvCentre4IJK_double, OpConvQuickSharpIJK_double, and Operateur_IJK_faces_diff_base_double.
exec_after_divergence_flux_x()
virtual void Operateur_IJK_faces_base_double::exec_after_divergence_flux_x (IJK_Field_double & resu, const int k_layer) inline protected virtual
Reimplemented in OpConvCentre2IJK_double, and OpConvCentre4IJK_double.
exec_after_divergence_flux_y()
virtual void Operateur_IJK_faces_base_double::exec_after_divergence_flux_y (IJK_Field_double & resu, const int k_layer) inline protected virtual
Reimplemented in OpConvCentre2IJK_double, and OpConvCentre4IJK_double.
exec_after_divergence_flux_z()
virtual void Operateur_IJK_faces_base_double::exec_after_divergence_flux_z (IJK_Field_double & resu, const int k_layer) inline protected virtual
Reimplemented in OpConvCentre2IJK_double, and OpConvCentre4IJK_double.
Member Data Documentation
info_obj
const Type_info Operateur_IJK_faces_base_double::info_obj static