TrioCFD: ParoiVEF_TBLE_scal Class Reference
ParoiVEF_TBLE_scal Class Reference
#include <ParoiVEF_TBLE_scal.h>
Public Member Functions
const Type_info * get_info () const override
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Turbulence_paroi_scal_base
void associer_modele (const Modele_turbulence_scal_base &)
const Type_info * get_info () const override
void imprimer_nusselt_mean_only (Sortie &, int, const TRUST_List< Nom > &, const Nom &) const
void imprimer_premiere_ligne_nusselt (int, const TRUST_List< Nom > &, const Nom &) const
int reprendre (Entree &is) override
int sauvegarder (Sortie &os) const override
virtual bool use_equivalent_distance () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Paroi_TBLE_QDM_Scal
void calculer_stat (int j, int i, double u, double v, double w, double T, double dt)
void imprimer_stat (Sortie &, double) const
int init_lois_paroi (const Domaine_VF &, const Domaine_Cl_dis_base &)
void init_valeurs_defaut ()
Entree & lire_donnees (const Motcle &motlu, Entree &s)
int reprendre (Entree &, const Domaine_dis_base &, const Domaine_Cl_dis_base &, double tps)
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Turbulence_paroi_scal_base
static void typer_lire_turbulence_paroi_scal (TRUST_Deriv< Turbulence_paroi_scal_base > &, const Modele_turbulence_scal_base &, Entree &)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
.SECTION voir aussi Turbulence_paroi_base
Constructor & Destructor Documentation
~ParoiVEF_TBLE_scal()
ParoiVEF_TBLE_scal::~ParoiVEF_TBLE_scal ()
Member Function Documentation
cree_instance()
Objet_U * ParoiVEF_TBLE_scal::cree_instance () static
taille_memoire()
unsigned ParoiVEF_TBLE_scal::taille_memoire () const override virtual
Reimplemented from Paroi_std_scal_hyd_VEF.
duplique()
int ParoiVEF_TBLE_scal::duplique () const override virtual
Reimplemented from Paroi_std_scal_hyd_VEF.
info()
const Type_info * ParoiVEF_TBLE_scal::info () static
get_info()
const Type_info * ParoiVEF_TBLE_scal::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Paroi_std_scal_hyd_VEF.
self_cast() [1/2]
ParoiVEF_TBLE_scal & ParoiVEF_TBLE_scal::self_cast (Objet_U & r) static
self_cast() [2/2]
const ParoiVEF_TBLE_scal & ParoiVEF_TBLE_scal::self_cast (const Objet_U & r) static
printOn()
Sortie & ParoiVEF_TBLE_scal::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Paroi_std_scal_hyd_VEF.
References Objet_U::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & ParoiVEF_TBLE_scal::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Paroi_std_scal_hyd_VEF.
References Paroi_TBLE_QDM_Scal::init_valeurs_defaut(), and Paroi_TBLE_QDM_Scal::lire_donnees().
calculer_scal()
int ParoiVEF_TBLE_scal::calculer_scal (Champ_Fonc_base & diffusivite_turb) override virtual
Reimplemented from Paroi_std_scal_hyd_VEF.
References Eq_couch_lim::aller_au_temps(), Eq_couch_lim::aller_jusqu_a_convergence(), Sources::calculer(), Milieu_base::capacite_calorifique(), Milieu_base::diffusivite(), Objet_U::dimension, Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), Paroi_TBLE_QDM_Scal::eps_statio, Paroi_TBLE_QDM_Scal::eq_temp, Probleme_base::equation(), Turbulence_paroi_scal_base::equivalent_distance_, Domaine_VF::face_normales(), Domaine_VF::face_voisins(), Eq_couch_lim::get_it(), Eq_couch_lim::get_Unp1(), Eq_couch_lim::get_y(), Convection_Diffusion_std::inconnue(), Turbulence_paroi_scal_base::le_dom_Cl_dis_, Turbulence_paroi_scal_base::le_dom_dis_, Milieu_base::masse_volumique(), Paroi_TBLE_QDM_Scal::max_it, Paroi_TBLE_QDM_Scal::max_it_statio, Equation_base::milieu(), Turbulence_paroi_scal_base::mon_modele_turb_scal, Field_base::nb_comp(), Front_VF::nb_faces(), Domaine_VF::nb_faces_tot(), Domaine_dis_base::nb_front_Cl(), Paroi_TBLE_QDM_Scal::nb_pts, Front_VF::num_face(), Paroi_TBLE_QDM_Scal::oui_stats, Schema_Temps_base::pas_de_temps(), Schema_Temps_base::pas_temps_min(), Equation_base::probleme(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Equation_base::schema_temps(), Eq_couch_lim::set_dt(), Eq_couch_lim::set_F(), Eq_couch_lim::set_u_y0(), Eq_couch_lim::set_u_yn(), Equation_base::sources(), Paroi_TBLE_QDM_Scal::statio, Schema_Temps_base::temps_courant(), TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), Champ_Inc_base::valeurs(), Champ_Proto::valeurs(), and Domaine_VF::volumes_entrelaces().
init_lois_paroi()
int ParoiVEF_TBLE_scal::init_lois_paroi () override virtual
Reimplemented from Paroi_std_scal_hyd_VEF.
References Objet_U::dimension, Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), Paroi_TBLE_QDM_Scal::epsilon, Paroi_TBLE_QDM_Scal::eq_temp, Turbulence_paroi_scal_base::equivalent_distance_, Process::exit(), Paroi_TBLE_QDM_Scal::fac, Domaine_VF::face_normales(), Domaine_VF::face_voisins(), Equation_base::get_modele(), Equation_base::inconnue(), Paroi_std_scal_hyd_VEF::init_lois_paroi(), Paroi_TBLE_QDM_Scal::init_lois_paroi(), Eq_couch_lim::initialiser(), Process::je_suis_maitre(), Turbulence_paroi_scal_base::le_dom_Cl_dis_, Turbulence_paroi_scal_base::le_dom_dis_, Modele_turbulence_hyd_base::loi_paroi(), Paroi_TBLE_QDM_Scal::max_it, Turbulence_paroi_scal_base::mon_modele_turb_scal, Paroi_TBLE_QDM_Scal::nb_comp, Front_VF::nb_faces(), Front_VF::nb_faces_tot(), Domaine_dis_base::nb_front_Cl(), Paroi_TBLE_QDM_Scal::nb_pts, Paroi_TBLE_QDM_Scal::nu_t_dyn, Front_VF::num_face(), Paroi_TBLE_QDM_Scal::oui_stats, Paroi_TBLE_QDM_Scal::reprise_ok, Equation_base::schema_temps(), Eq_couch_lim::set_u_y0(), Eq_couch_lim::set_u_yn(), Eq_couch_lim::set_Uinit(), Eq_couch_lim::set_Uinit_lin(), Eq_couch_lim::set_y0(), Eq_couch_lim::set_yn(), Schema_Temps_base::temps_courant(), Paroi_TBLE_QDM_Scal::tps_deb_stats, TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), TRUST_Ref_Objet_U::valeur(), Champ_Inc_base::valeurs(), and Paroi_TBLE_QDM_Scal::valeurs_reprises.
imprimer_nusselt()
void ParoiVEF_TBLE_scal::imprimer_nusselt (Sortie & os) const override virtual
Reimplemented from Paroi_scal_hyd_base_VEF.
References Turbulence_paroi_scal_base::equivalent_distance_, Paroi_scal_hyd_base_VEF::imprimer_nusselt(), Paroi_TBLE_QDM_Scal::imprimer_sondes(), Paroi_TBLE_QDM_Scal::imprimer_stat(), Convection_Diffusion_std::inconnue(), Turbulence_paroi_scal_base::mon_modele_turb_scal, and Champ_base::temps().
sauvegarder()
int ParoiVEF_TBLE_scal::sauvegarder (Sortie &) const override virtual
Sauvegarde d'un Objet_U sur un flot de sortie Methode a surcharger.
Parameters
(Sortie&) flot de sortie a utiliser pour la sauvegarde
Returns
(int) code de retour
Reimplemented from Turbulence_paroi_scal_base.
References Turbulence_paroi_scal_base::le_dom_Cl_dis_, Turbulence_paroi_scal_base::le_dom_dis_, Turbulence_paroi_scal_base::mon_modele_turb_scal, Paroi_TBLE_QDM_Scal::sauvegarder(), and TRUST_Ref< _CLASSE_ >::valeur().
reprendre()
int ParoiVEF_TBLE_scal::reprendre (Entree &) override virtual
Reprise d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree&) flot d'entree a utiliser pour la reprise
Returns
(int) code de retour
Reimplemented from Turbulence_paroi_scal_base.
References Turbulence_paroi_scal_base::le_dom_Cl_dis_, Turbulence_paroi_scal_base::le_dom_dis_, Turbulence_paroi_scal_base::mon_modele_turb_scal, TRUST_Ref< _CLASSE_ >::non_nul(), Paroi_TBLE_QDM_Scal::reprendre(), and TRUST_Ref< _CLASSE_ >::valeur().
getPbBase()
const Probleme_base & ParoiVEF_TBLE_scal::getPbBase () const override virtual
Implements Paroi_TBLE_QDM_Scal.
References Turbulence_paroi_scal_base::mon_modele_turb_scal.
getLoiParoiHydraulique()
Paroi_TBLE_QDM & ParoiVEF_TBLE_scal::getLoiParoiHydraulique () override virtual
Implements Paroi_TBLE_QDM_Scal.
References Probleme_base::equation(), Process::exit(), Equation_base::get_modele(), getLoiParoiHydraulique(), Modele_turbulence_hyd_base::loi_paroi(), Turbulence_paroi_scal_base::mon_modele_turb_scal, and TRUST_Ref_Objet_U::valeur().
Referenced by get_eq_couch_lim(), getLoiParoiHydraulique(), and getMuLambda().
getMuLambda()
MuLambda_TBLE_base & ParoiVEF_TBLE_scal::getMuLambda () override virtual
Implements Paroi_TBLE_QDM_Scal.
References getLoiParoiHydraulique(), and Paroi_TBLE_QDM::getMuLambda().
get_eq_couch_lim()
Eq_couch_lim & ParoiVEF_TBLE_scal::get_eq_couch_lim (int i) override virtual
Implements Paroi_TBLE_QDM_Scal.
References Paroi_TBLE_QDM::get_eq_couch_lim(), and getLoiParoiHydraulique().
Member Data Documentation
info_obj
const Type_info ParoiVEF_TBLE_scal::info_obj static