TrioCFD: Sauvegarde_Reprise_Maillage_FT Class Reference
Sauvegarde_Reprise_Maillage_FT Class Reference
#include <Sauvegarde_Reprise_Maillage_FT.h>
Static Public Member Functions
static void lire_xyz (Maillage_FT_Disc &mesh, const Domaine_VF *domaine_vf, Entree *fichier, const Domaine *domaine_src)
Member Function Documentation
ecrire_xyz()
void Sauvegarde_Reprise_Maillage_FT::ecrire_xyz (const Maillage_FT_Disc & mesh, const Domaine_VF & domaine_vf, Sortie & fichier) static
References Process::check_int_overflow(), Maillage_FT_Disc::desc_sommets(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Desc_Structure_FT::echange_espace_virtuel(), Domaine_VF::elem_faces(), Maillage_FT_Disc::facette_virtuelle(), Maillage_FT_Disc::facettes_, Process::je_suis_maitre(), Process::mppartial_sum(), Maillage_FT_Disc::nb_facettes(), Maillage_FT_Disc::nb_sommets(), Domaine_VF::numero_face_local(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), Maillage_FT_Disc::sommet_elem_, Maillage_FT_Disc::sommet_face_bord_, Maillage_FT_Disc::sommet_virtuel(), Maillage_FT_Disc::sommets_, Maillage_FT_Disc::temps_physique_, and Domaine_VF::xp().
Referenced by Maillage_FT_Disc::sauvegarder().
lire_xyz()
void Sauvegarde_Reprise_Maillage_FT::lire_xyz (Maillage_FT_Disc & mesh, const Domaine_VF * domaine_vf, Entree * fichier, const Domaine * domaine_src) static
Remplissage du maillage mesh a partir d'un fichier de sauvegarde xyz (fichier) ou d'un domaine source (domaine_src pour importation d'une cao)
domaine_vf est le domaine support du maillage (pour calcul de l'indice de l'element contenant chaque sommet du mesh. domaine_vf peut etre nul dans le cas d'une reprise xyz au cours de l'etape 'avancer'. Dans ce cas, on lit les coordonnees et les elements mais on ne remplit pas mesh.
References TRUSTArray< _TYPE_, _SIZE_ >::addr(), TRUSTArray< _TYPE_, _SIZE_ >::append_array(), Process::barrier(), Schema_Comm::begin_comm(), Desc_Structure_FT::calcul_schema_comm(), Domaine_32_64< _SIZE_ >::coord_sommets(), Maillage_FT_Disc::creer_sommets_virtuels(), Maillage_FT_Disc::desc_facettes_, Maillage_FT_Disc::desc_sommets(), Maillage_FT_Disc::desc_sommets_, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Domaine_dis_base::domaine(), Maillage_FT_Disc::drapeaux_sommets_, Desc_Structure_FT::echange_espace_virtuel(), Schema_Comm::echange_taille_et_messages(), Domaine_VF::elem_faces(), Schema_Comm::end_comm(), Process::exit(), Maillage_FT_Disc::facette_num_owner_, Maillage_FT_Disc::facettes_, Entree::get(), Domaine_32_64< _SIZE_ >::les_elems(), Process::me(), Maillage_FT_Disc::MINIMAL, Domaine_32_64< _SIZE_ >::nb_elem(), Maillage_FT_Disc::nb_facettes(), Domaine_32_64< _SIZE_ >::nb_som(), Maillage_FT_Disc::nb_sommets(), Process::nproc(), Schema_Comm::recv_buffer(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), Schema_Comm::send_buffer(), Schema_Comm::set_send_recv_pe_list(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), Maillage_FT_Disc::sommet_elem_, Maillage_FT_Disc::sommet_face_bord_, Maillage_FT_Disc::sommet_num_owner_, Maillage_FT_Disc::sommet_PE_owner_, Maillage_FT_Disc::sommets_, Maillage_FT_Disc::statut_, and Maillage_FT_Disc::temps_physique_.
Referenced by Transport_Interfaces_FT_Disc::lire_maillage_ft_cao(), and Maillage_FT_Disc::reprendre().
init_temps_physique()
int Sauvegarde_Reprise_Maillage_FT::init_temps_physique (Maillage_FT_Disc & mesh) protected
init_sommets()
void Sauvegarde_Reprise_Maillage_FT::init_sommets (Maillage_FT_Disc & mesh, const Domaine_VF * domaine_vf) protected
init_facettes()
void Sauvegarde_Reprise_Maillage_FT::init_facettes (Maillage_FT_Disc & mesh, const Domaine_VF * domaine_vf) protected