TrioCFD: Convection_Diffusion_Concentration_FT_Disc Class Reference
Convection_Diffusion_Concentration_FT_Disc Class Reference
#include <Convection_Diffusion_Concentration_FT_Disc.h>
Public Member Functions
const Type_info * get_info () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
Public Member Functions inherited from Convection_Diffusion_Concentration
void associer_constituant (const Constituant &)
void associer_milieu_base (const Milieu_base &) override
Constituant & constituant ()
const Constituant & constituant () const
const Motcle & domaine_application () const override
const Type_info * get_info () const override
int impr (Sortie &os) const override
const Champ_Inc_base & inconnue () const override
Champ_Inc_base & inconnue () override
int lire_motcle_non_standard (const Motcle &, Entree &) override
void mettre_a_jour (double) override
const Milieu_base & milieu () const override
Milieu_base & milieu () override
int nb_constituants () const
int preparer_calcul () override
Public Member Functions inherited from Convection_Diffusion_std
void associer_vitesse (const Champ_base &)
const Type_info * get_info () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
int nombre_d_operateurs () const override
const Operateur & operateur (int) const override
Operateur & operateur (int) override
const Champ_Inc_base & vitesse_transportante () const
Public Member Functions inherited from Equation_base
virtual void abortTimeStep ()
virtual void associer_domaine_dis (const Domaine_dis_base &)
virtual void associer_pb_base (const Probleme_base &)
virtual void associer_sch_tps_base (const Schema_Temps_base &)
virtual double calculer_pas_de_temps () const
virtual void completer ()
virtual std::vector< YAML_data > data_a_sauvegarder () const
DoubleTab & derivee_en_temps_conv (DoubleTab &, const DoubleTab &)
virtual DoubleTab & derivee_en_temps_inco (DoubleTab &)
const Discretisation_base & discretisation () const
virtual void discretiser ()
virtual const Motcle & domaine_application () const
virtual Domaine_Cl_dis_base & domaine_Cl_dis ()
virtual const Domaine_Cl_dis_base & domaine_Cl_dis () const
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual void imprimer (Sortie &os) const
virtual bool initTimeStep (double dt)
const Nom & le_nom () const override
int limpr () const
virtual void mettre_a_jour (double temps)
virtual int preparer_calcul ()
Probleme_base & probleme ()
const Probleme_base & probleme () const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Schema_Temps_base & schema_temps ()
const Schema_Temps_base & schema_temps () const
Solveur_Masse_base & solv_masse ()
const Solveur_Masse_base & solv_masse () const
Sources & sources ()
const Sources & sources () const
virtual void valider_iteration ()
virtual void verifie_ch_init_nb_comp (const Champ_Inc_base &ch_ref, const int nb_comp) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Equation_base
virtual Entree & lire_cl (Entree &)
virtual Entree & lire_cond_init (Entree &)
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual Entree & lire_sources (Entree &)
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
virtual int verif_Cl () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
See also
Convection_Diffusion_Concentration
Member Enumeration Documentation
Options
enum Convection_Diffusion_Concentration_FT_Disc::Options protected
Enumerator
RIEN
RAMASSE_MIETTES_SIMPLE
Constructor & Destructor Documentation
~Convection_Diffusion_Concentration_FT_Disc()
Convection_Diffusion_Concentration_FT_Disc::~Convection_Diffusion_Concentration_FT_Disc ()
Convection_Diffusion_Concentration_FT_Disc()
Convection_Diffusion_Concentration_FT_Disc::Convection_Diffusion_Concentration_FT_Disc ()
References constante_cinetique_, constante_cinetique_nu_t_, modele_cinetique_, option_, phase_a_conserver_, and RIEN.
Member Function Documentation
cree_instance()
Objet_U * Convection_Diffusion_Concentration_FT_Disc::cree_instance () static
taille_memoire()
unsigned Convection_Diffusion_Concentration_FT_Disc::taille_memoire () const override virtual
Reimplemented from Convection_Diffusion_Concentration.
duplique()
int Convection_Diffusion_Concentration_FT_Disc::duplique () const override virtual
Reimplemented from Convection_Diffusion_Concentration.
info()
const Type_info * Convection_Diffusion_Concentration_FT_Disc::info () static
get_info()
const Type_info * Convection_Diffusion_Concentration_FT_Disc::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Convection_Diffusion_Concentration.
self_cast() [1/2]
Convection_Diffusion_Concentration_FT_Disc & Convection_Diffusion_Concentration_FT_Disc::self_cast (Objet_U & r) static
self_cast() [2/2]
const Convection_Diffusion_Concentration_FT_Disc & Convection_Diffusion_Concentration_FT_Disc::self_cast (const Objet_U & r) static
printOn()
Sortie & Convection_Diffusion_Concentration_FT_Disc::printOn (Sortie & os) const override protected virtual
Surcharge Objet_U::printOn Imprime l'equation et ses composants sur un flot de sortie.
Imprime le nom de l'equation, le solveur masse, les termes sources les conditions aux limites discretisees, les inconnues et les operateurs.
Parameters
(Sortie& os) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Convection_Diffusion_Concentration.
References Convection_Diffusion_Concentration::printOn().
readOn()
Entree & Convection_Diffusion_Concentration_FT_Disc::readOn (Entree & is) override protected virtual
cf Convection_Diffusion_Concentration::readOn(is)
Reimplemented from Convection_Diffusion_Concentration.
References constante_cinetique_nu_t_, equations_source_chimie_, Process::exit(), Process::je_suis_maitre(), Equation_base::le_nom(), modele_cinetique_, nom_equation_nu_t_, Convection_Diffusion_Concentration::readOn(), and TRUST_Vector< _CLASSE_ >::size().
set_param()
void Convection_Diffusion_Concentration_FT_Disc::set_param (Param & titi) override virtual
Reimplemented from Convection_Diffusion_Concentration.
References Param::ajouter(), Param::ajouter_condition(), Param::ajouter_non_std(), constante_cinetique_, constante_cinetique_nu_t_, equations_source_chimie_, modele_cinetique_, nom_domaine_sortie_, nom_equation_nu_t_, phase_a_conserver_, Param::REQUIRED, and Convection_Diffusion_Concentration::set_param().
lire_motcle_non_standard()
int Convection_Diffusion_Concentration_FT_Disc::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Convection_Diffusion_Concentration.
References Process::barrier(), Process::exit(), Convection_Diffusion_Concentration::lire_motcle_non_standard(), Equation_base::mon_probleme, option_, RAMASSE_MIETTES_SIMPLE, ref_eq_transport_, RIEN, and TRUST_Ref< _CLASSE_ >::valeur().
mettre_a_jour()
void Convection_Diffusion_Concentration_FT_Disc::mettre_a_jour (double temps) override virtual
appel a mettre_a_jour() de l'ancetre et application de l' "option_" choisie pour traiter la presence d'une interface.
Reimplemented from Convection_Diffusion_Concentration.
References Process::barrier(), Equation_base::domaine_Cl_dis(), Equation_base::domaine_dis(), equations_source_chimie_, Process::exit(), Domaine_VF::faces_doubles(), Convection_Diffusion_Concentration::inconnue(), Process::je_suis_maitre(), Equation_base::le_nom(), marquer_faces_sous_domaine(), Convection_Diffusion_Concentration::mettre_a_jour(), mettre_a_jour_chimie(), Process::mp_sum(), multiplier_valeurs_faces(), Domaine_VF::nb_faces(), Domaine_VEF::nb_faces_non_std(), nom_domaine_sortie_, option_, Schema_Temps_base::pas_de_temps(), Equation_base::probleme(), ramasse_miette_simple(), RAMASSE_MIETTES_SIMPLE, ref_eq_transport_, RIEN, Probleme_base::schema_temps(), TRUST_Vector< _CLASSE_ >::size(), Champ_Inc_base::valeurs(), Debog::verifier(), and Domaine_VF::volumes_entrelaces().
ramasse_miette_simple()
void Convection_Diffusion_Concentration_FT_Disc::ramasse_miette_simple (double temps) protected
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Transport_Interfaces_FT_Disc::inconnue(), Convection_Diffusion_Concentration::inconnue(), Process::je_suis_maitre(), Process::Journal(), phase_a_conserver_, ref_eq_transport_, TRUSTVect< _TYPE_, _SIZE_ >::size(), TRUST_Ref< _CLASSE_ >::valeur(), and Champ_Proto::valeurs().
Referenced by mettre_a_jour().
mettre_a_jour_chimie()
void Convection_Diffusion_Concentration_FT_Disc::mettre_a_jour_chimie () protected
References Process::barrier(), constante_cinetique_, constante_cinetique_nu_t_, Convection_Diffusion_Concentration::constituant(), Constituant::diffusivite_constituant(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Equation_base::domaine_dis(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), equations_source_chimie_, Process::exit(), Fluide_Diphasique::fluide_phase(), Probleme_base::get_equation_by_name(), Equation_base::get_modele(), Probleme_base::getset_equation_by_name(), Equation_base::inconnue(), Convection_Diffusion_Concentration::inconnue(), Probleme_base::milieu(), modele_cinetique_, Equation_base::mon_probleme, nom_equation_nu_t_, Schema_Temps_base::pas_de_temps(), ref_eq_transport_, Probleme_base::schema_temps(), TRUST_Vector< _CLASSE_ >::size(), TRUST_Ref< _CLASSE_ >::valeur(), TRUST_Ref_Objet_U::valeur(), Champ_Don_base::valeurs(), Champ_Inc_base::valeurs(), Fluide_base::viscosite_cinematique(), and Modele_turbulence_hyd_base::viscosite_turbulente().
Referenced by mettre_a_jour().
multiplier_valeurs_faces()
void Convection_Diffusion_Concentration_FT_Disc::multiplier_valeurs_faces (const ArrOfBit marqueurs_faces, double facteur, double & integrale_avant, DoubleTab & tab) protected
References Equation_base::domaine_Cl_dis(), Equation_base::domaine_dis(), Domaine_VF::faces_doubles(), Process::mp_sum(), Domaine_VF::nb_faces(), Domaine_VEF::nb_faces_non_std(), and Domaine_VF::volumes_entrelaces().
Referenced by mettre_a_jour().
marquer_faces_sous_domaine()
void Convection_Diffusion_Concentration_FT_Disc::marquer_faces_sous_domaine (const Nom & nom_sous_domaine, ArrOfBit & marqueur, int sans_faces_non_std_volume_nul) const protected
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Domaine_dis_base::domaine(), Equation_base::domaine_Cl_dis(), Equation_base::domaine_dis(), Domaine_VF::elem_faces(), Sous_Domaine_32_64< _SIZE_ >::nb_elem_tot(), Domaine_VEF::nb_faces_non_std(), Domaine_VF::nb_faces_tot(), ArrOfBit_32_64< _SIZE_ >::resize_array(), ArrOfBit_32_64< _SIZE_ >::setbit(), and Domaine_32_64< _SIZE_ >::ss_domaine().
Referenced by mettre_a_jour().
Member Data Documentation
info_obj
const Type_info Convection_Diffusion_Concentration_FT_Disc::info_obj static
option_
Options Convection_Diffusion_Concentration_FT_Disc::option_ protected
Referenced by Convection_Diffusion_Concentration_FT_Disc(), lire_motcle_non_standard(), and mettre_a_jour().
phase_a_conserver_
int Convection_Diffusion_Concentration_FT_Disc::phase_a_conserver_ protected
Referenced by Convection_Diffusion_Concentration_FT_Disc(), ramasse_miette_simple(), and set_param().
ref_eq_transport_
TRUST_Ref< Equation_base *> Convection_Diffusion_Concentration_FT_Disc::ref_eq_transport_ protected
Referenced by lire_motcle_non_standard(), mettre_a_jour(), mettre_a_jour_chimie(), and ramasse_miette_simple().
equations_source_chimie_
Noms Convection_Diffusion_Concentration_FT_Disc::equations_source_chimie_ protected
Referenced by mettre_a_jour(), mettre_a_jour_chimie(), readOn(), and set_param().
constante_cinetique_
double Convection_Diffusion_Concentration_FT_Disc::constante_cinetique_ protected
Referenced by Convection_Diffusion_Concentration_FT_Disc(), mettre_a_jour_chimie(), and set_param().
constante_cinetique_nu_t_
double Convection_Diffusion_Concentration_FT_Disc::constante_cinetique_nu_t_ protected
Referenced by Convection_Diffusion_Concentration_FT_Disc(), mettre_a_jour_chimie(), readOn(), and set_param().
nom_equation_nu_t_
Nom Convection_Diffusion_Concentration_FT_Disc::nom_equation_nu_t_ protected
Referenced by mettre_a_jour_chimie(), readOn(), and set_param().
modele_cinetique_
int Convection_Diffusion_Concentration_FT_Disc::modele_cinetique_ protected
Referenced by Convection_Diffusion_Concentration_FT_Disc(), mettre_a_jour_chimie(), readOn(), and set_param().
nom_domaine_sortie_
Nom Convection_Diffusion_Concentration_FT_Disc::nom_domaine_sortie_ protected
Referenced by mettre_a_jour(), and set_param().