TrioCFD: Fluide_reel_base Class Reference
Fluide_reel_base Class Reference abstract
#include <Fluide_reel_base.h>
Classes
struct H_to_T
struct T_to_H
Public Member Functions
const Type_info * get_info () const override
void mettre_a_jour (double temps) override
Public Member Functions inherited from Fluide_base
const Type_info * get_info () const override
void mettre_a_jour (double) override
void verifier_coherence_champs (int &err, Nom &message) override
Public Member Functions inherited from Milieu_base
virtual int a_gravite () const
int associer_ (Objet_U &) override
virtual void associer_gravite (const Champ_Don_base &)
virtual Champ_Don_base & beta_t ()
virtual const Champ_Don_base & beta_t () const
virtual Champ_Don_base & capacite_calorifique ()
virtual const Champ_Don_base & capacite_calorifique () const
virtual Champ_Don_base & conductivite ()
virtual const Champ_Don_base & conductivite () const
virtual Champ_Don_base & diffusivite ()
virtual const Champ_Don_base & diffusivite () const
virtual int est_deja_associe ()
const Type_info * get_info () const override
virtual Champ_Don_base & gravite ()
virtual const Champ_Don_base & gravite () const
const Nom & le_nom () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual Champ_base & masse_volumique ()
virtual const Champ_base & masse_volumique () const
void nommer (const Nom &) override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Fluide_base
void creer_nu ()
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Milieu_base
virtual void calculer_alpha ()
void ecrire (Sortie &) const
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
ses proprietes:
viscosite cinematique, (mu)
viscosite dynamique, (nu)
masse volumique, (rho)
diffusivite, (alpha)
conductivite, (lambda)
capacite calorifique, (Cp)
dilatabilite thermique du constituant (beta_co)
See also
Milieu_base
Constructor & Destructor Documentation
~Fluide_reel_base()
Fluide_reel_base::~Fluide_reel_base () override
Fluide_reel_base()
Fluide_reel_base::Fluide_reel_base () inline
References converter_H_to_T_, converter_T_to_H_, Fluide_reel_base::H_to_T::set_instance(), and Fluide_reel_base::T_to_H::set_instance().
Member Function Documentation
info()
const Type_info * Fluide_reel_base::info () static
get_info()
const Type_info * Fluide_reel_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Fluide_base.
Reimplemented in Fluide_eau_c3_gaz, Fluide_eau_c3_liquide, Fluide_R12_c1_gaz, Fluide_R12_c1_liquide, Fluide_sodium_gaz, Fluide_sodium_liquide, Fluide_stiffened_gas, Fluide_generique_CoolProp, Fluide_generique_EOS, and Fluide_generique_TPPI_base.
self_cast() [1/2]
Fluide_reel_base & Fluide_reel_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Fluide_reel_base & Fluide_reel_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Fluide_reel_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Fluide_base.
Reimplemented in Fluide_eau_c3_gaz, Fluide_eau_c3_liquide, Fluide_R12_c1_gaz, Fluide_R12_c1_liquide, Fluide_sodium_gaz, Fluide_sodium_liquide, Fluide_stiffened_gas, Fluide_generique_CoolProp, Fluide_generique_EOS, and Fluide_generique_TPPI_base.
readOn()
Entree & Fluide_reel_base::readOn (Entree & is) override protected virtual
Lit les caracteristiques du fluide a partir d'un flot d'entree.
Format: Fluide_base { Mu type_champ bloc de lecture de champ Rho Champ_Uniforme 1 vrel [Cp Champ_Uniforme 1 vrel] [Lambda type_champ bloc de lecture de champ] [Beta_th type_champ bloc de lecture de champ] [Beta_co type_champ bloc de lecture de champ] } cf Milieu_base::readOn
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Exceptions
accolade ouvrante attendue
Reimplemented from Fluide_base.
Reimplemented in Fluide_eau_c3_gaz, Fluide_eau_c3_liquide, Fluide_R12_c1_gaz, Fluide_R12_c1_liquide, Fluide_sodium_gaz, Fluide_sodium_liquide, Fluide_stiffened_gas, Fluide_generique_CoolProp, Fluide_generique_EOS, and Fluide_generique_TPPI_base.
References Process::exit(), h_ref_, P_ref_, Objet_U::que_suis_je(), Fluide_base::readOn(), and T_ref_.
Referenced by Fluide_eau_c3_gaz::readOn(), Fluide_eau_c3_liquide::readOn(), Fluide_sodium_gaz::readOn(), Fluide_sodium_liquide::readOn(), Fluide_stiffened_gas::readOn(), and Fluide_generique_TPPI_base::readOn().
initTimeStep()
bool Fluide_reel_base::initTimeStep (double dt) override virtual
Reimplemented from Fluide_base.
References Fluide_base::ch_e_int_, Fluide_base::ch_h_ou_T_, Milieu_base::ch_rho_, Milieu_base::equation_, Schema_Temps_base::nb_valeurs_futures(), Schema_Temps_base::temps_futur(), and TRUST_Deriv< _CLASSE_ >::valeur().
initialiser()
int Fluide_reel_base::initialiser (const double temps) override virtual
Initialise les parametres du fluide.
Reimplemented from Fluide_base.
References Champ_Inc_base::associer_eqn(), Milieu_base::ch_alpha_, Milieu_base::ch_alpha_fois_rho_, Milieu_base::ch_beta_th_, Milieu_base::ch_Cp_, Fluide_base::ch_e_int_, Milieu_base::ch_g_, Fluide_base::ch_h_ou_T_, Milieu_base::ch_lambda_, Fluide_base::ch_mu_, Fluide_base::ch_nu_, Milieu_base::ch_rho_, Milieu_base::ch_rho_Cp_comme_T_, Champ_Inc_base::changer_temps(), Milieu_base::equation(), Milieu_base::id_composite_, Champ_Don_base::initialiser(), Milieu_base::initialiser_porosite(), is_incompressible(), mettre_a_jour(), Objet_U_ptr::non_nul(), P_ref_, res_en_T_, Champ_Inc_base::resize_val_bord(), Champ_Inc_base::set_val_bord_fluide_multiphase(), t_init_, T_ref_, TRUST_Deriv< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), and Champ_Proto::valeurs().
check_unknown_range()
int Fluide_reel_base::check_unknown_range () const override virtual
Reimplemented from Milieu_base.
References Fluide_base::ch_e_int_, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Milieu_base::equation(), Milieu_base::id_composite_, Equation_base::inconnue(), is_incompressible(), Process::mp_max(), Process::mp_min(), Objet_U::que_suis_je(), res_en_T_, unknown_range(), unknown_range_h(), Champ_Inc_base::valeurs(), and Champ_Proto::valeurs().
is_incompressible()
int Fluide_reel_base::is_incompressible () const inline override virtual
Reimplemented from Fluide_base.
References h_ref_, P_ref_, and T_ref_.
Referenced by calculate_fluid_properties_enthalpie_incompressible(), calculate_fluid_properties_incompressible(), check_unknown_range(), discretiser(), initialiser(), and mettre_a_jour().
abortTimeStep()
void Fluide_reel_base::abortTimeStep () override virtual
Reimplemented from Milieu_base.
References Champ_base::abortTimeStep(), Milieu_base::abortTimeStep(), Fluide_base::ch_e_int_, Fluide_base::ch_h_ou_T_, and Milieu_base::ch_rho_.
mettre_a_jour()
void Fluide_reel_base::mettre_a_jour (double temps) override virtual
Effectue une mise a jour en temps du milieu, et donc de ses parametres caracteristiques.
Les champs uniformes sont recalcules pour le nouveau temps specifie, les autres sont mis a par un appel a CLASSE_DU_CHAMP::mettre_a_jour(double temps).
Parameters
(double temps) le temps de mise a jour
Reimplemented from Fluide_base.
References calculate_fluid_properties(), calculate_fluid_properties_enthalpie(), calculate_fluid_properties_enthalpie_incompressible(), calculate_fluid_properties_incompressible(), Milieu_base::ch_alpha_, Milieu_base::ch_alpha_fois_rho_, Milieu_base::ch_beta_th_, Milieu_base::ch_Cp_, Fluide_base::ch_e_int_, Fluide_base::ch_h_ou_T_, Milieu_base::ch_lambda_, Fluide_base::ch_mu_, Fluide_base::ch_nu_, Milieu_base::ch_rho_, Milieu_base::ch_rho_Cp_comme_T_, TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Milieu_base::equation(), first_maj_, Equation_base::inconnue(), is_incompressible(), Milieu_base::masse_volumique(), Champ_Don_base::mettre_a_jour(), Champ_base::mettre_a_jour(), Objet_U_ptr::non_nul(), res_en_T_, Milieu_base::update_rho_cp(), TRUST_Deriv< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), Champ_Inc_base::valeurs(), and Champ_Proto::valeurs().
Referenced by initialiser(), and preparer_calcul().
preparer_calcul()
void Fluide_reel_base::preparer_calcul () override virtual
Reimplemented from Milieu_base.
References mettre_a_jour(), and t_init_.
set_param()
void Fluide_reel_base::set_param (Param & param) override virtual
Reimplemented from Fluide_base.
Reimplemented in Fluide_stiffened_gas, Fluide_generique_CoolProp, and Fluide_generique_EOS.
References Param::ajouter(), h_ref_, P_ref_, Milieu_base::set_additional_params(), and T_ref_.
Referenced by Fluide_stiffened_gas::set_param(), Fluide_generique_CoolProp::set_param(), and Fluide_generique_EOS::set_param().
discretiser()
void Fluide_reel_base::discretiser (const Probleme_base & pb, const Discretisation_base & dis) override virtual
Reimplemented from Fluide_base.
References _rho_(), _rho_h_(), Champs_compris_T< FIELD_TYPE >::ajoute_champ(), Milieu_base::ch_alpha_, Milieu_base::ch_alpha_fois_rho_, Milieu_base::ch_beta_th_, Milieu_base::ch_Cp_, Fluide_base::ch_e_int_, Fluide_base::ch_h_ou_T_, Milieu_base::ch_lambda_, Fluide_base::ch_mu_, Fluide_base::ch_nu_, Milieu_base::ch_rho_, Milieu_base::ch_rho_Cp_comme_T_, Milieu_base::ch_rho_Cp_elem_, Milieu_base::champs_compris_, Discretisation_base::discretiser_champ(), Milieu_base::discretiser_diametre_hydro(), Milieu_base::discretiser_porosite(), Equation_base::domaine_dis(), Probleme_base::equation(), Process::exit(), h_ref_, Milieu_base::id_composite_, Equation_base::inconnue(), is_incompressible(), Champ_Inc_base::nb_valeurs_temporelles(), Discretisation_base::nommer_completer_champ_physique(), P_ref_, res_en_T_, Probleme_base::schema_temps(), T_ref_, Schema_Temps_base::temps_courant(), and TRUST_Deriv< _CLASSE_ >::valeur().
creer_champs_non_lus()
void Fluide_reel_base::creer_champs_non_lus () inline override virtual
Reimplemented from Fluide_base.
unknown_range()
virtual std::map< std::string, std::array< double, 2 > > Fluide_reel_base::unknown_range () const inline virtual
Reimplemented in Fluide_eau_c3_gaz, Fluide_eau_c3_liquide, Fluide_R12_c1_gaz, Fluide_R12_c1_liquide, Fluide_sodium_gaz, Fluide_sodium_liquide, and Fluide_generique_TPPI_base.
Referenced by check_unknown_range(), and Fluide_generique_TPPI_base::unknown_range().
unknown_range_h()
virtual std::map< std::string, std::array< double, 2 > > Fluide_reel_base::unknown_range_h () const inline virtual
Reimplemented in Fluide_generique_TPPI_base.
Referenced by check_unknown_range(), and Fluide_generique_TPPI_base::unknown_range_h().
calculate_fluid_properties_incompressible()
void Fluide_reel_base::calculate_fluid_properties_incompressible () protected
References Milieu_base::equation(), Equation_base::inconnue(), is_incompressible(), and res_en_T_.
Referenced by mettre_a_jour().
calculate_fluid_properties()
void Fluide_reel_base::calculate_fluid_properties () protected
References Milieu_base::equation(), and Equation_base::inconnue().
Referenced by mettre_a_jour().
calculate_fluid_properties_enthalpie_incompressible()
void Fluide_reel_base::calculate_fluid_properties_enthalpie_incompressible () protected
References Fluide_base::ch_e_int_, Fluide_base::ch_h_ou_T_, Champ_Inc_base::derivees(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Milieu_base::equation(), Milieu_base::id_composite_, Equation_base::inconnue(), is_incompressible(), res_en_T_, TRUSTTab< _TYPE_, _SIZE_ >::resize(), Champ_Inc_base::val_bord(), TRUST_Deriv< _CLASSE_ >::valeur(), Champ_Inc_base::valeur_aux_bords(), and Champ_Inc_base::valeurs().
Referenced by mettre_a_jour().
calculate_fluid_properties_enthalpie()
void Fluide_reel_base::calculate_fluid_properties_enthalpie () protected
References Fluide_base::ch_e_int_, Fluide_base::ch_h_ou_T_, Milieu_base::ch_rho_, Champ_Inc_base::derivees(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Milieu_base::equation(), Process::exit(), TRUSTVect< _TYPE_, _SIZE_ >::get_span_tot(), Milieu_base::id_composite_, Equation_base::inconnue(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Champ_Inc_base::val_bord(), TRUST_Deriv< _CLASSE_ >::valeur(), Champ_Inc_base::valeur_aux_bords(), and Champ_Inc_base::valeurs().
Referenced by mettre_a_jour().
rho_()
virtual void Fluide_reel_base::rho_ (const SpanD T, const SpanD P, SpanD R, int ncomp = 1, int id = 0) const protected pure virtual
Implemented in Fluide_generique_TPPI_base, Fluide_eau_c3_gaz, Fluide_eau_c3_liquide, Fluide_R12_c1_gaz, Fluide_R12_c1_liquide, Fluide_sodium_gaz, Fluide_sodium_liquide, and Fluide_stiffened_gas.
dP_rho_()
virtual void Fluide_reel_base::dP_rho_ (const SpanD T, const SpanD P, SpanD dP_R, int ncomp = 1, int id = 0) const protected pure virtual
Implemented in Fluide_generique_TPPI_base, Fluide_eau_c3_gaz, Fluide_eau_c3_liquide, Fluide_R12_c1_gaz, Fluide_R12_c1_liquide, Fluide_sodium_gaz, Fluide_sodium_liquide, and Fluide_stiffened_gas.
dT_rho_()
virtual void Fluide_reel_base::dT_rho_ (const SpanD T, const SpanD P, SpanD dT_R, int ncomp = 1, int id = 0) const protected pure virtual
Implemented in Fluide_generique_TPPI_base, Fluide_eau_c3_gaz, Fluide_eau_c3_liquide, Fluide_R12_c1_gaz, Fluide_R12_c1_liquide, Fluide_sodium_gaz, Fluide_sodium_liquide, and Fluide_stiffened_gas.
h_()
virtual void Fluide_reel_base::h_ (const SpanD T, const SpanD P, SpanD H, int ncomp = 1, int id = 0) const protected pure virtual
Implemented in Fluide_generique_TPPI_base, Fluide_eau_c3_gaz, Fluide_eau_c3_liquide, Fluide_R12_c1_gaz, Fluide_R12_c1_liquide, Fluide_sodium_gaz, Fluide_sodium_liquide, and Fluide_stiffened_gas.
dP_h_()
virtual void Fluide_reel_base::dP_h_ (const SpanD T, const SpanD P, SpanD dP_H, int ncomp = 1, int id = 0) const protected pure virtual
Implemented in Fluide_generique_TPPI_base, Fluide_eau_c3_gaz, Fluide_eau_c3_liquide, Fluide_R12_c1_gaz, Fluide_R12_c1_liquide, Fluide_sodium_gaz, Fluide_sodium_liquide, and Fluide_stiffened_gas.
dT_h_()
virtual void Fluide_reel_base::dT_h_ (const SpanD T, const SpanD P, SpanD dT_H, int ncomp = 1, int id = 0) const protected pure virtual
Implemented in Fluide_generique_TPPI_base, Fluide_eau_c3_gaz, Fluide_eau_c3_liquide, Fluide_R12_c1_gaz, Fluide_R12_c1_liquide, Fluide_sodium_gaz, Fluide_sodium_liquide, and Fluide_stiffened_gas.
cp_()
virtual void Fluide_reel_base::cp_ (const SpanD T, const SpanD P, SpanD CP, int ncomp = 1, int id = 0) const protected pure virtual
Implemented in Fluide_generique_TPPI_base, Fluide_eau_c3_gaz, Fluide_eau_c3_liquide, Fluide_R12_c1_gaz, Fluide_R12_c1_liquide, Fluide_sodium_gaz, Fluide_sodium_liquide, and Fluide_stiffened_gas.
beta_()
virtual void Fluide_reel_base::beta_ (const SpanD T, const SpanD P, SpanD B, int ncomp = 1, int id = 0) const protected pure virtual
Implemented in Fluide_generique_TPPI_base, Fluide_eau_c3_gaz, Fluide_eau_c3_liquide, Fluide_R12_c1_gaz, Fluide_R12_c1_liquide, Fluide_sodium_gaz, Fluide_sodium_liquide, and Fluide_stiffened_gas.
mu_()
virtual void Fluide_reel_base::mu_ (const SpanD T, const SpanD P, SpanD M, int ncomp = 1, int id = 0) const protected pure virtual
Implemented in Fluide_generique_TPPI_base, Fluide_eau_c3_gaz, Fluide_eau_c3_liquide, Fluide_R12_c1_gaz, Fluide_R12_c1_liquide, Fluide_sodium_gaz, Fluide_sodium_liquide, and Fluide_stiffened_gas.
lambda_()
virtual void Fluide_reel_base::lambda_ (const SpanD T, const SpanD P, SpanD L, int ncomp = 1, int id = 0) const protected pure virtual
Implemented in Fluide_generique_TPPI_base, Fluide_eau_c3_gaz, Fluide_eau_c3_liquide, Fluide_R12_c1_gaz, Fluide_R12_c1_liquide, Fluide_sodium_gaz, Fluide_sodium_liquide, and Fluide_stiffened_gas.
compute_CPMLB_pb_multiphase_()
void Fluide_reel_base::compute_CPMLB_pb_multiphase_ (const MSpanD input, MLoiSpanD prop, int ncomp = 1, int id = 0) const protected virtual
Reimplemented in Fluide_generique_TPPI_base.
compute_all_pb_multiphase_()
void Fluide_reel_base::compute_all_pb_multiphase_ (const MSpanD input, MLoiSpanD inter, MLoiSpanD bord, int ncomp = 1, int id = 0) const protected virtual
Reimplemented in Fluide_generique_TPPI_base.
_rho_()
double Fluide_reel_base::_rho_ (const double T, const double P) const inline protected
Referenced by discretiser().
_dP_rho_()
double Fluide_reel_base::_dP_rho_ (const double T, const double P) const inline protected
_dT_rho_()
double Fluide_reel_base::_dT_rho_ (const double T, const double P) const inline protected
_h_()
double Fluide_reel_base::_h_ (const double T, const double P) const inline protected
_dP_h_()
double Fluide_reel_base::_dP_h_ (const double T, const double P) const inline protected
_dT_h_()
double Fluide_reel_base::_dT_h_ (const double T, const double P) const inline protected
_cp_()
double Fluide_reel_base::_cp_ (const double T, const double P) const inline protected
_beta_()
double Fluide_reel_base::_beta_ (const double T, const double P) const inline protected
_mu_()
double Fluide_reel_base::_mu_ (const double T, const double P) const inline protected
_lambda_()
double Fluide_reel_base::_lambda_ (const double T, const double P) const inline protected
rho_h_()
virtual void Fluide_reel_base::rho_h_ (const SpanD h, const SpanD P, SpanD R, int ncomp = 1, int id = 0) const protected pure virtual
Implemented in Fluide_generique_TPPI_base, Fluide_stiffened_gas, Fluide_eau_c3_gaz, Fluide_eau_c3_liquide, Fluide_R12_c1_gaz, Fluide_R12_c1_liquide, Fluide_sodium_gaz, and Fluide_sodium_liquide.
dP_rho_h_()
virtual void Fluide_reel_base::dP_rho_h_ (const SpanD h, const SpanD P, SpanD dP_R, int ncomp = 1, int id = 0) const protected pure virtual
Implemented in Fluide_generique_TPPI_base, Fluide_stiffened_gas, Fluide_eau_c3_gaz, Fluide_eau_c3_liquide, Fluide_R12_c1_gaz, Fluide_R12_c1_liquide, Fluide_sodium_gaz, and Fluide_sodium_liquide.
dh_rho_h_()
virtual void Fluide_reel_base::dh_rho_h_ (const SpanD h, const SpanD P, SpanD dT_R, int ncomp = 1, int id = 0) const protected pure virtual
Implemented in Fluide_generique_TPPI_base, Fluide_stiffened_gas, Fluide_eau_c3_gaz, Fluide_eau_c3_liquide, Fluide_R12_c1_gaz, Fluide_R12_c1_liquide, Fluide_sodium_gaz, and Fluide_sodium_liquide.
T_()
virtual void Fluide_reel_base::T_ (const SpanD h, const SpanD P, SpanD H, int ncomp = 1, int id = 0) const protected pure virtual
Implemented in Fluide_stiffened_gas, Fluide_generique_TPPI_base, Fluide_eau_c3_gaz, Fluide_eau_c3_liquide, Fluide_R12_c1_gaz, Fluide_R12_c1_liquide, Fluide_sodium_gaz, and Fluide_sodium_liquide.
dP_T_()
virtual void Fluide_reel_base::dP_T_ (const SpanD h, const SpanD P, SpanD dP_H, int ncomp = 1, int id = 0) const protected pure virtual
Implemented in Fluide_generique_TPPI_base, Fluide_stiffened_gas, Fluide_eau_c3_gaz, Fluide_eau_c3_liquide, Fluide_R12_c1_gaz, Fluide_R12_c1_liquide, Fluide_sodium_gaz, and Fluide_sodium_liquide.
dh_T_()
virtual void Fluide_reel_base::dh_T_ (const SpanD h, const SpanD P, SpanD dT_H, int ncomp = 1, int id = 0) const protected pure virtual
Implemented in Fluide_generique_TPPI_base, Fluide_stiffened_gas, Fluide_eau_c3_gaz, Fluide_eau_c3_liquide, Fluide_R12_c1_gaz, Fluide_R12_c1_liquide, Fluide_sodium_gaz, and Fluide_sodium_liquide.
cp_h_()
virtual void Fluide_reel_base::cp_h_ (const SpanD h, const SpanD P, SpanD CP, int ncomp = 1, int id = 0) const protected pure virtual
Implemented in Fluide_generique_TPPI_base, Fluide_stiffened_gas, Fluide_eau_c3_gaz, Fluide_eau_c3_liquide, Fluide_R12_c1_gaz, Fluide_R12_c1_liquide, Fluide_sodium_gaz, and Fluide_sodium_liquide.
beta_h_()
virtual void Fluide_reel_base::beta_h_ (const SpanD h, const SpanD P, SpanD B, int ncomp = 1, int id = 0) const protected pure virtual
Implemented in Fluide_generique_TPPI_base, Fluide_stiffened_gas, Fluide_eau_c3_gaz, Fluide_eau_c3_liquide, Fluide_R12_c1_gaz, Fluide_R12_c1_liquide, Fluide_sodium_gaz, and Fluide_sodium_liquide.
mu_h_()
virtual void Fluide_reel_base::mu_h_ (const SpanD h, const SpanD P, SpanD M, int ncomp = 1, int id = 0) const protected pure virtual
Implemented in Fluide_generique_TPPI_base, Fluide_stiffened_gas, Fluide_eau_c3_gaz, Fluide_eau_c3_liquide, Fluide_R12_c1_gaz, Fluide_R12_c1_liquide, Fluide_sodium_gaz, and Fluide_sodium_liquide.
lambda_h_()
virtual void Fluide_reel_base::lambda_h_ (const SpanD h, const SpanD P, SpanD L, int ncomp = 1, int id = 0) const protected pure virtual
Implemented in Fluide_generique_TPPI_base, Fluide_stiffened_gas, Fluide_eau_c3_gaz, Fluide_eau_c3_liquide, Fluide_R12_c1_gaz, Fluide_R12_c1_liquide, Fluide_sodium_gaz, and Fluide_sodium_liquide.
compute_CPMLB_pb_multiphase_h_()
void Fluide_reel_base::compute_CPMLB_pb_multiphase_h_ (const MSpanD input, MLoiSpanD_h prop, int ncomp = 1, int id = 0) const protected virtual
Reimplemented in Fluide_generique_TPPI_base.
compute_all_pb_multiphase_h_()
void Fluide_reel_base::compute_all_pb_multiphase_h_ (const MSpanD input, MLoiSpanD_h inter, MLoiSpanD_h bord, int ncomp = 1, int id = 0) const protected virtual
Reimplemented in Fluide_generique_TPPI_base.
_rho_h_() [1/2]
double Fluide_reel_base::_rho_h_ (const double h, const double P) const inline protected
Referenced by discretiser().
_dP_rho_h_() [1/2]
double Fluide_reel_base::_dP_rho_h_ (const double h, const double P) const inline protected
_dh_rho_h_() [1/2]
double Fluide_reel_base::_dh_rho_h_ (const double h, const double P) const inline protected
_T_() [1/2]
double Fluide_reel_base::_T_ (const double h, const double P) const inline protected
_dP_T_() [1/2]
double Fluide_reel_base::_dP_T_ (const double h, const double P) const inline protected
_dh_T_() [1/2]
double Fluide_reel_base::_dh_T_ (const double h, const double P) const inline protected
_cp_h_() [1/2]
double Fluide_reel_base::_cp_h_ (const double h, const double P) const inline protected
_beta_h_() [1/2]
double Fluide_reel_base::_beta_h_ (const double h, const double P) const inline protected
_mu_h_() [1/2]
double Fluide_reel_base::_mu_h_ (const double h, const double P) const inline protected
_lambda_h_() [1/2]
double Fluide_reel_base::_lambda_h_ (const double h, const double P) const inline protected
_rho_h_() [2/2]
void Fluide_reel_base::_rho_h_ (const double h, const double P, SpanD res) const inline
_dP_rho_h_() [2/2]
void Fluide_reel_base::_dP_rho_h_ (const double h, const double P, SpanD res) const inline
_dh_rho_h_() [2/2]
void Fluide_reel_base::_dh_rho_h_ (const double h, const double P, SpanD res) const inline
_T_() [2/2]
void Fluide_reel_base::_T_ (const double h, const double P, SpanD res) const inline
_dP_T_() [2/2]
void Fluide_reel_base::_dP_T_ (const double h, const double P, SpanD res) const inline
_dh_T_() [2/2]
void Fluide_reel_base::_dh_T_ (const double h, const double P, SpanD res) const inline
_cp_h_() [2/2]
void Fluide_reel_base::_cp_h_ (const double h, const double P, SpanD res) const inline
_beta_h_() [2/2]
void Fluide_reel_base::_beta_h_ (const double h, const double P, SpanD res) const inline
_mu_h_() [2/2]
void Fluide_reel_base::_mu_h_ (const double h, const double P, SpanD res) const inline
_lambda_h_() [2/2]
void Fluide_reel_base::_lambda_h_ (const double h, const double P, SpanD res) const inline
_compute_CPMLB_pb_multiphase_h_()
void Fluide_reel_base::_compute_CPMLB_pb_multiphase_h_ (MLoiSpanD_h prop) const
_compute_all_pb_multiphase_h_()
void Fluide_reel_base::_compute_all_pb_multiphase_h_ (MLoiSpanD_h inter, MLoiSpanD_h bord) const
Member Data Documentation
info_obj
const Type_info Fluide_reel_base::info_obj static
T_ref_
double Fluide_reel_base::T_ref_ = -1. protected
Referenced by discretiser(), initialiser(), is_incompressible(), readOn(), and set_param().
P_ref_
double Fluide_reel_base::P_ref_ = -1. protected
Referenced by discretiser(), initialiser(), is_incompressible(), readOn(), and set_param().
h_ref_
double Fluide_reel_base::h_ref_ = -1. protected
Referenced by discretiser(), is_incompressible(), readOn(), and set_param().
t_init_
double Fluide_reel_base::t_init_ = -1. protected
Referenced by initialiser(), and preparer_calcul().
first_maj_
int Fluide_reel_base::first_maj_ = 1 protected
Referenced by mettre_a_jour().
res_en_T_
bool Fluide_reel_base::res_en_T_ = true protected
Referenced by calculate_fluid_properties_enthalpie_incompressible(), calculate_fluid_properties_incompressible(), check_unknown_range(), discretiser(), initialiser(), mettre_a_jour(), and Fluide_generique_CoolProp::readOn().
converter_H_to_T_
H_to_T Fluide_reel_base::converter_H_to_T_
Referenced by Fluide_reel_base().
converter_T_to_H_
T_to_H Fluide_reel_base::converter_T_to_H_
Referenced by Fluide_reel_base().