TrioCFD: Source_Transport_K_Eps_VDF_Elem Class Reference
Source_Transport_K_Eps_VDF_Elem Class Reference
#include <Source_Transport_K_Eps_VDF_Elem.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Source_Transport_VDF_Elem_base
const Type_info * get_info () const override
void mettre_a_jour (double t) override
Public Member Functions inherited from Source_base
virtual int a_pour_Champ_Fonc (const Motcle &mot, TRUST_Ref< Champ_base * > &ch_ref) const
virtual void associer_champ_rho (const Champ_base &champ_rho)
virtual void completer ()
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
virtual void resetTime (double t)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
de Navier-Stokes ne sont pas couplees a la thermique ou a l'equation de convection-diffusion d'une concentration.
Constructor & Destructor Documentation
~Source_Transport_K_Eps_VDF_Elem()
Source_Transport_K_Eps_VDF_Elem::~Source_Transport_K_Eps_VDF_Elem ()
Source_Transport_K_Eps_VDF_Elem()
Source_Transport_K_Eps_VDF_Elem::Source_Transport_K_Eps_VDF_Elem (double cte1 = C1__, double cte2 = C2__) inline
Member Function Documentation
cree_instance()
Objet_U * Source_Transport_K_Eps_VDF_Elem::cree_instance () static
taille_memoire()
unsigned Source_Transport_K_Eps_VDF_Elem::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Source_Transport_K_Eps_VDF_Elem::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Source_Transport_K_Eps_VDF_Elem::info () static
get_info()
const Type_info * Source_Transport_K_Eps_VDF_Elem::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Source_Transport_VDF_Elem_base.
self_cast() [1/2]
Source_Transport_K_Eps_VDF_Elem & Source_Transport_K_Eps_VDF_Elem::self_cast (Objet_U & r) static
self_cast() [2/2]
const Source_Transport_K_Eps_VDF_Elem & Source_Transport_K_Eps_VDF_Elem::self_cast (const Objet_U & r) static
printOn()
Sortie & Source_Transport_K_Eps_VDF_Elem::printOn (Sortie & os) const override protected virtual
DOES NOTHING - to override in derived classes.
Imprime la source sur un flot de sortie.
Parameters
(Sortie& os) le flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Source_Transport_VDF_Elem_base.
References Objet_U::que_suis_je().
readOn()
Entree & Source_Transport_K_Eps_VDF_Elem::readOn (Entree & is) override protected virtual
DOES NOTHING - to override in derived classes.
Lecture d'un terme source sur un flot d'entree.
Parameters
(Entree& is) le flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Source_Transport_VDF_Elem_base.
References MorEqn::mon_equation, Objet_U::que_suis_je(), Source_Transport_VDF_Elem_base::readOn(), and Source_Transport_proto::verifier_pb_keps().
ajouter_blocs()
void Source_Transport_K_Eps_VDF_Elem::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl) const override virtual
Implements Source_Transport_VDF_Elem_base.
References Source_Transport_VDF_Elem_base::ajouter_keps(), Source_Transport_proto::C2, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), MorEqn::equation(), Nom::getString(), Equation_base::inconnue(), Source_Transport_VDF_Elem_base::le_dom_Cl_VDF, Source_Transport_VDF_Elem_base::le_dom_VDF, Field_base::le_nom(), mon_eq_transport_K_Eps, TRUSTTab< _TYPE_, _SIZE_ >::resize(), and Champ_Inc_base::valeurs().
Referenced by Source_Transport_K_Eps_aniso_therm_concen_VDF_Elem::ajouter_blocs(), Source_Transport_K_Eps_anisotherme_VDF_Elem::ajouter_blocs(), and Source_Transport_K_Eps_concen_VDF_Elem::ajouter_blocs().
associer_pb()
void Source_Transport_K_Eps_VDF_Elem::associer_pb (const Probleme_base & pb) override protected virtual
Reimplemented from Source_Transport_VDF_Elem_base.
References Source_Transport_VDF_Elem_base::associer_pb(), MorEqn::equation(), and mon_eq_transport_K_Eps.
Referenced by Source_Transport_K_Eps_aniso_therm_concen_VDF_Elem::associer_pb(), Source_Transport_K_Eps_anisotherme_VDF_Elem::associer_pb(), and Source_Transport_K_Eps_concen_VDF_Elem::associer_pb().
Member Data Documentation
info_obj
const Type_info Source_Transport_K_Eps_VDF_Elem::info_obj static
mon_eq_transport_K_Eps
TRUST_Ref< Transport_K_Eps *> Source_Transport_K_Eps_VDF_Elem::mon_eq_transport_K_Eps protected
Referenced by ajouter_blocs(), and associer_pb().