TrioCFD: IJK_Thermal_cut_cell Class Reference
IJK_Thermal_cut_cell Class Reference
#include <IJK_Thermal_cut_cell.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Public Types inherited from Champs_compris_IJK_interface
using FieldInfo_t = std::tuple< Motcle, Entity, Nature_du_champ, bool >
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
IJK_Thermal_cut_cell()
IJK_Thermal_cut_cell::IJK_Thermal_cut_cell ()
References IJK_Thermal_base::conserv_energy_global_, cut_cell_conv_scheme_, IJK_Thermal_base::needs_op_unform_, and Cut_cell_conv_scheme::scheme.
~IJK_Thermal_cut_cell()
IJK_Thermal_cut_cell::~IJK_Thermal_cut_cell ()
Member Function Documentation
cree_instance()
Objet_U * IJK_Thermal_cut_cell::cree_instance () static
taille_memoire()
unsigned IJK_Thermal_cut_cell::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int IJK_Thermal_cut_cell::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * IJK_Thermal_cut_cell::info () static
get_info()
const Type_info * IJK_Thermal_cut_cell::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from IJK_Thermal_base.
self_cast() [1/2]
IJK_Thermal_cut_cell & IJK_Thermal_cut_cell::self_cast (Objet_U & r) static
self_cast() [2/2]
const IJK_Thermal_cut_cell & IJK_Thermal_cut_cell::self_cast (const Objet_U & r) static
printOn()
Sortie & IJK_Thermal_cut_cell::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from IJK_Thermal_base.
References IJK_Thermal_base::conserv_energy_global_, convective_correction_, diffusive_correction_, IJK_Thermal_base::lambda_variable_, IJK_Thermal_base::printOn(), and IJK_Thermal_base::type_T_source_.
readOn()
Entree & IJK_Thermal_cut_cell::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from IJK_Thermal_base.
References IJK_Thermal_base::readOn().
initialize()
void IJK_Thermal_cut_cell::initialize (const Domaine_IJK & splitting, const int idx) override virtual
Reimplemented from IJK_Thermal_base.
References IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::allocate(), Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::allocate_ephemere(), Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::allocate_persistant(), Cut_cell_diffusion_auxiliaire::associer(), TRUSTTabFT_cut_cell_scalar< _TYPE_ >::associer_ephemere(), cellule_rk_restreint_conv_, cellule_rk_restreint_diff_, compute_temperature_init(), IJK_Thermal_base::conserv_energy_global_, convective_correction_, current_fluxes_conv_, current_fluxes_diff_, cut_cell_flux_convection_, cut_cell_flux_diffusion_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::data(), diffusive_correction_, div_rho_cp_T_, Domaine_IJK::ELEM, Process::exit(), IJK_Thermal_base::expression_T_init_, IJK_Thermal_base::fichier_reprise_temperature_, flux_interface_efficace_scalar_, flux_interface_ft_scalar_next_, flux_interface_ft_scalar_old_, flux_interface_ns_scalar_next_, flux_interface_ns_scalar_old_, IJK_Thermal_base::ghost_cells_, Cut_cell_schema_auxiliaire::initialise(), Operateur_IJK_elem_conv::initialize(), Operateur_IJK_elem_diff::initialize(), IJK_Thermal_base::initialize(), lambda_, IJK_Thermal_base::lambda_liquid_, IJK_Thermal_base::lambda_vapour_, Objet_U_ptr::non_nul(), postraiter_champs_intermediaires_, Objet_U::que_suis_je(), IJK_Thermal_base::ref_ijk_ft_, ref_ijk_ft_cut_cell_, IJK_Thermal_base::rho_cp_, IJK_Thermal_base::rho_cp_post_, IJK_Thermal_base::rho_cp_T_, RK3_F_fluxes_conv_, RK3_F_fluxes_diff_, runge_kutta_fluxes_convection_, runge_kutta_fluxes_diffusion_, IJK_Thermal_base::temperature_convection_op_, IJK_Thermal_base::temperature_diffusion_op_, IJK_Thermal_base::temperature_ft_, temperature_post_convection_, temperature_post_diff_regular_, temperature_post_dying_, temperature_post_regular_, IJK_Thermal_base::type_temperature_convection_form_, Objet_U_ptr::typer(), and TRUST_Ref< _CLASSE_ >::valeur().
compute_timestep()
double IJK_Thermal_cut_cell::compute_timestep (const double timestep, const double rho_l, const double rho_v, const double dxmin)
update_thermal_properties()
void IJK_Thermal_cut_cell::update_thermal_properties () override virtual
Reimplemented from IJK_Thermal_base.
References IJK_Thermal_base::cp_liquid_, IJK_Thermal_base::cp_vapour_, IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost(), lambda_, IJK_Thermal_base::lambda_liquid_, IJK_Thermal_base::lambda_vapour_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), ref_ijk_ft_cut_cell_, and IJK_Thermal_base::rho_cp_.
Referenced by perform_thermal_step().
set_param()
void IJK_Thermal_cut_cell::set_param (Param & param) override virtual
Reimplemented from IJK_Thermal_base.
References Param::ajouter(), Param::ajouter_flag(), convective_correction_, cut_cell_conv_scheme_, deactivate_diffusion_interface_, Param::dictionnaire(), diffusive_correction_, postraiter_champs_intermediaires_, Param::REQUIRED, runge_kutta_fluxes_convection_, runge_kutta_fluxes_diffusion_, runge_kutta_fluxes_pas_de_correction_convection_, runge_kutta_fluxes_pas_de_correction_diffusion_, runge_kutta_restriction_leniency_convection_, runge_kutta_restriction_leniency_diffusion_, Cut_cell_conv_scheme::scheme, and IJK_Thermal_base::set_param().
compute_temperature_init()
void IJK_Thermal_cut_cell::compute_temperature_init () override virtual
Reimplemented from IJK_Thermal_base.
References IJK_Thermal_base::compute_temperature_init(), IJK_Thermal_base::expression_T_init_, Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::get_cut_cell_disc(), Cut_cell_FT_Disc::get_n_tot(), IJK_Thermal_base::ref_ijk_ft_, and Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::set_field_data().
Referenced by initialize().
recompute_temperature_init()
void IJK_Thermal_cut_cell::recompute_temperature_init () override virtual
Reimplemented from IJK_Thermal_base.
References IJK_Thermal_base::expression_T_init_, Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::get_cut_cell_disc(), Cut_cell_FT_Disc::get_n_tot(), IJK_Thermal_base::recompute_temperature_init(), IJK_Thermal_base::ref_ijk_ft_, and Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::set_field_data().
perform_thermal_step()
void IJK_Thermal_cut_cell::perform_thermal_step (double total_timestep, int flag_rk, int rk_step)
References Cut_cell_schema_auxiliaire::add_dying_cells(), Cut_cell_schema_auxiliaire::add_small_nascent_cells(), add_temperature_diffusion(), Cut_cell_schema_auxiliaire::calcule_valeur_remplissage(), cellule_rk_restreint_conv_, cellule_rk_restreint_diff_, Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::compute_d_global_energy_cut_cell(), Cut_cell_schema_auxiliaire::compute_flux_dying_cells(), Cut_cell_schema_auxiliaire::compute_flux_small_nascent_cells(), Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::compute_global_energy_cut_cell(), compute_temperature_convection_cut_cell(), IJK_Thermal_base::conv_temperature_negligible_, convective_correction_, Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::copy_from(), current_fluxes_conv_, current_fluxes_diff_, cut_cell_conv_scheme_, cut_cell_flux_convection_, cut_cell_flux_diffusion_, Cut_cell_diffusion_auxiliaire::deactivate_correction_petites_cellules_diffusion_, deactivate_diffusion_interface_, IJK_Thermal_base::debug_, IJK_Thermal_base::diff_temperature_negligible_, diffusive_correction_, CutCell_GlobalInfo::diph_dying, CutCell_GlobalInfo::diph_l, CutCell_GlobalInfo::diph_nascent, CutCell_GlobalInfo::diph_regular, CutCell_GlobalInfo::diph_small, CutCell_GlobalInfo::diph_v, Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::echange_diph_vers_pure_cellules_finalement_pures(), Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel(), Cut_field_vector< T, N >::echange_espace_virtuel(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel(), flux_interface_efficace_scalar_, flux_interface_ft_scalar_next_, flux_interface_ft_scalar_old_, flux_interface_ns_scalar_next_, flux_interface_ns_scalar_old_, Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::get_cut_cell_disc(), IJK_Thermal_base::get_rhocp_l(), IJK_Thermal_base::get_rhocp_v(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost(), interfacial_phin_ai_, interfacial_temperature_, IJK_Thermal_base::lambda_liquid_, IJK_Thermal_base::lambda_vapour_, methode_flux_interface_, Objet_U_ptr::non_nul(), CutCell_GlobalInfo::overall, CutCell_GlobalInfo::overall_l, CutCell_GlobalInfo::overall_v, postraiter_champs_intermediaires_, print_Tmin_Tmax_cut_cell(), CutCell_GlobalInfo::pure, IJK_Thermal_base::ref_ijk_ft_, ref_ijk_ft_cut_cell_, Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::remplir_tableau_pure_cellules_diphasiques(), RK3_F_fluxes_conv_, RK3_F_fluxes_diff_, runge_kutta_fluxes_convection_, runge_kutta_fluxes_diffusion_, runge_kutta_fluxes_pas_de_correction_convection_, runge_kutta_fluxes_pas_de_correction_diffusion_, runge_kutta_restriction_leniency_convection_, runge_kutta_restriction_leniency_diffusion_, Cut_field_vector< T, N >::set_to_uniform_value(), IJK_Thermal_base::temperature_, IJK_Thermal_base::temperature_convection_op_, IJK_Thermal_base::temperature_diffusion_op_, IJK_Thermal_base::temperature_ft_, temperature_post_convection_, temperature_post_diff_regular_, temperature_post_dying_, temperature_post_regular_, update_thermal_properties(), TRUST_Deriv< _CLASSE_ >::valeur(), and verbosite_.
Referenced by euler_time_step(), and rk3_sub_step().
euler_time_step()
void IJK_Thermal_cut_cell::euler_time_step (const double timestep) override virtual
Reimplemented from IJK_Thermal_base.
References perform_thermal_step().
rk3_sub_step()
void IJK_Thermal_cut_cell::rk3_sub_step (const int rk_step, const double total_timestep, const double time) override virtual
Reimplemented from IJK_Thermal_base.
References IJK_Thermal_base::debug_, perform_thermal_step(), print_Tmin_Tmax_cut_cell(), and verbosite_.
sauvegarder_temperature()
void IJK_Thermal_cut_cell::sauvegarder_temperature (Nom & lata_name, int idx, const int & stop = 0) override virtual
Reimplemented from IJK_Thermal_base.
References IJK_Thermal_base::fichier_reprise_temperature_, IJK_Thermal_base::latastep_reprise_, IJK_Thermal_base::latastep_reprise_ini_, IJK_Thermal_base::ref_ijk_ft_, IJK_Thermal_base::temperature_, and IJK_Thermal_base::timestep_reprise_temperature_.
compute_global_energy()
double IJK_Thermal_cut_cell::compute_global_energy () inline override virtual
Reimplemented from IJK_Thermal_base.
References Process::exit().
print_Tmin_Tmax_cut_cell()
void IJK_Thermal_cut_cell::print_Tmin_Tmax_cut_cell (const Cut_field_double & cut_field_temperature, bool next, double current_time, const std::string & heading)
References Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::compute_max_cut_cell(), Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::compute_min_cut_cell(), CutCell_GlobalInfo::diph_dying, CutCell_GlobalInfo::diph_l, CutCell_GlobalInfo::diph_nascent, CutCell_GlobalInfo::diph_regular, CutCell_GlobalInfo::diph_small, CutCell_GlobalInfo::diph_v, Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::get_value_location(), CutCell_GlobalInfo::overall, CutCell_GlobalInfo::overall_l, CutCell_GlobalInfo::overall_v, CutCell_GlobalInfo::pure, and verbosite_.
Referenced by perform_thermal_step(), and rk3_sub_step().
calculer_flux_interface()
void IJK_Thermal_cut_cell::calculer_flux_interface ()
copie_pure_vers_diph_sans_interpolation()
void IJK_Thermal_cut_cell::copie_pure_vers_diph_sans_interpolation () inline override virtual
Reimplemented from IJK_Thermal_base.
References cellule_rk_restreint_conv_, cellule_rk_restreint_diff_, Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::copie_pure_vers_diph_sans_interpolation(), RK3_F_fluxes_conv_, RK3_F_fluxes_diff_, runge_kutta_fluxes_convection_, and runge_kutta_fluxes_diffusion_.
echange_pure_vers_diph_cellules_initialement_pures()
void IJK_Thermal_cut_cell::echange_pure_vers_diph_cellules_initialement_pures () inline override virtual
Reimplemented from IJK_Thermal_base.
References cellule_rk_restreint_conv_, cellule_rk_restreint_diff_, Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::echange_pure_vers_diph_cellules_initialement_pures(), Cut_field_vector< T, N >::echange_pure_vers_diph_cellules_initialement_pures(), RK3_F_fluxes_conv_, RK3_F_fluxes_diff_, runge_kutta_fluxes_convection_, and runge_kutta_fluxes_diffusion_.
echange_diph_vers_pure_cellules_finalement_pures()
void IJK_Thermal_cut_cell::echange_diph_vers_pure_cellules_finalement_pures () inline override virtual
Reimplemented from IJK_Thermal_base.
References cellule_rk_restreint_conv_, cellule_rk_restreint_diff_, Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::echange_diph_vers_pure_cellules_finalement_pures(), Cut_field_vector< T, N >::echange_diph_vers_pure_cellules_finalement_pures(), RK3_F_fluxes_conv_, RK3_F_fluxes_diff_, runge_kutta_fluxes_convection_, and runge_kutta_fluxes_diffusion_.
vide_phase_invalide_cellules_diphasiques()
void IJK_Thermal_cut_cell::vide_phase_invalide_cellules_diphasiques () inline override virtual
Reimplemented from IJK_Thermal_base.
References cellule_rk_restreint_conv_, cellule_rk_restreint_diff_, RK3_F_fluxes_conv_, RK3_F_fluxes_diff_, runge_kutta_fluxes_convection_, runge_kutta_fluxes_diffusion_, Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::vide_phase_invalide_cellules_diphasiques(), and Cut_field_vector< T, N >::vide_phase_invalide_cellules_diphasiques().
remplir_tableau_pure_cellules_diphasiques()
void IJK_Thermal_cut_cell::remplir_tableau_pure_cellules_diphasiques (bool next_time) inline override virtual
Reimplemented from IJK_Thermal_base.
References cellule_rk_restreint_conv_, cellule_rk_restreint_diff_, Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::remplir_tableau_pure_cellules_diphasiques(), Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::remplir_tableau_pure_cellules_diphasiques_max(), RK3_F_fluxes_conv_, RK3_F_fluxes_diff_, runge_kutta_fluxes_convection_, and runge_kutta_fluxes_diffusion_.
lire_temperature()
void IJK_Thermal_cut_cell::lire_temperature (const Domaine_IJK & splitting) override protected virtual
Reimplemented from IJK_Thermal_base.
References IJK_Thermal_base::fichier_reprise_temperature_, Domaine_base::le_nom(), IJK_Thermal_base::rang_, IJK_Thermal_base::rank_reprise_temperature_, IJK_Thermal_base::temperature_, and IJK_Thermal_base::timestep_reprise_temperature_.
compute_interfacial_temperature2()
void IJK_Thermal_cut_cell::compute_interfacial_temperature2 (ArrOfDouble & interfacial_temperature, ArrOfDouble & flux_normal_interp) override protected virtual
Reimplemented from IJK_Thermal_base.
References deactivate_diffusion_interface_, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Process::exit(), interfacial_phin_ai_, interfacial_temperature_, IJK_Thermal_base::ref_ijk_ft_, TRUSTTab< _TYPE_, _SIZE_ >::resize(), and TRUSTArray< _TYPE_, _SIZE_ >::resize_array().
compute_temperature_convection_cut_cell()
void IJK_Thermal_cut_cell::compute_temperature_convection_cut_cell (const Cut_field_vector3_double & cut_field_total_velocity, Cut_field_double & cut_field_d_temperature) protected
References Statistiques::begin_count(), IJK_Thermal_base::conv_temperature_negligible_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::data(), Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::divide_by_scalar(), Statistiques::end_count(), Statistiques::new_counter(), Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::set_to_uniform_value(), IJK_Thermal_base::temperature_convection_op_, IJK_Thermal_base::u_T_convective_volume_, DebogIJK::verifier(), and IJK_Thermal_base::vol_.
Referenced by perform_thermal_step().
add_temperature_diffusion()
void IJK_Thermal_cut_cell::add_temperature_diffusion () override protected virtual
Reimplemented from IJK_Thermal_base.
References Statistiques::begin_count(), IJK_Thermal_base::boundary_conditions_, IJK_Thermal_base::boundary_flux_kmax_, IJK_Thermal_base::boundary_flux_kmin_, IJK_Thermal_base::calculer_flux_thermique_bord(), Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::copy_from(), IJK_Thermal_base::cp_liquid_, IJK_Thermal_base::cp_vapour_, IJK_Thermal_base::diff_temperature_negligible_, IJK_Thermal_base::div_coeff_grad_T_volume_, Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::divide_by_scalar(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel(), Statistiques::end_count(), flux_interface_efficace_scalar_, Boundary_Conditions_Thermique::get_bctype_k_max(), Boundary_Conditions_Thermique::get_bctype_k_min(), Boundary_Conditions_Thermique::get_flux_kmax(), Boundary_Conditions_Thermique::get_flux_kmin(), Boundary_Conditions_Thermique::get_temperature_kmax(), Boundary_Conditions_Thermique::get_temperature_kmin(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost(), IJK_Thermal_base::imposer_flux_thermique_bord(), lambda_, IJK_Thermal_base::lambda_liquid_, Statistiques::new_counter(), Boundary_Conditions_Thermique::Paroi_Flux_impose, Boundary_Conditions_Thermique::Paroi_Temperature_imposee, ref_ijk_ft_cut_cell_, Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::set_to_uniform_value(), IJK_Thermal_base::temperature_, IJK_Thermal_base::temperature_diffusion_op_, DebogIJK::verifier(), and IJK_Thermal_base::vol_.
Referenced by perform_thermal_step().
compute_diffusion_increment()
void IJK_Thermal_cut_cell::compute_diffusion_increment () inline override protected virtual
Implements IJK_Thermal_base.
correct_temperature_for_eulerian_fluxes()
void IJK_Thermal_cut_cell::correct_temperature_for_eulerian_fluxes () inline override protected virtual
Implements IJK_Thermal_base.
Friends And Related Function Documentation
Postprocessing_IJK
friend class Postprocessing_IJK friend
Member Data Documentation
info_obj
const Type_info IJK_Thermal_cut_cell::info_obj static
ref_ijk_ft_cut_cell_
TRUST_Ref< Probleme_FTD_IJK_cut_cell *> IJK_Thermal_cut_cell::ref_ijk_ft_cut_cell_ protected
Referenced by add_temperature_diffusion(), initialize(), perform_thermal_step(), and update_thermal_properties().
div_rho_cp_T_
IJK_Field_double IJK_Thermal_cut_cell::div_rho_cp_T_ protected
Referenced by initialize().
lambda_
IJK_Field_double IJK_Thermal_cut_cell::lambda_ protected
Referenced by add_temperature_diffusion(), initialize(), and update_thermal_properties().
cut_cell_flux_diffusion_
FixedVector<Cut_cell_double, 3> IJK_Thermal_cut_cell::cut_cell_flux_diffusion_ protected
Referenced by initialize(), and perform_thermal_step().
cut_cell_flux_convection_
FixedVector<Cut_cell_double, 3> IJK_Thermal_cut_cell::cut_cell_flux_convection_ protected
Referenced by initialize(), and perform_thermal_step().
cut_cell_conv_scheme_
Cut_cell_conv_scheme IJK_Thermal_cut_cell::cut_cell_conv_scheme_ protected
Referenced by IJK_Thermal_cut_cell(), perform_thermal_step(), and set_param().
methode_flux_interface_
METHODE_FLUX_INTERFACE IJK_Thermal_cut_cell::methode_flux_interface_ = METHODE_FLUX_INTERFACE::INTERP_CUT_CELL protected
Referenced by perform_thermal_step().
flux_interface_ns_scalar_old_
IJK_Field_double IJK_Thermal_cut_cell::flux_interface_ns_scalar_old_ protected
Referenced by initialize(), and perform_thermal_step().
flux_interface_ft_scalar_old_
IJK_Field_double IJK_Thermal_cut_cell::flux_interface_ft_scalar_old_ protected
Referenced by initialize(), and perform_thermal_step().
flux_interface_ns_scalar_next_
IJK_Field_double IJK_Thermal_cut_cell::flux_interface_ns_scalar_next_ protected
Referenced by initialize(), and perform_thermal_step().
flux_interface_ft_scalar_next_
IJK_Field_double IJK_Thermal_cut_cell::flux_interface_ft_scalar_next_ protected
Referenced by initialize(), and perform_thermal_step().
flux_interface_efficace_scalar_
DoubleTabFT_cut_cell_scalar IJK_Thermal_cut_cell::flux_interface_efficace_scalar_ protected
Referenced by add_temperature_diffusion(), initialize(), and perform_thermal_step().
interfacial_temperature_
DoubleTabFT IJK_Thermal_cut_cell::interfacial_temperature_ protected
Referenced by compute_interfacial_temperature2(), and perform_thermal_step().
interfacial_phin_ai_
DoubleTabFT IJK_Thermal_cut_cell::interfacial_phin_ai_ protected
Referenced by compute_interfacial_temperature2(), and perform_thermal_step().
current_fluxes_conv_
Cut_field_vector3_double IJK_Thermal_cut_cell::current_fluxes_conv_ protected
Referenced by initialize(), and perform_thermal_step().
current_fluxes_diff_
Cut_field_vector3_double IJK_Thermal_cut_cell::current_fluxes_diff_ protected
Referenced by initialize(), and perform_thermal_step().
RK3_F_fluxes_conv_
Cut_field_vector3_double IJK_Thermal_cut_cell::RK3_F_fluxes_conv_ protected
Referenced by copie_pure_vers_diph_sans_interpolation(), echange_diph_vers_pure_cellules_finalement_pures(), echange_pure_vers_diph_cellules_initialement_pures(), initialize(), perform_thermal_step(), remplir_tableau_pure_cellules_diphasiques(), and vide_phase_invalide_cellules_diphasiques().
RK3_F_fluxes_diff_
Cut_field_vector3_double IJK_Thermal_cut_cell::RK3_F_fluxes_diff_ protected
Referenced by copie_pure_vers_diph_sans_interpolation(), echange_diph_vers_pure_cellules_finalement_pures(), echange_pure_vers_diph_cellules_initialement_pures(), initialize(), perform_thermal_step(), remplir_tableau_pure_cellules_diphasiques(), and vide_phase_invalide_cellules_diphasiques().
runge_kutta_fluxes_convection_
int IJK_Thermal_cut_cell::runge_kutta_fluxes_convection_ = 0 protected
Referenced by copie_pure_vers_diph_sans_interpolation(), echange_diph_vers_pure_cellules_finalement_pures(), echange_pure_vers_diph_cellules_initialement_pures(), initialize(), perform_thermal_step(), remplir_tableau_pure_cellules_diphasiques(), set_param(), and vide_phase_invalide_cellules_diphasiques().
runge_kutta_fluxes_diffusion_
int IJK_Thermal_cut_cell::runge_kutta_fluxes_diffusion_ = 0 protected
Referenced by copie_pure_vers_diph_sans_interpolation(), echange_diph_vers_pure_cellules_finalement_pures(), echange_pure_vers_diph_cellules_initialement_pures(), initialize(), perform_thermal_step(), remplir_tableau_pure_cellules_diphasiques(), set_param(), and vide_phase_invalide_cellules_diphasiques().
runge_kutta_fluxes_pas_de_correction_convection_
int IJK_Thermal_cut_cell::runge_kutta_fluxes_pas_de_correction_convection_ = 0 protected
Referenced by perform_thermal_step(), and set_param().
runge_kutta_fluxes_pas_de_correction_diffusion_
int IJK_Thermal_cut_cell::runge_kutta_fluxes_pas_de_correction_diffusion_ = 0 protected
Referenced by perform_thermal_step(), and set_param().
cellule_rk_restreint_conv_
Cut_field_int IJK_Thermal_cut_cell::cellule_rk_restreint_conv_ protected
Referenced by copie_pure_vers_diph_sans_interpolation(), echange_diph_vers_pure_cellules_finalement_pures(), echange_pure_vers_diph_cellules_initialement_pures(), initialize(), perform_thermal_step(), remplir_tableau_pure_cellules_diphasiques(), and vide_phase_invalide_cellules_diphasiques().
cellule_rk_restreint_diff_
Cut_field_int IJK_Thermal_cut_cell::cellule_rk_restreint_diff_ protected
Referenced by copie_pure_vers_diph_sans_interpolation(), echange_diph_vers_pure_cellules_finalement_pures(), echange_pure_vers_diph_cellules_initialement_pures(), initialize(), perform_thermal_step(), remplir_tableau_pure_cellules_diphasiques(), and vide_phase_invalide_cellules_diphasiques().
postraiter_champs_intermediaires_
int IJK_Thermal_cut_cell::postraiter_champs_intermediaires_ = 0 protected
Referenced by initialize(), perform_thermal_step(), and set_param().
temperature_post_dying_
Cut_field_double IJK_Thermal_cut_cell::temperature_post_dying_ protected
Referenced by initialize(), and perform_thermal_step().
temperature_post_regular_
Cut_field_double IJK_Thermal_cut_cell::temperature_post_regular_ protected
Referenced by initialize(), and perform_thermal_step().
temperature_post_convection_
Cut_field_double IJK_Thermal_cut_cell::temperature_post_convection_ protected
Referenced by initialize(), and perform_thermal_step().
temperature_post_diff_regular_
Cut_field_double IJK_Thermal_cut_cell::temperature_post_diff_regular_ protected
Referenced by initialize(), and perform_thermal_step().
convective_correction_
Cut_cell_convection_auxiliaire IJK_Thermal_cut_cell::convective_correction_ protected
Referenced by initialize(), perform_thermal_step(), printOn(), and set_param().
diffusive_correction_
Cut_cell_diffusion_auxiliaire IJK_Thermal_cut_cell::diffusive_correction_ protected
Referenced by initialize(), perform_thermal_step(), printOn(), and set_param().
deactivate_diffusion_interface_
int IJK_Thermal_cut_cell::deactivate_diffusion_interface_ = 0 protected
Referenced by compute_interfacial_temperature2(), perform_thermal_step(), and set_param().
runge_kutta_restriction_leniency_convection_
int IJK_Thermal_cut_cell::runge_kutta_restriction_leniency_convection_ = 0 protected
Referenced by perform_thermal_step(), and set_param().
runge_kutta_restriction_leniency_diffusion_
int IJK_Thermal_cut_cell::runge_kutta_restriction_leniency_diffusion_ = 0 protected
Referenced by perform_thermal_step(), and set_param().
verbosite_
int IJK_Thermal_cut_cell::verbosite_ = 2 protected
Referenced by perform_thermal_step(), print_Tmin_Tmax_cut_cell(), and rk3_sub_step().