TrioCFD: Modele_turbulence_hyd_RANS_Gen< MODELE > Class Template Reference
Modele_turbulence_hyd_RANS_Gen< MODELE > Class Template Reference
#include <Modele_turbulence_hyd_RANS_Gen.h>
Member Function Documentation
complete_viscosity_field()
template<typename MODELE > DoubleTab & Modele_turbulence_hyd_RANS_Gen< MODELE >::complete_viscosity_field (const int n, const Domaine_dis_base & dom_dis, Champ_Inc_base & visc)
References Champ_Inc_base::associer_domaine_dis_base(), Champ_Inc_base::changer_temps(), Field_base::fixer_nb_comp(), Champ_Inc_base::fixer_nb_valeurs_nodales(), Field_base::fixer_unite(), Field_base::nommer(), and Champ_Inc_base::valeurs().
calculate_limit_viscosity() [1/4]
template<typename MODELE > template<MODELE_TYPE M_TYPE> std::enable_if_t<(M_TYPE==MODELE_TYPE::K_EPS||M_TYPE==MODELE_TYPE::K_EPS_REALISABLE||M_TYPE==MODELE_TYPE::K_OMEGA), void > Modele_turbulence_hyd_RANS_Gen< MODELE >::calculate_limit_viscosity (Champ_Inc_base & ch_K_Eps_ou_Omega, double LeCmu)
calculate_limit_viscosity() [2/4]
template<typename MODELE > template<MODELE_TYPE M_TYPE> std::enable_if_t< M_TYPE==MODELE_TYPE::K_EPS_2_COUCHES, void > Modele_turbulence_hyd_RANS_Gen< MODELE >::calculate_limit_viscosity (Champ_Inc_base & ch_K_Eps_ou_Omega, double LeCmu)
References Milieu_base::equation(), Probleme_base::milieu(), Equation_base::probleme(), Champ_base::temps(), and Champ_Inc_base::valeurs().
calculate_limit_viscosity() [3/4]
template<typename MODELE > template<MODELE_TYPE M_TYPE> std::enable_if_t< M_TYPE==MODELE_TYPE::K_EPS_BAS_REYNOLDS, void > Modele_turbulence_hyd_RANS_Gen< MODELE >::calculate_limit_viscosity (Champ_Inc_base & ch_K_Eps_ou_Omega, double LeCmu)
References Champ_base::temps().
calculate_limit_viscosity() [4/4]
template<typename MODELE > template<MODELE_TYPE M_TYPE> std::enable_if_t<(M_TYPE==MODELE_TYPE::K_EPS_BICEPHALE||M_TYPE==MODELE_TYPE::K_EPS_REALISABLE_BICEPHALE), void > Modele_turbulence_hyd_RANS_Gen< MODELE >::calculate_limit_viscosity (Champ_Inc_base & ch_K, Champ_Inc_base & ch_Eps, double LeCmu)