TrioCFD: TRUSTProblem_sup_eqns< _DERIVED_TYPE_ > Class Template Reference
TRUSTProblem_sup_eqns< _DERIVED_TYPE_ > Class Template Reference
#include <TRUSTProblem_sup_eqns.h>
Constructor & Destructor Documentation
TRUSTProblem_sup_eqns()
template<typename _DERIVED_TYPE_ > TRUSTProblem_sup_eqns< _DERIVED_TYPE_ >::TRUSTProblem_sup_eqns () inline
Referenced by TRUSTProblem_sup_eqns< _DERIVED_TYPE_ >::duplique().
~TRUSTProblem_sup_eqns()
template<typename _DERIVED_TYPE_ > TRUSTProblem_sup_eqns< _DERIVED_TYPE_ >::~TRUSTProblem_sup_eqns () inline
Member Function Documentation
taille_memoire()
template<typename _DERIVED_TYPE_ > unsigned TRUSTProblem_sup_eqns< _DERIVED_TYPE_ >::taille_memoire () const inline override protected
duplique()
template<typename _DERIVED_TYPE_ > int TRUSTProblem_sup_eqns< _DERIVED_TYPE_ >::duplique () const inline override protected
References Process::exit(), and TRUSTProblem_sup_eqns< _DERIVED_TYPE_ >::TRUSTProblem_sup_eqns().
printOn()
template<typename _DERIVED_TYPE_ > Sortie & TRUSTProblem_sup_eqns< _DERIVED_TYPE_ >::printOn (Sortie & os) const inline override protected
Referenced by Pb_Thermohydraulique_Especes_QC::printOn(), Pb_Thermohydraulique_Especes_WC::printOn(), Pb_Thermohydraulique_Concentration_Scalaires_Passifs::printOn(), Pb_Hydraulique_Concentration_Scalaires_Passifs::printOn(), Pb_Thermohydraulique_Scalaires_Passifs::printOn(), Pb_Conduction_Scalaires_Passifs::printOn(), Pb_Thermohydraulique_Turbulent_Scalaires_Passifs::printOn(), Pb_Thermohydraulique_Especes_Turbulent_QC::printOn(), Pb_Hydraulique_Concentration_Turbulent_Scalaires_Passifs::printOn(), and Pb_Thermohydraulique_Concentration_Turbulent_Scalaires_Passifs::printOn().
readOn()
template<typename _DERIVED_TYPE_ > Entree & TRUSTProblem_sup_eqns< _DERIVED_TYPE_ >::readOn (Entree & is) inline override protected
References TRUSTProblem_sup_eqns< _DERIVED_TYPE_ >::is_lecture.
Referenced by Pb_Thermohydraulique_Especes_QC::readOn(), Pb_Thermohydraulique_Especes_WC::readOn(), Pb_Thermohydraulique_Concentration_Scalaires_Passifs::readOn(), Pb_Hydraulique_Concentration_Scalaires_Passifs::readOn(), Pb_Thermohydraulique_Scalaires_Passifs::readOn(), Pb_Conduction_Scalaires_Passifs::readOn(), Pb_Thermohydraulique_Turbulent_Scalaires_Passifs::readOn(), Pb_Thermohydraulique_Especes_Turbulent_QC::readOn(), Pb_Hydraulique_Concentration_Turbulent_Scalaires_Passifs::readOn(), and Pb_Thermohydraulique_Concentration_Turbulent_Scalaires_Passifs::readOn().
nombre_d_equations()
template<typename _DERIVED_TYPE_ > int TRUSTProblem_sup_eqns< _DERIVED_TYPE_ >::nombre_d_equations () const inline override
References List_Equations_Scalaires_Passifs_Especes::complete(), TRUSTProblem_sup_eqns< _DERIVED_TYPE_ >::list_eq_supp, and List_Equations_Scalaires_Passifs_Especes::nb_equation().
equation() [1/2]
template<typename _DERIVED_TYPE_ > const Equation_base & TRUSTProblem_sup_eqns< _DERIVED_TYPE_ >::equation (int i) const inline override
References List_Equations_Scalaires_Passifs_Especes::equation(), TRUSTProblem_sup_eqns< _DERIVED_TYPE_ >::is_lecture, and TRUSTProblem_sup_eqns< _DERIVED_TYPE_ >::list_eq_supp.
equation() [2/2]
template<typename _DERIVED_TYPE_ > Equation_base & TRUSTProblem_sup_eqns< _DERIVED_TYPE_ >::equation (int i) inline override
References List_Equations_Scalaires_Passifs_Especes::complete(), List_Equations_Scalaires_Passifs_Especes::equation(), TRUSTProblem_sup_eqns< _DERIVED_TYPE_ >::is_lecture, and TRUSTProblem_sup_eqns< _DERIVED_TYPE_ >::list_eq_supp.
associer_milieu_base()
template<typename _DERIVED_TYPE_ > void TRUSTProblem_sup_eqns< _DERIVED_TYPE_ >::associer_milieu_base (const Milieu_base & mil) inline override
References List_Equations_Scalaires_Passifs_Especes::associer_milieu_base(), and TRUSTProblem_sup_eqns< _DERIVED_TYPE_ >::list_eq_supp.
Member Data Documentation
list_eq_supp
template<typename _DERIVED_TYPE_ > List_Equations_Scalaires_Passifs_Especes TRUSTProblem_sup_eqns< _DERIVED_TYPE_ >::list_eq_supp protected
Referenced by TRUSTProblem_sup_eqns< _DERIVED_TYPE_ >::associer_milieu_base(), TRUSTProblem_sup_eqns< _DERIVED_TYPE_ >::equation(), and TRUSTProblem_sup_eqns< _DERIVED_TYPE_ >::nombre_d_equations().
is_lecture
template<typename _DERIVED_TYPE_ > int TRUSTProblem_sup_eqns< _DERIVED_TYPE_ >::is_lecture protected
Referenced by TRUSTProblem_sup_eqns< _DERIVED_TYPE_ >::equation(), and TRUSTProblem_sup_eqns< _DERIVED_TYPE_ >::readOn().