TrioCFD: Schema_Phase_field Class Reference
Schema_Phase_field Class Reference
#include <Schema_Phase_field.h>
Public Member Functions
void changer_temps_courant (const double) override
void completer () override
bool corriger_dt_calcule (double &) const override
virtual int deuxieme_dt (Convection_Diffusion_Phase_field &eq_c)
virtual int faire_un_pas_de_temps_C_D_Phase_field (Convection_Diffusion_Phase_field &)
int faire_un_pas_de_temps_eqn_base (Equation_base &) override
const Type_info * get_info () const override
void imprimer (Sortie &) const override
bool iterateTimeStep (bool &converged) override
int lire_motcle_non_standard (const Motcle &, Entree &) override
int mettre_a_jour () override
int nb_valeurs_futures () const override
int nb_valeurs_temporelles () const override
virtual int premier_dt (Convection_Diffusion_Phase_field &eq_c)
int stop () const override
double temps_defaut () const override
double temps_futur (int i) const override
Public Member Functions inherited from Schema_Temps_base
virtual void changer_temps_courant (const double)
virtual bool corriger_dt_calcule (double &dt) const
int diffusion_implicite () const
double & facteur_securite_pas ()
double facteur_securite_pas () const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual int impr (Sortie &os, Probleme_base &pb) const
virtual void imprimer (Sortie &os) const
void imprimer (Sortie &os, Probleme_base &pb) const
virtual bool isStationary () const
const Nom & le_nom () const override
int limpr () const
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual int mettre_a_jour ()
int nb_impr () const
int nb_pas_dt () const
int nb_pas_dt_max () const
int nb_pas_dt_max_atteint () const
int nb_sauv_max () const
void nommer (const Nom &) override
double pas_de_temps () const
double & pas_temps_max ()
double pas_temps_max () const
double & pas_temps_min ()
double pas_temps_min () const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Schema_Temps_base ()
double seuil_statio () const
virtual int stop () const
int stop_lu () const
double temps_calcul () const
double temps_courant () const
int temps_final_atteint () const
double temps_impr () const
double temps_init () const
double temps_max () const
double temps_precedent () const
double temps_sauv () const
void update_critere_statio (const DoubleTab &tab_critere, Equation_base &equation)
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
See also
Schema_Temps_base
Constructor & Destructor Documentation
Schema_Phase_field()
Schema_Phase_field::Schema_Phase_field ()
~Schema_Phase_field()
Schema_Phase_field::~Schema_Phase_field ()
Member Function Documentation
cree_instance()
Objet_U * Schema_Phase_field::cree_instance () static
taille_memoire()
unsigned Schema_Phase_field::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Schema_Phase_field::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Schema_Phase_field::info () static
get_info()
const Type_info * Schema_Phase_field::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Schema_Temps_base.
self_cast() [1/2]
Schema_Phase_field & Schema_Phase_field::self_cast (Objet_U & r) static
self_cast() [2/2]
const Schema_Phase_field & Schema_Phase_field::self_cast (const Objet_U & r) static
printOn()
Sortie & Schema_Phase_field::printOn (Sortie & s) const override protected virtual
Simple appel a: Schema_Temps_base::printOn(Sortie&) Ecrit le schema en temps sur un flot de sortie.
Parameters
(Sortie& s) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Schema_Temps_base.
References Schema_Temps_base::printOn().
readOn()
Entree & Schema_Phase_field::readOn (Entree & s) override protected virtual
Lit le schema en temps a partir d'un flot d'entree.
Simple appel a: Schema_Temps_base::readOn(Entree&)
Parameters
(Entree& s) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Schema_Temps_base.
References Schema_Temps_base::readOn().
nb_valeurs_temporelles()
int Schema_Phase_field::nb_valeurs_temporelles () const override virtual
Renvoie le nombre de valeurs temporelles a conserver.
Ici : le max des deux schemas utilises.
Implements Schema_Temps_base.
References Schema_Temps_base::nb_valeurs_temporelles(), sch2, and sch3.
nb_valeurs_futures()
int Schema_Phase_field::nb_valeurs_futures () const override virtual
Renvoie le nombre de valeurs temporelles futures.
Ici : la valeur commune aux deux schemas utilises.
Implements Schema_Temps_base.
References Schema_Temps_base::nb_valeurs_futures(), sch2, and sch3.
temps_futur()
double Schema_Phase_field::temps_futur (int i) const override virtual
Renvoie le le temps a la i-eme valeur future.
Ici : la valeur commune aux deux schemas utilises.
Implements Schema_Temps_base.
References Schema_Temps_base::pas_temps_min(), sch2, sch3, and Schema_Temps_base::temps_futur().
temps_defaut()
double Schema_Phase_field::temps_defaut () const override virtual
Renvoie le le temps le temps que doivent rendre les champs a l'appel de valeurs()
Ici : la valeur commune aux deux schemas utilises.
Implements Schema_Temps_base.
References Schema_Temps_base::pas_temps_min(), sch2, sch3, and Schema_Temps_base::temps_defaut().
initialize()
void Schema_Phase_field::initialize () override virtual
Reimplemented from Schema_Temps_base.
References Schema_Temps_base::initialize(), sch2, and sch3.
initTimeStep()
bool Schema_Phase_field::initTimeStep (double dt) override virtual
Reimplemented from Schema_Temps_base.
References Schema_Temps_base::initTimeStep(), sch2, and sch3.
faire_un_pas_de_temps_eqn_base()
int Schema_Phase_field::faire_un_pas_de_temps_eqn_base (Equation_base & eqn) override virtual
Effectue un pas de temps sur l'equation passee en parametre.
Le pas de temps effectue n'est pas standard si l'equation est de type Convection_Diffusion_Phase_field
Parameters
(Equation_base& eqn) l'equation que l'on veut faire avancer d'un pas de temps
Returns
(int) renvoie toujours 1
Implements Schema_Temps_base.
References Navier_Stokes_phase_field::calculer_rho(), faire_un_pas_de_temps_C_D_Phase_field(), Schema_Temps_base::faire_un_pas_de_temps_eqn_base(), Schema_Temps_base::isStationary(), Schema_Temps_base::pas_de_temps(), Objet_U::que_suis_je(), sch3, Schema_Temps_base::set_dt(), and Schema_Temps_base::set_stationnaire_atteint().
Referenced by iterateTimeStep().
iterateTimeStep()
bool Schema_Phase_field::iterateTimeStep (bool & converged) override virtual
faire_un_pas_de_temps_pb_base avec NS = equation(0) et CH = equation(1) Sert a calculer l'equation de Cahn-Hilliard en premier puis Navier-Stokes, en appelant
equation(1) d'abord puis equation(0) pour obtenir les couplages voulus. (dans le cas nb_eqn=2)
Parameters
(Pb_base& eqn) Pb a resoudre
Returns
(int) renvoie toujours 1
Reimplemented from Schema_Temps_base.
References Equation_base::derivee_en_temps_inco(), Equation_base::domaine_Cl_dis(), Schema_Temps_base::dt_, Probleme_base::equation(), Equation_base::equation_non_resolue(), faire_un_pas_de_temps_eqn_base(), Equation_base::inconnue(), Domaine_Cl_dis_base::mettre_a_jour(), Schema_Temps_base::nb_pas_dt(), Probleme_base::nombre_d_equations(), Schema_Temps_base::pb_base(), Objet_U::que_suis_je(), Equation_base::schema_temps(), Schema_Temps_base::temps_courant_, and Champ_Inc_base::valeurs().
faire_un_pas_de_temps_C_D_Phase_field()
int Schema_Phase_field::faire_un_pas_de_temps_C_D_Phase_field (Convection_Diffusion_Phase_field & eq_c) virtual
Effectue un pas de temps sur l'equation de type Convection_Diffusion_Phase_field.
Parameters
(Convection_Diffusion_Phase_field& eq_c) l'equation que l'on veut faire avancer d'un pas de temps
Returns
(int) renvoie toujours 1
References deuxieme_dt(), and premier_dt().
Referenced by faire_un_pas_de_temps_eqn_base().
premier_dt()
int Schema_Phase_field::premier_dt (Convection_Diffusion_Phase_field & eq_c) virtual
Effectue le premier demi-pas de temps1 sur l'equation de type Convection_Diffusion_Phase_field.
Parameters
(Convection_Diffusion_Phase_field& eq_c) l'equation que l'on veut faire avancer d'un demi-pas de temps
Returns
(int) renvoie toujours 1
References Source_Con_Phase_field_base::premier_demi_dt(), and Equation_base::sources().
Referenced by faire_un_pas_de_temps_C_D_Phase_field().
deuxieme_dt()
int Schema_Phase_field::deuxieme_dt (Convection_Diffusion_Phase_field & eq_c) virtual
Effectue le deuxieme demi-pas de temps sur l'equation de type Convection_Diffusion_Phase_field.
Parameters
(Convection_Diffusion_Phase_field& eq_c) l'equation que l'on veut faire avancer d'un demi-pas de temps
Returns
(int) renvoie toujours 1
References Schema_Temps_base::faire_un_pas_de_temps_eqn_base(), Convection_Diffusion_Phase_field::get_c_demi(), Convection_Diffusion_Concentration::inconnue(), Schema_Temps_base::isStationary(), Schema_Temps_base::pas_de_temps(), sch2, Schema_Temps_base::set_dt(), Schema_Temps_base::set_stationnaire_atteint(), and Champ_Inc_base::valeurs().
Referenced by faire_un_pas_de_temps_C_D_Phase_field().
valeur_temps_intermediaire()
const DoubleTab & Schema_Phase_field::valeur_temps_intermediaire () const inline
set_param()
void Schema_Phase_field::set_param (Param & titi) override virtual
Reimplemented from Schema_Temps_base.
References Param::ajouter_non_std(), and Schema_Temps_base::set_param().
lire_motcle_non_standard()
int Schema_Phase_field::lire_motcle_non_standard (const Motcle & mot, Entree & is) override virtual
Lecture du nombre d'iterations pour l'etape de relaxation du Schema_Phase_field.
Parameters
(const Motcle& mot) un mot cle
(Entree& is) un flot d'entree
Reimplemented from Schema_Temps_base.
References Schema_Temps_base::lire_motcle_non_standard(), sch2, sch3, Objet_U_ptr::typer(), and TRUST_Deriv< _CLASSE_ >::valeur().
mettre_a_jour()
int Schema_Phase_field::mettre_a_jour () override virtual
Mise a jour du temps courant (t+=dt) et du nombre de pas de temps effectue (nb_pas_dt_++).
Returns
(int) retourne mettre_a_jour de la classe mere
Reimplemented from Schema_Temps_base.
References Schema_Temps_base::mettre_a_jour(), sch2, and sch3.
corriger_dt_calcule()
bool Schema_Phase_field::corriger_dt_calcule (double & dt) const override virtual
Corrige le pas de temps dt_min <= dt <= dt_max.
Returns
(int) 1 si il faut faire une sauvegarde 0 sinon
(int) retourne corriger_pas_temps de la classe mere
Reimplemented from Schema_Temps_base.
References Schema_Temps_base::corriger_dt_calcule(), sch2, and sch3.
completer()
void Schema_Phase_field::completer () override virtual
Complete les attributs de sch2.
Returns
retourne toujours 1
Implements Schema_Temps_base.
References Schema_Temps_base::diffusion_implicite(), Schema_Temps_base::facteur_securite_pas(), Schema_Temps_base::indice_nb_pas_dt_max_atteint(), Schema_Temps_base::indice_tps_final_atteint(), Schema_Temps_base::isStationary(), Schema_Temps_base::lu(), Schema_Temps_base::mode_dt_start(), Schema_Temps_base::nb_pas_dt(), Schema_Temps_base::nb_pas_dt_max(), Schema_Temps_base::niter_max_diffusion_implicite(), Schema_Temps_base::pas_de_temps(), Schema_Temps_base::pas_temps_max(), Schema_Temps_base::pas_temps_min(), sch2, sch3, Schema_Temps_base::set_diffusion_implicite(), Schema_Temps_base::set_dt(), Schema_Temps_base::set_dt_impr(), Schema_Temps_base::set_dt_max(), Schema_Temps_base::set_dt_min(), Schema_Temps_base::set_dt_sauv(), Schema_Temps_base::set_facsec(), Schema_Temps_base::set_indice_nb_pas_dt_max_atteint(), Schema_Temps_base::set_indice_tps_final_atteint(), Schema_Temps_base::set_lu(), Schema_Temps_base::set_mode_dt_start(), Schema_Temps_base::set_nb_pas_dt(), Schema_Temps_base::set_nb_pas_dt_max(), Schema_Temps_base::set_niter_max_diffusion_implicite(), Schema_Temps_base::set_seuil_diffusion_implicite(), Schema_Temps_base::set_seuil_statio(), Schema_Temps_base::set_stationnaire_atteint(), Schema_Temps_base::set_temps_courant(), Schema_Temps_base::set_temps_init(), Schema_Temps_base::set_temps_max(), Schema_Temps_base::seuil_diffusion_implicite(), Schema_Temps_base::seuil_statio(), Schema_Temps_base::temps_courant(), Schema_Temps_base::temps_impr(), Schema_Temps_base::temps_init(), Schema_Temps_base::temps_max(), Schema_Temps_base::temps_sauv(), and TRUST_Deriv< _CLASSE_ >::valeur().
changer_temps_courant()
void Schema_Phase_field::changer_temps_courant (const double t) override virtual
Appel a l'objet sous-jacent Change le temps courant.
Parameters
(double& t) la nouvelle valeur du temps courant
Reimplemented from Schema_Temps_base.
References Schema_Temps_base::changer_temps_courant(), sch2, and sch3.
stop()
int Schema_Phase_field::stop () const override virtual
Appel a l'objet sous-jacent Renvoie 1 si il y lieu de stopper le calcul pour differente raisons:
   - le temps final est atteint
   - le nombre de pas de temps maximum est depasse
   - l'etat stationnaire est atteint
   - indicateur d'arret fichier
Renvoie 0 sinon
Returns
(entier) 1 si il y a lieu de s'arreter 0 sinon
Reimplemented from Schema_Temps_base.
References sch2, sch3, and Schema_Temps_base::stop().
imprimer()
void Schema_Phase_field::imprimer (Sortie & os) const override virtual
Appel a l'objet sous-jacent Imprime le schema en temp sur un flot de sortie (si il y a lieu).
Parameters
(Sortie& os) le flot de sortie
Reimplemented from Schema_Temps_base.
References Schema_Temps_base::imprimer(), sch2, and sch3.
associer_pb()
void Schema_Phase_field::associer_pb (const Probleme_base & un_probleme) override virtual
Reimplemented from Schema_Temps_base.
References Schema_Temps_base::associer_pb(), sch2, and sch3.
Member Data Documentation
info_obj
const Type_info Schema_Phase_field::info_obj static
nb_iterations_relax_
int Schema_Phase_field::nb_iterations_relax_ protected
sch2
TRUST_Deriv< Schema_Temps_base > Schema_Phase_field::sch2 protected
Referenced by associer_pb(), changer_temps_courant(), completer(), corriger_dt_calcule(), deuxieme_dt(), imprimer(), initialize(), initTimeStep(), lire_motcle_non_standard(), mettre_a_jour(), nb_valeurs_futures(), nb_valeurs_temporelles(), stop(), temps_defaut(), and temps_futur().
sch3
TRUST_Deriv< Schema_Temps_base > Schema_Phase_field::sch3 protected
Referenced by associer_pb(), changer_temps_courant(), completer(), corriger_dt_calcule(), faire_un_pas_de_temps_eqn_base(), imprimer(), initialize(), initTimeStep(), lire_motcle_non_standard(), mettre_a_jour(), nb_valeurs_futures(), nb_valeurs_temporelles(), stop(), temps_defaut(), and temps_futur().