TrioCFD: Raccord_distant_homogene_32_64< _SIZE_ > Class Template Reference
Raccord_distant_homogene_32_64< _SIZE_ > Class Template Reference
#include <Raccord_distant_homogene.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Frontiere_32_64< _SIZE_ >
void add (const Frontiere_32_64 &)
void ajouter_faces (const IntTab_t &)
void associer_domaine (const Domaine_t &)
Domaine_t & domaine ()
const Domaine_t & domaine () const
const Type_info * get_info () const override
const Nom & le_nom () const override
IntTab_t & les_sommets_des_faces ()
const IntTab_t & les_sommets_des_faces () const
void nommer (const Nom &) override
void renum (const IntVect_t &)
void typer_faces (const Motcle &)
void typer_faces (const Type_Face &)
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Member Typedef Documentation
Frontiere_t
template<typename _SIZE_ > using Raccord_distant_homogene_32_64< _SIZE_ >::Frontiere_t = Frontiere_32_64<_SIZE_>
Constructor & Destructor Documentation
Raccord_distant_homogene_32_64()
template<typename _T_ > Raccord_distant_homogene_32_64< _T_ >::Raccord_distant_homogene_32_64
~Raccord_distant_homogene_32_64()
template<typename _T_ > Raccord_distant_homogene_32_64< _T_ >::~Raccord_distant_homogene_32_64
Member Function Documentation
cree_instance()
template<typename _T_ > Objet_U * Raccord_distant_homogene_32_64< _T_ >::cree_instance static
taille_memoire()
template<typename _T_ > unsigned Raccord_distant_homogene_32_64< _T_ >::taille_memoire override virtual
Implements Objet_U.
duplique()
template<typename _T_ > int Raccord_distant_homogene_32_64< _T_ >::duplique override virtual
Implements Objet_U.
info()
template<typename _T_ > const Type_info * Raccord_distant_homogene_32_64< _T_ >::info static
get_info()
template<typename _T_ > const Type_info * Raccord_distant_homogene_32_64< _T_ >::get_info override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Raccord_distant_32_64< _SIZE_ >.
self_cast() [1/2]
template<typename _T_ > Raccord_distant_homogene_32_64< _T_ > & Raccord_distant_homogene_32_64< _T_ >::self_cast (Objet_U & r) static
self_cast() [2/2]
template<typename _T_ > const Raccord_distant_homogene_32_64< _T_ > & Raccord_distant_homogene_32_64< _T_ >::self_cast (const Objet_U & r) static
printOn()
template<typename _SIZE_ > Sortie & Raccord_distant_homogene_32_64< _SIZE_ >::printOn (Sortie & s) const override protected virtual
Simple appel a: Raccord_distant::printOn(Sortie&) (+ finl)
Parameters
(Sortie& s) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Raccord_distant_32_64< _SIZE_ >.
References Raccord_distant_32_64< _SIZE_ >::printOn().
readOn()
template<typename _SIZE_ > Entree & Raccord_distant_homogene_32_64< _SIZE_ >::readOn (Entree & s) override protected virtual
Simple appel a: Raccord_distant::readOn(Entree&)
Parameters
(Entree& s) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Raccord_distant_32_64< _SIZE_ >.
References Raccord_distant_32_64< _SIZE_ >::readOn().
Tab_Envoi() [1/2]
template<typename _SIZE_ > IntTab & Raccord_distant_homogene_32_64< _SIZE_ >::Tab_Envoi () inline
Referenced by Raccord_distant_homogene_32_64< _SIZE_ >::initialise().
Tab_Envoi() [2/2]
template<typename _SIZE_ > const IntTab & Raccord_distant_homogene_32_64< _SIZE_ >::Tab_Envoi () const inline
Tab_Recep() [1/2]
template<typename _SIZE_ > ArrOfInt & Raccord_distant_homogene_32_64< _SIZE_ >::Tab_Recep () inline
Referenced by Raccord_distant_homogene_32_64< _SIZE_ >::initialise().
Tab_Recep() [2/2]
template<typename _SIZE_ > const ArrOfInt & Raccord_distant_homogene_32_64< _SIZE_ >::Tab_Recep () const inline
nom_frontiere_voisine()
template<typename _SIZE_ > Nom & Raccord_distant_homogene_32_64< _SIZE_ >::nom_frontiere_voisine () inline
Referenced by Raccord_distant_homogene_32_64< _SIZE_ >::initialise().
est_initialise() [1/2]
template<typename _SIZE_ > int & Raccord_distant_homogene_32_64< _SIZE_ >::est_initialise () inline
Referenced by Raccord_distant_homogene_32_64< _SIZE_ >::initialise(), and Champ_front_calc::initialiser().
est_initialise() [2/2]
template<typename _SIZE_ > const int & Raccord_distant_homogene_32_64< _SIZE_ >::est_initialise () const inline
e() [1/2]
template<typename _SIZE_ > double & Raccord_distant_homogene_32_64< _SIZE_ >::e () inline
Referenced by Raccord_distant_homogene_32_64< _SIZE_ >::initialise().
e() [2/2]
template<typename _SIZE_ > const double & Raccord_distant_homogene_32_64< _SIZE_ >::e () const inline
trace_elem_distant() [1/2]
template<typename _SIZE_ > void Raccord_distant_homogene_32_64< _SIZE_ >::trace_elem_distant (const DoubleTab & y, DoubleTab & x) const override virtual
Reimplemented from Frontiere_32_64< _SIZE_ >.
trace_face_distant() [1/4]
template<typename _SIZE_ > void Raccord_distant_homogene_32_64< _SIZE_ >::trace_face_distant (const DoubleTab & y, DoubleTab & x) const override virtual
Reimplemented from Frontiere_32_64< _SIZE_ >.
trace_face_distant() [2/4]
template<typename _SIZE_ > void Raccord_distant_homogene_32_64< _SIZE_ >::trace_face_distant (const DoubleVect & y, DoubleVect & x) const override virtual
Reimplemented from Frontiere_32_64< _SIZE_ >.
completer()
template<typename _SIZE_ > void Raccord_distant_homogene_32_64< _SIZE_ >::completer
References TRUSTArray< _TYPE_, _SIZE_ >::append_array(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Process::nproc(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and ArrOfBit_32_64< _SIZE_ >::testsetbit().
Referenced by Raccord_distant_homogene_32_64< _SIZE_ >::initialise().
initialise() [1/2]
template<typename _SIZE_ > void Raccord_distant_homogene_32_64< _SIZE_ >::initialise (const Frontiere_t & opposed_boundary, const Domaine_dis_base & opposed_domaine_dis, const Domaine_dis_base & domaine_dis)
Referenced by Champ_front_contact_VEF::initialiser(), and Champ_front_calc::initialiser().
info_obj() [1/2]
const Type_info Raccord_distant_homogene_32_64< int >::info_obj ("Raccord_distant_homogene" , Raccord_distant_homogene_32_64< int >::cree_instance , 1 , Raccord_distant_homogene_32_64bases< int >)
info_obj() [2/2]
const Type_info Raccord_distant_homogene_32_64< trustIdType >::info_obj ("Raccord_distant_homogene" "_64" , Raccord_distant_homogene_32_64< trustIdType >::cree_instance , 1 , Raccord_distant_homogene_32_64bases< trustIdType >)
trace_elem_distant() [2/2]
void Raccord_distant_homogene_32_64< int >::trace_elem_distant (const DoubleTab & y, DoubleTab & x) const virtual
Retourne dans le DoubleTab x la trace sur le raccord distant du DoubleTab y localise aux elements du domaine distant.
Reimplemented from Frontiere_32_64< _SIZE_ >.
References Schema_Comm::begin_comm(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Schema_Comm::echange_taille_et_messages(), Schema_Comm::end_comm(), Process::exit(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Schema_Comm::recv_buffer(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Schema_Comm::send_buffer(), Schema_Comm::set_send_recv_pe_list(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and Faces_32_64< _SIZE_ >::voisin().
trace_face_distant() [3/4]
void Raccord_distant_homogene_32_64< int >::trace_face_distant (const DoubleTab & y, DoubleTab & x) const virtual
Retourne dans le DoubleTab x la trace sur le raccord distant du DoubleTab y localise aux faces.
Reimplemented from Frontiere_32_64< _SIZE_ >.
References TRUSTArray< _TYPE_, _SIZE_ >::addr(), Schema_Comm::begin_comm(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Schema_Comm::echange_taille_et_messages(), Schema_Comm::end_comm(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Schema_Comm::recv_buffer(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Schema_Comm::send_buffer(), Schema_Comm::set_send_recv_pe_list(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
trace_face_distant() [4/4]
void Raccord_distant_homogene_32_64< int >::trace_face_distant (const DoubleVect & y, DoubleVect & x) const virtual
Retourne dans le DoubleVect x la trace sur le raccord distant du DoubleVect y localise aux faces du raccord distant.
Reimplemented from Frontiere_32_64< _SIZE_ >.
References Schema_Comm::begin_comm(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Schema_Comm::echange_taille_et_messages(), Schema_Comm::end_comm(), Schema_Comm::recv_buffer(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), Schema_Comm::send_buffer(), Schema_Comm::set_send_recv_pe_list(), TRUSTVect< _TYPE_, _SIZE_ >::size(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
initialise() [2/2]
void Raccord_distant_homogene_32_64< int >::initialise (const Frontiere & opposed_boundary, const Domaine_dis_base & opposed_domaine_dis, const Domaine_dis_base & domaine_dis)
Initialise le raccord distant avec la frontiere et le domaine discretisee opposees au raccord distant, et le domaine discretisee du raccord distant Only called from Champ_front* instances, so can remain 32 bits only.
References Raccord_distant_homogene_32_64< _SIZE_ >::completer(), Objet_U::dimension, Domaine_dis_base::domaine(), Raccord_distant_homogene_32_64< _SIZE_ >::e(), Raccord_distant_homogene_32_64< _SIZE_ >::est_initialise(), Process::exit(), Domaine_base::le_nom(), Frontiere_32_64< _SIZE_ >::le_nom(), Process::me(), Frontiere_32_64< _SIZE_ >::nb_faces(), Raccord_distant_homogene_32_64< _SIZE_ >::nom_frontiere_voisine(), Process::nproc(), Frontiere_32_64< _SIZE_ >::num_premiere_face(), Objet_U::precision_geom, TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUST_Vector< _CLASSE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), Raccord_distant_homogene_32_64< _SIZE_ >::Tab_Envoi(), Raccord_distant_homogene_32_64< _SIZE_ >::Tab_Recep(), and Domaine_VF::xv().
Member Data Documentation
info_obj
template<typename _SIZE_ > const Type_info Raccord_distant_homogene_32_64< _SIZE_ >::info_obj static