TrioCFD: Cut_cell_correction_petites_cellules Class Reference
Cut_cell_correction_petites_cellules Class Reference
#include <Cut_cell_correction_petites_cellules.h>
Member Function Documentation
modification_flux_petites_cellules()
void Cut_cell_correction_petites_cellules::modification_flux_petites_cellules (CORRECTION_PETITES_CELLULES correction_petites_cellules, double quantite_totale, double flux[6]) static
Referenced by Cut_cell_schema_auxiliaire::add_dying_cells(), and Cut_cell_schema_auxiliaire::add_small_nascent_cells().
limitation_flux_avec_flux_max()
void Cut_cell_correction_petites_cellules::limitation_flux_avec_flux_max (CORRECTION_PETITES_CELLULES correction_petites_cellules, double quantite_totale, double somme_flux, double flux_max[6], double flux[6]) static
Referenced by Cut_cell_schema_auxiliaire::add_small_nascent_cells().
calcul_somme_flux()
double Cut_cell_correction_petites_cellules::calcul_somme_flux (const double flux[6]) static
Referenced by Cut_cell_schema_auxiliaire::add_dying_cells(), and Cut_cell_schema_auxiliaire::add_small_nascent_cells().