TrioCFD: Champ_Fonc_Tabule_Morceaux_Interp Class Reference
Champ_Fonc_Tabule_Morceaux_Interp Class Reference
#include <Champ_Fonc_Tabule_Morceaux_Interp.h>
Public Member Functions
const Type_info * get_info () const override
int initialiser (const double temps) override
const Type_info * get_info () const override
int initialiser (const double temps) override
Public Member Functions inherited from TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC_TABULE >
int initialiser (const double temps) override
void mettre_a_jour (double temps) override
DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const override
DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &valeurs, int le_poly) const override
double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const override
DoubleTab & valeur_aux (const DoubleTab &positions, DoubleTab &valeurs) const override
DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const override
DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const override
DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp) const override
Public Member Functions inherited from Champ_Don_base
void dimensionner (int, int)
int fixer_nb_valeurs_nodales (int nb_noeuds) override
const Type_info * get_info () const override
int imprime (Sortie &, int) const override
virtual int initialiser (const double temps)
void mettre_a_jour (double temps) override
int reprendre (Entree &) override
void resetTime (double time) override
int sauvegarder (Sortie &) const override
DoubleTab & valeurs () override
Public Member Functions inherited from Champ_base
Champ_base & affecter (const Champ_base &)
Champ_base ()
virtual double changer_temps (const double t)
const Type_info * get_info () const override
double temps () const
virtual DoubleTab & trace (const Frontiere_dis_base &, DoubleTab &, double, int distant) const
virtual DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const
virtual double valeur_a_compo (const DoubleVect &position, int ncomp) const
virtual DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &valeurs, int le_poly) const
virtual double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const
virtual DoubleVect & valeur_a_sommet (int, const Domaine &, DoubleVect &) const
virtual DoubleTab & valeur_aux (const DoubleTab &positions, DoubleTab &valeurs) const
virtual DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const
virtual DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const
virtual DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp) const
Public Member Functions inherited from Field_base
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
virtual void fixer_nb_comp (int i)
virtual const Nom & fixer_nom_compo (const Nom &)
virtual const Nom & fixer_nom_compo (int, const Nom &)
virtual const Noms & fixer_noms_compo (const Noms &)
virtual const Nom & fixer_unite (const Nom &)
virtual const Nom & fixer_unite (int i, const Nom &)
virtual const Noms & fixer_unites (const Noms &)
const Type_info * get_info () const override
const Nom & nom_compo (int) const
void nommer (const Nom &) override
const Nom & unite () const
const Nom & unite (int) const
const Noms & unites () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Champ_Proto
int lire_dimension (Entree &, const Nom &)
int lire_dimension (int dim, const Nom &le_nom_)
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Champ_Don_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Field_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
de l'espace et d'un autre champ scalaire passe en parametre .
See also
: TRUSTChamp_Morceaux_generique
Constructor & Destructor Documentation
Champ_Fonc_Tabule_Morceaux_Interp()
Champ_Fonc_Tabule_Morceaux_Interp::Champ_Fonc_Tabule_Morceaux_Interp ()
~Champ_Fonc_Tabule_Morceaux_Interp()
Champ_Fonc_Tabule_Morceaux_Interp::~Champ_Fonc_Tabule_Morceaux_Interp ()
Member Function Documentation
cree_instance()
Objet_U * Champ_Fonc_Tabule_Morceaux_Interp::cree_instance () static
taille_memoire()
unsigned Champ_Fonc_Tabule_Morceaux_Interp::taille_memoire () const override virtual
Reimplemented from Champ_Fonc_Tabule_Morceaux.
duplique()
int Champ_Fonc_Tabule_Morceaux_Interp::duplique () const override virtual
Reimplemented from Champ_Fonc_Tabule_Morceaux.
info()
const Type_info * Champ_Fonc_Tabule_Morceaux_Interp::info () static
get_info()
const Type_info * Champ_Fonc_Tabule_Morceaux_Interp::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Champ_Fonc_Tabule_Morceaux.
self_cast() [1/2]
Champ_Fonc_Tabule_Morceaux_Interp & Champ_Fonc_Tabule_Morceaux_Interp::self_cast (Objet_U & r) static
self_cast() [2/2]
const Champ_Fonc_Tabule_Morceaux_Interp & Champ_Fonc_Tabule_Morceaux_Interp::self_cast (const Objet_U & r) static
printOn()
Sortie & Champ_Fonc_Tabule_Morceaux_Interp::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Champ_Fonc_Tabule_Morceaux.
References Champ_Fonc_Tabule_Morceaux::printOn().
readOn()
Entree & Champ_Fonc_Tabule_Morceaux_Interp::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Champ_Fonc_Tabule_Morceaux.
References Champ_Fonc_Tabule_Morceaux::is_interp_, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC_TABULE >::read_pb_instead_of_domain, and Champ_Fonc_Tabule_Morceaux::readOn().
mettre_a_jour()
void Champ_Fonc_Tabule_Morceaux_Interp::mettre_a_jour (double) override virtual
mettre_a_jour de la classe de base Champ_base :ne fait rien !
Reimplemented from Champ_Fonc_Tabule_Morceaux.
References ch_param_interp, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Champ_Fonc_Tabule_Morceaux::CHTAB::i_ch, Champ_Fonc_Tabule_Morceaux::i_mor, Champ_Fonc_Tabule_Morceaux::CHTAB::la_table, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC_TABULE >::mon_domaine, Champ_Fonc_Tabule_Morceaux::morceaux, Table::val(), Table::val_simple(), and Champ_Don_base::valeurs().
initialiser()
int Champ_Fonc_Tabule_Morceaux_Interp::initialiser (const double un_temps) override virtual
NE FAIT RIEN.
A surcharger dans les classes derivees. Provoque l'initialisation du champ si necessaire
Reimplemented from Champ_Fonc_Tabule_Morceaux.
References ch_param_interp, TRUSTChamp_Morceaux_generique< _TYPE_ >::initialiser(), TRUST_Ref< _CLASSE_ >::le_nom(), Champ_Fonc_Tabule_Morceaux::m_pb_ch, Champ_Fonc_Tabule_Morceaux::morceaux, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC_TABULE >::ref_pb, and Champ_Fonc_Tabule_Morceaux::s_pb_ch.
Member Data Documentation
info_obj
const Type_info Champ_Fonc_Tabule_Morceaux_Interp::info_obj static
ch_param_interp
std::vector<Champ_Fonc_Interp> Champ_Fonc_Tabule_Morceaux_Interp::ch_param_interp protected
Referenced by initialiser(), and mettre_a_jour().