TrioCFD: Eval_Conv_VDF Class Reference
Eval_Conv_VDF Class Reference
#include <Eval_Conv_VDF.h>
Constructor & Destructor Documentation
Eval_Conv_VDF() [1/2]
Eval_Conv_VDF::Eval_Conv_VDF () inline
Eval_Conv_VDF() [2/2]
Eval_Conv_VDF::Eval_Conv_VDF (const Eval_Conv_VDF & eval) inline
References dt_vitesse, and TRUSTTab< _TYPE_, _SIZE_ >::ref().
Member Function Documentation
associer()
void Eval_Conv_VDF::associer (const Champ_Face_VDF & vit) inline
associe le champ de vitesse transportante
References dt_vitesse, TRUSTTab< _TYPE_, _SIZE_ >::ref(), Champ_Inc_base::valeurs(), and vitesse_.
mettre_a_jour()
void Eval_Conv_VDF::mettre_a_jour () inline
References dt_vitesse, TRUSTTab< _TYPE_, _SIZE_ >::ref(), and vitesse_.
vitesse() [1/2]
const Champ_Inc_base & Eval_Conv_VDF::vitesse () const inline
References TRUST_Ref< _CLASSE_ >::valeur(), and vitesse_.
vitesse() [2/2]
Champ_Inc_base & Eval_Conv_VDF::vitesse () inline
References TRUST_Ref< _CLASSE_ >::valeur(), and vitesse_.
get_elem()
int Eval_Conv_VDF::get_elem (int i, int j) const inline
References Evaluateur_VDF::elem_.
get_orientation()
int Eval_Conv_VDF::get_orientation (int i) const inline
References Evaluateur_VDF::orientation.
get_premiere_face_bord()
int Eval_Conv_VDF::get_premiere_face_bord () const inline
References Evaluateur_VDF::premiere_face_bord.
get_dt_vitesse()
double Eval_Conv_VDF::get_dt_vitesse (int face, int comp = 0) const inline
References dt_vitesse.
get_surface_porosite()
double Eval_Conv_VDF::get_surface_porosite (int face) const inline
References Evaluateur_VDF::porosite, and Evaluateur_VDF::surface.
get_surface()
double Eval_Conv_VDF::get_surface (int face) const inline
References Evaluateur_VDF::surface.
get_porosite()
double Eval_Conv_VDF::get_porosite (int face) const inline
References Evaluateur_VDF::porosite.
get_tab_vitesse()
const DoubleTab & Eval_Conv_VDF::get_tab_vitesse () const inline
References dt_vitesse.
get_la_zcl()
const Domaine_Cl_VDF & Eval_Conv_VDF::get_la_zcl () const inline
References Evaluateur_VDF::la_zcl, and TRUST_Ref< _CLASSE_ >::valeur().
Member Data Documentation
vitesse_
TRUST_Ref< Champ_Face_VDF *> Eval_Conv_VDF::vitesse_ protected
Referenced by associer(), mettre_a_jour(), and vitesse().
dt_vitesse
DoubleTab Eval_Conv_VDF::dt_vitesse protected
Referenced by associer(), Eval_Conv_VDF(), get_dt_vitesse(), get_tab_vitesse(), and mettre_a_jour().