TrioCFD: Eval_Diff_K_Eps_Bas_Re_VDF_var Class Reference
Eval_Diff_K_Eps_Bas_Re_VDF_var Class Reference
#include <Eval_Diff_K_Eps_Bas_Re_VDF_var.h>
Constructor & Destructor Documentation
Eval_Diff_K_Eps_Bas_Re_VDF_var()
Eval_Diff_K_Eps_Bas_Re_VDF_var::Eval_Diff_K_Eps_Bas_Re_VDF_var (double Prandt_K = PRDT_K_DEFAUT, double Prandt_Eps = PRDT_EPS_DEFAUT) inline
References Prdt.
Member Function Documentation
associer_diff_turb()
void Eval_Diff_K_Eps_Bas_Re_VDF_var::associer_diff_turb (const Champ_Fonc_base & diffu) inline
References diffusivite_turbulente_.
diffusivite_turbulente()
const Champ_Fonc_base & Eval_Diff_K_Eps_Bas_Re_VDF_var::diffusivite_turbulente () const inline
References diffusivite_turbulente_, and TRUST_Ref< _CLASSE_ >::valeur().
mettre_a_jour()
void Eval_Diff_K_Eps_Bas_Re_VDF_var::mettre_a_jour () inline override virtual
Reimplemented from Eval_Diff_VDF.
References diffusivite_turbulente_, dv_diffusivite_turbulente, and TRUSTVect< _TYPE_, _SIZE_ >::ref().
nu_1_impl()
double Eval_Diff_K_Eps_Bas_Re_VDF_var::nu_1_impl (int i, int compo) const inline
References dv_diffusivite_turbulente, Prdt, and Eval_Diff_VDF::tab_diffusivite_.
Referenced by compute_heq_impl().
compute_heq_impl()
double Eval_Diff_K_Eps_Bas_Re_VDF_var::compute_heq_impl (double d0, int i, double d1, int j, int compo) const inline
References nu_1_impl().
Member Data Documentation
PRDT_K_DEFAUT
constexpr double Eval_Diff_K_Eps_Bas_Re_VDF_var::PRDT_K_DEFAUT = 1.0 static constexpr protected
PRDT_EPS_DEFAUT
constexpr double Eval_Diff_K_Eps_Bas_Re_VDF_var::PRDT_EPS_DEFAUT = 1.3 static protected
Prdt_K
double Eval_Diff_K_Eps_Bas_Re_VDF_var::Prdt_K protected
Prdt_Eps
double Eval_Diff_K_Eps_Bas_Re_VDF_var::Prdt_Eps protected
Prdt
double Eval_Diff_K_Eps_Bas_Re_VDF_var::Prdt[2] protected
Referenced by Eval_Diff_K_Eps_Bas_Re_VDF_var(), and nu_1_impl().
diffusivite_turbulente_
TRUST_Ref< Champ_Fonc_base *> Eval_Diff_K_Eps_Bas_Re_VDF_var::diffusivite_turbulente_ protected
Referenced by associer_diff_turb(), diffusivite_turbulente(), and mettre_a_jour().
dv_diffusivite_turbulente
DoubleVect Eval_Diff_K_Eps_Bas_Re_VDF_var::dv_diffusivite_turbulente protected
Referenced by mettre_a_jour(), and nu_1_impl().