TrioCFD: Paroi_UTAU_IMP_Impl Class Reference
Paroi_UTAU_IMP_Impl Class Reference
#include <Paroi_UTAU_IMP_Impl.h>
Detailed Description
.SECTION voir aussi Turbulence_paroi_base
Member Function Documentation
lire_donnees()
Entree & Paroi_UTAU_IMP_Impl::lire_donnees (Entree & s)
References Parser_U::addVar(), diam_hydr, Objet_U::dimension, Process::exit(), lambda_c, lambda_c_ok, Field_base::nb_comp(), Parser_U::parseString(), Motcles::search(), Parser_U::setNbVar(), Parser_U::setString(), u_star, and u_star_ok.
Referenced by Paroi_UTAU_IMP_VDF::readOn(), and Paroi_Cisaillement_Imp_VEF::readOn().
calculer_utau()
double Paroi_UTAU_IMP_Impl::calculer_utau (const DoubleVect & pos, double norm_v, double d_visco)
References diam_hydr, Objet_U::dimension, Parser_U::eval(), lambda_c, Parser_U::setVar(), u_star, u_star_ok, and Champ_base::valeur_a_compo().
Referenced by Paroi_UTAU_IMP_VDF::calculer_hyd(), and Paroi_UTAU_IMP_VDF::calculer_hyd_BiK().
Member Data Documentation
u_star
TRUST_Deriv< Champ_Don_base > Paroi_UTAU_IMP_Impl::u_star protected
Referenced by calculer_utau(), and lire_donnees().
diam_hydr
TRUST_Deriv< Champ_Don_base > Paroi_UTAU_IMP_Impl::diam_hydr protected
Referenced by calculer_utau(), and lire_donnees().
lambda_c
Parser_U Paroi_UTAU_IMP_Impl::lambda_c protected
Referenced by calculer_utau(), and lire_donnees().
u_star_ok
int Paroi_UTAU_IMP_Impl::u_star_ok protected
Referenced by calculer_utau(), and lire_donnees().
lambda_c_ok
int Paroi_UTAU_IMP_Impl::lambda_c_ok protected
Referenced by lire_donnees().