TrioCFD: Source_rayo_semi_transp_QC_VDF_P0_VDF Class Reference
Source_rayo_semi_transp_QC_VDF_P0_VDF Class Reference
#include <Source_rayo_semi_transp_QC_VDF_P0_VDF.h>
Public Member Functions
void completer () override
const Type_info * get_info () const override
void mettre_a_jour (double temps) override
const Type_info * get_info () const override
void mettre_a_jour (double temps) override
Public Member Functions inherited from Source_base
virtual int a_pour_Champ_Fonc (const Motcle &mot, TRUST_Ref< Champ_base * > &ch_ref) const
virtual void associer_champ_rho (const Champ_base &champ_rho)
virtual void completer ()
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
virtual void resetTime (double t)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
.SECTION
Constructor & Destructor Documentation
Source_rayo_semi_transp_QC_VDF_P0_VDF()
Source_rayo_semi_transp_QC_VDF_P0_VDF::Source_rayo_semi_transp_QC_VDF_P0_VDF ()
~Source_rayo_semi_transp_QC_VDF_P0_VDF()
Source_rayo_semi_transp_QC_VDF_P0_VDF::~Source_rayo_semi_transp_QC_VDF_P0_VDF ()
Member Function Documentation
cree_instance()
Objet_U * Source_rayo_semi_transp_QC_VDF_P0_VDF::cree_instance () static
taille_memoire()
unsigned Source_rayo_semi_transp_QC_VDF_P0_VDF::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Source_rayo_semi_transp_QC_VDF_P0_VDF::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Source_rayo_semi_transp_QC_VDF_P0_VDF::info () static
get_info()
const Type_info * Source_rayo_semi_transp_QC_VDF_P0_VDF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Source_rayo_semi_transp_base.
self_cast() [1/2]
Source_rayo_semi_transp_QC_VDF_P0_VDF & Source_rayo_semi_transp_QC_VDF_P0_VDF::self_cast (Objet_U & r) static
self_cast() [2/2]
const Source_rayo_semi_transp_QC_VDF_P0_VDF & Source_rayo_semi_transp_QC_VDF_P0_VDF::self_cast (const Objet_U & r) static
printOn()
Sortie & Source_rayo_semi_transp_QC_VDF_P0_VDF::printOn (Sortie & os) const override protected virtual
DOES NOTHING - to override in derived classes.
Imprime la source sur un flot de sortie.
Parameters
(Sortie& os) le flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Source_rayo_semi_transp_base.
References Objet_U::que_suis_je().
readOn()
Entree & Source_rayo_semi_transp_QC_VDF_P0_VDF::readOn (Entree & is) override protected virtual
DOES NOTHING - to override in derived classes.
Lecture d'un terme source sur un flot d'entree.
Parameters
(Entree& is) le flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Source_rayo_semi_transp_base.
ajouter()
DoubleTab & Source_rayo_semi_transp_QC_VDF_P0_VDF::ajouter (DoubleTab & resu) const override virtual
Reimplemented from Source_base.
References Source::ajouter(), and le_source_rayo.
Referenced by calculer().
calculer()
DoubleTab & Source_rayo_semi_transp_QC_VDF_P0_VDF::calculer (DoubleTab & resu) const override virtual
Reimplemented from Source_base.
References ajouter().
mettre_a_jour()
void Source_rayo_semi_transp_QC_VDF_P0_VDF::mettre_a_jour (double temps) override virtual
DOES NOTHING - to override in derived classes.
Mise a jour en temps du terme source.
Parameters
(double) le pas de temps de mise a jour
Reimplemented from Source_rayo_semi_transp_base.
References le_source_rayo.
completer()
void Source_rayo_semi_transp_QC_VDF_P0_VDF::completer () override virtual
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees: Source_base::associer_domaines(const Domaine_dis_base& ,const Domaine_Cl_dis_base&) Source_base::associer_pb(const Probleme_base&)
Reimplemented from Source_base.
References Source_base::completer(), MorEqn::equation(), le_source_rayo, and Source::typer_direct().
source_rayo() [1/2]
Source & Source_rayo_semi_transp_QC_VDF_P0_VDF::source_rayo () inline
References le_source_rayo.
source_rayo() [2/2]
const Source & Source_rayo_semi_transp_QC_VDF_P0_VDF::source_rayo () const inline
References le_source_rayo.
associer_modele_rayo()
void Source_rayo_semi_transp_QC_VDF_P0_VDF::associer_modele_rayo (Modele_rayo_semi_transp & modele) override virtual
Appele par Pb_Couple_rayo_semi_transp::initialiser()
Reimplemented from Source_rayo_semi_transp_base.
References Source_rayo_semi_transp_base::associer_modele_rayo(), Source_rayo_semi_transp_base::le_modele_, le_source_rayo, and TRUST_Deriv< _CLASSE_ >::valeur().
associer_domaines()
void Source_rayo_semi_transp_QC_VDF_P0_VDF::associer_domaines (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis) override protected virtual
Implements Source_base.
associer_pb()
void Source_rayo_semi_transp_QC_VDF_P0_VDF::associer_pb (const Probleme_base & pb) override protected virtual
Implements Source_base.
Member Data Documentation
info_obj
const Type_info Source_rayo_semi_transp_QC_VDF_P0_VDF::info_obj static
le_source_rayo
Source Source_rayo_semi_transp_QC_VDF_P0_VDF::le_source_rayo protected
Referenced by ajouter(), associer_modele_rayo(), completer(), mettre_a_jour(), and source_rayo().