TrioCFD: Solv_GCP_NS Class Reference
Solv_GCP_NS Class Reference
#include <Solv_GCP_NS.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from solv_iteratif
const Type_info * get_info () const override
Public Member Functions inherited from SolveurSys_base
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
int lire_motcle_non_standard (const Motcle &, Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from solv_iteratif
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from SolveurSys_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Solv_GCP_NS()
Solv_GCP_NS::Solv_GCP_NS ()
~Solv_GCP_NS()
Solv_GCP_NS::~Solv_GCP_NS ()
Member Function Documentation
cree_instance()
Objet_U * Solv_GCP_NS::cree_instance () static
taille_memoire()
unsigned Solv_GCP_NS::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Solv_GCP_NS::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Solv_GCP_NS::info () static
get_info()
const Type_info * Solv_GCP_NS::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
Solv_GCP_NS & Solv_GCP_NS::self_cast (Objet_U & r) static
self_cast() [2/2]
const Solv_GCP_NS & Solv_GCP_NS::self_cast (const Objet_U & r) static
printOn()
Sortie & Solv_GCP_NS::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
readOn()
Entree & Solv_GCP_NS::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
References Param::lire_avec_accolades_depuis(), Objet_U::que_suis_je(), and set_param().
resoudre_systeme() [1/2]
int Solv_GCP_NS::resoudre_systeme (const Matrice_Base & la_matrice, const DoubleVect & secmem, DoubleVect & solution) override virtual
Implements SolveurSys_base.
References resoudre_systeme().
Referenced by resoudre_systeme().
resoudre_systeme() [2/2]
int Solv_GCP_NS::resoudre_systeme (const Matrice_Base & matrice, const DoubleVect & secmem, DoubleVect & solution, int niter_max) override virtual
Reimplemented from SolveurSys_base.
References TRUSTVect< _TYPE_, _SIZE_ >::ajoute(), Matrice_Base::ajouter_multvect(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Process::exit(), Matrice_Bloc_Sym::get_bloc(), Process::je_suis_maitre(), le_precond_, SolveurSys_base::limpr(), Process::mp_sum(), Matrice_Base::multvect(), Matrice_Base::multvectT(), Matrice_Bloc::nb_bloc_colonnes(), Matrice_Bloc::nb_bloc_lignes(), Matrice_Base::nb_lignes(), Objet_U_ptr::non_nul(), Precond_base::preconditionner(), SolveurSys::resoudre_systeme(), solv_iteratif::seuil_, TRUSTVect< _TYPE_, _SIZE_ >::size_totale(), solveur_poisson0, and solveur_poisson1.
reinit()
void Solv_GCP_NS::reinit () inline override virtual
Reimplemented from SolveurSys_base.
References SolveurSys_base::reinit(), solveur_poisson0, and solveur_poisson1.
supporte_matrice_morse_sym()
int Solv_GCP_NS::supporte_matrice_morse_sym () inline override virtual
Reimplemented from SolveurSys_base.
set_param()
void Solv_GCP_NS::set_param (Param & param) protected
References Param::ajouter(), Param::ajouter_non_std(), le_precond_, and solv_iteratif::seuil_.
Referenced by readOn().
lire_motcle_non_standard()
int Solv_GCP_NS::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override protected virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Objet_U.
References SolveurSys_base::fixer_limpr(), SolveurSys::nommer(), solveur_poisson0, and solveur_poisson1.
Member Data Documentation
info_obj
const Type_info Solv_GCP_NS::info_obj static
solveur_poisson1
SolveurSys Solv_GCP_NS::solveur_poisson1 protected
Referenced by lire_motcle_non_standard(), reinit(), and resoudre_systeme().
solveur_poisson0
SolveurSys Solv_GCP_NS::solveur_poisson0 protected
Referenced by lire_motcle_non_standard(), reinit(), and resoudre_systeme().
le_precond_
TRUST_Deriv< Precond_base > Solv_GCP_NS::le_precond_ protected
Referenced by resoudre_systeme(), and set_param().