TrioCFD: IJK_Field_template< _TYPE_, _TYPE_ARRAY_ > Class Template Reference
IJK_Field_template< _TYPE_, _TYPE_ARRAY_ > Class Template Reference
#include <IJK_Field_template.h>
Protected Member Functions
Sortie & printOn (Sortie &os) const override
Entree & readOn (Entree &is) override
Sortie & printOn (Sortie &os) const override
Entree & readOn (Entree &is) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Public Member Functions inherited from Field_base
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
virtual void fixer_nb_comp (int i)
virtual const Nom & fixer_nom_compo (const Nom &)
virtual const Nom & fixer_nom_compo (int, const Nom &)
virtual const Noms & fixer_noms_compo (const Noms &)
virtual const Nom & fixer_unite (const Nom &)
virtual const Nom & fixer_unite (int i, const Nom &)
virtual const Noms & fixer_unites (const Noms &)
const Type_info * get_info () const override
const Nom & nom_compo (int) const
void nommer (const Nom &) override
const Nom & unite () const
const Nom & unite (int) const
const Noms & unites () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
template<typename _TYPE_, typename _TYPE_ARRAY_>
class IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >
Each processor has a sub_box of the global box, and echange_espace_virtuel(n) exchanges n layers of ghost cells, echange_espace_virtuel handles periodicity by copying the first layer into the ghost layer on the opposite side.
Constructor & Destructor Documentation
IJK_Field_template()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::IJK_Field_template () inline
Referenced by IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::duplique().
Member Function Documentation
taille_memoire()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > unsigned IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::taille_memoire () const inline override protected virtual
Reimplemented from IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >.
duplique()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > int IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::duplique () const inline override protected virtual
Reimplemented from IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >.
References Process::exit(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::IJK_Field_template(), and Objet_U::numero().
printOn()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > Sortie & IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::printOn (Sortie & s) const inline override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >.
readOn()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > Entree & IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::readOn (Entree & s) inline override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >.
allocate() [1/2]
template<typename _TYPE_ , typename _TYPE_ARRAY_ > void IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::allocate (const Domaine_IJK & d, Domaine_IJK::Localisation l, int ghost_size, int additional_k_layers = 0, int nb_compo = 1, const Nom & name = Nom())
Referenced by Postprocessing_IJK::alloc_fields(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::allocate(), Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::allocate_ephemere(), IJK_Composantes_Connex::allocate_fields(), Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::allocate_paresseux(), Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::allocate_persistant(), IJK_Composantes_Connex::associate_rising_velocities_parameters(), IJK_Interfaces::calculer_kappa_ft(), IJK_Thermals::compute_new_thermal_field(), Postprocessing_IJK::init_integrated_and_ana(), IJK_One_Dimensional_Subproblems_Interfaces_Fields::initialise(), Cut_cell_FT_Disc::initialise(), Navier_Stokes_FTD_IJK::initialise_ns_fields(), Probleme_FTD_IJK_base::initialize(), Multigrille_Adrien::initialize(), Fourier_trans::initialize(), IJK_Ghost_Fluid_Fields::initialize(), Intersection_Interface_ijk_cell::initialize(), IJK_Thermal_base::initialize(), IJK_Thermal_cut_cell::initialize(), IJK_Thermal_Multiple_Subresolutions::initialize(), IJK_Thermal_Onefluid::initialize(), IJK_Thermal_Subresolution::initialize(), IJK_Interfaces::initialize(), IJK_Test_Multigrille::interpreter(), IJK_Lata_Swap_JK::interpreter(), DNS_QC_double::run(), Parallel_io_parameters::run_bench_read(), and Parallel_io_parameters::run_bench_write().
allocate() [2/2]
template<typename _TYPE_ , typename _TYPE_ARRAY_ > void IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::allocate (const Domaine_IJK & d, Domaine_IJK::Localisation l, int ghost_size, const Nom & name) inline
References IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::allocate().
allocate_shear_BC()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > void IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::allocate_shear_BC (int monofluide, double rov, double rol, int use_inv_rho_in_pressure_solver = 0)
Referenced by Navier_Stokes_FTD_IJK::initialise_ns_fields(), and Multigrille_Adrien::initialize().
dumplata_scalar()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > virtual void IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::dumplata_scalar (const char * filename, int step) const virtual
Reimplemented in Cut_field_template< _TYPE_, _TYPE_ARRAY_ >, Cut_field_template< int, ArrOfInt >, and Cut_field_template< double, ArrOfDouble >.
Referenced by Postprocessing_IJK::postraiter_champs().
get_domaine()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > const Domaine_IJK & IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_domaine () const inline
References IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::domaine_ref_, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by IJK_Thermal_base::add_temperature_source(), Cut_cell_surface_efficace::calcul_delta_volume_theorique_bilan(), Couplage_Tubes_IBC::calcul_F_pression(), Couplage_Tubes_IBC::calcul_F_pression2(), IJK_Interfaces::calculer_aire_interfaciale(), IJK_Interfaces::calculer_aire_interfaciale_for_compo(), IJK_Interfaces::calculer_distance_autres_compo_connexe_ijk(), IJK_Thermal_base::calculer_flux_thermique_bord(), IJK_Interfaces::calculer_indicatrice(), IJK_Interfaces::calculer_indicatrice_optim(), IJK_Thermal_base::calculer_k_pour_bord(), IJK_Interfaces::calculer_kappa_ft(), Navier_Stokes_FTD_IJK::calculer_moyenne_de_phase_liq(), Navier_Stokes_FTD_IJK::calculer_moyenne_de_phase_vap(), DNS_QC_double::calculer_moyennes_flux(), IJK_Interfaces::calculer_normales_et_aires_interfaciales(), IJK_Interfaces::calculer_surface_interface(), IJK_Thermal_base::calculer_temperature_adim_bulles(), IJK_Thermal_base::calculer_temperature_adimensionnelle_theta(), IJK_Thermal_base::calculer_temperature_physique_T(), Navier_Stokes_FTD_IJK::calculer_vitesse_droite(), Navier_Stokes_FTD_IJK::calculer_vitesse_gauche(), IJK_Thermal_Subresolution::complete_field_thermal_wake_slice_ij_values(), Statistiques_dns_ijk::compute_and_store_gradU_cell(), Statistiques_dns_ijk::compute_and_store_scalar_product_face_to_face(), IJK_Interfaces::compute_bubbles_volume_and_barycentres(), IJK_Composantes_Connex::compute_compo_connex_from_interface(), IJK_Thermal_Onefluid::compute_dT_rustine(), Operateur_IJK_faces_base_double::compute_dtstab_convection_local(), IJK_Interfaces::compute_external_forces_color_function(), IJK_Thermal_base::compute_global_energy(), DNS_QC_double::compute_rho_bulk(), DNS_QC_double::compute_rho_t_bulk(), DebogIJK::compute_signature(), DNS_QC_double::compute_t_bulk(), IJK_Thermal_Onefluid::compute_T_rust(), Corrige_flux_FT_temperature_subresolution::compute_temperature_cell_centre_neighbours(), IJK_Thermal_Onefluid::compute_temperature_convection_conservative(), IJK_Thermal_Subresolution::enforce_periodic_temperature_boundary_value(), Statistiques_dns_ijk::face_to_cell_gradient(), Sonde_IJK::fill_local_values(), Schema_Temps_IJK_base::find_timestep(), DNS_QC_double::fixer_reference_pression(), Couplage_Tubes_IBC::force_ibc_velocity(), Couplage_Tubes_IBC::force_ibc_velocity_anticipe_cube(), Couplage_Tubes_IBC::force_ibc_velocity_frac_vol(), Couplage_Tubes_IBC::force_ibc_velocity_miroir(), Couplage_Tubes_IBC::force_ibc_velocity_symetrie_plane(), IJK_Thermal_base::force_upstream_temperature(), Couplage_Tubes_IBC::ibc0_force_cube(), Couplage_Tubes_IBC::ibc0_velocity_cube(), Couplage_Tubes_IBC::ibc_diffuse_force_cube(), Couplage_Tubes_IBC::ibc_diffuse_velocity_cube(), Couplage_Tubes_IBC::ibc_localisee_velocity_cube(), Couplage_Tubes_IBC::ibc_localisee_velocity_cube_qdm(), IJK_Thermal_base::imposer_flux_thermique_bord(), Postprocessing_IJK::init_indicatrice_non_perturbe(), Postprocessing_IJK::init_integrated_and_ana(), Corrige_flux_FT_temperature_subresolution::replace_temperature_cell_centre_neighbours(), DNS_QC_double::rk3_sub_step(), Corrige_flux_FT_temperature_subresolution::smooth_temperature_cell_centre_neighbours(), and IJK_Interfaces::update_indicatrice().
get_localisation()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > Domaine_IJK::Localisation IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_localisation () const inline
References IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::localisation_.
Referenced by Cut_cell_FT_Disc::initialise(), Postprocessing_IJK::postraiter_champs(), Cut_cell_FT_Disc::update(), and IJK_Interfaces::update_indicatrice().
echange_espace_virtuel()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > void IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel (int ghost)
Referenced by Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::add_from(), IJK_Thermal_cut_cell::add_temperature_diffusion(), IJK_Thermal_Onefluid::add_temperature_diffusion(), IJK_Composantes_Connex::allocate_fields(), IJK_Composantes_Connex::associate_rising_velocities_parameters(), Cut_cell_surface_efficace::calcul_delta_volume_theorique_bilan(), DNS_QC_double::calculer_convection_vitesse(), Navier_Stokes_FTD_IJK::calculer_dv(), IJK_Thermal_base::calculer_ecart_T_ana(), IJK_Interfaces::calculer_indicatrice_intermediaire(), ComputeValParCompoInCell::calculer_moy_par_compo(), IJK_Thermal_base::calculer_temperature_physique_T(), DNS_QC_double::calculer_turbulent_diffusion_vitesse(), DNS_QC_double::calculer_velocity_elem(), IJK_Thermal_Subresolution::clip_max_temperature_values(), IJK_Thermal_Subresolution::clip_min_temperature_values(), Statistiques_dns_ijk::compute_and_store_gradU_cell(), IJK_Composantes_Connex::compute_bounding_box_fill_compo_connex(), IJK_Composantes_Connex::compute_compo_connex_from_interface(), IJK_Ghost_Fluid_Fields::compute_eulerian_curvature(), IJK_Ghost_Fluid_Fields::compute_eulerian_curvature_from_interface(), IJK_Ghost_Fluid_Fields::compute_eulerian_distance(), IJK_Thermal_base::compute_eulerian_grad_T_interface(), IJK_Thermal_base::compute_eulerian_temperature_ghost(), Postprocessing_IJK::compute_extended_pressures(), Corrige_flux_FT_temperature_subresolution::compute_min_max_ijk_any_reachable_fluxes(), Corrige_flux_FT_temperature_subresolution::compute_min_max_ijk_reachable_fluxes(), IJK_Composantes_Connex::compute_rising_velocities(), Corrige_flux_FT_temperature_subresolution::compute_temperature_cell_centre_neighbours(), IJK_Thermal_Onefluid::compute_temperature_convection_conservative(), IJK_Thermal_base::compute_temperature_gradient_elem(), IJK_Thermal_Subresolution::correct_any_temperature_field_for_visu(), IJK_Thermal_Subresolution::correct_any_temperature_fields_for_eulerian_fluxes(), Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel(), IJK_Thermal_base::ecrire_statistiques_bulles(), IJK_Composantes_Connex::fill_mixed_cell_compo(), Navier_Stokes_FTD_IJK::fill_variable_source_and_potential_phi(), Postprocessing_IJK::get_IJK_field(), IJK_MonofluidVar::harmo(), DNS_QC_double::initialise(), IJK_One_Dimensional_Subproblems_Interfaces_Fields::initialise(), Navier_Stokes_FTD_IJK::initialise_ijk_fields(), Navier_Stokes_FTD_IJK::initialise_ns_fields(), IJK_Thermal_Subresolution::initialise_thermal_subproblems(), IJK_Ghost_Fluid_Fields::initialize(), IJK_Thermal_base::initialize(), IJK_Thermal_Subresolution::initialize(), IJK_Interfaces::initialize(), Navier_Stokes_FTD_IJK::maj_indicatrice_rho_mu(), IJK_MonofluidVar::operator()(), IJK_Thermal_cut_cell::perform_thermal_step(), DNS_QC_double::posttraiter_champs_instantanes(), IJK_Thermal_base::posttraiter_champs_instantanes_thermal_interface_ref(), Navier_Stokes_FTD_IJK::projeter(), IJK_Thermal_base::propagate_eulerian_grad_T_interface(), Corrige_flux_FT_temperature_subresolution::replace_temperature_cell_centre_neighbours(), IJK_One_Dimensional_Subproblems_Interfaces_Fields::retrieve_interfacial_surface_quantity(), DNS_QC_double::rk3_sub_step(), DNS_QC_double::run(), DNS_QC_double::sauvegarder_qc(), DNS_QC_double::save_raw_data(), Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::set_to_sum(), Multigrille_base::solve_ijk_in_storage_template(), IJK_Thermal_Subresolution::store_temperature_before_extrapolation(), Fourier_trans::update(), IJK_Interfaces::update_indicatrice(), IJK_Thermal_base::update_thermal_properties(), IJK_Thermal_cut_cell::update_thermal_properties(), IJK_Thermal_Onefluid::update_thermal_properties(), and Navier_Stokes_FTD_IJK::update_v_or_rhov().
interpolation_for_shear_periodicity_IJK_Field()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > _TYPE_ IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::interpolation_for_shear_periodicity_IJK_Field (const int send_j, const int send_k)
interpolation_for_shear_periodicity_I_sig_kappa()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > void IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::interpolation_for_shear_periodicity_I_sig_kappa (const int send_j, const int send_k_zmin, const int send_k_zmax, _TYPE_ Isigkappazmin, _TYPE_ Isigkappazmax)
redistribute_with_shear_domain_ft()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > void IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::redistribute_with_shear_domain_ft (const IJK_Field_double & input, double DU_perio, const int ft_extension)
ajouter_second_membre_shear_perio()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > void IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::ajouter_second_membre_shear_perio (IJK_Field_double & resu)
get_shear_BC_helpler() [1/2]
template<typename _TYPE_ , typename _TYPE_ARRAY_ > IJK_Shear_Periodic_helpler & IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_shear_BC_helpler () inline
References IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::shear_BC_helpler_.
Referenced by Navier_Stokes_FTD_IJK::complete_initialise_ijk_fields(), Navier_Stokes_FTD_IJK::initialise_ijk_fields(), and Navier_Stokes_FTD_IJK::update_indicatrice_variables_monofluides().
get_shear_BC_helpler() [2/2]
template<typename _TYPE_ , typename _TYPE_ARRAY_ > const IJK_Shear_Periodic_helpler & IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_shear_BC_helpler () const inline
References IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::shear_BC_helpler_.
increase_alloc_counter()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > static void IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::increase_alloc_counter (int i = 1) inline static
References IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::alloc_counter_.
alloc_counter()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > static int IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::alloc_counter () inline static
References IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::alloc_counter_.
exchange_data()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > void IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::exchange_data (int pe_imin_, int is, int js, int ks, int pe_imax_, int ir, int jr, int kr, int isz, int jsz, int ksz, double offset_i = 0., double jump_i = 0., int nb_ghost = 0) protected
alloc_counter_()
int IJK_Field_template< float, ArrOfFloat >::alloc_counter_ protected
Member Data Documentation
domaine_ref_
template<typename _TYPE_ , typename _TYPE_ARRAY_ > TRUST_Ref< Domaine_IJK *> IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::domaine_ref_ protected
Referenced by IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_domaine().
localisation_
template<typename _TYPE_ , typename _TYPE_ARRAY_ > Domaine_IJK::Localisation IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::localisation_ protected
Referenced by IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_localisation().
shear_BC_helpler_
template<typename _TYPE_ , typename _TYPE_ARRAY_ > IJK_Shear_Periodic_helpler IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::shear_BC_helpler_ protected
Referenced by IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_shear_BC_helpler().
alloc_counter_
template<typename _TYPE_ , typename _TYPE_ARRAY_ > int IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::alloc_counter_ static protected
To monitor how many field allocations we perform.
Referenced by IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::alloc_counter(), and IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::increase_alloc_counter().