TrioCFD: Fourier_trans Class Reference
Fourier_trans Class Reference
#include <Fourier_trans.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Fourier_trans()
Fourier_trans::Fourier_trans ()
References N_echantillons_.
~Fourier_trans()
Fourier_trans::~Fourier_trans ()
Member Function Documentation
cree_instance()
Objet_U * Fourier_trans::cree_instance () static
taille_memoire()
unsigned Fourier_trans::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Fourier_trans::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Fourier_trans::info () static
get_info()
const Type_info * Fourier_trans::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
Fourier_trans & Fourier_trans::self_cast (Objet_U & r) static
self_cast() [2/2]
const Fourier_trans & Fourier_trans::self_cast (const Objet_U & r) static
printOn()
Sortie & Fourier_trans::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
readOn()
Entree & Fourier_trans::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
sauvegarde()
void Fourier_trans::sauvegarde () const
References Domaine_IJK::get_local_slice_index(), N_echantillons_, post_splitting_, Sortie_Fichier_base::precision(), ref_ki, Sortie_Fichier_base::setf(), TFi_, TFx_, TFy_, and tri_ki.
Referenced by DNS_QC_double::sauvegarder_qc().
reprise()
void Fourier_trans::reprise ()
References Param::ajouter(), Domaine_IJK::get_local_slice_index(), Param::lire_avec_accolades(), N_echantillons_, post_splitting_, ref_ki, TRUSTArray< _TYPE_, _SIZE_ >::size_array(), TFi_, TFx_, TFy_, and tri_ki.
Referenced by initialize().
postraiter()
void Fourier_trans::postraiter (Nom & base) const
References Ecrire_entete(), Process::je_suis_maitre(), Process::me(), postraiter_TFi(), postraiter_TFx(), postraiter_TFy(), Sortie_Fichier_base::precision(), and Sortie_Fichier_base::setf().
Referenced by DNS_QC_double::run().
update()
void Fourier_trans::update (const IJK_Field_vector3_double & vitesse, const IJK_Field_double & pression, const IJK_Field_double & masse_vol, const IJK_Field_double & champ_mu)
References Avant_TF, Statistiques::begin_count(), champ_mu, dx_, dy_, IJK_Field_vector< T, N >::echange_espace_virtuel(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel(), Domaine_IJK::ELEM, Statistiques::end_count(), Domaine_IJK::get_nb_items_global(), Domaine_IJK::get_offset_local(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost(), Imag_TF, masse_vol, N_echantillons_, Statistiques::new_counter(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), nu_moy_, post_splitting_, pression, Redistribute_Field::redistribute(), redistribute_to_post_splitting_elem_, redistribute_to_post_splitting_faces_, Reel_TF, ref_ki, resultat_, rho_moy_, TRUSTArray< _TYPE_, _SIZE_ >::size_array(), tab_dz_, TFi_, TFx_, TFy_, Traitement_spectral(), Traitement_spectral_klayer_direct(), tri_ki, vit_moy_, and vitesse.
Referenced by DNS_QC_double::run().
initialize()
void Fourier_trans::initialize (const Domaine_IJK & split_origine, const Domaine_IJK & split, TRUST_Vector< ArrOfDouble > vmoy, ArrOfDouble rhomoy, ArrOfDouble numoy, const double T_KMAX, const double T_KMIN, int avec_reprise)
References IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::allocate(), Avant_TF, Statistiques::begin_count(), champ_mu, dx_, dy_, Domaine_IJK::ELEM, elem_coord_, Statistiques::end_count(), Domaine_IJK::FACES_I, Domaine_IJK::FACES_J, Domaine_IJK::FACES_K, Domaine_IJK::get_constant_delta(), Domaine_IJK::get_delta(), Domaine_IJK::get_nb_elem_local(), Domaine_IJK::get_nb_elem_tot(), Domaine_IJK::get_node_coordinates(), Imag_TF, in, Redistribute_Field::initialize(), inverseplan, masse_vol, Statistiques::new_counter(), nu_moy_, out, plan, post_splitting_, pression, redistribute_to_post_splitting_elem_, redistribute_to_post_splitting_faces_, Reel_TF, ref_ki, reprise(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), resultat_, rho_moy_, TRUSTArray< _TYPE_, _SIZE_ >::size_array(), tab_dz_, TCL_kmax_, TCL_kmin_, TFi_, TFx_, TFy_, tri_ki, vit_moy_, and vitesse.
Referenced by DNS_QC_double::initialise().
N_echantillons()
int Fourier_trans::N_echantillons () const inline
References N_echantillons_.
Traitement_spectral()
void Fourier_trans::Traitement_spectral (const IJK_Field_double & entree, IJK_Field_double & reel, IJK_Field_double & imag, int sens) protected
References Process::exit(), Domaine_IJK::get_nb_elem_local(), post_splitting_, Traitement_spectral_klayer_direct(), and Traitement_spectral_klayer_inverse().
Referenced by update().
Traitement_spectral_klayer_direct()
void Fourier_trans::Traitement_spectral_klayer_direct (const IJK_Field_double & entree, IJK_Field_double & reel, IJK_Field_double & imag, int k) protected
References Domaine_IJK::get_nb_elem_local(), in, out, plan, and post_splitting_.
Referenced by Traitement_spectral(), and update().
Traitement_spectral_klayer_inverse()
void Fourier_trans::Traitement_spectral_klayer_inverse (IJK_Field_double & reel, IJK_Field_double & imag, int k) protected
References Domaine_IJK::get_nb_elem_local(), in, inverseplan, out, and post_splitting_.
Referenced by Traitement_spectral().
Ecrire_entete()
void Fourier_trans::Ecrire_entete (Sortie & os, int flag_valeur_instantanee = 0) const protected
References Process::exit(), and N_echantillons_.
Referenced by postraiter().
postraiter_TFi()
void Fourier_trans::postraiter_TFi (Sortie & os, int flag_valeur_instantanee = 0) const protected
References elem_coord_, Domaine_IJK::get_nb_elem_local(), Domaine_IJK::get_offset_local(), N_echantillons_, post_splitting_, TRUSTArray< _TYPE_, _SIZE_ >::size_array(), TFi_, and tri_ki.
Referenced by postraiter().
postraiter_TFx()
void Fourier_trans::postraiter_TFx (Sortie & os, int flag_valeur_instantanee = 0) const protected
References elem_coord_, Domaine_IJK::get_nb_elem_local(), Domaine_IJK::get_nb_elem_tot(), Domaine_IJK::get_node_coordinates(), Domaine_IJK::get_offset_local(), Domaine_IJK::get_origin(), N_echantillons_, post_splitting_, and TFx_.
Referenced by postraiter().
postraiter_TFy()
void Fourier_trans::postraiter_TFy (Sortie & os, int flag_valeur_instantanee = 0) const protected
References elem_coord_, Domaine_IJK::get_nb_elem_local(), Domaine_IJK::get_nb_elem_tot(), Domaine_IJK::get_node_coordinates(), Domaine_IJK::get_offset_local(), Domaine_IJK::get_origin(), N_echantillons_, post_splitting_, and TFy_.
Referenced by postraiter().
Member Data Documentation
info_obj
const Type_info Fourier_trans::info_obj static
redistribute_to_post_splitting_faces_
FixedVector<Redistribute_Field, 3> Fourier_trans::redistribute_to_post_splitting_faces_ protected
Referenced by initialize(), and update().
redistribute_to_post_splitting_elem_
Redistribute_Field Fourier_trans::redistribute_to_post_splitting_elem_ protected
Referenced by initialize(), and update().
resultat_
FixedVector<IJK_Field_double, 27> Fourier_trans::resultat_ protected
Referenced by initialize(), and update().
post_splitting_
Domaine_IJK Fourier_trans::post_splitting_ protected
Referenced by initialize(), postraiter_TFi(), postraiter_TFx(), postraiter_TFy(), reprise(), sauvegarde(), Traitement_spectral(), Traitement_spectral_klayer_direct(), Traitement_spectral_klayer_inverse(), and update().
vit_moy_
TRUST_Vector< ArrOfDouble > Fourier_trans::vit_moy_ protected
Referenced by initialize(), and update().
rho_moy_
ArrOfDouble Fourier_trans::rho_moy_ protected
Referenced by initialize(), and update().
nu_moy_
ArrOfDouble Fourier_trans::nu_moy_ protected
Referenced by initialize(), and update().
TCL_kmax_
double Fourier_trans::TCL_kmax_ protected
Referenced by initialize().
TCL_kmin_
double Fourier_trans::TCL_kmin_ protected
Referenced by initialize().
plan
fftw_plan Fourier_trans::plan protected
Referenced by initialize(), and Traitement_spectral_klayer_direct().
inverseplan
fftw_plan Fourier_trans::inverseplan protected
Referenced by initialize(), and Traitement_spectral_klayer_inverse().
in
fftw_complex* Fourier_trans::in protected
Referenced by initialize(), Traitement_spectral_klayer_direct(), and Traitement_spectral_klayer_inverse().
out
fftw_complex* Fourier_trans::out protected
Referenced by initialize(), Traitement_spectral_klayer_direct(), and Traitement_spectral_klayer_inverse().
elem_coord_
ArrOfDouble Fourier_trans::elem_coord_ protected
Referenced by initialize(), postraiter_TFi(), postraiter_TFx(), and postraiter_TFy().
dx_
double Fourier_trans::dx_ protected
Referenced by initialize(), and update().
dy_
double Fourier_trans::dy_ protected
Referenced by initialize(), and update().
tab_dz_
ArrOfDouble Fourier_trans::tab_dz_ protected
Referenced by initialize(), and update().
moyenne_spatiale_instantanee_
TRUST_Vector< ArrOfDouble > Fourier_trans::moyenne_spatiale_instantanee_ protected
integrale_temporelle_
TRUST_Vector< ArrOfDouble > Fourier_trans::integrale_temporelle_ protected
N_echantillons_
int Fourier_trans::N_echantillons_ protected
Referenced by Ecrire_entete(), Fourier_trans(), N_echantillons(), postraiter_TFi(), postraiter_TFx(), postraiter_TFy(), reprise(), sauvegarde(), and update().
Avant_TF
FixedVector<IJK_Field_double, 86> Fourier_trans::Avant_TF protected
Referenced by initialize(), and update().
Reel_TF
FixedVector<IJK_Field_double, 86> Fourier_trans::Reel_TF protected
Referenced by initialize(), and update().
Imag_TF
FixedVector<IJK_Field_double, 86> Fourier_trans::Imag_TF protected
Referenced by initialize(), and update().
vitesse
IJK_Field_vector3_double Fourier_trans::vitesse protected
Referenced by initialize(), and update().
champ_mu
IJK_Field_double Fourier_trans::champ_mu protected
Referenced by initialize(), and update().
masse_vol
IJK_Field_double Fourier_trans::masse_vol protected
Referenced by initialize(), and update().
pression
IJK_Field_double Fourier_trans::pression protected
Referenced by initialize(), and update().
TFx_
TRUST_Vector< ArrOfDouble > Fourier_trans::TFx_ protected
Referenced by initialize(), postraiter_TFx(), reprise(), sauvegarde(), and update().
TFy_
TRUST_Vector< ArrOfDouble > Fourier_trans::TFy_ protected
Referenced by initialize(), postraiter_TFy(), reprise(), sauvegarde(), and update().
TFi_
TRUST_Vector< ArrOfDouble > Fourier_trans::TFi_ protected
Referenced by initialize(), postraiter_TFi(), reprise(), sauvegarde(), and update().
tri_ki
ArrOfDouble Fourier_trans::tri_ki protected
Referenced by initialize(), postraiter_TFi(), reprise(), sauvegarde(), and update().
ref_ki
IntTab Fourier_trans::ref_ki protected
Referenced by initialize(), reprise(), sauvegarde(), and update().