TrioCFD: Paroi_scal_hyd_base_VDF Class Reference
Paroi_scal_hyd_base_VDF Class Reference
#include <Paroi_scal_hyd_base_VDF.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Turbulence_paroi_scal_base
void associer_modele (const Modele_turbulence_scal_base &)
const Type_info * get_info () const override
void imprimer_nusselt_mean_only (Sortie &, int, const TRUST_List< Nom > &, const Nom &) const
void imprimer_premiere_ligne_nusselt (int, const TRUST_List< Nom > &, const Nom &) const
int reprendre (Entree &is) override
int sauvegarder (Sortie &os) const override
virtual bool use_equivalent_distance () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Turbulence_paroi_scal_base
static void typer_lire_turbulence_paroi_scal (TRUST_Deriv< Turbulence_paroi_scal_base > &, const Modele_turbulence_scal_base &, Entree &)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Paroi_scal_hyd_base_VDF()
Paroi_scal_hyd_base_VDF::Paroi_scal_hyd_base_VDF ()
~Paroi_scal_hyd_base_VDF()
Paroi_scal_hyd_base_VDF::~Paroi_scal_hyd_base_VDF () override
Member Function Documentation
info()
const Type_info * Paroi_scal_hyd_base_VDF::info () static
get_info()
const Type_info * Paroi_scal_hyd_base_VDF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Turbulence_paroi_scal_base.
Reimplemented in Loi_Paroi_Nu_Impose_VDF, Paroi_2couches_scal_VDF, Paroi_loi_WW_scal_VDF, Paroi_ODVM_scal_VDF, Paroi_std_scal_hyd_VDF, Loi_expert_scalaire_VDF, and Paroi_TBLE_scal_VDF.
self_cast() [1/2]
Paroi_scal_hyd_base_VDF & Paroi_scal_hyd_base_VDF::self_cast (Objet_U & r) static
self_cast() [2/2]
const Paroi_scal_hyd_base_VDF & Paroi_scal_hyd_base_VDF::self_cast (const Objet_U & r) static
printOn()
Sortie & Paroi_scal_hyd_base_VDF::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Turbulence_paroi_scal_base.
Reimplemented in Loi_Paroi_Nu_Impose_VDF, Paroi_2couches_scal_VDF, Paroi_loi_WW_scal_VDF, Paroi_ODVM_scal_VDF, Paroi_std_scal_hyd_VDF, Loi_expert_scalaire_VDF, and Paroi_TBLE_scal_VDF.
References Objet_U::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Paroi_scal_hyd_base_VDF::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Turbulence_paroi_scal_base.
Reimplemented in Loi_Paroi_Nu_Impose_VDF, Paroi_2couches_scal_VDF, Paroi_loi_WW_scal_VDF, Paroi_ODVM_scal_VDF, Paroi_std_scal_hyd_VDF, Loi_expert_scalaire_VDF, and Paroi_TBLE_scal_VDF.
associer()
void Paroi_scal_hyd_base_VDF::associer (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis) override virtual
Implements Turbulence_paroi_scal_base.
References init_lois_paroi(), Turbulence_paroi_scal_base::le_dom_Cl_dis_, and Turbulence_paroi_scal_base::le_dom_dis_.
init_lois_paroi()
int Paroi_scal_hyd_base_VDF::init_lois_paroi () override virtual
Implements Turbulence_paroi_scal_base.
Reimplemented in Paroi_loi_WW_scal_VDF, Paroi_ODVM_scal_VDF, Paroi_std_scal_hyd_VDF, and Paroi_TBLE_scal_VDF.
References Objet_U::axi, TRUST_Vector< _CLASSE_ >::dimensionner(), Domaine_VDF::dist_norm_bord(), Domaine_VDF::dist_norm_bord_axi(), Turbulence_paroi_scal_base::equivalent_distance_, Turbulence_paroi_scal_base::le_dom_Cl_dis_, Turbulence_paroi_scal_base::le_dom_dis_, Front_VF::nb_faces(), Turbulence_paroi_scal_base::nb_fields_, Domaine_dis_base::nb_front_Cl(), Front_VF::num_face(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUST_Vector< _CLASSE_ >::resize(), Turbulence_paroi_scal_base::tab_, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by associer(), Paroi_loi_WW_scal_VDF::init_lois_paroi(), and Paroi_std_scal_hyd_VDF::init_lois_paroi().
compute_nusselt()
void Paroi_scal_hyd_base_VDF::compute_nusselt () const override virtual
Implements Turbulence_paroi_scal_base.
References Objet_U::axi, Milieu_base::conductivite(), Domaine_VDF::dist_norm_bord(), Domaine_VDF::dist_norm_bord_axi(), Equation_base::domaine_Cl_dis(), Probleme_base::equation(), Turbulence_paroi_scal_base::equivalent_distance_, Domaine_VF::face_voisins(), Neumann::flux_impose(), Domaine_VF::front_VF(), Equation_base::inconnue(), Turbulence_paroi_scal_base::le_dom_Cl_dis_, Turbulence_paroi_scal_base::le_dom_dis_, Frontiere_dis_base::le_nom(), Domaine_Cl_dis_base::les_conditions_limites(), Equation_base::milieu(), Turbulence_paroi_scal_base::mon_modele_turb_scal, Field_base::nb_comp(), Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_local_face(), Front_VF::num_premiere_face(), Equation_base::probleme(), Turbulence_paroi_scal_base::tab_, TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), and Champ_Inc_base::valeurs().
Referenced by imprimer_nusselt().
imprimer_nusselt()
void Paroi_scal_hyd_base_VDF::imprimer_nusselt (Sortie & os) const override virtual
Reimplemented from Turbulence_paroi_scal_base.
Reimplemented in Loi_Paroi_Nu_Impose_VDF, and Paroi_TBLE_scal_VDF.
References compute_nusselt(), Objet_U::dimension, Equation_base::domaine_Cl_dis(), Probleme_base::equation(), Domaine_VF::face_voisins(), Process::je_suis_maitre(), Turbulence_paroi_scal_base::le_dom_Cl_dis_, Turbulence_paroi_scal_base::le_dom_dis_, Frontiere_dis_base::le_nom(), Domaine_Cl_dis_base::les_conditions_limites(), Turbulence_paroi_scal_base::mon_modele_turb_scal, Front_VF::nb_faces(), Turbulence_paroi_scal_base::nb_fields_, Domaine_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), Turbulence_paroi_scal_base::ouvrir_fichier_partage(), Equation_base::probleme(), EcrFicPartage::syncfile(), Turbulence_paroi_scal_base::tab_, TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), and Domaine_VF::xv().
Referenced by Paroi_TBLE_scal_VDF::imprimer_nusselt().
equivalent_distance_name()
DoubleVect & Paroi_scal_hyd_base_VDF::equivalent_distance_name (DoubleVect & d_equiv, const Nom & nom_bord) const override virtual
Implements Turbulence_paroi_scal_base.
References Turbulence_paroi_scal_base::equivalent_distance(), Turbulence_paroi_scal_base::le_dom_dis_, Frontiere_dis_base::le_nom(), Front_VF::nb_faces(), and TRUSTVect< _TYPE_, _SIZE_ >::resize().
Member Data Documentation
info_obj
const Type_info Paroi_scal_hyd_base_VDF::info_obj static
nb_impr_
int Paroi_scal_hyd_base_VDF::nb_impr_ = -123 mutable protected