TrioCFD: IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ > Class Template Reference
IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ > Class Template Reference
#include <IJK_Field_local_template.h>
Protected Member Functions
Sortie & printOn (Sortie &os) const override
Entree & readOn (Entree &is) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Public Member Functions inherited from Field_base
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
virtual void fixer_nb_comp (int i)
virtual const Nom & fixer_nom_compo (const Nom &)
virtual const Nom & fixer_nom_compo (int, const Nom &)
virtual const Noms & fixer_noms_compo (const Noms &)
virtual const Nom & fixer_unite (const Nom &)
virtual const Nom & fixer_unite (int i, const Nom &)
virtual const Noms & fixer_unites (const Noms &)
const Type_info * get_info () const override
const Nom & nom_compo (int) const
void nommer (const Nom &) override
const Nom & unite () const
const Nom & unite (int) const
const Noms & unites () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
template<typename _TYPE_, typename _TYPE_ARRAY_>
class IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >
The scalar field can be accessed by
field(i,j,k) with "-ghost() <= i < ni() + ghost()", same for j and k
field.data()[linear_index(i,j,k)]
Inherits from Field_base to have access to all the naming logic.
Constructor & Destructor Documentation
IJK_Field_local_template()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::IJK_Field_local_template () inline
References Field_base::fixer_nb_comp().
Referenced by IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::duplique().
Member Function Documentation
taille_memoire()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > unsigned IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::taille_memoire () const inline override protected virtual
Implements Objet_U.
Reimplemented in IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >.
duplique()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > int IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::duplique () const inline override protected virtual
Implements Objet_U.
Reimplemented in IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >.
References Process::exit(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::IJK_Field_local_template(), and Objet_U::numero().
printOn()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > Sortie & IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::printOn (Sortie & s) const inline override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Field_base.
Reimplemented in IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >.
readOn()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > Entree & IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::readOn (Entree & s) inline override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Field_base.
Reimplemented in IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >.
allocate()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > void IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::allocate (int ni, int nj, int nk, int ghosts, int additional_k_layers = 0, int nb_compo = 1, bool external_storage = false)
Referenced by Operateur_IJK_elem_conv_base_double::ajouter(), IJK_Shear_Periodic_helpler::allocate(), Operateur_IJK_elem_conv_base_double::calculer(), IJK_Thermal_base::calculer_flux_thermique_bord(), OpGradQuickIJKScalar_double::calculer_grad(), OpGradQuickIJKScalar_double::calculer_grad_x(), OpGradQuickIJKScalar_double::calculer_grad_y(), OpGradQuickIJKScalar_double::calculer_grad_z(), Corrige_flux_FT_temperature_subresolution::compute_cell_neighbours_mixed_cell_faces_indices_to_correct(), Operateur_IJK_elem_base_double::compute_grad(), Operateur_IJK_elem_base_double::compute_grad_x(), Operateur_IJK_elem_base_double::compute_grad_y(), Operateur_IJK_elem_base_double::compute_grad_z(), and IJK_Thermal_base::imposer_flux_thermique_bord().
shift_k_origin()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > void IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::shift_k_origin (int n)
Referenced by Multigrille_base::solve_ijk_in_storage_template().
ref_ij()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > void IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ref_ij (IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ > & src, int k_layer)
Referenced by Operateur_IJK_elem_base_double::compute_grad_x(), and Operateur_IJK_elem_base_double::compute_grad_y().
linear_index() [1/2]
template<typename _TYPE_ , typename _TYPE_ARRAY_ > int IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::linear_index (int i, int j, int k) const inline
References IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::compo_stride_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost_size_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::j_stride_, Field_base::nb_compo_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk_, and IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::offset_.
Referenced by IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::operator()().
linear_index() [2/2]
template<typename _TYPE_ , typename _TYPE_ARRAY_ > int IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::linear_index (int i, int j, int k, int compo) const inline
References IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::compo_stride_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost_size_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::j_stride_, Field_base::nb_compo_, and IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::offset_.
operator()() [1/4]
template<typename _TYPE_ , typename _TYPE_ARRAY_ > _TYPE_ & IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::operator() (int i, int j, int k) inline
References IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::data_, and IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::linear_index().
Referenced by Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::operator()(), and Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::pure_().
operator()() [2/4]
template<typename _TYPE_ , typename _TYPE_ARRAY_ > const _TYPE_ & IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::operator() (int i, int j, int k) const inline
References IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::data_, and IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::linear_index().
operator()() [3/4]
template<typename _TYPE_ , typename _TYPE_ARRAY_ > _TYPE_ & IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::operator() (int i, int j, int k, int compo) inline
References IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::data_, and IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::linear_index().
operator()() [4/4]
template<typename _TYPE_ , typename _TYPE_ARRAY_ > const _TYPE_ & IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::operator() (int i, int j, int k, int compo) const inline
References IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::data_, and IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::linear_index().
linear_index_relaxed_test() [1/2]
template<typename _TYPE_ , typename _TYPE_ARRAY_ > int IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::linear_index_relaxed_test (int i, int j, int k) const inline
References IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::additional_k_layers_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::compo_stride_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::data_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost_size_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::j_stride_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::k_layer_shift_, Field_base::nb_compo_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk_, and IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::offset_.
Referenced by IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::get_in_allocated_area().
linear_index_relaxed_test() [2/2]
template<typename _TYPE_ , typename _TYPE_ARRAY_ > int IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::linear_index_relaxed_test (int i, int j, int k, int compo) const inline
References IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::additional_k_layers_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::compo_stride_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::data_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost_size_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::j_stride_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::k_layer_shift_, Field_base::nb_compo_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk_, and IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::offset_.
get_in_allocated_area() [1/4]
template<typename _TYPE_ , typename _TYPE_ARRAY_ > _TYPE_ & IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::get_in_allocated_area (int i, int j, int k) inline
References IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::data_, and IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::linear_index_relaxed_test().
get_in_allocated_area() [2/4]
template<typename _TYPE_ , typename _TYPE_ARRAY_ > const _TYPE_ & IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::get_in_allocated_area (int i, int j, int k) const inline
References IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::data_, and IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::linear_index_relaxed_test().
get_in_allocated_area() [3/4]
template<typename _TYPE_ , typename _TYPE_ARRAY_ > _TYPE_ & IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::get_in_allocated_area (int i, int j, int k, int compo) inline
References IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::data_, and IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::linear_index_relaxed_test().
get_in_allocated_area() [4/4]
template<typename _TYPE_ , typename _TYPE_ARRAY_ > const _TYPE_ & IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::get_in_allocated_area (int i, int j, int k, int compo) const inline
References IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::data_, and IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::linear_index_relaxed_test().
k_layer() [1/4]
template<typename _TYPE_ , typename _TYPE_ARRAY_ > _TYPE_ * IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::k_layer (int k) inline
References IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::compo_stride_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::data_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost_size_, Field_base::nb_compo_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk_, and IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::offset_.
k_layer() [2/4]
template<typename _TYPE_ , typename _TYPE_ARRAY_ > const _TYPE_ * IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::k_layer (int k) const inline
References IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::compo_stride_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::data_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost_size_, Field_base::nb_compo_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk_, and IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::offset_.
k_layer() [3/4]
template<typename _TYPE_ , typename _TYPE_ARRAY_ > _TYPE_ * IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::k_layer (int k, int compo) inline
References IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::compo_stride_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::data_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost_size_, Field_base::nb_compo_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk_, and IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::offset_.
k_layer() [4/4]
template<typename _TYPE_ , typename _TYPE_ARRAY_ > const _TYPE_ * IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::k_layer (int k, int compo) const inline
References IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::compo_stride_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::data_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost_size_, Field_base::nb_compo_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk_, and IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::offset_.
ni()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > int IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni () const inline
References IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni_.
Referenced by Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::add_from(), Operateur_IJK_elem_conv_base_double::ajouter(), Cut_cell_surface_efficace::calcul_delta_volume_theorique_bilan(), Couplage_Tubes_IBC::calcul_F_pression(), Couplage_Tubes_IBC::calcul_F_pression2(), DNS_QC_double::calcul_p_thermo_et_bilan(), Intersection_Interface_ijk_cell::calcul_projection_centre_sur_interface_moy(), Operateur_IJK_elem_conv_base_double::calculer(), IJK_Thermal_base::calculer_dT(), Navier_Stokes_FTD_IJK::calculer_dv(), IJK_Thermal_base::calculer_ecart_T_ana(), IJK_Thermal_base::calculer_energies(), IJK_Thermal_base::calculer_flux_thermique_bord(), OpGradQuickIJKScalar_double::calculer_grad(), OpGradQuickIJKScalar_double::calculer_grad_x(), OpGradQuickIJKScalar_double::calculer_grad_y(), OpGradQuickIJKScalar_double::calculer_grad_z(), IJK_Interfaces::calculer_indicatrice(), IJK_Interfaces::calculer_indicatrice_optim(), IJK_Interfaces::calculer_kappa_ft(), Navier_Stokes_FTD_IJK::calculer_moyenne_de_phase_liq(), Navier_Stokes_FTD_IJK::calculer_moyenne_de_phase_vap(), IJK_Interfaces::calculer_normales_et_aires_interfaciales(), IJK_Thermal_base::calculer_source_temperature_ana(), IJK_Interfaces::calculer_surface_interface(), IJK_Thermal_base::calculer_temperature_adim_bulles(), IJK_Thermal_base::calculer_temperature_adimensionnelle_theta(), IJK_Interfaces::calculer_var_volume_remaillage(), DNS_QC_double::calculer_velocity_elem(), Navier_Stokes_FTD_IJK::calculer_vitesse_droite(), Navier_Stokes_FTD_IJK::calculer_vitesse_gauche(), IJK_Thermal_Subresolution::clip_max_temperature_values(), IJK_Thermal_Subresolution::clip_min_temperature_values(), Corrige_flux_FT_temperature_subresolution::combine_all_fluxes_from_outisde_frontier_on_procs(), Corrige_flux_FT_temperature_subresolution::combine_fluxes_from_frontier_on_procs(), IJK_Thermal_Subresolution::compare_temperature_fields(), IJK_Thermal_Subresolution::complete_field_thermal_wake_slice_ij_values(), Navier_Stokes_FTD_IJK::compute_and_add_qdm_corrections(), Navier_Stokes_FTD_IJK::compute_and_add_qdm_corrections_monophasic(), IJK_Composantes_Connex::compute_compo_connex_from_interface(), Operateur_IJK_elem_conv_base_double::compute_curv_fram(), IJK_Thermal_Onefluid::compute_diffusion_increment(), IJK_Thermal_Subresolution::compute_diffusion_increment(), IJK_Thermal_Onefluid::compute_dT_rustine(), IJK_Thermal_base::compute_global_energy(), Operateur_IJK_elem_base_double::compute_grad_x(), Operateur_IJK_elem_base_double::compute_grad_y(), Operateur_IJK_elem_base_double::compute_grad_z(), IJK_Thermal_Subresolution::compute_mean_liquid_temperature(), DNS_QC_double::compute_rho_bulk(), DNS_QC_double::compute_rho_t_bulk(), DebogIJK::compute_signature(), DNS_QC_double::compute_t_bulk(), IJK_Thermal_Onefluid::compute_T_rust(), Corrige_flux_FT_temperature_subresolution::compute_temperature_cell_centre_neighbours(), IJK_Thermal_base::compute_temperature_convection(), IJK_Thermal_Onefluid::compute_temperature_convection_conservative(), ConstIJK_ptr< _TYPE_, _TYPE_ARRAY_ >::ConstIJK_ptr(), Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::copy_from(), IJK_Thermal_Subresolution::correct_any_temperature_field_for_visu(), IJK_Thermal_Subresolution::correct_any_temperature_fields_for_eulerian_fluxes(), Operateur_IJK_elem_base_double::correct_flux(), IJK_Thermal_Subresolution::correct_operators_for_visu(), IJK_Thermal_Subresolution::correct_temperature_increment_for_interface_leaving_cell(), IJK_Thermal_Multiple_Subresolutions::correct_temperature_vapour_for_eulerian_fluxes(), Corrige_flux_FT_temperature_conv::corrige_flux_faceIJ(), IJK_Thermal_Subresolution::enforce_periodic_temperature_boundary_value(), Navier_Stokes_FTD_IJK::euler_explicit_update(), IJK_Thermal_Subresolution::evaluate_total_liquid_absolute_parameter(), IJK_Thermal_Subresolution::evaluate_total_liquid_parameter_squared(), OpGradCentre2IJKScalar_double::fill_grad_field_x_y_(), OpGradFluxCentre2IJKScalar_double::fill_grad_field_x_y_(), OpGradQuickIJKScalar_double::fill_grad_field_x_y_(), OpGradFluxQuickIJKScalar_double::fill_grad_field_x_y_(), OpHessCentre2IJKScalar_double::fill_grad_field_x_y_(), OpHessFluxCentre2IJKScalar_double::fill_grad_field_x_y_(), OpGradCentre2IJKScalar_double::fill_grad_field_z_(), OpGradQuickIJKScalar_double::fill_grad_field_z_(), OpHessCentre2IJKScalar_double::fill_grad_field_z_(), Sonde_IJK::fill_local_values(), IJK_Composantes_Connex::fill_mixed_cell_compo(), Postprocessing_IJK::fill_surface_force(), Schema_Temps_IJK_base::find_timestep(), DNS_QC_double::fixer_reference_pression(), Couplage_Tubes_IBC::force_ibc_velocity(), Couplage_Tubes_IBC::force_ibc_velocity_anticipe_cube(), Couplage_Tubes_IBC::force_ibc_velocity_frac_vol(), Couplage_Tubes_IBC::force_ibc_velocity_miroir(), Couplage_Tubes_IBC::force_ibc_velocity_symetrie_plane(), IJK_Thermal_base::force_upstream_temperature(), Postprocessing_IJK::get_IJK_field(), Postprocessing_IJK::get_update_lambda2_and_rot_and_Q(), Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::get_value_location(), IJK_MonofluidVar::harmo(), Couplage_Tubes_IBC::ibc0_force_cube(), Couplage_Tubes_IBC::ibc0_velocity_cube(), Couplage_Tubes_IBC::ibc_diffuse_force_cube(), Couplage_Tubes_IBC::ibc_diffuse_velocity_cube(), Couplage_Tubes_IBC::ibc_localisee_velocity_cube(), Couplage_Tubes_IBC::ibc_localisee_velocity_cube_qdm(), IJK_Thermal_base::imposer_flux_thermique_bord(), DNS_QC_double::initialise(), IJK_Lata_Swap_JK::interpreter(), IJK_Interfaces::mean_over_compo(), IJK_MonofluidVar::operator()(), Operateur_IJK_faces_base_double::Operator_IJK_div(), Operateur_IJK_elem_base_double::Operator_IJK_div(), Navier_Stokes_FTD_IJK::projeter(), Corrige_flux_FT_temperature_subresolution::replace_temperature_cell_centre_neighbours(), DNS_QC_double::rk3_sub_step(), IJK_Shear_Periodic_helpler::set_I_sig_kappa_zmax_(), IJK_Shear_Periodic_helpler::set_I_sig_kappa_zmin_(), IJK_Shear_Periodic_helpler::set_indicatrice_ghost_zmax_(), IJK_Shear_Periodic_helpler::set_indicatrice_ghost_zmin_(), Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::set_to_sum(), Operateur_IJK_elem_conv_base_double::shift_curv_fram(), Multigrille_base::solve_ijk_in_storage_template(), Corrige_flux_FT_temperature_subresolution::sort_ijk_intersections_subproblems_indices_fluxes_by_k_layers(), Corrige_flux_FT_temperature_subresolution::store_any_cell_faces_corrected(), IJK_Thermal_Subresolution::store_temperature_before_extrapolation(), Switch_double::switch_scalar_field(), Navier_Stokes_FTD_IJK::terme_source_gravite(), DNS_QC_double::translation_pression(), Fourier_trans::update(), IJK_Interfaces::update_indicatrice(), IJK_Thermal_base::update_thermal_properties(), IJK_Thermal_cut_cell::update_thermal_properties(), IJK_Thermal_Onefluid::update_thermal_properties(), and Cut_cell_double::verify_consistency_within_layer().
nj()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > int IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj () const inline
References IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj_.
Referenced by Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::add_from(), Operateur_IJK_elem_conv_base_double::ajouter(), Cut_cell_surface_efficace::calcul_delta_volume_theorique_bilan(), Couplage_Tubes_IBC::calcul_F_pression(), Couplage_Tubes_IBC::calcul_F_pression2(), DNS_QC_double::calcul_p_thermo_et_bilan(), Intersection_Interface_ijk_cell::calcul_projection_centre_sur_interface_moy(), Operateur_IJK_elem_conv_base_double::calculer(), IJK_Thermal_base::calculer_dT(), Navier_Stokes_FTD_IJK::calculer_dv(), IJK_Thermal_base::calculer_ecart_T_ana(), IJK_Thermal_base::calculer_energies(), IJK_Thermal_base::calculer_flux_thermique_bord(), OpGradQuickIJKScalar_double::calculer_grad(), OpGradQuickIJKScalar_double::calculer_grad_x(), OpGradQuickIJKScalar_double::calculer_grad_y(), OpGradQuickIJKScalar_double::calculer_grad_z(), IJK_Interfaces::calculer_indicatrice(), IJK_Interfaces::calculer_indicatrice_optim(), IJK_Interfaces::calculer_kappa_ft(), Navier_Stokes_FTD_IJK::calculer_moyenne_de_phase_liq(), Navier_Stokes_FTD_IJK::calculer_moyenne_de_phase_vap(), IJK_Interfaces::calculer_normales_et_aires_interfaciales(), IJK_Thermal_base::calculer_source_temperature_ana(), IJK_Interfaces::calculer_surface_interface(), IJK_Thermal_base::calculer_temperature_adim_bulles(), IJK_Thermal_base::calculer_temperature_adimensionnelle_theta(), IJK_Interfaces::calculer_var_volume_remaillage(), DNS_QC_double::calculer_velocity_elem(), Navier_Stokes_FTD_IJK::calculer_vitesse_droite(), Navier_Stokes_FTD_IJK::calculer_vitesse_gauche(), IJK_Thermal_Subresolution::clip_max_temperature_values(), IJK_Thermal_Subresolution::clip_min_temperature_values(), Corrige_flux_FT_temperature_subresolution::combine_all_fluxes_from_outisde_frontier_on_procs(), Corrige_flux_FT_temperature_subresolution::combine_fluxes_from_frontier_on_procs(), IJK_Thermal_Subresolution::compare_temperature_fields(), IJK_Thermal_Subresolution::complete_field_thermal_wake_slice_ij_values(), Navier_Stokes_FTD_IJK::compute_and_add_qdm_corrections(), Navier_Stokes_FTD_IJK::compute_and_add_qdm_corrections_monophasic(), IJK_Composantes_Connex::compute_compo_connex_from_interface(), Operateur_IJK_elem_conv_base_double::compute_curv_fram(), IJK_Thermal_Onefluid::compute_diffusion_increment(), IJK_Thermal_Subresolution::compute_diffusion_increment(), IJK_Thermal_Onefluid::compute_dT_rustine(), IJK_Thermal_base::compute_global_energy(), Operateur_IJK_elem_base_double::compute_grad_x(), Operateur_IJK_elem_base_double::compute_grad_y(), Operateur_IJK_elem_base_double::compute_grad_z(), IJK_Thermal_Subresolution::compute_mean_liquid_temperature(), DNS_QC_double::compute_rho_bulk(), DNS_QC_double::compute_rho_t_bulk(), DebogIJK::compute_signature(), DNS_QC_double::compute_t_bulk(), IJK_Thermal_Onefluid::compute_T_rust(), Corrige_flux_FT_temperature_subresolution::compute_temperature_cell_centre_neighbours(), IJK_Thermal_base::compute_temperature_convection(), IJK_Thermal_Onefluid::compute_temperature_convection_conservative(), ConstIJK_ptr< _TYPE_, _TYPE_ARRAY_ >::ConstIJK_ptr(), Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::copy_from(), IJK_Thermal_Subresolution::correct_any_temperature_field_for_visu(), IJK_Thermal_Subresolution::correct_any_temperature_fields_for_eulerian_fluxes(), Operateur_IJK_elem_base_double::correct_flux(), IJK_Thermal_Subresolution::correct_operators_for_visu(), IJK_Thermal_Subresolution::correct_temperature_increment_for_interface_leaving_cell(), IJK_Thermal_Multiple_Subresolutions::correct_temperature_vapour_for_eulerian_fluxes(), Corrige_flux_FT_temperature_conv::corrige_flux_faceIJ(), IJK_Thermal_Subresolution::enforce_periodic_temperature_boundary_value(), Navier_Stokes_FTD_IJK::euler_explicit_update(), IJK_Thermal_Subresolution::evaluate_total_liquid_absolute_parameter(), IJK_Thermal_Subresolution::evaluate_total_liquid_parameter_squared(), OpGradCentre2IJKScalar_double::fill_grad_field_x_y_(), OpGradFluxCentre2IJKScalar_double::fill_grad_field_x_y_(), OpGradQuickIJKScalar_double::fill_grad_field_x_y_(), OpGradFluxQuickIJKScalar_double::fill_grad_field_x_y_(), OpHessCentre2IJKScalar_double::fill_grad_field_x_y_(), OpHessFluxCentre2IJKScalar_double::fill_grad_field_x_y_(), OpGradCentre2IJKScalar_double::fill_grad_field_z_(), OpGradQuickIJKScalar_double::fill_grad_field_z_(), OpHessCentre2IJKScalar_double::fill_grad_field_z_(), IJK_Composantes_Connex::fill_mixed_cell_compo(), Postprocessing_IJK::fill_surface_force(), Schema_Temps_IJK_base::find_timestep(), DNS_QC_double::fixer_reference_pression(), Couplage_Tubes_IBC::force_ibc_velocity(), Couplage_Tubes_IBC::force_ibc_velocity_anticipe_cube(), Couplage_Tubes_IBC::force_ibc_velocity_frac_vol(), Couplage_Tubes_IBC::force_ibc_velocity_miroir(), Couplage_Tubes_IBC::force_ibc_velocity_symetrie_plane(), IJK_Thermal_base::force_upstream_temperature(), Postprocessing_IJK::get_IJK_field(), Postprocessing_IJK::get_update_lambda2_and_rot_and_Q(), Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::get_value_location(), IJK_MonofluidVar::harmo(), Couplage_Tubes_IBC::ibc0_force_cube(), Couplage_Tubes_IBC::ibc0_velocity_cube(), Couplage_Tubes_IBC::ibc_diffuse_force_cube(), Couplage_Tubes_IBC::ibc_diffuse_velocity_cube(), Couplage_Tubes_IBC::ibc_localisee_velocity_cube(), Couplage_Tubes_IBC::ibc_localisee_velocity_cube_qdm(), IJK_Thermal_base::imposer_flux_thermique_bord(), DNS_QC_double::initialise(), IJK_Lata_Swap_JK::interpreter(), IJK_Interfaces::mean_over_compo(), IJK_MonofluidVar::operator()(), Operateur_IJK_faces_base_double::Operator_IJK_div(), Operateur_IJK_elem_base_double::Operator_IJK_div(), Navier_Stokes_FTD_IJK::projeter(), Corrige_flux_FT_temperature_subresolution::replace_temperature_cell_centre_neighbours(), DNS_QC_double::rk3_sub_step(), IJK_Shear_Periodic_helpler::set_I_sig_kappa_zmax_(), IJK_Shear_Periodic_helpler::set_I_sig_kappa_zmin_(), IJK_Shear_Periodic_helpler::set_indicatrice_ghost_zmax_(), IJK_Shear_Periodic_helpler::set_indicatrice_ghost_zmin_(), Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::set_to_sum(), Operateur_IJK_elem_conv_base_double::shift_curv_fram(), Multigrille_base::solve_ijk_in_storage_template(), Corrige_flux_FT_temperature_subresolution::sort_ijk_intersections_subproblems_indices_fluxes_by_k_layers(), Corrige_flux_FT_temperature_subresolution::store_any_cell_faces_corrected(), IJK_Thermal_Subresolution::store_temperature_before_extrapolation(), Switch_double::switch_scalar_field(), Navier_Stokes_FTD_IJK::terme_source_gravite(), DNS_QC_double::translation_pression(), Fourier_trans::update(), IJK_Interfaces::update_indicatrice(), IJK_Thermal_base::update_thermal_properties(), IJK_Thermal_cut_cell::update_thermal_properties(), IJK_Thermal_Onefluid::update_thermal_properties(), and Cut_cell_double::verify_consistency_within_layer().
nk()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > int IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk () const inline
References IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk_.
Referenced by Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::add_from(), Operateur_IJK_elem_conv_base_double::ajouter(), Cut_cell_surface_efficace::calcul_delta_volume_theorique_bilan(), Couplage_Tubes_IBC::calcul_F_pression(), Couplage_Tubes_IBC::calcul_F_pression2(), Intersection_Interface_ijk_cell::calcul_projection_centre_sur_interface_moy(), Operateur_IJK_elem_conv_base_double::calculer(), IJK_Thermal_base::calculer_dT(), IJK_Thermal_base::calculer_ecart_T_ana(), IJK_Thermal_base::calculer_energies(), IJK_Interfaces::calculer_indicatrice(), IJK_Interfaces::calculer_indicatrice_optim(), IJK_Thermal_base::calculer_k_pour_bord(), IJK_Interfaces::calculer_kappa_ft(), Navier_Stokes_FTD_IJK::calculer_moyenne_de_phase_liq(), Navier_Stokes_FTD_IJK::calculer_moyenne_de_phase_vap(), IJK_Interfaces::calculer_normales_et_aires_interfaciales(), IJK_Thermal_base::calculer_source_temperature_ana(), IJK_Interfaces::calculer_surface_interface(), IJK_Thermal_base::calculer_temperature_adim_bulles(), IJK_Thermal_base::calculer_temperature_adimensionnelle_theta(), IJK_Interfaces::calculer_var_volume_remaillage(), DNS_QC_double::calculer_velocity_elem(), Navier_Stokes_FTD_IJK::calculer_vitesse_droite(), IJK_Thermal_Subresolution::clip_max_temperature_values(), IJK_Thermal_Subresolution::clip_min_temperature_values(), Corrige_flux_FT_temperature_subresolution::combine_all_fluxes_from_outisde_frontier_on_procs(), Corrige_flux_FT_temperature_subresolution::combine_fluxes_from_frontier_on_procs(), IJK_Thermal_Subresolution::compare_temperature_fields(), IJK_Thermal_Subresolution::complete_field_thermal_wake_slice_ij_values(), Navier_Stokes_FTD_IJK::complete_initialise_ijk_fields(), Navier_Stokes_FTD_IJK::compute_and_add_qdm_corrections(), Navier_Stokes_FTD_IJK::compute_and_add_qdm_corrections_monophasic(), IJK_Composantes_Connex::compute_compo_connex_from_interface(), IJK_Thermal_Onefluid::compute_diffusion_increment(), IJK_Thermal_Subresolution::compute_diffusion_increment(), IJK_Thermal_Onefluid::compute_dT_rustine(), IJK_Thermal_base::compute_global_energy(), Operateur_IJK_elem_base_double::compute_grad_x(), Operateur_IJK_elem_base_double::compute_grad_y(), Operateur_IJK_elem_base_double::compute_grad_z(), IJK_Thermal_Subresolution::compute_mean_liquid_temperature(), DNS_QC_double::compute_rho_bulk(), DNS_QC_double::compute_rho_t_bulk(), DebogIJK::compute_signature(), DNS_QC_double::compute_t_bulk(), IJK_Thermal_Onefluid::compute_T_rust(), Corrige_flux_FT_temperature_subresolution::compute_temperature_cell_centre_neighbours(), IJK_Thermal_base::compute_temperature_convection(), IJK_Thermal_Onefluid::compute_temperature_convection_conservative(), ConstIJK_ptr< _TYPE_, _TYPE_ARRAY_ >::ConstIJK_ptr(), Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::copy_from(), IJK_Thermal_Subresolution::correct_any_temperature_field_for_visu(), IJK_Thermal_Subresolution::correct_any_temperature_fields_for_eulerian_fluxes(), IJK_Thermal_Subresolution::correct_operators_for_visu(), IJK_Thermal_Subresolution::correct_temperature_increment_for_interface_leaving_cell(), IJK_Thermal_Multiple_Subresolutions::correct_temperature_vapour_for_eulerian_fluxes(), IJK_Thermal_Subresolution::enforce_periodic_temperature_boundary_value(), Navier_Stokes_FTD_IJK::euler_time_step(), IJK_Thermal_Subresolution::evaluate_total_liquid_absolute_parameter(), IJK_Thermal_Subresolution::evaluate_total_liquid_parameter_squared(), IJK_Composantes_Connex::fill_mixed_cell_compo(), Postprocessing_IJK::fill_surface_force(), Schema_Temps_IJK_base::find_timestep(), DNS_QC_double::fixer_reference_pression(), Couplage_Tubes_IBC::force_ibc_velocity(), Couplage_Tubes_IBC::force_ibc_velocity_anticipe_cube(), Couplage_Tubes_IBC::force_ibc_velocity_frac_vol(), Couplage_Tubes_IBC::force_ibc_velocity_miroir(), Couplage_Tubes_IBC::force_ibc_velocity_symetrie_plane(), IJK_Thermal_base::force_upstream_temperature(), Postprocessing_IJK::get_IJK_field(), Postprocessing_IJK::get_update_lambda2_and_rot_and_Q(), Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::get_value_location(), IJK_MonofluidVar::harmo(), Couplage_Tubes_IBC::ibc0_force_cube(), Couplage_Tubes_IBC::ibc0_velocity_cube(), Couplage_Tubes_IBC::ibc_diffuse_force_cube(), Couplage_Tubes_IBC::ibc_diffuse_velocity_cube(), Couplage_Tubes_IBC::ibc_localisee_velocity_cube(), Couplage_Tubes_IBC::ibc_localisee_velocity_cube_qdm(), DNS_QC_double::initialise(), Navier_Stokes_FTD_IJK::initialise_ijk_fields(), IJK_Lata_Swap_JK::interpreter(), IJK_Interfaces::mean_over_compo(), IJK_MonofluidVar::operator()(), Navier_Stokes_FTD_IJK::projeter(), Corrige_flux_FT_temperature_subresolution::replace_temperature_cell_centre_neighbours(), DNS_QC_double::rk3_sub_step(), Navier_Stokes_FTD_IJK::rk3_sub_step(), IJK_Shear_Periodic_helpler::set_I_sig_kappa_zmax_(), IJK_Shear_Periodic_helpler::set_I_sig_kappa_zmin_(), IJK_Shear_Periodic_helpler::set_indicatrice_ghost_zmax_(), IJK_Shear_Periodic_helpler::set_indicatrice_ghost_zmin_(), Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::set_to_sum(), Multigrille_base::solve_ijk_in_storage_template(), Corrige_flux_FT_temperature_subresolution::sort_ijk_intersections_subproblems_indices_fluxes_by_k_layers(), Corrige_flux_FT_temperature_subresolution::store_any_cell_faces_corrected(), IJK_Thermal_Subresolution::store_temperature_before_extrapolation(), Switch_double::switch_scalar_field(), DNS_QC_double::translation_pression(), Fourier_trans::update(), IJK_Interfaces::update_indicatrice(), Navier_Stokes_FTD_IJK::update_indicatrice_variables_monofluides(), IJK_Thermal_base::update_thermal_properties(), IJK_Thermal_cut_cell::update_thermal_properties(), and IJK_Thermal_Onefluid::update_thermal_properties().
nb_elem_local()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > int IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nb_elem_local (int dir) const inline
References IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj_, and IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk_.
Referenced by DebogIJK::compute_signature().
j_stride()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > int IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::j_stride () const inline
References IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::j_stride_.
Referenced by ConstIJK_ptr< _TYPE_, _TYPE_ARRAY_ >::ConstIJK_ptr().
compo_stride()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > int IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::compo_stride () const inline
References IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::compo_stride_.
k_stride()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > int IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::k_stride () const inline
References IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::compo_stride_, and Field_base::nb_compo_.
Referenced by ConstIJK_ptr< _TYPE_, _TYPE_ARRAY_ >::ConstIJK_ptr().
ghost()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > int IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost () const inline
References IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost_size_.
Referenced by Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::add_from(), IJK_Thermal_cut_cell::add_temperature_diffusion(), IJK_Thermal_Onefluid::add_temperature_diffusion(), IJK_Composantes_Connex::allocate_fields(), IJK_Composantes_Connex::associate_rising_velocities_parameters(), Cut_cell_surface_efficace::calcul_delta_volume_theorique_bilan(), Couplage_Tubes_IBC::calcul_F_pression(), IJK_Thermal_base::calculer_ecart_T_ana(), IJK_Interfaces::calculer_indicatrice_intermediaire(), ComputeValParCompoInCell::calculer_moy_par_compo(), IJK_Thermal_base::calculer_temperature_physique_T(), IJK_Thermal_Subresolution::clip_max_temperature_values(), IJK_Thermal_Subresolution::clip_min_temperature_values(), Statistiques_dns_ijk::compute_and_store_gradU_cell(), IJK_Composantes_Connex::compute_bounding_box_fill_compo_connex(), IJK_Composantes_Connex::compute_compo_connex_from_interface(), IJK_Ghost_Fluid_Fields::compute_eulerian_curvature(), IJK_Ghost_Fluid_Fields::compute_eulerian_curvature_from_interface(), IJK_Ghost_Fluid_Fields::compute_eulerian_distance(), IJK_Thermal_base::compute_eulerian_grad_T_interface(), IJK_Thermal_base::compute_eulerian_temperature_ghost(), Postprocessing_IJK::compute_extended_pressures(), Corrige_flux_FT_temperature_subresolution::compute_min_max_ijk_any_reachable_fluxes(), Corrige_flux_FT_temperature_subresolution::compute_min_max_ijk_reachable_fluxes(), IJK_Composantes_Connex::compute_rising_velocities(), Corrige_flux_FT_temperature_subresolution::compute_temperature_cell_centre_neighbours(), IJK_Thermal_Onefluid::compute_temperature_convection_conservative(), IJK_Thermal_base::compute_temperature_gradient_elem(), ConstIJK_ptr< _TYPE_, _TYPE_ARRAY_ >::ConstIJK_ptr(), Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::copy_from(), IJK_Thermal_Subresolution::correct_any_temperature_field_for_visu(), IJK_Thermal_Subresolution::correct_any_temperature_fields_for_eulerian_fluxes(), IJK_Thermal_base::ecrire_statistiques_bulles(), IJK_Composantes_Connex::fill_mixed_cell_compo(), Navier_Stokes_FTD_IJK::fill_variable_source_and_potential_phi(), Couplage_Tubes_IBC::force_ibc_velocity_miroir(), Postprocessing_IJK::get_IJK_field(), IJK_MonofluidVar::harmo(), IJK_One_Dimensional_Subproblems_Interfaces_Fields::initialise(), Navier_Stokes_FTD_IJK::initialise_ijk_fields(), Navier_Stokes_FTD_IJK::initialise_ns_fields(), IJK_Thermal_Subresolution::initialise_thermal_subproblems(), IJK_Ghost_Fluid_Fields::initialize(), IJK_Thermal_base::initialize(), IJK_Thermal_Subresolution::initialize(), IJK_Interfaces::initialize(), Navier_Stokes_FTD_IJK::maj_indicatrice_rho_mu(), IJK_MonofluidVar::operator()(), IJK_Thermal_cut_cell::perform_thermal_step(), DNS_QC_double::posttraiter_champs_instantanes(), IJK_Thermal_base::posttraiter_champs_instantanes_thermal_interface_ref(), IJK_Thermal_base::propagate_eulerian_grad_T_interface(), Corrige_flux_FT_temperature_subresolution::replace_temperature_cell_centre_neighbours(), IJK_One_Dimensional_Subproblems_Interfaces_Fields::retrieve_interfacial_surface_quantity(), DNS_QC_double::sauvegarder_qc(), DNS_QC_double::save_raw_data(), Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::set_to_sum(), Multigrille_base::solve_ijk_in_storage_template(), IJK_Thermal_Subresolution::store_temperature_before_extrapolation(), Fourier_trans::update(), IJK_Interfaces::update_indicatrice(), IJK_Thermal_base::update_thermal_properties(), IJK_Thermal_cut_cell::update_thermal_properties(), IJK_Thermal_Onefluid::update_thermal_properties(), and Navier_Stokes_FTD_IJK::update_v_or_rhov().
k_shift()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > int IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::k_shift () const inline
References IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::k_layer_shift_.
Referenced by Multigrille_base::solve_ijk_in_storage_template().
k_shift_max()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > int IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::k_shift_max () const inline
References IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::additional_k_layers_.
get_allocated_size()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > int IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::get_allocated_size () const inline
References IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::allocated_size_.
data() [1/2]
template<typename _TYPE_ , typename _TYPE_ARRAY_ > _TYPE_ARRAY_ & IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::data () inline
References IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::data_.
Referenced by IJK_Composantes_Connex::allocate_fields(), IJK_Composantes_Connex::associate_rising_velocities_parameters(), IJK_Interfaces::calculer_aire_interfaciale(), IJK_Interfaces::calculer_aire_interfaciale_for_compo(), IJK_Interfaces::calculer_indicatrice(), IJK_Interfaces::calculer_indicatrice_intermediaire(), IJK_Interfaces::calculer_kappa_ft(), ComputeValParCompoInCell::calculer_moy_par_compo(), IJK_Interfaces::calculer_normales_et_aires_interfaciales(), IJK_Interfaces::calculer_phi_repuls_par_compo(), IJK_Interfaces::calculer_var_volume_remaillage(), IJK_Thermal_Subresolution::compare_temperature_fields(), Statistiques_dns_ijk::compute_and_store_scalar_product_face_to_face(), IJK_Composantes_Connex::compute_bounding_box_fill_compo_connex(), Corrige_flux_FT_temperature_subresolution::compute_cell_neighbours_mixed_cell_faces_any_field(), Corrige_flux_FT_temperature_subresolution::compute_cell_neighbours_mixed_cell_faces_indices_to_correct(), IJK_Ghost_Fluid_Fields::compute_eulerian_distance(), IJK_Thermal_base::compute_eulerian_grad_T_interface(), IJK_Composantes_Connex::compute_rising_velocities(), Corrige_flux_FT_temperature_subresolution::compute_temperature_cell_centre_neighbours(), IJK_Thermal_Subresolution::compute_temperature_cell_centres_first_correction(), IJK_Thermal_base::compute_temperature_convection(), IJK_Thermal_Onefluid::compute_temperature_convection_conservative(), IJK_Thermal_cut_cell::compute_temperature_convection_cut_cell(), IJK_Thermal_Subresolution::compute_thermal_subproblems(), IJK_Composantes_Connex::fill_mixed_cell_compo(), IJK_Interfaces::get_IJK_field(), Postprocessing_IJK::init_integrated_and_ana(), IJK_One_Dimensional_Subproblems_Interfaces_Fields::initialise(), Navier_Stokes_FTD_IJK::initialise_ns_fields(), IJK_Thermal_Subresolution::initialise_thermal_subproblems(), Multigrille_Adrien::initialize(), IJK_Thermal_base::initialize(), IJK_Thermal_cut_cell::initialize(), IJK_Thermal_Onefluid::initialize(), IJK_Thermal_Subresolution::initialize(), IJK_Interfaces::initialize(), Navier_Stokes_FTD_IJK::maj_indicatrice_rho_mu(), Postprocessing_IJK::postraiter_champs(), Navier_Stokes_FTD_IJK::preparer_calcul(), Navier_Stokes_FTD_IJK::projeter(), IJK_One_Dimensional_Subproblems_Interfaces_Fields::retrieve_interfacial_surface_quantity(), DNS_QC_double::rk3_sub_step(), DNS_QC_double::run(), Parallel_io_parameters::run_bench_read(), Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::set_to_uniform_value(), Multigrille_base::solve_ijk_in_storage_template(), IJK_Thermal_Subresolution::store_temperature_before_extrapolation(), and IJK_Thermal_base::update_thermal_properties().
data() [2/2]
template<typename _TYPE_ , typename _TYPE_ARRAY_ > const _TYPE_ARRAY_ & IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::data () const inline
References IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::data_.
Member Data Documentation
ni_
template<typename _TYPE_ , typename _TYPE_ARRAY_ > int IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni_ protected
Referenced by IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nb_elem_local(), and IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni().
nj_
template<typename _TYPE_ , typename _TYPE_ARRAY_ > int IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj_ protected
Referenced by IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nb_elem_local(), and IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj().
nk_
template<typename _TYPE_ , typename _TYPE_ARRAY_ > int IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk_ protected
Referenced by IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::k_layer(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::linear_index(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::linear_index_relaxed_test(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nb_elem_local(), and IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk().
ghost_size_
template<typename _TYPE_ , typename _TYPE_ARRAY_ > int IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost_size_ protected
Referenced by IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::k_layer(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::linear_index(), and IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::linear_index_relaxed_test().
j_stride_
template<typename _TYPE_ , typename _TYPE_ARRAY_ > int IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::j_stride_ protected
Referenced by IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::j_stride(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::linear_index(), and IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::linear_index_relaxed_test().
compo_stride_
template<typename _TYPE_ , typename _TYPE_ARRAY_ > int IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::compo_stride_ protected
Referenced by IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::compo_stride(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::k_layer(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::k_stride(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::linear_index(), and IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::linear_index_relaxed_test().
offset_
template<typename _TYPE_ , typename _TYPE_ARRAY_ > int IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::offset_ protected
Referenced by IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::k_layer(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::linear_index(), and IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::linear_index_relaxed_test().
k_layer_shift_
template<typename _TYPE_ , typename _TYPE_ARRAY_ > int IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::k_layer_shift_ protected
Referenced by IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::k_shift(), and IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::linear_index_relaxed_test().
additional_k_layers_
template<typename _TYPE_ , typename _TYPE_ARRAY_ > int IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::additional_k_layers_ protected
Referenced by IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::k_shift_max(), and IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::linear_index_relaxed_test().
allocated_size_
template<typename _TYPE_ , typename _TYPE_ARRAY_ > int IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::allocated_size_ protected
Referenced by IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::get_allocated_size().
data_
template<typename _TYPE_ , typename _TYPE_ARRAY_ > _TYPE_ARRAY_ IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::data_ protected
Referenced by IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::data(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::get_in_allocated_area(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::k_layer(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::linear_index_relaxed_test(), and IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::operator()().