TrioCFD: Operateur_Conv Class Reference
Operateur_Conv Class Reference
#include <Operateur_Conv.h>
Public Member Functions
DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const override
void associer_vitesse (const Champ_base &)
DoubleTab & calculer (const DoubleTab &, DoubleTab &) const override
const Type_info * get_info () const override
const Operateur_base & l_op_base () const override
Operateur_base & l_op_base () override
void typer () override
void typer (const Nom &)
const Champ_base & vitesse () const
Public Member Functions inherited from Operateur
DoubleTab & ajouter (const Champ_Inc_base &, DoubleTab &) const
DoubleTab & ajouter (DoubleTab &) const
DoubleTab & calculer (const Champ_Inc_base &, DoubleTab &) const
DoubleTab & calculer (DoubleTab &) const
virtual void completer ()
const Discretisation_base & discretisation () const
int impr (Sortie &os) const
void imprimer (Sortie &os) const
int limpr () const
Entree & lire (Entree &)
virtual void mettre_a_jour (double temps)
const Champ_Inc_base & mon_inconnue () const
const Nom & type () const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Objet_U_ptr
int associer_ (Objet_U &objet) override
const Type_info * get_info () const override
const Nom & le_nom () const override
Objet_U * typer (const char *nom_type)
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from TRUST_Deriv< Operateur_Conv_base >
Sortie & printOn (Sortie &os) const override
Entree & readOn (Entree &is) override
Protected Member Functions inherited from Objet_U_ptr
int change_num (const int *const) override
Objet_U * get_Objet_U_ptr_check () const
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
void recopie (const Objet_U &)
~Objet_U_ptr () override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
de convection. Un objet Operateur_Conv peut referencer n'importe quel objet derivant de Operateur_Conv_base.
See also
Operateur_Conv_base Operateur
Constructor & Destructor Documentation
Operateur_Conv()
Operateur_Conv::Operateur_Conv ()
~Operateur_Conv()
Operateur_Conv::~Operateur_Conv ()
Member Function Documentation
cree_instance()
Objet_U * Operateur_Conv::cree_instance () static
taille_memoire()
unsigned Operateur_Conv::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Operateur_Conv::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Operateur_Conv::info () static
get_info()
const Type_info * Operateur_Conv::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
Operateur_Conv & Operateur_Conv::self_cast (Objet_U & r) static
self_cast() [2/2]
const Operateur_Conv & Operateur_Conv::self_cast (const Objet_U & r) static
printOn()
Sortie & Operateur_Conv::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
References Operateur::ecrire().
readOn()
Entree & Operateur_Conv::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
References Nom::contient(), Process::exit(), TRUST_Ref< _CLASSE_ >::le_nom(), Operateur::lire(), MorEqn::mon_equation, Objet_U::que_suis_je(), and TRUST_Deriv< Operateur_Conv_base >::valeur().
l_op_base() [1/2]
Operateur_base & Operateur_Conv::l_op_base () inline override virtual
Renvoie l'objet sous-jacent upcaste en Operateur_base.
Returns
(Operateur_base&) l'objet sous-jacent upcaste en Operateur_base
Implements Operateur.
References TRUST_Deriv< Operateur_Conv_base >::valeur().
Referenced by Operateur_Conv_sensibility::associer(), and Op_Conv_ALE::associer().
l_op_base() [2/2]
const Operateur_base & Operateur_Conv::l_op_base () const inline override virtual
Renvoie l'objet sous-jacent upcaste en Operateur_base (version const)
Returns
(Operateur_base&) l'objet sous-jacent upcaste en Operateur_base
Implements Operateur.
References TRUST_Deriv< Operateur_Conv_base >::valeur().
ajouter()
DoubleTab & Operateur_Conv::ajouter (const DoubleTab & donnee, DoubleTab & resu) const override virtual
Ajoute la contribution de l'operateur au tableau passe en parametre.
Parameters
(DoubleTab& donnee) tableau contenant les donnees sur lesquelles on applique l'operateur.
(DoubleTab& resu) tableau auquel on ajoute la contribution de l'operateur
Returns
(DoubleTab&) le tableau contenant le resultat
Implements Operateur.
References Operateur_base::ajouter(), Statistiques::begin_count(), Statistiques::end_count(), and TRUST_Deriv< Operateur_Conv_base >::valeur().
Referenced by Operateur_Conv_sensibility::ajouter(), Op_Conv_ALE::ajouter(), Convection_Diffusion_Temperature_FT_Disc::derivee_en_temps_inco(), and Navier_Stokes_phase_field::derivee_en_temps_inco().
calculer()
DoubleTab & Operateur_Conv::calculer (const DoubleTab & donnee, DoubleTab & resu) const override virtual
Initialise le tableau passe en parametre avec la contribution de l'operateur.
Parameters
(DoubleTab& donnee) tableau contenant les donnees sur lesquelles on applique l'operateur.
(DoubleTab& resu) tableau dans lequel stocke la contribution de l'operateur
Returns
(DoubleTab&) le tableau contenant le resultat
Implements Operateur.
References Statistiques::begin_count(), Operateur_base::calculer(), Statistiques::end_count(), and TRUST_Deriv< Operateur_Conv_base >::valeur().
Referenced by Operateur_Conv_sensibility::calculer(), Op_Conv_ALE::calculer(), and Navier_Stokes_FT_Disc::derivee_en_temps_inco().
associer_vitesse()
void Operateur_Conv::associer_vitesse (const Champ_base & vit) inline
Associe la vitesse (en tant que vitesse transportante) a l'operateur de convection.
Parameters
(Champ_Inc_base& vit) le champ inconnue representant la vitesse
Returns
le champ inconnue representant la vitesse transportante
References la_vitesse.
Referenced by Transport_K_Eps::lire_motcle_non_standard(), Transport_K_Eps_non_std::lire_motcle_non_standard(), Transport_K_Eps_Realisable::lire_motcle_non_standard(), Transport_K_Omega::lire_motcle_non_standard(), Transport_K_ou_Eps::lire_motcle_non_standard(), Transport_K_ou_Eps_non_std::lire_motcle_non_standard(), Transport_K_ou_Eps_Realisable::lire_motcle_non_standard(), Convection_Diffusion_Espece_Multi_QC::lire_motcle_non_standard(), Convection_Diffusion_std::lire_motcle_non_standard(), Navier_Stokes_std::lire_motcle_non_standard(), Op_Conv_ALE_VEF::readOn(), and Operateur_Conv_sensibility_VEF::readOn().
vitesse()
const Champ_base & Operateur_Conv::vitesse () const inline
Renvoie la vitesse transportante de l'operateur.
Returns
(Champ_Inc_base&) le champ inconnue representant la vitesse transportante
References la_vitesse, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by typer().
typer() [1/2]
void Operateur_Conv::typer () override virtual
Type l'operateur: "Op_Conv" + motcle + discretisation + inconnue.
Associe la vitesse transportante a l'operateur base
Implements Operateur.
References Operateur_Conv_base::associer_vitesse(), Equation_base::discretisation(), Discretisation_base::get_name_of_type_for(), MorEqn::mon_equation, Objet_U::que_suis_je(), Operateur::typ, typer(), TRUST_Deriv< Operateur_Conv_base >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), and vitesse().
Referenced by typer().
typer() [2/2]
void Operateur_Conv::typer (const Nom & a_type) inline
Type l'operateur.
Parameters
(Nom& typ) le nom representant le type de l'operateur
References typer().
op_non_nul()
int Operateur_Conv::op_non_nul () const inline override virtual
Implements Operateur.
References Objet_U_ptr::non_nul().
Referenced by associer_norme_vitesse(), and Convection_Diffusion_Concentration::readOn().
associer_norme_vitesse()
void Operateur_Conv::associer_norme_vitesse (const Champ_base & norme_vitesse)
References Operateur_Conv_base::associer_norme_vitesse(), op_non_nul(), and TRUST_Deriv< Operateur_Conv_base >::valeur().
Member Data Documentation
info_obj
const Type_info Operateur_Conv::info_obj static
la_vitesse
TRUST_Ref< Champ_base *> Operateur_Conv::la_vitesse protected
Referenced by associer_vitesse(), and vitesse().