TrioCFD: IJK_Thermals Class Reference
IJK_Thermals Class Reference
#include <IJK_Thermals.h>
Public Member Functions
void associer_pb_base (const Probleme_base &) override
void completer () override
void discretiser () override
const Type_info * get_info () const override
int preparer_calcul () override
Public Member Functions inherited from Equation_base
virtual void abortTimeStep ()
virtual void associer_domaine_dis (const Domaine_dis_base &)
virtual void associer_pb_base (const Probleme_base &)
virtual void associer_sch_tps_base (const Schema_Temps_base &)
virtual double calculer_pas_de_temps () const
virtual void completer ()
virtual std::vector< YAML_data > data_a_sauvegarder () const
DoubleTab & derivee_en_temps_conv (DoubleTab &, const DoubleTab &)
virtual DoubleTab & derivee_en_temps_inco (DoubleTab &)
const Discretisation_base & discretisation () const
virtual void discretiser ()
virtual const Motcle & domaine_application () const
virtual Domaine_Cl_dis_base & domaine_Cl_dis ()
virtual const Domaine_Cl_dis_base & domaine_Cl_dis () const
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual void imprimer (Sortie &os) const
virtual bool initTimeStep (double dt)
const Nom & le_nom () const override
int limpr () const
virtual void mettre_a_jour (double temps)
virtual int preparer_calcul ()
Probleme_base & probleme ()
const Probleme_base & probleme () const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Schema_Temps_base & schema_temps ()
const Schema_Temps_base & schema_temps () const
Solveur_Masse_base & solv_masse ()
const Solveur_Masse_base & solv_masse () const
Sources & sources ()
const Sources & sources () const
virtual void valider_iteration ()
virtual void verifie_ch_init_nb_comp (const Champ_Inc_base &ch_ref, const int nb_comp) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Equation_base
virtual Entree & lire_cl (Entree &)
virtual Entree & lire_cond_init (Entree &)
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual Entree & lire_sources (Entree &)
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
virtual int verif_Cl () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Public Types inherited from Champs_compris_IJK_interface
using FieldInfo_t = std::tuple< Motcle, Entity, Nature_du_champ, bool >
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Member Typedef Documentation
FieldInfo_t
using IJK_Thermals::FieldInfo_t = Champs_compris_IJK_interface::FieldInfo_t
Constructor & Destructor Documentation
IJK_Thermals()
IJK_Thermals::IJK_Thermals ()
~IJK_Thermals()
IJK_Thermals::~IJK_Thermals ()
Member Function Documentation
cree_instance()
Objet_U * IJK_Thermals::cree_instance () static
taille_memoire()
unsigned IJK_Thermals::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int IJK_Thermals::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * IJK_Thermals::info () static
get_info()
const Type_info * IJK_Thermals::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Equation_base.
self_cast() [1/2]
IJK_Thermals & IJK_Thermals::self_cast (Objet_U & r) static
self_cast() [2/2]
const IJK_Thermals & IJK_Thermals::self_cast (const Objet_U & r) static
printOn()
Sortie & IJK_Thermals::printOn (Sortie & os) const override protected virtual
Surcharge Objet_U::printOn Imprime l'equation et ses composants sur un flot de sortie.
Imprime le nom de l'equation, le solveur masse, les termes sources les conditions aux limites discretisees, les inconnues et les operateurs.
Parameters
(Sortie& os) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Equation_base.
readOn()
Entree & IJK_Thermals::readOn (Entree & is) override protected virtual
Lecture d'une equation sur un flot d'entree.
Le format est le suivant: { [Source { [sou_1], [sour_2], ...} ] Conditions_limites { [cl_1] [cl_2] ... } Conditions_initiales { [cl_init] } }
Parameters
(Entree& is) un flot d'entree pour lire l'equation
Returns
(Entree&) le flot d'entree modifie
Exceptions
mauvais format de lecture, accolade ouvrante attendue
pas de conditions initiales, il faut initialiser l'inconnue
pas de conditions aux limites, il faut donner des conditions aux limites
Reimplemented from Equation_base.
References TRUST_List< _CLASSE_ >::add(), TRUST_List< _CLASSE_ >::dernier(), Process::exit(), liste_thermique_, TRUST_List< _CLASSE_ >::size(), IJK_Thermal_base::typer_lire_thermal_equation(), and TRUST_List< _CLASSE_ >::vide().
set_param()
void IJK_Thermals::set_param (Param & titi) inline override virtual
Reimplemented from Equation_base.
completer()
void IJK_Thermals::completer () override virtual
Complete la construction (initialisation) des objets associes a l'equation.
Complete les sources, associe l'equation a l'inconnue complete les operateurs, complete les conditions aux limites discretisees. Voir les methodes Source_base::completer(), Operateur_base::completer() Domaine_Cl_dis_base::completer() Domaine_Cl_dis_base::completer(const Domaine_dis_base&)
Reimplemented from Equation_base.
References IJK_Ghost_Fluid_Fields::associer(), associer_interface_intersections(), associer_post(), TRUST_List< _CLASSE_ >::est_vide(), ghost_fluid_fields_, liste_thermique_, ref_ijk_ft_, retrieve_ghost_fluid_params(), and TRUST_Ref< _CLASSE_ >::valeur().
associer_pb_base()
void IJK_Thermals::associer_pb_base (const Probleme_base & pb) override virtual
S'associe au Probleme passe en parametre.
Associe egalement les sources, les operateurs et le solveur de masse a l'equation.
Parameters
(Probleme_base& pb) le probleme auquel l'equation doit s'associer
Reimplemented from Equation_base.
References Process::exit(), Probleme_U::le_nom(), Equation_base::mon_probleme, Equation_base::nom_, Objet_U::que_suis_je(), and ref_ijk_ft_.
discretiser()
void IJK_Thermals::discretiser () inline override virtual
Discretise l'equation.
Type le domaine_Cl_dis, la formatte, l'associe a l'equation. Type le solveur masse, lui associe le domaine discretisee et le domaine des conditions aux limites discretisees.
Reimplemented from Equation_base.
preparer_calcul()
int IJK_Thermals::preparer_calcul () inline override virtual
Tout ce qui ne depend pas des autres problemes eventuels.
Returns
(int) renvoie toujours 1
Reimplemented from Equation_base.
milieu() [1/2]
const Milieu_base & IJK_Thermals::milieu () const override virtual
Implements Equation_base.
References TRUST_Ref< _CLASSE_ >::est_nul(), Process::exit(), le_fluide_, Probleme_U::le_nom(), Equation_base::probleme(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by milieu_ijk().
milieu() [2/2]
Milieu_base & IJK_Thermals::milieu () override virtual
Implements Equation_base.
References TRUST_Ref< _CLASSE_ >::est_nul(), Process::exit(), le_fluide_, Probleme_U::le_nom(), Equation_base::probleme(), and TRUST_Ref< _CLASSE_ >::valeur().
associer_milieu_base()
void IJK_Thermals::associer_milieu_base (const Milieu_base & un_milieu) override virtual
Implements Equation_base.
References Process::exit(), le_fluide_, liste_thermique_, and verifie_milieu().
nombre_d_operateurs()
int IJK_Thermals::nombre_d_operateurs () const inline override virtual
Implements Equation_base.
operateur() [1/2]
const Operateur & IJK_Thermals::operateur (int) const inline override virtual
Implements Equation_base.
operateur() [2/2]
Operateur & IJK_Thermals::operateur (int) inline override virtual
Implements Equation_base.
inconnue() [1/2]
const Champ_Inc_base & IJK_Thermals::inconnue () const inline override virtual
Implements Equation_base.
inconnue() [2/2]
Champ_Inc_base & IJK_Thermals::inconnue () inline override virtual
Implements Equation_base.
verifie_milieu()
void IJK_Thermals::verifie_milieu ()
References Milieu_base::capacite_calorifique(), Milieu_base::conductivite(), Process::exit(), Fluide_Diphasique::fluide_phase(), Milieu_base::has_capacite_calorifique(), Milieu_base::has_conductivite(), liste_thermique_, milieu_ijk(), TRUSTVect< _TYPE_, _SIZE_ >::size(), TRUST_List< _CLASSE_ >::size(), and Champ_Don_base::valeurs().
Referenced by associer_milieu_base().
milieu_ijk() [1/2]
Fluide_Diphasique_IJK & IJK_Thermals::milieu_ijk () inline
References milieu().
Referenced by verifie_milieu().
milieu_ijk() [2/2]
const Fluide_Diphasique_IJK & IJK_Thermals::milieu_ijk () const inline
References milieu().
set_fichier_reprise()
void IJK_Thermals::set_fichier_reprise (const char * lataname)
References TRUST_List< _CLASSE_ >::est_vide(), and liste_thermique_.
Referenced by Switch_FT_double::prepare_run(), and Probleme_FTD_IJK_base::reprendre_probleme().
get_fichier_reprise()
const Nom & IJK_Thermals::get_fichier_reprise ()
References TRUST_List< _CLASSE_ >::est_vide(), and liste_thermique_.
Referenced by Switch_FT_double::prepare_run().
associer_post()
void IJK_Thermals::associer_post (const Postprocessing_IJK & ijk_ft_post)
References liste_thermique_, and ref_ijk_ft_post_.
Referenced by completer().
associer_switch()
void IJK_Thermals::associer_switch (const Switch_FT_double & ijk_ft_switch)
References liste_thermique_, and ref_ijk_ft_switch_.
has_champ() [1/2]
bool IJK_Thermals::has_champ (const Motcle & nom) const override virtual
Reimplemented from Equation_base.
References ghost_fluid_fields_, IJK_Ghost_Fluid_Fields::has_champ(), and liste_thermique_.
Referenced by Probleme_FTD_IJK_base::has_champ().
has_champ() [2/2]
bool IJK_Thermals::has_champ (const Motcle & nom, TRUST_Ref< Champ_base * > & ref_champ) const inline override virtual
Reimplemented from Equation_base.
has_champ_vectoriel()
bool IJK_Thermals::has_champ_vectoriel (const Motcle & nom) const inline override virtual
Implements Champs_compris_IJK_interface.
Referenced by Probleme_FTD_IJK_base::has_champ_vectoriel().
get_IJK_field()
const IJK_Field_double & IJK_Thermals::get_IJK_field (const Motcle & nom) override virtual
Implements Champs_compris_IJK_interface.
References IJK_Ghost_Fluid_Fields::get_IJK_field(), ghost_fluid_fields_, IJK_Ghost_Fluid_Fields::has_champ(), and liste_thermique_.
Referenced by Probleme_FTD_IJK_base::get_IJK_field().
get_IJK_field_vector()
const IJK_Field_vector3_double & IJK_Thermals::get_IJK_field_vector (const Motcle & nom) override virtual
Implements Champs_compris_IJK_interface.
References IJK_Ghost_Fluid_Fields::get_IJK_field_vector(), ghost_fluid_fields_, IJK_Ghost_Fluid_Fields::has_champ(), and liste_thermique_.
Referenced by Probleme_FTD_IJK_base::get_IJK_field_vector().
Fill_postprocessable_fields()
void IJK_Thermals::Fill_postprocessable_fields (std::vector< FieldInfo_t > & chps) static
Referenced by Probleme_FTD_IJK_base::Fill_postprocessable_fields(), and Postprocessing_IJK::register_one_field().
get_noms_champs_postraitables()
void IJK_Thermals::get_noms_champs_postraitables (Noms & noms, Option opt = NONE) const override virtual
Reimplemented from Equation_base.
References IJK_Ghost_Fluid_Fields::get_noms_champs_postraitables(), ghost_fluid_fields_, and liste_thermique_.
Referenced by Probleme_FTD_IJK_base::get_noms_champs_postraitables().
split_name()
void IJK_Thermals::split_name (const Motcle & nom, Nom & var, int & rank) const
associer_interface_intersections()
void IJK_Thermals::associer_interface_intersections (const Intersection_Interface_ijk_cell & intersection_ijk_cell_, const Intersection_Interface_ijk_face & intersection_ijk_face_)
References liste_thermique_, ref_intersection_ijk_cell_, and ref_intersection_ijk_face_.
Referenced by completer().
retrieve_ghost_fluid_params()
void IJK_Thermals::retrieve_ghost_fluid_params ()
References TRUST_List< _CLASSE_ >::est_vide(), ghost_fluid_fields_, liste_thermique_, and IJK_Ghost_Fluid_Fields::retrieve_ghost_fluid_params().
Referenced by completer().
sauvegarder_temperature()
void IJK_Thermals::sauvegarder_temperature (Nom & lata_name, const int & stop)
References liste_thermique_.
Referenced by Probleme_FTD_IJK_base::sauvegarder_probleme().
sauvegarder_thermals()
void IJK_Thermals::sauvegarder_thermals (SFichier & fichier)
References TRUST_List< _CLASSE_ >::begin(), TRUST_List< _CLASSE_ >::end(), liste_thermique_, and TRUST_List< _CLASSE_ >::size().
compute_timestep()
void IJK_Thermals::compute_timestep (double & dt_thermals, const double dxmin)
References liste_thermique_.
Referenced by Schema_Temps_IJK_base::find_timestep().
initialize()
void IJK_Thermals::initialize (const Domaine_IJK & splitting)
References TRUST_List< _CLASSE_ >::add(), Option_IJK::DISABLE_DIPHASIQUE, TRUST_List< _CLASSE_ >::est_vide(), ghost_fluid_fields_, IJK_Ghost_Fluid_Fields::initialize(), interfacial_quantities_thermal_probes_folder_, lata_step_reprise_, lata_step_reprise_ini_, liste_thermique_, local_quantities_thermal_lines_folder_, local_quantities_thermal_lines_time_index_folder_, local_quantities_thermal_probes_folder_, local_quantities_thermal_probes_time_index_folder_, local_quantities_thermal_slices_folder_, local_quantities_thermal_slices_time_index_folder_, overall_bubbles_quantities_folder_, shell_quantities_thermal_probes_folder_, and thermal_rank_folder_.
Referenced by Probleme_FTD_IJK_base::initialise_ijk_fields().
recompute_temperature_init()
void IJK_Thermals::recompute_temperature_init ()
References liste_thermique_.
copie_pure_vers_diph_sans_interpolation()
void IJK_Thermals::copie_pure_vers_diph_sans_interpolation ()
References liste_thermique_.
echange_pure_vers_diph_cellules_initialement_pures()
void IJK_Thermals::echange_pure_vers_diph_cellules_initialement_pures ()
References liste_thermique_.
Referenced by Probleme_FTD_IJK_cut_cell::deplacer_interfaces(), and Probleme_FTD_IJK_cut_cell::deplacer_interfaces_rk3().
echange_diph_vers_pure_cellules_finalement_pures()
void IJK_Thermals::echange_diph_vers_pure_cellules_finalement_pures ()
References liste_thermique_.
Referenced by Probleme_FTD_IJK_cut_cell::deplacer_interfaces(), and Probleme_FTD_IJK_cut_cell::deplacer_interfaces_rk3().
vide_phase_invalide_cellules_diphasiques()
void IJK_Thermals::vide_phase_invalide_cellules_diphasiques ()
References liste_thermique_.
Referenced by Probleme_FTD_IJK_cut_cell::deplacer_interfaces(), and Probleme_FTD_IJK_cut_cell::deplacer_interfaces_rk3().
remplir_tableau_pure_cellules_diphasiques()
void IJK_Thermals::remplir_tableau_pure_cellules_diphasiques (bool next_time)
References liste_thermique_.
size_thermal_problem()
int IJK_Thermals::size_thermal_problem (Nom thermal_problem)
References liste_thermique_, and size().
update_thermal_properties()
void IJK_Thermals::update_thermal_properties ()
References liste_thermique_.
Referenced by Probleme_FTD_IJK_base::solveTimeStep_RK3(), and Probleme_FTD_IJK_base::update_thermal_properties().
euler_time_step()
void IJK_Thermals::euler_time_step (const double timestep)
References IJK_Ghost_Fluid_Fields::enforce_distance_curvature_values_for_post_processings(), ghost_fluid_fields_, and liste_thermique_.
Referenced by Probleme_FTD_IJK_base::euler_time_step().
euler_rustine_step()
void IJK_Thermals::euler_rustine_step (const double timestep)
References liste_thermique_.
Referenced by Probleme_FTD_IJK_base::solveTimeStep_Euler().
rk3_sub_step()
void IJK_Thermals::rk3_sub_step (const int rk_step, const double total_timestep, const double time)
References Process::exit(), and liste_thermique_.
Referenced by Probleme_FTD_IJK_base::rk3_sub_step().
rk3_rustine_sub_step()
void IJK_Thermals::rk3_rustine_sub_step (const int rk_step, const double total_timestep, const double fractionnal_timestep, const double time)
References liste_thermique_.
Referenced by Probleme_FTD_IJK_base::solveTimeStep_RK3().
ecrire_statistiques_bulles()
void IJK_Thermals::ecrire_statistiques_bulles (int reset, const Nom & nom_cas, const double current_time, const ArrOfDouble & surface)
References liste_thermique_.
posttraiter_tous_champs_thermal()
void IJK_Thermals::posttraiter_tous_champs_thermal (Motcles & liste_post_instantanes_)
References liste_thermique_.
posttraiter_champs_instantanes_thermal()
void IJK_Thermals::posttraiter_champs_instantanes_thermal (const Motcles & liste_post_instantanes, const char * lata_name, const int latastep, const double current_time, int & n)
init_switch_thermals()
void IJK_Thermals::init_switch_thermals (const Domaine_IJK & splitting)
References liste_thermique_.
Referenced by Switch_FT_double::init_thermals().
prepare_thermals()
void IJK_Thermals::prepare_thermals (const char * lataname)
References liste_thermique_.
Referenced by Switch_FT_double::prepare_thermals().
ghost_fluid_flag()
int IJK_Thermals::ghost_fluid_flag ()
References liste_thermique_.
Referenced by compute_eulerian_distance_curvature(), and Probleme_FTD_IJK_base::initialise_ijk_fields().
ecrire_fichier_reprise()
void IJK_Thermals::ecrire_fichier_reprise (SFichier & fichier, const char * lata_name)
References TRUST_List< _CLASSE_ >::begin(), TRUST_List< _CLASSE_ >::end(), liste_thermique_, and TRUST_List< _CLASSE_ >::size().
Referenced by Switch_FT_double::ecrire_fichier_reprise().
compute_ghost_cell_numbers_for_subproblems()
void IJK_Thermals::compute_ghost_cell_numbers_for_subproblems (const Domaine_IJK & splitting, int ghost_init)
References liste_thermique_.
Referenced by Probleme_FTD_IJK::initialize(), and Probleme_FTD_IJK_cut_cell::initialize().
get_probes_ghost_cells()
int IJK_Thermals::get_probes_ghost_cells (int ghost_init)
References liste_thermique_.
Referenced by Probleme_FTD_IJK::initialize(), and Probleme_FTD_IJK_cut_cell::initialize().
update_intersections()
void IJK_Thermals::update_intersections ()
References liste_thermique_.
clean_ijk_intersections()
void IJK_Thermals::clean_ijk_intersections ()
References liste_thermique_.
Referenced by Probleme_FTD_IJK_base::deplacer_interfaces().
compute_eulerian_distance()
void IJK_Thermals::compute_eulerian_distance ()
References IJK_Ghost_Fluid_Fields::compute_eulerian_distance(), TRUST_List< _CLASSE_ >::est_vide(), ghost_fluid_fields_, and liste_thermique_.
Referenced by compute_eulerian_distance_curvature().
compute_eulerian_curvature()
void IJK_Thermals::compute_eulerian_curvature ()
References IJK_Ghost_Fluid_Fields::compute_eulerian_curvature(), TRUST_List< _CLASSE_ >::est_vide(), ghost_fluid_fields_, and liste_thermique_.
compute_eulerian_curvature_from_interface()
void IJK_Thermals::compute_eulerian_curvature_from_interface ()
References IJK_Ghost_Fluid_Fields::compute_eulerian_curvature_from_interface(), TRUST_List< _CLASSE_ >::est_vide(), ghost_fluid_fields_, and liste_thermique_.
Referenced by compute_eulerian_distance_curvature().
compute_eulerian_distance_curvature()
void IJK_Thermals::compute_eulerian_distance_curvature ()
References compute_eulerian_curvature_from_interface(), compute_eulerian_distance(), TRUST_List< _CLASSE_ >::est_vide(), ghost_fluid_flag(), and liste_thermique_.
Referenced by Probleme_FTD_IJK_base::deplacer_interfaces().
set_latastep_reprise()
void IJK_Thermals::set_latastep_reprise (const bool stop)
References liste_thermique_, and ref_ijk_ft_.
thermal_subresolution_outputs()
void IJK_Thermals::thermal_subresolution_outputs (const int & dt_post_thermals_probes = 0)
References create_folders(), create_folders_for_probes(), get_disable_post_processing_probes_out_files(), ini_folder_out_files_, interfacial_quantities_thermal_probes_folder_, lata_step_reprise_ini_, liste_thermique_, local_quantities_thermal_lines_folder_, local_quantities_thermal_lines_time_index_folder_, local_quantities_thermal_probes_folder_, local_quantities_thermal_probes_time_index_folder_, local_quantities_thermal_slices_folder_, local_quantities_thermal_slices_time_index_folder_, overall_bubbles_quantities_folder_, post_pro_first_call_, ref_ijk_ft_, shell_quantities_thermal_probes_folder_, and thermal_rank_folder_.
get_disable_post_processing_probes_out_files()
int IJK_Thermals::get_disable_post_processing_probes_out_files () const
References liste_thermique_.
Referenced by thermal_subresolution_outputs().
get_modified_time()
double IJK_Thermals::get_modified_time ()
References TRUST_List< _CLASSE_ >::est_vide(), liste_thermique_, and ref_ijk_ft_.
get_rising_velocities_parameters()
void IJK_Thermals::get_rising_velocities_parameters (int & compute_rising_velocities, int & fill_rising_velocities, int & use_bubbles_velocities_from_interface, int & use_bubbles_velocities_from_barycentres)
References TRUST_List< _CLASSE_ >::est_vide(), and liste_thermique_.
Referenced by Probleme_FTD_IJK_base::initialise_ijk_fields().
create_folders_for_probes()
void IJK_Thermals::create_folders_for_probes ()
References create_folders(), interfacial_quantities_thermal_probes_folder_, liste_thermique_, local_quantities_thermal_lines_folder_, local_quantities_thermal_probes_folder_, local_quantities_thermal_slices_folder_, overall_bubbles_quantities_folder_, shell_quantities_thermal_probes_folder_, TRUST_List< _CLASSE_ >::size(), and thermal_rank_folder_.
Referenced by thermal_subresolution_outputs().
create_folders()
void IJK_Thermals::create_folders (Nom folder_name_base)
References Process::exit(), Nom::getString(), and Process::je_suis_maitre().
Referenced by create_folders_for_probes(), and thermal_subresolution_outputs().
set_first_step_thermals_post()
void IJK_Thermals::set_first_step_thermals_post (int & first_step_thermals_post)
References liste_thermique_, and TRUST_List< _CLASSE_ >::size().
set_post_pro_first_call()
void IJK_Thermals::set_post_pro_first_call () inline
References post_pro_first_call_.
Referenced by recompute_interface_smoothing(), and Probleme_FTD_IJK_base::solveTimeStep_Euler().
set_temperature_ini()
void IJK_Thermals::set_temperature_ini ()
References liste_thermique_.
Referenced by recompute_interface_smoothing(), and Probleme_FTD_IJK_base::solveTimeStep_Euler().
recompute_interface_smoothing()
void IJK_Thermals::recompute_interface_smoothing ()
References set_post_pro_first_call(), and set_temperature_ini().
compute_new_thermal_field()
void IJK_Thermals::compute_new_thermal_field (Switch_FT_double & switch_double_ft, const Domaine_IJK & new_mesh, const Nom & lata_name, DoubleTab & coeff_i, IntTab Indice_i, DoubleTab & coeff_j, IntTab Indice_j, DoubleTab & coeff_k, IntTab Indice_k)
References IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::allocate(), Switch_double::calculer_coeff(), Switch_double::calculer_coords_elem(), Domaine_IJK::ELEM, liste_thermique_, TRUST_List< _CLASSE_ >::size(), and Switch_double::switch_scalar_field().
Referenced by Switch_FT_double::compute_and_write_extra_fields().
copy_previous_interface_state()
void IJK_Thermals::copy_previous_interface_state ()
References liste_thermique_.
Referenced by Probleme_FTD_IJK_base::deplacer_interfaces().
get_liste_eqs() [1/2]
const TRUST_List< TRUST_Deriv< IJK_Thermal_base > > & IJK_Thermals::get_liste_eqs () const inline
References liste_thermique_.
get_liste_eqs() [2/2]
TRUST_List< TRUST_Deriv< IJK_Thermal_base > > & IJK_Thermals::get_liste_eqs () inline
References liste_thermique_.
size()
int IJK_Thermals::size () const inline
References liste_thermique_, and TRUST_List< _CLASSE_ >::size().
Referenced by size_thermal_problem().
est_vide()
int IJK_Thermals::est_vide () const inline
References TRUST_List< _CLASSE_ >::est_vide(), and liste_thermique_.
Referenced by Switch_FT_double::prepare_run().
Member Data Documentation
info_obj
const Type_info IJK_Thermals::info_obj static
liste_thermique_
TRUST_List< TRUST_Deriv< IJK_Thermal_base > > IJK_Thermals::liste_thermique_ protected
Referenced by associer_interface_intersections(), associer_milieu_base(), associer_post(), associer_switch(), clean_ijk_intersections(), completer(), compute_eulerian_curvature(), compute_eulerian_curvature_from_interface(), compute_eulerian_distance(), compute_eulerian_distance_curvature(), compute_ghost_cell_numbers_for_subproblems(), compute_new_thermal_field(), compute_timestep(), copie_pure_vers_diph_sans_interpolation(), copy_previous_interface_state(), create_folders_for_probes(), echange_diph_vers_pure_cellules_finalement_pures(), echange_pure_vers_diph_cellules_initialement_pures(), ecrire_fichier_reprise(), ecrire_statistiques_bulles(), est_vide(), euler_rustine_step(), euler_time_step(), get_disable_post_processing_probes_out_files(), get_fichier_reprise(), get_IJK_field(), get_IJK_field_vector(), get_liste_eqs(), get_modified_time(), get_noms_champs_postraitables(), get_probes_ghost_cells(), get_rising_velocities_parameters(), ghost_fluid_flag(), has_champ(), init_switch_thermals(), initialize(), posttraiter_tous_champs_thermal(), prepare_thermals(), readOn(), recompute_temperature_init(), remplir_tableau_pure_cellules_diphasiques(), retrieve_ghost_fluid_params(), rk3_rustine_sub_step(), rk3_sub_step(), sauvegarder_temperature(), sauvegarder_thermals(), set_fichier_reprise(), set_first_step_thermals_post(), set_latastep_reprise(), set_temperature_ini(), size(), size_thermal_problem(), thermal_subresolution_outputs(), update_intersections(), update_thermal_properties(), verifie_milieu(), and vide_phase_invalide_cellules_diphasiques().
le_fluide_
TRUST_Ref< Milieu_base *> IJK_Thermals::le_fluide_ protected
Referenced by associer_milieu_base(), and milieu().
ref_ijk_ft_
TRUST_Ref< Probleme_FTD_IJK_base *> IJK_Thermals::ref_ijk_ft_ protected
Referenced by associer_pb_base(), completer(), get_modified_time(), set_latastep_reprise(), and thermal_subresolution_outputs().
ref_ijk_ft_post_
TRUST_Ref< Postprocessing_IJK *> IJK_Thermals::ref_ijk_ft_post_ protected
Referenced by associer_post().
ref_ijk_ft_switch_
TRUST_Ref< Switch_FT_double *> IJK_Thermals::ref_ijk_ft_switch_ protected
Referenced by associer_switch().
ref_intersection_ijk_cell_
TRUST_Ref< Intersection_Interface_ijk_cell *> IJK_Thermals::ref_intersection_ijk_cell_ protected
Referenced by associer_interface_intersections().
ref_intersection_ijk_face_
TRUST_Ref< Intersection_Interface_ijk_face *> IJK_Thermals::ref_intersection_ijk_face_ protected
Referenced by associer_interface_intersections().
ghost_fluid_fields_
IJK_Ghost_Fluid_Fields IJK_Thermals::ghost_fluid_fields_ protected
Referenced by completer(), compute_eulerian_curvature(), compute_eulerian_curvature_from_interface(), compute_eulerian_distance(), euler_time_step(), get_IJK_field(), get_IJK_field_vector(), get_noms_champs_postraitables(), has_champ(), initialize(), and retrieve_ghost_fluid_params().
post_pro_first_call_
int IJK_Thermals::post_pro_first_call_ = 0 protected
Referenced by set_post_pro_first_call(), and thermal_subresolution_outputs().
make_dir_for_out_files_
System IJK_Thermals::make_dir_for_out_files_ protected
thermal_rank_folder_
TRUST_List< Nom > IJK_Thermals::thermal_rank_folder_ protected
Referenced by create_folders_for_probes(), initialize(), and thermal_subresolution_outputs().
overall_bubbles_quantities_folder_
Nom IJK_Thermals::overall_bubbles_quantities_folder_ protected
Referenced by create_folders_for_probes(), initialize(), and thermal_subresolution_outputs().
interfacial_quantities_thermal_probes_folder_
Nom IJK_Thermals::interfacial_quantities_thermal_probes_folder_ protected
Referenced by create_folders_for_probes(), initialize(), and thermal_subresolution_outputs().
shell_quantities_thermal_probes_folder_
Nom IJK_Thermals::shell_quantities_thermal_probes_folder_ protected
Referenced by create_folders_for_probes(), initialize(), and thermal_subresolution_outputs().
local_quantities_thermal_probes_folder_
Nom IJK_Thermals::local_quantities_thermal_probes_folder_ protected
Referenced by create_folders_for_probes(), initialize(), and thermal_subresolution_outputs().
local_quantities_thermal_probes_time_index_folder_
Nom IJK_Thermals::local_quantities_thermal_probes_time_index_folder_ protected
Referenced by initialize(), and thermal_subresolution_outputs().
local_quantities_thermal_slices_folder_
Nom IJK_Thermals::local_quantities_thermal_slices_folder_ protected
Referenced by create_folders_for_probes(), initialize(), and thermal_subresolution_outputs().
local_quantities_thermal_slices_time_index_folder_
Nom IJK_Thermals::local_quantities_thermal_slices_time_index_folder_ protected
Referenced by initialize(), and thermal_subresolution_outputs().
local_quantities_thermal_lines_folder_
Nom IJK_Thermals::local_quantities_thermal_lines_folder_ protected
Referenced by create_folders_for_probes(), initialize(), and thermal_subresolution_outputs().
local_quantities_thermal_lines_time_index_folder_
Nom IJK_Thermals::local_quantities_thermal_lines_time_index_folder_ protected
Referenced by initialize(), and thermal_subresolution_outputs().
ini_folder_out_files_
int IJK_Thermals::ini_folder_out_files_ = 0 protected
Referenced by thermal_subresolution_outputs().
lata_step_reprise_ini_
std::vector<int> IJK_Thermals::lata_step_reprise_ini_ protected
Referenced by initialize(), and thermal_subresolution_outputs().
lata_step_reprise_
std::vector<int> IJK_Thermals::lata_step_reprise_ protected
Referenced by initialize().