TrioCFD: Interpolation_IBM_power_law_tbl_proto Class Reference
Interpolation_IBM_power_law_tbl_proto Class Reference
#include <Interpolation_IBM_power_law_tbl_proto.h>
Detailed Description
Pure C++ class to allow multiple inheritance in Interpolation_IBM_power_law_tbl
Member Function Documentation
get_A_pwl()
double Interpolation_IBM_power_law_tbl_proto::get_A_pwl () inline
References A_pwl_.
Referenced by Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl(), and Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl_u_star().
get_B_pwl()
double Interpolation_IBM_power_law_tbl_proto::get_B_pwl () inline
References B_pwl_.
Referenced by Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl(), and Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl_u_star().
get_y_c_p_pwl()
double Interpolation_IBM_power_law_tbl_proto::get_y_c_p_pwl () inline
References y_c_p_pwl_.
Referenced by Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl(), and Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl_u_star().
Member Data Documentation
A_pwl_
double Interpolation_IBM_power_law_tbl_proto::A_pwl_ = 8.3 protected
Referenced by get_A_pwl().
B_pwl_
double Interpolation_IBM_power_law_tbl_proto::B_pwl_ = 1./7. protected
Referenced by get_B_pwl().
y_c_p_pwl_
double Interpolation_IBM_power_law_tbl_proto::y_c_p_pwl_ = 11.81 protected
Referenced by get_y_c_p_pwl().