TrioCFD: Echange_externe_impose_rayo_transp Class Reference
Echange_externe_impose_rayo_transp Class Reference
#include <Echange_externe_impose_rayo_transp.h>
Public Member Functions
const Type_info * get_info () const override
void mettre_a_jour (double) override
const Type_info * get_info () const override
Public Member Functions inherited from Echange_impose_base
int a_mettre_a_jour_ss_pas_dt () override
void associer_fr_dis_base (const Frontiere_dis_base &) override
double emissivite (int num) const
double emissivite (int num, int k) const
const Type_info * get_info () const override
virtual double h_imp (int num) const
virtual double h_imp (int num, int k) const
int initialiser (double temps) override
void mettre_a_jour (double) override
virtual Champ_front_base & T_ext ()
virtual double T_ext (int num) const
virtual double T_ext (int num, int k) const
Public Member Functions inherited from Cond_lim_base
virtual int a_mettre_a_jour_ss_pas_dt ()
virtual void associer_domaine_cl_dis_base (const Domaine_Cl_dis_base &)
virtual void associer_fr_dis_base (const Frontiere_dis_base &)
virtual void calculer_coeffs_echange (double temps)
virtual int compatible_avec_discr (const Discretisation_base &) const
Domaine_Cl_dis_base & domaine_Cl_dis ()
const Domaine_Cl_dis_base & domaine_Cl_dis () const
virtual Frontiere_dis_base & frontiere_dis ()
virtual const Frontiere_dis_base & frontiere_dis () const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
void set_modifier_val_imp (int)
virtual void verifie_ch_init_nb_comp () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Echange_externe_impose
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
void verifie_ch_init_nb_comp () const override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Cond_lim_base
void err_pas_compatible (const Discretisation_base &) const
void err_pas_compatible (const Equation_base &) const
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Echange_externe_impose_rayo_transp()
Echange_externe_impose_rayo_transp::Echange_externe_impose_rayo_transp ()
~Echange_externe_impose_rayo_transp()
Echange_externe_impose_rayo_transp::~Echange_externe_impose_rayo_transp ()
Member Function Documentation
cree_instance()
Objet_U * Echange_externe_impose_rayo_transp::cree_instance () static
taille_memoire()
unsigned Echange_externe_impose_rayo_transp::taille_memoire () const override virtual
Reimplemented from Echange_externe_impose.
duplique()
int Echange_externe_impose_rayo_transp::duplique () const override virtual
Reimplemented from Echange_externe_impose.
info()
const Type_info * Echange_externe_impose_rayo_transp::info () static
get_info()
const Type_info * Echange_externe_impose_rayo_transp::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Echange_externe_impose.
self_cast() [1/2]
Echange_externe_impose_rayo_transp & Echange_externe_impose_rayo_transp::self_cast (Objet_U & r) static
self_cast() [2/2]
const Echange_externe_impose_rayo_transp & Echange_externe_impose_rayo_transp::self_cast (const Objet_U & r) static
printOn()
Sortie & Echange_externe_impose_rayo_transp::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Echange_externe_impose.
readOn()
Entree & Echange_externe_impose_rayo_transp::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Echange_externe_impose.
References Process::exit(), Echange_impose_base::h_imp_, Cond_lim_base::le_champ_front, Motcles::search(), and Champ_front_base::valeurs().
compatible_avec_eqn()
int Echange_externe_impose_rayo_transp::compatible_avec_eqn (const Equation_base &) const inline override virtual
Reimplemented from Cond_lim_base.
completer()
void Echange_externe_impose_rayo_transp::completer () override virtual
Reimplemented from Cond_Lim_Rayo.
References Cond_lim_base::completer(), Cond_lim_base::domaine_Cl_dis(), Cond_lim_base::frontiere_dis(), and Cond_Lim_Rayo::preparer_surface().
mettre_a_jour()
void Echange_externe_impose_rayo_transp::mettre_a_jour (double temps) override virtual
Effectue une mise a jour en temps des conditions aux limites.
Lors du premier appel des initialisations sont effectuees: h_imp(0,0) = (rho(0,0)*Cp(0,0))
Parameters
(double temps) le temp de mise a jour
Reimplemented from Echange_impose_base.
References calculer_Teta_i(), and Echange_impose_base::mettre_a_jour().
calculer_Teta_i()
void Echange_externe_impose_rayo_transp::calculer_Teta_i ()
References Cond_lim_base::frontiere_dis(), Front_VF::nb_faces(), Echange_impose_base::T_ext(), and Cond_Lim_Rayo::Teta_i.
Referenced by mettre_a_jour().
Member Data Documentation
info_obj
const Type_info Echange_externe_impose_rayo_transp::info_obj static