TrioCFD: Filter_kernel_base Class Reference
Filter_kernel_base Class Reference abstract
#include <Filter_kernel.h>
Constructor & Destructor Documentation
Filter_kernel_base()
Filter_kernel_base::Filter_kernel_base (int ghost_size, double n_mailles, bool ponderation, bool normalisation) inline
~Filter_kernel_base()
virtual Filter_kernel_base::~Filter_kernel_base () inline virtual
Member Function Documentation
inhomogeneous()
virtual FixedVector< double, 21 > Filter_kernel_base::inhomogeneous (const bool elem, const int k, const int kg, const int nktot, const double delta, const ArrOfDouble_with_ghost & delta_z) pure virtual
Implemented in Filter_kernel_box, Filter_kernel_weight_13_13_base, Filter_kernel_weight_12_14_base, Filter_kernel_weight_23_16_base, Filter_kernel_weight_14_14_18_base, Filter_kernel_weight_15_15_15_base, Filter_kernel_weight_16_16_16_112_base, Filter_kernel_weight_14_38_base, and Filter_kernel_laplacian.
uniform()
virtual FixedVector< double, 21 > Filter_kernel_base::uniform (double delta, double dz) pure virtual
Implemented in Filter_kernel_box, Filter_kernel_weight_13_13_base, Filter_kernel_weight_12_14_base, Filter_kernel_weight_23_16_base, Filter_kernel_weight_14_14_18_base, Filter_kernel_weight_15_15_15_base, Filter_kernel_weight_16_16_16_112_base, Filter_kernel_weight_14_38_base, and Filter_kernel_laplacian.
ghost_size()
int Filter_kernel_base::ghost_size () inline
Referenced by DNS_QC_double::run(), shift_k_elem(), shift_k_face(), shift_uniform(), size_k_elem(), size_k_face(), and size_uniform().
n_mailles()
double Filter_kernel_base::n_mailles () inline
Referenced by DNS_QC_double::run().
ponderation()
bool Filter_kernel_base::ponderation () inline
normalisation()
bool Filter_kernel_base::normalisation () inline
size_uniform()
int Filter_kernel_base::size_uniform () inline
References ghost_size().
size_k_elem()
int Filter_kernel_base::size_k_elem (const int kg, const int nktot) inline
References ghost_size().
size_k_face()
int Filter_kernel_base::size_k_face (const int kg, const int nktot) inline
References ghost_size().
shift_uniform()
int Filter_kernel_base::shift_uniform () inline
References ghost_size().
shift_k_elem()
int Filter_kernel_base::shift_k_elem (const int kg) inline
References ghost_size().
shift_k_face()
int Filter_kernel_base::shift_k_face (const int kg) inline
References ghost_size().
is_at_wall_elem()
bool Filter_kernel_base::is_at_wall_elem (const int kg, const int nktot) inline
is_at_wall_face()
bool Filter_kernel_base::is_at_wall_face (const int kg, const int nktot) inline