TrioCFD: Eval_Conv_PolyMAC Class Reference
Eval_Conv_PolyMAC Class Reference
#include <Eval_Conv_PolyMAC.h>
Constructor & Destructor Documentation
Eval_Conv_PolyMAC() [1/2]
Eval_Conv_PolyMAC::Eval_Conv_PolyMAC () inline
constructeur par defaut
Eval_Conv_PolyMAC() [2/2]
Eval_Conv_PolyMAC::Eval_Conv_PolyMAC (const Eval_Conv_PolyMAC & eval) inline
References dt_vitesse, and TRUSTTab< _TYPE_, _SIZE_ >::ref().
Member Function Documentation
associer()
void Eval_Conv_PolyMAC::associer (const Champ_Face_PolyMAC & vit)
References dt_vitesse, TRUSTTab< _TYPE_, _SIZE_ >::ref(), Champ_Inc_base::valeurs(), and vitesse_.
Referenced by Op_Conv_Amont_PolyMAC_Elem::associer_vitesse(), and Op_Conv_Centre_PolyMAC_Elem::associer_vitesse().
mettre_a_jour()
void Eval_Conv_PolyMAC::mettre_a_jour ()
References dt_vitesse, TRUSTTab< _TYPE_, _SIZE_ >::ref(), and vitesse_.
vitesse() [1/2]
const Champ_Inc_base & Eval_Conv_PolyMAC::vitesse () const
References TRUST_Ref< _CLASSE_ >::valeur(), and vitesse_.
Referenced by Op_Conv_Amont_PolyMAC_Elem::vitesse(), and Op_Conv_Centre_PolyMAC_Elem::vitesse().
vitesse() [2/2]
Champ_Inc_base & Eval_Conv_PolyMAC::vitesse ()
References TRUST_Ref< _CLASSE_ >::valeur(), and vitesse_.
Member Data Documentation
vitesse_
TRUST_Ref< Champ_Face_PolyMAC *> Eval_Conv_PolyMAC::vitesse_ protected
Referenced by associer(), mettre_a_jour(), and vitesse().
dt_vitesse
DoubleTab Eval_Conv_PolyMAC::dt_vitesse protected
Referenced by associer(), Eval_Amont_PolyMAC_Elem::coeffs_face(), Eval_centre_PolyMAC_Elem::coeffs_face(), Eval_Amont_PolyMAC_Elem::coeffs_face_bloc_vitesse(), Eval_Amont_PolyMAC_Elem::coeffs_faces_interne(), Eval_centre_PolyMAC_Elem::coeffs_faces_interne(), Eval_Amont_PolyMAC_Elem::coeffs_faces_interne_bloc_vitesse(), Eval_Conv_PolyMAC(), Eval_Amont_PolyMAC_Elem::flux_face(), Eval_centre_PolyMAC_Elem::flux_face(), Eval_Amont_PolyMAC_Elem::flux_faces_interne(), Eval_centre_PolyMAC_Elem::flux_faces_interne(), mettre_a_jour(), Eval_Amont_PolyMAC_Elem::secmem_face(), and Eval_centre_PolyMAC_Elem::secmem_face().