TrioCFD: SurfaceVapeurIJKComputation Class Reference
SurfaceVapeurIJKComputation Class Reference
#include <SurfaceVapeurIJKComputation.h>
Constructor & Destructor Documentation
SurfaceVapeurIJKComputation()
SurfaceVapeurIJKComputation::SurfaceVapeurIJKComputation () inline
~SurfaceVapeurIJKComputation()
SurfaceVapeurIJKComputation::~SurfaceVapeurIJKComputation () inline
Member Function Documentation
initialize()
void SurfaceVapeurIJKComputation::initialize (const Domaine_IJK & splitting)
References compute_surf_mouillees_, desactive_med_, maillage_bulles_med_, and ref_domaine_.
Referenced by IJK_Interfaces::initialize().
compute_surf_and_barys()
int SurfaceVapeurIJKComputation::compute_surf_and_barys (const Maillage_FT_IJK & maillage_ft_ijk, const IJK_Field_double & indicatrice_ft, const IJK_Field_vector3_double & normale_of_interf, IJK_Field_vector3_double & surface_vapeur_par_face, FixedVector< IJK_Field_vector3_double, 3 > & barycentre_vapeur_par_face)
References calculer_surfaces_et_barys_faces_mouillees_vapeur(), compute_surf_mouillees_, desactive_med_, and rempli_surface_vapeur_par_face_interieur_bulles().
Referenced by IJK_Interfaces::calculer_indicatrice_next().
get_maillage_MED_from_IJK_FT()
void SurfaceVapeurIJKComputation::get_maillage_MED_from_IJK_FT (MEDCouplingUMesh * maillage_bulles_mcu, const Maillage_FT_IJK & maillage_bulles_ft_ijk) static
References TRUSTArray< _TYPE_, _SIZE_ >::addr(), Maillage_FT_Disc::facettes(), Maillage_FT_Disc::nb_facettes(), Maillage_FT_Disc::nb_sommets(), and Maillage_FT_Disc::sommets().
Referenced by set_maillage_MED().
set_compute_surfaces_mouillees()
void SurfaceVapeurIJKComputation::set_compute_surfaces_mouillees () inline
References compute_surf_mouillees_.
Referenced by IJK_Interfaces::set_compute_surfaces_mouillees().
rempli_surface_vapeur_par_face_interieur_bulles()
int SurfaceVapeurIJKComputation::rempli_surface_vapeur_par_face_interieur_bulles (IJK_Field_vector3_double & surface_vapeur_par_face, const IJK_Field_double & indicatrice_ft) protected
References ref_domaine_.
Referenced by compute_surf_and_barys().
set_maillage_MED()
void SurfaceVapeurIJKComputation::set_maillage_MED (const Maillage_FT_IJK & maillage_ft_ijk) protected
References get_maillage_MED_from_IJK_FT(), and maillage_bulles_med_.
Referenced by calculer_surfaces_et_barys_faces_mouillees_vapeur().
calculer_surfaces_et_barys_faces_mouillees_vapeur()
void SurfaceVapeurIJKComputation::calculer_surfaces_et_barys_faces_mouillees_vapeur (const Maillage_FT_IJK & maillage_ft_ijk, const IJK_Field_vector3_double & normale_of_interf, IJK_Field_vector3_double & surfaces, FixedVector< IJK_Field_vector3_double, 3 > & barycentres) protected
References check_if_vect_is_from_liquid2vapor(), IJK_Field_vector< T, N >::echange_espace_virtuel(), findCommonTuples(), IJK_Field_vector< T, N >::get_domaine(), get_IJK_ind_from_ind2d(), Domaine_IJK::get_nb_elem_local(), get_vect_from_sub_cells_tuple(), Process::je_suis_maitre(), maillage_bulles_med_, order_elem_mesh_filaire(), set_maillage_MED(), and slice_bubble().
Referenced by compute_surf_and_barys().
get_vect_from_sub_cells_tuple()
void SurfaceVapeurIJKComputation::get_vect_from_sub_cells_tuple (const int dim, const DataArrayDouble * bary0, const DataArrayIdType * cIcellsIdinMesh0, const DataArrayIdType * cellsIdinMesh0, DataArrayDouble * vect) const protected
Referenced by calculer_surfaces_et_barys_faces_mouillees_vapeur().
slice_bubble()
void SurfaceVapeurIJKComputation::slice_bubble (const double intersect_pt, const int dim, DataArrayIdType * cutcellsid, bool & plan_cut_some_bubble, MCU & mesh1dfil) const protected
References maillage_bulles_med_.
Referenced by calculer_surfaces_et_barys_faces_mouillees_vapeur().
findCommonTuples()
void SurfaceVapeurIJKComputation::findCommonTuples (const DataArrayIdType * mesh_merge, const mcIdType n_tot_mesh2d, DataArrayIdType * tab_id_subcells, DataArrayIdType * tab_id_cut_cells) const protected
Referenced by calculer_surfaces_et_barys_faces_mouillees_vapeur().
order_elem_mesh_filaire()
void SurfaceVapeurIJKComputation::order_elem_mesh_filaire (MEDCouplingUMesh * mesh1D) static protected
Referenced by calculer_surfaces_et_barys_faces_mouillees_vapeur().
get_IJK_ind_from_ind2d()
void SurfaceVapeurIJKComputation::get_IJK_ind_from_ind2d (const int dim, const int i_plan, const trustIdType i_2d, const int nx, std::array< int, 3 > & ijk_coo) const protected
References Process::check_int_overflow().
Referenced by calculer_surfaces_et_barys_faces_mouillees_vapeur(), and check_if_vect_is_from_liquid2vapor().
check_if_vect_is_from_liquid2vapor()
void SurfaceVapeurIJKComputation::check_if_vect_is_from_liquid2vapor (const IJK_Field_vector3_double & normale_of_interf, const DataArrayDouble * vector, const int dim, const int i_plan, const int nx, const DataArrayIdType * ids_diph, DataArrayIdType * ids_IJ_cell_from_diph) const protected
References get_IJK_ind_from_ind2d().
Referenced by calculer_surfaces_et_barys_faces_mouillees_vapeur().
Member Data Documentation
maillage_bulles_med_
MCU SurfaceVapeurIJKComputation::maillage_bulles_med_ protected
Referenced by calculer_surfaces_et_barys_faces_mouillees_vapeur(), initialize(), set_maillage_MED(), and slice_bubble().
ref_domaine_
TRUST_Ref< Domaine_IJK *> SurfaceVapeurIJKComputation::ref_domaine_ protected
Referenced by initialize(), and rempli_surface_vapeur_par_face_interieur_bulles().
desactive_med_
bool SurfaceVapeurIJKComputation::desactive_med_ protected
Referenced by compute_surf_and_barys(), and initialize().
compute_surf_mouillees_
bool SurfaceVapeurIJKComputation::compute_surf_mouillees_ protected
Referenced by compute_surf_and_barys(), initialize(), and set_compute_surfaces_mouillees().
debug_printing_
bool SurfaceVapeurIJKComputation::debug_printing_ protected