TrioCFD: Paroi_Cisaillement_Imp_VEF Class Reference
Paroi_Cisaillement_Imp_VEF Class Reference
#include <Paroi_Cisaillement_Imp_VEF.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Turbulence_paroi_base
void associer_modele (const Modele_turbulence_hyd_base &)
int calculer_hyd (Champ_Fonc_base &, Champ_Fonc_base &)
int calculer_hyd (Champ_Inc_base &)
const Type_info * get_info () const override
virtual void imprimer_premiere_ligne_ustar (int, const TRUST_List< Nom > &, const Nom &) const
virtual void imprimer_ustar_mean_only (Sortie &, int, const TRUST_List< Nom > &, const Nom &) const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Turbulence_paroi_base
static void typer_lire_turbulence_paroi (TRUST_Deriv< Turbulence_paroi_base > &, const Modele_turbulence_hyd_base &, Entree &)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
Utiliser plutot des conditions de symetrie et une perte de cherge volumique :
Loi de parois qui calcule le frottement a la paroi a partir d'une expression analytique donnee, fonction de la vitesse en premiere maille.
Suppose que la vitesse dans cette maille est la vitesse moyenne de l'ecoulement, cad que le canal ne fait qu'une maille d'epaisseur.
A utiliser avec un modele de turbulence negligeable, i.e. qui renvoie une viscosite turbulente nulle (par ex. Smagorinsky, avec Cs=0) CLASS: Paroi_Cisaillement_Imp_VEF
.SECTION voir aussi Turbulence_paroi_base
Constructor & Destructor Documentation
Paroi_Cisaillement_Imp_VEF()
Paroi_Cisaillement_Imp_VEF::Paroi_Cisaillement_Imp_VEF ()
~Paroi_Cisaillement_Imp_VEF()
Paroi_Cisaillement_Imp_VEF::~Paroi_Cisaillement_Imp_VEF ()
Member Function Documentation
cree_instance()
Objet_U * Paroi_Cisaillement_Imp_VEF::cree_instance () static
taille_memoire()
unsigned Paroi_Cisaillement_Imp_VEF::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Paroi_Cisaillement_Imp_VEF::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Paroi_Cisaillement_Imp_VEF::info () static
get_info()
const Type_info * Paroi_Cisaillement_Imp_VEF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Paroi_hyd_base_VEF.
self_cast() [1/2]
Paroi_Cisaillement_Imp_VEF & Paroi_Cisaillement_Imp_VEF::self_cast (Objet_U & r) static
self_cast() [2/2]
const Paroi_Cisaillement_Imp_VEF & Paroi_Cisaillement_Imp_VEF::self_cast (const Objet_U & r) static
printOn()
Sortie & Paroi_Cisaillement_Imp_VEF::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Paroi_hyd_base_VEF.
References Objet_U::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Paroi_Cisaillement_Imp_VEF::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Paroi_hyd_base_VEF.
References Paroi_UTAU_IMP_Impl::lire_donnees().
init_lois_paroi()
int Paroi_Cisaillement_Imp_VEF::init_lois_paroi () override virtual
Implements Turbulence_paroi_base.
References Paroi_hyd_base_VEF::init_lois_paroi_().
calculer_hyd() [1/2]
int Paroi_Cisaillement_Imp_VEF::calculer_hyd (DoubleTab & tab_k_eps) override virtual
Implements Turbulence_paroi_base.
calculer_hyd_BiK()
int Paroi_Cisaillement_Imp_VEF::calculer_hyd_BiK (DoubleTab & tab_k, DoubleTab & tab_eps) override virtual
Implements Turbulence_paroi_base.
calculer_hyd() [2/2]
int Paroi_Cisaillement_Imp_VEF::calculer_hyd (DoubleTab & tab_nu_t, DoubleTab & tab_k) override virtual
Implements Turbulence_paroi_base.
Member Data Documentation
info_obj
const Type_info Paroi_Cisaillement_Imp_VEF::info_obj static