TrioCFD: Modele_rayo_semi_transp Class Reference
Modele_rayo_semi_transp Class Reference
#include <Modele_rayo_semi_transp.h>
Public Member Functions
void associer_sch_tps_base (const Schema_Temps_base &) override
double calculer_pas_de_temps () const override
void completer () override
double computeTimeStep (bool &stop) const override
void discretiser (Discretisation_base &) override
const Type_info * get_info () const override
bool initTimeStep (double dt) override
bool iterateTimeStep (bool &converged) override
void mettre_a_jour (double temps) override
void terminate () override
void validateTimeStep () override
Public Member Functions inherited from Probleme_base
void abortTimeStep () override
int associer_ (Objet_U &) override
virtual void associer_domaine (const Domaine &)
virtual void associer_milieu_base (const Milieu_base &)
virtual void associer_sch_tps_base (const Schema_Temps_base &)
virtual double calculer_pas_de_temps () const
virtual void completer ()
double computeTimeStep (bool &stop) const override
const Discretisation_base & discretisation () const
virtual void discretiser (Discretisation_base &)
Domaine & domaine ()
const Domaine & domaine () const
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
Equation_base & equation (const Nom &)
const Equation_base & equation (const Nom &) const
TRUST_Ref< Field_base * > findInputField (const Nom &name) const override
virtual void finir ()
double futureTime () const override
const Type_info * get_info () const override
void getInputFieldsNames (Noms &noms) const override
void getOutputFieldsNames (Noms &noms) const override
virtual void imprimer (Sortie &os) const
void initialize () override
bool initTimeStep (double dt) override
bool isStationary () const override
bool iterateTimeStep (bool &converged) override
int limpr () const override
int lsauv () const override
virtual void mettre_a_jour (double temps)
virtual Milieu_base & milieu ()
virtual const Milieu_base & milieu () const
int postraiter (int force=1) override
double presentTime () const override
int reprendre (Entree &) override
void resetTime (double time) override
int sauvegarder (Sortie &) const override
Schema_Temps_base & schema_temps ()
const Schema_Temps_base & schema_temps () const
void terminate () override
bool updateGivenFields () override
void validateTimeStep () override
virtual int verifier ()
Public Member Functions inherited from Probleme_U
virtual void abortTimeStep ()
virtual double computeTimeStep (bool &stop) const
virtual TRUST_Ref< Field_base * > findInputField (const Nom &name) const
virtual double futureTime () const
const Type_info * get_info () const override
virtual void getInputFieldsNames (Noms &noms) const
virtual void getOutputFieldsNames (Noms &noms) const
virtual void initialize ()
virtual bool initTimeStep (double dt)
virtual bool isStationary () const
virtual bool iterateTimeStep (bool &converged)
const Nom & le_nom () const override
void nommer (const Nom &name) override
virtual int postraiter (int force=1)
virtual double presentTime () const
virtual void resetTime (double time)
virtual bool run ()
virtual bool runUntil (double time)
virtual void terminate ()
virtual bool updateGivenFields ()
virtual void validateTimeStep ()
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
Cela impose de differer certaines initialisations jusqu'a connaitre la discretisation utilisee.
Il partage son domaine avec un probleme de type hydraulique En l'etat actuel, toute la geometrie est clonee (donc postraitee 2 fois!) Apres le travail de B. Mathieu sur la geometrie, ce ne sera plus necessaire.
Il n'y a qu'une seule valeur temporelle (futur=present). Il faudrait en faire un probleme independant du temps.
Il conserve une ref sur le probleme hydraulique. Cette ref est utilisee de maniere intensive.
See also
Pb_Couple_rayo_semi_transp Equation_rayonnement_base
Constructor & Destructor Documentation
Modele_rayo_semi_transp()
Modele_rayo_semi_transp::Modele_rayo_semi_transp ()
~Modele_rayo_semi_transp()
Modele_rayo_semi_transp::~Modele_rayo_semi_transp ()
Member Function Documentation
cree_instance()
Objet_U * Modele_rayo_semi_transp::cree_instance () static
taille_memoire()
unsigned Modele_rayo_semi_transp::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Modele_rayo_semi_transp::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Modele_rayo_semi_transp::info () static
get_info()
const Type_info * Modele_rayo_semi_transp::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Probleme_base.
self_cast() [1/2]
Modele_rayo_semi_transp & Modele_rayo_semi_transp::self_cast (Objet_U & r) static
self_cast() [2/2]
const Modele_rayo_semi_transp & Modele_rayo_semi_transp::self_cast (const Objet_U & r) static
printOn()
Sortie & Modele_rayo_semi_transp::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Probleme_base.
readOn()
Entree & Modele_rayo_semi_transp::readOn (Entree & is) override protected virtual
Lecture d'un probleme dans un flot d'entree, et ouverture du flot de sauvegarde.
Format: { nom_milieu bloc de lecture d'un milieu nom_equation bloc de lecture d'une equation Postraitement bloc de lecture postraitement reprise | sauvegarde | sauvegarde_simple formatte | binaire | pdi nom_de_fichier } L'option sauvegarde_simple permet de sauver le probleme dans le fichier choisi en ecrasant a chaque fois les sauvegardes precedentes : cela permet d'economiser de la place disque.
Parameters
(Entree& is) flot d'entree
Returns
(Entree&) le flot d'entre modifie
Exceptions
pas d'accolade ouvrante en debut de format
mot clef "Postraitement" n'est pas la
format de sauvegarde doit etre "binaire" ou "formatte"
pas d'accolade fermante en fin de jeu de donnee
Reimplemented from Probleme_base.
References Probleme_base::readOn().
terminate()
void Modele_rayo_semi_transp::terminate () inline override virtual
This method is called once at the end, after any other one.
It frees the memory and saves anything that needs to be saved.
Exceptions
WrongContext
Reimplemented from Probleme_base.
References Probleme_base::finir().
computeTimeStep()
double Modele_rayo_semi_transp::computeTimeStep (bool & stop) const inline override virtual
Compute the value the Problem would like for the next time step.
This value will not necessarily be used at the call of initTimeStep, but it is a hint. This method may use all the internal state of the Problem.
Parameters
(stop) Does the Problem want to stop ?
Returns
(double) The desired time step
Exceptions
WrongContext
Reimplemented from Probleme_base.
initTimeStep()
bool Modele_rayo_semi_transp::initTimeStep (double dt) override virtual
This method allocates and initializes the unknown and given fields for the future time step.
The value of the interval is imposed through the parameter dt. In case of error, returns false.
Parameters
(double dt) the time interval to allocate
Returns
(bool) true=OK, false=error, not able to tackle this dt
Exceptions
WrongContext,WrongArgument
Reimplemented from Probleme_base.
References eq_rayo(), and Equation_rayonnement_base::initTimeStep().
iterateTimeStep()
bool Modele_rayo_semi_transp::iterateTimeStep (bool & converged) override virtual
In the case solveTimeStep uses an iterative process, this method executes a single iteration.
It is thus possible to modify the given fields between iterations. converged is set to true if the process has converged, ie if the unknown fields are solution to the problem on the next time step. Otherwise converged is set to false. The return value indicates if the convergence process behaves normally. If false, the Problem wishes to abort the time step resolution.
Parameters
(bool& converged) It is a return value : true if the process has converged, false otherwise.
Returns
(bool) true=OK, false=unable to converge
Exceptions
WrongContext
Reimplemented from Probleme_base.
References eq_rayo(), and Equation_rayonnement_base::solve().
validateTimeStep()
void Modele_rayo_semi_transp::validateTimeStep () override virtual
Validates the calculated unknown by moving the present time at the end of the time step.
This method is allowed to free past values of the unknown and given fields.
Exceptions
WrongContext
Reimplemented from Probleme_base.
References calculer_flux_radiatif(), eq_rayo(), Probleme_base::les_postraitements_, Schema_Temps_base::mettre_a_jour(), Equation_base::mettre_a_jour(), Postraitements::mettre_a_jour(), Probleme_base::presentTime(), probleme(), and Probleme_base::schema_temps().
completer()
void Modele_rayo_semi_transp::completer () inline override virtual
Complete les equations associees au probleme.
Remplissage des references, deleguee aux equations.
Reimplemented from Probleme_base.
nombre_d_equations()
int Modele_rayo_semi_transp::nombre_d_equations () const inline override virtual
Implements Probleme_base.
Referenced by discretiser().
equation() [1/2]
const Equation_base & Modele_rayo_semi_transp::equation (int i) const inline override virtual
Implements Probleme_base.
References Eq_rayo_.
Referenced by discretiser().
equation() [2/2]
Equation_base & Modele_rayo_semi_transp::equation (int i) inline override virtual
Implements Probleme_base.
References Eq_rayo_.
get_equation_by_name()
const Equation_base & Modele_rayo_semi_transp::get_equation_by_name (const Nom & un_nom) const inline override virtual
(B. Math): Methode virtuelle ajoutee pour les problemes ayant plusieurs equations de meme type (Probleme_FT_Disc_gen). Dans ce cas, le nom de l'equation n'est pas son type...
Reimplemented from Probleme_base.
References Eq_rayo_.
getset_equation_by_name()
Equation_base & Modele_rayo_semi_transp::getset_equation_by_name (const Nom & un_nom) inline override virtual
(B. Math): Methode virtuelle ajoutee pour les problemes ayant plusieurs equations de meme type (Probleme_FT_Disc_gen). Dans ce cas, le nom de l'equation n'est pas son type... Version non const. Cette methode est notamment appelee a la lecture du probleme.
Reimplemented from Probleme_base.
References Eq_rayo_.
calculer_pas_de_temps()
double Modele_rayo_semi_transp::calculer_pas_de_temps () const inline override virtual
Calcul la valeur du prochain pas de temps du probleme.
On calcule le minimum des pas de temps des equations associees au probleme.
Returns
(double) le pas de temps maximum autorise pour ce probleme
Reimplemented from Probleme_base.
mettre_a_jour()
void Modele_rayo_semi_transp::mettre_a_jour (double temps) inline override virtual
Effectue une mise a jour en temps du probleme.
Effectue la mise a jour sur toutes les equations du probleme.
Parameters
(double temps) le pas de temps de mise a jour
Reimplemented from Probleme_base.
References Process::exit().
is_pb_rayo()
bool Modele_rayo_semi_transp::is_pb_rayo () inline override virtual
Reimplemented from Probleme_base.
preparer_calcul()
void Modele_rayo_semi_transp::preparer_calcul () override virtual
Prepare le calcul: initialise les parametres du milieu et prepare le calcul de chacune des equations.
Reimplemented from Probleme_base.
References Cond_Lim_rayo_semi_transp::associer_modele(), Equation_rayonnement_base::completer(), Equation_base::domaine_Cl_dis(), eq_rayo(), Probleme_base::equation(), Process::exit(), Echange_contact_rayo_semi_transp_VDF::la_Cl_opposee(), Domaine_Cl_dis_base::les_conditions_limites(), Domaine_Cl_dis_base::nb_cond_lim(), Probleme_base::nombre_d_equations(), probleme(), Objet_U::que_suis_je(), Cond_Lim_rayo_semi_transp::recherche_emissivite_et_A(), TRUST_List< _CLASSE_ >::size(), Equation_base::sources(), and TRUST_Deriv< _CLASSE_ >::valeur().
discretiser()
void Modele_rayo_semi_transp::discretiser (Discretisation_base & une_discretisation) override virtual
Affecte une discretisation au probleme Discretise le Domaine associe au probleme avec la discretisation.
Associe le premier Domaine aux equations du probleme
Discretise les equations associees au probleme
Parameters
(Discretisation_base& discretisation) une discretisation pour le probleme
Reimplemented from Probleme_base.
References Probleme_base::associer(), Discretisation_base::associer_domaine(), Equation_base::associer_domaine_dis(), Equation_rayonnement_base::associer_fluide(), Equation_rayonnement_base::associer_modele_rayonnement(), Equation_base::associer_sch_tps_base(), Champ_base::changer_temps(), Equation_base::discretisation(), Equation_base::discretiser(), Discretisation_base::discretiser(), Probleme_base::domaine_dis(), Eq_rayo_, equation(), Probleme_base::equation(), Process::exit(), Field_base::fixer_nb_comp(), Champ_Don_base::fixer_nb_valeurs_nodales(), Field_base::fixer_unite(), Fluide_base::initialiser(), Fluide_base::is_rayo_semi_transp(), Fluide_base::kappa(), Probleme_base::la_discretisation_, Probleme_base::le_domaine_, Probleme_base::le_domaine_dis_, Probleme_U::le_nom(), Fluide_base::longueur_rayo(), Probleme_base::milieu(), nombre_d_equations(), Field_base::nommer(), probleme(), Objet_U::que_suis_je(), Probleme_base::schema_temps(), Schema_Temps_base::temps_courant(), Objet_U_ptr::typer(), and Fluide_base::typer_longeur_rayo().
associer_sch_tps_base()
void Modele_rayo_semi_transp::associer_sch_tps_base (const Schema_Temps_base & un_schema_en_temps) override virtual
Associe un schema en temps au probleme.
Associe ensuite le schema en temps a toutes les equations du probleme.
Parameters
(Schema_Temps_base& un_schema_en_temps) le schema en temps a associer
Reimplemented from Probleme_base.
References Probleme_base::le_schema_en_temps_.
Referenced by Pb_Couple_rayo_semi_transp::associer_sch_tps_base().
associer_probleme()
void Modele_rayo_semi_transp::associer_probleme (Probleme_base & Pb) inline
References mon_probleme_.
Referenced by Pb_Couple_rayo_semi_transp::le_modele_rayo_associe().
put_irradience()
Champ_Inc_base & Modele_rayo_semi_transp::put_irradience ()
References eq_rayo(), and Equation_rayonnement_base::inconnue().
probleme() [1/2]
Probleme_base & Modele_rayo_semi_transp::probleme () inline
References mon_probleme_, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by calculer_flux_radiatif(), discretiser(), Eq_rayo_semi_transp_VDF::evaluer_cl_rayonnement(), Eq_rayo_semi_transp_VEF::evaluer_cl_rayonnement(), Pb_Couple_rayo_semi_transp::initialize(), preparer_calcul(), Eq_rayo_semi_transp_VDF::resoudre(), Eq_rayo_semi_transp_VEF::resoudre(), and validateTimeStep().
probleme() [2/2]
const Probleme_base & Modele_rayo_semi_transp::probleme () const inline
References mon_probleme_, and TRUST_Ref< _CLASSE_ >::valeur().
eq_rayo() [1/2]
Equation_rayonnement_base & Modele_rayo_semi_transp::eq_rayo () inline
References Eq_rayo_, Objet_U_ptr::non_nul(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by Source_rayo_semi_transp_VDF_P0_VDF::ajouter(), Source_rayo_semi_transp_VEF_P1NC::ajouter(), calculer_flux_radiatif(), flux_radiatif(), Pb_Couple_rayo_semi_transp::initialize(), initTimeStep(), iterateTimeStep(), preparer_calcul(), put_irradience(), Cond_Lim_rayo_semi_transp::recherche_emissivite_et_A(), and validateTimeStep().
eq_rayo() [2/2]
const Equation_rayonnement_base & Modele_rayo_semi_transp::eq_rayo () const inline
References Eq_rayo_, Objet_U_ptr::non_nul(), and TRUST_Deriv< _CLASSE_ >::valeur().
valeur_sigma()
const double & Modele_rayo_semi_transp::valeur_sigma () const inline
References sigma.
Referenced by Source_rayo_semi_transp_VDF_P0_VDF::ajouter(), Source_rayo_semi_transp_VEF_P1NC::ajouter(), Flux_radiatif_VDF::calculer_flux_radiatif(), Flux_radiatif_VEF::calculer_flux_radiatif(), Eq_rayo_semi_transp_VDF::resoudre(), and Eq_rayo_semi_transp_VEF::resoudre().
flux_radiatif()
const Champ_front_base & Modele_rayo_semi_transp::flux_radiatif (const Nom & nom_bord) const
References Equation_base::domaine_Cl_dis(), eq_rayo(), Process::exit(), Flux_radiatif_base::flux_radiatif(), Objet_U_ptr::le_nom(), Domaine_Cl_dis_base::les_conditions_limites(), TRUST_Vector< _CLASSE_ >::size(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by Neumann_paroi_rayo_semi_transp_VDF::calculer_temperature_bord(), Echange_contact_rayo_semi_transp_VDF::calculer_Teta_equiv(), Echange_contact_rayo_semi_transp_VDF::calculer_Teta_paroi(), Neumann_paroi_rayo_semi_transp_VDF::flux_impose(), Neumann_paroi_rayo_semi_transp_VEF::flux_impose(), and Champ_front_contact_rayo_semi_transp_VEF::mettre_a_jour_flux_radiatif().
calculer_flux_radiatif()
void Modele_rayo_semi_transp::calculer_flux_radiatif ()
References Flux_radiatif_base::calculer_flux_radiatif(), Equation_base::domaine_Cl_dis(), eq_rayo(), Probleme_base::equation(), Process::exit(), Domaine_Cl_dis_base::les_conditions_limites(), probleme(), TRUST_Vector< _CLASSE_ >::size(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by Pb_Couple_rayo_semi_transp::initialize(), and validateTimeStep().
Member Data Documentation
info_obj
const Type_info Modele_rayo_semi_transp::info_obj static
mon_probleme_
TRUST_Ref< Probleme_base *> Modele_rayo_semi_transp::mon_probleme_ protected
Referenced by associer_probleme(), and probleme().
Eq_rayo_
TRUST_Deriv< Equation_rayonnement_base > Modele_rayo_semi_transp::Eq_rayo_ protected
Referenced by discretiser(), eq_rayo(), equation(), get_equation_by_name(), and getset_equation_by_name().
sigma
double const Modele_rayo_semi_transp::sigma = 5.67e-8 static protected
Referenced by valeur_sigma().