TrioCFD: Eval_Dirac_VEF_Face Class Reference
Eval_Dirac_VEF_Face Class Reference
#include <Eval_Dirac_VEF_Face.h>
Constructor & Destructor Documentation
Eval_Dirac_VEF_Face()
Eval_Dirac_VEF_Face::Eval_Dirac_VEF_Face () inline
Member Function Documentation
associer_champs()
void Eval_Dirac_VEF_Face::associer_champs (const Champ_Don_base & Q)
References la_puissance, puissance, and Champ_Don_base::valeurs().
Referenced by Source_Dirac_VEF_Face::associer_pb().
mettre_a_jour()
void Eval_Dirac_VEF_Face::mettre_a_jour () override virtual
Implements Evaluateur_Source.
References la_puissance, Evaluateur_Source::le_dom, mon_dom, and puissance.
calculer_terme_source_standard()
template<typename Type_Double > void Eval_Dirac_VEF_Face::calculer_terme_source_standard (const int num_face, Type_Double & source) const inline
References calculer_terme_source().
calculer_terme_source_non_standard()
template<typename Type_Double > void Eval_Dirac_VEF_Face::calculer_terme_source_non_standard (const int num_face, Type_Double & source) const inline
References calculer_terme_source().
associer_nb_elem_dirac()
void Eval_Dirac_VEF_Face::associer_nb_elem_dirac (int n)
References nb_dirac.
Referenced by Source_Dirac_VEF_Face::associer_domaines().
calculer_terme_source()
template<typename Type_Double > void Eval_Dirac_VEF_Face::calculer_terme_source (int num_face, Type_Double & source) const inline protected
References Process::exit(), Evaluateur_Source_VEF_Face::face_voisins, le_point, mon_dom, nb_dirac, and puissance.
Referenced by calculer_terme_source_non_standard(), and calculer_terme_source_standard().
Member Data Documentation
le_point
DoubleVect Eval_Dirac_VEF_Face::le_point
Referenced by Source_Dirac_VEF_Face::associer_pb(), and calculer_terme_source().
la_puissance
TRUST_Ref< Champ_Don_base *> Eval_Dirac_VEF_Face::la_puissance protected
Referenced by associer_champs(), and mettre_a_jour().
mon_dom
TRUST_Ref< Domaine *> Eval_Dirac_VEF_Face::mon_dom protected
Referenced by calculer_terme_source(), and mettre_a_jour().
puissance
double Eval_Dirac_VEF_Face::puissance protected
Referenced by associer_champs(), calculer_terme_source(), and mettre_a_jour().
nb_dirac
double Eval_Dirac_VEF_Face::nb_dirac protected
Referenced by associer_nb_elem_dirac(), and calculer_terme_source().