TrioCFD: Navier_Stokes_IBM_Turbulent Class Reference
Navier_Stokes_IBM_Turbulent Class Reference
#include <Navier_Stokes_IBM_Turbulent.h>
Public Member Functions
void completer () override
const Type_info * get_info () const override
void imprimer (Sortie &) const override
bool initTimeStep (double dt) override
int lire_motcle_non_standard (const Motcle &, Entree &) override
void mettre_a_jour (double) override
int preparer_calcul () override
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
const Type_info * get_info () const override
bool initTimeStep (double dt) override
int preparer_calcul () override
Public Member Functions inherited from Navier_Stokes_std
void abortTimeStep () override
void associer_milieu_base (const Milieu_base &) override
void associer_pb_base (const Probleme_base &) override
virtual void calculer_la_pression_en_pa ()
void completer () override
DoubleTab & derivee_en_temps_inco (DoubleTab &) override
const Motcle & domaine_application () const override
Fluide_base & fluide ()
const Fluide_base & fluide () const
const Type_info * get_info () const override
int impr (Sortie &os) const override
const Champ_Inc_base & inconnue () const override
Champ_Inc_base & inconnue () override
bool initTimeStep (double dt) override
Entree & lire_cond_init (Entree &) override
int lire_motcle_non_standard (const Motcle &, Entree &) override
void mettre_a_jour (double temps) override
const Milieu_base & milieu () const override
Milieu_base & milieu () override
int nombre_d_operateurs () const override
const Operateur & operateur (int) const override
Operateur & operateur (int) override
Operateur_Div & operateur_divergence ()
const Operateur_Div & operateur_divergence () const
Operateur_Grad & operateur_gradient ()
const Operateur_Grad & operateur_gradient () const
int preparer_calcul () override
virtual void projeter ()
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
SolveurSys & solveur_pression ()
int verif_Cl () const override
Public Member Functions inherited from Equation_base
virtual void abortTimeStep ()
virtual void associer_domaine_dis (const Domaine_dis_base &)
virtual void associer_pb_base (const Probleme_base &)
virtual void associer_sch_tps_base (const Schema_Temps_base &)
virtual double calculer_pas_de_temps () const
virtual void completer ()
virtual std::vector< YAML_data > data_a_sauvegarder () const
DoubleTab & derivee_en_temps_conv (DoubleTab &, const DoubleTab &)
virtual DoubleTab & derivee_en_temps_inco (DoubleTab &)
const Discretisation_base & discretisation () const
virtual void discretiser ()
virtual const Motcle & domaine_application () const
virtual Domaine_Cl_dis_base & domaine_Cl_dis ()
virtual const Domaine_Cl_dis_base & domaine_Cl_dis () const
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual void imprimer (Sortie &os) const
virtual bool initTimeStep (double dt)
const Nom & le_nom () const override
int limpr () const
virtual void mettre_a_jour (double temps)
virtual int preparer_calcul ()
Probleme_base & probleme ()
const Probleme_base & probleme () const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Schema_Temps_base & schema_temps ()
const Schema_Temps_base & schema_temps () const
Solveur_Masse_base & solv_masse ()
const Solveur_Masse_base & solv_masse () const
Sources & sources ()
const Sources & sources () const
virtual void valider_iteration ()
virtual void verifie_ch_init_nb_comp (const Champ_Inc_base &ch_ref, const int nb_comp) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Navier_Stokes_std
virtual void discretiser_assembleur_pression ()
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Equation_base
virtual Entree & lire_cl (Entree &)
virtual Entree & lire_cond_init (Entree &)
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual Entree & lire_sources (Entree &)
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
virtual int verif_Cl () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
visqueux verifiant la condition d'incompressibilite div U = 0 avec
modelisation de la turbulence.
Un membre de type OWN_PTR(Modele_turbulence_hyd_base)  representera le modele de turbulence.
See also
Navier_Stokes_IBM OWN_PTR(Modele_turbulence_hyd_base) Pb_Hydraulique_Turbulent, Pb_Thermohydraulique_Turbulent
Constructor & Destructor Documentation
Navier_Stokes_IBM_Turbulent()
Navier_Stokes_IBM_Turbulent::Navier_Stokes_IBM_Turbulent ()
~Navier_Stokes_IBM_Turbulent()
Navier_Stokes_IBM_Turbulent::~Navier_Stokes_IBM_Turbulent ()
Member Function Documentation
cree_instance()
Objet_U * Navier_Stokes_IBM_Turbulent::cree_instance () static
taille_memoire()
unsigned Navier_Stokes_IBM_Turbulent::taille_memoire () const override virtual
Reimplemented from Navier_Stokes_IBM.
duplique()
int Navier_Stokes_IBM_Turbulent::duplique () const override virtual
Reimplemented from Navier_Stokes_IBM.
info()
const Type_info * Navier_Stokes_IBM_Turbulent::info () static
get_info()
const Type_info * Navier_Stokes_IBM_Turbulent::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Navier_Stokes_IBM.
self_cast() [1/2]
Navier_Stokes_IBM_Turbulent & Navier_Stokes_IBM_Turbulent::self_cast (Objet_U & r) static
self_cast() [2/2]
const Navier_Stokes_IBM_Turbulent & Navier_Stokes_IBM_Turbulent::self_cast (const Objet_U & r) static
printOn()
Sortie & Navier_Stokes_IBM_Turbulent::printOn (Sortie & os) const override protected virtual
Surcharge Objet_U::printOn Imprime l'equation et ses composants sur un flot de sortie.
Imprime le nom de l'equation, le solveur masse, les termes sources les conditions aux limites discretisees, les inconnues et les operateurs.
Parameters
(Sortie& os) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Navier_Stokes_IBM.
References Equation_base::printOn().
readOn()
Entree & Navier_Stokes_IBM_Turbulent::readOn (Entree & is) override protected virtual
Lecture d'une equation sur un flot d'entree.
Le format est le suivant: { [Source { [sou_1], [sour_2], ...} ] Conditions_limites { [cl_1] [cl_2] ... } Conditions_initiales { [cl_init] } }
Parameters
(Entree& is) un flot d'entree pour lire l'equation
Returns
(Entree&) le flot d'entree modifie
Exceptions
mauvais format de lecture, accolade ouvrante attendue
pas de conditions initiales, il faut initialiser l'inconnue
pas de conditions aux limites, il faut donner des conditions aux limites
Reimplemented from Navier_Stokes_IBM.
References Navier_Stokes_IBM::readOn().
set_param()
void Navier_Stokes_IBM_Turbulent::set_param (Param & titi) override virtual
Reimplemented from Navier_Stokes_IBM.
References Param::ajouter_non_std(), Param::REQUIRED, and Navier_Stokes_IBM::set_param().
lire_motcle_non_standard()
int Navier_Stokes_IBM_Turbulent::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Equation_base.
References Operateur_Diff::associer_diffusivite(), Operateur_Diff::associer_diffusivite_pour_pas_de_temps(), diffusivite_pour_pas_de_temps(), diffusivite_pour_transport(), Navier_Stokes_std::lire_motcle_non_standard(), lire_op_diff_turbulent(), and Navier_Stokes_std::terme_diffusif.
viscosite_turbulente()
const Champ_Fonc_base & Navier_Stokes_IBM_Turbulent::viscosite_turbulente () const inline
References le_modele_turbulence, and Modele_turbulence_hyd_base::viscosite_turbulente().
Referenced by Pb_Hydraulique_IBM_Turbulent::viscosite_turbulente(), and Pb_Thermohydraulique_IBM_Turbulent::viscosite_turbulente().
modele_turbulence()
const Modele_turbulence_hyd_base & Navier_Stokes_IBM_Turbulent::modele_turbulence () const inline
References le_modele_turbulence, and TRUST_Deriv< _CLASSE_ >::valeur().
data_a_sauvegarder()
std::vector< YAML_data > Navier_Stokes_IBM_Turbulent::data_a_sauvegarder () const override virtual
for PDI IO: retrieve name, type and dimensions of the fields to save/restore
Reimplemented from Equation_base.
References Modele_turbulence_hyd_base::data_a_sauvegarder(), Navier_Stokes_std::data_a_sauvegarder(), and le_modele_turbulence.
sauvegarder()
int Navier_Stokes_IBM_Turbulent::sauvegarder (Sortie & os) const override virtual
Sauvegarde l'equation (et son modele de turbulence) sur un flot de sortie.
Parameters
(Sortie& os) un flot de sortie
Returns
(int) renvoie toujours 1
Reimplemented from Equation_base.
References le_modele_turbulence, Navier_Stokes_std::sauvegarder(), and Modele_turbulence_hyd_base::sauvegarder().
reprendre()
int Navier_Stokes_IBM_Turbulent::reprendre (Entree & is) override virtual
Reprise de l'equation et de son modele de turbulence a partir d'un flot d'entree.
Parameters
(Entree& is) un flot d'entree
Returns
(int) renvoie toujours 1
Exceptions
fin de fichier rencontre pendant la reprise
Reimplemented from Equation_base.
References Probleme_base::domaine(), TRUST_2_PDI::is_PDI_restart(), le_modele_turbulence, Domaine_base::le_nom(), Equation_base::probleme(), Objet_U::que_suis_je(), Navier_Stokes_std::reprendre(), Modele_turbulence_hyd_base::reprendre(), Equation_base::schema_temps(), and Schema_Temps_base::temps_courant().
preparer_calcul()
int Navier_Stokes_IBM_Turbulent::preparer_calcul () override virtual
Prepare le calcul.
Simple appe a Modele_turbulence_hyd_base->preparer_caclul() sur le membre reprresentant la turbulence.
Returns
(int) renvoie toujours 1
Reimplemented from Navier_Stokes_IBM.
References Modele_turbulence_hyd_base::has_loi_paroi_hyd(), Turbulence_paroi_base::init_lois_paroi(), le_modele_turbulence, Modele_turbulence_hyd_base::loi_paroi(), Modele_turbulence_hyd_base::preparer_calcul(), and Navier_Stokes_IBM::preparer_calcul().
initTimeStep()
bool Navier_Stokes_IBM_Turbulent::initTimeStep (double dt) override virtual
Allocation et initialisation de l'inconnue et des CLs jusqu'a present+dt.
autres initialisations pour les calculs sur le prochain pas de temps : operateurs, solveur_masse->
Returns
(0 en cas d'erreur, 1 sinon)
Reimplemented from Navier_Stokes_IBM.
References Modele_turbulence_hyd_base::initTimeStep(), Navier_Stokes_IBM::initTimeStep(), and le_modele_turbulence.
mettre_a_jour()
void Navier_Stokes_IBM_Turbulent::mettre_a_jour (double temps) override virtual
Effecttue une mise a jour en temps de l'equation.
Parameters
(double temps) le temps de mise a jour
Reimplemented from Equation_base.
References le_modele_turbulence, Navier_Stokes_std::mettre_a_jour(), and Modele_turbulence_hyd_base::mettre_a_jour().
completer()
void Navier_Stokes_IBM_Turbulent::completer () override virtual
Appels successifs a: Navier_Stokes_IBM::completer()
 Mod_Turb_Hyd::completer() [sur le membre concerne]
Reimplemented from Equation_base.
References Turbulence_paroi_base::completer(), Modele_turbulence_hyd_base::completer(), Navier_Stokes_std::completer(), le_modele_turbulence, and Modele_turbulence_hyd_base::loi_paroi().
diffusivite_pour_transport()
const Champ_Don_base & Navier_Stokes_IBM_Turbulent::diffusivite_pour_transport () const override virtual
Reimplemented from Navier_Stokes_std.
References Navier_Stokes_std::fluide(), and Fluide_base::viscosite_cinematique().
Referenced by lire_motcle_non_standard().
diffusivite_pour_pas_de_temps()
const Champ_base & Navier_Stokes_IBM_Turbulent::diffusivite_pour_pas_de_temps () const override virtual
Reimplemented from Navier_Stokes_std.
References Navier_Stokes_std::fluide(), and Fluide_base::viscosite_cinematique().
Referenced by lire_motcle_non_standard().
creer_champ()
void Navier_Stokes_IBM_Turbulent::creer_champ (const Motcle & motlu) override virtual
Reimplemented from Equation_base.
References Navier_Stokes_std::creer_champ(), Modele_turbulence_hyd_base::creer_champ(), le_modele_turbulence, and Objet_U_ptr::non_nul().
get_champ()
const Champ_base & Navier_Stokes_IBM_Turbulent::get_champ (const Motcle & nom) const override virtual
Reimplemented from Equation_base.
References Nom::getString(), Navier_Stokes_std::has_champ(), Modele_turbulence_hyd_base::has_champ(), le_modele_turbulence, and Objet_U_ptr::non_nul().
has_champ() [1/2]
bool Navier_Stokes_IBM_Turbulent::has_champ (const Motcle & nom, TRUST_Ref< Champ_base * > & ref_champ) const override virtual
Reimplemented from Equation_base.
References Navier_Stokes_std::has_champ(), Modele_turbulence_hyd_base::has_champ(), le_modele_turbulence, and Objet_U_ptr::non_nul().
has_champ() [2/2]
bool Navier_Stokes_IBM_Turbulent::has_champ (const Motcle & nom) const override virtual
Reimplemented from Equation_base.
References Navier_Stokes_std::has_champ(), Modele_turbulence_hyd_base::has_champ(), le_modele_turbulence, and Objet_U_ptr::non_nul().
get_noms_champs_postraitables()
void Navier_Stokes_IBM_Turbulent::get_noms_champs_postraitables (Noms & nom, Option opt = NONE) const override virtual
Reimplemented from Equation_base.
References Navier_Stokes_std::get_noms_champs_postraitables(), Modele_turbulence_hyd_base::get_noms_champs_postraitables(), le_modele_turbulence, and Objet_U_ptr::non_nul().
imprimer()
void Navier_Stokes_IBM_Turbulent::imprimer (Sortie & os) const override virtual
Imprime les operateurs de l'equation si le schema en temps indique que c'est necessaire.
[SI limpr() ALORS impr(os)]
Parameters
(Sortie& os) le flot de sortie
Reimplemented from Equation_base.
References Modele_turbulence_hyd_base::imprimer(), Equation_base::imprimer(), and le_modele_turbulence.
get_modele()
const RefObjU & Navier_Stokes_IBM_Turbulent::get_modele (Type_modele type) const override virtual
Reimplemented from Equation_base.
References Equation_base::get_modele(), Equation_base::liste_modeles_, TRUST_Ref_Objet_U::non_nul(), and TRUST_Ref_Objet_U::valeur().
imprime_residu()
void Navier_Stokes_IBM_Turbulent::imprime_residu (SFichier & fic) override virtual
Reimplemented from Equation_base.
References Equation_base::imprime_residu().
expression_residu()
Nom Navier_Stokes_IBM_Turbulent::expression_residu () override virtual
Reimplemented from Equation_base.
References Equation_base::expression_residu().
lire_op_diff_turbulent()
Entree & Navier_Stokes_IBM_Turbulent::lire_op_diff_turbulent (Entree & is) protected
References Operateur_Diff::associer_diffusivite(), Operateur_base::associer_eqn(), Objet_U::axi, Operateur_Diff::diffusivite(), Equation_base::discretisation(), Process::exit(), Navier_Stokes_std::inconnue(), Operateur_Diff::l_op_base(), Field_base::nb_comp(), Objet_U::que_suis_je(), Nom::suffix(), Navier_Stokes_std::terme_diffusif, Operateur_Diff::typer(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by lire_motcle_non_standard().
Member Data Documentation
info_obj
const Type_info Navier_Stokes_IBM_Turbulent::info_obj static
le_modele_turbulence
TRUST_Deriv< Modele_turbulence_hyd_base > Navier_Stokes_IBM_Turbulent::le_modele_turbulence protected
Referenced by completer(), creer_champ(), data_a_sauvegarder(), get_champ(), get_noms_champs_postraitables(), has_champ(), imprimer(), initTimeStep(), mettre_a_jour(), modele_turbulence(), preparer_calcul(), reprendre(), sauvegarder(), and viscosite_turbulente().