TrioCFD: Lata_2_Other Class Reference
Lata_2_Other Class Reference
#include <Lata_2_Other.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Interprete
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Interprete
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Interprete
static Objet_U & objet (const Nom &)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Lata_2_Other()
Lata_2_Other::Lata_2_Other ()
~Lata_2_Other()
Lata_2_Other::~Lata_2_Other ()
Member Function Documentation
cree_instance()
Objet_U * Lata_2_Other::cree_instance () static
taille_memoire()
unsigned Lata_2_Other::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Lata_2_Other::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Lata_2_Other::info () static
get_info()
const Type_info * Lata_2_Other::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
Lata_2_Other & Lata_2_Other::self_cast (Objet_U & r) static
self_cast() [2/2]
const Lata_2_Other & Lata_2_Other::self_cast (const Objet_U & r) static
printOn()
Sortie & Lata_2_Other::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
References Process::exit().
readOn()
Entree & Lata_2_Other::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
References Process::exit().
interpreter()
Entree & Lata_2_Other::interpreter (Entree & is) override virtual
Implements Interprete.
References Objet_U::axi, Process::barrier(), Nom::basename(), PE_Groups::create_group(), Nom::debute_par(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_int(), Format_Post_base::ecrire_champ(), Format_Post_base::ecrire_domaine(), Format_Post_base::ecrire_entete(), Format_Post_base::ecrire_temps(), PE_Groups::enter_group(), Process::exit(), PE_Groups::exit_group(), Format_Post_base::finir(), Nom::finit_par(), Nom::getChar(), Format_Post_base::init_ecriture(), Format_Post_base::initialize(), Format_Post_base::initialize_by_default(), Domaine_base::le_nom(), Domaine_32_64< _SIZE_ >::les_sommets(), Objet_U::nom_du_cas(), Domaine_base::nommer(), Nom::prefix(), Format_Post_base::preparer_post(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUST_Vector< _CLASSE_ >::size(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by Lata_2_CGNS::interpreter(), and Lata_2_MED::interpreter().
Member Data Documentation
info_obj
const Type_info Lata_2_Other::info_obj static