TrioCFD: Op_Grad_PolyMAC_P0P1NC_Face Class Reference
Op_Grad_PolyMAC_P0P1NC_Face Class Reference
#include <Op_Grad_PolyMAC_P0P1NC_Face.h>
Public Member Functions
void completer () override
const Type_info * get_info () const override
Public Member Functions inherited from Op_Grad_PolyMAC_Face
void contribuer_a_avec (const DoubleTab &inco, Matrice_Morse &matrice) const override
void dimensionner (Matrice_Morse &) const override
const Type_info * get_info () const override
int impr (Sortie &os) const override
void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const override
void dimensionner (Matrice_Morse &) const override
const Type_info * get_info () const override
Public Member Functions inherited from Operateur_base
void associer_eqn (const Equation_base &)
virtual double calculer_dt_stab () const
virtual void completer ()
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual void mettre_a_jour (double temps)
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
Cette classe represente l'operateur de gradient La discretisation est PolyMAC_P0P1NC On calcule le gradient d'un champ_Elem_PolyMAC_P0P1NC (la pression)
See also
Operateur_Grad_base
Constructor & Destructor Documentation
Op_Grad_PolyMAC_P0P1NC_Face()
Op_Grad_PolyMAC_P0P1NC_Face::Op_Grad_PolyMAC_P0P1NC_Face ()
~Op_Grad_PolyMAC_P0P1NC_Face()
Op_Grad_PolyMAC_P0P1NC_Face::~Op_Grad_PolyMAC_P0P1NC_Face ()
Member Function Documentation
cree_instance()
Objet_U * Op_Grad_PolyMAC_P0P1NC_Face::cree_instance () static
taille_memoire()
unsigned Op_Grad_PolyMAC_P0P1NC_Face::taille_memoire () const override virtual
Reimplemented from Op_Grad_PolyMAC_Face.
duplique()
int Op_Grad_PolyMAC_P0P1NC_Face::duplique () const override virtual
Reimplemented from Op_Grad_PolyMAC_Face.
info()
const Type_info * Op_Grad_PolyMAC_P0P1NC_Face::info () static
get_info()
const Type_info * Op_Grad_PolyMAC_P0P1NC_Face::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Op_Grad_PolyMAC_Face.
self_cast() [1/2]
Op_Grad_PolyMAC_P0P1NC_Face & Op_Grad_PolyMAC_P0P1NC_Face::self_cast (Objet_U & r) static
self_cast() [2/2]
const Op_Grad_PolyMAC_P0P1NC_Face & Op_Grad_PolyMAC_P0P1NC_Face::self_cast (const Objet_U & r) static
printOn()
Sortie & Op_Grad_PolyMAC_P0P1NC_Face::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN A surcharger dans les classes derivees.
Parameters
(Sortie& os) un flot de sortie
Returns
(Sortie&) le flot de sortie
Reimplemented from Op_Grad_PolyMAC_Face.
References Objet_U::que_suis_je().
readOn()
Entree & Op_Grad_PolyMAC_P0P1NC_Face::readOn (Entree & is) override protected virtual
NE FAIT RIEN A surcharger dans les classes derivees.
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree
Reimplemented from Op_Grad_PolyMAC_Face.
completer()
void Op_Grad_PolyMAC_P0P1NC_Face::completer () override virtual
Associe l'operateur au domaine_dis, le domaine_Cl_dis, et a l'inconnue de son equation.
Exceptions
pas d'equation associee
Reimplemented from Operateur_base.
References Operateur_base::completer(), MorEqn::equation(), Op_Grad_PolyMAC_Face::ref_domaine, and TRUST_Ref< _CLASSE_ >::valeur().
has_interface_blocs()
int Op_Grad_PolyMAC_P0P1NC_Face::has_interface_blocs () const inline override virtual
Reimplemented from Operateur_base.
dimensionner_blocs()
void Op_Grad_PolyMAC_P0P1NC_Face::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl = { }) const override virtual
Reimplemented from Operateur_base.
References Matrix_tools::allocate_morse_matrix(), TRUSTTab< _TYPE_, _SIZE_ >::append_line(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), MorEqn::equation(), Champ_Face_base::fcl(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Matrice_Morse::nb_colonnes(), Op_Grad_PolyMAC_Face::ref_domaine, TRUSTVect< _TYPE_, _SIZE_ >::size_totale(), TRUST_Ref< _CLASSE_ >::valeur(), and Champ_Inc_base::valeurs().
ajouter_blocs()
void Op_Grad_PolyMAC_P0P1NC_Face::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = { }) const override virtual
Reimplemented from Operateur_base.
References Statistiques::begin_count(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Statistiques::end_count(), MorEqn::equation(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Equation_base::milieu(), Milieu_base::porosite_elem(), Op_Grad_PolyMAC_Face::ref_domaine, and TRUST_Ref< _CLASSE_ >::valeur().
check_multiphase_compatibility()
void Op_Grad_PolyMAC_P0P1NC_Face::check_multiphase_compatibility () const inline override virtual
Reimplemented from MorEqn.
Member Data Documentation
info_obj
const Type_info Op_Grad_PolyMAC_P0P1NC_Face::info_obj static