TrioCFD: Source_QC_Chaleur_VDF Class Reference
Source_QC_Chaleur_VDF Class Reference
#include <Source_QC_Chaleur_VDF.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Source_Chaleur_Fluide_Dilatable_base
void completer () override
const Type_info * get_info () const override
void mettre_a_jour (double) override
Public Member Functions inherited from Source_base
virtual int a_pour_Champ_Fonc (const Motcle &mot, TRUST_Ref< Champ_base * > &ch_ref) const
virtual void associer_champ_rho (const Champ_base &champ_rho)
virtual void completer ()
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
virtual void resetTime (double t)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Source_QC_Chaleur
virtual DoubleTab & ajouter_ (DoubleTab &) const
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
Cette classe represente un terme source supplementaire a prendre en compte dans les equations de la chaleur dans le cas ou le fluide est quasi compressible et pour une discretisation VDF
See also
Source_base Fluide_Quasi_Compressible Source_QC_Chaleur
Constructor & Destructor Documentation
Source_QC_Chaleur_VDF()
Source_QC_Chaleur_VDF::Source_QC_Chaleur_VDF ()
~Source_QC_Chaleur_VDF()
Source_QC_Chaleur_VDF::~Source_QC_Chaleur_VDF ()
Member Function Documentation
cree_instance()
Objet_U * Source_QC_Chaleur_VDF::cree_instance () static
taille_memoire()
unsigned Source_QC_Chaleur_VDF::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Source_QC_Chaleur_VDF::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Source_QC_Chaleur_VDF::info () static
get_info()
const Type_info * Source_QC_Chaleur_VDF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Source_QC_Chaleur.
self_cast() [1/2]
Source_QC_Chaleur_VDF & Source_QC_Chaleur_VDF::self_cast (Objet_U & r) static
self_cast() [2/2]
const Source_QC_Chaleur_VDF & Source_QC_Chaleur_VDF::self_cast (const Objet_U & r) static
printOn()
Sortie & Source_QC_Chaleur_VDF::printOn (Sortie & os) const override protected virtual
DOES NOTHING - to override in derived classes.
Imprime la source sur un flot de sortie.
Parameters
(Sortie& os) le flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Source_QC_Chaleur.
References Objet_U::que_suis_je().
readOn()
Entree & Source_QC_Chaleur_VDF::readOn (Entree & is) override protected virtual
DOES NOTHING - to override in derived classes.
Lecture d'un terme source sur un flot d'entree.
Parameters
(Entree& is) le flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Source_QC_Chaleur.
associer_domaines()
void Source_QC_Chaleur_VDF::associer_domaines (const Domaine_dis_base & domaine, const Domaine_Cl_dis_base & zcl) override protected virtual
Implements Source_Chaleur_Fluide_Dilatable_base.
References Source_Fluide_Dilatable_VDF_Proto::associer_domaines_impl(), Source_Fluide_Dilatable_VDF_Proto::associer_volume_porosite_impl(), Source_Chaleur_Fluide_Dilatable_base::porosites, and Source_Chaleur_Fluide_Dilatable_base::volumes.
dimensionner_blocs()
void Source_QC_Chaleur_VDF::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl) const inline override protected virtual
Reimplemented from Source_base.
ajouter_blocs()
void Source_QC_Chaleur_VDF::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl) const inline override protected virtual
Reimplemented from Source_base.
References Source_QC_Chaleur::ajouter_().
has_interface_blocs()
int Source_QC_Chaleur_VDF::has_interface_blocs () const inline override protected virtual
Reimplemented from Source_base.
Member Data Documentation
info_obj
const Type_info Source_QC_Chaleur_VDF::info_obj static