TrioCFD: Couplage_Parietal_PolyMAC_helper Class Reference
Couplage_Parietal_PolyMAC_helper Class Reference
#include <Couplage_Parietal_PolyMAC_helper.h>
Member Function Documentation
associer()
void Couplage_Parietal_PolyMAC_helper::associer (const Op_Diff_PolyMAC_P0_Elem & op)
Referenced by Op_Diff_PolyMAC_P0_Elem::completer().
completer_d_nuc()
void Couplage_Parietal_PolyMAC_helper::completer_d_nuc ()
References TRUSTVect< _TYPE_, _SIZE_ >::line_size(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), and Champ_Inc_base::valeurs().
Referenced by Op_Diff_PolyMAC_P0_Elem::completer().
d_nuc_a_jour() [1/2]
int & Couplage_Parietal_PolyMAC_helper::d_nuc_a_jour () inline
Referenced by Op_Diff_PolyMAC_P0_Elem::d_nucleation(), and Op_Diff_PolyMAC_P0_Elem::mettre_a_jour().
d_nuc_a_jour() [2/2]
const int & Couplage_Parietal_PolyMAC_helper::d_nuc_a_jour () const inline
init_op_ext()
void Couplage_Parietal_PolyMAC_helper::init_op_ext () const
References TRUSTTab< _TYPE_, _SIZE_ >::append_line(), Op_Diff_PolyMAC_P0_Elem::couplage_parietal_helper(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Equation_base::domaine_Cl_dis(), MorEqn::equation(), Echange_contact_PolyMAC_P0P1NC::f_dist, Equation_base::inconnue(), Echange_contact_PolyMAC_P0::init_op(), Domaine_Cl_dis_base::les_conditions_limites(), Echange_contact_PolyMAC_P0::o_diff, TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUST_Vector< _CLASSE_ >::size(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Op_Diff_PolyMAC_P0_Elem::init_op_ext().
dimensionner_blocs()
void Couplage_Parietal_PolyMAC_helper::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl = {}) const
References Matrix_tools::allocate_morse_matrix(), Objet_U::dimension, Nom::getString(), TRUST_Ref< _CLASSE_ >::le_nom(), and Process::mp_sum_as_double().
Referenced by Op_Diff_PolyMAC_P0_Elem::dimensionner_blocs().
ajouter_blocs()
void Couplage_Parietal_PolyMAC_helper::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = {}) const
References Objet_U::dimension, Champ_Inc_P0_base::fcl(), Nom::getString(), TRUST_Ref< _CLASSE_ >::le_nom(), Domaine_dis_base::nb_elem_tot(), Domaine_VF::nb_faces(), Domaine_VF::premiere_face_int(), TRUST_Ref< _CLASSE_ >::valeur(), and Champ_Inc_base::valeurs().
Referenced by Op_Diff_PolyMAC_P0_Elem::ajouter_blocs().
d_nuc()
const DoubleTab & Couplage_Parietal_PolyMAC_helper::d_nuc () const inline
Referenced by Op_Diff_PolyMAC_P0_Elem::d_nucleation().