TrioCFD: Op_Diff_VEF_Face Class Reference
Op_Diff_VEF_Face Class Reference
#include <Op_Diff_VEF_Face.h>
Public Member Functions
void completer () override
const Type_info * get_info () const override
void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const override
Public Member Functions inherited from Op_Diff_VEF_base
double calculer_dt_stab () const override
const Type_info * get_info () const override
int impr (Sortie &os) const override
Public Member Functions inherited from Operateur_Diff_base
virtual void associer_diffusivite_pour_pas_de_temps (const Champ_base &)
const Type_info * get_info () const override
Public Member Functions inherited from Operateur_base
void associer_eqn (const Equation_base &)
virtual double calculer_dt_stab () const
virtual void completer ()
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual void mettre_a_jour (double temps)
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Public Member Functions inherited from Op_VEF_Face
void dimensionner (const Domaine_VEF &, const Domaine_Cl_VEF &, Matrice_Morse &) const
void modifier_matrice_pour_periodique_apres_contribuer (Matrice_Morse &matrice, const Equation_base &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Operateur_Diff_base
virtual const Champ_base & diffusivite_pour_pas_de_temps () const
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
La discretisation est VEF Le champ diffuse est scalaire
Constructor & Destructor Documentation
~Op_Diff_VEF_Face()
Op_Diff_VEF_Face::~Op_Diff_VEF_Face ()
Op_Diff_VEF_Face()
Op_Diff_VEF_Face::Op_Diff_VEF_Face ()
References Support_Champ_Masse_Volumique::declare_support_masse_volumique().
Member Function Documentation
cree_instance()
Objet_U * Op_Diff_VEF_Face::cree_instance () static
taille_memoire()
unsigned Op_Diff_VEF_Face::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Op_Diff_VEF_Face_Penalise, Op_Diff_VEF_Face_Stab, and Op_Diff_VEFP1NCP1B_Face.
duplique()
int Op_Diff_VEF_Face::duplique () const override virtual
Implements Objet_U.
Reimplemented in Op_Diff_VEF_Face_Penalise, Op_Diff_VEF_Face_Stab, and Op_Diff_VEFP1NCP1B_Face.
info()
const Type_info * Op_Diff_VEF_Face::info () static
get_info()
const Type_info * Op_Diff_VEF_Face::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Op_Diff_VEF_base.
Reimplemented in Op_Diff_VEF_Face_Penalise, Op_Diff_VEF_Face_Stab, and Op_Diff_VEFP1NCP1B_Face.
self_cast() [1/2]
Op_Diff_VEF_Face & Op_Diff_VEF_Face::self_cast (Objet_U & r) static
self_cast() [2/2]
const Op_Diff_VEF_Face & Op_Diff_VEF_Face::self_cast (const Objet_U & r) static
printOn()
Sortie & Op_Diff_VEF_Face::printOn (Sortie & os) const override protected virtual
DOES NOTHING - to override in derived classes.
Imprime l'operateur sur un flot de sortie.
Parameters
(Sortie& os) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Op_Diff_VEF_base.
Reimplemented in Op_Diff_VEF_Face_Penalise, Op_Diff_VEF_Face_Stab, and Op_Diff_VEFP1NCP1B_Face.
References Objet_U::que_suis_je().
readOn()
Entree & Op_Diff_VEF_Face::readOn (Entree & is) override protected virtual
DOES NOTHING - to override in derived classes.
Lit un operateur sur un flot d'entree.
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Op_Diff_VEF_base.
Reimplemented in Op_Diff_VEF_Face_Penalise, Op_Diff_VEF_Face_Stab, and Op_Diff_VEFP1NCP1B_Face.
associer_diffusivite()
void Op_Diff_VEF_Face::associer_diffusivite (const Champ_base & diffu) override virtual
associe le champ de diffusivite
Implements Operateur_Diff_base.
References diffusivite_.
completer()
void Op_Diff_VEF_Face::completer () override virtual
Associe l'operateur au domaine_dis, le domaine_Cl_dis, et a l'inconnue de son equation.
Exceptions
pas d'equation associee
Reimplemented from Operateur_base.
Reimplemented in Op_Diff_VEF_Face_Stab, and Op_Diff_VEFP1NCP1B_Face.
References Operateur_base::completer().
Referenced by Op_Diff_VEF_Face_Stab::completer(), and Op_Diff_VEFP1NCP1B_Face::completer().
diffusivite()
const Champ_base & Op_Diff_VEF_Face::diffusivite () const override virtual
Implements Operateur_Diff_base.
References diffusivite_, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Op_Diff_VEFP1NCP1B_Face::calculer_laplacien_som().
ajouter()
DoubleTab & Op_Diff_VEF_Face::ajouter (const DoubleTab & inconnue_org, DoubleTab & resu) const override virtual
Reimplemented from Operateur_base.
Reimplemented in Op_Diff_VEF_Face_Stab, Op_Diff_VEFP1NCP1B_Face, and Op_Diff_VEF_Face_Penalise.
References ajouter_cas_multi_scalaire(), ajouter_cas_scalaire(), ajouter_cas_vectoriel(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), MorEqn::equation(), Operateur_base::flux_bords_, Equation_base::inconnue(), Op_Diff_VEF_base::la_zcl_vef, Op_Diff_VEF_base::le_dom_vef, Equation_base::milieu(), Op_VEF_Face::modifier_flux(), Field_base::nature_du_champ(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Domaine_VF::nb_faces_bord(), Op_Diff_VEF_base::nu_, Op_Diff_VEF_base::phi_psi_diffuse(), Milieu_base::porosite_elem(), Milieu_base::porosite_face(), Op_Diff_VEF_base::remplir_nu(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Op_Diff_VEF_Face_Penalise::ajouter(), and calculer().
calculer()
DoubleTab & Op_Diff_VEF_Face::calculer (const DoubleTab & inconnue, DoubleTab & resu) const override virtual
Reimplemented from Operateur_base.
Reimplemented in Op_Diff_VEFP1NCP1B_Face, and Op_Diff_VEF_Face_Penalise.
References ajouter().
Referenced by verifier().
verifier()
void Op_Diff_VEF_Face::verifier () const
References calculer(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, MorEqn::equation(), Op_Diff_VEF_base::le_dom_vef, TRUST_Ref< _CLASSE_ >::valeur(), Domaine_VF::volumes_entrelaces(), and Domaine_VF::xv().
dimensionner()
void Op_Diff_VEF_Face::dimensionner (Matrice_Morse & matrice) const inline override virtual
on dimensionne notre matrice.
Reimplemented from Operateur_base.
Reimplemented in Op_Diff_VEFP1NCP1B_Face.
References Op_VEF_Face::dimensionner(), Op_Diff_VEF_base::la_zcl_vef, Op_Diff_VEF_base::le_dom_vef, and TRUST_Ref< _CLASSE_ >::valeur().
modifier_pour_Cl()
void Op_Diff_VEF_Face::modifier_pour_Cl (Matrice_Morse & , DoubleTab &) const inline override virtual
DOES NOTHING - to override in derived classes.
Parameters
(Matrice_Morse&) une matrice au format Morse
(DoubleTab&) un tableau de valeur (double)
Exceptions
methode a surcharger
Reimplemented from Operateur_base.
References Op_Diff_VEF_base::la_zcl_vef, Op_Diff_VEF_base::le_dom_vef, Op_VEF_Face::modifier_pour_Cl(), and TRUST_Ref< _CLASSE_ >::valeur().
contribuer_a_avec()
void Op_Diff_VEF_Face::contribuer_a_avec (const DoubleTab & inco, Matrice_Morse & matrice) const inline override virtual
on assemble la matrice.
Reimplemented from Operateur_base.
Reimplemented in Op_Diff_VEF_Face_Stab, and Op_Diff_VEFP1NCP1B_Face.
References ajouter_contribution(), ajouter_contribution_multi_scalaire(), MorEqn::equation(), Equation_base::inconnue(), and Field_base::nature_du_champ().
Referenced by Op_Diff_VEF_Face_Stab::contribuer_a_avec().
contribuer_au_second_membre()
void Op_Diff_VEF_Face::contribuer_au_second_membre (DoubleTab & resu) const inline override virtual
on ajoute la contribution du second membre.
Reimplemented from Operateur_base.
Reimplemented in Op_Diff_VEFP1NCP1B_Face.
References contribue_au_second_membre().
contribue_au_second_membre()
void Op_Diff_VEF_Face::contribue_au_second_membre (DoubleTab & resu) const
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Neumann::flux_impose(), Op_Diff_VEF_base::la_zcl_vef, Op_Diff_VEF_base::le_dom_vef, Domaine_Cl_dis_base::les_conditions_limites(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), Domaine_VF::surface(), TRUST_Deriv< _CLASSE_ >::valeur(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by contribuer_au_second_membre(), and Op_Diff_VEFP1NCP1B_Face::contribuer_au_second_membre().
ajouter_contribution()
void Op_Diff_VEF_Face::ajouter_contribution (const DoubleTab & tab_transporte, Matrice_Morse & tab_matrice) const
References Matrice_Morse_View::atomic_add(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), MorEqn::equation(), Domaine_VF::est_face_bord(), Periodique::face_associee(), Domaine_VF::face_normales(), Domaine_VF::face_voisins(), Echange_impose_base::h_imp(), Echange_impose_base::has_emissivite(), Equation_base::inconnue(), Domaine_VF::inverse_volumes(), Op_Diff_VEF_base::la_zcl_vef, Op_Diff_VEF_base::le_dom_vef, Domaine_Cl_dis_base::les_conditions_limites(), Equation_base::milieu(), Op_VEF_Face::modifier_matrice_pour_periodique_avant_contribuer(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Domaine_VF::nb_faces(), Front_VF::nb_faces(), Domaine_32_64< _SIZE_ >::nb_faces_elem(), Domaine_dis_base::nb_front_Cl(), Op_Diff_VEF_base::nu_, Front_VF::num_premiere_face(), Op_Diff_VEF_base::phi_psi_diffuse(), Milieu_base::porosite_face(), Domaine_VF::premiere_face_int(), Op_Diff_VEF_base::remplir_nu(), Matrice_Morse_View::set(), TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_Inc_base::valeurs(), TRUSTArray< _TYPE_, _SIZE_ >::view_ro(), TRUSTTab< _TYPE_, _SIZE_ >::view_ro(), and Op_Diff_VEF_base::viscA().
Referenced by Op_Diff_VEF_Face_Stab::ajouter_contribution(), and contribuer_a_avec().
ajouter_contribution_multi_scalaire()
void Op_Diff_VEF_Face::ajouter_contribution_multi_scalaire (const DoubleTab & tab_transporte, Matrice_Morse & tab_matrice) const
References Matrice_Morse_View::atomic_add(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), MorEqn::equation(), Domaine_VF::est_face_bord(), Periodique::face_associee(), Domaine_VF::face_normales(), Domaine_VF::face_voisins(), Echange_impose_base::h_imp(), Domaine_VF::inverse_volumes(), Op_Diff_VEF_base::la_zcl_vef, Op_Diff_VEF_base::le_dom_vef, Domaine_Cl_dis_base::les_conditions_limites(), Equation_base::milieu(), Op_VEF_Face::modifier_matrice_pour_periodique_apres_contribuer(), Op_VEF_Face::modifier_matrice_pour_periodique_avant_contribuer(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Front_VF::nb_faces(), Domaine_32_64< _SIZE_ >::nb_faces_elem(), Domaine_VF::nb_faces_tot(), Domaine_dis_base::nb_front_Cl(), Op_Diff_VEF_base::nu_, Front_VF::num_premiere_face(), Op_Diff_VEF_base::phi_psi_diffuse(), Milieu_base::porosite_elem(), Domaine_VF::premiere_face_int(), Op_Diff_VEF_base::remplir_nu(), Matrice_Morse_View::set(), Domaine_VF::surface(), TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), TRUSTArray< _TYPE_, _SIZE_ >::view_ro(), TRUSTTab< _TYPE_, _SIZE_ >::view_ro(), and Op_Diff_VEF_base::viscA().
Referenced by Op_Diff_VEF_Face_Stab::ajouter_contribution_multi_scalaire(), and contribuer_a_avec().
ajouter_cas_scalaire()
void Op_Diff_VEF_Face::ajouter_cas_scalaire (const DoubleTab & inconnue, DoubleTab & resu, DoubleTab & flux_bords, DoubleTab & nu, const Domaine_Cl_VEF & domaine_Cl_VEF, const Domaine_VEF & domaine_VEF) const
References Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), Periodique::face_associee(), Domaine_VF::face_normales(), Domaine_VF::face_surfaces(), Domaine_VF::face_voisins(), Operateur_base::flux_bords(), Neumann::flux_impose(), Echange_impose_base::h_imp(), Echange_impose_base::has_emissivite(), Domaine_VF::inverse_volumes(), Domaine_Cl_dis_base::les_conditions_limites(), Domaine_VF::nb_faces(), Front_VF::nb_faces(), Domaine_32_64< _SIZE_ >::nb_faces_elem(), Front_VF::nb_faces_tot(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_face(), Front_VF::num_premiere_face(), Domaine_VF::premiere_face_int(), Echange_impose_base::T_ext(), TRUST_Deriv< _CLASSE_ >::valeur(), TRUSTArray< _TYPE_, _SIZE_ >::view_ro(), TRUSTTab< _TYPE_, _SIZE_ >::view_ro(), and Op_Diff_VEF_base::viscA().
Referenced by ajouter().
ajouter_cas_vectoriel()
void Op_Diff_VEF_Face::ajouter_cas_vectoriel (const DoubleTab & inconnue, DoubleTab & resu, DoubleTab & flux_bords, DoubleTab & nu, const Domaine_Cl_VEF & domaine_Cl_VEF, const Domaine_VEF & domaine_VEF, int nb_comp) const
References Champ_P1NC::calcul_gradient(), Domaine_32_64< _SIZE_ >::creer_tableau_elements(), Objet_U::dimension, Domaine_dis_base::domaine(), Domaine_VF::face_normales(), Domaine_VF::face_voisins(), Operateur_base::flux_bords(), TRUSTVect< _TYPE_, _SIZE_ >::get_md_vector(), grad_, Domaine_Cl_dis_base::les_conditions_limites(), Domaine_VF::nb_faces(), Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), MD_Vector::non_nul(), Front_VF::num_premiere_face(), Domaine_VF::premiere_face_int(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUST_Deriv< _CLASSE_ >::valeur(), TRUSTTab< _TYPE_, _SIZE_ >::view_ro(), TRUSTTab< _TYPE_, _SIZE_ >::view_rw(), and TRUSTTab< _TYPE_, _SIZE_ >::view_wo().
Referenced by ajouter().
ajouter_cas_multi_scalaire()
void Op_Diff_VEF_Face::ajouter_cas_multi_scalaire (const DoubleTab & inconnue, DoubleTab & resu, DoubleTab & flux_bords, DoubleTab & nu, const Domaine_Cl_VEF & domaine_Cl_VEF, const Domaine_VEF & domaine_VEF, int nb_comp) const
References Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), Periodique::face_associee(), Domaine_VF::face_voisins(), Neumann::flux_impose(), Echange_impose_base::h_imp(), Echange_impose_base::has_emissivite(), Domaine_Cl_dis_base::les_conditions_limites(), Domaine_VF::nb_faces(), Front_VF::nb_faces(), Domaine_32_64< _SIZE_ >::nb_faces_elem(), Front_VF::nb_faces_tot(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_face(), Front_VF::num_premiere_face(), Domaine_VF::premiere_face_int(), Domaine_VF::surface(), Echange_impose_base::T_ext(), TRUST_Deriv< _CLASSE_ >::valeur(), and Op_Diff_VEF_base::viscA().
Referenced by ajouter().
Member Data Documentation
info_obj
const Type_info Op_Diff_VEF_Face::info_obj static
diffusivite_
TRUST_Ref< Champ_base *> Op_Diff_VEF_Face::diffusivite_ protected
Referenced by associer_diffusivite(), and diffusivite().
grad_
DoubleTab Op_Diff_VEF_Face::grad_ mutable protected
Referenced by ajouter_cas_vectoriel().