TrioCFD: Flux_2groupes_PolyMAC_P0 Class Reference
Flux_2groupes_PolyMAC_P0 Class Reference
#include <Flux_2groupes_PolyMAC_P0.h>
Public Member Functions
Flux_2groupes_PolyMAC_P0 ()
const Type_info * get_info () const override
void mettre_a_jour (double temps) override
Public Member Functions inherited from Source_base
virtual int a_pour_Champ_Fonc (const Motcle &mot, TRUST_Ref< Champ_base * > &ch_ref) const
virtual void associer_champ_rho (const Champ_base &champ_rho)
virtual void completer ()
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
virtual void resetTime (double t)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
Cette classe implemente dans PolyMAC_P0P1NC un operateur de frottement interfacial
de la forme F_{kl} = - F_{lk} = - C_{kl} (u_k - u_l) le calcul de C_{kl} est realise par la hierarchie Coefficient_Flux_2groupes_base
Constructor & Destructor Documentation
Flux_2groupes_PolyMAC_P0()
Flux_2groupes_PolyMAC_P0::Flux_2groupes_PolyMAC_P0 ()
Joseph L. Bottini, Taiyang Zhang, Caleb S. Brooks, Validation of two-group interfacial area transport equation in boiling flow, International Journal of Heat and Mass Transfer, 2024, https://doi.org/10.1016/j.ijheatmasstransfer.2024.125515
~Flux_2groupes_PolyMAC_P0()
Flux_2groupes_PolyMAC_P0::~Flux_2groupes_PolyMAC_P0 ()
Member Function Documentation
cree_instance()
Objet_U * Flux_2groupes_PolyMAC_P0::cree_instance () static
taille_memoire()
unsigned Flux_2groupes_PolyMAC_P0::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Flux_2groupes_PolyMAC_P0::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Flux_2groupes_PolyMAC_P0::info () static
get_info()
const Type_info * Flux_2groupes_PolyMAC_P0::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Source_base.
self_cast() [1/2]
Flux_2groupes_PolyMAC_P0 & Flux_2groupes_PolyMAC_P0::self_cast (Objet_U & r) static
self_cast() [2/2]
const Flux_2groupes_PolyMAC_P0 & Flux_2groupes_PolyMAC_P0::self_cast (const Objet_U & r) static
printOn()
Sortie & Flux_2groupes_PolyMAC_P0::printOn (Sortie & os) const override protected virtual
DOES NOTHING - to override in derived classes.
Imprime la source sur un flot de sortie.
Parameters
(Sortie& os) le flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Source_base.
readOn()
Entree & Flux_2groupes_PolyMAC_P0::readOn (Entree & is) override protected virtual
DOES NOTHING - to override in derived classes.
Lecture d'un terme source sur un flot d'entree.
Parameters
(Entree& is) le flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Source_base.
References Param::ajouter(), correlation_, Nom::debute_par(), dh_, MorEqn::equation(), Pb_Multiphase::equation(), Process::exit(), Nom::finit_par(), Probleme_base::get_correlation(), Probleme_base::has_correlation(), Param::lire_avec_accolades_depuis(), n_g1, n_g2, n_l, Pb_Multiphase::nb_phases(), Pb_Multiphase::nom_phase(), Objet_U::que_suis_je(), TRUST_List< _CLASSE_ >::size(), Equation_base::sources(), src_flux_interfacial_, and Correlation_base::typer_lire_correlation().
dimensionner_blocs()
void Flux_2groupes_PolyMAC_P0::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl = {}) const override virtual
Reimplemented from Source_base.
References Matrix_tools::allocate_morse_matrix(), TRUSTTab< _TYPE_, _SIZE_ >::append_line(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), MorEqn::equation(), Probleme_base::get_champ(), Equation_base::inconnue(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Matrice_Morse::nb_colonnes(), Equation_base::probleme(), Champ_Inc_base::valeurs(), and Champ_Proto::valeurs().
ajouter_blocs()
void Flux_2groupes_PolyMAC_P0::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = {}) const override virtual
Reimplemented from Source_base.
References Flux_2groupes_base::input_coeffs::a_i, Flux_2groupes_base::input_coeffs::alpha, Flux_2groupes_base::input_therms::alpha, Milieu_base::capacite_calorifique(), Flux_2groupes_base::coeffs(), Milieu_base::conductivite(), Op_Dift_Multiphase_proto::correlation(), correlation_, Flux_2groupes_base::input_therms::Cp, Flux_2groupes_base::input_coeffs::d_bulles, Flux_2groupes_base::input_therms::d_bulles, Flux_2groupes_base::output_therms::da_etaph1, Flux_2groupes_base::output_therms::da_etaph2, Flux_2groupes_base::output_therms::da_G1, Flux_2groupes_base::output_therms::da_G2, Flux_2groupes_base::output_coeffs::da_gamma, Flux_2groupes_base::output_coeffs::da_inter2g1, Flux_2groupes_base::output_coeffs::da_inter2g2, Flux_2groupes_base::output_coeffs::da_inter3g1, Flux_2groupes_base::output_coeffs::da_inter3g2, Flux_2groupes_base::output_coeffs::dai_gamma, Champ_Inc_base::derivees(), Flux_2groupes_base::input_coeffs::dh, Flux_2groupes_base::input_therms::dh, dh_, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Champ_Inc_base::domaine_Cl_dis(), Flux_2groupes_base::output_therms::dp_etaph1, Flux_2groupes_base::output_therms::dp_etaph2, Flux_2groupes_base::output_therms::dp_G1, Flux_2groupes_base::output_therms::dp_G2, Saturation_base::dP_Tsat(), Flux_2groupes_base::input_therms::dp_Tsat1, Flux_2groupes_base::input_therms::dp_Tsat2, Flux_2groupes_base::output_therms::dT_etaph1, Flux_2groupes_base::output_therms::dT_etaph2, Flux_2groupes_base::output_therms::dT_G1, Flux_2groupes_base::output_therms::dT_G2, Flux_2groupes_base::input_coeffs::e, Viscosite_turbulente_base::eps(), Flux_2groupes_base::input_coeffs::epsilon, MorEqn::equation(), Pb_Multiphase::equation_energie(), Pb_Multiphase::equation_masse(), Pb_Multiphase::equation_qdm(), Flux_2groupes_base::output_therms::etaph1, Flux_2groupes_base::output_therms::etaph2, Champ_Inc_P0_base::fcl(), Flux_2groupes_base::output_therms::G1, Flux_2groupes_base::output_therms::G2, Flux_2groupes_base::output_coeffs::gamma, Probleme_base::get_champ(), Champ_Face_base::get_elem_vector_field(), Milieu_composite::get_interface(), Milieu_composite::get_saturation(), Interface_base::get_sigma_tab(), Probleme_base::has_champ(), Milieu_composite::has_interface(), Milieu_composite::has_saturation(), Saturation_base::Hls(), Flux_2groupes_base::input_therms::hlsat, Equation_base::inconnue(), Flux_2groupes_base::output_coeffs::inter2g1, Flux_2groupes_base::output_coeffs::inter2g2, Flux_2groupes_base::output_coeffs::inter3g1, Flux_2groupes_base::output_coeffs::inter3g2, Flux_2groupes_base::input_coeffs::k_turb, Flux_2groupes_base::input_therms::lambda, Domaine_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Flux_2groupes_base::input_therms::Lvap, Saturation_base::Lvap(), Milieu_base::masse_volumique(), Equation_base::milieu(), Flux_2groupes_base::input_coeffs::mu, Flux_2groupes_base::input_therms::mu, Flux_2groupes_base::input_coeffs::n_g1, Flux_2groupes_base::input_therms::n_g1, n_g1, Flux_2groupes_base::input_coeffs::n_g2, Flux_2groupes_base::input_therms::n_g2, n_g2, Flux_2groupes_base::input_coeffs::n_l, Flux_2groupes_base::input_therms::n_l, n_l, Flux_2groupes_base::input_coeffs::nv, Flux_2groupes_base::input_coeffs::p, Flux_2groupes_base::input_therms::p, Schema_Temps_base::pas_de_temps(), Champ_Proto::passe(), Champ_Inc_base::passe(), Milieu_base::porosite_elem(), Equation_base::probleme(), Flux_2groupes_base::input_therms::qp, TRUSTTab< _TYPE_, _SIZE_ >::resize(), Flux_2groupes_base::input_coeffs::rho, Flux_2groupes_base::input_therms::rho, Probleme_base::schema_temps(), Flux_2groupes_base::input_coeffs::sigma, Flux_2groupes_base::input_therms::sigma, Interface_base::sigma(), Flux_2groupes_base::input_therms::T, Flux_2groupes_base::therm(), Saturation_base::Tsat(), Flux_2groupes_base::input_therms::Tsatg1, Flux_2groupes_base::input_therms::Tsatg2, TRUST_Deriv< _CLASSE_ >::valeur(), Champ_Inc_base::valeurs(), Champ_Proto::valeurs(), and Fluide_base::viscosite_dynamique().
check_multiphase_compatibility()
void Flux_2groupes_PolyMAC_P0::check_multiphase_compatibility () const inline override virtual
Reimplemented from MorEqn.
associer_domaines()
void Flux_2groupes_PolyMAC_P0::associer_domaines (const Domaine_dis_base & , const Domaine_Cl_dis_base &) inline override virtual
Implements Source_base.
associer_pb()
void Flux_2groupes_PolyMAC_P0::associer_pb (const Probleme_base &) inline override virtual
Implements Source_base.
mettre_a_jour()
void Flux_2groupes_PolyMAC_P0::mettre_a_jour (double temps) inline override virtual
DOES NOTHING - to override in derived classes.
Mise a jour en temps du terme source.
Parameters
(double) le pas de temps de mise a jour
Reimplemented from Source_base.
Member Data Documentation
info_obj
const Type_info Flux_2groupes_PolyMAC_P0::info_obj static
correlation_
TRUST_Deriv< Correlation_base > Flux_2groupes_PolyMAC_P0::correlation_ protected
Referenced by ajouter_blocs(), and readOn().
dh_
double Flux_2groupes_PolyMAC_P0::dh_ = 1.e6 protected
Referenced by ajouter_blocs(), and readOn().
n_l
int Flux_2groupes_PolyMAC_P0::n_l = -1 protected
Referenced by ajouter_blocs(), and readOn().
n_g1
int Flux_2groupes_PolyMAC_P0::n_g1 = -1 protected
Referenced by ajouter_blocs(), and readOn().
n_g2
int Flux_2groupes_PolyMAC_P0::n_g2 = -1 protected
Referenced by ajouter_blocs(), and readOn().
src_flux_interfacial_
TRUST_Ref< Source_base *> Flux_2groupes_PolyMAC_P0::src_flux_interfacial_ protected
Referenced by readOn().