TrioCFD: Eval_Diff_K_Omega_VDF_var Class Reference
Eval_Diff_K_Omega_VDF_var Class Reference
#include <Eval_Diff_K_Omega_VDF_var.h>
Member Function Documentation
associer()
void Eval_Diff_K_Omega_VDF_var::associer (const Champ_Don_base & diffu) inline
References Eval_Diff_K_Omega_VDF::diffusivite_, dv_diffusivite, TRUSTVect< _TYPE_, _SIZE_ >::ref(), and Champ_Don_base::valeurs().
mettre_a_jour()
void Eval_Diff_K_Omega_VDF_var::mettre_a_jour () inline override virtual
Reimplemented from Eval_Diff_K_Omega_VDF.
References Eval_Diff_K_Omega_VDF::diffusivite_, Eval_Diff_K_Omega_VDF::diffusivite_turbulente_, dv_diffusivite, Eval_Diff_K_Omega_VDF::dv_diffusivite_turbulente, and TRUSTVect< _TYPE_, _SIZE_ >::ref().
nu_1_impl()
double Eval_Diff_K_Omega_VDF_var::nu_1_impl (int i, int compo) const inline
References dv_diffusivite, Eval_Diff_K_Omega_VDF::dv_diffusivite_turbulente, and Eval_Diff_K_Omega_VDF::Prdt.
Referenced by compute_heq_impl(), and nu_2_impl().
nu_2_impl()
double Eval_Diff_K_Omega_VDF_var::nu_2_impl (int i, int compo) const inline
References nu_1_impl().
compute_heq_impl()
double Eval_Diff_K_Omega_VDF_var::compute_heq_impl (double d0, int i, double d1, int j, int compo) const inline
References nu_1_impl().
Member Data Documentation
dv_diffusivite
DoubleVect Eval_Diff_K_Omega_VDF_var::dv_diffusivite protected
Referenced by associer(), mettre_a_jour(), and nu_1_impl().