TrioCFD: Loi_Paroi_Nu_Impose_VDF Class Reference
Loi_Paroi_Nu_Impose_VDF Class Reference
#include <Loi_Paroi_Nu_Impose_VDF.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Turbulence_paroi_scal_base
void associer_modele (const Modele_turbulence_scal_base &)
const Type_info * get_info () const override
void imprimer_nusselt_mean_only (Sortie &, int, const TRUST_List< Nom > &, const Nom &) const
void imprimer_premiere_ligne_nusselt (int, const TRUST_List< Nom > &, const Nom &) const
int reprendre (Entree &is) override
int sauvegarder (Sortie &os) const override
virtual bool use_equivalent_distance () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Turbulence_paroi_scal_base
static void typer_lire_turbulence_paroi_scal (TRUST_Deriv< Turbulence_paroi_scal_base > &, const Modele_turbulence_scal_base &, Entree &)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
.SECTION voir aussi Paroi_std_hyd_VDF Cette classe permet d'imposer une loi de paroi de type nombre de Nusselt imposee. La fonction de Nusselt rentree par l'utilisateur peut etre une fonction de l'espace, du nombre de Reynolds et du nombre de Prandtl. Ces nombres de Reynolds et de Prandtl sont evalues a partir des quantites en paroi (vitesse, temperature etc...). Il convient donc de tenir compte de cela dans l'entree de la correlation du Nusselt. En effet, souvent les correlations de Nusselt utilise la vitesse moyenne dans la conduite. C'est pourquoi cette loi de paroi s'appliquera souvent dans le cas ou le probleme fluide ets resolu avec une seulle maille afin que la vitesse calcule represente exactement par conservation du debit la vitesse moyenne de l'ecoulement. Syntaxe : Loi_Paroi_Nu_Impose { nusselt fontion_de_(x,y,z,Re,Pr) diam_hydr valeur_diametre_hydraulique }
Constructor & Destructor Documentation
Loi_Paroi_Nu_Impose_VDF()
Loi_Paroi_Nu_Impose_VDF::Loi_Paroi_Nu_Impose_VDF ()
~Loi_Paroi_Nu_Impose_VDF()
Loi_Paroi_Nu_Impose_VDF::~Loi_Paroi_Nu_Impose_VDF ()
Member Function Documentation
cree_instance()
Objet_U * Loi_Paroi_Nu_Impose_VDF::cree_instance () static
taille_memoire()
unsigned Loi_Paroi_Nu_Impose_VDF::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Loi_Paroi_Nu_Impose_VDF::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Loi_Paroi_Nu_Impose_VDF::info () static
get_info()
const Type_info * Loi_Paroi_Nu_Impose_VDF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Paroi_scal_hyd_base_VDF.
self_cast() [1/2]
Loi_Paroi_Nu_Impose_VDF & Loi_Paroi_Nu_Impose_VDF::self_cast (Objet_U & r) static
self_cast() [2/2]
const Loi_Paroi_Nu_Impose_VDF & Loi_Paroi_Nu_Impose_VDF::self_cast (const Objet_U & r) static
printOn()
Sortie & Loi_Paroi_Nu_Impose_VDF::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Paroi_scal_hyd_base_VDF.
References Objet_U::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Loi_Paroi_Nu_Impose_VDF::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Paroi_scal_hyd_base_VDF.
References Parser_U::addVar(), diam_hydr, Objet_U::dimension, Process::exit(), Field_base::nb_comp(), nusselt, Parser_U::parseString(), Objet_U::que_suis_je(), Motcles::search(), Parser_U::setNbVar(), and Parser_U::setString().
calculer_scal()
int Loi_Paroi_Nu_Impose_VDF::calculer_scal (Champ_Fonc_base & diffusivite_turb) override virtual
Implements Turbulence_paroi_scal_base.
References diam_hydr, Milieu_base::diffusivite(), Objet_U::dimension, Domaine_VF::elem_faces(), Turbulence_paroi_scal_base::equivalent_distance_, Parser_U::eval(), Process::exit(), Domaine_VF::face_voisins(), Domaine_VF::front_VF(), Equation_base::inconnue(), Turbulence_paroi_scal_base::le_dom_Cl_dis_, Turbulence_paroi_scal_base::le_dom_dis_, Frontiere_dis_base::le_nom(), Equation_base::milieu(), Turbulence_paroi_scal_base::mon_modele_turb_scal, Field_base::nb_comp(), Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_local_face(), Front_VF::num_premiere_face(), nusselt, Domaine_VDF::orientation(), Parser_U::setVar(), TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_base::valeur_a_compo(), Champ_Don_base::valeurs(), Champ_Inc_base::valeurs(), Fluide_base::viscosite_cinematique(), and Domaine_VF::xv().
imprimer_nusselt()
void Loi_Paroi_Nu_Impose_VDF::imprimer_nusselt (Sortie &) const override virtual
Reimplemented from Paroi_scal_hyd_base_VDF.
References Milieu_base::conductivite(), diam_hydr, Objet_U::dimension, Equation_base::domaine_Cl_dis(), Probleme_base::equation(), Turbulence_paroi_scal_base::equivalent_distance_, Domaine_VF::face_voisins(), Neumann::flux_impose(), Domaine_VF::front_VF(), Equation_base::inconnue(), Process::je_suis_maitre(), Turbulence_paroi_scal_base::le_dom_Cl_dis_, Turbulence_paroi_scal_base::le_dom_dis_, Frontiere_dis_base::le_nom(), Domaine_Cl_dis_base::les_conditions_limites(), Equation_base::milieu(), Turbulence_paroi_scal_base::mon_modele_turb_scal, Field_base::nb_comp(), Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_local_face(), Front_VF::num_premiere_face(), Turbulence_paroi_scal_base::ouvrir_fichier_partage(), Equation_base::probleme(), EcrFicPartage::syncfile(), TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_base::valeur_a_compo(), Champ_Don_base::valeurs(), Champ_Inc_base::valeurs(), and Domaine_VF::xv().
Member Data Documentation
info_obj
const Type_info Loi_Paroi_Nu_Impose_VDF::info_obj static
diam_hydr
TRUST_Deriv< Champ_Don_base > Loi_Paroi_Nu_Impose_VDF::diam_hydr protected
Referenced by calculer_scal(), imprimer_nusselt(), and readOn().
nusselt
Parser_U Loi_Paroi_Nu_Impose_VDF::nusselt protected
Referenced by calculer_scal(), and readOn().