TrioCFD: Fluide_R12_c1_liquide Class Reference
Fluide_R12_c1_liquide Class Reference
#include <Fluide_R12_c1_liquide.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Fluide_reel_base
const Type_info * get_info () const override
void mettre_a_jour (double temps) override
Public Member Functions inherited from Fluide_base
const Type_info * get_info () const override
void mettre_a_jour (double) override
void verifier_coherence_champs (int &err, Nom &message) override
Public Member Functions inherited from Milieu_base
virtual int a_gravite () const
int associer_ (Objet_U &) override
virtual void associer_gravite (const Champ_Don_base &)
virtual Champ_Don_base & beta_t ()
virtual const Champ_Don_base & beta_t () const
virtual Champ_Don_base & capacite_calorifique ()
virtual const Champ_Don_base & capacite_calorifique () const
virtual Champ_Don_base & conductivite ()
virtual const Champ_Don_base & conductivite () const
virtual Champ_Don_base & diffusivite ()
virtual const Champ_Don_base & diffusivite () const
virtual int est_deja_associe ()
const Type_info * get_info () const override
virtual Champ_Don_base & gravite ()
virtual const Champ_Don_base & gravite () const
const Nom & le_nom () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual Champ_base & masse_volumique ()
virtual const Champ_base & masse_volumique () const
void nommer (const Nom &) override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Fluide_base
void creer_nu ()
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Milieu_base
virtual void calculer_alpha ()
void ecrire (Sortie &) const
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Fluide_R12_c1_liquide()
Fluide_R12_c1_liquide::Fluide_R12_c1_liquide ()
~Fluide_R12_c1_liquide()
Fluide_R12_c1_liquide::~Fluide_R12_c1_liquide ()
Member Function Documentation
cree_instance()
Objet_U * Fluide_R12_c1_liquide::cree_instance () static
taille_memoire()
unsigned Fluide_R12_c1_liquide::taille_memoire () const override virtual
Reimplemented from Fluide_base.
duplique()
int Fluide_R12_c1_liquide::duplique () const override virtual
Reimplemented from Fluide_base.
info()
const Type_info * Fluide_R12_c1_liquide::info () static
get_info()
const Type_info * Fluide_R12_c1_liquide::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Fluide_reel_base.
self_cast() [1/2]
Fluide_R12_c1_liquide & Fluide_R12_c1_liquide::self_cast (Objet_U & r) static
self_cast() [2/2]
const Fluide_R12_c1_liquide & Fluide_R12_c1_liquide::self_cast (const Objet_U & r) static
printOn()
Sortie & Fluide_R12_c1_liquide::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Fluide_reel_base.
readOn()
Entree & Fluide_R12_c1_liquide::readOn (Entree & is) override protected virtual
Lit les caracteristiques du fluide a partir d'un flot d'entree.
Format: Fluide_base { Mu type_champ bloc de lecture de champ Rho Champ_Uniforme 1 vrel [Cp Champ_Uniforme 1 vrel] [Lambda type_champ bloc de lecture de champ] [Beta_th type_champ bloc de lecture de champ] [Beta_co type_champ bloc de lecture de champ] } cf Milieu_base::readOn
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Exceptions
accolade ouvrante attendue
Reimplemented from Fluide_reel_base.
References Param::ajouter(), Process::exit(), Param::lire_avec_accolades_depuis(), and Objet_U::que_suis_je().
unknown_range()
std::map< std::string, std::array< double, 2 > > Fluide_R12_c1_liquide::unknown_range () const inline override protected virtual
Reimplemented from Fluide_reel_base.
rho_()
void Fluide_R12_c1_liquide::rho_ (const SpanD T, const SpanD P, SpanD res, int ncomp = 1, int id = 0) const override protected virtual
Implements Fluide_reel_base.
dP_rho_()
void Fluide_R12_c1_liquide::dP_rho_ (const SpanD T, const SpanD P, SpanD res, int ncomp = 1, int id = 0) const override protected virtual
Implements Fluide_reel_base.
dT_rho_()
void Fluide_R12_c1_liquide::dT_rho_ (const SpanD T, const SpanD P, SpanD res, int ncomp = 1, int id = 0) const override protected virtual
Implements Fluide_reel_base.
h_()
void Fluide_R12_c1_liquide::h_ (const SpanD T, const SpanD P, SpanD res, int ncomp = 1, int id = 0) const override protected virtual
Implements Fluide_reel_base.
dP_h_()
void Fluide_R12_c1_liquide::dP_h_ (const SpanD T, const SpanD P, SpanD res, int ncomp = 1, int id = 0) const override protected virtual
Implements Fluide_reel_base.
dT_h_()
void Fluide_R12_c1_liquide::dT_h_ (const SpanD T, const SpanD P, SpanD res, int ncomp = 1, int id = 0) const override protected virtual
Implements Fluide_reel_base.
cp_()
void Fluide_R12_c1_liquide::cp_ (const SpanD T, const SpanD P, SpanD res, int ncomp = 1, int id = 0) const override protected virtual
Implements Fluide_reel_base.
beta_()
void Fluide_R12_c1_liquide::beta_ (const SpanD T, const SpanD P, SpanD res, int ncomp = 1, int id = 0) const override protected virtual
Implements Fluide_reel_base.
mu_()
void Fluide_R12_c1_liquide::mu_ (const SpanD T, const SpanD P, SpanD res, int ncomp = 1, int id = 0) const override protected virtual
Implements Fluide_reel_base.
lambda_()
void Fluide_R12_c1_liquide::lambda_ (const SpanD T, const SpanD P, SpanD res, int ncomp = 1, int id = 0) const override protected virtual
Implements Fluide_reel_base.
rho_h_()
void Fluide_R12_c1_liquide::rho_h_ (const SpanD T, const SpanD P, SpanD res, int ncomp = 1, int id = 0) const inline override protected virtual
Implements Fluide_reel_base.
dP_rho_h_()
void Fluide_R12_c1_liquide::dP_rho_h_ (const SpanD T, const SpanD P, SpanD res, int ncomp = 1, int id = 0) const inline override protected virtual
Implements Fluide_reel_base.
dh_rho_h_()
void Fluide_R12_c1_liquide::dh_rho_h_ (const SpanD T, const SpanD P, SpanD res, int ncomp = 1, int id = 0) const inline override protected virtual
Implements Fluide_reel_base.
T_()
void Fluide_R12_c1_liquide::T_ (const SpanD T, const SpanD P, SpanD res, int ncomp = 1, int id = 0) const inline override protected virtual
Implements Fluide_reel_base.
dP_T_()
void Fluide_R12_c1_liquide::dP_T_ (const SpanD T, const SpanD P, SpanD res, int ncomp = 1, int id = 0) const inline override protected virtual
Implements Fluide_reel_base.
dh_T_()
void Fluide_R12_c1_liquide::dh_T_ (const SpanD T, const SpanD P, SpanD res, int ncomp = 1, int id = 0) const inline override protected virtual
Implements Fluide_reel_base.
cp_h_()
void Fluide_R12_c1_liquide::cp_h_ (const SpanD T, const SpanD P, SpanD res, int ncomp = 1, int id = 0) const inline override protected virtual
Implements Fluide_reel_base.
beta_h_()
void Fluide_R12_c1_liquide::beta_h_ (const SpanD T, const SpanD P, SpanD res, int ncomp = 1, int id = 0) const inline override protected virtual
Implements Fluide_reel_base.
mu_h_()
void Fluide_R12_c1_liquide::mu_h_ (const SpanD T, const SpanD P, SpanD res, int ncomp = 1, int id = 0) const inline override protected virtual
Implements Fluide_reel_base.
lambda_h_()
void Fluide_R12_c1_liquide::lambda_h_ (const SpanD T, const SpanD P, SpanD res, int ncomp = 1, int id = 0) const inline override protected virtual
Implements Fluide_reel_base.
Member Data Documentation
info_obj
const Type_info Fluide_R12_c1_liquide::info_obj static