TrioCFD: Operateur_IJK_faces_conv Class Reference
Operateur_IJK_faces_conv Class Reference
#include <Operateur_IJK_faces_conv.h>
Public Member Functions
const Type_info * get_info () const override
int lire_motcle_non_standard (const Motcle &mot, Entree &is) override
Public Member Functions inherited from Objet_U_ptr
int associer_ (Objet_U &objet) override
const Type_info * get_info () const override
const Nom & le_nom () const override
Objet_U * typer (const char *nom_type)
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from TRUST_Deriv< Operateur_IJK_faces_conv_base_double >
Sortie & printOn (Sortie &os) const override
Entree & readOn (Entree &is) override
Protected Member Functions inherited from Objet_U_ptr
int change_num (const int *const) override
Objet_U * get_Objet_U_ptr_check () const
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
void recopie (const Objet_U &)
~Objet_U_ptr () override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Operateur_IJK_faces_conv()
Operateur_IJK_faces_conv::Operateur_IJK_faces_conv ()
References convection_op_, convection_op_options_, convection_op_words_, convection_option_, convection_option_rank_, convection_rank_, is_cast_, prefix_, and suffix_.
~Operateur_IJK_faces_conv()
Operateur_IJK_faces_conv::~Operateur_IJK_faces_conv ()
Member Function Documentation
cree_instance()
Objet_U * Operateur_IJK_faces_conv::cree_instance () static
taille_memoire()
unsigned Operateur_IJK_faces_conv::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Operateur_IJK_faces_conv::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Operateur_IJK_faces_conv::info () static
get_info()
const Type_info * Operateur_IJK_faces_conv::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U_ptr.
self_cast() [1/2]
Operateur_IJK_faces_conv & Operateur_IJK_faces_conv::self_cast (Objet_U & r) static
self_cast() [2/2]
const Operateur_IJK_faces_conv & Operateur_IJK_faces_conv::self_cast (const Objet_U & r) static
printOn()
Sortie & Operateur_IJK_faces_conv::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U_ptr.
References convection_op_words_, convection_option_, and convection_rank_.
readOn()
Entree & Operateur_IJK_faces_conv::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U_ptr.
References typer_convection_op().
initialize()
void Operateur_IJK_faces_conv::initialize (const Domaine_IJK & splitting) inline
References Operateur_IJK_faces_conv_base_double::initialize(), is_cast_, typer_convection_op(), and TRUST_Deriv< Operateur_IJK_faces_conv_base_double >::valeur().
Referenced by Navier_Stokes_FTD_IJK::initialise_ns_fields().
lire_motcle_non_standard()
int Operateur_IJK_faces_conv::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Objet_U.
References convection_op_options_, convection_option_, Process::je_suis_maitre(), Motcles::search(), and TRUST_Vector< _CLASSE_ >::size().
search_convection_option_type()
void Operateur_IJK_faces_conv::search_convection_option_type (Entree & is)
References set_convection_option_type().
set_convection_option_type()
void Operateur_IJK_faces_conv::set_convection_option_type (Motcle word)
References convection_op_options_, convection_option_, Motcles::search(), and TRUST_Vector< _CLASSE_ >::size().
Referenced by search_convection_option_type().
set_param()
void Operateur_IJK_faces_conv::set_param (Param & param)
References Param::ajouter_non_std().
typer_convection_op() [1/2]
void Operateur_IJK_faces_conv::typer_convection_op (const char * convection_op)
References get_convection_op_type(), is_cast_, and Objet_U_ptr::typer().
Referenced by initialize(), and readOn().
typer_convection_op() [2/2]
Entree & Operateur_IJK_faces_conv::typer_convection_op (Entree & is)
References get_convection_op_type(), is_cast_, and Objet_U_ptr::typer().
get_convection_op_type()
Nom Operateur_IJK_faces_conv::get_convection_op_type (Motcle word)
References Process::abort(), convection_op_, convection_op_options_, convection_op_words_, convection_option_, convection_option_rank_, convection_rank_, prefix_, Motcles::search(), and suffix_.
Referenced by typer_convection_op().
get_convection_op_option_rank()
int Operateur_IJK_faces_conv::get_convection_op_option_rank () inline
References convection_option_rank_.
Referenced by Navier_Stokes_FTD_IJK::calculer_dv(), and Navier_Stokes_FTD_IJK::initialise_ns_fields().
get_convection_op_option()
Nom Operateur_IJK_faces_conv::get_convection_op_option () inline
References convection_option_.
get_convection_op()
Nom Operateur_IJK_faces_conv::get_convection_op () inline
References convection_op_.
Referenced by Navier_Stokes_FTD_IJK::calculer_dv().
Member Data Documentation
info_obj
const Type_info Operateur_IJK_faces_conv::info_obj static
convection_op_words_
Motcles Operateur_IJK_faces_conv::convection_op_words_ protected
Referenced by get_convection_op_type(), Operateur_IJK_faces_conv(), and printOn().
convection_op_options_
Motcles Operateur_IJK_faces_conv::convection_op_options_ protected
Referenced by get_convection_op_type(), lire_motcle_non_standard(), Operateur_IJK_faces_conv(), and set_convection_option_type().
prefix_
Nom Operateur_IJK_faces_conv::prefix_ protected
Referenced by get_convection_op_type(), and Operateur_IJK_faces_conv().
suffix_
Nom Operateur_IJK_faces_conv::suffix_ protected
Referenced by get_convection_op_type(), and Operateur_IJK_faces_conv().
convection_op_
Nom Operateur_IJK_faces_conv::convection_op_ protected
Referenced by get_convection_op(), get_convection_op_type(), and Operateur_IJK_faces_conv().
convection_option_
Nom Operateur_IJK_faces_conv::convection_option_ protected
Referenced by get_convection_op_option(), get_convection_op_type(), lire_motcle_non_standard(), Operateur_IJK_faces_conv(), printOn(), and set_convection_option_type().
convection_rank_
int Operateur_IJK_faces_conv::convection_rank_ protected
Referenced by get_convection_op_type(), Operateur_IJK_faces_conv(), and printOn().
convection_option_rank_
int Operateur_IJK_faces_conv::convection_option_rank_ protected
Referenced by get_convection_op_option_rank(), get_convection_op_type(), and Operateur_IJK_faces_conv().
is_cast_
bool Operateur_IJK_faces_conv::is_cast_ protected
Referenced by initialize(), Operateur_IJK_faces_conv(), and typer_convection_op().