TrioCFD: Modele_Fonc_Realisable_base Class Reference
Modele_Fonc_Realisable_base Class Reference abstract
#include <Modele_Fonc_Realisable_base.h>
Public Member Functions
const Type_info * get_info () const override
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Modele_Fonc_Realisable_base()
Modele_Fonc_Realisable_base::Modele_Fonc_Realisable_base ()
~Modele_Fonc_Realisable_base()
Modele_Fonc_Realisable_base::~Modele_Fonc_Realisable_base () override
Member Function Documentation
info()
const Type_info * Modele_Fonc_Realisable_base::info () static
get_info()
const Type_info * Modele_Fonc_Realisable_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
Modele_Fonc_Realisable_base & Modele_Fonc_Realisable_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Modele_Fonc_Realisable_base & Modele_Fonc_Realisable_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Modele_Fonc_Realisable_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
References Objet_U::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Modele_Fonc_Realisable_base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
typer_lire_Modele_Fonc_Realisable()
void Modele_Fonc_Realisable_base::typer_lire_Modele_Fonc_Realisable (TRUST_Deriv< Modele_Fonc_Realisable_base > & mod, const Equation_base & eqn, Entree & is) static
References associer(), associer_eqn(), associer_eqn_2(), associer_pb(), Equation_base::discretisation(), Equation_base::domaine_Cl_dis(), Equation_base::domaine_dis(), has_seconde_equation(), Equation_base::probleme(), Objet_U::que_suis_je(), and seconde_equation().
Referenced by Modele_turbulence_hyd_K_Eps_Realisable::lire_motcle_non_standard(), and Modele_turbulence_hyd_K_Eps_Realisable_Bicephale::lire_motcle_non_standard().
equation() [1/2]
const Equation_base & Modele_Fonc_Realisable_base::equation () const inline
References mon_equation, and TRUST_Ref< _CLASSE_ >::valeur().
equation() [2/2]
Equation_base & Modele_Fonc_Realisable_base::equation () inline
References mon_equation, and TRUST_Ref< _CLASSE_ >::valeur().
seconde_equation() [1/2]
const Equation_base & Modele_Fonc_Realisable_base::seconde_equation () const inline
References Process::exit(), ma_seconde_equation, TRUST_Ref< _CLASSE_ >::non_nul(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by typer_lire_Modele_Fonc_Realisable().
seconde_equation() [2/2]
Equation_base & Modele_Fonc_Realisable_base::seconde_equation () inline
References Process::exit(), ma_seconde_equation, TRUST_Ref< _CLASSE_ >::non_nul(), and TRUST_Ref< _CLASSE_ >::valeur().
get_S() [1/2]
const DoubleTab & Modele_Fonc_Realisable_base::get_S () const inline
References S_.
Referenced by Source_Transport_Realisable_VDF_Elem_base::ajouter_keps_real(), and Source_Transport_Realisable_VEF_Face_base::ajouter_keps_real().
get_S() [2/2]
DoubleTab & Modele_Fonc_Realisable_base::get_S () inline
References S_.
get_Cmu() [1/2]
const DoubleTab & Modele_Fonc_Realisable_base::get_Cmu () const inline
References Cmu_.
get_Cmu() [2/2]
DoubleTab & Modele_Fonc_Realisable_base::get_Cmu () inline
References Cmu_.
get_C1() [1/2]
const DoubleTab & Modele_Fonc_Realisable_base::get_C1 () const inline
References C1_.
Referenced by Source_Transport_Realisable_VDF_Elem_base::ajouter_keps_real(), and Source_Transport_Realisable_VEF_Face_base::ajouter_keps_real().
get_C1() [2/2]
DoubleTab & Modele_Fonc_Realisable_base::get_C1 () inline
References C1_.
preparer_calcul()
int Modele_Fonc_Realisable_base::preparer_calcul () virtual
mettre_a_jour()
virtual void Modele_Fonc_Realisable_base::mettre_a_jour (double) pure virtual
Implemented in Modele_Shih_Zhu_Lumley_VDF, and Modele_Shih_Zhu_Lumley_VEF.
discretiser()
void Modele_Fonc_Realisable_base::discretiser () virtual
References Champs_compris_T< FIELD_TYPE >::ajoute_champ(), BR_wall_length_, Discretisation_base::discretiser_champ(), and mon_equation.
Referenced by Modele_turbulence_hyd_K_Eps_Realisable::lire_motcle_non_standard(), and Modele_turbulence_hyd_K_Eps_Realisable_Bicephale::lire_motcle_non_standard().
completer()
void Modele_Fonc_Realisable_base::completer () virtual
associer_pb()
void Modele_Fonc_Realisable_base::associer_pb (const Probleme_base & pb) virtual
References eq_hydraulique, and Probleme_base::equation().
Referenced by typer_lire_Modele_Fonc_Realisable().
associer()
virtual void Modele_Fonc_Realisable_base::associer (const Domaine_dis_base & , const Domaine_Cl_dis_base &) pure virtual
Implemented in Modele_Shih_Zhu_Lumley_VDF, and Modele_Shih_Zhu_Lumley_VEF.
Referenced by typer_lire_Modele_Fonc_Realisable().
sauvegarder()
int Modele_Fonc_Realisable_base::sauvegarder (Sortie &) const override virtual
Sauvegarde d'un Objet_U sur un flot de sortie Methode a surcharger.
Parameters
(Sortie&) flot de sortie a utiliser pour la sauvegarde
Returns
(int) code de retour
Reimplemented from Objet_U.
reprendre()
int Modele_Fonc_Realisable_base::reprendre (Entree &) override virtual
Reprise d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree&) flot d'entree a utiliser pour la reprise
Returns
(int) code de retour
Reimplemented from Objet_U.
Calcul_is_Reynolds_stress_isotrope()
int Modele_Fonc_Realisable_base::Calcul_is_Reynolds_stress_isotrope () const virtual
Calcul_is_Cmu_constant()
int Modele_Fonc_Realisable_base::Calcul_is_Cmu_constant () const virtual
Calcul_S()
virtual void Modele_Fonc_Realisable_base::Calcul_S (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const DoubleTab & vitesse) pure virtual
Implemented in Modele_Shih_Zhu_Lumley_VDF, and Modele_Shih_Zhu_Lumley_VEF.
Calcul_C1()
virtual void Modele_Fonc_Realisable_base::Calcul_C1 (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const DoubleTab & vitesse, const DoubleTab & K_Eps, const double EPS_MIN) pure virtual
Implemented in Modele_Shih_Zhu_Lumley_VDF, and Modele_Shih_Zhu_Lumley_VEF.
Calcul_Cmu_et_S()
virtual void Modele_Fonc_Realisable_base::Calcul_Cmu_et_S (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const DoubleTab & vitesse, const DoubleTab & K_Eps, const double EPS_MIN) pure virtual
Implemented in Modele_Shih_Zhu_Lumley_VDF, and Modele_Shih_Zhu_Lumley_VEF.
Contributions_Sources()
virtual void Modele_Fonc_Realisable_base::Contributions_Sources (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const DoubleTab & vitesse, const DoubleTab & K_Eps, const double EPS_MIN) pure virtual
Implemented in Modele_Shih_Zhu_Lumley_VDF, and Modele_Shih_Zhu_Lumley_VEF.
Referenced by Source_Transport_K_Eps_Realisable_VDF_Elem::mettre_a_jour().
Contributions_Sources_Paroi()
virtual void Modele_Fonc_Realisable_base::Contributions_Sources_Paroi (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const DoubleTab & vitesse, const DoubleTab & K_Eps, const double EPS_MIN, const DoubleTab & visco_tab, const DoubleTab & visco_turb, const DoubleTab & tab_paroi, const int idt) pure virtual
Implemented in Modele_Shih_Zhu_Lumley_VEF, and Modele_Shih_Zhu_Lumley_VDF.
Referenced by Source_Transport_K_Eps_Realisable_VEF_Face::mettre_a_jour().
Calcul_C1_BiK()
virtual void Modele_Fonc_Realisable_base::Calcul_C1_BiK (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const DoubleTab & vitesse, const DoubleTab & K, const DoubleTab & Eps, const double EPS_MIN) pure virtual
Implemented in Modele_Shih_Zhu_Lumley_VDF, and Modele_Shih_Zhu_Lumley_VEF.
Calcul_Cmu_et_S_BiK()
virtual void Modele_Fonc_Realisable_base::Calcul_Cmu_et_S_BiK (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const DoubleTab & vitesse, const DoubleTab & K, const DoubleTab & Eps, const double EPS_MIN) pure virtual
Implemented in Modele_Shih_Zhu_Lumley_VDF, and Modele_Shih_Zhu_Lumley_VEF.
Contributions_Sources_BiK()
virtual void Modele_Fonc_Realisable_base::Contributions_Sources_BiK (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const DoubleTab & vitesse, const DoubleTab & K, const DoubleTab & Eps, const double EPS_MIN) pure virtual
Implemented in Modele_Shih_Zhu_Lumley_VDF, and Modele_Shih_Zhu_Lumley_VEF.
Referenced by Source_Transport_Eps_Realisable_VDF_Elem::mettre_a_jour(), and Source_Transport_K_Realisable_VDF_Elem::mettre_a_jour().
Contributions_Sources_Paroi_BiK()
virtual void Modele_Fonc_Realisable_base::Contributions_Sources_Paroi_BiK (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const DoubleTab & vitesse, const DoubleTab & K, const DoubleTab & Eps, const double EPS_MIN, const DoubleTab & visco_tab, const DoubleTab & visco_turb, const DoubleTab & tab_paroi, const int idt) pure virtual
Implemented in Modele_Shih_Zhu_Lumley_VDF, and Modele_Shih_Zhu_Lumley_VEF.
Referenced by Source_Transport_Eps_Realisable_VEF_Face::mettre_a_jour(), and Source_Transport_K_Realisable_VEF_Face::mettre_a_jour().
lire()
Entree & Modele_Fonc_Realisable_base::lire (const Motcle & , Entree &)
creer_champ()
void Modele_Fonc_Realisable_base::creer_champ (const Motcle & motlu) override virtual
Implements Champs_compris_interface.
get_champ()
const Champ_base & Modele_Fonc_Realisable_base::get_champ (const Motcle & nom) const override virtual
Implements Champs_compris_interface.
References Champs_compris_T< FIELD_TYPE >::get_champ().
has_champ() [1/2]
bool Modele_Fonc_Realisable_base::has_champ (const Motcle & nom, TRUST_Ref< Champ_base * > & ref_champ) const override virtual
Implements Champs_compris_interface.
References Champs_compris_T< FIELD_TYPE >::has_champ().
Referenced by Modele_turbulence_hyd_K_Eps_Realisable::get_champ(), Modele_turbulence_hyd_K_Eps_Realisable_Bicephale::get_champ(), Modele_turbulence_hyd_K_Eps_Realisable::has_champ(), and Modele_turbulence_hyd_K_Eps_Realisable_Bicephale::has_champ().
has_champ() [2/2]
bool Modele_Fonc_Realisable_base::has_champ (const Motcle & nom) const override virtual
Implements Champs_compris_interface.
References Champs_compris_T< FIELD_TYPE >::has_champ().
get_noms_champs_postraitables()
void Modele_Fonc_Realisable_base::get_noms_champs_postraitables (Noms & nom, Option opt = NONE) const override virtual
Implements Champs_compris_interface.
References TRUST_Vector< _CLASSE_ >::add(), and Champs_compris_T< FIELD_TYPE >::liste_noms_compris().
Referenced by Modele_turbulence_hyd_K_Eps_Realisable::get_noms_champs_postraitables(), and Modele_turbulence_hyd_K_Eps_Realisable_Bicephale::get_noms_champs_postraitables().
associer_eqn()
void Modele_Fonc_Realisable_base::associer_eqn (const Equation_base & eqn)
References mon_equation.
Referenced by typer_lire_Modele_Fonc_Realisable().
associer_eqn_2()
void Modele_Fonc_Realisable_base::associer_eqn_2 (const Equation_base & eqn) virtual
References ma_seconde_equation.
Referenced by Modele_turbulence_hyd_K_Eps_Realisable_Bicephale::lire_motcle_non_standard(), and typer_lire_Modele_Fonc_Realisable().
has_seconde_equation()
bool Modele_Fonc_Realisable_base::has_seconde_equation () const inline
References ma_seconde_equation, and TRUST_Ref< _CLASSE_ >::non_nul().
Referenced by typer_lire_Modele_Fonc_Realisable().
Member Data Documentation
info_obj
const Type_info Modele_Fonc_Realisable_base::info_obj static
ma_seconde_equation
TRUST_Ref< Equation_base *> Modele_Fonc_Realisable_base::ma_seconde_equation
Referenced by associer_eqn_2(), has_seconde_equation(), and seconde_equation().
S_
DoubleTab Modele_Fonc_Realisable_base::S_ protected
Referenced by Modele_Shih_Zhu_Lumley_VDF::Calcul_C1(), Modele_Shih_Zhu_Lumley_VEF::Calcul_C1(), Modele_Shih_Zhu_Lumley_VDF::Calcul_C1_BiK(), Modele_Shih_Zhu_Lumley_VEF::Calcul_C1_BiK(), Modele_Shih_Zhu_Lumley_VDF::Calcul_Cmu_et_S(), Modele_Shih_Zhu_Lumley_VEF::Calcul_Cmu_et_S(), Modele_Shih_Zhu_Lumley_VDF::Calcul_Cmu_et_S_BiK(), Modele_Shih_Zhu_Lumley_VEF::Calcul_Cmu_et_S_BiK(), Modele_Shih_Zhu_Lumley_VDF::Calcul_S(), Modele_Shih_Zhu_Lumley_VEF::Calcul_S(), get_S(), Modele_Shih_Zhu_Lumley_VDF::Initialisation(), and Modele_Shih_Zhu_Lumley_VEF::Initialisation().
Cmu_
DoubleTab Modele_Fonc_Realisable_base::Cmu_ protected
Referenced by Modele_Shih_Zhu_Lumley_VDF::Calcul_Cmu_et_S(), Modele_Shih_Zhu_Lumley_VEF::Calcul_Cmu_et_S(), Modele_Shih_Zhu_Lumley_VDF::Calcul_Cmu_et_S_BiK(), Modele_Shih_Zhu_Lumley_VEF::Calcul_Cmu_et_S_BiK(), get_Cmu(), Modele_Shih_Zhu_Lumley_VDF::Initialisation(), and Modele_Shih_Zhu_Lumley_VEF::Initialisation().
C1_
DoubleTab Modele_Fonc_Realisable_base::C1_ protected
Referenced by Modele_Shih_Zhu_Lumley_VDF::Calcul_C1(), Modele_Shih_Zhu_Lumley_VEF::Calcul_C1(), Modele_Shih_Zhu_Lumley_VDF::Calcul_C1_BiK(), Modele_Shih_Zhu_Lumley_VEF::Calcul_C1_BiK(), get_C1(), Modele_Shih_Zhu_Lumley_VDF::Initialisation(), and Modele_Shih_Zhu_Lumley_VEF::Initialisation().
mon_equation
TRUST_Ref< Equation_base *> Modele_Fonc_Realisable_base::mon_equation protected
Referenced by associer_eqn(), discretiser(), and equation().
le_fluide
TRUST_Ref< Fluide_base *> Modele_Fonc_Realisable_base::le_fluide protected
la_vitesse_transportante
TRUST_Ref< Champ_Inc_base *> Modele_Fonc_Realisable_base::la_vitesse_transportante protected
eq_hydraulique
TRUST_Ref< Equation_base *> Modele_Fonc_Realisable_base::eq_hydraulique protected
Referenced by associer_pb(), Modele_Shih_Zhu_Lumley_VDF::Calcul_Cmu_et_S(), Modele_Shih_Zhu_Lumley_VDF::Calcul_Cmu_et_S_BiK(), and Modele_Shih_Zhu_Lumley_VDF::Calcul_S().
visco_
TRUST_Ref< Champ_Don_base *> Modele_Fonc_Realisable_base::visco_ protected
nom_fic
Nom Modele_Fonc_Realisable_base::nom_fic protected
BR_wall_length_
TRUST_Deriv< Champ_Fonc_base > Modele_Fonc_Realisable_base::BR_wall_length_ protected
Referenced by discretiser().
is_Cmu_constant_
int Modele_Fonc_Realisable_base::is_Cmu_constant_ protected
Referenced by Modele_Shih_Zhu_Lumley_VDF::readOn(), and Modele_Shih_Zhu_Lumley_VEF::readOn().
is_Reynolds_stress_isotrope_
int Modele_Fonc_Realisable_base::is_Reynolds_stress_isotrope_ protected