TrioCFD: Champ_Generique_Champ Class Reference
Champ_Generique_Champ Class Reference
#include <Champ_Generique_Champ.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Champ_Generique_refChamp
const Champ_base & get_champ (TRUST_Deriv< Champ_base > &espace_stockage) const override
int get_dimension () const override
const Type_info * get_info () const override
Entity get_localisation (const int index=-1) const override
const Noms get_property (const Motcle &query) const override
virtual const Champ_base & get_ref_champ_base () const
const IntTab & get_ref_connectivity (Entity index1, Entity index2) const override
const DoubleTab & get_ref_coordinates () const override
const DoubleTab & get_ref_values () const override
void initialize (const Champ_base &champ)
int lire_motcle_non_standard (const Motcle &, Entree &) override
void mettre_a_jour (double temps) override
void set_param (Param &param) override
Public Member Functions inherited from Champ_Generique_base
virtual void get_copy_domain (Domaine &) const
virtual void get_copy_values (DoubleTab &) const
virtual int get_dimension () const
const Type_info * get_info () const override
virtual Entity get_localisation (const int index=-1) const
virtual const Noms get_property (const Motcle &query) const
virtual const IntTab & get_ref_connectivity (Entity index1, Entity index2) const
virtual const DoubleTab & get_ref_coordinates () const
virtual const Domaine & get_ref_domain () const
virtual const Domaine_dis_base & get_ref_domaine_dis_base () const
virtual const DoubleTab & get_ref_values () const
virtual void get_xyz_values (const DoubleTab &coords, DoubleTab &values, ArrOfBit &validity_flag) const
int lire_motcle_non_standard (const Motcle &, Entree &) override
void nommer (const Nom &nom) override
int reprendre (Entree &is) override
int sauvegarder (Sortie &os) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
const Champ_base & get_champ (TRUST_Deriv< Champ_base > &espace_stockage) const override
const Champ_base & get_ref_champ_base () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
void set_param (Param &param) override
Protected Member Functions inherited from Champ_Generique_refChamp
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Champ_Generique_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
Constructor & Destructor Documentation
Champ_Generique_Champ()
Champ_Generique_Champ::Champ_Generique_Champ ()
~Champ_Generique_Champ()
Champ_Generique_Champ::~Champ_Generique_Champ ()
Member Function Documentation
cree_instance()
Objet_U * Champ_Generique_Champ::cree_instance () static
taille_memoire()
unsigned Champ_Generique_Champ::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Champ_Generique_Champ::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Champ_Generique_Champ::info () static
get_info()
const Type_info * Champ_Generique_Champ::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
Champ_Generique_Champ & Champ_Generique_Champ::self_cast (Objet_U & r) static
self_cast() [2/2]
const Champ_Generique_Champ & Champ_Generique_Champ::self_cast (const Objet_U & r) static
printOn()
Sortie & Champ_Generique_Champ::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
References Champ_Generique_refChamp::printOn().
readOn()
Entree & Champ_Generique_Champ::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
References Champ_Generique_refChamp::readOn().
set_param()
void Champ_Generique_Champ::set_param (Param & param) override protected virtual
pb_champ : declenche la lecture du nom du probleme (nom_pb_) auquel appartient le champ discret et le nom de ce champ discret (nom_champ_)
nom_source : option pour nommer le champ en tant que source (sinon nommer par defaut)
Implements Champ_Generique_base.
References Param::ajouter(), Param::ajouter_non_std(), Champ_Generique_base::nom_pb_, and Param::REQUIRED.
lire_motcle_non_standard()
int Champ_Generique_Champ::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override protected virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Objet_U.
References champ_, Champ_Generique_refChamp::lire_motcle_non_standard(), Champ_Generique_refChamp::ref_champ_, TRUST_Ref< _CLASSE_ >::reset(), Champ_Generique_refChamp::set_ref_champ(), and TRUST_Deriv< _CLASSE_ >::valeur().
get_champ()
const Champ_base & Champ_Generique_Champ::get_champ (TRUST_Deriv< Champ_base > & espace_stockage) const override protected virtual
Voir Champ_Generique_base::get_champ.
Ici, l'espace_stockage n'est pas utilise, le champ existe deja
Implements Champ_Generique_base.
References champ_.
get_ref_champ_base()
const Champ_base & Champ_Generique_Champ::get_ref_champ_base () const override protected virtual
Renvoie le champ_base sous-jacent.
Teste si le champ a bien ete associe. A terme, cette methode disparaitra de la classe GenericField_base mais reste dans celle-ci (on y teste si le champ a ete associe). Exceptions: Champ_Generique_erreur("NOT_INITIALIZED")
Reimplemented from Champ_Generique_refChamp.
References champ_, and TRUST_Deriv< _CLASSE_ >::valeur().
reset()
void Champ_Generique_Champ::reset () override protected virtual
Implements Champ_Generique_base.
References champ_, Objet_U_ptr::detach(), and Champ_Generique_refChamp::reset().
mettre_a_jour()
void Champ_Generique_Champ::mettre_a_jour (double temps) override protected virtual
Implements Champ_Generique_base.
References champ_, and Champ_base::mettre_a_jour().
Member Data Documentation
info_obj
const Type_info Champ_Generique_Champ::info_obj static
champ_
TRUST_Deriv< Champ_base > Champ_Generique_Champ::champ_ protected
Referenced by get_champ(), get_ref_champ_base(), lire_motcle_non_standard(), mettre_a_jour(), and reset().