TrioCFD: Param Class Reference
Param Class Reference
#include <Param.h>
Public Member Functions
void dictionnaire (const char *, int)
int lire_avec_accolades_depuis (Entree &is)
Detailed Description
On peut lui ajouter un int, un double, un Objet_U, un flag associer a un nom. ajouter_non_std permet d'appeler la methode lire_motcle_non_standard de l'objet passe en parametre. To give synonyms or translation for parameters, use the following syntax: ajouter("keyword|french_keyword|japan_keyword",...) Example: Schema_Temps_base.pp
Member Enumeration Documentation
Nature
enum Param::Nature
Enumerator
OPTIONAL
REQUIRED
Constructor & Destructor Documentation
Param() [1/2]
Param::Param (const char * name)
Param() [2/2]
Param::Param () protected
Member Function Documentation
ajouter() [1/4]
void Param::ajouter (const char * mot, int * quoi, Param::Nature nat = Param::OPTIONAL)
References create_or_get_objet_a_lire(), Objet_a_lire::set_entier(), and Objet_a_lire::set_nature().
Referenced by ajouter_double(), ajouter_int(), ajouter_objet(), Multigrille_base::ajouter_param(), Coarsen_Operator_K::ajouter_param(), Coarsen_Operator_Uniform::ajouter_param(), Multigrille_Adrien::ajouter_param(), DNS_QC_double::interpreter(), DebogFT::interpreter(), Option_DG::interpreter(), IJK_Test_Multigrille::interpreter(), IJK_Lata_Swap_JK::interpreter(), Testeur::interpreter(), Pilote_ICoCo::interpreter(), DebogIJK::interpreter(), Parallel_io_parameters::interpreter(), Test_solveur::interpreter(), Integrer_champ_med::interpreter(), Moyenne_volumique::interpreter(), Execute_parallel::interpreter(), Option_Interpolation::interpreter(), Test_SSE_Kernels::interpreter(), Decouper_multi::interpreter(), MaillerParallel::interpreter(), Raffiner_isotrope_parallele::interpreter(), Extraire_surface_ALE::interpreter_(), Create_domain_from_sub_domain::interpreter_(), DecoupeBord_32_64< _SIZE_ >::interpreter_(), Extraire_domaine::interpreter_(), Extraire_plan::interpreter_(), Extraire_surface::interpreter_(), ExtrudeBord::interpreter_(), ExtrudeParoi::interpreter_(), Extruder::interpreter_(), Extruder_en20::interpreter_(), Extruder_en3::interpreter_(), Remove_elem::interpreter_(), LireMED_32_64< _SIZE_ >::interpreter_(), Postraiter_domaine::interpreter_(), VerifierCoin::interpreter_(), Corriger_frontiere_periodique_32_64< _SIZE_ >::interpreter_(), Traitement_particulier_NS_CEG::lire(), Decouper_32_64< _SIZE_ >::lire(), Transport_Marqueur_FT::lire_cond_init(), Proprietes_part_vol::lire_distribution(), DP_Impose::lire_donnees(), Perte_Charge_Singuliere::lire_donnees(), Schema_Euler_Implicite::lire_facsec_expert(), Transport_Marqueur_FT::lire_injection(), IJK_Thermal_Subresolution::lire_motcle_non_standard(), Statistiques_dns_ijk::lire_motcle_non_standard(), Statistiques_dns_ijk_FT::lire_motcle_non_standard(), Terme_Puissance_Thermique_Echange_Impose_Elem_base::lire_motcle_non_standard(), Maillage_FT_Disc::lire_param_maillage(), Transport_Marqueur_FT::lire_transformation(), Dispersion_bulles_turbulente_Burns::readOn(), Dispersion_bulles_turbulente_constante::readOn(), Flux_2groupes_Smith::readOn(), Flux_interfacial_constant_Nu::readOn(), Flux_parietal_Hibiki::readOn(), Flux_parietal_Kommajosyula::readOn(), Frottement_interfacial_Ishii_Zuber_Deformable::readOn(), Frottement_interfacial_Kumar_Brooks::readOn(), Frottement_interfacial_Tomiyama_complet::readOn(), Masse_ajoutee_Cai::readOn(), Portance_interfaciale_Sugrue_Modifiee::readOn(), Portance_interfaciale_Tomiyama_complet::readOn(), Fluide_R12_c1_gaz::readOn(), Fluide_R12_c1_liquide::readOn(), Coalescence_bulles_1groupe_PolyMAC_P0::readOn(), Coalescence_bulles_2groupes_PolyMAC_P0::readOn(), Correction_Lubchenko_PolyMAC_P0::readOn(), Flux_2groupes_PolyMAC_P0::readOn(), Rupture_bulles_1groupe_PolyMAC_P0::readOn(), Rupture_bulles_2groupes_PolyMAC_P0::readOn(), Source_injection_QDM_base::readOn(), Cond_lim_omega_demi::readOn(), Cond_lim_omega_dix::readOn(), Paroi_frottante_loi::readOn(), Transport_turbulent_GGDH_WIT::readOn(), Transport_turbulent_SGDH_WIT::readOn(), Viscosite_turbulente_k_omega::readOn(), Viscosite_turbulente_k_tau::readOn(), Viscosite_turbulente_sato::readOn(), Viscosite_turbulente_WIF::readOn(), Viscosite_turbulente_WIT::readOn(), Dissipation_WIT_PolyMAC_P0::readOn(), Production_HZDR_PolyMAC_P0::readOn(), Production_WIT_PolyMAC_P0::readOn(), Source_Dissipation_HZDR_PolyMAC_P0::readOn(), Source_Diffusion_croisee_echelle_temp_taux_diss_turb::readOn(), Source_Dissipation_echelle_temp_taux_diss_turb::readOn(), Source_Dissipation_energie_cin_turb::readOn(), Source_Production_echelle_temp_taux_diss_turb::readOn(), Source_Production_energie_cin_turb::readOn(), Parcours_interface::readOn(), Remaillage_FT::readOn(), Senseur_Interface::readOn(), IJK_Interfaces::readOn(), Couplage_Tubes_IBC::readOn(), Tube_impose::readOn(), Tube_libre::readOn(), FT_Field::readOn(), Maillage_FT_IJK::readOn(), Remaillage_FT_IJK::readOn(), Statistiques_dns_ijk::readOn(), consigne_initiale::readOn(), cible_donnee::readOn(), moyenne_par_morceaux::readOn(), moyenne_glissante::readOn(), correction_one_direction::readOn(), corrections_qdm::readOn(), init_forcage_THI::readOn(), Random_process::readOn(), IJK_SolveSys_FD_thermal::readOn(), Frontiere_ouverte_vitesse_vortex::readOn(), Echange_contact_VDF_FT_Disc::readOn(), Echange_contact_VDF_FT_Disc_solid::readOn(), Remailleur_Collision_FT_Juric::readOn(), Remailleur_Collision_FT_Thomas::readOn(), Topologie_Maillage_FT::readOn(), Terme_Source_Constituant_Vortex_VEF_Face::readOn(), Boundary_field_keps_from_ud::readOn(), Boundary_field_uniform_keps_from_ud::readOn(), Field_uniform_keps_from_ud::readOn(), Loi_expert_hydr_EF::readOn(), Loi_expert_scalaire_EF::readOn(), Loi_expert_scalaire_VDF::readOn(), Loi_expert_hydr_VEF::readOn(), Loi_expert_scalaire_VEF::readOn(), Paroi_rugueuse::readOn(), Op_Conv_BTD_EF::readOn(), Op_Conv_SUPG_EF::readOn(), Op_Diff_option_EF::readOn(), Op_Dift_EF_Q1_option::readOn(), Boundary_Conditions::readOn(), Boundary_Conditions_Thermique::readOn(), Multigrille_Adrien::readOn(), IJK_VDF_converter::readOn(), Champ_front_normal::readOn(), Champ_front_xyz_debit::readOn(), Champ_Input_P0_Composite::readOn(), Champ_Fonc_Interp::readOn(), Champ_front_Parametrique::readOn(), Champ_Parametrique::readOn(), Debog_Pb::readOn(), Equation_base::readOn(), PDF_model::readOn(), Source_PDF_base::readOn(), Loi_horaire::readOn(), Value_Input_Int::readOn(), Interpolation_IBM_hybrid::readOn(), Interpolation_IBM_mean_gradient::readOn(), Interpolation_IBM_power_law_tbl_u_star::readOn(), IJK_Grid_Geometry::readOn(), MD_Vector_base::readOn(), MD_Vector_composite::readOn(), MD_Vector_mono::readOn(), MD_Vector_seq::readOn(), MD_Vector_std::readOn(), ILU_SP::readOn(), Solv_GCP::readOn(), Solv_Optimal::readOn(), SolveurSys::readOn(), SSOR::readOn(), Champ_front_MED::readOn(), Parametre_diffusion_implicite::readOn(), Parametre_implicite::readOn(), Moyenne_volumique::readOn(), Correction_Antal_PolyMAC_P0::readOn(), Correction_Tomiyama_PolyMAC_P0::readOn(), Op_Conv_EF_Stab_PolyMAC_Face::readOn(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::readOn(), Chimie::readOn(), Reaction::readOn(), Loi_Etat_Binaire_GP_base::readOn(), Loi_Etat_Mono_GP_base::readOn(), Loi_Etat_TPPI_base::readOn(), Source_Masse_Fluide_Dilatable_base::readOn(), Loi_Etat_Multi_GP_QC::readOn(), Loi_Etat_rhoT_GP_QC::readOn(), Loi_Etat_Multi_GP_WC::readOn(), Terme_Puissance_Thermique_Echange_Impose_Elem_base::readOn(), Changement_phase_Silver_Simpson::readOn(), Diametre_bulles_constant::readOn(), Diametre_bulles_musig::readOn(), Dispersion_bulles_constante::readOn(), Flux_interfacial_Coef_Constant::readOn(), Flux_interfacial_Ranz_Marshall::readOn(), Flux_interfacial_Wolfert::readOn(), Flux_interfacial_Wolfert_composant::readOn(), Flux_interfacial_Zeitoun::readOn(), Flux_parietal_diphasique_simple_lineaire::readOn(), Frottement_interfacial_bulles_composant::readOn(), Frottement_interfacial_bulles_constant::readOn(), Frottement_interfacial_Ishii_Zuber::readOn(), Frottement_interfacial_Tomiyama::readOn(), Frottement_interfacial_Weber::readOn(), Masse_ajoutee_Coef_Constant::readOn(), Masse_ajoutee_Wijngaarden::readOn(), Masse_ajoutee_Zuber::readOn(), Multiplicateur_diphasique_Friedel::readOn(), Multiplicateur_diphasique_homogene::readOn(), Multiplicateur_diphasique_Lottes_Flinn::readOn(), Multiplicateur_diphasique_Muhler_Steinhagen::readOn(), Portance_interfaciale_Constante::readOn(), Portance_interfaciale_Sugrue::readOn(), Portance_interfaciale_Tomiyama::readOn(), Saturation_constant::readOn(), Op_Evanescence_Homogene_Elem_base::readOn(), Op_Evanescence_Homogene_Face_base::readOn(), Source_Dispersion_bulles_base::readOn(), Source_Frottement_interfacial_base::readOn(), Source_Portance_interfaciale_base::readOn(), Loi_paroi_base::readOn(), Transport_turbulent_aire_interfaciale::readOn(), Transport_turbulent_GGDH::readOn(), Transport_turbulent_Prandtl::readOn(), Transport_turbulent_SGDH::readOn(), Viscosite_turbulente_l_melange::readOn(), Viscosite_turbulente_Smagorinsky::readOn(), Viscosite_turbulente_WALE::readOn(), Paroi_decalee_Robin::readOn(), Correction_Antal_VDF::readOn(), ModPerm_Cte::readOn(), ModPerm_Carman_Kozeny::readOn(), VEF_discretisation::readOn(), Terme_Puissance_Thermique_Echange_Impose_VEF_Face::readOn(), Source_Transport_proto::readOn_anisotherme(), Source_Transport_proto::readOn_anisotherme_real(), Source_Transport_proto::readOn_proto(), Source_Transport_proto::readOn_real(), Postprocessing_IJK::reprendre_post(), Couplage_Tubes_IBC::reprendre_probleme(), DNS_QC_double::reprendre_qc(), Fourier_trans::reprise(), Milieu_base::set_additional_params(), Interpolation_IBM_base::set_param(), Interpolation_IBM_elem_fluid::set_param(), Interpolation_IBM_power_law_tbl::set_param(), Prepro_IBM_base::set_param(), Modele_turbulence_scal_base::set_param(), Schema_Temps_IJK_base::set_param(), Schema_Euler_Implicite_Stationnaire::set_param(), Schema_Euler_Implicite::set_param(), Schema_Implicite_Multi_TimeStep_base::set_param(), Modele_turbulence_hyd_2_eq_base::set_param(), Modele_turbulence_scal_Prandtl::set_param(), Modele_turbulence_scal_Schmidt::set_param(), Collision_Model_FT_base::set_param(), Post_Processing_Hydrodynamic_Forces::set_param(), Remaillage_FT::set_param(), Triple_Line_Model_FT_Disc::set_param(), Cut_cell_schema_auxiliaire::set_param(), Facettes_Interp_FT::set_param(), IJK_Thermal_base::set_param(), Switch_double::set_param(), Probleme_FTD_IJK_base::set_param(), IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::set_param(), Modele_Shih_Zhu_Lumley_VDF::set_param(), Modele_Lam_Bremhorst_VEF::set_param(), Modele_Shih_Zhu_Lumley_VEF::set_param(), Paroi_log_QDM::set_param(), Paroi_TBLE_QDM::set_param(), Ecrire_fichier_xyz_valeur::set_param(), Milieu_base::set_param(), Value_Input_Int::set_param(), DomaineAxi1d_32_64< _SIZE_ >::set_param(), PrecondA::set_param(), Solv_GCP_NS::set_param(), Solv_Gen::set_param(), Solv_Gmres::set_param(), Champ_Fonc_MED::set_param(), Champ_front_recyclage::set_param(), Perte_Charge_Gen::set_param(), Terme_Boussinesq_base::set_param(), Terme_Source_Canal_perio::set_param(), Interface_base::set_param(), Modele_turbulence_hyd_base::set_param(), Source_Neutronique::set_param(), Echange_contact_Correlation_VDF::set_param(), Echange_contact_Correlation_VEF::set_param(), Perte_Charge_VEF::set_param(), Solid_Particle_base::set_param(), Solid_Particle_sphere::set_param(), Solid_Particle_spheroid::set_param(), IJK_Thermal_cut_cell::set_param(), IJK_Thermal_Subresolution::set_param(), Postprocessing_IJK::set_param(), Switch_FT_double::set_param(), Probleme_FTD_IJK_cut_cell::set_param(), Fluide_Diphasique::set_param(), ParoiVEF_TBLE::set_param(), Transport_K_Eps::set_param(), Transport_K_Omega::set_param(), Transport_K_ou_Eps::set_param(), Transport_K_ou_Eps_Realisable::set_param(), Modele_turbulence_hyd_combinaison::set_param(), Modele_turbulence_hyd_K_Eps::set_param(), Modele_turbulence_hyd_K_Eps_Bicephale::set_param(), Modele_turbulence_hyd_K_Eps_Realisable::set_param(), Modele_turbulence_hyd_K_Eps_Realisable_Bicephale::set_param(), Modele_turbulence_hyd_K_Omega::set_param(), Modele_turbulence_hyd_RANS_Bicephale_base::set_param(), Modele_turbulence_hyd_RANS_K_Eps_base::set_param(), Modele_turbulence_hyd_RANS_K_Omega_base::set_param(), Champ_Gen_de_Champs_Gen::set_param(), Champ_Generique_Champ::set_param(), Champ_Generique_Extraction::set_param(), Champ_Generique_Interpolation::set_param(), Champ_Generique_Morceau_Equation::set_param(), Champ_Generique_Reduction_0D::set_param(), Champ_Generique_refChamp_special::set_param(), Champ_Generique_Statistiques_base::set_param(), Champ_Generique_Transformation::set_param(), Champ_Post_Operateur_Eqn::set_param(), Loi_Fermeture_Test::set_param(), Partitionneur_Fichier_Decoupage::set_param(), Partitionneur_Fichier_MED::set_param(), Partitionneur_Metis_32_64< _SIZE_ >::set_param(), Partitionneur_Parmetis::set_param(), Partitionneur_Partition::set_param(), Partitionneur_Ptscotch::set_param(), Partitionneur_Sous_Domaine::set_param(), Partitionneur_Sous_Domaines::set_param(), Format_Post_CGNS::set_param(), Format_Post_Lml::set_param(), Format_Post_Med::set_param(), Format_Post_XYZ::set_param(), Postraitement::set_param(), Schema_Implicite_base::set_param(), Espece::set_param(), Fluide_Quasi_Compressible::set_param(), Fluide_Weakly_Compressible::set_param(), Constituant::set_param(), Fluide_base::set_param(), Fluide_Incompressible::set_param(), Fluide_Ostwald::set_param(), Vitesse_derive_base::set_param(), Vitesse_derive_constante::set_param(), Vitesse_derive_Forces::set_param(), Vitesse_derive_Ishii::set_param(), Fluide_reel_base::set_param(), Fluide_stiffened_gas::set_param(), Saturation_base::set_param(), Fluide_generique_CoolProp::set_param(), Fluide_generique_EOS::set_param(), Saturation_generique_CoolProp::set_param(), Saturation_generique_EOS::set_param(), Modele_turbulence_hyd_0_eq_base::set_param(), Modele_turbulence_hyd_LES_base::set_param(), Modele_turbulence_hyd_LES_Smago_VDF::set_param(), Modele_turbulence_hyd_LES_Wale_VDF::set_param(), Modele_turbulence_hyd_Longueur_Melange_VDF::set_param(), Modele_turbulence_hyd_LES_Smago_VEF::set_param(), Modele_turbulence_hyd_LES_Wale_VEF::set_param(), Modele_turbulence_hyd_Longueur_Melange_VEF::set_param(), Equation_base::set_param(), Schema_Temps_base::set_param(), Energie_cinetique_turbulente::set_param(), Navier_Stokes_FTD_IJK::set_param(), Convection_Diffusion_Concentration_FT_Disc::set_param(), Convection_Diffusion_Concentration_Turbulent_FT_Disc::set_param(), Convection_Diffusion_Temperature_FT_Disc::set_param(), Navier_Stokes_FT_Disc::set_param(), Transport_Interfaces_FT_Disc::set_param(), Transport_Marqueur_FT::set_param(), Navier_Stokes_phase_field::set_param(), Modele_turbulence_scal_LES_dyn_VDF::set_param(), Transport_K_Eps_Realisable::set_param(), Transport_K_KEps::set_param(), Perte_Charge_Anisotrope_PolyMAC_Face::set_param(), Perte_Charge_Circulaire_PolyMAC_Face::set_param(), Perte_Charge_Directionnelle_PolyMAC_Face::set_param(), Convection_Diffusion_Espece_Multi_base::set_param(), Convection_Diffusion_Espece_Multi_QC::set_param(), Navier_Stokes_IBM::set_param(), Convection_Diffusion_Concentration::set_param(), Navier_Stokes_std::set_param(), Multi_Sch_ThHyd::set_param(), Sch_CN_EX_iteratif::set_param(), Sch_CN_iteratif::set_param(), Convection_Diffusion_Concentration_Turbulent::set_param(), Perte_Charge_Anisotrope_VDF_Face::set_param(), Perte_Charge_Circulaire_VDF_Face::set_param(), Perte_Charge_Directionnelle_VDF_Face::set_param(), Perte_Charge_Anisotrope_VEF_P1NC::set_param(), Perte_Charge_Circulaire_VEF_P1NC::set_param(), Perte_Charge_Directionnelle_VEF_P1NC::set_param(), Equation_IBM_proto::set_param_ibm_proto(), Switch_double::set_param_reprise(), Switch_FT_double::set_param_reprise(), IJK_Interfaces::set_param_reprise_pb(), Navier_Stokes_FTD_IJK::set_param_reprise_pb(), and Schema_Temps_IJK_base::set_param_reprise_pb().
ajouter() [2/4]
void Param::ajouter (const char * mot, trustIdType * quoi, Param::Nature nat = Param::OPTIONAL)
References create_or_get_objet_a_lire(), Objet_a_lire::set_nature(), and Objet_a_lire::set_tid().
ajouter() [3/4]
void Param::ajouter (const char * mot, double * quoi, Param::Nature nat = Param::OPTIONAL)
References create_or_get_objet_a_lire(), Objet_a_lire::set_double(), and Objet_a_lire::set_nature().
ajouter() [4/4]
void Param::ajouter (const char * mot, Objet_U * quoi, Param::Nature nat = Param::OPTIONAL)
References create_or_get_objet_a_lire(), Objet_a_lire::set_nature(), and Objet_a_lire::set_objet().
ajouter_arr_size_predefinie() [1/2]
void Param::ajouter_arr_size_predefinie (const char * mot, ArrOfInt * quoi, Param::Nature nat = Param::OPTIONAL)
References create_or_get_objet_a_lire(), Objet_a_lire::set_arrofint(), and Objet_a_lire::set_nature().
Referenced by ExtrudeBord::interpreter_(), Extruder::interpreter_(), Extruder_en20::interpreter_(), Extruder_en3::interpreter_(), Proprietes_part_vol::lire_distribution(), and Partitionneur_Tranche_32_64< _SIZE_ >::set_param().
ajouter_arr_size_predefinie() [2/2]
void Param::ajouter_arr_size_predefinie (const char * mot, ArrOfDouble * quoi, Param::Nature nat = Param::OPTIONAL)
References create_or_get_objet_a_lire(), Objet_a_lire::set_arrofdouble(), and Objet_a_lire::set_nature().
ajouter_flag() [1/2]
void Param::ajouter_flag (const char * mot, int * quoi, Param::Nature nat = Param::OPTIONAL)
References create_or_get_objet_a_lire(), Objet_a_lire::set_flag(), and Objet_a_lire::set_nature().
Referenced by Multigrille_base::ajouter_param(), DNS_QC_double::interpreter(), Option_IJK::interpreter(), Test_solveur::interpreter(), Execute_parallel::interpreter(), Option_Interpolation::interpreter(), MaillerParallel::interpreter(), Raffiner_isotrope_parallele::interpreter(), Extraire_surface_ALE::interpreter_(), Extraire_plan::interpreter_(), Extraire_surface::interpreter_(), ExtrudeBord::interpreter_(), ExtrudeParoi::interpreter_(), LireMED_32_64< _SIZE_ >::interpreter_(), VerifierCoin::interpreter_(), Decouper_32_64< _SIZE_ >::lire(), Parcours_interface::readOn(), IJK_Interfaces::readOn(), Tube_libre::readOn(), Statistiques_dns_ijk::readOn(), corrections_qdm::readOn(), Remailleur_Collision_FT_Thomas::readOn(), Topologie_Maillage_FT::readOn(), IJK_VDF_converter::readOn(), PDF_model::readOn(), Source_PDF_base::readOn(), IJK_Grid_Geometry::readOn(), Solv_GCP::readOn(), Solv_Optimal::readOn(), Parametre_implicite::readOn(), Loi_Etat_Multi_GP_QC::readOn(), VEF_discretisation::readOn(), Interpolation_IBM_base::set_param(), Prepro_IBM_base::set_param(), Schema_Temps_IJK_base::set_param(), Transport_K_Eps_base::set_param(), Transport_K_Omega_base::set_param(), Modele_turbulence_hyd_2_eq_base::set_param(), Post_Processing_Hydrodynamic_Forces::set_param(), Triple_Line_Model_FT_Disc::set_param(), Cut_cell_diffusion_auxiliaire::set_param(), IJK_Thermal_base::set_param(), Probleme_FTD_IJK_base::set_param(), IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::set_param(), Paroi_TBLE_QDM::set_param(), Ecrire_fichier_xyz_valeur::set_param(), Solv_Cholesky::set_param(), Solv_Gen::set_param(), Solv_Gmres::set_param(), Champ_Fonc_MED::set_param(), Modele_turbulence_hyd_base::set_param(), Echange_contact_Correlation_VDF::set_param(), Terme_Source_inc_base::set_param(), Echange_contact_Correlation_VEF::set_param(), IJK_Thermal_cut_cell::set_param(), IJK_Thermal_Multiple_Subresolutions::set_param(), IJK_Thermal_Onefluid::set_param(), IJK_Thermal_Subresolution::set_param(), Postprocessing_IJK::set_param(), Paroi_loi_WW_hyd_EF::set_param(), Paroi_loi_WW_hyd_VDF::set_param(), ParoiVDF_TBLE::set_param(), Paroi_loi_WW_hyd_VEF::set_param(), Champ_Post_Operateur_Eqn::set_param(), Partitionneur_Fichier_Decoupage::set_param(), Partitionneur_Metis_32_64< _SIZE_ >::set_param(), Partitionneur_Parmetis::set_param(), Partitionneur_Ptscotch::set_param(), Champ_Generique_modifier_pour_QC::set_param(), Schema_Temps_base::set_param(), Energie_cinetique_turbulente::set_param(), Navier_Stokes_FTD_IJK::set_param(), Convection_Diffusion_Temperature_FT_Disc::set_param(), Navier_Stokes_FT_Disc::set_param(), Transport_Interfaces_FT_Disc::set_param(), Transport_K_KEps::set_param(), and Navier_Stokes_std::set_param().
ajouter_flag() [2/2]
void Param::ajouter_flag (const char * mot, bool * quoi, Param::Nature nat = Param::OPTIONAL)
References create_or_get_objet_a_lire(), Objet_a_lire::set_flag(), and Objet_a_lire::set_nature().
ajouter_param()
Param & Param::ajouter_param (const char * mot, Param::Nature nat = Param::OPTIONAL)
References create_or_get_objet_a_lire(), Objet_a_lire::create_param(), Objet_a_lire::get_name(), proprietaire_, and Objet_a_lire::set_nature().
Referenced by Traitement_particulier_NS_CEG::lire().
ajouter_non_std()
void Param::ajouter_non_std (const char * mot, Objet_U * quoi, Param::Nature nat = Param::OPTIONAL)
References create_or_get_objet_a_lire(), Objet_a_lire::set_nature(), and Objet_a_lire::set_non_std().
Referenced by Statistiques_dns_ijk_FT::completer_read(), Option_CGNS::interpreter(), Option_PolyMAC::interpreter(), Option_VDF::interpreter(), Decouper_multi::interpreter(), Create_domain_from_sub_domain::interpreter_(), Remove_elem::interpreter_(), Postraiter_domaine::interpreter_(), Decouper_32_64< _SIZE_ >::lire(), Statistiques_dns_ijk::readOn(), PDF_model::readOn(), MD_Vector_composite::readOn(), Parametre_diffusion_implicite::readOn(), Reaction::readOn(), Terme_Puissance_Thermique_Echange_Impose_Elem_base::readOn(), Flux_parietal_Nusselt::readOn(), Prepro_IBM_base::set_param(), Modele_turbulence_scal_base::set_param(), Schema_Temps_IJK_base::set_param(), Transport_2eq_base::set_param(), Modele_turbulence_scal_Fluctuation_Temperature::set_param(), Modele_turbulence_scal_Fluctuation_Temperature_W::set_param(), Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re::set_param(), Schema_Euler_Implicite::set_param(), Conduction::set_param(), Collision_Model_FT_base::set_param(), Post_Processing_Hydrodynamic_Forces::set_param(), Proprietes_part_vol::set_param(), Operateur_IJK_elem_conv::set_param(), Operateur_IJK_elem_diff::set_param(), Operateur_IJK_faces_conv::set_param(), Operateur_IJK_faces_diff::set_param(), Solv_Cholesky::set_param(), Solv_GCP_NS::set_param(), Solv_Gen::set_param(), Solv_Gmres::set_param(), Solveur_Lineaire_Std::set_param(), Champ_front_recyclage::set_param(), Perte_Charge_Gen::set_param(), Terme_Boussinesq_base::set_param(), Terme_Source_Canal_perio::set_param(), Terme_Source_Coriolis_base::set_param(), Modele_turbulence_hyd_base::set_param(), Source_Neutronique::set_param(), Echange_contact_Correlation_VDF::set_param(), Source_Darcy_VDF_Face::set_param(), Source_Forchheimer_VDF_Face::set_param(), Echange_contact_Correlation_VEF::set_param(), Perte_Charge_VEF::set_param(), Source_Darcy_VEF_Face::set_param(), Source_Forchheimer_VEF_Face::set_param(), Postraitement_ft_lata::set_param(), Convection_Diffusion_Temperature_sensibility::set_param(), Navier_Stokes_std_sensibility::set_param(), ParoiVDF_TBLE::set_param(), Modele_turbulence_hyd_LES_selectif_mod_VDF::set_param(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::set_param(), Modele_turbulence_hyd_LES_VDF::set_param(), ParoiVEF_TBLE::set_param(), Modele_turbulence_hyd_K_Eps::set_param(), Modele_turbulence_hyd_K_Eps_2_Couches::set_param(), Modele_turbulence_hyd_K_Eps_Bas_Reynolds::set_param(), Modele_turbulence_hyd_K_Eps_Bicephale::set_param(), Modele_turbulence_hyd_K_Eps_Realisable::set_param(), Modele_turbulence_hyd_K_Eps_Realisable_Bicephale::set_param(), Modele_turbulence_hyd_K_Omega::set_param(), Champ_Gen_de_Champs_Gen::set_param(), Champ_Generique_Champ::set_param(), Champ_Generique_Moyenne::set_param(), Champ_Generique_Predefini::set_param(), Champ_Generique_refChamp::set_param(), Champ_Generique_Transformation::set_param(), Partitionneur_Metis_32_64< _SIZE_ >::set_param(), Champ_Fonc_MED_Table_Temps::set_param(), Postraitement::set_param(), Navier_Stokes_Fluide_Dilatable_base::set_param(), Fluide_Dilatable_base::set_param(), Fluide_Quasi_Compressible::set_param(), Constituant::set_param(), Energie_Multiphase::set_param(), Masse_Multiphase::set_param(), QDM_Multiphase::set_param(), Solide::set_param(), Modele_turbulence_hyd_Longueur_Melange_VEF::set_param(), Equation_base::set_param(), Schema_Temps_base::set_param(), Navier_Stokes_Turbulent_ALE::set_param(), Convection_Diffusion_Concentration_FT_Disc::set_param(), Convection_Diffusion_Concentration_Turbulent_FT_Disc::set_param(), Convection_Diffusion_Temperature_FT_Disc::set_param(), Navier_Stokes_FT_Disc::set_param(), Transport_Interfaces_FT_Disc::set_param(), Transport_Marqueur_FT::set_param(), Convection_Diffusion_Phase_field::set_param(), Navier_Stokes_phase_field::set_param(), Schema_Phase_field::set_param(), Equation_rayonnement_base::set_param(), Modele_turbulence_scal_LES_dyn_VDF::set_param(), Transport_K_KEps::set_param(), Perte_Charge_Anisotrope_PolyMAC_Face::set_param(), Perte_Charge_Circulaire_PolyMAC_Face::set_param(), Convection_Diffusion_Chaleur_QC::set_param(), Convection_Diffusion_Temperature_IBM_Turbulent::set_param(), Navier_Stokes_IBM_Turbulent::set_param(), Convection_Diffusion_Concentration::set_param(), Convection_Diffusion_std::set_param(), Convection_Diffusion_Temperature::set_param(), Navier_Stokes_std::set_param(), Convection_Diffusion_Chaleur_Turbulent_QC::set_param(), Convection_Diffusion_Concentration_Turbulent::set_param(), Convection_Diffusion_Espece_Binaire_Turbulent_QC::set_param(), Convection_Diffusion_Espece_Multi_Turbulent_QC::set_param(), Convection_Diffusion_Temperature_Turbulent::set_param(), Navier_Stokes_Turbulent::set_param(), Perte_Charge_Anisotrope_VDF_Face::set_param(), Perte_Charge_Circulaire_VDF_Face::set_param(), Perte_Charge_Anisotrope_VEF_P1NC::set_param(), and Perte_Charge_Circulaire_VEF_P1NC::set_param().
ajouter_condition()
void Param::ajouter_condition (const char * condition, const char * message, const char * name = 0)
References TRUST_List< _CLASSE_ >::add(), list_conditions_, list_message_erreur_conditions_, list_nom_conditions_, and TRUST_List< _CLASSE_ >::size().
Referenced by Postraiter_domaine::interpreter_(), Decouper_32_64< _SIZE_ >::lire(), Loi_expert_scalaire_EF::readOn(), Loi_expert_scalaire_VEF::readOn(), Op_Diff_option_EF::readOn(), Op_Dift_EF_Q1_option::readOn(), Transport_2eq_base::set_param(), Conduction::set_param(), Echange_contact_Correlation_VDF::set_param(), Echange_contact_Correlation_VEF::set_param(), ParoiVEF_TBLE::set_param(), Partitionneur_Metis_32_64< _SIZE_ >::set_param(), Partitionneur_Parmetis::set_param(), Partitionneur_Ptscotch::set_param(), Fluide_Ostwald::set_param(), Masse_Multiphase::set_param(), Solide::set_param(), Modele_turbulence_hyd_LES_Smago_VDF::set_param(), Modele_turbulence_hyd_LES_Wale_VDF::set_param(), Modele_turbulence_hyd_LES_Smago_VEF::set_param(), Modele_turbulence_hyd_LES_Wale_VEF::set_param(), Modele_turbulence_hyd_Longueur_Melange_VEF::set_param(), Convection_Diffusion_Concentration_FT_Disc::set_param(), Convection_Diffusion_Concentration_Turbulent_FT_Disc::set_param(), Convection_Diffusion_Temperature_FT_Disc::set_param(), Transport_Marqueur_FT::set_param(), and Navier_Stokes_std::set_param().
supprimer()
void Param::supprimer (const char * mot)
References Objet_a_lire::comprend_name(), Process::exit(), list_parametre_a_lire_, proprietaire_, and TRUST_List< _CLASSE_ >::suppr().
Referenced by Fluide_Dilatable_base::set_param(), and Fluide_Incompressible::set_param().
supprimer_condition()
void Param::supprimer_condition (const char * name)
References Process::exit(), list_conditions_, list_message_erreur_conditions_, list_nom_conditions_, proprietaire_, TRUST_List< _CLASSE_ >::rang(), and TRUST_List< _CLASSE_ >::suppr().
dictionnaire()
void Param::dictionnaire (const char * nom_option, int valeur)
Si le dernier parametre ajoute est de type "int", associe a ce parametre une ou plusieurs chaines de caracteres et pour chacune une valeur numerique.
Il faut appeler dictionnaire pour chaque motcle autorise pour ce parametre Le parametre lu doit alors etre un motcle parmi ceux du dictionnaire de noms autorises.
References Objet_a_lire::add_dict(), list_parametre_a_lire_, and TRUST_List< _CLASSE_ >::size().
Referenced by Multigrille_base::ajouter_param(), DebogFT::interpreter(), Pilote_ICoCo::interpreter(), DebogIJK::interpreter(), Moyenne_volumique::interpreter(), Maillage_FT_Disc::lire_param_maillage(), IJK_Interfaces::readOn(), Couplage_Tubes_IBC::readOn(), correction_one_direction::readOn(), corrections_qdm::readOn(), Remailleur_Collision_FT_Juric::readOn(), Topologie_Maillage_FT::readOn(), Loi_expert_hydr_VEF::readOn(), Boundary_Conditions::readOn(), Boundary_Conditions_Thermique::readOn(), IJK_VDF_converter::readOn(), Debog_Pb::readOn(), ILU_SP::readOn(), Moyenne_volumique::readOn(), Triple_Line_Model_FT_Disc::set_param(), Cut_cell_schema_auxiliaire::set_param(), IJK_Thermal_base::set_param(), IJK_Thermal_cut_cell::set_param(), IJK_Thermal_Subresolution::set_param(), Probleme_FTD_IJK_cut_cell::set_param(), Transport_K_Eps::set_param(), Transport_K_Omega::set_param(), Transport_K_ou_Eps::set_param(), Transport_K_ou_Eps_Realisable::set_param(), Champ_Generique_Interpolation::set_param(), and Transport_K_Eps_Realisable::set_param().
dictionnaire_param()
Param & Param::dictionnaire_param (const char * nom_option, int valeur)
References Objet_a_lire::add_dict(), list_parametre_a_lire_, proprietaire_, TRUST_List< _CLASSE_ >::size(), and ptrParam::valeur().
ajouter_int()
void Param::ajouter_int (const char * c, int * val, Param::Nature nat = Param::OPTIONAL) inline
References ajouter().
ajouter_double()
void Param::ajouter_double (const char * c, double * val, Param::Nature nat = Param::OPTIONAL) inline
References ajouter().
ajouter_objet()
void Param::ajouter_objet (const char * c, Objet_U * obj, Param::Nature nat = Param::OPTIONAL) inline
References ajouter().
lire_avec_accolades_depuis()
int Param::lire_avec_accolades_depuis (Entree & is)
Read the is input with the parameters (defined with the Param object) inside: { .
.. } Example, to read: { a 1 b 2 } Param param(que_suis_je()); int a,b; param.ajouter("a",&a); param.ajouter("b",&b); param.lire_avec_accolades_depuis(is);
References check(), Process::exit(), and read().
Referenced by Option_DG::interpreter(), Option_IJK::interpreter(), Pilote_ICoCo::interpreter(), Test_solveur::interpreter(), Integrer_champ_med::interpreter(), Option_CGNS::interpreter(), Moyenne_volumique::interpreter(), Execute_parallel::interpreter(), Option_Interpolation::interpreter(), Option_PolyMAC::interpreter(), Option_VDF::interpreter(), Decouper_multi::interpreter(), Extraire_surface_ALE::interpreter_(), Create_domain_from_sub_domain::interpreter_(), DecoupeBord_32_64< _SIZE_ >::interpreter_(), Extraire_domaine::interpreter_(), Extraire_plan::interpreter_(), Extraire_surface::interpreter_(), ExtrudeBord::interpreter_(), ExtrudeParoi::interpreter_(), Extruder::interpreter_(), Extruder_en20::interpreter_(), Extruder_en3::interpreter_(), Remove_elem::interpreter_(), Postraiter_domaine::interpreter_(), VerifierCoin::interpreter_(), Corriger_frontiere_periodique_32_64< _SIZE_ >::interpreter_(), Traitement_particulier_NS_CEG::lire(), Decouper_32_64< _SIZE_ >::lire(), lire_avec_accolades(), Transport_Marqueur_FT::lire_cl(), Transport_Marqueur_FT::lire_cond_init(), Proprietes_part_vol::lire_distribution(), Transport_Marqueur_FT::lire_injection(), IJK_Thermal_Subresolution::lire_motcle_non_standard(), Transport_Marqueur_FT::lire_transformation(), Objet_a_lire::read(), Dispersion_bulles_turbulente_Bazin::readOn(), Dispersion_bulles_turbulente_Burns::readOn(), Dispersion_bulles_turbulente_constante::readOn(), Dispersion_bulles_turbulente_Lavieville::readOn(), Flux_2groupes_Smith::readOn(), Flux_interfacial_constant_Nu::readOn(), Frottement_interfacial_Ishii_Zuber_Deformable::readOn(), Frottement_interfacial_Kumar_Brooks::readOn(), Frottement_interfacial_Tomiyama_complet::readOn(), Masse_ajoutee_Cai::readOn(), Portance_interfaciale_Sugrue_Modifiee::readOn(), Portance_interfaciale_Tomiyama_complet::readOn(), Fluide_R12_c1_gaz::readOn(), Fluide_R12_c1_liquide::readOn(), Coalescence_bulles_1groupe_PolyMAC_P0::readOn(), Coalescence_bulles_2groupes_PolyMAC_P0::readOn(), Correction_Lubchenko_PolyMAC_P0::readOn(), Flux_2groupes_PolyMAC_P0::readOn(), Rupture_bulles_1groupe_PolyMAC_P0::readOn(), Rupture_bulles_2groupes_PolyMAC_P0::readOn(), Source_injection_QDM_base::readOn(), Cond_lim_omega_demi::readOn(), Cond_lim_omega_dix::readOn(), Paroi_frottante_loi::readOn(), Transport_turbulent_GGDH_WIT::readOn(), Transport_turbulent_SGDH_WIT::readOn(), Viscosite_turbulente_k_omega::readOn(), Viscosite_turbulente_k_tau::readOn(), Viscosite_turbulente_sato::readOn(), Viscosite_turbulente_WIF::readOn(), Viscosite_turbulente_WIT::readOn(), Dissipation_WIT_PolyMAC_P0::readOn(), Production_HZDR_PolyMAC_P0::readOn(), Production_WIT_PolyMAC_P0::readOn(), Source_BIF_PolyMAC_P0::readOn(), Source_Dissipation_HZDR_PolyMAC_P0::readOn(), Source_Diffusion_croisee_echelle_temp_taux_diss_turb::readOn(), Source_Dissipation_echelle_temp_taux_diss_turb::readOn(), Source_Dissipation_energie_cin_turb::readOn(), Source_Production_echelle_temp_taux_diss_turb::readOn(), Source_Production_energie_cin_turb::readOn(), Collision_Model_FT_base::readOn(), Post_Processing_Hydrodynamic_Forces::readOn(), Parcours_interface::readOn(), Proprietes_part_vol::readOn(), Remaillage_FT::readOn(), Senseur_Interface::readOn(), Navier_Stokes_FTD_IJK::readOn(), Schema_Temps_IJK_base::readOn(), Remaillage_FT_IJK::readOn(), Frontiere_ouverte_vitesse_vortex::readOn(), Remailleur_Collision_FT_Juric::readOn(), Remailleur_Collision_FT_Thomas::readOn(), Topologie_Maillage_FT::readOn(), Terme_Source_Constituant_Vortex_VEF_Face::readOn(), Triple_Line_Model_FT_Disc::readOn(), Paroi_loi_WW_hyd_EF::readOn(), Loi_expert_hydr_EF::readOn(), Loi_expert_scalaire_EF::readOn(), Paroi_loi_WW_hyd_VDF::readOn(), Loi_expert_hydr_VDF::readOn(), ParoiVDF_TBLE::readOn(), Loi_expert_scalaire_VDF::readOn(), Modele_Shih_Zhu_Lumley_VDF::readOn(), Paroi_loi_WW_hyd_VEF::readOn(), Loi_expert_hydr_VEF::readOn(), ParoiVEF_TBLE::readOn(), Loi_expert_scalaire_VEF::readOn(), Modele_EASM_Baglietto_VEF::readOn(), Modele_Lam_Bremhorst_VEF::readOn(), Modele_Launder_Sharma_VEF::readOn(), Modele_Shih_Zhu_Lumley_VEF::readOn(), Modele_standard_KEps_VEF::readOn(), Op_Diff_option_EF::readOn(), Op_Dift_EF_Q1_option::readOn(), Champ_front_xyz_debit::readOn(), Champ_Input_P0_Composite::readOn(), Champ_Fonc_Interp::readOn(), Champ_front_Parametrique::readOn(), Champ_Generique_base::readOn(), Champ_Parametrique::readOn(), Ecrire_fichier_xyz_valeur::readOn(), Equation_base::readOn(), PDF_model::readOn(), Loi_Fermeture_base::readOn(), Loi_horaire::readOn(), Milieu_base::readOn(), Schema_Temps_base::readOn(), Value_Input_Int::readOn(), Partitionneur_base_32_64< _SIZE_ >::readOn(), DomaineAxi1d_32_64< _SIZE_ >::readOn(), Interpolation_IBM_elem_fluid::readOn(), Interpolation_IBM_hybrid::readOn(), Interpolation_IBM_mean_gradient::readOn(), Interpolation_IBM_power_law_tbl::readOn(), Interpolation_IBM_power_law_tbl_u_star::readOn(), Prepro_IBM_Ponderation::readOn(), Prepro_IBM_Uzawa::readOn(), PrecondA::readOn(), Solv_Cholesky::readOn(), Solv_GCP::readOn(), Solv_GCP_NS::readOn(), Solv_Gen::readOn(), Solv_Gmres::readOn(), Solv_Optimal::readOn(), Format_Post_base::readOn(), Postraitement_base::readOn(), Parametre_diffusion_implicite::readOn(), Parametre_implicite::readOn(), Solveur_Lineaire_Std::readOn(), Moyenne_volumique::readOn(), Champ_front_recyclage::readOn(), Correction_Antal_PolyMAC_P0::readOn(), Correction_Tomiyama_PolyMAC_P0::readOn(), Op_Conv_EF_Stab_PolyMAC_Face::readOn(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::readOn(), Chimie::readOn(), Reaction::readOn(), Loi_Etat_Binaire_GP_base::readOn(), Loi_Etat_Mono_GP_base::readOn(), Source_Masse_Fluide_Dilatable_base::readOn(), Loi_Etat_Multi_GP_QC::readOn(), Loi_Etat_Multi_GP_WC::readOn(), Perte_Charge_Gen::readOn(), Terme_Boussinesq_base::readOn(), Terme_Puissance_Thermique_Echange_Impose_Elem_base::readOn(), Terme_Source_Canal_perio::readOn(), Terme_Source_Coriolis_base::readOn(), Changement_phase_Silver_Simpson::readOn(), Diametre_bulles_constant::readOn(), Diametre_bulles_musig::readOn(), Dispersion_bulles_constante::readOn(), Flux_interfacial_Coef_Constant::readOn(), Flux_interfacial_Ranz_Marshall::readOn(), Flux_interfacial_Wolfert::readOn(), Flux_interfacial_Wolfert_composant::readOn(), Flux_interfacial_Zeitoun::readOn(), Flux_parietal_diphasique_simple_lineaire::readOn(), Flux_parietal_Nusselt::readOn(), Frottement_interfacial_bulles_composant::readOn(), Frottement_interfacial_bulles_constant::readOn(), Frottement_interfacial_Ishii_Zuber::readOn(), Frottement_interfacial_Sonnenburg::readOn(), Frottement_interfacial_Tomiyama::readOn(), Frottement_interfacial_Wallis::readOn(), Frottement_interfacial_Weber::readOn(), Masse_ajoutee_Coef_Constant::readOn(), Masse_ajoutee_Wijngaarden::readOn(), Masse_ajoutee_Zuber::readOn(), Multiplicateur_diphasique_Friedel::readOn(), Multiplicateur_diphasique_homogene::readOn(), Multiplicateur_diphasique_Lottes_Flinn::readOn(), Multiplicateur_diphasique_Muhler_Steinhagen::readOn(), Portance_interfaciale_Constante::readOn(), Portance_interfaciale_Sugrue::readOn(), Portance_interfaciale_Tomiyama::readOn(), Vitesse_relative_base::readOn(), Interface_base::readOn(), Saturation_base::readOn(), Saturation_constant::readOn(), Op_Evanescence_Homogene_Elem_base::readOn(), Op_Evanescence_Homogene_Face_base::readOn(), Source_Dispersion_bulles_base::readOn(), Source_Frottement_interfacial_base::readOn(), Source_Portance_interfaciale_base::readOn(), Loi_paroi_base::readOn(), Transport_turbulent_aire_interfaciale::readOn(), Transport_turbulent_GGDH::readOn(), Transport_turbulent_Prandtl::readOn(), Transport_turbulent_SGDH::readOn(), Viscosite_turbulente_l_melange::readOn(), Viscosite_turbulente_Smagorinsky::readOn(), Viscosite_turbulente_WALE::readOn(), Paroi_decalee_Robin::readOn(), Modele_turbulence_hyd_base::readOn(), Modele_turbulence_hyd_null::readOn(), Modele_turbulence_scal_base::readOn(), Modele_turbulence_scal_null::readOn(), Source_Neutronique::readOn(), Echange_contact_Correlation_VDF::readOn(), Correction_Antal_VDF::readOn(), ModPerm_Cte::readOn(), ModPerm_Carman_Kozeny::readOn(), Source_Darcy_VDF_Face::readOn(), Source_Forchheimer_VDF_Face::readOn(), Terme_Source_inc_base::readOn(), Echange_contact_Correlation_VEF::readOn(), Perte_Charge_VEF::readOn(), Source_Darcy_VEF_Face::readOn(), Source_Forchheimer_VEF_Face::readOn(), Terme_Puissance_Thermique_Echange_Impose_VEF_Face::readOn(), and Modele_turbulence_hyd_Longueur_Melange_VEF::readOn().
lire_sans_accolade()
int Param::lire_sans_accolade (Entree & is)
References TRUST_List< _CLASSE_ >::add(), check(), Process::exit(), Objet_a_lire::get_name(), Objet_a_lire::is_optional(), list_parametre_a_lire_, list_parametre_lu_, proprietaire_, and Objet_a_lire::read().
Referenced by IJK_Thermal_Subresolution::lire_motcle_non_standard(), IJK_SolveSys_FD_thermal::readOn(), SolveurSys::readOn(), and Champ_front_MED::readOn().
lire_avec_accolades()
int Param::lire_avec_accolades (Entree & is) inline
References lire_avec_accolades_depuis().
Referenced by DNS_QC_double::interpreter(), DebogFT::interpreter(), Switch_double::interpreter(), IJK_Test_Multigrille::interpreter(), IJK_Lata_Swap_JK::interpreter(), Testeur::interpreter(), DebogIJK::interpreter(), Parallel_io_parameters::interpreter(), Test_SSE_Kernels::interpreter(), MaillerParallel::interpreter(), Raffiner_isotrope_parallele::interpreter(), LireMED_32_64< _SIZE_ >::interpreter_(), DP_Impose::lire_donnees(), Perte_Charge_Singuliere::lire_donnees(), Schema_Euler_Implicite::lire_facsec_expert(), Switch_double::lire_fichier_reprise(), Statistiques_dns_ijk::lire_motcle_non_standard(), Statistiques_dns_ijk_FT::lire_motcle_non_standard(), Terme_Puissance_Thermique_Echange_Impose_Elem_base::lire_motcle_non_standard(), Maillage_FT_Disc::lire_param_maillage(), Flux_parietal_Hibiki::readOn(), Flux_parietal_Kommajosyula::readOn(), Flux_parietal_Kurul_Podowski::readOn(), Cut_cell_convection_auxiliaire::readOn(), Cut_cell_diffusion_auxiliaire::readOn(), Cut_cell_schema_auxiliaire::readOn(), Facettes_Interp_FT::readOn(), IJK_Interfaces::readOn(), IJK_Thermal_base::readOn(), Couplage_Tubes_IBC::readOn(), Tube_impose::readOn(), Tube_libre::readOn(), FT_Field::readOn(), Maillage_FT_IJK::readOn(), Statistiques_dns_ijk::readOn(), Probleme_FTD_IJK_base::readOn(), consigne_initiale::readOn(), cible_donnee::readOn(), moyenne_par_morceaux::readOn(), moyenne_glissante::readOn(), correction_one_direction::readOn(), corrections_qdm::readOn(), init_forcage_THI::readOn(), Random_process::readOn(), IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::readOn(), Echange_contact_VDF_FT_Disc::readOn(), Echange_contact_VDF_FT_Disc_solid::readOn(), Boundary_field_keps_from_ud::readOn(), Boundary_field_uniform_keps_from_ud::readOn(), Field_uniform_keps_from_ud::readOn(), Paroi_rugueuse::readOn(), Op_Conv_BTD_EF::readOn(), Op_Conv_SUPG_EF::readOn(), Boundary_Conditions::readOn(), Boundary_Conditions_Thermique::readOn(), Coarsen_Operator_base::readOn(), Multigrille_Adrien::readOn(), IJK_VDF_converter::readOn(), Champ_front_normal::readOn(), Debog_Pb::readOn(), Source_PDF_base::readOn(), IJK_Grid_Geometry::readOn(), MD_Vector_base::readOn(), MD_Vector_composite::readOn(), MD_Vector_mono::readOn(), MD_Vector_seq::readOn(), MD_Vector_std::readOn(), ILU_SP::readOn(), SSOR::readOn(), Champ_Fonc_MED::readOn(), Loi_Etat_rhoT_GP_QC::readOn(), VEF_discretisation::readOn(), Source_Transport_proto::readOn_anisotherme(), Source_Transport_proto::readOn_anisotherme_real(), Source_Transport_proto::readOn_nothing(), Source_Transport_proto::readOn_proto(), Source_Transport_proto::readOn_real(), Probleme_FTD_IJK_base::reprendre_probleme(), Couplage_Tubes_IBC::reprendre_probleme(), DNS_QC_double::reprendre_qc(), and Fourier_trans::reprise().
read()
int Param::read (Entree & is, int with_acco = 1)
References TRUST_List< _CLASSE_ >::add(), Objet_a_lire::comprend_name(), Process::exit(), list_parametre_a_lire_, list_parametre_lu_, proprietaire_, Objet_a_lire::read(), and TRUST_List< _CLASSE_ >::size().
Referenced by interface_CALCULBIJ::init_from_file(), interface_CALCULSI::init_from_file(), interface_INITGAUSS::init_from_file(), and lire_avec_accolades_depuis().
print()
void Param::print (Sortie & s) const
References list_parametre_a_lire_, Objet_a_lire::print(), and TRUST_List< _CLASSE_ >::size().
Referenced by interface_CALCULBIJ::dump(), interface_CALCULSI::dump(), interface_INITGAUSS::dump(), Triple_Line_Model_FT_Disc::printOn(), and Remaillage_FT_IJK::readOn().
get_list_mots_lus()
const TRUST_List< Nom > & Param::get_list_mots_lus () const inline
References list_parametre_lu_.
Referenced by Traitement_particulier_NS_CEG::lire(), Loi_expert_hydr_EF::readOn(), Loi_expert_hydr_VEF::readOn(), Parametre_implicite::readOn(), and Modele_turbulence_hyd_Longueur_Melange_VEF::readOn().
get_value()
double Param::get_value (const Nom & mot_lu) const
References Process::exit(), Objet_a_lire::get_name(), Objet_a_lire::get_value(), Objet_a_lire::is_type_simple(), list_parametre_a_lire_, and TRUST_List< _CLASSE_ >::size().
Referenced by check().
check()
int Param::check ()
References TRUST_List< _CLASSE_ >::add(), Parser_U::addVar(), TRUST_List< _CLASSE_ >::contient(), Parser_U::eval(), Objet_a_lire::get_name(), get_value(), Objet_a_lire::is_optional(), Objet_a_lire::is_type_simple(), list_conditions_, list_message_erreur_conditions_, list_nom_conditions_, list_parametre_a_lire_, list_parametre_lu_, Parser_U::parseString(), proprietaire_, Parser_U::setNbVar(), Parser_U::setString(), Parser_U::setVar(), and TRUST_List< _CLASSE_ >::size().
Referenced by lire_avec_accolades_depuis(), and lire_sans_accolade().
create_or_get_objet_a_lire()
Objet_a_lire & Param::create_or_get_objet_a_lire (const char * mot) protected
renvoit Objet_a_lire correspondant au mot le rajoute au besoin a la liste
References TRUST_List< _CLASSE_ >::add(), Process::exit(), list_parametre_a_lire_, proprietaire_, and Objet_a_lire::set_name().
Referenced by ajouter(), ajouter_arr_size_predefinie(), ajouter_flag(), ajouter_non_std(), and ajouter_param().
Member Data Documentation
list_parametre_a_lire_
TRUST_List< Objet_a_lire > Param::list_parametre_a_lire_ protected
Referenced by check(), create_or_get_objet_a_lire(), dictionnaire(), dictionnaire_param(), get_value(), lire_sans_accolade(), print(), read(), and supprimer().
proprietaire_
Nom Param::proprietaire_ protected
Referenced by ajouter_param(), check(), create_or_get_objet_a_lire(), dictionnaire_param(), lire_sans_accolade(), read(), supprimer(), and supprimer_condition().
list_parametre_lu_
TRUST_List< Nom > Param::list_parametre_lu_ protected
Referenced by check(), get_list_mots_lus(), lire_sans_accolade(), and read().
list_conditions_
TRUST_List< Nom > Param::list_conditions_ protected
Referenced by ajouter_condition(), check(), and supprimer_condition().
list_message_erreur_conditions_
TRUST_List< Nom > Param::list_message_erreur_conditions_ protected
Referenced by ajouter_condition(), check(), and supprimer_condition().
list_nom_conditions_
TRUST_List< Nom > Param::list_nom_conditions_ protected
Referenced by ajouter_condition(), check(), and supprimer_condition().