TrioCFD: Iterateur_VDF_base Class Reference
Iterateur_VDF_base Class Reference abstract
#include <Iterateur_VDF_base.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Iterateur_VDF_base()
Iterateur_VDF_base::Iterateur_VDF_base ()
~Iterateur_VDF_base()
Iterateur_VDF_base::~Iterateur_VDF_base () override
Member Function Documentation
info()
const Type_info * Iterateur_VDF_base::info () static
get_info()
const Type_info * Iterateur_VDF_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
Iterateur_VDF_base & Iterateur_VDF_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Iterateur_VDF_base & Iterateur_VDF_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Iterateur_VDF_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
References Objet_U::que_suis_je().
readOn()
Entree & Iterateur_VDF_base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
associer()
void Iterateur_VDF_base::associer (const Domaine_VDF & domaine_vdf, const Domaine_Cl_VDF & domaine_cl_vdf, const Operateur_base & op)
References la_zcl, le_dom, and op_base.
Referenced by Op_Div_VDF_Elem::associer(), Op_Diff_K_Eps_VDF_Generique< OP_TYPE >::associer_impl(), and Op_Diff_K_Omega_VDF_Generique< OP_TYPE >::associer_impl().
associer_domaine_cl_dis()
void Iterateur_VDF_base::associer_domaine_cl_dis (const Domaine_Cl_dis_base & zcl)
References la_zcl.
Referenced by Op_Conv_VDF_base::associer_domaine_cl_dis().
associer_champ_convecte_ou_inc()
void Iterateur_VDF_base::associer_champ_convecte_ou_inc (const Champ_Inc_base & ch, const Champ_base * chv, bool use = false)
References le_ch_v, le_champ_convecte_ou_inc, and use_base_val_b_.
Referenced by Op_Conv_VDF_base::associer_champ_convecte_elem(), Op_Conv_VDF_base::associer_champ_convecte_face(), Op_Diff_K_Eps_Bas_Re_VDF_base::completer(), Op_Diff_K_Eps_VDF_base::completer(), Op_Diff_K_Omega_VDF_base::completer(), Op_Diff_VDF_base::completer(), and Op_Div_VDF_base::completer().
ajouter_blocs()
virtual void Iterateur_VDF_base::ajouter_blocs (matrices_t mats, DoubleTab & secmem, const tabs_t & semi_impl) const pure virtual
Implemented in Iterateur_VDF_Elem< _TYPE_ >, and Iterateur_VDF_Face< _TYPE_ >.
Referenced by ajouter(), Op_Diff_K_Eps_Bas_Re_VDF_base::ajouter_blocs(), Op_Diff_VDF_Elem_base::ajouter_blocs(), Op_Diff_VDF_Face_base::ajouter_blocs(), Op_Dift_VDF_base::ajouter_blocs(), Op_Conv_VDF_base::ajouter_blocs(), and ajouter_contribution().
ajouter_contribution_autre_pb()
virtual void Iterateur_VDF_base::ajouter_contribution_autre_pb (const DoubleTab & , Matrice_Morse & , const Cond_lim & , std::map< int, std::pair< int, int > > &) const inline virtual
Reimplemented in Iterateur_VDF_Elem< _TYPE_ >.
Referenced by Op_Diff_VDF_Elem_base::contribuer_termes_croises().
contribuer_au_second_membre()
virtual void Iterateur_VDF_base::contribuer_au_second_membre (DoubleTab &) const inline virtual
Reimplemented in Iterateur_VDF_Elem< _TYPE_ >.
References Process::exit().
Referenced by Op_Diff_VDF_base::contribuer_au_second_membre().
completer_()
virtual void Iterateur_VDF_base::completer_ () pure virtual
Implemented in Iterateur_VDF_Elem< _TYPE_ >, and Iterateur_VDF_Face< _TYPE_ >.
Referenced by Op_Diff_K_Eps_Bas_Re_VDF_base::completer(), Op_Diff_K_Eps_VDF_base::completer(), Op_Diff_K_Omega_VDF_base::completer(), Op_Conv_VDF_base::completer(), Op_Diff_VDF_base::completer(), and Op_Div_VDF_base::completer().
impr()
virtual int Iterateur_VDF_base::impr (Sortie & os) const pure virtual
Implemented in Iterateur_VDF_Elem< _TYPE_ >, and Iterateur_VDF_Face< _TYPE_ >.
Referenced by Op_Conv_VDF_base::impr(), Op_Diff_VDF_base::impr(), and Op_Div_VDF_base::impr().
evaluateur() [1/2]
virtual Evaluateur_VDF & Iterateur_VDF_base::evaluateur () pure virtual
Implemented in Iterateur_VDF_Elem< _TYPE_ >, and Iterateur_VDF_Face< _TYPE_ >.
Referenced by Op_Diff_VDF_base::ajoute_terme_pour_axi(), Op_Dift_VDF_base::ajoute_terme_pour_axi_turb(), Op_Diff_Dift_VDF< OP_TYPE >::alpha_impl(), Op_Div_VDF_Elem::associer(), Op_Diff_Dift_VDF< OP_TYPE >::associer_corr_impl(), Op_Diff_K_Eps_VDF_base::associer_diffusivite(), Op_Diff_K_Omega_VDF_base::associer_diffusivite(), Op_Diff_K_Eps_Bas_Re_VDF_base::associer_diffusivite_impl(), Op_Diff_Dift_VDF< OP_TYPE >::associer_diffusivite_impl(), Op_Diff_K_Omega_VDF_base::associer_diffusivite_turbulente(), Op_Diff_K_Eps_Bas_Re_VDF_base::associer_diffusivite_turbulente_impl(), Op_Diff_Dift_VDF< OP_TYPE >::associer_diffusivite_turbulente_impl(), Op_Diff_K_Eps_VDF_Generique< OP_TYPE >::associer_impl(), Op_Diff_K_Omega_VDF_Generique< OP_TYPE >::associer_impl(), Op_Diff_Dift_VDF< OP_TYPE >::associer_loipar_impl(), Op_Diff_Dift_VDF< OP_TYPE >::associer_pb(), Op_Conv_VDF< OP_TYPE >::associer_vitesse_impl(), Op_Diff_K_Eps_Bas_Re_VDF_var_Elem::completer(), Op_Diff_K_Eps_VDF_base::completer(), Op_Diff_K_Omega_VDF_base::completer(), Op_Diff_Dift_VDF< OP_TYPE >::completer_impl(), Op_Diff_K_Eps_VDF_base::diffusivite(), Op_Diff_K_Omega_VDF_base::diffusivite(), Op_Diff_K_Eps_Bas_Re_VDF_base::diffusivite_impl(), Op_Diff_Dift_VDF< OP_TYPE >::diffusivite_impl(), Op_Diff_K_Eps_VDF_base::diffusivite_turbulente(), Op_Diff_K_Omega_VDF_base::diffusivite_turbulente(), Op_Diff_K_Eps_Bas_Re_VDF_base::diffusivite_turbulente_impl(), Op_Diff_Dift_VDF< OP_TYPE >::get_diffusivite_turbulente_multiphase_impl(), T_paroi_Champ_P0_VDF::me_calculer(), Op_Diff_Dift_VDF< OP_TYPE >::mettre_a_jour_impl(), Op_Diff_Dift_VDF< OP_TYPE >::set_nut_impl(), Op_Diff_Dift_VDF< OP_TYPE >::tab_alpha_impl(), and Op_Conv_VDF< OP_TYPE >::vitesse_impl().
evaluateur() [2/2]
virtual const Evaluateur_VDF & Iterateur_VDF_base::evaluateur () const pure virtual
Implemented in Iterateur_VDF_Elem< _TYPE_ >, and Iterateur_VDF_Face< _TYPE_ >.
domaine()
const Domaine_VDF & Iterateur_VDF_base::domaine () const inline
References le_dom, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Op_Diff_VDF_base::ajoute_terme_pour_axi(), Op_Dift_VDF_base::ajoute_terme_pour_axi_turb(), Op_Conv_Amont_VPoly_VDF_Face::ajouter_blocs(), Op_Dift_VDF_Face_base::calculer_borne_locale(), Op_Conv_VDF_base::calculer_dt_local(), Op_Diff_K_Eps_Bas_Re_VDF_var_Elem::calculer_dt_stab(), Op_Conv_VDF_base::calculer_dt_stab(), Op_Diff_VDF_Elem_base::calculer_dt_stab(), Op_Diff_VDF_Face_base::calculer_dt_stab(), Op_Dift_VDF_Face_base::calculer_dt_stab(), Op_Dift_Multiphase_VDF_Elem::calculer_dt_stab(), Op_Dift_Multiphase_VDF_Face::calculer_dt_stab(), Op_Dift_VDF_Elem_base::calculer_dt_stab_elem(), Op_Dift_VDF_Elem_base::calculer_dt_stab_elem_axi(), Op_Dift_VDF_Elem_base::calculer_dt_stab_elem_var_axi(), Op_Conv_VDF_base::calculer_pour_post(), Op_Diff_VDF_Elem_base::contribuer_termes_croises(), Op_Diff_K_Eps_Bas_Re_VDF_base::dimensionner_blocs(), Op_Diff_K_Eps_VDF_base::dimensionner_blocs(), Op_Diff_K_Omega_VDF_base::dimensionner_blocs(), Op_Diff_VDF_Elem_base::dimensionner_blocs(), Op_Diff_VDF_Face_base::dimensionner_blocs(), Op_Dift_VDF_Elem_base::dimensionner_blocs(), Op_Dift_VDF_Face_base::dimensionner_blocs(), Op_Conv_VDF_base::dimensionner_blocs_elem(), Op_Conv_VDF_base::dimensionner_blocs_face(), Op_Diff_VDF_Elem_base::dimensionner_termes_croises(), Op_Diff_VDF_base::init_op_ext(), Op_Conv_VDF_base::mettre_a_jour(), Op_Diff_K_Eps_VDF_base::modifier_pour_Cl(), Op_Diff_K_Omega_VDF_base::modifier_pour_Cl(), Op_Diff_K_Eps_Bas_Re_VDF_base::modifier_pour_Cl(), Op_Diff_VDF_Elem_base::modifier_pour_Cl(), Op_Diff_VDF_Face_base::modifier_pour_Cl(), Op_Dift_VDF_Elem_base::modifier_pour_Cl(), and Op_Dift_VDF_Face_base::modifier_pour_Cl().
domaine_Cl()
const Domaine_Cl_VDF & Iterateur_VDF_base::domaine_Cl () const inline
References la_zcl, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Op_Conv_Amont_VPoly_VDF_Face::ajouter_blocs(), Op_Conv_VDF_base::calculer_dt_local(), Op_Conv_VDF_base::calculer_dt_stab(), Op_Conv_VDF_base::calculer_pour_post(), Op_Diff_VDF_Elem_base::contribuer_termes_croises(), Op_Diff_K_Eps_Bas_Re_VDF_base::dimensionner_blocs(), Op_Diff_K_Eps_VDF_base::dimensionner_blocs(), Op_Diff_K_Omega_VDF_base::dimensionner_blocs(), Op_Diff_VDF_Elem_base::dimensionner_blocs(), Op_Diff_VDF_Face_base::dimensionner_blocs(), Op_Dift_VDF_Elem_base::dimensionner_blocs(), Op_Dift_VDF_Face_base::dimensionner_blocs(), Op_Diff_VDF_Elem_base::dimensionner_termes_croises(), Op_Diff_VDF_base::init_op_ext(), Op_Diff_K_Eps_VDF_base::modifier_pour_Cl(), Op_Diff_K_Omega_VDF_base::modifier_pour_Cl(), Op_Diff_K_Eps_Bas_Re_VDF_base::modifier_pour_Cl(), Op_Diff_VDF_Elem_base::modifier_pour_Cl(), Op_Diff_VDF_Face_base::modifier_pour_Cl(), Op_Dift_VDF_Elem_base::modifier_pour_Cl(), and Op_Dift_VDF_Face_base::modifier_pour_Cl().
type_cl()
Type_Cl_VDF Iterateur_VDF_base::type_cl (const Cond_lim & la_cl) const inline
References TRUST_Deriv< _CLASSE_ >::valeur().
is_convective_op()
const bool & Iterateur_VDF_base::is_convective_op () const inline
References is_conv_op_.
is_pb_multiphase()
const bool & Iterateur_VDF_base::is_pb_multiphase () const inline
References is_pb_multi.
set_name_champ_inco()
void Iterateur_VDF_base::set_name_champ_inco (const std::string & nom) inline
References nom_ch_inco_.
Referenced by Op_Conv_VDF_base::associer_champ_convecte_elem(), Op_Conv_VDF_base::associer_champ_convecte_face(), Op_Diff_K_Eps_Bas_Re_VDF_base::completer(), Op_Diff_K_Eps_VDF_base::completer(), Op_Diff_K_Omega_VDF_base::completer(), Op_Diff_VDF_base::completer(), and Op_Div_VDF_base::completer().
set_incompressible()
void Iterateur_VDF_base::set_incompressible (const int flag) inline
References incompressible_.
Referenced by Op_Conv_VDF_base::set_incompressible().
is_incompressible()
const int & Iterateur_VDF_base::is_incompressible () const inline
References incompressible_.
set_convective_op_pb_type()
void Iterateur_VDF_base::set_convective_op_pb_type (const bool ty_op, const bool ty_pb) inline
References is_conv_op_, and is_pb_multi.
Referenced by Op_Diff_K_Eps_Bas_Re_VDF_base::completer(), Op_Diff_K_Eps_VDF_base::completer(), Op_Diff_K_Omega_VDF_base::completer(), Op_Diff_VDF_base::completer(), Op_Div_VDF_base::completer(), and Op_Conv_VDF_base::preparer_calcul().
set_multiscalar_diff()
void Iterateur_VDF_base::set_multiscalar_diff (bool m) inline
References multiscalar_diff_.
Referenced by Op_Diff_VDF_base::completer().
calculer()
virtual DoubleTab & Iterateur_VDF_base::calculer (const DoubleTab & inco, DoubleTab & resu) const inline final virtual
References ajouter().
Referenced by Op_Diff_K_Eps_Bas_Re_VDF_base::calculer(), Op_Diff_K_Eps_VDF_base::calculer(), Op_Diff_K_Omega_VDF_base::calculer(), Op_Conv_VDF_base::calculer(), and Op_Div_VDF_base::calculer().
ajouter()
virtual DoubleTab & Iterateur_VDF_base::ajouter (const DoubleTab & inco, DoubleTab & secmem) const inline final virtual
References ajouter_blocs(), Objet_U::le_nom(), and op_base.
Referenced by Op_Div_VDF_base::ajouter(), Op_Diff_K_Eps_VDF_base::ajouter_blocs(), Op_Diff_K_Omega_VDF_base::ajouter_blocs(), and calculer().
ajouter_contribution()
virtual void Iterateur_VDF_base::ajouter_contribution (const DoubleTab & inco, Matrice_Morse & m) const inline final virtual
References ajouter_blocs(), Objet_U::le_nom(), and op_base.
Referenced by Op_Diff_K_Eps_VDF_base::ajouter_blocs(), and Op_Diff_K_Omega_VDF_base::ajouter_blocs().
associer_correlation_flux_parietal()
virtual void Iterateur_VDF_base::associer_correlation_flux_parietal (const Correlation_base & corr) inline virtual
Reimplemented in Iterateur_VDF_Elem< _TYPE_ >.
References Process::exit().
Referenced by Op_Diff_VDF_base::completer().
creer_champ_T_paroi_pour_flux_parietal()
virtual void Iterateur_VDF_base::creer_champ_T_paroi_pour_flux_parietal () inline virtual
Reimplemented in Iterateur_VDF_Elem< _TYPE_ >.
References Process::exit().
Referenced by Op_Diff_VDF_base::completer().
Member Data Documentation
info_obj
const Type_info Iterateur_VDF_base::info_obj static
le_dom
TRUST_Ref< Domaine_VDF *> Iterateur_VDF_base::le_dom protected
Referenced by associer(), Iterateur_VDF_Elem< _TYPE_ >::completer_(), and domaine().
la_zcl
TRUST_Ref< Domaine_Cl_VDF *> Iterateur_VDF_base::la_zcl protected
Referenced by associer(), associer_domaine_cl_dis(), domaine_Cl(), and Iterateur_VDF_Elem< _TYPE_ >::milieu().
op_base
TRUST_Ref< Operateur_base *> Iterateur_VDF_base::op_base protected
Referenced by ajouter(), ajouter_contribution(), and associer().
le_champ_convecte_ou_inc
TRUST_Ref< Champ_Inc_base *> Iterateur_VDF_base::le_champ_convecte_ou_inc protected
Referenced by associer_champ_convecte_ou_inc().
le_ch_v
TRUST_Ref< Champ_base *> Iterateur_VDF_base::le_ch_v protected
Referenced by associer_champ_convecte_ou_inc().
nom_ch_inco_
std::string Iterateur_VDF_base::nom_ch_inco_ protected
Referenced by set_name_champ_inco().
is_conv_op_
bool Iterateur_VDF_base::is_conv_op_ = false protected
Referenced by is_convective_op(), and set_convective_op_pb_type().
is_pb_multi
bool Iterateur_VDF_base::is_pb_multi = false protected
Referenced by is_pb_multiphase(), and set_convective_op_pb_type().
use_base_val_b_
bool Iterateur_VDF_base::use_base_val_b_ = false protected
Referenced by associer_champ_convecte_ou_inc().
multiscalar_diff_
bool Iterateur_VDF_base::multiscalar_diff_ = false protected
Referenced by set_multiscalar_diff().
incompressible_
int Iterateur_VDF_base::incompressible_ = 1 protected
Referenced by is_incompressible(), and set_incompressible().