TrioCFD: Postraitement_ft_lata Class Reference
Postraitement_ft_lata Class Reference
#include <Postraitement_ft_lata.h>
Public Member Functions
const Type_info * get_info () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
Public Member Functions inherited from Postraitement
int & compteur_champ_stat ()
const Type_info * get_info () const override
void init () override
virtual int lire_champs_a_postraiter (Entree &is, bool expect_acco)
int lire_motcle_non_standard (const Motcle &, Entree &) override
Postraitement ()
virtual int postraiter_champs ()
int postraiter_sondes ()
int reprendre (Entree &is) override
void resetTime (double t, const std::string dirname) override
int sauvegarder (Sortie &os) const override
int traiter_champs ()
int traiter_sondes ()
virtual int write_extra_mesh ()
Public Member Functions inherited from Postraitement_base
const Type_info * get_info () const override
const Nom & le_nom () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
int reprendre (Entree &is) override
int sauvegarder (Sortie &os) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Postraitement_ft_lata()
Postraitement_ft_lata::Postraitement_ft_lata ()
~Postraitement_ft_lata()
Postraitement_ft_lata::~Postraitement_ft_lata ()
Member Function Documentation
cree_instance()
Objet_U * Postraitement_ft_lata::cree_instance () static
taille_memoire()
unsigned Postraitement_ft_lata::taille_memoire () const override virtual
Reimplemented from Postraitement.
duplique()
int Postraitement_ft_lata::duplique () const override virtual
Reimplemented from Postraitement.
info()
const Type_info * Postraitement_ft_lata::info () static
get_info()
const Type_info * Postraitement_ft_lata::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Postraitement.
self_cast() [1/2]
Postraitement_ft_lata & Postraitement_ft_lata::self_cast (Objet_U & r) static
self_cast() [2/2]
const Postraitement_ft_lata & Postraitement_ft_lata::self_cast (const Objet_U & r) static
printOn()
Sortie & Postraitement_ft_lata::printOn (Sortie & s) const override protected virtual
Imprime le type de l'objet sur un flot de sortie.
Parameters
(Sortie& s) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Postraitement.
readOn()
Entree & Postraitement_ft_lata::readOn (Entree & s) override protected virtual
Lit les directives de postraitement sur un flot d'entree.
Format: Postraitement { Sondes bloc de lecture des sondes | Champs bloc de lecture des champs a postraiter | Statistiques bloc de lecture objet statistique | Fichier }
Parameters
(Entree& s) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Exceptions
accolade ouverte attendue
lecture des champs: mot clef "dt_post" attendu
lecture du bloc statistique: mot clef "dt_post" attendu
mot clef inconnu
Reimplemented from Postraitement.
References Process::exit(), Postraitement::format_post_, Postraitement_base::mon_probleme, Postraitement::readOn(), TRUST_Deriv< _CLASSE_ >::valeur(), and TRUST_Ref< _CLASSE_ >::valeur().
set_param()
void Postraitement_ft_lata::set_param (Param & param) override virtual
Reimplemented from Postraitement.
References Param::ajouter_non_std(), and Postraitement::set_param().
Referenced by Postprocessing_IJK::set_param().
lire_motcle_non_standard()
int Postraitement_ft_lata::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Postraitement.
References Postraitement::format_, lire_champs_interface(), lire_entete_bloc_interface(), Postraitement::lire_motcle_non_standard(), refequation_interfaces, and TRUST_Ref< _CLASSE_ >::reset().
write_extra_mesh()
int Postraitement_ft_lata::write_extra_mesh () override virtual
Override. Add the interfaces to the LATA output.
Reimplemented from Postraitement.
References ecrire_maillage_ft_disc(), TRUST_Ref< _CLASSE_ >::non_nul(), and refequation_interfaces.
postprocess_field_values()
void Postraitement_ft_lata::postprocess_field_values () override virtual
Reimplemented from Postraitement.
References TRUST_Vector< _CLASSE_ >::add(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Postraitement_base::ELEMENTS, Process::exit(), Maillage_FT_Disc::facettes(), filter_out_array(), Transport_Interfaces_FT_Disc::get_champ_post_FT(), id_domaine_, liste_champs_i_aux_elements, liste_champs_i_aux_sommets, Transport_Interfaces_FT_Disc::maillage_interface_pour_post(), Postraitement_base::mon_probleme, TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), no_virtuals_, Domaine_base::nommer(), TRUST_Ref< _CLASSE_ >::non_nul(), Postraitement::postprocess_field_values(), Postraitement::postraiter_tableau(), refequation_interfaces, TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUST_Vector< _CLASSE_ >::size(), Maillage_FT_Disc::sommets(), Postraitement_base::SOMMETS, and TRUST_Ref< _CLASSE_ >::valeur().
lire_champs_interface()
void Postraitement_ft_lata::lire_champs_interface (Entree & is) protected
lecture de la liste de champs aux interfaces a postraiter
References register_interface_field().
Referenced by lire_motcle_non_standard().
lire_entete_bloc_interface()
void Postraitement_ft_lata::lire_entete_bloc_interface (Entree & is) protected virtual
Reimplemented in Postprocessing_IJK.
References Probleme_FT_Disc_gen::equation_interfaces(), Process::exit(), Process::je_suis_maitre(), TRUST_Ref< _CLASSE_ >::le_nom(), Nom::le_nom(), Postraitement_base::mon_probleme, no_virtuals_, TRUST_Ref< _CLASSE_ >::non_nul(), Process::nproc(), refequation_interfaces, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by lire_motcle_non_standard().
register_interface_field()
void Postraitement_ft_lata::register_interface_field (const Motcle & nom_champ, const Motcle & loc_lu) protected virtual
Reimplemented in Postprocessing_IJK.
References TRUST_Vector< _CLASSE_ >::add(), Motcles::contient_(), Postraitement_base::demande_description, Postraitement_base::ELEMENTS, Process::exit(), Transport_Interfaces_FT_Disc::get_champ_post_FT(), liste_champs_i_aux_elements, liste_champs_i_aux_sommets, Objet_U::que_suis_je(), refequation_interfaces, Postraitement_base::SOMMETS, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by lire_champs_interface().
ecrire_maillage_ft_disc()
int Postraitement_ft_lata::ecrire_maillage_ft_disc () protected
Write the Maillage_FT_Disc object into a LATA file in V2 format.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Format_Post_Lata::ecrire_domaine_low_level(), Process::exit(), Maillage_FT_Disc::facettes(), filter_out_virtual_fa7(), Postraitement::format_post_, id_domaine_, no_virtuals_, refequation_interfaces, Maillage_FT_Disc::sommets(), TRUST_Deriv< _CLASSE_ >::valeur(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by write_extra_mesh().
filter_out_virtual_fa7()
int Postraitement_ft_lata::filter_out_virtual_fa7 (IntTab & new_fa7) protected
Build a reduced version of the facettes array, excluding virtual ones Also update the internal renumbering array for later usage when writing out field values.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Maillage_FT_Disc::facette_virtuelle(), Maillage_FT_Disc::facettes(), refequation_interfaces, renum_, and TRUSTTab< _TYPE_, _SIZE_ >::resize().
Referenced by ecrire_maillage_ft_disc().
filter_out_array()
void Postraitement_ft_lata::filter_out_array (const DoubleTab & dtab, DoubleTab & new_dtab) const protected
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), renum_, and TRUSTTab< _TYPE_, _SIZE_ >::resize().
Referenced by postprocess_field_values().
Member Data Documentation
info_obj
const Type_info Postraitement_ft_lata::info_obj static
refequation_interfaces
TRUST_Ref< Transport_Interfaces_FT_Disc *> Postraitement_ft_lata::refequation_interfaces protected
Referenced by ecrire_maillage_ft_disc(), filter_out_virtual_fa7(), lire_entete_bloc_interface(), lire_motcle_non_standard(), postprocess_field_values(), register_interface_field(), and write_extra_mesh().
liste_champs_i_aux_sommets
Motcles Postraitement_ft_lata::liste_champs_i_aux_sommets protected
Referenced by postprocess_field_values(), and register_interface_field().
liste_champs_i_aux_elements
Motcles Postraitement_ft_lata::liste_champs_i_aux_elements protected
Referenced by postprocess_field_values(), and register_interface_field().
id_domaine_
Nom Postraitement_ft_lata::id_domaine_ protected
Referenced by ecrire_maillage_ft_disc(), and postprocess_field_values().
renum_
std::vector<int> Postraitement_ft_lata::renum_ protected
Referenced by filter_out_array(), and filter_out_virtual_fa7().
no_virtuals_
bool Postraitement_ft_lata::no_virtuals_ = false protected
Referenced by ecrire_maillage_ft_disc(), lire_entete_bloc_interface(), and postprocess_field_values().