TrioCFD: Source_Portance_interfaciale_base Class Reference
Source_Portance_interfaciale_base Class Reference abstract
#include <Source_Portance_interfaciale_base.h>
Public Member Functions
void completer () override
const Type_info * get_info () const override
Public Member Functions inherited from Sources_Multiphase_base
const Type_info * get_info () const override
void mettre_a_jour (double temps) override
Public Member Functions inherited from Source_base
virtual int a_pour_Champ_Fonc (const Motcle &mot, TRUST_Ref< Champ_base * > &ch_ref) const
virtual void associer_champ_rho (const Champ_base &champ_rho)
virtual void completer ()
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
virtual void resetTime (double t)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Sources_Multiphase_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
Cette classe implemente un operateur de portance interfaciale
de la forme F_{n_l} = - F_{k} = C_{n_l, k} (u_k - u_n_l) x rot(u_n_l) ou la phase n_l est la phase liquide porteuse et k une phase gazeuse le calcul de C_{n_l, k} est realise par la hierarchie Portance_interfaciale_base
See also
Source_base
Constructor & Destructor Documentation
Source_Portance_interfaciale_base()
Source_Portance_interfaciale_base::Source_Portance_interfaciale_base ()
~Source_Portance_interfaciale_base()
Source_Portance_interfaciale_base::~Source_Portance_interfaciale_base () override
Member Function Documentation
info()
const Type_info * Source_Portance_interfaciale_base::info () static
get_info()
const Type_info * Source_Portance_interfaciale_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Source_base.
Reimplemented in Portance_interfaciale_VDF.
self_cast() [1/2]
Source_Portance_interfaciale_base & Source_Portance_interfaciale_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Source_Portance_interfaciale_base & Source_Portance_interfaciale_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Source_Portance_interfaciale_base::printOn (Sortie & os) const override protected virtual
DOES NOTHING - to override in derived classes.
Imprime la source sur un flot de sortie.
Parameters
(Sortie& os) le flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Source_base.
Reimplemented in Portance_interfaciale_VDF.
readOn()
Entree & Source_Portance_interfaciale_base::readOn (Entree & is) override protected virtual
DOES NOTHING - to override in derived classes.
Lecture d'un terme source sur un flot d'entree.
Parameters
(Entree& is) le flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Source_base.
Reimplemented in Portance_interfaciale_VDF.
References Param::ajouter(), beta_, correlation_, Probleme_base::creer_champ(), Nom::debute_par(), MorEqn::equation(), Process::exit(), g_, Probleme_base::get_correlation(), Probleme_base::has_correlation(), Param::lire_avec_accolades_depuis(), n_l, Pb_Multiphase::nb_phases(), Pb_Multiphase::nom_phase(), Objet_U::que_suis_je(), Pb_Multiphase::resolution_en_T(), and Correlation_base::typer_lire_correlation().
Referenced by Portance_interfaciale_PolyMAC_P0::readOn(), and Portance_interfaciale_VDF::readOn().
dimensionner_blocs()
void Source_Portance_interfaciale_base::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl = {}) const inline override virtual
Reimplemented from Source_base.
ajouter_blocs()
void Source_Portance_interfaciale_base::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = {}) const override pure virtual
Reimplemented from Source_base.
Implemented in Portance_interfaciale_PolyMAC_P0, and Portance_interfaciale_VDF.
correlation()
const Correlation_base & Source_Portance_interfaciale_base::correlation () const inline
References correlation_.
creer_champ()
void Source_Portance_interfaciale_base::creer_champ (const Motcle & motlu) override virtual
Reimplemented from Source_base.
References Champs_compris_T< FIELD_TYPE >::ajoute_champ(), C_lift, Source_base::champs_compris_, Probleme_base::discretisation(), Discretisation_base::discretiser_champ(), Probleme_base::domaine_dis(), MorEqn::equation(), Objet_U_ptr::est_nul(), Pb_Multiphase::nb_phases(), and wobble.
completer()
void Source_Portance_interfaciale_base::completer () override virtual
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees: Source_base::associer_domaines(const Domaine_dis_base& ,const Domaine_Cl_dis_base&) Source_base::associer_pb(const Probleme_base&)
Reimplemented from Source_base.
References MorEqn::equation(), Process::exit(), Source_base::has_champ(), Objet_U_ptr::non_nul(), Objet_U::que_suis_je(), and wobble.
Member Data Documentation
info_obj
const Type_info Source_Portance_interfaciale_base::info_obj static
correlation_
TRUST_Deriv< Correlation_base > Source_Portance_interfaciale_base::correlation_ protected
Referenced by Portance_interfaciale_PolyMAC_P0::ajouter_blocs(), Portance_interfaciale_VDF::ajouter_blocs(), correlation(), Portance_interfaciale_PolyMAC_P0::mettre_a_jour(), and readOn().
n_l
int Source_Portance_interfaciale_base::n_l = -1 protected
Referenced by Portance_interfaciale_PolyMAC_P0::ajouter_blocs(), Portance_interfaciale_VDF::ajouter_blocs(), Portance_interfaciale_PolyMAC_P0::mettre_a_jour(), and readOn().
beta_
double Source_Portance_interfaciale_base::beta_ = 1. protected
Referenced by Portance_interfaciale_PolyMAC_P0::ajouter_blocs(), Portance_interfaciale_VDF::ajouter_blocs(), and readOn().
g_
double Source_Portance_interfaciale_base::g_ = 9.81 protected
Referenced by Portance_interfaciale_PolyMAC_P0::mettre_a_jour(), and readOn().
wobble
TRUST_Deriv< Champ_Fonc_base > Source_Portance_interfaciale_base::wobble protected
Referenced by completer(), creer_champ(), and Portance_interfaciale_PolyMAC_P0::mettre_a_jour().
C_lift
TRUST_Deriv< Champ_Fonc_base > Source_Portance_interfaciale_base::C_lift protected
Referenced by creer_champ(), and Portance_interfaciale_PolyMAC_P0::mettre_a_jour().