TrioCFD: Loi_Fermeture_base Class Reference
Loi_Fermeture_base Class Reference
#include <Loi_Fermeture_base.h>
Public Member Functions
virtual void associer_pb_base (const Probleme_base &)
virtual void completer ()
virtual void discretiser (const Discretisation_base &)
const Champ_base & get_champ (const Motcle &nom) const override
const Type_info * get_info () const override
const Nom & le_nom () const override
virtual void mettre_a_jour (double temps)
void nommer (const Nom &nom) override
virtual void preparer_calcul ()
virtual void set_param (Param &param)
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
Cette classe calcule des champs qui peuvent dependre de plusieurs inconnues, de grandeurs physiques du milieu etc. Les champs de la classe sont rendus accessibles a tout le probleme a travers la methode get_champ() et leur mise a jour est declenchee par le probleme, apres la mise a jour du milieu et des equations.
Member Enumeration Documentation
Status
enum Loi_Fermeture_base::Status protected
Enumerator
INITIAL
PB_ASSOCIE
DISCRETISE
READON_FAIT
COMPLET
Constructor & Destructor Documentation
Loi_Fermeture_base()
Loi_Fermeture_base::Loi_Fermeture_base ()
References INITIAL, and status_.
~Loi_Fermeture_base()
Loi_Fermeture_base::~Loi_Fermeture_base () override
Member Function Documentation
info()
const Type_info * Loi_Fermeture_base::info () static
get_info()
const Type_info * Loi_Fermeture_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
Reimplemented in Loi_Fermeture_Test.
self_cast() [1/2]
Loi_Fermeture_base & Loi_Fermeture_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Loi_Fermeture_base & Loi_Fermeture_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Loi_Fermeture_base::printOn (Sortie & x) const override protected virtual
Pour l'instant, exit()
Reimplemented from Objet_U.
Reimplemented in Loi_Fermeture_Test.
References Process::exit().
Referenced by Loi_Fermeture_Test::printOn().
readOn()
Entree & Loi_Fermeture_base::readOn (Entree & is) override protected virtual
Cette methode appelle la methode set_param() pour initialiser les parametres, puis lit les parametres.
Dans l'implementation des classes derivees on peut se contenter d'appeler la methode de la classe de base et verifier les parametres.
Reimplemented from Objet_U.
Reimplemented in Loi_Fermeture_Test.
References DISCRETISE, Param::lire_avec_accolades_depuis(), Objet_U::que_suis_je(), READON_FAIT, set_param(), and status_.
Referenced by Loi_Fermeture_Test::readOn().
nommer()
void Loi_Fermeture_base::nommer (const Nom &) inline override virtual
Donne un nom a l'Objet_U Methode virtuelle a surcharger.
Parameters
(const Nom&) le nom a affectuer a l'Objet_U
Reimplemented from Objet_U.
le_nom()
const Nom & Loi_Fermeture_base::le_nom () const inline override virtual
Donne le nom de l'Objet_U Methode a surcharger : renvoie "neant" dans cette implementation.
Returns
(Nom&) le nom de l'Objet_U
Reimplemented from Objet_U.
Referenced by associer_pb_base().
creer_champ()
void Loi_Fermeture_base::creer_champ (const Motcle & motlu) inline override virtual
Implements Champs_compris_interface.
get_champ()
const Champ_base & Loi_Fermeture_base::get_champ (const Motcle & nom) const override virtual
Cette methode renvoie le champ de nom "nom" s'il est compris par la classe, sinon appelle la methode get_champ de l'ancetre.
Dans la classe de base, on leve l'exception Champ_compris_erreur.
Implements Champs_compris_interface.
References champs_compris_, and Champs_compris_T< FIELD_TYPE >::get_champ().
has_champ() [1/2]
bool Loi_Fermeture_base::has_champ (const Motcle & nom, TRUST_Ref< Champ_base * > & ref_champ) const override virtual
Implements Champs_compris_interface.
References champs_compris_, and Champs_compris_T< FIELD_TYPE >::has_champ().
has_champ() [2/2]
bool Loi_Fermeture_base::has_champ (const Motcle & nom) const override virtual
Implements Champs_compris_interface.
References champs_compris_, and Champs_compris_T< FIELD_TYPE >::has_champ().
get_noms_champs_postraitables()
void Loi_Fermeture_base::get_noms_champs_postraitables (Noms & nom, Option opt = NONE) const override virtual
Implements Champs_compris_interface.
References TRUST_Vector< _CLASSE_ >::add(), champs_compris_, Champs_compris_T< FIELD_TYPE >::liste_noms_compris(), and Objet_U::que_suis_je().
Referenced by Probleme_base::get_noms_champs_postraitables().
associer_pb_base()
void Loi_Fermeture_base::associer_pb_base (const Probleme_base & pb) virtual
Cette methode est la premiere appelee par le probleme pour construire l'objet au moment ou on l'associe au probleme.
On verifie qu'on est pas encore associe.
References Process::barrier(), Process::exit(), INITIAL, le_nom(), Probleme_U::le_nom(), mon_probleme(), PB_ASSOCIE, Objet_U::que_suis_je(), and status_.
Referenced by Probleme_base::associer_().
discretiser()
void Loi_Fermeture_base::discretiser (const Discretisation_base &) virtual
Cette methode est appelee par le probleme apres la discretisation des equations et du milieu et avant.
l'appel a readOn() pour lecture des parametres. Dans les classes derivees elle doit discretiser au minimum les champs qui seront requis dans le readOn() des equations ou des autres lois de fermeture.
Reimplemented in Loi_Fermeture_Test.
References DISCRETISE, PB_ASSOCIE, and status_.
Referenced by Loi_Fermeture_Test::discretiser(), and Probleme_base::discretiser().
set_param()
void Loi_Fermeture_base::set_param (Param & param) virtual
Cette methode est appelee par le readOn de la classe.
Elle doit etre reimplementee dans les classes derivees pour ajouter dans "param" les differents parametres a lire dans le jeu de donnees et appeler la methode de l'ancetre. Dans la classe de base: aucun parametre.
Reimplemented in Loi_Fermeture_Test.
Referenced by readOn().
completer()
void Loi_Fermeture_base::completer () virtual
Cette methode est appelee apres avoir lu toutes les equations et les lois de fermeture (tous les champs et les conditions aux limites.
du probleme sont disponibles)
References COMPLET, READON_FAIT, and status_.
Referenced by Probleme_base::completer().
preparer_calcul()
void Loi_Fermeture_base::preparer_calcul () virtual
Cette methode est appelee par le probleme apres preparer_calcul() des equations et du milieu.
Elle doit mettre a jour tous les champs qu'elle gere en fonction des autres champs du probleme.
References COMPLET, mettre_a_jour(), mon_probleme(), Probleme_base::schema_temps(), status_, and Schema_Temps_base::temps_courant().
Referenced by Probleme_base::preparer_calcul().
mettre_a_jour()
void Loi_Fermeture_base::mettre_a_jour (double temps) virtual
Cette methode est appelee par le probleme apres mettre_a_jour() des equations et du milieu.
Elle doit mettre a jour tous les champs qu'elle gere en fonction des autres champs du probleme.
Reimplemented in Loi_Fermeture_Test.
References COMPLET, and status_.
Referenced by Probleme_base::mettre_a_jour(), Pb_Dilatable_base::mettre_a_jour(), and preparer_calcul().
mon_probleme()
const Probleme_base & Loi_Fermeture_base::mon_probleme () const protected
Renvoie le probleme (j'ai cree cette methode pour ne pas donner acces au probleme en ecriture par la REF)
References TRUST_Ref< _CLASSE_ >::valeur().
Referenced by associer_pb_base(), Loi_Fermeture_Test::discretiser(), and preparer_calcul().
Member Data Documentation
info_obj
const Type_info Loi_Fermeture_base::info_obj static
champs_compris_
Champs_compris Loi_Fermeture_base::champs_compris_ protected
Referenced by Loi_Fermeture_Test::discretiser(), get_champ(), get_noms_champs_postraitables(), and has_champ().
status_
Status Loi_Fermeture_base::status_ protected
Referenced by associer_pb_base(), completer(), discretiser(), Loi_Fermeture_base(), mettre_a_jour(), Loi_Fermeture_Test::mettre_a_jour(), preparer_calcul(), and readOn().