TrioCFD: Cut_cell_schema_auxiliaire Class Reference
Cut_cell_schema_auxiliaire Class Reference abstract
#include <Cut_cell_schema_auxiliaire.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Cut_cell_schema_auxiliaire()
Cut_cell_schema_auxiliaire::Cut_cell_schema_auxiliaire ()
References tolerate_not_within_tetrahedron_.
~Cut_cell_schema_auxiliaire()
Cut_cell_schema_auxiliaire::~Cut_cell_schema_auxiliaire () override
Member Function Documentation
info()
const Type_info * Cut_cell_schema_auxiliaire::info () static
get_info()
const Type_info * Cut_cell_schema_auxiliaire::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
Cut_cell_schema_auxiliaire & Cut_cell_schema_auxiliaire::self_cast (Objet_U & r) static
self_cast() [2/2]
const Cut_cell_schema_auxiliaire & Cut_cell_schema_auxiliaire::self_cast (const Objet_U & r) static
printOn()
Sortie & Cut_cell_schema_auxiliaire::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
readOn()
Entree & Cut_cell_schema_auxiliaire::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
References Param::lire_avec_accolades(), Objet_U::que_suis_je(), and set_param().
initialise()
void Cut_cell_schema_auxiliaire::initialise (Cut_cell_FT_Disc & cut_cell_disc)
References TRUSTTabFT_cut_cell_scalar< _TYPE_ >::associer_ephemere(), TRUSTTabFT_cut_cell_vector6< _TYPE_ >::associer_ephemere(), flux_naive_, and temperature_remplissage_.
Referenced by IJK_Thermal_cut_cell::initialize().
set_param()
void Cut_cell_schema_auxiliaire::set_param (Param & param)
References Param::ajouter(), Param::dictionnaire(), and methode_valeur_remplissage_.
Referenced by readOn(), Cut_cell_convection_auxiliaire::set_param(), and Cut_cell_diffusion_auxiliaire::set_param().
dying_cells_flux()
virtual double Cut_cell_schema_auxiliaire::dying_cells_flux (int num_face, int phase, int n, const Cut_field_vector3_double & cut_field_total_velocity, const Cut_field_double & cut_field_temperature) pure virtual
Implemented in Cut_cell_convection_auxiliaire, and Cut_cell_diffusion_auxiliaire.
Referenced by compute_flux_dying_cells().
small_nascent_cells_flux()
virtual double Cut_cell_schema_auxiliaire::small_nascent_cells_flux (int num_face, int phase, int n, const Cut_field_vector3_double & cut_field_total_velocity, const Cut_field_double & cut_field_temperature) pure virtual
Implemented in Cut_cell_convection_auxiliaire, and Cut_cell_diffusion_auxiliaire.
Referenced by compute_flux_small_nascent_cells().
compute_flux_dying_cells()
void Cut_cell_schema_auxiliaire::compute_flux_dying_cells (const Cut_field_vector3_double & cut_field_total_velocity, const Cut_field_double & cut_field_temperature)
References IJK_Interfaces::convert_indicatrice_to_phase(), dying_cells_flux(), IJK_Interfaces::est_pure(), flux_naive_, Domaine_IJK::get_constant_delta(), Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::get_cut_cell_disc(), Cut_cell_FT_Disc::get_domaine(), Cut_cell_FT_Disc::get_ijk(), IJK_Interfaces::get_indicatrice_surfacique_efficace_face(), Cut_cell_FT_Disc::get_interfaces(), Cut_cell_FT_Disc::get_n_face(), Cut_cell_FT_Disc::get_n_from_statut_diphasique_index(), Cut_cell_FT_Disc::get_statut_diphasique_value_index(), IJK_Interfaces::I(), IJK_Interfaces::In(), Domaine_IJK::is_uniform(), IJK_Interfaces::phase_mourrante(), IJK_Interfaces::phase_naissante(), and Domaine_IJK::within_ghost().
Referenced by IJK_Thermal_cut_cell::perform_thermal_step().
compute_flux_small_nascent_cells()
void Cut_cell_schema_auxiliaire::compute_flux_small_nascent_cells (const Cut_field_vector3_double & cut_field_total_velocity, Cut_field_double & cut_field_temperature)
References IJK_Interfaces::below_small_threshold(), IJK_Interfaces::convert_indicatrice_to_phase(), IJK_Interfaces::est_pure(), flux_naive_, Domaine_IJK::get_constant_delta(), Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::get_cut_cell_disc(), Cut_cell_FT_Disc::get_domaine(), Cut_cell_FT_Disc::get_ijk(), IJK_Interfaces::get_indicatrice_surfacique_efficace_face(), Cut_cell_FT_Disc::get_interfaces(), Cut_cell_FT_Disc::get_n_face(), Cut_cell_FT_Disc::get_n_from_statut_diphasique_index(), Cut_cell_FT_Disc::get_statut_diphasique_value_index(), IJK_Interfaces::I(), IJK_Interfaces::In(), Domaine_IJK::is_uniform(), IJK_Interfaces::next_below_small_threshold_for_phase(), IJK_Interfaces::phase_mourrante(), IJK_Interfaces::phase_naissante(), small_nascent_cells_flux(), and Domaine_IJK::within_ghost().
Referenced by IJK_Thermal_cut_cell::perform_thermal_step().
calcule_valeur_remplissage()
void Cut_cell_schema_auxiliaire::calcule_valeur_remplissage (double timestep, double lambda_liquid, double lambda_vapour, const IJK_Field_double & flux_interface_ns, const ArrOfDouble & interfacial_temperature, const IJK_Field_double & temperature_ft, const Cut_field_vector3_double & cut_field_total_velocity, const Cut_field_double & cut_field_temperature)
References methode_valeur_remplissage_.
Referenced by IJK_Thermal_cut_cell::perform_thermal_step().
add_dying_cells()
void Cut_cell_schema_auxiliaire::add_dying_cells (const Cut_field_vector3_double & cut_field_total_velocity, Cut_field_double & cut_field_temperature, bool write_flux, Cut_field_vector3_double & cut_field_current_fluxes)
References Cut_cell_correction_petites_cellules::calcul_somme_flux(), IJK_Interfaces::convert_indicatrice_to_phase(), correction_petites_cellules_, Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::diph_l_, Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::diph_v_, Cut_field_vector< T, N >::echange_espace_virtuel(), IJK_Interfaces::est_pure(), flux_naive_, Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::get_cut_cell_disc(), Cut_cell_FT_Disc::get_domaine(), Cut_cell_FT_Disc::get_ijk(), Cut_cell_FT_Disc::get_interfaces(), Cut_cell_FT_Disc::get_n(), Cut_cell_FT_Disc::get_n_from_statut_diphasique_index(), Cut_cell_FT_Disc::get_statut_diphasique_value_index(), IJK_Interfaces::I(), IJK_Interfaces::In(), IJK_Interfaces::In_nonzero(), Domaine_IJK::is_uniform(), Cut_cell_correction_petites_cellules::modification_flux_petites_cellules(), Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::pure_(), and Domaine_IJK::within_ghost().
Referenced by IJK_Thermal_cut_cell::perform_thermal_step().
add_small_nascent_cells()
void Cut_cell_schema_auxiliaire::add_small_nascent_cells (const Cut_field_vector3_double & cut_field_total_velocity, Cut_field_double & cut_field_temperature, bool write_flux, Cut_field_vector3_double & cut_field_current_fluxes)
References IJK_Interfaces::below_small_threshold(), Cut_cell_correction_petites_cellules::calcul_somme_flux(), IJK_Interfaces::convert_indicatrice_to_phase(), correction_petites_cellules_, Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::diph_l_, Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::diph_v_, Cut_field_vector< T, N >::echange_espace_virtuel(), IJK_Interfaces::est_pure(), flux_naive_, Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::get_cut_cell_disc(), Cut_cell_FT_Disc::get_domaine(), Cut_cell_FT_Disc::get_ijk(), IJK_Interfaces::get_indicatrice_surfacique_efficace_face(), Cut_cell_FT_Disc::get_interfaces(), Cut_cell_FT_Disc::get_n(), Cut_cell_FT_Disc::get_n_face(), Cut_cell_FT_Disc::get_n_from_statut_diphasique_index(), Cut_cell_FT_Disc::get_statut_diphasique_value_index(), IJK_Interfaces::I(), IJK_Interfaces::In(), Domaine_IJK::is_uniform(), Cut_cell_correction_petites_cellules::limitation_flux_avec_flux_max(), Cut_cell_correction_petites_cellules::modification_flux_petites_cellules(), IJK_Interfaces::next_below_small_threshold_for_phase(), no_static_update_, IJK_Interfaces::phase_mourrante(), IJK_Interfaces::phase_naissante(), Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::pure_(), temperature_remplissage_, and Domaine_IJK::within_ghost().
Referenced by IJK_Thermal_cut_cell::perform_thermal_step().
calcule_valeur_remplissage_copie_directe()
void Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_copie_directe (const Cut_field_double & cut_field_temperature, DoubleTabFT_cut_cell_scalar & valeur_remplissage) protected
References IJK_Interfaces::below_small_threshold(), IJK_Interfaces::convert_indicatrice_to_phase(), Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::diph_l_, Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::diph_v_, IJK_Interfaces::est_pure(), Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::get_cut_cell_disc(), Cut_cell_FT_Disc::get_domaine(), Cut_cell_FT_Disc::get_ijk(), Cut_cell_FT_Disc::get_interfaces(), Cut_cell_FT_Disc::get_n_from_statut_diphasique_index(), Cut_cell_FT_Disc::get_statut_diphasique_value_index(), IJK_Interfaces::I(), IJK_Interfaces::In(), and Domaine_IJK::within_ghost().
calcule_valeur_remplissage_ponderation_voisin()
void Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_ponderation_voisin (bool est_directionnel, const Cut_field_vector3_double & cut_field_total_velocity, const Cut_field_double & cut_field_temperature, DoubleTabFT_cut_cell_scalar & valeur_remplissage) protected
References IJK_Interfaces::below_small_threshold(), IJK_Interfaces::convert_indicatrice_to_phase(), Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::diph_l_, Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::diph_v_, IJK_Interfaces::est_pure(), Domaine_IJK::get_constant_delta(), Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::get_cut_cell_disc(), Cut_cell_FT_Disc::get_domaine(), Cut_cell_FT_Disc::get_ijk(), IJK_Interfaces::get_indicatrice_surfacique_efficace_face(), Cut_cell_FT_Disc::get_interfaces(), Cut_cell_FT_Disc::get_n(), Cut_cell_FT_Disc::get_n_face(), Cut_cell_FT_Disc::get_n_from_statut_diphasique_index(), Cut_cell_FT_Disc::get_statut_diphasique_value_index(), IJK_Interfaces::I(), IJK_Interfaces::In(), Domaine_IJK::is_uniform(), IJK_Interfaces::next_below_small_threshold_for_phase(), Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::pure_(), and Domaine_IJK::within_ghost().
calcule_valeur_remplissage_semi_lagrangien()
void Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_semi_lagrangien (double timestep, double lambda_liquid, double lambda_vapour, const IJK_Field_double & flux_interface_ns, const Cut_field_double & cut_field_temperature, DoubleTabFT_cut_cell_scalar & valeur_remplissage) protected
References IJK_Interfaces::below_small_threshold(), IJK_Interfaces::convert_indicatrice_to_phase(), Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::diph_l_, Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::diph_v_, IJK_Interfaces::est_pure(), IJK_Interfaces::get_barycentre(), Domaine_IJK::get_constant_delta(), Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::get_cut_cell_disc(), Cut_cell_FT_Disc::get_domaine(), Cut_cell_FT_Disc::get_ijk(), Cut_cell_FT_Disc::get_interfaces(), Cut_cell_FT_Disc::get_n(), Cut_cell_FT_Disc::get_n_from_statut_diphasique_index(), IJK_Interfaces::get_normale_deplacement_interface(), Cut_cell_FT_Disc::get_statut_diphasique_value_index(), IJK_Interfaces::get_surface_interface_old(), IJK_Interfaces::get_vitesse_deplacement_interface(), IJK_Interfaces::I(), IJK_Interfaces::In(), Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::pure_(), and Domaine_IJK::within_ghost().
calcule_valeur_remplissage_semi_lagrangien_interpolate()
void Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_semi_lagrangien_interpolate (double timestep, const ArrOfDouble & interfacial_temperature, const IJK_Field_double & temperature_ft, const Cut_field_double & cut_field_temperature, DoubleTabFT_cut_cell_scalar & valeur_remplissage) protected
References IJK_Interfaces::below_small_threshold(), IJK_Interfaces::convert_indicatrice_to_phase(), IJK_Interfaces::est_pure(), Process::exit(), IJK_Interfaces::get_barycentre(), Domaine_IJK::get_constant_delta(), Domaine_IJK::get_coord_of_dof_along_dir(), Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::get_cut_cell_disc(), Cut_cell_FT_Disc::get_domaine(), Cut_cell_FT_Disc::get_ijk(), Cut_cell_FT_Disc::get_interfaces(), Cut_cell_FT_Disc::get_n_from_statut_diphasique_index(), Cut_cell_FT_Disc::get_statut_diphasique_value_index(), IJK_Interfaces::get_vitesse_deplacement_interface(), IJK_Interfaces::I(), IJK_Interfaces::In(), Domaine_IJK::NODES, tolerate_not_within_tetrahedron_, and Domaine_IJK::within_ghost().
Member Data Documentation
info_obj
const Type_info Cut_cell_schema_auxiliaire::info_obj static
correction_petites_cellules_
CORRECTION_PETITES_CELLULES Cut_cell_schema_auxiliaire::correction_petites_cellules_ protected
Referenced by add_dying_cells(), and add_small_nascent_cells().
flux_naive_
DoubleTabFT_cut_cell_vector6 Cut_cell_schema_auxiliaire::flux_naive_ protected
Referenced by add_dying_cells(), add_small_nascent_cells(), compute_flux_dying_cells(), compute_flux_small_nascent_cells(), and initialise().
temperature_remplissage_
DoubleTabFT_cut_cell_scalar Cut_cell_schema_auxiliaire::temperature_remplissage_ protected
Referenced by add_small_nascent_cells(), and initialise().
methode_valeur_remplissage_
METHODE_TEMPERATURE_REMPLISSAGE Cut_cell_schema_auxiliaire::methode_valeur_remplissage_ protected
Referenced by calcule_valeur_remplissage(), Cut_cell_convection_auxiliaire::Cut_cell_convection_auxiliaire(), Cut_cell_diffusion_auxiliaire::Cut_cell_diffusion_auxiliaire(), and set_param().
no_static_update_
bool Cut_cell_schema_auxiliaire::no_static_update_ protected
Referenced by add_small_nascent_cells().
tolerate_not_within_tetrahedron_
int Cut_cell_schema_auxiliaire::tolerate_not_within_tetrahedron_ protected
Referenced by calcule_valeur_remplissage_semi_lagrangien_interpolate(), and Cut_cell_schema_auxiliaire().