TrioCFD: Pb_Fluide_base Class Reference
Pb_Fluide_base Class Reference
#include <Pb_Fluide_base.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Probleme_base
void abortTimeStep () override
int associer_ (Objet_U &) override
virtual void associer_domaine (const Domaine &)
virtual void associer_milieu_base (const Milieu_base &)
virtual void associer_sch_tps_base (const Schema_Temps_base &)
virtual double calculer_pas_de_temps () const
virtual void completer ()
double computeTimeStep (bool &stop) const override
const Discretisation_base & discretisation () const
virtual void discretiser (Discretisation_base &)
Domaine & domaine ()
const Domaine & domaine () const
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
Equation_base & equation (const Nom &)
const Equation_base & equation (const Nom &) const
TRUST_Ref< Field_base * > findInputField (const Nom &name) const override
virtual void finir ()
double futureTime () const override
const Type_info * get_info () const override
void getInputFieldsNames (Noms &noms) const override
void getOutputFieldsNames (Noms &noms) const override
virtual void imprimer (Sortie &os) const
void initialize () override
bool initTimeStep (double dt) override
bool isStationary () const override
bool iterateTimeStep (bool &converged) override
int limpr () const override
int lsauv () const override
virtual void mettre_a_jour (double temps)
virtual Milieu_base & milieu ()
virtual const Milieu_base & milieu () const
int postraiter (int force=1) override
double presentTime () const override
int reprendre (Entree &) override
void resetTime (double time) override
int sauvegarder (Sortie &) const override
Schema_Temps_base & schema_temps ()
const Schema_Temps_base & schema_temps () const
void terminate () override
bool updateGivenFields () override
void validateTimeStep () override
virtual int verifier ()
Public Member Functions inherited from Probleme_U
virtual void abortTimeStep ()
virtual double computeTimeStep (bool &stop) const
virtual TRUST_Ref< Field_base * > findInputField (const Nom &name) const
virtual double futureTime () const
const Type_info * get_info () const override
virtual void getInputFieldsNames (Noms &noms) const
virtual void getOutputFieldsNames (Noms &noms) const
virtual void initialize ()
virtual bool initTimeStep (double dt)
virtual bool isStationary () const
virtual bool iterateTimeStep (bool &converged)
const Nom & le_nom () const override
void nommer (const Nom &name) override
virtual int postraiter (int force=1)
virtual double presentTime () const
virtual void resetTime (double time)
virtual bool run ()
virtual bool runUntil (double time)
virtual void terminate ()
virtual bool updateGivenFields ()
virtual void validateTimeStep ()
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
la hierarchie des problemes portant une equation de Navier_Stokes
See also
Probleme_base
Constructor & Destructor Documentation
Pb_Fluide_base()
Pb_Fluide_base::Pb_Fluide_base ()
~Pb_Fluide_base()
Pb_Fluide_base::~Pb_Fluide_base () override
Member Function Documentation
info()
const Type_info * Pb_Fluide_base::info () static
get_info()
const Type_info * Pb_Fluide_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Probleme_base.
Reimplemented in Pb_Hydraulique_ALE, Pb_Hydraulique_Turbulent_ALE, Probleme_FT_Disc_gen, Probleme_FTD_IJK, Probleme_FTD_IJK_base, Probleme_FTD_IJK_cut_cell, Pb_Phase_field, Pb_Hydraulique_Aposteriori, Pb_Rayo_Hydraulique, Pb_Rayo_Thermohydraulique, Pb_Rayo_Thermohydraulique_QC, Pb_Rayo_Hydraulique_Turbulent, Pb_Rayo_Thermohydraulique_Turbulent, Pb_Rayo_Thermohydraulique_Turbulent_QC, Pb_Hydraulique_sensibility, Pb_Thermohydraulique_sensibility, Pb_Hydraulique, Pb_Hydraulique_Concentration, Pb_Thermohydraulique, Pb_Thermohydraulique_Concentration, Pb_Thermohydraulique_Cloned_Concentration, Pb_Hydraulique_Cloned_Concentration, Pb_Thermohydraulique_List_Concentration, Pb_Hydraulique_List_Concentration, Pb_Thermohydraulique_Concentration_Scalaires_Passifs, Pb_Hydraulique_Concentration_Scalaires_Passifs, Pb_Thermohydraulique_Scalaires_Passifs, Pb_Multiphase, Pb_Multiphase_Enthalpie, Pb_Multiphase_HEM, Pb_Hydraulique_Concentration_Turbulent, Pb_Hydraulique_Melange_Binaire_Turbulent_QC, Pb_Hydraulique_Turbulent, Pb_Thermohydraulique_Concentration_Turbulent, Pb_Thermohydraulique_Turbulent, Pb_Thermohydraulique_Turbulent_QC, Pb_Thermohydraulique_Cloned_Concentration_Turbulent, Pb_Hydraulique_Cloned_Concentration_Turbulent, Pb_Thermohydraulique_List_Concentration_Turbulent, Pb_Hydraulique_List_Concentration_Turbulent, Pb_Thermohydraulique_Turbulent_Scalaires_Passifs, Pb_Thermohydraulique_Especes_Turbulent_QC, Pb_Hydraulique_Concentration_Turbulent_Scalaires_Passifs, and Pb_Thermohydraulique_Concentration_Turbulent_Scalaires_Passifs.
self_cast() [1/2]
Pb_Fluide_base & Pb_Fluide_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Pb_Fluide_base & Pb_Fluide_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Pb_Fluide_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Probleme_base.
Reimplemented in TRUSTProblem_sup_eqns< Pb_Hydraulique_Concentration >, TRUSTProblem_sup_eqns< Pb_Hydraulique_Concentration_Turbulent >, TRUSTProblem_sup_eqns< Pb_Thermohydraulique_Concentration >, TRUSTProblem_sup_eqns< Pb_Thermohydraulique_Concentration_Turbulent >, TRUSTProblem_sup_eqns< Pb_Thermohydraulique_QC >, TRUSTProblem_sup_eqns< Pb_Thermohydraulique_Turbulent_QC >, TRUSTProblem_sup_eqns< Pb_Thermohydraulique_WC >, TRUSTProblem_sup_eqns< Pb_Thermohydraulique >, TRUSTProblem_sup_eqns< Pb_Thermohydraulique_Turbulent >, TRUSTProblem_Concentration_Gen< Pb_Hydraulique, Convection_Diffusion_Concentration, Constituant >, TRUSTProblem_Concentration_Gen< Pb_Hydraulique_Turbulent, Convection_Diffusion_Concentration_Turbulent, Constituant >, TRUSTProblem_Concentration_Gen< Pb_Thermohydraulique, Convection_Diffusion_Concentration, Constituant >, TRUSTProblem_Concentration_Gen< Pb_Thermohydraulique_Turbulent, Convection_Diffusion_Concentration_Turbulent, Constituant >, Pb_Hydraulique_ALE, Pb_Hydraulique_Turbulent_ALE, Probleme_FT_Disc_gen, Probleme_FTD_IJK, Probleme_FTD_IJK_base, Probleme_FTD_IJK_cut_cell, Pb_Phase_field, Pb_Hydraulique_Aposteriori, Pb_Rayo_Hydraulique, Pb_Rayo_Thermohydraulique, Pb_Rayo_Thermohydraulique_QC, Pb_Rayo_Hydraulique_Turbulent, Pb_Rayo_Thermohydraulique_Turbulent, Pb_Rayo_Thermohydraulique_Turbulent_QC, Pb_Hydraulique_sensibility, Pb_Thermohydraulique_sensibility, Pb_Hydraulique, Pb_Hydraulique_Concentration, Pb_Thermohydraulique, Pb_Thermohydraulique_Concentration, Pb_Thermohydraulique_Cloned_Concentration, Pb_Hydraulique_Cloned_Concentration, Pb_Thermohydraulique_List_Concentration, Pb_Hydraulique_List_Concentration, Pb_Thermohydraulique_Concentration_Scalaires_Passifs, Pb_Hydraulique_Concentration_Scalaires_Passifs, Pb_Thermohydraulique_Scalaires_Passifs, Pb_Multiphase, Pb_Multiphase_Enthalpie, Pb_Multiphase_HEM, Pb_Hydraulique_Concentration_Turbulent, Pb_Hydraulique_Melange_Binaire_Turbulent_QC, Pb_Hydraulique_Turbulent, Pb_Thermohydraulique_Concentration_Turbulent, Pb_Thermohydraulique_Turbulent, Pb_Thermohydraulique_Turbulent_QC, Pb_Thermohydraulique_Cloned_Concentration_Turbulent, Pb_Hydraulique_Cloned_Concentration_Turbulent, Pb_Thermohydraulique_List_Concentration_Turbulent, Pb_Hydraulique_List_Concentration_Turbulent, Pb_Thermohydraulique_Turbulent_Scalaires_Passifs, Pb_Thermohydraulique_Especes_Turbulent_QC, Pb_Hydraulique_Concentration_Turbulent_Scalaires_Passifs, and Pb_Thermohydraulique_Concentration_Turbulent_Scalaires_Passifs.
References Probleme_base::printOn().
Referenced by Pb_Hydraulique_ALE::printOn(), Pb_Phase_field::printOn(), Pb_Hydraulique_Aposteriori::printOn(), Pb_Hydraulique_sensibility::printOn(), Pb_Thermohydraulique_sensibility::printOn(), Pb_Dilatable_base::printOn(), Pb_Hydraulique_IBM::printOn(), Pb_Hydraulique_IBM_Turbulent::printOn(), Pb_Thermohydraulique_IBM_Turbulent::printOn(), Pb_Hydraulique::printOn(), Pb_Hydraulique_Concentration::printOn(), Pb_Multiphase::printOn(), Pb_Hydraulique_Concentration_Turbulent::printOn(), Pb_Hydraulique_Turbulent::printOn(), Pb_Thermohydraulique_Concentration_Turbulent::printOn(), and Pb_Thermohydraulique_Turbulent::printOn().
readOn()
Entree & Pb_Fluide_base::readOn (Entree & is) override protected virtual
Lecture d'un probleme dans un flot d'entree, et ouverture du flot de sauvegarde.
Format: { nom_milieu bloc de lecture d'un milieu nom_equation bloc de lecture d'une equation Postraitement bloc de lecture postraitement reprise | sauvegarde | sauvegarde_simple formatte | binaire | pdi nom_de_fichier } L'option sauvegarde_simple permet de sauver le probleme dans le fichier choisi en ecrasant a chaque fois les sauvegardes precedentes : cela permet d'economiser de la place disque.
Parameters
(Entree& is) flot d'entree
Returns
(Entree&) le flot d'entre modifie
Exceptions
pas d'accolade ouvrante en debut de format
mot clef "Postraitement" n'est pas la
format de sauvegarde doit etre "binaire" ou "formatte"
pas d'accolade fermante en fin de jeu de donnee
Reimplemented from Probleme_base.
Reimplemented in Pb_Hydraulique_ALE, Pb_Hydraulique_Turbulent_ALE, Probleme_FT_Disc_gen, Probleme_FTD_IJK, Probleme_FTD_IJK_base, Probleme_FTD_IJK_cut_cell, Pb_Phase_field, Pb_Hydraulique_Aposteriori, Pb_Rayo_Hydraulique, Pb_Rayo_Thermohydraulique, Pb_Rayo_Thermohydraulique_QC, Pb_Rayo_Hydraulique_Turbulent, Pb_Rayo_Thermohydraulique_Turbulent, Pb_Rayo_Thermohydraulique_Turbulent_QC, Pb_Hydraulique_sensibility, Pb_Thermohydraulique_sensibility, Pb_Hydraulique, Pb_Hydraulique_Concentration, Pb_Thermohydraulique, Pb_Thermohydraulique_Concentration, Pb_Thermohydraulique_Cloned_Concentration, Pb_Hydraulique_Cloned_Concentration, Pb_Thermohydraulique_List_Concentration, Pb_Hydraulique_List_Concentration, Pb_Thermohydraulique_Concentration_Scalaires_Passifs, Pb_Hydraulique_Concentration_Scalaires_Passifs, Pb_Thermohydraulique_Scalaires_Passifs, Pb_Multiphase, Pb_Multiphase_Enthalpie, Pb_Multiphase_HEM, Pb_Hydraulique_Concentration_Turbulent, Pb_Hydraulique_Melange_Binaire_Turbulent_QC, Pb_Hydraulique_Turbulent, Pb_Thermohydraulique_Concentration_Turbulent, Pb_Thermohydraulique_Turbulent, Pb_Thermohydraulique_Turbulent_QC, Pb_Thermohydraulique_Cloned_Concentration_Turbulent, Pb_Hydraulique_Cloned_Concentration_Turbulent, Pb_Thermohydraulique_List_Concentration_Turbulent, Pb_Hydraulique_List_Concentration_Turbulent, Pb_Thermohydraulique_Turbulent_Scalaires_Passifs, Pb_Thermohydraulique_Especes_Turbulent_QC, Pb_Hydraulique_Concentration_Turbulent_Scalaires_Passifs, Pb_Thermohydraulique_Concentration_Turbulent_Scalaires_Passifs, TRUSTProblem_sup_eqns< Pb_Hydraulique_Concentration >, TRUSTProblem_sup_eqns< Pb_Hydraulique_Concentration_Turbulent >, TRUSTProblem_sup_eqns< Pb_Thermohydraulique_Concentration >, TRUSTProblem_sup_eqns< Pb_Thermohydraulique_Concentration_Turbulent >, TRUSTProblem_sup_eqns< Pb_Thermohydraulique_QC >, TRUSTProblem_sup_eqns< Pb_Thermohydraulique_Turbulent_QC >, TRUSTProblem_sup_eqns< Pb_Thermohydraulique_WC >, TRUSTProblem_sup_eqns< Pb_Thermohydraulique >, TRUSTProblem_sup_eqns< Pb_Thermohydraulique_Turbulent >, TRUSTProblem_Cloned_Concentration_Gen< Pb_Hydraulique >, TRUSTProblem_Cloned_Concentration_Gen< Pb_Hydraulique_Turbulent, Convection_Diffusion_Concentration_Turbulent, Constituant >, TRUSTProblem_Cloned_Concentration_Gen< Pb_Thermohydraulique >, TRUSTProblem_Cloned_Concentration_Gen< Pb_Thermohydraulique_Turbulent, Convection_Diffusion_Concentration_Turbulent, Constituant >, TRUSTProblem_List_Concentration_Gen< Pb_Hydraulique >, TRUSTProblem_List_Concentration_Gen< Pb_Hydraulique_Turbulent, Convection_Diffusion_Concentration_Turbulent, Constituant >, TRUSTProblem_List_Concentration_Gen< Pb_Thermohydraulique >, and TRUSTProblem_List_Concentration_Gen< Pb_Thermohydraulique_Turbulent, Convection_Diffusion_Concentration_Turbulent, Constituant >.
References Probleme_base::readOn().
Referenced by Pb_Hydraulique_ALE::readOn(), Probleme_FT_Disc_gen::readOn(), Pb_Phase_field::readOn(), Pb_Hydraulique_Aposteriori::readOn(), Pb_Hydraulique_sensibility::readOn(), Pb_Thermohydraulique_sensibility::readOn(), Pb_Dilatable_base::readOn(), Pb_Hydraulique_IBM::readOn(), Pb_Hydraulique_IBM_Turbulent::readOn(), Pb_Thermohydraulique_IBM_Turbulent::readOn(), Pb_Hydraulique::readOn(), Pb_Hydraulique_Concentration::readOn(), Pb_Multiphase::readOn(), Pb_Hydraulique_Concentration_Turbulent::readOn(), Pb_Hydraulique_Turbulent::readOn(), Pb_Thermohydraulique_Concentration_Turbulent::readOn(), and Pb_Thermohydraulique_Turbulent::readOn().
expression_predefini()
int Pb_Fluide_base::expression_predefini (const Motcle & motlu, Nom & expression) override virtual
Reimplemented from Probleme_base.
Reimplemented in Pb_Hydraulique_Melange_Binaire_Turbulent_QC, and Pb_Thermohydraulique_Turbulent_QC.
References Probleme_base::expression_predefini(), and Probleme_U::le_nom().
Referenced by Pb_Hydraulique_Melange_Binaire_Turbulent_QC::expression_predefini(), and Pb_Thermohydraulique_Turbulent_QC::expression_predefini().
Member Data Documentation
info_obj
const Type_info Pb_Fluide_base::info_obj static