TrioCFD: Perte_Charge_Singuliere_PolyMAC_P0P1NC_Face Class Reference
Perte_Charge_Singuliere_PolyMAC_P0P1NC_Face Class Reference
#include <Perte_Charge_Singuliere_PolyMAC_P0P1NC_Face.h>
Public Member Functions
void completer () override
const Type_info * get_info () const override
Public Member Functions inherited from Perte_Charge_Singuliere_PolyMAC_Face
const Type_info * get_info () const override
void mettre_a_jour (double temps) override
const Type_info * get_info () const override
void mettre_a_jour (double) override
Public Member Functions inherited from Source_base
virtual int a_pour_Champ_Fonc (const Motcle &mot, TRUST_Ref< Champ_base * > &ch_ref) const
virtual void associer_champ_rho (const Champ_base &champ_rho)
virtual void completer ()
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
virtual void resetTime (double t)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Terme_Source_Qdm
const Champ_Don_base & source () const
Public Member Functions inherited from Perte_Charge_Singuliere
double K () const
Entree & lire_donnees (Entree &)
Public Member Functions inherited from Perte_Charge
int direction_perte_charge () const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
See also
Perte_Charge_PolyMAC_Face
Constructor & Destructor Documentation
Perte_Charge_Singuliere_PolyMAC_P0P1NC_Face()
Perte_Charge_Singuliere_PolyMAC_P0P1NC_Face::Perte_Charge_Singuliere_PolyMAC_P0P1NC_Face ()
~Perte_Charge_Singuliere_PolyMAC_P0P1NC_Face()
Perte_Charge_Singuliere_PolyMAC_P0P1NC_Face::~Perte_Charge_Singuliere_PolyMAC_P0P1NC_Face ()
Member Function Documentation
cree_instance()
Objet_U * Perte_Charge_Singuliere_PolyMAC_P0P1NC_Face::cree_instance () static
taille_memoire()
unsigned Perte_Charge_Singuliere_PolyMAC_P0P1NC_Face::taille_memoire () const override virtual
Reimplemented from Perte_Charge_Singuliere_PolyMAC_Face.
duplique()
int Perte_Charge_Singuliere_PolyMAC_P0P1NC_Face::duplique () const override virtual
Reimplemented from Perte_Charge_Singuliere_PolyMAC_Face.
info()
const Type_info * Perte_Charge_Singuliere_PolyMAC_P0P1NC_Face::info () static
get_info()
const Type_info * Perte_Charge_Singuliere_PolyMAC_P0P1NC_Face::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Perte_Charge_Singuliere_PolyMAC_Face.
self_cast() [1/2]
Perte_Charge_Singuliere_PolyMAC_P0P1NC_Face & Perte_Charge_Singuliere_PolyMAC_P0P1NC_Face::self_cast (Objet_U & r) static
self_cast() [2/2]
const Perte_Charge_Singuliere_PolyMAC_P0P1NC_Face & Perte_Charge_Singuliere_PolyMAC_P0P1NC_Face::self_cast (const Objet_U & r) static
printOn()
Sortie & Perte_Charge_Singuliere_PolyMAC_P0P1NC_Face::printOn (Sortie & os) const override protected virtual
DOES NOTHING - to override in derived classes.
Imprime la source sur un flot de sortie.
Parameters
(Sortie& os) le flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Perte_Charge_Singuliere_PolyMAC_Face.
References Objet_U::que_suis_je().
readOn()
Entree & Perte_Charge_Singuliere_PolyMAC_P0P1NC_Face::readOn (Entree & is) override protected virtual
DOES NOTHING - to override in derived classes.
Lecture d'un terme source sur un flot d'entree.
Parameters
(Entree& is) le flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Perte_Charge_Singuliere_PolyMAC_Face.
References Perte_Charge_Singuliere_PolyMAC_Face::readOn().
has_interface_blocs()
int Perte_Charge_Singuliere_PolyMAC_P0P1NC_Face::has_interface_blocs () const inline override virtual
Reimplemented from Source_base.
completer()
void Perte_Charge_Singuliere_PolyMAC_P0P1NC_Face::completer () override virtual
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees: Source_base::associer_domaines(const Domaine_dis_base& ,const Domaine_Cl_dis_base&) Source_base::associer_pb(const Probleme_base&)
Reimplemented from Source_base.
References Source_base::completer(), and MorEqn::mon_equation.
check_multiphase_compatibility()
void Perte_Charge_Singuliere_PolyMAC_P0P1NC_Face::check_multiphase_compatibility () const inline override virtual
Reimplemented from MorEqn.
dimensionner_blocs()
void Perte_Charge_Singuliere_PolyMAC_P0P1NC_Face::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl = {}) const override virtual
Reimplemented from Source_base.
References Matrix_tools::allocate_morse_matrix(), TRUSTTab< _TYPE_, _SIZE_ >::append_line(), Objet_U::dimension, MorEqn::equation(), Nom::getString(), Equation_base::inconnue(), Field_base::le_nom(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Matrice_Morse::nb_colonnes(), Perte_Charge_PolyMAC_Face::num_faces, TRUSTVect< _TYPE_, _SIZE_ >::size(), and Champ_Inc_base::valeurs().
ajouter_blocs()
void Perte_Charge_Singuliere_PolyMAC_P0P1NC_Face::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = {}) const override virtual
Reimplemented from Source_base.
References Equation_base::champ_conserve(), Objet_U::dimension, Perte_Charge::direction_perte_charge(), MorEqn::equation(), Pb_Multiphase::equation_masse(), Nom::getString(), Equation_base::inconnue(), Perte_Charge_Singuliere::K(), Perte_Charge_PolyMAC_Face::la_vitesse, Field_base::le_nom(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Equation_base::milieu(), Perte_Charge_PolyMAC_Face::num_faces, Champ_Inc_base::passe(), Milieu_base::porosite_face(), TRUSTVect< _TYPE_, _SIZE_ >::size(), and Champ_Inc_base::valeurs().
Member Data Documentation
info_obj
const Type_info Perte_Charge_Singuliere_PolyMAC_P0P1NC_Face::info_obj static