TrioCFD: Ensemble_Faces_base Class Reference
Ensemble_Faces_base Class Reference
#include <Ensemble_Faces_base.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Ensemble_Faces_base()
Ensemble_Faces_base::Ensemble_Faces_base ()
~Ensemble_Faces_base()
Ensemble_Faces_base::~Ensemble_Faces_base ()
Member Function Documentation
cree_instance()
Objet_U * Ensemble_Faces_base::cree_instance () static
taille_memoire()
unsigned Ensemble_Faces_base::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Ensemble_Faces_base::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Ensemble_Faces_base::info () static
get_info()
const Type_info * Ensemble_Faces_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
Ensemble_Faces_base & Ensemble_Faces_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Ensemble_Faces_base & Ensemble_Faces_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Ensemble_Faces_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
readOn()
Entree & Ensemble_Faces_base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
cond_lim_rayo() [1/2]
const Cond_Lim_Rayo & Ensemble_Faces_base::cond_lim_rayo () const inline
References la_cond_lim_rayo_.
Referenced by surface(), and teta_i().
cond_lim_rayo() [2/2]
Cond_Lim_Rayo & Ensemble_Faces_base::cond_lim_rayo () inline
References la_cond_lim_rayo_.
la_cl_base() [1/2]
const Cond_lim_base & Ensemble_Faces_base::la_cl_base () const inline
References les_cl_base.
Referenced by Face_Rayonnante::calculer_temperature(), and Modele_Rayonnement_Milieu_Transparent::flux_radiatif().
la_cl_base() [2/2]
Cond_lim_base & Ensemble_Faces_base::la_cl_base () inline
References les_cl_base.
associer_les_cl()
void Ensemble_Faces_base::associer_les_cl (Cond_lim_base & la_cl)
References TRUSTList< _TYPE_ >::add(), Faces_32_64< _SIZE_ >::Calculer_centres_gravite(), Domaine_32_64< _SIZE_ >::coord_sommets(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Frontiere_32_64< _SIZE_ >::domaine(), Process::exit(), Frontiere_32_64< _SIZE_ >::faces(), Frontiere_dis_base::frontiere(), Cond_lim_base::frontiere_dis(), la_cond_lim_rayo_, Frontiere_32_64< _SIZE_ >::le_nom(), les_cl_base, Faces_32_64< _SIZE_ >::les_sommets(), Process::mp_sum(), Frontiere_32_64< _SIZE_ >::nb_faces(), nb_faces_bord_, num_face_Ensemble, positions_, TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), TRUSTList< _TYPE_ >::size(), and Faces_32_64< _SIZE_ >::type_face().
Referenced by Pb_Couple_Rayonnement::completer().
surface()
double Ensemble_Faces_base::surface (int numfa) const
References cond_lim_rayo(), and Cond_Lim_Rayo::surface().
Referenced by Face_Rayonnante::calculer_temperature().
teta_i()
double Ensemble_Faces_base::teta_i (int numfa)
References cond_lim_rayo(), and Cond_Lim_Rayo::teta_i().
Referenced by Face_Rayonnante::calculer_temperature().
contient()
int Ensemble_Faces_base::contient (int num_face) const
References num_face_Ensemble, and TRUSTVect< _TYPE_, _SIZE_ >::size().
Referenced by Modele_Rayonnement_Milieu_Transparent::flux_radiatif().
Table_faces()
const IntVect & Ensemble_Faces_base::Table_faces () const inline
References num_face_Ensemble.
Referenced by Face_Rayonnante::calculer_temperature().
lire()
void Ensemble_Faces_base::lire (const Nom & nom_bord_lu, const Nom & nom_bord, const Domaine & dom)
References Entree_Fichier_base::close(), Domaine_base::le_nom(), and positions_.
Referenced by Modele_Rayonnement_Milieu_Transparent::discretiser().
nb_faces_bord()
int Ensemble_Faces_base::nb_faces_bord () const inline
References nb_faces_bord_.
Referenced by Face_Rayonnante::calculer_temperature(), Pb_Couple_Rayonnement::completer(), and Modele_Rayonnement_Milieu_Transparent::flux_radiatif().
is_ok()
int Ensemble_Faces_base::is_ok () const
References les_cl_base, and TRUST_Ref< _CLASSE_ >::non_nul().
Referenced by Pb_Couple_Rayonnement::completer().
Member Data Documentation
info_obj
const Type_info Ensemble_Faces_base::info_obj static
num_face_Ensemble
IntVect Ensemble_Faces_base::num_face_Ensemble protected
Referenced by associer_les_cl(), contient(), and Table_faces().
les_cl_base
TRUST_Ref< Cond_lim_base *> Ensemble_Faces_base::les_cl_base protected
Referenced by associer_les_cl(), is_ok(), and la_cl_base().
la_cond_lim_rayo_
Cond_Lim_Rayo* Ensemble_Faces_base::la_cond_lim_rayo_ protected
Referenced by associer_les_cl(), and cond_lim_rayo().
nb_faces_bord_
int Ensemble_Faces_base::nb_faces_bord_ protected
Referenced by associer_les_cl(), and nb_faces_bord().
positions_
DoubleTab Ensemble_Faces_base::positions_ protected
Referenced by associer_les_cl(), and lire().