TrioCFD: Echange_contact_PolyMAC_P0P1NC Class Reference
Echange_contact_PolyMAC_P0P1NC Class Reference
#include <Echange_contact_PolyMAC_P0P1NC.h>
Public Member Functions
const Type_info * get_info () const override
void mettre_a_jour (double temps) override
void verifie_ch_init_nb_comp () const override
const Type_info * get_info () const override
Public Member Functions inherited from Echange_impose_base
int a_mettre_a_jour_ss_pas_dt () override
void associer_fr_dis_base (const Frontiere_dis_base &) override
double emissivite (int num) const
double emissivite (int num, int k) const
const Type_info * get_info () const override
virtual double h_imp (int num) const
virtual double h_imp (int num, int k) const
int initialiser (double temps) override
void mettre_a_jour (double) override
virtual Champ_front_base & T_ext ()
virtual double T_ext (int num) const
virtual double T_ext (int num, int k) const
Public Member Functions inherited from Cond_lim_base
virtual int a_mettre_a_jour_ss_pas_dt ()
virtual void associer_domaine_cl_dis_base (const Domaine_Cl_dis_base &)
virtual void associer_fr_dis_base (const Frontiere_dis_base &)
virtual void calculer_coeffs_echange (double temps)
virtual int compatible_avec_discr (const Discretisation_base &) const
Domaine_Cl_dis_base & domaine_Cl_dis ()
const Domaine_Cl_dis_base & domaine_Cl_dis () const
virtual Frontiere_dis_base & frontiere_dis ()
virtual const Frontiere_dis_base & frontiere_dis () const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
void set_modifier_val_imp (int)
virtual void verifie_ch_init_nb_comp () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
void verifie_ch_init_nb_comp () const override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Cond_lim_base
void err_pas_compatible (const Discretisation_base &) const
void err_pas_compatible (const Equation_base &) const
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
cette classe possede un autre champ_front avec autant de valeurs temporelles qui represente la temperature dans l'autre probleme.
Constructor & Destructor Documentation
Echange_contact_PolyMAC_P0P1NC()
Echange_contact_PolyMAC_P0P1NC::Echange_contact_PolyMAC_P0P1NC ()
~Echange_contact_PolyMAC_P0P1NC()
Echange_contact_PolyMAC_P0P1NC::~Echange_contact_PolyMAC_P0P1NC ()
Member Function Documentation
cree_instance()
Objet_U * Echange_contact_PolyMAC_P0P1NC::cree_instance () static
taille_memoire()
unsigned Echange_contact_PolyMAC_P0P1NC::taille_memoire () const override virtual
Reimplemented from Echange_externe_impose.
duplique()
int Echange_contact_PolyMAC_P0P1NC::duplique () const override virtual
Reimplemented from Echange_externe_impose.
info()
const Type_info * Echange_contact_PolyMAC_P0P1NC::info () static
get_info()
const Type_info * Echange_contact_PolyMAC_P0P1NC::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Echange_externe_impose.
self_cast() [1/2]
Echange_contact_PolyMAC_P0P1NC & Echange_contact_PolyMAC_P0P1NC::self_cast (Objet_U & r) static
self_cast() [2/2]
const Echange_contact_PolyMAC_P0P1NC & Echange_contact_PolyMAC_P0P1NC::self_cast (const Objet_U & r) static
printOn()
Sortie & Echange_contact_PolyMAC_P0P1NC::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Echange_externe_impose.
References Objet_U::que_suis_je().
readOn()
Entree & Echange_contact_PolyMAC_P0P1NC::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Echange_externe_impose.
References Cond_lim_base::app_domains, Field_base::fixer_nb_comp(), invh_paroi, Cond_lim_base::le_champ_front, nom_autre_pb_, nom_bord_, nom_champ_, Echange_impose_base::T_ext(), and Objet_U_ptr::typer().
Referenced by Echange_contact_PolyMAC_P0::readOn().
init_op()
void Echange_contact_PolyMAC_P0P1NC::init_op () const
References Champ_front_calc::creer(), diff, Cond_lim_base::domaine_Cl_dis(), Equation_base::domaine_dis(), Champ_front_calc::equation(), MorEqn::equation(), Process::exit(), Champ_front_calc::front_dis(), Cond_lim_base::frontiere_dis(), fvf, i_fvf, i_o_fvf, Operateur::l_op_base(), Objet_U::le_nom(), TRUST_Ref< _CLASSE_ >::le_nom(), Probleme_U::le_nom(), Nom::le_nom(), nom_autre_pb_, nom_bord_, nom_champ_, Equation_base::nombre_d_operateurs(), TRUST_Ref< _CLASSE_ >::non_nul(), o_diff, o_fvf, Equation_base::operateur(), Equation_base::probleme(), and Domaine_dis_base::rang_frontiere().
Referenced by Op_Diff_PolyMAC_P0P1NC_Elem::init_op_ext().
mettre_a_jour()
void Echange_contact_PolyMAC_P0P1NC::mettre_a_jour (double temps) inline override virtual
Effectue une mise a jour en temps des conditions aux limites.
Lors du premier appel des initialisations sont effectuees: h_imp(0,0) = (rho(0,0)*Cp(0,0))
Parameters
(double temps) le temp de mise a jour
Reimplemented from Echange_impose_base.
verifie_ch_init_nb_comp()
void Echange_contact_PolyMAC_P0P1NC::verifie_ch_init_nb_comp () const inline override virtual
Appel la verification du champ lu par l intermediaire de l equation pour laquelle on considere la condition limite.
La methode est surchargee dans les cas ou l utilisateur doit specifier le champ frontiere
Reimplemented from Echange_externe_impose.
init_f_dist()
void Echange_contact_PolyMAC_P0P1NC::init_f_dist () const
References TRUSTArray< _TYPE_, _SIZE_ >::addr(), Objet_U::dimension, Process::exit(), f_dist, f_dist_init_, fvf, TRUST_Ref< _CLASSE_ >::le_nom(), o_fvf, and TRUSTTab< _TYPE_, _SIZE_ >::resize().
Referenced by Op_Diff_PolyMAC_P0P1NC_Elem::dimensionner_blocs_ext().
Member Data Documentation
info_obj
const Type_info Echange_contact_PolyMAC_P0P1NC::info_obj static
fvf
TRUST_Ref< Front_VF *> Echange_contact_PolyMAC_P0P1NC::fvf mutable
Referenced by Op_Diff_PolyMAC_P0P1NC_Elem::dimensionner_blocs_ext(), init_f_dist(), Echange_contact_PolyMAC_P0::init_fs_dist(), Echange_contact_PolyMAC_P0::init_op(), and init_op().
o_fvf
TRUST_Ref< Front_VF *> Echange_contact_PolyMAC_P0P1NC::o_fvf
Referenced by init_f_dist(), Echange_contact_PolyMAC_P0::init_fs_dist(), Echange_contact_PolyMAC_P0::init_op(), and init_op().
i_fvf
int Echange_contact_PolyMAC_P0P1NC::i_fvf = -1 mutable
Referenced by Echange_contact_PolyMAC_P0::init_op(), and init_op().
i_o_fvf
int Echange_contact_PolyMAC_P0P1NC::i_o_fvf = -1
Referenced by Echange_contact_PolyMAC_P0::init_op(), and init_op().
diff
TRUST_Ref< Op_Diff_PolyMAC_P0P1NC_Elem *> Echange_contact_PolyMAC_P0P1NC::diff mutable
Referenced by init_op().
o_diff
TRUST_Ref< Op_Diff_PolyMAC_P0P1NC_Elem *> Echange_contact_PolyMAC_P0P1NC::o_diff
Referenced by Op_Diff_PolyMAC_P0P1NC_Elem::dimensionner_blocs_ext(), init_op(), and Op_Diff_PolyMAC_P0P1NC_Elem::init_op_ext().
o_idx
int Echange_contact_PolyMAC_P0P1NC::o_idx = -1 mutable
Referenced by Op_Diff_PolyMAC_P0P1NC_Elem::init_op_ext().
f_dist
IntTab Echange_contact_PolyMAC_P0P1NC::f_dist mutable
Referenced by Op_Diff_PolyMAC_P0P1NC_Elem::dimensionner_blocs_ext(), init_f_dist(), Echange_contact_PolyMAC_P0::init_fs_dist(), and Couplage_Parietal_PolyMAC_helper::init_op_ext().
f_dist_init_
int Echange_contact_PolyMAC_P0P1NC::f_dist_init_ = 0 mutable
Referenced by init_f_dist().
invh_paroi
double Echange_contact_PolyMAC_P0P1NC::invh_paroi = 1e30
Referenced by readOn().
nom_autre_pb_
Nom Echange_contact_PolyMAC_P0P1NC::nom_autre_pb_ protected
Referenced by Echange_contact_PolyMAC_P0::init_op(), init_op(), and readOn().
nom_bord_
Nom Echange_contact_PolyMAC_P0P1NC::nom_bord_ protected
Referenced by Echange_contact_PolyMAC_P0::init_op(), init_op(), and readOn().
nom_champ_
Nom Echange_contact_PolyMAC_P0P1NC::nom_champ_ protected
Referenced by Echange_contact_PolyMAC_P0::init_op(), init_op(), and readOn().