TrioCFD: Correction_Lubchenko_PolyMAC_P0 Class Reference
Correction_Lubchenko_PolyMAC_P0 Class Reference
#include <Correction_Lubchenko_PolyMAC_P0.h>
Public Member Functions
void completer () override
const Type_info * get_info () const override
void mettre_a_jour (double temps) override
Public Member Functions inherited from Source_base
virtual int a_pour_Champ_Fonc (const Motcle &mot, TRUST_Ref< Champ_base * > &ch_ref) const
virtual void associer_champ_rho (const Champ_base &champ_rho)
virtual void completer ()
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
virtual void resetTime (double t)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Correction_Lubchenko_PolyMAC_P0()
Correction_Lubchenko_PolyMAC_P0::Correction_Lubchenko_PolyMAC_P0 ()
~Correction_Lubchenko_PolyMAC_P0()
Correction_Lubchenko_PolyMAC_P0::~Correction_Lubchenko_PolyMAC_P0 ()
Member Function Documentation
cree_instance()
Objet_U * Correction_Lubchenko_PolyMAC_P0::cree_instance () static
taille_memoire()
unsigned Correction_Lubchenko_PolyMAC_P0::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Correction_Lubchenko_PolyMAC_P0::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Correction_Lubchenko_PolyMAC_P0::info () static
get_info()
const Type_info * Correction_Lubchenko_PolyMAC_P0::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Source_base.
self_cast() [1/2]
Correction_Lubchenko_PolyMAC_P0 & Correction_Lubchenko_PolyMAC_P0::self_cast (Objet_U & r) static
self_cast() [2/2]
const Correction_Lubchenko_PolyMAC_P0 & Correction_Lubchenko_PolyMAC_P0::self_cast (const Objet_U & r) static
printOn()
Sortie & Correction_Lubchenko_PolyMAC_P0::printOn (Sortie & os) const override protected virtual
DOES NOTHING - to override in derived classes.
Imprime la source sur un flot de sortie.
Parameters
(Sortie& os) le flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Source_base.
readOn()
Entree & Correction_Lubchenko_PolyMAC_P0::readOn (Entree & is) override protected virtual
DOES NOTHING - to override in derived classes.
Lecture d'un terme source sur un flot d'entree.
Parameters
(Entree& is) le flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Source_base.
References Param::ajouter(), beta_disp_, beta_lift_, Probleme_base::creer_champ(), Nom::debute_par(), MorEqn::equation(), Process::exit(), Param::lire_avec_accolades_depuis(), n_l, Pb_Multiphase::nb_phases(), Pb_Multiphase::nom_phase(), portee_disp_, portee_lift_, Objet_U::que_suis_je(), and use_bif_.
has_interface_blocs()
int Correction_Lubchenko_PolyMAC_P0::has_interface_blocs () const inline override virtual
Reimplemented from Source_base.
dimensionner_blocs()
void Correction_Lubchenko_PolyMAC_P0::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl = {}) const override virtual
Reimplemented from Source_base.
ajouter_blocs()
void Correction_Lubchenko_PolyMAC_P0::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = {}) const override virtual
Reimplemented from Source_base.
References ajouter_blocs_BIF(), ajouter_blocs_disp(), ajouter_blocs_lift(), MorEqn::equation(), and use_bif_.
check_multiphase_compatibility()
void Correction_Lubchenko_PolyMAC_P0::check_multiphase_compatibility () const inline override virtual
Reimplemented from MorEqn.
completer()
void Correction_Lubchenko_PolyMAC_P0::completer () override virtual
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees: Source_base::associer_domaines(const Domaine_dis_base& ,const Domaine_Cl_dis_base&) Source_base::associer_pb(const Probleme_base&)
Reimplemented from Source_base.
References correlation_dispersion_, correlation_lift_, MorEqn::equation(), Process::exit(), Probleme_base::has_champ(), is_turb, TRUST_Ref< _CLASSE_ >::non_nul(), TRUST_List< _CLASSE_ >::size(), and Equation_base::sources().
associer_domaines()
void Correction_Lubchenko_PolyMAC_P0::associer_domaines (const Domaine_dis_base & , const Domaine_Cl_dis_base &) inline override virtual
Implements Source_base.
associer_pb()
void Correction_Lubchenko_PolyMAC_P0::associer_pb (const Probleme_base &) inline override virtual
Implements Source_base.
mettre_a_jour()
void Correction_Lubchenko_PolyMAC_P0::mettre_a_jour (double temps) inline override virtual
DOES NOTHING - to override in derived classes.
Mise a jour en temps du terme source.
Parameters
(double) le pas de temps de mise a jour
Reimplemented from Source_base.
ajouter_blocs_lift()
void Correction_Lubchenko_PolyMAC_P0::ajouter_blocs_lift (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl) const protected
References Portance_interfaciale_base::input_t::alpha, beta_lift_, Portance_interfaciale_base::output_t::Cl, Portance_interfaciale_base::coefficient(), correlation_lift_, Portance_interfaciale_base::input_t::d_bulles, Objet_U::dimension, MorEqn::equation(), Pb_Multiphase::equation_energie(), Pb_Multiphase::equation_masse(), Pb_Multiphase::equation_qdm(), Champ_Face_base::fcl(), Probleme_base::get_champ(), Milieu_composite::get_interface(), Milieu_composite::get_saturation(), Saturation_base::get_sigma(), Probleme_base::has_champ(), Milieu_composite::has_interface(), Milieu_composite::has_saturation(), Equation_base::inconnue(), Portance_interfaciale_base::input_t::k_turb, TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Milieu_base::masse_volumique(), Equation_base::milieu(), Portance_interfaciale_base::input_t::mu, n_l, Portance_interfaciale_base::input_t::nv, Portance_interfaciale_base::input_t::p, Champ_Proto::passe(), Champ_Inc_base::passe(), Milieu_base::porosite_elem(), Milieu_base::porosite_face(), portee_lift_, Equation_base::probleme(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Portance_interfaciale_base::input_t::rho, Portance_interfaciale_base::input_t::sigma, Interface_base::sigma(), Portance_interfaciale_base::input_t::T, Champ_Face_PolyMAC_P0::v_norm(), TRUST_Ref< _CLASSE_ >::valeur(), and Champ_Proto::valeurs().
Referenced by ajouter_blocs().
ajouter_blocs_disp()
void Correction_Lubchenko_PolyMAC_P0::ajouter_blocs_disp (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl) const protected
References Dispersion_bulles_base::input_t::alpha, beta_disp_, Dispersion_bulles_base::coefficient(), correlation_dispersion_, Dispersion_bulles_base::output_t::Ctd, Dispersion_bulles_base::input_t::d_bulles, Objet_U::dimension, Dispersion_bulles_base::input_t::e, MorEqn::equation(), Pb_Multiphase::equation_energie(), Pb_Multiphase::equation_masse(), Pb_Multiphase::equation_qdm(), Champ_Face_base::fcl(), Probleme_base::get_champ(), Milieu_composite::get_interface(), Milieu_composite::get_saturation(), Interface_base::get_sigma_tab(), Probleme_base::has_champ(), Milieu_composite::has_interface(), Milieu_composite::has_saturation(), Equation_base::inconnue(), is_turb, Dispersion_bulles_base::input_t::k_turb, Dispersion_bulles_base::input_t::k_WIT, TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Milieu_base::masse_volumique(), Equation_base::milieu(), Dispersion_bulles_base::input_t::mu, n_l, Dispersion_bulles_base::input_t::nut, Dispersion_bulles_base::input_t::nv, Dispersion_bulles_base::input_t::p, Champ_Proto::passe(), Champ_Inc_base::passe(), Milieu_base::porosite_elem(), Milieu_base::porosite_face(), portee_disp_, Equation_base::probleme(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Dispersion_bulles_base::input_t::rho, Dispersion_bulles_base::input_t::sigma, Interface_base::sigma(), Dispersion_bulles_base::input_t::T, Champ_Face_PolyMAC_P0::v_norm(), TRUST_Ref< _CLASSE_ >::valeur(), and Champ_Proto::valeurs().
Referenced by ajouter_blocs().
ajouter_blocs_BIF()
void Correction_Lubchenko_PolyMAC_P0::ajouter_blocs_BIF (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl) const protected
References Op_Dift_Multiphase_proto::correlation(), MD_Vector_tools::creer_tableau_distribue(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, MorEqn::equation(), Probleme_base::equation(), Process::exit(), Champ_Inc_P0_base::fcl(), Champ_Elem_PolyMAC_P0::fgrad_d, Champ_Elem_PolyMAC_P0::fgrad_e, Champ_Elem_PolyMAC_P0::fgrad_w, Probleme_base::get_champ(), Source_base::get_champ(), TRUSTVect< _TYPE_, _SIZE_ >::get_md_vector(), Champ_Elem_PolyMAC_P0::init_grad(), Operateur::l_op_base(), Equation_base::milieu(), n_l, Navier_Stokes_std::operateur(), Champ_Proto::passe(), Milieu_base::porosite_elem(), Navier_Stokes_std::pression(), Equation_base::probleme(), Viscosite_turbulente_multiple::reynolds_stress_BIF(), Champ_Inc_base::valeurs(), Champ_Proto::valeurs(), and Navier_Stokes_std::vitesse().
Referenced by ajouter_blocs().
Member Data Documentation
info_obj
const Type_info Correction_Lubchenko_PolyMAC_P0::info_obj static
n_l
int Correction_Lubchenko_PolyMAC_P0::n_l = -1 protected
Referenced by ajouter_blocs_BIF(), ajouter_blocs_disp(), ajouter_blocs_lift(), and readOn().
is_turb
int Correction_Lubchenko_PolyMAC_P0::is_turb = 0 protected
Referenced by ajouter_blocs_disp(), and completer().
use_bif_
int Correction_Lubchenko_PolyMAC_P0::use_bif_ = 0 protected
Referenced by ajouter_blocs(), and readOn().
correlation_lift_
TRUST_Ref< Correlation_base *> Correction_Lubchenko_PolyMAC_P0::correlation_lift_ protected
Referenced by ajouter_blocs_lift(), and completer().
correlation_dispersion_
TRUST_Ref< Correlation_base *> Correction_Lubchenko_PolyMAC_P0::correlation_dispersion_ protected
Referenced by ajouter_blocs_disp(), and completer().
beta_lift_
double Correction_Lubchenko_PolyMAC_P0::beta_lift_ = 1. protected
Referenced by ajouter_blocs_lift(), and readOn().
beta_disp_
double Correction_Lubchenko_PolyMAC_P0::beta_disp_ = 1. protected
Referenced by ajouter_blocs_disp(), and readOn().
portee_disp_
double Correction_Lubchenko_PolyMAC_P0::portee_disp_ = 1. protected
Referenced by ajouter_blocs_disp(), and readOn().
portee_lift_
double Correction_Lubchenko_PolyMAC_P0::portee_lift_ = 1. protected
Referenced by ajouter_blocs_lift(), and readOn().