TrioCFD: Portance_interfaciale_Sugrue Class Reference
Portance_interfaciale_Sugrue Class Reference
#include <Portance_interfaciale_Sugrue.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
 Le coefficient renvoye par cette classe est toujours >0, c'est Portanc_interfaciale_PolyMAC_P0 qui gere les signes
Constructor & Destructor Documentation
Portance_interfaciale_Sugrue()
Portance_interfaciale_Sugrue::Portance_interfaciale_Sugrue ()
~Portance_interfaciale_Sugrue()
Portance_interfaciale_Sugrue::~Portance_interfaciale_Sugrue ()
Member Function Documentation
cree_instance()
Objet_U * Portance_interfaciale_Sugrue::cree_instance () static
taille_memoire()
unsigned Portance_interfaciale_Sugrue::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Portance_interfaciale_Sugrue::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Portance_interfaciale_Sugrue::info () static
get_info()
const Type_info * Portance_interfaciale_Sugrue::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Portance_interfaciale_base.
self_cast() [1/2]
Portance_interfaciale_Sugrue & Portance_interfaciale_Sugrue::self_cast (Objet_U & r) static
self_cast() [2/2]
const Portance_interfaciale_Sugrue & Portance_interfaciale_Sugrue::self_cast (const Objet_U & r) static
printOn()
Sortie & Portance_interfaciale_Sugrue::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Portance_interfaciale_base.
readOn()
Entree & Portance_interfaciale_Sugrue::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Portance_interfaciale_base.
References Param::ajouter(), Nom::debute_par(), Process::exit(), g_, Param::lire_avec_accolades_depuis(), n_l, Pb_Multiphase::nb_phases(), Pb_Multiphase::nom_phase(), Correlation_base::pb_, Objet_U::que_suis_je(), and TRUST_Ref< _CLASSE_ >::valeur().
coefficient()
void Portance_interfaciale_Sugrue::coefficient (const input_t & input, output_t & output) const override virtual
Implements Portance_interfaciale_base.
References Portance_interfaciale_base::input_t::alpha, Portance_interfaciale_base::output_t::Cl, Portance_interfaciale_base::input_t::d_bulles, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), g_, Portance_interfaciale_base::input_t::k_turb, n_l, Portance_interfaciale_base::input_t::nv, Portance_interfaciale_base::input_t::rho, and Portance_interfaciale_base::input_t::sigma.
Member Data Documentation
info_obj
const Type_info Portance_interfaciale_Sugrue::info_obj static
g_
double Portance_interfaciale_Sugrue::g_ =9.81 protected
Referenced by coefficient(), and readOn().
n_l
int Portance_interfaciale_Sugrue::n_l = -1 protected
Referenced by coefficient(), and readOn().