TrioCFD: Transport_2eq_base Class Reference
Transport_2eq_base Class Reference abstract
#include <Transport_2eq_base.h>
Public Member Functions
void associer_milieu_base (const Milieu_base &) override
double calculer_pas_de_temps () const override
const Type_info * get_info () const override
const Milieu_base & milieu () const override
Milieu_base & milieu () override
Modele_turbulence_hyd_2_eq_base & modele_turbulence ()
const Modele_turbulence_hyd_2_eq_base & modele_turbulence () const
Public Member Functions inherited from Equation_base
virtual void abortTimeStep ()
virtual void associer_domaine_dis (const Domaine_dis_base &)
virtual void associer_pb_base (const Probleme_base &)
virtual void associer_sch_tps_base (const Schema_Temps_base &)
virtual double calculer_pas_de_temps () const
virtual void completer ()
virtual std::vector< YAML_data > data_a_sauvegarder () const
DoubleTab & derivee_en_temps_conv (DoubleTab &, const DoubleTab &)
virtual DoubleTab & derivee_en_temps_inco (DoubleTab &)
const Discretisation_base & discretisation () const
virtual void discretiser ()
virtual const Motcle & domaine_application () const
virtual Domaine_Cl_dis_base & domaine_Cl_dis ()
virtual const Domaine_Cl_dis_base & domaine_Cl_dis () const
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual void imprimer (Sortie &os) const
virtual bool initTimeStep (double dt)
const Nom & le_nom () const override
int limpr () const
virtual void mettre_a_jour (double temps)
virtual int preparer_calcul ()
Probleme_base & probleme ()
const Probleme_base & probleme () const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Schema_Temps_base & schema_temps ()
const Schema_Temps_base & schema_temps () const
Solveur_Masse_base & solv_masse ()
const Solveur_Masse_base & solv_masse () const
Sources & sources ()
const Sources & sources () const
virtual void valider_iteration ()
virtual void verifie_ch_init_nb_comp (const Champ_Inc_base &ch_ref, const int nb_comp) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Equation_base
virtual Entree & lire_cl (Entree &)
virtual Entree & lire_cond_init (Entree &)
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual Entree & lire_sources (Entree &)
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
virtual int verif_Cl () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
de transport des modeles a deux equations type k-DISSIP
Constructor & Destructor Documentation
Transport_2eq_base()
Transport_2eq_base::Transport_2eq_base ()
~Transport_2eq_base()
Transport_2eq_base::~Transport_2eq_base () override
Member Function Documentation
info()
const Type_info * Transport_2eq_base::info () static
get_info()
const Type_info * Transport_2eq_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Equation_base.
Reimplemented in Transport_K_Eps, Transport_K_Eps_Bas_Reynolds, Transport_K_Eps_base, Transport_K_Eps_non_std, Transport_K_Eps_Realisable, Transport_K_KEps, Transport_K_Omega, Transport_K_Omega_base, Transport_K_ou_Eps, Transport_K_ou_Eps_base, Transport_K_ou_Eps_non_std, and Transport_K_ou_Eps_Realisable.
self_cast() [1/2]
Transport_2eq_base & Transport_2eq_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Transport_2eq_base & Transport_2eq_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Transport_2eq_base::printOn (Sortie & is) const override protected virtual
Parameters
(Sortie& is) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Equation_base.
Reimplemented in Transport_K_Eps, Transport_K_Eps_Bas_Reynolds, Transport_K_Eps_base, Transport_K_Eps_non_std, Transport_K_Eps_Realisable, Transport_K_KEps, Transport_K_Omega, Transport_K_Omega_base, Transport_K_ou_Eps, Transport_K_ou_Eps_base, Transport_K_ou_Eps_non_std, and Transport_K_ou_Eps_Realisable.
References Objet_U::que_suis_je().
readOn()
Entree & Transport_2eq_base::readOn (Entree & is) override protected virtual
Simple appel a Equation_base::readOn(Entree&)
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Equation_base.
Reimplemented in Transport_K_Eps, Transport_K_Eps_Bas_Reynolds, Transport_K_Eps_base, Transport_K_Eps_non_std, Transport_K_Eps_Realisable, Transport_K_KEps, Transport_K_Omega, Transport_K_Omega_base, Transport_K_ou_Eps, Transport_K_ou_Eps_base, Transport_K_ou_Eps_non_std, and Transport_K_ou_Eps_Realisable.
References Equation_base::readOn().
set_param()
void Transport_2eq_base::set_param (Param & param) override virtual
Reimplemented from Equation_base.
Reimplemented in Transport_K_Eps_base, Transport_K_Omega_base, Transport_K_Eps, Transport_K_Omega, Transport_K_ou_Eps, Transport_K_ou_Eps_Realisable, Transport_K_Eps_non_std, Transport_K_Eps_Realisable, Transport_K_KEps, and Transport_K_ou_Eps_non_std.
References Param::ajouter_condition(), Param::ajouter_non_std(), and Equation_base::set_param().
Referenced by Transport_K_Eps_base::set_param(), Transport_K_Omega_base::set_param(), Transport_K_ou_Eps::set_param(), Transport_K_ou_Eps_Realisable::set_param(), and Transport_K_ou_Eps_non_std::set_param().
associer()
void Transport_2eq_base::associer (const Equation_base & eqn_hydr)
References Equation_base::associer_domaine_dis(), Equation_base::associer_pb_base(), Equation_base::associer_sch_tps_base(), Equation_base::domaine_dis(), Equation_base::probleme(), and Equation_base::schema_temps().
Referenced by Transport_K_Eps::associer_modele_turbulence(), Transport_K_Eps_Bas_Reynolds::associer_modele_turbulence(), Transport_K_Eps_Realisable::associer_modele_turbulence(), Transport_K_KEps::associer_modele_turbulence(), Transport_K_Omega::associer_modele_turbulence(), Transport_K_ou_Eps::associer_modele_turbulence(), and Transport_K_ou_Eps_Realisable::associer_modele_turbulence().
associer_vitesse()
void Transport_2eq_base::associer_vitesse (const Champ_base & vit) inline
References la_vitesse_transportante.
Referenced by Transport_K_Eps::associer_modele_turbulence(), Transport_K_Eps_Bas_Reynolds::associer_modele_turbulence(), Transport_K_Eps_Realisable::associer_modele_turbulence(), Transport_K_KEps::associer_modele_turbulence(), Transport_K_Omega::associer_modele_turbulence(), Transport_K_ou_Eps::associer_modele_turbulence(), Transport_K_ou_Eps_Realisable::associer_modele_turbulence(), Transport_K_Eps::lire_motcle_non_standard(), Transport_K_Eps_non_std::lire_motcle_non_standard(), Transport_K_Eps_Realisable::lire_motcle_non_standard(), Transport_K_Omega::lire_motcle_non_standard(), Transport_K_ou_Eps::lire_motcle_non_standard(), Transport_K_ou_Eps_non_std::lire_motcle_non_standard(), and Transport_K_ou_Eps_Realisable::lire_motcle_non_standard().
associer_milieu_base()
void Transport_2eq_base::associer_milieu_base (const Milieu_base & un_milieu) override virtual
Associe un milieu physique a l'equation.
Parameters
(Milieu_base& un_milieu) le milieu physique a associer a l'equation
Implements Equation_base.
Reimplemented in Transport_K_Eps_Bas_Reynolds, Transport_K_Eps_Realisable, and Transport_K_KEps.
References le_fluide.
Referenced by Transport_K_Eps::associer_modele_turbulence(), Transport_K_Omega::associer_modele_turbulence(), Transport_K_ou_Eps::associer_modele_turbulence(), and Transport_K_ou_Eps_Realisable::associer_modele_turbulence().
milieu() [1/2]
Milieu_base & Transport_2eq_base::milieu () override virtual
Renvoie le milieu (fluide) associe a l'equation.
Returns
(Milieu_base&) le milieu (fluide) associe a l'equation
Implements Equation_base.
References Process::exit(), le_fluide, TRUST_Ref< _CLASSE_ >::non_nul(), Objet_U::que_suis_je(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Op_Diff_K_Eps_QC_VEF_Face::ajouter(), Transport_K_Eps_Realisable::completer(), Transport_K_Eps::readOn(), Transport_K_Omega::readOn(), Transport_K_ou_Eps::readOn(), and Transport_K_ou_Eps_Realisable::readOn().
milieu() [2/2]
const Milieu_base & Transport_2eq_base::milieu () const override virtual
Renvoie le milieu (fluide) associe a l'equation.
(version const)
Returns
(Milieu_base&) le milieu (fluide) associe a l'equation
Implements Equation_base.
References Process::exit(), le_fluide, TRUST_Ref< _CLASSE_ >::non_nul(), Objet_U::que_suis_je(), and TRUST_Ref< _CLASSE_ >::valeur().
calculer_pas_de_temps()
double Transport_2eq_base::calculer_pas_de_temps () const override virtual
Calcul du prochain pas de temps.
Renvoie l'inverse de la somme des inverses des pas de temps calcules par les operateurs. Ces pas de temps sont ceux pour le schema d'Euler explicite. Le pas de temps n'est pas majore par dt_max, ceci est fait dans corriger_dt_calcule
Returns
(double) inverse de la somme des inverses des pas de temps calcules par les operateurs
Reimplemented from Equation_base.
References Equation_base::calculer_pas_de_temps(), Probleme_base::equation(), and Equation_base::probleme().
modele_turbulence() [1/2]
const Modele_turbulence_hyd_2_eq_base & Transport_2eq_base::modele_turbulence () const inline
Renvoie le modele de turbulence associe a l'equation.
(version const)
Returns
(Modele_turbulence_hyd_base&) le modele de turbulence associe a l'equation
References mon_modele, TRUST_Ref< _CLASSE_ >::non_nul(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Op_Diff_K_Omega_VDF_base::associer_diffusivite_turbulente(), Op_Diff_K_Eps_Bas_Re_VDF_base::associer_diffusivite_turbulente_impl(), Modele_turbulence_hyd_K_Eps::calculer_viscosite_turbulente(), Modele_turbulence_hyd_K_Eps_Bicephale::calculer_viscosite_turbulente(), Op_Diff_K_Eps_VDF_base::completer(), Op_Diff_K_Omega_VDF_base::completer(), Transport_K_Eps_base::controler_K_Eps(), Transport_K_Omega_base::controler_K_Omega(), Transport_K_ou_Eps_base::controler_variable(), Transport_K_Eps::corriger_derivee_impl(), Transport_K_Omega::corriger_derivee_impl(), Transport_K_ou_Eps::corriger_derivee_impl(), Transport_K_ou_Eps_Realisable::corriger_derivee_impl(), Transport_K_Eps_base::discretiser(), Transport_K_Omega_base::discretiser(), Transport_K_ou_Eps_base::discretiser(), and lire_op_diff_turbulent().
modele_turbulence() [2/2]
Modele_turbulence_hyd_2_eq_base & Transport_2eq_base::modele_turbulence () inline
Renvoie le modele de turbulence associe a l'equation.
Returns
(Modele_turbulence_hyd_base&) le modele de turbulence associe a l'equation
References mon_modele, TRUST_Ref< _CLASSE_ >::non_nul(), and TRUST_Ref< _CLASSE_ >::valeur().
associer_modele_turbulence()
virtual void Transport_2eq_base::associer_modele_turbulence (const Modele_turbulence_hyd_2_eq_base &) pure virtual
Implemented in Transport_K_Eps, Transport_K_Eps_Bas_Reynolds, Transport_K_Eps_Realisable, Transport_K_KEps, Transport_K_Omega, Transport_K_ou_Eps, and Transport_K_ou_Eps_Realisable.
Referenced by Modele_turbulence_hyd_K_Eps::lire_motcle_non_standard(), Modele_turbulence_hyd_K_Eps_2_Couches::lire_motcle_non_standard(), Modele_turbulence_hyd_K_Eps_Bas_Reynolds::lire_motcle_non_standard(), Modele_turbulence_hyd_K_Eps_Realisable::lire_motcle_non_standard(), Modele_turbulence_hyd_K_Omega::lire_motcle_non_standard(), and Modele_turbulence_hyd_RANS_Bicephale_base::lire_motcle_non_standard().
get_position_cells()
void Transport_2eq_base::get_position_cells (Nom & position, int & n) protected
References Objet_U::dimension, Equation_base::domaine_dis(), and Domaine_VF::xp().
Referenced by Transport_K_Eps_base::controler_K_Eps(), and Transport_K_Omega_base::controler_K_Omega().
get_position_faces()
void Transport_2eq_base::get_position_faces (Nom & position, int & n) protected
References Objet_U::dimension, Equation_base::domaine_dis(), and Domaine_VF::xv().
Referenced by Transport_K_Eps_base::controler_K_Eps(), and Transport_K_Omega_base::controler_K_Omega().
lire_op_diff_turbulent()
Entree & Transport_2eq_base::lire_op_diff_turbulent (Entree & is) protected
References Operateur_Diff::associer_diffusivite(), Operateur_base::associer_eqn(), Objet_U::axi, Nom::contient(), Operateur_Diff::diffusivite(), Equation_base::discretisation(), Modele_turbulence_hyd_base::equation(), Process::exit(), Equation_base::inconnue(), Operateur_Diff::l_op_base(), modele_turbulence(), Field_base::nb_comp(), Objet_U::que_suis_je(), Nom::suffix(), terme_diffusif, and Operateur_Diff::typer().
Referenced by Transport_K_Eps::lire_motcle_non_standard(), Transport_K_Eps_non_std::lire_motcle_non_standard(), Transport_K_Eps_Realisable::lire_motcle_non_standard(), Transport_K_Omega::lire_motcle_non_standard(), Transport_K_ou_Eps::lire_motcle_non_standard(), Transport_K_ou_Eps_non_std::lire_motcle_non_standard(), and Transport_K_ou_Eps_Realisable::lire_motcle_non_standard().
Member Data Documentation
info_obj
const Type_info Transport_2eq_base::info_obj static
terme_diffusif
Operateur_Diff Transport_2eq_base::terme_diffusif protected
Referenced by Transport_K_Eps::lire_motcle_non_standard(), Transport_K_Eps_non_std::lire_motcle_non_standard(), Transport_K_Eps_Realisable::lire_motcle_non_standard(), Transport_K_Omega::lire_motcle_non_standard(), Transport_K_ou_Eps::lire_motcle_non_standard(), Transport_K_ou_Eps_non_std::lire_motcle_non_standard(), Transport_K_ou_Eps_Realisable::lire_motcle_non_standard(), lire_op_diff_turbulent(), Transport_K_Eps::operateur(), Transport_K_Eps_non_std::operateur(), Transport_K_Eps_Realisable::operateur(), Transport_K_Omega::operateur(), Transport_K_ou_Eps::operateur(), Transport_K_ou_Eps_non_std::operateur(), and Transport_K_ou_Eps_Realisable::operateur().
terme_convectif
Operateur_Conv Transport_2eq_base::terme_convectif protected
Referenced by Transport_K_Eps_ALE::corriger_derivee_impl_ALE(), Transport_K_Eps::lire_motcle_non_standard(), Transport_K_Eps_non_std::lire_motcle_non_standard(), Transport_K_Eps_Realisable::lire_motcle_non_standard(), Transport_K_Omega::lire_motcle_non_standard(), Transport_K_ou_Eps::lire_motcle_non_standard(), Transport_K_ou_Eps_non_std::lire_motcle_non_standard(), Transport_K_ou_Eps_Realisable::lire_motcle_non_standard(), Transport_K_Eps::operateur(), Transport_K_Eps_non_std::operateur(), Transport_K_Eps_Realisable::operateur(), Transport_K_Omega::operateur(), Transport_K_ou_Eps::operateur(), Transport_K_ou_Eps_non_std::operateur(), and Transport_K_ou_Eps_Realisable::operateur().
le_fluide
TRUST_Ref< Milieu_base *> Transport_2eq_base::le_fluide protected
Referenced by associer_milieu_base(), Transport_K_Eps_Bas_Reynolds::associer_milieu_base(), Transport_K_Eps_Realisable::associer_milieu_base(), Transport_K_KEps::associer_milieu_base(), Transport_K_Eps_non_std::diffusivite_pour_transport(), Transport_K_Eps_Realisable::diffusivite_pour_transport(), Transport_K_ou_Eps_non_std::diffusivite_pour_transport(), Transport_K_Eps::lire_motcle_non_standard(), Transport_K_Omega::lire_motcle_non_standard(), Transport_K_ou_Eps::lire_motcle_non_standard(), Transport_K_ou_Eps_Realisable::lire_motcle_non_standard(), and milieu().
la_vitesse_transportante
TRUST_Ref< Champ_Inc_base *> Transport_2eq_base::la_vitesse_transportante protected
Referenced by associer_vitesse().
mon_modele
TRUST_Ref< Modele_turbulence_hyd_2_eq_base *> Transport_2eq_base::mon_modele protected
Referenced by Transport_K_Eps::associer_modele_turbulence(), Transport_K_Eps_Bas_Reynolds::associer_modele_turbulence(), Transport_K_Eps_Realisable::associer_modele_turbulence(), Transport_K_KEps::associer_modele_turbulence(), Transport_K_Omega::associer_modele_turbulence(), Transport_K_ou_Eps::associer_modele_turbulence(), Transport_K_ou_Eps_Realisable::associer_modele_turbulence(), and modele_turbulence().