TrioCFD: Domaine_VF Class Reference
Domaine_VF Class Reference
#include <Domaine_VF.h>
Public Member Functions
void build_map_mc_Cmesh (const bool with_faces) override
void build_mc_dual_mesh () const
void build_mc_face_mesh () const
void construire_face_virt_pe_num ()
int elem_faces (int i, int j) const
int face_voisins (int num_face, int i) const
const Type_info * get_info () const override
void init_dist_paroi_globale (const Conds_lim &conds_lim) override
int nb_faces_bord () const
int nb_faces_bord_tot () const
int nb_faces_internes () const
int nb_faces_tot () const
int nb_som_face () const
int premiere_face_bord () const
int premiere_face_int () const
Public Member Functions inherited from Domaine_dis_base
void associer_domaine (const Domaine &)
const Domaine & domaine () const
void ecrire_noms_bords (Sortie &) const
virtual IntTab & face_sommets ()
const Frontiere_dis_base & frontiere_dis (const Nom &) const
const Type_info * get_info () const override
int nombre_de_sous_domaines_dis () const
int rang_frontiere (const Nom &) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
Cette classe abstraite contient les informations geometriques communes aux methodes de Volumes Finis (methodes VDF et VEF par exemple)
See also
Domaine_dis_base
Constructor & Destructor Documentation
Domaine_VF()
Domaine_VF::Domaine_VF ()
~Domaine_VF()
Domaine_VF::~Domaine_VF () override
Member Function Documentation
info()
const Type_info * Domaine_VF::info () static
get_info()
const Type_info * Domaine_VF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Domaine_dis_base.
Reimplemented in Domaine_VF_inst, Domaine_PolyMAC, Domaine_PolyMAC_P0, Domaine_PolyMAC_P0P1NC, Domaine_VDF, and Domaine_VEF.
self_cast() [1/2]
Domaine_VF & Domaine_VF::self_cast (Objet_U & r) static
self_cast() [2/2]
const Domaine_VF & Domaine_VF::self_cast (const Objet_U & r) static
printOn()
Sortie & Domaine_VF::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Domaine_dis_base.
Reimplemented in Domaine_VF_inst, Domaine_PolyMAC, Domaine_PolyMAC_P0, Domaine_PolyMAC_P0P1NC, Domaine_VDF, and Domaine_VEF.
References TRUSTVect< _TYPE_, _SIZE_ >::ecrit(), TRUSTTab< _TYPE_, _SIZE_ >::ecrit(), elem_faces_, face_sommets_, face_voisins_, les_bords_, nb_faces(), volumes_, volumes_entrelaces_, xp_, and xv_.
Referenced by Domaine_Poly_base::ecrit(), Domaine_EF::printOn(), Domaine_Poly_base::printOn(), Domaine_VF_inst::printOn(), Domaine_VDF::printOn(), and Domaine_VEF::printOn().
readOn()
Entree & Domaine_VF::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Domaine_dis_base.
Reimplemented in Domaine_VF_inst, Domaine_PolyMAC, Domaine_PolyMAC_P0, Domaine_PolyMAC_P0P1NC, Domaine_VDF, and Domaine_VEF.
References elem_faces_, face_sommets_, face_voisins_, les_bords_, TRUSTVect< _TYPE_, _SIZE_ >::lit(), TRUSTTab< _TYPE_, _SIZE_ >::lit(), volumes_, volumes_entrelaces_, xp_, and xv_.
Referenced by Domaine_EF::readOn(), Domaine_Poly_base::readOn(), Domaine_VF_inst::readOn(), Domaine_VDF::readOn(), and Domaine_VEF::readOn().
face_normales() [1/3]
virtual double Domaine_VF::face_normales (int face, int comp) const inline virtual
Reimplemented in Domaine_VDF, Domaine_VF_inst, and Domaine_VDF.
References face_normales_.
Referenced by Champ_Face_PolyMAC::affecter_(), Champ_Fonc_Face_PolyMAC::affecter_(), Op_Div_EF::ajouter(), Op_Conv_Amont_old_VEF_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Centre_EF_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_EF_VEF_P1NC::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Dift_VEF_Face_Q1::ajouter(), Op_Conv_RT_VEF_Face::ajouter(), Perte_Charge_Singuliere_PolyMAC_Face::ajouter(), Perte_Charge_Singuliere_VEF_Face::ajouter(), Terme_Boussinesq_VEF_Face::ajouter(), Terme_Source_Qdm_VEF_Face::ajouter(), Op_Div_VEFP1B_Elem::ajouter_aretes(), Op_Grad_VEF_P1B_Face::ajouter_aretes(), DP_Impose_VEF_Face::ajouter_blocs(), Op_Grad_EF::ajouter_bord(), Op_Diff_EF::ajouter_bords(), Op_Dift_EF_Q1::ajouter_bords(), Op_Diff_VEF_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Face::ajouter_cas_vectoriel(), Op_Conv_Amont_old_VEF_Face::ajouter_contribution(), Op_Conv_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Face::ajouter_contribution(), Op_Conv_RT_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Face::ajouter_contribution_multi_scalaire(), Operateur_Conv_sensibility_VEF::ajouter_conv_term(), Op_Div_VEFP1B_Elem::ajouter_elem(), Op_Grad_VEF_P1B_Face::ajouter_elem(), Operateur_Conv_sensibility_VEF::ajouter_Lsensibility_state_Amont(), Operateur_Conv_sensibility_VEF::ajouter_Lstate_sensibility_Amont(), Op_Grad_VEF_P1B_Face::ajouter_som(), Op_Div_VEFP1B_Elem::ajouter_som(), Op_Conv_ALE_VEF::ajouterALE(), Masse_VEF_P1NC::appliquer_impl(), Transport_Marqueur_FT::appliquer_reflexion_vitesse(), Parcours_interface::associer_domaine_dis(), Champ_front_contact_VEF::calcul_coeff_amort(), Modele_Jones_Launder_VEF::Calcul_D(), Modele_Launder_Sharma_VEF::Calcul_D(), Modele_Jones_Launder_VEF::Calcul_D_BiK(), Modele_Launder_Sharma_VEF::Calcul_D_BiK(), Champ_P1NC::calcul_duidxj_paroi(), Champ_front_contact_VEF::calcul_grads_locaux(), Champ_P1NC::calcul_h_conv(), Transport_Interfaces_FT_Disc::calcul_indicatrice_faces(), Champ_P1NC::calcul_y_plus(), Perte_Charge_Singuliere::calculate_Q(), Op_Diff_VEF_Face_Stab::calculer_coefficients(), Terme_Source_Canal_perio_VDF_Face::calculer_debit(), Terme_Source_Canal_perio_VEF_P1NC::calculer_debit(), Op_Diff_P1NC_barprim::calculer_divergence(), Op_Dift_VEF_P1NCP1B_Face::calculer_divergence_elem(), Op_Diff_VEFP1NCP1B_Face::calculer_divergence_elem(), Op_Dift_VEF_P1NCP1B_Face::calculer_divergence_som(), Op_Diff_VEFP1NCP1B_Face::calculer_divergence_som(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab_elem(), Op_Dift_VEF_base::calculer_dt_stab_P1NCP1B(), Op_Grad_EF::calculer_flux_bords(), Op_Grad_VEF_P1B_Face::calculer_flux_bords(), Op_Diff_VEFP1NCP1B_Face::calculer_flux_bords_elem(), Op_Diff_VEFP1NCP1B_Face::calculer_flux_bords_som(), Flux_radiatif_VEF::calculer_flux_radiatif(), EDO_Pression_th_VEF::calculer_grad(), Op_Dift_VEF_P1NCP1B_Face::calculer_gradient_elem(), Op_Diff_VEFP1NCP1B_Face::calculer_gradient_elem(), Navier_Stokes_FT_Disc::calculer_gradient_indicatrice(), Op_Dift_VEF_P1NCP1B_Face::calculer_gradient_som(), Op_Diff_VEFP1NCP1B_Face::calculer_gradient_som(), Op_Diff_VEF_Face_Stab::calculer_gradients(), Paroi_std_hyd_VEF::calculer_hyd(), Paroi_std_hyd_VEF_diphasique::calculer_hyd(), Paroi_negligeable_VEF::calculer_hyd(), ParoiVEF_TBLE::calculer_hyd(), Paroi_std_hyd_VEF::calculer_hyd_BiK(), ParoiVEF_TBLE::calculer_hyd_BiK(), ParoiVEF_TBLE_scal::calculer_scal(), Discretisation_tools::cells_to_faces(), Champ_P1NC::compo_normale_sortante(), Champ_Q1NC::compo_normale_sortante(), Op_Conv_Amont_old_VEF_Face::contribue_au_second_membre(), Op_Conv_VEF_Face::contribue_au_second_membre(), Perte_Charge_Singuliere_PolyMAC_Face::contribuer_a_avec(), Perte_Charge_Singuliere_VEF_Face::contribuer_a_avec(), Op_Dift_VEF_Face::contribuer_au_second_membre(), Op_Dift_VEF_P1NCP1B_Face::corriger_div_pour_Cl(), Sortie_libre_Gradient_Pression_libre_VEF::flux_impose(), Champ_Generique_Transformation::get_champ(), Champ_Generique_Tparoi_VEF::get_champ(), Champ_Q1NC::gradient(), Op_Diff_VEFP1NCP1B_Face::gradient_som(), Op_Diff_VEFP1NCP1B_Face::gradient_som_CL(), Domaine_Cl_PolyMAC::imposer_cond_lim(), Domaine_Cl_VEF::imposer_cond_lim(), Loi_Paroi_Nu_Impose_VEF::imprimer_nusselt(), ParoiVEF_TBLE::imprimer_ustar(), ParoiVEF_TBLE::init_lois_paroi(), ParoiVEF_TBLE_scal::init_lois_paroi(), Ch_front_Vortex::initialiser(), Champ_front_tangentiel_VEF::initialiser(), Domaine_ALE::laplacien(), Perte_Charge_Singuliere::lire_surfaces(), Champ_front_fonc_gradient_VEF::mettre_a_jour(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::mettre_a_jour(), Domaine_ALE::mettre_a_jour(), Estimateur_Aposteriori_P0_VEF::mettre_a_jour(), Op_Grad_VEF_P1B_Face::modifier_grad_pour_Cl(), Eq_rayo_semi_transp_VEF::modifier_matrice(), Op_VEF_Face::modifier_pour_Cl(), Assembleur_P_EF::modifier_secmem(), Assembleur_P_PolyMAC::modifier_secmem(), Assembleur_P_VEF::modifier_secmem(), Assembleur_P_VEFPreP1B::modifier_secmem_elem(), Assembleur_P_VEFPreP1B::modifier_secmem_som(), Champ_P1NC::norme_H1(), Terme_Source_Qdm_lambdaup_VEF_Face::norme_H1(), Echange_contact_Correlation_VEF::pdt_scal(), Echange_contact_Correlation_VEF::pdt_scalSqrt(), Traitement_particulier_NS_CEG::preparer_calcul_particulier(), Transport_Interfaces_FT_Disc::ramasse_miettes(), Assembleur_P_VEF::remplir(), Porosites::remplir_champ(), Op_Conv_EF_VEF_P1NC_Stab::remplir_fluent(), Op_Conv_Muscl_New_VEF_Face::remplir_fluent(), Op_Conv_VEF_Face::remplir_fluent(), Operateur_Conv_sensibility_VEF::remplir_fluent(), Op_Conv_ALE_VEF::remplir_fluent_ALEincluded(), Domaine_Cl_EF::remplir_type_elem_Cl(), Echange_contact_Correlation_VEF::surfacesVEF(), Op_Diff_RotRot::vecteur_normal(), Op_Curl_VEFP1B::vecteur_normal(), and Op_Rot_VEFP1B::vecteur_normal().
face_normales() [2/3]
virtual DoubleTab & Domaine_VF::face_normales () inline virtual
Reimplemented in Domaine_VDF, and Domaine_VF_inst.
References face_normales_.
Referenced by Domaine_EF::calculer_Bij_gen(), Domaine_EF_axi::calculer_Bij_gen(), Domaine_PolyMAC_P0::fgrad(), init_dist_paroi_globale(), Domaine_PolyMAC::init_equiv(), Domaine_PolyMAC::init_rf(), Domaine_PolyMAC::M2(), normalized_boundaries_outward_vector(), orientation(), orientation_si_definie(), and Domaine_PolyMAC::W2().
face_normales() [3/3]
virtual const DoubleTab & Domaine_VF::face_normales () const inline virtual
Reimplemented in Domaine_VDF, and Domaine_VF_inst.
References face_normales_.
calculer_face_surfaces()
void Domaine_VF::calculer_face_surfaces (const DoubleVect & surfaces) inline
Referenced by Domaine_ALE::mettre_a_jour().
face_surfaces() [1/2]
virtual const DoubleVect & Domaine_VF::face_surfaces () const inline virtual
Referenced by Champ_Face_PolyMAC::affecter_(), Champ_Fonc_Face_PolyMAC::affecter_(), Op_Div_PolyMAC::ajouter(), Op_Grad_PolyMAC_Face::ajouter(), Source_Robin::ajouter(), Perte_Charge_Singuliere_PolyMAC_Face::ajouter(), Terme_Source_Qdm_Face_PolyMAC::ajouter(), Perte_Charge_Singuliere_VEF_Face::ajouter(), Op_Grad_P0_to_Face::ajouter_blocs(), Op_Grad_VDF_Face::ajouter_blocs(), DP_Impose_PolyMAC_Face::ajouter_blocs(), DP_Impose_VEF_Face::ajouter_blocs(), Op_Diff_VEF_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution(), Source_Masse_Fluide_Dilatable_VEF::ajouter_eq_espece(), Source_Masse_Fluide_Dilatable_VDF::ajouter_projection(), Source_Masse_Fluide_Dilatable_VEF::ajouter_projection(), Op_Diff_VDF_Face_Axi_base::associer(), Op_Dift_VDF_Face_Axi_base::associer(), Evaluateur_PolyMAC::associer_domaines(), Evaluateur_VDF::associer_domaines(), Champ_front_contact_VEF::calcul_grads_locaux(), Transport_Interfaces_FT_Disc::calcul_indicatrice_faces(), Traitement_particulier_NS_temperature_VEF::calcul_temperature(), Perte_Charge_Singuliere::calculate_Q(), Domaine_EF_axi::calculer_Bij_gen(), Navier_Stokes_FT_Disc::calculer_delta_u_interface(), Op_Conv_VDF_base::calculer_dt_local(), Op_Conv_PolyMAC_iterateur_base::calculer_dt_stab(), Op_Conv_VDF_base::calculer_dt_stab(), Op_Grad_VDF_Face::calculer_flux_bords(), Op_Diff_VEFP1NCP1B_Face::calculer_flux_bords_elem(), Op_Diff_VEFP1NCP1B_Face::calculer_flux_bords_som(), Flux_radiatif_VDF::calculer_flux_radiatif(), Navier_Stokes_FT_Disc::calculer_gradient_indicatrice(), Domaine_EF::calculer_h_carre(), Domaine_Poly_base::calculer_h_carre(), Domaine_VEF::calculer_h_carre(), Domaine_PolyMAC::calculer_h_carre(), ParoiVDF_TBLE_LRM::calculer_hyd(), ParoiVDF_TBLE::calculer_hyd(), ParoiVDF_TBLE::calculer_hyd_BiK(), ParoiVDF_TBLE_LRM::calculer_hyd_BiK(), Champ_front_xyz_debit::calculer_normales_et_integrale(), Op_Conv_PolyMAC_iterateur_base::calculer_pour_post(), Op_Conv_VDF_base::calculer_pour_post(), Echange_contact_Correlation_VDF::calculer_Q(), Paroi_std_scal_hyd_EF::calculer_scal(), Paroi_scal_analytique_VEF::calculer_scal(), Paroi_std_scal_hyd_VEF::calculer_scal(), Domaine_PolyMAC::calculer_volumes_entrelaces(), Discretisation_tools::cells_to_faces(), Sortie_libre_pression_moyenne_imposee::completer(), Domaine_DG::compute_mesh_param(), Perte_Charge_Singuliere_PolyMAC_Face::contribuer_a_avec(), Perte_Charge_Singuliere_VEF_Face::contribuer_a_avec(), Op_Div_PolyMAC::contribuer_a_avec(), Op_Grad_PolyMAC_Face::contribuer_a_avec(), Op_Dift_VEF_Face::contribuer_au_second_membre(), Traitement_particulier_NS_CEG::critere_cea_jaea(), Domaine_Poly_base::detecter_faces_non_planes(), Domaine_Poly_base::dist_face_elem0(), Domaine_VEF::dist_face_elem0(), Domaine_Poly_base::dist_face_elem1(), Domaine_VEF::dist_face_elem1(), Domaine_Poly_base::dist_norm(), Domaine_Poly_base::dist_norm_bord(), Domaine_VDF::face_normales(), Domaine_PolyMAC_P0::fgrad(), Milieu_base::fill_section_passage_face(), Champ_Generique_Transformation::get_champ(), Champ_Generique_Tparoi_VEF::get_champ(), Domaine_Cl_PolyMAC::imposer_cond_lim(), Op_VEF_Face::impr(), Loi_Paroi_Nu_Impose_VEF::imprimer_nusselt(), init_dist_paroi_globale(), Domaine_PolyMAC::init_equiv(), Domaine_PolyMAC::init_rf(), Domaine_PolyMAC::init_ve(), Source_Masse_Fluide_Dilatable_base::mettre_a_jour(), Champ_front_pression_from_u::mettre_a_jour(), Champ_front_debit_QC::mettre_a_jour(), Champ_front_debit_QC_fonc_t::mettre_a_jour(), Echange_contact_VDF_FT_Disc::mettre_a_jour(), Estimateur_Aposteriori_P0_VEF::mettre_a_jour(), Courant_maille_Champ_Face::mettre_a_jour(), Reynolds_maille_Champ_Face::mettre_a_jour(), Echange_contact_Correlation_VEF::mettre_a_jour(), Eq_rayo_semi_transp_VDF::modifier_matrice(), AssembleurPVDF_PF::modifier_secmem_vitesse_imposee(), Assembleur_P_VDF::modifier_secmem_vitesse_imposee(), normalized_boundaries_outward_vector(), orientation(), orientation_si_definie(), Domaine_Poly_base::orthocentrer(), AssembleurPVDF_PF::remplir(), Assembleur_P_VDF::remplir(), DP_Impose_PolyMAC_Face::remplir_num_faces(), DP_Impose_VEF_Face::remplir_num_faces(), surface(), Echange_contact_Correlation_VDF::trier_coord(), and Echange_contact_PolyMAC::update_coeffs().
face_surfaces() [2/2]
virtual double Domaine_VF::face_surfaces (int i) const inline virtual
surface()
virtual double Domaine_VF::surface (int i) const inline virtual
References face_surfaces().
Referenced by Operateur_Conv_sensibility_VEF::add_diffusion_scalar_term(), Op_Diff_VEF_Face_Q1::ajouter(), Op_Dift_VEF_Face_Q1::ajouter(), Op_Diff_EF::ajouter_bords(), Op_Dift_EF_Q1::ajouter_bords(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Diff_EF::ajouter_contributions_bords(), Op_Dift_EF_Q1::ajouter_contributions_bords(), Op_Diff_VEF_Anisotrope_Face::contribue_au_second_membre(), Op_Diff_VEF_Face::contribue_au_second_membre(), Op_Diff_VEF_Face_Q1::contribue_au_second_membre(), Op_Diff_VEFP1NCP1B_Face::corriger_div_pour_Cl(), and Op_Diff_VEF_Face_Stab::modifie_pour_Cl().
discretiser()
void Domaine_VF::discretiser () override virtual
Genere les faces construits les frontieres.
Reimplemented from Domaine_dis_base.
Reimplemented in Domaine_PolyMAC, Domaine_PolyMAC_P0, Domaine_PolyMAC_P0P1NC, Domaine_VDF, and Domaine_VEF.
References Faces_32_64< _SIZE_ >::associer_domaine(), Scatter::calculer_renum_items_communs(), creer_faces(), Faces_builder::creer_faces_reeles(), Domaine_dis_base::discretiser(), Domaine_dis_base::domaine(), elem_faces_, Domaine_32_64< _SIZE_ >::faces_joint(), Domaine_32_64< _SIZE_ >::les_elems(), Domaine_32_64< _SIZE_ >::nb_som_tot(), reordonner(), Domaine_32_64< _SIZE_ >::type_elem(), Elem_geom_base_32_64< _SIZE_ >::type_face(), and Faces_32_64< _SIZE_ >::typer().
Referenced by Domaine_EF::discretiser(), Domaine_Poly_base::discretiser(), Domaine_VDF::discretiser(), Domaine_VEF::discretiser(), and Discretiser_domaine::interpreter_().
discretiser_no_face()
void Domaine_VF::discretiser_no_face () override virtual
Implements Domaine_dis_base.
References Domaine_32_64< _SIZE_ >::calculer_volumes(), Domaine_dis_base::domaine(), inverse_volumes(), typer_elem(), and volumes().
typer_discretiser_ss_domaine()
void Domaine_VF::typer_discretiser_ss_domaine (int i) override virtual
Implements Domaine_dis_base.
References Domaine_dis_base::domaine(), Domaine_dis_base::les_sous_domaines_dis, and Domaine_32_64< _SIZE_ >::ss_domaine().
infobord()
void Domaine_VF::infobord ()
References Faces_32_64< _SIZE_ >::associer_domaine(), Faces_32_64< _SIZE_ >::calculer_surfaces(), Domaine_dis_base::domaine(), Domaine_32_64< _SIZE_ >::faces_bord(), Domaine_32_64< _SIZE_ >::faces_raccord(), Objet_U::le_nom(), Domaine_base::le_nom(), Process::mp_sum(), Bords_32_64< _SIZE_ >::nb_bords(), Faces_32_64< _SIZE_ >::nb_faces(), and Raccords_32_64< _SIZE_ >::nb_raccords().
info_elem_som()
void Domaine_VF::info_elem_som ()
References Objet_U::dimension, Domaine_dis_base::domaine(), face_voisins(), Domaine_32_64< _SIZE_ >::faces_bord(), Domaine_32_64< _SIZE_ >::faces_raccord(), TRUSTVect< _TYPE_, _SIZE_ >::get_md_vector(), DeviceMemory::internal_items_size_, Objet_U::le_nom(), Domaine_base::le_nom(), Domaine_32_64< _SIZE_ >::les_elems(), Domaine_32_64< _SIZE_ >::les_sommets(), Process::mp_sum(), Bords_32_64< _SIZE_ >::nb_bords(), nb_faces(), MD_Vector_base::nb_items_seq_tot(), Raccords_32_64< _SIZE_ >::nb_raccords(), and premiere_face_int().
marquer_faces_double_contrib()
void Domaine_VF::marquer_faces_double_contrib (const Conds_lim & conds_lim)
References est_face_bord_, faces_doubles_, Cond_lim_base::frontiere_dis(), joint(), Joint_32_64< _SIZE_ >::joint_item(), Process::Journal(), Front_VF::nb_faces(), Front_VF::nb_faces_tot(), nb_joints(), Front_VF::num_face(), and Front_VF::num_premiere_face().
Referenced by Domaine_EF::modifier_pour_Cl(), Domaine_Poly_base::modifier_pour_Cl(), modifier_pour_Cl(), Domaine_PolyMAC::modifier_pour_Cl(), Domaine_VEF::modifier_pour_Cl(), and Domaine_VDF::modifier_pour_Cl().
typer_elem()
virtual void Domaine_VF::typer_elem (Domaine &) inline virtual
Reimplemented in Domaine_VEF, Domaine_EF, and Domaine_Poly_base.
Referenced by discretiser_no_face().
remplir_face_voisins_fictifs()
void Domaine_VF::remplir_face_voisins_fictifs (const Domaine_Cl_dis_base &) virtual
References Process::exit(), and Objet_U::que_suis_je().
creer_faces()
Faces * Domaine_VF::creer_faces () virtual
renvoie new(Faces) ! elle est surchargee par Domaine_VDF par ex.
Reimplemented in Domaine_VDF.
Referenced by discretiser().
reordonner()
void Domaine_VF::reordonner (Faces &) virtual
cette methode ne fait rien elle est surchargee par Domaine_VDF par ex.
Reimplemented in Domaine_EF, Domaine_Poly_base, Domaine_VDF, and Domaine_VEF.
Referenced by discretiser().
renumeroter()
void Domaine_VF::renumeroter (Faces & les_faces)
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Domaine_dis_base::domaine(), elem_faces_, Domaine_32_64< _SIZE_ >::faces_joint(), Faces_32_64< _SIZE_ >::les_sommets(), Faces_32_64< _SIZE_ >::nb_faces(), Domaine_32_64< _SIZE_ >::nb_faces_frontiere(), nb_faces_std_, TRUSTArray< _TYPE_, _SIZE_ >::ordonne_array(), rang_elem_non_std_, Joint_32_64< _SIZE_ >::set_joint_item(), TRUSTVect< _TYPE_, _SIZE_ >::size(), TRUST_List< _CLASSE_ >::size(), and Faces_32_64< _SIZE_ >::voisins().
Referenced by Domaine_EF::reordonner(), and Domaine_Poly_base::reordonner().
nb_joints()
int Domaine_VF::nb_joints () const inline
References Domaine_dis_base::domaine(), and Domaine_32_64< _SIZE_ >::nb_joints().
Referenced by Extraire_plan::interpreter_(), marquer_faces_double_contrib(), Domaine_VDF::reordonner(), and Collision_Model_FT_base::set_LC_zones().
premiere_face_int()
int Domaine_VF::premiere_face_int () const inline
une face est interne ssi elle separe deux elements.
renvoie le numero de la premiere face interne.
References nb_faces_bord().
Referenced by Operateur_Conv_sensibility_VEF::add_diffusion_scalar_term(), Operateur_Conv_sensibility_VEF::add_diffusion_term(), Champ_Face_VDF::affecter_(), Champ_Fonc_Face_VDF::affecter_(), Op_Div_EF::ajouter(), Op_Div_PolyMAC::ajouter(), Op_Grad_PolyMAC_Face::ajouter(), Op_Conv_EF_VEF_P1NC::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Diff_VEF_Face_Q1::ajouter(), Op_Dift_VEF_Face_Q1::ajouter(), Op_Rot_VEFP1B::ajouter(), Source_Reaction_Particules_VDF::ajouter(), Source_Reaction_Particules_VEF::ajouter(), SourceFiltree_FT_disc_VEF_P1NC::ajouter(), Source_Transport_Flux_Chaleur_Turbulente_VDF_Face::ajouter(), Terme_Source_Qdm_Face_PolyMAC::ajouter(), Perte_Charge_Reguliere_VEF_P1NC::ajouter(), Terme_Source_Rappel_T_VEF_Face::ajouter(), Perte_Charge_Reguliere_VDF_Face::ajouter_(), Tenseur_Reynolds_Externe_VDF_Face::ajouter_blocs(), Op_Grad_P0_to_Face::ajouter_blocs(), Op_Grad_VDF_Face::ajouter_blocs(), Terme_Source_Canal_perio_VDF_Face::ajouter_blocs(), Force_Centrifuge_VDF_Face_Axi::ajouter_blocs(), Perte_Charge_Singuliere_VDF_Face::ajouter_blocs(), Terme_Boussinesq_VDF_Face::ajouter_blocs(), Terme_Source_Acceleration_VDF_Face::ajouter_blocs(), Terme_Source_Coriolis_VDF_Face::ajouter_blocs(), Terme_Source_inc_th_VDF_Face::ajouter_blocs(), Terme_Source_inc_VDF_Face::ajouter_blocs(), Terme_Source_Qdm_VDF_Face::ajouter_blocs(), Couplage_Parietal_PolyMAC_helper::ajouter_blocs(), Op_Diff_EF::ajouter_bords(), Op_Dift_EF_Q1::ajouter_bords(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Face::ajouter_cas_vectoriel(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution(), Op_Diff_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Face_Q1::ajouter_contribution(), Op_Diff_VEF_Face_Stab::ajouter_contribution(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution_elem(), Iterateur_PolyMAC_Elem< _TYPE_ >::ajouter_contribution_interne(), Iterateur_PolyMAC_Elem< _TYPE_ >::ajouter_contribution_interne_vitesse(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face_Stab::ajouter_contribution_multi_scalaire(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution_som(), Operateur_Conv_sensibility_VEF::ajouter_conv_term(), Iterateur_PolyMAC_Elem< _TYPE_ >::ajouter_interne(), Op_Conv_ALE_VEF::ajouterALE(), Tensors_Computation_VEF::antisym_loop_internal_faces(), Masse_VDF_Face::appliquer_impl(), Masse_VEF_P1NC::appliquer_impl(), BilanQdmVEF::bilan_energie(), BilanQdmVEF::bilan_qdm(), Modele_Jones_Launder_VDF::Calcul_D(), Modele_Jones_Launder_Thermique_VDF::Calcul_D(), Modele_Jones_Launder_VDF::Calcul_D_BiK(), Modele_Jones_Launder_VEF::Calcul_E(), Modele_Launder_Sharma_VEF::Calcul_E(), Modele_Jones_Launder_Thermique_VDF::Calcul_E(), Traitement_particulier_NS_THI_VEF::calcul_Ec_spatial(), Modele_EASM_Baglietto_VEF::Calcul_F1(), Modele_EASM_Baglietto_VEF::Calcul_F1_BiK(), Modele_EASM_Baglietto_VEF::Calcul_Fmu(), Modele_EASM_Baglietto_VEF::Calcul_Fmu_BiK(), Traitement_particulier_NS_THI_VEF::calcul_moyenne(), Traitement_particulier_NS_THI_VDF::calcul_skewness_ordre_2(), Modele_Lam_Bremhorst_VEF::calcul_tenseur_face(), Modele_Shih_Zhu_Lumley_VEF::calcul_tenseur_face(), Calcul_Production_K_VEF::calcul_tenseur_face(), Traitement_particulier_NS_THI_VEF::calcul_vitesse_moyenne(), Op_Conv_ALE_VEF::calculateALEMeshVelocityGradientOnFaces(), Source_Con_Phase_field::calculer_div_alpha_rho_gradC(), Op_Conv_VDF_base::calculer_dt_local(), Op_Conv_VEF_base::calculer_dt_local(), Op_Conv_ALE_VEF::calculer_dt_stab(), Operateur_Conv_sensibility_VEF::calculer_dt_stab(), Op_Conv_PolyMAC_iterateur_base::calculer_dt_stab(), Op_Conv_VDF_base::calculer_dt_stab(), Op_Conv_VEF_base::calculer_dt_stab(), Traitement_particulier_NS_EC::calculer_Ec(), Op_Grad_VEF_P1B_Face::calculer_flux_bords(), EDO_Pression_th_VDF::calculer_grad(), EDO_Pression_th_VEF::calculer_grad(), Op_Conv_PolyMAC_iterateur_base::calculer_pour_post(), Op_Conv_VDF_base::calculer_pour_post(), Op_Conv_VEF_base::calculer_pour_post(), Source_Transport_Fluctuation_Temperature_VDF_Elem::calculer_Prod_uteta_T(), Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::calculer_Prod_uteta_T(), Source_Transport_Fluctuation_Temperature_W_VDF_Elem::calculer_Prod_uteta_T(), Loi_Paroi_Nu_Impose_VEF::calculer_scal(), Calcul_Production_K_VEF::calculer_terme_production_K(), Calcul_Production_K_VEF::calculer_terme_production_K_BiK(), Calcul_Production_K_VEF::calculer_terme_production_K_EASM(), Calcul_Production_K_VDF::calculer_u_conc(), Calcul_Production_K_VDF::calculer_u_teta(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_W_VDF_Elem::calculer_u_teta_W(), Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::calculer_u_teta_W(), Source_Transport_Fluctuation_Temperature_W_VDF_Elem::calculer_u_teta_W(), Domaine_EF::calculer_volumes_entrelaces(), Domaine_VDF::calculer_volumes_entrelaces(), calculer_xgr(), Discretisation_tools::cells_to_faces(), AssembleurPVDF_PF::construire(), Assembleur_P_VDF::construire(), Op_Dift_VEF_Face_Q1::contribuer_a_avec(), Perte_Charge_Reguliere_VEF_P1NC::contribuer_a_avec(), Op_Grad_PolyMAC_Face::contribuer_a_avec(), Iterateur_PolyMAC_Elem< _TYPE_ >::contribuer_au_second_membre_interne(), Navier_Stokes_phase_field::derivee_en_temps_inco(), Op_PolyMAC_Elem::dimensionner(), Source_Con_Phase_field::div_kappa_grad(), face_voisins_reel_fictif(), fbord(), Champ_P1NC_implementation::filtrer_resu(), Champ_Q1NC::gradient(), Iterateur_PolyMAC_Elem< _TYPE_ >::impr(), info_elem_som(), Sonde::initialiser(), Op_Diff_VEFP1NCP1B_Face::liste_face(), Source_Qdm_VDF_Phase_field::methode_1(), Source_Qdm_VDF_Phase_field::methode_2(), Source_Qdm_VDF_Phase_field::methode_3(), Source_Qdm_VDF_Phase_field::methode_4(), Estimateur_Aposteriori_P0_VEF::mettre_a_jour(), AssembleurPVDF_PF::remplir(), Assembleur_P_VDF::remplir(), Navier_Stokes_phase_field::rho_aux_faces(), Op_Diff_VEFP1NCP1B_Face::test(), and xv_bord().
nb_faces()
int Domaine_VF::nb_faces () const inline
renvoie le nombre global de faces.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), and face_sommets_.
Referenced by Navier_Stokes_phase_field::_aff_donnee_P1(), Operateur_Conv_sensibility_VEF::add_diffusion_scalar_term(), Operateur_Conv_sensibility_VEF::add_diffusion_term(), Champ_Face_PolyMAC::affecter_(), Champ_Fonc_Face_PolyMAC::affecter_(), Champ_Face_VDF::affecter_(), Champ_Fonc_Face_VDF::affecter_(), Champ_P1NC::affecter_(), Op_Diff_VDF_base::ajoute_terme_pour_axi(), Op_Dift_VDF_base::ajoute_terme_pour_axi_turb(), Op_Div_PolyMAC::ajouter(), Op_Grad_PolyMAC_Face::ajouter(), Op_Conv_EF_VEF_P1NC::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Conv_Vort_VEF_Face::ajouter(), Op_Diff_VEF_Face_Q1::ajouter(), Op_Dift_VEF_Face_Q1::ajouter(), Op_Rot_VEFP1B::ajouter(), Op_Diff_VEF_Face_Penalise::ajouter(), Source_Reaction_Particules_VDF::ajouter(), Source_Reaction_Particules_VEF::ajouter(), SourceFiltree_FT_disc_VEF_P1NC::ajouter(), Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::ajouter(), Source_Transport_Fluctuation_Temperature_W_VDF_Elem::ajouter(), Source_Transport_Flux_Chaleur_Turbulente_VDF_Face::ajouter(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_VEF_Face::ajouter(), Source_Transport_K_Eps_Bas_Reynolds_VEF_Face::ajouter(), Perte_Charge_Singuliere_PolyMAC_Face::ajouter(), Terme_Source_Qdm_Face_PolyMAC::ajouter(), Terme_Source_Canal_perio_VEF_P1NC::ajouter(), Terme_Source_Canal_RANS_LES_VEF_Face::ajouter(), Perte_Charge_VEF::ajouter(), Terme_Boussinesq_VEF_Face::ajouter(), Terme_Source_Qdm_lambdaup_VEF_Face::ajouter(), Terme_Source_Rappel_T_VEF_Face::ajouter(), Source_rayo_semi_transp_VEF_P1NC::ajouter(), Tenseur_Reynolds_Externe_VDF_Face::ajouter_blocs(), Op_Grad_P0_to_Face::ajouter_blocs(), Op_Grad_VDF_Face::ajouter_blocs(), Terme_Source_Canal_perio_VDF_Face::ajouter_blocs(), Terme_Source_Canal_RANS_LES_VDF_Face::ajouter_blocs(), Force_Centrifuge_VDF_Face_Axi::ajouter_blocs(), Terme_Boussinesq_VDF_Face::ajouter_blocs(), Terme_Source_Acceleration_VDF_Face::ajouter_blocs(), Terme_Source_Coriolis_VDF_Face::ajouter_blocs(), Terme_Source_inc_th_VDF_Face::ajouter_blocs(), Terme_Source_inc_VDF_Face::ajouter_blocs(), Terme_Source_Qdm_VDF_Face::ajouter_blocs(), Couplage_Parietal_PolyMAC_helper::ajouter_blocs(), DP_Impose_PolyMAC_Face::ajouter_blocs(), DP_Impose_VEF_Face::ajouter_blocs(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Face::ajouter_cas_vectoriel(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution(), Op_Diff_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Face_Q1::ajouter_contribution(), Op_Diff_VEF_Face_Stab::ajouter_contribution(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution_elem(), Iterateur_PolyMAC_Elem< _TYPE_ >::ajouter_contribution_interne(), Iterateur_PolyMAC_Elem< _TYPE_ >::ajouter_contribution_interne_vitesse(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face_Stab::ajouter_contribution_multi_scalaire(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution_som(), Operateur_Conv_sensibility_VEF::ajouter_conv_term(), Source_Masse_Fluide_Dilatable_VEF::ajouter_eq_espece(), Iterateur_PolyMAC_Elem< _TYPE_ >::ajouter_interne(), Operateur_Conv_sensibility_VEF::ajouter_Lsensibility_state_Amont(), Operateur_Conv_sensibility_VEF::ajouter_Lstate_sensibility_Amont(), Source_Masse_Fluide_Dilatable_VDF::ajouter_projection(), Source_Masse_Fluide_Dilatable_VEF::ajouter_projection(), Op_Conv_ALE_VEF::ajouterALE(), Tensors_Computation_VEF::antisym_loop_internal_faces(), Masse_PolyMAC_Face::appliquer_impl(), Masse_VDF_Face::appliquer_impl(), Masse_VEF_P1NC::appliquer_impl(), Parcours_interface::associer_domaine_dis(), Traitement_particulier_NS_THI_VEF::calcul_correlations(), Modele_Jones_Launder_VDF::Calcul_D(), Modele_Jones_Launder_VEF::Calcul_D(), Modele_Launder_Sharma_VEF::Calcul_D(), Modele_Jones_Launder_Thermique_VDF::Calcul_D(), Modele_Jones_Launder_VDF::Calcul_D_BiK(), Modele_Jones_Launder_VEF::Calcul_D_BiK(), Modele_Launder_Sharma_VEF::Calcul_D_BiK(), Modele_Jones_Launder_VEF::Calcul_E(), Modele_Launder_Sharma_VEF::Calcul_E(), Modele_Jones_Launder_Thermique_VDF::Calcul_E(), Traitement_particulier_NS_THI_VEF::calcul_Ec_spatial(), Modele_EASM_Baglietto_VEF::Calcul_F1(), Modele_Jones_Launder_VEF::Calcul_F1(), Modele_Lam_Bremhorst_VEF::Calcul_F1(), Modele_Launder_Sharma_VEF::Calcul_F1(), Modele_standard_KEps_VEF::Calcul_F1(), Modele_EASM_Baglietto_VEF::Calcul_F1_BiK(), Modele_Jones_Launder_VEF::Calcul_F1_BiK(), Modele_Lam_Bremhorst_VEF::Calcul_F1_BiK(), Modele_Launder_Sharma_VEF::Calcul_F1_BiK(), Modele_standard_KEps_VEF::Calcul_F1_BiK(), Modele_EASM_Baglietto_VEF::Calcul_F2(), Modele_Jones_Launder_VEF::Calcul_F2(), Modele_Lam_Bremhorst_VEF::Calcul_F2(), Modele_Launder_Sharma_VEF::Calcul_F2(), Modele_standard_KEps_VEF::Calcul_F2(), Modele_EASM_Baglietto_VEF::Calcul_F2_BiK(), Modele_Jones_Launder_VEF::Calcul_F2_BiK(), Modele_Lam_Bremhorst_VEF::Calcul_F2_BiK(), Modele_Launder_Sharma_VEF::Calcul_F2_BiK(), Modele_standard_KEps_VEF::Calcul_F2_BiK(), Modele_Jones_Launder_VEF::Calcul_Fmu(), Modele_Lam_Bremhorst_VEF::Calcul_Fmu(), Modele_Launder_Sharma_VEF::Calcul_Fmu(), Modele_standard_KEps_VEF::Calcul_Fmu(), Modele_EASM_Baglietto_VEF::Calcul_Fmu(), Modele_EASM_Baglietto_VEF::Calcul_Fmu_BiK(), Modele_Jones_Launder_VEF::Calcul_Fmu_BiK(), Modele_Lam_Bremhorst_VEF::Calcul_Fmu_BiK(), Modele_Launder_Sharma_VEF::Calcul_Fmu_BiK(), Modele_standard_KEps_VEF::Calcul_Fmu_BiK(), Traitement_particulier_NS_THI_VEF::calcul_moyenne(), Traitement_particulier_NS_THI_VEF::calcul_spectre(), Traitement_particulier_NS_THI_VEF_new::calcul_spectre(), Traitement_particulier_NS_THI_VDF::calcul_spectre_operateur(), Modele_Lam_Bremhorst_VEF::calcul_tenseur_face(), Modele_Shih_Zhu_Lumley_VEF::calcul_tenseur_face(), Calcul_Production_K_VEF::calcul_tenseur_face(), Traitement_particulier_NS_THI_VEF::calcul_vitesse_moyenne(), Op_Conv_ALE_VEF::calculateALEMeshVelocityGradientOnFaces(), Terme_Source_Constituant_Vortex_VEF_Face::calculer(), Navier_Stokes_FT_Disc::calculer_champ_forces_superficielles(), Navier_Stokes_FT_Disc::calculer_delta_u_interface(), Source_Con_Phase_field::calculer_div_alpha_rho_gradC(), Op_Conv_VDF_base::calculer_dt_local(), Op_Conv_VEF_base::calculer_dt_local(), Op_Conv_ALE_VEF::calculer_dt_stab(), Operateur_Conv_sensibility_VEF::calculer_dt_stab(), Op_Conv_PolyMAC_iterateur_base::calculer_dt_stab(), Op_Conv_VDF_base::calculer_dt_stab(), Op_Conv_VEF_base::calculer_dt_stab(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab_som(), Traitement_particulier_NS_EC::calculer_Ec(), Modele_turbulence_hyd_LES_VEF::calculer_fonction_structure(), EDO_Pression_th_VDF::calculer_grad(), EDO_Pression_th_VEF::calculer_grad(), Domaine_EF::calculer_h_carre(), Domaine_PolyMAC::calculer_h_carre(), ParoiVDF_TBLE_LRM::calculer_hyd(), ParoiVDF_TBLE::calculer_hyd(), ParoiVDF_TBLE::calculer_hyd_BiK(), ParoiVDF_TBLE_LRM::calculer_hyd_BiK(), Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_nut(), Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_vitesse(), Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_vitesse_rho_mu(), Op_Conv_PolyMAC_iterateur_base::calculer_pour_post(), Op_Conv_VDF_base::calculer_pour_post(), Op_Conv_VEF_base::calculer_pour_post(), Source_Transport_Fluctuation_Temperature_VDF_Elem::calculer_Prod_uteta_T(), Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::calculer_Prod_uteta_T(), Source_Transport_Fluctuation_Temperature_W_VDF_Elem::calculer_Prod_uteta_T(), Modele_turbulence_hyd_LES_Smago_filtre_VEF::calculer_S_barre(), Calcul_Production_K_VDF::calculer_terme_destruction_K(), Calcul_Production_K_VEF::calculer_terme_destruction_K_gen(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_W_VDF_Elem::calculer_terme_destruction_K_W(), Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::calculer_terme_destruction_K_W(), Source_Transport_Fluctuation_Temperature_W_VDF_Elem::calculer_terme_destruction_K_W(), Calcul_Production_K_VEF::calculer_terme_production_K(), Calcul_Production_K_VEF::calculer_terme_production_K_BiK(), Calcul_Production_K_VEF::calculer_terme_production_K_EASM(), Calcul_Production_K_VDF::calculer_u_conc(), Calcul_Production_K_VDF::calculer_u_teta(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_W_VDF_Elem::calculer_u_teta_W(), Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::calculer_u_teta_W(), Source_Transport_Fluctuation_Temperature_W_VDF_Elem::calculer_u_teta_W(), Modele_turbulence_hyd_LES_VEF::calculer_viscosite_turbulente(), Domaine_ALE::calculer_vitesse(), Domaine_EF::calculer_volumes_entrelaces(), Domaine_VDF::calculer_volumes_entrelaces(), Domaine_PolyMAC::calculer_volumes_entrelaces(), Domaine_PolyMAC_P0P1NC::calculer_volumes_entrelaces(), calculer_xgr(), Discretisation_tools::cells_to_faces(), Traitement_particulier_NS_THI_VDF::ch_vit_pour_fft(), Traitement_particulier_NS_THI_VDF::ch_vit_pour_fft_operateur(), Op_Diff_VEFP1NCP1B_Face::coeff_matrice_som(), Op_Diff_VEFP1NCP1B_Face::coeff_matrice_som_CL(), Op_Diff_VEFP1NCP1B_Face::coeff_matrice_som_perio(), Op_Diff_VEFP1NCP1B_Face::coeff_matrice_som_symetrie(), Domaine_Cl_VDF::completer(), Traitement_particulier_NS_THI_VEF::conservation_Ec(), construire_face_virt_pe_num(), Perte_Charge_Singuliere_PolyMAC_Face::contribuer_a_avec(), Op_Dift_VEF_Face_Q1::contribuer_a_avec(), Perte_Charge_VEF::contribuer_a_avec(), Op_Div_PolyMAC::contribuer_a_avec(), Op_Grad_PolyMAC_Face::contribuer_a_avec(), Op_Dift_VEF_Face::contribuer_au_second_membre(), Iterateur_PolyMAC_Elem< _TYPE_ >::contribuer_au_second_membre_interne(), VDF_discretisation::courant_maille(), Op_Div_VEFP1B_Elem::degres_liberte(), Navier_Stokes_phase_field::derivee_en_temps_inco(), Domaine_Poly_base::detecter_faces_non_planes(), Traitement_particulier_NS_THI_VEF::determine_tab_fft_VEF_3D(), Op_PolyMAC_Elem::dimensionner(), Op_VEF_Face::dimensionner(), Op_Grad_PolyMAC_Face::dimensionner(), Op_Div_PolyMAC::dimensionner(), Op_PolyMAC_Elem::dimensionner_bloc_vitesse(), Op_Grad_VDF_Face::dimensionner_blocs(), Perte_Charge_Singuliere_VDF_Face::dimensionner_blocs(), DP_Impose_VEF_Face::dimensionner_blocs(), Domaine_EF::discretiser(), Domaine_Poly_base::discretiser(), Domaine_VEF::discretiser(), PolyMAC_discretisation::discretiser_champ(), PolyMAC_P0P1NC_discretisation::discretiser_champ(), VDF_discretisation::discretiser_champ(), Source_Con_Phase_field::div_kappa_grad(), Maillage_FT_Disc::echanger_sommets_PE(), est_une_face_virt_bord(), Champ_val_tot_sur_vol_VEF::eval_contrib_loc(), face_numero_bord(), fbord(), Champ_Fonc_Face_PolyMAC::fixer_nb_valeurs_nodales(), Champ_Q1NC::gradient(), Champ_P1NC_implementation::imprime_P1NC(), info_elem_som(), Terme_Source_Canal_RANS_LES_VDF_Face::init(), Terme_Source_Canal_RANS_LES_VEF_Face::init(), Traitement_particulier_NS_THI_VEF::init_calc_spectre(), Traitement_particulier_NS_Profils_VDF::init_calcul_moyenne(), Terme_Source_Canal_RANS_LES_VDF_Face::init_calcul_moyenne_spat(), init_dist_paroi_globale(), Modele_turbulence_hyd_K_Omega::init_F1_F2_enstrophy(), Domaine_PolyMAC::init_m2solv(), Domaine_PolyMAC::init_virt_ef_map(), Modele_Shih_Zhu_Lumley_VEF::Initialisation(), Domaine_ALE::initialiser(), Champ_Fonc_Interp::initialiser(), Imprimer_Fichiers_RANS_VEF::interpreter(), Extraire_domaine::interpreter_(), Extraire_plan::interpreter_(), Traitement_particulier_NS_Brech_VEF::lire(), EDO_Pression_th_VEF::masse_totale(), Source_Qdm_VDF_Phase_field::methode_1(), Source_Qdm_VDF_Phase_field::methode_2(), Source_Qdm_VDF_Phase_field::methode_3(), Source_Qdm_VDF_Phase_field::methode_4(), Convection_Diffusion_Concentration_FT_Disc::mettre_a_jour(), Convection_Diffusion_Concentration_Turbulent_FT_Disc::mettre_a_jour(), Domaine_ALE::mettre_a_jour(), Courant_maille_Champ_Face::mettre_a_jour(), Reynolds_maille_Champ_Face::mettre_a_jour(), Terme_Source_Canal_RANS_LES_VDF_Face::mettre_a_jour(), Terme_Source_Canal_RANS_LES_VEF_Face::mettre_a_jour(), Domaine_EF::modifier_pour_Cl(), Domaine_Poly_base::modifier_pour_Cl(), Domaine_PolyMAC::modifier_pour_Cl(), Domaine_VEF::modifier_pour_Cl(), Terme_Source_Canal_RANS_LES_VDF_Face::moy_spat(), Convection_Diffusion_Concentration_FT_Disc::multiplier_valeurs_faces(), Convection_Diffusion_Concentration_Turbulent_FT_Disc::multiplier_valeurs_faces(), Eq_rayo_semi_transp_VEF::nb_colonnes(), nb_faces_internes(), Domaine_VEF::nb_faces_non_std(), Champ_Face_PolyMAC_P0P1NC::nb_valeurs_nodales(), Terme_Source_Qdm_lambdaup_VEF_Face::norme_L2(), Terme_Source_Canal_RANS_LES_VDF_Face::norme_vit(), Domaine_VEF::premiere_face_std(), printOn(), Champ_Don_Face_lu::readOn(), Champ_P1NC_implementation::remplir_coord_noeuds(), Champ_Q1NC_implementation::remplir_coord_noeuds(), Champ_Face_VDF_implementation::remplir_coord_noeuds_et_polys(), Champ_P1NC_implementation::remplir_coord_noeuds_et_polys(), Champ_Q1NC_implementation::remplir_coord_noeuds_et_polys(), remplir_face_numero_bord(), Op_Conv_EF_VEF_P1NC_Stab::remplir_fluent(), Op_Conv_Muscl_New_VEF_Face::remplir_fluent(), Op_Conv_ALE_VEF::remplir_fluent_ALEincluded(), Iterateur_Source_VEF_Face< _TYPE_ >::remplir_volumes_cl_dirichlet(), Traitement_particulier_NS_canal_VEF::remplir_Y(), Traitement_particulier_NS_THI_VEF_new::renorm_Ec(), Domaine_VDF::reordonner(), Eq_rayo_semi_transp_VEF::resoudre(), VDF_discretisation::reynolds_maille(), Navier_Stokes_phase_field::rho_aux_faces(), Traitement_particulier_NS_THI_VEF::sorties_globales(), Terme_Source_Canal_perio::source_convection_diffusion(), Traitement_particulier_NS_THI_VEF::suppression_vitesse_moyenne(), Op_Diff_VEFP1NCP1B_Face::test(), Echange_contact_PolyMAC::update_coeffs(), and Echange_contact_PolyMAC::update_delta().
nb_faces_tot()
int Domaine_VF::nb_faces_tot () const inline
renvoie le nombre total de faces.
C'est-a-dire faces reelles + faces virtuelles
References TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), and face_sommets_.
Referenced by Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Diff_VEF_Face_Stab::ajouter_antidiffusion(), Op_Diff_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution_som(), Operateur_Conv_sensibility_VEF::ajouter_conv_term(), Operateur_Conv_sensibility_VEF::ajouter_Lsensibility_state_Amont(), Operateur_Conv_sensibility_VEF::ajouter_Lstate_sensibility_Amont(), Source_Masse_Fluide_Dilatable_VEF::ajouter_projection(), Op_Conv_ALE_VEF::ajouterALE(), Masse_PolyMAC_Face::appliquer_impl(), Eq_rayo_semi_transp_VEF::assembler_matrice(), BilanQdmVEF::bilan_energie(), BilanQdmVEF::bilan_qdm(), Modele_Jones_Launder_VDF::Calcul_E(), Champ_Q1_EF::calcul_y_plus(), Champ_P1NC::calcul_y_plus_diphasique(), Champ_Face_VDF::calcul_y_plus_diphasique(), Milieu_base::calculate_face_hydr_diam(), Milieu_base::calculate_face_porosity(), Op_Conv_ALE_VEF::calculateALEjacobian(), Op_Conv_Muscl_New_VEF_Face::calculer_dt_stab(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab(), Paroi_std_hyd_VEF::calculer_hyd(), Paroi_std_hyd_VEF::calculer_hyd_BiK(), Op_Diff_VEF_Face_Stab::calculer_max(), Op_Diff_VEF_Face_Stab::calculer_min(), ParoiVEF_TBLE_scal::calculer_scal(), Calcul_Production_K_VEF::calculer_terme_destruction_K_gen(), Modele_turbulence_hyd_LES_VEF::calculer_viscosite_turbulente(), Discretisation_tools::cells_to_faces(), Op_Diff_VEF_Face_Stab::completer(), Op_Dift_Stab_VEF_Face::completer(), Calcul_Production_K_VEF::compute_utheta_nbConsti_gt_1_nbCompo_eq_0(), Calcul_Production_K_VEF::compute_utheta_nbConsti_gt_1_nbCompo_eq_1(), Calcul_Production_K_VEF::compute_utheta_nbConsti_gt_1_nbCompo_gt_1(), Calcul_Production_K_VEF::compute_utheta_nbConsti_le_1_nbCompo_eq_0(), Calcul_Production_K_VEF::compute_utheta_nbConsti_le_1_nbCompo_eq_1(), Calcul_Production_K_VEF::compute_utheta_nbConsti_le_1_nbCompo_gt_1(), construire_face_virt_pe_num(), construire_num_fac_loc(), Op_Div_VEFP1B_Elem::degres_liberte(), Op_PolyMAC_Elem::dimensionner(), Op_VDF_Face::dimensionner(), Op_VEF_Face::dimensionner(), Op_Grad_PolyMAC_Face::dimensionner(), Op_Diff_VEFP1NCP1B_Face::dimensionner(), Op_Div_PolyMAC::dimensionner(), Op_PolyMAC_Elem::dimensionner_bloc_vitesse(), Perte_Charge_Singuliere_VDF_Face::dimensionner_blocs(), DP_Impose_VEF_Face::dimensionner_blocs(), Domaine_EF::discretiser(), Domaine_Poly_base::discretiser(), Domaine_VEF::discretiser(), Viscosite_turbulente_WALE::eddy_viscosity(), Discretisation_tools::faces_to_cells(), Domaine_PolyMAC::init_equiv(), Domaine_PolyMAC::init_m2solv(), Domaine_PolyMAC::init_rf(), Domaine_PolyMAC_P0::init_stencils(), Domaine_PolyMAC::init_virt_ef_map(), Domaine_PolyMAC::init_we(), Domaine_ALE::initialiser(), Imprimer_Fichiers_RANS_VDF::interpreter(), Op_Diff_VEFP1NCP1B_Face::isFaceOfSymetry(), Op_Diff_VEFP1NCP1B_Face::liste_face(), Convection_Diffusion_Concentration_FT_Disc::marquer_faces_sous_domaine(), Convection_Diffusion_Concentration_Turbulent_FT_Disc::marquer_faces_sous_domaine(), Estimateur_Aposteriori_P0_VEF::mettre_a_jour(), Eq_rayo_semi_transp_VEF::nb_colonnes_tot(), Transport_Interfaces_FT_Disc::ramasse_miettes(), Champ_Face_VDF_implementation::remplir_coord_noeuds(), Perte_Charge_Reguliere_VEF_P1NC::remplir_num_faces(), Champ_Fonc_Face_PolyMAC::valeur_aux_elems(), Champ_Face_PolyMAC_P0::valeur_aux_elems_compo(), Champ_P1NC_implementation::valeur_aux_sommets(), and Champ_P1NC_implementation::valeur_aux_sommets_compo().
nb_som_face()
int Domaine_VF::nb_som_face () const inline
renvoie le nombre de sommets par face.
Rque : on a suppose que toutes les faces avait le meme nombre de sommet ce qui exclue des elements comme le prisme.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), and face_sommets_.
Referenced by Op_Div_EF::ajouter(), Op_Grad_EF::ajouter_bord(), Op_Diff_EF::ajouter_bords(), Op_Dift_EF_Q1::ajouter_bords(), Op_Diff_EF::ajouter_contributions_bords(), Op_Dift_EF_Q1::ajouter_contributions_bords(), Source_Masse_Fluide_Dilatable_VEF::ajouter_projection(), Parcours_interface::associer_domaine_dis(), Champ_Q1_EF::calcul_y_plus(), Domaine_EF::calculer_Bij(), Domaine_EF::calculer_Bij_gen(), Domaine_EF_axi::calculer_Bij_gen(), Op_Diff_VEFP1NCP1B_Face::calculer_divergence_som(), Op_Diff_VEFP1NCP1B_Face::calculer_flux_bords_som(), Op_Diff_VEFP1NCP1B_Face::calculer_gradient_som(), Paroi_loi_WW_hyd_EF::calculer_hyd(), Paroi_std_hyd_EF::calculer_hyd(), Domaine_ALE::calculer_vitesse(), Op_EF_base::dimensionner(), Op_Diff_VEFP1NCP1B_Face::gradient_som_CL(), init_dist_paroi_globale(), Domaine_ALE::initialiser(), Domaine_ALE::mettre_a_jour(), Op_Diff_VEF_Face_Penalise::signe(), Champ_P1NC_implementation::valeur_aux_sommets(), and Champ_P1NC_implementation::valeur_aux_sommets_compo().
nb_faces_bord()
int Domaine_VF::nb_faces_bord () const inline
renvoie le nombre de faces sur lesquelles sont appliquees les conditions limites :
bords, raccords, plaques.
References Domaine_dis_base::domaine(), and Domaine_32_64< _SIZE_ >::nb_faces_frontiere().
Referenced by Operateur_Conv_sensibility_VEF::add_diffusion_scalar_term(), Operateur_Conv_sensibility_VEF::add_diffusion_term(), Operateur_Conv_sensibility_VEF::ajouter(), Op_Div_EF::ajouter(), Op_Div_PolyMAC::ajouter(), Op_Conv_Amont_old_VEF_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Centre_EF_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_EF_VEF_P1NC_Stab::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_Muscl_New_VEF_Face::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Conv_Vort_VEF_Face::ajouter(), Op_Diff_VEF_Face::ajouter(), Op_Div_VEFP1B_Elem::ajouter(), Op_Diff_VEF_Face_Penalise::ajouter(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_scalaire(), Operateur_Conv_sensibility_VEF::ajouter_conv_term(), Operateur_Conv_sensibility_VEF::ajouter_Lsensibility_state_Amont(), Operateur_Conv_sensibility_VEF::ajouter_Lstate_sensibility_Amont(), Op_Conv_ALE_VEF::ajouterALE(), Domaine_Cl_VDF::associer(), Op_Diff_EF_base::associer(), Op_Diff_VEF_base::associer(), Maillage_FT_Disc::calculer_costheta_minmax(), Op_Grad_EF::calculer_flux_bords(), Op_Grad_VDF_Face::calculer_flux_bords(), Op_Grad_VEF_P1B_Face::calculer_flux_bords(), AssembleurPVDF_PF::construire(), Assembleur_P_VDF::construire(), Marching_Cubes::construire_noeuds_joints(), Domaine_VDF::creer_elements_fictifs(), Domaine_VDF::dist_norm_bord(), Domaine_VDF::dist_norm_bord_axi(), Paroi_ODVM_scal_VDF::init_lois_paroi(), Paroi_TBLE_QDM::init_lois_paroi(), Op_Diff_VEFP1NCP1B_Face::initialiser(), Op_Diff_VEF_Face_Stab::modifie_pour_Cl(), Iterateur_PolyMAC_Elem< _TYPE_ >::modifier_flux(), Op_EF_base::modifier_flux(), Op_VEF_Face::modifier_flux(), Domaine_Cl_VDF::nb_faces_bord(), nb_faces_internes(), and premiere_face_int().
nb_faces_bord_tot()
int Domaine_VF::nb_faces_bord_tot () const inline
renvoie le nombre total de faces sur lesquelles sont appliquees les conditions limites :
bords, raccords, plaques.
References MD_Vector_base::get_nb_items_tot(), and md_vector_faces_bord().
premiere_face_bord()
int Domaine_VF::premiere_face_bord () const inline
renvoie le numero de la premiere des faces sur lesquelles sont appliquees les conditions limites :
bords, raccords, plaques.
Referenced by Evaluateur_PolyMAC::associer_domaines(), Evaluateur_VDF::associer_domaines(), and Champ_Face_VDF::calculer_dercov_axi().
nb_faces_internes()
int Domaine_VF::nb_faces_internes () const inline
une face est interne ssi elle separe deux elements.
renvoie le nombre de faces internes.
References nb_faces(), and nb_faces_bord().
Referenced by Traitement_particulier_NS_EC::calculer_Ec(), AssembleurPVDF_PF::construire(), Assembleur_P_VDF::construire(), AssembleurPVDF_PF::remplir(), and Assembleur_P_VDF::remplir().
xv() [1/3]
double Domaine_VF::xv (int num_face, int k) const inline
References xv_.
Referenced by Navier_Stokes_phase_field::_aff_donnee_P1(), Champ_Face_PolyMAC::affecter_(), Champ_Fonc_Face_PolyMAC::affecter_(), Champ_Face_VDF::affecter_(), Champ_Fonc_Face_VDF::affecter_(), Op_Diff_VDF_base::ajoute_terme_pour_axi(), Op_Dift_VDF_base::ajoute_terme_pour_axi_turb(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_VEF_Face::ajouter(), SourceFiltree_FT_disc_VEF_P1NC::ajouter(), Terme_Source_Qdm_Face_PolyMAC::ajouter(), Perte_Charge_VEF::ajouter(), Terme_Boussinesq_VEF_Face::ajouter(), Terme_Source_Rappel_T_VEF_Face::ajouter(), Op_Diff_VEF_Face_Stab::ajouter_antidiffusion(), Op_Grad_P0_to_Face::ajouter_blocs(), Terme_Boussinesq_VDF_Face::ajouter_blocs(), DP_Impose_PolyMAC_Face::ajouter_blocs(), DP_Impose_VEF_Face::ajouter_blocs(), Sonde::ajouter_bords(), Operateur_Conv_sensibility_VEF::ajouter_conv_term(), Op_Conv_ALE_VEF::ajouterALE(), Transport_Marqueur_FT::appliquer_reflexion_vitesse(), Op_Diff_VDF_Face_Axi_base::associer(), Op_Dift_VDF_Face_Axi_base::associer(), Parcours_interface::associer_domaine_dis(), Force_Centrifuge_VDF_Face_Axi::associer_domaines(), Evaluateur_PolyMAC::associer_domaines(), Evaluateur_VDF::associer_domaines(), Champ_front_recyclage::calcul_moyenne_imposee(), Champ_P1NC::calcul_y_plus(), Terme_Source_Constituant_Vortex_VEF_Face::calculer(), Navier_Stokes_FT_Disc::calculer_delta_u_interface(), Champ_Face_VDF::calculer_dercov_axi(), Transport_Interfaces_FT_Disc::calculer_distance_interface_faces(), Traitement_particulier_NS_EC::calculer_Ec(), Modele_turbulence_hyd_LES_1elt_VEF::calculer_fonction_structure(), Modele_turbulence_hyd_LES_VEF::calculer_fonction_structure(), Paroi_std_hyd_VEF::calculer_hyd(), Paroi_negligeable_VEF::calculer_hyd(), Paroi_UTAU_IMP_VDF::calculer_hyd(), Paroi_UTAU_IMP_VDF::calculer_hyd_BiK(), Paroi_std_hyd_VEF::calculer_hyd_BiK(), Terme_Source_Acceleration::calculer_la_source(), Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_nut(), Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_Temp(), Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_vitesse(), Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_vitesse_rho_mu(), Loi_Paroi_Nu_Impose_VDF::calculer_scal(), Paroi_ODVM_scal_VDF::calculer_scal(), Loi_Paroi_Nu_Impose_VEF::calculer_scal(), Champ_front_calc_interne::completer(), Triple_Line_Model_FT_Disc::compute_TCL_fluxes_in_all_boundary_cells(), Domaine_ALE::computeFluidForceOnBeam(), Champ_front_contact_VEF::connectivity_failed(), Transport_K_ou_Eps_base::controler_variable(), Op_Conv_kschemas_centre_VEF::convkschemas_centre(), Parcours_interface::coupe_face_rectangulaire(), Traitement_particulier_NS_THI_VEF::determine_tab_fft_VEF_3D(), Post_Processing_Hydrodynamic_Forces_Stokes::fill_Stokes_velocity_field(), Champ_P1NC_implementation::filtrer_H1(), Champ_Generique_Transformation::get_champ(), Champ_front_recyclage::get_coord_faces(), Transport_Interfaces_FT_Disc::get_expression_vitesse_imposee(), Transport_2eq_base::get_position_faces(), Triple_Line_Model_FT_Disc::get_theta_app(), Convection_Diffusion_Temperature_FT_Disc::get_Twall(), Op_Grad_VEF_P1B_Face::impr(), Op_EF_base::impr(), Op_VEF_Face::impr(), Op_Grad_EF::impr(), Op_Grad_VDF_Face::impr(), Champ_P1NC_implementation::imprime_P1NC(), Loi_Paroi_Nu_Impose_VDF::imprimer_nusselt(), Loi_Paroi_Nu_Impose_VEF::imprimer_nusselt(), Paroi_scal_hyd_base_VDF::imprimer_nusselt(), Paroi_std_hyd_EF::imprimer_ustar(), Paroi_std_hyd_VDF::imprimer_ustar(), Paroi_std_hyd_VEF::imprimer_ustar(), ParoiVEF_TBLE::imprimer_ustar(), Paroi_2couches_VDF::imprimer_ustar(), ParoiVDF_TBLE_LRM::imprimer_ustar(), Echange_contact_Correlation_VEF::init(), Terme_Source_Canal_RANS_LES_VEF_Face::init(), Traitement_particulier_NS_Profils_VDF::init_calcul_moyenne(), Terme_Source_Canal_RANS_LES_VDF_Face::init_calcul_moyenne_spat(), Traitement_particulier_NS_chmoy_faceperio_VEF::init_calcul_stats(), init_dist_paroi_globale(), ParoiVDF_TBLE_LRM::init_lois_paroi(), Paroi_TBLE_QDM::init_lois_paroi(), Paroi_TBLE_QDM_Scal::init_lois_paroi(), Raccord_distant_homogene_32_64< _SIZE_ >::initialise(), Sonde::initialiser(), Ch_front_Vortex::initialiser(), Champ_front_lu::initialiser(), Champ_front_softanalytique::initialiser(), Champ_front_recyclage::initialiser_moyenne_imposee(), Transport_Interfaces_FT_Disc::interpoler_vitesse_face(), Extraire_plan::interpreter_(), Champ_front_recyclage::lire_fichier_format2(), Champ_front_recyclage::lire_fichier_format3(), Perte_Charge_Singuliere::lire_surfaces(), Champ_Front_Fonction::mettre_a_jour(), Champ_front_txyz::mettre_a_jour(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::mettre_a_jour(), Domaine_ALE::mettre_a_jour(), Echange_contact_VDF_FT_Disc::mettre_a_jour(), Echange_contact_VDF_FT_Disc_solid::mettre_a_jour(), Ch_front_Vortex::mettre_a_jour(), Terme_Source_Canal_RANS_LES_VDF_Face::mettre_a_jour(), Op_Conv_DI_L2_VEF_Face::poly_DI_L2_2d(), Op_Conv_DI_L2_VEF_Face::poly_DI_L2_3d(), Postraitement::postraiter_tableau(), Transport_Interfaces_FT_Disc::PPP_face_interface(), Transport_Interfaces_FT_Disc::PPP_face_interface_voisin(), Transport_Interfaces_FT_Disc::PPP_face_voisin(), Transport_Interfaces_FT_Disc::projete_point_face_fluide(), Transport_Interfaces_FT_Disc::projete_point_face_interface(), Debog_Pb::read_geometry_data(), Champ_Don_Face_lu::readOn(), Op_Conv_DI_L2_VEF_Face::reconst_DI_L2_2d(), Op_Conv_DI_L2_VEF_Face::reconst_DI_L2_3d(), Champ_front_contact_VEF::remplir_connect_bords(), Champ_Face_VDF_implementation::remplir_coord_noeuds(), Champ_P1NC_implementation::remplir_coord_noeuds(), Champ_Q1NC_implementation::remplir_coord_noeuds(), Domaine_Cl_VEF::remplir_normales_facettes_Cl(), Perte_Charge_Reguliere_VDF_Face::remplir_num_faces(), Traitement_particulier_NS_canal_VEF::remplir_Y(), Champ_Fonc_reprise_IJK::reprendre_IJK(), Op_Diff_VEFP1NCP1B_Face::test(), Champ_front_contact_VEF::test_faces_coin(), Champ_P1iP1B_implementation::trace(), Echange_contact_Correlation_VDF::trier_coord(), Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_face(), Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_face_sommets(), Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_gradU_elem(), Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_gradU_elem_P1(), Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_gradU_face(), Domaine_ALE::update_ALE_projection(), Op_Diff_VEF_Anisotrope_Face::verifier(), Op_Diff_VEF_Face::verifier(), Echange_contact_VDF::verifier_correspondance(), Parcours_interface::volume_barycentre_hexaedre(), Parcours_interface::volume_barycentre_rectangle(), Parcours_interface::volume_rectangle(), and Debog_Pb::write_geometry_data().
xp() [1/3]
double Domaine_VF::xp (int num_elem, int k) const inline
References xp_.
Referenced by Navier_Stokes_phase_field::_aff_donnee_P0(), Navier_Stokes_phase_field::_aff_donnee_P1Bulle(), Champ_P1_isoP1Bulle::affecter_(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_VEF_Face::ajouter(), Terme_Source_Qdm_Face_PolyMAC::ajouter(), Terme_Boussinesq_VEF_Face::ajouter(), Terme_Source_Rappel_T_VEF_Face::ajouter(), Source_Transport_K_KEps_VDF_Elem::ajouter_blocs(), Terme_Source_Qdm_VDF_Face::ajouter_blocs(), Terme_Source_Constituant_Vortex_VEF_Face::ajouter_terme_div_u(), Source_Con_Phase_field::assembler_matrice_point_fixe(), Op_Diff_VDF_Face_Axi_base::associer(), Op_Dift_VDF_Face_Axi_base::associer(), Op_Grad_VDF_Face_base::associer(), Force_Centrifuge_VDF_Face_Axi::associer_domaines(), Modele_Jones_Launder_VDF::Calcul_D(), Modele_Jones_Launder_Thermique_VDF::Calcul_D(), Modele_Jones_Launder_VDF::Calcul_D_BiK(), Modele_Jones_Launder_Thermique_VDF::Calcul_E(), Transport_Marqueur_FT::calcul_proprietes_geometriques(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calcul_tableaux_correspondance(), Modele_turbulence_scal_LES_dyn_VDF::calcul_tableaux_correspondance(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calcul_voisins(), Modele_turbulence_scal_LES_dyn_VDF::calcul_voisins(), Champ_P1NC::calcul_y_plus(), Source_Con_Phase_field::calculer_alpha_gradC_carre(), Source_Con_Phase_field::calculer_champ_fonc_c(), Navier_Stokes_FT_Disc::calculer_delta_u_interface(), Champ_Face_VDF::calculer_dercov_axi(), Transport_Interfaces_FT_Disc::calculer_distance_interface(), Transport_Interfaces_FT_Disc::calculer_distance_interface_faces(), Transport_Interfaces_FT_Disc::calculer_distance_interface_sommets(), Modele_turbulence_hyd_LES_1elt_VEF::calculer_fonction_structure(), EDO_Pression_th_VDF::calculer_grad(), EDO_Pression_th_VEF::calculer_grad(), Paroi_std_hyd_VEF::calculer_hyd(), Paroi_negligeable_VEF::calculer_hyd(), Algorithmes_Transport_FT_Disc::calculer_moments_indicatrice(), Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_nut(), Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_uv(), Traitement_particulier_NS_Profils_thermo_VDF::calculer_moyennes_spatiales_thermo(), Source_Con_Phase_field::calculer_u2_elem(), Champ_base::calculer_valeurs_elem_compo_post(), Modele_turbulence_hyd_combinaison::calculer_viscosite_turbulente(), Modele_turbulence_hyd_Longueur_Melange_VDF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_Longueur_Melange_VEF::calculer_viscosite_turbulente(), Triple_Line_Model_FT_Disc::compute_approximate_interface_inout(), Triple_Line_Model_FT_Disc::compute_TCL_fluxes_in_all_boundary_cells(), Post_Processing_Hydrodynamic_Forces::compute_viscosity_edges_sphere(), Transport_K_ou_Eps_base::controler_variable(), Traitement_particulier_NS_CEG::critere_areva(), Traitement_particulier_NS_CEG::critere_cea_jaea(), Modele_turbulence_hyd_LES_selectif_mod_VDF::cutoff(), Modele_turbulence_hyd_LES_1elt_selectif_mod_VEF::cutoff(), Modele_turbulence_hyd_LES_Fst_sel_VEF::cutoff(), Sauvegarde_Reprise_Maillage_FT::ecrire_xyz(), Extraire_surface::extraire_surface_without_cleaning(), Post_Processing_Hydrodynamic_Forces_Stokes::fill_Stokes_pressure_field(), Post_Processing_Hydrodynamic_Forces::find_neighboring_elements(), Post_Processing_Hydrodynamic_Forces::find_neighboring_faces(), Sonde::fix_probe_position_grav(), Champ_Generique_Transformation::get_champ(), Triple_Line_Model_FT_Disc::get_in_out_coords(), Transport_2eq_base::get_position_cells(), Convection_Diffusion_Temperature_FT_Disc::get_Twall(), Traitement_particulier_NS_Profils_VDF::init_calcul_moyenne(), Traitement_particulier_Solide_canal_VDF::init_calcul_moyenne(), Terme_Source_Solide_SWIFT_VDF::init_calcul_moyenne(), init_dist_paroi_globale(), Transport_Interfaces_FT_Disc::interpoler_vitesse_face(), Extraire_domaine::interpreter_(), Transport_Interfaces_FT_Disc::mettre_a_jour(), Domaine_ALE::mettre_a_jour(), Champ_Fonc_Tabule_Elem_PolyMAC::mettre_a_jour(), Champ_Fonc_Tabule_P0_VDF::mettre_a_jour(), Champ_Fonc_Tabule_P0_VEF::mettre_a_jour(), Op_Conv_DI_L2_VEF_Face::poly_DI_L2_2d(), Op_Conv_DI_L2_VEF_Face::poly_DI_L2_3d(), Debog_Pb::read_geometry_data(), Op_Conv_DI_L2_VEF_Face::reconst_DI_L2_2d(), Op_Conv_DI_L2_VEF_Face::reconst_DI_L2_3d(), Champ_P0_VDF::remplir_coord_noeuds(), Champ_P1iP1B_implementation::remplir_coord_noeuds(), Traitement_particulier_NS_canal_VDF::remplir_Tab_recap(), Traitement_particulier_NS_canal_VDF::remplir_Y(), Collision_Model_FT_base::set_LC_zones(), Moyenne_volumique::traiter_champs(), Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_elem(), Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_gradU_elem(), Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_gradU_elem_P1(), and Champ_base::valeur_aux_centres_de_gravite().
xa() [1/3]
double Domaine_VF::xa (int num_arete, int k) const inline
References xa_.
Referenced by Champ_Generique_Transformation::completer(), Assembleur_P_VEFPreP1B::modifier_matrice(), Debog_Pb::read_geometry_data(), and Debog_Pb::write_geometry_data().
face_numero_bord() [1/3]
int Domaine_VF::face_numero_bord (int num_face) const inline
References face_numero_bord_, and nb_faces().
face_numero_bord() [2/3]
IntTab & Domaine_VF::face_numero_bord () inline
References face_numero_bord_.
face_numero_bord() [3/3]
const IntTab & Domaine_VF::face_numero_bord () const inline
References face_numero_bord_.
remplir_face_numero_bord()
void Domaine_VF::remplir_face_numero_bord ()
References Domaine_32_64< _SIZE_ >::bord(), Domaine_dis_base::domaine(), face_numero_bord_, Domaine_32_64< _SIZE_ >::nb_bords(), Frontiere_32_64< _SIZE_ >::nb_faces(), nb_faces(), Domaine_32_64< _SIZE_ >::nb_raccords(), Frontiere_32_64< _SIZE_ >::num_premiere_face(), Domaine_32_64< _SIZE_ >::raccord(), and TRUSTTab< _TYPE_, _SIZE_ >::resize().
est_face_bord() [1/2]
ArrOfInt & Domaine_VF::est_face_bord () inline
References est_face_bord_.
Referenced by Op_Diff_VEF_Face::ajouter_contribution(), and Op_Diff_VEF_Face::ajouter_contribution_multi_scalaire().
est_face_bord() [2/2]
const ArrOfInt & Domaine_VF::est_face_bord () const inline
References est_face_bord_.
orientation() [1/2]
const IntVect & Domaine_VF::orientation () const inline virtual
Reimplemented in Domaine_VDF.
References Process::exit().
Referenced by Navier_Stokes_FT_Disc::calculer_gradient_indicatrice(), Collision_Model_FT_sphere::discretize_contact_forces_eulerian_field(), Champ_Generique_Reduction_0D::get_champ(), Domaine_PolyMAC::init_equiv(), and VDF_to_IJK::initialize().
orientation() [2/2]
int Domaine_VF::orientation (int num_face) const inline virtual
Reimplemented in Domaine_VDF.
References Objet_U::dimension, Process::exit(), face_normales(), and face_surfaces().
orientation_si_definie()
int Domaine_VF::orientation_si_definie (int num_face) const inline virtual
References Objet_U::dimension, face_normales(), and face_surfaces().
Referenced by Sonde::initialiser().
normalized_boundaries_outward_vector()
DoubleTab Domaine_VF::normalized_boundaries_outward_vector (int global_face_number, double scale_factor) const
Compute the normalized boundary outward vector associated to the face global_face_number and eventually scaled by scale_factor.
References Objet_U::dimension, face_normales(), face_surfaces(), face_voisins(), xp(), and xv().
Referenced by Champ_front_xyz_debit::calculer_normales_et_integrale(), and Boundary_field_inward::mettre_a_jour().
xv() [2/3]
DoubleTab & Domaine_VF::xv () inline
References xv_.
Referenced by Domaine_VDF::calculer_volumes_entrelaces(), calculer_xgr(), Domaine_VDF::discretiser(), Domaine_PolyMAC::init_ve(), Domaine_PolyMAC::M2(), normalized_boundaries_outward_vector(), Domaine_PolyMAC_P0P1NC::surf_elem_arete(), and Domaine_PolyMAC::W2().
xv() [3/3]
const DoubleTab & Domaine_VF::xv () const inline
References xv_.
xp() [2/3]
DoubleTab & Domaine_VF::xp () inline
References xp_.
Referenced by Domaine_VDF::calculer_volumes_entrelaces(), Domaine_VDF::discretiser(), get_position(), Domaine_PolyMAC::init_ve(), Domaine_PolyMAC::M2(), normalized_boundaries_outward_vector(), Domaine_EF_axi::remplir_tableau_origine(), Domaine_PolyMAC_P0P1NC::surf_elem_arete(), Domaine_VEF::vecteur_face_facette(), and Domaine_PolyMAC::W2().
xp() [3/3]
const DoubleTab & Domaine_VF::xp () const inline
References xp_.
xa() [2/3]
DoubleTab & Domaine_VF::xa () inline
References xa_.
Referenced by Domaine_VEF::construire_renum_arete_perio().
xa() [3/3]
const DoubleTab & Domaine_VF::xa () const inline
References xa_.
volumes_entrelaces() [1/3]
DoubleVect & Domaine_VF::volumes_entrelaces () inline
References volumes_entrelaces_.
Referenced by Op_Diff_VDF_base::ajoute_terme_pour_axi(), Op_Dift_VDF_base::ajoute_terme_pour_axi_turb(), Op_Conv_EF_VEF_P1NC::ajouter(), SourceFiltree_FT_disc_VEF_P1NC::ajouter(), Source_Transport_Flux_Chaleur_Turbulente_VDF_Face::ajouter(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_VEF_Face::ajouter(), Source_Transport_K_Eps_Bas_Reynolds_VEF_Face::ajouter(), Terme_Source_Canal_perio_VEF_P1NC::ajouter(), Terme_Source_Canal_RANS_LES_VEF_Face::ajouter(), Perte_Charge_Reguliere_VEF_P1NC::ajouter(), Perte_Charge_VEF::ajouter(), Terme_Source_Qdm_lambdaup_VEF_Face::ajouter(), Terme_Source_Rappel_T_VEF_Face::ajouter(), Source_rayo_semi_transp_VEF_P1NC::ajouter(), Perte_Charge_Reguliere_VDF_Face::ajouter_(), Tenseur_Reynolds_Externe_VDF_Face::ajouter_blocs(), Op_Grad_VDF_Face::ajouter_blocs(), Terme_Source_Canal_perio_VDF_Face::ajouter_blocs(), Terme_Source_Canal_RANS_LES_VDF_Face::ajouter_blocs(), Perte_Charge_Singuliere_VDF_Face::ajouter_blocs(), Terme_Boussinesq_VDF_Face::ajouter_blocs(), Terme_Source_Acceleration_VDF_Face::ajouter_blocs(), Terme_Source_Coriolis_VDF_Face::ajouter_blocs(), Terme_Source_inc_th_VDF_Face::ajouter_blocs(), Terme_Source_inc_VDF_Face::ajouter_blocs(), Terme_Source_Qdm_VDF_Face::ajouter_blocs(), Source_Masse_Fluide_Dilatable_VEF::ajouter_eq_espece(), Source_Masse_Fluide_Dilatable_VEF::ajouter_projection(), Masse_VDF_Face::appliquer_impl(), Masse_VEF_P1NC::appliquer_impl(), Assembleur_P_VDF::assembler(), Eq_rayo_semi_transp_VEF::assembler_matrice(), Simpler_Base::assembler_matrice_pression_implicite(), Assembleur_P_VDF::assembler_QC(), Assembleur_P_VEFPreP1B::assembler_rho_variable(), Assembleur_P_VDF::assembler_rho_variable(), Op_Diff_VDF_Face_Axi_base::associer(), Op_Dift_VDF_Face_Axi_base::associer(), Op_Grad_VDF_Face_base::associer(), Force_Centrifuge_VDF_Face_Axi::associer_domaines(), Evaluateur_PolyMAC::associer_domaines(), Evaluateur_VDF::associer_domaines(), Modele_Jones_Launder_VDF::Calcul_D(), Modele_Jones_Launder_VEF::Calcul_D(), Modele_Launder_Sharma_VEF::Calcul_D(), Modele_Jones_Launder_Thermique_VDF::Calcul_D(), Modele_Jones_Launder_VDF::Calcul_D_BiK(), Modele_Jones_Launder_VEF::Calcul_D_BiK(), Modele_Launder_Sharma_VEF::Calcul_D_BiK(), Traitement_particulier_NS_THI_VEF::calcul_Ec_spatial(), Transport_Interfaces_FT_Disc::calcul_indicatrice_faces(), Implicit_steady::calcul_mat_masse_diviser_par_dt_vdf(), Implicit_steady::calcul_mat_masse_diviser_par_dt_vef(), Traitement_particulier_NS_THI_VEF::calcul_moyenne(), Traitement_particulier_NS_THI_VDF::calcul_spectre_operateur(), Traitement_particulier_NS_THI_VEF::calcul_vitesse_moyenne(), Terme_Source_Constituant_Vortex_VEF_Face::calculer(), Op_Conv_VDF_base::calculer_dt_local(), Op_Conv_VEF_base::calculer_dt_local(), Op_Conv_ALE_VEF::calculer_dt_stab(), Operateur_Conv_sensibility_VEF::calculer_dt_stab(), Op_Conv_VEF_base::calculer_dt_stab(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab(), Traitement_particulier_NS_EC::calculer_Ec(), EDO_Pression_th_VEF::calculer_grad(), ParoiVDF_TBLE_LRM::calculer_hyd(), ParoiVDF_TBLE::calculer_hyd(), ParoiVEF_TBLE::calculer_hyd(), ParoiVDF_TBLE::calculer_hyd_BiK(), ParoiVDF_TBLE_LRM::calculer_hyd_BiK(), ParoiVEF_TBLE::calculer_hyd_BiK(), Op_Conv_VEF_base::calculer_pour_post(), ParoiVEF_TBLE_scal::calculer_scal(), Discretisation_tools::cells_to_faces(), Source_Transport_Realisable_VEF_Face_base::contribuer_a_avec(), Perte_Charge_Reguliere_VEF_P1NC::contribuer_a_avec(), Perte_Charge_VEF::contribuer_a_avec(), Collision_Model_FT_sphere::discretize_contact_forces_eulerian_field(), Champ_val_tot_sur_vol_VEF::eval_contrib_loc(), Domaine_PolyMAC_P0::fgrad(), Champ_P1NC_implementation::filtrer_resu(), Domaine_Cl_VEF::initialiser(), Convection_Diffusion_Concentration_FT_Disc::mettre_a_jour(), Convection_Diffusion_Concentration_Turbulent_FT_Disc::mettre_a_jour(), Domaine_ALE::mettre_a_jour(), Courant_maille_Champ_Face::mettre_a_jour(), Reynolds_maille_Champ_Face::mettre_a_jour(), Terme_Source_Canal_RANS_LES_VDF_Face::mettre_a_jour(), Tetra_VEF::modif_volumes_entrelaces(), Tri_VEF::modif_volumes_entrelaces(), Tetra_VEF::modif_volumes_entrelaces_faces_joints(), Tri_VEF::modif_volumes_entrelaces_faces_joints(), Convection_Diffusion_Concentration_FT_Disc::multiplier_valeurs_faces(), Convection_Diffusion_Concentration_Turbulent_FT_Disc::multiplier_valeurs_faces(), Terme_Source_Qdm_lambdaup_VEF_Face::norme_L2(), AssembleurPVDF_PF::remplir(), Domaine_Cl_VEF::remplir_volumes_entrelaces_Cl(), Eq_rayo_semi_transp_VEF::resoudre(), Op_Diff_VEF_Anisotrope_Face::verifier(), and Op_Diff_VEF_Face::verifier().
volumes_entrelaces() [2/3]
const DoubleVect & Domaine_VF::volumes_entrelaces () const inline
References volumes_entrelaces_.
volumes_entrelaces() [3/3]
double Domaine_VF::volumes_entrelaces (int num_face) const inline
References volumes_entrelaces_.
volumes_entrelaces_dir() [1/2]
const DoubleTab & Domaine_VF::volumes_entrelaces_dir () const inline
References volumes_entrelaces_dir_.
Referenced by Op_Grad_VDF_Face::ajouter_blocs(), and Perte_Charge_Singuliere_VDF_Face::ajouter_blocs().
volumes_entrelaces_dir() [2/2]
DoubleTab & Domaine_VF::volumes_entrelaces_dir () inline
References volumes_entrelaces_dir_.
joint() [1/2]
const Joint & Domaine_VF::joint (int i) const inline
References Domaine_dis_base::domaine(), and Domaine_32_64< _SIZE_ >::joint().
Referenced by Extraire_plan::interpreter_(), marquer_faces_double_contrib(), Domaine_VDF::reordonner(), and Collision_Model_FT_base::set_LC_zones().
joint() [2/2]
Joint & Domaine_VF::joint (int i) inline
References Domaine_dis_base::domaine(), and Domaine_32_64< _SIZE_ >::joint().
frontiere_dis() [1/2]
Frontiere_dis_base & Domaine_VF::frontiere_dis (int i) inline override virtual
renvoie la ieme frontiere_discrete.
Implements Domaine_dis_base.
References les_bords_.
Referenced by Champ_front_contact_VEF::calcul_coeff_amort(), Champ_front_contact_VEF::remplir_connect_bords(), Champ_front_contact_VEF::remplir_elems_voisin_bord(), and Champ_front_contact_VEF::test_faces_coin().
frontiere_dis() [2/2]
const Frontiere_dis_base & Domaine_VF::frontiere_dis (int i) const inline override virtual
renvoie la ieme frontiere_discrete.
Implements Domaine_dis_base.
References les_bords_.
nb_frontiere_dis()
int Domaine_VF::nb_frontiere_dis () const inline
References les_bords_, and TRUST_Vector< _CLASSE_ >::size().
Referenced by Champ_Generique_Extraction::completer().
front_VF()
const Front_VF & Domaine_VF::front_VF (int i) const inline
References les_bords_.
Referenced by Champ_front_contact_VEF::calcul_grads_locaux(), Traitement_particulier_NS_EC::calculer_Ec(), Loi_Paroi_Nu_Impose_VDF::calculer_scal(), Paroi_loi_WW_scal_VDF::calculer_scal(), Paroi_ODVM_scal_VDF::calculer_scal(), Paroi_std_scal_hyd_VDF::calculer_scal(), Paroi_TBLE_scal_VDF::calculer_scal(), Paroi_scal_hyd_base_VDF::compute_nusselt(), Domaine_Poly_base::dist_norm_bord(), Domaine_VDF::dist_norm_bord(), Loi_Paroi_Nu_Impose_VDF::imprimer_nusselt(), Domaine_Cl_VEF::initialiser(), PlaqThVDF::mettre_a_jour(), Domaine_Cl_EF::remplir_type_elem_Cl(), Domaine_Cl_VEF::remplir_type_elem_Cl(), and Domaine_Cl_VEF::remplir_volumes_entrelaces_Cl().
volumes() [1/3]
double Domaine_VF::volumes (int i) const inline
References volumes_.
Referenced by Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_Vort_VEF_Face::ajouter(), Op_Conv_RT_VEF_Face::ajouter(), Terme_Boussinesq_Sensibility_VEFPreP1B_Face::ajouter(), Source_Transport_Fluctuation_Temperature_VDF_Elem::ajouter(), Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::ajouter(), Source_Transport_Fluctuation_Temperature_W_VDF_Elem::ajouter(), Source_Transport_Flux_Chaleur_Turbulente_VDF_Face::ajouter(), Terme_Boussinesq_VEFPreP1B_Face::ajouter(), Terme_Source_Qdm_VEF_Face::ajouter(), Source_Transport_K_Eps_Bas_Reynolds_aniso_therm_concen_VDF_Elem::ajouter_blocs(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_VDF_Elem::ajouter_blocs(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_QC_VDF_Elem::ajouter_blocs(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_W_VDF_Elem::ajouter_blocs(), Source_Transport_K_KEps_VDF_Elem::ajouter_blocs(), Terme_Source_Canal_perio_VDF_P0::ajouter_blocs(), Terme_Source_Canal_RANS_LES_VDF_Elem::ajouter_blocs(), Terme_Source_Solide_SWIFT_VDF::ajouter_blocs(), Op_Diff_EF::ajouter_bords(), Op_Dift_EF_Q1::ajouter_bords(), Op_Diff_EF::ajouter_contribution(), Op_Dift_EF_Q1::ajouter_contribution(), Op_Conv_RT_VEF_Face::ajouter_contribution(), Op_Diff_EF::ajouter_contribution_new(), Op_Dift_EF_Q1::ajouter_contribution_new(), Op_Conv_EF::ajouter_contribution_sous_cond(), Op_Diff_EF::ajouter_new(), Op_Dift_EF_Q1::ajouter_new(), Source_Masse_Fluide_Dilatable_VDF::ajouter_projection(), Source_Masse_Fluide_Dilatable_VEF::ajouter_projection(), Terme_Source_Constituant_Vortex_VEF_Face::ajouter_terme_div_u(), Tensors_Computation_VEF::antisym_loop_edges_periodiqueBC(), Tensors_Computation_VEF::antisym_loop_internal_faces(), Masse_PolyMAC_Elem::appliquer_impl(), Masse_VDF_Elem::appliquer_impl(), Eq_rayo_semi_transp_VDF::assembler_matrice(), Champ_front_contact_VEF::calcul_coeff_amort(), Modele_Jones_Launder_VDF::Calcul_D(), Modele_Jones_Launder_VEF::Calcul_D(), Modele_Launder_Sharma_VEF::Calcul_D(), Modele_Jones_Launder_VDF::Calcul_D_BiK(), Modele_Jones_Launder_VEF::Calcul_D_BiK(), Modele_Launder_Sharma_VEF::Calcul_D_BiK(), Traitement_particulier_NS_THI_VEF::calcul_Df_spatial(), Modele_Jones_Launder_VEF::Calcul_E(), Modele_Launder_Sharma_VEF::Calcul_E(), Modele_Jones_Launder_Thermique_VDF::Calcul_E(), Traitement_particulier_NS_THI_VDF::calcul_Ec_D(), Modele_EASM_Baglietto_VEF::Calcul_F2(), Modele_Jones_Launder_VEF::Calcul_F2(), Modele_Lam_Bremhorst_VEF::Calcul_F2(), Modele_Launder_Sharma_VEF::Calcul_F2(), Modele_EASM_Baglietto_VEF::Calcul_F2_BiK(), Modele_Jones_Launder_VEF::Calcul_F2_BiK(), Modele_Lam_Bremhorst_VEF::Calcul_F2_BiK(), Modele_Launder_Sharma_VEF::Calcul_F2_BiK(), Modele_Jones_Launder_VEF::Calcul_Fmu(), Modele_Launder_Sharma_VEF::Calcul_Fmu(), Modele_EASM_Baglietto_VEF::Calcul_Fmu(), Modele_EASM_Baglietto_VEF::Calcul_Fmu_BiK(), Modele_Jones_Launder_VEF::Calcul_Fmu_BiK(), Modele_Launder_Sharma_VEF::Calcul_Fmu_BiK(), Champ_front_contact_VEF::calcul_grads_locaux(), Traitement_particulier_NS_THI_VEF::calcul_nu_t(), Transport_Marqueur_FT::calcul_proprietes_geometriques(), Traitement_particulier_NS_THI_VEF::calcul_Sk(), Modele_Lam_Bremhorst_VEF::calcul_tenseur_face(), Modele_Shih_Zhu_Lumley_VEF::calcul_tenseur_face(), Calcul_Production_K_VEF::calcul_tenseur_face(), Traitement_particulier_NS_THI_VEF::calcul_volume_elem(), Op_Conv_ALE_VEF::calculateALEMeshVelocityGradientOnFaces(), Op_Diff_VEF_Face_Stab::calculer_coefficients(), Source_Con_Phase_field::calculer_div_alpha_rho_gradC(), Op_Conv_PolyMAC_iterateur_base::calculer_dt_stab(), Op_Conv_VDF_base::calculer_dt_stab(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab_elem(), Op_Dift_VEF_base::calculer_dt_stab_P1NCP1B(), EDO_Pression_th_VEF::calculer_grad(), Op_Diff_VEFP1NCP1B_Face::calculer_gradient_elem(), Navier_Stokes_FT_Disc::calculer_gradient_indicatrice(), Op_Dift_VEF_P1NCP1B_Face::calculer_gradient_som(), Op_Diff_VEF_Face_Stab::calculer_gradients(), Transport_Interfaces_FT_Disc::calculer_integrale_indicatrice(), Algorithmes_Transport_FT_Disc::calculer_moments_indicatrice(), Op_Conv_PolyMAC_iterateur_base::calculer_pour_post(), Op_Conv_VDF_base::calculer_pour_post(), Modele_turbulence_hyd_LES_Fst_VEF::calculer_racine(), Modele_turbulence_hyd_LES_Smago_filtre_VEF::calculer_S_barre(), Paroi_std_scal_hyd_EF::calculer_scal(), Paroi_TBLE_scal_VDF::calculer_scal(), Paroi_scal_analytique_VEF::calculer_scal(), Paroi_std_scal_hyd_VEF::calculer_scal(), Calcul_Production_K_VEF::calculer_terme_destruction_K_gen(), Calcul_Production_K_VEF::calculer_terme_production_K(), Calcul_Production_K_VEF::calculer_terme_production_K_BiK(), Calcul_Production_K_VEF::calculer_terme_production_K_EASM(), Terme_Source_Acceleration_VDF_Face::calculer_vitesse_faces(), Transport_Interfaces_FT_Disc::calculer_vitesse_transport_interpolee(), Discretisation_tools::cells_to_faces(), Transport_Interfaces_FT_Disc::compute_particles_rms(), Triple_Line_Model_FT_Disc::compute_TCL_fluxes_in_all_boundary_cells(), Source_Transport_Realisable_VEF_Face_base::contribuer_a_avec(), Triple_Line_Model_FT_Disc::correct_TCL_energy_evolution(), Transport_Interfaces_FT_Disc::deplacer_maillage_ft_v_fluide(), Navier_Stokes_phase_field::derivee_en_temps_inco(), Transport_Marqueur_FT::detection_groupes_a_supprimer(), Source_Con_Phase_field::div_kappa_grad(), Convection_Diffusion_Temperature::ecrire_fichier_pena_th(), Champ_val_tot_sur_vol_VDF::eval_contrib_loc(), Champ_Generique_Reduction_0D::extraire(), Champ_Generique_Tparoi_VEF::get_champ(), Champ_Q1NC::gradient(), Paroi_TBLE_scal_VDF::init_lois_paroi(), Champ_P0_VDF::integrale_espace(), Domaine_ALE::laplacien(), T_paroi_Champ_P0_VDF::me_calculer(), Source_Qdm_VDF_Phase_field::methode_1(), Source_Qdm_VDF_Phase_field::methode_2(), Source_Qdm_VDF_Phase_field::methode_3(), Source_Qdm_VDF_Phase_field::methode_4(), Chimie::mettre_a_jour(), Transport_Interfaces_FT_Disc::mettre_a_jour(), Domaine_ALE::mettre_a_jour(), Champ_P0_VDF::moyenne(), Champ_Fonc_P0_base::moyenne(), Champ_P1NC::norme_H1(), Terme_Source_Qdm_lambdaup_VEF_Face::norme_H1(), Champ_P1_isoP1Bulle::norme_L2(), Echange_contact_Correlation_VEF::pdt_scal(), Echange_contact_Correlation_VEF::pdt_scalSqrt(), Assembleur_P_VEFPreP1B::projete_L2(), Op_Diff_RotRot::remplir_elem_elem_EF(), Perte_Charge_Reguliere_VDF_Face::remplir_num_faces(), Perte_Charge_Reguliere_VEF_P1NC::remplir_num_faces(), Op_Diff_RotRot::remplir_som_som_EF(), Eq_rayo_semi_transp_VDF::resoudre(), EDO_Pression_th_VDF_Gaz_Reel::resoudre(), Navier_Stokes_phase_field::rho_aux_faces(), Remailleur_Collision_FT_Thomas::traite_RuptureCoalescenceInterfaces_Conservatif(), Echange_contact_PolyMAC::update_coeffs(), Champ_implementation_P1::value_interpolation(), Discretisation_base::volume_maille(), Op_Div_EF::volumique(), Op_Div_PolyMAC::volumique(), and Op_Div_VDF_Elem::volumique().
inverse_volumes() [1/3]
double Domaine_VF::inverse_volumes (int i) const inline
References inverse_volumes_.
Referenced by Op_Diff_VEF_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Face::ajouter_contribution_multi_scalaire(), Domaine_ALE::mettre_a_jour(), and Estimateur_Aposteriori_P0_VEF::mettre_a_jour().
face_voisins() [1/3]
int Domaine_VF::face_voisins (int num_face, int i) const inline
renvoie l'element voisin de numface dans la direction i.
i=0 : dans le sens oppose de l'axe orthogonal a la face numface. i=1 : dans le sens de l'axe orthogonal a la face numface. exemple :
           |   0     |     1    |
                 numface
renvoie -1 si l'element n'existe pas (au bord).
References face_voisins_.
Referenced by Operateur_Conv_sensibility_VEF::add_diffusion_scalar_term(), Operateur_Conv_sensibility_VEF::add_diffusion_term(), Champ_Face_VDF::affecter_(), Champ_Fonc_Face_VDF::affecter_(), Op_Diff_VDF_base::ajoute_terme_pour_axi(), Op_Dift_VDF_base::ajoute_terme_pour_axi_turb(), Op_Div_PolyMAC::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_EF_VEF_P1NC::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Conv_Vort_VEF_Face::ajouter(), Op_Diff_VEF_Face_Q1::ajouter(), Op_Dift_VEF_Face_Q1::ajouter(), Op_Rot_VEFP1B::ajouter(), Op_Conv_RT_VEF_Face::ajouter(), SourceFiltree_FT_disc_VEF_P1NC::ajouter(), Source_Transport_Flux_Chaleur_Turbulente_VDF_Face::ajouter(), Source_Robin::ajouter(), Source_Robin_Scalaire::ajouter(), Terme_Source_Qdm_Face_PolyMAC::ajouter(), Perte_Charge_Reguliere_VEF_P1NC::ajouter(), Perte_Charge_VEF::ajouter(), Terme_Boussinesq_VEF_Face::ajouter(), Terme_Source_Qdm_VEF_Face::ajouter(), Terme_Source_Rappel_T_VEF_Face::ajouter(), Perte_Charge_Reguliere_VDF_Face::ajouter_(), Op_Div_VEFP1B_Elem::ajouter_aretes(), Op_Grad_VEF_P1B_Face::ajouter_aretes(), Tenseur_Reynolds_Externe_VDF_Face::ajouter_blocs(), Source_Transport_K_KEps_VDF_Elem::ajouter_blocs(), Perte_Charge_Singuliere_VDF_Face::ajouter_blocs(), Terme_Boussinesq_VDF_Face::ajouter_blocs(), Terme_Source_Acceleration_VDF_Face::ajouter_blocs(), Terme_Source_Coriolis_VDF_Face::ajouter_blocs(), Terme_Source_inc_th_VDF_Face::ajouter_blocs(), Terme_Source_inc_VDF_Face::ajouter_blocs(), Terme_Source_Qdm_VDF_Face::ajouter_blocs(), Op_Diff_EF::ajouter_bords(), Op_Dift_EF_Q1::ajouter_bords(), Sonde::ajouter_bords(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Face::ajouter_cas_vectoriel(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution(), Op_Diff_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Face_Q1::ajouter_contribution(), Op_Diff_VEF_Face_Stab::ajouter_contribution(), Op_Conv_RT_VEF_Face::ajouter_contribution(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution_elem(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face_Stab::ajouter_contribution_multi_scalaire(), Op_Diff_EF::ajouter_contributions_bords(), Op_Dift_EF_Q1::ajouter_contributions_bords(), Operateur_Conv_sensibility_VEF::ajouter_conv_term(), Op_Div_VEFP1B_Elem::ajouter_elem(), Op_Grad_VEF_P1B_Face::ajouter_elem(), Source_Masse_Fluide_Dilatable_VEF::ajouter_eq_espece(), Source_Masse_Fluide_Dilatable_VDF::ajouter_projection(), Source_Masse_Fluide_Dilatable_VEF::ajouter_projection(), Op_Grad_VEF_P1B_Face::ajouter_som(), Op_Div_VEFP1B_Elem::ajouter_som(), Op_Conv_ALE_VEF::ajouterALE(), Tensors_Computation_VEF::antisym_loop_edges_general(), Tensors_Computation_VEF::antisym_loop_edges_periodiqueBC(), Tensors_Computation_VEF::antisym_loop_internal_faces(), Masse_VEF_P1NC::appliquer_impl(), Source_Con_Phase_field::assembler_matrice_point_fixe(), Op_Grad_PolyMAC_Face::associer(), Op_Diff_VDF_Face_Axi_base::associer(), Op_Dift_VDF_Face_Axi_base::associer(), Op_Grad_VDF_Face_base::associer(), Evaluateur_PolyMAC::associer_domaines(), Evaluateur_VDF::associer_domaines(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calc_elem_elem(), Modele_turbulence_scal_LES_dyn_VDF::calc_elem_elem(), Champ_front_contact_VEF::calcul_coeff_amort(), Modele_Jones_Launder_VDF::Calcul_D(), Modele_Jones_Launder_Thermique_VDF::Calcul_D(), Modele_Jones_Launder_VDF::Calcul_D_BiK(), Champ_Face_VDF::calcul_duidxj(), Champ_P1NC::calcul_duidxj_paroi(), Modele_Jones_Launder_VDF::Calcul_E(), Modele_Jones_Launder_VEF::Calcul_E(), Modele_Launder_Sharma_VEF::Calcul_E(), Modele_Jones_Launder_Thermique_VDF::Calcul_E(), Parcours_interface::calcul_eq_plan(), Modele_EASM_Baglietto_VEF::Calcul_F1(), Modele_Lam_Bremhorst_VEF::Calcul_F1(), Modele_EASM_Baglietto_VEF::Calcul_F1_BiK(), Modele_Lam_Bremhorst_VEF::Calcul_F1_BiK(), Modele_EASM_Baglietto_VEF::Calcul_F2(), Modele_Jones_Launder_VEF::Calcul_F2(), Modele_Lam_Bremhorst_VEF::Calcul_F2(), Modele_Launder_Sharma_VEF::Calcul_F2(), Modele_EASM_Baglietto_VEF::Calcul_F2_BiK(), Modele_Jones_Launder_VEF::Calcul_F2_BiK(), Modele_Lam_Bremhorst_VEF::Calcul_F2_BiK(), Modele_Launder_Sharma_VEF::Calcul_F2_BiK(), Modele_Jones_Launder_VEF::Calcul_Fmu(), Modele_Lam_Bremhorst_VEF::Calcul_Fmu(), Modele_Launder_Sharma_VEF::Calcul_Fmu(), Modele_EASM_Baglietto_VEF::Calcul_Fmu(), Modele_EASM_Baglietto_VEF::Calcul_Fmu_BiK(), Modele_Jones_Launder_VEF::Calcul_Fmu_BiK(), Modele_Lam_Bremhorst_VEF::Calcul_Fmu_BiK(), Modele_Launder_Sharma_VEF::Calcul_Fmu_BiK(), Champ_front_contact_VEF::calcul_grads_locaux(), Champ_P1NC::calcul_h_conv(), Convection_Diffusion_Temperature::calcul_indic_pena_global(), Maillage_FT_Disc::calcul_indicatrice(), Traitement_particulier_NS_canal::calcul_reynolds_tau(), Champ_Face_VDF::calcul_S_barre_sans_contrib_paroi(), Traitement_particulier_NS_THI_VDF::calcul_skewness_ordre_2(), Modele_Lam_Bremhorst_VEF::calcul_tenseur_face(), Modele_Shih_Zhu_Lumley_VEF::calcul_tenseur_face(), Calcul_Production_K_VEF::calcul_tenseur_face(), Transport_Interfaces_FT_Disc::calcul_tolerance_projete_monophasique(), Champ_Q1_EF::calcul_y_plus(), Champ_P1NC::calcul_y_plus(), Champ_Face_VDF::calcul_y_plus(), Champ_P1NC::calcul_y_plus_diphasique(), Champ_Face_VDF::calcul_y_plus_diphasique(), Milieu_base::calculate_face_hydr_diam(), Milieu_base::calculate_face_porosity(), Perte_Charge_Singuliere::calculate_Q(), Op_Conv_ALE_VEF::calculateALEMeshVelocityGradientOnFaces(), Op_Diff_VEF_Face_Stab::calculer_coefficients(), Topologie_Maillage_FT::calculer_composantes_connexes_pour_suppression(), Navier_Stokes_FT_Disc::calculer_delta_u_interface(), Transport_Interfaces_FT_Disc::calculer_distance_interface(), Source_Con_Phase_field::calculer_div_alpha_rho_gradC(), Op_Diff_P1NC_barprim::calculer_divergence(), Op_Dift_VEF_P1NCP1B_Face::calculer_divergence_elem(), Op_Diff_VEFP1NCP1B_Face::calculer_divergence_elem(), Op_Dift_VEF_P1NCP1B_Face::calculer_divergence_som(), Op_Diff_VEFP1NCP1B_Face::calculer_divergence_som(), Champ_Face_VDF::calculer_dscald_centre_element(), Op_Conv_PolyMAC_iterateur_base::calculer_dt_stab(), Op_Conv_VDF_base::calculer_dt_stab(), Modele_turbulence_scal_LES_dyn_VDF::calculer_filter_coeff(), Modele_turbulence_hyd_LES_DSGS_VDF::calculer_filter_coeff(), Modele_turbulence_hyd_LES_DSGS_VDF::calculer_filter_field(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calculer_filter_field(), Modele_turbulence_hyd_LES_DSGS_VDF::calculer_filter_tensor(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calculer_filter_tensor(), Op_Grad_EF::calculer_flux_bords(), Op_Grad_VEF_P1B_Face::calculer_flux_bords(), Op_Diff_VEFP1NCP1B_Face::calculer_flux_bords_elem(), Flux_radiatif_VDF::calculer_flux_radiatif(), Modele_turbulence_hyd_LES_VDF::calculer_fonction_structure(), Modele_turbulence_hyd_LES_VEF::calculer_fonction_structure(), Modele_turbulence_hyd_LES_axi_VDF::calculer_fonction_structure(), EDO_Pression_th_VDF::calculer_grad(), EDO_Pression_th_VEF::calculer_grad(), Source_Transport_Flux_Chaleur_Turbulente_VDF_Face::calculer_Grad_U(), Op_Dift_VEF_P1NCP1B_Face::calculer_gradient_elem(), Op_Diff_VEFP1NCP1B_Face::calculer_gradient_elem(), Navier_Stokes_FT_Disc::calculer_gradient_indicatrice(), Op_Dift_VEF_P1NCP1B_Face::calculer_gradient_som(), Op_Diff_VEFP1NCP1B_Face::calculer_gradient_som(), Op_Diff_VEF_Face_Stab::calculer_gradients(), Echange_contact_Correlation_VEF::calculer_h_solide(), Echange_contact_Correlation_VDF::calculer_h_solide(), ParoiVDF_TBLE_LRM::calculer_hyd(), Paroi_std_hyd_VEF::calculer_hyd(), Paroi_negligeable_VDF::calculer_hyd(), Paroi_negligeable_VEF::calculer_hyd(), Paroi_std_hyd_VDF_diphasique::calculer_hyd(), Paroi_std_hyd_VEF_diphasique::calculer_hyd(), Paroi_loi_WW_hyd_EF::calculer_hyd(), Paroi_std_hyd_EF::calculer_hyd(), Paroi_2couches_VDF::calculer_hyd(), Paroi_loi_Ciofalo_hyd_VDF::calculer_hyd(), Paroi_loi_WW_hyd_VDF::calculer_hyd(), Paroi_loi_WW_hyd_VEF::calculer_hyd(), Paroi_std_hyd_VDF::calculer_hyd(), Paroi_UTAU_IMP_VDF::calculer_hyd(), ParoiVDF_TBLE::calculer_hyd(), ParoiVEF_TBLE::calculer_hyd(), Paroi_std_hyd_VDF::calculer_hyd_BiK(), Paroi_UTAU_IMP_VDF::calculer_hyd_BiK(), ParoiVDF_TBLE::calculer_hyd_BiK(), ParoiVDF_TBLE_LRM::calculer_hyd_BiK(), Paroi_std_hyd_VEF::calculer_hyd_BiK(), ParoiVEF_TBLE::calculer_hyd_BiK(), IJK_Interfaces::calculer_indicatrice(), IJK_Interfaces::calculer_indicatrices(), Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_nut(), Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_vitesse_rho_mu(), Paroi_std_hyd_VDF::calculer_moyennes_parois(), Modele_turbulence_hyd_LES_Wale_VDF::calculer_OP1_OP2(), Op_Conv_PolyMAC_iterateur_base::calculer_pour_post(), Op_Conv_VDF_base::calculer_pour_post(), Source_Transport_Fluctuation_Temperature_VDF_Elem::calculer_Prod_uteta_T(), Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::calculer_Prod_uteta_T(), Source_Transport_Fluctuation_Temperature_W_VDF_Elem::calculer_Prod_uteta_T(), Echange_contact_Correlation_VDF::calculer_Q(), Echange_contact_Correlation_VEF::calculer_Q(), Champ_Face_VDF::calculer_rotationnel_ordre2_centre_element(), Modele_turbulence_hyd_LES_Smago_filtre_VEF::calculer_S_barre(), Paroi_std_scal_hyd_EF::calculer_scal(), Loi_Paroi_Nu_Impose_VDF::calculer_scal(), Paroi_loi_WW_scal_VDF::calculer_scal(), Paroi_ODVM_scal_VDF::calculer_scal(), Paroi_std_scal_hyd_VDF::calculer_scal(), Paroi_TBLE_scal_VDF::calculer_scal(), Loi_Paroi_Nu_Impose_VEF::calculer_scal(), Paroi_loi_WW_scal_VEF::calculer_scal(), Paroi_scal_analytique_VEF::calculer_scal(), Paroi_std_scal_hyd_VEF::calculer_scal(), ParoiVEF_TBLE_scal::calculer_scal(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calculer_Sij_vel_filt(), Parcours_interface::calculer_sortie_face_bord(), Neumann_paroi_rayo_semi_transp_VDF::calculer_temperature_bord(), Calcul_Production_K_VEF::calculer_terme_destruction_K_gen(), Calcul_Production_K_VEF::calculer_terme_production_K(), Calcul_Production_K_VDF::calculer_terme_production_K_Axi(), Calcul_Production_K_VEF::calculer_terme_production_K_BiK(), Calcul_Production_K_VDF::calculer_terme_production_K_BiK_Axi(), Calcul_Production_K_VEF::calculer_terme_production_K_EASM(), Echange_contact_ODVM_VDF::calculer_Teta_equiv(), Paroi_flux_impose_Rayo_transp::calculer_Teta_i_VDF(), Echange_contact_VDF::calculer_Teta_paroi(), Echange_contact_Rayo_transp_VDF::calculer_Teta_paroi(), Echange_contact_rayo_semi_transp_VDF::calculer_Teta_paroi(), Calcul_Production_K_VDF::calculer_u_conc(), Calcul_Production_K_VDF::calculer_u_teta(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_W_VDF_Elem::calculer_u_teta_W(), Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::calculer_u_teta_W(), Source_Transport_Fluctuation_Temperature_W_VDF_Elem::calculer_u_teta_W(), Source_Transport_Flux_Chaleur_Turbulente_VDF_Face::calculer_uiuj(), Modele_turbulence_hyd_LES_VEF::calculer_viscosite_turbulente(), Terme_Source_Acceleration_VDF_Face::calculer_vitesse_faces(), Maillage_FT_Disc::check_sommets(), Op_Diff_VEF_Face_Penalise::coefficient_penalisation(), Triple_Line_Model_FT_Disc::completer(), Echange_contact_Rayo_transp_VDF::completer(), Paroi_flux_impose_Rayo_transp::completer(), Neumann_paroi_rayo_semi_transp_VDF::completer(), Sortie_libre_pression_moyenne_imposee::completer(), Echange_contact_Correlation_VEF::completer(), Convection_Diffusion_Temperature_FT_Disc::compute_divergence_free_velocity_extension(), IJK_Interfaces::compute_drapeaux_vapeur_v4(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_friction_force_projected_tensor(), Paroi_std_hyd_VDF::compute_law_komega(), Paroi_scal_hyd_base_VDF::compute_nusselt(), Navier_Stokes_FT_Disc::compute_particles_eulerian_id_number(), Triple_Line_Model_FT_Disc::compute_TCL_fluxes_in_all_boundary_cells(), Champ_front_contact_VEF::connectivity_failed(), AssembleurPVDF_PF::construire(), Assembleur_P_VDF::construire(), Marching_Cubes::construire_noeuds_uniques(), Source_Transport_Realisable_VEF_Face_base::contribuer_a_avec(), Op_Dift_VEF_Face_Q1::contribuer_a_avec(), Perte_Charge_Reguliere_VEF_P1NC::contribuer_a_avec(), Perte_Charge_VEF::contribuer_a_avec(), Op_Div_PolyMAC::contribuer_a_avec(), Op_Dift_VEF_Face::contribuer_au_second_membre(), Transport_K_Eps_base::controler_K_Eps(), Transport_K_Omega_base::controler_K_Omega(), Transport_K_ou_Eps_base::controler_variable(), Navier_Stokes_FT_Disc::correct_at_exit_bad_gradient(), Op_Diff_VEFP1NCP1B_Face::corriger_div_pour_Cl(), Traitement_particulier_NS_CEG::critere_areva(), Traitement_particulier_NS_CEG::critere_cea_jaea(), Modele_turbulence_hyd_LES_selectif_mod_VDF::cutoff(), Modele_turbulence_hyd_LES_selectif_VDF::cutoff(), Modele_turbulence_hyd_LES_1elt_selectif_mod_VEF::cutoff(), Modele_turbulence_hyd_LES_Fst_sel_VEF::cutoff(), Op_Div_VEFP1B_Elem::degres_liberte(), Maillage_FT_Disc::deplacer_sommets(), Navier_Stokes_phase_field::derivee_en_temps_inco(), Op_EF_base::dimensionner(), Op_PolyMAC_Elem::dimensionner(), Op_VDF_Face::dimensionner(), Op_VEF_Face::dimensionner(), Op_Grad_PolyMAC_Face::dimensionner(), Op_Div_PolyMAC::dimensionner(), Op_PolyMAC_Elem::dimensionner_bloc_vitesse(), Op_Grad_VDF_Face::dimensionner_blocs(), Collision_Model_FT_sphere::discretize_contact_forces_eulerian_field(), Source_Con_Phase_field::div_kappa_grad(), Viscosite_turbulente_WALE::eddy_viscosity(), Op_Diff_VEF_Face_Penalise::element_commun(), Champ_val_tot_sur_vol_VEF::eval_contrib_loc(), Flux_radiatif_VDF::evaluer_cl_rayonnement(), Post_Processing_Hydrodynamic_Forces::face_voisins_for_interp(), Champ_P1NC_implementation::filtrer_L2(), Neumann_paroi_rayo_semi_transp_VDF::flux_impose(), Sortie_libre_Gradient_Pression_libre_VEF::flux_impose(), Paroi_hyd_base_EF::get_champ(), Champ_Generique_Tparoi_VEF::get_champ(), Transport_Interfaces_FT_Disc::get_expression_vitesse_imposee(), Triple_Line_Model_FT_Disc::get_theta_app(), Convection_Diffusion_Temperature_FT_Disc::get_Twall(), Convection_Diffusion_Temperature_FT_Disc::get_Twall_at_elem(), Champ_Q1NC::gradient(), Op_Diff_VEFP1NCP1B_Face::gradient_som(), Op_Diff_VEFP1NCP1B_Face::gradient_som_CL(), Loi_Paroi_Nu_Impose_VDF::imprimer_nusselt(), Loi_Paroi_Nu_Impose_VEF::imprimer_nusselt(), Paroi_scal_hyd_base_VDF::imprimer_nusselt(), ParoiVDF_TBLE::init_lois_paroi(), ParoiVDF_TBLE_LRM::init_lois_paroi(), Paroi_ODVM_scal_VDF::init_lois_paroi(), Paroi_TBLE_scal_VDF::init_lois_paroi(), ParoiVEF_TBLE::init_lois_paroi(), ParoiVEF_TBLE_scal::init_lois_paroi(), Echange_contact_PolyMAC::initialiser(), Echange_contact_VDF::initialiser(), Sortie_libre_Gradient_Pression_libre_VEF::initialiser(), Champ_front_tangentiel_VEF::initialiser(), Transport_Interfaces_FT_Disc::interpoler_vitesse_face(), Extraire_domaine::interpreter_(), Op_Diff_VEFP1NCP1B_Face::isInStencil(), Domaine_ALE::laplacien(), Transport_Interfaces_FT_Disc::lire_maillage_ft_cao(), Op_Diff_VEFP1NCP1B_Face::liste_face(), T_paroi_Champ_P0_VDF::me_calculer(), Source_Qdm_VDF_Phase_field::methode_1(), Source_Qdm_VDF_Phase_field::methode_2(), Source_Qdm_VDF_Phase_field::methode_3(), Source_Qdm_VDF_Phase_field::methode_4(), Chimie::mettre_a_jour(), Champ_front_debit_QC::mettre_a_jour(), Champ_front_debit_QC_fonc_t::mettre_a_jour(), Champ_front_fonc_gradient_VEF::mettre_a_jour(), Domaine_ALE::mettre_a_jour(), Echange_contact_VDF_FT_Disc::mettre_a_jour(), Echange_contact_VDF_FT_Disc_solid::mettre_a_jour(), Estimateur_Aposteriori_P0_VEF::mettre_a_jour(), Champ_front_fonc_gradient_VDF::mettre_a_jour(), PlaqThVDF::mettre_a_jour(), Sortie_libre_Pression_imposee_Orlansky::mettre_a_jour(), Echange_contact_Correlation_VEF::mettre_a_jour(), Sonde::mettre_a_jour_bords(), Convection_Diffusion_Temperature::mise_en_place_domaine_fantome(), Iterateur_PolyMAC_Elem< _TYPE_ >::modifier_flux(), Eq_rayo_semi_transp_VDF::modifier_matrice(), Eq_rayo_semi_transp_VEF::modifier_matrice(), Op_Diff_K_Eps_VDF_base::modifier_pour_Cl(), Op_Diff_K_Omega_VDF_base::modifier_pour_Cl(), Assembleur_P_EF::modifier_secmem(), Assembleur_P_PolyMAC::modifier_secmem(), Assembleur_P_VEF::modifier_secmem(), Assembleur_P_VEFPreP1B::modifier_secmem_elem(), AssembleurPVDF_PF::modifier_secmem_pression_imposee(), Assembleur_P_VDF::modifier_secmem_pression_imposee(), Assembleur_P_VEFPreP1B::modifier_secmem_som(), AssembleurPVDF_PF::modifier_secmem_vitesse_imposee(), Assembleur_P_VDF::modifier_secmem_vitesse_imposee(), Champ_P1NC::norme_H1(), Terme_Source_Canal_RANS_LES_VDF_Face::norme_vit(), Parcours_interface::parcours_facette(), Echange_contact_Correlation_VEF::pdt_scal(), Convection_Diffusion_Temperature::penalisation_L2(), Op_Conv_DI_L2_VEF_Face::poly_DI_L2_2d(), Op_Conv_DI_L2_VEF_Face::poly_DI_L2_3d(), Transport_Interfaces_FT_Disc::PPP_face_interface(), Transport_Interfaces_FT_Disc::PPP_face_interface_voisin(), Transport_Interfaces_FT_Disc::PPP_face_voisin(), Transport_Interfaces_FT_Disc::projete_point_face_fluide(), Transport_Interfaces_FT_Disc::projete_point_face_interface(), Transport_Interfaces_FT_Disc::ramasse_miettes(), Assembleur_P_VEF::remplir(), AssembleurPVDF_PF::remplir(), Assembleur_P_VDF::remplir(), Porosites::remplir_champ(), Champ_front_contact_VEF::remplir_connect_bords(), Champ_Face_VDF_implementation::remplir_coord_noeuds_et_polys(), Champ_P1NC_implementation::remplir_coord_noeuds_et_polys(), Champ_Q1NC_implementation::remplir_coord_noeuds_et_polys(), Champ_front_contact_VEF::remplir_elems_voisin_bord(), Op_Dift_EF_Q1::remplir_marqueur_elem_CL_paroi(), Perte_Charge_Reguliere_VDF_Face::remplir_num_faces(), Perte_Charge_Reguliere_VEF_P1NC::remplir_num_faces(), Domaine_Cl_VEF::remplir_type_elem_Cl(), Domaine_Cl_VEF::remplir_volumes_entrelaces_Cl(), Navier_Stokes_phase_field::rho_aux_faces(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::stabilise_moyenne_6_points(), Modele_turbulence_scal_LES_dyn_VDF::stabilise_moyenne_6_points(), Op_Diff_VEFP1NCP1B_Face::test(), Champ_Face_PolyMAC_P0P1NC::trace(), Champ_Face_VDF_implementation::trace(), Champ_P1iP1B_implementation::trace(), Convection_Diffusion_Temperature::transport_ibc(), Echange_contact_PolyMAC::update_coeffs(), Echange_contact_PolyMAC::update_delta(), Echange_interne_impose::update_inv_lambda(), Champ_Fonc_P0_base::valeur_au_bord(), Champ_P1_isoP1Bulle::valeur_au_bord(), Assembleur_P_VEFPreP1B::verifier_dirichlet(), Op_Diff_VEF_Face_Penalise::voisinage(), and Debog_Pb::write_geometry_data().
elem_faces() [1/3]
int Domaine_VF::elem_faces (int num_elem, int i) const inline
renvoie le numero de le ieme face de la maille num_elem la facon dont ces faces sont numerotees est
laisse a la responsabilite des classes derivees
References elem_faces_.
Referenced by Operateur_Conv_sensibility_VEF::add_diffusion_scalar_term(), Operateur_Conv_sensibility_VEF::add_diffusion_term(), Op_Conv_Amont_old_VEF_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Centre_EF_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_EF_VEF_P1NC::ajouter(), Op_Conv_EF_VEF_P1NC_Stab::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_Muscl_New_VEF_Face::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Conv_Vort_VEF_Face::ajouter(), Op_Diff_VEF_Face_Q1::ajouter(), Op_Dift_VEF_Face_Q1::ajouter(), Op_Curl_VEFP1B::ajouter(), Op_Rot_VEFP1B::ajouter(), Op_Conv_RT_VEF_Face::ajouter(), Terme_Boussinesq_Sensibility_VEFPreP1B_Face::ajouter(), Source_Transport_Fluctuation_Temperature_VDF_Elem::ajouter(), Terme_Boussinesq_VEFPreP1B_Face::ajouter(), Terme_Source_Qdm_VEF_Face::ajouter(), Perte_Charge_Reguliere_VDF_Face::ajouter_(), Op_Diff_VEF_Face_Stab::ajouter_antidiffusion(), Op_Div_VEFP1B_Elem::ajouter_aretes(), Op_Grad_VEF_P1B_Face::ajouter_aretes(), Source_Transport_K_KEps_VDF_Elem::ajouter_blocs(), Op_Grad_P0_to_Face::ajouter_blocs(), Terme_Source_inc_th_VDF_Face::ajouter_blocs(), Terme_Source_inc_VDF_Face::ajouter_blocs(), Op_Diff_EF::ajouter_bords(), Op_Dift_EF_Q1::ajouter_bords(), Sonde::ajouter_bords(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Face::ajouter_cas_scalaire(), Op_Conv_Amont_old_VEF_Face::ajouter_contribution(), Op_Conv_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution(), Op_Diff_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Face_Q1::ajouter_contribution(), Op_Diff_VEF_Face_Stab::ajouter_contribution(), Op_Conv_RT_VEF_Face::ajouter_contribution(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution_elem(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face_Stab::ajouter_contribution_multi_scalaire(), Op_Diff_EF::ajouter_contributions_bords(), Op_Dift_EF_Q1::ajouter_contributions_bords(), Operateur_Conv_sensibility_VEF::ajouter_conv_term(), Op_Diff_VEF_Face_Stab::ajouter_diffusion(), Op_Div_VEFP1B_Elem::ajouter_elem(), Op_Grad_VEF_P1B_Face::ajouter_elem(), Source_Masse_Fluide_Dilatable_VEF::ajouter_eq_espece(), Operateur_Conv_sensibility_VEF::ajouter_Lsensibility_state_Amont(), Operateur_Conv_sensibility_VEF::ajouter_Lstate_sensibility_Amont(), Op_Diff_VEF_Face_Stab::ajouter_operateur_centre(), Source_Masse_Fluide_Dilatable_VEF::ajouter_projection(), Op_Grad_VEF_P1B_Face::ajouter_som(), Op_Div_VEFP1B_Elem::ajouter_som(), Op_Conv_ALE_VEF::ajouterALE(), Source_Con_Phase_field::assembler_matrice_point_fixe(), Op_Diff_VDF_Face_Axi_base::associer(), Op_Dift_VDF_Face_Axi_base::associer(), Force_Centrifuge_VDF_Face_Axi::associer_domaines(), Op_Diff_VEF_Face_Penalise::autre_face(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calc_elem_elem(), Modele_turbulence_scal_LES_dyn_VDF::calc_elem_elem(), Modele_Jones_Launder_VEF::Calcul_D(), Modele_Launder_Sharma_VEF::Calcul_D(), Modele_Jones_Launder_VEF::Calcul_D_BiK(), Modele_Launder_Sharma_VEF::Calcul_D_BiK(), Champ_Face_VDF::calcul_duidxj(), Modele_Jones_Launder_VDF::Calcul_E(), Modele_Jones_Launder_Thermique_VDF::Calcul_E(), Traitement_particulier_NS_THI_VDF::calcul_Ec_D(), Parcours_interface::calcul_eq_plan(), Champ_front_contact_VEF::calcul_grads_locaux(), Maillage_FT_Disc::calcul_indicatrice(), Champ_Face_VDF::calcul_S_barre_sans_contrib_paroi(), Traitement_particulier_NS_THI_VDF::calcul_skewness_ordre_2(), Transport_Interfaces_FT_Disc::calcul_tolerance_projete_diphasique(), Transport_Interfaces_FT_Disc::calcul_tolerance_projete_monophasique(), Champ_P1NC::calcul_y_plus(), Champ_P1NC::calcul_y_plus_diphasique(), Champ_Q1NC_implementation::calcule_valeur_a_elem_compo(), Source_Con_Phase_field::calculer_alpha_gradC_carre(), Modele_turbulence_hyd_LES_DSGS_VDF::calculer_cell_cent_vel(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calculer_cell_cent_vel(), Op_Diff_VEF_Face_Stab::calculer_coefficients(), Topologie_Maillage_FT::calculer_composantes_connexes_pour_suppression(), Navier_Stokes_FT_Disc::calculer_delta_u_interface(), Champ_Face_VDF::calculer_dercov_axi(), Transport_Interfaces_FT_Disc::calculer_distance_interface(), Transport_Interfaces_FT_Disc::calculer_distance_interface_faces(), Op_Diff_P1NC_barprim::calculer_divergence(), Op_Dift_VEF_P1NCP1B_Face::calculer_divergence_elem(), Op_Diff_VEFP1NCP1B_Face::calculer_divergence_elem(), Op_Dift_VEF_P1NCP1B_Face::calculer_divergence_som(), Op_Diff_VEFP1NCP1B_Face::calculer_divergence_som(), Champ_Face_VDF::calculer_dscald_centre_element(), Op_Diff_K_Eps_Bas_Re_VDF_var_Elem::calculer_dt_stab(), Op_Dift_Multiphase_VDF_Elem::calculer_dt_stab(), Op_Conv_Muscl_New_VEF_Face::calculer_dt_stab(), Op_Dift_VDF_Elem_base::calculer_dt_stab_elem(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab_elem(), Op_Dift_VDF_Elem_base::calculer_dt_stab_elem_axi(), Op_Dift_VDF_Elem_base::calculer_dt_stab_elem_var_axi(), Op_Dift_VEF_base::calculer_dt_stab_P1NCP1B(), Modele_turbulence_hyd_Longueur_Melange_VEF::calculer_f_amortissement(), Parcours_interface::calculer_face_sortie_element(), Modele_turbulence_scal_LES_dyn_VDF::calculer_filter_coeff(), Modele_turbulence_hyd_LES_DSGS_VDF::calculer_filter_coeff(), Modele_turbulence_hyd_LES_DSGS_VDF::calculer_filter_field(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calculer_filter_field(), Modele_turbulence_hyd_LES_DSGS_VDF::calculer_filter_tensor(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calculer_filter_tensor(), Modele_turbulence_hyd_LES_VDF::calculer_fonction_structure(), Modele_turbulence_hyd_LES_1elt_VEF::calculer_fonction_structure(), Modele_turbulence_hyd_LES_VEF::calculer_fonction_structure(), Modele_turbulence_hyd_LES_axi_VDF::calculer_fonction_structure(), Terme_Source_Coriolis_VDF_Face::calculer_force_de_Coriolis(), Op_Dift_VEF_P1NCP1B_Face::calculer_gradient_elem(), Op_Diff_VEFP1NCP1B_Face::calculer_gradient_elem(), Op_Dift_VEF_P1NCP1B_Face::calculer_gradient_som(), Op_Diff_VEFP1NCP1B_Face::calculer_gradient_som(), Op_Diff_VEF_Face_Stab::calculer_gradients(), ParoiVDF_TBLE_LRM::calculer_hyd(), Paroi_std_hyd_VEF::calculer_hyd(), Paroi_negligeable_VEF::calculer_hyd(), Paroi_std_hyd_VEF_diphasique::calculer_hyd(), Paroi_2couches_VDF::calculer_hyd(), Paroi_loi_Ciofalo_hyd_VDF::calculer_hyd(), Paroi_loi_WW_hyd_VEF::calculer_hyd(), ParoiVDF_TBLE::calculer_hyd(), ParoiVEF_TBLE::calculer_hyd(), ParoiVDF_TBLE::calculer_hyd_BiK(), ParoiVDF_TBLE_LRM::calculer_hyd_BiK(), Paroi_std_hyd_VEF::calculer_hyd_BiK(), ParoiVEF_TBLE::calculer_hyd_BiK(), IJK_Interfaces::calculer_indicatrice(), IJK_Interfaces::calculer_indicatrices(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calculer_length_scale(), Modele_turbulence_hyd_LES_VDF_base::calculer_longueurs_caracteristiques(), Op_Diff_VEF_Face_Stab::calculer_max(), Op_Diff_VEF_Face_Stab::calculer_min(), Traitement_particulier_NS_canal_VDF::calculer_moyenne_spatiale_Temp(), Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_uv(), Traitement_particulier_NS_canal_VDF::calculer_moyenne_spatiale_vitesse_rho_mu(), Paroi_std_hyd_VDF::calculer_moyennes_parois(), Traitement_particulier_NS_Profils_thermo_VDF::calculer_moyennes_spatiales_thermo(), Modele_turbulence_hyd_LES_Wale_VDF::calculer_OP1_OP2(), Source_Transport_Fluctuation_Temperature_VDF_Elem::calculer_Prod_uteta_T(), Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::calculer_Prod_uteta_T(), Source_Transport_Fluctuation_Temperature_W_VDF_Elem::calculer_Prod_uteta_T(), Champ_Face_VDF::calculer_rotationnel_ordre2_centre_element(), Modele_turbulence_hyd_LES_Smago_filtre_VEF::calculer_S_barre(), Loi_Paroi_Nu_Impose_VDF::calculer_scal(), Loi_Paroi_Nu_Impose_VEF::calculer_scal(), ParoiVEF_TBLE_scal::calculer_scal(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calculer_Sij_vel_filt(), Calcul_Production_K_VDF::calculer_terme_destruction_K(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_W_VDF_Elem::calculer_terme_destruction_K_W(), Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::calculer_terme_destruction_K_W(), Source_Transport_Fluctuation_Temperature_W_VDF_Elem::calculer_terme_destruction_K_W(), Calcul_Production_K_VDF::calculer_terme_production_K(), Calcul_Production_K_VDF::calculer_terme_production_K_BiK(), Calcul_Production_K_VDF::calculer_terme_production_K_for_komega(), Source_Con_Phase_field::calculer_u2_elem(), Modele_turbulence_hyd_LES_axi_VDF::calculer_viscosite_turbulente(), Terme_Source_Acceleration_VDF_Face::calculer_vitesse_faces(), Transport_Interfaces_FT_Disc::calculer_vitesse_transport_interpolee(), Discretisation_tools::cells_to_faces(), Echange_contact_Correlation_VEF::completer(), Convection_Diffusion_Temperature_FT_Disc::compute_divergence_free_velocity_extension(), IJK_Interfaces::compute_drapeaux_vapeur_v4(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_friction_force_projected_tensor(), Navier_Stokes_FT_Disc::compute_particles_eulerian_id_number(), Transport_Interfaces_FT_Disc::compute_particles_rms(), Triple_Line_Model_FT_Disc::compute_TCL_fluxes_in_all_boundary_cells(), Champ_front_contact_VEF::connectivity_failed(), Op_Dift_VEF_Face_Q1::contribuer_a_avec(), Transport_K_Eps_base::controler_K_Eps(), Transport_K_Omega_base::controler_K_Omega(), Transport_K_ou_Eps_base::controler_variable(), Navier_Stokes_FT_Disc::correct_at_exit_bad_gradient(), Parcours_interface::coupe_face_rectangulaire(), Traitement_particulier_NS_CEG::critere_areva(), Modele_turbulence_hyd_LES_selectif_mod_VDF::cutoff(), Modele_turbulence_hyd_LES_selectif_VDF::cutoff(), Modele_turbulence_hyd_LES_1elt_selectif_mod_VEF::cutoff(), Modele_turbulence_hyd_LES_Fst_sel_VEF::cutoff(), Op_Div_VEFP1B_Elem::degres_liberte(), Op_Diff_VEF_Face_Penalise::diametre(), Op_EF_base::dimensionner(), Op_VDF_Face::dimensionner(), Op_VEF_Face::dimensionner(), Sauvegarde_Reprise_Maillage_FT::ecrire_xyz(), Viscosite_turbulente_WALE::eddy_viscosity(), Post_Processing_Hydrodynamic_Forces::elem_faces_for_interp(), Champ_val_tot_sur_vol_VEF::eval_contrib_loc(), Discretisation_tools::faces_to_cells(), Champ_P1NC_implementation::filtrer_L2(), Sortie_libre_Gradient_Pression_libre_VEF::flux_impose(), Champ_Generique_Tparoi_VEF::get_champ(), Triple_Line_Model_FT_Disc::get_theta_app(), Convection_Diffusion_Temperature_FT_Disc::get_Twall_at_elem(), Champ_input_P0::getTemplate(), Op_Diff_VEFP1NCP1B_Face::gradient_som(), Op_Diff_VEFP1NCP1B_Face::gradient_som_CL(), Loi_Paroi_Nu_Impose_VEF::imprimer_nusselt(), Postraitement::init(), ParoiVDF_TBLE::init_lois_paroi(), ParoiVDF_TBLE_LRM::init_lois_paroi(), ParoiVEF_TBLE::init_lois_paroi(), ParoiVEF_TBLE_scal::init_lois_paroi(), Sonde::initialiser(), Echange_contact_PolyMAC::initialiser(), Champ_front_lu::initialiser(), Transport_Interfaces_FT_Disc::interpoler_vitesse_face(), Domaine_ALE::laplacien(), Transport_Interfaces_FT_Disc::lire_maillage_ft_cao(), Perte_Charge_Singuliere::lire_surfaces(), Sauvegarde_Reprise_Maillage_FT::lire_xyz(), Op_Diff_VEFP1NCP1B_Face::liste_face(), Convection_Diffusion_Concentration_FT_Disc::marquer_faces_sous_domaine(), Convection_Diffusion_Concentration_Turbulent_FT_Disc::marquer_faces_sous_domaine(), Discretisation_base::mesh_numbering(), Domaine_ALE::mettre_a_jour(), Sortie_libre_Pression_imposee_Orlansky::mettre_a_jour(), Echange_contact_Correlation_VEF::mettre_a_jour(), Convection_Diffusion_Temperature::mise_en_place_domaine_fantome(), Tetra_VEF::modif_volumes_entrelaces(), Tri_VEF::modif_volumes_entrelaces(), Tetra_VEF::modif_volumes_entrelaces_faces_joints(), Tri_VEF::modif_volumes_entrelaces_faces_joints(), Assembleur_P_VEFPreP1B::modifier_secmem_som(), Champ_P1NC::norme_H1(), Terme_Source_Qdm_lambdaup_VEF_Face::norme_H1(), Terme_Source_Canal_RANS_LES_VDF_Face::norme_vit(), Parcours_interface::parcours_facette(), Convection_Diffusion_Temperature::penalisation_L2(), Op_Conv_DI_L2_VEF_Face::poly_DI_L2_2d(), Op_Conv_DI_L2_VEF_Face::poly_DI_L2_3d(), Postraitement::postraiter_champs(), Transport_Interfaces_FT_Disc::PPP_face_interface_voisin(), Transport_Interfaces_FT_Disc::PPP_face_voisin(), Transport_Interfaces_FT_Disc::projete_point_face_fluide(), Transport_Interfaces_FT_Disc::projete_point_face_interface(), Transport_Interfaces_FT_Disc::ramasse_miettes(), Op_Conv_DI_L2_VEF_Face::reconst_DI_L2_2d(), Op_Conv_DI_L2_VEF_Face::reconst_DI_L2_3d(), Porosites::remplir_champ(), Champ_front_contact_VEF::remplir_connect_bords(), Op_Conv_VEF_Face::remplir_fluent(), Operateur_Conv_sensibility_VEF::remplir_fluent(), Domaine_Cl_VEF::remplir_normales_facettes_Cl(), Perte_Charge_Reguliere_VDF_Face::remplir_num_faces(), Perte_Charge_Reguliere_VEF_P1NC::remplir_num_faces(), Traitement_particulier_NS_canal_VDF::remplir_Tab_recap(), Domaine_Cl_VEF::remplir_type_elem_Cl(), EDO_Pression_th_VDF_Gaz_Reel::resoudre(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::stabilise_moyenne_6_points(), Modele_turbulence_scal_LES_dyn_VDF::stabilise_moyenne_6_points(), Champ_Face_VDF_implementation::trace(), Champ_Q1NC_implementation::transforme_coord2D(), Champ_Q1NC_implementation::transforme_coord3D(), Convection_Diffusion_Temperature::transport_ibc(), Echange_contact_PolyMAC::update_coeffs(), Echange_contact_PolyMAC::update_delta(), Parcours_interface::uzawa2(), Champ_P1NC_implementation::valeur_a_elem(), Champ_Q1NC_implementation::valeur_a_elem(), Champ_Face_VDF_implementation::valeur_a_elem_compo(), Champ_P1NC_implementation::valeur_a_elem_compo(), Champ_P1NC_implementation::valeur_a_sommet_compo(), Champ_P1NC_implementation::valeur_aux_centres_de_gravite(), Champ_P1NC_implementation::valeur_aux_elems(), Champ_Q1NC_implementation::valeur_aux_elems(), Champ_P1NC_implementation::valeur_aux_elems_compo(), Champ_Q1NC_implementation::valeur_aux_elems_compo(), Champ_P1NC_implementation::valeur_aux_sommets(), Champ_P1NC_implementation::valeur_aux_sommets_compo(), Op_Diff_VEF_Face_Penalise::voisinage(), Parcours_interface::volume_barycentre_hexaedre(), Parcours_interface::volume_barycentre_rectangle(), Parcours_interface::volume_rectangle(), and Debog_Pb::write_geometry_data().
face_sommets() [1/3]
int Domaine_VF::face_sommets (int i, int j) const inline
renvoie le numero du ieme sommet de la face num_face.
References face_sommets_.
Referenced by Champ_P1NC::affecter_(), Op_Div_EF::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Div_VEFP1B_Elem::ajouter(), Source_Reaction_Particules_VDF::ajouter(), Source_Reaction_Particules_VEF::ajouter(), Op_Grad_VEF_P1B_Face::ajouter_aretes(), Op_Grad_EF::ajouter_bord(), Op_Diff_EF::ajouter_bords(), Op_Dift_EF_Q1::ajouter_bords(), Op_Diff_EF::ajouter_contributions_bords(), Op_Dift_EF_Q1::ajouter_contributions_bords(), Operateur_Conv_sensibility_VEF::ajouter_conv_term(), Operateur_Conv_sensibility_VEF::ajouter_Lsensibility_state_Amont(), Operateur_Conv_sensibility_VEF::ajouter_Lstate_sensibility_Amont(), Source_Masse_Fluide_Dilatable_VEF::ajouter_projection(), Op_Grad_VEF_P1B_Face::ajouter_som(), Op_Div_VEFP1B_Elem::ajouter_som(), Op_Conv_ALE_VEF::ajouterALE(), Solveur_Masse_EF::appliquer_impl(), Champ_Q1_EF::calcul_y_plus(), Source_Con_Phase_field::calculer_alpha_gradC_carre(), Op_Dift_VEF_P1NCP1B_Face::calculer_divergence_som(), Op_Diff_VEFP1NCP1B_Face::calculer_divergence_som(), Op_Grad_VEF_P1B_Face::calculer_flux_bords(), Op_Diff_VEFP1NCP1B_Face::calculer_flux_bords_som(), EDO_Pression_th_VEF::calculer_grad(), Op_Dift_VEF_P1NCP1B_Face::calculer_gradient_som(), Op_Diff_VEFP1NCP1B_Face::calculer_gradient_som(), Paroi_loi_WW_hyd_EF::calculer_hyd(), Paroi_std_hyd_EF::calculer_hyd(), Parcours_interface::calculer_sortie_face_bord(), Source_Con_Phase_field::calculer_u2_elem(), Domaine_ALE::calculer_vitesse(), Traitement_particulier_NS_THI_VDF::ch_vit_pour_fft(), Traitement_particulier_NS_THI_VDF::ch_vit_pour_fft_operateur(), Champ_Generique_Transformation::completer(), Champ_Post_Operateur_Eqn::completer(), Marching_Cubes::construire_noeuds_joints(), Traitement_particulier_NS_CEG::critere_cea_jaea(), Op_Div_VEFP1B_Elem::degres_liberte(), Op_EF_base::dimensionner(), Source_PDF_EF::filtre_CLD(), Champ_P1NC_implementation::filtrer_H1(), Champ_P1NC_implementation::filtrer_L2(), Champ_P1NC_implementation::filtrer_resu(), Champ_input_P0::getTemplate(), Op_Diff_VEFP1NCP1B_Face::gradient_som_CL(), Domaine_Cl_EF::imposer_cond_lim(), Domaine_Cl_VEF::imposer_cond_lim(), Domaine_Cl_EF::imposer_symetrie_partiellement(), Echange_contact_Correlation_VEF::init(), Postraitement::init(), Domaine_ALE::initialiser(), Extraire_domaine::interpreter_(), Domaine_ALE::laplacien(), Perte_Charge_Singuliere::lire_surfaces(), Op_Diff_VEF_Face_Penalise::longueur(), Domaine_ALE::mettre_a_jour(), Op_EF_base::modifier_pour_Cl(), Assembleur_P_VEFPreP1B::modifier_secmem_som(), Postraitement::postraiter_champs(), Connectivite_frontieres::remplir_faces_voisins(), Domaine_Cl_EF::remplir_type_elem_Cl(), Champ_Fonc_reprise_IJK::reprendre_IJK(), Champ_Q1NC_implementation::transforme_coord2D(), Champ_Q1NC_implementation::transforme_coord3D(), Champ_Face_VDF_implementation::valeur_a_elem_compo(), Champ_P1NC_implementation::valeur_aux_sommets(), Champ_P1NC_implementation::valeur_aux_sommets_compo(), and Assembleur_P_VEFPreP1B::verifier_dirichlet().
volumes() [2/3]
DoubleVect & Domaine_VF::volumes () inline
References volumes_.
Referenced by Domaine_EF::calculer_h_carre(), Domaine_Poly_base::calculer_h_carre(), Domaine_VEF::calculer_h_carre(), Domaine_PolyMAC::calculer_h_carre(), Domaine_EF::calculer_IPhi(), Domaine_VDF::calculer_volumes_entrelaces(), compute_L1_norm(), compute_L2_norm(), Domaine_DG::compute_mesh_param(), discretiser_no_face(), Domaine_PolyMAC::init_m1_3d(), Domaine_PolyMAC::init_m2solv(), Domaine_PolyMAC::init_we_2d(), Domaine_PolyMAC_P0P1NC::M1(), Domaine_PolyMAC::M2(), Domaine_VEF::modifier_pour_Cl(), Domaine_PolyMAC_P0P1NC::W1(), and Domaine_PolyMAC::W2().
inverse_volumes() [2/3]
DoubleVect & Domaine_VF::inverse_volumes () inline
References inverse_volumes_.
Referenced by discretiser_no_face().
volumes() [3/3]
const DoubleVect & Domaine_VF::volumes () const inline
References volumes_.
inverse_volumes() [3/3]
const DoubleVect & Domaine_VF::inverse_volumes () const inline
References inverse_volumes_.
face_voisins() [2/3]
IntTab & Domaine_VF::face_voisins () inline override virtual
renvoie le tableaux des volumes des connectivites face elements cf au dessus.
Reimplemented from Domaine_dis_base.
References face_voisins_.
Referenced by build_mc_dual_mesh(), construire_num_fac_loc(), Domaine_VDF::creer_elements_fictifs(), Domaine_Poly_base::detecter_faces_non_planes(), Domaine_DG::discretiser(), Domaine_EF::discretiser(), Domaine_Poly_base::discretiser(), Domaine_VEF::discretiser(), Domaine_Poly_base::dist_norm(), Domaine_Poly_base::dist_norm_bord(), face_voisins_reel_fictif(), Domaine_PolyMAC_P0::fgrad(), info_elem_som(), init_dist_paroi_globale(), Domaine_PolyMAC::init_equiv(), Domaine_PolyMAC::init_m2solv(), Domaine_PolyMAC_P0::init_stencils(), Domaine_PolyMAC::init_ve(), Domaine_PolyMAC::M2(), Domaine_VDF::modifier_pour_Cl(), normalized_boundaries_outward_vector(), Domaine_EF::oriente_normale(), Domaine_Poly_base::oriente_normale(), Domaine_VEF::oriente_normale(), and Domaine_PolyMAC::W2().
face_voisins() [3/3]
const IntTab & Domaine_VF::face_voisins () const inline override virtual
cf au dessus.
Reimplemented from Domaine_dis_base.
References face_voisins_.
face_voisins_fictifs()
const IntTab & Domaine_VF::face_voisins_fictifs () const inline
References face_voisins_fictifs_.
face_voisins_reel_fictif()
void Domaine_VF::face_voisins_reel_fictif (int face, int & el0, int & elf) const inline
renvoie dans el0 le numero de l'elt a l'interieur renvoie dans elf le numero de l'elt fictif (-1 si il n'existe pas)
References face_voisins(), face_voisins_fictifs_, and premiere_face_int().
elem_faces() [2/3]
IntTab & Domaine_VF::elem_faces () inline
renvoie le tableau de connectivite element/faces
References elem_faces_.
Referenced by Domaine_DG::build_nfaces_elem_(), Domaine_EF::calculer_h_carre(), Domaine_Poly_base::calculer_h_carre(), Domaine_VEF::calculer_h_carre(), Domaine_PolyMAC::calculer_h_carre(), Domaine_DG::compute_mesh_param(), construire_num_fac_loc(), Domaine_DG::discretiser(), Domaine_EF::discretiser(), Domaine_Poly_base::discretiser(), Domaine_VDF::dist_elem_period(), Domaine_Poly_base::elem_arete_d(), Domaine_PolyMAC_P0::fgrad(), Domaine_PolyMAC::init_equiv(), Domaine_PolyMAC::init_m1_2d(), Domaine_PolyMAC::init_m2solv(), Domaine_PolyMAC::init_ve(), Domaine_PolyMAC::init_we_2d(), Domaine_PolyMAC::init_we_3d(), Domaine_PolyMAC_P0P1NC::M1(), Domaine_PolyMAC::M2(), Domaine_VDF::modifier_pour_Cl(), Domaine_Poly_base::orthocentrer(), Domaine_PolyMAC_P0P1NC::surf_elem_arete(), Domaine_VEF::vecteur_face_facette(), Domaine_Poly_base::vol_elem_som(), Domaine_PolyMAC_P0P1NC::W1(), and Domaine_PolyMAC::W2().
elem_faces() [3/3]
const IntTab & Domaine_VF::elem_faces () const inline
cf au dessus.
References elem_faces_.
faces_doubles() [1/2]
ArrOfInt & Domaine_VF::faces_doubles () inline
renvoie 1 pour les faces appartenant a un bord perio ou un item commun, 0 par defaut
References faces_doubles_.
Referenced by Op_Conv_VEF_Face::ajouter(), Terme_Source_Canal_perio_VEF_P1NC::ajouter(), Terme_Source_Constituant_Vortex_VEF_Face::calculer(), Traitement_particulier_NS_EC::calculer_Ec(), Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_nut(), Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_vitesse_rho_mu(), Champ_val_tot_sur_vol_VEF::eval_contrib_loc(), Convection_Diffusion_Concentration_FT_Disc::mettre_a_jour(), Convection_Diffusion_Concentration_Turbulent_FT_Disc::mettre_a_jour(), Convection_Diffusion_Concentration_FT_Disc::multiplier_valeurs_faces(), Convection_Diffusion_Concentration_Turbulent_FT_Disc::multiplier_valeurs_faces(), and Traitement_particulier_NS_canal_VEF::remplir_Y().
faces_doubles() [2/2]
const ArrOfInt & Domaine_VF::faces_doubles () const inline
cf au dessus
References faces_doubles_.
face_sommets() [2/3]
IntTab & Domaine_VF::face_sommets () inline override virtual
renvoie le tableau de connectivite faces/sommets.
Reimplemented from Domaine_dis_base.
References face_sommets_.
Referenced by build_mc_face_mesh(), Domaine_DG::compute_mesh_param(), Domaine_VEF::construire_renum_arete_perio(), Domaine_EF::discretiser(), Domaine_Poly_base::discretiser(), Domaine_VDF::dist_face_period(), Domaine_PolyMAC_P0::fgrad(), init_dist_paroi_globale(), Domaine_PolyMAC::init_rf(), Domaine_PolyMAC_P0::init_stencils(), Domaine_PolyMAC_P0P1NC::M1(), Domaine_Poly_base::orthocentrer(), Domaine_PolyMAC_P0P1NC::surf_elem_arete(), Domaine_Poly_base::vol_elem_som(), and Domaine_PolyMAC_P0P1NC::W1().
face_sommets() [3/3]
const IntTab & Domaine_VF::face_sommets () const inline override virtual
cf au dessus.
Reimplemented from Domaine_dis_base.
References face_sommets_.
modifier_pour_Cl()
void Domaine_VF::modifier_pour_Cl (const Conds_lim & conds_lim) override virtual
Implements Domaine_dis_base.
Reimplemented in Domaine_PolyMAC, Domaine_VEF, and Domaine_VDF.
References construire_num_fac_loc(), Periodique::face_associee(), face_voisins_, Cond_lim_base::frontiere_dis(), marquer_faces_double_contrib(), Front_VF::nb_faces(), Front_VF::nb_faces_tot(), Front_VF::num_face(), and Front_VF::num_premiere_face().
Referenced by Domaine_VDF::modifier_pour_Cl().
numero_face_local()
int Domaine_VF::numero_face_local (int face, int elem) const
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), and elem_faces_.
Referenced by construire_num_fac_loc(), and Sauvegarde_Reprise_Maillage_FT::ecrire_xyz().
numero_sommet_local()
int Domaine_VF::numero_sommet_local (int som, int elem) const inline
References Domaine_dis_base::domaine(), Domaine_32_64< _SIZE_ >::les_elems(), and Domaine_32_64< _SIZE_ >::nb_som_elem().
Referenced by Op_Curl_VEFP1B::ajouter().
get_num_fac_loc() [1/2]
const IntTab & Domaine_VF::get_num_fac_loc () const inline
References num_fac_loc_.
Referenced by Op_Diff_VEF_Face_Stab::calculer_gradients(), and Champ_P1_isoP1Bulle::valeur_au_bord().
get_num_fac_loc() [2/2]
int Domaine_VF::get_num_fac_loc (int face, int voisin) const inline
References num_fac_loc_.
construire_num_fac_loc()
void Domaine_VF::construire_num_fac_loc ()
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), elem_faces(), elem_faces_, face_voisins(), face_voisins_, nb_faces_tot(), num_fac_loc_, numero_face_local(), and TRUSTTab< _TYPE_, _SIZE_ >::resize().
Referenced by modifier_pour_Cl(), and Domaine_VEF::modifier_pour_Cl().
ind_faces_virt_bord()
const ArrOfInt & Domaine_VF::ind_faces_virt_bord () const inline
References Domaine_dis_base::domaine(), and Domaine_32_64< _SIZE_ >::ind_faces_virt_bord().
Referenced by est_une_face_virt_bord(), and fbord().
est_une_face_virt_bord()
int Domaine_VF::est_une_face_virt_bord (int face) const inline
renvoie 1 si face est une face virtuelle de bord, 0 sinon
References ind_faces_virt_bord(), and nb_faces().
Referenced by Op_Diff_VEFP1NCP1B_Face::liste_face().
fbord()
int Domaine_VF::fbord (int f) const inline
References ind_faces_virt_bord(), nb_faces(), and premiere_face_int().
Referenced by Domaine_PolyMAC_P0::init_stencils().
construire_face_virt_pe_num()
void Domaine_VF::construire_face_virt_pe_num ()
Remplissage du tableau face_virt_pe_num_ (voir commentaire dans Domaine_VF.
h)
References creer_tableau_faces(), nb_faces(), and nb_faces_tot().
Referenced by Transport_Interfaces_FT_Disc::discretiser().
face_virt_pe_num()
const IntTab & Domaine_VF::face_virt_pe_num () const
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), and face_virt_pe_num_.
Referenced by Maillage_FT_Disc::echanger_sommets_PE().
creer_tableau_faces()
void Domaine_VF::creer_tableau_faces (Array_base & t, RESIZE_OPTIONS opt = RESIZE_OPTIONS::COPY_INIT) const
References MD_Vector_tools::creer_tableau_distribue(), and md_vector_faces_.
Referenced by Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Operateur_Conv_sensibility_VEF::ajouter_conv_term(), Op_Conv_ALE_VEF::ajouterALE(), Domaine_Cl_VEF::associer(), Modele_Lam_Bremhorst_VEF::Calcul_Cmu(), Modele_Lam_Bremhorst_VEF::Calcul_Cmu_BiK(), Modele_Shih_Zhu_Lumley_VEF::Calcul_Cmu_et_S(), Modele_Shih_Zhu_Lumley_VEF::Calcul_Cmu_et_S_BiK(), Modele_Lam_Bremhorst_VEF::Calcul_Cmu_Paroi(), Modele_Lam_Bremhorst_VEF::Calcul_Cmu_Paroi_BiK(), Modele_Jones_Launder_VDF::Calcul_E(), Modele_Jones_Launder_VEF::Calcul_E(), Modele_Launder_Sharma_VEF::Calcul_E(), Traitement_particulier_NS_THI_VEF::calcul_Ec_spatial(), Modele_EASM_Baglietto_VEF::Calcul_F1(), Modele_Lam_Bremhorst_VEF::Calcul_F1(), Modele_EASM_Baglietto_VEF::Calcul_F1_BiK(), Modele_Lam_Bremhorst_VEF::Calcul_F1_BiK(), Modele_Lam_Bremhorst_VEF::Calcul_Fmu(), Modele_EASM_Baglietto_VEF::Calcul_Fmu(), Modele_EASM_Baglietto_VEF::Calcul_Fmu_BiK(), Modele_Lam_Bremhorst_VEF::Calcul_Fmu_BiK(), Traitement_particulier_NS_THI_VEF::calcul_moyenne(), Perte_Charge_Singuliere::calculate_Q(), Domaine_EF::calculer_volumes_entrelaces(), Domaine_VDF::calculer_volumes_entrelaces(), Domaine_VEF::calculer_volumes_entrelaces(), Domaine_PolyMAC::calculer_volumes_entrelaces(), Domaine_PolyMAC_P0P1NC::calculer_volumes_entrelaces(), construire_face_virt_pe_num(), Domaine_EF::discretiser(), Domaine_Poly_base::discretiser(), Domaine_VDF::discretiser(), Domaine_VEF::discretiser(), init_dist_paroi_globale(), Domaine_PolyMAC::init_equiv(), Modele_Lam_Bremhorst_VEF::init_tenseur_face(), Modele_Shih_Zhu_Lumley_VEF::init_tenseur_face(), Domaine_PolyMAC::init_virt_ef_map(), Echange_contact_PolyMAC::initialiser(), Echange_contact_VDF::initialiser(), Champ_Fonc_Interp::initialiser(), Convection_Diffusion_Temperature::lire_motcle_non_standard(), Perte_Charge_Singuliere::lire_surfaces(), DP_Impose_PolyMAC_Face::remplir_num_faces(), DP_Impose_VEF_Face::remplir_num_faces(), and Iterateur_Source_VEF_Face< _TYPE_ >::remplir_volumes_cl_dirichlet().
creer_tableau_aretes()
void Domaine_VF::creer_tableau_aretes (Array_base & t, RESIZE_OPTIONS opt = RESIZE_OPTIONS::COPY_INIT) const
References MD_Vector_tools::creer_tableau_distribue(), and md_vector_aretes().
Referenced by Op_Diff_VEFP1NCP1B_Face::ajouter_contribution(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab(), Domaine_VEF::construire_renum_arete_perio(), Domaine_VEF::discretiser_arete(), Domaine_Poly_base::discretiser_aretes(), Op_Diff_VEFP1NCP1B_Face::initialiser(), and Domaine_VEF::lecture_ok_arete().
creer_tableau_faces_bord()
void Domaine_VF::creer_tableau_faces_bord (Array_base & t, RESIZE_OPTIONS opt = RESIZE_OPTIONS::COPY_INIT) const
References MD_Vector_tools::creer_tableau_distribue(), and md_vector_faces_bord().
Referenced by Periodique::completer(), Domaine_Cl_VDF::completer(), ParoiVDF_TBLE_LRM::init_lois_paroi(), Paroi_hyd_base_EF::init_lois_paroi_(), Paroi_hyd_base_VEF::init_lois_paroi_(), and xv_bord().
md_vector_faces_bord()
const MD_Vector & Domaine_VF::md_vector_faces_bord () const inline
References md_vector_faces_front_.
Referenced by creer_tableau_faces_bord(), nb_faces_bord_tot(), and xv_bord().
md_vector_faces()
const MD_Vector & Domaine_VF::md_vector_faces () const inline
References md_vector_faces_.
Referenced by Domaine_VEF::calculer_volumes_entrelaces(), Domaine_PolyMAC_P0::discretiser(), Domaine_Poly_base::discretiser_aretes(), Champ_Fonc_Face_PolyMAC::fixer_nb_valeurs_nodales(), Champ_Q1NC::fixer_nb_valeurs_nodales(), Champ_P1NC::fixer_nb_valeurs_nodales(), Champ_Face_VDF::fixer_nb_valeurs_nodales(), Champ_Fonc_Face_VDF::fixer_nb_valeurs_nodales(), Champ_Fonc_P1NC::fixer_nb_valeurs_nodales(), Champ_Fonc_Q1NC::fixer_nb_valeurs_nodales(), Modele_turbulence_hyd_K_Omega::init_F1_F2_enstrophy(), Domaine_ALE::initialiser(), Debog_Pb::read_geometry_data(), and Debog_Pb::write_geometry_data().
md_vector_aretes()
const MD_Vector & Domaine_VF::md_vector_aretes () const inline
References md_vector_aretes_.
Referenced by creer_tableau_aretes(), Domaine_Poly_base::discretiser_aretes(), Domaine_VEF::discretiser_suite(), Domaine_VEF::lecture_ok_arete(), Debog_Pb::read_geometry_data(), and Debog_Pb::write_geometry_data().
xv_bord()
const DoubleTab & Domaine_VF::xv_bord () const virtual
References TRUSTArray< _TYPE_, _SIZE_ >::addr(), creer_tableau_faces_bord(), Objet_U::dimension, TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), TRUSTVect< _TYPE_, _SIZE_ >::get_md_vector(), md_vector_faces_bord(), premiere_face_int(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), xv_, and xv_bord_.
Referenced by Milieu_composite::calculer_masse_volumique().
calculer_xgr()
DoubleTab Domaine_VF::calculer_xgr () const
calcul le tableau xgr pour le calcul des moments des forces aux bords :
References Domaine_32_64< _SIZE_ >::cg_moments(), Objet_U::dimension, Domaine_dis_base::domaine(), nb_faces(), premiere_face_int(), and xv().
Referenced by Op_Grad_VEF_P1B_Face::impr(), Op_EF_base::impr(), Op_VEF_Face::impr(), and Op_Grad_VDF_Face::impr().
get_position()
void Domaine_VF::get_position (DoubleTab & positions) const virtual
Reimplemented in Domaine_DG.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Domaine_dis_base::nb_elem(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTTab< _TYPE_, _SIZE_ >::view_ro(), TRUSTTab< _TYPE_, _SIZE_ >::view_wo(), xp(), and xp_.
Referenced by Champ_Generique_Transformation::get_champ().
compute_L1_norm()
double Domaine_VF::compute_L1_norm (const DoubleVect & val_source) const virtual
Reimplemented in Domaine_DG.
References Domaine_dis_base::nb_elem(), and volumes().
compute_L2_norm()
double Domaine_VF::compute_L2_norm (const DoubleVect & val_source) const virtual
Reimplemented in Domaine_DG.
References Domaine_dis_base::nb_elem(), and volumes().
get_nb_integ_points()
void Domaine_VF::get_nb_integ_points (IntTab & nelem) const virtual
Reimplemented in Domaine_DG.
References Process::exit().
Referenced by Champ_Generique_Transformation::get_champ().
get_ind_integ_points()
void Domaine_VF::get_ind_integ_points (IntTab & nelem) const virtual
Reimplemented in Domaine_DG.
References Process::exit().
Referenced by Champ_Generique_Transformation::get_champ().
dot()
double Domaine_VF::dot (const double * a, const double * b, const double * ma = nullptr, const double * mb = nullptr) const inline
References Objet_U::dimension.
Referenced by Domaine_Poly_base::detecter_faces_non_planes(), Domaine_Poly_base::discretiser_aretes(), Domaine_Poly_base::dist_face_elem0(), Domaine_VEF::dist_face_elem0(), Domaine_Poly_base::dist_face_elem1(), Domaine_VEF::dist_face_elem1(), Domaine_Poly_base::dist_norm(), Domaine_Poly_base::dist_norm_bord(), Domaine_Poly_base::nu_dot(), and Domaine_Poly_base::vol_elem_som().
cross()
std::array< double, 3 > Domaine_VF::cross (int dima, int dimb, const double * a, const double * b, const double * ma = nullptr, const double * mb = nullptr) const inline
Referenced by Domaine_Poly_base::vol_elem_som().
dist_norm()
virtual double Domaine_VF::dist_norm (int) const inline virtual
Reimplemented in Domaine_Poly_base, and Domaine_VDF.
dist_norm_bord()
virtual double Domaine_VF::dist_norm_bord (int) const inline virtual
Reimplemented in Domaine_Poly_base, and Domaine_VDF.
dist_face_elem0()
virtual double Domaine_VF::dist_face_elem0 (int , int) const inline virtual
Reimplemented in Domaine_Poly_base, Domaine_VEF, and Domaine_VDF.
Referenced by init_dist_paroi_globale().
dist_face_elem1()
virtual double Domaine_VF::dist_face_elem1 (int , int) const inline virtual
Reimplemented in Domaine_Poly_base, Domaine_VEF, and Domaine_VDF.
Referenced by init_dist_paroi_globale().
dist_face_elem0_period()
virtual double Domaine_VF::dist_face_elem0_period (int , int , double) const inline virtual
Reimplemented in Domaine_Poly_base, and Domaine_VDF.
dist_face_elem1_period()
virtual double Domaine_VF::dist_face_elem1_period (int , int , double) const inline virtual
Reimplemented in Domaine_Poly_base, and Domaine_VDF.
init_dist_paroi_globale()
void Domaine_VF::init_dist_paroi_globale (const Conds_lim & conds_lim) override virtual
Methode inspiree de Raccord_distant_homogene::initialise
Reimplemented from Domaine_dis_base.
References Domaine_32_64< _SIZE_ >::coord_sommets(), MD_Vector_tools::creer_tableau_distribue(), Domaine_32_64< _SIZE_ >::creer_tableau_elements(), creer_tableau_faces(), Objet_U::dimension, dist_face_elem0(), dist_face_elem1(), Domaine_dis_base::dist_paroi_initialisee_, Domaine_dis_base::domaine(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Process::exit(), face_normales(), face_sommets(), face_surfaces(), face_voisins(), TRUSTVect< _TYPE_, _SIZE_ >::get_md_vector(), Domaine_base::le_nom(), Process::me(), Process::mp_max(), n_y_elem_, n_y_faces_, Domaine_dis_base::nb_elem(), nb_faces(), nb_som_face(), Process::nproc(), Objet_U::precision_geom, Objet_U::que_suis_je(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUST_Vector< _CLASSE_ >::resize(), TRUST_Vector< _CLASSE_ >::size(), xp(), xv(), Domaine_dis_base::y_elem_, and Domaine_dis_base::y_faces_.
normale_paroi_elem()
const DoubleTab & Domaine_VF::normale_paroi_elem () const inline
References n_y_elem_.
normale_paroi_faces()
const DoubleTab & Domaine_VF::normale_paroi_faces () const inline
References n_y_faces_.
build_mc_face_mesh()
void Domaine_VF::build_mc_face_mesh () const
Build the MEDCoupling face mesh. It is always made of polygons (in 3D) for simplicity purposes. Face numbers (and node numbers) are the same as in TRUST.
It unfortunately needs a Domaine_dis_base since this is at this level that the face_sommets relationship is held ... As a consequence also the faces of a Domaine can not be postprocessed before discretisation. Another consequence is that it is not available for 64 bits domains.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, TRUSTTab< _TYPE_, _SIZE_ >::dimension_int(), Domaine_dis_base::domaine(), Process::exit(), and face_sommets().
build_mc_dual_mesh()
void Domaine_VF::build_mc_dual_mesh () const
Build the dual mesh of the domain for post-processing of face fields.
For each face of each element, a polyhedron is built with faces being made of
the original face
triangles buit with the element center of mass and each of the segment of the original face Thus an inner face of the domain has two associated dual polyhedral elements, and a boundary face has only one associated dual element. The member face_dual_ is also completed and has the same logic and exact same ordering as face_voisins_.
References TRUSTArray< _TYPE_, _SIZE_ >::addr(), Process::check_int_overflow(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Domaine_dis_base::domaine(), face_dual_, face_voisins(), face_voisins_, Objet_U::le_nom(), Domaine_dis_base::nb_elem(), Domaine_32_64< _SIZE_ >::nb_elem(), Domaine_32_64< _SIZE_ >::nb_som(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), and xp_.
build_map_mc_Cmesh()
void Domaine_VF::build_map_mc_Cmesh (const bool with_faces) override virtual
Build internal MEDCoupling cartesian mesh and correspondances
Reimplemented from Domaine_dis_base.
References Domaine_dis_base::domaine(), Process::exit(), Objet_U::que_suis_je(), and Domaine_32_64< _SIZE_ >::type_elem().
Member Data Documentation
info_obj
const Type_info Domaine_VF::info_obj static
volumes_
DoubleVect Domaine_VF::volumes_ protected
Referenced by Domaine_EF::calculer_Bij(), Domaine_EF::calculer_volumes_entrelaces(), Domaine_EF::calculer_volumes_sommets(), Domaine_PolyMAC::init_ve(), Domaine_PolyMAC::init_we_3d(), Domaine_EF::modifier_pour_Cl(), Domaine_Poly_base::modifier_pour_Cl(), Domaine_PolyMAC::modifier_pour_Cl(), printOn(), readOn(), and volumes().
inverse_volumes_
DoubleVect Domaine_VF::inverse_volumes_ protected
Referenced by inverse_volumes().
volumes_entrelaces_
DoubleVect Domaine_VF::volumes_entrelaces_ protected
Referenced by Domaine_EF::calculer_volumes_entrelaces(), Domaine_VDF::calculer_volumes_entrelaces(), Domaine_VEF::calculer_volumes_entrelaces(), Domaine_PolyMAC::calculer_volumes_entrelaces(), Domaine_PolyMAC_P0P1NC::calculer_volumes_entrelaces(), Domaine_Poly_base::ecrit(), Domaine_EF::modifier_pour_Cl(), Domaine_Poly_base::modifier_pour_Cl(), Domaine_PolyMAC::modifier_pour_Cl(), Domaine_VEF::modifier_pour_Cl(), Domaine_EF::printOn(), Domaine_Poly_base::printOn(), printOn(), Domaine_VEF::printOn(), Domaine_EF::readOn(), Domaine_Poly_base::readOn(), readOn(), Domaine_VEF::readOn(), and volumes_entrelaces().
volumes_entrelaces_dir_
DoubleTab Domaine_VF::volumes_entrelaces_dir_ protected
Referenced by Domaine_VDF::calculer_volumes_entrelaces(), Domaine_PolyMAC::calculer_volumes_entrelaces(), Domaine_PolyMAC_P0P1NC::calculer_volumes_entrelaces(), Domaine_Poly_base::volumes_entrelaces_dir(), and volumes_entrelaces_dir().
face_normales_
DoubleTab Domaine_VF::face_normales_ protected
Referenced by Domaine_PolyMAC_P0P1NC::calculer_volumes_entrelaces(), Domaine_Poly_base::detecter_faces_non_planes(), Domaine_EF::discretiser(), Domaine_Poly_base::discretiser(), Domaine_VEF::discretiser(), Domaine_Poly_base::dist_face_elem0(), Domaine_VEF::dist_face_elem0(), Domaine_Poly_base::dist_face_elem1(), Domaine_VEF::dist_face_elem1(), Domaine_Poly_base::dist_norm(), Domaine_Poly_base::dist_norm_bord(), Domaine_Poly_base::ecrit(), face_normales(), Domaine_EF::modifier_pour_Cl(), Domaine_Poly_base::modifier_pour_Cl(), Domaine_PolyMAC::modifier_pour_Cl(), Domaine_VEF::modifier_pour_Cl(), Domaine_Poly_base::orthocentrer(), Domaine_EF::printOn(), Domaine_Poly_base::printOn(), Domaine_VEF::printOn(), Domaine_EF::readOn(), Domaine_Poly_base::readOn(), and Domaine_VEF::readOn().
face_voisins_
IntTab Domaine_VF::face_voisins_ protected
Referenced by Domaine_VDF::amont_amont(), build_mc_dual_mesh(), Domaine_EF::calculer_volumes_entrelaces(), Domaine_VDF::calculer_volumes_entrelaces(), Domaine_PolyMAC::calculer_volumes_entrelaces(), Domaine_PolyMAC_P0P1NC::calculer_volumes_entrelaces(), construire_num_fac_loc(), Domaine_VEF::construire_renum_arete_perio(), Domaine_VDF::dim_face(), Domaine_VDF::discretiser(), Domaine_VDF::dist_norm(), Domaine_VDF::dist_norm_axi(), Domaine_VDF::dist_norm_bord(), Domaine_VDF::dist_norm_bord_axi(), Domaine_VDF::dist_norm_period(), Domaine_VDF::distance_normale(), Domaine_VDF::elem_voisin(), Domaine_VDF::face_amont_conj(), Domaine_VDF::face_amont_princ(), Domaine_VDF::face_bord_amont(), face_voisins(), Domaine_EF::modifier_pour_Cl(), Domaine_Poly_base::modifier_pour_Cl(), modifier_pour_Cl(), Domaine_PolyMAC::modifier_pour_Cl(), Domaine_VEF::modifier_pour_Cl(), printOn(), and readOn().
face_voisins_fictifs_
IntTab Domaine_VF::face_voisins_fictifs_ protected
Referenced by Domaine_VDF::creer_elements_fictifs(), face_voisins_fictifs(), and face_voisins_reel_fictif().
xp_
DoubleTab Domaine_VF::xp_ protected
Referenced by build_mc_dual_mesh(), Domaine_PolyMAC::calculer_volumes_entrelaces(), Domaine_PolyMAC_P0P1NC::calculer_volumes_entrelaces(), Domaine_VDF::dist_elem(), Domaine_VDF::dist_elem_period(), Domaine_Poly_base::dist_face_elem0(), Domaine_VEF::dist_face_elem0(), Domaine_VDF::dist_face_elem0(), Domaine_VDF::dist_face_elem0_axi(), Domaine_VDF::dist_face_elem0_period(), Domaine_Poly_base::dist_face_elem1(), Domaine_VEF::dist_face_elem1(), Domaine_VDF::dist_face_elem1(), Domaine_VDF::dist_face_elem1_axi(), Domaine_VDF::dist_face_elem1_period(), Domaine_Poly_base::dist_norm(), Domaine_VDF::dist_norm(), Domaine_VDF::dist_norm_axi(), Domaine_Poly_base::dist_norm_bord(), Domaine_VDF::dist_norm_bord(), Domaine_VDF::dist_norm_bord_axi(), Domaine_VDF::dist_norm_period(), Domaine_VDF::distance_normale(), get_position(), Domaine_PolyMAC::init_equiv(), Domaine_PolyMAC::init_m1_2d(), Domaine_PolyMAC::init_m1_3d(), Domaine_PolyMAC::init_we_2d(), Domaine_PolyMAC::init_we_3d(), Domaine_EF::modifier_pour_Cl(), Domaine_Poly_base::modifier_pour_Cl(), Domaine_PolyMAC::modifier_pour_Cl(), Domaine_VEF::modifier_pour_Cl(), Domaine_EF::printOn(), Domaine_Poly_base::printOn(), printOn(), Domaine_VEF::printOn(), Domaine_EF::readOn(), Domaine_Poly_base::readOn(), readOn(), Domaine_VEF::readOn(), Domaine_Poly_base::vol_elem_som(), and xp().
xv_
DoubleTab Domaine_VF::xv_ protected
Referenced by Domaine_VDF::calculer_volumes_entrelaces(), Domaine_PolyMAC::calculer_volumes_entrelaces(), Domaine_PolyMAC_P0P1NC::calculer_volumes_entrelaces(), Domaine_Poly_base::detecter_faces_non_planes(), Domaine_VDF::dim_elem(), Domaine_Poly_base::discretiser(), Domaine_VDF::dist_elem_period(), Domaine_VDF::dist_face(), Domaine_VDF::dist_face_axi(), Domaine_Poly_base::dist_face_elem0(), Domaine_VEF::dist_face_elem0(), Domaine_VDF::dist_face_elem0(), Domaine_VDF::dist_face_elem0_axi(), Domaine_VDF::dist_face_elem0_period(), Domaine_Poly_base::dist_face_elem1(), Domaine_VEF::dist_face_elem1(), Domaine_VDF::dist_face_elem1(), Domaine_VDF::dist_face_elem1_axi(), Domaine_VDF::dist_face_elem1_period(), Domaine_VDF::dist_face_period(), Domaine_Poly_base::dist_norm_bord(), Domaine_VDF::dist_norm_bord(), Domaine_VDF::dist_norm_bord_axi(), Domaine_VDF::distance_face(), Domaine_VDF::distance_normale(), Domaine_PolyMAC::init_equiv(), Domaine_PolyMAC::init_m1_2d(), Domaine_PolyMAC::init_m1_3d(), Domaine_PolyMAC::init_rf(), Domaine_PolyMAC::init_we_2d(), Domaine_PolyMAC::init_we_3d(), Domaine_EF::modifier_pour_Cl(), Domaine_Poly_base::modifier_pour_Cl(), Domaine_PolyMAC::modifier_pour_Cl(), Domaine_VEF::modifier_pour_Cl(), Domaine_EF::printOn(), Domaine_Poly_base::printOn(), printOn(), Domaine_VEF::printOn(), Domaine_EF::readOn(), Domaine_Poly_base::readOn(), readOn(), Domaine_VEF::readOn(), Domaine_VEF::vecteur_face_facette(), Domaine_Poly_base::vol_elem_som(), xv(), and xv_bord().
xv_bord_
DoubleTab Domaine_VF::xv_bord_ mutable protected
Referenced by xv_bord().
elem_faces_
IntTab Domaine_VF::elem_faces_ protected
Referenced by Domaine_VDF::amont_amont(), Domaine_EF::calculer_Bij_gen(), Domaine_EF_axi::calculer_Bij_gen(), construire_num_fac_loc(), Domaine_VDF::dim_elem(), Domaine_DG::discretiser(), Domaine_Poly_base::discretiser(), discretiser(), elem_faces(), Domaine_VDF::elem_voisin(), Domaine_VDF::face_amont_conj(), Domaine_VDF::face_amont_princ(), Domaine_VDF::face_bord_amont(), Domaine_PolyMAC::init_m1_3d(), numero_face_local(), printOn(), readOn(), renumeroter(), and Domaine_VDF::reordonner().
face_sommets_
IntTab Domaine_VF::face_sommets_ protected
Referenced by Domaine_EF::calculer_Bij_gen(), Domaine_EF_axi::calculer_Bij_gen(), Domaine_Poly_base::detecter_faces_non_planes(), Domaine_Poly_base::discretiser(), face_sommets(), Domaine_PolyMAC::init_m1_2d(), Domaine_PolyMAC::init_m1_3d(), Domaine_PolyMAC::init_we(), Domaine_PolyMAC::init_we_2d(), Domaine_PolyMAC::init_we_3d(), nb_faces(), nb_faces_tot(), nb_som_face(), printOn(), and readOn().
xa_
DoubleTab Domaine_VF::xa_ protected
Referenced by Domaine_VEF::discretiser_arete(), Domaine_Poly_base::discretiser_aretes(), Domaine_PolyMAC::init_m1_3d(), Domaine_PolyMAC::init_rf(), Domaine_PolyMAC::init_we_3d(), Domaine_VEF::lecture_ok_arete(), Domaine_PolyMAC_P0P1NC::surf_elem_arete(), and xa().
face_numero_bord_
IntTab Domaine_VF::face_numero_bord_ protected
Referenced by face_numero_bord(), and remplir_face_numero_bord().
md_vector_faces_
MD_Vector Domaine_VF::md_vector_faces_ protected
Referenced by creer_tableau_faces(), and md_vector_faces().
md_vector_faces_front_
MD_Vector Domaine_VF::md_vector_faces_front_ protected
Referenced by md_vector_faces_bord().
md_vector_aretes_
MD_Vector Domaine_VF::md_vector_aretes_ protected
Referenced by Domaine_VEF::discretiser_arete(), Domaine_Poly_base::discretiser_aretes(), and md_vector_aretes().
les_bords_
TRUST_Vector< Front_VF > Domaine_VF::les_bords_ protected
Referenced by Domaine_Poly_base::dist_norm_bord(), Domaine_VDF::dist_norm_bord(), front_VF(), frontiere_dis(), nb_frontiere_dis(), printOn(), and readOn().
num_fac_loc_
IntTab Domaine_VF::num_fac_loc_ protected
Referenced by construire_num_fac_loc(), and get_num_fac_loc().
faces_doubles_
ArrOfInt Domaine_VF::faces_doubles_ protected
Referenced by faces_doubles(), and marquer_faces_double_contrib().
est_face_bord_
ArrOfInt Domaine_VF::est_face_bord_ protected
Referenced by est_face_bord(), and marquer_faces_double_contrib().
face_virt_pe_num_
IntTab Domaine_VF::face_virt_pe_num_ protected
Referenced by face_virt_pe_num().
n_y_elem_
DoubleTab Domaine_VF::n_y_elem_ protected
Referenced by init_dist_paroi_globale(), and normale_paroi_elem().
n_y_faces_
DoubleTab Domaine_VF::n_y_faces_ protected
Referenced by init_dist_paroi_globale(), and normale_paroi_faces().
nb_elem_std_
int Domaine_VF::nb_elem_std_ =-10 protected
Referenced by Domaine_Poly_base::ecrit(), Domaine_EF::nb_elem_Cl(), Domaine_Poly_base::nb_elem_Cl(), Domaine_VEF::nb_elem_Cl(), Domaine_EF::nb_elem_std(), Domaine_Poly_base::nb_elem_std(), Domaine_VEF::nb_elem_std(), Domaine_EF::printOn(), Domaine_Poly_base::printOn(), Domaine_VEF::printOn(), Domaine_EF::readOn(), Domaine_Poly_base::readOn(), Domaine_VEF::readOn(), Domaine_EF::reordonner(), and Domaine_Poly_base::reordonner().
nb_faces_std_
int Domaine_VF::nb_faces_std_ =-10 protected
Referenced by Domaine_Poly_base::ecrit(), Domaine_VEF::nb_faces_non_std(), Domaine_EF::nb_faces_std(), Domaine_Poly_base::nb_faces_std(), Domaine_VEF::nb_faces_std(), Domaine_VEF::premiere_face_std(), Domaine_EF::printOn(), Domaine_Poly_base::printOn(), Domaine_VEF::printOn(), Domaine_EF::readOn(), Domaine_Poly_base::readOn(), Domaine_VEF::readOn(), and renumeroter().
rang_elem_non_std_
IntVect Domaine_VF::rang_elem_non_std_ protected
Referenced by Domaine_Poly_base::ecrit(), Domaine_EF::printOn(), Domaine_Poly_base::printOn(), Domaine_VEF::printOn(), Domaine_EF::rang_elem_non_std(), Domaine_Poly_base::rang_elem_non_std(), Domaine_VEF::rang_elem_non_std(), Domaine_EF::readOn(), Domaine_Poly_base::readOn(), Domaine_VEF::readOn(), renumeroter(), Domaine_EF::reordonner(), Domaine_Poly_base::reordonner(), and Domaine_VEF::reordonner().
face_dual_
IntTab Domaine_VF::face_dual_ mutable protected
For each face f, face_dual_(f, j) returns the element built on the left and right of the face in the dual mesh. Same sorting as face_voisins_.
Referenced by build_mc_dual_mesh().