TrioCFD: Integrale_tps_Champ Class Reference
Integrale_tps_Champ Class Reference
#include <Integrale_tps_Champ.h>
Public Member Functions
const Type_info * get_info () const override
virtual void mettre_a_jour_integrale ()
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Integrale_tps_Champ()
Integrale_tps_Champ::Integrale_tps_Champ ()
~Integrale_tps_Champ()
Integrale_tps_Champ::~Integrale_tps_Champ ()
Member Function Documentation
cree_instance()
Objet_U * Integrale_tps_Champ::cree_instance () static
taille_memoire()
unsigned Integrale_tps_Champ::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Integrale_tps_produit_champs.
duplique()
int Integrale_tps_Champ::duplique () const override virtual
Implements Objet_U.
Reimplemented in Integrale_tps_produit_champs.
info()
const Type_info * Integrale_tps_Champ::info () static
get_info()
const Type_info * Integrale_tps_Champ::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
Reimplemented in Integrale_tps_produit_champs.
self_cast() [1/2]
Integrale_tps_Champ & Integrale_tps_Champ::self_cast (Objet_U & r) static
self_cast() [2/2]
const Integrale_tps_Champ & Integrale_tps_Champ::self_cast (const Objet_U & r) static
printOn()
Sortie & Integrale_tps_Champ::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
Reimplemented in Integrale_tps_produit_champs.
References Objet_U::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Integrale_tps_Champ::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
Reimplemented in Integrale_tps_produit_champs.
le_champ_calcule() [1/2]
const Champ_Fonc_base & Integrale_tps_Champ::le_champ_calcule () const inline
References le_champ_, and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by Op_Correlation::associer(), Op_Ecart_type::associer(), Op_Moyenne::associer(), Op_Correlation::calculer_valeurs(), Postraitement::champ_fonc(), Op_Correlation::completer(), Op_Ecart_type::completer(), Op_Moyenne::completer(), Postraitement::creer_champ_post_stat(), Op_Correlation::data_a_sauvegarder(), Op_Ecart_type::data_a_sauvegarder(), Op_Moyenne::data_a_sauvegarder(), Moyenne_volumique::get_champ(), Champ_Generique_Correlation::get_champ(), Champ_Generique_Correlation::get_champ_without_evaluation(), Champ_Generique_Correlation::get_property(), Op_Correlation::initialiser(), Op_Ecart_type::initialiser(), Op_Moyenne::initialiser(), Op_Correlation::le_nom(), Op_Ecart_type::le_nom(), Op_Moyenne::le_nom(), Op_Correlation::reprendre(), Op_Ecart_type::reprendre(), Op_Moyenne::reprendre(), Op_Correlation::sauvegarder(), Op_Ecart_type::sauvegarder(), Op_Moyenne::sauvegarder(), Op_Moyenne::set_pdi_name(), Champ_Generique_Correlation::temps(), Champ_Generique_Ecart_Type::temps(), Champ_Generique_Moyenne::temps(), Op_Correlation::temps(), Op_Ecart_type::temps(), Op_Moyenne::temps(), Champ_Generique_Ecart_Type::valeurs(), Op_Moyenne::valeurs(), Op_Correlation::valeurs_ab(), Op_Ecart_type::valeurs_carre(), and Champ_Generique_Ecart_Type::valeurs_carre().
le_champ_calcule() [2/2]
Champ_Fonc_base & Integrale_tps_Champ::le_champ_calcule () inline
References le_champ_, and TRUST_Deriv< _CLASSE_ >::valeur().
le_champ()
const TRUST_Ref< Champ_Generique_base * > & Integrale_tps_Champ::le_champ () const inline
References le_champ_ref_.
Referenced by Op_Correlation::completer(), Op_Ecart_type::completer(), Op_Moyenne::completer(), Operateur_Statistique_tps_base::completer_post_statistiques(), Champ_Generique_Ecart_Type::get_champ(), Champ_Generique_Moyenne::get_champ(), Champ_Generique_Ecart_Type::get_champ_without_evaluation(), Champ_Generique_Moyenne::get_champ_without_evaluation(), and Champ_Generique_Correlation::get_directive_pour_discr().
temps_integrale()
double Integrale_tps_Champ::temps_integrale () const inline
References tps_integrale_.
t_debut()
double Integrale_tps_Champ::t_debut () const inline
References t_debut_.
t_fin()
double Integrale_tps_Champ::t_fin () const inline
References t_fin_.
dt_integration()
double Integrale_tps_Champ::dt_integration () const inline
References dt_integr_calcul_.
Referenced by Op_Moyenne::dt_integration(), Op_Correlation::dt_integration_ab(), and Op_Ecart_type::dt_integration_carre().
fixer_t_debut()
void Integrale_tps_Champ::fixer_t_debut (double t) inline
References t_debut_.
Referenced by Op_Correlation::fixer_tstat_deb(), Op_Ecart_type::fixer_tstat_deb(), and Op_Moyenne::fixer_tstat_deb().
fixer_t_fin()
void Integrale_tps_Champ::fixer_t_fin (double t) inline
References t_fin_.
Referenced by Op_Moyenne::fixer_tstat_fin(), Op_Correlation::fixer_tstat_fin(), and Op_Ecart_type::fixer_tstat_fin().
fixer_dt_integr()
void Integrale_tps_Champ::fixer_dt_integr (double t) inline
References dt_integr_calcul_.
Referenced by Op_Correlation::fixer_tstat_deb(), Op_Ecart_type::fixer_tstat_deb(), and Op_Moyenne::fixer_tstat_deb().
fixer_tps_integrale()
void Integrale_tps_Champ::fixer_tps_integrale (double t) inline
References tps_integrale_.
Referenced by Op_Correlation::fixer_tstat_deb(), Op_Ecart_type::fixer_tstat_deb(), and Op_Moyenne::fixer_tstat_deb().
associer() [1/2]
void Integrale_tps_Champ::associer (const Champ_base & , int , double , double) inline
Referenced by Integrale_tps_produit_champs::associer(), Op_Ecart_type::associer(), and Op_Moyenne::associer().
associer() [2/2]
void Integrale_tps_Champ::associer (const Champ_Generique_base & le_ch, int n, double t0, double t1) inline
References dt_integr_calcul_, le_champ_ref_, puissance_, t_debut_, t_fin_, and tps_integrale_.
mettre_a_jour_integrale()
void Integrale_tps_Champ::mettre_a_jour_integrale () virtual
Mets a jour l'integrale.
Verifie que le temps de l'integrale est inferieur a celui du champ associe et poursuit l'integration jusqu'au temps courant. si la borne superieure de l'integrale n'est pas depassee.
Reimplemented in Integrale_tps_produit_champs.
References TRUSTVect< _TYPE_, _SIZE_ >::ajoute(), TRUSTVect< _TYPE_, _SIZE_ >::ajoute_carre(), dt_integr_calcul_, Process::exit(), TRUSTArray< _TYPE_, _SIZE_ >::isDataOnDevice(), le_champ_, le_champ_ref_, puissance_, TRUSTVect< _TYPE_, _SIZE_ >::size(), t_debut_, t_fin_, tps_integrale_, Champ_Don_base::valeurs(), and Champ_Proto::valeurs().
Referenced by mettre_a_jour().
mettre_a_jour()
virtual void Integrale_tps_Champ::mettre_a_jour (double) inline virtual
Reimplemented in Integrale_tps_produit_champs.
References Champ_base::changer_temps(), le_champ_, le_champ_ref_, and mettre_a_jour_integrale().
Referenced by Op_Moyenne::mettre_a_jour(), and Op_Ecart_type::mettre_a_jour().
typer_champ()
void Integrale_tps_Champ::typer_champ (const Nom & typ)
References le_champ_, and Objet_U_ptr::typer().
Referenced by Op_Correlation::associer(), Op_Ecart_type::associer(), Op_Moyenne::associer(), and Op_Correlation::completer().
Member Data Documentation
info_obj
const Type_info Integrale_tps_Champ::info_obj static
le_champ_
TRUST_Deriv< Champ_Fonc_base > Integrale_tps_Champ::le_champ_ protected
Referenced by Integrale_tps_produit_champs::ajoute_produit_tensoriel(), le_champ_calcule(), mettre_a_jour(), Integrale_tps_produit_champs::mettre_a_jour(), mettre_a_jour_integrale(), and typer_champ().
le_champ_ref_
TRUST_Ref< Champ_Generique_base *> Integrale_tps_Champ::le_champ_ref_ protected
Referenced by associer(), le_champ(), mettre_a_jour(), Integrale_tps_produit_champs::mettre_a_jour(), mettre_a_jour_integrale(), and Integrale_tps_produit_champs::mon_premier_champ().
puissance_
int Integrale_tps_Champ::puissance_ = -10 protected
Referenced by associer(), mettre_a_jour_integrale(), and Integrale_tps_produit_champs::premiere_puissance().
t_debut_
double Integrale_tps_Champ::t_debut_ = -100. protected
Referenced by associer(), fixer_t_debut(), mettre_a_jour_integrale(), Integrale_tps_produit_champs::mettre_a_jour_integrale(), and t_debut().
t_fin_
double Integrale_tps_Champ::t_fin_ = -100. protected
Referenced by associer(), fixer_t_fin(), mettre_a_jour_integrale(), Integrale_tps_produit_champs::mettre_a_jour_integrale(), and t_fin().
tps_integrale_
double Integrale_tps_Champ::tps_integrale_ = -100. protected
Referenced by associer(), fixer_tps_integrale(), mettre_a_jour_integrale(), Integrale_tps_produit_champs::mettre_a_jour_integrale(), and temps_integrale().
dt_integr_calcul_
double Integrale_tps_Champ::dt_integr_calcul_ = -100. protected
Referenced by associer(), dt_integration(), fixer_dt_integr(), mettre_a_jour_integrale(), and Integrale_tps_produit_champs::mettre_a_jour_integrale().