TrioCFD: Tensors_Computation_VEF Class Reference
Tensors_Computation_VEF Class Reference
#include <Tensors_Computation_VEF.h>
Constructor & Destructor Documentation
Tensors_Computation_VEF()
Tensors_Computation_VEF::Tensors_Computation_VEF () inline protected
Member Function Documentation
compute_enstrophy()
void TCV::compute_enstrophy (const Domaine_VEF & dom_VEF, const Domaine_Cl_VEF & dom_BC_VEF, const DoubleTab & velocity, DoubleTab & enstrophy) const protected
References antisym_loop_edge_faces(), antisym_loop_internal_faces(), Champ_P1NC::calcul_gradient(), Objet_U::dimension, and Domaine_dis_base::nb_elem_tot().
Referenced by Source_Transport_K_Omega_VEF_Face_base::ajouter_komega().
antisym_loop_edge_faces()
void TCV::antisym_loop_edge_faces (const Domaine_VEF & dom_VEF, const Domaine_Cl_VEF & dom_BC_VEF, const DoubleTab & gradient_elem, DoubleTab & enstrophy) const protected
References antisym_loop_edges_general(), antisym_loop_edges_periodiqueBC(), Domaine_Cl_dis_base::les_conditions_limites(), Domaine_dis_base::nb_front_Cl(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by compute_enstrophy().
antisym_loop_edges_general()
void TCV::antisym_loop_edges_general (const Domaine_VEF & dom_VEF, const Front_VF & the_edge, const DoubleTab & gradient_elem, DoubleTab & enstrophy) const protected
References Objet_U::dimension, Domaine_VF::face_voisins(), Front_VF::nb_faces(), and Front_VF::num_premiere_face().
Referenced by antisym_loop_edge_faces().
antisym_loop_edges_periodiqueBC()
void TCV::antisym_loop_edges_periodiqueBC (const Domaine_VEF & dom_VEF, const Front_VF & the_edge, const DoubleTab & gradient_elem, DoubleTab & enstrophy) const protected
References Objet_U::dimension, Domaine_VF::face_voisins(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), and Domaine_VF::volumes().
Referenced by antisym_loop_edge_faces().
antisym_loop_internal_faces()
void TCV::antisym_loop_internal_faces (const Domaine_VEF & dom_VEF, const DoubleTab & gradient_elem, DoubleTab & enstrophy) const protected
References Objet_U::dimension, Domaine_VF::face_voisins(), Domaine_VF::nb_faces(), Domaine_VF::premiere_face_int(), and Domaine_VF::volumes().
Referenced by compute_enstrophy().