TrioCFD: Paroi_TBLE_QDM_Scal Class Reference
Paroi_TBLE_QDM_Scal Class Reference abstract
#include <Paroi_TBLE_QDM_Scal.h>
Public Member Functions
void calculer_stat (int j, int i, double u, double v, double w, double T, double dt)
void imprimer_stat (Sortie &, double) const
int init_lois_paroi (const Domaine_VF &, const Domaine_Cl_dis_base &)
void init_valeurs_defaut ()
Entree & lire_donnees (const Motcle &motlu, Entree &s)
int reprendre (Entree &, const Domaine_dis_base &, const Domaine_Cl_dis_base &, double tps)
Detailed Description
.SECTION voir aussi Turbulence_paroi_scal_base
Constructor & Destructor Documentation
~Paroi_TBLE_QDM_Scal()
virtual Paroi_TBLE_QDM_Scal::~Paroi_TBLE_QDM_Scal () inline virtual
Member Function Documentation
lire_donnees()
Entree & Paroi_TBLE_QDM_Scal::lire_donnees (const Motcle & motlu, Entree & s)
Lecture des options de TBLE : a appeler dans readOn des classes filles
References Objet_U::dimension, TRUST_Vector< _CLASSE_ >::dimensionner(), eps_statio, epsilon, Process::exit(), fac, max_it, max_it_statio, modele_visco, nb_post_pts, nb_pts, nom_pts, oui_stats, Prandtl, TRUSTTab< _TYPE_, _SIZE_ >::resize(), restart, Motcles::search(), sonde_tble, statio, tps_deb_stats, and tps_fin_stats.
Referenced by Paroi_TBLE_scal_VDF::readOn(), and ParoiVEF_TBLE_scal::readOn().
init_lois_paroi()
int Paroi_TBLE_QDM_Scal::init_lois_paroi (const Domaine_VF & domaine_dis, const Domaine_Cl_dis_base & le_dom_Cl)
Initialise les tableaux (dimensionnement) : a appeler dans init_lois_paroi() des classes filles
References Alpha_mean_sum, Diffu_totale_hyd_base::associer_eqn_T(), Diffu_totale_base::associer_mulambda(), Objet_U::dimension, TRUST_Vector< _CLASSE_ >::dimensionner(), eq_temp, get_eq_couch_lim(), getMuLambda(), getPbBase(), is_init, Domaine_Cl_dis_base::les_conditions_limites(), modele_visco, Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), nb_post_pts, nb_pts, Front_VF::num_face(), num_faces_post, num_global_faces_post, Prandtl, TRUSTTab< _TYPE_, _SIZE_ >::resize(), Diffu_totale_scal_base::set_visco_tot(), Diffu_totale_scal_base::setPrandtl(), sonde_tble, Tmean_2_sum, Tmean_sum, UTmean_sum, TRUST_Deriv< _CLASSE_ >::valeur(), VTmean_sum, WTmean_sum, and Domaine_VF::xv().
Referenced by Paroi_TBLE_scal_VDF::init_lois_paroi(), and ParoiVEF_TBLE_scal::init_lois_paroi().
init_valeurs_defaut()
void Paroi_TBLE_QDM_Scal::init_valeurs_defaut ()
Initialise par defaut les attributs de la classe : a appeler dans readOn() des classes filles
References eps_statio, epsilon, fac, is_init, max_it, max_it_statio, modele_visco, nb_comp, nb_post_pts, nb_pts, oui_stats, Prandtl, reprise_ok, restart, statio, tps_deb_stats, and tps_fin_stats.
Referenced by Paroi_TBLE_scal_VDF::readOn(), and ParoiVEF_TBLE_scal::readOn().
reprendre()
int Paroi_TBLE_QDM_Scal::reprendre (Entree & , const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & le_dom_Cl, double tps)
Methodes d'arret/reprise a appeler pour les quantites TBLE
References Entree_Fichier_base::close(), Process::exit(), Entree_Fichier_base::fail(), getPbBase(), Domaine_Cl_dis_base::les_conditions_limites(), Process::me(), nb_comp, Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), nb_pts, Front_VF::num_premiere_face(), reprise_ok, TRUSTTab< _TYPE_, _SIZE_ >::resize(), restart, TRUST_Deriv< _CLASSE_ >::valeur(), and valeurs_reprises.
Referenced by Paroi_TBLE_scal_VDF::reprendre(), and ParoiVEF_TBLE_scal::reprendre().
sauvegarder()
int Paroi_TBLE_QDM_Scal::sauvegarder (Sortie & , const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & le_dom_Cl, double tps) const
References Sortie_Fichier_base::close(), eq_temp, Domaine_Cl_dis_base::les_conditions_limites(), Process::me(), nb_comp, Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), nb_pts, Front_VF::num_premiere_face(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by Paroi_TBLE_scal_VDF::sauvegarder(), and ParoiVEF_TBLE_scal::sauvegarder().
calculer_stat()
void Paroi_TBLE_QDM_Scal::calculer_stat (int j, int i, double u, double v, double w, double T, double dt)
Remplit les tableaux des quantites statistiques indice_post : indice de tableau du numero de postraitement a calculer (entre 0 et nb_post_pts) indice_maillage : indice correspondant au numero de maille dans le maillage 1D u, v, w, T: les composantes de la vitesse et de T sur la maille 1D "indice_maillage" de la face correspondante a "indice_post" dt : pas de temps courant
References Tmean_sum.
imprimer_stat()
void Paroi_TBLE_QDM_Scal::imprimer_stat (Sortie & , double tps) const
Impression des stats et des sondes TBLE dans les fichiers de sortie
References Objet_U::dimension, nb_post_pts, nb_pts, nom_pts, oui_stats, Tmean_2_sum, Tmean_sum, tps_deb_stats, UTmean_sum, VTmean_sum, and WTmean_sum.
Referenced by Paroi_TBLE_scal_VDF::imprimer_nusselt(), and ParoiVEF_TBLE_scal::imprimer_nusselt().
imprimer_sondes() [1/2]
void Paroi_TBLE_QDM_Scal::imprimer_sondes (Sortie & , double tps, const TRUST_Vector< DoubleVect > & distance_equivalente) const
References eq_temp, nb_post_pts, nb_pts, nom_pts, num_faces_post, and num_global_faces_post.
Referenced by Paroi_TBLE_scal_VDF::imprimer_nusselt(), and ParoiVEF_TBLE_scal::imprimer_nusselt().
imprimer_sondes() [2/2]
void Paroi_TBLE_QDM_Scal::imprimer_sondes (Sortie & , double tps, const DoubleVect & tab_d_equiv_) const
References eq_temp, nb_post_pts, nb_pts, nom_pts, num_faces_post, and num_global_faces_post.
get_eq_couche_lim_T()
Eq_couch_lim & Paroi_TBLE_QDM_Scal::get_eq_couche_lim_T (int i) inline
References eq_temp.
Referenced by ParoiVDF_TBLE_LRM::calculer_hyd(), ParoiVDF_TBLE::calculer_hyd(), ParoiVEF_TBLE::calculer_hyd(), ParoiVDF_TBLE::calculer_hyd_BiK(), ParoiVDF_TBLE_LRM::calculer_hyd_BiK(), and ParoiVEF_TBLE::calculer_hyd_BiK().
getPbBase()
virtual const Probleme_base & Paroi_TBLE_QDM_Scal::getPbBase () const pure virtual
Implemented in Paroi_TBLE_scal_VDF, and ParoiVEF_TBLE_scal.
Referenced by init_lois_paroi(), and reprendre().
getLoiParoiHydraulique()
virtual Paroi_TBLE_QDM & Paroi_TBLE_QDM_Scal::getLoiParoiHydraulique () pure virtual
Implemented in Paroi_TBLE_scal_VDF, and ParoiVEF_TBLE_scal.
getMuLambda()
virtual MuLambda_TBLE_base & Paroi_TBLE_QDM_Scal::getMuLambda () pure virtual
Implemented in Paroi_TBLE_scal_VDF, and ParoiVEF_TBLE_scal.
Referenced by init_lois_paroi().
get_eq_couch_lim()
virtual Eq_couch_lim & Paroi_TBLE_QDM_Scal::get_eq_couch_lim (int) pure virtual
Implemented in Paroi_TBLE_scal_VDF, and ParoiVEF_TBLE_scal.
Referenced by init_lois_paroi().
est_initialise()
int Paroi_TBLE_QDM_Scal::est_initialise () const inline
References is_init.
Referenced by ParoiVDF_TBLE::calculer_hyd(), ParoiVEF_TBLE::calculer_hyd(), ParoiVDF_TBLE::calculer_hyd_BiK(), and ParoiVEF_TBLE::calculer_hyd_BiK().
Member Data Documentation
statio
int Paroi_TBLE_QDM_Scal::statio protected
Referenced by Paroi_TBLE_scal_VDF::calculer_scal(), ParoiVEF_TBLE_scal::calculer_scal(), init_valeurs_defaut(), and lire_donnees().
max_it_statio
int Paroi_TBLE_QDM_Scal::max_it_statio protected
Referenced by Paroi_TBLE_scal_VDF::calculer_scal(), ParoiVEF_TBLE_scal::calculer_scal(), init_valeurs_defaut(), and lire_donnees().
eps_statio
double Paroi_TBLE_QDM_Scal::eps_statio protected
Referenced by Paroi_TBLE_scal_VDF::calculer_scal(), ParoiVEF_TBLE_scal::calculer_scal(), init_valeurs_defaut(), and lire_donnees().
modele_visco
Motcle Paroi_TBLE_QDM_Scal::modele_visco protected
Referenced by init_lois_paroi(), init_valeurs_defaut(), and lire_donnees().
nb_post_pts
int Paroi_TBLE_QDM_Scal::nb_post_pts protected
Referenced by imprimer_sondes(), imprimer_stat(), init_lois_paroi(), init_valeurs_defaut(), and lire_donnees().
sonde_tble
DoubleTab Paroi_TBLE_QDM_Scal::sonde_tble protected
Referenced by init_lois_paroi(), and lire_donnees().
nom_pts
Noms Paroi_TBLE_QDM_Scal::nom_pts protected
Referenced by imprimer_sondes(), imprimer_stat(), and lire_donnees().
num_faces_post
IntTab Paroi_TBLE_QDM_Scal::num_faces_post protected
Referenced by imprimer_sondes(), and init_lois_paroi().
num_global_faces_post
IntTab Paroi_TBLE_QDM_Scal::num_global_faces_post protected
Referenced by imprimer_sondes(), and init_lois_paroi().
nb_pts
int Paroi_TBLE_QDM_Scal::nb_pts protected
Referenced by Paroi_TBLE_scal_VDF::calculer_scal(), ParoiVEF_TBLE_scal::calculer_scal(), imprimer_sondes(), imprimer_stat(), Paroi_TBLE_scal_VDF::init_lois_paroi(), ParoiVEF_TBLE_scal::init_lois_paroi(), init_lois_paroi(), init_valeurs_defaut(), lire_donnees(), reprendre(), and sauvegarder().
nb_comp
int Paroi_TBLE_QDM_Scal::nb_comp protected
Referenced by Paroi_TBLE_scal_VDF::init_lois_paroi(), ParoiVEF_TBLE_scal::init_lois_paroi(), init_valeurs_defaut(), reprendre(), and sauvegarder().
oui_stats
int Paroi_TBLE_QDM_Scal::oui_stats protected
Referenced by Paroi_TBLE_scal_VDF::calculer_scal(), ParoiVEF_TBLE_scal::calculer_scal(), imprimer_stat(), ParoiVEF_TBLE_scal::init_lois_paroi(), init_valeurs_defaut(), and lire_donnees().
max_it
int Paroi_TBLE_QDM_Scal::max_it protected
Referenced by ParoiVEF_TBLE_scal::calculer_scal(), Paroi_TBLE_scal_VDF::init_lois_paroi(), ParoiVEF_TBLE_scal::init_lois_paroi(), init_valeurs_defaut(), and lire_donnees().
fac
double Paroi_TBLE_QDM_Scal::fac protected
Referenced by Paroi_TBLE_scal_VDF::init_lois_paroi(), ParoiVEF_TBLE_scal::init_lois_paroi(), init_valeurs_defaut(), and lire_donnees().
epsilon
double Paroi_TBLE_QDM_Scal::epsilon protected
Referenced by Paroi_TBLE_scal_VDF::init_lois_paroi(), ParoiVEF_TBLE_scal::init_lois_paroi(), init_valeurs_defaut(), and lire_donnees().
tps_deb_stats
double Paroi_TBLE_QDM_Scal::tps_deb_stats protected
Referenced by imprimer_stat(), ParoiVEF_TBLE_scal::init_lois_paroi(), init_valeurs_defaut(), and lire_donnees().
tps_fin_stats
double Paroi_TBLE_QDM_Scal::tps_fin_stats protected
Referenced by init_valeurs_defaut(), and lire_donnees().
nu_t_dyn
int Paroi_TBLE_QDM_Scal::nu_t_dyn protected
Referenced by Paroi_TBLE_scal_VDF::init_lois_paroi(), and ParoiVEF_TBLE_scal::init_lois_paroi().
eq_temp
TRUST_Vector< Eq_couch_lim > Paroi_TBLE_QDM_Scal::eq_temp protected
Referenced by Paroi_TBLE_scal_VDF::calculer_scal(), ParoiVEF_TBLE_scal::calculer_scal(), get_eq_couche_lim_T(), imprimer_sondes(), Paroi_TBLE_scal_VDF::init_lois_paroi(), ParoiVEF_TBLE_scal::init_lois_paroi(), init_lois_paroi(), and sauvegarder().
reprise_ok
int Paroi_TBLE_QDM_Scal::reprise_ok protected
Referenced by Paroi_TBLE_scal_VDF::init_lois_paroi(), ParoiVEF_TBLE_scal::init_lois_paroi(), init_valeurs_defaut(), and reprendre().
valeurs_reprises
DoubleTab Paroi_TBLE_QDM_Scal::valeurs_reprises protected
Referenced by Paroi_TBLE_scal_VDF::init_lois_paroi(), ParoiVEF_TBLE_scal::init_lois_paroi(), and reprendre().
restart
int Paroi_TBLE_QDM_Scal::restart protected
Referenced by init_valeurs_defaut(), lire_donnees(), and reprendre().
Tmean_sum
DoubleTab Paroi_TBLE_QDM_Scal::Tmean_sum protected
Referenced by calculer_stat(), imprimer_stat(), and init_lois_paroi().
UTmean_sum
DoubleTab Paroi_TBLE_QDM_Scal::UTmean_sum protected
Referenced by imprimer_stat(), and init_lois_paroi().
VTmean_sum
DoubleTab Paroi_TBLE_QDM_Scal::VTmean_sum protected
Referenced by imprimer_stat(), and init_lois_paroi().
WTmean_sum
DoubleTab Paroi_TBLE_QDM_Scal::WTmean_sum protected
Referenced by imprimer_stat(), and init_lois_paroi().
Tmean_2_sum
DoubleTab Paroi_TBLE_QDM_Scal::Tmean_2_sum protected
Referenced by imprimer_stat(), and init_lois_paroi().
Alpha_mean_sum
DoubleTab Paroi_TBLE_QDM_Scal::Alpha_mean_sum protected
Referenced by init_lois_paroi().
is_init
int Paroi_TBLE_QDM_Scal::is_init protected
Referenced by est_initialise(), init_lois_paroi(), and init_valeurs_defaut().
Prandtl
double Paroi_TBLE_QDM_Scal::Prandtl protected
Referenced by init_lois_paroi(), init_valeurs_defaut(), and lire_donnees().