TrioCFD: Cut_field_template< _TYPE_, _TYPE_ARRAY_ > Class Template Reference
Cut_field_template< _TYPE_, _TYPE_ARRAY_ > Class Template Reference
#include <Cut_field.h>
Additional Inherited Members
Public Member Functions inherited from Field_base
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
virtual void fixer_nb_comp (int i)
virtual const Nom & fixer_nom_compo (const Nom &)
virtual const Nom & fixer_nom_compo (int, const Nom &)
virtual const Noms & fixer_noms_compo (const Noms &)
virtual const Nom & fixer_unite (const Nom &)
virtual const Nom & fixer_unite (int i, const Nom &)
virtual const Noms & fixer_unites (const Noms &)
const Type_info * get_info () const override
const Nom & nom_compo (int) const
void nommer (const Nom &) override
const Nom & unite () const
const Nom & unite (int) const
const Noms & unites () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >
Sortie & printOn (Sortie &os) const override
Entree & readOn (Entree &is) override
Sortie & printOn (Sortie &os) const override
Entree & readOn (Entree &is) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Constructor & Destructor Documentation
Cut_field_template()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::Cut_field_template
Member Function Documentation
echange_espace_virtuel()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > void Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel (int ghost)
References IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel().
Referenced by IJK_Thermal_cut_cell::perform_thermal_step().
copie_pure_vers_diph_sans_interpolation()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > void Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::copie_pure_vers_diph_sans_interpolation
Referenced by IJK_Thermal_cut_cell::copie_pure_vers_diph_sans_interpolation().
echange_pure_vers_diph_cellules_initialement_pures()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > void Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::echange_pure_vers_diph_cellules_initialement_pures
Referenced by IJK_Thermal_cut_cell::echange_pure_vers_diph_cellules_initialement_pures().
check_agreement_diph_pure_cellules_initialement_pures()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > bool Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::check_agreement_diph_pure_cellules_initialement_pures
check_agreement_diph_pure_cellules_finalement_pures()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > bool Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::check_agreement_diph_pure_cellules_finalement_pures
References IJK_Interfaces::convert_indicatrice_to_phase().
echange_diph_vers_pure_cellules_finalement_pures()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > void Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::echange_diph_vers_pure_cellules_finalement_pures
Referenced by IJK_Thermal_cut_cell::echange_diph_vers_pure_cellules_finalement_pures(), and IJK_Thermal_cut_cell::perform_thermal_step().
vide_phase_invalide_cellules_diphasiques()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > void Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::vide_phase_invalide_cellules_diphasiques
References IJK_Interfaces::convert_indicatrice_to_phase().
Referenced by IJK_Thermal_cut_cell::vide_phase_invalide_cellules_diphasiques().
check_agreement_tableau_pure_cellules_diphasiques()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > bool Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::check_agreement_tableau_pure_cellules_diphasiques (bool next_time) const
remplir_tableau_pure_cellules_diphasiques()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > void Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::remplir_tableau_pure_cellules_diphasiques (bool next_time)
Referenced by IJK_Thermal_cut_cell::perform_thermal_step(), and IJK_Thermal_cut_cell::remplir_tableau_pure_cellules_diphasiques().
remplir_tableau_pure_cellules_diphasiques_max()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > void Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::remplir_tableau_pure_cellules_diphasiques_max (bool next_time)
Referenced by IJK_Thermal_cut_cell::remplir_tableau_pure_cellules_diphasiques().
set_field_data()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > void Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::set_field_data (const Nom & parser_expression_of_x_y_z_and_t, const IJK_Field_template< _TYPE_, _TYPE_ARRAY_ > & input_f, const double current_time)
Referenced by IJK_Thermal_cut_cell::compute_temperature_init(), and IJK_Thermal_cut_cell::recompute_temperature_init().
set_to_uniform_value()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > void Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::set_to_uniform_value (_TYPE_ valeur)
References IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::data().
Referenced by IJK_Thermal_cut_cell::add_temperature_diffusion(), and IJK_Thermal_cut_cell::compute_temperature_convection_cut_cell().
set_to_sum()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > void Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::set_to_sum (const Cut_field_template< _TYPE_, _TYPE_ARRAY_ > & data_1, const Cut_field_template< _TYPE_, _TYPE_ARRAY_ > & data_2)
References Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::diph_l_, Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::diph_v_, IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), and Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::pure_().
associer_persistant()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > void Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::associer_persistant (Cut_cell_FT_Disc & cut_cell_disc)
Referenced by Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::allocate_persistant().
associer_ephemere()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > void Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::associer_ephemere (Cut_cell_FT_Disc & cut_cell_disc)
Referenced by Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::allocate_ephemere().
associer_paresseux()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > void Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::associer_paresseux (Cut_cell_FT_Disc & cut_cell_disc)
Referenced by Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::allocate_paresseux().
copy_from()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > void Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::copy_from (const Cut_field_template< _TYPE_, _TYPE_ARRAY_ > & data)
References Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::diph_l_, Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::diph_v_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), and Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::pure_().
Referenced by IJK_Thermal_cut_cell::add_temperature_diffusion(), and IJK_Thermal_cut_cell::perform_thermal_step().
add_from()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > void Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::add_from (const Cut_field_template< _TYPE_, _TYPE_ARRAY_ > & data, _TYPE_ constant = 1)
References Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::diph_l_, Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::diph_v_, IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), and Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::pure_().
get_cut_cell_disc()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > const Cut_cell_FT_Disc & Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::get_cut_cell_disc () const inline
References Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::cut_cell_disc_, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Cut_cell_schema_auxiliaire::add_dying_cells(), Cut_cell_schema_auxiliaire::add_small_nascent_cells(), Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_copie_directe(), Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_ponderation_voisin(), Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_semi_lagrangien(), Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_semi_lagrangien_interpolate(), Cut_cell_schema_auxiliaire::compute_flux_dying_cells(), Cut_cell_schema_auxiliaire::compute_flux_small_nascent_cells(), IJK_Thermal_cut_cell::compute_temperature_init(), Cut_cell_convection_auxiliaire::dying_cells_flux(), Cut_cell_diffusion_auxiliaire::dying_cells_flux(), IJK_Thermal_cut_cell::perform_thermal_step(), IJK_Thermal_cut_cell::recompute_temperature_init(), Cut_cell_convection_auxiliaire::small_nascent_cells_flux(), and Cut_cell_diffusion_auxiliaire::small_nascent_cells_flux().
allocate_persistant()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > void Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::allocate_persistant (Cut_cell_FT_Disc & cut_cell_disc, const Domaine_IJK & splitting, Domaine_IJK::Localisation loc, int ghost_size, int additional_k_layers = 0, int nb_compo = 1) inline
References IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::allocate(), Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::associer_persistant(), and Field_base::le_nom().
Referenced by IJK_Thermal_cut_cell::initialize().
allocate_ephemere()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > void Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::allocate_ephemere (Cut_cell_FT_Disc & cut_cell_disc, const Domaine_IJK & splitting, Domaine_IJK::Localisation loc, int ghost_size, int additional_k_layers = 0, int nb_compo = 1) inline
References IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::allocate(), Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::associer_ephemere(), and Field_base::le_nom().
Referenced by IJK_Thermal_cut_cell::initialize().
allocate_paresseux()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > void Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::allocate_paresseux (Cut_cell_FT_Disc & cut_cell_disc, const Domaine_IJK & splitting, Domaine_IJK::Localisation loc, int ghost_size, int additional_k_layers = 0, int nb_compo = 1) inline
References IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::allocate(), Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::associer_paresseux(), and Field_base::le_nom().
dumplata_scalar()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > void Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::dumplata_scalar (const char * filename, int step) const override virtual
Reimplemented from IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >.
from_signed_independent_index() [1/2]
template<typename _TYPE_ , typename _TYPE_ARRAY_ > _TYPE_ & Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::from_signed_independent_index (int signed_independent_index)
from_signed_independent_index() [2/2]
template<typename _TYPE_ , typename _TYPE_ARRAY_ > const _TYPE_ & Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::from_signed_independent_index (int signed_independent_index) const
from_ijk_and_phase() [1/2]
template<typename _TYPE_ , typename _TYPE_ARRAY_ > _TYPE_ & Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::from_ijk_and_phase (int i, int j, int k, bool phase)
from_ijk_and_phase() [2/2]
template<typename _TYPE_ , typename _TYPE_ARRAY_ > const _TYPE_ & Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::from_ijk_and_phase (int i, int j, int k, bool phase) const
from_n_num_face_and_phase() [1/2]
template<typename _TYPE_ , typename _TYPE_ARRAY_ > _TYPE_ & Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::from_n_num_face_and_phase (int n, int num_face, bool phase)
from_n_num_face_and_phase() [2/2]
template<typename _TYPE_ , typename _TYPE_ARRAY_ > const _TYPE_ & Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::from_n_num_face_and_phase (int n, int num_face, bool phase) const
compute_global_energy_cut_cell()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > CutCell_GlobalInfo Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::compute_global_energy_cut_cell (bool next, double constant_l, double constant_v) const
Referenced by IJK_Thermal_cut_cell::perform_thermal_step().
compute_d_global_energy_cut_cell()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > CutCell_GlobalInfo Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::compute_d_global_energy_cut_cell (bool next) const
Referenced by IJK_Thermal_cut_cell::perform_thermal_step().
compute_norm_cut_cell()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > CutCell_GlobalInfo Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::compute_norm_cut_cell (bool next) const
compute_min_cut_cell()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > CutCell_GlobalInfo Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::compute_min_cut_cell (bool next) const
Referenced by IJK_Thermal_cut_cell::print_Tmin_Tmax_cut_cell().
compute_max_cut_cell()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > CutCell_GlobalInfo Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::compute_max_cut_cell (bool next) const
Referenced by IJK_Thermal_cut_cell::print_Tmin_Tmax_cut_cell().
get_value_location()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > Nom Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::get_value_location (_TYPE_ T) const
References Cut_cell_FT_Disc::get_n(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), and IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk().
Referenced by IJK_Thermal_cut_cell::print_Tmin_Tmax_cut_cell().
pure_() [1/2]
template<typename _TYPE_ , typename _TYPE_ARRAY_ > _TYPE_ & Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::pure_ (int i, int j, int k) inline
References IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::operator()().
Referenced by Cut_cell_schema_auxiliaire::add_dying_cells(), Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::add_from(), Cut_cell_schema_auxiliaire::add_small_nascent_cells(), Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_ponderation_voisin(), Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_semi_lagrangien(), Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::copy_from(), Cut_cell_convection_auxiliaire::dying_cells_flux(), Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::set_to_sum(), and Cut_cell_convection_auxiliaire::small_nascent_cells_flux().
pure_() [2/2]
template<typename _TYPE_ , typename _TYPE_ARRAY_ > const _TYPE_ & Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::pure_ (int i, int j, int k) const inline
References IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::operator()().
operator()() [1/4]
template<typename _TYPE_ , typename _TYPE_ARRAY_ > _TYPE_ & Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::operator() (int i, int j, int k) inline
References Process::exit(), and IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::operator()().
operator()() [2/4]
template<typename _TYPE_ , typename _TYPE_ARRAY_ > const _TYPE_ & Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::operator() (int i, int j, int k) const inline
References Process::exit(), and IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::operator()().
operator()() [3/4]
template<typename _TYPE_ , typename _TYPE_ARRAY_ > _TYPE_ & Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::operator() (int i, int j, int k, int compo) inline
References Process::exit(), and IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::operator()().
operator()() [4/4]
template<typename _TYPE_ , typename _TYPE_ARRAY_ > const _TYPE_ & Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::operator() (int i, int j, int k, int compo) const inline
References Process::exit(), and IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::operator()().
multiply_by_scalar()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > void Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::multiply_by_scalar (_TYPE_ scalar_l, _TYPE_ scalar_v)
divide_by_scalar()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > void Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::divide_by_scalar (_TYPE_ scalar_l, _TYPE_ scalar_v)
Referenced by IJK_Thermal_cut_cell::add_temperature_diffusion(), and IJK_Thermal_cut_cell::compute_temperature_convection_cut_cell().
Member Data Documentation
diph_l_
template<typename _TYPE_ , typename _TYPE_ARRAY_ > TRUSTTabFT_cut_cell<_TYPE_> Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::diph_l_
Referenced by Cut_cell_schema_auxiliaire::add_dying_cells(), Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::add_from(), Cut_cell_schema_auxiliaire::add_small_nascent_cells(), Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_copie_directe(), Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_ponderation_voisin(), Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_semi_lagrangien(), OpConvQuickIJKScalar_cut_cell_double::compute_cut_cell_divergence(), Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::copy_from(), Cut_cell_convection_auxiliaire::dying_cells_flux(), Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::set_to_sum(), and Cut_cell_convection_auxiliaire::small_nascent_cells_flux().
diph_v_
template<typename _TYPE_ , typename _TYPE_ARRAY_ > TRUSTTabFT_cut_cell<_TYPE_> Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::diph_v_
Referenced by Cut_cell_schema_auxiliaire::add_dying_cells(), Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::add_from(), Cut_cell_schema_auxiliaire::add_small_nascent_cells(), Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_copie_directe(), Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_ponderation_voisin(), Cut_cell_schema_auxiliaire::calcule_valeur_remplissage_semi_lagrangien(), OpConvQuickIJKScalar_cut_cell_double::compute_cut_cell_divergence(), Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::copy_from(), Cut_cell_convection_auxiliaire::dying_cells_flux(), Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::set_to_sum(), and Cut_cell_convection_auxiliaire::small_nascent_cells_flux().
cut_cell_disc_
template<typename _TYPE_ , typename _TYPE_ARRAY_ > TRUST_Ref< Cut_cell_FT_Disc *> Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::cut_cell_disc_ protected
Referenced by Cut_field_template< _TYPE_, _TYPE_ARRAY_ >::get_cut_cell_disc().