TrioCFD: IJK_Composantes_Connex Class Reference
IJK_Composantes_Connex Class Reference
#include <IJK_Composantes_Connex.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
IJK_Composantes_Connex()
IJK_Composantes_Connex::IJK_Composantes_Connex ()
~IJK_Composantes_Connex()
IJK_Composantes_Connex::~IJK_Composantes_Connex ()
Member Function Documentation
cree_instance()
Objet_U * IJK_Composantes_Connex::cree_instance () static
taille_memoire()
unsigned IJK_Composantes_Connex::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int IJK_Composantes_Connex::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * IJK_Composantes_Connex::info () static
get_info()
const Type_info * IJK_Composantes_Connex::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
IJK_Composantes_Connex & IJK_Composantes_Connex::self_cast (Objet_U & r) static
self_cast() [2/2]
const IJK_Composantes_Connex & IJK_Composantes_Connex::self_cast (const Objet_U & r) static
printOn()
Sortie & IJK_Composantes_Connex::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
References Objet_U::printOn().
readOn()
Entree & IJK_Composantes_Connex::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
References Objet_U::readOn().
initialize()
void IJK_Composantes_Connex::initialize (IJK_Interfaces & interfaces, const bool is_switch)
References interfaces_, and is_switch_.
Referenced by IJK_Interfaces::initialize().
allocate_fields()
void IJK_Composantes_Connex::allocate_fields (const Domaine_IJK & splitting, const int & compute_compo_fields)
References IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::allocate(), compute_compo_fields_, compute_from_bounding_box_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::data(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel(), Domaine_IJK::ELEM, eulerian_compo_connex_from_interface_ft_, eulerian_compo_connex_from_interface_ghost_ft_, eulerian_compo_connex_from_interface_ghost_int_ns_, eulerian_compo_connex_from_interface_ghost_ns_, eulerian_compo_connex_from_interface_int_ns_, eulerian_compo_connex_from_interface_ns_, eulerian_compo_connex_ft_, eulerian_compo_connex_ghost_ft_, eulerian_compo_connex_ghost_ns_, eulerian_compo_connex_ns_, eulerian_compo_connex_valid_compo_field_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost(), is_switch_, Process::nproc(), and ref_ijk_ft_.
Referenced by IJK_Interfaces::allocate_ijk_compo_connex_fields().
associer()
void IJK_Composantes_Connex::associer (const Probleme_FTD_IJK_base & ijk_ft)
References ref_ijk_ft_.
Referenced by IJK_Interfaces::associer_pb_base().
initialise_bubbles_params()
void IJK_Composantes_Connex::initialise_bubbles_params ()
References bubbles_barycentre_, bubbles_volume_, IJK_Interfaces::calculer_volume_bulles(), and interfaces_.
Referenced by IJK_Interfaces::initialise_ijk_compo_connex_bubbles_params().
associate_rising_velocities_parameters()
void IJK_Composantes_Connex::associate_rising_velocities_parameters (const Domaine_IJK & splitting, const int & compute_rising_velocities, const int & fill_rising_velocities, const int & use_bubbles_velocities_from_interface, const int & use_bubbles_velocities_from_barycentres)
References IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::allocate(), compute_compo_fields_, compute_rising_velocities(), compute_rising_velocities_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::data(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel(), Domaine_IJK::ELEM, eulerian_rising_velocities_, fill_rising_velocities_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost(), use_bubbles_velocities_from_barycentres_, and use_bubbles_velocities_from_interface_.
Referenced by IJK_Interfaces::associate_rising_velocities_parameters().
compute_bounding_box_fill_compo_connex()
void IJK_Composantes_Connex::compute_bounding_box_fill_compo_connex ()
References Statistiques::begin_count(), bounding_box_, bubbles_barycentre_, IJK_Interfaces::calculer_bounding_box_bulles(), compute_compo_fields_, compute_from_bounding_box_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::data(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel(), Statistiques::end_count(), eulerian_compo_connex_ft_, eulerian_compo_connex_ghost_ft_, eulerian_compo_connex_ghost_ns_, eulerian_compo_connex_ns_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost(), interfaces_, min_max_larger_box_, Statistiques::new_counter(), Process::nproc(), and ref_ijk_ft_.
Referenced by IJK_Interfaces::compute_compo_connex_from_bounding_box().
compute_compo_connex_from_interface()
void IJK_Composantes_Connex::compute_compo_connex_from_interface ()
References TRUSTArray< _TYPE_, _SIZE_ >::append_array(), Statistiques::begin_count(), bubbles_barycentre_, bubbles_volume_, IJK_Interfaces::compute_bubbles_volume_and_barycentres(), compute_compo_fields_, Domaine_IJK::convert_ijk_cell_to_packed(), Domaine_IJK::convert_packed_to_ijk_cell(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel(), Statistiques::end_count(), eulerian_compo_connex_from_interface_ghost_int_ns_, eulerian_compo_connex_from_interface_int_ns_, eulerian_compo_connex_valid_compo_field_, fill_mixed_cell_compo(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_domaine(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost(), IJK_Interfaces::In(), interfaces_, Statistiques::new_counter(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), TRUSTArray< _TYPE_, _SIZE_ >::reset(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by IJK_Interfaces::compute_compo_connex_from_interface().
compute_rising_velocities()
void IJK_Composantes_Connex::compute_rising_velocities ()
References Statistiques::begin_count(), bubbles_volume_, compute_rising_velocities_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::data(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel(), Statistiques::end_count(), eulerian_compo_connex_from_interface_int_ns_, eulerian_rising_velocities_, fill_rising_velocities_, IJK_Interfaces::get_bubble_velocities_from_barycentres(), IJK_Interfaces::get_bubble_velocities_from_interface(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost(), interfaces_, liquid_velocity_, Statistiques::new_counter(), ref_ijk_ft_, rising_vectors_, rising_velocities_, rising_velocity_overall_, TRUSTVect< _TYPE_, _SIZE_ >::size(), use_bubbles_velocities_from_barycentres_, and use_bubbles_velocities_from_interface_.
Referenced by IJK_Interfaces::associate_rising_velocities_parameters(), associate_rising_velocities_parameters(), and IJK_Interfaces::compute_rising_velocities_from_compo().
get_eulerian_compo_connex_ft()
const IJK_Field_double & IJK_Composantes_Connex::get_eulerian_compo_connex_ft () const inline
References eulerian_compo_connex_ft_.
get_eulerian_compo_connex()
const IJK_Field_double & IJK_Composantes_Connex::get_eulerian_compo_connex () const inline
References eulerian_compo_connex_ns_.
get_eulerian_compo_connex_ghost_ft()
const IJK_Field_double & IJK_Composantes_Connex::get_eulerian_compo_connex_ghost_ft () const inline
References eulerian_compo_connex_ghost_ft_.
get_eulerian_compo_connex_ghost()
const IJK_Field_double & IJK_Composantes_Connex::get_eulerian_compo_connex_ghost () const inline
References eulerian_compo_connex_ghost_ns_.
get_eulerian_compo_connex_from_interface_ft()
const IJK_Field_double & IJK_Composantes_Connex::get_eulerian_compo_connex_from_interface_ft () const inline
References eulerian_compo_connex_from_interface_ft_.
get_eulerian_compo_connex_from_interface_ghost_ft()
const IJK_Field_double & IJK_Composantes_Connex::get_eulerian_compo_connex_from_interface_ghost_ft () const inline
References eulerian_compo_connex_from_interface_ghost_ft_.
get_eulerian_compo_connex_from_interface_ns()
const IJK_Field_double & IJK_Composantes_Connex::get_eulerian_compo_connex_from_interface_ns () const inline
References eulerian_compo_connex_from_interface_ns_.
get_eulerian_compo_connex_from_interface_ghost_ns()
const IJK_Field_double & IJK_Composantes_Connex::get_eulerian_compo_connex_from_interface_ghost_ns () const inline
References eulerian_compo_connex_from_interface_ghost_ns_.
get_eulerian_compo_connex_int_from_interface_ns()
const IJK_Field_int & IJK_Composantes_Connex::get_eulerian_compo_connex_int_from_interface_ns () const inline
References eulerian_compo_connex_from_interface_int_ns_.
get_eulerian_compo_connex_int_from_interface_ghost_ns()
const IJK_Field_int & IJK_Composantes_Connex::get_eulerian_compo_connex_int_from_interface_ghost_ns () const inline
References eulerian_compo_connex_from_interface_ghost_int_ns_.
get_bounding_box()
const DoubleTab & IJK_Composantes_Connex::get_bounding_box () const inline
References bounding_box_.
Referenced by IJK_Thermal_base::force_upstream_temperature().
get_bubbles_barycentre()
const DoubleTab & IJK_Composantes_Connex::get_bubbles_barycentre () const inline
References bubbles_barycentre_.
get_bubbles_volume()
const ArrOfDouble & IJK_Composantes_Connex::get_bubbles_volume () const inline
References bubbles_volume_.
get_eulerian_rising_velocities()
const IJK_Field_double & IJK_Composantes_Connex::get_eulerian_rising_velocities () const inline
References eulerian_rising_velocities_.
get_rising_velocities()
const ArrOfDouble & IJK_Composantes_Connex::get_rising_velocities () const inline
References rising_velocities_.
get_rising_vectors()
const DoubleTab & IJK_Composantes_Connex::get_rising_vectors () const inline
References rising_vectors_.
get_rising_velocity_overall()
const Vecteur3 & IJK_Composantes_Connex::get_rising_velocity_overall () const inline
References rising_velocity_overall_.
get_liquid_velocity()
const Vecteur3 & IJK_Composantes_Connex::get_liquid_velocity () const inline
References liquid_velocity_.
get_min_max_larger_box()
const DoubleTab & IJK_Composantes_Connex::get_min_max_larger_box () const inline
References min_max_larger_box_.
get_compute_from_bounding_box()
const int & IJK_Composantes_Connex::get_compute_from_bounding_box () const inline
References compute_from_bounding_box_.
get_compute_compo_fields()
const int & IJK_Composantes_Connex::get_compute_compo_fields () const inline
References compute_compo_fields_.
Referenced by IJK_Interfaces::read_bubbles_barycentres(), IJK_Interfaces::read_bubbles_barycentres_vel(), and IJK_Interfaces::store_bubbles_barycentres().
fill_mixed_cell_compo()
void IJK_Composantes_Connex::fill_mixed_cell_compo () protected
References TRUSTArray< _TYPE_, _SIZE_ >::append_array(), Statistiques::begin_count(), Maillage_FT_IJK::compo_connexe_facettes(), Domaine_IJK::convert_packed_to_ijk_cell(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::data(), Intersections_Elem_Facettes::data_intersection(), Domaine_dis_base::domaine(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel(), Statistiques::end_count(), eulerian_compo_connex_from_interface_ft_, eulerian_compo_connex_from_interface_ghost_ft_, eulerian_compo_connex_from_interface_ghost_int_ns_, eulerian_compo_connex_from_interface_ghost_ns_, eulerian_compo_connex_from_interface_int_ns_, eulerian_compo_connex_from_interface_ns_, eulerian_compo_connex_valid_compo_field_, IJK_Interfaces::get_domaine_dis(), IJK_Interfaces::get_nb_bulles_reelles(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost(), Intersections_Elem_Facettes::index_elem(), Intersections_Elem_Facettes_Data::index_facette_suivante_, interfaces_, Maillage_FT_Disc::intersections_elem_facettes(), IJK_Interfaces::maillage_ft_ijk(), Domaine_32_64< _SIZE_ >::nb_elem(), Statistiques::new_counter(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), Intersections_Elem_Facettes_Data::numero_facette_, ref_ijk_ft_, TRUSTArray< _TYPE_, _SIZE_ >::reset(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by compute_compo_connex_from_interface().
Member Data Documentation
info_obj
const Type_info IJK_Composantes_Connex::info_obj static
ref_ijk_ft_
TRUST_Ref< Probleme_FTD_IJK_base *> IJK_Composantes_Connex::ref_ijk_ft_ protected
Referenced by allocate_fields(), associer(), compute_bounding_box_fill_compo_connex(), compute_rising_velocities(), and fill_mixed_cell_compo().
interfaces_
IJK_Interfaces* IJK_Composantes_Connex::interfaces_ = nullptr protected
Referenced by compute_bounding_box_fill_compo_connex(), compute_compo_connex_from_interface(), compute_rising_velocities(), fill_mixed_cell_compo(), initialise_bubbles_params(), and initialize().
is_switch_
bool IJK_Composantes_Connex::is_switch_ =false protected
Referenced by allocate_fields(), and initialize().
compute_compo_fields_
int IJK_Composantes_Connex::compute_compo_fields_ =0 protected
Referenced by allocate_fields(), associate_rising_velocities_parameters(), compute_bounding_box_fill_compo_connex(), compute_compo_connex_from_interface(), and get_compute_compo_fields().
compute_from_bounding_box_
int IJK_Composantes_Connex::compute_from_bounding_box_ =0 protected
Referenced by allocate_fields(), compute_bounding_box_fill_compo_connex(), and get_compute_from_bounding_box().
eulerian_compo_connex_ft_
IJK_Field_double IJK_Composantes_Connex::eulerian_compo_connex_ft_ protected
Referenced by allocate_fields(), compute_bounding_box_fill_compo_connex(), and get_eulerian_compo_connex_ft().
eulerian_compo_connex_ns_
IJK_Field_double IJK_Composantes_Connex::eulerian_compo_connex_ns_ protected
Referenced by allocate_fields(), compute_bounding_box_fill_compo_connex(), and get_eulerian_compo_connex().
eulerian_compo_connex_ghost_ft_
IJK_Field_double IJK_Composantes_Connex::eulerian_compo_connex_ghost_ft_ protected
Referenced by allocate_fields(), compute_bounding_box_fill_compo_connex(), and get_eulerian_compo_connex_ghost_ft().
eulerian_compo_connex_ghost_ns_
IJK_Field_double IJK_Composantes_Connex::eulerian_compo_connex_ghost_ns_ protected
Referenced by allocate_fields(), compute_bounding_box_fill_compo_connex(), and get_eulerian_compo_connex_ghost().
eulerian_compo_connex_from_interface_ft_
IJK_Field_double IJK_Composantes_Connex::eulerian_compo_connex_from_interface_ft_ protected
Referenced by allocate_fields(), fill_mixed_cell_compo(), and get_eulerian_compo_connex_from_interface_ft().
eulerian_compo_connex_from_interface_ns_
IJK_Field_double IJK_Composantes_Connex::eulerian_compo_connex_from_interface_ns_ protected
Referenced by allocate_fields(), fill_mixed_cell_compo(), and get_eulerian_compo_connex_from_interface_ns().
eulerian_compo_connex_from_interface_ghost_ft_
IJK_Field_double IJK_Composantes_Connex::eulerian_compo_connex_from_interface_ghost_ft_ protected
Referenced by allocate_fields(), fill_mixed_cell_compo(), and get_eulerian_compo_connex_from_interface_ghost_ft().
eulerian_compo_connex_from_interface_ghost_ns_
IJK_Field_double IJK_Composantes_Connex::eulerian_compo_connex_from_interface_ghost_ns_ protected
Referenced by allocate_fields(), fill_mixed_cell_compo(), and get_eulerian_compo_connex_from_interface_ghost_ns().
eulerian_compo_connex_from_interface_int_ns_
IJK_Field_int IJK_Composantes_Connex::eulerian_compo_connex_from_interface_int_ns_ protected
Referenced by allocate_fields(), compute_compo_connex_from_interface(), compute_rising_velocities(), fill_mixed_cell_compo(), and get_eulerian_compo_connex_int_from_interface_ns().
eulerian_compo_connex_from_interface_ghost_int_ns_
IJK_Field_int IJK_Composantes_Connex::eulerian_compo_connex_from_interface_ghost_int_ns_ protected
Referenced by allocate_fields(), compute_compo_connex_from_interface(), fill_mixed_cell_compo(), and get_eulerian_compo_connex_int_from_interface_ghost_ns().
eulerian_compo_connex_valid_compo_field_
IJK_Field_int IJK_Composantes_Connex::eulerian_compo_connex_valid_compo_field_ protected
Referenced by allocate_fields(), compute_compo_connex_from_interface(), and fill_mixed_cell_compo().
bounding_box_
DoubleTab IJK_Composantes_Connex::bounding_box_ protected
Referenced by compute_bounding_box_fill_compo_connex(), and get_bounding_box().
bubbles_barycentre_
DoubleTab IJK_Composantes_Connex::bubbles_barycentre_ protected
Referenced by compute_bounding_box_fill_compo_connex(), compute_compo_connex_from_interface(), get_bubbles_barycentre(), and initialise_bubbles_params().
bubbles_volume_
ArrOfDouble IJK_Composantes_Connex::bubbles_volume_ protected
Referenced by compute_compo_connex_from_interface(), compute_rising_velocities(), get_bubbles_volume(), and initialise_bubbles_params().
min_max_larger_box_
DoubleTab IJK_Composantes_Connex::min_max_larger_box_ protected
Referenced by compute_bounding_box_fill_compo_connex(), and get_min_max_larger_box().
eulerian_rising_velocities_
IJK_Field_double IJK_Composantes_Connex::eulerian_rising_velocities_ protected
Referenced by associate_rising_velocities_parameters(), compute_rising_velocities(), and get_eulerian_rising_velocities().
rising_velocities_
ArrOfDouble IJK_Composantes_Connex::rising_velocities_ protected
Referenced by compute_rising_velocities(), and get_rising_velocities().
rising_velocity_overall_
Vecteur3 IJK_Composantes_Connex::rising_velocity_overall_ = {0., 0., 0.} protected
Referenced by compute_rising_velocities(), and get_rising_velocity_overall().
rising_vectors_
DoubleTab IJK_Composantes_Connex::rising_vectors_ protected
Referenced by compute_rising_velocities(), and get_rising_vectors().
liquid_velocity_
Vecteur3 IJK_Composantes_Connex::liquid_velocity_ = {0., 0., 0.} protected
Referenced by compute_rising_velocities(), and get_liquid_velocity().
compute_rising_velocities_
int IJK_Composantes_Connex::compute_rising_velocities_ = 0 protected
Referenced by associate_rising_velocities_parameters(), and compute_rising_velocities().
fill_rising_velocities_
int IJK_Composantes_Connex::fill_rising_velocities_ = 0 protected
Referenced by associate_rising_velocities_parameters(), and compute_rising_velocities().
use_bubbles_velocities_from_interface_
int IJK_Composantes_Connex::use_bubbles_velocities_from_interface_ = 0 protected
Referenced by associate_rising_velocities_parameters(), and compute_rising_velocities().
use_bubbles_velocities_from_barycentres_
int IJK_Composantes_Connex::use_bubbles_velocities_from_barycentres_ = 0 protected
Referenced by associate_rising_velocities_parameters(), and compute_rising_velocities().
is_updated_
bool IJK_Composantes_Connex::is_updated_ = false protected