TrioCFD: IJK_Thermal_Multiple_Subresolutions Class Reference
IJK_Thermal_Multiple_Subresolutions Class Reference
#include <IJK_Thermal_Multiple_Subresolutions.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from IJK_Thermal_Subresolution
const Type_info * get_info () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from IJK_Thermal_Subresolution
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Public Types inherited from Champs_compris_IJK_interface
using FieldInfo_t = std::tuple< Motcle, Entity, Nature_du_champ, bool >
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
IJK_Thermal_Multiple_Subresolutions()
IJK_Thermal_Multiple_Subresolutions::IJK_Thermal_Multiple_Subresolutions ()
References convective_flux_vapour_correction_, diffusion_flux_vapour_correction_, main_phase_, uniform_alpha_vap_, and uniform_lambda_vap_.
~IJK_Thermal_Multiple_Subresolutions()
IJK_Thermal_Multiple_Subresolutions::~IJK_Thermal_Multiple_Subresolutions ()
Member Function Documentation
cree_instance()
Objet_U * IJK_Thermal_Multiple_Subresolutions::cree_instance () static
taille_memoire()
unsigned IJK_Thermal_Multiple_Subresolutions::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int IJK_Thermal_Multiple_Subresolutions::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * IJK_Thermal_Multiple_Subresolutions::info () static
get_info()
const Type_info * IJK_Thermal_Multiple_Subresolutions::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from IJK_Thermal_base.
self_cast() [1/2]
IJK_Thermal_Multiple_Subresolutions & IJK_Thermal_Multiple_Subresolutions::self_cast (Objet_U & r) static
self_cast() [2/2]
const IJK_Thermal_Multiple_Subresolutions & IJK_Thermal_Multiple_Subresolutions::self_cast (const Objet_U & r) static
printOn()
Sortie & IJK_Thermal_Multiple_Subresolutions::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from IJK_Thermal_base.
References IJK_Thermal_Subresolution::printOn().
readOn()
Entree & IJK_Thermal_Multiple_Subresolutions::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from IJK_Thermal_base.
References IJK_Thermal_base::cp_liquid_, IJK_Thermal_base::cp_vapour_, IJK_Thermal_base::lambda_liquid_, IJK_Thermal_base::lambda_vapour_, main_phase_, IJK_Thermal_Subresolution::readOn(), IJK_Thermal_base::ref_ijk_ft_, IJK_Thermal_base::uniform_alpha_, uniform_alpha_vap_, IJK_Thermal_base::uniform_lambda_, and uniform_lambda_vap_.
initialize()
void IJK_Thermal_Multiple_Subresolutions::initialize (const Domaine_IJK & splitting, const int idx) override virtual
Reimplemented from IJK_Thermal_base.
References IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::allocate(), IJK_Thermal_base::compute_distance_, Domaine_IJK::ELEM, IJK_Thermal_base::ghost_fluid_, IJK_Thermal_Subresolution::initialize(), Objet_U::que_suis_je(), and temperature_vapour_.
update_thermal_properties()
void IJK_Thermal_Multiple_Subresolutions::update_thermal_properties () override virtual
Reimplemented from IJK_Thermal_base.
References IJK_Thermal_Subresolution::update_thermal_properties().
set_param()
void IJK_Thermal_Multiple_Subresolutions::set_param (Param & param) override virtual
Reimplemented from IJK_Thermal_base.
References Param::ajouter_flag(), and main_phase_.
correct_temperature_vapour_for_eulerian_fluxes()
void IJK_Thermal_Multiple_Subresolutions::correct_temperature_vapour_for_eulerian_fluxes () protected
References IJK_Thermal_base::ghost_fluid_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), IJK_Thermal_Subresolution::override_vapour_mixed_values_, IJK_Thermal_base::ref_ijk_ft_, and temperature_vapour_.
Member Data Documentation
info_obj
const Type_info IJK_Thermal_Multiple_Subresolutions::info_obj static
temperature_vapour_
IJK_Field_double IJK_Thermal_Multiple_Subresolutions::temperature_vapour_ protected
Referenced by correct_temperature_vapour_for_eulerian_fluxes(), and initialize().
div_coeff_grad_T_vapour_volume_
IJK_Field_double IJK_Thermal_Multiple_Subresolutions::div_coeff_grad_T_vapour_volume_ protected
grad_T_vapour_
IJK_Field_vector3_double IJK_Thermal_Multiple_Subresolutions::grad_T_vapour_ protected
diffusion_temperature_vapour_op_
OpDiffUniformIJKScalar_double IJK_Thermal_Multiple_Subresolutions::diffusion_temperature_vapour_op_ protected
main_phase_
int IJK_Thermal_Multiple_Subresolutions::main_phase_ protected
Referenced by IJK_Thermal_Multiple_Subresolutions(), readOn(), and set_param().
diffusion_flux_vapour_correction_
int IJK_Thermal_Multiple_Subresolutions::diffusion_flux_vapour_correction_ protected
Referenced by IJK_Thermal_Multiple_Subresolutions().
convective_flux_vapour_correction_
int IJK_Thermal_Multiple_Subresolutions::convective_flux_vapour_correction_ protected
Referenced by IJK_Thermal_Multiple_Subresolutions().
uniform_lambda_vap_
double IJK_Thermal_Multiple_Subresolutions::uniform_lambda_vap_ protected
Referenced by IJK_Thermal_Multiple_Subresolutions(), and readOn().
uniform_alpha_vap_
double IJK_Thermal_Multiple_Subresolutions::uniform_alpha_vap_ protected
Referenced by IJK_Thermal_Multiple_Subresolutions(), and readOn().