TrioCFD: Diffu_totale_base Class Reference
Diffu_totale_base Class Reference abstract
#include <Diffu_totale_base.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
moleculaire et diffusivite turbulente) dans les equations de couche limite simplifiees necessaires a l'utilisation des lois de parois de type Balaras
Constructor & Destructor Documentation
~Diffu_totale_base()
Diffu_totale_base::~Diffu_totale_base () override
Diffu_totale_base()
Diffu_totale_base::Diffu_totale_base ()
Member Function Documentation
info()
const Type_info * Diffu_totale_base::info () static
get_info()
const Type_info * Diffu_totale_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
Reimplemented in Diffu_totale_hyd_base, and Diffu_totale_scal_base.
self_cast() [1/2]
Diffu_totale_base & Diffu_totale_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Diffu_totale_base & Diffu_totale_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Diffu_totale_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
Reimplemented in Diffu_totale_hyd_base, and Diffu_totale_scal_base.
readOn()
Entree & Diffu_totale_base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
Reimplemented in Diffu_totale_hyd_base, and Diffu_totale_scal_base.
calculer_a_local()
virtual double Diffu_totale_base::calculer_a_local (int ind) pure virtual
Implemented in Diffu_k, Diffu_laminaire, Diffu_lm, Diffu_scal_lm, and Diffu_totale_hyd_base.
Referenced by Eq_couch_lim::aller_au_temps(), ParoiVDF_TBLE_LRM::calculer_hyd(), ParoiVDF_TBLE_LRM::calculer_hyd_BiK(), and Eq_couch_lim::get_nut().
calculer_D_local()
virtual double Diffu_totale_base::calculer_D_local (int ind) pure virtual
Implemented in Diffu_k, Diffu_laminaire, Diffu_lm, and Diffu_scal_lm.
Referenced by Eq_couch_lim::get_D().
associer_eqn()
void Diffu_totale_base::associer_eqn (Eq_couch_lim & e) inline
References eq_couch_lim.
Referenced by Eq_couch_lim::set_diffu().
associer_mulambda()
void Diffu_totale_base::associer_mulambda (const MuLambda_TBLE_base & m) inline
References mu_lambda.
Referenced by Paroi_TBLE_QDM::init_lois_paroi(), and Paroi_TBLE_QDM_Scal::init_lois_paroi().
getKappa()
double Diffu_totale_base::getKappa () inline
Referenced by Diffu_lm::calculer_a_local().
setKappa()
void Diffu_totale_base::setKappa (double k) inline
Referenced by ParoiVDF_TBLE::init_lois_paroi(), and ParoiVEF_TBLE::init_lois_paroi().
Member Data Documentation
info_obj
const Type_info Diffu_totale_base::info_obj static
eq_couch_lim
TRUST_Ref< Eq_couch_lim *> Diffu_totale_base::eq_couch_lim protected
Referenced by associer_eqn(), Diffu_k::calculer_a_local(), Diffu_lm::calculer_a_local(), Diffu_scal_lm::calculer_a_local(), and Diffu_lm::calculer_D_local().
mu_lambda
TRUST_Ref< MuLambda_TBLE_base *> Diffu_totale_base::mu_lambda protected
Referenced by associer_mulambda(), Diffu_k::calculer_a_local(), Diffu_laminaire::calculer_a_local(), Diffu_lm::calculer_a_local(), and Diffu_scal_lm::calculer_a_local().