TrioCFD: Modele_turbulence_hyd_2_eq_base Class Reference
Modele_turbulence_hyd_2_eq_base Class Reference
#include <Modele_turbulence_hyd_2_eq_base.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Modele_turbulence_hyd_base
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Type_info * get_info () const override
virtual void imprimer (Sortie &) const
void lire_distance_paroi ()
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual int preparer_calcul ()
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Modele_turbulence_hyd_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
See also
Modele_turbulence_hyd_base
Constructor & Destructor Documentation
Modele_turbulence_hyd_2_eq_base()
Modele_turbulence_hyd_2_eq_base::Modele_turbulence_hyd_2_eq_base ()
~Modele_turbulence_hyd_2_eq_base()
Modele_turbulence_hyd_2_eq_base::~Modele_turbulence_hyd_2_eq_base () override
Member Function Documentation
info()
const Type_info * Modele_turbulence_hyd_2_eq_base::info () static
get_info()
const Type_info * Modele_turbulence_hyd_2_eq_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
Reimplemented in Modele_turbulence_hyd_K_Eps, Modele_turbulence_hyd_K_Eps_2_Couches, Modele_turbulence_hyd_K_Eps_Bas_Reynolds, Modele_turbulence_hyd_K_Eps_Bicephale, Modele_turbulence_hyd_K_Eps_Realisable, Modele_turbulence_hyd_K_Eps_Realisable_Bicephale, Modele_turbulence_hyd_K_Omega, Modele_turbulence_hyd_RANS_Bicephale_base, Modele_turbulence_hyd_RANS_K_Eps_base, and Modele_turbulence_hyd_RANS_K_Omega_base.
self_cast() [1/2]
Modele_turbulence_hyd_2_eq_base & Modele_turbulence_hyd_2_eq_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Modele_turbulence_hyd_2_eq_base & Modele_turbulence_hyd_2_eq_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Modele_turbulence_hyd_2_eq_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
Reimplemented in Modele_turbulence_hyd_K_Eps, Modele_turbulence_hyd_K_Eps_2_Couches, Modele_turbulence_hyd_K_Eps_Bas_Reynolds, Modele_turbulence_hyd_K_Eps_Bicephale, Modele_turbulence_hyd_K_Eps_Realisable, Modele_turbulence_hyd_K_Eps_Realisable_Bicephale, Modele_turbulence_hyd_K_Omega, Modele_turbulence_hyd_RANS_Bicephale_base, Modele_turbulence_hyd_RANS_K_Eps_base, and Modele_turbulence_hyd_RANS_K_Omega_base.
References Modele_turbulence_hyd_base::printOn().
Referenced by Modele_turbulence_hyd_RANS_K_Eps_base::printOn(), and Modele_turbulence_hyd_RANS_K_Omega_base::printOn().
readOn()
Entree & Modele_turbulence_hyd_2_eq_base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
Reimplemented in Modele_turbulence_hyd_K_Eps, Modele_turbulence_hyd_K_Eps_2_Couches, Modele_turbulence_hyd_K_Eps_Bas_Reynolds, Modele_turbulence_hyd_K_Eps_Bicephale, Modele_turbulence_hyd_K_Eps_Realisable, Modele_turbulence_hyd_K_Eps_Realisable_Bicephale, Modele_turbulence_hyd_K_Omega, Modele_turbulence_hyd_RANS_Bicephale_base, Modele_turbulence_hyd_RANS_K_Eps_base, and Modele_turbulence_hyd_RANS_K_Omega_base.
References Modele_turbulence_hyd_base::readOn().
Referenced by Modele_turbulence_hyd_RANS_K_Eps_base::readOn(), and Modele_turbulence_hyd_RANS_K_Omega_base::readOn().
set_param()
void Modele_turbulence_hyd_2_eq_base::set_param (Param & param) override virtual
Reimplemented from Modele_turbulence_hyd_base.
Reimplemented in Modele_turbulence_hyd_K_Eps, Modele_turbulence_hyd_K_Eps_2_Couches, Modele_turbulence_hyd_K_Eps_Bas_Reynolds, Modele_turbulence_hyd_K_Eps_Bicephale, Modele_turbulence_hyd_K_Eps_Realisable, Modele_turbulence_hyd_K_Eps_Realisable_Bicephale, Modele_turbulence_hyd_K_Omega, Modele_turbulence_hyd_RANS_Bicephale_base, Modele_turbulence_hyd_RANS_K_Eps_base, and Modele_turbulence_hyd_RANS_K_Omega_base.
References Param::ajouter(), Param::ajouter_flag(), K_MIN_, lquiet_, and Modele_turbulence_hyd_base::set_param().
Referenced by Modele_turbulence_hyd_RANS_Bicephale_base::set_param(), Modele_turbulence_hyd_RANS_K_Eps_base::set_param(), and Modele_turbulence_hyd_RANS_K_Omega_base::set_param().
verifie_loi_paroi()
void Modele_turbulence_hyd_2_eq_base::verifie_loi_paroi () virtual
Reimplemented in Modele_turbulence_hyd_K_Eps, Modele_turbulence_hyd_K_Eps_Bicephale, Modele_turbulence_hyd_K_Eps_Realisable, and Modele_turbulence_hyd_K_Eps_Realisable_Bicephale.
References Process::exit(), Modele_turbulence_hyd_base::loipar_, and Objet_U::que_suis_je().
Referenced by Modele_turbulence_hyd_K_Eps_2_Couches::completer(), Modele_turbulence_hyd_RANS_Bicephale_base::completer(), Modele_turbulence_hyd_RANS_K_Eps_base::completer(), and Modele_turbulence_hyd_RANS_K_Omega_base::completer().
reprendre_generique()
int Modele_turbulence_hyd_2_eq_base::reprendre_generique (Entree & is)
References Process::exit(), TRUST_2_PDI::is_PDI_restart(), and TRUSTTab< _TYPE_, _SIZE_ >::jump().
Referenced by Modele_turbulence_hyd_RANS_Bicephale_base::reprendre(), Modele_turbulence_hyd_RANS_K_Eps_base::reprendre(), and Modele_turbulence_hyd_RANS_K_Omega_base::reprendre().
nombre_d_equations()
virtual int Modele_turbulence_hyd_2_eq_base::nombre_d_equations () const inline virtual
Reimplemented in Modele_turbulence_hyd_RANS_Bicephale_base.
Referenced by Modele_turbulence_hyd_RANS_K_Eps_base::get_champ(), Modele_turbulence_hyd_RANS_K_Omega_base::get_champ(), Modele_turbulence_hyd_RANS_K_Eps_base::get_noms_champs_postraitables(), Modele_turbulence_hyd_RANS_K_Omega_base::get_noms_champs_postraitables(), Modele_turbulence_hyd_RANS_K_Eps_base::has_champ(), Modele_turbulence_hyd_RANS_K_Omega_base::has_champ(), and Modele_turbulence_hyd_K_Eps::preparer_calcul().
get_Prandtl_K()
double Modele_turbulence_hyd_2_eq_base::get_Prandtl_K () const inline
References Prandtl_K_.
Referenced by Op_Diff_K_Eps_VDF_base::completer(), Op_Diff_K_Omega_VDF_base::completer(), Op_Diff_K_Eps_VEF_base::completer(), and Op_Diff_K_Omega_VEF_base::completer().
get_Prandtl_Eps()
double Modele_turbulence_hyd_2_eq_base::get_Prandtl_Eps () const inline
References Prandtl_Eps_.
Referenced by Op_Diff_K_Eps_VDF_base::completer(), and Op_Diff_K_Eps_VEF_base::completer().
get_Prandtl_Omega()
double Modele_turbulence_hyd_2_eq_base::get_Prandtl_Omega () const inline
References Prandtl_Omega_.
Referenced by Op_Diff_K_Omega_VDF_base::completer(), and Op_Diff_K_Omega_VEF_base::completer().
get_EPS_MIN()
double Modele_turbulence_hyd_2_eq_base::get_EPS_MIN () const inline
References EPS_MIN_.
Referenced by Transport_K_Eps_base::controler_K_Eps(), and Transport_K_ou_Eps_base::controler_variable().
get_EPS_MAX()
double Modele_turbulence_hyd_2_eq_base::get_EPS_MAX () const inline
References EPS_MAX_.
Referenced by Transport_K_Eps_base::controler_K_Eps(), and Transport_K_ou_Eps_base::controler_variable().
get_OMEGA_MIN()
double Modele_turbulence_hyd_2_eq_base::get_OMEGA_MIN () const inline
References OMEGA_MIN_.
Referenced by Transport_K_Omega_base::controler_K_Omega().
get_OMEGA_MAX()
double Modele_turbulence_hyd_2_eq_base::get_OMEGA_MAX () const inline
References OMEGA_MAX_.
Referenced by Transport_K_Omega_base::controler_K_Omega().
get_K_MIN()
double Modele_turbulence_hyd_2_eq_base::get_K_MIN () const inline
References K_MIN_.
Referenced by Transport_K_Eps_base::controler_K_Eps(), Transport_K_Omega_base::controler_K_Omega(), and Transport_K_ou_Eps_base::controler_variable().
get_lquiet()
int Modele_turbulence_hyd_2_eq_base::get_lquiet () const inline
References lquiet_.
Referenced by Transport_K_Eps_base::controler_K_Eps(), Transport_K_Omega_base::controler_K_Omega(), and Transport_K_ou_Eps_base::controler_variable().
Member Data Documentation
info_obj
const Type_info Modele_turbulence_hyd_2_eq_base::info_obj static
Prandtl_K_
double Modele_turbulence_hyd_2_eq_base::Prandtl_K_ = 1. protected
Referenced by get_Prandtl_K(), Modele_turbulence_hyd_RANS_K_Omega_base::Modele_turbulence_hyd_RANS_K_Omega_base(), Modele_turbulence_hyd_K_Eps::set_param(), Modele_turbulence_hyd_K_Eps_Realisable::set_param(), Modele_turbulence_hyd_K_Eps_Realisable_Bicephale::set_param(), Modele_turbulence_hyd_K_Omega::set_param(), and Modele_turbulence_hyd_RANS_Bicephale_base::set_param().
Prandtl_Eps_
double Modele_turbulence_hyd_2_eq_base::Prandtl_Eps_ = 1.3 protected
Referenced by get_Prandtl_Eps(), Modele_turbulence_hyd_K_Eps::set_param(), Modele_turbulence_hyd_K_Eps_Realisable::set_param(), Modele_turbulence_hyd_K_Eps_Realisable_Bicephale::set_param(), and Modele_turbulence_hyd_RANS_Bicephale_base::set_param().
Prandtl_Omega_
double Modele_turbulence_hyd_2_eq_base::Prandtl_Omega_ = 2. protected
Referenced by get_Prandtl_Omega(), Modele_turbulence_hyd_RANS_K_Omega_base::Modele_turbulence_hyd_RANS_K_Omega_base(), and Modele_turbulence_hyd_K_Omega::set_param().
K_MIN_
double Modele_turbulence_hyd_2_eq_base::K_MIN_ = 1.e-20 protected
Referenced by get_K_MIN(), Modele_turbulence_hyd_RANS_Bicephale_base::Modele_turbulence_hyd_RANS_Bicephale_base(), and set_param().
EPS_MIN_
double Modele_turbulence_hyd_2_eq_base::EPS_MIN_ = 1.e-20 protected
Referenced by Modele_turbulence_hyd_K_Eps::calculer_viscosite_turbulente(), Modele_turbulence_hyd_K_Eps_Bicephale::calculer_viscosite_turbulente(), Modele_turbulence_hyd_K_Eps_Bicephale::fill_turbulent_viscosity_tab(), Modele_turbulence_hyd_K_Eps::fill_turbulent_viscosity_tab(), get_EPS_MIN(), Modele_turbulence_hyd_RANS_Bicephale_base::Modele_turbulence_hyd_RANS_Bicephale_base(), Modele_turbulence_hyd_RANS_Bicephale_base::set_param(), and Modele_turbulence_hyd_RANS_K_Eps_base::set_param().
EPS_MAX_
double Modele_turbulence_hyd_2_eq_base::EPS_MAX_ = 1.e+10 protected
Referenced by get_EPS_MAX(), Modele_turbulence_hyd_RANS_Bicephale_base::set_param(), and Modele_turbulence_hyd_RANS_K_Eps_base::set_param().
OMEGA_MIN_
double Modele_turbulence_hyd_2_eq_base::OMEGA_MIN_ = 1.e-20 protected
Referenced by Modele_turbulence_hyd_K_Omega::fill_turbulent_viscosity_tab(), get_OMEGA_MIN(), and Modele_turbulence_hyd_RANS_K_Omega_base::set_param().
OMEGA_MAX_
double Modele_turbulence_hyd_2_eq_base::OMEGA_MAX_ = 1.e+10 protected
Referenced by get_OMEGA_MAX(), and Modele_turbulence_hyd_RANS_K_Omega_base::set_param().
lquiet_
bool Modele_turbulence_hyd_2_eq_base::lquiet_ = false protected
Referenced by get_lquiet(), and set_param().