TrioCFD: Source_Darcy_VDF_Face Class Reference
Source_Darcy_VDF_Face Class Reference
#include <Source_Darcy_VDF_Face.h>
Public Member Functions
const Type_info * get_info () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
void mettre_a_jour (double temps) override
Public Member Functions inherited from Terme_Source_VDF_base
void completer () override
const Type_info * get_info () const override
Public Member Functions inherited from Source_base
virtual int a_pour_Champ_Fonc (const Motcle &mot, TRUST_Ref< Champ_base * > &ch_ref) const
virtual void associer_champ_rho (const Champ_base &champ_rho)
virtual void completer ()
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
virtual void resetTime (double t)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Terme_Source_VDF_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
Ce terme doit normalement etre de type "operateur" : pour l'instant il est code comme un terme source et donc ne doit etre utilise qu'avec un schema en temps de type explicite.
Constructor & Destructor Documentation
~Source_Darcy_VDF_Face()
Source_Darcy_VDF_Face::~Source_Darcy_VDF_Face ()
Source_Darcy_VDF_Face()
Source_Darcy_VDF_Face::Source_Darcy_VDF_Face () inline
Member Function Documentation
cree_instance()
Objet_U * Source_Darcy_VDF_Face::cree_instance () static
taille_memoire()
unsigned Source_Darcy_VDF_Face::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Source_Darcy_VDF_Face::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Source_Darcy_VDF_Face::info () static
get_info()
const Type_info * Source_Darcy_VDF_Face::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Source_base.
self_cast() [1/2]
Source_Darcy_VDF_Face & Source_Darcy_VDF_Face::self_cast (Objet_U & r) static
self_cast() [2/2]
const Source_Darcy_VDF_Face & Source_Darcy_VDF_Face::self_cast (const Objet_U & r) static
printOn()
Sortie & Source_Darcy_VDF_Face::printOn (Sortie & os) const override protected virtual
DOES NOTHING - to override in derived classes.
Imprime la source sur un flot de sortie.
Parameters
(Sortie& os) le flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Source_base.
References Objet_U::que_suis_je().
Referenced by Darcy_QC_VDF_Face::printOn().
readOn()
Entree & Source_Darcy_VDF_Face::readOn (Entree & is) override protected virtual
DOES NOTHING - to override in derived classes.
Lecture d'un terme source sur un flot d'entree.
Parameters
(Entree& is) le flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Source_base.
References Param::lire_avec_accolades_depuis(), Objet_U::que_suis_je(), Source_base::set_description(), Source_base::set_fichier(), and set_param().
Referenced by Darcy_QC_VDF_Face::readOn().
set_param()
void Source_Darcy_VDF_Face::set_param (Param & param)
References Param::ajouter_non_std(), and Param::REQUIRED.
Referenced by readOn().
lire_motcle_non_standard()
int Source_Darcy_VDF_Face::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Objet_U.
References eval(), Process::exit(), Eval_Darcy_VDF_Face::getPorosite(), Eval_Darcy_VDF_Face::modK_, Objet_U_ptr::typer(), and TRUST_Deriv< _CLASSE_ >::valeur().
associer_pb()
void Source_Darcy_VDF_Face::associer_pb (const Probleme_base & pb) override virtual
Implements Source_base.
References Eval_Darcy_VDF_Face::associer(), Probleme_base::equation(), eval(), Equation_base::inconnue(), and Probleme_base::milieu().
associer_domaines()
void Source_Darcy_VDF_Face::associer_domaines (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_cl_dis) override virtual
Implements Source_base.
References Evaluateur_Source::associer_domaines(), Iterateur_Source_base::associer_domaines(), eval(), and Terme_Source_VDF_base::iter_.
mettre_a_jour()
void Source_Darcy_VDF_Face::mettre_a_jour (double temps) inline override virtual
DOES NOTHING - to override in derived classes.
Mise a jour en temps du terme source.
Parameters
(double) le pas de temps de mise a jour
Reimplemented from Source_base.
eval()
Eval_Darcy_VDF_Face & Source_Darcy_VDF_Face::eval () inline
References Iterateur_Source_base::evaluateur(), and Terme_Source_VDF_base::iter_.
Referenced by associer_domaines(), associer_pb(), and lire_motcle_non_standard().
Member Data Documentation
info_obj
const Type_info Source_Darcy_VDF_Face::info_obj static