TrioCFD: Solveur_Masse_Elem_proto Class Reference
Solveur_Masse_Elem_proto Class Reference
#include <Solveur_Masse_Elem_proto.h>
Member Function Documentation
associer_masse_proto()
void Solveur_Masse_Elem_proto::associer_masse_proto (const Solveur_Masse_base & sm, const Domaine_VF & zvf)
References le_dom_, and solv_mass_.
Referenced by Masse_PolyMAC_P0P1NC_Elem::preparer_calcul(), and Masse_VDF_Elem::preparer_calcul().
preparer_calcul_proto()
void Solveur_Masse_Elem_proto::preparer_calcul_proto ()
References solv_mass_.
Referenced by Masse_PolyMAC_P0P1NC_Elem::preparer_calcul(), and Masse_VDF_Elem::preparer_calcul().
appliquer_impl_proto()
DoubleTab & Solveur_Masse_Elem_proto::appliquer_impl_proto (DoubleTab & sm) const
References TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Nom::getString(), le_dom_, TRUST_Ref< _CLASSE_ >::le_nom(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), solv_mass_, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Masse_PolyMAC_P0P1NC_Elem::appliquer_impl(), and Masse_VDF_Elem::appliquer_impl().
dimensionner_blocs_proto()
void Solveur_Masse_Elem_proto::dimensionner_blocs_proto (matrices_t matrices, const tabs_t & semi_impl = {}) const
References Matrix_tools::allocate_morse_matrix(), TRUSTTab< _TYPE_, _SIZE_ >::append_line(), Champ_Inc_base::derivees(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), le_dom_, TRUSTVect< _TYPE_, _SIZE_ >::line_size(), solv_mass_, TRUST_Ref< _CLASSE_ >::valeur(), and Champ_Inc_base::valeurs().
Referenced by Masse_PolyMAC_P0P1NC_Elem::dimensionner_blocs(), and Masse_VDF_Elem::dimensionner_blocs().
ajouter_blocs_proto()
void Solveur_Masse_Elem_proto::ajouter_blocs_proto (matrices_t matrices, DoubleTab & secmem, double dt, const tabs_t & semi_impl, int resoudre_en_increments) const
References Champ_Inc_base::derivees(), le_dom_, TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Champ_Inc_base::passe(), solv_mass_, TRUST_Ref< _CLASSE_ >::valeur(), and Champ_Inc_base::valeurs().
Referenced by Masse_PolyMAC_P0P1NC_Elem::ajouter_blocs(), and Masse_VDF_Elem::ajouter_blocs().
Member Data Documentation
solv_mass_
TRUST_Ref< Solveur_Masse_base *> Solveur_Masse_Elem_proto::solv_mass_ protected
Referenced by ajouter_blocs_proto(), appliquer_impl_proto(), associer_masse_proto(), dimensionner_blocs_proto(), and preparer_calcul_proto().
le_dom_
TRUST_Ref< Domaine_VF *> Solveur_Masse_Elem_proto::le_dom_ protected
Referenced by ajouter_blocs_proto(), appliquer_impl_proto(), associer_masse_proto(), and dimensionner_blocs_proto().