TrioCFD: Remailleur_Collision_FT_Thomas Class Reference
Remailleur_Collision_FT_Thomas Class Reference
#include <Remailleur_Collision_FT_Thomas.h>
Public Member Functions
const Type_info * get_info () const override
int traite_RuptureCoalescenceInterfaces_Conservatif (Maillage_FT_Disc &, Champ_base &) override
Public Member Functions inherited from Remailleur_Collision_FT_Juric
const Type_info * get_info () const override
int traite_RuptureCoalescenceInterfaces (Maillage_FT_Disc &maillage, Champ_base &indicatrice) const override
const Type_info * get_info () const override
virtual int traite_RuptureCoalescenceInterfaces_Conservatif (Maillage_FT_Disc &, Champ_base &)
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
See also
Transport_Interfaces_FT_Disc Maillage_FT_Disc
Constructor & Destructor Documentation
~Remailleur_Collision_FT_Thomas()
Remailleur_Collision_FT_Thomas::~Remailleur_Collision_FT_Thomas ()
Remailleur_Collision_FT_Thomas()
Remailleur_Collision_FT_Thomas::Remailleur_Collision_FT_Thomas ()
Member Function Documentation
cree_instance()
Objet_U * Remailleur_Collision_FT_Thomas::cree_instance () static
taille_memoire()
unsigned Remailleur_Collision_FT_Thomas::taille_memoire () const override virtual
Reimplemented from Remailleur_Collision_FT_Juric.
duplique()
int Remailleur_Collision_FT_Thomas::duplique () const override virtual
Reimplemented from Remailleur_Collision_FT_Juric.
info()
const Type_info * Remailleur_Collision_FT_Thomas::info () static
get_info()
const Type_info * Remailleur_Collision_FT_Thomas::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Remailleur_Collision_FT_Juric.
self_cast() [1/2]
Remailleur_Collision_FT_Thomas & Remailleur_Collision_FT_Thomas::self_cast (Objet_U & r) static
self_cast() [2/2]
const Remailleur_Collision_FT_Thomas & Remailleur_Collision_FT_Thomas::self_cast (const Objet_U & r) static
printOn()
Sortie & Remailleur_Collision_FT_Thomas::printOn (Sortie & os) const override protected virtual
Erreur.
Pas code.
Reimplemented from Remailleur_Collision_FT_Juric.
References Process::exit().
readOn()
Entree & Remailleur_Collision_FT_Thomas::readOn (Entree & is) override protected virtual
Lecture des parametres dans le fichier .
data
Reimplemented from Remailleur_Collision_FT_Juric.
References Param::ajouter(), Param::ajouter_flag(), Process::barrier(), Process::exit(), Param::lire_avec_accolades_depuis(), and Objet_U::que_suis_je().
traite_RuptureCoalescenceInterfaces_Conservatif()
int Remailleur_Collision_FT_Thomas::traite_RuptureCoalescenceInterfaces_Conservatif (Maillage_FT_Disc & maillage, Champ_base & indicatrice) override virtual
algorithme de remaillage qui tente de conserver le volume.
voir class Remailler_Collision_FT_Thomas Par defaut, appelle le remailleur non conservatif traite_RuptureCoalescenceInterfaces()
Reimplemented from Remailleur_Collision_FT_base.
References Remaillage_FT::corriger_volume(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Domaine_dis_base::domaine(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Maillage_FT_Disc::equation_transport(), Transport_Interfaces_FT_Disc::get_update_indicatrice(), initialiser_data(), Process::Journal(), Remaillage_FT::lisser_dvolume(), mettre_a_jour_data(), Process::mp_sum(), Maillage_FT_Disc::nb_sommets(), Maillage_FT_Disc::parcourir_maillage(), Remaillage_FT::remaillage_local_interface(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), TRUSTVect< _TYPE_, _SIZE_ >::size_totale(), Maillage_FT_Disc::temps(), Remailleur_Collision_FT_Juric::traite_RuptureCoalescenceInterfaces(), transport_volume_perdu_sur_element(), transport_volume_perdu_sur_sommet(), Champ_Proto::valeurs(), and Domaine_VF::volumes().
voisinage_sommet() [1/2]
const IntTab & Remailleur_Collision_FT_Thomas::voisinage_sommet () const inline
voisinage_sommet() [2/2]
IntTab & Remailleur_Collision_FT_Thomas::voisinage_sommet () inline
next_elem() [1/2]
const IntTab & Remailleur_Collision_FT_Thomas::next_elem () const inline
next_elem() [2/2]
IntTab & Remailleur_Collision_FT_Thomas::next_elem () inline
distance_interface_element_eulerien() [1/2]
const IntTab & Remailleur_Collision_FT_Thomas::distance_interface_element_eulerien () const inline
distance_interface_element_eulerien() [2/2]
IntTab & Remailleur_Collision_FT_Thomas::distance_interface_element_eulerien () inline
nombre_de_voisins_plus_proches() [1/2]
const IntTab & Remailleur_Collision_FT_Thomas::nombre_de_voisins_plus_proches () const inline
nombre_de_voisins_plus_proches() [2/2]
IntTab & Remailleur_Collision_FT_Thomas::nombre_de_voisins_plus_proches () inline
volume_perdu() [1/2]
const DoubleTab & Remailleur_Collision_FT_Thomas::volume_perdu () const inline
volume_perdu() [2/2]
DoubleTab & Remailleur_Collision_FT_Thomas::volume_perdu () inline
surface_interface_elements_voisins() [1/2]
const DoubleTab & Remailleur_Collision_FT_Thomas::surface_interface_elements_voisins () const inline
surface_interface_elements_voisins() [2/2]
DoubleTab & Remailleur_Collision_FT_Thomas::surface_interface_elements_voisins () inline
plus_grande_distance_interface_element_eulerien()
int Remailleur_Collision_FT_Thomas::plus_grande_distance_interface_element_eulerien () const inline
distance_utilisateur()
int Remailleur_Collision_FT_Thomas::distance_utilisateur () const inline
est_dimensionne()
int Remailleur_Collision_FT_Thomas::est_dimensionne () const inline
initialiser_data()
int Remailleur_Collision_FT_Thomas::initialiser_data (const Maillage_FT_Disc & maillage) protected
References Domaine_dis_base::domaine(), and TRUSTTab< _TYPE_, _SIZE_ >::reset().
Referenced by traite_RuptureCoalescenceInterfaces_Conservatif().
construire_voisinage_sommet()
int Remailleur_Collision_FT_Thomas::construire_voisinage_sommet (const Maillage_FT_Disc & maillage) protected
References TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Domaine_dis_base::domaine(), and ArrOfBit_32_64< _SIZE_ >::resize_array().
mettre_a_jour_data()
int Remailleur_Collision_FT_Thomas::mettre_a_jour_data (const Maillage_FT_Disc & maillage) protected
References TRUSTArray< _TYPE_, _SIZE_ >::append_array(), Intersections_Elem_Facettes::data_intersection(), Domaine_dis_base::domaine(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), elements_voisins(), Intersections_Elem_Facettes_Data::fraction_surface_intersection_, Maillage_FT_Disc::get_update_surface_facettes(), Intersections_Elem_Facettes_Data::index_element_suivant_, Intersections_Elem_Facettes::index_facette(), Maillage_FT_Disc::intersections_elem_facettes(), Process::mp_min(), Maillage_FT_Disc::nb_facettes(), Intersections_Elem_Facettes_Data::numero_element_, TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by traite_RuptureCoalescenceInterfaces_Conservatif().
transport_volume_perdu_sur_element() [1/2]
int Remailleur_Collision_FT_Thomas::transport_volume_perdu_sur_element (const int elem, const Maillage_FT_Disc & maillage) protected
References Domaine_dis_base::domaine(), elements_voisins(), elements_voisins_a_distance_plus_petite2(), Process::exit(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by traite_RuptureCoalescenceInterfaces_Conservatif(), and transport_volume_perdu_sur_element().
transport_volume_perdu_sur_element() [2/2]
double Remailleur_Collision_FT_Thomas::transport_volume_perdu_sur_element (const Maillage_FT_Disc & maillage) protected
References TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Domaine_dis_base::domaine(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), and transport_volume_perdu_sur_element().
transport_volume_perdu_sur_sommet() [1/2]
int Remailleur_Collision_FT_Thomas::transport_volume_perdu_sur_sommet (const int elem, ArrOfDouble & volume_perdu_sommet, const Maillage_FT_Disc & maillage) const protected
References Intersections_Elem_Facettes_Data::barycentre_, Intersections_Elem_Facettes::data_intersection(), Objet_U::dimension, TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Maillage_FT_Disc::facettes(), Intersections_Elem_Facettes_Data::fraction_surface_intersection_, Maillage_FT_Disc::get_update_surface_facettes(), Intersections_Elem_Facettes::index_elem(), Intersections_Elem_Facettes_Data::index_facette_suivante_, Maillage_FT_Disc::intersections_elem_facettes(), Maillage_FT_Disc::nb_facettes(), Maillage_FT_Disc::nb_sommets(), and Intersections_Elem_Facettes_Data::numero_facette_.
Referenced by traite_RuptureCoalescenceInterfaces_Conservatif(), and transport_volume_perdu_sur_sommet().
transport_volume_perdu_sur_sommet() [2/2]
double Remailleur_Collision_FT_Thomas::transport_volume_perdu_sur_sommet (ArrOfDouble & volume_perdu_sommet, const Maillage_FT_Disc & maillage) const protected
References Desc_Structure_FT::collecter_espace_virtuel(), Maillage_FT_Disc::desc_sommets(), Domaine_dis_base::domaine(), MD_Vector_tools::EV_SOMME, Maillage_FT_Disc::nb_sommets(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), Maillage_FT_Disc::sommet_virtuel(), and transport_volume_perdu_sur_sommet().
elements_voisins()
int Remailleur_Collision_FT_Thomas::elements_voisins (const int elem, ArrOfInt & liste_voisins, const Domaine_dis_base & un_domaine_dis) const protected
References TRUSTArray< _TYPE_, _SIZE_ >::append_array(), ArrOfBit_32_64< _SIZE_ >::clearbit(), Domaine_dis_base::domaine(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and ArrOfBit_32_64< _SIZE_ >::testsetbit().
Referenced by mettre_a_jour_data(), nb_elements_voisins(), nb_elements_voisins_a_distance_plus_petite(), and transport_volume_perdu_sur_element().
elements_voisins_a_distance_plus_petite2()
int Remailleur_Collision_FT_Thomas::elements_voisins_a_distance_plus_petite2 (const int elem, ArrOfInt & liste_voisins) const protected
References TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by nb_elements_voisins_a_distance_plus_petite(), and transport_volume_perdu_sur_element().
nb_elements_voisins()
int Remailleur_Collision_FT_Thomas::nb_elements_voisins (const int elem, const Domaine_dis_base & un_domaine_dis) const protected
References elements_voisins(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
nb_elements_voisins_a_distance_plus_petite() [1/2]
int Remailleur_Collision_FT_Thomas::nb_elements_voisins_a_distance_plus_petite (const int elem, const Domaine_dis_base & un_domaine_dis) const protected
References elements_voisins(), elements_voisins_a_distance_plus_petite2(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
nb_elements_voisins_a_distance_plus_petite() [2/2]
int Remailleur_Collision_FT_Thomas::nb_elements_voisins_a_distance_plus_petite (const int elem) const protected
References TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot().
Member Data Documentation
info_obj
const Type_info Remailleur_Collision_FT_Thomas::info_obj static