TrioCFD: Perte_Charge_Gen Class Reference
Perte_Charge_Gen Class Reference abstract
#include <Perte_Charge_Gen.h>
Public Member Functions
void completer () override
const Type_info * get_info () const override
Public Member Functions inherited from Source_base
virtual int a_pour_Champ_Fonc (const Motcle &mot, TRUST_Ref< Champ_base * > &ch_ref) const
virtual void associer_champ_rho (const Champ_base &champ_rho)
virtual void completer ()
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
virtual void resetTime (double t)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Terme_Source_Qdm
const Champ_Don_base & source () const
Protected Member Functions
virtual void coeffs_perte_charge (const DoubleVect &u, const DoubleVect &pos, double t, double norme_u, double dh, double nu, double reynolds, double &coeff_ortho, double &coeff_long, double &u_l, DoubleVect &v_valeur) const =0
int lire_motcle_non_standard (const Motcle &, Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Perte_Charge_Gen()
Perte_Charge_Gen::Perte_Charge_Gen ()
~Perte_Charge_Gen()
Perte_Charge_Gen::~Perte_Charge_Gen () override
Member Function Documentation
info()
const Type_info * Perte_Charge_Gen::info () static
get_info()
const Type_info * Perte_Charge_Gen::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Source_base.
Reimplemented in Perte_Charge_Anisotrope_VDF_Face, Perte_Charge_Circulaire_VDF_Face, Perte_Charge_Directionnelle_VDF_Face, Perte_Charge_Isotrope_VDF_Face, and Perte_Charge_VDF_base.
self_cast() [1/2]
Perte_Charge_Gen & Perte_Charge_Gen::self_cast (Objet_U & r) static
self_cast() [2/2]
const Perte_Charge_Gen & Perte_Charge_Gen::self_cast (const Objet_U & r) static
printOn()
Sortie & Perte_Charge_Gen::printOn (Sortie & os) const override protected virtual
DOES NOTHING - to override in derived classes.
Imprime la source sur un flot de sortie.
Parameters
(Sortie& os) le flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Source_base.
Reimplemented in Perte_Charge_Anisotrope_VDF_Face, Perte_Charge_Circulaire_VDF_Face, Perte_Charge_Directionnelle_VDF_Face, Perte_Charge_Isotrope_VDF_Face, and Perte_Charge_VDF_base.
References Objet_U::que_suis_je().
readOn()
Entree & Perte_Charge_Gen::readOn (Entree & is) override protected virtual
DOES NOTHING - to override in derived classes.
Lecture d'un terme source sur un flot d'entree.
Parameters
(Entree& is) le flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Source_base.
Reimplemented in Perte_Charge_Anisotrope_VDF_Face, Perte_Charge_Circulaire_VDF_Face, Perte_Charge_Directionnelle_VDF_Face, Perte_Charge_Isotrope_VDF_Face, and Perte_Charge_VDF_base.
References diam_hydr, Objet_U::dimension, Process::exit(), Parser_U::getString(), lambda, Param::lire_avec_accolades_depuis(), Field_base::nb_comp(), Parser_U::parseString(), Objet_U::que_suis_je(), set_param(), and Parser_U::setNbVar().
Referenced by Perte_Charge_PolyMAC::readOn(), and Perte_Charge_VDF_base::readOn().
dimensionner_blocs()
void Perte_Charge_Gen::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl = {}) const inline override virtual
Reimplemented from Source_base.
associer_pb()
void Perte_Charge_Gen::associer_pb (const Probleme_base & pb) override virtual
associe le_fluide et la_vitesse
Implements Source_base.
References MorEqn::equation(), Equation_base::inconnue(), la_vitesse, and le_fluide.
completer()
void Perte_Charge_Gen::completer () override virtual
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees: Source_base::associer_domaines(const Domaine_dis_base& ,const Domaine_Cl_dis_base&) Source_base::associer_pb(const Probleme_base&)
Reimplemented from Source_base.
References Source_base::completer(), Probleme_base::domaine(), MorEqn::equation(), le_sous_domaine, nom_sous_domaine, Equation_base::probleme(), sous_domaine, and Domaine_32_64< _SIZE_ >::ss_domaine().
set_param()
void Perte_Charge_Gen::set_param (Param & param) protected virtual
Reimplemented in Perte_Charge_Anisotrope_PolyMAC_Face, Perte_Charge_Circulaire_PolyMAC_Face, Perte_Charge_Directionnelle_PolyMAC_Face, Perte_Charge_Anisotrope_VDF_Face, Perte_Charge_Circulaire_VDF_Face, and Perte_Charge_Directionnelle_VDF_Face.
References Param::ajouter(), Param::ajouter_non_std(), diam_hydr, implicite_, and Param::REQUIRED.
Referenced by readOn(), Perte_Charge_Anisotrope_PolyMAC_Face::set_param(), Perte_Charge_Circulaire_PolyMAC_Face::set_param(), Perte_Charge_Directionnelle_PolyMAC_Face::set_param(), Perte_Charge_Anisotrope_VDF_Face::set_param(), Perte_Charge_Circulaire_VDF_Face::set_param(), and Perte_Charge_Directionnelle_VDF_Face::set_param().
lire_motcle_non_standard()
int Perte_Charge_Gen::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override protected virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Objet_U.
Reimplemented in Perte_Charge_Anisotrope_VDF_Face, and Perte_Charge_Circulaire_VDF_Face.
References Parser_U::addVar(), Objet_U::dimension, Process::exit(), lambda, nom_sous_domaine, Objet_U::que_suis_je(), Parser_U::setString(), and sous_domaine.
Referenced by Perte_Charge_Anisotrope_PolyMAC_Face::lire_motcle_non_standard(), Perte_Charge_Circulaire_PolyMAC_Face::lire_motcle_non_standard(), Perte_Charge_Anisotrope_VDF_Face::lire_motcle_non_standard(), and Perte_Charge_Circulaire_VDF_Face::lire_motcle_non_standard().
associer_domaines()
void Perte_Charge_Gen::associer_domaines (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis) override protected virtual
Implements Source_base.
References le_dom_Cl_dis_, and le_dom_vf_.
coeffs_perte_charge()
virtual void Perte_Charge_Gen::coeffs_perte_charge (const DoubleVect & u, const DoubleVect & pos, double t, double norme_u, double dh, double nu, double reynolds, double & coeff_ortho, double & coeff_long, double & u_l, DoubleVect & v_valeur) const protected pure virtual
Appele pour chaque face par ajouter()
Utilise les intermediaires de calcul : u, norme_u, dh_valeur, reynolds Retourne le resultat calcule dans p_charge.
Avantage : bonne factorisation. Inconvenient : cout de l'appel d'une methode virtuelle a l'interieur d'une boucle.
Parameters
u La vitesse a la face courante. 2 ou 3 composantes
pos toto
t titi
norme_u La norme de la vitesse a la face courante
dh Le diametre hydraulique a la face courante (tire de diam_hydr)
nu la viscosite cinematique
reynolds Le nombre de reynolds a la face courante : norme_u * dh_valeur / nu
coeff_ortho coefficient dans la direction orthogonale
coeff_long coefficient dans la direction longitudinale
u_l vitesse dans la direction longitudinale
v_valeur direction_longitudinale p_charge a 2 ou 3 composantes La perte de charge vaut -coeff_long*u_l*v_valeur -coeff_ortho(u -u_v*v_valeur)
Implemented in Perte_Charge_Anisotrope_PolyMAC_Face, Perte_Charge_Circulaire_PolyMAC_Face, Perte_Charge_Directionnelle_PolyMAC_Face, Perte_Charge_Isotrope_PolyMAC_Face, Perte_Charge_Anisotrope_VDF_Face, Perte_Charge_Circulaire_VDF_Face, Perte_Charge_Directionnelle_VDF_Face, and Perte_Charge_Isotrope_VDF_Face.
Referenced by Perte_Charge_PolyMAC::ajouter(), Perte_Charge_PolyMAC::ajouter_blocs(), Perte_Charge_VDF_base::ajouter_blocs(), and Perte_Charge_PolyMAC::contribuer_a_avec().
Member Data Documentation
info_obj
const Type_info Perte_Charge_Gen::info_obj static
diam_hydr
TRUST_Deriv< Champ_Don_base > Perte_Charge_Gen::diam_hydr protected
Diametre hydraulique utilise dans le calcul de la perte de charge.
Referenced by Perte_Charge_PolyMAC::ajouter(), Perte_Charge_PolyMAC::ajouter_blocs(), Perte_Charge_VDF_base::ajouter_blocs(), Perte_Charge_PolyMAC::contribuer_a_avec(), Perte_Charge_Anisotrope_PolyMAC_Face::mettre_a_jour(), Perte_Charge_Circulaire_PolyMAC_Face::mettre_a_jour(), Perte_Charge_Directionnelle_PolyMAC_Face::mettre_a_jour(), Perte_Charge_Isotrope_PolyMAC_Face::mettre_a_jour(), Perte_Charge_Anisotrope_VDF_Face::mettre_a_jour(), Perte_Charge_Circulaire_VDF_Face::mettre_a_jour(), Perte_Charge_Directionnelle_VDF_Face::mettre_a_jour(), Perte_Charge_Isotrope_VDF_Face::mettre_a_jour(), readOn(), and set_param().
le_fluide
TRUST_Ref< Fluide_base *> Perte_Charge_Gen::le_fluide protected
Fluide associe au probleme.
Referenced by Perte_Charge_PolyMAC::ajouter(), Perte_Charge_PolyMAC::ajouter_blocs(), Perte_Charge_VDF_base::ajouter_blocs(), associer_pb(), and Perte_Charge_PolyMAC::contribuer_a_avec().
la_vitesse
TRUST_Ref< Champ_Inc_base *> Perte_Charge_Gen::la_vitesse protected
Vitesse associee a l'equation resolue.
Referenced by Perte_Charge_PolyMAC::ajouter(), Perte_Charge_PolyMAC::ajouter_blocs(), Perte_Charge_VDF_base::ajouter_blocs(), and associer_pb().
le_dom_vf_
TRUST_Ref< Domaine_VF *> Perte_Charge_Gen::le_dom_vf_ protected
Domaine dans laquelle s'applique la perte de charge.
Referenced by associer_domaines(), and Perte_Charge_PolyMAC::le_dom_poly().
le_dom_Cl_dis_
TRUST_Ref< Domaine_Cl_dis_base *> Perte_Charge_Gen::le_dom_Cl_dis_ protected
Referenced by associer_domaines().
sous_domaine
bool Perte_Charge_Gen::sous_domaine = false protected
Le terme est-il limite a une sous-domaine ?
Referenced by Perte_Charge_PolyMAC::ajouter(), Perte_Charge_PolyMAC::ajouter_blocs(), Perte_Charge_VDF_base::ajouter_blocs(), completer(), Perte_Charge_PolyMAC::contribuer_a_avec(), and lire_motcle_non_standard().
nom_sous_domaine
Nom Perte_Charge_Gen::nom_sous_domaine protected
Nom de la sous-domaine, initialise dans readOn()
Referenced by completer(), and lire_motcle_non_standard().
le_sous_domaine
TRUST_Ref< Sous_Domaine *> Perte_Charge_Gen::le_sous_domaine protected
Initialise dans completer()
Referenced by Perte_Charge_PolyMAC::ajouter(), Perte_Charge_PolyMAC::ajouter_blocs(), Perte_Charge_VDF_base::ajouter_blocs(), completer(), and Perte_Charge_PolyMAC::contribuer_a_avec().
implicite_
int Perte_Charge_Gen::implicite_ = 1 protected
Referenced by set_param().
lambda
Parser_U Perte_Charge_Gen::lambda mutable protected
Referenced by Perte_Charge_Anisotrope_PolyMAC_Face::coeffs_perte_charge(), Perte_Charge_Circulaire_PolyMAC_Face::coeffs_perte_charge(), Perte_Charge_Directionnelle_PolyMAC_Face::coeffs_perte_charge(), Perte_Charge_Isotrope_PolyMAC_Face::coeffs_perte_charge(), Perte_Charge_Anisotrope_VDF_Face::coeffs_perte_charge(), Perte_Charge_Circulaire_VDF_Face::coeffs_perte_charge(), Perte_Charge_Directionnelle_VDF_Face::coeffs_perte_charge(), Perte_Charge_Isotrope_VDF_Face::coeffs_perte_charge(), Perte_Charge_Circulaire_PolyMAC_Face::lire_motcle_non_standard(), lire_motcle_non_standard(), Perte_Charge_Circulaire_VDF_Face::lire_motcle_non_standard(), and readOn().