TrioCFD: Switch_FT_double Class Reference
Switch_FT_double Class Reference
#include <IJK_switch_FT.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Interprete
static Objet_U & objet (const Nom &)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Switch_FT_double() [1/2]
Switch_FT_double::Switch_FT_double ()
~Switch_FT_double()
Switch_FT_double::~Switch_FT_double ()
Switch_FT_double() [2/2]
Switch_FT_double::Switch_FT_double (const Switch_FT_double & x) inline
References Process::exit().
Member Function Documentation
cree_instance()
Objet_U * Switch_FT_double::cree_instance () static
taille_memoire()
unsigned Switch_FT_double::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Switch_FT_double::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Switch_FT_double::info () static
get_info()
const Type_info * Switch_FT_double::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Switch_double.
self_cast() [1/2]
Switch_FT_double & Switch_FT_double::self_cast (Objet_U & r) static
self_cast() [2/2]
const Switch_FT_double & Switch_FT_double::self_cast (const Objet_U & r) static
printOn()
Sortie & Switch_FT_double::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Switch_double.
readOn()
Entree & Switch_FT_double::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Switch_double.
operator=()
const Switch_FT_double & Switch_FT_double::operator= (const Switch_FT_double &) inline
References Process::exit().
initialise()
void Switch_FT_double::initialise () override protected virtual
Reimplemented from Switch_double.
References init_forcage_THI::compute_initial_chouippe(), Option_IJK::DISABLE_DIPHASIQUE, Probleme_base::domaine_dis(), init_forcage_THI::get_b_flt(), Domaine_IJK::get_constant_delta(), init_forcage_THI::get_semi_gen(), Switch_double::initialise(), IJK_Interfaces::initialize(), interfaces_, Domaine_base::le_nom(), IJK_Interfaces::lire_maillage_ft_dans_lata(), new_forcage_, Switch_double::new_mesh_, Switch_double::new_ni_, Switch_double::new_nj_, Switch_double::new_nk_, Switch_double::nom_sauvegarde_, Process::nproc(), old_forcage_, old_ijk_splitting_ft_extension_, Switch_double::old_mesh_, Switch_double::old_ni_, Switch_double::old_nj_, Switch_double::old_nk_, Objet_U::que_suis_je(), and IJK_Interfaces::set_reprise().
init_thermals()
void Switch_FT_double::init_thermals () override protected virtual
Reimplemented from Switch_double.
References IJK_Thermals::init_switch_thermals(), Switch_double::old_mesh_, and thermals_.
prepare_run()
void Switch_FT_double::prepare_run () override protected virtual
Reimplemented from Switch_double.
References Option_IJK::DISABLE_DIPHASIQUE, IJK_Thermals::est_vide(), Switch_double::fichier_old_vitesse_, IJK_Interfaces::get_fichier_reprise(), IJK_Thermals::get_fichier_reprise(), interfaces_, Switch_double::nom_reprise_, Switch_double::prepare_run(), IJK_Interfaces::set_fichier_reprise(), IJK_Thermals::set_fichier_reprise(), and thermals_.
set_param()
void Switch_FT_double::set_param (Param & param) override protected virtual
Reimplemented from Switch_double.
References Param::ajouter(), interfaces_, liq_velocity_tmoy_, old_forcage_, old_ijk_splitting_ft_extension_, old_qdm_corrections_, Switch_double::set_param(), thermals_, vap_velocity_tmoy_, velocity_bubble_old_, and vitesse_upstream_reprise_.
ecrire_fichier_reprise()
void Switch_FT_double::ecrire_fichier_reprise (const char * fichier_sauvegarde, const bool and_lata = true) override protected virtual
Implements Switch_double.
References Switch_double::current_time_, IJK_Thermals::ecrire_fichier_reprise(), ecrire_header_lata(), interfaces_, Process::je_suis_maitre(), liq_velocity_tmoy_, new_forcage_, new_qdm_corrections_, Sortie_Fichier_base::precision(), IJK_Interfaces::set_fichier_sauvegarde(), Sortie_Fichier_base::setf(), Switch_double::terme_source_acceleration_, thermals_, vap_velocity_tmoy_, velocity_bubble_old_, vitesse_upstream_reprise_, and Switch_double::write_velocity().
set_param_reprise()
void Switch_FT_double::set_param_reprise (Param & param) override protected virtual
Reimplemented from Switch_double.
References Param::ajouter(), interfaces_, liq_velocity_tmoy_, new_forcage_, new_qdm_corrections_, Switch_double::set_param_reprise(), thermals_, vap_velocity_tmoy_, velocity_bubble_old_, and vitesse_upstream_reprise_.
prepare_thermals()
void Switch_FT_double::prepare_thermals (const Nom lata_name) override protected virtual
Reimplemented from Switch_double.
References IJK_Thermals::prepare_thermals(), and thermals_.
ecrire_header_lata()
void Switch_FT_double::ecrire_header_lata (const Nom lata_name) override protected virtual
Reimplemented from Switch_double.
References Option_IJK::DISABLE_DIPHASIQUE, Switch_double::ecrire_header_lata(), interfaces_, and IJK_Interfaces::sauvegarder_interfaces().
Referenced by ecrire_fichier_reprise().
compute_and_write_extra_fields()
void Switch_FT_double::compute_and_write_extra_fields (const Nom & lata_name, DoubleTab & coeff_i, IntTab Indice_i, DoubleTab & coeff_j, IntTab Indice_j, DoubleTab & coeff_k, IntTab Indice_k) override protected virtual
Implements Switch_double.
References IJK_Thermals::compute_new_thermal_field(), Switch_double::new_mesh_, and thermals_.
compute_and_write_extra_fields_direct()
void Switch_FT_double::compute_and_write_extra_fields_direct (SFichier & file, DoubleTab & coeff_i, IntTab Indice_i, DoubleTab & coeff_j, IntTab Indice_j, DoubleTab & coeff_k, IntTab Indice_k) override protected virtual
Implements Switch_double.
Friends And Related Function Documentation
IJK_Thermals
friend class IJK_Thermals friend
Member Data Documentation
info_obj
const Type_info Switch_FT_double::info_obj static
interfaces_
IJK_Interfaces Switch_FT_double::interfaces_ protected
Referenced by ecrire_fichier_reprise(), ecrire_header_lata(), initialise(), prepare_run(), set_param(), and set_param_reprise().
old_ijk_splitting_ft_extension_
int Switch_FT_double::old_ijk_splitting_ft_extension_ = 0 protected
Referenced by initialise(), and set_param().
old_forcage_
init_forcage_THI Switch_FT_double::old_forcage_ protected
Referenced by initialise(), and set_param().
new_forcage_
init_forcage_THI Switch_FT_double::new_forcage_ protected
Referenced by ecrire_fichier_reprise(), initialise(), and set_param_reprise().
old_qdm_corrections_
corrections_qdm Switch_FT_double::old_qdm_corrections_ protected
Referenced by set_param().
new_qdm_corrections_
corrections_qdm Switch_FT_double::new_qdm_corrections_ protected
Referenced by ecrire_fichier_reprise(), and set_param_reprise().
vap_velocity_tmoy_
double Switch_FT_double::vap_velocity_tmoy_ = 0. protected
Referenced by ecrire_fichier_reprise(), set_param(), and set_param_reprise().
liq_velocity_tmoy_
double Switch_FT_double::liq_velocity_tmoy_ = 0. protected
Referenced by ecrire_fichier_reprise(), set_param(), and set_param_reprise().
qdm_source_
double Switch_FT_double::qdm_source_ = 0. protected
last_source_qdm_update_time_
double Switch_FT_double::last_source_qdm_update_time_ = 0. protected
vitesse_upstream_reprise_
double Switch_FT_double::vitesse_upstream_reprise_ = 0. protected
Referenced by ecrire_fichier_reprise(), set_param(), and set_param_reprise().
velocity_bubble_old_
double Switch_FT_double::velocity_bubble_old_ = 0. protected
Referenced by ecrire_fichier_reprise(), set_param(), and set_param_reprise().
offset_list_index_
int Switch_FT_double::offset_list_index_ = 0. protected
size_listes_source_
int Switch_FT_double::size_listes_source_ = 0 protected
liste_instants_
ArrOfDouble Switch_FT_double::liste_instants_ protected
liste_vap_dl_
ArrOfDouble Switch_FT_double::liste_vap_dl_ protected
liste_liq_dl_
ArrOfDouble Switch_FT_double::liste_liq_dl_ protected
reprise_v_target_
double Switch_FT_double::reprise_v_target_ = 0. protected
list_index_
int Switch_FT_double::list_index_ = 0. protected
thermals_
IJK_Thermals Switch_FT_double::thermals_ protected
Referenced by compute_and_write_extra_fields(), ecrire_fichier_reprise(), init_thermals(), prepare_run(), prepare_thermals(), set_param(), and set_param_reprise().