TrioCFD: Domaine_DG Class Reference
Domaine_DG Class Reference
#include <Domaine_DG.h>
Public Member Functions
void discretiser () override
void get_ind_integ_points (IntTab &ind_integ_points) const override
const Type_info * get_info () const override
void get_nb_integ_points (IntTab &nb_integ_points) const override
void get_position (DoubleTab &positions) const override
void set_default_order (int order)
Public Member Functions inherited from Domaine_Poly_base
const Type_info * get_info () const override
void reordonner (Faces &) override
Public Member Functions inherited from Domaine_VF
void build_map_mc_Cmesh (const bool with_faces) override
void build_mc_dual_mesh () const
void build_mc_face_mesh () const
void construire_face_virt_pe_num ()
int elem_faces (int i, int j) const
int face_voisins (int num_face, int i) const
const Type_info * get_info () const override
void init_dist_paroi_globale (const Conds_lim &conds_lim) override
int nb_faces_bord () const
int nb_faces_bord_tot () const
int nb_faces_internes () const
int nb_faces_tot () const
int nb_som_face () const
int premiere_face_bord () const
int premiere_face_int () const
Public Member Functions inherited from Domaine_dis_base
void associer_domaine (const Domaine &)
const Domaine & domaine () const
void ecrire_noms_bords (Sortie &) const
virtual IntTab & face_sommets ()
const Frontiere_dis_base & frontiere_dis (const Nom &) const
const Type_info * get_info () const override
int nombre_de_sous_domaines_dis () const
int rang_frontiere (const Nom &) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
bool build_nfaces_elem_ ()
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Domaine_Poly_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Domaine_VF
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Domaine_DG()
Domaine_DG::Domaine_DG ()
~Domaine_DG()
Domaine_DG::~Domaine_DG ()
Member Function Documentation
cree_instance()
Objet_U * Domaine_DG::cree_instance () static
taille_memoire()
unsigned Domaine_DG::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Domaine_DG::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Domaine_DG::info () static
get_info()
const Type_info * Domaine_DG::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
Domaine_DG & Domaine_DG::self_cast (Objet_U & r) static
self_cast() [2/2]
const Domaine_DG & Domaine_DG::self_cast (const Objet_U & r) static
printOn()
Sortie & Domaine_DG::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
References Domaine_Poly_base::printOn().
readOn()
Entree & Domaine_DG::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
References Domaine_Poly_base::readOn().
discretiser()
void Domaine_DG::discretiser () override virtual
Compute mesh parameters, allocate quadratures and link them to the domain.
The function use Domaine_Poly_base::discretiser() that builds every geometric connectivities that are not in the mesh file
Reimplemented from Domaine_dis_base.
References build_nfaces_elem_(), calculer_h_carre(), compute_mesh_param(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Domaine_Poly_base::discretiser(), Domaine_VF::elem_faces(), Domaine_VF::elem_faces_, Domaine_VF::face_voisins(), Option_DG::GRAM_SCHMIDT, gram_schmidt_, Domaine_dis_base::nb_elem_tot(), quad1_, quad3_, quad5_, TRUSTTab< _TYPE_, _SIZE_ >::resize(), and stencil_sorted_.
init_equiv()
void Domaine_DG::init_equiv () const override virtual
New feature in Trust, not yet available in DG, ask Elie.
Implements Domaine_Poly_base.
get_dia()
const DoubleTab & Domaine_DG::get_dia () const inline
References dia_.
get_invdia()
const DoubleTab & Domaine_DG::get_invdia () const inline
References invdia_.
get_per()
const DoubleTab & Domaine_DG::get_per () const inline
References per_.
get_rho()
const DoubleTab & Domaine_DG::get_rho () const inline
References rho_.
get_sig()
const DoubleTab & Domaine_DG::get_sig () const inline
References sig_.
get_nfaces_elem()
const IntTab & Domaine_DG::get_nfaces_elem () const inline
References nfaces_elem_.
get_type_elem()
const TRUST_Deriv< Elem_poly_base > Domaine_DG::get_type_elem () const inline
References Domaine_Poly_base::type_elem_.
get_quadrature() [1/2]
const Quadrature_base & Domaine_DG::get_quadrature (int order) const inline
References Process::exit(), quad1_, quad3_, and quad5_.
Referenced by Eval_Puiss_Th_DG_Elem::calculer_terme_source(), and Champ_Elem_DG::valeur_aux().
get_quadrature() [2/2]
const Quadrature_base & Domaine_DG::get_quadrature () const inline
References get_quadrature(), and order_quad_.
Referenced by compute_L1_norm(), compute_L2_norm(), get_ind_integ_points(), get_nb_integ_points(), get_position(), and get_quadrature().
get_stencil_sorted()
const IntTab & Domaine_DG::get_stencil_sorted () const inline
References stencil_sorted_.
set_default_order()
void Domaine_DG::set_default_order (int order)
Set the global default order.
Parameters
order : order to specify
References order_quad_.
get_position()
void Domaine_DG::get_position (DoubleTab & positions) const override virtual
Compute positions of the quadrature points.
For now it uses the default quadrature order and compute positions for every cells
Parameters
positions coordinates of the quadrature points
Reimplemented from Domaine_VF.
References Quadrature_base::get_integ_points(), and get_quadrature().
compute_L1_norm()
double Domaine_DG::compute_L1_norm (const DoubleVect & val_source) const override virtual
Compute L_1 norm.
Reimplemented from Domaine_VF.
References Quadrature_base::compute_integral_on_elem(), get_quadrature(), Domaine_dis_base::nb_elem(), Quadrature_base::nb_pts_integ(), and Quadrature_base::nb_pts_integ_max().
compute_L2_norm()
double Domaine_DG::compute_L2_norm (const DoubleVect & val_source) const override virtual
Compute L_2 norm.
Reimplemented from Domaine_VF.
References Quadrature_base::compute_integral_on_elem(), get_quadrature(), Domaine_dis_base::nb_elem(), Quadrature_base::nb_pts_integ(), and Quadrature_base::nb_pts_integ_max().
get_nb_integ_points()
void Domaine_DG::get_nb_integ_points (IntTab & nb_integ_points) const override virtual
Give an IntTab that contains the number of integration points for each cell.
Parameters
nb_integ_points : nb_integ_points[i] give the number of integration points for cell i
Reimplemented from Domaine_VF.
References get_quadrature(), and Quadrature_base::get_tab_nb_pts_integ().
get_ind_integ_points()
void Domaine_DG::get_ind_integ_points (IntTab & ind_integ_points) const override virtual
Create the indirection that give for each cell, the index number of the first integration point.
Parameters
ind_integ_points : ind_integ_points[i] give the index of the first integration point associated with cell i
Reimplemented from Domaine_VF.
References Quadrature_base::get_ind_pts_integ(), and get_quadrature().
calculer_h_carre()
void Domaine_DG::calculer_h_carre () override virtual
Should disappear, as well as h_carre, as we have dia_, this come with a refactoring of Domaine_Poly_base.
Reimplemented from Domaine_Poly_base.
References dia_, Domaine_Poly_base::h_carre, Domaine_Poly_base::h_carre_, Process::mp_max(), Domaine_dis_base::nb_elem(), Domaine_dis_base::nb_elem_tot(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), and TRUSTVect< _TYPE_, _SIZE_ >::size().
Referenced by discretiser().
gram_schmidt()
const bool & Domaine_DG::gram_schmidt () const inline
References gram_schmidt_.
compute_mesh_param()
void Domaine_DG::compute_mesh_param () protected
Compute geometric quantities used for the computation TODO :: Put this in the Domain_Poly_base and delete h_carre.
< Array of the diameter for each cell
< Perimeter of each cell
< Diameter of the largest incircle for each cell
< Aspect ratio of each cell
References dia_, Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), Domaine_VF::face_sommets(), Domaine_VF::face_surfaces(), Domaine_32_64< _SIZE_ >::les_elems(), Domaine_32_64< _SIZE_ >::les_sommets(), Domaine_dis_base::nb_elem_tot(), nfaces_elem_, per_, TRUSTTab< _TYPE_, _SIZE_ >::resize(), rho_, sig_, and Domaine_VF::volumes().
Referenced by discretiser().
build_nfaces_elem_()
bool Domaine_DG::build_nfaces_elem_ () protected
Create an array that store the number of faces per element.
If the mesh is only composed with the same type of element, return yes.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Domaine_VF::elem_faces(), Process::exit(), Domaine_dis_base::nb_elem_tot(), nfaces_elem_, and TRUSTTab< _TYPE_, _SIZE_ >::resize().
Referenced by discretiser().
Member Data Documentation
info_obj
const Type_info Domaine_DG::info_obj static
quad1_
std::shared_ptr<Quadrature_base> Domaine_DG::quad1_ protected
Referenced by discretiser(), and get_quadrature().
quad3_
std::shared_ptr<Quadrature_base> Domaine_DG::quad3_ protected
Referenced by discretiser(), and get_quadrature().
quad5_
std::shared_ptr<Quadrature_base> Domaine_DG::quad5_ protected
Referenced by discretiser(), and get_quadrature().
dia_
DoubleTab Domaine_DG::dia_ protected
Referenced by calculer_h_carre(), compute_mesh_param(), and get_dia().
invdia_
DoubleTab Domaine_DG::invdia_ protected
Referenced by get_invdia().
per_
DoubleTab Domaine_DG::per_ protected
Referenced by compute_mesh_param(), and get_per().
rho_
DoubleTab Domaine_DG::rho_ protected
Referenced by compute_mesh_param(), and get_rho().
sig_
DoubleTab Domaine_DG::sig_ protected
Referenced by compute_mesh_param(), and get_sig().
nfaces_elem_
IntTab Domaine_DG::nfaces_elem_ protected
Referenced by build_nfaces_elem_(), compute_mesh_param(), and get_nfaces_elem().
order_quad_
int Domaine_DG::order_quad_ =-1 protected
Referenced by get_quadrature(), and set_default_order().
gram_schmidt_
bool Domaine_DG::gram_schmidt_ protected
Referenced by discretiser(), and gram_schmidt().
stencil_sorted_
IntTab Domaine_DG::stencil_sorted_ protected
Referenced by discretiser(), and get_stencil_sorted().