TrioCFD: ComputeValParCompoInCell Class Reference
ComputeValParCompoInCell Class Reference
#include <ComputeValParCompoInCell.h>
Constructor & Destructor Documentation
ComputeValParCompoInCell()
ComputeValParCompoInCell::ComputeValParCompoInCell () inline
References mesh_.
~ComputeValParCompoInCell()
ComputeValParCompoInCell::~ComputeValParCompoInCell () inline
Member Function Documentation
initialize()
void ComputeValParCompoInCell::initialize (const Domaine_IJK & splitting, const Maillage_FT_IJK & maillage_ft_ijk) inline
References mesh_, and ref_domaine_.
Referenced by IJK_Interfaces::initialize().
calculer_valeur_par_compo()
void ComputeValParCompoInCell::calculer_valeur_par_compo (const double time, const int itstep, IJK_Field_int & nb_compo_trav, FixedVector< IJK_Field_int, max_authorized_nb_of_components_ > & compos_trav, FixedVector< IJK_Field_double, 3 *max_authorized_nb_of_components_ > & normale_par_compo, FixedVector< IJK_Field_double, 3 *max_authorized_nb_of_components_ > & bary_par_compo, FixedVector< IJK_Field_double, max_authorized_nb_of_components_ > & indicatrice_par_compo, FixedVector< IJK_Field_double, max_authorized_nb_of_components_ > & surface_par_compo, FixedVector< IJK_Field_double, max_authorized_nb_of_components_ > & courbure_par_compo)
References calculer_moy_field_sommet_par_compo(), calculer_moy_par_compo(), Maillage_FT_Disc::get_update_courbure_sommets(), and mesh_.
Referenced by IJK_Interfaces::calculer_indicatrice_next().
calculer_moy_field_sommet_par_compo()
void ComputeValParCompoInCell::calculer_moy_field_sommet_par_compo (const ArrOfDouble & val_on_sommet, FixedVector< IJK_Field_double, max_authorized_nb_of_components_ > & field_par_compo) const
References Intersections_Elem_Facettes_Data::barycentre_, Maillage_FT_IJK::compo_connexe_facettes(), compute_list_compo_connex_in_element(), Intersections_Elem_Facettes::data_intersection(), FixedVector< T, N >::echange_espace_virtuel(), Maillage_FT_Disc::facettes(), Intersections_Elem_Facettes_Data::fraction_surface_intersection_, Maillage_FT_Disc::get_update_surface_facettes(), Intersections_Elem_Facettes::index_elem(), Intersections_Elem_Facettes_Data::index_facette_suivante_, Maillage_FT_Disc::intersections_elem_facettes(), mesh_, Intersections_Elem_Facettes_Data::numero_facette_, and ref_domaine_.
Referenced by IJK_Interfaces::calculer_phi_repuls_par_compo(), and calculer_valeur_par_compo().
calculer_somme_field_sommet_par_compo()
void ComputeValParCompoInCell::calculer_somme_field_sommet_par_compo (const ArrOfDouble & val_on_sommet, FixedVector< IJK_Field_double, max_authorized_nb_of_components_ > & field_par_compo) const
References Intersections_Elem_Facettes_Data::barycentre_, Maillage_FT_IJK::compo_connexe_facettes(), compute_list_compo_connex_in_element(), Intersections_Elem_Facettes::data_intersection(), FixedVector< T, N >::echange_espace_virtuel(), Maillage_FT_Disc::facettes(), Intersections_Elem_Facettes_Data::fraction_surface_intersection_, Maillage_FT_Disc::get_update_surface_facettes(), Intersections_Elem_Facettes::index_elem(), Intersections_Elem_Facettes_Data::index_facette_suivante_, Maillage_FT_Disc::intersections_elem_facettes(), mesh_, Intersections_Elem_Facettes_Data::numero_facette_, and ref_domaine_.
Referenced by IJK_Interfaces::calculer_phi_repuls_par_compo().
calculer_moy_field_fa7_par_compo()
void ComputeValParCompoInCell::calculer_moy_field_fa7_par_compo (const ArrOfDouble & val_on_fa7, FixedVector< IJK_Field_double, max_authorized_nb_of_components_ > & field_par_compo) const
References Maillage_FT_IJK::compo_connexe_facettes(), compute_list_compo_connex_in_element(), Intersections_Elem_Facettes::data_intersection(), FixedVector< T, N >::echange_espace_virtuel(), Intersections_Elem_Facettes_Data::fraction_surface_intersection_, Maillage_FT_Disc::get_update_surface_facettes(), Intersections_Elem_Facettes::index_elem(), Intersections_Elem_Facettes_Data::index_facette_suivante_, Maillage_FT_Disc::intersections_elem_facettes(), mesh_, Intersections_Elem_Facettes_Data::numero_facette_, and ref_domaine_.
calculer_moyennes_interface_element_pour_compo()
void ComputeValParCompoInCell::calculer_moyennes_interface_element_pour_compo (const int num_compo, const int elem, double & surface, Vecteur3 & normale, Vecteur3 & bary) const protected
References Intersections_Elem_Facettes_Data::barycentre_, Maillage_FT_IJK::compo_connexe_facettes(), Intersections_Elem_Facettes::data_intersection(), Process::exit(), Maillage_FT_Disc::facettes(), Intersections_Elem_Facettes_Data::fraction_surface_intersection_, Maillage_FT_Disc::get_update_normale_facettes(), Maillage_FT_Disc::get_update_surface_facettes(), Intersections_Elem_Facettes::index_elem(), Intersections_Elem_Facettes_Data::index_facette_suivante_, Maillage_FT_Disc::intersections_elem_facettes(), mesh_, Intersections_Elem_Facettes_Data::numero_facette_, and Maillage_FT_Disc::sommets().
Referenced by calculer_moy_par_compo().
calculer_indic_elem_pour_compo()
int ComputeValParCompoInCell::calculer_indic_elem_pour_compo (const int icompo, const int elem, double & indic) const protected
References Intersections_Elem_Facettes_Data::barycentre_, Maillage_FT_IJK::compo_connexe_facettes(), Intersections_Elem_Facettes_Data::contrib_volume_phase1_, Intersections_Elem_Facettes::data_intersection(), Maillage_FT_Disc::facettes(), Intersections_Elem_Facettes::index_elem(), Intersections_Elem_Facettes_Data::index_facette_suivante_, Maillage_FT_Disc::intersections_elem_facettes(), mesh_, Intersections_Elem_Facettes_Data::numero_facette_, and Maillage_FT_Disc::sommets().
Referenced by calculer_moy_par_compo().
calculer_moy_par_compo()
void ComputeValParCompoInCell::calculer_moy_par_compo (IJK_Field_int & nb_compo_traversante, FixedVector< IJK_Field_int, max_authorized_nb_of_components_ > & compos_traversantes, FixedVector< IJK_Field_double, 3 *max_authorized_nb_of_components_ > & normale_par_compo, FixedVector< IJK_Field_double, 3 *max_authorized_nb_of_components_ > & bary_par_compo, FixedVector< IJK_Field_double, max_authorized_nb_of_components_ > & indic_par_compo, FixedVector< IJK_Field_double, max_authorized_nb_of_components_ > & surface_par_compo) const protected
References calculer_indic_elem_pour_compo(), calculer_moyennes_interface_element_pour_compo(), compute_list_compo_connex_in_element(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::data(), FixedVector< T, N >::echange_espace_virtuel(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost(), and ref_domaine_.
Referenced by calculer_valeur_par_compo().
compute_list_compo_connex_in_element()
int ComputeValParCompoInCell::compute_list_compo_connex_in_element (const int elem, ArrOfInt & liste_composantes_connexes_dans_element) const protected
References TRUSTArray< _TYPE_, _SIZE_ >::append_array(), Maillage_FT_IJK::compo_connexe_facettes(), Intersections_Elem_Facettes::data_intersection(), Intersections_Elem_Facettes_Data::fraction_surface_intersection_, Intersections_Elem_Facettes::index_elem(), Intersections_Elem_Facettes_Data::index_facette_suivante_, Maillage_FT_Disc::intersections_elem_facettes(), mesh_, Intersections_Elem_Facettes_Data::numero_element_, Intersections_Elem_Facettes_Data::numero_facette_, TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by calculer_moy_field_fa7_par_compo(), calculer_moy_field_sommet_par_compo(), calculer_moy_par_compo(), and calculer_somme_field_sommet_par_compo().
Member Data Documentation
ref_domaine_
TRUST_Ref< Domaine_IJK *> ComputeValParCompoInCell::ref_domaine_ protected
Referenced by calculer_moy_field_fa7_par_compo(), calculer_moy_field_sommet_par_compo(), calculer_moy_par_compo(), calculer_somme_field_sommet_par_compo(), and initialize().
mesh_
const Maillage_FT_IJK* ComputeValParCompoInCell::mesh_ protected
Referenced by calculer_indic_elem_pour_compo(), calculer_moy_field_fa7_par_compo(), calculer_moy_field_sommet_par_compo(), calculer_moyennes_interface_element_pour_compo(), calculer_somme_field_sommet_par_compo(), calculer_valeur_par_compo(), compute_list_compo_connex_in_element(), ComputeValParCompoInCell(), and initialize().