TrioCFD: Dispersion_bulles_turbulente_Burns Class Reference
Dispersion_bulles_turbulente_Burns Class Reference
#include <Dispersion_bulles_turbulente_Burns.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Dispersion_bulles_turbulente_Burns()
Dispersion_bulles_turbulente_Burns::Dispersion_bulles_turbulente_Burns ()
~Dispersion_bulles_turbulente_Burns()
Dispersion_bulles_turbulente_Burns::~Dispersion_bulles_turbulente_Burns ()
Member Function Documentation
cree_instance()
Objet_U * Dispersion_bulles_turbulente_Burns::cree_instance () static
taille_memoire()
unsigned Dispersion_bulles_turbulente_Burns::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Dispersion_bulles_turbulente_Burns::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Dispersion_bulles_turbulente_Burns::info () static
get_info()
const Type_info * Dispersion_bulles_turbulente_Burns::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Dispersion_bulles_base.
self_cast() [1/2]
Dispersion_bulles_turbulente_Burns & Dispersion_bulles_turbulente_Burns::self_cast (Objet_U & r) static
self_cast() [2/2]
const Dispersion_bulles_turbulente_Burns & Dispersion_bulles_turbulente_Burns::self_cast (const Objet_U & r) static
printOn()
Sortie & Dispersion_bulles_turbulente_Burns::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Dispersion_bulles_base.
readOn()
Entree & Dispersion_bulles_turbulente_Burns::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Dispersion_bulles_base.
References a_res_, Param::ajouter(), coefBIA_, correlation_drag_, Nom::debute_par(), Process::exit(), g_, Probleme_base::get_correlation(), Probleme_base::has_correlation(), Param::lire_avec_accolades_depuis(), minimum_, n_l, Pb_Multiphase::nb_phases(), Pb_Multiphase::nom_phase(), Correlation_base::pb_, Prt_, Objet_U::que_suis_je(), Correlation_base::typer_lire_correlation(), and TRUST_Ref< _CLASSE_ >::valeur().
coefficient()
void Dispersion_bulles_turbulente_Burns::coefficient (const input_t & input, output_t & output) const override virtual
Implements Dispersion_bulles_base.
References a_res_, Dispersion_bulles_base::input_t::alpha, C_lambda_, coefBIA_, Frottement_interfacial_base::coefficient(), correlation_drag_, Dispersion_bulles_base::output_t::Ctd, Dispersion_bulles_base::input_t::d_bulles, Dispersion_bulles_base::input_t::dh, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), g_, Dispersion_bulles_base::input_t::k_WIT, minimum_, Dispersion_bulles_base::input_t::mu, n_l, Dispersion_bulles_base::input_t::nut, Dispersion_bulles_base::input_t::nv, Dispersion_bulles_base::input_t::p, Prt_, Dispersion_bulles_base::input_t::rho, Dispersion_bulles_base::input_t::sigma, Dispersion_bulles_base::input_t::T, and TRUST_Deriv< _CLASSE_ >::valeur().
completer()
void Dispersion_bulles_turbulente_Burns::completer () override virtual
Reimplemented from Correlation_base.
References a_res_, and Correlation_base::pb_.
Member Data Documentation
info_obj
const Type_info Dispersion_bulles_turbulente_Burns::info_obj static
correlation_drag_
TRUST_Deriv< Correlation_base > Dispersion_bulles_turbulente_Burns::correlation_drag_ protected
Referenced by coefficient(), and readOn().
n_l
int Dispersion_bulles_turbulente_Burns::n_l = -1 protected
Referenced by coefficient(), and readOn().
Prt_
double Dispersion_bulles_turbulente_Burns::Prt_ = .9 protected
Referenced by coefficient(), and readOn().
minimum_
double Dispersion_bulles_turbulente_Burns::minimum_ = -1. protected
Referenced by coefficient(), and readOn().
g_
double Dispersion_bulles_turbulente_Burns::g_ = 9.81 protected
Referenced by coefficient(), and readOn().
C_lambda_
double Dispersion_bulles_turbulente_Burns::C_lambda_ = 2.7 protected
Referenced by coefficient().
coefBIA_
double Dispersion_bulles_turbulente_Burns::coefBIA_ = 0. protected
Referenced by coefficient(), and readOn().
a_res_
double Dispersion_bulles_turbulente_Burns::a_res_ = -1. protected
Referenced by coefficient(), completer(), and readOn().