TrioCFD: TRUST_Deriv< _CLASSE_ > Class Template Reference
TRUST_Deriv< _CLASSE_ > Class Template Reference
#include <TRUST_Deriv.h>
Protected Member Functions
Sortie & printOn (Sortie &os) const override
Entree & readOn (Entree &is) override
Protected Member Functions inherited from Objet_U_ptr
int change_num (const int *const) override
Objet_U * get_Objet_U_ptr_check () const
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
void recopie (const Objet_U &)
~Objet_U_ptr () override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Public Member Functions inherited from Objet_U_ptr
int associer_ (Objet_U &objet) override
const Type_info * get_info () const override
const Nom & le_nom () const override
Objet_U * typer (const char *nom_type)
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
~TRUST_Deriv()
template<typename _CLASSE_ > TRUST_Deriv< _CLASSE_ >::~TRUST_Deriv () inline
References Objet_U_ptr::detach().
TRUST_Deriv() [1/3]
template<typename _CLASSE_ > TRUST_Deriv< _CLASSE_ >::TRUST_Deriv () inline
Referenced by TRUST_Deriv< _CLASSE_ >::duplique().
TRUST_Deriv() [2/3]
template<typename _CLASSE_ > TRUST_Deriv< _CLASSE_ >::TRUST_Deriv (const TRUST_Deriv< _CLASSE_ > & t) inline
References Objet_U_ptr::non_nul(), Objet_U_ptr::recopie(), and TRUST_Deriv< _CLASSE_ >::valeur().
TRUST_Deriv() [3/3]
template<typename _CLASSE_ > TRUST_Deriv< _CLASSE_ >::TRUST_Deriv (const _CLASSE_ & t) inline
References Objet_U_ptr::recopie().
Member Function Documentation
taille_memoire()
template<typename _CLASSE_ > unsigned TRUST_Deriv< _CLASSE_ >::taille_memoire () const inline override protected virtual
Implements Objet_U.
duplique()
template<typename _CLASSE_ > int TRUST_Deriv< _CLASSE_ >::duplique () const inline override protected virtual
Implements Objet_U.
References Process::exit(), Objet_U::numero(), and TRUST_Deriv< _CLASSE_ >::TRUST_Deriv().
printOn()
template<typename _CLASSE_ > Sortie & TRUST_Deriv< _CLASSE_ >::printOn (Sortie & s) const inline override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U_ptr.
References Objet_U_ptr::printOn().
readOn()
template<typename _CLASSE_ > Entree & TRUST_Deriv< _CLASSE_ >::readOn (Entree & s) inline override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U_ptr.
References Objet_U_ptr::readOn().
set_Objet_U_ptr()
template<typename _CLASSE_ > void TRUST_Deriv< _CLASSE_ >::set_Objet_U_ptr (Objet_U * ptr) inline override protected virtual
Fait pointer *this sur l'objet *ptr L'adresse peut etre nulle (pointeur nul).
Reimplemented from Objet_U_ptr.
References Objet_U_ptr::set_Objet_U_ptr().
Referenced by Cond_lim::adopt().
valeur() [1/2]
template<typename _CLASSE_ > const _CLASSE_ & TRUST_Deriv< _CLASSE_ >::valeur () const inline
References Objet_U_ptr::get_Objet_U_ptr_check().
Referenced by Modele_turbulence_hyd_LES_selectif_mod_VDF::a_pour_Champ_Fonc(), Modele_turbulence_hyd_LES_selectif_VDF::a_pour_Champ_Fonc(), Modele_turbulence_hyd_LES_1elt_selectif_mod_VEF::a_pour_Champ_Fonc(), Modele_turbulence_hyd_LES_Fst_sel_VEF::a_pour_Champ_Fonc(), Modele_turbulence_scal_Schmidt::a_pour_Champ_Fonc(), Sources::a_pour_Champ_Fonc(), Modele_turbulence_hyd_0_eq_base::a_pour_Champ_Fonc(), Terme_Source_Acceleration::a_pour_Champ_Fonc(), Operateur_Conv_sensibility_VEF::add_diffusion_scalar_term(), Operateur_Conv_sensibility_VEF::add_diffusion_term(), Probleme_FT_Disc_gen::add_FT_equation(), Matrix_tools::add_scaled_matrices(), Matrix_tools::add_symmetric_scaled_matrices(), Cond_lim::adopt(), Operateur_Conv_sensibility_VEF::ajouter(), Op_Grad_PolyMAC_Face::ajouter(), Op_Conv_Amont_old_VEF_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Centre_EF_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_EF_VEF_P1NC::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Conv_Vort_VEF_Face::ajouter(), Op_Diff_VEF_Face_Q1::ajouter(), Op_Dift_VEF_Face_Q1::ajouter(), Op_Div_VEFP1B_Elem::ajouter(), Source_Reaction_Particules_VDF::ajouter(), Source_Reaction_Particules_VEF::ajouter(), SourceFiltree_FT_disc_VEF_P1NC::ajouter(), Source_Gravite_PF_VDF::ajouter(), Terme_Boussinesq_Sensibility_VEFPreP1B_Face::ajouter(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_VEF_Face::ajouter(), Source_Transport_K_Eps_Bas_Reynolds_VEF_Face::ajouter(), Source_Robin::ajouter(), Source_Robin_Scalaire::ajouter(), Source_Qdm_EF::ajouter(), Source_Scalaire_EF::ajouter(), Perte_Charge_PolyMAC::ajouter(), Source_Generique_Face_PolyMAC::ajouter(), Terme_Source_Qdm_Face_PolyMAC::ajouter(), Perte_Charge_VEF::ajouter(), Source_Generique_VEF::ajouter(), Terme_Boussinesq_VEFPreP1B_Face::ajouter(), Terme_Source_Acceleration_VEF_Face::ajouter(), Terme_Source_Qdm_VEF_Face::ajouter(), Terme_Source_Th_TdivU_VEF_Face::ajouter(), Op_Grad_VEF_P1B_Face::ajouter_aretes(), Tenseur_Reynolds_Externe_VDF_Face::ajouter_blocs(), Source_Transport_Bas_Reynolds_VDF_Elem_base::ajouter_blocs(), Source_Transport_K_Eps_Bas_Reynolds_aniso_therm_concen_VDF_Elem::ajouter_blocs(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_VDF_Elem::ajouter_blocs(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_QC_VDF_Elem::ajouter_blocs(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_W_VDF_Elem::ajouter_blocs(), Source_Transport_K_KEps_VDF_Elem::ajouter_blocs(), Op_Grad_P0_to_Face::ajouter_blocs(), Op_Grad_VDF_Face::ajouter_blocs(), Terme_Source_Canal_perio_VDF_Face::ajouter_blocs(), Force_Centrifuge_VDF_Face_Axi::ajouter_blocs(), Source_Generique_VDF_Face::ajouter_blocs(), Terme_Boussinesq_VDF_Face::ajouter_blocs(), Terme_Source_Acceleration_VDF_Face::ajouter_blocs(), Terme_Source_Coriolis_VDF_Face::ajouter_blocs(), Terme_Source_inc_th_VDF_Face::ajouter_blocs(), Terme_Source_inc_VDF_Face::ajouter_blocs(), Terme_Source_Qdm_VDF_Face::ajouter_blocs(), Coalescence_bulles_1groupe_PolyMAC_P0::ajouter_blocs(), Coalescence_bulles_2groupes_PolyMAC_P0::ajouter_blocs(), Flux_2groupes_PolyMAC_P0::ajouter_blocs(), Injection_QDM_nulle_PolyMAC_P0::ajouter_blocs(), Rupture_bulles_1groupe_PolyMAC_P0::ajouter_blocs(), Rupture_bulles_2groupes_PolyMAC_P0::ajouter_blocs(), Injection_QDM_nulle_VDF::ajouter_blocs(), Diffusion_supplementaire_echelle_temp_turb_VDF::ajouter_blocs(), Frottement_interfacial_PolyMAC_P0::ajouter_blocs(), Portance_interfaciale_PolyMAC_P0::ajouter_blocs(), Perte_Charge_PolyMAC::ajouter_blocs(), Frottement_interfacial_VDF::ajouter_blocs(), Portance_interfaciale_VDF::ajouter_blocs(), Perte_Charge_VDF_base::ajouter_blocs(), Op_Grad_EF::ajouter_bord(), Iterateur_PolyMAC_Elem< _TYPE_ >::ajouter_bords(), Op_Diff_EF::ajouter_bords(), Op_Dift_EF_Q1::ajouter_bords(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Face::ajouter_cas_vectoriel(), Op_Conv_Amont_old_VEF_Face::ajouter_contribution(), Op_Conv_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution(), Op_Diff_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Face_Q1::ajouter_contribution(), Op_Diff_VEF_Face_Stab::ajouter_contribution(), Op_Conv_RT_VEF_Face::ajouter_contribution(), Iterateur_PolyMAC_Elem< _TYPE_ >::ajouter_contribution_bords(), Iterateur_PolyMAC_Elem< _TYPE_ >::ajouter_contribution_bords_vitesse(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution_elem(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face_Stab::ajouter_contribution_multi_scalaire(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution_som(), Op_Diff_EF::ajouter_contributions_bords(), Op_Dift_EF_Q1::ajouter_contributions_bords(), Operateur_Conv_sensibility_VEF::ajouter_conv_term(), Op_Grad_VEF_P1B_Face::ajouter_elem(), Source_Masse_Fluide_Dilatable_VEF::ajouter_eq_espece(), Iterateur_Source_Face< _TYPE_ >::ajouter_faces_bords(), Source_Fluide_Dilatable_VDF_Proto::ajouter_impl(), Source_Fluide_Dilatable_VEF_Proto::ajouter_impl(), Operateur_Conv_sensibility_VEF::ajouter_Lsensibility_state_Amont(), Operateur_Conv_sensibility_VEF::ajouter_Lstate_sensibility_Amont(), Matrice_Bloc::ajouter_multvect_(), Matrice_Bloc_Sym::ajouter_multvect_(), Matrice_Bloc::ajouter_multvectT_(), Source_Masse_Fluide_Dilatable_VEF::ajouter_projection(), Op_Grad_VEF_P1B_Face::ajouter_som(), Op_Div_VEFP1B_Elem::ajouter_som(), Op_Conv_ALE_VEF::ajouterALE(), Transport_Interfaces_FT_Disc::algorithmes_transport(), Eq_couch_lim::aller_au_temps(), Matrix_tools::allocate_for_scaled_addition(), Matrix_tools::allocate_for_symmetric_scaled_addition(), Matrix_tools::allocate_from_stencil(), QDM_Multiphase::alpha_res(), Tensors_Computation_VEF::antisym_loop_edge_faces(), Solveur_Masse_EF::appliquer_impl(), Masse_VDF_Face::appliquer_impl(), Masse_VEF_P1NC::appliquer_impl(), Assembleur_P_VDF_Q4::assembler(), Assembleur_P_EF::assembler_mat(), Assembleur_P_PolyMAC::assembler_mat(), Assembleur_P_PolyMAC_P0::assembler_mat(), Assembleur_P_PolyMAC_P0P1NC::assembler_mat(), Assembleur_P_VEFPreP1B::assembler_mat(), Op_Diff_RotRot::assembler_matrice(), AssembleurPVDF_PF::assembler_QC(), Assembleur_P_EF::assembler_QC(), Assembleur_P_PolyMAC::assembler_QC(), Assembleur_P_VDF::assembler_QC(), Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re::associe_modele_fonction(), Op_Diff_RotRot::associer(), Op_Diff_VEFP1NCP1B_Face::associer(), Op_Dift_VEF_P1NCP1B_Face::associer(), Modele_turbulence_hyd_LES_DSGS_VDF::associer(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::associer(), Sources::associer_champ_rho(), Temperature_imposee_paroi_rayo_semi_transp::associer_modele(), Source_rayo_semi_transp_QC_VDF_P0_VDF::associer_modele_rayo(), Source_rayo_semi_transp_QC_VEF_P1NC::associer_modele_rayo(), Temperature_imposee_paroi_rayo_transp::associer_modele_rayo(), Source_PDF_EF::associer_pb(), Pb_Hydraulique_ALE::associer_sch_tps_base(), Pb_Hydraulique_Turbulent_ALE::associer_sch_tps_base(), Fluide_base::beta_c(), Milieu_base::beta_t(), BilanQdmVEF::bilan_energie(), BilanQdmVEF::bilan_qdm(), Champ_Elem_DG::build_mass_matrix(), Matrice_Bloc::build_stencil(), Probleme_FTD_IJK_base::build_vdf_domaine(), IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::build_with_known_pattern(), IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::build_with_unknown_pattern(), Traitement_particulier_NS_chmoy_faceperio_VEF::calcul_chmoy_faceperio(), Modele_Jones_Launder_VDF::Calcul_D(), Modele_Jones_Launder_Thermique_VDF::Calcul_D(), Modele_Jones_Launder_VDF::Calcul_D_BiK(), Champ_P1NC::calcul_duidxj_paroi(), Modele_Jones_Launder_Thermique_VDF::Calcul_E(), Traitement_particulier_NS_THI_VEF::calcul_Ec_spatial(), Modele_EASM_Baglietto_VEF::Calcul_F1(), Modele_EASM_Baglietto_VEF::Calcul_F1_BiK(), Modele_EASM_Baglietto_VEF::Calcul_Fmu(), Modele_EASM_Baglietto_VEF::Calcul_Fmu_BiK(), Champ_P1NC::calcul_h_conv(), Traitement_particulier_NS_THI_VEF::calcul_moyenne(), Traitement_particulier_NS_canal::calcul_reynolds_tau(), Traitement_particulier_NS_THI_VDF::calcul_skewness_ordre_2(), Modele_Lam_Bremhorst_VEF::calcul_tenseur_face(), Modele_Shih_Zhu_Lumley_VEF::calcul_tenseur_face(), Calcul_Production_K_VEF::calcul_tenseur_face(), Traitement_particulier_NS_THI_VEF::calcul_vitesse_moyenne(), Champ_Q1_EF::calcul_y_plus(), Champ_P1NC::calcul_y_plus(), Champ_Face_VDF::calcul_y_plus(), Champ_P1NC::calcul_y_plus_diphasique(), Champ_Face_VDF::calcul_y_plus_diphasique(), Fluide_reel_base::calculate_fluid_properties_enthalpie(), Fluide_reel_base::calculate_fluid_properties_enthalpie_incompressible(), Op_Conv_ALE_VEF::calculateALEMeshVelocityGradientOnFaces(), Milieu_base::calculer_alpha(), Maillage_FT_Disc::calculer_costheta_minmax(), Terme_Source_Canal_perio_VDF_Face::calculer_debit(), Terme_Source_Canal_perio_VEF_P1NC::calculer_debit(), Modele_turbulence_scal_Prandtl::calculer_diffusivite_turbulente(), Op_Diff_P1NC_barprim::calculer_divergence(), Op_Dift_VEF_P1NCP1B_Face::calculer_divergence_som(), Op_Diff_VEFP1NCP1B_Face::calculer_divergence_som(), Op_Conv_VDF_base::calculer_dt_local(), Op_Conv_VEF_base::calculer_dt_local(), Op_Conv_ALE_VEF::calculer_dt_stab(), Operateur_Conv_sensibility_VEF::calculer_dt_stab(), Op_Diff_DG_base::calculer_dt_stab(), Op_Conv_PolyMAC_iterateur_base::calculer_dt_stab(), Op_Diff_PolyMAC_base::calculer_dt_stab(), Op_Conv_VDF_base::calculer_dt_stab(), Op_Conv_Muscl_New_VEF_Face::calculer_dt_stab(), Op_Conv_VEF_base::calculer_dt_stab(), Op_Diff_VEF_base::calculer_dt_stab(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab_elem(), Iterateur_PolyMAC_Elem< _TYPE_ >::calculer_flux_bord(), Op_Diff_VEFP1NCP1B_Face::calculer_flux_bords_elem(), Op_Diff_VEFP1NCP1B_Face::calculer_flux_bords_som(), Modele_rayo_semi_transp::calculer_flux_radiatif(), Flux_radiatif_VDF::calculer_flux_radiatif(), Flux_radiatif_VEF::calculer_flux_radiatif(), Modele_turbulence_hyd_LES_VDF::calculer_fonction_structure(), Modele_turbulence_hyd_LES_VEF::calculer_fonction_structure(), Modele_turbulence_hyd_LES_axi_VDF::calculer_fonction_structure(), EDO_Pression_th_VEF::calculer_grad(), Navier_Stokes_FT_Disc::calculer_gradient_indicatrice(), Op_Dift_VEF_P1NCP1B_Face::calculer_gradient_som(), Op_Diff_VEFP1NCP1B_Face::calculer_gradient_som(), Domaine_PolyMAC::calculer_h_carre(), ParoiVDF_TBLE_LRM::calculer_hyd(), Paroi_std_hyd_VEF::calculer_hyd(), Paroi_negligeable_VDF::calculer_hyd(), Paroi_negligeable_VEF::calculer_hyd(), Paroi_std_hyd_VDF_diphasique::calculer_hyd(), Paroi_std_hyd_VEF_diphasique::calculer_hyd(), Paroi_loi_WW_hyd_EF::calculer_hyd(), Paroi_std_hyd_EF::calculer_hyd(), Paroi_2couches_VDF::calculer_hyd(), Paroi_loi_Ciofalo_hyd_VDF::calculer_hyd(), Paroi_loi_WW_hyd_VDF::calculer_hyd(), Paroi_loi_WW_hyd_VEF::calculer_hyd(), Paroi_std_hyd_VDF::calculer_hyd(), Paroi_UTAU_IMP_VDF::calculer_hyd(), LoiParoiHybride::calculer_hyd(), ParoiVDF_TBLE::calculer_hyd(), ParoiVEF_TBLE::calculer_hyd(), Paroi_std_hyd_VDF::calculer_hyd_BiK(), Paroi_UTAU_IMP_VDF::calculer_hyd_BiK(), ParoiVDF_TBLE::calculer_hyd_BiK(), ParoiVDF_TBLE_LRM::calculer_hyd_BiK(), Paroi_std_hyd_VEF::calculer_hyd_BiK(), ParoiVEF_TBLE::calculer_hyd_BiK(), LoiParoiHybride::calculer_hyd_BiK(), Op_Diff_VEF_Face_Stab::calculer_max(), Op_Diff_VEF_Face_Stab::calculer_min(), Paroi_std_hyd_VDF::calculer_moyennes_parois(), Fluide_base::calculer_nu(), Op_Conv_PolyMAC_iterateur_base::calculer_pour_post(), Op_Conv_VDF_base::calculer_pour_post(), Op_Conv_VEF_base::calculer_pour_post(), Source_Transport_Fluctuation_Temperature_VDF_Elem::calculer_Prod_uteta_T(), Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::calculer_Prod_uteta_T(), Source_Transport_Fluctuation_Temperature_W_VDF_Elem::calculer_Prod_uteta_T(), Paroi_std_scal_hyd_EF::calculer_scal(), Loi_Paroi_Nu_Impose_VDF::calculer_scal(), Paroi_loi_WW_scal_VDF::calculer_scal(), Paroi_ODVM_scal_VDF::calculer_scal(), Paroi_std_scal_hyd_VDF::calculer_scal(), Paroi_TBLE_scal_VDF::calculer_scal(), Loi_Paroi_Nu_Impose_VEF::calculer_scal(), Paroi_loi_WW_scal_VEF::calculer_scal(), Paroi_scal_analytique_VEF::calculer_scal(), Paroi_std_scal_hyd_VEF::calculer_scal(), ParoiVEF_TBLE_scal::calculer_scal(), Neumann_paroi_rayo_semi_transp_VDF::calculer_temperature_bord(), Temperature_imposee_paroi_rayo_semi_transp::calculer_temperature_bord(), Fluide_base::calculer_temperature_multiphase(), Calcul_Production_K_VEF::calculer_terme_production_K(), Calcul_Production_K_VEF::calculer_terme_production_K_BiK(), Calcul_Production_K_VEF::calculer_terme_production_K_EASM(), Temperature_imposee_paroi_rayo_transp::calculer_Teta_i(), Calcul_Production_K_VDF::calculer_u_conc(), Calcul_Production_K_VDF::calculer_u_teta(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_W_VDF_Elem::calculer_u_teta_W(), Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::calculer_u_teta_W(), Source_Transport_Fluctuation_Temperature_W_VDF_Elem::calculer_u_teta_W(), Champ_base::calculer_valeurs_som_compo_post(), Champ_base::calculer_valeurs_som_post(), Source_PDF_EF::calculer_variable_imposee_elem_fluid(), Source_PDF_EF::calculer_variable_imposee_hybrid(), Source_PDF_EF::calculer_variable_imposee_mean_grad(), Modele_turbulence_hyd_LES_VEF::calculer_viscosite_turbulente(), Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl(), Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl_u_star(), Transport_Interfaces_FT_Disc::calculer_vitesse_transport_interpolee(), Op_Diff_RotRot::calculer_vorticite(), Op_Dift_Multiphase_proto::call_compute_diff_turb(), Op_Dift_Multiphase_proto::call_compute_nu_turb(), Milieu_base::capacite_calorifique(), Loi_Etat_base::ch_temperature(), Equation_base::champ_conserve(), Equation_base::champ_convecte(), Energie_Multiphase::champ_convecte(), DomaineAxi1d_32_64< _SIZE_ >::champ_origine(), Champ_P1NC_implementation::Champ_P1NC_implementation(), Assembleur_P_VEFPreP1B::changer_base_matrice(), Matrice_Bloc::check_block_matrix_structure(), Sources::check_multiphase_compatibility(), Matrice_Bloc_Sym::check_symmetric_block_matrix_structure(), Fluide_Dilatable_base::checkTraitementPth(), Transport_Interfaces_FT_Disc_interne::close_save_file(), Frottement_interfacial_Garnier::coefficient(), Frottement_interfacial_Rusche::coefficient(), Frottement_interfacial_Simonnet::coefficient(), Frottement_interfacial_Zenit::coefficient(), Dispersion_bulles_turbulente_Bazin::coefficient(), Dispersion_bulles_turbulente_Bertodano::coefficient(), Dispersion_bulles_turbulente_Burns::coefficient(), Dispersion_bulles_turbulente_Lavieville::coefficient(), IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::complete_empty_matrices_initialisation(), Triple_Line_Model_FT_Disc::completer(), Pb_Couple_Rayonnement::completer(), Diffusion_croisee_echelle_temp_taux_diss_turb_PolyMAC_P0::completer(), Source_Diffusion_supplementaire_echelle_temp_turb::completer(), Probleme_FTD_IJK_base::completer(), Echange_contact_VDF_FT_Disc::completer(), Echange_contact_VDF_FT_Disc_solid::completer(), Convection_Diffusion_Temperature_FT_Disc::completer(), Schema_Phase_field::completer(), Navier_Stokes_Fluide_Dilatable_base::completer(), Convection_Diffusion_Espece_Multi_QC::completer(), Convection_Diffusion_Espece_Multi_WC::completer(), Paroi_Knudsen_non_negligeable::completer(), Navier_Stokes_std::completer(), Terme_Source_Canal_perio::completer(), QDM_Multiphase::completer(), Loi_paroi_base::completer(), Multi_Sch_ThHyd::completer(), Op_Diff_VEF_Face_Stab::completer(), Op_Dift_Stab_VEF_Face::completer(), Convection_Diffusion_Temperature_FT_Disc::compute_divergence_free_velocity_extension(), Terme_Source_Canal_perio::compute_heat_flux(), Paroi_std_hyd_VDF::compute_law_komega(), Paroi_scal_hyd_base_EF::compute_nusselt(), Paroi_scal_hyd_base_VDF::compute_nusselt(), Paroi_scal_hyd_base_VEF::compute_nusselt(), Triple_Line_Model_FT_Disc::compute_TCL_fluxes_in_all_boundary_cells(), Calcul_Production_K_VEF::compute_utheta_nbConsti_gt_1_nbCompo_eq_0(), Calcul_Production_K_VEF::compute_utheta_nbConsti_gt_1_nbCompo_eq_1(), Calcul_Production_K_VEF::compute_utheta_nbConsti_gt_1_nbCompo_gt_1(), Calcul_Production_K_VEF::compute_utheta_nbConsti_le_1_nbCompo_eq_0(), Calcul_Production_K_VEF::compute_utheta_nbConsti_le_1_nbCompo_eq_1(), Calcul_Production_K_VEF::compute_utheta_nbConsti_le_1_nbCompo_gt_1(), Milieu_base::conductivite(), Fluide_Ostwald::consistance(), AssembleurPVDF_PF::construire(), Assembleur_P_VDF::construire(), Domain_Graph::construire_graph_elem_elem(), DomaineCutter_32_64< _SIZE_ >::construire_sous_domaine(), Solv_Externe::construit_matrice_morse_intermediaire(), Op_Conv_Amont_old_VEF_Face::contribue_au_second_membre(), Op_Conv_VEF_Face::contribue_au_second_membre(), Op_Diff_VEF_Anisotrope_Face::contribue_au_second_membre(), Op_Diff_VEF_Face::contribue_au_second_membre(), Op_Diff_VEF_Face_Q1::contribue_au_second_membre(), Sources::contribuer_a_avec(), Op_Conv_ALE_VEF::contribuer_a_avec(), Perte_Charge_PolyMAC::contribuer_a_avec(), Op_Dift_VEF_Face_Q1::contribuer_a_avec(), Perte_Charge_VEF::contribuer_a_avec(), Op_Grad_PolyMAC_Face::contribuer_a_avec(), Op_Diff_DG_Elem::contribuer_au_second_membre(), Op_Dift_VEF_Face::contribuer_au_second_membre(), Iterateur_PolyMAC_Elem< _TYPE_ >::contribuer_au_second_membre_bords(), Sources::contribuer_jacobienne(), Op_Diff_VDF_Elem_base::contribuer_termes_croises(), Transport_K_Eps_base::controler_K_Eps(), Transport_K_Omega_base::controler_K_Omega(), Transport_K_ou_Eps_base::controler_variable(), IJK_Thermal_Subresolution::convert_into_sparse_matrix(), Navier_Stokes_FT_Disc::correct_at_exit_bad_gradient(), Op_Dift_Multiphase_VDF_Elem::correlation(), Op_Diff_Turbulent_PolyMAC_P0_Elem::correlation_viscosite_turbulente(), Op_Diff_Turbulent_PolyMAC_P0_Face::correlation_viscosite_turbulente(), Op_Dift_Multiphase_VDF_Elem::correlation_viscosite_turbulente(), Op_Dift_Multiphase_VDF_Face::correlation_viscosite_turbulente(), Op_Diff_VEFP1NCP1B_Face::corriger_Cl_test(), Navier_Stokes_std::corriger_derivee_impl(), Transport_K_Eps_ALE::corriger_derivee_impl_ALE(), Op_Diff_VEFP1NCP1B_Face::corriger_div_pour_Cl(), Op_Dift_VEF_P1NCP1B_Face::corriger_div_pour_Cl(), Probleme_FTD_IJK::create_forced_dilation(), Navier_Stokes_Turbulent_ALE::creer_champ(), Transport_Marqueur_FT::creer_champ(), Navier_Stokes_Turbulent::creer_champ(), Fluide_Dilatable_base::creer_champs_non_lus(), Domaine_VDF::creer_elements_fictifs(), Fluide_base::creer_nu(), DecoupeBord_32_64< _SIZE_ >::decouper(), Probleme_FTD_IJK_base::deplacer_interfaces(), Probleme_FTD_IJK_cut_cell::deplacer_interfaces(), Probleme_FTD_IJK_base::deplacer_interfaces_rk3(), Probleme_FTD_IJK_cut_cell::deplacer_interfaces_rk3(), Equation_base::derivee_en_temps_inco(), Convection_Diffusion_Temperature_FT_Disc::derivee_en_temps_inco(), Navier_Stokes_phase_field::derivee_en_temps_inco(), Navier_Stokes_std::derivee_en_temps_inco(), Navier_Stokes_FT_Disc::derivee_en_temps_inco(), Milieu_base::diffusivite(), Constituant::diffusivite_constituant(), Milieu_base::diffusivite_fois_rho(), Op_Diff_Turbulent_PolyMAC_P0_Elem::dimension_min_nu(), Op_EF_base::dimensionner(), Op_PolyMAC_Elem::dimensionner(), Op_VDF_Face::dimensionner(), Sources::dimensionner(), Equation_rayonnement_base::dimensionner_Mat_Bloc_Morse_Sym(), Champ_P1NC_implementation::dimensionner_Mat_Bloc_Morse_Sym(), Equation_base::discretiser(), Navier_Stokes_std_ALE::discretiser(), Convection_Diffusion_Temperature_FT_Disc::discretiser(), Navier_Stokes_FT_Disc::discretiser(), Domaine_EF::discretiser(), Domaine_Poly_base::discretiser(), Domaine_VDF::discretiser(), Domaine_VEF::discretiser(), Milieu_base::discretiser(), Marqueur_Lagrange_base::discretiser(), Fluide_Dilatable_base::discretiser(), Fluide_Weakly_Compressible::discretiser(), Fluide_base::discretiser(), Fluide_Ostwald::discretiser(), Fluide_reel_base::discretiser(), Solide::discretiser(), Navier_Stokes_FT_Disc::discretiser_assembleur_pression(), Constituant::discretiser_multi_concentration(), Navier_Stokes_std::div(), Equation_base::domaine_Cl_dis(), Convection_Diffusion_Fluide_Dilatable_base::domaine_cl_modif(), Postraitement_ft_lata::ecrire_maillage_ft_disc(), Domaine_Poly_base::ecrit(), Viscosite_turbulente_k_omega::eddy_viscosity(), Echange_impose_base::emissivite(), Probleme_FTD_IJK_base::eq_ns(), Modele_rayo_semi_transp::eq_rayo(), Probleme_FTD_IJK_base::euler_time_step(), Champ_val_tot_sur_vol_VEF::eval_contrib_loc(), Eq_rayo_semi_transp_VDF::evaluer_cl_rayonnement(), Eq_rayo_semi_transp_VEF::evaluer_cl_rayonnement(), Navier_Stokes_Turbulent_ALE::expression_residu(), Navier_Stokes_Turbulent::expression_residu(), Matrix_tools::extend_matrix_stencil(), Domaine_bord_32_64< _SIZE_ >::extraire_domaine_bord(), Source_Masse_Fluide_Dilatable_base::fill_val_flux_tab(), Source_PDF_EF::filtre_CLD(), Champ_P1NC_implementation::filtrer_L2(), Champ_P1NC_implementation::filtrer_resu(), mon_main::finalize(), Save_Restart::finir(), Implicite_ALE::first_special_treatment(), Fluide_Diphasique::fluide_phase(), Modele_rayo_semi_transp::flux_radiatif(), Transport_Marqueur_FT::get_champ(), Navier_Stokes_Aposteriori::get_champ(), Transport_K_ou_Eps_base::get_champ(), Paroi_hyd_base_EF::get_champ(), Equation_base::get_champ(), Convection_Diffusion_Temperature::get_champ(), Convection_Diffusion_Temperature_base::get_champ(), Navier_Stokes_std::get_champ(), Conduction::get_champ(), Champ_Generique_Extraction::get_champ(), Champ_Generique_Tparoi_VEF::get_champ(), Transport_Interfaces_FT_Disc::get_collision_model(), Fluide_Diphasique_IJK::get_cp_liquid(), Fluide_Diphasique_IJK::get_cp_vapour(), Probleme_FTD_IJK_cut_cell::get_cut_field_velocity(), Eq_couch_lim::get_D(), Fluide_Diphasique_IJK::get_delta_rho(), Eq_couch_lim::get_diffu(), Convection_Diffusion_Temperature_FT_Disc::get_flux_and_Twall(), Convection_Diffusion_Temperature_FT_Disc::get_flux_to_face(), Sondes::get_from_cache(), Fluide_Diphasique_IJK::get_lambda_liquid(), Fluide_Diphasique_IJK::get_lambda_vapour(), Fluide_Diphasique_IJK::get_mu_liquid(), Fluide_Diphasique_IJK::get_mu_vapour(), Eq_couch_lim::get_nut(), Reaction::get_omega(), Champ_Generique_Champ::get_ref_champ_base(), Fluide_Diphasique_IJK::get_rho_liquid(), Fluide_Diphasique_IJK::get_rho_vapour(), Transport_Interfaces_FT_Disc::get_set_collision_model(), Fluide_Diphasique_IJK::get_set_cp_vapour(), Fluide_Diphasique_IJK::get_set_lambda_vapour(), Terme_Source_Acceleration::get_set_terme_source_post(), Champ_Generique_Predefini::get_source(), Matrice_Bloc::get_stencil(), Matrice_Bloc::get_stencil_coeff_templ(), Matrice_Bloc_Sym::get_symmetric_stencil(), Matrice_Bloc_Sym::get_symmetric_stencil_and_coefficients(), Terme_Source_Acceleration::get_terme_source_post(), Triple_Line_Model_FT_Disc::get_theta_app(), Transport_Interfaces_FT_Disc::get_update_distance_interface(), Transport_Interfaces_FT_Disc::get_update_distance_interface_faces(), Transport_Interfaces_FT_Disc::get_update_indicatrice(), Transport_Interfaces_FT_Disc::get_update_normale_interface(), Paroi_TBLE_QDM::getMuLambda(), Navier_Stokes_std::grad_P(), Milieu_base::gravite(), Echange_impose_base::h_imp(), IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::impose_boundary_conditions(), Op_VEF_Face::impr(), Transport_Interfaces_FT_Disc::impr(), Navier_Stokes_std::impr(), Op_Div_VEFP1B_Elem::impr(), Navier_Stokes_Turbulent_ALE::imprime_residu(), Navier_Stokes_Turbulent::imprime_residu(), Matrice_Bloc::imprimer(), Matrice_Bloc::imprimer_formatte(), Loi_Paroi_Nu_Impose_VDF::imprimer_nusselt(), Loi_Paroi_Nu_Impose_VEF::imprimer_nusselt(), Paroi_scal_hyd_base_EF::imprimer_nusselt(), Paroi_scal_hyd_base_VDF::imprimer_nusselt(), Paroi_scal_hyd_base_VEF::imprimer_nusselt(), Turbulence_paroi_scal_base::imprimer_nusselt_mean_only(), Turbulence_paroi_scal_base::imprimer_premiere_ligne_nusselt(), Turbulence_paroi_base::imprimer_premiere_ligne_ustar(), Paroi_std_hyd_EF::imprimer_ustar(), Paroi_std_hyd_VDF::imprimer_ustar(), Paroi_std_hyd_VEF::imprimer_ustar(), Paroi_2couches_VDF::imprimer_ustar(), Turbulence_paroi_base::imprimer_ustar_mean_only(), Navier_Stokes_std::inconnue(), Fluide_base::indice(), Fluide_Ostwald::indice_struct(), Traitement_particulier_NS_chmoy_faceperio_VEF::init_calcul_stats(), ParoiVDF_TBLE::init_lois_paroi(), ParoiVDF_TBLE_LRM::init_lois_paroi(), Paroi_ODVM_scal_VDF::init_lois_paroi(), Paroi_TBLE_scal_VDF::init_lois_paroi(), ParoiVEF_TBLE::init_lois_paroi(), ParoiVEF_TBLE_scal::init_lois_paroi(), Paroi_negligeable_VEF::init_lois_paroi(), Paroi_TBLE_QDM::init_lois_paroi(), Paroi_TBLE_QDM_Scal::init_lois_paroi(), Op_Diff_VDF_base::init_op_ext(), Probleme_FTD_IJK_base::initialise_ijk_fields(), IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::initialise_matrix_subproblems(), IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::initialise_sparse_matrix_subproblems(), Milieu_base::initialiser(), Fluide_Dilatable_base::initialiser(), Fluide_reel_base::initialiser(), Milieu_composite::initialiser(), Echange_contact_VDF_FT_Disc::initialiser(), Echange_contact_VDF_FT_Disc_solid::initialiser(), Terme_Source_Qdm_Face_PolyMAC_P0P1NC::initialiser(), Terme_Puissance_Thermique_Echange_Impose_Elem_base::initialiser(), Terme_Source_Qdm_VDF_Face::initialiser(), Terme_Puissance_Thermique_Echange_Impose_VEF_Face::initialiser(), Boundary_field_keps_from_ud::initialiser(), Domaine_ALE::initialiser(), Champ_front_xyz_debit::initialiser(), Terme_Puissance_Thermique::initialiser_champ_puissance(), Probleme_FTD_IJK::initialize(), Probleme_FTD_IJK_base::initialize(), Probleme_FTD_IJK_cut_cell::initialize(), Pb_Couple_rayo_semi_transp::initialize(), Fluide_base::initTimeStep(), Fluide_reel_base::initTimeStep(), Milieu_composite::initTimeStep(), Create_domain_from_sub_domain::interpreter_(), Modif_bord_to_raccord_32_64< _SIZE_ >::interpreter_(), Redresser_hexaedres_vdf::interpreter_(), Op_Diff_VEFP1NCP1B_Face::isFaceOfSymetry(), Simple::iterer_eqs(), SETS::iterer_NS(), Fluide_base::kappa(), Echange_contact_rayo_semi_transp_VDF::la_Cl_opposee(), Champ_Fonc_MED::le_champ(), Champ_Fonc_MED_Table_Temps::le_champ0(), Integrale_tps_Champ::le_champ_calcule(), Champ_Fonc_Tabule::le_champ_tabule_discretise(), Equation_base::lire_cl(), Terme_Puissance_Thermique::lire_donnees(), Pb_Multiphase::lire_equations(), LireMED_32_64< _SIZE_ >::lire_geom(), Convection_Diffusion_Turbulent::lire_modele(), Navier_Stokes_Turbulent_ALE::lire_motcle_non_standard(), Navier_Stokes_FT_Disc::lire_motcle_non_standard(), Transport_Marqueur_FT::lire_motcle_non_standard(), Schema_Phase_field::lire_motcle_non_standard(), Equation_rayonnement_base::lire_motcle_non_standard(), Champ_Generique_Champ::lire_motcle_non_standard(), Solveur_Lineaire_Std::lire_motcle_non_standard(), Fluide_Dilatable_base::lire_motcle_non_standard(), Convection_Diffusion_Temperature_IBM_Turbulent::lire_motcle_non_standard(), Convection_Diffusion_Chaleur_Turbulent_QC::lire_motcle_non_standard(), Convection_Diffusion_Concentration_Turbulent::lire_motcle_non_standard(), Convection_Diffusion_Espece_Binaire_Turbulent_QC::lire_motcle_non_standard(), Convection_Diffusion_Espece_Multi_Turbulent_QC::lire_motcle_non_standard(), Convection_Diffusion_Temperature_Turbulent::lire_motcle_non_standard(), Modele_turbulence_hyd_base::lire_motcle_non_standard(), Modele_turbulence_scal_base::lire_motcle_non_standard(), Source_Darcy_VDF_Face::lire_motcle_non_standard(), Source_Forchheimer_VDF_Face::lire_motcle_non_standard(), Source_Darcy_VEF_Face::lire_motcle_non_standard(), Source_Forchheimer_VEF_Face::lire_motcle_non_standard(), Navier_Stokes_Fluide_Dilatable_base::lire_motcle_non_standard(), Convection_Diffusion_Turbulent::lire_op_diff_turbulent(), Navier_Stokes_Turbulent_ALE::lire_op_diff_turbulent(), Navier_Stokes_IBM_Turbulent::lire_op_diff_turbulent(), Navier_Stokes_Turbulent::lire_op_diff_turbulent(), Op_Diff_VEFP1NCP1B_Face::liste_face(), Transport_K_KEps::loi2couches(), Modele_turbulence_hyd_base::loi_paroi(), Modele_turbulence_scal_base::loi_paroi(), Fluide_base::longeur_rayo(), Fluide_base::longueur_rayo(), IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::make_operation_on_sub_matrix_sparse(), Milieu_base::masse_volumique(), Equation_rayonnement_base::Mat_Morse_to_Mat_Bloc(), Champ_P1NC_implementation::Mat_Morse_to_Mat_Bloc(), Matrice_Morse_Sym::Matrice_Morse_Sym(), T_paroi_Champ_P0_VDF::me_calculer(), Maillage_FT_Disc::mesh_data_cache(), Source_Masse_Fluide_Dilatable_base::mettre_a_jour(), Terme_Puissance_Thermique::mettre_a_jour(), Transport_Interfaces_FT_Disc::mettre_a_jour(), Boundary_field_keps_from_ud::mettre_a_jour(), Portance_interfaciale_PolyMAC_P0::mettre_a_jour(), Navier_Stokes_std::mettre_a_jour(), Fluide_reel_base::mettre_a_jour(), Domaine_ALE::mettre_a_jour(), Echange_interne_impose::mettre_a_jour(), Navier_Stokes_phase_field::mettre_a_jour(), EDO_Pression_th_base::mettre_a_jour_CL(), Milieu_base::mettre_a_jour_porosite(), Navier_Stokes_IBM_Turbulent::modele_turbulence(), Navier_Stokes_Turbulent::modele_turbulence(), Op_Diff_VEF_Face_Stab::modifie_pour_Cl(), Op_Grad_VEF_P1B_Face::modifier_grad_pour_Cl(), Eq_rayo_semi_transp_VDF::modifier_matrice(), Eq_rayo_semi_transp_VEF::modifier_matrice(), Assembleur_P_VEF::modifier_matrice(), Assembleur_P_VEFPreP1B::modifier_matrice(), Op_VEF_Face::modifier_matrice_pour_periodique_apres_contribuer(), Op_Diff_Turbulent_PolyMAC_P0_Elem::modifier_mu(), Op_EF_base::modifier_pour_Cl(), Op_VDF_Face::modifier_pour_Cl(), Op_VEF_Face::modifier_pour_Cl(), Op_Diff_K_Eps_VDF_base::modifier_pour_Cl(), Op_Diff_K_Omega_VDF_base::modifier_pour_Cl(), Op_Conv_ALE_VEF::modifier_pour_Cl(), AssembleurPVDF_PF::modifier_secmem(), Assembleur_P_EF::modifier_secmem(), Assembleur_P_PolyMAC::modifier_secmem(), Assembleur_P_VDF::modifier_secmem(), Assembleur_P_VEF::modifier_secmem(), Assembleur_P_VEFPreP1B::modifier_secmem(), Assembleur_P_VEFPreP1B::modifier_secmem_elem(), Assembleur_P_VEFPreP1B::modifier_secmem_som(), IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::modify_rhs_for_bc(), Matrice_Bloc::nb_colonnes(), Matrice_Bloc::nb_lignes(), Champ_Generique_Predefini::nommer_source(), Polygone_poly::normale(), Champ_Generique_Divergence::Operateur(), Champ_Generique_Gradient::Operateur(), TRUST_Deriv< _CLASSE_ >::operator _CLASSE_ &(), TRUST_Deriv< _CLASSE_ >::operator const _CLASSE_ &(), Cond_lim::operator=(), Matrice_Morse_Sym::operator=(), Matrice::operator=(), TRUST_Deriv< _CLASSE_ >::operator=(), IJK_Thermal_cut_cell::perform_thermal_step(), IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::pre_initialise_matrix_subproblems(), IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::pre_initialise_sparse_matrix_subproblems(), SSOR::preconditionner_(), ILU_SP::prepare_(), Precond_local::prepare_(), Solv_GCP::prepare_data(), Probleme_FTD_IJK_base::preparer_calcul(), Navier_Stokes_FT_Disc::preparer_calcul(), Transport_Interfaces_FT_Disc::preparer_calcul(), Navier_Stokes_phase_field::preparer_calcul(), Modele_rayo_semi_transp::preparer_calcul(), Navier_Stokes_IBM::preparer_calcul(), Navier_Stokes_std::preparer_calcul(), Paroi_std_hyd_VDF::preparer_calcul_hyd(), Navier_Stokes_std::pression(), Navier_Stokes_std::pression_pa(), Domaine_EF::printOn(), Domaine_Poly_base::printOn(), Domaine_VEF::printOn(), Navier_Stokes_std::projeter(), Flux_parietal_Hibiki::qp(), Flux_parietal_Kommajosyula::qp(), Flux_parietal_Kurul_Podowski::qp(), Debog_Pb::read_geometry_data(), Solv_AMG::read_matrix(), Probleme_base::read_optional_equations(), Champ_Fonc_reprise_IJK::readOn(), Fluide_Diphasique::readOn(), Topologie_Maillage_FT::readOn(), Postraitement_ft_lata::readOn(), Modele_turbulence_scal_Fluctuation_Temperature_W::readOn(), Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re::readOn(), Source_Scalaire_EF::readOn(), Puissance_Thermique_EF::readOn(), Champ_Input_P0_Composite::readOn(), Milieu_base::readOn(), Sources::readOn(), Solv_AMG::readOn(), Pb_MED::readOn(), Pbc_MED::readOn(), Source_Masse_Fluide_Dilatable_base::readOn(), Navier_Stokes_std::readOn(), Fluide_base::readOn(), Milieu_composite::readOn(), Milieu_MUSIG::readOn(), Solide::readOn(), Terme_Puissance_Thermique_VDF_base::readOn(), Source_QC_QDM_Gen::readOn_spec(), Cond_Lim_rayo_semi_transp::recherche_emissivite_et_A(), IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::recombined_local_sub_matrix_with_matrix(), IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::reinitialise_matrix_subproblem(), Transport_Interfaces_FT_Disc::remailler_interface(), Topologie_Maillage_FT::remailler_interface(), Assembleur_P_VEF::remplir(), AssembleurPVDF_PF::remplir(), Assembleur_P_VDF::remplir(), Op_Conv_VEF_Face::remplir_fluent(), Operateur_Conv_sensibility_VEF::remplir_fluent(), Op_Dift_EF_Q1::remplir_marqueur_elem_CL_paroi(), Iterateur_Source_VEF_Face< _TYPE_ >::remplir_volumes_cl_dirichlet(), Navier_Stokes_std_ALE::renewing_jacobians(), Matrice_Morse_Sym::renumerote(), Transport_Interfaces_FT_Disc::reprendre(), Paroi_TBLE_QDM::reprendre(), Paroi_TBLE_QDM_Scal::reprendre(), Probleme_FTD_IJK_base::reprendre_probleme(), Milieu_base::resetTime(), EDO_Pression_th_VDF_Gaz_Parfait::resoudre(), EDO_Pression_th_VDF_Gaz_Reel::resoudre(), EDO_Pression_th_VEF_Gaz_Reel::resoudre(), EDO_Pression_th_VEF_Gaz_Parfait::resoudre(), Solv_Cholesky::resoudre_systeme(), Solv_Gen::resoudre_systeme(), Solv_Gmres::resoudre_systeme(), Probleme_FTD_IJK_base::rk3_sub_step(), Transport_Interfaces_FT_Disc::sauvegarder(), Paroi_TBLE_QDM::sauvegarder(), Paroi_TBLE_QDM_Scal::sauvegarder(), Transport_Interfaces_FT_Disc_interne::sauvegarder(), Probleme_FTD_IJK_base::sauvegarder_probleme(), Save_Restart::sauver(), Save_Restart::sauver_xyz(), Matrice_Bloc::scale(), IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::scale_matrix_by_vector(), Fluide_Dilatable_base::set_Cp(), Solv_Gen::solve(), Probleme_FTD_IJK_base::solveTimeStep(), Probleme_FTD_IJK_base::solveTimeStep_Euler(), Probleme_FTD_IJK_base::solveTimeStep_RK3(), Navier_Stokes_Fluide_Dilatable_base::source_masse(), SSOR::ssor(), IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::sum_matrices(), IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::sum_matrices_subproblems(), IJK_Finite_Difference_One_Dimensional_Matrix_Assembler::sum_sparse_matrices_subproblems(), Transport_Interfaces_FT_Disc::swap_particles_lagrangian_position_velocity(), Echange_impose_base::T_ext(), Convection_Diffusion_Temperature_base::t_paroi_thyd(), Op_Diff_VEFP1NCP1B_Face::test(), Op_Diff_RotRot::tester(), TRUST_Deriv< _CLASSE_ >::TRUST_Deriv(), Iterateur_PolyMAC_base::type_cl(), Iterateur_VDF_base::type_cl(), Domaine_EF::type_elem(), Domaine_Poly_base::type_elem(), Domaine_VEF::type_elem(), Domaine_VEF::typer_elem(), Domaine_EF::typer_elem(), Domaine_Poly_base::typer_elem(), TRUST_Deriv< _CLASSE_ >::typer_lire(), Op_Diff_PolyMAC_P0P1NC_base::update_aux(), Milieu_base::update_rho_cp(), Fluide_Dilatable_base::update_rho_cp(), Probleme_FTD_IJK_cut_cell::update_twice_indicator_field(), Champ_Face_VDF::verifie_valeurs_cl(), Champ_P1NC::verifie_valeurs_cl(), Champ_Q1NC::verifie_valeurs_cl(), Fluide_Diphasique::verifier_coherence_champs(), Fluide_Dilatable_base::verifier_coherence_champs(), Fluide_base::verifier_coherence_champs(), Fluide_Incompressible::verifier_coherence_champs(), Solide::verifier_coherence_champs(), Assembleur_P_VEFPreP1B::verifier_dirichlet(), Fluide_base::viscosite_cinematique(), Fluide_base::viscosite_dynamique(), and Navier_Stokes_std::vitesse().
valeur() [2/2]
template<typename _CLASSE_ > _CLASSE_ & TRUST_Deriv< _CLASSE_ >::valeur () inline
References Objet_U_ptr::get_Objet_U_ptr_check().
operator->() [1/2]
template<typename _CLASSE_ > const _CLASSE_ * TRUST_Deriv< _CLASSE_ >::operator-> () const inline
References Objet_U_ptr::get_Objet_U_ptr_check().
operator->() [2/2]
template<typename _CLASSE_ > _CLASSE_ * TRUST_Deriv< _CLASSE_ >::operator-> () inline
References Objet_U_ptr::get_Objet_U_ptr_check().
operator=() [1/2]
template<typename _CLASSE_ > const TRUST_Deriv & TRUST_Deriv< _CLASSE_ >::operator= (const _CLASSE_ & t) inline
References Objet_U_ptr::detach(), and Objet_U_ptr::recopie().
operator=() [2/2]
template<typename _CLASSE_ > const TRUST_Deriv & TRUST_Deriv< _CLASSE_ >::operator= (const TRUST_Deriv< _CLASSE_ > & t) inline
References Objet_U_ptr::detach(), Objet_U_ptr::non_nul(), Objet_U_ptr::recopie(), and TRUST_Deriv< _CLASSE_ >::valeur().
operator const _CLASSE_ &()
template<typename _CLASSE_ > TRUST_Deriv< _CLASSE_ >::operator const _CLASSE_ & () const inline
References TRUST_Deriv< _CLASSE_ >::valeur().
operator _CLASSE_ &()
template<typename _CLASSE_ > TRUST_Deriv< _CLASSE_ >::operator _CLASSE_ & () inline
References TRUST_Deriv< _CLASSE_ >::valeur().
get_info_ptr()
template<typename _CLASSE_ > const Type_info & TRUST_Deriv< _CLASSE_ >::get_info_ptr () const inline override virtual
Implements Objet_U_ptr.
typer_lire_simple()
template<typename _CLASSE_ > Entree & TRUST_Deriv< _CLASSE_ >::typer_lire_simple (Entree & is, const char * msg = "??") inline
References TRUST_Deriv< _CLASSE_ >::typer_lire().
Referenced by Milieu_composite::readOn(), and Milieu_MUSIG::readOn().
typer_lire()
template<typename _CLASSE_ > Entree & TRUST_Deriv< _CLASSE_ >::typer_lire (Entree & is, const char * b = "??", const char * msg = "??") inline
References Objet_U_ptr::typer(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by Fluide_Dilatable_base::lire_motcle_non_standard(), and TRUST_Deriv< _CLASSE_ >::typer_lire_simple().