TrioCFD: Flux_radiatif_VEF Class Reference
Flux_radiatif_VEF Class Reference
#include <Flux_radiatif_VEF.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Flux_radiatif_base
void completer () override
const Type_info * get_info () const override
Public Member Functions inherited from Neumann_paroi
const Type_info * get_info () const override
void verifie_ch_init_nb_comp () const override
Public Member Functions inherited from Neumann
const DoubleTab & flux_impose (bool nb_faces_tot=false) const
virtual double flux_impose (int i) const
virtual double flux_impose (int i, int j) const
const Type_info * get_info () const override
Public Member Functions inherited from Cond_lim_base
virtual int a_mettre_a_jour_ss_pas_dt ()
virtual void associer_domaine_cl_dis_base (const Domaine_Cl_dis_base &)
virtual void associer_fr_dis_base (const Frontiere_dis_base &)
virtual void calculer_coeffs_echange (double temps)
virtual int compatible_avec_discr (const Discretisation_base &) const
Domaine_Cl_dis_base & domaine_Cl_dis ()
const Domaine_Cl_dis_base & domaine_Cl_dis () const
virtual Frontiere_dis_base & frontiere_dis ()
virtual const Frontiere_dis_base & frontiere_dis () const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
void set_modifier_val_imp (int)
virtual void verifie_ch_init_nb_comp () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Cond_lim_base
void err_pas_compatible (const Discretisation_base &) const
void err_pas_compatible (const Equation_base &) const
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
.FINHTML .FINEPS
Constructor & Destructor Documentation
Flux_radiatif_VEF()
Flux_radiatif_VEF::Flux_radiatif_VEF ()
~Flux_radiatif_VEF()
Flux_radiatif_VEF::~Flux_radiatif_VEF ()
Member Function Documentation
cree_instance()
Objet_U * Flux_radiatif_VEF::cree_instance () static
taille_memoire()
unsigned Flux_radiatif_VEF::taille_memoire () const override virtual
Reimplemented from Neumann_paroi.
duplique()
int Flux_radiatif_VEF::duplique () const override virtual
Reimplemented from Neumann_paroi.
info()
const Type_info * Flux_radiatif_VEF::info () static
get_info()
const Type_info * Flux_radiatif_VEF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Flux_radiatif_base.
self_cast() [1/2]
Flux_radiatif_VEF & Flux_radiatif_VEF::self_cast (Objet_U & r) static
self_cast() [2/2]
const Flux_radiatif_VEF & Flux_radiatif_VEF::self_cast (const Objet_U & r) static
printOn()
Sortie & Flux_radiatif_VEF::printOn (Sortie & s) const override protected virtual
Imprime le type de l'equation sur un flot de sortie.
Parameters
(Sortie& s) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Flux_radiatif_base.
References Objet_U::que_suis_je().
readOn()
Entree & Flux_radiatif_VEF::readOn (Entree & s) override protected virtual
Parameters
(Entree& s) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Flux_radiatif_base.
References Flux_radiatif_base::readOn().
evaluer_cl_rayonnement()
void Flux_radiatif_VEF::evaluer_cl_rayonnement (Champ_front_base & Tb, const Champ_Don_base & coeff_abs, const Champ_Don_base & longueur_rayo, const Champ_Don_base & indice, const Domaine_VF & zvf, const double sigma, double temps)
References Flux_radiatif_base::emissivite(), Cond_lim_base::frontiere_dis(), Cond_lim_base::le_champ_front, Field_base::nb_comp(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), Champ_Don_base::valeurs(), Champ_front_base::valeurs(), and Champ_front_base::valeurs_au_temps().
Referenced by Eq_rayo_semi_transp_VEF::evaluer_cl_rayonnement().
calculer_flux_radiatif()
void Flux_radiatif_VEF::calculer_flux_radiatif (const Equation_base & eq_temp) override virtual
Implements Flux_radiatif_base.
References Flux_radiatif_base::A(), Objet_U::dimension, Cond_lim_base::domaine_Cl_dis(), Equation_base::domaine_Cl_dis(), Flux_radiatif_base::emissivite(), Process::exit(), Domaine_VF::face_normales(), Equation_rayonnement_base::fluide(), Flux_radiatif_base::flux_radiatif(), Cond_lim_base::frontiere_dis(), Equation_rayonnement_base::inconnue(), Fluide_base::indice(), Objet_U::le_nom(), Frontiere_dis_base::le_nom(), Objet_U_ptr::le_nom(), Domaine_Cl_dis_base::les_conditions_limites(), Schema_Temps_base::limpr(), Equation_rayonnement_base::Modele(), Field_base::nb_comp(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Equation_base::schema_temps(), TRUST_Vector< _CLASSE_ >::size(), Frontiere_ouverte_rayo_semi_transp::temperature_bord(), Frontiere_ouverte_temperature_imposee_rayo_semi_transp::temperature_bord(), Neumann_paroi_rayo_semi_transp_VEF::temperature_bord(), Temperature_imposee_paroi_rayo_semi_transp::temperature_bord(), TRUST_Deriv< _CLASSE_ >::valeur(), Modele_rayo_semi_transp::valeur_sigma(), Champ_Don_base::valeurs(), Champ_front_base::valeurs(), Champ_Inc_base::valeurs(), and Debog::verifier_bord().
Member Data Documentation
info_obj
const Type_info Flux_radiatif_VEF::info_obj static