TrioCFD: Navier_Stokes_phase_field Class Reference
Navier_Stokes_phase_field Class Reference
#include <Navier_Stokes_phase_field.h>
Public Member Functions
double calculer_pas_de_temps () const override
void completer () override
DoubleTab & derivee_en_temps_inco (DoubleTab &) override
const Type_info * get_info () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
void mettre_a_jour (double) override
Public Member Functions inherited from Navier_Stokes_std
void abortTimeStep () override
void associer_milieu_base (const Milieu_base &) override
void associer_pb_base (const Probleme_base &) override
virtual void calculer_la_pression_en_pa ()
void completer () override
DoubleTab & derivee_en_temps_inco (DoubleTab &) override
const Motcle & domaine_application () const override
Fluide_base & fluide ()
const Fluide_base & fluide () const
const Type_info * get_info () const override
int impr (Sortie &os) const override
const Champ_Inc_base & inconnue () const override
Champ_Inc_base & inconnue () override
bool initTimeStep (double dt) override
Entree & lire_cond_init (Entree &) override
int lire_motcle_non_standard (const Motcle &, Entree &) override
void mettre_a_jour (double temps) override
const Milieu_base & milieu () const override
Milieu_base & milieu () override
int nombre_d_operateurs () const override
const Operateur & operateur (int) const override
Operateur & operateur (int) override
Operateur_Div & operateur_divergence ()
const Operateur_Div & operateur_divergence () const
Operateur_Grad & operateur_gradient ()
const Operateur_Grad & operateur_gradient () const
int preparer_calcul () override
virtual void projeter ()
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
SolveurSys & solveur_pression ()
int verif_Cl () const override
Public Member Functions inherited from Equation_base
virtual void abortTimeStep ()
virtual void associer_domaine_dis (const Domaine_dis_base &)
virtual void associer_pb_base (const Probleme_base &)
virtual void associer_sch_tps_base (const Schema_Temps_base &)
virtual double calculer_pas_de_temps () const
virtual void completer ()
virtual std::vector< YAML_data > data_a_sauvegarder () const
DoubleTab & derivee_en_temps_conv (DoubleTab &, const DoubleTab &)
virtual DoubleTab & derivee_en_temps_inco (DoubleTab &)
const Discretisation_base & discretisation () const
virtual void discretiser ()
virtual const Motcle & domaine_application () const
virtual Domaine_Cl_dis_base & domaine_Cl_dis ()
virtual const Domaine_Cl_dis_base & domaine_Cl_dis () const
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual void imprimer (Sortie &os) const
virtual bool initTimeStep (double dt)
const Nom & le_nom () const override
int limpr () const
virtual void mettre_a_jour (double temps)
virtual int preparer_calcul ()
Probleme_base & probleme ()
const Probleme_base & probleme () const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Schema_Temps_base & schema_temps ()
const Schema_Temps_base & schema_temps () const
Solveur_Masse_base & solv_masse ()
const Solveur_Masse_base & solv_masse () const
Sources & sources ()
const Sources & sources () const
virtual void valider_iteration ()
virtual void verifie_ch_init_nb_comp (const Champ_Inc_base &ch_ref, const int nb_comp) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Navier_Stokes_std
virtual void discretiser_assembleur_pression ()
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Equation_base
virtual Entree & lire_cl (Entree &)
virtual Entree & lire_cond_init (Entree &)
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual Entree & lire_sources (Entree &)
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
virtual int verif_Cl () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
pour un fluide sans modelisation de la turbulence. On suppose l'hypothese de fluide incompressible: div U = 0 On peut 1) soit utiliser un modele a rho variable 2) soit utiliser l'hypothese de Boussinesq Dans ce cas, on considere la masse volumique constante (egale a rho_0) sauf dans le terme des forces de gravite. Sous ces hypotheses, on utilise la forme suivante des equations de Navier_Stokes: DU/dt = div(terme visqueux) - gradP/rho_0 + Bt(T-T0)g + autres sources/rho_0 div U = 0 avec DU/dt : derivee particulaire de la vitesse rho_0 : masse volumique de reference T0 : temperature de reference Bt : coefficient de dilatabilite du fluide g : vecteur gravite Rq : l'implementation de la classe permet bien sur de negliger certains termes de l'equation (le terme visqueux, le terme convectif, tel ou tel terme source). L'inconnue est le champ de vitesse.
Pour le traitement des cas un peu particulier : ajout de Traitement_particulier exemple : THI, canal (CA)
See also
Equation_base Pb_Hydraulique Pb_Thermohydraulique, Post-traitement du potentiel chimique generalise
Constructor & Destructor Documentation
Navier_Stokes_phase_field()
Navier_Stokes_phase_field::Navier_Stokes_phase_field ()
References boussi_, diff_boussi_, g_, and TRUSTVect< _TYPE_, _SIZE_ >::resize().
~Navier_Stokes_phase_field()
Navier_Stokes_phase_field::~Navier_Stokes_phase_field () override
Member Function Documentation
cree_instance()
Objet_U * Navier_Stokes_phase_field::cree_instance () static
taille_memoire()
unsigned Navier_Stokes_phase_field::taille_memoire () const override virtual
Reimplemented from Navier_Stokes_std.
duplique()
int Navier_Stokes_phase_field::duplique () const override virtual
Reimplemented from Navier_Stokes_std.
info()
const Type_info * Navier_Stokes_phase_field::info () static
get_info()
const Type_info * Navier_Stokes_phase_field::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Navier_Stokes_std.
self_cast() [1/2]
Navier_Stokes_phase_field & Navier_Stokes_phase_field::self_cast (Objet_U & r) static
self_cast() [2/2]
const Navier_Stokes_phase_field & Navier_Stokes_phase_field::self_cast (const Objet_U & r) static
printOn()
Sortie & Navier_Stokes_phase_field::printOn (Sortie & is) const override protected virtual
Simple appel a: Navier_Stokes_std::printOn(Sortie&) Ecrit l'equation sur un flot de sortie.
Parameters
(Sortie& os) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Navier_Stokes_std.
References Navier_Stokes_std::printOn().
readOn()
Entree & Navier_Stokes_phase_field::readOn (Entree & is) override protected virtual
Appel Navier_Stokes_phase_field::readOn(Entree& is) En sortie verifie que l'on a bien lu:
   - le terme diffusif,
   - le terme convectif,
   - le solveur en pression
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Exceptions
terme diffusif non specifie dans jeu de donnees, specifier un type negligeable pour l'operateur si il est a negliger
terme convectif non specifie dans jeu de donnees, specifier un type negligeable pour l'operateur si il est a negliger
solveur pression non defini dans jeu de donnees
Reimplemented from Navier_Stokes_std.
References TRUST_List< _CLASSE_ >::add(), Equation_base::discretisation(), Process::exit(), g_, Equation_base::les_sources, Objet_U::que_suis_je(), Navier_Stokes_std::readOn(), TRUSTVect< _TYPE_, _SIZE_ >::size(), and Source::typer_direct().
set_param()
void Navier_Stokes_phase_field::set_param (Param & titi) override virtual
Reimplemented from Navier_Stokes_std.
References Param::ajouter(), Param::ajouter_non_std(), g_, Param::OPTIONAL, Param::REQUIRED, and Navier_Stokes_std::set_param().
lire_motcle_non_standard()
int Navier_Stokes_phase_field::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Navier_Stokes_std.
References Champs_compris_T< FIELD_TYPE >::ajoute_champ(), boussi_, Equation_base::champs_compris_, diff_boussi_, Equation_base::discretisation(), Equation_base::domaine_dis(), drhodc_, Process::exit(), Navier_Stokes_std::le_fluide, Navier_Stokes_std::lire_motcle_non_standard(), mu_, Discretisation_base::nommer_completer_champ_physique(), Equation_base::probleme(), and rho_.
discretiser()
void Navier_Stokes_phase_field::discretiser () override virtual
Dicretise l'equation.
Reimplemented from Navier_Stokes_std.
References Navier_Stokes_std::assembleur_pression_, Assembleur_base::associer_domaine_dis_base(), Navier_Stokes_std::discretiser(), Equation_base::domaine_dis(), Process::exit(), Navier_Stokes_std::le_fluide, TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), rho0_, Assembleur_base::set_resoudre_increment_pression(), and Objet_U_ptr::typer().
completer()
void Navier_Stokes_phase_field::completer () override virtual
Complete l'equation base, associe la pression a l'equation,.
complete la divergence, le gradient et le solveur pression. Ajout de 2 termes sources: l'un representant la force centrifuge dans le cas axi-symetrique,l'autre intervenant dans la resolution en 2D axisymetrique Association d une equation de transport d interface a l ensemble de points suivis si le fluide est marque
Reimplemented from Navier_Stokes_std.
References betac_, Navier_Stokes_std::completer(), creer_champ(), and Navier_Stokes_std::le_fluide.
preparer_calcul()
int Navier_Stokes_phase_field::preparer_calcul () override virtual
Dicretise l'equation.
Reimplemented from Navier_Stokes_std.
References Assembleur_base::assembler(), Assembleur_base::assembler_rho_variable(), Navier_Stokes_std::assembleur_pression_, boussi_, Operateur_Grad::calculer(), Navier_Stokes_std::calculer_la_pression_en_pa(), calculer_mu(), calculer_rho(), Champ_base::changer_temps(), Champ_Inc_base::changer_temps(), Navier_Stokes_std::divergence_U, drhodc_, TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Navier_Stokes_std::gradient, Navier_Stokes_std::gradient_P, Navier_Stokes_std::inconnue(), Champ_Don_base::initialiser(), Navier_Stokes_std::la_pression, Navier_Stokes_std::le_traitement_particulier, Navier_Stokes_std::matrice_pression_, mu_, Objet_U_ptr::non_nul(), Equation_base::preparer_calcul(), Traitement_particulier_NS_base::preparer_calcul_particulier(), Navier_Stokes_std::projection_a_faire(), Navier_Stokes_std::projeter(), rho_, rho_aux_faces(), Equation_base::schema_temps(), TRUST_Deriv< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), Champ_Inc_base::valeurs(), and Debog::verifier().
rho_aux_faces()
void Navier_Stokes_phase_field::rho_aux_faces (const DoubleTab & tab_rho, Champ_Don_base & rho_face_P) virtual
Interpole la masse volumique aux faces (pour l'assembleur pression en particulier)
References Equation_base::domaine_dis(), Domaine_VF::face_voisins(), Domaine_VF::nb_faces(), Domaine_VF::premiere_face_int(), Champ_Don_base::valeurs(), and Domaine_VF::volumes().
Referenced by mettre_a_jour(), and preparer_calcul().
rho()
const Champ_Don_base & Navier_Stokes_phase_field::rho () const inline
References rho_.
Referenced by Source_Gravite_PF_VDF::ajouter(), Source_Con_Phase_field::calculer_div_alpha_rho_gradC(), calculer_pas_de_temps(), Source_Qdm_VDF_Phase_field::methode_1(), Source_Qdm_VDF_Phase_field::methode_2(), Source_Qdm_VDF_Phase_field::methode_3(), and Source_Qdm_VDF_Phase_field::methode_4().
drhodc()
const Champ_Don_base & Navier_Stokes_phase_field::drhodc () const inline
References drhodc_.
Referenced by Source_Con_Phase_field::associer_pb().
rho0()
const double & Navier_Stokes_phase_field::rho0 () const inline
References rho0_.
Referenced by Source_Gravite_PF_VDF::ajouter(), Source_Con_Phase_field::associer_pb(), and Source_Qdm_VDF_Phase_field::associer_pb().
mu() [1/2]
Champ_Don_base & Navier_Stokes_phase_field::mu () inline
References mu_.
mu() [2/2]
const Champ_Don_base & Navier_Stokes_phase_field::mu () const inline
References mu_.
get_boussi_()
int & Navier_Stokes_phase_field::get_boussi_ () inline
References boussi_.
Referenced by Source_Gravite_PF_VDF::ajouter(), Source_Con_Phase_field::associer_pb(), and Source_Qdm_VDF_Phase_field::associer_pb().
get_g_() [1/2]
DoubleVect & Navier_Stokes_phase_field::get_g_ () inline
References g_.
Referenced by Source_Gravite_PF_VDF::ajouter(), and Source_Con_Phase_field::associer_pb().
get_g_() [2/2]
const DoubleVect & Navier_Stokes_phase_field::get_g_ () const inline
References g_.
derivee_en_temps_inco()
DoubleTab & Navier_Stokes_phase_field::derivee_en_temps_inco (DoubleTab & derivee) override virtual
Returns the time derivative of the unknown I of the equation: dI/dt = M-1*(sum(operators(I) + sources))
In : derivee contains I (but immediatly set to 0) Out: derivee contains dI/dt
Reimplemented from Navier_Stokes_std.
References Operateur_Conv::ajouter(), Operateur_Diff::ajouter(), Operateur_Div::ajouter(), Sources::ajouter(), Solveur_Masse_base::appliquer(), Assembleur_base::assembler_rho_variable(), Navier_Stokes_std::assembleur_pression_, boussi_, Equation_base::calculate_time_derivative(), Operateur_Div::calculer(), Operateur_Grad::calculer(), Equation_base::derivee_en_temps(), Navier_Stokes_std::derivee_en_temps_inco(), diff_boussi_, Objet_U::dimension, Navier_Stokes_std::divergence, Equation_base::domaine_dis(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_VF::face_voisins(), Navier_Stokes_std::gradient, Navier_Stokes_std::inconnue(), Navier_Stokes_std::la_pression, Navier_Stokes_std::la_vitesse, Equation_base::le_dom_dis, Equation_base::le_schema_en_temps, Equation_base::les_sources, TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Navier_Stokes_std::matrice_pression_, Assembleur_base::modifier_secmem(), Schema_Temps_base::modifier_second_membre(), Assembleur_base::modifier_solution(), Domaine_VF::nb_faces(), Domaine_VF::premiere_face_int(), SolveurSys::resoudre_systeme(), rho0_, rho_, Equation_base::schema_temps(), Equation_base::solveur_masse, Navier_Stokes_std::solveur_pression_, Navier_Stokes_std::terme_convectif, Navier_Stokes_std::terme_diffusif, TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), Champ_Inc_base::valeurs(), and Domaine_VF::volumes().
mettre_a_jour()
void Navier_Stokes_phase_field::mettre_a_jour (double temps) override virtual
Effectue une mise a jour en temps de l'equation.
Appelle Equation_base::mettre_a_jour(double) et met a jour la pression. Integration des points suivis si le fluide est marque Mise a jour du champ postraitable correspondant
Parameters
(double temps) le temps de mise a jour
Reimplemented from Navier_Stokes_std.
References Assembleur_base::assembler(), Assembleur_base::assembler_rho_variable(), Navier_Stokes_std::assembleur_pression_, boussi_, calculer_mu(), calculer_rho(), Champ_base::changer_temps(), drhodc_, Navier_Stokes_std::inconnue(), Navier_Stokes_std::matrice_pression_, Navier_Stokes_std::mettre_a_jour(), mu_, Objet_U_ptr::non_nul(), rho_, rho_aux_faces(), TRUST_Deriv< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), and Champ_Inc_base::valeurs().
diffusivite_pour_transport()
const Champ_Don_base & Navier_Stokes_phase_field::diffusivite_pour_transport () const override virtual
Reimplemented from Navier_Stokes_std.
References boussi_, diff_boussi_, diffusivite_pour_transport(), Process::exit(), Navier_Stokes_std::le_fluide, and mu_.
Referenced by diffusivite_pour_transport().
creer_champ()
void Navier_Stokes_phase_field::creer_champ (const Motcle & motlu) override virtual
Reimplemented from Navier_Stokes_std.
References Champs_compris_T< FIELD_TYPE >::ajoute_champ(), boussi_, Equation_base::champs_compris_, Navier_Stokes_std::creer_champ(), Equation_base::discretisation(), Discretisation_base::discretiser_champ(), Equation_base::domaine_dis(), drhodc_, Process::exit(), Navier_Stokes_std::le_fluide, Objet_U_ptr::le_nom(), Discretisation_base::nommer_completer_champ_physique(), Objet_U_ptr::non_nul(), Equation_base::probleme(), and rho_.
Referenced by completer().
calculer_rho()
void Navier_Stokes_phase_field::calculer_rho (const bool init = false) virtual
Calcule rho_n+1 pour utilisation dans la pression.
References betac_, boussi_, Source_Con_Phase_field_base::calculer_champ_fonc_c(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), drhodc_, TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Champ_Inc_base::futur(), Source_Con_Phase_field::get_type_systeme_naire(), Convection_Diffusion_Concentration::inconnue(), Navier_Stokes_std::le_fluide, TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Equation_base::mon_probleme, rho0_, rho_, Equation_base::schema_temps(), Equation_base::sources(), Schema_Temps_base::temps_courant(), Schema_Temps_base::temps_futur(), and Champ_Don_base::valeurs().
Referenced by Schema_Phase_field::faire_un_pas_de_temps_eqn_base(), mettre_a_jour(), and preparer_calcul().
calculer_mu()
void Navier_Stokes_phase_field::calculer_mu (const bool init = false) virtual
References boussi_, Source_Con_Phase_field_base::calculer_champ_fonc_c(), diff_boussi_, TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Champ_Inc_base::futur(), Convection_Diffusion_Concentration::inconnue(), Equation_base::mon_probleme, mu_, Equation_base::schema_temps(), Equation_base::sources(), Schema_Temps_base::temps_courant(), Schema_Temps_base::temps_futur(), and Champ_Don_base::valeurs().
Referenced by mettre_a_jour(), and preparer_calcul().
calculer_pas_de_temps()
double Navier_Stokes_phase_field::calculer_pas_de_temps () const override virtual
Calcul du prochain pas de temps.
Renvoie l'inverse de la somme des inverses des pas de temps calcules par les operateurs. Ces pas de temps sont ceux pour le schema d'Euler explicite. Le pas de temps n'est pas majore par dt_max, ceci est fait dans corriger_dt_calcule
Returns
(double) inverse de la somme des inverses des pas de temps calcules par les operateurs
Reimplemented from Equation_base.
References Operateur::calculer_pas_de_temps(), Statistiques::last_time(), Equation_base::le_schema_en_temps, Schema_Temps_base::nb_pas_dt(), Equation_base::probleme(), rho(), Equation_base::schema_temps(), Schema_Temps_base::temps_courant(), Schema_Temps_base::temps_init(), Schema_Temps_base::temps_max(), Navier_Stokes_std::terme_convectif, Navier_Stokes_std::terme_diffusif, and Champ_Don_base::valeurs().
getset_terme_source_()
int & Navier_Stokes_phase_field::getset_terme_source_ () inline
References terme_source_.
Referenced by Source_Con_Phase_field::associer_pb(), and Source_Qdm_VDF_Phase_field::associer_pb().
getset_compressible_()
int & Navier_Stokes_phase_field::getset_compressible_ () inline
References compressible_.
Referenced by Source_Qdm_VDF_Phase_field::associer_pb().
get_diff_boussi_()
int & Navier_Stokes_phase_field::get_diff_boussi_ () inline
References diff_boussi_.
Referenced by Source_Con_Phase_field::associer_pb().
_aff_donnee_P0()
void Navier_Stokes_phase_field::_aff_donnee_P0 (const DoubleTab & tab, const Motcle & mot) const protected
References Objet_U::dimension, Equation_base::domaine_dis(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Domaine_dis_base::nb_elem_tot(), and Domaine_VF::xp().
_aff_donnee_P1()
void Navier_Stokes_phase_field::_aff_donnee_P1 (const DoubleTab & tab, const Motcle & mot) const protected
References Objet_U::dimension, Equation_base::domaine_dis(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Domaine_VF::nb_faces(), and Domaine_VF::xv().
_aff_donnee_P1Bulle()
void Navier_Stokes_phase_field::_aff_donnee_P1Bulle (const DoubleTab & tab, const Motcle & mot) const protected
References Domaine_32_64< _SIZE_ >::coord_sommets(), Objet_U::dimension, Domaine_dis_base::domaine(), Equation_base::domaine_dis(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Domaine_dis_base::nb_elem_tot(), Domaine_dis_base::nb_som(), and Domaine_VF::xp().
Member Data Documentation
info_obj
const Type_info Navier_Stokes_phase_field::info_obj static
rho_
TRUST_Deriv< Champ_Don_base > Navier_Stokes_phase_field::rho_ protected
Referenced by calculer_rho(), creer_champ(), derivee_en_temps_inco(), lire_motcle_non_standard(), mettre_a_jour(), preparer_calcul(), and rho().
drhodc_
TRUST_Deriv< Champ_Don_base > Navier_Stokes_phase_field::drhodc_ protected
Referenced by calculer_rho(), creer_champ(), drhodc(), lire_motcle_non_standard(), mettre_a_jour(), and preparer_calcul().
rho0_
double Navier_Stokes_phase_field::rho0_ protected
Referenced by calculer_rho(), derivee_en_temps_inco(), discretiser(), and rho0().
betac_
TRUST_Ref< Champ_Don_base *> Navier_Stokes_phase_field::betac_ protected
Referenced by calculer_rho(), and completer().
mu_
TRUST_Deriv< Champ_Don_base > Navier_Stokes_phase_field::mu_ protected
Referenced by calculer_mu(), diffusivite_pour_transport(), lire_motcle_non_standard(), mettre_a_jour(), mu(), and preparer_calcul().
boussi_
int Navier_Stokes_phase_field::boussi_ protected
Referenced by calculer_mu(), calculer_rho(), creer_champ(), derivee_en_temps_inco(), diffusivite_pour_transport(), get_boussi_(), lire_motcle_non_standard(), mettre_a_jour(), Navier_Stokes_phase_field(), and preparer_calcul().
diff_boussi_
int Navier_Stokes_phase_field::diff_boussi_ protected
Referenced by calculer_mu(), derivee_en_temps_inco(), diffusivite_pour_transport(), get_diff_boussi_(), lire_motcle_non_standard(), and Navier_Stokes_phase_field().
g_
DoubleVect Navier_Stokes_phase_field::g_ protected
Referenced by get_g_(), Navier_Stokes_phase_field(), readOn(), and set_param().
terme_source_
int Navier_Stokes_phase_field::terme_source_ protected
Referenced by getset_terme_source_().
compressible_
int Navier_Stokes_phase_field::compressible_ protected
Referenced by getset_compressible_().