TrioCFD: EcrFicCollecteBin Class Reference
EcrFicCollecteBin Class Reference
#include <EcrFicCollecteBin.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from EcrFicCollecte
EcrFicCollecte (const char *name, std::ios_base::openmode mode=ios::out)
const Type_info * get_info () const override
int ouvrir (const char *name, std::ios_base::openmode mode=ios::out) override
Public Member Functions inherited from SFichier
const Type_info * get_info () const override
Public Member Functions inherited from Sortie_Fichier_base
Sortie & flush () override
const Type_info * get_info () const override
Public Member Functions inherited from Sortie
virtual Sortie & operator<< (const char *ob)
virtual Sortie & operator<< (const Objet_U &ob)
void set_bin (bool bin) override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from SFichier
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Sortie_Fichier_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from AbstractIO
template<typename _TYPE_ >
bool must_convert () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Attributes inherited from Sortie_Fichier_base
ofstream * ofstream_ = nullptr
Protected Attributes inherited from Sortie
std::unique_ptr< ostream > ostream_
Protected Attributes inherited from AbstractIO
bool avoid_conversion_
Detailed Description
Il y a autant de fichiers que de processus, physiquement localises sur le disque de la machine hebergeant la tache maitre de l'application Trio-U (le processus de rang 0 dans le groupe "tous") Le processus maitre recoit chaque item a ecrire de chacun des processus et dans chacun chacun des fichiers. il en est de meme pour les methodes d'inspection de l'etat d'un fichier.
Constructor & Destructor Documentation
EcrFicCollecteBin() [1/2]
EcrFicCollecteBin::EcrFicCollecteBin () inline
References Sortie::set_bin().
EcrFicCollecteBin() [2/2]
EcrFicCollecteBin::EcrFicCollecteBin (const char * name, std::ios_base::openmode mode = ios::out) inline
References EcrFicCollecte::ouvrir(), and Sortie::set_bin().
~EcrFicCollecteBin()
EcrFicCollecteBin::~EcrFicCollecteBin () inline override
References Sortie_Fichier_base::close().
Member Function Documentation
cree_instance()
Objet_U * EcrFicCollecteBin::cree_instance () static
taille_memoire()
unsigned EcrFicCollecteBin::taille_memoire () const override virtual
Reimplemented from EcrFicCollecte.
duplique()
int EcrFicCollecteBin::duplique () const override virtual
Reimplemented from EcrFicCollecte.
info()
const Type_info * EcrFicCollecteBin::info () static
get_info()
const Type_info * EcrFicCollecteBin::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from EcrFicCollecte.
self_cast() [1/2]
EcrFicCollecteBin & EcrFicCollecteBin::self_cast (Objet_U & r) static
self_cast() [2/2]
const EcrFicCollecteBin & EcrFicCollecteBin::self_cast (const Objet_U & r) static
printOn()
Sortie & EcrFicCollecteBin::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from EcrFicCollecte.
readOn()
Entree & EcrFicCollecteBin::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from EcrFicCollecte.
Member Data Documentation
info_obj
const Type_info EcrFicCollecteBin::info_obj static