TrioCFD: Source_Transport_K_Eps_Realisable_aniso_therm_concen_VEF_Face Class Reference
Source_Transport_K_Eps_Realisable_aniso_therm_concen_VEF_Face Class Reference
#include <Source_Transport_K_Eps_Realisable_aniso_therm_concen_VEF_Face.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Source_Transport_K_Eps_Realisable_VEF_Face
const Type_info * get_info () const override
void mettre_a_jour (double temps) override
const Type_info * get_info () const override
const Type_info * get_info () const override
void mettre_a_jour (double temps) override
Public Member Functions inherited from Source_base
virtual int a_pour_Champ_Fonc (const Motcle &mot, TRUST_Ref< Champ_base * > &ch_ref) const
virtual void associer_champ_rho (const Champ_base &champ_rho)
virtual void completer ()
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
virtual void resetTime (double t)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Source_Transport_K_Eps_Realisable_VEF_Face
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Calcul_Production_K_VEF
DoubleTab & calculer_terme_production_K (const Domaine_VEF &, const Domaine_Cl_VEF &, DoubleTab &, const DoubleTab &, const DoubleTab &, const DoubleTab &, const int &interpol_visco, const double &limiteur) const
double get_turbulent_viscosity (const DoubleTab &visco_turb, const DoubleVect &volumes, const int type_interpo, const int poly1, const int poly2, const double limiteur) const
void loop_for_internal_or_periodic_faces (DoubleTab &prodK, const DoubleTab &gradient_elem, const DoubleTab &visco_turb, const DoubleVect &volumes, const IntTab &face_voisins, const int nfaceinit, const int nfaceend, const int interpol_visco, const double limiteur) const
void loop_for_non_periodic_boundaries (DoubleTab &prodK, const DoubleTab &gradient_elem, const DoubleTab &visco_turb, const DoubleVect &volumes, const IntTab &face_voisins, const int nfaceinit, const int nfaceend, const int interpol_visco, const double limiteur) const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
~Source_Transport_K_Eps_Realisable_aniso_therm_concen_VEF_Face()
Source_Transport_K_Eps_Realisable_aniso_therm_concen_VEF_Face::~Source_Transport_K_Eps_Realisable_aniso_therm_concen_VEF_Face ()
Source_Transport_K_Eps_Realisable_aniso_therm_concen_VEF_Face()
Source_Transport_K_Eps_Realisable_aniso_therm_concen_VEF_Face::Source_Transport_K_Eps_Realisable_aniso_therm_concen_VEF_Face (double cte2 = C2__, double cte3 = C3_R__) inline
References Source_Transport_proto::C3.
Member Function Documentation
cree_instance()
Objet_U * Source_Transport_K_Eps_Realisable_aniso_therm_concen_VEF_Face::cree_instance () static
taille_memoire()
unsigned Source_Transport_K_Eps_Realisable_aniso_therm_concen_VEF_Face::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Source_Transport_K_Eps_Realisable_aniso_therm_concen_VEF_Face::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Source_Transport_K_Eps_Realisable_aniso_therm_concen_VEF_Face::info () static
get_info()
const Type_info * Source_Transport_K_Eps_Realisable_aniso_therm_concen_VEF_Face::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Source_Transport_Realisable_VEF_Face_base.
self_cast() [1/2]
Source_Transport_K_Eps_Realisable_aniso_therm_concen_VEF_Face & Source_Transport_K_Eps_Realisable_aniso_therm_concen_VEF_Face::self_cast (Objet_U & r) static
self_cast() [2/2]
const Source_Transport_K_Eps_Realisable_aniso_therm_concen_VEF_Face & Source_Transport_K_Eps_Realisable_aniso_therm_concen_VEF_Face::self_cast (const Objet_U & r) static
printOn()
Sortie & Source_Transport_K_Eps_Realisable_aniso_therm_concen_VEF_Face::printOn (Sortie & os) const override protected virtual
DOES NOTHING - to override in derived classes.
Imprime la source sur un flot de sortie.
Parameters
(Sortie& os) le flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Source_Transport_Realisable_VEF_Face_base.
References Objet_U::que_suis_je().
readOn()
Entree & Source_Transport_K_Eps_Realisable_aniso_therm_concen_VEF_Face::readOn (Entree & is) override protected virtual
DOES NOTHING - to override in derived classes.
Lecture d'un terme source sur un flot d'entree.
Parameters
(Entree& is) le flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Source_Transport_Realisable_VEF_Face_base.
References Objet_U::que_suis_je(), and Source_Transport_proto::readOn_anisotherme_concen_real().
associer_pb()
void Source_Transport_K_Eps_Realisable_aniso_therm_concen_VEF_Face::associer_pb (const Probleme_base & pb) override virtual
Reimplemented from Source_Transport_VEF_Face_base.
References Source_Transport_K_Eps_Realisable_VEF_Face::associer_pb(), Source_Transport_proto::associer_pb_anisotherme_concen(), Objet_U::que_suis_je(), and Source_Transport_proto::verifier_milieu_anisotherme_concen().
ajouter()
DoubleTab & Source_Transport_K_Eps_Realisable_aniso_therm_concen_VEF_Face::ajouter (DoubleTab & resu) const override virtual
Implements Source_Transport_VEF_Face_base.
References Source_Transport_K_Eps_Realisable_VEF_Face::ajouter(), and Source_Transport_VEF_Face_base::ajouter_anisotherme_concen().
Member Data Documentation
info_obj
const Type_info Source_Transport_K_Eps_Realisable_aniso_therm_concen_VEF_Face::info_obj static