TrioCFD: Cond_Lim_rayo_semi_transp Class Reference
Cond_Lim_rayo_semi_transp Class Reference abstract
#include <Cond_Lim_rayo_semi_transp.h>
Public Member Functions
virtual void associer_modele (const Modele_rayo_semi_transp &)
Modele_rayo_semi_transp & modele ()
const Modele_rayo_semi_transp & modele () const
Detailed Description
See also
Ce n'est pas une classe de l'arbre TRUST a elle seule., Cette classe est faite etre une classe mere d'une classe, qui heritera par ailleurs d'Objet_U
Constructor & Destructor Documentation
~Cond_Lim_rayo_semi_transp()
Cond_Lim_rayo_semi_transp::~Cond_Lim_rayo_semi_transp () inline protected virtual
Member Function Documentation
associer_modele()
void Cond_Lim_rayo_semi_transp::associer_modele (const Modele_rayo_semi_transp & un_modele) virtual
Associe une equation a l'objet.
Affecte le membre Cond_Lim_rayo_semi_transp::mon_modele avec l'objet passe en parametre.
Parameters
(Modele_rayo_semi_transp& modele) le modele auquel on veut s'associer
Reimplemented in Temperature_imposee_paroi_rayo_semi_transp.
References mon_modele.
Referenced by Temperature_imposee_paroi_rayo_semi_transp::associer_modele(), and Modele_rayo_semi_transp::preparer_calcul().
modele() [1/2]
const Modele_rayo_semi_transp & Cond_Lim_rayo_semi_transp::modele () const inline
Renvoie la reference sur le modele pointe par Cond_Lim_rayo_semi_transp::mon_modele.
(version const)
Returns
(Equation_base&) le modele associe a l'objet
Exceptions
pas de modele associe
References mon_modele, TRUST_Ref< _CLASSE_ >::non_nul(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Neumann_paroi_rayo_semi_transp_VDF::calculer_temperature_bord(), Echange_contact_rayo_semi_transp_VDF::calculer_Teta_equiv(), Echange_contact_rayo_semi_transp_VDF::calculer_Teta_paroi(), Neumann_paroi_rayo_semi_transp_VDF::flux_impose(), Neumann_paroi_rayo_semi_transp_VEF::flux_impose(), and recherche_emissivite_et_A().
modele() [2/2]
Modele_rayo_semi_transp & Cond_Lim_rayo_semi_transp::modele () inline
Renvoie la reference sur le modele pointe par Cond_Lim_rayo_semi_transp::mon_modele.
Returns
(Equation_base&) le modele associe a l'objet
Exceptions
pas de modele associe
References mon_modele, TRUST_Ref< _CLASSE_ >::non_nul(), and TRUST_Ref< _CLASSE_ >::valeur().
recherche_emissivite_et_A()
void Cond_Lim_rayo_semi_transp::recherche_emissivite_et_A () virtual
References Flux_radiatif_base::A(), A_, Champ_front_base::associer_fr_dis_base(), Equation_base::domaine_Cl_dis(), Flux_radiatif_base::emissivite(), emissivite_, Modele_rayo_semi_transp::eq_rayo(), Process::exit(), Cond_lim_base::frontiere_dis(), la_cl(), Frontiere_dis_base::le_nom(), Objet_U_ptr::le_nom(), Domaine_Cl_dis_base::les_conditions_limites(), modele(), TRUST_Vector< _CLASSE_ >::size(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by Modele_rayo_semi_transp::preparer_calcul().
emissivite() [1/2]
Champ_front_base & Cond_Lim_rayo_semi_transp::emissivite () inline
References emissivite_.
emissivite() [2/2]
const Champ_front_base & Cond_Lim_rayo_semi_transp::emissivite () const inline
References emissivite_.
A() [1/2]
double & Cond_Lim_rayo_semi_transp::A () inline
References A_.
A() [2/2]
const double & Cond_Lim_rayo_semi_transp::A () const inline
References A_.
la_cl()
virtual const Cond_lim_base & Cond_Lim_rayo_semi_transp::la_cl () const pure virtual
Implemented in Frontiere_ouverte_rayo_semi_transp, Frontiere_ouverte_temperature_imposee_rayo_semi_transp, Echange_contact_rayo_semi_transp_VDF, Echange_externe_impose_rayo_semi_transp, Echange_global_impose_rayo_semi_transp, Neumann_paroi_rayo_semi_transp_VDF, Neumann_paroi_rayo_semi_transp_VEF, and Temperature_imposee_paroi_rayo_semi_transp.
Referenced by recherche_emissivite_et_A().
Member Data Documentation
mon_modele
TRUST_Ref< Modele_rayo_semi_transp *> Cond_Lim_rayo_semi_transp::mon_modele protected
Referenced by associer_modele(), and modele().
emissivite_
TRUST_Deriv< Champ_front_base > Cond_Lim_rayo_semi_transp::emissivite_ protected
Referenced by emissivite(), and recherche_emissivite_et_A().
A_
double Cond_Lim_rayo_semi_transp::A_ protected
Referenced by A(), and recherche_emissivite_et_A().