TrioCFD: Raffiner_Simplexes_32_64< _SIZE_ > Class Template Reference
Raffiner_Simplexes_32_64< _SIZE_ > Class Template Reference
#include <Raffiner_Simplexes.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Interprete_geometrique_base_32_64< _SIZE_ >
const Type_info * get_info () const override
void mettre_a_jour_sous_domaine (Domaine_t &domaine, int_t &elem, int_t num_premier_elem, int_t nb_elem) const
Public Member Functions inherited from Interprete
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Interprete
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Interprete
static Objet_U & objet (const Nom &)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Member Typedef Documentation
int_t
template<typename _SIZE_ > using Raffiner_Simplexes_32_64< _SIZE_ >::int_t = _SIZE_
Domaine_t
template<typename _SIZE_ > using Raffiner_Simplexes_32_64< _SIZE_ >::Domaine_t = Domaine_32_64<_SIZE_>
Constructor & Destructor Documentation
Raffiner_Simplexes_32_64()
template<typename _T_ > Raffiner_Simplexes_32_64< _T_ >::Raffiner_Simplexes_32_64
~Raffiner_Simplexes_32_64()
template<typename _T_ > Raffiner_Simplexes_32_64< _T_ >::~Raffiner_Simplexes_32_64
Member Function Documentation
cree_instance()
template<typename _T_ > Objet_U * Raffiner_Simplexes_32_64< _T_ >::cree_instance static
taille_memoire()
template<typename _T_ > unsigned Raffiner_Simplexes_32_64< _T_ >::taille_memoire override virtual
Implements Objet_U.
duplique()
template<typename _T_ > int Raffiner_Simplexes_32_64< _T_ >::duplique override virtual
Implements Objet_U.
info()
template<typename _T_ > const Type_info * Raffiner_Simplexes_32_64< _T_ >::info static
get_info()
template<typename _T_ > const Type_info * Raffiner_Simplexes_32_64< _T_ >::get_info override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Interprete_geometrique_base_32_64< _SIZE_ >.
self_cast() [1/2]
template<typename _T_ > Raffiner_Simplexes_32_64< _T_ > & Raffiner_Simplexes_32_64< _T_ >::self_cast (Objet_U & r) static
self_cast() [2/2]
template<typename _T_ > const Raffiner_Simplexes_32_64< _T_ > & Raffiner_Simplexes_32_64< _T_ >::self_cast (const Objet_U & r) static
printOn()
template<typename _SIZE_ > Sortie & Raffiner_Simplexes_32_64< _SIZE_ >::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Interprete_geometrique_base_32_64< _SIZE_ >.
References Interprete::printOn().
Referenced by Raffiner_isotrope_parallele::printOn().
readOn()
template<typename _SIZE_ > Entree & Raffiner_Simplexes_32_64< _SIZE_ >::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Interprete_geometrique_base_32_64< _SIZE_ >.
References Interprete::readOn().
Referenced by Raffiner_isotrope_parallele::readOn().
interpreter_()
template<typename _SIZE_ > Entree & Raffiner_Simplexes_32_64< _SIZE_ >::interpreter_ (Entree & is) override virtual
Implements Interprete_geometrique_base_32_64< _SIZE_ >.
References Scatter::init_sequential_domain(), and Scatter::uninit_sequential_domain().
refine_domain()
template<typename _SIZE_ > void Raffiner_Simplexes_32_64< _SIZE_ >::refine_domain (const Domaine_t & src, Domaine_t & dest) protected
References Domaine_32_64< _SIZE_ >::bords_int(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Domaine_32_64< _SIZE_ >::faces_bord(), Domaine_32_64< _SIZE_ >::faces_joint(), Domaine_32_64< _SIZE_ >::faces_raccord(), Domaine_32_64< _SIZE_ >::groupes_faces(), Domaine_32_64< _SIZE_ >::les_elems(), Domaine_32_64< _SIZE_ >::les_sommets(), Domaine_32_64< _SIZE_ >::nb_som(), Domaine_32_64< _SIZE_ >::nb_ss_domaines(), Objet_U::que_suis_je(), TRUST_List< _CLASSE_ >::size(), Domaine_32_64< _SIZE_ >::ss_domaine(), and Domaine_32_64< _SIZE_ >::type_elem().
Referenced by Raffiner_isotrope_parallele::interpreter().
info_obj() [1/2]
const Type_info Raffiner_Simplexes_32_64< int >::info_obj ("Raffiner_Simplexes" , Raffiner_Simplexes_32_64< int >::cree_instance , 1 , Raffiner_Simplexes_32_64bases< int >)
info_obj() [2/2]
const Type_info Raffiner_Simplexes_32_64< trustIdType >::info_obj ("Raffiner_Simplexes" "_64" , Raffiner_Simplexes_32_64< trustIdType >::cree_instance , 1 , Raffiner_Simplexes_32_64bases< trustIdType >)
Member Data Documentation
info_obj
template<typename _SIZE_ > const Type_info Raffiner_Simplexes_32_64< _SIZE_ >::info_obj static