TrioCFD: Masse_PolyMAC_Elem Class Reference
Masse_PolyMAC_Elem Class Reference
#include <Masse_PolyMAC_Elem.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Solveur_Masse_base
virtual DoubleTab & appliquer (DoubleTab &) const
virtual void assembler ()
const Type_info * get_info () const override
virtual void mettre_a_jour (double temps)
virtual void resetTime (double temps)
void set_name_of_coefficient_temporel (const Nom &)
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Masse_PolyMAC_Elem()
Masse_PolyMAC_Elem::Masse_PolyMAC_Elem ()
~Masse_PolyMAC_Elem()
Masse_PolyMAC_Elem::~Masse_PolyMAC_Elem ()
Member Function Documentation
cree_instance()
Objet_U * Masse_PolyMAC_Elem::cree_instance () static
taille_memoire()
unsigned Masse_PolyMAC_Elem::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Masse_PolyMAC_Elem::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Masse_PolyMAC_Elem::info () static
get_info()
const Type_info * Masse_PolyMAC_Elem::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Masse_PolyMAC_base.
self_cast() [1/2]
Masse_PolyMAC_Elem & Masse_PolyMAC_Elem::self_cast (Objet_U & r) static
self_cast() [2/2]
const Masse_PolyMAC_Elem & Masse_PolyMAC_Elem::self_cast (const Objet_U & r) static
printOn()
Sortie & Masse_PolyMAC_Elem::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Masse_PolyMAC_base.
References Objet_U::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Masse_PolyMAC_Elem::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Masse_PolyMAC_base.
dimensionner()
void Masse_PolyMAC_Elem::dimensionner (Matrice_Morse & matrix) const override virtual
Reimplemented from Solveur_Masse_base.
References Matrix_tools::allocate_morse_matrix(), TRUSTTab< _TYPE_, _SIZE_ >::append_line(), MorEqn::equation(), Champ_Inc_P0_base::fcl(), Masse_PolyMAC_base::le_dom_PolyMAC, TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Matrice_Morse::nb_lignes(), Masse_PolyMAC_base::no_diff_, TRUST_Ref< _CLASSE_ >::valeur(), and Champ_Inc_base::valeurs().
ajouter_masse() [1/2]
DoubleTab & Masse_PolyMAC_Elem::ajouter_masse (double dt, DoubleTab & x, const DoubleTab & y, int penalisation = 1) const override virtual
Reimplemented from Solveur_Masse_base.
References Masse_PolyMAC_base::appliquer_coef(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), MorEqn::equation(), Champ_Inc_P0_base::fcl(), Solveur_Masse_base::has_coefficient_temporel_, Masse_PolyMAC_base::le_dom_Cl_PolyMAC, Masse_PolyMAC_base::le_dom_PolyMAC, TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Equation_base::milieu(), Milieu_base::porosite_elem(), and TRUST_Ref< _CLASSE_ >::valeur().
ajouter_masse() [2/2]
Matrice_Base & Masse_PolyMAC_Elem::ajouter_masse (double dt, Matrice_Base & matrice, int penalisation = 1) const override virtual
Reimplemented from Solveur_Masse_base.
References Masse_PolyMAC_base::appliquer_coef(), MorEqn::equation(), Champ_Inc_P0_base::fcl(), Solveur_Masse_base::has_coefficient_temporel_, Masse_PolyMAC_base::le_dom_PolyMAC, TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Equation_base::milieu(), Matrice_Morse::nb_lignes(), Masse_PolyMAC_base::no_diff_, Milieu_base::porosite_elem(), TRUST_Ref< _CLASSE_ >::valeur(), and Champ_Inc_base::valeurs().
appliquer_impl()
DoubleTab & Masse_PolyMAC_Elem::appliquer_impl (DoubleTab & sm) const override virtual
Implements Solveur_Masse_base.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), MorEqn::equation(), Process::exit(), Masse_PolyMAC_base::le_dom_PolyMAC, TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Equation_base::milieu(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Domaine_dis_base::nb_elem(), Milieu_base::porosite_elem(), TRUST_Ref< _CLASSE_ >::valeur(), and Domaine_VF::volumes().
Member Data Documentation
info_obj
const Type_info Masse_PolyMAC_Elem::info_obj static