TrioCFD: KerasModel Class Reference
KerasModel Class Reference
#include <keras_model.h>
Member Enumeration Documentation
LayerType
enum KerasModel::LayerType
Enumerator
kDense
kConvolution2d
kFlatten
kElu
kActivation
kMaxPooling2D
kLSTM
kEmbedding
Constructor & Destructor Documentation
KerasModel()
KerasModel::KerasModel () inline
~KerasModel()
virtual KerasModel::~KerasModel () inline virtual
Member Function Documentation
LoadModel()
bool KerasModel::LoadModel (const std::string & filename) virtual
References Process::exit(), kActivation, kConvolution2d, kDense, kElu, kEmbedding, kFlatten, kLSTM, kMaxPooling2D, and KerasLayer::LoadLayer().
Referenced by TBNN::TBNN().
Apply()
bool KerasModel::Apply (Tensor * in, Tensor * out) virtual
References Apply().
Referenced by Apply().