TrioCFD: Collision_Model_FT_sphere Class Reference
Collision_Model_FT_sphere Class Reference
#include <Collision_Model_FT_sphere.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Collision_Model_FT_base
const Type_info * get_info () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
int reprendre (Entree &is) override
int sauvegarder (Sortie &os) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
Description: This class enables to compute solid-solid interactions for fpi module under the framework of soft-sphere collision model. Under this framework, multiple collisions can occurs at the same time (ie a particle can collide with 2 or more particles). The collision is spread out on multiple time steps. A slight overlap (less than the mesh grid size) occurs during the process.
Constructor & Destructor Documentation
~Collision_Model_FT_sphere()
Collision_Model_FT_sphere::~Collision_Model_FT_sphere ()
Collision_Model_FT_sphere()
Collision_Model_FT_sphere::Collision_Model_FT_sphere ()
Member Function Documentation
cree_instance()
Objet_U * Collision_Model_FT_sphere::cree_instance () static
taille_memoire()
unsigned Collision_Model_FT_sphere::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Collision_Model_FT_sphere::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Collision_Model_FT_sphere::info () static
get_info()
const Type_info * Collision_Model_FT_sphere::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Collision_Model_FT_base.
self_cast() [1/2]
Collision_Model_FT_sphere & Collision_Model_FT_sphere::self_cast (Objet_U & r) static
self_cast() [2/2]
const Collision_Model_FT_sphere & Collision_Model_FT_sphere::self_cast (const Objet_U & r) static
printOn()
Sortie & Collision_Model_FT_sphere::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Collision_Model_FT_base.
References Process::exit().
readOn()
Entree & Collision_Model_FT_sphere::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Collision_Model_FT_base.
References Collision_Model_FT_base::readOn().
compute_lagrangian_contact_forces()
void Collision_Model_FT_sphere::compute_lagrangian_contact_forces (const Fluide_Diphasique & two_phase_fluid, const DoubleTab & particles_position, const DoubleTab & particles_velocity, const double & deltat_simu) override virtual
Implements Collision_Model_FT_base.
References Collision_Model_FT_base::add_collision(), Process::check_int_overflow(), Collision_Model_FT_base::collision_number_, Collision_Model_FT_base::compute_contact_force(), Collision_Model_FT_base::compute_dX_dU(), Collision_Model_FT_base::compute_ewet_legendre(), Collision_Model_FT_base::detection_method_, Objet_U::dimension, Collision_Model_FT_base::e_eff_, Collision_Model_FT_base::F_now_, Collision_Model_FT_base::F_old_, Fluide_Diphasique::fluide_phase(), Fluide_Diphasique::get_id_fluid_phase(), Collision_Model_FT_base::get_ind_start_particles_j(), Collision_Model_FT_base::get_nb_particles_j(), Collision_Model_FT_base::get_particle_i(), Collision_Model_FT_base::get_particle_j(), Collision_Model_FT_base::lagrangian_contact_forces_, Collision_Model_FT_base::LC_VERLET, Process::mp_sum(), Collision_Model_FT_base::nb_particles_tot_, Collision_Model_FT_base::nb_real_particles_, and Collision_Model_FT_base::particles_collision_number_.
discretize_contact_forces_eulerian_field()
void Collision_Model_FT_sphere::discretize_contact_forces_eulerian_field (const DoubleTab & volumic_phase_indicator_function, const Domaine_VF & domain_vf, const IntTab & particles_eulerian_id_number, DoubleTab & contact_force_source_term) override virtual
Implements Collision_Model_FT_base.
References Domaine_VF::face_voisins(), Collision_Model_FT_base::lagrangian_contact_forces_, Domaine_VF::orientation(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and Domaine_VF::volumes_entrelaces().
Member Data Documentation
info_obj
const Type_info Collision_Model_FT_sphere::info_obj static