TrioCFD: Iterateur_PolyMAC_base Class Reference
Iterateur_PolyMAC_base Class Reference abstract
#include <Iterateur_PolyMAC_base.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Iterateur_PolyMAC_base()
Iterateur_PolyMAC_base::Iterateur_PolyMAC_base ()
~Iterateur_PolyMAC_base()
Iterateur_PolyMAC_base::~Iterateur_PolyMAC_base () override
Member Function Documentation
info()
const Type_info * Iterateur_PolyMAC_base::info () static
get_info()
const Type_info * Iterateur_PolyMAC_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
Iterateur_PolyMAC_base & Iterateur_PolyMAC_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Iterateur_PolyMAC_base & Iterateur_PolyMAC_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Iterateur_PolyMAC_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
References Objet_U::que_suis_je().
readOn()
Entree & Iterateur_PolyMAC_base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
associer() [1/2]
void Iterateur_PolyMAC_base::associer (const Domaine_PolyMAC & domaine_vdf, const Domaine_Cl_PolyMAC & domaine_cl_vdf, const Operateur_base & op)
References la_zcl, le_domaine, and op_base.
Referenced by Op_Conv_Amont_PolyMAC_Elem::associer(), Op_Conv_Centre_PolyMAC_Elem::associer(), and associer().
associer() [2/2]
void Iterateur_PolyMAC_base::associer (const Domaine_dis_base & z, const Domaine_Cl_dis_base & zcl, const Operateur_base & op)
References associer().
associer_domaine_cl_dis()
void Iterateur_PolyMAC_base::associer_domaine_cl_dis (const Domaine_Cl_dis_base & zcl)
References la_zcl.
Referenced by Op_Conv_PolyMAC_iterateur_base::associer_domaine_cl_dis().
type_cl()
Type_Cl_PolyMAC Iterateur_PolyMAC_base::type_cl (const Cond_lim & la_cl) const inline
References TRUST_Deriv< _CLASSE_ >::valeur().
ajouter()
virtual DoubleTab & Iterateur_PolyMAC_base::ajouter (const DoubleTab & , DoubleTab &) const pure virtual
Implemented in Iterateur_PolyMAC_Elem< _TYPE_ >.
Referenced by Op_Conv_PolyMAC_iterateur_base::ajouter().
calculer_flux_bord()
void Iterateur_PolyMAC_base::calculer_flux_bord (const DoubleTab & inco) const virtual
Reimplemented in Iterateur_PolyMAC_Elem< _TYPE_ >.
References Process::exit(), and Objet_U::que_suis_je().
calculer()
virtual DoubleTab & Iterateur_PolyMAC_base::calculer (const DoubleTab & , DoubleTab &) const pure virtual
Implemented in Iterateur_PolyMAC_Elem< _TYPE_ >.
Referenced by Op_Conv_PolyMAC_iterateur_base::calculer().
contribuer_au_second_membre()
virtual void Iterateur_PolyMAC_base::contribuer_au_second_membre (DoubleTab &) const pure virtual
Implemented in Iterateur_PolyMAC_Elem< _TYPE_ >.
Referenced by Op_Conv_PolyMAC_iterateur_base::contribuer_au_second_membre().
ajouter_contribution()
virtual void Iterateur_PolyMAC_base::ajouter_contribution (const DoubleTab & , Matrice_Morse &) const pure virtual
Implemented in Iterateur_PolyMAC_Elem< _TYPE_ >.
Referenced by Op_Conv_PolyMAC_iterateur_base::contribuer_a_avec().
ajouter_contribution_vitesse()
virtual void Iterateur_PolyMAC_base::ajouter_contribution_vitesse (const DoubleTab & , Matrice_Morse &) const pure virtual
Implemented in Iterateur_PolyMAC_Elem< _TYPE_ >.
Referenced by Op_Conv_PolyMAC_iterateur_base::contribuer_bloc_vitesse().
evaluateur() [1/2]
virtual Evaluateur_PolyMAC & Iterateur_PolyMAC_base::evaluateur () pure virtual
Implemented in Iterateur_PolyMAC_Elem< _TYPE_ >.
Referenced by Op_Conv_Amont_PolyMAC_Elem::associer(), Op_Conv_Centre_PolyMAC_Elem::associer(), Op_Conv_Amont_PolyMAC_Elem::associer_vitesse(), Op_Conv_Centre_PolyMAC_Elem::associer_vitesse(), Op_Conv_Amont_PolyMAC_Elem::vitesse(), and Op_Conv_Centre_PolyMAC_Elem::vitesse().
evaluateur() [2/2]
virtual const Evaluateur_PolyMAC & Iterateur_PolyMAC_base::evaluateur () const pure virtual
Implemented in Iterateur_PolyMAC_Elem< _TYPE_ >.
domaine()
const Domaine_PolyMAC & Iterateur_PolyMAC_base::domaine () const inline
References le_domaine, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Op_Conv_PolyMAC_iterateur_base::calculer_dt_stab(), Op_Conv_PolyMAC_iterateur_base::calculer_pour_post(), Op_Conv_Amont_PolyMAC_Elem::dimensionner(), Op_Conv_Centre_PolyMAC_Elem::dimensionner(), Op_Conv_Amont_PolyMAC_Elem::dimensionner_bloc_vitesse(), Op_Conv_Centre_PolyMAC_Elem::dimensionner_bloc_vitesse(), Op_Conv_Amont_PolyMAC_Elem::modifier_pour_Cl(), and Op_Conv_Centre_PolyMAC_Elem::modifier_pour_Cl().
domaine_Cl()
const Domaine_Cl_PolyMAC & Iterateur_PolyMAC_base::domaine_Cl () const inline
References la_zcl, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Op_Conv_PolyMAC_iterateur_base::calculer_dt_stab(), Op_Conv_PolyMAC_iterateur_base::calculer_pour_post(), Op_Conv_Amont_PolyMAC_Elem::dimensionner(), Op_Conv_Centre_PolyMAC_Elem::dimensionner(), Op_Conv_Amont_PolyMAC_Elem::dimensionner_bloc_vitesse(), Op_Conv_Centre_PolyMAC_Elem::dimensionner_bloc_vitesse(), Op_Conv_Amont_PolyMAC_Elem::modifier_pour_Cl(), and Op_Conv_Centre_PolyMAC_Elem::modifier_pour_Cl().
completer_()
virtual void Iterateur_PolyMAC_base::completer_ () pure virtual
Implemented in Iterateur_PolyMAC_Elem< _TYPE_ >.
Referenced by Op_Conv_PolyMAC_iterateur_base::completer().
impr()
virtual int Iterateur_PolyMAC_base::impr (Sortie & os) const pure virtual
Implemented in Iterateur_PolyMAC_Elem< _TYPE_ >.
Referenced by Op_Conv_PolyMAC_iterateur_base::impr().
Member Data Documentation
info_obj
const Type_info Iterateur_PolyMAC_base::info_obj static
le_domaine
TRUST_Ref< Domaine_PolyMAC *> Iterateur_PolyMAC_base::le_domaine protected
Referenced by associer(), and domaine().
la_zcl
TRUST_Ref< Domaine_Cl_PolyMAC *> Iterateur_PolyMAC_base::la_zcl protected
Referenced by associer(), associer_domaine_cl_dis(), and domaine_Cl().
op_base
TRUST_Ref< Operateur_base *> Iterateur_PolyMAC_base::op_base protected
Referenced by associer().