TrioCFD: EcrFicPartage Class Reference
EcrFicPartage Class Reference
#include <EcrFicPartage.h>
Public Member Functions
const Type_info * get_info () const override
Sortie & lockfile () override
Sortie & operator<< (const char *ob) override
Sortie & operator<< (const Objet_U &ob) override
Sortie & syncfile () override
Sortie & unlockfile () override
Public Member Functions inherited from SFichier
const Type_info * get_info () const override
Public Member Functions inherited from Sortie_Fichier_base
Sortie & flush () override
const Type_info * get_info () const override
Public Member Functions inherited from Sortie
virtual Sortie & operator<< (const char *ob)
virtual Sortie & operator<< (const Objet_U &ob)
void set_bin (bool bin) override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from SFichier
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Sortie_Fichier_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from AbstractIO
template<typename _TYPE_ >
bool must_convert () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Attributes inherited from Sortie_Fichier_base
ofstream * ofstream_ = nullptr
Protected Attributes inherited from Sortie
std::unique_ptr< ostream > ostream_
Protected Attributes inherited from AbstractIO
bool avoid_conversion_
Constructor & Destructor Documentation
EcrFicPartage() [1/2]
EcrFicPartage::EcrFicPartage ()
References set_bin().
EcrFicPartage() [2/2]
EcrFicPartage::EcrFicPartage (const char * name, std::ios_base::openmode mode = ios::out)
Ouvre le fichier avec les parametres mode et prot donnes Ces parametres sont les parametres de la methode open standard.
References AbstractIO::is_64b(), ouvrir(), AbstractIO::set_64b(), and set_bin().
~EcrFicPartage()
EcrFicPartage::~EcrFicPartage () override
ferme le fichier
References close().
Member Function Documentation
cree_instance()
Objet_U * EcrFicPartage::cree_instance () static
taille_memoire()
unsigned EcrFicPartage::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in EcrFicPartageBin.
duplique()
int EcrFicPartage::duplique () const override virtual
Implements Objet_U.
Reimplemented in EcrFicPartageBin.
info()
const Type_info * EcrFicPartage::info () static
get_info()
const Type_info * EcrFicPartage::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
Reimplemented in EcrFicPartageBin.
self_cast() [1/2]
EcrFicPartage & EcrFicPartage::self_cast (Objet_U & r) static
self_cast() [2/2]
const EcrFicPartage & EcrFicPartage::self_cast (const Objet_U & r) static
printOn()
Sortie & EcrFicPartage::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
Reimplemented in EcrFicPartageBin.
readOn()
Entree & EcrFicPartage::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
Reimplemented in EcrFicPartageBin.
ouvrir()
int EcrFicPartage::ouvrir (const char * name, std::ios_base::openmode mode = ios::out) override virtual
Ouvre le fichier avec les parametres mode et prot donnes Ces parametres sont les parametres de la methode open standard.
Reimplemented from Sortie_Fichier_base.
References Process::barrier(), Process::je_suis_maitre(), OBuffer::new_buffer(), nom_fic_, Sortie_Fichier_base::ouvrir(), and syncfile().
Referenced by IJK_Interfaces::dumplata_ft_mesh(), EcrFicPartage(), EcrFicPartageBin::EcrFicPartageBin(), Format_Post_Lml::ecrire_champ_lml(), Format_Post_XYZ::ecrire_champ_xyz(), Format_Post_Lml::ecrire_domaine_lml(), Format_Post_Lml::ecrire_entete_lml(), Format_Post_Lml::ecrire_item_int_lml(), Format_Post_Lml::ecrire_temps_lml(), Format_Post_Lml::finir_lml(), Echange_contact_VDF_FT_Disc_solid::mettre_a_jour(), Turbulence_paroi_base::ouvrir_fichier_partage(), Turbulence_paroi_scal_base::ouvrir_fichier_partage(), and Operateur_base::ouvrir_fichier_partage().
close()
void EcrFicPartage::close ()
References Process::barrier(), Sortie_Fichier_base::close(), Process::exit(), Process::je_suis_maitre(), OBuffer::len(), Process::me(), Process::mp_sum(), nom_fic_, OBuffer::str(), and syncfile().
Referenced by Traitement_particulier_NS_chmoy_faceperio_VEF::calcul_chmoy_faceperio(), IJK_Interfaces::dumplata_ft_mesh(), Traitement_particulier_NS_chmoy_faceperio_VEF::init_calcul_stats(), and ~EcrFicPartage().
lockfile()
Sortie & EcrFicPartage::lockfile () override virtual
Permet au processus appelant de bloquer en attente de la ressource commune a tous les processus qui est le fichier partage.
Si le processus appelant cette methode n'est pas le premier, il atend du processus precedent l'endroit ou il doit se positionner dans le fichier pour effectuer sa prochaine ecriture. Cette methode est systematiquement appelee avant toute nouvelle ecriture dans le fichier.
Returns
(Sortie&) *this
Reimplemented from Sortie.
Referenced by Format_Post_Lml::ecrire_champ_lml(), Format_Post_Lml::ecrire_domaine_lml(), Format_Post_Lml::ecrire_item_int_lml(), and Face_Rayonnante::ecrire_temperature_bord().
unlockfile()
Sortie & EcrFicPartage::unlockfile () override virtual
Permet de debloquer la ressource critique pour leprocessus suivant.
Le processus appelant, sauf si c'est le premier processus du groupe, envoie sa position courante au precessus suivant dans le groupe. Cette methode est a appeler apres chaque ecriture dans le fichier.
Returns
(Sortie&) *this
Reimplemented from Sortie.
Referenced by Format_Post_Lml::ecrire_champ_lml(), Format_Post_XYZ::ecrire_champ_xyz(), Format_Post_Lml::ecrire_domaine_lml(), and Format_Post_Lml::ecrire_item_int_lml().
syncfile()
Sortie & EcrFicPartage::syncfile () override virtual
Provoque l'ecriture sur disque des donnees accumulees sur les differents processeurs depuis le dernier appel a syncfile().
Les donnees sont ecrites dans l'ordre croissant des processeurs. Cette fonction doit etre appelee le meme nombre de fois sur tous les processeurs !
Exemple: processeur 0: processeur 1: file << "pe0 : 1" << finl; file << "pe1 : 1" << finl; file << "pe0 : 2" << finl; file << "pe1 : 2" << finl; file.syncfile(); file.syncfile(); file << "pe0 : 3" << finl; file << "pe1 : 3" << finl; file << "pe0 : 4" << finl; file.syncfile(); file.syncfile(); file << "pe0 : end" << finl; // le processeur 1 n'ecrit pas de donnees file.syncfile(); file.syncfile();
Contenu du fichier : pe0 : 1 pe0 : 2 pe1 : 1 pe1 : 2 pe0 : 3 pe0 : 4 pe1 : 3 pe0 : end
Reimplemented from Sortie.
References Statistiques::begin_count(), AbstractIO::bin_, PE_Groups::current_group(), Statistiques::end_count(), Sortie::get_ostream(), Process::je_suis_maitre(), OBuffer::len(), Process::me(), OBuffer::new_buffer(), Process::nproc(), OBuffer::put_null_char(), Comm_Group::recv(), Comm_Group::send(), and OBuffer::str().
Referenced by Traitement_particulier_NS_chmoy_faceperio_VEF::calcul_chmoy_faceperio(), close(), Statistiques::dump(), IJK_Interfaces::dumplata_ft_mesh(), Format_Post_Lml::ecrire_champ_lml(), Format_Post_XYZ::ecrire_champ_xyz(), Format_Post_Lml::ecrire_domaine_lml(), Format_Post_Lml::ecrire_entete_lml(), Format_Post_Lml::ecrire_item_int_lml(), Format_Post_Lml::ecrire_temps_lml(), Format_Post_Lml::finir_lml(), Op_Grad_VEF_P1B_Face::impr(), Op_EF_base::impr(), Op_VEF_Face::impr(), Op_Div_EF::impr(), Op_Grad_EF::impr(), Iterateur_PolyMAC_Elem< _TYPE_ >::impr(), Op_Conv_PolyMAC_base::impr(), Op_Diff_PolyMAC_Gen_base::impr(), Op_Div_PolyMAC::impr(), Op_Grad_VDF_Face::impr(), Op_Div_VEFP1B_Elem::impr(), Loi_Paroi_Nu_Impose_VDF::imprimer_nusselt(), Loi_Paroi_Nu_Impose_VEF::imprimer_nusselt(), Paroi_scal_hyd_base_EF::imprimer_nusselt(), Paroi_scal_hyd_base_VDF::imprimer_nusselt(), Paroi_scal_hyd_base_VEF::imprimer_nusselt(), Turbulence_paroi_scal_base::imprimer_nusselt_mean_only(), Turbulence_paroi_scal_base::imprimer_premiere_ligne_nusselt(), Turbulence_paroi_base::imprimer_premiere_ligne_ustar(), Paroi_std_hyd_EF::imprimer_ustar(), Paroi_std_hyd_VDF::imprimer_ustar(), Paroi_std_hyd_VEF::imprimer_ustar(), Paroi_2couches_VDF::imprimer_ustar(), Turbulence_paroi_base::imprimer_ustar_mean_only(), Traitement_particulier_NS_chmoy_faceperio_VEF::init_calcul_stats(), Echange_contact_VDF_FT_Disc_solid::mettre_a_jour(), and ouvrir().
precision()
void EcrFicPartage::precision (int i) override virtual
Reimplemented from Sortie.
References OBuffer::precision().
Referenced by Traitement_particulier_NS_chmoy_faceperio_VEF::calcul_chmoy_faceperio(), Traitement_particulier_NS_chmoy_faceperio_VEF::init_calcul_stats(), and Operateur_base::ouvrir_fichier_partage().
get_precision()
int EcrFicPartage::get_precision () override virtual
Reimplemented from Sortie_Fichier_base.
References OBuffer::get_precision().
flush()
Sortie & EcrFicPartage::flush () override virtual
Reimplemented from Sortie.
Referenced by Format_Post_XYZ::ecrire_champ_xyz(), Format_Post_Lml::ecrire_domaine_lml(), Format_Post_Lml::ecrire_entete_lml(), Format_Post_Lml::ecrire_item_int_lml(), Format_Post_Lml::ecrire_temps_lml(), and Format_Post_Lml::finir_lml().
set_bin()
void EcrFicPartage::set_bin (bool bin) override virtual
Reimplemented from AbstractIO.
References AbstractIO::bin_, OBuffer::set_bin(), and Sortie::set_bin().
Referenced by EcrFicPartage(), and EcrFicPartageBin::EcrFicPartageBin().
set_64b()
void EcrFicPartage::set_64b (bool is64) override virtual
Reimplemented from AbstractIO.
References AbstractIO::set_64b().
Referenced by IJK_Interfaces::dumplata_ft_mesh().
operator<<() [1/11]
Sortie & EcrFicPartage::operator<< (const char * ob) override virtual
Ecriture d'une chaine de caracteres.
Attention, pour pouvoir relire correctement la chaine en mode ascii, celle-ci ne doit pas contenir de separateur (ni espace, ni retour a la ligne, ...)
Reimplemented from Sortie.
operator<<() [2/11]
Sortie & EcrFicPartage::operator<< (const Objet_U & ob) override virtual
Ecriture d'un objet ou d'une variable.
Dans cette implementation (et dans la plupart des classes derivees) on appelle simplement ob.printOn (a l'exception de Sortie_Nulle) Attention, si on veut que le flux puisse etre indifferemment ASCII ou BINAIRE, il faut inserer "<< space <<" ou "<< finl <<" pour separer les objets.
Reimplemented from Sortie.
operator<<() [3/11]
Sortie & EcrFicPartage::operator<< (const std::string & ob) override virtual
Reimplemented from Sortie.
operator<<() [4/11]
Sortie & EcrFicPartage::operator<< (const Separateur & s) override virtual
Reimplemented from Sortie.
operator<<() [5/11]
Sortie & EcrFicPartage::operator<< (const True_int ob) override virtual
Reimplemented from Sortie.
operator<<() [6/11]
Sortie & EcrFicPartage::operator<< (const unsigned ob) override virtual
Reimplemented from Sortie.
operator<<() [7/11]
Sortie & EcrFicPartage::operator<< (const long ob) override virtual
Reimplemented from Sortie.
operator<<() [8/11]
Sortie & EcrFicPartage::operator<< (const long long ob) override virtual
Reimplemented from Sortie.
operator<<() [9/11]
Sortie & EcrFicPartage::operator<< (const unsigned long ob) override virtual
Reimplemented from Sortie.
operator<<() [10/11]
Sortie & EcrFicPartage::operator<< (const float ob) override virtual
Reimplemented from Sortie.
operator<<() [11/11]
Sortie & EcrFicPartage::operator<< (const double ob) override virtual
Reimplemented from Sortie.
put() [1/6]
int EcrFicPartage::put (const unsigned * ob, std::streamsize n, std::streamsize pas) override virtual
Reimplemented from Sortie.
Referenced by IJK_Interfaces::dumplata_ft_mesh().
put() [2/6]
int EcrFicPartage::put (const True_int * ob, std::streamsize n, std::streamsize pas) override virtual
Reimplemented from Sortie.
put() [3/6]
int EcrFicPartage::put (const long * ob, std::streamsize n, std::streamsize pas) override virtual
Reimplemented from Sortie.
put() [4/6]
int EcrFicPartage::put (const long long * ob, std::streamsize n, std::streamsize pas) override virtual
Reimplemented from Sortie.
put() [5/6]
int EcrFicPartage::put (const float * ob, std::streamsize n, std::streamsize pas) override virtual
Reimplemented from Sortie.
put() [6/6]
int EcrFicPartage::put (const double * ob, std::streamsize n, std::streamsize pas) override virtual
Reimplemented from Sortie.
Member Data Documentation
info_obj
const Type_info EcrFicPartage::info_obj static
nom_fic_
Nom EcrFicPartage::nom_fic_ protected
Referenced by close(), and ouvrir().