TrioCFD: TRUST_2_PDI Class Reference
TRUST_2_PDI Class Reference
#include <TRUST_2_PDI.h>
Public Member Functions
void get_type (const Nom &name, Nom &type)
void prepareRestart (int &last_iteration, double &tinit, int resume_last_time)
void share_TRUSTTab_dimensions (const DoubleTab &tab, const Nom &name, int write)
void share_type (const Nom &name, const Nom &type)
Detailed Description
PDI needs to be initialized with a YAML file, containing all the data that we want to exchange with the outside world (see the class Ecrire_YAML for details). Note that every data that will be handled via PDI first needs to be declared in the YAML file that has been used to initialize it!
Here is how PDI works: 1) TRUST makes it known to PDI that some of our data is accessible (ie we start sharing a pointer to the data, no copy here!) 2) PDI notifies the selected plugin that the data is ready 3) The plugin works with the data and behaves just as we described it in the YAML file 4) Once the work is done, TRUST can reclaim the data (which means PDI will no longer be able to reach it) and pursue the simulation
These steps can be completed at once in a single operation or asynchronously (ie we share the data, we busy ourselves with some other stuff, then we trigger the IO operations and reclaim the data).
An example on how to use it: """""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""" int var = 5; TRUST_2_PDI::init(yaml_filename); TRUST_2_PDI pdi_interface; pdi_interface.start_sharing("pb_var", &var); // the YAML file must contain a data named pb_var pdi_interface.trigger("event"); // there has to be an event in the YAML that tells us what to do with the data pdi_interface.stop_sharing_last_variable(); // data is no more available // the last 3 instructions can be squeezed in one with the methods TRUST_2_PDI::read()/TRUST_2_PDI::write() TRUST_2_PDI::finalize(); """"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
Member Function Documentation
init()
static void TRUST_2_PDI::init (std::string IO_config) inline static
References Process::exit(), Comm_Group_MPI::get_mpi_comm(), PE_Groups::get_node_group(), Comm_Group_MPI::get_node_id(), PE_Groups::get_node_master(), Comm_Group::nproc(), and Comm_Group::rank().
Referenced by Save_Restart::sauver(), and Probleme_Couple::sauver().
finalize()
static void TRUST_2_PDI::finalize () inline static
Referenced by Save_Restart::finir(), and Champ_Fonc_reprise::readOn().
set_PDI_checkpoint()
static void TRUST_2_PDI::set_PDI_checkpoint (int c) inline static
Referenced by Transport_Interfaces_FT_Disc_interne::sauvegarder(), and Save_Restart::sauver().
set_PDI_restart()
static void TRUST_2_PDI::set_PDI_restart (int r) inline static
Referenced by Transport_Interfaces_FT_Disc_interne::reprendre().
is_PDI_initialized()
static int TRUST_2_PDI::is_PDI_initialized () inline static
Referenced by Save_Restart::finir(), Save_Restart::sauver(), and Probleme_Couple::sauver().
is_PDI_checkpoint()
static int TRUST_2_PDI::is_PDI_checkpoint () inline static
Referenced by EcritureLectureSpecial::is_ecriture_special(), Navier_Stokes_std_ALE::sauvegarder(), Maillage_FT_Disc::sauvegarder(), Remaillage_FT::sauvegarder(), Transport_Interfaces_FT_Disc::sauvegarder(), Champ_Fonc_base::sauvegarder(), Champ_Inc_base::sauvegarder(), Schema_Temps_base::sauvegarder(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::sauvegarder(), Modele_turbulence_hyd_base::sauvegarder(), Transport_Interfaces_FT_Disc_interne::sauvegarder(), Postraitement::sauvegarder(), and Convection_Diffusion_Fluide_Dilatable_Proto::Sauvegarder_WC().
is_PDI_restart()
static int TRUST_2_PDI::is_PDI_restart () inline static
Referenced by Navier_Stokes_std_ALE::reprendre(), Maillage_FT_Disc::reprendre(), Remaillage_FT::reprendre(), Transport_Interfaces_FT_Disc::reprendre(), Champ_Fonc_base::reprendre(), Champ_Inc_base::reprendre(), Equation_base::reprendre(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::reprendre(), Navier_Stokes_IBM_Turbulent::reprendre(), Navier_Stokes_std::reprendre(), Navier_Stokes_Turbulent::reprendre(), Transport_Interfaces_FT_Disc_interne::reprendre(), Champ_Generique_Statistiques_base::reprendre(), Postraitement::reprendre(), Operateurs_Statistique_tps::reprendre(), Modele_turbulence_hyd_2_eq_base::reprendre_generique(), and Convection_Diffusion_Fluide_Dilatable_Proto::Reprendre_WC().
read()
void TRUST_2_PDI::read (const std::string & name, void * data) inline
Referenced by prepareRestart(), Champ_Fonc_base::reprendre(), Champ_Inc_base::reprendre(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::reprendre(), Transport_Interfaces_FT_Disc_interne::reprendre(), Postraitement::reprendre(), and Operateurs_Statistique_tps::reprendre().
write()
void TRUST_2_PDI::write (const std::string & name, const void * data) inline
Referenced by prepareRestart(), Save_Restart::sauver(), share_TRUSTTab_dimensions(), and share_type().
TRUST_start_sharing()
void TRUST_2_PDI::TRUST_start_sharing (const std::string & name, const void * data) inline
Referenced by Navier_Stokes_std_ALE::sauvegarder(), Champ_Fonc_base::sauvegarder(), Champ_Inc_base::sauvegarder(), Schema_Temps_base::sauvegarder(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::sauvegarder(), Transport_Interfaces_FT_Disc_interne::sauvegarder(), Postraitement::sauvegarder(), Convection_Diffusion_Fluide_Dilatable_Proto::Sauvegarder_WC(), and Save_Restart::sauver().
trigger()
void TRUST_2_PDI::trigger (const std::string & event) inline
Referenced by get_type(), Schema_Temps_base::sauvegarder(), and Save_Restart::sauver().
stop_sharing_last_variable()
void TRUST_2_PDI::stop_sharing_last_variable () inline
Referenced by Schema_Temps_base::sauvegarder(), and Save_Restart::sauver().
stop_sharing()
void TRUST_2_PDI::stop_sharing () inline
Referenced by Save_Restart::sauver().
share_type()
void TRUST_2_PDI::share_type (const Nom & name, const Nom & type)
Generic method to share the type of a TRUST object.
Parameters
(Nom name) the name of the object
(Nom type) type of the object
References Nom::getChar(), Nom::getString(), Nom::longueur(), and write().
Referenced by Champ_Inc_base::sauvegarder().
get_type()
void TRUST_2_PDI::get_type (const Nom & name, Nom & type)
Generic method to read the type of a TRUST object in the HDF5 file.
Parameters
(Nom name) the name of the object
(Nom type) type of the object
References Nom::getChar(), Nom::getString(), and trigger().
Referenced by Transport_Interfaces_FT_Disc_interne::reprendre().
share_TRUSTTab_dimensions()
void TRUST_2_PDI::share_TRUSTTab_dimensions (const DoubleTab & tab, const Nom & name, int write)
Generic method to share the dimensions of a TRUST DoubleTab with PDI.
Parameters
(const DoubleTab& tab) the array we want to share with PDI
(Nom name) the name of the array
(int write) flag to specify if we want to write the dimensions or read into it
References TRUSTArray< _TYPE_, _SIZE_ >::addr(), Comm_Group::COLL_MAX, TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), PE_Groups::get_node_group(), Nom::getString(), Comm_Group::mp_collective_op(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), and write().
Referenced by Champ_Fonc_base::reprendre(), Champ_Inc_base::reprendre(), Navier_Stokes_std_ALE::sauvegarder(), Champ_Fonc_base::sauvegarder(), Champ_Inc_base::sauvegarder(), and Convection_Diffusion_Fluide_Dilatable_Proto::Sauvegarder_WC().
prepareRestart()
void TRUST_2_PDI::prepareRestart (int & last_iteration, double & tinit, int resume_last_time)
Generic method to prepare the restart of a computation.
Parameters
(int& last_iteration) the index of the backup iteration we want to recover from
(double& tinit) the time from which we want to resume the calculation
(int resume_last_time) flag to specify if we want to resume from the last time or we want to recover from a specific time
References Process::exit(), Process::node_master(), Process::nproc(), read(), and write().