TrioCFD: Discret_Thyd Class Reference
Discret_Thyd Class Reference
#include <Discret_Thyd.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Discret_Thermique
const Type_info * get_info () const override
Public Member Functions inherited from Discretisation_base
virtual void discretiser_champ (const Motcle &directive, const Domaine_dis_base &z, Nature_du_champ nature, const Noms &nom, const Noms &unite, int nb_comp, int nb_pas_dt, double temps, TRUST_Deriv< Champ_Inc_base > &champ, const Nom &sous_type=NOM_VIDE) const
const Type_info * get_info () const override
virtual Nom get_name_of_type_for (const Nom &class_operateur, const Nom &type_operteur, const Equation_base &eqn, const TRUST_Ref< Champ_base * > &champ_supp=TRUST_Ref< Champ_base * >()) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Discret_Thermique
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Discretisation_base
static void creer_champ (TRUST_Deriv< Champ_Don_base > &ch, const Domaine_dis_base &z, const Nom &type, const Nom &nom, const Nom &unite, int nb_comp, int nb_ddl, double temps, const Nom &directive=NOM_VIDE, const Nom &nom_discretisation=NOM_VIDE)
static void creer_champ (TRUST_Deriv< Champ_Fonc_base > &ch, const Domaine_dis_base &z, const Nom &type, const Nom &nom, const Nom &unite, int nb_comp, int nb_ddl, double temps, const Nom &directive=NOM_VIDE, const Nom &nom_discretisation=NOM_VIDE)
static void creer_champ (TRUST_Deriv< Champ_Inc_base > &ch, const Domaine_dis_base &z, const Nom &type, const Nom &nom, const Nom &unite, int nb_comp, int nb_ddl, int nb_pas_dt, double temps, const Nom &directive=NOM_VIDE, const Nom &nom_discretisation=NOM_VIDE)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
spatiale appliquee aux problemes de thermo-hydrauliques. Les methodes virtuelles pures sont a implementer dans les classes derivees pour typer et discretiser les champs portes par les equations liees a la discretisation.
See also
Discret_Thermique
Constructor & Destructor Documentation
Discret_Thyd()
Discret_Thyd::Discret_Thyd ()
~Discret_Thyd()
Discret_Thyd::~Discret_Thyd () override
Member Function Documentation
info()
const Type_info * Discret_Thyd::info () static
get_info()
const Type_info * Discret_Thyd::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Discretisation_base.
Reimplemented in VDF_discretisation, and VEF_discretisation.
self_cast() [1/2]
Discret_Thyd & Discret_Thyd::self_cast (Objet_U & r) static
self_cast() [2/2]
const Discret_Thyd & Discret_Thyd::self_cast (const Objet_U & r) static
printOn()
Sortie & Discret_Thyd::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Discretisation_base.
Reimplemented in VDF_discretisation, and VEF_discretisation.
readOn()
Entree & Discret_Thyd::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Discretisation_base.
Reimplemented in VDF_discretisation, and VEF_discretisation.
vitesse()
void Discret_Thyd::vitesse (const Schema_Temps_base & sch, Domaine_dis_base & z, TRUST_Deriv< Champ_Inc_base > & ch, int nb_comp = 1) const
References Objet_U::dimension, Discretisation_base::discretiser_champ(), Schema_Temps_base::nb_valeurs_temporelles(), and Schema_Temps_base::temps_courant().
Referenced by Navier_Stokes_Fluide_Dilatable_base::discretiser(), Navier_Stokes_Turbulent_QC::discretiser(), Navier_Stokes_std::discretiser_vitesse(), and QDM_Multiphase::discretiser_vitesse().
translation()
void Discret_Thyd::translation (const Schema_Temps_base & sch, Domaine_dis_base & z, TRUST_Deriv< Champ_Fonc_base > & ch) const
References Objet_U::dimension, Discretisation_base::discretiser_champ(), and Schema_Temps_base::temps_courant().
entcor()
void Discret_Thyd::entcor (const Schema_Temps_base & sch, Domaine_dis_base & z, TRUST_Deriv< Champ_Fonc_base > & ch) const
References Objet_U::dimension, Discretisation_base::discretiser_champ(), and Schema_Temps_base::temps_courant().
pression()
void Discret_Thyd::pression (const Schema_Temps_base & sch, Domaine_dis_base & z, TRUST_Deriv< Champ_Inc_base > & ch) const
References Discretisation_base::discretiser_champ(), and Schema_Temps_base::temps_courant().
Referenced by Navier_Stokes_std::discretiser().
pression_en_pa()
void Discret_Thyd::pression_en_pa (const Schema_Temps_base & sch, Domaine_dis_base & z, TRUST_Deriv< Champ_Inc_base > & ch) const
References Discretisation_base::discretiser_champ(), and Schema_Temps_base::temps_courant().
Referenced by Navier_Stokes_std::discretiser().
divergence_U()
void Discret_Thyd::divergence_U (const Schema_Temps_base & sch, Domaine_dis_base & z, TRUST_Deriv< Champ_Inc_base > & ch) const
References Discretisation_base::discretiser_champ(), and Schema_Temps_base::temps_courant().
Referenced by Navier_Stokes_std::discretiser().
gradient_P()
void Discret_Thyd::gradient_P (const Schema_Temps_base & sch, Domaine_dis_base & z, TRUST_Deriv< Champ_Inc_base > & ch, int nb_comp = 1) const
References Objet_U::dimension, Discretisation_base::discretiser_champ(), and Schema_Temps_base::temps_courant().
Referenced by QDM_Multiphase::creer_champ(), and Navier_Stokes_std::discretiser_grad_p().
concentration()
void Discret_Thyd::concentration (const Schema_Temps_base & sch, Domaine_dis_base & z, TRUST_Deriv< Champ_Inc_base > & ch, int nb_constituants = 1, const Nom nom_champ = "concentration") const
References Discretisation_base::discretiser_champ(), Field_base::fixer_nature_du_champ(), Field_base::fixer_nom_compo(), Schema_Temps_base::nb_valeurs_temporelles(), Field_base::nommer(), and Schema_Temps_base::temps_courant().
Referenced by Convection_Diffusion_Concentration::discretiser().
diametre_hydraulique_face()
void Discret_Thyd::diametre_hydraulique_face (const Domaine_dis_base & z, const DoubleVect & diam_face, const Schema_Temps_base & sch, TRUST_Deriv< Champ_Fonc_base > & ch) const
References Discretisation_base::discretiser_champ(), TRUSTTab< _TYPE_, _SIZE_ >::ref(), Schema_Temps_base::temps_courant(), and Champ_Don_base::valeurs().
section_passage()
void Discret_Thyd::section_passage (const Domaine_dis_base & z, const DoubleVect & section_passage_face, const Schema_Temps_base & sch, TRUST_Deriv< Champ_Fonc_base > & ch) const
References Objet_U::dimension, Discretisation_base::discretiser_champ(), TRUSTArray< _TYPE_, _SIZE_ >::inject_array(), Schema_Temps_base::temps_courant(), and Champ_Don_base::valeurs().
creer_champ_vorticite()
void Discret_Thyd::creer_champ_vorticite (const Schema_Temps_base & , const Champ_Inc_base & , TRUST_Deriv< Champ_Fonc_base > &) const virtual
Reimplemented in EF_discretisation, PolyMAC_P0_discretisation, VDF_discretisation, and VEF_discretisation.
References Process::exit(), and Objet_U::que_suis_je().
Referenced by Navier_Stokes_std::creer_champ().
grad_u()
void Discret_Thyd::grad_u (const Domaine_dis_base & , const Domaine_Cl_dis_base & , const Champ_Inc_base & , TRUST_Deriv< Champ_Fonc_base > &) const virtual
Reimplemented in VDF_discretisation, VEF_discretisation, DG_discretisation, PolyMAC_discretisation, PolyMAC_P0_discretisation, and PolyMAC_P0P1NC_discretisation.
References Process::exit(), and Objet_U::que_suis_je().
Referenced by Navier_Stokes_std::creer_champ().
proprietes_physiques_fluide_Ostwald()
void Discret_Thyd::proprietes_physiques_fluide_Ostwald (const Domaine_dis_base & , Fluide_Ostwald & , const Navier_Stokes_std & , const Champ_Inc_base &) const virtual
Reimplemented in EF_discretisation, VDF_discretisation, and VEF_discretisation.
References Process::exit(), and Objet_U::que_suis_je().
Referenced by Fluide_Ostwald::discretiser().
distance_paroi_globale()
void Discret_Thyd::distance_paroi_globale (const Schema_Temps_base & , Domaine_dis_base & , TRUST_Deriv< Champ_Fonc_base > &) const virtual
Reimplemented in DG_discretisation, PolyMAC_discretisation, VDF_discretisation, and VEF_discretisation.
References Process::exit(), and Objet_U::que_suis_je().
Referenced by Navier_Stokes_std::creer_champ().
y_plus()
void Discret_Thyd::y_plus (const Domaine_dis_base & , const Domaine_Cl_dis_base & , const Champ_Inc_base & , TRUST_Deriv< Champ_Fonc_base > &) const virtual
Reimplemented in VDF_discretisation, EF_discretisation, PolyMAC_P0P1NC_discretisation, and VEF_discretisation.
References Process::exit(), and Objet_U::que_suis_je().
Referenced by Navier_Stokes_std::creer_champ().
grad_T()
void Discret_Thyd::grad_T (const Domaine_dis_base & z, const Domaine_Cl_dis_base & zcl, const Champ_Inc_base & eqn, TRUST_Deriv< Champ_Fonc_base > & ch) const virtual
Reimplemented in EF_discretisation, and VEF_discretisation.
References Process::exit(), and Objet_U::que_suis_je().
Referenced by Convection_Diffusion_Temperature::creer_champ().
h_conv()
void Discret_Thyd::h_conv (const Domaine_dis_base & z, const Domaine_Cl_dis_base & zcl, const Champ_Inc_base & eqn, TRUST_Deriv< Champ_Fonc_base > & ch, Motcle & nom, int temp_ref) const virtual
Reimplemented in EF_discretisation, and VEF_discretisation.
References Process::exit(), and Objet_U::que_suis_je().
Referenced by Convection_Diffusion_Temperature::creer_champ().
critere_Q()
void Discret_Thyd::critere_Q (const Domaine_dis_base & , const Domaine_Cl_dis_base & , const Champ_Inc_base & , TRUST_Deriv< Champ_Fonc_base > &) const virtual
Reimplemented in VDF_discretisation, EF_discretisation, and VEF_discretisation.
References Process::exit(), and Objet_U::que_suis_je().
Referenced by Navier_Stokes_std::creer_champ().
reynolds_maille()
virtual void Discret_Thyd::reynolds_maille (const Domaine_dis_base & , const Fluide_base & , const Champ_Inc_base & , TRUST_Deriv< Champ_Fonc_base > &) const inline virtual
Reimplemented in VDF_discretisation.
References Process::exit().
Referenced by Navier_Stokes_std::creer_champ().
courant_maille()
virtual void Discret_Thyd::courant_maille (const Domaine_dis_base & , const Schema_Temps_base & , const Champ_Inc_base & , TRUST_Deriv< Champ_Fonc_base > &) const inline virtual
Reimplemented in VDF_discretisation.
References Process::exit().
Referenced by Navier_Stokes_std::creer_champ().
estimateur_aposteriori()
virtual void Discret_Thyd::estimateur_aposteriori (const Domaine_dis_base & , const Domaine_Cl_dis_base & , const Champ_Inc_base & , const Champ_Inc_base & , const Champ_Don_base & , TRUST_Deriv< Champ_Fonc_base > &) const inline virtual
References Process::exit().
taux_cisaillement()
virtual void Discret_Thyd::taux_cisaillement (const Domaine_dis_base & , const Domaine_Cl_dis_base & , const Champ_Inc_base & , TRUST_Deriv< Champ_Fonc_base > &) const inline virtual
Reimplemented in PolyMAC_P0_discretisation, VDF_discretisation, and VEF_discretisation.
References Process::exit().
Referenced by Navier_Stokes_std::creer_champ().
Member Data Documentation
info_obj
const Type_info Discret_Thyd::info_obj static