TrioCFD: Domain_Graph Class Reference
Domain_Graph Class Reference
#include <Domain_Graph.h>
Member Typedef Documentation
ArrOfIdx_
using Domain_Graph::ArrOfIdx_ = TRUSTArray<idx_t, idx_t>
Member Function Documentation
construire_graph_from_segment()
template<typename _SIZE_ > template void Domain_Graph::construire_graph_from_segment (const Domaine_32_64< _SIZE_ > & dom, bool use_weights)
References adjncy, ewgts, Matrix_tools::fill_csr_arrays(), Domaine_32_64< _SIZE_ >::les_elems(), nedges, nvtxs, TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), vwgts, weightflag, and xadj.
Referenced by Partitionneur_Metis_32_64< _SIZE_ >::construire_partition().
construire_graph_elem_elem()
template<typename _SIZE_ > template void Domain_Graph::construire_graph_elem_elem (const Domaine_32_64< _SIZE_ > & dom, const Noms & liste_bords_periodiques, bool use_weights, Static_Int_Lists_32_64< _SIZE_ > & graph_elements_perio)
References adjncy, Partitionneur_base_32_64< _SIZE_ >::calculer_graphe_connexions_periodiques(), Process::check_int_overflow(), Domaine_32_64< _SIZE_ >::construire_elem_virt_pe_num(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), edgegsttab, ewgts, Process::exit(), Static_Int_Lists_32_64< _SIZE_ >::get_list_size(), Elem_geom_base_32_64< _SIZE_ >::get_tab_faces_sommets_locaux(), Process::is_parallel(), Process::is_sequential(), Domaine_32_64< _SIZE_ >::les_elems(), Process::me(), Process::mp_sum(), Process::mppartial_sum(), Domaine_32_64< _SIZE_ >::nb_elem(), Domaine_32_64< _SIZE_ >::nb_faces_frontiere(), Domaine_32_64< _SIZE_ >::nb_faces_joint(), Domaine_32_64< _SIZE_ >::nb_som(), nedges, Process::nproc(), nvtxs, TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), TRUST_Vector< _CLASSE_ >::size(), Domaine_32_64< _SIZE_ >::type_elem(), TRUST_Deriv< _CLASSE_ >::valeur(), vtxdist, vwgts, weightflag, and xadj.
Referenced by Partitionneur_Metis_32_64< _SIZE_ >::construire_partition(), Partitionneur_Parmetis::construire_partition(), and Partitionneur_Ptscotch::construire_partition().
Member Data Documentation
nvtxs
idx_t Domain_Graph::nvtxs
Referenced by construire_graph_elem_elem(), construire_graph_from_segment(), Partitionneur_Metis_32_64< _SIZE_ >::construire_partition(), and Partitionneur_Parmetis::construire_partition().
nedges
idx_t Domain_Graph::nedges
Referenced by construire_graph_elem_elem(), and construire_graph_from_segment().
weightflag
idx_t Domain_Graph::weightflag
Referenced by construire_graph_elem_elem(), construire_graph_from_segment(), and Partitionneur_Parmetis::construire_partition().
xadj
ArrOfIdx_ Domain_Graph::xadj
Referenced by construire_graph_elem_elem(), construire_graph_from_segment(), Partitionneur_Metis_32_64< _SIZE_ >::construire_partition(), Partitionneur_Parmetis::construire_partition(), and Partitionneur_Ptscotch::construire_partition().
adjncy
ArrOfIdx_ Domain_Graph::adjncy
Referenced by construire_graph_elem_elem(), construire_graph_from_segment(), Partitionneur_Metis_32_64< _SIZE_ >::construire_partition(), Partitionneur_Parmetis::construire_partition(), and Partitionneur_Ptscotch::construire_partition().
vwgts
ArrOfIdx_ Domain_Graph::vwgts
Referenced by construire_graph_elem_elem(), construire_graph_from_segment(), Partitionneur_Metis_32_64< _SIZE_ >::construire_partition(), and Partitionneur_Parmetis::construire_partition().
ewgts
ArrOfIdx_ Domain_Graph::ewgts
Referenced by construire_graph_elem_elem(), construire_graph_from_segment(), Partitionneur_Metis_32_64< _SIZE_ >::construire_partition(), Partitionneur_Parmetis::construire_partition(), and Partitionneur_Ptscotch::construire_partition().
vtxdist
ArrOfIdx_ Domain_Graph::vtxdist
Referenced by construire_graph_elem_elem(), and Partitionneur_Parmetis::construire_partition().
edgegsttab
ArrOfIdx_ Domain_Graph::edgegsttab
Referenced by construire_graph_elem_elem(), and Partitionneur_Ptscotch::construire_partition().