TrioCFD: Paroi_std_hyd_VEF_diphasique Class Reference
Paroi_std_hyd_VEF_diphasique Class Reference
#include <Paroi_std_hyd_VEF_diphasique.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Paroi_std_hyd_VEF
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Turbulence_paroi_base
void associer_modele (const Modele_turbulence_hyd_base &)
int calculer_hyd (Champ_Fonc_base &, Champ_Fonc_base &)
int calculer_hyd (Champ_Inc_base &)
const Type_info * get_info () const override
virtual void imprimer_premiere_ligne_ustar (int, const TRUST_List< Nom > &, const Nom &) const
virtual void imprimer_ustar_mean_only (Sortie &, int, const TRUST_List< Nom > &, const Nom &) const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Paroi_std_hyd_VEF
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Turbulence_paroi_base
static void typer_lire_turbulence_paroi (TRUST_Deriv< Turbulence_paroi_base > &, const Modele_turbulence_hyd_base &, Entree &)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
Constructor & Destructor Documentation
Paroi_std_hyd_VEF_diphasique()
Paroi_std_hyd_VEF_diphasique::Paroi_std_hyd_VEF_diphasique ()
~Paroi_std_hyd_VEF_diphasique()
Paroi_std_hyd_VEF_diphasique::~Paroi_std_hyd_VEF_diphasique ()
Member Function Documentation
cree_instance()
Objet_U * Paroi_std_hyd_VEF_diphasique::cree_instance () static
taille_memoire()
unsigned Paroi_std_hyd_VEF_diphasique::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Paroi_std_hyd_VEF_diphasique::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Paroi_std_hyd_VEF_diphasique::info () static
get_info()
const Type_info * Paroi_std_hyd_VEF_diphasique::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Paroi_hyd_base_VEF.
self_cast() [1/2]
Paroi_std_hyd_VEF_diphasique & Paroi_std_hyd_VEF_diphasique::self_cast (Objet_U & r) static
self_cast() [2/2]
const Paroi_std_hyd_VEF_diphasique & Paroi_std_hyd_VEF_diphasique::self_cast (const Objet_U & r) static
printOn()
Sortie & Paroi_std_hyd_VEF_diphasique::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Paroi_hyd_base_VEF.
References Objet_U::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Paroi_std_hyd_VEF_diphasique::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Paroi_hyd_base_VEF.
References Paroi_std_hyd_VEF::readOn().
calculer_hyd() [1/2]
int Paroi_std_hyd_VEF_diphasique::calculer_hyd (DoubleTab & tab_k_eps) override virtual
Implements Turbulence_paroi_base.
References Process::exit().
calculer_hyd() [2/2]
int Paroi_std_hyd_VEF_diphasique::calculer_hyd (DoubleTab & tab_nu_t, DoubleTab & tab_k) override virtual
Implements Turbulence_paroi_base.
References Paroi_std_hyd_VEF::calculer_k_eps(), Paroi_std_hyd_VEF::calculer_u_plus(), Turbulence_paroi_base::Cisaillement_paroi_, Paroi_log_QDM::Cmu_, Objet_U::dimension, Domaine_dis_base::domaine(), Equation_base::domaine_Cl_dis(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_VF::elem_faces(), MorEqn::equation(), Probleme_base::equation(), Paroi_log_QDM::Erugu, Process::exit(), Domaine_VF::face_normales(), Domaine_VF::face_voisins(), Fluide_Diphasique::fluide_phase(), Paroi_decalee_Robin::get_delta(), Equation_base::inconnue(), Transport_Interfaces_FT_Disc::inconnue(), Paroi_std_hyd_VEF::is_u_star_impose_, Turbulence_paroi_base::le_dom_Cl_dis_, Turbulence_paroi_base::le_dom_dis_, TRUSTVect< _TYPE_, _SIZE_ >::local_min_vect(), Equation_base::milieu(), Turbulence_paroi_base::mon_modele_turb_hyd, TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Front_VF::nb_faces_tot(), Domaine_dis_base::nb_front_Cl(), Modele_turbulence_hyd_combinaison::nombre_sources(), Front_VF::num_face(), Equation_base::probleme(), Turbulence_paroi_base::tab_d_plus_, Turbulence_paroi_base::tab_u_star_, Paroi_std_hyd_VEF::u_star_impose_, Paroi_std_hyd_VEF::uplus_, TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), Champ_Inc_base::valeurs(), Debog::verifier(), and Fluide_base::viscosite_cinematique().
Member Data Documentation
info_obj
const Type_info Paroi_std_hyd_VEF_diphasique::info_obj static