TrioCFD: Transport_Fluctuation_Temperature_W Class Reference
Transport_Fluctuation_Temperature_W Class Reference
#include <Transport_Fluctuation_Temperature_W.h>
Public Member Functions
void associer_milieu_base (const Milieu_base &) override
void completer () override
void discretiser () override
const Motcle & domaine_application () const override
const Type_info * get_info () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
int nombre_d_operateurs () const override
const Operateur & operateur (int) const override
Operateur & operateur (int) override
Public Member Functions inherited from Convection_Diffusion_std
void associer_vitesse (const Champ_base &)
const Type_info * get_info () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
int nombre_d_operateurs () const override
const Operateur & operateur (int) const override
Operateur & operateur (int) override
const Champ_Inc_base & vitesse_transportante () const
Public Member Functions inherited from Equation_base
virtual void abortTimeStep ()
virtual void associer_domaine_dis (const Domaine_dis_base &)
virtual void associer_pb_base (const Probleme_base &)
virtual void associer_sch_tps_base (const Schema_Temps_base &)
virtual double calculer_pas_de_temps () const
virtual void completer ()
virtual std::vector< YAML_data > data_a_sauvegarder () const
DoubleTab & derivee_en_temps_conv (DoubleTab &, const DoubleTab &)
virtual DoubleTab & derivee_en_temps_inco (DoubleTab &)
const Discretisation_base & discretisation () const
virtual void discretiser ()
virtual const Motcle & domaine_application () const
virtual Domaine_Cl_dis_base & domaine_Cl_dis ()
virtual const Domaine_Cl_dis_base & domaine_Cl_dis () const
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual void imprimer (Sortie &os) const
virtual bool initTimeStep (double dt)
const Nom & le_nom () const override
int limpr () const
virtual void mettre_a_jour (double temps)
virtual int preparer_calcul ()
Probleme_base & probleme ()
const Probleme_base & probleme () const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Schema_Temps_base & schema_temps ()
const Schema_Temps_base & schema_temps () const
Solveur_Masse_base & solv_masse ()
const Solveur_Masse_base & solv_masse () const
Sources & sources ()
const Sources & sources () const
virtual void valider_iteration ()
virtual void verifie_ch_init_nb_comp (const Champ_Inc_base &ch_ref, const int nb_comp) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Equation_base
virtual Entree & lire_cl (Entree &)
virtual Entree & lire_cond_init (Entree &)
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual Entree & lire_sources (Entree &)
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
virtual int verif_Cl () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
~Transport_Fluctuation_Temperature_W()
Transport_Fluctuation_Temperature_W::~Transport_Fluctuation_Temperature_W ()
Transport_Fluctuation_Temperature_W()
Transport_Fluctuation_Temperature_W::Transport_Fluctuation_Temperature_W ()
Member Function Documentation
cree_instance()
Objet_U * Transport_Fluctuation_Temperature_W::cree_instance () static
taille_memoire()
unsigned Transport_Fluctuation_Temperature_W::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Transport_Fluctuation_Temperature_W_Bas_Re.
duplique()
int Transport_Fluctuation_Temperature_W::duplique () const override virtual
Implements Objet_U.
Reimplemented in Transport_Fluctuation_Temperature_W_Bas_Re.
info()
const Type_info * Transport_Fluctuation_Temperature_W::info () static
get_info()
const Type_info * Transport_Fluctuation_Temperature_W::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Convection_Diffusion_std.
Reimplemented in Transport_Fluctuation_Temperature_W_Bas_Re.
self_cast() [1/2]
Transport_Fluctuation_Temperature_W & Transport_Fluctuation_Temperature_W::self_cast (Objet_U & r) static
self_cast() [2/2]
const Transport_Fluctuation_Temperature_W & Transport_Fluctuation_Temperature_W::self_cast (const Objet_U & r) static
printOn()
Sortie & Transport_Fluctuation_Temperature_W::printOn (Sortie & is) const override protected virtual
Simple appel a Equation_base::printOn(Sortie&)
Parameters
(Sortie& is) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Convection_Diffusion_std.
Reimplemented in Transport_Fluctuation_Temperature_W_Bas_Re.
References Objet_U::que_suis_je().
readOn()
Entree & Transport_Fluctuation_Temperature_W::readOn (Entree & is) override protected virtual
cf Convection_Diffusion_std::readOn(is)
Reimplemented from Convection_Diffusion_std.
Reimplemented in Transport_Fluctuation_Temperature_W_Bas_Re.
References TRUST_List< _CLASSE_ >::add(), TRUST_List< _CLASSE_ >::est_vide(), Equation_base::les_sources, Equation_base::probleme(), Convection_Diffusion_std::readOn(), and Source::typer().
Referenced by Transport_Fluctuation_Temperature_W_Bas_Re::readOn().
set_param()
void Transport_Fluctuation_Temperature_W::set_param (Param & titi) override virtual
Reimplemented from Convection_Diffusion_std.
Reimplemented in Transport_Fluctuation_Temperature_W_Bas_Re.
References Convection_Diffusion_std::set_param().
Referenced by Transport_Fluctuation_Temperature_W_Bas_Re::set_param().
lire_motcle_non_standard()
int Transport_Fluctuation_Temperature_W::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Convection_Diffusion_std.
Reimplemented in Transport_Fluctuation_Temperature_W_Bas_Re.
References Convection_Diffusion_std::lire_motcle_non_standard(), and terme_diffusif.
Referenced by Transport_Fluctuation_Temperature_W_Bas_Re::lire_motcle_non_standard().
associer_milieu_base()
void Transport_Fluctuation_Temperature_W::associer_milieu_base (const Milieu_base & un_milieu) override virtual
association entre Transport_Fluctuation_Temperature_W et Milieu_base.
affecte le_Milieu_base.
Implements Equation_base.
References le_fluide.
Referenced by associer_modele_turbulence(), and Transport_Fluctuation_Temperature_W_Bas_Re::associer_modele_turbulence().
associer_modele_turbulence()
void Transport_Fluctuation_Temperature_W::associer_modele_turbulence (const Modele_turbulence_scal_Fluctuation_Temperature_W & modele)
References Equation_base::associer_domaine_dis(), associer_milieu_base(), Equation_base::associer_pb_base(), Equation_base::associer_sch_tps_base(), discretiser(), Equation_base::domaine_dis(), Modele_turbulence_scal_base::equation(), Equation_base::milieu(), mon_modele_Fluctu_Temp, Equation_base::probleme(), and Equation_base::schema_temps().
discretiser()
void Transport_Fluctuation_Temperature_W::discretiser () override virtual
Discretise l'equation.
Type le domaine_Cl_dis, la formatte, l'associe a l'equation. Type le solveur masse, lui associe le domaine discretisee et le domaine des conditions aux limites discretisees.
Reimplemented from Equation_base.
References Champs_compris_T< FIELD_TYPE >::ajoute_champ(), Equation_base::champs_compris_, Equation_base::discretisation(), Equation_base::discretiser(), Equation_base::domaine_dis(), Discret_Thermique::Fluctu_Temperature(), le_champ_Fluctu_Temperature, Objet_U::que_suis_je(), and Equation_base::schema_temps().
Referenced by associer_modele_turbulence(), and Transport_Fluctuation_Temperature_W_Bas_Re::associer_modele_turbulence().
completer()
void Transport_Fluctuation_Temperature_W::completer () override virtual
Complete la construction (initialisation) des objets associes a l'equation.
Complete les sources, associe l'equation a l'inconnue complete les operateurs, complete les conditions aux limites discretisees. Voir les methodes Source_base::completer(), Operateur_base::completer() Domaine_Cl_dis_base::completer() Domaine_Cl_dis_base::completer(const Domaine_dis_base&)
Reimplemented from Equation_base.
References Equation_base::completer().
milieu() [1/2]
const Milieu_base & Transport_Fluctuation_Temperature_W::milieu () const override virtual
Implements Equation_base.
Reimplemented in Transport_Fluctuation_Temperature_W_Bas_Re.
References Process::exit(), le_fluide, TRUST_Ref< _CLASSE_ >::non_nul(), and TRUST_Ref< _CLASSE_ >::valeur().
milieu() [2/2]
Milieu_base & Transport_Fluctuation_Temperature_W::milieu () override virtual
Implements Equation_base.
Reimplemented in Transport_Fluctuation_Temperature_W_Bas_Re.
References Process::exit(), le_fluide, TRUST_Ref< _CLASSE_ >::non_nul(), and TRUST_Ref< _CLASSE_ >::valeur().
modele_turbulence() [1/2]
const Modele_turbulence_scal_Fluctuation_Temperature_W & Transport_Fluctuation_Temperature_W::modele_turbulence () const inline
References mon_modele_Fluctu_Temp, TRUST_Ref< _CLASSE_ >::non_nul(), and TRUST_Ref< _CLASSE_ >::valeur().
modele_turbulence() [2/2]
Modele_turbulence_scal_Fluctuation_Temperature_W & Transport_Fluctuation_Temperature_W::modele_turbulence () inline
References mon_modele_Fluctu_Temp, TRUST_Ref< _CLASSE_ >::non_nul(), and TRUST_Ref< _CLASSE_ >::valeur().
nombre_d_operateurs()
int Transport_Fluctuation_Temperature_W::nombre_d_operateurs () const override virtual
surcharge de la methode d'Equation_base.
renvoie le nombre d'operateurs.
Reimplemented from Convection_Diffusion_std.
Referenced by operateur(), and Transport_Fluctuation_Temperature_W_Bas_Re::operateur().
operateur() [1/2]
const Operateur & Transport_Fluctuation_Temperature_W::operateur (int i) const override virtual
surcharge de la methode d'Equation_base.
renvoie le ieme operateur.
Reimplemented from Convection_Diffusion_std.
Reimplemented in Transport_Fluctuation_Temperature_W_Bas_Re.
References Process::exit(), nombre_d_operateurs(), Convection_Diffusion_std::terme_convectif, and terme_diffusif.
operateur() [2/2]
Operateur & Transport_Fluctuation_Temperature_W::operateur (int i) override virtual
surcharge de la methode d'Equation_base.
renvoie le ieme operateur.
Reimplemented from Convection_Diffusion_std.
Reimplemented in Transport_Fluctuation_Temperature_W_Bas_Re.
References Process::exit(), nombre_d_operateurs(), Convection_Diffusion_std::terme_convectif, and terme_diffusif.
inconnue() [1/2]
const Champ_Inc_base & Transport_Fluctuation_Temperature_W::inconnue () const inline override virtual
renvoie le champ inconnue.
Implements Convection_Diffusion_std.
References le_champ_Fluctu_Temperature.
Referenced by Source_Transport_K_Eps_Bas_Reynolds_anisotherme_W_VDF_Elem::ajouter_blocs().
inconnue() [2/2]
Champ_Inc_base & Transport_Fluctuation_Temperature_W::inconnue () inline override virtual
renvoie le champ inconnue.
Implements Convection_Diffusion_std.
References le_champ_Fluctu_Temperature.
domaine_application()
const Motcle & Transport_Fluctuation_Temperature_W::domaine_application () const override virtual
Renvoie "indetermine" Navier_Stokes_standard par exemple surcharge cette methode.
pour renvoyer "Hydraulique"
Returns
(Motcle&) le nom du domaine d'aplication
Reimplemented from Equation_base.
controler_grandeur()
int Transport_Fluctuation_Temperature_W::controler_grandeur ()
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), le_champ_Fluctu_Temperature, and Champ_Inc_base::valeurs().
Member Data Documentation
info_obj
const Type_info Transport_Fluctuation_Temperature_W::info_obj static
le_champ_Fluctu_Temperature
TRUST_Deriv< Champ_Inc_base > Transport_Fluctuation_Temperature_W::le_champ_Fluctu_Temperature protected
Referenced by controler_grandeur(), discretiser(), and inconnue().
terme_diffusif
Op_Diff_Fluctu_Temp Transport_Fluctuation_Temperature_W::terme_diffusif protected
Referenced by lire_motcle_non_standard(), Transport_Fluctuation_Temperature_W_Bas_Re::lire_motcle_non_standard(), operateur(), and Transport_Fluctuation_Temperature_W_Bas_Re::operateur().
le_fluide
TRUST_Ref< Fluide_base *> Transport_Fluctuation_Temperature_W::le_fluide protected
Referenced by associer_milieu_base(), milieu(), and Transport_Fluctuation_Temperature_W_Bas_Re::milieu().
mon_modele_Fluctu_Temp
TRUST_Ref< Modele_turbulence_scal_Fluctuation_Temperature_W *> Transport_Fluctuation_Temperature_W::mon_modele_Fluctu_Temp protected
Referenced by associer_modele_turbulence(), and modele_turbulence().