TrioCFD: LoiParoiHybride_VDF Class Reference
LoiParoiHybride_VDF Class Reference
#include <LoiParoiHybride_VDF.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Turbulence_paroi_base
void associer_modele (const Modele_turbulence_hyd_base &)
int calculer_hyd (Champ_Fonc_base &, Champ_Fonc_base &)
int calculer_hyd (Champ_Inc_base &)
const Type_info * get_info () const override
virtual void imprimer_premiere_ligne_ustar (int, const TRUST_List< Nom > &, const Nom &) const
virtual void imprimer_ustar_mean_only (Sortie &, int, const TRUST_List< Nom > &, const Nom &) const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Turbulence_paroi_base
static void typer_lire_turbulence_paroi (TRUST_Deriv< Turbulence_paroi_base > &, const Modele_turbulence_hyd_base &, Entree &)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
.SECTION voir aussi Turbulence_paroi_base
Constructor & Destructor Documentation
LoiParoiHybride_VDF()
LoiParoiHybride_VDF::LoiParoiHybride_VDF ()
~LoiParoiHybride_VDF()
LoiParoiHybride_VDF::~LoiParoiHybride_VDF ()
Member Function Documentation
cree_instance()
Objet_U * LoiParoiHybride_VDF::cree_instance () static
taille_memoire()
unsigned LoiParoiHybride_VDF::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int LoiParoiHybride_VDF::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * LoiParoiHybride_VDF::info () static
get_info()
const Type_info * LoiParoiHybride_VDF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Paroi_hyd_base_VDF.
self_cast() [1/2]
LoiParoiHybride_VDF & LoiParoiHybride_VDF::self_cast (Objet_U & r) static
self_cast() [2/2]
const LoiParoiHybride_VDF & LoiParoiHybride_VDF::self_cast (const Objet_U & r) static
printOn()
Sortie & LoiParoiHybride_VDF::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Paroi_hyd_base_VDF.
References Objet_U::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & LoiParoiHybride_VDF::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Paroi_hyd_base_VDF.
References Turbulence_paroi_base::le_dom_Cl_dis_, Turbulence_paroi_base::le_dom_dis_, Objet_U_ptr::le_nom(), LoiParoiHybride::lire(), Turbulence_paroi_base::mon_modele_turb_hyd, and TRUST_Ref< _CLASSE_ >::valeur().
associer()
void LoiParoiHybride_VDF::associer (const Domaine_dis_base & zd, const Domaine_Cl_dis_base & zcl) override virtual
Reimplemented from Paroi_hyd_base_VDF.
References LoiParoiHybride::associer(), and Paroi_hyd_base_VDF::associer().
init_lois_paroi()
int LoiParoiHybride_VDF::init_lois_paroi () override virtual
Implements Turbulence_paroi_base.
References Turbulence_paroi_base::Cisaillement_paroi_, Objet_U::dimension, TRUSTVect< _TYPE_, _SIZE_ >::get_md_vector(), LoiParoiHybride::init_lois_paroi(), Turbulence_paroi_base::le_dom_dis_, MD_Vector::non_nul(), and TRUSTTab< _TYPE_, _SIZE_ >::resize().
calculer_hyd() [1/2]
int LoiParoiHybride_VDF::calculer_hyd (DoubleTab & tab1) override virtual
Implements Turbulence_paroi_base.
References LoiParoiHybride::calculer_hyd(), Turbulence_paroi_base::Cisaillement_paroi_, Turbulence_paroi_base::le_dom_Cl_dis_, Turbulence_paroi_base::le_dom_dis_, and TRUST_Ref< _CLASSE_ >::valeur().
calculer_hyd() [2/2]
int LoiParoiHybride_VDF::calculer_hyd (DoubleTab & tab1, DoubleTab & tab2) override virtual
Implements Turbulence_paroi_base.
References LoiParoiHybride::calculer_hyd(), Turbulence_paroi_base::Cisaillement_paroi_, Turbulence_paroi_base::le_dom_Cl_dis_, Turbulence_paroi_base::le_dom_dis_, and TRUST_Ref< _CLASSE_ >::valeur().
calculer_hyd_BiK()
int LoiParoiHybride_VDF::calculer_hyd_BiK (DoubleTab & tab_k, DoubleTab & tab_eps) override virtual
Implements Turbulence_paroi_base.
References LoiParoiHybride::calculer_hyd_BiK(), Turbulence_paroi_base::Cisaillement_paroi_, Turbulence_paroi_base::le_dom_Cl_dis_, Turbulence_paroi_base::le_dom_dis_, and TRUST_Ref< _CLASSE_ >::valeur().
Member Data Documentation
info_obj
const Type_info LoiParoiHybride_VDF::info_obj static