TrioCFD: Paroi_frottante_simple Class Reference
Paroi_frottante_simple Class Reference
#include <Paroi_frottante_simple.h>
Public Member Functions
const Type_info * get_info () const override
virtual int initialiser (double temps) override
void mettre_a_jour (double tps) override
const Type_info * get_info () const override
Public Member Functions inherited from Frottement_impose_base
void associer_domaine_cl_dis_base (const Domaine_Cl_dis_base &zcl) override
void associer_fr_dis_base (const Frontiere_dis_base &fr) override
void calculer_coeffs_echange (double temps) override
const Frontiere_dis_base & frontiere_dis () const override
Frontiere_dis_base & frontiere_dis () override
const Type_info * get_info () const override
int initialiser (double temps) override=0
void verifie_ch_init_nb_comp () const override
const Type_info * get_info () const override
Public Member Functions inherited from Cond_lim_base
virtual int a_mettre_a_jour_ss_pas_dt ()
virtual void associer_domaine_cl_dis_base (const Domaine_Cl_dis_base &)
virtual void associer_fr_dis_base (const Frontiere_dis_base &)
virtual void calculer_coeffs_echange (double temps)
virtual int compatible_avec_discr (const Discretisation_base &) const
Domaine_Cl_dis_base & domaine_Cl_dis ()
const Domaine_Cl_dis_base & domaine_Cl_dis () const
virtual Frontiere_dis_base & frontiere_dis ()
virtual const Frontiere_dis_base & frontiere_dis () const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
void set_modifier_val_imp (int)
virtual void verifie_ch_init_nb_comp () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Cond_lim_base
void err_pas_compatible (const Discretisation_base &) const
void err_pas_compatible (const Equation_base &) const
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
transport de QDM. Le coefficient de frottement est calcule a partir de la correlation de loi de paroi adaptative.
See also
Neumann
Constructor & Destructor Documentation
Paroi_frottante_simple()
Paroi_frottante_simple::Paroi_frottante_simple ()
~Paroi_frottante_simple()
Paroi_frottante_simple::~Paroi_frottante_simple ()
Member Function Documentation
cree_instance()
Objet_U * Paroi_frottante_simple::cree_instance () static
taille_memoire()
unsigned Paroi_frottante_simple::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Paroi_frottante_simple::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Paroi_frottante_simple::info () static
get_info()
const Type_info * Paroi_frottante_simple::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Frottement_global_impose.
self_cast() [1/2]
Paroi_frottante_simple & Paroi_frottante_simple::self_cast (Objet_U & r) static
self_cast() [2/2]
const Paroi_frottante_simple & Paroi_frottante_simple::self_cast (const Objet_U & r) static
printOn()
Sortie & Paroi_frottante_simple::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Frottement_global_impose.
References Objet_U::que_suis_je().
readOn()
Entree & Paroi_frottante_simple::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Frottement_global_impose.
References Cond_lim_base::app_domains, Cond_lim_base::le_champ_front, and Objet_U_ptr::typer().
completer()
void Paroi_frottante_simple::completer () override virtual
NE FAIT RIEN A surcharger dans les classes derivees.
Reimplemented from Frottement_impose_base.
References Cond_lim_base::domaine_Cl_dis(), Process::exit(), and Objet_U::que_suis_je().
initialiser()
int Paroi_frottante_simple::initialiser (double temps) override virtual
Initialisation en debut de calcul.
A appeler avant tout calculer_coeffs_echange ou mettre_a_jour Contrairementaux methodes mettre_a_jour, les methodes initialiser des CLs ne peuvent pas dependre de l'exterieur (lui-meme peut ne pas etre initialise)
Returns
(0 en cas d'erreur, 1 sinon.)
Implements Frottement_impose_base.
References correlation_loi_paroi_, Cond_lim_base::domaine_Cl_dis(), MorEqn::equation(), Probleme_base::get_correlation(), Frottement_impose_base::la_frontiere_dis, Equation_base::probleme(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), valeurs_coeff_, and valeurs_coeff_grad_.
avancer()
virtual int Paroi_frottante_simple::avancer (double temps) inline override virtual
Tourne la roue de la CL.
Reimplemented from Cond_lim_base.
mettre_a_jour()
void Paroi_frottante_simple::mettre_a_jour (double temps) override virtual
Effectue une mise a jour en temps de la condition aux limites.
Parameters
(double temps) le pas de temps de mise a jour
Reimplemented from Cond_lim_base.
References me_calculer(), and Frottement_impose_base::mon_temps.
me_calculer()
void Paroi_frottante_simple::me_calculer ()
References correlation_loi_paroi_, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Cond_lim_base::domaine_Cl_dis(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), MorEqn::equation(), fac_coeff_grad(), Probleme_base::get_champ(), Champ_Face_base::get_elem_vector_field(), Loi_paroi_base::get_tab(), Equation_base::inconnue(), Frottement_impose_base::la_frontiere_dis, TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Champ_Proto::passe(), Equation_base::probleme(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_Inc_base::valeurs(), valeurs_coeff_, and valeurs_coeff_grad_.
Referenced by mettre_a_jour().
coefficient_frottement() [1/2]
virtual double Paroi_frottante_simple::coefficient_frottement (int i) const inline override virtual
Reimplemented from Navier.
References valeurs_coeff_.
coefficient_frottement() [2/2]
virtual double Paroi_frottante_simple::coefficient_frottement (int i, int j) const inline override virtual
Reimplemented from Navier.
References valeurs_coeff_.
coefficient_frottement_grad() [1/2]
virtual double Paroi_frottante_simple::coefficient_frottement_grad (int i) const inline override virtual
Reimplemented from Navier.
References valeurs_coeff_grad_.
coefficient_frottement_grad() [2/2]
virtual double Paroi_frottante_simple::coefficient_frottement_grad (int i, int j) const inline override virtual
Reimplemented from Navier.
References valeurs_coeff_grad_.
liste_faces_loi_paroi()
void Paroi_frottante_simple::liste_faces_loi_paroi (IntTab & tab) override virtual
Implements Frottement_impose_base.
References Frottement_impose_base::la_frontiere_dis, and TRUSTVect< _TYPE_, _SIZE_ >::line_size().
fac_coeff_grad()
virtual double Paroi_frottante_simple::fac_coeff_grad (double y_p) const inline protected virtual
Reimplemented in Paroi_frottante_loi.
Referenced by me_calculer().
Member Data Documentation
info_obj
const Type_info Paroi_frottante_simple::info_obj static
correlation_loi_paroi_
TRUST_Ref< Correlation_base *> Paroi_frottante_simple::correlation_loi_paroi_ protected
Referenced by initialiser(), and me_calculer().
valeurs_coeff_
DoubleTab Paroi_frottante_simple::valeurs_coeff_ protected
Referenced by coefficient_frottement(), initialiser(), and me_calculer().
valeurs_coeff_grad_
DoubleTab Paroi_frottante_simple::valeurs_coeff_grad_ protected
Referenced by coefficient_frottement_grad(), initialiser(), and me_calculer().