TrioCFD: Connectivite_frontieres Class Reference
Connectivite_frontieres Class Reference
#include <Connectivite_frontieres.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Connectivite_frontieres()
Connectivite_frontieres::Connectivite_frontieres ()
~Connectivite_frontieres()
Connectivite_frontieres::~Connectivite_frontieres ()
Member Function Documentation
cree_instance()
Objet_U * Connectivite_frontieres::cree_instance () static
taille_memoire()
unsigned Connectivite_frontieres::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Connectivite_frontieres::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Connectivite_frontieres::info () static
get_info()
const Type_info * Connectivite_frontieres::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
Connectivite_frontieres & Connectivite_frontieres::self_cast (Objet_U & r) static
self_cast() [2/2]
const Connectivite_frontieres & Connectivite_frontieres::self_cast (const Objet_U & r) static
printOn()
Sortie & Connectivite_frontieres::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
References Process::exit().
readOn()
Entree & Connectivite_frontieres::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
References Process::exit().
associer_domaine_vf()
void Connectivite_frontieres::associer_domaine_vf (const Domaine_VF & domaine_vf) virtual
References refdomaine_vf_, remplir_def_face_aretes(), and remplir_faces_voisins().
Referenced by Transport_Interfaces_FT_Disc::discretiser(), and IJK_Interfaces::initialize().
faces_voisins()
const IntTab & Connectivite_frontieres::faces_voisins () const inline
References faces_voisins_, TRUST_Ref< _CLASSE_ >::non_nul(), and refdomaine_vf_.
Referenced by Parcours_interface::calculer_sortie_face_bord().
face_cond_lim()
const ArrOfInt & Connectivite_frontieres::face_cond_lim () const
def_face_aretes()
const IntTab & Connectivite_frontieres::def_face_aretes () const inline
References def_face_aretes_, TRUST_Ref< _CLASSE_ >::non_nul(), and refdomaine_vf_.
Referenced by Parcours_interface::calculer_sortie_face_bord().
remplir_def_face_aretes()
void Connectivite_frontieres::remplir_def_face_aretes (const Domaine_VF & domaine_vf) protected
References def_face_aretes_, Domaine_dis_base::domaine(), Process::exit(), Objet_U::que_suis_je(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), and Domaine_32_64< _SIZE_ >::type_elem().
Referenced by associer_domaine_vf().
remplir_faces_voisins()
void Connectivite_frontieres::remplir_faces_voisins (const Domaine_VF & domaine_vf) protected
Remplissage de faces_voisins_.
References TRUSTArray< _TYPE_, _SIZE_ >::addr(), def_face_aretes_, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Domaine_dis_base::domaine(), Process::exit(), Domaine_VF::face_sommets(), faces_voisins_, Frontiere_32_64< _SIZE_ >::get_faces_virt(), Process::me(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by associer_domaine_vf().
Member Data Documentation
info_obj
const Type_info Connectivite_frontieres::info_obj static
refdomaine_vf_
TRUST_Ref< Domaine_VF *> Connectivite_frontieres::refdomaine_vf_ protected
Referenced by associer_domaine_vf(), def_face_aretes(), and faces_voisins().
faces_voisins_
IntTab Connectivite_frontieres::faces_voisins_ protected
Referenced by faces_voisins(), and remplir_faces_voisins().
face_cond_lim_
ArrOfInt Connectivite_frontieres::face_cond_lim_ protected
def_face_aretes_
IntTab Connectivite_frontieres::def_face_aretes_ protected
Referenced by def_face_aretes(), remplir_def_face_aretes(), and remplir_faces_voisins().