TrioCFD: Traitement_particulier_NS_THI_VEF Class Reference
Traitement_particulier_NS_THI_VEF Class Reference
#include <Traitement_particulier_NS_THI_VEF.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
pour les calculs de  THI, en particulier initialisation
particuliere et calculs des spectres!!
See also
Navier_Stokes_Turbulent, Traitement_particulier_base,, Traitement_particulier_VEF
Constructor & Destructor Documentation
Traitement_particulier_NS_THI_VEF()
Traitement_particulier_NS_THI_VEF::Traitement_particulier_NS_THI_VEF ()
~Traitement_particulier_NS_THI_VEF()
Traitement_particulier_NS_THI_VEF::~Traitement_particulier_NS_THI_VEF ()
Member Function Documentation
cree_instance()
Objet_U * Traitement_particulier_NS_THI_VEF::cree_instance () static
taille_memoire()
unsigned Traitement_particulier_NS_THI_VEF::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Traitement_particulier_NS_THI_VEF::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Traitement_particulier_NS_THI_VEF::info () static
get_info()
const Type_info * Traitement_particulier_NS_THI_VEF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Traitement_particulier_NS_THI.
self_cast() [1/2]
Traitement_particulier_NS_THI_VEF & Traitement_particulier_NS_THI_VEF::self_cast (Objet_U & r) static
self_cast() [2/2]
const Traitement_particulier_NS_THI_VEF & Traitement_particulier_NS_THI_VEF::self_cast (const Objet_U & r) static
printOn()
Sortie & Traitement_particulier_NS_THI_VEF::printOn (Sortie & is) const override protected virtual
Parameters
(Sortie& is) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Traitement_particulier_NS_THI.
readOn()
Entree & Traitement_particulier_NS_THI_VEF::readOn (Entree & is) override protected virtual
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Traitement_particulier_NS_THI.
lire()
Entree & Traitement_particulier_NS_THI_VEF::lire (Entree & is) override virtual
Reimplemented from Traitement_particulier_NS_THI.
References Traitement_particulier_NS_THI::Ec_init, Process::exit(), Traitement_particulier_NS_THI::fac_init, Traitement_particulier_NS_THI::init, Process::je_suis_maitre(), Traitement_particulier_NS_base::mon_equation, Traitement_particulier_NS_THI::oui_calc_spectre, Traitement_particulier_NS_THI::oui_transf, and Motcles::search().
preparer_calcul_particulier()
void Traitement_particulier_NS_THI_VEF::preparer_calcul_particulier () override virtual
Reimplemented from Traitement_particulier_NS_THI.
References calcul_Ec_spatial(), calcul_spectre(), calcul_vitesse_moyenne(), calcul_volume_elem(), Objet_U::dimension, Traitement_particulier_NS_THI::Ec_init, Traitement_particulier_NS_THI::init, init_calc_spectre(), Process::je_suis_maitre(), Traitement_particulier_NS_base::mon_equation, Traitement_particulier_NS_THI::oui_calc_spectre, renorm_Ec(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), and sorties_globales().
post_traitement_particulier()
void Traitement_particulier_NS_THI_VEF::post_traitement_particulier () override virtual
Reimplemented from Traitement_particulier_NS_THI.
References calcul_spectre(), calcul_vitesse_moyenne(), conservation_Ec(), Traitement_particulier_NS_base::mon_equation, Traitement_particulier_NS_THI::oui_calc_spectre, and sorties_globales().
determine_tab_fft_VEF_3D()
void Traitement_particulier_NS_THI_VEF::determine_tab_fft_VEF_3D (IntTab & tab_domaine, DoubleTab & coord_domaine, IntVect & nb_coord_domaine, int & nb_spectres, int & nb_points)
References Objet_U::dimension, Process::exit(), Process::je_suis_maitre(), Traitement_particulier_NS_base::mon_equation, Domaine_VF::nb_faces(), ppcm(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), and Domaine_VF::xv().
Referenced by init_calc_spectre().
determine_tab_fft_VEF_1D()
void Traitement_particulier_NS_THI_VEF::determine_tab_fft_VEF_1D (const IntTab & tab_domaine, const DoubleTab & coord_domaine, const IntVect & nb_coord_domaine, IntVect & nb_spectres, IntVect & nb_points)
References Objet_U::dimension, Process::je_suis_maitre(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), and TRUSTVect< _TYPE_, _SIZE_ >::resize().
Referenced by init_calc_spectre().
calcul_spectre_3D()
void Traitement_particulier_NS_THI_VEF::calcul_spectre_3D (const DoubleTab & vitesse, Nom ext, double & Ec_spectre)
References ch_pour_fft_VEF_3D(), and Traitement_particulier_NS_base::mon_equation.
Referenced by calcul_spectre(), and renorm_Ec().
calcul_spectre_1D()
void Traitement_particulier_NS_THI_VEF::calcul_spectre_1D (const DoubleTab & vitesse, Nom ext, double & Ec_spectre)
References TRUSTArray< _TYPE_, _SIZE_ >::addr(), ch_pour_fft_VEF_1D(), Objet_U::dimension, and Traitement_particulier_NS_base::mon_equation.
Referenced by calcul_spectre(), and renorm_Ec().
calcul_spectre_operateur()
void Traitement_particulier_NS_THI_VEF::calcul_spectre_operateur (int , DoubleTab & , DoubleTab & , double) inline override virtual
Implements Traitement_particulier_NS_THI.
calcul_volume_elem()
double Traitement_particulier_NS_THI_VEF::calcul_volume_elem () protected
References Traitement_particulier_NS_base::mon_equation, Process::mp_sum(), Domaine_dis_base::nb_elem(), and Domaine_VF::volumes().
Referenced by preparer_calcul_particulier().
renorm_Ec()
void Traitement_particulier_NS_THI_VEF::renorm_Ec () override protected virtual
Implements Traitement_particulier_NS_THI.
References calcul_Ec_spatial(), calcul_spectre_1D(), calcul_spectre_3D(), Traitement_particulier_NS_THI::Ec_init, Process::exit(), Traitement_particulier_NS_THI::fac_init, Process::je_suis_maitre(), and Traitement_particulier_NS_base::mon_equation.
Referenced by preparer_calcul_particulier().
calcul_Ec_spatial()
double Traitement_particulier_NS_THI_VEF::calcul_Ec_spatial (const DoubleTab & vitesse, Nom ext) protected
References Domaine_VF::creer_tableau_faces(), Periodique::face_associee(), Process::je_suis_maitre(), Domaine_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Traitement_particulier_NS_base::mon_equation, TRUSTVect< _TYPE_, _SIZE_ >::mp_max_vect(), TRUSTVect< _TYPE_, _SIZE_ >::mp_min_vect(), Domaine_VF::nb_faces(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), Sortie_Fichier_base::precision(), Domaine_VF::premiere_face_int(), TRUST_Vector< _CLASSE_ >::size(), TRUST_Deriv< _CLASSE_ >::valeur(), and Domaine_VF::volumes_entrelaces().
Referenced by conservation_Ec(), preparer_calcul_particulier(), renorm_Ec(), and sorties_globales().
calcul_Df_spatial()
void Traitement_particulier_NS_THI_VEF::calcul_Df_spatial (double & Df) protected
References Champ_P1NC::cal_rot_ordre1(), Objet_U::dimension, Process::je_suis_maitre(), Traitement_particulier_NS_base::mon_equation, Process::mp_max(), Process::mp_min(), Process::mp_sum(), Domaine_dis_base::nb_elem(), Sortie_Fichier_base::precision(), and Domaine_VF::volumes().
Referenced by sorties_globales().
calcul_Sk()
void Traitement_particulier_NS_THI_VEF::calcul_Sk (DoubleTab & Sk) protected
References Objet_U::dimension, Champ_P1NC::gradient(), Process::je_suis_maitre(), Traitement_particulier_NS_base::mon_equation, Process::mp_sum(), Domaine_dis_base::nb_elem(), Domaine_dis_base::nb_elem_tot(), Sortie_Fichier_base::precision(), and Domaine_VF::volumes().
Referenced by sorties_globales().
calcul_nu_t()
void Traitement_particulier_NS_THI_VEF::calcul_nu_t () protected
References Process::je_suis_maitre(), Traitement_particulier_NS_base::mon_equation, Process::mp_max(), Process::mp_min(), Process::mp_sum(), Domaine_dis_base::nb_elem(), Sortie_Fichier_base::precision(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), Navier_Stokes_Turbulent::viscosite_turbulente(), and Domaine_VF::volumes().
Referenced by sorties_globales().
init_calc_spectre()
void Traitement_particulier_NS_THI_VEF::init_calc_spectre () override protected virtual
Implements Traitement_particulier_NS_THI.
References determine_tab_fft_VEF_1D(), determine_tab_fft_VEF_3D(), Objet_U::dimension, Traitement_particulier_NS_base::mon_equation, Domaine_dis_base::nb_elem(), Domaine_VF::nb_faces(), Process::nproc(), and suppression_vitesse_moyenne().
Referenced by preparer_calcul_particulier().
calcul_vitesse_moyenne()
void Traitement_particulier_NS_THI_VEF::calcul_vitesse_moyenne (const DoubleTab & tab_global, DoubleVect & moyenne) protected
References Periodique::face_associee(), TRUSTVect< _TYPE_, _SIZE_ >::get_md_vector(), MD_Vector_base::get_sequential_items_flags(), Domaine_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Traitement_particulier_NS_base::mon_equation, Process::mp_sum(), Domaine_VF::nb_faces(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), Domaine_VF::premiere_face_int(), TRUST_Vector< _CLASSE_ >::size(), TRUST_Deriv< _CLASSE_ >::valeur(), and Domaine_VF::volumes_entrelaces().
Referenced by calcul_spectre(), post_traitement_particulier(), preparer_calcul_particulier(), and suppression_vitesse_moyenne().
calcul_moyenne()
void Traitement_particulier_NS_THI_VEF::calcul_moyenne (const DoubleTab & tab_global, double & moyenne) protected
References Domaine_VF::creer_tableau_faces(), Periodique::face_associee(), Domaine_Cl_dis_base::les_conditions_limites(), Traitement_particulier_NS_base::mon_equation, Domaine_VF::nb_faces(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), Domaine_VF::premiere_face_int(), TRUST_Vector< _CLASSE_ >::size(), TRUST_Deriv< _CLASSE_ >::valeur(), and Domaine_VF::volumes_entrelaces().
Referenced by calcul_spectre().
impression_moyenne()
void Traitement_particulier_NS_THI_VEF::impression_moyenne () protected
References Objet_U::dimension, Process::je_suis_maitre(), Traitement_particulier_NS_base::mon_equation, and Sortie_Fichier_base::precision().
Referenced by calcul_spectre(), and suppression_vitesse_moyenne().
suppression_vitesse_moyenne()
void Traitement_particulier_NS_THI_VEF::suppression_vitesse_moyenne () protected
References calcul_vitesse_moyenne(), Objet_U::dimension, impression_moyenne(), Process::je_suis_maitre(), Traitement_particulier_NS_base::mon_equation, and Domaine_VF::nb_faces().
Referenced by init_calc_spectre().
conservation_Ec()
void Traitement_particulier_NS_THI_VEF::conservation_Ec () protected
References calcul_Ec_spatial(), Objet_U::dimension, Traitement_particulier_NS_THI::Ec_init, Process::je_suis_maitre(), Traitement_particulier_NS_base::mon_equation, and Domaine_VF::nb_faces().
Referenced by post_traitement_particulier().
calcul_spectre()
void Traitement_particulier_NS_THI_VEF::calcul_spectre () override protected virtual
Implements Traitement_particulier_NS_THI.
References calcul_moyenne(), calcul_spectre_1D(), calcul_spectre_3D(), calcul_vitesse_moyenne(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Champ_P1NC::filtrer_L2(), impression_moyenne(), Process::je_suis_maitre(), Traitement_particulier_NS_base::mon_equation, Domaine_VF::nb_faces(), Process::nproc(), TRUSTTab< _TYPE_, _SIZE_ >::ref(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), and Champ_Inc_base::valeurs().
Referenced by post_traitement_particulier(), and preparer_calcul_particulier().
calcul_correlations()
void Traitement_particulier_NS_THI_VEF::calcul_correlations (const DoubleTab & vitesse) protected
References Objet_U::dimension, Champ_P1NC::filtrer_L2(), isotropie(), Traitement_particulier_NS_base::mon_equation, Domaine_VF::nb_faces(), and Process::nproc().
Referenced by sorties_globales().
isotropie()
void Traitement_particulier_NS_THI_VEF::isotropie (const DoubleTab & vitesse, Nom ext) protected
References Process::je_suis_maitre(), Traitement_particulier_NS_base::mon_equation, and Process::nproc().
Referenced by calcul_correlations().
sorties_globales()
void Traitement_particulier_NS_THI_VEF::sorties_globales () override protected virtual
Implements Traitement_particulier_NS_THI.
References calcul_correlations(), calcul_Df_spatial(), calcul_Ec_spatial(), calcul_nu_t(), calcul_Sk(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Champ_P1NC::filtrer_L2(), Process::je_suis_maitre(), Traitement_particulier_NS_base::mon_equation, Domaine_VF::nb_faces(), Sortie_Fichier_base::precision(), and TRUSTTab< _TYPE_, _SIZE_ >::resize().
Referenced by post_traitement_particulier(), and preparer_calcul_particulier().
ch_pour_fft_VEF_3D()
void Traitement_particulier_NS_THI_VEF::ch_pour_fft_VEF_3D (const DoubleTab & tab_global, DoubleTab & tab_u, DoubleTab & tab_v, DoubleTab & tab_w, int num_spectre) const protected
Referenced by calcul_spectre_3D().
ch_pour_fft_VEF_1D()
void Traitement_particulier_NS_THI_VEF::ch_pour_fft_VEF_1D (const DoubleTab & tab_global, DoubleVect & vect_u, DoubleVect & vect_v, DoubleVect & vect_w, int dir, int num_spectre) const protected
Referenced by calcul_spectre_1D().
ppcm()
int Traitement_particulier_NS_THI_VEF::ppcm (int a, int b) protected
References pgcd().
Referenced by determine_tab_fft_VEF_3D().
pgcd()
int Traitement_particulier_NS_THI_VEF::pgcd (int a, int b) protected
Referenced by ppcm().
Member Data Documentation
info_obj
const Type_info Traitement_particulier_NS_THI_VEF::info_obj static