TrioCFD: Domaine_base Class Reference
Domaine_base Class Reference
#include <Domaine_base.h>
Public Member Functions
const Type_info * get_info () const override
const Nom & le_nom () const override
void nommer (const Nom &nom) override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
See also
Domaine class which inherits from Domaine_base and is templatized on entity index size (32 / 64b)
Constructor & Destructor Documentation
~Domaine_base()
Domaine_base::~Domaine_base () override
Member Function Documentation
info()
const Type_info * Domaine_base::info () static
get_info()
const Type_info * Domaine_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
Reimplemented in Domaine_ALE, Domaine_32_64< int >, Domaine_bord_32_64< _SIZE_ >, DomaineAxi1d_32_64< _SIZE_ >, Pave_32_64< _SIZE_ >, and Domaine_IJK.
self_cast() [1/2]
Domaine_base & Domaine_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Domaine_base & Domaine_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Domaine_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
Reimplemented in Domaine_ALE, Domaine_32_64< int >, Domaine_bord_32_64< _SIZE_ >, DomaineAxi1d_32_64< _SIZE_ >, Pave_32_64< _SIZE_ >, and Domaine_IJK.
readOn()
Entree & Domaine_base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
Reimplemented in Domaine_ALE, Domaine_32_64< int >, Domaine_bord_32_64< _SIZE_ >, DomaineAxi1d_32_64< _SIZE_ >, Pave_32_64< _SIZE_ >, and Domaine_IJK.
le_nom()
const Nom & Domaine_base::le_nom () const inline override virtual
Donne le nom de l'Objet_U Methode a surcharger : renvoie "neant" dans cette implementation.
Returns
(Nom&) le nom de l'Objet_U
Reimplemented from Objet_U.
References nom_.
Referenced by Modele_turbulence_hyd_base::a_faire(), Modele_turbulence_scal_base::a_faire(), Champ_implementation_P0::affecter_(), Rectify_Mesh::apply(), Refine_Mesh::apply(), Domaine_dis_cache::build_or_get(), Domaine_dis_cache::build_or_get_poly_post(), Champ_base::calculer_valeurs_elem_compo_post(), Champ_base::calculer_valeurs_elem_post(), Champ_base::calculer_valeurs_som_compo_post(), Champ_base::calculer_valeurs_som_post(), Terme_Boussinesq_base::check(), Reordonner_faces_periodiques_32_64< _SIZE_ >::chercher_direction_perio(), Faces_32_64< _SIZE_ >::compare(), Champ_Generique_Extraction::completer(), Champ_Generique_Interpolation::completer(), Domaine_32_64< _SIZE_ >::comprimer(), Domaine_ALE::computeFluidForceOnBeam(), Champ_front_contact_VEF::connectivity_failed(), Extruder_en3::construire_bords(), Partitionneur_Partition::construire_partition(), DomaineCutter_32_64< _SIZE_ >::construire_sous_domaine(), Corriger_frontiere_periodique_32_64< _SIZE_ >::corriger_coordonnees_sommets_perio(), Pb_MED::creer_champ(), Postraitement::creer_champ_post(), Postraitement::creer_champ_post_stat(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::data_a_sauvegarder(), DecoupeBord_32_64< _SIZE_ >::decouper(), Domaine_Poly_base::discretiser(), Postraiter_domaine::ecrire(), Format_Post_Med::ecrire_champ_med(), Champ_Generique_Reduction_0D::extraire(), TroisDto2D_32_64< _SIZE_ >::extraire_2D(), Domaine_bord_32_64< _SIZE_ >::extraire_domaine_bord(), Domaine_VF::info_elem_som(), Domaine_VF::infobord(), Postraitement::init(), Domaine_VF::init_dist_paroi_globale(), Domaine_PolyMAC::init_equiv(), Postprocessing_IJK::init_indicatrice_non_perturbe(), Postprocessing_IJK::init_integrated_and_ana(), Domaine_PolyMAC::init_m1_3d(), Domaine_PolyMAC::init_ve(), DNS_QC_double::initialise(), Switch_double::initialise(), Switch_FT_double::initialise(), Raccord_distant_homogene_32_64< _SIZE_ >::initialise(), Navier_Stokes_FTD_IJK::initialise_velocity_from_file(), Sonde::initialiser(), Champ_front_contact_VEF::initialiser(), Champ_front_calc::initialiser(), Ecrire_Champ_MED::interpreter(), Lata_2_Other::interpreter(), Extraire_surface_ALE::interpreter_(), DecoupeBord_32_64< _SIZE_ >::interpreter_(), Dilate::interpreter_(), Distanceparoi::interpreter_(), Extraire_surface::interpreter_(), RegroupeBord_32_64< _SIZE_ >::interpreter_(), VerifierCoin::interpreter_(), Pb_Couple_rayo_semi_transp::le_modele_rayo_associe(), Domaine_VEF::lecture_ok_arete(), Ensemble_Faces_base::lire(), Modele_turbulence_hyd_base::lire_distance_paroi(), ScatterMED::lire_domaine(), LireMED_32_64< _SIZE_ >::lire_geom(), Transport_Interfaces_FT_Disc::lire_maillage_ft_cao(), Decouper_multi::lire_motcle_non_standard(), Postraitement::lire_motcle_non_standard(), Modele_turbulence_hyd_base::lire_motcle_non_standard(), Modele_turbulence_scal_base::lire_motcle_non_standard(), IJK_Thermal_base::lire_temperature(), IJK_Thermal_cut_cell::lire_temperature(), NettoieNoeuds_32_64< _SIZE_ >::nettoie(), Champ_Generique_Interpolation::nommer_source(), Champ_Generique_refChamp::nommer_source(), Postraitement::postraiter_champs(), Postraitement::postraiter_tableau(), Postraitement::postraiter_tableaux(), Domaine_dis_base::rang_frontiere(), Domaine_ALE::reading_beam_model(), Domaine_IJK::readOn(), Champ_Fonc_MED::readOn(), Champ_Fonc_reprise::readOn(), Remove_elem::remove_elem_(), Champ_front_contact_VEF::remplir_connect_bords(), Navier_Stokes_std_ALE::reprendre(), Navier_Stokes_Turbulent_ALE::reprendre(), Navier_Stokes_FT_Disc::reprendre(), Equation_base::reprendre(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::reprendre(), Navier_Stokes_IBM_Turbulent::reprendre(), Navier_Stokes_std::reprendre(), Navier_Stokes_Turbulent::reprendre(), Convection_Diffusion_Fluide_Dilatable_Proto::Reprendre_WC(), DNS_QC_double::run(), Parallel_io_parameters::run_bench_read(), Champ_Fonc_base::sauvegarder(), Champ_Inc_base::sauvegarder(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::sauvegarder(), Modele_turbulence_hyd_null::sauvegarder(), Postraitement::sauvegarder(), Champ_implementation::valeur_aux_sommets(), Champ_implementation::valeur_aux_sommets_compo(), Echange_contact_VDF::verifier_correspondance(), and Switch_double::write_velocity().
nommer()
void Domaine_base::nommer (const Nom &) inline override virtual
Donne un nom a l'Objet_U Methode virtuelle a surcharger.
Parameters
(const Nom&) le nom a affectuer a l'Objet_U
Reimplemented from Objet_U.
References nom_.
Referenced by DomaineCutter_32_64< _SIZE_ >::construire_sous_domaine(), Domaine_bord_32_64< _SIZE_ >::extraire_domaine_bord(), Extraire_surface::extraire_surface_without_cleaning(), Domaine_IJK::init_subregion(), Lata_2_Other::interpreter(), Create_domain_from_sub_domain::interpreter_(), Pb_Couple_rayo_semi_transp::le_modele_rayo_associe(), ScatterMED::lire_domaine(), Postraitement_ft_lata::postprocess_field_values(), and Champ_Fonc_MED::readOn().
epsilon()
double Domaine_base::epsilon () const inline
References epsilon_.
Referenced by Corriger_frontiere_periodique_32_64< _SIZE_ >::corriger_coordonnees_sommets_perio(), Octree_32_64< _SIZE_ >::get_epsilon(), and Champ_Fonc_reprise_IJK::reprendre_IJK().
initialiser()
virtual void Domaine_base::initialiser (double temps, Domaine_dis_base & , Probleme_base &) inline virtual
Reimplemented in Domaine_ALE.
Referenced by Probleme_base_interface_proto::initialize_impl().
set_dt()
virtual void Domaine_base::set_dt (double & dt_) inline virtual
Reimplemented in Domaine_ALE.
Referenced by Probleme_base_interface_proto::initTimeStep_impl().
mettre_a_jour()
virtual void Domaine_base::mettre_a_jour (double temps, Domaine_dis_base & , Probleme_base &) inline virtual
Reimplemented in Domaine_ALE.
Referenced by Probleme_base_interface_proto::iterateTimeStep_impl(), and Pb_Dilatable_base::mettre_a_jour().
update_after_post()
virtual void Domaine_base::update_after_post (double temps) inline virtual
Reimplemented in Domaine_ALE.
associer_bords_a_imprimer()
void Domaine_base::associer_bords_a_imprimer (TRUST_List< Nom > liste) inline
References bords_a_imprimer_.
associer_bords_a_imprimer_sum()
void Domaine_base::associer_bords_a_imprimer_sum (TRUST_List< Nom > liste) inline
References bords_a_imprimer_sum_.
lire_bords_a_imprimer()
Entree & Domaine_base::lire_bords_a_imprimer (Entree & s)
References TRUST_List< _CLASSE_ >::add(), bords_a_imprimer_, and Process::exit().
Referenced by Imprimer_flux::interpreter_().
lire_bords_a_imprimer_sum()
Entree & Domaine_base::lire_bords_a_imprimer_sum (Entree & s)
References TRUST_List< _CLASSE_ >::add(), bords_a_imprimer_sum_, and Process::exit().
Referenced by Imprimer_flux_sum::interpreter_().
bords_a_imprimer()
const TRUST_List< Nom > & Domaine_base::bords_a_imprimer () const inline
References bords_a_imprimer_.
Referenced by Paroi_flux_impose_Rayo_transp::calculer_Teta_i_VDF(), Op_Grad_VEF_P1B_Face::impr(), Op_EF_base::impr(), Op_VEF_Face::impr(), Op_Grad_EF::impr(), Iterateur_PolyMAC_Elem< _TYPE_ >::impr(), Op_Conv_PolyMAC_base::impr(), Op_Diff_PolyMAC_Gen_base::impr(), and Op_Grad_VDF_Face::impr().
bords_a_imprimer_sum()
const TRUST_List< Nom > & Domaine_base::bords_a_imprimer_sum () const inline
References bords_a_imprimer_sum_.
Referenced by Op_Grad_VEF_P1B_Face::impr(), Op_EF_base::impr(), Op_VEF_Face::impr(), Op_Grad_EF::impr(), Op_Conv_PolyMAC_base::impr(), Op_Diff_PolyMAC_Gen_base::impr(), Op_Grad_VDF_Face::impr(), and Operateur_base::ouvrir_fichier().
moments_a_imprimer() [1/2]
int Domaine_base::moments_a_imprimer () const inline
References moments_a_imprimer_.
Referenced by Op_Grad_VEF_P1B_Face::impr(), Op_EF_base::impr(), Op_VEF_Face::impr(), Op_Conv_PolyMAC_base::impr(), Op_Diff_PolyMAC_Gen_base::impr(), and Calculer_Moments::interpreter_().
moments_a_imprimer() [2/2]
int & Domaine_base::moments_a_imprimer () inline
References moments_a_imprimer_.
axi1d()
bool Domaine_base::axi1d () const inline
References axi1d_.
fixer_epsilon()
void Domaine_base::fixer_epsilon (double eps) inline
References epsilon_.
Referenced by Mailler_32_64< _SIZE_ >::interpreter_().
deformable() [1/2]
bool Domaine_base::deformable () const inline
References deformable_.
Referenced by Postraitement::init(), and Postraitement::postraiter_champs().
deformable() [2/2]
bool & Domaine_base::deformable () inline
References deformable_.
set_fichier_lu()
void Domaine_base::set_fichier_lu (Nom & nom) inline
References fichier_lu_.
Referenced by Raffiner_isotrope_parallele::interpreter(), Scatter::lire_domaine(), and ScatterMED::lire_domaine().
get_fichier_lu()
const Nom & Domaine_base::get_fichier_lu () const inline
References fichier_lu_.
duplique_bords_internes()
void Domaine_base::duplique_bords_internes () protected
Member Data Documentation
info_obj
const Type_info Domaine_base::info_obj static
nom_
Nom Domaine_base::nom_ protected
Domaine name.
Referenced by Domaine_32_64< _SIZE_ >::fill_from_list(), le_nom(), Domaine_32_64< _SIZE_ >::merge_wo_vertices_with(), and nommer().
moments_a_imprimer_
int Domaine_base::moments_a_imprimer_ protected
Referenced by moments_a_imprimer().
bords_a_imprimer_
TRUST_List< Nom > Domaine_base::bords_a_imprimer_ protected
Referenced by associer_bords_a_imprimer(), bords_a_imprimer(), and lire_bords_a_imprimer().
bords_a_imprimer_sum_
TRUST_List< Nom > Domaine_base::bords_a_imprimer_sum_ protected
Referenced by associer_bords_a_imprimer_sum(), bords_a_imprimer_sum(), and lire_bords_a_imprimer_sum().
axi1d_
int Domaine_base::axi1d_ protected
Referenced by axi1d().
epsilon_
double Domaine_base::epsilon_ protected
Referenced by epsilon(), and fixer_epsilon().
deformable_
bool Domaine_base::deformable_ protected
Referenced by Domaine_ALE::clear(), and deformable().
fichier_lu_
Nom Domaine_base::fichier_lu_ protected
Referenced by get_fichier_lu(), and set_fichier_lu().
volume_total_
double Domaine_base::volume_total_ protected
Volume total du domaine (somme sur tous les processeurs)