TrioCFD: Ecrire_YAML Class Reference
Ecrire_YAML Class Reference
#include <Ecrire_YAML.h>
Detailed Description
The data that will be written are the ones that have been set in Equation_base::data_a_sauvegarder() (+overloads) and Postraitement_base::data_a_sauvegarder() (+ overloads)
These data must then be shared with PDI (during the simulation) in order to trigger the wanted IO operations, see also the class TRUST_2_PDI
The structure of the file is as follows (indentation matters!):
Metadata: mdata1 : type # for scalar mdata2 : { type: array, subtype: ..., size: ... } # for arrays ... Data: data1 : type ... Plugins: plugin1: plugin2: ...
We're using the HDF5 plugin. Here is an example of how to declare a HDF5 dataset (structure gathering data of the same type) and write our TRUST data into it:
file: filename datasets: dataset1: { type: array, subtype: ..., size: ... } #declaration of first dataset dataset2: { type: array, subtype: ..., size: ... } #declaration of second dataset ... write: data1: # TRUST data (it has to be declared in the data section first!) dataset: dataset1 # the dataset to which the data belongs dataset_selection: size: [...,...] # What is the size of the section in the dataset (for every dimension) we will work with ? start:[...,...] # Where do we want to start to write/read the data in the dataset (for every dimension)?
Constructor & Destructor Documentation
Ecrire_YAML()
Ecrire_YAML::Ecrire_YAML () inline
Member Function Documentation
write_checkpoint_file()
void Ecrire_YAML::write_checkpoint_file (const std::string & yaml_fname)
Generate the YAML file that will be read for checkpoint.
References Process::barrier(), and Process::je_suis_maitre().
Referenced by Save_Restart::sauver(), and Probleme_Couple::sauver().
write_restart_file()
void Ecrire_YAML::write_restart_file (const std::string & yaml_fname)
Generate the YAML file that will be read for restart.
References Process::barrier(), and Process::je_suis_maitre().
write_champ_fonc_restart_file()
void Ecrire_YAML::write_champ_fonc_restart_file (const std::string & filename)
Generate the YAML file that will be read with champ_fonc_reprise.
References Process::barrier(), and Process::je_suis_maitre().
add_pb_base()
void Ecrire_YAML::add_pb_base (const Probleme_base & pb_base, const Nom & file_name) inline
References Nom::find(), Nom::getString(), and Process::is_parallel().
Referenced by Save_Restart::sauver(), and Probleme_Couple::sauver().
add_field()
void Ecrire_YAML::add_field (Nom pb, Nom nom, int nb_dim)
Adds a field (name+dimension) to the block of the problem pb_name in the YAML file.
References Process::exit(), Nom::getString(), and Probleme_U::le_nom().
add_scalar()
void Ecrire_YAML::add_scalar (Nom pb, Nom nom, Nom type, bool is_local)
Adds a scalar (name+type) to the block of the problem pb_name in the YAML file.
References Process::exit(), Nom::getString(), Probleme_U::le_nom(), and YAML_data::set_local().