TrioCFD: Champ_front_var Class Reference
Champ_front_var Class Reference
#include <Champ_front_var.h>
Public Member Functions
const Type_info * get_info () const override
int initialiser (double temps, const Champ_Inc_base &inco) override
Public Member Functions inherited from Champ_front_base
virtual void associer_fr_dis_base (const Frontiere_dis_base &)
virtual int avancer (double temps)
virtual void calculer_coeffs_echange (double temps)
virtual void fixer_nb_valeurs_temporelles (int nb_cases)
virtual Frontiere_dis_base & frontiere_dis ()
virtual const Frontiere_dis_base & frontiere_dis () const
const Type_info * get_info () const override
virtual int initialiser (double temps, const Champ_Inc_base &inco)
virtual void mettre_a_jour (double temps)
virtual int reculer (double temps)
virtual const DoubleTab & valeurs () const override
virtual DoubleTab & valeurs () override
virtual void valeurs_face (int, DoubleVect &) const
Public Member Functions inherited from Field_base
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
virtual void fixer_nb_comp (int i)
virtual const Nom & fixer_nom_compo (const Nom &)
virtual const Nom & fixer_nom_compo (int, const Nom &)
virtual const Noms & fixer_noms_compo (const Noms &)
virtual const Nom & fixer_unite (const Nom &)
virtual const Nom & fixer_unite (int i, const Nom &)
virtual const Noms & fixer_unites (const Noms &)
const Type_info * get_info () const override
const Nom & nom_compo (int) const
void nommer (const Nom &) override
const Nom & unite () const
const Nom & unite (int) const
const Noms & unites () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Champ_Proto
int lire_dimension (Entree &, const Nom &)
int lire_dimension (int dim, const Nom &le_nom_)
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Field_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
une frontiere variable en espace (non uniforme).
Le DoubleTab est dimensionne au nombre de faces de la frontiere
par la methode initialiser et possede un espace virtuel.
Chaque modification du tableau de valeurs doit donc etre suivie
d'un appel a echange_espace_virtuel().
Les Champ_front_var sont classes suivant qu'ils sont
stationnaires (Champ_front_var_stationnaire) ou non
(Champ_front_var_instationnaire).
Dans le premier cas, le tableau de valeurs est rempli une fois
pour toutes par la methode initialiser. Dans le deuxieme, il
est aussi recalcule a chaque appel a mettre_a_jour.
See also
Champ_front_base Champ_Var
Constructor & Destructor Documentation
Champ_front_var()
Champ_front_var::Champ_front_var ()
~Champ_front_var()
Champ_front_var::~Champ_front_var () override
Member Function Documentation
info()
const Type_info * Champ_front_var::info () static
get_info()
const Type_info * Champ_front_var::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Champ_front_base.
Reimplemented in Ch_front_input_ALE, Champ_front_ALE, Champ_front_ALE_Beam, Champ_front_ALE_projection, Champ_front_contact_rayo_transp_VEF, Champ_front_rayonnement, Champ_front_contact_rayo_semi_transp_VEF, Boundary_field_keps_from_ud, Champ_front_var_instationnaire, Champ_front_MED, Champ_front_recyclage, Champ_front_softanalytique, Champ_front_pression_from_u, Champ_front_synt, Champ_front_debit_QC, Champ_front_debit_QC_fonc_t, Champ_front_fonc_gradient_VDF, Champ_front_contact_fictif_VEF, Champ_front_contact_VEF, Champ_front_fonc_gradient_VEF, and Champ_front_tangentiel_VEF.
self_cast() [1/2]
Champ_front_var & Champ_front_var::self_cast (Objet_U & r) static
self_cast() [2/2]
const Champ_front_var & Champ_front_var::self_cast (const Objet_U & r) static
printOn()
Sortie & Champ_front_var::printOn (Sortie & s) const override protected virtual
Imprime le nom du champ sur un flot de sortie.
Parameters
(Sortie& s) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Champ_front_base.
Reimplemented in Ch_front_input_ALE, Champ_front_ALE, Champ_front_ALE_Beam, Champ_front_ALE_projection, Champ_front_contact_rayo_transp_VEF, Champ_front_rayonnement, Champ_front_contact_rayo_semi_transp_VEF, Boundary_field_keps_from_ud, Champ_front_var_instationnaire, Champ_front_MED, Champ_front_recyclage, Champ_front_softanalytique, Champ_front_pression_from_u, Champ_front_synt, Champ_front_debit_QC, Champ_front_debit_QC_fonc_t, Champ_front_fonc_gradient_VDF, Champ_front_contact_fictif_VEF, Champ_front_contact_VEF, Champ_front_fonc_gradient_VEF, and Champ_front_tangentiel_VEF.
References Field_base::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Champ_front_var::readOn (Entree & s) override protected virtual
NE FAIT RIEN A surcharger dans les classes derivees.
Doit dans tous les cas fixer nb_comp
Parameters
(Entree& is)
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Champ_front_base.
Reimplemented in Ch_front_input_ALE, Champ_front_ALE, Champ_front_ALE_Beam, Champ_front_ALE_projection, Champ_front_contact_rayo_transp_VEF, Champ_front_rayonnement, Champ_front_contact_rayo_semi_transp_VEF, Boundary_field_keps_from_ud, Champ_front_var_instationnaire, Champ_front_MED, Champ_front_recyclage, Champ_front_softanalytique, Champ_front_pression_from_u, Champ_front_synt, Champ_front_debit_QC, Champ_front_debit_QC_fonc_t, Champ_front_fonc_gradient_VDF, Champ_front_contact_fictif_VEF, Champ_front_contact_VEF, Champ_front_fonc_gradient_VEF, and Champ_front_tangentiel_VEF.
References Field_base::fixer_nb_comp().
initialiser()
int Champ_front_var::initialiser (double temps, const Champ_Inc_base & inco) override virtual
Initialisation en debut de calcul.
Dimensionne le tableau de valeurs et cree son espace virtuel. Les classes derivees doivent imperativement appeler cette methode.
Returns
(0 en cas d'erreur, 1 sinon.)
Reimplemented from Champ_front_base.
Reimplemented in Ch_front_input_ALE, Champ_front_ALE, Champ_front_contact_rayo_transp_VEF, Champ_front_contact_rayo_semi_transp_VEF, Boundary_field_keps_from_ud, Champ_front_var_instationnaire, Champ_front_recyclage, Champ_front_softanalytique, Champ_front_pression_from_u, Champ_front_synt, Champ_front_contact_VEF, and Champ_front_tangentiel_VEF.
References Frontiere_32_64< _SIZE_ >::creer_tableau_faces(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Frontiere_dis_base::frontiere(), Champ_front_base::frontiere_dis(), Champ_front_base::les_valeurs, Roue::nb_cases(), Field_base::nb_comp(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), and TRUSTTab< _TYPE_, _SIZE_ >::resize().
Referenced by Champ_front_fonc_pois_ipsn::initialiser(), Champ_front_fonc_pois_tube::initialiser(), Champ_front_lu::initialiser(), Champ_front_var_instationnaire::initialiser(), and Champ_front_softanalytique::initialiser().
Member Data Documentation
info_obj
const Type_info Champ_front_var::info_obj static