TrioCFD: Temperature_imposee_paroi_rayo_semi_transp Class Reference
Temperature_imposee_paroi_rayo_semi_transp Class Reference
#include <Temperature_imposee_paroi_rayo_semi_transp.h>
Public Member Functions
void associer_modele (const Modele_rayo_semi_transp &) override
int compatible_avec_eqn (const Equation_base &) const override
const Type_info * get_info () const override
Public Member Functions inherited from Cond_Lim_rayo_semi_transp
virtual void associer_modele (const Modele_rayo_semi_transp &)
Modele_rayo_semi_transp & modele ()
const Modele_rayo_semi_transp & modele () const
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Dirichlet
const Type_info * get_info () const override
virtual double val_imp (int i) const
virtual double val_imp (int i, int j) const
void verifie_ch_init_nb_comp () const override
Public Member Functions inherited from Cond_lim_base
virtual int a_mettre_a_jour_ss_pas_dt ()
virtual void associer_domaine_cl_dis_base (const Domaine_Cl_dis_base &)
virtual void associer_fr_dis_base (const Frontiere_dis_base &)
virtual void calculer_coeffs_echange (double temps)
virtual int compatible_avec_discr (const Discretisation_base &) const
Domaine_Cl_dis_base & domaine_Cl_dis ()
const Domaine_Cl_dis_base & domaine_Cl_dis () const
virtual Frontiere_dis_base & frontiere_dis ()
virtual const Frontiere_dis_base & frontiere_dis () const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
void set_modifier_val_imp (int)
virtual void verifie_ch_init_nb_comp () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Cond_lim_base
void err_pas_compatible (const Discretisation_base &) const
void err_pas_compatible (const Equation_base &) const
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
uniquement pour une discretisation VEF.
Constructor & Destructor Documentation
Temperature_imposee_paroi_rayo_semi_transp()
Temperature_imposee_paroi_rayo_semi_transp::Temperature_imposee_paroi_rayo_semi_transp ()
~Temperature_imposee_paroi_rayo_semi_transp()
Temperature_imposee_paroi_rayo_semi_transp::~Temperature_imposee_paroi_rayo_semi_transp ()
Member Function Documentation
cree_instance()
Objet_U * Temperature_imposee_paroi_rayo_semi_transp::cree_instance () static
taille_memoire()
unsigned Temperature_imposee_paroi_rayo_semi_transp::taille_memoire () const override virtual
Reimplemented from Temperature_imposee_paroi.
duplique()
int Temperature_imposee_paroi_rayo_semi_transp::duplique () const override virtual
Reimplemented from Temperature_imposee_paroi.
info()
const Type_info * Temperature_imposee_paroi_rayo_semi_transp::info () static
get_info()
const Type_info * Temperature_imposee_paroi_rayo_semi_transp::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Temperature_imposee_paroi.
self_cast() [1/2]
Temperature_imposee_paroi_rayo_semi_transp & Temperature_imposee_paroi_rayo_semi_transp::self_cast (Objet_U & r) static
self_cast() [2/2]
const Temperature_imposee_paroi_rayo_semi_transp & Temperature_imposee_paroi_rayo_semi_transp::self_cast (const Objet_U & r) static
printOn()
Sortie & Temperature_imposee_paroi_rayo_semi_transp::printOn (Sortie & os) const override protected virtual
Parameters
(Sortie& os) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Temperature_imposee_paroi.
readOn()
Entree & Temperature_imposee_paroi_rayo_semi_transp::readOn (Entree & is) override protected virtual
Simple appel a: Temperature_imposee_paroi::readOn(Entree&) Lit la CL a partir d'un flot d'entree.
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Temperature_imposee_paroi.
References Temperature_imposee_paroi::readOn().
associer_modele()
void Temperature_imposee_paroi_rayo_semi_transp::associer_modele (const Modele_rayo_semi_transp & un_modele) override virtual
Associe une equation a l'objet.
Affecte le membre Cond_Lim_rayo_semi_transp::mon_modele avec l'objet passe en parametre.
Parameters
(Modele_rayo_semi_transp& modele) le modele auquel on veut s'associer
Reimplemented from Cond_Lim_rayo_semi_transp.
References Cond_Lim_rayo_semi_transp::associer_modele(), Champ_front_contact_rayo_semi_transp_VEF::associer_modele_rayo(), Cond_lim_base::le_champ_front, and TRUST_Deriv< _CLASSE_ >::valeur().
compatible_avec_eqn()
int Temperature_imposee_paroi_rayo_semi_transp::compatible_avec_eqn (const Equation_base & eqn) const override virtual
Renvoie un booleen indiquant la compatibilite des conditions aux limites avec l'equation specifiee en parametre.
Des CL de type Temperature_imposee_paroi sont compatibles avec une equation dont le domaine est la Thermique ou bien indetermine.
Parameters
(Equation_base& eqn) l'equation avec laquelle il faut verifier la compatibilite
Returns
(int) valeur booleenne, 1 si les CL sont compatibles avec l'equation 0 sinon
Reimplemented from Cond_lim_base.
References Equation_base::domaine_application(), and Cond_lim_base::err_pas_compatible().
la_cl()
const Cond_lim_base & Temperature_imposee_paroi_rayo_semi_transp::la_cl () const override virtual
Implements Cond_Lim_rayo_semi_transp.
temperature_bord()
Champ_front_base & Temperature_imposee_paroi_rayo_semi_transp::temperature_bord ()
References Cond_lim_base::le_champ_front.
Referenced by Flux_radiatif_VEF::calculer_flux_radiatif(), and Eq_rayo_semi_transp_VEF::evaluer_cl_rayonnement().
calculer_temperature_bord()
void Temperature_imposee_paroi_rayo_semi_transp::calculer_temperature_bord (double temps)
References Champ_front_contact_rayo_semi_transp_VEF::calculer_temperature_bord(), Cond_lim_base::le_champ_front, and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by Eq_rayo_semi_transp_VEF::evaluer_cl_rayonnement().
completer()
void Temperature_imposee_paroi_rayo_semi_transp::completer () override virtual
NE FAIT RIEN A surcharger dans les classes derivees.
Reimplemented from Cond_lim_base.
References Cond_lim_base::completer().
Member Data Documentation
info_obj
const Type_info Temperature_imposee_paroi_rayo_semi_transp::info_obj static