TrioCFD: Domaine_VDF Class Reference
Domaine_VDF Class Reference
#include <Domaine_VDF.h>
Public Member Functions
void discretiser () override
double dist_face_elem0 (int, int) const override
double dist_face_elem0_axi (int, int) const
double dist_face_elem1 (int, int) const override
double dist_face_elem1_axi (int, int) const
const Type_info * get_info () const override
IntVect & orientation ()
int orientation (int) const override
void reordonner (Faces &) override
Public Member Functions inherited from Domaine_VF
void build_map_mc_Cmesh (const bool with_faces) override
void build_mc_dual_mesh () const
void build_mc_face_mesh () const
void construire_face_virt_pe_num ()
int elem_faces (int i, int j) const
int face_voisins (int num_face, int i) const
const Type_info * get_info () const override
void init_dist_paroi_globale (const Conds_lim &conds_lim) override
int nb_faces_bord () const
int nb_faces_bord_tot () const
int nb_faces_internes () const
int nb_faces_tot () const
int nb_som_face () const
int premiere_face_bord () const
int premiere_face_int () const
Public Member Functions inherited from Domaine_dis_base
void associer_domaine (const Domaine &)
const Domaine & domaine () const
void ecrire_noms_bords (Sortie &) const
virtual IntTab & face_sommets ()
const Frontiere_dis_base & frontiere_dis (const Nom &) const
const Type_info * get_info () const override
int nombre_de_sous_domaines_dis () const
int rang_frontiere (const Nom &) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
    Classe instanciable qui derive de Domaine_VF.
    Cette classe contient les informations geometriques que demande
    la methode des Volumes Differences Finis.
    La classe porte un certain nombre d'informations concernant les faces
 L'ensemble des faces est numerote comme suit:
      - les faces qui sont sur un Domaine_joint apparaissent en premier
              (dans l'ordre du vecteur les_joints)
           - les faces qui sont sur un Domaine_bord apparaissent ensuite
          (dans l'ordre du vecteur les_bords)
          - les faces internes apparaissent ensuite
 A chaque face on fait correspondre un int qui indique son orientation.
 On suppose qu'a l'interieur de chaque famille de faces (bord,joint,interne)
 on trouve:
      - le bloc des faces d'equation x = cte (faces d'orientation 0)
      - le bloc des faces d'equation y = cte (faces d'orientation 1)
      - le bloc des faces d'equation z = cte (faces d'orientation 2)
 Pour le bloc des faces de bord on conserve les sous-blocs constitues par
 les faces d'un meme bord.
 On n'a pas besoin d'une numerotation particuliere des elements.
 On a introduit la notion d'arete pour le calcul des flux diffusifs et
 convectifs dans la conservation de la quantite de mouvement.
 Le tableau Qdm contient la connectivite arete/faces. Dans le tableau
 Qdm les aretes apparaissent dans l'ordre suivant:
      - bloc des aretes joints
      - bloc des aretes bord
      - bloc des aretes mixtes
      - bloc des aretes internes
 A l'interieur de chaque bloc les aretes apparaissent dans l'ordre
 suivant: aretes XY, aretes XZ et aretes YZ.
Constructor & Destructor Documentation
Domaine_VDF()
Domaine_VDF::Domaine_VDF ()
~Domaine_VDF()
Domaine_VDF::~Domaine_VDF ()
Member Function Documentation
cree_instance()
Objet_U * Domaine_VDF::cree_instance () static
taille_memoire()
unsigned Domaine_VDF::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Domaine_VDF::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Domaine_VDF::info () static
get_info()
const Type_info * Domaine_VDF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Domaine_VF.
self_cast() [1/2]
Domaine_VDF & Domaine_VDF::self_cast (Objet_U & r) static
self_cast() [2/2]
const Domaine_VDF & Domaine_VDF::self_cast (const Objet_U & r) static
printOn()
Sortie & Domaine_VDF::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Domaine_VF.
References TRUSTTab< _TYPE_, _SIZE_ >::ecrit(), and Domaine_VF::printOn().
readOn()
Entree & Domaine_VDF::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Domaine_VF.
References TRUSTTab< _TYPE_, _SIZE_ >::lit(), and Domaine_VF::readOn().
discretiser()
void Domaine_VDF::discretiser () override virtual
appel a Domaine_VF::discretiser() calcul des centres de gravite des elements
remplissage des connectivites elements/faces on reordonne les connectivites faces/elements de sorte que el1 est a gauche et el2 a droite. calcul des porosites volumiques et surfaciques generation des aretes calcul des pas du maillage
Reimplemented from Domaine_VF.
References calculer_volumes_entrelaces(), Domaine_VF::creer_tableau_faces(), Objet_U::dimension, TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Domaine_VF::discretiser(), Domaine_dis_base::domaine(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Process::exit(), Domaine_VF::face_voisins_, Objet_U::que_suis_je(), TRUSTVect< _TYPE_, _SIZE_ >::set_md_vector(), Domaine_32_64< _SIZE_ >::type_elem(), TRUST_Deriv< _CLASSE_ >::valeur(), Domaine_VF::xp(), and Domaine_VF::xv().
creer_faces()
Faces * Domaine_VDF::creer_faces () override virtual
renvoie un Faces_VDF* !
Reimplemented from Domaine_VF.
reordonner()
void Domaine_VDF::reordonner (Faces & les_faces) override virtual
Reordonne les faces internes par orientation, on doit mettre a jour tous les tableaux qui dependent des indices de faces, soit:
faces_sommets
faces_voisins
elem_faces
orientation
Domaine.faces_joint().items_communs(FACE)
Reimplemented from Domaine_VF.
References Faces_VDF::calculer_orientation(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Domaine_dis_base::domaine(), Domaine_VF::elem_faces_, Domaine_32_64< _SIZE_ >::faces_joint(), Domaine_VF::joint(), Faces_32_64< _SIZE_ >::les_sommets(), Faces_32_64< _SIZE_ >::nb_faces(), Domaine_VF::nb_faces(), Domaine_32_64< _SIZE_ >::nb_faces_frontiere(), Domaine_VF::nb_joints(), TRUSTArray< _TYPE_, _SIZE_ >::ordonne_array(), orientation(), Joint_32_64< _SIZE_ >::set_joint_item(), TRUSTVect< _TYPE_, _SIZE_ >::size(), TRUST_List< _CLASSE_ >::size(), and Faces_32_64< _SIZE_ >::voisins().
nb_faces_X()
int Domaine_VDF::nb_faces_X () const inline
Referenced by Champ_Fonc_Face_VDF::affecter_(), Terme_Source_Solide_SWIFT_VDF::calcul_moyenne(), Terme_Source_Solide_SWIFT_VDF::init_calcul_moyenne(), and Terme_Source_Canal_RANS_LES_VDF_Face::mettre_a_jour().
nb_faces_Y()
int Domaine_VDF::nb_faces_Y () const inline
Referenced by Champ_Fonc_Face_VDF::affecter_(), Terme_Source_Canal_RANS_LES_VDF_Face::init(), Terme_Source_Canal_RANS_LES_VDF_Face::init_calcul_moyenne_spat(), and Terme_Source_Canal_RANS_LES_VDF_Face::mettre_a_jour().
nb_faces_Z()
int Domaine_VDF::nb_faces_Z () const inline
Referenced by Champ_Fonc_Face_VDF::affecter_(), Terme_Source_Solide_SWIFT_VDF::calcul_moyenne(), Terme_Source_Solide_SWIFT_VDF::init_calcul_moyenne(), and Terme_Source_Canal_RANS_LES_VDF_Face::mettre_a_jour().
nb_aretes()
int Domaine_VDF::nb_aretes () const inline
Referenced by Champ_Face_VDF::calculer_dercov_axi(), Calcul_Production_K_VDF::calculer_terme_production_K_Axi(), and Calcul_Production_K_VDF::calculer_terme_production_K_BiK_Axi().
nb_aretes_joint()
int Domaine_VDF::nb_aretes_joint () const inline
nb_aretes_coin()
int Domaine_VDF::nb_aretes_coin () const inline
Referenced by Domaine_Cl_VDF::associer(), Modele_Jones_Launder_VDF::calcul_derivees_premieres_croisees(), Modele_Jones_Launder_VDF::calcul_derivees_secondes_croisees(), Champ_Face_VDF::calcul_duidxj(), Champ_Face_VDF::calcul_S_barre_sans_contrib_paroi(), Modele_turbulence_hyd_LES_VDF::calculer_fonction_structure(), Domaine_Cl_VDF::completer(), and modifier_pour_Cl().
premiere_arete_coin()
int Domaine_VDF::premiere_arete_coin () const inline
Referenced by Modele_Jones_Launder_VDF::calcul_derivees_premieres_croisees(), Modele_Jones_Launder_VDF::calcul_derivees_secondes_croisees(), Champ_Face_VDF::calcul_duidxj(), Champ_Face_VDF::calcul_S_barre_sans_contrib_paroi(), Modele_turbulence_hyd_LES_VDF::calculer_fonction_structure(), Domaine_Cl_VDF::completer(), and modifier_pour_Cl().
nb_aretes_bord()
int Domaine_VDF::nb_aretes_bord () const inline
Referenced by Domaine_Cl_VDF::associer(), Modele_Jones_Launder_VDF::calcul_derivees_premieres_croisees(), Modele_Jones_Launder_VDF::calcul_derivees_secondes_croisees(), Champ_Face_VDF::calcul_duidxj(), Champ_Face_VDF::calcul_S_barre_sans_contrib_paroi(), Champ_Face_VDF::calculer_dercov_axi(), Modele_turbulence_hyd_LES_VDF::calculer_fonction_structure(), Modele_turbulence_hyd_LES_axi_VDF::calculer_fonction_structure(), Calcul_Production_K_VDF::calculer_terme_production_K_Axi(), Calcul_Production_K_VDF::calculer_terme_production_K_BiK_Axi(), Domaine_Cl_VDF::completer(), and modifier_pour_Cl().
premiere_arete_bord()
int Domaine_VDF::premiere_arete_bord () const inline
Referenced by Modele_Jones_Launder_VDF::calcul_derivees_premieres_croisees(), Modele_Jones_Launder_VDF::calcul_derivees_secondes_croisees(), Champ_Face_VDF::calcul_duidxj(), Champ_Face_VDF::calcul_S_barre_sans_contrib_paroi(), Champ_Face_VDF::calculer_dercov_axi(), Modele_turbulence_hyd_LES_VDF::calculer_fonction_structure(), Modele_turbulence_hyd_LES_axi_VDF::calculer_fonction_structure(), Calcul_Production_K_VDF::calculer_terme_production_K_Axi(), Calcul_Production_K_VDF::calculer_terme_production_K_BiK_Axi(), Domaine_Cl_VDF::completer(), and modifier_pour_Cl().
nb_aretes_mixtes()
int Domaine_VDF::nb_aretes_mixtes () const inline
Referenced by Modele_Jones_Launder_VDF::calcul_derivees_premieres_croisees(), Modele_Jones_Launder_VDF::calcul_derivees_secondes_croisees(), Champ_Face_VDF::calcul_duidxj(), Champ_Face_VDF::calcul_S_barre_sans_contrib_paroi(), Modele_turbulence_hyd_LES_VDF::calculer_fonction_structure(), and Modele_turbulence_hyd_LES_axi_VDF::calculer_fonction_structure().
premiere_arete_mixte()
int Domaine_VDF::premiere_arete_mixte () const inline
Referenced by Modele_Jones_Launder_VDF::calcul_derivees_premieres_croisees(), Modele_Jones_Launder_VDF::calcul_derivees_secondes_croisees(), Champ_Face_VDF::calcul_duidxj(), Champ_Face_VDF::calcul_S_barre_sans_contrib_paroi(), Champ_Face_VDF::calculer_dercov_axi(), Modele_turbulence_hyd_LES_VDF::calculer_fonction_structure(), and Modele_turbulence_hyd_LES_axi_VDF::calculer_fonction_structure().
nb_aretes_internes()
int Domaine_VDF::nb_aretes_internes () const inline
Referenced by Modele_Jones_Launder_VDF::calcul_derivees_premieres_croisees(), Modele_Jones_Launder_VDF::calcul_derivees_secondes_croisees(), Champ_Face_VDF::calcul_duidxj(), Champ_Face_VDF::calcul_S_barre_sans_contrib_paroi(), Modele_turbulence_hyd_LES_VDF::calculer_fonction_structure(), Modele_turbulence_hyd_LES_axi_VDF::calculer_fonction_structure(), Source_Transport_Flux_Chaleur_Turbulente_VDF_Face::calculer_Grad_U(), and Source_Transport_Flux_Chaleur_Turbulente_VDF_Face::calculer_uiuj().
premiere_arete_interne()
int Domaine_VDF::premiere_arete_interne () const inline
Referenced by Modele_Jones_Launder_VDF::calcul_derivees_premieres_croisees(), Modele_Jones_Launder_VDF::calcul_derivees_secondes_croisees(), Champ_Face_VDF::calcul_duidxj(), Champ_Face_VDF::calcul_S_barre_sans_contrib_paroi(), Modele_turbulence_hyd_LES_VDF::calculer_fonction_structure(), Modele_turbulence_hyd_LES_axi_VDF::calculer_fonction_structure(), Source_Transport_Flux_Chaleur_Turbulente_VDF_Face::calculer_Grad_U(), Calcul_Production_K_VDF::calculer_terme_production_K_Axi(), Calcul_Production_K_VDF::calculer_terme_production_K_BiK_Axi(), and Source_Transport_Flux_Chaleur_Turbulente_VDF_Face::calculer_uiuj().
h_x()
double Domaine_VDF::h_x () const inline
Referenced by Op_Diff_VDF_Elem_base::calculer_dt_stab().
h_y()
double Domaine_VDF::h_y () const inline
Referenced by Op_Diff_VDF_Elem_base::calculer_dt_stab().
h_z()
double Domaine_VDF::h_z () const inline
Referenced by Op_Diff_VDF_Elem_base::calculer_dt_stab().
Qdm() [1/3]
int Domaine_VDF::Qdm (int num_arete, int i) const inline
Referenced by Op_Diff_VDF_Face_Axi_base::associer(), Op_Dift_VDF_Face_Axi_base::associer(), Modele_Jones_Launder_VDF::calcul_derivees_premieres_croisees(), Modele_Jones_Launder_VDF::calcul_derivees_secondes_croisees(), Champ_Face_VDF::calcul_duidxj(), Champ_Face_VDF::calcul_S_barre_sans_contrib_paroi(), Champ_Face_VDF::calculer_dercov_axi(), Modele_turbulence_hyd_LES_VDF::calculer_fonction_structure(), Modele_turbulence_hyd_LES_axi_VDF::calculer_fonction_structure(), Source_Transport_Flux_Chaleur_Turbulente_VDF_Face::calculer_Grad_U(), Calcul_Production_K_VDF::calculer_terme_production_K_Axi(), Calcul_Production_K_VDF::calculer_terme_production_K_BiK_Axi(), Source_Transport_Flux_Chaleur_Turbulente_VDF_Face::calculer_uiuj(), and Domaine_Cl_VDF::completer().
face_normales() [1/4]
double Domaine_VDF::face_normales (int num_face, int k) const inline override virtual
Reimplemented from Domaine_VF.
References Domaine_VF::face_surfaces(), and orientation().
Referenced by Modele_Jones_Launder_VDF::calcul_derivees_premieres_croisees(), ParoiVDF_TBLE_LRM::calculer_hyd(), ParoiVDF_TBLE::calculer_hyd(), ParoiVDF_TBLE::calculer_hyd_BiK(), and ParoiVDF_TBLE_LRM::calculer_hyd_BiK().
orientation() [1/3]
int Domaine_VDF::orientation (int i) const inline override virtual
inline DoubleVect& Domaine_VDF::porosite_face() {
return porosite_face_; }
inline const DoubleVect& Domaine_VDF::porosite_face() const {
return porosite_face_; }
inline DoubleVect& Domaine_VDF::porosite_elem() {
return porosite_elem_; }
inline const DoubleVect& Domaine_VDF::porosite_elem() const {
return porosite_elem_; }
inline double Domaine_VDF::porosite_elem(int i) const {
return porosite_elem_[i]; }
Reimplemented from Domaine_VF.
Referenced by Champ_Face_VDF::affecter(), Champ_Face_VDF::affecter_(), Champ_Fonc_Face_VDF::affecter_(), Op_Diff_VDF_base::ajoute_terme_pour_axi(), Op_Dift_VDF_base::ajoute_terme_pour_axi_turb(), Source_Reaction_Particules_VDF::ajouter(), Source_Transport_Flux_Chaleur_Turbulente_VDF_Face::ajouter(), Perte_Charge_Reguliere_VDF_Face::ajouter_(), Tenseur_Reynolds_Externe_VDF_Face::ajouter_blocs(), Terme_Boussinesq_VDF_Face::ajouter_blocs(), Terme_Source_Acceleration_VDF_Face::ajouter_blocs(), Terme_Source_Coriolis_VDF_Face::ajouter_blocs(), Terme_Source_inc_th_VDF_Face::ajouter_blocs(), Terme_Source_inc_VDF_Face::ajouter_blocs(), Terme_Source_Qdm_VDF_Face::ajouter_blocs(), Source_Con_Phase_field::assembler_matrice_point_fixe(), Op_Diff_VDF_Face_Axi_base::associer(), Op_Dift_VDF_Face_Axi_base::associer(), Op_Grad_VDF_Face_base::associer(), Force_Centrifuge_VDF_Face_Axi::associer_domaines(), Evaluateur_VDF::associer_domaines(), Modele_Jones_Launder_VDF::Calcul_D(), Modele_Jones_Launder_Thermique_VDF::Calcul_D(), Modele_Jones_Launder_VDF::Calcul_D_BiK(), Modele_Jones_Launder_VDF::calcul_derivees_premieres_croisees(), Modele_Jones_Launder_VDF::calcul_derivees_secondes_croisees(), Champ_Face_VDF::calcul_duidxj(), Modele_Jones_Launder_Thermique_VDF::Calcul_E(), Transport_Interfaces_FT_Disc::calcul_effort_fluide_interface(), Transport_Interfaces_FT_Disc::calcul_indicatrice_faces(), Champ_Face_VDF::calcul_S_barre_sans_contrib_paroi(), Traitement_particulier_NS_THI_VDF::calcul_skewness_ordre_2(), Transport_Interfaces_FT_Disc::calcul_tolerance_projete_monophasique(), Transport_Interfaces_FT_Disc::calcul_vitesse(), Champ_Face_VDF::calcul_y_plus(), Champ_Face_VDF::calcul_y_plus_diphasique(), Navier_Stokes_FT_Disc::calculer_delta_u_interface(), Champ_Face_VDF::calculer_dercov_axi(), Modele_turbulence_hyd_LES_VDF::calculer_fonction_structure(), Modele_turbulence_hyd_LES_axi_VDF::calculer_fonction_structure(), EDO_Pression_th_VDF::calculer_grad(), Source_Transport_Flux_Chaleur_Turbulente_VDF_Face::calculer_Grad_U(), ParoiVDF_TBLE_LRM::calculer_hyd(), Paroi_negligeable_VDF::calculer_hyd(), Paroi_std_hyd_VDF_diphasique::calculer_hyd(), Paroi_2couches_VDF::calculer_hyd(), Paroi_loi_Ciofalo_hyd_VDF::calculer_hyd(), Paroi_loi_WW_hyd_VDF::calculer_hyd(), Paroi_std_hyd_VDF::calculer_hyd(), Paroi_UTAU_IMP_VDF::calculer_hyd(), ParoiVDF_TBLE::calculer_hyd(), Paroi_std_hyd_VDF::calculer_hyd_BiK(), Paroi_UTAU_IMP_VDF::calculer_hyd_BiK(), ParoiVDF_TBLE::calculer_hyd_BiK(), ParoiVDF_TBLE_LRM::calculer_hyd_BiK(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calculer_length_scale(), Modele_turbulence_hyd_LES_VDF_base::calculer_longueurs_caracteristiques(), Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_vitesse(), Paroi_std_hyd_VDF::calculer_moyennes_parois(), Loi_Paroi_Nu_Impose_VDF::calculer_scal(), Paroi_std_scal_hyd_VDF::calculer_scal(), Paroi_TBLE_scal_VDF::calculer_scal(), Calcul_Production_K_VDF::calculer_terme_production_K(), Calcul_Production_K_VDF::calculer_terme_production_K_BiK(), Calcul_Production_K_VDF::calculer_terme_production_K_for_komega(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_W_VDF_Elem::calculer_u_teta_W(), Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::calculer_u_teta_W(), Source_Transport_Fluctuation_Temperature_W_VDF_Elem::calculer_u_teta_W(), Source_Transport_Flux_Chaleur_Turbulente_VDF_Face::calculer_uiuj(), Terme_Source_Acceleration_VDF_Face::calculer_vitesse_faces(), Traitement_particulier_NS_THI_VDF::ch_vit_pour_fft(), Traitement_particulier_NS_THI_VDF::ch_vit_pour_fft_operateur(), Paroi_std_hyd_VDF::compute_law_komega(), Triple_Line_Model_FT_Disc::compute_TCL_fluxes_in_all_boundary_cells(), Op_VDF_Face::dimensionner(), Post_Processing_Hydrodynamic_Forces_Stokes::fill_Stokes_velocity_field(), Transport_Interfaces_FT_Disc::get_expression_vitesse_imposee(), Triple_Line_Model_FT_Disc::get_theta_app(), Domaine_Cl_VDF::imposer_cond_lim(), Transport_Interfaces_FT_Disc::impr_effort_fluide_interface(), ParoiVDF_TBLE::imprimer_ustar(), ParoiVDF_TBLE_LRM::imprimer_ustar(), Traitement_particulier_NS_Profils_VDF::init_calcul_moyenne(), Terme_Source_Canal_RANS_LES_VDF_Face::init_calcul_moyenne_spat(), ParoiVDF_TBLE::init_lois_paroi(), ParoiVDF_TBLE_LRM::init_lois_paroi(), Transport_Interfaces_FT_Disc::interpoler_vitesse_face(), Champ_front_fonc_gradient_VDF::mettre_a_jour(), Sortie_libre_Pression_imposee_Orlansky::mettre_a_jour(), Terme_Source_Canal_RANS_LES_VDF_Face::mettre_a_jour(), Op_VDF_Face::modifier_pour_Cl(), AssembleurPVDF_PF::modifier_secmem_vitesse_imposee(), Assembleur_P_VDF::modifier_secmem_vitesse_imposee(), Terme_Source_Canal_RANS_LES_VDF_Face::moy_spat(), Transport_Interfaces_FT_Disc::projete_point_face_fluide(), Transport_Interfaces_FT_Disc::projete_point_face_interface(), Perte_Charge_Singuliere_VDF_Face::remplir_num_faces(), Collision_Model_FT_base::set_geometric_parameters(), and Champ_Face_VDF_implementation::trace().
dist_face()
double Domaine_VDF::dist_face (int fac1, int fac2, int k) const inline
References Domaine_VF::xv_.
Referenced by Modele_Jones_Launder_VDF::calcul_derivees_premieres_croisees(), Modele_Jones_Launder_VDF::calcul_derivees_secondes_croisees(), Champ_Face_VDF::calcul_duidxj(), Modele_Jones_Launder_Thermique_VDF::Calcul_E(), Traitement_particulier_NS_THI_VDF::calcul_skewness_ordre_2(), Op_Diff_K_Eps_Bas_Re_VDF_var_Elem::calculer_dt_stab(), Op_Dift_Multiphase_VDF_Elem::calculer_dt_stab(), Op_Dift_VDF_Elem_base::calculer_dt_stab_elem(), Source_Transport_Flux_Chaleur_Turbulente_VDF_Face::calculer_Grad_U(), Source_Transport_Flux_Chaleur_Turbulente_VDF_Face::calculer_uiuj(), Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_face(), Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_face_sommets(), and Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_gradU_face().
dist_norm()
double Domaine_VDF::dist_norm (int num_face) const inline override virtual
Reimplemented from Domaine_VF.
References Domaine_VF::face_voisins_, and Domaine_VF::xp_.
Referenced by Source_Transport_Flux_Chaleur_Turbulente_VDF_Face::ajouter(), ParoiVDF_TBLE_LRM::calculer_hyd(), ParoiVDF_TBLE_LRM::calculer_hyd_BiK(), Source_Transport_Fluctuation_Temperature_VDF_Elem::calculer_Prod_uteta_T(), Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::calculer_Prod_uteta_T(), Source_Transport_Fluctuation_Temperature_W_VDF_Elem::calculer_Prod_uteta_T(), Calcul_Production_K_VDF::calculer_u_conc(), Calcul_Production_K_VDF::calculer_u_teta(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_W_VDF_Elem::calculer_u_teta_W(), Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::calculer_u_teta_W(), and Source_Transport_Fluctuation_Temperature_W_VDF_Elem::calculer_u_teta_W().
dist_norm_bord() [1/2]
double Domaine_VDF::dist_norm_bord (int num_face) const inline override virtual
Reimplemented from Domaine_VF.
References Domaine_VF::face_voisins_, Domaine_VF::nb_faces_bord(), Domaine_VF::xp_, and Domaine_VF::xv_.
Referenced by Source_Transport_Flux_Chaleur_Turbulente_VDF_Face::ajouter(), Modele_Jones_Launder_VDF::Calcul_D(), Modele_Jones_Launder_Thermique_VDF::Calcul_D(), Modele_Jones_Launder_VDF::Calcul_D_BiK(), Modele_Jones_Launder_VDF::calcul_derivees_premieres_croisees(), Champ_Face_VDF::calcul_duidxj(), Modele_Jones_Launder_Thermique_VDF::Calcul_E(), Champ_Face_VDF::calcul_S_barre_sans_contrib_paroi(), Champ_Face_VDF::calcul_y_plus(), Champ_Face_VDF::calcul_y_plus_diphasique(), Flux_radiatif_VDF::calculer_flux_radiatif(), Echange_contact_Correlation_VDF::calculer_h_solide(), ParoiVDF_TBLE_LRM::calculer_hyd(), Paroi_negligeable_VDF::calculer_hyd(), Paroi_std_hyd_VDF_diphasique::calculer_hyd(), Paroi_loi_Ciofalo_hyd_VDF::calculer_hyd(), Paroi_loi_WW_hyd_VDF::calculer_hyd(), Paroi_std_hyd_VDF::calculer_hyd(), ParoiVDF_TBLE::calculer_hyd(), Paroi_std_hyd_VDF::calculer_hyd_BiK(), ParoiVDF_TBLE::calculer_hyd_BiK(), ParoiVDF_TBLE_LRM::calculer_hyd_BiK(), Source_Transport_Fluctuation_Temperature_VDF_Elem::calculer_Prod_uteta_T(), Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::calculer_Prod_uteta_T(), Source_Transport_Fluctuation_Temperature_W_VDF_Elem::calculer_Prod_uteta_T(), Paroi_loi_WW_scal_VDF::calculer_scal(), Paroi_std_scal_hyd_VDF::calculer_scal(), Paroi_TBLE_scal_VDF::calculer_scal(), Neumann_paroi_rayo_semi_transp_VDF::calculer_temperature_bord(), Paroi_flux_impose_Rayo_transp::calculer_Teta_i_VDF(), Calcul_Production_K_VDF::calculer_u_conc(), Calcul_Production_K_VDF::calculer_u_teta(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_W_VDF_Elem::calculer_u_teta_W(), Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::calculer_u_teta_W(), Source_Transport_Fluctuation_Temperature_W_VDF_Elem::calculer_u_teta_W(), Paroi_std_hyd_VDF::compute_law_komega(), Paroi_scal_hyd_base_VDF::compute_nusselt(), dist_norm_bord(), Flux_radiatif_VDF::evaluer_cl_rayonnement(), ParoiVDF_TBLE::init_lois_paroi(), ParoiVDF_TBLE_LRM::init_lois_paroi(), Paroi_ODVM_scal_VDF::init_lois_paroi(), Paroi_TBLE_scal_VDF::init_lois_paroi(), Paroi_scal_hyd_base_VDF::init_lois_paroi(), T_paroi_Champ_P0_VDF::me_calculer(), Champ_front_fonc_gradient_VDF::mettre_a_jour(), PlaqThVDF::mettre_a_jour(), Eq_rayo_semi_transp_VDF::modifier_matrice(), and Echange_interne_impose::update_inv_lambda().
dist_face_elem0()
double Domaine_VDF::dist_face_elem0 (int num_face, int n0) const inline override virtual
Fonction de calcul utilisable uniquement en coordonnees cartesiennes de la distance entre le centre d'une face et.
le centre de face_voisins(face,0)
Reimplemented from Domaine_VF.
References Domaine_VF::xp_, and Domaine_VF::xv_.
Referenced by Triple_Line_Model_FT_Disc::completer(), Triple_Line_Model_FT_Disc::compute_TCL_fluxes_in_all_boundary_cells(), and Triple_Line_Model_FT_Disc::get_theta_app().
dist_face_elem1()
double Domaine_VDF::dist_face_elem1 (int num_face, int n1) const inline override virtual
Fonction de calcul utilisable uniquement en coordonnees cartesiennes de la distance entre le centre d'une face et.
le centre de face_voisins(face,1)
Reimplemented from Domaine_VF.
References Domaine_VF::xp_, and Domaine_VF::xv_.
dist_face_axi()
double Domaine_VDF::dist_face_axi (int fac1, int fac2, int k) const inline
References Domaine_VF::xv_.
Referenced by Op_Dift_VDF_Elem_base::calculer_dt_stab_elem_axi(), Op_Dift_VDF_Elem_base::calculer_dt_stab_elem_var_axi(), Modele_turbulence_hyd_LES_axi_VDF::calculer_fonction_structure(), and Modele_turbulence_hyd_LES_axi_VDF::calculer_viscosite_turbulente().
dist_face_period()
double Domaine_VDF::dist_face_period (int fac1, int fac2, int k) const inline
References Domaine_32_64< _SIZE_ >::coord_sommets(), Domaine_dis_base::domaine(), Domaine_VF::face_sommets(), and Domaine_VF::xv_.
Referenced by Champ_Face_VDF::calcul_duidxj(), and Champ_Face_VDF::calcul_S_barre_sans_contrib_paroi().
dist_norm_period()
double Domaine_VDF::dist_norm_period (int num_face, double l) const inline
References Domaine_VF::face_voisins_, and Domaine_VF::xp_.
dist_face_elem0_period()
double Domaine_VDF::dist_face_elem0_period (int num_face, int n0, double l) const inline override virtual
Reimplemented from Domaine_VF.
References Domaine_VF::xp_, and Domaine_VF::xv_.
dist_face_elem1_period()
double Domaine_VDF::dist_face_elem1_period (int num_face, int n1, double l) const inline override virtual
Reimplemented from Domaine_VF.
References Domaine_VF::xp_, and Domaine_VF::xv_.
dist_norm_axi()
double Domaine_VDF::dist_norm_axi (int num_face) const inline
References Domaine_VF::face_voisins_, and Domaine_VF::xp_.
Referenced by Source_Transport_Fluctuation_Temperature_VDF_Elem::calculer_Prod_uteta_T(), Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::calculer_Prod_uteta_T(), Source_Transport_Fluctuation_Temperature_W_VDF_Elem::calculer_Prod_uteta_T(), Calcul_Production_K_VDF::calculer_u_conc(), Calcul_Production_K_VDF::calculer_u_teta(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_W_VDF_Elem::calculer_u_teta_W(), Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::calculer_u_teta_W(), and Source_Transport_Fluctuation_Temperature_W_VDF_Elem::calculer_u_teta_W().
dist_norm_bord_axi()
double Domaine_VDF::dist_norm_bord_axi (int num_face) const inline
References Domaine_VF::face_voisins_, Domaine_VF::nb_faces_bord(), Domaine_VF::xp_, and Domaine_VF::xv_.
Referenced by Champ_Face_VDF::calcul_y_plus(), Champ_Face_VDF::calcul_y_plus_diphasique(), ParoiVDF_TBLE_LRM::calculer_hyd(), Paroi_negligeable_VDF::calculer_hyd(), Paroi_std_hyd_VDF_diphasique::calculer_hyd(), Paroi_loi_Ciofalo_hyd_VDF::calculer_hyd(), Paroi_loi_WW_hyd_VDF::calculer_hyd(), Paroi_std_hyd_VDF::calculer_hyd(), ParoiVDF_TBLE::calculer_hyd(), Paroi_std_hyd_VDF::calculer_hyd_BiK(), ParoiVDF_TBLE::calculer_hyd_BiK(), ParoiVDF_TBLE_LRM::calculer_hyd_BiK(), Source_Transport_Fluctuation_Temperature_VDF_Elem::calculer_Prod_uteta_T(), Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::calculer_Prod_uteta_T(), Source_Transport_Fluctuation_Temperature_W_VDF_Elem::calculer_Prod_uteta_T(), Paroi_loi_WW_scal_VDF::calculer_scal(), Paroi_std_scal_hyd_VDF::calculer_scal(), Paroi_TBLE_scal_VDF::calculer_scal(), Calcul_Production_K_VDF::calculer_u_conc(), Calcul_Production_K_VDF::calculer_u_teta(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_W_VDF_Elem::calculer_u_teta_W(), Source_Transport_Fluctuation_Temperature_W_Bas_Re_VDF_Elem::calculer_u_teta_W(), Source_Transport_Fluctuation_Temperature_W_VDF_Elem::calculer_u_teta_W(), Paroi_std_hyd_VDF::compute_law_komega(), Paroi_scal_hyd_base_VDF::compute_nusselt(), dist_norm_bord(), ParoiVDF_TBLE::init_lois_paroi(), ParoiVDF_TBLE_LRM::init_lois_paroi(), Paroi_ODVM_scal_VDF::init_lois_paroi(), Paroi_TBLE_scal_VDF::init_lois_paroi(), Paroi_scal_hyd_base_VDF::init_lois_paroi(), T_paroi_Champ_P0_VDF::me_calculer(), and Champ_front_fonc_gradient_VDF::mettre_a_jour().
dist_face_elem0_axi()
double Domaine_VDF::dist_face_elem0_axi (int num_face, int n0) const inline
Fonction de calcul utilisable uniquement en coordonnees cylindriques de la distance entre le centre d'une face et.
le centre de face_voisins(face,0)
References Domaine_VF::xp_, and Domaine_VF::xv_.
dist_face_elem1_axi()
double Domaine_VDF::dist_face_elem1_axi (int num_face, int n1) const inline
Fonction de calcul utilisable uniquement en coordonnees cylindriques de la distance entre le centre d'une face et le centre.
de face_voisins(face,1)
References Domaine_VF::xp_, and Domaine_VF::xv_.
distance_face()
double Domaine_VDF::distance_face (int n1, int n2, int k) const inline
References Objet_U::axi, and Domaine_VF::xv_.
Referenced by Transport_Interfaces_FT_Disc::calcul_tolerance_projete_diphasique(), and Transport_Interfaces_FT_Disc::calcul_tolerance_projete_monophasique().
distance_normale()
double Domaine_VDF::distance_normale (int num_face) const inline
References Objet_U::axi, Domaine_VF::face_voisins_, Domaine_VF::xp_, and Domaine_VF::xv_.
Referenced by Source_Transport_K_KEps_VDF_Elem::ajouter_blocs(), and Paroi_2couches_VDF::calculer_hyd().
dist_elem()
double Domaine_VDF::dist_elem (int n1, int n2, int k) const inline
References Domaine_VF::xp_.
Referenced by Post_Processing_Hydrodynamic_Forces::compute_friction_force_projected_tensor(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_friction_force_projected_tensor(), Post_Processing_Hydrodynamic_Forces::compute_heat_transfer(), Post_Processing_Hydrodynamic_Forces::compute_neighbors_coordinates_fluid_fa7(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_neighbors_coordinates_fluid_fa7(), Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_elem(), Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_gradU_elem(), and Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_gradU_elem_P1().
dist_elem_period()
double Domaine_VDF::dist_elem_period (int n1, int n2, int k) const inline
References Objet_U::dimension, Domaine_VF::elem_faces(), Domaine_VF::xp_, and Domaine_VF::xv_.
Referenced by Modele_Jones_Launder_VDF::Calcul_D(), Modele_Jones_Launder_VDF::Calcul_D_BiK(), Modele_turbulence_hyd_LES_selectif_mod_VDF::cutoff(), and Modele_turbulence_hyd_LES_selectif_VDF::cutoff().
dim_elem()
double Domaine_VDF::dim_elem (int n1, int k) const inline
References Objet_U::dimension, Domaine_VF::elem_faces_, and Domaine_VF::xv_.
Referenced by Terme_Source_inc_th_VDF_Face::ajouter_blocs(), Terme_Source_inc_VDF_Face::ajouter_blocs(), Champ_Face_VDF::calcul_duidxj(), Modele_Jones_Launder_VDF::Calcul_E(), Champ_Face_VDF::calcul_S_barre_sans_contrib_paroi(), Op_Dift_VDF_Face_base::calculer_borne_locale(), Op_Dift_Multiphase_VDF_Face::calculer_dt_stab(), Op_Dift_VDF_Face_base::calculer_dt_stab(), Op_Diff_VDF_base::calculer_dt_stab_(), Modele_turbulence_hyd_LES_VDF::calculer_fonction_structure(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calculer_length_scale(), Modele_turbulence_hyd_LES_VDF_base::calculer_longueurs_caracteristiques(), Paroi_std_hyd_VDF::calculer_moyennes_parois(), Paroi_std_scal_hyd_VDF::calculer_scal(), Modele_turbulence_hyd_LES_SMAGO_DYN_VDF::calculer_Sij_vel_filt(), Calcul_Production_K_VDF::calculer_terme_production_K(), Calcul_Production_K_VDF::calculer_terme_production_K_BiK(), Calcul_Production_K_VDF::calculer_terme_production_K_for_komega(), calculer_volumes_entrelaces(), Triple_Line_Model_FT_Disc::compute_approximate_interface_inout(), Modele_turbulence_hyd_LES_selectif_mod_VDF::cutoff(), delta_C(), dim_face(), Triple_Line_Model_FT_Disc::get_in_out_coords(), and EDO_Pression_th_VDF_Gaz_Reel::resoudre().
dim_face()
double Domaine_VDF::dim_face (int n1, int k) const inline
References dim_elem(), and Domaine_VF::face_voisins_.
delta_C()
double Domaine_VDF::delta_C (int elem) const inline
References dim_elem(), and Objet_U::dimension.
amont_amont()
int Domaine_VDF::amont_amont (int num_face, int i) const inline
References Objet_U::dimension, Domaine_VF::elem_faces_, and Domaine_VF::face_voisins_.
face_amont_princ()
int Domaine_VDF::face_amont_princ (int num_face, int i) const inline
References Objet_U::dimension, Domaine_VF::elem_faces_, Domaine_VF::face_voisins_, and orientation().
Referenced by Op_VDF_Face::dimensionner().
face_amont_conj()
int Domaine_VDF::face_amont_conj (int num_face, int k, int i) const inline
References Objet_U::dimension, Domaine_VF::elem_faces_, Domaine_VF::face_voisins_, and orientation().
face_bord_amont()
int Domaine_VDF::face_bord_amont (int num_face, int k, int i) const inline
Determine la face voisine de notre face en prevoyant que cette derniere puisse etre de type bord.
References Objet_U::dimension, Domaine_VF::elem_faces_, Domaine_VF::face_voisins_, and orientation().
Referenced by Op_VDF_Face::dimensionner().
elem_voisin()
int Domaine_VDF::elem_voisin (int elem, int face, int indic) const inline
References Objet_U::dimension, Domaine_VF::elem_faces_, and Domaine_VF::face_voisins_.
Referenced by Modele_turbulence_hyd_LES_VDF::calculer_fonction_structure(), Modele_turbulence_hyd_LES_axi_VDF::calculer_fonction_structure(), and Traitement_particulier_NS_canal_VDF::remplir_Tab_recap().
orientation() [2/3]
IntVect & Domaine_VDF::orientation () inline
inline double Domaine_VDF::porosite_face(int i) const {
return porosite_face_[i]; }
Referenced by face_amont_conj(), face_amont_princ(), face_bord_amont(), face_normales(), and reordonner().
orientation() [3/3]
const IntVect & Domaine_VDF::orientation () const inline override virtual
Reimplemented from Domaine_VF.
Qdm() [2/3]
IntTab & Domaine_VDF::Qdm () inline
Qdm() [3/3]
const IntTab & Domaine_VDF::Qdm () const inline
calculer_volumes_entrelaces()
void Domaine_VDF::calculer_volumes_entrelaces ()
remplissage des volumes entrelaces
References Objet_U::axi, Objet_U::bidim_axi, Domaine_VF::creer_tableau_faces(), dim_elem(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_VF::face_voisins_, Domaine_VF::nb_faces(), Domaine_VF::premiere_face_int(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Domaine_VF::volumes(), Domaine_VF::volumes_entrelaces_, Domaine_VF::volumes_entrelaces_dir_, Domaine_VF::xp(), Domaine_VF::xv(), and Domaine_VF::xv_.
Referenced by discretiser().
modifier_pour_Cl()
void Domaine_VDF::modifier_pour_Cl (const Conds_lim & cl) override virtual
Reimplemented from Domaine_VF.
References Objet_U::dimension, Cond_lim_base::domaine_Cl_dis(), Domaine_VF::elem_faces(), Domaine_VF::face_voisins(), TypeAreteCoinVDF::FLUIDE_FLUIDE, TypeAreteCoinVDF::FLUIDE_PAROI, Cond_lim_base::frontiere_dis(), Domaine_VF::marquer_faces_double_contrib(), Domaine_VF::modifier_pour_Cl(), nb_aretes_bord(), nb_aretes_coin(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), TypeAreteCoinVDF::PAROI_FLUIDE, TypeAreteCoinVDF::PERIO_FLUIDE, TypeAreteCoinVDF::PERIO_PAROI, TypeAreteBordVDF::PERIO_PERIO, TypeAreteCoinVDF::PERIO_PERIO, premiere_arete_bord(), premiere_arete_coin(), TRUST_Vector< _CLASSE_ >::size(), Domaine_Cl_VDF::type_arete_bord(), and Domaine_Cl_VDF::type_arete_coin().
creer_elements_fictifs()
void Domaine_VDF::creer_elements_fictifs (const Domaine_Cl_dis_base & zcldisbase) override virtual
remplit le tableau face_voisins_fictifs_ ne CREE PAS d elts fictifs!!!
Reimplemented from Domaine_dis_base.
References Domaine_VF::face_voisins(), Domaine_VF::face_voisins_fictifs_, Domaine_Cl_dis_base::les_conditions_limites(), Domaine_dis_base::nb_elem(), Domaine_dis_base::nb_elem_tot(), Front_VF::nb_faces(), Domaine_VF::nb_faces_bord(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTVect< _TYPE_, _SIZE_ >::size(), and TRUST_Deriv< _CLASSE_ >::valeur().
dist_norm_bord() [2/2]
DoubleVect & Domaine_VDF::dist_norm_bord (DoubleVect & dist, const Nom & nom_bord) const
References Objet_U::axi, dist_norm_bord(), dist_norm_bord_axi(), Domaine_VF::front_VF(), Frontiere_dis_base::le_nom(), Domaine_VF::les_bords_, Front_VF::nb_faces(), Front_VF::num_premiere_face(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), and TRUST_Vector< _CLASSE_ >::size().
init_virt_e_map()
void Domaine_VDF::init_virt_e_map () const
References Domaine_32_64< _SIZE_ >::creer_tableau_elements(), Domaine_dis_base::domaine(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Process::me(), Domaine_dis_base::nb_elem(), Domaine_dis_base::nb_elem_tot(), and virt_e_map.
Referenced by Echange_contact_VDF::initialiser().
face_normales() [2/4]
virtual double Domaine_VF::face_normales (int face, int comp) const inline virtual
Reimplemented from Domaine_VF.
face_normales() [3/4]
virtual DoubleTab & Domaine_VF::face_normales () inline virtual
Reimplemented from Domaine_VF.
face_normales() [4/4]
virtual const DoubleTab & Domaine_VF::face_normales () const inline virtual
Reimplemented from Domaine_VF.
Member Data Documentation
info_obj
const Type_info Domaine_VDF::info_obj static
virt_e_map
std::map<std::array<int, 2>, int> Domaine_VDF::virt_e_map mutable
Referenced by init_virt_e_map(), and Echange_contact_VDF::initialiser().