TrioCFD: Tube_base Class Reference
Tube_base Class Reference abstract
#include <Tube_base.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Tube_base()
Tube_base::Tube_base ()
~Tube_base()
Tube_base::~Tube_base () override
Member Function Documentation
info()
const Type_info * Tube_base::info () static
get_info()
const Type_info * Tube_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
Reimplemented in Tube_impose, and Tube_libre.
self_cast() [1/2]
Tube_base & Tube_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Tube_base & Tube_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Tube_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
Reimplemented in Tube_impose, and Tube_libre.
readOn()
Entree & Tube_base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
Reimplemented in Tube_impose, and Tube_libre.
initialize()
void Tube_base::initialize (const Domaine_IJK & x)
References ref_domaine_.
get_current_pos()
const Vecteur3 & Tube_base::get_current_pos () const inline
References pos_.
Referenced by Couplage_Tubes_IBC::calcul_F_pression(), Couplage_Tubes_IBC::calcul_F_pression2(), Couplage_Tubes_IBC::force_ibc_velocity(), Couplage_Tubes_IBC::force_ibc_velocity_anticipe_cube(), Couplage_Tubes_IBC::force_ibc_velocity_frac_vol(), Couplage_Tubes_IBC::force_ibc_velocity_miroir(), Couplage_Tubes_IBC::force_ibc_velocity_symetrie_plane(), Couplage_Tubes_IBC::ibc0_force_cube(), Couplage_Tubes_IBC::ibc0_velocity_cube(), Couplage_Tubes_IBC::ibc_diffuse_force_cube(), Couplage_Tubes_IBC::ibc_diffuse_velocity_cube(), Couplage_Tubes_IBC::ibc_localisee_velocity_cube(), and Couplage_Tubes_IBC::ibc_localisee_velocity_cube_qdm().
get_current_velocity()
const Vecteur3 & Tube_base::get_current_velocity () const inline
References v_.
Referenced by Couplage_Tubes_IBC::force_ibc_velocity(), Couplage_Tubes_IBC::force_ibc_velocity_anticipe_cube(), Couplage_Tubes_IBC::force_ibc_velocity_frac_vol(), Couplage_Tubes_IBC::force_ibc_velocity_miroir(), Couplage_Tubes_IBC::force_ibc_velocity_symetrie_plane(), Couplage_Tubes_IBC::ibc0_force_cube(), Couplage_Tubes_IBC::ibc0_velocity_cube(), Couplage_Tubes_IBC::ibc_diffuse_force_cube(), Couplage_Tubes_IBC::ibc_diffuse_velocity_cube(), Couplage_Tubes_IBC::ibc_localisee_velocity_cube(), and Couplage_Tubes_IBC::ibc_localisee_velocity_cube_qdm().
get_current_acceleration()
const Vecteur3 & Tube_base::get_current_acceleration () const inline
References acceleration_.
get_omega()
double Tube_base::get_omega () const inline
References omega_.
Referenced by Couplage_Tubes_IBC::force_ibc_velocity(), Couplage_Tubes_IBC::force_ibc_velocity_anticipe_cube(), Couplage_Tubes_IBC::force_ibc_velocity_frac_vol(), Couplage_Tubes_IBC::force_ibc_velocity_miroir(), Couplage_Tubes_IBC::ibc0_force_cube(), Couplage_Tubes_IBC::ibc0_velocity_cube(), Couplage_Tubes_IBC::ibc_diffuse_force_cube(), Couplage_Tubes_IBC::ibc_diffuse_velocity_cube(), Couplage_Tubes_IBC::ibc_localisee_velocity_cube(), and Couplage_Tubes_IBC::ibc_localisee_velocity_cube_qdm().
get_rayon()
double Tube_base::get_rayon () const inline
References rayon_.
Referenced by Couplage_Tubes_IBC::calcul_F_pression(), Couplage_Tubes_IBC::calcul_F_pression2(), Couplage_Tubes_IBC::force_ibc_velocity(), Couplage_Tubes_IBC::force_ibc_velocity_frac_vol(), Couplage_Tubes_IBC::force_ibc_velocity_miroir(), and Couplage_Tubes_IBC::force_ibc_velocity_symetrie_plane().
update_vitesse_position()
virtual void Tube_base::update_vitesse_position (double current_time, double dt, const Vecteur3 & force_appliquee) pure virtual
Implemented in Tube_impose, and Tube_libre.
nom_du_tube()
const Nom & Tube_base::nom_du_tube () const inline
References nom_.
Member Data Documentation
info_obj
const Type_info Tube_base::info_obj static
ref_domaine_
TRUST_Ref< Domaine_IJK *> Tube_base::ref_domaine_ protected
Referenced by initialize(), and Tube_libre::update_vitesse_position().
omega_
double Tube_base::omega_ protected
Referenced by get_omega(), Tube_impose::printOn(), Tube_libre::printOn(), Tube_impose::readOn(), and Tube_libre::readOn().
rayon_
double Tube_base::rayon_ protected
Referenced by get_rayon(), Tube_impose::printOn(), Tube_libre::printOn(), Tube_impose::readOn(), Tube_libre::readOn(), and Tube_libre::update_vitesse_position().
pos_
Vecteur3 Tube_base::pos_ protected
Referenced by get_current_pos(), Tube_impose::printOn(), Tube_libre::printOn(), Tube_libre::readOn(), Tube_impose::update_vitesse_position(), and Tube_libre::update_vitesse_position().
v_
Vecteur3 Tube_base::v_ protected
Referenced by get_current_velocity(), Tube_impose::printOn(), Tube_libre::printOn(), Tube_libre::readOn(), Tube_impose::update_vitesse_position(), and Tube_libre::update_vitesse_position().
acceleration_
Vecteur3 Tube_base::acceleration_ protected
Referenced by get_current_acceleration(), Tube_impose::printOn(), Tube_libre::printOn(), Tube_libre::readOn(), Tube_impose::update_vitesse_position(), and Tube_libre::update_vitesse_position().
nom_
Nom Tube_base::nom_ protected
Referenced by nom_du_tube(), Tube_impose::printOn(), Tube_libre::printOn(), Tube_impose::readOn(), and Tube_libre::readOn().