TrioCFD: Modele_turbulence_hyd_LES_VDF Class Reference
Modele_turbulence_hyd_LES_VDF Class Reference
#include <Modele_turbulence_hyd_LES_VDF.h>
Public Member Functions
const Type_info * get_info () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
const Type_info * get_info () const override
Public Member Functions inherited from Modele_turbulence_hyd_LES_base
const Type_info * get_info () const override
void imprimer (Sortie &is) const override
int preparer_calcul () override
int reprendre (Entree &is) override
const Type_info * get_info () const override
void imprimer (Sortie &) const override
int reprendre (Entree &is) override
Public Member Functions inherited from Modele_turbulence_hyd_base
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Type_info * get_info () const override
virtual void imprimer (Sortie &) const
void lire_distance_paroi ()
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual int preparer_calcul ()
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
maille fonction de structure en VDF
.SECTION voir aussi Modele_turbulence_hyd_LES_base
Constructor & Destructor Documentation
Modele_turbulence_hyd_LES_VDF()
Modele_turbulence_hyd_LES_VDF::Modele_turbulence_hyd_LES_VDF ()
~Modele_turbulence_hyd_LES_VDF()
Modele_turbulence_hyd_LES_VDF::~Modele_turbulence_hyd_LES_VDF ()
Member Function Documentation
cree_instance()
Objet_U * Modele_turbulence_hyd_LES_VDF::cree_instance () static
taille_memoire()
unsigned Modele_turbulence_hyd_LES_VDF::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Modele_turbulence_hyd_LES_VDF::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Modele_turbulence_hyd_LES_VDF::info () static
get_info()
const Type_info * Modele_turbulence_hyd_LES_VDF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Modele_turbulence_hyd_LES_VDF_base.
self_cast() [1/2]
Modele_turbulence_hyd_LES_VDF & Modele_turbulence_hyd_LES_VDF::self_cast (Objet_U & r) static
self_cast() [2/2]
const Modele_turbulence_hyd_LES_VDF & Modele_turbulence_hyd_LES_VDF::self_cast (const Objet_U & r) static
printOn()
Sortie & Modele_turbulence_hyd_LES_VDF::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Modele_turbulence_hyd_LES_VDF_base.
References Objet_U::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Modele_turbulence_hyd_LES_VDF::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Modele_turbulence_hyd_LES_VDF_base.
References Modele_turbulence_hyd_LES_VDF_base::readOn().
Referenced by Modele_turbulence_hyd_LES_axi_VDF::readOn(), Modele_turbulence_hyd_LES_selectif_mod_VDF::readOn(), and Modele_turbulence_hyd_LES_selectif_VDF::readOn().
set_param()
void Modele_turbulence_hyd_LES_VDF::set_param (Param & param) override virtual
Reimplemented from Modele_turbulence_hyd_LES_base.
References Param::ajouter_non_std(), and Modele_turbulence_hyd_LES_base::set_param().
Referenced by Modele_turbulence_hyd_LES_selectif_mod_VDF::set_param().
lire_motcle_non_standard()
int Modele_turbulence_hyd_LES_VDF::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
< liste stockant tous les noms de frontiere du domaine
Reimplemented from Modele_turbulence_hyd_base.
References dir1_, dir2_, dir3_, Process::exit(), Modele_turbulence_hyd_base::lire_motcle_non_standard(), and nb_points_.
Referenced by Modele_turbulence_hyd_LES_selectif_mod_VDF::lire_motcle_non_standard().
calculer_viscosite_turbulente()
Champ_Fonc_base & Modele_turbulence_hyd_LES_VDF::calculer_viscosite_turbulente () override protected virtual
Implements Modele_turbulence_hyd_0_eq_base.
References calculer_fonction_structure(), Champ_base::changer_temps(), Csm1_, Domaine_dis_base::domaine(), Process::exit(), F2_, Modele_turbulence_hyd_LES_base::l_, Modele_turbulence_hyd_base::la_viscosite_turbulente_, Modele_turbulence_hyd_0_eq_base::le_dom_VF_, Modele_turbulence_hyd_base::mon_equation_, Domaine_32_64< _SIZE_ >::nb_elem(), Domaine_32_64< _SIZE_ >::nb_elem_tot(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), TRUSTVect< _TYPE_, _SIZE_ >::size(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), and Debog::verifier().
calculer_energie_cinetique_turb()
void Modele_turbulence_hyd_LES_VDF::calculer_energie_cinetique_turb () override protected virtual
Reimplemented from Modele_turbulence_hyd_LES_base.
References Champ_base::changer_temps(), Csm2_, Modele_turbulence_hyd_0_eq_base::energie_cinetique_turb_, Process::exit(), F2_, Modele_turbulence_hyd_0_eq_base::le_dom_VF_, Modele_turbulence_hyd_base::mon_equation_, TRUSTVect< _TYPE_, _SIZE_ >::size(), TRUST_Ref< _CLASSE_ >::valeur(), and Champ_Don_base::valeurs().
calculer_fonction_structure()
void Modele_turbulence_hyd_LES_VDF::calculer_fonction_structure () protected virtual
Reimplemented in Modele_turbulence_hyd_LES_axi_VDF, Modele_turbulence_hyd_LES_selectif_mod_VDF, and Modele_turbulence_hyd_LES_selectif_VDF.
References Domaine_VDF::dim_elem(), Objet_U::dimension, dir1_, dir2_, Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), Domaine_VDF::elem_voisin(), Process::exit(), F2_, Domaine_VF::face_voisins(), Modele_turbulence_hyd_LES_base::l_, Modele_turbulence_hyd_0_eq_base::le_dom_Cl_, Modele_turbulence_hyd_0_eq_base::le_dom_VF_, Domaine_Cl_dis_base::les_conditions_limites(), Modele_turbulence_hyd_base::mon_equation_, Domaine_VDF::nb_aretes_bord(), Domaine_VDF::nb_aretes_coin(), Domaine_VDF::nb_aretes_internes(), Domaine_VDF::nb_aretes_mixtes(), Domaine_32_64< _SIZE_ >::nb_elem(), Domaine_32_64< _SIZE_ >::nb_elem_tot(), Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), nb_points_, Front_VF::num_premiere_face(), Domaine_VDF::orientation(), TypeAreteBordVDF::PAROI_PAROI, TypeAreteCoinVDF::PERIO_PAROI, TypeAreteBordVDF::PERIO_PERIO, TypeAreteCoinVDF::PERIO_PERIO, Domaine_VDF::premiere_arete_bord(), Domaine_VDF::premiere_arete_coin(), Domaine_VDF::premiere_arete_interne(), Domaine_VDF::premiere_arete_mixte(), Domaine_VDF::Qdm(), Domaine_Cl_VDF::type_arete_bord(), Domaine_Cl_VDF::type_arete_coin(), TRUST_Deriv< _CLASSE_ >::valeur(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Modele_turbulence_hyd_LES_selectif_mod_VDF::calculer_fonction_structure(), Modele_turbulence_hyd_LES_selectif_VDF::calculer_fonction_structure(), and calculer_viscosite_turbulente().
Member Data Documentation
info_obj
const Type_info Modele_turbulence_hyd_LES_VDF::info_obj static
F2_
DoubleVect Modele_turbulence_hyd_LES_VDF::F2_ protected
Referenced by calculer_energie_cinetique_turb(), calculer_fonction_structure(), Modele_turbulence_hyd_LES_axi_VDF::calculer_fonction_structure(), Modele_turbulence_hyd_LES_axi_VDF::calculer_viscosite_turbulente(), calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_selectif_mod_VDF::cutoff(), and Modele_turbulence_hyd_LES_selectif_VDF::cutoff().
nb_points_
int Modele_turbulence_hyd_LES_VDF::nb_points_ = 6 protected
Referenced by calculer_fonction_structure(), Modele_turbulence_hyd_LES_selectif_mod_VDF::cutoff(), and lire_motcle_non_standard().
dir1_
int Modele_turbulence_hyd_LES_VDF::dir1_ = -123 protected
Referenced by calculer_fonction_structure(), and lire_motcle_non_standard().
dir2_
int Modele_turbulence_hyd_LES_VDF::dir2_ = -123 protected
Referenced by calculer_fonction_structure(), and lire_motcle_non_standard().
dir3_
int Modele_turbulence_hyd_LES_VDF::dir3_ = -123 protected
Referenced by Modele_turbulence_hyd_LES_selectif_mod_VDF::cutoff(), and lire_motcle_non_standard().
Csm1_
double Modele_turbulence_hyd_LES_VDF::Csm1_ = CSM1 protected
Referenced by calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_selectif_mod_VDF::Modele_turbulence_hyd_LES_selectif_mod_VDF(), and Modele_turbulence_hyd_LES_selectif_VDF::Modele_turbulence_hyd_LES_selectif_VDF().
Csm2_
double Modele_turbulence_hyd_LES_VDF::Csm2_ = CSM2 protected
Referenced by calculer_energie_cinetique_turb(), Modele_turbulence_hyd_LES_selectif_mod_VDF::Modele_turbulence_hyd_LES_selectif_mod_VDF(), and Modele_turbulence_hyd_LES_selectif_VDF::Modele_turbulence_hyd_LES_selectif_VDF().