TrioCFD: Masse_ajoutee_base Class Reference
Masse_ajoutee_base Class Reference abstract
#include <Masse_ajoutee_base.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
 alpha_k rho_k Dv_k / Dt -> alpha_k rho_k Dv_k / Dt + sum_l ma(k, l) Dv_l / Dt
 cette classe definit une fonction calculer avec :
entrees : alpha[n] -> taux de presence de la phase n rho[n] -> masse volumique de la phase n
entree / sortie : a_r(k, l) -> a mettre dans l'equation de qdm (par defaut : alpha(k) * rho(k) pour la phase k)
NB: le alpha donnee a la correlation est le alpha passe : pas de derivee a calculer
Constructor & Destructor Documentation
Masse_ajoutee_base()
Masse_ajoutee_base::Masse_ajoutee_base ()
~Masse_ajoutee_base()
Masse_ajoutee_base::~Masse_ajoutee_base () override
Member Function Documentation
info()
const Type_info * Masse_ajoutee_base::info () static
get_info()
const Type_info * Masse_ajoutee_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Correlation_base.
Reimplemented in Masse_ajoutee_Cai, Masse_ajoutee_Coef_Constant, Masse_ajoutee_Wijngaarden, and Masse_ajoutee_Zuber.
self_cast() [1/2]
Masse_ajoutee_base & Masse_ajoutee_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Masse_ajoutee_base & Masse_ajoutee_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Masse_ajoutee_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Correlation_base.
Reimplemented in Masse_ajoutee_Cai, Masse_ajoutee_Coef_Constant, Masse_ajoutee_Wijngaarden, and Masse_ajoutee_Zuber.
readOn()
Entree & Masse_ajoutee_base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Correlation_base.
Reimplemented in Masse_ajoutee_Cai, Masse_ajoutee_Coef_Constant, Masse_ajoutee_Wijngaarden, and Masse_ajoutee_Zuber.
ajouter()
virtual void Masse_ajoutee_base::ajouter (const double * alpha, const double * rho, DoubleTab & a_r) const pure virtual
Implemented in Masse_ajoutee_Cai, Masse_ajoutee_Coef_Constant, Masse_ajoutee_Wijngaarden, and Masse_ajoutee_Zuber.
Referenced by Op_Conv_EF_Stab_PolyMAC_P0_Face::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Face::ajouter_blocs(), Op_Conv_Amont_VPoly_VDF_Face::ajouter_blocs(), Masse_PolyMAC_P0_Face::ajouter_blocs(), Masse_VDF_Face::ajouter_blocs(), and Solveur_Masse_Face_proto::ajouter_blocs_proto().
coefficient()
virtual void Masse_ajoutee_base::coefficient (const double * alpha, const double * rho, DoubleTab & coeff) const inline virtual
Reimplemented in Masse_ajoutee_Coef_Constant.
References Process::exit(), and Objet_U::que_suis_je().
Referenced by Viscosite_turbulente_k_omega::eddy_viscosity().
ajouter_inj()
virtual void Masse_ajoutee_base::ajouter_inj (const double * flux_alpha, const double * alpha, const double * rho, DoubleTab & f_a_r) const pure virtual
Implemented in Masse_ajoutee_Cai, Masse_ajoutee_Coef_Constant, Masse_ajoutee_Wijngaarden, and Masse_ajoutee_Zuber.
Referenced by Injection_QDM_nulle_PolyMAC_P0::ajouter_blocs(), and Injection_QDM_nulle_VDF::ajouter_blocs().
coeff()
virtual void Masse_ajoutee_base::coeff (const DoubleTab & alpha, const DoubleTab & rho, DoubleTab & coeff) const pure virtual
Implemented in Masse_ajoutee_Cai, Masse_ajoutee_Coef_Constant, Masse_ajoutee_Wijngaarden, and Masse_ajoutee_Zuber.
Referenced by Dispersion_bulles_turbulente_Bazin::coefficient(), and Dispersion_bulles_turbulente_Lavieville::coefficient().
Member Data Documentation
info_obj
const Type_info Masse_ajoutee_base::info_obj static
limiter_liquid_
double Masse_ajoutee_base::limiter_liquid_ = 0.5 protected
Referenced by Masse_ajoutee_Cai::ajouter(), Masse_ajoutee_Coef_Constant::ajouter(), Masse_ajoutee_Wijngaarden::ajouter(), Masse_ajoutee_Zuber::ajouter(), Masse_ajoutee_Cai::ajouter_inj(), Masse_ajoutee_Coef_Constant::ajouter_inj(), Masse_ajoutee_Wijngaarden::ajouter_inj(), Masse_ajoutee_Zuber::ajouter_inj(), Masse_ajoutee_Cai::coeff(), Masse_ajoutee_Coef_Constant::coeff(), Masse_ajoutee_Wijngaarden::coeff(), Masse_ajoutee_Zuber::coeff(), Masse_ajoutee_Coef_Constant::coefficient(), Masse_ajoutee_Cai::readOn(), Masse_ajoutee_Coef_Constant::readOn(), Masse_ajoutee_Wijngaarden::readOn(), and Masse_ajoutee_Zuber::readOn().