TrioCFD: Convection_Diffusion_Temperature Class Reference
Convection_Diffusion_Temperature Class Reference
#include <Convection_Diffusion_Temperature.h>
Public Member Functions
void associer_milieu_base (const Milieu_base &) override
DoubleTab & derivee_en_temps_inco (DoubleTab &) override
void discretiser () override
const Motcle & domaine_application () const override
const Type_info * get_info () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
int preparer_calcul () override
Public Member Functions inherited from Convection_Diffusion_Temperature_base
void associer_milieu_base (const Milieu_base &) override
Fluide_base & fluide ()
const Type_info * get_info () const override
Public Member Functions inherited from Convection_Diffusion_std
void associer_vitesse (const Champ_base &)
const Type_info * get_info () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
int nombre_d_operateurs () const override
const Operateur & operateur (int) const override
Operateur & operateur (int) override
const Champ_Inc_base & vitesse_transportante () const
Public Member Functions inherited from Equation_base
virtual void abortTimeStep ()
virtual void associer_domaine_dis (const Domaine_dis_base &)
virtual void associer_pb_base (const Probleme_base &)
virtual void associer_sch_tps_base (const Schema_Temps_base &)
virtual double calculer_pas_de_temps () const
virtual void completer ()
virtual std::vector< YAML_data > data_a_sauvegarder () const
DoubleTab & derivee_en_temps_conv (DoubleTab &, const DoubleTab &)
virtual DoubleTab & derivee_en_temps_inco (DoubleTab &)
const Discretisation_base & discretisation () const
virtual void discretiser ()
virtual const Motcle & domaine_application () const
virtual Domaine_Cl_dis_base & domaine_Cl_dis ()
virtual const Domaine_Cl_dis_base & domaine_Cl_dis () const
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual void imprimer (Sortie &os) const
virtual bool initTimeStep (double dt)
const Nom & le_nom () const override
int limpr () const
virtual void mettre_a_jour (double temps)
virtual int preparer_calcul ()
Probleme_base & probleme ()
const Probleme_base & probleme () const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Schema_Temps_base & schema_temps ()
const Schema_Temps_base & schema_temps () const
Solveur_Masse_base & solv_masse ()
const Solveur_Masse_base & solv_masse () const
Sources & sources ()
const Sources & sources () const
virtual void valider_iteration ()
virtual void verifie_ch_init_nb_comp (const Champ_Inc_base &ch_ref, const int nb_comp) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Convection_Diffusion_Temperature_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Equation_base
virtual Entree & lire_cl (Entree &)
virtual Entree & lire_cond_init (Entree &)
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual Entree & lire_sources (Entree &)
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
virtual int verif_Cl () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
quand le scalaire subissant le transport est la temperature.
See also
Conv_Diffusion_std
Constructor & Destructor Documentation
Convection_Diffusion_Temperature()
Convection_Diffusion_Temperature::Convection_Diffusion_Temperature ()
~Convection_Diffusion_Temperature()
Convection_Diffusion_Temperature::~Convection_Diffusion_Temperature ()
Member Function Documentation
cree_instance()
Objet_U * Convection_Diffusion_Temperature::cree_instance () static
taille_memoire()
unsigned Convection_Diffusion_Temperature::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Convection_Diffusion_Temperature_FT_Disc, Convection_Diffusion_Temperature_sensibility, and Convection_Diffusion_Temperature_Turbulent.
duplique()
int Convection_Diffusion_Temperature::duplique () const override virtual
Implements Objet_U.
Reimplemented in Convection_Diffusion_Temperature_FT_Disc, Convection_Diffusion_Temperature_sensibility, and Convection_Diffusion_Temperature_Turbulent.
info()
const Type_info * Convection_Diffusion_Temperature::info () static
get_info()
const Type_info * Convection_Diffusion_Temperature::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Convection_Diffusion_std.
Reimplemented in Convection_Diffusion_Temperature_FT_Disc, Convection_Diffusion_Temperature_sensibility, and Convection_Diffusion_Temperature_Turbulent.
self_cast() [1/2]
Convection_Diffusion_Temperature & Convection_Diffusion_Temperature::self_cast (Objet_U & r) static
self_cast() [2/2]
const Convection_Diffusion_Temperature & Convection_Diffusion_Temperature::self_cast (const Objet_U & r) static
printOn()
Sortie & Convection_Diffusion_Temperature::printOn (Sortie & is) const override protected virtual
Simple appel a Equation_base::printOn(Sortie&)
Parameters
(Sortie& is) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Convection_Diffusion_std.
Reimplemented in Convection_Diffusion_Temperature_FT_Disc, Convection_Diffusion_Temperature_sensibility, and Convection_Diffusion_Temperature_Turbulent.
References Convection_Diffusion_Temperature_base::printOn().
Referenced by Convection_Diffusion_Temperature_FT_Disc::printOn(), Convection_Diffusion_Temperature_sensibility::printOn(), and Convection_Diffusion_Temperature_IBM::printOn().
readOn()
Entree & Convection_Diffusion_Temperature::readOn (Entree & is) override protected virtual
cf Equation_base::readOn(Entree&)
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Exceptions
terme diffusif non specifie
terme convectif non specifie
Reimplemented from Convection_Diffusion_std.
Reimplemented in Convection_Diffusion_Temperature_FT_Disc, Convection_Diffusion_Temperature_sensibility, and Convection_Diffusion_Temperature_Turbulent.
References inconnue(), la_temperature, Convection_Diffusion_Temperature_base::le_fluide, Field_base::le_nom(), Objet_U_ptr::non_nul(), TRUST_Ref< _CLASSE_ >::non_nul(), Convection_Diffusion_Temperature_base::readOn(), Operateur::set_description(), Operateur::set_fichier(), Solveur_Masse_base::set_name_of_coefficient_temporel(), Equation_base::solveur_masse, Nom::suffix(), Convection_Diffusion_std::terme_convectif, and Convection_Diffusion_std::terme_diffusif.
Referenced by Convection_Diffusion_Temperature_sensibility::readOn(), Convection_Diffusion_Temperature_IBM::readOn(), and Convection_Diffusion_Temperature_Turbulent::readOn().
set_param()
void Convection_Diffusion_Temperature::set_param (Param & titi) override virtual
Reimplemented from Convection_Diffusion_std.
Reimplemented in Convection_Diffusion_Temperature_sensibility, Convection_Diffusion_Temperature_FT_Disc, and Convection_Diffusion_Temperature_Turbulent.
References Param::ajouter_non_std(), and Convection_Diffusion_std::set_param().
Referenced by Convection_Diffusion_Temperature_sensibility::set_param(), Convection_Diffusion_Temperature_FT_Disc::set_param(), Convection_Diffusion_Temperature_IBM::set_param(), and Convection_Diffusion_Temperature_Turbulent::set_param().
lire_motcle_non_standard()
int Convection_Diffusion_Temperature::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Convection_Diffusion_std.
Reimplemented in Convection_Diffusion_Temperature_FT_Disc, Convection_Diffusion_Temperature_Turbulent, and Convection_Diffusion_Temperature_sensibility.
References TRUST_Vector< _CLASSE_ >::add(), choix_pena, Domaine_32_64< _SIZE_ >::creer_tableau_elements(), Domaine_VF::creer_tableau_faces(), Domaine_dis_base::domaine(), Equation_base::domaine_dis(), eta, Process::exit(), indic_face_pena_global, indic_pena_global, is_penalized, Convection_Diffusion_std::lire_motcle_non_standard(), Equation_base::probleme(), ref_penalisation_L2_FTD, TRUSTTab< _TYPE_, _SIZE_ >::resize(), and tab_penalisation_L2_FTD.
Referenced by Convection_Diffusion_Temperature_FT_Disc::lire_motcle_non_standard(), Convection_Diffusion_Temperature_IBM_Turbulent::lire_motcle_non_standard(), Convection_Diffusion_Temperature_Turbulent::lire_motcle_non_standard(), and Convection_Diffusion_Temperature_sensibility::lire_motcle_non_standard().
inconnue() [1/2]
const Champ_Inc_base & Convection_Diffusion_Temperature::inconnue () const inline override virtual
Implements Convection_Diffusion_std.
References la_temperature.
Referenced by Terme_Source_inc_th_VDF_Face::ajouter_blocs(), assembler_blocs(), Convection_Diffusion_Temperature_FT_Disc::calculer_grad_t(), Navier_Stokes_FT_Disc::compute_boussinesq_additional_gravity(), Post_Processing_Hydrodynamic_Forces::compute_heat_transfer(), Convection_Diffusion_Temperature_FT_Disc::correct_mpoint(), Convection_Diffusion_Temperature_FT_Disc::derivee_en_temps_inco(), derivee_en_temps_inco(), ecrire_fichier_pena_th(), Convection_Diffusion_Temperature_FT_Disc::get_Twall(), Convection_Diffusion_Temperature_FT_Disc::mettre_a_jour(), penalisation_L2(), Convection_Diffusion_Temperature_FT_Disc::readOn(), readOn(), and Convection_Diffusion_Temperature_FT_Disc::suppression_interfaces().
inconnue() [2/2]
Champ_Inc_base & Convection_Diffusion_Temperature::inconnue () inline override virtual
Implements Convection_Diffusion_std.
References la_temperature.
discretiser()
void Convection_Diffusion_Temperature::discretiser () override virtual
Discretise l'equation.
Type le domaine_Cl_dis, la formatte, l'associe a l'equation. Type le solveur masse, lui associe le domaine discretisee et le domaine des conditions aux limites discretisees.
Reimplemented from Equation_base.
Reimplemented in Convection_Diffusion_Temperature_FT_Disc.
References Champs_compris_T< FIELD_TYPE >::ajoute_champ(), Equation_base::champs_compris_, Equation_base::discretisation(), Equation_base::discretiser(), Equation_base::domaine_dis(), Process::exit(), la_temperature, Convection_Diffusion_Temperature_base::le_fluide, Objet_U::que_suis_je(), Equation_base::schema_temps(), Discret_Thermique::temperature(), and TRUST_Ref< _CLASSE_ >::valeur().
preparer_calcul()
int Convection_Diffusion_Temperature::preparer_calcul () override virtual
Tout ce qui ne depend pas des autres problemes eventuels.
Returns
(int) renvoie toujours 1
Reimplemented from Equation_base.
Reimplemented in Convection_Diffusion_Temperature_FT_Disc, and Convection_Diffusion_Temperature_Turbulent.
References Equation_base::preparer_calcul().
Referenced by Convection_Diffusion_Temperature_Turbulent::preparer_calcul().
associer_milieu_base()
void Convection_Diffusion_Temperature::associer_milieu_base (const Milieu_base & un_milieu) override virtual
Associe un milieu physique a l'equation, le milieu est en fait caste en Fluide_base.
Parameters
(Milieu_base& un_milieu)
Exceptions
le milieu n'est pas un Fluide_base
Implements Equation_base.
Reimplemented in Convection_Diffusion_Temperature_FT_Disc.
References Convection_Diffusion_Temperature_base::associer_fluide(), Process::exit(), and Objet_U::que_suis_je().
Referenced by Pb_Thermohydraulique_sensibility::associer_milieu_base(), Pb_Thermohydraulique_IBM::associer_milieu_base(), Pb_Thermohydraulique_IBM_Turbulent::associer_milieu_base(), Pb_Thermohydraulique::associer_milieu_base(), Pb_Thermohydraulique_Concentration_Turbulent::associer_milieu_base(), and Pb_Thermohydraulique_Turbulent::associer_milieu_base().
creer_champ()
void Convection_Diffusion_Temperature::creer_champ (const Motcle & motlu) override virtual
Reimplemented from Equation_base.
Reimplemented in Convection_Diffusion_Temperature_Turbulent.
References Champs_compris_T< FIELD_TYPE >::ajoute_champ(), Equation_base::champs_compris_, Convection_Diffusion_Temperature_base::creer_champ(), Equation_base::discretisation(), Equation_base::domaine_Cl_dis(), Equation_base::domaine_dis(), Objet_U_ptr::est_nul(), Discret_Thyd::grad_T(), gradient_temperature, Discret_Thyd::h_conv(), h_echange, la_temperature, and Nom::suffix().
Referenced by Convection_Diffusion_Temperature_IBM_Turbulent::creer_champ(), and Convection_Diffusion_Temperature_Turbulent::creer_champ().
get_champ()
const Champ_base & Convection_Diffusion_Temperature::get_champ (const Motcle & nom) const override virtual
Reimplemented from Equation_base.
Reimplemented in Convection_Diffusion_Temperature_Turbulent.
References Equation_base::champs_compris_, Champs_compris_T< FIELD_TYPE >::get_champ(), Convection_Diffusion_Temperature_base::get_champ(), gradient_temperature, h_echange, la_temperature, Field_base::le_nom(), Champ_Fonc_base::mettre_a_jour(), MorEqn::mon_equation_non_nul(), Objet_U_ptr::non_nul(), Equation_base::schema_temps(), Champ_base::temps(), Schema_Temps_base::temps_init(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by Convection_Diffusion_Temperature_FT_Disc::derivee_en_temps_inco(), and has_champ().
has_champ() [1/2]
bool Convection_Diffusion_Temperature::has_champ (const Motcle & nom, TRUST_Ref< Champ_base * > & ref_champ) const override virtual
Reimplemented from Equation_base.
Reimplemented in Convection_Diffusion_Temperature_Turbulent.
References get_champ(), h_echange, Convection_Diffusion_Temperature_base::has_champ(), Field_base::le_nom(), and Objet_U_ptr::non_nul().
Referenced by Convection_Diffusion_Temperature_IBM_Turbulent::get_champ(), Convection_Diffusion_Temperature_Turbulent::get_champ(), Convection_Diffusion_Temperature_IBM_Turbulent::has_champ(), and Convection_Diffusion_Temperature_Turbulent::has_champ().
has_champ() [2/2]
bool Convection_Diffusion_Temperature::has_champ (const Motcle & nom) const override virtual
Reimplemented from Equation_base.
Reimplemented in Convection_Diffusion_Temperature_Turbulent.
References h_echange, Convection_Diffusion_Temperature_base::has_champ(), Field_base::le_nom(), and Objet_U_ptr::non_nul().
get_noms_champs_postraitables()
void Convection_Diffusion_Temperature::get_noms_champs_postraitables (Noms & nom, Option opt = NONE) const override virtual
Reimplemented from Equation_base.
Reimplemented in Convection_Diffusion_Temperature_Turbulent.
References TRUST_Vector< _CLASSE_ >::add(), Equation_base::champs_compris_, Convection_Diffusion_Temperature_base::get_noms_champs_postraitables(), Champs_compris_T< FIELD_TYPE >::liste_noms_compris(), and Objet_U::que_suis_je().
Referenced by Convection_Diffusion_Temperature_IBM_Turbulent::get_noms_champs_postraitables(), and Convection_Diffusion_Temperature_Turbulent::get_noms_champs_postraitables().
get_time_factor()
double Convection_Diffusion_Temperature::get_time_factor () const override virtual
Reimplemented from Equation_base.
References Milieu_base::capacite_calorifique(), Equation_base::domaine_dis(), Milieu_base::masse_volumique(), Convection_Diffusion_Temperature_base::milieu(), Domaine_dis_base::nb_elem(), Champ_Don_base::valeurs(), and Champ_Proto::valeurs().
Referenced by assembler(), assembler_blocs(), derivee_en_temps_inco(), and transport_ibc().
domaine_application()
const Motcle & Convection_Diffusion_Temperature::domaine_application () const override virtual
Renvoie le nom du domaine d'application de l'equation.
Ici "Thermique".
Returns
(Motcle&) le nom du domaine d'application de l'equation
Reimplemented from Equation_base.
derivee_en_temps_inco()
DoubleTab & Convection_Diffusion_Temperature::derivee_en_temps_inco (DoubleTab & derivee) override virtual
Returns the time derivative of the unknown I of the equation: dI/dt = M-1*(sum(operators(I) + sources))
In : derivee contains I (but immediatly set to 0) Out: derivee contains dI/dt
Reimplemented from Equation_base.
Reimplemented in Convection_Diffusion_Temperature_FT_Disc.
References TRUSTTab< _TYPE_, _SIZE_ >::copy(), Equation_base::derivee_en_temps_conv(), Equation_base::derivee_en_temps_inco(), get_time_factor(), Equation_base::has_time_factor_, inconnue(), is_penalized, mise_en_place_domaine_fantome(), Convection_Diffusion_std::nombre_d_operateurs(), transport_ibc(), and Champ_Inc_base::valeurs().
Referenced by Convection_Diffusion_Temperature_FT_Disc::derivee_en_temps_inco().
assembler()
void Convection_Diffusion_Temperature::assembler (Matrice_Morse & mat_morse, const DoubleTab & present, DoubleTab & secmem) override virtual
Reimplemented from Equation_base.
References Operateur::ajouter(), Sources::ajouter(), Matrice_Base::ajouter_multvect(), Statistiques::begin_count(), Discretisation_base::codage_du_calcul_du_residu(), Operateur_base::contribuer_a_avec(), Sources::contribuer_a_avec(), Operateur_base::contribuer_au_second_membre(), Equation_base::discretisation(), Probleme_base::discretisation(), Statistiques::end_count(), Process::exit(), Matrice_Morse::get_set_coeff(), get_time_factor(), Operateur::l_op_base(), Convection_Diffusion_std::nombre_d_operateurs(), Convection_Diffusion_std::operateur(), Equation_base::probleme(), Objet_U::que_suis_je(), Equation_base::sources(), Operateur_base::tester_contribuer_a_avec(), Discretisation_base::VIA_AJOUTER, and Discretisation_base::VIA_CONTRIBUER_AU_SECOND_MEMBRE.
assembler_blocs()
void Convection_Diffusion_Temperature::assembler_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = {}) const override virtual
Reimplemented from Equation_base.
References Operateur_base::ajouter_blocs(), Matrice_Base::ajouter_multvect(), Equation_base::assembler_blocs(), Statistiques::begin_count(), Equation_base::discretisation(), Statistiques::end_count(), get_time_factor(), Nom::getString(), inconnue(), Operateur::l_op_base(), Field_base::le_nom(), Equation_base::les_sources, Convection_Diffusion_std::nombre_d_operateurs(), Convection_Diffusion_std::operateur(), Equation_base::probleme(), Objet_U::que_suis_je(), and TRUST_List< _CLASSE_ >::size().
calculer_rho_cp_T()
void Convection_Diffusion_Temperature::calculer_rho_cp_T (const Objet_U & obj, DoubleTab & val, DoubleTab & bval, tabs_t & deriv) static
References Milieu_base::capacite_calorifique(), Equation_base::inconnue(), Milieu_base::masse_volumique(), Equation_base::milieu(), Champ_Don_base::valeurs(), and Champ_Proto::valeurs().
filtrage_si_appart_ibc()
DoubleTab & Convection_Diffusion_Temperature::filtrage_si_appart_ibc (DoubleTab & u_conv, DoubleTab & u) protected
References TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), indic_pena_global, set_indic_pena_globale(), and TRUSTVect< _TYPE_, _SIZE_ >::size().
penalisation_L2()
DoubleTab & Convection_Diffusion_Temperature::penalisation_L2 (DoubleTab & u) protected
References choix_pena, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Equation_base::domaine_dis(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), ecrire_fichier_pena_th(), Domaine_VF::elem_faces(), eta, Process::exit(), Domaine_VF::face_voisins(), Transport_Interfaces_base::get_update_indicatrice(), inconnue(), indic_pena_global, TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Schema_Temps_base::pas_de_temps(), ref_penalisation_L2_FTD, Equation_base::schema_temps(), set_indic_pena_globale(), TRUSTVect< _TYPE_, _SIZE_ >::size(), TRUST_Vector< _CLASSE_ >::size(), tab_penalisation_L2_FTD, Champ_Inc_base::valeurs(), and Champ_Proto::valeurs().
verifier_tag_indicatrice_pena_glob()
int Convection_Diffusion_Temperature::verifier_tag_indicatrice_pena_glob () protected
References Transport_Interfaces_base::get_mesh_tag(), ref_penalisation_L2_FTD, and tag_indic_pena_global.
Referenced by mise_en_place_domaine_fantome(), and set_indic_pena_globale().
mise_a_jour_tag_indicatrice_pena_glob()
int Convection_Diffusion_Temperature::mise_a_jour_tag_indicatrice_pena_glob () protected
References Transport_Interfaces_base::get_mesh_tag(), ref_penalisation_L2_FTD, and tag_indic_pena_global.
Referenced by mise_en_place_domaine_fantome(), and set_indic_pena_globale().
set_indic_pena_globale()
void Convection_Diffusion_Temperature::set_indic_pena_globale () protected
References calcul_indic_pena_global(), indic_face_pena_global, indic_pena_global, mise_a_jour_tag_indicatrice_pena_glob(), and verifier_tag_indicatrice_pena_glob().
Referenced by filtrage_si_appart_ibc(), penalisation_L2(), and transport_ibc().
mise_en_place_domaine_fantome()
void Convection_Diffusion_Temperature::mise_en_place_domaine_fantome (DoubleTab & solution) protected
References calcul_indic_pena_global(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Equation_base::domaine_dis(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_VF::elem_faces(), Process::exit(), Domaine_VF::face_voisins(), indic_face_pena_global, indic_pena_global, mise_a_jour_tag_indicatrice_pena_glob(), Equation_base::schema_temps(), tab_penalisation_L2_FTD, and verifier_tag_indicatrice_pena_glob().
Referenced by derivee_en_temps_inco().
calcul_indic_pena_global()
void Convection_Diffusion_Temperature::calcul_indic_pena_global (IntTab & indicatrice_totale, IntTab & indicatrice_face_totale) protected
References TRUSTTab< _TYPE_, _SIZE_ >::copy(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Equation_base::domaine_dis(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Process::exit(), Domaine_VF::face_voisins(), Transport_Interfaces_base::get_update_indicatrice(), indic_face_pena_global, indic_pena_global, ref_penalisation_L2_FTD, and Champ_Proto::valeurs().
Referenced by mise_en_place_domaine_fantome(), and set_indic_pena_globale().
transport_ibc()
void Convection_Diffusion_Temperature::transport_ibc (DoubleTrav & secmem_conv_vr, DoubleTab & inco_conv_vr) protected
References Equation_base::derivee_en_temps_conv(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Equation_base::domaine_dis(), Domaine_VF::elem_faces(), Domaine_VF::face_voisins(), get_time_factor(), indic_face_pena_global, indic_pena_global, Convection_Diffusion_std::nombre_d_operateurs(), set_indic_pena_globale(), and TRUSTVect< _TYPE_, _SIZE_ >::size().
Referenced by derivee_en_temps_inco().
ecrire_fichier_pena_th()
void Convection_Diffusion_Temperature::ecrire_fichier_pena_th (DoubleTab & u_old, DoubleTab & u, DoubleTab & tref, DoubleTab & denom) protected
References Milieu_base::capacite_calorifique(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Equation_base::domaine_dis(), eta, Transport_Interfaces_base::get_update_indicatrice(), inconnue(), Process::je_suis_maitre(), Equation_base::le_schema_en_temps, Milieu_base::masse_volumique(), Convection_Diffusion_Temperature_base::milieu(), Process::mp_sum(), Objet_U::nom_du_cas(), Sortie_Fichier_base::ouvrir(), Schema_Temps_base::pas_de_temps(), Equation_base::probleme(), ref_penalisation_L2_FTD, Equation_base::schema_temps(), Champ_Don_base::valeurs(), Champ_Inc_base::valeurs(), Champ_Proto::valeurs(), and Domaine_VF::volumes().
Referenced by penalisation_L2().
Member Data Documentation
info_obj
const Type_info Convection_Diffusion_Temperature::info_obj static
la_temperature
TRUST_Deriv< Champ_Inc_base > Convection_Diffusion_Temperature::la_temperature protected
Referenced by creer_champ(), Convection_Diffusion_Temperature_FT_Disc::discretiser(), discretiser(), get_champ(), inconnue(), and readOn().
gradient_temperature
TRUST_Deriv< Champ_Fonc_base > Convection_Diffusion_Temperature::gradient_temperature protected
Referenced by creer_champ(), and get_champ().
h_echange
TRUST_Deriv< Champ_Fonc_base > Convection_Diffusion_Temperature::h_echange protected
Referenced by creer_champ(), get_champ(), and has_champ().
is_penalized
int Convection_Diffusion_Temperature::is_penalized = 0 protected
Referenced by derivee_en_temps_inco(), and lire_motcle_non_standard().
eta
double Convection_Diffusion_Temperature::eta = 1.0 protected
Referenced by ecrire_fichier_pena_th(), lire_motcle_non_standard(), and penalisation_L2().
choix_pena
int Convection_Diffusion_Temperature::choix_pena = 0 protected
Referenced by lire_motcle_non_standard(), and penalisation_L2().
tag_indic_pena_global
int Convection_Diffusion_Temperature::tag_indic_pena_global = -1 protected
Referenced by mise_a_jour_tag_indicatrice_pena_glob(), and verifier_tag_indicatrice_pena_glob().
indic_pena_global
IntTab Convection_Diffusion_Temperature::indic_pena_global = 0 protected
Referenced by calcul_indic_pena_global(), filtrage_si_appart_ibc(), lire_motcle_non_standard(), mise_en_place_domaine_fantome(), penalisation_L2(), set_indic_pena_globale(), and transport_ibc().
indic_face_pena_global
IntTab Convection_Diffusion_Temperature::indic_face_pena_global = 0 protected
Referenced by calcul_indic_pena_global(), lire_motcle_non_standard(), mise_en_place_domaine_fantome(), set_indic_pena_globale(), and transport_ibc().
ref_penalisation_L2_FTD
TRUST_Vector< RefObjU > Convection_Diffusion_Temperature::ref_penalisation_L2_FTD protected
Referenced by calcul_indic_pena_global(), ecrire_fichier_pena_th(), lire_motcle_non_standard(), mise_a_jour_tag_indicatrice_pena_glob(), penalisation_L2(), and verifier_tag_indicatrice_pena_glob().
tab_penalisation_L2_FTD
DoubleTabs Convection_Diffusion_Temperature::tab_penalisation_L2_FTD protected
Referenced by lire_motcle_non_standard(), mise_en_place_domaine_fantome(), and penalisation_L2().