TrioCFD: Domaine_Poly_base Class Reference
Domaine_Poly_base Class Reference abstract
#include <Domaine_Poly_base.h>
Public Member Functions
const Type_info * get_info () const override
void reordonner (Faces &) override
Public Member Functions inherited from Domaine_VF
void build_map_mc_Cmesh (const bool with_faces) override
void build_mc_dual_mesh () const
void build_mc_face_mesh () const
void construire_face_virt_pe_num ()
int elem_faces (int i, int j) const
int face_voisins (int num_face, int i) const
const Type_info * get_info () const override
void init_dist_paroi_globale (const Conds_lim &conds_lim) override
int nb_faces_bord () const
int nb_faces_bord_tot () const
int nb_faces_internes () const
int nb_faces_tot () const
int nb_som_face () const
int premiere_face_bord () const
int premiere_face_int () const
Public Member Functions inherited from Domaine_dis_base
void associer_domaine (const Domaine &)
const Domaine & domaine () const
void ecrire_noms_bords (Sortie &) const
virtual IntTab & face_sommets ()
const Frontiere_dis_base & frontiere_dis (const Nom &) const
const Type_info * get_info () const override
int nombre_de_sous_domaines_dis () const
int rang_frontiere (const Nom &) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Domaine_VF
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
    Classe instanciable qui derive de Domaine_VF.
    Cette classe contient les informations geometriques que demande
    la methode des Volumes Elements Finis (element de Crouzeix-Raviart)
    La classe porte un certain nombre d'informations concernant les faces
    Dans cet ensemble de faces on fait figurer aussi les faces du bord et
 des joints. Pour manipuler les faces on distingue 2 categories:
      - les faces non standard qui sont sur un joint, un bord ou qui sont
        internes tout en appartenant a un element du bord
      - les faces standard qui sont les faces internes n'appartenant pas
        a un element du bord
 Cette distinction correspond au traitement des conditions aux limites:les
 faces standard ne "voient pas" les conditions aux limites.
 L'ensemble des faces est numerote comme suit:
      - les faces qui sont sur un Domaine_joint apparaissent en premier
           (dans l'ordre du vecteur les_joints)
         - les faces qui sont sur un Domaine_bord apparaissent ensuite
       (dans l'ordre du vecteur les_bords)
         - les faces internes non standard apparaissent ensuite
      - les faces internes standard en dernier
 Finalement on trouve regroupees en premier toutes les faces non standard
 qui vont necessiter un traitement particulier
 On distingue deux types d'elements
      - les elements non standard : ils ont au moins une face de bord
      - les elements standard : ils n'ont pas de face de bord
 Les elements standard (resp. les elements non standard) ne sont pas ranges
 de maniere consecutive dans l'objet Domaine. On utilise le tableau
 rang_elem_non_std pour acceder de maniere selective a l'un ou
 l'autre des types d'elements
Constructor & Destructor Documentation
Domaine_Poly_base()
Domaine_Poly_base::Domaine_Poly_base ()
~Domaine_Poly_base()
Domaine_Poly_base::~Domaine_Poly_base () override
Member Function Documentation
info()
const Type_info * Domaine_Poly_base::info () static
get_info()
const Type_info * Domaine_Poly_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Domaine_dis_base.
Reimplemented in Domaine_PolyMAC, Domaine_PolyMAC_P0, and Domaine_PolyMAC_P0P1NC.
self_cast() [1/2]
Domaine_Poly_base & Domaine_Poly_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Domaine_Poly_base & Domaine_Poly_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Domaine_Poly_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Domaine_dis_base.
Reimplemented in Domaine_PolyMAC, Domaine_PolyMAC_P0, and Domaine_PolyMAC_P0P1NC.
References Domaine_VF::face_normales_, h_carre, Domaine_VF::nb_elem_std_, Domaine_VF::nb_faces_std_, Domaine_VF::printOn(), Domaine_VF::rang_elem_non_std_, type_elem_, TRUST_Deriv< _CLASSE_ >::valeur(), Domaine_VF::volumes_entrelaces_, Domaine_VF::xp_, and Domaine_VF::xv_.
Referenced by Domaine_DG::printOn(), Domaine_PolyMAC::printOn(), Domaine_PolyMAC_P0::printOn(), and Domaine_PolyMAC_P0P1NC::printOn().
readOn()
Entree & Domaine_Poly_base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Domaine_dis_base.
Reimplemented in Domaine_PolyMAC, Domaine_PolyMAC_P0, and Domaine_PolyMAC_P0P1NC.
References Process::exit(), Domaine_VF::face_normales_, h_carre, Domaine_VF::nb_elem_std_, Domaine_VF::nb_faces_std_, Domaine_VF::rang_elem_non_std_, Domaine_VF::readOn(), type_elem_, Domaine_VF::volumes_entrelaces_, Domaine_VF::xp_, and Domaine_VF::xv_.
Referenced by Domaine_DG::readOn(), Domaine_PolyMAC::readOn(), Domaine_PolyMAC_P0::readOn(), and Domaine_PolyMAC_P0P1NC::readOn().
typer_elem()
void Domaine_Poly_base::typer_elem (Domaine & domaine_geom) override virtual
Reimplemented from Domaine_VF.
References Process::exit(), Objet_U::que_suis_je(), Domaine_32_64< _SIZE_ >::type_elem(), type_elem_, Objet_U_ptr::typer(), Domaine_32_64< _SIZE_ >::typer(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by discretiser().
discretiser()
void Domaine_Poly_base::discretiser () override virtual
Reimplemented from Domaine_dis_base.
Reimplemented in Domaine_PolyMAC, Domaine_PolyMAC_P0, and Domaine_PolyMAC_P0P1NC.
References calculer_volumes_entrelaces(), Domaine_32_64< _SIZE_ >::coord_sommets(), Domaine_VF::creer_tableau_faces(), detecter_faces_non_planes(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Domaine_VF::discretiser(), Domaine_dis_base::domaine(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_VF::elem_faces(), Domaine_VF::elem_faces_, Process::exit(), Domaine_VF::face_normales_, Domaine_VF::face_sommets(), Domaine_VF::face_sommets_, Domaine_VF::face_voisins(), Domaine_base::le_nom(), Domaine_dis_base::nb_elem_tot(), Domaine_VF::nb_faces(), Domaine_VF::nb_faces_tot(), Elem_poly_base::normale(), Objet_U::que_suis_je(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Domaine_32_64< _SIZE_ >::type_elem(), type_elem_, typer_elem(), TRUST_Deriv< _CLASSE_ >::valeur(), and Domaine_VF::xv_.
Referenced by Domaine_DG::discretiser(), Domaine_PolyMAC::discretiser(), Domaine_PolyMAC_P0::discretiser(), and Domaine_PolyMAC_P0P1NC::discretiser().
calculer_volumes_entrelaces()
virtual void Domaine_Poly_base::calculer_volumes_entrelaces () inline virtual
Reimplemented in Domaine_PolyMAC, and Domaine_PolyMAC_P0P1NC.
Referenced by discretiser().
discretiser_aretes()
void Domaine_Poly_base::discretiser_aretes ()
References MD_Vector_composite::add_part(), Domaine_32_64< _SIZE_ >::aretes_som(), Domaine_32_64< _SIZE_ >::coord_sommets(), MD_Vector::copy(), Domaine_32_64< _SIZE_ >::creer_aretes(), Domaine_VF::creer_tableau_aretes(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Domaine_dis_base::domaine(), Domaine_VF::dot(), TRUSTVect< _TYPE_, _SIZE_ >::get_md_vector(), longueur_aretes_, Domaine_VF::md_vector_aretes(), Domaine_VF::md_vector_aretes_, Domaine_VF::md_vector_faces(), mdv_elems_faces, mdv_faces_aretes, Domaine_32_64< _SIZE_ >::nb_aretes_tot(), Domaine_dis_base::nb_elem_tot(), Domaine_dis_base::nb_som_tot(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Domaine_32_64< _SIZE_ >::set_aretes_som(), Domaine_32_64< _SIZE_ >::set_elem_aretes(), som_arete, ta_, and Domaine_VF::xa_.
Referenced by Domaine_PolyMAC::discretiser(), and Domaine_PolyMAC_P0P1NC::discretiser().
orthocentrer()
void Domaine_Poly_base::orthocentrer ()
References Domaine_32_64< _SIZE_ >::coord_sommets(), Objet_U::dimension, Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), Domaine_VF::face_normales_, Domaine_VF::face_sommets(), Domaine_VF::face_surfaces(), and Domaine_32_64< _SIZE_ >::les_elems().
longueur_aretes()
const DoubleVect & Domaine_Poly_base::longueur_aretes () const inline
References longueur_aretes_.
Referenced by Domaine_PolyMAC::init_rf().
ta()
const DoubleTab & Domaine_Poly_base::ta () const inline
References ta_.
reordonner()
void Domaine_Poly_base::reordonner (Faces & les_faces) override virtual
Methode appelee par Domaine_VF::discretiser apres la creation des faces reelles.
On reordonne les faces de sorte a placer les faces "non standard" au debut de la liste des faces. Les faces non standard sont celles dont les volumes de controles sont modifies par les conditions aux limites.
Reimplemented from Domaine_VF.
References Domaine_32_64< _SIZE_ >::creer_tableau_elements(), Domaine_dis_base::domaine(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_dis_base::nb_elem(), Domaine_VF::nb_elem_std_, Domaine_32_64< _SIZE_ >::nb_faces_frontiere(), Domaine_VF::rang_elem_non_std_, Domaine_VF::renumeroter(), TRUSTVect< _TYPE_, _SIZE_ >::size_totale(), and Faces_32_64< _SIZE_ >::voisin().
modifier_pour_Cl()
void Domaine_Poly_base::modifier_pour_Cl (const Conds_lim & conds_lim) override virtual
Implements Domaine_dis_base.
Reimplemented in Domaine_PolyMAC.
References Objet_U::dimension, Domaine_dis_base::domaine(), Periodique::face_associee(), Domaine_VF::face_normales_, Domaine_VF::face_voisins_, Cond_lim_base::frontiere_dis(), Process::Journal(), Domaine_VF::marquer_faces_double_contrib(), Domaine_VF::nb_faces(), Front_VF::nb_faces(), Domaine_32_64< _SIZE_ >::nb_faces_elem(), Front_VF::nb_faces_tot(), Front_VF::num_face(), Front_VF::num_premiere_face(), TRUST_Vector< _CLASSE_ >::size(), Domaine_VF::volumes_, Domaine_VF::volumes_entrelaces_, Domaine_VF::xp_, and Domaine_VF::xv_.
type_elem()
const Elem_poly_base & Domaine_Poly_base::type_elem () const inline
References type_elem_, and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by Domaine_PolyMAC::calculer_h_carre().
nb_elem_Cl()
int Domaine_Poly_base::nb_elem_Cl () const inline
References Domaine_dis_base::nb_elem(), and Domaine_VF::nb_elem_std_.
nb_faces_joint()
int Domaine_Poly_base::nb_faces_joint () const inline
nb_faces_std()
int Domaine_Poly_base::nb_faces_std () const inline
References Domaine_VF::nb_faces_std_.
nb_elem_std()
int Domaine_Poly_base::nb_elem_std () const inline
References Domaine_VF::nb_elem_std_.
carre_pas_du_maillage()
double Domaine_Poly_base::carre_pas_du_maillage () const inline
References h_carre.
carre_pas_maille()
double Domaine_Poly_base::carre_pas_maille (int i) const inline
References h_carre_.
rang_elem_non_std() [1/2]
IntVect & Domaine_Poly_base::rang_elem_non_std () inline
References Domaine_VF::rang_elem_non_std_.
rang_elem_non_std() [2/2]
const IntVect & Domaine_Poly_base::rang_elem_non_std () const inline
References Domaine_VF::rang_elem_non_std_.
oriente_normale()
int Domaine_Poly_base::oriente_normale (int face_opp, int elem2) const inline
References Domaine_VF::face_voisins().
Referenced by Op_Div_PolyMAC::ajouter().
calculer_h_carre()
void Domaine_Poly_base::calculer_h_carre () virtual
Reimplemented in Domaine_DG, and Domaine_PolyMAC.
References Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), Domaine_VF::face_surfaces(), h_carre, h_carre_, Domaine_dis_base::nb_elem_tot(), Domaine_32_64< _SIZE_ >::nb_faces_elem(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), TRUSTVect< _TYPE_, _SIZE_ >::size(), and Domaine_VF::volumes().
volumes_entrelaces_dir() [1/2]
DoubleTab & Domaine_Poly_base::volumes_entrelaces_dir () inline
References Domaine_VF::volumes_entrelaces_dir_.
Referenced by Domaine_PolyMAC_P0::fgrad().
volumes_entrelaces_dir() [2/2]
const DoubleTab & Domaine_Poly_base::volumes_entrelaces_dir () const inline
References Domaine_VF::volumes_entrelaces_dir_.
nu_dot()
double Domaine_Poly_base::nu_dot (const DoubleTab * nu, int e, int n, const double * a, const double * b, const double * ma = nullptr, const double * mb = nullptr) const inline
References Objet_U::dimension, Domaine_VF::dot(), and TRUSTTab< _TYPE_, _SIZE_ >::nb_dim().
Referenced by Domaine_PolyMAC_P0P1NC::M1(), Domaine_PolyMAC::M2(), Domaine_PolyMAC_P0P1NC::W1(), and Domaine_PolyMAC::W2().
dist_norm()
double Domaine_Poly_base::dist_norm (int num_face) const inline override virtual
Reimplemented from Domaine_VF.
References Domaine_VF::dot(), Domaine_VF::face_normales_, Domaine_VF::face_surfaces(), Domaine_VF::face_voisins(), and Domaine_VF::xp_.
dist_norm_bord() [1/2]
double Domaine_Poly_base::dist_norm_bord (int num_face) const inline override virtual
Reimplemented from Domaine_VF.
References Domaine_VF::dot(), Domaine_VF::face_normales_, Domaine_VF::face_surfaces(), Domaine_VF::face_voisins(), Domaine_VF::xp_, and Domaine_VF::xv_.
Referenced by dist_norm_bord().
dist_norm_bord() [2/2]
DoubleVect & Domaine_Poly_base::dist_norm_bord (DoubleVect & dist, const Nom & nom_bord) const
References dist_norm_bord(), Domaine_VF::front_VF(), Frontiere_dis_base::le_nom(), Domaine_VF::les_bords_, Front_VF::nb_faces(), Front_VF::num_premiere_face(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), and TRUST_Vector< _CLASSE_ >::size().
dist_face_elem0()
double Domaine_Poly_base::dist_face_elem0 (int num_face, int n0) const inline override virtual
Reimplemented from Domaine_VF.
References Domaine_VF::dot(), Domaine_VF::face_normales_, Domaine_VF::face_surfaces(), Domaine_VF::xp_, and Domaine_VF::xv_.
dist_face_elem1()
double Domaine_Poly_base::dist_face_elem1 (int num_face, int n1) const inline override virtual
Reimplemented from Domaine_VF.
References Domaine_VF::dot(), Domaine_VF::face_normales_, Domaine_VF::face_surfaces(), Domaine_VF::xp_, and Domaine_VF::xv_.
dist_face_elem0_period()
double Domaine_Poly_base::dist_face_elem0_period (int num_face, int n0, double l) const inline override virtual
Reimplemented from Domaine_VF.
References Process::abort().
dist_face_elem1_period()
double Domaine_Poly_base::dist_face_elem1_period (int num_face, int n1, double l) const inline override virtual
Reimplemented from Domaine_VF.
References Process::abort().
detecter_faces_non_planes()
void Domaine_Poly_base::detecter_faces_non_planes () const
References Domaine_32_64< _SIZE_ >::coord_sommets(), Domaine_dis_base::domaine(), Domaine_VF::dot(), Process::exit(), Domaine_VF::face_normales_, Domaine_VF::face_sommets_, Domaine_VF::face_surfaces(), Domaine_VF::face_voisins(), Process::me(), Domaine_VF::nb_faces(), Process::nproc(), and Domaine_VF::xv_.
Referenced by discretiser().
equiv()
const IntTab & Domaine_Poly_base::equiv () const
References equiv_, init_equiv(), and TRUSTTab< _TYPE_, _SIZE_ >::nb_dim().
init_equiv()
virtual void Domaine_Poly_base::init_equiv () const pure virtual
Implemented in Domaine_DG, and Domaine_PolyMAC.
Referenced by equiv().
som_elem()
const Static_Int_Lists & Domaine_Poly_base::som_elem () const
References Domaine_dis_base::domaine(), Static_Int_Lists_32_64< _SIZE_ >::get_nb_lists(), Domaine_dis_base::nb_som_tot(), and som_elem_.
Referenced by Domaine_PolyMAC_P0::fgrad().
elem_som_d()
const IntTab & Domaine_Poly_base::elem_som_d () const
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Domaine_dis_base::domaine(), elem_som_d_, Domaine_32_64< _SIZE_ >::les_elems(), Domaine_dis_base::nb_elem_tot(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), and TRUSTVect< _TYPE_, _SIZE_ >::size().
Referenced by pvol_som(), Champ_implementation_P1::value_interpolation(), and vol_elem_som().
elem_arete_d()
const IntTab & Domaine_Poly_base::elem_arete_d () const
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Domaine_dis_base::domaine(), elem_arete_d_, Domaine_32_64< _SIZE_ >::elem_aretes(), Domaine_VF::elem_faces(), Domaine_dis_base::nb_elem_tot(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), and TRUSTVect< _TYPE_, _SIZE_ >::size().
Referenced by Domaine_PolyMAC_P0P1NC::M1(), Domaine_PolyMAC_P0P1NC::surf_elem_arete(), and Domaine_PolyMAC_P0P1NC::W1().
vol_elem_som()
const DoubleTab & Domaine_Poly_base::vol_elem_som () const
References Domaine_32_64< _SIZE_ >::coord_sommets(), Domaine_VF::cross(), Objet_U::dimension, Domaine_dis_base::domaine(), Domaine_VF::dot(), Domaine_VF::elem_faces(), elem_som_d(), Domaine_VF::face_sommets(), Domaine_32_64< _SIZE_ >::les_elems(), Domaine_dis_base::nb_elem_tot(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTVect< _TYPE_, _SIZE_ >::size(), vol_elem_som_, Domaine_VF::xp_, and Domaine_VF::xv_.
Referenced by pvol_som(), and Champ_implementation_P1::value_interpolation().
pvol_som()
const DoubleTab & Domaine_Poly_base::pvol_som (const DoubleVect & poro) const
References Domaine_32_64< _SIZE_ >::creer_tableau_sommets(), Domaine_dis_base::domaine(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), elem_som_d(), Domaine_32_64< _SIZE_ >::les_elems(), Domaine_dis_base::nb_elem_tot(), pvol_som_, TRUSTVect< _TYPE_, _SIZE_ >::size(), and vol_elem_som().
ecrit()
Sortie & Domaine_Poly_base::ecrit (Sortie & os) const protected
References TRUSTVect< _TYPE_, _SIZE_ >::ecrit(), TRUSTTab< _TYPE_, _SIZE_ >::ecrit(), Domaine_VF::face_normales_, h_carre, Domaine_VF::nb_elem_std_, Domaine_VF::nb_faces_std_, Domaine_VF::printOn(), Domaine_VF::rang_elem_non_std_, type_elem_, TRUST_Deriv< _CLASSE_ >::valeur(), and Domaine_VF::volumes_entrelaces_.
Member Data Documentation
info_obj
const Type_info Domaine_Poly_base::info_obj static
som_arete
std::vector<std::map<int, int> > Domaine_Poly_base::som_arete
Referenced by discretiser_aretes(), Domaine_PolyMAC::init_m1_3d(), Domaine_PolyMAC::init_rf(), Domaine_PolyMAC::init_we(), Domaine_PolyMAC::init_we_3d(), and Domaine_PolyMAC_P0P1NC::surf_elem_arete().
mdv_elems_faces
MD_Vector Domaine_Poly_base::mdv_elems_faces mutable
Referenced by discretiser_aretes(), and Echange_contact_PolyMAC::initialiser().
mdv_faces_aretes
MD_Vector Domaine_Poly_base::mdv_faces_aretes
Referenced by discretiser_aretes().
h_carre
double Domaine_Poly_base::h_carre = 1e+38 protected
Referenced by calculer_h_carre(), Domaine_DG::calculer_h_carre(), Domaine_PolyMAC::calculer_h_carre(), carre_pas_du_maillage(), ecrit(), printOn(), and readOn().
h_carre_
DoubleVect Domaine_Poly_base::h_carre_ protected
Referenced by calculer_h_carre(), Domaine_DG::calculer_h_carre(), Domaine_PolyMAC::calculer_h_carre(), and carre_pas_maille().
type_elem_
TRUST_Deriv< Elem_poly_base > Domaine_Poly_base::type_elem_ protected
Referenced by discretiser(), ecrit(), Domaine_DG::get_type_elem(), printOn(), readOn(), type_elem(), and typer_elem().
equiv_
IntTab Domaine_Poly_base::equiv_ mutable protected
Referenced by equiv(), and Domaine_PolyMAC::init_equiv().
som_elem_
Static_Int_Lists Domaine_Poly_base::som_elem_ mutable protected
Referenced by som_elem().
elem_som_d_
IntTab Domaine_Poly_base::elem_som_d_ mutable protected
Referenced by elem_som_d().
elem_arete_d_
IntTab Domaine_Poly_base::elem_arete_d_ protected
Referenced by elem_arete_d().
vol_elem_som_
DoubleTab Domaine_Poly_base::vol_elem_som_ mutable protected
Referenced by vol_elem_som().
pvol_som_
DoubleTab Domaine_Poly_base::pvol_som_ protected
Referenced by pvol_som().
longueur_aretes_
DoubleVect Domaine_Poly_base::longueur_aretes_ protected
Referenced by discretiser_aretes(), Domaine_PolyMAC::init_m1_3d(), Domaine_PolyMAC::init_we_3d(), and longueur_aretes().
ta_
DoubleTab Domaine_Poly_base::ta_ mutable protected
Referenced by discretiser_aretes(), Domaine_PolyMAC::init_m1_3d(), Domaine_PolyMAC::init_rf(), Domaine_PolyMAC::init_we_3d(), Domaine_PolyMAC_P0P1NC::surf_elem_arete(), and ta().