TrioCFD: MD_Vector Class Reference
MD_Vector Class Reference
#include <MD_Vector.h>
Public Member Functions
void copy (const MD_Vector_base &)
Detailed Description
instances de cette classe. L'objet pointe ne peut etre accede qu'en "const" et n'est accessible que par des instances de MD_Vector. Donc il n'existe pas de moyen d'y acceder en "non const" autrement qu'avec un cast. La methode attach() et le constructeur par copie rattachent le pointeur a une instance existante deja attachee a un pointeur. La methode attach_detach() s'approprie l'objet pointe par le OWN_PTR et detache l'objet du OWN_PTR. C'est la seule facon de "construire" les objets MD_Vector (evite une copie, et permet d'assurer que le MD_Vect ne peut plus etre modifie une fois que qu'il a ete attache a un MD_Vector) ATTENTION: la securite de la methode repose sur le fait que l'instance pointee par MD_Vector n'est accessible nulle part ailleurs que par des objets MD_Vector. NE PAS AJOUTER de methode attach(const MD_Vector_base &), cela casse la securite de la classe !!! (B.Mathieu) inline d'un maximum de methodes pour ne pas penaliser les tableaux non distribues, tout en evitant d'inclure MD_Vector_base.h
Constructor & Destructor Documentation
MD_Vector() [1/2]
MD_Vector::MD_Vector () inline
MD_Vector() [2/2]
MD_Vector::MD_Vector (const MD_Vector & src) inline
constructeur par copie, associe le pointeur au meme objet que la source
References attach().
Member Function Documentation
operator=()
MD_Vector & MD_Vector::operator= (const MD_Vector & src) inline
idem que attach(src)
References attach().
attach()
void MD_Vector::attach (const MD_Vector & src) inline
Detache le pointeur et attache au meme objet que src.
Referenced by MD_Vector(), and operator=().
detach()
void MD_Vector::detach () inline
Detache le pointeur de l'objet pointe.
Referenced by MD_Vector_tools::CleanMyStatics(), TRUSTVect< _TYPE_, _SIZE_ >::detach_vect(), and TRUSTVect< _TYPE_, _SIZE_ >::reset().
non_nul()
int MD_Vector::non_nul () const inline
Referenced by MD_Vector_composite::add_part(), Op_Conv_VEF_Face::ajouter(), Op_Diff_VEF_Face::ajouter_cas_vectoriel(), SETS::assembler(), EOS_Tools_VEF::associer_domaines(), Champ_front_base::calculer_derivee_en_temps(), Op_Conv_VDF_base::calculer_dt_stab(), Neumann_paroi_rayo_semi_transp_VDF::calculer_temperature_bord(), Domaine_32_64< _SIZE_ >::calculer_volumes(), Domaine_VEF::calculer_volumes_entrelaces(), MD_Vector_tools::creer_md_vect_renum(), MD_Vector_tools::creer_tableau_distribue(), Champ_Fonc_base::creer_tableau_distribue(), Champ_Inc_base::creer_tableau_distribue(), Navier_Stokes_Fluide_Dilatable_Proto::derivee_en_temps_inco_impl(), Milieu_base::discretiser_diametre_hydro(), Milieu_base::discretiser_porosite(), EcritureLectureSpecial::ecriture_special(), Navier_Stokes_Fluide_Dilatable_Proto::impr_impl(), Paroi_std_hyd_EF::init_lois_paroi(), LoiParoiHybride_VDF::init_lois_paroi(), Paroi_std_hyd_VEF::init_lois_paroi(), Paroi_scal_hyd_base_EF::init_lois_paroi(), Paroi_scal_hyd_base_VEF::init_lois_paroi(), Paroi_hyd_base_EF::init_lois_paroi_(), Paroi_hyd_base_VDF::init_lois_paroi_(), Paroi_hyd_base_VEF::init_lois_paroi_(), Modele_Lam_Bremhorst_VEF::init_tenseur_elem(), Modele_Shih_Zhu_Lumley_VEF::init_tenseur_elem(), Modele_Lam_Bremhorst_VEF::init_tenseur_face(), Modele_Shih_Zhu_Lumley_VEF::init_tenseur_face(), EcritureLectureSpecial::lecture_special(), Domaine_32_64< _SIZE_ >::md_vector_elements(), Domaine_VEF::md_vector_p1b(), SSOR::prepare_(), TRUSTVect< _TYPE_, _SIZE_ >::printOn(), TRUSTVect< _TYPE_, _SIZE_ >::readOn(), Op_Diff_VEF_base::remplir_nu(), Op_Diff_EF::remplir_nu(), Op_Dift_EF_Q1::remplir_nu(), Champ_Fonc_reprise_IJK::reprendre_IJK(), Champ_Elem_PolyMAC::trace(), Op_Diff_DG_base::update_nu(), Op_Diff_PolyMAC_base::update_nu(), and Debog_Pb::write_geometry_data().
copy()
void MD_Vector::copy (const MD_Vector_base & src)
construction d'un objet MD_Vector par copie d'un objet existant.
C'est la methode recommandee pour creer un objet MD_Vector (autrement que par copie d'un autre MD_Vector)
References Objet_U::duplique(), Memoire::Instance(), and Memoire::objet_u_ptr().
Referenced by Desc_Structure_FT::calcul_schema_comm(), IJK_Thermal_Subresolution::compute_md_vector(), Scatter::construire_md_vector(), Domaine_PolyMAC_P0::discretiser(), Domaine_Poly_base::discretiser_aretes(), Domaine_VEF::discretiser_suite(), MD_Vector_seq::fill_md_vect_renum(), Scatter::init_sequential_domain(), Simple::iterer_eqs(), SETS::iterer_NS(), MD_Vector_composite::readOn(), MD_Vector_tools::restore_vector_with_md(), and Op_Diff_PolyMAC_P0P1NC_base::update_aux().
valeur()
const MD_Vector_base & MD_Vector::valeur () const inline
Referenced by MD_Vector_composite::add_part(), Champ_Generique_Transformation::completer(), Champ_Post_Operateur_Eqn::completer(), Scatter::construire_espace_virtuel_traduction(), MD_Vector_tools::creer_tableau_distribue(), MD_Vector_tools::dump_vector_with_md(), MD_Vector_composite::printOn(), and Champ_Fonc_reprise_IJK::reprendre_IJK().
operator->()
const MD_Vector_base * MD_Vector::operator-> () const inline
operator==()
int MD_Vector::operator== (const MD_Vector & md) const
renvoie 1 si les structures sont identiques, 0 sinon
Referenced by operator!=().
operator!=()
int MD_Vector::operator!= (const MD_Vector & md) const
reponse inverse de == ...
References operator==().