TrioCFD: Remaillage_FT_IJK Class Reference
Remaillage_FT_IJK Class Reference
#include <Remaillage_FT_IJK.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Remaillage_FT
void associer_domaine (const Domaine_dis_base &domaine_dis)
void barycentrer_lisser_apres_remaillage (Maillage_FT_Disc &maillage, ArrOfDouble &var_volume)
void barycentrer_lisser_systematique (double temps, Maillage_FT_Disc &maillage)
double calculer_variation_volume (const Maillage_FT_Disc &maillage, const DoubleTab &position_initiale, ArrOfDouble &varVolume) const
void corriger_volume (Maillage_FT_Disc &maillage, ArrOfDouble &var_volume)
const Type_info * get_info () const override
void lisser_dvolume (const Maillage_FT_Disc &maillage, ArrOfDouble &var_volume, const int nb_iterations) const
virtual void regulariser_courbure (Maillage_FT_Disc &maillage, const double coeff, ArrOfDouble &dvolume) const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
void set_param (Param &p)
int supprimer_facettes_nulles (Maillage_FT_Disc &maillage) const
int traite_adherence (Maillage_FT_Disc &maillage) const
int traite_decollement (Maillage_FT_Disc &maillage, const DoubleTab &deplacement) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
double calculer_longueurIdeale2_arete (const Maillage_FT_Disc &maillage, int som0, double x, double y, double z) const override
Protected Member Functions inherited from Remaillage_FT
int calculer_barycentre_facettes_voisines (const Maillage_FT_Disc &maillage, DoubleTab &barycentres) const
int calculer_connectivites_sommetFacettes (const Maillage_FT_Disc &maillage, ArrOfInt &fa7VoisinesSom_index, IntTab &fa7VoisinesSom_data) const
int calculer_correction_deplacement (DoubleTab &deplacement, const ArrOfDouble &varVolume, const DoubleTab &deplacement_varVolume, const ArrOfDouble &norme2_deplacement_varVolume) const
int calculer_differentielle_volume (const Maillage_FT_Disc &maillage, DoubleTab &differentielle_volume) const
virtual double calculer_longueurIdeale2_arete (const Maillage_FT_Disc &maillage, int som0, double x, double y, double z) const
double calculer_variation_volume_facette_2D (int fa7, const Maillage_FT_Disc &maillage, const DoubleTab &position_initiale) const
double calculer_volume_sommets_supprimes (const Maillage_FT_Disc &maillage, const ArrOfInt &tab_somSupp, ArrOfDouble &varVolume) const
int diviser_grandes_aretes (Maillage_FT_Disc &maillage) const
int nettoyer_maillage (Maillage_FT_Disc &maillage) const
int permuter_aretes (Maillage_FT_Disc &maillage) const
double qualiteTriangle (const FTd_vecteur3 &som0, const FTd_vecteur3 &som1, const FTd_vecteur3 &som2, double &aire) const
double redistribuer_sommets (Maillage_FT_Disc &maillage, const double relaxation_direction_tangente, const double relaxation_direction_normale, ArrOfDouble &var_volume_impose, ArrOfDouble &var_volume_obtenu) const
double regulariser_maillage (Maillage_FT_Disc &maillage, ArrOfDouble &var_volume, const double facteur_barycentrage_tangent, const double coeff_lissage, const int nb_iter_barycentrage, const int nb_iter_lissage, const int max_nb_iter_correction_volume, const double seuil_dvolume) const
int supprimer_doublons_facettes (Maillage_FT_Disc &maillage) const
int supprimer_facettes_bord (Maillage_FT_Disc &maillage) const
int supprimer_petites_aretes (Maillage_FT_Disc &maillage, ArrOfDouble &varVolume) const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Remaillage_FT_IJK()
Remaillage_FT_IJK::Remaillage_FT_IJK ()
References Remaillage_FT::critere_arete_, Remaillage_FT::equilateral_, Remaillage_FT::facteur_longueur_ideale_, Remaillage_FT::nb_iter_bary_volume_seul_, Remaillage_FT::nb_iter_barycentrage_, and Remaillage_FT::nb_iter_remaillage_.
~Remaillage_FT_IJK()
Remaillage_FT_IJK::~Remaillage_FT_IJK ()
Member Function Documentation
cree_instance()
Objet_U * Remaillage_FT_IJK::cree_instance () static
taille_memoire()
unsigned Remaillage_FT_IJK::taille_memoire () const override virtual
Reimplemented from Remaillage_FT.
duplique()
int Remaillage_FT_IJK::duplique () const override virtual
Reimplemented from Remaillage_FT.
info()
const Type_info * Remaillage_FT_IJK::info () static
get_info()
const Type_info * Remaillage_FT_IJK::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Remaillage_FT.
self_cast() [1/2]
Remaillage_FT_IJK & Remaillage_FT_IJK::self_cast (Objet_U & r) static
self_cast() [2/2]
const Remaillage_FT_IJK & Remaillage_FT_IJK::self_cast (const Objet_U & r) static
printOn()
Sortie & Remaillage_FT_IJK::printOn (Sortie & x) const override protected virtual
Cette fonction ne doit pas etre appelee.
Reimplemented from Remaillage_FT.
References Remaillage_FT::critere_arete_, Remaillage_FT::dt_remaillage_, Remaillage_FT::equilateral_, Remaillage_FT::facteur_longueur_ideale_, Remaillage_FT::lissage_courbure_coeff_, Remaillage_FT::lissage_courbure_iterations_si_remaillage_, Remaillage_FT::lissage_courbure_iterations_systematique_, Remaillage_FT::nb_iter_bary_volume_seul_, Remaillage_FT::nb_iter_barycentrage_, Remaillage_FT::nb_iter_remaillage_, Remaillage_FT::relax_barycentrage_, and Remaillage_FT::seuil_dvolume_residuel_.
readOn()
Entree & Remaillage_FT_IJK::readOn (Entree & is) override protected virtual
Lecture des parametres de remaillage.
Reimplemented from Remaillage_FT.
References Param::ajouter(), Remaillage_FT::critere_arete_, Remaillage_FT::dt_remaillage_, Remaillage_FT::equilateral_, Process::exit(), Remaillage_FT::facteur_longueur_ideale_, Param::lire_avec_accolades_depuis(), Remaillage_FT::lissage_courbure_coeff_, Remaillage_FT::lissage_courbure_iterations_si_remaillage_, Remaillage_FT::lissage_courbure_iterations_systematique_, Remaillage_FT::nb_iter_bary_volume_seul_, Remaillage_FT::nb_iter_barycentrage_, Remaillage_FT::nb_iter_remaillage_, Param::print(), Objet_U::que_suis_je(), Remaillage_FT::relax_barycentrage_, and Remaillage_FT::seuil_dvolume_residuel_.
get_delta_euler()
Vecteur3 Remaillage_FT_IJK::get_delta_euler (const Maillage_FT_IJK & maillage) const
References Objet_U::dimension, Domaine_IJK::get_constant_delta(), and Maillage_FT_IJK::get_domaine().
Referenced by calculer_longueurIdeale2_arete().
barycentrer_lisser_systematique_ijk()
void Remaillage_FT_IJK::barycentrer_lisser_systematique_ijk (Maillage_FT_IJK & maillage, ArrOfDouble & var_volume)
References Statistiques::begin_count(), FT_Field::check_conservation(), FT_Field::correction_conservation_globale(), Statistiques::end_count(), FT_Field::get_disable_surfactant(), Remaillage_FT::lissage_courbure_coeff_, Remaillage_FT::lissage_courbure_iterations_systematique_, Remaillage_FT::nb_iter_bary_volume_seul_, Remaillage_FT::nb_iter_barycentrage_, Maillage_FT_Disc::nb_sommets(), Statistiques::new_counter(), FT_Field::passer_variable_extensive(), FT_Field::passer_variable_intensive(), Remaillage_FT::regulariser_maillage(), Remaillage_FT::relax_barycentrage_, TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), Maillage_FT_IJK::set_barycentrage(), Remaillage_FT::seuil_dvolume_residuel_, Remaillage_FT::supprimer_facettes_bord(), and Maillage_FT_IJK::Surfactant_facettes_non_const().
Referenced by IJK_Interfaces::remailler_interface().
barycentrer_lisser_apres_remaillage()
void Remaillage_FT_IJK::barycentrer_lisser_apres_remaillage (Maillage_FT_IJK & maillage, ArrOfDouble & var_volume)
References Statistiques::begin_count(), Statistiques::end_count(), FT_Field::get_disable_surfactant(), Remaillage_FT::lissage_courbure_coeff_, Remaillage_FT::lissage_courbure_iterations_si_remaillage_, Remaillage_FT::nb_iter_bary_volume_seul_, Remaillage_FT::nb_iter_barycentrage_, Remaillage_FT::nettoyer_maillage(), Statistiques::new_counter(), FT_Field::passer_variable_extensive(), FT_Field::passer_variable_intensive(), Remaillage_FT::regulariser_maillage(), Remaillage_FT::relax_barycentrage_, Maillage_FT_IJK::set_barycentrage(), Remaillage_FT::seuil_dvolume_residuel_, Remaillage_FT::supprimer_facettes_bord(), and Maillage_FT_IJK::Surfactant_facettes_non_const().
Referenced by remaillage_local_interface().
remaillage_local_interface()
void Remaillage_FT_IJK::remaillage_local_interface (double temps, Maillage_FT_IJK & maillage)
References barycentrer_lisser_apres_remaillage(), Statistiques::begin_count(), FT_Field::check_conservation(), Comm_Group::check_enabled(), Maillage_FT_IJK::check_mesh(), FT_Field::correction_conservation_globale(), Maillage_FT_IJK::corriger_proprietaires_facettes(), diviser_grandes_aretes(), FT_Field::echange_espace_virtuel(), Statistiques::end_count(), FT_Field::get_disable_surfactant(), FT_Field::get_only_remaillage(), Process::je_suis_maitre(), Process::Journal(), Remaillage_FT::nb_iter_remaillage_, Maillage_FT_Disc::nb_sommets(), Maillage_FT_Disc::nettoyer_elements_virtuels(), Remaillage_FT::nettoyer_maillage(), Statistiques::new_counter(), FT_Field::passer_variable_extensive(), FT_Field::passer_variable_intensive(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), Remaillage_FT::supprimer_doublons_facettes(), supprimer_petites_aretes(), Maillage_FT_IJK::Surfactant_facettes_non_const(), Remaillage_FT::temps_, Remaillage_FT::temps_dernier_lissage_, Remaillage_FT::temps_dernier_remaillage_, and Remaillage_FT::variation_volume_.
Referenced by IJK_Interfaces::remailler_interface().
get_facteur_longueur_ideale()
const double & Remaillage_FT_IJK::get_facteur_longueur_ideale () const inline
References Remaillage_FT::facteur_longueur_ideale_.
Referenced by Schema_Temps_IJK_base::find_timestep().
diviser_grandes_aretes()
int Remaillage_FT_IJK::diviser_grandes_aretes (Maillage_FT_IJK & maillage) const protected
References Statistiques::begin_count(), Desc_Structure_FT::calcul_schema_comm(), Process::check_int_overflow(), Maillage_FT_IJK::compo_connexe_facettes_non_const(), Maillage_FT_Disc::convertir_numero_distant_local(), Maillage_FT_IJK::corriger_proprietaires_facettes(), Maillage_FT_IJK::deplacer_sommets(), Maillage_FT_Disc::desc_facettes_, Maillage_FT_Disc::desc_sommets(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, FT_Field::echange_espace_virtuel(), Statistiques::end_count(), Maillage_FT_Disc::facettes_, FT_Field::get_disable_surfactant(), Process::Journal(), Maillage_FT_Disc::maillage_modifie(), Remaillage_FT::marquer_aretes(), Process::me(), Maillage_FT_Disc::MINIMAL, Process::mp_sum(), Maillage_FT_Disc::nb_facettes(), Maillage_FT_Disc::nb_sommets(), Maillage_FT_Disc::nettoyer_elements_virtuels(), Statistiques::new_counter(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), FT_Field::resize_array(), Maillage_FT_Disc::sommet_num_owner_, Maillage_FT_IJK::Surfactant_facettes_non_const(), and Remaillage_FT::temps_.
Referenced by remaillage_local_interface().
supprimer_petites_aretes()
int Remaillage_FT_IJK::supprimer_petites_aretes (Maillage_FT_IJK & maillage, ArrOfDouble & varVolume) const protected
References TRUSTArray< _TYPE_, _SIZE_ >::append_array(), TRUSTTab< _TYPE_, _SIZE_ >::append_line(), Statistiques::begin_count(), FT_Field::calculer_normale_apres_deplacement(), Remaillage_FT::calculer_variation_volume(), FT_Field::champ_sommet_from_facettes(), Process::check_int_overflow(), Maillage_FT_IJK::check_mesh(), Desc_Structure_FT::collecter_espace_virtuel(), FT_Field::completer_compo_connexe_partielle(), Maillage_FT_IJK::compo_connexe_facettes_non_const(), Maillage_FT_Disc::convertir_numero_distant_local(), Maillage_FT_IJK::corriger_proprietaires_facettes(), Maillage_FT_Disc::creer_sommets_virtuels_numowner(), Maillage_FT_Disc::desc_sommets(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Desc_Structure_FT::echange_espace_virtuel(), FT_Field::echange_espace_virtuel(), Statistiques::end_count(), MD_Vector_tools::EV_SOMME, Maillage_FT_Disc::facettes_, FT_Field::get_compo_connexe_sommets(), FT_Field::get_disable_surfactant(), Maillage_FT_IJK::get_domaine(), FT_Field::get_facettes_sommets_full_compo_non_const(), FT_Field::get_liste_sommets_et_deplacements_non_const(), FT_Field::get_sorted_index(), Maillage_FT_Disc::get_surface_facettes(), Maillage_FT_Disc::maillage_modifie(), Remaillage_FT::marquer_aretes(), Process::me(), Maillage_FT_Disc::MINIMAL, Process::mp_sum(), Maillage_FT_Disc::nb_sommets(), Statistiques::new_counter(), FT_Field::reinit_remeshing_table(), FT_Field::remailler_FT_Field(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), FT_Field::sauvegarder_triangle(), FT_Field::set_tolerance_point_identique(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), Maillage_FT_Disc::sommet_num_owner(), Maillage_FT_Disc::sommet_virtuel(), Maillage_FT_Disc::sommets(), Maillage_FT_Disc::sommets_, Remaillage_FT::supprimer_petites_aretes(), Maillage_FT_IJK::Surfactant_facettes_non_const(), FT_Field::update_FT_Field_local_from_full_compo(), Point3D::x, Point3D::y, and Point3D::z.
Referenced by remaillage_local_interface().
calculer_longueurIdeale2_arete()
double Remaillage_FT_IJK::calculer_longueurIdeale2_arete (const Maillage_FT_Disc & maillage, int som0, double x, double y, double z) const override protected virtual
Cette fonction calcule le carre de la longueur ideale d'une arete Dans un premier, cette longueur ideale est la racine cubique (en 3D) de la moyenne.
des volumes des elements euleriens contenant les sommets
Parameters
(som0) indice du 1er sommet de l'arete
(som1) indice du 2e sommet de l'arete
Returns
(double) carre de la longueur idealede l'arete
Reimplemented from Remaillage_FT.
References Objet_U::dimension, Remaillage_FT::equilateral_, Process::exit(), Remaillage_FT::facteur_longueur_ideale_, get_delta_euler(), and Maillage_FT_Disc::sommets().
Member Data Documentation
info_obj
const Type_info Remaillage_FT_IJK::info_obj static