TrioCFD: Echange_externe_impose_H Class Reference
Echange_externe_impose_H Class Reference
#include <Echange_externe_impose_H.h>
Public Member Functions
const Type_info * get_info () const override
Champ_front_base & T_ext () override
double T_ext (int num) const override
double T_ext (int num, int k) const override
const Type_info * get_info () const override
Public Member Functions inherited from Echange_impose_base
int a_mettre_a_jour_ss_pas_dt () override
void associer_fr_dis_base (const Frontiere_dis_base &) override
double emissivite (int num) const
double emissivite (int num, int k) const
const Type_info * get_info () const override
virtual double h_imp (int num) const
virtual double h_imp (int num, int k) const
int initialiser (double temps) override
void mettre_a_jour (double) override
virtual Champ_front_base & T_ext ()
virtual double T_ext (int num) const
virtual double T_ext (int num, int k) const
Public Member Functions inherited from Cond_lim_base
virtual int a_mettre_a_jour_ss_pas_dt ()
virtual void associer_domaine_cl_dis_base (const Domaine_Cl_dis_base &)
virtual void associer_fr_dis_base (const Frontiere_dis_base &)
virtual void calculer_coeffs_echange (double temps)
virtual int compatible_avec_discr (const Discretisation_base &) const
Domaine_Cl_dis_base & domaine_Cl_dis ()
const Domaine_Cl_dis_base & domaine_Cl_dis () const
virtual Frontiere_dis_base & frontiere_dis ()
virtual const Frontiere_dis_base & frontiere_dis () const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
void set_modifier_val_imp (int)
virtual void verifie_ch_init_nb_comp () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Echange_externe_impose
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
void verifie_ch_init_nb_comp () const override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Cond_lim_base
void err_pas_compatible (const Discretisation_base &) const
void err_pas_compatible (const Equation_base &) const
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
See also
Echange_impose_base Echange_externe_impose
Constructor & Destructor Documentation
Echange_externe_impose_H()
Echange_externe_impose_H::Echange_externe_impose_H ()
~Echange_externe_impose_H()
Echange_externe_impose_H::~Echange_externe_impose_H ()
Member Function Documentation
cree_instance()
Objet_U * Echange_externe_impose_H::cree_instance () static
taille_memoire()
unsigned Echange_externe_impose_H::taille_memoire () const override virtual
Reimplemented from Echange_externe_impose.
duplique()
int Echange_externe_impose_H::duplique () const override virtual
Reimplemented from Echange_externe_impose.
info()
const Type_info * Echange_externe_impose_H::info () static
get_info()
const Type_info * Echange_externe_impose_H::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Echange_externe_impose.
self_cast() [1/2]
Echange_externe_impose_H & Echange_externe_impose_H::self_cast (Objet_U & r) static
self_cast() [2/2]
const Echange_externe_impose_H & Echange_externe_impose_H::self_cast (const Objet_U & r) static
printOn()
Sortie & Echange_externe_impose_H::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Echange_externe_impose.
References Objet_U::que_suis_je().
readOn()
Entree & Echange_externe_impose_H::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Echange_externe_impose.
References Cond_lim_base::app_domains, and Echange_externe_impose::readOn().
completer()
void Echange_externe_impose_H::completer () override virtual
Complete les conditions aux limites.
Reimplemented from Cond_lim_base.
References Cond_lim_base::completer(), le_fluide, Cond_lim_base::modifier_val_imp, and Cond_lim_base::mon_dom_cl_dis.
T_ext() [1/4]
double Echange_externe_impose_H::T_ext (int i) const override virtual
Renvoie la valeur de la temperature imposee sur la i-eme composante du champ de frontiere.
Parameters
(int i) l'indice de la composante du champ de de frontiere
Returns
(double)
Reimplemented from Echange_impose_base.
References Process::abort(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Cond_lim_base::le_champ_front, le_fluide, Cond_lim_base::modifier_val_imp, TRUSTVect< _TYPE_, _SIZE_ >::size(), and Champ_front_base::valeurs().
T_ext() [2/4]
double Echange_externe_impose_H::T_ext (int i, int j) const override virtual
Renvoie la valeur de la temperature imposee sur la (i,j)-eme composante du champ de frontiere.
Parameters
(int i)
(int j)
Returns
(double)
Reimplemented from Echange_impose_base.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Cond_lim_base::le_champ_front, le_fluide, Cond_lim_base::modifier_val_imp, and Champ_front_base::valeurs().
T_ext() [3/4]
Champ_front_base & Echange_externe_impose_H::T_ext () inline override virtual
Renvoie le champ T_ext de temperature imposee a la frontiere.
Returns
(Champ_front_base&) le champ T_ext de temperature imposee a la frontiere
Reimplemented from Echange_impose_base.
References Cond_lim_base::le_champ_front.
T_ext() [4/4]
const Champ_front_base & Echange_externe_impose_H::T_ext () const inline override virtual
Reimplemented from Echange_impose_base.
References Cond_lim_base::le_champ_front.
Member Data Documentation
info_obj
const Type_info Echange_externe_impose_H::info_obj static
le_fluide
TRUST_Ref< Fluide_Dilatable_base *> Echange_externe_impose_H::le_fluide protected
Referenced by completer(), and T_ext().