TrioCFD: Eval_Source_C_VDF_Elem Class Reference
Eval_Source_C_VDF_Elem Class Reference
#include <Eval_Source_C_VDF_Elem.h>
Constructor & Destructor Documentation
Eval_Source_C_VDF_Elem()
Eval_Source_C_VDF_Elem::Eval_Source_C_VDF_Elem () inline
Member Function Documentation
calculer_terme_source()
template<typename Type_Double > void Eval_Source_C_VDF_Elem::calculer_terme_source (const int num_elem, Type_Double & source) const
References la_source_constituant, Evaluateur_Source_Elem::porosite_vol, source_constituant, TRUST_Ref< _CLASSE_ >::valeur(), and Evaluateur_Source_Elem::volumes.
associer_champs()
void Eval_Source_C_VDF_Elem::associer_champs (const Champ_Don_base & Q) inline
References la_source_constituant, TRUSTTab< _TYPE_, _SIZE_ >::ref(), source_constituant, and Champ_Don_base::valeurs().
Referenced by Terme_Source_Constituant_VDF_Elem::associer_pb().
mettre_a_jour()
void Eval_Source_C_VDF_Elem::mettre_a_jour () inline override virtual
Implements Evaluateur_Source.
Member Data Documentation
la_source_constituant
TRUST_Ref< Champ_Don_base *> Eval_Source_C_VDF_Elem::la_source_constituant protected
Referenced by associer_champs(), and calculer_terme_source().
source_constituant
DoubleTab Eval_Source_C_VDF_Elem::source_constituant protected
Referenced by associer_champs(), and calculer_terme_source().