TrioCFD: Facettes_Interp_FT Class Reference
Facettes_Interp_FT Class Reference
#include <Facettes_Interp_FT.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Facettes_Interp_FT()
Facettes_Interp_FT::Facettes_Interp_FT ()
~Facettes_Interp_FT()
Facettes_Interp_FT::~Facettes_Interp_FT ()
Member Function Documentation
cree_instance()
Objet_U * Facettes_Interp_FT::cree_instance () static
taille_memoire()
unsigned Facettes_Interp_FT::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Facettes_Interp_FT::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Facettes_Interp_FT::info () static
get_info()
const Type_info * Facettes_Interp_FT::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
Facettes_Interp_FT & Facettes_Interp_FT::self_cast (Objet_U & r) static
self_cast() [2/2]
const Facettes_Interp_FT & Facettes_Interp_FT::self_cast (const Objet_U & r) static
printOn()
Sortie & Facettes_Interp_FT::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
readOn()
Entree & Facettes_Interp_FT::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
References Param::lire_avec_accolades(), Objet_U::que_suis_je(), and set_param().
associer()
void Facettes_Interp_FT::associer (const IJK_Interfaces & interfaces, const Cut_cell_FT_Disc & cut_cell_disc, const Domaine_IJK & splitting_ft, const Maillage_FT_IJK & maillage_ft_ijk, const Maillage_FT_IJK & old_maillage_ft_ijk)
References maillage_ft_ijk(), old_maillage_ft_ijk(), ref_cut_cell_disc_, ref_domaine_, ref_interfaces_, ref_maillage_ft_ijk_, and ref_old_maillage_ft_ijk_.
Referenced by Probleme_FTD_IJK_cut_cell::initialize().
set_param()
void Facettes_Interp_FT::set_param (Param & param)
References Param::ajouter(), number_of_interpolation_points_, scaled_distance_interpolation_1_, and scaled_distance_interpolation_2_.
Referenced by readOn().
cut_cell_perform_interpolation_facettes_next()
void Facettes_Interp_FT::cut_cell_perform_interpolation_facettes_next (int old_en_premier)
References coefficient_, cut_cell_perform_interpolation_facettes(), interpolation_coord_, next(), old_en_premier_, ref_cut_cell_disc_, ref_domaine_, ref_interfaces_, ref_maillage_ft_ijk_, signed_independent_index_, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Probleme_FTD_IJK_cut_cell::cut_cell_perform_interpolation_facettes().
cut_cell_perform_interpolation_facettes_old()
void Facettes_Interp_FT::cut_cell_perform_interpolation_facettes_old (bool not_old_en_premier)
References coefficient_, cut_cell_perform_interpolation_facettes(), interpolation_coord_, old(), old_en_premier_, ref_cut_cell_disc_, ref_domaine_, ref_interfaces_, ref_old_maillage_ft_ijk_, signed_independent_index_, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Probleme_FTD_IJK_cut_cell::update_twice_indicator_field().
get_signed_independent_index_next()
const FixedVector< IntTabFT, 4 > & Facettes_Interp_FT::get_signed_independent_index_next () const inline
References next(), and signed_independent_index_.
get_signed_independent_index_old()
const FixedVector< IntTabFT, 4 > & Facettes_Interp_FT::get_signed_independent_index_old () const inline
References old(), and signed_independent_index_.
get_coefficient_next()
const FixedVector< DoubleTabFT, 4 > & Facettes_Interp_FT::get_coefficient_next () const inline
References coefficient_, and next().
get_coefficient_old()
const FixedVector< DoubleTabFT, 4 > & Facettes_Interp_FT::get_coefficient_old () const inline
References coefficient_, and old().
old()
int Facettes_Interp_FT::old () const inline
References old_en_premier_.
Referenced by cut_cell_perform_interpolation_facettes_old(), get_coefficient_old(), and get_signed_independent_index_old().
next()
int Facettes_Interp_FT::next () const inline
References old_en_premier_.
Referenced by cut_cell_perform_interpolation_facettes_next(), get_coefficient_next(), and get_signed_independent_index_next().
get_number_of_interpolation_points()
int Facettes_Interp_FT::get_number_of_interpolation_points () const inline
References number_of_interpolation_points_.
get_scaled_distance_interpolation_1()
double Facettes_Interp_FT::get_scaled_distance_interpolation_1 () const inline
References scaled_distance_interpolation_1_.
get_scaled_distance_interpolation_2()
double Facettes_Interp_FT::get_scaled_distance_interpolation_2 () const inline
References scaled_distance_interpolation_2_.
maillage_ft_ijk()
const Maillage_FT_IJK & Facettes_Interp_FT::maillage_ft_ijk () const inline
References ref_maillage_ft_ijk_.
Referenced by associer().
old_maillage_ft_ijk()
const Maillage_FT_IJK & Facettes_Interp_FT::old_maillage_ft_ijk () const inline
References ref_old_maillage_ft_ijk_.
Referenced by associer().
get_distance_interpolation_1()
double Facettes_Interp_FT::get_distance_interpolation_1 () const
References Domaine_IJK::get_constant_delta(), ref_domaine_, scaled_distance_interpolation_1_, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by cut_cell_perform_interpolation_facettes().
get_distance_interpolation_2()
double Facettes_Interp_FT::get_distance_interpolation_2 () const
References Domaine_IJK::get_constant_delta(), ref_domaine_, scaled_distance_interpolation_2_, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by cut_cell_perform_interpolation_facettes().
cut_cell_perform_interpolation_facettes()
void Facettes_Interp_FT::cut_cell_perform_interpolation_facettes (bool next_time, const Cut_cell_FT_Disc & cut_cell_disc, const Domaine_IJK & geom, const Maillage_FT_IJK & maillage, FixedVector< DoubleTabFT, 4 > & interpolation_coord, FixedVector< IntTabFT, 4 > & interpolation_signed_independent_index, FixedVector< DoubleTabFT, 4 > & interpolation_coefficient) protected
References calcul_coefficient_interpolation_facette_cut_cell(), calcul_coefficient_interpolation_facette_cut_cell_second_order(), Process::exit(), get_distance_interpolation_1(), get_distance_interpolation_2(), Maillage_FT_Disc::get_update_normale_facettes(), and number_of_interpolation_points_.
Referenced by cut_cell_perform_interpolation_facettes_next(), and cut_cell_perform_interpolation_facettes_old().
calcul_coefficient_interpolation_facette_cut_cell()
void Facettes_Interp_FT::calcul_coefficient_interpolation_facette_cut_cell (bool next_time, const double dist, const Cut_cell_FT_Disc & cut_cell_disc, const Maillage_FT_IJK & maillage, FixedVector< DoubleTabFT, 4 > & interpolation_coord, const DoubleTab & normal_on_interf, FixedVector< IntTabFT, 4 > & cut_cell_facettes_interpolation_signed_independent_index, FixedVector< DoubleTabFT, 4 > & cut_cell_facettes_interpolation_coefficient) protected
References Maillage_FT_Disc::coords_fa7(), Objet_U::dimension, Intersection_Interface_ijk::get_position_interpolation_normal_interf(), and Maillage_FT_Disc::nb_facettes().
Referenced by cut_cell_perform_interpolation_facettes().
calcul_coefficient_interpolation_facette_cut_cell_second_order()
void Facettes_Interp_FT::calcul_coefficient_interpolation_facette_cut_cell_second_order (bool next_time, const double dist_1, const double dist_2, const Cut_cell_FT_Disc & cut_cell_disc, const Maillage_FT_IJK & maillage, FixedVector< DoubleTabFT, 4 > & interpolation_coord, const DoubleTab & normal_on_interf, FixedVector< IntTabFT, 4 > & cut_cell_facettes_interpolation_signed_independent_index, FixedVector< DoubleTabFT, 4 > & cut_cell_facettes_interpolation_coefficient) protected
References Maillage_FT_Disc::coords_fa7(), Objet_U::dimension, Intersection_Interface_ijk::get_position_interpolation_normal_interf(), and Maillage_FT_Disc::nb_facettes().
Referenced by cut_cell_perform_interpolation_facettes().
Member Data Documentation
info_obj
const Type_info Facettes_Interp_FT::info_obj static
signed_independent_index_
FixedVector<FixedVector<IntTabFT, 4>, 2> Facettes_Interp_FT::signed_independent_index_ protected
Referenced by cut_cell_perform_interpolation_facettes_next(), cut_cell_perform_interpolation_facettes_old(), get_signed_independent_index_next(), and get_signed_independent_index_old().
coefficient_
FixedVector<FixedVector<DoubleTabFT, 4>, 2> Facettes_Interp_FT::coefficient_ protected
Referenced by cut_cell_perform_interpolation_facettes_next(), cut_cell_perform_interpolation_facettes_old(), get_coefficient_next(), and get_coefficient_old().
interpolation_coord_
FixedVector<FixedVector<DoubleTabFT, 4>, 2> Facettes_Interp_FT::interpolation_coord_ protected
Referenced by cut_cell_perform_interpolation_facettes_next(), and cut_cell_perform_interpolation_facettes_old().
old_en_premier_
bool Facettes_Interp_FT::old_en_premier_ = true protected
Referenced by cut_cell_perform_interpolation_facettes_next(), cut_cell_perform_interpolation_facettes_old(), next(), and old().
ref_interfaces_
TRUST_Ref< IJK_Interfaces *> Facettes_Interp_FT::ref_interfaces_ protected
Referenced by associer(), cut_cell_perform_interpolation_facettes_next(), and cut_cell_perform_interpolation_facettes_old().
ref_cut_cell_disc_
TRUST_Ref< Cut_cell_FT_Disc *> Facettes_Interp_FT::ref_cut_cell_disc_ protected
Referenced by associer(), cut_cell_perform_interpolation_facettes_next(), and cut_cell_perform_interpolation_facettes_old().
ref_domaine_
TRUST_Ref< Domaine_IJK *> Facettes_Interp_FT::ref_domaine_ protected
Referenced by associer(), cut_cell_perform_interpolation_facettes_next(), cut_cell_perform_interpolation_facettes_old(), get_distance_interpolation_1(), and get_distance_interpolation_2().
ref_maillage_ft_ijk_
TRUST_Ref< Maillage_FT_IJK *> Facettes_Interp_FT::ref_maillage_ft_ijk_ protected
Referenced by associer(), cut_cell_perform_interpolation_facettes_next(), and maillage_ft_ijk().
ref_old_maillage_ft_ijk_
TRUST_Ref< Maillage_FT_IJK *> Facettes_Interp_FT::ref_old_maillage_ft_ijk_ protected
Referenced by associer(), cut_cell_perform_interpolation_facettes_old(), and old_maillage_ft_ijk().
number_of_interpolation_points_
int Facettes_Interp_FT::number_of_interpolation_points_ = 1 protected
Referenced by cut_cell_perform_interpolation_facettes(), get_number_of_interpolation_points(), and set_param().
scaled_distance_interpolation_1_
double Facettes_Interp_FT::scaled_distance_interpolation_1_ = 1.0 protected
Referenced by get_distance_interpolation_1(), get_scaled_distance_interpolation_1(), and set_param().
scaled_distance_interpolation_2_
double Facettes_Interp_FT::scaled_distance_interpolation_2_ = 2.0 protected
Referenced by get_distance_interpolation_2(), get_scaled_distance_interpolation_2(), and set_param().