TrioCFD: Modele_turbulence_hyd_K_Omega Class Reference
Modele_turbulence_hyd_K_Omega Class Reference
#include <Modele_turbulence_hyd_K_Omega.h>
Public Member Functions
virtual Champ_Fonc_base & calculer_viscosite_turbulente (double)
const Transport_K_Omega_base & eqn_transp_K_Omega () const override
Transport_K_Omega_base & eqn_transp_K_Omega () override
DoubleTab & get_enstrophy ()
const DoubleTab & get_enstrophy () const
const Type_info * get_info () const override
DoubleTab & get_tabF1 ()
const DoubleTab & get_tabF1 () const
DoubleTab & get_tabF2 ()
const DoubleTab & get_tabF2 () const
void init_F1_F2_enstrophy ()
virtual Champ_Inc_base & K_Omega ()
virtual const Champ_Inc_base & K_Omega () const
int lire_motcle_non_standard (const Motcle &, Entree &) override
void mettre_a_jour (double) override
int preparer_calcul () override
Public Member Functions inherited from Modele_turbulence_hyd_RANS_K_Omega_base
const Type_info * get_info () const override
int reprendre (Entree &is) override
int sauvegarder (Sortie &os) const override
const Type_info * get_info () const override
Public Member Functions inherited from Modele_turbulence_hyd_base
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Type_info * get_info () const override
virtual void imprimer (Sortie &) const
void lire_distance_paroi ()
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual int preparer_calcul ()
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Protected Member Functions
void fill_turbulent_viscosity_tab (const DoubleTab &K_Omega, DoubleTab &turbulent_viscosity)
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Modele_turbulence_hyd_RANS_K_Omega_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
equations de Navier-Stokes.
See also
Modele_turbulence_hyd_base Modele_turbulence_hyd_LES_base
Constructor & Destructor Documentation
Modele_turbulence_hyd_K_Omega()
Modele_turbulence_hyd_K_Omega::Modele_turbulence_hyd_K_Omega ()
~Modele_turbulence_hyd_K_Omega()
Modele_turbulence_hyd_K_Omega::~Modele_turbulence_hyd_K_Omega ()
Member Function Documentation
cree_instance()
Objet_U * Modele_turbulence_hyd_K_Omega::cree_instance () static
taille_memoire()
unsigned Modele_turbulence_hyd_K_Omega::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Modele_turbulence_hyd_K_Omega::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Modele_turbulence_hyd_K_Omega::info () static
get_info()
const Type_info * Modele_turbulence_hyd_K_Omega::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Modele_turbulence_hyd_2_eq_base.
self_cast() [1/2]
Modele_turbulence_hyd_K_Omega & Modele_turbulence_hyd_K_Omega::self_cast (Objet_U & r) static
self_cast() [2/2]
const Modele_turbulence_hyd_K_Omega & Modele_turbulence_hyd_K_Omega::self_cast (const Objet_U & r) static
printOn()
Sortie & Modele_turbulence_hyd_K_Omega::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Modele_turbulence_hyd_2_eq_base.
References Objet_U::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Modele_turbulence_hyd_K_Omega::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Modele_turbulence_hyd_2_eq_base.
References Navier_Stokes_std::creer_champ(), Modele_turbulence_hyd_base::equation(), is_SST_, Modele_turbulence_hyd_RANS_K_Omega_base::model_variant_, and Modele_turbulence_hyd_RANS_K_Omega_base::readOn().
set_param()
void Modele_turbulence_hyd_K_Omega::set_param (Param & param) override virtual
Reimplemented from Modele_turbulence_hyd_2_eq_base.
References Param::ajouter(), Param::ajouter_non_std(), Modele_turbulence_hyd_RANS_K_Omega_base::model_variant_, Param::OPTIONAL, Modele_turbulence_hyd_2_eq_base::Prandtl_K_, Modele_turbulence_hyd_2_eq_base::Prandtl_Omega_, Param::REQUIRED, and Modele_turbulence_hyd_RANS_K_Omega_base::set_param().
lire_motcle_non_standard()
int Modele_turbulence_hyd_K_Omega::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
< liste stockant tous les noms de frontiere du domaine
Reimplemented from Modele_turbulence_hyd_base.
References Transport_2eq_base::associer_modele_turbulence(), eqn_transp_K_Omega(), and Modele_turbulence_hyd_base::lire_motcle_non_standard().
preparer_calcul()
int Modele_turbulence_hyd_K_Omega::preparer_calcul () override virtual
Prepare the computation of the k-omega model.
Initialise tables if model variant is SST and compute the viscosity limit.
Reimplemented from Modele_turbulence_hyd_base.
References eqn_transp_K_Omega(), init_F1_F2_enstrophy(), is_SST(), K_Omega(), Modele_turbulence_hyd_base::la_viscosite_turbulente_, Equation_base::preparer_calcul(), Modele_turbulence_hyd_base::preparer_calcul(), Champ_Don_base::valeurs(), and Debog::verifier().
initTimeStep()
bool Modele_turbulence_hyd_K_Omega::initTimeStep (double dt) override virtual
Reimplemented from Modele_turbulence_hyd_base.
References eqn_transport_K_Omega_, and Equation_base::initTimeStep().
mettre_a_jour()
void Modele_turbulence_hyd_K_Omega::mettre_a_jour (double temps) override virtual
Performs a time update of the turbulence model.
Update the transport equation of k and omega, computes the wall function and the turbulence viscosity.
Parameters
[in] (double temps) new time
Implements Modele_turbulence_hyd_base.
References Statistiques::begin_count(), Equation_base::domaine_Cl_dis(), Statistiques::end_count(), eqn_transp_K_Omega(), Schema_Temps_base::faire_un_pas_de_temps_eqn_base(), K_Omega(), Modele_turbulence_hyd_base::la_viscosite_turbulente_, Domaine_Cl_dis_base::mettre_a_jour(), Equation_base::mettre_a_jour(), Equation_base::schema_temps(), Champ_Don_base::valeurs(), and Debog::verifier().
K_Omega() [1/2]
Champ_Inc_base & Modele_turbulence_hyd_K_Omega::K_Omega () inline virtual
Renvoie le champ inconnue du modele de turbulence i.
e. : (K, Omega). Cette inconnue est portee par l'equation de transport K-Omega porte par le modele.
Returns
(Champ_Inc_base&) le champ inconnue (K, Omega)
References eqn_transport_K_Omega_, and Transport_K_Omega_base::inconnue().
Referenced by mettre_a_jour(), and preparer_calcul().
K_Omega() [2/2]
const Champ_Inc_base & Modele_turbulence_hyd_K_Omega::K_Omega () const inline virtual
Renvoie le champ inconnue du modele de turbulence i.
e. : (K, Omega). Cette inconnue est portee par l'equation de transport K-Omega porte par le modele. (version const)
Returns
(Champ_Inc_base&) le champ inconnue (K, Omega)
References eqn_transport_K_Omega_, and Transport_K_Omega_base::inconnue().
eqn_transp_K_Omega() [1/2]
Transport_K_Omega_base & Modele_turbulence_hyd_K_Omega::eqn_transp_K_Omega () inline override virtual
Renvoie l'equation du modele de turbulence i.
e. : (K, Omega).
Returns
(Transport_K_Omega&) equation (K, Omega)
Implements Modele_turbulence_hyd_RANS_K_Omega_base.
References eqn_transport_K_Omega_.
Referenced by calculer_viscosite_turbulente(), init_F1_F2_enstrophy(), lire_motcle_non_standard(), mettre_a_jour(), and preparer_calcul().
eqn_transp_K_Omega() [2/2]
const Transport_K_Omega_base & Modele_turbulence_hyd_K_Omega::eqn_transp_K_Omega () const inline override virtual
Renvoie l'equation du modele de turbulence i.
e. : (K, Omega). (version const)
Returns
(Transport_K_Omega&) equation (K, Omega)
Implements Modele_turbulence_hyd_RANS_K_Omega_base.
References eqn_transport_K_Omega_.
init_F1_F2_enstrophy()
void Modele_turbulence_hyd_K_Omega::init_F1_F2_enstrophy ()
Initialise three tabs when turbulence model variant is SST.
The tables F1, F2 and enstrophy are used to computer a blending function. They are initialised with the total (real+virtual) DoF.
References MD_Vector_tools::creer_tableau_distribue(), enstrophy_, eqn_transp_K_Omega(), Domaine_VF::md_vector_faces(), Domaine_VF::nb_faces(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), tabF1_, and tabF2_.
Referenced by preparer_calcul().
get_tabF1() [1/2]
const DoubleTab & Modele_turbulence_hyd_K_Omega::get_tabF1 () const inline
Returns the blending table F1 for SST.
(version const)
Returns
(DoubleTab&) tabF1_
References tabF1_.
get_tabF1() [2/2]
DoubleTab & Modele_turbulence_hyd_K_Omega::get_tabF1 () inline
Returns the blending table F1 for SST.
Returns
(DoubleTab&) tabF1_
References tabF1_.
get_tabF2() [1/2]
const DoubleTab & Modele_turbulence_hyd_K_Omega::get_tabF2 () const inline
Returns the table F2 for SST.
(version const)
Returns
(DoubleTab&) tabF2_
References tabF2_.
get_tabF2() [2/2]
DoubleTab & Modele_turbulence_hyd_K_Omega::get_tabF2 () inline
Returns the table F2 for SST.
Returns
(DoubleTab&) tabF2_
References tabF2_.
get_enstrophy() [1/2]
const DoubleTab & Modele_turbulence_hyd_K_Omega::get_enstrophy () const inline
Returns the field enstrophy.
(version const)
Returns
(DoubleTab&) enstrophy
References enstrophy_.
get_enstrophy() [2/2]
DoubleTab & Modele_turbulence_hyd_K_Omega::get_enstrophy () inline
Returns the field F2.
Returns
(DoubleTab&) tabF2
References enstrophy_.
equation_k_omega()
const Equation_base & Modele_turbulence_hyd_K_Omega::equation_k_omega (int i) const inline override virtual
Implements Modele_turbulence_hyd_RANS_K_Omega_base.
References eqn_transport_K_Omega_.
controler()
void Modele_turbulence_hyd_K_Omega::controler () inline
References Transport_K_Omega_base::controler_K_Omega(), and eqn_transport_K_Omega_.
calculer_viscosite_turbulente()
Champ_Fonc_base & Modele_turbulence_hyd_K_Omega::calculer_viscosite_turbulente (double temps) virtual
Calcule la viscosite turbulente au temps demande.
Parameters
(double temps) le temps auquel il faut calculer la viscosite
Returns
(Champ_Fonc_base&) la viscosite turbulente au temps demande
Exceptions
erreur de taille de visco_turb_K_omega
References Champ_base::affecter(), Champ_base::changer_temps(), Modele_turbulence_hyd_RANS_Gen< Modele_turbulence_hyd_K_Omega >::complete_viscosity_field(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Domaine_dis_base::domaine(), Equation_base::domaine_dis(), eqn_transp_K_Omega(), Process::exit(), fill_turbulent_viscosity_tab(), Transport_K_Omega_base::inconnue(), Modele_turbulence_hyd_base::la_viscosite_turbulente_, Process::mp_max(), Domaine_32_64< _SIZE_ >::nb_elem(), Objet_U::que_suis_je(), TRUSTVect< _TYPE_, _SIZE_ >::size(), Champ_Don_base::valeurs(), Champ_Proto::valeurs(), and Debog::verifier().
is_SST()
bool Modele_turbulence_hyd_K_Omega::is_SST () const inline
References is_SST_.
Referenced by fill_turbulent_viscosity_tab(), and preparer_calcul().
fill_turbulent_viscosity_tab()
void Modele_turbulence_hyd_K_Omega::fill_turbulent_viscosity_tab (const DoubleTab & tab_K_Omega, DoubleTab & turbulent_viscosity) protected
Fill the turbulent viscosity table depending on the model.
If omega is lower that the threshold OMEGA_MIN_, turbulent viscosity is null. If the model variant is SST, a special inverse time scale is computed in place of omega.
Parameters
[in] (tab_K_Omega_dim0) the dimension(0) of the K_Omega table, i.e. the number of face or elements.
[in] (tab_K_Omega&) the table containing the turbulent kinetic and the inverse time scale omega
[in] (turbulent_viscosity&) the turbulent viscosity table
References Modele_turbulence_hyd_RANS_K_Omega_base::CST_A1, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), enstrophy_, is_SST(), Modele_turbulence_hyd_2_eq_base::OMEGA_MIN_, and tabF2_.
Referenced by calculer_viscosite_turbulente().
Member Data Documentation
info_obj
const Type_info Modele_turbulence_hyd_K_Omega::info_obj static
eqn_transport_K_Omega_
Transport_K_Omega Modele_turbulence_hyd_K_Omega::eqn_transport_K_Omega_ protected
Referenced by controler(), eqn_transp_K_Omega(), equation_k_omega(), initTimeStep(), and K_Omega().
tabF1_
DoubleTab Modele_turbulence_hyd_K_Omega::tabF1_ protected
Referenced by get_tabF1(), and init_F1_F2_enstrophy().
tabF2_
DoubleTab Modele_turbulence_hyd_K_Omega::tabF2_ protected
Referenced by fill_turbulent_viscosity_tab(), get_tabF2(), and init_F1_F2_enstrophy().
enstrophy_
DoubleTab Modele_turbulence_hyd_K_Omega::enstrophy_ protected
Referenced by fill_turbulent_viscosity_tab(), get_enstrophy(), and init_F1_F2_enstrophy().
is_SST_
bool Modele_turbulence_hyd_K_Omega::is_SST_ protected
Referenced by is_SST(), and readOn().