TrioCFD: Aretes Class Reference
Aretes Class Reference
#include <Aretes.h>
Public Member Functions
void affecter (int &, int, int, int, int, int, int, int, const ArrOfInt &)
IntTab & faces ()
const Type_info * get_info () const override
void trier (int &, int &, int &, int &)
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Aretes() [1/2]
Aretes::Aretes ()
~Aretes()
Aretes::~Aretes ()
Aretes() [2/2]
Aretes::Aretes (int n) inline
Constructeur : dimensionne les tableaux.
Member Function Documentation
cree_instance()
Objet_U * Aretes::cree_instance () static
taille_memoire()
unsigned Aretes::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Aretes::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Aretes::info () static
get_info()
const Type_info * Aretes::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
Aretes & Aretes::self_cast (Objet_U & r) static
self_cast() [2/2]
const Aretes & Aretes::self_cast (const Objet_U & r) static
printOn()
Sortie & Aretes::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
readOn()
Entree & Aretes::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
affecter()
void Aretes::affecter (int & numero_a, int dir, int type, int nb_face, int f1, int f2, int f3, int f4, const ArrOfInt & est_une_plaque)
affecte a l'arete numero les faces f1, f2, f3, f4
l'arete est de type2_ type ou : type2_ = -1 si arete coin type2_ = 0 si arete bord type2_ = 1 si arete mixte type2_ = 2 si arete interne l'arete est de type1_ dir ou : type1_ = 0 si arete XY type1_ = 1 si arete XZ type1_ = 2 si arete YZ En dimension 2 il n'y a que des aretes XY
faces()
IntTab & Aretes::faces () inline
retourne le tableau (IntTab) des faces de dimension nb_aretes,4
faces(num_arete,i) 0 <= i <= 3: numeros des 4 faces qui se partagent l'arete num_arete Pour une arete interne les 4 faces existent Pour une arete bord un ou deux des numeros valent -1.
dimensionner()
void Aretes::dimensionner (int n)
Dimensionne les tableaux.
References TRUSTTab< _TYPE_, _SIZE_ >::resize(), and TRUSTVect< _TYPE_, _SIZE_ >::resize().
trier()
void Aretes::trier (int & nb_aretes_coin, int & nb_aretes_bord, int & nb_aretes_mixte, int & nb_aretes_interne)
reoordonne le tableaux des aretes avec d'abord les aretes coins (elles n'ont que deux faces)
puis les aretes bord (elles ont trois faces dont deux de bord) puis les aretes mixte (elles ont quatre faces dont deux de bord) puis les aretes_internes (elles ont quatre faces internes)
References TRUSTVect< _TYPE_, _SIZE_ >::size().
trier_pour_debog()
void Aretes::trier_pour_debog (int & nb_aretes_coin, int & nb_aretes_bord, int & nb_aretes_mixte, int & nb_aretes_interne, const DoubleTab & xv)
References Objet_U::dimension, Process::exit(), Process::me(), and TRUSTVect< _TYPE_, _SIZE_ >::size().
calculer_centre_de_gravite()
void Aretes::calculer_centre_de_gravite (Domaine_VDF & domaine)
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Process::exit(), and TRUSTTab< _TYPE_, _SIZE_ >::resize().
Member Data Documentation
info_obj
const Type_info Aretes::info_obj static