TrioCFD: Frontiere_ouverte_temperature_imposee_rayo_semi_transp Class Reference
Frontiere_ouverte_temperature_imposee_rayo_semi_transp Class Reference
#include <Frontiere_ouverte_temperature_imposee_rayo_semi_transp.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Cond_Lim_rayo_semi_transp
virtual void associer_modele (const Modele_rayo_semi_transp &)
Modele_rayo_semi_transp & modele ()
const Modele_rayo_semi_transp & modele () const
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Dirichlet
const Type_info * get_info () const override
virtual double val_imp (int i) const
virtual double val_imp (int i, int j) const
void verifie_ch_init_nb_comp () const override
Public Member Functions inherited from Cond_lim_base
virtual int a_mettre_a_jour_ss_pas_dt ()
virtual void associer_domaine_cl_dis_base (const Domaine_Cl_dis_base &)
virtual void associer_fr_dis_base (const Frontiere_dis_base &)
virtual void calculer_coeffs_echange (double temps)
virtual int compatible_avec_discr (const Discretisation_base &) const
Domaine_Cl_dis_base & domaine_Cl_dis ()
const Domaine_Cl_dis_base & domaine_Cl_dis () const
virtual Frontiere_dis_base & frontiere_dis ()
virtual const Frontiere_dis_base & frontiere_dis () const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
void set_modifier_val_imp (int)
virtual void verifie_ch_init_nb_comp () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Cond_lim_base
void err_pas_compatible (const Discretisation_base &) const
void err_pas_compatible (const Equation_base &) const
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
.SECTION
Constructor & Destructor Documentation
Frontiere_ouverte_temperature_imposee_rayo_semi_transp()
Frontiere_ouverte_temperature_imposee_rayo_semi_transp::Frontiere_ouverte_temperature_imposee_rayo_semi_transp ()
~Frontiere_ouverte_temperature_imposee_rayo_semi_transp()
Frontiere_ouverte_temperature_imposee_rayo_semi_transp::~Frontiere_ouverte_temperature_imposee_rayo_semi_transp ()
Member Function Documentation
cree_instance()
Objet_U * Frontiere_ouverte_temperature_imposee_rayo_semi_transp::cree_instance () static
taille_memoire()
unsigned Frontiere_ouverte_temperature_imposee_rayo_semi_transp::taille_memoire () const override virtual
Reimplemented from Entree_fluide_temperature_imposee.
duplique()
int Frontiere_ouverte_temperature_imposee_rayo_semi_transp::duplique () const override virtual
Reimplemented from Entree_fluide_temperature_imposee.
info()
const Type_info * Frontiere_ouverte_temperature_imposee_rayo_semi_transp::info () static
get_info()
const Type_info * Frontiere_ouverte_temperature_imposee_rayo_semi_transp::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Entree_fluide_temperature_imposee.
self_cast() [1/2]
Frontiere_ouverte_temperature_imposee_rayo_semi_transp & Frontiere_ouverte_temperature_imposee_rayo_semi_transp::self_cast (Objet_U & r) static
self_cast() [2/2]
const Frontiere_ouverte_temperature_imposee_rayo_semi_transp & Frontiere_ouverte_temperature_imposee_rayo_semi_transp::self_cast (const Objet_U & r) static
printOn()
Sortie & Frontiere_ouverte_temperature_imposee_rayo_semi_transp::printOn (Sortie & os) const override protected virtual
Parameters
(Sortie& os) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Entree_fluide_temperature_imposee.
readOn()
Entree & Frontiere_ouverte_temperature_imposee_rayo_semi_transp::readOn (Entree & is) override protected virtual
Lecture des parametres de la condition Neumann_paroi.
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Entree_fluide_temperature_imposee.
References Entree_fluide_temperature_imposee::readOn().
la_cl()
const Cond_lim_base & Frontiere_ouverte_temperature_imposee_rayo_semi_transp::la_cl () const override virtual
Implements Cond_Lim_rayo_semi_transp.
completer()
void Frontiere_ouverte_temperature_imposee_rayo_semi_transp::completer () override virtual
NE FAIT RIEN A surcharger dans les classes derivees.
Reimplemented from Cond_lim_base.
References Cond_lim_base::completer().
compatible_avec_eqn()
int Frontiere_ouverte_temperature_imposee_rayo_semi_transp::compatible_avec_eqn (const Equation_base &) const inline override virtual
Reimplemented from Cond_lim_base.
temperature_bord() [1/2]
Champ_front_base & Frontiere_ouverte_temperature_imposee_rayo_semi_transp::temperature_bord () inline
References Cond_lim_base::le_champ_front.
Referenced by Flux_radiatif_VDF::calculer_flux_radiatif(), Flux_radiatif_VEF::calculer_flux_radiatif(), Eq_rayo_semi_transp_VDF::evaluer_cl_rayonnement(), and Eq_rayo_semi_transp_VEF::evaluer_cl_rayonnement().
temperature_bord() [2/2]
const Champ_front_base & Frontiere_ouverte_temperature_imposee_rayo_semi_transp::temperature_bord () const inline
References Cond_lim_base::le_champ_front.
calculer_temperature_bord()
void Frontiere_ouverte_temperature_imposee_rayo_semi_transp::calculer_temperature_bord (double temps)
Referenced by Eq_rayo_semi_transp_VDF::evaluer_cl_rayonnement(), and Eq_rayo_semi_transp_VEF::evaluer_cl_rayonnement().
Member Data Documentation
info_obj
const Type_info Frontiere_ouverte_temperature_imposee_rayo_semi_transp::info_obj static