TrioCFD: Reordonner_faces_periodiques_32_64< _SIZE_ > Class Template Reference
Reordonner_faces_periodiques_32_64< _SIZE_ > Class Template Reference
#include <Reordonner_faces_periodiques.h>
Static Public Member Functions
static int check_faces_periodiques (const Frontiere_32_64< _SIZE_ > &frontiere, ArrOfDouble &vecteur_delta, ArrOfDouble &erreur, bool verbose=false)
static int reordonner_faces_periodiques (const Domaine_32_64< _SIZE_ > &domaine, IntTab_T< _SIZE_ > &faces, const ArrOfDouble &direction_perio, const double epsilon)
Static Public Member Functions inherited from Interprete
static Objet_U & objet (const Nom &)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Additional Inherited Members
Public Member Functions inherited from Interprete_geometrique_base_32_64< _SIZE_ >
const Type_info * get_info () const override
void mettre_a_jour_sous_domaine (Domaine_t &domaine, int_t &elem, int_t num_premier_elem, int_t nb_elem) const
Public Member Functions inherited from Interprete
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions inherited from Interprete_geometrique_base_32_64< _SIZE_ >
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Interprete
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
template<typename _SIZE_>
class Reordonner_faces_periodiques_32_64< _SIZE_ >
meme ordre, les faces jumelles sur le bord oppose).
Member Typedef Documentation
int_t
template<typename _SIZE_ > using Reordonner_faces_periodiques_32_64< _SIZE_ >::int_t = _SIZE_
Member Function Documentation
reordonner_faces_periodiques()
template<typename _SIZE_ > int Reordonner_faces_periodiques_32_64< _SIZE_ >::reordonner_faces_periodiques (const Domaine_32_64< _SIZE_ > & domaine, IntTab_T< _SIZE_ > & faces, const ArrOfDouble & direction_perio, const double epsilon) static
Reordonne le tableau "faces" selon la convention des faces periodiques: D'abord les faces d'une extremite, puis dans le meme ordre, les faces jumelles.
Attention, l'algorithme est en n carre (lent), et ne fonctionne qu'en sequentiel.
Parameters
(domaine) le domaine a laquelle appartiennent les faces
(direction_perio) le vecteur qui separe le centre d'une face au centre de la face opposee
(faces) le tableau des faces (pour chaque face, indices de ses sommets) a reordonner Valeur de retour: 1 si ok, 0 si on n'a pas trouve de face jumelle a une face a precision_geom pres.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension().
Referenced by MaillerParallel::interpreter(), Corriger_frontiere_periodique_32_64< _SIZE_ >::interpreter_(), and Scatter::lire_domaine().
check_faces_periodiques()
template<typename _SIZE_ > int Reordonner_faces_periodiques_32_64< _SIZE_ >::check_faces_periodiques (const Frontiere_32_64< _SIZE_ > & frontiere, ArrOfDouble & vecteur_delta, ArrOfDouble & erreur, bool verbose = false) static
essaie de verifier si les faces du bord num_bord sont ordonnees suivant la convention des faces periodiques.
On stocke dans vecteur_delta la direction de periodicite presumee (intervalle mesure entre la premiere face et la face jumelle), et erreur le max de l'erreur par rapport a cette mesure pour les autres faces. En parallele, l'erreur est le max sur tous les processeurs Valeur de retour: 1 si ok, 0 si l'erreur est superieure a precision_geom.
References Process::barrier(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Frontiere_32_64< _SIZE_ >::domaine(), Frontiere_32_64< _SIZE_ >::faces(), Process::is_parallel(), Process::je_suis_maitre(), Frontiere_32_64< _SIZE_ >::le_nom(), Domaine_32_64< _SIZE_ >::les_sommets(), Faces_32_64< _SIZE_ >::les_sommets(), Process::mp_max(), Objet_U::precision_geom, and TRUSTArray< _TYPE_, _SIZE_ >::resize_array().
Referenced by Partitionneur_base_32_64< _SIZE_ >::calculer_graphe_connexions_periodiques(), Partitionneur_Tranche_32_64< _SIZE_ >::chercher_direction_perio(), and Periodique::completer().
renum_som_perio()
template<typename _SIZE_ > void Reordonner_faces_periodiques_32_64< _SIZE_ >::renum_som_perio (const Domaine_32_64< _SIZE_ > & dom, const Noms & liste_bords_periodiques, ArrOfInt_T< _SIZE_ > & renum_som_perio, bool calculer_espace_virtuel) static
References TRUSTTab< _TYPE_, _SIZE_ >::dimension_int(), Process::exit(), Process::is_parallel(), Frontiere_32_64< _SIZE_ >::les_sommets_des_faces(), Process::me(), and Objet_U::precision_geom.
Referenced by Scatter::calculer_espace_distant_sommets(), and Partitionneur_base_32_64< _SIZE_ >::corriger_bords_avec_graphe().
chercher_direction_perio()
template<typename _SIZE_ > void Reordonner_faces_periodiques_32_64< _SIZE_ >::chercher_direction_perio (ArrOfDouble & direction_perio, const Domaine_32_64< _SIZE_ > & dom, const Nom & bord) static
References Domaine_32_64< _SIZE_ >::coord_sommets(), Domaine_32_64< _SIZE_ >::frontiere(), Domaine_base::le_nom(), Frontiere_32_64< _SIZE_ >::nb_faces(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), and Domaine_32_64< _SIZE_ >::type_elem().
Referenced by Corriger_frontiere_periodique_32_64< _SIZE_ >::interpreter_(), and Scatter::lire_domaine().