TrioCFD: Frontiere_ouverte_vitesse_vortex Class Reference
Frontiere_ouverte_vitesse_vortex Class Reference
#include <Frontiere_ouverte_vitesse_vortex.h>
Public Member Functions
const Type_info * get_info () const override
void mettre_a_jour (double temps) override
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Dirichlet
const Type_info * get_info () const override
virtual double val_imp (int i) const
virtual double val_imp (int i, int j) const
void verifie_ch_init_nb_comp () const override
Public Member Functions inherited from Cond_lim_base
virtual int a_mettre_a_jour_ss_pas_dt ()
virtual void associer_domaine_cl_dis_base (const Domaine_Cl_dis_base &)
virtual void associer_fr_dis_base (const Frontiere_dis_base &)
virtual void calculer_coeffs_echange (double temps)
virtual int compatible_avec_discr (const Discretisation_base &) const
Domaine_Cl_dis_base & domaine_Cl_dis ()
const Domaine_Cl_dis_base & domaine_Cl_dis () const
virtual Frontiere_dis_base & frontiere_dis ()
virtual const Frontiere_dis_base & frontiere_dis () const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
void set_modifier_val_imp (int)
virtual void verifie_ch_init_nb_comp () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Cond_lim_base
void err_pas_compatible (const Discretisation_base &) const
void err_pas_compatible (const Equation_base &) const
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Frontiere_ouverte_vitesse_vortex()
Frontiere_ouverte_vitesse_vortex::Frontiere_ouverte_vitesse_vortex ()
~Frontiere_ouverte_vitesse_vortex()
Frontiere_ouverte_vitesse_vortex::~Frontiere_ouverte_vitesse_vortex ()
Member Function Documentation
cree_instance()
Objet_U * Frontiere_ouverte_vitesse_vortex::cree_instance () static
taille_memoire()
unsigned Frontiere_ouverte_vitesse_vortex::taille_memoire () const override virtual
Reimplemented from Entree_fluide_vitesse_imposee.
duplique()
int Frontiere_ouverte_vitesse_vortex::duplique () const override virtual
Reimplemented from Entree_fluide_vitesse_imposee.
info()
const Type_info * Frontiere_ouverte_vitesse_vortex::info () static
get_info()
const Type_info * Frontiere_ouverte_vitesse_vortex::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Entree_fluide_vitesse_imposee.
self_cast() [1/2]
Frontiere_ouverte_vitesse_vortex & Frontiere_ouverte_vitesse_vortex::self_cast (Objet_U & r) static
self_cast() [2/2]
const Frontiere_ouverte_vitesse_vortex & Frontiere_ouverte_vitesse_vortex::self_cast (const Objet_U & r) static
printOn()
Sortie & Frontiere_ouverte_vitesse_vortex::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Entree_fluide_vitesse_imposee.
readOn()
Entree & Frontiere_ouverte_vitesse_vortex::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Entree_fluide_vitesse_imposee.
References Param::ajouter(), coeff_vitesse_, Objet_U::dimension, Process::exit(), integrale_reference_, Cond_lim_base::le_champ_front, Param::lire_avec_accolades_depuis(), nom_equation_, nom_sous_domaine_, Objet_U::que_suis_je(), Param::REQUIRED, signe_, and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
mettre_a_jour()
void Frontiere_ouverte_vitesse_vortex::mettre_a_jour (double temps) override virtual
Effectue une mise a jour en temps de la condition aux limites.
Parameters
(double temps) le pas de temps de mise a jour
Reimplemented from Cond_lim_base.
References coeff_vitesse_, Objet_U::dimension, Domaine_Cl_dis_base::domaine(), Cond_lim_base::domaine_Cl_dis(), Domaine_Cl_dis_base::domaine_dis(), MorEqn::equation(), Probleme_base::get_equation_by_name(), Transport_Interfaces_FT_Disc::inconnue(), integrale_reference_, Cond_lim_base::le_champ_front, Champ_front_base::mettre_a_jour(), Sous_Domaine_32_64< _SIZE_ >::nb_elem_tot(), nom_equation_, nom_sous_domaine_, Equation_base::probleme(), signe_, Domaine_32_64< _SIZE_ >::ss_domaine(), Champ_front_base::valeurs(), and Champ_Inc_base::valeurs().
Member Data Documentation
info_obj
const Type_info Frontiere_ouverte_vitesse_vortex::info_obj static
nom_sous_domaine_
Nom Frontiere_ouverte_vitesse_vortex::nom_sous_domaine_ protected
Referenced by mettre_a_jour(), and readOn().
nom_equation_
Nom Frontiere_ouverte_vitesse_vortex::nom_equation_ protected
Referenced by mettre_a_jour(), and readOn().
integrale_reference_
double Frontiere_ouverte_vitesse_vortex::integrale_reference_ protected
Referenced by mettre_a_jour(), and readOn().
signe_
int Frontiere_ouverte_vitesse_vortex::signe_ protected
Referenced by mettre_a_jour(), and readOn().
coeff_vitesse_
ArrOfDouble Frontiere_ouverte_vitesse_vortex::coeff_vitesse_ protected
Referenced by mettre_a_jour(), and readOn().