TrioCFD: Source_Frottement_interfacial_base Class Reference
Source_Frottement_interfacial_base Class Reference abstract
#include <Source_Frottement_interfacial_base.h>
Public Member Functions
void completer () override
const Type_info * get_info () const override
Public Member Functions inherited from Sources_Multiphase_base
const Type_info * get_info () const override
void mettre_a_jour (double temps) override
Public Member Functions inherited from Source_base
virtual int a_pour_Champ_Fonc (const Motcle &mot, TRUST_Ref< Champ_base * > &ch_ref) const
virtual void associer_champ_rho (const Champ_base &champ_rho)
virtual void completer ()
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
virtual void resetTime (double t)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Sources_Multiphase_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
Cette classe implemente un operateur de frottement interfacial
de la forme F_{kl} = - F_{lk} = - C_{kl} (u_k - u_l) le calcul de C_{kl} est realise par la hierarchie Coefficient_Frottement_interfacial_base
See also
Source_base
Constructor & Destructor Documentation
Source_Frottement_interfacial_base()
Source_Frottement_interfacial_base::Source_Frottement_interfacial_base ()
~Source_Frottement_interfacial_base()
Source_Frottement_interfacial_base::~Source_Frottement_interfacial_base () override
Member Function Documentation
info()
const Type_info * Source_Frottement_interfacial_base::info () static
get_info()
const Type_info * Source_Frottement_interfacial_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Source_base.
Reimplemented in Frottement_interfacial_VDF.
self_cast() [1/2]
Source_Frottement_interfacial_base & Source_Frottement_interfacial_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Source_Frottement_interfacial_base & Source_Frottement_interfacial_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Source_Frottement_interfacial_base::printOn (Sortie & os) const override protected virtual
DOES NOTHING - to override in derived classes.
Imprime la source sur un flot de sortie.
Parameters
(Sortie& os) le flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Source_base.
Reimplemented in Frottement_interfacial_VDF.
readOn()
Entree & Source_Frottement_interfacial_base::readOn (Entree & is) override protected virtual
DOES NOTHING - to override in derived classes.
Lecture d'un terme source sur un flot d'entree.
Parameters
(Entree& is) le flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Source_base.
Reimplemented in Frottement_interfacial_VDF.
References a_res_, Param::ajouter(), beta_, correlation_, dv_min, MorEqn::equation(), Process::exit(), exp_res, Probleme_base::get_correlation(), Probleme_base::has_correlation(), Param::lire_avec_accolades_depuis(), Objet_U::que_suis_je(), Pb_Multiphase::resolution_en_T(), and Correlation_base::typer_lire_correlation().
Referenced by Frottement_interfacial_PolyMAC_P0::readOn(), and Frottement_interfacial_VDF::readOn().
dimensionner_blocs()
void Source_Frottement_interfacial_base::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl = {}) const override virtual
Reimplemented from Source_base.
References Matrix_tools::allocate_morse_matrix(), TRUSTTab< _TYPE_, _SIZE_ >::append_line(), dimensionner_blocs_aux(), MorEqn::equation(), Champ_Face_base::fcl(), Nom::getString(), Field_base::le_nom(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Matrice_Morse::nb_colonnes(), TRUSTVect< _TYPE_, _SIZE_ >::size_totale(), and Champ_Inc_base::valeurs().
ajouter_blocs()
void Source_Frottement_interfacial_base::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = {}) const override pure virtual
Reimplemented from Source_base.
Implemented in Frottement_interfacial_PolyMAC_P0, and Frottement_interfacial_VDF.
completer()
void Source_Frottement_interfacial_base::completer () override virtual
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees: Source_base::associer_domaines(const Domaine_dis_base& ,const Domaine_Cl_dis_base&) Source_base::associer_pb(const Probleme_base&)
Reimplemented from Source_base.
References a_res_, and MorEqn::equation().
dimensionner_blocs_aux()
virtual void Source_Frottement_interfacial_base::dimensionner_blocs_aux (IntTab &) const inline protected virtual
Reimplemented in Frottement_interfacial_PolyMAC_P0.
Referenced by dimensionner_blocs().
Member Data Documentation
info_obj
const Type_info Source_Frottement_interfacial_base::info_obj static
correlation_
TRUST_Deriv< Correlation_base > Source_Frottement_interfacial_base::correlation_ protected
Referenced by Frottement_interfacial_PolyMAC_P0::ajouter_blocs(), Frottement_interfacial_VDF::ajouter_blocs(), and readOn().
a_res_
double Source_Frottement_interfacial_base::a_res_ = -1. protected
Referenced by Frottement_interfacial_PolyMAC_P0::ajouter_blocs(), Frottement_interfacial_VDF::ajouter_blocs(), completer(), and readOn().
dv_min
double Source_Frottement_interfacial_base::dv_min = 0.01 protected
Referenced by Frottement_interfacial_PolyMAC_P0::ajouter_blocs(), Frottement_interfacial_VDF::ajouter_blocs(), and readOn().
beta_
double Source_Frottement_interfacial_base::beta_ = 1. protected
Referenced by Frottement_interfacial_PolyMAC_P0::ajouter_blocs(), and readOn().
exp_res
int Source_Frottement_interfacial_base::exp_res = 2 protected
Referenced by Frottement_interfacial_PolyMAC_P0::ajouter_blocs(), Frottement_interfacial_VDF::ajouter_blocs(), and readOn().