TrioCFD: Terme_Puissance_Thermique Class Reference
Terme_Puissance_Thermique Class Reference
#include <Terme_Puissance_Thermique.h>
Public Member Functions
void lire_donnees (Entree &, const Equation_base &eqn)
Detailed Description
du type degagement volumique de puissance thermique. Un objet Terme_Puissance_Thermique contient la puissance (OWN_PTR(Champ_base) donne utilisateur) et des references a la masse volumique (rho) et la chaleur. specifique (Cp).
See also
Classe non instanciable., L'implementation des termes dependra de leur discretisation.
Member Function Documentation
lire_donnees()
void Terme_Puissance_Thermique::lire_donnees (Entree & is, const Equation_base & eqn)
Lit le terme de puissance thermique a partir d'un flot d'entree et d une equation pour eventuellement.
acceder a la discretisation afin de typer la_puissance. Lit uniquement un champ donne representant la_puissance.
Parameters
(Entree& is) un flot d'entree
References Champ_base::affecter(), Equation_base::discretisation(), Probleme_base::discretisation(), Discretisation_base::discretiser_champ(), Equation_base::domaine_dis(), Field_base::fixer_nb_comp(), Field_base::fixer_nom_compo(), Discretisation_base::is_dg(), Discretisation_base::is_polymac_family(), Discretisation_base::is_vdf(), Discretisation_base::is_vef(), la_puissance, la_puissance_lu, Field_base::le_nom(), Field_base::nb_comp(), Field_base::nommer(), Discretisation_base::nommer_completer_champ_physique(), Equation_base::probleme(), Objet_U_ptr::typer(), TRUST_Deriv< _CLASSE_ >::valeur(), and Champ_Don_base::valeurs().
Referenced by Terme_Puissance_Thermique_DG_base::readOn(), Puissance_Thermique_EF::readOn(), Puissance_Thermique_QC_EF::readOn(), Terme_Puissance_Thermique_PolyMAC_base::readOn(), Terme_Puissance_Thermique_VDF_base::readOn(), and Terme_Puissance_Thermique_VEF_base::readOn().
mettre_a_jour()
void Terme_Puissance_Thermique::mettre_a_jour (double temps)
References Champ_base::affecter(), la_puissance, la_puissance_lu, Champ_Don_base::mettre_a_jour(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by Terme_Puissance_Thermique_DG_Elem::mettre_a_jour(), Puissance_Thermique_EF::mettre_a_jour(), Puissance_Thermique_QC_EF::mettre_a_jour(), Terme_Puissance_Thermique_PolyMAC_Elem::mettre_a_jour(), Source_Dirac_VDF_Elem::mettre_a_jour(), Terme_Puissance_Thermique_QC_VDF_Elem::mettre_a_jour(), Terme_Puissance_Thermique_VDF_Elem::mettre_a_jour(), Source_Dirac_VEF_Face::mettre_a_jour(), Terme_Puissance_Thermique_QC_VEF_Face::mettre_a_jour(), Terme_Puissance_Thermique_VEF_Face::mettre_a_jour(), and resetTime().
modify_name_file()
void Terme_Puissance_Thermique::modify_name_file (Nom & fichier) const
References la_puissance, and Objet_U_ptr::le_nom().
Referenced by Terme_Puissance_Thermique_DG_base::readOn(), Terme_Puissance_Thermique_PolyMAC_base::readOn(), Terme_Puissance_Thermique_VDF_base::readOn(), and Terme_Puissance_Thermique_VEF_base::readOn().
puissance_thermique()
const DoubleTab & Terme_Puissance_Thermique::puissance_thermique () const inline
References la_puissance, and Champ_Don_base::valeurs().
initialiser_champ_puissance()
void Terme_Puissance_Thermique::initialiser_champ_puissance (const Equation_base & eqn)
References Equation_base::domaine_Cl_dis(), Equation_base::domaine_dis(), Champ_val_tot_sur_vol_base::evaluer(), la_puissance_lu, and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by Terme_Puissance_Thermique_DG_base::initialiser(), Terme_Puissance_Thermique_PolyMAC_base::initialiser(), Terme_Puissance_Thermique_VDF_base::initialiser(), and Terme_Puissance_Thermique_VEF_base::initialiser().
resetTime()
void Terme_Puissance_Thermique::resetTime (double t)
References mettre_a_jour().
Referenced by Puissance_Thermique_EF::resetTime(), and Terme_Puissance_Thermique_VDF_base::resetTime().
Member Data Documentation
la_puissance_lu
TRUST_Deriv< Champ_Don_base > Terme_Puissance_Thermique::la_puissance_lu protected
Referenced by initialiser_champ_puissance(), lire_donnees(), mettre_a_jour(), Puissance_Thermique_EF::readOn(), and Terme_Puissance_Thermique_VDF_base::readOn().
la_puissance
TRUST_Deriv< Champ_Don_base > Terme_Puissance_Thermique::la_puissance protected
Referenced by Terme_Puissance_Thermique_DG_Elem::associer_pb(), Puissance_Thermique_EF::associer_pb(), Puissance_Thermique_QC_EF::associer_pb(), Terme_Puissance_Thermique_PolyMAC_Elem::associer_pb(), Source_Dirac_VDF_Elem::associer_pb(), Source_Neutronique_VDF::associer_pb(), Terme_Puissance_Thermique_QC_VDF_Elem::associer_pb(), Terme_Puissance_Thermique_VDF_Elem::associer_pb(), Source_Dirac_VEF_Face::associer_pb(), Terme_Puissance_Thermique_QC_VEF_Face::associer_pb(), Terme_Puissance_Thermique_VEF_Face::associer_pb(), lire_donnees(), mettre_a_jour(), Source_Neutronique::mettre_a_jour(), modify_name_file(), puissance_thermique(), Terme_Puissance_Thermique_DG_base::readOn(), Puissance_Thermique_EF::readOn(), Puissance_Thermique_QC_EF::readOn(), Terme_Puissance_Thermique_PolyMAC_base::readOn(), Source_Neutronique::readOn(), Terme_Puissance_Thermique_VDF_base::readOn(), and Terme_Puissance_Thermique_VEF_base::readOn().