TrioCFD: Ch_front_input_uniforme Class Reference
Ch_front_input_uniforme Class Reference
#include <Ch_front_input_uniforme.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Champ_front_instationnaire_base
int avancer (double temps) override
const Type_info * get_info () const override
int initialiser (double temps, const Champ_Inc_base &inco) override
int reculer (double temps) override
const DoubleTab & valeurs_au_temps (double temps) const override
DoubleTab & valeurs_au_temps (double temps) override
void valeurs_face (int, DoubleVect &) const override
Public Member Functions inherited from Champ_front_base
virtual void associer_fr_dis_base (const Frontiere_dis_base &)
virtual int avancer (double temps)
virtual void calculer_coeffs_echange (double temps)
virtual void fixer_nb_valeurs_temporelles (int nb_cases)
virtual Frontiere_dis_base & frontiere_dis ()
virtual const Frontiere_dis_base & frontiere_dis () const
const Type_info * get_info () const override
virtual int initialiser (double temps, const Champ_Inc_base &inco)
virtual void mettre_a_jour (double temps)
virtual int reculer (double temps)
virtual const DoubleTab & valeurs () const override
virtual DoubleTab & valeurs () override
virtual void valeurs_face (int, DoubleVect &) const
Public Member Functions inherited from Field_base
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
virtual void fixer_nb_comp (int i)
virtual const Nom & fixer_nom_compo (const Nom &)
virtual const Nom & fixer_nom_compo (int, const Nom &)
virtual const Noms & fixer_noms_compo (const Noms &)
virtual const Nom & fixer_unite (const Nom &)
virtual const Nom & fixer_unite (int i, const Nom &)
virtual const Noms & fixer_unites (const Noms &)
const Type_info * get_info () const override
const Nom & nom_compo (int) const
void nommer (const Nom &) override
const Nom & unite () const
const Nom & unite (int) const
const Noms & unites () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Champ_Proto
int lire_dimension (Entree &, const Nom &)
int lire_dimension (int dim, const Nom &le_nom_)
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Champ_front_instationnaire_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Field_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Champ_Input_Proto
void read (Entree &is)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
Cette classe represente un champ accessible par setInputField
uniforme sur une frontiere.
See also
Champ_Input_Proto
Constructor & Destructor Documentation
Ch_front_input_uniforme()
Ch_front_input_uniforme::Ch_front_input_uniforme ()
~Ch_front_input_uniforme()
Ch_front_input_uniforme::~Ch_front_input_uniforme ()
Member Function Documentation
cree_instance()
Objet_U * Ch_front_input_uniforme::cree_instance () static
taille_memoire()
unsigned Ch_front_input_uniforme::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Ch_front_input_uniforme::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Ch_front_input_uniforme::info () static
get_info()
const Type_info * Ch_front_input_uniforme::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
Ch_front_input_uniforme & Ch_front_input_uniforme::self_cast (Objet_U & r) static
self_cast() [2/2]
const Ch_front_input_uniforme & Ch_front_input_uniforme::self_cast (const Objet_U & r) static
printOn()
Sortie & Ch_front_input_uniforme::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
readOn()
Entree & Ch_front_input_uniforme::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
References Champ_Input_Proto::mon_pb, Champ_Input_Proto::read(), and Champ_Input_Proto::sous_domaine_ok.
initialiser()
int Ch_front_input_uniforme::initialiser (double temps, const Champ_Inc_base & inco) override virtual
By default initializes to zero.
Reimplemented from Champ_front_base.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Champ_Input_Proto::initial_value_, Champ_front_instationnaire_base::initialiser(), Champ_front_base::les_valeurs, Roue::nb_cases(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
affecter_()
Champ_front_base & Ch_front_input_uniforme::affecter_ (const Champ_front_base &) inline override virtual
Implements Champ_front_base.
getTemplate()
void Ch_front_input_uniforme::getTemplate (TrioField & afield) const override virtual
Provides afield with a dummy geometry, a name, a time interval, components, and no field ownership.
Implements Champ_Input_Proto.
References Field_base::le_nom(), Champ_Input_Proto::mon_pb, and Field_base::nb_comp().
setValue()
void Ch_front_input_uniforme::setValue (const TrioField & afield) override virtual
Uses the first value in afield as uniform value, regardless of geometry.
Implements Champ_Input_Proto.
References Champ_front_base::calculer_derivee_en_temps(), Champ_front_base::les_valeurs, Roue::nb_cases(), Champ_Input_Proto::setValueOnTab(), and Champ_front_base::valeurs().
set_nb_comp()
void Ch_front_input_uniforme::set_nb_comp (int i) override protected virtual
Implements Champ_Input_Proto.
References Field_base::fixer_nb_comp().
set_name()
void Ch_front_input_uniforme::set_name (const Nom & name) override protected virtual
Implements Champ_Input_Proto.
References Field_base::nommer().
get_name()
const Nom & Ch_front_input_uniforme::get_name () const protected virtual
References Field_base::le_nom().
Member Data Documentation
info_obj
const Type_info Ch_front_input_uniforme::info_obj static