TrioCFD: Source_WC_Chaleur_VEF Class Reference
Source_WC_Chaleur_VEF Class Reference
#include <Source_WC_Chaleur_VEF.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Source_Chaleur_Fluide_Dilatable_base
void completer () override
const Type_info * get_info () const override
void mettre_a_jour (double) override
Public Member Functions inherited from Source_base
virtual int a_pour_Champ_Fonc (const Motcle &mot, TRUST_Ref< Champ_base * > &ch_ref) const
virtual void associer_champ_rho (const Champ_base &champ_rho)
virtual void completer ()
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
virtual void resetTime (double t)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Source_WC_Chaleur
DoubleTab & ajouter_ (DoubleTab &) const
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
Cette classe represente un terme source supplementaire a prendre en compte dans les equations de la chaleur dans le cas ou le fluide est weakly compressible et pour une discretisation VEF
See also
Source_base Fluide_Weakly_Compressible Source_WC_Chaleur
Constructor & Destructor Documentation
Source_WC_Chaleur_VEF()
Source_WC_Chaleur_VEF::Source_WC_Chaleur_VEF ()
~Source_WC_Chaleur_VEF()
Source_WC_Chaleur_VEF::~Source_WC_Chaleur_VEF ()
Member Function Documentation
cree_instance()
Objet_U * Source_WC_Chaleur_VEF::cree_instance () static
taille_memoire()
unsigned Source_WC_Chaleur_VEF::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Source_WC_Chaleur_VEF::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Source_WC_Chaleur_VEF::info () static
get_info()
const Type_info * Source_WC_Chaleur_VEF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Source_WC_Chaleur.
self_cast() [1/2]
Source_WC_Chaleur_VEF & Source_WC_Chaleur_VEF::self_cast (Objet_U & r) static
self_cast() [2/2]
const Source_WC_Chaleur_VEF & Source_WC_Chaleur_VEF::self_cast (const Objet_U & r) static
printOn()
Sortie & Source_WC_Chaleur_VEF::printOn (Sortie & os) const override protected virtual
DOES NOTHING - to override in derived classes.
Imprime la source sur un flot de sortie.
Parameters
(Sortie& os) le flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Source_WC_Chaleur.
References Objet_U::que_suis_je().
readOn()
Entree & Source_WC_Chaleur_VEF::readOn (Entree & is) override protected virtual
DOES NOTHING - to override in derived classes.
Lecture d'un terme source sur un flot d'entree.
Parameters
(Entree& is) le flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Source_WC_Chaleur.
associer_domaines()
void Source_WC_Chaleur_VEF::associer_domaines (const Domaine_dis_base & domaine, const Domaine_Cl_dis_base & zcl) override protected virtual
Implements Source_Chaleur_Fluide_Dilatable_base.
References Source_Fluide_Dilatable_VEF_Proto::associer_domaines_impl(), Source_Fluide_Dilatable_VEF_Proto::associer_volume_porosite_impl(), Source_Chaleur_Fluide_Dilatable_base::porosites, and Source_Chaleur_Fluide_Dilatable_base::volumes.
compute_interpolate_gradP()
void Source_WC_Chaleur_VEF::compute_interpolate_gradP (DoubleTab & UgradP_face, const DoubleTab & Ptot) const override protected virtual
Implements Source_WC_Chaleur.
References Operateur_Grad::calculer(), Milieu_base::conductivite(), Source_WC_Chaleur::correct_grad_boundary(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Navier_Stokes_std::milieu(), MorEqn::mon_equation, Convection_Diffusion_Chaleur_WC::operateur_gradient_WC(), Objet_U::que_suis_je(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTVect< _TYPE_, _SIZE_ >::size_totale(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), Champ_Inc_base::valeurs(), and Navier_Stokes_std::vitesse().
Member Data Documentation
info_obj
const Type_info Source_WC_Chaleur_VEF::info_obj static