TrioCFD: TRUST_List< _CLASSE_ > Class Template Reference
TRUST_List< _CLASSE_ > Class Template Reference
#include <TRUST_List.h>
Protected Member Functions
Sortie & printOn (Sortie &os) const override
Entree & readOn (Entree &is) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
template<typename _CLASSE_>
class TRUST_List< _CLASSE_ >
La classe template TRUST_List est utilisable pour n'importe quelle classe Utilisation (par exemple):
TRUST_List<Milieu_base>
Constructor & Destructor Documentation
~TRUST_List()
template<typename _CLASSE_ > TRUST_List< _CLASSE_ >::~TRUST_List () inline
TRUST_List() [1/3]
template<typename _CLASSE_ > TRUST_List< _CLASSE_ >::TRUST_List () inline
TRUST_List() [2/3]
template<typename _CLASSE_ > TRUST_List< _CLASSE_ >::TRUST_List (const _CLASSE_ & t) inline
TRUST_List() [3/3]
template<typename _CLASSE_ > TRUST_List< _CLASSE_ >::TRUST_List (const TRUST_List< _CLASSE_ > & t) inline
Member Function Documentation
taille_memoire()
template<typename _CLASSE_ > unsigned TRUST_List< _CLASSE_ >::taille_memoire () const inline override protected virtual
Implements Objet_U.
duplique()
template<typename _CLASSE_ > int TRUST_List< _CLASSE_ >::duplique () const inline override protected virtual
Implements Objet_U.
printOn()
template<typename _CLASSE_ > Sortie & TRUST_List< _CLASSE_ >::printOn (Sortie & s) const inline override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
References TRUST_List< _CLASSE_ >::size().
readOn()
template<typename _CLASSE_ > Entree & TRUST_List< _CLASSE_ >::readOn (Entree & s) inline override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
References TRUST_List< _CLASSE_ >::add(), and Process::exit().
begin() [1/2]
template<typename _CLASSE_ > Iterator TRUST_List< _CLASSE_ >::begin () inline
Referenced by IJK_Thermals::ecrire_fichier_reprise(), and IJK_Thermals::sauvegarder_thermals().
end() [1/2]
template<typename _CLASSE_ > Iterator TRUST_List< _CLASSE_ >::end () inline
Referenced by IJK_Thermals::ecrire_fichier_reprise(), and IJK_Thermals::sauvegarder_thermals().
begin() [2/2]
template<typename _CLASSE_ > const CIterator TRUST_List< _CLASSE_ >::begin () const inline
end() [2/2]
template<typename _CLASSE_ > const CIterator TRUST_List< _CLASSE_ >::end () const inline
get_stl_list() [1/2]
template<typename _CLASSE_ > const std::list< _CLASSE_ > & TRUST_List< _CLASSE_ >::get_stl_list () const inline
Referenced by TRUST_List< _CLASSE_ >::add(), Champ_Uniforme_Morceaux_Tabule_Temps::me_calculer(), Postraitement::postraiter_tableaux(), and Probleme_FT_Disc_gen::typer_lire_milieu().
get_stl_list() [2/2]
template<typename _CLASSE_ > std::list< _CLASSE_ > & TRUST_List< _CLASSE_ >::get_stl_list () inline
size()
template<typename _CLASSE_ > int TRUST_List< _CLASSE_ >::size () const inline
Referenced by Objet_a_lire::add_dict(), Probleme_base_interface_proto::addInputField_impl(), Param::ajouter_condition(), Scatter::ajouter_joints(), Equation_base::assembler_blocs(), Convection_Diffusion_Temperature::assembler_blocs(), Convection_Diffusion_Espece_Multi_QC::assembler_blocs_avec_inertie(), Echange_contact_Correlation_VDF::calculer_CL(), Echange_contact_Correlation_VEF::calculer_CL(), Scatter::calculer_espace_distant(), ParoiVDF_TBLE_LRM::calculer_hyd(), ParoiVDF_TBLE::calculer_hyd(), ParoiVDF_TBLE::calculer_hyd_BiK(), ParoiVDF_TBLE_LRM::calculer_hyd_BiK(), Loi_Etat_Multi_GP_QC::calculer_masse_molaire(), Scatter::calculer_nb_items_virtuels(), Chimie::calculer_pas_de_temps(), Scatter::calculer_renum_items_communs(), Loi_Etat_Multi_GP_QC::calculer_tab_Cp(), Loi_Etat_Multi_GP_WC::calculer_tab_Cp(), Param::check(), Scatter::check_consistancy_remote_items(), Correction_Lubchenko_PolyMAC_P0::completer(), Champ_Gen_de_Champs_Gen::completer(), Champ_Generique_Transformation::completer(), Chimie::completer(), IJK_Thermals::compute_new_thermal_field(), Scatter::construire_md_vector(), IJK_Thermals::create_folders_for_probes(), Postraitement::creer_champ_post_med(), Faces_builder::creer_faces_reeles(), Champ_Gen_de_Champs_Gen::data_a_sauvegarder(), Param::dictionnaire(), Param::dictionnaire_param(), Equation_base::dimensionner_blocs(), Chimie::discretiser(), Postraiter_domaine::ecrire(), IJK_Thermals::ecrire_fichier_reprise(), Pb_Hydraulique_IBM::equation(), Pb_Thermohydraulique_IBM::equation(), Pb_Hydraulique::equation(), Pb_Thermohydraulique::equation(), Pb_Multiphase::equation(), Probleme_base_interface_proto::findInputField_impl(), Chimie::get_champ(), Moyenne_volumique::get_champ(), Objet_a_lire::get_names_message(), Champ_Gen_de_Champs_Gen::get_nb_sources(), Chimie::get_noms_champs_postraitables(), Champ_Gen_de_Champs_Gen::get_source(), Param::get_value(), Probleme_base_interface_proto::getInputFieldsNames_impl(), Probleme_base_interface_proto::getOutputFieldsNames_impl(), Chimie::has_champ(), Equation_base::has_interface_blocs(), ParoiVDF_TBLE::init_lois_paroi(), ParoiVEF_TBLE::init_lois_paroi(), Echange_contact_Correlation_VDF::init_tab_echange(), Loi_Etat_Multi_GP_base::initialiser_inco_ch(), Loi_Etat_Multi_GP_WC::initialiser_inco_ch(), Pb_Couple_rayo_semi_transp::initialize(), MaillerParallel::interpreter(), Create_domain_from_sub_domain::interpreter_(), SupprimeBord_32_64< _SIZE_ >::interpreter_(), Scatter::lire_domaine(), Chimie::mettre_a_jour(), Champ_Gen_de_Champs_Gen::mettre_a_jour(), List_Equations_Scalaires_Passifs_Especes::nb_equation(), TRUSTProblem_Concentration_Gen< _DERIVED_TYPE_, _EQUATION_TYPE_, _MEDIUM_TYPE_ >::nb_equations_multi(), Couplage_U::nb_problemes(), Champ_front_Parametrique::newCompute(), Champ_Parametrique::newCompute(), Probleme_FT_Disc_gen::nombre_d_equations(), Pb_Hydraulique_IBM::nombre_d_equations(), Pb_Thermohydraulique_IBM::nombre_d_equations(), Pb_Hydraulique::nombre_d_equations(), Pb_Thermohydraulique::nombre_d_equations(), Pb_Multiphase::nombre_d_equations(), TRUST_List< _CLASSE_ >::operator[](), Modele_rayo_semi_transp::preparer_calcul(), Navier_Stokes_IBM::preparer_calcul(), Param::print(), TRUST_List< _CLASSE_ >::printOn(), Loi_Etat_Multi_GP_QC::rabot(), Param::read(), Flux_2groupes_PolyMAC_P0::readOn(), Nucleation_paroi_PolyMAC_P0::readOn(), IJK_Thermals::readOn(), Probleme_FTD_IJK_base::readOn(), List_Equations_Scalaires_Passifs_Especes::readOn(), Sonde::readOn(), Energie_Multiphase::readOn(), Masse_Multiphase::readOn(), Equation_IBM_proto::readOn_ibm_proto(), Raffiner_Simplexes_32_64< _SIZE_ >::refine_domain(), RegroupeBord_32_64< _SIZE_ >::regroupe_bord(), Domaine_VF::renumeroter(), Domaine_VDF::reordonner(), Scatter::reordonner_faces_de_joint(), Champ_Gen_de_Champs_Gen::reprendre(), Champ_Gen_de_Champs_Gen::sauvegarder(), IJK_Thermals::sauvegarder_thermals(), IJK_Thermals::set_first_step_thermals_post(), IJK_Thermals::size(), Scatter::trier_les_joints(), and IJK_Thermals::verifie_milieu().
vide()
template<typename _CLASSE_ > void TRUST_List< _CLASSE_ >::vide () inline
Referenced by Domaine_ALE::clear(), Sondes::clear_cache(), Champ_Gen_de_Champs_Gen::completer(), Champ_Generique_Transformation::completer(), LireMED_32_64< _SIZE_ >::fill_frontieres(), Probleme_base::finir(), Create_domain_from_sub_domain::interpreter_(), IJK_Thermals::readOn(), and Champ_Gen_de_Champs_Gen::reset().
front() [1/2]
template<typename _CLASSE_ > const _CLASSE_ & TRUST_List< _CLASSE_ >::front () const inline
Referenced by Probleme_FTD_IJK_base::build_vdf_domaine(), Probleme_FTD_IJK_base::completer(), Probleme_FTD_IJK::create_forced_dilation(), Probleme_FTD_IJK_base::deplacer_interfaces(), Probleme_FTD_IJK_cut_cell::deplacer_interfaces(), Probleme_FTD_IJK_base::deplacer_interfaces_rk3(), Probleme_FTD_IJK_cut_cell::deplacer_interfaces_rk3(), Probleme_FTD_IJK_base::eq_ns(), Probleme_FTD_IJK_base::euler_time_step(), Probleme_FTD_IJK_cut_cell::get_cut_field_velocity(), Probleme_FTD_IJK_base::get_post(), Probleme_FTD_IJK_base::initialise_ijk_fields(), Probleme_FTD_IJK::initialize(), Probleme_FTD_IJK_base::initialize(), Probleme_FTD_IJK_cut_cell::initialize(), Probleme_FTD_IJK_base::preparer_calcul(), Probleme_FTD_IJK_base::reprendre_probleme(), Probleme_FTD_IJK_base::rk3_sub_step(), Probleme_FTD_IJK_base::sauvegarder_probleme(), Probleme_FTD_IJK_base::solveTimeStep(), Probleme_FTD_IJK_base::solveTimeStep_Euler(), Probleme_FTD_IJK_base::solveTimeStep_RK3(), and Probleme_FTD_IJK_cut_cell::update_twice_indicator_field().
front() [2/2]
template<typename _CLASSE_ > _CLASSE_ & TRUST_List< _CLASSE_ >::front () inline
dernier() [1/2]
template<typename _CLASSE_ > const _CLASSE_ & TRUST_List< _CLASSE_ >::dernier () const inline
Referenced by Probleme_FT_Disc_gen::add_FT_equation(), Injection_QDM_nulle_PolyMAC_P0::ajouter_blocs(), Injection_QDM_nulle_VDF::ajouter_blocs(), Sondes::get_from_cache(), Probleme_base::read_optional_equations(), and IJK_Thermals::readOn().
dernier() [2/2]
template<typename _CLASSE_ > _CLASSE_ & TRUST_List< _CLASSE_ >::dernier () inline
est_vide()
template<typename _CLASSE_ > int TRUST_List< _CLASSE_ >::est_vide () const inline
Referenced by IJK_Thermals::completer(), Transport_K_Eps_Bas_Reynolds::completer(), Transport_K_Eps_Realisable::completer(), IJK_Thermals::compute_eulerian_curvature(), IJK_Thermals::compute_eulerian_curvature_from_interface(), IJK_Thermals::compute_eulerian_distance(), IJK_Thermals::compute_eulerian_distance_curvature(), IJK_Thermals::est_vide(), IJK_Thermals::get_fichier_reprise(), IJK_Thermals::get_modified_time(), IJK_Thermals::get_rising_velocities_parameters(), Op_Grad_VEF_P1B_Face::impr(), Op_EF_base::impr(), Op_VEF_Face::impr(), Iterateur_PolyMAC_Elem< _TYPE_ >::impr(), Op_Conv_PolyMAC_base::impr(), Op_Diff_PolyMAC_Gen_base::impr(), IJK_Thermals::initialize(), Transport_K_Eps::readOn(), Transport_K_KEps::readOn(), Transport_K_Omega::readOn(), Transport_K_ou_Eps::readOn(), Transport_K_ou_Eps_Realisable::readOn(), Transport_Fluctuation_Temperature::readOn(), Transport_Fluctuation_Temperature_W::readOn(), Transport_Fluctuation_Temperature_W_Bas_Re::readOn(), Transport_Flux_Chaleur_Turbulente::readOn(), IJK_Thermals::retrieve_ghost_fluid_params(), and IJK_Thermals::set_fichier_reprise().
suppr()
template<typename _CLASSE_ > void TRUST_List< _CLASSE_ >::suppr (const _CLASSE_ & t) inline
Referenced by DecoupeBord_32_64< _SIZE_ >::decouper(), TroisDto2D_32_64< _SIZE_ >::extraire_2D(), Create_domain_from_sub_domain::interpreter_(), Modif_bord_to_raccord_32_64< _SIZE_ >::interpreter_(), SupprimeBord_32_64< _SIZE_ >::interpreter_(), Remove_Invalid_Internal_Boundaries::interpreter_(), RegroupeBord_32_64< _SIZE_ >::regroupe_bord(), Param::supprimer(), and Param::supprimer_condition().
add() [1/2]
template<typename _CLASSE_ > TRUST_List & TRUST_List< _CLASSE_ >::add (const TRUST_List< _CLASSE_ > & a_list) inline
References TRUST_List< _CLASSE_ >::get_stl_list().
Referenced by Objet_a_lire::add_dict(), Probleme_FT_Disc_gen::add_FT_equation(), Parser::addCst(), Probleme_base_interface_proto::addInputField_impl(), Couplage_U::addProblem(), Param::ajouter_condition(), Probleme_base::associer_(), Loi_Etat_Multi_GP_QC::associer_espece(), Loi_Etat_Multi_GP_base::associer_inconnue(), Param::check(), Transport_K_Eps_Bas_Reynolds::completer(), Transport_K_Eps_Realisable::completer(), Navier_Stokes_QC::completer(), Navier_Stokes_WC::completer(), Navier_Stokes_std::completer(), Navier_Stokes_Turbulent_QC::completer(), Champ_Gen_de_Champs_Gen::completer(), Champ_Generique_Transformation::completer(), Extruder_en3::construire_bords(), Param::create_or_get_objet_a_lire(), Pb_MED::creer_champ(), Postraitement::creer_champ_post(), Postraitement::creer_champ_post_moreqn(), Postraitement::creer_champ_post_stat(), DecoupeBord_32_64< _SIZE_ >::decouper(), TroisDto2D_32_64< _SIZE_ >::extraire_2D(), Extruder::extruder_dvt(), Extruder_en20::extruder_dvt(), Extruder::extruder_dvt_hexa(), Sondes::get_from_cache(), Probleme_base::init_postraitements(), IJK_Thermals::initialize(), MaillerParallel::interpreter(), Create_domain_from_sub_domain::interpreter_(), Extraire_domaine::interpreter_(), Lire_Tgrid::interpreter_(), Modif_bord_to_raccord_32_64< _SIZE_ >::interpreter_(), Domaine_base::lire_bords_a_imprimer(), Domaine_base::lire_bords_a_imprimer_sum(), Lecture_Champ::lire_champs(), Postraitement::lire_champs_a_postraiter(), Transport_Marqueur_FT::lire_motcle_non_standard(), Champ_Gen_de_Champs_Gen::lire_motcle_non_standard(), Convection_Diffusion_Chaleur_QC::lire_motcle_non_standard(), Convection_Diffusion_Chaleur_WC::lire_motcle_non_standard(), Modele_turbulence_hyd_base::lire_motcle_non_standard(), Modele_turbulence_scal_base::lire_motcle_non_standard(), Param::lire_sans_accolade(), Postraitement::lire_tableaux_a_postraiter(), Operateur_base::ouvrir_fichier(), Param::read(), Probleme_base::read_optional_equations(), Domaine_ALE::reading_vit_bords_ALE(), IJK_Thermals::readOn(), Navier_Stokes_phase_field::readOn(), Transport_K_Eps::readOn(), Transport_K_KEps::readOn(), Transport_K_Omega::readOn(), Transport_K_ou_Eps::readOn(), Transport_K_ou_Eps_Realisable::readOn(), Transport_Fluctuation_Temperature::readOn(), Transport_Fluctuation_Temperature_W::readOn(), Transport_Fluctuation_Temperature_W_Bas_Re::readOn(), Transport_Flux_Chaleur_Turbulente::readOn(), Puissance_Thermique_EF::readOn(), Champ_Uniforme_Morceaux_Tabule_Temps::readOn(), Champ_front_Parametrique::readOn(), Champ_Parametrique::readOn(), List_Equations_Scalaires_Passifs_Especes::readOn(), Milieu_base::readOn(), Fluide_base::readOn(), Solide::readOn(), Terme_Puissance_Thermique_VDF_base::readOn(), TRUST_List< _CLASSE_ >::readOn(), Postprocessing_IJK::register_one_field(), and Objet_a_lire::set_name().
add() [2/2]
template<typename _CLASSE_ > _CLASSE_ & TRUST_List< _CLASSE_ >::add (const _CLASSE_ & t) inline
add_if_not()
template<typename _CLASSE_ > _CLASSE_ & TRUST_List< _CLASSE_ >::add_if_not (const _CLASSE_ & t) inline
Referenced by Postraitement::complete_champ(), Postraitement::creer_champ_post(), Postraitement::creer_champ_post_moreqn(), and Postraitement::creer_champ_post_stat().
operator[]() [1/4]
template<typename _CLASSE_ > _CLASSE_ & TRUST_List< _CLASSE_ >::operator[] (int i) inline
References Process::exit(), and TRUST_List< _CLASSE_ >::size().
Referenced by TRUST_List< _CLASSE_ >::operator()().
operator[]() [2/4]
template<typename _CLASSE_ > const _CLASSE_ & TRUST_List< _CLASSE_ >::operator[] (int i) const inline
References Process::exit(), and TRUST_List< _CLASSE_ >::size().
operator[]() [3/4]
template<typename _CLASSE_ > _CLASSE_ & TRUST_List< _CLASSE_ >::operator[] (const Nom & nom) inline
References TRUST_List< _CLASSE_ >::size().
operator[]() [4/4]
template<typename _CLASSE_ > const _CLASSE_ & TRUST_List< _CLASSE_ >::operator[] (const Nom & nom) const inline
References TRUST_List< _CLASSE_ >::size().
operator()() [1/4]
template<typename _CLASSE_ > _CLASSE_ & TRUST_List< _CLASSE_ >::operator() (int i) inline
References TRUST_List< _CLASSE_ >::operator[]().
operator()() [2/4]
template<typename _CLASSE_ > const _CLASSE_ & TRUST_List< _CLASSE_ >::operator() (int i) const inline
References TRUST_List< _CLASSE_ >::operator[]().
operator()() [3/4]
template<typename _CLASSE_ > _CLASSE_ & TRUST_List< _CLASSE_ >::operator() (const Nom & n) inline
References TRUST_List< _CLASSE_ >::operator[]().
operator()() [4/4]
template<typename _CLASSE_ > const _CLASSE_ & TRUST_List< _CLASSE_ >::operator() (const Nom & n) const inline
References TRUST_List< _CLASSE_ >::operator[]().
operator=() [1/2]
template<typename _CLASSE_ > TRUST_List & TRUST_List< _CLASSE_ >::operator= (const _CLASSE_ & t) inline
operator=() [2/2]
template<typename _CLASSE_ > TRUST_List & TRUST_List< _CLASSE_ >::operator= (const TRUST_List< _CLASSE_ > & t) inline
contient() [1/2]
template<typename _CLASSE_ > int TRUST_List< _CLASSE_ >::contient (const char *const ch) const inline
Referenced by Paroi_flux_impose_Rayo_transp::calculer_Teta_i_VDF(), Param::check(), Postraitement::creer_champ_post(), Postraitement::creer_champ_post_moreqn(), Postraitement::creer_champ_post_stat(), Op_Grad_VEF_P1B_Face::impr(), Op_EF_base::impr(), Op_VEF_Face::impr(), Op_Grad_EF::impr(), Iterateur_PolyMAC_Elem< _TYPE_ >::impr(), Op_Conv_PolyMAC_base::impr(), Op_Diff_PolyMAC_Gen_base::impr(), Op_Grad_VDF_Face::impr(), Postraitement::lire_champs_a_postraiter(), Operateur_base::ouvrir_fichier(), and Modele_turbulence_hyd_Longueur_Melange_VEF::preparer_calcul().
contient() [2/2]
template<typename _CLASSE_ > int TRUST_List< _CLASSE_ >::contient (const Objet_U & obj) const inline
rang() [1/2]
template<typename _CLASSE_ > int TRUST_List< _CLASSE_ >::rang (const char *const ch) const inline
Referenced by Probleme_base::init_postraitements(), Traitement_particulier_NS_CEG::lire(), Loi_expert_hydr_EF::readOn(), Loi_expert_hydr_VEF::readOn(), Parametre_implicite::readOn(), and Param::supprimer_condition().
rang() [2/2]
template<typename _CLASSE_ > int TRUST_List< _CLASSE_ >::rang (const _CLASSE_ & obj) const inline