TrioCFD: Domaine_PolyMAC Class Reference
Domaine_PolyMAC Class Reference
#include <Domaine_PolyMAC.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Domaine_Poly_base
const Type_info * get_info () const override
void reordonner (Faces &) override
Public Member Functions inherited from Domaine_VF
void build_map_mc_Cmesh (const bool with_faces) override
void build_mc_dual_mesh () const
void build_mc_face_mesh () const
void construire_face_virt_pe_num ()
int elem_faces (int i, int j) const
int face_voisins (int num_face, int i) const
const Type_info * get_info () const override
void init_dist_paroi_globale (const Conds_lim &conds_lim) override
int nb_faces_bord () const
int nb_faces_bord_tot () const
int nb_faces_internes () const
int nb_faces_tot () const
int nb_som_face () const
int premiere_face_bord () const
int premiere_face_int () const
Public Member Functions inherited from Domaine_dis_base
void associer_domaine (const Domaine &)
const Domaine & domaine () const
void ecrire_noms_bords (Sortie &) const
virtual IntTab & face_sommets ()
const Frontiere_dis_base & frontiere_dis (const Nom &) const
const Type_info * get_info () const override
int nombre_de_sous_domaines_dis () const
int rang_frontiere (const Nom &) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Domaine_PolyMAC()
Domaine_PolyMAC::Domaine_PolyMAC ()
~Domaine_PolyMAC()
Domaine_PolyMAC::~Domaine_PolyMAC ()
Member Function Documentation
cree_instance()
Objet_U * Domaine_PolyMAC::cree_instance () static
taille_memoire()
unsigned Domaine_PolyMAC::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Domaine_PolyMAC_P0, and Domaine_PolyMAC_P0P1NC.
duplique()
int Domaine_PolyMAC::duplique () const override virtual
Implements Objet_U.
Reimplemented in Domaine_PolyMAC_P0, and Domaine_PolyMAC_P0P1NC.
info()
const Type_info * Domaine_PolyMAC::info () static
get_info()
const Type_info * Domaine_PolyMAC::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Domaine_Poly_base.
Reimplemented in Domaine_PolyMAC_P0, and Domaine_PolyMAC_P0P1NC.
self_cast() [1/2]
Domaine_PolyMAC & Domaine_PolyMAC::self_cast (Objet_U & r) static
self_cast() [2/2]
const Domaine_PolyMAC & Domaine_PolyMAC::self_cast (const Objet_U & r) static
printOn()
Sortie & Domaine_PolyMAC::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Domaine_Poly_base.
Reimplemented in Domaine_PolyMAC_P0, and Domaine_PolyMAC_P0P1NC.
References Domaine_Poly_base::printOn().
readOn()
Entree & Domaine_PolyMAC::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Domaine_Poly_base.
Reimplemented in Domaine_PolyMAC_P0, and Domaine_PolyMAC_P0P1NC.
References Domaine_Poly_base::readOn().
discretiser()
void Domaine_PolyMAC::discretiser () override virtual
Reimplemented from Domaine_Poly_base.
Reimplemented in Domaine_PolyMAC_P0, and Domaine_PolyMAC_P0P1NC.
References calculer_h_carre(), Domaine_Poly_base::discretiser(), and Domaine_Poly_base::discretiser_aretes().
swap()
void Domaine_PolyMAC::swap (int , int , int) inline
modifier_pour_Cl()
void Domaine_PolyMAC::modifier_pour_Cl (const Conds_lim & conds_lim) override virtual
Reimplemented from Domaine_Poly_base.
References Objet_U::dimension, Domaine_dis_base::domaine(), Periodique::face_associee(), Domaine_VF::face_normales_, Domaine_VF::face_voisins_, Cond_lim_base::frontiere_dis(), Process::Journal(), Domaine_VF::marquer_faces_double_contrib(), Domaine_VF::nb_faces(), Front_VF::nb_faces(), Domaine_32_64< _SIZE_ >::nb_faces_elem(), Front_VF::nb_faces_tot(), Front_VF::num_face(), Front_VF::num_premiere_face(), TRUST_Vector< _CLASSE_ >::size(), Domaine_VF::volumes_, Domaine_VF::volumes_entrelaces_, Domaine_VF::xp_, and Domaine_VF::xv_.
init_equiv()
void Domaine_PolyMAC::init_equiv () const override virtual
Implements Domaine_Poly_base.
References Domaine_VF::creer_tableau_faces(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Domaine_dis_base::domaine(), dot(), Domaine_VF::elem_faces(), Domaine_Poly_base::equiv_, Domaine_VF::face_normales(), Domaine_VF::face_surfaces(), Domaine_VF::face_voisins(), Domaine_base::le_nom(), Option_PolyMAC::MAILLAGE_VDF, Domaine_VF::nb_faces_tot(), Domaine_VF::orientation(), Objet_U::que_suis_je(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Domaine_VF::xp_, and Domaine_VF::xv_.
arete_faces()
const IntTab & Domaine_PolyMAC::arete_faces () const inline
calculer_volumes_entrelaces()
void Domaine_PolyMAC::calculer_volumes_entrelaces () override virtual
Reimplemented from Domaine_Poly_base.
Reimplemented in Domaine_PolyMAC_P0P1NC.
References Domaine_VF::creer_tableau_faces(), dot(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_VF::face_surfaces(), Domaine_VF::face_voisins_, Domaine_VF::nb_faces(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Domaine_VF::volumes_entrelaces_, Domaine_VF::volumes_entrelaces_dir_, Domaine_VF::xp_, and Domaine_VF::xv_.
calculer_h_carre()
void Domaine_PolyMAC::calculer_h_carre () override virtual
Reimplemented from Domaine_Poly_base.
References Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), Domaine_VF::face_surfaces(), Domaine_Poly_base::h_carre, Domaine_Poly_base::h_carre_, Domaine_dis_base::nb_elem(), Domaine_VF::nb_faces(), Domaine_32_64< _SIZE_ >::nb_faces_elem(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), Domaine_32_64< _SIZE_ >::type_elem(), Domaine_Poly_base::type_elem(), TRUST_Deriv< _CLASSE_ >::valeur(), and Domaine_VF::volumes().
Referenced by discretiser().
dot() [1/2]
double Domaine_PolyMAC::dot (const double * a, const double * b, const double * ma = nullptr, const double * mb = nullptr) const inline
References Objet_U::dimension, and dot().
Referenced by calculer_volumes_entrelaces(), Domaine_PolyMAC_P0P1NC::calculer_volumes_entrelaces(), dot(), init_equiv(), init_m1_3d(), init_rf(), init_we_3d(), Domaine_PolyMAC_P0P1NC::M1(), M2(), Domaine_PolyMAC_P0P1NC::surf_elem_arete(), Domaine_PolyMAC_P0P1NC::W1(), and W2().
dot() [2/2]
KOKKOS_INLINE_FUNCTION double Domaine_PolyMAC::dot (const int dim, const double * a, const double * b, const double * ma = nullptr, const double * mb = nullptr) const
cross()
std::array< double, 3 > Domaine_PolyMAC::cross (int dima, int dimb, const double * a, const double * b, const double * ma = nullptr, const double * mb = nullptr) const inline
Referenced by init_m1_2d(), init_m1_3d(), init_rf(), init_we_2d(), init_we_3d(), and Domaine_PolyMAC_P0P1NC::surf_elem_arete().
init_ve()
void Domaine_PolyMAC::init_ve () const
References TRUSTTab< _TYPE_, _SIZE_ >::append_line(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), Domaine_VF::face_surfaces(), Domaine_VF::face_voisins(), is_init, Domaine_base::le_nom(), Domaine_dis_base::nb_elem_tot(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), veci, vedeb, veji, Domaine_VF::volumes_, Domaine_VF::xp(), and Domaine_VF::xv().
init_rf()
void Domaine_PolyMAC::init_rf () const
References TRUSTTab< _TYPE_, _SIZE_ >::append_line(), Domaine_32_64< _SIZE_ >::coord_sommets(), cross(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Domaine_dis_base::domaine(), dot(), Domaine_VF::face_normales(), Domaine_VF::face_sommets(), Domaine_VF::face_surfaces(), is_init, Domaine_Poly_base::longueur_aretes(), Domaine_VF::nb_faces_tot(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), rfci, rfdeb, rfji, Domaine_Poly_base::som_arete, Domaine_Poly_base::ta_, Domaine_VF::xa_, and Domaine_VF::xv_.
ajouter_stabilisation()
void Domaine_PolyMAC::ajouter_stabilisation (DoubleTab & M, DoubleTab & N) const inline
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, and TRUSTTab< _TYPE_, _SIZE_ >::resize().
Referenced by init_m1_3d().
W_stabiliser()
int Domaine_PolyMAC::W_stabiliser (DoubleTab & W, DoubleTab & R, DoubleTab & N, int * ctr, double * spectre) const inline
References Objet_U::dimension, Process::exit(), Matrice33::inverse(), and TRUSTTab< _TYPE_, _SIZE_ >::resize().
init_m2()
void Domaine_PolyMAC::init_m2 () const
References Option_PolyMAC::USE_NEW_M2.
Referenced by init_m2solv(), Echange_contact_PolyMAC::initialiser(), and Echange_contact_PolyMAC::update_coeffs().
init_m2solv()
void Domaine_PolyMAC::init_m2solv () const
References Matrix_tools::allocate_symmetric_morse_matrix(), TRUSTTab< _TYPE_, _SIZE_ >::append_line(), Domaine_VF::elem_faces(), Domaine_VF::face_voisins(), init_m2(), is_init, m2c, m2d, m2i, m2j, m2mat, m2solv, Domaine_dis_base::nb_elem_tot(), Domaine_VF::nb_faces(), Domaine_VF::nb_faces_tot(), Matrice_Sym::set_est_definie(), and Domaine_VF::volumes().
init_we()
void Domaine_PolyMAC::init_we () const inline
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Domaine_dis_base::domaine(), Domaine_VF::face_sommets_, init_we_2d(), init_we_3d(), is_init, Domaine_VF::nb_faces_tot(), Domaine_dis_base::nb_som_tot(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), and Domaine_Poly_base::som_arete.
Referenced by init_m1().
init_we_2d()
void Domaine_PolyMAC::init_we_2d () const
References TRUSTTab< _TYPE_, _SIZE_ >::append_line(), Domaine_32_64< _SIZE_ >::coord_sommets(), cross(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), Domaine_VF::face_sommets_, Domaine_dis_base::nb_elem_tot(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Domaine_VF::volumes(), weci, wedeb, weji, Domaine_VF::xp_, and Domaine_VF::xv_.
Referenced by init_we().
init_we_3d()
void Domaine_PolyMAC::init_we_3d () const
References TRUSTTab< _TYPE_, _SIZE_ >::append_line(), cross(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), dot(), Domaine_VF::elem_faces(), Domaine_VF::face_sommets_, Domaine_Poly_base::longueur_aretes_, Domaine_dis_base::nb_elem_tot(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Domaine_Poly_base::som_arete, Domaine_Poly_base::ta_, Domaine_VF::volumes_, weci, wedeb, weji, Domaine_VF::xa_, Domaine_VF::xp_, and Domaine_VF::xv_.
Referenced by init_we().
init_m1()
void Domaine_PolyMAC::init_m1 () const
References Objet_U::dimension, init_m1_2d(), init_m1_3d(), init_we(), and is_init.
init_m1_2d()
void Domaine_PolyMAC::init_m1_2d () const
References TRUSTTab< _TYPE_, _SIZE_ >::append_line(), Domaine_32_64< _SIZE_ >::coord_sommets(), cross(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), Domaine_VF::face_sommets_, m1ci, m1deb, m1ji, Domaine_dis_base::nb_elem_tot(), Domaine_dis_base::nb_som_tot(), Domaine_32_64< _SIZE_ >::nb_som_tot(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Domaine_VF::xp_, and Domaine_VF::xv_.
Referenced by init_m1().
init_m1_3d()
void Domaine_PolyMAC::init_m1_3d () const
References ajouter_stabilisation(), TRUSTTab< _TYPE_, _SIZE_ >::append_line(), Process::barrier(), Domaine_32_64< _SIZE_ >::creer_tableau_elements(), cross(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Domaine_dis_base::domaine(), dot(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_32_64< _SIZE_ >::elem_aretes(), Domaine_VF::elem_faces_, Domaine_VF::face_sommets_, Domaine_base::le_nom(), Domaine_Poly_base::longueur_aretes_, m1ci, m1deb, m1ji, Domaine_32_64< _SIZE_ >::nb_aretes_tot(), Domaine_dis_base::nb_elem(), Domaine_dis_base::nb_elem_tot(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Domaine_Poly_base::som_arete, Domaine_Poly_base::ta_, Domaine_VF::volumes(), weci, wedeb, weji, Domaine_VF::xa_, Domaine_VF::xp_, and Domaine_VF::xv_.
Referenced by init_m1().
init_virt_ef_map()
void Domaine_PolyMAC::init_virt_ef_map () const
References Domaine_32_64< _SIZE_ >::creer_tableau_elements(), Domaine_VF::creer_tableau_faces(), Domaine_dis_base::domaine(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), is_init, Process::me(), Domaine_dis_base::nb_elem(), Domaine_dis_base::nb_elem_tot(), Domaine_VF::nb_faces(), Domaine_VF::nb_faces_tot(), and virt_ef_map.
Referenced by Echange_contact_PolyMAC::initialiser().
M2()
void Domaine_PolyMAC::M2 (const DoubleTab * nu, int e, DoubleTab & m2) const
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), dot(), Domaine_VF::elem_faces(), Domaine_VF::face_normales(), Domaine_VF::face_voisins(), Domaine_Poly_base::nu_dot(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Domaine_VF::volumes(), Domaine_VF::xp(), and Domaine_VF::xv().
W2()
void Domaine_PolyMAC::W2 (const DoubleTab * nu, int e, DoubleTab & w2) const
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), dot(), Domaine_VF::elem_faces(), Domaine_VF::face_normales(), Domaine_VF::face_voisins(), Domaine_Poly_base::nu_dot(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Domaine_VF::volumes(), Domaine_VF::xp(), and Domaine_VF::xv().
Member Data Documentation
info_obj
const Type_info Domaine_PolyMAC::info_obj static
cyclic
IntVect Domaine_PolyMAC::cyclic
is_init
std::map<std::string, int> Domaine_PolyMAC::is_init mutable
Referenced by init_m1(), init_m2solv(), init_rf(), init_ve(), init_virt_ef_map(), and init_we().
vedeb
IntTab Domaine_PolyMAC::vedeb mutable
Referenced by init_ve().
veji
IntTab Domaine_PolyMAC::veji
Referenced by init_ve().
veci
DoubleTab Domaine_PolyMAC::veci mutable
Referenced by init_ve().
rfdeb
IntTab Domaine_PolyMAC::rfdeb mutable
Referenced by init_rf().
rfji
IntTab Domaine_PolyMAC::rfji
Referenced by init_rf().
rfci
DoubleTab Domaine_PolyMAC::rfci mutable
Referenced by init_rf().
m2d
IntTab Domaine_PolyMAC::m2d mutable
Referenced by init_m2solv(), Echange_contact_PolyMAC::initialiser(), Echange_contact_PolyMAC::update_coeffs(), and Echange_contact_PolyMAC::update_delta().
m2i
IntTab Domaine_PolyMAC::m2i
Referenced by init_m2solv().
m2j
IntTab Domaine_PolyMAC::m2j
Referenced by init_m2solv().
w2i
IntTab Domaine_PolyMAC::w2i
Referenced by Echange_contact_PolyMAC::initialiser(), Echange_contact_PolyMAC::update_coeffs(), and Echange_contact_PolyMAC::update_delta().
w2j
IntTab Domaine_PolyMAC::w2j
Referenced by Echange_contact_PolyMAC::initialiser(), Echange_contact_PolyMAC::update_coeffs(), and Echange_contact_PolyMAC::update_delta().
m2c
DoubleTab Domaine_PolyMAC::m2c mutable
Referenced by init_m2solv().
w2c
DoubleTab Domaine_PolyMAC::w2c
Referenced by Echange_contact_PolyMAC::update_coeffs().
m2mat
Matrice_Morse_Sym Domaine_PolyMAC::m2mat mutable
Referenced by init_m2solv().
m2solv
SolveurSys Domaine_PolyMAC::m2solv mutable
Referenced by init_m2solv().
wedeb
IntTab Domaine_PolyMAC::wedeb mutable
Referenced by init_m1_3d(), init_we_2d(), and init_we_3d().
weji
IntTab Domaine_PolyMAC::weji
Referenced by init_m1_3d(), init_we_2d(), and init_we_3d().
weci
DoubleTab Domaine_PolyMAC::weci mutable
Referenced by init_m1_3d(), init_we_2d(), and init_we_3d().
m1deb
IntTab Domaine_PolyMAC::m1deb mutable
Referenced by init_m1_2d(), and init_m1_3d().
m1ji
IntTab Domaine_PolyMAC::m1ji
Referenced by init_m1_2d(), and init_m1_3d().
m1ci
DoubleTab Domaine_PolyMAC::m1ci mutable
Referenced by init_m1_2d(), and init_m1_3d().
virt_ef_map
std::map<std::array<int, 2>, int> Domaine_PolyMAC::virt_ef_map mutable
Referenced by init_virt_ef_map(), and Echange_contact_PolyMAC::initialiser().