TrioCFD: Champ_Fonc_Face_VDF Class Reference
Champ_Fonc_Face_VDF Class Reference
#include <Champ_Fonc_Face_VDF.h>
Public Member Functions
Champ_base & affecter_ (const Champ_base &) override
int fixer_nb_valeurs_nodales (int) override
const Type_info * get_info () const override
int imprime (Sortie &os, int ncomp) const override
void mettre_a_jour (double) override
DoubleTab & remplir_coord_noeuds (DoubleTab &positions) const override
int remplir_coord_noeuds_et_polys (DoubleTab &positions, IntVect &polys) const override
DoubleTab & trace (const Frontiere_dis_base &, DoubleTab &, double, int distant) const override
DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &tab_valeurs, int ncomp) const override
Public Member Functions inherited from Champ_Fonc_base
Champ_base & affecter_ (const Champ_base &) override
Champ_base & affecter_compo (const Champ_base &, int compo) override
int fixer_nb_valeurs_nodales (int nb_noeuds) override
const Type_info * get_info () const override
void mettre_a_jour (double temps) override
virtual DoubleTab & remplir_coord_noeuds (DoubleTab &) const
virtual DoubleTab & remplir_coord_noeuds_compo (DoubleTab &, int) const
virtual int remplir_coord_noeuds_et_polys (DoubleTab &, IntVect &) const
virtual int remplir_coord_noeuds_et_polys_compo (DoubleTab &, IntVect &, int) const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
DoubleTab & valeur_aux (const DoubleTab &, DoubleTab &) const override
Public Member Functions inherited from Champ_Don_base
void dimensionner (int, int)
int fixer_nb_valeurs_nodales (int nb_noeuds) override
const Type_info * get_info () const override
int imprime (Sortie &, int) const override
virtual int initialiser (const double temps)
void mettre_a_jour (double temps) override
int reprendre (Entree &) override
void resetTime (double time) override
int sauvegarder (Sortie &) const override
DoubleTab & valeurs () override
Public Member Functions inherited from Champ_base
Champ_base & affecter (const Champ_base &)
Champ_base ()
virtual double changer_temps (const double t)
const Type_info * get_info () const override
double temps () const
virtual DoubleTab & trace (const Frontiere_dis_base &, DoubleTab &, double, int distant) const
virtual DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const
virtual double valeur_a_compo (const DoubleVect &position, int ncomp) const
virtual DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &valeurs, int le_poly) const
virtual double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const
virtual DoubleVect & valeur_a_sommet (int, const Domaine &, DoubleVect &) const
virtual DoubleTab & valeur_aux (const DoubleTab &positions, DoubleTab &valeurs) const
virtual DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const
virtual DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const
virtual DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp) const
Public Member Functions inherited from Field_base
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
virtual void fixer_nb_comp (int i)
virtual const Nom & fixer_nom_compo (const Nom &)
virtual const Nom & fixer_nom_compo (int, const Nom &)
virtual const Noms & fixer_noms_compo (const Noms &)
virtual const Nom & fixer_unite (const Nom &)
virtual const Nom & fixer_unite (int i, const Nom &)
virtual const Noms & fixer_unites (const Noms &)
const Type_info * get_info () const override
const Nom & nom_compo (int) const
void nommer (const Nom &) override
const Nom & unite () const
const Nom & unite (int) const
const Noms & unites () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Champ_Proto
int lire_dimension (Entree &, const Nom &)
int lire_dimension (int dim, const Nom &le_nom_)
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
See also
Champ_Fonc_base Champ_Face_VDF
Constructor & Destructor Documentation
Champ_Fonc_Face_VDF()
Champ_Fonc_Face_VDF::Champ_Fonc_Face_VDF ()
~Champ_Fonc_Face_VDF()
Champ_Fonc_Face_VDF::~Champ_Fonc_Face_VDF ()
Member Function Documentation
cree_instance()
Objet_U * Champ_Fonc_Face_VDF::cree_instance () static
taille_memoire()
unsigned Champ_Fonc_Face_VDF::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Courant_maille_Champ_Face, and Reynolds_maille_Champ_Face.
duplique()
int Champ_Fonc_Face_VDF::duplique () const override virtual
Implements Objet_U.
Reimplemented in Courant_maille_Champ_Face, and Reynolds_maille_Champ_Face.
info()
const Type_info * Champ_Fonc_Face_VDF::info () static
get_info()
const Type_info * Champ_Fonc_Face_VDF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Champ_Fonc_base.
Reimplemented in Courant_maille_Champ_Face, and Reynolds_maille_Champ_Face.
self_cast() [1/2]
Champ_Fonc_Face_VDF & Champ_Fonc_Face_VDF::self_cast (Objet_U & r) static
self_cast() [2/2]
const Champ_Fonc_Face_VDF & Champ_Fonc_Face_VDF::self_cast (const Objet_U & r) static
printOn()
Sortie & Champ_Fonc_Face_VDF::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Champ_Fonc_base.
Reimplemented in Courant_maille_Champ_Face, and Reynolds_maille_Champ_Face.
References Field_base::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Champ_Fonc_Face_VDF::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Champ_Fonc_base.
Reimplemented in Courant_maille_Champ_Face, and Reynolds_maille_Champ_Face.
fixer_nb_valeurs_nodales()
int Champ_Fonc_Face_VDF::fixer_nb_valeurs_nodales (int nb_noeuds) override virtual
Fixe le nombre de degres de liberte par composante.
Parameters
(int nb_noeuds) le nombre de degre de liberte par composante
Reimplemented from Champ_Fonc_base.
References Champ_Fonc_base::creer_tableau_distribue(), Objet_U::dimension, domaine_vdf(), Domaine_VF::md_vector_faces(), and Field_base::nb_compo_.
Referenced by VDF_discretisation::courant_maille(), and VDF_discretisation::reynolds_maille().
imprime()
int Champ_Fonc_Face_VDF::imprime (Sortie & os, int ncomp) const override virtual
NE FAIT RIEN.
EXIT ! A surcharger dans les classes derivees
Reimplemented from Champ_Don_base.
References Champ_Face_VDF_implementation::imprime_Face().
mettre_a_jour()
void Champ_Fonc_Face_VDF::mettre_a_jour (double un_temps) override virtual
Mise a jour en temps du champ.
Parameters
(double temps) le temps de mise a jour
Reimplemented from Champ_Fonc_base.
Reimplemented in Courant_maille_Champ_Face, and Reynolds_maille_Champ_Face.
References Champ_Fonc_base::mettre_a_jour().
trace()
DoubleTab & Champ_Fonc_Face_VDF::trace (const Frontiere_dis_base & , DoubleTab & x, double tps, int distant) const override virtual
Calcule la trace d'un champ sur une frontiere au temps tps.
WEC : La frontiere passee en parametre doit faire partie du domaine sur lequel s'appuie le champ Le resultat est calcule sur cette frontiere et la taille du DoubleTab x correspond au nombre de faces de la frontiere. x peut avoir un espace virtuel, la fonction trace apelle echange_espace_virtuel.
Cas particulier (malheureusement) du Champ_P0_VDF : Si la frontiere est un raccord, le resultat est calcule sur le raccord associe. Dans ce cas, le DoubleTab x doit etre dimensionne sur le raccord associe.
Parameters
(Frontiere_dis_base&) frontiere discretisee sur laquelle on veut calculer la trace du champ au temps tps
(DoubleTab& x , double tps) les valeurs du champ sur la frontiere au temps tps
Returns
(DoubleTab&) les valeurs du champ sur la frontiere au temps tps
Reimplemented from Champ_base.
References Champ_Face_VDF_implementation::trace(), and Champ_Don_base::valeurs().
affecter_()
Champ_base & Champ_Fonc_Face_VDF::affecter_ (const Champ_base & ch) override virtual
Affecte un Champ_base dans un Champ_Fonc_base.
Parameters
(Champ_base& ch) le champ partie droite de l'affectation
Returns
(Champ_base&) le resultat de l'affectation (*this) (avec upcast)
Reimplemented from Champ_Fonc_base.
References Objet_U::dimension, domaine_vdf(), Domaine_VF::face_voisins(), Domaine_VF::nb_faces(), Domaine_VDF::nb_faces_X(), Domaine_VDF::nb_faces_Y(), Domaine_VDF::nb_faces_Z(), Domaine_VDF::orientation(), Domaine_VF::premiere_face_int(), Champ_base::valeur_aux_compo(), Champ_Don_base::valeurs(), Champ_Proto::valeurs(), and Domaine_VF::xv().
valeur_aux_compo()
DoubleVect & Champ_Fonc_Face_VDF::valeur_aux_compo (const DoubleTab & pos, DoubleVect & les_valeurs, int compo) const override virtual
Idem que valeur_aux(const DoubleTab &, DoubleTab &), mais calcule uniquement la composante compo du champ.
Dans l'implementation de champ_base, on appelle valeur_aux(const DoubleTab &, DoubleTab &)
Parameters
(pos) le tableau des coordonnees des points de calcul (on ne traite pas l'espace virtuel du tableau)
(les_valeurs) tableau destination des valeurs a calculer. Le tableau valeurs doit avoir la bonne taille en entree, soit les_valeurs.size() == pos.dimension(0)
(compo) l'index de la composante du champ a calculer
Returns
(reference au tableau les_valeurs)
Reimplemented from Champ_base.
References Domaine_32_64< _SIZE_ >::chercher_elements(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Domaine_dis_base::domaine(), Champ_Fonc_base::domaine_dis_base(), and valeur_aux_elems_compo().
domaine_vdf()
const Domaine_VDF & Champ_Fonc_Face_VDF::domaine_vdf () const inline override virtual
Implements Champ_Face_VDF_implementation.
References Champ_Fonc_base::le_dom_VF, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by affecter_(), fixer_nb_valeurs_nodales(), Courant_maille_Champ_Face::mettre_a_jour(), and Reynolds_maille_Champ_Face::mettre_a_jour().
valeur_a_elem()
DoubleVect & Champ_Fonc_Face_VDF::valeur_a_elem (const DoubleVect & position, DoubleVect & val, int le_poly) const inline override virtual
Reimplemented from Champ_Face_VDF_implementation.
References Champ_Face_VDF_implementation::valeur_a_elem().
valeur_a_elem_compo()
double Champ_Fonc_Face_VDF::valeur_a_elem_compo (const DoubleVect & position, int le_poly, int ncomp) const inline override virtual
Reimplemented from Champ_Face_VDF_implementation.
References Champ_Face_VDF_implementation::valeur_a_elem_compo().
valeur_aux_elems()
DoubleTab & Champ_Fonc_Face_VDF::valeur_aux_elems (const DoubleTab & positions, const IntVect & les_polys, DoubleTab & tab_valeurs) const inline override virtual
Reimplemented from Champ_Face_VDF_implementation.
References Champ_Face_VDF_implementation::valeur_aux_elems().
valeur_aux_elems_compo()
DoubleVect & Champ_Fonc_Face_VDF::valeur_aux_elems_compo (const DoubleTab & positions, const IntVect & les_polys, DoubleVect & tab_valeurs, int ncomp) const inline override virtual
Reimplemented from Champ_Face_VDF_implementation.
References Champ_Face_VDF_implementation::valeur_aux_elems_compo().
Referenced by valeur_aux_compo().
valeur_aux_sommets()
DoubleTab & Champ_Fonc_Face_VDF::valeur_aux_sommets (const Domaine & dom, DoubleTab & val) const inline override virtual
Reimplemented from Champ_Face_VDF_implementation.
References Champ_Face_VDF_implementation::valeur_aux_sommets().
valeur_aux_sommets_compo()
DoubleVect & Champ_Fonc_Face_VDF::valeur_aux_sommets_compo (const Domaine & dom, DoubleVect & val, int comp) const inline override virtual
Reimplemented from Champ_Face_VDF_implementation.
References Champ_Face_VDF_implementation::valeur_aux_sommets_compo().
remplir_coord_noeuds()
DoubleTab & Champ_Fonc_Face_VDF::remplir_coord_noeuds (DoubleTab & coord) const inline override virtual
NE FAIT RIEN A surcharger dans les classes derivees.
Parameters
(DoubleTab& coord)
Returns
(DoubleTab&) renvoie toujours le parametre coord
Reimplemented from Champ_Fonc_base.
References Champ_Face_VDF_implementation::remplir_coord_noeuds().
remplir_coord_noeuds_et_polys()
int Champ_Fonc_Face_VDF::remplir_coord_noeuds_et_polys (DoubleTab & , IntVect &) const inline override virtual
NE FAIT RIEN A surcharger dans les classes derivees.
Parameters
(DoubleTab&)
(IntVect&)
Returns
(int) renvoie toujours 0
Reimplemented from Champ_Fonc_base.
References Champ_Face_VDF_implementation::remplir_coord_noeuds_et_polys().
Member Data Documentation
info_obj
const Type_info Champ_Fonc_Face_VDF::info_obj static