TrioCFD: Convection_diffusion_turbulence_multiphase Class Reference
Convection_diffusion_turbulence_multiphase Class Reference
#include <Convection_diffusion_turbulence_multiphase.h>
Public Member Functions
void associer_milieu_base (const Milieu_base &) override
void completer () override
const Motcle & domaine_application () const override
const Type_info * get_info () const override
int impr (Sortie &os) const override
const Champ_Inc_base & inconnue () const override
Champ_Inc_base & inconnue () override
const Milieu_base & milieu () const override
Milieu_base & milieu () override
Public Member Functions inherited from Convection_Diffusion_std
void associer_vitesse (const Champ_base &)
const Type_info * get_info () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
int nombre_d_operateurs () const override
const Operateur & operateur (int) const override
Operateur & operateur (int) override
const Champ_Inc_base & vitesse_transportante () const
Public Member Functions inherited from Equation_base
virtual void abortTimeStep ()
virtual void associer_domaine_dis (const Domaine_dis_base &)
virtual void associer_pb_base (const Probleme_base &)
virtual void associer_sch_tps_base (const Schema_Temps_base &)
virtual double calculer_pas_de_temps () const
virtual void completer ()
virtual std::vector< YAML_data > data_a_sauvegarder () const
DoubleTab & derivee_en_temps_conv (DoubleTab &, const DoubleTab &)
virtual DoubleTab & derivee_en_temps_inco (DoubleTab &)
const Discretisation_base & discretisation () const
virtual void discretiser ()
virtual const Motcle & domaine_application () const
virtual Domaine_Cl_dis_base & domaine_Cl_dis ()
virtual const Domaine_Cl_dis_base & domaine_Cl_dis () const
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual void imprimer (Sortie &os) const
virtual bool initTimeStep (double dt)
const Nom & le_nom () const override
int limpr () const
virtual void mettre_a_jour (double temps)
virtual int preparer_calcul ()
Probleme_base & probleme ()
const Probleme_base & probleme () const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Schema_Temps_base & schema_temps ()
const Schema_Temps_base & schema_temps () const
Solveur_Masse_base & solv_masse ()
const Solveur_Masse_base & solv_masse () const
Sources & sources ()
const Sources & sources () const
virtual void valider_iteration ()
virtual void verifie_ch_init_nb_comp (const Champ_Inc_base &ch_ref, const int nb_comp) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Equation_base
virtual Entree & lire_cl (Entree &)
virtual Entree & lire_cond_init (Entree &)
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual Entree & lire_sources (Entree &)
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
virtual int verif_Cl () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
See also
Conv_Diffusion_std Convection_Diffusion_Temperature
Constructor & Destructor Documentation
Convection_diffusion_turbulence_multiphase()
Convection_diffusion_turbulence_multiphase::Convection_diffusion_turbulence_multiphase ()
~Convection_diffusion_turbulence_multiphase()
Convection_diffusion_turbulence_multiphase::~Convection_diffusion_turbulence_multiphase () override
Member Function Documentation
info()
const Type_info * Convection_diffusion_turbulence_multiphase::info () static
get_info()
const Type_info * Convection_diffusion_turbulence_multiphase::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Convection_Diffusion_std.
Reimplemented in Echelle_temporelle_turbulente, Energie_cinetique_turbulente, and Taux_dissipation_turbulent.
self_cast() [1/2]
Convection_diffusion_turbulence_multiphase & Convection_diffusion_turbulence_multiphase::self_cast (Objet_U & r) static
self_cast() [2/2]
const Convection_diffusion_turbulence_multiphase & Convection_diffusion_turbulence_multiphase::self_cast (const Objet_U & r) static
printOn()
Sortie & Convection_diffusion_turbulence_multiphase::printOn (Sortie & is) const override protected virtual
Simple appel a: Convection_Diffusion_std::printOn(Sortie&)
Parameters
(Sortie& is) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Convection_Diffusion_std.
Reimplemented in Echelle_temporelle_turbulente, Energie_cinetique_turbulente, and Taux_dissipation_turbulent.
References Convection_Diffusion_std::printOn().
Referenced by Echelle_temporelle_turbulente::printOn(), Energie_cinetique_turbulente::printOn(), and Taux_dissipation_turbulent::printOn().
readOn()
Entree & Convection_diffusion_turbulence_multiphase::readOn (Entree & is) override protected virtual
Verifie si l'equation a une inconnue et un fluide associe et appelle Convection_Diffusion_std::readOn(Entree&).
Parameters
(Entree& is) un flot d'entree
Returns
(Entree& is) le flot d'entree modifie
Reimplemented from Convection_Diffusion_std.
Reimplemented in Echelle_temporelle_turbulente, Energie_cinetique_turbulente, and Taux_dissipation_turbulent.
References l_inco_ch, le_fluide, Objet_U_ptr::non_nul(), TRUST_Ref< _CLASSE_ >::non_nul(), and Convection_Diffusion_std::readOn().
Referenced by Echelle_temporelle_turbulente::readOn(), Energie_cinetique_turbulente::readOn(), and Taux_dissipation_turbulent::readOn().
completer()
void Convection_diffusion_turbulence_multiphase::completer () override virtual
Complete la construction (initialisation) des objets associes a l'equation.
Complete les sources, associe l'equation a l'inconnue complete les operateurs, complete les conditions aux limites discretisees. Voir les methodes Source_base::completer(), Operateur_base::completer() Domaine_Cl_dis_base::completer() Domaine_Cl_dis_base::completer(const Domaine_dis_base&)
Reimplemented from Equation_base.
References MorEqn::associer_eqn(), Operateur_base::associer_eqn(), Equation_base::completer(), Nom::debute_par(), Equation_base::domaine_Cl_dis(), Equation_base::domaine_dis(), inconnue(), Operateur_Grad::l_op_base(), Op_Grad_, Objet_U::que_suis_je(), and Operateur_Grad::typer().
inconnue() [1/2]
const Champ_Inc_base & Convection_diffusion_turbulence_multiphase::inconnue () const inline override virtual
Renvoie le champ inconnue representant l'inconnue (k, omega, epsilon, tau) (version const)
Returns
(Champ_Inc_base&) le champ inconnue representant la temperature (GP) ou l'enthalpie (GR)
Implements Convection_Diffusion_std.
References l_inco_ch.
Referenced by completer(), and Energie_cinetique_turbulente::mettre_a_jour().
inconnue() [2/2]
Champ_Inc_base & Convection_diffusion_turbulence_multiphase::inconnue () inline override virtual
Renvoie le champ inconnue representant l'inconnue (k, omega, epsilon, tau)
Returns
(Champ_Inc_base&) le champ inconnue representant la temperature (GP) ou l'enthalpie (GR)
Implements Convection_Diffusion_std.
References l_inco_ch.
associer_milieu_base()
void Convection_diffusion_turbulence_multiphase::associer_milieu_base (const Milieu_base & un_milieu) override virtual
Associe un milieu physique a l'equation, le milieu est en fait caste en Fluide_base ou en Fluide_Ostwald.
Parameters
(Milieu_base& un_milieu)
Exceptions
les proprietes physiques du fluide ne sont pas toutes specifiees
Implements Equation_base.
References le_fluide.
milieu() [1/2]
const Milieu_base & Convection_diffusion_turbulence_multiphase::milieu () const override virtual
Renvoie le milieu physique de l'equation.
(un Fluide_base upcaste en Milieu_base) (version const)
Returns
(Milieu_base&) le Fluide_base upcaste en Milieu_base
Implements Equation_base.
References le_fluide, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Echelle_temporelle_turbulente::diffusivite_pour_pas_de_temps(), Energie_cinetique_turbulente::diffusivite_pour_pas_de_temps(), Taux_dissipation_turbulent::diffusivite_pour_pas_de_temps(), Echelle_temporelle_turbulente::diffusivite_pour_transport(), Energie_cinetique_turbulente::diffusivite_pour_transport(), and Taux_dissipation_turbulent::diffusivite_pour_transport().
milieu() [2/2]
Milieu_base & Convection_diffusion_turbulence_multiphase::milieu () override virtual
Renvoie le milieu physique de l'equation.
(un Fluide_base upcaste en Milieu_base)
Returns
(Milieu_base&) le Fluide_base upcaste en Milieu_base
Implements Equation_base.
References le_fluide, and TRUST_Ref< _CLASSE_ >::valeur().
impr()
int Convection_diffusion_turbulence_multiphase::impr (Sortie & os) const override virtual
Impression des flux sur les bords sur un flot de sortie.
Appelle Equation_base::impr(Sortie&)
Parameters
(Sortie& os) un flot de sortie
Returns
(int) code de retour propage
Reimplemented from Equation_base.
References Equation_base::impr().
domaine_application()
const Motcle & Convection_diffusion_turbulence_multiphase::domaine_application () const override virtual
Renvoie le nom du domaine d'application de l'equation.
Ici "Turbulence".
Returns
(Motcle&) le nom du domaine d'application de l'equation
Reimplemented from Equation_base.
positive_unkown()
bool Convection_diffusion_turbulence_multiphase::positive_unkown () inline override virtual
Reimplemented from Equation_base.
operateur_gradient_inconnue()
const Operateur_Grad & Convection_diffusion_turbulence_multiphase::operateur_gradient_inconnue () const inline
References Op_Grad_.
Referenced by Diffusion_croisee_echelle_temp_taux_diss_turb_VDF::ajouter_blocs(), and Diffusion_supplementaire_echelle_temp_turb_VDF::ajouter_blocs().
Member Data Documentation
info_obj
const Type_info Convection_diffusion_turbulence_multiphase::info_obj static
l_inco_ch
TRUST_Deriv< Champ_Inc_base > Convection_diffusion_turbulence_multiphase::l_inco_ch protected
Referenced by Echelle_temporelle_turbulente::discretiser(), Energie_cinetique_turbulente::discretiser(), Taux_dissipation_turbulent::discretiser(), inconnue(), and readOn().
le_fluide
TRUST_Ref< Fluide_base *> Convection_diffusion_turbulence_multiphase::le_fluide protected
Referenced by associer_milieu_base(), milieu(), and readOn().
Op_Grad_
Operateur_Grad Convection_diffusion_turbulence_multiphase::Op_Grad_ protected
Referenced by completer(), and operateur_gradient_inconnue().