TrioCFD: Postraiter_domaine Class Reference
Postraiter_domaine Class Reference
#include <Postraiter_domaine.h>
Public Member Functions
const Type_info * get_info () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
Public Member Functions inherited from Interprete_geometrique_base_32_64< _SIZE_ >
const Type_info * get_info () const override
void mettre_a_jour_sous_domaine (Domaine_t &domaine, int_t &elem, int_t num_premier_elem, int_t nb_elem) const
Public Member Functions inherited from Interprete
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Interprete
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Interprete
static Objet_U & objet (const Nom &)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
See also
Interprete_geometrique_base
Constructor & Destructor Documentation
Postraiter_domaine()
Postraiter_domaine::Postraiter_domaine ()
~Postraiter_domaine()
Postraiter_domaine::~Postraiter_domaine ()
Member Function Documentation
cree_instance()
Objet_U * Postraiter_domaine::cree_instance () static
taille_memoire()
unsigned Postraiter_domaine::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Postraiter_domaine::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Postraiter_domaine::info () static
get_info()
const Type_info * Postraiter_domaine::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Interprete_geometrique_base_32_64< _SIZE_ >.
self_cast() [1/2]
Postraiter_domaine & Postraiter_domaine::self_cast (Objet_U & r) static
self_cast() [2/2]
const Postraiter_domaine & Postraiter_domaine::self_cast (const Objet_U & r) static
printOn()
Sortie & Postraiter_domaine::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Interprete_geometrique_base_32_64< _SIZE_ >.
References Interprete::printOn().
readOn()
Entree & Postraiter_domaine::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Interprete_geometrique_base_32_64< _SIZE_ >.
References Interprete::readOn().
interpreter_()
Entree & Postraiter_domaine::interpreter_ (Entree & is) override virtual
Implements Interprete_geometrique_base_32_64< _SIZE_ >.
References Param::ajouter(), Param::ajouter_condition(), Param::ajouter_non_std(), Interprete_geometrique_base_32_64< _SIZE_ >::associer_domaine(), Interprete_geometrique_base_32_64< _SIZE_ >::domaines(), dual_, ecrire(), ecrire_frontiere_, Process::exit(), format_binaire_, format_post_, joint_non_ecrit_, Param::lire_avec_accolades_depuis(), nb_domaine_, Objet_U::nom_du_cas(), Objet_U::que_suis_je(), and Param::REQUIRED.
ecrire()
void Postraiter_domaine::ecrire (Nom & nom_pdb)
References Process::barrier(), Domaine_32_64< _SIZE_ >::bord(), Domaine_dis_cache::Build_or_get(), Nom::debute_par(), Interprete_geometrique_base_32_64< _SIZE_ >::domaine(), Domaine_32_64< _SIZE_ >::domaines_frontieres(), dual_, Format_Post_base::ecrire_champ(), Format_Post_base::ecrire_domaine(), Format_Post_base::ecrire_domaine_dis(), Format_Post_base::ecrire_domaine_dual(), Format_Post_base::ecrire_entete(), ecrire_frontiere_, Format_Post_base::ecrire_temps(), Process::exit(), Frontiere_32_64< _SIZE_ >::faces(), Format_Post_base::finir(), format_binaire_, format_post_, Domaine_32_64< _SIZE_ >::frontiere(), Nom::getChar(), Format_Post_base::init_ecriture(), Format_Post_base::initialize(), Format_Post_base::initialize_by_default(), Process::je_suis_maitre(), Domaine_32_64< _SIZE_ >::joint(), joint_non_ecrit_, Domaine_base::le_nom(), Frontiere_32_64< _SIZE_ >::le_nom(), Sous_Domaine_32_64< _SIZE_ >::le_nom(), Objet_U_ptr::le_nom(), Domaine_32_64< _SIZE_ >::les_elems(), Process::me(), Process::mp_sum(), Domaine_32_64< _SIZE_ >::nb_bords(), nb_domaine_, Domaine_32_64< _SIZE_ >::nb_elem(), Domaine_32_64< _SIZE_ >::nb_elem_tot(), Sous_Domaine_32_64< _SIZE_ >::nb_elem_tot(), Domaine_32_64< _SIZE_ >::nb_joints(), Domaine_32_64< _SIZE_ >::nb_raccords(), Domaine_32_64< _SIZE_ >::nb_som(), Domaine_32_64< _SIZE_ >::nb_ss_domaines(), Nom::nom_me(), Process::nproc(), Joint_32_64< _SIZE_ >::PEvoisin(), Nom::prefix(), Format_Post_base::preparer_post(), Domaine_32_64< _SIZE_ >::raccord(), Domaine_32_64< _SIZE_ >::rang_frontiere(), Format_Post_base::set_postraiter_domain(), Format_Post_base::set_single_lata_option(), TRUST_List< _CLASSE_ >::size(), and Domaine_32_64< _SIZE_ >::ss_domaine().
Referenced by interpreter_().
lire_motcle_non_standard()
int Postraiter_domaine::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Objet_U.
References Interprete_geometrique_base_32_64< _SIZE_ >::associer_domaine(), and Process::exit().
Member Data Documentation
info_obj
const Type_info Postraiter_domaine::info_obj static
commande_
Nom Postraiter_domaine::commande_ protected
format_post_
Nom Postraiter_domaine::format_post_ protected
Referenced by ecrire(), and interpreter_().
nb_domaine_
int Postraiter_domaine::nb_domaine_ = 0 protected
Referenced by ecrire(), and interpreter_().
joint_non_ecrit_
int Postraiter_domaine::joint_non_ecrit_ = 1 protected
Referenced by ecrire(), and interpreter_().
format_binaire_
int Postraiter_domaine::format_binaire_ = 1 protected
Referenced by ecrire(), and interpreter_().
ecrire_frontiere_
int Postraiter_domaine::ecrire_frontiere_ = 1 protected
Referenced by ecrire(), and interpreter_().
dual_
int Postraiter_domaine::dual_ = 0 protected
Referenced by ecrire(), and interpreter_().