TrioCFD: Champ_lu_proto Class Reference
Champ_lu_proto Class Reference
#include <Champ_lu_proto.h>
Constructor & Destructor Documentation
~Champ_lu_proto()
virtual Champ_lu_proto::~Champ_lu_proto () inline virtual
Member Function Documentation
put_file_into_nom()
Nom Champ_lu_proto::put_file_into_nom (int n, const Nom & col_file) const
References Process::exit().
Referenced by Champ_Fonc_MED_Table_Temps::lire_motcle_non_standard(), Champ_front_Tabule_lu::readOn(), and Champ_Tabule_lu::readOn().