TrioCFD: PolyMAC_P0_discretisation Class Reference
PolyMAC_P0_discretisation Class Reference
#include <PolyMAC_P0_discretisation.h>
Public Member Functions
const Type_info * get_info () const override
void grad_u (const Domaine_dis_base &z, const Domaine_Cl_dis_base &zcl, const Champ_Inc_base &ch_vitesse, TRUST_Deriv< Champ_Fonc_base > &ch) const override
Public Member Functions inherited from PolyMAC_P0P1NC_discretisation
void discretiser_champ (const Motcle &directive, const Domaine_dis_base &z, Nature_du_champ nature, const Noms &nom, const Noms &unite, int nb_comp, double temps, TRUST_Deriv< Champ_Don_base > &champ) const override
void discretiser_champ (const Motcle &directive, const Domaine_dis_base &z, Nature_du_champ nature, const Noms &nom, const Noms &unite, int nb_comp, double temps, TRUST_Deriv< Champ_Fonc_base > &champ) const override
void discretiser_champ (const Motcle &directive, const Domaine_dis_base &z, Nature_du_champ nature, const Noms &nom, const Noms &unite, int nb_comp, int nb_pas_dt, double temps, TRUST_Deriv< Champ_Inc_base > &champ, const Nom &sous_type=NOM_VIDE) const override
void discretiser_champ (const Motcle &directive, const Domaine_dis_base &z, Nature_du_champ nature, const Noms &nom, const Noms &unite, int nb_comp, int nb_pas_dt, double temps, TRUST_Deriv< Champ_Inc_base > &champ, const Nom &sous_type=NOM_VIDE) const override
const Type_info * get_info () const override
Nom get_name_of_type_for (const Nom &class_operateur, const Nom &type_operateur, const Equation_base &eqn, const TRUST_Ref< Champ_base * > &champ_sup) const override
void grad_u (const Domaine_dis_base &z, const Domaine_Cl_dis_base &zcl, const Champ_Inc_base &ch_vitesse, TRUST_Deriv< Champ_Fonc_base > &ch) const override
void discretiser_champ (const Motcle &directive, const Domaine_dis_base &z, Nature_du_champ nature, const Noms &nom, const Noms &unite, int nb_comp, double temps, TRUST_Deriv< Champ_Don_base > &champ) const override
void discretiser_champ (const Motcle &directive, const Domaine_dis_base &z, Nature_du_champ nature, const Noms &nom, const Noms &unite, int nb_comp, double temps, TRUST_Deriv< Champ_Fonc_base > &champ) const override
void discretiser_champ (const Motcle &directive, const Domaine_dis_base &z, Nature_du_champ nature, const Noms &nom, const Noms &unite, int nb_comp, int nb_pas_dt, double temps, TRUST_Deriv< Champ_Inc_base > &champ, const Nom &sous_type=NOM_VIDE) const override
const Type_info * get_info () const override
Nom get_name_of_type_for (const Nom &class_operateur, const Nom &type_operateur, const Equation_base &eqn, const TRUST_Ref< Champ_base * > &champ_sup) const override
void grad_u (const Domaine_dis_base &z, const Domaine_Cl_dis_base &zcl, const Champ_Inc_base &ch_vitesse, TRUST_Deriv< Champ_Fonc_base > &ch) const override
Public Member Functions inherited from Discret_Thyd
const Type_info * get_info () const override
Public Member Functions inherited from Discret_Thermique
const Type_info * get_info () const override
virtual void discretiser_champ (const Motcle &directive, const Domaine_dis_base &z, Nature_du_champ nature, const Noms &nom, const Noms &unite, int nb_comp, int nb_pas_dt, double temps, TRUST_Deriv< Champ_Inc_base > &champ, const Nom &sous_type=NOM_VIDE) const
const Type_info * get_info () const override
virtual Nom get_name_of_type_for (const Nom &class_operateur, const Nom &type_operteur, const Equation_base &eqn, const TRUST_Ref< Champ_base * > &champ_supp=TRUST_Ref< Champ_base * >()) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from PolyMAC_P0P1NC_discretisation
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Discret_Thyd
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Discret_Thermique
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Discretisation_base
static void creer_champ (TRUST_Deriv< Champ_Don_base > &ch, const Domaine_dis_base &z, const Nom &type, const Nom &nom, const Nom &unite, int nb_comp, int nb_ddl, double temps, const Nom &directive=NOM_VIDE, const Nom &nom_discretisation=NOM_VIDE)
static void creer_champ (TRUST_Deriv< Champ_Fonc_base > &ch, const Domaine_dis_base &z, const Nom &type, const Nom &nom, const Nom &unite, int nb_comp, int nb_ddl, double temps, const Nom &directive=NOM_VIDE, const Nom &nom_discretisation=NOM_VIDE)
static void creer_champ (TRUST_Deriv< Champ_Inc_base > &ch, const Domaine_dis_base &z, const Nom &type, const Nom &nom, const Nom &unite, int nb_comp, int nb_ddl, int nb_pas_dt, double temps, const Nom &directive=NOM_VIDE, const Nom &nom_discretisation=NOM_VIDE)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
PolyMAC_P0_discretisation()
PolyMAC_P0_discretisation::PolyMAC_P0_discretisation ()
~PolyMAC_P0_discretisation()
PolyMAC_P0_discretisation::~PolyMAC_P0_discretisation ()
Member Function Documentation
cree_instance()
Objet_U * PolyMAC_P0_discretisation::cree_instance () static
taille_memoire()
unsigned PolyMAC_P0_discretisation::taille_memoire () const override virtual
Reimplemented from PolyMAC_discretisation.
duplique()
int PolyMAC_P0_discretisation::duplique () const override virtual
Reimplemented from PolyMAC_discretisation.
info()
const Type_info * PolyMAC_P0_discretisation::info () static
get_info()
const Type_info * PolyMAC_P0_discretisation::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from PolyMAC_discretisation.
self_cast() [1/2]
PolyMAC_P0_discretisation & PolyMAC_P0_discretisation::self_cast (Objet_U & r) static
self_cast() [2/2]
const PolyMAC_P0_discretisation & PolyMAC_P0_discretisation::self_cast (const Objet_U & r) static
printOn()
Sortie & PolyMAC_P0_discretisation::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from PolyMAC_discretisation.
readOn()
Entree & PolyMAC_P0_discretisation::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from PolyMAC_discretisation.
grad_u()
void PolyMAC_P0_discretisation::grad_u (const Domaine_dis_base & z, const Domaine_Cl_dis_base & zcl, const Champ_Inc_base & ch_vitesse, TRUST_Deriv< Champ_Fonc_base > & ch) const override virtual
discretise en PolyMAC le fluide incompressible, donc K e N
Postcondition: la methode ne modifie pas l'objet
Parameters
(Domaine_dis_base&) domaine a discretiser
(Fluide_Ostwald&) fluide a discretiser
(Champ_Inc_base&) ch_vitesse
(Champ_Inc_base&) temperature
Reimplemented from PolyMAC_discretisation.
References grad_Champ_Face_PolyMAC_P0::associer_champ(), grad_Champ_Face_PolyMAC_P0::associer_domaine_Cl_dis_base(), Champ_Fonc_base::associer_domaine_dis_base(), Champ_base::changer_temps(), Objet_U::dimension, Field_base::fixer_nature_du_champ(), Field_base::fixer_nb_comp(), grad_Champ_Face_PolyMAC_P0::fixer_nb_valeurs_nodales(), Field_base::fixer_nom_compo(), Field_base::fixer_unite(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Field_base::nommer(), Champ_Don_base::valeurs(), and Champ_Inc_base::valeurs().
taux_cisaillement()
void PolyMAC_P0_discretisation::taux_cisaillement (const Domaine_dis_base & z, const Domaine_Cl_dis_base & zcl, const Champ_Inc_base & ch_vitesse, TRUST_Deriv< Champ_Fonc_base > & ch) const override virtual
Reimplemented from Discret_Thyd.
References Champ_Fonc_Elem_PolyMAC_P0_TC::associer_champ(), Champ_Fonc_base::associer_domaine_dis_base(), Champ_base::changer_temps(), Champ_Inc_base::domaine_dis_base(), Field_base::fixer_nature_du_champ(), Field_base::fixer_nb_comp(), Champ_Fonc_P0_base::fixer_nb_valeurs_nodales(), Field_base::fixer_nom_compo(), Field_base::fixer_unite(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Field_base::nommer(), and Champ_Inc_base::valeurs().
creer_champ_vorticite()
void PolyMAC_P0_discretisation::creer_champ_vorticite (const Schema_Temps_base & sch, const Champ_Inc_base & ch_vitesse, TRUST_Deriv< Champ_Fonc_base > & ch) const override virtual
Reimplemented from Discret_Thyd.
References Process::abort(), Champ_Fonc_Elem_PolyMAC_P0_rot::associer_champ(), Champ_Fonc_base::associer_domaine_dis_base(), Champ_base::changer_temps(), Objet_U::dimension, Champ_Inc_base::domaine_dis_base(), Field_base::fixer_nature_du_champ(), Field_base::fixer_nb_comp(), Champ_Fonc_P0_base::fixer_nb_valeurs_nodales(), Field_base::fixer_nom_compo(), Field_base::fixer_unite(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Field_base::nommer(), and Champ_Inc_base::valeurs().
residu()
void PolyMAC_P0_discretisation::residu (const Domaine_dis_base & z, const Champ_Inc_base & ch_inco, TRUST_Deriv< Champ_Fonc_base > & champ) const override virtual
Reimplemented from Discretisation_base.
References Nom::debute_par(), Objet_U::dimension, PolyMAC_P0P1NC_discretisation::discretiser_champ(), Field_base::le_nom(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Objet_U::que_suis_je(), PolyMAC_P0P1NC_discretisation::residu(), Champ_base::temps(), Champ_Don_base::valeurs(), and Champ_Inc_base::valeurs().
is_polymac_p0()
bool PolyMAC_P0_discretisation::is_polymac_p0 () const inline override virtual
Reimplemented from Discretisation_base.
is_polymac_p0p1nc()
bool PolyMAC_P0_discretisation::is_polymac_p0p1nc () const inline override virtual
Reimplemented from Discretisation_base.
is_polymac()
bool PolyMAC_P0_discretisation::is_polymac () const inline override virtual
Reimplemented from PolyMAC_discretisation.
Member Data Documentation
info_obj
const Type_info PolyMAC_P0_discretisation::info_obj static