TrioCFD: Source_Fluide_Dilatable_VEF_Proto Class Reference
Source_Fluide_Dilatable_VEF_Proto Class Reference
#include <Source_Fluide_Dilatable_VEF_Proto.h>
Member Function Documentation
associer_domaines_impl()
void Source_Fluide_Dilatable_VEF_Proto::associer_domaines_impl (const Domaine_dis_base & domaine, const Domaine_Cl_dis_base & domaine_cl) protected
References le_dom, and le_dom_Cl.
Referenced by Source_QC_Chaleur_VEF::associer_domaines(), Source_WC_Chaleur_VEF::associer_domaines(), Source_QC_Gravite_VEF::associer_domaines(), and Source_WC_Gravite_VEF::associer_domaines().
associer_volume_porosite_impl()
void Source_Fluide_Dilatable_VEF_Proto::associer_volume_porosite_impl (const Domaine_dis_base & domaine, DoubleVect & volumes, DoubleVect & porosites) protected
References le_dom_Cl, and TRUSTVect< _TYPE_, _SIZE_ >::ref().
Referenced by Source_QC_Chaleur_VEF::associer_domaines(), and Source_WC_Chaleur_VEF::associer_domaines().
ajouter_impl()
void Source_Fluide_Dilatable_VEF_Proto::ajouter_impl (const Equation_base & eqn, const DoubleVect & g, const int dimension, const double rho_m, const DoubleTab & tab_rho, DoubleTab & resu) const protected
References Objet_U::dimension, Equation_base::discretisation(), Process::exit(), le_dom, le_dom_Cl, Front_VF::nb_faces(), Front_VF::num_premiere_face(), Objet_U::que_suis_je(), TRUST_Deriv< _CLASSE_ >::valeur(), TRUSTArray< _TYPE_, _SIZE_ >::view_ro(), and TRUSTTab< _TYPE_, _SIZE_ >::view_rw().
Referenced by Source_QC_Gravite_VEF::ajouter(), and Source_WC_Gravite_VEF::ajouter().
Member Data Documentation
le_dom
TRUST_Ref< Domaine_VEF *> Source_Fluide_Dilatable_VEF_Proto::le_dom protected
Referenced by ajouter_impl(), and associer_domaines_impl().
le_dom_Cl
TRUST_Ref< Domaine_Cl_VEF *> Source_Fluide_Dilatable_VEF_Proto::le_dom_Cl protected
Referenced by ajouter_impl(), associer_domaines_impl(), and associer_volume_porosite_impl().