TrioCFD: DP_Impose_VEF_Face Class Reference
DP_Impose_VEF_Face Class Reference
#include <DP_Impose_VEF_Face.h>
Public Member Functions
void completer () override
const Type_info * get_info () const override
void mettre_a_jour (double temps) override
Public Member Functions inherited from Perte_Charge_VEF_Face
const Type_info * get_info () const override
void mettre_a_jour (double) override
Public Member Functions inherited from Source_base
virtual int a_pour_Champ_Fonc (const Motcle &mot, TRUST_Ref< Champ_base * > &ch_ref) const
virtual void associer_champ_rho (const Champ_base &champ_rho)
virtual void completer ()
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
virtual void resetTime (double t)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Terme_Source_Qdm
const Champ_Don_base & source () const
Public Member Functions inherited from DP_Impose
Entree & lire_donnees (Entree &)
Public Member Functions inherited from Perte_Charge_Singuliere
double K () const
Entree & lire_donnees (Entree &)
Public Member Functions inherited from Perte_Charge
int direction_perte_charge () const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Perte_Charge_VEF_Face
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
See also
Perte_Charge_VEF_Face
Constructor & Destructor Documentation
DP_Impose_VEF_Face()
DP_Impose_VEF_Face::DP_Impose_VEF_Face ()
~DP_Impose_VEF_Face()
DP_Impose_VEF_Face::~DP_Impose_VEF_Face ()
Member Function Documentation
cree_instance()
Objet_U * DP_Impose_VEF_Face::cree_instance () static
taille_memoire()
unsigned DP_Impose_VEF_Face::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int DP_Impose_VEF_Face::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * DP_Impose_VEF_Face::info () static
get_info()
const Type_info * DP_Impose_VEF_Face::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Source_base.
self_cast() [1/2]
DP_Impose_VEF_Face & DP_Impose_VEF_Face::self_cast (Objet_U & r) static
self_cast() [2/2]
const DP_Impose_VEF_Face & DP_Impose_VEF_Face::self_cast (const Objet_U & r) static
printOn()
Sortie & DP_Impose_VEF_Face::printOn (Sortie & os) const override protected virtual
DOES NOTHING - to override in derived classes.
Imprime la source sur un flot de sortie.
Parameters
(Sortie& os) le flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Source_base.
References Objet_U::que_suis_je().
readOn()
Entree & DP_Impose_VEF_Face::readOn (Entree & is) override protected virtual
DOES NOTHING - to override in derived classes.
Lecture d'un terme source sur un flot d'entree.
Parameters
(Entree& is) le flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Source_base.
References TRUST_Vector< _CLASSE_ >::add(), Process::exit(), Perte_Charge_Singuliere::identifiant_, DP_Impose::lire_donnees(), Process::mp_max(), Perte_Charge_Singuliere::regul_, remplir_num_faces(), Source_base::set_col_names(), Source_base::set_description(), Source_base::set_fichier(), sgn, and TRUSTVect< _TYPE_, _SIZE_ >::size().
has_interface_blocs()
int DP_Impose_VEF_Face::has_interface_blocs () const inline override virtual
Reimplemented from Source_base.
dimensionner_blocs()
void DP_Impose_VEF_Face::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl = {}) const override virtual
Reimplemented from Source_base.
References Matrix_tools::allocate_morse_matrix(), TRUSTTab< _TYPE_, _SIZE_ >::append_line(), Objet_U::dimension, MorEqn::equation(), Nom::getString(), Equation_base::inconnue(), Field_base::le_nom(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Matrice_Morse::nb_colonnes(), Domaine_VF::nb_faces(), Domaine_VF::nb_faces_tot(), Perte_Charge_VEF_Face::num_faces, TRUSTVect< _TYPE_, _SIZE_ >::size(), and Champ_Inc_base::valeurs().
ajouter_blocs()
void DP_Impose_VEF_Face::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = {}) const override virtual
Reimplemented from Source_base.
References Source_base::bilan(), Objet_U::dimension, DP_Impose::DP_, DP_Impose::dp_regul_, MorEqn::equation(), Domaine_VF::face_normales(), Domaine_VF::face_surfaces(), Nom::getString(), Equation_base::inconnue(), Probleme_base::is_dilatable(), Field_base::le_nom(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Milieu_base::masse_volumique(), Process::me(), Equation_base::milieu(), Process::mp_max(), Domaine_VF::nb_faces(), Perte_Charge_VEF_Face::num_faces, Milieu_base::porosite_face(), Equation_base::probleme(), Perte_Charge_Singuliere::regul_, sgn, TRUSTVect< _TYPE_, _SIZE_ >::size(), surf, Champ_base::valeur_aux(), Champ_Inc_base::valeurs(), Champ_Proto::valeurs(), and Domaine_VF::xv().
remplir_num_faces()
void DP_Impose_VEF_Face::remplir_num_faces (Entree & s)
References Domaine_VF::creer_tableau_faces(), Probleme_base::domaine(), MorEqn::equation(), Process::exit(), Domaine_VF::face_surfaces(), Process::je_suis_maitre(), Perte_Charge_Singuliere::lire_surfaces(), Process::mp_max(), Domaine_dis_base::nb_elem(), Perte_Charge_VEF_Face::num_faces, Equation_base::probleme(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), sgn, TRUSTVect< _TYPE_, _SIZE_ >::size(), and surf.
Referenced by readOn().
mettre_a_jour()
void DP_Impose_VEF_Face::mettre_a_jour (double temps) override virtual
DOES NOTHING - to override in derived classes.
Mise a jour en temps du terme source.
Parameters
(double) le pas de temps de mise a jour
Reimplemented from Source_base.
References Source_base::bilan(), Perte_Charge_Singuliere::calculate_Q(), MorEqn::equation(), Process::me(), DP_Impose::mettre_a_jour(), Perte_Charge_VEF_Face::num_faces, Perte_Charge_Singuliere::regul_, sgn, and DP_Impose::update_dp_regul().
completer()
void DP_Impose_VEF_Face::completer () override virtual
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees: Source_base::associer_domaines(const Domaine_dis_base& ,const Domaine_Cl_dis_base&) Source_base::associer_pb(const Probleme_base&)
Reimplemented from Source_base.
References Source_base::bilan(), Source_base::completer(), Perte_Charge_Singuliere::regul_, and TRUSTVect< _TYPE_, _SIZE_ >::resize().
ajouter()
DoubleTab & DP_Impose_VEF_Face::ajouter (DoubleTab & resu) const inline override virtual
Implements Perte_Charge_VEF_Face.
References Source_base::ajouter().
Member Data Documentation
info_obj
const Type_info DP_Impose_VEF_Face::info_obj static
sgn
IntVect DP_Impose_VEF_Face::sgn protected
Referenced by ajouter_blocs(), mettre_a_jour(), readOn(), and remplir_num_faces().
surf
double DP_Impose_VEF_Face::surf = -123. protected
Referenced by ajouter_blocs(), and remplir_num_faces().