TrioCFD: Production_energie_cin_turb_VDF Class Reference
Production_energie_cin_turb_VDF Class Reference
#include <Production_energie_cin_turb_VDF.h>
Public Member Functions
void completer () override
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Sources_Multiphase_base
const Type_info * get_info () const override
void mettre_a_jour (double temps) override
Public Member Functions inherited from Source_base
virtual int a_pour_Champ_Fonc (const Motcle &mot, TRUST_Ref< Champ_base * > &ch_ref) const
virtual void associer_champ_rho (const Champ_base &champ_rho)
virtual void completer ()
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
virtual void resetTime (double t)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
See also
Operateur_PolyMAC_P0_base Operateur_base
Constructor & Destructor Documentation
Production_energie_cin_turb_VDF()
Production_energie_cin_turb_VDF::Production_energie_cin_turb_VDF ()
~Production_energie_cin_turb_VDF()
Production_energie_cin_turb_VDF::~Production_energie_cin_turb_VDF ()
Member Function Documentation
cree_instance()
Objet_U * Production_energie_cin_turb_VDF::cree_instance () static
taille_memoire()
unsigned Production_energie_cin_turb_VDF::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Production_energie_cin_turb_VDF::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Production_energie_cin_turb_VDF::info () static
get_info()
const Type_info * Production_energie_cin_turb_VDF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Source_Production_energie_cin_turb.
self_cast() [1/2]
Production_energie_cin_turb_VDF & Production_energie_cin_turb_VDF::self_cast (Objet_U & r) static
self_cast() [2/2]
const Production_energie_cin_turb_VDF & Production_energie_cin_turb_VDF::self_cast (const Objet_U & r) static
printOn()
Sortie & Production_energie_cin_turb_VDF::printOn (Sortie & os) const override protected virtual
DOES NOTHING - to override in derived classes.
Imprime la source sur un flot de sortie.
Parameters
(Sortie& os) le flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Source_Production_energie_cin_turb.
References Source_Production_energie_cin_turb::printOn().
readOn()
Entree & Production_energie_cin_turb_VDF::readOn (Entree & is) override protected virtual
DOES NOTHING - to override in derived classes.
Lecture d'un terme source sur un flot d'entree.
Parameters
(Entree& is) le flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Source_Production_energie_cin_turb.
References Source_Production_energie_cin_turb::readOn().
ajouter_blocs()
void Production_energie_cin_turb_VDF::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = {}) const override virtual
Implements Source_Production_energie_cin_turb.
References MD_Vector_tools::creer_tableau_distribue(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Viscosite_turbulente_base::eddy_viscosity(), MorEqn::equation(), Probleme_base::equation(), Probleme_base::get_champ(), TRUSTVect< _TYPE_, _SIZE_ >::get_md_vector(), Probleme_base::has_champ(), Equation_base::inconnue(), Operateur::l_op_base(), Viscosite_turbulente_base::limiteur(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Milieu_base::masse_volumique(), Equation_base::milieu(), Probleme_base::nombre_d_equations(), Navier_Stokes_std::operateur(), Champ_Proto::passe(), Milieu_base::porosite_elem(), Navier_Stokes_std::pression(), Equation_base::probleme(), Champ_Inc_base::valeurs(), and Champ_Proto::valeurs().
completer()
void Production_energie_cin_turb_VDF::completer () override virtual
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees: Source_base::associer_domaines(const Domaine_dis_base& ,const Domaine_Cl_dis_base&) Source_base::associer_pb(const Probleme_base&)
Reimplemented from Source_base.
References MorEqn::equation(), Process::exit(), Operateur::l_op_base(), Navier_Stokes_std::operateur(), and Objet_U::que_suis_je().
Member Data Documentation
info_obj
const Type_info Production_energie_cin_turb_VDF::info_obj static