TrioCFD: Frottement_interfacial_base Class Reference
Frottement_interfacial_base Class Reference abstract
#include <Frottement_interfacial_base.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
 F_{kl} = - F_{lk} = - C_{kl} (u_k - u_l)
 cette classe definit une fonction C_{kl} dependant de :
   alpha, p, T -> inconnues (une valeur par phase chacune)
   rho, mu, sigma -> proprietes physiques (idem)
   ndv(k, l) -> ||v_k - v_l||, a remplir pour k < l
sortie : coeff(k, l, 0/1) -> coefficient C_{kl} et sa derivee en ndv(k, l), rempli pour k < l
Constructor & Destructor Documentation
Frottement_interfacial_base()
Frottement_interfacial_base::Frottement_interfacial_base ()
~Frottement_interfacial_base()
Frottement_interfacial_base::~Frottement_interfacial_base () override
Member Function Documentation
info()
const Type_info * Frottement_interfacial_base::info () static
get_info()
const Type_info * Frottement_interfacial_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Correlation_base.
Reimplemented in Frottement_interfacial_Ishii_Zuber_Deformable, Frottement_interfacial_Kumar_Brooks, Frottement_interfacial_Tomiyama_complet, Frottement_interfacial_bulles_composant, Frottement_interfacial_bulles_constant, Frottement_interfacial_Garnier, Frottement_interfacial_Ishii_Zuber, Frottement_interfacial_Rusche, Frottement_interfacial_Simonnet, Frottement_interfacial_Sonnenburg, Frottement_interfacial_Tomiyama, Frottement_interfacial_Wallis, Frottement_interfacial_Weber, and Frottement_interfacial_Zenit.
self_cast() [1/2]
Frottement_interfacial_base & Frottement_interfacial_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Frottement_interfacial_base & Frottement_interfacial_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Frottement_interfacial_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Correlation_base.
Reimplemented in Frottement_interfacial_Ishii_Zuber_Deformable, Frottement_interfacial_Kumar_Brooks, Frottement_interfacial_Tomiyama_complet, Frottement_interfacial_bulles_composant, Frottement_interfacial_bulles_constant, Frottement_interfacial_Garnier, Frottement_interfacial_Ishii_Zuber, Frottement_interfacial_Rusche, Frottement_interfacial_Simonnet, Frottement_interfacial_Sonnenburg, Frottement_interfacial_Tomiyama, Frottement_interfacial_Wallis, Frottement_interfacial_Weber, and Frottement_interfacial_Zenit.
readOn()
Entree & Frottement_interfacial_base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Correlation_base.
Reimplemented in Frottement_interfacial_Ishii_Zuber_Deformable, Frottement_interfacial_Kumar_Brooks, Frottement_interfacial_Tomiyama_complet, Frottement_interfacial_bulles_composant, Frottement_interfacial_bulles_constant, Frottement_interfacial_Garnier, Frottement_interfacial_Ishii_Zuber, Frottement_interfacial_Rusche, Frottement_interfacial_Simonnet, Frottement_interfacial_Sonnenburg, Frottement_interfacial_Tomiyama, Frottement_interfacial_Wallis, Frottement_interfacial_Weber, and Frottement_interfacial_Zenit.
coefficient()
virtual void Frottement_interfacial_base::coefficient (const DoubleTab & alpha, const DoubleTab & p, const DoubleTab & T, const DoubleTab & rho, const DoubleTab & mu, const DoubleTab & sigma, double Dh, const DoubleTab & ndv, const DoubleTab & d_bulles, DoubleTab & coeff) const pure virtual
Implemented in Frottement_interfacial_Ishii_Zuber_Deformable, Frottement_interfacial_Kumar_Brooks, Frottement_interfacial_Tomiyama_complet, Frottement_interfacial_bulles_composant, Frottement_interfacial_bulles_constant, Frottement_interfacial_Garnier, Frottement_interfacial_Ishii_Zuber, Frottement_interfacial_Rusche, Frottement_interfacial_Simonnet, Frottement_interfacial_Sonnenburg, Frottement_interfacial_Tomiyama, Frottement_interfacial_Wallis, Frottement_interfacial_Weber, and Frottement_interfacial_Zenit.
Referenced by Frottement_interfacial_PolyMAC_P0::ajouter_blocs(), Frottement_interfacial_VDF::ajouter_blocs(), Dispersion_bulles_turbulente_Burns::coefficient(), and Portance_interfaciale_Sugrue_Modifiee::coefficient().
coefficient_CD()
virtual void Frottement_interfacial_base::coefficient_CD (const DoubleTab & alpha, const DoubleTab & p, const DoubleTab & T, const DoubleTab & rho, const DoubleTab & mu, const DoubleTab & sigma, double Dh, const DoubleTab & ndv, const DoubleTab & d_bulles, DoubleTab & coeff) const inline virtual
Reimplemented in Frottement_interfacial_Ishii_Zuber_Deformable, Frottement_interfacial_Kumar_Brooks, Frottement_interfacial_Tomiyama_complet, Frottement_interfacial_Ishii_Zuber, and Frottement_interfacial_Tomiyama.
Referenced by Dispersion_bulles_turbulente_Bazin::coefficient(), Dispersion_bulles_turbulente_Bertodano::coefficient(), and Dispersion_bulles_turbulente_Lavieville::coefficient().
Member Data Documentation
info_obj
const Type_info Frottement_interfacial_base::info_obj static