TrioCFD: corrections_qdm Class Reference
corrections_qdm Class Reference
#include <corrections_qdm.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
<Corrections to comply with the mean momentum budget in the three directions.>
Member Enumeration Documentation
type_dict_
enum corrections_qdm::type_dict_
Enumerator
GB
GR
NONE_IJK
Constructor & Destructor Documentation
~corrections_qdm()
corrections_qdm::~corrections_qdm ()
corrections_qdm()
corrections_qdm::corrections_qdm ()
Member Function Documentation
cree_instance()
Objet_U * corrections_qdm::cree_instance () static
taille_memoire()
unsigned corrections_qdm::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int corrections_qdm::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * corrections_qdm::info () static
get_info()
const Type_info * corrections_qdm::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
corrections_qdm & corrections_qdm::self_cast (Objet_U & r) static
self_cast() [2/2]
const corrections_qdm & corrections_qdm::self_cast (const Objet_U & r) static
printOn()
Sortie & corrections_qdm::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
References correction_x_, correction_y_, correction_z_, GB, get_type_(), GR, NONE_IJK, and write_me_.
readOn()
Entree & corrections_qdm::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
References Param::ajouter(), Param::ajouter_flag(), correction_x_, correction_y_, correction_z_, Param::dictionnaire(), GB, GR, Param::lire_avec_accolades(), NONE_IJK, Objet_U::que_suis_je(), type_, and write_me_.
set_corrections()
void corrections_qdm::set_corrections (correction_one_direction & in_corr_x_, correction_one_direction & in_corr_y_, correction_one_direction & in_corr_z_)
References correction_x_, correction_y_, correction_z_, and correction_one_direction::set_correction().
set_time()
void corrections_qdm::set_time (double time, double time_step, int time_iteration)
References correction_x_, correction_y_, correction_z_, and correction_one_direction::set_time_for_correction().
Referenced by Navier_Stokes_FTD_IJK::set_time_for_corrections().
set_vitesse_relative()
void corrections_qdm::set_vitesse_relative (int direction, double vitesse_relative)
References correction_x_, correction_y_, correction_z_, correction_one_direction::get_need_for_vit_rel(), and correction_one_direction::set_vl_vv().
Referenced by Navier_Stokes_FTD_IJK::compute_and_add_qdm_corrections(), and Navier_Stokes_FTD_IJK::compute_and_add_qdm_corrections_monophasic().
set_rho_liquide()
void corrections_qdm::set_rho_liquide (double rho_liquide)
References correction_x_, correction_y_, correction_z_, correction_one_direction::get_need_for_rho_liq(), and correction_one_direction::set_rho_liq().
Referenced by Navier_Stokes_FTD_IJK::compute_and_add_qdm_corrections(), and Navier_Stokes_FTD_IJK::compute_and_add_qdm_corrections_monophasic().
set_rho_moyen_alpha_l()
void corrections_qdm::set_rho_moyen_alpha_l (double rho_moyen, double alpha_l)
References correction_x_, correction_y_, correction_z_, and correction_one_direction::set_rho_moyen_alpha_l_for_correction().
Referenced by Navier_Stokes_FTD_IJK::compute_and_add_qdm_corrections(), and Navier_Stokes_FTD_IJK::compute_and_add_qdm_corrections_monophasic().
set_rho_vel_moyen()
void corrections_qdm::set_rho_vel_moyen (int direction, double rho_vel_moyen)
References correction_x_, correction_y_, correction_z_, and correction_one_direction::set_rho_vel_moyen_for_correction().
Referenced by Navier_Stokes_FTD_IJK::compute_and_add_qdm_corrections(), and Navier_Stokes_FTD_IJK::compute_and_add_qdm_corrections_monophasic().
set_mean_values_for_corrections()
void corrections_qdm::set_mean_values_for_corrections (double rho_vel_moyen, double rho_moyen, double alpha_l)
References correction_x_, correction_y_, correction_z_, and correction_one_direction::set_mean_values_for_correction().
compute_correction_value_one_direction()
void corrections_qdm::compute_correction_value_one_direction (int dir)
References correction_one_direction::compute_correction_value(), correction_x_, correction_y_, and correction_z_.
Referenced by Navier_Stokes_FTD_IJK::compute_and_add_qdm_corrections(), and Navier_Stokes_FTD_IJK::compute_and_add_qdm_corrections_monophasic().
compute_correct_velocity_one_direction()
void corrections_qdm::compute_correct_velocity_one_direction (int dir, double vel_ijk_t)
References correction_one_direction::compute_correct_velocity(), correction_x_, correction_y_, and correction_z_.
Referenced by Navier_Stokes_FTD_IJK::compute_and_add_qdm_corrections(), and Navier_Stokes_FTD_IJK::compute_and_add_qdm_corrections_monophasic().
get_correct_velocities()
Vecteur3 corrections_qdm::get_correct_velocities ()
References correction_x_, correction_y_, correction_z_, and correction_one_direction::get_correct_velocity().
get_velocity_corrections()
Vecteur3 corrections_qdm::get_velocity_corrections ()
References correction_x_, correction_y_, correction_z_, and correction_one_direction::get_velocity_correction().
Referenced by Navier_Stokes_FTD_IJK::write_qdm_corrections_information().
get_correction_values()
Vecteur3 corrections_qdm::get_correction_values ()
References correction_x_, correction_y_, correction_z_, and correction_one_direction::get_correction_value().
Referenced by Navier_Stokes_FTD_IJK::write_qdm_corrections_information().
get_correct_velocitiy_one_direction()
double corrections_qdm::get_correct_velocitiy_one_direction (int dir)
References correction_x_, correction_y_, correction_z_, and correction_one_direction::get_correct_velocity().
Referenced by Navier_Stokes_FTD_IJK::compute_and_add_qdm_corrections(), and Navier_Stokes_FTD_IJK::compute_and_add_qdm_corrections_monophasic().
get_need_for_vitesse_relative()
int corrections_qdm::get_need_for_vitesse_relative (int direction)
References correction_x_, correction_y_, correction_z_, and correction_one_direction::get_need_for_vit_rel().
Referenced by Navier_Stokes_FTD_IJK::compute_and_add_qdm_corrections(), and Navier_Stokes_FTD_IJK::compute_and_add_qdm_corrections_monophasic().
get_need_to_compute_correction_value_one_direction()
int corrections_qdm::get_need_to_compute_correction_value_one_direction (int direction)
References correction_x_, correction_y_, correction_z_, and correction_one_direction::get_need_to_compute_correction_value().
Referenced by Navier_Stokes_FTD_IJK::compute_and_add_qdm_corrections(), and Navier_Stokes_FTD_IJK::compute_and_add_qdm_corrections_monophasic().
get_type_()
corrections_qdm::type_dict_ corrections_qdm::get_type_ () const
References type_.
Referenced by printOn().
is_type_gb()
int corrections_qdm::is_type_gb () const
References GB, and type_.
Referenced by Navier_Stokes_FTD_IJK::calculer_terme_source_acceleration().
is_type_gr()
int corrections_qdm::is_type_gr () const
References GR, and type_.
is_type_none()
int corrections_qdm::is_type_none () const
References NONE_IJK, and type_.
Referenced by Navier_Stokes_FTD_IJK::corriger_qdm().
write_me()
int corrections_qdm::write_me () const
References write_me_.
Referenced by Navier_Stokes_FTD_IJK::corriger_qdm().
Member Data Documentation
info_obj
const Type_info corrections_qdm::info_obj static
type_
int corrections_qdm::type_ protected
Referenced by get_type_(), is_type_gb(), is_type_gr(), is_type_none(), and readOn().
write_me_
int corrections_qdm::write_me_ protected
Referenced by printOn(), readOn(), and write_me().
correction_x_
correction_one_direction corrections_qdm::correction_x_ protected
Referenced by compute_correct_velocity_one_direction(), compute_correction_value_one_direction(), get_correct_velocities(), get_correct_velocitiy_one_direction(), get_correction_values(), get_need_for_vitesse_relative(), get_need_to_compute_correction_value_one_direction(), get_velocity_corrections(), printOn(), readOn(), set_corrections(), set_mean_values_for_corrections(), set_rho_liquide(), set_rho_moyen_alpha_l(), set_rho_vel_moyen(), set_time(), and set_vitesse_relative().
correction_y_
correction_one_direction corrections_qdm::correction_y_ protected
Referenced by compute_correct_velocity_one_direction(), compute_correction_value_one_direction(), get_correct_velocities(), get_correct_velocitiy_one_direction(), get_correction_values(), get_need_for_vitesse_relative(), get_need_to_compute_correction_value_one_direction(), get_velocity_corrections(), printOn(), readOn(), set_corrections(), set_mean_values_for_corrections(), set_rho_liquide(), set_rho_moyen_alpha_l(), set_rho_vel_moyen(), set_time(), and set_vitesse_relative().
correction_z_
correction_one_direction corrections_qdm::correction_z_ protected
Referenced by compute_correct_velocity_one_direction(), compute_correction_value_one_direction(), get_correct_velocities(), get_correct_velocitiy_one_direction(), get_correction_values(), get_need_for_vitesse_relative(), get_need_to_compute_correction_value_one_direction(), get_velocity_corrections(), printOn(), readOn(), set_corrections(), set_mean_values_for_corrections(), set_rho_liquide(), set_rho_moyen_alpha_l(), set_rho_vel_moyen(), set_time(), and set_vitesse_relative().