TrioCFD: Dispersion_bulles_PolyMAC_P0 Class Reference
Dispersion_bulles_PolyMAC_P0 Class Reference
#include <Dispersion_bulles_PolyMAC_P0.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Source_Dispersion_bulles_base
const Type_info * get_info () const override
Public Member Functions inherited from Sources_Multiphase_base
const Type_info * get_info () const override
void mettre_a_jour (double temps) override
Public Member Functions inherited from Source_base
virtual int a_pour_Champ_Fonc (const Motcle &mot, TRUST_Ref< Champ_base * > &ch_ref) const
virtual void associer_champ_rho (const Champ_base &champ_rho)
virtual void completer ()
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
virtual void resetTime (double t)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Source_Dispersion_bulles_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Sources_Multiphase_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Dispersion_bulles_PolyMAC_P0()
Dispersion_bulles_PolyMAC_P0::Dispersion_bulles_PolyMAC_P0 ()
~Dispersion_bulles_PolyMAC_P0()
Dispersion_bulles_PolyMAC_P0::~Dispersion_bulles_PolyMAC_P0 ()
Member Function Documentation
cree_instance()
Objet_U * Dispersion_bulles_PolyMAC_P0::cree_instance () static
taille_memoire()
unsigned Dispersion_bulles_PolyMAC_P0::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Dispersion_bulles_PolyMAC_P0::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Dispersion_bulles_PolyMAC_P0::info () static
get_info()
const Type_info * Dispersion_bulles_PolyMAC_P0::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Source_base.
self_cast() [1/2]
Dispersion_bulles_PolyMAC_P0 & Dispersion_bulles_PolyMAC_P0::self_cast (Objet_U & r) static
self_cast() [2/2]
const Dispersion_bulles_PolyMAC_P0 & Dispersion_bulles_PolyMAC_P0::self_cast (const Objet_U & r) static
printOn()
Sortie & Dispersion_bulles_PolyMAC_P0::printOn (Sortie & os) const override protected virtual
DOES NOTHING - to override in derived classes.
Imprime la source sur un flot de sortie.
Parameters
(Sortie& os) le flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Source_base.
readOn()
Entree & Dispersion_bulles_PolyMAC_P0::readOn (Entree & is) override protected virtual
DOES NOTHING - to override in derived classes.
Lecture d'un terme source sur un flot d'entree.
Parameters
(Entree& is) le flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Source_base.
References MorEqn::equation(), Source_Dispersion_bulles_base::is_turb, and Source_Dispersion_bulles_base::readOn().
ajouter_blocs()
void Dispersion_bulles_PolyMAC_P0::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = {}) const override protected virtual
Implements Source_Dispersion_bulles_base.
References Dispersion_bulles_base::input_t::alpha, Source_Dispersion_bulles_base::beta_, Dispersion_bulles_base::coefficient(), Source_Dispersion_bulles_base::correlation(), Source_Dispersion_bulles_base::correlation_, Dispersion_bulles_base::output_t::Ctd, Dispersion_bulles_base::input_t::d_bulles, Objet_U::dimension, Champ_Inc_base::domaine_Cl_dis(), Dispersion_bulles_base::input_t::e, MorEqn::equation(), Pb_Multiphase::equation_energie(), Pb_Multiphase::equation_masse(), Pb_Multiphase::equation_qdm(), Process::exit(), Champ_Inc_P0_base::fcl(), Champ_Face_base::fcl(), Champ_Elem_PolyMAC_P0::fgrad_d, Champ_Elem_PolyMAC_P0::fgrad_e, Champ_Elem_PolyMAC_P0::fgrad_w, Probleme_base::get_champ(), Milieu_composite::get_interface(), Milieu_composite::get_saturation(), Interface_base::get_sigma_tab(), Probleme_base::has_champ(), Milieu_composite::has_interface(), Milieu_composite::has_saturation(), Equation_base::inconnue(), Champ_Elem_PolyMAC_P0::init_grad(), Source_Dispersion_bulles_base::is_turb, Dispersion_bulles_base::input_t::k_turb, Dispersion_bulles_base::input_t::k_WIT, Domaine_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Milieu_base::masse_volumique(), Equation_base::milieu(), Dispersion_bulles_base::input_t::mu, Dispersion_bulles_base::input_t::nut, Dispersion_bulles_base::input_t::nv, Dispersion_bulles_base::input_t::p, Champ_Proto::passe(), Champ_Inc_base::passe(), Milieu_base::porosite_elem(), Milieu_base::porosite_face(), Equation_base::probleme(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Pb_Multiphase::resolution_en_T(), Dispersion_bulles_base::input_t::rho, Dispersion_bulles_base::input_t::sigma, Interface_base::sigma(), Interface_base::sigma_h(), Dispersion_bulles_base::input_t::T, Champ_Face_PolyMAC_P0::v_norm(), TRUST_Ref< _CLASSE_ >::valeur(), and Champ_Proto::valeurs().
dimensionner_blocs_aux()
void Dispersion_bulles_PolyMAC_P0::dimensionner_blocs_aux (IntTab & stencil) const override protected virtual
Implements Source_Dispersion_bulles_base.
References TRUSTTab< _TYPE_, _SIZE_ >::append_line(), Objet_U::dimension, MorEqn::equation(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), and Champ_Inc_base::valeurs().
Member Data Documentation
info_obj
const Type_info Dispersion_bulles_PolyMAC_P0::info_obj static