TrioCFD: Flux_parietal_Hibiki Class Reference
Flux_parietal_Hibiki Class Reference
#include <Flux_parietal_Hibiki.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
 pour un ecoulement turbulent avec une loi de paroi adaptative
 (i.e. qui peut gerer la zone visqueuse comme la zone log en proche paroi)
 cf page 123 de la these de Hibiki
Constructor & Destructor Documentation
Flux_parietal_Hibiki()
Flux_parietal_Hibiki::Flux_parietal_Hibiki ()
~Flux_parietal_Hibiki()
Flux_parietal_Hibiki::~Flux_parietal_Hibiki ()
Member Function Documentation
cree_instance()
Objet_U * Flux_parietal_Hibiki::cree_instance () static
taille_memoire()
unsigned Flux_parietal_Hibiki::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Flux_parietal_Hibiki::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Flux_parietal_Hibiki::info () static
get_info()
const Type_info * Flux_parietal_Hibiki::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Flux_parietal_base.
self_cast() [1/2]
Flux_parietal_Hibiki & Flux_parietal_Hibiki::self_cast (Objet_U & r) static
self_cast() [2/2]
const Flux_parietal_Hibiki & Flux_parietal_Hibiki::self_cast (const Objet_U & r) static
printOn()
Sortie & Flux_parietal_Hibiki::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Flux_parietal_base.
References Flux_parietal_base::printOn().
readOn()
Entree & Flux_parietal_Hibiki::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Flux_parietal_base.
References Param::ajouter(), correlation_monophasique_, Nom::debute_par(), Process::exit(), Nom::finit_par(), G_, Param::lire_avec_accolades(), molar_mass_, n_g1, n_g2, n_l, Pb_Multiphase::nb_phases(), Pb_Multiphase::nom_phase(), Correlation_base::pb_, Objet_U::que_suis_je(), Qw_, Param::REQUIRED, theta_, Correlation_base::typer_lire_correlation(), and TRUST_Ref< _CLASSE_ >::valeur().
qp()
void Flux_parietal_Hibiki::qp (const input_t & input, output_t & output) const override virtual
Implements Flux_parietal_base.
References correlation_monophasique_, Flux_parietal_base::input_t::Cp, Flux_parietal_base::output_t::d_nuc, Flux_parietal_base::output_t::da_qpi, Flux_parietal_base::output_t::da_qpk, Flux_parietal_base::output_t::dp_qpi, Flux_parietal_base::output_t::dp_qpk, Flux_parietal_base::output_t::dTf_qpi, Flux_parietal_base::output_t::dTf_qpk, dTg_Hibiki_Ishii_Site_density(), dTl_Hibiki_Ishii_Site_density(), dTp_Hibiki_Ishii_Site_density(), Flux_parietal_base::output_t::dTp_qpi, Flux_parietal_base::output_t::dTp_qpk, Flux_parietal_base::output_t::dv_qpi, Flux_parietal_base::output_t::dv_qpk, G_, Milieu_composite::has_saturation(), Hibiki_Ishii_Site_density(), Flux_parietal_base::input_t::lambda, Flux_parietal_base::input_t::Lvap, molar_mass_, Flux_parietal_base::input_t::mu, Flux_parietal_base::input_t::N, n_g1, n_l, Flux_parietal_base::output_t::nonlinear, Flux_parietal_base::input_t::p, Correlation_base::pb_, Flux_parietal_base::output_t::qpi, Flux_parietal_base::output_t::qpk, Qw_, Flux_parietal_base::input_t::rho, Flux_parietal_base::input_t::Sigma, Flux_parietal_base::input_t::T, theta_, Flux_parietal_base::input_t::Tp, Flux_parietal_base::input_t::Tsat, and TRUST_Deriv< _CLASSE_ >::valeur().
completer()
void Flux_parietal_Hibiki::completer () override virtual
Reimplemented from Correlation_base.
References Correlation_base::completer(), and correlation_monophasique_.
calculates_bubble_nucleation_diameter()
int Flux_parietal_Hibiki::calculates_bubble_nucleation_diameter () const inline override virtual
Reimplemented from Flux_parietal_base.
needs_saturation()
int Flux_parietal_Hibiki::needs_saturation () const inline override virtual
Reimplemented from Flux_parietal_base.
T_at_wall()
virtual int Flux_parietal_Hibiki::T_at_wall () const inline override virtual
Implements Flux_parietal_base.
Hibiki_Ishii_Site_density()
double Flux_parietal_Hibiki::Hibiki_Ishii_Site_density (double rho_v, double rho_l, double T_v, double T_l, double p, double Tp, double h_lv, double T_sat, double sigma, double theta, double molar_mass) const protected
Referenced by qp().
dTg_Hibiki_Ishii_Site_density()
double Flux_parietal_Hibiki::dTg_Hibiki_Ishii_Site_density (double rho_v, double rho_l, double T_v, double T_l, double p, double Tp, double h_lv, double T_sat, double sigma, double theta, double molar_mass) const protected
Referenced by qp().
dTl_Hibiki_Ishii_Site_density()
double Flux_parietal_Hibiki::dTl_Hibiki_Ishii_Site_density (double rho_v, double rho_l, double T_v, double T_l, double p, double Tp, double h_lv, double T_sat, double sigma, double theta, double molar_mass) const protected
Referenced by qp().
dTp_Hibiki_Ishii_Site_density()
double Flux_parietal_Hibiki::dTp_Hibiki_Ishii_Site_density (double rho_v, double rho_l, double T_v, double T_l, double p, double Tp, double h_lv, double T_sat, double sigma, double theta, double molar_mass) const protected
Referenced by qp().
Member Data Documentation
info_obj
const Type_info Flux_parietal_Hibiki::info_obj static
correlation_monophasique_
TRUST_Deriv< Correlation_base > Flux_parietal_Hibiki::correlation_monophasique_ protected
Referenced by completer(), qp(), and readOn().
theta_
double Flux_parietal_Hibiki::theta_ = 90. protected
Referenced by qp(), and readOn().
molar_mass_
double Flux_parietal_Hibiki::molar_mass_ protected
Referenced by qp(), and readOn().
Qw_
double Flux_parietal_Hibiki::Qw_ = 0. protected
Referenced by qp(), and readOn().
G_
double Flux_parietal_Hibiki::G_ = 1. protected
Referenced by qp(), and readOn().
n_l
int Flux_parietal_Hibiki::n_l = -1 protected
Referenced by qp(), and readOn().
n_g1
int Flux_parietal_Hibiki::n_g1 = -1 protected
Referenced by qp(), and readOn().
n_g2
int Flux_parietal_Hibiki::n_g2 = -1 protected
Referenced by readOn().