TrioCFD: Transport_turbulent_aire_interfaciale Class Reference
Transport_turbulent_aire_interfaciale Class Reference
#include <Transport_turbulent_aire_interfaciale.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Transport_turbulent_base
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Transport_turbulent_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
< u'_i theta'> = - nu_t / Pr_t d_i theta = - sigma_t nu_t d_i theta (l'utilisateur peut donner sigma_t ou Pr_t)
Constructor & Destructor Documentation
Transport_turbulent_aire_interfaciale()
Transport_turbulent_aire_interfaciale::Transport_turbulent_aire_interfaciale ()
~Transport_turbulent_aire_interfaciale()
Transport_turbulent_aire_interfaciale::~Transport_turbulent_aire_interfaciale ()
Member Function Documentation
cree_instance()
Objet_U * Transport_turbulent_aire_interfaciale::cree_instance () static
taille_memoire()
unsigned Transport_turbulent_aire_interfaciale::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Transport_turbulent_aire_interfaciale::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Transport_turbulent_aire_interfaciale::info () static
get_info()
const Type_info * Transport_turbulent_aire_interfaciale::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Correlation_base.
self_cast() [1/2]
Transport_turbulent_aire_interfaciale & Transport_turbulent_aire_interfaciale::self_cast (Objet_U & r) static
self_cast() [2/2]
const Transport_turbulent_aire_interfaciale & Transport_turbulent_aire_interfaciale::self_cast (const Objet_U & r) static
printOn()
Sortie & Transport_turbulent_aire_interfaciale::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Correlation_base.
readOn()
Entree & Transport_turbulent_aire_interfaciale::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Correlation_base.
References Param::ajouter(), Param::lire_avec_accolades_depuis(), and Objet_U::que_suis_je().
dimension_min_nu()
int Transport_turbulent_aire_interfaciale::dimension_min_nu () const inline override virtual
Implements Transport_turbulent_base.
modifier_mu()
void Transport_turbulent_aire_interfaciale::modifier_mu (const Convection_Diffusion_std & eq, const Viscosite_turbulente_base & visc_turb, DoubleTab & nu) const override virtual
Implements Transport_turbulent_base.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Probleme_base::get_champ(), Probleme_base::has_champ(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Champ_Proto::passe(), and Equation_base::probleme().
Member Data Documentation
info_obj
const Type_info Transport_turbulent_aire_interfaciale::info_obj static