TrioCFD: Force_sp Class Reference
Force_sp Class Reference
#include <Force_sp.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Force_sp()
Force_sp::Force_sp ()
~Force_sp()
Force_sp::~Force_sp ()
Member Function Documentation
cree_instance()
Objet_U * Force_sp::cree_instance () static
taille_memoire()
unsigned Force_sp::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Force_sp::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Force_sp::info () static
get_info()
const Type_info * Force_sp::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
Force_sp & Force_sp::self_cast (Objet_U & r) static
self_cast() [2/2]
const Force_sp & Force_sp::self_cast (const Objet_U & r) static
printOn()
Sortie & Force_sp::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
References Objet_U::printOn().
readOn()
Entree & Force_sp::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
References Objet_U::readOn().
initialise() [1/2]
void Force_sp::initialise (int nl, int nn, int nm, int momin, int momax, double kmin, double kmax, std::string nom_fichier)
References TRUSTArray< _TYPE_, _SIZE_ >::resize_array().
Referenced by init_forcage_THI::compute_initial_chouippe().
initialise() [2/2]
void Force_sp::initialise (int nl, int nn, int nm, int momin, int momax, double kmin, double kmax, double amplitude, std::string nom_fichier)
References TRUSTArray< _TYPE_, _SIZE_ >::resize_array().
compute_step2()
void Force_sp::compute_step2 (ArrOfDouble & process_flt)
References Process::je_suis_maitre().
Referenced by init_forcage_THI::compute_THI_force().
field_advection()
void Force_sp::field_advection (const ArrOfDouble & advection_length, const double dt, const int it)
References Process::je_suis_maitre().
set_zero()
void Force_sp::set_zero ()
References TRUSTArray< _TYPE_, _SIZE_ >::resize().
Referenced by init_forcage_THI::compute_THI_force().
compute_dirac_board()
void Force_sp::compute_dirac_board ()
References Process::je_suis_maitre().
compute_dirac_point_div_nulle()
void Force_sp::compute_dirac_point_div_nulle ()
References Process::je_suis_maitre().
Referenced by init_forcage_THI::compute_THI_force().
compute_dirac_point_uniZ()
void Force_sp::compute_dirac_point_uniZ ()
References Process::je_suis_maitre().
Referenced by init_forcage_THI::compute_THI_force().
compute_dirac_point_uniY()
void Force_sp::compute_dirac_point_uniY ()
References Process::je_suis_maitre().
Referenced by init_forcage_THI::compute_THI_force().
compute_dirac_point_uniX_alongX()
void Force_sp::compute_dirac_point_uniX_alongX ()
References Process::je_suis_maitre(), and Process::me().
Referenced by init_forcage_THI::compute_THI_force().
compute_dirac_point_uniX_alongY()
void Force_sp::compute_dirac_point_uniX_alongY ()
References Process::je_suis_maitre(), and Process::me().
Referenced by init_forcage_THI::compute_THI_force().
compute_dirac_point()
void Force_sp::compute_dirac_point ()
References Process::je_suis_maitre().
compute_door_rope()
void Force_sp::compute_door_rope ()
References Process::je_suis_maitre().
compute_door_cube()
void Force_sp::compute_door_cube ()
References Process::je_suis_maitre().
Referenced by init_forcage_THI::compute_THI_force().
compute_force_kappa()
void Force_sp::compute_force_kappa ()
References Process::je_suis_maitre().
compute_diracs_for_cos_squarred()
void Force_sp::compute_diracs_for_cos_squarred ()
References Process::je_suis_maitre().
Referenced by init_forcage_THI::compute_THI_force().
compute_diracs_for_t_times_cos_squarred()
void Force_sp::compute_diracs_for_t_times_cos_squarred (double time)
References Process::je_suis_maitre().
Referenced by init_forcage_THI::compute_THI_force().
write()
void Force_sp::write (std::string nom_fichier_sortie, double time)
write_separate()
void Force_sp::write_separate (std::string nom_fichier_sortie, double t)
compute_energie()
void Force_sp::compute_energie ()
get_energie()
double Force_sp::get_energie ()
get_force()
double Force_sp::get_force (int cpx, int dir, int ind)
get_coeff()
std::vector< std::vector< std::vector< double > > > Force_sp::get_coeff ()
get_coeff_flt()
ArrOfDouble & Force_sp::get_coeff_flt ()
Referenced by init_forcage_THI::compute_THI_force().
Member Data Documentation
info_obj
const Type_info Force_sp::info_obj static