TrioCFD: Post_Processing_Hydrodynamic_Forces Class Reference
Post_Processing_Hydrodynamic_Forces Class Reference
#include <Post_Processing_Hydrodynamic_Forces.h>
Public Member Functions
const Type_info * get_info () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Member Enumeration Documentation
Method_friction_force_computation
enum class Post_Processing_Hydrodynamic_Forces::Method_friction_force_computation strong
Enumerator
TRILINEAR_LINEAR_COMPLET_TENSOR
TRILINEAR_LINEAR_PROJECTED_TENSOR
Method_pressure_force_computation
enum class Post_Processing_Hydrodynamic_Forces::Method_pressure_force_computation strong
Enumerator
TRILINEAR_LINEAR
Location_stress_tensor
enum class Post_Processing_Hydrodynamic_Forces::Location_stress_tensor strong
Enumerator
FACES_NORMALE_X
ELEMENTS
Constructor & Destructor Documentation
~Post_Processing_Hydrodynamic_Forces()
Post_Processing_Hydrodynamic_Forces::~Post_Processing_Hydrodynamic_Forces ()
Post_Processing_Hydrodynamic_Forces()
Post_Processing_Hydrodynamic_Forces::Post_Processing_Hydrodynamic_Forces ()
Member Function Documentation
cree_instance()
Objet_U * Post_Processing_Hydrodynamic_Forces::cree_instance () static
taille_memoire()
unsigned Post_Processing_Hydrodynamic_Forces::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Post_Processing_Hydrodynamic_Forces_Stokes.
duplique()
int Post_Processing_Hydrodynamic_Forces::duplique () const override virtual
Implements Objet_U.
Reimplemented in Post_Processing_Hydrodynamic_Forces_Stokes.
info()
const Type_info * Post_Processing_Hydrodynamic_Forces::info () static
get_info()
const Type_info * Post_Processing_Hydrodynamic_Forces::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
Reimplemented in Post_Processing_Hydrodynamic_Forces_Stokes.
self_cast() [1/2]
Post_Processing_Hydrodynamic_Forces & Post_Processing_Hydrodynamic_Forces::self_cast (Objet_U & r) static
self_cast() [2/2]
const Post_Processing_Hydrodynamic_Forces & Post_Processing_Hydrodynamic_Forces::self_cast (const Objet_U & r) static
printOn()
Sortie & Post_Processing_Hydrodynamic_Forces::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
Reimplemented in Post_Processing_Hydrodynamic_Forces_Stokes.
References Process::exit().
readOn()
Entree & Post_Processing_Hydrodynamic_Forces::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
Reimplemented in Post_Processing_Hydrodynamic_Forces_Stokes.
References Param::lire_avec_accolades_depuis(), Objet_U::que_suis_je(), and set_param().
set_param()
void Post_Processing_Hydrodynamic_Forces::set_param (Param & p)
References Param::ajouter(), Param::ajouter_flag(), Param::ajouter_non_std(), interpolation_distance_gradU_P1_, interpolation_distance_gradU_P2_, interpolation_distance_pressure_P1_, interpolation_distance_pressure_P2_, interpolation_distance_temperature_P1_, interpolation_distance_temperature_P2_, is_compute_forces_, is_compute_heat_transfer_, is_compute_stokes_theoretical_forces_, is_post_process_friction_force_fa7_, is_post_process_pressure_fa7_, is_post_process_pressure_force_fa7_, is_post_process_stress_tensor_fa7_, and Param::REQUIRED.
Referenced by readOn().
lire_motcle_non_standard()
int Post_Processing_Hydrodynamic_Forces::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Objet_U.
References TRUST_Vector< _CLASSE_ >::add(), ELEMENTS, Process::exit(), FACES_NORMALE_X, location_stress_tensor_, method_friction_force_computation_, method_pressure_force_computation_, Objet_U::que_suis_je(), Motcles::search(), TRILINEAR_LINEAR, TRILINEAR_LINEAR_COMPLET_TENSOR, and TRILINEAR_LINEAR_PROJECTED_TENSOR.
associate_transport_equation()
void Post_Processing_Hydrodynamic_Forces::associate_transport_equation (Transport_Interfaces_FT_Disc & ptr_eq_transport) inline
References ptr_eq_transport_.
Referenced by Transport_Interfaces_FT_Disc::preparer_calcul().
associate_ns_equation()
void Post_Processing_Hydrodynamic_Forces::associate_ns_equation (const Navier_Stokes_FT_Disc & eqn) inline
References ptr_eq_ns_.
Referenced by Transport_Interfaces_FT_Disc::preparer_calcul().
associate_temp_equation()
void Post_Processing_Hydrodynamic_Forces::associate_temp_equation (const Convection_Diffusion_Temperature_FT_Disc & eqn) inline
References ptr_eq_temp_.
Referenced by Transport_Interfaces_FT_Disc::associate_temp_equation_post_processing().
drop_the_flag()
void Post_Processing_Hydrodynamic_Forces::drop_the_flag () inline
References flag_force_computation_.
Referenced by Transport_Interfaces_FT_Disc::mettre_a_jour().
raise_the_flag()
void Post_Processing_Hydrodynamic_Forces::raise_the_flag () inline
References flag_force_computation_.
Referenced by compute_hydrodynamic_forces(), and Post_Processing_Hydrodynamic_Forces_Stokes::compute_hydrodynamic_forces().
drop_the_flag_heat_transfer()
void Post_Processing_Hydrodynamic_Forces::drop_the_flag_heat_transfer () inline
References flag_heat_transfer_computation_.
Referenced by Transport_Interfaces_FT_Disc::mettre_a_jour().
raise_the_flag_heat_transfer()
void Post_Processing_Hydrodynamic_Forces::raise_the_flag_heat_transfer () inline
References flag_heat_transfer_computation_.
Referenced by compute_heat_transfer().
compute_hydrodynamic_forces()
void Post_Processing_Hydrodynamic_Forces::compute_hydrodynamic_forces () virtual
Reimplemented in Post_Processing_Hydrodynamic_Forces_Stokes.
References compute_friction_force_complet_tensor(), compute_friction_force_projected_tensor(), compute_neighbors_coordinates_fluid_fa7(), compute_pressure_force_trilinear_linear(), compute_proportion_fa7_ok_and_is_fluid_P2(), compute_U_P2_moy(), Objet_U::dimension, Convection_Diffusion_Temperature_FT_Disc::ELEM_DIPH, Process::exit(), flag_force_computation_, Maillage_FT_Disc::get_gravity_center_fa7(), Navier_Stokes_FT_Disc::get_particles_eulerian_id_number(), Maillage_FT_Disc::get_update_normale_facettes(), Maillage_FT_Disc::get_update_surface_facettes(), list_elem_diph_, Transport_Interfaces_FT_Disc::maillage_interface_pour_post(), method_friction_force_computation_, Nb_fa7_tot_par_compo_, Maillage_FT_Disc::nb_facettes(), Convection_Diffusion_Temperature_FT_Disc::P1, prop_P2_fluid_compo_, proportion_fa7_ok_UP2_, ptr_eq_ns_, ptr_eq_transport_, raise_the_flag(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), resize_and_init_tables(), resize_coord_neighbor_fluid_fa7(), resize_data_fa7(), total_friction_force_, total_pressure_force_, total_surface_interf_, U_P2_moy_, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Transport_Interfaces_FT_Disc::get_champ_post_FT(), and Transport_Interfaces_FT_Disc::mettre_a_jour().
compute_heat_transfer()
void Post_Processing_Hydrodynamic_Forces::compute_heat_transfer ()
References Domaine_32_64< _SIZE_ >::chercher_elements(), Milieu_base::conductivite(), coord_neighbor_fluid_fa7_temp_1_, coord_neighbor_fluid_fa7_temp_2_, Objet_U::dimension, Domaine_VDF::dist_elem(), Domaine_dis_base::domaine(), Equation_base::domaine_dis(), elem_faces_for_interp(), face_voisins_for_interp(), Maillage_FT_Disc::facette_virtuelle(), flag_heat_transfer_computation_, Navier_Stokes_FT_Disc::fluide_diphasique(), Fluide_Diphasique::fluide_phase(), Maillage_FT_Disc::get_gravity_center_fa7(), Convection_Diffusion_Temperature_FT_Disc::get_tsat_constant(), Maillage_FT_Disc::get_update_normale_facettes(), Maillage_FT_Disc::get_update_surface_facettes(), heat_transfer_fa7_, Convection_Diffusion_Temperature::inconnue(), interpolation_distance_temperature_P1_, interpolation_distance_temperature_P2_, Transport_Interfaces_FT_Disc::maillage_interface(), Maillage_FT_Disc::nb_facettes(), ptr_eq_ns_, ptr_eq_temp_, ptr_eq_transport_, raise_the_flag_heat_transfer(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), total_heat_transfer_, trilinear_interpolation_elem(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), and Champ_Inc_base::valeurs().
Referenced by Transport_Interfaces_FT_Disc::get_champ_post_FT(), and Transport_Interfaces_FT_Disc::mettre_a_jour().
get_pressure_fa7()
const DoubleVect & Post_Processing_Hydrodynamic_Forces::get_pressure_fa7 () const inline
References pressure_fa7_.
Referenced by Transport_Interfaces_FT_Disc::fill_ftab_pressure(), and Transport_Interfaces_FT_Disc::fill_ftab_Stokes_pressure_interp().
get_total_surface_interf()
const DoubleVect & Post_Processing_Hydrodynamic_Forces::get_total_surface_interf () const inline
References total_surface_interf_.
Referenced by Transport_Interfaces_FT_Disc::impr().
get_heat_transfer()
const DoubleVect & Post_Processing_Hydrodynamic_Forces::get_heat_transfer () const inline
References total_heat_transfer_.
Referenced by Transport_Interfaces_FT_Disc::impr().
get_pressure_force()
const DoubleTab & Post_Processing_Hydrodynamic_Forces::get_pressure_force () const inline
References total_pressure_force_.
Referenced by Transport_Interfaces_FT_Disc::impr().
get_friction_force()
const DoubleTab & Post_Processing_Hydrodynamic_Forces::get_friction_force () const inline
References total_friction_force_.
Referenced by Transport_Interfaces_FT_Disc::impr().
get_pressure_force_fa7()
const DoubleTab & Post_Processing_Hydrodynamic_Forces::get_pressure_force_fa7 () const inline
References pressure_force_fa7_.
Referenced by Transport_Interfaces_FT_Disc::fill_ftab_pressure_force().
get_friction_force_fa7()
const DoubleTab & Post_Processing_Hydrodynamic_Forces::get_friction_force_fa7 () const inline
References friction_force_fa7_.
Referenced by Transport_Interfaces_FT_Disc::fill_ftab_friction_force().
get_heat_transfer_fa7()
const DoubleTab & Post_Processing_Hydrodynamic_Forces::get_heat_transfer_fa7 () const inline
References heat_transfer_fa7_.
get_U_P1()
const DoubleTab & Post_Processing_Hydrodynamic_Forces::get_U_P1 () const inline
References U_P1_.
get_U_P2()
const DoubleTab & Post_Processing_Hydrodynamic_Forces::get_U_P2 () const inline
References U_P2_.
get_U_P2_moy()
const DoubleTab & Post_Processing_Hydrodynamic_Forces::get_U_P2_moy () const inline
References U_P2_moy_.
Referenced by Transport_Interfaces_FT_Disc::impr().
get_prop_fa7_ok_P2()
const DoubleTab & Post_Processing_Hydrodynamic_Forces::get_prop_fa7_ok_P2 () const inline
References proportion_fa7_ok_UP2_.
Referenced by Transport_Interfaces_FT_Disc::impr().
get_prop_P2_fluid()
const DoubleTab & Post_Processing_Hydrodynamic_Forces::get_prop_P2_fluid () const inline
References prop_P2_fluid_compo_.
Referenced by Transport_Interfaces_FT_Disc::impr().
get_sigma_xx_fa7()
const DoubleTab & Post_Processing_Hydrodynamic_Forces::get_sigma_xx_fa7 () const inline
References sigma_xx_fa7_.
get_sigma_xy_fa7()
const DoubleTab & Post_Processing_Hydrodynamic_Forces::get_sigma_xy_fa7 () const inline
References sigma_xy_fa7_.
get_sigma_xz_fa7()
const DoubleTab & Post_Processing_Hydrodynamic_Forces::get_sigma_xz_fa7 () const inline
References sigma_xz_fa7_.
get_sigma_yx_fa7()
const DoubleTab & Post_Processing_Hydrodynamic_Forces::get_sigma_yx_fa7 () const inline
References sigma_yx_fa7_.
get_sigma_yy_fa7()
const DoubleTab & Post_Processing_Hydrodynamic_Forces::get_sigma_yy_fa7 () const inline
References sigma_yy_fa7_.
get_sigma_yz_fa7()
const DoubleTab & Post_Processing_Hydrodynamic_Forces::get_sigma_yz_fa7 () const inline
References sigma_yz_fa7_.
get_sigma_zx_fa7()
const DoubleTab & Post_Processing_Hydrodynamic_Forces::get_sigma_zx_fa7 () const inline
References sigma_zx_fa7_.
get_sigma_zy_fa7()
const DoubleTab & Post_Processing_Hydrodynamic_Forces::get_sigma_zy_fa7 () const inline
References sigma_zy_fa7_.
get_sigma_zz_fa7()
const DoubleTab & Post_Processing_Hydrodynamic_Forces::get_sigma_zz_fa7 () const inline
References sigma_zz_fa7_.
get_dUdx_P1()
const DoubleTab & Post_Processing_Hydrodynamic_Forces::get_dUdx_P1 () inline
References dUdx_P1_.
get_dUdy_P1()
const DoubleTab & Post_Processing_Hydrodynamic_Forces::get_dUdy_P1 () inline
References dUdy_P1_.
get_dUdz_P1()
const DoubleTab & Post_Processing_Hydrodynamic_Forces::get_dUdz_P1 () inline
References dUdz_P1_.
get_dVdx_P1()
const DoubleTab & Post_Processing_Hydrodynamic_Forces::get_dVdx_P1 () inline
References dVdx_P1_.
get_dVdy_P1()
const DoubleTab & Post_Processing_Hydrodynamic_Forces::get_dVdy_P1 () inline
References dVdy_P1_.
get_dVdz_P1()
const DoubleTab & Post_Processing_Hydrodynamic_Forces::get_dVdz_P1 () inline
References dVdz_P1_.
get_dWdx_P1()
const DoubleTab & Post_Processing_Hydrodynamic_Forces::get_dWdx_P1 () inline
References dWdx_P1_.
get_dWdy_P1()
const DoubleTab & Post_Processing_Hydrodynamic_Forces::get_dWdy_P1 () inline
References dWdy_P1_.
get_dWdz_P1()
const DoubleTab & Post_Processing_Hydrodynamic_Forces::get_dWdz_P1 () inline
References dWdz_P1_.
get_dUdx_P2()
const DoubleTab & Post_Processing_Hydrodynamic_Forces::get_dUdx_P2 () inline
References dUdx_P2_.
get_dUdy_P2()
const DoubleTab & Post_Processing_Hydrodynamic_Forces::get_dUdy_P2 () inline
References dUdy_P2_.
get_dUdz_P2()
const DoubleTab & Post_Processing_Hydrodynamic_Forces::get_dUdz_P2 () inline
References dUdz_P2_.
get_dVdx_P2()
const DoubleTab & Post_Processing_Hydrodynamic_Forces::get_dVdx_P2 () inline
References dVdx_P2_.
get_dVdy_P2()
const DoubleTab & Post_Processing_Hydrodynamic_Forces::get_dVdy_P2 () inline
References dVdy_P2_.
get_dVdz_P2()
const DoubleTab & Post_Processing_Hydrodynamic_Forces::get_dVdz_P2 () inline
References dVdz_P2_.
get_dWdx_P2()
const DoubleTab & Post_Processing_Hydrodynamic_Forces::get_dWdx_P2 () inline
References dWdx_P2_.
get_dWdy_P2()
const DoubleTab & Post_Processing_Hydrodynamic_Forces::get_dWdy_P2 () inline
References dWdy_P2_.
get_dWdz_P2()
const DoubleTab & Post_Processing_Hydrodynamic_Forces::get_dWdz_P2 () inline
References dWdz_P2_.
get_is_compute_forces()
int Post_Processing_Hydrodynamic_Forces::get_is_compute_forces () const inline
References is_compute_forces_.
Referenced by Transport_Interfaces_FT_Disc::get_champ_post_FT(), Transport_Interfaces_FT_Disc::impr(), Transport_Interfaces_FT_Disc::mettre_a_jour(), and Post_Processing_Hydrodynamic_Forces_Stokes::set_param().
get_is_compute_forces_Stokes_th()
int Post_Processing_Hydrodynamic_Forces::get_is_compute_forces_Stokes_th () const inline
References is_compute_stokes_theoretical_forces_.
Referenced by Transport_Interfaces_FT_Disc::fill_ftab_Stokes(), Transport_Interfaces_FT_Disc::fill_ftab_Stokes_pressure_interp(), Transport_Interfaces_FT_Disc::fill_ftab_Stokes_pressure_th(), Transport_Interfaces_FT_Disc::get_champ_post_FT(), Transport_Interfaces_FT_Disc::impr(), Transport_Interfaces_FT_Disc::mettre_a_jour(), Navier_Stokes_FT_Disc::preparer_calcul(), and Post_Processing_Hydrodynamic_Forces_Stokes::set_param().
get_is_compute_heat_transfer()
int Post_Processing_Hydrodynamic_Forces::get_is_compute_heat_transfer () const inline
References is_compute_heat_transfer_.
Referenced by Transport_Interfaces_FT_Disc::get_champ_post_FT(), Transport_Interfaces_FT_Disc::impr(), and Transport_Interfaces_FT_Disc::mettre_a_jour().
get_is_post_process_pressure_force_fa7()
int Post_Processing_Hydrodynamic_Forces::get_is_post_process_pressure_force_fa7 () const inline
References is_post_process_pressure_force_fa7_.
Referenced by Transport_Interfaces_FT_Disc::fill_ftab_pressure_force(), and Post_Processing_Hydrodynamic_Forces_Stokes::set_param().
get_is_post_process_friction_force_fa7()
int Post_Processing_Hydrodynamic_Forces::get_is_post_process_friction_force_fa7 () const inline
References is_post_process_friction_force_fa7_.
Referenced by Transport_Interfaces_FT_Disc::fill_ftab_friction_force(), and Post_Processing_Hydrodynamic_Forces_Stokes::set_param().
get_is_post_process_stress_tensor_fa7()
int Post_Processing_Hydrodynamic_Forces::get_is_post_process_stress_tensor_fa7 () const inline
References is_post_process_stress_tensor_fa7_.
Referenced by Post_Processing_Hydrodynamic_Forces_Stokes::set_param().
get_is_post_process_pressure_fa7()
int Post_Processing_Hydrodynamic_Forces::get_is_post_process_pressure_fa7 () const inline
References is_post_process_pressure_fa7_.
Referenced by Transport_Interfaces_FT_Disc::fill_ftab_pressure(), and Post_Processing_Hydrodynamic_Forces_Stokes::set_param().
get_interpolation_distance_pressure_P1()
const double & Post_Processing_Hydrodynamic_Forces::get_interpolation_distance_pressure_P1 () const inline
References interpolation_distance_pressure_P1_.
Referenced by Post_Processing_Hydrodynamic_Forces_Stokes::set_param().
get_interpolation_distance_pressure_P2()
const double & Post_Processing_Hydrodynamic_Forces::get_interpolation_distance_pressure_P2 () const inline
References interpolation_distance_pressure_P2_.
Referenced by Post_Processing_Hydrodynamic_Forces_Stokes::set_param().
get_interpolation_distance_gradU_P1()
const double & Post_Processing_Hydrodynamic_Forces::get_interpolation_distance_gradU_P1 () const inline
References interpolation_distance_gradU_P1_.
Referenced by Post_Processing_Hydrodynamic_Forces_Stokes::set_param().
get_interpolation_distance_gradU_P2()
const double & Post_Processing_Hydrodynamic_Forces::get_interpolation_distance_gradU_P2 () const inline
References interpolation_distance_gradU_P2_.
Referenced by Post_Processing_Hydrodynamic_Forces_Stokes::set_param().
resize_and_init_tables()
void Post_Processing_Hydrodynamic_Forces::resize_and_init_tables (int nb_compo_tot) virtual
Reimplemented in Post_Processing_Hydrodynamic_Forces_Stokes.
References Objet_U::dimension, Nb_fa7_tot_par_compo_, prop_P2_fluid_compo_, proportion_fa7_ok_UP2_, TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), total_friction_force_, total_heat_transfer_, total_pressure_force_, total_surface_interf_, and U_P2_moy_.
Referenced by compute_hydrodynamic_forces(), and Transport_Interfaces_FT_Disc::preparer_calcul().
get_method_pressure_force_computation()
const Method_pressure_force_computation & Post_Processing_Hydrodynamic_Forces::get_method_pressure_force_computation () const inline
References method_pressure_force_computation_.
Referenced by Post_Processing_Hydrodynamic_Forces_Stokes::set_param().
get_method_friction_force_computation()
const Method_friction_force_computation & Post_Processing_Hydrodynamic_Forces::get_method_friction_force_computation () const inline
References method_friction_force_computation_.
get_location_stress_tensor()
const Location_stress_tensor & Post_Processing_Hydrodynamic_Forces::get_location_stress_tensor () const inline
References location_stress_tensor_.
Referenced by Post_Processing_Hydrodynamic_Forces_Stokes::set_param().
elem_faces_for_interp()
int Post_Processing_Hydrodynamic_Forces::elem_faces_for_interp (int num_face, int i) const protected
References Domaine_VF::elem_faces(), Process::Journal(), ptr_eq_ns_, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by compute_friction_force_projected_tensor(), compute_heat_transfer(), compute_neighbors_coordinates_fluid_fa7(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_neighbors_coordinates_fluid_fa7(), find_neighboring_elements(), find_neighboring_faces(), trilinear_interpolation_gradU_elem(), trilinear_interpolation_gradU_elem_P1(), and trilinear_interpolation_gradU_face().
face_voisins_for_interp()
int Post_Processing_Hydrodynamic_Forces::face_voisins_for_interp (int num_face, int i) const protected
References Domaine_VF::face_voisins(), Process::Journal(), ptr_eq_ns_, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by compute_friction_force_projected_tensor(), compute_heat_transfer(), compute_neighbors_coordinates_fluid_fa7(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_neighbors_coordinates_fluid_fa7(), compute_viscosity_edges_sphere(), find_neighboring_elements(), find_neighboring_faces(), trilinear_interpolation_gradU_elem(), trilinear_interpolation_gradU_elem_P1(), and trilinear_interpolation_gradU_face().
trilinear_interpolation_face()
int Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_face (const DoubleTab & valeurs_champ, DoubleTab & coord, DoubleTab & resu) protected
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Domaine_VDF::dist_face(), Equation_base::domaine_dis(), Maillage_FT_Disc::facette_virtuelle(), find_neighboring_faces_xyz(), Transport_Interfaces_FT_Disc::maillage_interface(), ptr_eq_ns_, ptr_eq_transport_, TRUST_Ref< _CLASSE_ >::valeur(), and Domaine_VF::xv().
Referenced by compute_friction_force_projected_tensor(), and Post_Processing_Hydrodynamic_Forces_Stokes::compute_friction_force_projected_tensor().
trilinear_interpolation_elem() [1/2]
int Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_elem (const DoubleTab & valeurs_champ, DoubleTab & coord, DoubleTab & resu) protected
References Convection_Diffusion_Temperature_FT_Disc::P1, and trilinear_interpolation_elem().
Referenced by compute_heat_transfer(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_pressure_force_trilinear_linear(), compute_pressure_force_trilinear_linear(), and trilinear_interpolation_elem().
trilinear_interpolation_elem() [2/2]
int Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_elem (const DoubleTab & valeurs_champ, DoubleTab & coord, DoubleTab & resu, const int is_P2, const Convection_Diffusion_Temperature_FT_Disc::Thermal_correction_discretization_method discr) protected
Interpolation trilineaire d'un champs "valeurs_champs" aux coordonnees coord a partir des 8 elements (4 en 2D) voisins les plus proches. Valeurs_chaamps contient typiquement le champ de presssion ou le champ de temperature. On utilise egalement cette fonction pour sauvegarder la liste des elments P1 ainsi que l'indiatrice des elements P2.
References TRUSTTab< _TYPE_, _SIZE_ >::append_line(), Domaine_32_64< _SIZE_ >::chercher_elements(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Domaine_VDF::dist_elem(), Domaine_dis_base::domaine(), Maillage_FT_Disc::facette_virtuelle(), find_neighboring_elements(), Maillage_FT_Disc::get_gravity_center_fa7(), Navier_Stokes_FT_Disc::get_particles_eulerian_id_number(), Transport_Interfaces_FT_Disc::get_update_indicatrice(), list_elem_P1_, list_elem_P1_all_, Transport_Interfaces_FT_Disc::maillage_interface(), Convection_Diffusion_Temperature_FT_Disc::P1, Convection_Diffusion_Temperature_FT_Disc::P1_ALL, phase_indicator_function_P2_, ptr_eq_ns_, ptr_eq_transport_, TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_Proto::valeurs(), and Domaine_VF::xp().
trilinear_interpolation_gradU_face()
int Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_gradU_face (const DoubleTab & valeurs_champ, DoubleTab & coord, DoubleTab & resu) protected
References Domaine_32_64< _SIZE_ >::chercher_elements(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Domaine_VDF::dist_face(), Domaine_dis_base::domaine(), Equation_base::domaine_dis(), elem_faces_for_interp(), face_voisins_for_interp(), Maillage_FT_Disc::facette_virtuelle(), find_neighboring_faces(), Transport_Interfaces_FT_Disc::maillage_interface(), ptr_eq_ns_, ptr_eq_transport_, TRUST_Ref< _CLASSE_ >::valeur(), and Domaine_VF::xv().
Referenced by compute_friction_force_complet_tensor(), and Post_Processing_Hydrodynamic_Forces_Stokes::compute_friction_force_complet_tensor().
trilinear_interpolation_gradU_elem_P1()
int Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_gradU_elem_P1 (const DoubleTab & valeurs_champ, DoubleTab & coord, DoubleTab & resu) protected
References compute_viscosity_edges_sphere(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Domaine_VDF::dist_elem(), Equation_base::domaine_dis(), elem_faces_for_interp(), face_voisins_for_interp(), Maillage_FT_Disc::facette_virtuelle(), find_neighboring_elements(), Navier_Stokes_FT_Disc::fluide_diphasique(), Fluide_Diphasique::fluide_phase(), Fluide_Diphasique::get_id_fluid_phase(), Navier_Stokes_FT_Disc::get_particles_eulerian_id_number(), Transport_Interfaces_FT_Disc::get_update_indicatrice(), Transport_Interfaces_FT_Disc::maillage_interface(), ptr_eq_ns_, ptr_eq_transport_, TRUST_Ref< _CLASSE_ >::valeur(), Champ_Proto::valeurs(), Domaine_VF::xp(), and Domaine_VF::xv().
trilinear_interpolation_gradU_elem()
int Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_gradU_elem (const DoubleTab & valeurs_champ, DoubleTab & coord, DoubleTab & resu) protected
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Domaine_VDF::dist_elem(), Equation_base::domaine_dis(), elem_faces_for_interp(), face_voisins_for_interp(), Maillage_FT_Disc::facette_virtuelle(), find_neighboring_elements(), Navier_Stokes_FT_Disc::fluide_diphasique(), Fluide_Diphasique::fluide_phase(), Fluide_Diphasique::get_id_fluid_phase(), Transport_Interfaces_FT_Disc::maillage_interface(), ptr_eq_ns_, ptr_eq_transport_, TRUST_Ref< _CLASSE_ >::valeur(), Domaine_VF::xp(), and Domaine_VF::xv().
Referenced by compute_friction_force_complet_tensor(), and Post_Processing_Hydrodynamic_Forces_Stokes::compute_friction_force_complet_tensor().
trilinear_interpolation_face_sommets()
int Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_face_sommets (const DoubleTab & valeurs_champ, DoubleTab & coord, DoubleTab & resu) protected
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Domaine_VDF::dist_face(), Equation_base::domaine_dis(), find_neighboring_faces_xyz(), Transport_Interfaces_FT_Disc::maillage_interface(), ptr_eq_ns_, ptr_eq_transport_, Maillage_FT_Disc::sommet_elem(), Maillage_FT_Disc::sommets(), TRUST_Ref< _CLASSE_ >::valeur(), and Domaine_VF::xv().
compute_viscosity_edges_sphere()
double Post_Processing_Hydrodynamic_Forces::compute_viscosity_edges_sphere (int face1, int face2, int particle_id) protected
References Equation_base::domaine_dis(), face_voisins_for_interp(), Navier_Stokes_FT_Disc::fluide_diphasique(), Fluide_Diphasique::fluide_phase(), Solid_Particle_base::get_equivalent_radius(), Fluide_Diphasique::get_id_fluid_phase(), Transport_Interfaces_FT_Disc::get_particles_position(), ptr_eq_ns_, ptr_eq_transport_, TRUST_Ref< _CLASSE_ >::valeur(), and Domaine_VF::xp().
Referenced by trilinear_interpolation_gradU_elem_P1().
find_neighboring_elements()
double Post_Processing_Hydrodynamic_Forces::find_neighboring_elements (DoubleVect & coord_elem_interp, IntVect & neighboring_elements, const int sauv_list_P1 = 0, const int num_fa7 = -1) protected
References Domaine_32_64< _SIZE_ >::chercher_elements(), Objet_U::dimension, Domaine_dis_base::domaine(), Equation_base::domaine_dis(), elem_faces_for_interp(), face_voisins_for_interp(), Transport_Interfaces_FT_Disc::get_update_indicatrice(), list_elem_P1_, ptr_eq_ns_, ptr_eq_transport_, TRUST_Ref< _CLASSE_ >::valeur(), Champ_Proto::valeurs(), and Domaine_VF::xp().
Referenced by trilinear_interpolation_elem(), trilinear_interpolation_gradU_elem(), and trilinear_interpolation_gradU_elem_P1().
find_neighboring_faces()
void Post_Processing_Hydrodynamic_Forces::find_neighboring_faces (DoubleVect & coord_elem_interp, IntVect & neighboring_faces, int orientation) const protected
References Domaine_32_64< _SIZE_ >::chercher_elements(), Objet_U::dimension, Domaine_dis_base::domaine(), Equation_base::domaine_dis(), elem_faces_for_interp(), face_voisins_for_interp(), ptr_eq_ns_, TRUST_Ref< _CLASSE_ >::valeur(), and Domaine_VF::xp().
Referenced by find_neighboring_faces_xyz(), and trilinear_interpolation_gradU_face().
find_neighboring_faces_xyz()
void Post_Processing_Hydrodynamic_Forces::find_neighboring_faces_xyz (DoubleVect & coord_elem_interp, IntTab & neighboring_faces) const protected
References find_neighboring_faces().
Referenced by trilinear_interpolation_face(), and trilinear_interpolation_face_sommets().
resize_sigma()
void Post_Processing_Hydrodynamic_Forces::resize_sigma (int nb_fa7) protected virtual
Reimplemented in Post_Processing_Hydrodynamic_Forces_Stokes.
References TRUSTTab< _TYPE_, _SIZE_ >::resize(), sigma_xx_fa7_, sigma_xy_fa7_, sigma_xz_fa7_, sigma_yx_fa7_, sigma_yy_fa7_, sigma_yz_fa7_, sigma_zx_fa7_, sigma_zy_fa7_, and sigma_zz_fa7_.
Referenced by resize_data_fa7().
resize_gradU_P1()
void Post_Processing_Hydrodynamic_Forces::resize_gradU_P1 (int nb_fa7) protected virtual
Reimplemented in Post_Processing_Hydrodynamic_Forces_Stokes.
References dUdx_P1_, dUdy_P1_, dUdz_P1_, dVdx_P1_, dVdy_P1_, dVdz_P1_, dWdx_P1_, dWdy_P1_, dWdz_P1_, and TRUSTTab< _TYPE_, _SIZE_ >::resize().
Referenced by resize_data_fa7().
resize_gradU_P2()
void Post_Processing_Hydrodynamic_Forces::resize_gradU_P2 (int nb_fa7) protected virtual
Reimplemented in Post_Processing_Hydrodynamic_Forces_Stokes.
References dUdx_P2_, dUdy_P2_, dUdz_P2_, dVdx_P2_, dVdy_P2_, dVdz_P2_, dWdx_P2_, dWdy_P2_, dWdz_P2_, and TRUSTTab< _TYPE_, _SIZE_ >::resize().
Referenced by resize_data_fa7().
resize_data_fa7()
void Post_Processing_Hydrodynamic_Forces::resize_data_fa7 (int nb_fa7) protected virtual
Reimplemented in Post_Processing_Hydrodynamic_Forces_Stokes.
References Objet_U::dimension, friction_force_fa7_, is_post_process_friction_force_fa7_, is_post_process_pressure_fa7_, is_post_process_pressure_force_fa7_, is_post_process_stress_tensor_fa7_, phase_indicator_function_P2_, pressure_fa7_, pressure_force_fa7_, TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), resize_gradU_P1(), resize_gradU_P2(), resize_sigma(), U_P1_, and U_P2_.
Referenced by compute_hydrodynamic_forces().
resize_coord_neighbor_fluid_fa7()
void Post_Processing_Hydrodynamic_Forces::resize_coord_neighbor_fluid_fa7 (int nb_fa7) protected
References coord_neighbor_fluid_fa7_gradU_1_, coord_neighbor_fluid_fa7_gradU_2_, coord_neighbor_fluid_fa7_pressure_1_, coord_neighbor_fluid_fa7_pressure_2_, Objet_U::dimension, and TRUSTTab< _TYPE_, _SIZE_ >::resize().
Referenced by compute_hydrodynamic_forces(), and Post_Processing_Hydrodynamic_Forces_Stokes::compute_hydrodynamic_forces().
fill_absurd_value_coord_neighbor_fluid_fa7()
void Post_Processing_Hydrodynamic_Forces::fill_absurd_value_coord_neighbor_fluid_fa7 (int fa7) protected
References coord_neighbor_fluid_fa7_gradU_1_, coord_neighbor_fluid_fa7_gradU_2_, coord_neighbor_fluid_fa7_pressure_1_, coord_neighbor_fluid_fa7_pressure_2_, and Objet_U::dimension.
Referenced by compute_neighbors_coordinates_fluid_fa7().
fill_sigma()
void Post_Processing_Hydrodynamic_Forces::fill_sigma (int fa7, Matrice_Dense stress_tensor) protected
References sigma_xx_fa7_, sigma_xy_fa7_, sigma_xz_fa7_, sigma_yx_fa7_, sigma_yy_fa7_, sigma_yz_fa7_, sigma_zx_fa7_, sigma_zy_fa7_, and sigma_zz_fa7_.
Referenced by compute_friction_force_complet_tensor(), and Post_Processing_Hydrodynamic_Forces_Stokes::compute_friction_force_complet_tensor().
fill_gradU_P1()
void Post_Processing_Hydrodynamic_Forces::fill_gradU_P1 (int fa7, DoubleTab gradU_P1) protected
References dUdx_P1_, dUdy_P1_, dUdz_P1_, dVdx_P1_, dVdy_P1_, dVdz_P1_, dWdx_P1_, dWdy_P1_, and dWdz_P1_.
Referenced by compute_friction_force_complet_tensor(), and Post_Processing_Hydrodynamic_Forces_Stokes::compute_friction_force_complet_tensor().
fill_gradU_P2()
void Post_Processing_Hydrodynamic_Forces::fill_gradU_P2 (int fa7, DoubleTab gradU_P2) protected
References dUdx_P2_, dUdy_P2_, dUdz_P2_, dVdx_P2_, dVdy_P2_, dVdz_P2_, dWdx_P2_, dWdy_P2_, and dWdz_P2_.
Referenced by compute_friction_force_complet_tensor(), and Post_Processing_Hydrodynamic_Forces_Stokes::compute_friction_force_complet_tensor().
compute_pressure_force_trilinear_linear()
void Post_Processing_Hydrodynamic_Forces::compute_pressure_force_trilinear_linear (int nb_fa7, const Maillage_FT_Disc & mesh, Convection_Diffusion_Temperature_FT_Disc::Thermal_correction_discretization_method thermal_correction_discretization_method, const IntVect & compo_connexes_fa7, const ArrOfDouble & fa7_surface, const DoubleTab & tab_fa7_normal) protected virtual
Reimplemented in Post_Processing_Hydrodynamic_Forces_Stokes.
References coord_neighbor_fluid_fa7_pressure_1_, coord_neighbor_fluid_fa7_pressure_2_, Objet_U::dimension, Maillage_FT_Disc::facette_virtuelle(), interpolation_distance_pressure_P1_, interpolation_distance_pressure_P2_, is_post_process_pressure_fa7_, is_post_process_pressure_force_fa7_, Navier_Stokes_std::la_pression, phase_indicator_function_P2_, pressure_fa7_, pressure_force_fa7_, prop_P2_fluid_compo_, ptr_eq_ns_, total_pressure_force_, total_surface_interf_, trilinear_interpolation_elem(), TRUST_Ref< _CLASSE_ >::valeur(), and Champ_Inc_base::valeurs().
Referenced by compute_hydrodynamic_forces().
compute_friction_force_complet_tensor()
void Post_Processing_Hydrodynamic_Forces::compute_friction_force_complet_tensor (int nb_fa7, const Maillage_FT_Disc & mesh, const IntVect & compo_connexes_fa7, const ArrOfDouble & fa7_surface, const DoubleTab & tab_fa7_normal) protected virtual
Reimplemented in Post_Processing_Hydrodynamic_Forces_Stokes.
References coord_neighbor_fluid_fa7_gradU_1_, coord_neighbor_fluid_fa7_gradU_2_, Objet_U::dimension, ELEMENTS, FACES_NORMALE_X, Maillage_FT_Disc::facette_virtuelle(), fill_gradU_P1(), fill_gradU_P2(), fill_sigma(), friction_force_fa7_, interpolation_distance_gradU_P1_, interpolation_distance_gradU_P2_, is_post_process_friction_force_fa7_, is_post_process_stress_tensor_fa7_, Navier_Stokes_std::la_vitesse, location_stress_tensor_, ptr_eq_ns_, total_friction_force_, trilinear_interpolation_gradU_elem(), trilinear_interpolation_gradU_face(), TRUST_Ref< _CLASSE_ >::valeur(), and Champ_Inc_base::valeurs().
Referenced by compute_hydrodynamic_forces().
compute_friction_force_projected_tensor()
void Post_Processing_Hydrodynamic_Forces::compute_friction_force_projected_tensor (int nb_fa7, const Maillage_FT_Disc & mesh, const IntVect & compo_connexes_fa7, const ArrOfDouble & fa7_surface, const DoubleTab & tab_fa7_normal) protected virtual
Reimplemented in Post_Processing_Hydrodynamic_Forces_Stokes.
References Domaine_32_64< _SIZE_ >::chercher_elements(), coord_neighbor_fluid_fa7_gradU_1_, coord_neighbor_fluid_fa7_gradU_2_, Objet_U::dimension, Domaine_VDF::dist_elem(), Domaine_dis_base::domaine(), Equation_base::domaine_dis(), elem_faces_for_interp(), ELEMENTS, face_voisins_for_interp(), Maillage_FT_Disc::facette_virtuelle(), Navier_Stokes_FT_Disc::fluide_diphasique(), Fluide_Diphasique::fluide_phase(), friction_force_fa7_, Maillage_FT_Disc::get_gravity_center_fa7(), Fluide_Diphasique::get_id_fluid_phase(), Transport_Interfaces_FT_Disc::get_particles_position(), Transport_Interfaces_FT_Disc::get_particles_velocity(), is_post_process_friction_force_fa7_, Navier_Stokes_std::la_vitesse, location_stress_tensor_, Nb_fa7_tot_par_compo_, proportion_fa7_ok_UP2_, ptr_eq_ns_, ptr_eq_transport_, TRUSTTab< _TYPE_, _SIZE_ >::resize(), total_friction_force_, trilinear_interpolation_face(), U_P1_, U_P2_, U_P2_moy_, TRUST_Ref< _CLASSE_ >::valeur(), and Champ_Inc_base::valeurs().
Referenced by compute_hydrodynamic_forces().
compute_neighbors_coordinates_fluid_fa7()
void Post_Processing_Hydrodynamic_Forces::compute_neighbors_coordinates_fluid_fa7 (const int nb_fa7, const int is_discr_elem_diph, const DoubleTab & gravity_center_fa7, const Maillage_FT_Disc & mesh, const DoubleTab & tab_fa7_normal, const IntTab & particles_eulerian_id_number) protected virtual
Reimplemented in Post_Processing_Hydrodynamic_Forces_Stokes.
References Domaine_32_64< _SIZE_ >::chercher_elements(), coord_neighbor_fluid_fa7_gradU_1_, coord_neighbor_fluid_fa7_gradU_2_, coord_neighbor_fluid_fa7_pressure_1_, coord_neighbor_fluid_fa7_pressure_2_, Objet_U::dimension, Domaine_VDF::dist_elem(), Domaine_dis_base::domaine(), Equation_base::domaine_dis(), elem_faces_for_interp(), face_voisins_for_interp(), Maillage_FT_Disc::facette_virtuelle(), fill_absurd_value_coord_neighbor_fluid_fa7(), interpolation_distance_pressure_P1_, interpolation_distance_pressure_P2_, list_elem_diph_, ptr_eq_ns_, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by compute_hydrodynamic_forces().
compute_U_P2_moy()
void Post_Processing_Hydrodynamic_Forces::compute_U_P2_moy (const int nb_particles_tot) protected
References Objet_U::dimension, proportion_fa7_ok_UP2_, and U_P2_moy_.
Referenced by compute_hydrodynamic_forces().
compute_proportion_fa7_ok_and_is_fluid_P2()
void Post_Processing_Hydrodynamic_Forces::compute_proportion_fa7_ok_and_is_fluid_P2 (const int nb_particles_tot) protected
References Objet_U::dimension, Nb_fa7_tot_par_compo_, prop_P2_fluid_compo_, and proportion_fa7_ok_UP2_.
Referenced by compute_hydrodynamic_forces().
Member Data Documentation
info_obj
const Type_info Post_Processing_Hydrodynamic_Forces::info_obj static
ptr_eq_transport_
TRUST_Ref< Transport_Interfaces_FT_Disc *> Post_Processing_Hydrodynamic_Forces::ptr_eq_transport_ protected
Referenced by associate_transport_equation(), compute_friction_force_projected_tensor(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_friction_force_projected_tensor(), compute_heat_transfer(), compute_hydrodynamic_forces(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_hydrodynamic_forces(), compute_viscosity_edges_sphere(), Post_Processing_Hydrodynamic_Forces_Stokes::fill_sigma_Stokes_th(), find_neighboring_elements(), trilinear_interpolation_elem(), trilinear_interpolation_face(), trilinear_interpolation_face_sommets(), trilinear_interpolation_gradU_elem(), trilinear_interpolation_gradU_elem_P1(), and trilinear_interpolation_gradU_face().
ptr_eq_ns_
TRUST_Ref< Navier_Stokes_FT_Disc *> Post_Processing_Hydrodynamic_Forces::ptr_eq_ns_ protected
Referenced by associate_ns_equation(), compute_friction_force_complet_tensor(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_friction_force_complet_tensor(), compute_friction_force_projected_tensor(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_friction_force_projected_tensor(), compute_heat_transfer(), compute_hydrodynamic_forces(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_hydrodynamic_forces(), compute_neighbors_coordinates_fluid_fa7(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_neighbors_coordinates_fluid_fa7(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_pressure_force_trilinear_linear(), compute_pressure_force_trilinear_linear(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_pressure_interf(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_vinf_Stokes(), compute_viscosity_edges_sphere(), elem_faces_for_interp(), face_voisins_for_interp(), Post_Processing_Hydrodynamic_Forces_Stokes::fill_sigma_Stokes_th(), Post_Processing_Hydrodynamic_Forces_Stokes::fill_Stokes_pressure_field(), Post_Processing_Hydrodynamic_Forces_Stokes::fill_Stokes_velocity_field(), find_neighboring_elements(), find_neighboring_faces(), trilinear_interpolation_elem(), trilinear_interpolation_face(), trilinear_interpolation_face_sommets(), trilinear_interpolation_gradU_elem(), trilinear_interpolation_gradU_elem_P1(), and trilinear_interpolation_gradU_face().
ptr_eq_temp_
TRUST_Ref< Convection_Diffusion_Temperature_FT_Disc *> Post_Processing_Hydrodynamic_Forces::ptr_eq_temp_ protected
Referenced by associate_temp_equation(), and compute_heat_transfer().
method_pressure_force_computation_
Method_pressure_force_computation Post_Processing_Hydrodynamic_Forces::method_pressure_force_computation_ protected
Initial value:
=
    Method_pressure_force_computation::TRILINEAR_LINEAR
Referenced by get_method_pressure_force_computation(), lire_motcle_non_standard(), and Post_Processing_Hydrodynamic_Forces_Stokes::set_param().
method_friction_force_computation_
Method_friction_force_computation Post_Processing_Hydrodynamic_Forces::method_friction_force_computation_ protected
Initial value:
=
    Method_friction_force_computation::TRILINEAR_LINEAR_PROJECTED_TENSOR
Referenced by compute_hydrodynamic_forces(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_hydrodynamic_forces(), get_method_friction_force_computation(), and lire_motcle_non_standard().
location_stress_tensor_
Location_stress_tensor Post_Processing_Hydrodynamic_Forces::location_stress_tensor_ =Location_stress_tensor::ELEMENTS protected
Referenced by compute_friction_force_complet_tensor(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_friction_force_complet_tensor(), compute_friction_force_projected_tensor(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_friction_force_projected_tensor(), get_location_stress_tensor(), lire_motcle_non_standard(), and Post_Processing_Hydrodynamic_Forces_Stokes::set_param().
is_compute_stokes_theoretical_forces_
int Post_Processing_Hydrodynamic_Forces::is_compute_stokes_theoretical_forces_ =0 protected
Referenced by get_is_compute_forces_Stokes_th(), Post_Processing_Hydrodynamic_Forces_Stokes::set_param(), and set_param().
is_post_process_pressure_force_fa7_
int Post_Processing_Hydrodynamic_Forces::is_post_process_pressure_force_fa7_ =0 protected
Referenced by compute_pressure_force_trilinear_linear(), get_is_post_process_pressure_force_fa7(), resize_data_fa7(), Post_Processing_Hydrodynamic_Forces_Stokes::set_param(), and set_param().
is_post_process_friction_force_fa7_
int Post_Processing_Hydrodynamic_Forces::is_post_process_friction_force_fa7_ =0 protected
Referenced by compute_friction_force_complet_tensor(), compute_friction_force_projected_tensor(), get_is_post_process_friction_force_fa7(), resize_data_fa7(), Post_Processing_Hydrodynamic_Forces_Stokes::set_param(), and set_param().
is_post_process_stress_tensor_fa7_
int Post_Processing_Hydrodynamic_Forces::is_post_process_stress_tensor_fa7_ =0 protected
Referenced by compute_friction_force_complet_tensor(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_friction_force_complet_tensor(), get_is_post_process_stress_tensor_fa7(), resize_data_fa7(), Post_Processing_Hydrodynamic_Forces_Stokes::resize_data_fa7(), Post_Processing_Hydrodynamic_Forces_Stokes::set_param(), and set_param().
is_post_process_pressure_fa7_
int Post_Processing_Hydrodynamic_Forces::is_post_process_pressure_fa7_ =0 protected
Referenced by compute_pressure_force_trilinear_linear(), get_is_post_process_pressure_fa7(), resize_data_fa7(), Post_Processing_Hydrodynamic_Forces_Stokes::resize_data_fa7(), Post_Processing_Hydrodynamic_Forces_Stokes::set_param(), and set_param().
is_compute_heat_transfer_
int Post_Processing_Hydrodynamic_Forces::is_compute_heat_transfer_ =0 protected
Referenced by get_is_compute_heat_transfer(), and set_param().
is_compute_forces_
int Post_Processing_Hydrodynamic_Forces::is_compute_forces_ =0 protected
Referenced by get_is_compute_forces(), Post_Processing_Hydrodynamic_Forces_Stokes::set_param(), and set_param().
flag_force_computation_
int Post_Processing_Hydrodynamic_Forces::flag_force_computation_ =0 protected
Referenced by compute_hydrodynamic_forces(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_hydrodynamic_forces(), drop_the_flag(), and raise_the_flag().
flag_heat_transfer_computation_
int Post_Processing_Hydrodynamic_Forces::flag_heat_transfer_computation_ =0 protected
Referenced by compute_heat_transfer(), drop_the_flag_heat_transfer(), and raise_the_flag_heat_transfer().
interpolation_distance_temperature_P1_
double Post_Processing_Hydrodynamic_Forces::interpolation_distance_temperature_P1_ =0 protected
Referenced by compute_heat_transfer(), and set_param().
interpolation_distance_temperature_P2_
double Post_Processing_Hydrodynamic_Forces::interpolation_distance_temperature_P2_ =0 protected
Referenced by compute_heat_transfer(), and set_param().
interpolation_distance_pressure_P1_
double Post_Processing_Hydrodynamic_Forces::interpolation_distance_pressure_P1_ =0 protected
Referenced by compute_neighbors_coordinates_fluid_fa7(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_neighbors_coordinates_fluid_fa7(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_pressure_force_trilinear_linear(), compute_pressure_force_trilinear_linear(), get_interpolation_distance_pressure_P1(), Post_Processing_Hydrodynamic_Forces_Stokes::set_param(), and set_param().
interpolation_distance_pressure_P2_
double Post_Processing_Hydrodynamic_Forces::interpolation_distance_pressure_P2_ =0 protected
Referenced by compute_neighbors_coordinates_fluid_fa7(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_neighbors_coordinates_fluid_fa7(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_pressure_force_trilinear_linear(), compute_pressure_force_trilinear_linear(), get_interpolation_distance_pressure_P2(), Post_Processing_Hydrodynamic_Forces_Stokes::set_param(), and set_param().
interpolation_distance_gradU_P1_
double Post_Processing_Hydrodynamic_Forces::interpolation_distance_gradU_P1_ =0 protected
Referenced by compute_friction_force_complet_tensor(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_friction_force_complet_tensor(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_neighbors_coordinates_fluid_fa7(), get_interpolation_distance_gradU_P1(), Post_Processing_Hydrodynamic_Forces_Stokes::set_param(), and set_param().
interpolation_distance_gradU_P2_
double Post_Processing_Hydrodynamic_Forces::interpolation_distance_gradU_P2_ =0 protected
Referenced by compute_friction_force_complet_tensor(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_friction_force_complet_tensor(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_neighbors_coordinates_fluid_fa7(), get_interpolation_distance_gradU_P2(), Post_Processing_Hydrodynamic_Forces_Stokes::set_param(), and set_param().
phase_indicator_function_P1_
DoubleVect Post_Processing_Hydrodynamic_Forces::phase_indicator_function_P1_ protected
phase_indicator_function_P2_
DoubleVect Post_Processing_Hydrodynamic_Forces::phase_indicator_function_P2_ protected
Referenced by compute_pressure_force_trilinear_linear(), resize_data_fa7(), and trilinear_interpolation_elem().
total_surface_interf_
DoubleVect Post_Processing_Hydrodynamic_Forces::total_surface_interf_ protected
Referenced by compute_hydrodynamic_forces(), compute_pressure_force_trilinear_linear(), get_total_surface_interf(), and resize_and_init_tables().
total_heat_transfer_
DoubleVect Post_Processing_Hydrodynamic_Forces::total_heat_transfer_ protected
Referenced by compute_heat_transfer(), get_heat_transfer(), and resize_and_init_tables().
pressure_fa7_
DoubleVect Post_Processing_Hydrodynamic_Forces::pressure_fa7_ protected
Referenced by Post_Processing_Hydrodynamic_Forces_Stokes::compute_pressure_force_trilinear_linear(), compute_pressure_force_trilinear_linear(), get_pressure_fa7(), resize_data_fa7(), and Post_Processing_Hydrodynamic_Forces_Stokes::resize_data_fa7().
list_elem_P1_all_
IntTab Post_Processing_Hydrodynamic_Forces::list_elem_P1_all_ mutable protected
Referenced by trilinear_interpolation_elem().
list_elem_P1_
IntTab Post_Processing_Hydrodynamic_Forces::list_elem_P1_ mutable protected
Referenced by find_neighboring_elements(), and trilinear_interpolation_elem().
Nb_fa7_tot_par_compo_
IntTab Post_Processing_Hydrodynamic_Forces::Nb_fa7_tot_par_compo_ protected
Referenced by compute_friction_force_projected_tensor(), compute_hydrodynamic_forces(), compute_proportion_fa7_ok_and_is_fluid_P2(), and resize_and_init_tables().
list_elem_diph_
IntTab Post_Processing_Hydrodynamic_Forces::list_elem_diph_ protected
Referenced by compute_hydrodynamic_forces(), and compute_neighbors_coordinates_fluid_fa7().
proportion_fa7_ok_UP2_
DoubleTab Post_Processing_Hydrodynamic_Forces::proportion_fa7_ok_UP2_ protected
Referenced by compute_friction_force_projected_tensor(), compute_hydrodynamic_forces(), compute_proportion_fa7_ok_and_is_fluid_P2(), compute_U_P2_moy(), get_prop_fa7_ok_P2(), and resize_and_init_tables().
total_pressure_force_
DoubleTab Post_Processing_Hydrodynamic_Forces::total_pressure_force_ protected
Referenced by compute_hydrodynamic_forces(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_hydrodynamic_forces(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_pressure_force_trilinear_linear(), compute_pressure_force_trilinear_linear(), get_pressure_force(), resize_and_init_tables(), and Post_Processing_Hydrodynamic_Forces_Stokes::resize_and_init_tables().
total_friction_force_
DoubleTab Post_Processing_Hydrodynamic_Forces::total_friction_force_ protected
Referenced by compute_friction_force_complet_tensor(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_friction_force_complet_tensor(), compute_friction_force_projected_tensor(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_friction_force_projected_tensor(), compute_hydrodynamic_forces(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_hydrodynamic_forces(), get_friction_force(), resize_and_init_tables(), and Post_Processing_Hydrodynamic_Forces_Stokes::resize_and_init_tables().
prop_P2_fluid_compo_
DoubleTab Post_Processing_Hydrodynamic_Forces::prop_P2_fluid_compo_ protected
Referenced by compute_hydrodynamic_forces(), compute_pressure_force_trilinear_linear(), compute_proportion_fa7_ok_and_is_fluid_P2(), get_prop_P2_fluid(), and resize_and_init_tables().
pressure_force_fa7_
DoubleTab Post_Processing_Hydrodynamic_Forces::pressure_force_fa7_ protected
Referenced by Post_Processing_Hydrodynamic_Forces_Stokes::compute_pressure_force_trilinear_linear(), compute_pressure_force_trilinear_linear(), get_pressure_force_fa7(), resize_data_fa7(), and Post_Processing_Hydrodynamic_Forces_Stokes::resize_data_fa7().
friction_force_fa7_
DoubleTab Post_Processing_Hydrodynamic_Forces::friction_force_fa7_ protected
Referenced by compute_friction_force_complet_tensor(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_friction_force_complet_tensor(), compute_friction_force_projected_tensor(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_friction_force_projected_tensor(), get_friction_force_fa7(), resize_data_fa7(), and Post_Processing_Hydrodynamic_Forces_Stokes::resize_data_fa7().
heat_transfer_fa7_
DoubleTab Post_Processing_Hydrodynamic_Forces::heat_transfer_fa7_ protected
Referenced by compute_heat_transfer(), and get_heat_transfer_fa7().
U_P2_moy_
DoubleTab Post_Processing_Hydrodynamic_Forces::U_P2_moy_ protected
Referenced by compute_friction_force_projected_tensor(), compute_hydrodynamic_forces(), compute_U_P2_moy(), get_U_P2_moy(), and resize_and_init_tables().
U_P1_
DoubleTab Post_Processing_Hydrodynamic_Forces::U_P1_ protected
Referenced by compute_friction_force_projected_tensor(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_friction_force_projected_tensor(), get_U_P1(), resize_data_fa7(), and Post_Processing_Hydrodynamic_Forces_Stokes::resize_data_fa7().
U_P2_
DoubleTab Post_Processing_Hydrodynamic_Forces::U_P2_ protected
Referenced by compute_friction_force_projected_tensor(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_friction_force_projected_tensor(), get_U_P2(), resize_data_fa7(), and Post_Processing_Hydrodynamic_Forces_Stokes::resize_data_fa7().
sigma_xx_fa7_
DoubleTab Post_Processing_Hydrodynamic_Forces::sigma_xx_fa7_ protected
Referenced by fill_sigma(), get_sigma_xx_fa7(), resize_sigma(), and Post_Processing_Hydrodynamic_Forces_Stokes::resize_sigma().
sigma_xy_fa7_
DoubleTab Post_Processing_Hydrodynamic_Forces::sigma_xy_fa7_ protected
Referenced by fill_sigma(), get_sigma_xy_fa7(), resize_sigma(), and Post_Processing_Hydrodynamic_Forces_Stokes::resize_sigma().
sigma_xz_fa7_
DoubleTab Post_Processing_Hydrodynamic_Forces::sigma_xz_fa7_ protected
Referenced by fill_sigma(), get_sigma_xz_fa7(), resize_sigma(), and Post_Processing_Hydrodynamic_Forces_Stokes::resize_sigma().
sigma_yx_fa7_
DoubleTab Post_Processing_Hydrodynamic_Forces::sigma_yx_fa7_ protected
Referenced by fill_sigma(), get_sigma_yx_fa7(), resize_sigma(), and Post_Processing_Hydrodynamic_Forces_Stokes::resize_sigma().
sigma_yy_fa7_
DoubleTab Post_Processing_Hydrodynamic_Forces::sigma_yy_fa7_ protected
Referenced by fill_sigma(), get_sigma_yy_fa7(), resize_sigma(), and Post_Processing_Hydrodynamic_Forces_Stokes::resize_sigma().
sigma_yz_fa7_
DoubleTab Post_Processing_Hydrodynamic_Forces::sigma_yz_fa7_ protected
Referenced by fill_sigma(), get_sigma_yz_fa7(), resize_sigma(), and Post_Processing_Hydrodynamic_Forces_Stokes::resize_sigma().
sigma_zx_fa7_
DoubleTab Post_Processing_Hydrodynamic_Forces::sigma_zx_fa7_ protected
Referenced by fill_sigma(), get_sigma_zx_fa7(), resize_sigma(), and Post_Processing_Hydrodynamic_Forces_Stokes::resize_sigma().
sigma_zy_fa7_
DoubleTab Post_Processing_Hydrodynamic_Forces::sigma_zy_fa7_ protected
Referenced by fill_sigma(), get_sigma_zy_fa7(), resize_sigma(), and Post_Processing_Hydrodynamic_Forces_Stokes::resize_sigma().
sigma_zz_fa7_
DoubleTab Post_Processing_Hydrodynamic_Forces::sigma_zz_fa7_ protected
Referenced by fill_sigma(), get_sigma_zz_fa7(), resize_sigma(), and Post_Processing_Hydrodynamic_Forces_Stokes::resize_sigma().
dUdx_P1_
DoubleTab Post_Processing_Hydrodynamic_Forces::dUdx_P1_ protected
Referenced by fill_gradU_P1(), get_dUdx_P1(), resize_gradU_P1(), and Post_Processing_Hydrodynamic_Forces_Stokes::resize_gradU_P1().
dUdy_P1_
DoubleTab Post_Processing_Hydrodynamic_Forces::dUdy_P1_ protected
Referenced by fill_gradU_P1(), get_dUdy_P1(), resize_gradU_P1(), and Post_Processing_Hydrodynamic_Forces_Stokes::resize_gradU_P1().
dUdz_P1_
DoubleTab Post_Processing_Hydrodynamic_Forces::dUdz_P1_ protected
Referenced by fill_gradU_P1(), get_dUdz_P1(), resize_gradU_P1(), and Post_Processing_Hydrodynamic_Forces_Stokes::resize_gradU_P1().
dVdx_P1_
DoubleTab Post_Processing_Hydrodynamic_Forces::dVdx_P1_ protected
Referenced by fill_gradU_P1(), get_dVdx_P1(), resize_gradU_P1(), and Post_Processing_Hydrodynamic_Forces_Stokes::resize_gradU_P1().
dVdy_P1_
DoubleTab Post_Processing_Hydrodynamic_Forces::dVdy_P1_ protected
Referenced by fill_gradU_P1(), get_dVdy_P1(), resize_gradU_P1(), and Post_Processing_Hydrodynamic_Forces_Stokes::resize_gradU_P1().
dVdz_P1_
DoubleTab Post_Processing_Hydrodynamic_Forces::dVdz_P1_ protected
Referenced by fill_gradU_P1(), get_dVdz_P1(), resize_gradU_P1(), and Post_Processing_Hydrodynamic_Forces_Stokes::resize_gradU_P1().
dWdx_P1_
DoubleTab Post_Processing_Hydrodynamic_Forces::dWdx_P1_ protected
Referenced by fill_gradU_P1(), get_dWdx_P1(), resize_gradU_P1(), and Post_Processing_Hydrodynamic_Forces_Stokes::resize_gradU_P1().
dWdy_P1_
DoubleTab Post_Processing_Hydrodynamic_Forces::dWdy_P1_ protected
Referenced by fill_gradU_P1(), get_dWdy_P1(), resize_gradU_P1(), and Post_Processing_Hydrodynamic_Forces_Stokes::resize_gradU_P1().
dWdz_P1_
DoubleTab Post_Processing_Hydrodynamic_Forces::dWdz_P1_ protected
Referenced by fill_gradU_P1(), get_dWdz_P1(), resize_gradU_P1(), and Post_Processing_Hydrodynamic_Forces_Stokes::resize_gradU_P1().
dUdx_P2_
DoubleTab Post_Processing_Hydrodynamic_Forces::dUdx_P2_ protected
Referenced by fill_gradU_P2(), get_dUdx_P2(), resize_gradU_P2(), and Post_Processing_Hydrodynamic_Forces_Stokes::resize_gradU_P2().
dUdy_P2_
DoubleTab Post_Processing_Hydrodynamic_Forces::dUdy_P2_ protected
Referenced by fill_gradU_P2(), get_dUdy_P2(), resize_gradU_P2(), and Post_Processing_Hydrodynamic_Forces_Stokes::resize_gradU_P2().
dUdz_P2_
DoubleTab Post_Processing_Hydrodynamic_Forces::dUdz_P2_ protected
Referenced by fill_gradU_P2(), get_dUdz_P2(), resize_gradU_P2(), and Post_Processing_Hydrodynamic_Forces_Stokes::resize_gradU_P2().
dVdx_P2_
DoubleTab Post_Processing_Hydrodynamic_Forces::dVdx_P2_ protected
Referenced by fill_gradU_P2(), get_dVdx_P2(), resize_gradU_P2(), and Post_Processing_Hydrodynamic_Forces_Stokes::resize_gradU_P2().
dVdy_P2_
DoubleTab Post_Processing_Hydrodynamic_Forces::dVdy_P2_ protected
Referenced by fill_gradU_P2(), get_dVdy_P2(), resize_gradU_P2(), and Post_Processing_Hydrodynamic_Forces_Stokes::resize_gradU_P2().
dVdz_P2_
DoubleTab Post_Processing_Hydrodynamic_Forces::dVdz_P2_ protected
Referenced by fill_gradU_P2(), get_dVdz_P2(), resize_gradU_P2(), and Post_Processing_Hydrodynamic_Forces_Stokes::resize_gradU_P2().
dWdx_P2_
DoubleTab Post_Processing_Hydrodynamic_Forces::dWdx_P2_ protected
Referenced by fill_gradU_P2(), get_dWdx_P2(), resize_gradU_P2(), and Post_Processing_Hydrodynamic_Forces_Stokes::resize_gradU_P2().
dWdy_P2_
DoubleTab Post_Processing_Hydrodynamic_Forces::dWdy_P2_ protected
Referenced by fill_gradU_P2(), get_dWdy_P2(), resize_gradU_P2(), and Post_Processing_Hydrodynamic_Forces_Stokes::resize_gradU_P2().
dWdz_P2_
DoubleTab Post_Processing_Hydrodynamic_Forces::dWdz_P2_ protected
Referenced by fill_gradU_P2(), get_dWdz_P2(), resize_gradU_P2(), and Post_Processing_Hydrodynamic_Forces_Stokes::resize_gradU_P2().
coord_neighbor_fluid_fa7_pressure_1_
DoubleTab Post_Processing_Hydrodynamic_Forces::coord_neighbor_fluid_fa7_pressure_1_ protected
Referenced by compute_neighbors_coordinates_fluid_fa7(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_neighbors_coordinates_fluid_fa7(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_pressure_force_trilinear_linear(), compute_pressure_force_trilinear_linear(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_UP1_UP2_Stokes(), fill_absurd_value_coord_neighbor_fluid_fa7(), and resize_coord_neighbor_fluid_fa7().
coord_neighbor_fluid_fa7_pressure_2_
DoubleTab Post_Processing_Hydrodynamic_Forces::coord_neighbor_fluid_fa7_pressure_2_ protected
Referenced by compute_neighbors_coordinates_fluid_fa7(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_neighbors_coordinates_fluid_fa7(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_pressure_force_trilinear_linear(), compute_pressure_force_trilinear_linear(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_UP1_UP2_Stokes(), fill_absurd_value_coord_neighbor_fluid_fa7(), and resize_coord_neighbor_fluid_fa7().
coord_neighbor_fluid_fa7_gradU_1_
DoubleTab Post_Processing_Hydrodynamic_Forces::coord_neighbor_fluid_fa7_gradU_1_ protected
Referenced by compute_friction_force_complet_tensor(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_friction_force_complet_tensor(), compute_friction_force_projected_tensor(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_friction_force_projected_tensor(), compute_neighbors_coordinates_fluid_fa7(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_neighbors_coordinates_fluid_fa7(), fill_absurd_value_coord_neighbor_fluid_fa7(), Post_Processing_Hydrodynamic_Forces_Stokes::fill_gradU_P1_Stokes_th(), and resize_coord_neighbor_fluid_fa7().
coord_neighbor_fluid_fa7_gradU_2_
DoubleTab Post_Processing_Hydrodynamic_Forces::coord_neighbor_fluid_fa7_gradU_2_ protected
Referenced by compute_friction_force_complet_tensor(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_friction_force_complet_tensor(), compute_friction_force_projected_tensor(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_friction_force_projected_tensor(), compute_neighbors_coordinates_fluid_fa7(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_neighbors_coordinates_fluid_fa7(), fill_absurd_value_coord_neighbor_fluid_fa7(), Post_Processing_Hydrodynamic_Forces_Stokes::fill_gradU_P2_Stokes_th(), and resize_coord_neighbor_fluid_fa7().
coord_neighbor_fluid_fa7_temp_1_
DoubleTab Post_Processing_Hydrodynamic_Forces::coord_neighbor_fluid_fa7_temp_1_ protected
Referenced by compute_heat_transfer().
coord_neighbor_fluid_fa7_temp_2_
DoubleTab Post_Processing_Hydrodynamic_Forces::coord_neighbor_fluid_fa7_temp_2_ protected
Referenced by compute_heat_transfer().