TrioCFD: Convection_Diffusion_Espece_Multi_WC Class Reference
Convection_Diffusion_Espece_Multi_WC Class Reference
#include <Convection_Diffusion_Espece_Multi_WC.h>
Public Member Functions
DoubleTab & derivee_en_temps_inco (DoubleTab &) override
const Type_info * get_info () const override
Public Member Functions inherited from Convection_Diffusion_Espece_Multi_base
const Type_info * get_info () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
Public Member Functions inherited from Convection_Diffusion_Espece_Fluide_Dilatable_base
std::vector< YAML_data > data_a_sauvegarder () const override
DoubleTab & derivee_en_temps_inco (DoubleTab &) override=0
void discretiser () override
const Motcle & domaine_application () const override
const Type_info * get_info () const override
int preparer_calcul () override
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Public Member Functions inherited from Convection_Diffusion_Fluide_Dilatable_base
const Type_info * get_info () const override
int impr (Sortie &os) const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
Public Member Functions inherited from Convection_Diffusion_std
void associer_vitesse (const Champ_base &)
const Type_info * get_info () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
int nombre_d_operateurs () const override
const Operateur & operateur (int) const override
Operateur & operateur (int) override
const Champ_Inc_base & vitesse_transportante () const
Public Member Functions inherited from Equation_base
virtual void abortTimeStep ()
virtual void associer_domaine_dis (const Domaine_dis_base &)
virtual void associer_pb_base (const Probleme_base &)
virtual void associer_sch_tps_base (const Schema_Temps_base &)
virtual double calculer_pas_de_temps () const
virtual void completer ()
virtual std::vector< YAML_data > data_a_sauvegarder () const
DoubleTab & derivee_en_temps_conv (DoubleTab &, const DoubleTab &)
virtual DoubleTab & derivee_en_temps_inco (DoubleTab &)
const Discretisation_base & discretisation () const
virtual void discretiser ()
virtual const Motcle & domaine_application () const
virtual Domaine_Cl_dis_base & domaine_Cl_dis ()
virtual const Domaine_Cl_dis_base & domaine_Cl_dis () const
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual void imprimer (Sortie &os) const
virtual bool initTimeStep (double dt)
const Nom & le_nom () const override
int limpr () const
virtual void mettre_a_jour (double temps)
virtual int preparer_calcul ()
Probleme_base & probleme ()
const Probleme_base & probleme () const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Schema_Temps_base & schema_temps ()
const Schema_Temps_base & schema_temps () const
Solveur_Masse_base & solv_masse ()
const Solveur_Masse_base & solv_masse () const
Sources & sources ()
const Sources & sources () const
virtual void valider_iteration ()
virtual void verifie_ch_init_nb_comp (const Champ_Inc_base &ch_ref, const int nb_comp) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Convection_Diffusion_std
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Equation_base
virtual Entree & lire_cl (Entree &)
virtual Entree & lire_cond_init (Entree &)
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual Entree & lire_sources (Entree &)
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
virtual int verif_Cl () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Convection_Diffusion_Fluide_Dilatable_Proto
DoubleTab & derivee_en_temps_inco_sans_solveur_masse_impl (Convection_Diffusion_Fluide_Dilatable_base &eqn, DoubleTab &derivee, const bool is_expl)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
pour un fluide quasi conpressible quand le scalaire subissant le transport est
la fraction massique
See also
Convection_Diffusion_Espece_Multi_base
Constructor & Destructor Documentation
Convection_Diffusion_Espece_Multi_WC()
Convection_Diffusion_Espece_Multi_WC::Convection_Diffusion_Espece_Multi_WC ()
~Convection_Diffusion_Espece_Multi_WC()
Convection_Diffusion_Espece_Multi_WC::~Convection_Diffusion_Espece_Multi_WC ()
Member Function Documentation
cree_instance()
Objet_U * Convection_Diffusion_Espece_Multi_WC::cree_instance () static
taille_memoire()
unsigned Convection_Diffusion_Espece_Multi_WC::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Convection_Diffusion_Espece_Multi_WC::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Convection_Diffusion_Espece_Multi_WC::info () static
get_info()
const Type_info * Convection_Diffusion_Espece_Multi_WC::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Convection_Diffusion_Espece_Multi_base.
self_cast() [1/2]
Convection_Diffusion_Espece_Multi_WC & Convection_Diffusion_Espece_Multi_WC::self_cast (Objet_U & r) static
self_cast() [2/2]
const Convection_Diffusion_Espece_Multi_WC & Convection_Diffusion_Espece_Multi_WC::self_cast (const Objet_U & r) static
printOn()
Sortie & Convection_Diffusion_Espece_Multi_WC::printOn (Sortie & os) const override protected virtual
Surcharge Objet_U::printOn Imprime l'equation et ses composants sur un flot de sortie.
Imprime le nom de l'equation, le solveur masse, les termes sources les conditions aux limites discretisees, les inconnues et les operateurs.
Parameters
(Sortie& os) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Convection_Diffusion_Espece_Multi_base.
References Convection_Diffusion_Espece_Multi_base::printOn().
readOn()
Entree & Convection_Diffusion_Espece_Multi_WC::readOn (Entree & is) override protected virtual
Lecture d'une equation sur un flot d'entree.
Le format est le suivant: { [Source { [sou_1], [sour_2], ...} ] Conditions_limites { [cl_1] [cl_2] ... } Conditions_initiales { [cl_init] } }
Parameters
(Entree& is) un flot d'entree pour lire l'equation
Returns
(Entree&) le flot d'entree modifie
Exceptions
mauvais format de lecture, accolade ouvrante attendue
pas de conditions initiales, il faut initialiser l'inconnue
pas de conditions aux limites, il faut donner des conditions aux limites
Reimplemented from Convection_Diffusion_Espece_Multi_base.
References Convection_Diffusion_Espece_Multi_base::readOn().
completer()
void Convection_Diffusion_Espece_Multi_WC::completer () override virtual
Associe l inconnue de l equation a la loi d etat,.
Reimplemented from Equation_base.
References Loi_Etat_Multi_GP_base::associer_inconnue(), Equation_base::completer(), Convection_Diffusion_Fluide_Dilatable_base::fluide(), Convection_Diffusion_Fluide_Dilatable_base::l_inco_ch, Fluide_Dilatable_base::loi_etat(), and TRUST_Deriv< _CLASSE_ >::valeur().
assembler()
void Convection_Diffusion_Espece_Multi_WC::assembler (Matrice_Morse & mat_morse, const DoubleTab & present, DoubleTab & secmem) override virtual
Implements Convection_Diffusion_Espece_Fluide_Dilatable_base.
References Convection_Diffusion_Fluide_Dilatable_Proto::assembler_impl().
diffusivite_pour_pas_de_temps()
const Champ_base & Convection_Diffusion_Espece_Multi_WC::diffusivite_pour_pas_de_temps () const override virtual
Implements Convection_Diffusion_Espece_Fluide_Dilatable_base.
References Convection_Diffusion_Fluide_Dilatable_base::le_fluide.
vitesse_pour_transport()
const Champ_base & Convection_Diffusion_Espece_Multi_WC::vitesse_pour_transport () const override virtual
Reimplemented from Convection_Diffusion_std.
References Equation_base::probleme(), and Navier_Stokes_std::rho_la_vitesse().
assembler_blocs_avec_inertie()
void Convection_Diffusion_Espece_Multi_WC::assembler_blocs_avec_inertie (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl) override virtual
Reimplemented from Equation_base.
References Schema_Temps_base::ajouter_blocs(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_blocs(), Statistiques::begin_count(), Equation_base::discretisation(), Statistiques::end_count(), Nom::getString(), Convection_Diffusion_Fluide_Dilatable_base::inconnue(), Field_base::le_nom(), Equation_base::modifier_pour_Cl(), and Equation_base::schema_temps().
derivee_en_temps_inco()
DoubleTab & Convection_Diffusion_Espece_Multi_WC::derivee_en_temps_inco (DoubleTab & derivee) override virtual
Returns the time derivative of the unknown I of the equation: dI/dt = M-1*(sum(operators(I) + sources))
In : derivee contains I (but immediatly set to 0) Out: derivee contains dI/dt
Implements Convection_Diffusion_Espece_Fluide_Dilatable_base.
References Convection_Diffusion_Fluide_Dilatable_Proto::derivee_en_temps_inco_sans_solveur_masse_impl().
Member Data Documentation
info_obj
const Type_info Convection_Diffusion_Espece_Multi_WC::info_obj static