TrioCFD: Eval_Source_C_VEF_Face Class Reference
Eval_Source_C_VEF_Face Class Reference
#include <Eval_Source_C_VEF_Face.h>
Constructor & Destructor Documentation
Eval_Source_C_VEF_Face()
Eval_Source_C_VEF_Face::Eval_Source_C_VEF_Face () inline
Member Function Documentation
completer()
void Eval_Source_C_VEF_Face::completer () override virtual
Reimplemented from Evaluateur_Source_Face.
References Evaluateur_Source_VEF_Face::completer(), Evaluateur_Source_VEF_Face::face_voisins, Evaluateur_Source::le_dom, nb_faces_elem, TRUSTTab< _TYPE_, _SIZE_ >::ref(), TRUSTVect< _TYPE_, _SIZE_ >::ref(), TRUST_Ref< _CLASSE_ >::valeur(), and volumes.
associer_champs()
void Eval_Source_C_VEF_Face::associer_champs (const Champ_Don_base & Q)
References la_source_constituant, TRUSTTab< _TYPE_, _SIZE_ >::ref(), source_constituant, and Champ_Don_base::valeurs().
Referenced by Terme_Source_Constituant_VEF_Face::associer_pb().
mettre_a_jour()
void Eval_Source_C_VEF_Face::mettre_a_jour () inline override virtual
Implements Evaluateur_Source.
Member Data Documentation
la_source_constituant
TRUST_Ref< Champ_Don_base *> Eval_Source_C_VEF_Face::la_source_constituant protected
Referenced by associer_champs().
source_constituant
DoubleTab Eval_Source_C_VEF_Face::source_constituant protected
Referenced by associer_champs(), and Eval_Source_C_VEF_Face_View::set().
volumes
DoubleVect Eval_Source_C_VEF_Face::volumes protected
Referenced by completer(), and Eval_Source_C_VEF_Face_View::set().
nb_faces_elem
int Eval_Source_C_VEF_Face::nb_faces_elem = 0 mutable protected
Referenced by Eval_Source_C_VEF_Face_View::calculer_terme_source_non_standard_view(), Eval_Source_C_VEF_Face_View::calculer_terme_source_standard_view(), completer(), and Eval_Source_C_VEF_Face_View::set().