TrioCFD: Champ_front_Tabule Class Reference
Champ_front_Tabule Class Reference
#include <Champ_front_Tabule.h>
Public Member Functions
Champ_front_base & affecter_ (const Champ_front_base &ch) override
const Type_info * get_info () const override
int initialiser (double temps, const Champ_Inc_base &inco) override
void mettre_a_jour (double temps) override
Public Member Functions inherited from Champ_front_instationnaire_base
int avancer (double temps) override
const Type_info * get_info () const override
int initialiser (double temps, const Champ_Inc_base &inco) override
int reculer (double temps) override
const DoubleTab & valeurs_au_temps (double temps) const override
DoubleTab & valeurs_au_temps (double temps) override
void valeurs_face (int, DoubleVect &) const override
Public Member Functions inherited from Champ_front_base
virtual void associer_fr_dis_base (const Frontiere_dis_base &)
virtual int avancer (double temps)
virtual void calculer_coeffs_echange (double temps)
virtual void fixer_nb_valeurs_temporelles (int nb_cases)
virtual Frontiere_dis_base & frontiere_dis ()
virtual const Frontiere_dis_base & frontiere_dis () const
const Type_info * get_info () const override
virtual int initialiser (double temps, const Champ_Inc_base &inco)
virtual void mettre_a_jour (double temps)
virtual int reculer (double temps)
virtual const DoubleTab & valeurs () const override
virtual DoubleTab & valeurs () override
virtual void valeurs_face (int, DoubleVect &) const
Public Member Functions inherited from Field_base
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
virtual void fixer_nb_comp (int i)
virtual const Nom & fixer_nom_compo (const Nom &)
virtual const Nom & fixer_nom_compo (int, const Nom &)
virtual const Noms & fixer_noms_compo (const Noms &)
virtual const Nom & fixer_unite (const Nom &)
virtual const Nom & fixer_unite (int i, const Nom &)
virtual const Noms & fixer_unites (const Noms &)
const Type_info * get_info () const override
const Nom & nom_compo (int) const
void nommer (const Nom &) override
const Nom & unite () const
const Nom & unite (int) const
const Noms & unites () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Champ_Proto
int lire_dimension (Entree &, const Nom &)
int lire_dimension (int dim, const Nom &le_nom_)
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Champ_front_instationnaire_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Field_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
represente les champs aux frontieres uniformes en espace,
calcules par tabulation en fonction du temps.
See also
Champ_front_base
Constructor & Destructor Documentation
Champ_front_Tabule()
Champ_front_Tabule::Champ_front_Tabule ()
~Champ_front_Tabule()
Champ_front_Tabule::~Champ_front_Tabule ()
Member Function Documentation
cree_instance()
Objet_U * Champ_front_Tabule::cree_instance () static
taille_memoire()
unsigned Champ_front_Tabule::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Champ_front_Tabule_lu.
duplique()
int Champ_front_Tabule::duplique () const override virtual
Implements Objet_U.
Reimplemented in Champ_front_Tabule_lu.
info()
const Type_info * Champ_front_Tabule::info () static
get_info()
const Type_info * Champ_front_Tabule::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
Reimplemented in Champ_front_Tabule_lu.
self_cast() [1/2]
Champ_front_Tabule & Champ_front_Tabule::self_cast (Objet_U & r) static
self_cast() [2/2]
const Champ_front_Tabule & Champ_front_Tabule::self_cast (const Objet_U & r) static
printOn()
Sortie & Champ_front_Tabule::printOn (Sortie & os) const override protected virtual
Imprime les valeurs du champ sur un flot de sortie.
Parameters
(Sortie& os) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Objet_U.
Reimplemented in Champ_front_Tabule_lu.
References Champ_front_base::valeurs().
Referenced by Champ_front_Tabule_lu::printOn().
readOn()
Entree & Champ_front_Tabule::readOn (Entree & is) override protected virtual
Lit les valeurs du champ tabule a partir d'un flot d'entree.
Format: Champ_front_Tabule nb_comp { nval tps_1...tps_nval vrel_1...vrel_nval }
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Exceptions
accolade ouvrante attendue
accolade fermante attendue
Reimplemented from Objet_U.
Reimplemented in Champ_front_Tabule_lu.
References Process::exit(), Field_base::fixer_nb_comp(), la_table, Champ_Proto::lire_dimension(), Objet_U::que_suis_je(), and Table::remplir().
Referenced by Champ_front_Tabule_lu::readOn().
affecter_()
Champ_front_base & Champ_front_Tabule::affecter_ (const Champ_front_base & ch) override virtual
Renvoie l'objet Champ_front_Tabule upcaste en Champ_front_base.
Parameters
(Champ_front_base& ch)
Returns
(Champ_front_base&) (*this) upcaste en Champ_front_base
Implements Champ_front_base.
initialiser()
int Champ_front_Tabule::initialiser (double temps, const Champ_Inc_base & inco) override virtual
Initialisation en debut de calcul.
Imperativement cette methode ne doit pas utiliser de donnees externes a l'equation (couplage). Si mettre_a_jour le fait, alors initialiser ne doit pas appeler mettre_a_jour.
Returns
(0 en cas d'erreur, 1 sinon.)
Reimplemented from Champ_front_base.
References Champ_front_instationnaire_base::initialiser(), and mettre_a_jour().
mettre_a_jour()
void Champ_front_Tabule::mettre_a_jour (double temps) override virtual
Mise a jour en temps du champ.
Calcul du gradient Gpoint.
Parameters
(double tps) le temps de mise a jour
Reimplemented from Champ_front_base.
References la_table, Table::valeurs(), and Champ_front_instationnaire_base::valeurs_au_temps().
Referenced by initialiser().
getTable()
Table & Champ_front_Tabule::getTable () inline
References la_table.
Member Data Documentation
info_obj
const Type_info Champ_front_Tabule::info_obj static
la_table
Table Champ_front_Tabule::la_table protected
Referenced by getTable(), mettre_a_jour(), and readOn().