TrioCFD: Associer Class Reference
Associer Class Reference
#include <Associer.h>
Public Member Functions
const Type_info * get_info () const override
Entree & interpreter (Entree &) override
Public Member Functions inherited from Interprete
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Interprete
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Interprete
static Objet_U & objet (const Nom &)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
[DANS LE JEU DE DONNEES] Associer ob1 ob2
See also
Interprete
Constructor & Destructor Documentation
Associer()
Associer::Associer ()
~Associer()
Associer::~Associer ()
Member Function Documentation
cree_instance()
Objet_U * Associer::cree_instance () static
taille_memoire()
unsigned Associer::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Associer::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Associer::info () static
get_info()
const Type_info * Associer::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
Associer & Associer::self_cast (Objet_U & r) static
self_cast() [2/2]
const Associer & Associer::self_cast (const Objet_U & r) static
printOn()
Sortie & Associer::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
References Interprete::printOn().
readOn()
Entree & Associer::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
References Interprete::readOn().
interpreter()
Entree & Associer::interpreter (Entree & is) override virtual
Fonction principale de l'interprete Associer: associer deux objets.
On essaye d'associer 1 a 2 et 2 a 1, provoque une erreur si cela echoue.
Parameters
(Entree& is) un flot d'entree, a partir duquel on lit les noms des objets a associer
Returns
(Entree&) le flot d'entree modifie
Exceptions
on ne sait pas associer obj1 et obj2
Implements Interprete.
References Objet_U::associer_(), Entree::eof(), Process::exit(), Interprete::objet(), and Objet_U::que_suis_je().
Member Data Documentation
info_obj
const Type_info Associer::info_obj static