TrioCFD: Cut_field_vector< T, N > Class Template Reference
Cut_field_vector< T, N > Class Template Reference
#include <Cut_field.h>
Additional Inherited Members
Public Member Functions inherited from IJK_Field_vector< T, N >
void nommer (const Nom &nam) override
Sortie & printOn (Sortie &os) const override
Entree & readOn (Entree &is) override
Public Member Functions inherited from Field_base
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
virtual void fixer_nb_comp (int i)
virtual const Nom & fixer_nom_compo (const Nom &)
virtual const Nom & fixer_nom_compo (int, const Nom &)
virtual const Noms & fixer_noms_compo (const Noms &)
virtual const Nom & fixer_unite (const Nom &)
virtual const Nom & fixer_unite (int i, const Nom &)
virtual const Noms & fixer_unites (const Noms &)
const Type_info * get_info () const override
const Nom & nom_compo (int) const
void nommer (const Nom &) override
const Nom & unite () const
const Nom & unite (int) const
const Noms & unites () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Constructor & Destructor Documentation
Cut_field_vector()
template<class T , int N> Cut_field_vector< T, N >::Cut_field_vector
Member Function Documentation
set_to_uniform_value()
template<class T , int N> void Cut_field_vector< T, N >::set_to_uniform_value (int valeur)
References Cut_field_vector< T, N >::operator[]().
Referenced by IJK_Interfaces::calculer_var_volume_remaillage(), and IJK_Thermal_cut_cell::perform_thermal_step().
echange_espace_virtuel()
template<class T , int N> void Cut_field_vector< T, N >::echange_espace_virtuel (int ghost)
References Cut_field_vector< T, N >::operator[]().
Referenced by Cut_cell_schema_auxiliaire::add_dying_cells(), Cut_cell_schema_auxiliaire::add_small_nascent_cells(), and IJK_Thermal_cut_cell::perform_thermal_step().
ghost()
template<class T , int N> int Cut_field_vector< T, N >::ghost
References Cut_field_vector< T, N >::operator[]().
Referenced by IJK_Interfaces::calculer_vitesse_de_deformation().
echange_pure_vers_diph_cellules_initialement_pures()
template<class T , int N> void Cut_field_vector< T, N >::echange_pure_vers_diph_cellules_initialement_pures
References Cut_field_vector< T, N >::operator[]().
Referenced by IJK_Thermal_cut_cell::echange_pure_vers_diph_cellules_initialement_pures().
echange_diph_vers_pure_cellules_finalement_pures()
template<class T , int N> void Cut_field_vector< T, N >::echange_diph_vers_pure_cellules_finalement_pures
References Cut_field_vector< T, N >::operator[]().
Referenced by IJK_Thermal_cut_cell::echange_diph_vers_pure_cellules_finalement_pures().
vide_phase_invalide_cellules_diphasiques()
template<class T , int N> void Cut_field_vector< T, N >::vide_phase_invalide_cellules_diphasiques
References Cut_field_vector< T, N >::operator[]().
Referenced by IJK_Thermal_cut_cell::vide_phase_invalide_cellules_diphasiques().
operator[]() [1/2]
template<class T , int N> Cut_field_template< T, TRUSTArray< T > > & Cut_field_vector< T, N >::operator[] (int i) inline
References IJK_Field_vector< T, N >::operator[]().
Referenced by Cut_field_vector< T, N >::echange_diph_vers_pure_cellules_finalement_pures(), Cut_field_vector< T, N >::echange_espace_virtuel(), Cut_field_vector< T, N >::echange_pure_vers_diph_cellules_initialement_pures(), Cut_field_vector< T, N >::ghost(), Cut_field_vector< T, N >::set_to_uniform_value(), and Cut_field_vector< T, N >::vide_phase_invalide_cellules_diphasiques().
operator[]() [2/2]
template<class T , int N> const Cut_field_template< T, TRUSTArray< T > > & Cut_field_vector< T, N >::operator[] (int i) const inline
References IJK_Field_vector< T, N >::operator[]().