TrioCFD: Extruder_en20 Class Reference
Extruder_en20 Class Reference
#include <Extruder_en20.h>
Public Member Functions
void extruder (Domaine &)
const Type_info * get_info () const override
Entree & interpreter_ (Entree &) override
Public Member Functions inherited from Interprete_geometrique_base_32_64< _SIZE_ >
const Type_info * get_info () const override
void mettre_a_jour_sous_domaine (Domaine_t &domaine, int_t &elem, int_t num_premier_elem, int_t nb_elem) const
Public Member Functions inherited from Interprete
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Interprete_geometrique_base_32_64< _SIZE_ >
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Interprete
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Interprete
static Objet_U & objet (const Nom &)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
la directive Extruder_en20: Extruder_en20 nom_domaine Cette directive est a utiliser en discretisation VEF 2D pour obtenir un maillage 3D par extrusion puis decoupage.
See also
Interprete Extruder_en20, Cette classe est utilisable en 3D
Constructor & Destructor Documentation
~Extruder_en20()
Extruder_en20::~Extruder_en20 ()
Extruder_en20()
Extruder_en20::Extruder_en20 ()
References direction, and TRUSTArray< _TYPE_, _SIZE_ >::resize().
Member Function Documentation
cree_instance()
Objet_U * Extruder_en20::cree_instance () static
taille_memoire()
unsigned Extruder_en20::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Extruder_en20::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Extruder_en20::info () static
get_info()
const Type_info * Extruder_en20::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
Extruder_en20 & Extruder_en20::self_cast (Objet_U & r) static
self_cast() [2/2]
const Extruder_en20 & Extruder_en20::self_cast (const Objet_U & r) static
printOn()
Sortie & Extruder_en20::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
References Interprete::printOn().
readOn()
Entree & Extruder_en20::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
References Interprete::readOn().
interpreter_()
Entree & Extruder_en20::interpreter_ (Entree & is) override virtual
Fonction principale de l'interprete Extruder_en20 Triangule tout le domaine.
specifie par la directive. On triangule le domaine grace a la methode: void Extruder_en20::extruder(Domaine& domaine) const Extruder signifie ici transformer en triangle des elements geometrique d'un domaine.
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree
Exceptions
l'objet a mailler n'est pas du type Domaine
Implements Interprete_geometrique_base_32_64< _SIZE_ >.
References Param::ajouter(), Param::ajouter_arr_size_predefinie(), Interprete_geometrique_base_32_64< _SIZE_ >::associer_domaine(), direction, Interprete_geometrique_base_32_64< _SIZE_ >::domaine(), extruder(), Scatter::init_sequential_domain(), Param::lire_avec_accolades_depuis(), NZ, Objet_U::que_suis_je(), Param::REQUIRED, and Scatter::uninit_sequential_domain().
setDirection()
void Extruder_en20::setDirection (double lx, double ly, double lz) inline
References direction.
setNbTranches()
void Extruder_en20::setNbTranches (int n) inline
References NZ.
extruder()
void Extruder_en20::extruder (Domaine & dom)
Triangule tous les element d'un domaine: transforme les elements goemetriques du domaine en triangles.
Pour l'instant on ne sait raffiner que des Rectangles (on les coupe en 4).
Parameters
(Domaine& domaine) le domaine dont on veut raffiner les elements
References Domaine_32_64< _SIZE_ >::ajouter(), Faces_32_64< _SIZE_ >::associer_domaine(), Faces_builder::creer_faces_reeles(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, direction, Process::exit(), extruder_dvt(), Domaine_32_64< _SIZE_ >::invalide_octree(), Domaine_32_64< _SIZE_ >::les_elems(), Domaine_32_64< _SIZE_ >::les_sommets(), Interprete_geometrique_base_32_64< _SIZE_ >::mettre_a_jour_sous_domaine(), Faces_32_64< _SIZE_ >::nb_faces(), Domaine_32_64< _SIZE_ >::nb_som(), Domaine_32_64< _SIZE_ >::nb_som_tot(), NZ, Objet_U::que_suis_je(), TRUSTTab< _TYPE_, _SIZE_ >::ref(), TRUSTTab< _TYPE_, _SIZE_ >::reset(), Faces_32_64< _SIZE_ >::sommet(), Domaine_32_64< _SIZE_ >::type_elem(), Elem_geom_base_32_64< _SIZE_ >::type_face(), Faces_32_64< _SIZE_ >::typer(), Domaine_32_64< _SIZE_ >::typer(), and Faces_32_64< _SIZE_ >::voisin().
Referenced by interpreter_().
extruder_dvt()
void Extruder_en20::extruder_dvt (Domaine & dom, Faces & les_faces, int oldnbsom, int oldsz) protected virtual
References TRUST_List< _CLASSE_ >::add(), Frontiere_32_64< _SIZE_ >::faces(), Domaine_32_64< _SIZE_ >::faces_bord(), Domaine_32_64< _SIZE_ >::faces_raccord(), Domaine_32_64< _SIZE_ >::les_elems(), Faces_32_64< _SIZE_ >::nb_faces(), Frontiere_32_64< _SIZE_ >::nommer(), and Faces_32_64< _SIZE_ >::typer().
Referenced by extruder().
Member Data Documentation
info_obj
const Type_info Extruder_en20::info_obj static
direction
ArrOfDouble Extruder_en20::direction protected
Referenced by extruder(), Extruder_en20(), interpreter_(), and setDirection().
NZ
int Extruder_en20::NZ = -10 protected
Referenced by extruder(), interpreter_(), and setNbTranches().