TrioCFD: Matrice_Morse_Sym Class Reference
Matrice_Morse_Sym Class Reference
#include <Matrice_Morse_Sym.h>
Public Member Functions
DoubleTab & ajouter_multTab_ (const DoubleTab &, DoubleTab &) const override
DoubleVect & ajouter_multvect_ (const DoubleVect &, DoubleVect &) const override
DoubleVect & ajouter_multvectT_ (const DoubleVect &, DoubleVect &) const override
void compacte (int elim_coeff_nul=0)
const Type_info * get_info () const override
int inverse (const DoubleVect &, DoubleVect &, double) const override
Matrice_Morse_Sym (const Matrice_Morse &)
Matrice_Morse_Sym (const Matrice_Morse_Sym &)
Matrice_Morse_Sym (int, int, const IntLists &, const DoubleLists &, const DoubleVect &)
Matrice_Morse_Sym & operator*= (double)
Matrice_Morse_Sym operator- () const
Matrice_Morse_Sym & operator= (const Matrice_Morse_Sym &)
Public Member Functions inherited from Matrice_Morse
Matrice_Morse & affecte_prod (const Matrice_Morse &A, const Matrice_Morse &B)
DoubleTab & ajouter_multTab_ (const DoubleTab &, DoubleTab &) const override
DoubleVect & ajouter_multvect_ (const DoubleVect &, DoubleVect &) const override
DoubleVect & ajouter_multvectT_ (const DoubleVect &, DoubleVect &) const override
void compacte (int elim_coeff_nul=0)
void dimensionner (const IntTab &)
const Type_info * get_info () const override
virtual int inverse (const DoubleVect &, DoubleVect &, double) const
Matrice_Morse (const Matrice_Morse &)
Matrice_Morse (int n, int m, int nnz)
Matrice_Morse (int n, int nnz)
Matrice_Morse & operator*= (const DoubleVect &)
Matrice_Morse & operator*= (double)
Matrice_Morse & operator+= (const Matrice_Morse &)
Matrice_Morse operator- () const
Matrice_Morse & operator/= (double)
Matrice_Morse & operator= (const Matrice_Morse &)
int ordre () const override
virtual Matrice_Morse & transpose (const Matrice_Morse &a)
Public Member Functions inherited from Matrice_Base
virtual DoubleTab & ajouter_multTab (const DoubleTab &, DoubleTab &r) const
virtual DoubleVect & ajouter_multvect (const DoubleVect &x, DoubleVect &r) const
virtual DoubleVect & ajouter_multvectT (const DoubleVect &x, DoubleVect &r) const
const Type_info * get_info () const override
virtual DoubleTab & multTab (const DoubleTab &, DoubleTab &r) const
virtual DoubleVect & multvect (const DoubleVect &, DoubleVect &) const
virtual DoubleVect & multvectT (const DoubleVect &, DoubleVect &) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Friends
Matrice_Morse_Sym operator* (const Matrice_Morse_Sym &, double)
Matrice_Morse_Sym operator* (double, const Matrice_Morse_Sym &)
Matrice_Morse_Sym operator+ (const Matrice_Morse_Sym &, const Matrice_Morse_Sym &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
Symetrique: on ne stocke que la partie triangulaire superieure de la matrice. Important: Tous les coefficients diagonaux doivent etre stockes meme s'ils sont nuls (hypothese TRUST pour plusieurs methodes dont multvect). Cette classe derive de Matrice_Morse et Matrice_Sym.
See also
Matrice_Morse Matrice_Sym
Constructor & Destructor Documentation
~Matrice_Morse_Sym()
Matrice_Morse_Sym::~Matrice_Morse_Sym ()
Matrice_Morse_Sym() [1/5]
Matrice_Morse_Sym::Matrice_Morse_Sym (int n1 = 1, int n2 = 1) inline
References Matrice_Morse::symetrique_.
Matrice_Morse_Sym() [2/5]
Matrice_Morse_Sym::Matrice_Morse_Sym (int n1, int n2, const IntLists & voisins, const DoubleLists & valeurs, const DoubleVect & terme_diag)
Constructeur d'une Matrice_Morse_Sym comportant n1 lignes et pouvant stocker n2 elements non-nuls (au maximum).
Les elements de la matrice et la table des connectivites sont donnes dans les 3 derniers parametres.
Parameters
(int n1) le nombre de ligne de la matrice
(int n2) le nombre d'element non nuls stockable par la matrice
(IntLists& voisins) liste des voisins de chaque lignes
(DoubleLists& valeurs) liste des valeurs
(DoubleVect& terme_diag) le vecteur des termes diagonaux
References Matrice_Morse::morse_matrix_structure_has_changed_, Matrice_Morse::remplir(), and Matrice_Morse::symetrique_.
Matrice_Morse_Sym() [3/5]
Matrice_Morse_Sym::Matrice_Morse_Sym (const Matrice & A)
References Matrice_Morse::morse_matrix_structure_has_changed_, Matrice_Morse::symetrique_, and TRUST_Deriv< _CLASSE_ >::valeur().
Matrice_Morse_Sym() [4/5]
Matrice_Morse_Sym::Matrice_Morse_Sym (const Matrice_Morse & A)
Constructeur d'une Matrice_Morse_Sym par copie d'une Matrice_Morse.
Parameters
(Matrice_Morse& acopier) la matrice a copier
References compacte(), Matrice_Morse::morse_matrix_structure_has_changed_, Matrice_Morse::partie_sup(), and Matrice_Morse::symetrique_.
Matrice_Morse_Sym() [5/5]
Matrice_Morse_Sym::Matrice_Morse_Sym (const Matrice_Morse_Sym & acopier)
Constructeur d'une Matrice_Morse_Sym par copie d'une Matrice_Morse.
Parameters
(Matrice_Morse& acopier) la matrice a copier
References Matrice_Sym::get_est_definie(), Matrice_Morse::morse_matrix_structure_has_changed_, Matrice_Sym::set_est_definie(), and Matrice_Morse::symetrique_.
Member Function Documentation
cree_instance()
Objet_U * Matrice_Morse_Sym::cree_instance () static
taille_memoire()
unsigned Matrice_Morse_Sym::taille_memoire () const override virtual
Reimplemented from Matrice_Morse.
duplique()
int Matrice_Morse_Sym::duplique () const override virtual
Reimplemented from Matrice_Morse.
info()
const Type_info * Matrice_Morse_Sym::info () static
get_info()
const Type_info * Matrice_Morse_Sym::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Matrice_Morse.
self_cast() [1/2]
Matrice_Morse_Sym & Matrice_Morse_Sym::self_cast (Objet_U & r) static
self_cast() [2/2]
const Matrice_Morse_Sym & Matrice_Morse_Sym::self_cast (const Objet_U & r) static
printOn()
Sortie & Matrice_Morse_Sym::printOn (Sortie & s) const override protected virtual
Ecrit les trois tableaux de la structure de stockage Morse sur un flot de sortie.
Parameters
(Sortie& s) un flot de sortie
Returns
(Sortie& s) le flot de sortie modifie
Reimplemented from Matrice_Morse.
References Matrice_Sym::get_est_definie(), and Matrice_Morse::printOn().
readOn()
Entree & Matrice_Morse_Sym::readOn (Entree & s) override protected virtual
NON CODE.
Parameters
(Entree& s) un flot d'entree
Returns
(Entree& s) le flot d'entree
Exceptions
NON CODE
Reimplemented from Matrice_Morse.
References Matrice_Morse::readOn(), and Matrice_Sym::set_est_definie().
operator=() [1/3]
Matrice_Morse_Sym & Matrice_Morse_Sym::operator= (const Matrice_Morse_Sym & a)
Operateur d'affectatiob d'une Matrice_Morse_Sym dans une Matrice_Morse_Sym.
Parameters
(Matrice_Morse_Sym& a) la partie droite de l'affectation
Returns
(Matrice_Morse_Sym&) le resultat de l'affectation (*this)
References Matrice_Morse::coeff_, Matrice_Morse::get_coeff(), Matrice_Sym::get_est_definie(), Matrice_Morse::get_tab1(), Matrice_Morse::get_tab2(), Matrice_Base::is_stencil_up_to_date(), Matrice_Base::is_stencil_up_to_date_, Matrice_Morse::m_, Matrice_Morse::morse_matrix_structure_has_changed_, Matrice_Morse::nb_colonnes(), Matrice_Sym::set_est_definie(), Matrice_Morse::tab1_, and Matrice_Morse::tab2_.
operator=() [2/3]
Matrice_Morse_Sym & Matrice_Morse_Sym::operator= (const Matrice_Morse & A)
References Matrice_Morse::coeff_, compacte(), Matrice_Morse::get_coeff(), Matrice_Morse::get_symmetric(), Matrice_Morse::get_tab1(), Matrice_Morse::get_tab2(), Matrice_Base::is_stencil_up_to_date(), Matrice_Base::is_stencil_up_to_date_, Matrice_Morse::m_, Matrice_Morse::morse_matrix_structure_has_changed_, Matrice_Morse::nb_colonnes(), Matrice_Morse::partie_sup(), Matrice_Morse::symetrique_, Matrice_Morse::tab1_, and Matrice_Morse::tab2_.
operator=() [3/3]
Matrice_Morse_Sym & Matrice_Morse_Sym::operator= (const Matrice & A)
References Matrice_Morse::morse_matrix_structure_has_changed_, and TRUST_Deriv< _CLASSE_ >::valeur().
operator*=()
Matrice_Morse_Sym & Matrice_Morse_Sym::operator*= (double x)
NE FAIT RIEN : NON CODE.
Parameters
(double)
Returns
(Matrice_Morse_Sym)
Exceptions
NON CODE
References scale().
scale()
void Matrice_Morse_Sym::scale (const double x) override virtual
Reimplemented from Matrice_Morse.
References Matrice_Morse::coeff_.
Referenced by operator*=().
get_stencil()
void Matrice_Morse_Sym::get_stencil (IntTab & stencil) const override virtual
Reimplemented from Matrice_Morse.
References assert_check_symmetric_morse_matrix_structure(), get_symmetric_stencil(), Matrice_Morse::nb_lignes(), and Matrice_Sym::unsymmetrize_stencil().
get_symmetric_stencil()
void Matrice_Morse_Sym::get_symmetric_stencil (IntTab & stencil) const override virtual
Reimplemented from Matrice_Base.
References TRUSTTab< _TYPE_, _SIZE_ >::append_line(), assert_check_symmetric_morse_matrix_structure(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Matrice_Morse::nb_lignes(), TRUSTArray< _TYPE_, _SIZE_ >::ordonne_array(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), Matrice_Morse::tab1_, and Matrice_Morse::tab2_.
Referenced by get_stencil(), and Matrice_Base::get_symmetric_stencil().
get_stencil_and_coefficients()
void Matrice_Morse_Sym::get_stencil_and_coefficients (IntTab & stencil, ArrOfDouble & coefficients) const override virtual
Reimplemented from Matrice_Morse.
References assert_check_symmetric_morse_matrix_structure(), get_symmetric_stencil_and_coefficients(), Matrice_Morse::nb_lignes(), and Matrice_Sym::unsymmetrize_stencil_and_coefficients().
get_symmetric_stencil_and_coefficients()
void Matrice_Morse_Sym::get_symmetric_stencil_and_coefficients (IntTab & stencil, ArrOfDouble & coefficients) const override virtual
Reimplemented from Matrice_Base.
References TRUSTArray< _TYPE_, _SIZE_ >::append_array(), TRUSTTab< _TYPE_, _SIZE_ >::append_line(), assert_check_symmetric_morse_matrix_structure(), Matrice_Morse::coeff_, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Matrice_Morse::nb_lignes(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), Matrice_Morse::tab1_, and Matrice_Morse::tab2_.
Referenced by get_stencil_and_coefficients(), and Matrice_Base::get_symmetric_stencil_and_coefficients().
operator-()
Matrice_Morse_Sym Matrice_Morse_Sym::operator- () const
Operateur de negation unaire, renvoie l'opposee de la matrice: - A.
Appelle operator*(const Matrice_Morse_Sym&,double)
ajouter_multTab_()
DoubleTab & Matrice_Morse_Sym::ajouter_multTab_ (const DoubleTab & x, DoubleTab & resu) const override virtual
Operation de multiplication-accumulation (saxpy) matrice matrice (matrice represente par un tableau)
Operation: RESU = RESU + A*X
Parameters
(DoubleTab& x) la matrice a multiplier
(DoubleTab& resu) la matrice resultat de l'operation
Returns
(DoubleTab&) la matrice resultat de l'operation
Exceptions
taille du resultat incompatible avec la taille de x
Reimplemented from Matrice_Morse.
References Matrice_Base::ajouter_multvect(), assert_check_symmetric_morse_matrix_structure(), Matrice_Morse::coeff_, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Matrice_Morse::nb_lignes(), Matrice_Morse::tab1_, and Matrice_Morse::tab2_.
ajouter_multvect_()
DoubleVect & Matrice_Morse_Sym::ajouter_multvect_ (const DoubleVect & x, DoubleVect & resu) const override virtual
Operation de multiplication-accumulation (saxpy) matrice vecteur.
Operation: resu = resu + A*x
Parameters
(DoubleVect& x) le vecteur a multiplier
(DoubleVect& resu) le vecteur resultat de l'operation
Returns
(DoubleVect&) le vecteur resultat de l'operation
Reimplemented from Matrice_Morse.
References TRUSTArray< _TYPE_, _SIZE_ >::addr(), assert_check_symmetric_morse_matrix_structure(), Matrice_Morse::coeff_, Matrice_Morse::get_coeff(), Matrice_Morse::get_tab1(), Matrice_Morse::get_tab2(), Matrice_Morse::m_, Matrice_Morse::nb_lignes(), TRUSTVect< _TYPE_, _SIZE_ >::size(), TRUSTVect< _TYPE_, _SIZE_ >::size_totale(), Matrice_Morse::tab1_, and Matrice_Morse::tab2_.
ajouter_multvectT_()
DoubleVect & Matrice_Morse_Sym::ajouter_multvectT_ (const DoubleVect & x, DoubleVect & resu) const override virtual
Operation de multiplication-accumulation (saxpy) matrice vecteur, par la matrice transposee.
Operation: resu = resu + A^{T}*x
Parameters
(DoubleVect& x) le vecteur a multiplier
(DoubleVect& resu) le vecteur resultat de l'operation
Returns
(DoubleVect&) le vecteur resultat de l'operation
Reimplemented from Matrice_Morse.
References Process::exit().
multvect_et_prodscal()
double Matrice_Morse_Sym::multvect_et_prodscal (const DoubleVect & x, DoubleVect & resu) const virtual
References TRUSTArray< _TYPE_, _SIZE_ >::addr(), assert_check_symmetric_morse_matrix_structure(), Matrice_Morse::get_coeff(), Matrice_Morse::get_tab1(), Matrice_Morse::get_tab2(), Matrice_Morse::m_, Matrice_Morse::nb_lignes(), TRUSTVect< _TYPE_, _SIZE_ >::size(), and TRUSTVect< _TYPE_, _SIZE_ >::size_totale().
inverse() [1/2]
int Matrice_Morse_Sym::inverse (const DoubleVect & secmem, DoubleVect & solution, double coeff_seuil) const override virtual
Calcule la solution du systeme lineaire: A * solution = secmem.
La methode utilisee est GMRES preconditionnee avec ILUT. ATTENTION: cette methode n'a vraisemblablement jamais ete testee en parallele
Parameters
(DoubleVect& secmem) le second membre du systeme lineaire
(DoubleVect& solution) la solution du systeme
(double coeff_seuil)
Returns
(int) renvoie toujours 1
Exceptions
Erreur dans ilut 'matrix may be wrong' dixit SAAD
Erreur dans ilut : debordement dans L
Erreur dans ilut : debordement dans U
Valeur illegale de lfil : sans doute ecrasement memoire
Ligne vide rencontree
Pivot nul rencontre ! au pas
Il s'est passe quelque chose de bizarre : je prefere tout arreter.
Reimplemented from Matrice_Morse.
References Process::exit().
inverse() [2/2]
int Matrice_Morse_Sym::inverse (const DoubleVect & secmem, DoubleVect & solution, double coeff_seuil, int max_iter) const override virtual
Reimplemented from Matrice_Morse.
References Process::exit().
imprimer_formatte()
Sortie & Matrice_Morse_Sym::imprimer_formatte (Sortie & s) const override virtual
Reimplemented from Matrice_Morse.
References Matrice_Morse::imprimer_formatte().
Referenced by Assembleur_P_EF::assembler_mat(), Matrice_Bloc_Sym::BlocSymToMatMorseSym(), Solv_Cholesky::Fact_Cholesky(), and Op_Diff_RotRot::tester().
compacte()
void Matrice_Morse_Sym::compacte (int elim_coeff_nul = 0)
Suppression des doublons on ordonne tab2;.
Verification de la diagonale: tous ses elements doivent etre stockes
References Matrice_Morse::coeff_, Matrice_Morse::compacte(), Matrice_Morse::morse_matrix_structure_has_changed_, Matrice_Morse::nb_lignes(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), Matrice_Morse::tab1_, and Matrice_Morse::tab2_.
Referenced by Op_Dift_VEF_P1NCP1B_Face::calculer_gradient_som(), Domaine_ALE::laplacien(), Matrice_Morse_Sym(), and operator=().
renumerote()
void Matrice_Morse_Sym::renumerote () const
Renumerotation d'une matrice afin de reduire la largeur de bande.
References TRUSTArray< _TYPE_, _SIZE_ >::addr(), Matrice_Morse::get_coeff(), Matrice_Morse::get_tab1(), Matrice_Morse::get_tab2(), Matrice_Morse::largeur_de_bande(), Matrice_Morse::morse_matrix_structure_has_changed_, Matrice_Morse::ordre(), Matrice_Morse::partie_sup(), permutation(), permutation_inverse(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), Matrice_Morse::transpose(), Objet_U_ptr::typer(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by Solv_Cholesky::Cholesky().
matrice_renumerotee() [1/2]
Matrice & Matrice_Morse_Sym::matrice_renumerotee () inline
Referenced by Solv_Cholesky::Cholesky().
matrice_renumerotee() [2/2]
Matrice & Matrice_Morse_Sym::matrice_renumerotee () const inline
permutation() [1/2]
ArrOfInt & Matrice_Morse_Sym::permutation () inline
Referenced by Solv_Cholesky::Cholesky(), and renumerote().
permutation_inverse() [1/2]
ArrOfInt & Matrice_Morse_Sym::permutation_inverse () inline
Referenced by Solv_Cholesky::Cholesky(), and renumerote().
permutation() [2/2]
ArrOfInt & Matrice_Morse_Sym::permutation () const inline
permutation_inverse() [2/2]
ArrOfInt & Matrice_Morse_Sym::permutation_inverse () const inline
check_symmetric_morse_matrix_structure()
bool Matrice_Morse_Sym::check_symmetric_morse_matrix_structure () const
References Matrice_Morse::check_morse_matrix_structure(), Matrice_Morse::nb_lignes(), Matrice_Morse::tab1_, and Matrice_Morse::tab2_.
Referenced by assert_check_sorted_symmetric_morse_matrix_structure(), and assert_check_symmetric_morse_matrix_structure().
check_sorted_symmetric_morse_matrix_structure()
bool Matrice_Morse_Sym::check_sorted_symmetric_morse_matrix_structure () const
References Matrice_Morse::check_sorted_morse_matrix_structure(), Matrice_Morse::nb_lignes(), Matrice_Morse::tab1_, and Matrice_Morse::tab2_.
Referenced by Matrix_tools::add_symmetric_scaled_matrices().
assert_check_symmetric_morse_matrix_structure()
void Matrice_Morse_Sym::assert_check_symmetric_morse_matrix_structure () const
References check_symmetric_morse_matrix_structure(), Process::exit(), and Matrice_Morse::morse_matrix_structure_has_changed_.
Referenced by ajouter_multTab_(), ajouter_multvect_(), get_stencil(), get_stencil_and_coefficients(), get_symmetric_stencil(), get_symmetric_stencil_and_coefficients(), and multvect_et_prodscal().
assert_check_sorted_symmetric_morse_matrix_structure()
void Matrice_Morse_Sym::assert_check_sorted_symmetric_morse_matrix_structure () const
References check_symmetric_morse_matrix_structure(), Process::exit(), and Matrice_Morse::morse_matrix_structure_has_changed_.
Friends And Related Function Documentation
operator+
Matrice_Morse_Sym operator+ (const Matrice_Morse_Sym & , const Matrice_Morse_Sym &) friend
Fonction (hors classe) amie de la classe Matrice_Morse_Sym NE FAIT RIEN : NON CODE.
Parameters
(Matrice_Morse_Sym&)
(Matrice_Morse_Sym&)
Returns
(Matrice_Morse_Sym)
operator* [1/2]
Matrice_Morse_Sym operator* (const Matrice_Morse_Sym & , double) friend
Fonction (hors classe) amie de la classe Matrice_Morse_Sym Simple appel a operator*(double,const Matrice_Morse_Sym&) (qui est NON CODE)
Parameters
(Matrice_Morse_Sym& A) la matrice a multiplier par x
(double x) un scalaire
Returns
(Matrice_Morse_Sym) le resultat de l'appel sous-jacent
operator* [2/2]
Matrice_Morse_Sym operator* (double , const Matrice_Morse_Sym &) friend
Fonction (hors classe) amie de la classe Matrice_Morse_Sym NE FAIT RIEN : NON CODE.
Parameters
(double)
(Matrice_Morse_Sym& A)
Returns
(Matrice_Morse_Sym)
Exceptions
NON CODE
Member Data Documentation
info_obj
const Type_info Matrice_Morse_Sym::info_obj static