TrioCFD: Desc_Structure_FT Class Reference
Desc_Structure_FT Class Reference
#include <Descripteur_FT.h>
Public Member Functions
int check () const
void echanger_elements (const ArrOfInt &nouveau_pe)
Descripteur_FT & espace_distant ()
const Descripteur_FT & espace_distant () const
Descripteur_FT & espace_virtuel ()
const Descripteur_FT & espace_virtuel () const
const Type_info * get_info () const override
void remplir_element_pe (ArrOfInt &element_pe) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
Desc_Structure_FT est un descripteur adapte aux maillages lagrangiens des interfaces. Il contient un tableau d'elements et non une serie d'intervalles (le plus souvent, les elements distants et virtuels ne sont pas contigus dans les tableaux). De plus, l'allocation memoire est specialisee (les tableaux croissent geometriquement mais ne decroissent jamais, leur taille est generalement superieure au nombre d'elements qu'ils contiennent).
Definition de la correspondance: Pour deux processeurs numerotes A et B quelconques et un indice i, on considere les deux numeros suivants nA = (Sur processeur A, espace_distant.elements(B) [i]) nB = (Sur processeur B, espace_virtuel.elements(A) [i]) On dit que l'espace distant et l'espace virtuel sont en correspondance si l'element nA sur le processeur A et l'element nB sur le processeur B representent le meme element (sommet ou facette ...)
Member Enumeration Documentation
Status
enum Desc_Structure_FT::Status protected
Enumerator
BAD
OK
Constructor & Destructor Documentation
~Desc_Structure_FT()
Desc_Structure_FT::~Desc_Structure_FT ()
Desc_Structure_FT()
Desc_Structure_FT::Desc_Structure_FT ()
Member Function Documentation
cree_instance()
Objet_U * Desc_Structure_FT::cree_instance () static
taille_memoire()
unsigned Desc_Structure_FT::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Desc_Structure_FT::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Desc_Structure_FT::info () static
get_info()
const Type_info * Desc_Structure_FT::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
Desc_Structure_FT & Desc_Structure_FT::self_cast (Objet_U & r) static
self_cast() [2/2]
const Desc_Structure_FT & Desc_Structure_FT::self_cast (const Objet_U & r) static
printOn()
Sortie & Desc_Structure_FT::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
References espace_distant_, espace_virtuel_, and Objet_U::que_suis_je().
readOn()
Entree & Desc_Structure_FT::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
References check(), espace_distant_, espace_virtuel_, Process::exit(), Objet_U::que_suis_je(), and reset().
reset()
void Desc_Structure_FT::reset ()
References BAD, espace_distant_, espace_virtuel_, Descripteur_FT::reset(), and status_md_.
Referenced by Maillage_FT_IJK::lire_maillage_ft_dans_lata(), Maillage_FT_Disc::nettoyer_maillage(), readOn(), Maillage_FT_Disc::reset(), and Cut_cell_FT_Disc::update().
echange_espace_virtuel() [1/4]
void Desc_Structure_FT::echange_espace_virtuel (ArrOfDouble & tab) const
References collecter_espace_virtuel(), and MD_Vector_tools::ECHANGE_EV.
Referenced by Maillage_FT_Disc::ajouter_maillage(), FT_Field::avancer_en_temps(), Maillage_FT_Disc::calcul_courbure_sommets(), Remaillage_FT::calculer_barycentre_facettes_voisines(), Marching_Cubes::calculer_coord_noeuds(), Maillage_FT_Disc::calculer_costheta_minmax(), Remaillage_FT::calculer_differentielle_volume(), Remaillage_FT::calculer_variation_volume(), IJK_Interfaces::calculer_vecteurs_de_deplacement_rigide(), Transport_Interfaces_FT_Disc::calculer_vitesse_transport_interpolee(), Maillage_FT_Disc::check_mesh(), Maillage_FT_Disc::check_sommets(), Maillage_FT_IJK::check_sommets(), IJK_Interfaces::compute_external_forces_(), Operator_FT_Disc::Compute_interfaciale_source(), Marching_Cubes::correspondance_espaces_distant_virtuel(), Maillage_FT_Disc::corriger_proprietaires_facettes(), Maillage_FT_IJK::creer_facettes_virtuelles(), Maillage_FT_Disc::deplacer_sommets(), Maillage_FT_IJK::deplacer_sommets(), Cut_cell_FT_Disc::echange_espace_virtuel(), FT_Field::echange_espace_virtuel(), Maillage_FT_Disc::echanger_sommets_PE(), Sauvegarde_Reprise_Maillage_FT::ecrire_xyz(), Parcours_interface::eloigner_sommets_des_faces(), Operator_FT_Disc::Facette_to_Sommets(), FT_Field::initialize(), Sauvegarde_Reprise_Maillage_FT::lire_xyz(), Remaillage_FT::lisser_dvolume(), Maillage_FT_Disc::nettoyer_maillage(), Maillage_FT_Disc::nettoyer_noeuds_virtuels_et_frontieres(), Maillage_FT_Disc::nettoyer_phase(), Operator_FT_Disc::Operator_Gradient_FT_sommets(), Operator_FT_Disc::Operator_integral_bord_facette_phi_p_dl(), Operator_FT_Disc::Operator_Laplacian_FT_element(), Parcours_interface::parcourir(), FT_Field::passer_variable_extensive(), FT_Field::passer_variable_intensive(), Remaillage_FT::redistribuer_sommets(), Remaillage_FT::regulariser_courbure(), Maillage_FT_Disc::remplir_structure(), IJK_Interfaces::RK3_G_store_vi_echange_esp_vect(), Operator_FT_Disc::Sommets_to_Facettes(), Remaillage_FT::supprimer_doublons_facettes(), Remaillage_FT::supprimer_petites_aretes(), Remaillage_FT_IJK::supprimer_petites_aretes(), Remaillage_FT::traite_decollement(), Transport_Interfaces_FT_Disc::transfert_conservatif_eulerien_vers_lagrangien_sommets(), IJK_Interfaces::transporter_maillage_deformation(), IJK_Interfaces::transporter_maillage_remaillage(), FT_Field::update_Field_sommets(), FT_Field::update_sigma_and_interfacial_source_term_sommet(), and Maillage_FT_Disc::update_tableau_apres_transport().
echange_espace_virtuel() [2/4]
void Desc_Structure_FT::echange_espace_virtuel (ArrOfInt & tab) const
References collecter_espace_virtuel(), and MD_Vector_tools::ECHANGE_EV.
echange_espace_virtuel() [3/4]
void Desc_Structure_FT::echange_espace_virtuel (ArrOfDouble & tab, MD_Vector_tools::Operations_echange op) const
References collecter_espace_virtuel().
echange_espace_virtuel() [4/4]
void Desc_Structure_FT::echange_espace_virtuel (ArrOfInt & tab, MD_Vector_tools::Operations_echange op) const
References collecter_espace_virtuel().
collecter_espace_virtuel() [1/2]
void Desc_Structure_FT::collecter_espace_virtuel (ArrOfDouble & tab, MD_Vector_tools::Operations_echange op) const
References MD_Vector_tools::echange_espace_virtuel(), md_vector_, OK, TRUSTVect< _TYPE_, _SIZE_ >::ref(), TRUSTVect< _TYPE_, _SIZE_ >::ref_array(), TRUSTVect< _TYPE_, _SIZE_ >::reset(), TRUSTVect< _TYPE_, _SIZE_ >::set_md_vector(), status_md_, and tmp_doublevect_.
Referenced by Maillage_FT_Disc::calcul_courbure_sommets(), Remaillage_FT::calculer_barycentre_facettes_voisines(), Remaillage_FT::calculer_differentielle_volume(), Remaillage_FT::calculer_variation_volume(), FT_Field::champ_sommet_from_facettes(), echange_espace_virtuel(), Operator_FT_Disc::Facette_to_Sommets(), Remaillage_FT::lisser_dvolume(), Operator_FT_Disc::Operator_integral_bord_facette_phi_p_dl(), Remaillage_FT::regulariser_courbure(), Remaillage_FT::supprimer_petites_aretes(), Remaillage_FT_IJK::supprimer_petites_aretes(), Remaillage_FT::traite_decollement(), Transport_Interfaces_FT_Disc::transfert_conservatif_eulerien_vers_lagrangien_sommets(), Remailleur_Collision_FT_Thomas::transport_volume_perdu_sur_sommet(), IJK_Interfaces::transporter_maillage_remaillage(), FT_Field::update_Field_sommets(), and Maillage_FT_Disc::update_tableau_apres_transport().
collecter_espace_virtuel() [2/2]
void Desc_Structure_FT::collecter_espace_virtuel (ArrOfInt & tab, MD_Vector_tools::Operations_echange op) const
References MD_Vector_tools::echange_espace_virtuel(), md_vector_, OK, TRUSTVect< _TYPE_, _SIZE_ >::ref(), TRUSTVect< _TYPE_, _SIZE_ >::ref_array(), TRUSTVect< _TYPE_, _SIZE_ >::reset(), TRUSTVect< _TYPE_, _SIZE_ >::set_md_vector(), status_md_, and tmp_intvect_.
espace_distant() [1/2]
Descripteur_FT & Desc_Structure_FT::espace_distant ()
Renvoie une reference non-const a l'espace distant.
Le statut du descripteur passe a BAD => il faudra recalculer le schema de com.
References BAD, espace_distant_, and status_md_.
Referenced by Maillage_FT_Disc::ajouter_maillage(), calcul_schema_comm(), Maillage_FT_Disc::check_mesh(), Maillage_FT_Disc::check_sommets(), Maillage_FT_IJK::check_sommets(), Marching_Cubes::construire_noeuds_uniques(), Maillage_FT_Disc::creer_facettes_virtuelles(), Maillage_FT_Disc::creer_sommets_virtuels(), Cut_cell_FT_Disc::initialise_communications(), Maillage_FT_Disc::nettoyer_maillage(), Maillage_FT_Disc::nettoyer_noeuds_virtuels_et_frontieres(), Maillage_FT_Disc::nettoyer_phase(), and Maillage_FT_Disc::remplir_structure().
espace_distant() [2/2]
const Descripteur_FT & Desc_Structure_FT::espace_distant () const
Renvoie une reference const a l'espace distant.
Le statut reste OK.
References espace_distant_.
espace_virtuel() [1/2]
Descripteur_FT & Desc_Structure_FT::espace_virtuel ()
Renvoie une reference non-const a l'espace virtuel.
Le statut du descripteur passe a BAD => il faudra recalculer le schema de com.
References BAD, espace_virtuel_, and status_md_.
Referenced by Maillage_FT_Disc::ajouter_maillage(), calcul_schema_comm(), Maillage_FT_Disc::check_mesh(), Maillage_FT_Disc::check_sommets(), Maillage_FT_IJK::check_sommets(), Marching_Cubes::construire_noeuds_uniques(), Maillage_FT_Disc::convertir_numero_distant_local(), Marching_Cubes::correspondance_espaces_distant_virtuel(), Maillage_FT_Disc::creer_facettes_virtuelles(), Maillage_FT_Disc::creer_sommets_virtuels(), Cut_cell_FT_Disc::initialise_communications(), Maillage_FT_Disc::nettoyer_maillage(), Maillage_FT_Disc::nettoyer_noeuds_virtuels_et_frontieres(), Maillage_FT_Disc::nettoyer_phase(), Maillage_FT_Disc::preparer_tableau_avant_transport(), and Maillage_FT_Disc::remplir_structure().
espace_virtuel() [2/2]
const Descripteur_FT & Desc_Structure_FT::espace_virtuel () const
Renvoie une reference const a l'espace virtuel.
Le statut reste OK.
References espace_virtuel_.
calcul_schema_comm()
void Desc_Structure_FT::calcul_schema_comm (const int nb_items_tot)
References Descripteur_FT::all_elements(), blocs_to_recv_, MD_Vector::copy(), espace_distant(), espace_virtuel(), md_vector_, Process::nproc(), OK, Descripteur_FT::pe_voisins(), pe_voisins_, TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), schema_comm_, schema_comm_inverse_, Schema_Comm::set_send_recv_pe_list(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and status_md_.
Referenced by Maillage_FT_Disc::ajouter_maillage(), Marching_Cubes::construire_noeuds_uniques(), Marching_Cubes::correspondance_espaces_distant_virtuel(), Maillage_FT_Disc::creer_facettes_virtuelles(), Maillage_FT_Disc::creer_sommets_virtuels(), Remaillage_FT::diviser_grandes_aretes(), Remaillage_FT_IJK::diviser_grandes_aretes(), echanger_elements(), Cut_cell_FT_Disc::initialise_communications(), Maillage_FT_IJK::lire_maillage_ft_dans_lata(), Sauvegarde_Reprise_Maillage_FT::lire_xyz(), Remaillage_FT::marquer_aretes(), Maillage_FT_Disc::nettoyer_maillage(), Maillage_FT_Disc::nettoyer_noeuds_virtuels_et_frontieres(), Maillage_FT_Disc::nettoyer_phase(), Maillage_FT_Disc::remplir_structure(), and Maillage_FT_Disc::reprendre().
echanger_elements()
void Desc_Structure_FT::echanger_elements (const ArrOfInt & nouveau_pe)
Correction des espaces distants et virtuels lors d'un changement de proprietaire (noeud ou facette).
Les operations sont les suivantes :
sur l'ancien proprietaire de l'element, on retire l'element de l'espace distant.
sur le nouveau proprietaire, on ajoute l'element a l'espace distant, pour tous les PEs ou cet element est virtuel.
sur les PEs ou cet element est virtuel, on retire l'element de la liste d'elements virtuels de l'ancien PE et on l'ajoute a la fin de la liste d'elements virtuels du nouveau proprietaire. L'ordre d'ajout des elements dans les espaces distants et virtuels est identique pour que les espaces soient en correspondance.
Parameters
(nouveau_pe) tableau de taille nb_sommets ou nb_facettes, qui contient le numero du nouveau pe proprietaire, ou -1 si l'element ne change pas de main. L'espace virtuel de ce tableau doit etre a jour (echange_espace_virtuel realise).
References Descripteur_FT::ajoute_element(), BAD, Schema_Comm::begin_comm(), Descripteur_FT::calcul_liste_pe_voisins(), calcul_schema_comm(), check(), Comm_Group::check_enabled(), Schema_Comm::echange_taille_et_messages(), Descripteur_FT::elements(), Schema_Comm::end_comm(), Entree::eof(), espace_distant_, espace_virtuel_, Process::me(), Descripteur_FT::pe_voisins(), Schema_Comm::recv_buffer(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), Descripteur_FT::retirer_elements(), schema_comm_, Schema_Comm::send_buffer(), Schema_Comm::set_send_recv_pe_list(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and status_md_.
Referenced by Maillage_FT_Disc::corriger_proprietaires_facettes(), Maillage_FT_IJK::deplacer_sommets(), and Maillage_FT_Disc::echanger_sommets_PE().
remplir_element_pe()
void Desc_Structure_FT::remplir_element_pe (ArrOfInt & element_pe) const
remplit le tableau qui donne pour chaque element le numero du pe proprietaire.
Le tableau fourni doit avoir la bonne taille (nombre d'elements = sommets ou facettes par ex.) Ce tableau est rempli en utilisant l'espace virtuel (tous les elements sont a moi, sauf ceux qui sont dans l'espace virtuel).
References Descripteur_FT::elements(), espace_virtuel_, Process::me(), Descripteur_FT::pe_voisins(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by Maillage_FT_Disc::check_mesh(), Maillage_FT_Disc::check_sommets(), Maillage_FT_IJK::check_sommets(), Maillage_FT_Disc::corriger_proprietaires_facettes(), Maillage_FT_IJK::deplacer_sommets(), Maillage_FT_Disc::echanger_sommets_PE(), Maillage_FT_Disc::facette_PE_owner(), and Maillage_FT_Disc::remplir_structure().
check()
int Desc_Structure_FT::check () const
Verification de la coherence de la structure (graphe des voisins et taille des espaces virtuels et distants)
On envoie tout au processeur 0.
References Process::barrier(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Descripteur_FT::elements(), espace_distant_, espace_virtuel_, Process::exit(), Process::je_suis_maitre(), Process::me(), Process::nproc(), Descripteur_FT::pe_voisins(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by Maillage_FT_Disc::check_mesh(), Maillage_FT_Disc::check_sommets(), Maillage_FT_IJK::check_sommets(), echanger_elements(), and readOn().
schema_comm()
const Schema_Comm & Desc_Structure_FT::schema_comm () const
References OK, schema_comm_, and status_md_.
Referenced by Remaillage_FT::marquer_aretes().
schema_comm_inverse()
const Schema_Comm & Desc_Structure_FT::schema_comm_inverse () const
References OK, schema_comm_inverse_, and status_md_.
Referenced by Maillage_FT_Disc::corriger_proprietaires_facettes(), Maillage_FT_Disc::creer_facettes_virtuelles(), Maillage_FT_Disc::echanger_facettes(), Maillage_FT_Disc::echanger_sommets_PE(), Remaillage_FT::marquer_aretes(), Maillage_FT_Disc::nettoyer_maillage(), Maillage_FT_Disc::nettoyer_noeuds_virtuels_et_frontieres(), and Maillage_FT_Disc::nettoyer_phase().
get_md_vector()
const MD_Vector & Desc_Structure_FT::get_md_vector () const
References md_vector_, OK, and status_md_.
Referenced by Maillage_FT_Disc::creer_tableau_elements(), and Maillage_FT_Disc::creer_tableau_sommets().
Member Data Documentation
info_obj
const Type_info Desc_Structure_FT::info_obj static
espace_distant_
Descripteur_FT Desc_Structure_FT::espace_distant_ protected
Referenced by check(), echanger_elements(), espace_distant(), printOn(), readOn(), and reset().
espace_virtuel_
Descripteur_FT Desc_Structure_FT::espace_virtuel_ protected
Referenced by check(), echanger_elements(), espace_virtuel(), printOn(), readOn(), remplir_element_pe(), and reset().
status_md_
enum Desc_Structure_FT::Status Desc_Structure_FT::status_md_ protected
Referenced by calcul_schema_comm(), collecter_espace_virtuel(), echanger_elements(), espace_distant(), espace_virtuel(), get_md_vector(), reset(), schema_comm(), and schema_comm_inverse().
pe_voisins_
ArrOfInt Desc_Structure_FT::pe_voisins_ protected
Referenced by calcul_schema_comm().
blocs_to_recv_
TRUST_Vector< ArrOfInt > Desc_Structure_FT::blocs_to_recv_ protected
Referenced by calcul_schema_comm().
md_vector_
MD_Vector Desc_Structure_FT::md_vector_ protected
Referenced by calcul_schema_comm(), collecter_espace_virtuel(), and get_md_vector().
tmp_doublevect_
DoubleVect Desc_Structure_FT::tmp_doublevect_ mutable protected
Referenced by collecter_espace_virtuel().
tmp_intvect_
IntVect Desc_Structure_FT::tmp_intvect_ mutable protected
Referenced by collecter_espace_virtuel().
schema_comm_
Schema_Comm Desc_Structure_FT::schema_comm_ protected
Referenced by calcul_schema_comm(), echanger_elements(), and schema_comm().
schema_comm_inverse_
Schema_Comm Desc_Structure_FT::schema_comm_inverse_ protected
Referenced by calcul_schema_comm(), and schema_comm_inverse().