TrioCFD: Modele_turbulence_scal_Schmidt Class Reference
Modele_turbulence_scal_Schmidt Class Reference
#include <Modele_turbulence_scal_Schmidt.h>
Public Member Functions
virtual int a_pour_Champ_Fonc (const Motcle &, TRUST_Ref< Champ_base * > &) const
virtual int comprend_champ (const Motcle &) const
const Type_info * get_info () const override
void mettre_a_jour (double) override
Public Member Functions inherited from Modele_turbulence_scal_diffturb_base
void associer_viscosite_turbulente (const Champ_Fonc_base &)
void completer () override
const Type_info * get_info () const override
int reprendre (Entree &) override
Public Member Functions inherited from Modele_turbulence_scal_base
virtual void associer (const Domaine_dis_base &, const Domaine_Cl_dis_base &)
void associer_eqn (const Equation_base &)
const Type_info * get_info () const override
virtual void imprimer (Sortie &) const
int limpr_nusselt (double, double, double, double) const
int lire_motcle_non_standard (const Motcle &, Entree &) override
Turbulence_paroi_scal_base & loi_paroi ()
const Turbulence_paroi_scal_base & loi_paroi () const
int loi_paroi_non_nulle () const
virtual int preparer_calcul ()
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Champ_Fonc_base & calculer_diffusion_turbulente ()
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
pour la diffusion turbulente: diffu_turb = visco_turb / Sc_turb;
See also
Mod_Turb_scal_diffuturb_base
Constructor & Destructor Documentation
Modele_turbulence_scal_Schmidt()
Modele_turbulence_scal_Schmidt::Modele_turbulence_scal_Schmidt ()
~Modele_turbulence_scal_Schmidt()
Modele_turbulence_scal_Schmidt::~Modele_turbulence_scal_Schmidt ()
Member Function Documentation
cree_instance()
Objet_U * Modele_turbulence_scal_Schmidt::cree_instance () static
taille_memoire()
unsigned Modele_turbulence_scal_Schmidt::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Modele_turbulence_scal_Schmidt::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Modele_turbulence_scal_Schmidt::info () static
get_info()
const Type_info * Modele_turbulence_scal_Schmidt::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Modele_turbulence_scal_diffturb_base.
self_cast() [1/2]
Modele_turbulence_scal_Schmidt & Modele_turbulence_scal_Schmidt::self_cast (Objet_U & r) static
self_cast() [2/2]
const Modele_turbulence_scal_Schmidt & Modele_turbulence_scal_Schmidt::self_cast (const Objet_U & r) static
printOn()
Sortie & Modele_turbulence_scal_Schmidt::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Modele_turbulence_scal_diffturb_base.
References Modele_turbulence_scal_diffturb_base::printOn().
readOn()
Entree & Modele_turbulence_scal_Schmidt::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Modele_turbulence_scal_diffturb_base.
References LeScturb_, and Modele_turbulence_scal_diffturb_base::readOn().
comprend_champ()
int Modele_turbulence_scal_Schmidt::comprend_champ (const Motcle & mot) const virtual
Renvoie 1 si le mot cle passe en parametre est un nom de champ de l'objet.
Parameters
(Motcle& mot) le mot cle a comparer aux noms de champs connus
Returns
(int) 0 si le mot n'est pas un nom de champ 1 sinon
a_pour_Champ_Fonc()
int Modele_turbulence_scal_Schmidt::a_pour_Champ_Fonc (const Motcle & mot, TRUST_Ref< Champ_base * > & ch_ref) const virtual
Renvoie 1 si un champ fonction (Champ_Fonc) du nom specifie est porte par le modele de turbulence.
Renvoie 0 sinon.
Parameters
(Motcle& mot) le nom d'un champ fonction du modele de turbulence
(OBS_PTR(Champ_base)& ch_ref) la reference sur le champ recherche (si il a ete trouve)
Returns
(int) 1 si un champ fonction du nom specifie a ete trouve 0 sinon
References Modele_turbulence_scal_base::diffusivite_turbulente_, and TRUST_Deriv< _CLASSE_ >::valeur().
mettre_a_jour()
void Modele_turbulence_scal_Schmidt::mettre_a_jour (double) override virtual
Calcule le coefficient turbulent utilise dans l equation et la loi de paroi.
Parameters
(double)
Implements Modele_turbulence_scal_base.
References calculer_diffusion_turbulente(), Turbulence_paroi_scal_base::calculer_scal(), Modele_turbulence_scal_base::conductivite_turbulente_, Modele_turbulence_scal_base::diffusivite_turbulente_, TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Modele_turbulence_scal_base::equation(), Modele_turbulence_scal_base::loi_paroi_non_nulle(), Modele_turbulence_scal_base::loipar_, Probleme_base::milieu(), Equation_base::probleme(), and Champ_Don_base::valeurs().
set_param()
void Modele_turbulence_scal_Schmidt::set_param (Param & param) override virtual
Reimplemented from Modele_turbulence_scal_base.
References Param::ajouter(), LeScturb_, and Modele_turbulence_scal_base::set_param().
get_Scturb()
double Modele_turbulence_scal_Schmidt::get_Scturb () const inline
References LeScturb_.
Referenced by Convection_Diffusion_Concentration_Turbulent_FT_Disc::mettre_a_jour_chimie().
calculer_diffusion_turbulente()
Champ_Fonc_base & Modele_turbulence_scal_Schmidt::calculer_diffusion_turbulente () protected
Calcule la diffusion turbulente.
diffusion_turbulente = viscosite_turbulente / Sc_turbulent
Returns
(Champ_Fonc_base&) la diffusion turbulente nouvellement calculee
Exceptions
les champs diffusivite_turbulente et viscosite_turbulente doivent avoir le meme nombre de valeurs nodales
References Champ_base::changer_temps(), Modele_turbulence_scal_base::diffusivite_turbulente_, Modele_turbulence_scal_base::equation(), Process::exit(), Modele_turbulence_scal_diffturb_base::la_viscosite_turbulente_, LeScturb_, TRUSTVect< _TYPE_, _SIZE_ >::size(), and Champ_Don_base::valeurs().
Referenced by mettre_a_jour().
Member Data Documentation
info_obj
const Type_info Modele_turbulence_scal_Schmidt::info_obj static
LeScturb_
double Modele_turbulence_scal_Schmidt::LeScturb_ = 0.7 protected
Referenced by calculer_diffusion_turbulente(), get_Scturb(), readOn(), and set_param().