TrioCFD: Pb_Phase_field Class Reference
Pb_Phase_field Class Reference
#include <Pb_Phase_field.h>
Public Member Functions
void associer_milieu_base (const Milieu_base &) override
const Equation_base & equation (int) const override
Equation_base & equation (int) override
const Type_info * get_info () const override
int nombre_d_equations () const override
int verifier () override
const Type_info * get_info () const override
Public Member Functions inherited from Probleme_base
void abortTimeStep () override
int associer_ (Objet_U &) override
virtual void associer_domaine (const Domaine &)
virtual void associer_milieu_base (const Milieu_base &)
virtual void associer_sch_tps_base (const Schema_Temps_base &)
virtual double calculer_pas_de_temps () const
virtual void completer ()
double computeTimeStep (bool &stop) const override
const Discretisation_base & discretisation () const
virtual void discretiser (Discretisation_base &)
Domaine & domaine ()
const Domaine & domaine () const
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
Equation_base & equation (const Nom &)
const Equation_base & equation (const Nom &) const
TRUST_Ref< Field_base * > findInputField (const Nom &name) const override
virtual void finir ()
double futureTime () const override
const Type_info * get_info () const override
void getInputFieldsNames (Noms &noms) const override
void getOutputFieldsNames (Noms &noms) const override
virtual void imprimer (Sortie &os) const
void initialize () override
bool initTimeStep (double dt) override
bool isStationary () const override
bool iterateTimeStep (bool &converged) override
int limpr () const override
int lsauv () const override
virtual void mettre_a_jour (double temps)
virtual Milieu_base & milieu ()
virtual const Milieu_base & milieu () const
int postraiter (int force=1) override
double presentTime () const override
int reprendre (Entree &) override
void resetTime (double time) override
int sauvegarder (Sortie &) const override
Schema_Temps_base & schema_temps ()
const Schema_Temps_base & schema_temps () const
void terminate () override
bool updateGivenFields () override
void validateTimeStep () override
virtual int verifier ()
Public Member Functions inherited from Probleme_U
virtual void abortTimeStep ()
virtual double computeTimeStep (bool &stop) const
virtual TRUST_Ref< Field_base * > findInputField (const Nom &name) const
virtual double futureTime () const
const Type_info * get_info () const override
virtual void getInputFieldsNames (Noms &noms) const
virtual void getOutputFieldsNames (Noms &noms) const
virtual void initialize ()
virtual bool initTimeStep (double dt)
virtual bool isStationary () const
virtual bool iterateTimeStep (bool &converged)
const Nom & le_nom () const override
void nommer (const Nom &name) override
virtual int postraiter (int force=1)
virtual double presentTime () const
virtual void resetTime (double time)
virtual bool run ()
virtual bool runUntil (double time)
virtual void terminate ()
virtual bool updateGivenFields ()
virtual void validateTimeStep ()
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
d'un ou plusieurs constituants:
Equations de Navier_Stokes en regime laminaire pour un fluide incompressible
Equations de convection-diffusion en regime laminaire En fait si on transporte plusieurs constituants on utilisera une seule equation de convection-diffusion avec une inconnue vectorielle. En general, on couple les 2 equations par l'intermediaire du terme source des forces de volume de Navier_Stokes dans lequel on prend en compte de petites variations de la masse volumique en fonction du ou des constituants
See also
Pb_Fluide_base
Constructor & Destructor Documentation
Pb_Phase_field()
Pb_Phase_field::Pb_Phase_field ()
~Pb_Phase_field()
Pb_Phase_field::~Pb_Phase_field ()
Member Function Documentation
cree_instance()
Objet_U * Pb_Phase_field::cree_instance () static
taille_memoire()
unsigned Pb_Phase_field::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Pb_Phase_field::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Pb_Phase_field::info () static
get_info()
const Type_info * Pb_Phase_field::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Pb_Fluide_base.
self_cast() [1/2]
Pb_Phase_field & Pb_Phase_field::self_cast (Objet_U & r) static
self_cast() [2/2]
const Pb_Phase_field & Pb_Phase_field::self_cast (const Objet_U & r) static
printOn()
Sortie & Pb_Phase_field::printOn (Sortie & os) const override protected virtual
Simple appel a: Pb_Fluide_base::printOn(Sortie&) Ecrit le probleme sur un flot de sortie.
Parameters
(Sortie& os) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Pb_Fluide_base.
References Pb_Fluide_base::printOn().
readOn()
Entree & Pb_Phase_field::readOn (Entree & is) override protected virtual
Simple appel a: Pb_Fluide_base::readOn(Entree&) Lit le probleme a partir d'un flot d'entree.
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Pb_Fluide_base.
References Pb_Fluide_base::readOn().
nombre_d_equations()
int Pb_Phase_field::nombre_d_equations () const override virtual
Renvoie le nombre d'equation, Renvoie 2 car il y a 2 equations a un probleme.
hydraulique avec transport:
l'equation de Navier Stokes
une equation de convection-diffusion (eventuellement vectorielle)
Returns
(int) le nombre d'equation
Implements Probleme_base.
Referenced by typer_lire_milieu().
equation() [1/2]
const Equation_base & Pb_Phase_field::equation (int i) const override virtual
Renvoie l'equation d'hydraulique de type Navier_Stokes_std si i=0 Renvoie l'equation de convection-diffusion de type.
Convection_Diffusion_Concentration si i=1 (l'equation de convection diffusion peut-etre vectorielle) (version const)
Parameters
(int i) l'index de l'equation a renvoyer
Returns
(Equation_base&) l'equation correspondante a l'index
Implements Probleme_base.
References eq_concentration, and eq_hydraulique.
Referenced by typer_lire_milieu().
equation() [2/2]
Equation_base & Pb_Phase_field::equation (int i) override virtual
Renvoie l'equation d'hydraulique de type Navier_Stokes si i=0 Renvoie l'equation de convection-diffusion de type.
Convection_Diffusion_Concentration si i=1 (l'equation de convection diffusion peut-etre vectorielle)
Parameters
(int i) l'index de l'equation a renvoyer
Returns
(Equation_base&) l'equation correspondante a l'index
Implements Probleme_base.
References eq_concentration, and eq_hydraulique.
associer_milieu_base()
void Pb_Phase_field::associer_milieu_base (const Milieu_base & mil) override virtual
Associe un milieu au probleme, Si le milieu est de type.
 - Fluide_Incompressible, il sera associe a l'equation de l'hydraulique
 - Constituant, il sera associe a l'equation de convection-diffusion
Un autre type de milieu provoque une erreur
Parameters
(Milieu_base& mil) le milieu physique a associer au probleme
Exceptions
mauvais type de milieu physique
Reimplemented from Probleme_base.
References Convection_Diffusion_Concentration::associer_milieu_base(), Navier_Stokes_std::associer_milieu_base(), eq_concentration, eq_hydraulique, Process::exit(), and Objet_U::que_suis_je().
Referenced by typer_lire_milieu().
verifier()
int Pb_Phase_field::verifier () override virtual
Teste la compatibilite des equations de convection-diffusion et de l'hydraulique.
Le test se fait sur les conditions aux limites discretisees de chaque equation. Appel la fonction de librairie hors classe: tester_compatibilite_hydr_concentration(const Domaine_Cl_dis_base&,const Domaine_Cl_dis_base&)
Returns
(int) code de retour propage
Reimplemented from Probleme_base.
References Equation_base::domaine_Cl_dis(), eq_concentration, and eq_hydraulique.
typer_lire_milieu()
void Pb_Phase_field::typer_lire_milieu (Entree & is) override protected virtual
Reimplemented from Probleme_base.
References associer_milieu_base(), Equation_base::associer_milieu_equation(), Milieu_base::discretiser(), Probleme_base::discretiser_equations(), equation(), Probleme_base::la_discretisation_, Probleme_base::le_milieu_, Equation_base::milieu(), nombre_d_equations(), and TRUST_Ref< _CLASSE_ >::valeur().
Member Data Documentation
info_obj
const Type_info Pb_Phase_field::info_obj static
eq_hydraulique
Navier_Stokes_phase_field Pb_Phase_field::eq_hydraulique protected
Referenced by associer_milieu_base(), equation(), and verifier().
eq_concentration
Convection_Diffusion_Phase_field Pb_Phase_field::eq_concentration protected
Referenced by associer_milieu_base(), equation(), and verifier().