TrioCFD: Transport_K_KEps Class Reference
Transport_K_KEps Class Reference
#include <Transport_K_KEps.h>
Public Member Functions
void associer_milieu_base (const Milieu_base &) override
void associer_modele_turbulence (const Modele_turbulence_hyd_2_eq_base &) override
const Motcle & domaine_application () const override
int get_impr () const
const Type_info * get_info () const override
int get_nbcouches () const
int get_nutswitch () const
int get_switch () const
int get_yswitch () const
int lire_motcle_non_standard (const Motcle &, Entree &) override
Public Member Functions inherited from Transport_K_Eps_non_std
const Type_info * get_info () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
const Operateur & operateur (int) const override
Operateur & operateur (int) override
Public Member Functions inherited from Transport_K_Eps_base
int controler_K_Eps ()
void discretiser () override
const Type_info * get_info () const override
const Champ_Inc_base & inconnue () const override
Champ_Inc_base & inconnue () override
Public Member Functions inherited from Transport_2eq_base
void associer_milieu_base (const Milieu_base &) override
double calculer_pas_de_temps () const override
const Type_info * get_info () const override
const Milieu_base & milieu () const override
Milieu_base & milieu () override
Modele_turbulence_hyd_2_eq_base & modele_turbulence ()
const Modele_turbulence_hyd_2_eq_base & modele_turbulence () const
Public Member Functions inherited from Equation_base
virtual void abortTimeStep ()
virtual void associer_domaine_dis (const Domaine_dis_base &)
virtual void associer_pb_base (const Probleme_base &)
virtual void associer_sch_tps_base (const Schema_Temps_base &)
virtual double calculer_pas_de_temps () const
virtual void completer ()
virtual std::vector< YAML_data > data_a_sauvegarder () const
DoubleTab & derivee_en_temps_conv (DoubleTab &, const DoubleTab &)
virtual DoubleTab & derivee_en_temps_inco (DoubleTab &)
const Discretisation_base & discretisation () const
virtual void discretiser ()
virtual const Motcle & domaine_application () const
virtual Domaine_Cl_dis_base & domaine_Cl_dis ()
virtual const Domaine_Cl_dis_base & domaine_Cl_dis () const
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual void imprimer (Sortie &os) const
virtual bool initTimeStep (double dt)
const Nom & le_nom () const override
int limpr () const
virtual void mettre_a_jour (double temps)
virtual int preparer_calcul ()
Probleme_base & probleme ()
const Probleme_base & probleme () const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Schema_Temps_base & schema_temps ()
const Schema_Temps_base & schema_temps () const
Solveur_Masse_base & solv_masse ()
const Solveur_Masse_base & solv_masse () const
Sources & sources ()
const Sources & sources () const
virtual void valider_iteration ()
virtual void verifie_ch_init_nb_comp (const Champ_Inc_base &ch_ref, const int nb_comp) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Equation_base
virtual Entree & lire_cl (Entree &)
virtual Entree & lire_cond_init (Entree &)
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual Entree & lire_sources (Entree &)
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
virtual int verif_Cl () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
turbulente K et du taux de dissipation epsilon (eps) associee au modele de turbulence (k,eps) a deux couches. On traite en une seule equation le transport des deux grandeurs turbulentes. Il s'agit donc d'une equation vectorielle, dont le champ inconnue possede 2 composantes: K et epsilon. On instanciera un objet de cette classe uniquement si on utilise le modele a deux couches pour traiter la turbulence
See also
Equation_base
Constructor & Destructor Documentation
Transport_K_KEps()
Transport_K_KEps::Transport_K_KEps ()
~Transport_K_KEps()
Transport_K_KEps::~Transport_K_KEps ()
Member Function Documentation
cree_instance()
Objet_U * Transport_K_KEps::cree_instance () static
taille_memoire()
unsigned Transport_K_KEps::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Transport_K_KEps::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Transport_K_KEps::info () static
get_info()
const Type_info * Transport_K_KEps::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Transport_K_Eps_non_std.
self_cast() [1/2]
Transport_K_KEps & Transport_K_KEps::self_cast (Objet_U & r) static
self_cast() [2/2]
const Transport_K_KEps & Transport_K_KEps::self_cast (const Objet_U & r) static
printOn()
Sortie & Transport_K_KEps::printOn (Sortie & s) const override protected virtual
Imprime le type de l'equation sur un flot de sortie.
Parameters
(Sortie& s) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Transport_K_Eps_non_std.
References Objet_U::que_suis_je().
readOn()
Entree & Transport_K_KEps::readOn (Entree & s) override protected virtual
Lit les specifications d'une equation de transport K-epsilon a partir d'un flot d'entree.
Controle dynamique du type du terme source.
Parameters
(Entree& s) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Transport_K_Eps_non_std.
References TRUST_List< _CLASSE_ >::add(), TRUST_List< _CLASSE_ >::est_vide(), Equation_base::les_sources, loi_2couches, Equation_base::probleme(), Transport_K_Eps_non_std::readOn(), Objet_U_ptr::typer(), and Source::typer().
set_param()
void Transport_K_KEps::set_param (Param & titi) override virtual
Reimplemented from Transport_K_Eps_non_std.
References Param::ajouter(), Param::ajouter_flag(), Param::ajouter_non_std(), and Transport_K_Eps_non_std::set_param().
lire_motcle_non_standard()
int Transport_K_KEps::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Transport_K_Eps_non_std.
References Process::exit(), Transport_K_Eps_non_std::lire_motcle_non_standard(), loi_2couches, and Objet_U_ptr::typer().
associer_milieu_base()
void Transport_K_KEps::associer_milieu_base (const Milieu_base & un_milieu) override virtual
Associe un milieu physique a l'equation.
Le Milieu_base passe en parametre est caste en Fluide_Incompressible.
Parameters
(Milieu_base& un_milieu) le milieu physique a associer a l'equation
Reimplemented from Transport_2eq_base.
References Transport_2eq_base::le_fluide.
Referenced by associer_modele_turbulence().
associer_modele_turbulence()
void Transport_K_KEps::associer_modele_turbulence (const Modele_turbulence_hyd_2_eq_base & modele) override virtual
Associe un modele de turbulence K-epsilon deux couches a l'equation.
Parameters
(Modele_turbulence_hyd_K_Eps_2_Couches& modele) le modele de turbulence K-epsilon deux couches a associer a l'equation
Implements Transport_2eq_base.
References Transport_2eq_base::associer(), associer_milieu_base(), Transport_2eq_base::associer_vitesse(), Transport_K_Eps_base::discretiser(), Modele_turbulence_hyd_base::equation(), Equation_base::inconnue(), Equation_base::liste_modeles_, Equation_base::milieu(), Transport_2eq_base::mon_modele, and TRUST_Ref< _CLASSE_ >::valeur().
get_nbcouches()
int Transport_K_KEps::get_nbcouches () const inline
Renvoie le nombre de couches utilisees pour le modele 1-equation.
(version const)
Returns
(int) le nombre de couches
Referenced by Modele_turbulence_hyd_K_Eps_2_Couches::get_nbcouches().
get_yswitch()
int Transport_K_KEps::get_yswitch () const inline
Renvoie le y* de switch entre les deux couches pour le modele a deux couches.
(version const)
Returns
(int) le nombre de couches
Referenced by Modele_turbulence_hyd_K_Eps_2_Couches::get_yswitch().
get_switch()
int Transport_K_KEps::get_switch () const inline
Renvoie 0 si on choisit le switch par y*, 0 par nu_t.
(version const)
Returns
(int)
Referenced by Modele_turbulence_hyd_K_Eps_2_Couches::get_switch().
get_nutswitch()
int Transport_K_KEps::get_nutswitch () const inline
Renvoie la valeur de nut/nu qui delimite les deux couches.
(version const)
Returns
(int) valeur limite de nu_t/nu
Referenced by Modele_turbulence_hyd_K_Eps_2_Couches::get_nutswitch().
get_impr()
int Transport_K_KEps::get_impr () const inline
indique si on doit ecrire le domaine des 2 couches dans le .
out. (version const)
Returns
(int) 1 si on imprime , 0 sinon.
Referenced by Modele_turbulence_hyd_K_Eps_2_Couches::get_impr().
vitesse_transportante()
const Champ_Inc_base & Transport_K_KEps::vitesse_transportante () inline
domaine_application()
const Motcle & Transport_K_KEps::domaine_application () const override virtual
Renvoie le nom du domaine d'application de l'equation.
Ici "Transport_Keps".
Returns
(Motcle&) le nom du domaine d'application de l'equation
Reimplemented from Equation_base.
loi2couches()
Loi_2couches_base & Transport_K_KEps::loi2couches () inline
References loi_2couches, and TRUST_Deriv< _CLASSE_ >::valeur().
Member Data Documentation
info_obj
const Type_info Transport_K_KEps::info_obj static
loi_2couches
TRUST_Deriv< Loi_2couches_base > Transport_K_KEps::loi_2couches protected
Referenced by lire_motcle_non_standard(), loi2couches(), and readOn().