TrioCFD: Portance_interfaciale_VDF Class Reference
Portance_interfaciale_VDF Class Reference
#include <Portance_interfaciale_VDF.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Source_Portance_interfaciale_base
void completer () override
const Type_info * get_info () const override
Public Member Functions inherited from Sources_Multiphase_base
const Type_info * get_info () const override
void mettre_a_jour (double temps) override
Public Member Functions inherited from Source_base
virtual int a_pour_Champ_Fonc (const Motcle &mot, TRUST_Ref< Champ_base * > &ch_ref) const
virtual void associer_champ_rho (const Champ_base &champ_rho)
virtual void completer ()
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
virtual void resetTime (double t)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Portance_interfaciale_VDF()
Portance_interfaciale_VDF::Portance_interfaciale_VDF ()
~Portance_interfaciale_VDF()
Portance_interfaciale_VDF::~Portance_interfaciale_VDF ()
Member Function Documentation
cree_instance()
Objet_U * Portance_interfaciale_VDF::cree_instance () static
taille_memoire()
unsigned Portance_interfaciale_VDF::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Portance_interfaciale_VDF::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Portance_interfaciale_VDF::info () static
get_info()
const Type_info * Portance_interfaciale_VDF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Source_Portance_interfaciale_base.
self_cast() [1/2]
Portance_interfaciale_VDF & Portance_interfaciale_VDF::self_cast (Objet_U & r) static
self_cast() [2/2]
const Portance_interfaciale_VDF & Portance_interfaciale_VDF::self_cast (const Objet_U & r) static
printOn()
Sortie & Portance_interfaciale_VDF::printOn (Sortie & os) const override protected virtual
DOES NOTHING - to override in derived classes.
Imprime la source sur un flot de sortie.
Parameters
(Sortie& os) le flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Source_Portance_interfaciale_base.
readOn()
Entree & Portance_interfaciale_VDF::readOn (Entree & is) override protected virtual
DOES NOTHING - to override in derived classes.
Lecture d'un terme source sur un flot d'entree.
Parameters
(Entree& is) le flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Source_Portance_interfaciale_base.
References Source_Portance_interfaciale_base::readOn().
ajouter_blocs()
void Portance_interfaciale_VDF::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = {}) const override virtual
Implements Source_Portance_interfaciale_base.
References Portance_interfaciale_base::input_t::alpha, Source_Portance_interfaciale_base::beta_, Portance_interfaciale_base::output_t::Cl, Portance_interfaciale_base::coefficient(), Source_Portance_interfaciale_base::correlation_, Portance_interfaciale_base::input_t::d_bulles, Objet_U::dimension, MorEqn::equation(), Pb_Multiphase::equation_energie(), Pb_Multiphase::equation_masse(), Pb_Multiphase::equation_qdm(), Process::exit(), Champ_Face_base::fcl(), Probleme_base::get_champ(), Champ_Face_base::get_elem_vector_field(), Milieu_composite::get_interface(), Milieu_composite::get_saturation(), Interface_base::get_sigma_tab(), Probleme_base::has_champ(), Milieu_composite::has_interface(), Milieu_composite::has_saturation(), Equation_base::inconnue(), Portance_interfaciale_base::input_t::k_turb, TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Milieu_base::masse_volumique(), Equation_base::milieu(), Portance_interfaciale_base::input_t::mu, Source_Portance_interfaciale_base::n_l, Portance_interfaciale_base::input_t::nv, Portance_interfaciale_base::input_t::p, Champ_Proto::passe(), Champ_Inc_base::passe(), Milieu_base::porosite_face(), Equation_base::probleme(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Pb_Multiphase::resolution_en_T(), Portance_interfaciale_base::input_t::rho, Portance_interfaciale_base::input_t::sigma, Interface_base::sigma(), Interface_base::sigma_h(), Portance_interfaciale_base::input_t::T, Champ_Face_VDF::v_norm(), TRUST_Deriv< _CLASSE_ >::valeur(), Champ_Inc_base::valeurs(), and Champ_Proto::valeurs().
Member Data Documentation
info_obj
const Type_info Portance_interfaciale_VDF::info_obj static