TrioCFD: Traitement_particulier_NS_CEG Class Reference
Traitement_particulier_NS_CEG Class Reference
#include <Traitement_particulier_NS_CEG.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Traitement_particulier_NS_CEG()
Traitement_particulier_NS_CEG::Traitement_particulier_NS_CEG () inline
~Traitement_particulier_NS_CEG()
Traitement_particulier_NS_CEG::~Traitement_particulier_NS_CEG () inline override
Member Function Documentation
info()
const Type_info * Traitement_particulier_NS_CEG::info () static
get_info()
const Type_info * Traitement_particulier_NS_CEG::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Traitement_particulier_NS_base.
Reimplemented in Traitement_particulier_NS_CEG_VEF.
self_cast() [1/2]
Traitement_particulier_NS_CEG & Traitement_particulier_NS_CEG::self_cast (Objet_U & r) static
self_cast() [2/2]
const Traitement_particulier_NS_CEG & Traitement_particulier_NS_CEG::self_cast (const Objet_U & r) static
printOn()
Sortie & Traitement_particulier_NS_CEG::printOn (Sortie & is) const override protected virtual
Parameters
(Sortie& is) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Traitement_particulier_NS_base.
Reimplemented in Traitement_particulier_NS_CEG_VEF.
readOn()
Entree & Traitement_particulier_NS_CEG::readOn (Entree & is) override protected virtual
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Traitement_particulier_NS_base.
Reimplemented in Traitement_particulier_NS_CEG_VEF.
lire()
Entree & Traitement_particulier_NS_CEG::lire (Entree & is) override virtual
Implements Traitement_particulier_NS_base.
References Param::ajouter(), Param::ajouter_param(), C_, calculer_critere_areva_, calculer_critere_cea_jaea_, critere_cea_jaea_normalise_, debug_, dernier_temps_, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), dt_post_, Param::get_list_mots_lus(), haspi_, la_surface_libre_nom_, Param::lire_avec_accolades_depuis(), min_critere_Q_sur_max_critere_Q_, Traitement_particulier_NS_base::mon_equation, TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), nb_mailles_mini_, TRUST_List< _CLASSE_ >::rang(), Param::REQUIRED, t_deb_, and t_fin_.
preparer_calcul_particulier()
void Traitement_particulier_NS_CEG::preparer_calcul_particulier () override virtual
Implements Traitement_particulier_NS_base.
References calculer_critere_areva_, calculer_critere_cea_jaea_, Process::exit(), Domaine_VF::face_normales(), la_surface_libre_, la_surface_libre_nom_, Objet_U::le_nom(), Traitement_particulier_NS_base::mon_equation, and TRUST_Vector< _CLASSE_ >::size().
post_traitement_particulier()
void Traitement_particulier_NS_CEG::post_traitement_particulier () override virtual
Implements Traitement_particulier_NS_base.
References Statistiques::begin_count(), calculer_critere_areva_, calculer_critere_cea_jaea_, critere_areva(), critere_cea_jaea(), debug_, dernier_temps_, Statistiques::end_count(), Statistiques::last_time(), Traitement_particulier_NS_base::mon_equation, t_deb_, and t_fin_.
en_cours_de_resolution()
void Traitement_particulier_NS_CEG::en_cours_de_resolution (int , DoubleTab & , DoubleTab & , double) inline override virtual
Implements Traitement_particulier_NS_base.
sauver_stat()
void Traitement_particulier_NS_CEG::sauver_stat () const inline override virtual
Implements Traitement_particulier_NS_base.
reprendre_stat()
void Traitement_particulier_NS_CEG::reprendre_stat () inline override virtual
Implements Traitement_particulier_NS_base.
critere_areva()
void Traitement_particulier_NS_CEG::critere_areva () protected
References C_, Domaine_VF::elem_faces(), Domaine_VF::face_voisins(), haspi_, imprimer(), la_surface_libre_, Process::me(), Navier_Stokes_Turbulent::modele_turbulence(), Traitement_particulier_NS_base::mon_equation, Process::mp_max(), and Domaine_VF::xp().
Referenced by post_traitement_particulier().
critere_cea_jaea()
void Traitement_particulier_NS_CEG::critere_cea_jaea () protected
References Statistiques::begin_count(), Process::check_int_overflow(), critere_cea_jaea_normalise_, debug_, Postraitement::dt_post(), dt_post_, Statistiques::end_count(), Domaine_VF::face_sommets(), Domaine_VF::face_surfaces(), Domaine_VF::face_voisins(), haspi_, imprimer(), Process::je_suis_maitre(), la_surface_libre_, Statistiques::last_time(), lpost(), Process::me(), min_critere_Q_sur_max_critere_Q_, Traitement_particulier_NS_base::mon_equation, Process::mp_max(), TRUSTVect< _TYPE_, _SIZE_ >::mp_max_vect(), Process::mp_min(), Process::mp_sum(), Domaine_dis_base::nb_elem(), nb_mailles_mini_, Objet_U::nom_du_cas(), Process::nproc(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::resize(), Schema_Temps_base::temps_courant(), TRUST_Ref< _CLASSE_ >::valeur(), and Domaine_VF::xp().
Referenced by post_traitement_particulier().
imprimer()
void Traitement_particulier_NS_CEG::imprimer (const double valeur_critere, const Nom & critere, const ArrOfDouble & centre_vortex, const double rayon_vortex) protected
References Sortie_Fichier_base::close(), TRUST_Ref< _CLASSE_ >::le_nom(), Traitement_particulier_NS_base::mon_equation, Objet_U::nom_du_cas(), Sortie_Fichier_base::ouvrir(), Sortie_Fichier_base::precision(), and Sortie_Fichier_base::setf().
Referenced by critere_areva(), and critere_cea_jaea().
lpost()
int Traitement_particulier_NS_CEG::lpost (double temps_courant, double dt_post) const protected
References dernier_temps_.
Referenced by critere_cea_jaea().
Member Data Documentation
info_obj
const Type_info Traitement_particulier_NS_CEG::info_obj static
la_surface_libre_nom_
Nom Traitement_particulier_NS_CEG::la_surface_libre_nom_ protected
Referenced by lire(), and preparer_calcul_particulier().
la_surface_libre_
TRUST_Ref< Front_VF *> Traitement_particulier_NS_CEG::la_surface_libre_ protected
Referenced by critere_areva(), critere_cea_jaea(), and preparer_calcul_particulier().
haspi_
double Traitement_particulier_NS_CEG::haspi_ protected
Referenced by critere_areva(), critere_cea_jaea(), and lire().
C_
double Traitement_particulier_NS_CEG::C_ protected
Referenced by critere_areva(), and lire().
calculer_critere_areva_
int Traitement_particulier_NS_CEG::calculer_critere_areva_ protected
Referenced by lire(), post_traitement_particulier(), and preparer_calcul_particulier().
calculer_critere_cea_jaea_
int Traitement_particulier_NS_CEG::calculer_critere_cea_jaea_ protected
Referenced by lire(), post_traitement_particulier(), and preparer_calcul_particulier().
critere_cea_jaea_normalise_
int Traitement_particulier_NS_CEG::critere_cea_jaea_normalise_ protected
Referenced by critere_cea_jaea(), and lire().
nb_mailles_mini_
int Traitement_particulier_NS_CEG::nb_mailles_mini_ protected
Referenced by critere_cea_jaea(), and lire().
t_deb_
double Traitement_particulier_NS_CEG::t_deb_ protected
Referenced by lire(), and post_traitement_particulier().
t_fin_
double Traitement_particulier_NS_CEG::t_fin_ protected
Referenced by lire(), and post_traitement_particulier().
dernier_temps_
double Traitement_particulier_NS_CEG::dernier_temps_ protected
Referenced by lire(), lpost(), and post_traitement_particulier().
dt_post_
double Traitement_particulier_NS_CEG::dt_post_ protected
Referenced by critere_cea_jaea(), and lire().
debug_
int Traitement_particulier_NS_CEG::debug_ protected
Referenced by critere_cea_jaea(), lire(), and post_traitement_particulier().
min_critere_Q_sur_max_critere_Q_
double Traitement_particulier_NS_CEG::min_critere_Q_sur_max_critere_Q_ protected
Referenced by critere_cea_jaea(), and lire().