TrioCFD: Source_Generique_VEF Class Reference
Source_Generique_VEF Class Reference
#include <Source_Generique_VEF.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Source_Generique_base
void completer () override
const Type_info * get_info () const override
void mettre_a_jour (double temps) override
Public Member Functions inherited from Source_base
virtual int a_pour_Champ_Fonc (const Motcle &mot, TRUST_Ref< Champ_base * > &ch_ref) const
virtual void associer_champ_rho (const Champ_base &champ_rho)
virtual void completer ()
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
virtual void resetTime (double t)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
See also
Source_Generique_base
Constructor & Destructor Documentation
Source_Generique_VEF()
Source_Generique_VEF::Source_Generique_VEF ()
~Source_Generique_VEF()
Source_Generique_VEF::~Source_Generique_VEF ()
Member Function Documentation
cree_instance()
Objet_U * Source_Generique_VEF::cree_instance () static
taille_memoire()
unsigned Source_Generique_VEF::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Source_Generique_VEF::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Source_Generique_VEF::info () static
get_info()
const Type_info * Source_Generique_VEF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Source_Generique_base.
self_cast() [1/2]
Source_Generique_VEF & Source_Generique_VEF::self_cast (Objet_U & r) static
self_cast() [2/2]
const Source_Generique_VEF & Source_Generique_VEF::self_cast (const Objet_U & r) static
printOn()
Sortie & Source_Generique_VEF::printOn (Sortie & os) const override protected virtual
DOES NOTHING - to override in derived classes.
Imprime la source sur un flot de sortie.
Parameters
(Sortie& os) le flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Source_Generique_base.
References Objet_U::que_suis_je().
readOn()
Entree & Source_Generique_VEF::readOn (Entree & is) override protected virtual
DOES NOTHING - to override in derived classes.
Lecture d'un terme source sur un flot d'entree.
Parameters
(Entree& is) le flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Source_Generique_base.
References Source_Generique_base::readOn().
ajouter()
DoubleTab & Source_Generique_VEF::ajouter (DoubleTab & resu) const override virtual
Reimplemented from Source_base.
References Source_Generique_base::ch_source_, MorEqn::equation(), Champ_Generique_base::get_champ(), la_zcl_VEF, le_dom_VEF, TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Equation_base::milieu(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), Milieu_base::porosite_face(), TRUST_Deriv< _CLASSE_ >::valeur(), and Champ_Proto::valeurs().
associer_domaines()
void Source_Generique_VEF::associer_domaines (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & zcl_dis) override virtual
Implements Source_Generique_base.
References la_zcl_VEF, and le_dom_VEF.
localisation_source()
Nom Source_Generique_VEF::localisation_source () override virtual
Implements Source_Generique_base.
Member Data Documentation
info_obj
const Type_info Source_Generique_VEF::info_obj static
le_dom_VEF
TRUST_Ref< Domaine_VEF *> Source_Generique_VEF::le_dom_VEF protected
Referenced by ajouter(), and associer_domaines().
la_zcl_VEF
TRUST_Ref< Domaine_Cl_VEF *> Source_Generique_VEF::la_zcl_VEF protected
Referenced by ajouter(), and associer_domaines().