TrioCFD: Transport_Fluctuation_Temperature_W_Bas_Re Class Reference
Transport_Fluctuation_Temperature_W_Bas_Re Class Reference
#include <Transport_Fluctuation_Temperature_W_Bas_Re.h>
Public Member Functions
const Type_info * get_info () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
const Operateur & operateur (int) const override
Operateur & operateur (int) override
Public Member Functions inherited from Transport_Fluctuation_Temperature_W
void associer_milieu_base (const Milieu_base &) override
void completer () override
void discretiser () override
const Motcle & domaine_application () const override
const Type_info * get_info () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
int nombre_d_operateurs () const override
const Operateur & operateur (int) const override
Operateur & operateur (int) override
Public Member Functions inherited from Convection_Diffusion_std
void associer_vitesse (const Champ_base &)
const Type_info * get_info () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
int nombre_d_operateurs () const override
const Operateur & operateur (int) const override
Operateur & operateur (int) override
const Champ_Inc_base & vitesse_transportante () const
Public Member Functions inherited from Equation_base
virtual void abortTimeStep ()
virtual void associer_domaine_dis (const Domaine_dis_base &)
virtual void associer_pb_base (const Probleme_base &)
virtual void associer_sch_tps_base (const Schema_Temps_base &)
virtual double calculer_pas_de_temps () const
virtual void completer ()
virtual std::vector< YAML_data > data_a_sauvegarder () const
DoubleTab & derivee_en_temps_conv (DoubleTab &, const DoubleTab &)
virtual DoubleTab & derivee_en_temps_inco (DoubleTab &)
const Discretisation_base & discretisation () const
virtual void discretiser ()
virtual const Motcle & domaine_application () const
virtual Domaine_Cl_dis_base & domaine_Cl_dis ()
virtual const Domaine_Cl_dis_base & domaine_Cl_dis () const
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual void imprimer (Sortie &os) const
virtual bool initTimeStep (double dt)
const Nom & le_nom () const override
int limpr () const
virtual void mettre_a_jour (double temps)
virtual int preparer_calcul ()
Probleme_base & probleme ()
const Probleme_base & probleme () const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Schema_Temps_base & schema_temps ()
const Schema_Temps_base & schema_temps () const
Solveur_Masse_base & solv_masse ()
const Solveur_Masse_base & solv_masse () const
Sources & sources ()
const Sources & sources () const
virtual void valider_iteration ()
virtual void verifie_ch_init_nb_comp (const Champ_Inc_base &ch_ref, const int nb_comp) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Sortie & printOn (Sortie &x) const override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Equation_base
virtual Entree & lire_cl (Entree &)
virtual Entree & lire_cond_init (Entree &)
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual Entree & lire_sources (Entree &)
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
virtual int verif_Cl () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Transport_Fluctuation_Temperature_W_Bas_Re()
Transport_Fluctuation_Temperature_W_Bas_Re::Transport_Fluctuation_Temperature_W_Bas_Re ()
~Transport_Fluctuation_Temperature_W_Bas_Re()
Transport_Fluctuation_Temperature_W_Bas_Re::~Transport_Fluctuation_Temperature_W_Bas_Re ()
Member Function Documentation
cree_instance()
Objet_U * Transport_Fluctuation_Temperature_W_Bas_Re::cree_instance () static
taille_memoire()
unsigned Transport_Fluctuation_Temperature_W_Bas_Re::taille_memoire () const override virtual
Reimplemented from Transport_Fluctuation_Temperature_W.
duplique()
int Transport_Fluctuation_Temperature_W_Bas_Re::duplique () const override virtual
Reimplemented from Transport_Fluctuation_Temperature_W.
info()
const Type_info * Transport_Fluctuation_Temperature_W_Bas_Re::info () static
get_info()
const Type_info * Transport_Fluctuation_Temperature_W_Bas_Re::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Transport_Fluctuation_Temperature_W.
self_cast() [1/2]
Transport_Fluctuation_Temperature_W_Bas_Re & Transport_Fluctuation_Temperature_W_Bas_Re::self_cast (Objet_U & r) static
self_cast() [2/2]
const Transport_Fluctuation_Temperature_W_Bas_Re & Transport_Fluctuation_Temperature_W_Bas_Re::self_cast (const Objet_U & r) static
printOn()
Sortie & Transport_Fluctuation_Temperature_W_Bas_Re::printOn (Sortie & is) const override protected virtual
Simple appel a Equation_base::printOn(Sortie&)
Parameters
(Sortie& is) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Transport_Fluctuation_Temperature_W.
References Objet_U::que_suis_je().
readOn()
Entree & Transport_Fluctuation_Temperature_W_Bas_Re::readOn (Entree & is) override protected virtual
cf Transport_Fluctuation_Temperature_W::readOn(is)
Reimplemented from Transport_Fluctuation_Temperature_W.
References TRUST_List< _CLASSE_ >::add(), TRUST_List< _CLASSE_ >::est_vide(), Process::exit(), Equation_base::les_sources, Equation_base::probleme(), Objet_U::que_suis_je(), Transport_Fluctuation_Temperature_W::readOn(), and Source::typer().
set_param()
void Transport_Fluctuation_Temperature_W_Bas_Re::set_param (Param & titi) override virtual
Reimplemented from Transport_Fluctuation_Temperature_W.
References Transport_Fluctuation_Temperature_W::set_param().
lire_motcle_non_standard()
int Transport_Fluctuation_Temperature_W_Bas_Re::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Transport_Fluctuation_Temperature_W.
References Transport_Fluctuation_Temperature_W::lire_motcle_non_standard(), and Transport_Fluctuation_Temperature_W::terme_diffusif.
associer_modele_turbulence()
void Transport_Fluctuation_Temperature_W_Bas_Re::associer_modele_turbulence (const Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re & modele)
References Equation_base::associer_domaine_dis(), Transport_Fluctuation_Temperature_W::associer_milieu_base(), Equation_base::associer_pb_base(), Equation_base::associer_sch_tps_base(), Transport_Fluctuation_Temperature_W::discretiser(), Equation_base::domaine_dis(), Modele_turbulence_scal_base::equation(), Equation_base::milieu(), mon_modele_Fluctu_Temp, Equation_base::probleme(), and Equation_base::schema_temps().
milieu() [1/2]
const Milieu_base & Transport_Fluctuation_Temperature_W_Bas_Re::milieu () const inline override virtual
Reimplemented from Transport_Fluctuation_Temperature_W.
References Process::exit(), Transport_Fluctuation_Temperature_W::le_fluide, TRUST_Ref< _CLASSE_ >::non_nul(), and TRUST_Ref< _CLASSE_ >::valeur().
milieu() [2/2]
Milieu_base & Transport_Fluctuation_Temperature_W_Bas_Re::milieu () inline override virtual
Reimplemented from Transport_Fluctuation_Temperature_W.
References Process::exit(), Transport_Fluctuation_Temperature_W::le_fluide, TRUST_Ref< _CLASSE_ >::non_nul(), and TRUST_Ref< _CLASSE_ >::valeur().
modele_turbulence() [1/2]
Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re & Transport_Fluctuation_Temperature_W_Bas_Re::modele_turbulence () inline
References mon_modele_Fluctu_Temp, TRUST_Ref< _CLASSE_ >::non_nul(), and TRUST_Ref< _CLASSE_ >::valeur().
modele_turbulence() [2/2]
const Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re & Transport_Fluctuation_Temperature_W_Bas_Re::modele_turbulence () const inline
References mon_modele_Fluctu_Temp, TRUST_Ref< _CLASSE_ >::non_nul(), and TRUST_Ref< _CLASSE_ >::valeur().
operateur() [1/2]
const Operateur & Transport_Fluctuation_Temperature_W_Bas_Re::operateur (int i) const override virtual
surcharge de la methode d'Equation_base.
renvoie le ieme operateur.
Reimplemented from Transport_Fluctuation_Temperature_W.
References Process::exit(), Transport_Fluctuation_Temperature_W::nombre_d_operateurs(), Convection_Diffusion_std::terme_convectif, and Transport_Fluctuation_Temperature_W::terme_diffusif.
operateur() [2/2]
Operateur & Transport_Fluctuation_Temperature_W_Bas_Re::operateur (int i) override virtual
surcharge de la methode d'Equation_base.
renvoie le ieme operateur.
Reimplemented from Transport_Fluctuation_Temperature_W.
References Process::exit(), Transport_Fluctuation_Temperature_W::nombre_d_operateurs(), Convection_Diffusion_std::terme_convectif, and Transport_Fluctuation_Temperature_W::terme_diffusif.
Member Data Documentation
info_obj
const Type_info Transport_Fluctuation_Temperature_W_Bas_Re::info_obj static
mon_modele_Fluctu_Temp
TRUST_Ref< Modele_turbulence_scal_Fluctuation_Temperature_W_Bas_Re *> Transport_Fluctuation_Temperature_W_Bas_Re::mon_modele_Fluctu_Temp protected
Referenced by associer_modele_turbulence(), and modele_turbulence().