TrioCFD: Paroi_flux_impose_Rayo_transp Class Reference
Paroi_flux_impose_Rayo_transp Class Reference
#include <Paroi_flux_impose_Rayo_transp.h>
Public Member Functions
const Type_info * get_info () const override
void mettre_a_jour (double temps) override
Public Member Functions inherited from Paroi_Rayo_transp
double flux_impose (int i) const override
double flux_impose (int i, int j) const override
const Type_info * get_info () const override
Public Member Functions inherited from Neumann_paroi
const Type_info * get_info () const override
void verifie_ch_init_nb_comp () const override
Public Member Functions inherited from Neumann
const DoubleTab & flux_impose (bool nb_faces_tot=false) const
virtual double flux_impose (int i) const
virtual double flux_impose (int i, int j) const
const Type_info * get_info () const override
Public Member Functions inherited from Cond_lim_base
virtual int a_mettre_a_jour_ss_pas_dt ()
virtual void associer_domaine_cl_dis_base (const Domaine_Cl_dis_base &)
virtual void associer_fr_dis_base (const Frontiere_dis_base &)
virtual void calculer_coeffs_echange (double temps)
virtual int compatible_avec_discr (const Discretisation_base &) const
Domaine_Cl_dis_base & domaine_Cl_dis ()
const Domaine_Cl_dis_base & domaine_Cl_dis () const
virtual Frontiere_dis_base & frontiere_dis ()
virtual const Frontiere_dis_base & frontiere_dis () const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
void set_modifier_val_imp (int)
virtual void verifie_ch_init_nb_comp () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Cond_lim_base
void err_pas_compatible (const Discretisation_base &) const
void err_pas_compatible (const Equation_base &) const
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Paroi_flux_impose_Rayo_transp()
Paroi_flux_impose_Rayo_transp::Paroi_flux_impose_Rayo_transp ()
~Paroi_flux_impose_Rayo_transp()
Paroi_flux_impose_Rayo_transp::~Paroi_flux_impose_Rayo_transp ()
Member Function Documentation
cree_instance()
Objet_U * Paroi_flux_impose_Rayo_transp::cree_instance () static
taille_memoire()
unsigned Paroi_flux_impose_Rayo_transp::taille_memoire () const override virtual
Reimplemented from Neumann_paroi.
duplique()
int Paroi_flux_impose_Rayo_transp::duplique () const override virtual
Reimplemented from Neumann_paroi.
info()
const Type_info * Paroi_flux_impose_Rayo_transp::info () static
get_info()
const Type_info * Paroi_flux_impose_Rayo_transp::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Paroi_Rayo_transp.
self_cast() [1/2]
Paroi_flux_impose_Rayo_transp & Paroi_flux_impose_Rayo_transp::self_cast (Objet_U & r) static
self_cast() [2/2]
const Paroi_flux_impose_Rayo_transp & Paroi_flux_impose_Rayo_transp::self_cast (const Objet_U & r) static
printOn()
Sortie & Paroi_flux_impose_Rayo_transp::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Paroi_Rayo_transp.
readOn()
Entree & Paroi_flux_impose_Rayo_transp::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Paroi_Rayo_transp.
References Neumann_paroi::readOn().
calculer_Teta_i()
void Paroi_flux_impose_Rayo_transp::calculer_Teta_i ()
References calculer_Teta_i_VDF(), calculer_Teta_i_VEF(), and is_VDF_.
Referenced by mettre_a_jour().
mettre_a_jour()
void Paroi_flux_impose_Rayo_transp::mettre_a_jour (double temps) override virtual
Effectue une mise a jour en temps de la condition aux limites.
Parameters
(double temps) le pas de temps de mise a jour
Reimplemented from Cond_lim_base.
References calculer_Teta_i(), and Cond_lim_base::mettre_a_jour().
completer()
void Paroi_flux_impose_Rayo_transp::completer () override virtual
Reimplemented from Cond_Lim_Rayo.
References Cond_lim_base::domaine_Cl_dis(), domaine_VDF, Domaine_VF::face_voisins(), Cond_lim_base::frontiere_dis(), is_VDF_, Cond_lim_base::mon_dom_cl_dis, Front_VF::nb_faces(), Front_VF::num_premiere_face(), Cond_Lim_Rayo::preparer_surface(), Cond_Lim_Rayo::Teta_i, and TRUST_Ref< _CLASSE_ >::valeur().
calculer_Teta_i_VDF()
void Paroi_flux_impose_Rayo_transp::calculer_Teta_i_VDF () protected
References Domaine_base::bords_a_imprimer(), Milieu_base::capacite_calorifique(), Milieu_base::conductivite(), TRUST_List< _CLASSE_ >::contient(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Domaine_VDF::dist_norm_bord(), Domaine_dis_base::domaine(), Cond_lim_base::domaine_Cl_dis(), domaine_VDF, Process::exit(), Domaine_VF::face_voisins(), Cond_lim_base::frontiere_dis(), Cond_lim_base::le_champ_front, Cond_Lim_Rayo::le_modele_rayo, Frontiere_dis_base::le_nom(), Schema_Temps_base::limpr(), Milieu_base::masse_volumique(), Cond_lim_base::mon_dom_cl_dis, Front_VF::nb_faces(), Front_VF::num_premiere_face(), Schema_Temps_base::pas_de_temps(), TRUSTVect< _TYPE_, _SIZE_ >::size(), Cond_Lim_Rayo::Teta_i, TRUST_Ref< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), Champ_front_base::valeurs(), and Champ_Proto::valeurs().
Referenced by calculer_Teta_i().
calculer_Teta_i_VEF()
void Paroi_flux_impose_Rayo_transp::calculer_Teta_i_VEF () protected
References Cond_lim_base::frontiere_dis(), Cond_Lim_Rayo::le_modele_rayo, Cond_lim_base::mon_dom_cl_dis, Front_VF::nb_faces(), Front_VF::num_premiere_face(), and Cond_Lim_Rayo::Teta_i.
Referenced by calculer_Teta_i().
Member Data Documentation
info_obj
const Type_info Paroi_flux_impose_Rayo_transp::info_obj static
domaine_VDF
TRUST_Ref< Domaine_VDF *> Paroi_flux_impose_Rayo_transp::domaine_VDF protected
Referenced by calculer_Teta_i_VDF(), and completer().
is_VDF_
int Paroi_flux_impose_Rayo_transp::is_VDF_ protected
Referenced by calculer_Teta_i(), and completer().