TrioCFD: IJK_One_Dimensional_Subproblem_Geometry Class Reference
IJK_One_Dimensional_Subproblem_Geometry Class Reference
#include <IJK_One_Dimensional_Subproblem_Geometry.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
IJK_One_Dimensional_Subproblem_Geometry()
IJK_One_Dimensional_Subproblem_Geometry::IJK_One_Dimensional_Subproblem_Geometry ()
References disable_find_cell_centre_probe_tip_, disable_probe_collision_, enable_resize_probe_collision_, interfaces_, points_per_thermal_subproblem_, and resize_probe_collision_index_.
~IJK_One_Dimensional_Subproblem_Geometry()
IJK_One_Dimensional_Subproblem_Geometry::~IJK_One_Dimensional_Subproblem_Geometry ()
Member Function Documentation
cree_instance()
Objet_U * IJK_One_Dimensional_Subproblem_Geometry::cree_instance () static
taille_memoire()
unsigned IJK_One_Dimensional_Subproblem_Geometry::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int IJK_One_Dimensional_Subproblem_Geometry::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * IJK_One_Dimensional_Subproblem_Geometry::info () static
get_info()
const Type_info * IJK_One_Dimensional_Subproblem_Geometry::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
IJK_One_Dimensional_Subproblem_Geometry & IJK_One_Dimensional_Subproblem_Geometry::self_cast (Objet_U & r) static
self_cast() [2/2]
const IJK_One_Dimensional_Subproblem_Geometry & IJK_One_Dimensional_Subproblem_Geometry::self_cast (const Objet_U & r) static
printOn()
Sortie & IJK_One_Dimensional_Subproblem_Geometry::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
References Objet_U::printOn().
readOn()
Entree & IJK_One_Dimensional_Subproblem_Geometry::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
References Objet_U::readOn().
compute_interface_basis_vectors()
void IJK_One_Dimensional_Subproblem_Geometry::compute_interface_basis_vectors ()
compute_pure_spherical_basis_vectors()
void IJK_One_Dimensional_Subproblem_Geometry::compute_pure_spherical_basis_vectors ()
compute_local_discretisation()
void IJK_One_Dimensional_Subproblem_Geometry::compute_local_discretisation ()
interpolate_indicator_on_probes()
void IJK_One_Dimensional_Subproblem_Geometry::interpolate_indicator_on_probes ()
References coordinates_cartesian_compo_, disable_find_cell_centre_probe_tip_, disable_probe_collision_, enable_resize_probe_collision_, find_cell_related_indicator_on_probes(), IJK_Interfaces::I(), indicator_interp_, interfaces_, points_per_thermal_subproblem_, TRUSTVect< _TYPE_, _SIZE_ >::resize(), and resize_probe_collision_index_.
find_cell_related_indicator_on_probes()
double IJK_One_Dimensional_Subproblem_Geometry::find_cell_related_indicator_on_probes (const int & last_index)
References coordinates_cartesian_compo_, Domaine_IJK::ELEM, Domaine_IJK::get_constant_delta(), IJK_Interfaces::I(), index_i_, index_j_, index_k_, interfaces_, and ref_ijk_ft_.
Referenced by interpolate_indicator_on_probes().
compute_distance_cell_centre()
void IJK_One_Dimensional_Subproblem_Geometry::compute_distance_cell_centre ()
References cell_centre_distance_, cell_centre_tangential_distance_, debug_, Domaine_IJK::ELEM, facet_barycentre_, has_computed_cell_centre_distance_, index_i_, index_j_, index_k_, Vecteur3::length(), normal_vector_compo_, Vecteur3::produit_scalaire(), ref_ijk_ft_, and tangential_distance_vector_.
compute_distance_faces_centres()
void IJK_One_Dimensional_Subproblem_Geometry::compute_distance_faces_centres ()
References compute_vertex_position(), debug_, face_centres_distance_, face_centres_tangential_distance_, face_tangential_distance_vector_, Domaine_IJK::FACES_I, Domaine_IJK::FACES_J, Domaine_IJK::FACES_K, facet_barycentre_, has_computed_cell_faces_distance_, index_i_, index_j_, index_k_, Vecteur3::length(), normal_vector_compo_, Vecteur3::produit_scalaire(), pure_liquid_neighbours_, ref_ijk_ft_, vertices_centres_distance_, vertices_centres_tangential_distance_, and vertices_tangential_distance_vector_.
compute_distance_cell_centres_neighbours()
void IJK_One_Dimensional_Subproblem_Geometry::compute_distance_cell_centres_neighbours ()
References cell_centre_distance_, compute_cell_weighting(), correct_neighbours_rank_, dxyz_increment_bool_, Domaine_IJK::get_constant_delta(), get_dxyz_increment_max(), index_i_, index_j_, index_k_, neighbours_weighting_, normal_vector_compo_, probe_length_, Vecteur3::produit_scalaire(), pure_neighbours_corrected_colinearity_, pure_neighbours_corrected_distance_, pure_neighbours_corrected_sign_, pure_neighbours_to_correct_, and ref_ijk_ft_.
compute_cell_weighting()
double IJK_One_Dimensional_Subproblem_Geometry::compute_cell_weighting (const double & dx_contrib, const double & dy_contrib, const double & dz_contrib)
References compute_colinearity(), compute_distance_cell_faces(), neighbours_colinearity_distance_weighting_, neighbours_colinearity_weighting_, and neighbours_distance_weighting_.
Referenced by compute_distance_cell_centres_neighbours().
compute_distance_last_cell_faces_neighbours()
void IJK_One_Dimensional_Subproblem_Geometry::compute_distance_last_cell_faces_neighbours ()
References cell_centre_distance_, compute_cell_faces_weighting(), correct_neighbours_rank_, dxyz_over_two_increment_bool_, Domaine_IJK::get_constant_delta(), get_dxyz_increment_max(), get_dxyz_over_two_increment_max(), index_i_, index_j_, index_k_, neighbours_last_faces_weighting_, normal_vector_compo_, probe_length_, Vecteur3::produit_scalaire(), pure_neighbours_corrected_sign_, pure_neighbours_last_faces_corrected_colinearity_, pure_neighbours_last_faces_corrected_distance_, pure_neighbours_last_faces_to_correct_, and ref_ijk_ft_.
compute_cell_faces_weighting()
double IJK_One_Dimensional_Subproblem_Geometry::compute_cell_faces_weighting (const double & dx_contrib, const double & dy_contrib, const double & dz_contrib, const int & dir)
References compute_colinearity(), compute_colinearity_cell_faces(), compute_distance_cell_faces(), neighbours_last_faces_colinearity_face_weighting_, neighbours_last_faces_colinearity_weighting_, neighbours_last_faces_distance_colinearity_face_weighting_, neighbours_last_faces_distance_colinearity_weighting_, and neighbours_last_faces_distance_weighting_.
Referenced by compute_distance_last_cell_faces_neighbours().
compute_relative_vector_cell_faces()
Vecteur3 IJK_One_Dimensional_Subproblem_Geometry::compute_relative_vector_cell_faces (const double & dx_contrib, const double & dy_contrib, const double & dz_contrib)
References cell_centre_distance_, cell_centre_tangential_distance_, normal_vector_compo_, and tangential_distance_vector_.
Referenced by compute_colinearity(), compute_colinearity_cell_faces(), and compute_distance_cell_faces().
compute_colinearity()
double IJK_One_Dimensional_Subproblem_Geometry::compute_colinearity (const double & dx_contrib, const double & dy_contrib, const double & dz_contrib)
References compute_relative_vector_cell_faces(), Vecteur3::length(), normal_vector_compo_, and Vecteur3::produit_scalaire().
Referenced by compute_cell_faces_weighting(), and compute_cell_weighting().
compute_colinearity_cell_faces()
double IJK_One_Dimensional_Subproblem_Geometry::compute_colinearity_cell_faces (const double & dx_contrib, const double & dy_contrib, const double & dz_contrib, const int & dir)
References compute_relative_vector_cell_faces(), and Vecteur3::length().
Referenced by compute_cell_faces_weighting().
compute_distance_cell_faces()
double IJK_One_Dimensional_Subproblem_Geometry::compute_distance_cell_faces (const double & dx_contrib, const double & dy_contrib, const double & dz_contrib)
References compute_relative_vector_cell_faces(), Vecteur3::produit_scalaire(), and tangential_distance_vector_.
Referenced by compute_cell_faces_weighting(), and compute_cell_weighting().
get_dxyz_increment_max()
int IJK_One_Dimensional_Subproblem_Geometry::get_dxyz_increment_max ()
References correct_neighbours_rank_, Domaine_IJK::get_constant_delta(), neighbours_corrected_rank_, probe_length_, and ref_ijk_ft_.
Referenced by compute_distance_cell_centres_neighbours(), and compute_distance_last_cell_faces_neighbours().
get_dxyz_over_two_increment_max()
int IJK_One_Dimensional_Subproblem_Geometry::get_dxyz_over_two_increment_max ()
References correct_neighbours_rank_, Domaine_IJK::get_constant_delta(), neighbours_face_corrected_rank_, probe_length_, and ref_ijk_ft_.
Referenced by compute_distance_last_cell_faces_neighbours().
get_maximum_remaining_distance()
void IJK_One_Dimensional_Subproblem_Geometry::get_maximum_remaining_distance (int & dx_remaining, int & dy_remaining, int & dz_remaining)
References cell_centre_distance_, normal_vector_compo_, and probe_length_.
compute_vertex_position()
void IJK_One_Dimensional_Subproblem_Geometry::compute_vertex_position (const int & vertex_number, const int & face_dir, Vecteur3 & bary_vertex, double & distance_vertex_centre, double & tangential_distance_vertex_centre, Vecteur3 & tangential_distance_vector_vertex_centre) protected
References Domaine_IJK::get_constant_delta(), Vecteur3::length(), normal_vector_compo_, Vecteur3::produit_scalaire(), and ref_ijk_ft_.
Referenced by compute_distance_faces_centres().
Friends And Related Function Documentation
IJK_One_Dimensional_Subproblem
friend class IJK_One_Dimensional_Subproblem friend
Member Data Documentation
info_obj
const Type_info IJK_One_Dimensional_Subproblem_Geometry::info_obj static
ref_ijk_ft_
TRUST_Ref< Probleme_FTD_IJK_base *> IJK_One_Dimensional_Subproblem_Geometry::ref_ijk_ft_ protected
Referenced by compute_distance_cell_centre(), compute_distance_cell_centres_neighbours(), compute_distance_faces_centres(), compute_distance_last_cell_faces_neighbours(), compute_vertex_position(), find_cell_related_indicator_on_probes(), get_dxyz_increment_max(), and get_dxyz_over_two_increment_max().
interfaces_
const IJK_Interfaces* IJK_One_Dimensional_Subproblem_Geometry::interfaces_ protected
Referenced by find_cell_related_indicator_on_probes(), IJK_One_Dimensional_Subproblem_Geometry(), and interpolate_indicator_on_probes().
debug_
int IJK_One_Dimensional_Subproblem_Geometry::debug_ = 0 protected
Referenced by compute_distance_cell_centre(), and compute_distance_faces_centres().
points_per_thermal_subproblem_
int* IJK_One_Dimensional_Subproblem_Geometry::points_per_thermal_subproblem_ protected
Referenced by IJK_One_Dimensional_Subproblem_Geometry(), and interpolate_indicator_on_probes().
probe_length_
double IJK_One_Dimensional_Subproblem_Geometry::probe_length_ = 0. protected
Referenced by compute_distance_cell_centres_neighbours(), compute_distance_last_cell_faces_neighbours(), get_dxyz_increment_max(), get_dxyz_over_two_increment_max(), and get_maximum_remaining_distance().
coordinates_cartesian_compo_
DoubleTab IJK_One_Dimensional_Subproblem_Geometry::coordinates_cartesian_compo_ protected
Referenced by find_cell_related_indicator_on_probes(), and interpolate_indicator_on_probes().
disable_probe_collision_
int IJK_One_Dimensional_Subproblem_Geometry::disable_probe_collision_ protected
Referenced by IJK_One_Dimensional_Subproblem_Geometry(), and interpolate_indicator_on_probes().
enable_resize_probe_collision_
int IJK_One_Dimensional_Subproblem_Geometry::enable_resize_probe_collision_ protected
Referenced by IJK_One_Dimensional_Subproblem_Geometry(), and interpolate_indicator_on_probes().
disable_find_cell_centre_probe_tip_
int IJK_One_Dimensional_Subproblem_Geometry::disable_find_cell_centre_probe_tip_ protected
Referenced by IJK_One_Dimensional_Subproblem_Geometry(), and interpolate_indicator_on_probes().
resize_probe_collision_index_
int IJK_One_Dimensional_Subproblem_Geometry::resize_probe_collision_index_ protected
Referenced by IJK_One_Dimensional_Subproblem_Geometry(), and interpolate_indicator_on_probes().
indicator_interp_
DoubleVect IJK_One_Dimensional_Subproblem_Geometry::indicator_interp_ protected
Referenced by interpolate_indicator_on_probes().
facet_barycentre_
Vecteur3 IJK_One_Dimensional_Subproblem_Geometry::facet_barycentre_ protected
Referenced by compute_distance_cell_centre(), and compute_distance_faces_centres().
normal_vector_compo_
Vecteur3 IJK_One_Dimensional_Subproblem_Geometry::normal_vector_compo_ protected
Referenced by compute_colinearity(), compute_distance_cell_centre(), compute_distance_cell_centres_neighbours(), compute_distance_faces_centres(), compute_distance_last_cell_faces_neighbours(), compute_relative_vector_cell_faces(), compute_vertex_position(), and get_maximum_remaining_distance().
index_i_
int IJK_One_Dimensional_Subproblem_Geometry::index_i_ = 0 protected
Referenced by compute_distance_cell_centre(), compute_distance_cell_centres_neighbours(), compute_distance_faces_centres(), compute_distance_last_cell_faces_neighbours(), and find_cell_related_indicator_on_probes().
index_j_
int IJK_One_Dimensional_Subproblem_Geometry::index_j_ = 0 protected
Referenced by compute_distance_cell_centre(), compute_distance_cell_centres_neighbours(), compute_distance_faces_centres(), compute_distance_last_cell_faces_neighbours(), and find_cell_related_indicator_on_probes().
index_k_
int IJK_One_Dimensional_Subproblem_Geometry::index_k_ = 0 protected
Referenced by compute_distance_cell_centre(), compute_distance_cell_centres_neighbours(), compute_distance_faces_centres(), compute_distance_last_cell_faces_neighbours(), and find_cell_related_indicator_on_probes().
cell_centre_distance_
double IJK_One_Dimensional_Subproblem_Geometry::cell_centre_distance_ = 0 protected
Referenced by compute_distance_cell_centre(), compute_distance_cell_centres_neighbours(), compute_distance_last_cell_faces_neighbours(), compute_relative_vector_cell_faces(), and get_maximum_remaining_distance().
cell_centre_tangential_distance_
double IJK_One_Dimensional_Subproblem_Geometry::cell_centre_tangential_distance_ = 0. protected
Referenced by compute_distance_cell_centre(), and compute_relative_vector_cell_faces().
tangential_distance_vector_
Vecteur3 IJK_One_Dimensional_Subproblem_Geometry::tangential_distance_vector_ protected
Referenced by compute_distance_cell_centre(), compute_distance_cell_faces(), and compute_relative_vector_cell_faces().
pure_liquid_neighbours_
FixedVector<bool,6> IJK_One_Dimensional_Subproblem_Geometry::pure_liquid_neighbours_ protected
Referenced by compute_distance_faces_centres().
face_centres_distance_
FixedVector<double,6> IJK_One_Dimensional_Subproblem_Geometry::face_centres_distance_ protected
Referenced by compute_distance_faces_centres().
face_centres_tangential_distance_
FixedVector<double,6> IJK_One_Dimensional_Subproblem_Geometry::face_centres_tangential_distance_ protected
Referenced by compute_distance_faces_centres().
face_tangential_distance_vector_
FixedVector<Vecteur3,6> IJK_One_Dimensional_Subproblem_Geometry::face_tangential_distance_vector_ protected
Referenced by compute_distance_faces_centres().
vertices_centres_distance_
FixedVector<FixedVector<double,4>,6> IJK_One_Dimensional_Subproblem_Geometry::vertices_centres_distance_ protected
Referenced by compute_distance_faces_centres().
vertices_centres_tangential_distance_
FixedVector<FixedVector<double,4>,6> IJK_One_Dimensional_Subproblem_Geometry::vertices_centres_tangential_distance_ protected
Referenced by compute_distance_faces_centres().
vertices_tangential_distance_vector_
FixedVector<FixedVector<Vecteur3,4>,6> IJK_One_Dimensional_Subproblem_Geometry::vertices_tangential_distance_vector_ protected
Referenced by compute_distance_faces_centres().
modified_probe_length_from_vertices_
double IJK_One_Dimensional_Subproblem_Geometry::modified_probe_length_from_vertices_ = 0. protected
has_computed_cell_centre_distance_
bool IJK_One_Dimensional_Subproblem_Geometry::has_computed_cell_centre_distance_ =false protected
Referenced by compute_distance_cell_centre().
has_computed_cell_faces_distance_
bool IJK_One_Dimensional_Subproblem_Geometry::has_computed_cell_faces_distance_ =false protected
Referenced by compute_distance_faces_centres().
correct_fluxes_
int IJK_One_Dimensional_Subproblem_Geometry::correct_fluxes_ = 0 protected
correct_temperature_cell_neighbours_
int IJK_One_Dimensional_Subproblem_Geometry::correct_temperature_cell_neighbours_ = 0 protected
correct_neighbours_rank_
int IJK_One_Dimensional_Subproblem_Geometry::correct_neighbours_rank_ = 1 protected
Referenced by compute_distance_cell_centres_neighbours(), compute_distance_last_cell_faces_neighbours(), get_dxyz_increment_max(), and get_dxyz_over_two_increment_max().
neighbours_corrected_rank_
int IJK_One_Dimensional_Subproblem_Geometry::neighbours_corrected_rank_ = 1 protected
Referenced by get_dxyz_increment_max().
neighbours_weighting_
int IJK_One_Dimensional_Subproblem_Geometry::neighbours_weighting_ = 0 protected
Referenced by compute_distance_cell_centres_neighbours().
neighbours_colinearity_weighting_
int IJK_One_Dimensional_Subproblem_Geometry::neighbours_colinearity_weighting_ = 0 protected
Referenced by compute_cell_weighting().
neighbours_distance_weighting_
int IJK_One_Dimensional_Subproblem_Geometry::neighbours_distance_weighting_ = 0 protected
Referenced by compute_cell_weighting().
neighbours_colinearity_distance_weighting_
int IJK_One_Dimensional_Subproblem_Geometry::neighbours_colinearity_distance_weighting_ = 0 protected
Referenced by compute_cell_weighting().
pure_neighbours_corrected_sign_
FixedVector<int,3> IJK_One_Dimensional_Subproblem_Geometry::pure_neighbours_corrected_sign_ protected
Referenced by compute_distance_cell_centres_neighbours(), and compute_distance_last_cell_faces_neighbours().
pure_neighbours_to_correct_
std::vector<std::vector<std::vector<bool> > > IJK_One_Dimensional_Subproblem_Geometry::pure_neighbours_to_correct_ protected
Referenced by compute_distance_cell_centres_neighbours().
pure_neighbours_corrected_distance_
std::vector<std::vector<std::vector<double> > > IJK_One_Dimensional_Subproblem_Geometry::pure_neighbours_corrected_distance_ protected
Referenced by compute_distance_cell_centres_neighbours().
pure_neighbours_corrected_colinearity_
std::vector<std::vector<std::vector<double> > > IJK_One_Dimensional_Subproblem_Geometry::pure_neighbours_corrected_colinearity_ protected
Referenced by compute_distance_cell_centres_neighbours().
dxyz_increment_bool_
int IJK_One_Dimensional_Subproblem_Geometry::dxyz_increment_bool_ = 0 protected
Referenced by compute_distance_cell_centres_neighbours().
dxyz_over_two_increment_bool_
int IJK_One_Dimensional_Subproblem_Geometry::dxyz_over_two_increment_bool_ = 0 protected
Referenced by compute_distance_last_cell_faces_neighbours().
find_cell_neighbours_for_fluxes_spherical_correction_
int IJK_One_Dimensional_Subproblem_Geometry::find_cell_neighbours_for_fluxes_spherical_correction_ = 0 protected
compute_reachable_fluxes_
int IJK_One_Dimensional_Subproblem_Geometry::compute_reachable_fluxes_ = 0 protected
neighbours_last_faces_weighting_
int IJK_One_Dimensional_Subproblem_Geometry::neighbours_last_faces_weighting_ = 0 protected
Referenced by compute_distance_last_cell_faces_neighbours().
neighbours_last_faces_colinearity_weighting_
int IJK_One_Dimensional_Subproblem_Geometry::neighbours_last_faces_colinearity_weighting_ = 0 protected
Referenced by compute_cell_faces_weighting().
neighbours_last_faces_colinearity_face_weighting_
int IJK_One_Dimensional_Subproblem_Geometry::neighbours_last_faces_colinearity_face_weighting_ = 0. protected
Referenced by compute_cell_faces_weighting().
neighbours_last_faces_distance_weighting_
int IJK_One_Dimensional_Subproblem_Geometry::neighbours_last_faces_distance_weighting_ = 0. protected
Referenced by compute_cell_faces_weighting().
neighbours_last_faces_distance_colinearity_weighting_
int IJK_One_Dimensional_Subproblem_Geometry::neighbours_last_faces_distance_colinearity_weighting_ = 0. protected
Referenced by compute_cell_faces_weighting().
neighbours_last_faces_distance_colinearity_face_weighting_
int IJK_One_Dimensional_Subproblem_Geometry::neighbours_last_faces_distance_colinearity_face_weighting_ = 0. protected
Referenced by compute_cell_faces_weighting().
neighbours_face_corrected_rank_
int IJK_One_Dimensional_Subproblem_Geometry::neighbours_face_corrected_rank_ = 1 protected
Referenced by get_dxyz_over_two_increment_max().
pure_neighbours_last_faces_to_correct_
std::vector<std::vector<std::vector<std::vector<bool> > > > IJK_One_Dimensional_Subproblem_Geometry::pure_neighbours_last_faces_to_correct_ protected
Referenced by compute_distance_last_cell_faces_neighbours().
pure_neighbours_last_faces_corrected_distance_
std::vector<std::vector<std::vector<std::vector<double> > > > IJK_One_Dimensional_Subproblem_Geometry::pure_neighbours_last_faces_corrected_distance_ protected
Referenced by compute_distance_last_cell_faces_neighbours().
pure_neighbours_last_faces_corrected_colinearity_
std::vector<std::vector<std::vector<std::vector<double> > > > IJK_One_Dimensional_Subproblem_Geometry::pure_neighbours_last_faces_corrected_colinearity_ protected
Referenced by compute_distance_last_cell_faces_neighbours().