TrioCFD: Masse_PolyMAC_P0P1NC_Face Class Reference
Masse_PolyMAC_P0P1NC_Face Class Reference
#include <Masse_PolyMAC_P0P1NC_Face.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Solveur_Masse_base
virtual DoubleTab & appliquer (DoubleTab &) const
virtual void assembler ()
const Type_info * get_info () const override
virtual void mettre_a_jour (double temps)
virtual void resetTime (double temps)
void set_name_of_coefficient_temporel (const Nom &)
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Masse_PolyMAC_P0P1NC_Face()
Masse_PolyMAC_P0P1NC_Face::Masse_PolyMAC_P0P1NC_Face ()
~Masse_PolyMAC_P0P1NC_Face()
Masse_PolyMAC_P0P1NC_Face::~Masse_PolyMAC_P0P1NC_Face ()
Member Function Documentation
cree_instance()
Objet_U * Masse_PolyMAC_P0P1NC_Face::cree_instance () static
taille_memoire()
unsigned Masse_PolyMAC_P0P1NC_Face::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Masse_PolyMAC_P0P1NC_Face::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Masse_PolyMAC_P0P1NC_Face::info () static
get_info()
const Type_info * Masse_PolyMAC_P0P1NC_Face::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Masse_PolyMAC_P0P1NC_base.
self_cast() [1/2]
Masse_PolyMAC_P0P1NC_Face & Masse_PolyMAC_P0P1NC_Face::self_cast (Objet_U & r) static
self_cast() [2/2]
const Masse_PolyMAC_P0P1NC_Face & Masse_PolyMAC_P0P1NC_Face::self_cast (const Objet_U & r) static
printOn()
Sortie & Masse_PolyMAC_P0P1NC_Face::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Masse_PolyMAC_P0P1NC_base.
References Objet_U::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Masse_PolyMAC_P0P1NC_Face::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Masse_PolyMAC_P0P1NC_base.
completer()
void Masse_PolyMAC_P0P1NC_Face::completer () override virtual
Reimplemented from Masse_PolyMAC_P0P1NC_base.
References Solveur_Masse_Face_proto::associer_masse_proto(), Masse_PolyMAC_base::le_dom_PolyMAC, and TRUST_Ref< _CLASSE_ >::valeur().
appliquer_impl()
DoubleTab & Masse_PolyMAC_P0P1NC_Face::appliquer_impl (DoubleTab & sm) const override virtual
Implements Solveur_Masse_base.
References TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), MorEqn::equation(), Equation_base::inconnue(), Masse_PolyMAC_base::le_dom_PolyMAC, TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Equation_base::milieu(), Milieu_base::porosite_face(), TRUST_Ref< _CLASSE_ >::valeur(), and Champ_Inc_base::valeurs().
corriger_solution()
DoubleTab & Masse_PolyMAC_P0P1NC_Face::corriger_solution (DoubleTab & x, const DoubleTab & y, int incr = 0) const override virtual
Reimplemented from Solveur_Masse_base.
Reimplemented in Masse_PolyMAC_P0_Face.
References Objet_U::dimension, MorEqn::equation(), Equation_base::inconnue(), Masse_PolyMAC_base::le_dom_Cl_PolyMAC, Masse_PolyMAC_base::le_dom_PolyMAC, TRUSTVect< _TYPE_, _SIZE_ >::line_size(), TRUST_Ref< _CLASSE_ >::valeur(), and Champ_Inc_base::valeurs().
dimensionner_blocs()
void Masse_PolyMAC_P0P1NC_Face::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl) const override virtual
Reimplemented from Solveur_Masse_base.
References Solveur_Masse_Face_proto::dimensionner_blocs_proto().
ajouter_blocs()
void Masse_PolyMAC_P0P1NC_Face::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, double dt, const tabs_t & semi_impl, int resoudre_en_increments) const override virtual
Reimplemented from Solveur_Masse_base.
References Solveur_Masse_Face_proto::ajouter_blocs_proto().
Member Data Documentation
info_obj
const Type_info Masse_PolyMAC_P0P1NC_Face::info_obj static