TrioCFD: Echange_contact_Rayo_transp_VDF Class Reference
Echange_contact_Rayo_transp_VDF Class Reference
#include <Echange_contact_Rayo_transp_VDF.h>
Public Member Functions
const Type_info * get_info () const override
void mettre_a_jour (double) override
Public Member Functions inherited from Echange_contact_VDF
const Type_info * get_info () const override
int initialiser (double temps) override
void mettre_a_jour (double) override
Public Member Functions inherited from Echange_global_impose
int compatible_avec_discr (const Discretisation_base &discr) const override
const Type_info * get_info () const override
int initialiser (double temps) override
void mettre_a_jour (double temps) override
Public Member Functions inherited from Echange_impose_base
int a_mettre_a_jour_ss_pas_dt () override
void associer_fr_dis_base (const Frontiere_dis_base &) override
double emissivite (int num) const
double emissivite (int num, int k) const
const Type_info * get_info () const override
virtual double h_imp (int num) const
virtual double h_imp (int num, int k) const
int initialiser (double temps) override
void mettre_a_jour (double) override
virtual Champ_front_base & T_ext ()
virtual double T_ext (int num) const
virtual double T_ext (int num, int k) const
Public Member Functions inherited from Cond_lim_base
virtual int a_mettre_a_jour_ss_pas_dt ()
virtual void associer_domaine_cl_dis_base (const Domaine_Cl_dis_base &)
virtual void associer_fr_dis_base (const Frontiere_dis_base &)
virtual void calculer_coeffs_echange (double temps)
virtual int compatible_avec_discr (const Discretisation_base &) const
Domaine_Cl_dis_base & domaine_Cl_dis ()
const Domaine_Cl_dis_base & domaine_Cl_dis () const
virtual Frontiere_dis_base & frontiere_dis ()
virtual const Frontiere_dis_base & frontiere_dis () const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
void set_modifier_val_imp (int)
virtual void verifie_ch_init_nb_comp () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Cond_lim_base
void err_pas_compatible (const Discretisation_base &) const
void err_pas_compatible (const Equation_base &) const
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Echange_contact_Rayo_transp_VDF()
Echange_contact_Rayo_transp_VDF::Echange_contact_Rayo_transp_VDF ()
~Echange_contact_Rayo_transp_VDF()
Echange_contact_Rayo_transp_VDF::~Echange_contact_Rayo_transp_VDF ()
Member Function Documentation
cree_instance()
Objet_U * Echange_contact_Rayo_transp_VDF::cree_instance () static
taille_memoire()
unsigned Echange_contact_Rayo_transp_VDF::taille_memoire () const override virtual
Reimplemented from Echange_contact_VDF.
Reimplemented in Echange_contact_Rayo_transp_sans_relax_VDF.
duplique()
int Echange_contact_Rayo_transp_VDF::duplique () const override virtual
Reimplemented from Echange_contact_VDF.
Reimplemented in Echange_contact_Rayo_transp_sans_relax_VDF.
info()
const Type_info * Echange_contact_Rayo_transp_VDF::info () static
get_info()
const Type_info * Echange_contact_Rayo_transp_VDF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Echange_contact_VDF.
Reimplemented in Echange_contact_Rayo_transp_sans_relax_VDF.
self_cast() [1/2]
Echange_contact_Rayo_transp_VDF & Echange_contact_Rayo_transp_VDF::self_cast (Objet_U & r) static
self_cast() [2/2]
const Echange_contact_Rayo_transp_VDF & Echange_contact_Rayo_transp_VDF::self_cast (const Objet_U & r) static
printOn()
Sortie & Echange_contact_Rayo_transp_VDF::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Echange_contact_VDF.
Reimplemented in Echange_contact_Rayo_transp_sans_relax_VDF.
Referenced by Echange_contact_Rayo_transp_sans_relax_VDF::printOn().
readOn()
Entree & Echange_contact_Rayo_transp_VDF::readOn (Entree & s) override protected virtual
Simple appel a Echange_impose_base::readOn(Entree&) Lit les specifications des conditions aux limites.
a partir d'un flot d'entree.
Parameters
(Entree& s) un flot d'entree
Returns
(Entree&) le flot de sortie modifie
Reimplemented from Echange_contact_VDF.
Reimplemented in Echange_contact_Rayo_transp_sans_relax_VDF.
References Echange_contact_VDF::readOn().
Referenced by Echange_contact_Rayo_transp_sans_relax_VDF::readOn().
compatible_avec_eqn()
int Echange_contact_Rayo_transp_VDF::compatible_avec_eqn (const Equation_base &) const inline override virtual
Reimplemented from Cond_lim_base.
completer()
void Echange_contact_Rayo_transp_VDF::completer () override virtual
NE FAIT RIEN A surcharger dans les classes derivees.
Reimplemented from Echange_contact_VDF.
References Echange_contact_VDF::completer(), Cond_lim_base::domaine_Cl_dis(), MorEqn::equation(), Domaine_VF::face_voisins(), Cond_lim_base::frontiere_dis(), Equation_base::inconnue(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), Cond_Lim_Rayo::preparer_surface(), Cond_Lim_Rayo::Teta_i, and Champ_Inc_base::valeurs().
mettre_a_jour()
void Echange_contact_Rayo_transp_VDF::mettre_a_jour (double temps) override virtual
Effectue une mise a jour en temps de la condition aux limites.
Parameters
(double temps) le pas de temps de mise a jour
Reimplemented from Echange_contact_VDF.
References Champ_front_base::associer_fr_dis_base(), Echange_contact_VDF::autre_h, Echange_contact_VDF::calculer_h_autre_pb(), Echange_contact_VDF::calculer_h_mon_pb(), calculer_Teta_paroi(), Milieu_base::conductivite(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Domaine_dis_base::domaine(), Cond_lim_base::domaine_Cl_dis(), Domaine_Cl_dis_base::domaine_dis(), Equation_base::domaine_dis(), MorEqn::equation(), Process::exit(), Champ_front_calc::front_dis(), Frontiere_dis_base::frontiere(), Cond_lim_base::frontiere_dis(), Domaine_dis_base::frontiere_dis(), Echange_impose_base::h_imp_, Echange_contact_VDF::h_paroi, Champ_front_calc::inconnue(), Milieu_base::is_rayo_transp(), Objet_U::le_nom(), Frontiere_dis_base::le_nom(), Frontiere_32_64< _SIZE_ >::le_nom(), Champ_front_base::mettre_a_jour(), Echange_global_impose::mettre_a_jour(), Champ_front_calc::milieu(), Probleme_base::milieu(), Field_base::nb_comp(), Front_VF::num_premiere_face(), num_premiere_face_dans_pb_fluide, Equation_base::probleme(), Objet_U::que_suis_je(), Domaine_32_64< _SIZE_ >::raccord(), Echange_contact_VDF::T_autre_pb(), Echange_impose_base::T_ext(), Champ_front_base::valeurs(), and Echange_contact_VDF::verifier_correspondance().
calculer_Teta_paroi()
void Echange_contact_Rayo_transp_VDF::calculer_Teta_paroi (DoubleTab & tab_p, const DoubleTab & mon_h, const DoubleTab & autre_h, int is_pb_fluide, double temps) override virtual
remplit Teta_p utilise T_autre_pb au temps passe en parametre
Reimplemented from Echange_contact_VDF.
References alpha_, Domaine_dis_base::domaine(), Cond_lim_base::domaine_Cl_dis(), Domaine_Cl_dis_base::domaine_dis(), MorEqn::equation(), Process::exit(), Domaine_VF::face_voisins(), Modele_Rayonnement_Milieu_Transparent::flux_radiatif(), Champ_front_calc::front_dis(), Frontiere_dis_base::frontiere(), Cond_lim_base::frontiere_dis(), Equation_base::inconnue(), Milieu_base::is_rayo_transp(), Cond_Lim_Rayo::le_modele_rayo, Frontiere_32_64< _SIZE_ >::le_nom(), Probleme_base::milieu(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), num_premiere_face_dans_pb_fluide, Equation_base::probleme(), Objet_U::que_suis_je(), Domaine_32_64< _SIZE_ >::raccord(), Modele_Rayonnement_Milieu_Transparent::relaxation(), Echange_contact_VDF::T_autre_pb(), Cond_Lim_Rayo::Teta_i, Frontiere_32_64< _SIZE_ >::trace_face_distant(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_Inc_base::valeurs(), Champ_front_var_instationnaire::valeurs_au_temps(), and Debog::verifier().
Referenced by mettre_a_jour().
calculer_Teta_equiv()
void Echange_contact_Rayo_transp_VDF::calculer_Teta_equiv (DoubleTab & Teta_equiv, const DoubleTab & mon_h, const DoubleTab & autre_h, int is_pb_fluide, double temps) override virtual
remplit Teta_eq utilise T_autre_pb au temps passe en parametre
Reimplemented from Echange_contact_VDF.
References Process::exit().
Member Data Documentation
info_obj
const Type_info Echange_contact_Rayo_transp_VDF::info_obj static
num_premiere_face_dans_pb_fluide
int Echange_contact_Rayo_transp_VDF::num_premiere_face_dans_pb_fluide protected
Referenced by calculer_Teta_paroi(), Echange_contact_Rayo_transp_sans_relax_VDF::Echange_contact_Rayo_transp_sans_relax_VDF(), and mettre_a_jour().
alpha_
double Echange_contact_Rayo_transp_VDF::alpha_ protected
Referenced by calculer_Teta_paroi(), and Echange_contact_Rayo_transp_sans_relax_VDF::Echange_contact_Rayo_transp_sans_relax_VDF().