TrioCFD: Ecrire_Fichier_Formatte Class Reference
Ecrire_Fichier_Formatte Class Reference
#include <Ecrire_Fichier_Formatte.h>
Public Member Functions
const Type_info * get_info () const override
Entree & interpreter (Entree &) override
const Type_info * get_info () const override
Public Member Functions inherited from Interprete
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Additional Inherited Members
Static Public Member Functions inherited from Interprete
static Objet_U & objet (const Nom &)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Interprete
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Constructor & Destructor Documentation
Ecrire_Fichier_Formatte()
Ecrire_Fichier_Formatte::Ecrire_Fichier_Formatte ()
~Ecrire_Fichier_Formatte()
Ecrire_Fichier_Formatte::~Ecrire_Fichier_Formatte ()
Member Function Documentation
cree_instance()
Objet_U * Ecrire_Fichier_Formatte::cree_instance () static
taille_memoire()
unsigned Ecrire_Fichier_Formatte::taille_memoire () const override virtual
Reimplemented from Ecrire_Fichier.
duplique()
int Ecrire_Fichier_Formatte::duplique () const override virtual
Reimplemented from Ecrire_Fichier.
info()
const Type_info * Ecrire_Fichier_Formatte::info () static
get_info()
const Type_info * Ecrire_Fichier_Formatte::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Ecrire_Fichier.
self_cast() [1/2]
Ecrire_Fichier_Formatte & Ecrire_Fichier_Formatte::self_cast (Objet_U & r) static
self_cast() [2/2]
const Ecrire_Fichier_Formatte & Ecrire_Fichier_Formatte::self_cast (const Objet_U & r) static
printOn()
Sortie & Ecrire_Fichier_Formatte::printOn (Sortie & x) const override protected virtual
Appel a la methode printOn de la classe Interprete.
Reimplemented from Ecrire_Fichier.
References Interprete::printOn().
readOn()
Entree & Ecrire_Fichier_Formatte::readOn (Entree & is) override protected virtual
Appel a la methode readOn de la classe Interprete.
Reimplemented from Ecrire_Fichier.
References Interprete::readOn().
interpreter()
Entree & Ecrire_Fichier_Formatte::interpreter (Entree & is) override virtual
Interprete sequentiel.
Syntaxe: Ecrire_Fichier_Formatte nom_objet nom_fichier
Reimplemented from Ecrire_Fichier.
References Ecrire_Fichier::interpreter_().
Member Data Documentation
info_obj
const Type_info Ecrire_Fichier_Formatte::info_obj static