TrioCFD: Champ_Fonc_MED_Table_Temps Class Reference
Champ_Fonc_MED_Table_Temps Class Reference
#include <Champ_Fonc_MED_Table_Temps.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Champ_Fonc_MED
const Type_info * get_info () const override
void mettre_a_jour (double) override
DoubleTab & remplir_coord_noeuds (DoubleTab &) const override
int remplir_coord_noeuds_et_polys (DoubleTab &, IntVect &) const override
DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const override
DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &valeurs, int le_poly) const override
DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const override
DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp) const override
DoubleTab & valeurs () override
Public Member Functions inherited from Champ_Fonc_base
Champ_base & affecter_ (const Champ_base &) override
Champ_base & affecter_compo (const Champ_base &, int compo) override
int fixer_nb_valeurs_nodales (int nb_noeuds) override
const Type_info * get_info () const override
void mettre_a_jour (double temps) override
virtual DoubleTab & remplir_coord_noeuds (DoubleTab &) const
virtual DoubleTab & remplir_coord_noeuds_compo (DoubleTab &, int) const
virtual int remplir_coord_noeuds_et_polys (DoubleTab &, IntVect &) const
virtual int remplir_coord_noeuds_et_polys_compo (DoubleTab &, IntVect &, int) const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
DoubleTab & valeur_aux (const DoubleTab &, DoubleTab &) const override
Public Member Functions inherited from Champ_Don_base
void dimensionner (int, int)
int fixer_nb_valeurs_nodales (int nb_noeuds) override
const Type_info * get_info () const override
int imprime (Sortie &, int) const override
virtual int initialiser (const double temps)
void mettre_a_jour (double temps) override
int reprendre (Entree &) override
void resetTime (double time) override
int sauvegarder (Sortie &) const override
DoubleTab & valeurs () override
Public Member Functions inherited from Champ_base
Champ_base & affecter (const Champ_base &)
Champ_base ()
virtual double changer_temps (const double t)
const Type_info * get_info () const override
double temps () const
virtual DoubleTab & trace (const Frontiere_dis_base &, DoubleTab &, double, int distant) const
virtual DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const
virtual double valeur_a_compo (const DoubleVect &position, int ncomp) const
virtual DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &valeurs, int le_poly) const
virtual double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const
virtual DoubleVect & valeur_a_sommet (int, const Domaine &, DoubleVect &) const
virtual DoubleTab & valeur_aux (const DoubleTab &positions, DoubleTab &valeurs) const
virtual DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const
virtual DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const
virtual DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp) const
Public Member Functions inherited from Field_base
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
virtual void fixer_nb_comp (int i)
virtual const Nom & fixer_nom_compo (const Nom &)
virtual const Nom & fixer_nom_compo (int, const Nom &)
virtual const Noms & fixer_noms_compo (const Noms &)
virtual const Nom & fixer_unite (const Nom &)
virtual const Nom & fixer_unite (int i, const Nom &)
virtual const Noms & fixer_unites (const Noms &)
const Type_info * get_info () const override
const Nom & nom_compo (int) const
void nommer (const Nom &) override
const Nom & unite () const
const Nom & unite (int) const
const Noms & unites () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Champ_Proto
int lire_dimension (Entree &, const Nom &)
int lire_dimension (int dim, const Nom &le_nom_)
Protected Member Functions
int lire_motcle_non_standard (const Motcle &, Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
Constructor & Destructor Documentation
Champ_Fonc_MED_Table_Temps()
Champ_Fonc_MED_Table_Temps::Champ_Fonc_MED_Table_Temps ()
~Champ_Fonc_MED_Table_Temps()
Champ_Fonc_MED_Table_Temps::~Champ_Fonc_MED_Table_Temps ()
Member Function Documentation
cree_instance()
Objet_U * Champ_Fonc_MED_Table_Temps::cree_instance () static
taille_memoire()
unsigned Champ_Fonc_MED_Table_Temps::taille_memoire () const override virtual
Reimplemented from Champ_Fonc_MED.
duplique()
int Champ_Fonc_MED_Table_Temps::duplique () const override virtual
Reimplemented from Champ_Fonc_MED.
info()
const Type_info * Champ_Fonc_MED_Table_Temps::info () static
get_info()
const Type_info * Champ_Fonc_MED_Table_Temps::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Champ_Fonc_MED.
self_cast() [1/2]
Champ_Fonc_MED_Table_Temps & Champ_Fonc_MED_Table_Temps::self_cast (Objet_U & r) static
self_cast() [2/2]
const Champ_Fonc_MED_Table_Temps & Champ_Fonc_MED_Table_Temps::self_cast (const Objet_U & r) static
printOn()
Sortie & Champ_Fonc_MED_Table_Temps::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Champ_Fonc_MED.
References Champ_Fonc_MED::printOn().
readOn()
Entree & Champ_Fonc_MED_Table_Temps::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Champ_Fonc_MED.
References Process::exit(), Champ_Fonc_MED::readOn(), and table_lue_.
lire_donnees_champ()
void Champ_Fonc_MED_Table_Temps::lire_donnees_champ (const std::string & fileName, const std::string & meshName, const std::string & fieldName, ArrOfDouble & temps_sauv, int & size, int & nbcomp, Nom & type_champ) override
References Domaine_dis_base::associer_domaine(), Champ_Fonc_base::associer_domaine_dis_base(), Objet_U::dimension, Champ_Fonc_MED::domainebidon_inst, Process::exit(), Field_base::fixer_nb_comp(), Champ_Fonc_base::fixer_nb_valeurs_nodales(), Champ_Fonc_MED::last_time_only_, le_champ0(), Champ_Fonc_MED::mon_dom, Domaine_dis_base::nb_elem(), Objet_U::que_suis_je(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), Objet_U_ptr::typer(), Champ_Fonc_MED::valeurs(), and vrai_champ0_.
lire()
void Champ_Fonc_MED_Table_Temps::lire (double tps, int given_iteration = -1) override virtual
Reimplemented from Champ_Fonc_MED.
References Champ_Fonc_MED::domainebidon_inst, Process::exit(), la_table, Champ_Fonc_MED::le_champ(), le_champ0(), Champ_Fonc_base::mettre_a_jour(), Domaine_dis_base::nb_elem(), Objet_U::que_suis_je(), Table::val(), and Champ_Don_base::valeurs().
instationnaire()
bool Champ_Fonc_MED_Table_Temps::instationnaire () const override virtual
Reimplemented from Champ_Don_base.
References Table::instationnaire(), and la_table.
set_param()
void Champ_Fonc_MED_Table_Temps::set_param (Param & param) override protected virtual
Reimplemented from Champ_Fonc_MED.
References Param::ajouter_non_std(), and Champ_Fonc_MED::set_param().
lire_motcle_non_standard()
int Champ_Fonc_MED_Table_Temps::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override protected virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Objet_U.
References Process::exit(), la_table, Objet_U::lire_motcle_non_standard(), Lecture_Table::lire_table(), Champ_lu_proto::put_file_into_nom(), and table_lue_.
le_champ0() [1/2]
virtual const Champ_Fonc_base & Champ_Fonc_MED_Table_Temps::le_champ0 () const inline protected virtual
References TRUST_Deriv< _CLASSE_ >::valeur(), and vrai_champ0_.
Referenced by lire(), and lire_donnees_champ().
le_champ0() [2/2]
virtual Champ_Fonc_base & Champ_Fonc_MED_Table_Temps::le_champ0 () inline protected virtual
References TRUST_Deriv< _CLASSE_ >::valeur(), and vrai_champ0_.
Member Data Documentation
info_obj
const Type_info Champ_Fonc_MED_Table_Temps::info_obj static
la_table
Table Champ_Fonc_MED_Table_Temps::la_table protected
Referenced by instationnaire(), lire(), and lire_motcle_non_standard().
vrai_champ0_
TRUST_Deriv< Champ_Fonc_base > Champ_Fonc_MED_Table_Temps::vrai_champ0_ protected
Referenced by le_champ0(), and lire_donnees_champ().
table_lue_
bool Champ_Fonc_MED_Table_Temps::table_lue_ = false protected
Referenced by lire_motcle_non_standard(), and readOn().