TrioCFD: Op_Conv_EF_Stab_PolyMAC_P0_Face Class Reference
Op_Conv_EF_Stab_PolyMAC_P0_Face Class Reference
#include <Op_Conv_EF_Stab_PolyMAC_P0_Face.h>
Public Member Functions
double calculer_dt_stab () const override
void completer () override
const Type_info * get_info () const override
Public Member Functions inherited from Op_Conv_EF_Stab_PolyMAC_P0P1NC_Face
double calculer_dt_stab () const override
const Type_info * get_info () const override
Public Member Functions inherited from Op_Conv_EF_Stab_PolyMAC_Face
void completer () override
void dimensionner (Matrice_Morse &mat) const override
const Type_info * get_info () const override
void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const override
Public Member Functions inherited from Op_Conv_PolyMAC_base
double calculer_dt_stab () const override
void completer () override
const Type_info * get_info () const override
int impr (Sortie &os) const override
const Type_info * get_info () const override
Public Member Functions inherited from Operateur_base
void associer_eqn (const Equation_base &)
virtual double calculer_dt_stab () const
virtual void completer ()
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual void mettre_a_jour (double temps)
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Op_Conv_EF_Stab_PolyMAC_P0P1NC_Face
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Op_Conv_PolyMAC_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Op_Conv_EF_Stab_PolyMAC_P0_Face()
Op_Conv_EF_Stab_PolyMAC_P0_Face::Op_Conv_EF_Stab_PolyMAC_P0_Face ()
~Op_Conv_EF_Stab_PolyMAC_P0_Face()
Op_Conv_EF_Stab_PolyMAC_P0_Face::~Op_Conv_EF_Stab_PolyMAC_P0_Face ()
Member Function Documentation
cree_instance()
Objet_U * Op_Conv_EF_Stab_PolyMAC_P0_Face::cree_instance () static
taille_memoire()
unsigned Op_Conv_EF_Stab_PolyMAC_P0_Face::taille_memoire () const override virtual
Reimplemented from Op_Conv_EF_Stab_PolyMAC_Face.
Reimplemented in Op_Conv_Amont_PolyMAC_P0_Face, and Op_Conv_Centre_PolyMAC_P0_Face.
duplique()
int Op_Conv_EF_Stab_PolyMAC_P0_Face::duplique () const override virtual
Reimplemented from Op_Conv_EF_Stab_PolyMAC_Face.
Reimplemented in Op_Conv_Amont_PolyMAC_P0_Face, and Op_Conv_Centre_PolyMAC_P0_Face.
info()
const Type_info * Op_Conv_EF_Stab_PolyMAC_P0_Face::info () static
get_info()
const Type_info * Op_Conv_EF_Stab_PolyMAC_P0_Face::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Op_Conv_EF_Stab_PolyMAC_Face.
Reimplemented in Op_Conv_Amont_PolyMAC_P0_Face, and Op_Conv_Centre_PolyMAC_P0_Face.
self_cast() [1/2]
Op_Conv_EF_Stab_PolyMAC_P0_Face & Op_Conv_EF_Stab_PolyMAC_P0_Face::self_cast (Objet_U & r) static
self_cast() [2/2]
const Op_Conv_EF_Stab_PolyMAC_P0_Face & Op_Conv_EF_Stab_PolyMAC_P0_Face::self_cast (const Objet_U & r) static
printOn()
Sortie & Op_Conv_EF_Stab_PolyMAC_P0_Face::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN A surcharger dans les classes derivees.
Parameters
(Sortie& os) un flot de sortie
Returns
(Sortie&) le flot de sortie
Reimplemented from Op_Conv_EF_Stab_PolyMAC_Face.
Reimplemented in Op_Conv_Amont_PolyMAC_P0_Face, and Op_Conv_Centre_PolyMAC_P0_Face.
References Op_Conv_PolyMAC_base::printOn().
readOn()
Entree & Op_Conv_EF_Stab_PolyMAC_P0_Face::readOn (Entree & is) override protected virtual
NE FAIT RIEN A surcharger dans les classes derivees.
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree
Reimplemented from Op_Conv_EF_Stab_PolyMAC_Face.
Reimplemented in Op_Conv_Amont_PolyMAC_P0_Face, and Op_Conv_Centre_PolyMAC_P0_Face.
References Op_Conv_EF_Stab_PolyMAC_Face::readOn().
completer()
void Op_Conv_EF_Stab_PolyMAC_P0_Face::completer () override virtual
Associe l'operateur au domaine_dis, le domaine_Cl_dis, et a l'inconnue de son equation.
Exceptions
pas d'equation associee
Reimplemented from Op_Conv_EF_Stab_PolyMAC_Face.
References Op_Conv_EF_Stab_PolyMAC_Face::completer(), TRUST_Ref< _CLASSE_ >::valeur(), and Op_Conv_PolyMAC_base::vitesse_.
calculer_dt_stab()
double Op_Conv_EF_Stab_PolyMAC_P0_Face::calculer_dt_stab () const override virtual
Calcul dt_stab.
Returns
(double) renvoie toujours 1.e30
Reimplemented from Operateur_base.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), MorEqn::equation(), Champ_Face_base::fcl(), Op_Conv_PolyMAC_base::le_dom_poly_, TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Equation_base::milieu(), Process::mp_min(), Milieu_base::porosite_elem(), Milieu_base::porosite_face(), Option_PolyMAC::TRAITEMENT_AXI, TRUST_Ref< _CLASSE_ >::valeur(), and Op_Conv_PolyMAC_base::vitesse_.
dimensionner_blocs()
void Op_Conv_EF_Stab_PolyMAC_P0_Face::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl = { }) const override virtual
Reimplemented from Operateur_base.
References Matrix_tools::allocate_morse_matrix(), TRUSTTab< _TYPE_, _SIZE_ >::append_line(), Objet_U::dimension, MorEqn::equation(), Champ_Face_base::fcl(), Probleme_base::get_correlation(), Nom::getString(), Probleme_base::has_correlation(), Equation_base::inconnue(), Op_Conv_PolyMAC_base::le_dom_poly_, Field_base::le_nom(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Matrice_Morse::nb_colonnes(), TRUST_Ref< _CLASSE_ >::valeur(), and Champ_Inc_base::valeurs().
ajouter_blocs()
void Op_Conv_EF_Stab_PolyMAC_P0_Face::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = { }) const override virtual
Reimplemented from Operateur_base.
References Masse_ajoutee_base::ajouter(), Op_Conv_EF_Stab_PolyMAC_Face::alpha_, Statistiques::begin_count(), Equation_base::champ_conserve(), Objet_U::dimension, Statistiques::end_count(), MorEqn::equation(), Pb_Multiphase::equation_masse(), Champ_Face_base::fcl(), Probleme_base::get_correlation(), Nom::getString(), Probleme_base::has_correlation(), Operateur_Conv_base::incompressible_, Equation_base::inconnue(), Op_Conv_PolyMAC_base::la_zcl_poly_, Op_Conv_PolyMAC_base::le_dom_poly_, Field_base::le_nom(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Milieu_base::masse_volumique(), Equation_base::milieu(), Champ_Proto::passe(), Champ_Inc_base::passe(), Op_Conv_EF_Stab_PolyMAC_Face::porosite_e, Op_Conv_EF_Stab_PolyMAC_Face::porosite_f, TRUST_Ref< _CLASSE_ >::valeur(), and Champ_Inc_base::valeurs().
Member Data Documentation
info_obj
const Type_info Op_Conv_EF_Stab_PolyMAC_P0_Face::info_obj static