TrioCFD: Viscosite_turbulente_LES_base Class Reference
Viscosite_turbulente_LES_base Class Reference
#include <Viscosite_turbulente_LES_base.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Viscosite_turbulente_LES_base()
Viscosite_turbulente_LES_base::Viscosite_turbulente_LES_base ()
~Viscosite_turbulente_LES_base()
Viscosite_turbulente_LES_base::~Viscosite_turbulente_LES_base () override
Member Function Documentation
info()
const Type_info * Viscosite_turbulente_LES_base::info () static
get_info()
const Type_info * Viscosite_turbulente_LES_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Viscosite_turbulente_base.
Reimplemented in Viscosite_turbulente_Smagorinsky, and Viscosite_turbulente_WALE.
self_cast() [1/2]
Viscosite_turbulente_LES_base & Viscosite_turbulente_LES_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Viscosite_turbulente_LES_base & Viscosite_turbulente_LES_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Viscosite_turbulente_LES_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Viscosite_turbulente_base.
Reimplemented in Viscosite_turbulente_Smagorinsky, and Viscosite_turbulente_WALE.
readOn()
Entree & Viscosite_turbulente_LES_base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Viscosite_turbulente_base.
Reimplemented in Viscosite_turbulente_Smagorinsky, and Viscosite_turbulente_WALE.
Referenced by Viscosite_turbulente_Smagorinsky::readOn(), and Viscosite_turbulente_WALE::readOn().
reynolds_stress()
void Viscosite_turbulente_LES_base::reynolds_stress (DoubleTab & R_ij) const inline override virtual
Implements Viscosite_turbulente_base.
References Process::exit().
k_over_eps()
void Viscosite_turbulente_LES_base::k_over_eps (DoubleTab & k_sur_eps) const inline override virtual
Implements Viscosite_turbulente_base.
References Process::exit().
eps()
void Viscosite_turbulente_LES_base::eps (DoubleTab & eps) const inline override virtual
Implements Viscosite_turbulente_base.
References Process::exit().
Member Data Documentation
info_obj
const Type_info Viscosite_turbulente_LES_base::info_obj static
mod_const_
double Viscosite_turbulente_LES_base::mod_const_ = -123. protected
Referenced by Viscosite_turbulente_Smagorinsky::eddy_viscosity(), Viscosite_turbulente_WALE::eddy_viscosity(), Viscosite_turbulente_Smagorinsky::readOn(), and Viscosite_turbulente_WALE::readOn().
l_
DoubleVect Viscosite_turbulente_LES_base::l_ protected
Referenced by Viscosite_turbulente_Smagorinsky::eddy_viscosity(), and Viscosite_turbulente_WALE::eddy_viscosity().