TrioCFD: Collision_Model_FT_arbitrary Class Reference
Collision_Model_FT_arbitrary Class Reference
#include <Collision_Model_FT_arbitrary.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Collision_Model_FT_base
const Type_info * get_info () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
int reprendre (Entree &is) override
int sauvegarder (Sortie &os) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Collision_Model_FT_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
~Collision_Model_FT_arbitrary()
Collision_Model_FT_arbitrary::~Collision_Model_FT_arbitrary ()
Collision_Model_FT_arbitrary()
Collision_Model_FT_arbitrary::Collision_Model_FT_arbitrary ()
Member Function Documentation
cree_instance()
Objet_U * Collision_Model_FT_arbitrary::cree_instance () static
taille_memoire()
unsigned Collision_Model_FT_arbitrary::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Collision_Model_FT_arbitrary::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Collision_Model_FT_arbitrary::info () static
get_info()
const Type_info * Collision_Model_FT_arbitrary::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
Collision_Model_FT_arbitrary & Collision_Model_FT_arbitrary::self_cast (Objet_U & r) static
self_cast() [2/2]
const Collision_Model_FT_arbitrary & Collision_Model_FT_arbitrary::self_cast (const Objet_U & r) static
printOn()
Sortie & Collision_Model_FT_arbitrary::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
References Process::exit().
readOn()
Entree & Collision_Model_FT_arbitrary::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
References Collision_Model_FT_base::readOn().
compute_lagrangian_contact_forces()
void Collision_Model_FT_arbitrary::compute_lagrangian_contact_forces (const Fluide_Diphasique & two_phase_fluid, const DoubleTab & particles_position, const DoubleTab & particles_velocity, const double & deltat_simu) override virtual
Implements Collision_Model_FT_base.
References Process::exit().
discretize_contact_forces_eulerian_field()
void Collision_Model_FT_arbitrary::discretize_contact_forces_eulerian_field (const DoubleTab & volumic_phase_indicator_function, const Domaine_VF & domain_vf, const IntTab & particles_eulerian_id_number, DoubleTab & contact_force_source_term) override virtual
Implements Collision_Model_FT_base.
References Process::exit().
Member Data Documentation
info_obj
const Type_info Collision_Model_FT_arbitrary::info_obj static