TrioCFD: Simd_Array_template< _TYPE_, N > Class Template Reference
Simd_Array_template< _TYPE_, N > Class Template Reference
#include <Simd_Array_template.h>
Member Function Documentation
operator[]() [1/2]
template<typename _TYPE_ , int N> _TYPE_ & Simd_Array_template< _TYPE_, N >::operator[] (int i) inline
References Simd_Array_template< _TYPE_, N >::data_.
operator[]() [2/2]
template<typename _TYPE_ , int N> const _TYPE_ & Simd_Array_template< _TYPE_, N >::operator[] (int i) const inline
References Simd_Array_template< _TYPE_, N >::data_.
SimdGet()
template<typename _TYPE_ , int N> Simd_template< _TYPE_ > Simd_Array_template< _TYPE_, N >::SimdGet (int vector_index) const inline
References Simd_Array_template< _TYPE_, N >::data_, and Simd_Array_template< _TYPE_, N >::SimdGet().
Referenced by Simd_Array_template< _TYPE_, N >::SimdGet().
SimdPut()
template<typename _TYPE_ , int N> void Simd_Array_template< _TYPE_, N >::SimdPut (int vector_index, const Simd_template< _TYPE_ > & x) inline
References Simd_Array_template< _TYPE_, N >::data_, and Simd_Array_template< _TYPE_, N >::SimdPut().
Referenced by Simd_Array_template< _TYPE_, N >::SimdPut().
Member Data Documentation
data_
template<typename _TYPE_ , int N> _TYPE_ Simd_Array_template< _TYPE_, N >::data_[N] protected
Referenced by Simd_Array_template< _TYPE_, N >::operator[](), Simd_Array_template< _TYPE_, N >::SimdGet(), and Simd_Array_template< _TYPE_, N >::SimdPut().