TrioCFD: Op_Dift_Multiphase_proto Class Reference
Op_Dift_Multiphase_proto Class Reference
#include <Op_Dift_Multiphase_proto.h>
Member Function Documentation
associer_proto()
void Op_Dift_Multiphase_proto::associer_proto (const Probleme_base & pb, Champs_compris & ch)
References is_pbm_, le_chmp_compris_, pbm_, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Op_Diff_Turbulent_PolyMAC_P0_Elem::readOn(), Op_Diff_Turbulent_PolyMAC_P0_Face::readOn(), Op_Dift_Multiphase_VDF_Elem::readOn(), and Op_Dift_Multiphase_VDF_Face::readOn().
correlation()
const Correlation_base & Op_Dift_Multiphase_proto::correlation () const inline
References corr_.
Referenced by Coalescence_bulles_1groupe_PolyMAC_P0::ajouter_blocs(), Coalescence_bulles_2groupes_PolyMAC_P0::ajouter_blocs(), Flux_2groupes_PolyMAC_P0::ajouter_blocs(), Rupture_bulles_1groupe_PolyMAC_P0::ajouter_blocs(), Rupture_bulles_2groupes_PolyMAC_P0::ajouter_blocs(), Source_BIF_PolyMAC_P0::ajouter_blocs(), and Correction_Lubchenko_PolyMAC_P0::ajouter_blocs_BIF().
ajout_champs_proto_face()
void Op_Dift_Multiphase_proto::ajout_champs_proto_face () inline
Referenced by Op_Diff_Turbulent_PolyMAC_P0_Face::readOn(), and Op_Dift_Multiphase_VDF_Face::readOn().
ajout_champs_proto_elem()
void Op_Dift_Multiphase_proto::ajout_champs_proto_elem () inline
Referenced by Op_Diff_Turbulent_PolyMAC_P0_Elem::readOn(), and Op_Dift_Multiphase_VDF_Elem::readOn().
get_noms_champs_postraitables_proto()
void Op_Dift_Multiphase_proto::get_noms_champs_postraitables_proto (const Nom & classe, Noms & nom, Option opt) const
References TRUST_Vector< _CLASSE_ >::add(), is_pbm_, noms_mu_ou_alpha_turb_post_, noms_nu_ou_lambda_turb_post_, pbm_, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Op_Diff_Turbulent_PolyMAC_P0_Elem::get_noms_champs_postraitables(), Op_Diff_Turbulent_PolyMAC_P0_Face::get_noms_champs_postraitables(), Op_Dift_Multiphase_VDF_Elem::get_noms_champs_postraitables(), and Op_Dift_Multiphase_VDF_Face::get_noms_champs_postraitables().
creer_champ_proto_face()
void Op_Dift_Multiphase_proto::creer_champ_proto_face (const Motcle & motlu) inline
Referenced by Op_Diff_Turbulent_PolyMAC_P0_Face::creer_champ(), and Op_Dift_Multiphase_VDF_Face::creer_champ().
creer_champ_proto_elem()
void Op_Dift_Multiphase_proto::creer_champ_proto_elem (const Motcle & motlu) inline
Referenced by Op_Diff_Turbulent_PolyMAC_P0_Elem::creer_champ(), and Op_Dift_Multiphase_VDF_Elem::creer_champ().
completer_proto_face()
void Op_Dift_Multiphase_proto::completer_proto_face (const Operateur_Diff_base & op) inline
Referenced by Op_Diff_Turbulent_PolyMAC_P0_Face::completer(), and Op_Dift_Multiphase_VDF_Face::completer().
completer_proto_elem()
void Op_Dift_Multiphase_proto::completer_proto_elem (const Operateur_Diff_base & op) inline
Referenced by Op_Diff_Turbulent_PolyMAC_P0_Elem::completer(), and Op_Dift_Multiphase_VDF_Elem::completer().
mettre_a_jour_proto_face()
void Op_Dift_Multiphase_proto::mettre_a_jour_proto_face (const double temps) inline
Referenced by Op_Diff_Turbulent_PolyMAC_P0_Face::mettre_a_jour(), and Op_Dift_Multiphase_VDF_Face::mettre_a_jour().
mettre_a_jour_proto_elem()
void Op_Dift_Multiphase_proto::mettre_a_jour_proto_elem (const double temps) inline
Referenced by Op_Diff_Turbulent_PolyMAC_P0_Elem::mettre_a_jour(), and Op_Dift_Multiphase_VDF_Elem::mettre_a_jour().
viscosite_turbulente()
DoubleTab & Op_Dift_Multiphase_proto::viscosite_turbulente () inline
References nu_ou_lambda_turb_.
diffusivite_turbulente()
DoubleTab & Op_Dift_Multiphase_proto::diffusivite_turbulente () inline
References nu_ou_lambda_turb_.
call_compute_nu_turb()
void Op_Dift_Multiphase_proto::call_compute_nu_turb () inline
References corr_, nu_ou_lambda_turb_, and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by Op_Diff_Turbulent_PolyMAC_P0_Face::mettre_a_jour(), Op_Dift_Multiphase_VDF_Face::mettre_a_jour(), Op_Diff_Turbulent_PolyMAC_P0_Face::preparer_calcul(), and Op_Dift_Multiphase_VDF_Face::preparer_calcul().
call_compute_diff_turb()
void Op_Dift_Multiphase_proto::call_compute_diff_turb (const Convection_Diffusion_std & eq, const Viscosite_turbulente_base & visc_turb) inline
References corr_, nu_ou_lambda_turb_, and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by Op_Dift_Multiphase_VDF_Elem::mettre_a_jour().
Member Data Documentation
is_pbm_
bool Op_Dift_Multiphase_proto::is_pbm_ = true protected
Referenced by associer_proto(), and get_noms_champs_postraitables_proto().
nu_ou_lambda_turb_
DoubleTab Op_Dift_Multiphase_proto::nu_ou_lambda_turb_ protected
Referenced by Op_Dift_Multiphase_VDF_Elem::calculer_dt_stab(), Op_Dift_Multiphase_VDF_Face::calculer_dt_stab(), call_compute_diff_turb(), call_compute_nu_turb(), Op_Dift_Multiphase_VDF_Elem::completer(), Op_Dift_Multiphase_VDF_Face::completer(), diffusivite_turbulente(), Op_Diff_Turbulent_PolyMAC_P0_Face::mettre_a_jour(), Op_Dift_Multiphase_VDF_Elem::mettre_a_jour(), Op_Dift_Multiphase_VDF_Face::mettre_a_jour(), Op_Diff_Turbulent_PolyMAC_P0_Elem::modifier_mu(), Op_Diff_Turbulent_PolyMAC_P0_Face::modifier_mu(), and viscosite_turbulente().
corr_
TRUST_Deriv< Correlation_base > Op_Dift_Multiphase_proto::corr_ protected
Referenced by call_compute_diff_turb(), call_compute_nu_turb(), Op_Dift_Multiphase_VDF_Elem::completer(), Op_Dift_Multiphase_VDF_Face::completer(), correlation(), Op_Dift_Multiphase_VDF_Elem::correlation(), Op_Diff_Turbulent_PolyMAC_P0_Elem::correlation_viscosite_turbulente(), Op_Diff_Turbulent_PolyMAC_P0_Face::correlation_viscosite_turbulente(), Op_Dift_Multiphase_VDF_Elem::correlation_viscosite_turbulente(), Op_Dift_Multiphase_VDF_Face::correlation_viscosite_turbulente(), Op_Diff_Turbulent_PolyMAC_P0_Elem::dimension_min_nu(), Op_Diff_Turbulent_PolyMAC_P0_Elem::modifier_mu(), Op_Diff_Turbulent_PolyMAC_P0_Face::modifier_mu(), Op_Diff_Turbulent_PolyMAC_P0_Elem::readOn(), Op_Diff_Turbulent_PolyMAC_P0_Face::readOn(), Op_Dift_Multiphase_VDF_Elem::readOn(), and Op_Dift_Multiphase_VDF_Face::readOn().
nu_ou_lambda_turb_post_
std::vector<TRUST_Deriv< Champ_Fonc_base > > Op_Dift_Multiphase_proto::nu_ou_lambda_turb_post_ protected
mu_ou_alpha_turb_post_
std::vector<TRUST_Deriv< Champ_Fonc_base > > Op_Dift_Multiphase_proto::mu_ou_alpha_turb_post_ protected
noms_nu_ou_lambda_turb_post_
Motcles Op_Dift_Multiphase_proto::noms_nu_ou_lambda_turb_post_ protected
Referenced by get_noms_champs_postraitables_proto().
noms_mu_ou_alpha_turb_post_
Motcles Op_Dift_Multiphase_proto::noms_mu_ou_alpha_turb_post_ protected
Referenced by get_noms_champs_postraitables_proto().
pbm_
TRUST_Ref< Probleme_base *> Op_Dift_Multiphase_proto::pbm_ protected
Referenced by associer_proto(), and get_noms_champs_postraitables_proto().
le_chmp_compris_
TRUST_Ref< Champs_compris *> Op_Dift_Multiphase_proto::le_chmp_compris_ protected
Referenced by associer_proto().