TrioCFD: EcritureLectureSpecial Class Reference
EcritureLectureSpecial Class Reference
#include <EcritureLectureSpecial.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions
static int ecriture_special (const Champ_base &ch, Sortie &fich)
static Nom & get_Output ()
static int is_ecriture_special (int &special, int &a_faire)
static int is_lecture_special ()
Static Public Member Functions inherited from Interprete
static Objet_U & objet (const Nom &)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Constructor & Destructor Documentation
EcritureLectureSpecial()
EcritureLectureSpecial::EcritureLectureSpecial ()
~EcritureLectureSpecial()
EcritureLectureSpecial::~EcritureLectureSpecial ()
Member Function Documentation
cree_instance()
Objet_U * EcritureLectureSpecial::cree_instance () static
taille_memoire()
unsigned EcritureLectureSpecial::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int EcritureLectureSpecial::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * EcritureLectureSpecial::info () static
get_info()
const Type_info * EcritureLectureSpecial::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Interprete.
self_cast() [1/2]
EcritureLectureSpecial & EcritureLectureSpecial::self_cast (Objet_U & r) static
self_cast() [2/2]
const EcritureLectureSpecial & EcritureLectureSpecial::self_cast (const Objet_U & r) static
printOn()
Sortie & EcritureLectureSpecial::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Interprete.
readOn()
Entree & EcritureLectureSpecial::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Interprete.
interpreter()
Entree & EcritureLectureSpecial::interpreter (Entree & fich) override virtual
Implements Interprete.
References Active, and Process::exit().
lecture_special() [1/2]
void EcritureLectureSpecial::lecture_special (Champ_base & ch, Entree & fich) static
simple appel a EcritureLectureSpecial::lecture_special (const Domaine_VF& zvf,Entree& fich,int nbval, DoubleTab& val)
References Champ_base::domaine_dis_base(), lecture_special(), and Champ_Proto::valeurs().
Referenced by lecture_special(), Modele_turbulence_hyd_base::lire_distance_paroi(), Modele_turbulence_hyd_Longueur_Melange_VEF::lire_distance_paroi(), Modele_Lam_Bremhorst_VEF::lire_distance_paroi(), Champ_Fonc_base::reprendre(), and Champ_Inc_base::reprendre().
lecture_special() [2/2]
void EcritureLectureSpecial::lecture_special (const Domaine_VF & zvf, Entree & fich, DoubleTab & val) static
codage de la relecture d'un champ a partir d'un fichier special positions,valeurs
References TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Process::exit(), TRUSTVect< _TYPE_, _SIZE_ >::get_md_vector(), MD_Vector_base::nb_items_seq_tot(), and MD_Vector::non_nul().
ecriture_special() [1/2]
int EcritureLectureSpecial::ecriture_special (const Champ_base & ch, Sortie & fich) static
simple appel a EcritureLectureSpecial::ecriture_special (const Domaine_VF& zvf,Sortie& fich,int nbval,const DoubleTab& val)
apres avoir recupere le tableau val
References Champ_base::domaine_dis_base(), ecriture_special(), and Champ_Proto::valeurs().
Referenced by ecriture_special(), Champ_Fonc_base::sauvegarder(), and Champ_Inc_base::sauvegarder().
ecriture_special() [2/2]
int EcritureLectureSpecial::ecriture_special (const Domaine_VF & zvf, Sortie & fich, const DoubleTab & val) static
codage de l'ecriture des positions et des valeurs de val
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Process::exit(), TRUSTVect< _TYPE_, _SIZE_ >::get_md_vector(), Process::je_suis_maitre(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), MD_Vector_base::nb_items_seq_tot(), MD_Vector::non_nul(), and Sortie::syncfile().
is_lecture_special()
int EcritureLectureSpecial::is_lecture_special () static
indique si le format special a ete demande en lecture active par reprise xyz .
...
References mode_lec.
Referenced by Navier_Stokes_std_ALE::reprendre(), Maillage_FT_Disc::reprendre(), Transport_Interfaces_FT_Disc::reprendre(), Champ_Fonc_base::reprendre(), Champ_Inc_base::reprendre(), Collision_Model_FT_base::reprendre(), and Convection_Diffusion_Fluide_Dilatable_Proto::Reprendre_WC().
is_ecriture_special()
int EcritureLectureSpecial::is_ecriture_special (int & special, int & a_faire) static
indique si le format special a ete demande en lecture active par sauvegarde xyz .
... si le mode ecriture est special c.a.d si format de sauvegarde xyz alors special =1 a_faire=je_suis_maitre sinon special=0 , a_faire=1
References TRUST_2_PDI::is_PDI_checkpoint(), Process::je_suis_maitre(), and mode_ecr.
Referenced by Modele_turbulence_hyd_base::a_faire(), Modele_turbulence_scal_base::a_faire(), Navier_Stokes_std_ALE::sauvegarder(), Maillage_FT_Disc::sauvegarder(), Remaillage_FT::sauvegarder(), Transport_Interfaces_FT_Disc::sauvegarder(), Champ_Fonc_base::sauvegarder(), Champ_Inc_base::sauvegarder(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::sauvegarder(), Modele_turbulence_hyd_null::sauvegarder(), Collision_Model_FT_base::sauvegarder(), Transport_Interfaces_FT_Disc_interne::sauvegarder(), Postraitement::sauvegarder(), Operateurs_Statistique_tps::sauvegarder(), and Convection_Diffusion_Fluide_Dilatable_Proto::Sauvegarder_WC().
get_Output()
Nom & EcritureLectureSpecial::get_Output () static
Renvoie le mode d'ecriture utilise (pour pouvoir le modifier).
Cette methode est statique.
References Process::is_sequential(), and Output.
Referenced by Transport_Interfaces_FT_Disc_interne::init_save_file(), Save_Restart::sauver(), and Save_Restart::sauver_xyz().
Member Data Documentation
info_obj
const Type_info EcritureLectureSpecial::info_obj static
Active
int EcritureLectureSpecial::Active =1 static
Referenced by Save_Restart::allocation(), Save_Restart::finir(), interpreter(), Save_Restart::lire_sauvegarde_reprise(), and Save_Restart::preparer_calcul().
mode_ecr
int EcritureLectureSpecial::mode_ecr =-1 static
Referenced by is_ecriture_special(), Transport_Interfaces_FT_Disc_interne::sauvegarder(), Save_Restart::sauver(), and Save_Restart::sauver_xyz().
mode_lec
int EcritureLectureSpecial::mode_lec =0 static
Referenced by is_lecture_special(), Transport_Interfaces_FT_Disc::lire_cond_init(), Champ_Fonc_reprise::readOn(), and Transport_Interfaces_FT_Disc_interne::reprendre().
Input
Nom EcritureLectureSpecial::Input ="LecFicDiffuseBin" static
Referenced by Champ_Fonc_reprise::readOn(), and Transport_Interfaces_FT_Disc_interne::reprendre().
Output
Nom EcritureLectureSpecial::Output ="EcrFicPartageMPIIO" static
Referenced by get_Output().