TrioCFD: Frottement_interfacial_Ishii_Zuber_Deformable Class Reference
Frottement_interfacial_Ishii_Zuber_Deformable Class Reference
#include <Frottement_interfacial_Ishii_Zuber_Deformable.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Frottement_interfacial_Ishii_Zuber_Deformable()
Frottement_interfacial_Ishii_Zuber_Deformable::Frottement_interfacial_Ishii_Zuber_Deformable ()
~Frottement_interfacial_Ishii_Zuber_Deformable()
Frottement_interfacial_Ishii_Zuber_Deformable::~Frottement_interfacial_Ishii_Zuber_Deformable ()
Member Function Documentation
cree_instance()
Objet_U * Frottement_interfacial_Ishii_Zuber_Deformable::cree_instance () static
taille_memoire()
unsigned Frottement_interfacial_Ishii_Zuber_Deformable::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Frottement_interfacial_Ishii_Zuber_Deformable::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Frottement_interfacial_Ishii_Zuber_Deformable::info () static
get_info()
const Type_info * Frottement_interfacial_Ishii_Zuber_Deformable::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Frottement_interfacial_base.
self_cast() [1/2]
Frottement_interfacial_Ishii_Zuber_Deformable & Frottement_interfacial_Ishii_Zuber_Deformable::self_cast (Objet_U & r) static
self_cast() [2/2]
const Frottement_interfacial_Ishii_Zuber_Deformable & Frottement_interfacial_Ishii_Zuber_Deformable::self_cast (const Objet_U & r) static
printOn()
Sortie & Frottement_interfacial_Ishii_Zuber_Deformable::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Frottement_interfacial_base.
readOn()
Entree & Frottement_interfacial_Ishii_Zuber_Deformable::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Frottement_interfacial_base.
References Param::ajouter(), beta_, Nom::debute_par(), Process::exit(), g_, Param::lire_avec_accolades_depuis(), Probleme_base::milieu(), n_l, Pb_Multiphase::nb_phases(), Pb_Multiphase::nom_phase(), Correlation_base::pb_, Objet_U::que_suis_je(), and TRUST_Ref< _CLASSE_ >::valeur().
coefficient()
void Frottement_interfacial_Ishii_Zuber_Deformable::coefficient (const DoubleTab & alpha, const DoubleTab & p, const DoubleTab & T, const DoubleTab & rho, const DoubleTab & mu, const DoubleTab & sigma, double Dh, const DoubleTab & ndv, const DoubleTab & d_bulles, DoubleTab & coeff) const override virtual
Implements Frottement_interfacial_base.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), and n_l.
coefficient_CD()
void Frottement_interfacial_Ishii_Zuber_Deformable::coefficient_CD (const DoubleTab & alpha, const DoubleTab & p, const DoubleTab & T, const DoubleTab & rho, const DoubleTab & mu, const DoubleTab & sigma, double Dh, const DoubleTab & ndv, const DoubleTab & d_bulles, DoubleTab & coeff) const override virtual
Reimplemented from Frottement_interfacial_base.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), and n_l.
Member Data Documentation
info_obj
const Type_info Frottement_interfacial_Ishii_Zuber_Deformable::info_obj static
g_
double Frottement_interfacial_Ishii_Zuber_Deformable::g_ = 9.81 protected
Referenced by readOn().
beta_
double Frottement_interfacial_Ishii_Zuber_Deformable::beta_ = 1. protected
Referenced by readOn().
n_l
int Frottement_interfacial_Ishii_Zuber_Deformable::n_l = -1 protected
Referenced by coefficient(), coefficient_CD(), and readOn().