TrioCFD: Boundary_Conditions Class Reference
Boundary_Conditions Class Reference
#include <Boundary_Conditions.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Member Enumeration Documentation
BCType
enum Boundary_Conditions::BCType
Enumerator
Paroi
Symetrie
Perio
Mixte_shear
Constructor & Destructor Documentation
Boundary_Conditions()
Boundary_Conditions::Boundary_Conditions ()
References bctype_kmax_, bctype_kmin_, conserv_qdm_, defilement_, dU_perio_, interp_monofluide_, order_interpolation_poisson_solver_, Paroi, resolution_u_prime_, t0_shear_, vxkmax_, and vxkmin_.
~Boundary_Conditions()
Boundary_Conditions::~Boundary_Conditions ()
Member Function Documentation
cree_instance()
Objet_U * Boundary_Conditions::cree_instance () static
taille_memoire()
unsigned Boundary_Conditions::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Boundary_Conditions::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Boundary_Conditions::info () static
get_info()
const Type_info * Boundary_Conditions::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
Boundary_Conditions & Boundary_Conditions::self_cast (Objet_U & r) static
self_cast() [2/2]
const Boundary_Conditions & Boundary_Conditions::self_cast (const Objet_U & r) static
printOn()
Sortie & Boundary_Conditions::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
readOn()
Entree & Boundary_Conditions::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
References Param::ajouter(), bctype_kmax_, bctype_kmin_, conserv_qdm_, defilement_, IJK_Shear_Periodic_helpler::defilement_, Param::dictionnaire(), dU_perio_, interp_monofluide_, Param::lire_avec_accolades(), Mixte_shear, order_interpolation_poisson_solver_, IJK_Shear_Periodic_helpler::order_interpolation_poisson_solver_, Paroi, Perio, Objet_U::que_suis_je(), Param::REQUIRED, resolution_u_prime_, IJK_Shear_Periodic_helpler::shear_x_time_, t0_shear_, vxkmax_, and vxkmin_.
get_bctype_k_min()
BCType Boundary_Conditions::get_bctype_k_min () const inline
References bctype_kmin_.
get_bctype_k_max()
BCType Boundary_Conditions::get_bctype_k_max () const inline
References bctype_kmax_.
set_vx_kmin()
void Boundary_Conditions::set_vx_kmin (double value) inline
References vxkmin_.
set_vx_kmax()
void Boundary_Conditions::set_vx_kmax (double value) inline
References vxkmax_.
set_dU_perio()
void Boundary_Conditions::set_dU_perio (double value) inline
References dU_perio_.
get_vx_kmin()
double Boundary_Conditions::get_vx_kmin () const inline
References vxkmin_.
get_vx_kmax()
double Boundary_Conditions::get_vx_kmax () const inline
References vxkmax_.
get_dU_perio()
double Boundary_Conditions::get_dU_perio (int fluctuations = 0) const inline
References dU_perio_.
Referenced by Navier_Stokes_FTD_IJK::calculer_vitesse_ft(), Navier_Stokes_FTD_IJK::complete_initialise_ijk_fields(), Navier_Stokes_FTD_IJK::initialise_ijk_fields(), Probleme_FTD_IJK_base::reprendre_probleme(), Probleme_FTD_IJK_base::solveTimeStep(), and Navier_Stokes_FTD_IJK::update_v_ghost_from_rho_v().
get_t0_shear()
double Boundary_Conditions::get_t0_shear () const inline
References t0_shear_.
Referenced by Navier_Stokes_FTD_IJK::complete_initialise_ijk_fields(), Navier_Stokes_FTD_IJK::initialise_ijk_fields(), Probleme_FTD_IJK_base::reprendre_probleme(), and Probleme_FTD_IJK_base::solveTimeStep().
get_defilement()
int Boundary_Conditions::get_defilement () const inline
References defilement_.
get_correction_interp_monofluide()
int Boundary_Conditions::get_correction_interp_monofluide () const inline
References interp_monofluide_.
Referenced by Navier_Stokes_FTD_IJK::complete_initialise_ijk_fields(), Navier_Stokes_FTD_IJK::initialise_ijk_fields(), Navier_Stokes_FTD_IJK::initialise_ns_fields(), and Navier_Stokes_FTD_IJK::update_indicatrice_variables_monofluides().
get_correction_conserv_qdm()
int Boundary_Conditions::get_correction_conserv_qdm () const inline
References conserv_qdm_.
Referenced by Navier_Stokes_FTD_IJK::update_v_or_rhov().
get_resolution_u_prime_()
int Boundary_Conditions::get_resolution_u_prime_ () const inline
References resolution_u_prime_.
Referenced by Navier_Stokes_FTD_IJK::calculer_vitesse_ft().
Member Data Documentation
info_obj
const Type_info Boundary_Conditions::info_obj static
bctype_kmin_
int Boundary_Conditions::bctype_kmin_ protected
Referenced by Boundary_Conditions(), get_bctype_k_min(), and readOn().
bctype_kmax_
int Boundary_Conditions::bctype_kmax_ protected
Referenced by Boundary_Conditions(), get_bctype_k_max(), and readOn().
vxkmin_
double Boundary_Conditions::vxkmin_ protected
Referenced by Boundary_Conditions(), get_vx_kmin(), readOn(), and set_vx_kmin().
vxkmax_
double Boundary_Conditions::vxkmax_ protected
Referenced by Boundary_Conditions(), get_vx_kmax(), readOn(), and set_vx_kmax().
dU_perio_
double Boundary_Conditions::dU_perio_ protected
Referenced by Boundary_Conditions(), get_dU_perio(), readOn(), and set_dU_perio().
t0_shear_
double Boundary_Conditions::t0_shear_ protected
Referenced by Boundary_Conditions(), get_t0_shear(), and readOn().
defilement_
int Boundary_Conditions::defilement_ protected
Referenced by Boundary_Conditions(), get_defilement(), and readOn().
order_interpolation_poisson_solver_
int Boundary_Conditions::order_interpolation_poisson_solver_ protected
Referenced by Boundary_Conditions(), and readOn().
interp_monofluide_
int Boundary_Conditions::interp_monofluide_ protected
Referenced by Boundary_Conditions(), get_correction_interp_monofluide(), and readOn().
conserv_qdm_
int Boundary_Conditions::conserv_qdm_ protected
Referenced by Boundary_Conditions(), get_correction_conserv_qdm(), and readOn().
resolution_u_prime_
int Boundary_Conditions::resolution_u_prime_ protected
Referenced by Boundary_Conditions(), get_resolution_u_prime_(), and readOn().