TrioCFD: Corriger_frontiere_periodique_32_64< _SIZE_ > Class Template Reference
Corriger_frontiere_periodique_32_64< _SIZE_ > Class Template Reference
#include <Corriger_frontiere_periodique.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Interprete_geometrique_base_32_64< _SIZE_ >
const Type_info * get_info () const override
void mettre_a_jour_sous_domaine (Domaine_t &domaine, int_t &elem, int_t num_premier_elem, int_t nb_elem) const
Public Member Functions inherited from Interprete
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions
static void corriger_coordonnees_sommets_perio (Domaine_t &dom, const Nom &nom_bord, const ArrOfDouble &vecteur_perio, const Nom &nom_fichier_post)
Static Public Member Functions inherited from Interprete
static Objet_U & objet (const Nom &)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Interprete_geometrique_base_32_64< _SIZE_ >
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Interprete
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
template<typename _SIZE_>
class Corriger_frontiere_periodique_32_64< _SIZE_ >
(cas de certains maillages tetra si le mailleur est trop contraint par la CAO). Il tente de deplacer les sommets pour les aligner.
Cet interprete permet de corriger les frontieres periodiques pour etre conformes aux besoins de TRUST:
reordonner les faces du bord periodique pour que la face i+n/2 soit en face de la face i, et toutes les faces [0 .. n/2-1] du meme cote et [n/2 .. n-1] de l'autre cote
deplacer les sommets des faces periodiques si besoin (si la CAO est fausse) Syntaxe: Corriger_frontiere_periodique { domaine NOMDOMAINE bord NOMBORDPERIO [ direction DIMENSION dx dy [ dz ] ] [ fichier_post BASENAME ] }
Member Typedef Documentation
int_t
template<typename _SIZE_ > using Corriger_frontiere_periodique_32_64< _SIZE_ >::int_t = _SIZE_
IntTab_t
template<typename _SIZE_ > using Corriger_frontiere_periodique_32_64< _SIZE_ >::IntTab_t = IntTab_T<_SIZE_>
DoubleTab_t
template<typename _SIZE_ > using Corriger_frontiere_periodique_32_64< _SIZE_ >::DoubleTab_t = DoubleTab_T<_SIZE_>
ArrOfInt_t
template<typename _SIZE_ > using Corriger_frontiere_periodique_32_64< _SIZE_ >::ArrOfInt_t = ArrOfInt_T<_SIZE_>
ArrOfDouble_t
template<typename _SIZE_ > using Corriger_frontiere_periodique_32_64< _SIZE_ >::ArrOfDouble_t = ArrOfDouble_T<_SIZE_>
ArrOfBit_t
template<typename _SIZE_ > using Corriger_frontiere_periodique_32_64< _SIZE_ >::ArrOfBit_t = ArrOfBit_32_64<_SIZE_>
Octree_Double_t
template<typename _SIZE_ > using Corriger_frontiere_periodique_32_64< _SIZE_ >::Octree_Double_t = Octree_Double_32_64<_SIZE_>
Bord_t
template<typename _SIZE_ > using Corriger_frontiere_periodique_32_64< _SIZE_ >::Bord_t = Bord_32_64<_SIZE_>
Domaine_bord_t
template<typename _SIZE_ > using Corriger_frontiere_periodique_32_64< _SIZE_ >::Domaine_bord_t = Domaine_bord_32_64<_SIZE_>
Domaine_t
template<typename _SIZE_ > using Corriger_frontiere_periodique_32_64< _SIZE_ >::Domaine_t = Domaine_32_64<_SIZE_>
Constructor & Destructor Documentation
Corriger_frontiere_periodique_32_64()
template<typename _T_ > Corriger_frontiere_periodique_32_64< _T_ >::Corriger_frontiere_periodique_32_64
~Corriger_frontiere_periodique_32_64()
template<typename _T_ > Corriger_frontiere_periodique_32_64< _T_ >::~Corriger_frontiere_periodique_32_64
Member Function Documentation
cree_instance()
template<typename _T_ > Objet_U * Corriger_frontiere_periodique_32_64< _T_ >::cree_instance static
taille_memoire()
template<typename _T_ > unsigned Corriger_frontiere_periodique_32_64< _T_ >::taille_memoire override virtual
Implements Objet_U.
duplique()
template<typename _T_ > int Corriger_frontiere_periodique_32_64< _T_ >::duplique override virtual
Implements Objet_U.
info()
template<typename _T_ > const Type_info * Corriger_frontiere_periodique_32_64< _T_ >::info static
get_info()
template<typename _T_ > const Type_info * Corriger_frontiere_periodique_32_64< _T_ >::get_info override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
template<typename _T_ > Corriger_frontiere_periodique_32_64< _T_ > & Corriger_frontiere_periodique_32_64< _T_ >::self_cast (Objet_U & r) static
self_cast() [2/2]
template<typename _T_ > const Corriger_frontiere_periodique_32_64< _T_ > & Corriger_frontiere_periodique_32_64< _T_ >::self_cast (const Objet_U & r) static
printOn()
template<typename _SIZE_ > Sortie & Corriger_frontiere_periodique_32_64< _SIZE_ >::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
readOn()
template<typename _SIZE_ > Entree & Corriger_frontiere_periodique_32_64< _SIZE_ >::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
interpreter_()
template<typename _SIZE_ > Entree & Corriger_frontiere_periodique_32_64< _SIZE_ >::interpreter_ (Entree & is) override virtual
Implements Interprete_geometrique_base_32_64< _SIZE_ >.
References Param::ajouter(), Domaine_32_64< _SIZE_ >::bord(), Reordonner_faces_periodiques_32_64< _SIZE_ >::chercher_direction_perio(), Domaine_32_64< _SIZE_ >::coord_sommets(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Frontiere_32_64< _SIZE_ >::faces(), Faces_32_64< _SIZE_ >::les_sommets(), Param::lire_avec_accolades_depuis(), Objet_U::precision_geom, Reordonner_faces_periodiques_32_64< _SIZE_ >::reordonner_faces_periodiques(), Param::REQUIRED, and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
corriger_coordonnees_sommets_perio()
template<typename _SIZE_ > void Corriger_frontiere_periodique_32_64< _SIZE_ >::corriger_coordonnees_sommets_perio (Domaine_t & dom, const Nom & nom_bord, const ArrOfDouble & vecteur_perio, const Nom & nom_fichier_post) static
Pour chaque sommet du bord periodique, on cherche son sommet oppose dans la direction + ou - vecteur_perio et dans un rayon search_radius.
Parmi le couple de sommets forme, on deplace celui qui se trouve en +vecteur_perio pour le mettre en face de l'autre sommet. Exit en cas d'erreur (si les sommets sont trop eloignes de leur sommet associe)
Parameters
(dom) le domaine a modifier. On deplace les coordonnees des sommets periodiques.
(nom_bord) le nom du bord periodique du domaine a traiter
(vecteur_perio) un vecteur de taille "dimension" qui contient le delta entre deux sommets periodiques associes (voir methode chercher_direction_perio())
(nom_fichier_post) si different de "??", on cree un fichier de postraitement contenant les faces du bord initial et un vecteur qui indique le deplacement applique aux sommets.
References TRUST_Vector< _CLASSE_ >::add(), Process::barrier(), Octree_Double_32_64< _SIZE_ >::build_nodes(), Domaine_bord_32_64< _SIZE_ >::construire_domaine_bord(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Format_Post_base::ecrire_champ(), Format_Post_base::ecrire_domaine(), Format_Post_base::ecrire_entete(), Format_Post_base::ecrire_temps(), Domaine_base::epsilon(), Process::exit(), Format_Post_base::finir(), Domaine_bord_32_64< _SIZE_ >::get_renum_som(), Domaine_base::le_nom(), Domaine_32_64< _SIZE_ >::les_sommets(), Process::nproc(), Octree_Double_32_64< _SIZE_ >::search_elements_box(), Octree_Double_32_64< _SIZE_ >::search_nodes_close_to(), and ArrOfBit_32_64< _SIZE_ >::testsetbit().
info_obj() [1/2]
const Type_info Corriger_frontiere_periodique_32_64< int >::info_obj ("Corriger_frontiere_periodique" , Corriger_frontiere_periodique_32_64< int >::cree_instance , 1 , Corriger_frontiere_periodique_32_64bases< int >)
info_obj() [2/2]
const Type_info Corriger_frontiere_periodique_32_64< trustIdType >::info_obj ("Corriger_frontiere_periodique" "_64" , Corriger_frontiere_periodique_32_64< trustIdType >::cree_instance , 1 , Corriger_frontiere_periodique_32_64bases< trustIdType >)
Member Data Documentation
info_obj
template<typename _SIZE_ > const Type_info Corriger_frontiere_periodique_32_64< _SIZE_ >::info_obj static