TrioCFD: Postraitement Class Reference
Postraitement Class Reference
#include <Postraitement.h>
Public Member Functions
int & compteur_champ_stat ()
const Type_info * get_info () const override
void init () override
virtual int lire_champs_a_postraiter (Entree &is, bool expect_acco)
int lire_motcle_non_standard (const Motcle &, Entree &) override
Postraitement ()
virtual int postraiter_champs ()
int postraiter_sondes ()
int reprendre (Entree &is) override
void resetTime (double t, const std::string dirname) override
int sauvegarder (Sortie &os) const override
int traiter_champs ()
int traiter_sondes ()
virtual int write_extra_mesh ()
Public Member Functions inherited from Postraitement_base
const Type_info * get_info () const override
const Nom & le_nom () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
int reprendre (Entree &is) override
int sauvegarder (Sortie &os) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Postraitement_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
                            tous les champs generiques du post-traitement
                      -d une liste d identifiants noms_champs_a_post_ qui contient l identifiant
                       des champs a post-traiter
-Lecture des champs generiques declares dans le bloc "definition_champs" (ajoutes dans  champs_post_complet_)
et ajout dans cette liste des champs crees par macro (declenche par ancienne syntaxe dans "champs" et "statistiques")
   Construction de la liste des identifiants noms_champs_a_post_ au cours des operations de lecture
-Mise a jour des champs generiques, en realite mise a jour des operateurs statistiques pour les champs qui en porte
-postraitement realise dans postraiter_champs()
   Parcours des identifiants
   Le champ generique correspondant a un identifiant est recupere par :             get_champ_post("identifiant")
   Pour ce champ generique : on calcul les valeurs a ecrire par :                     get_champ(espace_stockage)
                             on recupere les informations complementaires par : get_property(), get_time() ...
   Ecriture des valeurs calculees :                                             postraiter(...)
Les macros utilises pour la creation des champs generiques sont detaillees dans le .cpp de la classe Voir creer_champ_post() et creer_champ_post_stat()
See also
Hierarchie des champs generiques (Champ_Generique_base), La syntaxe a respecter dans le jdd, Postraitement {, Sondes, {, ..., }, Definition_champs, {, //Specification des champs generiques, }, Champs, {, -Creation de champ generique par macro si utilisation ancienne syntaxe (ex : vitesse elem) et ajout, identifiant dans la liste noms_champs_a_post_, -Ajout dans la liste noms_champs_a_post_ pour cas d un champ declare dans le bloc "definition_champs", }, Statistiques, {, t_deb val_1 t_fin_val_2, -Creation de champ generique par macro si utilisation ancienne syntaxe (ex : Moyenne vitesse elem) et ajout, identifiant dans la liste noms_champs_a_post_, }, }
Constructor & Destructor Documentation
~Postraitement()
Postraitement::~Postraitement ()
References noms_fichiers_sondes_.
Postraitement()
Postraitement::Postraitement ()
Constructeur par defaut.
Les frequences de postraitement prennent la valeur par defaut 1e6. Et aucun postraitement n'est demande.
Member Function Documentation
cree_instance()
Objet_U * Postraitement::cree_instance () static
taille_memoire()
unsigned Postraitement::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Postprocessing_IJK, and Postraitement_ft_lata.
duplique()
int Postraitement::duplique () const override virtual
Implements Objet_U.
Reimplemented in Postprocessing_IJK, and Postraitement_ft_lata.
info()
const Type_info * Postraitement::info () static
get_info()
const Type_info * Postraitement::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
Reimplemented in Postprocessing_IJK, and Postraitement_ft_lata.
self_cast() [1/2]
Postraitement & Postraitement::self_cast (Objet_U & r) static
self_cast() [2/2]
const Postraitement & Postraitement::self_cast (const Objet_U & r) static
printOn()
Sortie & Postraitement::printOn (Sortie & s) const override protected virtual
Imprime le type de l'objet sur un flot de sortie.
Parameters
(Sortie& s) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Objet_U.
Reimplemented in Postprocessing_IJK, and Postraitement_ft_lata.
References Objet_U::que_suis_je().
readOn()
Entree & Postraitement::readOn (Entree & s) override protected virtual
Lit les directives de postraitement sur un flot d'entree.
Format: Postraitement { Sondes bloc de lecture des sondes | Champs bloc de lecture des champs a postraiter | Statistiques bloc de lecture objet statistique | Fichier }
Parameters
(Entree& s) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Exceptions
accolade ouverte attendue
lecture des champs: mot clef "dt_post" attendu
lecture du bloc statistique: mot clef "dt_post" attendu
mot clef inconnu
Reimplemented from Objet_U.
Reimplemented in Postprocessing_IJK, and Postraitement_ft_lata.
References binaire_, Sondes::completer(), Probleme_base::domaine(), dt_post_, Process::exit(), format_, format_post_, Nom::getChar(), Format_Post_base::initialize(), le_domaine_, Postraitement_base::le_nom(), les_sondes_, Postraitement_base::mon_probleme, nb_pas_dt_post_, nom_fich_, TRUST_Ref< _CLASSE_ >::non_nul(), option_para_, Nom::prefix(), Postraitement_base::readOn(), Format_Post_base::set_single_lata_option(), Objet_U_ptr::typer(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Postraitement_ft_lata::readOn().
associer_nom_et_pb_base()
void Postraitement::associer_nom_et_pb_base (const Nom & nom, const Probleme_base & pb) override virtual
Reimplemented from Postraitement_base.
References Postraitement_base::associer_nom_et_pb_base().
Referenced by Source_Generique_base::completer().
postraiter() [1/2]
void Postraitement::postraiter (int forcer) override virtual
Implements Postraitement_base.
Reimplemented in Postprocessing_IJK.
References besoin_postraiter_champs(), champs_post_complet_, dernier_temps_, dt_integr_serie_, Champ_Gen_de_Champs_Gen::fixer_serie(), lserie_, Postraitement_base::mon_probleme, postraiter_champs(), postraiter_sondes(), postraiter_tableaux(), sondes_demande_, tableaux_demande_, traiter_champs(), traiter_sondes(), traiter_tableaux(), tstat_deb_, tstat_dernier_calcul_, and tstat_fin_.
Referenced by postprocess_field_values(), and Postprocessing_IJK::postraiter().
mettre_a_jour()
void Postraitement::mettre_a_jour (double temps) override virtual
Reimplemented from Postraitement_base.
References champs_post_complet_, Schema_Temps_base::pas_de_temps(), probleme(), Probleme_base::schema_temps(), tstat_deb_, tstat_dernier_calcul_, and tstat_fin_.
finir()
void Postraitement::finir () override virtual
Finalise le postraitement Ferme le fichier associe.
Reimplemented from Postraitement_base.
References besoin_postraiter_champs(), TRUST_Vector< _CLASSE_ >::clear(), est_le_dernier_postraitement_pour_nom_fich_, Sondes::fermer_fichiers(), Sondes_Int::fermer_fichiers(), Format_Post_base::finir(), format_, format_post_, les_sondes_, les_sondes_int_, Format_Post_base::modify_file_basename(), Postraitement_base::mon_probleme, nom_fich(), and Nom::prefix().
data_a_sauvegarder()
std::vector< YAML_data > Postraitement::data_a_sauvegarder () const override virtual
for PDI IO: retrieve name, type and dimensions of the fields to save/restore
Reimplemented from Postraitement_base.
References champs_post_complet_, Nom::getString(), Probleme_U::le_nom(), Postraitement_base::le_nom(), probleme(), YAML_data::set_conditions(), YAML_data::set_local(), stat_demande_, stat_demande_definition_champs_, and tstat_deb_.
sauvegarder()
int Postraitement::sauvegarder (Sortie &) const override virtual
Sauvegarde d'un Objet_U sur un flot de sortie Methode a surcharger.
Parameters
(Sortie&) flot de sortie a utiliser pour la sauvegarde
Returns
(int) code de retour
Reimplemented from Objet_U.
References champs_post_complet_, Probleme_base::domaine(), Sortie::flush(), Nom::getString(), EcritureLectureSpecial::is_ecriture_special(), TRUST_2_PDI::is_PDI_checkpoint(), Probleme_U::le_nom(), Domaine_base::le_nom(), Postraitement_base::le_nom(), Postraitement_base::mon_probleme, nb_champs_stat_, probleme(), Liste_Champ_Generique::sauvegarder(), Probleme_base::schema_temps(), stat_demande_, stat_demande_definition_champs_, Schema_Temps_base::temps_courant(), TRUST_2_PDI::TRUST_start_sharing(), tstat_deb_, and tstat_dernier_calcul_.
reprendre()
int Postraitement::reprendre (Entree &) override virtual
Reprise d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree&) flot d'entree a utiliser pour la reprise
Returns
(int) code de retour
Reimplemented from Objet_U.
References champs_post_complet_, Process::exit(), Champ_Gen_de_Champs_Gen::fixer_tstat_deb(), Nom::getString(), TRUST_2_PDI::is_PDI_restart(), TRUSTTab< _TYPE_, _SIZE_ >::jump(), Probleme_U::le_nom(), Postraitement_base::le_nom(), Champ_Gen_de_Champs_Gen::lire_bidon(), lserie_, Postraitement_base::mon_probleme, nb_champs_stat_, probleme(), TRUST_2_PDI::read(), Liste_Champ_Generique::reprendre(), Probleme_base::schema_temps(), stat_demande_, stat_demande_definition_champs_, Schema_Temps_base::temps_courant(), and tstat_deb_.
completer()
void Postraitement::completer () override virtual
Implements Postraitement_base.
Reimplemented in Postprocessing_IJK.
References Sondes::init_bords(), and les_sondes_.
completer_sondes()
void Postraitement::completer_sondes () override virtual
Reimplemented from Postraitement_base.
References Sondes::completer(), and les_sondes_.
Referenced by Postprocessing_IJK::init().
init()
void Postraitement::init () override virtual
Initialise le postraitement.
Cree le fichier associe au postraitement, ecrit des infos sur TrioU. Ecrit le probleme sur le fichier.
Reimplemented from Postraitement_base.
Reimplemented in Postprocessing_IJK.
References TRUST_Vector< _CLASSE_ >::add(), Objet_U::axi, besoin_postraiter_champs(), Format_Post_base::completer_post(), Noms::contient_(), Domaine_base::deformable(), dernier_temps_, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), domaine_dis_pour_faces_, Format_Post_base::ecrire_domaine_dis(), Format_Post_base::ecrire_entete(), Format_Post_base::ecrire_item_int(), Domaine_VF::elem_faces(), est_le_dernier_postraitement_pour_nom_fich(), est_le_premier_postraitement_pour_nom_fich(), est_le_premier_postraitement_pour_nom_fich_, Process::exit(), Domaine_VF::face_sommets(), Nom::finit_par(), format_, format_post_, formats_supportes_, get_champ_post(), get_nom_localisation(), Champ_Gen_de_Champs_Gen::get_source(), le_domaine_, Domaine_base::le_nom(), Format_Post_base::modify_file_basename(), Postraitement_base::mon_probleme, Field_base::nature_du_champ(), Field_base::nb_comp(), Domaine_32_64< _SIZE_ >::nb_som(), nom_fich(), nom_fich_, noms_champs_a_post_, TRUST_Ref< _CLASSE_ >::non_nul(), Nom::prefix(), Format_Post_base::preparer_post(), TRUST_Vector< _CLASSE_ >::size(), Schema_Temps_base::temps_courant(), Schema_Temps_base::temps_init(), and TRUST_Ref< _CLASSE_ >::valeur().
set_param()
void Postraitement::set_param (Param & param) override virtual
Implements Postraitement_base.
Reimplemented in Postprocessing_IJK, and Postraitement_ft_lata.
References Param::ajouter(), Param::ajouter_non_std(), champs_demande_, DeprecatedKeepDuplicatedProbes, dt_post_, Process::exit(), format_, nb_pas_dt_post_, nom_fich_, option_para_, stat_demande_, and suffix_for_reset_.
Referenced by Postraitement_ft_lata::set_param().
lire_motcle_non_standard()
int Postraitement::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Objet_U.
Reimplemented in Postraitement_ft_lata.
References Parser_U::addVar(), Sondes::associer_post(), Sondes_Int::associer_post(), binaire_, Interprete_bloc::BLOC_EOF, champs_demande_, comprend_champ_post(), Sous_Domaine_32_64< _SIZE_ >::domaine(), dt_integr_serie_, dt_post_, Parser_U::eval(), Process::exit(), fdt_post_, Motcle::finit_par(), Probleme_base::get_noms_champs_postraitables(), Nom::getPrefix(), Interprete_bloc::interprete_courant(), Interprete_bloc::interpreter_bloc(), le_domaine_, Probleme_U::le_nom(), Domaine_base::le_nom(), les_sondes_, les_sondes_int_, lire_champs_a_postraiter(), lire_champs_operateurs(), lire_champs_stat_a_postraiter(), lire_motcle_non_standard(), lire_tableaux_a_postraiter(), lserie_, Nom::majuscule(), Postraitement_base::mon_probleme, nb_pas_dt_post_, Interprete::objet(), Interprete_bloc::objet_global(), Interprete_bloc::objet_global_existant(), Sondes_Int::ouvrir_fichiers(), Parser_U::parseString(), probleme(), Objet_U::que_suis_je(), Noms::rang(), Sondes::set_update_positions(), Parser_U::setNbVar(), Parser_U::setString(), sondes_demande_, stat_demande_, and tableaux_demande_.
Referenced by Postraitement_ft_lata::lire_motcle_non_standard(), and lire_motcle_non_standard().
resetTime()
void Postraitement::resetTime (double time, const std::string dirname) override virtual
When reseting time (see ProblemTrio::resetTime() documentation) we change the name of the postprocessing files with a new suffix. TODO: In the current setup suffix is "" meaning that the previous output are discarded. This might change in the future!
Implements Postraitement_base.
Reimplemented in Postprocessing_IJK.
References dernier_temps_, format_, format_post_, les_sondes_, nom_fich(), nom_fich_, Nom::prefix(), Format_Post_base::resetTime(), Sondes::resetTime(), suffix_for_reset_, and temps_.
les_sondes() [1/2]
const Sondes & Postraitement::les_sondes () const inline
References les_sondes_.
les_sondes() [2/2]
Sondes & Postraitement::les_sondes () inline
References les_sondes_.
probleme() [1/2]
Probleme_base & Postraitement::probleme () inline
References Postraitement_base::mon_probleme, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Champ_Generique_modifier_pour_QC::completer(), data_a_sauvegarder(), lire_champs_a_postraiter(), lire_champs_operateurs(), lire_motcle_non_standard(), mettre_a_jour(), reprendre(), sauvegarder(), set_expression_champ(), traiter_tableaux(), and verifie_nom_et_sources().
probleme() [2/2]
const Probleme_base & Postraitement::probleme () const inline
References Postraitement_base::mon_probleme, and TRUST_Ref< _CLASSE_ >::valeur().
postraiter_sondes()
int Postraitement::postraiter_sondes ()
Effectue le postraitement lie au sondes de facon imperative.
Returns
(int) renvoie toujours 1
References les_sondes_, les_sondes_int_, Postraitement_base::mon_probleme, Sondes::postraiter(), and Sondes_Int::postraiter().
Referenced by postraiter(), and Probleme_FTD_IJK_base::preparer_calcul().
traiter_sondes()
int Postraitement::traiter_sondes ()
Mets a jour (en temps) le sondes.
Returns
(int) renvoie toujours 1
References les_sondes_, Sondes::mettre_a_jour(), and Postraitement_base::mon_probleme.
Referenced by postraiter().
postraiter_champs()
int Postraitement::postraiter_champs () virtual
Effectue le postraitement des Champs de facon imperative.
Mets a jour les champs crees.
Returns
(int) renvoie toujours 1
Reimplemented in Postprocessing_IJK.
References besoin_postraiter_champs(), Domaine_base::deformable(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), domaine_dis_pour_faces_, Format_Post_base::ecrire_domaine_dis(), Format_Post_base::ecrire_item_int(), Format_Post_base::ecrire_temps(), Domaine_VF::elem_faces(), est_le_premier_postraitement_pour_nom_fich_, Domaine_VF::face_sommets(), Format_Post_base::finir_ecriture(), format_post_, Format_Post_base::init_ecriture(), le_domaine_, Domaine_base::le_nom(), Postraitement_base::mon_probleme, Domaine_32_64< _SIZE_ >::nb_som(), TRUST_Ref< _CLASSE_ >::non_nul(), postprocess_field_values(), temps_, TRUST_Ref< _CLASSE_ >::valeur(), and write_extra_mesh().
Referenced by postraiter(), and traiter_champs().
postprocess_field_values()
void Postraitement::postprocess_field_values () virtual
Reimplemented in Postraitement_ft_lata.
References Champ_Generique_base::composante(), Nom::debute_par(), Champ_Generique_base::get_champ(), get_champ_post(), Champ_Generique_base::get_info_type_post(), Champ_Generique_base::get_localisation(), get_nom_localisation(), Champ_Generique_base::get_property(), le_domaine_, Postraitement_base::mon_probleme, Field_base::nature_du_champ(), noms_champs_a_post_, postraiter(), Objet_U::que_suis_je(), Champ_base::valeur_aux_faces(), and Champ_Proto::valeurs().
Referenced by Postraitement_ft_lata::postprocess_field_values(), and postraiter_champs().
traiter_champs()
int Postraitement::traiter_champs ()
Effectue le postraitement des Champs si cela est necessaire.
Returns
(int) renvoie toujours 1
References dt_post_, Parser_U::eval(), fdt_post_, ind_post(), lpost(), Postraitement_base::mon_probleme, Schema_Temps_base::nb_pas_dt(), postraiter_champs(), Parser_U::setVar(), and Schema_Temps_base::temps_courant().
Referenced by postraiter().
lire_champs_a_postraiter()
int Postraitement::lire_champs_a_postraiter (Entree & s, bool expect_acco) virtual
Lit le nom des champs a postraiter sur un flot d'entree.
Format: { ??? }
Parameters
(Entree& s) un flot d'entree
Returns
(int) renvoie toujours 1
Exceptions
accolade ouvrante attendue
Reimplemented in Postprocessing_IJK.
References TRUST_List< _CLASSE_ >::add(), complete_champ(), comprend_champ_post(), TRUST_List< _CLASSE_ >::contient(), Motcles::contient_(), creer_champ_post(), creer_champ_post_med(), creer_champ_post_moreqn(), Probleme_base::equation(), Process::exit(), Probleme_base::expression_predefini(), Probleme_base::get_champ_post(), Champ_Generique_base::get_property(), Equation_base::inconnue(), Postraitement_base::mon_probleme, Field_base::nb_comp(), Probleme_base::nombre_d_equations(), Equation_base::nombre_d_operateurs(), Equation_base::nombre_d_operateurs_tot(), noms_champs_a_post_, probleme(), and TRUST_Vector< _CLASSE_ >::size().
Referenced by lire_motcle_non_standard().
lire_champs_stat_a_postraiter()
int Postraitement::lire_champs_stat_a_postraiter (Entree & s)
References creer_champ_post_stat(), Process::exit(), Postraitement_base::mon_probleme, nb_champs_stat_, tstat_deb_, and tstat_fin_.
Referenced by lire_motcle_non_standard().
lire_champs_operateurs()
int Postraitement::lire_champs_operateurs (Entree & is)
Lit les champs a postraiter sur un flot d'entree.
References complete_champ(), Process::exit(), Probleme_base::expression_predefini(), Probleme_U::le_nom(), and probleme().
Referenced by lire_motcle_non_standard().
complete_champ()
void Postraitement::complete_champ (Champ_Generique_base & champ, const Motcle & motlu)
References TRUST_List< _CLASSE_ >::add_if_not(), champs_post_complet_, cherche_stat_dans_les_sources(), Champ_Generique_base::completer(), nb_champs_stat_, Champ_Generique_base::nommer(), and verifie_nom_et_sources().
Referenced by lire_champs_a_postraiter(), and lire_champs_operateurs().
postraiter_tableaux()
int Postraitement::postraiter_tableaux ()
References Format_Post_base::ecrire_item_int(), Format_Post_base::ecrire_temps(), est_le_premier_postraitement_pour_nom_fich_, format_post_, TRUST_List< _CLASSE_ >::get_stl_list(), le_domaine_, Domaine_base::le_nom(), Postraitement_base::mon_probleme, noms_tableaux_, tableaux_a_postraiter_, and temps_.
Referenced by postraiter(), and traiter_tableaux().
traiter_tableaux()
int Postraitement::traiter_tableaux ()
References dt_post_, lpost(), postraiter_tableaux(), probleme(), Probleme_base::schema_temps(), and Schema_Temps_base::temps_courant().
Referenced by postraiter().
lire_tableaux_a_postraiter()
int Postraitement::lire_tableaux_a_postraiter (Entree & s)
References TRUST_List< _CLASSE_ >::add(), Process::exit(), Postraitement_base::mon_probleme, noms_tableaux_, TRUST_Vector< _CLASSE_ >::size(), and tableaux_a_postraiter_.
Referenced by lire_motcle_non_standard().
lpost()
int Postraitement::lpost (double temps_courant, double dt_post) const inline
References dernier_temps_, and dt_post().
Referenced by traiter_champs(), and traiter_tableaux().
lpost_champ()
int Postraitement::lpost_champ (double) const inline
lpost_stat()
int Postraitement::lpost_stat (double) const inline
ind_post()
int Postraitement::ind_post (int nb_pas_dt) const inline
References nb_pas_dt_post_.
Referenced by traiter_champs().
nb_pas_dt_post()
int Postraitement::nb_pas_dt_post () const inline
References nb_pas_dt_post_.
dt_post()
double Postraitement::dt_post () const inline
References dt_post_.
Referenced by Traitement_particulier_NS_CEG::critere_cea_jaea(), Probleme_base::init_postraitements(), and lpost().
nom_fich()
Nom Postraitement::nom_fich () const inline
References nom_fich_.
Referenced by finir(), init(), Probleme_base::init_postraitements(), and resetTime().
noms_fichiers_sondes()
static TRUST_List< Nom > & Postraitement::noms_fichiers_sondes () inline static
References noms_fichiers_sondes_.
est_le_premier_postraitement_pour_nom_fich()
int & Postraitement::est_le_premier_postraitement_pour_nom_fich () inline
References est_le_premier_postraitement_pour_nom_fich_.
Referenced by init(), and Probleme_base::init_postraitements().
est_le_dernier_postraitement_pour_nom_fich()
int & Postraitement::est_le_dernier_postraitement_pour_nom_fich () inline
References est_le_dernier_postraitement_pour_nom_fich_.
Referenced by init(), and Probleme_base::init_postraitements().
les_statistiques()
Operateurs_Statistique_tps & Postraitement::les_statistiques () inline
References les_statistiques_.
Referenced by Moyenne_volumique::get_champ().
sondes_demande()
int Postraitement::sondes_demande () inline
References sondes_demande_.
champs_demande()
int Postraitement::champs_demande () inline
References champs_demande_.
Referenced by Probleme_base::init_postraitements().
stat_demande()
int Postraitement::stat_demande () const inline
References stat_demande_.
stat_demande_definition_champs()
int Postraitement::stat_demande_definition_champs () const inline
References stat_demande_definition_champs_.
tableaux_demande()
int Postraitement::tableaux_demande () inline
References tableaux_demande_.
besoin_postraiter_champs()
bool Postraitement::besoin_postraiter_champs () inline
References champs_demande_, stat_demande_, and stat_demande_definition_champs_.
Referenced by finir(), init(), postraiter(), and postraiter_champs().
noms_champs_a_post()
TRUST_List< Nom > & Postraitement::noms_champs_a_post () inline
References noms_champs_a_post_.
Referenced by Modele_turbulence_hyd_base::preparer_calcul(), and Modele_turbulence_hyd_Longueur_Melange_VEF::preparer_calcul().
champs_post_complet()
const Liste_Champ_Generique & Postraitement::champs_post_complet () const inline
References champs_post_complet_.
postraiter() [2/2]
int Postraitement::postraiter (const Domaine & dom, const Noms & unites, const Noms & noms_compo, const int ncomp, const double temps, Nom nom_post, const Nom & localisation, const Nom & nature, const DoubleTab & valeurs, int tenseur)
References postraiter_tableau(), and postraiter_tenseur().
postraiter_tableau()
int Postraitement::postraiter_tableau (const Domaine & dom, const Noms & unites, const Noms & noms_compo, const int ncomp, const double temps, Nom nom_post, const Nom & localisation, const Nom & nature, const DoubleTab & valeurs)
References Domaine_32_64< _SIZE_ >::calculer_centres_gravite(), Domaine_32_64< _SIZE_ >::coord_sommets(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), domaine_dis_pour_faces_, Format_Post_base::ecrire_champ(), Format_Post_base::ecrire_champ2(), format_, format_post_, TRUSTArray< _TYPE_, _SIZE_ >::isDataOnDevice(), Domaine_base::le_nom(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), TRUST_Ref< _CLASSE_ >::valeur(), TRUSTTab< _TYPE_, _SIZE_ >::view_ro(), TRUSTTab< _TYPE_, _SIZE_ >::view_wo(), and Domaine_VF::xv().
Referenced by Postraitement_ft_lata::postprocess_field_values(), postraiter(), and postraiter_tenseur().
postraiter_tenseur()
int Postraitement::postraiter_tenseur (const Domaine & dom, const Noms & unites, const Noms & noms_compo, const int ncomp, const double temps, Nom nom_post, const Nom & localisation, const Nom & nature, const DoubleTab & valeurs)
References postraiter_tableau(), and TRUST_Vector< _CLASSE_ >::size().
Referenced by postraiter().
get_champ_post()
const Champ_Generique_base & Postraitement::get_champ_post (const Motcle & nom) const virtual
References champs_post_complet_, Champ_Generique_base::get_champ_post(), and Nom::getString().
Referenced by champ_fonc(), Champ_Gen_de_Champs_Gen::completer(), Champ_Generique_Correlation::completer(), Champ_Generique_Ecart_Type::completer(), creer_champ_post(), Probleme_base::get_champ_post(), init(), and postprocess_field_values().
has_champ_post()
bool Postraitement::has_champ_post (const Motcle & nom) const virtual
References champs_post_complet_.
Referenced by Probleme_base::get_champ_post(), and Probleme_base::has_champ_post().
set_expression_champ()
Nom Postraitement::set_expression_champ (const Motcle & motlu1, const Motcle & motlu2, const Motcle & motlu3, const Motcle & motlu4, const int trouve)
References Probleme_U::le_nom(), and probleme().
Referenced by creer_champ_post(), and creer_champ_post_stat().
creer_champ_post()
void Postraitement::creer_champ_post (const Motcle & motlu1, const Motcle & motlu2, Entree & s)
References TRUST_List< _CLASSE_ >::add(), TRUST_List< _CLASSE_ >::add_if_not(), champs_post_complet_, Champ_Generique_base::completer(), Champ_Generique_base::composante(), comprend_champ_post(), TRUST_List< _CLASSE_ >::contient(), Process::exit(), Champ_Generique_Interpolation::fixer_noms_compo(), Champ_Generique_Interpolation::fixer_noms_synonyms(), get_champ_post(), Champ_Generique_Interpolation::get_ref_domain(), le_domaine_, TRUST_Ref< _CLASSE_ >::le_nom(), Domaine_base::le_nom(), Nom::le_nom(), Postraitement_base::mon_probleme, Champ_Gen_de_Champs_Gen::nommer_sources(), noms_champs_a_post_, Champ_Generique_Interpolation::set_domaine(), set_expression_champ(), and TRUST_Vector< _CLASSE_ >::size().
Referenced by creer_champ_post_med(), and lire_champs_a_postraiter().
creer_champ_post_stat()
void Postraitement::creer_champ_post_stat (const Motcle & motlu1, const Motcle & motlu2, const Motcle & motlu3, const Motcle & motlu4, const double t_deb, const double t_fin, Entree & s)
References TRUST_List< _CLASSE_ >::add(), TRUST_List< _CLASSE_ >::add_if_not(), champs_post_complet_, Champ_Generique_base::completer(), TRUST_List< _CLASSE_ >::contient(), Process::exit(), Champ_Generique_Interpolation::fixer_noms_compo(), Champ_Generique_Statistiques_base::fixer_tdeb_tfin(), Champ_Generique_refChamp::get_champ(), Champ_Generique_Interpolation::get_ref_domain(), Champ_Gen_de_Champs_Gen::get_source(), Champ_Generique_Correlation::integrale(), Integrale_tps_Champ::le_champ_calcule(), le_domaine_, Domaine_base::le_nom(), Champ_Gen_de_Champs_Gen::nommer_sources(), noms_champs_a_post_, Field_base::noms_compo(), Champ_Generique_Interpolation::set_domaine(), set_expression_champ(), Champ_Gen_de_Champs_Gen::set_source(), TRUST_Vector< _CLASSE_ >::size(), and Champ_Generique_Statistiques_base::use_source_name_only().
Referenced by lire_champs_stat_a_postraiter().
creer_champ_post_moreqn()
void Postraitement::creer_champ_post_moreqn (const Motcle & type, const Motcle & option, const int num_eq, const int num_morceau, const int compo, Entree & s)
References TRUST_List< _CLASSE_ >::add(), TRUST_List< _CLASSE_ >::add_if_not(), champs_post_complet_, Champ_Generique_base::completer(), TRUST_List< _CLASSE_ >::contient(), Process::exit(), TRUST_Ref< _CLASSE_ >::le_nom(), Field_base::le_nom(), Postraitement_base::mon_probleme, Objet_U::nommer(), Champ_Gen_de_Champs_Gen::nommer_sources(), and noms_champs_a_post_.
Referenced by lire_champs_a_postraiter().
creer_champ_post_med()
void Postraitement::creer_champ_post_med (const Motcle & motlu1, const Motcle & motlu2, Entree & s)
References champs_post_complet_, creer_champ_post(), Objet_U::nommer(), noms_champs_a_post_, Nom::prefix(), TRUST_List< _CLASSE_ >::size(), and Nom::suffix().
Referenced by lire_champs_a_postraiter().
comprend_champ_post()
int Postraitement::comprend_champ_post (const Motcle & identifiant) const
References champs_post_complet_.
Referenced by champ_fonc(), Champ_Generique_Correlation::completer(), Champ_Generique_Ecart_Type::completer(), Probleme_base::comprend_champ_post(), creer_champ_post(), lire_champs_a_postraiter(), and lire_motcle_non_standard().
verifie_nom_et_sources()
void Postraitement::verifie_nom_et_sources (const Champ_Generique_base & champ)
References Probleme_base::comprend_champ_post(), Motcles::contient_(), Process::exit(), Probleme_base::get_noms_champs_postraitables(), Champ_Generique_base::get_property(), Probleme_U::le_nom(), probleme(), and TRUST_Vector< _CLASSE_ >::size().
Referenced by complete_champ().
get_nom_localisation()
Nom Postraitement::get_nom_localisation (const Entity & loc) static
Referenced by init(), and postprocess_field_values().
champ_fonc()
int Postraitement::champ_fonc (Motcle & nom_champ, TRUST_Ref< Champ_base * > & mon_champ, TRUST_Ref< Operateur_Statistique_tps_base * > & operateur_statistique) const
References comprend_champ_post(), get_champ_post(), Champ_Generique_Statistiques_base::integrale(), Integrale_tps_Champ::le_champ_calcule(), and Champ_Generique_Statistiques_base::Operateur_Statistique().
compteur_champ_stat()
int & Postraitement::compteur_champ_stat () inline
Test de postraitement en tenant compte de l'evolution en temps du champ.
Renvoie VRAI si le champ necessite un postraitement, vu le temps courant et le pas de temps fourni.
Parameters
(double temps_courant) le temps courant
(double dt) le pas de temps qui vient d'etre accompli
Returns
(int) valeur booleenne, VRAI si le pas de temp et le temps courant fournis indique qu'un postraitement est necessaire, FAUX sinon.
References nb_champs_stat_.
tstat_deb()
const double & Postraitement::tstat_deb () const inline
References tstat_deb_.
tstat_fin()
const double & Postraitement::tstat_fin () const inline
References tstat_fin_.
cherche_stat_dans_les_sources()
int Postraitement::cherche_stat_dans_les_sources (const Champ_Gen_de_Champs_Gen & ch, Motcle nom)
On recherche les champs statistiques dans les sources du champ courant.
References cherche_stat_dans_les_sources(), Process::exit(), Champ_Gen_de_Champs_Gen::get_nb_sources(), Champ_Gen_de_Champs_Gen::get_source(), stat_demande_definition_champs_, Champ_Generique_Statistiques_base::tstat_deb(), tstat_deb_, Champ_Generique_Statistiques_base::tstat_fin(), and tstat_fin_.
Referenced by cherche_stat_dans_les_sources(), and complete_champ().
write_extra_mesh()
virtual int Postraitement::write_extra_mesh () inline virtual
Calls by postraiter_champs() and allows a derived class to write extra meshes if needed
Returns
-1 if nothing more was written, 1 otherwise.
Reimplemented in Postprocessing_IJK, and Postraitement_ft_lata.
Referenced by postraiter_champs().
domaine()
const TRUST_Ref< Domaine * > & Postraitement::domaine () inline
References le_domaine_.
Member Data Documentation
info_obj
const Type_info Postraitement::info_obj static
DeprecatedKeepDuplicatedProbes
int Postraitement::DeprecatedKeepDuplicatedProbes =0
Referenced by set_param().
est_le_premier_postraitement_pour_nom_fich_
int Postraitement::est_le_premier_postraitement_pour_nom_fich_ protected
Referenced by est_le_premier_postraitement_pour_nom_fich(), init(), postraiter_champs(), and postraiter_tableaux().
est_le_dernier_postraitement_pour_nom_fich_
int Postraitement::est_le_dernier_postraitement_pour_nom_fich_ protected
Referenced by est_le_dernier_postraitement_pour_nom_fich(), and finir().
dt_post_
double Postraitement::dt_post_ protected
ecriture des donnees (champs, stats, int_array) tous les dt_post (un temps)
Referenced by dt_post(), lire_motcle_non_standard(), readOn(), set_param(), traiter_champs(), and traiter_tableaux().
nb_pas_dt_post_
int Postraitement::nb_pas_dt_post_ protected
ecriture des donnees (champs, stats, int_array) tous les dt_post (une periode en nb d'iteration)
Referenced by ind_post(), lire_motcle_non_standard(), nb_pas_dt_post(), readOn(), and set_param().
fdt_post_
Parser_U Postraitement::fdt_post_ protected
Referenced by lire_motcle_non_standard(), and traiter_champs().
les_sondes_
Sondes Postraitement::les_sondes_ protected
Referenced by completer(), completer_sondes(), finir(), les_sondes(), lire_motcle_non_standard(), Postprocessing_IJK::postraiter(), postraiter_sondes(), readOn(), resetTime(), and traiter_sondes().
les_sondes_int_
Sondes_Int Postraitement::les_sondes_int_ protected
Referenced by finir(), lire_motcle_non_standard(), and postraiter_sondes().
les_statistiques_
Operateurs_Statistique_tps Postraitement::les_statistiques_ protected
Referenced by les_statistiques().
noms_champs_a_post_
TRUST_List< Nom > Postraitement::noms_champs_a_post_ protected
Referenced by creer_champ_post(), creer_champ_post_med(), creer_champ_post_moreqn(), creer_champ_post_stat(), init(), lire_champs_a_postraiter(), noms_champs_a_post(), postprocess_field_values(), and Postprocessing_IJK::register_one_field().
champs_post_complet_
Liste_Champ_Generique Postraitement::champs_post_complet_ protected
Referenced by champs_post_complet(), complete_champ(), comprend_champ_post(), creer_champ_post(), creer_champ_post_med(), creer_champ_post_moreqn(), creer_champ_post_stat(), data_a_sauvegarder(), get_champ_post(), has_champ_post(), mettre_a_jour(), postraiter(), reprendre(), and sauvegarder().
nb_champs_stat_
int Postraitement::nb_champs_stat_ protected
Referenced by complete_champ(), compteur_champ_stat(), lire_champs_stat_a_postraiter(), reprendre(), and sauvegarder().
tstat_deb_
double Postraitement::tstat_deb_ protected
Referenced by cherche_stat_dans_les_sources(), data_a_sauvegarder(), lire_champs_stat_a_postraiter(), mettre_a_jour(), postraiter(), reprendre(), sauvegarder(), and tstat_deb().
tstat_fin_
double Postraitement::tstat_fin_ protected
Referenced by cherche_stat_dans_les_sources(), lire_champs_stat_a_postraiter(), mettre_a_jour(), postraiter(), and tstat_fin().
tstat_dernier_calcul_
double Postraitement::tstat_dernier_calcul_ protected
Referenced by mettre_a_jour(), postraiter(), and sauvegarder().
lserie_
int Postraitement::lserie_ protected
Referenced by lire_motcle_non_standard(), postraiter(), and reprendre().
dt_integr_serie_
double Postraitement::dt_integr_serie_ protected
Referenced by lire_motcle_non_standard(), and postraiter().
tableaux_a_postraiter_
TRUST_List< TRUST_Ref< IntVect *> > Postraitement::tableaux_a_postraiter_ protected
Referenced by lire_tableaux_a_postraiter(), and postraiter_tableaux().
noms_tableaux_
TRUST_List< Nom > Postraitement::noms_tableaux_ protected
Referenced by lire_tableaux_a_postraiter(), and postraiter_tableaux().
format_post_
TRUST_Deriv< Format_Post_base > Postraitement::format_post_ protected
Referenced by Postraitement_ft_lata::ecrire_maillage_ft_disc(), finir(), init(), postraiter_champs(), postraiter_tableau(), postraiter_tableaux(), Postraitement_ft_lata::readOn(), readOn(), and resetTime().
noms_fichiers_sondes_
TRUST_List< Nom > Postraitement::noms_fichiers_sondes_ =TRUST_List< Nom >() static protected
Referenced by noms_fichiers_sondes(), and ~Postraitement().
sondes_demande_
bool Postraitement::sondes_demande_ protected
Referenced by lire_motcle_non_standard(), postraiter(), and sondes_demande().
champs_demande_
bool Postraitement::champs_demande_ protected
Referenced by besoin_postraiter_champs(), champs_demande(), lire_motcle_non_standard(), and set_param().
stat_demande_
bool Postraitement::stat_demande_ protected
Referenced by besoin_postraiter_champs(), data_a_sauvegarder(), lire_motcle_non_standard(), reprendre(), sauvegarder(), set_param(), and stat_demande().
stat_demande_definition_champs_
bool Postraitement::stat_demande_definition_champs_ protected
Referenced by besoin_postraiter_champs(), cherche_stat_dans_les_sources(), data_a_sauvegarder(), reprendre(), sauvegarder(), and stat_demande_definition_champs().
tableaux_demande_
bool Postraitement::tableaux_demande_ protected
Referenced by lire_motcle_non_standard(), postraiter(), and tableaux_demande().
binaire_
int Postraitement::binaire_ protected
Referenced by lire_motcle_non_standard(), and readOn().
nom_fich_
Nom Postraitement::nom_fich_ protected
Referenced by Postprocessing_IJK::init(), init(), nom_fich(), Postprocessing_IJK::postraiter_champs(), Postprocessing_IJK::prepare_lata_and_stats(), readOn(), resetTime(), set_param(), and Postprocessing_IJK::write_extra_mesh().
format_
Nom Postraitement::format_ protected
Referenced by finir(), init(), Postraitement_ft_lata::lire_motcle_non_standard(), postraiter_tableau(), readOn(), resetTime(), and set_param().
option_para_
Nom Postraitement::option_para_ protected
Referenced by readOn(), and set_param().
suffix_for_reset_
Nom Postraitement::suffix_for_reset_ protected
Referenced by resetTime(), and set_param().
temps_
double Postraitement::temps_ protected
Referenced by postraiter_champs(), postraiter_tableaux(), and resetTime().
dernier_temps_
double Postraitement::dernier_temps_ protected
Referenced by init(), lpost(), postraiter(), and resetTime().
formats_supportes_
Motcles Postraitement::formats_supportes_ =Motcles(0) static protected
Referenced by init().
le_domaine_
TRUST_Ref< Domaine *> Postraitement::le_domaine_ protected
Referenced by creer_champ_post(), creer_champ_post_stat(), domaine(), init(), lire_motcle_non_standard(), postprocess_field_values(), postraiter_champs(), postraiter_tableaux(), and readOn().
domaine_dis_pour_faces_
TRUST_Ref< Domaine_dis_base *> Postraitement::domaine_dis_pour_faces_ protected
Referenced by init(), postraiter_champs(), and postraiter_tableau().