TrioCFD: Paroi_std_hyd_EF Class Reference
Paroi_std_hyd_EF Class Reference
#include <Paroi_std_hyd_EF.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Turbulence_paroi_base
void associer_modele (const Modele_turbulence_hyd_base &)
int calculer_hyd (Champ_Fonc_base &, Champ_Fonc_base &)
int calculer_hyd (Champ_Inc_base &)
const Type_info * get_info () const override
virtual void imprimer_premiere_ligne_ustar (int, const TRUST_List< Nom > &, const Nom &) const
virtual void imprimer_ustar_mean_only (Sortie &, int, const TRUST_List< Nom > &, const Nom &) const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Turbulence_paroi_base
static void typer_lire_turbulence_paroi (TRUST_Deriv< Turbulence_paroi_base > &, const Modele_turbulence_hyd_base &, Entree &)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
.SECTION voir aussi Turbulence_paroi_base
Constructor & Destructor Documentation
~Paroi_std_hyd_EF()
Paroi_std_hyd_EF::~Paroi_std_hyd_EF ()
Paroi_std_hyd_EF()
Paroi_std_hyd_EF::Paroi_std_hyd_EF ()
Member Function Documentation
cree_instance()
Objet_U * Paroi_std_hyd_EF::cree_instance () static
taille_memoire()
unsigned Paroi_std_hyd_EF::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Loi_expert_hydr_EF.
duplique()
int Paroi_std_hyd_EF::duplique () const override virtual
Implements Objet_U.
Reimplemented in Loi_expert_hydr_EF.
info()
const Type_info * Paroi_std_hyd_EF::info () static
get_info()
const Type_info * Paroi_std_hyd_EF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Paroi_hyd_base_EF.
Reimplemented in Loi_expert_hydr_EF.
self_cast() [1/2]
Paroi_std_hyd_EF & Paroi_std_hyd_EF::self_cast (Objet_U & r) static
self_cast() [2/2]
const Paroi_std_hyd_EF & Paroi_std_hyd_EF::self_cast (const Objet_U & r) static
printOn()
Sortie & Paroi_std_hyd_EF::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Paroi_hyd_base_EF.
Reimplemented in Loi_expert_hydr_EF.
References Objet_U::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Paroi_std_hyd_EF::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Paroi_hyd_base_EF.
Reimplemented in Loi_expert_hydr_EF.
References Paroi_hyd_base_EF::readOn().
set_param()
void Paroi_std_hyd_EF::set_param (Param & param) override virtual
Reimplemented from Turbulence_paroi_base.
References Paroi_log_QDM::set_param(), and Turbulence_paroi_base::set_param().
Referenced by Loi_expert_hydr_EF::readOn(), and Paroi_loi_WW_hyd_EF::set_param().
init_lois_paroi()
int Paroi_std_hyd_EF::init_lois_paroi () override virtual
Implements Turbulence_paroi_base.
References Turbulence_paroi_base::Cisaillement_paroi_, Objet_U::dimension, TRUSTVect< _TYPE_, _SIZE_ >::get_md_vector(), init_lois_paroi_hydraulique(), iterations_LP, Turbulence_paroi_base::le_dom_dis_, MD_Vector::non_nul(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), seuil_LP, Turbulence_paroi_base::tab_d_plus_, Turbulence_paroi_base::tab_u_star_, and uplus_.
calculer_hyd() [1/2]
int Paroi_std_hyd_EF::calculer_hyd (DoubleTab & tab_k_eps) override virtual
Implements Turbulence_paroi_base.
calculer_hyd_BiK()
int Paroi_std_hyd_EF::calculer_hyd_BiK (DoubleTab & tab_k, DoubleTab & tab_eps) override virtual
Implements Turbulence_paroi_base.
calculer_hyd() [2/2]
int Paroi_std_hyd_EF::calculer_hyd (DoubleTab & tab_nu_t, DoubleTab & tab_k) override virtual
Implements Turbulence_paroi_base.
References calculer_k_eps(), calculer_u_plus(), Turbulence_paroi_base::Cisaillement_paroi_, Paroi_log_QDM::Cmu_, Objet_U::dimension, Domaine_dis_base::domaine(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Paroi_log_QDM::Erugu, Process::exit(), Domaine_VF::face_sommets(), Domaine_VF::face_voisins(), Equation_base::inconnue(), is_u_star_impose_, Turbulence_paroi_base::le_dom_Cl_dis_, Turbulence_paroi_base::le_dom_dis_, Domaine_32_64< _SIZE_ >::les_elems(), TRUSTVect< _TYPE_, _SIZE_ >::local_min_vect(), Equation_base::milieu(), Turbulence_paroi_base::mon_modele_turb_hyd, TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Front_VF::nb_faces_tot(), Domaine_dis_base::nb_front_Cl(), Domaine_32_64< _SIZE_ >::nb_som_elem(), Domaine_VF::nb_som_face(), Modele_turbulence_hyd_combinaison::nombre_sources(), Front_VF::num_face(), Turbulence_paroi_base::tab_d_plus_, Turbulence_paroi_base::tab_u_star_, u_star_impose_, uplus_, TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), Champ_Inc_base::valeurs(), Debog::verifier(), and Fluide_base::viscosite_cinematique().
imprimer_ustar()
void Paroi_std_hyd_EF::imprimer_ustar (Sortie & os) const override virtual
Reimplemented from Turbulence_paroi_base.
References Turbulence_paroi_base::Cisaillement_paroi_, Objet_U::dimension, iterations_LP, Process::je_suis_maitre(), Turbulence_paroi_base::le_dom_Cl_dis_, Turbulence_paroi_base::le_dom_dis_, Frontiere_dis_base::le_nom(), Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), Turbulence_paroi_base::ouvrir_fichier_partage(), Objet_U::que_suis_je(), seuil_LP, EcrFicPartage::syncfile(), Turbulence_paroi_base::tab_d_plus(), Turbulence_paroi_base::tab_u_star(), uplus_, TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), and Domaine_VF::xv().
calculer_u_plus()
double Paroi_std_hyd_EF::calculer_u_plus (const int ind_face, const double u_plus_d_plus, const double erugu)
References iterations_LP, Paroi_log_QDM::Kappa_, and seuil_LP.
Referenced by calculer_hyd().
calculer_k_eps()
int Paroi_std_hyd_EF::calculer_k_eps (double & k, double & eps, double yp, double u_star, double d_visco, double dist) virtual
References Paroi_log_QDM::Cmu_, and Paroi_log_QDM::Kappa_.
Referenced by calculer_hyd().
init_lois_paroi_hydraulique()
int Paroi_std_hyd_EF::init_lois_paroi_hydraulique () protected virtual
Reimplemented in Paroi_loi_WW_hyd_EF.
References Paroi_log_QDM::Cmu_, Paroi_log_QDM::init_lois_paroi_hydraulique_(), and Turbulence_paroi_base::mon_modele_turb_hyd.
Referenced by init_lois_paroi().
Member Data Documentation
info_obj
const Type_info Paroi_std_hyd_EF::info_obj static
uplus_
DoubleVect Paroi_std_hyd_EF::uplus_ protected
Referenced by calculer_hyd(), Paroi_loi_WW_hyd_EF::calculer_u_star_couche_puissance(), Paroi_loi_WW_hyd_EF::calculer_u_star_sous_couche_visq(), imprimer_ustar(), and init_lois_paroi().
seuil_LP
DoubleVect Paroi_std_hyd_EF::seuil_LP protected
Referenced by calculer_u_plus(), imprimer_ustar(), and init_lois_paroi().
iterations_LP
IntVect Paroi_std_hyd_EF::iterations_LP protected
Referenced by calculer_u_plus(), imprimer_ustar(), and init_lois_paroi().
u_star_impose_
double Paroi_std_hyd_EF::u_star_impose_ protected
Referenced by calculer_hyd(), and Loi_expert_hydr_EF::readOn().
is_u_star_impose_
int Paroi_std_hyd_EF::is_u_star_impose_ protected
Referenced by calculer_hyd(), and Loi_expert_hydr_EF::readOn().