TrioCFD: Champ_Parametrique Class Reference
Champ_Parametrique Class Reference
#include <Champ_Parametrique.h>
Public Member Functions
int fixer_nb_valeurs_nodales (int nb_noeuds) override
const Type_info * get_info () const override
int imprime (Sortie &os, int j) const override
int initialiser (const double temps) override
void mettre_a_jour (double temps) override
int reprendre (Entree &is) override
void resetTime (double time) override
int sauvegarder (Sortie &os) const override
DoubleTab & valeur_aux (const DoubleTab &positions, DoubleTab &valeurs) const override
DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const override
DoubleTab & valeurs () override
Public Member Functions inherited from Champ_Don_base
void dimensionner (int, int)
int fixer_nb_valeurs_nodales (int nb_noeuds) override
const Type_info * get_info () const override
int imprime (Sortie &, int) const override
virtual int initialiser (const double temps)
void mettre_a_jour (double temps) override
int reprendre (Entree &) override
void resetTime (double time) override
int sauvegarder (Sortie &) const override
DoubleTab & valeurs () override
Public Member Functions inherited from Champ_base
Champ_base & affecter (const Champ_base &)
Champ_base ()
virtual double changer_temps (const double t)
const Type_info * get_info () const override
double temps () const
virtual DoubleTab & trace (const Frontiere_dis_base &, DoubleTab &, double, int distant) const
virtual DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const
virtual double valeur_a_compo (const DoubleVect &position, int ncomp) const
virtual DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &valeurs, int le_poly) const
virtual double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const
virtual DoubleVect & valeur_a_sommet (int, const Domaine &, DoubleVect &) const
virtual DoubleTab & valeur_aux (const DoubleTab &positions, DoubleTab &valeurs) const
virtual DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const
virtual DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const
virtual DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp) const
Public Member Functions inherited from Field_base
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
virtual void fixer_nb_comp (int i)
virtual const Nom & fixer_nom_compo (const Nom &)
virtual const Nom & fixer_nom_compo (int, const Nom &)
virtual const Noms & fixer_noms_compo (const Noms &)
virtual const Nom & fixer_unite (const Nom &)
virtual const Nom & fixer_unite (int i, const Nom &)
virtual const Noms & fixer_unites (const Noms &)
const Type_info * get_info () const override
const Nom & nom_compo (int) const
void nommer (const Nom &) override
const Nom & unite () const
const Nom & unite (int) const
const Noms & unites () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Champ_Proto
int lire_dimension (Entree &, const Nom &)
int lire_dimension (int dim, const Nom &le_nom_)
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Field_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
Constructor & Destructor Documentation
Champ_Parametrique()
Champ_Parametrique::Champ_Parametrique ()
~Champ_Parametrique()
Champ_Parametrique::~Champ_Parametrique ()
Member Function Documentation
cree_instance()
Objet_U * Champ_Parametrique::cree_instance () static
taille_memoire()
unsigned Champ_Parametrique::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Champ_Parametrique::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Champ_Parametrique::info () static
get_info()
const Type_info * Champ_Parametrique::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Champ_Don_base.
self_cast() [1/2]
Champ_Parametrique & Champ_Parametrique::self_cast (Objet_U & r) static
self_cast() [2/2]
const Champ_Parametrique & Champ_Parametrique::self_cast (const Objet_U & r) static
printOn()
Sortie & Champ_Parametrique::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Champ_Don_base.
References Champ_Don_base::printOn().
readOn()
Entree & Champ_Parametrique::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Champ_Don_base.
References TRUST_List< _CLASSE_ >::add(), Param::ajouter(), champs_, enabled, Process::exit(), Field_base::fixer_nb_comp(), Param::lire_avec_accolades_depuis(), newCompute(), Objet_U::que_suis_je(), Param::REQUIRED, and Sortie_Fichier_base::set_root().
mettre_a_jour()
void Champ_Parametrique::mettre_a_jour (double t) inline override virtual
Mise a jour en temps.
Parameters
(double) le temps de mise a jour
Reimplemented from Champ_Don_base.
References champ(), Champ_Don_base::mettre_a_jour(), and Champ_base::temps().
imprime()
int Champ_Parametrique::imprime (Sortie & os, int ncomp) const inline override virtual
NE FAIT RIEN.
EXIT ! A surcharger dans les classes derivees
Reimplemented from Champ_Don_base.
References champ(), and Champ_Don_base::imprime().
fixer_nb_valeurs_nodales()
int Champ_Parametrique::fixer_nb_valeurs_nodales (int nb_noeuds) inline override virtual
Fixe le nombre de degres de liberte par composante.
Parameters
(int nb_noeuds) le nombre de degre de liberte par composante
Reimplemented from Champ_Don_base.
References champ(), and Champ_Don_base::fixer_nb_valeurs_nodales().
reprendre()
int Champ_Parametrique::reprendre (Entree &) inline override virtual
NE FAIT RIEN.
A surcharger dans les classes derivees
Reimplemented from Champ_Don_base.
References champ(), and Champ_Don_base::reprendre().
sauvegarder()
int Champ_Parametrique::sauvegarder (Sortie &) const inline override virtual
NE FAIT RIEN.
A surcharger dans les classes derivees
Reimplemented from Champ_Don_base.
References champ(), and Champ_Don_base::sauvegarder().
resetTime()
void Champ_Parametrique::resetTime (double time) inline override virtual
See comments in Probleme_base_interface_proto::resetTime_impl() Here we update.
Reimplemented from Champ_Don_base.
References champ(), and Champ_Don_base::resetTime().
valeurs() [1/4]
DoubleTab & Champ_Parametrique::valeurs () inline override virtual
Surcharge Champ_base::valeurs() Renvoie le tableau des valeurs.
Returns
(DoubleTab&) le tableau des valeurs du champs
Reimplemented from Champ_Don_base.
References champ(), and Champ_Don_base::valeurs().
Referenced by valeur_aux(), and valeur_aux_elems().
valeurs() [2/4]
const DoubleTab & Champ_Parametrique::valeurs () const inline override virtual
Reimplemented from Champ_Don_base.
References champ(), and Champ_Don_base::valeurs().
valeurs() [3/4]
DoubleTab & Champ_Parametrique::valeurs (double temps) inline override virtual
Reimplemented from Champ_Proto.
References champ(), Champ_base::temps(), and Champ_Don_base::valeurs().
valeurs() [4/4]
const DoubleTab & Champ_Parametrique::valeurs (double temps) const inline override virtual
Reimplemented from Champ_Proto.
References champ(), Champ_base::temps(), and Champ_Don_base::valeurs().
affecter_()
Champ_base & Champ_Parametrique::affecter_ (const Champ_base &) inline override virtual
Provoque une erreur ! A surcharger par les classes derivees ! non virtuelle pure par commoditees de developpement !
Reimplemented from Champ_Don_base.
References Champ_base::affecter(), and champ().
affecter_compo()
Champ_base & Champ_Parametrique::affecter_compo (const Champ_base & , int) inline override virtual
Provoque une erreur ! A surcharger par les classes derivees ! non virtuelle pure par commoditees de developpement !
Reimplemented from Champ_Don_base.
References Champ_Don_base::affecter_compo(), and champ().
nb_valeurs_nodales()
int Champ_Parametrique::nb_valeurs_nodales () const inline override virtual
Renvoie le nombre de degre de liberte par composante: le nombre de noeuds.
Reimplemented from Champ_Don_base.
References champ(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), and Champ_Don_base::valeurs().
valeur_aux()
DoubleTab & Champ_Parametrique::valeur_aux (const DoubleTab & positions, DoubleTab & les_valeurs) const inline override virtual
Provoque une erreur ! Doit etre surchargee par les classes derivees.
non virtuelle pure par commodite de developpement ! Renvoie les valeurs du champ aux points specifies par leurs coordonnees.
Parameters
(DoubleTab&) le tableau des coordonnees des points de calcul
(DoubleTab& les_valeurs) le tableau des valeurs du champ aux points specifies
Returns
(DoubleTab&) le tableau des valeurs du champ aux points specifies
Reimplemented from Champ_base.
References champ(), Champ_base::valeur_aux(), and valeurs().
valeur_aux_elems()
DoubleTab & Champ_Parametrique::valeur_aux_elems (const DoubleTab & positions, const IntVect & les_polys, DoubleTab & les_valeurs) const inline override virtual
provoque une erreur ! doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement ! Renvoie les valeurs du champ aux points specifies par leurs coordonnees, en indiquant que les points de calculs sont situes dans les elements indiques.
Parameters
(DoubleTab&) le tableau des coordonnees des points de calcul
(IntVect&) le tableau des elements dans lesquels sont situes les points de calcul
(DoubleTab& les_valeurs) le tableau des valeurs du champ aux points specifies
Returns
(DoubleTab&) le tableau des valeurs du champ aux points specifies
Reimplemented from Champ_base.
References champ(), Champ_base::valeur_aux_elems(), and valeurs().
instationnaire()
bool Champ_Parametrique::instationnaire () const inline override virtual
Reimplemented from Champ_Don_base.
References champ(), and Champ_Don_base::instationnaire().
initialiser()
int Champ_Parametrique::initialiser (const double un_temps) inline override virtual
NE FAIT RIEN.
A surcharger dans les classes derivees. Provoque l'initialisation du champ si necessaire
Reimplemented from Champ_Don_base.
References champs_, and Champ_base::temps().
newCompute()
std::string Champ_Parametrique::newCompute () const
References champ(), champs_, dirnameCompute(), index_, Objet_U::que_suis_je(), and TRUST_List< _CLASSE_ >::size().
Referenced by Probleme_base::newCompute(), and readOn().
dirnameCompute()
std::string Champ_Parametrique::dirnameCompute (int compute) static
References dirnameDefault.
Referenced by Champ_front_Parametrique::newCompute(), and newCompute().
champ() [1/2]
Champ_Don_base & Champ_Parametrique::champ () inline protected
References champs_, and index_.
Referenced by affecter_(), affecter_compo(), fixer_nb_valeurs_nodales(), imprime(), instationnaire(), mettre_a_jour(), nb_valeurs_nodales(), newCompute(), reprendre(), resetTime(), sauvegarder(), valeur_aux(), valeur_aux_elems(), and valeurs().
champ() [2/2]
const Champ_Don_base & Champ_Parametrique::champ () const inline protected
References champs_, and index_.
Member Data Documentation
info_obj
const Type_info Champ_Parametrique::info_obj static
enabled
bool Champ_Parametrique::enabled =false static
Referenced by Probleme_base::newCompute(), and readOn().
dirnameDefault
std::string Champ_Parametrique::dirnameDefault ="" static
Referenced by dirnameCompute().
champs_
TRUST_List< TRUST_Deriv< Champ_Don_base > > Champ_Parametrique::champs_ protected
Referenced by champ(), initialiser(), newCompute(), and readOn().
index_
int Champ_Parametrique::index_ =0 mutable protected
Referenced by champ(), and newCompute().