TrioCFD: Projection_ALE_boundary Class Reference
Projection_ALE_boundary Class Reference
#include <Projection_ALE_boundary.h>
Public Member Functions
const Type_info * get_info () const override
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Constructor & Destructor Documentation
Projection_ALE_boundary()
Projection_ALE_boundary::Projection_ALE_boundary ()
~Projection_ALE_boundary()
Projection_ALE_boundary::~Projection_ALE_boundary ()
Member Function Documentation
cree_instance()
Objet_U * Projection_ALE_boundary::cree_instance () static
taille_memoire()
unsigned Projection_ALE_boundary::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Projection_ALE_boundary::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Projection_ALE_boundary::info () static
get_info()
const Type_info * Projection_ALE_boundary::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Interprete_geometrique_base_32_64< _SIZE_ >.
self_cast() [1/2]
Projection_ALE_boundary & Projection_ALE_boundary::self_cast (Objet_U & r) static
self_cast() [2/2]
const Projection_ALE_boundary & Projection_ALE_boundary::self_cast (const Objet_U & r) static
printOn()
Sortie & Projection_ALE_boundary::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Interprete_geometrique_base_32_64< _SIZE_ >.
References Interprete::printOn().
readOn()
Entree & Projection_ALE_boundary::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Interprete_geometrique_base_32_64< _SIZE_ >.
References Interprete::readOn().
interpreter_()
Entree & Projection_ALE_boundary::interpreter_ (Entree & is) override protected virtual
Implements Interprete_geometrique_base_32_64< _SIZE_ >.
References Interprete_geometrique_base_32_64< _SIZE_ >::associer_domaine(), Interprete_geometrique_base_32_64< _SIZE_ >::domaine(), and Domaine_ALE::reading_projection_ALE_boundary().
Member Data Documentation
info_obj
const Type_info Projection_ALE_boundary::info_obj static