TrioCFD: Op_Diff_VEF_base Class Reference
Op_Diff_VEF_base Class Reference
#include <Op_Diff_VEF_base.h>
Public Member Functions
double calculer_dt_stab () const override
const Type_info * get_info () const override
int impr (Sortie &os) const override
Public Member Functions inherited from Operateur_Diff_base
virtual void associer_diffusivite_pour_pas_de_temps (const Champ_base &)
const Type_info * get_info () const override
Public Member Functions inherited from Operateur_base
void associer_eqn (const Equation_base &)
virtual double calculer_dt_stab () const
virtual void completer ()
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual void mettre_a_jour (double temps)
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Public Member Functions inherited from Op_VEF_Face
void dimensionner (const Domaine_VEF &, const Domaine_Cl_VEF &, Matrice_Morse &) const
void modifier_matrice_pour_periodique_apres_contribuer (Matrice_Morse &matrice, const Equation_base &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Operateur_Diff_base
virtual const Champ_base & diffusivite_pour_pas_de_temps () const
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
Classe de base des operateurs de convection VEF
Constructor & Destructor Documentation
Op_Diff_VEF_base()
Op_Diff_VEF_base::Op_Diff_VEF_base ()
~Op_Diff_VEF_base()
Op_Diff_VEF_base::~Op_Diff_VEF_base () override
Member Function Documentation
info()
const Type_info * Op_Diff_VEF_base::info () static
get_info()
const Type_info * Op_Diff_VEF_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Operateur_Diff_base.
Reimplemented in Op_Diff_K_Eps_QC_VEF_Face, Op_Diff_K_Eps_VEF_base, Op_Diff_K_Eps_VEF_Face, Op_Diff_K_Omega_VEF_base, Op_Diff_K_Omega_VEF_Face, Op_Diff_VEF_Face, Op_Diff_VEF_Face_Penalise, Op_Diff_VEF_Face_Q1, Op_Diff_VEF_Face_Stab, Op_Diff_VEFP1NCP1B_Face, Op_Dift_Stab_VEF_Face, Op_Dift_standard_VEF_Face, Op_Dift_VEF_base, Op_Dift_VEF_Face, Op_Dift_VEF_Face_Q1, and Op_Dift_VEF_P1NCP1B_Face.
self_cast() [1/2]
Op_Diff_VEF_base & Op_Diff_VEF_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Op_Diff_VEF_base & Op_Diff_VEF_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Op_Diff_VEF_base::printOn (Sortie & os) const override protected virtual
DOES NOTHING - to override in derived classes.
Imprime l'operateur sur un flot de sortie.
Parameters
(Sortie& os) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Operateur_Diff_base.
Reimplemented in Op_Diff_K_Eps_QC_VEF_Face, Op_Diff_K_Eps_VEF_base, Op_Diff_K_Eps_VEF_Face, Op_Diff_K_Omega_VEF_base, Op_Diff_K_Omega_VEF_Face, Op_Diff_VEF_Face, Op_Diff_VEF_Face_Penalise, Op_Diff_VEF_Face_Q1, Op_Diff_VEF_Face_Stab, Op_Diff_VEFP1NCP1B_Face, Op_Dift_Stab_VEF_Face, Op_Dift_standard_VEF_Face, Op_Dift_VEF_base, Op_Dift_VEF_Face, Op_Dift_VEF_Face_Q1, and Op_Dift_VEF_P1NCP1B_Face.
References Objet_U::que_suis_je().
Referenced by Op_Dift_VEF_base::printOn().
readOn()
Entree & Op_Diff_VEF_base::readOn (Entree & is) override protected virtual
DOES NOTHING - to override in derived classes.
Lit un operateur sur un flot d'entree.
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Operateur_Diff_base.
Reimplemented in Op_Diff_K_Eps_QC_VEF_Face, Op_Diff_K_Eps_VEF_base, Op_Diff_K_Eps_VEF_Face, Op_Diff_K_Omega_VEF_base, Op_Diff_K_Omega_VEF_Face, Op_Diff_VEF_Face, Op_Diff_VEF_Face_Penalise, Op_Diff_VEF_Face_Q1, Op_Diff_VEF_Face_Stab, Op_Diff_VEFP1NCP1B_Face, Op_Dift_Stab_VEF_Face, Op_Dift_standard_VEF_Face, Op_Dift_VEF_base, Op_Dift_VEF_Face, Op_Dift_VEF_Face_Q1, and Op_Dift_VEF_P1NCP1B_Face.
Referenced by Op_Dift_VEF_base::readOn().
impr()
int Op_Diff_VEF_base::impr (Sortie & os) const override virtual
DOES NOTHING - to override in derived classes.
Imprime l'operateur sur un flot de sortie.
Parameters
(Sortie& os)
Returns
(int) renvoie toujours 1
Reimplemented from Operateur_base.
References Op_VEF_Face::impr().
associer()
void Op_Diff_VEF_base::associer (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_cl_dis, const Champ_Inc_base & ch_transporte) override virtual
Implements Operateur_base.
Reimplemented in Op_Diff_VEFP1NCP1B_Face, Op_Dift_VEF_base, and Op_Dift_VEF_P1NCP1B_Face.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Operateur_base::flux_bords_, la_zcl_vef, le_dom_vef, TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Domaine_VF::nb_faces_bord(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUST_Ref< _CLASSE_ >::valeur(), and Champ_Inc_base::valeurs().
viscA() [1/2]
template<typename _TYPE_ > double Op_Diff_VEF_base::viscA (int face_i, int face_j, int num_elem, const _TYPE_ & diffu) const inline
References Objet_U::dimension, le_dom_vef, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Op_Diff_VEF_Anisotrope_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution(), Op_Diff_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Face_Stab::ajouter_contribution(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution_elem(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face::ajouter_contribution_multi_scalaire(), and Op_Diff_VEF_Face_Stab::ajouter_contribution_multi_scalaire().
viscA() [2/2]
template<typename _TYPE_ > KOKKOS_INLINE_FUNCTION double Op_Diff_VEF_base::viscA (int face_i, int face_j, int num_elem, const _TYPE_ & diffu, CIntTabView face_voisins_v, CDoubleTabView face_normales_v, CDoubleArrView inverse_volumes_v) const
calculer_dt_stab()
double Op_Diff_VEF_base::calculer_dt_stab () const override virtual
Calcul dt_stab.
Returns
(double) renvoie toujours 1.e30
Reimplemented from Operateur_base.
Reimplemented in Op_Diff_VEF_Face_Q1, Op_Diff_VEFP1NCP1B_Face, Op_Dift_VEF_base, Op_Dift_VEF_Face_Q1, and Op_Dift_VEF_P1NCP1B_Face.
References Domaine_VEF::carre_pas_du_maillage(), Domaine_VEF::carre_pas_maille(), Milieu_base::conductivite(), Operateur_Diff_base::diffusivite(), Operateur_Diff_base::diffusivite_pour_pas_de_temps(), Objet_U::dimension, MorEqn::equation(), Support_Champ_Masse_Volumique::get_champ_masse_volumique(), Echange_impose_base::h_imp(), Support_Champ_Masse_Volumique::has_champ_masse_volumique(), la_zcl_vef, le_dom_vef, Domaine_Cl_dis_base::les_conditions_limites(), Equation_base::milieu(), Process::mp_max(), Process::mp_min(), Domaine_Cl_dis_base::nb_cond_lim(), Domaine_dis_base::nb_elem(), nu_, remplir_nu(), TRUSTVect< _TYPE_, _SIZE_ >::size(), TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), Champ_front_base::valeurs(), Champ_Proto::valeurs(), and TRUSTArray< _TYPE_, _SIZE_ >::view_ro().
Referenced by calculer_pour_post().
calculer_pour_post()
void Op_Diff_VEF_base::calculer_pour_post (Champ_base & espace_stockage, const Nom & option, int comp) const override virtual
Reimplemented from Operateur_base.
Reimplemented in Op_Dift_VEF_base.
References calculer_dt_stab(), Operateur_base::calculer_pour_post(), Domaine_VEF::carre_pas_maille(), Operateur_Diff_base::diffusivite(), Operateur_Diff_base::diffusivite_pour_pas_de_temps(), Objet_U::dimension, Support_Champ_Masse_Volumique::get_champ_masse_volumique(), Support_Champ_Masse_Volumique::has_champ_masse_volumique(), le_dom_vef, Domaine_dis_base::nb_elem(), Domaine_dis_base::nb_elem_tot(), TRUST_Ref< _CLASSE_ >::non_nul(), nu_, remplir_nu(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), TRUST_Ref< _CLASSE_ >::valeur(), and Champ_Proto::valeurs().
Referenced by Op_Dift_VEF_base::calculer_pour_post().
get_localisation_pour_post()
Motcle Op_Diff_VEF_base::get_localisation_pour_post (const Nom & option) const override virtual
Reimplemented from Operateur_base.
References Operateur_base::get_localisation_pour_post().
remplir_nu()
void Op_Diff_VEF_base::remplir_nu (DoubleTab & tab_nu) const virtual
Reimplemented in Op_Dift_VEF_Face_Q1, and Op_Dift_VEF_P1NCP1B_Face.
References Domaine_32_64< _SIZE_ >::creer_tableau_elements(), Operateur_Diff_base::diffusivite(), Domaine_dis_base::domaine(), TRUSTVect< _TYPE_, _SIZE_ >::get_md_vector(), le_dom_vef, TRUSTVect< _TYPE_, _SIZE_ >::line_size(), MD_Vector::non_nul(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUST_Ref< _CLASSE_ >::valeur(), and Champ_Proto::valeurs().
Referenced by Op_Diff_K_Eps_VEF_Face::ajouter(), Op_Diff_K_Omega_VEF_Face::ajouter(), Op_Diff_VEF_Anisotrope_Face::ajouter(), Op_Diff_VEF_Face::ajouter(), Op_Diff_VEF_Face_Q1::ajouter(), Op_Diff_VEF_Face_Stab::ajouter(), Op_Diff_VEFP1NCP1B_Face::ajouter(), Op_Dift_Stab_VEF_Face::ajouter(), Op_Dift_standard_VEF_Face::ajouter(), Op_Dift_VEF_Face::ajouter(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution(), Op_Diff_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Face_Q1::ajouter_contribution(), Op_Diff_VEF_Face_Stab::ajouter_contribution(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face_Stab::ajouter_contribution_multi_scalaire(), calculer_dt_stab(), Op_Diff_VEF_Face_Q1::calculer_dt_stab(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab(), Op_Dift_VEF_base::calculer_dt_stab(), calculer_pour_post(), Op_Dift_VEF_base::calculer_pour_post(), Op_Diff_K_Eps_VEF_Face::contribuer_a_avec(), Op_Diff_K_Omega_VEF_Face::contribuer_a_avec(), Op_Dift_Stab_VEF_Face::contribuer_a_avec(), Op_Dift_VEF_Face::contribuer_a_avec(), and Op_Diff_VEFP1NCP1B_Face::test().
phi_psi_diffuse()
int Op_Diff_VEF_base::phi_psi_diffuse (const Equation_base & eq) const
definit si on calcule div(phi nu grad Psi) ou div(nu grap Phi psi)
References Equation_base::inconnue(), and Field_base::le_nom().
Referenced by Op_Diff_VEF_Anisotrope_Face::ajouter(), Op_Diff_VEF_Face::ajouter(), Op_Diff_VEF_Face_Stab::ajouter(), Op_Diff_VEFP1NCP1B_Face::ajouter(), Op_Dift_Stab_VEF_Face::ajouter(), Op_Dift_VEF_Face::ajouter(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution(), Op_Diff_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Face_Stab::ajouter_contribution(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face_Stab::ajouter_contribution_multi_scalaire(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab(), Op_Diff_K_Eps_VEF_Face::contribuer_a_avec(), Op_Diff_K_Omega_VEF_Face::contribuer_a_avec(), Op_Dift_Stab_VEF_Face::contribuer_a_avec(), Op_Dift_VEF_Face::contribuer_a_avec(), Op_Dift_VEF_Face::contribuer_au_second_membre(), and Op_Diff_VEFP1NCP1B_Face::test().
domaine_vef()
const Domaine_VEF & Op_Diff_VEF_base::domaine_vef () const inline
References le_dom_vef, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Op_Dift_VEF_Face_Q1::ajouter(), Op_Dift_VEF_P1NCP1B_Face::ajouter(), Op_Dift_VEF_base::calculer_borne_locale(), Op_Dift_VEF_P1NCP1B_Face::calculer_divergence_elem(), Op_Dift_VEF_P1NCP1B_Face::calculer_divergence_som(), Op_Dift_VEF_base::calculer_dt_stab(), Op_Dift_VEF_base::calculer_dt_stab_P1NCP1B(), Op_Dift_VEF_P1NCP1B_Face::calculer_gradient_elem(), Op_Dift_VEF_P1NCP1B_Face::calculer_gradient_som(), Op_Dift_VEF_base::calculer_pour_post(), Op_Dift_Stab_VEF_Face::completer(), Op_Dift_VEF_Face_Q1::contribuer_a_avec(), Op_Dift_VEF_Face::contribuer_au_second_membre(), and Op_Dift_VEF_P1NCP1B_Face::corriger_div_pour_Cl().
domaine_cl_vef()
const Domaine_Cl_VEF & Op_Diff_VEF_base::domaine_cl_vef () const inline
References la_zcl_vef, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Op_Dift_VEF_Face_Q1::ajouter(), Op_Dift_VEF_P1NCP1B_Face::calculer_divergence_som(), Op_Dift_VEF_P1NCP1B_Face::calculer_gradient_som(), Op_Dift_Stab_VEF_Face::completer(), Op_Dift_VEF_Face_Q1::contribuer_a_avec(), Op_Dift_VEF_Face::contribuer_au_second_membre(), and Op_Dift_VEF_P1NCP1B_Face::corriger_div_pour_Cl().
Member Data Documentation
info_obj
const Type_info Op_Diff_VEF_base::info_obj static
le_dom_vef
TRUST_Ref< Domaine_VEF *> Op_Diff_VEF_base::le_dom_vef protected
Referenced by Op_Diff_K_Eps_VEF_Face::ajouter(), Op_Diff_K_Omega_VEF_Face::ajouter(), Op_Diff_VEF_Anisotrope_Face::ajouter(), Op_Diff_VEF_Face::ajouter(), Op_Diff_VEF_Face_Q1::ajouter(), Op_Diff_VEF_Face_Stab::ajouter(), Op_Dift_Stab_VEF_Face::ajouter(), Op_Dift_VEF_Face::ajouter(), Op_Diff_VEF_Face_Stab::ajouter_antidiffusion(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution(), Op_Diff_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Face_Q1::ajouter_contribution(), Op_Diff_VEF_Face_Stab::ajouter_contribution(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution_elem(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face_Stab::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face_Stab::ajouter_diffusion(), Op_Diff_VEF_Face_Stab::ajouter_operateur_centre(), associer(), Op_Diff_VEFP1NCP1B_Face::associer(), Op_Dift_VEF_base::associer(), Op_Dift_VEF_P1NCP1B_Face::associer(), Op_Diff_VEF_Face_Stab::calculer_coefficients(), calculer_dt_stab(), Op_Diff_VEF_Face_Q1::calculer_dt_stab(), Op_Diff_VEF_Face_Stab::calculer_gradients(), Op_Diff_VEF_Face_Stab::calculer_max(), Op_Diff_VEF_Face_Stab::calculer_min(), calculer_pour_post(), Op_Dift_VEF_base::calculer_pour_post(), Op_Diff_VEF_Face_Stab::completer(), Op_Diff_VEF_Anisotrope_Face::contribue_au_second_membre(), Op_Diff_VEF_Face::contribue_au_second_membre(), Op_Diff_VEF_Face_Q1::contribue_au_second_membre(), Op_Diff_K_Omega_VEF_Face::contribuer_a_avec(), Op_Diff_VEF_Anisotrope_Face::dimensionner(), Op_Diff_VEF_Face::dimensionner(), Op_Diff_VEF_Face_Q1::dimensionner(), Op_Diff_VEFP1NCP1B_Face::dimensionner(), Op_Dift_VEF_base::dimensionner(), domaine_vef(), Op_Diff_VEFP1NCP1B_Face::domaine_vef(), Op_Diff_VEF_Face_Stab::modifie_pour_Cl(), Op_Diff_VEF_Anisotrope_Face::modifier_pour_Cl(), Op_Diff_VEF_Face::modifier_pour_Cl(), Op_Diff_VEF_Face_Q1::modifier_pour_Cl(), Op_Dift_VEF_base::modifier_pour_Cl(), remplir_nu(), Op_Diff_VEF_Anisotrope_Face::verifier(), Op_Diff_VEF_Face::verifier(), and viscA().
la_zcl_vef
TRUST_Ref< Domaine_Cl_VEF *> Op_Diff_VEF_base::la_zcl_vef protected
Referenced by Op_Diff_VEF_Anisotrope_Face::ajouter(), Op_Diff_VEF_Face::ajouter(), Op_Diff_VEF_Face_Q1::ajouter(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution(), Op_Diff_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Face_Q1::ajouter_contribution(), Op_Diff_VEF_Face_Stab::ajouter_contribution(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution_elem(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face_Stab::ajouter_contribution_multi_scalaire(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution_som(), associer(), Op_Diff_VEFP1NCP1B_Face::associer(), Op_Dift_VEF_base::associer(), Op_Dift_VEF_P1NCP1B_Face::associer(), Op_Diff_VEFP1NCP1B_Face::calculer_divergence_som(), calculer_dt_stab(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab_elem(), Op_Diff_VEFP1NCP1B_Face::calculer_flux_bords_elem(), Op_Diff_VEFP1NCP1B_Face::calculer_flux_bords_som(), Op_Diff_VEFP1NCP1B_Face::calculer_gradient_som(), Op_Diff_VEF_Face_Stab::calculer_max(), Op_Diff_VEF_Face_Stab::calculer_min(), Op_Diff_VEF_Face_Stab::completer(), Op_Diff_VEF_Anisotrope_Face::contribue_au_second_membre(), Op_Diff_VEF_Face::contribue_au_second_membre(), Op_Diff_VEF_Face_Q1::contribue_au_second_membre(), Op_Diff_VEFP1NCP1B_Face::corriger_Cl_test(), Op_Diff_VEFP1NCP1B_Face::corriger_div_pour_Cl(), Op_Diff_VEF_Anisotrope_Face::dimensionner(), Op_Diff_VEF_Face::dimensionner(), Op_Diff_VEF_Face_Q1::dimensionner(), Op_Diff_VEFP1NCP1B_Face::dimensionner(), Op_Dift_VEF_base::dimensionner(), domaine_cl_vef(), Op_Diff_VEFP1NCP1B_Face::domaine_Cl_VEFPreP1B(), Op_Diff_VEFP1NCP1B_Face::isFaceOfSymetry(), Op_Diff_VEFP1NCP1B_Face::liste_face(), Op_Diff_VEF_Face_Stab::modifie_pour_Cl(), Op_Diff_VEF_Anisotrope_Face::modifier_pour_Cl(), Op_Diff_VEF_Face::modifier_pour_Cl(), Op_Diff_VEF_Face_Q1::modifier_pour_Cl(), Op_Dift_VEF_base::modifier_pour_Cl(), and Op_Diff_VEFP1NCP1B_Face::test().
inconnue_
TRUST_Ref< Champ_Inc_base *> Op_Diff_VEF_base::inconnue_ protected
Referenced by Op_Diff_VEFP1NCP1B_Face::associer(), Op_Dift_VEF_base::associer(), Op_Dift_VEF_P1NCP1B_Face::associer(), and Op_Diff_VEFP1NCP1B_Face::dimensionner().
nu_
DoubleTab Op_Diff_VEF_base::nu_ mutable protected
Referenced by Op_Diff_K_Eps_VEF_Face::ajouter(), Op_Diff_K_Omega_VEF_Face::ajouter(), Op_Diff_VEF_Anisotrope_Face::ajouter(), Op_Diff_VEF_Face::ajouter(), Op_Diff_VEF_Face_Q1::ajouter(), Op_Diff_VEF_Face_Stab::ajouter(), Op_Diff_VEFP1NCP1B_Face::ajouter(), Op_Dift_Stab_VEF_Face::ajouter(), Op_Dift_VEF_Face::ajouter(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution(), Op_Diff_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Face_Q1::ajouter_contribution(), Op_Diff_VEF_Face_Stab::ajouter_contribution(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face_Stab::ajouter_contribution_multi_scalaire(), calculer_dt_stab(), Op_Diff_VEF_Face_Q1::calculer_dt_stab(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab(), Op_Dift_VEF_base::calculer_dt_stab(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab_elem(), calculer_pour_post(), Op_Dift_VEF_base::calculer_pour_post(), Op_Diff_K_Eps_VEF_Face::contribuer_a_avec(), Op_Diff_K_Omega_VEF_Face::contribuer_a_avec(), Op_Dift_Stab_VEF_Face::contribuer_a_avec(), Op_Dift_VEF_Face::contribuer_a_avec(), Op_Dift_VEF_Face::contribuer_au_second_membre(), and Op_Diff_VEFP1NCP1B_Face::test().