TrioCFD: Ecrire_Fichier Class Reference
Ecrire_Fichier Class Reference
#include <Ecrire_Fichier.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Interprete
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Interprete
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Interprete
static Objet_U & objet (const Nom &)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Ecrire_Fichier()
Ecrire_Fichier::Ecrire_Fichier ()
~Ecrire_Fichier()
Ecrire_Fichier::~Ecrire_Fichier ()
Member Function Documentation
cree_instance()
Objet_U * Ecrire_Fichier::cree_instance () static
taille_memoire()
unsigned Ecrire_Fichier::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Ecrire_Fichier_Formatte.
duplique()
int Ecrire_Fichier::duplique () const override virtual
Implements Objet_U.
Reimplemented in Ecrire_Fichier_Formatte.
info()
const Type_info * Ecrire_Fichier::info () static
get_info()
const Type_info * Ecrire_Fichier::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
Reimplemented in Ecrire_Fichier_Formatte.
self_cast() [1/2]
Ecrire_Fichier & Ecrire_Fichier::self_cast (Objet_U & r) static
self_cast() [2/2]
const Ecrire_Fichier & Ecrire_Fichier::self_cast (const Objet_U & r) static
printOn()
Sortie & Ecrire_Fichier::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
Reimplemented in Ecrire_Fichier_Formatte.
References Interprete::printOn().
readOn()
Entree & Ecrire_Fichier::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
Reimplemented in Ecrire_Fichier_Formatte.
References Interprete::readOn().
interpreter()
Entree & Ecrire_Fichier::interpreter (Entree & is) override virtual
Implements Interprete.
Reimplemented in Ecrire_Fichier_Formatte.
References interpreter_().
interpreter_()
void Ecrire_Fichier::interpreter_ (Entree & is, int format_binaire) protected
References Process::barrier(), Process::exit(), Sortie_Fichier_base::get_ofstream(), Sortie::get_ostream(), Process::nproc(), Interprete::objet(), Sortie_Fichier_base::ouvrir(), and Sortie::set_bin().
Referenced by interpreter(), and Ecrire_Fichier_Formatte::interpreter().
Member Data Documentation
info_obj
const Type_info Ecrire_Fichier::info_obj static