TrioCFD: Cut_cell_double Class Reference
Cut_cell_double Class Reference
#include <TRUSTTabFT_cut_cell.h>
Member Function Documentation
associer_persistant()
void Cut_cell_double::associer_persistant (Cut_cell_FT_Disc & cut_cell_disc)
References Cut_cell_data::associer_persistant().
associer_ephemere()
void Cut_cell_double::associer_ephemere (Cut_cell_FT_Disc & cut_cell_disc)
References Cut_cell_data::associer_ephemere().
associer_paresseux()
void Cut_cell_double::associer_paresseux (Cut_cell_FT_Disc & cut_cell_disc)
References Cut_cell_data::associer_paresseux().
verify_consistency_within_layer()
bool Cut_cell_double::verify_consistency_within_layer (int dir, int k_layer, const IJK_Field_local_double & flux)
References IJK_Interfaces::convert_indicatrice_to_phase(), Cut_cell_data::cut_cell_disc_, Cut_cell_data::diph_l_, Cut_cell_data::diph_v_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), and IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj().