TrioCFD: Schema_Temps_IJK_base Class Reference
Schema_Temps_IJK_base Class Reference
#include <Schema_Temps_IJK_base.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Schema_Temps_base
virtual void changer_temps_courant (const double)
virtual bool corriger_dt_calcule (double &dt) const
int diffusion_implicite () const
double & facteur_securite_pas ()
double facteur_securite_pas () const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual int impr (Sortie &os, Probleme_base &pb) const
virtual void imprimer (Sortie &os) const
void imprimer (Sortie &os, Probleme_base &pb) const
virtual bool isStationary () const
const Nom & le_nom () const override
int limpr () const
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual int mettre_a_jour ()
int nb_impr () const
int nb_pas_dt () const
int nb_pas_dt_max () const
int nb_pas_dt_max_atteint () const
int nb_sauv_max () const
void nommer (const Nom &) override
double pas_de_temps () const
double & pas_temps_max ()
double pas_temps_max () const
double & pas_temps_min ()
double pas_temps_min () const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Schema_Temps_base ()
double seuil_statio () const
virtual int stop () const
int stop_lu () const
double temps_calcul () const
double temps_courant () const
int temps_final_atteint () const
double temps_impr () const
double temps_init () const
double temps_max () const
double temps_precedent () const
double temps_sauv () const
void update_critere_statio (const DoubleTab &tab_critere, Equation_base &equation)
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Schema_Temps_IJK_base()
Schema_Temps_IJK_base::Schema_Temps_IJK_base ()
~Schema_Temps_IJK_base()
Schema_Temps_IJK_base::~Schema_Temps_IJK_base () override
Member Function Documentation
info()
const Type_info * Schema_Temps_IJK_base::info () static
get_info()
const Type_info * Schema_Temps_IJK_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Schema_Temps_base.
self_cast() [1/2]
Schema_Temps_IJK_base & Schema_Temps_IJK_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Schema_Temps_IJK_base & Schema_Temps_IJK_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Schema_Temps_IJK_base::printOn (Sortie & os) const override protected virtual
Surcharge Objet_U::printOn(Sortie&) Imprime le schema en temps sur un flot de sortie.
!! Attention n'est pas symetrique de la lecture !! On ecrit les differents parametres du schema en temps.
Parameters
(Sortie& os) le flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Schema_Temps_base.
References cfl_, Schema_Temps_base::dt_, dt_sauvegarde_, fo_, max_simu_time_, Schema_Temps_base::nb_pas_dt_max_, oh_, Schema_Temps_base::temps_courant_, timestep_facsec_, Schema_Temps_base::tinit_, tstep_init_, and use_tstep_init_.
Referenced by Schema_Euler_explicite_IJK::printOn(), and Schema_RK3_IJK::printOn().
readOn()
Entree & Schema_Temps_IJK_base::readOn (Entree & is) override protected virtual
Lecture d'un schema en temps a partir d'un flot d'entree.
Le format de lecture attendu est le suivant: { [Motcle valeur_reelle] } Les mots clefs peuvent etre: tinit, tmax, nb_pas_dt_max, dt_min, dt_max, dt_sauv, dt_impr, facsec, seuil_statio,
Parameters
(Entree& is) le flot d'entree
Returns
(Entree&) le flot d'entree modifie
Exceptions
accolade ouvrante attendue
motclef inconnu a cet endroit
Reimplemented from Schema_Temps_base.
References Param::lire_avec_accolades_depuis(), Schema_Temps_base::lu_, Objet_U::nom_du_cas(), Objet_U::que_suis_je(), set_param(), stop_file_, Schema_Temps_base::temps_courant_, and Schema_Temps_base::tinit_.
Referenced by Schema_Euler_explicite_IJK::readOn(), and Schema_RK3_IJK::readOn().
nb_valeurs_temporelles()
int Schema_Temps_IJK_base::nb_valeurs_temporelles () const inline override virtual
Implements Schema_Temps_base.
nb_valeurs_futures()
int Schema_Temps_IJK_base::nb_valeurs_futures () const inline override virtual
Implements Schema_Temps_base.
temps_futur()
double Schema_Temps_IJK_base::temps_futur (int i) const inline override virtual
Implements Schema_Temps_base.
References Schema_Temps_base::pas_de_temps(), and Schema_Temps_base::temps_courant().
temps_defaut()
double Schema_Temps_IJK_base::temps_defaut () const inline override virtual
Implements Schema_Temps_base.
References Schema_Temps_base::pas_de_temps(), and Schema_Temps_base::temps_courant().
completer()
void Schema_Temps_IJK_base::completer () override virtual
Implements Schema_Temps_base.
References first_step_interface_smoothing_, Schema_Temps_base::mon_probleme, Schema_Temps_base::temps_courant_, tstep_init_, use_tstep_init_, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Probleme_FTD_IJK_base::completer().
computeTimeStep()
double Schema_Temps_IJK_base::computeTimeStep (bool & stop) const override virtual
Reimplemented from Schema_Temps_base.
References cfl_, Schema_Temps_base::dt_, find_timestep(), fo_, max_timestep_, oh_, Schema_Temps_base::stop(), and timestep_facsec_.
Referenced by Probleme_FTD_IJK_base::computeTimeStep().
set_param()
void Schema_Temps_IJK_base::set_param (Param & param) override virtual
Reimplemented from Schema_Temps_base.
References Param::ajouter(), Param::ajouter_flag(), Param::ajouter_non_std(), cfl_, Schema_Temps_base::dt_, dt_sauvegarde_, enable_dt_oh_ideal_length_factor_, first_step_interface_smoothing_, fo_, max_simu_time_, Schema_Temps_base::nb_pas_dt_max_, oh_, Param::REQUIRED, timestep_facsec_, Schema_Temps_base::tinit_, tstep_init_, and use_tstep_init_.
Referenced by readOn().
set_param_reprise_pb()
void Schema_Temps_IJK_base::set_param_reprise_pb (Param & param)
References Param::ajouter(), Schema_Temps_base::temps_courant_, and tstep_init_.
Referenced by Probleme_FTD_IJK_base::reprendre_probleme().
get_dt_cfl()
double Schema_Temps_IJK_base::get_dt_cfl () const inline
References dt_cfl_.
get_dt_fo()
double Schema_Temps_IJK_base::get_dt_fo () const inline
References dt_fo_.
get_dt_oh()
double Schema_Temps_IJK_base::get_dt_oh () const inline
References dt_oh_.
get_dt_cfl_liq()
double Schema_Temps_IJK_base::get_dt_cfl_liq () const inline
References dt_cfl_liq_.
get_dt_cfl_vap_()
double Schema_Temps_IJK_base::get_dt_cfl_vap_ () const inline
References dt_cfl_vap_.
get_dt_fo_liq()
double Schema_Temps_IJK_base::get_dt_fo_liq () const inline
References dt_fo_liq_.
get_dt_fo_vap_()
double Schema_Temps_IJK_base::get_dt_fo_vap_ () const inline
References dt_fo_vap_.
get_timestep_facsec()
double Schema_Temps_IJK_base::get_timestep_facsec () const inline
References timestep_facsec_.
Referenced by Probleme_FTD_IJK_cut_cell::readOn().
get_modified_time_ini()
double Schema_Temps_IJK_base::get_modified_time_ini () const inline
References modified_time_ini_.
get_max_simu_time()
double Schema_Temps_IJK_base::get_max_simu_time () const inline
References max_simu_time_.
Referenced by check_stop_criteria().
get_max_timestep()
double Schema_Temps_IJK_base::get_max_timestep () const inline
References max_timestep_.
Referenced by Probleme_FTD_IJK_base::run().
get_current_time()
double Schema_Temps_IJK_base::get_current_time () const inline
References Schema_Temps_base::temps_courant().
Referenced by check_stop_criteria(), Navier_Stokes_FTD_IJK::complete_initialise_ijk_fields(), Navier_Stokes_FTD_IJK::compute_correction_for_momentum_balance(), Navier_Stokes_FTD_IJK::initialise_ijk_fields(), Postprocessing_IJK::postraiter(), Probleme_FTD_IJK_base::reprendre_probleme(), Navier_Stokes_FTD_IJK::sauvegarder_equation(), Probleme_FTD_IJK_base::sauvegarder_probleme(), Probleme_FTD_IJK_base::solveTimeStep(), Probleme_FTD_IJK_base::solveTimeStep_RK3(), Navier_Stokes_FTD_IJK::write_check_etapes_et_termes(), and Navier_Stokes_FTD_IJK::write_qdm_corrections_information().
get_timestep()
double Schema_Temps_IJK_base::get_timestep () const inline
References Schema_Temps_base::pas_de_temps().
Referenced by Navier_Stokes_FTD_IJK::calculer_dv(), Navier_Stokes_FTD_IJK::calculer_terme_asservissement(), Navier_Stokes_FTD_IJK::compute_correction_for_momentum_balance(), Navier_Stokes_FTD_IJK::create_forced_dilation(), Navier_Stokes_FTD_IJK::euler_explicit_update(), Navier_Stokes_FTD_IJK::euler_time_step(), Postprocessing_IJK::get_IJK_field(), Postprocessing_IJK::postraiter(), and Probleme_FTD_IJK_base::solveTimeStep_RK3().
set_timestep()
double & Schema_Temps_IJK_base::set_timestep () inline
References Schema_Temps_base::set_dt().
Referenced by Probleme_FTD_IJK_base::run().
get_nb_timesteps()
int Schema_Temps_IJK_base::get_nb_timesteps () const inline
References Schema_Temps_base::nb_pas_dt_max().
Referenced by check_stop_criteria(), and Probleme_FTD_IJK_base::run().
get_tstep() [1/2]
int Schema_Temps_IJK_base::get_tstep () const inline
References Schema_Temps_base::nb_pas_dt().
Referenced by Navier_Stokes_FTD_IJK::calculer_dv(), Navier_Stokes_FTD_IJK::calculer_terme_source_acceleration(), check_stop_criteria(), Navier_Stokes_FTD_IJK::compute_correction_for_momentum_balance(), Navier_Stokes_FTD_IJK::euler_time_step(), Probleme_FTD_IJK_base::run(), Probleme_FTD_IJK_base::sauvegarder_probleme(), Probleme_FTD_IJK_base::sauver(), Navier_Stokes_FTD_IJK::write_check_etapes_et_termes(), Postprocessing_IJK::write_extra_mesh(), and Navier_Stokes_FTD_IJK::write_qdm_corrections_information().
get_tstep() [2/2]
int & Schema_Temps_IJK_base::get_tstep () inline
References Schema_Temps_base::nb_pas_dt_.
get_tstep_init()
int Schema_Temps_IJK_base::get_tstep_init () const inline
References tstep_init_.
Referenced by Probleme_FTD_IJK_base::sauvegarder_probleme(), and Probleme_FTD_IJK_base::sauver().
get_tstep_sauv()
int Schema_Temps_IJK_base::get_tstep_sauv () const inline
References tstep_sauv_.
get_use_tstep_init()
int Schema_Temps_IJK_base::get_use_tstep_init () const inline
References use_tstep_init_.
get_first_step_interface_smoothing() [1/2]
int & Schema_Temps_IJK_base::get_first_step_interface_smoothing () inline
References first_step_interface_smoothing_.
Referenced by Probleme_FTD_IJK_base::solveTimeStep_Euler().
get_first_step_interface_smoothing() [2/2]
int Schema_Temps_IJK_base::get_first_step_interface_smoothing () const inline
References first_step_interface_smoothing_.
get_enable_dt_oh_ideal_length_factor()
int Schema_Temps_IJK_base::get_enable_dt_oh_ideal_length_factor () const inline
References enable_dt_oh_ideal_length_factor_.
get_dt_sauvegarde()
int Schema_Temps_IJK_base::get_dt_sauvegarde () const inline
References dt_sauvegarde_.
Referenced by Probleme_FTD_IJK_base::sauver().
find_timestep()
double Schema_Temps_IJK_base::find_timestep (const double max_timestep, const double cfl, const double fo, const double oh)
References Statistiques::begin_count(), Sortie_Fichier_base::close(), IJK_Thermals::compute_timestep(), dt_cfl_, dt_cfl_liq_, dt_cfl_vap_, dt_fo_, dt_fo_liq_, dt_fo_vap_, dt_oh_, enable_dt_oh_ideal_length_factor_, Statistiques::end_count(), Probleme_FTD_IJK_base::eq_ns(), Domaine_IJK::get_constant_delta(), Domaine_IJK::get_delta(), Navier_Stokes_FTD_IJK::get_disable_convection_qdm(), Navier_Stokes_FTD_IJK::get_disable_diffusion_qdm(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_domaine(), Remaillage_FT_IJK::get_facteur_longueur_ideale(), Probleme_FTD_IJK_base::get_ijk_thermals(), Fluide_Diphasique_IJK::get_mu_liquid(), Fluide_Diphasique_IJK::get_mu_vapour(), Probleme_FTD_IJK_base::get_remaillage_ft_ijk(), Probleme_FTD_IJK_base::get_reprise(), Fluide_Diphasique_IJK::get_rho_liquid(), Fluide_Diphasique_IJK::get_rho_vapour(), Navier_Stokes_FTD_IJK::get_velocity(), Probleme_FTD_IJK_base::has_interface(), Probleme_FTD_IJK_base::has_thermals(), Schema_Temps_base::ind_temps_cpu_max_atteint, Process::je_suis_maitre(), Statistiques::last_time(), max_simu_time_, Probleme_FTD_IJK_base::milieu_ijk(), Schema_Temps_base::mon_probleme, Process::mp_max(), Process::mp_min(), Schema_Temps_base::nb_pas_dt_, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), Fluide_Diphasique::sigma(), Schema_Temps_base::tcpumax_, Schema_Temps_base::temps_courant_, Schema_Temps_base::temps_cpu_ecoule_, timestep_facsec_, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by computeTimeStep().
set_modified_time_ini()
void Schema_Temps_IJK_base::set_modified_time_ini (const double t) inline
References modified_time_ini_.
Referenced by Probleme_FTD_IJK_base::preparer_calcul().
set_max_timestep()
void Schema_Temps_IJK_base::set_max_timestep (const double t) inline
References max_timestep_.
Referenced by Probleme_FTD_IJK_base::run().
set_max_timestep_if_smaller()
void Schema_Temps_IJK_base::set_max_timestep_if_smaller (const double t) inline
References max_timestep_.
Referenced by Probleme_FTD_IJK_base::run().
set_current_time()
void Schema_Temps_IJK_base::set_current_time (const double t) inline
References Schema_Temps_base::changer_temps_courant().
Referenced by Probleme_FTD_IJK_base::preparer_calcul(), and Probleme_FTD_IJK_base::solveTimeStep().
set_tstep_sauv()
void Schema_Temps_IJK_base::set_tstep_sauv (const int ts) inline
References tstep_sauv_.
Referenced by Probleme_FTD_IJK_base::sauver().
check_stop_criteria()
void Schema_Temps_IJK_base::check_stop_criteria (bool & stop) const
References get_current_time(), get_max_simu_time(), get_nb_timesteps(), get_tstep(), Schema_Temps_base::ind_temps_cpu_max_atteint, Process::je_suis_maitre(), Probleme_U::le_nom(), Entree_Fichier_base::ouvrir(), Schema_Temps_base::pb_base(), Schema_Temps_base::stop(), and stop_file_.
Referenced by Probleme_FTD_IJK_base::run().
Member Data Documentation
info_obj
const Type_info Schema_Temps_IJK_base::info_obj static
dt_cfl_
double Schema_Temps_IJK_base::dt_cfl_ = 1.e20 protected
Referenced by find_timestep(), and get_dt_cfl().
dt_fo_
double Schema_Temps_IJK_base::dt_fo_ = 1.e20 protected
Referenced by find_timestep(), and get_dt_fo().
dt_oh_
double Schema_Temps_IJK_base::dt_oh_ = 1.e20 protected
Referenced by find_timestep(), and get_dt_oh().
dt_fo_liq_
double Schema_Temps_IJK_base::dt_fo_liq_ = 1.e20 protected
Referenced by find_timestep(), and get_dt_fo_liq().
dt_fo_vap_
double Schema_Temps_IJK_base::dt_fo_vap_ = 1.e20 protected
Referenced by find_timestep(), and get_dt_fo_vap_().
dt_cfl_liq_
double Schema_Temps_IJK_base::dt_cfl_liq_ = 1.e20 protected
Referenced by find_timestep(), and get_dt_cfl_liq().
dt_cfl_vap_
double Schema_Temps_IJK_base::dt_cfl_vap_ = 1.e20 protected
Referenced by find_timestep(), and get_dt_cfl_vap_().
timestep_facsec_
double Schema_Temps_IJK_base::timestep_facsec_ = 1. protected
Referenced by computeTimeStep(), find_timestep(), get_timestep_facsec(), printOn(), and set_param().
max_simu_time_
double Schema_Temps_IJK_base::max_simu_time_ = 1e6 protected
Referenced by find_timestep(), get_max_simu_time(), printOn(), and set_param().
modified_time_ini_
double Schema_Temps_IJK_base::modified_time_ini_ = 0. protected
Referenced by get_modified_time_ini(), and set_modified_time_ini().
max_timestep_
double Schema_Temps_IJK_base::max_timestep_ = -123. protected
Referenced by computeTimeStep(), get_max_timestep(), set_max_timestep(), and set_max_timestep_if_smaller().
cfl_
double Schema_Temps_IJK_base::cfl_ = 1. protected
Referenced by computeTimeStep(), printOn(), and set_param().
fo_
double Schema_Temps_IJK_base::fo_ = 1. protected
Referenced by computeTimeStep(), printOn(), and set_param().
oh_
double Schema_Temps_IJK_base::oh_ = 1. protected
Referenced by computeTimeStep(), printOn(), and set_param().
enable_dt_oh_ideal_length_factor_
int Schema_Temps_IJK_base::enable_dt_oh_ideal_length_factor_ = 0 protected
Referenced by find_timestep(), get_enable_dt_oh_ideal_length_factor(), and set_param().
first_step_interface_smoothing_
int Schema_Temps_IJK_base::first_step_interface_smoothing_ = 0 protected
Referenced by completer(), get_first_step_interface_smoothing(), and set_param().
tstep_sauv_
int Schema_Temps_IJK_base::tstep_sauv_ = 0 protected
Referenced by get_tstep_sauv(), and set_tstep_sauv().
tstep_init_
int Schema_Temps_IJK_base::tstep_init_ = 0 protected
Referenced by completer(), get_tstep_init(), printOn(), set_param(), and set_param_reprise_pb().
use_tstep_init_
int Schema_Temps_IJK_base::use_tstep_init_ = 0 protected
Referenced by completer(), get_use_tstep_init(), printOn(), and set_param().
dt_sauvegarde_
int Schema_Temps_IJK_base::dt_sauvegarde_ = 2000000000 protected
Referenced by get_dt_sauvegarde(), printOn(), and set_param().
stop_file_
Nom Schema_Temps_IJK_base::stop_file_ protected
Referenced by check_stop_criteria(), and readOn().