TrioCFD: Save_Restart Class Reference
Save_Restart Class Reference
#include <Save_Restart.h>
Public Member Functions
int allocate_file_size (long int &size) const
Member Function Documentation
assoscier_pb_base()
void Save_Restart::assoscier_pb_base (const Probleme_base & pb)
Referenced by Probleme_base::associer(), and Pb_MED::readOn().
allocation()
void Save_Restart::allocation () const
References EcritureLectureSpecial::Active, allocate_file_size(), Process::barrier(), Process::exit(), Process::je_suis_maitre(), Process::nproc(), and sauver_xyz().
Referenced by Probleme_base::allocation().
allocate_file_size()
int Save_Restart::allocate_file_size (long int & size) const
Verifie que la place necessaire existe sur le disque dur.
Parameters
l'espace disque requis
Returns
(int) retourne 1 si l'espace disque est suffisant, 0 sinon
References Objet_U::nom_du_cas().
Referenced by allocation().
reprise_format_temps()
const char * Save_Restart::reprise_format_temps () const inline
Referenced by Probleme_base::reprise_format_temps().
reprise_effectuee() [1/2]
bool & Save_Restart::reprise_effectuee () inline
Referenced by lire_sauvegarde_reprise(), and Probleme_base::reprise_effectuee().
reprise_effectuee() [2/2]
bool Save_Restart::reprise_effectuee () const inline
preparer_calcul()
void Save_Restart::preparer_calcul ()
References EcritureLectureSpecial::Active, Process::je_suis_maitre(), and sauver_xyz().
Referenced by Probleme_base::preparer_calcul().
sauver_xyz()
void Save_Restart::sauver_xyz (int verbose) const
References Statistiques::begin_count(), Objet_U_ptr::detach(), Statistiques::end_count(), EcritureLectureSpecial::get_Output(), Process::je_suis_maitre(), Statistiques::last_time(), TRUST_Ref< _CLASSE_ >::le_nom(), EcritureLectureSpecial::mode_ecr, Objet_U::nom_du_cas(), Sortie_Fichier_base::ouvrir(), Objet_U_ptr::typer(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by allocation(), finir(), and preparer_calcul().
is_restart_in_progress()
bool Save_Restart::is_restart_in_progress () const inline
Referenced by Probleme_base::postraiter().
set_restart_in_progress()
void Save_Restart::set_restart_in_progress (const bool res) inline
Referenced by Probleme_base::postraiter().
is_sauvegarde_simple()
int Save_Restart::is_sauvegarde_simple () const inline
Referenced by Probleme_base::is_sauvegarde_simple().
checkpoint_filename()
const Nom & Save_Restart::checkpoint_filename () const inline
Referenced by Probleme_base::checkpoint_filename().
restart_filename()
const Nom & Save_Restart::restart_filename () const inline
Referenced by Probleme_base::restart_filename().
checkpoint_format()
const Nom & Save_Restart::checkpoint_format () const inline
Referenced by Probleme_base::checkpoint_format().
yaml_filename()
const Nom & Save_Restart::yaml_filename () const inline
Referenced by Probleme_base::yaml_filename().
lire_sauvegarde_reprise()
void Save_Restart::lire_sauvegarde_reprise (Entree & is, Motcle & motlu)
References EcritureLectureSpecial::Active, Objet_U_ptr::detach(), Process::exit(), Process::force_single_file(), TRUST_Ref< _CLASSE_ >::le_nom(), Objet_U::nom_du_cas(), Process::nproc(), and reprise_effectuee().
Referenced by Probleme_base::readOn().
sauver()
int Save_Restart::sauver () const
Ecriture sur fichier en vue d'une reprise (sauvegarde)
References Ecrire_YAML::add_pb_base(), FichierHDF::close(), FichierHDF::create(), FichierHDF::create_and_fill_dataset_MW(), Objet_U_ptr::detach(), Process::exit(), EcritureLectureSpecial::get_Output(), Nom::getString(), TRUST_2_PDI::init(), TRUST_2_PDI::is_PDI_initialized(), Process::je_suis_maitre(), TRUST_Ref< _CLASSE_ >::le_nom(), EcritureLectureSpecial::mode_ecr, Process::node_master(), Objet_U_ptr::non_nul(), Process::nproc(), Sortie_Fichier_base::ouvrir(), AbstractIO::set_64b(), TRUST_2_PDI::set_PDI_checkpoint(), Sortie_Fichier_base::setf(), TRUST_2_PDI::stop_sharing(), TRUST_2_PDI::stop_sharing_last_variable(), TRUST_2_PDI::trigger(), TRUST_2_PDI::TRUST_start_sharing(), Objet_U_ptr::typer(), TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_2_PDI::write(), and Ecrire_YAML::write_checkpoint_file().
Referenced by Probleme_base::sauver().
finir()
void Save_Restart::finir ()
References EcritureLectureSpecial::Active, FichierHDF::close(), FichierHDF::create(), FichierHDF::create_and_fill_dataset_MW(), Objet_U_ptr::detach(), TRUST_2_PDI::finalize(), TRUST_2_PDI::is_PDI_initialized(), Process::je_suis_maitre(), Objet_U_ptr::non_nul(), sauver_xyz(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by Probleme_base::finir().