TrioCFD: Operateur Class Reference
Operateur Class Reference abstract
#include <Operateur.h>
Public Member Functions
DoubleTab & ajouter (const Champ_Inc_base &, DoubleTab &) const
DoubleTab & ajouter (DoubleTab &) const
DoubleTab & calculer (const Champ_Inc_base &, DoubleTab &) const
DoubleTab & calculer (DoubleTab &) const
virtual void completer ()
const Discretisation_base & discretisation () const
int impr (Sortie &os) const
void imprimer (Sortie &os) const
int limpr () const
Entree & lire (Entree &)
virtual void mettre_a_jour (double temps)
const Champ_Inc_base & mon_inconnue () const
const Nom & type () const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Detailed Description
Cette classe generique est particuliere car elle n'HERITE PAS
de OWN_PTR(Operateur_base) mais de MorEqn.
Une reference sur un Operateur_base est renvoye par la methode
Operateur::l_op_base() qui est virtuelle pure et doit etre surchargee
dans ses derivees.
See also
MorEqn Operateur_base, Classe abstraite, Methodes abstraites:, Operateur_base& l_op_base(), const Operateur_base& l_op_base() const, DoubleTab& calculer(const DoubleTab&,DoubleTab&) const, DoubleTab& calculer(const DoubleTab&,DoubleTab&) const
Member Function Documentation
l_op_base() [1/2]
virtual Operateur_base & Operateur::l_op_base () pure virtual
Implemented in Op_Diff_Fluctu_Temp, Op_Diff_Flux_Chaleur_Turb, Operateur_Conv, Operateur_Diff, Operateur_Div, Operateur_Grad, and Operateur_Evanescence.
Referenced by Equation_base::abortTimeStep(), ajouter(), Terme_Source_Th_TdivU_VEF_Face::ajouter(), Nucleation_paroi_PolyMAC_P0::ajouter_blocs(), Production_energie_cin_turb_PolyMAC_P0::ajouter_blocs(), Source_BIF_PolyMAC_P0::ajouter_blocs(), Source_Dissipation_energie_cin_turb::ajouter_blocs(), Production_energie_cin_turb_VDF::ajouter_blocs(), Source_Flux_interfacial_base::ajouter_blocs(), Correction_Lubchenko_PolyMAC_P0::ajouter_blocs_BIF(), ajouter_contribution_explicite_au_second_membre(), Equation_base::ajouter_termes_croises(), Equation_base::assembler(), Convection_Diffusion_Espece_Multi_QC::assembler(), Convection_Diffusion_Temperature::assembler(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_avec_inertie_impl(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_blocs(), Equation_base::assembler_blocs(), Convection_Diffusion_Temperature::assembler_blocs(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_blocs_avec_inertie(), Convection_Diffusion_Espece_Multi_QC::assembler_blocs_avec_inertie(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_impl(), associer_champ(), Champ_P1NC::calcul_h_conv(), Convection_Diffusion_Fluide_Dilatable_Proto::calculer_div_rho_u_impl(), Equation_base::calculer_pas_de_temps(), calculer_pas_de_temps(), Pb_Multiphase::calculer_pas_de_temps(), Equation_base::calculer_pas_de_temps_locaux(), calculer_pas_de_temps_locaux(), Equation_base::completer(), completer(), Source_Dissipation_energie_cin_turb::completer(), Production_energie_cin_turb_VDF::completer(), Travail_pression_VDF::completer(), Terme_Source_Canal_perio::compute_heat_flux(), Equation_base::contribuer_termes_croises(), Equation_base::creer_champ(), Equation_base::derivee_en_temps_inco(), Navier_Stokes_std::derivee_en_temps_inco(), Equation_base::dimensionner_blocs(), Equation_base::dimensionner_matrice_sans_mem(), Equation_base::dimensionner_termes_croises(), Equation_base::get_champ(), Equation_base::get_noms_champs_postraitables(), Equation_base::has_champ(), Equation_base::has_interface_blocs(), impr(), imprimer(), Echange_contact_PolyMAC_P0::init_op(), Echange_contact_PolyMAC_P0P1NC::init_op(), Op_Diff_VDF_base::init_op_ext(), Echange_contact_PolyMAC::initialiser(), lire(), mettre_a_jour(), Op_Dift_Multiphase_VDF_Elem::mettre_a_jour(), Op_Diff_Turbulent_PolyMAC_P0_Elem::modifier_mu(), Equation_base::modifier_pour_Cl(), Equation_base::preparer_calcul(), Equation_base::printOn(), Equation_base::resetTime(), set_description(), set_fichier(), Echange_contact_PolyMAC::update_coeffs(), Echange_contact_PolyMAC::update_delta(), and Equation_base::updateGivenFields().
l_op_base() [2/2]
virtual const Operateur_base & Operateur::l_op_base () const pure virtual
Implemented in Op_Diff_Fluctu_Temp, Op_Diff_Flux_Chaleur_Turb, Operateur_Conv, Operateur_Diff, Operateur_Div, Operateur_Grad, and Operateur_Evanescence.
ajouter() [1/3]
virtual DoubleTab & Operateur::ajouter (const DoubleTab & , DoubleTab &) const pure virtual
Implemented in Op_Diff_Fluctu_Temp, Op_Diff_Flux_Chaleur_Turb, Operateur_Conv, Operateur_Diff, Operateur_Div, Operateur_Grad, and Operateur_Evanescence.
Referenced by ajouter(), Terme_Source_Th_TdivU_VEF_Face::ajouter(), Equation_base::assembler(), Convection_Diffusion_Espece_Multi_QC::assembler(), Convection_Diffusion_Temperature::assembler(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_avec_inertie_impl(), calculer(), Convection_Diffusion_Fluide_Dilatable_Proto::calculer_div_rho_u_impl(), Terme_Source_Canal_perio::compute_heat_flux(), Equation_base::derivee_en_temps_inco(), Convection_Diffusion_Espece_Multi_QC::derivee_en_temps_inco(), Navier_Stokes_std::derivee_en_temps_inco(), Convection_Diffusion_Fluide_Dilatable_Proto::derivee_en_temps_inco_sans_solveur_masse_impl(), Navier_Stokes_IBM::preparer_calcul(), and Navier_Stokes_std::preparer_calcul().
calculer() [1/3]
virtual DoubleTab & Operateur::calculer (const DoubleTab & , DoubleTab &) const pure virtual
Implemented in Op_Diff_Fluctu_Temp, Op_Diff_Flux_Chaleur_Turb, Operateur_Conv, Operateur_Diff, Operateur_Div, Operateur_Grad, and Operateur_Evanescence.
Referenced by ajouter(), calculer(), and Equation_base::derivee_en_temps_inco().
ajouter() [2/3]
DoubleTab & Operateur::ajouter (const Champ_Inc_base & ch, DoubleTab & resu) const
Calcule et ajoute la contribution de l'operateur au second membre de l'equation.
Appelle Operateur::ajouter(const DoubleTab&, DoubleTab&)
Parameters
(Champ_Inc_base& ch) le champ inconnu sur lequel l'operateur agit
[in,out] (DoubleTab& resu) le tableau stockant les valeurs du second membre auquel on ajoute la contribution de l'operateur
Returns
(DoubleTab&) le second membre auquel on a ajoute la contribution de l'operateur
References TRUSTVect< _TYPE_, _SIZE_ >::ajoute(), TRUSTVect< _TYPE_, _SIZE_ >::ajoute_sans_ech_esp_virt(), ajouter(), Solveur_Masse_base::appliquer(), calculer(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), MorEqn::equation(), Operateur_base::get_nb_ss_pas_de_temps(), l_op_base(), Schema_Temps_base::pas_de_temps(), Equation_base::schema_temps(), Equation_base::solv_masse(), and Champ_Inc_base::valeurs().
calculer() [2/3]
DoubleTab & Operateur::calculer (const Champ_Inc_base & ch, DoubleTab & resu) const
Calcule la contribution de l'operateur, et renvoie le tableau des valeurs.
Parameters
(Champ_Inc_base& ch) le champ inconnu sur lequel l'operateur agit
(DoubleTab& resu) le tableau stockant les valeurs resultant de l'application de l'operateur sur le champ inconnu.
Returns
(DoubleTab&) le resultat de l'application de l'operateur sur le champ inconnu
References calculer(), and Champ_Inc_base::valeurs().
ajouter() [3/3]
DoubleTab & Operateur::ajouter (DoubleTab & resu) const
Ajoute la contribution de l'operateur au tableau passe en parametre.
Appelle Operateur::ajouter(const Champ_Inc_base&, DoubleTab&)
Parameters
(DoubleTab& resu) le tableau stockant les valeurs du second membre auquel on ajoute la contribution de l'operateur
Returns
(DoubleTab&) le second membre auquel on a ajoute la contribution de l'operateur
References ajouter(), and le_champ_inco.
calculer() [3/3]
DoubleTab & Operateur::calculer (DoubleTab & resu) const
Applique l'operateur au champ inconnu et renvoie le resultat.
Appelle Operateur::calculer(const Champ_Inc_base&, DoubleTab&);
Parameters
(DoubleTab& resu) le tableau stockant les valeurs resultant de l'application de l'operateur sur le champ inconnu.
Returns
(DoubleTab&) le resultat de l'application de l'operateur sur le champ inconnu
References ajouter(), and le_champ_inco.
type()
const Nom & Operateur::type () const
Renvoie le (nom du) type de l'operateur a creer.
Returns
(Nom&) le nom du type de l'operateur a creer
References typ.
Referenced by Operateur_Conv_sensibility_VEF::ajouter(), Operateur_Conv_sensibility_VEF::ajouter_conv_term(), Op_Conv_ALE_VEF::ajouterALE(), and Convection_Diffusion_Temperature_FT_Disc::compute_divergence_free_velocity_extension().
calculer_pas_de_temps()
double Operateur::calculer_pas_de_temps () const
Calcule le prochain pas de temps.
References Statistiques::begin_count(), Operateur_base::calculer_dt_stab(), Statistiques::end_count(), MorEqn::equation(), l_op_base(), and Process::mp_min().
Referenced by Transport_Interfaces_FT_Disc::calcul_vitesse(), Equation_base::calculer_pas_de_temps(), Navier_Stokes_phase_field::calculer_pas_de_temps(), Pb_Multiphase::calculer_pas_de_temps(), and Equation_base::derivee_en_temps_conv().
calculer_pas_de_temps_locaux()
void Operateur::calculer_pas_de_temps_locaux (DoubleTab & dt_locaux) const
Calculate the next local time steps.
References Operateur_base::calculer_dt_local(), and l_op_base().
Referenced by Equation_base::calculer_pas_de_temps_locaux().
impr()
int Operateur::impr (Sortie & os) const
Imprime l'operateur sur un flot de sortie de facon inconditionnelle.
Parameters
(Sortie& os) le flot de sortie pour l'impression
Returns
(int) code de Operateur_base::impr(Sortie&)
References Operateur_base::impr(), and l_op_base().
Referenced by Equation_base::impr(), and Navier_Stokes_std::impr().
typer()
virtual void Operateur::typer () pure virtual
Implemented in Op_Diff_Fluctu_Temp, Op_Diff_Flux_Chaleur_Turb, Operateur_Conv, Operateur_Diff, Operateur_Div, Operateur_Grad, and Operateur_Evanescence.
Referenced by lire().
completer()
void Operateur::completer () virtual
Met a jour les references des objets associes a l'operateur.
Operateur::le_champ_inco, Operateur::champ_inco Appelle Operateur_base::completer()
Reimplemented in Op_Diff_Fluctu_Temp, and Op_Diff_Flux_Chaleur_Turb.
References Operateur_base::completer(), l_op_base(), le_champ_inco, MorEqn::mon_equation, and TRUST_Ref< _CLASSE_ >::non_nul().
Referenced by Equation_base::completer(), Op_Conv_ALE_VEF::completer(), Convection_Diffusion_Phase_field::completer(), Op_Diff_Fluctu_Temp::completer(), Op_Diff_Flux_Chaleur_Turb::completer(), Transport_Fluctuation_Temperature::completer(), Transport_Flux_Chaleur_Turbulente::completer(), Navier_Stokes_std::completer(), Champ_Generique_Divergence::completer(), Convection_Diffusion_Temperature_FT_Disc::compute_divergence_free_velocity_extension(), and Equation_rayonnement_base::readOn().
mettre_a_jour()
void Operateur::mettre_a_jour (double temps) virtual
Effecttue une mise a jour en temps de l'operateur.
Appelle Operateur_base::mettre_a_jour(double)
Parameters
(double temps) le pas de temps de mise a jour
References l_op_base(), and Operateur_base::mettre_a_jour().
Referenced by Equation_base::initTimeStep().
mon_inconnue()
const Champ_Inc_base & Operateur::mon_inconnue () const
Renvoie le champ representant l'inconnue de l'equation dont l'operateur fait partie.
Returns
(Champ_Inc_base&) le champ inconuu de l'equation associee
References le_champ_inco, and TRUST_Ref< _CLASSE_ >::valeur().
discretisation()
const Discretisation_base & Operateur::discretisation () const
Renvoie la discretisation de l'equation dont l'operateur fait partie.
Returns
(Discretisation_base&) la discretisation de l'equation associee
References MorEqn::mon_equation.
limpr()
int Operateur::limpr () const
Demande a l'equation si une impression est necessaire Renvoie 1 pour OUI, 0 sinon.
Returns
(int) 1 si une impression est necessaire 0 sinon
References MorEqn::mon_equation.
Referenced by imprimer().
imprimer()
void Operateur::imprimer (Sortie & os) const
Imprime l'operateur sur un flot de sortie, si c'est necessaire.
(voir Schema_Temp_base::limpr())
Parameters
(Sortie& os) le flot de sortie pour l'impression
References Operateur_base::impr(), l_op_base(), and limpr().
ecrire()
Sortie & Operateur::ecrire (Sortie & os) const
References typ.
Referenced by Operateur_Conv::printOn(), Operateur_Diff::printOn(), Operateur_Div::printOn(), Operateur_Grad::printOn(), and Operateur_Evanescence::printOn().
lire()
Entree & Operateur::lire (Entree & is)
Lit un operateur sur un flot d'entree.
Type l'operateur et lui associe son equation. Format: { [UN Motcle REPRESENTANT UN TYPE] }
Parameters
(Entree& is) le flot d'entree ou lire l'operateur
Returns
(Entree&) le flot d'entree modifie
Exceptions
accolade ouvrante attendue
accolade fermante attendue
References Operateur_base::associer_eqn(), MorEqn::equation(), Process::exit(), l_op_base(), Operateur_base::lire_solveur(), Operateur_base::set_decal_temps(), Operateur_base::set_nb_ss_pas_de_temps(), typ, and typer().
Referenced by Op_Conv_ALE_VEF::readOn(), Operateur_Conv_sensibility_VEF::readOn(), Op_Diff_Fluctu_Temp::readOn(), Op_Diff_Flux_Chaleur_Turb::readOn(), Operateur_Conv::readOn(), Operateur_Diff::readOn(), Operateur_Div::readOn(), Operateur_Grad::readOn(), and Operateur_Evanescence::readOn().
ajouter_contribution_explicite_au_second_membre()
void Operateur::ajouter_contribution_explicite_au_second_membre (const Champ_Inc_base & inconnue, DoubleTab & derivee) const
References Operateur_base::ajouter_contribution_explicite_au_second_membre(), and l_op_base().
associer_champ()
void Operateur::associer_champ (const Champ_Inc_base & ch, const std::string & nom_ch)
References Operateur_base::associer_champ(), l_op_base(), le_champ_inco, and nom_inco_.
set_fichier()
void Operateur::set_fichier (const Nom & nom)
References l_op_base(), and Operateur_base::set_fichier().
Referenced by Echelle_temporelle_turbulente::readOn(), Energie_cinetique_turbulente::readOn(), Energie_cinetique_turbulente_WIT::readOn(), Taux_dissipation_turbulent::readOn(), Convection_Diffusion_Temperature_FT_Disc::readOn(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::readOn(), Convection_Diffusion_Espece_Binaire_base::readOn(), Convection_Diffusion_Espece_Multi_base::readOn(), Convection_Diffusion_Concentration::readOn(), Convection_Diffusion_Temperature::readOn(), Navier_Stokes_std::readOn(), Aire_interfaciale::readOn(), Energie_Multiphase::readOn(), Masse_Multiphase::readOn(), and Conduction::readOn().
set_description()
void Operateur::set_description (const Nom & nom)
References l_op_base(), and Operateur_base::set_description().
Referenced by Echelle_temporelle_turbulente::readOn(), Energie_cinetique_turbulente::readOn(), Energie_cinetique_turbulente_WIT::readOn(), Taux_dissipation_turbulent::readOn(), Convection_Diffusion_Temperature_FT_Disc::readOn(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::readOn(), Convection_Diffusion_Espece_Binaire_base::readOn(), Convection_Diffusion_Espece_Multi_base::readOn(), Navier_Stokes_Fluide_Dilatable_base::readOn(), Convection_Diffusion_Concentration::readOn(), Convection_Diffusion_Temperature::readOn(), Navier_Stokes_std::readOn(), Aire_interfaciale::readOn(), Energie_Multiphase::readOn(), Masse_Multiphase::readOn(), QDM_Multiphase::readOn(), Navier_Stokes_Turbulent_QC::readOn(), and Conduction::readOn().
op_non_nul()
virtual int Operateur::op_non_nul () const pure virtual
Implemented in Op_Diff_Fluctu_Temp, Op_Diff_Flux_Chaleur_Turb, Operateur_Conv, Operateur_Diff, Operateur_Div, Operateur_Grad, and Operateur_Evanescence.
Referenced by Equation_base::creer_champ(), Equation_base::get_champ(), Equation_base::get_noms_champs_postraitables(), Equation_base::has_champ(), and Equation_base::updateGivenFields().
Member Data Documentation
nom_inco_
std::string Operateur::nom_inco_ protected
Referenced by associer_champ().
le_champ_inco
TRUST_Ref< Champ_Inc_base *> Operateur::le_champ_inco protected
Referenced by ajouter(), associer_champ(), calculer(), completer(), and mon_inconnue().
typ
Motcle Operateur::typ protected
Referenced by ecrire(), lire(), type(), Op_Diff_Fluctu_Temp::typer(), Op_Diff_Flux_Chaleur_Turb::typer(), Operateur_Conv::typer(), Operateur_Diff::typer(), and Operateur_Evanescence::typer().