TrioCFD: Cond_Lim_Rayo Class Reference
Cond_Lim_Rayo Class Reference
#include <Cond_Lim_Rayo.h>
Constructor & Destructor Documentation
~Cond_Lim_Rayo()
Cond_Lim_Rayo::~Cond_Lim_Rayo () inline virtual
Member Function Documentation
completer()
void Cond_Lim_Rayo::completer () virtual
Reimplemented in Frontiere_Ouverte_Rayo_transp, Frontiere_Ouverte_temperature_imposee_Rayo_transp, Echange_contact_Rayo_transp_VDF, Echange_externe_impose_rayo_transp, Paroi_flux_impose_Rayo_transp, and Temperature_imposee_paroi_rayo_transp.
References Process::exit().
preparer_surface()
void Cond_Lim_Rayo::preparer_surface (const Frontiere_dis_base & fr, const Domaine_Cl_dis_base & zcl)
References Domaine_Cl_dis_base::domaine_dis(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), Surf_i, and Teta_i.
Referenced by Frontiere_Ouverte_Rayo_transp::completer(), Frontiere_Ouverte_temperature_imposee_Rayo_transp::completer(), Echange_contact_Rayo_transp_VDF::completer(), Echange_externe_impose_rayo_transp::completer(), Paroi_flux_impose_Rayo_transp::completer(), and Temperature_imposee_paroi_rayo_transp::completer().
associer_modele_rayo()
void Cond_Lim_Rayo::associer_modele_rayo (Modele_Rayonnement_base & mod) virtual
Reimplemented in Temperature_imposee_paroi_rayo_transp.
References le_modele_rayo.
surface()
double Cond_Lim_Rayo::surface (int numfa) const inline virtual
References Surf_i.
Referenced by Ensemble_Faces_base::surface().
teta_i() [1/2]
double Cond_Lim_Rayo::teta_i (int numfa) inline virtual
References Teta_i.
Referenced by Ensemble_Faces_base::teta_i().
teta_i() [2/2]
double Cond_Lim_Rayo::teta_i (int numfa) const inline virtual
References Teta_i.
modele_rayo() [1/2]
Modele_Rayonnement_Milieu_Transparent & Cond_Lim_Rayo::modele_rayo () inline
References le_modele_rayo, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Temperature_imposee_paroi_rayo_transp::associer_modele_rayo().
modele_rayo() [2/2]
const Modele_Rayonnement_Milieu_Transparent & Cond_Lim_Rayo::modele_rayo () const inline
References le_modele_rayo, and TRUST_Ref< _CLASSE_ >::valeur().
Member Data Documentation
Surf_i
DoubleVect Cond_Lim_Rayo::Surf_i protected
Referenced by preparer_surface(), and surface().
Teta_i
DoubleVect Cond_Lim_Rayo::Teta_i protected
Referenced by Frontiere_Ouverte_Rayo_transp::calculer_Teta_i(), Frontiere_Ouverte_temperature_imposee_Rayo_transp::calculer_Teta_i(), Echange_externe_impose_rayo_transp::calculer_Teta_i(), Temperature_imposee_paroi_rayo_transp::calculer_Teta_i(), Paroi_flux_impose_Rayo_transp::calculer_Teta_i_VDF(), Paroi_flux_impose_Rayo_transp::calculer_Teta_i_VEF(), Echange_contact_Rayo_transp_VDF::calculer_Teta_paroi(), Echange_contact_Rayo_transp_VDF::completer(), Paroi_flux_impose_Rayo_transp::completer(), preparer_surface(), and teta_i().
le_modele_rayo
TRUST_Ref< Modele_Rayonnement_Milieu_Transparent *> Cond_Lim_Rayo::le_modele_rayo protected
Referenced by associer_modele_rayo(), Temperature_imposee_paroi_rayo_transp::associer_modele_rayo(), Paroi_flux_impose_Rayo_transp::calculer_Teta_i_VDF(), Paroi_flux_impose_Rayo_transp::calculer_Teta_i_VEF(), Echange_contact_Rayo_transp_VDF::calculer_Teta_paroi(), Paroi_Rayo_transp::flux_impose(), and modele_rayo().