TrioCFD: Energie_cinetique_turbulente_WIT Class Reference
Energie_cinetique_turbulente_WIT Class Reference
#include <Energie_cinetique_turbulente_WIT.h>
Public Member Functions
void associer_fluide (const Fluide_base &)
void associer_milieu_base (const Milieu_base &) override
const Motcle & domaine_application () const override
const Type_info * get_info () const override
int impr (Sortie &os) const override
const Champ_Inc_base & inconnue () const override
Champ_Inc_base & inconnue () override
const Milieu_base & milieu () const override
Milieu_base & milieu () override
Public Member Functions inherited from Convection_Diffusion_std
void associer_vitesse (const Champ_base &)
const Type_info * get_info () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
int nombre_d_operateurs () const override
const Operateur & operateur (int) const override
Operateur & operateur (int) override
const Champ_Inc_base & vitesse_transportante () const
Public Member Functions inherited from Equation_base
virtual void abortTimeStep ()
virtual void associer_domaine_dis (const Domaine_dis_base &)
virtual void associer_pb_base (const Probleme_base &)
virtual void associer_sch_tps_base (const Schema_Temps_base &)
virtual double calculer_pas_de_temps () const
virtual void completer ()
virtual std::vector< YAML_data > data_a_sauvegarder () const
DoubleTab & derivee_en_temps_conv (DoubleTab &, const DoubleTab &)
virtual DoubleTab & derivee_en_temps_inco (DoubleTab &)
const Discretisation_base & discretisation () const
virtual void discretiser ()
virtual const Motcle & domaine_application () const
virtual Domaine_Cl_dis_base & domaine_Cl_dis ()
virtual const Domaine_Cl_dis_base & domaine_Cl_dis () const
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual void imprimer (Sortie &os) const
virtual bool initTimeStep (double dt)
const Nom & le_nom () const override
int limpr () const
virtual void mettre_a_jour (double temps)
virtual int preparer_calcul ()
Probleme_base & probleme ()
const Probleme_base & probleme () const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Schema_Temps_base & schema_temps ()
const Schema_Temps_base & schema_temps () const
Solveur_Masse_base & solv_masse ()
const Solveur_Masse_base & solv_masse () const
Sources & sources ()
const Sources & sources () const
virtual void valider_iteration ()
virtual void verifie_ch_init_nb_comp (const Champ_Inc_base &ch_ref, const int nb_comp) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Equation_base
virtual Entree & lire_cl (Entree &)
virtual Entree & lire_cond_init (Entree &)
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual Entree & lire_sources (Entree &)
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
virtual int verif_Cl () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
See also
Conv_Diffusion_std Convection_Diffusion_Temperature
Constructor & Destructor Documentation
~Energie_cinetique_turbulente_WIT()
Energie_cinetique_turbulente_WIT::~Energie_cinetique_turbulente_WIT ()
Energie_cinetique_turbulente_WIT()
Energie_cinetique_turbulente_WIT::Energie_cinetique_turbulente_WIT ()
Member Function Documentation
cree_instance()
Objet_U * Energie_cinetique_turbulente_WIT::cree_instance () static
taille_memoire()
unsigned Energie_cinetique_turbulente_WIT::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Energie_cinetique_turbulente_WIT::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Energie_cinetique_turbulente_WIT::info () static
get_info()
const Type_info * Energie_cinetique_turbulente_WIT::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Convection_Diffusion_std.
self_cast() [1/2]
Energie_cinetique_turbulente_WIT & Energie_cinetique_turbulente_WIT::self_cast (Objet_U & r) static
self_cast() [2/2]
const Energie_cinetique_turbulente_WIT & Energie_cinetique_turbulente_WIT::self_cast (const Objet_U & r) static
printOn()
Sortie & Energie_cinetique_turbulente_WIT::printOn (Sortie & is) const override protected virtual
Simple appel a: Convection_Diffusion_std::printOn(Sortie&)
Parameters
(Sortie& is) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Convection_Diffusion_std.
References Convection_Diffusion_std::printOn().
readOn()
Entree & Energie_cinetique_turbulente_WIT::readOn (Entree & is) override protected virtual
Verifie si l'equation a une inconnue et un fluide associe et appelle Convection_Diffusion_std::readOn(Entree&).
Parameters
(Entree& is) un flot d'entree
Returns
(Entree& is) le flot d'entree modifie
Reimplemented from Convection_Diffusion_std.
References l_inco_ch, le_fluide, Objet_U_ptr::non_nul(), TRUST_Ref< _CLASSE_ >::non_nul(), Convection_Diffusion_std::readOn(), Operateur::set_description(), Operateur::set_fichier(), Convection_Diffusion_std::terme_convectif, and Convection_Diffusion_std::terme_diffusif.
associer_fluide()
void Energie_cinetique_turbulente_WIT::associer_fluide (const Fluide_base & un_fluide)
Associe un fluide incompressible a l'equation.
Parameters
(Fluide_base& un_fluide) le milieu fluide incompressible a associer a l'equation
References le_fluide.
Referenced by associer_milieu_base().
inconnue() [1/2]
const Champ_Inc_base & Energie_cinetique_turbulente_WIT::inconnue () const inline override virtual
Renvoie le champ inconnue representant l'inconnue (T ou H) (version const)
Returns
(Champ_Inc_base&) le champ inconnue representant la temperature (GP) ou l'enthalpie (GR)
Implements Convection_Diffusion_std.
References l_inco_ch.
inconnue() [2/2]
Champ_Inc_base & Energie_cinetique_turbulente_WIT::inconnue () inline override virtual
Renvoie le champ inconnue representant l'inconnue (T ou H)
Returns
(Champ_Inc_base&) le champ inconnue representant la temperature (GP) ou l'enthalpie (GR)
Implements Convection_Diffusion_std.
References l_inco_ch.
discretiser()
void Energie_cinetique_turbulente_WIT::discretiser () override virtual
Discretise l'equation.
Reimplemented from Equation_base.
References Champs_compris_T< FIELD_TYPE >::ajoute_champ(), Equation_base::champs_compris_, Equation_base::discretisation(), Equation_base::discretiser(), Discretisation_base::discretiser_champ(), Equation_base::domaine_dis(), Field_base::fixer_nature_du_champ(), Field_base::fixer_nom_compo(), l_inco_ch, Schema_Temps_base::nb_valeurs_temporelles(), Equation_base::schema_temps(), and Schema_Temps_base::temps_courant().
milieu() [1/2]
const Milieu_base & Energie_cinetique_turbulente_WIT::milieu () const override virtual
Renvoie le milieu physique de l'equation.
(un Fluide_base upcaste en Milieu_base) (version const)
Returns
(Milieu_base&) le Fluide_base upcaste en Milieu_base
Implements Equation_base.
References le_fluide.
Referenced by diffusivite_pour_pas_de_temps(), and diffusivite_pour_transport().
milieu() [2/2]
Milieu_base & Energie_cinetique_turbulente_WIT::milieu () override virtual
Renvoie le milieu physique de l'equation.
(un Fluide_base upcaste en Milieu_base)
Returns
(Milieu_base&) le Fluide_base upcaste en Milieu_base
Implements Equation_base.
References le_fluide.
associer_milieu_base()
void Energie_cinetique_turbulente_WIT::associer_milieu_base (const Milieu_base & un_milieu) override virtual
Associe un milieu physique a l'equation, le milieu est en fait caste en Fluide_base ou en Fluide_Ostwald.
Parameters
(Milieu_base& un_milieu)
Exceptions
les proprietes physiques du fluide ne sont pas toutes specifiees
Implements Equation_base.
References associer_fluide().
impr()
int Energie_cinetique_turbulente_WIT::impr (Sortie & os) const override virtual
Impression des flux sur les bords sur un flot de sortie.
Appelle Equation_base::impr(Sortie&)
Parameters
(Sortie& os) un flot de sortie
Returns
(int) code de retour propage
Reimplemented from Equation_base.
References Equation_base::impr().
diffusivite_pour_transport()
const Champ_Don_base & Energie_cinetique_turbulente_WIT::diffusivite_pour_transport () const override virtual
Reimplemented from Convection_Diffusion_std.
References milieu().
diffusivite_pour_pas_de_temps()
const Champ_base & Energie_cinetique_turbulente_WIT::diffusivite_pour_pas_de_temps () const override virtual
Reimplemented from Convection_Diffusion_std.
References milieu().
domaine_application()
const Motcle & Energie_cinetique_turbulente_WIT::domaine_application () const override virtual
Renvoie le nom du domaine d'application de l'equation.
Ici "Thermique".
Returns
(Motcle&) le nom du domaine d'application de l'equation
Reimplemented from Equation_base.
calculer_alpha_rho_k_WIT()
void Energie_cinetique_turbulente_WIT::calculer_alpha_rho_k_WIT (const Objet_U & obj, DoubleTab & val, DoubleTab & bval, tabs_t & deriv) static
References TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Equation_base::inconnue(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Champ_Inc_base::valeur_aux_bords(), and Champ_Inc_base::valeurs().
Referenced by get_fonc_champ_conserve().
get_fonc_champ_conserve()
virtual std::pair< std::string, fonc_calc_t > Energie_cinetique_turbulente_WIT::get_fonc_champ_conserve () const inline override virtual
Reimplemented from Equation_base.
References calculer_alpha_rho_k_WIT().
positive_unkown()
virtual bool Energie_cinetique_turbulente_WIT::positive_unkown () inline override virtual
Reimplemented from Equation_base.
Member Data Documentation
info_obj
const Type_info Energie_cinetique_turbulente_WIT::info_obj static
l_inco_ch
TRUST_Deriv< Champ_Inc_base > Energie_cinetique_turbulente_WIT::l_inco_ch protected
Referenced by discretiser(), inconnue(), and readOn().
le_fluide
TRUST_Ref< Fluide_base *> Energie_cinetique_turbulente_WIT::le_fluide protected
Referenced by associer_fluide(), milieu(), and readOn().