TrioCFD: Joint_32_64< _SIZE_ > Class Template Reference
Joint_32_64< _SIZE_ > Class Template Reference
#include <Joint.h>
Public Member Functions
void ajouter_faces (const IntTab_t &)
const Type_info * get_info () const override
Joint_Items_t & set_joint_item (JOINT_ITEM type)
Public Member Functions inherited from Frontiere_32_64< _SIZE_ >
void add (const Frontiere_32_64 &)
void ajouter_faces (const IntTab_t &)
void associer_domaine (const Domaine_t &)
Domaine_t & domaine ()
const Domaine_t & domaine () const
const Type_info * get_info () const override
const Nom & le_nom () const override
IntTab_t & les_sommets_des_faces ()
const IntTab_t & les_sommets_des_faces () const
void nommer (const Nom &) override
void renum (const IntVect_t &)
void typer_faces (const Motcle &)
void typer_faces (const Type_Face &)
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
template<typename _SIZE_>
class Joint_32_64< _SIZE_ >
Elle porte en plus dans les Joint_Items les informations permettant de construire les tableaux distribues indexes par les items geometriques (sommets, faces, elements, aretes, faces_frontieres)
See also
Scatter Joint_Item
Member Typedef Documentation
int_t
template<typename _SIZE_ > using Joint_32_64< _SIZE_ >::int_t = _SIZE_
ArrOfInt_t
template<typename _SIZE_ > using Joint_32_64< _SIZE_ >::ArrOfInt_t = ArrOfInt_T<_SIZE_>
IntTab_t
template<typename _SIZE_ > using Joint_32_64< _SIZE_ >::IntTab_t = IntTab_T<_SIZE_>
Joint_Items_t
template<typename _SIZE_ > using Joint_32_64< _SIZE_ >::Joint_Items_t = Joint_Items_32_64<_SIZE_>
Frontiere_t
template<typename _SIZE_ > using Joint_32_64< _SIZE_ >::Frontiere_t = Frontiere_32_64<_SIZE_>
Constructor & Destructor Documentation
Joint_32_64()
template<typename _T_ > Joint_32_64< _T_ >::Joint_32_64
~Joint_32_64()
template<typename _T_ > Joint_32_64< _T_ >::~Joint_32_64
Member Function Documentation
cree_instance()
template<typename _T_ > Objet_U * Joint_32_64< _T_ >::cree_instance static
taille_memoire()
template<typename _T_ > unsigned Joint_32_64< _T_ >::taille_memoire override virtual
Implements Objet_U.
duplique()
template<typename _T_ > int Joint_32_64< _T_ >::duplique override virtual
Implements Objet_U.
info()
template<typename _T_ > const Type_info * Joint_32_64< _T_ >::info static
get_info()
template<typename _T_ > const Type_info * Joint_32_64< _T_ >::get_info override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Frontiere_32_64< _SIZE_ >.
self_cast() [1/2]
template<typename _T_ > Joint_32_64< _T_ > & Joint_32_64< _T_ >::self_cast (Objet_U & r) static
self_cast() [2/2]
template<typename _T_ > const Joint_32_64< _T_ > & Joint_32_64< _T_ >::self_cast (const Objet_U & r) static
printOn()
template<typename _SIZE_ > Sortie & Joint_32_64< _SIZE_ >::printOn (Sortie & s) const override protected virtual
Ecrit le joint sur un flot de sortie.
On ecrit:
la frontiere
le PE voisin
l'epaisseur
les sommets
Reimplemented from Frontiere_32_64< _SIZE_ >.
readOn()
template<typename _SIZE_ > Entree & Joint_32_64< _SIZE_ >::readOn (Entree & s) override protected virtual
Lit un joint a partir d'un flot d'entree.
Reimplemented from Frontiere_32_64< _SIZE_ >.
References Process::exit(), and Process::je_suis_maitre().
affecte_PEvoisin()
template<typename _SIZE_ > void Joint_32_64< _SIZE_ >::affecte_PEvoisin (int num) inline
affecte_epaisseur()
template<typename _SIZE_ > void Joint_32_64< _SIZE_ >::affecte_epaisseur (int ep) inline
PEvoisin()
template<typename _SIZE_ > int Joint_32_64< _SIZE_ >::PEvoisin () const inline
Referenced by Maillage_FT_Disc::associer_domaine_dis_parcours(), Scatter::calculer_espace_distant(), Scatter::calculer_espace_distant_elements(), Scatter::calculer_nb_items_virtuels(), Scatter::calculer_renum_items_communs(), Joints_32_64< _SIZE_ >::comprimer(), Postraiter_domaine::ecrire(), Extraire_plan::interpreter_(), Joints_32_64< _SIZE_ >::joint_PE(), Scatter::read_domain_no_comm(), Marching_Cubes::remplir_renum_virt_loc(), Scatter::reordonner_faces_de_joint(), and Collision_Model_FT_base::set_LC_zones().
epaisseur()
template<typename _SIZE_ > int Joint_32_64< _SIZE_ >::epaisseur () const inline
Referenced by Assembleur_P_VEFPreP1B::assembler_mat(), and Scatter::calculer_espace_distant_elements().
dimensionner()
template<typename _SIZE_ > void Joint_32_64< _SIZE_ >::dimensionner (int i)
Referenced by Joints_32_64< _SIZE_ >::comprimer().
ajouter_faces()
template<typename _SIZE_ > void Joint_32_64< _SIZE_ >::ajouter_faces (const IntTab_t & sommets)
Ajoute des faces a la frontiere (au joint) voir Frontiere::ajouter_faces(const IntTab&)
Parameters
(IntTab& sommets) tableau contenant les numeros des sommets des face a ajouter
Referenced by Joints_32_64< _SIZE_ >::comprimer().
renum_virt_loc()
template<typename _SIZE_ > const IntTab_t & Joint_32_64< _SIZE_ >::renum_virt_loc () const inline
References Joint_32_64< _SIZE_ >::joint_item().
Referenced by Marching_Cubes::remplir_renum_virt_loc().
esp_dist_elems()
template<typename _SIZE_ > const ArrOfInt_t & Joint_32_64< _SIZE_ >::esp_dist_elems () const inline
References Joint_32_64< _SIZE_ >::joint_item().
esp_dist_sommets()
template<typename _SIZE_ > const ArrOfInt_t & Joint_32_64< _SIZE_ >::esp_dist_sommets () const inline
References Joint_32_64< _SIZE_ >::joint_item().
esp_dist_faces()
template<typename _SIZE_ > const ArrOfInt_t & Joint_32_64< _SIZE_ >::esp_dist_faces () const inline
References Joint_32_64< _SIZE_ >::joint_item().
set_joint_item()
template<typename _SIZE_ > Joint_32_64< _SIZE_ >::Joint_Items_t & Joint_32_64< _SIZE_ >::set_joint_item (JOINT_ITEM item)
Renvoie les informations de joint pour un type d'item geometrique donne, pour remplissage des structures.
Ces structures sont generalement remplies par la classe Scatter. Exceptions notables: Domaine_VDF et Domaine_VF pour la renumerotation des faces.
Referenced by Scatter::calculer_espace_distant(), Scatter::calculer_nb_items_virtuels(), Scatter::calculer_renum_items_communs(), DomaineCutter_32_64< _SIZE_ >::construire_sous_domaine(), Scatter::corriger_espace_distant_elements_perio(), Faces_builder::creer_faces_reeles(), Domaine_VF::renumeroter(), and Domaine_VDF::reordonner().
joint_item()
template<typename _SIZE_ > const Joint_32_64< _SIZE_ >::Joint_Items_t & Joint_32_64< _SIZE_ >::joint_item (JOINT_ITEM type) const
Renvoie les informations de joint pour le type demande.
Referenced by Scatter::calculer_espace_distant(), Scatter::calculer_espace_distant_elements(), Scatter::calculer_nb_items_virtuels(), Scatter::calculer_renum_items_communs(), Scatter::check_consistancy_remote_items(), Joint_32_64< _SIZE_ >::esp_dist_elems(), Joint_32_64< _SIZE_ >::esp_dist_faces(), Joint_32_64< _SIZE_ >::esp_dist_sommets(), Extraire_plan::interpreter_(), Domaine_VF::marquer_faces_double_contrib(), Scatter::read_domain_no_comm(), and Joint_32_64< _SIZE_ >::renum_virt_loc().
info_obj() [1/2]
const Type_info Joint_32_64< int >::info_obj ("Joint_32_64< _SIZE_ >" , Joint_32_64< int >::cree_instance , 1 , Joint_32_64bases< int >)
info_obj() [2/2]
const Type_info Joint_32_64< trustIdType >::info_obj ("Joint_32_64< _SIZE_ >" "_64" , Joint_32_64< trustIdType >::cree_instance , 1 , Joint_32_64bases< trustIdType >)
Member Data Documentation
info_obj
template<typename _SIZE_ > const Type_info Joint_32_64< _SIZE_ >::info_obj static