TrioCFD: Topologie_Maillage_FT Class Reference
Topologie_Maillage_FT Class Reference
#include <Topologie_Maillage_FT.h>
Public Member Functions
virtual int calculer_composantes_connexes_pour_suppression (const Domaine_VF &domaine_vf, const DoubleTab &indicatrice, IntVect &num_compo) const
const Type_info * get_info () const override
virtual void remailler_interface (const double temps, Maillage_FT_Disc &maillage, Champ_base &indicatrice, Remaillage_FT &algo_remaillage_local)
virtual double suppression_interfaces (const IntVect &num_compo, const ArrOfInt &flags_compo_a_supprimer, Maillage_FT_Disc &maillage, DoubleTab &indicatrice)
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
int test_collision_facettes (const Maillage_FT_Disc &maillage, ArrOfInt &liste_elements_collision) const
int test_intersection_facettes_2D (int fa70, int fa71, const Maillage_FT_Disc &maillage) const
int test_intersection_facettes_3D (int fa70, int fa71, const Maillage_FT_Disc &maillage) const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
See also
Transport_Interfaces_FT_Disc Maillage_FT_Disc
Constructor & Destructor Documentation
~Topologie_Maillage_FT()
Topologie_Maillage_FT::~Topologie_Maillage_FT ()
Topologie_Maillage_FT()
Topologie_Maillage_FT::Topologie_Maillage_FT ()
Member Function Documentation
cree_instance()
Objet_U * Topologie_Maillage_FT::cree_instance () static
taille_memoire()
unsigned Topologie_Maillage_FT::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Topologie_Maillage_FT::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Topologie_Maillage_FT::info () static
get_info()
const Type_info * Topologie_Maillage_FT::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
Topologie_Maillage_FT & Topologie_Maillage_FT::self_cast (Objet_U & r) static
self_cast() [2/2]
const Topologie_Maillage_FT & Topologie_Maillage_FT::self_cast (const Objet_U & r) static
printOn()
Sortie & Topologie_Maillage_FT::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
References Process::exit().
readOn()
Entree & Topologie_Maillage_FT::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
References active_, Param::ajouter(), Param::ajouter_flag(), Param::dictionnaire(), Process::exit(), Process::je_suis_maitre(), juric_local_, Param::lire_avec_accolades_depuis(), Objet_U_ptr::non_nul(), phase_continue_, Objet_U::que_suis_je(), remailleur_Collision_, Param::REQUIRED, and TRUST_Deriv< _CLASSE_ >::valeur().
remailler_interface()
void Topologie_Maillage_FT::remailler_interface (const double temps, Maillage_FT_Disc & maillage, Champ_base & indicatrice, Remaillage_FT & algo_remaillage_local) virtual
Remaillage de l'interface: - amelioration petites et grandes facettes,.
barycentrage,
gestion des coalescences-fragmentations.
References Remaillage_FT::a_lisser(), Remaillage_FT::a_remailler(), active_, Maillage_FT_Disc::ajouter_maillage(), Remaillage_FT::barycentrer_lisser_systematique(), calculer_composantes_connexes_pour_suppression(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Champ_base::domaine_dis_base(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), get_phase_continue(), Process::je_suis_maitre(), Process::Journal(), juric_local_, Maillage_FT_Disc::MINIMAL, Maillage_FT_Disc::parcourir_maillage(), Maillage_FT_Disc::recopie(), Remaillage_FT::remaillage_local_interface(), remailleur_Collision_, TRUSTArray< _TYPE_, _SIZE_ >::size_array(), suppression_interfaces(), test_collision_facettes(), Remailleur_Collision_FT_base::traite_RuptureCoalescenceInterfaces(), Remailleur_Collision_FT_base::traite_RuptureCoalescenceInterfaces_Conservatif(), TRUST_Deriv< _CLASSE_ >::valeur(), and Champ_Proto::valeurs().
Referenced by Transport_Interfaces_FT_Disc::remailler_interface().
calculer_composantes_connexes_pour_suppression()
int Topologie_Maillage_FT::calculer_composantes_connexes_pour_suppression (const Domaine_VF & domaine_vf, const DoubleTab & indicatrice, IntVect & num_compo) const virtual
Computes eulerian connex components of the phase indicator function "indicatrice" according to the get_phase_continue() property.
This method must be used to compute the input data for supprimer_interfaces.
For each eulerian mesh cell num_compo[i] = -1 for all mesh cells containing phase "get_phase_continue()" num_compo[i] = N with 0 <= N < Nmax, for all other mesh cells. N is a global connex component number. Two adjacent cells (by face) for which indicatrice[i] != get_phase_continue() will have the same N.
Parameters
(num_compo) output: resized, md_vector setup, filled with -1 <= num_compo[i] < Nmax, and virtual space updated. Valeur de retour: Returns Nmax, global number of connex components found.
References Domaine_32_64< _SIZE_ >::creer_tableau_elements(), Domaine_dis_base::domaine(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_VF::elem_faces(), Domaine_VF::face_voisins(), get_phase_continue(), and Domaine_32_64< _SIZE_ >::nb_elem().
Referenced by Transport_Interfaces_FT_Disc::calculer_composantes_connexes_pour_suppression(), remailler_interface(), and Transport_Interfaces_FT_Disc::test_suppression_interfaces_sous_domaine().
suppression_interfaces()
double Topologie_Maillage_FT::suppression_interfaces (const IntVect & num_compo, const ArrOfInt & flags_compo_a_supprimer, Maillage_FT_Disc & maillage, DoubleTab & indicatrice) virtual
Removes all interfaces contained in eulerian elements marked by the "flags_" array, and updates the "indicatrice" field by putting.
"get_phase_condinue()" in those elements. Virtual lagrangian elements are removed. "flags" must be of size "nb_elem" and must be built with one or more connex components (see calcul_composantes_connexes_eurleriennes). Return value: Integral of the "indicatrice" change (e.g. volume of phase changed, positive or negative)
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), get_phase_continue(), Maillage_FT_Disc::nb_facettes(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), and TRUSTVect< _TYPE_, _SIZE_ >::size().
Referenced by remailler_interface(), Transport_Interfaces_FT_Disc::suppression_interfaces(), and Transport_Interfaces_FT_Disc::test_suppression_interfaces_sous_domaine().
get_phase_continue()
int Topologie_Maillage_FT::get_phase_continue () const
References Process::exit(), and phase_continue_.
Referenced by calculer_composantes_connexes_pour_suppression(), remailler_interface(), suppression_interfaces(), and Transport_Interfaces_FT_Disc::test_suppression_interfaces_sous_domaine().
test_RuptureCoalescenceInterfaces()
int Topologie_Maillage_FT::test_RuptureCoalescenceInterfaces (const Maillage_FT_Disc & maillage) protected
test_collision_facettes()
int Topologie_Maillage_FT::test_collision_facettes (const Maillage_FT_Disc & maillage, ArrOfInt & liste_elements_collision) const protected
Teste s'il existe deux facettes du maillage qui se coupent (avec test_intersection_facettes_2D/3D).
On ne teste pas tous les couples possibles, seulement les couples de facettes qui coupent un meme element eulerien.
References TRUSTArray< _TYPE_, _SIZE_ >::append_array(), ArrOfBit_32_64< _SIZE_ >::clearbit(), Intersections_Elem_Facettes::data_intersection(), Objet_U::dimension, Intersections_Elem_Facettes::index_elem(), Intersections_Elem_Facettes_Data::index_element_suivant_, Intersections_Elem_Facettes::index_facette(), Intersections_Elem_Facettes_Data::index_facette_suivante_, Maillage_FT_Disc::intersections_elem_facettes(), Process::mp_max(), Maillage_FT_Disc::nb_facettes(), Intersections_Elem_Facettes_Data::numero_element_, Intersections_Elem_Facettes_Data::numero_facette_, TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), test_intersection_facettes_2D(), test_intersection_facettes_3D(), and ArrOfBit_32_64< _SIZE_ >::testsetbit().
Referenced by remailler_interface().
test_intersection_facettes_3D()
int Topologie_Maillage_FT::test_intersection_facettes_3D (int fa70, int fa71, const Maillage_FT_Disc & maillage) const protected
Teste si les facettes fa70 et fa71 se coupent.
Renvoie 0 si elles ne se coupent pas, -1 si elles ont deux sommets communs, -2 si elles ont trois sommets communs, -3 si le test preliminaire est positif et l'autre test non 1 si les facettes se coupent et n'ont aucun sommet commun -4 si les facettes ont un sommet commun. L'algorithme est identique a celui decrit dans http://www.cs.lth.se/home/Tomas_Akenine_Moller/pubs/tritri.pdf "a fast triangle-triangle intersection test (tomas moller)"
References Maillage_FT_Disc::facettes(), Maillage_FT_Disc::get_update_normale_facettes(), and Maillage_FT_Disc::sommets().
Referenced by test_collision_facettes().
test_intersection_facettes_2D()
int Topologie_Maillage_FT::test_intersection_facettes_2D (int fa70, int fa71, const Maillage_FT_Disc & maillage) const protected
Voir test_intersection_facettes_3D.
Algorithme B. Mathieu Renvoie 0 si les facettes ne se coupent pas -1 si 1 sommet commun -2 si 2 sommets communs 1 si les facettes se coupent
References Maillage_FT_Disc::facettes(), and Maillage_FT_Disc::sommets().
Referenced by test_collision_facettes().
Member Data Documentation
info_obj
const Type_info Topologie_Maillage_FT::info_obj static
active_
int Topologie_Maillage_FT::active_ protected
Referenced by readOn(), and remailler_interface().
remailleur_Collision_
TRUST_Deriv< Remailleur_Collision_FT_base > Topologie_Maillage_FT::remailleur_Collision_ protected
Referenced by readOn(), and remailler_interface().
Erreur_max_coordonnees_
double Topologie_Maillage_FT::Erreur_max_coordonnees_ protected
juric_local_
int Topologie_Maillage_FT::juric_local_ protected
Referenced by readOn(), and remailler_interface().
phase_continue_
int Topologie_Maillage_FT::phase_continue_ protected
Referenced by get_phase_continue(), and readOn().