TrioCFD: Parser_Eval Class Reference
Parser_Eval Class Reference
#include <Parser_Eval.h>
Detailed Description
La fonction peut dependre de l espace (x, y, z), du temps (t) et d'un champ parametre (val).
Member Function Documentation
fonction()
TRUST_Vector< Parser_U > & Parser_Eval::fonction () inline
References fonction_.
Referenced by Table::lire_f(), Table::lire_fxyzt(), and Champ_Don_Fonc_xyz::readOn().
parser() [1/2]
Parser_U & Parser_Eval::parser (int i) inline
References fonction_.
Referenced by eval_fct(), Champ_Fonc_Tabule_P0_VEF::mettre_a_jour(), and Table::val().
parser() [2/2]
Parser_U & Parser_Eval::parser (int i) const inline
References fonction_.
eval_fct() [1/8]
void Parser_Eval::eval_fct (const DoubleTab & positions, DoubleTab & val) const inline
Referenced by Champ_Don_Fonc_xyz::readOn(), and Table::valeurs().
eval_fct() [2/8]
void Parser_Eval::eval_fct (const DoubleTab & positions, const double t, DoubleTab & val) const inline
eval_fct() [3/8]
void Parser_Eval::eval_fct (const DoubleTab & positions, const double t, const DoubleTab & val_param, DoubleTab & val) const inline
eval_fct() [4/8]
void Parser_Eval::eval_fct (const DoubleTab & positions, DoubleVect & val, const int ncomp) const inline
eval_fct() [5/8]
void Parser_Eval::eval_fct (const DoubleTab & positions, const double t, DoubleVect & val, const int ncomp) const inline
eval_fct() [6/8]
void Parser_Eval::eval_fct (const DoubleVect & position, DoubleVect & val) const inline
eval_fct() [7/8]
void Parser_Eval::eval_fct (const DoubleVect & position, const double t, DoubleVect & val) const inline
eval_fct() [8/8]
void Parser_Eval::eval_fct (const DoubleTabs & variables, DoubleTab & val) const
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Parser_U::eval(), fonction_, TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), parser(), Parser_U::setVar(), and TRUST_Vector< _CLASSE_ >::size().
Member Data Documentation
fonction_
TRUST_Vector< Parser_U > Parser_Eval::fonction_ mutable protected
Referenced by eval_fct(), fonction(), and parser().