TrioCFD: Eval_Puiss_Th_DG_Elem Class Reference
Eval_Puiss_Th_DG_Elem Class Reference
#include <Eval_Puiss_Th_DG_Elem.h>
Member Function Documentation
mettre_a_jour()
void Eval_Puiss_Th_DG_Elem::mettre_a_jour () inline override virtual
Implements Evaluateur_Source.
associer_champs()
void Eval_Puiss_Th_DG_Elem::associer_champs (const Champ_Don_base & Q) inline
References la_puissance, puissance, TRUSTTab< _TYPE_, _SIZE_ >::ref(), and Champ_Don_base::valeurs().
Referenced by Terme_Puissance_Thermique_DG_Elem::associer_pb().
calculer_terme_source()
template<typename Type_Double > void Eval_Puiss_Th_DG_Elem::calculer_terme_source (const int e, Type_Double & S) const inline
References Quadrature_base::compute_integral_on_elem(), Champ_Elem_DG::eval_bfunc(), Domaine_DG::get_quadrature(), Evaluateur_Source::la_zcl, Evaluateur_Source::le_dom, Champ_Elem_DG::nb_bfunc(), Quadrature_base::nb_pts_integ(), Quadrature_base::nb_pts_integ_max(), puissance, and TRUST_Ref< _CLASSE_ >::valeur().
Member Data Documentation
la_puissance
TRUST_Ref< Champ_Don_base *> Eval_Puiss_Th_DG_Elem::la_puissance protected
Referenced by associer_champs().
puissance
DoubleTab Eval_Puiss_Th_DG_Elem::puissance protected
Referenced by associer_champs(), and calculer_terme_source().