TrioCFD: Interprete_geometrique_base_32_64< _SIZE_ > Class Template Reference
Interprete_geometrique_base_32_64< _SIZE_ > Class Template Reference abstract
#include <Interprete_geometrique_base.h>
Public Member Functions
const Type_info * get_info () const override
void mettre_a_jour_sous_domaine (Domaine_t &domaine, int_t &elem, int_t num_premier_elem, int_t nb_elem) const
Public Member Functions inherited from Interprete
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Interprete
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Interprete
static Objet_U & objet (const Nom &)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
template<typename _SIZE_>
class Interprete_geometrique_base_32_64< _SIZE_ >
See also
Classe abstraite dont les interpretes geometriques qui modifient un ou plusieurs domaines doivent deriver., Une reference est faite a chaque domaine. L'invalidation de l'octree apres modification du domaine, (par interpreter_(is)) est factorisee dans la methode interpreter(), Methodes abstraites:, int nombre_d_operateurs() const
Member Typedef Documentation
int_t
template<typename _SIZE_ > using Interprete_geometrique_base_32_64< _SIZE_ >::int_t = _SIZE_
Domaine_t
template<typename _SIZE_ > using Interprete_geometrique_base_32_64< _SIZE_ >::Domaine_t = Domaine_32_64<_SIZE_>
Constructor & Destructor Documentation
Interprete_geometrique_base_32_64()
template<typename _T_ > Interprete_geometrique_base_32_64< _T_ >::Interprete_geometrique_base_32_64
~Interprete_geometrique_base_32_64()
template<typename _T_ > Interprete_geometrique_base_32_64< _T_ >::~Interprete_geometrique_base_32_64 override
Member Function Documentation
info()
template<typename _T_ > const Type_info * Interprete_geometrique_base_32_64< _T_ >::info static
get_info()
template<typename _T_ > const Type_info * Interprete_geometrique_base_32_64< _T_ >::get_info override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
Reimplemented in ALE_Neumann_BC_for_grid_problem, Extraire_surface_ALE, Imposer_vit_bords_ALE, Solver_moving_mesh_ALE, Structural_dynamic_mesh_model, Beam_model, Projection_ALE_boundary, ConcatAnsys, Lire_Ideas, Lire_Tgrid, Mailler_32_64< _SIZE_ >, Modif_bord_to_raccord_32_64< _SIZE_ >, NettoieNoeuds_32_64< _SIZE_ >, OrienteFacesBord_32_64< _SIZE_ >, Orienter_Simplexes, Polyedriser_32_64< _SIZE_ >, Raffiner_anisotrope_32_64< _SIZE_ >, Raffiner_isotrope_parallele, Raffiner_Simplexes_32_64< _SIZE_ >, Rectify_Mesh, Redresser_hexaedres_vdf, Refine_Mesh, RegroupeBord_32_64< _SIZE_ >, Remove_elem, Remove_Invalid_Internal_Boundaries, Reordonner_32_64< _SIZE_ >, Reorienter_tetraedres_32_64< _SIZE_ >, Reorienter_triangles_32_64< _SIZE_ >, Rotation, SupprimeBord_32_64< _SIZE_ >, Tetraedriser, Tetraedriser_homogene, Tetraedriser_homogene_compact, Tetraedriser_homogene_fin, Tetraedriser_par_prisme, Transformer_32_64< _SIZE_ >, Triangulation_base, Trianguler, Trianguler_fin, Trianguler_H, TroisDto2D_32_64< _SIZE_ >, TroisDto2Daxi, Verifier_Qualite_Raffinements_32_64< _SIZE_ >, Verifier_Simplexes_32_64< _SIZE_ >, LireMED_32_64< _SIZE_ >, Read_MED_For_Testing_No_Verify_Option, Postraiter_domaine, and VerifierCoin.
self_cast() [1/2]
template<typename _T_ > Interprete_geometrique_base_32_64< _T_ > & Interprete_geometrique_base_32_64< _T_ >::self_cast (Objet_U & r) static
self_cast() [2/2]
template<typename _T_ > const Interprete_geometrique_base_32_64< _T_ > & Interprete_geometrique_base_32_64< _T_ >::self_cast (const Objet_U & r) static
printOn()
template<typename _SIZE_ > Sortie & Interprete_geometrique_base_32_64< _SIZE_ >::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
Reimplemented in ALE_Neumann_BC_for_grid_problem, Extraire_surface_ALE, Imposer_vit_bords_ALE, Solver_moving_mesh_ALE, Structural_dynamic_mesh_model, Beam_model, Projection_ALE_boundary, ConcatAnsys, Lire_Ideas, Lire_Tgrid, Mailler_32_64< _SIZE_ >, Modif_bord_to_raccord_32_64< _SIZE_ >, NettoieNoeuds_32_64< _SIZE_ >, OrienteFacesBord_32_64< _SIZE_ >, Orienter_Simplexes, Polyedriser_32_64< _SIZE_ >, Raffiner_anisotrope_32_64< _SIZE_ >, Raffiner_isotrope_parallele, Raffiner_Simplexes_32_64< _SIZE_ >, Rectify_Mesh, Redresser_hexaedres_vdf, Refine_Mesh, RegroupeBord_32_64< _SIZE_ >, Remove_elem, Remove_Invalid_Internal_Boundaries, Reordonner_32_64< _SIZE_ >, Reorienter_tetraedres_32_64< _SIZE_ >, Reorienter_triangles_32_64< _SIZE_ >, Rotation, SupprimeBord_32_64< _SIZE_ >, Tetraedriser, Tetraedriser_homogene, Tetraedriser_homogene_compact, Tetraedriser_homogene_fin, Tetraedriser_par_prisme, Transformer_32_64< _SIZE_ >, Triangulation_base, Trianguler, Trianguler_fin, Trianguler_H, TroisDto2D_32_64< _SIZE_ >, TroisDto2Daxi, Verifier_Qualite_Raffinements_32_64< _SIZE_ >, Verifier_Simplexes_32_64< _SIZE_ >, LireMED_32_64< _SIZE_ >, Read_MED_For_Testing_No_Verify_Option, Postraiter_domaine, and VerifierCoin.
Referenced by Orienter_Simplexes::printOn(), Verifier_Qualite_Raffinements_32_64< _SIZE_ >::printOn(), and Verifier_Simplexes_32_64< _SIZE_ >::printOn().
readOn()
template<typename _SIZE_ > Entree & Interprete_geometrique_base_32_64< _SIZE_ >::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
Reimplemented in ALE_Neumann_BC_for_grid_problem, Extraire_surface_ALE, Imposer_vit_bords_ALE, Solver_moving_mesh_ALE, Structural_dynamic_mesh_model, Beam_model, Projection_ALE_boundary, ConcatAnsys, Lire_Ideas, Lire_Tgrid, Mailler_32_64< _SIZE_ >, Modif_bord_to_raccord_32_64< _SIZE_ >, NettoieNoeuds_32_64< _SIZE_ >, OrienteFacesBord_32_64< _SIZE_ >, Orienter_Simplexes, Polyedriser_32_64< _SIZE_ >, Raffiner_anisotrope_32_64< _SIZE_ >, Raffiner_isotrope_parallele, Raffiner_Simplexes_32_64< _SIZE_ >, Rectify_Mesh, Redresser_hexaedres_vdf, Refine_Mesh, RegroupeBord_32_64< _SIZE_ >, Remove_elem, Remove_Invalid_Internal_Boundaries, Reordonner_32_64< _SIZE_ >, Reorienter_tetraedres_32_64< _SIZE_ >, Reorienter_triangles_32_64< _SIZE_ >, Rotation, SupprimeBord_32_64< _SIZE_ >, Tetraedriser, Tetraedriser_homogene, Tetraedriser_homogene_compact, Tetraedriser_homogene_fin, Tetraedriser_par_prisme, Transformer_32_64< _SIZE_ >, Triangulation_base, Trianguler, Trianguler_fin, Trianguler_H, TroisDto2D_32_64< _SIZE_ >, TroisDto2Daxi, Verifier_Qualite_Raffinements_32_64< _SIZE_ >, Verifier_Simplexes_32_64< _SIZE_ >, LireMED_32_64< _SIZE_ >, Read_MED_For_Testing_No_Verify_Option, Postraiter_domaine, and VerifierCoin.
Referenced by Orienter_Simplexes::readOn(), Verifier_Qualite_Raffinements_32_64< _SIZE_ >::readOn(), and Verifier_Simplexes_32_64< _SIZE_ >::readOn().
interpreter()
template<typename _SIZE_ > Entree & Interprete_geometrique_base_32_64< _SIZE_ >::interpreter (Entree & is) override virtual
Implements Interprete.
Reimplemented in Raffiner_isotrope_parallele.
References Bords_32_64< _SIZE_ >::associer_domaine(), Bords_Internes_32_64< _SIZE_ >::associer_domaine(), Groupes_Faces_32_64< _SIZE_ >::associer_domaine(), Joints_32_64< _SIZE_ >::associer_domaine(), Raccords_32_64< _SIZE_ >::associer_domaine(), Domaine_32_64< _SIZE_ >::bords_int(), Domaine_32_64< _SIZE_ >::faces_bord(), Domaine_32_64< _SIZE_ >::faces_joint(), Domaine_32_64< _SIZE_ >::faces_raccord(), Domaine_32_64< _SIZE_ >::fixer_premieres_faces_frontiere(), Domaine_32_64< _SIZE_ >::groupes_faces(), Process::imprimer_ram_totale(), Domaine_32_64< _SIZE_ >::invalide_octree(), Domaine_32_64< _SIZE_ >::set_mc_mesh_ready(), and Domaine_32_64< _SIZE_ >::type_elem().
Referenced by Extraire_plan::interpreter_().
associer_domaine() [1/3]
template<typename _SIZE_ > void Interprete_geometrique_base_32_64< _SIZE_ >::associer_domaine (Nom & nom_dom)
Referenced by ALE_Neumann_BC_for_grid_problem::interpreter_(), Extraire_surface_ALE::interpreter_(), Imposer_vit_bords_ALE::interpreter_(), Solver_moving_mesh_ALE::interpreter_(), Structural_dynamic_mesh_model::interpreter_(), Beam_model::interpreter_(), Projection_ALE_boundary::interpreter_(), ConcatAnsys::interpreter_(), Calculer_Moments::interpreter_(), Decouper_Bord_coincident::interpreter_(), Dilate::interpreter_(), Discretiser_domaine::interpreter_(), Distanceparoi::interpreter_(), Extraire_domaine::interpreter_(), Extraire_plan::interpreter_(), Extraire_surface::interpreter_(), ExtrudeBord::interpreter_(), ExtrudeParoi::interpreter_(), Extruder::interpreter_(), Extruder_en20::interpreter_(), Extruder_en3::interpreter_(), Imprimer_flux::interpreter_(), Imprimer_flux_sum::interpreter_(), Lire_Ideas::interpreter_(), Lire_Tgrid::interpreter_(), Redresser_hexaedres_vdf::interpreter_(), Remove_elem::interpreter_(), Rotation::interpreter_(), Triangulation_base::interpreter_(), Postraiter_domaine::interpreter_(), VerifierCoin::interpreter_(), Orienter_Simplexes::interpreter_(), Rectify_Mesh::interpreter_(), Refine_Mesh::interpreter_(), Remove_Invalid_Internal_Boundaries::interpreter_(), ScatterMED::lire_domaine(), Postraiter_domaine::lire_motcle_non_standard(), Champ_Fonc_MED::readOn(), and Pb_MED::readOn().
associer_domaine() [2/3]
template<typename _SIZE_ > void Interprete_geometrique_base_32_64< _SIZE_ >::associer_domaine (Entree & is)
References Objet_U::que_suis_je().
associer_domaine() [3/3]
template<typename _SIZE_ > void Interprete_geometrique_base_32_64< _SIZE_ >::associer_domaine (Domaine_t & dom)
domaine() [1/2]
template<typename _SIZE_ > Domaine_t & Interprete_geometrique_base_32_64< _SIZE_ >::domaine (int i = 0) inline
References Interprete_geometrique_base_32_64< _SIZE_ >::domains_.
Referenced by Rectify_Mesh::apply(), Refine_Mesh::apply(), Rectify_Mesh::apply_2D(), Refine_Mesh::apply_2D(), Rectify_Mesh::apply_3D(), Refine_Mesh::apply_3D(), Refine_Mesh::build_edges(), Refine_Mesh::build_new_boundary_faces_2D(), Refine_Mesh::build_new_boundary_faces_3D(), Refine_Mesh::build_new_cells_2D(), Refine_Mesh::build_new_cells_3D(), Refine_Mesh::build_new_connector_faces_2D(), Refine_Mesh::build_new_connector_faces_3D(), Refine_Mesh::build_new_frontier_faces_2D(), Refine_Mesh::build_new_frontier_faces_3D(), Refine_Mesh::build_new_internal_frontier_faces_2D(), Refine_Mesh::build_new_internal_frontier_faces_3D(), Refine_Mesh::build_new_nodes(), Refine_Mesh::build_new_sub_domaines_descriptions(), Rectify_Mesh::check_cell_enumeration_3D(), Rectify_Mesh::check_cell_orientation_2D(), Rectify_Mesh::check_cell_orientation_3D(), Rectify_Mesh::check_cell_type(), Refine_Mesh::check_cell_type(), Remove_elem::creer_faces(), Tetraedriser_homogene_compact::creer_sommet(), Tetraedriser_homogene_fin::creer_sommet(), Decouper_Bord_coincident::decouper_(), Postraiter_domaine::ecrire(), Decouper_multi::interpreter(), ALE_Neumann_BC_for_grid_problem::interpreter_(), Extraire_surface_ALE::interpreter_(), Imposer_vit_bords_ALE::interpreter_(), Solver_moving_mesh_ALE::interpreter_(), Structural_dynamic_mesh_model::interpreter_(), Beam_model::interpreter_(), Projection_ALE_boundary::interpreter_(), ConcatAnsys::interpreter_(), Calculer_Moments::interpreter_(), Decouper_Bord_coincident::interpreter_(), Dilate::interpreter_(), Discretiser_domaine::interpreter_(), Distanceparoi::interpreter_(), Extraire_domaine::interpreter_(), Extraire_plan::interpreter_(), Extraire_surface::interpreter_(), ExtrudeBord::interpreter_(), ExtrudeParoi::interpreter_(), Extruder::interpreter_(), Extruder_en20::interpreter_(), Extruder_en3::interpreter_(), Imprimer_flux::interpreter_(), Imprimer_flux_sum::interpreter_(), Lire_Ideas::interpreter_(), Lire_Tgrid::interpreter_(), Redresser_hexaedres_vdf::interpreter_(), Remove_elem::interpreter_(), Triangulation_base::interpreter_(), VerifierCoin::interpreter_(), Orienter_Simplexes::interpreter_(), Remove_Invalid_Internal_Boundaries::interpreter_(), Decouper_multi::lire_motcle_non_standard(), Remove_elem::remove_elem_(), Tetraedriser::trianguler(), Tetraedriser_homogene::trianguler(), Tetraedriser_homogene_compact::trianguler(), Tetraedriser_homogene_fin::trianguler(), Tetraedriser_par_prisme::trianguler(), Trianguler::trianguler(), Trianguler_H::trianguler(), Refine_Mesh::update_boundary_faces(), Refine_Mesh::update_cells(), Refine_Mesh::update_connector_faces(), Refine_Mesh::update_internal_frontier_faces(), Refine_Mesh::update_nodes(), Refine_Mesh::update_octree(), and Refine_Mesh::update_sub_domaines().
domaine() [2/2]
template<typename _SIZE_ > const Domaine_t & Interprete_geometrique_base_32_64< _SIZE_ >::domaine (int i = 0) const inline
References Interprete_geometrique_base_32_64< _SIZE_ >::domains_.
domaines()
template<typename _SIZE_ > TRUST_List< TRUST_Ref< Domaine_t * > > & Interprete_geometrique_base_32_64< _SIZE_ >::domaines () inline
References Interprete_geometrique_base_32_64< _SIZE_ >::domains_.
Referenced by Postraiter_domaine::interpreter_().
mettre_a_jour_sous_domaine()
template<typename _SIZE_ > void Interprete_geometrique_base_32_64< _SIZE_ >::mettre_a_jour_sous_domaine (Domaine_t & domaine, int_t & elem, int_t num_premier_elem, int_t nb_elem) const
Ajoute dans les sous-domaines les nouveaux elements
References Sous_Domaine_32_64< _SIZE_ >::add_elem(), Sous_Domaine_32_64< _SIZE_ >::le_nom(), Sous_Domaine_32_64< _SIZE_ >::nb_elem_tot(), Domaine_32_64< _SIZE_ >::nb_ss_domaines(), and Domaine_32_64< _SIZE_ >::ss_domaine().
Referenced by Decouper_Bord_coincident::decouper_(), ExtrudeParoi::extrude(), Extruder::extruder(), Extruder_en20::extruder(), Extruder_en3::extruder(), VerifierCoin::interpreter_(), Tetraedriser::trianguler(), Tetraedriser_homogene::trianguler(), Tetraedriser_homogene_compact::trianguler(), Tetraedriser_homogene_fin::trianguler(), Tetraedriser_par_prisme::trianguler(), Trianguler::trianguler(), Trianguler_fin::trianguler(), and Trianguler_H::trianguler().
interpreter_()
template<typename _SIZE_ > virtual Entree & Interprete_geometrique_base_32_64< _SIZE_ >::interpreter_ (Entree & is) protected pure virtual
Implemented in ALE_Neumann_BC_for_grid_problem, Extraire_surface_ALE, Imposer_vit_bords_ALE, Solver_moving_mesh_ALE, Structural_dynamic_mesh_model, Beam_model, Projection_ALE_boundary, ConcatAnsys, Calculer_Moments, Create_domain_from_sub_domain, DecoupeBord_32_64< _SIZE_ >, Decouper_Bord_coincident, Dilate, Discretiser_domaine, Distanceparoi, Extraire_domaine, Extraire_plan, Extraire_surface, ExtrudeBord, ExtrudeParoi, Extruder, Extruder_en20, Extruder_en3, Imprimer_flux, Imprimer_flux_sum, Lire_Ideas, Lire_Tgrid, Mailler_32_64< _SIZE_ >, Modif_bord_to_raccord_32_64< _SIZE_ >, NettoieNoeuds_32_64< _SIZE_ >, OrienteFacesBord_32_64< _SIZE_ >, Polyedriser_32_64< _SIZE_ >, Raffiner_anisotrope_32_64< _SIZE_ >, Redresser_hexaedres_vdf, RegroupeBord_32_64< _SIZE_ >, Remove_elem, Reordonner_32_64< _SIZE_ >, Reorienter_tetraedres_32_64< _SIZE_ >, Reorienter_triangles_32_64< _SIZE_ >, Rotation, SupprimeBord_32_64< _SIZE_ >, Transformer_32_64< _SIZE_ >, Triangulation_base, TroisDto2D_32_64< _SIZE_ >, LireMED_32_64< _SIZE_ >, Read_MED_For_Testing_No_Verify_Option, Postraiter_domaine, VerifierCoin, Corriger_frontiere_periodique_32_64< _SIZE_ >, Orienter_Simplexes, Raffiner_Simplexes_32_64< _SIZE_ >, Rectify_Mesh, Refine_Mesh, Remove_Invalid_Internal_Boundaries, Verifier_Qualite_Raffinements_32_64< _SIZE_ >, and Verifier_Simplexes_32_64< _SIZE_ >.
info_obj() [1/2]
const Type_info Interprete_geometrique_base_32_64< int >::info_obj ("Interprete_geometrique_base" , 1 , Interprete_geometrique_base_32_64bases< int >)
info_obj() [2/2]
const Type_info Interprete_geometrique_base_32_64< trustIdType >::info_obj ("Interprete_geometrique_base" "_64" , 1 , Interprete_geometrique_base_32_64bases< trustIdType >)
Member Data Documentation
info_obj
template<typename _SIZE_ > const Type_info Interprete_geometrique_base_32_64< _SIZE_ >::info_obj static
domains_
template<typename _SIZE_ > TRUST_List< TRUST_Ref< Domaine_t *> > Interprete_geometrique_base_32_64< _SIZE_ >::domains_ protected
Referenced by Interprete_geometrique_base_32_64< _SIZE_ >::domaine(), and Interprete_geometrique_base_32_64< _SIZE_ >::domaines().