TrioCFD: Modele_turbulence_scal_Prandtl Class Reference
Modele_turbulence_scal_Prandtl Class Reference
#include <Modele_turbulence_scal_Prandtl.h>
Public Member Functions
const Type_info * get_info () const override
void mettre_a_jour (double) override
Public Member Functions inherited from Modele_turbulence_scal_diffturb_base
void associer_viscosite_turbulente (const Champ_Fonc_base &)
void completer () override
const Type_info * get_info () const override
int reprendre (Entree &) override
Public Member Functions inherited from Modele_turbulence_scal_base
virtual void associer (const Domaine_dis_base &, const Domaine_Cl_dis_base &)
void associer_eqn (const Equation_base &)
const Type_info * get_info () const override
virtual void imprimer (Sortie &) const
int limpr_nusselt (double, double, double, double) const
int lire_motcle_non_standard (const Motcle &, Entree &) override
Turbulence_paroi_scal_base & loi_paroi ()
const Turbulence_paroi_scal_base & loi_paroi () const
int loi_paroi_non_nulle () const
virtual int preparer_calcul ()
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
virtual Champ_Fonc_base & calculer_diffusivite_turbulente ()
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
pour la diffusivite turbulente: alpha_turb = visco_turb / Prdt_turb;
See also
Mod_Turb_scal_diffuturb_base
Constructor & Destructor Documentation
Modele_turbulence_scal_Prandtl()
Modele_turbulence_scal_Prandtl::Modele_turbulence_scal_Prandtl ()
~Modele_turbulence_scal_Prandtl()
Modele_turbulence_scal_Prandtl::~Modele_turbulence_scal_Prandtl ()
Member Function Documentation
cree_instance()
Objet_U * Modele_turbulence_scal_Prandtl::cree_instance () static
taille_memoire()
unsigned Modele_turbulence_scal_Prandtl::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Modele_turbulence_scal_Prandtl::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Modele_turbulence_scal_Prandtl::info () static
get_info()
const Type_info * Modele_turbulence_scal_Prandtl::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Modele_turbulence_scal_diffturb_base.
self_cast() [1/2]
Modele_turbulence_scal_Prandtl & Modele_turbulence_scal_Prandtl::self_cast (Objet_U & r) static
self_cast() [2/2]
const Modele_turbulence_scal_Prandtl & Modele_turbulence_scal_Prandtl::self_cast (const Objet_U & r) static
printOn()
Sortie & Modele_turbulence_scal_Prandtl::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Modele_turbulence_scal_diffturb_base.
References Modele_turbulence_scal_diffturb_base::printOn().
readOn()
Entree & Modele_turbulence_scal_Prandtl::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Modele_turbulence_scal_diffturb_base.
References Parser_U::addVar(), definition_fonction_, fonction1_, fonction_, LePrdt_, LePrdt_fct_, Parser_U::parseString(), Modele_turbulence_scal_diffturb_base::readOn(), Parser_U::setNbVar(), and Parser_U::setString().
mettre_a_jour()
void Modele_turbulence_scal_Prandtl::mettre_a_jour (double) override virtual
Calcule la diffusivite turbulente et la loi de paroi.
Parameters
(double)
Implements Modele_turbulence_scal_base.
References calculer_diffusivite_turbulente(), Turbulence_paroi_scal_base::calculer_scal(), Milieu_base::capacite_calorifique(), Modele_turbulence_scal_base::conductivite_turbulente_, Modele_turbulence_scal_base::diffusivite_turbulente_, TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Modele_turbulence_scal_base::equation(), Modele_turbulence_scal_base::loi_paroi_non_nulle(), Modele_turbulence_scal_base::loipar_, Milieu_base::masse_volumique(), Probleme_base::milieu(), Modele_turbulence_scal_base::mon_equation_, Equation_base::probleme(), TRUSTVect< _TYPE_, _SIZE_ >::size(), Champ_Don_base::valeurs(), and Champ_Proto::valeurs().
set_param()
void Modele_turbulence_scal_Prandtl::set_param (Param & param) override virtual
Reimplemented from Modele_turbulence_scal_base.
References Param::ajouter(), definition_fonction_, LePrdt_fct_, and Modele_turbulence_scal_base::set_param().
calculer_diffusivite_turbulente()
Champ_Fonc_base & Modele_turbulence_scal_Prandtl::calculer_diffusivite_turbulente () protected virtual
Calcule la diffusivite turbulente.
diffusivite_turbulente = viscosite_turbulente / Prdt_turbulent
Returns
(Champ_Fonc_base&) la diffusivite turbulente nouvellement calculee
Exceptions
les champs diffusivite_turbulente et viscosite_turbulente doivent avoir le meme nombre de valeurs nodales
References Champ_base::changer_temps(), definition_fonction_, Milieu_base::diffusivite(), Modele_turbulence_scal_base::diffusivite_turbulente_, Modele_turbulence_scal_base::equation(), Parser_U::eval(), Process::exit(), fonction1_, fonction_, Milieu_base::has_diffusivite(), Modele_turbulence_scal_diffturb_base::la_viscosite_turbulente_, LePrdt_, LePrdt_fct_, Modele_turbulence_scal_base::mon_equation_, TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Parser_U::setVar(), TRUSTVect< _TYPE_, _SIZE_ >::size(), TRUST_Deriv< _CLASSE_ >::valeur(), and Champ_Don_base::valeurs().
Referenced by mettre_a_jour().
Member Data Documentation
info_obj
const Type_info Modele_turbulence_scal_Prandtl::info_obj static
LePrdt_
double Modele_turbulence_scal_Prandtl::LePrdt_ = 0.9 protected
Referenced by calculer_diffusivite_turbulente(), and readOn().
LePrdt_fct_
Nom Modele_turbulence_scal_Prandtl::LePrdt_fct_ protected
Referenced by calculer_diffusivite_turbulente(), readOn(), and set_param().
definition_fonction_
Nom Modele_turbulence_scal_Prandtl::definition_fonction_ protected
Referenced by calculer_diffusivite_turbulente(), readOn(), and set_param().
fonction_
Parser_U Modele_turbulence_scal_Prandtl::fonction_ protected
Referenced by calculer_diffusivite_turbulente(), and readOn().
fonction1_
Parser_U Modele_turbulence_scal_Prandtl::fonction1_ protected
Referenced by calculer_diffusivite_turbulente(), and readOn().