TrioCFD: Viscosite_turbulente_l_melange Class Reference
Viscosite_turbulente_l_melange Class Reference
#include <Viscosite_turbulente_l_melange.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Viscosite_turbulente_l_melange()
Viscosite_turbulente_l_melange::Viscosite_turbulente_l_melange ()
~Viscosite_turbulente_l_melange()
Viscosite_turbulente_l_melange::~Viscosite_turbulente_l_melange ()
Member Function Documentation
cree_instance()
Objet_U * Viscosite_turbulente_l_melange::cree_instance () static
taille_memoire()
unsigned Viscosite_turbulente_l_melange::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Viscosite_turbulente_l_melange::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Viscosite_turbulente_l_melange::info () static
get_info()
const Type_info * Viscosite_turbulente_l_melange::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Viscosite_turbulente_base.
self_cast() [1/2]
Viscosite_turbulente_l_melange & Viscosite_turbulente_l_melange::self_cast (Objet_U & r) static
self_cast() [2/2]
const Viscosite_turbulente_l_melange & Viscosite_turbulente_l_melange::self_cast (const Objet_U & r) static
printOn()
Sortie & Viscosite_turbulente_l_melange::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Viscosite_turbulente_base.
readOn()
Entree & Viscosite_turbulente_l_melange::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Viscosite_turbulente_base.
References Param::ajouter(), l_melange_, Param::lire_avec_accolades_depuis(), Correlation_base::pb_, Objet_U::que_suis_je(), and Param::REQUIRED.
eddy_viscosity()
void Viscosite_turbulente_l_melange::eddy_viscosity (DoubleTab & nu_t) const override virtual
Implements Viscosite_turbulente_base.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), l_melange_, and Correlation_base::pb_.
reynolds_stress()
void Viscosite_turbulente_l_melange::reynolds_stress (DoubleTab & R_ij) const override virtual
Implements Viscosite_turbulente_base.
References Process::abort().
k_over_eps()
void Viscosite_turbulente_l_melange::k_over_eps (DoubleTab & k_sur_eps) const override virtual
Implements Viscosite_turbulente_base.
References Process::abort().
eps()
void Viscosite_turbulente_l_melange::eps (DoubleTab & eps) const override virtual
Implements Viscosite_turbulente_base.
References Process::abort().
limiteur()
double Viscosite_turbulente_l_melange::limiteur () const inline
References limiter_.
gradu_required()
int Viscosite_turbulente_l_melange::gradu_required () const inline override virtual
Reimplemented from Viscosite_turbulente_base.
get_l_melange()
const double & Viscosite_turbulente_l_melange::get_l_melange () const inline
References l_melange_.
Member Data Documentation
info_obj
const Type_info Viscosite_turbulente_l_melange::info_obj static
l_melange_
double Viscosite_turbulente_l_melange::l_melange_ = -123. protected
Referenced by eddy_viscosity(), get_l_melange(), and readOn().
limiter_
double Viscosite_turbulente_l_melange::limiter_ = 0.01 protected
Referenced by limiteur().