TrioCFD: Ch_front_input_ALE Class Reference
Ch_front_input_ALE Class Reference
#include <Ch_front_input_ALE.h>
Public Member Functions
const Type_info * get_info () const override
void getTemplate (TrioField &afield) const override
int initialiser (double temps, const Champ_Inc_base &inco) override
void mettre_a_jour (double temps) override
const Type_info * get_info () const override
void getTemplate (TrioField &afield) const override
int initialiser (double temps, const Champ_Inc_base &inco) override
const Type_info * get_info () const override
void getTemplate (TrioField &afield) const override
int initialiser (double temps, const Champ_Inc_base &inco) override
const Type_info * get_info () const override
int initialiser (double temps, const Champ_Inc_base &inco) override
Public Member Functions inherited from Champ_front_var_instationnaire
int avancer (double temps) override
const Type_info * get_info () const override
int initialiser (double temps, const Champ_Inc_base &inco) override
int reculer (double temps) override
const DoubleTab & valeurs_au_temps (double temps) const override
DoubleTab & valeurs_au_temps (double temps) override
const Type_info * get_info () const override
int initialiser (double temps, const Champ_Inc_base &inco) override
Public Member Functions inherited from Champ_front_base
virtual void associer_fr_dis_base (const Frontiere_dis_base &)
virtual int avancer (double temps)
virtual void calculer_coeffs_echange (double temps)
virtual void fixer_nb_valeurs_temporelles (int nb_cases)
virtual Frontiere_dis_base & frontiere_dis ()
virtual const Frontiere_dis_base & frontiere_dis () const
const Type_info * get_info () const override
virtual int initialiser (double temps, const Champ_Inc_base &inco)
virtual void mettre_a_jour (double temps)
virtual int reculer (double temps)
virtual const DoubleTab & valeurs () const override
virtual DoubleTab & valeurs () override
virtual void valeurs_face (int, DoubleVect &) const
Public Member Functions inherited from Field_base
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
virtual void fixer_nb_comp (int i)
virtual const Nom & fixer_nom_compo (const Nom &)
virtual const Nom & fixer_nom_compo (int, const Nom &)
virtual const Noms & fixer_noms_compo (const Noms &)
virtual const Nom & fixer_unite (const Nom &)
virtual const Nom & fixer_unite (int i, const Nom &)
virtual const Noms & fixer_unites (const Noms &)
const Type_info * get_info () const override
const Nom & nom_compo (int) const
void nommer (const Nom &) override
const Nom & unite () const
const Nom & unite (int) const
const Noms & unites () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Champ_Proto
int lire_dimension (Entree &, const Nom &)
int lire_dimension (int dim, const Nom &le_nom_)
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Champ_Input_Proto
void read (Entree &is)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
Cette classe represente un champ accessible par setInputField
defini sur une frontiere avec une valeur par face. In case of ALE calculation.
See also
Champ_Input_Proto
Constructor & Destructor Documentation
~Ch_front_input_ALE()
Ch_front_input_ALE::~Ch_front_input_ALE ()
Ch_front_input_ALE()
Ch_front_input_ALE::Ch_front_input_ALE ()
Member Function Documentation
cree_instance()
Objet_U * Ch_front_input_ALE::cree_instance () static
taille_memoire()
unsigned Ch_front_input_ALE::taille_memoire () const override virtual
Reimplemented from Ch_front_input_P1.
duplique()
int Ch_front_input_ALE::duplique () const override virtual
Reimplemented from Ch_front_input_P1.
info()
const Type_info * Ch_front_input_ALE::info () static
get_info()
const Type_info * Ch_front_input_ALE::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Ch_front_input_P1.
self_cast() [1/2]
Ch_front_input_ALE & Ch_front_input_ALE::self_cast (Objet_U & r) static
self_cast() [2/2]
const Ch_front_input_ALE & Ch_front_input_ALE::self_cast (const Objet_U & r) static
printOn()
Sortie & Ch_front_input_ALE::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Ch_front_input_P1.
References Ch_front_input::printOn().
readOn()
Entree & Ch_front_input_ALE::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Ch_front_input_P1.
References Ch_front_input::readOn().
affecter_()
Champ_front_base & Ch_front_input_ALE::affecter_ (const Champ_front_base &) inline override virtual
Reimplemented from Ch_front_input.
getTemplate()
void Ch_front_input_ALE::getTemplate (TrioField & afield) const override virtual
Provides afield with a name, a time interval, components, and no field ownership.
The geometry includes all nodes of the domain and all faces of the boundary. WEC : optimization possible here
Reimplemented from Ch_front_input_P1.
References Ch_front_input::buildSommetsFaces(), and Ch_front_input_P1::getTemplate().
setValue()
void Ch_front_input_ALE::setValue (const TrioField & afield) override virtual
Uses the first value in afield as uniform value, regardless of geometry.
Reimplemented from Ch_front_input_P1.
References Ch_front_input_P1::les_valeurs_som, and Field_base::nb_comp().
initialiser()
int Ch_front_input_ALE::initialiser (double temps, const Champ_Inc_base & inco) override virtual
Initialisation en debut de calcul.
Imperativement cette methode ne doit pas utiliser de donnees externes a l'equation (couplage). Si mettre_a_jour le fait, alors initialiser ne doit pas appeler mettre_a_jour.
Returns
(0 en cas d'erreur, 1 sinon.)
Reimplemented from Ch_front_input_P1.
References alreadyInit_, Ch_front_input_P1::initialiser(), and mettre_a_jour().
Referenced by Domaine_ALE::initialiser().
get_vit_som_bord_ALE()
DoubleTab & Ch_front_input_ALE::get_vit_som_bord_ALE () inline
References vit_som_bord_ALE.
mettre_a_jour()
void Ch_front_input_ALE::mettre_a_jour (double temps) override virtual
NE FAIT RIEN, a surcharger.
Cette methode est appelee au debut de chaque pas de temps ou sous-pas-de-temps, elle peut eventuellement utiliser des donnees exterieures a l'equation. A charge a l'algorithme de s'assurer que ces donnees sont pertinentes... Calcule la valeur de la condition aux limites au temps demande.
Parameters
(double)
Reimplemented from Champ_front_base.
References TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Frontiere_32_64< _SIZE_ >::faces(), Champ_front_base::la_frontiere_dis, Field_base::nb_comp(), Frontiere_32_64< _SIZE_ >::nb_faces(), Faces_32_64< _SIZE_ >::nb_som_faces(), remplir_vit_som_bord_ALE(), Faces_32_64< _SIZE_ >::sommet(), Champ_front_var_instationnaire::valeurs_au_temps(), and vit_som_bord_ALE.
Referenced by initialiser().
remplir_vit_som_bord_ALE()
void Ch_front_input_ALE::remplir_vit_som_bord_ALE (double tps)
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Frontiere_32_64< _SIZE_ >::domaine(), Frontiere_32_64< _SIZE_ >::faces(), Champ_Input_Proto::initial_value_, Champ_front_base::la_frontiere_dis, Faces_32_64< _SIZE_ >::les_sommets(), Ch_front_input_P1::les_valeurs_som, Champ_Input_Proto::mon_pb, Field_base::nb_comp(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), and vit_som_bord_ALE.
Referenced by mettre_a_jour().
Member Data Documentation
info_obj
const Type_info Ch_front_input_ALE::info_obj static
vit_som_bord_ALE
DoubleTab Ch_front_input_ALE::vit_som_bord_ALE protected
Referenced by get_vit_som_bord_ALE(), mettre_a_jour(), and remplir_vit_som_bord_ALE().
alreadyInit_
bool Ch_front_input_ALE::alreadyInit_ protected
Referenced by initialiser().