TrioCFD: IJK_MonofluidVar Class Reference
IJK_MonofluidVar Class Reference
#include <MonofluidVar.h>
Detailed Description
Cette classe vise à simplifier l'appel aux propriétés constantes par phase dans la formulation monofluide.
Constructor & Destructor Documentation
IJK_MonofluidVar()
IJK_MonofluidVar::IJK_MonofluidVar () inline
~IJK_MonofluidVar()
IJK_MonofluidVar::~IJK_MonofluidVar () inline
Member Function Documentation
initialize()
void IJK_MonofluidVar::initialize (const double liqu_val, const double vap_val)
Referenced by Corrige_flux_FT_temperature_conv::initialize().
operator()() [1/3]
double IJK_MonofluidVar::operator() (const double indic_l) const
Referenced by operator()().
operator()() [2/3]
double IJK_MonofluidVar::operator() (const IJK_Field_double & indic_l, const int i, const int j, const int k) const
References operator()().
operator()() [3/3]
void IJK_MonofluidVar::operator() (const IJK_Field_double & indic_l, IJK_Field_double & res) const
References IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), and IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk().
harmo() [1/3]
double IJK_MonofluidVar::harmo (const double indic_l) const
Referenced by harmo().
harmo() [2/3]
double IJK_MonofluidVar::harmo (const IJK_Field_double & indic_l, const int i, const int j, const int k) const
References harmo().
harmo() [3/3]
void IJK_MonofluidVar::harmo (const IJK_Field_double & indic_l, IJK_Field_double & res) const
References IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), and IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk().
operator*=()
IJK_MonofluidVar & IJK_MonofluidVar::operator*= (const IJK_MonofluidVar & mono2)
References liqu(), and vap().
operator/=()
IJK_MonofluidVar & IJK_MonofluidVar::operator/= (const IJK_MonofluidVar & mono2)
References liqu(), and vap().
operator+=()
IJK_MonofluidVar & IJK_MonofluidVar::operator+= (const IJK_MonofluidVar & mono2)
References liqu(), and vap().
liqu()
double IJK_MonofluidVar::liqu () const
Referenced by operator*=(), operator+=(), and operator/=().
vap()
double IJK_MonofluidVar::vap () const
Referenced by operator*=(), operator+=(), and operator/=().