TrioCFD: Source_PDF_base Class Reference
Source_PDF_base Class Reference
#include <Source_PDF_base.h>
Public Member Functions
const Type_info * get_info () const override
void mettre_a_jour (double) override
void ouvrir_fichier (SFichier &, const Nom &, const int) const override
Public Member Functions inherited from Source_dep_inco_base
const Type_info * get_info () const override
Public Member Functions inherited from Source_base
virtual int a_pour_Champ_Fonc (const Motcle &mot, TRUST_Ref< Champ_base * > &ch_ref) const
virtual void associer_champ_rho (const Champ_base &champ_rho)
virtual void completer ()
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
virtual void resetTime (double t)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Source_dep_inco_base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
See also
Source_dep_inco_base, and Source_PDF
Constructor & Destructor Documentation
Source_PDF_base()
Source_PDF_base::Source_PDF_base ()
~Source_PDF_base()
Source_PDF_base::~Source_PDF_base () override
Member Function Documentation
info()
const Type_info * Source_PDF_base::info () static
get_info()
const Type_info * Source_PDF_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
Source_PDF_base & Source_PDF_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Source_PDF_base & Source_PDF_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Source_PDF_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
References Objet_U::que_suis_je().
readOn()
Entree & Source_PDF_base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
References Param::ajouter(), Param::ajouter_flag(), champ_aire_lu_, champ_rotation_lu_, PDF_model::echelle_relax_, echelle_relax_, MorEqn::equation(), Process::exit(), imm_wall_law_, interpolation_bool_, interpolation_lue_, Type_info::les_sous_types(), Param::lire_avec_accolades(), modele_lu_, Param::OPTIONAL, Objet_U::que_suis_je(), Param::REQUIRED, PDF_model::temps_relax_, temps_relax_, and transpose_rotation_.
Referenced by Source_PDF_EF::readOn().
getInterpolationBool()
const int & Source_PDF_base::getInterpolationBool () const inline
References interpolation_bool_.
associer_pb()
void Source_PDF_base::associer_pb (const Probleme_base & pb) override virtual
Implements Source_base.
References Process::abort().
ajouter()
DoubleTab & Source_PDF_base::ajouter (DoubleTab & secmem) const override virtual
Reimplemented from Source_base.
References ajouter_(), Source_base::ajouter_blocs(), Source_base::has_interface_blocs(), and variable_imposee_.
ajouter_() [1/2]
DoubleTab & Source_PDF_base::ajouter_ (const DoubleTab & variable, DoubleTab & resu) const override virtual
Implements Source_dep_inco_base.
References Process::abort().
Referenced by ajouter(), calculer(), and calculer_pdf().
ajouter_() [2/2]
DoubleTab & Source_PDF_base::ajouter_ (const DoubleTab & variable, DoubleTab & resu, const int i_traitement_special) const virtual
Reimplemented in Source_PDF_EF.
References Process::abort().
calculer() [1/2]
DoubleTab & Source_PDF_base::calculer (DoubleTab & resu) const override virtual
Reimplemented from Source_base.
References ajouter_(), MorEqn::equation(), Equation_base::inconnue(), and Champ_Inc_base::valeurs().
Referenced by Equation_IBM_proto::derivee_en_temps_inco_ibm_proto(), Source_PDF_EF::impr(), and Navier_Stokes_IBM::preparer_calcul().
calculer() [2/2]
DoubleTab & Source_PDF_base::calculer (DoubleTab & resu, const int i_traitement_special) const
References ajouter_(), MorEqn::equation(), Equation_base::inconnue(), and Champ_Inc_base::valeurs().
calculer_pdf()
DoubleTab & Source_PDF_base::calculer_pdf (DoubleTab & resu) const
References ajouter_(), and variable_imposee_.
Referenced by Equation_IBM_proto::derivee_en_temps_inco_ibm_proto(), and Navier_Stokes_IBM::preparer_calcul().
mettre_a_jour()
void Source_PDF_base::mettre_a_jour (double temps) override virtual
DOES NOTHING - to override in derived classes.
Mise a jour en temps du terme source.
Parameters
(double) le pas de temps de mise a jour
Reimplemented from Source_base.
contribuer_a_avec()
void Source_PDF_base::contribuer_a_avec (const DoubleTab & , Matrice_Morse & mat) const override virtual
contribution a la matrice implicite des termes sources par defaut pas de contribution
Reimplemented from Source_base.
References Process::abort().
fonct_coeff()
double Source_PDF_base::fonct_coeff (const double rho_m, const double aire, const double dt) const
References echelle_relax_, MorEqn::equation(), Equation_base::probleme(), Probleme_base::schema_temps(), Schema_Temps_base::temps_courant(), and temps_relax_.
Referenced by Source_PDF_EF::compute_coeff_elem(), Source_PDF_EF::compute_coeff_matrice(), and Source_PDF_EF::compute_pond().
diag_coeff_elem()
DoubleVect Source_PDF_base::diag_coeff_elem (ArrOfDouble & variable_elem, const DoubleTab & rotation, int num_elem) const virtual
Reimplemented in Source_PDF_EF.
References Process::abort().
compute_coeff_elem()
DoubleTab Source_PDF_base::compute_coeff_elem () const virtual
Reimplemented in Source_PDF_EF.
References Process::abort().
compute_coeff_matrice()
DoubleTab Source_PDF_base::compute_coeff_matrice () const virtual
Reimplemented in Source_PDF_EF.
References Process::abort().
Referenced by Navier_Stokes_IBM::initTimeStep(), and Equation_IBM_proto::preparer_calcul_ibm_proto().
multiply_coeff_volume()
void Source_PDF_base::multiply_coeff_volume (DoubleTab & coeff) const virtual
Reimplemented in Source_PDF_EF.
References Process::abort().
Referenced by Navier_Stokes_IBM::initTimeStep(), and Navier_Stokes_IBM::preparer_calcul().
correct_variable()
void Source_PDF_base::correct_variable (const DoubleTab & coeff_node, DoubleTab & variable) const virtual
Reimplemented in Source_PDF_EF.
References Process::abort().
Referenced by Equation_IBM_proto::modify_initial_variable_ibm_proto().
calculer_variable_imposee()
void Source_PDF_base::calculer_variable_imposee ()
References calculer_variable_imposee_elem_fluid(), calculer_variable_imposee_hybrid(), calculer_variable_imposee_mean_grad(), calculer_vitesse_imposee_power_law_tbl(), calculer_vitesse_imposee_power_law_tbl_u_star(), interpolation_bool_, interpolation_lue_, and Objet_U::que_suis_je().
Referenced by Equation_IBM_proto::initTimeStep_ibm_proto().
updateChampRho()
void Source_PDF_base::updateChampRho ()
References Champ_base::affecter(), champ_rho_, MorEqn::equation(), Source_base::get_champ(), and Objet_U::que_suis_je().
Referenced by Source_PDF_EF::associer_pb(), Navier_Stokes_IBM::initTimeStep(), and Equation_IBM_proto::preparer_calcul_ibm_proto().
get_modele()
const PDF_model & Source_PDF_base::get_modele () const inline
References modele_lu_.
Referenced by Equation_IBM_proto::derivee_en_temps_inco_ibm_proto().
impr()
int Source_PDF_base::impr (Sortie & os) const override virtual
Reimplemented from Source_base.
References Process::abort().
ouvrir_fichier()
void Source_PDF_base::ouvrir_fichier (SFichier & os, const Nom & type, const int flag = 1) const override virtual
Ouverture/creation d'un fichier d'impression d'un terme source A surcharger dans les classes derivees.
Exceptions
methode a surcharger
Reimplemented from Source_base.
References Source_base::description(), PDF_model::dim_variable_, Objet_U::dimension, MorEqn::equation(), Process::exit(), Probleme_U::le_nom(), modele_lu_, Source_base::out_, Sortie_Fichier_base::ouvrir(), Sortie_Fichier_base::precision(), Schema_Temps_base::precision_impr(), Equation_base::probleme(), Objet_U::que_suis_je(), Probleme_base::reprise_effectuee(), Probleme_base::schema_temps(), and Sortie_Fichier_base::setf().
Referenced by Source_PDF_EF::impr().
get_sec_mem_pdf()
const DoubleTab & Source_PDF_base::get_sec_mem_pdf () const inline
References sec_mem_pdf.
set_sec_mem_pdf()
void Source_PDF_base::set_sec_mem_pdf (DoubleTab & it) inline
References sec_mem_pdf.
Referenced by Equation_IBM_proto::derivee_en_temps_inco_ibm_proto().
get_matrice_pression_variable_bool_()
const bool & Source_PDF_base::get_matrice_pression_variable_bool_ () const inline
References matrice_pression_variable_bool_.
Referenced by Navier_Stokes_IBM::initTimeStep().
set_matrice_pression_variable_bool_()
void Source_PDF_base::set_matrice_pression_variable_bool_ (bool & flag) inline
References matrice_pression_variable_bool_.
correct_pressure()
void Source_PDF_base::correct_pressure (const DoubleTab & coeff_node, DoubleTab & pression, const DoubleTab & correction_en_pression) const virtual
Reimplemented in Source_PDF_EF.
References Process::abort().
correct_incr_pressure()
void Source_PDF_base::correct_incr_pressure (const DoubleTab & coeff_node, DoubleTab & correction_en_pression) const virtual
Reimplemented in Source_PDF_EF.
References Process::abort().
Referenced by Navier_Stokes_IBM::preparer_calcul().
compute_variable_imposee_projete()
void Source_PDF_base::compute_variable_imposee_projete (const DoubleTab & marqueur, const DoubleTab & points, double val, double eps) protected virtual
Reimplemented in Source_PDF_EF.
References Process::abort().
get_tuvw_local()
ArrOfDouble Source_PDF_base::get_tuvw_local () const protected
References Objet_U::dimension, PDF_model::eta_, and modele_lu_.
Referenced by Source_PDF_EF::diag_coeff_elem().
associer_domaines()
void Source_PDF_base::associer_domaines (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis) override protected virtual
Implements Source_base.
References Process::abort().
compute_indicateur_nodal_champ_aire()
void Source_PDF_base::compute_indicateur_nodal_champ_aire () protected virtual
Reimplemented in Source_PDF_EF.
References Process::abort().
rotate_imposed_velocity()
void Source_PDF_base::rotate_imposed_velocity (DoubleTab & vitesse_imposee) protected virtual
Reimplemented in Source_PDF_EF.
References Process::abort().
calculer_variable_imposee_elem_fluid()
void Source_PDF_base::calculer_variable_imposee_elem_fluid () protected virtual
Reimplemented in Source_PDF_EF.
References Process::abort().
Referenced by calculer_variable_imposee().
calculer_variable_imposee_hybrid()
void Source_PDF_base::calculer_variable_imposee_hybrid () protected virtual
Reimplemented in Source_PDF_EF.
References Process::abort().
Referenced by calculer_variable_imposee().
calculer_variable_imposee_mean_grad()
void Source_PDF_base::calculer_variable_imposee_mean_grad () protected virtual
Reimplemented in Source_PDF_EF.
References Process::abort().
Referenced by calculer_variable_imposee().
calculer_vitesse_imposee_power_law_tbl()
void Source_PDF_base::calculer_vitesse_imposee_power_law_tbl () protected virtual
Reimplemented in Source_PDF_EF.
References Process::abort().
Referenced by calculer_variable_imposee().
calculer_vitesse_imposee_power_law_tbl_u_star()
void Source_PDF_base::calculer_vitesse_imposee_power_law_tbl_u_star () protected virtual
Reimplemented in Source_PDF_EF.
References Process::abort().
Referenced by calculer_variable_imposee().
Member Data Documentation
info_obj
const Type_info Source_PDF_base::info_obj static
type_variable_imposee_
int Source_PDF_base::type_variable_imposee_ = -1 protected
Referenced by Source_PDF_EF::associer_pb().
champ_rotation_lu_
TRUST_Deriv< Champ_Don_base > Source_PDF_base::champ_rotation_lu_ protected
Referenced by Source_PDF_EF::associer_pb(), and readOn().
champ_rotation_
TRUST_Deriv< Champ_Don_base > Source_PDF_base::champ_rotation_ protected
Referenced by Source_PDF_EF::ajouter_(), Source_PDF_EF::associer_pb(), Source_PDF_EF::compute_coeff_elem(), Source_PDF_EF::compute_coeff_matrice(), Source_PDF_EF::contribuer_a_avec(), and Source_PDF_EF::rotate_imposed_velocity().
champ_aire_lu_
TRUST_Deriv< Champ_Don_base > Source_PDF_base::champ_aire_lu_ protected
Referenced by Source_PDF_EF::associer_pb(), and readOn().
champ_aire_
TRUST_Deriv< Champ_Don_base > Source_PDF_base::champ_aire_ protected
Referenced by Source_PDF_EF::ajouter_(), Source_PDF_EF::associer_pb(), Source_PDF_EF::compute_coeff_elem(), Source_PDF_EF::compute_coeff_matrice(), Source_PDF_EF::compute_indicateur_nodal_champ_aire(), Source_PDF_EF::contribuer_a_avec(), Source_PDF_EF::correct_incr_pressure(), Source_PDF_EF::correct_pressure(), and Source_PDF_EF::verif_ajouter_contrib().
champ_rho_
TRUST_Deriv< Champ_Don_base > Source_PDF_base::champ_rho_ protected
Referenced by Source_PDF_EF::ajouter_(), Source_PDF_EF::associer_pb(), Source_PDF_EF::compute_coeff_elem(), Source_PDF_EF::compute_coeff_matrice(), Source_PDF_EF::contribuer_a_avec(), and updateChampRho().
transpose_rotation_
bool Source_PDF_base::transpose_rotation_ = false protected
Referenced by Source_PDF_EF::associer_pb(), and readOn().
indicateur_nodal_champ_aire_
DoubleTab Source_PDF_base::indicateur_nodal_champ_aire_ protected
Referenced by Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl(), and Source_PDF_EF::compute_indicateur_nodal_champ_aire().
variable_imposee_
DoubleTab Source_PDF_base::variable_imposee_ protected
Referenced by ajouter(), Source_PDF_EF::associer_pb(), calculer_pdf(), Source_PDF_EF::calculer_variable_imposee_elem_fluid(), Source_PDF_EF::calculer_variable_imposee_hybrid(), Source_PDF_EF::calculer_variable_imposee_mean_grad(), Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl(), Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl_u_star(), and Source_PDF_EF::correct_variable().
modele_lu_
PDF_model Source_PDF_base::modele_lu_ protected
Referenced by Source_PDF_EF::ajouter_(), Source_PDF_EF::associer_pb(), Source_PDF_EF::calculer_variable_imposee_elem_fluid(), Source_PDF_EF::calculer_variable_imposee_hybrid(), Source_PDF_EF::calculer_variable_imposee_mean_grad(), Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl(), Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl_u_star(), Source_PDF_EF::compute_coeff_elem(), Source_PDF_EF::compute_coeff_matrice(), Source_PDF_EF::compute_variable_imposee_projete(), Source_PDF_EF::contribuer_a_avec(), get_modele(), get_tuvw_local(), Source_PDF_EF::impr(), ouvrir_fichier(), and readOn().
temps_relax_
double Source_PDF_base::temps_relax_ = -100. protected
Referenced by Source_PDF_EF::associer_pb(), fonct_coeff(), and readOn().
echelle_relax_
double Source_PDF_base::echelle_relax_ = -100. protected
Referenced by Source_PDF_EF::associer_pb(), fonct_coeff(), and readOn().
penalized_
bool Source_PDF_base::penalized_ = false protected
sec_mem_pdf
DoubleTab Source_PDF_base::sec_mem_pdf protected
Referenced by get_sec_mem_pdf(), Source_PDF_EF::impr(), and set_sec_mem_pdf().
matrice_pression_variable_bool_
bool Source_PDF_base::matrice_pression_variable_bool_ = false protected
Referenced by Source_PDF_EF::associer_pb(), get_matrice_pression_variable_bool_(), and set_matrice_pression_variable_bool_().
imm_wall_law_
bool Source_PDF_base::imm_wall_law_ = false protected
Referenced by Source_PDF_EF::creer_champ(), Source_PDF_EF::get_noms_champs_postraitables(), and readOn().
interpolation_lue_
TRUST_Deriv< Interpolation_IBM_base > Source_PDF_base::interpolation_lue_ protected
Referenced by Source_PDF_EF::associer_pb(), calculer_variable_imposee(), Source_PDF_EF::calculer_variable_imposee_elem_fluid(), Source_PDF_EF::calculer_variable_imposee_hybrid(), Source_PDF_EF::calculer_variable_imposee_mean_grad(), Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl(), Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl_u_star(), and readOn().
interpolation_bool_
int Source_PDF_base::interpolation_bool_ = 0 protected
Referenced by Source_PDF_EF::associer_pb(), calculer_variable_imposee(), getInterpolationBool(), and readOn().