TrioCFD: Operateur_Diff_base Class Reference
Operateur_Diff_base Class Reference abstract
#include <Operateur_Diff_base.h>
Public Member Functions
virtual void associer_diffusivite_pour_pas_de_temps (const Champ_base &)
const Type_info * get_info () const override
Public Member Functions inherited from Operateur_base
void associer_eqn (const Equation_base &)
virtual double calculer_dt_stab () const
virtual void completer ()
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual void mettre_a_jour (double temps)
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Protected Member Functions
virtual const Champ_base & diffusivite_pour_pas_de_temps () const
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
un terme de diffusion dans une equation. Le choix du terme depend de la modelisation laminaire ou turbulente de l'ecoulement, de la discretisation et du type du champ de diffusivite. Ces variantes donneront lieu a des classes filles de Operateur_Diff_base.
See also
Operateur_base Operateur_Diff, Classe abstraite, Methode abstraite, void associer_diffusivite(const Champ_Don_base&), const Champ_Don_base& diffusivite() const
Constructor & Destructor Documentation
Operateur_Diff_base()
Operateur_Diff_base::Operateur_Diff_base ()
~Operateur_Diff_base()
Operateur_Diff_base::~Operateur_Diff_base () override
Member Function Documentation
info()
const Type_info * Operateur_Diff_base::info () static
get_info()
const Type_info * Operateur_Diff_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Operateur_base.
Reimplemented in Op_Diff_K_Eps_Bas_Re_VDF_base, Op_Diff_K_Eps_Bas_Re_VDF_Elem_Axi, Op_Diff_K_Eps_Bas_Re_VDF_Elem, Op_Diff_K_Eps_Bas_Re_VDF_var_Elem, Op_Diff_K_Eps_VDF_base, Op_Diff_K_Eps_VDF_Elem, Op_Diff_K_Eps_VDF_Elem_Axi, Op_Diff_K_Eps_QC_VDF_Elem, Op_Diff_K_Eps_var_VDF_Elem, Op_Diff_K_Eps_var_QC_VDF_Elem, Op_Diff_K_VDF_Elem, Op_Diff_Eps_VDF_Elem, Op_Diff_K_Omega_VDF_base, Op_Diff_K_Omega_VDF_Elem, Op_Diff_K_Omega_var_VDF_Elem, Op_Diff_K_Eps_QC_VEF_Face, Op_Diff_K_Eps_VEF_base, Op_Diff_K_Eps_VEF_Face, Op_Diff_K_Omega_VEF_base, Op_Diff_K_Omega_VEF_Face, Op_Diff_PolyMAC_base, Op_Diff_PolyMAC_Gen_base, Op_Diff_PolyMAC_P0_base, Op_Diff_PolyMAC_P0P1NC_base, Op_Diff_PolyMAC_Elem, Op_Diff_Nonlinear_PolyMAC_Elem, Op_Dift_PolyMAC_Elem, Op_Dift_Nonlinear_PolyMAC_Elem, Op_Diff_PolyMAC_Face, Op_Diff_PolyMAC_P0_Elem, Op_Dift_PolyMAC_P0_Elem, Op_Diff_PolyMAC_P0_Face, Op_Diff_PolyMAC_P0P1NC_Elem, Op_Diff_PolyMAC_P0P1NC_Face, Op_Diff_Turbulent_PolyMAC_P0_Elem, Op_Diff_Turbulent_PolyMAC_P0_Face, Op_Diff_VDF_base, Op_Diff_VDF_Elem_base, Op_Diff_VDF_Face_Axi_base, Op_Diff_VDF_Face_base, Op_Dift_VDF_base, Op_Dift_VDF_Elem_base, Op_Dift_VDF_Face_Axi_base, Op_Dift_VDF_Face_base, Op_Diff_VDF_Elem, Op_Diff_VDF_Elem_Axi, Op_Diff_VDF_Elem_aniso, Op_Diff_VDF_Multi_inco_Elem, Op_Diff_VDF_Multi_inco_Multi_scalar_Elem, Op_Diff_VDF_Multi_inco_Elem_Axi, Op_Diff_VDF_Face, Op_Diff_VDF_Face_Axi, Op_Dift_Multiphase_VDF_Elem, Op_Dift_Multiphase_VDF_Face, Op_Dift_VDF_Elem, Op_Dift_VDF_Elem_Axi, Op_Dift_VDF_Multi_inco_Elem, Op_Dift_VDF_Multi_inco_Elem_Axi, Op_Dift_VDF_Face, Op_Dift_VDF_Face_Axi, Op_Diff_P1NC_barprim, Op_Diff_RotRot, Op_Diff_VEF_Anisotrope_Face, Op_Diff_VEF_base, Op_Diff_VEF_Face, Op_Diff_VEF_Face_Penalise, Op_Diff_VEF_Face_Q1, Op_Diff_VEF_Face_Stab, Op_Diff_VEFP1NCP1B_Face, Op_Dift_Stab_VEF_Face, Op_Dift_standard_VEF_Face, Op_Dift_VEF_base, Op_Dift_VEF_Face, Op_Dift_VEF_Face_Q1, and Op_Dift_VEF_P1NCP1B_Face.
self_cast() [1/2]
Operateur_Diff_base & Operateur_Diff_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Operateur_Diff_base & Operateur_Diff_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Operateur_Diff_base::printOn (Sortie & os) const override protected virtual
DOES NOTHING - to override in derived classes.
Imprime l'operateur sur un flot de sortie.
Parameters
(Sortie& os) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Operateur_base.
Reimplemented in Op_Diff_K_Eps_Bas_Re_VDF_base, Op_Diff_K_Eps_Bas_Re_VDF_Elem_Axi, Op_Diff_K_Eps_Bas_Re_VDF_Elem, Op_Diff_K_Eps_Bas_Re_VDF_var_Elem, Op_Diff_K_Eps_VDF_base, Op_Diff_K_Eps_VDF_Elem, Op_Diff_K_Eps_VDF_Elem_Axi, Op_Diff_K_Eps_QC_VDF_Elem, Op_Diff_K_Eps_var_VDF_Elem, Op_Diff_K_Eps_var_QC_VDF_Elem, Op_Diff_K_VDF_Elem, Op_Diff_Eps_VDF_Elem, Op_Diff_K_Omega_VDF_base, Op_Diff_K_Omega_VDF_Elem, Op_Diff_K_Omega_var_VDF_Elem, Op_Diff_K_Eps_QC_VEF_Face, Op_Diff_K_Eps_VEF_base, Op_Diff_K_Eps_VEF_Face, Op_Diff_K_Omega_VEF_base, Op_Diff_K_Omega_VEF_Face, Op_Diff_PolyMAC_base, Op_Diff_PolyMAC_Gen_base, Op_Diff_PolyMAC_P0_base, Op_Diff_PolyMAC_P0P1NC_base, Op_Diff_PolyMAC_Elem, Op_Diff_Nonlinear_PolyMAC_Elem, Op_Dift_PolyMAC_Elem, Op_Dift_Nonlinear_PolyMAC_Elem, Op_Diff_PolyMAC_Face, Op_Diff_PolyMAC_P0_Elem, Op_Dift_PolyMAC_P0_Elem, Op_Diff_PolyMAC_P0_Face, Op_Diff_PolyMAC_P0P1NC_Elem, Op_Diff_PolyMAC_P0P1NC_Face, Op_Diff_Turbulent_PolyMAC_P0_Elem, Op_Diff_Turbulent_PolyMAC_P0_Face, Op_Diff_VDF_base, Op_Diff_VDF_Elem_base, Op_Diff_VDF_Face_Axi_base, Op_Diff_VDF_Face_base, Op_Dift_VDF_base, Op_Dift_VDF_Elem_base, Op_Dift_VDF_Face_Axi_base, Op_Dift_VDF_Face_base, Op_Diff_VDF_Elem, Op_Diff_VDF_Elem_Axi, Op_Diff_VDF_Elem_aniso, Op_Diff_VDF_Multi_inco_Elem, Op_Diff_VDF_Multi_inco_Multi_scalar_Elem, Op_Diff_VDF_Multi_inco_Elem_Axi, Op_Diff_VDF_Face, Op_Diff_VDF_Face_Axi, Op_Dift_Multiphase_VDF_Elem, Op_Dift_Multiphase_VDF_Face, Op_Dift_VDF_Elem, Op_Dift_VDF_Elem_Axi, Op_Dift_VDF_Multi_inco_Elem, Op_Dift_VDF_Multi_inco_Elem_Axi, Op_Dift_VDF_Face, Op_Dift_VDF_Face_Axi, Op_Diff_P1NC_barprim, Op_Diff_RotRot, Op_Diff_VEF_Anisotrope_Face, Op_Diff_VEF_base, Op_Diff_VEF_Face, Op_Diff_VEF_Face_Penalise, Op_Diff_VEF_Face_Q1, Op_Diff_VEF_Face_Stab, Op_Diff_VEFP1NCP1B_Face, Op_Dift_Stab_VEF_Face, Op_Dift_standard_VEF_Face, Op_Dift_VEF_base, Op_Dift_VEF_Face, Op_Dift_VEF_Face_Q1, and Op_Dift_VEF_P1NCP1B_Face.
readOn()
Entree & Operateur_Diff_base::readOn (Entree & is) override protected virtual
DOES NOTHING - to override in derived classes.
Lit un operateur sur un flot d'entree.
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Operateur_base.
Reimplemented in Op_Diff_K_Eps_Bas_Re_VDF_base, Op_Diff_K_Eps_Bas_Re_VDF_Elem_Axi, Op_Diff_K_Eps_Bas_Re_VDF_Elem, Op_Diff_K_Eps_Bas_Re_VDF_var_Elem, Op_Diff_K_Eps_VDF_base, Op_Diff_K_Eps_VDF_Elem, Op_Diff_K_Eps_VDF_Elem_Axi, Op_Diff_K_Eps_QC_VDF_Elem, Op_Diff_K_Eps_var_VDF_Elem, Op_Diff_K_Eps_var_QC_VDF_Elem, Op_Diff_K_VDF_Elem, Op_Diff_Eps_VDF_Elem, Op_Diff_K_Omega_VDF_base, Op_Diff_K_Omega_VDF_Elem, Op_Diff_K_Omega_var_VDF_Elem, Op_Diff_K_Eps_QC_VEF_Face, Op_Diff_K_Eps_VEF_base, Op_Diff_K_Eps_VEF_Face, Op_Diff_K_Omega_VEF_base, Op_Diff_K_Omega_VEF_Face, Op_Diff_PolyMAC_base, Op_Diff_PolyMAC_Gen_base, Op_Diff_PolyMAC_P0_base, Op_Diff_PolyMAC_P0P1NC_base, Op_Diff_PolyMAC_Elem, Op_Diff_Nonlinear_PolyMAC_Elem, Op_Dift_PolyMAC_Elem, Op_Dift_Nonlinear_PolyMAC_Elem, Op_Diff_PolyMAC_Face, Op_Diff_PolyMAC_P0_Elem, Op_Dift_PolyMAC_P0_Elem, Op_Diff_PolyMAC_P0_Face, Op_Diff_PolyMAC_P0P1NC_Elem, Op_Diff_PolyMAC_P0P1NC_Face, Op_Diff_Turbulent_PolyMAC_P0_Elem, Op_Diff_Turbulent_PolyMAC_P0_Face, Op_Diff_VDF_base, Op_Diff_VDF_Elem_base, Op_Diff_VDF_Face_Axi_base, Op_Diff_VDF_Face_base, Op_Dift_VDF_base, Op_Dift_VDF_Elem_base, Op_Dift_VDF_Face_Axi_base, Op_Dift_VDF_Face_base, Op_Diff_VDF_Elem, Op_Diff_VDF_Elem_Axi, Op_Diff_VDF_Elem_aniso, Op_Diff_VDF_Multi_inco_Elem, Op_Diff_VDF_Multi_inco_Multi_scalar_Elem, Op_Diff_VDF_Multi_inco_Elem_Axi, Op_Diff_VDF_Face, Op_Diff_VDF_Face_Axi, Op_Dift_Multiphase_VDF_Elem, Op_Dift_Multiphase_VDF_Face, Op_Dift_VDF_Elem, Op_Dift_VDF_Elem_Axi, Op_Dift_VDF_Multi_inco_Elem, Op_Dift_VDF_Multi_inco_Elem_Axi, Op_Dift_VDF_Face, Op_Dift_VDF_Face_Axi, Op_Diff_P1NC_barprim, Op_Diff_RotRot, Op_Diff_VEF_Anisotrope_Face, Op_Diff_VEF_base, Op_Diff_VEF_Face, Op_Diff_VEF_Face_Penalise, Op_Diff_VEF_Face_Q1, Op_Diff_VEF_Face_Stab, Op_Diff_VEFP1NCP1B_Face, Op_Dift_Stab_VEF_Face, Op_Dift_standard_VEF_Face, Op_Dift_VEF_base, Op_Dift_VEF_Face, Op_Dift_VEF_Face_Q1, and Op_Dift_VEF_P1NCP1B_Face.
associer_diffusivite()
virtual void Operateur_Diff_base::associer_diffusivite (const Champ_base &) pure virtual
Implemented in Op_Diff_EF, Op_Dift_EF_Q1, Op_Diff_negligeable, Op_Diff_P1NC_barprim, Op_Diff_RotRot, Op_Diff_VEF_Anisotrope_Face, Op_Diff_VEF_Face, Op_Diff_VEF_Face_Q1, Op_Diff_K_Eps_Bas_Re_VDF_Elem_Axi, Op_Diff_K_Eps_Bas_Re_VDF_Elem, Op_Diff_K_Eps_Bas_Re_VDF_var_Elem, Op_Diff_VDF_Elem, Op_Diff_VDF_Elem_Axi, Op_Diff_VDF_Elem_aniso, Op_Diff_VDF_Multi_inco_Elem, Op_Diff_VDF_Multi_inco_Multi_scalar_Elem, Op_Diff_VDF_Multi_inco_Elem_Axi, Op_Diff_VDF_Face, Op_Dift_Multiphase_VDF_Elem, Op_Dift_Multiphase_VDF_Face, Op_Dift_VDF_Elem, Op_Dift_VDF_Elem_Axi, Op_Dift_VDF_Multi_inco_Elem, Op_Dift_VDF_Multi_inco_Elem_Axi, Op_Dift_VDF_Face, Op_Diff_K_Eps_VDF_base, Op_Diff_K_Omega_VDF_base, Op_Diff_DG_base, Op_Diff_PolyMAC_Gen_base, Op_Diff_VDF_Face_Axi, Op_Dift_VDF_Face_Axi, and Op_Dift_VEF_base.
Referenced by Operateur_Diff::typer().
associer_diffusivite_pour_pas_de_temps()
void Operateur_Diff_base::associer_diffusivite_pour_pas_de_temps (const Champ_base & diffu) virtual
Associe la vraie diffusivite en m^2/s (en QC par exemple, l'operateur est applique a rho*u, et on associe alors la viscosite dynamique a.
l'operateur au lieu de la viscosite dynamique. Dans ce cas, il faut associer la vraie diffusivite ici pour le calcul du pas de temps de stabilite.
References diffusivite_pour_pas_de_temps_, Process::je_suis_maitre(), Field_base::le_nom(), and Field_base::unite().
Referenced by Operateur_Diff::associer_diffusivite_pour_pas_de_temps().
diffusivite()
virtual const Champ_base & Operateur_Diff_base::diffusivite () const pure virtual
Implemented in Op_Diff_K_Eps_Bas_Re_VDF_Elem_Axi, Op_Diff_K_Eps_Bas_Re_VDF_Elem, Op_Diff_K_Eps_Bas_Re_VDF_var_Elem, Op_Diff_K_Eps_VDF_base, Op_Diff_K_Omega_VDF_base, Op_Diff_DG_base, Op_Diff_EF, Op_Dift_EF_Q1, Op_Diff_negligeable, Op_Diff_PolyMAC_Gen_base, Op_Diff_VDF_Elem, Op_Diff_VDF_Elem_Axi, Op_Diff_VDF_Elem_aniso, Op_Diff_VDF_Multi_inco_Elem, Op_Diff_VDF_Multi_inco_Multi_scalar_Elem, Op_Diff_VDF_Multi_inco_Elem_Axi, Op_Diff_VDF_Face, Op_Diff_VDF_Face_Axi, Op_Dift_Multiphase_VDF_Elem, Op_Dift_Multiphase_VDF_Face, Op_Dift_VDF_Elem, Op_Dift_VDF_Elem_Axi, Op_Dift_VDF_Multi_inco_Elem, Op_Dift_VDF_Multi_inco_Elem_Axi, Op_Dift_VDF_Face, Op_Dift_VDF_Face_Axi, Op_Diff_P1NC_barprim, Op_Diff_RotRot, Op_Diff_VEF_Anisotrope_Face, Op_Diff_VEF_Face, Op_Diff_VEF_Face_Q1, Op_Dift_VEF_base, and Op_Dift_VDF_Face_base.
Referenced by Op_Dift_EF_base::calculer_borne_locale(), Op_Diff_EF_base::calculer_dt_stab(), Op_Diff_VDF_Elem_base::calculer_dt_stab(), Op_Diff_VEF_base::calculer_dt_stab(), Op_Diff_VDF_base::calculer_dt_stab_(), Op_Diff_VEF_base::calculer_pour_post(), Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl(), Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl_u_star(), and Op_Diff_VEF_base::remplir_nu().
calculer_borne_locale()
virtual void Operateur_Diff_base::calculer_borne_locale (DoubleVect & , double , double) const inline virtual
Reimplemented in Op_Dift_EF_base, Op_Dift_VDF_Face_base, and Op_Dift_VEF_base.
Referenced by Modele_turbulence_hyd_base::limiter_viscosite_turbulente().
init_op_ext()
virtual void Operateur_Diff_base::init_op_ext () const inline virtual
Reimplemented in Op_Diff_PolyMAC_P0_Elem, Op_Diff_PolyMAC_P0P1NC_Elem, and Op_Diff_VDF_base.
References op_ext.
Referenced by Op_Diff_DG_Elem::dimensionner_blocs().
is_turb()
virtual bool Operateur_Diff_base::is_turb () const inline virtual
Reimplemented in Op_Diff_Turbulent_PolyMAC_P0_Elem, Op_Diff_Turbulent_PolyMAC_P0_Face, Op_Dift_Multiphase_VDF_Elem, and Op_Dift_Multiphase_VDF_Face.
Referenced by Op_Dift_VDF_base::ajoute_terme_pour_axi_turb().
correlation_viscosite_turbulente()
virtual const Correlation_base * Operateur_Diff_base::correlation_viscosite_turbulente () const inline virtual
Reimplemented in Op_Diff_Turbulent_PolyMAC_P0_Elem, Op_Diff_Turbulent_PolyMAC_P0_Face, Op_Dift_Multiphase_VDF_Elem, and Op_Dift_Multiphase_VDF_Face.
diffusivite_pour_pas_de_temps()
const Champ_base & Operateur_Diff_base::diffusivite_pour_pas_de_temps () const protected virtual
Renvoie le champ_don correspondant a la vraie diffusivite du milieu qui sert pour le calcul du pas de temps.
Si l'operateur s'applique a rho*v par exemple (cas du QC par exemple), la diffusivite associee est la viscosite dynamique et non la viscosite cinematique. Il faut utiliser la viscosite cinematique pour le calcul du pas de temps... La vraie diffusivite (en m^2/s) est determinee comme suit:
si diffusivite_pour_pas_de_temps_ a ete initialise => on l'utilise (systeme mis en place pour le front-tracking, car le milieu est invalide)
sinon on utilise diffusivite()
References diffusivite_pour_pas_de_temps_, TRUST_Ref< _CLASSE_ >::non_nul(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Op_Dift_VDF_Multi_inco_Elem::alpha_(), Op_Diff_DG_base::calculer_dt_stab(), Op_Diff_EF_base::calculer_dt_stab(), Op_Dift_EF_Q1::calculer_dt_stab(), Op_Diff_PolyMAC_base::calculer_dt_stab(), Op_Diff_PolyMAC_P0_Elem::calculer_dt_stab(), Op_Diff_PolyMAC_P0P1NC_Elem::calculer_dt_stab(), Op_Diff_VDF_Elem_base::calculer_dt_stab(), Op_Dift_Multiphase_VDF_Elem::calculer_dt_stab(), Op_Dift_Multiphase_VDF_Face::calculer_dt_stab(), Op_Diff_P1NC_barprim::calculer_dt_stab(), Op_Diff_VEF_base::calculer_dt_stab(), Op_Diff_VEF_Face_Q1::calculer_dt_stab(), Op_Dift_VEF_base::calculer_dt_stab(), Op_Dift_VDF_Face_base::calculer_dt_stab(), Op_Diff_VDF_base::calculer_dt_stab_(), Op_Diff_VEF_base::calculer_pour_post(), and Op_Dift_VEF_base::calculer_pour_post().
Member Data Documentation
info_obj
const Type_info Operateur_Diff_base::info_obj static
op_ext
std::vector<const Operateur_Diff_base *> Operateur_Diff_base::op_ext mutable
Referenced by Op_Diff_VDF_Elem_base::ajouter_blocs(), Op_Diff_PolyMAC_P0P1NC_Elem::ajouter_blocs_ext(), Op_Diff_PolyMAC_P0P1NC_Face::completer(), Op_Diff_VDF_Elem_base::dimensionner_blocs(), Op_Diff_DG_Elem::dimensionner_blocs(), Op_Diff_PolyMAC_P0P1NC_Elem::dimensionner_blocs_ext(), init_op_ext(), Op_Diff_PolyMAC_P0_Elem::init_op_ext(), Op_Diff_PolyMAC_P0P1NC_Elem::init_op_ext(), Op_Diff_VDF_base::init_op_ext(), and Op_Diff_PolyMAC_P0P1NC_base::update_aux().
diffusivite_pour_pas_de_temps_
TRUST_Ref< Champ_base *> Operateur_Diff_base::diffusivite_pour_pas_de_temps_ protected
Referenced by associer_diffusivite_pour_pas_de_temps(), and diffusivite_pour_pas_de_temps().