TrioCFD: Modele_turbulence_hyd_LES_VDF_base Class Reference
Modele_turbulence_hyd_LES_VDF_base Class Reference
#include <Modele_turbulence_hyd_LES_VDF_base.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Modele_turbulence_hyd_LES_base
const Type_info * get_info () const override
void imprimer (Sortie &is) const override
int preparer_calcul () override
int reprendre (Entree &is) override
const Type_info * get_info () const override
void imprimer (Sortie &) const override
int reprendre (Entree &is) override
Public Member Functions inherited from Modele_turbulence_hyd_base
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Type_info * get_info () const override
virtual void imprimer (Sortie &) const
void lire_distance_paroi ()
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual int preparer_calcul ()
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
maille en VDF
.SECTION voir aussi Modele_turbulence_hyd_LES_base
Constructor & Destructor Documentation
Modele_turbulence_hyd_LES_VDF_base()
Modele_turbulence_hyd_LES_VDF_base::Modele_turbulence_hyd_LES_VDF_base ()
~Modele_turbulence_hyd_LES_VDF_base()
Modele_turbulence_hyd_LES_VDF_base::~Modele_turbulence_hyd_LES_VDF_base () override
Member Function Documentation
info()
const Type_info * Modele_turbulence_hyd_LES_VDF_base::info () static
get_info()
const Type_info * Modele_turbulence_hyd_LES_VDF_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Modele_turbulence_hyd_LES_base.
Reimplemented in Modele_turbulence_hyd_LES_axi_VDF, Modele_turbulence_hyd_LES_DSGS_VDF, Modele_turbulence_hyd_LES_selectif_mod_VDF, Modele_turbulence_hyd_LES_selectif_VDF, Modele_turbulence_hyd_LES_SMAGO_DYN_VDF, Modele_turbulence_hyd_LES_VDF, and Modele_turbulence_hyd_LES_Wale_VDF.
self_cast() [1/2]
Modele_turbulence_hyd_LES_VDF_base & Modele_turbulence_hyd_LES_VDF_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Modele_turbulence_hyd_LES_VDF_base & Modele_turbulence_hyd_LES_VDF_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Modele_turbulence_hyd_LES_VDF_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Modele_turbulence_hyd_LES_base.
Reimplemented in Modele_turbulence_hyd_LES_axi_VDF, Modele_turbulence_hyd_LES_DSGS_VDF, Modele_turbulence_hyd_LES_selectif_mod_VDF, Modele_turbulence_hyd_LES_selectif_VDF, Modele_turbulence_hyd_LES_SMAGO_DYN_VDF, Modele_turbulence_hyd_LES_VDF, and Modele_turbulence_hyd_LES_Wale_VDF.
References Objet_U::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Modele_turbulence_hyd_LES_VDF_base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Modele_turbulence_hyd_LES_base.
Reimplemented in Modele_turbulence_hyd_LES_axi_VDF, Modele_turbulence_hyd_LES_DSGS_VDF, Modele_turbulence_hyd_LES_selectif_mod_VDF, Modele_turbulence_hyd_LES_selectif_VDF, Modele_turbulence_hyd_LES_SMAGO_DYN_VDF, Modele_turbulence_hyd_LES_VDF, and Modele_turbulence_hyd_LES_Wale_VDF.
References Modele_turbulence_hyd_LES_base::readOn().
Referenced by Modele_turbulence_hyd_LES_VDF::readOn(), Modele_turbulence_hyd_LES_Smago_VDF::readOn(), and Modele_turbulence_hyd_LES_Wale_VDF::readOn().
calculer_longueurs_caracteristiques()
void Modele_turbulence_hyd_LES_VDF_base::calculer_longueurs_caracteristiques () override virtual
Implements Modele_turbulence_hyd_LES_base.
Reimplemented in Modele_turbulence_hyd_LES_axi_VDF.
References Domaine_VDF::dim_elem(), Objet_U::dimension, Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), Process::exit(), Modele_turbulence_hyd_LES_base::l_, Modele_turbulence_hyd_0_eq_base::le_dom_VF_, Modele_turbulence_hyd_LES_base::methode_, Domaine_32_64< _SIZE_ >::nb_elem(), Domaine_VDF::orientation(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), and TRUST_Ref< _CLASSE_ >::valeur().
Member Data Documentation
info_obj
const Type_info Modele_turbulence_hyd_LES_VDF_base::info_obj static