TrioCFD: Modele_Jones_Launder_VDF Class Reference
Modele_Jones_Launder_VDF Class Reference
#include <Modele_Jones_Launder_VDF.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Modele_Fonc_Bas_Reynolds_Base
const Type_info * get_info () const override
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Modele_Fonc_Bas_Reynolds_Base
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Modele_Jones_Launder_VDF()
Modele_Jones_Launder_VDF::Modele_Jones_Launder_VDF ()
~Modele_Jones_Launder_VDF()
Modele_Jones_Launder_VDF::~Modele_Jones_Launder_VDF ()
Member Function Documentation
cree_instance()
Objet_U * Modele_Jones_Launder_VDF::cree_instance () static
taille_memoire()
unsigned Modele_Jones_Launder_VDF::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Modele_Launder_Sharma_VDF.
duplique()
int Modele_Jones_Launder_VDF::duplique () const override virtual
Implements Objet_U.
Reimplemented in Modele_Launder_Sharma_VDF.
info()
const Type_info * Modele_Jones_Launder_VDF::info () static
get_info()
const Type_info * Modele_Jones_Launder_VDF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
Reimplemented in Modele_Launder_Sharma_VDF.
self_cast() [1/2]
Modele_Jones_Launder_VDF & Modele_Jones_Launder_VDF::self_cast (Objet_U & r) static
self_cast() [2/2]
const Modele_Jones_Launder_VDF & Modele_Jones_Launder_VDF::self_cast (const Objet_U & r) static
printOn()
Sortie & Modele_Jones_Launder_VDF::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
Reimplemented in Modele_Launder_Sharma_VDF.
Referenced by Modele_F1F2FMU_unitaire_VDF::printOn(), and Modele_Launder_Sharma_VDF::printOn().
readOn()
Entree & Modele_Jones_Launder_VDF::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
Reimplemented in Modele_Launder_Sharma_VDF.
References Process::exit().
Referenced by Modele_F1F2FMU_unitaire_VDF::readOn(), and Modele_Launder_Sharma_VDF::readOn().
lire()
Entree & Modele_Jones_Launder_VDF::lire (const Motcle & , Entree & is)
associer()
void Modele_Jones_Launder_VDF::associer (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis) override virtual
Implements Modele_Fonc_Bas_Reynolds_Base.
Reimplemented in Modele_Launder_Sharma_VDF.
mettre_a_jour()
void Modele_Jones_Launder_VDF::mettre_a_jour (double temps) override virtual
Implements Modele_Fonc_Bas_Reynolds_Base.
Calcul_D()
DoubleTab & Modele_Jones_Launder_VDF::Calcul_D (DoubleTab & D, const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const DoubleTab & vitesse, const DoubleTab & K_eps_Bas_Re, const Champ_Don_base & ch_visco) const override virtual
Implements Modele_Fonc_Bas_Reynolds_Base.
References Domaine_VDF::dist_elem_period(), Domaine_VDF::dist_norm_bord(), MorEqn::equation(), Process::exit(), Domaine_VF::face_voisins(), Domaine_Cl_dis_base::les_conditions_limites(), Equation_base::milieu(), Domaine_dis_base::nb_elem_tot(), Domaine_VF::nb_faces(), Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), Domaine_VDF::orientation(), Milieu_base::porosite_face(), Domaine_VF::premiere_face_int(), Objet_U::que_suis_je(), TRUST_Deriv< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), Domaine_VF::volumes(), Domaine_VF::volumes_entrelaces(), and Domaine_VF::xp().
Calcul_E()
DoubleTab & Modele_Jones_Launder_VDF::Calcul_E (DoubleTab & E, const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const DoubleTab & vit, const DoubleTab & K_eps_Bas_Re, const Champ_Don_base & ch_visco, const DoubleTab & visco_turb) const override virtual
Implements Modele_Fonc_Bas_Reynolds_Base.
References calcul_derivees_premieres_croisees(), calcul_derivees_secondes_croisees(), Domaine_32_64< _SIZE_ >::creer_tableau_elements(), Domaine_VF::creer_tableau_faces(), Domaine_VDF::dim_elem(), Objet_U::dimension, Domaine_dis_base::domaine(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_VF::elem_faces(), Modele_Fonc_Bas_Reynolds_Base::eq_hydraulique, Domaine_VF::face_voisins(), Domaine_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Domaine_dis_base::nb_elem_tot(), Front_VF::nb_faces(), Domaine_VF::nb_faces_tot(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), Champ_Don_base::valeurs(), and Champ_Inc_base::valeurs().
Referenced by Calcul_E_BiK().
Calcul_F1()
DoubleTab & Modele_Jones_Launder_VDF::Calcul_F1 (DoubleTab & F1, const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const DoubleTab & P, const DoubleTab & K_eps_Bas_Re, const Champ_base & ch_visco) const override virtual
Implements Modele_Fonc_Bas_Reynolds_Base.
References Domaine_dis_base::nb_elem().
Calcul_F2()
DoubleTab & Modele_Jones_Launder_VDF::Calcul_F2 (DoubleTab & F2, DoubleTab & Deb, const Domaine_dis_base & domaine_dis, const DoubleTab & K_eps_Bas_Re, const Champ_base & ch_visco) const override virtual
Implements Modele_Fonc_Bas_Reynolds_Base.
References Domaine_dis_base::nb_elem(), and Champ_Proto::valeurs().
Calcul_Fmu()
DoubleTab & Modele_Jones_Launder_VDF::Calcul_Fmu (DoubleTab & Fmu, const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const DoubleTab & K_eps_Bas_Re, const Champ_Don_base & ch_visco) const override virtual
Implements Modele_Fonc_Bas_Reynolds_Base.
Reimplemented in Modele_Launder_Sharma_VDF.
References Domaine_dis_base::nb_elem(), and Champ_Don_base::valeurs().
Calcul_D_BiK()
DoubleTab & Modele_Jones_Launder_VDF::Calcul_D_BiK (DoubleTab & D, const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const DoubleTab & vitesse, const DoubleTab & K_Bas_Re, const DoubleTab & eps_Bas_Re, const Champ_Don_base & ch_visco) const override virtual
Implements Modele_Fonc_Bas_Reynolds_Base.
References Domaine_VDF::dist_elem_period(), Domaine_VDF::dist_norm_bord(), MorEqn::equation(), Process::exit(), Domaine_VF::face_voisins(), Domaine_Cl_dis_base::les_conditions_limites(), Equation_base::milieu(), Domaine_dis_base::nb_elem_tot(), Domaine_VF::nb_faces(), Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), Domaine_VDF::orientation(), Milieu_base::porosite_face(), Domaine_VF::premiere_face_int(), Objet_U::que_suis_je(), TRUST_Deriv< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), Domaine_VF::volumes(), Domaine_VF::volumes_entrelaces(), and Domaine_VF::xp().
Calcul_E_BiK()
DoubleTab & Modele_Jones_Launder_VDF::Calcul_E_BiK (DoubleTab & E, const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const DoubleTab & vit, const DoubleTab & K_Bas_Re, const DoubleTab & eps_Bas_Re, const Champ_Don_base & ch_visco, const DoubleTab & visco_turb) const override virtual
Implements Modele_Fonc_Bas_Reynolds_Base.
References Calcul_E().
Calcul_F1_BiK()
DoubleTab & Modele_Jones_Launder_VDF::Calcul_F1_BiK (DoubleTab & F1, const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const DoubleTab & P, const DoubleTab & K_Bas_Re, const DoubleTab & eps_Bas_Re, const Champ_base & ch_visco) const override virtual
Implements Modele_Fonc_Bas_Reynolds_Base.
References Domaine_dis_base::nb_elem().
Calcul_F2_BiK()
DoubleTab & Modele_Jones_Launder_VDF::Calcul_F2_BiK (DoubleTab & F2, DoubleTab & Deb, const Domaine_dis_base & domaine_dis, const DoubleTab & K_Bas_Re, const DoubleTab & eps_Bas_Re, const Champ_base & ch_visco) const override virtual
Implements Modele_Fonc_Bas_Reynolds_Base.
References Domaine_dis_base::nb_elem(), and Champ_Proto::valeurs().
Calcul_Fmu_BiK()
DoubleTab & Modele_Jones_Launder_VDF::Calcul_Fmu_BiK (DoubleTab & Fmu, const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const DoubleTab & K_Bas_Re, const DoubleTab & eps_Bas_Re, const Champ_Don_base & ch_visco) const override virtual
Implements Modele_Fonc_Bas_Reynolds_Base.
Reimplemented in Modele_Launder_Sharma_VDF.
References Domaine_dis_base::nb_elem(), and Champ_Don_base::valeurs().
calcul_derivees_premieres_croisees()
DoubleTab & Modele_Jones_Launder_VDF::calcul_derivees_premieres_croisees (DoubleTab & derivee_premiere, const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const DoubleTab & vit) const protected
References Objet_U::dimension, Domaine_VDF::dist_face(), Domaine_VDF::dist_norm_bord(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Modele_Fonc_Bas_Reynolds_Base::eq_hydraulique, Process::exit(), Domaine_VDF::face_normales(), Domaine_VDF::nb_aretes_bord(), Domaine_VDF::nb_aretes_coin(), Domaine_VDF::nb_aretes_internes(), Domaine_VDF::nb_aretes_mixtes(), Domaine_VDF::orientation(), TypeAreteCoinVDF::PERIO_PAROI, TypeAreteBordVDF::PERIO_PERIO, TypeAreteCoinVDF::PERIO_PERIO, Domaine_VDF::premiere_arete_bord(), Domaine_VDF::premiere_arete_coin(), Domaine_VDF::premiere_arete_interne(), Domaine_VDF::premiere_arete_mixte(), Domaine_VDF::Qdm(), Champ_base::temps(), Domaine_Cl_VDF::type_arete_bord(), Domaine_Cl_VDF::type_arete_coin(), and Champ_Inc_base::valeurs().
Referenced by Calcul_E().
calcul_derivees_secondes_croisees()
DoubleTab & Modele_Jones_Launder_VDF::calcul_derivees_secondes_croisees (DoubleTab & derivee_seconde, const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const DoubleTab & derivee_premiere) const protected
References Objet_U::dimension, Domaine_VDF::dist_face(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_VDF::nb_aretes_bord(), Domaine_VDF::nb_aretes_coin(), Domaine_VDF::nb_aretes_internes(), Domaine_VDF::nb_aretes_mixtes(), Domaine_VDF::orientation(), TypeAreteCoinVDF::PERIO_PAROI, TypeAreteBordVDF::PERIO_PERIO, TypeAreteCoinVDF::PERIO_PERIO, Domaine_VDF::premiere_arete_bord(), Domaine_VDF::premiere_arete_coin(), Domaine_VDF::premiere_arete_interne(), Domaine_VDF::premiere_arete_mixte(), Domaine_VDF::Qdm(), Domaine_Cl_VDF::type_arete_bord(), and Domaine_Cl_VDF::type_arete_coin().
Referenced by Calcul_E().
Member Data Documentation
info_obj
const Type_info Modele_Jones_Launder_VDF::info_obj static
le_dom_VDF
TRUST_Ref< Domaine_VDF *> Modele_Jones_Launder_VDF::le_dom_VDF protected
le_dom_Cl_VDF
TRUST_Ref< Domaine_Cl_VDF *> Modele_Jones_Launder_VDF::le_dom_Cl_VDF protected