TrioCFD: ParoiVEF_TBLE Class Reference
ParoiVEF_TBLE Class Reference
#include <ParoiVEF_TBLE.h>
Public Member Functions
const Type_info * get_info () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
const Type_info * get_info () const override
Public Member Functions inherited from Turbulence_paroi_base
void associer_modele (const Modele_turbulence_hyd_base &)
int calculer_hyd (Champ_Fonc_base &, Champ_Fonc_base &)
int calculer_hyd (Champ_Inc_base &)
const Type_info * get_info () const override
virtual void imprimer_premiere_ligne_ustar (int, const TRUST_List< Nom > &, const Nom &) const
virtual void imprimer_ustar_mean_only (Sortie &, int, const TRUST_List< Nom > &, const Nom &) const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Paroi_TBLE_QDM
void calculer_stat (int indice_post, int indice_maillage, double Fx, double Fy, double Fz, double u, double v, double w, double dt)
void imprimer_stat (Sortie &, double) const
int init_lois_paroi (const Domaine_VF &, const Domaine_Cl_dis_base &)
int reprendre (Entree &, const Domaine_dis_base &, const Domaine_Cl_dis_base &, double tps)
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Turbulence_paroi_base
static void typer_lire_turbulence_paroi (TRUST_Deriv< Turbulence_paroi_base > &, const Modele_turbulence_hyd_base &, Entree &)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
.SECTION voir aussi Turbulence_paroi_base
Constructor & Destructor Documentation
~ParoiVEF_TBLE()
ParoiVEF_TBLE::~ParoiVEF_TBLE ()
ParoiVEF_TBLE()
ParoiVEF_TBLE::ParoiVEF_TBLE ()
Member Function Documentation
cree_instance()
Objet_U * ParoiVEF_TBLE::cree_instance () static
taille_memoire()
unsigned ParoiVEF_TBLE::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int ParoiVEF_TBLE::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * ParoiVEF_TBLE::info () static
get_info()
const Type_info * ParoiVEF_TBLE::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Paroi_hyd_base_VEF.
self_cast() [1/2]
ParoiVEF_TBLE & ParoiVEF_TBLE::self_cast (Objet_U & r) static
self_cast() [2/2]
const ParoiVEF_TBLE & ParoiVEF_TBLE::self_cast (const Objet_U & r) static
printOn()
Sortie & ParoiVEF_TBLE::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Paroi_hyd_base_VEF.
References Objet_U::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & ParoiVEF_TBLE::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Paroi_hyd_base_VEF.
References Param::lire_avec_accolades_depuis(), Objet_U::que_suis_je(), and set_param().
set_param()
void ParoiVEF_TBLE::set_param (Param & param) override virtual
Reimplemented from Turbulence_paroi_base.
References Param::ajouter(), Param::ajouter_condition(), Param::ajouter_non_std(), Paroi_log_QDM::set_param(), Paroi_TBLE_QDM::set_param(), and Turbulence_paroi_base::set_param().
Referenced by readOn().
lire_motcle_non_standard()
int ParoiVEF_TBLE::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Objet_U.
References Paroi_TBLE_QDM::lire_motcle_non_standard().
init_lois_paroi()
int ParoiVEF_TBLE::init_lois_paroi () override virtual
Implements Turbulence_paroi_base.
References Paroi_TBLE_QDM::beta_t, Milieu_base::beta_t(), Objet_U::dimension, Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), Paroi_TBLE_QDM::epsilon, Paroi_TBLE_QDM::eq_vit, Process::exit(), Paroi_TBLE_QDM::fac, Domaine_VF::face_normales(), Domaine_VF::face_voisins(), Eq_couch_lim::get_diffu(), Equation_base::inconnue(), Paroi_TBLE_QDM::init_lois_paroi(), Paroi_hyd_base_VEF::init_lois_paroi_(), Eq_couch_lim::initialiser(), Process::je_suis_maitre(), Paroi_log_QDM::Kappa_, Turbulence_paroi_base::le_dom_Cl_dis_, Turbulence_paroi_base::le_dom_dis_, Paroi_TBLE_QDM::max_it, Equation_base::milieu(), Turbulence_paroi_base::mon_modele_turb_hyd, Paroi_TBLE_QDM::nb_comp, Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), Paroi_TBLE_QDM::nb_pts, Paroi_TBLE_QDM::nu_t_dyn, Front_VF::num_face(), Paroi_TBLE_QDM::reprise_ok, TRUSTTab< _TYPE_, _SIZE_ >::resize(), Terme_Boussinesq_base::Scalaire0(), Eq_couch_lim::set_u_y0(), Eq_couch_lim::set_u_yn(), Eq_couch_lim::set_Uinit(), Eq_couch_lim::set_Uinit_lin(), Eq_couch_lim::set_y0(), Eq_couch_lim::set_yn(), Diffu_totale_base::setKappa(), TRUST_List< _CLASSE_ >::size(), Paroi_TBLE_QDM::source_boussinesq, Equation_base::sources(), Paroi_TBLE_QDM::T0, TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), Champ_Inc_base::valeurs(), and Paroi_TBLE_QDM::valeurs_reprises.
calculer_hyd() [1/3]
int ParoiVEF_TBLE::calculer_hyd (DoubleTab & tab_k_eps) override virtual
Implements Turbulence_paroi_base.
References calculer_hyd().
Referenced by calculer_hyd().
calculer_hyd_BiK()
int ParoiVEF_TBLE::calculer_hyd_BiK (DoubleTab & tab_k, DoubleTab & tab_eps) override virtual
Implements Turbulence_paroi_base.
References Eq_couch_lim::aller_au_temps(), Eq_couch_lim::aller_jusqu_a_convergence(), Paroi_TBLE_QDM::beta_t, Operateur_Grad::calculer(), Turbulence_paroi_base::Cisaillement_paroi_, Objet_U::dimension, Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), Paroi_TBLE_QDM::eps_statio, Paroi_TBLE_QDM::eq_vit, Paroi_TBLE_QDM_Scal::est_initialise(), Process::exit(), Paroi_hyd_base_VEF::face_keps_imposee_, Domaine_VF::face_normales(), Domaine_VF::face_voisins(), Paroi_hyd_base_VEF::flag_face_keps_imposee_, Eq_couch_lim::get_cis(), Paroi_TBLE_QDM_Scal::get_eq_couche_lim_T(), Eq_couch_lim::get_it(), Equation_base::get_modele(), Eq_couch_lim::get_Unp1(), Milieu_base::gravite(), Equation_base::inconnue(), Process::je_suis_maitre(), Turbulence_paroi_base::le_dom_Cl_dis_, Turbulence_paroi_base::le_dom_dis_, TRUSTVect< _TYPE_, _SIZE_ >::local_min_vect(), Modele_turbulence_scal_base::loi_paroi(), Paroi_TBLE_QDM::max_it, Paroi_TBLE_QDM::max_it_statio, Equation_base::milieu(), Turbulence_paroi_base::mon_modele_turb_hyd, Paroi_TBLE_QDM::nb_comp, Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), Paroi_TBLE_QDM::nb_pts, Front_VF::num_face(), Navier_Stokes_std::operateur_gradient(), Paroi_TBLE_QDM::oui_stats, Schema_Temps_base::pas_de_temps(), Schema_Temps_base::pas_temps_min(), Navier_Stokes_std::pression(), Equation_base::schema_temps(), Eq_couch_lim::set_dt(), Eq_couch_lim::set_F(), Eq_couch_lim::set_u_y0(), Eq_couch_lim::set_u_yn(), Paroi_TBLE_QDM::source_boussinesq, Paroi_TBLE_QDM::statio, Paroi_TBLE_QDM::T0, Turbulence_paroi_base::tab_d_plus(), Turbulence_paroi_base::tab_d_plus_, Turbulence_paroi_base::tab_u_star(), Turbulence_paroi_base::tab_u_star_, Schema_Temps_base::temps_courant(), Paroi_TBLE_QDM::tps_start_stat_nu_t_dyn, TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), TRUST_Ref_Objet_U::valeur(), Champ_Don_base::valeurs(), Champ_Inc_base::valeurs(), Paroi_TBLE_QDM::visco_turb_moy, Fluide_base::viscosite_cinematique(), and Domaine_VF::volumes_entrelaces().
calculer_hyd() [2/3]
int ParoiVEF_TBLE::calculer_hyd (DoubleTab & nu_t, DoubleTab & tab_k) override virtual
Implements Turbulence_paroi_base.
References calculer_hyd().
calculer_hyd() [3/3]
int ParoiVEF_TBLE::calculer_hyd (DoubleTab & tab1, int isKeps, DoubleTab & tab2)
References Eq_couch_lim::aller_au_temps(), Eq_couch_lim::aller_jusqu_a_convergence(), Paroi_TBLE_QDM::beta_t, Operateur_Grad::calculer(), Turbulence_paroi_base::Cisaillement_paroi_, Objet_U::dimension, Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), Paroi_TBLE_QDM::eps_statio, Paroi_TBLE_QDM::eq_vit, Paroi_TBLE_QDM_Scal::est_initialise(), Process::exit(), Paroi_hyd_base_VEF::face_keps_imposee_, Domaine_VF::face_normales(), Domaine_VF::face_voisins(), Paroi_hyd_base_VEF::flag_face_keps_imposee_, Eq_couch_lim::get_cis(), Paroi_TBLE_QDM_Scal::get_eq_couche_lim_T(), Eq_couch_lim::get_it(), Equation_base::get_modele(), Eq_couch_lim::get_nu_t_yn(), Eq_couch_lim::get_Unp1(), Milieu_base::gravite(), Equation_base::inconnue(), Process::je_suis_maitre(), Turbulence_paroi_base::le_dom_Cl_dis_, Turbulence_paroi_base::le_dom_dis_, TRUSTVect< _TYPE_, _SIZE_ >::local_min_vect(), Modele_turbulence_scal_base::loi_paroi(), Paroi_TBLE_QDM::max_it, Paroi_TBLE_QDM::max_it_statio, Equation_base::milieu(), Turbulence_paroi_base::mon_modele_turb_hyd, Paroi_TBLE_QDM::nb_comp, Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), Paroi_TBLE_QDM::nb_pts, Paroi_TBLE_QDM::nu_t_dyn, Front_VF::num_face(), Navier_Stokes_std::operateur_gradient(), Paroi_TBLE_QDM::oui_stats, Schema_Temps_base::pas_de_temps(), Schema_Temps_base::pas_temps_min(), Navier_Stokes_std::pression(), Equation_base::schema_temps(), Eq_couch_lim::set_dt(), Eq_couch_lim::set_F(), Eq_couch_lim::set_nu_t_yn(), Eq_couch_lim::set_u_y0(), Eq_couch_lim::set_u_yn(), Paroi_TBLE_QDM::source_boussinesq, Paroi_TBLE_QDM::statio, Paroi_TBLE_QDM::T0, Turbulence_paroi_base::tab_d_plus(), Turbulence_paroi_base::tab_d_plus_, Turbulence_paroi_base::tab_u_star(), Turbulence_paroi_base::tab_u_star_, Schema_Temps_base::temps_courant(), Paroi_TBLE_QDM::tps_nu_t_dyn, Paroi_TBLE_QDM::tps_start_stat_nu_t_dyn, TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), TRUST_Ref_Objet_U::valeur(), Champ_Don_base::valeurs(), Champ_Inc_base::valeurs(), Paroi_TBLE_QDM::visco_turb_moy, Fluide_base::viscosite_cinematique(), and Domaine_VF::volumes_entrelaces().
imprimer_ustar()
void ParoiVEF_TBLE::imprimer_ustar (Sortie & os) const override virtual
Reimplemented from Turbulence_paroi_base.
References Objet_U::dimension, Paroi_TBLE_QDM::eq_vit, Domaine_VF::face_normales(), Paroi_TBLE_QDM::imprimer_stat(), Equation_base::inconnue(), Turbulence_paroi_base::le_dom_dis_, Turbulence_paroi_base::mon_modele_turb_hyd, Paroi_TBLE_QDM::nb_post_pts, Paroi_TBLE_QDM::nb_pts, Paroi_TBLE_QDM::nom_pts, Paroi_TBLE_QDM::num_faces_post, Paroi_TBLE_QDM::num_global_faces_post, Turbulence_paroi_base::tab_u_star(), Champ_base::temps(), TRUST_Ref< _CLASSE_ >::valeur(), and Domaine_VF::xv().
sauvegarder()
int ParoiVEF_TBLE::sauvegarder (Sortie &) const override virtual
Sauvegarde d'un Objet_U sur un flot de sortie Methode a surcharger.
Parameters
(Sortie&) flot de sortie a utiliser pour la sauvegarde
Returns
(int) code de retour
Reimplemented from Turbulence_paroi_base.
References Turbulence_paroi_base::le_dom_Cl_dis_, Turbulence_paroi_base::le_dom_dis_, Turbulence_paroi_base::mon_modele_turb_hyd, Paroi_TBLE_QDM::sauvegarder(), and TRUST_Ref< _CLASSE_ >::valeur().
reprendre()
int ParoiVEF_TBLE::reprendre (Entree &) override virtual
Reprise d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree&) flot d'entree a utiliser pour la reprise
Returns
(int) code de retour
Reimplemented from Turbulence_paroi_base.
References Turbulence_paroi_base::le_dom_Cl_dis_, Turbulence_paroi_base::le_dom_dis_, Turbulence_paroi_base::mon_modele_turb_hyd, TRUST_Ref< _CLASSE_ >::non_nul(), Paroi_TBLE_QDM::reprendre(), and TRUST_Ref< _CLASSE_ >::valeur().
getPbBase()
const Probleme_base & ParoiVEF_TBLE::getPbBase () const override virtual
Implements Paroi_TBLE_QDM.
References Turbulence_paroi_base::mon_modele_turb_hyd.
Member Data Documentation
info_obj
const Type_info ParoiVEF_TBLE::info_obj static