TrioCFD: PDF_model Class Reference
PDF_model Class Reference
#include <PDF_model.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
int lire_motcle_non_standard (const Motcle &, Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
Constructor & Destructor Documentation
PDF_model()
PDF_model::PDF_model ()
~PDF_model()
PDF_model::~PDF_model ()
Member Function Documentation
cree_instance()
Objet_U * PDF_model::cree_instance () static
taille_memoire()
unsigned PDF_model::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int PDF_model::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * PDF_model::info () static
get_info()
const Type_info * PDF_model::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
PDF_model & PDF_model::self_cast (Objet_U & r) static
self_cast() [2/2]
const PDF_model & PDF_model::self_cast (const Objet_U & r) static
printOn()
Sortie & PDF_model::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
References Objet_U::printOn().
readOn()
Entree & PDF_model::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
References Param::ajouter(), Param::ajouter_flag(), Param::ajouter_non_std(), coefku_, echelle_relax_, eta_, Process::exit(), Param::lire_avec_accolades_depuis(), local_, Param::OPTIONAL, pdf_bilan_, Objet_U::que_suis_je(), Param::REQUIRED, temps_relax_, and type_variable_imposee_.
get_variable_imposee()
double PDF_model::get_variable_imposee (ArrOfDouble & x, int comp)
References Objet_U::dimension.
Referenced by affecter_variable_imposee(), and Source_PDF_EF::compute_variable_imposee_projete().
affecter_variable_imposee()
void PDF_model::affecter_variable_imposee (Domaine_VF & le_dom, const DoubleTab & coords)
References dim_variable_, Objet_U::dimension, Process::exit(), get_variable_imposee(), Domaine_dis_base::nb_som_tot(), type_variable_imposee_, Champ_Don_base::valeurs(), and variable_imposee_.
Referenced by Source_PDF_EF::associer_pb().
eta()
double PDF_model::eta () const inline
References eta_.
pdf_bilan()
int PDF_model::pdf_bilan () const inline
References pdf_bilan_.
Referenced by Equation_IBM_proto::derivee_en_temps_inco_ibm_proto(), and Source_PDF_EF::impr().
lire_motcle_non_standard()
int PDF_model::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override protected virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Objet_U.
References dim_variable_, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, TRUST_Vector< _CLASSE_ >::dimensionner(), Process::exit(), local_, type_variable_imposee_, Champ_Don_base::valeurs(), and variable_imposee_lu_.
Friends And Related Function Documentation
Source_PDF_base
friend class Source_PDF_base friend
Source_PDF_EF
friend class Source_PDF_EF friend
Member Data Documentation
info_obj
const Type_info PDF_model::info_obj static
variable_imposee_lu_
TRUST_Deriv< Champ_Don_base > PDF_model::variable_imposee_lu_ protected
Referenced by Source_PDF_EF::associer_pb(), and lire_motcle_non_standard().
variable_imposee_
TRUST_Deriv< Champ_Don_base > PDF_model::variable_imposee_ protected
Referenced by affecter_variable_imposee(), Source_PDF_EF::associer_pb(), Source_PDF_EF::calculer_variable_imposee_elem_fluid(), Source_PDF_EF::calculer_variable_imposee_hybrid(), Source_PDF_EF::calculer_variable_imposee_mean_grad(), Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl(), Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl_u_star(), and Source_PDF_EF::compute_variable_imposee_projete().
dim_variable_
int PDF_model::dim_variable_ =-1 protected
Referenced by affecter_variable_imposee(), Source_PDF_EF::associer_pb(), Source_PDF_EF::impr(), lire_motcle_non_standard(), and Source_PDF_base::ouvrir_fichier().
eta_
double PDF_model::eta_ = -100. protected
Referenced by Source_PDF_EF::ajouter_(), Source_PDF_EF::compute_coeff_elem(), Source_PDF_EF::compute_coeff_matrice(), Source_PDF_EF::contribuer_a_avec(), eta(), Source_PDF_base::get_tuvw_local(), and readOn().
coefku_
double PDF_model::coefku_ = -100. protected
Referenced by readOn().
temps_relax_
double PDF_model::temps_relax_ =1.0e+12 protected
Referenced by Source_PDF_EF::associer_pb(), readOn(), and Source_PDF_base::readOn().
echelle_relax_
double PDF_model::echelle_relax_ =5.0e-2 protected
Referenced by Source_PDF_EF::associer_pb(), readOn(), and Source_PDF_base::readOn().
type_variable_imposee_
int PDF_model::type_variable_imposee_ = -1 protected
Referenced by affecter_variable_imposee(), Source_PDF_EF::associer_pb(), lire_motcle_non_standard(), and readOn().
local_
bool PDF_model::local_ = false protected
Referenced by Source_PDF_EF::associer_pb(), lire_motcle_non_standard(), and readOn().
pdf_bilan_
int PDF_model::pdf_bilan_ = 0 protected
Referenced by pdf_bilan(), and readOn().