TrioCFD: Navier_Stokes_FT_Disc Class Reference
Navier_Stokes_FT_Disc Class Reference
#include <Navier_Stokes_FT_Disc.h>
Public Member Functions
void associer_pb_base (const Probleme_base &probleme) override
void calculer_delta_u_interface (Champ_base &u0, int phase_pilote, int ordre)
void discretiser () override
virtual const Champ_base * get_delta_vitesse_interface () const
const Type_info * get_info () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
void mettre_a_jour (double temps) override
const Milieu_base & milieu () const override
Milieu_base & milieu () override
void projeter () override
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Public Member Functions inherited from Navier_Stokes_Turbulent
void completer () override
const Type_info * get_info () const override
void imprimer (Sortie &) const override
bool initTimeStep (double dt) override
int lire_motcle_non_standard (const Motcle &, Entree &) override
void mettre_a_jour (double) override
int preparer_calcul () override
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Public Member Functions inherited from Navier_Stokes_std
void abortTimeStep () override
void associer_milieu_base (const Milieu_base &) override
void associer_pb_base (const Probleme_base &) override
virtual void calculer_la_pression_en_pa ()
void completer () override
DoubleTab & derivee_en_temps_inco (DoubleTab &) override
const Motcle & domaine_application () const override
Fluide_base & fluide ()
const Fluide_base & fluide () const
const Type_info * get_info () const override
int impr (Sortie &os) const override
const Champ_Inc_base & inconnue () const override
Champ_Inc_base & inconnue () override
bool initTimeStep (double dt) override
Entree & lire_cond_init (Entree &) override
int lire_motcle_non_standard (const Motcle &, Entree &) override
void mettre_a_jour (double temps) override
const Milieu_base & milieu () const override
Milieu_base & milieu () override
int nombre_d_operateurs () const override
const Operateur & operateur (int) const override
Operateur & operateur (int) override
Operateur_Div & operateur_divergence ()
const Operateur_Div & operateur_divergence () const
Operateur_Grad & operateur_gradient ()
const Operateur_Grad & operateur_gradient () const
int preparer_calcul () override
virtual void projeter ()
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
SolveurSys & solveur_pression ()
int verif_Cl () const override
Public Member Functions inherited from Equation_base
virtual void abortTimeStep ()
virtual void associer_domaine_dis (const Domaine_dis_base &)
virtual void associer_pb_base (const Probleme_base &)
virtual void associer_sch_tps_base (const Schema_Temps_base &)
virtual double calculer_pas_de_temps () const
virtual void completer ()
virtual std::vector< YAML_data > data_a_sauvegarder () const
DoubleTab & derivee_en_temps_conv (DoubleTab &, const DoubleTab &)
virtual DoubleTab & derivee_en_temps_inco (DoubleTab &)
const Discretisation_base & discretisation () const
virtual void discretiser ()
virtual const Motcle & domaine_application () const
virtual Domaine_Cl_dis_base & domaine_Cl_dis ()
virtual const Domaine_Cl_dis_base & domaine_Cl_dis () const
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual void imprimer (Sortie &os) const
virtual bool initTimeStep (double dt)
const Nom & le_nom () const override
int limpr () const
virtual void mettre_a_jour (double temps)
virtual int preparer_calcul ()
Probleme_base & probleme ()
const Probleme_base & probleme () const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Schema_Temps_base & schema_temps ()
const Schema_Temps_base & schema_temps () const
Solveur_Masse_base & solv_masse ()
const Solveur_Masse_base & solv_masse () const
Sources & sources ()
const Sources & sources () const
virtual void valider_iteration ()
virtual void verifie_ch_init_nb_comp (const Champ_Inc_base &ch_ref, const int nb_comp) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
void associer_milieu_base (const Milieu_base &fluide) override
virtual void calculer_champ_forces_superficielles (const Maillage_FT_Disc &maillage, const Champ_base &gradient_indicatrice, Champ_base &potentiel_elements, Champ_base &potentiel_faces, Champ_base &champ)
virtual void calculer_gradient_indicatrice (const Champ_base &indicatrice, const DoubleTab &distance_interface_sommets, Champ_base &gradient_i)
void discretiser_assembleur_pression () override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
virtual void discretiser_assembleur_pression ()
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Equation_base
virtual Entree & lire_cl (Entree &)
virtual Entree & lire_cond_init (Entree &)
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual Entree & lire_sources (Entree &)
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
virtual int verif_Cl () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Navier_Stokes_FT_Disc()
Navier_Stokes_FT_Disc::Navier_Stokes_FT_Disc ()
~Navier_Stokes_FT_Disc()
Navier_Stokes_FT_Disc::~Navier_Stokes_FT_Disc ()
Member Function Documentation
cree_instance()
Objet_U * Navier_Stokes_FT_Disc::cree_instance () static
taille_memoire()
unsigned Navier_Stokes_FT_Disc::taille_memoire () const override virtual
Reimplemented from Navier_Stokes_Turbulent.
duplique()
int Navier_Stokes_FT_Disc::duplique () const override virtual
Reimplemented from Navier_Stokes_Turbulent.
info()
const Type_info * Navier_Stokes_FT_Disc::info () static
get_info()
const Type_info * Navier_Stokes_FT_Disc::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Navier_Stokes_Turbulent.
self_cast() [1/2]
Navier_Stokes_FT_Disc & Navier_Stokes_FT_Disc::self_cast (Objet_U & r) static
self_cast() [2/2]
const Navier_Stokes_FT_Disc & Navier_Stokes_FT_Disc::self_cast (const Objet_U & r) static
printOn()
Sortie & Navier_Stokes_FT_Disc::printOn (Sortie & os) const override protected virtual
Surcharge Objet_U::printOn Imprime l'equation et ses composants sur un flot de sortie.
Imprime le nom de l'equation, le solveur masse, les termes sources les conditions aux limites discretisees, les inconnues et les operateurs.
Parameters
(Sortie& os) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Navier_Stokes_Turbulent.
References Navier_Stokes_std::printOn().
readOn()
Entree & Navier_Stokes_FT_Disc::readOn (Entree & is) override protected virtual
Appel Equation_base::readOn(Entree& is) En sortie verifie que l'on a bien lu:
   - le terme diffusif,
   - le terme convectif,
   - le solveur en pression
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Exceptions
terme diffusif non specifie dans jeu de donnees, specifier un type negligeable pour l'operateur si il est a negliger
terme convectif non specifie dans jeu de donnees, specifier un type negligeable pour l'operateur si il est a negliger
solveur pression non defini dans jeu de donnees
Reimplemented from Navier_Stokes_Turbulent.
References Operateur_Diff::associer_diffusivite(), champ_mu_, Navier_Stokes_Turbulent::readOn(), and Navier_Stokes_std::terme_diffusif.
set_param()
void Navier_Stokes_FT_Disc::set_param (Param & titi) override virtual
Reimplemented from Navier_Stokes_Turbulent.
References Param::ajouter(), Param::ajouter_flag(), Param::ajouter_non_std(), and Navier_Stokes_Turbulent::set_param().
lire_motcle_non_standard()
int Navier_Stokes_FT_Disc::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Navier_Stokes_Turbulent.
References TRUST_Vector< _CLASSE_ >::add(), Support_Champ_Masse_Volumique::associer_champ_masse_volumique(), Operateur_Diff::associer_diffusivite(), Process::barrier(), champ_rho_elem_, Navier_Stokes_FT_Disc_interne::CORRECTION_GHOST_INDIC, diffusivite_pour_transport(), Objet_U::dimension, Probleme_FT_Disc_gen::equation_interfaces(), Navier_Stokes_FT_Disc_interne::eta, Process::exit(), Probleme_FT_Disc_gen::get_equation_by_name(), Navier_Stokes_FT_Disc_interne::GRAVITE_GRAD_I, Navier_Stokes_FT_Disc_interne::GRAVITE_RHO_G, Navier_Stokes_FT_Disc_interne::INTERP_AI_BASED, Navier_Stokes_FT_Disc_interne::INTERP_AI_BASED_UIEXT, Navier_Stokes_FT_Disc_interne::INTERP_AI_BASED_UVEXT, Navier_Stokes_FT_Disc_interne::INTERP_MODIFIEE, Navier_Stokes_FT_Disc_interne::INTERP_MODIFIEE_UIEXT, Navier_Stokes_FT_Disc_interne::INTERP_MODIFIEE_UVEXT, Navier_Stokes_FT_Disc_interne::INTERP_STANDARD, Navier_Stokes_FT_Disc_interne::INTERP_STANDARD_UIEXT, Navier_Stokes_FT_Disc_interne::INTERP_STANDARD_UVEXT, Navier_Stokes_FT_Disc_interne::is_explicite, Navier_Stokes_FT_Disc_interne::is_penalized, Navier_Stokes_FT_Disc_interne::is_pfl_flottant, Process::je_suis_maitre(), Navier_Stokes_Turbulent::le_modele_turbulence, Navier_Stokes_Turbulent::lire_motcle_non_standard(), Navier_Stokes_Turbulent::lire_op_diff_turbulent(), Navier_Stokes_FT_Disc_interne::NO_CORRECTION, Objet_U_ptr::non_nul(), Navier_Stokes_FT_Disc_interne::OutletCorrection_pour_dI_dt_, Navier_Stokes_FT_Disc_interne::p_ref_pena, probleme_ft(), Motcles::search(), TRUST_Vector< _CLASSE_ >::size(), Navier_Stokes_std::terme_diffusif, Navier_Stokes_FT_Disc_interne::terme_gravite_, Navier_Stokes_FT_Disc_interne::type_interpol_indic_pour_dI_dt_, TRUST_Deriv< _CLASSE_ >::valeur(), Navier_Stokes_FT_Disc_interne::x_pfl_imp, Navier_Stokes_FT_Disc_interne::y_pfl_imp, Navier_Stokes_FT_Disc_interne::z_pfl_imp, Navier_Stokes_FT_Disc_interne::ZERO_NET_FLUX_ON_MIXED_CELLS, and Navier_Stokes_FT_Disc_interne::ZERO_OUT_FLUX_ON_MIXED_CELLS.
milieu() [1/2]
const Milieu_base & Navier_Stokes_FT_Disc::milieu () const override virtual
Renvoie le milieu physique de l'equation (le Fluide_base upcaste en Milieu_base)
Returns
(Milieu_base&) le Fluide_base de l'equation upcaste en Milieu_base
Reimplemented from Navier_Stokes_std.
References Navier_Stokes_std::milieu().
Referenced by Transport_Marqueur_FT::calculer_proprietes_fluide_pos_particules(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_vinf_Stokes(), derivee_en_temps_inco(), and preparer_calcul().
milieu() [2/2]
Milieu_base & Navier_Stokes_FT_Disc::milieu () override virtual
Renvoie le milieu physique de l'equation (le Fluide_base upcaste en Milieu_base)
(version const)
Returns
(Milieu_base&) le Fluide_base de l'equation upcaste en Milieu_base
Reimplemented from Navier_Stokes_std.
References Navier_Stokes_std::milieu().
associer_pb_base()
void Navier_Stokes_FT_Disc::associer_pb_base (const Probleme_base & pb) override virtual
S'associe au probleme: apelle Equation_base::associer_pb_base(const Probleme_base&)
s'associe avec les operateurs de divergence et de gradient.
Parameters
(Probleme_base& pb) le probleme auquel s'associer
Reimplemented from Navier_Stokes_std.
References Navier_Stokes_std::associer_pb_base(), Process::exit(), and probleme_ft_.
discretiser()
void Navier_Stokes_FT_Disc::discretiser () override virtual
Discretisation des champs utilises dans cette equation.
Fonction appelee par Probleme_base::discretiser. B. Mathieu : a titre experimental, au lieu de dupliquer les noms des champs ici et dans "a_pour_champ_Fonc", on stocke les champs dans une liste. (voir a_pour_champ_fonc).
Reimplemented from Navier_Stokes_std.
References Champs_compris_T< FIELD_TYPE >::ajoute_champ(), champ_mu_, champ_nu_, champ_rho_elem_, champ_rho_faces_, Equation_base::champs_compris_, Domaine_32_64< _SIZE_ >::creer_tableau_elements(), Equation_base::discretisation(), Navier_Stokes_std::discretiser(), Discretisation_base::discretiser_champ(), Domaine_dis_base::domaine(), Equation_base::domaine_dis(), fluide_diphasique(), get_is_solid_particle(), Equation_base::le_nom(), Field_base::nommer(), particles_eulerian_id_number_, particles_eulerian_id_number_post_, Objet_U::que_suis_je(), Equation_base::schema_temps(), set_id_fluid_phase(), set_is_solid_particle(), Schema_Temps_base::temps_courant(), and TRUST_Deriv< _CLASSE_ >::valeur().
data_a_sauvegarder()
std::vector< YAML_data > Navier_Stokes_FT_Disc::data_a_sauvegarder () const override virtual
for PDI IO: retrieve name, type and dimensions of the fields to save/restore
Reimplemented from Navier_Stokes_Turbulent.
References Champ_Fonc_base::data_a_sauvegarder(), Navier_Stokes_Turbulent::data_a_sauvegarder(), is_solid_particle_, and particles_eulerian_id_number_post_.
sauvegarder()
int Navier_Stokes_FT_Disc::sauvegarder (Sortie & os) const override virtual
Sauvegarde l'equation (et son modele de turbulence) sur un flot de sortie.
Parameters
(Sortie& os) un flot de sortie
Returns
(int) renvoie toujours 1
Reimplemented from Navier_Stokes_Turbulent.
References is_solid_particle_, particles_eulerian_id_number_post_, Champ_Fonc_base::sauvegarder(), and Navier_Stokes_Turbulent::sauvegarder().
reprendre()
int Navier_Stokes_FT_Disc::reprendre (Entree & is) override virtual
Reprise de l'equation et de son modele de turbulence a partir d'un flot d'entree.
Parameters
(Entree& is) un flot d'entree
Returns
(int) renvoie toujours 1
Exceptions
fin de fichier rencontre pendant la reprise
Reimplemented from Navier_Stokes_Turbulent.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Probleme_base::domaine(), is_solid_particle_, Domaine_base::le_nom(), Objet_U_ptr::le_nom(), particles_eulerian_id_number_post_, Equation_base::probleme(), Objet_U::que_suis_je(), Champ_Fonc_base::reprendre(), Navier_Stokes_Turbulent::reprendre(), Equation_base::schema_temps(), Schema_Temps_base::temps_courant(), and Champ_Don_base::valeurs().
preparer_calcul()
int Navier_Stokes_FT_Disc::preparer_calcul () override virtual
methode appelee par Probleme_base::preparer_calcul()
Reimplemented from Navier_Stokes_Turbulent.
References Champs_compris_T< FIELD_TYPE >::ajoute_champ(), Solveur_Masse_base::appliquer(), Assembleur_base::assembler_rho_variable(), Navier_Stokes_std::assembleur_pression(), Navier_Stokes_std::assembleur_pression_, Support_Champ_Masse_Volumique::associer_champ_masse_volumique(), Operateur_Div::calculer(), Operateur_Grad::calculer(), champ_mu_, champ_nu_, champ_rho_elem_, champ_rho_faces_, Equation_base::champs_compris_, Champ_Inc_base::changer_temps(), compute_particles_eulerian_id_number(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Equation_base::discretisation(), Discretisation_base::discretiser_champ(), Navier_Stokes_std::divergence, Equation_base::domaine_dis(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), fluide_diphasique(), Post_Processing_Hydrodynamic_Forces::get_is_compute_forces_Stokes_th(), Navier_Stokes_std::gradient, Navier_Stokes_std::inconnue(), is_solid_particle_, Process::je_suis_maitre(), Navier_Stokes_std::la_pression, Navier_Stokes_Turbulent::le_modele_turbulence, Navier_Stokes_std::le_traitement_particulier, TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Navier_Stokes_std::matrice_pression_, milieu(), Assembleur_base::modifier_secmem(), Assembleur_base::modifier_solution(), Objet_U_ptr::non_nul(), Equation_base::preparer_calcul(), Modele_turbulence_hyd_base::preparer_calcul(), Traitement_particulier_NS_base::preparer_calcul_particulier(), pressure_field_Stokes_th_, Navier_Stokes_std::projection_a_faire(), SolveurSys::resoudre_systeme(), Equation_base::schema_temps(), Equation_base::solveur_masse, Navier_Stokes_std::solveur_pression(), Navier_Stokes_std::solveur_pression_, Support_Champ_Masse_Volumique::support_ok(), Schema_Temps_base::temps_courant(), TRUST_Deriv< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), Champ_Inc_base::valeurs(), and velocity_field_Stokes_th_.
preparer_pas_de_temps()
void Navier_Stokes_FT_Disc::preparer_pas_de_temps ()
mettre_a_jour()
void Navier_Stokes_FT_Disc::mettre_a_jour (double temps) override virtual
Effecttue une mise a jour en temps de l'equation.
Parameters
(double temps) le temps de mise a jour
Reimplemented from Navier_Stokes_Turbulent.
References champ_mu_, champ_nu_, champ_rho_elem_, champ_rho_faces_, Equation_base::domaine_dis(), is_solid_particle_, Champ_Don_base::mettre_a_jour(), Champ_Fonc_base::mettre_a_jour(), Navier_Stokes_Turbulent::mettre_a_jour(), Domaine_dis_base::nb_elem(), particles_eulerian_id_number_, particles_eulerian_id_number_post_, and Champ_Don_base::valeurs().
calculer_la_pression_en_pa()
void Navier_Stokes_FT_Disc::calculer_la_pression_en_pa () override virtual
In Front Tracking, pression is in Pa and so pression_pa field <=> pression field.
Reimplemented from Navier_Stokes_std.
References Navier_Stokes_std::la_pression, Navier_Stokes_std::la_pression_en_pa, and Champ_Inc_base::valeurs().
derivee_en_temps_inco()
DoubleTab & Navier_Stokes_FT_Disc::derivee_en_temps_inco (DoubleTab & vpoint) override virtual
Calcul de la derivee en temps de la vitesse.
Reimplemented from Navier_Stokes_std.
References Sources::ajouter(), Solveur_Masse_base::appliquer(), Parametre_implicite::calcul_explicite(), Operateur_Conv::calculer(), Operateur_Diff::calculer(), Operateur_Grad::calculer(), calculer_champ_forces_superficielles(), calculer_gradient_indicatrice(), champ_mu_, champ_nu_, champ_rho_elem_, champ_rho_faces_, compute_boussinesq_additional_gravity(), compute_eulerian_field_contact_forces(), TRUSTTab< _TYPE_, _SIZE_ >::copy(), Equation_base::derivee_en_temps_conv(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Equation_base::domaine_dis(), Process::exit(), fluide_diphasique(), Transport_Interfaces_FT_Disc::get_ptr_collision_model(), Transport_Interfaces_FT_Disc::get_update_distance_interface_sommets(), Navier_Stokes_std::gradient, Milieu_base::gravite(), Navier_Stokes_FT_Disc_interne::GRAVITE_RHO_G, Navier_Stokes_std::inconnue(), is_solid_particle_, Navier_Stokes_std::la_pression, Navier_Stokes_std::la_vitesse, Equation_base::le_dom_dis, Equation_base::les_sources, TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Transport_Interfaces_FT_Disc::maillage_interface(), milieu(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Objet_U_ptr::non_nul(), Equation_base::parametre_equation_, Equation_base::schema_temps(), Equation_base::solveur_masse, Navier_Stokes_std::terme_convectif, Navier_Stokes_std::terme_diffusif, TRUST_Deriv< _CLASSE_ >::valeur(), Champ_Don_base::valeurs(), and Champ_Inc_base::valeurs().
projeter()
void Navier_Stokes_FT_Disc::projeter () override virtual
methode appelee par Navier_Stokes_std::preparer_calcul.
..
Reimplemented from Navier_Stokes_std.
References Process::je_suis_maitre(), and Equation_base::limpr().
calculer_div_normale_interface()
const Champ_base & Navier_Stokes_FT_Disc::calculer_div_normale_interface () virtual
References Solveur_Masse_base::appliquer(), Operateur_Div::calculer(), Operateur_Grad::calculer(), correct_at_exit_bad_gradient(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Navier_Stokes_std::divergence, Equation_base::domaine_dis(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Transport_Interfaces_FT_Disc::get_update_distance_interface(), Navier_Stokes_std::gradient, Navier_Stokes_std::inconnue(), Equation_base::solveur_masse, and Champ_Proto::valeurs().
Referenced by calculer_delta_u_interface(), and Convection_Diffusion_Temperature_FT_Disc::calculer_grad_t().
correct_at_exit_bad_gradient()
void Navier_Stokes_FT_Disc::correct_at_exit_bad_gradient (DoubleTab & u0) const
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Equation_base::domaine_Cl_dis(), Equation_base::domaine_dis(), Domaine_VF::elem_faces(), Process::exit(), Domaine_VF::face_voisins(), Domaine_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by calculer_delta_u_interface(), and calculer_div_normale_interface().
calculer_delta_u_interface()
void Navier_Stokes_FT_Disc::calculer_delta_u_interface (Champ_base & champ_u0, int phase_pilote, int ordre)
Calcul du saut de vitesse a l'interface du au changement de phase.
phase_pilote = -1: u-u0 = champ de vitesse de deplacement de l'interface phase_pilote = 0 : u+u0 = champ de vitesse de la phase 0 phase_pilote = 1 : u+u0 = champ de vitesse de la phase 1 ordre = 0 : pas de prise en compte de la correction en courbure ordre = 1 : prise en compte de la correction en courbure a l'ordre 1 ordre = 2 : prise en compte de la correction en courbure a l'ordre 2
References Solveur_Masse_base::appliquer(), Objet_U::bidim_axi, Operateur_Grad::calculer(), calculer_div_normale_interface(), correct_at_exit_bad_gradient(), Intersections_Elem_Facettes::data_intersection(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Equation_base::domaine_dis(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_VF::elem_faces(), Process::exit(), Domaine_VF::face_surfaces(), Domaine_VF::face_voisins(), fluide_diphasique(), Fluide_Diphasique::fluide_phase(), Transport_Interfaces_FT_Disc::get_update_distance_interface(), Transport_Interfaces_FT_Disc::get_update_normale_interface(), Navier_Stokes_std::gradient, Intersections_Elem_Facettes::index_facette(), Maillage_FT_Disc::intersections_elem_facettes(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Transport_Interfaces_FT_Disc::maillage_interface(), Milieu_base::masse_volumique(), Domaine_VF::nb_faces(), Maillage_FT_Disc::nb_facettes(), Intersections_Elem_Facettes_Data::numero_element_, Domaine_VDF::orientation(), Objet_U::que_suis_je(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Equation_base::solveur_masse, Champ_Proto::valeurs(), Domaine_VF::xp(), and Domaine_VF::xv().
Referenced by Convection_Diffusion_Temperature_FT_Disc::derivee_en_temps_inco().
diffusivite_pour_transport()
const Champ_Don_base & Navier_Stokes_FT_Disc::diffusivite_pour_transport () const override virtual
Reimplemented from Navier_Stokes_Turbulent.
References champ_mu_.
Referenced by lire_motcle_non_standard().
get_delta_vitesse_interface()
const Champ_base * Navier_Stokes_FT_Disc::get_delta_vitesse_interface () const virtual
Si le champ de vitesse est discontinu (calcul avec changement de phase), renvoie un pointeur vers le champ delta_v de "discontinuite", tel que.
inconnue - delta_v = vitesse de deplacement des interfaces (voir Transport_Interfaces_FT_Disc::deplacer_maillage_v_fluide()) Si pas de changement de phase, renvoie un pointeur nul.
Referenced by Transport_Interfaces_FT_Disc::ajouter_contribution_saut_vitesse(), Transport_Marqueur_FT::calcul_vitesse_p(), Transport_Interfaces_FT_Disc::deplacer_maillage_ft_v_fluide(), and Transport_Interfaces_FT_Disc::fill_ftab_velocity().
fluide_diphasique()
const Fluide_Diphasique & Navier_Stokes_FT_Disc::fluide_diphasique () const virtual
References Process::exit().
Referenced by calculer_delta_u_interface(), calculer_dI_dt(), Transport_Interfaces_FT_Disc::calculer_vitesse_transport_interpolee(), compute_eulerian_field_contact_forces(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_friction_force_complet_tensor(), Post_Processing_Hydrodynamic_Forces::compute_friction_force_projected_tensor(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_friction_force_projected_tensor(), Post_Processing_Hydrodynamic_Forces::compute_heat_transfer(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_neighbors_coordinates_fluid_fa7(), compute_particles_eulerian_id_number(), Transport_Interfaces_FT_Disc::compute_particles_rms(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_pressure_force_trilinear_linear(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_pressure_interf(), Triple_Line_Model_FT_Disc::compute_TCL_fluxes_in_all_boundary_cells(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_vinf_Stokes(), Post_Processing_Hydrodynamic_Forces::compute_viscosity_edges_sphere(), derivee_en_temps_inco(), discretiser(), Post_Processing_Hydrodynamic_Forces_Stokes::fill_sigma_Stokes_th(), Post_Processing_Hydrodynamic_Forces_Stokes::fill_Stokes_pressure_field(), Post_Processing_Hydrodynamic_Forces_Stokes::fill_Stokes_velocity_field(), preparer_calcul(), Collision_Model_FT_base::preparer_calcul(), Collision_Model_FT_base::research_collision_pairs_Verlet(), Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_gradU_elem(), and Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_gradU_elem_P1().
compute_boussinesq_additional_gravity()
void Navier_Stokes_FT_Disc::compute_boussinesq_additional_gravity (const Convection_Diffusion_Temperature_FT_Disc & eq, const Fluide_Diphasique & fluide_diphasique, const IntTab & face_voisins, const DoubleVect & volumes_entrelaces, const IntVect & orientation, const DoubleTab & indicatrice, const ArrOfDouble & g, DoubleTab & gravite_face) const
References Milieu_base::beta_t(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Fluide_Diphasique::fluide_phase(), Convection_Diffusion_Temperature_FT_Disc::get_phase(), Convection_Diffusion_Temperature::inconnue(), Champ_Don_base::valeurs(), and Champ_Inc_base::valeurs().
Referenced by derivee_en_temps_inco().
is_terme_gravite_rhog()
int Navier_Stokes_FT_Disc::is_terme_gravite_rhog () const
References Navier_Stokes_FT_Disc_interne::GRAVITE_RHO_G.
Referenced by Transport_Marqueur_FT::calculer_proprietes_fluide_pos_particules().
champ_rho_faces()
const Champ_Fonc_base & Navier_Stokes_FT_Disc::champ_rho_faces () const
References champ_rho_faces_.
calculer_dI_dt()
void Navier_Stokes_FT_Disc::calculer_dI_dt (DoubleVect & dI_dt) virtual
References TRUSTTab< _TYPE_, _SIZE_ >::copy(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Equation_base::domaine_dis(), Domaine_dis_base::face_voisins(), fluide_diphasique(), Fluide_Diphasique::fluide_phase(), Transport_Interfaces_FT_Disc::inconnue(), Navier_Stokes_std::inconnue(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Transport_Interfaces_FT_Disc::maillage_interface(), Milieu_base::masse_volumique(), Champ_Inc_base::valeurs(), and Champ_Proto::valeurs().
Referenced by Transport_Interfaces_FT_Disc::deplacer_maillage_ft_v_fluide().
get_is_penalized()
const int & Navier_Stokes_FT_Disc::get_is_penalized () const
References Navier_Stokes_FT_Disc_interne::is_penalized.
get_new_mass_source()
const int & Navier_Stokes_FT_Disc::get_new_mass_source () const
References Navier_Stokes_FT_Disc_interne::new_mass_source_.
Referenced by Transport_Interfaces_FT_Disc::ajouter_contribution_saut_vitesse().
get_interfacial_area()
const DoubleTab & Navier_Stokes_FT_Disc::get_interfacial_area () const
Referenced by Transport_Interfaces_FT_Disc::calcul_indicatrice_faces(), Convection_Diffusion_Temperature_FT_Disc::correct_mpoint(), and Convection_Diffusion_Temperature_FT_Disc::derivee_en_temps_inco().
get_set_interfacial_area()
DoubleTab & Navier_Stokes_FT_Disc::get_set_interfacial_area ()
get_mpoint()
const DoubleTab & Navier_Stokes_FT_Disc::get_mpoint () const
get_set_mpoint()
DoubleTab & Navier_Stokes_FT_Disc::get_set_mpoint ()
get_solveur_pression()
const SolveurSys & Navier_Stokes_FT_Disc::get_solveur_pression () const
References Navier_Stokes_std::solveur_pression_.
get_is_solid_particle()
const bool & Navier_Stokes_FT_Disc::get_is_solid_particle () const inline
References is_solid_particle_.
Referenced by discretiser(), and Transport_Interfaces_FT_Disc::lire_motcle_non_standard().
get_particles_eulerian_id_number()
const IntTab & Navier_Stokes_FT_Disc::get_particles_eulerian_id_number () const inline
References particles_eulerian_id_number_.
Referenced by Transport_Interfaces_FT_Disc::calculer_vitesse_transport_interpolee(), Post_Processing_Hydrodynamic_Forces::compute_hydrodynamic_forces(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_hydrodynamic_forces(), Transport_Interfaces_FT_Disc::compute_particles_rms(), Transport_Interfaces_FT_Disc::swap_particles_lagrangian_position_velocity(), Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_elem(), and Post_Processing_Hydrodynamic_Forces::trilinear_interpolation_gradU_elem_P1().
compute_particles_eulerian_id_number()
void Navier_Stokes_FT_Disc::compute_particles_eulerian_id_number (const TRUST_Deriv< Collision_Model_FT_base > & collision_model_ptr)
References Equation_base::domaine_dis(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_VF::elem_faces(), Domaine_VF::face_voisins(), fluide_diphasique(), Fluide_Diphasique::get_id_fluid_phase(), Collision_Model_FT_base::get_is_force_on_two_phase_elem(), Domaine_dis_base::nb_elem(), and particles_eulerian_id_number_.
Referenced by Transport_Interfaces_FT_Disc::calculer_vitesse_transport_interpolee(), Transport_Interfaces_FT_Disc::mettre_a_jour(), and preparer_calcul().
swap_particles_eulerian_id_number()
void Navier_Stokes_FT_Disc::swap_particles_eulerian_id_number (const ArrOfInt & gravity_center_elem)
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), particles_eulerian_id_number_, and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by Transport_Interfaces_FT_Disc::calculer_vitesse_transport_interpolee(), Transport_Interfaces_FT_Disc::init_particles_position_velocity(), and Transport_Interfaces_FT_Disc::mettre_a_jour().
get_set_velocity_field_Stokes_th()
DoubleTab & Navier_Stokes_FT_Disc::get_set_velocity_field_Stokes_th () inline
References Champ_Don_base::valeurs(), and velocity_field_Stokes_th_.
Referenced by Post_Processing_Hydrodynamic_Forces_Stokes::compute_friction_force_complet_tensor(), Post_Processing_Hydrodynamic_Forces_Stokes::compute_friction_force_projected_tensor(), and Post_Processing_Hydrodynamic_Forces_Stokes::fill_Stokes_velocity_field().
get_set_pressure_field_Stokes_th()
DoubleTab & Navier_Stokes_FT_Disc::get_set_pressure_field_Stokes_th () inline
References pressure_field_Stokes_th_, and Champ_Don_base::valeurs().
Referenced by Post_Processing_Hydrodynamic_Forces_Stokes::compute_pressure_force_trilinear_linear(), and Post_Processing_Hydrodynamic_Forces_Stokes::fill_Stokes_pressure_field().
discretiser_assembleur_pression()
void Navier_Stokes_FT_Disc::discretiser_assembleur_pression () override protected virtual
Methode surchargee de Navier_Stokes_std, appelee par Navier_Stokes_std::discretiser().
L'assembleur pression est particulier pour le front-tracking en VEF (en attendant qu'on factorise tous ces assembleurs pression)
Reimplemented from Navier_Stokes_std.
References Navier_Stokes_std::assembleur_pression_, Assembleur_base::associer_domaine_dis_base(), Equation_base::discretisation(), Equation_base::domaine_dis(), Objet_U::que_suis_je(), Assembleur_base::set_resoudre_en_u(), Assembleur_base::set_resoudre_increment_pression(), Objet_U_ptr::typer(), and TRUST_Deriv< _CLASSE_ >::valeur().
associer_milieu_base()
void Navier_Stokes_FT_Disc::associer_milieu_base (const Milieu_base & un_milieu) override protected virtual
Associe un mileu physique a l'equation en construisant dynamiquement (cast) un objet de type Fluide_base.
a partir de l'objet Milieu_base passe en parametre.
Parameters
(Milieu_base& un_milieu) le milieu a associer a l'equation
Reimplemented from Navier_Stokes_std.
References Navier_Stokes_std::associer_milieu_base().
probleme_ft() [1/2]
const Probleme_FT_Disc_gen & Navier_Stokes_FT_Disc::probleme_ft () const protected virtual
References probleme_ft_, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by lire_motcle_non_standard().
probleme_ft() [2/2]
Probleme_FT_Disc_gen & Navier_Stokes_FT_Disc::probleme_ft () protected virtual
References probleme_ft_, and TRUST_Ref< _CLASSE_ >::valeur().
calculer_champ_forces_superficielles()
void Navier_Stokes_FT_Disc::calculer_champ_forces_superficielles (const Maillage_FT_Disc & maillage, const Champ_base & gradient_indicatrice, Champ_base & potentiel_elements, Champ_base & potentiel_faces, Champ_base & champ) protected virtual
Calcul des forces de tension superficielles (F_sigma) et de la partie a rotationnel non nul de la gravite (G_rot) (si GRAVITE_GRAD_I) :
F_sigma = INTEGRALE sur le volume de controle (sigma_aux_faces * courbure_aux_faces * gradient(indicatrice)
gradient_sigma) G_rot = INTEGRALE sur le volume de controle (phi * gradient(rho)) (avec phi = potentiel de pesanteur)
Parameters
(gradient_indicatrice) le gradient de l'indicatrice issu de l'operateur "gradient", donc homogene a l'integrale du gradient sur les volumes de controle de la vitesse.
(potentiel_faces) un champ aux faces a une composante, ou on stocke le "potentiel aux faces"
(champ) le champ aux faces (meme discretisation que la vitesse) ou on stocke le terme source des forces superficielles.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Equation_base::domaine_dis(), Domaine_VF::nb_faces(), Maillage_FT_Disc::nb_sommets(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), and Champ_Proto::valeurs().
Referenced by derivee_en_temps_inco().
calculer_gradient_indicatrice()
void Navier_Stokes_FT_Disc::calculer_gradient_indicatrice (const Champ_base & indicatrice, const DoubleTab & distance_interface_sommets, Champ_base & gradient_i) protected virtual
Calcul du gradient de l'indicatrice.
Ce gradient est utilise pour calculer le second membre de l'equation de qdm, contenant les termes de tension de surface. En VEF, on commence par creer un champ P1B a partir du champ P0 et on calcule le gradient. Design de classe a revoir pour separer VDF et VEF...
Parametre : indicatrice Signification : un champ aux elements (l'espace virtuel doit etre a jour) Parametre : gradient_i Signification : un champ discretise comme la vitesse dans lequel on met gradient(indicatrice).
References Operateur_Grad::calculer(), Navier_Stokes_FT_Disc_interne::CORRECTION_GHOST_INDIC, Objet_U::dimension, Domaine_dis_base::domaine(), Equation_base::domaine_Cl_dis(), Equation_base::domaine_dis(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Process::exit(), Domaine_VF::face_normales(), Domaine_VF::face_surfaces(), Domaine_dis_base::face_voisins(), Domaine_VF::face_voisins(), Navier_Stokes_std::gradient, Intersections_Elem_Facettes::index_elem(), Maillage_FT_Disc::intersections_elem_facettes(), Process::Journal(), Domaine_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Transport_Interfaces_FT_Disc::maillage_interface(), Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), Domaine_VF::orientation(), Navier_Stokes_FT_Disc_interne::OutletCorrection_pour_dI_dt_, Objet_U::precision_geom, Objet_U::que_suis_je(), TRUSTVect< _TYPE_, _SIZE_ >::size_totale(), TRUST_Deriv< _CLASSE_ >::valeur(), Champ_Proto::valeurs(), and Domaine_VF::volumes().
Referenced by derivee_en_temps_inco().
set_is_solid_particle()
void Navier_Stokes_FT_Disc::set_is_solid_particle (const bool & is_solid_particle) inline protected
References is_solid_particle_.
Referenced by discretiser().
set_id_fluid_phase()
void Navier_Stokes_FT_Disc::set_id_fluid_phase (const int & id_fluid_phase) inline protected
References id_fluid_phase_.
Referenced by discretiser().
compute_eulerian_field_contact_forces()
void Navier_Stokes_FT_Disc::compute_eulerian_field_contact_forces (const Maillage_FT_Disc & mesh, const Champ_base & field_volumic_phase_indicator_function) protected
References Statistiques::begin_count(), Collision_Model_FT_base::compute_lagrangian_contact_forces(), Collision_Model_FT_base::discretize_contact_forces_eulerian_field(), Equation_base::domaine_dis(), Statistiques::end_count(), fluide_diphasique(), Collision_Model_FT_base::get_nb_dt_compute_Verlet(), Collision_Model_FT_base::get_set_nb_dt_Verlet(), Collision_Model_FT_base::is_Verlet_activated(), Schema_Temps_base::nb_pas_dt(), Statistiques::new_counter(), particles_eulerian_id_number_, Schema_Temps_base::pas_de_temps(), Collision_Model_FT_base::research_collision_pairs_Verlet(), and Equation_base::schema_temps().
Referenced by derivee_en_temps_inco().
eulerian_discretization_contact_forces()
void Navier_Stokes_FT_Disc::eulerian_discretization_contact_forces (const DoubleTab & volumic_phase_indicator_function, const DoubleTab & interlaced_volumes, const DoubleTab & eu) protected
Friends And Related Function Documentation
Post_Processing_Hydrodynamic_Forces
friend class Post_Processing_Hydrodynamic_Forces friend
Member Data Documentation
info_obj
const Type_info Navier_Stokes_FT_Disc::info_obj static
probleme_ft_
TRUST_Ref< Probleme_FT_Disc_gen *> Navier_Stokes_FT_Disc::probleme_ft_ protected
Referenced by associer_pb_base(), and probleme_ft().
champ_rho_elem_
TRUST_Deriv< Champ_Fonc_base > Navier_Stokes_FT_Disc::champ_rho_elem_ protected
Referenced by derivee_en_temps_inco(), discretiser(), lire_motcle_non_standard(), mettre_a_jour(), and preparer_calcul().
champ_rho_faces_
TRUST_Deriv< Champ_Fonc_base > Navier_Stokes_FT_Disc::champ_rho_faces_ protected
Referenced by champ_rho_faces(), derivee_en_temps_inco(), discretiser(), mettre_a_jour(), and preparer_calcul().
champ_mu_
TRUST_Deriv< Champ_Don_base > Navier_Stokes_FT_Disc::champ_mu_ protected
Referenced by derivee_en_temps_inco(), diffusivite_pour_transport(), discretiser(), mettre_a_jour(), preparer_calcul(), and readOn().
champ_nu_
TRUST_Deriv< Champ_Don_base > Navier_Stokes_FT_Disc::champ_nu_ protected
Referenced by derivee_en_temps_inco(), discretiser(), mettre_a_jour(), and preparer_calcul().
is_solid_particle_
bool Navier_Stokes_FT_Disc::is_solid_particle_ =false protected
Referenced by data_a_sauvegarder(), derivee_en_temps_inco(), get_is_solid_particle(), mettre_a_jour(), preparer_calcul(), reprendre(), sauvegarder(), and set_is_solid_particle().
id_fluid_phase_
int Navier_Stokes_FT_Disc::id_fluid_phase_ =1 protected
Referenced by set_id_fluid_phase().
particles_eulerian_id_number_
IntTab Navier_Stokes_FT_Disc::particles_eulerian_id_number_ protected
Referenced by compute_eulerian_field_contact_forces(), compute_particles_eulerian_id_number(), discretiser(), get_particles_eulerian_id_number(), mettre_a_jour(), and swap_particles_eulerian_id_number().
particles_eulerian_id_number_post_
TRUST_Deriv< Champ_Fonc_base > Navier_Stokes_FT_Disc::particles_eulerian_id_number_post_ protected
Referenced by data_a_sauvegarder(), discretiser(), mettre_a_jour(), reprendre(), and sauvegarder().
velocity_field_Stokes_th_
TRUST_Deriv< Champ_Fonc_base > Navier_Stokes_FT_Disc::velocity_field_Stokes_th_ protected
Referenced by get_set_velocity_field_Stokes_th(), and preparer_calcul().
pressure_field_Stokes_th_
TRUST_Deriv< Champ_Fonc_base > Navier_Stokes_FT_Disc::pressure_field_Stokes_th_ protected
Referenced by get_set_pressure_field_Stokes_th(), and preparer_calcul().