TrioCFD: Probleme_FTD_IJK_base Class Reference
Probleme_FTD_IJK_base Class Reference
#include <Probleme_FTD_IJK_base.h>
Public Member Functions
void abortTimeStep () override
int associer_ (Objet_U &) override
void completer () override
double computeTimeStep (bool &stop) const override
void discretiser (Discretisation_base &dis) override
const Type_info * get_info () const override
void initialize () override
bool initTimeStep (double dt) override
bool iterateTimeStep (bool &converged) override
void mettre_a_jour (double temps) override
double presentTime () const override
void resetTime (double time) override
bool run () override
void terminate () override
virtual bool updateGivenFields () override
void validateTimeStep () override
Public Member Functions inherited from Probleme_FT_Disc_gen
int associer_ (Objet_U &ob) override
void associer_milieu_base (const Milieu_base &milieu) override
double calculer_pas_de_temps () const override
void completer () override
const Type_info * get_info () const override
void mettre_a_jour (double temps) override
virtual bool updateGivenFields () override
const Type_info * get_info () const override
Public Member Functions inherited from Probleme_base
void abortTimeStep () override
int associer_ (Objet_U &) override
virtual void associer_domaine (const Domaine &)
virtual void associer_milieu_base (const Milieu_base &)
virtual void associer_sch_tps_base (const Schema_Temps_base &)
virtual double calculer_pas_de_temps () const
virtual void completer ()
double computeTimeStep (bool &stop) const override
const Discretisation_base & discretisation () const
virtual void discretiser (Discretisation_base &)
Domaine & domaine ()
const Domaine & domaine () const
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
Equation_base & equation (const Nom &)
const Equation_base & equation (const Nom &) const
TRUST_Ref< Field_base * > findInputField (const Nom &name) const override
virtual void finir ()
double futureTime () const override
const Type_info * get_info () const override
void getInputFieldsNames (Noms &noms) const override
void getOutputFieldsNames (Noms &noms) const override
virtual void imprimer (Sortie &os) const
void initialize () override
bool initTimeStep (double dt) override
bool isStationary () const override
bool iterateTimeStep (bool &converged) override
int limpr () const override
int lsauv () const override
virtual void mettre_a_jour (double temps)
virtual Milieu_base & milieu ()
virtual const Milieu_base & milieu () const
int postraiter (int force=1) override
double presentTime () const override
int reprendre (Entree &) override
void resetTime (double time) override
int sauvegarder (Sortie &) const override
Schema_Temps_base & schema_temps ()
const Schema_Temps_base & schema_temps () const
void terminate () override
bool updateGivenFields () override
void validateTimeStep () override
virtual int verifier ()
Public Member Functions inherited from Probleme_U
virtual void abortTimeStep ()
virtual double computeTimeStep (bool &stop) const
virtual TRUST_Ref< Field_base * > findInputField (const Nom &name) const
virtual double futureTime () const
const Type_info * get_info () const override
virtual void getInputFieldsNames (Noms &noms) const
virtual void getOutputFieldsNames (Noms &noms) const
virtual void initialize ()
virtual bool initTimeStep (double dt)
virtual bool isStationary () const
virtual bool iterateTimeStep (bool &converged)
const Nom & le_nom () const override
void nommer (const Nom &name) override
virtual int postraiter (int force=1)
virtual double presentTime () const
virtual void resetTime (double time)
virtual bool run ()
virtual bool runUntil (double time)
virtual void terminate ()
virtual bool updateGivenFields ()
virtual void validateTimeStep ()
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Static Protected Member Functions
static void Fill_postprocessable_fields ()
Additional Inherited Members
Public Types inherited from Champs_compris_IJK_interface
using FieldInfo_t = std::tuple< Motcle, Entity, Nature_du_champ, bool >
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Member Typedef Documentation
FieldInfo_t
using Probleme_FTD_IJK_base::FieldInfo_t = Champs_compris_IJK_interface::FieldInfo_t
Constructor & Destructor Documentation
Probleme_FTD_IJK_base()
Probleme_FTD_IJK_base::Probleme_FTD_IJK_base ()
~Probleme_FTD_IJK_base()
Probleme_FTD_IJK_base::~Probleme_FTD_IJK_base () override
Member Function Documentation
info()
const Type_info * Probleme_FTD_IJK_base::info () static
get_info()
const Type_info * Probleme_FTD_IJK_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Probleme_FT_Disc_gen.
Reimplemented in Probleme_FTD_IJK_cut_cell.
self_cast() [1/2]
Probleme_FTD_IJK_base & Probleme_FTD_IJK_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Probleme_FTD_IJK_base & Probleme_FTD_IJK_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Probleme_FTD_IJK_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Probleme_FT_Disc_gen.
Reimplemented in Probleme_FTD_IJK_cut_cell.
References Objet_U::que_suis_je().
readOn()
Entree & Probleme_FTD_IJK_base::readOn (Entree & is) override protected virtual
Lecture d'un probleme dans un flot d'entree, et ouverture du flot de sauvegarde.
Format: { nom_milieu bloc de lecture d'un milieu nom_equation bloc de lecture d'une equation Postraitement bloc de lecture postraitement reprise | sauvegarde | sauvegarde_simple formatte | binaire | pdi nom_de_fichier } L'option sauvegarde_simple permet de sauver le probleme dans le fichier choisi en ecrasant a chaque fois les sauvegardes precedentes : cela permet d'economiser de la place disque.
Parameters
(Entree& is) flot d'entree
Returns
(Entree&) le flot d'entre modifie
Exceptions
pas d'accolade ouvrante en debut de format
mot clef "Postraitement" n'est pas la
format de sauvegarde doit etre "binaire" ou "formatte"
pas d'accolade fermante en fin de jeu de donnee
Reimplemented from Probleme_FT_Disc_gen.
Reimplemented in Probleme_FTD_IJK_cut_cell.
References completer(), Objet_U::dimension, Probleme_FT_Disc_gen::equations_, Process::exit(), Fill_postprocessable_fields(), Probleme_FT_Disc_gen::getset_equation_by_name(), Probleme_U::le_nom(), Probleme_base::les_postraitements_, Param::lire_avec_accolades(), Postraitements::lire_postraitements(), lire_solved_equations(), milieu_ijk(), Objet_U::nom_du_cas(), nom_sauvegarde_, Objet_U::que_suis_je(), set_param(), TRUST_List< _CLASSE_ >::size(), and typer_lire_milieu().
Referenced by Probleme_FTD_IJK::readOn(), and Probleme_FTD_IJK_cut_cell::readOn().
associer_()
int Probleme_FTD_IJK_base::associer_ (Objet_U & ob) override virtual
surcharge Objet_U::associer_(Objet_U& ob) Associe differents objets au probleme en controlant
le type de l'objet a associer a l'execution.
On peut ainsi associer: un schema en temps, un domaine de calcul ou
un milieu physique.
Utilise les routine de la classe Type_Info (Utilitaires)
Parameters
(Objet_U& ob) l'objet a associer
Returns
(int) 1 si association reussie 0 sinon 2 si le milieu est deja associe a un autre probleme
Exceptions
Objet_U de type inconnu (non prevu)
Reimplemented from Probleme_FT_Disc_gen.
References Probleme_FT_Disc_gen::associer_(), and domaine_ijk_.
set_param()
void Probleme_FTD_IJK_base::set_param (Param & param) virtual
Reimplemented in Probleme_FTD_IJK_cut_cell.
References Param::ajouter(), Param::ajouter_flag(), nom_reprise_, nom_sauvegarde_, and sauvegarder_xyz_.
Referenced by readOn(), and Probleme_FTD_IJK_cut_cell::set_param().
get_domaine_ft() [1/2]
const Domaine_IJK & Probleme_FTD_IJK_base::get_domaine_ft () const inline
References domaine_ft_.
Referenced by Navier_Stokes_FTD_IJK::build_redistribute_extended_splitting_ft(), Navier_Stokes_FTD_IJK::completer(), Navier_Stokes_FTD_IJK::initialise_ijk_fields(), and Navier_Stokes_FTD_IJK::initialise_ns_fields().
get_domaine_ft() [2/2]
Domaine_IJK & Probleme_FTD_IJK_base::get_domaine_ft () inline
References domaine_ft_.
get_domaine()
const Domaine_IJK & Probleme_FTD_IJK_base::get_domaine () const inline
References domaine_ijk_, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Navier_Stokes_FTD_IJK::compute_correction_for_momentum_balance().
domaine_ijk() [1/2]
const Domaine_IJK & Probleme_FTD_IJK_base::domaine_ijk () const inline
References domaine_ijk_, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Navier_Stokes_FTD_IJK::build_redistribute_extended_splitting_ft(), Navier_Stokes_FTD_IJK::calculer_dv(), Navier_Stokes_FTD_IJK::calculer_vitesse_ft(), Navier_Stokes_FTD_IJK::initialise_ijk_fields(), Navier_Stokes_FTD_IJK::initialise_ns_fields(), and Navier_Stokes_FTD_IJK::update_v_ghost_from_rho_v().
domaine_ijk() [2/2]
Domaine_IJK & Probleme_FTD_IJK_base::domaine_ijk () inline
References domaine_ijk_, and TRUST_Ref< _CLASSE_ >::valeur().
discretiser()
void Probleme_FTD_IJK_base::discretiser (Discretisation_base & dis) override virtual
Nothing to be done here for now ...
Reimplemented from Probleme_base.
References Process::exit(), and Probleme_U::le_nom().
preparer_calcul()
void Probleme_FTD_IJK_base::preparer_calcul () override virtual
Prepare le calcul: initialise les parametres du milieu et prepare le calcul de chacune des equations.
Reimplemented from Probleme_base.
References IJK_Interfaces::compute_vinterp(), IJK_Interfaces::detecter_et_supprimer_rejeton(), Option_IJK::DISABLE_DIPHASIQUE, Probleme_FT_Disc_gen::equations_, Navier_Stokes_FTD_IJK::forcage_control_ecoulement(), TRUST_List< _CLASSE_ >::front(), get_ijk_thermals(), get_interface(), get_post(), Navier_Stokes_FTD_IJK::get_suppression_rejetons(), has_thermals_, Postraitement::postraiter_sondes(), Navier_Stokes_FTD_IJK::preparer_calcul(), reprise_, schema_temps_ijk(), Schema_Temps_IJK_base::set_current_time(), Schema_Temps_IJK_base::set_modified_time_ini(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by run().
typer_lire_milieu()
void Probleme_FTD_IJK_base::typer_lire_milieu (Entree & is) override virtual
Reimplemented from Probleme_FT_Disc_gen.
References Probleme_base::le_milieu_.
Referenced by readOn().
lire_solved_equations()
void Probleme_FTD_IJK_base::lire_solved_equations (Entree & is) override virtual
Reimplemented from Probleme_FT_Disc_gen.
References TRUST_Vector< _CLASSE_ >::add(), Probleme_FT_Disc_gen::add_FT_equation(), Nom::contient(), Process::exit(), has_interface_, has_ns_, has_thermals_, Type_info::les_sous_types(), Objet_U::que_suis_je(), and Noms::rang().
Referenced by readOn().
completer()
void Probleme_FTD_IJK_base::completer () override virtual
Complete les equations associees au probleme.
Remplissage des references, deleguee aux equations.
Reimplemented from Probleme_FT_Disc_gen.
References Postprocessing_IJK::associer_domaines(), Navier_Stokes_FTD_IJK::associer_interfaces(), Postprocessing_IJK::associer_probleme(), build_vdf_domaine(), Fluide_Diphasique_IJK::calculate_direction_gravite(), Postraitements::completer(), Schema_Temps_IJK_base::completer(), domaine_ft_, domaine_ijk_, Probleme_FT_Disc_gen::equations_, fichier_post_, TRUST_List< _CLASSE_ >::front(), get_interface(), get_post(), has_interface_, lata_name_, Probleme_base::les_postraitements_, milieu_ijk(), Objet_U::nom_du_cas(), nom_reprise_, reprendre_probleme(), schema_temps_ijk(), TRUST_Deriv< _CLASSE_ >::valeur(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by readOn().
mettre_a_jour()
void Probleme_FTD_IJK_base::mettre_a_jour (double temps) inline override virtual
Effectue une mise a jour en temps du probleme.
Effectue la mise a jour sur toutes les equations du probleme.
Parameters
(double temps) le pas de temps de mise a jour
Reimplemented from Probleme_FT_Disc_gen.
updateGivenFields()
virtual bool Probleme_FTD_IJK_base::updateGivenFields () inline override virtual
ATTENTION :
Rentre ici tout ce qui ne correspond pas a l'API normale de Problem.
Actuellement on y met a jour les CLs et les termes sources, sachant que certains vont chercher eux-memes des informations dans les problemes voisins...
Programme de travail : tout ce qui est dans cette methode doit etre rendu independant de l'exterieur, et peut du coup rejoindre initTimeStep. Le reste passe dans l'interface d'echange de champs. Ce travail sera fini quand updateGivenFields sera vide et supprime !
Returns
(true=OK, false=error)
Reimplemented from Probleme_FT_Disc_gen.
milieu_ijk() [1/2]
Fluide_Diphasique_IJK & Probleme_FTD_IJK_base::milieu_ijk () inline
References Probleme_base::le_milieu_.
Referenced by completer(), Schema_Temps_IJK_base::find_timestep(), readOn(), sauver(), solveTimeStep_Euler(), solveTimeStep_RK3(), and update_indicator_field().
milieu_ijk() [2/2]
const Fluide_Diphasique_IJK & Probleme_FTD_IJK_base::milieu_ijk () const inline
References Probleme_base::le_milieu_.
schema_temps_ijk() [1/2]
const Schema_Temps_IJK_base & Probleme_FTD_IJK_base::schema_temps_ijk () const inline
References Probleme_base::le_schema_en_temps_, and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by completer(), computeTimeStep(), Probleme_FTD_IJK_cut_cell::deplacer_interfaces(), Probleme_FTD_IJK_cut_cell::deplacer_interfaces_rk3(), euler_time_step(), preparer_calcul(), Probleme_FTD_IJK_cut_cell::readOn(), reprendre_probleme(), run(), sauvegarder_probleme(), sauver(), solveTimeStep(), solveTimeStep_Euler(), solveTimeStep_RK3(), and update_indicator_field().
schema_temps_ijk() [2/2]
Schema_Temps_IJK_base & Probleme_FTD_IJK_base::schema_temps_ijk () inline
References Probleme_base::le_schema_en_temps_, and TRUST_Ref< _CLASSE_ >::valeur().
run()
bool Probleme_FTD_IJK_base::run () override virtual
Cette methode est une sorte de main() du Problem Elle peut etre utilisee si le probleme n'est couple a aucun autre.
(s'il n'a besoin d'aucun champ d'entree).
Returns
(bool) true=OK, false=error
Reimplemented from Probleme_U.
References abortTimeStep(), Statistiques::begin_count(), Schema_Temps_IJK_base::check_stop_criteria(), Statistiques::compute_avg_min_max_var_per_step(), computeTimeStep(), Objet_U::disable_TU, Statistiques::dump(), Statistiques::end_count(), Schema_Temps_IJK_base::get_max_timestep(), Postprocessing_IJK::get_max_timestep_for_post(), Schema_Temps_IJK_base::get_nb_timesteps(), get_post(), Schema_Temps_IJK_base::get_tstep(), initTimeStep(), Probleme_base::postraiter(), preparer_calcul(), Statistiques::print_communciation_tracking_details(), Statistiques::reset_counters(), sauver(), schema_temps_ijk(), Schema_Temps_IJK_base::set_max_timestep(), Schema_Temps_IJK_base::set_max_timestep_if_smaller(), Statistiques::set_three_first_steps_elapsed(), Schema_Temps_IJK_base::set_timestep(), solveTimeStep(), stop_, and validateTimeStep().
initialize()
void Probleme_FTD_IJK_base::initialize () override virtual
This method is called once at the beginning, before any other one of the interface Problem.
Exceptions
WrongContext
Reimplemented from Probleme_base.
Reimplemented in Probleme_FTD_IJK_cut_cell.
References IJK_Field_template< double, ArrOfDouble >::alloc_counter(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::allocate(), domaine_ijk_, Domaine_IJK::ELEM, Probleme_FT_Disc_gen::equations_, TRUST_List< _CLASSE_ >::front(), Probleme_base::init_postraitements(), initialise_ijk_fields(), initialise_interfaces(), Navier_Stokes_FTD_IJK::initialise_ns_fields(), Objet_U::que_suis_je(), treatment_count_, TRUST_Deriv< _CLASSE_ >::valeur(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by Probleme_FTD_IJK::initialize(), and Probleme_FTD_IJK_cut_cell::initialize().
terminate()
void Probleme_FTD_IJK_base::terminate () override virtual
This method is called once at the end, after any other one.
It frees the memory and saves anything that needs to be saved.
Exceptions
WrongContext
Reimplemented from Probleme_base.
References Sortie_Fichier_base::close(), get_post(), Process::je_suis_maitre(), and Sortie_Fichier_base::ouvrir().
sauver()
void Probleme_FTD_IJK_base::sauver () const override virtual
Ecriture sur fichier en vue d'une reprise (sauvegarde)
Reimplemented from Probleme_base.
References IJK_Interfaces::calculer_indicatrice_next(), IJK_Interfaces::creer_duplicata_bulles(), Option_IJK::DISABLE_DIPHASIQUE, Fluide_Diphasique_IJK::get_delta_rho(), Schema_Temps_IJK_base::get_dt_sauvegarde(), get_interface(), Schema_Temps_IJK_base::get_tstep(), Schema_Temps_IJK_base::get_tstep_init(), milieu_ijk(), nom_sauvegarde_, sauvegarder_probleme(), schema_temps_ijk(), Schema_Temps_IJK_base::set_tstep_sauv(), stop_, and IJK_Interfaces::supprimer_duplicata_bulles().
Referenced by run().
presentTime()
double Probleme_FTD_IJK_base::presentTime () const inline override virtual
Returns the present time.
This value may change only at the call of validateTimeStep. A surcharger
Returns
(double) present time
Exceptions
WrongContext
Reimplemented from Probleme_base.
computeTimeStep()
double Probleme_FTD_IJK_base::computeTimeStep (bool & stop) const override virtual
Compute the value the Problem would like for the next time step.
This value will not necessarily be used at the call of initTimeStep, but it is a hint. This method may use all the internal state of the Problem.
Parameters
(stop) Does the Problem want to stop ?
Returns
(double) The desired time step
Exceptions
WrongContext
Reimplemented from Probleme_base.
References Schema_Temps_IJK_base::computeTimeStep(), and schema_temps_ijk().
Referenced by run().
initTimeStep()
bool Probleme_FTD_IJK_base::initTimeStep (double dt) inline override virtual
This method allocates and initializes the unknown and given fields for the future time step.
The value of the interval is imposed through the parameter dt. In case of error, returns false.
Parameters
(double dt) the time interval to allocate
Returns
(bool) true=OK, false=error, not able to tackle this dt
Exceptions
WrongContext,WrongArgument
Reimplemented from Probleme_base.
Referenced by run().
solveTimeStep()
bool Probleme_FTD_IJK_base::solveTimeStep () override virtual
pour recodage eventuel et appel unifie en python
Reimplemented from Probleme_base.
References Postprocessing_IJK::compute_extended_pressures(), Navier_Stokes_FTD_IJK::compute_var_volume_par_bulle(), Navier_Stokes_FTD_IJK::corriger_qdm(), create_forced_dilation(), IJK_Interfaces::creer_duplicata_bulles(), Option_IJK::DISABLE_DIPHASIQUE, Probleme_FT_Disc_gen::equations_, Process::exit(), TRUST_List< _CLASSE_ >::front(), Navier_Stokes_FTD_IJK::get_boundary_conditions(), Schema_Temps_IJK_base::get_current_time(), Boundary_Conditions::get_dU_perio(), get_interface(), IJK_Interfaces::get_nb_bulles_ghost(), IJK_Interfaces::get_nb_bulles_reelles(), get_post(), Boundary_Conditions::get_t0_shear(), Objet_U::que_suis_je(), schema_temps_ijk(), Schema_Temps_IJK_base::set_current_time(), IJK_Shear_Periodic_helpler::shear_x_time_, solveTimeStep_Euler(), solveTimeStep_RK3(), t_debut_statistiques(), Postprocessing_IJK::update_stat_ft(), Navier_Stokes_FTD_IJK::update_v_or_rhov(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by run().
validateTimeStep()
void Probleme_FTD_IJK_base::validateTimeStep () override virtual
Validates the calculated unknown by moving the present time at the end of the time step.
This method is allowed to free past values of the unknown and given fields.
Exceptions
WrongContext
Reimplemented from Probleme_base.
References IJK_Interfaces::compute_vinterp(), Option_IJK::DISABLE_DIPHASIQUE, get_interface(), and get_post().
Referenced by run().
setStationary()
void Probleme_FTD_IJK_base::setStationary (bool) inline override virtual
Tells to the Problem that stationary is reached or not.
Reimplemented from Probleme_base.
abortTimeStep()
void Probleme_FTD_IJK_base::abortTimeStep () inline override virtual
Aborts the resolution of the current time step.
Exceptions
WrongContext
Reimplemented from Probleme_base.
Referenced by run().
resetTime()
void Probleme_FTD_IJK_base::resetTime (double time) inline override virtual
Reset the current time of the Problem to a given value.
Particularly useful for the initialization of complex transients: the starting point of the transient of interest is computed first, the time is reset to 0, and then the actual transient of interest starts with proper initial conditions, and global time 0.
Parameters
[in] time the new current time.
Exceptions
ICoCo::WrongContext exception if called before initialize() or after terminate().
ICoCo::WrongContext exception if called inside the TIME_STEP_DEFINED context (see Problem documentation)
Reimplemented from Probleme_base.
iterateTimeStep()
bool Probleme_FTD_IJK_base::iterateTimeStep (bool & converged) inline override virtual
In the case solveTimeStep uses an iterative process, this method executes a single iteration.
It is thus possible to modify the given fields between iterations. converged is set to true if the process has converged, ie if the unknown fields are solution to the problem on the next time step. Otherwise converged is set to false. The return value indicates if the convergence process behaves normally. If false, the Problem wishes to abort the time step resolution.
Parameters
(bool& converged) It is a return value : true if the process has converged, false otherwise.
Returns
(bool) true=OK, false=unable to converge
Exceptions
WrongContext
Reimplemented from Probleme_base.
References Probleme_base_interface_proto::iterateTimeStep_impl().
lire_equations()
Entree & Probleme_FTD_IJK_base::lire_equations (Entree & is, Motcle & dernier_mot) inline override virtual
Lecture des equations du probleme.
Reimplemented from Probleme_FT_Disc_gen.
treatment_count() [1/2]
IJK_Field_int & Probleme_FTD_IJK_base::treatment_count () inline
References treatment_count_.
treatment_count() [2/2]
const IJK_Field_int & Probleme_FTD_IJK_base::treatment_count () const inline
References treatment_count_.
new_treatment() [1/2]
int Probleme_FTD_IJK_base::new_treatment () const inline
References new_treatment_.
new_treatment() [2/2]
int & Probleme_FTD_IJK_base::new_treatment () inline
References new_treatment_.
nom_sauvegarde()
const Nom & Probleme_FTD_IJK_base::nom_sauvegarde () const inline
References nom_sauvegarde_.
Referenced by Navier_Stokes_FTD_IJK::initialise_ijk_fields().
has_champ() [1/2]
bool Probleme_FTD_IJK_base::has_champ (const Motcle & nom) const override virtual
Implements Champs_compris_IJK_interface.
References Probleme_FT_Disc_gen::equations_, get_ijk_thermals(), get_interface(), get_post(), IJK_Interfaces::has_champ(), IJK_Thermals::has_champ(), Navier_Stokes_FTD_IJK::has_champ(), Postprocessing_IJK::has_champ(), has_interface_, and has_thermals_.
Referenced by get_IJK_field().
has_champ() [2/2]
bool Probleme_FTD_IJK_base::has_champ (const Motcle & nom, TRUST_Ref< Champ_base * > & ref_champ) const inline override virtual
Reimplemented from Probleme_base.
has_champ_vectoriel()
bool Probleme_FTD_IJK_base::has_champ_vectoriel (const Motcle & nom) const override virtual
Implements Champs_compris_IJK_interface.
References Probleme_FT_Disc_gen::equations_, get_ijk_thermals(), get_interface(), get_post(), IJK_Interfaces::has_champ_vectoriel(), IJK_Thermals::has_champ_vectoriel(), Navier_Stokes_FTD_IJK::has_champ_vectoriel(), Postprocessing_IJK::has_champ_vectoriel(), has_interface_, and has_thermals_.
Referenced by get_IJK_field_vector().
get_IJK_field()
const IJK_Field_double & Probleme_FTD_IJK_base::get_IJK_field (const Motcle & nom) override virtual
Implements Champs_compris_IJK_interface.
References Probleme_FT_Disc_gen::equations_, IJK_Interfaces::get_IJK_field(), IJK_Thermals::get_IJK_field(), Navier_Stokes_FTD_IJK::get_IJK_field(), Postprocessing_IJK::get_IJK_field(), get_ijk_thermals(), get_interface(), get_post(), Navier_Stokes_FTD_IJK::has_champ(), has_champ(), has_interface_, and has_thermals_.
get_IJK_field_vector()
const IJK_Field_vector3_double & Probleme_FTD_IJK_base::get_IJK_field_vector (const Motcle & nom) override virtual
Implements Champs_compris_IJK_interface.
References Probleme_FT_Disc_gen::equations_, IJK_Interfaces::get_IJK_field_vector(), IJK_Thermals::get_IJK_field_vector(), Navier_Stokes_FTD_IJK::get_IJK_field_vector(), Postprocessing_IJK::get_IJK_field_vector(), get_ijk_thermals(), get_interface(), get_post(), Navier_Stokes_FTD_IJK::has_champ_vectoriel(), has_champ_vectoriel(), has_interface_, and has_thermals_.
initialise_ijk_fields()
void Probleme_FTD_IJK_base::initialise_ijk_fields ()
References IJK_Interfaces::allocate_ijk_compo_connex_fields(), IJK_Interfaces::associate_rising_velocities_parameters(), Navier_Stokes_FTD_IJK::complete_initialise_ijk_fields(), domaine_ijk_, eq_ns(), Probleme_FT_Disc_gen::equations_, TRUST_List< _CLASSE_ >::front(), Navier_Stokes_FTD_IJK::get_compute_rising_velocities(), Navier_Stokes_FTD_IJK::get_fill_rising_velocities(), get_ijk_thermals(), get_interface(), IJK_Thermals::get_rising_velocities_parameters(), Navier_Stokes_FTD_IJK::get_upstream_velocity_measured(), Navier_Stokes_FTD_IJK::get_use_bubbles_velocities_from_barycentres(), Navier_Stokes_FTD_IJK::get_use_bubbles_velocities_from_interface(), IJK_Thermals::ghost_fluid_flag(), has_thermals_, IJK_Interfaces::initialise_ijk_compo_connex_bubbles_params(), Navier_Stokes_FTD_IJK::initialise_ijk_fields(), IJK_Thermals::initialize(), Objet_U::que_suis_je(), TRUST_Deriv< _CLASSE_ >::valeur(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by initialize().
initialise_interfaces()
void Probleme_FTD_IJK_base::initialise_interfaces ()
References Option_IJK::DISABLE_DIPHASIQUE, domaine_ft_, domaine_ijk_, get_interface(), IJK_Interfaces::initialize(), Objet_U::que_suis_je(), refprobleme_ft_disc_, IJK_Interfaces::register_fields(), thermal_probes_ghost_cells_, update_twice_indicator_field(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by initialize().
sauvegarder_probleme()
void Probleme_FTD_IJK_base::sauvegarder_probleme (const char * fichier_sauvegarde, const int & stop)
References Statistiques::begin_count(), Option_IJK::DISABLE_DIPHASIQUE, Statistiques::end_count(), Probleme_FT_Disc_gen::equations_, TRUST_List< _CLASSE_ >::front(), Schema_Temps_IJK_base::get_current_time(), get_ijk_thermals(), get_interface(), get_post(), Schema_Temps_IJK_base::get_tstep(), Schema_Temps_IJK_base::get_tstep_init(), Navier_Stokes_FTD_IJK::get_velocity(), has_thermals_, Process::je_suis_maitre(), Sortie_Fichier_base::ouvrir(), Sortie_Fichier_base::precision(), Navier_Stokes_FTD_IJK::sauvegarder_equation(), IJK_Interfaces::sauvegarder_interfaces(), Postprocessing_IJK::sauvegarder_post(), Postprocessing_IJK::sauvegarder_post_maitre(), IJK_Thermals::sauvegarder_temperature(), sauvegarder_xyz_, schema_temps_ijk(), Sortie_Fichier_base::setf(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by sauver().
reprendre_probleme()
void Probleme_FTD_IJK_base::reprendre_probleme (const char * fichier_reprise)
References Option_IJK::DISABLE_DIPHASIQUE, Probleme_FT_Disc_gen::equations_, TRUST_List< _CLASSE_ >::front(), Navier_Stokes_FTD_IJK::get_boundary_conditions(), Schema_Temps_IJK_base::get_current_time(), Boundary_Conditions::get_dU_perio(), get_ijk_thermals(), get_interface(), get_post(), Boundary_Conditions::get_t0_shear(), has_thermals_, Param::lire_avec_accolades(), Objet_U::que_suis_je(), Postprocessing_IJK::reprendre_post(), reprise_, schema_temps_ijk(), IJK_Thermals::set_fichier_reprise(), IJK_Interfaces::set_fichier_reprise_interface(), Navier_Stokes_FTD_IJK::set_fichier_reprise_vitesse(), IJK_Interfaces::set_param_reprise_pb(), Navier_Stokes_FTD_IJK::set_param_reprise_pb(), Schema_Temps_IJK_base::set_param_reprise_pb(), IJK_Shear_Periodic_helpler::shear_x_time_, and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by completer().
update_thermal_properties()
void Probleme_FTD_IJK_base::update_thermal_properties ()
References get_ijk_thermals(), has_thermals_, and IJK_Thermals::update_thermal_properties().
Referenced by Navier_Stokes_FTD_IJK::preparer_calcul(), and Navier_Stokes_FTD_IJK::projeter().
get_thermal_probes_ghost_cells()
int Probleme_FTD_IJK_base::get_thermal_probes_ghost_cells () const inline
References thermal_probes_ghost_cells_.
Referenced by Navier_Stokes_FTD_IJK::initialise_ns_fields().
t_debut_statistiques()
double Probleme_FTD_IJK_base::t_debut_statistiques () const inline
References get_post(), and Postprocessing_IJK::t_debut_statistiques().
Referenced by solveTimeStep().
get_reprise()
bool Probleme_FTD_IJK_base::get_reprise () const inline
References reprise_.
Referenced by Navier_Stokes_FTD_IJK::calculer_terme_source_acceleration(), Navier_Stokes_FTD_IJK::compute_correction_for_momentum_balance(), Schema_Temps_IJK_base::find_timestep(), Navier_Stokes_FTD_IJK::write_check_etapes_et_termes(), and Navier_Stokes_FTD_IJK::write_qdm_corrections_information().
get_noms_champs_postraitables()
void Probleme_FTD_IJK_base::get_noms_champs_postraitables (Noms & noms, Option opt) const override virtual
Reimplemented from Probleme_base.
References TRUST_Vector< _CLASSE_ >::add(), Probleme_FT_Disc_gen::equations_, get_ijk_thermals(), get_interface(), Postprocessing_IJK::get_noms_champs_postraitables(), IJK_Interfaces::get_noms_champs_postraitables(), IJK_Thermals::get_noms_champs_postraitables(), Navier_Stokes_FTD_IJK::get_noms_champs_postraitables(), get_post(), has_interface_, has_thermals_, and TRUST_Vector< _CLASSE_ >::reset().
get_post() [1/2]
const Postprocessing_IJK & Probleme_FTD_IJK_base::get_post () const inline
References TRUST_List< _CLASSE_ >::front(), and Probleme_base::les_postraitements_.
Referenced by IJK_Thermal_base::associer(), IJK_One_Dimensional_Subproblems_Interfaces_Fields::associer(), Navier_Stokes_FTD_IJK::calculer_dv(), completer(), Navier_Stokes_FTD_IJK::fill_variable_source_and_potential_phi(), get_IJK_field(), get_IJK_field_vector(), get_noms_champs_postraitables(), has_champ(), has_champ_vectoriel(), Navier_Stokes_FTD_IJK::initialise_ijk_fields(), Probleme_FTD_IJK_cut_cell::initialize(), Navier_Stokes_FTD_IJK::preparer_calcul(), preparer_calcul(), Navier_Stokes_FTD_IJK::projeter(), reprendre_probleme(), run(), sauvegarder_probleme(), solveTimeStep(), t_debut_statistiques(), terminate(), Statistiques_dns_ijk_FT::update_stat(), and validateTimeStep().
get_post() [2/2]
Postprocessing_IJK & Probleme_FTD_IJK_base::get_post () inline
References TRUST_List< _CLASSE_ >::front(), and Probleme_base::les_postraitements_.
get_delta_z_local() [1/2]
ArrOfDouble_with_ghost & Probleme_FTD_IJK_base::get_delta_z_local () inline
References delta_z_local_.
Referenced by Navier_Stokes_FTD_IJK::calculer_dv().
get_delta_z_local() [2/2]
const ArrOfDouble_with_ghost & Probleme_FTD_IJK_base::get_delta_z_local () const inline
References delta_z_local_.
deplacer_interfaces()
void Probleme_FTD_IJK_base::deplacer_interfaces (const double timestep, const int rk_step, ArrOfDouble & var_volume_par_bulle, const int first_step_interface_smoothing) virtual
Reimplemented in Probleme_FTD_IJK_cut_cell.
References Statistiques::begin_count(), Navier_Stokes_FTD_IJK::calculer_vitesse_ft(), IJK_Thermals::clean_ijk_intersections(), IJK_Thermals::compute_eulerian_distance_curvature(), IJK_Thermals::copy_previous_interface_state(), Navier_Stokes_FTD_IJK::deplacer_interfaces(), Option_IJK::DISABLE_DIPHASIQUE, Statistiques::end_count(), Probleme_FT_Disc_gen::equations_, TRUST_List< _CLASSE_ >::front(), get_ijk_thermals(), get_interface(), has_thermals_, Statistiques::new_counter(), update_indicator_field(), IJK_Interfaces::update_indicatrice_variables_monofluides(), Navier_Stokes_FTD_IJK::update_indicatrice_variables_monofluides(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by Probleme_FTD_IJK_cut_cell::deplacer_interfaces(), and solveTimeStep_Euler().
deplacer_interfaces_rk3()
void Probleme_FTD_IJK_base::deplacer_interfaces_rk3 (const double timestep, const int rk_step, ArrOfDouble & var_volume_par_bulle) virtual
Reimplemented in Probleme_FTD_IJK_cut_cell.
References Option_IJK::DISABLE_DIPHASIQUE, Probleme_FT_Disc_gen::equations_, TRUST_List< _CLASSE_ >::front(), get_interface(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by Probleme_FTD_IJK_cut_cell::deplacer_interfaces_rk3(), and solveTimeStep_RK3().
update_indicator_field()
void Probleme_FTD_IJK_base::update_indicator_field () virtual
Reimplemented in Probleme_FTD_IJK_cut_cell.
References IJK_Interfaces::calculer_indicatrice_next(), Fluide_Diphasique_IJK::get_delta_rho(), get_interface(), milieu_ijk(), schema_temps_ijk(), and IJK_Interfaces::switch_indicatrice_next_old().
Referenced by deplacer_interfaces(), Navier_Stokes_FTD_IJK::deplacer_interfaces_rk3(), Probleme_FTD_IJK_cut_cell::update_indicator_field(), and update_twice_indicator_field().
update_twice_indicator_field()
void Probleme_FTD_IJK_base::update_twice_indicator_field () virtual
Reimplemented in Probleme_FTD_IJK_cut_cell.
References update_indicator_field(), and update_old_intersections().
Referenced by initialise_interfaces().
update_pre_remeshing_indicator_field()
void Probleme_FTD_IJK_base::update_pre_remeshing_indicator_field ()
References IJK_Interfaces::calculer_indicatrice_avant_remaillage(), and get_interface().
Referenced by Navier_Stokes_FTD_IJK::deplacer_interfaces(), and Navier_Stokes_FTD_IJK::deplacer_interfaces_rk3().
update_post_remeshing_indicator_field()
void Probleme_FTD_IJK_base::update_post_remeshing_indicator_field ()
References IJK_Interfaces::calculer_indicatrice_apres_remaillage(), and get_interface().
Referenced by Navier_Stokes_FTD_IJK::deplacer_interfaces(), and Navier_Stokes_FTD_IJK::deplacer_interfaces_rk3().
update_old_intersections()
void Probleme_FTD_IJK_base::update_old_intersections ()
References get_interface(), and IJK_Interfaces::update_old_intersections().
Referenced by Probleme_FTD_IJK_cut_cell::deplacer_interfaces(), Probleme_FTD_IJK_cut_cell::deplacer_interfaces_rk3(), update_twice_indicator_field(), and Probleme_FTD_IJK_cut_cell::update_twice_indicator_field().
parcourir_maillage()
void Probleme_FTD_IJK_base::parcourir_maillage ()
References get_interface(), IJK_Interfaces::maillage_ft_ijk(), Maillage_FT_Disc::nb_sommets(), IJK_Interfaces::parcourir_maillage(), IJK_Interfaces::RK3_G_store_vi_echange_esp_vect(), and IJK_Interfaces::RK3_G_store_vi_resize().
Referenced by Navier_Stokes_FTD_IJK::maj_indicatrice_rho_mu(), solveTimeStep_Euler(), and solveTimeStep_RK3().
calculer_rho_mu_indicatrice()
void Probleme_FTD_IJK_base::calculer_rho_mu_indicatrice (const bool parcourir = true)
get_lata_name()
const Nom & Probleme_FTD_IJK_base::get_lata_name () const inline
References lata_name_.
probleme()
const Probleme_base & Probleme_FTD_IJK_base::probleme (const Domaine_IJK & dom) const inline
References domaine_ft_, Process::exit(), refprobleme_ft_disc_, and TRUST_Ref< _CLASSE_ >::valeur().
get_cut_cell_disc()
virtual Cut_cell_FT_Disc * Probleme_FTD_IJK_base::get_cut_cell_disc () inline virtual
Reimplemented in Probleme_FTD_IJK_cut_cell.
References Process::exit().
has_ns()
bool Probleme_FTD_IJK_base::has_ns () const inline
References has_ns_.
has_interface()
bool Probleme_FTD_IJK_base::has_interface () const inline
References has_interface_.
Referenced by Navier_Stokes_FTD_IJK::calculer_dv(), and Schema_Temps_IJK_base::find_timestep().
has_thermals()
bool Probleme_FTD_IJK_base::has_thermals () const inline
References has_thermals_.
Referenced by Schema_Temps_IJK_base::find_timestep().
eq_ns() [1/2]
const Navier_Stokes_FTD_IJK & Probleme_FTD_IJK_base::eq_ns () const inline
References Probleme_FT_Disc_gen::equations_, TRUST_List< _CLASSE_ >::front(), has_ns_, and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by Schema_Temps_IJK_base::find_timestep(), initialise_ijk_fields(), Probleme_FTD_IJK::initialize(), Probleme_FTD_IJK_cut_cell::initialize(), and Statistiques_dns_ijk_FT::update_stat().
eq_ns() [2/2]
Navier_Stokes_FTD_IJK & Probleme_FTD_IJK_base::eq_ns () inline
References Probleme_FT_Disc_gen::equations_, TRUST_List< _CLASSE_ >::front(), has_ns_, and TRUST_Deriv< _CLASSE_ >::valeur().
get_interface() [1/2]
const IJK_Interfaces & Probleme_FTD_IJK_base::get_interface () const inline
References Probleme_FT_Disc_gen::equations_, has_interface_, and interface_to_remove_later_when_clean_.
Referenced by completer(), Probleme_FTD_IJK_cut_cell::cut_cell_perform_interpolation_facettes(), deplacer_interfaces(), Probleme_FTD_IJK_cut_cell::deplacer_interfaces(), deplacer_interfaces_rk3(), Probleme_FTD_IJK_cut_cell::deplacer_interfaces_rk3(), get_IJK_field(), get_IJK_field_vector(), get_maillage_ft_ijk(), get_noms_champs_postraitables(), get_remaillage_ft_ijk(), has_champ(), has_champ_vectoriel(), initialise_ijk_fields(), initialise_interfaces(), Probleme_FTD_IJK_cut_cell::initialize(), parcourir_maillage(), preparer_calcul(), Probleme_FTD_IJK_cut_cell::readOn(), reprendre_probleme(), sauvegarder_probleme(), sauver(), solveTimeStep(), solveTimeStep_Euler(), solveTimeStep_RK3(), update_indicator_field(), Probleme_FTD_IJK_cut_cell::update_indicator_field(), update_old_intersections(), update_post_remeshing_indicator_field(), update_pre_remeshing_indicator_field(), Probleme_FTD_IJK_cut_cell::update_twice_indicator_field(), and validateTimeStep().
get_interface() [2/2]
IJK_Interfaces & Probleme_FTD_IJK_base::get_interface () inline
References Probleme_FT_Disc_gen::equations_, has_interface_, and interface_to_remove_later_when_clean_.
get_maillage_ft_ijk()
const Maillage_FT_IJK & Probleme_FTD_IJK_base::get_maillage_ft_ijk () const inline
References get_interface(), has_interface_, and IJK_Interfaces::maillage_ft_ijk().
get_remaillage_ft_ijk()
const Remaillage_FT_IJK & Probleme_FTD_IJK_base::get_remaillage_ft_ijk () const inline
References get_interface(), has_interface_, and IJK_Interfaces::remaillage_ft_ijk().
Referenced by Schema_Temps_IJK_base::find_timestep().
get_ijk_thermals() [1/2]
const IJK_Thermals & Probleme_FTD_IJK_base::get_ijk_thermals () const inline
References Probleme_FT_Disc_gen::equations_, has_interface_, and has_thermals_.
Referenced by deplacer_interfaces(), Probleme_FTD_IJK_cut_cell::deplacer_interfaces(), Probleme_FTD_IJK_cut_cell::deplacer_interfaces_rk3(), euler_time_step(), Schema_Temps_IJK_base::find_timestep(), get_IJK_field(), get_IJK_field_vector(), get_noms_champs_postraitables(), has_champ(), has_champ_vectoriel(), initialise_ijk_fields(), Probleme_FTD_IJK::initialize(), Probleme_FTD_IJK_cut_cell::initialize(), preparer_calcul(), reprendre_probleme(), rk3_sub_step(), sauvegarder_probleme(), solveTimeStep_Euler(), solveTimeStep_RK3(), and update_thermal_properties().
get_ijk_thermals() [2/2]
IJK_Thermals & Probleme_FTD_IJK_base::get_ijk_thermals () inline
References Probleme_FT_Disc_gen::equations_, has_interface_, and has_thermals_.
euler_time_step()
void Probleme_FTD_IJK_base::euler_time_step (ArrOfDouble & var_volume_par_bulle) protected
References Statistiques::begin_count(), Statistiques::end_count(), Probleme_FT_Disc_gen::equations_, Navier_Stokes_FTD_IJK::euler_time_step(), IJK_Thermals::euler_time_step(), TRUST_List< _CLASSE_ >::front(), get_ijk_thermals(), has_thermals_, Statistiques::new_counter(), schema_temps_ijk(), Navier_Stokes_FTD_IJK::update_v_or_rhov(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by solveTimeStep_Euler().
rk3_sub_step()
void Probleme_FTD_IJK_base::rk3_sub_step (const int rk_step, const double total_timestep, const double fractionnal_timestep, const double time) protected
References Statistiques::begin_count(), Statistiques::end_count(), Probleme_FT_Disc_gen::equations_, TRUST_List< _CLASSE_ >::front(), get_ijk_thermals(), has_thermals_, Statistiques::new_counter(), IJK_Thermals::rk3_sub_step(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by solveTimeStep_RK3().
create_forced_dilation()
virtual void Probleme_FTD_IJK_base::create_forced_dilation () inline protected virtual
Reimplemented in Probleme_FTD_IJK.
Referenced by solveTimeStep().
solveTimeStep_Euler()
void Probleme_FTD_IJK_base::solveTimeStep_Euler (DoubleTrav & var_volume_par_bulle) protected
References Navier_Stokes_FTD_IJK::calculer_terme_source_acceleration(), Navier_Stokes_FTD_IJK::compute_var_volume_par_bulle(), IJK_Interfaces::creer_duplicata_bulles(), deplacer_interfaces(), Option_IJK::DISABLE_DIPHASIQUE, Probleme_FT_Disc_gen::equations_, IJK_Thermals::euler_rustine_step(), euler_time_step(), TRUST_List< _CLASSE_ >::front(), Schema_Temps_IJK_base::get_first_step_interface_smoothing(), get_ijk_thermals(), get_interface(), has_thermals_, Navier_Stokes_FTD_IJK::maj_indicatrice_rho_mu(), milieu_ijk(), parcourir_maillage(), schema_temps_ijk(), IJK_Thermals::set_post_pro_first_call(), IJK_Thermals::set_temperature_ini(), IJK_Interfaces::supprimer_duplicata_bulles(), Navier_Stokes_FTD_IJK::test_etapes_et_bilan_rho_u_euler(), IJK_Interfaces::transferer_bulle_perio(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by solveTimeStep().
solveTimeStep_RK3()
void Probleme_FTD_IJK_base::solveTimeStep_RK3 (DoubleTrav & var_volume_par_bulle) protected
References Navier_Stokes_FTD_IJK::calculer_terme_source_acceleration(), IJK_Interfaces::creer_duplicata_bulles(), deplacer_interfaces_rk3(), Option_IJK::DISABLE_DIPHASIQUE, Probleme_FT_Disc_gen::equations_, TRUST_List< _CLASSE_ >::front(), Schema_Temps_IJK_base::get_current_time(), Schema_RK3_IJK::get_current_time_at_rk3_step(), get_ijk_thermals(), get_interface(), Schema_RK3_IJK::get_rk_step(), Schema_Temps_IJK_base::get_timestep(), has_thermals_, Navier_Stokes_FTD_IJK::maj_indicatrice_rho_mu(), milieu_ijk(), parcourir_maillage(), IJK_Thermals::rk3_rustine_sub_step(), rk3_sub_step(), schema_temps_ijk(), IJK_Interfaces::supprimer_duplicata_bulles(), Navier_Stokes_FTD_IJK::test_etapes_et_bilan_rho_u_euler(), IJK_Interfaces::transferer_bulle_perio(), IJK_Thermals::update_thermal_properties(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by solveTimeStep().
build_vdf_domaine()
void Probleme_FTD_IJK_base::build_vdf_domaine () protected
References domaine_ft_, domaine_ijk_, Probleme_FT_Disc_gen::equations_, TRUST_List< _CLASSE_ >::front(), refprobleme_ft_disc_, refprobleme_ns_, TRUST_Deriv< _CLASSE_ >::valeur(), and TRUST_Ref< _CLASSE_ >::valeur().
Referenced by completer().
Fill_postprocessable_fields()
void Probleme_FTD_IJK_base::Fill_postprocessable_fields () static protected
Fills in all possible fields that may be post-processed. Done only once even if multiple problems.
References Objet_U::dimension, IJK_Interfaces::Fill_postprocessable_fields(), IJK_Thermals::Fill_postprocessable_fields(), Navier_Stokes_FTD_IJK::Fill_postprocessable_fields(), Postprocessing_IJK::Fill_postprocessable_fields(), Statistiques_dns_ijk::Fill_postprocessable_fields(), IJK_Ghost_Fluid_Fields::Fill_postprocessable_fields(), and Postprocessing_IJK::Get_champs_postraitables().
Referenced by readOn().
Friends And Related Function Documentation
IJK_Thermique_cut_cell
friend class IJK_Thermique_cut_cell friend
Statistiques_dns_ijk_FT
friend class Statistiques_dns_ijk_FT friend
Postprocessing_IJK
friend class Postprocessing_IJK friend
Member Data Documentation
info_obj
const Type_info Probleme_FTD_IJK_base::info_obj static
interface_to_remove_later_when_clean_
IJK_Interfaces Probleme_FTD_IJK_base::interface_to_remove_later_when_clean_ protected
Referenced by get_interface().
has_interface_
bool Probleme_FTD_IJK_base::has_interface_ = false protected
Referenced by completer(), get_IJK_field(), get_IJK_field_vector(), get_ijk_thermals(), get_interface(), get_maillage_ft_ijk(), get_noms_champs_postraitables(), get_remaillage_ft_ijk(), has_champ(), has_champ_vectoriel(), has_interface(), and lire_solved_equations().
has_ns_
bool Probleme_FTD_IJK_base::has_ns_ = false protected
Referenced by eq_ns(), has_ns(), and lire_solved_equations().
has_thermals_
bool Probleme_FTD_IJK_base::has_thermals_ = false protected
Referenced by deplacer_interfaces(), Probleme_FTD_IJK_cut_cell::deplacer_interfaces(), Probleme_FTD_IJK_cut_cell::deplacer_interfaces_rk3(), euler_time_step(), get_IJK_field(), get_IJK_field_vector(), get_ijk_thermals(), get_noms_champs_postraitables(), has_champ(), has_champ_vectoriel(), has_thermals(), initialise_ijk_fields(), Probleme_FTD_IJK::initialize(), Probleme_FTD_IJK_cut_cell::initialize(), lire_solved_equations(), preparer_calcul(), reprendre_probleme(), rk3_sub_step(), sauvegarder_probleme(), solveTimeStep_Euler(), solveTimeStep_RK3(), and update_thermal_properties().
delta_z_local_
ArrOfDouble_with_ghost Probleme_FTD_IJK_base::delta_z_local_ protected
Referenced by get_delta_z_local(), Probleme_FTD_IJK::initialize(), and Probleme_FTD_IJK_cut_cell::initialize().
domaine_ijk_
TRUST_Ref< Domaine_IJK *> Probleme_FTD_IJK_base::domaine_ijk_ protected
Referenced by associer_(), build_vdf_domaine(), completer(), domaine_ijk(), get_domaine(), initialise_ijk_fields(), initialise_interfaces(), Probleme_FTD_IJK::initialize(), initialize(), and Probleme_FTD_IJK_cut_cell::initialize().
domaine_ft_
Domaine_IJK Probleme_FTD_IJK_base::domaine_ft_ protected
Referenced by build_vdf_domaine(), completer(), get_domaine_ft(), initialise_interfaces(), Probleme_FTD_IJK_cut_cell::initialize(), and probleme().
lata_name_
Nom Probleme_FTD_IJK_base::lata_name_ protected
Referenced by completer(), and get_lata_name().
stop_
bool Probleme_FTD_IJK_base::stop_ = false protected
Referenced by run(), and sauver().
fichier_post_
Nom Probleme_FTD_IJK_base::fichier_post_ protected
Referenced by completer().
nom_sauvegarde_
Nom Probleme_FTD_IJK_base::nom_sauvegarde_ protected
Referenced by nom_sauvegarde(), readOn(), sauver(), and set_param().
nom_reprise_
Nom Probleme_FTD_IJK_base::nom_reprise_ protected
Referenced by completer(), and set_param().
sauvegarder_xyz_
bool Probleme_FTD_IJK_base::sauvegarder_xyz_ = false protected
Referenced by sauvegarder_probleme(), and set_param().
reprise_
bool Probleme_FTD_IJK_base::reprise_ = false protected
Referenced by get_reprise(), preparer_calcul(), and reprendre_probleme().
refprobleme_ft_disc_
TRUST_Ref< Probleme_base *> Probleme_FTD_IJK_base::refprobleme_ft_disc_ protected
Referenced by build_vdf_domaine(), initialise_interfaces(), and probleme().
refprobleme_ns_
TRUST_Ref< Probleme_base *> Probleme_FTD_IJK_base::refprobleme_ns_ protected
Referenced by build_vdf_domaine().
treatment_count_
IJK_Field_int Probleme_FTD_IJK_base::treatment_count_ protected
Referenced by initialize(), and treatment_count().
new_treatment_
int Probleme_FTD_IJK_base::new_treatment_ = 0 protected
Referenced by new_treatment().
thermal_probes_ghost_cells_
int Probleme_FTD_IJK_base::thermal_probes_ghost_cells_ = 2 protected
Referenced by get_thermal_probes_ghost_cells(), initialise_interfaces(), Probleme_FTD_IJK::initialize(), and Probleme_FTD_IJK_cut_cell::initialize().