TrioCFD: ArrOfBit_32_64< _SIZE_ > Class Template Reference
ArrOfBit_32_64< _SIZE_ > Class Template Reference
#include <ArrOfBit.h>
Public Member Functions
const Type_info * get_info () const override
ArrOfBit_32_64 & resize_array (int_t n)
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Member Typedef Documentation
int_t
template<typename _SIZE_ > using ArrOfBit_32_64< _SIZE_ >::int_t = _SIZE_
Constructor & Destructor Documentation
ArrOfBit_32_64() [1/2]
template<typename _SIZE_ > ArrOfBit_32_64< _SIZE_ >::ArrOfBit_32_64 (int_t n = 0)
Constructeur d'un tableau de taille n, non initialise.
ArrOfBit_32_64() [2/2]
template<typename _SIZE_ > ArrOfBit_32_64< _SIZE_ >::ArrOfBit_32_64 (const ArrOfBit_32_64< _SIZE_ > & array)
Constructeur par copie (deep copy)
~ArrOfBit_32_64()
template<typename _SIZE_ > ArrOfBit_32_64< _SIZE_ >::~ArrOfBit_32_64 override
Destructeur.
Member Function Documentation
cree_instance()
template<typename _T_ > Objet_U * ArrOfBit_32_64< _T_ >::cree_instance static
taille_memoire()
template<typename _T_ > unsigned ArrOfBit_32_64< _T_ >::taille_memoire override virtual
Implements Objet_U.
duplique()
template<typename _T_ > int ArrOfBit_32_64< _T_ >::duplique override virtual
Implements Objet_U.
info()
template<typename _T_ > const Type_info * ArrOfBit_32_64< _T_ >::info static
get_info()
template<typename _T_ > const Type_info * ArrOfBit_32_64< _T_ >::get_info override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
self_cast() [1/2]
template<typename _T_ > ArrOfBit_32_64< _T_ > & ArrOfBit_32_64< _T_ >::self_cast (Objet_U & r) static
self_cast() [2/2]
template<typename _T_ > const ArrOfBit_32_64< _T_ > & ArrOfBit_32_64< _T_ >::self_cast (const Objet_U & r) static
printOn()
template<typename _SIZE_ > Sortie & ArrOfBit_32_64< _SIZE_ >::printOn (Sortie & os) const override protected virtual
Ecriture du tableau.
Format: n 0 1 0 0 1 0 ... (n valeurs)
Reimplemented from Objet_U.
readOn()
template<typename _SIZE_ > Entree & ArrOfBit_32_64< _SIZE_ >::readOn (Entree & is) override protected virtual
Lecture du tableau.
Format: n 0 1 0 0 1 0 ... (n valeurs)
Reimplemented from Objet_U.
operator=() [1/2]
template<typename _SIZE_ > ArrOfBit_32_64< _SIZE_ > & ArrOfBit_32_64< _SIZE_ >::operator= (const ArrOfBit_32_64< _SIZE_ > & array)
Operateur copie (deep copy).
References ArrOfBit_32_64< _SIZE_ >::data, and ArrOfBit_32_64< _SIZE_ >::taille.
operator=() [2/2]
template<typename _SIZE_ > ArrOfBit_32_64< _SIZE_ > & ArrOfBit_32_64< _SIZE_ >::operator= (int_t i)
Si la valeur est non nulle, met la valeur 1 dans tous les elements du tableau, sinon met la valeur 0.
operator[]()
template<typename _SIZE_ > int ArrOfBit_32_64< _SIZE_ >::operator[] (int_t i) const inline
Renvoie 1 si le bit e est mis, 0 sinon.
setbit()
template<typename _SIZE_ > void ArrOfBit_32_64< _SIZE_ >::setbit (int_t i) const inline
Met le bit e a 1.
Referenced by Maillage_FT_Disc::calcul_indicatrice(), Marching_Cubes::calculer_signe(), Matrice_Morse::check_morse_matrix_structure(), Matrice_Morse::check_sorted_morse_matrix_structure(), Op_Diff_VEFP1NCP1B_Face::isFaceOfSymetry(), Op_Diff_VEFP1NCP1B_Face::liste_face(), Convection_Diffusion_Concentration_FT_Disc::marquer_faces_sous_domaine(), Convection_Diffusion_Concentration_Turbulent_FT_Disc::marquer_faces_sous_domaine(), and Parcours_interface::parcours_facette().
testsetbit()
template<typename _SIZE_ > int ArrOfBit_32_64< _SIZE_ >::testsetbit (int_t i) const inline
Renvoie la valeur du bit e, puis met le bit e a 1.
Referenced by Maillage_FT_Disc::calcul_courbure_sommets(), Raccord_distant_homogene_32_64< _SIZE_ >::completer(), Scatter::construire_md_vector(), Corriger_frontiere_periodique_32_64< _SIZE_ >::corriger_coordonnees_sommets_perio(), Remailleur_Collision_FT_Thomas::elements_voisins(), Parcours_interface::parcours_facette(), Transport_Interfaces_FT_Disc::projete_point_face_fluide(), Transport_Interfaces_FT_Disc::projete_point_face_interface(), Champ_Don_Face_lu::readOn(), Transport_Interfaces_FT_Disc::StockageFa7(), and Topologie_Maillage_FT::test_collision_facettes().
clearbit()
template<typename _SIZE_ > void ArrOfBit_32_64< _SIZE_ >::clearbit (int_t i) const inline
Met le bit e a 0.
Referenced by Maillage_FT_Disc::calcul_indicatrice(), Remailleur_Collision_FT_Thomas::elements_voisins(), MD_Vector_base::get_seq_flags_impl(), and Topologie_Maillage_FT::test_collision_facettes().
size_array()
template<typename _SIZE_ > int_t ArrOfBit_32_64< _SIZE_ >::size_array () const inline
Renvoie la taille du tableau en bits.
References ArrOfBit_32_64< _SIZE_ >::taille.
Referenced by Op_Diff_VEFP1NCP1B_Face::isFaceOfSymetry().
resize_array()
template<typename _SIZE_ > ArrOfBit_32_64< _SIZE_ > & ArrOfBit_32_64< _SIZE_ >::resize_array (int_t n)
Change la taille du tableau et copie les donnees existantes.
Si la taille est plus petite, les donnees sont tronquees, et si la taille est plus grande, les nouveaux elements ne sont pas initialises.
Referenced by Parcours_interface::associer_domaine_dis(), Maillage_FT_Disc::calcul_courbure_sommets(), Maillage_FT_Disc::calcul_indicatrice(), Marching_Cubes::calculer_signe(), Remailleur_Collision_FT_Thomas::construire_voisinage_sommet(), MD_Vector_seq::get_seq_flags_impl(), MD_Vector_base::get_sequential_items_flags(), Convection_Diffusion_Concentration_FT_Disc::marquer_faces_sous_domaine(), and Convection_Diffusion_Concentration_Turbulent_FT_Disc::marquer_faces_sous_domaine().
calculer_int_size()
template<typename _SIZE_ > ArrOfBit_32_64< _SIZE_ >::int_t ArrOfBit_32_64< _SIZE_ >::calculer_int_size (int_t taille) const protected
Taille en "int" du tableau requis pour stocker un tableau de bits de taille donnees.
info_obj()
const Type_info ArrOfBit_32_64< trustIdType >::info_obj ("ArrOfBit" "_64" , ArrOfBit_32_64< trustIdType >::cree_instance , 1 , ArrOfBit_32_64bases< trustIdType >)
Member Data Documentation
info_obj
template<typename _SIZE_ > const Type_info ArrOfBit_32_64< _SIZE_ >::info_obj static
taille
template<typename _SIZE_ > int_t ArrOfBit_32_64< _SIZE_ >::taille protected
Referenced by ArrOfBit_32_64< _SIZE_ >::operator=(), and ArrOfBit_32_64< _SIZE_ >::size_array().
data
template<typename _SIZE_ > unsigned int* ArrOfBit_32_64< _SIZE_ >::data protected
Referenced by ArrOfBit_32_64< _SIZE_ >::operator=().
SIZE_OF_INT_BITS
template<typename _SIZE_ > constexpr unsigned int ArrOfBit_32_64< _SIZE_ >::SIZE_OF_INT_BITS = 5 static constexpr protected
DRAPEAUX_INT
template<typename _SIZE_ > constexpr unsigned int ArrOfBit_32_64< _SIZE_ >::DRAPEAUX_INT = 31 static constexpr protected