TrioCFD: Op_Conv_VEF_base Class Reference
Op_Conv_VEF_base Class Reference
#include <Op_Conv_VEF_base.h>
Public Member Functions
double calculer_dt_stab () const override
const Type_info * get_info () const override
int impr (Sortie &os) const override
const Type_info * get_info () const override
Public Member Functions inherited from Operateur_base
void associer_eqn (const Equation_base &)
virtual double calculer_dt_stab () const
virtual void completer ()
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
const Type_info * get_info () const override
virtual int impr (Sortie &os) const
virtual void mettre_a_jour (double temps)
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Op_VEF_Face
void dimensionner (const Domaine_VEF &, const Domaine_Cl_VEF &, Matrice_Morse &) const
void modifier_matrice_pour_periodique_apres_contribuer (Matrice_Morse &matrice, const Equation_base &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
Classe de base des operateurs de convection VEF
Constructor & Destructor Documentation
Op_Conv_VEF_base()
Op_Conv_VEF_base::Op_Conv_VEF_base ()
~Op_Conv_VEF_base()
Op_Conv_VEF_base::~Op_Conv_VEF_base () override
Member Function Documentation
info()
const Type_info * Op_Conv_VEF_base::info () static
get_info()
const Type_info * Op_Conv_VEF_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Operateur_Conv_base.
Reimplemented in Op_Conv_RT_VEF_Face, Op_Conv_VEF_Face, Op_Conv_Vort_VEF_Face, OpVEF_Centre, OpVEF_Centre4, and OpVEF_Quick.
self_cast() [1/2]
Op_Conv_VEF_base & Op_Conv_VEF_base::self_cast (Objet_U & r) static
self_cast() [2/2]
const Op_Conv_VEF_base & Op_Conv_VEF_base::self_cast (const Objet_U & r) static
printOn()
Sortie & Op_Conv_VEF_base::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN A surcharger dans les classes derivees.
Parameters
(Sortie& os) un flot de sortie
Returns
(Sortie&) le flot de sortie
Reimplemented from Operateur_Conv_base.
Reimplemented in Op_Conv_RT_VEF_Face, Op_Conv_VEF_Face, Op_Conv_Vort_VEF_Face, OpVEF_Centre, OpVEF_Centre4, and OpVEF_Quick.
References Objet_U::que_suis_je().
readOn()
Entree & Op_Conv_VEF_base::readOn (Entree & is) override protected virtual
NE FAIT RIEN A surcharger dans les classes derivees.
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree
Reimplemented from Operateur_Conv_base.
Reimplemented in Op_Conv_RT_VEF_Face, Op_Conv_VEF_Face, Op_Conv_Vort_VEF_Face, OpVEF_Centre, OpVEF_Centre4, and OpVEF_Quick.
associer_vitesse()
void Op_Conv_VEF_base::associer_vitesse (const Champ_base & vit) override virtual
Implements Operateur_Conv_base.
References vitesse_.
vitesse() [1/2]
const Champ_Inc_base & Op_Conv_VEF_base::vitesse () const inline
References TRUST_Ref< _CLASSE_ >::valeur(), and vitesse_.
Referenced by Op_Conv_Amont_old_VEF_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Conv_RT_VEF_Face::ajouter(), Op_Conv_Amont_old_VEF_Face::ajouter_contribution(), Op_Conv_VEF_Face::ajouter_contribution(), Op_Conv_RT_VEF_Face::ajouter_contribution(), calculer_dt_stab(), calculer_pour_post(), Op_Conv_VEF_Face::contribue_au_second_membre(), and Op_Conv_VEF_Face::remplir_fluent().
vitesse() [2/2]
Champ_Inc_base & Op_Conv_VEF_base::vitesse () inline
References TRUST_Ref< _CLASSE_ >::valeur(), and vitesse_.
associer()
void Op_Conv_VEF_base::associer (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_cl_dis, const Champ_Inc_base &) override virtual
Implements Operateur_base.
References fluent_, la_zcl_vef, le_dom_vef, and roue.
Referenced by Op_Conv_kschemas_VEF::associer().
calculer()
DoubleTab & Op_Conv_VEF_base::calculer (const DoubleTab & transporte, DoubleTab & resu) const override virtual
Reimplemented from Operateur_base.
References Operateur_base::ajouter().
abortTimeStep()
void Op_Conv_VEF_base::abortTimeStep () override virtual
Reimplemented from Operateur_base.
References Operateur_base::abortTimeStep().
calculer_dt_stab()
double Op_Conv_VEF_base::calculer_dt_stab () const override virtual
Calcul dt_stab.
Returns
(double) renvoie toujours 1.e30
Reimplemented from Operateur_base.
References MorEqn::equation(), faces_entrelaces_Cl_, Operateur_Conv_base::fixer_dt_stab_conv(), fluent_, la_zcl_vef, le_dom_vef, Objet_U::le_nom(), Domaine_Cl_dis_base::les_conditions_limites(), Process::mp_min(), Domaine_VF::nb_faces(), Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), Domaine_VF::premiere_face_int(), Domaine_VEF::premiere_face_std(), remplir_fluent(), TRUSTArray< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), TRUSTArray< _TYPE_, _SIZE_ >::view_ro(), vitesse(), Domaine_VF::volumes_entrelaces(), and Domaine_Cl_VEF::volumes_entrelaces_Cl().
Referenced by Op_Conv_Muscl_New_VEF_Face::calculer_dt_stab().
calculer_dt_local()
void Op_Conv_VEF_base::calculer_dt_local (DoubleTab & dt_face) const override virtual
Reimplemented from Operateur_base.
References TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Periodique::face_associee(), fluent_, la_zcl_vef, le_dom_vef, Domaine_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_, _SIZE_ >::mp_max_abs_vect(), Domaine_VF::nb_faces(), Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_face(), Front_VF::num_premiere_face(), Domaine_VF::premiere_face_int(), Domaine_VEF::premiere_face_std(), remplir_fluent(), TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), Domaine_VF::volumes_entrelaces(), and Domaine_Cl_VEF::volumes_entrelaces_Cl().
calculer_pour_post()
void Op_Conv_VEF_base::calculer_pour_post (Champ_base & espace_stockage, const Nom & option, int comp) const override virtual
Reimplemented from Operateur_base.
References Operateur_base::calculer_pour_post(), MorEqn::equation(), fluent_, la_zcl_vef, le_dom_vef, Objet_U::le_nom(), Domaine_Cl_dis_base::les_conditions_limites(), Domaine_VF::nb_faces(), Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), TRUST_Ref< _CLASSE_ >::non_nul(), Front_VF::num_premiere_face(), Domaine_VF::premiere_face_int(), Domaine_VEF::premiere_face_std(), remplir_fluent(), TRUST_Deriv< _CLASSE_ >::valeur(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_Proto::valeurs(), vitesse(), Domaine_VF::volumes_entrelaces(), and Domaine_Cl_VEF::volumes_entrelaces_Cl().
get_localisation_pour_post()
Motcle Op_Conv_VEF_base::get_localisation_pour_post (const Nom & option) const override virtual
Reimplemented from Operateur_base.
References Operateur_base::get_localisation_pour_post().
remplir_fluent()
void Op_Conv_VEF_base::remplir_fluent () const virtual
Reimplemented in Op_Conv_EF_VEF_P1NC_Stab, Op_Conv_Muscl_New_VEF_Face, and Op_Conv_VEF_Face.
References Operateur_base::ajouter(), MorEqn::equation(), and Operateur_base::flux_bords_.
Referenced by calculer_dt_local(), calculer_dt_stab(), and calculer_pour_post().
impr()
int Op_Conv_VEF_base::impr (Sortie & os) const override virtual
DOES NOTHING - to override in derived classes.
Imprime l'operateur sur un flot de sortie.
Parameters
(Sortie& os)
Returns
(int) renvoie toujours 1
Reimplemented from Operateur_base.
References Op_VEF_Face::impr().
associer_domaine_cl_dis()
void Op_Conv_VEF_base::associer_domaine_cl_dis (const Domaine_Cl_dis_base & domaine_cl_dis) override virtual
Reimplemented from Operateur_base.
References la_zcl_vef.
phi_u_transportant()
int Op_Conv_VEF_base::phi_u_transportant (const Equation_base & eq) const
definit si l'on convecte psi avec phi*u ou avec u
References Equation_base::inconnue(), and Field_base::le_nom().
Referenced by Op_Conv_EF_VEF_P1NC::ajouter(), Op_Conv_EF_VEF_P1NC_Stab::ajouter(), Op_Conv_Muscl_New_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter_contribution(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution(), Op_Conv_RT_VEF_Face::ajouter_contribution(), Operateur_Conv_sensibility_VEF::ajouter_conv_term(), Op_Conv_ALE_VEF::ajouterALE(), Op_Conv_Muscl_New_VEF_Face::calculer_dt_stab(), and Op_Conv_VEF_Face::remplir_fluent().
Member Data Documentation
info_obj
const Type_info Op_Conv_VEF_base::info_obj static
le_dom_vef
TRUST_Ref< Domaine_VEF *> Op_Conv_VEF_base::le_dom_vef protected
Referenced by Op_Conv_Amont_old_VEF_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Centre_EF_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_EF_VEF_P1NC::ajouter(), Op_Conv_EF_VEF_P1NC_Stab::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_Muscl_New_VEF_Face::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Conv_Vort_VEF_Face::ajouter(), Op_Conv_RT_VEF_Face::ajouter(), Op_Conv_Amont_old_VEF_Face::ajouter_contribution(), Op_Conv_VEF_Face::ajouter_contribution(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution(), Op_Conv_RT_VEF_Face::ajouter_contribution(), Op_Conv_Centre_old_VEF_Face::associer(), associer(), calculer_dt_local(), Op_Conv_Muscl_New_VEF_Face::calculer_dt_stab(), calculer_dt_stab(), calculer_pour_post(), Op_Conv_EF_VEF_P1NC_Stab::completer(), Op_Conv_VEF_Face::completer(), Op_Conv_Amont_old_VEF_Face::contribue_au_second_membre(), Op_Conv_VEF_Face::contribue_au_second_membre(), Op_Conv_kschemas_centre_VEF::convkschemas_centre(), Op_Conv_Amont_old_VEF_Face::dimensionner(), Op_Conv_EF_VEF_P1NC::dimensionner(), Op_Conv_VEF_Face::dimensionner(), Op_Conv_Amont_old_VEF_Face::modifier_pour_Cl(), Op_Conv_EF_VEF_P1NC::modifier_pour_Cl(), Op_Conv_VEF_Face::modifier_pour_Cl(), Op_Conv_DI_L2_VEF_Face::poly_DI_L2_2d(), Op_Conv_DI_L2_VEF_Face::poly_DI_L2_3d(), Op_Conv_DI_L2_VEF_Face::reconst_DI_L2_2d(), Op_Conv_DI_L2_VEF_Face::reconst_DI_L2_3d(), Op_Conv_EF_VEF_P1NC_Stab::remplir_fluent(), Op_Conv_Muscl_New_VEF_Face::remplir_fluent(), and Op_Conv_VEF_Face::remplir_fluent().
la_zcl_vef
TRUST_Ref< Domaine_Cl_VEF *> Op_Conv_VEF_base::la_zcl_vef protected
Referenced by Op_Conv_Amont_old_VEF_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Centre_EF_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_EF_VEF_P1NC::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Conv_Vort_VEF_Face::ajouter(), Op_Conv_RT_VEF_Face::ajouter(), Op_Conv_Amont_old_VEF_Face::ajouter_contribution(), Op_Conv_VEF_Face::ajouter_contribution(), Op_Conv_RT_VEF_Face::ajouter_contribution(), Op_Conv_Centre_old_VEF_Face::associer(), associer(), associer_domaine_cl_dis(), calculer_dt_local(), Op_Conv_Muscl_New_VEF_Face::calculer_dt_stab(), calculer_dt_stab(), calculer_pour_post(), Op_Conv_VEF_Face::completer(), Op_Conv_Amont_old_VEF_Face::contribue_au_second_membre(), Op_Conv_VEF_Face::contribue_au_second_membre(), Op_Conv_Amont_old_VEF_Face::dimensionner(), Op_Conv_EF_VEF_P1NC::dimensionner(), Op_Conv_VEF_Face::dimensionner(), Op_Conv_Amont_old_VEF_Face::modifier_pour_Cl(), Op_Conv_EF_VEF_P1NC::modifier_pour_Cl(), Op_Conv_VEF_Face::modifier_pour_Cl(), and Op_Conv_VEF_Face::remplir_fluent().
vitesse_
TRUST_Ref< Champ_Inc_base *> Op_Conv_VEF_base::vitesse_ protected
Referenced by Op_Conv_Amont_old_VEF_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Centre_EF_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_EF_VEF_P1NC::ajouter(), Op_Conv_EF_VEF_P1NC_Stab::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_Muscl_New_VEF_Face::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_Vort_VEF_Face::ajouter(), Op_Conv_Amont_old_VEF_Face::ajouter_contribution(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution(), Op_Conv_DI_L2_VEF_Face::associer_vitesse(), associer_vitesse(), Op_Conv_Muscl_New_VEF_Face::calculer_dt_stab(), Op_Conv_Amont_old_VEF_Face::contribue_au_second_membre(), Op_Conv_DI_L2_VEF_Face::reconst_DI_L2_2d(), Op_Conv_DI_L2_VEF_Face::reconst_DI_L2_3d(), Op_Conv_EF_VEF_P1NC_Stab::remplir_fluent(), Op_Conv_Muscl_New_VEF_Face::remplir_fluent(), and vitesse().
fluent_
DoubleVect Op_Conv_VEF_base::fluent_ mutable protected
Referenced by Op_Conv_Amont_old_VEF_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Centre_EF_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_EF_VEF_P1NC::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_Vort_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::associer(), associer(), calculer_dt_local(), calculer_dt_stab(), calculer_pour_post(), Op_Conv_EF_VEF_P1NC_Stab::remplir_fluent(), Op_Conv_Muscl_New_VEF_Face::remplir_fluent(), and Op_Conv_VEF_Face::remplir_fluent().
jeton
int Op_Conv_VEF_base::jeton = -1 mutable protected
roue
int Op_Conv_VEF_base::roue = -1 mutable protected
Referenced by associer().
faces_entrelaces_Cl_
ArrOfInt Op_Conv_VEF_base::faces_entrelaces_Cl_ mutable protected
Referenced by calculer_dt_stab().