TrioCFD: Assembleur_P_PolyMAC_P0P1NC Class Reference
Assembleur_P_PolyMAC_P0P1NC Class Reference
#include <Assembleur_P_PolyMAC_P0P1NC.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Assembleur_P_PolyMAC
int assembler_QC (const DoubleTab &, Matrice &) override
int assembler_rho_variable (Matrice &, const Champ_Don_base &rho) override
const Type_info * get_info () const override
Public Member Functions inherited from Assembleur_base
virtual int assembler_rho_variable (Matrice &, const Champ_Don_base &rho)
const Type_info * get_info () const override
int set_resoudre_en_u (int flag)
int set_resoudre_increment_pression (int flag)
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Assembleur_P_PolyMAC_P0P1NC()
Assembleur_P_PolyMAC_P0P1NC::Assembleur_P_PolyMAC_P0P1NC ()
~Assembleur_P_PolyMAC_P0P1NC()
Assembleur_P_PolyMAC_P0P1NC::~Assembleur_P_PolyMAC_P0P1NC ()
Member Function Documentation
cree_instance()
Objet_U * Assembleur_P_PolyMAC_P0P1NC::cree_instance () static
taille_memoire()
unsigned Assembleur_P_PolyMAC_P0P1NC::taille_memoire () const override virtual
Reimplemented from Assembleur_P_PolyMAC.
duplique()
int Assembleur_P_PolyMAC_P0P1NC::duplique () const override virtual
Reimplemented from Assembleur_P_PolyMAC.
info()
const Type_info * Assembleur_P_PolyMAC_P0P1NC::info () static
get_info()
const Type_info * Assembleur_P_PolyMAC_P0P1NC::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Assembleur_P_PolyMAC.
self_cast() [1/2]
Assembleur_P_PolyMAC_P0P1NC & Assembleur_P_PolyMAC_P0P1NC::self_cast (Objet_U & r) static
self_cast() [2/2]
const Assembleur_P_PolyMAC_P0P1NC & Assembleur_P_PolyMAC_P0P1NC::self_cast (const Objet_U & r) static
printOn()
Sortie & Assembleur_P_PolyMAC_P0P1NC::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Assembleur_P_PolyMAC.
References Objet_U::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Assembleur_P_PolyMAC_P0P1NC::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Assembleur_P_PolyMAC.
References Assembleur_base::readOn().
Referenced by Assembleur_P_PolyMAC_P0::readOn().
assembler_mat()
int Assembleur_P_PolyMAC_P0P1NC::assembler_mat (Matrice & la_matrice, const DoubleVect & diag, int incr_pression, int resoudre_en_u) override virtual
Reimplemented from Assembleur_P_PolyMAC.
References Matrix_tools::allocate_morse_matrix(), TRUSTTab< _TYPE_, _SIZE_ >::append_line(), Statistiques::begin_count(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Statistiques::end_count(), Assembleur_P_PolyMAC::equation(), Champ_Face_base::fcl(), Matrice_Morse::get_set_coeff(), Matrice_Morse::get_set_tab1(), Matrice_Morse::get_set_tab2(), Assembleur_P_PolyMAC::has_P_ref, Statistiques::last_time(), Assembleur_P_PolyMAC::le_dom_Cl_PolyMAC, Assembleur_P_PolyMAC::le_dom_PolyMAC, Process::me(), Equation_base::milieu(), Assembleur_P_PolyMAC::mon_equation, Milieu_base::porosite_elem(), Milieu_base::porosite_face(), TRUSTVect< _TYPE_, _SIZE_ >::ref_array(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), Matrice_Morse::set_nb_columns(), Assembleur_base::set_resoudre_en_u(), Assembleur_base::set_resoudre_increment_pression(), TRUSTVect< _TYPE_, _SIZE_ >::size(), TRUSTVect< _TYPE_, _SIZE_ >::size_totale(), Assembleur_P_PolyMAC::stencil_done, Assembleur_P_PolyMAC::tab1, Assembleur_P_PolyMAC::tab2, Objet_U_ptr::typer(), TRUST_Deriv< _CLASSE_ >::valeur(), and TRUST_Ref< _CLASSE_ >::valeur().
modifier_secmem()
int Assembleur_P_PolyMAC_P0P1NC::modifier_secmem (DoubleTab &) inline override virtual
Reimplemented from Assembleur_P_PolyMAC.
modifier_solution()
int Assembleur_P_PolyMAC_P0P1NC::modifier_solution (DoubleTab & pression) override virtual
Reimplemented from Assembleur_P_PolyMAC.
References Debog::verifier().
dimensionner_continuite()
void Assembleur_P_PolyMAC_P0P1NC::dimensionner_continuite (matrices_t matrices, int aux_only = 0) const override virtual
Reimplemented from Assembleur_base.
References Matrix_tools::allocate_morse_matrix(), TRUSTTab< _TYPE_, _SIZE_ >::append_line(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Assembleur_P_PolyMAC::equation(), Equation_base::get_champ(), Equation_base::inconnue(), Assembleur_P_PolyMAC::le_dom_PolyMAC, TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Assembleur_P_PolyMAC::mon_equation, TRUST_Ref< _CLASSE_ >::valeur(), Champ_Inc_base::valeurs(), and Champ_Proto::valeurs().
assembler_continuite()
void Assembleur_P_PolyMAC_P0P1NC::assembler_continuite (matrices_t matrices, DoubleTab & secmem, int aux_only = 0) const override virtual
Reimplemented from Assembleur_base.
References Process::abort(), Equation_base::champ_conserve(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Assembleur_P_PolyMAC::equation(), Pb_Multiphase::equation_masse(), Probleme_base::get_champ(), Equation_base::inconnue(), Assembleur_P_PolyMAC::le_dom_Cl_PolyMAC, Assembleur_P_PolyMAC::le_dom_PolyMAC, Equation_base::milieu(), Assembleur_P_PolyMAC::mon_equation, Champ_Inc_base::passe(), Milieu_base::porosite_elem(), Equation_base::probleme(), TRUST_Ref< _CLASSE_ >::valeur(), Champ_Inc_base::valeurs(), and Champ_Proto::valeurs().
norme_continuite()
DoubleTab Assembleur_P_PolyMAC_P0P1NC::norme_continuite () const override virtual
Reimplemented from Assembleur_base.
References Assembleur_P_PolyMAC::equation(), Assembleur_P_PolyMAC::le_dom_PolyMAC, Equation_base::milieu(), and Milieu_base::porosite_elem().
modifier_secmem_pour_incr_p()
void Assembleur_P_PolyMAC_P0P1NC::modifier_secmem_pour_incr_p (const DoubleTab & press, const double fac, DoubleTab & incr) const override virtual
Reimplemented from Assembleur_base.
References Assembleur_P_PolyMAC::equation(), Champ_Face_base::fcl(), Probleme_base::get_champ(), Assembleur_P_PolyMAC::le_dom_Cl_PolyMAC, Assembleur_P_PolyMAC::le_dom_PolyMAC, TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Assembleur_P_PolyMAC::mon_equation, Equation_base::probleme(), TRUST_Ref< _CLASSE_ >::valeur(), and Champ_Proto::valeurs().
corriger_vitesses()
void Assembleur_P_PolyMAC_P0P1NC::corriger_vitesses (const DoubleTab & dP, DoubleTab & dv) const inline override virtual
Reimplemented from Assembleur_P_PolyMAC.
References Process::exit().
Member Data Documentation
info_obj
const Type_info Assembleur_P_PolyMAC_P0P1NC::info_obj static