TrioCFD: Eval_Puiss_Th_QC_VEF_Face_View Class Reference
Eval_Puiss_Th_QC_VEF_Face_View Class Reference
#include <Eval_Puiss_Th_QC_VEF_Face.h>
Member Function Documentation
has_view()
virtual bool Eval_Puiss_Th_QC_VEF_Face_View::has_view () const inline override virtual
Reimplemented from Evaluateur_Source_VEF_Face.
set()
void Eval_Puiss_Th_QC_VEF_Face_View::set (const Eval_Puiss_Th_QC_VEF_Face_View & eval) const inline
References Evaluateur_Source_VEF_Face::face_voisins, TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Eval_Puiss_Th_QC_VEF_Face::nb_faces_elem, Evaluateur_Source_Face::porosite_surf, Eval_Puiss_Th_QC_VEF_Face::tab_puissance, Eval_Puiss_Th_QC_VEF_Face::tab_volumes, TRUSTArray< _TYPE_, _SIZE_ >::view_ro(), TRUSTTab< _TYPE_, _SIZE_ >::view_ro(), Evaluateur_Source_Face::volumes_entrelaces, and Evaluateur_Source_VEF_Face::volumes_entrelaces_Cl.
calculer_terme_source_standard_view()
KOKKOS_INLINE_FUNCTION void Eval_Puiss_Th_QC_VEF_Face_View::calculer_terme_source_standard_view (int num_face, DoubleArrView source) const inline
References Process::Kokkos_exit(), and Eval_Puiss_Th_QC_VEF_Face::nb_faces_elem.
calculer_terme_source_non_standard_view()
KOKKOS_INLINE_FUNCTION void Eval_Puiss_Th_QC_VEF_Face_View::calculer_terme_source_non_standard_view (int num_face, DoubleArrView source) const inline
References Process::Kokkos_exit(), and Eval_Puiss_Th_QC_VEF_Face::nb_faces_elem.