TrioCFD: Probleme_FTD_IJK_cut_cell Class Reference
Probleme_FTD_IJK_cut_cell Class Reference
#include <Probleme_FTD_IJK_cut_cell.h>
Public Member Functions
const Facettes_Interp_FT & get_cut_cell_facettes_interpolation () const
const Type_info * get_info () const override
Public Member Functions inherited from Probleme_FTD_IJK_base
void abortTimeStep () override
int associer_ (Objet_U &) override
void completer () override
double computeTimeStep (bool &stop) const override
void discretiser (Discretisation_base &dis) override
const Type_info * get_info () const override
void initialize () override
bool initTimeStep (double dt) override
bool iterateTimeStep (bool &converged) override
void mettre_a_jour (double temps) override
double presentTime () const override
void resetTime (double time) override
bool run () override
void terminate () override
virtual bool updateGivenFields () override
void validateTimeStep () override
Public Member Functions inherited from Probleme_FT_Disc_gen
int associer_ (Objet_U &ob) override
void associer_milieu_base (const Milieu_base &milieu) override
double calculer_pas_de_temps () const override
void completer () override
const Type_info * get_info () const override
void mettre_a_jour (double temps) override
virtual bool updateGivenFields () override
const Type_info * get_info () const override
Public Member Functions inherited from Probleme_base
void abortTimeStep () override
int associer_ (Objet_U &) override
virtual void associer_domaine (const Domaine &)
virtual void associer_milieu_base (const Milieu_base &)
virtual void associer_sch_tps_base (const Schema_Temps_base &)
virtual double calculer_pas_de_temps () const
virtual void completer ()
double computeTimeStep (bool &stop) const override
const Discretisation_base & discretisation () const
virtual void discretiser (Discretisation_base &)
Domaine & domaine ()
const Domaine & domaine () const
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
Equation_base & equation (const Nom &)
const Equation_base & equation (const Nom &) const
TRUST_Ref< Field_base * > findInputField (const Nom &name) const override
virtual void finir ()
double futureTime () const override
const Type_info * get_info () const override
void getInputFieldsNames (Noms &noms) const override
void getOutputFieldsNames (Noms &noms) const override
virtual void imprimer (Sortie &os) const
void initialize () override
bool initTimeStep (double dt) override
bool isStationary () const override
bool iterateTimeStep (bool &converged) override
int limpr () const override
int lsauv () const override
virtual void mettre_a_jour (double temps)
virtual Milieu_base & milieu ()
virtual const Milieu_base & milieu () const
int postraiter (int force=1) override
double presentTime () const override
int reprendre (Entree &) override
void resetTime (double time) override
int sauvegarder (Sortie &) const override
Schema_Temps_base & schema_temps ()
const Schema_Temps_base & schema_temps () const
void terminate () override
bool updateGivenFields () override
void validateTimeStep () override
virtual int verifier ()
Public Member Functions inherited from Probleme_U
virtual void abortTimeStep ()
virtual double computeTimeStep (bool &stop) const
virtual TRUST_Ref< Field_base * > findInputField (const Nom &name) const
virtual double futureTime () const
const Type_info * get_info () const override
virtual void getInputFieldsNames (Noms &noms) const
virtual void getOutputFieldsNames (Noms &noms) const
virtual void initialize ()
virtual bool initTimeStep (double dt)
virtual bool isStationary () const
virtual bool iterateTimeStep (bool &converged)
const Nom & le_nom () const override
void nommer (const Nom &name) override
virtual int postraiter (int force=1)
virtual double presentTime () const
virtual void resetTime (double time)
virtual bool run ()
virtual bool runUntil (double time)
virtual void terminate ()
virtual bool updateGivenFields ()
virtual void validateTimeStep ()
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
void initialize () override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Public Types inherited from Champs_compris_IJK_interface
using FieldInfo_t = std::tuple< Motcle, Entity, Nature_du_champ, bool >
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Static Protected Member Functions inherited from Probleme_FTD_IJK_base
static void Fill_postprocessable_fields ()
Constructor & Destructor Documentation
Probleme_FTD_IJK_cut_cell()
Probleme_FTD_IJK_cut_cell::Probleme_FTD_IJK_cut_cell ()
~Probleme_FTD_IJK_cut_cell()
Probleme_FTD_IJK_cut_cell::~Probleme_FTD_IJK_cut_cell ()
Member Function Documentation
cree_instance()
Objet_U * Probleme_FTD_IJK_cut_cell::cree_instance () static
taille_memoire()
unsigned Probleme_FTD_IJK_cut_cell::taille_memoire () const override virtual
Reimplemented from Probleme_FT_Disc_gen.
duplique()
int Probleme_FTD_IJK_cut_cell::duplique () const override virtual
Reimplemented from Probleme_FT_Disc_gen.
info()
const Type_info * Probleme_FTD_IJK_cut_cell::info () static
get_info()
const Type_info * Probleme_FTD_IJK_cut_cell::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Probleme_FTD_IJK_base.
self_cast() [1/2]
Probleme_FTD_IJK_cut_cell & Probleme_FTD_IJK_cut_cell::self_cast (Objet_U & r) static
self_cast() [2/2]
const Probleme_FTD_IJK_cut_cell & Probleme_FTD_IJK_cut_cell::self_cast (const Objet_U & r) static
printOn()
Sortie & Probleme_FTD_IJK_cut_cell::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Probleme_FTD_IJK_base.
readOn()
Entree & Probleme_FTD_IJK_cut_cell::readOn (Entree & is) override protected virtual
Lecture d'un probleme dans un flot d'entree, et ouverture du flot de sauvegarde.
Format: { nom_milieu bloc de lecture d'un milieu nom_equation bloc de lecture d'une equation Postraitement bloc de lecture postraitement reprise | sauvegarde | sauvegarde_simple formatte | binaire | pdi nom_de_fichier } L'option sauvegarde_simple permet de sauver le probleme dans le fichier choisi en ecrasant a chaque fois les sauvegardes precedentes : cela permet d'economiser de la place disque.
Parameters
(Entree& is) flot d'entree
Returns
(Entree&) le flot d'entre modifie
Exceptions
pas d'accolade ouvrante en debut de format
mot clef "Postraitement" n'est pas la
format de sauvegarde doit etre "binaire" ou "formatte"
pas d'accolade fermante en fin de jeu de donnee
Reimplemented from Probleme_FTD_IJK_base.
References Probleme_FTD_IJK_base::get_interface(), Schema_Temps_IJK_base::get_timestep_facsec(), Probleme_FTD_IJK_base::readOn(), Probleme_FTD_IJK_base::schema_temps_ijk(), IJK_Interfaces::set_seuil_indicatrice_petite(), seuil_indicatrice_petite_facsec_, and seuil_indicatrice_petite_fixe_.
set_param()
void Probleme_FTD_IJK_cut_cell::set_param (Param & param) override virtual
Reimplemented from Probleme_FTD_IJK_base.
References Param::ajouter(), Param::dictionnaire(), Probleme_FTD_IJK_base::set_param(), seuil_indicatrice_petite_facsec_, seuil_indicatrice_petite_fixe_, and type_surface_efficace_face_.
deplacer_interfaces()
void Probleme_FTD_IJK_cut_cell::deplacer_interfaces (const double timestep, const int rk_step, ArrOfDouble & var_volume_par_bulle, const int first_step_interface_smoothing) override virtual
Reimplemented from Probleme_FTD_IJK_base.
References IJK_Interfaces::calcul_surface_efficace_face(), IJK_Interfaces::calcul_surface_efficace_face_initial(), IJK_Interfaces::calcul_surface_efficace_interface(), IJK_Interfaces::calcul_surface_efficace_interface_initial(), cut_cell_disc_, cut_cell_perform_interpolation_facettes(), Probleme_FTD_IJK_base::deplacer_interfaces(), IJK_Thermals::echange_diph_vers_pure_cellules_finalement_pures(), IJK_Thermals::echange_pure_vers_diph_cellules_initialement_pures(), Probleme_FT_Disc_gen::equations_, TRUST_List< _CLASSE_ >::front(), IJK_Interfaces::get_dt_impression_bilan_indicatrice(), Probleme_FTD_IJK_base::get_ijk_thermals(), Probleme_FTD_IJK_base::get_interface(), Probleme_FTD_IJK_base::has_thermals_, IJK_Interfaces::I(), IJK_Interfaces::imprime_bilan_indicatrice(), IJK_Interfaces::In(), Probleme_FTD_IJK_base::schema_temps_ijk(), type_surface_efficace_face_, type_surface_efficace_interface_, Cut_cell_FT_Disc::update(), Probleme_FTD_IJK_base::update_old_intersections(), TRUST_Deriv< _CLASSE_ >::valeur(), and IJK_Thermals::vide_phase_invalide_cellules_diphasiques().
deplacer_interfaces_rk3()
void Probleme_FTD_IJK_cut_cell::deplacer_interfaces_rk3 (const double timestep, const int rk_step, ArrOfDouble & var_volume_par_bulle) override virtual
Reimplemented from Probleme_FTD_IJK_base.
References IJK_Interfaces::calcul_surface_efficace_face(), IJK_Interfaces::calcul_surface_efficace_face_initial(), IJK_Interfaces::calcul_surface_efficace_interface(), IJK_Interfaces::calcul_surface_efficace_interface_initial(), cut_cell_disc_, cut_cell_perform_interpolation_facettes(), Probleme_FTD_IJK_base::deplacer_interfaces_rk3(), IJK_Thermals::echange_diph_vers_pure_cellules_finalement_pures(), IJK_Thermals::echange_pure_vers_diph_cellules_initialement_pures(), Probleme_FT_Disc_gen::equations_, TRUST_List< _CLASSE_ >::front(), IJK_Interfaces::get_dt_impression_bilan_indicatrice(), Probleme_FTD_IJK_base::get_ijk_thermals(), Probleme_FTD_IJK_base::get_interface(), Probleme_FTD_IJK_base::has_thermals_, IJK_Interfaces::I(), IJK_Interfaces::imprime_bilan_indicatrice(), IJK_Interfaces::In(), Probleme_FTD_IJK_base::schema_temps_ijk(), type_surface_efficace_face_, type_surface_efficace_interface_, Cut_cell_FT_Disc::update(), Probleme_FTD_IJK_base::update_old_intersections(), TRUST_Deriv< _CLASSE_ >::valeur(), and IJK_Thermals::vide_phase_invalide_cellules_diphasiques().
update_indicator_field()
void Probleme_FTD_IJK_cut_cell::update_indicator_field () override virtual
Reimplemented from Probleme_FTD_IJK_base.
References cut_cell_disc_, Probleme_FTD_IJK_base::get_interface(), Cut_cell_FT_Disc::remove_dead_and_virtual_cells(), and Probleme_FTD_IJK_base::update_indicator_field().
Referenced by update_twice_indicator_field().
update_twice_indicator_field()
void Probleme_FTD_IJK_cut_cell::update_twice_indicator_field () override virtual
Reimplemented from Probleme_FTD_IJK_base.
References cut_cell_disc_, cut_cell_facettes_interpolation_, cut_cell_perform_interpolation_facettes(), Facettes_Interp_FT::cut_cell_perform_interpolation_facettes_old(), Probleme_FT_Disc_gen::equations_, TRUST_List< _CLASSE_ >::front(), Probleme_FTD_IJK_base::get_interface(), IJK_Interfaces::I(), IJK_Interfaces::In(), IJK_Interfaces::old(), Cut_cell_FT_Disc::update(), update_indicator_field(), Probleme_FTD_IJK_base::update_old_intersections(), and TRUST_Deriv< _CLASSE_ >::valeur().
get_cut_cell_disc()
Cut_cell_FT_Disc * Probleme_FTD_IJK_cut_cell::get_cut_cell_disc () inline override virtual
Reimplemented from Probleme_FTD_IJK_base.
References cut_cell_disc_.
get_cut_field_velocity()
const Cut_field_vector3_double & Probleme_FTD_IJK_cut_cell::get_cut_field_velocity () const
References Probleme_FT_Disc_gen::equations_, TRUST_List< _CLASSE_ >::front(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by IJK_Interfaces::calculer_var_volume_remaillage().
get_cut_cell_facettes_interpolation()
const Facettes_Interp_FT & Probleme_FTD_IJK_cut_cell::get_cut_cell_facettes_interpolation () const inline
Getter des objets Facettes_Interp_FT, permettant d'acceder aux indices et coefficients des points d'interpolation a une certaine distance des facettes de l'interface
References cut_cell_facettes_interpolation_.
cut_cell_perform_interpolation_facettes()
void Probleme_FTD_IJK_cut_cell::cut_cell_perform_interpolation_facettes () inline
References cut_cell_facettes_interpolation_, Facettes_Interp_FT::cut_cell_perform_interpolation_facettes_next(), and Probleme_FTD_IJK_base::get_interface().
Referenced by deplacer_interfaces(), deplacer_interfaces_rk3(), and update_twice_indicator_field().
initialize()
void Probleme_FTD_IJK_cut_cell::initialize () override protected virtual
This method is called once at the beginning, before any other one of the interface Problem.
Exceptions
WrongContext
Reimplemented from Probleme_FTD_IJK_base.
References IJK_Interfaces::activate_cut_cell(), Postprocessing_IJK::activate_cut_cell(), Facettes_Interp_FT::associer(), IJK_Thermals::compute_ghost_cell_numbers_for_subproblems(), cut_cell_disc_, cut_cell_facettes_interpolation_, IJK_Shear_Periodic_helpler::defilement_, Probleme_FTD_IJK_base::delta_z_local_, Probleme_FTD_IJK_base::domaine_ft_, Probleme_FTD_IJK_base::domaine_ijk_, Domaine_IJK::ELEM, Probleme_FTD_IJK_base::eq_ns(), Probleme_FT_Disc_gen::equations_, TRUST_List< _CLASSE_ >::front(), Navier_Stokes_FTD_IJK::get_boundary_conditions(), Probleme_FTD_IJK_base::get_ijk_thermals(), Probleme_FTD_IJK_base::get_interface(), Probleme_FTD_IJK_base::get_post(), IJK_Thermals::get_probes_ghost_cells(), Navier_Stokes_FTD_IJK::get_velocity(), Probleme_FTD_IJK_base::has_thermals_, Cut_cell_FT_Disc::initialise(), Probleme_FTD_IJK_base::initialize(), IJK_Interfaces::maillage_ft_ijk(), Probleme_U::nommer(), IJK_Interfaces::old_maillage_ft_ijk(), Probleme_FTD_IJK_base::thermal_probes_ghost_cells_, TRUST_Deriv< _CLASSE_ >::valeur(), and TRUST_Ref< _CLASSE_ >::valeur().
Member Data Documentation
info_obj
const Type_info Probleme_FTD_IJK_cut_cell::info_obj static
cut_cell_disc_
Cut_cell_FT_Disc Probleme_FTD_IJK_cut_cell::cut_cell_disc_ protected
Referenced by deplacer_interfaces(), deplacer_interfaces_rk3(), get_cut_cell_disc(), initialize(), update_indicator_field(), and update_twice_indicator_field().
velocity_interface_
DoubleTabFT_cut_cell_vector3 Probleme_FTD_IJK_cut_cell::velocity_interface_ protected
type_surface_efficace_face_
TYPE_SURFACE_EFFICACE_FACE Probleme_FTD_IJK_cut_cell::type_surface_efficace_face_ = TYPE_SURFACE_EFFICACE_FACE::NON_INITIALISE protected
Referenced by deplacer_interfaces(), deplacer_interfaces_rk3(), and set_param().
type_surface_efficace_interface_
TYPE_SURFACE_EFFICACE_INTERFACE Probleme_FTD_IJK_cut_cell::type_surface_efficace_interface_ = TYPE_SURFACE_EFFICACE_INTERFACE::NON_INITIALISE protected
Referenced by deplacer_interfaces(), and deplacer_interfaces_rk3().
seuil_indicatrice_petite_fixe_
double Probleme_FTD_IJK_cut_cell::seuil_indicatrice_petite_fixe_ = -1 protected
Referenced by readOn(), and set_param().
seuil_indicatrice_petite_facsec_
double Probleme_FTD_IJK_cut_cell::seuil_indicatrice_petite_facsec_ = -1 protected
Referenced by readOn(), and set_param().
cut_cell_facettes_interpolation_
Facettes_Interp_FT Probleme_FTD_IJK_cut_cell::cut_cell_facettes_interpolation_ protected
Referenced by cut_cell_perform_interpolation_facettes(), get_cut_cell_facettes_interpolation(), initialize(), and update_twice_indicator_field().