TrioCFD: Evaluateur_Source_VEF_Face Class Reference
Evaluateur_Source_VEF_Face Class Reference
#include <Evaluateur_Source_VEF_Face.h>
Constructor & Destructor Documentation
Evaluateur_Source_VEF_Face() [1/2]
Evaluateur_Source_VEF_Face::Evaluateur_Source_VEF_Face () inline
Evaluateur_Source_VEF_Face() [2/2]
Evaluateur_Source_VEF_Face::Evaluateur_Source_VEF_Face (const Evaluateur_Source_VEF_Face & eval)
References face_voisins, Evaluateur_Source_Face::porosite_surf, TRUSTTab< _TYPE_, _SIZE_ >::ref(), TRUSTVect< _TYPE_, _SIZE_ >::ref(), Evaluateur_Source_Face::volumes_entrelaces, and volumes_entrelaces_Cl.
Member Function Documentation
changer_volumes_entrelaces_Cl()
void Evaluateur_Source_VEF_Face::changer_volumes_entrelaces_Cl (DoubleVect & vol) virtual
References TRUSTVect< _TYPE_, _SIZE_ >::ref(), and volumes_entrelaces_Cl.
completer()
void Evaluateur_Source_VEF_Face::completer () override virtual
Reimplemented from Evaluateur_Source_Face.
References face_voisins, Evaluateur_Source::la_zcl, Evaluateur_Source::le_dom, Evaluateur_Source_Face::porosite_surf, TRUSTTab< _TYPE_, _SIZE_ >::ref(), TRUSTVect< _TYPE_, _SIZE_ >::ref(), TRUST_Ref< _CLASSE_ >::valeur(), Evaluateur_Source_Face::volumes_entrelaces, and volumes_entrelaces_Cl.
Referenced by Eval_Puiss_Th_QC_VEF_Face::completer(), Eval_Puiss_Th_VEF_Face::completer(), and Eval_Source_C_VEF_Face::completer().
calculer_terme_source_standard()
template<typename Type_Double > void Evaluateur_Source_VEF_Face::calculer_terme_source_standard (const int , Type_Double &) const inline
References Process::exit().
calculer_terme_source_non_standard()
template<typename Type_Double > void Evaluateur_Source_VEF_Face::calculer_terme_source_non_standard (const int , Type_Double &) const inline
References Process::exit().
has_view()
virtual bool Evaluateur_Source_VEF_Face::has_view () const inline virtual
Reimplemented in Eval_Puiss_Th_QC_VEF_Face_View, Eval_Puiss_Th_VEF_Face_View, and Eval_Source_C_VEF_Face_View.
calculer_terme_source_standard_view()
void Evaluateur_Source_VEF_Face::calculer_terme_source_standard_view (const int , DoubleArrView) const inline
References Process::Kokkos_exit().
calculer_terme_source_non_standard_view()
void Evaluateur_Source_VEF_Face::calculer_terme_source_non_standard_view (const int , DoubleArrView) const inline
References Process::Kokkos_exit().
Member Data Documentation
volumes_entrelaces_Cl
DoubleVect Evaluateur_Source_VEF_Face::volumes_entrelaces_Cl protected
Referenced by Eval_Darcy_VEF_Face::calculer_terme_source_non_standard(), Eval_Forchheimer_VEF_Face::calculer_terme_source_non_standard(), changer_volumes_entrelaces_Cl(), completer(), Evaluateur_Source_VEF_Face(), Eval_Puiss_Th_QC_VEF_Face_View::set(), Eval_Puiss_Th_VEF_Face_View::set(), and Eval_Source_C_VEF_Face_View::set().
face_voisins
IntTab Evaluateur_Source_VEF_Face::face_voisins protected
Referenced by Eval_Dirac_VEF_Face::calculer_terme_source(), Eval_Puiss_Th_QC_VEF_Face::completer(), Eval_Source_C_VEF_Face::completer(), completer(), Evaluateur_Source_VEF_Face(), Eval_Puiss_Th_QC_VEF_Face_View::set(), Eval_Puiss_Th_VEF_Face_View::set(), and Eval_Source_C_VEF_Face_View::set().