TrioCFD: Echange_global_impose_rayo_semi_transp Class Reference
Echange_global_impose_rayo_semi_transp Class Reference
#include <Echange_global_impose_rayo_semi_transp.h>
Public Member Functions
const Type_info * get_info () const override
void verifie_ch_init_nb_comp () const override
Public Member Functions inherited from Cond_Lim_rayo_semi_transp
virtual void associer_modele (const Modele_rayo_semi_transp &)
Modele_rayo_semi_transp & modele ()
const Modele_rayo_semi_transp & modele () const
Public Member Functions inherited from Echange_global_impose
int compatible_avec_discr (const Discretisation_base &discr) const override
const Type_info * get_info () const override
int initialiser (double temps) override
void mettre_a_jour (double temps) override
Public Member Functions inherited from Echange_impose_base
int a_mettre_a_jour_ss_pas_dt () override
void associer_fr_dis_base (const Frontiere_dis_base &) override
double emissivite (int num) const
double emissivite (int num, int k) const
const Type_info * get_info () const override
virtual double h_imp (int num) const
virtual double h_imp (int num, int k) const
int initialiser (double temps) override
void mettre_a_jour (double) override
virtual Champ_front_base & T_ext ()
virtual double T_ext (int num) const
virtual double T_ext (int num, int k) const
Public Member Functions inherited from Cond_lim_base
virtual int a_mettre_a_jour_ss_pas_dt ()
virtual void associer_domaine_cl_dis_base (const Domaine_Cl_dis_base &)
virtual void associer_fr_dis_base (const Frontiere_dis_base &)
virtual void calculer_coeffs_echange (double temps)
virtual int compatible_avec_discr (const Discretisation_base &) const
Domaine_Cl_dis_base & domaine_Cl_dis ()
const Domaine_Cl_dis_base & domaine_Cl_dis () const
virtual Frontiere_dis_base & frontiere_dis ()
virtual const Frontiere_dis_base & frontiere_dis () const
const Type_info * get_info () const override
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
void set_modifier_val_imp (int)
virtual void verifie_ch_init_nb_comp () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Cond_lim_base
void err_pas_compatible (const Discretisation_base &) const
void err_pas_compatible (const Equation_base &) const
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
uniquement pour une discretisation VDF.
Constructor & Destructor Documentation
Echange_global_impose_rayo_semi_transp()
Echange_global_impose_rayo_semi_transp::Echange_global_impose_rayo_semi_transp ()
~Echange_global_impose_rayo_semi_transp()
Echange_global_impose_rayo_semi_transp::~Echange_global_impose_rayo_semi_transp ()
Member Function Documentation
cree_instance()
Objet_U * Echange_global_impose_rayo_semi_transp::cree_instance () static
taille_memoire()
unsigned Echange_global_impose_rayo_semi_transp::taille_memoire () const override virtual
Reimplemented from Echange_global_impose.
duplique()
int Echange_global_impose_rayo_semi_transp::duplique () const override virtual
Reimplemented from Echange_global_impose.
info()
const Type_info * Echange_global_impose_rayo_semi_transp::info () static
get_info()
const Type_info * Echange_global_impose_rayo_semi_transp::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Echange_global_impose.
self_cast() [1/2]
Echange_global_impose_rayo_semi_transp & Echange_global_impose_rayo_semi_transp::self_cast (Objet_U & r) static
self_cast() [2/2]
const Echange_global_impose_rayo_semi_transp & Echange_global_impose_rayo_semi_transp::self_cast (const Objet_U & r) static
printOn()
Sortie & Echange_global_impose_rayo_semi_transp::printOn (Sortie & os) const override protected virtual
Parameters
(Sortie& os) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Echange_global_impose.
readOn()
Entree & Echange_global_impose_rayo_semi_transp::readOn (Entree & is) override protected virtual
Lecture des parametres de la condition Echange_impose Lecture de l'emissivite de la paroi.
Lecture du coefficient A
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Echange_global_impose.
References Process::exit(), Echange_impose_base::h_imp_, Cond_lim_base::le_champ_front, and Motcles::search().
la_cl()
const Cond_lim_base & Echange_global_impose_rayo_semi_transp::la_cl () const override virtual
Implements Cond_Lim_rayo_semi_transp.
temperature_bord()
Champ_front_base & Echange_global_impose_rayo_semi_transp::temperature_bord ()
References Echange_impose_base::T_ext().
Referenced by Flux_radiatif_VDF::calculer_flux_radiatif(), and Eq_rayo_semi_transp_VDF::evaluer_cl_rayonnement().
calculer_temperature_bord()
void Echange_global_impose_rayo_semi_transp::calculer_temperature_bord (double temps)
Referenced by Eq_rayo_semi_transp_VDF::evaluer_cl_rayonnement().
compatible_avec_eqn()
int Echange_global_impose_rayo_semi_transp::compatible_avec_eqn (const Equation_base &) const inline override virtual
Reimplemented from Cond_lim_base.
completer()
void Echange_global_impose_rayo_semi_transp::completer () override virtual
NE FAIT RIEN A surcharger dans les classes derivees.
Reimplemented from Echange_global_impose.
References Echange_global_impose::completer().
verifie_ch_init_nb_comp()
void Echange_global_impose_rayo_semi_transp::verifie_ch_init_nb_comp () const override virtual
Appel la verification du champ lu par l intermediaire de l equation pour laquelle on considere la condition limite.
La methode est surchargee dans les cas ou l utilisateur doit specifier le champ frontiere
Reimplemented from Cond_lim_base.
References Cond_lim_base::domaine_Cl_dis(), MorEqn::equation(), Equation_base::inconnue(), Cond_lim_base::le_champ_front, Field_base::nb_comp(), Objet_U_ptr::non_nul(), and Equation_base::verifie_ch_init_nb_comp().
Member Data Documentation
info_obj
const Type_info Echange_global_impose_rayo_semi_transp::info_obj static