TrioCFD: Traitement_particulier_NS_THI_VDF Class Reference
Traitement_particulier_NS_THI_VDF Class Reference
#include <Traitement_particulier_NS_THI_VDF.h>
Public Member Functions
const Type_info * get_info () const override
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Protected Member Functions
void calcul_Ec_D (double &, double &)
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
pour les calculs de THI, en particulier initialisation
particuliere et calculs des spectres!!
See also
Navier_Stokes_Turbulent, Traitement_particulier_base,, Traitement_particulier_THI
Constructor & Destructor Documentation
Traitement_particulier_NS_THI_VDF()
Traitement_particulier_NS_THI_VDF::Traitement_particulier_NS_THI_VDF ()
~Traitement_particulier_NS_THI_VDF()
Traitement_particulier_NS_THI_VDF::~Traitement_particulier_NS_THI_VDF ()
Member Function Documentation
cree_instance()
Objet_U * Traitement_particulier_NS_THI_VDF::cree_instance () static
taille_memoire()
unsigned Traitement_particulier_NS_THI_VDF::taille_memoire () const override virtual
Implements Objet_U.
duplique()
int Traitement_particulier_NS_THI_VDF::duplique () const override virtual
Implements Objet_U.
info()
const Type_info * Traitement_particulier_NS_THI_VDF::info () static
get_info()
const Type_info * Traitement_particulier_NS_THI_VDF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Traitement_particulier_NS_THI.
self_cast() [1/2]
Traitement_particulier_NS_THI_VDF & Traitement_particulier_NS_THI_VDF::self_cast (Objet_U & r) static
self_cast() [2/2]
const Traitement_particulier_NS_THI_VDF & Traitement_particulier_NS_THI_VDF::self_cast (const Objet_U & r) static
printOn()
Sortie & Traitement_particulier_NS_THI_VDF::printOn (Sortie & is) const override protected virtual
Parameters
(Sortie& is) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Reimplemented from Traitement_particulier_NS_THI.
readOn()
Entree & Traitement_particulier_NS_THI_VDF::readOn (Entree & is) override protected virtual
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
Reimplemented from Traitement_particulier_NS_THI.
renorm_Ec()
void Traitement_particulier_NS_THI_VDF::renorm_Ec () override protected virtual
Implements Traitement_particulier_NS_THI.
References calcul_Ec_D(), ch_vit_pour_fft(), Objet_U::dimension, Domaine_dis_base::domaine(), Traitement_particulier_NS_THI::Ec_init, Traitement_particulier_NS_THI::fac_init, Traitement_particulier_NS_base::mon_equation, and Traitement_particulier_NS_THI::nb_som_dir.
init_calc_spectre()
void Traitement_particulier_NS_THI_VDF::init_calc_spectre () override protected virtual
Implements Traitement_particulier_NS_THI.
References Traitement_particulier_NS_THI::calcul_nb_som_dir(), ch_vit_pour_fft(), Objet_U::dimension, Domaine_dis_base::domaine(), Traitement_particulier_NS_base::mon_equation, Traitement_particulier_NS_THI::nb_som_dir, and Process::nproc().
calcul_spectre()
void Traitement_particulier_NS_THI_VDF::calcul_spectre () override protected virtual
Implements Traitement_particulier_NS_THI.
References ch_vit_pour_fft(), Objet_U::dimension, Domaine_dis_base::domaine(), Traitement_particulier_NS_base::mon_equation, Traitement_particulier_NS_THI::nb_som_dir, and Process::nproc().
sorties_globales()
void Traitement_particulier_NS_THI_VDF::sorties_globales () override protected virtual
Implements Traitement_particulier_NS_THI.
References calcul_Ec_D(), calcul_skewness_ordre_2(), Process::je_suis_maitre(), and Traitement_particulier_NS_base::mon_equation.
calcul_Ec_D()
void Traitement_particulier_NS_THI_VDF::calcul_Ec_D (double & Ec, double & D) protected
Calcul de Ec = 1/2 < u^2 > D = 1/2 < w^2 > ou w est le rotationnel de u.
x^2 est le produit scalaire x*x < x > est la moyenne sur le volume
< x > = INTEGRALE(x_i d Omega) / INTEGRALE(d Omega) sur Omega sur Omega
References Champ_Face_VDF::calculer_rotationnel_ordre2_centre_element(), Objet_U::dimension, Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Traitement_particulier_NS_base::mon_equation, Process::mp_sum(), and Domaine_VF::volumes().
Referenced by renorm_Ec(), and sorties_globales().
ch_vit_pour_fft()
void Traitement_particulier_NS_THI_VDF::ch_vit_pour_fft (DoubleTab & vit) protected
References Objet_U::dimension, Domaine_dis_base::domaine(), Domaine_VF::face_sommets(), Traitement_particulier_NS_base::mon_equation, Traitement_particulier_NS_THI::msg_erreur_maillage(), Domaine_VF::nb_faces(), Domaine_32_64< _SIZE_ >::nb_som(), Traitement_particulier_NS_THI::nb_som_dir, and Domaine_VDF::orientation().
Referenced by calcul_spectre(), init_calc_spectre(), and renorm_Ec().
ch_vit_pour_fft_operateur()
void Traitement_particulier_NS_THI_VDF::ch_vit_pour_fft_operateur (DoubleTab & u, DoubleTab & vit) protected
References Objet_U::dimension, Domaine_dis_base::domaine(), Domaine_VF::face_sommets(), Traitement_particulier_NS_base::mon_equation, Traitement_particulier_NS_THI::msg_erreur_maillage(), Domaine_VF::nb_faces(), Domaine_32_64< _SIZE_ >::nb_som(), Traitement_particulier_NS_THI::nb_som_dir, and Domaine_VDF::orientation().
Referenced by calcul_spectre_operateur().
calcul_spectre_operateur()
void Traitement_particulier_NS_THI_VDF::calcul_spectre_operateur (int nb_op, DoubleTab & u, DoubleTab & u_av, double dt) override protected virtual
Implements Traitement_particulier_NS_THI.
References Traitement_particulier_NS_THI::calcul_nb_som_dir(), ch_vit_pour_fft_operateur(), Objet_U::dimension, Domaine_dis_base::domaine(), Traitement_particulier_NS_base::mon_equation, Domaine_VF::nb_faces(), Traitement_particulier_NS_THI::nb_som_dir, and Domaine_VF::volumes_entrelaces().
calcul_skewness_ordre_2()
void Traitement_particulier_NS_THI_VDF::calcul_skewness_ordre_2 (double & Skewness) protected
References Process::check_int_overflow(), Objet_U::dimension, Domaine_VDF::dist_face(), Domaine_VF::elem_faces(), Periodique::face_associee(), Domaine_VF::face_voisins(), Cond_lim_base::frontiere_dis(), Domaine_Cl_dis_base::les_conditions_limites(), Traitement_particulier_NS_base::mon_equation, Process::mp_sum(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), Domaine_VDF::orientation(), Domaine_VF::premiere_face_int(), and TRUST_Deriv< _CLASSE_ >::valeur().
Referenced by sorties_globales().
Member Data Documentation
info_obj
const Type_info Traitement_particulier_NS_THI_VDF::info_obj static