TrioCFD: OpConvQuickIJKScalar_double Class Reference
OpConvQuickIJKScalar_double Class Reference
#include <OpConvQuickIJKScalar.h>
Public Member Functions
const Type_info * get_info () const override
Public Member Functions inherited from Operateur_IJK_elem_conv_base_double
const Type_info * get_info () const override
const Type_info * get_info () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Operateur_IJK_elem_conv_base_double
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
~OpConvQuickIJKScalar_double()
OpConvQuickIJKScalar_double::~OpConvQuickIJKScalar_double ()
OpConvQuickIJKScalar_double()
OpConvQuickIJKScalar_double::OpConvQuickIJKScalar_double () inline
Member Function Documentation
cree_instance()
Objet_U * OpConvQuickIJKScalar_double::cree_instance () static
taille_memoire()
unsigned OpConvQuickIJKScalar_double::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in OpConvQuickIJKScalar_cut_cell_double, OpConvQuickInterfaceIJKScalar_double, OpConvQuickInterfaceOnefluidIJKScalar_double, OpGradQuickIJKScalar_double, and OpGradFluxQuickIJKScalar_double.
duplique()
int OpConvQuickIJKScalar_double::duplique () const override virtual
Implements Objet_U.
Reimplemented in OpConvQuickIJKScalar_cut_cell_double, OpConvQuickInterfaceIJKScalar_double, OpConvQuickInterfaceOnefluidIJKScalar_double, OpGradQuickIJKScalar_double, and OpGradFluxQuickIJKScalar_double.
info()
const Type_info * OpConvQuickIJKScalar_double::info () static
get_info()
const Type_info * OpConvQuickIJKScalar_double::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
(const Type_info*) structure regroupant les informations sur le type de l'Objet_U
Reimplemented from Objet_U.
Reimplemented in OpConvQuickIJKScalar_cut_cell_double, OpConvQuickInterfaceIJKScalar_double, OpConvQuickInterfaceOnefluidIJKScalar_double, OpGradQuickIJKScalar_double, and OpGradFluxQuickIJKScalar_double.
self_cast() [1/2]
OpConvQuickIJKScalar_double & OpConvQuickIJKScalar_double::self_cast (Objet_U & r) static
self_cast() [2/2]
const OpConvQuickIJKScalar_double & OpConvQuickIJKScalar_double::self_cast (const Objet_U & r) static
printOn()
Sortie & OpConvQuickIJKScalar_double::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
Reimplemented in OpConvQuickIJKScalar_cut_cell_double, OpConvQuickInterfaceIJKScalar_double, OpConvQuickInterfaceOnefluidIJKScalar_double, OpGradQuickIJKScalar_double, and OpGradFluxQuickIJKScalar_double.
Referenced by OpConvQuickInterfaceIJKScalar_double::printOn(), and OpConvQuickInterfaceOnefluidIJKScalar_double::printOn().
readOn()
Entree & OpConvQuickIJKScalar_double::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
Reimplemented in OpConvQuickIJKScalar_cut_cell_double, OpConvQuickInterfaceIJKScalar_double, OpConvQuickInterfaceOnefluidIJKScalar_double, OpGradQuickIJKScalar_double, and OpGradFluxQuickIJKScalar_double.
Referenced by OpConvQuickInterfaceIJKScalar_double::readOn(), and OpConvQuickInterfaceOnefluidIJKScalar_double::readOn().
compute_flux_x()
void OpConvQuickIJKScalar_double::compute_flux_x (IJK_Field_local_double & resu, const int k_layer) inline override protected virtual
Implements Operateur_IJK_elem_base_double.
Reimplemented in OpConvQuickIJKScalar_cut_cell_double.
compute_flux_y()
void OpConvQuickIJKScalar_double::compute_flux_y (IJK_Field_local_double & resu, const int k_layer) inline override protected virtual
Implements Operateur_IJK_elem_base_double.
Reimplemented in OpConvQuickIJKScalar_cut_cell_double.
compute_flux_z()
void OpConvQuickIJKScalar_double::compute_flux_z (IJK_Field_local_double & resu, const int k_layer) inline override protected virtual
Implements Operateur_IJK_elem_base_double.
Reimplemented in OpConvQuickIJKScalar_cut_cell_double.
Member Data Documentation
info_obj
const Type_info OpConvQuickIJKScalar_double::info_obj static