TrioCFD: Source_Transport_proto Struct Reference
Source_Transport_proto Struct Reference
#include <Source_Transport_proto.h>
Constructor & Destructor Documentation
Source_Transport_proto() [1/2]
Source_Transport_proto::Source_Transport_proto () inline protected
Source_Transport_proto() [2/2]
Source_Transport_proto::Source_Transport_proto (double cs1, double cs2) inline protected
Member Function Documentation
readOn_proto()
Entree & Source_Transport_proto::readOn_proto (Entree & is, const Nom & nom) protected
References Param::ajouter(), C1, C2, and Param::lire_avec_accolades().
Referenced by Source_Transport_K_Omega_VDF_Elem_base::readOn(), Source_Transport_VDF_Elem_base::readOn(), Source_Transport_K_Omega_VEF_Face_base::readOn(), and Source_Transport_VEF_Face_base::readOn().
readOn_nothing()
Entree & Source_Transport_proto::readOn_nothing (Entree & is, const Nom & nom) protected
References Param::lire_avec_accolades().
Referenced by Source_Transport_K_aniso_therm_concen_VDF_Elem::readOn(), Source_Transport_K_anisotherme_VDF_Elem::readOn(), Source_Transport_K_concen_VDF_Elem::readOn(), Source_Transport_K_Realisable_aniso_concen_VDF_Elem::readOn(), Source_Transport_K_Realisable_aniso_therm_concen_VDF_Elem::readOn(), Source_Transport_K_Realisable_anisotherme_VDF_Elem::readOn(), Source_Transport_K_Realisable_VDF_Elem::readOn(), Source_Transport_K_VDF_Elem::readOn(), Source_Transport_K_aniso_concen_VEF_Face::readOn(), Source_Transport_K_aniso_therm_concen_VEF_Face::readOn(), Source_Transport_K_anisotherme_VEF_Face::readOn(), Source_Transport_K_Realisable_aniso_concen_VEF_Face::readOn(), Source_Transport_K_Realisable_aniso_therm_concen_VEF_Face::readOn(), Source_Transport_K_Realisable_anisotherme_VEF_Face::readOn(), Source_Transport_K_Realisable_VEF_Face::readOn(), and Source_Transport_K_VEF_Face::readOn().
readOn_anisotherme()
Entree & Source_Transport_proto::readOn_anisotherme (Entree & is, const Nom & nom) protected
References Param::ajouter(), C1, C2, C3, and Param::lire_avec_accolades().
Referenced by Source_Transport_Eps_anisotherme_VDF_Elem::readOn(), Source_Transport_K_Eps_anisotherme_VDF_Elem::readOn(), Source_Transport_K_KEps_anisotherme_VDF_Elem::readOn(), Source_Transport_Eps_anisotherme_VEF_Face::readOn(), Source_Transport_K_Eps_anisotherme_VEF_Face::readOn(), readOn_anisotherme_concen(), and readOn_concen().
readOn_concen()
Entree & Source_Transport_proto::readOn_concen (Entree & is, const Nom & nom) protected
References readOn_anisotherme().
Referenced by Source_Transport_Eps_concen_VDF_Elem::readOn(), Source_Transport_K_Eps_concen_VDF_Elem::readOn(), Source_Transport_Eps_aniso_concen_VEF_Face::readOn(), and Source_Transport_K_Eps_aniso_concen_VEF_Face::readOn().
readOn_anisotherme_concen()
Entree & Source_Transport_proto::readOn_anisotherme_concen (Entree & is, const Nom & nom) protected
References readOn_anisotherme().
Referenced by Source_Transport_Eps_aniso_therm_concen_VDF_Elem::readOn(), Source_Transport_K_Eps_aniso_therm_concen_VDF_Elem::readOn(), Source_Transport_Eps_aniso_therm_concen_VEF_Face::readOn(), and Source_Transport_K_Eps_aniso_therm_concen_VEF_Face::readOn().
readOn_real()
Entree & Source_Transport_proto::readOn_real (Entree & is, const Nom & nom) protected
References _coefficient_limiteur, _interpolation_viscosite_turbulente, Param::ajouter(), C2, Process::exit(), and Param::lire_avec_accolades().
Referenced by Source_Transport_Realisable_VDF_Elem_base::readOn(), and Source_Transport_Realisable_VEF_Face_base::readOn().
readOn_anisotherme_real()
Entree & Source_Transport_proto::readOn_anisotherme_real (Entree & is, const Nom & nom) protected
References Param::ajouter(), C2, C3, and Param::lire_avec_accolades().
Referenced by Source_Transport_Eps_Realisable_anisotherme_VDF_Elem::readOn(), Source_Transport_K_Eps_Realisable_anisotherme_VDF_Elem::readOn(), Source_Transport_Eps_Realisable_anisotherme_VEF_Face::readOn(), Source_Transport_K_Eps_Realisable_anisotherme_VEF_Face::readOn(), readOn_anisotherme_concen_real(), and readOn_concen_real().
readOn_concen_real()
Entree & Source_Transport_proto::readOn_concen_real (Entree & is, const Nom & nom) protected
References readOn_anisotherme_real().
Referenced by Source_Transport_Eps_Realisable_aniso_concen_VDF_Elem::readOn(), Source_Transport_K_Eps_Realisable_aniso_concen_VDF_Elem::readOn(), Source_Transport_Eps_Realisable_aniso_concen_VEF_Face::readOn(), and Source_Transport_K_Eps_Realisable_aniso_concen_VEF_Face::readOn().
readOn_anisotherme_concen_real()
Entree & Source_Transport_proto::readOn_anisotherme_concen_real (Entree & is, const Nom & nom) protected
References readOn_anisotherme_real().
Referenced by Source_Transport_Eps_Realisable_aniso_therm_concen_VDF_Elem::readOn(), Source_Transport_K_Eps_Realisable_aniso_therm_concen_VDF_Elem::readOn(), Source_Transport_Eps_Realisable_aniso_therm_concen_VEF_Face::readOn(), and Source_Transport_K_Eps_Realisable_aniso_therm_concen_VEF_Face::readOn().
verifier_pb_keps()
void Source_Transport_proto::verifier_pb_keps (const Probleme_base & pb, const Nom & nom) protected
References Objet_U::que_suis_je().
Referenced by Source_Transport_Eps_VDF_Elem::readOn(), Source_Transport_K_VDF_Elem::readOn(), Source_Transport_K_Eps_VDF_Elem::readOn(), Source_Transport_Eps_VEF_Face::readOn(), Source_Transport_K_VEF_Face::readOn(), and Source_Transport_K_Eps_VEF_Face::readOn().
verifier_pb_keps_anisotherme()
void Source_Transport_proto::verifier_pb_keps_anisotherme (const Probleme_base & pb, const Nom & nom) protected
References Objet_U::que_suis_je().
Referenced by Source_Transport_Eps_anisotherme_VDF_Elem::readOn(), Source_Transport_K_anisotherme_VDF_Elem::readOn(), Source_Transport_K_Eps_anisotherme_VDF_Elem::readOn(), Source_Transport_Eps_anisotherme_VEF_Face::readOn(), Source_Transport_K_anisotherme_VEF_Face::readOn(), and Source_Transport_K_Eps_anisotherme_VEF_Face::readOn().
verifier_pb_keps_concen()
void Source_Transport_proto::verifier_pb_keps_concen (const Probleme_base & pb, const Nom & nom) protected
References Objet_U::que_suis_je().
Referenced by Source_Transport_Eps_concen_VDF_Elem::readOn(), Source_Transport_K_concen_VDF_Elem::readOn(), Source_Transport_K_Eps_concen_VDF_Elem::readOn(), Source_Transport_Eps_aniso_concen_VEF_Face::readOn(), Source_Transport_K_aniso_concen_VEF_Face::readOn(), and Source_Transport_K_Eps_aniso_concen_VEF_Face::readOn().
verifier_pb_keps_anisotherme_concen()
void Source_Transport_proto::verifier_pb_keps_anisotherme_concen (const Probleme_base & pb, const Nom & nom) protected
References Objet_U::que_suis_je().
Referenced by Source_Transport_Eps_aniso_therm_concen_VDF_Elem::readOn(), Source_Transport_K_aniso_therm_concen_VDF_Elem::readOn(), Source_Transport_K_Eps_aniso_therm_concen_VDF_Elem::readOn(), Source_Transport_Eps_aniso_therm_concen_VEF_Face::readOn(), Source_Transport_K_aniso_therm_concen_VEF_Face::readOn(), and Source_Transport_K_Eps_aniso_therm_concen_VEF_Face::readOn().
verifier_pb_komega()
void Source_Transport_proto::verifier_pb_komega (const Probleme_base & pb, const Nom & nom) protected
References Process::exit().
Referenced by Source_Transport_K_Omega_VDF_Elem::readOn(), and Source_Transport_K_Omega_VEF_Face::readOn().
verifier_milieu_anisotherme()
void Source_Transport_proto::verifier_milieu_anisotherme (const Probleme_base & pb, const Nom & nom) protected
References Probleme_base::equation(), Equation_base::milieu(), Probleme_base::nombre_d_equations(), and Objet_U::que_suis_je().
Referenced by Source_Transport_Eps_anisotherme_VDF_Elem::associer_pb(), Source_Transport_Eps_Realisable_anisotherme_VDF_Elem::associer_pb(), Source_Transport_K_anisotherme_VDF_Elem::associer_pb(), Source_Transport_K_Realisable_anisotherme_VDF_Elem::associer_pb(), Source_Transport_K_Eps_anisotherme_VDF_Elem::associer_pb(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_VDF_Elem::associer_pb(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_W_VDF_Elem::associer_pb(), Source_Transport_K_Eps_Realisable_anisotherme_VDF_Elem::associer_pb(), Source_Transport_Eps_anisotherme_VEF_Face::associer_pb(), Source_Transport_Eps_Realisable_anisotherme_VEF_Face::associer_pb(), Source_Transport_K_anisotherme_VEF_Face::associer_pb(), Source_Transport_K_Realisable_anisotherme_VEF_Face::associer_pb(), Source_Transport_K_Eps_anisotherme_VEF_Face::associer_pb(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_VEF_Face::associer_pb(), and Source_Transport_K_Eps_Realisable_anisotherme_VEF_Face::associer_pb().
verifier_milieu_concen()
void Source_Transport_proto::verifier_milieu_concen (const Probleme_base & pb, const Nom & nom) protected
References Probleme_base::equation(), Equation_base::milieu(), Probleme_base::nombre_d_equations(), and Objet_U::que_suis_je().
Referenced by Source_Transport_Eps_concen_VDF_Elem::associer_pb(), Source_Transport_Eps_Realisable_aniso_concen_VDF_Elem::associer_pb(), Source_Transport_K_concen_VDF_Elem::associer_pb(), Source_Transport_K_Realisable_aniso_concen_VDF_Elem::associer_pb(), Source_Transport_K_Eps_concen_VDF_Elem::associer_pb(), Source_Transport_K_Eps_Realisable_aniso_concen_VDF_Elem::associer_pb(), Source_Transport_Eps_aniso_concen_VEF_Face::associer_pb(), Source_Transport_Eps_Realisable_aniso_concen_VEF_Face::associer_pb(), Source_Transport_K_aniso_concen_VEF_Face::associer_pb(), Source_Transport_K_Realisable_aniso_concen_VEF_Face::associer_pb(), Source_Transport_K_Eps_aniso_concen_VEF_Face::associer_pb(), and Source_Transport_K_Eps_Realisable_aniso_concen_VEF_Face::associer_pb().
verifier_milieu_anisotherme_concen()
void Source_Transport_proto::verifier_milieu_anisotherme_concen (const Probleme_base & pb, const Nom & nom) protected
References Probleme_base::equation(), Equation_base::milieu(), Probleme_base::nombre_d_equations(), and Objet_U::que_suis_je().
Referenced by Source_Transport_Eps_aniso_therm_concen_VDF_Elem::associer_pb(), Source_Transport_Eps_Realisable_aniso_therm_concen_VDF_Elem::associer_pb(), Source_Transport_K_aniso_therm_concen_VDF_Elem::associer_pb(), Source_Transport_K_Realisable_aniso_therm_concen_VDF_Elem::associer_pb(), Source_Transport_K_Eps_aniso_therm_concen_VDF_Elem::associer_pb(), Source_Transport_K_Eps_Bas_Reynolds_aniso_therm_concen_VDF_Elem::associer_pb(), Source_Transport_K_Eps_Realisable_aniso_therm_concen_VDF_Elem::associer_pb(), Source_Transport_Eps_aniso_therm_concen_VEF_Face::associer_pb(), Source_Transport_Eps_Realisable_aniso_therm_concen_VEF_Face::associer_pb(), Source_Transport_K_aniso_therm_concen_VEF_Face::associer_pb(), Source_Transport_K_Realisable_aniso_therm_concen_VEF_Face::associer_pb(), Source_Transport_K_Eps_aniso_therm_concen_VEF_Face::associer_pb(), and Source_Transport_K_Eps_Realisable_aniso_therm_concen_VEF_Face::associer_pb().
verifier_beta_concen()
void Source_Transport_proto::verifier_beta_concen (const Fluide_base & fluide) protected
References Process::exit(), and Fluide_base::has_beta_c().
Referenced by associer_pb_anisotherme_concen(), and associer_pb_concen().
associer_pb_proto()
void Source_Transport_proto::associer_pb_proto (const Probleme_base & pb) protected
References eq_hydraulique, and Probleme_base::equation().
Referenced by Source_Transport_K_Omega_VDF_Elem_base::associer_pb(), Source_Transport_VDF_Elem_base::associer_pb(), Source_Transport_K_Omega_VEF_Face_base::associer_pb(), and Source_Transport_VEF_Face_base::associer_pb().
associer_pb_anisotherme()
void Source_Transport_proto::associer_pb_anisotherme (const Probleme_base & pb) protected
References beta_t, Milieu_base::beta_t(), eq_thermique, Probleme_base::equation(), gravite, Milieu_base::gravite(), and Equation_base::milieu().
Referenced by Source_Transport_Eps_anisotherme_VDF_Elem::associer_pb(), Source_Transport_Eps_Realisable_anisotherme_VDF_Elem::associer_pb(), Source_Transport_K_anisotherme_VDF_Elem::associer_pb(), Source_Transport_K_Realisable_anisotherme_VDF_Elem::associer_pb(), Source_Transport_K_Eps_anisotherme_VDF_Elem::associer_pb(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_VDF_Elem::associer_pb(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_W_VDF_Elem::associer_pb(), Source_Transport_K_Eps_Realisable_anisotherme_VDF_Elem::associer_pb(), Source_Transport_K_KEps_anisotherme_VDF_Elem::associer_pb(), Source_Transport_Eps_anisotherme_VEF_Face::associer_pb(), Source_Transport_Eps_Realisable_anisotherme_VEF_Face::associer_pb(), Source_Transport_K_anisotherme_VEF_Face::associer_pb(), Source_Transport_K_Realisable_anisotherme_VEF_Face::associer_pb(), Source_Transport_K_Eps_anisotherme_VEF_Face::associer_pb(), and Source_Transport_K_Eps_Realisable_anisotherme_VEF_Face::associer_pb().
associer_pb_concen()
void Source_Transport_proto::associer_pb_concen (const Probleme_base & pb) protected
References beta_c, Fluide_base::beta_c(), eq_concentration, Probleme_base::equation(), gravite, Milieu_base::gravite(), Equation_base::milieu(), and verifier_beta_concen().
Referenced by Source_Transport_Eps_concen_VDF_Elem::associer_pb(), Source_Transport_Eps_Realisable_aniso_concen_VDF_Elem::associer_pb(), Source_Transport_K_concen_VDF_Elem::associer_pb(), Source_Transport_K_Realisable_aniso_concen_VDF_Elem::associer_pb(), Source_Transport_K_Eps_concen_VDF_Elem::associer_pb(), Source_Transport_K_Eps_Realisable_aniso_concen_VDF_Elem::associer_pb(), Source_Transport_Eps_aniso_concen_VEF_Face::associer_pb(), Source_Transport_Eps_Realisable_aniso_concen_VEF_Face::associer_pb(), Source_Transport_K_aniso_concen_VEF_Face::associer_pb(), Source_Transport_K_Realisable_aniso_concen_VEF_Face::associer_pb(), Source_Transport_K_Eps_aniso_concen_VEF_Face::associer_pb(), and Source_Transport_K_Eps_Realisable_aniso_concen_VEF_Face::associer_pb().
associer_pb_anisotherme_concen()
void Source_Transport_proto::associer_pb_anisotherme_concen (const Probleme_base & pb) protected
References beta_c, Fluide_base::beta_c(), beta_t, Milieu_base::beta_t(), eq_concentration, eq_thermique, Probleme_base::equation(), gravite, Milieu_base::gravite(), Equation_base::milieu(), and verifier_beta_concen().
Referenced by Source_Transport_Eps_aniso_therm_concen_VDF_Elem::associer_pb(), Source_Transport_Eps_Realisable_aniso_therm_concen_VDF_Elem::associer_pb(), Source_Transport_K_aniso_therm_concen_VDF_Elem::associer_pb(), Source_Transport_K_Realisable_aniso_therm_concen_VDF_Elem::associer_pb(), Source_Transport_K_Eps_aniso_therm_concen_VDF_Elem::associer_pb(), Source_Transport_K_Eps_Bas_Reynolds_aniso_therm_concen_VDF_Elem::associer_pb(), Source_Transport_K_Eps_Realisable_aniso_therm_concen_VDF_Elem::associer_pb(), Source_Transport_Eps_aniso_therm_concen_VEF_Face::associer_pb(), Source_Transport_Eps_Realisable_aniso_therm_concen_VEF_Face::associer_pb(), Source_Transport_K_aniso_therm_concen_VEF_Face::associer_pb(), Source_Transport_K_Realisable_aniso_therm_concen_VEF_Face::associer_pb(), Source_Transport_K_Eps_aniso_therm_concen_VEF_Face::associer_pb(), and Source_Transport_K_Eps_Realisable_aniso_therm_concen_VEF_Face::associer_pb().
Member Data Documentation
C1__
constexpr double Source_Transport_proto::C1__ = 1.44 static constexpr protected
C2__
constexpr double Source_Transport_proto::C2__ = 1.92 static protected
C3__
constexpr double Source_Transport_proto::C3__ = 1.0 static protected
C21_R__
constexpr double Source_Transport_proto::C21_R__ = 1.9 static constexpr protected
C3_R__
constexpr double Source_Transport_proto::C3_R__ = 1.0 static protected
C11__
constexpr double Source_Transport_proto::C11__ = 1.55 static constexpr protected
C21__
constexpr double Source_Transport_proto::C21__ = 2. static protected
interpolation_viscosite_turbulente__
constexpr int Source_Transport_proto::interpolation_viscosite_turbulente__ = 0 static constexpr protected
coefficient_limiteur__
constexpr double Source_Transport_proto::coefficient_limiteur__ = 1. static constexpr protected
C1
double Source_Transport_proto::C1 = C1__ protected
Referenced by Source_Transport_K_Eps_Bas_Reynolds_anisotherme_VEF_Face::ajouter(), Source_Transport_K_Eps_Bas_Reynolds_VEF_Face::ajouter(), Source_Transport_K_Eps_Bas_Reynolds_aniso_therm_concen_VDF_Elem::ajouter_blocs(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_VDF_Elem::ajouter_blocs(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_QC_VDF_Elem::ajouter_blocs(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_W_VDF_Elem::ajouter_blocs(), Source_Transport_K_KEps_VDF_Elem::ajouter_blocs(), readOn_anisotherme(), readOn_proto(), and Source_Transport_K_Eps_Bas_Reynolds_anisotherme_QC_VDF_Elem::Source_Transport_K_Eps_Bas_Reynolds_anisotherme_QC_VDF_Elem().
C2
double Source_Transport_proto::C2 = C2__ protected
Referenced by Source_Transport_K_Eps_Bas_Reynolds_anisotherme_VEF_Face::ajouter(), Source_Transport_K_Eps_Bas_Reynolds_VEF_Face::ajouter(), Source_Transport_Eps_VDF_Elem::ajouter_blocs(), Source_Transport_K_Eps_Bas_Reynolds_aniso_therm_concen_VDF_Elem::ajouter_blocs(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_VDF_Elem::ajouter_blocs(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_QC_VDF_Elem::ajouter_blocs(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_W_VDF_Elem::ajouter_blocs(), Source_Transport_K_Eps_VDF_Elem::ajouter_blocs(), Source_Transport_K_KEps_VDF_Elem::ajouter_blocs(), Source_Transport_K_Eps_VEF_Face::contribuer_a_avec(), readOn_anisotherme(), readOn_anisotherme_real(), readOn_proto(), readOn_real(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_QC_VDF_Elem::Source_Transport_K_Eps_Bas_Reynolds_anisotherme_QC_VDF_Elem(), Source_Transport_Realisable_VDF_Elem_base::Source_Transport_Realisable_VDF_Elem_base(), and Source_Transport_Realisable_VEF_Face_base::Source_Transport_Realisable_VEF_Face_base().
C3
double Source_Transport_proto::C3 = C3__ protected
Referenced by readOn_anisotherme(), readOn_anisotherme_real(), Source_Transport_Eps_aniso_concen_VEF_Face::Source_Transport_Eps_aniso_concen_VEF_Face(), Source_Transport_Eps_aniso_therm_concen_VDF_Elem::Source_Transport_Eps_aniso_therm_concen_VDF_Elem(), Source_Transport_Eps_aniso_therm_concen_VEF_Face::Source_Transport_Eps_aniso_therm_concen_VEF_Face(), Source_Transport_Eps_anisotherme_VDF_Elem::Source_Transport_Eps_anisotherme_VDF_Elem(), Source_Transport_Eps_anisotherme_VEF_Face::Source_Transport_Eps_anisotherme_VEF_Face(), Source_Transport_Eps_concen_VDF_Elem::Source_Transport_Eps_concen_VDF_Elem(), Source_Transport_Eps_Realisable_aniso_concen_VDF_Elem::Source_Transport_Eps_Realisable_aniso_concen_VDF_Elem(), Source_Transport_Eps_Realisable_aniso_concen_VEF_Face::Source_Transport_Eps_Realisable_aniso_concen_VEF_Face(), Source_Transport_Eps_Realisable_aniso_therm_concen_VDF_Elem::Source_Transport_Eps_Realisable_aniso_therm_concen_VDF_Elem(), Source_Transport_Eps_Realisable_aniso_therm_concen_VEF_Face::Source_Transport_Eps_Realisable_aniso_therm_concen_VEF_Face(), Source_Transport_Eps_Realisable_anisotherme_VDF_Elem::Source_Transport_Eps_Realisable_anisotherme_VDF_Elem(), Source_Transport_Eps_Realisable_anisotherme_VEF_Face::Source_Transport_Eps_Realisable_anisotherme_VEF_Face(), Source_Transport_K_Eps_aniso_concen_VEF_Face::Source_Transport_K_Eps_aniso_concen_VEF_Face(), Source_Transport_K_Eps_aniso_therm_concen_VDF_Elem::Source_Transport_K_Eps_aniso_therm_concen_VDF_Elem(), Source_Transport_K_Eps_aniso_therm_concen_VEF_Face::Source_Transport_K_Eps_aniso_therm_concen_VEF_Face(), Source_Transport_K_Eps_anisotherme_VDF_Elem::Source_Transport_K_Eps_anisotherme_VDF_Elem(), Source_Transport_K_Eps_anisotherme_VEF_Face::Source_Transport_K_Eps_anisotherme_VEF_Face(), Source_Transport_K_Eps_concen_VDF_Elem::Source_Transport_K_Eps_concen_VDF_Elem(), Source_Transport_K_Eps_Realisable_aniso_concen_VDF_Elem::Source_Transport_K_Eps_Realisable_aniso_concen_VDF_Elem(), Source_Transport_K_Eps_Realisable_aniso_concen_VEF_Face::Source_Transport_K_Eps_Realisable_aniso_concen_VEF_Face(), Source_Transport_K_Eps_Realisable_aniso_therm_concen_VDF_Elem::Source_Transport_K_Eps_Realisable_aniso_therm_concen_VDF_Elem(), Source_Transport_K_Eps_Realisable_aniso_therm_concen_VEF_Face::Source_Transport_K_Eps_Realisable_aniso_therm_concen_VEF_Face(), Source_Transport_K_Eps_Realisable_anisotherme_VDF_Elem::Source_Transport_K_Eps_Realisable_anisotherme_VDF_Elem(), Source_Transport_K_Eps_Realisable_anisotherme_VEF_Face::Source_Transport_K_Eps_Realisable_anisotherme_VEF_Face(), and Source_Transport_K_KEps_anisotherme_VDF_Elem::Source_Transport_K_KEps_anisotherme_VDF_Elem().
_interpolation_viscosite_turbulente
int Source_Transport_proto::_interpolation_viscosite_turbulente = interpolation_viscosite_turbulente__ protected
Referenced by Source_Transport_K_Realisable_VEF_Face::ajouter(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_VEF_Face::ajouter(), Source_Transport_K_Eps_Bas_Reynolds_VEF_Face::ajouter(), Source_Transport_VEF_Face_base::ajouter_keps(), Source_Transport_K_Omega_VEF_Face_base::ajouter_komega(), Source_Transport_K_Omega_VEF_Face::contribuer_a_avec(), and readOn_real().
_coefficient_limiteur
double Source_Transport_proto::_coefficient_limiteur = coefficient_limiteur__ protected
Referenced by Source_Transport_K_Realisable_VEF_Face::ajouter(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_VEF_Face::ajouter(), Source_Transport_K_Eps_Bas_Reynolds_VEF_Face::ajouter(), Source_Transport_VEF_Face_base::ajouter_keps(), Source_Transport_K_Omega_VEF_Face_base::ajouter_komega(), Source_Transport_K_Omega_VEF_Face::contribuer_a_avec(), and readOn_real().
beta_t
TRUST_Ref< Champ_Don_base *> Source_Transport_proto::beta_t protected
Referenced by Source_Transport_K_Eps_Bas_Reynolds_anisotherme_VEF_Face::ajouter(), Source_Transport_VDF_Elem_base::ajouter_anisotherme(), Source_Transport_VEF_Face_base::ajouter_anisotherme(), Source_Transport_VDF_Elem_base::ajouter_anisotherme_concen(), Source_Transport_VEF_Face_base::ajouter_anisotherme_concen(), Source_Transport_K_Eps_Bas_Reynolds_aniso_therm_concen_VDF_Elem::ajouter_blocs(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_VDF_Elem::ajouter_blocs(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_W_VDF_Elem::ajouter_blocs(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_VEF_Face::associer_pb(), associer_pb_anisotherme(), associer_pb_anisotherme_concen(), and Source_Transport_K_Eps_Bas_Reynolds_anisotherme_W_VDF_Elem::calculer_u_teta_W().
beta_c
TRUST_Ref< Champ_Don_base *> Source_Transport_proto::beta_c protected
Referenced by Source_Transport_VDF_Elem_base::ajouter_anisotherme_concen(), Source_Transport_VEF_Face_base::ajouter_anisotherme_concen(), Source_Transport_K_Eps_Bas_Reynolds_aniso_therm_concen_VDF_Elem::ajouter_blocs(), Source_Transport_VDF_Elem_base::ajouter_concen(), Source_Transport_VEF_Face_base::ajouter_concen(), associer_pb_anisotherme_concen(), and associer_pb_concen().
gravite
TRUST_Ref< Champ_Don_base *> Source_Transport_proto::gravite protected
Referenced by Source_Transport_K_Eps_Bas_Reynolds_anisotherme_VEF_Face::ajouter(), Source_Transport_VDF_Elem_base::ajouter_anisotherme(), Source_Transport_VEF_Face_base::ajouter_anisotherme(), Source_Transport_VDF_Elem_base::ajouter_anisotherme_concen(), Source_Transport_VEF_Face_base::ajouter_anisotherme_concen(), Source_Transport_K_Eps_Bas_Reynolds_aniso_therm_concen_VDF_Elem::ajouter_blocs(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_VDF_Elem::ajouter_blocs(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_W_VDF_Elem::ajouter_blocs(), Source_Transport_VDF_Elem_base::ajouter_concen(), Source_Transport_VEF_Face_base::ajouter_concen(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_VDF_Elem::associer_pb(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_VEF_Face::associer_pb(), associer_pb_anisotherme(), associer_pb_anisotherme_concen(), associer_pb_concen(), and Source_Transport_K_Eps_Bas_Reynolds_anisotherme_W_VDF_Elem::calculer_u_teta_W().
eq_hydraulique
TRUST_Ref< Equation_base *> Source_Transport_proto::eq_hydraulique protected
Referenced by Source_Transport_K_Realisable_VEF_Face::ajouter(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_VEF_Face::ajouter(), Source_Transport_K_Eps_Bas_Reynolds_VEF_Face::ajouter(), Source_Transport_Bas_Reynolds_VDF_Elem_base::ajouter_blocs(), Source_Transport_Realisable_VDF_Elem_base::ajouter_blocs(), Source_Transport_K_Realisable_VDF_Elem::ajouter_blocs(), Source_Transport_K_Eps_Bas_Reynolds_aniso_therm_concen_VDF_Elem::ajouter_blocs(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_VDF_Elem::ajouter_blocs(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_QC_VDF_Elem::ajouter_blocs(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_W_VDF_Elem::ajouter_blocs(), Source_Transport_K_KEps_VDF_Elem::ajouter_blocs(), Source_Transport_VDF_Elem_base::ajouter_keps(), Source_Transport_VEF_Face_base::ajouter_keps(), Source_Transport_Realisable_VDF_Elem_base::ajouter_keps_real(), Source_Transport_Realisable_VEF_Face_base::ajouter_keps_real(), Source_Transport_K_Omega_VDF_Elem_base::ajouter_komega(), Source_Transport_K_Omega_VEF_Face_base::ajouter_komega(), associer_pb_proto(), Source_Transport_Realisable_VEF_Face_base::contribuer_a_avec(), Source_Transport_K_Omega_VEF_Face::contribuer_a_avec(), Source_Transport_Eps_Realisable_VDF_Elem::mettre_a_jour(), Source_Transport_K_Realisable_VDF_Elem::mettre_a_jour(), Source_Transport_K_Eps_Realisable_VDF_Elem::mettre_a_jour(), Source_Transport_Eps_Realisable_VEF_Face::mettre_a_jour(), Source_Transport_K_Realisable_VEF_Face::mettre_a_jour(), and Source_Transport_K_Eps_Realisable_VEF_Face::mettre_a_jour().
eq_thermique
TRUST_Ref< Convection_Diffusion_Temperature *> Source_Transport_proto::eq_thermique protected
Referenced by Source_Transport_K_Eps_Bas_Reynolds_anisotherme_VEF_Face::ajouter(), Source_Transport_VDF_Elem_base::ajouter_anisotherme(), Source_Transport_VEF_Face_base::ajouter_anisotherme(), Source_Transport_VDF_Elem_base::ajouter_anisotherme_concen(), Source_Transport_VEF_Face_base::ajouter_anisotherme_concen(), Source_Transport_K_Eps_Bas_Reynolds_aniso_therm_concen_VDF_Elem::ajouter_blocs(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_VDF_Elem::ajouter_blocs(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_W_VDF_Elem::ajouter_blocs(), Source_Transport_K_Eps_Bas_Reynolds_anisotherme_VEF_Face::associer_pb(), associer_pb_anisotherme(), and associer_pb_anisotherme_concen().
eq_concentration
TRUST_Ref< Convection_Diffusion_Concentration *> Source_Transport_proto::eq_concentration protected
Referenced by Source_Transport_VDF_Elem_base::ajouter_anisotherme_concen(), Source_Transport_VEF_Face_base::ajouter_anisotherme_concen(), Source_Transport_K_Eps_Bas_Reynolds_aniso_therm_concen_VDF_Elem::ajouter_blocs(), Source_Transport_VDF_Elem_base::ajouter_concen(), Source_Transport_VEF_Face_base::ajouter_concen(), associer_pb_anisotherme_concen(), and associer_pb_concen().