TrioCFD: Matrice_Morse_View Struct Reference
Matrice_Morse_View Struct Reference
#include <Matrice_Morse.h>
Member Function Documentation
set()
void Matrice_Morse_View::set (Matrice_Morse & matrice) inline
References coeff_v, Matrice_Morse::get_set_coeff(), Matrice_Morse::get_symmetric(), Matrice_Morse::get_tab1(), Matrice_Morse::get_tab2(), Matrice_Morse::sorted_, sorted_, symetrique_, tab1_v, tab2_v, TRUSTArray< _TYPE_, _SIZE_ >::view_ro(), and TRUSTArray< _TYPE_, _SIZE_ >::view_rw().
Referenced by Op_Diff_VEF_Face::ajouter_contribution(), and Op_Diff_VEF_Face::ajouter_contribution_multi_scalaire().
operator()()
KOKKOS_INLINE_FUNCTION double & Matrice_Morse_View::operator() (int i, int j) const inline
References coeff_v, Process::Kokkos_exit(), symetrique_, and tab1_v.
atomic_add()
KOKKOS_INLINE_FUNCTION void Matrice_Morse_View::atomic_add (int i, int j, double coeff) const inline
References add().
Referenced by Op_Diff_VEF_Face::ajouter_contribution(), and Op_Diff_VEF_Face::ajouter_contribution_multi_scalaire().
add()
KOKKOS_INLINE_FUNCTION void Matrice_Morse_View::add (int i, int j, double coeff, bool atomic = false) const inline
References coeff_v, Process::Kokkos_exit(), symetrique_, tab1_v, and tab2_v.
Referenced by atomic_add().
Member Data Documentation
tab1_v
CIntArrView Matrice_Morse_View::tab1_v
Referenced by add(), operator()(), and set().
tab2_v
CIntArrView Matrice_Morse_View::tab2_v
Referenced by add(), and set().
coeff_v
DoubleArrView Matrice_Morse_View::coeff_v mutable
Referenced by add(), operator()(), and set().
symetrique_
int Matrice_Morse_View::symetrique_ = 0
Referenced by add(), operator()(), and set().
sorted_
int Matrice_Morse_View::sorted_ = 0
Referenced by set().