# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# build is entirely overriden to only download the artifact from github
build:
  os: "ubuntu-24.04"
  tools:
    python: "3.12"
  commands:
    - python ./rtd/download_github_artifact.py

