# coding = utf-8

# Configuration file for the Sphinx documentation builder.
# For a full options list, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

import sys
import os
import shutil
from datetime import datetime

import DoxygenToRST

from urllib.request import urlretrieve
import tarfile


print(sys.argv)

# -- Generate RST from Doxygen XML -------------------------------------------
print("Building RST from Doxygen")






doxygen_build_path="./srcs/developer_guide/doxygen"


CLEAN_DOXYGEN=(os.environ.get("CLEAN_DOXYGEN", "0")!="0") # true if CLEAN_DOXYGEN env var is set to anything other than "0"
if CLEAN_DOXYGEN:
    print("Cleaning doxygen related files")
    shutil.rmtree(f"{doxygen_build_path}/xml")
    shutil.rmtree(f"{doxygen_build_path}/html")
    shutil.rmtree(f"{doxygen_build_path}/rst")
else:
    print("Keeping doxygen related files (if they exist)")


# Download doxygen outputs from last release
version="v1.9.6"
print(f"Downloading doxygen data from {version}")

xml_url=f"https://github.com/cea-trust-platform/TrioCFD-code/releases/download/{version}/doxygen_xml_{version}.tar.gz"
xml_path=f"{doxygen_build_path}/doxygen_xml_{version}.tar.gz"

html_url=f"https://github.com/cea-trust-platform/TrioCFD-code/releases/download/{version}/doxygen_html_{version}.tar.gz"
html_path=f"{doxygen_build_path}/doxygen_html_{version}.tar.gz"


if not os.path.exists(f"{doxygen_build_path}/xml"):
    print("Download and extract xml:", xml_url)
    urlretrieve(xml_url, xml_path)
    with tarfile.open(xml_path) as tar:
        tar.extractall(path="./srcs/developer_guide/doxygen")


if not os.path.exists(f"{doxygen_build_path}/html"):
    print("Download and extract html:", html_url)
    urlretrieve(html_url, html_path)
    with tarfile.open(html_path) as tar:
        tar.extractall(path="./srcs/developer_guide/doxygen")



DoxygenToRST.run(input="./srcs/developer_guide/doxygen/xml",
                output="./srcs/developer_guide/doxygen/rst",
                keeprst=not(CLEAN_DOXYGEN))




# -- Project information -----------------------------------------------------

project = 'TrioCFD'
author = 'The TrioCFD team'
copyright = f'{datetime.now().year}, CEA'

# -- General configuration ---------------------------------------------------

# Extension modules
pygments_style = 'sphinx'
extensions = [
    'sphinx.ext.autodoc',           # Include documentation from docstrings
    'sphinx.ext.intersphinx',       # Allows linking to documentation of other projects.
    'sphinx.ext.coverage',          # Generates coverage reports for your documentation.
    'sphinx.ext.doctest',           # Allows you to test snippets of code embedded in your documentation.
    'sphinx.ext.autosummary',       # Automatically generates summary tables for modules, classes, and functions.
    'sphinx.ext.graphviz',          # Enables the inclusion of Graphviz diagrams in your documentation.
    'sphinx.ext.ifconfig',          # Allows conditional inclusion of content based on configuration values.
    'sphinx_copybutton',            # add copy button on code blocks
    # Stopped using autosectionlabel because it causes problems with doyxgen. also changing titles is a pain, I rather set fixed targets to each titles
    # 'sphinx.ext.autosectionlabel',  # Automatically adds section labels to all sections.
    'sphinx.ext.napoleon',          # Support for Google style docstrings
    'sphinxcontrib.bibtex',         # To manage citations with bibtex
    'myst_parser',                  # Allows you to use Markdown in your Sphinx documentation.
    'sphinx_design'                 # For dropdown
]

autosectionlabel_prefix_document = True


myst_enable_extensions = ["dollarmath", "amsmath", "colon_fence",]
myst_heading_anchors = 1


extlinks = {
    'github': ('https://github.com/cea-trust-platform/trust-code/%s', 'GitHub: %s'),
    'trust': ('https://trust-platform.org/%s', 'TRUST: %s'),
}

htmlhelp_basename = 'TrioCFD Documentation'
bibtex_bibfiles = ['bibliography.bib']

# To show or not private members
autodoc_default_options = {"members": True,
                           "undoc-members": True,
                           "private-members": False}


# generate autosummary even if no references
# numpydoc_show_class_members = False
# autosummary_generate = False
# autosummary_imported_members = False

# Figure numerotation
numfig = True
numfig_secnum_depth = 2
numfig_format = {
    'figure': 'Figure %s',
    'table': 'Table %s',
    'code-block': 'Code %s',
}

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The master toctree document
master_doc = 'index'

# Language for content autogenerated by Sphinx
language = "en"

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#

# html_theme = 'sphinx_rtd_theme'
html_theme = 'sphinx_book_theme'


html_logo = "images/tcfd.png"
html_favicon = "images/tcfd.png"

html_theme_options = {
    "show_toc_level": 2,
    "navigation_depth": 1,
    "collapse_navigation": True, 
    "navigation_with_keys": True,  
    "show_navbar_depth": 1,
    "show_prev_next": False,
    "home_page_in_toc": True,
    # "announcement": (
    #     "Welcome to the new TrioCFD documentation !"
    # ),
    "repository_url": "https://github.com/cea-trust-platform/triocfd-code",
    "repository_branch": "master",
    "use_repository_button": True,
    "use_edit_page_button": False,  # True si tu veux permettre l'édition directe
    "use_issues_button": True,      # True pour afficher un lien vers les issues
    "use_download_button": True,    # True pour permettre le téléchargement
    # Search and content options
    "use_sidenotes": True,          # Pour de meilleures annotations
    "show_toc_level": 2,           # Profondeur d'affichage dans la TOC
    "max_navbar_depth": 3,
}


# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]

html_js_files = ["highlight.js"]
html_css_files = ['custom.css']

# To avoid cache error
suppress_warnings = ["config.cache"]

# To allow mardown pages
source_suffix = {'.rst': 'restructuredtext', '.md': 'markdown'}
