# coding = utf-8

# Configuration file for the Sphinx documentation builder.
# For a full options list, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

import sys
import os
from datetime import datetime

sys.path.insert(0, os.path.abspath('..'))

# -- Project information -----------------------------------------------------

project = 'TrioCFD'
author = 'TrioCFD'
copyright = f'{datetime.now().year}, CEA'

# -- General configuration ---------------------------------------------------

# Extension modules
pygments_style = 'sphinx'
extensions = [
    'sphinx.ext.autodoc',           # Include documentation from docstrings
    'sphinx.ext.intersphinx',       # Allows linking to documentation of other projects.
    'sphinx.ext.coverage',          # Generates coverage reports for your documentation.
    'sphinx.ext.doctest',           # Allows you to test snippets of code embedded in your documentation.
    'sphinx.ext.autosummary',       # Automatically generates summary tables for modules, classes, and functions.
    'sphinx.ext.graphviz',          # Enables the inclusion of Graphviz diagrams in your documentation.
    'sphinx.ext.ifconfig',          # Allows conditional inclusion of content based on configuration values.
    'sphinx.ext.autosectionlabel',  # Automatically adds section labels to all sections.
    'sphinx.ext.napoleon',          # Support for Google style docstrings
    'myst_parser'                   # Allows you to use Markdown in your Sphinx documentation.
]

htmlhelp_basename = 'TrioCFD_Documentation'

# To show or not private members
autodoc_default_options = {"members": True,
                           "undoc-members": True,
                           "private-members": False}


# generate autosummary even if no references
# numpydoc_show_class_members = False
# autosummary_generate = False
# autosummary_imported_members = False

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The master toctree document
master_doc = 'index'

# Language for content autogenerated by Sphinx
language = "en"

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = 'sphinx_material'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = []

# To avoid cache error
suppress_warnings = ["config.cache"]

# To allow mardown pages
source_suffix = {'.rst': 'restructuredtext', '.md': 'markdown'}
