# coding = utf-8

# Configuration file for the Sphinx documentation builder.
# For a full options list, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

import sys
import os
from datetime import datetime

sys.path.insert(0, os.path.abspath('..'))

# -- Project information -----------------------------------------------------

project = 'TrioCFD'
author = 'The TrioCFD team'
copyright = f'{datetime.now().year}, CEA'

# -- General configuration ---------------------------------------------------

# Extension modules
pygments_style = 'sphinx'
extensions = [
    'sphinx.ext.autodoc',           # Include documentation from docstrings
    'sphinx.ext.intersphinx',       # Allows linking to documentation of other projects.
    'sphinx.ext.coverage',          # Generates coverage reports for your documentation.
    'sphinx.ext.doctest',           # Allows you to test snippets of code embedded in your documentation.
    'sphinx.ext.autosummary',       # Automatically generates summary tables for modules, classes, and functions.
    'sphinx.ext.graphviz',          # Enables the inclusion of Graphviz diagrams in your documentation.
    'sphinx.ext.ifconfig',          # Allows conditional inclusion of content based on configuration values.
    'sphinx_copybutton',            # add copy button on code blocks
    # Stopped using autosectionlabel because it causes problems with doyxgen. also changing titles is a pain, I rather set fixed targets to each titles
    # 'sphinx.ext.autosectionlabel',  # Automatically adds section labels to all sections.
    'sphinx.ext.napoleon',          # Support for Google style docstrings
    'sphinxcontrib.bibtex',         # To manage citations with bibtex
    'myst_parser',                  # Allows you to use Markdown in your Sphinx documentation.
    'sphinx_design'                 # For dropdown
]

autosectionlabel_prefix_document = True


myst_enable_extensions = ["dollarmath", "amsmath", "colon_fence",]
myst_heading_anchors = 1
htmlhelp_basename = 'TrioCFD'
bibtex_bibfiles = ['bibliography.bib']

# To show or not private members
autodoc_default_options = {"members": True,
                           "undoc-members": True,
                           "private-members": False}


# generate autosummary even if no references
# numpydoc_show_class_members = False
# autosummary_generate = False
# autosummary_imported_members = False

# Figure numerotation
numfig = True
numfig_format = {
    'code-block': 'Listing %s',
    'figure': 'Fig. %s',
    'section': 'Section',
    'table': 'Table %s',
}

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The master toctree document
master_doc = 'index'

# Language for content autogenerated by Sphinx
language = "en"

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#

# html_theme = 'sphinx_rtd_theme'
html_theme = 'sphinx_book_theme'


html_logo = "images/tcfd.png"
html_favicon = "images/tcfd.png"

html_theme_options = {
    "home_page_in_toc": True,
    "announcement": (
        "Welcome to the new TrioCFD documentation !"
    ),
    "repository_url": "https://github.com/cea-trust-platform/triocfd-documentation",
    "use_repository_button": True,
}


# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]

html_js_files = ["highlight.js"]

# To avoid cache error
suppress_warnings = ["config.cache"]

# To allow mardown pages
source_suffix = {'.rst': 'restructuredtext', '.md': 'markdown'}
