#!/bin/bash


# aims to fix malformation of the all.rst generated by trust
# some problems may have to be fixed manually (linebreaks during bullet list for example)

# replace words ending in undescore with \_, otherwise considered as hyperlink by sphinx
sed -i  -e "s/Ogden_alpha_/Ogden_alpha\\\_/g" \
        -e "s/Ogden_mu_/Ogden_mu\\\_/g" \
        -e "s/phase0_/phase0\\\_/g" \
        -e "s/phase1_/phase1\\\_/g" \
        -e "s/nb_diam_upstream_/nb_diam_upstream\\\_/g" \
        -e "s/\[A_ i \]/\[A_i \]/g" \
        ./all.rst

# asterisks used to indicate product
sed -i  -e "s/\*24/\\\*24/g" \
        -e "s/of\*40/of\\\*40/g" \
        -e "s/\*g\./\\\*g\./g" \
        -e "s/\*.decoupage_som/\\\*.decoupage_som/g" \
        ./all.rst

# characters indicating norms (used for substitution of terms in rst)
sed -i  -e "s/|/\\\|/g" \
        ./all.rst
        
# append objet_u documentation, as it is not create from the base code (but referenced by the doc of Read keyword)
sed -i '1s/^/\n.. _objet_u:\n\n\*\*Objet_u\*\*\n===================================\n\nThe base class from which all TRUST Keywords are derived.\n\n/' ./all.rst